### ISSUE TITLE
What is the replacement for ILiquidTemplateEventHandler in 1.0.0?

### ISSUE THREAD

**Issue by mattcrossmarc** [OrchardCMS/OrchardCore#10000]
The ILiquidTemplateEventHandler is no longer available in OrchardCore v1.0.0. I'm currently using this to add values to the local scope that can be obtained in Liquid pages.

For example, an implementation of ILiquidTemplateEventHandler could be used like this prior to 1.0.0:

```
public async Task RenderingAsync(TemplateContext context)
{
    context.LocalScope.SetValue("SomeValue", FluidValue.Create(_someValue));
}
```

And then SomeValue could be referenced in a Liquid page, like this:

```
{% assign someValue = SomeValue %}
```
What is the correct way to do this in v1.0.0?

Thanks for your help

**Comment by sebastienros** [comment]
You can register customer property resolvers in a Startup class like this:

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Alias/Startup.cs#L29-L56

**Comment by mattcrossmarc** [comment]
Thanks for the quick reply. I'm not seeing that property accessors are invoked when using Liquid syntax like either of these:

```
{% assign someValue = SomeValue %}
```
or

```
{{ SomeValue }}
```

Is there some other syntax that needs to be used in Liquid for retrieving values from these registered property accessors?

**Comment by vpellichero** [comment]
I have exactly the same issue, could someone tells me why my code isn't called when I put `{{ MyTag }}` in the liquid file?

**Comment by jtkech** [comment]
When an object instance was added and then available from a Liquid scope, to access its properties you have to register the related type on which you can also define custom prop accessors.

    o.MemberAccessStrategy.Register<SomeType>();

Here, it is not directly related to an object of a given type, in fact we add for you in the Liquid scope a wrapped LiquidContentAccessor object named "Content", you can do the same with another name.

    o.Scope.SetValue("Content", new ObjectValue(new LiquidContentAccessor()));

On which we can register a LiquidPropertyAccessor, in your case named "SomeValue", just to be able to run code when in the Liquid syntax we access a pseudo property of the above pseudo object.

    o.MemberAccessStrategy.Register<LiquidContentAccessor, LiquidPropertyAccessor>("Alias", (obj, context) =>

So, in your case the right Liquid syntax would be {{ Content.SomeValue }}
