### ISSUE TITLE
LiquidToHtmlAsync no longer resolves model properties as of v1.0.0

### ISSUE THREAD

**Issue by mattcrossmarc** [OrchardCMS/OrchardCore#10005]
I've been using IOrchardHelper.LiquidToHtmlAsync within a custom controller to generate HTML from a Liquid template, using data from a provided model. However, as of v1.0.0, properties accessed from the model within the template are no longer resolved. The provided model can be converted to JSON and successfully written to the HTML body, showing that the values are present in the model, but property access is not resulting in a value being returned.

Here is an example model:

```
public class ContactViewModel
{
    public string Name { get; set; }

    public string Email { get; set; }

    public string Message { get; set; }

    public string VerifyContact { get; set; }
}
```

Below is an example Liquid template that uses this model:

```
{{ Model | json }}

<p>
    Name: {{ Model.Name }}<br />
    Email: {{ Model.Email }}
</p>
<p>
    Message:<br />
    {{ Model.Message }}
</p>
```

Below is an example call to LiquidToHtmlAsync using this template:

```
var model = new ContactViewModel { Name = "John Doe", Email = "john@example.com", Message = "Hello" };

using (var sb = StringBuilderPool.GetInstance())
{
  using var sw = new StringWriter(sb.Builder);
  IHtmlContent htmlContent = await _orchardHelper.LiquidToHtmlAsync((string)contactEmailContent.Content.LiquidPart.Liquid, model);
  htmlContent.WriteTo(sw, HtmlEncoder.Default);
  body = sw.ToString();
}
```

And here is the resulting content in v1.0.0:
```
{&quot;Name&quot;:&quot;John Doe&quot;,&quot;Email&quot;:&quot;john@example.com&quot;,&quot;Message&quot;:&quot;Hello&quot;,&quot;VerifyContact&quot;:null}

<p>
    Name: <br />
    Email: 
</p>
<p>
    Message:<br />
    
</p>
```

In rc2 and prior, the property values were returned as expected. Is this a supported scenario in v1.0.0? If not, is there an alternate way to accomplish this in v1.0.0?

**Comment by mattcrossmarc** [comment]
Hi @sebastienros, it looks like this change in behavior was a result of changes to Fluid in v2. I'm able to get Fluid to correctly bind model properties by explicitly registering the view model's type with the DefaultMemberAccessStrategy, like this:

context.Options.MemberAccessStrategy.Register(viewModel.GetType());

Is this expected as a required step in Fluid v2 or is there another way to get Fluid to auto-register model types?

**Comment by sebastienros** [comment]
This is expected, yes. Ideally we should pass the object directly as the "model" to Fluid which would then let you access `Name` directly, without registering the class, instead of `Model.Name`. But since we want to keep some similarities with Razor templates we use the `Model` property to wrap the actual model object.

**Comment by mattcrossmarc** [comment]
Thanks. Given that, what is the right way to have OrchardCore register the model type with Fluid when using IOrchardHelper.LiquidToHtmlAsync, if any?

```
IHtmlContent htmlContent = await _orchardHelper.LiquidToHtmlAsync((string)contactEmailContent.Content.LiquidPart.Liquid, model);
```

**Comment by mattcrossmarc** [comment]
Ok, got it sorted. Model types used for binding in Liquid templates need to be registered when configuring TemplateOptions, such as below:

```
services.Configure<TemplateOptions>(o =>
{
    o.MemberAccessStrategy.Register<ContactViewModel>();
});
```
