### ISSUE TITLE
Exception Value cannot be null or empty. (Parameter 'areaName')

### ISSUE THREAD

**Issue by omarhassani** [OrchardCMS/OrchardCore#10017]
### To Reproduce
1. Use OrchardCore.Samples - https://github.com/OrchardCMS/OrchardCore.Samples
2. Replace ConfigureServices with this code in Startup.cs

```C#
            services.AddMvc(options => options.EnableEndpointRouting = false);
            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
            .AddAzureAD(options => Configuration.Bind("AzureAd", options));
            services.AddOrchardCore().AddMvc().ConfigureServices(t =>
            {
                t.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                    .AddAzureAD(options => Configuration.Bind("AzureAd", options));
            });

            services.AddRazorPages().AddMvcOptions(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });
```

3. In appsettings.json add this section, please use your Azure AAD details:

```JSON
"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<yourdomain>.onmicrosoft.com",
    "TenantId": "<yourTenantId>",
    "ClientId": "<yourClientId>",
    "CallbackPath": "/signin-oidc"
  },
```

4. Now try acceding to localhost:port/Module2/hello and you will see the error
![image](https://user-images.githubusercontent.com/46158478/127863943-30155814-76e5-4062-baf3-02010a1fa01b.png)
5. I've tried with removing these two lines, because there already existe in the orchard config:
```C#
            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
            .AddAzureAD(options => Configuration.Bind("AzureAd", options));
```
But, it show the folowing error:
![image](https://user-images.githubusercontent.com/46158478/127864616-14a04359-a97a-40e0-b03a-e7b05af03e89.png)

Could you help please

**Comment by Skrypt** [comment]
This is an issue with how you register these services. Could be the order or because you are not taking in consideration that we register these services on each tenants somewhere else.
