### ISSUE TITLE
Content group shape is rendered with empty contents when using grouping shapes

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#10027]
I am using placement files to group the editor shapes into cards and columns as described here : 

https://docs.orchardcore.net/en/latest/docs/reference/core/Placement/#supported-groupings

But when I arrange all field and part shapes into cards and columns the content card shape renders, regardless of if it has shapes or not, as shown below :

![image](https://user-images.githubusercontent.com/1516981/128149409-361cc8cb-e1b9-4fb9-9496-19e599f097a5.png)

Looking into the CardGrouping Shape that takes care of the grouping it seems that it creates the ContentGrouping shape  with child shapes  (that are empty)  causing the card to render.

![image](https://user-images.githubusercontent.com/1516981/128149385-f900c209-a246-4205-b051-9a7ac7635e4d.png)

So is there a way to not render grouping shapes that are empty ?

@deanmarcussen

**Comment by deanmarcussen** [comment]
There is always a Content shape by default. It's necesary for the arrangement.

**Comment by giannik** [comment]
Yes @deanmarcussen  I can understand that. 
So I quess a quick solution would be to use javascript to remove the empty card from the dom ??
thanks.

**Comment by Skrypt** [comment]
The driver sets the GroupId so there is definitely a "Content" shape created every time. This "Content" shape doesn't know if there is any child shape to render yet so ... javascript is probably the quickest solution for you now.

**Comment by giannik** [comment]
thanks guys.. javascript it is.
