### ISSUE TITLE
Pick multiple image sizes and automatically generate srcset

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#10050]
### Is your feature request related to a problem? Please describe.
When you have multiple sizes of the same image per different resolutions you need to specify `srcset` attribute

### Describe the solution you'd like
Image picker allows to select many image sizes per image container and choose their multipliers.
It provides a property that automatically returns `srcset` value.

``` HTM
<img srcset="cupcake.png 1x, cupcake@2x.png 2x, cupcake@3x.png 3x" src="cupcake.png"> 
```

**Comment by sebastienros** [comment]
Can you already do it in your template by using the field's image, and then create the srcset as you need by using the tag helper or liquid filter to generate the media transformation url?

**Comment by xperiandri** [comment]
The main point is that the image picker in the admin panel UI does not allow selection of multiple images. Having that functionality will simplify the solution very much.

**Comment by xperiandri** [comment]
Rendering is not an issue at all

**Comment by deanmarcussen** [comment]
change the settings for the media field to allow multiples

**Comment by sebastienros** [comment]
> the image picker in the admin panel UI does not allow selection of multiple images

Did @deanmarcussen 's suggestion work for you?
