### ISSUE TITLE
Add site settings deployment for audit trail content type settings

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#10086]
Add site settings deployment for audit trail content type settings

And update the new google analytics site setting to take advantage of the new extension methods

/cc @Piedone because I didn't get to it before it got merged

**Comment by Piedone** [comment]
Did you mean Google Tag Manager site settings? That's the one that already has a deployment step and follows the old pattern. (Though it doesn't show up under Deployment Steps because `DeploymentStartup` is not being called for some reason.) Though we could add steps for the other features too.

**Comment by Piedone** [comment]
Opened a PR for it.
