### ISSUE TITLE
Media Library CreateSubdirectory Error

### ISSUE THREAD

**Issue by Yuexs** [OrchardCMS/OrchardCore#1009]
[FileSystemStore.cs](https://github.com/OrchardCMS/OrchardCore/blob/master/src/OrchardCore/OrchardCore.StorageProviders.FileSystem/FileSystemStore.cs)

        public Task<bool> TryCreateFolderAsync(string subpath)
        {
            try
            {
                // Use CreateSubdirectory to ensure the directory doesn't go over its boundaries
                new DirectoryInfo(_localPath).CreateSubdirectory(subpath);
                return Task.FromResult(true);
            }
            catch
            {
                return Task.FromResult(false);
            }
        }

new DirectoryInfo(_localPath).CreateSubdirectory(subpath);

If there is a "/" symbol on the front end of the string, an exception is thrown.

The specified path. This cannot be a different disk volume or Universal Naming Convention (UNC) name.

I modify the code below to be normal.

        public Task<bool> TryCreateFolderAsync(string subpath)
        {
            try
            {
                // Use CreateSubdirectory to ensure the directory doesn't go over its boundaries
                new DirectoryInfo(_localPath).CreateSubdirectory(subpath.StartsWith("/") ? subpath.Remove(0, 1) : subpath);
                return Task.FromResult(true);
            }
            catch
            {
                return Task.FromResult(false);
            }
        }

**Comment by agriffard** [comment]
Thank you. I didn't see it when I made #1050.

I fixed it in OrchardCore\AdminController.cs passing newpath.TrimStart('/') but it should may be done in TryCreateFolderAsync() as you suggest.
