### ISSUE TITLE
Cors module bug while deleting any origin

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#10104]
Add 2 hosts to origin and try to delete first
the second from the list deleted instead first.

![image](https://user-images.githubusercontent.com/61165619/129150367-e804b984-c7fb-4c08-b3d5-217e698b3b76.png)

![image](https://user-images.githubusercontent.com/61165619/129150416-da30085e-82ab-4d93-9c88-7ff18c3b4e53.png)

**Comment by sebastienros** [comment]
Do you feel like you could try fixing it? Might be an array index issue.

**Comment by Skrypt** [comment]
This UI would need some ❤️ 
I listed the missing bits on the original PR.
