### ISSUE TITLE
Html and Markdown Fields don't interpret Liquid syntax 

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1010]
The Html and Markdown Fields don't work if you enter a filter with Liquid syntax.

It is a problem if you select an Editor like the Wysiwyg one for this kind of field and that you expect to add a Media image that won't be rendered.

They should use the same LiquidTemplateManager.RenderAsync() method than the BodyPart or MarkdownPart so they may need an Html Property in their ViewModel, separated from their content.

As a consequence, a HtmlWidget with a HtmlField won't be rendered properly if you add Liquid syntax, like the one in a Page content type created by the agency recipe.

**Comment by agriffard** [comment]
The #1066 PR adds it to the HtmlField.

You can test it by editing the Footer in http://localhost:2918/OrchardCore.Layers/Admin/Index beacause it is an HtmlWidget with an HtmlField.

Ex : add Liquid syntax like this:
`{{ "/logos/creative-market.jpg" | asset_url | img_tag }}`

**Comment by agriffard** [comment]
I tested the LandingPage of TheAgency theme by editing the Body of the first Service with Liquid syntax but it doesn't produce the expected content:
In Debug, in BodyPartDisplay, line 64 I can see the .Html property is correctly rendered :
```
await _liquidTemplatemanager.RenderAsync(bodyPart.Body, writer, NullEncoder.Default, templateContext);
model.Html = writer.ToString();
```
but in the Preview or if I publish the content, the Liquid syntax is displayed as if it was not interpreted.

**Comment by sebastienros** [comment]
Ah ;) The code looked good. Try to debug you will find the issue.

**Comment by agriffard** [comment]
I reopen it because I don't understand why it doesn't work with a BodyPart.

**Comment by agriffard** [comment]
It is with the BodyPart that it doesn't work, not with the HtmlField.

**Comment by agriffard** [comment]
I get it. 
It is because of the template that displays the Body property with a for loop on the Services:

`<p class="text-muted">{{ service.BodyPart.Body | raw }}</p>`

But I don't know what I can change in the template or in the Driver to display it well.

The same problem might occur with a MarkdownPart.

**Comment by jtkech** [comment]
- The problem here is that the `BagPartViewModel` has a collection of `ContentItems` which are not shapes. This is in `BagPart.cshtml` (unused here) that items shapes are built, not in the driver (anyway, they are built with the `Summary` display type). So, e.g the bodyPart driver is not called.

- With shapes, the body part driver would be called and we could render the body as a shape. But here, maybe we need a liquid tag to do a `BuildDisplayAsync()` on a given content item.

**Comment by agriffard** [comment]
Thank you for the explanations @jtkech .

**Comment by agriffard** [comment]
I have a BlogPost with an image added in Liquid from the media selector.
In a `BodyPart_Summary` Template, I d' like to display only a summary of the part, so I used this Liquid code :
`{{ Model.Body | strip_html | truncatewords:75 | newline_to_br | raw }}{% a display_for:Model.ContentItem %}...{% enda %}`

but the the Liquid of the image `{{ img_tag ...  }}` is not interpreted.

What can I do to remove the Liquid code in the summary? Equivalent of `strip_html` but that cleans the Liquid.


The `newline_to_br` does not seem to work. The new lines are not replaced by `<br>`

**Comment by agriffard** [comment]
Does the `markdownify` filter can be used in Liquid to do this ?

**Comment by sebastienros** [comment]
I just tried and it works on html field, markdown field, html part. On the markdown part it gets evaluated then saved as part of the markdown content, so it's just working once ;) I am continuing my investigations.

**Comment by sebastienros** [comment]
Submitting a PR for MarkdownBodyPArt, the rest is working fine.

![image](https://user-images.githubusercontent.com/1165805/49910083-44c12d80-fe36-11e8-8391-5a97ea102e1b.png)

![image](https://user-images.githubusercontent.com/1165805/49910096-4d196880-fe36-11e8-8461-ceb99cc3cb1c.png)

**Comment by sebastienros** [comment]
Even works with the media button (both html and md wysiwyg editors)
