### ISSUE TITLE
OrchardCore.feeds should be disabled by default in standard recipes

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#10115]
In blog theme  it adds some extra fields in the blog edit form from the admin  which I think confuses most people and bloats the UI.
It should be off by default and users can enable at will.

**Comment by Piedone** [comment]
RSS/Atom feeds are quite the basic functionality of a blog though. I'd agree for the Agency and blank recipes.

**Comment by giannik** [comment]
Agree, I just think the user should deliberately activate it.

**Comment by deanmarcussen** [comment]
If the fields are confusing people, could we not improve the documentation, rather than removing the feature by default? as @Piedone says it is rather basic functionality to support an rss feed

**Comment by giannik** [comment]
ok. 
added back the Orchardcore.feeds feature for the blog theme recipe.
