### ISSUE TITLE
Upgrading to 1.0 is having unhandled error

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#10125]
### To Reproduce
When I do the upgrade

### Expected behavior
TypeLoadException: Could not load type 'OrchardCore.Data.Migration.DataMigration' from assembly 'OrchardCore.Data.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

is there any other component needs to be updated?

Thank you as always!

regards,
Gil

**Comment by Skrypt** [comment]
Please make sure you updated all your modules and also all your custom modules. This is not supposed to happen. The issue is on your side more likely.

**Comment by deanmarcussen** [comment]
You need to change some references to `OrchardCore.Data.YesSql` or  `OrchardCore.Data.YesSql.Abstractions`

and clean and rebuild your project. 

this pr significantly broke existing references https://github.com/OrchardCMS/OrchardCore/pull/9246

**Comment by webmedia1012** [comment]
Thank you sir, but I don't believe I use YesSql , I only use microsost Sql, and when you say references how do you mean? I essentially inspected my project file and could not find yesSql. Please advise.

**Comment by deanmarcussen** [comment]
Whichever project contains your data migration needs to be updated to take a reference to the above mentioned projects as the class was moved 

yessql is the data connection library used to connect to sql server

**Comment by webmedia1012** [comment]
Thank you @deanmarcussen , So here's how my setup looks like. Our site currently uses OC(orchardCore) from nuget package and now that you have a new update to 1.0.0, all I did was to upgrade the said package from nuget. Being just the libraries (nuget package) I'm using, do I have to download the bitbucket version of 1.0.0 (codes) and then reference from t that package instead when updating ? and also tried searching for the YesSql reference in all my projects and can't find anything. - thank you!

**Comment by Skrypt** [comment]
When using Nuget packages, generally you need to update the version of Orchard Core in every custom modules that you also created. So, it's generally not a change that is done in only one place unless you used a custom .csproj to make all your references done in that single project which you can then import. I'm probably going too far by explaining this but you basically have mismatching versions of a specific assembly which @deanmarcussen says is related with OrchardCore.Data.YesSql or OrchardCore.Data.YesSql.Abstractions.

**Comment by webmedia1012** [comment]
Alright I found the error and it was a project called Etch.Search, now I'm updated! I will close this ticket. Thank you very much. I'm opening another one, since the admin is throwing an error.
