### ISSUE TITLE
Tenant name and module name

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#1016]
For example,

Tenant: tenant1
Module: tenant1

then contents are `404`. e.g., `/tenant1/scripts/some.js`.

If rename the `tenant1` prefix to something else, the contents will work.

**Comment by sebastienros** [comment]
That's expected, and there is no solution to it actually. Maybe some validation to prevent tenant names with an existing module's name.

**Comment by sebastienros** [comment]
Won't fix
