### ISSUE TITLE
Change in GenerateUniqueAliasAsync in alias part handler

### ISSUE THREAD

**Issue by tropcicstefan** [OrchardCMS/OrchardCore#10170]
### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is.

Imagine content type with alias part (pattern: `{{ Model.ContentItem.DisplayText |  slugify }}`), and two items that have same 'display text'. 
For instance title of value 'Orchard alias part feature'. 

First item will have alias with value of : 'orchard-alias-part-feature'
Second item will have alias with value of : 'orchard-alias-part-0'
=>Second item lost part of information.
### Describe the solution you'd like. A clear and concise description of what you want to happen.
Could we change second item alias to 'orchard-alias-part-feature-0' so it doesn't lose any information. 
By putting this [int.TryParse](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Alias/Handlers/AliasPartHandler.cs#L142) in if condition and setting `unversionedAlias `only if last substring is an `int`.

### Describe alternatives you've considered. A clear and concise description of any alternative solutions or features you've considered.
a) Leave it as is.
b) Put version number behind '--' => 'orchard-alias-part-feature--0'

**Comment by deanmarcussen** [comment]
>  `orchard-alias-part-feature-0`

Sounds fine to me, that would have been the original intention. Happy to take a pr for it.
