### ISSUE TITLE
Is the high project count necessary?

### ISSUE THREAD

**Issue by flq** [OrchardCMS/OrchardCore#1017]
This issue is somewhat related to #920 , but I just want to figure out if there is actually some interest in bringing the total number of projects down.

The reason of doing this is simply the developer expereience: Less projects means faster startup and compile times and generally more happy developers.

The second reason is that projects should strictly be used as deployment artefact boundaries. If you want a logical separation, namespaces serve the same purpose.

So, if someone would do a dependency analysis of the projects (e.g. with NDepend) and bring those projects together that are deployed together, is this something that is in the interest of this community, or rather not?

**Comment by sebastienros** [comment]
> deployment artefact boundaries

And also dependency boundaries. You will find that most of the projects in `OrchardCore` folder are Abstractions and their Implementations. Most modules depend on only specific abstractions and fewer implementation ones.

But anyway here are some ideas:
#### For OrchardCode developers
Create a solution that points to the packages from nuget (once they are there) as developing OrchardCore doesn't always need all the other packages source code. Or at least one solution with only the modules as source code.

#### For web application developers
There is nothing to fix here as they should just reference `OrchardCore.Cms` as a package reference, leaving all the compilation task to their own code only.

We have to try it though as adding one project by source might have a domino effect on many other referenced projects.

This should be much better as soon as we are on Nuget.

**Comment by flq** [comment]
Okay...let's go a little bit into the dependency boundaries, and because we have a lot of assemblies, let's start with the abstractions. Doing a query on all **abstraction** assemblies with NDepend, we indeed get a lot of independent Abstractions. However, we also get an interesting graph with these assemblies:

![image](https://user-images.githubusercontent.com/123748/30667434-ce29197e-9e57-11e7-86db-83a7ae4a2f84.png)

This cluster appears to be a candidate for merging, and hence also the merging of the implementations. The questions I would like to ask is: What would one lose to have an Orchard Core Abstraction containing those assemblies, with a corresponding core implementation?

**Comment by alexbocharov** [comment]
@sebastienros 

> For web application developers
There is nothing to fix here as they should just reference OrchardCore.Cms as a package reference, leaving all the compilation task to their own code only.
We have to try it though as adding one project by source might have a domino effect on many other referenced projects.

Worked up to version 1.0.0-beta1-3216. Version 1.0.0-beta1-* (>3234) breaks this (After renaming OrchardCore.Cms to OrchardCore.Application.Cms.Targets).

**Comment by alexbocharov** [comment]
Need manually add reference to OrchardCore.Application.Cms.Props, OrchardCore.Application.targets, OrchardCore.Module.props

**Comment by alexbocharov** [comment]
> For OrchardCode developers
Create a solution that points to the packages from nuget (once they are there) as developing OrchardCore doesn't always need all the other packages source code. Or at least one solution with only the modules as source code.

I plan to highlight the core, modules and themes

**Comment by flq** [comment]
Well, as far as I can see, people are happy with the high project count. Personally I find it amazing, you folks must have very powerful machines.

**Comment by alexbocharov** [comment]
Not so steep. But to merge projects is also questionable.

**Comment by alexbocharov** [comment]
To split solutions seems correct

**Comment by sebastienros** [comment]
@flq totally agree with the slowness, but the solution is not to reduce the number of projects. Fortunately it should only impact the core team who works on new default modules. Sometime I also use VS Code as it is not impacted by the size of the solution.

**Comment by flq** [comment]
Doesn't make much sense to me to keep this open.
