### ISSUE TITLE
ContentOptionsViewModel. How does it work with  QueryFilterResult ?

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#10186]
Hello,
I am trying to build a custom driver that builds the search parameters shape (like in the contents admin list).
So my code looks like this :
```
  var options = new ContentOptionsViewModel();
   options.SelectedContentType ="Blog";  //pass in search parameters
   options.SearchText = "search text"
   
   // this does'nt work as .FilterResult is null
   //options.FilterResult.MapFrom(options);

  // With the options populated we filter the query, allowing the filters to alter the options.
  await ContentsAdminListQueryService.QueryAsync(options, UpdateModelAccessor.ModelUpdater);
  var header = await ContentOptionsDisplayManager.BuildEditorAsync(options,  UpdateModelAccessor.ModelUpdater, false);
	
```
This doesnt work because options.FilterResult is null and there is no parameterless constructor 
to pass in an empty  QueryFilterResult<ContentItem>  

```
  //doesnt work
  options.FilterResult = new QueryFilterResult<ContentItem>();
```

It works in AdminController by using a custom model binder : 

```
 public async Task<IActionResult> List(
            [ModelBinder(BinderType = typeof(ContentItemFilterEngineModelBinder), Name = "q")] QueryFilterResult<ContentItem> queryFilterResult, 
            ContentOptionsViewModel options,
            PagerParameters pagerParameters, 
            string contentTypeId = "")

```

So my question is if there is a way  build the QueryFilterResult (without model binding) and pass it to the options or better yet do somthing like :

```
options.FilterResult.MapFrom(options);
```
 and take care of internally   creating the options.FilterResult so  I dont have to worry about the filter parser?

@deanmarcussen 

Thank you.

**Comment by deanmarcussen** [comment]
What are you actually trying to achieve?

The arrangement is a bit useless if you take the parser out of it.

But have a look at the list form post in the contents controller.

or if you are just wanting to extend the filters see the localization module

**Comment by deanmarcussen** [comment]
Btw you have to run it through the parser to get a result, as the parse result has the the query Funcs. You could give the parser an empty string, and you’ll get an empty result which can be added to

**Comment by giannik** [comment]
Thanks @deanmarcussen 

I gave an empty string to the parser and it worked.

I want to build a search list for content items in the front end so I copied some code from the admin contents list and the parser thing was blocking me.
