### ISSUE TITLE
In GraphQL a content part resolves as ContentPart instead of the actual type when a content field precedes it in the query.

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#10181]
### Describe the bug

I have a content type that contains a text field (named "Biography") and a custom content part (PersonPart). The former gets a `biography` field in GraphQL by default and I have implemented an `ObjectGraphType<PersonPart>` to expose a `person` field. Depending on the order of the two in the query either it consistently works fine or consistently throws errors.

This works:
```graphql
query PersonFirst {
  personPage {
    person {
      biography
      birthDateUtc
      handedness
      name
    }
    biography
    displayText
  }
}
```

This doesn't work:
```graphql
query BiographFirst {
  personPage {
    biography
    person {
      biography
      birthDateUtc
      handedness
      name
    }
    displayText
  }
}
```

This is the error:
```text
GraphQL.ExecutionError: Expected value of type "Lombiq.TrainingDemo.GraphQL.Services.PersonPartObjectGraphType" for "PersonPartObjectGraphType" but got: OrchardCore.ContentManagement.ContentPart.
   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node)
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) debugger eval code:1:9
```

### To Reproduce
1. Clone and build this repo: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/tree/issue/OSOE-36
2. Set up the site with the Training Demo recipe.
3. Run the "Sample Content - Person" recipe.
4. Go to Admin > Configuration > GraphiQL
5. Insert the above GraphQL queries.
6. See error only on the second one.

### Expected behavior
The query should yield identical results regardless of field order in the request.

### Screenshots

[Video of the reproduction.](https://user-images.githubusercontent.com/4007293/131267947-43e13513-5337-42b3-ad91-d55197d115da.mp4)

The state of the ValueNodeResult method mentioned in the error:
BiographyFirst
![image](https://user-images.githubusercontent.com/4007293/131270329-91512098-51db-4661-8de4-49c44a43c017.png)
PersonFirst
![image](https://user-images.githubusercontent.com/4007293/131270332-60e0fed1-8872-4e7c-9ca4-75781eebbbce.png)

**Comment by gvkries** [comment]
I think this has been fixed in the meantime, I cannot reproduce it on the main branch.

**Comment by Piedone** [comment]
@sarahelsaig could you please confirm?

**Comment by sarahelsaig** [comment]
Yes, it's been fixed very recently. Specifically the new type checking on line 67 here solved this issue as well:
https://github.com/OrchardCMS/OrchardCore/blob/ff88852c0573807cb66330d7b2c534832ffd23e0/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs#L64-L70
Thanks, @tropcicstefan!
