### ISSUE TITLE
OrchardCore.CMS NuGet package doesn't include any recipes

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1018]
This causes the Setup screen to bomb out because it calls `.First()` on an empty collection.

**Comment by sebastienros** [comment]
Good catch, I was actually thinking about have the recipes in a different package. So we could have only the CMS without the recipes, and add custom recipes, or have a package with CMS and the default recipes.

But we still need to fix this bug and display a fine message.

**Comment by paynecrl97** [comment]
I'll do it tonight if you point me in the direction of where the specifications for the packages live...

**Comment by paynecrl97** [comment]
And as for displaying a nicer message when there are no recipes enabled- how do you envision that working?

I assume that setup will not work if there are no recipes available, so we shouldn't even show the setup screen in this scenario.

Either that, or try and come up with a way to run setup without a recipe being available?

**Comment by paynecrl97** [comment]
The problem with recipes in their own package, is that the recipes are dependant on features being there.

So if you create a `OrchardCore.Recipes.Blog` package, that'd have to take dependencies on all the packages that contain the features that that recipe tries to enable.

**Comment by sebastienros** [comment]
We can just change the drop down to display a red message instead. And a validation rule in the action to prevent the setup, like it's done for the password or the other mandatory fields.

Create three new packages, OrchardCore.Recipes.Blog, OrchardCore.Recipes.Agency and OrchardCore.Recipes.SaaS. They will contain a static file that needs to be packaged in the nuget, in the Recipes folder. Then reference them from the Cms.Web project.

**Comment by sebastienros** [comment]
That would make sense to have them depend on the features they require.

**Comment by sebastienros** [comment]
Or they can just depend on the Cms bundle/ It's like the `.All` in dotnet core 2.0.

**Comment by paynecrl97** [comment]
But wouldn't the CMS bundle also depend on the theme packages?

Can NuGet handle circular dependencies like that?

**Comment by sebastienros** [comment]
I don't think it's circular

**Comment by paynecrl97** [comment]
The CMS bundle would need to take a dependency on at least one recipe package, or else users wouldn't be able to run the setup. And if the purpose of this bundle is to be a one stop shop to get a site up and running then it defeats that objective.

Unless I'm missing something?

**Comment by sebastienros** [comment]
the cms bundle doesn't, the web application does

**Comment by sebastienros** [comment]
or we a separate bundle, one that references the cms metapackage and the recipes

**Comment by paynecrl97** [comment]
OK, so this is how it looks if there are no recipes available:

![image](https://user-images.githubusercontent.com/2872984/30666467-53097a32-9e4c-11e7-8645-20cb5f368797.png)

Working on the validation now...
