### ISSUE TITLE
Can't get access token via email address as user name

### ISSUE THREAD

**Issue by hung-doan** [OrchardCMS/OrchardCore#10190]
### To Reproduce
Get access token via POST https://localhost:44391/connect/token
- grant_type
- scope
- username
- password
- client_id

If I use the user name, It works. 
However, if I use user email. It doesn't work. 

### Expected behavior
-  According to this discussion thread: https://github.com/OrchardCMS/OrchardCore/pull/7645. There is a change to not allow the username = email. However, there should be a fallback to authenticate by username or email. 
-  I expect I can use username or email as to login. 

### Screenshots
![image](https://user-images.githubusercontent.com/11371581/131404090-dc0ab09c-5269-479f-8dd4-b5fe8b3ffb43.png)

**Comment by hung-doan** [comment]
My current workaround is to add a middleware to replace "@" by "+" in username (right before passing form data into OrchardCore)
```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	// TODO: follow https://github.com/OrchardCMS/OrchardCore/issues/10190 and remove this workaround.
	app.Use(async (context, next) =>
	{
		if (context.Request.Path.Value != null
			&& context.Request.Path.HasValue
			&& context.Request.Path.Value.ToLower().StartsWith("/connect/token"))
		{
			var formDictionary = new Dictionary<string, StringValues>();
			foreach (var key in context.Request.Form.Keys)
			{
				context.Request.Form.TryGetValue(key, out StringValues formValues);

				// Change client_id value to "NewValue"
				if (key == "username")
				{
					string userName = formValues.ToString();
					string normalizedUserName = userName.Replacee("@", "+");
					formValues = new string[] { normalizedUserName };
				}

				formDictionary.Add(key, formValues);
			}

			context.Request.Form = new FormCollection(formDictionary);
		}
		// Do work that doesn't write to the Response.
		await next.Invoke();
		// Do logging or other work that doesn't write to the Response.
	});

}
```

**Comment by deanmarcussen** [comment]
@kevinchalet we never did login via username or email for OpenID, just cookie auth, is that something you're ok with OpenID supporting?

**Comment by kevinchalet** [comment]
@deanmarcussen consistency always wins, so if it's supported for interactive logins, there's no reason not to support it everywhere.

That said, it's not something the OpenID module manages: the username/password authentication is handled by the user service in `OrchardCore.Users.Core`:

https://github.com/OrchardCMS/OrchardCore/blob/ce53b9a90e2ba329e9b0a039a298d489302edefe/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs#L492-L514

https://github.com/OrchardCMS/OrchardCore/blob/ce53b9a90e2ba329e9b0a039a298d489302edefe/src/OrchardCore/OrchardCore.Users.Core/Services/UserService.cs#L57-L64
