### ISSUE TITLE
Can't save changes when IContentManager is resolved via ShellHost.

### ISSUE THREAD

**Issue by NickMaev** [OrchardCMS/OrchardCore#10198]
### Describe the bug
OrchardCore v. 1.0

`ContentManager` methods such as `UpdateAsync` and `CreateAsync` don't work when they are resolved via `ShellHost`. 
It's necessary for me to resolve `IContentManager` from other modules because it can't be resolved using a regular DI mechanism. 
But the bug reproduces at the main ASP.NET Core application without modules.

### To Reproduce
1. Create a new project using with the headless tenant using the following command:
```cmd
dotnet new occms -n MySite
```
2. Create a new `ContentType` with `TextField`.
3. Create a new `ContentItem` from its `ContentType`.
4. Create a new `Controller`.
5. Resolve `IShellHost` in the `Controller`'s constructor.
6. Access the `Default` tenant's scope via `IShellHost.GetScopeAsync(string tenantName)`.
7. Resolve `IContentManager` via given scope.
8. Get the `ContentItem` (from step 2) via `IContentManager.GetAsync(string contentItemId)`.
9. Alter `ContentItem` and update it, validation will be succeeded.
10. Update the page of `ContentItem`'s editor in the admin panel. Changes were not saved.

Use this code for reproducing the bug:
```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OrchardCore;
using OrchardCore.ContentFields.Fields;
using OrchardCore.ContentManagement;
using OrchardCore.Environment.Shell;

namespace MySite.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TestController: ControllerBase
    {
        private readonly IShellHost _shellHost;

        public TestController(IShellHost shellHost)
        {
            _shellHost = shellHost;
        }
        
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            // Get the scope of the Default tenant.
            var scope = await _shellHost.GetScopeAsync("Default");
            // Resolve content manager via the given scope.
            var contentManager = scope.ServiceProvider.GetService(typeof(IContentManager)) as IContentManager;
            // Get the content item by its ID via content manager. You should create it before.
            var ci = await contentManager.GetAsync("[Id of the content item]");
            // Modify the content part's field by its name.
            ci.Alter<ContentPart>(ci.ContentType, x =>
            {
                x.Alter<TextField>("[Your field name]", y => y.Text = "[New value]");
            });
            // Update the content item.
            await contentManager.UpdateAsync(ci);
            // Validate the content item to make sure that update was succeeded.
            var val = await contentManager.ValidateAsync(ci);
            
            return Ok(val);
        }
    }
}
```

Btw: 
When the content manager is resolved using regular DI (which can't be in Orchard Module) it works as expected.

### Expected behavior
When the `IContentManager` is resolved via `IShellHost` the tenant's scope methods like create or update work as expected.

**Comment by jtkech** [comment]
You need to execute your code by using the `ShellScope.UsingAsync()` extension, here an example.

https://github.com/OrchardCMS/OrchardCore/blob/926eadb5342c7a674c636214de30d700b7daecae/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs#L60-L69

**Comment by NickMaev** [comment]
> You need to execute your code by using the `ShellScope.UsingAsync()` extension, here an example.
> 
> https://github.com/OrchardCMS/OrchardCore/blob/926eadb5342c7a674c636214de30d700b7daecae/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs#L60-L69

It works like a charm! Thank you so much.
