### ISSUE TITLE
Document creation of queries

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#1020]
I am  confused about queries, in "rencentblogpost" example, i can get the result. 
If i want to Query  blogpost belong to one specified blog, how i write the code?  and ,how i learn more queries? please give me some advices.

**Comment by etcetraw** [comment]
if you search orchard podcast queries , you will find a weekly meeting recording where it was discussed.

**Comment by agriffard** [comment]
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Queries/README/
