### ISSUE TITLE
About OrchardCoreBuilder.ConfigureServices's configure being triggered multiple times

### ISSUE THREAD

**Issue by kamikyo** [OrchardCMS/OrchardCore#10209]
My code looks like this:
```
services.AddOrchardCore()
    .ConfigureServices(configure)
    .AddMvc();
```
Now I have a module called CoreTest.  When I request this module,this is what will happen:
```
async Task<ShellContext> IShellContextFactory.CreateShellContextAsync(ShellSettings settings)
{
    if (_logger.IsEnabled(LogLevel.Information))
    {
        _logger.LogInformation("Creating shell context for tenant '{TenantName}'", settings.Name);
    }

    var describedContext = await CreateDescribedContextAsync(settings, MinimumShellDescriptor());

    ShellDescriptor currentDescriptor = null;
    await describedContext.CreateScope().UsingServiceScopeAsync(async scope =>
    {
        var shellDescriptorManager = scope.ServiceProvider.GetService<IShellDescriptorManager>();
        currentDescriptor = await shellDescriptorManager.GetShellDescriptorAsync();
    });

    if (currentDescriptor != null)
    {
        describedContext.Dispose();
        return await CreateDescribedContextAsync(settings, currentDescriptor);
    }

    return describedContext;
}
```
`var describedContext = await CreateDescribedContextAsync(settings, MinimumShellDescriptor());` after execution. the OrchardCoreBuilder.ConfigureServices's configure will be executed once.

next
```
    if (currentDescriptor != null)
    {
        describedContext.Dispose();
        return await CreateDescribedContextAsync(settings, currentDescriptor);
    }
```
after execution. the OrchardCoreBuilder.ConfigureServices's configure will be executed again.

At the same time, in `OrchardCore.Environment.Shell.Distributed.DistributedShellHostedService`. The method `CreateDistributedContextAsync` is invoking `_shellContextFactory.CreateDescribedContextAsync`. 
This will cause the OrchardCoreBuilder.ConfigureServices's configure to be executed twice again (at least twice, and more often when blocking occurs).

Of course `ModularTenantContainerMiddleware.Invoke` will not be idle either.
`var shellScope = await _shellHost.GetScopeAsync(shellSettings);`  same will cause the OrchardCoreBuilder.ConfigureServices‘s configure to be executed.

That means that the same OrchardCoreBuilder.ConfigureServices's configure will eventually be executed at least 5 times.
Is this the expected behavior?

**Comment by jtkech** [comment]
@kaipm From memory

Yes, the first time we create a tenant / shell container (only once until the shell needs to be rebuilt) we call all the `ConfigureServices()` of the startup of all enabled modules / features, this including the one defined from the app on the `OCBuilder` returned by `AddOrchardCore()`, this because the app also behaves as a module.

But yes, because before we first need to know which features are enabled, this by retrieving the `ShellDescriptor` from the database, we first create a temporary container to resolve the `IShellDescriptorManager`.

But we create this container on a `MinimumShellDescriptor` meaning that the `ConfigureServices()` will be called on a very limited set of modules / features, but yes the app being an always enabled feature, the one defined from the app (not the one of the main startup, the one defined on the OCBuilder) will be called.

About the `DistributedShellHostedService`, yes we do the same kind of thing to create an isolated container for the default tenant, but we cache it so here also only once until the default tenant has changed (e.g. a feature was disabled).

**Comment by kaipm** [comment]
The answer seems to be intended for @kamikyo :)

**Comment by jtkech** [comment]
Oops, yes thanks ;)

**Comment by kamikyo** [comment]
@jtkech Thank you very much for your patient explanation. 
I have another question, let's say I have two modules: module A and module B. 
I remember in a previous version, if I use service.AddTransient<ServiceA>() in module A, it will throw an exception "can not resolve type ServiceA" if I don't inject it in module B. 
But now (ver 1.0.0) there is no such problem. 
Of course, I prefer the design of 1.0.0. 
I mean, it's true that some versions were designed that way before, right?

**Comment by jtkech** [comment]
> I remember in a previous version, if I use service.AddTransient() in module A, it will throw an exception "can not resolve type ServiceA" if I don't inject it in module B.

Do you mean that if you inject it it works? Not sure I understand, would need a more detailled use case.

That said, when we enable a feature through the admin or a recipe on startup, we ensure that its dependencies are enabled. But it seems that you don't use the cms, only `AddOrchardCore()`, not `AddOrchardCms()`.

So I assume that you define your enabled features by code or through the config (e.g. in appsettings.json) by using the `Features` collection field. If so, let's say that module B depends on module A (defined in the manifest file of module B) and that you only specify module B in your features, before module A was not automatically enabled, now it is.

**Comment by kamikyo** [comment]
Entry.csproj:
```
<ItemGroup>
  <ProjectReference Include="ModuleA.csproj" />
  <ProjectReference Include="ModuleB.csproj" />
</ItemGroup>
```
Entry's Startup.cs:
```
public void ConfigureServices(IServiceCollection services) {
  services.AddOrchardCore()
      .ConfigureServices(configure)
      .AddMvc();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env){
  app.UseOrchardCore();
}
```
no Manifest.cs

---------------------------------------------

ModuleA's Startup.cs:
```
public override void ConfigureServices(IServiceCollection services){
  services.AddTransient<ServiceA>();
}
```
ModuleA's ControllerA.cs:
`public ControllerA(ServiceA _sa){ ... }` It works well

---------------------------------------------

ModuleB's Startup.cs:
```
public override void ConfigureServices(IServiceCollection services){
  //nothing
}
```
ModuleB's ControllerB.cs:
`public ControllerB(ServiceA _sa){ ... }` Now it also works well (in version 1.0.0), But I remember a previous version that threw an exception: `can not resolve type ServiceA`

**Comment by ns8482e** [comment]
If ModuleB depends on Module A  and if you have dependency defined in `Manifest.cs` properly, `ServiceA` always get resolved from ModuleB 

>previous version that threw an exception: can not resolve type ServiceA

@kamikyo based on my understanding with OC,  - this would only occur if you have not properly defined dependency in `Manifest.cs`  of `ModuleB` or not using `Order` property for `ModuleB` to run `ConfigureServices` later. As that might have resulted in  calling `ConfigureServices` of dependent module ` ModuleB` before dependency `ModuleA`

To control execution order of `ConfigureServices` between modules, you need to either define `ModuleB` as dependent on `MoudleA` in `Manifest.cs` or define `Order` property to run it later.

**Comment by kamikyo** [comment]
@ns8482e Thank you for your answer. In previous versions, I did use OC just like you said,So the exception "can not resolve type ServiceA" is thrown.
But now, the same way it is used, the OC module works fine. So, I think OC should have made a big change to dependency injection.
Anyway, your answer made the doubts in my mind disappear, thank you again.
