### ISSUE TITLE
Is there possible to update automaticly in orchard core  like wordpress or planned?

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#1021]

**Comment by agriffard** [comment]
That is not how Orchard Core works.

You need to see it as an Application Framework that allows you to add modules to your application and makes it easy to extend it.

The OrchardCore.Cms.Web project is just one example showing how to reference the Orchard Core Modules.

That being said, as they are published as Nuget packages, it will be easy to update the modules but you will have to restore them and build the application so it won't be an automatic update as it is in Wordpress.

**Comment by khoshroomahdi** [comment]
Thanks
