### ISSUE TITLE
select language (Culture) doesn't exists anymore

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#10211]
After  update to new version "1.1.0-preview-16455", the culture menu doesn't appear anymore. It seems the module haven't attached in this version.

![image](https://user-images.githubusercontent.com/56995550/132126212-ca33b17a-b117-4369-9f5f-011a59c1c0c1.png)

**Comment by Skrypt** [comment]
Enabled the "Localization" feature ?

**Comment by overstartup** [comment]
> Enabled the "Localization" feature ?

![image](https://user-images.githubusercontent.com/56995550/132143657-a3943ae3-328f-4316-b1c9-2582cb240afb.png)

These are what I have regarding localization.
There is extra dll to import?

**Comment by Skrypt** [comment]
You are missing OrchardCore.Localization module.

**Comment by Diman96** [comment]
What do you mean? I tried adding it like this to theme module 
`<PackageReference Include="OrchardCore.Localization" Version="$(OrcahrdCoreVersion)" />`
and the menu item did not appear.

**Comment by Diman96** [comment]
OrchardCoreVersion=1.1.0-preview-16457

**Comment by Skrypt** [comment]
Then you should try to see in your custom module what is removing this menu entry. Try accessing the url directly instead to see if it works. But if the feature is not showing in the Admin to be enabled then it is more likely that it fails loading the module. You could then have some custom code that removes this service from the code.

**Comment by hishamco** [comment]
@overstartup could you please provide a minimal repo to reproduce?

**Comment by Diman96** [comment]
On 1.1.0-preview-16445 everything works fine, later versions do not display localization and the toggle function `switch_culture_url` does not work. There is nothing that could overload the localization in the project.

**Comment by hishamco** [comment]
> On 1.1.0-preview-16445 everything works fine, later versions do not display localization and the toggle function switch_culture_url does not work. There is nothing that could overload the localization in the project.

@jtkech is this related to https://github.com/OrchardCMS/OrchardCore/commit/48119bdee7dd3fa0ec4154545013c12e792eb112

**Comment by jtkech** [comment]
Just tried, I confirm the issue

@hishamco it is related to your last PR #10178

When a manifest define at least one feature, which is required when you have more than one feature in a given module, the module attribute can't define the main feature anymore, in that case most of the time we use the first feature to define this main feature by using the Id of the module, here `OrchardCore.Localization`, then we use subsequent feature attributes to define the new ones, here `OrchardCore.Localization.ContentLanguageHeader`.

Here the feature that we added but before there was no feature attributes, so we need to define a first feature related to the main one `OrchardCore.Localization`.

https://github.com/OrchardCMS/OrchardCore/blob/ad6dc18f15aeb50d1aab382293f2146c579fcdac/src/OrchardCore.Modules/OrchardCore.Localization/Manifest.cs#L13-L18

I will fix it soon

**Comment by hishamco** [comment]
> @hishamco it is related to your last PR #10178

Oh really?!! I though the issue was related to Liquid, anyhow I will try to have a look if there's a module with multiple features, I presume OC.Users have many features

**Comment by hishamco** [comment]
@jtkech is this example of what you mean?

https://github.com/OrchardCMS/OrchardCore/blob/ad6dc18f15aeb50d1aab382293f2146c579fcdac/src/OrchardCore.Modules/OrchardCore.Users/Manifest.cs#L10-L15

Where one feature at least has the same name of the module?

**Comment by jtkech** [comment]
@hishamco yes exactly.

I saw another little thing so I did a PR that I will merge.

Need to leave but I will revisit it tomorrow.

But I will merge my PR as it fixes this issue.
