### ISSUE TITLE
How to extending the User type?

### ISSUE THREAD

**Issue by YaoaY** [OrchardCMS/OrchardCore#1022]
For example,I need to add some properties to the default User model.
Such as:
`public string PhoneNumber { get; set; }`
`public int Age { get; set; }`

At first I thought I could create a new module  to 'weld' these additional properties to User.
Such as 'Orchard.Profile','Orchard.Avatars' or something, as people did in O1.

[Customizing User Registration](http://www.ideliverable.com/blog/customizing-user-registration-and-login-with-dynamic-forms-and-workflows)

But after some search, I found no way to do so in OrchardCore？

@Jetski5822 You seems to have asked a similar question seven years ago.:joy:
[https://social.msdn.microsoft.com/Forums/en-US/716799b3-36e1-4e76-99ad-c1d6e57ee369/profiles-user-profiles-avatars-implementation?forum=orcharddiscussions](https://social.msdn.microsoft.com/Forums/en-US/716799b3-36e1-4e76-99ad-c1d6e57ee369/profiles-user-profiles-avatars-implementation?forum=orcharddiscussions)

**Comment by jnucpz** [comment]
a similar answer: https://github.com/OrchardCMS/OrchardCore/issues/888

**Comment by YaoaY** [comment]
**Add IEntity support to User** -> #1025 
😀 👍 👍
