### ISSUE TITLE
dotnet new occms --logger Serilog on case-sensitive file systems.

### ISSUE THREAD

**Issue by andrewjcarney** [OrchardCMS/OrchardCore#10246]
The default log directory for serilog in this template is lower case, which causes a duplicate folder to get created on case-sensitive file systems.

Steps to reproduce:

```

$ mkdir example && cd example               
$ dotnet new occms --logger Serilog 
$ dotnet run
$ tree -L 1
.
├── app_data               <----
├── App_Data               <----
├── appsettings.json
├── bin
├── bugexample.csproj
├── Localization
├── obj
├── Program.cs
├── Properties
├── Startup.cs
└── wwwroot

```

Workaround:

update your local `appsettings.json` to have the correct path:

```
      {
        "Name": "File",
        "Args": {
          "path": "App_Data/Logs/orchard-log.txt",
          "rollingInterval": "Day",
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.ffff}|{TenantName}|{MachineName}|{RequestId}|{SourceContext}|{Level:u3}|{Message:lj}{NewLine}{Exception}",
          "restrictedToMinimumLevel": "Warning"
        }
      }

```

https://github.com/OrchardCMS/OrchardCore/blob/e5cad712fecfad29dbab79844ba1d68f6d503416/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Web/appsettings.json#L32

**Comment by hishamco** [comment]
@andrewjcarney could you please create a PR, then the team can review your changes?

**Comment by andrewjcarney** [comment]
Hello @hishamco - done!  #10268 

https://github.com/OrchardCMS/OrchardCore/pull/10268
