### ISSUE TITLE
Admin theme - placing bootstrap and 3rd CSS under root[data-theme] cause styling issue as it break the current precedence of CSS selectors

### ISSUE THREAD

**Issue by hung-doan** [OrchardCMS/OrchardCore#10249]
### Describe the bug
In v1.0.0 we put bootstrap and 3rd CSS under  `root[data-theme]`, which changes the default precedence/priority of CSS selectors from the CSS/CSS-library.

**Issue:** It break almost of my custom CSS or 3rd library - for selectors that access the same element as in the Admin CSS file.

The styling from Admin CSS always override my custom CSS or 3rd library, regardless of the order of CSS files.

The current work around at the moment are:
- Add "!important" keyword or change the selectors that have more specific/priority than selector from Admin theme.
- For my 3rd CSS library, I have to modify their source code (which is a bad practice), or I have to extract and mimic some CSS from the library and add !important keyword to where I need to fix the issues. 

In the RC version or in the usual workflow. I simply add my CSS file after the admin theme (including bootstraps,...), then it will work fine and override the default style of bootstrap. 

However, It doesn't work any more. It's very troublesome as currently I have to regression test my whole app because I'm not sure which styling from my custom CSS or my 3rd library that stop working.

### To Reproduce
For example I want to set background color of `a` element
CSS file order
```
<link href="/TheAdmin/css/TheAdmin.css" media="all" rel="stylesheet" type="text/css" />
<link href="/MyCustomTheme/css/MyAdmin.css" media="all" rel="stylesheet" type="text/css" />
```
HTML: 
```
<a class="my-link">My link</a>
```

MyAdmin.css : 
```
a.my-link {
    background-color: red;
}
```
In the normal case, my CSS will override this style from bootstrap: 
```
a {
  background-color: transparent;
}
```

However, within the Admin theme this CSS doesn't work as the Admin theme put bootstrap CSS under the much more detailed selector :root[data-theme=default]
```
[dir]:root[data-theme=default] a {
  background-color: transparent;
}
```

### Expected behavior
Should we consider a better approach to deal with the 3rd library without changing their default precedence/priority ?

### Screenshots
![image](https://user-images.githubusercontent.com/11371581/132993711-d853fbc6-b9d8-44c5-a8d3-159cdae7de95.png)

**Comment by Skrypt** [comment]
If we want to support a dark theme we need to have a selector wathever it might be. So, the issue is not with the selector but with the support of a dark theme with Bootstrap 3rd party libraries. As you can see our 3rd party libraries are transpiled in both theme so that they work. That's the only possible workaround as of now because Bootstrap doesn't support a dark theme yet. We will revise this when Bootstrap 6 will be out as it is supposed to support a dark theme.
