### ISSUE TITLE
Add IEntity support to User

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1025]
And make the current implementation based on a driver.

**Comment by paynecrl97** [comment]
I'm going to have a go at doing this.

Am I good to base this on the way `ISite` works in the `OC.Settings` module, and then create 2 drivers- one for user setting & one for roles?

**Comment by sebastienros** [comment]
Yes, I actually explained this to @sfmskywalker yesterday. You resolve a `IDisplayManager<IUser>` and it will let you use drivers for `IUser`. Then you can use `SectionDisplayDriver` to handle parts-like drivers.

So yes, if you understand how `ISite` works, it should be super easy to do it for Users. You could optionally implement `Display`, with shapes targeting the front end and others for the admin. And use it in the current view that displays the list of users (SummaryAdmin display type).

**Comment by paynecrl97** [comment]
Oh yeah, didn't think about using SummaryAdmin to display the list. I'll add that in too.

**Comment by hishamco** [comment]
@paynecrl97 are you still interested to do this?

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/1054
