### ISSUE TITLE
OpenID Client has an authentication error after orchard is upgraded to v1

### ISSUE THREAD

**Issue by MaChao9914** [OrchardCMS/OrchardCore#10266]
When I configure OpenId authentication between tenants，there will be error: invalid_request This client application is not allowed to use the specified scope.But there is no problem in the rc2 version.

**Comment by hishamco** [comment]
@kevinchalet any idea?

**Comment by kevinchalet** [comment]
@MaChao9914 see https://github.com/OrchardCMS/OrchardCore/issues/1981.

**Comment by MaChao9914** [comment]
thanks for your answer. 
There is possible not to add the standard scopes?

**Comment by MaChao9914** [comment]
And there is another problem here. 
I found that the userID field is automatically updated, but the providerKey field in the corresponding RP`s database table Document and Table UserByLoginInfoIndex is not automatically updated.
