### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by Wielebny666** [OrchardCMS/OrchardCore#1026]
Hi,
i fill all forms and after finish setup:
An error occurred while initializing the datastore: This SqlTransaction has completed; it is no longer usable.

**Comment by Wielebny666** [comment]
I use Mssql 2016.
After await store.InitializeAsync(); in SetupService

Exception thrown: 'System.Data.SqlClient.SqlException' in YesSql.Core.dll
Exception thrown: 'System.InvalidOperationException' in System.Data.SqlClient.dll

**Comment by agriffard** [comment]
Was it because of a wrong Connection string ?

**Comment by Wielebny666** [comment]
My connection string:
Data Source=LENOVO\ELMER;Initial Catalog=MES;User Id=xxxxx;Password=xxxxx
In Microsoft SQL Management Studio i see:
![image](https://user-images.githubusercontent.com/31576684/31101092-809d42a6-a7cc-11e7-9fb8-0362838d9371.png)

**Comment by sebastienros** [comment]
Try to set a TAble Prefix, the tabke it's trying to create probably already exists

**Comment by agriffard** [comment]
related to #944 ?

**Comment by sebastienros** [comment]
I think this is because the db had already existing tables.

**Comment by ashishpd** [comment]
Can we more details in the error message. I am running into this problem as well. I have tried everything - no database to start with, then manually created the database, then used an existing database with known connection string for that db, which works otherwise fine in other apps.

**Comment by jtkech** [comment]
Maybe related to #1395

**Comment by sebastienros** [comment]
I will fix this. The unit tests in YesSql might not cover a special case.

**Comment by roballred** [comment]
I have run into this error, just to vote that it is still open

**Comment by jchenga** [comment]
I am also running into this issue.  I created two web sites referencing 1.0.0-beta2-67846 and 1.0.0-beta3-* respectively. Both had the same error message "An error occurred while initializing the datastore: This SqlTransaction has completed; it is no longer usable."

This happened with SQL Server 12. SQLite works.
