### ISSUE TITLE
in my module OrchardCore.Module.Targets.csproj references necessary?

### ISSUE THREAD

**Issue by yiji** [OrchardCMS/OrchardCore#1027]
in core modules every module has reference OrchardCore.Module.Targets.csproj.
i am not clear msbuild,but i guess in my module this project reference is not necessary.  Just place Directory.Build.props in the project folder sibling directory,is it?

**Comment by sebastienros** [comment]
If you want to place the props file by yourself that's fine, but most people will prefer to reference a package. Even more as we might change what it contains or does in the future.
