### ISSUE TITLE
Convert INotifier to async

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#10282]
### Is your feature request related to a problem? Please describe.

I've replaced the `INotifier` on the front end with a signalR version, which works asyncronously.

### Describe the solution you'd like

Update `INotifier` to use `ValueTask` when adding notifications.

### Describe alternatives you've considered

Prefer not to do a custom implementation, as using `INotifier` allows the front end to also recieve messaging notifications from code in the `OrchardCore` code base, which is very convenient for us.

**Comment by sebastienros** [comment]
Add `AddAsync` implementation that defaults to the `Add` one so it's not breaking.

**Comment by sebastienros** [comment]
With default interface implementation, and test with a module (from package) built for the old version, to see if it still works.
