### ISSUE TITLE
Decoupled CMS in MVC project

### ISSUE THREAD

**Issue by Brouilles** [OrchardCMS/OrchardCore#10302]
1. Create a "ASP.NET Core Web App (Model-View-Controller) in Visual Studio
2. Edit the csproj  with the following
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OrchardCore.Application.Cms.Core.targets" Version="1.0.0" />
  </ItemGroup>
</Project>
```
3. Edit the Startup as follow
```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GaetanDezeiraud
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // services.AddControllersWithViews();
            services.AddOrchardCms();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            /*
            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
            */
            app.UseOrchardCore();
        }
    }
}
```
4. Start the project, setup at configuration to blank
5. At the website index, have `The page could not be found.` I think because don't use the `pattern: "{controller=Home}/{action=Index}/{id?}");` maybe?

I don't know what else to do.

I see this issue https://github.com/OrchardCMS/OrchardCore/issues/5394. But don't help me...
A little out of subject. But it is possible to define an MVC Model and Orchard automaticaly setup the Content Type? Maybe with annotations?

Thanks.

**Comment by sfsharapov** [comment]
@Brouilles, I can't get the point. What is your problem?

I've reproduced your step and I've got «The page could not be found» error. It [is okay for «blank»](https://github.com/OrchardCMS/OrchardCore/issues/5394#issuecomment-579589967) recipe.

**Comment by Brouilles** [comment]
Thanks for your time.
With the same setup on a ASP.net core Application (not MVC) I have always access to the default project template at / and /privacy generated by Visual Studio. With the use or Bootstrap. 

Ans it is not the case when I create an MVC project. I want to use Orchard in the Decoupled way.

In some, I want to do this https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/ inside a MVC project.

I hope it is possible.

**Comment by ns8482e** [comment]
configure orchard core cms as following in your startup for MVC routes
```cs
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms()
             .Configure( (app, routes, svc)  =>{
                   routes.MapAreaControllerRoute("default", "yourwebproject", "{controller=Home}/{action=Index}/{id?}");
            })
           ;
        }
```

**Comment by sfsharapov** [comment]
> ```cs
>  public void ConfigureServices(IServiceCollection services)
>         {
>             services.AddOrchardCms()
>              .Configure( (app, routes, svc)  =>{
>                    routes.MapAreaControllerRoute("default", "yourwebproject", "{controller=Home}/{action=Index}/{id?}");
>             })
>            ;
>         }
> ```
Well, I'm still getting error in the given MVC project.

The problem is [services.AddOrchardCms() invokes AddRazorPages() internally](https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/). The same is not happening in MVC project, that's there is an error page.

**Comment by ns8482e** [comment]
MVC should work by just calling  `AddOrchardCms()`

**Comment by ns8482e** [comment]
Have you tried requesting get action using url `/tenantprefix/yourwebproject/controller/action`   ?

**Comment by Brouilles** [comment]
> configure orchard core cms as following in your startup for MVC routes
> 
> ```cs
>  public void ConfigureServices(IServiceCollection services)
>         {
>             services.AddOrchardCms()
>              .Configure( (app, routes, svc)  =>{
>                    routes.MapAreaControllerRoute("default", "yourwebproject", "{controller=Home}/{action=Index}/{id?}");
>             })
>            ;
>         }
> ```

Like @sfsharapov, it doesn't work.

**Comment by ns8482e** [comment]
It must be MapAreaControllerRoute

**Comment by Brouilles** [comment]
I know. I have try with `MapAreaControllerRoute` without success.
But I have also try with `MapControllerRoute` to see.

**Comment by sebastienros** [comment]
From the repro code I don't see any controller or action. So even if your route is fine it won't find anything to display until you actually create those and query the mapped url for it, even if it means creating one for the root url (`/`).

If you can see some content with the default ASP.NET templates it's because these also generate a controller and an action.

**Comment by inzi** [comment]
@Brouilles - Did you ever resolve this? I am having the same issue despite trying the numerous suggestions here.

**Comment by giantpenguin** [comment]
I would like to re-open this issue since I see that the issue has never been resolved.

**Comment by allschu** [comment]
> ```cs
>                    routes.MapAreaControllerRoute("default", "yourwebproject", "{controller=Home}/{action=Index}/{id?}");
> ```

This worked perfectly for me!
