### ISSUE TITLE
Create an option for enable or disable term of taxonomy

### ISSUE THREAD

**Issue by lengockyquang** [OrchardCMS/OrchardCore#10315]
### Is your feature request related to a problem? Please describe.
For example, I have a taxonomy with multiple terms such as Term A, B and C. Then I create posts for term A, B and C. But after that I want to hide term B and only display term A and C. If we remove that term (A) from the taxonomy, it also remove the relation between posts and term A. Are there any solutions to resolve this ?

### Describe the solution you'd like
May be we can have an option to disable the taxonomy terms.

**Comment by tropcicstefan** [comment]
You could define term content type with a flag 'active' and make an editor that shows only active terms.

**Comment by tropcicstefan** [comment]
See in [OrchardCore.ContentFields project ](https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore.Modules/OrchardCore.ContentFields/Views) how TextField has different editors for CodeMirror, Color, Emial, Header... 
That's what you need for TaxonomyField where you'll filter only active terms based on that active property.
You'll need to create two views in your project TaxonomyField-OnlyActive.Edit.cshtml, TaxonomyField-OnlyActive.Option.cshtml and in settings of that part change editor.

**Comment by lengockyquang** [comment]
I think i've got your point. Thanks for advices. Gonna close thiss
