### ISSUE TITLE
Fix bad async usage in RecipeHarvester

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#10329]
https://github.com/OrchardCMS/OrchardCore/blob/a4081acd2d77349530f741d88e4ab4e520d9037a/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeHarvester.cs#L56

Uses `.Result` because it is wrapped in a Linq Select

Should be adapted to use `Task.WhenAll` as the recipe reader underlying is making use of json async methods.

**Comment by jtkech** [comment]
Good catch and should be named `GetRecipeDescriptorAsync()` with the `Async` suffix

> Should be adapted to use Task.WhenAll

Or just a foreach loop to do an `await GetRecipeDescriptorAsync()` on each recipeFile

**Comment by Piedone** [comment]
"foreach loop to do an `await GetRecipeDescriptorAsync()`" is safer since it doesn't require thread safety.

**Comment by sebastienros** [comment]
Agreed with the looped await.
