### ISSUE TITLE
Verify H[].ToString() usage

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#10322]
Check that 
```
ModelState.AddModelError("foo", H["Please select one or more features."].ToString());
```

is replaced by 

```
ModelState.AddModelError("foo", S["Please select one or more features."]);
```

all over the code base

**Comment by hishamco** [comment]
I checked the code base, we are using `IStringLocalizer` in all the places except the one that you mentioned above, I wil submit a PR
