### ISSUE TITLE
Add Feature Deployment Step(s)

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1032]
I'd like to have a go at implementing this. Here's my thoughts:

- There should be two steps- Enable Features, & Disable Features. *Enable Features* will export all of the enable features from the source environment, and will enable all those features on the target. *Disable Features* will do the same, but for disabled features. Maybe at a later date add the ability to pick and choose which features end up exported?
- Is it OK for `OrchardCore.Features` to take a dependency on `Deployment.Abstractions`? I'm guessing `.Features` is the right place for this work.
- How to handle importing an enabled/disabled feature that doesn't exist on the target env? Ignore if trying to disable, fail if trying to enable?

**Comment by paynecrl97** [comment]
Edit:

- I've created a single step: `All Features`. This maintains consistency with the `All Content` steps that already exist.
- Importing is handled by the existing features recipe handler, so missing features are handled the same way as they would be when running a recipe

**Comment by sebastienros** [comment]
Great. If you want to let the user handle the missing features behavior, you could add a checkbox, "Fail if a feature is missing." that would just prevent the recipe from continuing, and cancel the current transaction. Not that steps might have started new transactions. But the Features steps should be first in the list (handled in the deployment plan manually).
