### ISSUE TITLE
How to custom endpoints url of OrchardCore.Openid?

### ISSUE THREAD

**Issue by YaoaY** [OrchardCMS/OrchardCore#1033]
For example ,
`OrchardCore.OpenId` has some endpoints such as:

/**OrchardCore.OpenId**/Access/Token

How can i visit this endpoint through /**auth**/Access/Token ?

Did i need a module like [`Orchard Rewrite Rules` ](http://orchardrewriterules.codeplex.com/) ❓

**Comment by sebastienros** [comment]
If you depend on this feature and create another rule then it should take precedence.

You can also use rewrite rules, but these will just be inbound rules, meaning the links will still be generated with the old route.

**Comment by YaoaY** [comment]
Thank you @sebastienros .

Finally I figure out that this problem is not about routing.
OpenId configured these endpoints in hardcode..
That's why `/auth/Access/Token` always results 404..

`src\OrchardCore.Modules\OrchardCore.OpenId\Services\OpenIdConfiguration.cs`
```
if (settings.EnableTokenEndpoint)
{
     options.TokenEndpointPath = "/OrchardCore.OpenId/Access/Token";
}
```

/cc @PinpointTownes @alexbocharov

**Comment by PinpointTownes** [comment]
@YaoaY the paths of the default endpoints are indeed hardcoded in the current bits and not intended to be replaced, even dynamically using some URL rewriting voodoo magic (we need static paths to expose the absolute endpoints URL as part of the OIDC discovery document).

To be honest, I've never been a huge fan of the default URLs (subjectively, they are not super pretty) so we could indeed consider making them configurable. The tricky part would be finding a way to force MVC to use this configured route and nothing else (OpenIddict will automatically rejects requests whose path doesn't match the configured value)

**Comment by YaoaY** [comment]
Work around in my custom user module (`OrchardCore.MyUsers`):


1.
Implement ` IConfigureNamedOptions<OpenIddictOptions>`
```
using OpenIddict;

namespace OrchardCore.MyUsers.Services
{
    public class MyOpenIdConfiguration : IConfigureNamedOptions<OpenIddictOptions>
    {
        public void Configure(string name, OpenIddictOptions options)
        {
            options.TokenEndpointPath = "/OpenId/Connect/Token";
        }
    }
}
```

 Need to reference the `OpenIddict` nuget package ,**keep the version consistent with which `OrchardCore.OpenId`  referenced** ( 2.0.0-preview1-0657 for now )

2.
In `OrchardCore.MyUsers.Startup.cs` 
Add route:
```
public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
 {
   app.UseAuthentication();
            
      routes.MapAreaRoute(
         name: "OpenId",
          areaName: "OrchardCore.OpenId",
          template: "openid/connect/{action}",
          defaults: new { Controller = "Access" }
       );
}
```

Regiester `MyOpenIdConfiguration`:
```
public override void ConfigureServices(IServiceCollection services)
{
   services.TryAddEnumerable(new []
     {
          ServiceDescriptor.Singleton<IConfigureOptions<OpenIddictOptions>, MyOpenIdConfiguration>()
     });
}
```

![001 qq 20170929194334](https://user-images.githubusercontent.com/8706312/31014673-b2c74d10-a54e-11e7-98d0-fe0069a06565.png)

![002 qq 20170929194428](https://user-images.githubusercontent.com/8706312/31014679-b952be58-a54e-11e7-87ec-3919ee26399e.png)

**Comment by sebastienros** [comment]
I think it could deserve a section in the readme.md
