### ISSUE TITLE
Redirect URL encoding issue on Azure

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/OrchardCore#10364]
### Describe the bug
When publishing this ```Admin/Contents/ContentItems/{ContentItemId}/Edit?returnUrl={greek or unicode characters}``` the redirect goes to ```{some encoded or strange characters url}``` and of course we are getting page not found... It happens on Azure, not on local dev env.. Both on .net 3.1 and 5

### To Reproduce
1. Publish a blogpost with permalink that contains non English characters
2. Edit this blogpost and have a redirect url the above permalink
3. See error

### Expected behavior
Non English characters should not be encoded

### Screenshots
![image](https://user-images.githubusercontent.com/1871551/135157414-d94bc6cb-204d-4168-a227-99f32a9571e7.png)

![image](https://user-images.githubusercontent.com/1871551/135157480-a3afe5a2-6880-45e1-a34e-8b3092ae6b87.png)

![image](https://user-images.githubusercontent.com/1871551/135157557-c0b8e4b8-6374-4dd7-8ac7-02842742d629.png)

**Comment by hishamco** [comment]
@urbanit can we reproduce this in localhost?

**Comment by urbanit** [comment]
As said, unfortunately it happens on Azure, not on local dev env... LocalRedirect args seem fine... @sebastienros asked me to open this in order to forward it to Azure as well..

**Comment by hishamco** [comment]
> As said, unfortunately it happens on Azure,

I though it can be reproduce on localhost but seems not

Thanks

**Comment by sebastienros** [comment]
I was able to repro locally and on Azure. I think there might be a but in OC but I want to understand how you got there.
Were you using the localization dropdown to switch languages on a content item?

**Comment by urbanit** [comment]
In a multilingual site, in blogpost detail template, the following code is used
```
{% assign allowEdit =  User | has_permission:"EditContent",Model.ContentItem %}
{% if allowEdit %}
<a href="/Admin/Contents/ContentItems/{{ Model.ContentItem.ContentItemId }}/Edit?returnUrl={{ Model.ContentItem | display_url }}" class="btn btn-primary btn-sm">Edit</a>
{% endif %}
```

**Comment by sebastienros** [comment]
I see, you added a link for editor on the front-end.

So we need to fix it in OC. It happens that url passed to `RedirectResult` should be encoded. It's documented nowhere, and aspnet templates don't do that. And it seems it can't be changed.

**Comment by sebastienros** [comment]
Can you actually try to `url_encode` the `display_url`? That's how it should be done actually. Even though it might not fix the underlying issue.

**Comment by jtkech** [comment]
Hmm, display_url uses the url helper that already encodes the url

Hmm, maybe here another encoding when evaluating the liquid expression

Maybe also try to use `| raw`

**Comment by sebastienros** [comment]
if urlhelper encodes, then that's ok, I am fixing the underlying issue and will check it works.

**Comment by sebastienros** [comment]
@urbanit  Please test the PR if you can.

**Comment by jtkech** [comment]
@urbanit just for info

And you may want to prepend your `/Admin/Contents/ContentItems/...` href

With something like this `{{ Request.UriPathBase }}` if i remember correctly

This new liquid accessor produces an escaped uri component, here for the pathBase

This to be e.g. virtual folder and / or tenant aware.

**Comment by jtkech** [comment]
@urbanit 

See my comment https://github.com/OrchardCMS/OrchardCore/issues/10383#issuecomment-932642466
