### ISSUE TITLE
Found a small bug in the TheBlogTheme

### ISSUE THREAD

**Issue by TonyWoo** [OrchardCMS/OrchardCore#1036]
Just found a small bug in the TheBlogTheme, the file is /OrchardCore.Themes/TheBlogTheme/Views/Layout.liquid.  Please see below. I think we need to change the ":" to "=". For example, the <meta charset:"utf-8"> will be changed to ` <meta charset="utf-8" >` . 
If you view the page in the mobile device, it's not responsive because the same issue one the line 7. Thanks.

https://github.com/OrchardCMS/OrchardCore/blob/7b9f8ce6a6820e3bfd0c7bf0a5e72c8d5330d066/src/OrchardCore.Themes/TheBlogTheme/Views/Layout.liquid#L5

https://github.com/OrchardCMS/OrchardCore/blob/7b9f8ce6a6820e3bfd0c7bf0a5e72c8d5330d066/src/OrchardCore.Themes/TheBlogTheme/Views/Layout.liquid#L6

https://github.com/OrchardCMS/OrchardCore/blob/7b9f8ce6a6820e3bfd0c7bf0a5e72c8d5330d066/src/OrchardCore.Themes/TheBlogTheme/Views/Layout.liquid#L7

**Comment by jtkech** [comment]
Oh yes, at one time they were liquid tags. So you are right, feel free to make a PR (let us know if you need help to do it). Thanks.
