### ISSUE TITLE
The latest updated custom setting could not be got after site settings updated.

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#10366]
### Describe the bug
Use site settings service to update a custom setting then get the updated value immediately using custom setting service. The return value is the old one.

### To Reproduce
1. Create a custom setting
2. Save the setting using below code:
```
var sp = _httpContextAccessor.HttpContext.RequestServices;
var siteInfo = await siteService.LoadSiteSettingsAsync();
var siteSettingsDisplayManager = sp.GetRequiredService<IDisplayManager<ISite>>();
await siteSettingsDisplayManager.UpdateEditorAsync(siteInfo, updateModel, false, "CustomSiteSettings");
await siteService.UpdateSiteSettingsAsync(siteInfo);
var customSettingsService = sp.GetRequiredService<CustomSettingsService>();
return await customSettingsService.GetSettingsAsync(settingsName);
```
The returned custom setting value is the same as the one before update.
But when next request come, the customSettingsService.GetSettingsAsync(settingsName) can return the latest value then.

### Expected behavior
The updated custom setting value can be returned in the current same handing request.

**Comment by jtkech** [comment]
This is intended, the session is committed at the end of a given scope, the data being persisted if the session was not cancelled before by any validation checking.

Here, after `UpdateEditorAsync()`, you may have to check if the model state is valid before doing `UpdateSiteSettingsAsync()`.

**Comment by HengzheLi** [comment]
I got it. Thanks.

**Comment by HengzheLi** [comment]
By the way, could it abstract a ICustomSettingService interface from CustomSettingsService class? It would be help on unit test.

**Comment by jtkech** [comment]
Yes, maybe in `OC.Infrastructure.Abstractions` where `ISiteService` is defined

eel free to suggest a PR
