### ISSUE TITLE
Preview Part is missing after migration

### ISSUE THREAD

**Issue by vengi83644** [OrchardCMS/OrchardCore#10360]
This is in continuation with the below bugs

https://github.com/OrchardCMS/OrchardCore/issues/8115
https://github.com/OrchardCMS/OrchardCore/issues/10359

We were not able to find the Preview part in the version 1.0.0-rc2-13450 (which was migrated from an earlier version). We migrated to this rc2 as suggested in the issue #8115 . But still couldn't find that.

So, I today migrated to the latest stable version 1.0.0 and found login issue as reported in #10359.

Then, I checked out the 1.0 Orchard Core source and wired my database and somehow I found the problem is that the UserId is null while calling the Method Microsoft.AspNetCore.Identity.GenerateClaimsAsync(user) from your service DefaultUserClaimsPrincipalProviderFactory.

But still, the PREVIEW part is missing in the Content Parts which is mentioned in the below doc.
https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/#configuring-the-preview-feature-for-blog-posts
![image](https://user-images.githubusercontent.com/5276778/135119823-36035698-f35c-4a14-9786-79078062854f.png)

Please note that, I was able to see the Preview part if I start Orchard from scratch in the latest version.

**Comment by deanmarcussen** [comment]
Can you have a look at your log files after you rmigration please?

I imagine something has failed there, and it is causing your problems with your userid

**Comment by vengi83644** [comment]
While changing the Package version from 1.0.0-rc2-13450 to 1.0.0, we haven't enabled logs. After that only, I enabled logs and got that error log mentioned in #10359.

Is there any way you guys can give me SQL scripts that can fix the migration for both UserId and Preview part?
In the below documents may be?
OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Abstractions
OrchardCore.Users.Models.User, OrchardCore.Users.Core

**Comment by vengi83644** [comment]
I compared the new launched database with my migrated database and I think I have found it.

**First bug**
UserId is not added for some users in the document type OrchardCore.Users.Models.User, OrchardCore.Users.Core

Actual: {"Id":15501,"UserName":"venky",
Expected: {"Id":15501,"UserId":"venky","UserName":"venky", 

**Second bug**
PreviewPart's PartName is set as null during the migration

Actual: {"PartName":null,"Name":"PreviewPart"",
Expected: {"PartName":"PreviewPart","Name":"PreviewPart",

I have tried adding the userId and I was able to login properly. But not able to update the Abstractions document as it is a having large content.

Let me try with other ways and come back.

**Comment by Skrypt** [comment]
You will need to use SQL JSON functions on your database to update the JSON data.

**Comment by vengi83644** [comment]
Thanks @Skrypt for the way.

During the migration, the preview part is not added in the "ContentPartDefinitionRecords".

I then included the below json and it worked.

{
	"Name": "PreviewPart",
	"Settings": {
		"ContentPartSettings": {
			"Attachable": true,
			"Description": "Provides a way to define the url that is used to render your content item for preview. You only need to use this for the content preview feature when running the frontend decoupled from the admin."
			}
		},
	"ContentPartFieldDefinitionRecords": []
}

**Comment by Skrypt** [comment]
Let us know if anything else. It is always good to have some feedback and an alternative for those who could encounter the same issue. Of course the proper path is always to make the migrations work properly but sometimes a small detail can make them fail. Best is always to look at the logs when to see what happened wrong while trying to execute the migration.
