### ISSUE TITLE
Icon for Custom Setting menu item

### ISSUE THREAD

**Issue by Azaliusz** [OrchardCMS/OrchardCore#10367]
### Is your feature request related to a problem? Please describe.
I created a setting using Custom Settings and wanted to set the item icon in the menu that came with it, but I haven't found a solution so far. 

### Describe the solution you'd like
If a `.Id(type.Name)` were added to the builder in the `CustomSettings/AdminMenu.BuildNavigationAsync` method, the menu item could be overriden with a shape named NavigationItemText-NAME_OF_SETTINGS.Id.

**Comment by Piedone** [comment]
An `AddClass()` would be useful too.

**Comment by sebastienros** [comment]
In `OrchardCore.CustomSettings.AdminMenu` call something like `AddClass(type.Classified()).Id(type.Classified)` for each created item.
