### ISSUE TITLE
Datepicker is shown transparent when editor is Localized

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#10377]
### Describe the bug
When you create a DatePicker field and select the Editor Type to localized (instead of standard), then the bug as described in 
https://github.com/OrchardCMS/OrchardCore/issues/9771 still persists

Tested in 1.0 and latest 1.1.0-preview

**Comment by hishamco** [comment]
Please screenshot

**Comment by LMSSonos** [comment]
This is the setting:

![image](https://user-images.githubusercontent.com/19758451/135669940-57f58a62-2500-4352-8230-95cbaeec62f7.png)

And here the output

![image](https://user-images.githubusercontent.com/19758451/135670044-ba3e38e9-39ef-4bbe-9fcc-64df06a88a0f.png)

If I change the setting to Standard instead of Localized it works as expected

**Comment by hishamco** [comment]
I will double check this one

**Comment by hishamco** [comment]
Which version are you using? I tried that yesterday but the localized date picker doesn't show, @Skrypt any idea?

**Comment by LMSSonos** [comment]
Tested it on `1.0.0` and `1.1.0-preview-16483`

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/136281846-5574fcb1-81dc-4951-bae0-a4112cd7be0c.png)

**Comment by hishamco** [comment]
I saw something similar, I thought it's regression bug, nothing but I saw one of your PR fixing something related if it's not the same issue. I will try to have a look again

**Comment by hishamco** [comment]
@Skrypt is this still happen after your bootstrap PR?

**Comment by hishamco** [comment]
@LMSSonos can you confirm if this still happening?

**Comment by LMSSonos** [comment]
@hishamco - I tested it in v1.4 and works now as expected in dark and light mode.

![image](https://user-images.githubusercontent.com/19758451/175878162-6b1fca5c-5c88-4fde-9a36-304a05273f35.png)
