### ISSUE TITLE
api/lucene/content did not respect size 

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#10426]
### To Reproduce
1. Go to one of those 3:
`https://localhost:44300/api/lucene/content?indexname=search&query={ "query": { "match_all": {} } }&parameters={"size": 2}`
`https://localhost:44300/api/lucene/content?indexname=search&query={ "query": { "match_all": {} } }&parameters={"size": "2"}`
`https://localhost:44300/api/lucene/content?indexname=search&query={ "query": { "match_all": {} } }&parameters={size: 2}`

2. See error: cannot see size in effect.
3. size passed in:
![lucene-size](https://user-images.githubusercontent.com/297675/136316581-b1c30548-c158-4564-85bf-ee9f9f81a739.png)
4 ln65 , only get query , no size:
![lucene-size-2](https://user-images.githubusercontent.com/297675/136316671-7b83b1bc-4af5-421b-bd20-812ac5a08fe8.png)

**Comment by infofromca** [comment]
But more important!!!
line 65 , there is big issue here or in deeper code ..., (even Fluid?):
` var tokenizedContent = await _liquidTemplateManager.RenderStringAsync(luceneQuery.Template, _javaScriptEncoder, parameters.Select(x => new KeyValuePair<string, FluidValue>(x.Key, FluidValue.Create(x.Value, _templateOptions))));`

because **size  has already been in side parameters, but output  tokenizedContent has not any info about it!!!!**

**Comment by infofromca** [comment]
@Skrypt  
it does matter how to transfer the data.
it has big issue with  the call in line 65 here , Let me repeat it:
**why the data inside IDictionary<string, object> parameters has dispeared in Ln65,
size has already been inside parameters, but output tokenizedContent has not any info about it!!!!**
which means the call has issue .
I think we should reopen this issue

**Comment by Skrypt** [comment]
Please feel free to challenge me on the issue. Maybe I've not seen something but to me, this works properly.

**Comment by infofromca** [comment]
no no no, not result, please put debug (trace cursor) to parameters  and tokenizedContent .

to be clear, I think here we either  should not use :
`await _liquidTemplateManager.RenderStringAsync(luceneQuery.Template, _javaScriptEncoder, **parameters**.Select(x => new KeyValuePair<string, FluidValue>(x.Key, FluidValue.Create(x.Value, _templateOptions))));`

or there is  a bug inside _liquidTemplateManager.RenderStringAsync method

**Comment by infofromca** [comment]
I know why!!!
You used this url:
https://localhost:44300/api/lucene/content?indexName=search&parameters={%20from:%200,%20size:%201}&query={%20%22from%22:%20{{%20from%20}},%20%22size%22:%20{{%20size%20}},%20%22query%22:%20{%20%22match_all%22:%20{}%20}}
for this, luceneQuery.Template already contain the info about size , then got them in the result of tokenizedContent.
but pay atten to it, **those size and from not come from parameters**, you did tricky in your demo.

now the issue I am focusing is that the data of parameters does not merge to the result and then  tokenizedContent has not any info from parameters.
to test , please change parameters to something like {anypeoperty: anyvalue}

**Comment by sebastienros** [comment]
To summarize, the query that needs to be entered is:

```
{ 
  "from": {{ from | json }}, 
  "size": {{ size | json }}, 
  "query": { "match_all": {} }
}
```

This is a Liquid template, so the `{{ size }}` will be replaced with `1`.
