### ISSUE TITLE
AutoSetup seems not to start

### ISSUE THREAD

**Issue by timbuktuuu** [OrchardCMS/OrchardCore#10430]
### Describe the bug
I try to setup a OrchardCore Installation with the AutoSetup Feature for local development. But it looks like the AutoSetup is never called.

### To Reproduce
1. Solution with basic NuGet packages
2. Running inside its own Docker Container 
3. Database gets initialized on docker startup up. After this the CMS is initializing
4. Database Container and Orchard Container in the same Docker network

### Expected behavior
It should work like expected and the Setup page is history

**Comment by Skrypt** [comment]
It should work. Without repro steps we can't really help. It could be the appsettings.json configs who are wrong. It could be that it requires to set a Global environment var so that this works with Docker.
