### ISSUE TITLE
Wysiwyg add feature selection options?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1045]
such as
![p nf1d22n_46df 9duw8vs](https://user-images.githubusercontent.com/28694676/31012923-452b955c-a546-11e7-9003-865c931a21b7.png)
![vfny k 1qj2wj j e nuy 7](https://user-images.githubusercontent.com/28694676/31012927-49316e88-a546-11e7-8b93-f99ff5a59f59.png)

**Comment by agriffard** [comment]
I guess you have the same error than in #1039 if you open your console? : jQuery is not defined.
