### ISSUE TITLE
ContainedPartDisplayDriver add Display

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#10450]
Show ListContentItem

![image](https://user-images.githubusercontent.com/16968103/136732932-4952d16d-60ab-41cd-8da6-f9bdca225e6e.png)

**Comment by sebastienros** [comment]
Could you try to write some text explaining what you mean?

**Comment by chinasqzl** [comment]
In BlogPost DetailAdmin, some of the information for the blog is displayed.
![image](https://user-images.githubusercontent.com/16968103/139635653-a27250d2-7e1b-4fcd-b5ee-3ac4699557e6.png)

**Comment by deanmarcussen** [comment]
> In BlogPost DetailAdmin, some of the information for the blog is displayed.

Yes this is correct, some information is displayed in `DetailAdmin`.

It looks like you have already written a custom display driver to show the extra information you want to display (which is good Orchard Core is designed to be extensible to support adding custom features)

Do you want this to be a standard feature, e.g. a link back to the parent of the list?

We already have a link back to `Edit` the parent in the List display, and normally contained items aren't set as listable in the normal admin contents list.

**Comment by chinasqzl** [comment]
Thumbnail that displays the blog

Default Thumbnail:
e.g. a link back to the parent of the list
