### ISSUE TITLE
Use Orchard 2 for relational data

### ISSUE THREAD

**Issue by gentledepp** [OrchardCMS/OrchardCore#1046]
Hello!
Me again... (sry for bothering)

I would like to use orchard 2 for some kind of relational data.
Say I create a content type **device**
Device has normal text-fields like **serial number**, **description**
but also a field **type** which defines the current device's type. (e.g. Laptop or whatever)
Now that type is not simply text, but a reference to a content type **device type".
It displays the "title" part of the referenced content item (of type device type)

1) when the user enters some text into that field, it should work like an autocomplete textbox and show the list of devices matching the current filter
2) if there is no suitable device type, and the user hits [enter], I would like to open a dialog that allows the user to enter a new device type (content item) which is then used.
3) if the user clicks the search button next to that autocomplete textbox, a search dialog should open, allowing the user to search for a suitable type based on one or more columns/fields of that content type

Now the device could also have other "reference" fields like this, and the referenced items as well and so on.

I am perfectly aware that this is not part of the intended basic functionality, however, I wonder if there was a "good way" to implement this feature.
Or if you think that this won't ever work, because of some technical issues, I would appreciate if you told me so and elaborated a little so I understood your opinion.

**Comment by gentledepp** [comment]
Here is a description on how something like this could be achieved in orchard 1.x
http://docs.orchardproject.net/en/latest/Documentation/Creating-1-n-and-n-n-relations/

**Comment by sebastienros** [comment]
You are asking for the taxonomy module actually. Or the Content Item picker field. Taxonomy is the next thing on my list, so it should be here in the next month.

**Comment by sebastienros** [comment]
Duplicate #1141
