### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by 454020312** [OrchardCMS/OrchardCore#10472]
Orchard Core 1.0.0 版本
Release notes https://docs.orchardcore.net/en/latest/docs/releases/1.0.0/
Admin界面 多语言  需要 在Features界面中 开启一次 Localization 才能生效 会有些不友好,全局默认的没生效

**Comment by hishamco** [comment]
It's not clear what you asking for, Please use English to clarifiy what you mean. In case of releases please check the [releases](https://github.com/OrchardCMS/OrchardCore/releases)
