### ISSUE TITLE
Using Orchard 2 with EntityFramework Core

### ISSUE THREAD

**Issue by gentledepp** [OrchardCMS/OrchardCore#1047]
We think about migrating from an asp.net web app to orchard core.
That web app uses entity framework as data access layer.
To ease the migration, we might have to actually use EF Core alongside with YesSql.

Could that work?

The main concern I have is with the table prefixes as I do not know how these can work with EF Core code first migrations.

As I recall, you started out using EF Core as YesSql did not exist back then. So I was hoping you could give me a solution?

Thank you so much!

**Comment by sebastienros** [comment]
I don't remember if I handled table prefixes when I worked with EF. Probably not as I was trying the have some stuff to work before.

I assume you would have to just define a custom mapping for each tenant and add the prefix yourself.

**Comment by gentledepp** [comment]
Thanks!
