### ISSUE TITLE
Edit "Content Parts Display Name" is invalid

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1049]
Edit "Content Parts Display Name" is invalid

![6](https://user-images.githubusercontent.com/28694676/31044769-fcece8f0-a607-11e7-9825-8e460901e23f.gif)

**Comment by agriffard** [comment]
I confirm the problem exists when you want to change the Display Name of a Content Part.

I also encountered a nother one:
If you edit a Content Type and change the Display Name then save, it works but if you change again and save one more time it doesn't work. It only works if you reloads the page, not after the redirect.

**Comment by agriffard** [comment]
The DisplayName of the EditPartViewModel loks like this :
```
public string DisplayName
        {
            get { return !string.IsNullOrWhiteSpace(_displayName) ? _displayName : Name.TrimEnd("Part").CamelFriendly(); }
            set { _displayName = value; }
        }
```
but it is never set and the `ContentPartDefinition `and the `ContentPartDefinitionRecord `don't have a `DisplayName` property either.

**Comment by pgy866** [comment]
But i'm not programming! So hope to fix it!
thank you very much!

**Comment by agriffard** [comment]
It is just to give some details about what happens and what should be fixed.
