### ISSUE TITLE
Decode UTF in Link Field

### ISSUE THREAD

**Issue by sergeor** [OrchardCMS/OrchardCore#10520]
The item that holds the URL, Link Field, does not accept non-Unicode characters.
For example the link /τροφιμα/ψαρια must encode to %2F%CF%84%CF%81%CE%BF%CF%86%CE%B9%CE%BC%CE%B1%2F%CF%88%CE%B1%CF%81%CE%B9%CE%B1 and then save.
The annoying thing is that when I edit it I, must decode it, if I want to read it.

It will be nice if non-latin characters encoding and decoding in background

**Comment by sebastienros** [comment]
Is your issue with the way it is encoded in the html output? It works fine to me.

```html
<div class="field field-type-linkfield field-name-foo-link">
    <a href="http://google.com/&#x3C4;&#x3C1;&#x3BF;&#x3C6;&#x3B9;&#x3BC;&#x3B1;/&#x3C8;&#x3B1;&#x3C1;&#x3B9;&#x3B1;?query=&#x3C8;&#x3B1;&#x3C1;&#x3B9;&#x3B1;">The link</a>
</div>
```

![image](https://user-images.githubusercontent.com/1165805/138334260-a837feaf-58e6-461a-8764-c7a0fb4c3d4a.png)

In this case it's documented here: https://docs.orchardcore.net/en/latest/docs/guides/encoding-settings/

**Comment by sebastienros** [comment]
Ah! That explains. When I saw the same error I assumed it didn't accept relative urls at all. That's probably the actual issue, the validation we do server-side.
