### ISSUE TITLE
OrchardCore as a Nuget package in AspNetCore web app results in 404

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#1052]
This was mentioned in #1017 by @alexbocharov, but unless I'm mistaken an issue has not been created for it:

Following the rename OrchardCore.Cms -> OrchardCore.Application.Cms.Targets (PR #997) running a vanilla AspNetCore web application with reference to OrchardCore.Application.Cms.Targets results in a 404. Essentially the Packages folder is not generated.

Steps to reproduce: http://www.ideliverable.com/blog/getting-started-with-orchard-core-as-a-nuget-package (thanks @paynecrl97).

_Workaround is either revert to 1.0.0-beta1-3216 or reference OrchardCore.Application.Cms.props, OrchardCore.Application.targets (in the host), OrchardCore.Module.props (in modules) and OrchardCore.Module.props and OrchardCore.Theme.props (in themes)._

**Comment by jtkech** [comment]
I think it's because the targets or props file name must match the package ID.

E.g we would need to replace

    OrchardCore.Application.Cms.props
    OrchardCore.Application.targets
    OrchardCore.Module.props
    OrchardCore.Theme.props
    ...

With

    OrchardCore.Application.Cms.Targets.props
    OrchardCore.Application.Targets.targets
    OrchardCore.Module.Targets.props
    OrchardCore.Theme.Targets.props
    ...

**Comment by sebastienros** [comment]
I didn't think about it when I decided not to include the suffix in the file names ... thanks
