### ISSUE TITLE
OC.Module.Targets NuGet package- include Module.txt file?

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1056]
After installing the `OC.Module.Targets` package into a class library, the next two things you'll need to do in order for the features to appear in the admin section are:

1. Add a reference to your module from your web project
1. Add a `Module.txt file`

I don't think there's anything we can do to automate the first thing, but we *could* add a template for a `Module.txt` into the correct location. This would help streamline module creation. The same is true for themes.

I don't think this is as simple as simply adding the file to the `Content` folder of the package, as it'd get overwritten on every update. But could we use powershell to move the file to the correct location if it doesn't already exist?

Another option would be to display a 'next steps' page in VS after installing the package (I've seen this a few time, Glimpse is one example that comes to mind).

**Comment by jtkech** [comment]
What we already have through an msbuild task (executed when building) is that if there is no manifest file, a simple one (with only the module name = project name) is created under the `obj` subfolder, [see here](https://github.com/OrchardCMS/OrchardCore/blob/master/src/OrchardCore/OrchardCore.Module.Targets/OrchardCore.Module.Targets.props#L18).

Then, this simple manifest file is copied under the `/Packages` folder, [see here](https://github.com/OrchardCMS/OrchardCore/blob/master/src/OrchardCore/OrchardCore.Module.Targets/OrchardCore.Module.Targets.props#L41).

Maybe better to create this simple manifest file just under the module directory (not under the `obj` subfolder), then people could complete it without having to create it here, i don't know...

**Comment by sebastienros** [comment]
Templates.

**Comment by petedavis** [comment]
@jtkech  Adding the Module.txt folder under obj folder is broken.

![image](https://user-images.githubusercontent.com/164331/33937685-44cce982-e054-11e7-9091-96010bb0103f.png)

You cannot delete the missing file as visual studio prevents deleting files written by the targets props file.

**Comment by jtkech** [comment]
@petedavis ok thanks.

This file is generated (with only the module name) and used only if you don't have the regular one (with additional infos) directly under your module folder.

So, i will do a PR to clean it automatically if it exists and a regular one has been added.

**Comment by jtkech** [comment]
Done through #1295.
