### ISSUE TITLE
Intermittent encoding issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10597]
![Sans titre](https://user-images.githubusercontent.com/3228637/139541861-c60c1068-15f6-43f0-9db3-6b97b69feb62.jpg)

![image](https://user-images.githubusercontent.com/3228637/141827655-afeb3b64-40e1-4d48-8534-8ea882e19a29.png)

Strange encoding issue happening intermittently

**Comment by hishamco** [comment]
I already notice that too, I though it's something crazy or stupid happend in my browser cache ;)

**Comment by sebastienros** [comment]
Javascript bug

**Comment by Skrypt** [comment]
I'm starting to think that this is because these are 2 special chars.

**Comment by sebastienros** [comment]
Might be a bug in a previous version of Fluid. I fixed a race condition that could create issues with text buffers.

**Comment by Skrypt** [comment]
I'm currently working on the Bootstrap 5 branch on which I merged the latest main branch last night so I should have the latest Fluid bits.­

**Comment by deanmarcussen** [comment]
Don't think it's Fluid, this is all razor rendered code.

I see it also sometimes, in development @Skrypt - don't think I've ever seen it in prod

Thought it might have been font awesome javascript related, but you're right it's all around those special chars we use for the dash and the menu expansion.

**Comment by sebastienros** [comment]
The html to render it is 

```html
<span class="hint dashed">@T["Check to set this content item as the homepage once published."]</span>
```

This is the `dashed` definition:

```scss
.hint,
.text-muted {
    &.dashed::before {
        content: '\2014\00a0';
    }
}
```

And it's correctly processed in css (I checked the minified version too)

```css
:root[data-theme=default] .text-muted.dashed::before {
  content: "— ";
}
```

So it looks like something is incorrectly transmitting the unicode chars or interpreting them. Could be chrome or asp.net. We need to see what is on the wire to locate the issue. When it occurs please look at the network tab and report the results.

**Comment by Skrypt** [comment]
So on the network tab it did'nt download the css file though. If I look at sources I can definitely see that the css file uses these strange chars.

![image](https://user-images.githubusercontent.com/3228637/145644200-abf6fcfc-3ae3-4137-a853-e31671c4e3a0.png)

**Comment by Skrypt** [comment]
Here is the same CSS file after a refresh : 

![image](https://user-images.githubusercontent.com/3228637/145647119-3daa0a88-61a3-4050-bdd2-b0d539b82e6a.png)

**Comment by sebastienros** [comment]
The `?v=` parameter has changed. When is it changing and how is it computed? Only to understand why the content downloaded would be different.

**Comment by sebastienros** [comment]
Would be good to see the charset and all the headers sent on the requests.

**Comment by jtkech** [comment]
Maybe helpful

https://github.com/FortAwesome/Font-Awesome/issues/14660#issuecomment-790734298

**Comment by Skrypt** [comment]
Though this is not a font-awesome char. These are simple styles with special chars.

**Comment by Skrypt** [comment]
Here are the request headers on a successful request.

![image](https://user-images.githubusercontent.com/3228637/145650641-d4678626-6171-400e-a811-d8a2b7b3db55.png)

**Comment by Skrypt** [comment]
Here again. Modified a Razor template and Hot Reload refreshed the page : 

![image](https://user-images.githubusercontent.com/3228637/145651100-86a15abe-2418-4ecf-bc25-6e39adc1eaca.png)

**Comment by jtkech** [comment]
> Though this is not a font-awesome char. These are simple styles with special chars.

Okay, but maybe the same issue, but not sure at all ;)

That said they recommend to not only define the charset as a meta but also at the beginning of css files.

**Comment by Skrypt** [comment]
The version of the CSS changes on every Hot Reload refresh.

**Comment by jtkech** [comment]
But do we have the charset defined at the beginning of css files?

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/145651326-e4da8f8d-28c8-4c35-a907-5d5a74d83abe.png)

**Comment by Skrypt** [comment]
No, but we use `<meta charset="utf-8">` so that should cover it.

**Comment by jtkech** [comment]
But they recommend both for their issue, but maybe not the same issue here ;)

**Comment by Skrypt** [comment]
Ok, reading and it seems like they are saying that the issue comes from dart-sass.

**Comment by Skrypt** [comment]
But looking at the CSS files everything is there. `@charset "UTF-8";`

**Comment by Skrypt** [comment]
Also served correctly : 

![image](https://user-images.githubusercontent.com/3228637/145652148-243d3fdb-37c1-48ba-a9c8-b2ee5ad4f9fb.png)

**Comment by jtkech** [comment]
Just saw this too in TheAdmin.css ;)

    :root[data-theme=darkmode] .blockquote-footer::before {
      content: "â€”Â ";
    }

**Comment by Skrypt** [comment]
You can see the file is saved also as UTF-8

![image](https://user-images.githubusercontent.com/3228637/145652324-18db12d6-70a4-43eb-9001-763c709b6383.png)

**Comment by jtkech** [comment]
Yes I saw it

**Comment by Skrypt** [comment]
So it's in the transport or when we version it? But the version file just defines a new URL to bust the CSS cached on the client-side.

**Comment by jtkech** [comment]
When I request manually TheAdmin.css the weird chars are always in this file

But didn't see yet in any rendered page

**Comment by Skrypt** [comment]
Same here : 

![image](https://user-images.githubusercontent.com/3228637/145652848-79e3b19a-4bd3-479a-92a4-0f09c6d078de.png)

**Comment by jtkech** [comment]
This is he one to collapse the menu

    :root[data-theme=darkmode] .leftbar-compactor:before {
      content: "âŸª";
   }

**Comment by Skrypt** [comment]
Okay, so it is always served with strange chars even though it is saved as a UTF-8 file. Maybe the issue is in our code then.

**Comment by jtkech** [comment]
Okay charset is present in the generated theAdmin.css

But maybe should be at the beginning of e.g. `_sidebar-menu.scss`

Before generation of the final output file

**Comment by Skrypt** [comment]
I don't think the issue is with the generation made by dart-scss because the files are encoded properly with UTF-8.
And when they are served they are not.

**Comment by jtkech** [comment]
Okay putting the following at the very beginning of TheAdmin.css file directly

    @charset "UTF-8";

Fixed the issue

    :root[data-theme=default] .leftbar-compactor:before {
      content: "⟪";
    }

**Comment by Skrypt** [comment]
Do you think it is because we added comments before that line?

**Comment by jtkech** [comment]
It looks like

**Comment by jtkech** [comment]
But the weird chars don't render in my browser

**Comment by Skrypt** [comment]
It's worth nothing trying to remove the comments OR adding it all the time in these comments as the first line?

**Comment by jtkech** [comment]
And if I remove completely `@charset "UTF-8";`

These chars now appear also in my browser ;)

![Weird chars](https://user-images.githubusercontent.com/8586360/145655139-6b8edcbf-560c-493f-91d9-a5d7831929c5.png)

**Comment by Skrypt** [comment]
Ok make a PR 🙈 🎅🏼

**Comment by Skrypt** [comment]
Friday is the day that things gets done 😉

**Comment by jtkech** [comment]
But are these comments auto generated by gulp?

**Comment by Skrypt** [comment]
Yes

**Comment by jtkech** [comment]
Okay simple to remove, I let you do a PR ;)
