### ISSUE TITLE
Dropdown Menus and Bootstrap Select in RTL

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10591]
### Describe the bug

The dropdown menus and Bootstrap Select in RTL are not displayed properly.

### Screenshots

https://user-images.githubusercontent.com/3228637/139500661-284441c2-1e29-4790-94f9-ffa775688ea4.mp4

**Comment by Skrypt** [comment]
@tropcicstefan @hishamco 

Opened this issue to track instead of holding a good PR.

Thanks.

**Comment by tropcicstefan** [comment]
It appears bootstrap select [doesn't support RTL](https://github.com/snapappointments/bootstrap-select/issues/862)

Maybe the solution is to align right for LTR and align left for RTL?

**Comment by Skrypt** [comment]
I'm working on Bootstrap 5 PR will take a look and decide if we deprecate these badly supported third-party librairies.

**Comment by hishamco** [comment]
I can replce this later after finishing Bootstrap 5 updates

**Comment by Skrypt** [comment]
I'm actually testing what Github uses for these dropdown menus.

https://github.com/github/details-menu-element

**Comment by sebastienros** [comment]
Is this fixed in the BS5 version of the plugin?

**Comment by Skrypt** [comment]
The issue seems to be still open even if there are PR's that got merged. I don't know the details yet but at the same time, I'm asking myself if `Bootstrap Select` is necessary. Will need to be evaluated. The `Bootstrap Select` component has a PR for Bootstrap 5 but it's been in development for 7 months. Bootstrap Slider has no PR for Bootstrap 5 yet. So, we are dependent on these libraries which don't get updated really quickly.

The `details menu` from `Github` seems to be quite simple and has no dependency on `JQuery` which seems more appealing to me.

**Comment by hishamco** [comment]
@Skrypt you can assign this to me, I will find a time to revise this one

**Comment by hishamco** [comment]
This has been fixed after BS5
