### ISSUE TITLE
Unable to load item"OrchardCore.Application.Targets"""OrchardCore.Application.Cms.Targets""details! operation failed!

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1059]
In the new test!
https://github.com/OrchardCMS/OrchardCore/tree/67ba2e9c31310e75e4b87a69ebb7da59e745a7f6

An error occurred while restoring the "nuget" package, and the operation failed because the details of the project "........." could not be loaded.

![s71004-032329 1](https://user-images.githubusercontent.com/28694676/31144559-b7bd1c42-a8b3-11e7-988c-c1410c80582f.jpg)

https://github.com/OrchardCMS/OrchardCore/tree/67ba2e9c31310e75e4b87a69ebb7da59e745a7f6/src/OrchardCore/OrchardCore.Application.Targets

https://github.com/OrchardCMS/OrchardCore/tree/67ba2e9c31310e75e4b87a69ebb7da59e745a7f6/src/OrchardCore/OrchardCore.Application.Cms.Targets

**Comment by sebastienros** [comment]
Change your project properties to target netcore2.0

**Comment by pgy866** [comment]
I see it seems to have been repaired! Efficiency is great! thank you very much!
