### ISSUE TITLE
OrchardCore.Users LinkExternalLogin [POST] signs-in users when email is not verified.

### ISSUE THREAD

**Issue by XpandIT-RFID** [OrchardCMS/OrchardCore#10626]
Hi, I just noticed that as a user that just made an account and haven't verified the email I can just go and link to an external provider and it signs me in after linking.

If I log out I can't log back in unless I verify my email, as expected.

I think this is a bug that needs fixing. For now I will just make my own LinkExternalLogin POST and override the View.

**Comment by sebastienros** [comment]
Looks like we should only link external accounts if the user is actually authenticated, and the local account's address is verified if required.

**Comment by XpandIT-RFID** [comment]
This is what I did on my case:
![image](https://user-images.githubusercontent.com/83280308/140509835-4ed8fa80-6ff1-4c60-bc10-92ca8e92dbbb.png)
If the user doesn't have his email confirmed then I just return to the login page with an exception.
This worked for me, but maybe the LinkExternalLogin Action should be revised.

**Comment by ns8482e** [comment]
It seems working as expected  with following settings - using Azure AD

![image](https://user-images.githubusercontent.com/23270244/140524249-927fe0c4-4a96-4ae6-b1d4-5efd45f1c088.png)


it doesn't allow to login if email is not verified 

![image](https://user-images.githubusercontent.com/23270244/140524096-1a496114-4516-41e0-86ff-aa50e28157ed.png)

**Comment by XpandIT-RFID** [comment]
Hm, I am on version 1.0 of OrchardCore that may be it.
Also I am testing with Facebook and Google.

**Comment by ns8482e** [comment]
I am using Azure AD. However - The setting is for `User Registration` feature that applies to all external login - you have to enable it.

If you don't have "Users must verify" checked then it will allow non-verified users - to login

**Comment by XpandIT-RFID** [comment]
Yeah I have it enabled.
![image](https://user-images.githubusercontent.com/83280308/140526683-2297e2e5-91ff-4a7b-ac49-aea4328b22c8.png)

This may be a 1.0 bug, or could also be something in my code. 
Thanks for clarifying :)

**Comment by Skrypt** [comment]
@sebastienros Not sure what needs to be done on that one.

**Comment by sebastienros** [comment]
@XpandIT-RFID would you mind trying with 1.1 just to be sure it was fixed?

**Comment by sebastienros** [comment]
In parallel can someone else try to repro and confirm the issue can't be reproed?

**Comment by deanmarcussen** [comment]
It's quite an edge case, but I did find the issue, so no need to check it on 1.1 @XpandIT-RFID
