### ISSUE TITLE
The admin  menu manage page  cannot  be dragged

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#10642]
![admin menu error](https://user-images.githubusercontent.com/15613121/140546612-c14d0884-eece-4b91-b3ab-65a7c02fd7ae.gif)

**Comment by hyzx86** [comment]
![admin menu error2](https://user-images.githubusercontent.com/15613121/140546977-ef0d017e-5a0f-48c7-8bdf-6eb06e3f040d.gif)

**Comment by hishamco** [comment]
Seems it's regression bug, @agriffard  @Skrypt any idea?

**Comment by Skrypt** [comment]
I saw this in the Bootstrap 5 branch. I thought it was because of that. Now, it's a regression from an updated javascript dependency. I think it is JQuery UI.

**Comment by deanmarcussen** [comment]
Should just switch it to use SortableJs - the underlying library the vue draggable uses. We use it in other places, it’s good and simple

**Comment by LunarChild** [comment]
It seemed that the file:jquery-ui.js makes this trouble .but when I use the Nuget lib and publish a website this function work

**Comment by sebastienros** [comment]
@deanmarcussen says we should try the new version of NestedSortable

**Comment by deanmarcussen** [comment]
https://github.com/ilikenwf/nestedSortable

**Comment by scleaver** [comment]
I was seeing this same in the site menu module... but seems to be fixed in the latest OC as of today - #10798 (this is the commit I am testing on) @Skrypt

**Comment by Skrypt** [comment]
From looking at the repository @deanmarcussen linked and the file we have there is no update available on the component. We use the latest available. Which means it has not been updated since 2016.

**Comment by Skrypt** [comment]
I think we need to either replace it with https://github.com/SortableJS/Sortable or revert the changes on the JQueryUI version update.

**Comment by Skrypt** [comment]
Actually, now that I'm looking at the code there's not been any update on JQuery-UI for a while. So, it's just the nestedSortable.js component that doesn't work anymore with the latest browsers.

**Comment by deanmarcussen** [comment]
I tried reverting jquery ui this morning with @scleaver and it worked (v 1.12 I think)

Might be best to revert in the short term

**Comment by Skrypt** [comment]
ahh ! Now I see

![image](https://user-images.githubusercontent.com/3228637/144652917-b5b6a78e-dc20-4dfc-b9da-8e36524415b4.png)

**Comment by Skrypt** [comment]
Ok I agree on the change just revert to JQuery-ui 1.12.1

**Comment by Skrypt** [comment]
See #10804
