### ISSUE TITLE
Implement customized field editors

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1064]
c.f. #717, https://github.com/OrchardCMS/OrchardCore/issues/689

We need to configure field editors. After choosing the editor, the settings UI shows up on a separate page, like parts.

**Comment by pgy866** [comment]
The new source code compiles through, publishes the Web error, I cannot solve some errors lets him publish through the web!

Is this function like this one?
https://github. com/orchardcms/orchardcore/issues/1045

**Comment by sebastienros** [comment]
@pgy866 yes I think this is related

**Comment by Skrypt** [comment]
Related https://github.com/OrchardCMS/OrchardCore/issues/2105
