### ISSUE TITLE
Simplify the Pluralization APIs

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#1065]
@sebastienros I have looked to localization APIs, specifically pluralization, and I'm already logged an issue from the early days of ASP.NET Core to support it out-of-the-box https://github.com/aspnet/Localization/issues/17

After digging into the pluralization APIs seems it's similar to what I did before year ago in the PR https://github.com/aspnet/Localization/pull/305, my plan is to simplify the APIs and remove unnecessary types to make things work as expected.

By doing this the `PortableObjectStringLocalizer` will inherit from`IPluralizeStringLocalizer` rather than `IStringLocalizer` which is make sense. So any custom `StringLocalizer` will have an option to support pluralization or not, because not all the resource providers supports pluralization

Please let me hear your feedback ..

**Comment by sebastienros** [comment]
I looked for this interface and found `IPluralStringLocalizer`. I think we should remove it, it was something I had done a long time ago before we work on the PO localization. Not sure if you are referring to it or not.

**Comment by hishamco** [comment]
Yep it's there in my PR, in general we can simplify the pluralization APIs by removing many of existence types and use `IPluralStringLocalizer` instead

**Comment by sebastienros** [comment]
If it's simpler ... fine but we might disagree on the definition of simpler ;) let's see what you have in mind in the PR. And thanks for the help.

**Comment by hishamco** [comment]
I'm working on a prototype, hope I will ping you when it's ready
