### ISSUE TITLE
Can't specify a culture when rendering dates in liquid

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/OrchardCore#10655]
### Describe the bug
Can't specify culture when rendering dates in liquid. For example the code...
```
{{ Model.ContentItem.Content.Session.Date.Value | date: "%A %e %B %Y" }}
```
...renders 'Zaterdag 6 november 2021' on my development machine with a Dutch OS. But when I deploy this code to my webserver with an English OS, it renders 'Saturday 6 November 2021'. As the site is completely in Dutch, I want to able to specify a culture here.

I tried this piece of code in startup.cs...
```
services.Configure<TemplateOptions>(options =>
{
    options.CultureInfo = new System.Globalization.CultureInfo("nl-BE");
});
```
...but it made no difference.

### To Reproduce
1. Display any date in Liquid using the format `%A %e %B %Y`
2. Try to show the results in a different language than your OS.

### Expected behavior
I want to able to specify a culture.

**Comment by hishamco** [comment]
I quote from Fluid docs

> Formats date and times using standard .NET date and time formats. It uses the current culture of the system.

Try to Set the `CurrentCulture`

**Comment by netwavebe** [comment]
@hishamco : where?

**Comment by hishamco** [comment]
You can set it on top of your view

**Comment by hishamco** [comment]
Also if you enable the localization module this will be done automcatically

**Comment by netwavebe** [comment]
No localization module here as the site is Dutch only. By 'view' you mean liquid template? I don't have razor views if that's what you mean?

**Comment by ns8482e** [comment]
@netwavebe  It's taking `CurrentUICulture`

This is output for liquid syntax `{{ "2022-03-16" | date: "%A %e %B %Y" }}`

![image](https://user-images.githubusercontent.com/23270244/140651144-68544c65-f5cd-4a96-b8c0-2fdfb1d11cfc.png)

Localization -> Cultures -  Settings in Orchard Admin

![image](https://user-images.githubusercontent.com/23270244/140651241-4ff13aec-961f-4fb2-ae65-04ec561df923.png)

Settings in Chrome

![image](https://user-images.githubusercontent.com/23270244/140651064-8194df00-031d-4129-be18-cb4521d26aa4.png)

**Comment by ns8482e** [comment]
> Try to Set the `CurrentCulture`

It won't have any effect as OC's View engine is overriding `TemplateOptions` with `CurrentUICulture`

**Comment by netwavebe** [comment]
Thanks @ns8482e. I'm trying to get this working without the localization module.

**Comment by hishamco** [comment]
> It won't have any effect as OC's View engine is overriding TemplateOptions with CurrentUICulture

I didn't dig into `TemplateOptions`, thanks anyway @ns8482e

**Comment by netwavebe** [comment]
`CultureInfo.DefaultThreadCurrentUICulture = new System.Globalization.CultureInfo("nl-BE");` in `Startup.cs` seem to do the trick!

So in summary:

- If 'Localization' is enabled, there is no problem
- If 'Localization' is not enabled, it takes the culture of the server OS. There is no way to specify the default culture? I believe this was possible in Orchard 1?

**Comment by hishamco** [comment]
I already told you to set the CurrentCulture ;) happy that works with you

**Comment by netwavebe** [comment]
> Also if you enable the localization module this will be done automcatically
Actually, I should have listened to this advice.

Dug deeper in what happened to the default culture, and saw https://github.com/OrchardCMS/OrchardCore/pull/3732 and https://github.com/OrchardCMS/OrchardCore/issues/3559. The default culture setting was moved from `SiteSettings.cs` to the `Localization` feature.

After enabling this feature, everything worked fine. I hestitated to enable the feature because I thought it would also enable content item localization, which I do not want. However, that is a seperate feature.

Hope my experience can help someone in the future.

Thanks guys!

**Comment by Skrypt** [comment]
Yes, we don't change how ASP.NET works. The fallback to system OS is from ASP.NET Core. So, when you enable the Localization module. The Localization module is just a wrapup on top of the ASP.NET Localization middleware.

**Comment by Skrypt** [comment]
As for your current content items they will be treated as if they were in the default culture unless you would enable the Content Localization module. Then, you would need to assign the Localization Part to your Content Types that you want to localize. Then, now these content items would become of Invariant Culture unless you would re-publish them with a specific supported culture set previously in the Admin UI settings.

There are still caveats with these localized content items. For example, you can remove supported cultures while having still content items in that culture. We don't prevent doing this and maybe we should.

**Comment by netwavebe** [comment]
Thanks for the clarification, @Skrypt!

For the liquid syntax to be localized, all I had to do was enable the Localization feature. Nothing else. 'nl-BE' was already set correctly (not sure how OC knew this, especially on the webserver).

For this website, I don't need content localization at all as it's Dutch-only. So literally one click fixed my problem :wink:

**Comment by Skrypt** [comment]
You probably had something in the database when it tried to `InitializeLocalizationSettingsAsync()`... `siteSettings.As<LocalizationSettings>()`
Else, `CultureInfo.InstalledUICulture.Name` returned `nl-BE`.
