### ISSUE TITLE
Docker Localization .po files issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10678]
I'm testing with the latest OrchardCore Linux Docker image and the .po files don't seem to be loaded or present at all.
This works though locally when building Orchard Core source code.

![image](https://user-images.githubusercontent.com/3228637/140954352-ad4e730e-596b-4129-aa74-4395ebb8765e.png)

**Comment by sebastienros** [comment]
We probably forgot to copy the localization files in the destination folder

**Comment by hishamco** [comment]
> We probably forgot to copy the localization files in the destination folder

The localization files got copied during the build, Am I right?

/cc @jtkech
