### ISSUE TITLE
FlowPart Wysiwyg/Trumbowyg configurations

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10670]
### Is your feature request related to a problem? Please describe.
We have custom configurations of Trumbowyg editor for ContentField and HtmlBodyPart but from the FlowPart it is not configurable.

### Describe the solution you'd like
We should be able to change the configuration of the Wysiwyg editor used in the FlowPart.

### Describe alternatives you've considered
Currently overriding the HtmlField-Wysiwyg.Edit.cshtml template to achieve this.

```javascript
        var settings = { 
            lang: '@culture.TwoLetterISOLanguageName',
            semantic: false
        }
```

**Comment by deanmarcussen** [comment]
Wouldn’t you just change the editor for the widget to the trumbowyg editor?

the culture settings issue re:this editor is because trum doesn’t support all Langs Oob, so the js needs to be null checked and when it exists should be spread. (Sorry I know it’s a different issue but you reminded me)

**Comment by Skrypt** [comment]
I mean in this case what I wanted is to configure the Trumbowyg to not enforce using a `<p>` as it's first dom element by setting `semantic: false`. But, right now we can't configure the settings of the editor in a FlowPart. Wether it would be changing it for a different one or to be able to configure its settings.

**Comment by sebastienros** [comment]
Please check with Trumbowig editor type instead of Wysiwyg
