### ISSUE TITLE
Multiple GetMedia calls when adding a folder

### ISSUE THREAD

**Issue by dannoh** [OrchardCMS/OrchardCore#10680]
When you click OK on the new Media Folder name dialog the first thing it does after creating the new folder is emits 'beforeFolderAdded' which loads the folder we are currently on.  Then it emits the 'folderAdded' which selects the new folder (triggering a load of the new folder through the watcher)
It appears that both requests are in flight at the same time, and we are seeing that occasionally the beforeFolderAdded request comes in last and then makes it appear as if the new folder has all the contents of the previously selected folder.

```javascript
bus.$on('addFolder', function (target, folder) {
    if (self.model == target) {

        bus.$emit('beforeFolderAdded', self.model);
        if (self.children !== null) {
            self.children.push(folder);
        }                
        folder.parent = self.model;
        bus.$emit('folderAdded', folder);
    }
});
```

It wasn't immediately obvious to me why we load the folder before adding a new folder.  Can we just not do that? Or do we need some code to ensure we don't load the out of date data of the first request.

**Comment by sebastienros** [comment]
Do you think you can provide a PR to fix the issue?

**Comment by dannoh** [comment]
Created the PR
#10701
