### ISSUE TITLE
Compile Net5.0 using Visual Studio

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#10696]
Dears,

My project still use net5.0 ,  Before the.net6.0 upgrade, I could also debug in OC directly from the OC source code using attatch to the process, 

https://github.com/OrchardCMS/OrchardCore/discussions/10603#discussioncomment-1573640

such as the `executeQuery ` bug  I encountered recently. This operation is now unavailable after the OC upgrade to 6.0
I tried the following:

1. Using the compile command and copying the results into my project, the code doesn't seem to have changed anything and breakpoints can't be attached
`dotnet build.src/orchardcore.cms.Web / -- Configuration Debug -- Framework net5.0 -- Debug`

2. Modify the props file in the OC project directly:
 ```< DefaultTargetFramework > net5.0 < / DefaultTargetFramework >```
VS2022  and VS2019 will  compile faild....

_Originally posted by @hyzx86 in https://github.com/OrchardCMS/OrchardCore/pull/10380#issuecomment-967006335_

**Comment by sebastienros** [comment]
To complete the issue, what I am seeing is this message in VS, for all the projects.

```
Error	NETSDK1005	Assets file 'C:\code\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement.Abstractions\obj\project.assets.json' doesn't have a target for 'net5.0'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project.	OrchardCore.DisplayManagement.Abstractions	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	
```

I can confirm that when VS builds, the assets.json file only has the net6.0 target. While building from command line works

@hyzx86 Can you try to create a `global.json` file with this content at the root

```
{
  "sdk": {
    "version": "5.0.403" // Change this to a 5.0 SDK that you have installed.
  }
}
```

Then update the `<CommonTargetFrameworks>` with only `net5.0` ?

I will continue to investigate.

**Comment by hyzx86** [comment]
@sebastienros  still not work..
