### ISSUE TITLE
resources tag helper behaves differently in dotnet run and published binary in .NET 6 and 1.2.0-preview-16579

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#10691]
### Describe the bug
I am using OrcardCore module in non CMS system. I upgraded the project to .NET 6 yesterday hence I had to target `1.2.0-preview-16579`. I encountered this problem after the upgrade.

``` <resources type="Stylesheet" />``` does not render when it is published and run.

So this is the source

![source](https://user-images.githubusercontent.com/1761249/141277850-80572457-7546-4259-9d6d-64d484831fda.png)

It renders OK when I run it from Visual Studio 2022 or command line `dotnet run`
![dotnet-run](https://user-images.githubusercontent.com/1761249/141277895-37851726-8f7b-41d4-a572-4a1e48a0dbf9.png)

However when I publish using `dotnet publish Crucible.Web.csproj -c Release -o  {path}` and run the resulting .exe binary, the resource tag helper does not render.

![published](https://user-images.githubusercontent.com/1761249/141278516-bcfa1f22-0246-475e-8e3a-664e361e7d38.png)

**Comment by deanmarcussen** [comment]
Do you have a direct `PackageReference` to the `OrchardCore.ResourceManagement` nuget package for the theme or module you are using the tag helper in?

TagHelpers are discovered by .NET via assembly reflection in production so require a direct reference.

Meanwhile this might also be .NET 6 related, but we'll check the easy things first :)

**Comment by dodyg** [comment]
I have 

``` <PackageReference Include="OrchardCore.ResourceManagement" Version="1.2.0-preview-16579" />```

both in the module and the host project.

**Comment by dodyg** [comment]
The DLL is also of the correct version at the published folder
![sure](https://user-images.githubusercontent.com/1761249/141284500-1d24abbb-92e3-4102-ac19-498ef7034d31.png)

**Comment by deanmarcussen** [comment]
Well, we checked the easy stuff, we'll have to see if we can repro it with .NET 6 locally. (and see if it's just related to the Resource management TagHelper, or has some impact on other Tag Helpers)

I imagine you aren't using the Admin, so we can't simply check there if the standard Content tag helpers are rendering correctly in the admin list?

**Comment by dodyg** [comment]
I created a sample although in this case `<resources type="Stylesheet" />` doesn't work at all scenarios.

https://github.com/dodyg/orchardcore-net6-resource

**Comment by deanmarcussen** [comment]
@dodyg I remove this from your sample project and it started working fine. (wasn't working at all before that)

```
 <ItemGroup>
    <Content Remove="Views\_ViewImports.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Views\_ViewImports.cshtml">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </EmbeddedResource>
  </ItemGroup>
```

**Comment by dodyg** [comment]
Indeed. I updated the sample from

(relying on _ViewImports.cshtml)
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>Resources</title>
    <resources type="Stylesheet"  />
</head>
<body>


    @RenderBody()

    <resources type="FootScript" />
</body>
</html>
```

to

```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>Resources</title>
    <resources type="Stylesheet"  />
</head>
<body>


    @RenderBody()

    <resources type="FootScript" />
</body>
</html>
```

Let me try to port the sample to .NET 5 and see what happens.

**Comment by deanmarcussen** [comment]
@dodyg I am not sure if you resolved it or not?

I made only changes to the csproj to get it working. (No changes to ViewImports)

If you still don’t have it working let me know and I’ll pr your sample repo

**Comment by dodyg** [comment]
Ah OK. I fixed it by putting 

```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
```
directly on the `_Layout.cshtml`.

**Comment by dodyg** [comment]
I wonder why `<Content Remove="Views\_ViewImports.cshtml" />` would fix the problem as well.

**Comment by Skrypt** [comment]
Ok, so the issue is that you removed the `_ViewImports.cshtml` file which does Global `imports` and `using` in your views. By adding these directly in your view it works so the issue is that you had no `_ViewImports.cshtml` file. Just like @deanmarcussen said, in development, these assemblies are resolved through reflection by not when it's published.

I don't think there is any action on our side to do then. Close if you agree.
