### ISSUE TITLE
OrchardCore breaks after upgrade to .NET 6 and v1.1.0

### ISSUE THREAD

**Issue by oemdata** [OrchardCMS/OrchardCore#10698]
I have an orchardcore web application that I use as a headless CMS. It was working great in VS 2019, .NET 5, and v1.0. After I open the project in VS2022, upgrade to .NET 6, and upgrade OC to v1.1.0, I am getting the following error when I launch the app in Visual Studio: InvalidOperationException: A descriptor for '/Areas/orchard.cms.web/Pages/Error.cshtml' was not found.

**Comment by dodyg** [comment]
Try the latest https://cloudsmith.io/~orchardcore/repos/preview/packages/detail/nuget/OrchardCore.Application.Cms.Targets/latest/

**Comment by Skrypt** [comment]
You need to upgrade to latest OC version like @dodyg says.

1.2.0-preview-16586 is current.

**Comment by oemdata** [comment]
Thanks for the reply. I updated OC to the latest preview version, and now I am getting a different error.

ArgumentException: Value cannot be null or empty. (Parameter 'areaName')

Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapAreaControllerRoute(IEndpointRouteBuilder endpoints, string name, string areaName, string pattern, object defaults, object constraints, object dataTokens)

OrchardCore.Mvc.Routing.DefaultAreaControllerRouteMapper.TryMapAreaControllerRoute(IEndpointRouteBuilder routes, ControllerActionDescriptor descriptor)

OrchardCore.Mvc.Startup.Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)

OrchardCore.Modules.ModularTenantRouterMiddleware+<>c__DisplayClass7_0.<ConfigureTenantPipeline>b__1(IEndpointRouteBuilder routes)

Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)

OrchardCore.Modules.ModularTenantRouterMiddleware.ConfigureTenantPipeline(IApplicationBuilder appBuilder)

OrchardCore.Modules.ModularTenantRouterMiddleware.<BuildTenantPipeline>b__6_0(IApplicationBuilder builder)

OrchardCore.Diagnostics.DiagnosticsStartupFilter+<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)

OrchardCore.ContentPreview.PreviewStartupFilter+<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)

Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)

OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline()

OrchardCore.Modules.ModularTenantRouterMiddleware.InitializePipelineAsync(ShellContext shellContext)

OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)

OrchardCore.Modules.ModularTenantContainerMiddleware+<>c__DisplayClass4_0+<<Invoke>b__0>d.MoveNext()

OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)

OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)

OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)

OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)

OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Skrypt** [comment]
This is a custom route with an AreaName set as null which throws an exception.

**Comment by oemdata** [comment]
But I don't understand where this custom route is coming from. The web app is basically an empty MVC app created by Visual Studio and then I added OC to it. Here is my Startup.cs ...

using dataforth.application.CMS;
using infrastructure.cms.orchard.GetContent;
using infrastructure.cms.orchard.Models;
using infrastructure.sqlserver.CQRS.Raw.Queries;
using infrastructure.sqlserver.EFCore;
using infrastructure.sqlserver.Legacy;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using OrchardCore.ContentManagement;
using Serilog;
using Serilog.Events;
using Serilog.Sinks.SystemConsole.Themes;

namespace orchard.cms.web
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .MinimumLevel.Override("System", LogEventLevel.Warning)
                .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft.EntityFrameworkCore.Database.Command", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .WriteTo.RollingFile(configuration.GetValue<string>("LogFilePath"))
                .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}", theme: AnsiConsoleTheme.Literate)
                .CreateLogger();
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
            services.AddMvc();
            
            // configure DbContext
            var builder = new SqlConnectionStringBuilder(Configuration.GetConnectionString("DefaultConnection"));
            services.AddDbContext<DataforthDbContext>(options =>
                options.UseSqlServer(builder.ConnectionString));
            var builder2 = new SqlConnectionStringBuilder(Configuration.GetConnectionString("LegacyConnection"));
            services.AddDbContext<LegacyDbContext>(options =>
                options.UseSqlServer(builder2.ConnectionString));

            services.AddContentPart<OrderableProduct>();
            services.AddContentPart<GenericProduct>();
            services.AddContentPart<PDFCollateral>();
            services.AddContentPart<LegacyDocumentMeta>();
            services.AddContentPart<ProductSeries>();
            services.AddContentPart<PressRelease>();
            services.AddContentPart<TechNote>();
            services.AddContentPart<ApplicationNote>();

            services.AddTransient<IRawQueries, RawQueries>();
            services.AddTransient<ICMSProvider, OrchardDataforthCMSProvider>();
            services.AddTransient<ILocalizationSetManager, LocalizationSetManager>();
            
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();         
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();
            //app.UseAuthorization();

            app.UseOrchardCore();
        }
    }
}

**Comment by oemdata** [comment]
I inadvertently close id, reopening this issue now.

**Comment by dodyg** [comment]
@oemdata can you please put the whole project on a repo somewhere so we can try to replicate it.

**Comment by oemdata** [comment]
I've stripped out the OC web from my overall solution and posted it to a repo. It's behaving the same way ... it works in .net 5 but not in .net 6: https://github.com/oemdata/orchard.cms.web.

**Comment by oemdata** [comment]
Any update on this?

**Comment by deanmarcussen** [comment]
why are you calling `UseRouting()` ? looks like an issue to me.
This is called by Orchard

https://github.com/oemdata/orchard.cms.web/blob/9e689ba14880df8d98b921740e54c9b24c5e7d63/orchard.cms.web/Startup.cs#L72

My recommendation to you would be to use the templates to create an app, rather than putting it together yourself.

https://docs.orchardcore.net/en/latest/docs/getting-started/templates/

I also don't see a nuget.config pointing towards cloudsmith, so you might want to check you actually have one, and are getting the correct updated version of Orchard Core

https://docs.orchardcore.net/en/latest/docs/getting-started/preview-package-source/
