### ISSUE TITLE
JavaScript in Footer Widgets ripped when saving

### ISSUE THREAD

**Issue by zijianhuang** [OrchardCMS/OrchardCore#10702]
### Describe the bug

When creating a new Website with CMS, receipt "Website Ready to Use", the init process creates contents and widgets including a footer with the following:

```html
Copyright © Your Website <script>document.write(new Date().getFullYear())</script>
```

When saving, the script is removed.

### To Reproduce
1. Go to Admin area, Design/Widgets
2. Edit Footer
3. You see the copyright notice scripts had been created by the init process.
4. Save and load again, the script section is removed.

### Expected behavior
Javascript remains.

**Comment by zijianhuang** [comment]
Thanks. Understood.
However, the widget including the JavaScript is generated by OrchardCore's init process for receipt "Website Ready to Use". Then when the admin want to change "Your website" to an organisation name and save, the Sanitizer removes the script. At the moment I have to hack the database to put the JS scripts back.

It will be good you provide a switch to allow JavaScript as an opt-in option.

**Comment by Piedone** [comment]
There is a switch (well, multiple ones). Please check out the docs I linked.

**Comment by zijianhuang** [comment]
thanks. I see https://docs.orchardcore.net/en/ag-docs/docs/reference/modules/Liquid/ is an optional opt-in module. If I really need to add more JavaScript stuffs for whatever visual effects, I shall be installing Liquid first.

**Comment by zijianhuang** [comment]
found it at Configuration/Features.
