### ISSUE TITLE
Timer Event not work in China（TimeZone +8）

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#10713]
The workflow always hangs and cannot continue, after checking the source code, I found that one is local time and one is UTC time, if in western countries there may not be this problem, but in TimeZone +8 it will not continue (it may hang for 8 hours)
I modified part of the code and it can execute now, but I think this may not be the best solution

![image](https://user-images.githubusercontent.com/15613121/142168990-d24c08fa-58f9-48bb-844d-83e8f49dd5df.png)

**Comment by hyzx86** [comment]
So do I need to specify a utc time corn expression?

**Comment by hyzx86** [comment]
Hi @deanmarcussen  , Can you help me with this problem?

**Comment by jtkech** [comment]
> So do I need to specify a utc time corn expression?

Yes, I think so.

https://github.com/atifaziz/NCrontab/issues/47#issuecomment-464516304

https://github.com/atifaziz/NCrontab/issues/41#issue-317890509

**Comment by Skrypt** [comment]
First time I see this `≥` combined char instead of `>=` in C#.

**Comment by hyzx86** [comment]
> First time I see this `≥` combined char instead of `>=` in C#.

 That is a font style 'Fira Code'  😁
https://github.com/tonsky/FiraCode

**Comment by hishamco** [comment]
> First time I see this ≥ combined char instead of >= in C#.

Yes, this is new font coming up in VS
