### ISSUE TITLE
Now the source code Publish web unsuccessful, very sad

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1072]
https://github.com/OrchardCMS/OrchardCore/tree/1d084df18800bd98a85ac6358f1c40d2dd0b7972

Now the source code Publish web unsuccessful, very sad

![default](https://user-images.githubusercontent.com/28694676/31307602-540bf328-ab9a-11e7-8e4e-ca34324b8cf4.PNG)
![1](https://user-images.githubusercontent.com/28694676/31307603-5411c136-ab9a-11e7-8182-18a313110b66.PNG)
![3](https://user-images.githubusercontent.com/28694676/31307604-54148b32-ab9a-11e7-9f6d-d76a5356e297.PNG)

**Comment by agriffard** [comment]
What is this link ?
 https://github.com/OrchardCMS/OrchardCore/tree/1d084df18800bd98a85ac6358f1c40d2dd0b7972 

Why do you use this repository https://bitbucket.org/Lombiq/orchard-2-hg instead of the github one ?

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/tree/1d084df18800bd98a85ac6358f1c40d2dd0b7972

Is

https://github.com/OrchardCMS/OrchardCore/commits/master
![s71008-020715 1](https://user-images.githubusercontent.com/28694676/31310621-eebfcb1e-abcd-11e7-8884-19f4b0139730.jpg)

**Comment by pgy866** [comment]
https://bitbucket.org/Lombiq/orchard-2-hg
Is not it synchronized?
I prefer bitbucket interface

**Comment by agriffard** [comment]
There was indeed an error int the views AddFieldTo.cshtml and EditField.cshtml due to wrong namespace using for extension method DisplayName() on a ContentPartDefinition.
=>
@using OrchardCore.ContentManagement.Metadata.Settings

**Comment by pgy866** [comment]
thank you very much! 
Successful release of the network, very happy!

 There is a duplicate.
![146e5576f8f6624b](https://user-images.githubusercontent.com/28694676/31319041-cc5f5f64-ac8e-11e7-93c4-c3ce0a8fa829.png)
