### ISSUE TITLE
Liquid : Request.Query.value not working

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10737]
### Describe the bug

{{ Request.Query.something }} should return the QueryString element value and it doesn't as of now from the latest main branch.

### Screenshot

https://user-images.githubusercontent.com/3228637/142957299-c48141ca-078f-4f22-93a4-6e4365e6e435.mp4

**Comment by jtkech** [comment]
It's an IQueryCollection whose underlying type is (now?) a QueryCollectionInternal but we only allow access to QueryCollection, I made it working by replacing in the startup of OC.DisMng.Liquid

This

    nameof(HttpRequest.Query) => new ObjectValue(request.Query),

By

    nameof(HttpRequest.Query) =>
        new ObjectValue(new QueryCollection(request.Query.ToDictionary(kv => kv.Key, kv => kv.Value))),

Will do a PR soon.
