### ISSUE TITLE
Management interface at the same time multiple operating window?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1073]
Can that be it?
Backstage,
Multiple operation windows

![default](https://user-images.githubusercontent.com/28694676/31307687-cee8039c-ab9b-11e7-8495-7ac87aa98a16.PNG)

![image](https://user-images.githubusercontent.com/28694676/31307647-359f1aae-ab9b-11e7-81a5-871d32dc12b5.png)

**Comment by agriffard** [comment]
If the question is "Could we have an admin dashboard that allows to open pages in different tabs", I don't think so.

**Comment by pgy866** [comment]
Sorry!
Google translation, may mean change! I mean, is there a plan to add such a function?
  can operate on multiple interfaces in the administrator interface

**Comment by agriffard** [comment]
No, we don't have any plan to add such feature.

**Comment by pgy866** [comment]
Is this a bad way?
Or too simple?
 Not included in the core function?
 Still quite like this operation management background!
