### ISSUE TITLE
Tenant "setup" and "view" buttons not working properly.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10742]
When trying to setup a new tenant by clicking on the setup button it returns a server not found error in the browser.
This is because we don't append the current server port to the tenant setup page url.

https://user-images.githubusercontent.com/3228637/142970670-201075cf-0b00-4e91-97a2-fa98f5df3288.mp4

**Comment by Skrypt** [comment]
See discussion here : https://github.com/OrchardCMS/OrchardCore/discussions/10749#discussioncomment-1693928

**Comment by sebastienros** [comment]
The tenant should not be configured with a scheme or port. It needs to reuse whatever is currently used in the request.
