### ISSUE TITLE
Creating a tenant without a prefix or domain returns an NRE

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10744]
### Describe the bug
Creating a tenant without a prefix or domain returns an NRE

### To Reproduce
Create a second tenant and omit to put a Url prefix or hostname.

### Expected behavior
It should throw a form validation error.

### Screenshots

![image](https://user-images.githubusercontent.com/3228637/142979891-6fd54436-6bac-4571-b9dc-3f21c7aa613d.png)

**Comment by hishamco** [comment]
@Skrypt I think the issue was resolved, I didn't see any exception, so I will close this for now, feel free to open if it occurs again
