### ISSUE TITLE
LocalizedContentItemIndex Latest column, added but not migrated?

### ISSUE THREAD

**Issue by dannoh** [OrchardCMS/OrchardCore#10756]
Recently upgraded our version of OrchardCore, and we ran into something that I believe is an issue, but wanted to double check.

The ContentLocalization Migrations.cs added a new migration to add `Latest` to the `LocalizedContentItemIndex` table.
In addition the `DefaultContentLocalizationManager` updated some queries (`GetItemsForSetAsync`) that use this new value.

Problem we see with older data is that this column is NULL for versions that are Latest, so they don't get returned by the query anymore.

Seems like we will need to backfill this column properly, sound correct?

**Comment by Skrypt** [comment]
Yes, correct sound. :smile:

**Comment by sebastienros** [comment]
> Seems like we will need to backfill this column properly, sounds correct?

Yes. This should also be written in the docs then. Can you update them in a PR?
