### ISSUE TITLE
Upgrade Orchard Core Package from 1.0.0-rc2-13450 to 1.0.0 issue(The OpenID Connect module is not correctly configured.)

### ISSUE THREAD

**Issue by sucalavlad** [OrchardCMS/OrchardCore#10752]
Hello. I am currently upgrading the orchard core package on an existing website from 1.0.0-rc2-13450 to 1.0.0. 
I did not find any official troubleshooting documentation for this, but looking through the issues I found a script that helped me progress with the migrations issue I was having.
`Error: Invalid column name 'IsLockoutEnabled'.`
Link to fix: https://github.com/OrchardCMS/OrchardCore/issues/7206#issuecomment-907987125
After running that script with dropping and mocking the indexes on some of the openid tables, from what I see the migrations are applied successfully.
Below is the result for

`SELECT * FROM site_Document WHERE [Type] = 'OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data'`

```
{
   "Id":1,
   "DataMigrations":[
      {
         "DataMigrationClass":"OrchardCore.Liquid.Migrations",
         "Version":1
      },
      {
         "DataMigrationClass":"OrchardCore.ContentManagement.Records.Migrations",
         "Version":6
      },
      {
         "DataMigrationClass":"OrchardCore.Contents.Migrations",
         "Version":1
      },
      {
         "DataMigrationClass":"OrchardCore.Alias.Migrations",
         "Version":4
      },
      {
         "DataMigrationClass":"OrchardCore.ContentFields.Migrations",
         "Version":2
      },
      {
         "DataMigrationClass":"OrchardCore.Deployment.Migrations",
         "Version":1
      },
      {
         "DataMigrationClass":"OrchardCore.Widgets.Migrations",
         "Version":1
      },
      {
         "DataMigrationClass":"OrchardCore.Flows.Migrations",
         "Version":3
      },
      {
         "DataMigrationClass":"OrchardCore.Html.Migrations",
         "Version":5
      },
      {
         "DataMigrationClass":"OrchardCore.Indexing.Migrations",
         "Version":1
      },
      {
         "DataMigrationClass":"OrchardCore.Layers.Migrations",
         "Version":3
      },
      {
         "DataMigrationClass":"OrchardCore.Lists.Migrations",
         "Version":3
      },
      {
         "DataMigrationClass":"OrchardCore.Markdown.Migrations",
         "Version":4
      },
      {
         "DataMigrationClass":"OrchardCore.Title.Migrations",
         "Version":2
      },
      {
         "DataMigrationClass":"OrchardCore.Menu.Migrations",
         "Version":4
      },
      {
         "DataMigrationClass":"OrchardCore.OpenId.YesSql.Migrations.OpenIdMigrations",
         "Version":8
      },
      {
         "DataMigrationClass":"OrchardCore.PublishLater.Migrations",
         "Version":2
      },
      {
         "DataMigrationClass":"OrchardCore.Users.Migrations",
         "Version":12
      },
      {
         "DataMigrationClass":"TrackerContentTypes.ModelMigrations",
         "Version":1
      },
      {
         "DataMigrationClass":"TrackerContentTypes.IndexMigrations",
         "Version":1
      },
      {
         "DataMigrationClass":"TrackerContentTypes.ContentMigrations",
         "Version":1
      }
   ]
}
```
but when trying to access the tenants I ran those scripts on I receive the following two errors in the logs and I am not exactly sure how to fix this issue.
```
OrchardCore.OpenId.Configuration.OpenIdServerConfiguration|WRN|The OpenID Connect module is not correctly configured.
OrchardCore.OpenId.Configuration.OpenIdValidationConfiguration|WRN|The OpenID Connect module is not correctly configured.
```
Do you have any suggestions please?

**Comment by hishamco** [comment]
IsLockoutEnabled is related to Identity, @kevinchalet any idea?

**Comment by sucalavlad** [comment]
As previously stated the IsLockout issue was resolved by running the scripts provided in the link below
https://github.com/OrchardCMS/OrchardCore/issues/7206#issuecomment-907987125
I am not sure that was the correct way of doing it though or if I am missing any other changes.
Basically I would need help understanding what would cause these OpenId Connect module issues.
`OrchardCore.OpenId.Configuration.OpenIdServerConfiguration|WRN|The OpenID Connect module is not correctly configured.
OrchardCore.OpenId.Configuration.OpenIdValidationConfiguration|WRN|The OpenID Connect module is not correctly configured.
`

**Comment by sebastienros** [comment]
Can you try to re-save the configuration in the admin? It will probably restore the missing values required in the new version.

**Comment by sucalavlad** [comment]
Hello. I did not give enough context, but your solution did work in the end. 
I had multiple tenants and my mistake was that I only re-saved the configuration on the default tenant and for the other ones the migrations did not apply correctly on the open id settings.
I went to each tenant individually and perform a save on the Authorization Server Page(Security→ OpenID Connect → Settings) and that fixed the issue.
Thank you very much for the help.
Only one mention, It would help a lot if you made the contents of this page (https://github.com/OrchardCMS/OrchardCore/issues/7206) available in the official release documentation.

**Comment by sucalavlad** [comment]
I have reopened the issue in the hopes of getting a response. 
Thank you

**Comment by sebastienros** [comment]
> after doing some changes to a content type and creating new migrations I noticed that when they are applied to a tenant it's openid server settings are badly upgraded and I need to go through the whole resaving configuration process again

I don't understand the "and creating new migrations" part. What do you mean by "creating new migrations"?

**Comment by sucalavlad** [comment]
Sorry, what I meant to say that this issue appeared when adding a new step to a DataMigration class. In this case it was to add a new field to a content part. 
![image](https://user-images.githubusercontent.com/30407875/154049228-fffb6d2b-4851-4892-8cb9-f447b99cab1b.png)
The change has nothing to do with the tenant recipe but it triggered the update I mentioned in the previous post.
