### ISSUE TITLE
ContentTypes (with AliasPart) defined in recipe aren't added to AliasPartIndex SQL Table when instantiated in CMS

### ISSUE THREAD

**Issue by Muggei** [OrchardCMS/OrchardCore#10757]
### ContentTypes (with AliasPart) defined in recipe aren't added to AliasPartIndex SQL Table when instantiated in CMS
Hi, 
I'm currently facing the following issue: 
ContentTypes with AliasPart which are defined in my recipe don't get added to the AliasPartIndex database table. This prevents me from retrieving my content items by (where: {alias: {alias: "xyz"}}) in graphQL. I use AutoSetup on Startup.

E.g. my ContentTypeDefinition looks like this:
```
//----------------------------------
//MyContentItem
        {
          "Name": "MyContentItem",
          "DisplayName": "MyContentItem",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true,
              "Draftable": true,
              "Versionable": true,
              "Securable": true
            },
            "FullTextAspectSettings": {}
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "AliasPart",
              "Name": "Alias",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "2"
                },
                "GraphQLContentTypePartSettings": {},
                "AliasPartSettings": {},
                "ContentIndexSettings": {
                  "Included": true,
                  "Stored": true,
                  "Analyzed": true
                }
              }
            },
            {
              "PartName": "TitlePart",
              "Name": "DisplayName",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "1"
                }
              }
            },
            {
              "PartName": "ContactPersonPart",
              "Name": "ContactPerson",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            }
          ]
        }
//----------------------------------

```
Sidenote: The ContactPersonPart is simply a ContentTypePart with two TextFields.

### To Reproduce
1. Add a ContentTypeDefinition to the recipe with an AliasPart
2. Let the Default Tenant be initialized via AutoSetup using the recipe
3. Create a content item with the type of the ContentType "MyContentItem"
4. Run GraphQL Query with "where alias"
5. Check AliasPartIndex Db Table

The GraphQL result is: "GraphQL.ExecutionError: Error trying to resolve myContentItem" and AliasPartIndex Db Table is empty.

I checked if its the same behaviour when creating a ContentTypeDefinition with an AliasPart directly inside the running CMS, but then it worked.

### Expected behavior
ContentType Instances from ContentTypes with AliasPart defined in the recipe are retrievable via GraphQL.

**Comment by deanmarcussen** [comment]
> I checked if its the same behaviour when creating a ContentTypeDefinition with an AliasPart directly inside the running CMS, but then it worked.

I would suggest the issue is likely to be with your recipe, setting up a content definition with alias with autosetup works fine for me.

You may not have turned the Alias module on in the recipe, or your type definition has an issue (it looks ok).

Suggestions
- Check you have the Alias feature on.
- Export your content definition file with the import/export deployment feature and see what is different.
- Does it work if you resave the type definition from the admin after setup is complete?

**Comment by Muggei** [comment]
Thanks for the reply:
1. Alias feature is on
2. Exported the definition of a type i create inside the running cms, and adjusted my recipe accordingly. still same result
3. Resaving the type definition did not work

One thing was different between the export and my initial recipe, but did not change the endresult:
Before:
```
//----------------------------------
//MyContentItem
        {
          "Name": "MyContentItem",
          "DisplayName": "MyContentItem",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true,
              "Draftable": true,
              "Versionable": true,
              "Securable": true
            },
            "FullTextAspectSettings": {}
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "AliasPart",
              "Name": "Alias",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "2"
                }
              }
            },
            {
              "PartName": "TitlePart",
              "Name": "DisplayName",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "1"
                }
              }
            },
            {
              "PartName": "ContactPersonPart",
              "Name": "ContactPerson",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            }
          ]
        }
//----------------------------------
```

After (Added the "MyContentItem" to the ContentTypePartDefinitionRecords). This is also done in the exported recipe.
```
//----------------------------------
//MyContentItem
        {
          "Name": "MyContentItem",
          "DisplayName": "MyContentItem",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true,
              "Draftable": true,
              "Versionable": true,
              "Securable": true
            },
            "FullTextAspectSettings": {}
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "MyContentItem",
              "Name": "MyContentItem",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            },
            {
              "PartName": "AliasPart",
              "Name": "Alias",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "1"
                }
              }
            },
            {
              "PartName": "TitlePart",
              "Name": "DisplayName",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "2"
                }
              }
            },
            {
              "PartName": "ContactPersonPart",
              "Name": "ContactPerson",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "3"
                }
              }
            }
          ]
        }
//----------------------------------
```

**Comment by Muggei** [comment]
Ok, I think i found the issue. It seems it only works out of the box when the "Name" Property of the AliasPart is also "AliasPart". 
Is it possible to have an AliasPart with a custom name?

**Comment by deanmarcussen** [comment]
> Ok, I think i found the issue. It seems it only works out of the box when the "Name" Property of the AliasPart is also "AliasPart". Is it possible to have an AliasPart with a custom name?

No I don't think so. Custom names are for Attachable parts (parts that can be attached more than once).
An AliasPart is not an Attachable part
