### ISSUE TITLE
Taxonomy terms drag and drop doesnt work

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#10755]
When trying a new instance using the blog recipe : 
  --From the admin go to **Categories** taxonomy and add a new term. 
  -- Try to drag and  drop terms in the UI . It doesnt work. 
  -- Javascript error  occurs  : Uncaught TypeError: Cannot read properties of undefined (reading 'vertical')

**Comment by Skrypt** [comment]
JQuery UI version update that created this regression. Known issue, thanks for reporting.

**Comment by hishamco** [comment]
I think there's another opened issue reporting the same thing

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/10642

**Comment by scleaver** [comment]
This seems to be fixed in the latest version.
