### ISSUE TITLE
.NET 6.0 Refactoring

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#10761]
We should have a discussion about the new syntax improvements available in .NET 6.0 during next meeting:

File-scoped namespaces

Global usings

Options in .csproj:
```
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
```

Merge Program.cs and Startup.cs into minimal Program.cs as in the new project templates (in OrchardCore.Cms.Web and code templates)

**Comment by agriffard** [comment]
My opinion is:

The less lines there is in a file, the clearer the code is.

I like 'File-scoped namespaces' syntax. It could be applied on all existing files by using the 'Clean up' feature in Resharper.

Global usings has to be made per project so it would be a choice per project, not always needed, to add a Usings.cs file with global usings where useful.

Use `ImplicitUsings` to not require a using for common, widely used namespaces, but we need to add them to all .csproj.

Merge Program.cs and Startup.cs into one Program.cs (I will submit a PR).

**Comment by hishamco** [comment]
As @Skypt mentioned in another PR, mutil-targeting is an issue

**Comment by agriffard** [comment]
I guess that we will have at least one release keeping multi-targetting with netcore3.1, net5 and net6, and then we would be able to choose if we want to only support net6 and embrace the new syntax for the next versions.

**Comment by hishamco** [comment]
I think we need to move to .NET 6.0 while it's LTS

**Comment by sebastienros** [comment]
So only file based namespaces will work across the board.
Try also to have the Cms.web target net6.0 only and use the single Program.cs.
