### ISSUE TITLE
CultureDictionary & CultureDictionaryRecord improvements

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#1076]
After I'm looking to the source of both `CultureDictionary` and `CultureDictionaryRecord`, I come up with the following:

- The name `CultureDictionary` doesn't make sense because the dictionary doesn't manage and maintain the cultures, name like `ResourceDictionary` it would be better, because we manage and maintain localization resources. Similarly `ResourceDictionaryEntry` is a good for a particular resource entry 

- I'm not sure why is the `Culture` is needed in the dictionary, the  `LanguageCode` is better, but I don't have any doubt to leave it as its

- The `Transaltion` it something related to the  `CultureDictionaryRecord` rather than `CultureDictionary`

- The `GetKey` in `CultureDictionaryRecord` seems more specific to PO, it would be nice if we move the current implementation as extension method, to make the underlying API generic for any other localization resource provider that support pluralization

- Removing calculating the plural form from the indexer to the pluralization abstraction APIs will have a great value, so the developer has a full control for any further customization by overriding the default implementation

/cc @sebastienros

**Comment by Skrypt** [comment]
> I'm not sure why is the Culture is needed in the dictionary, the LanguageCode is better, but I don't have any doubt to leave it as its

We are using Culture as an identifier because of x-plat compatibility. The LCID can differ from one OS to an other.
