### ISSUE TITLE
GraphQL - Content item permissions validation

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#10760]
I am creating secured section in OC using AuthorizationHandlers for content items. Everything works fine in CMS, but GraphQL API is missing permission validation. 

I have investigated possible options, here are my notes:
* OC has permission validation for content type access (only checking content type name)
* OC does not validate "contentItem" query at all, so restricted content types can be accessed with this query
* I think we need validation per content item before returning result to GraphQL
* Possible solution could be to add event handlers into resolve functions in graphql
* Another solution could be to update GraphQL to current version, so anyone could just define BaseSchemaNodeVisitor and customize resolver behavior
* There is currently no way to customize result of graphql
* I have ended up with adding custom bool field with result of authorization - but that is possible solution only when you do not have can control access to graphql

**Comment by carlwoodhouse** [comment]
Certainly we need to resolve some of these permissions things 

> There is currently no way to customize result of graphql

I mean this isnt strictly true .. 

checkout ` GraphQLFilter<ContentItem>` - these allow you to do prequery and postquuery filtering of results

**Comment by MikeKry** [comment]
@carlwoodhouse 

Nice, I missed that and it will help my case. Maybe we could consider some better placement in documentation or something. 

Anyway I still think item permissions should be validated by default.

**Comment by carlwoodhouse** [comment]
I agree they should :)

**Comment by MikeAlhayek** [comment]
@MikeKry I just came across this issue. I had a PR last year that I think solved this issue. Are you still having the same issue? PR #12734 checks the permission before querying the contents. 

https://github.com/OrchardCMS/OrchardCore/blob/fa063b8975e611f63c347fc14f5e2cd23e8e2e6c/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentItemFilters.cs#L30-L61

If that indeed solves this issue, please close this issue.

**Comment by MikeKry** [comment]
@MikeAlhayek 

I do not know, if that solved this issue. When I look at code, it looks as it should, but when I tried it doesnt seem to work.

I have created new role which has access to only one content type and user that has this role can access all pages of this type.
![image](https://github.com/OrchardCMS/OrchardCore/assets/52829889/e0338ac7-3c7b-4eb2-a691-51c9b1f53a9c)

but when I try to fetch any other type, that is not allowed in role definition, I still get all results
![image](https://github.com/OrchardCMS/OrchardCore/assets/52829889/646d61b0-0cb3-4d12-8388-e5c267293918)


I think it might be because there is still permission "View XY by others" effective, even though I did not allow it..? 

![image](https://github.com/OrchardCMS/OrchardCore/assets/52829889/53fdb500-4ce2-4a05-88b3-3d801bd60916)

Can it be disabled? Even anonymous user without any permission has this effective..

**Comment by MikeAlhayek** [comment]
I am guessing the Anonymous and/or Authenticated roles give View by others permissions on Contents. You may want to uncheck that so that your permissions are honored.

**Comment by MikeKry** [comment]
@MikeAlhayek 

I did not find any possibility to uncheck these permissions.. Do you have idea where to find it?

**Comment by MikeAlhayek** [comment]
Edit both the Anonymous an Authenticated roles and uncheck the "View Content By others" permission.

**Comment by MikeKry** [comment]
@MikeAlhayek 

Ah, ok, seems it works ok then (y) Thanks
