### ISSUE TITLE
ShellSettings reporting wrong name

### ISSUE THREAD

**Issue by markgould** [OrchardCMS/OrchardCore#10778]
We're using this module for Application Insights - https://github.com/Lombiq/Orchard-Azure-Application-Insights and I'm noticing in the telemetry, the shell name is typically reporting another tenant.

I'm not seeing anything wrong in that project, so I'm reporting it here. The [Startup.cs](https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/dev/Startup.cs) registers items using the IServiceCollection passed to ConfigureServices - so it should be a singleton just for the tenant.

The Telemetry Initializer just gets an injected ShellSettings class - https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/dev/TelemetryInitializers/ShellNamePopulatingTelemetryInitializer.cs

Is there something obvious here I'm missing?

**Comment by hishamco** [comment]
@Piedone could this be logged here or in Lombiq repo?

**Comment by Piedone** [comment]
This is a bug in the AI module so I'm moving the issue to there.. Thanks @markgould for reporting and @hishamco for letting me know.

**Comment by Piedone** [comment]
Can't move issues between orgs :(. So recreated it here: https://github.com/Lombiq/Orchard-Azure-Application-Insights/issues/19

**Comment by markgould** [comment]
Thank you both @hishamco and @Piedone for responding so quickly! I'll close the issue out over here.

**Comment by Piedone** [comment]
While this was due to a bug in the Application Insights module, I found a bug in Orchard too: https://github.com/OrchardCMS/OrchardCore/pull/10779
