### ISSUE TITLE
Make sure Logger / Notifier usage is consistent

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10797]
It should use string interpolation.

Examples of what I found : 

```C#
    _notifier.SuccessAsync(H["'{0}' has been restored.", contentItem.DisplayText]);
```

A lot of these are on the Notifiers when there is only one string passed.

The Logger instances usage seems to be consistent.

So, I'm thinking that those have not been changed because they are Localizations and it would require to also change all these strings in Crowdin.

/cc @agriffard

**Comment by Piedone** [comment]
Do you mean that it should _not_ use string interpolation? Both log messages and localized strings should use string format parameters instead of putting the data directly into the string.

**Comment by Skrypt** [comment]
The difference is that Logger instances are not using translated strings. We never translate logs.
So, we use string interpolation for those strings. But localized strings should never use string interpolation. I think you are right.

**Comment by Piedone** [comment]
Logging should use parameters as well for semantic logging. See e.g.: https://blog.stephencleary.com/2020/06/a-new-pattern-for-exception-logging.html#:~:text=Semantic%20Logging%20/%20Structured%20Logging It can be quite useful when processing logs.

**Comment by Skrypt** [comment]
Ok, so it's not string interpolation but semantic logging and it's what we do. Makes sense then. I was guessing that underneath this method it was kind of using string interpolation but it's more than that. This is also maybe why we don't translate logs.

So, I'm closing this issue.
