### ISSUE TITLE
Notifications are hard to read in dark mode due to low contrast

### ISSUE THREAD

**Issue by 0liver** [OrchardCMS/OrchardCore#10796]
### Describe the bug
In dark mode, the notification text is quite hard to read on the green background - see below.

### To Reproduce
1. Turn on dark mode (I don't know where, maybe it's a browser setting?).
2. Go to the Admin dashboard.
2. Look at the Welcome message.

### Expected behavior
An easily readable message text.

### Screenshots

![image](https://user-images.githubusercontent.com/164360/144488122-026aa015-fbd1-4515-9fe0-e76f2ac45b86.png)

The contrast ratio is **2.76:1**, which does not sound too bad, but in combination with the font it actually appears worse than e.g. in [this online tool here](https://contrastchecker.online/155724/28a745):

![image](https://user-images.githubusercontent.com/164360/144488425-a6c9d536-bde2-46e0-aa7b-bca3102fd852.png)

**Comment by Skrypt** [comment]
We have a PR for Bootstrap 5 where it should be fixed. Feel free to contribute there.

**Comment by 0liver** [comment]
Could you please link that PR here?

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/9371

**Comment by 0liver** [comment]
That PR is for using Bootstrap 5 in the Admin area. But notifications are shown in the frontend as well, and there, Bootstrap 5.1 is already integrated from what I saw in the commits between 1.0 and 1.1.

And while I would like to submit a PR, I really don't have any idea of OC's design system, so it would be hard for me to suggest something that will work in the broader context.

**Comment by Skrypt** [comment]
The frontend themes have their own thing so it's another topic.

Here, you just need to modify the text color for when we are in the dark mode. I will take a look as part of #9371

**Comment by Skrypt** [comment]
Fixed in #9371
![image](https://user-images.githubusercontent.com/3228637/148517069-d06d55e9-cb05-4b6a-837e-a06c459119b2.png)

**Comment by hishamco** [comment]
Could you please link this issue into Bootstrap PR or mention it in the description, so when the PR is merged it should be closed automatically

**Comment by Skrypt** [comment]
It is already linked look at the right panel here.
