### ISSUE TITLE
Distributed tenants still produce flat files

### ISSUE THREAD

**Issue by sonicmouse** [OrchardCMS/OrchardCore#10794]
I need to make sure that I set up a SaaS that has tenants that can run on multiple instances. I believe I have set this up correctly, but the tenant is still producing files.

I am using .NET Core 3.1 and the NuGet packages to accomplish this. My `appsettings.json` is set up as so:

```
{
	"EnvironmentName": "Development",
	"OrchardCoreFeatures": {
		"Global": [
			"OrchardCore.Redis",
			"OrchardCore.Redis.DataProtection",
			"OrchardCore.Redis.Lock",
			"OrchardCore.Redis.Cache",
			"OrchardCore.DataProtection.Azure"
		]
	},
	"OrchardCore": {
		"DatabaseProvider": "SqlConnection",
		"ConnectionString": "...",
		"OrchardCore_Admin": {
			"AdminUrlPrefix": "SomethingAdmin"
		},
		"OrchardCore_Shells_Database": { // needs AddDatabaseShellsConfiguration() registered in startup
			"DatabaseProvider": "SqlConnection",
			"ConnectionString": "...",
			"TablePrefix": "something-cms-shellsettings",
			"MigrateFromFiles": true
		},
		"OrchardCore_Media_Azure": {
			"ConnectionString": "...",
			"ContainerName": "something-cms-{{ ShellSettings.Name }}-media",
			"BasePath": "Media",
			"CreateContainer": true
		},
		"OrchardCore_DataProtection_Azure": {
			"ConnectionString": "...",
			"ContainerName": "something-cms-dataprotection",
			"BlobName": null, // auto-generate based on tenant name
			"CreateContainer": true
		},
		"OrchardCore_Redis": {
			"Configuration": "...",
			"InstancePrefix": "something-cms-"
		}
	}
}
```
How my startup.cs looks:
```
public class Startup
{
	private readonly IConfiguration _config;

	public Startup(IConfiguration configuration)
	{
		_config = configuration;
	}

	private string[] GetStringsFromConfig(string section) =>
		_config.GetSection(section).Get<string[]>() ?? Array.Empty<string>();

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddOrchardCms(builder => builder
			.AddGlobalFeatures(GetStringsFromConfig("OrchardCoreFeatures:Global"))
			.AddDatabaseShellsConfiguration() /* config in OrchardCore_Shells_Database appsetting */);
	}

	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
		}

		app.UseOrchardCore();
	}
}
```
I start with a fresh database, a cleared Redis Cache instance, empty blob storage account and an empty `App_Data` directory.

I create a SaaS service, and everything still looks OK:
- There was no `App_Data` directory created.
- The Azure Blob Storage container got created with the `DataProtectionKeys.xml` file.
- The database has the tables `*shellsettings_Document` and `*shellsettings_Identifiers` tables.
- The Redis Cache has the keys `*DefaultOrchardCore.Roles.Models.RolesDocument`, `*DefaultOrchardCore.Settings.SiteSettings`, `*DefaultID_OrchardCore.Roles.Models.RolesDocument`, `*DefaultID_OrchardCore.Settings.SiteSettings`.

Next, I go into the features section of the SaaS service and enable `Distributed Tenants`.

Finally, I create a new headless tenant. I click "Setup" in the UI, fill in the details and click "Finish Setup".

- The Azure Blob Storage was created for the tenant and has the `DataProtectionKeys.xml` file.
- The database has a slew of new tables prefixed with the new tenant's name.
- The Redis Cache has a slew of new keys created with the new tenant's name.

But, an `App_Data` directory exists with the following files:
![image](https://user-images.githubusercontent.com/2473180/144464521-606055e9-20d5-43c4-aa20-555f9732d843.png)

I see a `Media` directory. That makes sense, I haven't turned on `Azure Media Storage` in the new tenant yet. I'll do that now. That turns on the `Media Cache` feature automatically as well.

Maybe these are just artifacts left over from initializing the site? So, I shut down the site. Shift+Delete the `App_Data` directory and start the service back up.

The `App_Data` directory is re-created, but now it looks like this:
![image](https://user-images.githubusercontent.com/2473180/144466377-baaf373f-d5f5-497a-9c29-dcf213f4a1e2.png)

**And all my `Content Types` and `Content Parts` are gone.**

1) How do we make Content Type/Parts store in the database or in a distributed way?
2) Are the rest of these files not needed to run as a distributed service? So, let's say I deploy this service in an App Service Plan in Azure. Then I scale the App Service Plan to 2 instances. Now there are 2 instances that have their own set of flat files. Will this cause conflicts?

I think this software is amazing and I really want to use it at my company for all our CMS needs, but the Distributed tenants are probably the most important feature. DevOps won't even look at it if it can't scale horizontally properly.

Thanks for any information you can give me.

**Comment by sebastienros** [comment]
The lucene modules is fine creating files locally on each node, it syncs locally all the indices. There is an ElasticSearch PR though that you might be interested into if you really don't want this behavior.

For data protection, there are custom modules to store the keys on blob storage or Redis.

**Comment by sonicmouse** [comment]
What about the `ContentDefinition.json` file? How is that distributed?

**Comment by deanmarcussen** [comment]
For that you need to disable the File Content Definition store, and they will be stored in the database.

See the docs: https://docs.orchardcore.net/en/latest/docs/guides/content-definitions/

Each component/module/feature uses it's own distributed features, so you need to choose to turn them all on.

**Comment by sonicmouse** [comment]
Now I get it, Thank you.

There is one last question I have about what you said in your first answer:

_For data protection, there are custom modules to store the keys on blob storage or Redis._

What exactly does that mean? Is that for the `IdentityModel-*-Certificates` directory data you're talking about? Or are you talking about the `OrchardCore.DataProtection.Azure` and `OrchardCore.Redis.DataProtection` features?

**Comment by Skrypt** [comment]
As part of this, here is one solution that I think should have been done for a while but felt under the table : 

https://github.com/OrchardCMS/OrchardCore/pull/10799

**Comment by sonicmouse** [comment]
One final question: When setting up Redis Cache, will it need to have persistent data turned on? For example, if the Redis server reboots, will losing those keys cause any issues, or will it regenerate what it needs to function properly?

**Comment by Skrypt** [comment]
When restarting the application it will cache back what it has in the persistence storage. If the Redis server reboots and doesn't save beforehand what it had cached then you lose what was currently cached. Though, when we update records I believe that we push the changes to the persistence storage and then invalidate the cache to get it refreshed. @jtkech might have more insights about this if that's not the case in certain places.

**Comment by jtkech** [comment]
Yes @Skrypt is right when data are not available from Redis there are retrieved from the shared database, and we take care that Redis data are kept in sync with the related data in the database.

For info we now have a failover mode when Redis is disconnected, in that case we read data from the database (with some local caching with low expiration time) but we don't allow to update data, this until Redis is re-connected.

**Comment by sonicmouse** [comment]
OK, so in turn, if the keys are removed from redis, then they will regenerate organically with no issues, correct?

**Comment by jtkech** [comment]
Yes

**Comment by Skrypt** [comment]
As long as you are using data that came serialized from the database it should work. On server-side and on client-side.

**Comment by sonicmouse** [comment]
OK -- just verifying. I have Orchard running in Azure on Linux across 3 instances right now and it's working great.

Thanks to everyone who helped out. This software is almost too good to be true. Great job everyone.
