### ISSUE TITLE
Content folder is not watched?

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#1080]
Why is content folder not watched?

It would make life so much easier when in development.

https://github.com/OrchardCMS/OrchardCore/blob/a32f02ab9ee5bc1cd85500e742f25c6a0c024590/src/OrchardCore/OrchardCore.Modules/ModuleProjectContentFileProvider.cs#L78-L81

**Comment by jtkech** [comment]
As i remember.

- We do this for razor files to tell to the razor engine when it needs to do a re-compilation. But for a content file, as i can see, we just need to serve it from the project location.

- When you update a content file, at least you need to do a refresh on client side. Try also to clear the cache under the browser tools.

- Another scenario is when you update a file which is not directly requested by the client, this when it needs to be embedded in another file which is the result of a gulp task that you would need to do.

**Comment by awyl** [comment]
How do I serve it from the project location?  I think currently it is serving from the `Packages` folder.

I have a gulp task that bundle js files in a `Assets` folder to the `Content` folder.  I change one of the js file, and the bundle is recreated.  But the one in `Packages` folder is not updated.  So it is not a cache issue.  By the way, I have "Disable cache" in the developer console, so every time I refresh, the browser will bypass the cache.

**Comment by jtkech** [comment]
Based on your environment you need to have `env.IsDevelopment() == true`, [see here](https://github.com/OrchardCMS/OrchardCore/blob/a32f02ab9ee5bc1cd85500e742f25c6a0c024590/src/OrchardCore/OrchardCore.Modules/Extensions/ModularApplicationBuilderExtensions.cs#L57) (we check the same somewhere for razor files).

It is done through an environment variable. Under VStudio, in the web app properties, in the debug tab, you need to set `ASPNETCORE == Development`.

**Comment by awyl** [comment]
There is already this:
`ASPNETCORE_ENVIRONMENT = Development`

**Comment by jtkech** [comment]
> But the one in Packages folder is not updated

Yes, you would need to re-build the app. But while in dev we serve the one in the project location. We know project content file paths by looking in this mapping file which is generated on build.

    src\OrchardCore.Cms.Web\obj\ModuleProjectContentFiles.map

Can you check if the path of your requested requested file is in this mapping file.

On my side I will re-try it this night and let you know my findings.

**Comment by awyl** [comment]
Yes, the paths are like the `ModuleProjectRazorFiles.map`.
```
"physical path in the module folder"|"packages relative path"
```

Thanks for taking a look.

**Comment by jtkech** [comment]
- Just re-tried with `src\OrchardCore.Themes\TheAgencyTheme\Content\js\contact_me.js`. I took this one to not have to run a gulp task.

- Then, when i update the above file, after a refresh i can see the change through the browser tools.

- So, i would need more infos on your use case.

**Comment by awyl** [comment]
Perhaps it was because I was using nuget packages instead of full source code?

**Comment by jtkech** [comment]
Maybe. For a given module, the above works if your app references it as a project. Your app also needs to reference a bundle (renamed target) as a package OR as a project. In the last case you also need to do some imports, see the `.csproj` of the web app in our solution.

**Comment by awyl** [comment]
I figure out why changes are not reflected during development.  But I am not sure whether it should be fixed.

The reason is `ModuleProjectContentFileProvider` is case sensitive. 
For example, my file is `c:/somepath/mymodule/Content/Scripts/some.js`.

So 
`/mymodule/scripts/some.js` will be mapped to `/Packages/mymodule/Content/Scripts/some.js` by the `PhysicalFileProvider`
`/mymodule/Scripts/some.js` will be mapped to `c:/somepath/mymodule/Content/Scripts/some.js`

Since OC could be run in Linux, or Mac.  I think this shouldn't be fixed???

**Comment by jtkech** [comment]
Good catch.

> Since OC could be run in Linux, or Mac. I think this shouldn't be fixed???

I think your are right. On another side when you request `.../scripts/some.js` the default provider fallback to `.../Scripts/some.js` (i think it detects it is on Windows), so ... But not sure it's a good idea for an app which could target different environments ...

So, in our side i think it's better to keep it case sensitive, otherwise we would need to check the environment. I also think it can help to prevent some issues e.g if we debug an app on Windows and then use it in another environment where you should be case sensitive.
