### ISSUE TITLE
Consider allowing more OpenIddict endpoints to be enabled via the UI and via recipes

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#10803]
As a basic authorization server, the OpenID module doesn't use all the features/endpoints offered by OpenIddict, like introspection and revocation. As mentioned in https://github.com/openiddict/openiddict-core/issues/1359#issuecomment-985710404, these features can be configured by amending the OpenIddict settings via a custom plugin, but a simpler story - GUI or recipes-based - may be preferable.

Additional context: https://github.com/openiddict/openiddict-core/issues/1359#issuecomment-985252903

**Comment by kevinchalet** [comment]
@mcalasa said he was interested in sending a PR to add introspection/revocation support: https://github.com/openiddict/openiddict-core/issues/1359#issuecomment-1114159565 ❤️

**Comment by mcalasa** [comment]
@kevinchalet I've added Allow Introspection and Revocation Endpoint check boxes to the OpenId Application Settings page and that is saving the settings in the database correctly as I check and uncheck it then save.  
![image](https://user-images.githubusercontent.com/1282946/169981525-58520c81-3dcc-4484-b021-a498cbe4bcc2.png)


I've also added Enable Introspection and Revocation Endpoint check boxes to the OpenId Server settings page and that is saving the settings in the database correctly as I check and uncheck it then save as well.
![image](https://user-images.githubusercontent.com/1282946/169981756-95a7cf12-4717-498b-9719-93c6c6c033ad.png)



Now for the server settings I'm not too sure how to actually plug-in the Introspection and Revocation server options in OC and will need your guidance there. I'm guessing I may have to submit a PR in Openiddict to modify OpenIddictServerAspNetCoreOptions, OpenIddictClientOwinOptions and any other files related to it to include those options in there?  I'm basing this by looking at how enabling the user info endpoint was implemented. 
Let me know your thoughts on this.

Thank you

**Comment by mcalasa** [comment]
Oh man, can't believe I missed that LOL.  You the man @kevinchalet 
Easy enough change to make and will test this out.

Thank you!

**Comment by kevinchalet** [comment]
Haha. Let us know how it goes 😄

**Comment by mcalasa** [comment]
@kevinchalet As I was about to test the Authorization Code Flow I noticed that PKCE was not an option.  I saw this issue https://github.com/OrchardCMS/OrchardCore/issues/7138#issuecomment-723453045 and told myself why not and proceeded to add PKCE to the Server and Application settings pages.  I did confirm that it does save the requirement settings correctly in the database.  I will be testing and verifying to make sure everything works correctly as well.

**Server settings page**
![image](https://user-images.githubusercontent.com/1282946/173217423-b7ae2ce7-e649-4c23-969a-0f219f150235.png)

**Application settings page**
![image](https://user-images.githubusercontent.com/1282946/173217449-36ae875c-11bd-4b6b-ad51-4aee3816cff9.png)

**Comment by kevinchalet** [comment]
Nice!

Should we add a warning message telling users they should ensure their client/client lib supports PKCE before enabling this option?

For the global option, we should at least mention that it will apply to all clients, whether the "require PKCE" flag was set or not on the individual client registrations.

**Comment by mcalasa** [comment]
Should that warning message be like a dialog that pops up stating that their client lib should support PKCE?  Or do you think a label by the check box should state that?

For the global option I'll add a label next to the check box unless you have a better option.
