### ISSUE TITLE
Modules have wrong information or display wrong information

### ISSUE THREAD

**Issue by papyr** [OrchardCMS/OrchardCore#10808]
Please see the picture below, on the home page, when a developer looks for modules in the gallery to add to his orchard site.

The sort order/information about the modules is wrong.

Click sort by `newest`
Also the module specific information `does not have any Info` or links to the `sites/github/source/latest version/compatibility/changelog`. 

Compared to ABP & Serenity, orchard is far behind and slow in development/features, and also hard to understand!

![image](https://user-images.githubusercontent.com/12733414/144688884-1afb7077-4f45-4064-97e5-f10625dafe32.png)

**Comment by jtkech** [comment]
The above modules are related to the previous Orchard not to the new OrchardCore based on AspnetCore

OrchardCore Modules are now exposed as Nuget packages
