### ISSUE TITLE
Unable to find package OrchardCore...

### ISSUE THREAD

**Issue by atorres16** [OrchardCMS/OrchardCore#10800]
### Describe the bug
Restoring nuget packages fail with 3 errors:

1. Unable to find package OrchardCore.Environment.Cache.Abstractions with version (>= 1.0.0-beta2-70992)
    - Found 7 version(s) in nuget.org [ Nearest version: 1.0.0-beta2-69590 ]
    - Found 0 version(s) in Microsoft Visual Studio Offline Packages
2. Unable to find package OrchardCore.Recipes.Implementations with version (>= 1.0.0-beta2-70992)
    - Found 7 version(s) in nuget.org [ Nearest version: 1.0.0-beta2-69590 ]
    - Found 0 version(s) in Microsoft Visual Studio Offline Packages
3. Version conflict detected for Microsoft.AspNetCore.Antiforgery. Install/reference Microsoft.AspNetCore.Antiforgery 2.2.0 directly to project app-host to resolve this issue. 
 app-host -> OrchardCore.Application.Cms.Targets 1.0.0-beta2-70992 -> OrchardCore.Users 1.0.0-beta3-71075 -> OrchardCore.ContentManagement.Display 1.0.0-beta3-71075 -> OrchardCore.ContentManagement.Abstractions 1.0.0-beta3-71075 -> OrchardCore.Mvc.Core 1.0.0-beta3-71075 -> OrchardCore.DisplayManagement.Abstractions 1.0.0-beta3-71075 -> Microsoft.AspNetCore.Mvc.Razor 2.2.0 -> Microsoft.AspNetCore.Mvc.ViewFeatures 2.2.0 -> Microsoft.AspNetCore.Antiforgery (>= 2.2.0) 
 app-host -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.AspNetCore.Antiforgery (>= 2.1.1 && < 2.2.0).

### To Reproduce
1. Follow the instructions on https://docs.orchardcore.net/en/latest/docs/getting-started/templates/
2. In a PS terminal run:
   ```dotnet new occms```
3. Open the project and restore the packages

### Screenshots
![image](https://user-images.githubusercontent.com/19210281/144513594-b6fc695a-1d5f-417a-9ecd-488578cc34ee.png)

Using Visual Studio 2022, Power Shell 7

**Comment by deanmarcussen** [comment]
It looks like you have old templates installed

Can you run 
`dotnet new -i OrchardCore.ProjectTemplates::1.1.0`

and then try `dotnet new occms`

If that still fails, can you past the copy of the `csproj` that has been produced.
