### ISSUE TITLE
Preview Fails in Chromium Browsers

### ISSUE THREAD

**Issue by Ranger1230** [OrchardCMS/OrchardCore#10812]
### Describe the bug
When you try to preview an un-published page in a Chromium Browser (Edge, Chrome, Brave) the preview simply displays "undefined".

### To Reproduce
1. In the Admin go to "Content" then "Content Items"
2. Click on "Edit" for one of the content items
3. Click on "Preview"
4. In a Chromium browser you will see "undefined" for the page contents, in other browsers (Firefox) you see the content for that content item.
5. If you make a change to the content in the "Edit" tab with the preview tab still open, the content will then populate, so this is just on the initial load.

### Expected behavior
All browsers should display the preview content.

### Additional Details
In "\OrchardCore\src\OrchardCore.Modules\OrchardCore.ContentPreview\Views\Preview\Index.cshtml" in the "renderPreview" function in the "$.post(...).done" function there is the line `iframe.contentWindow.document.close();`. In Chromium browsers this appears to trigger the "onload" event for the iframe. If you look up a few lines you will see the iframes onload event is set and the "previewRenderData" is used to populate the iframe. Unfortunately the close function is called before that value is set by the ajax response function.

Maybe the "previewRenderData" should be populated before calling "close()"?

### System Details
MS Edge Version 96.0.1054.43
Brave Version 1.32.113 Chromium: 96.0.4664.45
Windows 11 Build 22000.348

**Comment by Skrypt** [comment]
Open a PR so that we can test it.
