### ISSUE TITLE
Parsing error with standard PoEdit header

### ISSUE THREAD

**Issue by Franklin89** [OrchardCMS/OrchardCore#1081]
If I add the following (standard PoEdit) header to the `SimpleEntry.po` the test will fail:

```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: de_CH\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.0.4\n"

msgid "Unknown system error"
msgstr "Error desconegut del sistema"
```

**Problem**
![image](https://user-images.githubusercontent.com/4151467/31389602-ca7e13cc-add1-11e7-99a0-27f93b61d197.png)

The `ParseIgnoresPoeditHeader` test successfully passes even with the new header. So suppose some more debugging is needed.

I found this error while developing my ASP.NET Core MVC application with the help of your localization implementation. I was using PoEdit to create my translation files. PoEdit adds those headers to the `.po` files.

**Comment by sebastienros** [comment]
Based on the format reference this sound like a bug: http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html#sec-poheader

Would probably be worth implementing all these examples as unit tests.

**Comment by Franklin89** [comment]
So I did some debugging and saw that the header lines that do not start with a hashtag will be parsed as `PoContext.Text` and not like other comments as `PoContext.Other`

I have not looked at the parsing implementation yet, so not sure how everything works yet.

**Comment by sebastienros** [comment]
Would it be that this isn't a bug actually, and that by adding a header a new empty entry is created to the test is broken because it was not designed this way?

**Comment by Franklin89** [comment]
@sebastienros Not sure what you mean here. But this is how PoEdit saves the file, including the header every time. Which will result in a strange translation of the first entry, unless you delete the header manually. I mean I am not sure if this was designed to work with files created with PoEdit? I am only using the localization package in my project.
