### ISSUE TITLE
Admin content list filter needs further extensibility points for sorting

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#10825]
I recently needed to add some additional filtering options to the admin content list and as such implemented my own IContentsAdminListFilterProvider. The filtering options I required restricted the list to certain content types (easy in current implementation) and needed to do a custom sort of the items by a date field attached to the content type using the DateTimeFieldIndex.

Because of the way the sort filter works and that it is always applied with a default sort, implementing custom sorting was not possible because you can not remove a term when another filter is in play and so the "sort" was always ruining my custom sort.

### Describe the solution you'd like
A think the admin content list implementation needs a way of removing a term from the filter if another filter needs it removed in order to work.

### Describe alternatives you've considered
I tried to disabling the sort query but this then applied to all content types and you could no longer sort, not just the content type I was targeting:
```
.WithNamedTerm("sort", builder => builder
   .OneCondition((val, query) =>
   {
    return query;
   })
```
As a workaround, I copied the default logic for the sort filter into my own provider and manipulated the way it worked by removing the `.AlwaysRun()` etc. It doesn't work 100% because if you choose a sort option first and then an option from my custom filter the sort order wins... it only works if the sort has not been selected and is on the default.

Additionally, this is not ideal because it is a unnecessary customization that could cause maintenance issue for in the future if some OC logic for the sort changes or improves.

**Comment by Skrypt** [comment]
I think you can discuss about this with @deanmarcussen.

But generally when 2 different filters don't work well together maybe there is something wrong with the design. I'd like to see it to understand because it is really abstract without seeing the actual result of what you are talking about.

**Comment by scleaver** [comment]
@Skrypt for example - i have a content type called Episode (as in podcast episode) with a DateTimeField called ReleasedUtc which the official date and time in which the episode was released or recorded.

Sometimes the user will want the content list ordered by the standard sort options last published, last modified or last created but a lot of the time they will want or ordered ReleasedUtc - newest (descending order) or oldest (ascending order).

I also have the following options purely for convenience:

This week
Last week
This month
Last month
Last 3 months 
Last 6 months

All of these are ordered by ReleasedUtc in descending order so the newest is at the top.

Hope that explains it

**Comment by deanmarcussen** [comment]
Sorting is hard, because you only ever want to apply one sort. And you must also always apply one sort.

What I would suggest for this one, is that you might be better off just having one sort list, and one sort function.

I would implement a custom `IAdminListQueryService` (compose it from the default one) and when the `options.SelectedContentType == "Episode"` insert the extra values into the `options.Sorts` list before executing the query.

Then I would override the sort filter, keeping the default behaviour, and adding the extra sorts that you want, which will only be selectable when the content type is `Episode`

Reasonably sure that will work.

**Comment by scleaver** [comment]
Thanks @deanmarcussen - that sounds like a better option actually.

I'll leave this open and close it if I don't have any issues
