### ISSUE TITLE
SanitizeHtml logic broken

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#10823]
### Describe the bug

Looks like SanitizeHtml flag for HtmlBodyPart and MarkDownBodyPart is somehow broken. When I set it to false in ContentDefinition my html content (div's etc.) are still render as text and not as part of HTML document.

### To Reproduce
1. Setup Blog recipe
2. In Admin: ContentDefinition -> Article -> HtmlBody (click edit button) -> Sanitize Html (untick this checkbox)
3. Edit Article to include html elements like div's etc.

### Expected behavior
I expect html elements to be render as part of html document when Sanitize Html option is disabled

**Comment by hishamco** [comment]
Seems, you are right, I will have a look

**Comment by hishamco** [comment]
@arkadiuszwojcik could you please try the associated PR

**Comment by hishamco** [comment]
@arkadiuszwojcik seems I miss understood your comment, the html santizer prevents and cleans any user input that leads to XSS, not render the HTML, for more information please refer to https://docs.orchardcore.net/en/latest/docs/reference/core/Sanitizer/

To render HTML markup in your try to use Monaco Editor for instance to allow you to write html code, this will render the HTML output and not displays the HTML code as text

I will do a final check to the source before applying my changes to make sure the santize is working as expected

**Comment by hishamco** [comment]
HTML santizer works as expected

**Comment by arkadiuszwojcik** [comment]
@hishamco maybe I don't undestand something but I have in my recipes such logic:

```
"MarkdownBodyPart": {
   "Markdown": "[file:text('Snippets/articles/article_name.markdown')]"
 } 
```

This markdown document include some html tags. Before everything was working, html was rendered as part of HTML document. Now html parts are rendered as regular text. I thought this issue was related to santizer. What can it be then? I don't even use editor at this point.

**Comment by hishamco** [comment]
@deanmarcussen any idea?

**Comment by deanmarcussen** [comment]
The markdown part doesn't include html by default (html is not part of markdown). It's unrelated to sanitzing.

Docs here: https://docs.orchardcore.net/en/latest/docs/reference/modules/Markdown/#markdown-configuration

I don't know whether you're talking about the Html part here or the Markdown part, but there's nothing in Html sanitization that prevents writing html. Mostly it just removes scripts

**Comment by hishamco** [comment]
> Mostly it just removes scripts

That's what I mentioned https://github.com/OrchardCMS/OrchardCore/issues/10823#issuecomment-987685745, @arkadiuszwojcik hope the answers are clear

**Comment by arkadiuszwojcik** [comment]
Looks like this was my issue. Didn't know that at some point default behaviour changed. It works after change to:

```
"OrchardCore_Markdown": {
      "Extensions": "advanced"
}
```

Thnak you @hishamco and @deanmarcussen
