### ISSUE TITLE
Is there a way to remove the owner and author from being saved in the document table

### ISSUE THREAD

**Issue by SteeveDumais** [OrchardCMS/OrchardCore#10832]
I want to remove the owner and author field from the document table

**Comment by Skrypt** [comment]
You can add a ContentHandler that will null these but I'm strongly advising against doing this because the Permission system gravitates around the owner field. The author is just a data reference.

**Comment by SteeveDumais** [comment]
I was wondering about the document table only not the contentitem table.  The handler send to remove both

**Comment by Skrypt** [comment]
Yes, it will remove both you are right. Probably the permissions are evaluated from the ContentItemIndex table only. Then, what you want is kind of a hack. The `session.save(contentItem)` will trigger the IndexingProvider which will add the data that you passed from the ContentHandler. I'm not sure we can do this, need to look at the different events in the Handler but I'm not sure this will do it.

**Comment by deanmarcussen** [comment]
The `Document table` and `ContentItemIndex` table are intimately connected, i.e. the `ContentItemIndex` is built from the values in the `Document` table, as @Skrypt says.

When a `ContentItem` is deserialized the values are only ever populated from the `Document` that is retrieved. The `ContentItemIndex table is only ever used for querying.

If you remove them, they will be gone for good from both tables.

Which I suspect is not what you want.

Perhaps if you explain what you are trying to achieve then we would be able to advise.

**Comment by SteeveDumais** [comment]
What we are trying to do is to remove all personal information from the document table json so that it would make it easier to create a script to simply remove the author and owner from the contentItem table when we have to comply to GDPR requests.  Going through and cleaning up json is harder and riskier

**Comment by ns8482e** [comment]
@SteeveDumais  As @Skrypt suggested you can implement `ContentHandler` that runs after orchard provided and override Creating/Updating/Versoning methods to override values for Owner/Author

**Comment by SteeveDumais** [comment]
The userid's are app uses is username and emails which is data that has to be scrubbed.  Its ok if it can not be done I will find another way to scrub the data

**Comment by Skrypt** [comment]
People should not use emails as a UserId. It's been migrated so that it's not possible anymore. It's always a unique identifier that could be now something+domain.com if it got migrated properly when a UserId was his email.

**Comment by Skrypt** [comment]
```
-- Assign Users with a UserId

DECLARE @count int
DECLARE @i int = 1
DECLARE @Migrate bit = 1
DECLARE @DocumentId int
DECLARE @NormalizedUserName nvarchar(255)
DECLARE @UserId nvarchar(26)

IF(@Migrate = 1)
BEGIN
	SET @count = (SELECT COUNT(*) FROM UserIndex)
	SET @i = 1
	WHILE(@i <= @count)
	BEGIN
		WITH OrderedUserIndex AS
		(
			SELECT DocumentId, NormalizedUserName,
			ROW_NUMBER() OVER (ORDER BY Id) AS 'RowNumber'
			FROM UserIndex
		)
		SELECT @DocumentId = DocumentId, @NormalizedUserName = NormalizedUserName FROM OrderedUserIndex WHERE RowNumber = @i
		SET @UserId = LEFT(LOWER(REPLACE(NEWID(), '-', '')), 26)

		UPDATE UserIndex SET UserId = @UserId WHERE DocumentId = @DocumentId

		-- We update Users in the Document table
		UPDATE Document
		SET Content = JSON_MODIFY(Content, '$.UserId', @UserId)
		WHERE Id = @DocumentId

		-- We add UserId on all ContentItems in Document table
		UPDATE Document
		SET Content = JSON_MODIFY(Content, '$.Owner', @UserId)
		WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions'
		AND JSON_VALUE(Content, '$.Owner') = REPLACE(@NormalizedUserName, '+', '@')

		SELECT @i = @i + 1
	END
END

UPDATE ContentItemIndex SET Owner = (SELECT JSON_VALUE(Content, '$.Owner') FROM Document WHERE Id = ContentItemIndex.DocumentId)

-- Change SuperUser in sitesettings

UPDATE Document SET Content = JSON_MODIFY(Content, '$.SuperUser', (SELECT UserId FROM UserIndex WHERE NormalizedUserName = 'ADMIN'))
WHERE Type = 'OrchardCore.Settings.SiteSettings, OrchardCore.Settings'
```

**Comment by sebastienros** [comment]
I concur you can create the handler to not store the Author property anywhere (it's purely for denormalizing the user name in the json document and table). And you will have to run some query or code if you want to remove old values if you have any. But if you start gathering data with your handler, then you won't have to scrub data.

**Comment by SteeveDumais** [comment]
We have changed the value in the handler and have created a script to cleans the data
