### ISSUE TITLE
External login does not record user logged in audit trail event

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/OrchardCore#10836]
### Describe the bug
When a user logs in using an external login such as Azure AD with the user audit logging turned on for the logged in event, nothing is recorded in the audit log. It works correctly with local login. It appears that the UserEventHandler LoggedIn event is never invoked and therefore the audit trail record is never created.

### To Reproduce
1. Enable and configure an external login
2. Enable Audit Trail and the Users Audit Trail features
3. Log out and log back in using the external login configured in step 1
4. No logged in audit trail record will be created

### Expected behavior
After a user successfully logs in with an external login, the UserEventHandler->LoggedInAsync event should be invoked so that an audit trail record is created for the logged in event similar to how it is done for local login.

**Comment by Piedone** [comment]
This should be supported, see `ExternalLoginCallback`. However, I don't see how this can not work on a successful login, as it triggers the WF event directly from `LoggedInActionResult()`. Strange.

**Comment by douwinga** [comment]
Ya, the workflow event works as expected, but the audit trail uses a separate user event handler that is not getting invoked. It appears the `LoggingInAsync` is being invoked but `LoggedInAsync` is not. I am just not sure when exactly this should be called in the `AccountController`
