### ISSUE TITLE
Media added via code deleted from ContentItem if updated manually

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#10843]
Media added vi code with name ,deleted from ContentItem if it was updated manually from the admin page

### Screenshots
![image](https://user-images.githubusercontent.com/61165619/145391590-8944a556-711b-4c66-abbe-91821c1dd133.png)

**Comment by Skrypt** [comment]
This can happen if the Media field uses an attached media field. Because the image picker expects that the file stands in a different folder.

**Comment by vitalybrandes** [comment]
> This can happen if the Media field uses an attached media field. Because the image picker expects that the file stands in a static folder.
> 
> See #10570

Will 10570 fix it?

**Comment by deanmarcussen** [comment]
Are you actually using the Attached Media Field editor?

If so, then you would need to add the media item, in the same way the editor does, (with the attached media service) to prevent that.

Or don't use the Attached Media Field editor

**Comment by vitalybrandes** [comment]
> Are you actually using the Attached Media Field editor?
> 
> If so, then you would need to add the media item, in the same way the editor does, (with the attached media service) to prevent that.
> 
> Or don't use the Attached Media Field editor

@deanmarcussen 
Yes, i do using attached media editor.
Ill switch it to check.
thank you
