### ISSUE TITLE
Allow sending email without "To" if "Cc" or "Bcc" is provided

### ISSUE THREAD

**Issue by bluenex** [OrchardCMS/OrchardCore#10840]
### Is your feature request related to a problem? Please describe.

We implement an email system to send to many recipients at once and want the recipients to be in "Bcc" instead of "To". The current working email module on upstream seems to require "To" so having only "Bcc" is not possible to send.

### Describe the solution you'd like

We use workflow to send the email data received from the front-end form. So, we modified workflow related files, and here are some of the places we made changes:

- add optional to `recipients` on this line
https://github.com/OrchardCMS/OrchardCore/blob/e73a81ee82bb55fad2a4ac5d3d1fe6fd986f28b4/src/OrchardCore.Modules/OrchardCore.Email/Workflows/Activities/EmailTask.cs#L125

- remove `[Required]` from `RecipientsExpression` on this line
https://github.com/OrchardCMS/OrchardCore/blob/e73a81ee82bb55fad2a4ac5d3d1fe6fd986f28b4/src/OrchardCore.Modules/OrchardCore.Email/Workflows/ViewModels/EmailTaskViewModel.cs#L17-L18

With this, we are able to send an email to "Bcc" only.

### Describe alternatives you've considered

I propose this because I feel that it should be possible to send an email with only either "Cc" or "Bcc". But it is up to the team to consider how this should be implemented.

**Comment by Skrypt** [comment]
Okay, but if we do so we need to have a validation that prevents trying to send an email without a To, Bcc or Cc provided.

**Comment by Skrypt** [comment]
I suggest we look at the RFC to make sure about this.

**Comment by sebastienros** [comment]
If our client supports that feature then it should be fine.

**Comment by Piedone** [comment]
`To` is not required if `BCC` is present: https://www.oreilly.com/library/view/programming-internet-email/9780596802585/ch02s04.html

**Comment by hishamco** [comment]
After few investigation `TO` is required as I said before according the RFC https://datatracker.ietf.org/doc/html/rfc822#appendix-A.3.1, so I'm with @Skrypt we should follow them, in this case a custom implementation of `ISmtpService` may better to satisfy the customer needs

Thanks

**Comment by hishamco** [comment]
> To is not required if BCC is present: https://www.oreilly.com/library/view/programming-internet-email/9780596802585/ch02s04.html

According to the link above, Date, From and either To or BCC are mandatory headers.

What about CC? The interesting part is they are referring to RFC 822 which I pointed to above ;) I don't know from which paragraph they quote this, if someone can help me to find anything please shoot it here to make it clear to everyone

**Comment by Skrypt** [comment]
If our library supports it then it must be ok. I'm not sure if this RFC is up to date. You can see also that there have been updates of that RFC document which obsoletes some parts of it. So, you need to be careful when analyzing RFC documents. What I think is that for sending an email you should have at least one address in either To, Cc or Bcc so we should validate that we have at least one address in one of those fields.

Also like Sebastien said. It's about the library that we use. If they support it then it should be fine. Else, it's them that are not following RFC and should fix the issue. So it's not on us to decide that part. Maybe look at the Mailkit repository to sort things out.

**Comment by hishamco** [comment]
Thanks Jasmin, so we should have at least on of the following fields presents: To, Cc or Bcc. I will work on this soon after verifying that my other PR is passing ;)

I think this should mentioned in docs too to make it clear to the audience

**Comment by bluenex** [comment]
@hishamco I tried following the RFC to answer your question.

Starting form [RFC 822 here](https://www.rfc-editor.org/info/rfc822), it is obsoleted by these RFCs respectively 

- [RFC 2822](https://www.rfc-editor.org/info/rfc2822)
- [RFC 5322](https://www.rfc-editor.org/info/rfc5322) -> this is updated (appended) by [RFC 6854](https://www.rfc-editor.org/info/rfc6854)

In [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322.txt) at `3.6. Field Definitions`, there is a table containing min and max number for each field.

Checking at [FAQ page of MailKit](http://www.mimekit.net/docs/html/Frequently-Asked-Questions.htm), I still find RFC 822 mentioned along with a couple of other RFCs. However, from what we have tried on our local, it does support sending to Bcc only.

**Comment by hishamco** [comment]
I already started a PR, but the functional tests fails in Ubuntu

**Comment by hishamco** [comment]
The PR is almost (if not all) ready, waiting for a feedback

**Comment by Skrypt** [comment]
RFC 5322 --> 3.6.3

**Comment by hishamco** [comment]
@bluenex your can try the feature that you asked for using the latest bits
