### ISSUE TITLE
Update LangVersion to 9 at least, or rather 10

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#10850]
### Is your feature request related to a problem? Please describe.
Currently, the allowed C# language version depends on the development environment. Instead, we should specify it explicitly.

### Describe the solution you'd like
Specify `<LangVersion>10</LangVersion>` in `OrchardCore.Commons.props`.

### Describe alternatives you've considered
I guess this is not as trivial as this, since this config was changed around a lot: https://github.com/OrchardCMS/OrchardCore/pull/9017 configured it as 9.0, https://github.com/OrchardCMS/OrchardCore/pull/9079 reverted this to 8.0, and https://github.com/OrchardCMS/OrchardCore/pull/10038 removed the property altogether. Maybe we need to drop .NET Core 3.1 support for this?

**Comment by hishamco** [comment]
> Maybe we need to drop .NET Core 3.1 support for this?

This can be done after few month, when the 3.1 is out of date (if all agreed)

**Comment by deanmarcussen** [comment]
Yes, it's not that trivial.

The Razor compiler in 3.1 doesn't support new lang features.

So really you want to open an issue regarding when to drop 3.1 I'm open to it, but the idea hasn't got a lot of traction so far.

**Comment by sebastienros** [comment]
We said we would drop netcoreapp3.1 (and net5.0) once we have shipped 1.2.

**Comment by hishamco** [comment]
While `netcoreapp3.1` is LTS version I suggest to drop it after ~3 months (when it reaches the EOS)
