### ISSUE TITLE
Admin filter terms should be more descriptive 

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#10862]
Currently we have the following filter terms  for content items : 

- status
- sort
- type
- text

Propose to replace with more descriptive term names like : 

- contentitem.status
- contentitem.sort
- contentitem.contenttype
- contentitem.displaytext

The reasons are : 

- Easier to understand where the mapping is going on.
- Less error prone to conflicts from custom indexes. Eg I had a custom index on an Issue contenttype with a status field .  I named my custom term  "status" which conflicted with the existing status term.  By having a guideline to prefix with contenttype  its more unlikely to have conflicts . eg so I could write contentitem.status:Published issue.status=InProgress  

@deanmarcussen

**Comment by deanmarcussen** [comment]
>Easier to understand where the mapping is going on.
Less error prone to conflicts from custom indexes.

These sound like development concerns, and not actual usage concerns.

The idea of having a short term name is to allow quick entry of a term (if a user wants to enter it manually).
So making them longer seems counter-productive.

Also it is the `ContentItems` list, so why would you have to specify `contentitem` to search a contentitem property?

I would suggest that for your scenario, if you want to extend them like that, it would be better if you removed the registration for the standard terms, and registered with the name you want.

Potentially we could add some functionality to the term builder to make that easier to do, but there's nothing currently that prevents you removing the di registrations, and adding them as you prefer.

You would also have to update the helper views I suspect

**Comment by giannik** [comment]
ok @deanmarcussen  I can do that locally.
Just thought it would be usefull for others.
