### ISSUE TITLE
BlobFileStore performance improvement

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#10876]
While doing performance testing with images I found that the BlobFileStore.GetFileInfoAsync() was quite expensive to use.  One thing I've noticed is that there is an ExistsAsync call which doesn't appear to be required as the blob.GetPropertiesAsync() call will throw a RequestFailedException with an error code of "BlobNotFound".  While the usage of exceptions is known to be less performant I'm working under the assumption that calls to this method will occur after a file has been uploaded so we can expect it to exist most of the time.

Based on that I'd like to create a tiny PR that removes the ExistAsync call and replaces it with an additional catch for the exception I mentioned above.  

I've verified that updating a file doesn't make use of this call but there may be other reasons this check needs to exist? 

Thoughts?

**Comment by sebastienros** [comment]
Fine as long at the change has a comment explaining why ExistAsync is not called.

**Comment by sebastienros** [comment]
@hishamco you don't need to cc people, we do triage and can assign people when necessary, and we also have notifications turned on. Unless you see there is no traction (like more than 10 minutes).

**Comment by Piedone** [comment]
I guess Hisham's intention is to make sure those people who have worked on related things are notified. I personally welcome these :).

**Comment by sebastienros** [comment]
Maybe because you don't follow all issues, or are not pinged as much. But sometimes it just duplicates notifications that we already get. At least as I mentioned if this is done "some time" after the issue is created to give a chance to read it or respond. Being cc'ed seems like there is something that has to be handled with some sort of urgency.

**Comment by hishamco** [comment]
Noted

**Comment by ShaneCourtrille** [comment]
@sebastienros Is the comment in the pull request what you were thinking?  Thanks
