### ISSUE TITLE
Edit Template Editor Suggestions

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1087]
- Support Ctrl+S to save the template and continue editing. The current workflow is limited.
- Use CodeMirror or Monaco to support syntax highlighting (At least HTML)

**Comment by sebastienros** [comment]
CTRL+S is a good idea, could just trigger the form POST, but we need to change the controller to not redirect to the list page if a specific argument is set.

For the second suggestion, we are already using codemirror and there is syntax highlighting 

![image](https://user-images.githubusercontent.com/1165805/31454854-b0cc0f70-ae6b-11e7-9e35-b6bfbc94452d.png)

**Comment by dodyg** [comment]
OK - is that in dev branch? Because master branch does not have the editor

![no-editor](https://user-images.githubusercontent.com/1761249/31476844-e700255c-af08-11e7-967e-f4fb6f0effcd.png)

**Comment by sebastienros** [comment]
Both, since the templates feature exists. Maybe there is an issue with the
scrips, can you check the network tab for any missing ones?

**Comment by dodyg** [comment]
OK - I think it's because of this

```
https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
```
I am accessing the web from China without VPN and they blocked Google here.

**Comment by Jetski5822** [comment]
Argh - The great firewall!!! 

You could try turning off the use of the CDN in the site settings page?

**Comment by agriffard** [comment]
The CDN option is not yet added in the Settings in OC : see #448

**Comment by sebastienros** [comment]
We can change the themes to use local resources. The can be added to the theme directly, if they are not in Resources already. I don't want to add too much to the Resources because of the themes.

**Comment by sebastienros** [comment]
I like the CTRL+S idea, probably should be mapped to Draft also in content items.
But Chome already has a binding for it.
Maybe a shortcut for Preview also.

**Comment by agriffard** [comment]
Other interesting UI improvement:
Always have the buttons visible, even if the codemirror area is long.

Like the filter bar on some list pages.

/cc @hishamco

**Comment by hishamco** [comment]
@agriffard this could be different coz the action button are on the bottom of the page, I made an experiment to make this happen by triggering scroll event

**Comment by hishamco** [comment]
BTW @agriffard we may need to open a new issue related to key binding, so I can apply this in all the pages in the admin site. We need to agree about the suitable shortcuts for each action
