### ISSUE TITLE
Audit Trail : View element perf issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10884]
When trying to view an audit trail element by clicking on the "View" button on the Audit Trail event it takes around 46 seconds to display the page.

![image](https://user-images.githubusercontent.com/3228637/146225888-bc8bb17a-eab9-45a0-987e-5876015e533d.png)

![image](https://user-images.githubusercontent.com/3228637/146225833-0751464d-f0a9-48be-84fb-4fa28b7c7e08.png)

![image](https://user-images.githubusercontent.com/3228637/146226079-e9959ffd-0575-47fa-a164-ed439e991325.png)

**Comment by Piedone** [comment]
Do you have any further info or a repro you can share? I don't see this issue even with a huge amount of Audit Trail events.

**Comment by Skrypt** [comment]
I don't have more details maybe the issue is specific or it's not there anymore. Need to test.

**Comment by Piedone** [comment]
Closing due to no updates.
