### ISSUE TITLE
Prevent some important static routes to be used in the Autoroute.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10909]
For example, the /login route can be overridden by a page named Login which will prevent the user to be able to login into the admin and unpublish the page.

There are probably other routes like these that should never be used with an AutoroutePart that should be validated.
Maybe the Route Table could be parsed to prevent this to happen. Else, an excluded paths dictionary could work too.
Not sure if the route table would be too much performance-wise though.

**Comment by ns8482e** [comment]
I guess to override the route - the `ConfigureOrder` for overriding route needs to be before the overridden route, - so if developer defines route `/login` with `ConfigureOrder = -1` will take precedence over `/login` provided by Users module  - Isn't that the expected behaviror?

**Comment by Skrypt** [comment]
That's one way to fix the issue. I think though that being able to override routes is expected behavior.
We have one configuration to allow modifying the Login view inside a theme but it's not relevant if we can override it with an autoroute. One could use a Liquid page with a custom form to customize its login page, so I'm not sure at all what we should do. Just raised the issue for now.

**Comment by ns8482e** [comment]
@Skrypt I agree with this issue - IMHO Content Editor should not be able to override code provided routes by just creating and publising a content item with same route using Autoroute.  - Code provided routes should have higher precedence over Autoroute provided routes.

**Comment by sebastienros** [comment]
I think it's ok to override, and if it's actually an issue for their site, then stop doing it. If we block then users will be blocked from doing it and ask to remove the constraint.
