### ISSUE TITLE
Implement content item permissions

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1091]
Content item permissions need to be dynamic so that they can be assigned by Content Type or Owner (just like O1)

**Comment by hyzx86** [comment]
Hi @Skrypt  ,Is this function done in this branch?

**Comment by Skrypt** [comment]
No it's not, it's just a beginning of migrating the old module to OC. Nothing should be considered final.

**Comment by alexdresko** [comment]
Please help me understand. Does this mean that the "Content Item Permissions" module is not available, even in the dev branch? I'm using the dev branch (1.0.0-beta3-70508), and I'm having a really difficult time figuring out how to do some of the security-related things that are discussed here in the repo and on SO. For example, I'd like to secure a content type, or a content item and I don't see any such functionality. I see the "securable" checkbox on the content type, but it doesn't appear to do anything. I also don't see a "Content Item Permissions" module. 

So I'm really confused by all this and I'd be super grateful if someone could help iron things out. As it stands, I feel like I'm just flailing my arms around, and it's not getting me anywhere.

**Comment by Piedone** [comment]
The securable checkbox does nothing at the moment (https://github.com/OrchardCMS/OrchardCore/issues/2570) and there is no content item-level access control either (the infrastructure for that is there, but there is no implementation, so in a custom module you can still do content item-level access control).

**Comment by alexdresko** [comment]
@Piedone - Thanks for the tips. That's very helpful. 

> so in a custom module you can still do content item-level access control

Can you expand on that just a bit? Do you mean [this](http://docs.orchardproject.net/en/latest/Documentation/Developer-FAQ/#what-is-the-permissionscs-file)?

**Comment by Piedone** [comment]
Close, but that's the docs for Orchard 1.x :). For Core it's here: https://orchardcore.readthedocs.io/en/latest/

What I mean is that in Orchard the ASP.NET Core `IAuthorizationService` is used to authorize access to content items, like when showing the editor of a content item: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/AdminController.cs#L438 Note that the content item object is passed to the `resource` parameter.

You can write an `AuthorizationHandler` that will hook into the authorization pipeline, recognize that a content item is being authorized against, and execute some arbitrary logic to determine whether the authorization is successful. This is how role-based authorization is also implemented (minus checking for the content item), see: https://github.com/OrchardCMS/OrchardCore/blob/d729a2048a4390380d99e7be9f7968ff8f8e9271/src/OrchardCore.Modules/OrchardCore.Roles/Services/RolesPermissionsHandler.cs Once these missing features are done they'll be implemented in a similar fashion too.

**Comment by agriffard** [comment]
Related to #3354

**Comment by dalenewman** [comment]
There is a community created module for content item permissions [here](https://github.com/EtchUK/Etch.OrchardCore.ContentPermissions).  It's working for me.

**Comment by Piedone** [comment]
@peterkeating is the module open-source? There's no licence.

**Comment by peterkeating** [comment]
@Piedone Yeps! I've gone through and added a license to all our open source modules 👍

**Comment by Piedone** [comment]
Great then! So unless you have any objections I'd guess if people really want it as part of an OOTB feature of Orchard (I would, it was also part of O1) then your module could be incorporated into Orchard, keeping the licence.

**Comment by peterkeating** [comment]
No objections at all :)

**Comment by Piedone** [comment]
Thank you, fantastic! Somebody just asked about this under https://github.com/OrchardCMS/OrchardCore/issues/5925.
