### ISSUE TITLE
Autofac module dependency registration not working

### ISSUE THREAD

**Issue by sparrow58** [OrchardCMS/OrchardCore#10932]
### Describe the bug
I just added OrchardCore to my project that already had Autofac module and everything was working correctly, after adding:      

`services.AddOrchardCore().AddMvc();` 

And: ` app.UseOrchardCore();` to the Startup.cs.
The autofac registration stopped working and I get exception: 
`InvalidOperationException: Unable to resolve service for type 'Tharwat.DataAccess.IRepositoryAsync 1[Tharwat.Easy.Domain.Models.WifiNetworks.Network]' while attempting to activate 'Tharwat.Easy.Web.Controllers.WifiNetworks.NetworkController'`
This is how I register Autofac Module in the Startup.cs

```
 public void ConfigureContainer(ContainerBuilder builder)
        {
            builder.RegisterModule(new AutofacModule());
        }
```

```
public class AutofacModule: Autofac.Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            //base.Load(builder);

            var asm = new[]
            {
                Assembly.GetExecutingAssembly(),
                Assembly.Load("Tharwat.Easy.Domain"),
                Assembly.Load("Tharwat.Easy.DataAccess"),
            };

            builder.RegisterAssemblyTypes(asm)
                   .AsImplementedInterfaces()
                   .PublicOnly();
              ...
              ...
              ...
        }
    }
```

I understood that OrchardCore uses Autofac, but why it overrides my autofac regiseration and what should I do to make it work.

**Comment by Skrypt** [comment]
Orchard Core doesn't use Autofac at all. We are using .NET Core DI.

**Comment by hishamco** [comment]
I surprised when @sparrow58 mentioned that, I was telling myself seem a new update happen which I don't know about it ;)

BTW you can use `Autofac.Extensions.DependencyInjection` instead of creating a new module for that, please checkout https://docs.autofac.org/en/latest/integration/aspnetcore.html

**Comment by deanmarcussen** [comment]
Orchard1 used AutoFac which maybe where your confusion comes in.

Orchard Core as @Skrypt says uses Microsoft DI, and we are dependant on that, and do not support any other containers, including AutoFaq.

You can search the issues we are are tracking support for it, but it is not straightforward to achieve.

**Comment by sparrow58** [comment]
Guys, I'm confused. What does this docs belong to [https://docs.orchardproject.net/en/latest/Documentation/How-Orchard-works/]()

**Comment by Skrypt** [comment]
Orchard. Not Orchard Core.

Orchard Core : https://docs.orchardcore.net/en/latest/
