### ISSUE TITLE
GrapeJS or VVVwebJs - HTML Frontent builder integration  / speed up development

### ISSUE THREAD

**Issue by fasteddys** [OrchardCMS/OrchardCore#10930]
Hello, can you please consider / at lease show people how to use a frontend builder for the pages

https://github.com/artf/grapesjs

https://github.com/givanz/VvvebJs

![image](https://user-images.githubusercontent.com/96149622/147601470-f594f274-29f4-41ae-9669-86b837fcf40a.png)

**Comment by hishamco** [comment]
Duplicate for #962
