### ISSUE TITLE
Content and Entity picker fields

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1094]
OrchardCore will need a Content picker field as in O1. #352

I am also wondering: How could I be able to associate User(s) to a content?
Would it be possible to have some kind of EntityPickerField in which you can specify the entity type that you will be able to select?

**Comment by sebastienros** [comment]
User Picker Field. Different than Content Picker Field. Also important to have different fields as they will have distinct UIs. And there is no common contract to request an entity.

**Comment by li0803** [comment]
Thanks for the answer.
Now, is there a branch for this? I have a quick look at ag/enumerationfield and fields branches. But they have not updated for a long time. If there is a branch for this. May be I can provide same help. Or I have to wait for the RC

**Comment by xperiandri** [comment]
Any updates?

**Comment by sebastienros** [comment]
No updates, but very important

**Comment by ArashSade** [comment]
Yesterday I had a conversation about this with @sebastienros on the gitter. Perhaps useful to add the conversation to this issue.
It went like this:

![image](https://user-images.githubusercontent.com/14197890/44450884-65991500-a5f2-11e8-8f2e-7640310d4a23.png)

At the end I made a bold statement, but I take that back. I know little about the internal workings of ContentPicker and OrchardCore to be able to give an opinion.

Perhaps good to know that in Dynamics 365, when you create a connection entity record, two records are created in the database. The first record represents a source to target connection and the second record represents a target to source connection. This guarantees that a query will find all connections that the record participates in, regardless whether the record is a source record or a target record in the connection.

In connection entity, you have two end of a relationship. These two endings have their own name and that is why you can approach the entities from both sides in the right way. Suppose you have a Parent-Child relationship between two entities.
You define that 'X' is parent of 'Y' and you also define that 'Y' is child of 'X'. In contrast to many other systems that only create a single record with a 'source' and 'target' and a two-part name with a dash in between for the relation. Depending on the situation you have to know on which side you are, if you are now on the 'target' side, then you should know that you are on the 'child' side. If you are on the 'source' side, then you should know that you are on the 'Parent' side. In other words, the left is 'source' and the right is 'target' within a relationship. With my little knowledge about the O1 ContentPicker, I think it creates a record for a relationship and works in this way.

In our own CRM (no CMS used), we tried to apply Dynamics 365 Connections idea. In this way we wanted to have the possibility to add a relationship between different existing entities. For example, to indicate that there was a 'Referral relation' (Referral-ReferredBy) or a 'Hierarchy' (Account-SubAccount) between the entities.

But unfortunately we have run into various problems and have stopped. Most problems had to do with existing data structure and entities.
We also could not find a good way to deal with changing the connections. For example, we could not properly move a "sub-account" to another parent account or define a "sub-account" as the parent for another entities. (multi-level relationship)

At the end we opted for the simple known and reliable way of making a relationship. The only way that always worked and that was ForeignKey relationship in the SQL database. Yes, it is not the same, it is static and a pain to implement, but adding, changing, removing, indexing, quering and especially the relational integrity between the entities is supported by the RDBMS and a well known concept for the developers.
It is certainly not the same as a Connections entity and certainly does not offer the same possibilities. But we can live with it.

I hope this long story can contribute to the eventual implementation of this functionality within the OrchardCore.

**Comment by sebastienros** [comment]
Note to myself: Index the relationship to be able to query it both ways.
