### ISSUE TITLE
Add select/deselect all option to the ContentPickerField and UserPickerField

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#10942]
### Is your feature request related to a problem? Please describe.
Sometimes, the user need to select all items in the menu "10+". Currently, it requires the user to click and select 10+ times to select all options. very tedious and not friendly use case.

### Describe the solution you'd like
I think the standard `ContentPickerField` and `UserPickerField` are great. But I a button to allow the user to select and select all can be very handy in many cases. 
Also, it would be nice to be able to manually set the selected option. For example, if I want my page to manually set the selected values using Javascript. I should be able to set the selected values using the JavaScript after the page is loaded manually using JS.

### Describe alternatives you've considered
Nothing yet

**Comment by hishamco** [comment]
Do we really not have this? I think it is good to add this option

**Comment by CrestApps** [comment]
Another thing would be nice from the user experience is to also add a check mark on the right side of the selected items on the menu itself. This would tell the user if an option is already selected when the menu is open. Like if the user want to select 5 options, then close the menu and open it again, it's nice to indicate which 5 he/she already selected.

**Comment by deanmarcussen** [comment]
This would be misleading to a user.

the pickers return 50 by default and more when searching. So select all, couldn’t actually mean all, always, as it depends on the number of items returned, and visible 

suggest you implement your own editor mode, if you want this.

Check mark to indicate already selected seems like a good idea for improvement.

**Comment by sebastienros** [comment]
Too risky, you could add a reference to so many items ...
