### ISSUE TITLE
Suggestion: Change BagPart name

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1095]
The BagPart is a nice way to add sub-contents to a Content item and add, edit and organize them from the edition page of the content that contains them.

Combined with the ability to specify the template of a Content type in Liquid syntax from the admin, this is definitely an interesting feature (See agency theme's one page for example).

However, I think the name '`Bag`' isn't really self-explanatory. 

May be something like '`SubItems`' or '`Nested`' could be better.

If anyone has a suggestion for a more easily understandable name, please share your thoughts.

**Comment by giannik** [comment]
SubContent?

**Comment by sebastienros** [comment]
`Nested`
`Embedded`
`Attachments`, though this is more how you should name the part instance in some cases.

I used `Bag` to balance with `List`, as in programming languages. Could be `Set` also.

**Comment by sfmskywalker** [comment]
What about `Collection`?

**Comment by sebastienros** [comment]
@DaRosenberg suggests `LocalList`

**Comment by Jetski5822** [comment]
I would like to keep it as BagPart

**Comment by sebastienros** [comment]
Just to add that we are not using `ContainerPart` so far so it's possibility

**Comment by JoshTango** [comment]
I like the name Collection

**Comment by sebastienros** [comment]
We could add a new Part named Collection and migrate to it so it doesn't break the existing sites. Maybe create a new module, or move Bag in a Deprecated module.

**Comment by agriffard** [comment]
If we don't decide to change the name before 1.0 RTM, it is gonna be very difficult to change it after.
I also like `ContainerPart`.

**Comment by JoshTango** [comment]
Can you add fields in this or only content parts?

**Comment by jptissot** [comment]
@JoshTango Bag allows you to add a list of ContentItems (instances of ContentTypes) so you can use Parts and fields in each "child" type

**Comment by JoshTango** [comment]
Well then how bout ContentTypeCollection?

**Comment by sebastienros** [comment]
We should go with ContainerPart, but we need migration path, and document the template changes.
We already handled migration when we moved BodyPart to HtmlBodyPart, so we could just copy the same code for the migration. Data + content definition.

The name collection should be used for Lists. There is another issue talking about this.
