### ISSUE TITLE
Trying to step into OC code - missing PDBs?

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#10959]
OC version 1.1.0

### Describe the bug
I'm trying to step into OC code and struggling to get it to work.

### To Reproduce
In Visual Studio 2022 I turned off "just my code", enabled Source Link support, and load all symbols from NuGet.org.
![image](https://user-images.githubusercontent.com/68876423/148089330-8893f38b-d53a-4586-9b2b-005bf8aa895c.png)
![image](https://user-images.githubusercontent.com/68876423/148089384-1bac8b9f-fb1c-46d2-9d83-d837c7e31239.png)

I tried the following four breakpoints, and only one of them works.

1. OrchardCore.Users.Services.UserService.GetAuthenticatedUserAsync
2. OrchardCore.Admin.AdminAttribute.IsApplied
3. OrchardCore.Contents.Controllers.ItemController.Display
4. OrchardCore.DisplayManagement.Notify.NotifyFilter.OnActionExecuted

Of these four, only number 2 worked. The Source Link dialog popped up and asked me if I wanted to download the code. The other three display a page similar to this.
![image](https://user-images.githubusercontent.com/68876423/148089853-919074b6-bd64-4672-9140-4fae321ba9d9.png)

**Comment by Skrypt** [comment]
Which version of Visual Studio and MSBuild you have installed?

**Comment by rjpowers10** [comment]
> Which version of Visual Studio and MSBuild you have installed?

- Visual Studio 17.0.4
- MSBuild 17.0.0.52104

**Comment by Skrypt** [comment]
Ok, I know that some pdb's have been recently. Maybe this works only better with the "main" branch which are the "preview" nuget packages.

**Comment by ns8482e** [comment]
@rjpowers10 some package has PDB and some has missing - for 1.1 - due to network issue when 1.1 deployed. See @sebastienros comment https://github.com/OrchardCMS/OrchardCore/issues/9990#issuecomment-948795286

Hopefully it will be resolved in 1.2

**Comment by ns8482e** [comment]
You can remove desc from base part ( i.e. BagPart) using migration from any module that has dependency on "Flow" with following code

```cs
 _contentDefinitionManager.AlterPartDefinition("BagPart", builder => builder
                .WithDescription(""));
```

**Comment by ns8482e** [comment]
@rjpowers10  1.2 released - I hope it will work with symbols now.

**Comment by sebastienros** [comment]
There were no network failure so it should all be good.
There is an issue in the NuGet repos that explains how it's impossible to just re-push missing symbols, because it can't skip existing ones and fail the dotnet push step.

**Comment by rjpowers10** [comment]
I've updated to OC 1.2. Recall that my test breakpoints are

1. OrchardCore.Users.Services.UserService.GetAuthenticatedUserAsync
2. OrchardCore.Admin.AdminAttribute.IsApplied
3. OrchardCore.Contents.Controllers.ItemController.Display
4. OrchardCore.DisplayManagement.Notify.NotifyFilter.OnActionExecuted

1, 2, and 4 worked as expected. I hit the breakpoint for 3, but still nothing:
![image](https://user-images.githubusercontent.com/68876423/148606452-8c767ea5-a032-4be5-8ed6-3027c147948c.png)

**Comment by Skrypt** [comment]
I just tried with OrchardCore.Contents.Permissions and it works on my side. So, there is definitely a source link happening.

I tried with 1.3.0-preview-16650 which is quite close to 1.2.

**Comment by rjpowers10** [comment]
> I just tried with OrchardCore.Contents.Permissions and it works on my side. So, there is definitely a source link happening.
> 
> I tried with 1.3.0-preview-16650 which is quite close to 1.2.

I tried another test and I was prompted to download OrchardCore.Contents.Permissions. But strangely I still am never prompted to download OrchardCore.Contents.Controllers.ItemController.

**Comment by Skrypt** [comment]
Did you override it inside your own module?

**Comment by rjpowers10** [comment]
> Did you override it inside your own module?

I may have at one time just to have a simple way of debugging it, but it is not currently overridden.

**Comment by Skrypt** [comment]
At this point, I'm not sure. I need to repro the exact same code that you have where you are trying to resolve the controller.
Can you show me a code example of what you are actually doing?

**Comment by rjpowers10** [comment]
> At this point, I'm not sure. I need to repro the exact same code that you have where you are trying to resolve the controller. Can you show me a code example of what you are actually doing with the controller in your custom code?

I'm not doing anything in my code. I'm just trying to view the detail of a content item. Like I said, I can hit the OrchardCore.Contents.Controllers.ItemController.Display breakpoint, VS just can't find the code when it does.

If you can't figure it out then maybe it's something on my end. Thanks for trying.

**Comment by sebastienros** [comment]
I have the same issue with 1.2 and VS 2022, but only the controller didn't work. It might be because the action is invoked using reflection and the debugger can't intercept it. I can step in the thing that calls the action through reflection, and it stops the debugger also, but it can't get the code. The PDB is correctly downloaded in the symbols cache folder.

**Comment by sebastienros** [comment]
And same issue for other controllers, so the reflection based invocation might be the issue (note it's an ASP.NET MVC thing)
