### ISSUE TITLE
Blog Body placement in Theme

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1097]
I specified a Zone in my custom theme, in the Layout.cshtml :
`@await RenderSectionAsync("BeforeContent", required: false)`

I want to change the placement of the title of any content type and the description of a Blog, stored in a BodyPart so I added a placement.json:

```
{
  "TitlePart": [
    {
      "display-type": "Detail",
      "place": "/BeforeContent"
    }
  ],
  "BodyPart": [
    {
      "display-type": "Detail",
      "differentiator": "Blog",
      "place": "/BeforeContent"
    }
  ]
}
```

but I don't manage to find the good property to set in order to only move the Body of a Blog in this zone. 

What is the equivalent `<Match ContentType="Blog">...` in O1?
Is it `differenciator` and what do I have to put inside?

**Comment by sebastienros** [comment]
I don't think we support it yet. The code is commented out waiting to find a solution.

**Comment by sebastienros** [comment]
Implement a custom service that placement (in displaymanagement) will invoke to delegate custom filters. I think it was done by Carl a month ago in O1.

**Comment by agriffard** [comment]
A template could also be used.
```
{% zone "BeforeContent" %}
...
{% endzone %}
```
