### ISSUE TITLE
Adding Widget with 'Render Title' unchecked causes an error

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1098]
When I add a RawHtml widget in a zone from the Layers admin page, if I don't check 'Render the title', then when I reload a front page loading this widget, there is an error :
`Cannot convert null to 'bool' because it is a non-nullable value type`

If I re-edit the widget and check it and publish, then go back re-uncheck and publish again, the error won't occur anymore.

So the first save must store a `Null` value for the property.

**Comment by jtkech** [comment]
I did better, i was not able to add a widget from the layers page. Layer metadata were not updated.

But i found a fix and then i also found a fix for the render title issue. Not sure it is the better way but i will do a PR tomorrow to be reviewed.

**Comment by agriffard** [comment]
Currently, adding a widget doesn't work anymore at all.
