### ISSUE TITLE
Current widgets / Types do Not support Metrics / Graphs

### ISSUE THREAD

**Issue by fasteddys** [OrchardCMS/OrchardCore#10995]
### Which component Strategy for new developers & Students to build metrics based components

There's some confusion in the Developers & students community. they do not know, **which path to take to build transactional components/functionality**, for e.g. if a developer wants to create a component with a` master-details table` for customer shipping/orders tables Or, **GRAPH** for e.g. Number of `returns per product D3 / eCharts Graph`, and a table below with details on selected row-item in the graph... which one / do they use a module, do they use a widget, or content type its very fuzzy on which one to pick??

Next, if a developer wants to scaffold Orchard Form, or custom Widgets , module, for e.g. in the last .net dev meetup many mentioned, they don't know how to create a simple pie chart in orchard for e.g. there are several use cases like a customer returns per product.

I posted a help request in the Lombiq CVS2022 extension, and proposed using Extension, they gave up after trying, first because of the compatibility issue, which is being fixed, but also some functionality issue. So, if it has more comments/picture on what the code structure/components its scaffolding, step 1, 2 etc. in comments form then developers would be able to use it to easily create Module or Widget.

They key thing to understand is the flexibility in your scaffolding / visual extension is perhaps a good entry point as a visual tool in VS to help them create the components they want.

If you notice in the admin dashboard there is no single graph there?

Can you create a core component, with a graph and table to show number of failed attempts, IP aaddress (kinda like WordFence or loginizer in WP), this would be a good reference app.

**Comment by sebastienros** [comment]
> for e.g. in the last .net dev meetup many mentioned

Source?

> Can you create a core component, with a graph and table to show number of failed attempts...

Yes you can

**Comment by Skrypt** [comment]
It's been triaged for documentation. Keeping it open.

**Comment by Skrypt** [comment]
Here is a SQL diagram that shows a many-to-many relationship.

![tables-relations3](https://user-images.githubusercontent.com/3228637/152274816-1f296161-a2aa-4bbd-a2bb-cf5dec3754eb.png)

If we start from a Migrations.cs file in a module to create these tables we can do something like this : 

```C#
using System;
using OrchardCore.ContentManagement.Metadata;
using OrchardCore.ContentManagement.Metadata.Settings;
using OrchardCore.Data.Migration;
using YesSql.Sql;

namespace YourNamespace
{
    public class Migrations : DataMigration
    {
        public int Create()
        {
           // We create the 3 tables first
           SchemaBuilder.CreateTable(nameof(Employee), table => table
                .Column<int>(nameof(Employee.EmployeeID), col => col.PrimaryKey().Identity())
                .Column<string>(nameof(IndexingTask.FirstName), c => c.WithLength(50))
                .Column<string>(nameof(IndexingTask.LastName), col => c.WithLength(50))
            );

           // This is the "middle" table that stores the many to many references
           SchemaBuilder.CreateTable(nameof(EmployeeSkill), table => table
                .Column<int>(nameof(Employee.EmployeeID))
                .Column<int>(nameof(SkillDescription.SkillID))
            );

           SchemaBuilder.CreateTable(nameof(SkillDescription), table => table
                .Column<int>(nameof(SkillDescription.SkillID), col => col.PrimaryKey().Identity())
                .Column<string>(nameof(SkillDescription.Description), c => c.WithLength(30))
            );
            
            // We create the foreign keys that will create the many to many relationship
            SchemaBuilder.CreateForeignKey(
                     "fk_" + nameof(Employee) + "_" + nameof(SkillDescription), // foreign key name
                     nameof(Employee),  // source table name
                     new string [] { "EmployeeId" },  // source table columns to include in the FK
                     nameof(EmployeeSkill),  // destination table name
                     new string [] { "EmployeeId" }  // destination table name columns to include in the FK
            );

            SchemaBuilder.CreateForeignKey(
                     "fk_" + nameof(EmployeeSkill) + "_" + nameof(SkillDescription), // foreign key name
                     nameof(EmployeeSkill),  // source table name
                     new string [] { "SkillID" },  // source table columns to include in the FK
                     nameof(SkillDescription),  // destination table name
                     new string [] { "SkillID" }  // destination table name columns to include in the FK
            );

            return 1;
        }
    }
}
```

Consider this as a draft as I didn't try this code yet.

**Comment by Skrypt** [comment]
I'm thinking that I'm maybe making a mistake there where I could use SchemaBuilder.CreateMapIndexTable for the EmployeeSkill and SkillDescription tables.

**Comment by Skrypt** [comment]
Documentation it is ...

**Comment by fasteddys** [comment]
@Skrypt thanks for the guidance here... exactly what we were looking for... first its not always admins looking at dashboards. If you look at Kendo/SiteCore/ABP etc. they have `business user facing dashboards` in the apps. This is a very common scenario besides `dataTables`  or `Master-Detail Forms` to view LOB transactional data.

_"...I believe that Widgets shapes can be added from the Admin UI by using the "Templates" feature. Though, when it comes to consume a javascript library I generally build an entire module that builds these Widgets. Else, it is also totally doable from the admin UI if you don't need to create handlers and drivers for your custom shapes..."_ (Awesome advice) 👍 

I also see how your migration builder is adding the schema (similar to EF), which has helped us. 👍 

**Use case**
Since we already had another app with dashboards and charts, where we already had a simple `ViewComponent `(previously Partials) tried to easily convert/port over that code and failed.. because of the internals on how to wire it up.

Scaffolder:
We tried to scaffold a new module and port over the code - we were unable to follow how to achieve this even from the documentation (I have not see the latest), but if it could have some pictures describing the layers/shapes imagine a lasagna or a stack to visually depict what goes where and the sequence of steps or even a sample that would help.

**Comment by Skrypt** [comment]
I think I would start by analyzing the OrchardCore.Demo module

https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore.Modules/OrchardCore.Demo

And then I think you need to learn the differences between "Content Type", "Content Part", "Content Field",
Shapes, Drivers, Handlers.

Here, a driver is something similar to a controller but for a shape. And a shape is kind of a dynamic ViewModel. You need to think about the fact that Orchard Core uses composition to create its runtime data models and there is some dynamic typing involved because of that. So, we don't use standard controllers for these because of the dynamic nature of shapes.

I think you need to take a simple module like the OrchardCore.Demo one and try different things. Look at other modules to see how things are done when needing more advanced things. That's the best way to learn. Else, there is the documentation for really specific things but maybe we are missing simple tutorials.

There is also this repository : 

https://github.com/OrchardCMS/OrchardCore.Samples

But I think it needs an update.

**Comment by hishamco** [comment]
In terms of graphs and chart I think Lombiq already did a module for Chart Js. @Piedone correct me if I'm wrong

**Comment by Piedone** [comment]
Yes, [the Chart.js module](https://github.com/Lombiq/Orchard-Chart.js). Thanks for pointing out Hisham.

**Comment by fasteddys** [comment]
@Piedone I was able to download an build and see the chart component very helpful 👍 missing some steps on making it functional in a module for us.

Usecase: The user selected the widget and _wants to connect materials or shift dataset to it_, can you please share some info on how are the backend DataSources/Tables exposed/discovered to the widget and how does the Module know about the widget?

### Use case sample: For e.g. we have a small manufacturing/recycling warehouse sample.
__________

For e.g. we have several Tables, and taking these two for e.q:

MaterialsTable
`[id, vendor, materialtype (metal/plastic/glass), WeightDropOff, MeltingCompleted, ShiftHours, TotalHours ]`

ShiftsTable
`[id, ShiftType, DateTimeStarted,DateTimeCompleted, WeightCompleted, NumberOfWorkers, TotalCost  ]`

ChartView... Manager wants to view in the graph widget

- _How much was completed per shift_
- _How much was labor cost per shift_

We can render the graph, and we see your datasets definition, but do we configure this so user can pick each of those to view.

Please confirm we are doing right steps:

We made a widget and a module but dont know what to do to connect the two.

`codegen module Manfacturing /IncludeInSolution:true`


________________
From your `ChartJsDataSet` base class we created new dataSets

    public class MaterialsTableDataSet : ChartJsDataSet
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<string> materialtype { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<decimal> TotalHours { get; set; }
        //... other props
    }


    public class ShiftsTableDataSet : ChartJsDataSet
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<string> ShiftType { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<decimal> TotalCost  { get; set; }
        //... other props
    }

______________________

**Comment by DAud-IcI** [comment]
Hi @fasteddys ,

The Chart.JS module is focused on the front-end side of things. You have to access data from the DB separately. It sounds like you already have a DB with this data to be displayed, so doing a database-first setup with Entity Framework Core might be the most appropriate.

You shouldn't inherit from `ChartJsDataSet`. If you haven't yet, create a separate model you use to get data from your DB table. Then create a view-model for your widget that contains these properties:
```csharp
    public IEnumerable<string>> ChartLabels { get; set; }
    public IEnumerable<ChartJsDataSet> ChartDataSets { get; set; }
    public object ChartOptions { get; set; }
```
Your widget's driver should fetch the DB rows, convert them into data series according to your business logic and then initialize the viewmodel that contains the above properties like this:
```csharp
    // Fetch from DB, convert as needed. If you need his to be user customizable, attach that information to
    // your widget's content item so it can be accessed by your logic here.
    var shifts = ...;

    model.ChartLabels = shifts.Select(shift => shift.DateTimeStarted.ToString());
    model.ChartDataSets = new List<ChartJsDataSet>
    {
        new()
        {
            Label = "Total Cost",
            Data = shifts.Select(shift => shift.TotalCost),
        },
    };
    // Options can be PascalCase, but otherwise same as https://www.chartjs.org/docs/2.9.4/configuration/#global-configuration
    model.ChartOptions = new
    {
        Layout = new Layout(50, 10, 10, 10),
    };
```
Finally include in your widget's template:
```razor
        <chart labels="@viewModel.ChartLabels"
               datasets="@viewModel.ChartDataSets"
               options="@viewModel.ChartOptions"></chart>
```

**Comment by fasteddys** [comment]
Much love 😄  to your help @DAud-IcI thanks to your help the mud is clearing up some.

Samples: _don't show drivers_
When I study/follow/tried to search for driver inside the chart Widget sample and module sample both were empty 
          https://github.com/Lombiq/Orchard-Chart.js/search?q=driver 
          https://github.com/OrchardCMS/OrchardCore.Samples/search?q=driver

__________________

So, from your help, I understand this I should code it up like a regular MVC app, and let user switch between datasets in frontend, and in view switch in JS code, I am assuming when I pass more than one in the model, the driver will make it available to the chartJSWidget

    model.ChartDataSets = new List<ChartJsDataSet>
    {
        new()
        {
            Label = "Total Cost",
            Data = shifts.Select(shift => shift.TotalCost),
        },
    };

    // I added these and planning to let user select and should I change it in the frontend, like a regular MVC view?
    model.MaterialsDataSets = new List<ChartJsMaterialsDataSet>
    {
        new()
        {
            Label = "Total Time",
            Data = Materials.Select(materials=> materials.TotalHours),
        },
    };

________________

**Documentation help section**: is confusing it shows _drivers inside modules_, but the _ChartJs is a UI widget_??  so are they the same thing, how do they get linked/wired up?? I added a suggestion below...

I was trying to follow [this Orchard help](https://docs.orchardcore.net/projects/O1/en/latest/Documentation/Getting-Started-with-Modules-Part-2/) so I could build the driver for the widget 

<img width="630" alt="image" src="https://user-images.githubusercontent.com/96149622/153998021-a2b32467-5fb0-4209-a6cc-bab74702d941.png">

Please correct me

-  So I assumed a Widget is _just another independent module/project packaging on how code is organized_? I understand Widget are a UI item, but not modules. Also, I am trying to figure out a) how to package our code so its not impacted by version changes etc. b) how to organize our code base and features

Maybe the clue is the content part behind a widget, yes?? `public class MyChartDriver : ContentPartDriver<MyChartWidget>` ?

_____________

### Humble Suggestion
While, they have a good effort and nice amount of documentation, a picture to show the architecture & composition _would really help clear up the relationships/inheritance/structure_ and `MODULE  `<-> `Widget `composition/aggregates.

For e.g. a layered or relationship image on how to build up to the widget from a module!
![image](https://user-images.githubusercontent.com/96149622/153998886-dfb086e4-e977-44a9-804c-d0a0b5607fea.png)

**Comment by DAud-IcI** [comment]
> Samples: don't show drivers

Yes, my sample only included the Chart specific parts to keep it simple. 
Drivers are kind of like controllers for content items, and a widget is just a specialized content item. Check out the "Content Item and Content Part development" section of [our training demo](https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/dev/StartLearningHere.md) (or specifically the driver [here](https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/dev/Drivers/PersonPartDisplayDriver.cs)) if you've never worked with them before. 

> Documentation help section:

Disregard that documentation, it's for the legacy "Orchard CMS" (also known as O1). It's an older CMS made for .Net Framework and many concepts don't translate to Orchard Core so it will only get confusing.

> So I assumed a Widget is just another independent module/project packaging on how code is organized?

A widget is a content type with a special stereotype value. They can be placed on the layout independently of the current page's content (in Admin Dashboard > Design > Widgets). A module can contain multiple widgets, but you have to define them like any other content type (see the training demo linked above).
![image](https://user-images.githubusercontent.com/4007293/154004051-ed642bca-eeba-452f-b0b5-14f30452a10a.png)

> Humble Suggestion

I've tried, but I'm not graphic designer.
![oc](https://user-images.githubusercontent.com/4007293/154008184-93a43114-ee8d-4876-8ba9-bd6987a09ac4.png)

**Comment by fasteddys** [comment]
Thanks
