### ISSUE TITLE
Error in Setup NullRef exception

### ISSUE THREAD

**Issue by SperoSophia** [OrchardCMS/OrchardCore#1099]
As of (fc23bfc) setup fails, this has been tested azure sql db, local sqlexpress and sqlite.

`NullReferenceException: Object reference not set to an instance of an object.
YesSql.Data.WorkerQueryKey.GetHashCode()
System.Collections.Generic.GenericEqualityComparer.GetHashCode(T obj)
YesSql.Store+<ProduceAsync>d__30.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
YesSql.Services.DefaultQuery+Query+<FirstOrDefaultImpl>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
OrchardCore.ContentManagement.DefaultContentManager+<GetVersionAsync>d__17.MoveNext() in DefaultContentManager.cs` ...

**Comment by agriffard** [comment]
I also had this error after a setup today.

**Comment by agriffard** [comment]
Setup is not working anymore since the last YesSql change : b14174c8532a40985b616dbf16116019cd349f36 even for sqLite but only for recipes with a Content Step like theAgency or theBlog.

**Comment by sebastienros** [comment]
Fixed
