### ISSUE TITLE
Audit Filter 

### ISSUE THREAD

**Issue by fasteddys** [OrchardCMS/OrchardCore#10994]
### Security  `Audit`
Security is paramount, and it would be nice to have some protection agains phisinf and locked out users or DDOS etc.

### Viewable / notification on Audits
Having a plugin module to `View `Audits in the admin section, or even making it part of core.

How can I implement something like into the core, and make it viewable as a view?

```
namespace DemoAudit.Filters
{
    public class AuditFilterAttribute : ActionFilterAttribute
    {
        private readonly IAuditRepository _auditRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public AuditFilterAttribute(IHttpContextAccessor httpContextAccessor, IAuditRepository auditRepository)
        {
            _httpContextAccessor = httpContextAccessor;
            _auditRepository = auditRepository;
        }
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var objaudit = new AuditModel(); // Getting Action Name 
            var controllerName = ((ControllerBase)filterContext.Controller)
                .ControllerContext.ActionDescriptor.ControllerName;
            var actionName = ((ControllerBase)filterContext.Controller)
                .ControllerContext.ActionDescriptor.ActionName;
            var actionDescriptorRouteValues = ((ControllerBase)filterContext.Controller)
                .ControllerContext.ActionDescriptor.RouteValues;

            if (actionDescriptorRouteValues.ContainsKey("area"))
            {
                var area = actionDescriptorRouteValues["area"];
                if (area != null)
                {
                    objaudit.Area = Convert.ToString(area);
                }
            }

            var request = filterContext.HttpContext.Request;

            if (!string.IsNullOrEmpty(Convert.ToString(filterContext.HttpContext.Session.GetInt32(AllSessionKeys.LangId))))
            {
                objaudit.LangId = Convert.ToString(filterContext.HttpContext.Session.GetInt32(AllSessionKeys.LangId));
            }
            else
            {
                objaudit.LangId = "";
            }

            if (!string.IsNullOrEmpty(Convert.ToString(filterContext.HttpContext.Session.GetInt32(AllSessionKeys.UserId))))
            {
                objaudit.UserId = Convert.ToString(filterContext.HttpContext.Session.GetInt32(AllSessionKeys.UserId));
            }
            else
            {
                objaudit.UserId = "";
            }

            if (!string.IsNullOrEmpty(Convert.ToString(filterContext.HttpContext.Session.GetInt32(AllSessionKeys.RoleId))))
            {
                objaudit.RoleId = Convert.ToString(filterContext.HttpContext.Session.GetInt32(AllSessionKeys.RoleId));
            }
            else
            {
                objaudit.RoleId = "";
            }


            if (!string.IsNullOrEmpty(Convert.ToString(filterContext.HttpContext.Session.GetString(AllSessionKeys.IsFirstLogin))))
            {
                objaudit.IsFirstLogin = Convert.ToString(filterContext.HttpContext.Session.GetString(AllSessionKeys.IsFirstLogin));
            }
            else
            {
                objaudit.IsFirstLogin = "";
            }

            objaudit.SessionId = filterContext.HttpContext.Session.Id; ; // Application SessionID // User IPAddress 
            if (_httpContextAccessor.HttpContext != null)
                objaudit.IpAddress = Convert.ToString(_httpContextAccessor.HttpContext.Connection.RemoteIpAddress);

            objaudit.PageAccessed = Convert.ToString(filterContext.HttpContext.Request.Path); // URL User Requested 

            objaudit.LoginStatus = "A";
            objaudit.ControllerName = controllerName; // ControllerName 
            objaudit.ActionName = actionName;

            RequestHeaders header = request.GetTypedHeaders();
            Uri uriReferer = header.Referer;

            if (uriReferer != null)
            {
                objaudit.UrlReferrer = header.Referer.AbsoluteUri;
            }

            _auditRepository.InsertAuditLogs(objaudit);
        }
    }
}
```

**Comment by Piedone** [comment]
There's an Audit Trail module in Orchard, see these videos:

- https://www.youtube.com/watch?v=uMBN6TVhaMg
- https://www.youtube.com/watch?v=ko0jEgQtXYc
- https://www.youtube.com/watch?v=t28rnjYtlJc

Isn't this what you're looking for?

**Comment by fasteddys** [comment]
Hello @Piedone thanks, yes. But if you look in WordFence or Security Loginizer you will see a few more details and actions.

For e.g. `auto ban, for more that 3 login attempts to root etc.`

Vulnerability view
![image](https://user-images.githubusercontent.com/96149622/148703983-fc3f81f8-7921-42e6-9fbc-5f9b392971e4.png)

![image](https://user-images.githubusercontent.com/96149622/148704072-5193fcd1-47a6-431e-9acd-53f56268dad4.png)

![image](https://user-images.githubusercontent.com/96149622/148704081-4776f641-d66e-4627-ad8c-88cc97e5bd9b.png)


![image](https://user-images.githubusercontent.com/96149622/148704010-bedabdfa-377c-4cf0-9dad-ac05e8a53399.png)

![image](https://user-images.githubusercontent.com/96149622/148704048-159d949e-ef4c-4db6-a6b8-2142f2f85e94.png)

**Comment by Piedone** [comment]
There seems to be multiple independent things conflated for me:

- Something related to security scanning and detecting if an extension (module or theme) has a known vulnerability. However, I'm not sure about your intentions, please elaborate.
- Additional security/WAF features added to Orchard. While I think these are outside the responsibility of Orchard (or any CMS) and should be handled by a dedicated WAF/reverse proxy, please elaborate which features, specifically, you'd like to see.
- Extending the Audit Trail with new events: Please open separate feature requests for each event that you'd like to see. E.g. "Enabled/disabled theme".

Ideally, an issue should be about a single item. If my above understanding of the three items is correct, then please open separate feature requests **using the provided template** for each of them (and one for each Audit Trail event), and close this one.

**Comment by fasteddys** [comment]
Sorry about that, coming from WP or Drupal/Joomla world, they are usually bundled in one plug-in as you can see in the screenshots above.

I will close it out.
