### ISSUE TITLE
Disabling theme results in InvalidOperationException

### ISSUE THREAD

**Issue by jorismathijssen** [OrchardCMS/OrchardCore#11006]
I'm running the CMS in dark mode and wanted to turn off the theme feature. After disabling themes the whole CMS wont load and returns a HTTP 500.

The exception in the backend is
`No service for type 'OrchardCore.Themes.Services.DarkModeService' has been registered.`

The following stacktrace is thrown:
https://gist.github.com/jorismathijssen/451d369bbed491576e6f6d7b9eba7aae

**Comment by Skrypt** [comment]
So when you say that you turned off the theme feature that might be the reason why you get this issue because you then need to update the templates to not inject this DarkModeService simply.

Else, keep the theme feature enabled ... none issue to me.

**Comment by jorismathijssen** [comment]
@Skrypt that actually looks like a good solution. I can add service to my custom startup.cs

I thought it would be helpful to report this. I did not want people to change the theme, so turning of the feature sounded like a good idea to me. I did not expect to break my admin dashboard with it.

Your suggestions will help me. If you think that it is a none issue, this can be closed
