### ISSUE TITLE
Liquid if and unless variable starting with 'empty' creates exception

### ISSUE THREAD

**Issue by PBMikeW** [OrchardCMS/OrchardCore#11012]
Liquid if variable starting with 'empty' creates exception

```liquid
{% if emptyCard %}
<p>Creates Invalid 'if' tag exception in 1.2, worked fine in 1.1</p>
{% endif %}

{% if cardEmpty %}
<p>Works fine</p>
{% endif %}
```

**Comment by Skrypt** [comment]
/cc @sebastienros 

Not sure if this is an issue. Did `emptyCard` get assigned anything?
And here what is the difference with `cardEmpty`? We don't see it getting assigned any value either.
