### ISSUE TITLE
Media indexing doesn't work when using Azure Storage

### ISSUE THREAD

**Issue by pedronave** [OrchardCMS/OrchardCore#11014]
### Describe the bug

I've been testing the new Media Indexing feature introduced in #9544 and ran into an issue when using Azure Storage.
Using local media storage, everything indexes fine. When I set up the use of Azure Media Storage, the indexing stops working.

This happens because the file stream provided to PdfPig [doesn't support seeking](https://github.com/UglyToad/PdfPig/blob/c74ca5fda8a51f3af9cf19c675272f57d3beee60/src/UglyToad.PdfPig.Core/StreamInputBytes.cs#L45) (see the stack trace below).
I'm guessing it's because the stream returned by [BlobFileStore's `GetFileStreamAsync`](https://github.com/OrchardCMS/OrchardCore/blob/b0cc503f2d6bdd9c287b0717020c25e23a175951/src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs#L340) doesn't support seeking, but I'm not sure if there is a workaround for it.

```
[
  {
    "severityLevel": "Error",
    "outerId": "0",
    "message": "The provided stream did not support seeking.",
    "type": "System.ArgumentException",
    "id": "11983995",
    "parsedStack": [
      {
        "assembly": "UglyToad.PdfPig.Core, Version=0.1.5.0, Culture=neutral, PublicKeyToken=605d367334e74123",
        "method": "UglyToad.PdfPig.Core.StreamInputBytes..ctor",
        "level": 0,
        "line": 0
      },
      {
        "assembly": "OrchardCore.Media, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "OrchardCore.Media.Indexing.PdfMediaFileTextProvider.GetText",
        "level": 1,
        "line": 0
      },
      {
        "assembly": "OrchardCore.Media, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "OrchardCore.Media.Indexing.MediaFieldIndexHandler+<BuildIndexAsync>d__6.MoveNext",
        "level": 2,
        "line": 0
      },
      {
        "assembly": "System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
        "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
        "level": 3,
        "line": 0
      },
      {
        "assembly": "System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
        "method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
        "level": 4,
        "line": 0
      },
      {
        "assembly": "OrchardCore.Abstractions, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "OrchardCore.Modules.InvokeExtensions+<InvokeAsync>d__10`6.MoveNext",
        "level": 5,
        "line": 0
      }
    ]
  }
]
```

### To Reproduce
1. Setup Azure Media Storage
2. Create a Content Type and configure media indexing according to the documentation
3. Create a Content Item of the above type and upload and add a PDF document to the Content Item
4. If the index is checked, the PDF content will not be indexed

### Expected behavior
The PDF content should be indexed as it is with local media storage.

**Comment by mariojsnunes** [comment]
cc/ @Piedone

**Comment by Piedone** [comment]
I'm looking into it.

**Comment by Piedone** [comment]
Gotta love lying interfaces... Thanks for the detailed bug report and looking into PdfPig as well. Could you try out the linked PR @pedronave please?

**Comment by pedronave** [comment]
Hey @Piedone, just gave it a try and it seems to be working now!

**Comment by Piedone** [comment]
Great, thanks!
