### ISSUE TITLE
unable to find metadata of orchardcore.rules.1.2.1

### ISSUE THREAD

**Issue by six006** [OrchardCMS/OrchardCore#11032]
when install package with nuget ,I got a error `unable to find metadata of orchardcore.rules.1.2.1`
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>demo_cms</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.2.1" />
  </ItemGroup>
</Project>


```

![image](https://user-images.githubusercontent.com/5348170/149979903-7f5d9a46-f793-4901-9dfb-160915b4b507.png)

**Comment by deanmarcussen** [comment]
This was reported on the release of 1.1 as well.

It seems like there is a NuGet cache issue that some users, possibly from China experience.

There are a number of solutions suggested on this issue https://github.com/OrchardCMS/OrchardCore/issues/9974

**Comment by six006** [comment]
Thanks,I have resolved ,
https://cloud.tencent.com/developer/article/1627467

**Comment by theonewu** [comment]
In China, you should change the nuget source. I suggest the huaweiyun:  https://repo.huaweicloud.com/repository/nuget/v3/index.json
