### ISSUE TITLE
The notifier does not work now

### ISSUE THREAD

**Issue by alexbocharov** [OrchardCMS/OrchardCore#1103]
Detected for `1.0.0-beta1-3384`

**Comment by sebastienros** [comment]
What is the notifier?

**Comment by alexbocharov** [comment]
OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Notify/INotifier.cs

**Comment by alexbocharov** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.DisplayManagement/Notify/INotifier.cs

**Comment by alexbocharov** [comment]
For example, when editing a user

**Comment by sebastienros** [comment]
☹️
