### ISSUE TITLE
How to use strongly typed model in alternative view of a Theme correctly?

### ISSUE THREAD

**Issue by YaoaY** [OrchardCMS/OrchardCore#1104]
In my custom admin theme,i created `Views/OrchardCore.Users/admin/Index.cshtml` to override the default view which the module provided.

There is a problem with using `Input Tag Helper`.
```<input id="search-box" asp-for="Options.Search" type="text" class="input-sm form-control" placeholder="@T["Search"]" autofocus="autofocus">```

> The asp-for attribute value is a ModelExpression and the right hand side of a lambda expression.

It was worked in the `OrchredCore.Users` module (of cause):

https://github.com/OrchardCMS/OrchardCore/blob/bd2982ac9cadab2679a85880899ab9b98785a258/src/OrchardCore.Modules/OrchardCore.Users/Views/Admin/Index.cshtml#L41

But in my alternative view, I didn't have the `OrchardCore.Users.UsersIndexViewModel` ,and `An expression tree may not contain a dynamic operation` .

After i added this line:
`@model OrchardCore.Users.ViewModels.UsersIndexViewModel`
Anyway , It's worked.
![a0qq 20171019001340](https://user-images.githubusercontent.com/8706312/31729734-772da31c-b462-11e7-80af-6f727d5424be.png)

Except that IDE suggested error `cs0234 the type or namespace name 'Users' does not exist in the namespace 'OrchardCore` ....
![a01qq 20171019001402](https://user-images.githubusercontent.com/8706312/31729741-8139f2f2-b462-11e7-93fd-abfb9239d6b1.png)

Am i doing right? is there any other way ?

**Comment by sebastienros** [comment]
I assume you theme project would need to reference the package that owns this class.

**Comment by YaoaY** [comment]
Thanks @sebastienros !

I just do not want to do so, so I asked this question.:joy:

if that's the only way... 👌

**Comment by sebastienros** [comment]
If you want to remove the IDE issue you need to reference the project. Otherwise you will just have to live with the error. But it's only in the editor fortunately.

Ideally there would be a way to have "editor only" references, but to my knowledge it doesn't exist, but I will ask if there is a way to add a reference and mark it as "transient" for instance so that it would not be required when deployed.

**Comment by sebastienros** [comment]
Apparently there is a way, reference the other packages, but then mark the `<PackageReference>` with `PrivateAssets="All"`

Then ensure that when you create the package it doesn't reference the other ones.

**Comment by YaoaY** [comment]
Than you for your help @sebastienros ! 🍻 
I'm all clear now 😀 
Live with the error or reference packages with `PrivateAssets="All"` both are good for me.
And when the reference condition `Condition="'$(Configuration)' == 'Debug'"` is available someday. That'll be perfect. 🙏
