### ISSUE TITLE
`AddHttpClient<MyService>()` fails within Modules.

### ISSUE THREAD

**Issue by johnrom** [OrchardCMS/OrchardCore#11041]
new version of #6677 as it was asked that a new issue be created.

Typed calls to `AddHttpClient` are failing within a module in `.Net 5.0` and `.Net 6.0`. (I tried rolling back to .Net 5.0 in case OC 1.1 was incompatibile with 6.0).

```cs
// MainProject/Startup.cs
class MainStartup
{        
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddHttpClient<MyService>(); // this is cool
  }
}

// Module/Startup.cs
class ModuleStartup : OrchardCore.Modules.StartupBase
{ 
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddHttpClient<MyService>(); // NullReferenceException
  }
}
```

The issue is as follows. In AspNetCore, `AddHttpClient` registers a singleton of `HttpClientMappingRegistry`.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L52-L54

When initializing a typed HTTP Client, `HttpClientBuilderExtensions.AddTypedClient` calls `HttpClientBuilderExtensions.ReserveClient`, which iterates through the Builder's Services and attempts to find an _instantiated_ instance of HttpClientMappingRegistry. 

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L634-L636

Orchard Core's FeatureAwareServiceCollection doesn't automatically instantiate Singletons, for the reason that @marlon-tucker linked in the initial issue -- it doesn't implement `IDisposable`, so it isn't instantiated until `ServiceProvider.GetService<HttpClientMappingRegistry>()` is called:

https://github.com/OrchardCMS/OrchardCore/blob/ec2154ae099913ee81751f30c4f7660952fe63c9/src/OrchardCore/OrchardCore/Shell/Builders/Extensions/ServiceProviderExtensions.cs#L42-L59

As you can see in the `ReserveClient` method above, however, GetService is never called on the `HttpClientMappingRegistry` -- it is instead selected through LINQ, meaning it is never instantiated. `Single()` returns a registered service, but `Single().ImplementedInstance` is null.

![image](https://user-images.githubusercontent.com/1881482/150216148-0c281f52-ad45-41df-a20b-142e223ebf16.png)

I'll try and provide a repro when I have the chance.

**Comment by johnrom** [comment]
Even if I manually instantiate the `HttpClientMappingRegistry` and the `Microsoft.Extensions.DependencyInjection.ServiceCollection` is proven to have this instance, the instance itself doesn't appear to be copied to the `FeatureAwareServiceCollection`.

**Comment by rjpowers10** [comment]
I'm using AddHttpClient in one of my modules, although I'm not using the same overload. I'm using this overload
```
public static IHttpClientBuilder AddHttpClient(this IServiceCollection services, string name, Action<IServiceProvider, HttpClient> configureClient)
```

This is in OC 1.2.2 and I haven't had any problems. Not sure if it is workable for your situation but it could be a possible workaround.

**Comment by johnrom** [comment]
Reproduction here:

https://github.com/johnrom/orchard-core-issue-reproduction#11041

**Comment by deanmarcussen** [comment]
Thanks for the detailed repro @johnrom 

I suspect from reading the code that the issue exists because you are registering `AddHttpClient()` at both a module level and the main host startup module. Which is one way I can see the code you linked failing.

Does `AddHttpClient()` work fine from a module, when you do not register it at app level?

I'm guessing it does, because we (OC) use `AddHttpClient()` in a few of our modules already, Twitter, Recaptcha, and personally I use it in modules quite regularly.

Can you confirm?

Should make it easier to understand, what we can (if anything) do about it.

**Comment by sebastienros** [comment]
Maybe the way we create the tenant service collection has an issue with this type of service.
@johnrom is only being able to do it from a module an issue? Does the instance need to be shared across tenant scopes (host singleton) ?

**Comment by johnrom** [comment]
I think it is an issue because delaying Application Insights registration to a module probably misses some of the First Chance Exceptions that could occur between BuildServiceProvider and Tenant Initialization.

App Insights and I think Snapshot Collector also use AddTypedClient, but I can double check whenever I enable those on the project I'm working on.

**Comment by johnrom** [comment]
Whether the host singleton is different than the tenant singletons would depend if HttpClients for the host are exposed to tenants. If so, they should be shared so a tenant can not register the same HttpClient for a given name. If not, then they should probably be separate.

If I understand it correctly, the intent of the Microsoft team is to prevent this, though AspNetCore obviously has no concept of Tenants:

```cs
// imagine it's in a host
services.AddHttpClient<IMySharedLibraryService>();

// imagine it's in a tenant
services.AddHttpClient<IMySharedLibraryService>();
```

**Comment by Skrypt** [comment]
> AspNetCore obviously has no concept of Tenants

I think that may be what is happening. Though, probably @jtkech could comment on this since he's the one that worked on the feature since .NET 5.0.

**Comment by jtkech** [comment]
Yes, good catch about the line where it assumes to retrieve the `HttpClientMappingRegistry` implementation instance. Anyway, to make it working at both host and tenant levels, not good to share the same `HttpClientMappingRegistry` as it holds a global `NamedClientRegistrations` dictionary that may be mutated on each tenant container building.

We had the same kind of issue with the new routing system that uses a global list that is mutated each time a tenant pipeline is built by calling `UseEndPoints()`, we needed to isolate tenant level routing services by removing some host level registrations (some are registered by instance of internal classes) and re-register them at the tenant level.

https://github.com/OrchardCMS/OrchardCore/blob/7c7a3dfea1a6ec945103a3f40111eaec5f30056e/src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs#L239-L260

So looks like we need a tenant level `AddHttpClient()` that will be able (with the same technic) to e.g. re-register `HttpClientMappingRegistry` (which is an internal class) at the tenant level.

**Comment by sondli** [comment]
Has this issue been addressed in later versions of OC? I am using 1.2.2 and having the same issues

**Comment by jtkech** [comment]
I don't remember the details but we are using it in some projects.

For example, as we register it in a module startup

    s.AddHttpClient("SomeName", httpClient => httpClient.BaseAddress = new Uri("https://..."));

And then use it in a controller.

    var stream = await _httpClientFactory
        .CreateClient("SomeName")
        .GetStreamAsync(path, HttpContext.RequestAborted);

**Comment by ShaneCourtrille** [comment]
This seems to be working for us so thanks :)

**Comment by marlon-tucker** [comment]
From memory this issue presents itself if any AddHttpClient is called outside the main Orchard initialisation phase.

We resolved it by moving any of those kinds of services inside the `services.AddOrchardCms().ConfigureServices(s => ...)` where `s` is the service collection managed by the Orchard tenanting system. This basically means the internal class is where Microsoft expects it to be.

The downside is this bug is fairly difficult to track down when it presents itself.

Perhaps the Orchard docs on the "Getting Stsrted" page need to explicitly say any additional service registration needs to happen inside the aforementioned lambda expression.

**Comment by jtkech** [comment]
`services.AddOrchardCms().ConfigureServices(s => ...)` register services at the tenant level, it is like doing it in a module/feature startup but is called for any tenant (not based on an enabled feature).

In both cases there is an `Order` param / property that you can tweak.

**Comment by ShaneCourtrille** [comment]
We have a main TenantStartup.cs that we run before doing any other modules and were able to work around this problem by adding the following code earlier in that

```
    var registry = services.SingleOrDefault(sd => sd.ServiceType.Name == "HttpClientMappingRegistry");
                if (registry?.ImplementationInstance == null)
                    services.Remove(registry);
```

**Comment by marlon-tucker** [comment]
I've again hit into this issue.

We are adding a Serilog Sink which pushes logs to some external service. This requires adding the HttpClientFactory infrastructure into the host service collection (as the sink exists outside the tenanting system) - but doing so then causes issues if any of the tenanted service collections also call `AddHttpClient` as discussed above. 

At the moment I have implemented Shane's workaround to get us out of a hole but considering how prevalent the use of `AddHttpClient` is, the tenanting system Orchard uses should handle this as transparently as possible.

To add extra complexity, I can see someone calling `AddHttpClient<T>` on the host service collection expecting that to be available to all tenants. But if each tenant gets its own `HttpClientMappingRegistry` then that wont be the case. Ideally the tenant registries will need to merge the mappings form the host one.

**Comment by marlon-tucker** [comment]
I spoke too soon.

if `AddHttpClient` is called on the host service collection, it sets up a singleton instance of `IHttpClientFactory` .  The implementation of that factory has an `IOptionsSnapshot<HttpClientFactoryOptions>` member which it uses to do the client setup work. 

However, because `IHttpClientFactory` is setup in the host service provider, that options monitor is not aware of any configuration that happens in the shell context service providers. Therefore if a module configures a named client (not sure if the same applies to typed clients) and then asks the factory for an instance of that named client, none of the configurations are applied.

Which ultimately means at the moment, the host service collection should never have `AddHttpClient` called on it. 

I'm going to have to figure out an alternative mechanism to support my Serilog requirements.

**Comment by Jetski5822** [comment]
Just hit this too - any thoughts on how to resolve it?

**Comment by Jetski5822** [comment]
I did this to get it to work

```
		public static IServiceCollection AddTenantHttpClientServices(this IServiceCollection services)
		{
			// The http client system is not tenant aware and uses a global registry of NamedClientRegistrations within HttpClientMappingRegistry
			// which is not good to share as the dictionary may be mutated on each tenant container building.

			var implementationTypesToRemove = new ServiceCollection().AddHttpClient()
				.Where(sd => sd.Lifetime == ServiceLifetime.Singleton || sd.ServiceType == typeof(IConfigureOptions<HttpClientFactoryOptions>))
				.Select(sd => sd.GetImplementationType())
				.ToArray();

			var descriptorsToRemove = services
				.Where(sd => (sd is ClonedSingletonDescriptor || sd.ServiceType == typeof(IConfigureOptions<HttpClientFactoryOptions>)) &&
					implementationTypesToRemove.Contains(sd.GetImplementationType()))
				.ToArray();

			foreach (var descriptor in descriptorsToRemove)
			{
				services.Remove(descriptor);
			}

			services.AddHttpClient();

			return services;
		}
```

**Comment by sebastienros** [comment]
@jtkech is this an issue related to open generics and the way we duplicate the registrations?

**Comment by jtkech** [comment]
What @Jetski5822 did is what I suggested here https://github.com/OrchardCMS/OrchardCore/issues/11041#issuecomment-1017990336 where I commented the following, saying that we already have to do the same kind of things to isolate tenants from the routing services registered at the host level. So we may need to do the same for `.AddHttpClient()`, in fact it works and I'm using it, this is only the generic `.AddHttpClient<ServiceType>()` that doesn't work.

> Yes, good catch about the line where it assumes to retrieve the HttpClientMappingRegistry implementation instance. Anyway, to make it working at both host and tenant levels, not good to share the same HttpClientMappingRegistry as it holds a global NamedClientRegistrations dictionary that may be mutated on each tenant container building.

> We had the same kind of issue with the new routing system that uses a global list that is mutated each time a tenant pipeline is built by calling UseEndPoints(), we needed to isolate tenant level routing services by removing some host level registrations (some are registered by instance of internal classes) and re-register them at the tenant level.

**Comment by marlon-tucker** [comment]
Please be aware of my comment https://github.com/OrchardCMS/OrchardCore/issues/11041#issuecomment-1516697079 which highlights why the non generic `AddHttpClient` calls may not work either.

To get around it you would also have to remove the host HttpClientFactory implementation from the shell service collections, so the shells each get their own singleton instance. That's just a guess at this point though.

**Comment by jtkech** [comment]
@marlon-tucker thanks, I will take it into account.

**Comment by Jetski5822** [comment]
One other consideration is the number of tenants and httpclients. Say we have 2000 tenants, and we call AddHttpClient 2000 times, could that be a memory leak?

**Comment by sebastienros** [comment]
It's not a leak, but an overhead. We do `AddXYZ` for more than just that already.

However, `HttpClient` instances should be unique (per configuration) because there is no reason to duplicate them, they already handle their own pool of connections. Kind of related to the recent improvements we did to Redis connections.

Ideally, we should have as few instances as possible. But we want to be close to the standard .NET usage model.

**Comment by jtkech** [comment]
@Jetski5822 @sebastienros  Okay, will take all of this into account

**Comment by jtkech** [comment]
Okay as @johnrom mentioned in the first comment, looks like `HttpClientMappingRegistry` is not a service intended to be resolved, it is only retrieved from the services collection to check/mutate its inner `NamedClientRegistrations ` dictionary, for example.

    var registry = (HttpClientMappingRegistry?)builder.Services.Single(sd =>
        sd.ServiceType == typeof(HttpClientMappingRegistry)).ImplementationInstance;

    ...
    ...

    registry.NamedClientRegistrations[name] = type;

So the 2 problems are, because it is not disposable we don't pass this registry instance as is to the tenant serices collection, and it doesn't use a concurrent dictionary.

**Comment by Jetski5822** [comment]
@jtkech thoughts on how to resolve this?

**Comment by jtkech** [comment]
It depends on what we want.

1. At least it works if we only use `AddHttpClient()` and `AddHttpClient<>()` at the tenant level.

2. To make it working at both levels we could isolate services as we do for routing, yes @marlon-tucker is right, we would also need to isolate the client factory that uses host level singleton options.

    But then the clients would neither be shared across tenants nor with the host level ones.

3. More complex to coordinate clients across tenants, we could use a thread safe host service, as we now do to share Redis connections, but then we would need different helpers as `AddTenantHttpClient()`.

    The above beeing a compromise because if we also want to share the host level clients, we would also need to initialize the above host coordinator / options with the data registered from the host.


So it depends on what we want, maybe as a first compromise we could support 2. so that it works as before at the tenant level (nothing is shared) but it also allows to register things at the host level.

**Comment by Jetski5822** [comment]
So the problem with having HttpClient at the Parent level, and then at the Tenant level, is that, even if you do..

```
var typetoRemap = services.SingleOrDefault(x => x.ServiceType.Name == "HttpClientMappingRegistry");

if (typetoRemap == null)
{
	return services;
}

// https://github.com/dotnet/runtime/blob/16fc92fef48a98aa474bd1f07ec96a44b7da77be/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#LL537C72-L537C100
// Required an Implementation Instance
services.Remove(typetoRemap);
services.AddSingleton(typetoRemap.ServiceType, serviceProvider.GetService(typetoRemap.ServiceType));
```

You still have the issue that the AddHttpClient<> adds configuration, like call backs... so if you do AddHttpClient<T>(builder => {}) at the tenant level, then the builder will never be called.

Not sure how to resolve that.

**Comment by jtkech** [comment]
Can't for now but I'll try to look at it in the next days.

`HttpClientMappingRegistry` needs to be re-registered as an implementation instance, and needs to be a new instance that you can retrieve by calling `AddHttpClient()` on an isolated collection, as you previously commented, then from memory you also need to re-register `IHttpClientFactory` and the configuration of `HttpClientFactoryOptions`. But if at the end nothing is shared, you could just remove these services and then just recall `AddHttpClient()` at the tenant level.

**Comment by Jetski5822** [comment]
Issue is that DefaultHttpClientFactory holds the references to the Handlers, those are the expensive things; Im wondering if its even possible at the moment to do this...

What I want to avoid is having thousands of HttpHandlers... which will happen if its at the tenant level.

**Comment by marlon-tucker** [comment]
The `DefaultHttpClientFactory` gets the client configurations from a injected [IOptionsMonitor](https://source.dot.net/Microsoft.Extensions.Options/A.html#0b0ae221bf3b6163)<[HttpClientFactoryOptions](https://source.dot.net/Microsoft.Extensions.Http/HttpClientFactoryOptions.cs.html#98f8fe396bbd9f73)>. 

Is it possible to inject a custom implementation of that `IOptionsMonitor<HttpClientFactoryOptions>` which is able to read configurations from both the host level and if it is able to detect a current tenant it can read any configurations from there as well.

Ok it may not be quite as optimised, but with some caching it may be able to get pretty close.

**Comment by jtkech** [comment]
Okay, so at least we want to be able to configure things at both levels without failing, then to share things across tenants so that we don't have for example too many handlers.

Then I think it's better to keep the tenants isolated from the host, or do we really need that a tenant can use a client only configured from the host, what will never work is to use from the host a client that is only configured at the tenant level.

**Comment by jtkech** [comment]
In the meantime here some thoughts based on what I saw.

- First I think that connections sharing is done at a lower IO level.

- What I saw is that anyway a new `HttpClient` is always created and that handlers are resolved or activated, for a typed client an object factory is cached but not sure it takes a lot of memory.

    Yes, this is the Handlers Pipeline that is cached when built by the `DefaultHttpClientFactory`, but here too not sure that it takes a lot of memory, this is not the activated handler instances that are cached.

    Note: Tenants are isolated "Sites" with their Filters/Handlers, Pipeline, APIs and so on, so make sense that they also have their own http client Handlers Pipeline, but I understand the memory concern.

- One annoying thing is that the client factory creates a scope that will be used to activate handlers, which is not a `ShellScope` which e.g. prevents a shell to be disposed while a scope is still active.

            if (!options.SuppressHandlerScope)
            {
                scope = _scopeFactory.CreateScope();
                services = scope.ServiceProvider;
            }

    Anyway the scope is created from the service provider resolved by the factory, so what happens if a `DelegatingHandler` resolve services that may depend on the enabled features of a given tenant.

    This is the case of our `Twitter` handler that injects tenant specific services including a security service, more over this handler is only registered by the tenants having the `Twitter` feature enabled.

    Note: Here we may need a custom service provider as we use for the `RequestServices` that we made aware of the current `ShellScope` so that it returns the `ShellScope.Services` if a current one exists.

- So, in case there is not so much memory consumption by duplicating some caches, maybe a good compromise would be to support the point 2. from my previous list.

    This to allow http client configurations at both host and tenant levels but without sharing them, and let it working as before at the tenant level (no sharing across tenants).
