### ISSUE TITLE
The field defined as UserPickerField could not be found in Graphql

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11054]
I create a type that has a field to specify to a user
This field can be queried in Lucene
But I can't find it in Graphql. I searched the source code of OrchardCore, and it doesn't seem to define Graphql type for UserPickerField. Is it removed or is there a better way to query it?

**Comment by hyzx86** [comment]
Here is the type definition
![image](https://user-images.githubusercontent.com/15613121/150623554-c2e8f081-bd27-4c84-a8bd-8bc025232947.png)

but can not fond `Test11Users`  in graphql
![image](https://user-images.githubusercontent.com/15613121/150623527-c173f93f-74c1-45d7-afe3-8435b24ed1e3.png)

**Comment by hyzx86** [comment]
Done for me，
but about `userManager.FindByIdAsync(id)` , Is there supposed to be a cache here?


``` C#
    public class UserPickerFieldQueryObjectType : ObjectGraphType<UserPickerField>
    {
        public UserPickerFieldQueryObjectType()
        {
            Name = nameof(ContentPickerField);

            Field<ListGraphType<StringGraphType>, IEnumerable<string>>()
                .Name("userIds")
                .Description("content item ids")
                .PagingArguments()
                .Resolve(x =>
                {
                    return x.Source.UserIds;
                });

            Field<ListGraphType<StringGraphType>, IEnumerable<string>>()
                .Name("userNames")
                .Description("the userName")
                .PagingArguments()
                .Resolve(x =>
               {
                   return x.Source.GetUserNames();
               });

            Field<ListGraphType<ContentItemInterface>, ContentItem[]>()
             .Name("properties")
             .Description("the user properties")
             .PagingArguments()
               .Resolve(x =>
             {
                 var userIds = x.Source.UserIds;
                 if (userIds != null && userIds.Length > 0)
                 {
                     var serviceProvider = x.ResolveServiceProvider();
                     var userManager = serviceProvider.GetRequiredService<UserManager<IUser>>();

                     var items = userIds.Select(id =>
                   {
                       var u = userManager.FindByIdAsync(id).GetAwaiter().GetResult();
                       if (u != null)
                       {
                           var profile = ((User)u).As<ContentItem>("UserProfile");
                           return profile;
                       }
                       return null;

                   });
                     return items.Where(u => u != null).ToArray();

                 }
                 else
                 {
                     return Array.Empty<ContentItem>();
                 }

             });
        }
    }
```

**Comment by hyzx86** [comment]
`OrchardCore.Users.Services.UserStore`

there is no caching, which means that if there are 100 results, 100 SQL queries will be executed.

``` C#
        public async Task<IUser> FindByIdAsync(string userId, CancellationToken cancellationToken = default(CancellationToken))
        {
            return await _session.Query<User, UserIndex>(u => u.UserId == userId).FirstOrDefaultAsync();
        }
```
CustomUserSettings feels a little inappropriate
We should have a type that can be indexed and queried separately, that can be bound to each User information and can use all the functionality of ContentType, such as Lucene Index, SQL Index and Graphql

**Comment by hyzx86** [comment]
updated :



            Field<ListGraphType<ContentItemInterface>, ContentItem[]>()
             .Name("UserProfile")
             .Description("the user profiles")
             .PagingArguments()
               .ResolveAsync(async x =>
             {
                 var userIds = x.Source.UserIds;
                 var contentItemLoader = x.GetOrAddPublishedContentItemByIdDataLoader();
                 var items = await contentItemLoader.LoadAsync(x.Page(x.Source.UserIds));
                 return items.Where(item => item != null).ToArray();  
             });

**Comment by Skrypt** [comment]
I'm not sure 100% if it was not intentional to not expose UserName / UserId's from the GraphQL endpoint though.

**Comment by gvkries** [comment]
Completed by #15389
