### ISSUE TITLE
Orchard logo as icon for each NuGet package

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#11050]
### Is your feature request related to a problem? Please describe.
We could have [an icon](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file) for the NuGet packages instead of the default one:

![image](https://user-images.githubusercontent.com/1976647/150584964-2df43ee2-7cb8-4970-804a-2733803cf2ab.png)

This is a bit of branding.

### Describe the solution you'd like
This can be added by using a single central logo file in from the root, then along the lines of this in a Directory.Build.props file:

```xml
<Project>
  <PropertyGroup>
    <PackageIcon>NuGetIcon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="NuGetIcon.png" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <!-- Copying the Orchard logo as an icon to all NuGet-published projects. -->
  <Target Name="Copy NuGet icon" AfterTargets="AfterResolveReferences">
    <Copy SourceFiles="$(MSBuildThisFileDirectory)OrchardCoreNuGetIcon.png" DestinationFiles="$(ProjectDir)NuGetIcon.png" SkipUnchangedFiles="true" />
  </Target>
</Project>
```

### Describe alternatives you've considered
Leaving it as it is.

**Comment by ns8482e** [comment]
@Piedone Created PR #11053
