### ISSUE TITLE
Set default Admin Theme Programatically

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#11079]
As we know OC provides `TheAdmin` as default admin theme. I came up with a scenario where I need to set a custom admin theme by default. I know that the theme set in the recipes

I'm looking for a hook to set my custom theme even `TheAdmin` is set during setup, I just digging into the code

https://github.com/OrchardCMS/OrchardCore/blob/2264ae2960a03367fb111c69b79f6bd31635241b/src/OrchardCore.Modules/OrchardCore.Themes/Services/SiteThemeService.cs#L32-L37

I didn't find any sort of handler that allow us to intercept the process, @jtkech any idea?

**Comment by ns8482e** [comment]
Theme can applied on request by implementing  IThemeSelector

**Comment by hishamco** [comment]
Thanks Niraj, I saw `IThemeSelector` but I didn't realize that it can be used from settings. I was though there should be a handler. Anyhow I will try to set the admin theme using the same technique

**Comment by hishamco** [comment]
I will try to implement my own `IThemeSelector` instead

**Comment by hishamco** [comment]
Works great!! Thanks again Niraj
