### ISSUE TITLE
Placement is not applied to ContentPart_Edit

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#11088]
### Describe the bug

When placement is defined for `ContentPart_Edit` none of them applied /cc @kdubious 

```json
{
  "ContentPart_Edit": [ 
    { 
      "place": "-", 
      "contentType": [ "Container" ] 
    } ], 
"BackgroundColor_Edit": [
    { 
      "place": "-", 
      "contentType": [ "Container" ] 
    } ], 
"BootstrapColor_Edit": [
  {
    "place": "-", 
    "contentType": [ "Container" ] 
    
  } ]
}

```
### To Reproduce
1. Create Part `BootstrapColor`  with `TextField` with PredefinedList  as editor
2. Select Reusable
2. Add `BootstrapColor` Part as named part to `Container`  content type with name `BackgroundColor `
3. Add any of following placement rule in placement.json to hide . <br/>
`"ContentPart_Edit": [ { "place": "-", "contentType": [ "Container"], "contentPart" : ["BootstrapColor"], "differentiator": "BackgroundColor" } ]` OR <br/>
`"BootstrapColor_Edit": [ { "place": "-", "contentType": [ "Container"], "contentPart" : ["BootstrapColor"], "differentiator": "BackgroundColor" } ]` OR <br/>
`"BootstrapColor": [ { "place": "-", "displayType": "Edit", "contentType": [ "Container"], "contentPart" : ["BootstrapColor"], "differentiator": "BackgroundColor" } ]`
4. See part is still visible while editing and placement rule is not applied.
### Expected behavior
The  placement should apply

### Screenshots
NONE

**Comment by kdubious** [comment]
Yes, indeed. I think there might be several ways to solve this. The ideal would be to allow "edit" placements for "parts" that are added to content types, or added into flow parts.

In the repro steps:
```BackgroundColor``` is the name of the part as used on a content type.
```BootstrapColor``` is the name of the part itself.

**Comment by ns8482e** [comment]
How about changing shape type to `[Part]_Edit` instead of `ContentPart_Edit` ? That will allows to create separate record in Placement in admin

**Comment by kdubious** [comment]
@ns8482e i tried both, but both failed. BackgroundColor_Edit and BootstrapColor_Edit.
