### ISSUE TITLE
ContentPart with custom DisplayMode 

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#11084]
When you create a custom DisplayMode for a ContentPart (Ex : https://github.com/agriffard/Prism.OrchardCore):
- It is not displayed on the Dashboard (Widget with a content type definition that has the ContentPart with a custom DisplayMode)
- If you declare some Settings, you cannot get them in the custom Display view.

https://github.com/agriffard/Prism.OrchardCore/blob/908337aa0d17bf9d771607f40e78278e3346fe92/src/Prism/Views/HtmlBodyPart-Prism.Display.cshtml#L10

**Comment by ns8482e** [comment]
@agriffard That I don’t like about display modes as it changes the core shape on which placement works

you need it define placement for shape of display mode like this https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Html/placement.json

**Comment by sebastienros** [comment]
> you need to define placement for shape of display mode

@ns8482e Does it mean that having a display mode defined on a Part, it would not be visible on the front-end?

**Comment by ns8482e** [comment]
@sebastienros  should not be any issue with `Summary` or `Detail` display types - this issue is only for given display type when display type is not defined in driver.  i.e. here for HtmlBodyPart `DetailAdmin`  is not placed by driver and instead placed using placement - so driver is not aware of where to place the shape for `DetailAdmin`.

**Comment by agriffard** [comment]
What should it look like exactly @ns8482e ?

https://github.com/agriffard/Prism.OrchardCore/commit/f5101edad8cc437a1f3f7ddb503cb40bad8f6052

```
{
  "HtmlBodyPart_Display__Prism": [
    {
      "place": "Content:10",
      "displayType": "DetailAdmin",
      "contentType": "DashboardWidget"
    }
  ]
} 
```

Does not seem to work to display `HtmlBodyPart-Prism.Display.cshtml` for an Html Dashboard widget with an HtmlBodyPart with Prism DisplayMode.

**Comment by agriffard** [comment]
Second problem : Any chance you know why I can't retrieve the associated Settings:

https://github.com/agriffard/Prism.OrchardCore/blob/f5101edad8cc437a1f3f7ddb503cb40bad8f6052/src/Prism/Views/HtmlBodyPart-Prism.Display.cshtml#L10

**Comment by agriffard** [comment]
```
@{
    HtmlBodyPartPrismDisplaySettings settings = new HtmlBodyPartPrismDisplaySettings();
    if (Model.TypePartDefinition != null)
    {
        settings = Model.TypePartDefinition.GetSettings<HtmlBodyPartPrismDisplaySettings>();
    }
}
<script asp-name="prism" version="1" at="Foot"></script>
<style asp-src="~/Prism.OrchardCore/Styles/@(settings.Theme ?? "prism").css" version="1"></style>
```

`Model.TypePartDefinition` is always null.

**Comment by ns8482e** [comment]
> `Model.TypePartDefinition` is always null.

I guess it's only available for edit `Edit` shapes

**Comment by agriffard** [comment]
> I guess it's only available for `Edit` shapes

But it is working for Fields with Display mode (Ex: TextField with Header).

**Comment by gwonen** [comment]
Is the naming convention for alternate display mode placement documented anywhere? I had to search for this issue to figure out that I needed to target `TaxonomyField_Display__Tags` to move my TaxonomyField.

**Comment by sebastienros** [comment]
@gwonen please file a PR to update the documentation if that can help someone else

**Comment by sebastienros** [comment]
@ns8482e hasn't this feature been implemented already?

**Comment by ns8482e** [comment]
Documented under Templates https://docs.orchardcore.net/en/latest/docs/reference/modules/Templates/#templates-orchardcoretemplates

**Comment by Piedone** [comment]
This was done, then.
