### ISSUE TITLE
Middleware registered using UseModules not run

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1108]
Adding a piece of middleware like so...

![image](https://user-images.githubusercontent.com/619530/31773259-18e60c7c-b4da-11e7-97c9-8653f42543dd.png)

The middleware never gets hit

**Comment by jtkech** [comment]
@Jetski5822 

After a quick look i think it's because you do it at the app level, not through the `startup.Configure()` of a module. So in this case your `.UseMiddleware()` would need to be called before

    app.UseMiddleware<ModularTenantRouterMiddleware>() // called by the 1st version of UseModules()

This because `ModularTenantRouterMiddleware` will build and use the middleware pipeline of the current tenant. So for this use case, in the 2nd `UseModules()` we would need to reverse the calling order,

    public static IApplicationBuilder UseModules(this IApplicationBuilder app, ...)
    {
        app.UseModules(); // for this use case, would need to be called after

        app.ConfigureModules(modules);

        return app;
    }

But right now, just try this

    app.UseMiddleware<YourGlobalMiddleware>();
    app.UseModules();

**Comment by Jetski5822** [comment]
Thanks for looking in to this @jtkech  - however the behaviour of 

```
app.UseMiddleware<YourGlobalMiddleware>();
app.UseModules();
```

Any my example are different. You example will run before the modular middleware runs and will run in the application scope. My Example should register the middleware at the Tenant scope.

**Comment by jtkech** [comment]
Ah okay.

So you would need to use the `startup.Configure()` of a module as done in `OrchardCore.Commons`.

But maybe you want the ability to add a default `middleware` to all tenant pipelines without adding something to `OrchardCore.Commons`, and without having to enable another specific module intended to register this middleware. If so, you would need to be able to add this module to the default features.

**Comment by sebastienros** [comment]
I assume this piece of code should enable to register a middleware for all tenants (before we fork the pipelines). But shouldn't it be doable already without this lambda? By just adding a middleware before we call UseModules() ? Hence we could remove this lambda?

**Comment by jtkech** [comment]
This is what i suggested but it seems that @Jetski5822 want to register a middleware in tenant pipelines but still from the startup of his application.

But not sure, i'm a little lost, need more time and / or more infos ...

**Comment by anoordende** [comment]
Not sure if it helps, but just a moment ago I had some middleware not being hit which was due to mvc handling the request before the middleware.

**Comment by jtkech** [comment]
@anoordende so here we can't do anything ;) Maybe some caching configured at the app level.

@Jetski5822 not sure at all but can you try this change in `ModularApplicationBuilderExtensions`.

        public static IApplicationBuilder UseModules(this IApplicationBuilder app, Action<ModularApplicationBuilder> modules = null)
        {
            // Ensure the shell tenants are loaded when a request comes in
            // and replaces the current service provider for the tenant's one.
            app.UseMiddleware<ModularTenantContainerMiddleware>();

            app.ConfigureModules(modules);

            app.UseMiddleware<ModularTenantRouterMiddleware>();

            return app;
        }

        //public static IApplicationBuilder UseModules(this IApplicationBuilder app, Action<ModularApplicationBuilder> modules)
        //{
        //    app.UseModules();
        //
        //    app.ConfigureModules(modules);
        //
        //    return app;
        //}

        public static IApplicationBuilder ConfigureModules(this IApplicationBuilder app, Action<ModularApplicationBuilder> modules)
        {
            var modularApplicationBuilder = new ModularApplicationBuilder(app);
            modules?.Invoke(modularApplicationBuilder); // take care of this line

            return app;
        }


**And then retry exactly what you did.**
