### ISSUE TITLE
Support Mermaid Markdown syntax

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#11081]
Add support to Mermaid Syntax for Markdown (Body, Part, Field).
It allows you to easily describe textually different kinds of diagrams (Flow, sequence, chart, ...). 

https://mermaid-js.github.io/mermaid/#/examples

![image](https://user-images.githubusercontent.com/703248/151329042-299e30fd-ae46-439b-8ca3-973656e33f94.png)

https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoicGllXG5cIkRvZ3NcIiA6IDQyLjk2XG5cIkNhdHNcIiA6IDUwLjA1XG5cIlJhdHNcIiA6IDEwLjAxIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjp0cnVlfQ

![image](https://user-images.githubusercontent.com/703248/151328944-9478c3e5-91de-4cb8-b245-c3726635c1f1.png)

It seems easy to integrate in javascript:

https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted?id=working-examples

I guess it could be a display mode.

**Comment by ns8482e** [comment]
Liquid is powerful - it's better to build using liquid filters

**Comment by sebastienros** [comment]
Not by default. External module.
