### ISSUE TITLE
Enable https module does not seem to redirect to https

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#11085]
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/11082

<div type='discussions-op-text'>

<sup>Originally posted by **giannik** January 27, 2022</sup>
I enabled the https module and set it up as shown below to redirect all requests to https .

But when going to frontend and calling home page without https it doesnt seem to redirect to https and browser says site its not secure.

Certificates are all ok , if i manually type in https it works , but the automatic redirect from http does not work.

Is there something I might be missing ?  

![image](https://user-images.githubusercontent.com/1516981/151385194-b1c45789-6d11-4171-848d-777a990aef10.png)
</div>

**Comment by giannik** [comment]
Ok I had to add a re-write rule in IIS , deoes not hae to do with the module.
Closing.
