### ISSUE TITLE
Invalid serial number for shell descriptor during Setup

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#11091]
I started to build a new theme, whenever I setup a new tenant I got invalid operation exception, I'm not sure why I'm getting this

/cc @jtkech

**Comment by hishamco** [comment]
FYI I'm working on `1.0.0` it was fine when I worked with other two themes before week ago, all of the sudden this happen today while setup any tenant with any theme

**Comment by deanmarcussen** [comment]
The exception means you are trying to run setup on a database that has already been setup previously. You need to use a clean database

**Comment by hishamco** [comment]
Thanks Dean, I'm using SQLIte it supposed to create a new database in each setup, let me check if the tenant folder exists and come back to you

**Comment by hishamco** [comment]
You are right, seems the first installation doesn't completed successfully, that you the database exist from first installation

Thanks
