### ISSUE TITLE
OpenId data migration issue

### ISSUE THREAD

**Issue by JESUS-PEREZ** [OrchardCMS/OrchardCore#11110]
### **Issue:**
Foreign key exceptions while running migration no.7 of OpenId migrations.

### **Cause:**
Some tables are being deleted before deleting their foreign keys. Exceptions found at list on these two foreign keys:
- `FK_OpenIdAppByRoleNameIndex_Document_DocumentId`
- `FK_OpenIdApplicationIndex`

### **Steps to reproduce the issue:**
1. Upgrade from v1.0.0-rc2-13450 to v1.2.2

### **More information**
Looking at the code of the [failing migration](https://github.com/sebastienros/yessql/blob/0b8dd422407b5216882d2dc990d74ab29c4e56cd/src/YesSql.Core/Sql/SchemaBuilder.cs#L139), it seems it is deleting/re-creating all **OpenId** tables. The problem is at the time of removing the old tables.

`The DELETE statement conflicted with the REFERENCE constraint "FK_OpenIdAppByRoleNameIndex_Document_DocumentId". The conflict occurred in database "Orchard_db", table "dbo.OpenIdAppByRoleNameIndex_Document", column 'DocumentId'.
`

![image](https://user-images.githubusercontent.com/22843772/152003540-d0f8872a-064f-483d-9df2-4cbd7d9f36e1.png)

Looking also at [YesSql library](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Migrations/OpenIdMigrations.cs), it seems that at the time of doing `DropReduceIndexTable<OpenIdAppByRoleNameIndex>()`, it tries to remove a foreign key called `FK_{table}_DocumentId` while in our database that foreign key is called `FK_{table}_Document_DocumentId`.

As a workaround we tried to remove the foreign key (`FK_OpenIdAppByRoleNameIndex_Document_DocumentId`) manually before running the migrations, but then we got another issue related to `OpenIdApplicationIndex` table.

`The DELETE statement conflicted with the REFERENCE constraint "FK_OpenIdApplicationIndex". The conflict occurred in database "Orchard_db", table "dbo.OpenIdApplicationIndex", column 'DocumentId'. 
`

Again, we tried to remove that foreign key manually, but now the migration complains because it can't find the foreign key we manually removed.

`'FK_OpenIdApplicationIndex' is not a constraint. Could not drop constraint. See previous errors`

**Comment by sebastienros** [comment]
> it seems that at the time of doing DropReduceIndexTable<OpenIdAppByRoleNameIndex>(), it tries to remove a foreign key called FK_{table}_DocumentId while in our database that foreign key is called FK_{table}_Document_DocumentId.

If YesSql's behavior was updated between 1.0 and 1.2 then that's probably why upgrading to 1.0, 1.1 and 1.2 in order will fix this issue.

**Comment by JESUS-PEREZ** [comment]
We tried to upgrade from v1.0.0-rc2-13450 to v1.0.0, and we found same issue with OpenId migrations, unfortunately. Although now get directly get an error on "OpenIdApplicationIndex", and not on "OpenIdAppByRoleNameIndex" table

`The DELETE statement conflicted with the REFERENCE constraint "FK_OpenIdApplicationIndex". The conflict occurred in database "Orchard_db", table "dbo.OpenIdApplicationIndex", column 'DocumentId'.`

**Comment by JESUS-PEREZ** [comment]
It seems we have solved the problem about "OrchardCore.Users" migrations by adding this module as a dependency on the manifest of one of our custom modules, but not sure if this is the way to solve the issue. I would have expected these migrations to be automatically picked up..

**Comment by sebastienros** [comment]
This sounds familiar ...

**Comment by sebastienros** [comment]
Apparently, an issue with ordering of migrations, so referencing the module will make it run before.

**Comment by sebastienros** [comment]
Will reopen if someone else hits the same issue.
