### ISSUE TITLE
Error when switching RazorRuntimeCompilation in Host project

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#11128]
When switching  RazorRuntimeCompilation  on and then off a compilation error occurs.

To repro :
1. Use latest dev branch start a new site with any recipe (I used the blog recipe)
2. In OrchardCore.Cms.Web.csproj set RazorRuntimeCompilation from false to true
```
    <RazorRuntimeCompilation>true</RazorRuntimeCompilation>
```
3. Run project and see everything working 
4. Stop site and turn back RazorRuntimeCompilation setting  to false
5. Run site and get the following error
```
One or more compilation references may be missing. If you're seeing this in a published application, set 'CopyRefAssembliesToPublishDirectory' to true in your project file to ensure files in the refs directory are published.
```

![image](https://user-images.githubusercontent.com/1516981/152644573-b4fe0dbd-e726-41bb-93d5-ea4b3c8516ce.png)

**Comment by vengi83644** [comment]
I too had this behavior. I am thinking because of the folders in bin.

Mine got away once I did clean and run the app.

**Comment by sebastienros** [comment]
Not sure it's supported in .NET 6. Have you tried with a standard ASP.NET template to be sure it's related to OC?

**Comment by jtkech** [comment]
Just tried with the last dev it works, try to do a `git clean -xdf` under your solution folder.

`RazorRuntimeCompilation` is our own property used to reference (or not) the `.Razor.RuntimeCompilation` package whose build `targets` will populate (or not) the `refs` folder with the needed compile time libs.

**Comment by Skrypt** [comment]
People should use "Hot Reload" now. "dotnet watch"
This RazorRuntime compilation is kind of the same feature but only for Razor templates.
I won't debate about the reliability of "hot reload" but people should get used to "dotnet watch".

**Comment by giannik** [comment]
Yes, deleting the bin folders from solution worked.
@Skrypt  yes the unreliability of "dotnet watch run" was the reason to looking into something else.
