### ISSUE TITLE
Recipe files get copied at root during publish

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1112]
When publishing with `dotnet publish -c Release -o c:\temp\orchard` your get the recipe files copied at the root, and also copied in the module's folder in `Packages`. This makes the recipes appear twice.

I think they should only be copied in the Packages with the rest of the asset. @jtkech do you think we are doing something special for these files? It shouldn't behave differently than content files, right?

**Comment by jtkech** [comment]
Just tried, you are right, but we don't do anything special for these files.

Maybe because they are `.json` files, i think some changes has been done around these files in last versions of msbuild.

I will take a look asap and fix it.

**Comment by jtkech** [comment]
Fixed, i will do a PR.
