### ISSUE TITLE
OrchardCore.Menu.Migrations.UpdateFrom3Async causes extreme memory usage and application hanging

### ISSUE THREAD

**Issue by ryanwawr** [OrchardCMS/OrchardCore#11123]
I am attempting to update an Orchard Core solution from RC2 to 1.2.2, but UpdateFrom3Async in OrchardCore.Menu.Migrations causes extreme memory usage and does not seem to terminate when we attempt to run the migration on a copy of our production database. For context, the website we are upgrading hosts the documentation for our enterprise software, so we have a large number of menu items to support organization and easy navigation of the help content. To give an idea of scale, we have 43 menus, the largst of which have a few hundred sub-topics, each represented by a menu item. The issue with the migration appears to be that it is attempting to migrate ContentItem.Name to DisplayText for every _version_ of every menu, and we have over 3600 versions of those 43 menus. I added a breakpoint in Visual Studio to log the content item Id of each item being migrated, then started the migration and let it run overnight. It immediately jumped up to ~18GB memory usage, and when I came back to check ~15 hours later, it was still running and had logged ~1.25 million content item IDs, most of which were repeated around 450 times.

I copied the update code in that migration method to one of the projects in our solution for easier debugging, and when I tried changing the predicate in this query
`var menus = await _session.Query<ContentItem, ContentItemIndex>(x => x.ContentType == "Menu").ListAsync();`
to also filter by only the latest or published version, I got 43 results instead of 3600+, and the migration completed in seconds.

I could imagine that the lack of filtering by latest or published version would be intentional in order to catch and update older versions of content, as a content editor might unpublish a version and revert to an older one, but this is causing major problems in our attempt to update. Is there a more efficient way to accomplish the intended migration here? We have around 23,000 content item versions total across all content types, but because of the way our data is structured, we end up updating the same versions of content items hundreds of times.

**Comment by Skrypt** [comment]
Have you tried to update it from RC2 to 1.0 then to 1.1 and then finally to 1.2 in order?

**Comment by ryanwawr** [comment]
Yes, I have. We initially tried to update from .NET Core 3.1 and Orchard Core RC2 to .NET 5 and Orchard Core 1.2.2, but stepped back the version repeatedly to see if that resolved the issue. Currently I am just trying to update from RC2 to 1.0 with no change to the .NET framework, and I am still experiencing this issue.

**Comment by Skrypt** [comment]
Best way to skip this migration is to change the value of the last migration executed in the database. Then execute this migration manually with SQL.

**Comment by Skrypt** [comment]
To find the record which contains migrations values for each module : 

```SQL
SELECT * FROM Document WHERE Type = 'OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data'
```

Then alter the JSON value for your module in the Content column.

**Comment by Skrypt** [comment]
After this you can update your Menu DisplayText by using pure SQL depending on the database you are using the SQL will be different. I believe you will require to use some JSON functions to achieve this.

**Comment by ryanwawr** [comment]
I tried that yesterday. Skipped the migration in Orchard.Core.Menus, then copied it into a migration file in one of our modules to more easily debug it. We're probably going to have to update the database manually, as you suggested. Posted the issue because it seemed like a problem that other users may encounter as well, though I suppose there probably aren't a ton of users with thousands of menu items who are updating from release candidates at this point.

**Comment by Skrypt** [comment]
```SQL

//SQL Server
UPDATE ContentItemIndex SET (DisplayText = (SELECT JSON_VALUE(Document.Content, '$.DisplayText') FROM Document WHERE Document.Id = ContentItemIndex.DocumentId))
WHERE ContentType = 'Menu'
```

**Comment by Skrypt** [comment]
I'm looking at the C# code and it seems to take the value from the MenuListPart. So maybe a small adjustment needed there on the JSON value taken from the Document table.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/152579306-68a5eec7-5a56-44bb-a3b3-76d5bcc249f3.png)

**Comment by Skrypt** [comment]
Take a look at what is missing in the older database and add these JSON values with JSON Functions. It's totally doable.

**Comment by ryanwawr** [comment]
Thanks, I'll play around with that. Given our use case, it may be good enough for us to update just the latest and published versions of the menus, which could be accomplished pretty easily by just skipping the migration as you suggested and copying it into one of our modules with a small modification to the query predicate.

And agreed. I think our scenario is a bit out of the ordinary (mostly in having this much data on an RC), but does seem odd that it's using that much memory. Memory usage jumps up to about 12 GB when debugging from Visual Studio just from executing the initial query before jumping up about 50% once it's gotten into the loop for a while, though some percentage of that is probably debug info.

**Comment by Skrypt** [comment]
Note for YesSQL. Add JSON FUNCTION Dialect for running one simple SQL query instead of generating massive amount of SQL for these migrations.

**Comment by sebastienros** [comment]
> I copied the update code in that migration method to one of the projects in our solution for easier debugging, and when I tried changing the predicate in this query
var menus = await _session.Query<ContentItem, ContentItemIndex>(x => x.ContentType == "Menu").ListAsync(); to also filter by only the latest or published version, I got 43 results instead of 3600+, and the migration completed in seconds.

I don't understand, this is the current code from the migration. How are the queries different?

Note for migration developers, don't query the database without bounding the results, use pages of 50 items for instance and do the operation in batches, it will be very fast and won't allocate much.
We should also move to System.Text.Json which would optimize that.

Side discussion:
We might want to think about serializing the documents in binary, so assuming this is always JSON in the db might not be the best thing. And one step further might be to decouple the documents store from SQL to allow for using files or blob storage, we would not even be able to joint to Document tables, only indices. In that specific case that would not fix anything, but this level of abstraction (not assuming JSON storage) makes the current code work fine if we decided to do it.

**Comment by ryanwawr** [comment]
> I don't understand, this is the current code from the migration. How are the queries different?

What I pasted was the current code from the migration. I changed the predicate to 
`(x => x.ContentType == "Menu" && x.Latest)`
when I copied the migration into my solution to avoid looping over the same content items hundreds of times. Admittedly, this may miss some content item versions that the original migration would update, but that's likely not going to be an issue for us.

**Comment by sebastienros** [comment]
I'd prefer to keep updating the old versions and add batching instead. Do you want to add the code to a PR?

**Comment by Skrypt** [comment]
So basically loop 50 times and do a _session.CommitAsync()

Ok, I understand the fact that the Document storage data format could be using different implementations. And in that case, we prefer to abstract these migration operations.

**Comment by sebastienros** [comment]
@deanmarcussen reminds us that we can't call `SaveChangesAsync()` in migrations (not `CommitAsync` since it doesn't exist anymore) but we should do `FlushAsync()` on every page.
After the call we also need to call `_session.Detach(obj)` such that it's not kept in memory by OC.

**Comment by Piedone** [comment]
We've added `UpdateFrom3Async()` in 2021. So, this shouldn't really affect anybody now. Please reopen/comment if it's a serious concern for you still.

**Comment by ryanwawr** [comment]
@Piedone No concerns here. We worked around it and haven't run into issues since.

**Comment by Piedone** [comment]
Thanks for the update!
