### ISSUE TITLE
Add ability to configure the mini-profiler to appear to specific roles.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#11144]
### Is your feature request related to a problem? Please describe.
An admin need to profile a production instance. Enabling MiniProfiles for everyone to see is not acceptable is most cases. Also, a user may want to profile an ajax request to analyze query or other info.

### Describe the solution you'd like
Add the following MiniProfile settings to the UI so it's way to configure it.
 1. Selects roles to make it visible to "Administrator" would be the default roles.
 2. Add option to enable/disable the profiles without having to disable the feature. This is a nice to have, not a must have.
 3. Where should the profiler be visible "Frontend", "Backend", or "Front and Backend"

Add a way to profile ajax requests also.

### Describe alternatives you've considered
Currently I am only using it locally not in production because I don't want everyone to see the MiniProfiler. For the AJAX request, I used SQL Profilers to get the raw sql query and analyze it manually.

**Comment by hishamco** [comment]
Agree in the principle we could add some features that could be bound to OC roles

**Comment by DotCat1985** [comment]
I've opened a pull request related to this issue.
Please let me know what you think, so we will fix the mini-profile soon.

**Comment by Piedone** [comment]
Implemented in https://github.com/OrchardCMS/OrchardCore/pull/11502.
