### ISSUE TITLE
Documentation - configuration description

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#11160]
In documentation page for configuration, there is misleading information - using dot in "OrchardCore.Media" which is deprecated instead of "OrchardCore_Media".

Small improvement, but if someone is editing docs, it could be changed.

![image](https://user-images.githubusercontent.com/52829889/153576208-6b328af5-96e3-481d-9594-3901b21cc7ee.png)

p.s. can I add label documentation somehow to this?

**Comment by Skrypt** [comment]
You can submit a PR, the docs are in this repository
