### ISSUE TITLE
Review .vsconfig file

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#11176]
https://github.com/OrchardCMS/OrchardCore/blob/cfcafbd7c1add1becf09e5bf83fbd9246045f0ee/.vsconfig#L8

We should review this file to make sure the packages are still relevant.

**Comment by jptissot** [comment]
With a new VS 2022 installation, I see this message: 

![{05FE417C-92C1-4FEE-BC2C-9FBD31B0EFAD}](https://user-images.githubusercontent.com/4681586/153761403-2aa63e6d-c9bc-4eca-a3c9-3b3585d1c6b7.png)

**Comment by jtkech** [comment]
It is  there since a while, I planned to fix it but never took the time to do it ;)

Should not appear as it works without installing extra components
