### ISSUE TITLE
Proxy configuration for the Mail module

### ISSUE THREAD

**Issue by pivielti** [OrchardCMS/OrchardCore#11183]
Hi,

My web-hosting provider doesn't allow outbound connections by default. (IONOS Windows Shared). I know that all outbound connections should be sent through a proxy in this platform. 

I was able to configure it for HTTP(S) by adding this in the Startup.cs of my OrchardCore web app :
`HttpClient.DefaultProxy = new WebProxy(""http://winproxy.server.lan:3128");`.

However I was not able to configure this for SMTP connections. So currently I'm not able to send a mail with Orchard on this hosting provider.

Can you provide a way to configure a proxy for SMTP connections ?

**Comment by hishamco** [comment]
FYI MailKit has supports for Socks4 and Socks5 proxies. but OC does provides that, let me check this and what are the suitble way to provide such feature to the end users in terms os APIs

**Comment by hishamco** [comment]
@pivielti does your proxy required a credentials? if not please let me know, so I can test it

**Comment by pivielti** [comment]
Hi @hishamco, it doesn't require credentials but it is only reachable from the IONOS network.

**Comment by hishamco** [comment]
I see seems I will not be able to test, anyhow are using the source base or the NuGet package for `OC.Email`?

**Comment by hishamco** [comment]
@pivielti try to use [OCC.Email](https://www.nuget.org/packages/OrchardCoreContrib.Email/1.1.0) for validation. I will push a PR once you confirm it's working. I already added a unit test [here](https://github.com/OrchardCoreContrib/OrchardCoreContrib/blob/dev/test/OrchardCoreContrib.Tests/Email/SmtpServiceTests.cs)

To make it work just initialize a new instance of `MailProxy` like the following:

```csharp
var settings = new SmtpSettings
{
    Proxy = new MailProxy { Host = "Your Host", Port, YourPort };
}
```

**Comment by pivielti** [comment]
> I see seems I will not be able to test, anyhow are using the source base or the NuGet package for `OC.Email`?

I only reference the NuGet package ´OrchardCore.Application.Cms.Targets´. My web app is essentially a basic setup with a theme project.

**Comment by sebastienros** [comment]
Having this as an option in the SMTP settings would be fine.

**Comment by hishamco** [comment]
Ok, I will try to do what I did in the OCC to make this happen
