### ISSUE TITLE
Update the consent page to allow creating permanent authorizations

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#1118]
Currently the consent page asks for consent every time an OIDC request is received. We should revisit that and offer a way to "remember" that the user already granted the application an access by storing a new authorization in the database.

/cc @jersiovic

**Comment by jersiovic** [comment]
@PinpointTownes  Implementing OpenIdAuthorizationStore service will make that openiddict stores authorizations? Or do we need to do extra stuff.
Then we would need to check in access controller if exist a token for same subject (user) requested  related to an authorization with same scope of the authorization requested. Is this what you mean?

**Comment by PinpointTownes** [comment]
Yup, that's the idea @jersiovic :+1:

**Comment by PinpointTownes** [comment]
Assigned to me as I started working on it.
