### ISSUE TITLE
Seo Module: Many fields dont appear in the GraphQL API

### ISSUE THREAD

**Issue by dannyd89** [OrchardCMS/OrchardCore#11199]
### Describe the bug

I'm currently trying Orchard Core as a potential CMS for my company and ran into a problem with the SEO module and GraphQL I couldn't fix.

### To Reproduce
I added the Seo module under features to be able to add Seo metas to a content item.
When trying to get this data over the GraphiQL interface, not all of the fields available through the Seo module appear there.
If I add a OpenAPI module and call the content item data over that endpoint I get all the data including the Seo meta data I entered

### Expected behavior
All the Seo meta fields should appear in the GraphiQL interface and be queriable

### Screenshots
Screenshot from swagger:
![image](https://user-images.githubusercontent.com/15252548/154517662-8dd1bf09-f0cf-4dff-8492-24b53cda59e0.png)

Screenshot from GraphiQL:
![image](https://user-images.githubusercontent.com/15252548/154517785-969318f2-8848-4824-bfa7-bb7ae8fd2bb5.png)

Since Im very interested in the project I may also offer to fix this if someone points me in the general direction where this needs to be fixed in the OrchardCore.Seo module

**Comment by sebastienros** [comment]
Maybe start by checking how the other fields are adding it to GraphQL? TextField might be the simplest.
