### ISSUE TITLE
Admin menu - active item selected by display name

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#11190]
It seems that active item in admin menu is selected by display name, which causes problems when translation is the same, e.g. in czech culture there is translation "Šablony" for both Themes and Templates and both are selecting last item with this displayname  

![image](https://user-images.githubusercontent.com/52829889/153875385-9d7a0b7c-53cd-4c05-96d2-f377007683de.png)

**Comment by hishamco** [comment]
AFAIK there's css class injected for each menu item, that's why you saw the issue, but again me as a human been how can I differentiate between the first and second while the display text are same ;)

**Comment by MikeKry** [comment]
true, maybe the best solution would be to just change translation in czech, as it does not give sense anyway. Themes = Témata, Templates = Šablony
