### ISSUE TITLE
[SEO] Meta tags and favicon are not rendered to preview

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#11206]
### Describe the bug
Tab 1 - content item
Tab 2 - its preview
![image](https://user-images.githubusercontent.com/2365592/154581629-4cb428ef-599b-43ab-b494-7c62c8127903.png)

### To Reproduce
1. Enable rendering of SEO tags
2. Set title to a different value
3. Open a preview
![image](https://user-images.githubusercontent.com/2365592/154581881-4e004d63-2f9c-4571-a7b8-3d229787283f.png)

### Expected behavior
SEO tags are rendered on preview

**Comment by Skrypt** [comment]
I think this is because it is rendered inside an actual iframe. The preview renders an iframe so it cannot render an HTML header because the actual header is rendered inside that iframe.

So we have : 

```html
<html>
<header>
preview doesn't render anything here because it's the header of the preview view itself.
</header>
<body>
    <iframe>
          <html>
               <header>Preview header renders here but doesn't affect the current page header because it's inside an iframe</header>
               <body>Preview content renders here</body>
          </html>
    </iframe>
</body>
</html>
```

**Comment by Piedone** [comment]
Yep, and this is not something that seems feasible to change. Please reopen if you think this is a crucial issue and you're willing to work on contributing it.
