### ISSUE TITLE
Remove OrchardCore.Contents.FileContentDefinition usage from remaining recipes

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#11200]
### Is your feature request related to a problem? Please describe.
Under https://github.com/OrchardCMS/OrchardCore/pull/10799 the Agency and Blog recipes got `OrchardCore.Contents.FileContentDefinition` usage removed, since as was the consensus, it's only useful in specific cases and most of the time you need to turn it off. The same issue is there with the Headless and Blank recipes. Especially for the Blank recipe I see no reason to include anything apart from the bare bones. (And if you're using and SQL DB, which unless you're really savvy you will do, I don't see the point of `OrchardCore.Contents.FileContentDefinition` at all: Why make data storage more complicated?)

### Describe the solution you'd like
Just remove the `OrchardCore.Contents.FileContentDefinition` enable step from the two recipes.

### Describe alternatives you've considered
The alternative is turning it off after every single setup and migrate content definition as described [in the docs](https://docs.orchardcore.net/en/latest/docs/guides/content-definitions/).

**Comment by sebastienros** [comment]
Fine then!

**Comment by Skrypt** [comment]
My bad I thought I did not look closely enough when I did that PR. I agree with removing it.
