### ISSUE TITLE
Remove Lucene from built-in recipes

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#11203]
### Is your feature request related to a problem? Please describe.
Similar to https://github.com/OrchardCMS/OrchardCore/issues/11200 this is about making the built-in setup recipes lightweight: Lucene is a feature that you don't need on every site, especially that due to it storing files on the local file system that need to be preserved (i.e. not temp files) it needs special considerations for hosting (you need to take care of those files when moving the app between environments and doing deployments).

### Describe the solution you'd like
I propose to not enable Lucene by default in the following recipes:
- Headless: just remove it.
- Blank: just remove it.
- Blog: remove it and reimplement the `RecentBlogPosts` Query as an SQL Query. Since this recipe is also kind of an example of configuring Lucene, I wouldn't completely destroy this aspect; rather, the current configuration can remain in the theme as a separate, non-setup recipe that you can run if you want to do what the current recipe does, Query-wise (i.e. it would enable and configure Lucene and indexing, delete the `RecentBlogPosts` SQL Query and replace it with the current Lucene Query).

### Describe alternatives you've considered
The alternative is disabling the feature after every setup and re-implementing `RecentBlogPosts` as an SQL Query.

**Comment by sebastienros** [comment]
We need to ensure the doc is up to date with enabling the feature when configuring the search page at least.

**Comment by Piedone** [comment]
Good point and yes, we could have a Search recipe as well as a separate one to switch the Query (you may want both, one of them, or neither).

**Comment by Piedone** [comment]
Yes, auto-rebuilding works but I consider it more of a failsafe than what you want to rely on heavily (since especially if you use Lucene not just for search but also Queries, an index rebuild will cause a partial outage on your site until it's done). Anyway, this is the reason for the Elasticsearch initiative.

What about what I proposed in my last message for the Blog recipe? I.e.:

- Create an SQL `RecentBlogPosts` Query and don't enable Lucene by default.
- Have a separate, non-setup recipe to set up search just for a frontend search page (i.e. 90% of what happens related to Lucene in the recipe now).
- Have a second non-setup recipe that runs the previous one and also swaps out `RecentBlogPosts` with a Lucene Query.
- Document this.

So, you have all the examples there, but you are not forced to use Lucene right away, only if you want it and understand the consequences. (BTW this is not anything against Lucene of course, we absolutely need it and full text search in general.)

**Comment by Piedone** [comment]
@Skrypt what do you think?

**Comment by Skrypt** [comment]
I agree with the suggested changes.

**Comment by Piedone** [comment]
@BanzragchUchral is working on this.
