### ISSUE TITLE
[Sitename] must be localizable

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#11208]
### Is your feature request related to a problem? Please describe.
Currently, you set Sitename in settings and it is used as title metatag. If the site is localizable, Sitename still is not. 

### Describe the solution you'd like
Make Sitename localizable.

### Related issues
#11207

**Comment by Skrypt** [comment]
Have you tried `@T[Orchard.Sitename]` and you create a .po translation?
Else, this is something that will be done with the Dynamic Localizations PR which is kind of stale right now.

**Comment by hishamco** [comment]
@sebastienros can we try to triage the dynamic localiztion PR, or review that work that I did in OCC, seems there are many things needs a dynamic nature of localization

**Comment by sebastienros** [comment]
@hishamco Where is the PR that I can merge it?

**Comment by hishamco** [comment]
#4466 

let me update it with the latest stuff I did in OCC or we can use `OrchardCoreContrib.Localization` as 3rd party package reference, then when it's stable we can move the work done in OC
