### ISSUE TITLE
[SEO] Render title as `<Content item title> – <Site name>` by default

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#11207]
### Is your feature request related to a problem? Please describe.
Currently, the title of each page is the site name unless specified in the SEO tab of content items.

### Describe the solution you'd like
I think that the default value must be:
1. `<Content item title> – <Site name>` if title is set
2. `<Site name>` if the title is not set or is the default page

Because it is what you usually set.
Maybe it would be nice to be able to define it using Liquid.

**Comment by Piedone** [comment]
Yes: https://github.com/OrchardCMS/OrchardCore/discussions/11117#discussioncomment-2106043

**Comment by Piedone** [comment]
The current default pattern is item title - site name.
