### ISSUE TITLE
Q: How to connect the authoring views

### ISSUE THREAD

**Issue by mwpowellhtx** [OrchardCMS/OrchardCore#11217]
Using the `Coming Soon` boilerplate stuff initially. I see what I think are the rendered outputs. Is there a way to review the _admin_ or _author_ level views, however? I see I can access an `https://localhost:5001/admin` page, for instance, but I do not see anything that indicates the _content_, _items_, _views_, or other half-expected CMS artifacts, etc. Apologies if my verbiage is a bit clumsy. Thanks!

**Comment by Piedone** [comment]
Not really sure what your question is about, but are you asking where the display (HTML and else) of admin pages are coming from? They are from [TheAdmin](https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore.Themes/TheAdmin) theme and from the respective modules. E.g. [this template](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Title/Views/TitlePart.Edit.cshtml) is for the title editor.
