### ISSUE TITLE
ModifiedUtc and PublishedUtc are not correctly imported by a setup recipe

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1121]
If I use a recipe to create content items that have `ModifiedUtc` and `PublishedUtc` properties, they don't seem to be imported correctly. 

The generated content items have a last modified date corresponding to the date of execution of the setup.

**Comment by agriffard** [comment]
I guess this is because of the CreateAsync in the ContentStep.cs:
https://github.com/OrchardCMS/OrchardCore/blob/7ae71fbd06efd1a34e3c5931721980286f4ff291/src/OrchardCore.Modules/OrchardCore.Contents/Recipes/ContentStep.cs#L43

and then in the ContentsHandler.cs that sets the ModifiedUtc to utcNow:
https://github.com/OrchardCMS/OrchardCore/blob/7ae71fbd06efd1a34e3c5931721980286f4ff291/src/OrchardCore/OrchardCore.ContentManagement/Handlers/ContentsHandler.cs#L25

**Comment by sebastienros** [comment]
Probably because of that `CreateAsync` call, exactly. It's taking it as a new content item, and not something that has to be imported without alteration.

It will probably require an `Import` action in the handler.

**Comment by sebastienros** [comment]
I think it's fixed, would you be able to try it?

**Comment by hishamco** [comment]
@agriffard could you please try it as Seb suggest before, if it's still there, I may handle this

**Comment by agriffard** [comment]
@hishamco The problem is still here.
The `ModifiedUtc` and `PublishedUtc` properties are initiated to utcNow in ContentsHandler:
`context.ContentItem.ModifiedUtc = utcNow; `
so even if you pass a `ModifiedUtc` in the json recipe, it is not taken into account.

**Comment by hishamco** [comment]
Ok, no worry I will look into this one

**Comment by hishamco** [comment]
@agriffard is this happen when you run the recipe from the admin too?

**Comment by agriffard** [comment]
It is when I create a tenant from a recipe that I exported and made it a setup recipe.

**Comment by hishamco** [comment]
I will try to examine both cases, thanks
