### ISSUE TITLE
Q: How to 'reset' to ground zero

### ISSUE THREAD

**Issue by mwpowellhtx** [OrchardCMS/OrchardCore#11216]
### Describe the bug
More of a question/discussion, perhaps, than a true bug. Getting my sea legs under me initially.

### To Reproduce
1. Establish the baseline CMS out of the box following the basic _Getting Started_ guidelines
1. From `Postgres pgAdmin` (or, _insert your DB manager_) reset connections and put the DB on the shelf; i.e. disconnect and rename to something else i.e. `#ontheshelf` or whatever
1. Receiving exception, `Npgsql.PostgresException (0x80004005): 3D000: database "my_orchardcore_cms" does not exist`

### Expected behavior
Evidently there is more being configured than 'just' the database, which is half unexpected on my part, or at least until I get another of my legs under me.

Plus side the baseline CMS content does 'work'. However, could not verify the table names, etc. I want to backtrack and setup with the _prefixes_, anticipating possibly multiple tenants, if not also 'versions' if you will, of our web site, i.e. a _ctor_ version, then a simple _brochure_ version, then more integrated from there, in phases. Each of which is potentially multiple tenant, if not 'replacing' the prior phase content.

Mind orienting me to what else is being setup that I need to unwind, undo, etc, in order to achieve the setup screen once again?

Thank you...

**Comment by Piedone** [comment]
Yep: You need to remove the tenant's folder too. With more involved [configuration](https://docs.orchardcore.net/en/latest/docs/reference/core/Configuration/) you can also get rid of local storage completely.

Please open discussions for questions here next time: https://github.com/OrchardCMS/OrchardCore/discussions

Please reopen if anything remains unclear.

**Comment by mwpowellhtx** [comment]
@sebastienros Would be helpful I think to illustrate a `Table Prefix` usage example, i.e. _"You can specify a table prefix if you intend to reuse the same database for multiple sites."_ For instance, I enter, `"alpha_"` and I end up with `"alpha__"` for _prefixes_ it seems. We do not need any underscores, which is part of the prefixed naming convention; however, that is undocumented out of the box.

**Comment by mwpowellhtx** [comment]
> Please open discussions for questions here next time: https://github.com/OrchardCMS/OrchardCore/discussions

Ah, okay; thanks for clarifying, no worries.

**Comment by Piedone** [comment]
Would you like to venture into adding a note about the table prefix at the bottom of [this docs page](https://docs.orchardcore.net/en/latest/docs/getting-started/? See: https://docs.orchardcore.net/en/latest/docs/topics/docs-contributions/

**Comment by mwpowellhtx** [comment]
> Would you like to venture into adding a note...

Assuming there is a cost benefit to doing so. However, at the moment, we are focused on our business verticals. Thanks so much...

**Comment by Piedone** [comment]
I'm talking about submitting a pull request with a line added to that documentation page. Probably not too big of a business expense and it would make a nice first contribution ;).

**Comment by mwpowellhtx** [comment]
> I'm talking about submitting a pull request with a line added to that documentation page. Probably not too big of a business expense and it would make a nice first contribution ;).

I understand the implications, yes; our focus is what it is at the moment, but I appreciate the nudge.

**Comment by hishamco** [comment]
Can we open this? if the conversation still ...
