### ISSUE TITLE
Dojo Course 3 videos in docs

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#11219]
### Is your feature request related to a problem? Please describe.
I'm asking about this because just adding it would perhaps come over as pushy advertising.

There are 40 Orchard tutorial videos in the [Dojo Course 3](https://www.youtube.com/playlist?list=PLuskKJW0FhJcSX7j0Bd-1X5hq3dgCtYwO), each for a specific topic. These topics usually map to specific modules. If you don't look through it or arrive at it from somewhere, it's hard to discover though.

### Describe the solution you'd like
Add these videos under the Videos sections a lot of pages [like this one](https://docs.orchardcore.net/en/latest/docs/reference/modules/AdminDashboard/) already has. I.e. add each video to a matching page (one video might be matching for multiple pages).

### Describe alternatives you've considered
The tutorials are already linked from [here](https://docs.orchardcore.net/en/latest/docs/resources/tutorials/) so the alternative discovery exists.

**Comment by Piedone** [comment]
The YouTube playlist has all the videos in order. The idea behind adding each video to a relevant docs page is to aid discoverability when you don't want to just watch the whole thing from top to bottom.

**Comment by hishamco** [comment]
> The YouTube playlist has all the videos in order

Right, but it's good to have them on tutorials section or at least point to the YouTube list

**Comment by Piedone** [comment]
That's already done here: https://docs.orchardcore.net/en/latest/docs/resources/tutorials/

**Comment by hishamco** [comment]
Maybe I didn't notice that ;)

In case you need me to help you to spread the videos links into our docs let me know

**Comment by Piedone** [comment]
Thank you! For now, I'm just asking for feedback on whether everyone is OK with this, or rather, anybody has an objection.

**Comment by hishamco** [comment]
I don't have any objection while we already have some video links in our docs, let us hear the feedback from the other members

**Comment by porgabi** [comment]
Can't assign myself but I'm doing this.

**Comment by hishamco** [comment]
It's your Gabor
