### ISSUE TITLE
Ellipsis liquid filter

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1123]
Todo: Create the equivalent of the `Ellipsis `extension method as a Liquid filter.

`truncate` exists in Liquid but it cuts the string at the exact characters count, while ellipsis removes the HTML markups to prevent that.

Thanks to this, it will be easy to add a BodyPart.Summary.liquid in a theme, like this :
`{{Model.Body | truncate: 200 | raw }} `

**Comment by sebastienros** [comment]
There is another filter to remove html tags that you can use first.

**Comment by agriffard** [comment]
Ok, it can be a an alternative indeed :
`{{ Model.Body | strip_html | truncatewords:50 | raw }} `

**Comment by sebastienros** [comment]
Close it then?
