### ISSUE TITLE
An error occurred while sending an email: 'Method not found: 'MimeKit.MimeEntity MimeKit.AttachmentCollection.Add(System.String, System.IO.Stream)'.'

### ISSUE THREAD

**Issue by ericrrichards** [OrchardCMS/OrchardCore#11245]
### Describe the bug

I have another library that I am using that depends on MailKit/MimeKit 3.1.0, and if I include that library, the OrchardCore.Cms.Email feature stops working.  All attempts to send emails through the ISmtpService generate this error:

`An error occurred while sending an email: 'Method not found: 'MimeKit.MimeEntity MimeKit.AttachmentCollection.Add(System.String, System.IO.Stream)'.'`

### To Reproduce
1. Include MailKit 3.1.0 and MimeKit 3.1.0 in an OrchardCMS project
2. Enable and configure the Email feature
1. Go to 'https://localhost/Admin/Email/Index'
2. Click on 'Test Settings'
3. Fill out the form to send a basic email with recipient, subject and body

1. Remove references to MailKit 3.1.0 and MimeKit 3.1.0
2. Rerun steps 3,4,5
3. Mail is sent successfully

**Comment by hishamco** [comment]
Why you need to reference MailKit and MimeKit, OC.Email.Module is already referenced them

**Comment by ericrrichards** [comment]
I am using other non-orchard code that has a dependency on newer versions
of MailKit.

This is the simplest reproduction that exhibits the same behavior.

**Comment by hishamco** [comment]
I will bumb the versions ...

**Comment by hishamco** [comment]
Seems @agriffard  already updated the versions [here](https://github.com/OrchardCMS/OrchardCore/pull/11111), so please use the nightly builds
