### ISSUE TITLE
OpenIdServerSettings are being overwritten and makes the tenant unusable

### ISSUE THREAD

**Issue by sucalavlad** [OrchardCMS/OrchardCore#11265]
Hello,

I am working on an application that uses orchard core for its versioning and multi-tenant possibilities.
I encountered an issue during the upgrade of orchard core from 1.0.0-rc2-13450 to 1.0.0([issue](https://github.com/OrchardCMS/OrchardCore/issues/10752)) that was making my tenants unusable, but was resolved by going into each tenant's admin and resaving the configuration found in OpenId Connect -> Settings -> Authorization Server.
I thought this issue only appeared because of the upgrade, but I discovered that when I add new steps to a cms data migration(for example modifying a content type) and orchard core needs to update its entities the same problem occurs. 
Orchard core modifies the "OpenIdServerSettings" section in the Document table, Orchard.Core.Settings row of each tenant and makes it unusable, because the cms then cannot properly read the open id settings until I go perform the configuration resave I mentioned before in the admin panel.
How my tenant's recipe.json open id server settings section looks:
![image](https://user-images.githubusercontent.com/30407875/155560238-9e631fff-4268-4484-857d-a60f6134afea.png)
How the working tenant settings look in the database:
![image](https://user-images.githubusercontent.com/30407875/155561562-7105e28e-48f8-4c3f-a5a5-4864ad70f7d2.png)
How the tenant settings look when updated by orchard core(not working):
![image](https://user-images.githubusercontent.com/30407875/155561715-b8031f54-d9d7-4774-8114-8e075b1f55e5.png)
I am not sure what is causing this update, please let me know if there is something I need to modify in my recipe or if you have any ideas.

Thank you,
Vlad S.

**Comment by hishamco** [comment]
Could you please try to use the latest version?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
