### ISSUE TITLE
Micro Frontends Request

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#11272]
There have been a lot of articles talking about micro frontends.  I think this should be a goal of Orchard.
My previous request about name spaces here can be ignored now I think if you make micro frontends:
https://github.com/OrchardCMS/OrchardCore/issues/4808

Micro frontends should contain all the content types and liquid templates and other needed schema to support it.

**Comment by hishamco** [comment]
> Micro frontends should contain all the content types and liquid templates and other needed schema to support it.

Could you please elaborate?

**Comment by JoshTango** [comment]
Also technically  content definition might be considered a backend item and therefore part of a microservice instead of micro frontend.  However I think maybe Orchard should just definer its own jargon so create Micro Something.

**Comment by JoshTango** [comment]
Also Micro Something should be able to be created in the Admin UI.  I know you can make a module but that involves writing code.

**Comment by JoshTango** [comment]
If I use WIX for example I'm pretty sure they have Microservices and Micro frontends for their platform.  I see checkboxes for things like Forum or Membership Sign Up or others.

**Comment by JoshTango** [comment]
Just so we are all on the same page we are talking about a vertical slice up and down the stack.  So I assume separate database tables but not necessarily separate databases.  Separate content definitions and front end templates.  I assume the whole thing could be packaged up as well.  Perhaps its own recipe?

**Comment by Piedone** [comment]
You can divide up an OC app into multiple smaller OC apps (i.e. microservices). What exactly would you need from OC for this?
