### ISSUE TITLE
Documentation Bug Maybe

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#11275]
https://docs.orchardcore.net/en/dev/docs/getting-started/templates/

It currently declares 1.0.0 but maybe that should be updated to 1.2.2?

Also it gives instructions on how to download the latest dev branch where it also says 1.0.0
Maybe that should also be updated ?
@agriffard

**Comment by hishamco** [comment]
It's updated in the source, seems @agriffard not push the changes in docs.orchardcore.net

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/tree/main/src/docs/getting-started/templates

**Comment by JoshTango** [comment]
I get the same error when using the 13. command:
OrchardCore.ProjectTemplates::1.3.0-* is not supported.

@deanmarcussen

**Comment by agriffard** [comment]
The `dev` branch is not used anymore.

Start from the root `https://docs.orchardcore.net/` and you will be redirected to `https://docs.orchardcore.net/en/latest`.

The correct link is https://docs.orchardcore.net/en/latest/docs/getting-started/templates/

**Comment by JoshTango** [comment]
ok thanks.
The link I provided is what shows up in google search.

Also this link:
dotnet new -i OrchardCore.ProjectTemplates::1.3.0-* --nuget-source https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json  

gives the error:
OrchardCore.ProjectTemplates::1.3.0-* is not supported.

**Comment by JoshTango** [comment]
when i go to the nuget site the highest version is 1.2.2

**Comment by hishamco** [comment]
Ya, it's the latest official release, `1.3.0` is the current on going version, which can be accessed via CloudSmith

**Comment by JoshTango** [comment]
well 1.3 will not download from cloudsmith

**Comment by sebastienros** [comment]
It works with `OrchardCore.ProjectTemplates::1.3.0-preview-16739` so "dotnet new" doesn't seem to understand the `-*`. We need to set the full version for previews. By default it detects the latest stable version. Or we would need to remove the `preview` prefix.

**Comment by Piedone** [comment]
This isn't an issue anymore.
