### ISSUE TITLE
Installing code generation templates fails

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#11273]
The following template packages will be installed:
   OrchardCore.ProjectTemplates::1.0.0-rc2-*

OrchardCore.ProjectTemplates::1.0.0-rc2-* is not supported.

**Comment by hishamco** [comment]
RC2?!!

**Comment by JoshTango** [comment]
read the new bug I made for documentation:

https://github.com/OrchardCMS/OrchardCore/issues/11275

**Comment by Piedone** [comment]
Templates work currently and the documentation issue was discussed under the linked issue.
