### ISSUE TITLE
Execution order of AutoroutePartHandler vs TitlePartHandler

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#11285]
OC 1.2.2

### Describe the bug
I have an autoroute pattern that is based on the content item's DisplayText, `foo/{{ ContentItem.DisplayText | slugify }}`. I'm also trying to programmatically set the TitlePart (and DisplayText) in a custom TitlePartHandler. The problem is there doesn't seem to be a good way to control the ordering of those handlers, so the AutoroutePartHandler runs before my CustomTitlePartHandler and therefore the DisplayText is not yet set.

### To Reproduce
1. Create a new OC site using the blog recipe.
2. Set breakpoints in AutoroutePartHandler.UpdatedAsync and TitlePartHandler.UpdatedAsync
3. Create a new "page" content item
4. Save the content item and see that the AutoroutePartHandler breakpoint is hit before the TitlePartHandler breakpoint.

### Expected behavior
I think it's common for the Autoroute pattern to incorporate the DisplayText, and that works fine as long as you provide a title before the AutoroutePartHandler runs (for example, the user simply providing the title text on the edit page). But I think there is a hole when the TitlePart is being generated in a content part handler, like my own CustomTitlePartHandler or the built-in OC TitlePartHandler.

### Screenshots
Looking at ContentPartHandlerCoordinator, there doesn't seem to be any guarantee to the order in which the content parts are handled. In my case, the AutoroutePart is going to be handled before the TitlePart.
![image](https://user-images.githubusercontent.com/68876423/156187700-eb79d1b9-632f-4e2a-9f23-83af1cdf5cc9.png)

Here's the built-in OC functionality to set the TitlePart based on a pattern. But if my Autoroute pattern depends on the DisplayText, I think there is a hole here if it's not guarnateed for the TitlePartHandler to run first.
![image](https://user-images.githubusercontent.com/68876423/156187896-67363701-5854-4146-b9c5-86b4f4e9270c.png)

### Workaround
I can probably get around this by using a different event (for example, UpdatingAsync, CreatedAsync, etc.). But TitlePartHandler and AutorouteHandler use UpdatedAsync, so that's what I went with for my CustomTitlePartHandler.

**Comment by rjpowers10** [comment]
Here's another test using the blog recipe. This time I don't have my CustomTitlePartHandler; this is all out-of-the-box OC 1.2.2.

Set a sample title pattern on the title part of the "page" content type.
![image](https://user-images.githubusercontent.com/68876423/156208678-88ef4626-d8b8-4484-8fd9-6fc1ca0d2f92.png)

The Autoroute part uses a pattern based on the DisplayText.
![image](https://user-images.githubusercontent.com/68876423/156208784-aef0091f-dc11-47b7-89eb-bce112201ebb.png)

Create a new page. Don't enter anything and just click "save draft".
![image](https://user-images.githubusercontent.com/68876423/156208871-5474e769-1d97-4757-8928-8bec5a775285.png)

After the first save, the TitlePart is set.
![image](https://user-images.githubusercontent.com/68876423/156208921-7cf7cda6-7ac4-4f9d-9f82-f2fb349a0b55.png)

Do nothing and save the draft again. The AutoroutePart is now set.
![image](https://user-images.githubusercontent.com/68876423/156209039-de54c542-7939-4a6f-bcff-de818bbca824.png)

**Comment by Skrypt** [comment]
There is no autoroute that should be created if the Content Item never got published first. Creating a draft shouldn't create an Autoroute Part. Are you sure that you never published this content item?

**Comment by rjpowers10** [comment]
> There is no autoroute that should be created if the Content Item never got published first. Creating a draft shouldn't create an Autoroute Part. Are you sure that you never published this content item?

Are you saying that the autoroute path should only be set on a publish, not a draft? Looking at AutoroutePartHandler.UpdatedAsync, that doesn't seem to be the case.

In my example above I never published the content item. As I said, I saved the draft once, then I saved it again.

**Comment by Skrypt** [comment]
Normally yes, A draft should never produce a working URL with an Autoroute because it's not published.

**Comment by Skrypt** [comment]
Ok, I'm looking at the database in the AutoroutePartIndex. When you save a draft of a content item. It adds a record and sets the Published column to false.

![image](https://user-images.githubusercontent.com/3228637/156264195-ebf3758a-cd22-4485-a153-ffa4772706ae.png)

So, yes it sets the Autoroute "Path" but it's not used as a route. It removes the content item from the route dictionary. So, it is important to set the "Path" when you are publishing the content item at least.

**Comment by Skrypt** [comment]
When you publish a content item and that you save a draft on top of that content item. In the AutoroutePart it sets 2 different records.

![image](https://user-images.githubusercontent.com/3228637/156264530-ec203157-83ed-418b-8d3d-1965842f003a.png)

The only one that will produce a URL working with the path /123123 is the one that is Published == 1.

**Comment by Skrypt** [comment]
So basically, what you see there in the "Autoroute" input in your HTML form is what is currently used (if item has been published) OR what will be eventually used (if you changed the TitlePart and saved a Draft on top of a published version).

**Comment by Skrypt** [comment]
Ok I agree there is an issue though.

**Comment by Skrypt** [comment]
Ok I found the issue. Use `{{ ContentItem.DisplayText | slugify }}` on your AutoroutePart pattern instead of `{{ Model.ContentItem | display_text | slugify }}`

**Comment by Skrypt** [comment]
https://user-images.githubusercontent.com/3228637/156266812-bd44de5c-673e-42e7-9ba5-d34debb19225.mp4

**Comment by Skrypt** [comment]
Can I see your code for your CustomTitlePartHandler?

**Comment by jtkech** [comment]
@Skrypt

Just for info `ConfigureOrder` only defines the order of startup `Configure()` when we build the tenant pipeline, this is the `Order` (0 by default) that acts on the order of startup `ConfigureServices()` when we build the tenant container, so acts on the services / options registrations.

But the manifest dependencies have an higher precedence on this ordering, dependant after its dependencies.

Hmm, because Autoroute and Title don't depend on each other and don't override their `Order`, need to be checked but I think that at the end this is the alphabetic order that will be used, Title after Autoroute ;)

**Comment by Skrypt** [comment]
We have : 

1 - Page (affected by Order ?)
2 - AutoroutePart
3 - FlowPart
4 - TitlePart

**Comment by jtkech** [comment]
Page is a content type, not a part so normally no part driver / handler ordering
Hmm but there is alaways a default part with the same name of the type.

> But if for example, he set his module to Order = 1 then it would be automatically be added after TitlePart.

Hmm yes, but better I think to depend on the Title module / feature in the manifest

**Comment by jtkech** [comment]
> So if I understand correctly he wants to use the DisplayText to generate the AutoroutePart

Yes, I'm using this but don't remember the details ;)

**Comment by Skrypt** [comment]
There's one thing that doesn't work though about his test that he made because on my side even if I set the TilePart.Pattern = "This is a test" and that the AutoroutePart.Pattern = `{{ ContentItem.DisplayText | slugify }}` it works perfectly fine meaning that it uses a value from the AutoroutePart even if its handlers are executed in the opposite order.

**Comment by Skrypt** [comment]
I'm wrong. The templates are executed inside the Drivers themselves.

**Comment by jtkech** [comment]
Yes, looks like you are right, Autoroute would "need" to depend on Title

Then to override the Title would need a driver to run after Title and still before Autoroute, then Title seems to also have an handler that sets the DisplayText if a setting pattern exists ;)

**Comment by Skrypt** [comment]
Why have we set the Autoroute module with `ConfigureOrder = - 100;`?

We can't really make the Autoroute module depend on the Title module because the AutoroutePart.Path could be generated with almost any values coming from any custom modules. So, that's why the AutoroutePart handlers should be executed last I think.

**Comment by jtkech** [comment]
As I remember it's an aspnet routing concern, to register and then execute some services first e.g. `AutorouteTransformer` as I remember

**Comment by jtkech** [comment]
Because of this in the pipeline I think

        public override void Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
        {
            // The 1st segment prevents the transformer to be executed for the home.
            routes.MapDynamicControllerRoute<AutorouteTransformer>("/{any}/{**slug}");
        }

**Comment by Skrypt** [comment]
Ok, so we set these routes first so that the MVC routes have a priority over them. But then it affects the Handler orders. If we set an Order that is completely the opposite; let's say Order = 9999 then we need to see if this would affect the Handler Order and the service register order.

**Comment by jtkech** [comment]
> We can't really make the Autoroute module depend on the Title module

You're right, I didn't say this, just **would** need

**Comment by jtkech** [comment]
`ConfigureOrder = - 100` don't affect the handlers ordering, only the ordering when we build the pipeline, e.g. routing things

**Comment by jtkech** [comment]
Yes

**Comment by Skrypt** [comment]
As long as you don't have 10 000 modules :wink:

**Comment by jtkech** [comment]
And maybe would break the dependency graph for modules that would depend on Autoroute

**Comment by jtkech** [comment]
// IStartup instances are ordered by module dependency with an Order of 0 by default.
            // OrderBy performs a stable sort so order is preserved among equal Order values.
            startups = startups.OrderBy(s => s.Order);

**Comment by Skrypt** [comment]
The only module that depends on OrchardCore.Autoroute is OrchardCore.ContentLocalization.ContentCulturePicker.
Without naming any other modules that we don't know about.
