### ISSUE TITLE
Publish fails on OrchardCore.Demo\Views\Home\ShapePerformance.cshtml

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#1129]
Publishing a web project using OrchardCore as NuGet package with OrchardCore.Demo included results in the follow errors:

~~~~
Cannot convert lambda expression to intended delegate type because some of the return types
in the block are not implicitly convertible to the delegate return type
ShapePerformance.cshtml:65

Cannot implicitly convert type 'string' to 'System.Threading.Tasks.Task'
ShapePerformance.cshtml:65
~~~~

[Link to source](https://github.com/OrchardCMS/OrchardCore/blob/4419a86f53853eb880d2a8bf79a01238a082cffa/src/OrchardCore.Modules/OrchardCore.Demo/Views/Home/ShapePerformance.cshtml#L65)

**Comment by sebastienros** [comment]
Was wondering why I would not see this as I have published orchard many times, and now I realize that we are not referencing Demo by default ... that makes sense.
