### ISSUE TITLE
Dynamic add features on production

### ISSUE THREAD

**Issue by timeshift92** [OrchardCMS/OrchardCore#11303]
### Is your feature request related to a problem? Please describe.
imagine that the project is in production and you can’t stop it, but they ask you to add some modules that need to be developed, and it would be nice to be able to add these modules dynamically

### Describe the solution you'd like
like in the old orchard
is it possible to add features dynamically

### Describe alternatives you've considered
[A clear and concise description of any alternative solutions or features you've considered.](https://docs.orchardcore.net/projects/O1/en/mkdocs/Documentation/Orchard-module-loader-and-dynamic-compilation/)

**Comment by ns8482e** [comment]
With containers  and continuous deployment a you can and new modules without stopping your production site

**Comment by Skrypt** [comment]
We had issues in the past with uploading/enabling modules from runtime so we decided to not reintroduce this feature in OC for performance reasons. Also, there is the fact that removing an assembly from runtime back then was not possible, so basically we couldn't update an assembly from runtime.

Now, as Niraj says, the proper way to do this nowadays it's to make use of Docker and its container's hot-swapping feature. This is exactly what Docker exists for. Also, I believe that in Azure for example there is a feature named "Deployment slots" which allows you to prepare a new version of the website and to swap when it is ready.

**Comment by timeshift92** [comment]
understood, if I deploy it again from the repository, the changed data will not be erased, are they all stored in the database?
Or do I need to set up a deployment plan?

**Comment by Skrypt** [comment]
If you are using SQLite the idea is to create a volume where your App_Data folder will stand when using Docker containers. So, when you swap your container then it keeps using that same App_Data folder that is not contained inside your container.

https://hub.docker.com/r/orchardproject/orchardcore-cms-linux

You can read the instructions here to achieve this. I believe there are multiple other ways to achieve this too.

**Comment by timeshift92** [comment]
thanks for the explanation, didn't guess about App_Data, 
I have no questions left, should I close the issue ?
