### ISSUE TITLE
Missing SEO settings menu

### ISSUE THREAD

**Issue by Tokyo1985** [OrchardCMS/OrchardCore#11310]
Settings menu is missing in the **SEO module**, because `AdminMenu` class is not developed: see the source code in the links below. So, we cannot set the SEO configuration by **OrchardCore** dashboard.

https://github.com/OrchardCMS/OrchardCore/blob/556359c75bf6ab3343b3343d6bcc4541c1b7bce1/src/OrchardCore.Modules/OrchardCore.Seo/

https://github.com/OrchardCMS/OrchardCore/blob/556359c75bf6ab3343b3343d6bcc4541c1b7bce1/src/OrchardCore.Modules/OrchardCore.Seo/Startup.cs#L23

**Comment by hishamco** [comment]
Based on @agriffard PR #8630 seems there's no `AdminMenu` for this, I expect there's a configuration in `appsettings.json` but not documented

@agriffard could you please clarify?

**Comment by agriffard** [comment]
You need to add a SeoMetaPart to your content type.

**Comment by Tokyo1985** [comment]
> You need to add a SeoMetaPart to your content type.
It's clear. Thank you.

**Comment by hishamco** [comment]
> You need to add a SeoMetaPart to your content type.

I forgot this :(
