### ISSUE TITLE
OpenID tokens cleanup optimization

### ISSUE THREAD

**Issue by alin-devnet** [OrchardCMS/OrchardCore#11327]
I've noticed some regular SQL spikes and concluded that those are coming from [OpenIdBackgroundTask](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.OpenId/Tasks/OpenIdBackgroundTask.cs) which cleans up invalid/expired tokens. 

Looking at https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdTokenStore.cs#L426 it looks like that will generate 100 database hits and multiplied for each tenant it adds up. 

Can that be changed to break the loop if the last query returned less than 1000 rows to prevent unnecessary database hits? Happy to do the change, wanted to confirm I'm on the right path first.

**Comment by kevinchalet** [comment]
Sounds like a good idea but we should probably first check with @sebastienros whether YesSql now supports set-based deletes (which would be a much better approach).

**Comment by kevinchalet** [comment]
I believe this was fixed by https://github.com/OrchardCMS/OrchardCore/pull/11382. If not, feel free to re-open.
