### ISSUE TITLE
Refactor Settings.ToObject to GetSettings/WithSettings

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1134]
Example in `BagPartDisplay` compared to `ContentPartFieldIndexSettingsDisplayDriver`.

One is using `JObject.ToObject` directly while the other uses a sub property specific to the settings. This is prevent name collisions.

**Comment by jtkech** [comment]
@sebastienros 

Beginning with `BagPartDisplay`, quite easy. But there are many places to change, and after doing this you need to re-edit your content types, update and save again your related part settings.

So, for an existing site it could be a breaking change.

Let me know if it is worth to continue

**Comment by sebastienros** [comment]
Will be done as part of this issue:
https://github.com/OrchardCMS/OrchardCore/issues/1976
