### ISSUE TITLE
Admin URL prefix cannot be changed

### ISSUE THREAD

**Issue by hieucd04** [OrchardCMS/OrchardCore#11350]
### Describe the bug
I followed the instructions below to change admin prefix but it didn't work.
https://docs.orchardcore.net/en/dev/docs/reference/modules/Admin/

### To Reproduce
1. Create a new & blank website as described here: https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/
2. Add this piece of code to `appsettings.json`:
```
"OrchardCore": {
  "OrchardCore_Admin": {
      "AdminUrlPrefix": "orchard-cms"
  }
}
```
4. Start the site and fill in necessary info
5. Go to `/orchard-cms`

### Expected behavior
Login screen appeared

### Actual behavior
404 happened

### More info
Orchard Core version: 1.3.0
.NET SDK version: 6.0

**Comment by hishamco** [comment]
What's the URL that you redirected to?

**Comment by Skrypt** [comment]
404 is page not found.

**Comment by hishamco** [comment]
Do you mean login page? if yes, the login has nothing to do with Admin URL prefix, the prefix has been used in the admin pages. Am I right?

**Comment by Skrypt** [comment]
Yes and the setting he is talking about is that /admin would then be replaced by /orchard-cms
And this /orchard-cms is returning a page not found 404 error which means it doesn't work for him.

**Comment by hishamco** [comment]
If this is the case that mean there's a breaking change or something goes wrong, I may try this

**Comment by hieucd04** [comment]
I figured it out!
The reason it was not working for me was because I did not use `Host.CreateDefaultBuilder(args)` in `Program.cs` which led to missing default configurations that Orchard Core expects.

This line of code fixed it for me: `.ConfigureDefaults(args);`
