### ISSUE TITLE
Liquid can't seem to handle IHtmlContent

### ISSUE THREAD

**Issue by ovekaaven** [OrchardCMS/OrchardCore#11360]
### Describe the bug

I've tried to use the INotifier interface, where you're supposed to enter a LocalizedHtmlString, which derives from IHtmlContent. Then I tried to customize the message presentation by creating a Message.liquid. Alas, try as I might to convince the {{ Model.Message }} to actually print the message, it was all for naught.

(And of course, it's annoying to do this in Razor because IHtmlContent doesn't have a way to simply return the string so that I can javascript-escape it. And I can't easily just cast it, since it becomes a HtmlString instead of a LocalizedHtmlString if it's been serialized...)

### To Reproduce
1. Create a Message.liquid in your theme, containing "{{ Model.Message }}" and "{{ Model.Message | json }}"
2. Do something that creates a notification. I used custom code, but some workflow could probably do it. (Not sure if it would behave differently with the HtmlString, I've only fought this problem with the LocalizedHtmlString.)
3. The json version should show that there's a Value, but {{ Model.Message }} only prints "Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString" (and {{ Model.Message.Value }} prints nothing, it seems)

### Expected behavior
I should be able to print a IHtmlContent-derived object from Liquid (especially you can apparently generate such objects with Liquid).

**Comment by Skrypt** [comment]
Have you tried `{{ something | raw }}` ?

**Comment by ovekaaven** [comment]
Using "raw" results in it printing "Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString"

**Comment by Skrypt** [comment]
Ok so this is the LocalizedHtmlString object and you want its value.

**Comment by ovekaaven** [comment]
Updated the report since the original {{ Model.Message }} actually prints the same with or without the raw.

**Comment by ovekaaven** [comment]
I've confirmed that {{ Model.Message.Value | raw }} does nothing.

**Comment by ovekaaven** [comment]
If it helps for testing, the controller code looks something like this

```
    public class ContactController : Controller
    {
        private INotifier _notifier;
        private IHtmlLocalizer H;

        public ContactController(
            INotifier notifier,
            IHtmlLocalizer<ContactController> htmlLocalizer)
        {
            _notifier = notifier;
            H = htmlLocalizer;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SendAsync(ContactViewModel form)
        {
            if (form == null) return BadRequest();
            await _notifier.InformationAsync(H["This is a test."]);
            return View("Index");
        }
    }
```

**Comment by Skrypt** [comment]
_notifier.InformationAsync(new LocalizedHtmlString(nameof(ContactController.SendAsync), "{0}", false, "This is a test."));

**Comment by ovekaaven** [comment]
That doesn't seem to change anything, and it seems better to use IHtmlLocalizer anyway.

**Comment by hishamco** [comment]
We may need a helper function, like this:

```csharp
public static string ToHtmlString(this IHtmlContent html)
{
    using (var writer = new StringWriter())
    {
        html.WriteTo(writer, HtmlEncoder.Default);

        return writer.ToString();
    }
}
```

**Comment by Skrypt** [comment]
That would be a filter for Liquid. That's why I was suggesting | raw but maybe there is something else like | html.

**Comment by Skrypt** [comment]
I've found nothing quickly.

**Comment by sebastienros** [comment]
Fortunately, there should be an easy solution. We need to tell Fluid how to handle `IHtmlContent`

First create a custom `FluidValue` that will wrap and `IHtmlContent`:

```c#
private class HtmlContentValue : ObjectValueBase
{
    public HtmlContentValue(IHtmlContent content) : base(content)
    {
    }

    public override void WriteTo(TextWriter writer, TextEncoder encoder, CultureInfo cultureInfo)
    {
        var htmlContent = Value as IHtmlContent;

        if (htmlContent == null)
        {
            return;
        }

        htmlContent.WriteTo(writer, NullHtmlEncoder.Default);
    }
}
```

Then convert any `IHtmlContent` to this instance. Probably in a setup class since it's updating Fluid's options. There should be many examples for that in modules.

```c#
options.ValueConverters.Add(o => o is IHtmlContent h ? new HtmlContentValue(h) : null);
```

**Comment by sebastienros** [comment]
There might be another way, without the custom wrapper:

```
options.ValueConverters.Add(o => 
{
    if (o is IHtmlContent h)
    {
        using (var sw = new StringWriter())
        {
            h.WriteTo(sw, htmlEncoder); // from DI or from fluid's options
            return new StringValue(sw.ToString(), false);
        }
    }
    else
    {
        return null;
    }
}
);
```

**Comment by jtkech** [comment]
@ovekaaven  @sebastienros we already have this kind of converter

https://github.com/OrchardCMS/OrchardCore/blob/247457e63b2531e3288f017ee95f182a1231bd5b/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/OrchardCoreBuilderExtensions.cs#L52-L65

But there is an error, it is checking `o is IHtmlContent c` in place of `x is IHtmlContent c` ;)

Updating the above code with the following fixed the issue, I will do a PR

                    o.ValueConverters.Add(x =>
                    {
                        if (x is Shape s)
                        {
                            return new ObjectValue(s);
                        }
                        else if (x is IHtmlContent c)
                        {
                            return new HtmlContentValue(c);
                        }

                        return null;
                    });
