### ISSUE TITLE
Reduce injected services by introducing IPassport service

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#11372]
### Is your feature request related to a problem? Please describe.
In every class of the OC project where authorization is needed, one has to inject both `IAuthorizationService` along with `IHttpContextAccessor` the access the `User` object on the `HttpContext` to authorize the current principal. Although it's not a problem, I find creating a service that handle accessing the Context, User and authorization would help reduce the need to inject multiple services every time authorizing is needed.

### Describe the solution you'd like
I think if we add a service called something like `IPassport` it would help us reduce code, and make the code a bit more readable. Here is how I think the contract would look like

```
    public interface IPassport
    {
        Task<bool> IsAuthenticatedAsync();

        Task<string> UserIdAsync();

        Task<string> UserNameAsync();

        Task<IUser> UserAsync();

        Task<T> UserAsync<T>() where T : class, IUser;

        Task<bool> AuthorizeAsync(Permission permission);

        Task<bool> AuthorizeAsync(Permission permission, object resource);

        Task<IEnumerable<Claim>> ClaimsAsync();

        Task<Claim> ClaimAsync(string type);

        Task<bool> IsInRoleAsync(string role);

        HttpContext HttpContext { get; }
    }
```

I am not sure where would be the best place for this in OC. Here are route to look into. First, we can add `IPassport` interface into `OrchardCore.Users.Abstractions`. However, this would require us to add a reference to `OrchardCore.Infrastructure.Abstraction` in `OrchardCore.Users.Abstractions` and not sure if this is acceptable.

The second option could be that we add the `IPassport` to `OrchardCore.Infrastructure` but this would require adding a reference to `OrchardCore.Users.Abstractions`

Finally, I think `OrchardCore.Users` would be a good place for the implementation. 

Once this is accepted and home is found for the service, I would create a PR for this request.

**Comment by hishamco** [comment]
I don't think this an issue while we need to inject one service in the controller. This is because other classes have no notion of `HttpContext` built in. But we could have an overload that don't require a user to passed in, the implementation should figure out the user from DI

**Comment by CrestApps** [comment]
> I don't think this an issue while we need to inject one service in the controller. This is because other classes have no notion of `HttpContext` built in. But we could have an overload that don't require a user to passed in, the implementation should figure out the user from DI

I am not sure that I understand the comment. The base controller exposes the `User` instance so in the controller you already only have to inject a single service. But when trying to authorize in other services like driver, it would be nice to only inject `IPassport` instead of 2 service. For example the code in https://github.com/OrchardCMS/OrchardCore/blob/c8b2954e038aaa54963b60bc6cfe193cfea54799/src/OrchardCore.Modules/OrchardCore.Contents/Drivers/OwnerEditorDriver.cs would look like this with the `IPassport`

```
public class OwnerEditorDriver : ContentPartDisplayDriver<CommonPart>
{
    private readonly IPassport _passport;
    private readonly UserManager<IUser> _userManager;
    private readonly IStringLocalizer S;

    public OwnerEditorDriver(IPassport passport,
        UserManager<IUser> userManager,
        IStringLocalizer<OwnerEditorDriver> stringLocalizer)
    {
        _passport = passport;
        _userManager = userManager;
        S = stringLocalizer;
    }

    public override IDisplayResult Edit(CommonPart part, BuildPartEditorContext context)
    {
        var settings = context.TypePartDefinition.GetSettings<CommonPartSettings>();

        if (settings.DisplayOwnerEditor)
        {
            return Initialize<OwnerEditorViewModel>("CommonPart_Edit__Owner", async model =>
            {
                if (part.ContentItem.Owner != null)
                {
                    // TODO Move this editor to a user picker.
                    var user = await _userManager.FindByIdAsync(part.ContentItem.Owner);
                    model.OwnerName = user.UserName;
                }
            }).RenderWhen(async () => await _passport.AuthorizeAsync(StandardPermissions.SiteOwner, part));
        }

        return null;
    }

    public override async Task<IDisplayResult> UpdateAsync(CommonPart part, UpdatePartEditorContext context)
    {
        if (!await _passport.AuthorizeAsync(StandardPermissions.SiteOwner, part))
        {
            return null;
        }

        var settings = context.TypePartDefinition.GetSettings<CommonPartSettings>();

        if (!settings.DisplayOwnerEditor)
        {
            if (part.ContentItem.Owner == null)
            {
                part.ContentItem.Owner = await _passport.UserIdAsync();
            }
        }
        else
        {
            var model = new OwnerEditorViewModel();

            if (part.ContentItem.Owner != null)
            {
                var user = await _userManager.FindByIdAsync(part.ContentItem.Owner);
                model.OwnerName = user.UserName;
            }

            var priorOwnerName = model.OwnerName;
            await context.Updater.TryUpdateModelAsync(model, Prefix);

            if (model.OwnerName != priorOwnerName)
            {
                var newOwner = await _userManager.FindByNameAsync(model.OwnerName);

                if (newOwner == null)
                {
                    context.Updater.ModelState.AddModelError("CommonPart.OwnerName", S["Invalid user name"]);
                }
                else
                {
                    part.ContentItem.Owner = await _userManager.GetUserIdAsync(newOwner);
                }
            }
        }

        return Edit(part, context);
    }
}
```

**Comment by hishamco** [comment]
I got what you mean, let us hear the feedback from others

**Comment by Piedone** [comment]
How about just a proxy service that exposes `IAuthorizationService` and `HttpContext` (or `IHttpContextAccessor`) as properties? You have one fewer injection but there's no need to maintain a duplicated API.

**Comment by hishamco** [comment]
>  along with IHttpContextAccessor the access the User object on the HttpContext to authorize the current principal

Again, for the current principal creating an extention method for `User` is enough, so no need to inject the `IAuthorizationService`

**Comment by hishamco** [comment]
>  along with IHttpContextAccessor the access the User object on the HttpContext to authorize the current principal

Again, for the current principal creating an extention method for `User` is enough, so no need to inject the `IAuthorizationService`

**Comment by ns8482e** [comment]
@CrestApps It's all about separation of duties `IAuthorizationService` is responsible with authorizing a given user for given resource - ( not necessarily limited to just logged in user )

where as, `IHttpContextAccessor` is related to current request and may not be available in background threads - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0#httpcontext-access-from-a-background-thread

Also to note that Drivers are not just tied to current request  - you could build and generate display in background thread for email purpose e.g. you may generate Approve link in email depending on whom you send email to in approval flow - that may could use same driver

**Comment by CrestApps** [comment]
> @CrestApps It's all about separation of duties `IAuthorizationService` is responsible with authorizing a given user for given resource - ( not necessarily limited to just logged in user )
> 
> where as, `IHttpContextAccessor` is related to current request and may not be available in background threads - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0#httpcontext-access-from-a-background-thread
> 
> Also to note that Drivers are not just tied to current request - you could build and generate display in background thread for email purpose e.g. you may generate Approve link in email depending on whom you send email to in approval flow - that may could use same driver

I get it. In these cases one would not use `IPassport` this service should be used when access to the `User` and `AuthenticationService` is needed. The idea here is to make thing easier and clean up the code a tiny bit.

**Comment by jtkech** [comment]
@ns8482e @CrestApps

Just for info, even if running in the context of a background task, we always provide an accessible HttpContext whose RequesServices are the Services of the current ShellScope, see in our `ModularBackgroundService.cs` where we create an HttpContext on which we do `httpContext.UseShellScopeServices()`, as we do when serving a request on a given tenant in `ModularTenantContainerMiddleware`.

But you would have to do the same yourself if you use a custom way to trigger background works.

**Comment by Skrypt** [comment]
Yes but this is a "fake" httpContext.

**Comment by jtkech** [comment]
> Yes but this is a "fake" httpContext

Yes, in the background we have no choice, this was just for info.

Hmm, but a custom background job may already have user related data or can be related to an already authorized action as for the PublishLater feature.

> That httpContext could have been easily renamed to BackgroundTaskContext.

For info, in the background we have an httpContext `IsBackground` item set to true.
