### ISSUE TITLE
Add option to prevent YesSql file locking

### ISSUE THREAD

**Issue by johnrom** [OrchardCMS/OrchardCore#11387]
I'm currently upgrading a project to .Net 6.0 and realized that I need to modify the configuration. Using the pooled Sqlite settings uses a lock which prevents our backup process from backing up the Sqlite db. I need to add `;Pooling=False` to the connection string, but it doesn't appear that there is an API for this.

On the cheap, even something as being able to configure `DatabaseFileName` would be fine, as we could overwrite `yessql.db` with `yessql.db;Pooling=False` (aka Connection String Injection) and then the connection string would be `Data Source=[etc]/yessql.db;Pooling=False;Cache=Shared`.

Not sure if this would conflict with the `PoolingJsonNetSerializer` or other assumptions that Orchard Core makes about the pooled nature of connections. If so, there should be a more involved way to configure Sql like `IOptions<OrchardCoreSqliteOptions>.Value.IsPooled`

**Comment by johnrom** [comment]
I reproduced the issue here as well. I was unable to get an unpooled and properly disposed connection from Orchard Core's YesSql db, but I was able to prevent pooling and locking on a custom YesSql instance as well as Sqlite itself. I also added a Sqlite that was configured for pooling and one which intentionally didn't dispose the connection even though it was unpooled, to prove they also have the same issue.

https://github.com/johnrom/orchard-core-issue-reproduction/tree/johnrom/repro-yessql-locking

**Comment by hishamco** [comment]
@johnrom can you propose your solution in YesSQL repo if there are changes need to be done internally?

**Comment by johnrom** [comment]
There are no changes required in YesSQL, it can be done by allowing the dev to configure the Connection String passed to `UseSqlLite()` as demonstrated [here](https://github.com/johnrom/orchard-core-issue-reproduction/blob/johnrom/repro-yessql-unlocked/OrchardCoreSqliteLockedTablesTest.Web/Startup.cs#L60-L68).

**Comment by johnrom** [comment]
PR here: https://github.com/OrchardCMS/OrchardCore/pull/11393
