### ISSUE TITLE
Let the recipe files use the json5 extension too

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore#11409]
### Is your feature request related to a problem? Please describe.
The JSON spec doesn't permit comments or trailing commas, however the [JSON5](https://json5.org/) spec does. Newtonsoft.Json already supports [almost the whole JSON5 featureset](https://twitter.com/jamesnk/status/1017528475534553088). Adding comments to the recipe files is [already a thing we do](https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/dev/Recipes/TrainingDemo.recipe.json#L2-L3) yet it makes most IDEs and the GitHub file viewer angry. This would be fixed by letting the devs rename the files to _*.recipe.json5_. The recipe file is already parsed via Newtonsoft.Json so there is no dependency change here.

### Describe the solution you'd like
Altering `OrchardCore.Recipes.Services.RecipeDeploymentTargetHandler.ImportFromFileAsync` and `OrchardCore.Deployment.Controllers.ImportController` to check if a file with the recipe code and `.recipe.json5` extension exists first.

### Describe alternatives you've considered
While researching the topic I didn't see completely clear answer as to whether the two missing features in the linked tweet has been added or not. If this is a deal breaker, I can do further research and address it upstream first. However I agree with JamesNK, that what devs care about is already there so we should use it.

**Comment by Skrypt** [comment]
The question is: does System.Text.Json will supports JSON5 specifications? Because the idea is to move most of the implementations in Orchard Core to use System.Text.Json when it will be mature enough for us. Else, we are adding more specifications that System.Text.Json needs to support and thus making the switch even more difficult.

Just saying. Else, this will only allow to open up .json5 files and see proper syntax highlighting? Newtonsoft currently ignores comments in json files.

@sebastienros

**Comment by DAud-IcI** [comment]
> does System.Text.Json will supports JSON5 specifications?

[Looks like System.Text.Json doesn't support it and they have no plan to either.](https://github.com/dotnet/runtime/issues/35251) I didn't know the plan is to migrate away from Json.Net. In that case feel free to close this suggestion.

> this will only allow to open up .json5 files and see proper syntax highlighting?

Yes, it would just be a tooling improvement.

**Comment by DAud-IcI** [comment]
No, json5 is more than just comments. For example trailing commas, or using apostrophe instead of quote when it makes sense (eg parsing serialised html attributes won't have to be escaped). System.Text.Json only supports comments and nothing else.

**Comment by Skrypt** [comment]
Ok then same question applies still. Does System.Text.Json supports JSON5?

**Comment by sebastienros** [comment]
I didn't read the issue correctly, I am fine with the suggestion of reading json5 extensions too.
But ... does it mean we wouldn't be able to migrate to STJ? Or at least as long as the json5 files would only contain comments (not sure to what extent STJ supports json5). Also this is not about renaming our current files.

**Comment by DAud-IcI** [comment]
Do you plan to completely drop Newtonsoft.Json in favor of STJ? Or to make either of them possible JSON backends? I think being able to choose serialization providers for the recipes would be pretty nice (not just JSON5 but other formats too, like the way IConfiguration can come from different providers). In this case STJ could be the preferred tool for JSON and Newtonsoft.JSON for JSON5. I'd be happy to look into it and contribute if you think that would be an interesting addition to OC.

If you intend to use STJ only, then the tooling will be imperfect either way: if you use JSON the comments will be incorrectly marked as error, if you use JSON5 the IDE will allow syntax the deserializer doesn't support (e.g. unquoted property names). In this case sticking with only .json is the safer bet.

> Also this is not about renaming our current files.

Agree.

**Comment by sebastienros** [comment]
Ultimately we want to get rid of NewtonSoft Json

**Comment by DAud-IcI** [comment]
Okay, then it's not a good idea for those circumstances. I will keep an eye out for System.Text.Json in case their stance on JSON5 (or any other JSON supersets) changes, and will report back if that happens. Closing the issue in the meantime.
