### ISSUE TITLE
suggest add dynamic module loader

### ISSUE THREAD

**Issue by a591537394** [OrchardCMS/OrchardCore#11408]
### Demand
We want to share our module, and the module can be as a plugin, be loaded directly in admin panle, just like the plugin of wordpress.

### What's useful of that feature?
Anyone are need money to keep live , the developer of orchard core is not excluded. in order to make the community running in a positive and automatic state, a simple way that can allow developer to create income is very important.
 
### The solution that i had considered
The modular solution of ABP Framework can be a reference, ABP modular can dynamic load plug-in modules in a specific folder. I think that may be a method to implement that demand. Wish orchard core become better , thank you.

**Comment by hishamco** [comment]
In Orchard Core we took a decision to not allow dynamic loading of modules, so all the modules should be added to the web application, run it, then you can make use of your new module

**Comment by a591537394** [comment]
aa...
Can i modify the framework to a hot plug-in modular framework and push to this place?

**Comment by hishamco** [comment]
It's Open Source, but you can't push here. But you can suggest this in [Orchard Core Contrib (OCC)](https://github.com/OrchardCoreContrib/OrchardCoreContrib)

**Comment by ns8482e** [comment]
@a591537394 Orchard core modules are nuget packages

you can add package reference in your project and use CI/CD pipeline to deploy your application
