### ISSUE TITLE
Liquid filters that render tags should have optional arguments to set custom attributes

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1140]
Like `attr-title: "foo", attr-placeholder: "bar"`

TODO: Look into shopify tag filter to see if this is a common practice.

**Comment by jtkech** [comment]
This makes me think first about some rules we could have for arguments, and maybe some simple utilities to implement these rules.

**Suggestions**

- We can have, but not necessarily, a default argument (an unnamed one) but only one and at the first position (index 0).

- If a named argument has the name of the default one, then we use it even if there is another unnamed argument at the first position which then would not be used. We could do the opposite but i think it's better to give a higher precedence to the named argument, especially if we could use extra arguments.

- All other arguments should be named and could have, depending on the specific implementation, a default value if not set.

- Named arguments which have not be used could be extra ones. E.g when rendering a tag we could assume that they are extra html attributes on which we would need to replace `_` to `-`.

- If no arguments is needed that's ok. And if we could have extra arguments they should be named.

- If we have only one argument, it can be a default unnamed one. But if it is a named argument it should have the correct name.

**Remaks based on the above**

- In `NamedHelperTag` we already do part of the above. In `BuildArguments()` if the first argument is not a named argument we assume it is the default argument. **But we don't check if a named argument with the default name has been passed**. Then other arguments should be named and that's ok.

- Note: with `NamedHelperTag` we already pass extra html attributes through the tag helper context.

- E.g in the `render_section` tag we indifferently use `arguments.At(0)` for the zone `name` parameter. **But as above we don't check if it has been passed at another position as a named argument**. Then other arguments need to be named and that's ok.

- Note: with `NamedHelperTag` we use `RegisterDefaultArgument()` to register a default argument name.

- In the `img_tag` there is.

      var alt = arguments.At(0).Or(arguments["tag"]);
      var css = arguments.At(1).Or(arguments["class"]);

    So here we could have 2 default unamed arguments which have (at a given position) a higher precedence. **But, as an example, the following will not work**.

      img_tag: class: "***", tag: "***"

    So here, maybe better to use

      var alt = arguments["tag"].Or(arguments.At(0));
      var css = arguments["class"].Or(arguments.At(1));

    But because at a given position we don't check the argument name (if it exists),  this would not work.

      img_tag: "***", other_attr: "***"

If you agree, i could refactor a little liquid tags and filters. Maybe i could add it to my current PR #1142. And maybe also replace the `img_tag` filter `tag` argument with an `alt` argument, related to #1109.

And then also implement optional arguments to set custom attributes, e.g for the `img_tag` filter.

But it depends on the rules we really want.
