### ISSUE TITLE
Taxonomy module

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1141]

**Comment by xperiandri** [comment]
What is the progress on this?
Is there at least Content Item picker?

**Comment by xperiandri** [comment]
Will this functionality have entity joining features?

**Comment by sebastienros** [comment]
`Entity joining` ? How is it different from taxonomies?

**Comment by xperiandri** [comment]
Maybe I don't understand what do you means by taxonomy interms of content definitions and documents.

**Comment by xperiandri** [comment]
How can I help in order to have this feature ready in July?

**Comment by sebastienros** [comment]
I am currently working on Taxonomies, I expect to finish it in the next couple weeks.

But you might actually need a Content Item Reference field. You could try to work on it but without prior experience it will be hard as it's not a simple one. I can do it after Taxonomies.

Is there someone else who wants to do it?

**Comment by xperiandri** [comment]
Lets store a link to first demo here https://youtu.be/N8BQtmpBFuo?t=40m8s

**Comment by xperiandri** [comment]
So this is how I modeled conference domain in terms of Orchard documents
![eaid_3b591c7e_9dba_4c1c_9412_923f1e83f6b1](https://user-images.githubusercontent.com/2365592/43742064-36e91194-99d9-11e8-9ebc-74553141428e.png)

Composition means nesting
Aggregation means dependency via foreign key like field

What I need is to query a Speaker, then all his/her sessions, then all slot bindings and finally slots and days connected to them.
Do you consider something like this?

**Comment by sebastienros** [comment]
You are shooting yourself in the foot! It's too complex. Not that it's incorrect, just that you can make it simpler by removing some concepts. For instance QA, just create a comments section using Disqus. Unless it's an editor only feature (no front-end editing experience). Conference Day can just be a field, and you can create a view for it with a lucene query.

But I can definitely see you'll need Taxonomy and/or content item reference field.

**Comment by xperiandri** [comment]
Day uses schedule.
A particular schedule can be reused for the other days.
Maybe it is unnecessary. I will see soon.

> or content item reference field

At least this would be extremely helpful
