### ISSUE TITLE
OrchardCore.Resources should not depend on ISiteService

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11423]
### Is your feature request related to a problem? Please describe.
I am trying to use `OrchardCore.ResourceManagement` in a standard ASP.NET project. I am using `OrchardCore.ResourceManagement` to deal with resources but would also like to use `OrchardCore.Resources` to provide me common resources to use. The issue here is that  `OrchardCore.Resources` depends `ISiteService` and that may couple the module with CMS data. 

### Describe the solution you'd like
IMHO, `OrchardCore.Resources` should not depend on `ISiteService` as that may couple the module with CMS data. I suggest we replace that with `IResourceSettingProvider` which provides the settings needed for the resource. Here is how I suggest we approach this

The following two file would probably go in `OrchardCore.ResourceManagement.Abstraction`
```
public interface IResourceSettingProvider
{
	public Task<ResourceSetting> GetAsync();
}

public class ResourceSetting
{
	public ResourceDebugMode ResourceDebugMode { get; set; }
    public bool UseCdn { get; set; }
    public string CdnBaseUrl { get; set; }
    public bool AppendVersion { get; set; } = true;
	public string ContentBasePath { get; set; } = String.Empty;
}
```
Then in the `OrchardCore.Resource` we would add default implementation of `IResourceSettingProvider` would read settings from the `appsettings.json`. Finally, in the `OrchardCore.Settings` we can add a different implementation that would replace the default implementation with one that reads from the `ISiteService`.

### Describe alternatives you've considered
I created my own module that does not depend on `ISiteService` because I don't need to bother with implementing it and in my module I added common resources like bootstrap

**Comment by Piedone** [comment]
This sounds interesting and I see the appeal. Note though that even with the current implementation you don't need CMS features if you want to use the module, you just need to implement `ISiteService` (and you don't need any CMS or DB feature for that).

**Comment by sebastienros** [comment]
> The following two file would probably go in OrchardCore.ResourceManagement.Abstraction

I agree.

Also I notivec that ResourceManagement depends on OrchardCore.Abstractions, can we remove that dependency?

**Comment by CrestApps** [comment]
@sebastienros the reason `OrchardCore.ResourceManagement` depends on `OrchardCore.Abstractions` is because of [IOrchardHelper extension](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.ResourceManagement/Razor/ResourceCdnHelperExtensions.cs#L13)

If we removed the dependency, where would you relocate the `ResourceUrl()` extension to?

**Comment by ns8482e** [comment]
IMO this dependency is fine, it's just that `ISiteService` needs to move to `OrchardCore.Abstrations` and provide another config based implementation for Framework.

**Comment by CrestApps** [comment]
@ns8482e I think `ISiteService` should live in `OrchardCore.Abstraction` as per your recommendation. But, if we do that we'll also have to move `ISite`, `ResourceDebugMode` and `CacheMode` to `OrchardCore.Abstrations` which is a good idea IMO. However, I still think the `OrchardCore.ResourceManagement` should not need to depend on `ISiteServices` it just need couple settings out of it not the entire object. Why would we need to depend on a large object when it's not really needed. I think utilizing `IOptions<>` is a better use in this case.

Anyway, if moving `ISiteService`, `ISite`, `ResourceDebugMode` and `CacheMode` to `OrchardCore.Abstrations` is the recommended approach I can make the change to the existing PR #11569

**Comment by ns8482e** [comment]
IMHO it's okay to have `OrchardCore.ResourceManagement` depends on `ISite` as both are part of framework and `ISite` is a property in `RazorPage` which is also part for orchard core framework (display management)
