### ISSUE TITLE
Lucene: Document contains at least one immense term in field

### ISSUE THREAD

**Issue by devlife** [OrchardCMS/OrchardCore#11422]
### Describe the bug
Getting the below `ArgumentException` when trying to reset/rebuild a lucene index where one of the content items has very long text.

```
ArgumentException: Document contains at least one immense term in field="BlogPost.HtmlBody" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[3c 64 69 76 20 63 6c 61 73 73 3d 22 69 6e 73 69 67 68 74 2d 61 72 74 69 63 6c 65 73 2d 77]...' at Lucene.Net.Index.DocInverterPerField.ProcessFields(IIndexableField[] fields, Int32 count)
```

### To Reproduce
1. Create a site for the blog theme
2. If one does not already exist, create an index for `Blog Post`
3. Create a query which will use the index in step 2
```
{
    "query": {
          "bool": {
                  "must": [
                          {
                              "match": {
                                  "BlogPost.Tags": {
                                      "query":"{% for tag in tags %}{{tag}} {% endfor %}",
                                      "operator": "or"
                                  }
                              }
                          },
                  ],
              }
    },
    "sort": {
      "BlogPost.PostedDate": {
        "order": "desc",
        "type": "double"
      }
  	}
}
```
5. Make sure you have an extremely long blog post
6. Click Reset or Rebuild on the index and see the error

### Expected behavior
I would like to know if there is any way around this issue and/or if there is a way to identify which blog post or posts are responsible for this.

**Comment by Skrypt** [comment]
Of course, everything has its limits. Maybe we need to use a TextField here instead of a StringField. But, of course, if you change a Field from one type to the other then you need to rebuild the index so that it uses the proper Lucene Type in the Lucene document.

**Comment by devlife** [comment]
@Skrypt how do I go about using a TextField? Are you talking about changing the field type of the HtmlBody?

**Comment by sebastienros** [comment]
When we index the value in lucene we need to validate the length. I am very surprised that is a limit.
If there is really one then we can split it into multiple entries on the same field.

**Comment by devlife** [comment]
The current type is `HtmlField`. To be clear, are you saying I need to convert it to a `TextField`? I don't think the client would want to write blog posts in plain text.

**Comment by sebastienros** [comment]
I was referring to the current code that creates the entry in Lucene, it should detect it's too big (what's the limit, if there is actually one like you seem to show), and then split it in two values.

**Comment by sebastienros** [comment]
Another option to investigate is this InedxWriter option: https://knowledgebase.progress.com/articles/Article/Text-field-indexing-limit-in-Lucene#:~:text=The%20Lucene%20IndexWriter%20has%20a%20property%20called%20MaxFieldLength.,specified%20to%20be%20%22UNLIMITED%22%20which%20corresponds%20to%20Int32.MaxValue.

**Comment by Skrypt** [comment]
Lucene setting may be global or per index. Need to see.

**Comment by devlife** [comment]
Until we have a fix or a workaround I'm working with my client to potentially shorten the blog posts that are too long.

**Comment by Skrypt** [comment]
Sorry, been busy with other tasks. You can try to create a PR that I will review if you need this ASAP.

**Comment by devlife** [comment]
No worries. Lucene is definitely very unfamiliar to me so I would probably be more of a hinderance. If I get time I'll see what I can do but I have a workaround until this gets some traction.

**Comment by devlife** [comment]
@Skrypt So I added a new field (TextField) and put the HtmlBody content there instead of the HtmlField. However, now I'm getting the same error but for the TextField.

```

**Comment by sebastienros** [comment]
@devlife would you try to create a PR to fix the issue? there are two suggested solutions in this thread.

**Comment by devlife** [comment]
@sebastienros so I've spent some time looking into this and it seems like we _should_ be able to do something like `writer.SetMaxFieldLength()` but that doesn't exist even though it's in the docs.

https://lucenenet.apache.org/docs/3.0.3/d2/d1d/class_lucene_1_1_net_1_1_index_1_1_index_writer.html#a91be1a71d5a51f7232dc2b6f5e021d9e

https://lucenenet.apache.org/docs/3.0.3/d0/d90/_index_writer_8cs_source.html (line 1465)

What version of Lucene.Net are we using?

**Comment by sebastienros** [comment]
This repository, but I can't find this property, seems like obsoleted.

https://github.com/apache/lucenenet

So maybe try the other option, at this line https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/HtmlFieldIndexHandler.cs#L15

Split the value in multiple strings, and call the same line for each segment. It will add multiple values to the same field in lucene, which is supported.

**Comment by devlife** [comment]
This is so strange. it seems to be working with the TextField now. Just FYI. I'll try to get to the PR this week.

**Comment by devlife** [comment]
Here is the PR. I'm not quite sure how I can go about testing this. If you can give me some pointers of how I can test this particular change (ie. use my local version of OrchardCore instead of NuGet) I'll be happy to do that as well.

**Comment by jtkech** [comment]
Okay I'm closing it, @devlife when you will have time can you open a new issue with the enhancement label, you will better describe the goal of that new size limit setting than me ;)

See https://github.com/OrchardCMS/OrchardCore/pull/11630#issuecomment-1452131255
