### ISSUE TITLE
Themes menu should not have sub menu items

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#1143]
If we look closely the `Active Themes` sub menu item, it doesn't make sense because it has the active an non-active themes, it would be nice if we remove the sub menu item, so all the themes will be shown when we click the `Themes` menu

**Comment by pgy866** [comment]
I think we can add some custom templates later

**Comment by sebastienros** [comment]
the Active Themes pages lists all Enabled and non-enabled ones to be precise. Let's just remove the "Active" word.

**Comment by hishamco** [comment]
So what's the need of the sub menu in this case?!!

**Comment by sebastienros** [comment]
I can't find anything better than `active themes` for now.

**Comment by hishamco** [comment]
As I told you, no need for the sub menu at all, we can make it `Themes`

**Comment by sebastienros** [comment]
That would be ugly, and there will be more things in the future there

**Comment by hishamco** [comment]
Why it will be ugly? I saw many CMSs have such things, in the future if we need to any sub items, nothing stop us.  Believe it or not `Active Theme` doesn't make sense at all .. Am I right?
