### ISSUE TITLE
Disabling Resources Module Broke Site

### ISSUE THREAD

**Issue by dsghi** [OrchardCMS/OrchardCore#11451]
### Describe the bug
I was able to disable the Resources module without any warning and hosed my site. I know it's a dumb mistake, it was kind of a "turn it off and back on" thing I was thinking I could do. Please don't make fun of me. 😂

An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'OrchardCore.Recipes.Services.IRecipeMigrator' while attempting to activate 'OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget.ExportContentToDeploymentTargetMigrations'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)

### To Reproduce
1. Go to modules
2. Search for Resources
3. Click Disable
4. Cry

### Expected behavior
I expect that either 1) there is no option to disable a required module, or 2) a very mean error.

I see this discussed regarding[ another issue in the past](https://github.com/OrchardCMS/OrchardCore/issues/3403)

Total random thought - it would be nice if there was a "safe mode" if someone does disable things they shouldn't, or somehow they're corrupted or missing, there's still some kind of basic interface to allow for fixing.

**Comment by Skrypt** [comment]
You may have found a rabbit hole 🐰 and 🐇

**Comment by Skrypt** [comment]
But more seriously. Maybe the issue is that the recipe module requires the resource module to be enabled. We will need to push more tests.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/160529883-2a613c6a-d2a5-405d-908c-ff6d24729317.png)

**Comment by Skrypt** [comment]
One solution is to make it IsAlwaysEnabled = true in its manifest to prevent disabling it.
I think it is a necessary module for most of the admin modules in OC.

**Comment by ns8482e** [comment]
Why not just have admin module depend on it ?
