### ISSUE TITLE
OrchardCore.Mvc.Web Sample Not Working

### ISSUE THREAD

**Issue by nfplee** [OrchardCMS/OrchardCore#1145]
If I clone the repository and then set the "OrchardCore.Mvc.Web" application as the startup project. When I run the application I get a blank page.

**Comment by piskernik** [comment]
You could try: https://github.com/OrchardCMS/OrchardCore.Samples as starting point. (It helped me).

**Comment by nfplee** [comment]
Thanks I found that as well and successfully have it working. However I'd like to step through the application to get a better understanding of how things work.

I took the sample above and added the NuGet package references as project references instead. However this didn't update the Packages directory when I built the application. After comparing the samples I added the following to the "ModularApplication.csproj" file:


<Import Project="..\..\OrchardCore\src\OrchardCore\OrchardCore.Application.Targets\OrchardCore.Application.Targets.targets" />

However now I get the following error when I do a build:

"The target "CopyPackageAssetFiles" does not exist in the project.
19>Done building project "Module1.csproj" -- FAILED."

**Comment by jtkech** [comment]
@nfplee 

Just tried `OrchardCore.Mvc.Web` it works but currently i'm based on the dev branch.

When an app reference `OrchardCore.Application.***.Targets` as a project, you also need to import at least the following, e.g see in our web app `.csproj` file.

    <Import Project="..\OrchardCore\OrchardCore.Application.Targets\OrchardCore.Application.Targets.targets" />


When a module reference `OrchardCore.Module.Targets` as a project, you also need at least to import

    <Import Project="..\OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.props" />

See in `OrchardCore.Modules/Directory.Build.props`. This is why it is automatically done for our modules.

**Comment by nfplee** [comment]
Thanks @jtkech. I've now got this working. I guess you can close this if it's working in the dev branch. Just a small question. How come you don't have to make the manual import if you reference the NuGet package?

**Comment by jtkech** [comment]
The trick is done through msbuild .csproj, .props and .targets files of the related projects, see in these files.

- Particularly they define some `PackagePath` so when they are packed the packages embed part of their own .props / .targets files. Note: a module also embeds its asset files (e.g content files and views).

- When referenced as packages the embedded msbuild files participate of the building of the main app.

- When referenced as projects each one has its own building process. So, we need to import some files.
