### ISSUE TITLE
Feature Request: view、 layout、Edit Template Editor Suggestions  and Code helper

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1146]
**Feature Request**: **view**、 **layout**、**Edit Template Editor Suggestions**  and **Code helper**.

A bit like the following picture in the function, do not know whether to consider adding such a function?

I am sorry！
Machine translation!
I hope the meaning of machine translation is conveyed clearly。

![layout helper](https://user-images.githubusercontent.com/28694676/32133323-2556c39a-bc08-11e7-85fc-ea2f9418e96e.gif)

**Comment by agriffard** [comment]
The Template editor already exists and allow to add alternates to content types or parts or widgets based on naming conventions (see http://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Templates/README/) but this is the **Liquid syntax** that is used.

OrchardCore won't provide an admin feature that allows to edit the Razor code of the views (.cshtml files) for a matter of security.

**Comment by pgy866** [comment]
@agriffard  Thank you for your enthusiastic reply!
