### ISSUE TITLE
Tag helper for validation error not functioning

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#11469]
Trying to add custom css class with the  ValidationMessageTagHelper  does not apply the proper class came.
Seems the issue is with this line :
https://github.com/OrchardCMS/OrchardCore/blob/ee83d3298867afe9f5e52115110ef09e6fc7f4ba/src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ValidationMessageTagHelper.cs#L64

**Comment by sebastienros** [comment]
Can someone confirm the issue and fix before we merge it?

**Comment by jtkech** [comment]
Just tried, I can confirm the issue and fix
