### ISSUE TITLE
Validation hooks were not performed when the content is publishing

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11466]
In `DefaultContentManager`
`PublishAsync` only fires the `PublishingAsync` and `PublishedAsync` events in the handler
But more often than not we want it to trigger all the necessary life cycles sequentially
For example, I want to execute its ValidateAsync before publishing

![image](https://user-images.githubusercontent.com/15613121/160967439-53d3f881-d8cc-4e15-90ca-2fb7d89329d2.png)

**Comment by hyzx86** [comment]
When I tried to override `DefaultContentManager`, I found that some properties were declared Internal, making them inaccessible to external assemblies
![image](https://user-images.githubusercontent.com/15613121/160968764-8f9e7c15-2bdf-4a8d-88f6-32c8a6fa0e97.png)

![image](https://user-images.githubusercontent.com/15613121/160969178-225f839c-0cc6-454e-8c1f-cda14182a4d4.png)

**Comment by ns8482e** [comment]
@hyzx86 when you publish you actually publish successful saved draft version that is already validated

**Comment by hyzx86** [comment]
> @hyzx86 when you publish you actually publish successful saved draft version that is already validated

But my type only wants it to validate ~ when it is in effect
Luckily I did it this way ：

![image](https://user-images.githubusercontent.com/15613121/160974113-0d9f94f6-52dd-4072-a826-f8119f0784c9.png)

But the notify is 🤣..

![image](https://user-images.githubusercontent.com/15613121/160974471-caa6879b-fb2f-4377-bc21-f27001320c77.png)

**Comment by jtkech** [comment]
We already have ValidateAsync() helpers that we use for example in the API controller of the OC.Contents module

**Comment by hyzx86** [comment]
> We already have ValidateAsync() helpers that we use for example in the API controller of the OC.Contents module

Yes, Thanks ，The prompt on the MVC page doesn't matter to me, I use the SPA mode
I have tested the content api controller , it is  work fine

![image](https://user-images.githubusercontent.com/15613121/160980321-895d2b8e-6c75-4bd1-8584-d99e777cf207.png)

**Comment by hyzx86** [comment]
Whole file

``` C#

using EasyOC.OrchardCore.OpenApi.Indexs;
using EasyOC.OrchardCore.OpenApi.Model;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using OrchardCore.ContentManagement;
using OrchardCore.ContentManagement.Handlers;
using OrchardCore.DisplayManagement.Notify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using YesSql;

namespace EasyOC.OrchardCore.OpenApi.Handlers
{
    public class VbenMenuHandler : ContentPartHandler<VbenMenuPart>
    {
        private readonly IFreeSql _freeSql;
        private readonly INotifier _notifier;
        private readonly IHtmlLocalizer H;
        public VbenMenuHandler(IFreeSql freeSql, INotifier notifier,
            IHtmlLocalizer<VbenMenuHandler> h)
        {
            _freeSql = freeSql;
            _notifier = notifier;
            H = h;
        }

        public override async Task PublishingAsync(PublishContentContext context, VbenMenuPart instance)
        {
            var validateResult = await CheckRoutePath(instance);
            if (validateResult.Any())
            {
                await _notifier.ErrorAsync(H["The RoutePath is duplicated with ：{0}", validateResult.JoinAsString(",")]);
                context.Cancel = true;
                return;
            }
            await base.PublishingAsync(context, instance);
        }

        public override async Task ValidatingAsync(ValidateContentContext context, VbenMenuPart instance)
        {
            var existsMenu = await CheckRoutePath(instance);
            if (existsMenu.Any())
            {
                context.Fail($"The RoutePath is duplicated with ：{existsMenu.FirstOrDefault()}", "MenuName");
                return;
            }
            await base.ValidatingAsync(context, instance);
        }
        private async Task<List<string>> CheckRoutePath(VbenMenuPart context)
        {
            var part = context.ContentItem.As<VbenMenuPart>();
            if (part.ContentItem.Latest && part.RoutePath is not null)
            {
                var parentId = part.ParentMenu.ContentItemIds.FirstOrDefault();
                var existsMenu = await _freeSql.Select<VbenMenuPartIndex>().Where(x => x.Published && x.Latest
                                  //limit in same parent
                                  && parentId == x.ParentMenu && part.RoutePath.Text.ToLower() == x.RoutePath
                                  && part.ContentItem.ContentItemId != x.ContentItemId)
                                    .ToListAsync(x => x.MenuName);

                return existsMenu;
            }
            else
            {
                return default;
            }
        }
    }
}

```

**Comment by Piedone** [comment]
Strangely, `ValidateAsync()` is only called from `CreateContentItemVersionAsync` and `UpdateContentItemVersionAsync`, and when called explicitly for a content item by the consumer, like [here](https://github.com/OrchardCMS/OrchardCore/blob/125fd39f0b11b7fe4d1392a37664085b3bc2dc55/src/OrchardCore.Modules/OrchardCore.Contents/Scripting/ContentMethodsProvider.cs#L27).

We should probably call it for all content operations.

This has been confusing for @MarGraz too: https://github.com/OrchardCMS/OrchardCore/discussions/15952.

**Comment by hyzx86** [comment]
> @hyzx86 when you publish you actually publish successful saved draft version that is already validated 

It seems that the validation process now has to be done after the save, so if we need to validate before entering the database do we have to implement a separate event?
