### ISSUE TITLE
How about enabling  Content Field SQL Index on each field? Just like the Lucene Index

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11467]
It is currently too expensive to enable Content Field SQL Index
If I have 10 fields to update
If you update 100 data
Plus ContentItemIndex
So it's going to produce at least 100 times 11 Update/insert statement

**Comment by hyzx86** [comment]
In addition, the current ContentField_Index table should be optimized
For example, fields like Published Latest already exist in ContentItemIndex
We can bring it out directly by using the Join query

**Comment by giannik** [comment]
We discused this here:
https://github.com/OrchardCMS/OrchardCore/issues/8869

**Comment by hyzx86** [comment]
> We discused this here: #8869

got it
