### ISSUE TITLE
Pager alternate

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1147]
I want to customize the pager shape of a Blog ListPart in a custom theme.

So I tried to change the ListPart-Blog.liquid like this to change the ItemClasses property :
```
{% for item in Model.ContentItems %}
    {% display item %}
{% endfor %}

{% assign previousText = "← Newer Posts" | t %}
{% assign nextText = "Older Posts →" | t %}
{% assign previousClass = "previous" | t %}
{% assign nextClass = "next" | t %}
{% assign itemClasses = "page-item" | split: " " %}

{% display Model.Pager | set_properties: previous_text: previousText,
    next_text: nextText, previous_class: previousClass, next_class: nextClass, item_classes: itemClasses %}
```

but it returns an error :
`InvalidCastException: Object must implement IConvertible.`

The next goal is to obtain a pager like this one so that it is correctly deisplayed with Bootstrap :
```
<ul class="pagination">
  <li class="page-item">
    <a href="/blog?after=635352192000000000" class="page-link">Older Posts</a>
  </li>
</ul> 
```
but I don't know what I can change in the view because the 'pager' class is added in PagerShapes.cs l 242 :
`Shape.Classes.Add("pager");`
and the available properties don't allow me to specify the class of the `<ul>`, `<li>` and `<a>` :
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Navigation/README/#pagerslim

**Comment by jtkech** [comment]
For the `ItemClasses` i fixed it. As other fixes all related to liquid, right now i put it in my current PR #1142 (see my comment), so if you want to try it. Maybe i will need to open other PRs.

**Comment by agriffard** [comment]
see also #547

**Comment by agriffard** [comment]
Add 'ListPart' template : 
```
{% for item in Model.ContentItems %}
    {% display item | build_display: "Summary" %}
{% endfor %}

{% assign previousText = "← Newer Posts" | t %}
{% assign nextText = "Older Posts →" | t %}
{% assign previousClass = "previous" | t %}
{% assign nextClass = "next" | t %}
{% assign itemClasses = "page-item" | split: " " %}

{% display Model.Pager | add_classes: "pagination" | set_properties: previous_text: previousText, next_text: nextText, previous_class: previousClass, next_class: nextClass, item_classes: itemClasses %}
```

Add Pager_Next and Pager_Previous templates :
`{% display Model | clear_alternates | add_classes: "page-link" | shape_type: "Pager_Link" %}`
