### ISSUE TITLE
OpenID Token validity 

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#11477]
### Describe the bug
Described in https://github.com/OrchardCMS/OrchardCore/discussions/11476

It seems that token validity is incorrectly stored in database.

### To Reproduce
1. call endpoint connect/token at time T+0
2. client app stores expiration time as datetime.now + expiration_time returned from cms (returns timespan > 1h)
3. if you check database, token CreationDate is T+n (as for me, 0 < n < 15 minutes)
4. ExpirationTime is CreationTime + 1 hour => T+n+1hour
5. When you call api after T+1hour, it returns 401 status code, but expiration time returned from OC is T+n+1 hour, so client app waits for this time to elapse and then gets token
6. after T+n+1 hour, client app regenerates token and app works ok. 

### Screenshots

![image](https://user-images.githubusercontent.com/52829889/161298843-b87df8df-5b82-4696-8b5b-964a17a0da12.png)

+ log 

```
2022-04-01 01:00:16.9427|....|INF|Start processing HTTP request POST "https://localhost:8000/connect/token"
2022-04-01 02:09:30.4606|....|Start processing HTTP request POST "https://localhost:8000/connect/token"
2022-04-01 03:09:30.4331|....|Start processing HTTP request POST "https://localhost:8000/api/graphql" ==> returns 401 (T+1 hour)
2022-04-01 03:20:30.4437|....|Start processing HTTP request POST "https://localhost:8000/connect/token" ==> gets new token (T+1+n)
2022-04-01 04:20:30.4431|....|Start processing HTTP request POST "https://localhost:8000/connect/token"
2022-04-01 05:20:30.4851|....|Start processing HTTP request POST "https://localhost:8000/api/graphql"  ==> returns 401 (T+1 hour)
2022-04-01 05:33:30.3932|....|Start processing HTTP request POST "https://localhost:8000/connect/token" ==> gets new token (T+1+n)

```

**Comment by Skrypt** [comment]
Are you in daylight saving time still?

**Comment by Skrypt** [comment]
Else, one thing I'm noticing is the fact that there could be some "offset time" where there is no token currently activated because it will try to generate one on the first request if there is none. So we can see here that the token that expires at 3:20 gets a refreshed token at 3:33 because of that.

**Comment by Skrypt** [comment]
Now, If I'm looking at the method in the OpenIdTokenStore.SetCreationDateAsync() method we store the value as UtcDateTime. No issue there.

If I'm looking at the method GetCreationDateAsync() we specify that the DateTime returned is of DateTimeKind.Utc. No issue there.

So, need to see where we are evaluating the client token vs the server token.

**Comment by MikeKry** [comment]
1/ Are you in daylight saving time still?
nope, we switched last week and I noticed this problem on more projects since then (but I wasn't looking for this error before, so it might have been there before) 

2/ ...So we can see here that the token that expires at 3:20 gets a refreshed token at 3:33 because of that.

Interesting thing is that the token that shloud expire at 3:20 really expired at 3:09, as seen in log:
`2022-04-01 03:09:30.4331|....|Start processing HTTP request POST "https://localhost:8000/api/graphql" ==> returns 401 (T+1 hour)`
 and when requested again at 3:20 it returns valid token, 
 `2022-04-01 03:20:30.4437|....|Start processing HTTP request POST "https://localhost:8000/connect/token" ==> gets new token (T+1+n)`
 but in DB it has creation date 3:33 instead of 3:20 (time that it was really generated).



So the problem is imho somewhere between creating token and storing it in DB: in reality created at 3:20, in database created at 3:33

**Comment by MikeKry** [comment]
@Skrypt  

thanks for help, it it is working okay - it seems that mentioned dates and times are just coincidences. 

Misinterpretation was caused by serilog configuration with Timestamp as mentioned in here https://docs.orchardcore.net/en/dev/docs/reference/core/Logging.Serilog/
is logging in server time, not UTC - so logs in DB are T-2 hours so the call at 03:20:30.4437 is in UTC 01:20.. 

So everything okay here - maybe worth updating serilog docs to mention time in utc as `{Timestamp:u}` (https://github.com/serilog/serilog/issues/1419) instead of `{Timestamp:yyyy-MM-dd HH:mm:ss.ffff}`

as I know, OrchardCore uses utc everywhere else, so it might be also in logs?
