### ISSUE TITLE
IOException: The process cannot access the file 'yessql.db' because it is being used by another process.

### ISSUE THREAD

**Issue by uussoft** [OrchardCMS/OrchardCore#11479]
When  delete the tenant, an IOException is thrown，IOException: The process cannot access the file 'yessql.db' because it is being used by another process.

**Comment by Skrypt** [comment]
That's expected if the application is running or if there is any process using the yessql.db file. If you delete a tenant you must also remove its folder in the App_Data folder manually else that may cause issues when trying to create a new tenant with the same name "default". So, we need to have exact repro steps to evaluate if there is anything we have to fix here.

**Comment by uussoft** [comment]
Thanks for your answer！
