### ISSUE TITLE
Using alternates on the front end with ContentPart_Edit causes shape rendering issues

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#11492]
I would like to render content items in edit mode for users  to create content items on the front end. 
So I've created front end alternates , similar to the backend , that are added to the alternates list when rendering on the front end (see below the alternates code).
Im having issues that seem very random concerning how the alternates are added when content item shape is created.
For instance when calling for the front end :
```
 var model = await _contentItemDisplayManager.BuildEditorAsync(contentItem, _updateModelAccessor.ModelUpdater, true);
```

Im am getting the following error  (not always but sometines ): 

![image](https://user-images.githubusercontent.com/1516981/161685325-30aef026-93fe-4b77-80e7-31f3a42e27c4.png)

While debugging Im seeing the error cause on this line :

 https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs#L276

Also noticing while debugging the the ordering of  alternates in the list for the content item is  now always the same  .

@jtkech  Could it have to do with the shape hierarchy ? Im seeing :

```
ContentPart-FrontEnd.Edit
   BagPart-FrontEnd.Edit
```
in the list of alternates as a hierarchy. Could it be confusing what model to pass into the  BagPart-FrontEnd causing the error ?

This is puzzling me for the last days , if anyione can point me in the right direction I would be gratefull.

**Code used for generating alternates on the front end** 

```
public class ContentPartEditAlternatesFrontEnd : IShapeTableProvider
{
    public void Discover(ShapeTableBuilder builder)
    {
        builder.Describe("ContentPart_Edit")
            .OnDisplaying(context =>
                {
                    var httpContextAccessor = context.ServiceProvider.GetRequiredService<IHttpContextAccessor>();
                    // Should only run on the front end not Admin
                    if (AdminAttribute.IsApplied(httpContextAccessor.HttpContext))
                    {
                        return;
                    }


                    var shape = context.Shape;
                    var contentTypePartDefinition =
                        shape.GetProperty<ContentTypePartDefinition>("ContentTypePartDefinition");
                    if (contentTypePartDefinition != null)

                    {
                        var partTypeName = contentTypePartDefinition.PartDefinition.Name;
                        var partName = contentTypePartDefinition.Name; // shape.ContentTypePartDefinition.Name;
                        var contentType =
                            contentTypePartDefinition.ContentTypeDefinition
                                .Name; // shape.ContentTypePartDefinition.ContentTypeDefinition.Name;
                        var isNamedPart = contentTypePartDefinition.PartDefinition.IsReusable() &&
                                          partName != partTypeName;
                        var shapeType = "ContentPart_Edit";

                        // ContentPart_Edit__[PartType]
                        // eg ContentPart-ServicePart-FrontEnd.Edit
                        context.Shape.Metadata.Alternates.Add($"{shapeType}__{partTypeName}__FrontEnd");

                        // ContentPart_Edit__[ContentType]__[PartType]
                        // e.g. ContentPart-LandingPage-ServicePart-FrontEnd.Edit
                        context.Shape.Metadata.Alternates.Add($"{shapeType}__{contentType}__{partTypeName}__FrontEnd");

                        if (isNamedPart)
                        {
                            // ContentPart_Edit__[ContentType]__[PartName]
                            // e.g. ContentPart-LandingPage-BillingService.Edit ContentPart-LandingPage-HelplineService-FrontEnd.Edit
                            context.Shape.Metadata.Alternates.Add($"{shapeType}__{contentType}__{partName}__FrontEnd");
                        }
                    }
                }
            );
    }
}
```

**Comment by sebastienros** [comment]
> I would like to render content items in edit mode for users to create content items on the front end.

Sorry, this was intentionally not designed for this. Many have asked and tried, this is not supported, I don't recall all the reasons but you will hit a wall. Only approach would be to duplicate a lot of logic and adapt to your needs. Zones for instance. All the current drivers won't match zones which are not from admin. Also the way we build editors with javascript and css for the admin.

**Comment by giannik** [comment]
thanks @sebastienros .
Just noticed that this happens in the admin too, so its not related to front end. 
Reported new issue here #11500
