### ISSUE TITLE
ContentPart_Edit alternates does not work when BagPart attached to content type

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#11500]
When creating a content type with a named bag part attached the ContentPart_Edit Alternates does not work 

To Reproduce
 1. In the Admin create a content type called OrderRequest 
 2. Also create a content type called OrderRequestLineItem
 3. In The OrderRequest content type add a named part of Bag with name Order Request Line Items (technical name: OrderRequest LineItems ) and add the content type **OrderRequestLineItem** as  a valid selection  from list
 4. In the admin in views folder  add a file  ContentPart-OrderRequest-OrderRequestLineItems.Edit.cshtml to override default implementation (copy the code from BagPart.Edit into here as it will be overiding this template)
 5. The following code is what adds this alternate 
 https://github.com/OrchardCMS/OrchardCore/blob/b9a8b1d62908b2770d35f5fc5c1fed9c9de47f2f/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentItemDisplayCoordinator.cs#L254

 7. In content items list click New : Order Request 
 8. You will see the following exception
![image](https://user-images.githubusercontent.com/1516981/162267947-c3047478-11c6-49a7-aa62-c64151facc97.png)

@ns8482e

**Comment by jtkech** [comment]
From memory, ContentPart alternates are mainly used for dynamic parts created from the Admin UI, so the shape/model is a Shape, can be casted `@model dynamic` at the first line, but that is not proxied (by Castle) to a dedicated view model type, here `BagPartEditViewModel`.

In your alternate you can still try to specify at the first line an `IShape` or dynamic model and then in the code try to convert it to the desired type `model as SomeViewModelType`, but I think it will not work.

But the more regular way to do that is to define custom editor modes (see the docs, they will be selectable through the part settings, configurable in migrations) that will use dedicated alternates, with the same view model types, or if you want to use adapted/other view model types you can define and register custom drivers to be used in these editor modes, and that will drive these custom view models (there are examples in the source repo).

**Comment by ns8482e** [comment]
> 4\. In the admin in views folder  add a file  ContentPart-OrderRequest-OrderRequestLineItems.Edit.cshtml to override default implementation (copy the code from BagPart.Edit into here as it will be overiding this template)

@giannik  At first glance ,

The line you referred adds alternate to  the shape `ContentPart_Edit` 

(https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentPart.Edit.cshtml) -  

Using content of  `BagPart_Edit` for `ContentPart-OrderRequest-OrderRequestLineItems.Edit.cshtml` is IMHO invalid override.
Verify shape metadata using `{{ Model.Content | console_log }}` 

I guess to override shape of `BagPart_Edit` following template is more relevant

https://docs.orchardcore.net/en/dev/docs/reference/modules/Templates/#contenttype_displaytype__partname
e.g. `OrderRequest_Edit__OrderRequestLineItems` or `OrderRequest-OrderRequestLineItems.Edit.cshtml`

**Comment by giannik** [comment]
So the ContentPart_Edit alternate is basically a wrapper around the actual concrete part (bagpart_edit in this case) and should not be used to override the concrete part.
Thanks guys, I get it,
