### ISSUE TITLE
Noobie: How to include menu in template?

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1153]
I am building a site using Orchard at the moment. How can I include a global menu in a template?

**Comment by agriffard** [comment]
Create it in the admin and based on the alias, you can use this liquid syntax :
`{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_duration: "00:05:00", cache_tag: "alias:main-menu" %}`

**Comment by dodyg** [comment]
Where can I shape the menu? I tried to create ```Content_Menu``` and ```Content_Summary_Menu``` template from the ```Menu``` Content Type definition but it has no effects.

**Comment by agriffard** [comment]
Look at TheBlogTheme views : Menu.liquid, MenuItem.liquid and MenuItemLink-LinkMenuItem.liquid

**Comment by dodyg** [comment]
How can I disable the cache for the ```{% shape %}```? Because right now I made a modification to menu.liquid and it picked up the changes. I edited one more time and it stopped picking up change.

**Comment by sebastienros** [comment]
@dodyg if you want to disable caching, then remove the `cache_duration` property, but this would be a bug that it's not taking the changes.

**Comment by dodyg** [comment]
First I use this 
```{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_duration: "00:05:00", cache_tag: "alias:main-menu" %}```

Then I edited the template to 

```
{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_duration: "00:00:00", cache_tag: "alias:main-menu" %}```

This change in cache duration did not change the behavior of the cache. I had to restart the application to make it always refresh.

**Comment by sebastienros** [comment]
Actually remove the `cache-id`. This is what starts the cached version discovery.
