### ISSUE TITLE
Workflow IfElseTask throwing exception when checking property with Single/Double quotes ('') blank string

### ISSUE THREAD

**Issue by MohitNaroliya** [OrchardCMS/OrchardCore#11530]
Workflow IfElseTask throwing exception when we are checking any property value blank with Single/Double quotes, I tried to debug on OrchardCore main branch source and found exception in WorkflowManager.cs file without any details in exception object.. 

![image](https://user-images.githubusercontent.com/26460323/163119885-588ae1df-9c4b-4200-a00c-a12775f493ac.png)

![image](https://user-images.githubusercontent.com/26460323/163120237-9057cde3-a55d-4e4f-8d5e-f916ce12604d.png)

### When I dig more in the inner methods and here is the highlighted line where throwing exception - 

![image](https://user-images.githubusercontent.com/26460323/163120702-11a6a6e9-0f5b-4476-a939-e0cd3395ddb5.png)

**Comment by MohitNaroliya** [comment]
We are using nuget OC version 1.3.0 packages.

**Comment by lampersky** [comment]
I assumed **IsTrue** is **BooleanField**, so you should change a bit your condition inside **IfElseTask** to

`property('ContentItem').Content.TestContentType.IsTrue.Value`

or 

`property('ContentItem').Content.TestContentType.IsTrue.Value === true`

![image](https://user-images.githubusercontent.com/6403130/163137477-95769062-9b60-490c-9e9a-d41ee2703981.png)

![image](https://user-images.githubusercontent.com/6403130/163137637-ccdb055a-640f-483a-b7b9-b31acb2b0777.png)

**Comment by lampersky** [comment]
other than that, I was able to reproduce your issue, when used wrong **condition**

![image](https://user-images.githubusercontent.com/6403130/163139346-6dac1858-89f0-414e-87ea-56c112301abf.png)

**Comment by MohitNaroliya** [comment]
Thanks @lampersky for your response.. I am having issue to check content property string value blank with following conditional statement - 'property('ContentItem').Content.TestContentType.IsTrue === ""'..

**Comment by lampersky** [comment]
if **IsTrue** is a TextField you should access its value this way:
`property('ContentItem').Content.TestContentType.TextField.Text != ''`
