### ISSUE TITLE
Auto Register generic IDisplayManager for framework

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#11547]
### Is your feature request related to a problem? Please describe.
In OC framework, to add display manager, we configure services for each type  as below eg

```cs
services.AddScoped<IDisplayManager<MenuItem>, DisplayManager<MenuItem>>();
services.AddScoped<IDisplayManager<User>, DisplayManager<User>>();
```

It seems redundant code to resolve services for `DisplayManager` for given type

### Describe the solution you'd like
Orchard builder should register generic display manager resolver as below similar to what its already done for `Documents`  [here](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.Infrastructure/Documents/OrchardCoreBuilderExtensions.cs#L18)

```cs
services.AddScoped(typeof(IDisplayManager<>), typeof(DisplayManager<>));
```

**Comment by sebastienros** [comment]
If everything still works then looks like a good idea.
