### ISSUE TITLE
Document Menu theming

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1154]

**Comment by agriffard** [comment]
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Navigation/README/ exists

**Comment by sebastienros** [comment]
It's unrelated, menus are here https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Menu/README/

Navigation is for the admin navigation.

**Comment by agriffard** [comment]
Pager shapes properties are in the Navigation Readme

**Comment by agriffard** [comment]
Move Pager shapes explanations to OrchardCore.Menu/ReadMe.md

Add examples of Menu, MenuItem and MenuItemLink-LinkMenuItem in Liquid and Razor.

**Comment by agriffard** [comment]
In OrchardCore.Navigation/ReadMe.md:
Add examples of Pager_Next and Pager_Previous.

In OrchardCore.ListPart/ReadMe.md:
Add examples of ListPart (alternates or templates) with custom pager.
Link to the Pager shapes explanations in Navigation.

**Comment by sebastienros** [comment]
TODO: Explain the alternates that can be used, and when showing examples in Razor/Liquid have them render the same thing. Also keep samples simple, and add more details as needed in other samples (for instance multi-level menus).
