### ISSUE TITLE
Feature attribute is not working for razor page

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#11558]
### Describe the bug
Feature attribute is not applied to razor page. Razor pages are always tied to the module.

### To Reproduce

1. Create a Module with a feature
2. Add a Razor Page
3. Add Feature attribute to razor page
4. Enable the module and the feature, it will serve Razor page
5. Disable Feature - notice that Razor page is still served.

### Expected behavior
When  feature is disabled it should not serve the Razor Page.

**Comment by hishamco** [comment]
Is this happening after the latest changes in module and feature attribute?

**Comment by Skrypt** [comment]
No I think he found a 🐛

**Comment by ns8482e** [comment]
No, I guess Views, and Pages are always tied to Module Id
