### ISSUE TITLE
Shortcodes - geneates empty lines

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#11563]
If you define shortcode with multiline definition, result contains newline characters.

for example this shortcode
```
{% capture output %} (HERE)
<iframe width="{{Args.width}}" height="{{Args.height}}" src="https://www.youtube-nocookie.com/embed/{{Content}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
{% endcapture %} (HERE)
{{ output | raw }}
```
gerenates result as "\r\n\r\n<iframe width...", \r\n comes from places marked as *(HERE)*, when you place everyting on one line, then it works ok.

Is there any way to remove/change this behavior? I want to have structured shortcode definitions, but newlines are causing formatting problems.

**Comment by hishamco** [comment]
I assume you got \r\n per new line

**Comment by MikeKry** [comment]
yes, for each newline it prints newlines to shortcode output - but I do not want them included in result, I want to print only content that is inside {%capture%}

**Comment by ns8482e** [comment]
@MikeKry  IMO that's how liquid - `capture`  takes complex strings and preserves all chars between    `{% capture %}` and  `{% endcapture %}`

have you tried  `strip` and `strip_newlines`  ?  https://shopify.github.io/liquid/filters/strip/

**Comment by MikeKry** [comment]
problem is not in newlines, that are captured by {capture}, but newlines that are around capture blocks (shortcodes get resolved as whole, not only "output" variable) 

for example this:
```
{% assign content_item = Content.ContentItemId[Args.id] %} (NEWLINE HERE)
(NEWLINE HERE)
{% capture output %}(NEWLINE HERE)
<a href="{{content_item.Content.AutoroutePart.Path }}">{{Content}}</a>
{% endcapture %}(NEWLINE HERE)
{{ output | sanitize_html | raw }}
```

prints  3 times \r\n before <a href> and 1 time after that. 

only solution I found is to remove all spaces and place it on one line, like this:

```
{% assign content_item = Content.ContentItemId[Args.id] %} (NEWLINE HERE){% capture output %}(NEWLINE HERE)<a href="{{content_item.Content.AutoroutePart.Path }}">{{Content}}</a>{% endcapture %}(NEWLINE HERE){{ output | sanitize_html | raw }}
```

**Comment by MikeKry** [comment]
but it is possible, that it is just how liquid works generally as here:
https://shopify.github.io/liquid/filters/strip_newlines/

in example, they have also two newlines before result (assuming it is copy of real output)
![image](https://user-images.githubusercontent.com/52829889/164460852-8eff37f0-62cd-446c-87b0-8fc0c243b908.png)

 but if I place it in liquid sandbox (e.g. here https://liquidsandbox.zweisolutions.com/) there are no newlines

**Comment by ns8482e** [comment]
@MikeKry as I said earlier liquid will take all the chars ( spaces and new lines) from your liquid template. 
See highlighted `newlines` below, all will be captured -  
 
![image](https://user-images.githubusercontent.com/23270244/164500361-1cd5ab2d-1510-4bfc-ba58-03b902d62c82.png)

**Comment by ns8482e** [comment]
This will remove leading and trailing `\r\n` from capture.

```liquid
{% capture output %}
<iframe width="{{Args.width}}" height="{{Args.height}}" 
        src="https://www.youtube-nocookie.com/embed/{{Content}}" 
        frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen ></iframe>
{% endcapture %}{{ output  | strip  | raw }}
```

**Comment by sebastienros** [comment]
Use `{% capture output -%}` which will ignore all whitespace after the end, and `{%- endcapture %}` which will remove all whitespace until the previous line. This is a standard feature of liquid that works on all the tags. https://shopify.github.io/liquid/basics/whitespace/

**Comment by sebastienros** [comment]
Please reopen if I didn't understand the issue correctly

**Comment by MikeKry** [comment]
@sebastienros 

Yes, that is exactly what I needed, thank you!

Seems like it is not a bug at all then..
