### ISSUE TITLE
Parsed Lucene query provider

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#11560]
### Is your feature request related to a problem? Please describe.
You can write elaborate [Lucene Queries](https://docs.orchardcore.net/en/latest/docs/reference/modules/Lucene/#lucene-queries) with the ElasticSearch DSL. This includes the `match` query type (akin to using the `my search term` syntax in the search box) and `match_all` (like writing `"my search term"` for exact search). And you can optionally use the parsed Lucene search syntax in the search text box. However, you can't combine the two, you can't add the ability to use the search syntax with a Query.

### Describe the solution you'd like
Add an `ILuceneQueryProvider` to address this.

### Describe alternatives you've considered
You can use simple search but then you loose out on Queries.

**Comment by Skrypt** [comment]
Have you tried using a Boolean query like a "must" == "AND" or "should" == "OR".

**Comment by Skrypt** [comment]
The match query also has an "operator" param which can be set to "AND" or "OR" (Default).

**Comment by Piedone** [comment]
I included "Lucene" in the title so you'd jump on it right away :D.

Yes, I tried those. I didn't clarify it, but this is not about coding the query by hand but allowing the usage of the [Query Parser Syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) so it can also come from a parameter. So, e.g. you can combine a search field with a more elaborate query to offer complex search.

I'll open a PR in a minute and you'll see :).

**Comment by sebastienros** [comment]
Question is what's the difference between QueryParser and MultiField query parser.

**Comment by Piedone** [comment]
Indeed, I've missed that (it's not in the docs, will add it) but it doesn't seem to work as I expect. E.g. this matches an item with the exact "exploration" word in its `Content.ContentItem.FullText` field.

```json
{
  "query":
  {
    "parsed": {
      "Content.ContentItem.FullText": {
        "query": "\"exploration\""
      }
    }
  }
}
```

This, however, doesn't match anything in the same index:

```json
{
  "query":
  {
    "query_string": {
      "query": "\"exploration\"",
      "default_field": "Content.ContentItem.FullText"
    }
  }
}
```

This works though:

```json
{
  "query":
  {
    "query_string": {
      "query": "Content.ContentItem.FullText:\"exploration\""
    }
  }
}
```

I fixed this in the linked PR. `simple_query_string` is also available but also missing from the docs, added it too.

It seems to me that the only difference notable here between `MultiFieldQueryParser` and `QueryParser` is that the former can query multiple fields at once with the field names supplied in its ctor. But that shouldn't be an issue because supposedly `QueryParser` supports that as too, as part of the query syntax.
