### ISSUE TITLE
Error displaying ListPart with liquid view or Template

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1157]
Since yesterday, I have an error when I was displaying the page of a Blog using a theme with .liquid views or Templates with liquid syntax.

Launching the application in Debug, there is a StackOverflowException in OrchardCore.DisplayManagement.Liquid\ LiquidViewTemplate.cs , line 172 :
`var displayHelperFactory = services.GetRequiredService<IDisplayHelperFactory>();`

**Comment by agriffard** [comment]
Other case: with an OC app suing the OC.Application.Cms.Targets Nuget package, if I updated to the latest preview version (1.0.0-beta1-3477), I also have an Error when I want to display a Blog. It has a custom Bootstrap theme with .liquid views.

**Comment by agriffard** [comment]
@jtkech : It must be related to the `HTTP Error 502.3 - Bad Gateway` I mentionned in #1142

**Comment by jtkech** [comment]
@agriffard 

Humm, `StackOverflowException` are you sure you don't display the same shape recursively. In #1142 you talked about a pager template, which one and which code?

Just tried the template `Pager_Next` i showed you.

    {% display Model | clear_alternates | add_classes: classes | shape_type: "Pager_Link" %}

Then i removed the `shape_type` so it displays itself recursively.

    {% display Model | clear_alternates | add_classes: classes | shape_type: "Pager_Link" %}

Then i got the following.

![http error 502 3](https://user-images.githubusercontent.com/8586360/32251756-b8c93360-be92-11e7-9267-8a193bc052f8.png)
![stackoverflowexception](https://user-images.githubusercontent.com/8586360/32251757-b8e9396c-be92-11e7-8c2c-208b0685f9e0.png)

**Comment by agriffard** [comment]
That is exactly what I have done indeed but then, even if I delete the templates, the error was still occurring.
I will recheck.

**Comment by agriffard** [comment]
The weird thing is that the error does not occur if I launch the application in Debug and there is this 502 error from the source of OC and also from an app using OC as nuget package.

**Comment by jtkech** [comment]
- First i updated my above example where i forgot to remove ` | shape_type: "Pager_Link"`. I did this to simulate a shape which displays itself and so on.

- **I'm quite sure that, as in this example, you have a liquid view which do an infinite loop like this**.

- While in dev we serve asset files from their project locations. So, if your views are correctly updated / removed from there, maybe that's why it's ok in Debug.

- When not in dev asset files are served from the `Packages` folder. Maybe there are not updated here. E.g if you only update views files in a project you would need to do a `ReBuild` on it before building the app, this to force the updated assets files to be copied under `Packages`. Note that this `ReBuild` is automatically done when publishing an app.

- Maybe you still have a template in your database which fails. In my example, to be able to restart the app i needed to delete manually the database templates record from the database.

**Comment by agriffard** [comment]
Ok, I also had all of these ideas to find where was the bug, so I did :
- Checked all the liquid views. None was changed.
- Remove all the templates but the Content_Landing one.
- Deleted the packages and rebuilt.
- Retried from scratch after deleting the App_Data and redone a setup with SqLite.
and always the same error and also with my app that uses OrchardCore.Application.CMS.Targets nuget package.

but I understand that if you don't have the bug anymore, this is something on my machine, I just need to find it.

Would there be an explanation about this bug not occuring in Debug?

**Comment by jtkech** [comment]
- There was an issue where it was failing only if not in dev. But it has been fixed about 15 days ago.

- So, as i understand with your app you can repro the issue in your local machine when not running in debug (e.g starting the app from the command line) and just after doing a fresh setup. Can you share your app, just to try it on my machine and see if i can repro?

**Comment by sebastienros** [comment]
Don't just delete app_Data, but do a `git clean -xdf`

**Comment by agriffard** [comment]
Ok, I just tried this (with the buildDisplay branch).

All cleaned.
Relaunch the setup.
Create site with TheAgency recipe and sqlite.
Go to admin and create a blog.
Go to http://localhost:2918/blog and the error 502.3 appears.

![image](https://user-images.githubusercontent.com/703248/32301551-b338a5b2-bf5e-11e7-84e1-732224d3ee9d.png)

**Comment by sebastienros** [comment]
well, you broke orcahrd, fix it now!

**Comment by sebastienros** [comment]
good job ;)

**Comment by agriffard** [comment]
I switched back to the dev branch and same error.

I also tried the same steps on another existing instance and another folder and guess what? .... same error.

**Comment by sebastienros** [comment]
Nothing in the logs?

**Comment by jtkech** [comment]
Just tried the same steps with the last dev and sqlite. Then `http://localhost:2918/blog` works.
But i trust you and i would be happy to understand what happens.

**Comment by agriffard** [comment]
Nothing in logs.

Tried again a setup with the blog recipe and of course, this is now the home that crashes.

If I launch with dotnet run, here is the error:
`Process is terminating due to StackOverflowException.` 

I had this 2 versions in C:\Program Files\dotnet\sdk : 
2.0.2-vspre-006949
2.1.1-preview-007094
I don't know why so I deleted them but no change.

dotnet --version is 2.0.2
VS version is 15.5.0 Preview 2.0

Good night.

**Comment by agriffard** [comment]
I deleted all the packages in {myuserfolder}\.nuget and rebuild but still the same error.

**Comment by sebastienros** [comment]
I am currently editing the ListPart for the Blog recipe and it works fine

**Comment by sebastienros** [comment]
Using this opportunity to refactor and to document how to theme lists.

**Comment by sebastienros** [comment]
Try again with the latest dev.

**Comment by agriffard** [comment]
I did a few more things: 
Delete packages NugetFallbackFolder in `.dotnet`
Delete remaining files about 2.0.2-vspre-006949 and 2.1.1-preview-007094 versions

After a restart, the error is not occuring anymore.

**Comment by jtkech** [comment]
@agriffard cool 👍
