### ISSUE TITLE
Markdown editor doesn't render email links with sanitization.

### ISSUE THREAD

**Issue by Psichorex** [OrchardCMS/OrchardCore#11594]
### Describe the bug
Markdown editor can't render email links properly when HtmlSanitization is turned to true.
You have to add a service configuration in the startup for Markdown to handle mailto links which is fine but angled bracket 
links should work without this config.
On deault none of these were rendering as links:

`<sample@sample.com>` This should work on default.
`[Link](mailto:sample@sample.com)`

### To Reproduce
1. Go to any content item that has a markdown field or markdown body (preferably one with Wysiwyg editor so can you can see
2. that the link you are trying to use is indeed a link as the editor will recognize it as a link.)
3. Click on the markdown editor an insert a link either of the 2 mentioned above.
5. Publish your content item and click on View to see whether the link is rendering on default.

### Expected behavior
The <> link should work without setting anything in code. Turning sanitization to false to resolve this is considered bad practice and it is highly disadvised.

**Comment by sebastienros** [comment]
Is it possible that the `mailto` prefix can be used to inject javascript?

**Comment by sebastienros** [comment]
There is an extensibility point in HtmlSanitizer: https://github.com/mganss/HtmlSanitizer?msclkid=feb7dd62c71811ecabe0ae4af8a34b76#uri-schemes-allowed-by-default

And there is a way to customize it with options:
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.Infrastructure/Html/HtmlSanitizerOptions.cs#L9
