### ISSUE TITLE
ShapeViewModel should have an overload that would accept the ShapeType

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11597]
### Is your feature request related to a problem? Please describe.
I need to create a shape manually using [ShapeViewModel<>](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.DisplayManagement/Views/ShapeViewModelOfT.cs#L5) directly. I had to do that in 2 steps
1. initialize mt shape 
2. Set the Type on the Metadata object.

### Describe the solution you'd like
I think `ShapeViewModelOfT` should have an overload constructor that would allow the consumer to provider a custom `shapeType`. I think we may want to event set the `Metadata.Type` on the current constructor so the Type is set by default.

**Comment by hishamco** [comment]
I like the idea

**Comment by ns8482e** [comment]
This is useful in case of generic types
