### ISSUE TITLE
Support a read-only behavior in content management screen

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11605]
### Is your feature request related to a problem? Please describe.
I have a need to give a specific role permission to edit some content types but view only other content types. To do that, I created a content type X and want to give U role access to ONLY view content (i.e., "View own X", "View X by others", "Preview X by others", and "List X content item(s) owner by all users"). These rules were not enough to show X in the manage contents screen. After testing, it turned out that in order for X to show up, I had to give "Edit X" permission which is not what I need here since I am trying to give read-only view.

Also, when I add X on AdminMenu, it does not show up unless the user has "publish or unpublished X" rule. At the very least for constancy, the same logic used in the manage admin screen should also apply on the AdminMenu. Sp if X appears on content-management it should also appear on AdminMenu and vice-versa.

### Describe the solution you'd like
I think both AdminMenu and content-management screens should be viewable if the user have "View own X", "View X by others", "Preview X by others", or "List X content item(s) owner by all users". Any of these permission should be enough to display content. View rules should be implied if one have edit, delete or publish permission "you can't delete, edit or publish if you can't view something". Making this change will easily add a view-only support to the contents in admin. I can't think of a good reason to not support view-only support in OC.

### Describe alternatives you've considered
Have not came up with a good iteam-

**Comment by sebastienros** [comment]
Probably what you described: don't hide the link to a content item if we have the View permission and not the Edit (currently we hide it). Then in the Edit screen hide the Save/Publish buttons if there is no Edit permission. We could optionally freeze all inputs (or read-only) but that might be hard to handle for everything and users would complain if one can't be read-only. If someone submits the form via API, there the controller is already checking the Edit permission.

**Comment by chinasqzl** [comment]
Why not use DetailAdmin?

**Comment by CrestApps** [comment]
@sebastienros can you please check out the changes I made in PR #11615. I think with that change we have support for the read-only scenario. 

One thing I can't seem to understand is how the permissions "View all content" and "View own content" as effective by default? As you can see in the screenshot below, there is no permission granted. Yet, the view permissions are effective. This is not a problem that I can see, but wondering how that is inherited. 

![image](https://user-images.githubusercontent.com/24724371/166004668-57b56ab9-4e74-4546-8ac2-2d4803970e70.png)

Anyhow, this is the final output where I am mixing some read only content (TestBlog) with editable content (TestProduct)
![image](https://user-images.githubusercontent.com/24724371/166059581-5ea4ca7c-8b9c-42b1-9e63-5cd4fb9ae591.png)


@chinasqzl not sure that I follow your suggestion.
