### ISSUE TITLE
Orchard adds spaces to my content part names - why, and how to disable?

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#11610]
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/11600

<div type='discussions-op-text'>

<sup>Originally posted by **andrerav** April 27, 2022</sup>
Hi,
When I create a content part with the name "SomeKindOfContentComponent", the technical name is split up at the uppercased characters, like so:

![image](https://user-images.githubusercontent.com/3635018/165540128-e3a8e3d8-7891-45aa-9951-fd7b9e62fe50.png)

Why is this, and how can I permanently disable it?</div>

**Comment by sebastienros** [comment]
Based on convention, should it be configurable?

**Comment by sebastienros** [comment]
@Skrypt tells me you can already use the Display Name, but we don't respect it apparently. We should use it if it's available.

**Comment by hishamco** [comment]
> And just use the technical name in technical screens.

Which screens are required technical names? IMHO display name is should used for the UI

**Comment by sebastienros** [comment]
@hishamco I am thinking about the screens where we manage the display name. So maybe only one place.
