### ISSUE TITLE
How can I simplify the updating and creation of content objects?

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11638]
I have a code for creating/saving content objects, the following code I copied from the content item management source code
Missing parts of code can cause some strange problems, such as not triggering `IContentHandler`
What I want to know is, can the following code be simplified?
Is there any API out there that can do this?

``` C#
  var doc = await YesSession.Query<ContentItem, ContentItemIndex>()
                .Where(x => x.Latest & x.Published)
                .With<DynamicIndexConfigDataIndex>()
                .Where(x => x.TypeName == model.TypeName)
                .FirstOrDefaultAsync();
            var createFlag = false;
            if (doc == null)
            {
                createFlag = true;
                doc = await ContentManager.NewAsync(nameof(DynamicIndexConfigSetting));
            }
            doc.Alter<DynamicIndexConfigSetting>(part =>
            {
                part.TableName = new TextField { Text = model.TableName };
                part.TypeName = new TextField { Text = model.TypeName };
                part.ConfigData = new TextField { Text = JsonConvert.SerializeObject(model.Fields) };
                part.EntityInfo = new TextField { Text = JsonConvert.SerializeObject(model.EntityInfo) };
            });
            ContentValidateResult result;
            if (createFlag)
            {
                result = await ContentManager.UpdateValidateAndCreateAsync(doc, VersionOptions.Draft);
            }
            else
            {
                await ContentManager.UpdateAsync(doc);
                result = await ContentManager.ValidateAsync(doc);
            }
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    await Notifier.ErrorAsync(H[error.ErrorMessage, error.MemberNames]);
                }
            } 
            else
           {
                    await ContentManager.PublishAsync(doc);
           }
```

**Comment by hyzx86** [comment]
In fact, I still can't confirm that all the above code is complete, I wonder if there is something missing

**Comment by hyzx86** [comment]
Normally, do you need to explicitly assign these two attributes before updating or creating content?

```
            contentItem.Latest = true;
            contentItem.Published = true;
``

**Comment by jtkech** [comment]
Overall looks good.

Published and Latest are managed by the content manager if the right methods are called.

You can follow what is done here.
https://github.com/OrchardCMS/OrchardCore/blob/219270423a566b8d9f9de39f97932b5e1d7213ae/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs#L88

**Comment by hyzx86** [comment]
@jtkech 
Thanks，But I don't know why TitlePart generation can't be triggered

**Comment by jtkech** [comment]
Hmm, because here drivers are not triggered, only handlers for validation.

You may need some additional code.

Need to leave, will take a look this night ;)

I may have some examples.

**Comment by jtkech** [comment]
All looks good ;)

Just saw that you use the `ContentItem.Alter<TPart>()` that mutate the part and apply it, good!

Not sure but about your `UserProfile` why not using the same technic in place of dealing with `JObjects`, knowing that `.Alter<TPart>()` uses `GetOrCreate()<TPart>()` (or you can use it explicitly).

**Comment by hyzx86** [comment]
> Not sure but about your `UserProfile` why not using the same technic in place of dealing with `JObjects`, knowing that `.Alter<TPart>()` uses `GetOrCreate()<TPart>()` (or you can use it explicitly).
Because I didn't notice it at first .
Later found that can be used in this way, since there is no error that do not change it 🤣


In this code, 'UserProfileInternal' is' CustomUserSettings' in user.properties
I want to copy all the information in UserProfileInternal to the normal type UserProfile
They will generate a map, 'UserProfile' can use Lucene and Grapql
In fact, in the original code, I initialized the contentitemId of the contentitem with the UserId


![image](https://user-images.githubusercontent.com/15613121/166863311-78bb09b1-6cb4-43ef-b701-b76b8db3b759.png)

**Comment by hyzx86** [comment]
@jtkech 
I've done some tests on updating the content object data, and they work,

```
 var user = context.User as User;
            var userProfileContent = user.As<ContentItem>("UserProfileInternal");
            if (userProfileContent == null)
            {
                return;
            }
            userProfileContent.ContentType = "UserProfile";
            var contentItem = await _contentManager.CloneAsync(userProfileContent); 
            contentItem.Remove("UserProfileInternal");
            //ContentPart must be registered manually
            contentItem.Alter<UserProfile>("UserProfile", profilePart =>
            {
                profilePart.UserName.Text = user.UserName;
                profilePart.Email.Text = user.Email;
                profilePart.UserId.Text = user.UserId;
                profilePart.OwnerUser.UserIds = new string[] { user.UserId };

                // The following code does not work
                //profilePart.GetOrCreate<TextField>("UserId").Text = user.UserId; 

            });
            
            contentItem.Owner = user.UserId;
            contentItem.ContentItemId = user.UserId;
            var existsContent = await _contentManager.GetAsync(user.UserId);
            var isCreate = existsContent == null;
            if (!isCreate)
            {
                contentItem = existsContent.Merge(contentItem, new JsonMergeSettings { MergeArrayHandling = MergeArrayHandling.Replace });
            }

            action?.Invoke(contentItem);
            await _contentManager.CreateOrUpdateAndPublishAsync(contentItem, isCreate, new PublishOptions
            {
                Notifier = notifier,
                HtmlLocalizer = htmlLocalizer
            });

```


The reason why TitlePart cannot be generated has also been found
Because I used two Orm frameworks in my project, I introduced FreeSql
Since the previous code created the DbConnection separately from the ConnectionString
The Sqlite database is locked.
I adjusted the code so that FreeSql uses Yessql DbConnection directly. Currently working well 😉

But it raises a new question:
Should code executed in ContentHandler roll back the state and throw an exception if an error is reported?
Currently, only logs are logged and no exception information is thrown.
If this occurs in a production environment, it is likely to affect the integrity of the business.

**Comment by hyzx86** [comment]
Thanks @jtkech ,   It was so difficult that I revised it many times afterwards. 🤣

This is what it looks like now.
 
```C#
  var user = context.User as User;
            var internalProfile = user.As<ContentItem>("UserProfileInternal");
            if (internalProfile == null && internalProfile.Content.UserProfilePart != null)
            {
                return;
            }
            var contentItem = await _contentManager.NewAsync(nameof(UserProfile));

            contentItem.Content["UserProfilePart"] = (internalProfile.Content.UserProfilePart as JObject).DeepClone();
            contentItem.Remove("UserProfileInternal");
            //ContentPart must be registered manually
            contentItem.Alter<UserProfile>(nameof(UserProfile), profilePart =>
            {
                profilePart.UserName.Text = user.UserName;
                profilePart.Email.Text = user.Email;
                profilePart.UserId.Text = user.UserId;
                profilePart.OwnerUser.UserIds = new string[] { user.UserId };

            });

            contentItem.Owner = user.UserId;
            var existsContent = await ((EOCDefaultContentManager)_contentManager).GetAsync(user.UserId, VersionOptions.DraftRequired);
            var isCreate = existsContent == null;
            if (!isCreate)
            {
                contentItem = existsContent.Merge(contentItem, new JsonMergeSettings { MergeArrayHandling = MergeArrayHandling.Replace });
            }
            contentItem.ContentItemId = user.UserId;

            await _contentManager.CreateOrUpdateAndPublishAsync(contentItem, isCreate, new PublishOptions
            {
                Notifier = notifier,
                HtmlLocalizer = htmlLocalizer
            });
```
