### ISSUE TITLE
Unable to set Media Text

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/OrchardCore#11639]
### Describe the bug
V1.3

MediaText icon above a selected image is disabled even though the Allow Media Text setting is true for that MediaPickerField.

### To Reproduce
1. Attach a MediaPickerField to a content type.
2. Select an image from the media libray
3. Can't set media text (alt text) for the image

### Expected behavior
Expect to be able to see a text box in a modal that allows for entry of media text for the selected image.

### Screenshots
![Screenshot 2022-05-04 at 14 01 18](https://user-images.githubusercontent.com/5065543/166686455-0859f510-95e2-4483-be17-92b38814f879.png)

**Comment by Skrypt** [comment]
You need to select the image and then click on the "bubble" icon.

**Comment by stevetayloruk** [comment]
wow!  I feel so dumb, but i have to say its not intuitive.  I (almost) tried everything to get it to work.  It does kinda make sense because of the potential to have multiple images loaded in.  

I think a better UI would be to associate the action with the actual image itself. So under or above each image you can set the text.

Thanks for the enlightenment @Skrypt
