### ISSUE TITLE
OrchardCore.Resource manifest contains incorrect definition for "tether"

### ISSUE THREAD

**Issue by bsamba** [OrchardCMS/OrchardCore#1163]
The code contains the following, which is incorrect (bold text):
 manifest
                .DefineScript("tether")
                .SetUrl("/OrchardCore.Resources/Scripts/tether.js", **"/OrchardCore.Resources/Scripts/bootstrap.js"**)
                .SetCdn("https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js", "https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.js")
                .SetVersion("1.4.0")
                ;

**Comment by agriffard** [comment]
Indeed, it should be 
`.SetUrl("/OrchardCore.Resources/Scripts/tether.min.js", "/OrchardCore.Resources/Scripts/tether.js")`
