### ISSUE TITLE
Cannot override OpenId views

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#11644]
It seems that views from openid module cannot be overriden by admin theme. 

I have used same steps as when overriding users module, which works correctly. 

![image](https://user-images.githubusercontent.com/52829889/166899230-dfede86f-2a9f-4677-9ee9-df1581b74548.png)

I have checked if areaname, controller name and action name is ok and I see no problem here.

Logout looks like this by default: 
![image](https://user-images.githubusercontent.com/52829889/166899482-39507310-9a6b-460b-a945-4c8d7daaeeff.png)

 Is it possible that it is not allowed to override or that I need site theme instead of admin theme? I am using headless recipe so I have no site theme active.

**Comment by MikeKry** [comment]
Ok, it really is overridable only by Site Theme..

2 questions:

1/ is it possible to somehow move / allow override of "site theme" views from admin theme? I would like to avoid creating of site themes
2/ if not, is it possible to use "BaseTheme" as in AdminThemes for SiteTheme? I do not really want to do anything with site theme as I have headless app.

**Comment by ns8482e** [comment]
@MikeKry if you are using headless you can out those files in web application and and set Layout to null

**Comment by hyzx86** [comment]
> I tried that also, but with no luck

Try to create a theme ，use `BaseTheme` property, it's very easy:

![image](https://user-images.githubusercontent.com/15613121/166940428-e047ee0f-d0e1-4d5d-9811-e9b594c8922b.png)

then you can replace you want：
![image](https://user-images.githubusercontent.com/15613121/166940870-9abb0539-26bf-4124-bd45-9c38af387694.png)

**Comment by sebastienros** [comment]
It has to come from the front-end theme.

**Comment by sebastienros** [comment]
What about a minimalistic theme with a layout that only renders the body? This way you could override the views in it.

**Comment by MikeKry** [comment]
Yes, I ended up with minimalistic FE theme with Layout containing only RenderBody function.
But I think its a wrong use of archirecture, headless ideally shall not have frontend active at all (but that does not work either currently, you can access content items on OrchardCore frontend even when you use headless)

**Comment by ns8482e** [comment]
> Yes, I ended up with minimalistic FE theme with Layout containing only RenderBody function.
> But I think its a wrong use of archirecture, headless ideally shall not have frontend active at all (but that does not work either currently, you can access content items on OrchardCore frontend even when you use headless)


As per prev comment You can have Set  layout to null e.g ` _Layout=null`

**Comment by MikeKry** [comment]
@ns8482e 

setting layout to null does not solve architecture issue of headless project containing FE theme :)

**Comment by sebastienros** [comment]
@vitalybrandes there is a feature that lets you write template from the admin directly (for the FE) so you don't need to create a custom theme. The templates are stored in database.

**Comment by vitalybrandes** [comment]
> @vitalybrandes there is a feature that lets you write template from the admin directly (for the FE) so you don't need to create a custom theme. The templates are stored in database.

Hi @sebastienros,
i am working in headless mode,
my UI build in Blazor, once i am trying to logout, the logout.cshtml  is presented.
I override this page in my own admin template but with no result.
Following this issue, looks like i cannot override this layout in admin template and need to add front theme for this.
I am wondering if there is any additional flow , expert this.
 As well this is relevant also for Authorize.cshtml layout.

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/214091967-562ad506-fdc0-4803-9aa0-577d6d217cc9.png)
In SPA , if you click the  button ‘No’ ,the page will redirect to orchardore‘s  home page

**Comment by hishamco** [comment]
> In SPA , if you click the button ‘No’ ,the page will redirect to orchardore‘s home page

Here you need to change the return URL / callback

**Comment by hyzx86** [comment]
Because the user did not consent. So it should go back to the previous page, right?
![image](https://user-images.githubusercontent.com/15613121/214094582-eafe8c2f-006c-4b86-9f3e-3c7b7d6ab444.png)

**Comment by vitalybrandes** [comment]
> ![image](https://user-images.githubusercontent.com/15613121/214091967-562ad506-fdc0-4803-9aa0-577d6d217cc9.png) In SPA , if you click the button ‘No’ ,the page will redirect to orchardore‘s home page Typically, we want the user to be able to return to the SPA program, or we can use implicit consent here, where the user simply confirms the exit in the SPA program

#13089

**Comment by ManOguaR** [comment]
ANYONE HAS SOLVED THE ISSUE OF OPENID VIEWS IN THEMES?
