### ISSUE TITLE
CodeMirror 5.65.2 SRI hashes are wrong

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#11646]
### Describe the bug
In OC 1.3 the codemirror.cs and codemirror.js files are failing the integrity check. It looks like the version may have been updated without also updating the SRI hashes.

### To Reproduce

1. Create a new OC 1.3 site using the blog theme
2. Check "Use framework CDN" at Admin/Settings/general
3. Edit the AutoroutePart settings for a BlogPost at Admin/ContentTypes/BlogPost/ContentParts/AutoroutePart/Edit

### Screenshots
![image](https://user-images.githubusercontent.com/68876423/166968075-fe00e62f-f57b-4e57-8692-178611cc0dd9.png)

![image](https://user-images.githubusercontent.com/68876423/166968090-9f09b7b8-ac77-4d5a-9d2d-007dcf0ab2d9.png)

**Comment by Skrypt** [comment]
I'm not sure if we should keep using the Codemirror editor while we have now the Monaco one.

**Comment by Skrypt** [comment]
We had issues where the SRI hashes changed for some reason as reported by @agriffard. I suggest that we do a PR and then release a 1.3.1 version with the patch as this is pretty important that it works.

**Comment by sebastienros** [comment]
Good thing we need to ship 1.4

Also, who wants to create a build step that verifies all the resources we have we shas on the CI?

**Comment by dsghi** [comment]
This is also causing #11388

**Comment by hishamco** [comment]
> It could be a unit test, since we can fake the services, resolve all resource, and download them this way.

I already did a PR long time for, that using source genrators, I think I need to continue work on it to avoid such SHA inconsistency
