### ISSUE TITLE
Should code executed in ContentHandler roll back the state and throw an exception if an error is reported

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11643]
Should code executed in ContentHandler roll back the state and throw an exception if an error is reported?
Currently, only logs are logged and no exception information is thrown.
If this occurs in a production environment, it is likely to affect the integrity of the business.

_Originally posted by @hyzx86 in https://github.com/OrchardCMS/OrchardCore/issues/11638#issuecomment-1118212732_

**Comment by hyzx86** [comment]
_session.CancelAsync()  Yes, I see  ,I have set up Freesql to use Yessql's DbConnection and DbTransaction
Freesql is also rolled back when _session.cancelAsync () is executed

But my idea is, can we write some code so that it can hook all the Handler methods
If an uncaught exception occurs, simply roll back the thing and notify "operation failed"
At present, it is a very embarrassing situation, I submitted, the prompt was successful, but the result is not correct.

**Comment by hyzx86** [comment]
Just like UnitOfWork

**Comment by jtkech** [comment]
> But my idea is, can we write some code so that it can hook all the Handler methods
If an uncaught exception occurs, simply roll back the thing and notify "operation failed"
At present, it is a very embarrassing situation, I submitted, the prompt was successful, but the result is not correct.

If an uncaught exception occurs the session will be canceled and then the transaction rolled back, but yes sometimes I need to add try/catch blocks, e.g. in a controller to populate a notifier.

        catch (Exception ex)
        {
            await _notifier.ErrorAsync(H["Failed to import Releases.<br/>{0}", ex.Message]);
            await _documentStore.CancelAsync();
        }

        return RedirectToAction(nameof(Index));

**Comment by hyzx86** [comment]
> If an uncaught exception occurs the session will be canceled and then the transaction rolled back, but yes sometimes I need to add try/catch blocks, e.g. in a controller to populate a notifier.

But I don't know why the method in Handler doesn't throw an exception when it executes

**Comment by jtkech** [comment]
From memory, when using editors, normally this is the drivers that validate (not handlers) when updating/binding. Outside editors, without using drivers, we use handlers to validate e.g. autoroute part (not all parts/fields have oob handlers that can validate).

We call drivers/handlers by using a safe `.InvokeAsync()` extension helper, so any exception from drivers/handlers are catched, we only log errors. So yes you are right, in that case we only have log errors.

We would need at least to have an invalid model state when using drivers, and validation result success equal to false when using handlers to validate.

Hum, it seems to me that there is already an opened issue related to this ;)

**Comment by hyzx86** [comment]
It is recommended that this be abstracted as an interface and that objects such as Logger Notify be injected automatically by specifying a type
The e other problem is the order in which it is executed, which so far does not seem manageable.
Although they may be automatically loaded in order of module dependencies, it may not be possible to customize the execution order of some Handles, although this could be improved by making it a class and abstracting out an interface

```C#
        public IEnumerable<IContentHandler> Handlers { get; private set; } 
        public IEnumerable<IContentHandler> ReversedHandlers { get; private set; } 
```

**Comment by hyzx86** [comment]
Hi @jtkech 

How about this implementation?

```C#
    public class HandlerExctuterBase<TriggerClass> : IHandlerExctuter<TriggerClass> where TriggerClass : class
    {
        private readonly INotifier _notifier;
        private readonly ILogger _logger;
        private readonly ISession _session;
        private readonly IHtmlLocalizer H;
        public HandlerExctuterBase(INotifier notifier, ILogger<TriggerClass> logger, IHtmlLocalizer<TriggerClass> h, ISession session)
        {
            _notifier = notifier;
            _logger = logger;
            H = h;
            _session = session;
        }
        protected virtual void HandleException(Exception ex, string sourceType, string method)
        {
            _notifier.ErrorAsync(H["Opration faild."]);

            if (_session.CurrentTransaction != null)
            {
                _session.CancelAsync();
            }
            if (IsLogged(ex))
            {
                _logger.LogError(ex, "{Type} thrown from {Method} by {Exception}",
                     sourceType,
                     method,
                     ex.GetType().Name);
            }
            if (ex.IsFatal())
            {
                throw ex;
            }
        }
```
use:

```C#
 // old
 await Handlers.InvokeAsync((handler, context) => handler.ImportingAsync(context), context, _logger);
 //new
await _handlerExctuter.InvokeAsync(Handlers, (handler, context) => handler.ImportingAsync(context), context);
```

I made a sample in my project

https://github.com/EasyOC/EasyOC/pull/18/commits/c48555a80f6002b539f2c05c3c40f622a5efd00f#diff-4fa945c101e1e264b29bd3d0e89c0a105157284aae6849f1083af347e5b0bed4

**Comment by jtkech** [comment]
Yes the concept looks good, you could suggest a PR so that we could review the details.

For info as I remember, about ordering dirvers/handlers are now enlisted in part options in module/feature startup, so in the order of startup executions, so ordered by dependencies. In a startup, for a given part you can remove/add drivers/handlers, you can also override a startup Order property, knowing that a module/feature can have multiple startups with different Order values. Note: sometimes `Xxxxed` dirvers/handlers are executed in a reverse order, but not always.

**Comment by hyzx86** [comment]
Ok, I will migrate to OC after I implement this function in EasyOC
