### ISSUE TITLE
Make DefaultContentManager as override able

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11655]
I wanted to rewrite The `DeaultContentManager`,  but there are some problems ：
1. Data is a property of the Internal modifier that prevents me from accessing this property in other assemblies 
2. Define all the methods in DefaultContentManager as virtual methods

![image](https://user-images.githubusercontent.com/15613121/167176889-415cfe34-481c-42eb-b72c-4d87022b841b.png)

**Comment by hishamco** [comment]
What sort of modifications you may change in the default implementation?

**Comment by ns8482e** [comment]
@hyzx86 why you would rewrite content manager?

**Comment by ns8482e** [comment]
There are other framework features available for CRUD of entity other than content item

**Comment by hyzx86** [comment]
Here I have create a PR ，but it still at there many days
https://github.com/OrchardCMS/OrchardCore/pull/11532

Here I created a PR, but it's still there for many days
I'm going to rewrite the bulk import function,
And some error event interception
OC's PR audit was so slow that I could only quickly implement these changes by modifying the code.
However, these Settings prevented me from overwriting some features

**Comment by hyzx86** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/11643

**Comment by hyzx86** [comment]
It seems to have been solved by internal invocation😂

![image](https://user-images.githubusercontent.com/15613121/167240739-557a0140-c921-4be1-b287-957767ba1ffa.png)
