### ISSUE TITLE
how to hide top nav bar during preview of page In Orchadcore CMS 

### ISSUE THREAD

**Issue by syedshadab19** [OrchardCMS/OrchardCore#11675]
Hi,

In the orchadcore cms i want to remove the top nav bar during preview of page. Please see the snapshot showcasing the top nav bar to be removed.

![image](https://user-images.githubusercontent.com/25971751/167673231-216cfcd0-c96e-4936-a5bc-4eb63afae2ec.png)

**Comment by sebastienros** [comment]
This nav bar should be part of the front-end theme.
What recipe are you using? What are the repro steps?

**Comment by syedshadab19** [comment]
The Recipe Being Used is "Software as a service"
Yes, the navbar is part of the front-end theme.

Reproduction Steps: 
Step 1 : Select content item in left hand menu and click on new to create a page.
![image](https://user-images.githubusercontent.com/25971751/168210677-9a5e3a3b-8c35-49bc-8c6d-35f599f8cf66.png)

Step 2 : After the content page has been created click on view 
![image](https://user-images.githubusercontent.com/25971751/168211091-61c00867-fb1a-4342-8abe-90208e2fd545.png)


Step 3: When the page is viewed I am getting the navbar as shown in the snapshot which I want to hide or remove when the page is viewed.
![image](https://user-images.githubusercontent.com/25971751/168211015-e1aebeda-b425-42ac-baa3-bc934265829e.png)

**Comment by Skrypt** [comment]
Can't you use then javascript to hide that Navbar that is inside the preview iframe?

**Comment by syedshadab19** [comment]
Can you please specify how to use javascript in the page

**Comment by sebastienros** [comment]
You need to create a new Theme project or copy an existing one and modify it.
https://docs.orchardcore.net/en/dev/docs/getting-started/theme

**Comment by syedshadab19** [comment]
Ok thank you will check the link.
Is there a way to remove it by using the features of orchadcore admin UI

**Comment by syedshadab19** [comment]
ok thank you Ill check it.

**Comment by syedshadab19** [comment]
Hi I checked the Theme Settings and I am unable to remove the theme completely can you please specify the steps?
