### ISSUE TITLE
the graphql is not support query latest and published content

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11688]
Should we add a `PublishedAndLatest` option or change an option to support the latest and Published versions by default?

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/168117397-a11637ce-2c28-4ed2-94f7-74e019228fd8.png)
![image](https://user-images.githubusercontent.com/15613121/168117409-b2f807ae-a3bf-4ac1-b013-6fb2fd1589f3.png)

**Comment by hyzx86** [comment]
Why update objects after saving.. Is this object already in the transaction?

In addition, I can't find the code to update the `latest` property

Because I use the spa program, is it only included in the MVC controller?

https://github.com/OrchardCMS/OrchardCore/blob/526816bbf6fc597c4910e560468b680ef14119ef/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L325-L329

**Comment by sebastienros** [comment]
Can you explain why you would want that?
Usually, we want to return either the Published version of a content item, or the Latest version. And optionally just the draft if it exists.

What you are suggesting is to be able to return the Published version only if there isn't a draft. And as soon as a draft is created, this would return nothing. I can't find a reason for that.

**Comment by hyzx86** [comment]
Hi @sebastienros ,
You mean if a content is published, it must be the latest, right?

**Comment by jtkech** [comment]
No, usualy when we want published items we don't care if they are latest

If an item is not published but is latest, it means that it is a draft, and that the published version (if exists) is no more latest. If latest = published = false, it means that it is soft deleted item.

**Comment by hyzx86** [comment]
got it,
That is, I don't need to care if it is the latest version. As long as it was a released version, ordinary users should be able to see it.
Therefore, when ordinary users used it, such as the pull down menu to check the data source, they only needed to restrict all the released versions

**Comment by hyzx86** [comment]
I made a list of content management using the graphql API,
Therefore, I hope that admin users can see all undeleted contents at the same time by default，
Jsut like `/Admin/Contents/ContentItems`
In this case, I can only modify the existing API or implement it with customized yessql

![image](https://user-images.githubusercontent.com/15613121/168202557-6c904a7f-719c-4301-af55-961cd77f180f.png)

**Comment by jtkech** [comment]
> Therefore, I hope that admin users can see all undeleted contents at the same time by default，
Jsut like /Admin/Contents/ContentItems

So what you would need is all items that are `Published OR Latest`

**Comment by hyzx86** [comment]
> So what you would need is all items that are `Published OR Latest`

Yes, filtering only published can also solve my last problem.

Now the new problem comes again..
That is the filtering of `Published OR Latest` ,

So I'm considering whether we should directly change published and latest to support optional filtering conditions in graphql

**Comment by Skrypt** [comment]
There is a method we use on server-side that is HasPublished() and HasDraft() maybe that is what you are missing.

**Comment by sebastienros** [comment]
> That is the filtering of `Publish OR Latest`

This is the same as `Latest`, proof:

```
	Draft + Published	Draft only 	Published only
P|L     Draft                   Draft           Published
L       Draft                   Draft           Published
```
