### ISSUE TITLE
Migrations Issue when upgrading from 1.0.0-rc2-13450 to 1.0.0

### ISSUE THREAD

**Issue by kgwadu** [OrchardCMS/OrchardCore#11695]
I am trying to upgrade an Orchard Core project from 1.0.0-rc2-13450 to 1.0.0. When i do this i get a series of migration errors ( shown below ). Have been trying desperately to figure out whats wrong and what a potential fix could be with no luck so far.

Any help would be GREATLY appreciated.

Error while running migration version 0 for 'OrchardCore.PublishLater'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

Error while running migration version 0 for 'OrchardCore.Taxonomies'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

An unhandled exception has occurred while executing the request. Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.

**Comment by Skrypt** [comment]
You can find the answer to that one in multiple issues reported in here. Do a search on UserId.
