### ISSUE TITLE
Script with PreRelease version

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#11701]
Related to #11700

In the Resource manifest file, if I declare a script with `.SetVersion("5.2.0-beta1");`, this TagHelper is not processed in the Layout:
`<script asp-name="bootstrap" version="5" at="Foot"></script>`

I need to remove `-beta1` to make it work.

**Comment by sebastienros** [comment]
Should we also add a new argument to no look at pre-release version (the current default apparently, maybe not on purpose).
