### ISSUE TITLE
When building a ContentItem Editor using GroupId, the parts driver never get called in 1.4-preview

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11718]
### Describe the bug
When using `IContentItemDisplayManager` build-editor for a specific GroupId, the drivers for each of the corresponding part never gets called. **This was not an issue in version 1.3 however it is an issue in 1.4-preview.**

### To Reproduce
1. Create a content part that generates special result when the `content.GroupId` is set to "test"
2. Create a content type and attach the content part you previously created
3. Now create a new controller to render the content-items under a specific GroupId
4. in the controller caller the driver like so

```
_displayManager.BuildEditorAsync(contentItem, _accessor.Updater, true, "true", "some-prefix")
```

### Expected behavior
The driver for each attached part would get called. Its then the driver responsibility to return something, nothing or something different when the groupId is set.

**Comment by ns8482e** [comment]
@Skrypt  @sebastienros @deanmarcussen  Just curious do we have any `ContentPart` editor in OC that targets specific GroupId. ? I guess the OOTB implementation is all on empty group.  

As in 1.4-preview `ContentPart_Edit` now supports placement and default implementation places it on empty group ("")

IMHO If module author needs to  place custom `ContentPart` editor shape on specific group, then dev has to also needs to bring the container `ContentPart_Edit` on to that group the `ContentPart` using placement rule

**Comment by ns8482e** [comment]
I know we have section driver that supports grouped but not sure if editing content items support it by default?

**Comment by Skrypt** [comment]
To be honest I need to wrap my head around the issue to understand it better. Maybe it is a missing implementation or a non-supported use case that just luckily ended up working.
