### ISSUE TITLE
Widget: How not to render the wrapper?

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1172]
Question: Is it possible to not render the `<article>` around a widget ?

Can I just use a Liquid Template to override the Widget view?

**Comment by jtkech** [comment]
`Widget` template

    <article class="{{ Model.Classes | join: " " }}">
        {% if Model.Header or Model.Meta %}
        <header>
            {% display Model.Header %}
            {% if Model.Meta %}
            <div class="metadata">
                {% display Model.Meta %}
            </div>
            {% endif %}
        </header>
        {% endif %}

        {% display Model.Content %}

        {% if Model.Footer %}
        <footer>
            {% display Model.Footer %}
        </footer>
        {% endif %}
    </article>

The only thing is that in the related razor view we have.

    var contentTypeClassName = ((string)Model.ContentItem.ContentType).HtmlClassify();

But we don't have an `html_classify` filter, maybe good to do it.

So, in place of having e.g `<article class="widget widget-html-widget html-widget">`.
With the above example we only get `<article class="widget widget-html-widget">`.

**Comment by sebastienros** [comment]
Close ?

**Comment by agriffard** [comment]
If I create a `Widget` template with this simple syntax:
`{% display Model.Content %}`
The `article` is not displayed anymote but the widget is still surrounded by these markups:
```
<div class="widget-container"> 
   <div class="field field-type-htmlfield field-name-html-widget-html-widget">
```
How can I also remove them in order to only have the raw content of the widget?

**Comment by sebastienros** [comment]
`Widget_Wrapper`

`{% display Model.Content %}`

**Comment by sebastienros** [comment]
It contains the logic to render the title based on the `Model.ContentItem.Content.LayerMetadata.RenderTitle` value and `Model.ContentItem.Content.LayerMetadata.Title`

**Comment by agriffard** [comment]
If I name the template `Widget_Wrapper`, it is not replaced.

**Comment by sebastienros** [comment]
This is an extra one

**Comment by sebastienros** [comment]
Note to my future self:
We might not need the `Widget_Wrapper` which is added automatically in the `LayerFilter`. After all if we need to change the html around a widget, we can already do so in the main stereotype template. But it might be harder as this would mean copy-pasting the whole thing. Or maybe just have an empty `Widget_Wrapper` template such that a theme can change it independently from the stereotype template. 

We should provide an alternate for the `Widget` shape that would be based on the zone name, such that we can change the template of a widget for each zone. And also do it for the wrapper if this is kept.
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Layers/Services/LayerFilter.cs#L114

**Comment by agriffard** [comment]
`Widget__RawHtml`
```
{% assign fields = Model.ContentItem.Content[Model.ContentItem.ContentType] %}
{{ fields.Content.Html | raw }}
```

**Comment by sebastienros** [comment]
Reopening for documentation tag

**Comment by agriffard** [comment]
Add ReadMe.md in OrchardCore.Widgets.

Explain what templates can be added to prevent the widgets from rendering the `<article>...` structure.
Ex: `Widget`
`{{ Model.Content | shape_render }}`

In TheTheme, as an example, we could add a Widget.cshtml alternate that would render just this:
`@await DisplayAsync(Model.Content)`

For the Widget_Wrapper.cshtml, we could just, by default, not surround it with `<div class="widget-container">`
