### ISSUE TITLE
Codemirror issue with SHA

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#11730]
![image](https://user-images.githubusercontent.com/3228637/169404015-5b94e7d8-a04b-463f-829d-a76dfb38f231.png)

**Comment by agriffard** [comment]
https://github.com/codemirror/CodeMirror/releases/tag/5.65.4

**Comment by Skrypt** [comment]
I let you do a PR @agriffard
This PR fixed the SHA issue. Works on Azure.
