### ISSUE TITLE
Add a way to prevent the user from managing content-type or content-part

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11736]
### Is your feature request related to a problem? Please describe.
Sometime I want to create a content type that is only manageable from code. For example, I want to create a creatable content type, but I don't want the admin to be able to change the structure of the content-type. Instead content-type would only be manageable via code (using migrations).

### Describe the solution you'd like
Adding `DisabledUserInterface` option to `ContentTypeSettings` and  `ContentPartSettings` which will be used by the UI to prevent one from managing it.

**Comment by hishamco** [comment]
> but I don't want the admin to be able to change the structure of the content-type

This is different from what "Is Creatable" means, if you set it to false no one can able to create your content item from the UI, but changing the structure is possible

For your case you could create a permission say "Manage Content Definition" that will be applied in the content definition pages. Please check first if there's such permission otherwise you need to have to

**Comment by hishamco** [comment]
As I can see, there's `EditContentTypes` permission available it may works for your case

**Comment by CrestApps** [comment]
@hishamco this has nothing to do with "Is Creatable". the "Is Creatable" would still be honored if the code generated type is configured with "Cretable()" option. The idea here is to prevent the admin from changing the structure of the content-type. Meaning an admin won't see the content type on the content types list. so no part can be added or removed "unless a module make the change from code"

The `EditContentTypes` would work only on a non-admin users. Again the idea is to prevent anyone from using the UI to manipulate the content-type. In some case, if an admin make a change to a specific content type, things would not work as expected. so in that case, I don't want to give the admin a way to break the function of a content-type.

**Comment by CrestApps** [comment]
@hishamco I updated the above with screenshots to give you visual

**Comment by hishamco** [comment]
> The EditContentTypes would work only on a non-admin users

Right, I think you can exculde the admin, let me try, Again add new option "Has UI" or "Manageable" can be doable but it should be applied through a permission. Don't forgot we allow to simplify the things from the UI without touching the code - I know there's cases when you need to write code -

**Comment by CrestApps** [comment]
@hishamco the idea is not to prevent the admin from editing contentypes, that would not be good. But to prevent a specific content-type from being available in the manage content-type in the UI. This would not change existing setup, but extends the function to allow for code managed content-types.

I don't think `HasUI()`, `Manageable()`, or `Listable()` are good names in this case since content-types HasUI, manageable or listable. However, `DisableUI(bool disableUI = true)` or `DisableUserInterface(bool disableUI = true)` would mean to explicitly disable the UI so you are not impacting existing function and not asking the user to apply `HasUI()` everywhere.

**Comment by sebastienros** [comment]
I suggest to use dynamic permissions on content type definitions and content part definitions, like `ManageContentType_{0}`, and `ManageContentTypes`.

**Comment by CrestApps** [comment]
@sebastienros  PR #11737 was updated to use permissions as per you suggestions. Thank you
