### ISSUE TITLE
OrchardCMS Admin panel loads really slow on Azure App Service (Linux) when using WebOptimizer

### ISSUE THREAD

**Issue by antonis-sna** [OrchardCMS/OrchardCore#11761]
I am using OrchardCMS (1.2.2) with SQL Server and everything works fine and smooth on my local machine. 

However, when I publish my solution to **Azure App Service** (net5.0, self-contained deployment mode, linux-x64), the admin panel loads forever. For example, the admin of my landing page content type takes almost 5-6 minutes to load. My App Service is hosted on Azure by using Basic Tier, 1 B1 (1 Core(s) with 1.75 GB RAM, 10 GB Storage) on Linux OS and all my resources (app service, sql server, database, etc.) are hosted on West Europe datacenters.

Below I attach a screenshot from the network tab of chrome developer tools, showing how long each request takes to complete:

![image](https://user-images.githubusercontent.com/8733981/170090015-e13b21db-98f1-40a4-8f36-c825ecd0f197.png)

Below I attach a screenshot of one random request:

![image](https://user-images.githubusercontent.com/8733981/170090294-e8213317-9562-4756-a120-1083c970388b.png)

Meanwhile, when I monitor the Log Stream from my Azure App Service I get multiple requests of this type:

```
File '/TheAdmin/js/TheAdmin.min.js' not found. Passing on to next middleware.
OrchardCore.Modules.ModularTenantRouterMiddleware[0]

File '/OrchardCore.Resources/Scripts/bootstrap-select.min.js' not found. Passing on to next middleware.
OrchardCore.Modules.ModularTenantRouterMiddleware[0]

File '/OrchardCore.Resources/Scripts/js.cookie.min.js' not found. Passing on to next middleware.
OrchardCore.Modules.ModularTenantRouterMiddleware[0]

...
```

On the other side, when I run my solution from my local machine with VS2022 on debug mode and I connect to the remote Azure SQL Server DB, everything loads fine, so it seems not a database connection problem. I should mention that my landing page loads fine and I haven't faced any issue with my front page, loading issues occur only when accessing the Orchard Admin panel.

Do I have to configure any special setting while publishing to Azure ? Has anyone faced any similar issue before? 

Thanks

**Comment by CrestApps** [comment]
Note sure this is going to help you much, but I would suggest you turn on the mini profiler feature on admin and see if that’ll give you additional data.

https://docs.orchardcore.net/en/latest/docs/reference/modules/MiniProfiler/


I would also enable SSH on your container and run tracert from the container to the database server “or other services you are using” to make sure the connection between the services is solid. You can also look at the networking logs in Azure to see if there is more clues 

I am using OC on azure service app using docker container and have no issues.

**Comment by ns8482e** [comment]
Are you using orchard source code or are you using nuge packages?

Aleo verify that your asp net core environment is not Development

**Comment by antonis-sna** [comment]
The following line from the Azure Log Stream got me suspicious:

`
2022-05-24T16:23:40.786293209Z WebOptimizer.AssetBuilder[1005]
`

So I removed the **LigerShark.WebOptimizer.Core** nuget package from my project and everything loads normally now. However, I really don't know why there was a conflict between the admin panel and **WebOptimizer**. 

In **Startup.cs** I had the following in **ConfigureServices()**:
`services.AddWebOptimizer(pipeline =>
 {
       pipeline.MinifyJsFiles();
       pipeline.MinifyCssFiles();
});
`

And in **Configure**():
`app.UseWebOptimizer();`

Also in **_ViewImports**:
`@addTagHelper *, WebOptimizer.Core`

Removing only the code parts did not fixed the issue. Removing the **entire** nuget library did.

Does anyone know why?

**Comment by Skrypt** [comment]
The "Use resources cache-busting" option will only change the URI if the assets have changed. If you are using the "response cache" then it might take some time before the page gets refreshed.

The minification option in the admin is only there to say: use the minified version of the assets if any is provided to the ResourceManager. It won't minify the assets for you; it needs to be minified manually with the gulp pipeline.

Here, when you are using the WebOptimizer you may need to use its own cache busting feature since you would then need to assert that our cache busting middleware is executed after the WebOptimizer one.

**Comment by antonis-sna** [comment]
> start a PR if you want

It's weird that this "delay" seems to happen only when I deploy to Azure and not on my local machine where it works perfectly fine while bundling, minifiing and cache busting all script and style files in both my landing page and admin panel.

I wish I find the strength to deal with this issue with a PR. Also, I don't know if this issue should be closed or stay open for anyone else who's struggling with similar problems.

**Comment by Skrypt** [comment]
Keep it open, it will get triaged tomorrow.

**Comment by antonis-sna** [comment]
I tried to use WebOptimizer as it runs simply as an out-of-the-box solution and I 've been already using it in older ASP.Net MVC projects. However, I 'll try to use gulp pipeline as you suggested. Thank you

**Comment by sebastienros** [comment]
Please reopen if you think there is still a bug in OC
