### ISSUE TITLE
Cannot use session state from a module 

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#11786]
I would like to use session state to create a wizard form experience storing data from each step in session state.
After following this article https://github.com/OrchardCMS/OrchardCore/discussions/8146 by @jtkech  I 
I registered 
```
 public override void ConfigureServices(IServiceCollection services)
        {
           services.AddMvc().AddSessionStateTempDataProvider(); 
            services.AddSession();
 
        }
   public override void Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
        {
            app.UseSession();

        }
```

Then got the following error in the **orchardcore.forms module**

![image](https://user-images.githubusercontent.com/1516981/171017366-74b3280c-0b2b-48ad-a6b8-90670a08bac2.png)

Even after disabling this  filter  from source code I still got an error from my module using session state

![image](https://user-images.githubusercontent.com/1516981/171017683-8b579966-0a00-4b94-8b52-75c595eb81d5.png)

 

**Here is my class that is trying to use Session State :** 

```
public class SessionRegisterUserSubscriptionPersistence : IRegisterUserSubscriptionPersistence
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private ISession Session => _httpContextAccessor?.HttpContext?.Session;

    public SessionRegisterUserSubscriptionPersistence(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;

    }
}
```

Anyone can help ? 
@jtkech

**Comment by ns8482e** [comment]
I guess you need to call use session before UseOrchardCore in host startup

**Comment by giannik** [comment]
I still got an error :
```
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Session.ISessionStore' while attempting to activate 'Microsoft.AspNetCore.Session.SessionMiddleware'
```


Guess I should try Memory cache to store temp state.

Thanks @ns8482e
