### ISSUE TITLE
Searching from a modal is not working

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11802]
### Describe the bug
Any modal in the admin page where search is available is a modal is no longer working.

### To Reproduce
1. Enable "Export Content To Deployment Target" feature
2. Click on "Configuration" >> "Import/Export" >> "Deployment Plans". 
3. Create a deployment or edit an existing one
4. Click "Add Step" button
5. In the modal "window" try searching for anything, nothing happens I am expecting the items to be narrowed down based on my search
![image](https://user-images.githubusercontent.com/24724371/172029571-92f7400f-b38c-44ff-b312-d39c1a0efeed.png)

Another way to see it,
1. Enable "Layer" feature
2. Click on "Design" >> "Widgets" >> click on "Add" under layer or edit existing one 
3. Create a deployment or edit an existing one
4. Click "Add" button to add a rule to the layer
5. In the modal "window" try searching for anything, nothing happens I am expecting the items to be narrowed down based on my search
![image](https://user-images.githubusercontent.com/24724371/172029673-5ad7b31d-d444-46e7-b470-22168808fa9e.png)

**Comment by hishamco** [comment]
Are you using 1.4 bits?

**Comment by CrestApps** [comment]
Yes

**Comment by hishamco** [comment]
I'm fetching the latest source, I will check this one

**Comment by hishamco** [comment]
I'm able to reproduce the issue
