### ISSUE TITLE
Validate table prefix before allowing new tenant to be added

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11803]
### Describe the bug
When adding a new tenant, we allow the user to set a prefix to the tables to enable reusing the same database for multiple tenets. However, we don't validate to ensure that the prefix isn't already used first. The problem with this is that it throws an exception

![Screenshot_6](https://user-images.githubusercontent.com/24724371/172030172-f77d709f-6512-4443-a091-b08b720c44b1.png)

### To Reproduce
1. Create 2 tenant on same database connection with the same prefix or both with no prefix.
2. Set up both tenants. you should see the exception when you set up the second tenant.

### Suggestion 
When creating the tenant, we should group existing connections by prefix. Then check to make sure the prefix isn't already used before allowing it.

I think this logic should be part of the `ITenantValidator` But I think the validation would have to be done per type/servername/databasename/prefix

**Comment by hishamco** [comment]
I remembered @jtkech mentioned the reason behind "Invalid Serial Number" long time ago, may be the tenant not loaded successfully

**Comment by Skrypt** [comment]
Maybe this should be part of YesSql, it needs to be evaluated.

**Comment by hishamco** [comment]
> Maybe this should be part of YesSql, it needs to be evaluated.

Let me check YesSQL I'm sure I suggested or mentioned something similar there

**Comment by hishamco** [comment]
Seems `ValidateAsync()` is the right place to do this check https://github.com/OrchardCMS/OrchardCore/blob/ef76b6f2a7faf716bd5f1754a394e9a755e20177/src/OrchardCore.Modules/OrchardCore.Tenants/Services/TenantValidator.cs#L38

@CrestApps I can submit a PR for this, unless you need to do it ;)

**Comment by hishamco** [comment]
> I think this logic should be part of the ITenantValidator But I think the validation would have to be done per type/servername/databasename/prefix

I didn't notice that you refer to `ITenantValidator` before ;)
