### ISSUE TITLE
Zones - Edit Widgets and Layers - Widgets reorder drag/drop not working - v1.4

### ISSUE THREAD

**Issue by muzzi-w** [OrchardCMS/OrchardCore#11812]
### Describe the bug
v1.4. 
On the admin 'Setting - Zones' page, drag and drop of widgets doesn't work. 

### To Reproduce
1. Go to 'Design - Settings - Zones'
2. Create two or more widgets in a zones'
3. Try to drag a widget to a space above or below another widget. The multi-arrow icon appears but you cannot move order of widget

### Expected behavior
Tested and works on v1.1. 
You should be able to move a widget to a different position/zone

**Comment by Skrypt** [comment]
I'm surprised about that one. I'm pretty sure I tested it. I will try it.
