### ISSUE TITLE
Some <select> tags have "form-control" class, but really should be 'form-select'

### ISSUE THREAD

**Issue by muzzi-w** [OrchardCMS/OrchardCore#11815]
### Is your feature request related to a problem? Please describe.
In most instances, from a UI/UX perspective, a `<select>` tag (drop down list) should have a 'form-select' class, not a 'form-control' class. There are several `<select>` tags that still have the 'form-control' class.

e.g. Taxonomy Edit > Term Content Type 

The result is that there is no indication it is a drop down (normally with the down caret) until focus/action in control

### Describe the solution you'd like
Update the select tag class where appropriate so the representation is a drop down list

**Comment by hishamco** [comment]
Could you please push a PR?
