### ISSUE TITLE
Disable Feature results in InvalidOperationException being thrown

### ISSUE THREAD

**Issue by Andrew120219** [OrchardCMS/OrchardCore#11823]
I have a module that I created and use in a couple of different Orchard sites. When enabled the module works as intended on both sites. The problem is when I go to disable this module on one of the sites as soon as I click 'Yes' button to confirm I want to disable it, I am met with this error:

```
InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Session.ISessionStore' while attempting to activate 'Microsoft.AspNetCore.Session.SessionMiddleware'.
Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)
Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, object[] parameters)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline()
OrchardCore.Modules.ModularTenantRouterMiddleware.InitializePipelineAsync(ShellContext shellContext)
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
OrchardCore.Modules.ModularTenantContainerMiddleware+<>c__DisplayClass4_0+<<Invoke>b__0>d.MoveNext()
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
I have narrowed it down to the shell descriptor changes in the database. The serial number is incremented and then the structure changes. Before trying to disable the module my shell descriptor has a serial number of 11 and it has the Features and Parameters properties.

Once I disable and confirm my choice the serial number increments to 12, but now the shell descriptor has the Features and Installed properties. It is immediately after clicking the 'Yes' confirmation button that this error occurs.

I can disable any other modules with out any issue. I am able to enable and disable the module in question on another orchard site without issue. They are both running Orchard 1.1.0.

This error puts the database into a state that stops the site from working. If I restore just the ShellDescriptor record in the Document database to its previous version the site starts to work again.

**Comment by hishamco** [comment]
Do you have any OC module dependency?

**Comment by Andrew120219** [comment]
@hishamco > Do you have any OC module dependency?
Originally this module had a dependency on Orchcard.ContentFields, but it was there in error. I removed that a while ago. Now this module has 0 dependencies on any other modules.

**Comment by hishamco** [comment]
Seems you are using AspNetCore Session, are you sure you add its service `AddSession()` in your startup?

**Comment by Andrew120219** [comment]
```
public override void ConfigureServices(IServiceCollection services)
        {
            services
                .AddScoped<ITrackingCodeService, TrackingCodeService>()
                .AddScoped<ICookieService, CookieService>()
                .AddScoped<IDataContext, ADOContext>()
                .AddScoped<ITrackingDataService, TrackingDataService>()
                .AddScoped<IVisitorProcessingService, VisitorProcessingService>();

            services.Configure<MvcOptions>(options => options.Filters.Add(typeof(TrackingInjectionFilter)));
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromSeconds(10);
                options.Cookie.IsEssential = true;
            });
        }

        public override void Configure(IApplicationBuilder builder, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
        {
            routes.MapAreaControllerRoute
            (
                name: "Tracking",
                areaName: "SecureData.Orchard.Tracking",
                pattern: "",
                defaults: new {controller = "Tracking", action = "Index"}
            );

            builder.UseCookiePolicy();
            builder.UseSession();
        }
    }
```

**Comment by hishamco** [comment]
Strange!! is your module OSS, or can you share minimal code to reproduce the issue?

**Comment by Andrew120219** [comment]
So I originally made this module with this specific site as a project in the solution. Recently I started a new project where all module development will be performed. I moved the project there and refactored and cleaned it up a bit and made it so these modules could be consumed from a local nuget repo. This module works on my other site as a nuget package. I was in the process of disabling and then removing the reference to the module project so I could use the nuget and this is what is happening.

Is there a way I can maybe remove any reference of this project from the database files so that Orchard knows nothing of this module?  Then I can try to use the nuget package version that works with the other site.

**Comment by Skrypt** [comment]
```SQL
SELECT * FROM Document WHERE Type = `OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Abstractions`
```

Will get you all the modules.

And

```SQL
SELECT * FROM Document WHERE Type = `OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data`
```

Will get you all the module migrations. It should be cleaned for both.
