### ISSUE TITLE
Add description to content types

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11827]
### Is your feature request related to a problem? Please describe.
I created `StudentGoal`, `StrengthGoal`, and few other content types, where each have an attached `BagPart` that would allow the user to add multiple notes to each goal. I also created `StudentGoalNote`, `StrengthGoalNote`, and other notes to allow a user with permission add notes "different kind of notes". The reason I have multiple different note types is because I want to different roles to have different permission (some roles my be able to add a specific note but not all type of notes.) However, since these `StudentGoalNote`, `StrengthGoalNote`, and others are nothing but note to the user, I want the display name to be "Note" so it makes sense on the UI for the user.  Below is a screenshot from the admin panel 
![image](https://user-images.githubusercontent.com/24724371/172496903-a08a6a57-ccbd-4193-a22e-d7c1592bf849.png)

The above looks good and does exactly what I want. However, since all these notes have the same display name, this makes the content-type UI not friendly. Note this is not a duplicate problem, each of these note serves a different purpose but should be called "Note"

![image](https://user-images.githubusercontent.com/24724371/172497452-9f5ed4d6-2bfa-4678-bb4c-a80476d710ed.png)

### Describe the solution you'd like
If the Content-type have description like `ContentPart` does, this would solve the problem and I would be able to add a description to the Content-Type describing what each note actually is used for.

If this something would be accepted, I would submit a PR.

**Comment by CrestApps** [comment]
Adding Stereotype of a note isn’t going to improve the content-type UI. I’ll try to create a PR for adding description

**Comment by CrestApps** [comment]
In addition to description, maybe it will also be nice to show the technical name as a badge next to the display name of the UI as we would do with widgets. But I think for consistency we add description just like we have for bag-part

**Comment by sebastienros** [comment]
I agree with adding it. Anyone thinks we shouldn't?
