### ISSUE TITLE
Not able to delete tenant through admin UI

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#11839]
It's currently not possible to delete a tenant through the admin UI.
Even if there are checkboxes in the tenant overview, there is no button to execute bulk actions on them.
Being able to delete a tenant and not just disable it, would be helpfull!

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1212

**Comment by Flarescape** [comment]
@sebastienros sorry, didn't find this one and thanks! 👍
