### ISSUE TITLE
How to remove a field from display

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1183]
```
 {% display Model.Content | remove_item: "BodyPart" | remove_item : "Blog.CoverImage" %}
```
I have a field called ```CoverImage```. How can I remove it?

This is an example https://innolabs.me/blog. There is a ```Cover Image: /blog/blog-banner-img.png``` shown on the page that I would like to remove.

**Comment by sebastienros** [comment]
Can you try `"Blog-CoverImage"`. The documentation for this value is here: http://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Templates/README/#shape-differentiators

**Comment by sebastienros** [comment]
This is assuming that `CoverImage` is attached to the `Blog` type (which has an implicit same part name)

**Comment by jtkech** [comment]
@dodyg @sebastienros try `Blog-CoverImage-YourFieldType`

Because just saw that in `ContentFieldDisplayDriver` we have


                if (partType == shapeType)
                {
                    // BodyPart-Description, Services-Description
                    result.Differentiator($"{partName}-{fieldName}");
                }
                else
                {
                    // BodyPart-Description-TextField, Services-Description-TextField
                    result.Differentiator($"{partName}-{fieldName}-{shapeType}");
                }

But in the context of a field, `partType == shapeType` is never true. So i think we should have

                if (fieldType == shapeType)

I will propose a patch.

**Comment by sebastienros** [comment]
Probably a bug ... I agree this should be `fieldType`

**Comment by sebastienros** [comment]
I fixed it on the dev branch, and also fixed the documentation

**Comment by dodyg** [comment]
This works. Thanks.
