### ISSUE TITLE
Unify all script providers in orchardcore

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11830]
I sorted out a list of all script providers in January this year, but my English is not very good. I hope someone can help me sort it into the document

# [Liquid Filters](https://github.com/EasyOC/EasyOC/wiki/OrchardCore-%E4%B8%AD%E7%9A%84%E6%89%80%E6%9C%89-Liquid-%E8%BF%87%E6%BB%A4%E5%99%A8%E6%B8%85%E5%8D%95-%7C-List-of-all-liquid-filters-in-Orchardcore)

## Common

``` Liquid
{{"UserName" | Upper }}  
```
> output : `USERNAME` 

## OrchardCore.Liquid
> OrchardCore\src\OrchardCore.Modules\OrchardCore.Liquid\Startup.cs

`{{"input" | local}}`

`{{"input" | slugify}}`

`{{"input" | liquid}}`

`{{"input" "arguments" "context" | href}}`

`{{"input" "arguments" "context" | absolute_url}}`

`{{"input" | shape_new}}`

`{{"input" | shape_render}}`

`{{"input" | shape_stringify}}`

`{{"input" "arguments" "context" | shortcode}}`

## OrchardCore.Users
> OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Startup.cs

### users_by_id
 ```Lqiud 
 {% assign userlist = ['userid1','userid2',user.userId] | users_by_id   %}
 ```
`{{"input" | users_by_id}}`

`{{"input" | has_permission}}`

`{{"input" | is_in_role}}`

`{{"input" | user_email}}`

### localization_set
根据指定的 语言 比如 zh-CN 获得 该语言下的内容信息

源代码路径：OrchardCore\src\OrchardCore.Modules\OrchardCore.ContentLocalization\Startup.cs

`{{"input" | localization_set}}`  

### switch_culture_url

 `{{"input" "arguments" "context" | switch_culture_url}}`

### console_log
 > OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ServiceCollectionExtensions.cs 

 ``` {{"test" | console_log}}```

## OrchardCore.Contents
> OrchardCore\src\OrchardCore.Modules\OrchardCore.Contents\Startup.cs
 
`{{"input" "arguments" "context" | display_url}}`

`{{"input" | shape_build_display}}`

`{{"input" | content_item_id}}`

`{{"input" | full_text}}`

## OrchardCore.DisplayManagement
> OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\OrchardCoreBuilderExtensions.cs

`{{"input" | append_version}}`

`{{"input" | resource_url}}`

`{{"input" | sanitize_html}}`

## OrchardCore.Lists
> OrchardCore\src\OrchardCore.Modules\OrchardCore.Lists\Startup.cs
> 
`{{"input" | list_count}}`

`{{"input" | list_items}}`

`{{"input" | container}}`

## OrchardCore.Markdown

> OrchardCore\src\OrchardCore.Modules\OrchardCore.Markdown\Startup.cs

`{{"input" | markdownify}}`

## OrchardCore.Media 
> OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Startup.cs

`{{"input" "arguments" "context" | asset_url}}`

`{{"input" "arguments" "context" | resize_url}}`

//OrchardCore\src\OrchardCore.Modules\OrchardCore.Queries\Startup.cs
//{{"input" | query}}

## OrchardCore.Taxonomies
> OrchardCore\src\OrchardCore.Modules\OrchardCore.Taxonomies\Startup.cs
> 
`{{"input" | inherited_terms}}`

`{{"input" | taxonomy_terms}}`

## OrchardCore.Workflows
> OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Startup.cs

`{{"input" | signal_url}}`

``` Liquid
{% var content | 'zh-cn' | localization_set  %}
{{content.ContentItem.UserName.Text  }}
```
> 张三

``` Liquid
{% var enContent | 'en-US' | localization_set  %}
{{enContent.ContentItem.UserName.Text}} 
```
> San Zhang

# [Javascript  methods](https://github.com/EasyOC/EasyOC/wiki/OrchardCore-%E4%B8%AD%E7%9A%84%E6%89%80%E6%9C%89%E5%90%8E%E5%8F%B0Javascript-%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0%E6%B8%85%E5%8D%95)

``` typescript
//OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Scripting\WorkflowMethodsProvider.cs
  //WorkflowMethodsProvider
  workflow(): object //workflowContext
  /**
   * @returns 返回工作流Id
   */
  workflowId(): string

  input(str: string): object
  property(str: string): object

  output(name: string, value: string): void
  setProperty(name: string, value: string): void
  lastResult(): object
  correlationId(): string

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Contents\Scripting\ContentMethodsProvider.cs
  //ContentMethodsProvider
  /**
   *
   * @returns IContent
   */
  newContentItem(contentType: string): object //IContent;
  /**
   *
   * @returns IContent
   */
  createContentItem(
    contentType: string,
    publish: boolean,
    properties: object,
  ): object //IContent;
  updateContentItem(contentItem: object, properties: object): void //contentItem: ContentItem
  deleteContentItem(contentItem: object, properties: object): void //contentItem: ContentItem

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Contents\Scripting\UrlMethodsProvider.cs
  //UrlMethodsProvider
  getUrlPrefix(path: string): string

  //OrchardCore\src\OrchardCore\OrchardCore.Infrastructure\Entities\Scripting\IdGeneratorMethod.cs
  //IdGeneratorMethod
  uuid(): string

  //OrchardCore\src\OrchardCore\OrchardCore.Infrastructure\Scripting\CommonGeneratorMethods.cs
  //CommonGeneratorMethods
  base64(encoded: string): string
  html(encoded: string): string
  gzip(encoded: string): string

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Layers\Services\DefaultLayersMethodProvider.cs
  //DefaultLayersMethodProvider
  isHomepage(): boolean
  isAnonymous(): boolean
  isAuthenticated(): boolean
  isInRole(role: string): boolean
  url(url: string): boolean
  culture(culture: string): boolean

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Queries\QueryGlobalMethodProvider.cs
  //QueryGlobalMethodProvider
  executeQuery(name: string, parameters: object): object

  //OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\ConfigurationMethodProvider.cs
  //ConfigurationMethodProvider
  configuration(key: string, defaultValue: object): object

  //OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\ParametersMethodProvider.cs
  //ParametersMethodProvider
  parameters(name: string): object

  //OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\VariablesMethodProvider.cs
  //VariablesMethodProvider
  variables(name: string): object

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Scripting\Providers\LogProvider.cs
  //LogProvider
  log(level: string, text: string, param: object): void

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Scripting\HttpMethodsProvider.cs
  //HttpMethodsProvider
  httpContext(): object //HttpContext
  queryString(name: string): object
  responseWrite(text: string): void
  absoluteUrl(relativePath: string): string
  readBody(): string
  requestForm(field: string): object
  queryStringAsJson(): object //Delegate//serviceProvider: IServiceProvider
  requestFormAsJson(): object //Delegate//serviceProvider: IServiceProvider
  /**
   * 序列化 Body , FormData 或 QueryString 为字典
   * @returns Dictionary<string, object>
   */
  deserializeRequestData(): object //Dictionary<string, object>;

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Scripting\SignalMethodProvider.cs
  //SignalMethodProvider
  signalUrl(signal: string): string
  //TokenMethodProvider
  createWorkflowToken(
    workflowTypeId: string,
    activityId: string,
    days: number,
  ): string

  //OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Scripting\OutcomeMethodProvider.cs
  //OutcomeMethodProvider
  setOutcome(name: string): void
```

**Comment by hishamco** [comment]
If the intend to make them in a thread for info, a discussion is better than github issue. Unless your intend is to write them down in the docs /cc @agriffard

**Comment by hishamco** [comment]
If you asked me I can move it to discussion without creeating a new one
