### ISSUE TITLE
Graphql UI Partial function failure

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11831]
![image](https://user-images.githubusercontent.com/15613121/172659874-9019ccac-d655-4541-97b2-3cd80b757711.png)

**Comment by hishamco** [comment]
Could you please push a PR for it?

**Comment by hyzx86** [comment]
yes  , here https://github.com/OrchardCMS/OrchardCore/pull/11833

**Comment by hyzx86** [comment]
@sebastienros  

I have tested the latest released version  `1.5.0-preview-16895`  in my project, and this problem still exists
