### ISSUE TITLE
Link to Monaco editor documentation in Content Type fields is broken

### ISSUE THREAD

**Issue by muzzi-w** [OrchardCMS/OrchardCore#11835]
### Describe the bug
The link ('Documentation for options') to the Monaco editor documentation are broken. This is referenced to three places.

OrchardCore.Modules\OrchardCore.ContentFields\Views\HtmlFieldMonacoEditorSettings.Edit.cshtml
OrchardCore.Modules\OrchardCore.ContentFields\Views\TextFieldMonacoEditorSettings.Edit.cshtml
OrchardCore.Modules\OrchardCore.Html\Views\HtmlBodyPartMonacoSettings.Edit.cshtml

Not sure what the correct url is but maybe... `https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html.html`
 
![image](https://user-images.githubusercontent.com/12488547/172789451-07b03c9b-ca7e-4de3-83e3-64cb7adbf69e.png)

**Comment by sebastienros** [comment]
Would be able to provide a PR?

**Comment by hishamco** [comment]
I didn't realize that the case is matter here!!

**Comment by muzzi-w** [comment]
Sorry for the confusion here. It's actually the link url (href) that was wrong. 
The current link is... `https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html` which results in a 404
A better link might be... `https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html.html`

**Comment by muzzi-w** [comment]
@hishamco thanks for attending to my recent Issue posts. I should really learn how to do my owm PRs!

**Comment by hishamco** [comment]
No need to close the issue, it will be closed automatically when the PR merged. BTW I'm glad to let you start with your first PR please start with one of these [issues](https://github.com/OrchardCMS/OrchardCore/labels/good%20first%20issue)

**Comment by hishamco** [comment]
> A better link might be... https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html.html

This link for the supported languages not the editor options
