### ISSUE TITLE
Website search to include bagpart fields

### ISSUE THREAD

**Issue by kgwadu** [OrchardCMS/OrchardCore#11844]
We have full text search setup on our website and we are able to add our custom fields so they are searchable however we can't figure out if its possible to include fields on a content item thats on a bagpart. Is this possible? If not will this be something that will be added at some point?

We have some websites that require very dynamic content and allow for sections of content to be added via a bag part. So in a lot of instances, the core of the content on a page comes from the bagpart collection and not the fields on the bagpart container.

**Comment by sebastienros** [comment]
Does anyone know if the body metadata is not populated from bag/flow parts?

**Comment by Skrypt** [comment]
From memory I think @hswami did a PR back then for that matter. Maybe he could confirm.
