### ISSUE TITLE
What is a shape?

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1184]
Is the object that's accessible to the template or is it something else? 

I read [this](http://docs.orchardproject.net/en/latest/Documentation/Basic-Orchard-Concepts/#zone) and I still can't figure it out.

**Comment by etcetraw** [comment]
https://youtu.be/gKLjtCIs4GU

**Comment by sebastienros** [comment]
Everything in this video should be in the documentation

**Comment by agriffard** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/4121#issuecomment-539608731

**Comment by dodyg** [comment]
Two years after this question and I still don't understand Shape fully lol.

**Comment by sebastienros** [comment]
Simple answer: It's a view model ... to be continued

**Comment by sfmskywalker** [comment]
The way I understand a shape is that it's a view model with metadata (a property that all shapes have). This metadata contains information the view engine uses to know which template to use to render the shape. When executing the selected template, the view engine passes in the shape as the model for said template.

In addition, shapes can have child shapes, allowing the system to compose an entire tree of shapes with the Layout shape typically being at the root.

There's more to it, but looking at shapes like this always helped me understand them enough to work with them effectively.

**Comment by dodyg** [comment]
I think what makes it unclear is the role of zone in the shape (https://github.com/OrchardCMS/OrchardCore/issues/4121#issuecomment-541442390)

>It's all about what type of Shape the Model is made of for each template. Sometimes Model if a Zones shape, like in your example.

It's not obvious when you can use `Model.Content` or use `Model.ContentItem.Content` to access your Parts.

**Comment by agriffard** [comment]
http://docs.orchardcore.net/en/dev/docs/reference/core/Placement/#shapes
