### ISSUE TITLE
Validate database connection before setting up a tenant

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11876]
### Is your feature request related to a problem? Please describe.
In some cases, while trying to setup a new tenant on the "Setup" screen, the user is able to provide connection settings if the connection is not per-configured. 

In other case, the setup could fail and only some of the tables are created on the connection which leads to incomplete setup. If we run into an in-complete setup, the user should be notified that the tables already exists so they can change the connection or manually delete incomplete tables. Not sure if possible, if a setup fail, may be find out the created table and drop them manually? We would have to find a way to track created tables during setup before dropping table otherwise we could unintentionally drop wrong tables.

Both cases above will lead to this exception

![image](https://user-images.githubusercontent.com/24724371/174127237-677c5ebb-b110-46de-87d8-0644cd034fa1.png)

### Describe the solution you'd like
I think we should validate the database connection before allowing the user to proceed the setup.

Bonus, If possible, track a list new tables, and if the setup fail, drop them

This issue is related to #1183 and #11863 but targets a different scenarios.

**Comment by sebastienros** [comment]
We don't record the list of created tables. Which is also blocking the deletion of existing tenants (the db part).
