### ISSUE TITLE
DocumentManager hides exception

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#11873]
DocumentManager.UpdateAsync is currently hiding exceptions that occur when the distributed cache throws an exception.  

It would be helpful if in the code below the current exception was provided to InvalidOperationException as an InnerException.

```
                try
                {
                    _ = await _distributedCache.GetStringAsync(_options.CacheIdKey);
                }
                catch
                {
                    await DocumentStore.CancelAsync();

                    throw new InvalidOperationException($"Can't update the '{typeof(TDocument).Name}' if not able to access the distributed cache");
                }

```

**Comment by hishamco** [comment]
We can log the exception message. Can you have a PR for it?

**Comment by sebastienros** [comment]
Unless the issue is to just not hide the inner exception's details (still log it).
