### ISSUE TITLE
You can't pick users when you only have permissions to edit your own content.

### ISSUE THREAD

**Issue by Kees-Schouten** [OrchardCMS/OrchardCore#11878]
You can't pick users when you only have permissions to edit your own content.

### To Reproduce
I have a content type  "Project" with a user content picker field. I'm only authorizated to edit my own created projects. When I create a new project I currently can't select users with the user picker field.

### Expected behavior
I should be able to select users when I have the permission to create the content item (in this example "Project").

### Proposed fix
https://github.com/OrchardCMS/OrchardCore/commit/f8fab3c2f8c5a606080b5333f70f949dcbb7a790

### Screenshots
![select users bug](https://user-images.githubusercontent.com/4984029/174396532-059b4b54-9798-4399-ab92-7f133215896e.png)

**Comment by hishamco** [comment]
I think this is a bug. please create a PR for it, then e can review

**Comment by Kees-Schouten** [comment]
Created pull request:

https://github.com/OrchardCMS/OrchardCore/pull/11880

**Comment by CrestApps** [comment]
I don't think this is a bug. Check the settings on your UserFieldPicker to ensure you it lists all the available users not specific roles which excludes yourself.

**Comment by CrestApps** [comment]
@Kees-Schouten @hishamco The problem isn't permission related. 

The problem occurs when a user attaches a field to a content type, the field settings does not have default roles selected or have the DisplayAllUsers selected so in that case, the search break because it does not know where to look at.

I think the fix is ContentUserField should display all users by default unless the user specifically selected specific roles.

**Comment by Kees-Schouten** [comment]
Although the change (Display All Users) is nice it doesn't fix the bug. Unfortunately it's really an bug and I fixed it by using my merge request.

Please follow my reproduction steps and see for your self. Make sure that role, in my case "ProjectManager" only has the permission to "Edit Project" and not "Edit Project for others". 

After configuring the permissions that way, create an new Project and see that you can't select users.

**Comment by Kees-Schouten** [comment]
Thanks the effort! Now I see where we misunderstand. When I enabled the checkboxes like you did in the section "Contents (OrchardCore.Contents)", the user picker works as expected. But In that case it's possible for the users to create all content types.

**The bug occurs** only when you select the checkboxes in the section "Project Content Type - Project". Because I want the users of the role "ProjectManager" only to be able to create content types of type "Project". In this case the UserPickerField doesn't work and stays empty.

**Comment by CrestApps** [comment]
@Kees-Schouten  Even when I change the permission it still works as expected. Have you tried my previous recommendation?

>> Are you sure you are using the latest version of 1.5-preview from cloud smith? If you are, make sure you undo your change. Then, since you created your content type before this fix, you may have to edit the settings one more time to update your existing data. So edit your content type, then edit the users filed and make sure "Display All Users" is checked then save. Be sure to hit the save button even if the "Display All Users" is already selected to update the setting of the field in the database.

**Comment by Kees-Schouten** [comment]
Yes i'm running on main branch and I have your changes running, see:

![image](https://user-images.githubusercontent.com/4984029/177617671-677aa427-f600-419e-bb4d-b560d2f37bef.png)

I also saved multiples times the FieldSettings settings, Part settings and content type definitions.

Please check the UserPickerAdminController.cs and line 51, that's the following code:

`if (!await _authorizationService.AuthorizeAsync(User, CommonPermissions.EditContent, contentItem))`

![image](https://user-images.githubusercontent.com/4984029/177617487-47f7adb2-1d5a-4c6c-80a4-6ec12f658b42.png)

It's clearly an permission problem because the debugger steps in to the Forbid response and as an result the UserPickerField stays empty. The projectmanager does not have the EditContent permission because I dont want him to create others types of content except Projects.

**Comment by Kees-Schouten** [comment]
@CrestApps your change, and correct me if I'm wrong, doesn't change anything related to the if statement:

`if (!await _authorizationService.AuthorizeAsync(User, CommonPermissions.EditContent, contentItem))`

That if statement is run in to when I don't have "Edit own content" permission and will result in Forbid response. When you remove the permission "Edit own content" your self and log off and log on again you should have the same result.

**Comment by CrestApps** [comment]
@Kees-Schouten yes my change has nothing to do with the line you posted because that isn't the problem. The problem you keep referring to here is addressed [here](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.Contents/Security/ContentTypeAuthorizationHandler.cs#L44-L47). So when the line `if (!await _authorizationService.AuthorizeAsync(User, CommonPermissions.EditContent, contentItem))` is executed, we check to see if you own the given content, and if have `CommonPermissions.EditOwnContent` permission.

You never answered my previous questions so I can't provide you further recommendation 

> Are you sure you are using the latest version of 1.5-preview from cloud smith? If you are, make sure you undo your change. Then, since you created your content type before this fix, you may have to edit the settings one more time to update your existing data. So edit your content type, then edit the users filed and make sure "Display All Users" is checked then save. Be sure to hit the save button even if the "Display All Users" is already selected to update the setting of the field in the database.

**Comment by CrestApps** [comment]
Click on your existing content-type, find the UserPicker field and click edit next to it. Not you’ll see the UserField setting. Make sure “Show All Users” is selected then click save. This should work. If you are saying that field is still not working. Please share a screen shots of your setting and the no working field

**Comment by hishamco** [comment]
I'm not sure why we still posting on a closed issue, please reopen or start a new discussion if something else related
