### ISSUE TITLE
We need to update the "Getting Started" section of the documentation

### ISSUE THREAD

**Issue by Diman96** [OrchardCMS/OrchardCore#11888]
This section of the documentation is critically outdated, so much so that it is not possible to get the results that are described. 
As an example this [page](https://docs.orchardcore.net/en/dev/docs/getting-started/), the latest version of OrchardCore 1.4.0 which uses `.Net 6.0` and accordingly if you create a new empty project '.NET Core web application'  with `.Net 6.0`  you will not have a `Startap.cs` file in which all the basic manipulations should take place.

For new developers, this section is an important element of getting started with orchard. And such difficulties that in the guide can have a negative impact on entering a new environment.

My suggestion is to update this section for use on the latest stable version of OrchardCore and be sure to specify the platform versions on which it should work in case of obsolescence to be clear for which version this instruction is valid. Because at the moment there is only one[ page](https://docs.orchardcore.net/en/latest/docs/getting-started/templates/) of this section that mentions the versions for which this example is used.

**Comment by hishamco** [comment]
Can you help on improving this?

**Comment by hishamco** [comment]
Can you help on improving this?

**Comment by Diman96** [comment]
I can help. But if I get in trouble, I might need help from someone who knows Orchard better than I do.
