### ISSUE TITLE
Filter and Saved Filters needed to manage content

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1189]
- At minimum people should be able to filter by content type
- Filter by author would be nice
- Filter by published/draft status would be grand
- Filter by date created/published in range would be amazing
- Sort by last updated asc/desc
- Search by title is needed
- Being able to saved filters and have it readily available would be awesome

![filter-needed](https://user-images.githubusercontent.com/1761249/32538150-bc4fc5a4-c46d-11e7-8909-93db471445b8.png)

**Comment by sfmskywalker** [comment]
Also:

* Filter by stereotype

**Comment by sebastienros** [comment]
Also

- Filter by anything

**Comment by sebastienros** [comment]
It's called Content Tree, it's in the roadmap, it needs design, and more importantly a dev to work on it.
