### ISSUE TITLE
Disappearing content block inside SEO part upon validation error

### ISSUE THREAD

**Issue by MZole** [OrchardCMS/OrchardCore#11902]
### Describe the bug

I've set up an OC site and added the SeoMetaPart to my Content type. I have added a numeric field to my content type, typed in letters, and published it, and the Content Block inside the SEO part disappeared. I also tested adding a handler to SeoMetaPart, which added a ModelError if the PageTitle/MetaDescription was longer than x characters. 
So in summary I think if a validation error occurs (either in the SeoMeta- or the Content part), the Content block disappears inside the SEO page.

### To Reproduce

1. Turn on the SEO module
2. Add the SeoMeta Part to a Content type
3. Make a validation error

### Expected behavior
The Content block inside the SEO part shouldn't disappear.

### Screenshots
![image](https://user-images.githubusercontent.com/99020631/175790058-8860de14-343b-4b7a-9a64-5cb2244ef6af.png)

**Comment by CrestApps** [comment]
Check your log file for an exception

**Comment by MZole** [comment]
There are no exceptions in the log.
