### ISSUE TITLE
Sample needed

### ISSUE THREAD

**Issue by MattPil29** [OrchardCMS/OrchardCore#1191]
Hi,

I'm trying very hard to use the great modular approach demonstrated here to build an application framework that can have pages\blogs etc as default and then custom modules specific to my clients requirements.  As this is a new project i'd like to use Core.  All the material on the web at the moment shows how to make a basic core module that says hello world or a more advanced module in v1.

I could really do with a **quick example repo that shows a core module** that has:
* an admin page for the module that can set an integer\string\boolean for re-use in the module.
* an example of storing module specific data in a multitenant core db i.e. I want a CRUD UI that re-uses the core DB.  Therefore I imagine I need migrations etc in the Module project.
* a razor page with Core authorization enabled to display message or redirect unauthorized users. 
* a razor page that includes one or more bits of content from the CMS, i.e.list of blogs.
* an example of retrieving the values set in the module config.
* a razor page that displays well in the overall site layout (i.e. blog theme has menu and footer).
* a razor page that 'breaks out' of site layout and uses standard boot strap layout.

I already use OrchardCMS/OrchardCore.Samples but it doesn't go far enough.  I realize this sounds a lot but having seen the quick demos you guys can do I hope its simple enough.  

Many thanks, Matt

PS

Here are a few other observations that I'm made while playing:
* the Agency recipe New Page editor only allows HTML widget whereas the Blog recipe has a selection of widgets to allow nested layout using containers etc.  
* out of the box the Agency recipe pages don't display well i.e. not embedded within the site layout.
* In a recent test I did the module.txt file was updated in each build changing the name back to the project name.  In a test the day before this didn't happen - not sure why this would be.

Feature requests:
* allow menu items to be permissions based.  I.e. Login\logout based on status.  Admin menu if you are logged in as admin.  Arbitrary menu based on arbitrary role.
* basic image resizing\placement in page\blog editing.

**Comment by sebastienros** [comment]
Thanks a lot for taking the time to provide some feedback. What's interesting is that I was chatting with @jtkech yesterday night about the exact same issues for the existing recipes. We are fully aware of these issues and will fix them.

I will create distinct issues to track this feedback, some of them will need design.

**Comment by MattPil29** [comment]
Thanks for rapid response. As a first time user I have lots of feedback. Lots could be addressed with more samples and documentation. If anyone could provide some of the demo code requested above I’d be very grateful.

**Comment by Jetski5822** [comment]
@MattPil29 loving the feedback!!! - keep it coming man.

**Comment by sebastienros** [comment]
Can you please file an issue for the image resizing you mentioned, I don't really understand what you mean. I created issues for the other ones.
