### ISSUE TITLE
Remove GetTypeInfo()

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1192]
Its dead... we should remove it, as the abstraction is no longer required.

https://github.com/dotnet/platform-compat/pull/46

**Comment by jtkech** [comment]
I think it will be easy to migrate as i'm reading this.

> With .NET Standard 2.0 we've added all the reflection APIs back to `Type`.

So, just tried (only building) the following example

    // type.GetTypeInfo().GetCustomAttributes<FeatureAttribute>(false).FirstOrDefault();
    type.GetCustomAttributes<FeatureAttribute>(false).FirstOrDefault();

And when implementing an interface where we need to return `TypeInfo`, seems that we can do.

    // type.GetTypeInfo()
    System.Reflection.IntrospectionExtensions.GetTypeInfo(type)

**Comment by sebastienros** [comment]
> And when implementing an interface where we need to return TypeInfo

Or stop returning this but just a `Type`

**Comment by jtkech** [comment]
Exactly!

But this is when we implement an interface we don't define ourselves, e.g an `IApplicationPartTypeProvider` where there is.

    public IEnumerable<TypeInfo> Types

**Comment by sebastienros** [comment]
👍

**Comment by jtkech** [comment]
A PR will be easy to do.

Let me know when it will be the time to do it.

**Comment by sebastienros** [comment]
Don't tell @DaRosenberg that you can't create a PR because we can only use dev ;)

**Comment by jtkech** [comment]
Oh yes, i saw its gitter comment, i think he is right ;)

**Comment by Jetski5822** [comment]
LOL - I knew @jtkech would pick this one up :)
