### ISSUE TITLE
Display the feature name instead of the id when listing the permission in admin

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11922]
### Is your feature request related to a problem? Please describe.
When the permissions are listed during role edit/create, currently we show the feature Id instead of a name. Displaying the feature id is not user friendly.

![image](https://user-images.githubusercontent.com/24724371/176494086-2a884a31-3a28-4685-8bed-7193527cfa64.png)

### Describe the solution you'd like
I think the permissions should be grouped by feature id but we should show the feature name if one is available

**Comment by CrestApps** [comment]
@Skrypt and yes the id will be more unique which is why I suggest we still group by id but display the name. we could show the id in a lighter color if needed.

**Comment by Skrypt** [comment]
Ok, if we want to make this right. We need to display both, I agree. Then something like : 

### OrchardCore.Media (id)
#### Media Feature (name)

**Comment by CrestApps** [comment]
@Skrypt How does this look?
![image](https://user-images.githubusercontent.com/24724371/176502525-9605eb39-2a38-49ed-b86f-97cdc646ef25.png)

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/176503118-365c06e7-767e-4a02-9a61-627e8ac0f7a9.png)

**Comment by Skrypt** [comment]
If we keep grouping by Feature Id then the Feature Id should be displayed before the Feature Name.

**Comment by Skrypt** [comment]
Yes, I don't think it will break anything.
