### ISSUE TITLE
Add IsSystem property to IRole interface to allow identifing the system roles easily.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#11920]
## Is your feature request related to a problem? Please describe.
In many instances in OrchardCore's code, we repetitively use the following code
```
var allRoles = (await _roleService.GetRoleNamesAsync()).Except(new[] { "Anonymous", "Authenticated" }, StringComparer.OrdinalIgnoreCase);
```
These two roles are system roles; IMO, both should be grouped somehow.

## Describe the solution you'd like
First it may be a good idea to add the following class to reduce the use of these terms all over the place.

```
public class CommonRoleConstants
{
    public const string Administrator = "Administrator";
    public const string Editor = "Editor";
    public const string Moderator = "Moderator";
    public const string Author = "Author";
    public const string Contributor = "Contributor";
    public const string Authenticated = "Authenticated";
    public const string Anonymous = "Anonymous";
}
```
I can think of two approaches to clean up the code

### Option 1: Flagging the System Role
I think this may be a better option even if it require few changes. But the idea is to add `bool IsSystem { get; }` property to the [IRole](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Security/IRole.cs) interface Then,
 - Either, set the `IsSystem` flag to true when adding these 2 roles. Perhaps we should also add `IsSystem` flag to [PermissionStereotype](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.ContentLocalization/Permissions.cs#L53-L60) also since that is used to create the role internally via [RoleUpdater](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.Roles/Services/RoleUpdater.cs) 
otherwise, we would have to add a check if the new role is system based or not 
```
role = new Role 
{ 
    RoleName = stereotype.Name, 
    RoleDescription = stereotype.Name + " role",
    IsSystem = new[] { CommonRoleConstants.Anonymous, CommonRoleConstants.Authenticated }.Contains(stereotype.Name, StringComparer.OrdinalIgnoreCase)
};
```
 - Or, define the `bool IsSystem` property in Role like this 
```
public class Role : IRole
{
     // ... existing properties
     public bool IsSystem => new[] { CommonRoleConstants.Anonymous, CommonRoleConstants.Authenticated }.Contains(RoleName, StringComparer.OrdinalIgnoreCase);
}
```
 - In addition to any of the above, we'll update the [IRoleService](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Security/Services/IRoleService.cs#L10) to accept `bool includeSystemRoles = true` parameter to allow us to easily remove the system roles.

### Option 2: Use extensions methods
A less invasive options may be create an extension for the `IRoleService`. I feel approach is a patch but may be more acceptable since the change would be minimal. The idea would be to update the existing [RoleServiceExtensions](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Security/Services/RoleServiceExtensions.cs) by changing it to something like this
```
public static class RoleServiceExtensions
{
    public static async Task<IEnumerable<string>> GetRoleNamesAsync(this IRoleService roleService, bool includeSystemRoles = true)
    {
        var roles = await roleService.GetRolesAsync(includeSystemRoles);

        return roles.Select(r => r.RoleName);
    }

    public static async Task<IEnumerable<IRole>> GetRolesAsync(this IRoleService roleService, bool includeSystemRoles)
    {
        var roles = await roleService.GetRolesAsync();

        if (!includeSystemRoles)
        {
            return roles.Where(x => !RoleHelper.IsSystemRole(x.RoleName));
        }

        return roles;
    }
}

public static class RoleHelper
{
    public static bool IsSystemRole(string roleName)
    {
        return new[] { CommonRoleConstants.Anonymous, CommonRoleConstants.Authenticated }.Contains(x.RoleName, StringComparer.OrdinalIgnoreCase));
    }
}
```

The `RoleHelper` method would come in handy when refactoring code [like the one here](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.Roles/Services/RoleStore.cs#L86-L87)

There could be better ways to do this. Idea?

If this is something we are willing to adopt, suggest the better approach and I'll create a PR for this.

**Comment by hishamco** [comment]
I was thinking before to add the roles in a class as you mentioned, but with extra thing. Localize them will be extra plus

**Comment by hishamco** [comment]
I might work on roles list with minimal solution to support localize them. Then you can do the refactoring

**Comment by CrestApps** [comment]
@sebastienros @hishamco @Skrypt  here is maybe even a better way to do this which will give us much more flexibility and would allow uses to delete unwanted default roles.

The idea is to add a type for each role, then get roles by type. For the sake of the original enhancement, will have a type called `system` which will allow us exclude these types.

To do that, we'll add `Type` property in `IRole` like this  `public string Type { get; set; }`

In the `IRoleService` we would add a new method to get roles by type like this `Task<IEnumerable<IRole>> GetRolesAsync(string type);`

This approach will go a long way because now we don't have to force the user to use the default roles. Using such approach will allow to change change `IPermissionProvider` from something like this

```
public class UserPermissionProvider : IPermissionProvider
{
    public IEnumerable<PermissionStereotype> GetDefaultStereotypes() =>
        new[]
        {
                new PermissionStereotype
                {
                    Name = "Administrator",
                    Permissions = new[]
                    {
                        UserPermissions.ImportUsingExcel,
                    },
                },
        };

    public Task<IEnumerable<Permission>> GetPermissionsAsync() =>
        Task.FromResult(new[]
        {
                UserPermissions.ImportUsingExcel,
        }
        .AsEnumerable());
}
```

to something like this

```
public class UserPermissionProvider : IPermissionProvider
{
	public IRoleService _roleService;

	public UserPermissionProvider(IRoleService roleService)
	{
		_roleService = roleService
	}

    public IEnumerable<PermissionStereotype> GetDefaultStereotypes()
    {
    	return _roleService.GetRolesAsync("administrator")
    				      .GetAwaiter()
    				     .GetResult()
				     .Select(role => new PermissionStereotype
				     {
				          Name = x.RoleName,
				          Permissions = new[]
				          {
				               UserPermissions.ImportUsingExcel,
				           },
				       }).ToArray();
    }

    public Task<IEnumerable<Permission>> GetPermissionsAsync() =>
        Task.FromResult(new[]
        {
                UserPermissions.ImportUsingExcel,
        }
        .AsEnumerable());
}
```

Finally, we would add `Delete` button to the `Roles` UI where role isn't of a type `system`.

It would be even nicer if we convert `IEnumerable<PermissionStereotype> GetDefaultStereotypes()` to `Task<IEnumerable<PermissionStereotype>> GetDefaultStereotypesAsync()` were we can using `await` instead or `.GetAwaiter().GetResult()`
