### ISSUE TITLE
Documentation theme should allow Razor/Liquid switches

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1193]
We need to tweak the documentation theme to allow code sections to appear as tabs for Razor and Liquid such that when an article provides a snippet it can be done with both languages.

**Comment by agriffard** [comment]
May be something like this : 
https://softwarerecs.stackexchange.com/questions/14737/syntax-highlighting-plugin-with-tabs#answer-25966

and when you want to add some code tabs you would use this kind of syntax :
```
<div id="tabs">
  <div id="tabRazor">
'''
@await RenderSectionAsync("Header", required: false)
'''
  </div>
  <div id="tabLiquid">
'''
{% render_section "Header", required: false %}
'''
  </div>
  <ul>
    <li><a href="#tabRazor">Razor</a></li>
    <li><a href="#tabLiquid">Liquid</a></li>
  </ul>
</div>
```

then, we will need a doc to explain how to create docs :-)

**Comment by agriffard** [comment]
See https://github.com/yacir/markdown-fenced-code-tabs/ to add tabs for code samples to documentation :
https://yacir.github.io/markdown-fenced-code-tabs/

**Comment by agriffard** [comment]
https://hackernoon.com/fenced-code-tabs-in-mkdocs-material-a7951a9f8738

**Comment by agriffard** [comment]
I managed to make it work locally with the material theme:
![media](https://user-images.githubusercontent.com/703248/40888454-90db03b0-6757-11e8-87e0-8d03d63dd7b4.gif)

**Comment by sebastienros** [comment]
Can we host the documentation on Azure Static websites?

**Comment by agriffard** [comment]
I don't know how it would be triggered, automatically built and deployed.

**Comment by sebastienros** [comment]
CI ?

**Comment by agriffard** [comment]
I managed to do this: 
- Create a storage on Azure and enabled the static site.
- Create a VSTS Build definition connected to the github repo on the dev branch.
- Add steps to use Python, install MkDocs, build the site and upload it to the $web folder (used by the static site)

Here is the result:
https://orchardcorefr.z6.web.core.windows.net/

So, it works but I am not really satisfied: It takes a long time to upload because all the source code is included.

**Comment by agriffard** [comment]
https://github.com/dotnet/docfx could be an interesting static generator for the docs and the apis.
The v3 seems promising too.

See an example to generate the doc and host it on Azure static website :
https://dennisdel.com/blog/docs-in-cloud/
