### ISSUE TITLE
The Full-Text patern field is hidden on page load when "Use custom full-text" is checked

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#11933]
### Describe the bug
Here is my content exit page
![image](https://user-images.githubusercontent.com/24724371/176749345-4dcd9fe2-31c2-475d-aeca-2a30e5bdf37f.png)

but when the page is first loaded the hidden field does not show up unless you check/uncheck the "User custom full-text" again

![image](https://user-images.githubusercontent.com/24724371/176749491-7f7f44f8-0163-4900-9770-19da295a7fe7.png)

### To Reproduce
1. Edit any content type.
2. in the Full-Text settings section, check "Use custom full-text"
3. Save the page
4. on the page load the "custom full-text" field is invisible.

### Expected behavior
The field should show up on page load when the "Use custom full-text" is checked.

**Comment by Skrypt** [comment]
BS5 regression probably.
