### ISSUE TITLE
Serious Issue, certain settings being synced across dev, uat and prod environments

### ISSUE THREAD

**Issue by kgwadu** [OrchardCMS/OrchardCore#11930]
We have noticed a very serious issue where certain changes made on one environment are being pushed to 2 other environments. 

1. Changing a content type locally will apply the same change on uat (azure web app) and prod (azure web app). We have the physical content definition file
2. Changing the recaptcha keys (security > settings > recaptcha) will also change the keys on the other 2 environments
3. Changing the base url in configuration > settings > general will also change the url on the other 2 environments.

We have not noticed this behaviour on any of our other OC websites, any help would be greatly appreciated, this is causing a lot of problems for us.

**Comment by sebastienros** [comment]
is it possible that you are using the same redis instance (in case you use redis to sync your nodes) ?

**Comment by kgwadu** [comment]
@sebastienros  I can confirm that Orchard Core is storing a bunch of data in our redis cache. We do not have any of the redis features enabled, how do we prevent Orchard Core from using our redis cache??

**Comment by kgwadu** [comment]
@sebastienros  First image is what OC is storing in Redis, the second screenshot is the Redis features.

![image](https://user-images.githubusercontent.com/51178767/177883092-a6723d17-e359-4e16-8bde-a3079120e68a.png)
![image](https://user-images.githubusercontent.com/51178767/177883120-94391a4a-6d5d-4a1f-b41a-b98c477941e3.png)

**Comment by sebastienros** [comment]
Re-reading the issue, isn't it normal if your two environments are using the same database? Isn't it the case? These settings are stored in the db (though I am not sure about the content types).

**Comment by kgwadu** [comment]
@sebastienros so ultimately the problem is that orchard core is using our redis cache resource even though we havent enabled any features related to redis cache. We have been unsuccessful with trying to find a way to prevent OC from using this.

**Comment by sebastienros** [comment]
Thanks for confirming, we need to find someone to debug this. If you want to start the investigation on your side you could add a break point in the REDIS services and see what is invoking it even though the feature is not enabled.

I find it weird though that Orchard is able to store something on Redis if you haven't configured it. How can it be that clever to find your instance? Have you checked OC's configuration files to be sure there isn't any config there?

**Comment by jtkech** [comment]
Yes we have services that inject `IDistributedCache`which by default is a `MemoryDistributedCache`, same interface but memory only. For example the document manager and the dynamic cache.

Then the redis cache feature is to provide a concrete implementation of a distributed cache, but could be any other feature e.g. providing a cache from a shared database. So yes if you register at the tenant level a custom `IDistributedCache` it will then be used.

Idem e.g. if you use the aspnetcore Distributed cache tag helper that will use any current implementation of `IDistributedCache`.

**Comment by jtkech** [comment]
Hmm, maybe one solution would be to register at the tenant level your distributed cache before we register the `MemoryDistributedCache` so that our services will resolve this last one.

Then in your code you could inject an `IEnumerable<IDistributedCache>` and then only keep your typeor filter out the `MemoryDistributedCache`.

**Comment by kgwadu** [comment]
@sebastienros @jtkech ok so it sounds like the issue is this "So yes if you register at the tenant level a custom IDistributedCache it will then be used.", will try your suggestion regarding order. Thank you.

**Comment by jtkech** [comment]
The default Order value is 0, so normally a value of -1 would be sufficient.
