### ISSUE TITLE
Fix Taxonomies docs

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11966]
### Describe the bug
In the [Taxonomies docs](https://docs.orchardcore.net/en/latest/docs/reference/modules/Taxonomies/) states the following code to render terms with `Categories` taxonomies with `Categories` alias. `<shape type="Term" alias="Categories" />` 

But the example should read `<shape type="Term" alias="alias:Categories" />` instead

**Comment by Skrypt** [comment]
Seems redundant. We probably changed something that broke it. Maybe it would be more relevant to fix it so that it works like it was.

**Comment by CrestApps** [comment]
@Skrypt it seems redundant agreed! This code requires it to be prefixed with `alias:`. Note that the existing document shows this as liquid temple `{% shape "term", alias: "alias:categories" %}` also redundant. I think we should just first the document for now and if someone want to change the Razor helpers and liquid helper to append `alias:` when alias is used, why not.

**Comment by sebastienros** [comment]
Historical reasons, alias and alias are not the same here, but I think we fixed it at some point, it's still working for backward compatibility reasons. It might be called `handle` now in the tag helper. And there should be other helpers specific to alias that don't require `alias:`.
