### ISSUE TITLE
Dropdown button is appearing under another Dropdown when adding widgets

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#11969]
### Describe the bug
When adding a widget to a zone from under the "Design" tab. Clicking on "Add Widget" button show the available widgets menu under the next "Add Widget" button. Probably need adjust the `z-index`

Here is screenshot of before clicking "Add Widget" button
![image](https://user-images.githubusercontent.com/24724371/177836799-c91aeb1e-1406-44c4-8ecc-a1e69318c959.png)

Here is a picture of after "Add Widget" is clicked.
![image](https://user-images.githubusercontent.com/24724371/177836832-1412830e-e0a8-4b48-a43c-e84b655338d2.png)

**Comment by hishamco** [comment]
The `z-index` is a good option, but let me check why the button is the top most

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/ef76b6f2a7faf716bd5f1754a394e9a755e20177/src/OrchardCore.Themes/TheAdmin/Assets/scss/modules/_layout.scss#L145

@Skrypt is `z-index` in `.btn-dropdown` was set for a special reason?

**Comment by Skrypt** [comment]
For that same reason where those dropdowns need to have a higher z-index than our top navbar and other elements. Though, here the issue is that the z-index needs to increment from top to bottom if you want these dropdowns to not appear through each other.

**Comment by hishamco** [comment]
> For that same reason where those dropdowns need to have a higher z-index than our top navbar and other elements.

I though you are the one who did that ;)

**Comment by ryanwawr** [comment]
Running into the same problem, but the fact that both the dropdown menu and the button are 0.8 opacity when not hovered seems to exacerbate the issue, so would be nice if that were adjusted as well.

![image](https://user-images.githubusercontent.com/6531664/225409766-5c8675cd-d61a-4b59-bf35-ef5a99ecdae1.png)

**Comment by MikeAlhayek** [comment]
Submitted a PR to fix this issue.
