### ISSUE TITLE
ShellSettings/DatabaseShellsSettingsSources memory leak

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#11965]
### Describe the bug
There appears to be a memory leak caused by the usage of IConfiguration as the backing for ShellSettings.  What I've found is that memory used by each ShellSettings instance is not being freed for garbage collection due to some fairly crazy gcroots even if you intentionally release the ShellSetting.  

In our case drilling further into the problem shows most of the memory is being used by Strings related to the DatabaseShellsSettingsSources with the VersionId field being the largest consumer of memory.   The problem is that the DatabaseShellsSettingSources contains data for ALL tenants (which in our case is 2000+) even if you're only loading/reloading a single tenant.  

I've considered either two possible solutions but the entire configuration subsystem to safely do either.

1. Make the source use a singleton internally that was shared for each call and updated as appropriate.  This is preferred since it keeps memory cost low even with many tenants but is a pretty big change in behavior since currently once you get a ShellSetting it's not live updated.  I'm also not 100% sure of how to pull this one off since I haven't studied how the builder works internally (for instance maybe AddInMemoryCollection could be provided with the same list of KeyValuePairs across different calls?

1. Figure out how to properly dispose of IConfigurationRoots when they are no longer needed.  It looks like work was done in .NET Core 3 to support this but it also appears to depend on disposing of the HostingEnvironment but I'm assuming the base work could potentially be used here? maybe?

**Comment by Skrypt** [comment]
So the issue is that each instance of DatabaseShellsSettingSources contains data of ALL tenants.
This means it should probably be a singleton instead. Or each instance should contain only the data relevant to a specific tenant?

**Comment by Skrypt** [comment]
@jtkech without looking at the code is it not already an application-wide singleton?

**Comment by jtkech** [comment]
Yes `DatabaseShellsSettingsSources` it is a Host Singleton.

I will take a look when I will have time

**Comment by jtkech** [comment]
@ShaneCourtrille

I took a look on this one, yes we need to keep in memory the shell settings of all tenants, then when building the config of a given tenant we only use the related section.

But I saw something when we fully reload a tenant, not the case when we only enable a feature or change admin settings where the tenant is only released and will re-use the same shell settings, but when we fully reload a tenant from the admin Tenants Page or explicitly by code.

So when we fully reload a tenant, currently we do somewhere the following where a MemoryStream is created with all settings values, knowing that at the end only the tenant related section will be used.

    if (document.ShellsSettings != null)
    {
        builder.AddJsonStream(new MemoryStream(
            Encoding.UTF8.GetBytes(document.ShellsSettings.ToString(Formatting.None))));
    }

Maybe it could explain all or part of your memory leak. So, when we fully reload a single tenant and only in that case, in place of doing the above we could do this to only serialize the related section.

    if (document.ShellsSettings != null && document.ShellsSettings.ContainsKey(tenant))
    {
        var shellSettings = new JObject
        {
            [tenant] = document.ShellsSettings[tenant]
        };

        builder.AddJsonStream(new MemoryStream(
            Encoding.UTF8.GetBytes(shellSettings.ToString(Formatting.None))));
    }

If that makes sense I can do a PR.

Hmm this is related to `DatabaseShellsSettingsSources`, but maybe also something to do with the default `ShellsSettingsSources` where we use a `AddJsonFile()` on the global `tenants.json` file, maybe good to share the same `PhysicalFileProvider` in place of creating a new one when we fully reload a single tenant.

**Comment by ShaneCourtrille** [comment]
@jtkech Yes.. we're seeing memory usage from calls to ShellHost.UpdateShellSettingsAsync which trigger a reload of the tenant which loads the all tenant shell settings.  By reducing the number of calls we were able to reduce memory consumption but we still have to update shell settings at points so reducing the cost of this call would benefit us greatly.

**Comment by sebastienros** [comment]
@ShaneCourtrille now I want to know what you are doing with OC and these 2000 tenants.

**Comment by Piedone** [comment]
BTW @ShaneCourtrille with this many tenants [this module of ours](https://github.com/Lombiq/Hosting-Tenants) may be interesting for you, especially [this feature](https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.IdleTenantManagement/Readme.md) for shutting down idle tenants.
