### ISSUE TITLE
Invalid filter used in the Tenants list

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11974]
### Describe the bug
When clicking on the State badge on the `/admin/Tenants` list, the data does not get filtered as it should. The problem is that the filter in the generated URL has this `Options.Filter=Uninitialized` instead of `Options.Status=Uninitialized`. Also, the URL should have `&` when `?` is part of the URL and `?` if it does not exists in the URL.

![image](https://user-images.githubusercontent.com/24724371/178048351-ddf9ed13-d86b-4543-8530-7a20202c5fc8.png)

### To Reproduce
1. Go to Tenants list `/admin/Tenants`
2. Next to any tenant click on the badge that shows the tenant's status
3. You'll notices that the list did not get filtered

### Expected behavior
When clicking on "Uninitialized" badge, only tenants with "Uninitialized" should show up.

**Comment by hishamco** [comment]
Let me check this one, and thanks for reporting

**Comment by hishamco** [comment]
> Also, the URL should have & when ? is part of the URL and ? if it does not exists in the URL.

This will not break the filter, but it's good to fix it too. Nice catch ;)
