### ISSUE TITLE
Add documentation for module creation

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1197]
From https://github.com/OrchardCMS/OrchardCore/issues/1191

I could really do with a quick example repo that shows a core module that has:

an admin page for the module that can set an integer\string\boolean for re-use in the module.
an example of storing module specific data in a multitenant core db i.e. I want a CRUD UI that re-uses the core DB. Therefore I imagine I need migrations etc in the Module project.
a razor page with Core authorization enabled to display message or redirect unauthorized users.
a razor page that includes one or more bits of content from the CMS, i.e.list of blogs.
an example of retrieving the values set in the module config.
a razor page that displays well in the overall site layout (i.e. blog theme has menu and footer).
a razor page that 'breaks out' of site layout and uses standard boot strap layout.

**Comment by Jetski5822** [comment]
Add documentations for 

> There are way too many concepts that are not explained well from zones, shape, widget, stereotype, layers, etc.

**Comment by Piedone** [comment]
This is largely done by the [Training Demo module](https://github.com/Lombiq/Orchard-Training-Demo-Module/). Possibly we could add Razor pages. But I don't think this is in any way a blocker for 1.0, we have enough documentation on module development already.
