### ISSUE TITLE
Export some content directly

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11986]
- [X] Export Workflows from Workflow List and Edit page #11939
- [ ] Admin UI Templates.
- [ ] Manage ContentType/ContentPart List 
- [ ] Edit ContentType/ContentPart
- [ ] Queries

There are many contents, and the process may be complex. We should try to reuse the code in `XXXDeploymentSource`

**Comment by Piedone** [comment]
Related? https://github.com/OrchardCMS/OrchardCore/issues/11405
