### ISSUE TITLE
Trumbowyg missing icons

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#11985]
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/11979

<div type='discussions-op-text'>

<sup>Originally posted by **kevinsmgov** July  9, 2022</sup>
When I add "indent" and "outdent" buttons to the Trumbowyg configuration, the buttons appear and function in the bar but there are no icons in them (they are blank). Does anyone know what additional configuration in necessary to make the icons show in the buttons?</div>

**Comment by Piedone** [comment]
This is fixed in the latest `main`:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/ee78f03c-c950-4538-884d-1bc112f83587)
