### ISSUE TITLE
Restrict specific recipes from being executing more than once

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11987]
### Is your feature request related to a problem? Please describe.
When defining sub recipes that create default content, executing it more than one time will cause duplicate content being added. 

### Describe the solution you'd like
Add a flag that would allow us to prevent it from being executed more than once. This would only apply to recipes that aren't marked as setup recipe. We'll probably have to store executing counts in a document to be able to make this work. May be we can even show a message on the UI stating "Recipe has been already executed".

![image](https://user-images.githubusercontent.com/24724371/178121266-6ab7e515-a128-4f64-8a3b-c536900dc726.png)

**Comment by hishamco** [comment]
This is annoying :) setup recipes SHOULD be executed once as you mentioned to avoid unexpected results

**Comment by CrestApps** [comment]
@hishamco 
I think you miss understood the request. We can't prevent the setup recipes from being executed. This would only apply to non-setup recipes or partial recipes. Typically these recipes are executed manually from the UI. And if we create a sub recipe that is responsible of creating default content, it would be wrong to execute it more than once since it'll just create duplicate. and if a setup recipe is executing partial recipes, then this won't be a problem since setup recipe will be executing during the tenant setup.

**Comment by ns8482e** [comment]
@CrestApps I believe @deanmarcussen has done some work related to idempotency in recipes

**Comment by deanmarcussen** [comment]
Just use a fixed guid for the contentitemid and it will be ignored in the import. 

Alternate with a generated guid for the version number and it will reset the content to the importing version.

**Comment by CrestApps** [comment]
@deanmarcussen won't it be nice to have a flag that would allow the app to just ignore the execution of the recipe? I understand the workaround, but there may be other cases "other than importing content" where this would come in handy. I think adding a flag is more elegant than having to hard core multiple ids in the recipe.

**Comment by sebastienros** [comment]
Make it idempotent.

**Comment by sebastienros** [comment]
Explained in triage
