### ISSUE TITLE
Have rooted media folders

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1199]
> There is no way to root the default folder within asset folder for specific content types. So if you are blogging extensively, every time you upload an image, you have to navigate from the root folder again.

**Comment by matiasmolleja** [comment]
Hi,
Maybe we can close this?
Not exactly setting a default folder, but we are getting the issue solved I think,
The media always opens in the last opened folder. So there is no need to navigate again to it.

**Comment by sebastienros** [comment]
Maybe another issue would be to be able to set a root folder in the media field settings such that we __can't__ use another folder.

**Comment by matiasmolleja** [comment]
A common use case for that would be too set a "home" directory per user, so that the user is not able to browse outside of its own "entry point" in the full file storage tree.
