### ISSUE TITLE
UI Refresh & Enhancements

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#12006]
As we all know, the UI in many places need to refresh and consistent. One of the main UI issues that I notice using bootstrap colors extensively, while some colors are not make sense to the actions.

I can take the initiative an start prettify the UI in one page, then we can apply these changes after we approve it

**Comment by CrestApps** [comment]
Just a thought, we should find a way to create reusable components for each of these button. This way we have one reusable component for all these actions. Component view or a shape.

**Comment by hishamco** [comment]
It could be doable if we introduce `OC.UI` that contains all the predefine components that could be reused and override. Believe it or not I was thinking in the past about UI project that remove the dependency from bootstrap or any other UI framework. May be one day this could be happen even as a community project

**Comment by hishamco** [comment]
Could be, but base UI components should be abstracted

**Comment by hishamco** [comment]
I just created a quick prototype something similar to Azure DevOps dropdown menu. The final output make a lot of room, which makes the list item clear and clean

https://user-images.githubusercontent.com/3237266/179314511-f90a6757-2440-4787-950e-54b07bb94fc1.mp4

**Comment by CrestApps** [comment]
@hishamco although this look nice, it requires 2 click to get to the common functions. IMO, I think the "View" and "Edit" should be kept as buttons. 

Either way, this should be constant across the entire admin.

**Comment by hishamco** [comment]
I don't think we need the buttons and random colors anymore ;) regarding the clicks that how it works ;)

You can check Azure DevOps to see it in action, I will submit a PR soon

> Either way, this should be constant across the entire admin.

Sure

**Comment by sebastienros** [comment]
Is it about creating reusable components (not a fan) or refreshing some items that could be made better (always good).

**Comment by hishamco** [comment]
This about refreshing some items. But still I'm planning about creating a resuable components as a separated project, probably OSS if there's no resources interested on this

**Comment by hishamco** [comment]
Closing this while no one interested :)
