### ISSUE TITLE
Add save and continue features.

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1201]
> Most of the editors do not have save and continue features.

Save and not leave the page

**Comment by agriffard** [comment]
It would be two actions: 'Save Draft' or 'Save Draft and continue'.
We could use a dropdown button.

Some admin pages are still missing the `returnUrl` parameter that allows to come back to the previous page.

**Comment by agriffard** [comment]
Can be closed. #3623

**Comment by sebastienros** [comment]
Hummm, not yet

**Comment by agriffard** [comment]
Can this be closed?
There is a "and Continue" on a few pages (Content, Template).
