### ISSUE TITLE
Hide TablePrefix for SQLite while editing a tenant.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#12010]
### Describe the bug

Minor issue but the Tenant Create Editor doesn't allow to define a TablePrefix for Sqlite.
Only after the tenant has been created by re-editing it through the Tenant Edit Editor.

### To Reproduce
1. Create a teant and select Sqlite.
2. You can't define a Table Prefix.
3. Save and re-edit the tenant.
4. You now can define a prefix.

@hishamco I think this is an issue that you can easily fix.

**Comment by CrestApps** [comment]
I think I can add that to #11803 to prevent a possible conflict.

**Comment by hishamco** [comment]
Believe it or not I was wondering why this happening, I though it's by design. I will submit a PR

@CrestApps thanks, but let us don't mix things. I still need to know the progress in table prefix validation

**Comment by sebastienros** [comment]
We hid the prefix by design. Assuming sqlite would not make sense for multi-tenancy. Now I don't see why technically it would not work, though I don't see the point. It's better for perf to separate the files, even more that there can only be one writer to a sqlite file. Would be a bad practice.

**Comment by jtkech** [comment]
@sebastienros 

Yes, I was just using it for testing purpose because it was allowed.
So no problem to keep the `TablePrefix` hidden in the `Create` Editor.

But then the `TablePrefix` should be also hidden in the `Edit` Editor.

**Comment by hishamco** [comment]
> But then the TablePrefix should be also hidden in the Edit Editor.

That's what I'd like to say if we agreed to not use it for multi-tenancy, but again I see benifit to allow users to use the table prefix in SQLite

**Comment by jtkech** [comment]
Anyway when we select Sqlite we have a dedicated db file (name/path are hardcoded as I remember) per tenant, so for now not so useful. I used it only for testing while working on how to retrieve all tables with a given prefix.

So one suggestion would be to do the opposite in your related PR, hide the TablePrefix in both editors.

**Comment by hishamco** [comment]
> So one suggestion would be to do the opposite in your related PR, hide the TablePrefix in both editors.

That's what I will do ;)

**Comment by hishamco** [comment]
Done

**Comment by ns8482e** [comment]
@sebastienros @hishamco I guess havi g table prefix on SQLite help create tenant that can easily be ported on SQL backed multi-tenant db using ETL/Scripts without manually adding prefix

**Comment by hishamco** [comment]
I'm agree with you Niraj, let us wait for Seb, if the above reasons convince him ;)

**Comment by ns8482e** [comment]
@hishamco @sebastienros May be it’s ok not have UI option, however it should be documented that TablePrefix is possible in SQLite and How to configure  using config

**Comment by jtkech** [comment]
Okay and I changed the title of this issue
