### ISSUE TITLE
Create user generate password does not consistently meet default password requirement

### ISSUE THREAD

**Issue by daveblack101** [OrchardCMS/OrchardCore#12019]
### Describe the bug
Password randomness occasionally omits a special character or number 

### To Reproduce
Got to create a new user >> click generate password.

### Expected behavior
Password should include a number, lower and uppercase letter, and special character.

### Screenshots
![image](https://user-images.githubusercontent.com/1476149/179334507-46d00521-a03e-4821-87bb-c94402888ecb.png)

**Comment by hishamco** [comment]
@CrestApps I think you are the one who worked on this, am I right?

**Comment by CrestApps** [comment]
Yes. I’ll fix it tomorrow. Feel free to assign it to me

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/b51608aee848285d37aa0590c622dfd7d9dbff41/src/OrchardCore.Modules/OrchardCore.Users/Views/UserFields.Edit.cshtml#L75-L84

BTW the current function SHOULD be align the password requirements for `IdentityOptions`
