### ISSUE TITLE
Use file scoped namespaces

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#12029]

**Comment by hishamco** [comment]
[Based on the comment](https://github.com/OrchardCMS/OrchardCore/pull/11991#discussion_r923342190)

**Comment by Skrypt** [comment]
See if this can be done by cleaning up the code with VS tool.

**Comment by hishamco** [comment]
I don't think so, but it will save my life if it does ;)

**Comment by Skrypt** [comment]
I'm running the code cleanup with the namespace preference set to file_scoped. It will take a while.

![image](https://user-images.githubusercontent.com/3228637/179555782-89a0d9b9-483c-41dc-9421-51e79bb1e4b1.png)

![image](https://user-images.githubusercontent.com/3228637/179555816-f6edd31e-bdd4-425e-a611-1bfda19a5229.png)

**Comment by hishamco** [comment]
I just run it when you added my comment ...

**Comment by hishamco** [comment]
Still WIP

**Comment by sebastienros** [comment]
Only for new files
