### ISSUE TITLE
For workflows that SetPropertyTask, arrays can, but objects are exceptions.

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#12020]
![image](https://user-images.githubusercontent.com/16968103/179337977-3242ea78-8cd7-423a-bea5-f4bf6b55b048.png)
![image](https://user-images.githubusercontent.com/16968103/179337998-e4bc5dea-36c5-4e59-9b01-e2e8131b77da.png)

"faultMessage": "Line 1: Unexpected token :"

**Comment by chinasqzl** [comment]
{
  "id": 19,
  "workflowId": "408kb7p83k0kb289wepaxq724y",
  "workflowTypeId": "4345vy641ztm7vmwctyzvj24nz",
  "correlationId": null,
  "state": {
    "LastResult": null,
    "Input": {},
    "Output": {},
    "Properties": {},
    "ActivityStates": {
      "47sm7shbc62e4vrdsve2dx69xq": {
        "ActivityMetadata": {
          "Title": null
        },
        "HttpMethod": "GET",
        "Url": "/Blog/workflows/Invoke?token=CfDJ8GNbRv3b51hPmf94id1iKGvrMEvCFf8rlXOuU2G4xeZv86oolMXpfhrD1WURv_pvdnFXuRbXdJe1UxVr7DM2DZKnAXOPoSn92uGROBhkOYNHhf8s8ozrrohU7pBqCoSwE9LUnE30fUH_kKfsT6rCC7-zju2Df8ogfE_p6uNdvMPJxK2Ce8YvukbCy4TAs6A8tqIZlO-Um5dXKxPr8QE0MspfgtNxV_uNyMlRIyxXKthk",
        "ValidateAntiforgeryToken": true,
        "TokenLifeSpan": 0
      },
      "45eq2z7vhpya95ps567hyhwdmq": {
        "ActivityMetadata": {
          "Title": null
        },
        "PropertyName": "i",
        "Value": {
          "Expression": "{'a':1,'b':2}"
        }
      }
    },
    "ExecutedActivities": []
  },
  "status": 6,
  "faultMessage": "Line 1: Unexpected token :",
  "lockTimeout": 0,
  "lockExpiration": 0,
  "blockingActivities": [],
  "createdUtc": "2022-07-16T06:20:44.869132Z",
  "isAtomic": false
}

**Comment by lampersky** [comment]
@chinasqzl wrap this dictionary in an extra parenthesis

![image](https://user-images.githubusercontent.com/6403130/179346549-94573165-0a36-46a1-b954-3c659f157e08.png)

other than that, sometimes if you have more complex sceneria you could return your object from anonymous function

![image](https://user-images.githubusercontent.com/6403130/179346501-efb52d74-216a-42ac-afd4-a524668d08b6.png)

I'm not sure if this is a bug, rather a known limitation.

**Comment by chinasqzl** [comment]
Thank you
