### ISSUE TITLE
Add async modifier for DisplayAsync()

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#12023]
https://github.com/OrchardCMS/OrchardCore/blob/5c0ad15503044c5a93f5248440092a8473863490/src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorPage.cs#L88
I'm wondering why we not awaited the call `ShapeExecuteAsync()` it's a bug or by design?!!

/cc @sebastienros

**Comment by jtkech** [comment]
That's okay because the method doesn't use any other `await SomeAsync()`, e.g. only some `Task.FromResult<T>()`, and because `_displayHelper.ShapeExecuteAsync()` returns the same `Task<T>`.

**Comment by hishamco** [comment]
So why it suffix with `Async` while there's no `await` ;)

**Comment by jtkech** [comment]
Because it is still an async method returning an awaitable Task, may be the one returned by ShapeExecuteAsync(), or an already completed Task if returned by Task.FromResult() ;)

**Comment by sebastienros** [comment]
Not a bug, C# feature.

**Comment by hishamco** [comment]
I don't think it's a bug from the beginning but i'm surprising because there's nothing to await for

**Comment by jtkech** [comment]
> there's nothing to await for

There is something to await, here this is the caller that may await the Task we return.

Each time we return a Task<> or ValueTask<> should be suffixed with Async
