### ISSUE TITLE
SanitizeHtml on HtmlField not honored on package import.

### ISSUE THREAD

**Issue by sonicmouse** [OrchardCMS/OrchardCore#12037]
I have a Recipe that has this definition:

```
{
  "FieldName": "HtmlField",
  "Name": "articleEntryBody",
  "Settings": {
	"ContentPartFieldSettings": {
	  "DisplayName": "Body",
	  "Editor": "Wysiwyg",
	  "Position": "10"
	},
	"HtmlFieldSettings": {
	  "SanitizeHtml": false
	},
	"ContentIndexSettings": {}
  }
}
```
Below that, I have article content that looks like this:
![image](https://user-images.githubusercontent.com/2473180/179810271-49f09db8-e881-4175-baf4-feee9c7b5e0c.png)

I import the package, and when i navigate to the resource, it changed it to this:
![image](https://user-images.githubusercontent.com/2473180/179810717-7662dc39-d50c-4324-b06e-3d25a6267e14.png)

Notice the `<div class="media-carousel">` was changed to `<p class="media-carousel">`.

Apparently setting `SanitizeHtml` to `false` isn't enough. Is there any way I can just shut off all HTML sanitization? I don't want to use it for this project and deadlines are creeping fast.

**Comment by CrestApps** [comment]
I had similar issue even when adding HTML content to a content item using the UI the same happens

**Comment by Skrypt** [comment]
This is probably just an issue when importing recipes. The HtmlSanitizer is probably not executed.

**Comment by sonicmouse** [comment]
Is there any way i can shut off sanitization globally so it never runs, @Skrypt ?

**Comment by Skrypt** [comment]
I don't recommend it. But you would need to take a look at https://github.com/mganss/HtmlSanitizer options.
Or, you could unregister the service with the DI from a custom module I guess.

**Comment by sonicmouse** [comment]
When i pull the data out via GraphQL, it's in this converted state. That's right after package import, without viewing it in the editor, if that helps.

**Comment by CrestApps** [comment]
@sonicmouse are you able to share with us the recipe you are using to create the content-type and import the content item that is causing this problem? This will make reproducing the problem easier.

**Comment by sonicmouse** [comment]
I tore down everything and rebuilt it to test what I said, and it's not converting it on import. It seems to be the bug that is referenced above. When I go to article page, it's acting the exact same where the `div` is being converted to `p` and the edit box is not scaled correctly.

But I swear I never edited the article contents. I imported, then pulled the data out via GraphQL. So I have no idea how it ever got in that state to begin with. But I sure can't recreate it now. This data was imported on a much earlier version of Orchard Core CMS though (v1.1.0 I believe), so maybe there was something that was fixed since then.

You can mark this as duplicate if you'd like.

**Comment by CrestApps** [comment]
@sonicmouse glad to know its just a bug :)  apparently this isn't a bug. its part of the default that the editor creator provide. A proposed fixed can be found in PR#12050. If this one get merge, you won't need to make a change. but for now, I suggest you use `Tryumbowyg` and add this to the settings

```
 semantic: {
        'b': 'strong',
        'i': 'em',
        's': 'del',
        'strike': 'del'
    }
```

**Comment by sonicmouse** [comment]
What is the best way to fix this? Is there going to be a fix for WYSIWYG editor?

Or do I change it from WYSIWYG to Trumbowyg and set the `semantic: false` option? (i really don't want to do that as it may disable other things that I may need).

**Comment by sonicmouse** [comment]
Thank you, @CrestApps. Is there a timeframe on the PR being merged? Sorry to be annoying, just trying to get info to management.

**Comment by CrestApps** [comment]
I don't know if it'll get approved. Since it's not a bug, you can change the default behavior as stated above for now. WYSIWYG uses Tryumbowyg.

**Comment by sonicmouse** [comment]
@CrestApps fix worked for me, so I am closing this out due to the fact that this issue has already been reported.
