### ISSUE TITLE
Registring Scoped service in different modules with different concrete implementation

### ISSUE THREAD

**Issue by florimm** [OrchardCMS/OrchardCore#1204]
If we have a host and two Modules and on each of them we register a different implementation of the same interface example:
```
interface IFoo {
    string getMeesage();
}
```
in module 1 we register
```
class ModuleOneFoo : IFoo {
     public string getMessage() { return "Module1";  }
}
```

and in module 2 we register
```
class ModuleTwoFoo : IFoo {
     public string getMessage() { return "Module2";  }
}
```

I tested and in my sample, the one overrides other.
In the source there I already see that you use that (different implementation )in multiple modules this code:
 `services.AddScoped<IPermissionProvider, Permissions>();) .`
Is this a bug or am I'm missed something?
Thanks

**Comment by sebastienros** [comment]
For the `IPermissionProvider` you are mentioning we resolve `IEnumerable<IPermissionProvider>` as we want all the registered instances.

In your case you just want one, and you can still register as many as you want. the last one to be registered will be the one resolved. To be sure you are getting the one you want there you have to:
- define a feature dependency in your module.txt file to the one you want to override. The effect is that the Startup of your module will run after the one your depend on, so your configuration will win.
- if you can't define a dependency, you can set the `Order` property to something greater than 0 (or the order that the other module's startup has), so you are run after the other module
- you can also remove any existing service in the service collection (won't help in your case)

**Comment by florimm** [comment]
But in my case, both module will use their implementation so I don't wont to override.
Can I use a different DI framework (like StructureMap) so I can register both implementations at their module but resolve by name?

**Comment by sebastienros** [comment]
Modules in Orchard share the same container instance, such that one module can improve the behavior of others. In your if you don't want to share the implementation then you can create a new interface in the modules, that inherits from the main one. You can also use options and pass the service to it. Finally you can also just register the class directly, if you don't need the interface or don't want other implementations.
