### ISSUE TITLE
Workflow  ScriptTask Error: Property 'map' of object is not a function

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#12043]
Script:

``` js
var userList=['admin']

log('Error',"userList:"+JSON.stringify(userList))
var getMailBoxParams=userList.map(x=>`'${x}'`);
var mailListResult=executeQuery("QueryUserEmailByUserName",{userNames:getMailBoxParams.join(',')})
var staticEmail=[{"Email":"HUARUI2219@QQ.COM"}] 
log('Error',"staticEmail map:"+JSON.stringify(staticEmail.map(x=>x.Email)))
log('Error',"mailListResult:"+JSON.stringify(mailListResult))
log('Error',"mailListResult:"+JSON.stringify(mailListResult.map(x=>x.Email)))

var allMailStr= mailListResult.map(x=>`${x.Email}`).join(";")
setProperty("mailList",allMailStr)
setOutcome('Done');
```

log output

``` log
> userList:["admin"] 
> staticEmail map:["xxx@QQ.COM"] 
> mailListResult:[{"Email":"xxx@QQ.COM"}] 
>ERROR|An unhandled error occurred while executing an activity. Workflow ID: '16883'. Activity: '446k3gcdes9xs00j9pxmmy6hnj', 'ScriptTask'. Putting the workflow in the faulted state. Jint.Runtime.JavaScriptException: Cannot read property 'map' of undefined
   at :9:67    at :9:67


```

**Comment by hyzx86** [comment]
The above tests use the latest code, but the tests in version 1.2.0 are normal

![image](https://user-images.githubusercontent.com/15613121/179903274-c7178685-0450-439a-8f71-694f9551403a.png)

**Comment by hyzx86** [comment]
> log('Error',"mailListResult:"+mailListResult)
mailListResult:System.Collections.Generic.List`1[Newtonsoft.Json.Linq.JObject]

**Comment by hyzx86** [comment]
```
> log('Error',"mailListResult:"+mailListResult.ToArray().map(x=>x.Email))
["HUARUI2219@QQ.COM"] 
```

**Comment by lampersky** [comment]
> After `ToArray`, it can be output normally
> @sebastienros Is it a bug in Jint?

@hyzx86 I don't think it is a bug in Jint. Please have a look at **executeQuery** implementation, it is returning `IEnumerable<object>` which for **Scripting** is just a regular object, not an array, that is why you can't access map method. As you've noticed by converting object to an array you were able to use map method. You could also use spread operator to achieve the same.

here is original "**executeQuery**" method:
![image](https://user-images.githubusercontent.com/6403130/179915851-2cbf9396-4b48-45d8-86a1-4257682a080d.png)

You can simply fix this, by returning an array:

![image](https://user-images.githubusercontent.com/6403130/179916589-921f6800-dbba-4f53-9ec0-a7438d8bebb1.png)

(I've used Linq here, so please remember to add `using System.Linq;` )

**Comment by hyzx86** [comment]
@lampersky 
Last year, I submitted a similar issue and created PR, which is the same as the code above, but the final solution is that orchardcore updated jint. After a period of time, there was no such problem, but the latest version reappeared. I don't know why

**Comment by hyzx86** [comment]
https://github.com/sebastienros/jint/issues/1005

**Comment by hyzx86** [comment]
@lampersky 
So your solution is to re inject an `executeQuery ` implementation?

Like this?
``` C#
 services.AddSingleton<IGlobalMethodProvider, MyQueryGlobalMethodProvider>();
```

I tested this method, and it really works,

However, there will be two such methods in the system. I don't know whether it will cause unexpected problems

**Comment by lampersky** [comment]
> I don't know whether it will cause unexpected problems

I would say you will also need to replace **DefaultScriptingManager** with your own implementation, where you can choose which method should be used. Orchard Core will accept many **GlobalMethod**s with the same name, but you can't be 100% sure which one will be used inside **JavaScriptEngine** (IScriptingEngine).

Here you can see, my own module where I've duplicated one of exisiting GlobalMethod:
![image](https://user-images.githubusercontent.com/6403130/180645411-60896747-49e2-4b53-a098-20a55803b20f.png)

and here you can see how those methods are registered within **Jint.Engine**, as you can see methods with the same name overwrite existing ones:
![image](https://user-images.githubusercontent.com/6403130/180645643-7e137baa-ff11-425f-85b3-fb736f05b07a.png)

@hyzx86 I hope that helps :)

**Comment by hyzx86** [comment]
@lampersky   Thanks for sharing 
I will to refer to your code to solve this problem,

@sebastienros 
At the same time, I submitted my replication test on Jint
