### ISSUE TITLE
WYSIWYG/Trumbowyg editors are changing div element to p

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#12049]
### Describe the bug
When using HtmlBodyPart or HTML Field with either WYSIWYG or Trumbowyg, the editor convert `div` elements to `p`.

Also, when the user switch into code insert mode, the textarea box does not take up the full size of the editor. 
![image](https://user-images.githubusercontent.com/24724371/180047938-6b2ab0a2-901e-4fe9-b840-4b93d10e28bf.png)

### To Reproduce
1. Add `HtmlBodyPart` or `HtmlField` to a content type, use either `WYSIWYG` or `Trumbowyg` editors
2. Create new or edit existing content item. Click on `<>` of the editor to switch into code insert mode and insert the following

Here is the issue in action
![wysiwyg](https://user-images.githubusercontent.com/24724371/180039239-94c08cf6-42c6-4864-924b-50794c236ddc.gif)

**Comment by Skrypt** [comment]
Unless I'm wrong, with these editors, we provide configurations from the admin UI. So, you that you can change this. But, by default, it sets the first element to a paragraph.

**Comment by Skrypt** [comment]
For trumbowyg you can with this configuration option : 

https://alex-d.github.io/Trumbowyg/documentation/#semantic

**Comment by Skrypt** [comment]
I think that "Wysiwyg" editor option will be "Trumbowyg" with some basic configuration.
The "Trumbowyg" editor option allows you to change the configurations.
So, I saw one issue there about the "Wysiwyg" editor not displaying properly though.

**Comment by ns8482e** [comment]
@CrestApps its default behavior of trumbowyg library.

WYSIWYG  editor and Trumbowyg editor  are just wrappers in OC and uses default behavior ootb 

However @Skrypt is saying that Trumbowyg editor allows you to customize config to fit  if your needs


If you don’t like to change config on every instance of trumbowyg, in part/field, you can override their default behavior across application, you can change it via edit template OR  you can add your own edit template.

**Comment by hishamco** [comment]
Totally agree with @ns8482e

**Comment by CrestApps** [comment]
What benefit "if any" does OC developer gain from changing all `div` to `p` by default? To me it's just a bad idea altogether and is annoying. In OC, by default we should not be changing `div` to `p` because  `Trumbowyg` want to have some odd settings in there for some reason. we can always set our own default as we do today by adding the buttons that we think will be beneficial by most users.

**Comment by Skrypt** [comment]
It has been discussed in today's meeting that we can at least force some defaults on the "Wysiwyg" editor if it is the Trumbowyg editor. So, we would simply turn off the semantics on the Trumbowyg editor by default for OC.

**Comment by CrestApps** [comment]
@Skrypt would we just set `semantic: false` by default or would we change it to

```
semantic: {
        'b': 'strong',
        'i': 'em',
        's': 'del',
        'strike': 'del'
    }
```

I don't know if we use `b`, `i`, `s` and `strike` attributes in OC or not? I'll update PR #12050 based on your response.

**Comment by ns8482e** [comment]
@CrestApps  the reason trumbowyg replace div with p

https://github.com/Alex-D/Trumbowyg/issues/410#issuecomment-250732936

**Comment by CrestApps** [comment]
In triage, there was a decision to set `semantic: false` for `Wysiwyg` editor and leave the `Trumbowyg` editor untouched as the user is able to set their own settings from the UI. The agreed on change is now part of #12050
