### ISSUE TITLE
Medias not loaded on IIS deployed site

### ISSUE THREAD

**Issue by mattiascibien** [OrchardCMS/OrchardCore#1205]
I have just tried to upload a site on a hosting provider (Using IIS with .net core support) using the latest myget version (agency template) at https://next.mattiascibien.net) but I cannot see the images (like: https://next.mattiascibien.net/Media/portfolio/05-full.jpg?&width=400&height=300&rmode=strech). 
When accessing the URL only a blank page is displayed (no HTTP 404) 

On my local copy everythin g is fine

Site has been published using Publish from visual studio (using OrchardCore as a Nuget Dependency).

**Comment by sebastienros** [comment]
do you have a wwwroot folder?

**Comment by sebastienros** [comment]
And can you share your log file content?

**Comment by mattiascibien** [comment]
Hi,
I have checked on the deployed site and I have found the wwwroot folder with a is-cache inside. 

anyway I tried to find my nlog logs (they should have been under App_Data) but could not find anything.  

While debugging also this was fine. I guess I will try again from the beginning.

**Comment by sebastienros** [comment]
Do you have any update on this?

**Comment by mattiascibien** [comment]
Sorry, did not have the time to check. I'll try again asap.



Inviato da smartphone Samsung Galaxy.


-------- Messaggio originale --------
Da: Sébastien Ros <notifications@github.com>
Data: 16/11/17 21:36 (GMT+01:00)
A: OrchardCMS/OrchardCore <OrchardCore@noreply.github.com>
Cc: Mattias Cibien <mattias.cibien@outlook.com>, Author <author@noreply.github.com>
Oggetto: Re: [OrchardCMS/OrchardCore] Medias not loaded on IIS deployed site (#1205)


Do you have any update on this?

**Comment by sebastienros** [comment]
Please reopen if you can still repro
