### ISSUE TITLE
When renaming media item to a name that already exists, JS throw an error

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#12061]
### Describe the bug

When you rename item to a name that already exists I get the following error
```
SyntaxError: Unexpected token < in JSON at position 0
```

Also, when media file fails, the error showed become visible on the screen without having to click on the Errors count to see the actual error.
![image](https://user-images.githubusercontent.com/24724371/180255700-0f14954e-9202-4fb8-ba8c-88b2988934ef.png)

After clicking "Errors: 1" I can see the error
![image](https://user-images.githubusercontent.com/24724371/180255996-370a39aa-1494-4f2a-8772-3dd5dfb74ce2.png)

Finally, when someone rename the a file and click "Ok" button after renaming an item, the modal should disappear and currently it stay open

### To Reproduce
1. Upload a file called dog.jpg
2. Upload a file called cat.jpg
3. Now, rename cat.jpg to dog.jpg, you should get the error in the console.

**Comment by Skrypt** [comment]
First test with the latest main branch : 

https://user-images.githubusercontent.com/3228637/180263809-1c598c6e-cbdd-4385-8d27-048f380e7567.mp4

**Comment by Skrypt** [comment]
Also, I fixed the modal issue recently.

**Comment by CrestApps** [comment]
@Skrypt I forgot I was using custom Admin Theme. It must be an issue there because changing it to the `Admin Theme` worked as you showed.

What about the errors hidden by default?

**Comment by Skrypt** [comment]
I think it was intentional to keep it collapsed but maybe it would be better to display the message better. To be honest the media gallery needs some UI work.

**Comment by CrestApps** [comment]
agreed, it needs some work. I logged in couple other enhancements related to media stuff

**Comment by sebastienros** [comment]
Please open a separate issue for "Also, when media file fails, the error showed become visible on the screen without having to click on the Errors count to see the actual error."
