### ISSUE TITLE
Error message：An error occured while executing this request.!! Menu overlap

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1208]
http://192.168.1.100/OrchardCore.Users/Admin/Index

Nightly (dev): https://github.com/OrchardCMS/OrchardCore/tree/7d069b3d0f32416d5d2f3991616c3b41bc3143a0

Error message：An error occured while executing this request.!!
Menu overlap。
**I use VPN network。**
![1](https://user-images.githubusercontent.com/28694676/32698183-b060a5d0-c7db-11e7-897b-9d77e8e4a9ed.gif)

**Comment by Jetski5822** [comment]
hey @pgy866 , do you have anything in your log's folder that could help diagnose this?

**Comment by sebastienros** [comment]
I can repro

**Comment by Jetski5822** [comment]
You broke it?

**Comment by sebastienros** [comment]
Ye, I am fixing it now ;)

**Comment by pgy866** [comment]
@Jetski5822  
@sebastienros 
thank you all!
After the test has been normal repair!
