### ISSUE TITLE
Uploaded media must be treated as normal routable content

### ISSUE THREAD

**Issue by giantpenguin** [OrchardCMS/OrchardCore#12096]
### Is your feature request related to a problem? Please describe.
The url to an image has not been updated when moving the image around the Media Library e.g., move the referenced image to a sub-folder, the property that holds reference to the image still keeps the before-moved url of the image.

### Describe the solution you'd like
Any uploaded image (or media content) must be treated as a normal content and has its routable capability so that its (referenced) url will be updated correspondent to its new location.

**Comment by Skrypt** [comment]
Have you tried cleaning the Media cache?

**Comment by giantpenguin** [comment]
Hi @Skrypt 

I sure that yes, it is a local site on my desktop then I can turn on/off the machine

![image](https://user-images.githubusercontent.com/7245621/181210512-76b7cc67-ce56-472e-af9c-204786fab6d4.png)

Thank for your reply!

**Comment by Skrypt** [comment]
But then you need to update the LandingPage that integrates these images. If you move them then the LandingPage will still have the previous links set. We can't prevent this from happening since the Media Library doesn't keep a database reference of all media files. It has been decided that in Orchard Core we would not do that for perf reasons.

**Comment by giantpenguin** [comment]
we should not save or embed the referenced image/media's public url e.g., /media/portfolio/4.jpg in database but that image's internal (something built with the media/content identity) url instead, the media's public url will be resolved/routed from its saved internal url when is requested.

**Comment by Skrypt** [comment]
That is what we agreed to not do in OC. Not saving an internal URL for each media item because it would require fetching the media metadata from the database which would degrade performance. You can create a Content Type with a ContentHandler for your specific needs if that is what you need.

**Comment by giantpenguin** [comment]
Thank @Skrypt for your suggestion!
But I see that it is so inconvenience, if just a image is referenced by many contents the editor must resave all that contents if just moving around the image, and what if the site owner needs to re-structure the whole media contents.

**Comment by sebastienros** [comment]
You can create a Media content type which would point to a physical media. Then all your content items could reference this media instead of inserting a file path. That's more work, there are also some performance implications.
