### ISSUE TITLE
Orchardcore use nuget, how to solve the problem of referring googleapis？

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1209]
https://github.com/OrchardCMS/OrchardCore/blob/e64b6f5efa1f6ea21865576d6ed277cd9784cd1a/src/OrchardCore.Modules/OrchardCore.Resources/ResourceManifest.cs

Some countries currently only use VPN only normal access to CDN，
Recommendation: increase the Cdn source settings, you can set the CDN source for local resources (set UI)?Or update the CDN。

**Comment by YaoaY** [comment]
Create your own Resource Module ,and do whatever you want 😎  .

> 自己做一个资源模块，然后为所欲为。

[https://github.com/YaoaY/MyOrchardThemes](url)

**Comment by pgy866** [comment]
@YaoaY  For me it is difficult! I will not write the code, sad! Just look at your module, great, as if CDN is currently only a small number of countries have a problem, you can PR cdn this problem? thank you very much!

对于我来说，那是困难的！我不会写代码，难过！刚看啦你的模块,非常棒，好像CDN目前只有很少部分国家有问题，你可以公关cdn这个问题吗？非常感谢！

**Comment by sebastienros** [comment]
You don't need to use the resource manifest, you can just insert the url you want to use in your themes.
