### ISSUE TITLE
Feature recommendations: Media files use strict permissions mode！

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1210]
Can media folders increase the ability to set precise control permissions for each folder individually? Based on: User? Role？
Recommended additional Settings UI：Whether to use strict permission mode for media files, mainly for the control of additions and deletions

**Comment by sebastienros** [comment]
Would not prevent assets from being requested, but could limit the management of specific folders (adding, deleting, selecting elements).

**Comment by pgy866** [comment]
Looking forward to, Orchard Core, is perfect.

**Comment by hishamco** [comment]
Closed with the respect of #9369
