### ISSUE TITLE
Edit placements Dropdown for text fields is broken

### ISSUE THREAD

**Issue by daveblack101** [OrchardCMS/OrchardCore#12116]
Clicking on the dropdown does not activate it. 

Other field types do not appear to be affected.

![image](https://user-images.githubusercontent.com/1476149/181812323-3ab8f978-0423-4ec8-b305-bad029889376.png)

**Comment by ns8482e** [comment]
May be a leftover bug related to bs5 upgrade

**Comment by Skrypt** [comment]
More like a Monaco issue there that breaks the javascript runtime.

**Comment by Skrypt** [comment]
I can repro. Strange issue if it's about BS5 because it renders the same HTML elements as on other pages.

**Comment by hishamco** [comment]
@daveblack101 is the other dropdowns underneath work fine?

**Comment by daveblack101** [comment]
I checked about half of the others and they were working.

**Comment by hishamco** [comment]
Last question are you working on nightly builds? If Not please have a try may be an upgrade issue in a specific version

**Comment by daveblack101** [comment]
I noticed in in 1.5.0-preview-16930

**Comment by hishamco** [comment]
BTW I did some changes recently in the dropdown, but it was related to the arrow color. So, when you tell some are working I didn't expect it's from my PR

Let me share the PR, then check the build before, may be something weird happen

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/commit/39188a341cea790e7a73b294f3febebc66bf3ccf

**Comment by Piedone** [comment]
This is fixed in the latest `main`.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/52b3d322-f7b6-4ab2-b4eb-b3db7e85a241)
