### ISSUE TITLE
Passing an empty string to localizer crashes if Localization freature is enabled

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore#12130]
### Describe the bug

If you call `T[string.Empty]` you get the exception "ArgumentException: MessageId can't be empty", but only if Localization is enabled. If it's disabled is just becomes an empty string. Both IStringLocalizer and IHtmlLocalizer are affected.
This was identified in https://github.com/OrchardCMS/OrchardCore.Commerce/issues/129

### To Reproduce
1. Add `@T[""]` to any cshtml file.
2. Enable the Localization feature.
3. Visit the page.

### Expected behavior

If the input string is null or empty, it should just return itself. This is reasonable, because `NullLocalizer` has no problem with null or empty inputs so the behavior would be consistent regardless of which IStringLocalizer implementation is used.

### Screenshots
![error message](https://user-images.githubusercontent.com/4007293/181908541-89fa91c9-3612-4019-8435-3aee2944af71.png)

**Comment by hishamco** [comment]
IMHO the localized key can't be null or empty, so this behavior shouldn't affect by module status (enable or disable), @sebastienros your though?

**Comment by ns8482e** [comment]
If you go to wrong way you always see `wrong way` sign 

ArgumentException is telling that it’s wrong way 😀

**Comment by DAud-IcI** [comment]
But why isn't `NullLocalizer` telling me that as well? If `T[""]` always throws an `ArgumentException` that's ok too, but currently you only get an exception if the _Localization_ feature is enabled.

The inconsistency between localizer implementations is the bigger problem here.

**Comment by ns8482e** [comment]
@DAud-IcI I guess NullLocalizer returns what you give

**Comment by hishamco** [comment]
`NullLocalizer` is nothing but return the same key as value, except for the key is `null` or empty which fails in

https://github.com/OrchardCMS/OrchardCore/blob/acce79aab20eeb05f02d1fed873674b1ce40a789/src/OrchardCore/OrchardCore/Localization/NullStringLocalizerFactory.cs#L44

So, again I see the key SHOULD be not `null` or empty

**Comment by DAud-IcI** [comment]
That only applies to parameterized strings. Like I said, `@T[""]` does [not](https://github.com/OrchardCMS/OrchardCore/blob/acce79aab20eeb05f02d1fed873674b1ce40a789/src/OrchardCore/OrchardCore/Localization/NullStringLocalizerFactory.cs#L27) fail under `NullLocalizer`.

This perhaps could be as simple as replacing
```csharp
public LocalizedString this[string name] => new LocalizedString(name, name, false);
```
with
```csharp
public LocalizedString this[string name] => this[name, Array.Empty<object>()];
```

**Comment by DAud-IcI** [comment]
I thought we have agreed that you shouldn't? That's why I gave my previous suggestion, as currently `NullLocalizer` allows it.

Also I didn't say it has to be static. If you see the error I linked in the issue description it has `T[currency.EnglishName]`. It just happens to be an empty string for certain types. However I don't think it's very relevant here.

**Comment by hishamco** [comment]
`T[currency.EnglishName]` is a dynamic not a static string. Am I right?

**Comment by ns8482e** [comment]
@DAud-IcI  IMHO to match behavior - NullLocalizer should throw error :) - But purpose of having NullLocalizer is not to throw error

**Comment by hishamco** [comment]
I don't think we should leave this open, because `NullLocalizer` is what the name implies, while a real localization SHOULD NOT allow null or empty string, @sebastienros correct me if I'm wrong

**Comment by Skrypt** [comment]
I think it is fine how it is. I think ultimately NullLocalizer should throw error on bad usage of a T[""]. There is no such thing as a translation of an empty string. And it should definitely throw.

**Comment by hishamco** [comment]
`NullLocalizer` should be null localizer ;) similar to `NullLogger` which is not log anything except it doesn't throw if you request `IStringLocalizer` from DI

**Comment by Skrypt** [comment]
So all good then.
