### ISSUE TITLE
Sql query content and Liquid Widget

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1213]
- I create a Sql query named 'Contents' like this:
```
select *
from ContentItemIndex 
where Published = true and ContentType = '{{ type }}'
order by CreatedUtc DESC
```
- I can run the query and it returns the json of the Blog posts.

- I add a Liquid Widget to a Layer with this Liquid syntax: 
```
{% assign contents = 'Contents' | query type:'BlogPost' %}
{% for content in contents %}
      {{ content }}
{% endfor %}
```

=> Nothing is displayed in the widget. It seems the parameter is not taken in account.

**Comment by agriffard** [comment]
Second test:
- I select `Id` and replace in the query `{{ type }}` by `BlogPost`
```
select Id
from ContentItemIndex 
where Published = true and ContentType = 'BlogPost'
order by CreatedUtc DESC
```
- As I selected `Id`, I check 'Return Documents'.

- I remove `type:'BlogPost'` in the widget:
```
{% assign contents = 'Contents' | query %}
{% for content in contents %}
      {{ content }}
{% endfor %}
```

=> Nothing is displayed. 

On another OC application, I created the same kind of query and it returns the json of another content item, not the one with the Id returned by the query.

**Comment by agriffard** [comment]
I have the same result if I test this url : `/api/queries/Contents?parameters={}`
=> `[]`: no data.

Note: if I call `/api/queries/Contents` without parameters, an Exception occurs :
```
NullReferenceException: Object reference not set to an instance of an object.
OrchardCore.Queries.Sql.SqlQuerySource+<ExecuteQueryAsync>d__7.MoveNext() in SqlQuerySource.cs, line 40
```

**Comment by sebastienros** [comment]
Return DocumentId from the query

**Comment by agriffard** [comment]
Ok, my bad. When I return DocumentId, the second test works.

**Comment by sebastienros** [comment]
This works for me:

```sql
select DocumentId
from ContentItemIndex 
where Published = true and ContentType = '{{ type }}'
order by CreatedUtc DESC
```

```liquid
{% assign contents = 'Contents' | query: type: 'BlogPost' %}
{% for content in contents %}
      {{ content | display_text }}
{% endfor %}
```
