### ISSUE TITLE
Unable to Search only Title in Orchard Search Index

### ISSUE THREAD

**Issue by Syed-Hasnain-Askari** [OrchardCMS/OrchardCore#12139]
I'm working on Orchard Search functionality, When I search on it then the result shows title along with banner image just like that.
 
![image](https://user-images.githubusercontent.com/47834896/182627609-7082244f-077e-4b74-af36-7667e56d5958.png)

but I need only to show Title which is actually part not field , my configuration is 
![image](https://user-images.githubusercontent.com/47834896/182630531-ebdaacce-11c8-4105-8a5d-1af1d60da678.png)
I have also allow index option in Title part
![image](https://user-images.githubusercontent.com/47834896/182631098-9bb30921-684c-4c73-8da9-b53eebb03ccf.png)

Know someone who can answer?

**Comment by Syed-Hasnain-Askari** [comment]
> You need to remove the "Analyzed" setting. The TitlePart will then stored in the "Content.ContentItem.DisplayText" but you will be able to do a full-text search on the "Content.ContentItem.Displaytext.Analyzed" field still.

Thanks for your response. I have removed the Analyzed setting and applied Content.ContentItem.Displaytext.Analyzed on Default searched fields. like 
![image](https://user-images.githubusercontent.com/47834896/182710152-1a35447d-de83-4d52-bfc5-75057d42fe14.png)

but it gives blank screen, while Content.ContentItem.FullText is working with banner imge.


![image](https://user-images.githubusercontent.com/47834896/182710842-3637c725-e43c-49d1-9de7-6b10102da185.png)


Content.ContentItem.DisplayText is also not work.

**Comment by Skrypt** [comment]
Content.ContentItem.DisplayText.Analyzed will not display in the results because it is not a "stored" field. It is only "Analyzed" but I'm pretty sure it is there. You will need to use a "match" query on it instead of a term query.
