### ISSUE TITLE
Show BagPart content when the post request generates errors in the bagpart.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12140]
### Is your feature request related to a problem? Please describe.

Assume we have a content-type (ex., `Product`) with a BagPart attached. The user create new or edits existing product and provids an invalid data for an items within the BagPart. The post request fails validation which is great! However, the bag part will be rendered in a collapsed state. So the user is left wondering where is the error until the user uncollapse the bag part and see the highlighted error

### Describe the solution you'd like
I think when rendering the BagPart, we should uncollpase the bagpart if there is an error in any of it's contents.

**Comment by hishamco** [comment]
Do you mean UI/UX improvement, right?

**Comment by CrestApps** [comment]
yes. Specifically `BagPart` improvement

**Comment by hishamco** [comment]
Are you plan to open a PR?

**Comment by hishamco** [comment]
May be an error alert is suited for this case

**Comment by CrestApps** [comment]
I’ll try if time permits. I think all we need to do is check the ModelState for and error where error-key starts with prefix of the BagPart. If any errors, we can add `show` class to the BagPart.

**Comment by hishamco** [comment]
If we have multiple items in bag part, this might not be obvious, that's why I prefer to show the error in a standard alert

**Comment by CrestApps** [comment]
If we have more than one BagPart, it would be named part which will have different prefix. Plus, most drivers provide key to errors so we should just show the field validation. Otherwise, we’ll display the error twice “once as alert and other as around field”

**Comment by ns8482e** [comment]
It does highlight the errored input

**Comment by MikeAlhayek** [comment]
@ns8482e yes it highlights the fields but the widget block that contains the field will be collapsed and so the user does not see the highlighted fields unless they uncollapse the bag container. Here is a screencast to explain this issue better

![BagPartWithErrors](https://user-images.githubusercontent.com/24724371/190264893-15c84676-33bf-4eaf-ab74-9bb00aa4de40.gif)

**Comment by MikeKry** [comment]
@MikeAlhayek 

Is it possible that PR for this caused that all bag part items are uncollapsed everytime you edit content item, not only on error?
It is kinda annoying, because when you have a lot of items, all of them are open in edit mode and you have to scroll a lot...

**Comment by MikeAlhayek** [comment]
@MikeKry it should not but I'll have to check it out when I have time.

**Comment by MikeAlhayek** [comment]
@MikeKry I suggest that open up a new issue with this. Perhaps, you want to explain the expected behavior that you want as well. Also, do you recall the behavior prior the BagPart change?
