### ISSUE TITLE
Dark Mode Applied with a New Tenant 

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#12147]
### To Reproduce
1. Go to 'Configuration' -> 'Tenants'
2. Click on 'Add Tenant'
3. Fill up the tenant info
4. Click on 'View'
5. Login
6. The admin site show up with dark mode

### Expected behavior
The admin site show up with light (aka default) mode

**Comment by hishamco** [comment]
@Skrypt I'm sure it's not by design, correct me if I'm wrong, so I can check the default preferences

**Comment by Skrypt** [comment]
If the OS is using dark mode maybe the default then become the dark mode.

**Comment by hishamco** [comment]
Ya, I really foget this one
