### ISSUE TITLE
Remove Hardcoded display route for ContentItems

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#1215]
I found that **OrchardCore.Autoroute.Routing.AutorouteRoute** has hardcoded route,

```
context.RouteData.Values["area"] = "OrchardCore.Contents";
context.RouteData.Values["controller"] = "Item";
context.RouteData.Values["action"] = "Display";
context.RouteData.Values["contentItemId"] = contentItemId;
```

So all ContentItems will be rendered via OrchardCore.Contents.ItemController.
But Every ContentItem has Metadata with DisplayRouteValues property, I could just specify my custom Display Route in Metadata and I would expect my custom Display Route will be invoked (instead of  OrchardCore.Contents.ItemController.Display)

In Orchard 1 we used AliasMap/IAliasService in order to override Display routes for particular ContentItems.

**Comment by sebastienros** [comment]
Talked offline with @rserj and my suggestion would be to handle the Display metadata in the Item controller. Or to load the content item in the autoroute handler (PS: be careful with perf to prevent multiple queries on the same item).
