### ISSUE TITLE
Cannot overwrite the layout view if  use the `BaseTheme` property

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#12153]
When using a custom theme,  cannot overwrite the layout view if  use the `BaseTheme` property

https://github.com/OrchardCMS/OrchardCore/discussions/12125#discussion-4266804

**Comment by jtkech** [comment]
Do you mean a CustomTheme having a BaseTheme = SomeBaseTheme?

If so CustomTheme can override the Layout but to see it in action your CustomTheme not only needs to be enabled but also needs to be selected as the current theme.

**Comment by hyzx86** [comment]
Yes, I did, but it didn't work
The rewritten module page can take effect, but layout_ login. The changes on cshtml will not take effect. There is a detailed screenshot at this address..

https://github.com/OrchardCMS/OrchardCore/issues/12153

Finally, I copied all the files in TheAdmin to my project, and removed the `BaseTheme`  config

**Comment by hyzx86** [comment]
Here is my testing , 
The follow image has describe my test infomation

My Theme module is  BasedOn  `TheAdmin` Theme.

If the code effect , the debug point will be stop , or the login page should display `33333333333333`

But it doesn't work~~

![image](https://user-images.githubusercontent.com/15613121/182038065-85e15e32-ddcc-429b-897e-a4b8ee089393.png)
![image](https://user-images.githubusercontent.com/15613121/182038107-c61541c0-ebec-4847-a3a1-d68f66f870c4.png)

**Comment by jtkech** [comment]
@hyzx86 

Just tried in the context of a project having a custom admin theme.

But it uses OC version 1.3 so maybe need to be tried with the last dev.

But it works by just adding a `Layout-Login.cshtml` in the custom admin theme whose manifest is.

    [assembly: Theme(
        Name = "***",
        Author = "***",
        Website = "***",
        Version = "0.0.1",
        Description = "***",
        Tags = new[] { "admin" },
        BaseTheme = "TheAdmin"
    )]

**Comment by hyzx86** [comment]
I was using 1.4.0 ~ 
Later, I will upgrade to the latest version and test it

**Comment by hyzx86** [comment]
@jtkech  Yes, it's worked now , Thanks
![image](https://user-images.githubusercontent.com/15613121/183301712-63cd7825-b203-42cf-b211-f9a2b969c7ef.png)
