### ISSUE TITLE
Renaming files in media library including OrchardCore.Media.Azure

### ISSUE THREAD

**Issue by DavidStania** [OrchardCMS/OrchardCore#12150]
I'm using the 'OrchardCore.Media.Azure' module and the data is stored in the blob storage like expected. After renaming the filename in my media library, the filename was renamed on the blob storage but the modal in the media library gives no feedback and not closing after action is done. It is also not posible to close the modal by clicking on 'Cancel' or 'X' only by clicking outside the modal.

Adding new folder in the media library is working, but also no feedback and modal is not closing.

A feedback with an success message would be nice.

**Comment by hishamco** [comment]
> the filename was renamed on the blob storage but the modal in the media library gives no feedback and not closing after action is done. It is also not posible to close the modal by clicking on 'Cancel' or 'X' only by clicking outside the modal.

Did you try in `OC.Media` module, @Skrypt seems the modal issue happens in many places ;)

**Comment by Skrypt** [comment]
This is fixed in the main branch. Will need to wait for a new release or use main branch.
