### ISSUE TITLE
Update ImageSharp

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1216]
There is an issue with special chars in media urls

https://github.com/SixLabors/ImageSharp.Web/issues/10

**Comment by sebastienros** [comment]
`MediaFileSystemResolver` will also need to be updated

**Comment by PinpointTownes** [comment]
@JimBobSquarePants hey.

Curious: instead of manually unencoding the string representation of `PathString` (which is URL-encoded when implicitly converted to a `string`), have you considered using `context.Request.Path.Value`?

**Comment by sebastienros** [comment]
Very non-intuitive behavior. I need to check everywhere we use `Request.Path` ...

**Comment by JimBobSquarePants** [comment]
@PinpointTownes I had not as I wasn't aware of the property. That appears to be a better fix.

**Comment by agriffard** [comment]
It currently uses version 1.0.0-dev000064  
https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp.Web
1.0.0-dev000068 is available.
