### ISSUE TITLE
Sitemap does not include the homepage of the site

### ISSUE THREAD

**Issue by xtomas** [OrchardCMS/OrchardCore#12167]
### Description
Sitemap does not include the homepage of the site.

### Steps to reproduce the behavior:
1. Add new sitemap
2. Add Sitemap Content Types
3. Select Index All Content Types and Create source
4. There is no homepage (index /) location in the sitemap output

### Expected behavior
Homeroute (/) will be included by deafult or there will be some options to add home route into sitemap output.

**Comment by Skrypt** [comment]
I'm not sure if having a sitemap record for a homepage makes sense. The https://domain.name url stands by itself.

**Comment by xtomas** [comment]
Technically the content item marked as homepage in the sitemap already exists, but with the autoroute value (that can not be null, empty, root, etc.). So the index one content `/` item is missing but there is one redundant with autoroute value (for example '/homepag'). Imho the homepage one should be the first one.

**Comment by Skrypt** [comment]
Well, I think that "/homepage" in that case is an "alias" and that the "/" route is not necessary.

**Comment by xtomas** [comment]
Our requirement is to not publish the URL `/homepage` in the sitemap. The only way how to achieve this is to create special content type and exclude it from sitemap. But then will be no homepage item in the sitemap at all.

**Comment by xtomas** [comment]
Side effect of required autoroute value for homepage is blocking the url for other content items.

**Comment by Skrypt** [comment]
Ok, can you add a reference to the SEO recommendation so that we can move forward with a change?

**Comment by xtomas** [comment]
I'm sorry, I don't know what you mean by "add a reference to the SEO recommendation".

**Comment by xtomas** [comment]
I think the content type sitemap source should have option to include homepage and exclude autoroute path of the homepage content item. The main reason is that SEO recommends NOT having duplicate pages, i.e. the same content on multiple URLs. By publishing `/homepage` in `sitemap.xml` we create the duplicate page to the existing (and indexed) homepage on `/` .

**Comment by sebastienros** [comment]
What about detecting when a content item is the home page, and not use the autoroute path but `/`.

**Comment by jtkech** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/12729
