### ISSUE TITLE
Broken link at Tenant setup command

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1217]
![broken-link](https://user-images.githubusercontent.com/1761249/32769149-66675944-c923-11e7-9a88-8f6f6c9d5464.png)

**Comment by sebastienros** [comment]
What values did you enter when you created the tenant?

**Comment by dodyg** [comment]
![values-tenant](https://user-images.githubusercontent.com/1761249/32789998-d29ce42a-c965-11e7-8cd1-49ba58b966ca.png)

**Comment by sebastienros** [comment]
Read this more closely:
![image](https://user-images.githubusercontent.com/1165805/32790304-ef1c9bd4-c912-11e7-9181-13ef2bac2fe3.png)

you need to enter silverkey.demoday.us instead

**Comment by dodyg** [comment]
Damn. OK.

**Comment by sebastienros** [comment]
Feel free to add a PR with some validation logic that would fail if the value starts with `"http"`, that will be a common mistake.
