### ISSUE TITLE
Administrator module link, error message, do not show the left menu item.

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1218]
Disable the module
(Templates), visit http://192.168.1.100:807/OrchardCore.Templates/Template/Index,
Display: The page could not be found.
After the prompt message should display the left menu?
![1](https://user-images.githubusercontent.com/28694676/32774019-f881e780-c965-11e7-9aaf-23b49c554f9c.png)

**Comment by sebastienros** [comment]
Repro:
- Disable Templates module
- Open OrchardCore.Templates/Template/Index
- 404

That's totally expected, if you disable the module then there is nothing to return at this url.

**Comment by pgy866** [comment]
Thank you
