### ISSUE TITLE
Trigger indexing from a recipe

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#12199]
### Is your feature request related to a problem? Please describe.
Currently, when we are creating a search index from a recipe it doesn't build the index. This causes issues with Lucene and Elasticsearch where the Queries won't return any results and also Elasticsearch will log an issue about "all shards failed" if nothing has been indexed yet in its indexes.

### Describe the solution you'd like
As an enhancement. It would be nice to be able to trigger an index to be rebuilt or reset from a scheduled background task as a one-time only task.

**Comment by jtkech** [comment]
Maybe a good candidate for our new `HttpBackgroundJob` component.
