### ISSUE TITLE
Suspicious increment at DistributedShellHostedService.cs 

### ISSUE THREAD

**Issue by VasilievSerg** [OrchardCMS/OrchardCore#12200]
Hello,
I found the suspicious code fragment via PVS-Studio ([V3133](https://pvs-studio.com/en/docs/warnings/v3133/) diagnostic rule).

[Link to the sources](https://github.com/OrchardCMS/OrchardCore/blob/025986695a8cf55682446c25e6c8cecda55d89cc/src/OrchardCore/OrchardCore/Shell/Distributed/DistributedShellHostedService.cs#L99).
Here is the code:
```
// Manage the second counter used to sync the default tenant while it is 'Uninitialized'.
defaultTenantSyncingSeconds = defaultContext.Settings.State == TenantState.Uninitialized
  ? defaultTenantSyncingSeconds++
  : 0;
```

Looks like the increment operator is senseless here.
It doesn't change the state of `defaultTenantSyncingSeconds` variable.

**Comment by jtkech** [comment]
Oops, looks like I didn't retry it after a last refactoring.

I will fix it thanks.

**Comment by jtkech** [comment]
Okay in fact it works because `defaultTenantSyncingSeconds` is auto incremented again just after

                    // Check periodically if the default tenant is still 'Uninitialized'.
                    if (defaultTenantSyncingSeconds++ > DefaultTenantSyncingPeriod)
                    {
                        defaultTenantSyncingSeconds = 0;

So we just need to remove the first post auto increment which is useless.

I will patch it, maybe tomorrow
