### ISSUE TITLE
Can't find Razor Layout.cshtml file

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#12206]
### Describe the bug

Creating a Layout.cshtml razor view in place of Layout.liquid causes error.

### To Reproduce

In a temporary folder, create a solution as follows:

```
dotnet new sln -o TestSolution
cd TestSolution
dotnet new occms -o TestSite
dotnet new octheme -n "TestLiquidTheme"
dotnet new octheme -n "TestRazorTheme"
dotnet add TestSite/TestSite.csproj reference TestLiquidTheme/TestLiquidTheme.csproj
dotnet add TestSite/TestSite.csproj reference TestRazorTheme/TestRazorTheme.csproj
dotnet sln add TestSite/TestSite.csproj
dotnet sln add TestLiquidTheme/TestLiquidTheme.csproj
dotnet sln add TestRazorTheme/TestRazorTheme.csproj
```

I then:
1. open the solution
2. delete /TestRazorTheme/Views/Layout.liquid
3. inside /TestRazorTheme/Views/, create:

_ViewImports.cshtml with this content:

```
@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
@addTagHelper *, OrchardCore.Menu
```

Layout.cshtml with this content:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test</title>
</head>
<body>
    @await RenderBodyAsync()
</body>
</html>
```

4. run the site and create a blog site.
5. switch the theme to TestLiquidTheme, view the site, and all is well.
6. switch the theme to TestRazorTheme, view the site, and get error:

InvalidOperationException: 
The partial view '/Areas/TestRazorTheme/Views/Layout.cshtml' was not found. 
The following locations were searched:
/Areas/TestRazorTheme/Views/Layout.cshtml

I feel like usually there is a much bigger list of search paths e.g. not including the "Areas" segment.

I'm using Windows 11 with the latest version of Orchard templates installed (currently 1.4.0). I also noticed that the docs page says you have to modify the theme's project file to use `<Project Sdk="Microsoft.NET.Sdk.Razor">` but that is already the default.

**Comment by ns8482e** [comment]
Which editor are you using?

**Comment by fuzl-llc** [comment]
Microsoft Visual Studio Community 2019 Version 16.11.18.

**Comment by jtkech** [comment]
You may need to also add a `_ViewImports.cshtml` file.

**Comment by fuzl-llc** [comment]
Yes, I added _ViewImports.cshtml as described above (I messed up using the code tags in the initial posting so you might not have seen it... it should be there now though).

**Comment by ns8482e** [comment]
May be the editor acting weird, if it added cshtml as content then remove that entry from csproj

**Comment by fuzl-llc** [comment]
> if it added cshtml as content

I'm not sure what you mean by this... do you mean in "build action" in properties? It is Embedded resource which I think is correct (it is the same as Layout.liquid anyway).

**Comment by jtkech** [comment]
Did you remove Layout.liquid?

**Comment by fuzl-llc** [comment]
Yes, it was deleted.

**Comment by ns8482e** [comment]
Layout.cshtml needs to be embedded resource in csproj

it seems when you deleted Layout.liquid and added Layout.cshtml the editor might have added it as content 

remove the ItemGroup that adds Layout.cshtml as content from csproj

**Comment by fuzl-llc** [comment]
I don't see an ItemGroup in the TestRazorTheme.csproj for the Layout.cshtml file, but when I select "Layout.cshtml" in Solution Explorer and look at the Properties window's "Build action" it does say "Embedded resource." Am I looking in the wrong place?

Interestingly, I am able to get it to run with the Razor Layout theme in VS Code so perhaps it is something to do with Visual Studio?

**Comment by ns8482e** [comment]
May be! 

VS 2019 is not supported for .net 6 only 2022

**Comment by jtkech** [comment]
Under Visual Studio force a rebuild of the web app, or the theme first

**Comment by fuzl-llc** [comment]
I'm going to upgrade to VS 2022 and then give it a try. Weirdly, I was able to open and run it successfully in Visual Studio after running it successfully in VS Code. Even though it ran, including with the razor theme working, the project didn't load in solution explorer. So something really weird is happening and it sounds like Visual Studio 2022 might be the best next step... thanks - will update when done.

**Comment by fuzl-llc** [comment]
That fixed it. Thanks to you both! I'm coming back to Orchard after a long break and even though I think read somewhere it was now .NET 6 only, I didn't know I needed to upgrade to VS 2022. I'm actually sort of surprised it worked as much as it did in VS 2019. Thanks again!
