### ISSUE TITLE
Shall we let ContentPickerField support the firstValue  in Graphql

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#12221]
just like tihs:

``` graphql

 industry {
    firstValue 
    firstContentItem {
      displayText 
    }
  }
```

Or who can tell me how to replace the registered `ObjectGraphType`

There are some problems covering this type in my project..
Maybe I didn't find the right way

**Comment by sebastienros** [comment]
What is the current result from GraphQL with such field?

**Comment by hyzx86** [comment]
> What is the current result from GraphQL with such field?

Array only 
``` graphql
industry { 
    contentItemIds
    contentItems
+    firstValue 
+    firstContentItem {
+      displayText 
+    }
  }
```

**Comment by hyzx86** [comment]
I think firstValue should be able to hold all locations, such as `Media`, `ContentItems`, `Users` 
and all collection types. 

This problem is raised because some front-end frameworks are not very friendly to the content binding of array types

But now it seems to be OK
1. I don't need that frame anymore
2. I added this field to the existing type in my project
