### ISSUE TITLE
Page not found error for taxonomy part

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#12227]
### Describe the bug
There is a page not found error when trying to view the taxonomy part's edit page.

### To Reproduce
It should repro on any site, but I did this on a standard "Blog" recipe site:
1. Go to "Admin > Content > Content Definition > Content Types"
2. Click the "Taxonomy" link
3. Scroll down to the "Parts" section and click the "Taxonomy" part row's "Edit" button.
4. On the resulting page, click the "Part Definition" link.
5. See "The page could not be found" error at "/Admin/ContentParts/Edit/TaxonomyPart" URL.

### Expected behavior
Normally this link sends you to the same page as if you'd gone to "Admin > Content > Content Definition > Content Parts" and clicked the edit button for a part. However, there is no Taxonomy part listed. I know Taxonomies are sort of special so maybe this is by design that they are not listed but then the broken link should not be shown.

**Comment by Piedone** [comment]
Such hidden parts correctly don't have an edit link anymore, thus this isn't now an issue.
