### ISSUE TITLE
Change project editorconfig to use underscore (_) instead of (this.) when creating new fields

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12232]
### Describe the bug

When injecting new service in a class constructor, VisualStudio suggest the use `this.` syntax to initialize the variable as you can see in the following screenshot.

![image](https://user-images.githubusercontent.com/24724371/185757212-75d920cf-516a-4708-8a9d-5b55a31c7285.png)

When using the above suggestion, the output will look like this

```
public class OrchardCoreExample
{
    private readonly IContentManager contentManager;

    public OrchardCoreExample(IContentManager contentManager)
    {
        this.contentManager = contentManager;
    }
}
```
The above is not the style use in the OrchardCore solutions. I suggest we change the editor to the following instead

![image](https://user-images.githubusercontent.com/24724371/185757080-563e88d1-6d14-4cee-8cab-5a3c23bfdfbd.png)

So the new suggested code will look like this by default

```
public class OrchardCoreExample
{
    private readonly IContentManager _contentManager;

    public OrchardCoreExample(IContentManager contentManager)
    {
        _contentManager = contentManager;
    }
}
```

**Comment by hishamco** [comment]
I don't think we use `this` in our code base but I never mind to add this to code config

**Comment by MikeAlhayek** [comment]
Yes. We do not use `this.` this change will make sure the IntelliSense to not even suggest `this.` and suggest the use of `_` instead

**Comment by hishamco** [comment]
I know, we already did it without intellisense ;)
