### ISSUE TITLE
meaning between  "MaxPageSize" and   "MaxPagedCount"

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#12239]
### Expected behavior
under namespace OrchardCore.Contents.Controllers
{
    public class AdminController : Controller

line 243:
  if (_pagerOptions.MaxPagedCount > 0 && pager.PageSize > _pagerOptions.MaxPagedCount)
            {
                pager.PageSize = _pagerOptions.MaxPagedCount;
            }
It seems that MaxPagedCount  should be MaxPageSize

**Comment by MikeAlhayek** [comment]
I think the `MaxPagedCount` is the absolute max count we are willing to fetch even if `PageSize` is greater than it. It’s a safety catch all setting. So if the user put 10000 in the admin settings, we’ll ignore the 10000 and fallback to `MaxPagedCount`. However, if `MaxPagedCount` is 0, we don’t have security of fall place and we’ll always take what ever the use provide in the UI.

**Comment by MikeAlhayek** [comment]
I think `MaxPagedCount` should be eliminated since `MaxPageSize` isn’t configurable from the UI.  `MaxPageSize` would only come from the appsettings only with a default value of 0. So if the app sets `MaxPageSize` is set, then we should enforce that `PageSize` is less than `MaxPageSize`
