### ISSUE TITLE
Return X-Powered-By header

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1224]
Instead of relying on the meta tag from resource manager.

**Comment by sebastienros** [comment]
I suggest to inject it from a middleware, even for Orchard Core Framework, but provide an option object to opt out. No version.

**Comment by matiaskusack** [comment]
Ok, I'm taking this as my first contribution. I've thougth on implementing it as an option in services.UseModules extension of ModularApplicationBuilder.

It would be something like:
``
app.UseModules(builder => builder.UsePoweredByOrchardCore(enabled: true));
``

Is that a good approach?
