### ISSUE TITLE
Workflow: LoggedIn-Event - User Object not available at this point

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#12250]
I tried to use the user event `LoggedIn` to check for specific roles and stuff, but there is a problem with the event timing i think.
When i use this event as the start event of the workflow, there is no user object to access, neither any liquid helper related to users work nor the `Validate User` task.

OC 1.4.0

**Comment by Piedone** [comment]
This isn't an issue anymore:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/8b2b968e-dcf5-48c1-bb73-afb25695e4e2)
