### ISSUE TITLE
After parsing a value an unexpected character was encountered - Workflow error

### ISSUE THREAD

**Issue by Aurwa-Karrom** [OrchardCMS/OrchardCore#12258]
I'm trying to create a content type using workflows
But I get an error when I send a link or a picture by trumbowyg.. some help please
![image](https://user-images.githubusercontent.com/95365727/186362123-900e4945-58e8-4403-8343-905ad0abc088.png)
![68747470733a2f2f66696c65732e6769747465722e696d2f3539656137646433643733343038636534663761666664312f624f77652f7468756d622f696d6167652e706e67](https://user-images.githubusercontent.com/95365727/186362156-ec19223d-5e41-404d-8f43-7f6cec53cd41.png)

The error I'm getting:After parsing a value an unexpected character was encountered: h. Path 'Ticket.Description.Html', line 6, position 36.

**Comment by ahmedtabba** [comment]
Try to replace the double quotation " with a single quotation '
This error happened because when you add a link at the html editor it will wrap the href attribute with a double quotation and that causes the conflict

**Comment by Aurwa-Karrom** [comment]
You're awesome, thank you very much..it's working now
