### ISSUE TITLE
Form SelectInput does not show the options editor when added to the DOM

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12267]
### Describe the bug
When trying to add "Select Input" while creating a form, the option editor isn't loaded. Also, the edit button, does not open the modal that would allow you to populate the options using json. If the content is saved, and the page is loaded again then modal and the options editor works just fine.

### To Reproduce
1. Enable `OC.Flows` and `OC.Forms` module
2. Create content type `Test` with `FlowPart` and make it creatable
3. Create a new content item of type `Test`, then add "Select Input" widget

### Expected behavior
I should be able to click on the Edit button and the modal should show up. I also should be able to add options when the Select Input is added to the DOM

### Screenshots
Before the content-item is saved
![image](https://user-images.githubusercontent.com/24724371/186720403-0324db59-f46e-4977-b905-b21444cce8a5.png)

After the content-item is saved
![image](https://user-images.githubusercontent.com/24724371/186720844-2948ab35-4071-479e-8511-cd6ee24cb5da.png)

**Comment by Skrypt** [comment]
This one may be because of BS5 regression.

**Comment by MikeAlhayek** [comment]
humm. It works after the save. It's likely due to initializing error when the widget is added on the fly.

**Comment by Skrypt** [comment]
Yes, the entire script element is not added to the footer of that page.
So the initializeSelectOptionsEditor() is not called.
