### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by Qwiziz** [OrchardCMS/OrchardCore#12266]
Hello!
I checked the project with the PVS-Studio analyzer and found several suspicious code fragments. Would you like to take a look at them? I published the [article](https://pvs-studio.com/en/blog/posts/csharp/0982/) that describes the most interesting analyzer warnings.
If you want to see all of the warnings, try a free PVS-Studio version ([more details here](https://pvs-studio.com/en/order/open-source-license/)).

**Comment by hishamco** [comment]
Thanks for reporting this, I may have a look to the reported issues in your blog post

**Comment by hishamco** [comment]
We already fixed more than 90 - 97% of the reported issues in the mentioned blog post, just left two or three because they need some thinking to avoid breaking things
