### ISSUE TITLE
Add Listable or IsOnDemand flag to features

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12279]
### Is your feature request related to a problem? Please describe.
Provide a way to define a feature as "Not Listable" on the Features UI. This would be very useful when we need to create a module that defined generic services that could be used by other features.

Here is an example, I want to create a feature that would allow the app-user to receive notifications from the website (Any kind of notification, email, web, SMS, push, etc)
With any notification method/provider, I would need some common services. For example,
1. `UserNotificationDisplayDriver` to allow the user user to select notification types to use "from available services". 
2. `NotificationCoordinator` that would be responsible to sending the message to the any service that is listening.
3. possible common services.

So I would create a feature called `Notifications` that is NOT listable" so the user can't enable alone since it's not useful by itself (this will eliminate some confusion). This feature would allow me to provide common setup/services "listed above". But this feature would only be available if other modules depend on it.

So now, I would create a second feature called `Notification.Email`. This feature would depend on `Notification`, and would only register `Email` related services by implementing key services defined in `Notification.Abstractions` project.

Now, the user will be able to enable "Email Notification", "Push Notification" or any other feature and since all these features depend on "Notification" feature, we don't need to worry about redundant service registration. Also, the site Admin won't get confused by seeing a listed feature called "Notifications"

### Describe the solution you'd like
Add a "Listable" flag in the `FeatureAttribute` and honor it in the `OC.Features.AdminController`

**Comment by jtkech** [comment]
This make me think about the `[RequireFeatures(...)]` allowing a module/feature to define functionalities (not listable as regular features) that are auto validated if the required features are enabled.

**Comment by MikeAlhayek** [comment]
Hum, `[RequireFeatures()...]` provides you a way to change/add new behavior when multiple features are enabled. What I am suggesting here is to make a feature not visible on the UI. so we can still use `[RequireFeatures(...)]` if needed. But in the above example, it won't work unless `Notifications` is enabled first.  

So my manifest will look something like this
```
[assembly: Feature(
    Id = "OrchardCore.Notifications",
    Listable = false
)]

[assembly: Feature(
    Id = "OrchardCore.Notifications.Email",
    Name = "Email Notifications",
    Dependencies = new [] { "OrchardCore.Notifications" }
)]

```

**Comment by jtkech** [comment]
Yes at some point at least one of your module/feature would need to be enabled. But then you can define many functionalities (not features so not listable) that would be auto validated, e.g. dedicated startups that register dedicated services and that would be executed only if their required feature(s) are enabled.

**Comment by MikeAlhayek** [comment]
@jtkech  Are suggesting something like extension for `IServiceCollection` that would register common service?

```
public static class ServiceCollectionExtensions
{
    public static void RegisterNotificationCore(this IServiceCollection services)
    {
          //...
    }
}
```

If that is your suggestion, that is exactly what I am doing now as a workaround. But, it's not really ideal. For example, I need to register a display driver. A display driver, should only be registered once. So if I call `services.RegisterNotificationCore()` in `EmailNotificationStartup` and also in `PushNotificationStartup` then the driver would be registered twice which is bad. So as a workaround, I would do something like this 

```
public static class ServiceCollectionExtensions
{
    public static void RegisterNotificationCore(this IServiceCollection services)
    {
        if (!services.Any(x => x.ServiceType == typeof(IDisplayDriver<User>) && x.ImplementationType == typeof(UserNotificationPartDisplayDriver)))
        {
            // avoid registering the driver more than one time.
            services.AddScoped<IDisplayDriver<User>, UserNotificationPartDisplayDriver>();
        }
    }
}
```
Obviously that is one example. In other examples, the "base" (aka `Notifications` feature, may expose routes to an admin controller. The admin controller only depends on interfaces, so as long as there is one service the controller will do its work. This is another example why having a common startup feature is great.

**Comment by jtkech** [comment]
Yes just ideas on the fly, as usual would need more time to better understand the scenarios.

I will re-read your comments later on, hmm maybe what you need (but not sure) is a new attribute that doesn't check that all required features are enabled but that check that only one of them is enabled ;)

Notice that you can also decorate controllers with the `[RequireFeatures(...)]` attribute.

**Comment by jtkech** [comment]
You can also use the `services.TryAddScoped<>()` pattern.

**Comment by MikeAlhayek** [comment]
@jtkech `TryAddScoped<>` does not work for generic registration.

So if you call `services.TryAddScoped<IDisplayDriver<User>, UserNotificationPartDisplayDriver>();` 3 times, it'll get registered 3 time. Yes, we could create a better implementation of `TryAddScoped`. But what when you want to provide a common controller to work for implementation module? Do we really, need to also create Extension method for the routes? and if we do, how can we decorate the controller with a `Feature()` attribute that would only be available in more than one feature.

**Comment by jtkech** [comment]
I'm lost ;)

Yes if it is much more complicated than just adding a Listable property, will think about it, was just to be sure we don't add useless things. On the fly, in some places we use marker interfaces to know if some service(s) was registered, as aspnetcore uses.

Hmm, what happens if at some point you want to use different implementations of `Notifications`.

**Comment by ns8482e** [comment]
@MikeAlhayek IMO if feature is not a feature on its own but just a dependency for other concrete feature then it’s really not a feature 

here you are really trying to find a way how to register dependency

if that’s the case then you can create shared project containing the extension method for service collection and add needed method using TryAddxxx

**Comment by MikeAlhayek** [comment]
@ns8482e I understand what you are saying. Please review my previous response to @jtkech. I am trying to create a feature that isn't manageable using the Feature UI to eliminate confusion and listing unnecessary features. Basically a feature that can't exists alone and require a companion. So it is a feature that provides services, controller and routes.... but it just can't exists alone. Think of this feature as the interface/contract for other features.

**Comment by MikeAlhayek** [comment]
@jtkech It is as simple as adding `Listable` property and honor it in the Features  admin. I'll submit a PR so it can be looked at. If more than one notification implementation, then the base notification would know how to handle it using a `NotificationCoordinator` service.

**Comment by ns8482e** [comment]
@MikeAlhayek  what you are describing is IMO - for not listable feature technically are always active on default application feature that are not usable/accessible until `RequreFeatures` are active.  

For example following class will only available when `feature B` is active.
```cs
[RequireFeatures("B")]
[Feature(Application.DefaultFeatureId)]
public class  Myclass 
{
}
```

Defining your services using `Application.DefaultFeatureId` will not list in Features UI

**Comment by MikeAlhayek** [comment]
@ns8482e that will always activate that feature which isn’t what I really want. I just want to be able to activate a feature “upon need”. Activating resources by default is a waste of resources specially if it’s not needed.  I am aware the difference between both attributes and use them all the time.  But they are not good fit for the examples I posted above

**Comment by ns8482e** [comment]
@MikeAlhayek  using `RequireFeatures`  doesn't activate the the feature until dependency are met.

**Comment by hishamco** [comment]
I didn't read all the comments, but

> So I would create a feature called Notifications that is NOT listable" so the user can't enable alone since it's not useful by itself (this will eliminate some confusion). 

Why you are not using `AlwaysEnabled`, so you can avoid to disable the feature accidentally

**Comment by MikeAlhayek** [comment]
@hishamco because this isn't a feature that is always enabled. It's a feature that is always enabled only when the dependents are enabled.

@ns8482e, @jtkech the PR #12281 is ready to be reviewed which may help explaining the concept.

**Comment by MikeAlhayek** [comment]
I think this flag should be called `IsOnDemand` instead of `Listable` since the key here is making this feature available on-demand, and we'll keep it listed in the Features UI without a way to enable/disable it.

**Comment by jtkech** [comment]
This is what I suggested at some point, based on a feature state, e.g. `ByDependencyOnly`.

**Comment by MikeAlhayek** [comment]
@jtkech Alright, so you agree with the concept here. I just need to rename `listable` at this point. I feel naming it `IsOnDemand` is more appealing to me than `ByDependencyOnly` for some reason. Not sure, any other suggestions on a name?

**Comment by jtkech** [comment]
Yes here https://github.com/OrchardCMS/OrchardCore/pull/12281#issuecomment-1229051485 I was suggesting on the fly `EnabledOnlyByDependency` ;)

Hmm yes `EnabledByDependencyOnly` (not `EnableByDependencyOnly`) looks better.

About the concept at least I got it, but it implies a lot of changes, I will think about it, need more time.

**Comment by MikeAlhayek** [comment]
okay. I'll change it to `EnabledByDependencyOnly`. When you review the PR, let me know if you have better/shorter idea.

**Comment by jtkech** [comment]
Okay no problem.

Hmm, just thinking about the case of an `EnabledByDependencyOnly` feature that can be auto enabled/disabled, and that is also `IsAlwaysEnabled` and/or  `DefaultTenantOnly`.

**Comment by MikeAlhayek** [comment]
I think if a module is always enabled, then you can’t disable it. In a way, it does not make since to have always enabled + EnabledByDependency. So it’s one or the other. I don’t think it matter if DefaultTenant or not in this case. Probably I would need to add a check of AlwaysEnabled we ignore the EnabledByDependeny flag. I’ll try to finish up the PR tomorrow so you can look at it.

**Comment by MikeAlhayek** [comment]
Yeah I actually just check the code. DefaultTenantOnlyFeatureValidationProvider Ensures that DefaultTenants features are only available to default tenant. Meaning if you want `EnabledByDependencyOnly` and `DefaultTenantOnly` you are free to do that. So the only check that is needed is to ensure that `EnabledByDependencyOnly` Is ignored when `IsAlwaysEnabled` is used

**Comment by MikeAlhayek** [comment]
The PR is finally ready. Here a summary of what concept with updated terminology

A feature with `EnabledByDependencyOnly`, will automatically get enabled/disabled as needed by other features.

Let's say we have the following features

```
[assembly: Feature(
    Id = "OC.Notification",
    EnabledByDependencyOnly = true
)]

[assembly: Feature(
    Id = "OC.Notification.Email",
    Dependencies = new[]
    {
        "OC.Notification"
    }
)]

[assembly: Feature(
    Id = "OC.Notification.Push",
    Dependencies = new[]
    {
        "OC.Notification"
    }
)]

[assembly: Feature(
    Id = "OC.Notification.Web",
    Dependencies = new[]
    {
        "OC.Notification"
    }
)]
```

`OC.Notification` will automatically get **enabled** when **any** of `OC.Notification.Email`, `OC.Notification.Push`, or `OC.Notification.Web` are enabled.

At the same time, `OC.Notification` will automatically get **disabled** when **all** of `OC.Notification.Email`, `OC.Notification.Push`, and `OC.Notification.Web` are disabled.

The key difference between `EnabledByDependencyOnly` and `IsAlwaysEnabled` is that the latter will always be enabled regardless or if it's needed or not.

Checkout the PR for other info including a screencast.

**Comment by hishamco** [comment]
Again I'm too later with your discussion with @jtkech ;) I have few comments or enhancements. `EnabledByDependencyOnly` the naming is hard ;) I'm suggesting to add a property named `EnabledMode` which is of type enumeration as the following:

```csharp
public enum FeatureEnablingMode
{
    Auto,
    Dependency,
    User
}
```

`Auto` might trigger `IsAlwaysEnabled`, so we could remove `IsAlwaysEnabled` later

`Dependency` enabled the feature by its dependencies, either one or all

`User` enabled the feature by the user which is the default one

**Comment by jtkech** [comment]
Note: Here we are talking about manifest data that are not full feature properties but more like  settings/metadata used at an higher level e.g. by the `OC.Features` code and UI, e.g. nothing prevents to disable by code an `IsAlwaysEnabled` feature, for more details read the comments in the related PR.

Anyway it would be a breaking change to use an enum, but using the term `Auto` for `IsAlwaysEnabled` is not good because `IsAlwaysEnabled` needs as other features to be first enabled, the difference is that it can't be disabled afterwards.

`Auto` would be more related to `EnabledByDependencyOnly` as it would be auto-enabled when we enable one of its dependent, but not only as it would be also auto-disabled when we disable all its dependents.

The term `Dependency` is not enough as all features are already auto enabled when we enable a dependent, the difference is that features that are not `EnabledByDependencyOnly` can also be enabled explicitly through the admin UI, so the suffix `Only` is important.

> enabled the feature by its dependencies, either one or all

This is wrong, a feature is not enabled by its dependencies but by its dependents. When a given feature A has in its dependents a feature B, it means that the feature B has in its dependencies the feature A. So, `ByDependency` just means by using the dependency graph, e.g. we could have used `ByAnyDependent`.
