### ISSUE TITLE
OrchardCore.MediaLibrary creating new folder bug

### ISSUE THREAD

**Issue by janjindracek** [OrchardCMS/OrchardCore#12272]
### To Reproduce
1. Go to Media library
2. Click on the "plus" button, which creates a new folder
3. Opens a dialogue
4. Create a new folder
5. Try to click on "Cancel" or the cross button"

### Expected behavior
The folder creation dialog should close after the folder is created

### Actual behavior
The cross/Cancel button does nothing, user has to click on the grey background behind the dialogue to close

### Screenshots
![image](https://user-images.githubusercontent.com/55285501/186878800-1be8d8b4-9c92-4aac-851a-63f7d6a4e200.png)

**Comment by hishamco** [comment]
@Skrypt it's in your plate ;)

**Comment by hishamco** [comment]
Unless we should wait for the upcoming release

**Comment by Skrypt** [comment]
This bug is fixed in the main branch. I'm pretty sure.

**Comment by hishamco** [comment]
@janjindracek please wait for the upcoming release 1.5.0
