### ISSUE TITLE
How to prevent HTML in markdown Body on Alias  

### ISSUE THREAD

**Issue by Syed-Hasnain-Askari** [OrchardCMS/OrchardCore#12274]
Folks, I have content Type in which markdown Body part also markdown is add, for example the Alias of that content type is /software/register. When I type "~/register" instead of /article/register so all the HTML shows in browser window, see below:

![image](https://user-images.githubusercontent.com/47834896/186919726-0295eeaa-c7cd-4182-bf94-e8f60fdebb69.png)

but when we go with proper alias so page render proper design where we have html from also:

![image](https://user-images.githubusercontent.com/47834896/186951476-ffaef477-7553-4953-b397-57750b4b94e3.png)

I want to prevent to show the raw html please advise @ns8482e @hishamco @Skrypt 
Need your kind attention on above.

**Comment by Skrypt** [comment]
duplicate
