### ISSUE TITLE
 Trumbowyg Editor - Image as base64

### ISSUE THREAD

**Issue by Aurwa-Karrom** [OrchardCMS/OrchardCore#12275]
I'm adding image as base64 using the Trumbowyg editor but when I publishing .. the image src disappear

**Comment by hishamco** [comment]
How and where did you add it?

**Comment by Aurwa-Karrom** [comment]
In Content Type as Html Field

**Comment by hishamco** [comment]
Is HtmlSantizer enabled?

**Comment by Aurwa-Karrom** [comment]
Yes, I disabled it, and it works now
But is this good?
Because this content type will be filled in by users, I might get xss attack

**Comment by Skrypt** [comment]
You should configure the HtmlSanitizer instead of disabling it.

**Comment by Aurwa-Karrom** [comment]
Can I get some help with configuration

![image](https://user-images.githubusercontent.com/95365727/187022522-a3adfac6-ad62-4f01-929e-6292a7147ee9.png)
![image](https://user-images.githubusercontent.com/95365727/187022525-4947fe95-16e4-4639-b9c1-69a18022c4cc.png)

Isn't the src attribute supposed to remain by default?

![image](https://user-images.githubusercontent.com/95365727/187022729-b6ffa319-df1c-43ab-9077-889b5165ebee.png)
