### ISSUE TITLE
OpenId settings page not displaying in admin

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#1229]
After enabling the OpenId module I am currently not seeing any settings pages appear in the admin area.

I created a module with a display driver that extends SectionDisplayDriver<ISite, MySettings> and getting the same issue.

branch: dev
last commit date: 14/11/2017

**Comment by sebastienros** [comment]
I checked other settings and they work (layers, general, ...)

**Comment by sebastienros** [comment]
Have you registered it in the Startup? Is the driver hit?

**Comment by agriffard** [comment]
Using the dev branch, I added the OpenId project as a dependency to  OrchardCore.Application.Cms.Targets.

Then I enabled the OpenId feature.

The settings page appears in the menu and is available at this url: http://localhost:2918/Admin/Settings/open%20id

![image](https://user-images.githubusercontent.com/703248/32914146-d9b0b574-cb14-11e7-8e44-4386ea52dff0.png)

**Comment by petedavis** [comment]
Found that I had an old binary being loaded as I couldnt get a breakpoint to load
