### ISSUE TITLE
Render form widgets in a custom template instead of using Widget.cshtml Widget

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12296]
### Is your feature request related to a problem? Please describe.
Currently, all of the form widgets are rendered using `Widget.cshtml` which renders too much html without any added value. Also, by default the create form does not look well formatted by default because of this.

### Describe the solution you'd like
I think we should create default `Widget-Form`, `Widget-Input`, `Widget-Label`, Widget-Select`, `Widget-Validation` and `Widget-ValidationSummary`

Really all these templates should need only this

```
<div class="@String.Join(" ", Model.Classes.ToArray())">
    @await DisplayAsync(Model.Content)
</div>
```
Only the `Widget-Select`, `Widget-TextArea` and `Widget-Input` should have this

```
@{
    Model.Classes.Add("mb-3");
}
<div class="@String.Join(" ", Model.Classes.ToArray())">
    @await DisplayAsync(Model.Content)
</div>
```

**Comment by sebastienros** [comment]
Assuming the solution is to create new shapes that will morph by default to Widget.cshtml.

**Comment by sebastienros** [comment]
I agree with the proposal, @ns8482e I didn't see any comment on the PR about this change, do you agree also?

The only breaking behavior is if users haven't defined any custom template for form elements (or widget.cshtml) in their front-end theme.

**Comment by ns8482e** [comment]
@sebastienros I agree, it’s similar to what we have for RawHtml template.

As this being for front-end the override needs to be in ootb themes, so if users have override these templates on their theme, changes to ootb has no effect on users custom theme
