### ISSUE TITLE
UI: TextField settings bugs

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#12303]
### Describe the bug

After updating to 1.4, there are some UI bugs in textfield. Tested also on https://try.orchardcore.net/

1/ Edit placements dropdown does not open on click (seems like css/js problem). Works in other field types (e.g. HtmlField)
2/ TextField dropdowns do not have arrow

### Screenshots

![image](https://user-images.githubusercontent.com/52829889/187635135-7b69aee3-0730-4cd3-8f78-13719dfc0084.png)

![image](https://user-images.githubusercontent.com/52829889/187635268-1eba865e-c1b8-47f0-a13a-ef7f89c1cd5c.png)
![image](https://user-images.githubusercontent.com/52829889/187635645-be43967d-ec5c-4284-9a22-84336053e6ba.png)

**Comment by hishamco** [comment]
@MikeKry can you check in the nightly build, if it's still exist please add "bug" label because we need to fix it before the next release

**Comment by Skrypt** [comment]
I assume that you used a "predefined list" editor for that TextField. I tested on latest `main` branch and I can see the arrow on the dropdown.

**Comment by MikeKry** [comment]
@Skrypt 

Yes, it is a predefined list, but it seems that was broken also e.g. in email settings
![image](https://user-images.githubusercontent.com/52829889/188652257-8a6a8f09-611d-4b63-b8b2-6fdd59ebe746.png)

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/188703268-254dff42-b4fa-41c6-816b-8630f18c3ea9.png)
 
Seems to be fixed in main branch.
