### ISSUE TITLE
SlugService should not leave a trailing hyphen

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#12317]
### Describe the bug
If your string ends with a non digit/letter you end up with a trailing hyphen in the slugified value.

### To Reproduce
OC 1.4, create a site using the blog recipe

You can see this in a number of cases.

1. Create a new Page and end the title with a period.
![image](https://user-images.githubusercontent.com/68876423/188234743-9bedf231-8c19-4efe-bdf3-00fdc8ec3658.png)

Now I admit ending a page title with a period is a little usual, but you can also see this with other cases that might not be so unusual.

2. Enable the "media slugify" feature and upload the following example: The team (2020).jpg (as seen [here](https://docs.orchardcore.net/en/dev/docs/reference/modules/Media.Slugify))

The filename becomes the-team-2020-.jpg
![image](https://user-images.githubusercontent.com/68876423/188235242-27b26c46-d4c3-4285-9d03-759004a8ed2b.png)

3. I made an example taxonomy for authors. One of my taxonomy terms is "Smith, John B.". The slugified route becomes "smith-john-b-".
![image](https://user-images.githubusercontent.com/68876423/188235576-770c7bcb-db9b-4c06-a46b-7f9c6d2f0389.png)

![image](https://user-images.githubusercontent.com/68876423/188235600-9006e80a-abeb-4a91-95fc-7a2f4faafb04.png)

**Comment by hishamco** [comment]
Seems you added a dot at the end, that's why hypend has been added

**Comment by sebastienros** [comment]
> Seems you added a dot at the end, that's why hypend has been added

That shows the bug, we need to be fix it.

**Comment by hishamco** [comment]
If we accept the dot to be at the end I will submit a fix for it

**Comment by hishamco** [comment]
It's at the end, so no action needed here

**Comment by sebastienros** [comment]
The bug to fix is "this-is-ending-with-dot-" should be "this-is-ending-with-dot"

**Comment by hishamco** [comment]
It's in my plate now
