### ISSUE TITLE
Separate operation of the database

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1234]
Create a new database, you can manage and operate, and can choose a database for tenants, One a database can be used by multiple tenants。
新建一个数据库，可以管理与操作，并可以为租户选择数据库，一个数据库可以在多个租户中使用。

**Comment by awyl** [comment]
You can already do that now when you setup a new tenant. Select a database instead of `None`.

Use a same database and connection string and use a different prefix for different tenant, they can coexist in the same database.

**Comment by pgy866** [comment]
@awyl Thank you very much。
