### ISSUE TITLE
  Feature suggestion: Orchard Membership Module

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1235]
Orchard Membership  Module
Separated from the site administrator,
For the site's front-end Membership management and development,
You can configure user groups, member connections.
You can set up a Membership as a site administrator.
Orchard Membership DATA。

Orchard  会员  模块
与站点管理员分离，
用于网站的前端Membership 的 管理和开发，
可以配置用户组、会员连接。
可以设置某个Membership为站点管理员。
Orchard 会员数据库

**Comment by sebastienros** [comment]
Can be done as a separate module, we tend not to add custom front end modules.
