### ISSUE TITLE
Whether the Yarp Gateway function module can be provided in a future release

### ISSUE THREAD

**Issue by vipwan** [OrchardCMS/OrchardCore#12355]
Whether the Yarp Gateway function module can be provided in a future release, If can use Yarp and OpenIdDic together, it's perfect

**Comment by jtkech** [comment]
I started to look at it but 2 years ago ;

But we may still plan to use it for example to do some kind of OC Tenants load balancing among different OC nodes served by different servers.

**Comment by Skrypt** [comment]
If we compare it to NGinx then it is never bundled as part of a web application. I would need to look at it but it feels like it should be something that gets implemented as a standalone service that will be invoked directly and that will proxy the calls to other internal apps.

**Comment by vipwan** [comment]
At present, more and more NET developers are moving closer to microservices, and the OC Framework itself has such a gene, if the OC Framework can integrate gateway load balancing authentication and link tracing, it will definitely shine in this regard

**Comment by Piedone** [comment]
What is it that you're looking for, exactly? You can already use YARP with Orchard without any further development (we're doing that too).

**Comment by Piedone** [comment]
Hmm, I don't really see the appeal of packaging it up as a module. Perhaps only to add simple redirect rules from the admin, but otherwise you'd have to configure it from code anyway.

**Comment by Skrypt** [comment]
I never used it so far so I can't say much. We already have a Proxy module in OC so I assumed that he wanted something like that.

**Comment by Piedone** [comment]
The Clusters feature is tracked under https://github.com/OrchardCMS/OrchardCore/issues/13636 now.

**Comment by weirdyang** [comment]
> What is it that you're looking for, exactly? You can already use YARP with Orchard without any further development (we're doing that too).

do you mind providing an example? is this in a module or in the host application?

**Comment by hishamco** [comment]
FYI https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.ReverseProxy.Yarp/README.md if you want an extra feature you can file an issue in the related repo

**Comment by Piedone** [comment]
> > What is it that you're looking for, exactly? You can already use YARP with Orchard without any further development (we're doing that too).
> 
> do you mind providing an example? is this in a module or in the host application?

YARP is set up in a simple vanilla ASP.NET Core app, hosted in a container. This sits in front of the OC app, which is a separate app, hosted separately. That is all.

I don't think you need anything else for when you do this; but on Azure, and perhaps otherwise as well, you definitely need something like our [`UseForwardedHeadersForCloudflareAndAzure`](https://github.com/Lombiq/Helpful-Libraries/blob/4c4e42e74c5ecd08b438e3485a9ba36b5c2bbd5b/Lombiq.HelpfulLibraries.AspNetCore/Extensions/ForwardedHeadersApplicationBuilderExtensions.cs#L25) too.

**Comment by weirdyang** [comment]
> > > What is it that you're looking for, exactly? You can already use YARP with Orchard without any further development (we're doing that too).
> > 
> > 
> > do you mind providing an example? is this in a module or in the host application?
> 
> YARP is set up in a simple vanilla ASP.NET Core app, hosted in a container. This sits in front of the OC app, which is a separate app, hosted separately. That is all.
> 
> I don't think you need anything else for when you do this; but on Azure, and perhaps otherwise as well, you definitely need something like our [`UseForwardedHeadersForCloudflareAndAzure`](https://github.com/Lombiq/Helpful-Libraries/blob/4c4e42e74c5ecd08b438e3485a9ba36b5c2bbd5b/Lombiq.HelpfulLibraries.AspNetCore/Extensions/ForwardedHeadersApplicationBuilderExtensions.cs#L25) too.

thanks i figured it out, I need to implement my own IProxyConfigProvider to allow for dynamic configuration (e.g. allowing user to customize via a UI and then apply the changes)
