### ISSUE TITLE
ContentAnchorTag is broken.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#12376]
@hishamco Looks like ContentAnchorTag is broken since #12326 

![Post List Broken](https://user-images.githubusercontent.com/8586360/189558695-e74c098b-2729-41dc-8486-911c557bd6e1.png)

**Comment by hishamco** [comment]
Oh really, let me check ..

**Comment by jtkech** [comment]
Look at #12377
