### ISSUE TITLE
Fix Context Type filter font color

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12371]
### Describe the bug
When viewing the Manage contents section, the "Content Type" filter has a different text color than the other filters. I think it would look better if it matches the other filters.

![image](https://user-images.githubusercontent.com/24724371/189536365-fe83041f-de31-4ba5-9d9c-22d01898f9a0.png)

**Comment by hishamco** [comment]
I already saw this UI issue long time ago but I didn't log it, thanks you do it in my behalf ;)
