### ISSUE TITLE
When the roles feature is disable the site breaks

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12406]
### Describe the bug
If the user disable the roles module the site crashes because the Users needs the following services to work
 - IRoleService
 - RoleManager<IRole>
 - IRoleStore<IRole>

### To Reproduce
1. Disable the Roles module

### Expected behavior
No exception when disabling the roles module.

There are 2 possible fixes here. 
 1. In the users module add `OrchardCore.Roles` to the dependency list. But this would force the user to use the roles modules to be able to authenticate users in OC.
 2. Add the following services to the Users startup file
```
services.TryAddScoped<IRoleService, RoleService>();
services.TryAddScoped<RoleManager<IRole>>();
services.TryAddScoped<IRoleStore<IRole>, RoleStore>();
```

But to do we have to move `RolesDocument`, `RoleService` and `RoleStore` from `OrchardCore.Roles` to `OrchardCore.Roles.Core` which I believe where they should live anyway.

**Comment by hishamco** [comment]
Ya disabling the module breaks everything

**Comment by sebastienros** [comment]
Add a feature dependency from Users to Roles?
Or maybe some change was added at some point that resolves these services from Users, and it should not.

**Comment by MikeAlhayek** [comment]
@sebastienros if we add dependency `OrchardCore.Roles` to `OrchardCore.Users` using the mainifest file, we will force the user to always use the Roles module and I don't know that this is what we want to introduce here.

Another option we can do is add a new implementation on `IRoleStore<IRole>` in the Users that just returns completed tasks and we can add that using `TryAddScopped<>` so that way it won't override OC.Roles but it will prevent the site from breaking

**Comment by hishamco** [comment]
User should work without roles, adding this dependency is good and bad

**Comment by MikeAlhayek** [comment]
@hishamco I agree which is why I don't think we should add dependency to Roles using the mainifest. I am going to update the PR by creating an empty store and see if that works for the team.

**Comment by jtkech** [comment]
From memory we deal with standard aspnetcore services and generic interfaces for our custom `IUser`, then yes as I can see for example `UserStore` injects `IUserRoleStore<IUser>`.

If we keep it without any dependency as it is currently, so not really as a feature dependency but as a requirement to provide concrete implementations of standard aspnetcore roles interfaces. So if the Roles feature is not enabled, we should provide concrete implementations, e.g. by enabling another feature or any other way to register these Roles services at the tenant level.

We could think about a dependency of Users => Roles, and if we want other Roles implementations enable another feature that would also depend on Roles so that its startup is run after allowing it to override Roles services (last registered wins), or replace the registered services, we already do such things in some places.

So maybe normal that it fails if Roles is disabled, maybe Roles (maybe also Users) should be IsAlwaysEnabled in the sense that they can't be disabled when they have been enabled.

**Comment by MikeAlhayek** [comment]
@jtkech yes that is why I suggested we have an empty service just to that the store is registered. This would work if the Roles module is disabled as it'll be a fall back. However, I think if we don't use the `Roles` module then the site/permission will no longer be usable. When the admin logs in for the very first time, since roles services won't be available there would be no way to tell what permission/claims should the admin get. so we log him/her in but we won't have any claims. In another word, the admin won't be able to access dashboard to even enable/disable features.

So I think in order for this to work correctly, we should either depend on `OrchardCore.Roles` using the Mainifest. Or, add an implementation into the Users module like "EmptyRoleService" that would somehow actually provide permission for the logged in user.

**Comment by ns8482e** [comment]
From functionality perspective, roles are not required for authentication, meaning all users have equal permission in absence of role, in other words all users are with Administrator role

In absence of Roles module, Ideally user module should provide blank default blank implementation of `IUserRoleStore` that always return hard coded stereotype role for Administrator ( No storage required or RoleDocument required )

When role module is enabled, it will replace the default blank IUserRoleStore implementation with actual implementation that supports storage with RoleDocument

**Comment by ns8482e** [comment]
Also once enabled, Roles module can not be disabled so we should mark it as always enabled in manifest

**Comment by MikeAlhayek** [comment]
Not sure if treating all authenticated users are admin by default is a good idea. This would defiantly work but what if the user setup a site without enabling the roles module "they did not know any better"? Then Everyone user becomes an admin.

**Comment by MikeAlhayek** [comment]
I have to look more, but I think there is a way to tell of a user is a super admin "maybe in the settings" and if that is the case we load admin permission, otherwise maybe we load Author permissions.

**Comment by ns8482e** [comment]
> Not sure if treating all authenticated users are admin by default is a good idea.

May be, May be not - It’s all about implement. But I guess your to the concept.  When role doesn’t exits then there is only one permission - authenticated

OC user module should work exactly same way when Roles is module disabled as in ASP.NET identity when IUserRoleStore is not implemented

**Comment by MikeAlhayek** [comment]
@ns8482e Identity default to no claims I believe. The developer is responsible of providing the claims. But in order for OC to work, admin should have access to all permissions/claims by default. But I don't agree we can grant the same permissions to other users. However, we can decide to grant other user a specific "lower access" role. At that point it's a safer approach. With that, it's up to the developer to register the claims using other module than Roles "OC does not provide this function."

I'll check tomorrow to see if there is a way to determine the site admin from the settings. But we'll need to decide which role to default none-admin to... I suggest we put that in the appsettings and set it to "Authenticated". So if roles is not enabled, we take the role from the appsettings and load the claims. This may be the safest approach.

**Comment by MikeAlhayek** [comment]
@jtkech @ns8482e Please check out the updated PR. When the roles module is disabled, we check if the user is a superadmin first. If superadmin, we load administrator claims.

**Comment by MikeAlhayek** [comment]
@sebastienros we should visit this during triage
