### ISSUE TITLE
Feature suggestion: Widget and content type replication

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1241]
Feature suggestion: Widget and content type replication
`功能建议:小部件和内容类型的复制`

I use Orchard Core to do a simple customer management system, some of the widget and content types I will customize a lot of fields, sometimes very similar, are you can add copy widget or content type copy it?
`我用orchard Core做一个简单的客户管理系统时，一些小部件和内容类型我会自定义很多字段，有时候很相似，是否可以添加复制小部件或内容类型的复制呢？`

**Comment by sebastienros** [comment]
Good idea.

**Comment by agriffard** [comment]
Content cloning is implemented.

**Comment by jptissot** [comment]
@agriffard I think this is about cloning a widget and not the whole ContentItem.
