### ISSUE TITLE
A field with the name: XX is already registered for GraphType: YY

### ISSUE THREAD

**Issue by tropcicstefan** [OrchardCMS/OrchardCore#12423]
### Describe the bug
In [#8669](https://github.com/OrchardCMS/OrchardCore/pull/8669/files#top) @deanmarcussen did some builder changes so parts that aren't collapsed don't have double field registration. The thing is, there is no check when part is collapsed. So when other builder than `DynamicContentTypeBuilder` already builds some of the fields there is an error of double field registration.

### Expected behavior
Use already added field by changing   [if (fieldType != null)](https://github.com/OrchardCMS/OrchardCore/blob/4386194e0e6652a8eb87ee5ab0b20515acffb7d7/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/DynamicContentTypeBuilder.cs#L59) to if (fieldType != null && !contentItemType.HasField(fieldType .Name)

**Comment by tropcicstefan** [comment]
New graphql brings new behaviour

**Comment by lampersky** [comment]
@tropcicstefan could you have a look if [this](https://github.com/OrchardCMS/OrchardCore/pull/13927) fix will solve your issue?

**Comment by Piedone** [comment]
@tropcicstefan could you please confirm if https://github.com/OrchardCMS/OrchardCore/pull/13927 fixed this issue?

**Comment by tropcicstefan** [comment]
@Piedone it did fix my issue in the sense there is no exception thrown.
But it's weird that we now have double field in graphqltype for same property

made content type "test" with content part "ante" with textfield "MyProperty". Result is this image

![image](https://github.com/OrchardCMS/OrchardCore/assets/30324480/370941d8-d2f5-4c30-b9d2-8fdbbd11393c)

**Comment by Piedone** [comment]
@lampersky could you comment on this, please?

**Comment by Piedone** [comment]
Thank you! @tropcicstefan could you please check the same with a fresh install, just to rule out any previously existing config issues?

**Comment by Piedone** [comment]
If this was still a bug with `main`, then https://github.com/OrchardCMS/OrchardCore/pull/16151 fixes it.
