### ISSUE TITLE
Automatically copy NLog.config from module

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#1242]
The NLog module should copy NLog.config from all modules that reference it to the web project just like content files.  So that in the web project, they can easily be included with something like below in the main `NLog.config`.

```
<include file="NLog/*.config" />
```

**Comment by sebastienros** [comment]
Can you explain why a module would change the logging configuration?

Also I think there is a way to change the main web project to add more specific files, like we do for `.liquid`.

**Comment by jtkech** [comment]
Currently, if you have a `Nlog.config` file in a module, it is copied under `Packages` as other assets. Then maybe we could harvest and use them.

if we really need these files to be copied just under the app in `NLog/*.config`, we could do it easily e.g through the `OrchardCore.Application.Targets.targets` msbuild script file.

**Comment by awyl** [comment]
Yes, the config files need to be moved to a single folder, because currently NLog does not support directories wildcard.

My use case:  I need to log the search that users enter, I figure that using the existing log module would save me time.  And then I need to configure where the log goes.

**Comment by jtkech** [comment]
Okay.

Because i'm working on a new way to embedd module assets files, maybe better to first see if we will use or not this version. Then it will be easy, i think through the cms app targets, to copy these files (coming from module projects and packages) to the `NLog` shared directory.

**Comment by awyl** [comment]
Yes.  Nice work there, thank you!!!  And thanks for considering it.

I have never worked with msbuild before.  I have tried to look at your work and the doc and google.  I couldn't get it to work and I can't bare the long build time.  So I decide to leave it to the pro!! 

:)

**Comment by awyl** [comment]
@jtkech 

With the new embedded assets, how do I reference the Nlog file?  It used to be at `Packages/{module}/NLog.config`.

**Comment by jtkech** [comment]
Try `.Modules/{module}/NLog.config`.

**Comment by sebastienros** [comment]
Closing the issue because there is a workaround, and also because you can customize any log from the main application's startup code.
