### ISSUE TITLE
Lucene query parsing error when using terms filter

### ISSUE THREAD

**Issue by scottiemc7** [OrchardCMS/OrchardCore#12439]
### Describe the bug
I have a ContentType named `Listing`, which has a text field called `Type`.  `Type` can be "League", "Club", or "Event". I am trying to create a Lucene query and running into an issue filtering by `Type`.

Query:
````
{
  "query": {
    "bool" : {
        "must": {
            "match_all": {}
          },
        "filter": [
            { "terms" : { "Listing.Type" : {{ e }} } }
          ]
    }
  },
  "sort": [
    { "Content.ContentItem.ModifiedUtc": { "order": "desc" } },
    { "Content.ContentItem.CreatedUtc": { "order": "desc" } }
  ]
}
````

Input:
````
{ e: ["Event", "Club"] }
````

For some reason running the query produces a parsing error:
`Invalid query : Unexpected character encountered while parsing value: C. Path 'query.bool.filter[0].terms['Listing.Type']', line 8, position 43.`

How would you pass an array of options to a query like this?

Related discussion:
https://github.com/OrchardCMS/OrchardCore/discussions/11943#discussion-4190829

### Screenshots
<img width="1163" alt="Screen Shot 2022-09-16 at 5 16 19 PM" src="https://user-images.githubusercontent.com/1521455/190832631-172c85da-05f0-44bc-99b9-9b93d7680e05.png">

**Comment by sebastienros** [comment]
`C` is the first letter of `Club`, the issue is that the rendered query is

```json
{ "terms" : { "Listing.Type" : Club } }
```

Which is invalid json. Try to use `{{ e | json }}` instead such that the value is formatter for json output.

**Comment by Skrypt** [comment]
{{ e | raw | json }}
