### ISSUE TITLE
BUG - Admin security -> settings -> User login bug when trying to save checkbox

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#12445]
I click Use site theme for login page.
I press the save button but it will not save.

**Comment by jtkech** [comment]
Just tried it works, it requires an active site theme, do you have one?

**Comment by JoshTango** [comment]
I was playing with themes also.  Maybe a validation error then?

**Comment by hishamco** [comment]
Please steps to reproduce

**Comment by Piedone** [comment]
Closing due to no reply from the author.
