### ISSUE TITLE
Orchard Core field type can convert?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1244]
Orchard Core field type can convert?
For example: Link Field into Text Field?
Is there any way? I saw YESSQL database file, the content is stored in a table in a field.
Looks a bit messy。
```
Orchard Core 字段的类型是否可以进行转换？
例如：Link Field  转成 Text Field？
有什么方法吗？我看到YESSQL数据库文件，内容被保存在一个表一个字段中。
看起来有点乱？
```

**Comment by sebastienros** [comment]
It's not supported, it might work if the types are compatible, but they shouldn't be. Field type should represent physical value and hence not be compatible.
