### ISSUE TITLE
SqlParser can't parse SQL queries with CTEs in them 

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#12446]
### Describe the bug
There is a line in SqlQuerySource that tries to parse a SQL query:

`SqlParser.TryParse(tokenizedQuery, dialect, _session.Store.Configuration.TablePrefix, parameters, out var rawQuery, out var messages)`

If you try to use a query with a CTE (common table expression), the parse fails with the following error:

Syntax error, expected: SELECT at line:0, col:0

I'm not sure if this is a bug or by design, given Orchard supports storage in different database providers and I'm not sure they all support CTEs. If so, perhaps this could be moved to a feature request for those of us who want to use CTEs and are ok with a requirement that our sites must run on a database that supports them.

### Expected behavior
Ideally, we could use CTEs in SQL queries. Note: I'm not suggesting necessarily that the Orchard UI should support that, but if we use a database connection directly, it would be nice if we could use CTEs (and get the benefits of the SqlParser.TryParse method).

**Comment by hishamco** [comment]
Please supply a simple query to test, if it's fail this will conclude that such expression is not supported yet (if the syntax is correct)

**Comment by lampersky** [comment]
@fuzl-llc it is Orchard Core parser and grammar limitation, CTE is not supported yet

**Comment by fuzl-llc** [comment]
Thanks @lampersky. Is there a way this can be converted to a feature request? Or, should I close this and create one separately?

**Comment by hishamco** [comment]
> Is there a way this can be converted to a feature request? Or, should I close this and create one separately?

You can create a PR and wait for the team to review it or you can subclass the SqlParser to make this happen in your project

**Comment by ns8482e** [comment]
@fuzl-llc I guess you can execute sql queries directly to db without needing to use OC's parser

**Comment by fuzl-llc** [comment]
Thanks @ns8482e! Yes, that is exactly what I'm doing for now. I like to do things the standard Orchard way as much as possible but it does seem to work just fine to execute my CTE directly using the connection object.

**Comment by sebastienros** [comment]
Looks like all dbs we support support this syntax. Maybe worth adding to the grammar then. Shouldn't be hard to do, unless we really can only return one statement. For instance the same concern could apply to having two SELECT statements in a query.

**Comment by sebastienros** [comment]
I checked the grammar and we already return a statement list but these are unions only for now.

**Comment by aminmohammadi05** [comment]
Hi, would you please do a favor to me? I want to run this query on Orchard that return 3 random products:
`SELECT TOP (3) * FROM ContentItemIndex WHERE (ContentType = 'Product') AND (Published = 1) ORDER BY newid()`
The query works on SQL server very good but in Orchard gives this error:
`Syntax error, expected: OVER, AS, id_simple, ,, HAVING, ORDER, LIMIT, OFFSET, ), UNION, ;, SELECT, FROM, WHERE, GROUP at line:0, col:15`
![Lcmow](https://user-images.githubusercontent.com/20872120/198878394-01426a63-ee4a-469f-a663-1a6253f3c210.png)
