### ISSUE TITLE
VS Project link items are not copied into the package directory

### ISSUE THREAD

**Issue by bsamba** [OrchardCMS/OrchardCore#1245]
To repro:
1. Include a linked .cshtml file in the View (or subfolder under view). This is also true for other content files as well.
2. Build solution and observe the Package directory does not have the files

I have also experimented with Shared projects as well and the results are the same

**Comment by sebastienros** [comment]
@jtkech do you understand? When you add an item you can "reference" an existing file.

**Comment by jtkech** [comment]
@sebastienros @bsamba humm, yes, be able to also reference assets which are included as linked items under VS. Maybe not so simple, need to see how we can grab them through msbuild. I will try it under my branch and will let you know.

**Comment by jtkech** [comment]
I did some tests., and i got this relative path `\OrchardCore.Body\..\OrchardCore.Demo\Views\Foo.cshtml` and this embedded resource name `...OrchardCore.Demo.Views.Foo.cshtml`.

- So, while in debug mode, to serve this content from its project location, in the mapping files we would need to implement full paths in place of relative paths (as we did at some point).

- To serve it as an embedded file in the module assembly (as in my branch), through msbuild i could easily embedd this linked file and force the resource name to be just `Views.Foo.cshtml`, this by using the `Link` property. So, here that's good.

- The most difficult will be to precompile this view on publishing. The main msbuild script would need to retrieve the linked items of the referenced projects. I think, as we did before, we would need again to call a msbuild task on each referenced module.

So, i think it's doable but it might add some complexity. If we really want this, before starting on it, maybe better to first see if we will use or not the embedded version of assets files.

**Comment by jtkech** [comment]
Normally, this is now implemented.

Now assets files are embedded in module assemblies. To include an existing asset from another project, under VS add it as a linked item and specify embedded resource for the build action.

**Comment by bsamba** [comment]
I have tried this, but it doesn't seem to work.
1. Embedded the files as such..
<EmbeddedResource Include="..\<ModuleName>\Views\Shared\**\*.*">
      <Link>Views\Shared\%(RecursiveDir)%(FileName)</Link>
 </EmbeddedResource>
2. I the files in the "module.assets.map"
3. However, when I load up the app, the views cannot be found.

I'm building with OrchardCore build 1.0.0-beta2-3915
Please let me know if there's something I'm doing wrong

**Comment by jtkech** [comment]
I tried it by only adding linked items one by one, marked them as embedded and then just let VS update the .csproj file (see below). But first i didn't try it in a more global way as you.

    <ItemGroup>
      <EmbeddedResource Include="..\OrchardCore.Demo\Views\Foo.cshtml" Link="Views\Foo.cshtml" />
    </ItemGroup>

Then just tried, it seems to work by using the following because you are missing the file extensions.

    <Link>Views\Shared\%(RecursiveDir)%(FileName)%(Extension)</Link>

**Comment by bsamba** [comment]
Apologies, it works with the extension, thanks!
