### ISSUE TITLE
Search box buttons and input size consistency

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#12457]
![image](https://user-images.githubusercontent.com/3228637/191274025-7d542b69-2bbf-4d52-b765-f3e5a77baf2d.png)

As you can see here in a ListPart the buttons are smaller than the input.
The search box has been recently restyled and its size has changed. It should use form-control-sm to make it as small as these buttons.

@MikeAlhayek

**Comment by MikeAlhayek** [comment]
@Skrypt i'll have a PR for this soon
