### ISSUE TITLE
Device dependent template processing

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1246]
The responsive design does not always work for mobile - especially regarding the large size of the dependency we are pulling into the device.

Orchard needs to address this. Having different template to be processed based on device detection can help a lot.

**Comment by pgy866** [comment]
What a wonderful, but non-stop accumulation? Will affect the RC version of the release? I saw that RC was changed to Scheduled March 2018。
`多么美好，但是这样不停的累积？是否会影响RC版本的发布？我看到RC 被修改为 2018年3月啦。`

The picture below is also a view of my favorite CMS. If you can implement PR in Orchard Core, that's great.
`下图也是我喜爱的一个CMS的视图。如果能够在Orchard Core中实施公关，那非常棒。`
![image](https://user-images.githubusercontent.com/28694676/33124389-b6a8c786-cfb7-11e7-89fb-c2fd46017a3c.png)

**Comment by sebastienros** [comment]
You can already do that by implementing https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.DisplayManagement/Theming/IThemeSelector.cs 

Right now this means you would have your own logic in this class, but we could also imagine a module alongside the theme selection to define the logic to select the theme name. To prevent CPU usage we can then store the theme in a cookie for subsequent requests.

**Comment by giannik** [comment]
an old post , but relative :
https://weblogs.asp.net/bleroy/dynamically-switching-the-theme-in-orchard

**Comment by awyl** [comment]
I have extracted some logic from this.
https://github.com/laskoviymishka/MvcDeviceDetector

For controller views, it looks for `.m` and `.t` views (configurable).

Then I add a `IShapeTableProvider` to add those alternative for shape views for specific shapes I am interested in.  One problem I have is I don't know how to `Describe` all shapes.
