### ISSUE TITLE
 BUG - recaptcha ERROR for site owner: Invalid key type

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#12471]
I registered for a v3 recpatch on google.
on the register page I get:
ERROR for site owner: Invalid key type

Is there guidance on what type of key to use?

**Comment by MikeAlhayek** [comment]
https://docs.orchardcore.net/en/latest/docs/reference/modules/ReCaptcha/

**Comment by JoshTango** [comment]
Yes I went through that.
It doesnt specify v2 or v3 or enterprise.

**Comment by JoshTango** [comment]
mAYBE THE MODULE IS NOT COMPATIBLE WITH V3 RECAPTCHA BY GOOGLE WHICH IS THE NEW VERSION?

**Comment by hishamco** [comment]
If I remember it compatible with v2

**Comment by hishamco** [comment]
Related to #5531

**Comment by sebastienros** [comment]
Duplicate

**Comment by JoshTango** [comment]
yes i switched to v2 and it works.  Maybe upgrade the module?

**Comment by Skrypt** [comment]
These are 2 different Recaptcha and should be kept separated. So, I would say we would need to simply add the ability to specify which version to use from the Recaptcha module.

**Comment by JoshTango** [comment]
yes i aggree.
Also there is enterprise version now.
