### ISSUE TITLE
Unit Test reporting "Fail" in CI

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#12479]
![image](https://user-images.githubusercontent.com/3228637/191848857-66550697-1cf1-41b9-8922-8f4f31554218.png)

The current CI reports issues when running Unit Tests. See the latest Workflow actions to troubleshoot.
I'm not sure why as of now but the Unit Tests are not set to a failing state afterward either.

**Comment by MikeAlhayek** [comment]
I don’t know if this fail is also related to this https://github.com/OrchardCMS/OrchardCore/actions/runs/3086217358/jobs/4990345159

**Comment by Skrypt** [comment]
No, it is a different one. Those are functional tests, not unit tests.
