### ISSUE TITLE
Common shared view cshtm

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#1248]
Hi,

I need to have a common error page in the theme that I want to call from all my specific modules. But the search path /Packages/{Theme}/Views/Shared/{page}.cshtm seems to be missing. Is this a bug or the wanted behaviour?

InvalidOperationException: The view 'Error' was not found. The following locations were searched:
/Packages/Flexmind.Theme/Views/Flexmind.CarRepair.Module/ServiceOrderHeader/Error.cshtml
/Packages/Flexmind.Theme/Views/Flexmind.CarRepair.Module/Shared/Error.cshtml
/Packages/Flexmind.CarRepair.Module/Views/ServiceOrderHeader/Error.cshtml
/Packages/Flexmind.CarRepair.Module/Views/Shared/Error.cshtml
/Areas/Flexmind.CarRepair.Module/Views/ServiceOrderHeader/Error.en-US.cshtml
/Areas/Flexmind.CarRepair.Module/Views/ServiceOrderHeader/Error.en.cshtml
/Areas/Flexmind.CarRepair.Module/Views/ServiceOrderHeader/Error.cshtml
/Areas/Flexmind.CarRepair.Module/Views/Shared/Error.en-US.cshtml
/Areas/Flexmind.CarRepair.Module/Views/Shared/Error.en.cshtml
/Areas/Flexmind.CarRepair.Module/Views/Shared/Error.cshtml
/Views/Shared/Error.en-US.cshtml
/Views/Shared/Error.en.cshtml
/Views/Shared/Error.cshtml

Regards,
Jérôme Piquot
Flexmind

**Comment by sebastienros** [comment]
I assume we could add this common views as a fallback if no module matches. We currently use the module as the prefix to let a theme override a specific view from a module without having conflicts.

@jtkech Easy right?

**Comment by jpiquot** [comment]
Hi Sébastien,

Thank you for your answer.

Regards,
Jérôme

**Comment by jtkech** [comment]
@sebastienros @jpiquot yes, it would be easy. Currently in the code we have

    var themeViewsPath = '/' + theme.Extension.SubPath + "/Views/" + context.AreaName;
    result.Add(themeViewsPath + "/{1}/{0}" + RazorViewEngine.ViewExtension);
    result.Add(themeViewsPath + "/Shared/{0}" + RazorViewEngine.ViewExtension);

So, there is always the module name in the path. Maybe we would need to have something like this.

    var themeViewsPath = '/' + theme.Extension.SubPath + "/Views";
    var themeViewsAreaPath = themeViewsPath + '/' + context.AreaName;
     result.Add(themeViewsAreaPath + "/{1}/{0}" + RazorViewEngine.ViewExtension);
     result.Add(themeViewsAreaPath + "/Shared/{0}" + RazorViewEngine.ViewExtension);
     result.Add(themeViewsPath + "/Shared/{0}" + RazorViewEngine.ViewExtension);

**Comment by jpiquot** [comment]
Hi Jean-Thierry,
I have checked on your branch and it works well. 
Thanks for this very quick fix.
Regards,
Jérôme Piquot
Flexmind

**Comment by jtkech** [comment]
Thanks for trying it.
