### ISSUE TITLE
When using ContentTypes without any fields, the "Fields" section should not show up

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12488]
### Describe the bug
When we enable `OC.ContentTypes` feature but not enable any feature that compose fields like `OC.ContentFields`, the Fields section shows up.

![image](https://user-images.githubusercontent.com/24724371/192036008-99ac0472-4dd2-4bb6-97e1-58480ec74f8f.png)

### To Reproduce
1. Enable OC.ContentTypes and disable OC.ContentFields.
2. Go to Content Types and edit or add a new content type

### Suggestion
I think we should remove the "Add field" button when there is no fields definitions. Also, if a currently attached field has no definition, we should not be able to edit it, but we should be able to remove it. This can happen if a field was attach to a content type/part while the field definition is available but then the feature that provides the definition was disabled. 

Moreover, we should remove the "Fields" section from the UI if the current content-type has no fields and also there is no field definitions.

**Comment by ns8482e** [comment]
@MikeAlhayek is the ContentField feature is the only way to create fields in content item?

If ContentField is disabled you may not able add/alter definition from UI but you still should be able to see content item definition containing  fields

**Comment by MikeAlhayek** [comment]
@ns8482e no, fields can be added by multiple features as they should. This is why the PR looks for field definitions, and if there is no definitions, we don't show the button since there would be no fields to add which will cause and error on submit.

**Comment by hishamco** [comment]
What if the user planned to add a field later? How we can show that button again?!!

**Comment by MikeAlhayek** [comment]
@hishamco it won't matter. when a feature is enabled that compose fields, the field definition would have records and we show the button again. 

Check out PR #12492 and fix is pretty simple.
