### ISSUE TITLE
Remove the min-height on multiple select in TheAdmin theme

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12490]
### Is your feature request related to a problem? Please describe.
Currently, we override BS 5 and set a min-height of 300px on multiple select. It takes lots of room on the screen and should be left as BS 5 renders it.

### Describe the solution you'd like
The css code

```
select[multiple] {
    min-height: 300px;
}
```
should be removed from `_forms.scss` file in TheAdmin theme so the default BS 5 size takes presence. 

Here is how it looks like today

![image](https://user-images.githubusercontent.com/24724371/192052467-86a1b5f9-8c4d-462f-9ac9-fb03aab71c6f.png)

This is how I think it should look like by default

![image](https://user-images.githubusercontent.com/24724371/192052582-9def55a8-96d6-42d1-be2c-33c4ace04c12.png)

If someone want it larger, they can override the default instead of us providing a custom default

**Comment by hishamco** [comment]
While it's multi picker it should be bigger to allow the user to select more items easily, may be your items are few and that's why you see the list is too big ;)

**Comment by MikeAlhayek** [comment]
@hishamco I suggest we leave the design to the defaults of BS since that is the framework we use. If they thought it would have been such a good idea to have a min height, I am sure they would have added a min height. I think we should stick with very minimal overrides for BS framework.

**Comment by hishamco** [comment]
Agree to leave the design to the BS defaults
