### ISSUE TITLE
Add tags and descriptions for nuget packages

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1249]
Our packages in Nuget are not currently tagged, with things like `orchardcore`

Also we need to get the descriptions from the module.txt files in to the nuget packages.

**Comment by agriffard** [comment]
We now use a Manifest.cs to describe a Module but I guess the issue is still to be done.

**Comment by ns8482e** [comment]
Related #6404

**Comment by hishamco** [comment]
Can we close this while it's a duplicate of #6404?
