### ISSUE TITLE
Workflow task for adding tenant

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#12515]
I remeber in the SASS video done a few years ago that they said you could do all this in workflow.
I don't see an add tenant task in the workflow currently.
Maybe make one?

**Comment by MikeAlhayek** [comment]
If you are on the default tenant, you should be able to add workflow tasks for creating tenant. I never used this, but from the code I can tell there is a task called "Create Tenant Task".

you can see the code [here](https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore.Modules/OrchardCore.Tenants/Workflows/Activities)

**Comment by JoshTango** [comment]
Yes I just verified that.  I had actually put my website into its own separate tenant and was hoping to call it from there.

**Comment by MikeAlhayek** [comment]
Currently the only way to manage tenants in OC is by using the Default tenant and so it’s the only way to manage tenants. If this is not an issue, please close it.

Can someone move this issue to a discussion?
