### ISSUE TITLE
Missing disable user registration setting

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#1252]
Like in O1.

**Comment by pgy866** [comment]
![default](https://user-images.githubusercontent.com/28694676/33319465-cb499744-d479-11e7-9fde-d9517ee966a8.PNG)

**https://github.com/OrchardCMS/OrchardCore/issues/1235**
If you create the Orchard Membership Module,
For site registration and some other site Membership management settings such as the development needs,
Will it be better?
```
如果创建Orchard Membership Module，
为站点注册等提供一些站点Membership 的一些管理设置等开发需要，
会不会更好呢？
```

**Comment by awyl** [comment]
現在已經能夠注冊, 但是我要關掉這個功能.

**Comment by awyl** [comment]
Yea, I file them first and see if I have the time to do PR.

**Comment by agriffard** [comment]
A few remarks after I did some tests:
- The Users sub menu under settings should have a position, at least to be lower than the General one.
- It could be interesting to have a way to specify a role you can set for new users.
- If I enable the checkbox, when I register a new user, my currently logged user is disconnected.

The RegistrationSettings.Edit.cshtml Edit form should use the Bootstrap css classes, like this :
```
<div class="form-check">
        <label class="form-check-label" asp-for="UsersCanRegister">
            <input asp-for="UsersCanRegister" type="checkbox" class="form-check-input" />
            @T["Users can create new accounts on the site"]
        </label>
    </div>
```
May be with an additional label to explain that a Register form will be added.

Question : 
If I extend a User with fields, will the register form have these fields added?
Can it be customized in the Theme? What would be the name of the alternate?

When the email module will be available, I guess all the challenge email process will be integrated.

**Comment by sebastienros** [comment]
Is users can be extended, and the form needs to be rendered in the front end, then we should have two sets of drivers, for the admin and for the front end. So we can customize the rendering independently. I don't remember how they are extensible.

Ok to have a default role for registered users. Unless we only want to use Workflows.

**Comment by agriffard** [comment]
The only feature that exists for the moment is, when 'User Registration' is enabled, is to 'Do not allow user with unconfirmed Email to be able to connect'.
In O1, there is no other way to 'disable' a user, we can only delete it or remove some roles.

**Comment by Skrypt** [comment]
Allow to disable a user account by adding IsDisabled param on User class and make changes where it's needed like on the Login controller to prevent login when a user is disabled.
