### ISSUE TITLE
Missing image graphics on home page

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#12522]
Hi Team,

### Describe the bug
We are running multi tenant CMS on orchard core. All of sudden images used in homepage on different tenants disappeared when our server goes offline and then comes back online. It happen to tenants with multiple domain listed in hostname separated by comma. However, after restarting the tenant it come back. So could you please advise what would be case.

Regards

**Comment by hishamco** [comment]
I didn't understand the issue presicely!! if the server goes down I presume all the tenants and resources will not be available

**Comment by hishamco** [comment]
I see, may be a caching issue, could you copy URL for one and open it in a private window in Edge or incongito mode in Chrome

**Comment by lampersky** [comment]
@khurram4u2 do you observe any errors in your log stream?

your problem reminds me about [this](https://github.com/OrchardCMS/OrchardCore/issues/9319) issue

**Comment by Skrypt** [comment]
We need to have repro steps and/or logs.
