### ISSUE TITLE
Remove hard coded HTML ids from UserFields.Edit.cshtml view

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12531]
### Is your feature request related to a problem? Please describe.
I am trying to create a feature that would allow an Admin to bulk import users from excel file. After the user uploaded the excel file, I want to build the Edit fields for every user in my file. This means calling the `UserFields.Edit.cshtml` multiple times in the same output. The only problem that I am facing is that the password generator fails because the same html id are used on the same page which is not good. Here are the hard coded ids `generatePassword`, `passwordConfirmationToggle`, `passwordToggle` and `copyPassword`.

### Describe the solution you'd like
We should never hard code fixed ID in views that are used by driver. Instead, we should dynamically generate ID or class name to allow the user to reuse the views if needed like in my case.

### Workaround
I override the view in my own theme, but since this view is driver driven, I think it should be robust.

**Comment by hishamco** [comment]
> The only problem that I am facing is that the password generator fails because the same html id are used on the same page which is not good. 

Could you please point where the password generaor id used more than once?

**Comment by MikeAlhayek** [comment]
As mentioned I am working a module that allows my admin to import multiple users, and when I call the build editor on the User display manager, the listed ids appear more than once.

**Comment by hishamco** [comment]
This is happen according to your scenario, but I didn't see any issue in the current view
