### ISSUE TITLE
Hiding the content picker field select control

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#12541]
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/12540

<div type='discussions-op-text'>

<sup>Originally posted by **fuzl-llc** October  2, 2022</sup>
If you are using the content picker field, and set "multiple" to false, there doesn't seem to be any need to show the search/select list control once you've selected a content item. Of course if you delete the content item, you need to show it again but while a content item is selected, the search/select list control is currently shown disabled under the selected content item. I feel like it is a weird UI where the space taken up by this field doubles and halves when you select/delete content which moves the following controls up and down. It also takes up twice the vertical space it needs to, adds to clutter on the admin pages, and would just be much nicer if it was hidden. The same issue exists for the user picker field (and perhaps other things).

Here is the issue:

![OrchardIssue](https://user-images.githubusercontent.com/62618663/193428294-e4c766d1-52f1-428c-ab46-e90602fe22ae.gif)

And here is how it looks fixed:

![OrchardFix](https://user-images.githubusercontent.com/62618663/193428291-84692720-f19b-4c48-81e7-17775c22d187.gif)

I wasn't sure where to put this as it isn't really a bug and seems too small to be considered a "feature request." I became obsessed with this last night and somehow managed to get some working code that does what I want, though I suspect it is not the best code/approach and currently only works if I edit the generated .js file for vue-multiselect-wrapper.js. I'm still pretty new to Orchard, am not great w/Javascript and jQuery, and have never used vue or gulp... but thought perhaps one of the gurus could take what I've done and clean it up to do it right. I'm happy to help if I can if there is interest in making this change.</div>

**Comment by hishamco** [comment]
@fuzl-llc could you please submit a PR with your proposal changes, then we can review

**Comment by fuzl-llc** [comment]
Sure. I've never done one before but I think I saw a document somewhere describing how...

**Comment by hishamco** [comment]
1. Fork the OC repo
2. Clone your forked repo
3. Apply your changes
4. Add your commits using a Git client
5. Push your commit
6. Create a pull request from the working branch (from within your repo)

**Comment by fuzl-llc** [comment]
Thanks for that. I'm working on it...

**Comment by fuzl-llc** [comment]
Please see PR #12543.

**Comment by MikeAlhayek** [comment]
So much better! Thank you
