### ISSUE TITLE
Fix sample TaskActivity code in documentation

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#12542]
This link has sample code for an activity.  It doesn't compile.  It might need to be updated:

https://docs.orchardcore.net/en/dev/docs/reference/modules/Workflows/#developing-custom-activities

**Comment by JoshTango** [comment]
I  think its mostly just the class  WorkflowContext has changed to WorkflowExecutionContext

**Comment by hishamco** [comment]
Could you please submit a PR?
