### ISSUE TITLE
Password generator is creating passwords that are not compatible with PasswordOptions

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12569]
### Describe the bug
Currently, when creating a new user, the password generator is does not create a password with digit due to a [typo here](https://github.com/OrchardCMS/OrchardCore/blob/de7d3898cd30d51f2aad3b891f6f8d8b1e10f0f3/src/OrchardCore.Modules/OrchardCore.Users/Views/UserFields.Edit.cshtml#L100)

The line should be changed `const requireDigit = generate.getAttribute('data-password-requireDigit') === 'true';` instead of `const requireDigit = generate.getAttribute('data-password-requireDigit') === 'True';`

**Comment by hishamco** [comment]
If there's a typo, please fix it in a separated PR, because the linked PR fixing another issue

**Comment by MikeAlhayek** [comment]
@hishamco done
