### ISSUE TITLE
Allow non default tenants to enable tenant module feature.

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#12564]
Ok so I made a custom task to add a tenant because I found out you could only enable the tenants feature in the default tenant only.
My task shows up in the default tenant workflow just fine.
But I don't want to use it in the default.  Instead, I want to use this task in regular tenants.
However when I go to the workflow page I get an error as follows:

InvalidOperationException: Unable to resolve service for type 'OrchardCore.Setup.Services.ISetupService

Now I read that the only way to get the setup service resolved is to enable the tenant feature which I can't do because I want to use this task in a non-default tenant.

Is there a plan of action for this issue? @sebastienros

**Comment by MikeAlhayek** [comment]
I would question the fact you want to allow any tenant to add a new tenant into your environment. If you do, you are basically saying an admin of any tenant can their own instance using workflow.

Regardless, you don't need the tenants module to use the default `ISetupService`. You can also use `OrchardCore.Setup` feature. Lastly, you can always register it as you wish in your own enviornment by using [AddSetup()](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.Setup.Core/ServiceCollectionExtensions.cs#L14) extensions.

**Comment by sebastienros** [comment]
@JoshTango can you try to follow @MikeAlhayek 's suggestion with AddSetup?

**Comment by JoshTango** [comment]
Yes I will explore this.

**Comment by hishamco** [comment]
Can we remove the discussion label while we already have a discussion section, so we can use "Convert to Discussion" option

**Comment by Piedone** [comment]
Closing due to no update from the author.
