### ISSUE TITLE
CSS classes being added to my menu even though my alternate does not have them and I call Model.Classes.Clear()

### ISSUE THREAD

**Issue by Eaglef90** [OrchardCMS/OrchardCore#12579]
I have written my own alternates to display my menu and no matter what code I have tried using it seems the very first UL element is having extra CSS classes "menu menu-site-navigation-menu" added to it. I have been able to override all the other auto-generated code but these 3 CSS classes.

The code in my alternate is:

```C#
@{
    TagBuilder tag = Tag(Model, "ul");
    Model.Classes.Clear();

    tag.InnerHtml.AppendHtml(@"
        <li>
            <a href=""https://www.site.com/"">
                <i class=""Icon-Home""></i>
            </a>
        </li>"
    );

    var menuItemCount = (int)Model.Items.Count;
    var currentMenuItemNumber = 1;

    foreach (var menuItem in Model.Items)
    { 
        tag.InnerHtml.AppendHtml(await DisplayAsync(menuItem));

        if (currentMenuItemNumber < 11) { tag.InnerHtml.AppendHtml("<li class=\"VerticalDivider\"></li>"); }

        currentMenuItemNumber++;
    }
}

@tag
```

And the HTML it generates is:

```html
<ul class="menu menu-site-navigation-menu">
        <li>
            <a href="https://www.site.com/">
                <i class="Icon-Home"></i>
            </a>
        </li>
<li>

<a href="javascript:;">Site<b class="Caret"></b></a></li><li class="VerticalDivider"></li>
<li>
```

It seems like this is a bug that these tags are still being generated, maybe hard coded into the CMS somewhere?

**Comment by Skrypt** [comment]
Refer to NavigationShapes class where the Shapes of these menus are defined.

**Comment by Eaglef90** [comment]
> Refer to NavigationShapes class where the Shapes of these menus are defined.

I am confused. Am I supposed to use Navigation Themes to display the menu shape or shape alternatives? When I last asked about menus I was told menu alternates. Or do I have to do both?

**Comment by Skrypt** [comment]
I'm not sure what you are trying to do here. I have no context. Please explain.

**Comment by sebastienros** [comment]
Can you try calling `Model.Classes.Clear();` before the tag is created?

**Comment by Eaglef90** [comment]
> Can you try calling `Model.Classes.Clear();` before the tag is created?

Due to the lack of documentation and having to be a super expert in programming I have dumped Orchard Core and moved on to more mature options so I can't try this.

Go ahead and close this (and my other posts) if you want to. Best of luck in making Orchard Core into something.

**Comment by ns8482e** [comment]
Interesting, @Eaglef90 if you are in cshtml why do you write c# code to generate html?

You could have write `<ul>` directly with `class` you need without using `Tag` and AppendHtml

**Comment by jtkech** [comment]
Just for testing ;)

With `Model.Classes.Clear();` before `TagBuilder tag = Tag(Model, "ul");`
