### ISSUE TITLE
Access of Feature Enable / Disable button.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#1257]
Working on my branch after having merged the last `dev`, feature Enable / Disable buttons can't be accessed on their full zone, only at the bottom. I think it's a styles issue.

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1243

The last DEV branch, after updating "Update Bootstrap 4 to Beta (# 986)", came up with this issue.
`最后一个DEV分支，更新“Update Bootstrap 4 to Beta (#986) ” 之后，出现的这个问题。`

**Comment by jtkech** [comment]
@pgy866 thanks for locating it, so @agriffard will be able to fix it more simply.

**Comment by agriffard** [comment]
Fixed in https://github.com/OrchardCMS/OrchardCore/commit/7465d58209699ae7d37072f053a8b7a2d26dcf7d
