### ISSUE TITLE
Template not showing in RTL direction

### ISSUE THREAD

**Issue by sayyad84** [OrchardCMS/OrchardCore#12580]
There is a bug in the templates section, which direction must be set to LTR. Please fix this in future versions. in OrchardCore.Templates->Views->Templates, Create and Edit views:
before:
![image](https://user-images.githubusercontent.com/57654948/194385486-4a5507d5-f98f-4916-a3df-16475437b01b.png)
after:
![image](https://user-images.githubusercontent.com/57654948/194385537-272f3916-e3c5-4bee-a1a5-65bc44c767bb.png)

**Comment by hishamco** [comment]
Does localization module enabled? Is a RTL culture the default one?

**Comment by sayyad84** [comment]
Yes, Localization is enabled and a RTL culture is default.

**Comment by hishamco** [comment]
I need to reproduce the issue

**Comment by sayyad84** [comment]
Activate a right-to-left culture as default and create a new Template in the Design->Templates section.

**Comment by hishamco** [comment]
That's what I supposed to do ;)

**Comment by Skrypt** [comment]
It is not something that needs to be fixed in OC.
See https://github.com/Microsoft/vscode/issues/11770

**Comment by sayyad84** [comment]
> It is not something that needs to be fixed in OC. It is the Monaco Editor.

Hi,
If the default culture is right to left, it is not possible to type in the template field. Do you think this is not a bug? In addition, the method of solving the problem by changing the Create.cshtml, Edit.cshtml of OrchardCore.Templates module one has been sent.

**Comment by sayyad84** [comment]
In addition, this problem must be solved in OrchardCore.Modules\OrchardCore.Queries\Views\Admin\Query.cshtml. Note that the texts typed in these fields are in English and must be left to right.

**Comment by hishamco** [comment]
@Skrypt I don't think that Monaco editor not support RTL

**Comment by Skrypt** [comment]
You can search quickly on Google "monaco editor + rtl" and you will find a Github issue about it in the VSCode repository.
https://github.com/microsoft/vscode/issues/86667
