### ISSUE TITLE
Test and potentially use larger (faster) GitHub-hosted runners for builds

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#12583]
### Is your feature request related to a problem? Please describe.
PR builds currently run for about 7-8 minutes. This is not bad, but it would also be better to have faster builds if possible.

### Describe the solution you'd like
Larger, and thus faster GitHub-hosted runners [are now available in beta](https://github.blog/2022-09-01-github-actions-introducing-the-new-larger-github-hosted-runners-beta/). There are options to use even 64-vCore VMs for builds, which offer a significant performance upgrade over the default 2-vCore ones.

Supposedly the workflows don't need to be significantly modified. After some organization-wide configuration changes, and changing the machine-type configured in each workflow, they can use the faster runners. (In practice, there can be incompatibilities, I noticed and reported two already, but the GitHub Actions team is quickly fixing them.)

I'm happy to do this (am working on the same thing for Lombiq too) but as the first step, somebody needs to enroll the OrchardCMS organization into the beta, which doesn't seem to be possible for me:

![image](https://user-images.githubusercontent.com/1976647/194615743-001a2591-88ea-442b-ab22-d56d7b5537d4.png)

Perhaps you can do this @sebastienros?

After this, there's also a gotcha: The larger runners are not free, but [paid per minute](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates). How does this work under .NET Foundation? (It's only them, as the owner of the enterprise account, who can pay for any GitHub service.)

### Describe alternatives you've considered
[BuildJet](https://buildjet.com/) offers a similar service, but it's an external one and only Ubuntu is available. It's significantly cheaper, however.

We can also try to make the builds faster, but I don't see any options there. And if we'll have more automated checks, like static code analysis, it'll just become slower (since it does more, not due to lack of optimization).

**Comment by Piedone** [comment]
@sebastienros could you please point to who at DNF might be suitable to talk to about this?

**Comment by sebastienros** [comment]
> PR builds currently run for about 7-8 minutes

Who is complaining about it? (you at least).

I am not really OK to start paying for builds that we can't control. Some users just commit every single change, it's a waste of resource/money. I'd like to study other options first to solve this (as much as this is a problem). Like changing what is built, or re-organize things if some early issues can be found quicker, delaying some functional tests, ...

Do you know how long the same script takes on your local machine to understand how much we could gain? And how much would it cost for the amount of builds we currently do to get the same result as your local machine?

**Comment by Piedone** [comment]
Have you heard of a developer who _doesn't_ complain that the build is slow? :) If it can be made faster, and DNF is happy to pay for it (I have no idea, hence the need to talk to them as a zeroth step), then why not see if it makes sense?

Well, the first step is to test, and see what the performance gain and cost would be. I'm not saying we should definitely use larger runners, if possible at all. On my machine (R), a build [like this](https://github.com/OrchardCMS/OrchardCore/actions/runs/3274775191/jobs/5388752391#step:6:1) takes not 5m but 19s. While this is kind of a lower bound (perhaps on the best PC with a RAM drive you can get down to 5s?), it doesn't matter much because the GitHub runners are completely different hardware. I don't think this is achievable with GitHub-hosted runners at all, because their bottleneck is I/O and the runners are ephemeral, but we can perhaps about halve the workflow runtime by using the next tier (i.e. 4-core for Ubuntu, 8-core for Windows). This, according to my measurements with Lombiq builds, is both realistic and the price/performance sweet spot.

We certainly don't need to run everything all the time (just as it doesn't happen now), and I'll further evaluate things under https://github.com/OrchardCMS/OrchardCore/pull/11194 (like, perhaps we only need to run functional tests, but then for all DBs, when a PR gets approved?). However, at the end of the day, the build needs to happen every time, and it takes enough time already.

BTW with [the `cancel-in-progress` config](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) you can constrain all PRs to just run a single build at a given time, i.e. if you frequently commit and push as well, then not every one of them will do a full build.

**Comment by sebastienros** [comment]
FYI, 3m13s on my machine if you clear your nuget cache and clean the repos to be in the same state as the CI machine.

**Comment by Piedone** [comment]
That's what I was referring to by the GitHub runners being ephemeral. In any case, your number is not necessarily indicative either. We can only see if we test. If that's good by DNF, then let's do some testing. If not, then this issue is not applicable, to begin with.

**Comment by Piedone** [comment]
So @sebastienros who do you think we can talk to at DNF?

**Comment by Piedone** [comment]
Ah! https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/ We actually use larger runners now! Gradually, we got larger runners fro the end of November, and roughly froom the beginning of December they all run on faster runners:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/cb362203-65c7-45a5-afac-a1663617f2c0)

So, nothing to do here for now.
