### ISSUE TITLE
List "Create" button breaks if more than one creatable content type

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#12595]
### Describe the bug

When you add the List part to a content type, you can then add child content items in a 1:many relationship. When you click the link to edit a content part with a list part, it doesn't immediately show the content editors but rather a list of all its contained items with two buttons: one to edit the part and one to add new items to the list. This last button says "Create [contained content type name]" if the list is configured to only allow a single content type to be contained in the list, and "Create" with a little downward facing icon indicating it is a drop down, to show the different creatable content type names if the list is configured to allow more than one content type to be contained in the list. The single contained content item case works fine - I can click the button add items to the list. When multiple items are containable in the list, the button is broken. Clicking it does nothing.

### Note

I observe this when I create a site from the latest 1.4.0 version nuget package but I'm not able to repro if I pull the latest Orchard source - all seems to work just fine. I searched and didn't see an existing bug but either way it seems it is fixed. Not sure if it is worth keeping this around to mark fixed in the next release if anyone else affected by this issue in the current release.

### To Reproduce
1. Create a content type with a list part.
2. Configure the list part to allow multiple content items to be contained.
3. Create a new instance of the container content type.
4. Try to click the "Create" button to add items to its list.
5. The button gets highlighted when clicked but nothing happens.

### Expected behavior
It should open to show the allowable items that can be created.

**Comment by fuzl-llc** [comment]
Might there be any workarounds to this issue for those of us using v1.4.0 nuget packages? I'm not sure when the next Orchard release is and I've never tried to develop against the latest source code... and I'm not even sure how best to do that given I've already got a bunch of projects all using the OrchardCore.Application.Cms.Core.Targets and direct references to the 1.4.0 nuget packages.

**Comment by hishamco** [comment]
If the steps above can't reproduced in the nightly build, we need to close this. May be it was a bug

**Comment by fuzl-llc** [comment]
Yes, the nightly build is fine. In fact I came up with an answer for the workaround which is to just use the preview nuget packages from the nightly build:

https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/

That isn't a good workaround if you're in prod but my project is going to be in dev for a few months so using this works for me and the problem is fixed with the current preview packages.
