### ISSUE TITLE
Don't lose an empty option name on saving Predefined List settings

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#12592]
### Describe the bug

For a `PredefinedList` Text field it is allowed to define in a Migration an empty Option name.
It works well and when you edit the related settings you can see that the empty Option name is there.
But then if you save the settings and re-edit them, you can see  that you lost the empty Option name.

### To Reproduce
1. Define in a Migration a `PredefinedList` Text field with an empty Option name.
2. Setup the site and go to the settings editor of the above field.
3. You can see that the empty Option name is there, then save the settings.
4. Re-edit the settings to see that you lost the empty Option name.

### Expected behavior
Because it is allowed to define an empty Option name in a Migration and it works well.
Just don't remove this empty Option name when saving the `PredefinedList` settings.

**Comment by hishamco** [comment]
Seems you modified the description which is fine, can we fix the other issues related to empty after your PR got merge?

**Comment by jtkech** [comment]
Yes no problem ;)
