### ISSUE TITLE
In workflow , the method of input()  can't support the Numeric field .

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#12597]
### Describe the bug
I create a content type --"ceshi". add a Numeric field type-- "zhengshu"。in workflow, i want get the value of Numeric  Field.  in workflow , i create a set property task, use javascript  "input('ContentItem').Content.ceshi.zhengshu.Value ."
workflow "faultMessage": "Type provided must be an Enum. (Parameter 'enumType')".

possible reason:
input() method  can't support the Numeric Field .
<img width="495" alt="微信图片_20221008094911" src="https://user-images.githubusercontent.com/17457950/194809243-ae56bf1a-53aa-4e0e-8858-d6c38ee536ea.png">

### Screenshots
![微信图片_20221010093945](https://user-images.githubusercontent.com/17457950/194788065-f668115e-eba8-470a-afa2-4a4935b73ba2.png)
"faultMessage": "Type provided must be an Enum. (Parameter 'enumType')".

**Comment by lampersky** [comment]
@jnucpz I've just tried to reproduce your issue with no luck:

![image](https://user-images.githubusercontent.com/6403130/194859533-e1f34de3-80e8-46da-821a-7416cc5ccb8d.png)

as you can see it works:

![image](https://user-images.githubusercontent.com/6403130/194859751-a252a390-a4bd-4227-9ef5-cfa31d267204.png)

Are you sure you don't have a typo in your **SetPropertyTask**? Could you share your workflow and ContentType + example Content Item?

**Comment by zl2fxy** [comment]
@lampersky  @sebastienros,  i download sourcecode to debug, when value is Decimal,it is wrong,  convertible.GetTypeCode() is Decimal not is double,so it use a method of jsNumber.Create(Object value)  not is jsNumber.Create(double value),it is wrong of jint
![2022-10-11](https://user-images.githubusercontent.com/19570956/194998540-2e4915da-0452-4764-a0f9-55d07be78bde.png)
![1665463698162](https://user-images.githubusercontent.com/19570956/194999642-5c33a226-21f5-4225-9141-4911ad3dadba.png)
![image](https://user-images.githubusercontent.com/19570956/195000055-5d11cdc3-9b12-4d9c-a3b9-50982af13319.png)

**Comment by lampersky** [comment]
@zl2fxy you are right, I was using integer, that's why I wasn't able to repro the issue

**Comment by jnucpz** [comment]
What time this bug can be fixed?

**Comment by sebastienros** [comment]
@jnucpz can you provide a PR that fixes the conversion in DefaultObjectConverter? That's the fastest way to get the fix in.
