### ISSUE TITLE
Home Page Url In Sitemap using permalink 

### ISSUE THREAD

**Issue by kgwadu** [OrchardCMS/OrchardCore#12596]
I'm not 100% sure this is a bug but its a big issue for us with regards to SEO. For the permalink you can't set / to indicate the home page, it needs to contain something e.g. https://www.domain.com/home-page. So in our auto-generated sitemap, the home page url is showing as https://www.domain.com/home-page instead of showing as https://www.domain.com/.

Is there some way around this? Or are we doing something wrong?

**Comment by hishamco** [comment]
There's an option to set any page to home, also you can edit the auto route slug for a particular page

**Comment by kgwadu** [comment]
> There's an option to set any page to home, also you can edit the auto route slug for a particular page

Sorry i didn't explain myself clearly, we have the home page set as the home page, the problem is, in our sitemap, we want the home page url to only contain the domain e.g. https://www.domain.com, but with the autoroute part, you cannot leave the value blank or set it to /. So we have home in the autoroute which causes the sitemap to render the home page url as https://www.domain.com/home.

**Comment by hishamco** [comment]
You can use `OrchardCore.HomeRoute` instead to set the path to `/`

**Comment by kgwadu** [comment]
> You can use `OrchardCore.HomeRoute` instead to set the path to `/`

I seem to already have the feature "OrchardCore.HomeRoute" enabled but i can't for the life of me figure out how i use it. I cant see any new content part or settings, the documentation on the wiki just describes what it does not how you use it, cant find anything online with details as to how this works.

**Comment by sebastienros** [comment]
You said two contradictory things, can you clarify?

> we have the home page set as the home page

> "OrchardCore.HomeRoute" enabled but i can't for the life of me figure out how i use it

You have set a content item as the home page if its autoroute has the checkbox "Home page" checked in its editor (available if you enabled the HomeRoute feature).

At that point whatever is in the autoroute textbox, the `/` endpoint will load your content item. We would expect the sitemap to use this url too (and not the canonical one with whatever slug it has, and which should be greyed out in the editor).  If the sitemap doesn't do that it might be a bug there.

**Comment by kgwadu** [comment]
@sebastienros @hishamco Ok i had already said in my original message that i was having an issue with the home page so when "OrchardCore.HomeRoute" was mentioned i thought there was something additional that i was missing. So to reiterate, we have a content item which has Home Page selected in the autoroute and in the sitemap, the url for the home page is displaying the full path of the autoroute (https://www.domain.com/home-page) instead of just the domain (https://www.domain.com/).

**Comment by jtkech** [comment]
Yes Sitemap retrieves the url e.g. from `AutorouteContentHandler.GetContentItemAspectAsync()` that populate `metadata.DisplayRouteValues`, may need to check if the content item has an `AutoroutePart` whose `SetHomepage` is set to true.

**Comment by kgwadu** [comment]
@jtkech the current home page has an autoroute and SetHomepage is set to true. I cant imagine this not being a big deal for most sites who expect their home page url to only contain the primary domain and not include an additional path.

**Comment by jtkech** [comment]
Yes I think you are right, just need someone to focus on it a little and suggest a PR.

Hmm yes should be fixed, I may do it if nobody else start something.

Ping me again if I forget ;)

**Comment by hishamco** [comment]
I might have a look if @kgwadu not planning to push a PR for it

**Comment by kgwadu** [comment]
@jtkech  @hishamco that would be great, i dont think id be able to look into this anytime soon.

**Comment by hishamco** [comment]
No hurry, but if you gonna do it, I will assign it to you, otherwise one of us should fix it one day ;)

**Comment by jtkech** [comment]
Fixed through #12729
