### ISSUE TITLE
BUG - Adding the All Features step to deployment plan destroys app when imported

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#12611]
If you import a deployment plan zip file that has the All Features step then things get destroyed in the content editor part of the app.
For example the Title Part disappears completely.

**Comment by MikeAlhayek** [comment]
@JoshTango can you please provide steps to re-produce the issue?

> destroyed in the content editor
What does this mean? Please elaborate and share screenshots if possible.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
