### ISSUE TITLE
Make the AdminTheme default to any theme other than "darkmode"

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12625]
### Describe the bug
I have a mobile app that behaves as a wrapper which renders an OrchardCore based website. When running this mobile app on IOS, for some odd reason the value of `data-theme=default` in the Admin theme gets changed to `light` instead of default so it becomes `data-theme=light`. Since TheAdmin theme only is aware for `default` and `darkmode` the admin theme does not render correctly in the mobile app.

Unless there is a value not too, I think we can easily make TheAdmin theme supports `darkmode` and for anything else we load the `default` theme. By changing `:root[data-theme='default'] ` to `:root:not([data-theme='darkmode'])`

**Comment by hishamco** [comment]
> When running this mobile app on IOS, for some odd reason the value of data-theme=default in the Admin theme gets changed to light instead of default so it becomes data-theme=light

What kind of odd reasons, that change the current behavior?

**Comment by ns8482e** [comment]
If the value changed to `light` and if admin theme don't have such mode then it's either bug in code somewhere that needs to change invalid value `light` to `default`.
