### ISSUE TITLE
Add support for Shortcodes in IWorkflowExpressionEvaluator

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12634]
### Is your feature request related to a problem? Please describe.
When `IWorkflowExpressionEvaluator` is used to evaluate parameters used in the workflow, we only support for `Liquid` but not Shortcodes.

### Describe the solution you'd like
I think we should be able to support both `Liquid` and `Shortcode` in `IWorkflowExpressionEvaluator`

**Comment by ns8482e** [comment]
I guess short code has different purpose, intention of shortcode is display/rendering html not use as scripting.

Whereas overall liquid you can use as scripting like generating query, json, etc

**Comment by Piedone** [comment]
Agree with @ns8482e: we don't really need a third way of scripting workflows.
