### ISSUE TITLE
Lists - RSS feeds should be optional

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#12650]
### Is your feature request related to a problem? Please describe.
After activation of Feeds module, each List part gets its public url which can be accessed from public and cannot be secured.
List items can be intended to be private / handled in some custom way. If someone activates Feeds module, it can leak those data through newly added endpoint. 

I do not know if there is another endpoit which would show this data. Anonymous access of list on frontend is disabled by removing roles from anonymous user. 

### Describe the solution you'd like
Add option to disable/enable feed generation for given list part. Or permission implementation.

![image](https://user-images.githubusercontent.com/52829889/195979669-c911a6d0-1003-4ed0-b534-2f7f172ccf2e.png)
even setting custom url does not disable created endpoint

**Comment by hishamco** [comment]
Make sense to make the feed optional or configured by the list settings or at least adding a permission to limit the access

**Comment by ns8482e** [comment]
If I remember it's a feature that you can disable `"OrchardCore.Feeds`

**Comment by MikeKry** [comment]
@ns8482e  

Yes, you do remember correctly. But that does not allow selective enable/disable of specific feeds. You might want feature enabled, but just not for given feed.

**Comment by sebastienros** [comment]
Would be a good addition
