### ISSUE TITLE
Add a feature to send notifications to the user

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12651]
### Is your feature request related to a problem? Please describe.
Currently, there is no way to send a user a notification. We have a way to send an email using workflows but not true notification. A notification can send via Web, Email, Push, SMS, etc. A user will need to be able to opt-in/out of receiving notification. Some people may opt-in Push + Web notification but opt-out Email notification.

These notifications will likely to be triggered by workflows.

/cc @Skrypt

**Comment by ns8482e** [comment]
If Notification is needed in OrchardCore then it should not be tied to User/CMS - It should be part of Framework, It should be a service that can be Subscribed to an event and Subscriber can be notified for given event

**Comment by MikeAlhayek** [comment]
@ns8482e you should review PR #12638. These notifications are event driven like from workflow or from code. The interfaces depend on `IUser` to function whereas the core implementation is for the CMS since we depend on `YesSql` to store notifications and also on `User` object to give us more info about the user. For example, if a user want email notification, we need to know which user to send to. If you want, you can create your own implementation of `INotificationManager` which does not need to store the data in YesSql or the `User` object then use `IUser` to use other methods to deliver notification to the `IUser` object like if you just want to create a SignalR websocket that would just deliver the notification instantly and/or use your own store to store notifications.

**Comment by ns8482e** [comment]
What I mean to say is if notification is a service, then you can have any subscriber not just `IUser` as long as object has notifiable properties like - Email, Mobile (sms), Phone (voice), Fax then you can send notification using the service.

**Comment by giannik** [comment]
@MikeAlhayek A signalr implementation would be usefull to provide realtime notifications (like a chat app). Im wondering if a signalr impelmentation would work for multitenancy scenarios  ? So the messages that are sent are isolated per tenant.

**Comment by MikeAlhayek** [comment]
@giannik yes it's on my todo https://github.com/OrchardCMS/OrchardCore/pull/12638 read the todo items there
