### ISSUE TITLE
Media Field does not resolve the Public URL of media items

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1266]
The Media Field view model does not contain the public URLs of the media items it contains. This means that anyone just using the `Model.Field.Paths` property will find that their media item paths can be incorrect.

e.g. At its simplest, the path `images/myimage.jpg` needs to be `/media/images/myimage.jpg` in order to display it on the front end. It starts getting a bit more complicated if you have a tenant with a path prefix, or are using the Azure media storage implementation.

The work around is to inject `IMediaFileStore` into the view and call `MapPathToPublicUrl()` on each path, but I think this would be better done in the driver.

**Comment by sebastienros** [comment]
In liquid there is a tag to do that. In razor I think you should use `Url.Content`. But we might need a tag helper as we need to support custom cdns, and the method you are mentioning.

**Comment by etcetraw** [comment]
what would be the proper way of resizing the image in razor?  liquid tag appears to be just modifying the url.

**Comment by dodyg** [comment]
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Media/README/#image-resizing-filters

**Comment by sebastienros** [comment]
> liquid tag appears to be just modifying the url.

YEs, this is the only thing you need to do, then a middleware detects it in the request and give you a transformed image

**Comment by agriffard** [comment]
@paynecrl97 The PR #1267 has been closed. Is this issue related and can be closed?
