### ISSUE TITLE
NRE when rebuilding some Indexes after updated to 1.5-preview

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#12668]
### Describe the bug
Was on 1.4-preview-16817, after updating to 1.5-preview-17109 got this issue when rebuilding some of my indexes:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Search.Lucene.LuceneIndexManager.CreateLuceneDocument(DocumentIndex documentIndex, LuceneIndexSettings indexSettings)
   at OrchardCore.Search.Lucene.LuceneIndexManager.<>c__DisplayClass17_0.<StoreDocumentsAsync>b__0(IndexWriter writer)
   at OrchardCore.Search.Lucene.LuceneIndexManager.WriteAsync(String indexName, Action`1 action, Boolean close)
   at OrchardCore.Search.Lucene.LuceneIndexManager.StoreDocumentsAsync(String indexName, IEnumerable`1 indexDocuments)
   at OrchardCore.Search.Lucene.LuceneIndexingService.<>c__DisplayClass10_0.<<ProcessContentItemsAsync>b__0>d.MoveNext()
```

Could be the same as #457 and maybe the fix was lost with the ElasticSearch refactor?

**Comment by mariojsnunes** [comment]
From the stacktrace I assume the NRE is on LuceneIndexManager.CreateLuceneDocument

**Comment by Skrypt** [comment]
If you could repro that would help find why the LuceneIndexSettings are returning a NULL value. Else the fix you are mentioning is merely a sanity check on the DocumentIndex entries values to make sure they are not NULL. It seems to have been removed at some point. I could reinsert it back if the issue is on an Entry value that is NULL. Though, since we are migrating the IndexSettings to LuceneIndexSettings I would take a look in my database to see if these have been migrated properly first.

**Comment by mariojsnunes** [comment]
Okay I'll check that first, thanks!

**Comment by mariojsnunes** [comment]
Okay LuceneIndexSettings were correctly migrated.
This is happening because ContentItemVersionId is null:
![image](https://user-images.githubusercontent.com/8073622/196926902-382f5741-9527-4bfb-9fe0-1055ed43aeb6.png)

**Comment by mariojsnunes** [comment]
This might be due to custom code for creating ContentItems which is not generating the version.
I'll try to replicate.

**Comment by mariojsnunes** [comment]
Okay so the issue was caused by creating content items with NewAsync and PublishAsync only. Need to call CreateAsync before PublishAsync to generate the VersionId.

Question: To fix my databases can I simply generate the ContentItemVersionId and update the items on ContentItemIndex?

**Comment by mariojsnunes** [comment]
Even after updating the tables with ContentItemVersionId and deleting Lucene folder from App_Data, ContentItemVersionId remains null. Any idea why?

Anyway, this would fix my issue:
![image](https://user-images.githubusercontent.com/8073622/197013611-ef6cef4b-da5d-483d-a289-85c56d9432ab.png)
Would it be accepted if I create a PR?

**Comment by hishamco** [comment]
Go for it @mariojsnunes, then ryou can request @Skrypt for approval

**Comment by jtkech** [comment]
Just for info, yes we use NewAsync() for example to create a fake item before checking for an authorisation, as I remember we also use NewAsync() to build items embedded in a BagPart. So would mean that these items are not intended to be stored. Hmm, we could have used `CreateAsync()` for BagPart items, but it also does a session save that we can't do for embedded items.

But yes maybe `NewAsync()` could at least auto generate a `ContentItemVersionId` to not have this kind of issue and it would not bother the above usage, but not calling `CreateAsync()` also means that the related handlers are not called.

**Comment by mariojsnunes** [comment]
Okay also updating ContentItemVersionId on the Document table fixed the issue, I am closing this.

@jtkech yeah this would not happen if it is generated on NewAsync().
Although it could be unnecessary work if authorization fails... And, like you said, we are supposed to call CreateAsync anyway 🤔.

Thanks for the help!!
