### ISSUE TITLE
Setup page not work, No error information is recorded when the database connection fails

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#12679]
First of all, I found that I could not add tenants in my program. I kept prompting that the connection string was incorrect or the server was unavailable. In fact, there was no problem with the database server.
My project uses OC 1.5.0-preview-17106

And Setup page not work.
After filling in all the contents, submit without prompting any error, and still stay on the Setup  page

![image](https://user-images.githubusercontent.com/15613121/197240301-87041513-5488-4770-be3c-5fd984a2e733.png)

To verify this problem, I pulled the latest code and ran the installation program directly using the latest source code. The same problem applies

**Comment by hyzx86** [comment]
Add Tenant
![image](https://user-images.githubusercontent.com/15613121/197241214-1e18ef38-a739-4649-8b44-48a79da9e50d.png)

**Comment by hyzx86** [comment]
Should I write the error information to the log file?
Instead of being ignored when encountering problems?

https://github.com/OrchardCMS/OrchardCore/blob/2385c92dfc3e97324d8031def75e99007c85c80b/src/OrchardCore/OrchardCore.Data.YesSql/DbConnectionValidator.cs#L77-L89

**Comment by hyzx86** [comment]
Solved, after  add Encrypt=false or TrustServerCertificate=True

https://github.com/OrchardCMS/OrchardCore/issues/12653

But I think the error information should be recorded. Not everyone will debug the source code to find problems..

**Comment by MikeAlhayek** [comment]
I am logging the error to provide the admin more info about the error. Can't do much on the UI as this is only impacts SQL Server connection.

**Comment by hishamco** [comment]
Could be related to the TRUSTED connection?
