### ISSUE TITLE
Content between tenants Broadcasting, data sharing

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1268]
Content between tenants Broadcasting, data sharing

For example (Site Clusters):
Set up a group company, there are many subsidiaries.
"Tenant 1" represents the group company site; "Tenant 2", "Tenant 3" represent two different affiliate sites;
 Tenant 1 needs the latest two latest news articles about Tenant 2 and Tenant 3 in the latest news bulletin.

Just suggestive ideas, do not know if they are interested in PR;
Or is there any way to achieve data sharing between tenants?
```
租户之间的内容Broadcasting，数据共享
例如（站点集群）：
建立一个集团公司，有很多子公司。
“租户1”代表集团公司站点；“租户2”、“租户3”，代表两个不同的子公司站点；
 “租户1”需要在新闻文章最新动态公告中获取“租户2”、“租户3”最新的前面2条最新的新闻文章内容。

只是建议性想法，不知道是否有兴趣公关；
或者有什么方法可以实现租户间的数据共享呢？

```
![1](https://user-images.githubusercontent.com/28694676/33514923-6545927a-d796-11e7-9956-a2ef8d653de9.png)
![2](https://user-images.githubusercontent.com/28694676/33514924-65762f8e-d796-11e7-8107-0b3ce9326ad2.png)
![3](https://user-images.githubusercontent.com/28694676/33514925-65a56448-d796-11e7-939c-a982a56f4a3d.png)

**Comment by paynecrl97** [comment]
You *might* be able to do this if you set up a deployment plan, and then configure remote deployments between the tenants?

It wouldn't be an automated sync (i.e. publishing new content on Tenant A wouldn't automatically push it to Tenant B), but maybe that could be achieved once the workflows module is completed?

**Comment by sebastienros** [comment]
This will be automated once we have workflow activity for it.

**Comment by pgy866** [comment]
Thank you
