### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#12680]
### Prepare the project

Do some housekeeping on GitHub in the [main repo](https://github.com/OrchardCMS/OrchardCore).

- [ ] Close remaining issues for the version (including merging corresponding pull requests if suitable) or assign them to the next one.
- [ ] Assign all issues that were closed for an upcoming version (including a wildcard version like "1.0.x") to this version (milestone).

### Prepare the code

Update the source so everything looks like on the new version.

- [x] Create a `release/<version name>` branch out of `main`.
- [x] Update code generation templates in `OrchardCore.ProjectTemplates`.
- [x] Update the `OrchardCore.Commons.props` file: Update `VersionPrefix` for release versions (like "1.0.0") and `VersionSuffix` for pre-release versions (like "rc2", for the full version to be e.g. "1.0.0-rc2").
- [x] Update module versions in `ManifestConstants`.

### Prepare and publish Orchard Core Translations

Update everything in the [Translations project](https://github.com/OrchardCMS/OrchardCore.Translations). Only do this once all the code changes are done since localized strings can change until then.

- [x] Update .po files with [PoExtractor](https://github.com/lukaskabrt/PoExtractor). This will also update [Crowdin](https://crowdin.com/project/orchard-core).
- [x] Publish the new version on NuGet.
- [x] Update the `OrchardCore.Translations.All` package reference in the main repo's _src/OrchardCore.Build/Dependencies.props_ file to refer to the new NuGet package.

### Test the release

Make sure everything works all right.

- [x] Make sure that [OrchardCore.Samples works](https://github.com/OrchardCMS/OrchardCore.Samples).
- [x] - [Creating a modular ASP.NET Core application](https://docs.orchardcore.net/en/latest/docs/guides/create-modular-application-mvc/)
    - [Creating an Orchard Core CMS website](https://docs.orchardcore.net/en/latest/docs/guides/create-cms-application/)
    - [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/latest/docs/guides/decoupled-cms/)

### Prepare the documentation

Update the docs so they contain information about the new release so once the release is out you'll just need to point to new information.

- [x] Create release notes in a specific documentation section. You can take the previous release notes as a template.
    - Overview of the release's highlights and goals. What do you want people to remember this release for?
    - Prerequisites. What framework version do you need, anything else to work with Orchard?
    - Upgrade steps, any migration necessary from previous versions, breaking changes.

### Publish the release

Do the harder parts of making the release public. This should come after everything above is done.

- [ ] Merge `release/<version name>` to `master`.
    - Merges to `master` need two approvals so you'll need to create a pull request.
    - Merge it as a merge commit, not squash merge.
- [ ] Tag `main` with the full version name, including the prefix and suffix (e.g. "1.0.0-rc2").
- [ ] Test the [guides](https://docs.orchardcore.net/en/latest/docs/guides/) with the packages now automatically published to NuGet. Test at least the following guides:
    - [Creating a modular ASP.NET Core application](https://docs.orchardcore.net/en/latest/docs/guides/create-modular-application-mvc/)
    - [Creating an Orchard Core CMS website](https://docs.orchardcore.net/en/latest/docs/guides/create-cms-application/)
    - [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/latest/docs/guides/decoupled-cms/)
- [ ] Update [Try Orchard Core](https://github.com/OrchardCMS/TryOrchardCore).

### Publicize the release

Let the whole world know about our shiny new release. Savor this part! These steps will make the release public so only do them once everything else is ready.

- [ ] Update the documentation to mention the version in all places where the latest version is referenced, for example, but not limited to (do a search for the package version string): [Status in the root README](https://docs.orchardcore.net/en/latest/#status), CLI templates, commands, the [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/latest/docs/guides/decoupled-cms/) guide.
- [ ] Update the tagged [release](https://github.com/OrchardCMS/OrchardCore/releases) on GitHub: Change its title to something more descriptive (e.g. "Orchard Core 1.0.0 RC 2"), add a link in its description to the release notes in the documentation (something like `For details on this version see the [release notes in the documentation](link here).`). Add a link to this release under [Status in the root README](https://docs.orchardcore.net/en/latest/#status).
- [ ] Publish a blog post on the website.
- [ ] Ask to publish a blog post on [DevBlogs](https://devblogs.microsoft.com/).
- [ ] Ask to publish a blog post on [.NET Foundation News](https://dotnetfoundation.org/news).
- [ ] Tweet

**Comment by Skrypt** [comment]
The guides are not displaying properly on dev:

https://docs.orchardcore.net/en/dev/docs/guides/
https://docs.orchardcore.net/en/dev/docs/guides/create-modular-application-mvc/
https://docs.orchardcore.net/en/dev/docs/guides/create-cms-application/
https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/

Though they are fine on latest:

https://docs.orchardcore.net/en/latest/docs/guides/
https://docs.orchardcore.net/en/latest/docs/guides/create-modular-application-mvc/
https://docs.orchardcore.net/en/latest/docs/guides/create-cms-application/
https://docs.orchardcore.net/en/latest/docs/guides/decoupled-cms/

**Comment by agriffard** [comment]
I set the `dev` branch to hidden yesterday.

**Comment by Skrypt** [comment]
Nlog configurations have changed and there is no indication about it in the release.md file. We should advise people that the NLog configs have changed so that it doesn't lead to overlogging for them.

**Comment by deanmarcussen** [comment]
> Nlog configurations have changed and there is no indication about it in the release.md file. We should advise people that the NLog configs have changed so that it doesn't lead to overlogging for them.
> 
> https://github.com/NLog/NLog.Web/wiki/Missing-trace%5Cdebug-logs-in-ASP.NET-Core-6%3F

Also need to update the `UseNLogWeb` extensions to support passing an NLog config to enable the old behaviour.

Minor issue, but we tracked +1gb of logs this morning after deploying, because we rely on the aspnetcore logging section to reduce our log levels.

**Comment by Skrypt** [comment]
Well, it can become a security issue if the logs are filling the entire server storage. So, make sure to take a look before deploying.

**Comment by snakefoot** [comment]
> Also need to update the UseNLogWeb extensions to support passing an NLog config to enable the old behaviour.

It is also possible to overwite the default value using this static-property:
```c#
NLog.Web.NLogAspNetCoreOptions.Default.RemoveLoggerFactoryFilter = false;
```
The recommended approach is just to fix the NLog-configuration like this:
```xml
<rules>
    <logger name="System.*" finalMinLevel="Warn" />    <!-- Insert in the top -->
    <logger name="Microsoft.*" finalMinLevel="Warn" /> <!-- Insert in the top -->

    <!-- Everything else -->
</rules>
```
See also: https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlogextensionslogging-without-any-filter
