### ISSUE TITLE
position argument does not work on fluid resize_url filter

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#1269]
```{{ 'animals/kittens.jpg' | asset_url | resize_url: 100, 240 | img_tag }}```

as stated here https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Media/README/#image-resizing-filters

will only produce `?`.

```{{ 'animals/kittens.jpg' | asset_url | resize_url: width:100, height:240 | img_tag }}``` works.

**Comment by dodyg** [comment]
Also I wonder why this resizing does not work

http://innolabs.me/media/project/game-arena/0ScreenShot_11_16_2017_3_43%20PM_.png?width=16&height=32

**Comment by sebastienros** [comment]
For your question I assume this is a bug in ImageShart that has been resolved the same day we shipped beta1. Because of the `%20` in the url.

**Comment by j42house** [comment]
Did removing %20 from you filename solve your issue? Resizing is not working for me right now and I'm curious if you had another setup issue.
I am using this:
`{{ 'about/4.jpg' | asset_url | resize_url: width:50, height:50 | img_tag }}`
 and OrchardCore.Media Version 1.0.0-beta1-3667

**Comment by dodyg** [comment]
The resizing is not working.

**Comment by sebastienros** [comment]
Can someone try to change this line https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Media/Processing/MediaFileSystemResolver.cs#L50

to `var filePath = _mediaStore.MapPublicUrlToPath(context.Request.Path.Value);` ?

**Comment by jtkech** [comment]
For infos.

Just tried without any change.

- `{{ 'about/4.jpg' | asset_url | resize_url: width:50, height:50 | img_tag }}` works on my side, this in a liquid template and as a token in a body part.

- `localhost:2918/media/about/4.jpg?&width=50&height=50` in the browser address bar also works.

- But, if the image name has a space, it doesn't work.

Then, using `context.Request.Path.Value`.

- It also works if the image name has a space, the url is correctly decoded before mapping to a path.

**Comment by sebastienros** [comment]
Please create a PR, and also fix the documentation or the code so that it matches.

**Comment by sebastienros** [comment]
Maybe better if it accepts anonymous parameters in this case also.

**Comment by jtkech** [comment]
Ok. So, you mean that the following would work.

    {{ 'animals/kittens.jpg' | asset_url | resize_url: 100, 240 | img_tag }}

As i remember, most of filters could have a default (and required) argument (not a named one) but only one. But indeed, for this one it makes sense to have 2 default arguments. So, as you want.

**Comment by sebastienros** [comment]
can't we do `arg.At(0)` and `arg.At(1)` if the named ones are not here?

**Comment by jtkech** [comment]
Yes we can, i will do it, something like `.Or(arguments.At(0))`.

**Comment by j42house** [comment]
FYI for anyone that still didn't get resizing working, my issue turned out to be unrelated and was due to Image Sharp requiring a wwwroot folder at the root of my .Web project folder

**Comment by sebastienros** [comment]
This is why we force the creation of this folder by placing a file inside.
