### ISSUE TITLE
Running a deployment plan

### ISSUE THREAD

**Issue by Binary-Man** [OrchardCMS/OrchardCore#1270]
After creating a deployment name and clicking on this name you get:

InvalidOperationException: Unable to resolve service for type 'OrchardCore.ContentManagement.IContentManager' while attempting to activate 'OrchardCore.Deployment.Steps.AllContentDeploymentSource'.

**Comment by Binary-Man** [comment]
It would seem, that services for ContentManager weren't included in AddDeploymentServices in OrchardCore\OrchardCore.Deployment.Core\ServiceCollectionExtensions.cs.
By including these interfaces listed below and their concrete classes the problem went away:

 services.AddScoped<IContentManager, DefaultContentManager>();
 services.AddScoped<IContentDefinitionManager, ContentDefinitionManager>();
services.AddScoped<IContentItemIdGenerator, DefaultContentItemIdGenerator>();
services.AddScoped<IIdGenerator, IdGenerator>();

**Comment by sebastienros** [comment]
If this solved the issue, then I can assume you are not actually using the content manager, or it would already be registered. If I am right then you shouldn't use this step.

I am keeping the bug open as the solution is to move this step in the Contents module, where it should be defined as a `[RequireFeature]` over Deployment.

**Comment by Binary-Man** [comment]
Yes you're right i'm not using the content manager, i'm deploying my own modules using the framework.
What step should I use?

**Comment by sebastienros** [comment]
You can submit a PR that moves the content management steps into the content management module.

**Comment by agriffard** [comment]
The content steps are in a different startup in the contents module:
https://github.com/OrchardCMS/OrchardCore/blob/3325a9abaa347c508f69134b3af3a16a054c8762/src/OrchardCore.Modules/OrchardCore.Contents/Startup.cs#L143
