### ISSUE TITLE
Remove tenants as scope from OrchardCore.OpenId.Management feature when it's not running in the default tenant

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12722]
### Is your feature request related to a problem? Please describe.
The feature "OrchardCore.OpenId.Management" allows adding, editing and removing the registered applications. Also, this module is allowed for any tenant to be able to use as it should. However, when you go to Scopes ends point which is part of the feature, you get a list of all running tenants even when you are not the default tenant. I think this is wrong. Its okay for a default tenants to see a list of all running tenants and add scope to different tenants. But I don't think we should allow a subtenant to add scope to other tenants.

### Describe the solution you'd like
Maybe we should [change the line] (https://github.com/OrchardCMS/OrchardCore/blob/6e3203e084c8a7091228c58be8367a74b5bd88bc/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ScopeController.cs#L183) to something like this instead

```C#
var model = new CreateOpenIdScopeViewModel();

if (_shellSettings.IsDefaultShell())
{
    foreach (var tenant in _shellHost.GetAllSettings().Where(s => s.State == TenantState.Running))
    {
        model.Tenants.Add(new CreateOpenIdScopeViewModel.TenantEntry
        {
            Current = String.Equals(tenant.Name, _shellSettings.Name),
            Name = tenant.Name
        });
    }
}
else
{
    model.Tenants.Add(new CreateOpenIdScopeViewModel.TenantEntry
    {
        Current = String.Equals(_shellSettings.Name, _shellSettings.Name),
        Name = _shellSettings.Name
    });
}
```

**Comment by MikeAlhayek** [comment]
@kevinchalet

**Comment by kevinchalet** [comment]
It's been designed this way to support having the authorization server in one tenant and one or multiple APIs in any other tenant. We could certainly restrict this ability to the default tenant only, but it would likely break a few users.

While your demand is about the OpenID module, it's actually not specific to OpenID. I believe "cross-tenant permissions" have been discussed at some point, but I'm not sure what the outcome was (it's likely a complicated thing to design and implement).

**Comment by MikeAlhayek** [comment]
@kevinchalet there is no demand made... its just a request :)

I am not aware of any other component that allow a sub tenant list all tenants like that "except for default". May be add a setting to enable/disable this behavior so one can turn it off if needed. To allow sub tenant to list all tenants in the environment is very weird. I think if we make it settings based, then we can allow backward compatibility, but also allow someone to prevent this from happening.

**Comment by jtkech** [comment]
> @jtkech is there any other components in OC that allow a sub tenant to list other tenants?

No as i remember

**Comment by ns8482e** [comment]
IMO even if A tenant customer is not utilizing  open id feature, by enabling module in their tenancy a tenant customer  can see who other tenants are, which is not good for hosting provider in multi tenant environment.

**Comment by ns8482e** [comment]
May be list of checkbox should be turned into comma separated list?

so if you know tenant name you can add it list for cross-tenant permissions

**Comment by MikeAlhayek** [comment]
@ns8482e I think the right thing to do is not to list all tenants for a sub tenant. But changing that would introduce a breaking change. The default site can have authentication server that would provide scope for other tenants but sub tenant should not be allowed to do such a thing. 

I suggested the configuration option just to not break existing tenants.

**Comment by ns8482e** [comment]
@MikeAlhayek I don’t think it’s breaking change for concerting selected checkbox to comma separated tenant names

**Comment by ns8482e** [comment]
@sebastienros its makes more sense to move the UI on edit tenant screen

**Comment by MikeAlhayek** [comment]
![image](https://user-images.githubusercontent.com/24724371/201182776-120ac346-a333-4173-b94d-4ff1085d0fba.png)

**Comment by sebastienros** [comment]
Recommendation, 
- Keep current UI to create scopes, with only the local tenant displayed and used in the controller
- If the edit scopes screen is executed from Default, then add a selection for which tenant's scopes to edit, and also list other tenants to be chosen from.

**Comment by MikeAlhayek** [comment]
@sebastienros the PR is ready for a review

**Comment by jtkech** [comment]
When I said that there is no other component listing other tenants, I didn't say that it is good or not ;)

As said by @kevinchalet maybe we are missing cross tenants permissions, maybe harder at the beginning but would prevent to change the behavior of tenants depending on being the Default tenant or not.

Yes, for me basically there is neither host tenant nor parent/childs tenants. Maybe OC would need to be a standalone application to manage tenants without a Default tenant, and being able to define groups. Or as it is currently, allow some way to define tenants groups, e.g. based on their enabled features.

But yes maybe too late and I'm not against the direction we are taking, I think @kevinchalet is best placed to see with @sebastienros if we're on the right path.

That said as I remember there is one place where we list tenants but only those having the openId server feature enabled, maybe here we could use the same kind of filtering.

**Comment by Piedone** [comment]
As a SaaS operator, not letting non-Default tenants list other tenants is crucial.
