### ISSUE TITLE
Make OrchardCore.Features not always enabled

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12723]
### Is your feature request related to a problem? Please describe.
Currently, the module `OrchardCore.Features` is always enabled. We recently added a feature for the default tenant to be able to manage features on the behalf of any tenant. Can we remove the `AlwaysEnabled` flag from `OrchardCore.Features` as the saas owner may not want to allow the tenant to control their own features.

**Comment by Skrypt** [comment]
That makes sense but that could be enabled/disabled by role/permission too.

**Comment by MikeAlhayek** [comment]
@Skrypt you can't enable/disable it currently because it is always enabled. So if we remove that flag, yes we can enable/disable it just like any other feature. We may need to just prevent it from being disabled using the UI when the current tenant is `Default`.

**Comment by Skrypt** [comment]
I meant that you could have permission/role to allow modifying "features" instead too. Or both, I don't mind. But the goal would be the same in the end.

**Comment by MikeAlhayek** [comment]
Features already have permission `Permissions.ManageFeatures`. But if you are a SaaS owner, and you don't want your tenants to manage their own feature, then you would just disable it for them. Instead, you'll be able to manage it their features using the features management on the default side.

But I think we agree that OC.Features should not always be enabled.

**Comment by MikeAlhayek** [comment]
PR is ready
