### ISSUE TITLE
Zone tag helper and zone rendering order issue

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1273]
Given a Layout like this:

```
@await DisplayAsync(Model.Title)
@await DisplayBodyAsync()
@await DisplayAsync(Model.Footer)
```

It is not possible to push shapes from a content zone into the layout Title zone using the `<zone name="/Title">` tag helper because the `Title` zone has already been rendered.

We should defer building the HTML until we know where all the shapes belong.

**Comment by jtkech** [comment]
As i remember.

In the layout you would need to use `RenderSectionAsync("ZoneName", required: false)`, then in the shape `<zone name="ZoneName">`.
