### ISSUE TITLE
View not found for ViewComponent in a different module

### ISSUE THREAD

**Issue by mcapewell** [OrchardCMS/OrchardCore#1274]
I am using the OrchardCore Framework (not CMS) to try and build a modular web app. I have a ViewComponent in Module B but the view cannot be found when this is used from Module A.

Any help would be greatly appreciated! Here is the error message displayed:

InvalidOperationException: The view 'Components/Test/Default' was not found. The following locations were searched:
/Packages/ModuleA/Views/Home/Components/Test/Default.cshtml
/Packages/ModuleA/Views/Shared/Components/Test/Default.cshtml
/Areas/ModuleA/Views/Home/Components/Test/Default.en-GB.cshtml
/Areas/ModuleA/Views/Home/Components/Test/Default.en.cshtml
/Areas/ModuleA/Views/Home/Components/Test/Default.cshtml
/Areas/ModuleA/Views/Shared/Components/Test/Default.en-GB.cshtml
/Areas/ModuleA/Views/Shared/Components/Test/Default.en.cshtml
/Areas/ModuleA/Views/Shared/Components/Test/Default.cshtml
/Views/Shared/Components/Test/Default.en-GB.cshtml
/Views/Shared/Components/Test/Default.en.cshtml
/Views/Shared/Components/Test/Default.cshtml

**Comment by sebastienros** [comment]
I am almost sure I am already doing something similar. In the Lists module I am calling a `ViewComponent` from the ContentTypes module, the one to render a list of Content Types to choose from.

**Comment by mcapewell** [comment]
Hi @sebastienros, you are right, I've seen that code and it works if I run a demo CMS application. But for some reason it doesn't work for my ViewComponent. I am not using CMS whereas ContentTypes seems to be part of the CMS rather than the Framework. Is there a difference here?

**Comment by mcapewell** [comment]
I have now uploaded my demo project where ModuleB can correctly display the ViewComponent, but ModuleA cannot.

https://github.com/mcapewell/MyWebApp

**Comment by jtkech** [comment]
As i remember, so not sure, but try to also define a `Startup : StartupBase` class in your ModuleB.

**Comment by mcapewell** [comment]
Hi @jtkech, thanks for the suggestion. Just tried that but still get the same error. I feel that I must be missing something simple like that.

**Comment by jtkech** [comment]
Ho, i think i understand.

With the cms items are composed of parts and fields which are rendered through drivers which act as sub controllers but returning shape views. So, in the context of a main controller defined in a given module e.g `ModuleB`, we can render shape views through drivers defined in others modules e.g in `ModuleA`.

Then a shape view whose driver is defined in `ModuleA` can invoke a shared view component defined in `ModuleB` but only if it is in the context of a main controller defined in `ModuleB`, the one which also defines the view component.

**Comment by mcapewell** [comment]
OK, I think I understand. So that explains how/why is works for the CMS. But should it or could it work in my case?

**Comment by jtkech** [comment]
So, any enabled module can provide shape views which use a view component defined in another module, e.g `ModuleB`. But only if it is in the context of the `ModuleB` "area".

See in your trace, razor also searchs in default locations as `/Areas/ModuleA/...` but not in `/Areas/ModuleB/...`. So i would say, at least for mvc, it's by design.

So, in your case i think it can't work, but i'm not against such a feature which allows to share view components accross modules areas. So we would need to resolve the component name from the requested view name / path, then lookup in the `ApplicationPartManager` for the registered `ViewComponentFeatures` to see which module provides this component and maybe see if the module is enabled...

@sebastienros do you think it is worth and allowed to do this?

For the cms, i think that, with the last dev branch, we can now share view components through a theme by putting them in the `CurrentTheme/Views/Shared/Components` folder.

But in your case you would need to put them in `/Views/Shared/Components` from the root.

Just tried, it works.

![hellofrommodulea](https://user-images.githubusercontent.com/8586360/33749979-3d5991dc-dbd1-11e7-873d-a965d0861da0.png)

**Comment by mcapewell** [comment]
Thanks for the helpful info @jtkech, it is very appreciated.

Let me explain to you our particular use case so you can assess whether there is a good case for inclusion as a feature in OrchardCore or not.

We currently have 10+ web applications that we would like to migrate to ASP.NET Core. We are currently prototyping how to do this in a modular way. Whilst having unique business functionality, each app does share the same look and feel, so we would like to implement UI items such as the main menu etc. as shared ViewComponents.

So in our case we do not want the views under the root `/Views/Shared/Components` because this would mean duplicating the views across the many host web applications.

I am currently looking into injecting another `IViewLocationExpanderProvider` as a possible solution.

**Comment by jtkech** [comment]
Yes, i understand.

This is what we do when using the cms through content and display management core features. This to compose items with reusable parts and fields, and render them through shape views. Modules can be enabled / disabled, we can define dependencies between them, and so on ... And we have themes (specific modules) where you can define / override shapes, controller and components views.

But you can create your own bundle, not all the cms, with the modules and the services you want. See which services are registered in `AddOrchardCms()`, e.g `AddThemingHost()` and `AddModules()` which defines default features as `OrchardCore.Commons` which call in its startup `AddTheming()`, and so on ...

So, one possibility would be to use the theming services without all the cms. But right now theming has a dependency on the cms, it is planned to remove this dependency. So, meanwhile you had a good idea to use new `IViewLocationExpanderProvider(s)`. This can be done through modules which define and register their provider in their startup, so they are used by our `CompositeViewLocationExpanderProvider`. This way you could have modules which embedd shared components views

This is exactly what we do for our `ThemeAwareViewLocationExpanderProvider` where we check what is the current front end theme (and its based themes) to add locations, but you can have your on logic.

**Comment by mcapewell** [comment]
Thanks again @jtkech for all of your help! Sorry but forgot to reply until now.

For the time being I have created an `IViewLocationExpanderProvider` similar to `ThemeAwareViewLocationExpanderProvider` and it appears to be working well.

**Comment by sebastienros** [comment]
@jtkech do we need to handle this?

**Comment by jtkech** [comment]
@mcapewell no worries.

@sebastienros i'm not against but i don't think so.

**Comment by sebastienros** [comment]
Would it work if the component's view was in a shared folder in the module?

**Comment by sfmskywalker** [comment]
> I am almost sure I am already doing something similar. In the Lists module I am calling a ViewComponent from the ContentTypes module, the one to render a list of Content Types to choose from

That works since the controller driving the view lives in OrchardCore.ContentTypes.

> Would it work if the component's view was in a shared folder in the module?

I tried, but doesn't work - only the shared folder of the project is checked, together with the module hosting the controller in context.

Expanding the view engine to include shared views from all modules might make sense. But how to deal with conflicting names in case two modules declare a VC with the same name?

**Comment by jtkech** [comment]
> But how to deal with conflicting names in case two modules declare a VC with the same name?

Yes, i thought about this and said to me that to make a VC local just use

    Views/<controller_name>/Components/<view_component_name>/<view_name>

And to share it

    Views/Shared/Components/<view_component_name>/<view_name>

But you're right, the last one would be to share the VC among controllers but in the same module. So, maybe find a way so a module could explicitly define a VC that could be share accross other modules. Maybe through a service or just by using another specific view location path.

**Comment by sebastienros** [comment]
When there are conflicts, the order of the location expander defines the winner. Like for shape templates. That's a good feature, not an issue.

**Comment by jtkech** [comment]
Yes, this is why in the @sfmskywalker PR i was talking about to

> ... see which of these modules (**ordered by deps**) are enabled ...

So, right now, for a controller view and then a VC, we also search in the theme views + module area name ... And recently we also search in the theme views shared folder without specifying the module area name.

But we could do the same for any other enabled and ordered modules **as we do for shapes** when using

    var descriptors = _shapeDescriptors
        .Where(sd => enabledAndOrderedFeatureIds.Contains(sd.Value.Feature.Id))

Humm, seems to make sense that modules could share views accross modules as they do for shapes. And this way i think they could share not only VC but also controller views.

I will work on it soon.
