### ISSUE TITLE
Is https://docs.orchardcore.net/en/dev/ supposed to work?

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#12745]
### Describe the bug
For a long time I've had a bookmark to [https://docs.orchardcore.net/en/dev/](https://docs.orchardcore.net/en/dev/). A few days ago I noticed all the styling appears to be broken.

### To Reproduce
1. Go to [https://docs.orchardcore.net/en/dev/](https://docs.orchardcore.net/en/dev/)

### Screenshots
![image](https://user-images.githubusercontent.com/68876423/199096214-4970a36a-eb9b-450f-8450-1916061901ed.png)

I just today noticed there is also [https://docs.orchardcore.net/en/latest/](https://docs.orchardcore.net/en/latest/). Is that what I'm supposed to be using?

**Comment by agriffard** [comment]
You are supposed to use https://docs.orchardcore.net/en/latest/ which is the default redirection and same than `main`.
`dev` is not used anymore and I disabled it from readthedocs last week to prevent old docs.

**Comment by agriffard** [comment]
There was some assets that were not loading properly on the 404 page.
I changed it to simply say that the url has not been found and suggest to go back to the homepage.

**Comment by rjpowers10** [comment]
Thanks for the response. I'll update my bookmark to just be [https://docs.orchardcore.net/](https://docs.orchardcore.net/]). I think I bookmarked the old dev version way back before OC 1.0.
