### ISSUE TITLE
Liquid zone in template

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1275]
I created an application with OC.Targets as a Nuget package andn a custom theme.

There is a BeforeContent zone in my layout.cshtml.

I made a Template for a Content type.

When I use this kind of code in the Template:
```
{% zone "BeforeContent" %}
....
{% endzone %}
```
If I run it locally, it works.

But if I publish in a folder and host the application in IIS, there is an error with the text inside:
_An error occured while executing this request._
The Layout around is correctly rendered but there are some widgets rendered twice.

There is no logs if I enable them.

@jtkech : any idea?

**Comment by jtkech** [comment]
Just tried to repro but it works on my side, even in a published context.
What happens if you remove the zone part in your template, are these widgets still rendered twice?
What happens if you remove some of these widgets, is this zone part still not rendered?

**Comment by agriffard** [comment]
Have you tried with the source code of OC or an empty application with OC.Targets package?
I use the latest version of OC.Targets

I started from the Agency recipe so the template that causes the error is `Content__LandingPage`.

If I remove the `zone` in the template, it works.

I also have errors 500 in admin after I save a template or a widget without knowing the cause, but the contents are saved though.

The pictures from /media also cause an error with the message.

**Comment by agriffard** [comment]
I host it on IIS with a binding on localhost:90 to test it locally.

I installed the dotnet windows hosting module.

**Comment by jtkech** [comment]
No, source code + blog theme, then publish. I will try with last packages and the agency asap.

Meanwhile, not sure it's related, but the only thing i saw that was really different in a published context was related to the liquid script tag helper. Normally it matches and executes our razor `ScripTagHelper`, but in some context another mvc taghelper might be selected first.

The result is that some scripts could be at a wrong place (e.g not after jquery) and produce some errors. I fixed it on my branch, it is very easy. In our razor `SrciptTagHelper.cs` just rename the property `Src` to another name e.g `Source`.

**Comment by jtkech** [comment]
Did not have enough time but just tried with the latest version of OC.Targets, the Agency recipe, then adding a `BeforeContent` zone and use `{% zone "BeforeContent" %}` in the landing page, then publishing. All seems to work well but here still with IISExpress.

Tomorrow night, i will do more tests after installing IIS and the dotnet windows hosting module on my local machine.

**Comment by jtkech** [comment]
Just re-tried.

Last OC package references + IIS + dotnet hosting module, local port 90...
I used a clone of the agency theme where the layout displays a BeforeContent zone.
Then i packed this new theme to use it as a package from a local feed.

Then, after an agency setup, i selected this theme, added a simple html widget in the BeforeContent zone. Then i used the zone tag helper in the landing page, this to add 2 simple texts.

Then it was working, sorry i can't repro :(

**Comment by agriffard** [comment]
Even if I change the selected theme and use TheAgency, I have the error.

**Comment by agriffard** [comment]
I will try to check the IIS logs.

**Comment by agriffard** [comment]
I can see the errors 500 but it doesn't give me any other details.

**Comment by jtkech** [comment]
> I also have errors 500 in admin after I save a template or a widget without knowing the cause, but the contents are saved though.

Humm, i could repro the error 500 issue if i use `Sqlite` and if i remove the writing access of the iis site on the published folder. Then no logs and the content seems to be saved but in fact it is only cached because if i restart the site i can see that it was not saved.

**Comment by agriffard** [comment]
OK. Thank you. It seems related. I indeed use a sqLite database.

I had readonly on my folders. I published in C:\inetpub\wwwroot\mysite.

I moved it and updated the properties of the yessql.db to remove the readonly.

I can now save the Template in admin but the error in front is still occurring.

**Comment by jtkech** [comment]
Okay.

For infos, i gave to my testing site the full control on all the published folder.

![autorisations](https://user-images.githubusercontent.com/8586360/33742526-0444f90e-dba9-11e7-9abc-ec4663367502.png)

**Comment by agriffard** [comment]
OK. Now I have logs working and damn, I know where it comes from.

I had the same issue a month ago on my other site : #1156

**Comment by agriffard** [comment]
I added this in my .csproj and it now works:
`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`

**Comment by jtkech** [comment]
Okay cool.

Indeed we have this for `OrchardCore.Cms.Web`. Normally, the `refs` folder is used for view compilation at runtime, so i thought we kept this just in case people use precompilation but afterwards still add some views under their published app.

Humm, just remembered that we serve a default content for `/_ViewImports`. It is done by code but maybe razor still needs refs assemblies to compile it. I will check this.

**Comment by jtkech** [comment]
So, not completely sure, but based on my last tests it seems that when a theme doesn't include a `_ViewImports` as `TheBlogTheme`, we serve a default one by code and then razor ask us for our `refs` assemblies which doesn't exist... If i don't provide any additional references, razor still fails on some missing assemblies. So, for our default `_ViewImports` content, i will try to provide a full precompiled view.
