### ISSUE TITLE
bug : LIMIT is not supported?

### ISSUE THREAD

**Issue by etcetraw** [OrchardCMS/OrchardCore#1276]
I think LIMIT should work in sql queries but does not seem to be working. I am trying SELECT * FROM ContentItemIndex join document on ContentItemIndex.DocumentId = document.id where ContentType like "BlogPost" LIMIT 5

**Comment by hishamco** [comment]
Could you please verify whether this a YesSql bug or not? Because I already saw similar one with a specific version of MS SQL Server long time back

**Comment by sebastienros** [comment]
It's an issue in the SQL Parser in Orchard. It doesn't parse and convert LIMIT statements. And we need to define which syntax we want to support.
