### ISSUE TITLE
Bugs in displaying the localized calendar!

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/OrchardCore#12762]
In version 1.5.0, when we define the date field and change its type to Localized. In the data entry form, the calendar is not displayed correctly.
The calendar is also not localized. For example, the Arabic calendar does not work.

![image](https://user-images.githubusercontent.com/13555275/200100704-3a950a45-0d7b-4b8d-b769-c72970f669c5.png)

![image](https://user-images.githubusercontent.com/13555275/200100562-edad0751-7c66-4b3d-a95d-e0d583be6971.png)

**Comment by hishamco** [comment]
@Skrypt is there something broken in the bootstrap?

**Comment by asemandeveloper** [comment]
> @Skrypt is there something broken in the bootstrap?

Thank you
Maybe.
Also, when I have selected the Arabic culture, it does not show the Hijri (Arabic) calendar.

**Comment by hishamco** [comment]
Hijri calndar is another thing, I don't think we support this in terms of UI, but it would be a big plus for Arabian ;)

**Comment by micrub-it** [comment]
I have the same problem with IT localzation

**Comment by stoyandimov** [comment]
@hishamco, I'm don't think localized calendar renders with bootstrap. Looking at the resource manager, it's probably still `jQuery-ui`.

[In this PR](https://github.com/OrchardCMS/OrchardCore/pull/13115), I ensure the `jQuery-ui` resources are included when the editor is displayed . I didn't want to switch to `bootstrap-datepicker` without discussing it first, but I hope this PR will be good enough fix for v1.6.

**Comment by hishamco** [comment]
> @hishamco, I'm don't think localized calendar renders with bootstrap

Sure this will not be rendered properly

**Comment by asemandeveloper** [comment]
Hello to all
As with Orchard CMS, it is better to display the calendar based on the selected culture. For example, if the Arabic culture is selected, the calendar will also show Hijri.
In your work, only the title of the months changes and not the dates and days of the calendar.

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/13115#issuecomment-1449687574
