### ISSUE TITLE
Add ContentType on the alias index.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12764]
### Is your feature request related to a problem? Please describe.
Sometimes one want an alias per content type. instead of having to hard code the content type as part of the alias. It would be good to add ContentType column to the index just like we currently have Published and Latest

**Comment by sebastienros** [comment]
An alias should be unique for the whole content items, if it's not the case that's a bug.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Alias/Handlers/AliasPartHandler.cs#L85
