### ISSUE TITLE
Expose Content Fields Indexing via GraphQL for content field filtering

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#12781]
### Is your feature request related to a problem? Please describe.
If you want to filter (with `where`) on the value of content fields, you have to implement a `WhereInputObjectGraphType` for it. There's no built-in way to filter on content field values from GraphQL.

This came up in [this discussion](https://github.com/OrchardCMS/OrchardCore/discussions/12630) too.

### Describe the solution you'd like
We already have [Content Fields Indexing](https://docs.orchardcore.net/en/latest/docs/reference/modules/SQLIndexing/#content-fields-indexing) to be able to run SQL queries for field values. Let's build on that, and expose such SQL indices in GraphQL too.

### Describe alternatives you've considered
An alternative would be to manually create indices for each field, and a `WhereInputObjectGraphType` for each of them.

Also, we could expose SQL Queries too: https://github.com/OrchardCMS/OrchardCore/issues/16008.

**Comment by Piedone** [comment]
@MikeAlhayek you may be interested in this.

**Comment by MikeAlhayek** [comment]
@Piedone thanks. Yes this is what is needed to allow one to filter by specific fields. I don't have much time to dig in, have anyone started working on this? Currently the API isn't very useful without this

**Comment by Piedone** [comment]
I'm not aware of anybody working on this.

**Comment by hishamco** [comment]
I remembered @carlwoodhouse was working on GraphQL, also I don't want to forget @hyzx86 he did a great contributions on both workflow and GraphQL

**Comment by hyzx86** [comment]
Why don't you try a script query? 
I've already made one. that works very well. Opened the door to a new world ;)
In this issue , There is a video at the bottom of the page. 


https://github.com/OrchardCMS/OrchardCore/issues/12766
it can do more than just query.  

If you're interested, you can find that in EasyOC. 
https://github.com/EasyOC/EasyOC/tree/main/src/Modules/EasyOC.Scripting

**Comment by hyzx86** [comment]
The current SQLIndex feature data insertion efficiency is too low.

In my project, I used a dynamic type definition of OC to generate C # class, use [Natasha](https://github.com/dotnetcore/Natasha)

The definition of C# class is store in a content item, and the DynamicIndex Type will build from the contentitem when needed
![image](https://user-images.githubusercontent.com/15613121/201068977-39f7cedb-f3af-42fa-883f-ebec9926c21f.png)

And then created an index table with FreeSQL (ORM) to filter the fields completed by the Part+fields

https://github.com/EasyOC/EasyOC/blob/f247642590b9f2be6f2b00b14a5693ff22c7283c/src/Modules/EasyOC.GraphQL/Queries/PagedContentItemsQuery.cs#L108-L136

![image](https://user-images.githubusercontent.com/15613121/201066845-e88698dd-1f01-46f2-99a8-70ace72d4633.png)



But now I think Lucene Index is what we should pay more attention to
It's just that the index management of fields is a bit troublesome.
And it does not support searches that ignore case

**Comment by Piedone** [comment]
Duplicates https://github.com/OrchardCMS/OrchardCore/issues/7047.
