### ISSUE TITLE
Publish later does not work on multiple servers after upgrading to 1.5.

### ISSUE THREAD

**Issue by ItaloFSS** [OrchardCMS/OrchardCore#12787]
After updating to Orchard Core 1.5, content scheduled to be published only gets published on a single server instance. All other instances get a 404 when browsing the URL, and manually republishing the content fixes the issue.

**Comment by hishamco** [comment]
It's just happening on multiple servers?

**Comment by ItaloFSS** [comment]
We run our website on three servers on Azure. The content gets published on the server where the publish later background task runs. If I keep refreshing the browser, it works every once in a while when the request is served from the published server.

**Comment by ItaloFSS** [comment]
It only happens in a multiple server environment. I haven't been able to reproduce locally. 

We use the Redis Bus feature to keep the content in sync across multiple servers. Everything worked great in 1.4, it broke over the weekend when we migrated the website to 1.5.

**Comment by ItaloFSS** [comment]
Found the issue. When we upgraded the website, we published it to the staging slot and swapped it to production. After the swap stage was now running Orchard 1.4, for some reason, it was causing a conflict with the 1.5 in production. After updating the staging slot to 1.5, the issue went away.
