### ISSUE TITLE
NLog.Extensions.Logging changes capture of EventId

### ISSUE THREAD

**Issue by MZole** [OrchardCMS/OrchardCore#12790]
### Describe the bug

[NLog.Extensions.Logging v5 changes](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlogextensionslogging-changes-capture-of-eventid) from `EventId_Id` and `EventId_Name` to `EventId` and `EventName`.

### Expected behavior
Changing to `${event-properties:item=EventId}` [here](https://github.com/OrchardCMS/OrchardCore/blob/0f1acae452e6cca2c5fa7f062e4e6c9c71e60540/src/OrchardCore.Cms.Web/NLog.config#L17).

**Comment by Piedone** [comment]
It was @snakefoot kind enough to let us know about this [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/264#discussion_r1018376993).

**Comment by Skrypt** [comment]
Two Zoltán on the same issue... that's abuse. 😉
