### ISSUE TITLE
NET Foundation CLA bot not running under PRs

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#12808]
### Describe the bug

The .NET Foundation CLA bot until recently (when Sebastien disabled it) didn't run for PRs, causing all open PRs to show up as pending, without people actually being able to do anything about it.

Just opening this to have an issue for the discussion during [this community meeting](https://www.youtube.com/watch?v=MnF3V3H52GE&t=276s).

I've reported this back in February [here](https://github.com/dotnet-foundation/website/issues/1086), with nobody responding. Though at the time I thought this only affects some random PRs, not all.

### To Reproduce
Since it's disabled now, no way to reproduce it. Check out the above-linked recording for details.

### Expected behavior
The CLA bot asks the contributor to sign an agreement if they're new, or approve the PR.

**Comment by hishamco** [comment]
https://github.com/aspnet/Announcements/issues/501

**Comment by Skrypt** [comment]
Related : https://github.com/OrchardCMS/OrchardCore/discussions/13332
