### ISSUE TITLE
Administrator stereotype in OrchardCore.Deployment

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#1280]
Hi,
In the deployment module, the ManageDeploymentPlan permission has not been added to the Administrator stereotype. Is this an expected design or has it been omitted?

[OrchardCore.Modules/OrchardCore.Deployment/Permissions.cs](https://github.com/OrchardCMS/OrchardCore/blob/e64191cb19346afe1fd28a1ca28a2aaa00d19d52/src/OrchardCore.Modules/OrchardCore.Deployment/Permissions.cs)
`
               new PermissionStereotype
                {
                    Name = "Administrator",
                    Permissions = new[] { Import, Export }
                }
`

Usually Administrator has all permissions. Why not use : `new PermissionStereotype{Name=Administrator, Permissions = GetPermissions();}` in all Permissions classes?
The `GetDefaultStereotypes()` method could be added in a PermissionsBase class that defaults Administrator stereotype to all permissions.

Regards,
Jérôme Piquot
[Flexmind France](http://www.flexmind.fr)

**Comment by sebastienros** [comment]
It has to be added manually

**Comment by jpiquot** [comment]
Hi Sebastien,

Thank you for the answer.

Regards,
Jérôme Piquot
[Flexmind France](http://www.flexmind.fr)
