### ISSUE TITLE
Why  ‘TitlePart.Edit.cshtml’ overridden in module doesn't work?

### ISSUE THREAD

**Issue by rllxxx** [OrchardCMS/OrchardCore#12817]
### I want to rewrite TitlePart html in my module，

I have some try，

- rewrite it in theme,  file name is 'TitlePart.Edit.cshtml'---it can work
- rewrite it in module, file name is 'ContentType-TitlePart.Edit.cshtml' ---it can work
- rewrite it in module, file name is 'TitlePart.Edit.cshtml'---it can  not work × 

Why? , looking forward to your reply.

thks.

**Comment by ns8482e** [comment]
Add dependency in your module

**Comment by rllxxx** [comment]
> Add dependency in your module

![image](https://user-images.githubusercontent.com/13895891/201835724-c2995c50-d11f-460a-9f66-fe9f98da94c8.png)

I added `OrchardCore.Title` dependency in my module, but it still  doesn't work

**Comment by jtkech** [comment]
Add a dependency in your manifest.cs file

**Comment by rllxxx** [comment]
> Add a dependency in your manifest.cs file

Thanks a lot, it works

![image](https://user-images.githubusercontent.com/13895891/201837111-4184711c-f248-49bc-85c9-e3aae0e29744.png)

**Comment by rllxxx** [comment]
> Add a dependency in your manifest.cs file

However，I can not understand, why  the `ContentType-TitlePart.cshtml` can be overwritten successfully in my module? (no dependencies in manifest)

**Comment by ns8482e** [comment]
> > Add a dependency in your manifest.cs file
> 
> However，I can not understand, why the `ContentType-TitlePart.cshtml` can be overwritten successfully in my module? (no dependencies in manifest)

Alternates are bound from currently active theme’s shape table, all modules contribute to shape table, here you are not overriding any shape

TitlePart_Edit is base shape type it’s not an alternate so it’s only bound from original module or its dependency can override

**Comment by rllxxx** [comment]
> 
okey, I see.  thks.

**Comment by rllxxx** [comment]
> > > Add a dependency in your manifest.cs file
> > 
> > 
> > However，I can not understand, why the `ContentType-TitlePart.cshtml` can be overwritten successfully in my module? (no dependencies in manifest)
> 
> Alternates are bound from currently active theme’s shape table, all modules contribute to shape table, here you are not overriding any shape
> 
> TitlePart_Edit is base shape type it’s not an alternate so it’s only bound from original module or its dependency can override

okey, I see. thks.

**Comment by jtkech** [comment]
For info and from memory, a Theme has an implicit dependency on all modules so that it can override any shape alternates. For a module you may need a manifest dependency as we did OR provide a more specialized alternate, as you did with `ContentType-TitlePart.Edit.cshtml`, I think this is why it was working without adding a dependency if this alternate is not already defined in another place.

**Comment by rllxxx** [comment]
> For info and from memory, a Theme has an implicit dependency on all modules so that it can override any shape alternates. For a module you may need a manifest dependency as we did OR provide a more specialized alternate, as you did with `ContentType-TitlePart.Edit.cshtml`, I think this is why it was working without adding a dependency if this alternate is not already defined in another place.

!!!, okey, ![image](https://user-images.githubusercontent.com/13895891/201842239-6361f5c7-8120-44d8-95ce-ce9745be18bd.png)
