### ISSUE TITLE
Move Redis Connection pooling to be cross-tenant

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#12822]
We have noticed that the number of Redis connections scales with the number of tenants.  This leads to a large number of Redis connections being required when you have a large number of loaded tenants even if individual tenants may not have a lot of actual activity.  The problem is that when you use something like Azure Redis you will quickly run into cost issues to allow for enough connections to exist even though Redis is barely being used (CPU/memory usage is very low).  

If we were able to share the Redis connection pool across all tenants then scaling would be correlated with actual usage of the system as opposed to tenant count.

**Comment by sebastienros** [comment]
Could be a host service.

**Comment by ShaneCourtrille** [comment]
@sebastienros Isn't the problem that Redis is registered at the Tenant level?  If this was done at the Host level instead I ?think? it would be available to the DistributedCache at the Tenant level?

**Comment by sebastienros** [comment]
@ShaneCourtrille this is what I meant with my comment.

**Comment by ShaneCourtrille** [comment]
@sebastienros so.. we just made Connection and Database static in the RedisService which has cut our connection count in half.  Creating a new Connection & Database is already controlled via a semaphore in this class so it SEEMS like this is safe.. but I don't know.  It feels weird that it could be so simple though so I wanted to see if you could identify any reason this is a dangerous idea.  

One thing to mention is that our RedisOptions do not differ per Tenant so there is no need for us to have a different connection per distinct RedisConfig.

**Comment by sebastienros** [comment]
I think it's ok as long as your connection is the same, but it can't be a long term solution.
I don't know if SE.Redis is keeping an internal connection pool based on connection string (like HttClient or database clients are doing). If that's the case then there might be a bug there if your change fixes the issue.
If that's not the case then we should create a pool in OC and have it return a connection per connection string. Could you investigate? At least the first part of my question.

**Comment by sebastienros** [comment]
I have read the ConnectionMultiplexer code and how we use it and I think we should have a pool in OC. It can be an internal class that is used by RedisService to build a `ConnectionMultiplexer` instance per connection string (or ConfigurationOption identity). This way you should end-up with a single instance even if each tenant has a different instance prefix.

Then the semaphore usage can be move in this pool. Do you feel like trying to create a PR? It should not be very hard, maybe count the number of leases though to be able to call Dispose when all instances are returned (which it theory should not happen). We can also summon @jtkech if you think it's too hard (not sure how busy he's though, I don't want to talk for him).

**Comment by jtkech** [comment]
@sebastienros

No problem to help @ShaneCourtrille on this one when I have time.

@ShaneCourtrille Just ping me again to remind me when you need help.

**Comment by ShaneCourtrille** [comment]
@jtkech, @sebastienros So interestingly enough we made our simplified version of this change and it decreased connections by 50% and that number has been consistent in two different environments.  Now that is a great improvement but I expected more AND it's strange how consistent it's been so far.  We're going to get it into another few environments to see perform some additional automated/manual testing so will update with more info then.

**Comment by jtkech** [comment]
Cool, good to know!

I don't know how you did it because we use the aspnetcore `RedisCache`that connects itself. But now the `RedisCacheOptions` has a `ConnectionMultiplexerFactory` property that we can setup to share a connection, as we already can for data protection but in a non async way.

So I did a PR #13531 where we register at the host level a `IRedisConnectionFactory` that the `RedisService` uses, and that we also use to setup the `RedisCacheOptions.ConnectionMultiplexerFactory`.  So in this PR all services, including the aspnetcore `RedisCache`, also use the same connection.

For now in this PR I didn't implemented a connection pool, we assume that all tenants use the same config to connect, the difference being still done by prefixing the keys according to the tenant names.

So if you could try #13531 if you have time.

**Comment by ShaneCourtrille** [comment]
@jtkech Just wanted to update you on this.. we have deployed it to production and the difference is huge as we've gone from 8K+ to ~20 on average.  Thanks so much for this fix!

**Comment by jtkech** [comment]
You're welcome
