### ISSUE TITLE
Double database connexion validation in SetupService

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#12825]
It seems to me that there is a double database connexion validation in SetupService.

There is the `IDbConnectionValidator.ValidateAsync` method
https://github.com/OrchardCMS/OrchardCore/blob/2b1771f467fa1fff124acd8f8bc95392b16583f5/src/OrchardCore/OrchardCore.Setup.Core/SetupService.cs#L170-L184

And also this piece of code :
https://github.com/OrchardCMS/OrchardCore/blob/2b1771f467fa1fff124acd8f8bc95392b16583f5/src/OrchardCore/OrchardCore.Setup.Core/SetupService.cs#L201-L223

Isn't this the same verification ?

The idea behind is to remove the dependency over YesSql.

**Comment by Skrypt** [comment]
I think one will throw an exception instead of just testing if it actually works before moving forward.

**Comment by TFleury** [comment]
They both add an error and return.

**Comment by Skrypt** [comment]
True, sorry I've read that code too quickly. Then we need to move the validations all in one place. I believe that the issue is that our DBConnectionValidator will not test if the Store was properly instantiated. This is why it is doing GetRequiredService.
