### ISSUE TITLE
NullReferenceException on RuleService.EvaluateAsync after migrate from 1.0.0-rc2-15475 to 1.2.2

### ISSUE THREAD

**Issue by sivakumar715** [OrchardCMS/OrchardCore#12833]
### To Reproduce
1. Migrate all the orchardcore packages used in site from `1.0.0-rc2-15475` to `1.2.2`
2. Fix the compile time errors if any
3. Build & Run the solution and throws  _InvalidOperationException_ on `Session` object at next middleware (eg., await next();). Below is the screenshot from quick watch.
![image](https://user-images.githubusercontent.com/54092242/202443944-d2d3ab1e-40cf-432e-a664-113e140ca4ab.png)

5. Fixed above session error by adding below code in startup and now session as well configured. 
**ConfigureServices:**
services.AddSession();
services.AddDistributedMemoryCache();

**Configure:**
app.UseSession();

![image](https://user-images.githubusercontent.com/54092242/202445213-1e7c61cb-7640-418f-8b5c-c892d89e10ea.png)

6. Build & Run the solution , again exception throws at next middleware. But, there is no exception details on `Microsoft.AspNetCore.Http.DefaultHttpContext` object and below error displayed on the screen.
![image](https://user-images.githubusercontent.com/54092242/202442014-e5fc78dc-ba83-4096-80d3-791064306c74.png)

### Expected behavior
Website should launch homepage without any error

@sebastienros - please suggest us if you aware of this issue.

**Comment by sebastienros** [comment]
Please upgrade to 1.3, then 1.4 then 1.5.

**Comment by sivakumar715** [comment]
hi @sebastienros - Thanks for quick response.

Migrated to 1.5 but still facing the above issue.

**Comment by Skrypt** [comment]
Go to the admin and remove or update any rules that are set on Layers. This should fix the issue.

**Comment by sebastienros** [comment]
Can you debug and see what is using the Session?

Also is it possible that it's coming from `PA.Com.Core.Autoroute.RoutePopulationMiddleware`? I see it in the stack right before the exception.

**Comment by Ramemis** [comment]
We are also facing this issue any update on this?

**Comment by sebastienros** [comment]
@Ramemis have you tried this?

> Go to the admin and remove or update any rules that are set on Layers. This should fix the issue.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
