### ISSUE TITLE
Default Orchard module project has "type could not be found" errors

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#12844]
### Describe the bug
When creating a default Orchard module project using "dotnet new" there are "type could not be found" errors.

### To Reproduce
1. Get Orchard 1.5.0
2. Ensure have latest Orchard 1.5.0 project templates
3. Create a new module project using: dotnet new ocmodulecms -n "TestModule"
4. Open the project in Visual Studio
5. Open the Startup.cs file and see red underline errors for IServiceCollection, IApplicationBuilder, and IEndpointRouteBuilder
6. Right click the project and select "Build"
7. See same errors:

The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'IApplicationBuilder' could not be found (are you missing a using directive or an assembly reference?)
The type or namespace name 'IEndpointRouteBuilder' could not be found (are you missing a using directive or an assembly reference?)

### Expected behavior
The Startup.cs file has no errors and the project builds.

### Notes
Could this be related to implicit usings being enabled in the project file?

### Workaround
Add these usings:
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

**Comment by Skrypt** [comment]
Pull Request as a reference: https://github.com/OrchardCMS/OrchardCore/pull/10762

**Comment by MikeAlhayek** [comment]
@fuzl-llc is this still an issue even after PR #10762 was merged?

**Comment by sebastienros** [comment]
Verified locally that this issue is fixed for the next version.
