### ISSUE TITLE
Make Some Controller Rewriteable

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#12846]
Just like AccountController , we should abstract some methods to extract the interface to make it easier to replace
At present, if I want to modify some login codes, I have to load the entire UserModule into my project, which will cause trouble for subsequent code updates

**Comment by sebastienros** [comment]
Have you checked if there isn't a way in aspnet to register different controllers dynamically? The current controllers are provided by Application Parts, Orchard has a custom implementation to load them from modules, so there might be a way already to replace existing ones.

**Comment by hyzx86** [comment]
related https://github.com/OrchardCMS/OrchardCore/issues/11644#issuecomment-1399438340

**Comment by hyzx86** [comment]
Sorry, I tried many ways but couldn't rewrite the controller. Maybe I'm not looking the right way,
Can you provide some examples?

**Comment by hishamco** [comment]
@hyzx86 could you please clarify what are you trying to do in details to check if I can help

**Comment by hyzx86** [comment]
First time , I tried to replace `Aaction` with this way
``` C# 
    public class ActionReplaceServiceProvider : IActionInvokerProvider
    {
        private readonly ActionReplaceOption _replaceOptions;

        public ActionReplaceServiceProvider(IOptions<ActionReplaceOption> replaceOptions)
        {
            _replaceOptions = replaceOptions.Value;
        }

        public int Order => 10;

        public void OnProvidersExecuted(ActionInvokerProviderContext context)
        {

        }

        public void OnProvidersExecuting(ActionInvokerProviderContext context)
        {
            var actionDescriptor = context.ActionContext.ActionDescriptor as ControllerActionDescriptor;
            var replaceConfg = _replaceOptions.FindOption(actionDescriptor.MethodInfo);
            if (replaceConfg != null)
            {
// change action methodinfo
                actionDescriptor.MethodInfo = replaceConfg.ActionMapping[actionDescriptor.MethodInfo.Name];
                actionDescriptor.ControllerTypeInfo = replaceConfg.NewController.GetTypeInfo();
            }
        }
    }
```

Then I considered using Filter as an alternative, but it didn't feel like it would work because it would require a lot of work to initialize the object and find the corresponding view

Finally, a possible approach is to use the UrlRewrite function to rewrite a known request path to another path



As for the suggestion that @sebastienros mentioned, I just had a quick look and I don't know where to start

> The current controllers are provided by Application Parts, Orchard has a custom implementation to load them from modules, so there might be a way already to replace existing ones.

**Comment by hishamco** [comment]
@hyzx86 could you please ping me on Gitter, I need to discuss two issues with you, this one and the Chinese one ;)

**Comment by hyzx86** [comment]
Sure, I've already ping you. Did you get the message?

**Comment by hishamco** [comment]
Yep

**Comment by hishamco** [comment]
After 30 minutes of chatting because each one of me & @hyzx86 don't understand the other language ;) Arabic VS. Chinese I realize that @hyzx86 needs to overwrite some of the functionalities on `AccountController`, so my suggestion we can introduce a services if the functionality could be overridden and make sense, otherwise replace the `OC.Users` modules might be a better options for him

There's another option that you can override the action with changing the its order, @MikeAlhayek I think you told me about something similar on the past,  am I right? or is it only related to Swagger API

**Comment by hyzx86** [comment]
sorry, I must study English hard.😥

**Comment by hishamco** [comment]
No problem, even I I'm not English native ;)

**Comment by MikeAlhayek** [comment]
@hyzx86 we should teach @hishamco Chinese instead :)

@hyzx86 Maybe you want to explain why you want to do this? Are you trying to change the UI?

**Comment by hyzx86** [comment]
Yes, I think there are some key interaction logic that has a strong dependency on MVC, and we should extract these interaction logic as interfaces

just like 

user module
openid module

**Comment by MikeAlhayek** [comment]
Controllers can be extended by firing events "in which we have." If you want to create your own logic in the controller, then you should define your own custom route and direct the user to your new route. If you have a specific need, I suggest that you explain exactly what you want to achieve and we'll share thoughts for your problem.

**Comment by hyzx86** [comment]
Beginning, I just want to extend the user login handler: ` IExternalLoginEventHandler `

But since it's called in the controller
So I want to be able to override this controller method

I submitted a PR that didn't pass for a long time : https://github.com/OrchardCMS/OrchardCore/pull/12845
Eventually I override the `IExternalLoginEventHandler` in my solution let it directly in the script update user information

``` C#
        public async Task UpdateRoles(UpdateRolesContext context)
        {
            var loginSettings = (await _siteService.GetSiteSettingsAsync()).As<LoginSettings>();
            //build new UpdateUserContext instance ,for update user properties
            var updateUserContext = new UpdateUserContext(context.User, context.LoginProvider, context.ExternalClaims, context.UserRoles);
            if (loginSettings.UseScriptToSyncRoles)
            {
                var script = $"js: function syncRoles(context) {{\n{loginSettings.SyncRolesScript}\n}}\nvar context={JsonConvert.SerializeObject(context, _jsonSettings)};\nsyncRoles(context);\nreturn context;";
                dynamic evaluationResult = _scriptingManager.Evaluate(script, null, null, null);
                context.RolesToAdd.AddRange((evaluationResult.rolesToAdd as object[]).Select(i => i.ToString()));
                context.RolesToRemove.AddRange((evaluationResult.rolesToRemove as object[]).Select(i => i.ToString()));
                if (evaluationResult.propertiesToUpdate != null)
                {
                    (context.User as User).Properties.Merge(evaluationResult.propertiesToUpdate);
                    await _userManager.UpdateAsync(context.User);
                }

            }
        }
```

It works, but may update the user information twice
Two audit logs are generated

So to avoid this, I want to be able to override the controller methods directly

**Comment by hyzx86** [comment]
> Isn't there a way in MVC to replace a controller by another one (see Application Parts).

Sorry, I didn't understand the `Application Parts` mentioned here 😭
What does it mean? Can you be more specific? Thanks!

**Comment by hyzx86** [comment]
@sebastienros  Do you mean the `OrchardCore.Mvc.Core` module?

https://github.com/OrchardCMS/OrchardCore/blob/f8b8ef358d0c7a3db572dd227fd4aee4bf9dc5e4/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L50-L68

**Comment by hyzx86** [comment]
@sebastienros , Perfect! it works, Thanks a lot!

this is my testing code , for those who need it

```C#
    [RequireFeatures("OrchardCore.Users")]
    public class RoutingReplace : StartupBase
    {

        public override void Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
        {
            var ocAccountControllerType = typeof(AccountController);
            var descriptors = serviceProvider.GetRequiredService<IActionDescriptorCollectionProvider>()
                .ActionDescriptors.Items
                .OfType<ControllerActionDescriptor>()
                .Where(x => x.ControllerTypeInfo.FullName == ocAccountControllerType.FullName
                    && x.ControllerName == "Account" && x.ActionName == "Login")
                .ToArray()
                ;

            Console.WriteLine("total:{0}", descriptors.Length);//2
            foreach (var descriptor in descriptors)
            {
                var type = typeof(EocAccountController);
                descriptor.ControllerTypeInfo = type.GetTypeInfo();
                descriptor.MethodInfo = type.GetMethod(nameof(EocAccountController.Login));
            }

            routes.MapRazorPages();
        }
    }
```

![image](https://user-images.githubusercontent.com/15613121/215149357-f6534442-91ce-471f-8df7-13b77bc6efb9.png)

**Comment by hyzx86** [comment]
I released a custom module to solve this problem 

https://www.nuget.org/packages/EasyOC.ReplaceAction
