### ISSUE TITLE
Progressive Web App support

### ISSUE THREAD

**Issue by VaclavElias** [OrchardCMS/OrchardCore#1285]
Maybe this might be also possible to add

https://madskristensen.net/blog/progressive-web-apps-made-easy-with-aspnet-core/

Follow up of #1250

**Comment by Piedone** [comment]
This should work with OC without anything special. Do you think something in OC is needed?

**Comment by VaclavElias** [comment]
Ohh, this is like 7 years old 🤣. I don't know the answer but many things must have been changed so you might be right. Please, feel free to close this issue.

**Comment by Piedone** [comment]
Thank you :):
