### ISSUE TITLE
Allow registering multiple redirect_uri/post_logout_redirect_uri

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#1287]
Thanks to https://github.com/OrchardCMS/OrchardCore/pull/1286, the revamped OpenID stores will now support storing multiple `redirect_uri`/`post_logout_redirect_uri` in the database. We may want to update the admin controller/views to allow entering more than one address.

/cc @jersiovic

**Comment by PinpointTownes** [comment]
@sebastienros what's the "recommended" option for multi-valued inputs in the Orchard world? A textarea backed by a `string` property + some splitting or multiple textboxes created via JS?

**Comment by sebastienros** [comment]
Both are fine. I have done both so far in different screens. You can do a text area to have something done quickly. And from JS, I have used VueJs for instance in the media management UI.
