### ISSUE TITLE
Consider overriding the default caching policy for the OpenID Connect discovery documents

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#1289]
When enabling the caching module, the OpenID Connect discovery documents are returned with a max-age of 60 seconds and cached server-side so OpenIddict doesn't have to handle the discovery requests every time.

We may want to go further and opt for a longer duration: a 30 mn or 1h policy might be reasonable.

/cc @sebastienros as I believe you wrote the response caching module.

**Comment by sebastienros** [comment]
I think it's a bug and this should only cache text/html results. Not API calls.
Or we need a better module that could be configured to distinguish them.

**Comment by PinpointTownes** [comment]
lol, good to know it was not intended... :trollface: 

Anyway, adding a 30min caching policy to the OpenID module shouldn't be too complicated. Lemme know if you like the idea.

**Comment by kevinchalet** [comment]
Looks like there wasn't much interest for this feature. Closing.
