### ISSUE TITLE
Error connecting to SQL server

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/OrchardCore#12903]
In Orchard core version 1.5, connection to SQL Server is not established! While this problem does not exist in version 1.4

**Comment by agriffard** [comment]
Does it come from the expected encryption parameter in the connectionstring? :
https://docs.orchardcore.net/en/latest/docs/releases/1.5.0/#yessql-breaking-changes

**Comment by asemandeveloper** [comment]
> Does it come from the expected encryption parameter in the connectionstring? : https://docs.orchardcore.net/en/latest/docs/releases/1.5.0/#yessql-breaking-changes

My connection string is like this

Server=mypc;Database=Orchard;Persist Security Info=True;Integrated Security=True;

**Comment by TFleury** [comment]
If you have to change it to :
```Server=mypc;Database=Orchard;Persist Security Info=True;Integrated Security=True;TrustServerCertificate=true```

**Comment by hishamco** [comment]
As @agriffard said that the connection has been encrypted. @asemandeveloper please change your connectionString to what @TFleury is mentioned above
