### ISSUE TITLE
Query content part

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1291]
Enable displaying a list of items by adding a Query content part.

After the part is added to a type, the user can pick from a list of queries from a select list. The results from the query will be displayed on the front end.

This might be crossing into `Lists` territory here, so we may want to consider updating the ListPart to take the list items from a provider?

**Comment by sebastienros** [comment]
That a Projection Part, which takes a Query, a list of parameters (json for simplicity) and a Display type.
It could also support an optional pager. Like in O1.

**Comment by xperiandri** [comment]
Is it about page display or admin theme part editors?

**Comment by sebastienros** [comment]
It should be about front end at first. 

For the admin, the Content Tree feature should be extensible enough to support this too.

**Comment by agriffard** [comment]
We can use a LiquidPart to call a query and render the results.
