### ISSUE TITLE
The ListPart navigation is showing up over the Admin menu on mobile device

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12949]
### Describe the bug
The ListPart had enhancement in v1.5 where we added a Navigation bar over for the container and it's contained items. The navigation has a z-index value of 1001 while the action-bar has a z-index of 1000.  the navigation bar should have a higher z-index than the action-bar to make sure any menu from the ListNaviation to show up over the action-bar. 

### Expected behavior
I expect the admin menu to show up correctly on the top when it is open.

### Screenshots
![image](https://user-images.githubusercontent.com/24724371/207455044-72549699-f643-4ac1-b602-2d0e04a52d3c.png)

**Comment by hyzx86** [comment]
In this case, we should just be changing the Menu that pops up, so why raise the z-index of the entire menu area?



![image](https://user-images.githubusercontent.com/15613121/234184005-37f7dbeb-e14d-4e0d-8c62-d5fe6e40dbd6.png)

**Comment by MikeAlhayek** [comment]
I am not sure what I am looking at here. Is this a custom part that is appearing behind the menu?

**Comment by hyzx86** [comment]
😭 I don't think we should adjust the z-index of the entire menu

Seems unnecessary


I introduced a third-party low-code UI, but it was always obscured by the menu

If it really can not ~ I can only open all on the right side

https://aisuda.bce.baidu.com/amis/zh-CN/components/drawer#%E6%8C%87%E5%AE%9A%E5%BC%B9%E5%87%BA%E6%96%B9%E5%90%91

**Comment by hyzx86** [comment]
Once the z-index is over 1030 my side drawer component is occluded ~

https://user-images.githubusercontent.com/15613121/234316413-2c3e853c-16f1-46d1-9a43-a7901ade780f.mp4

I'll try to override the styles in my component first
