### ISSUE TITLE
Localization .po file locations error

### ISSUE THREAD

**Issue by yiji** [OrchardCMS/OrchardCore#1294]
Localization Module README.md

PO files locations

PO files are found with the following steps:

    For each module and theme all files matching [ModuleLocation]/App_Data/Localization/[CultureName]/OrchardCore.po
    Then all files matching /App_Data/Localization/[CultureName]/OrchardCore.po
    For each tenant all files matching /App_Data/Sites/[TenantName]/Localization/[CultureName]/OrchardCore.po

Right:
Packages/[ModuleName]/Localization/[CultureName]/OrchardCore.po
Localization/[CultureName]/OrchardCore.po

**Comment by jtkech** [comment]
Yes, thanks.

In `ModularPoFileLocationProvider.cs` line 43, for the global location i think we would need to use `shellOptions.Value.ShellsApplicationDataPath` in place of `_root`.

Need to leave, i will do a PR tomorrow if not already done by @sebastienros.
