### ISSUE TITLE
Perf regression

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#12961]
From https://github.com/OrchardCMS/OrchardCore/pull/12588

Working set is doubled, reproduced on different machines

![image](https://user-images.githubusercontent.com/1165805/208320371-4347f878-ac4a-44f4-a4ca-7bee62ef2cc9.png)

**Comment by sebastienros** [comment]
The fallacy of max values. During the whole run the max working set is hit on startup and goes down quickly to its steady state:

![image](https://user-images.githubusercontent.com/1165805/208320779-965596bb-77a7-4a78-9457-181c6fa49281.png)

**Comment by lahma** [comment]
You gave me a startle there 😉
