### ISSUE TITLE
TypeLoadException: Method 'GetAggregateOrders' in type 'YesSql.Provider.Sqlite.SqliteDialect' from assembly 'YesSql.Provider.Sqlite

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12973]
### Describe the bug
When running the main branch locally I am getting the following error

> TypeLoadException: Method 'GetAggregateOrders' in type 'YesSql.Provider.Sqlite.SqliteDialect' from assembly 'YesSql.Provider.Sqlite, Version=0.0.0.0, Culture=neutral, PublicKeyToken=51cdb8c1938e4789' does not have an implementation.

This happened after PR #12959 was merged.

**Comment by sebastienros** [comment]
Probably old dll that was loaded.
