### ISSUE TITLE
Add settings for GraphQL to exclude content types from being exposed

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#12982]
### Is your feature request related to a problem? Please describe.
Today, GraphQL expose all content types to the user. A permission check is applied to filter out content types user can't view. There is no way to control which content-types should be exposed to the API. Not everyone want to expose every content types. For example, if I have a `SitePage` content type that I want everyone to be able to view it, but I do not want anyone to query it from the API.

### Describe the solution you'd like
We can simply add a content type settings to `Hide` the content type like we do today for the content parts.

**Comment by sebastienros** [comment]
OK with it being a content type setting

**Comment by MikeAlhayek** [comment]
@sebastienros PR https://github.com/OrchardCMS/OrchardCore/issues/12982 was added for this
