### ISSUE TITLE
AutoroutePartSettings not compiling

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#13006]
I used this code from the documentation:

```
_contentDefinitionManager.AlterTypeDefinition("Product", type => type
    .WithPart("AutoroutePart", part => part
        // sets the position among other parts
        .WithPosition("2")
        // sets all the settings on the AutoroutePart
        .WithSettings(new AutoroutePartSettings { Pattern = "{{ ContentItem | display_text | slugify }}" })
    )
);
```
The "new AutoroutePartSettings" does not compile and I have the Autoroute nuget package installed.

Is the documentation up to date?

**Comment by MikeAlhayek** [comment]
Make sure a valid `OrchardCore.Autoroute` package is installed. And be sure to add `using OrchardCore.Autoroute.Models;`

This is a local issue not an bug.

**Comment by JoshTango** [comment]
Thanks. I uninsalled and reinstalled all Autoroute packages and it works now and I added the model reference.
