### ISSUE TITLE
Need better documentation regarding Resources

### ISSUE THREAD

**Issue by websitewill** [OrchardCMS/OrchardCore#1300]
While trying to figure out how to inject scripts at the document foot, from a partial view, I found a lack of documentation relating to this subject, as well as some typos and lack of clarity on the page dedicated to resources: http://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Resources/README/

Could use more discussion and pointers to where these things are used in the themes/modules provided in the repository.

**Comment by sebastienros** [comment]
- Document how to inject resources (api, tag helpers and liquid tags)
- Example to register a script is wrong, it accepts an `IHtmlContent`

**Comment by sebastienros** [comment]
@websitewill we closed the issue base on @agriffard 's PR. However if you still have questions about this feature that are not answer, please reopen one with more details about what you don't understand, and the kind of examples you would like to see.
