### ISSUE TITLE
Trouble to understand the admin section

### ISSUE THREAD

**Issue by surfmuggle** [OrchardCMS/OrchardCore#1302]
While trying to getting to know orchardCore (no prior orchard experience) it was / still is not easy for me 

 - to understand the admin sections,  
 - and how to place content items or menu items  onto the start page

I assume that each content item is of a certain content type. 
I defined a type with a few properties (title, markdown editor, and so on) and created some content items. 
Currently my admin section contains these content items and types (see also screenshots below)

```
New
        ContentTypeOne v4
        Menu
Content 
        Content Items 
                  Manage Content
                                 ContentTypeOne v4 (meaning Content Item 1 of ContentType A)
                                 First Menu Title (Content Item 2 of ContentType ?)
                                 Welcome (Content Item 3 of ContentType ?)
                                 ContentTypeOne v4 (meaning Content Item 4 of ContentType A)
Content Definition
        Content Types 
                  ContentType A  (Display Name: ContentTypeOne v4)
                  ContentType B  (Display Name: Link Menu Item; Stereotype: _MenuItem_) 
                  ContentType C  (Display Name: Menu)

```                                 

 - It is confusing that in my case the content items 1 and 4 both have the same name _"ContentTypeOne v4"_
 - How can i change the name for a content item?
 - My start page http://localhost:2918/# is still empty - what do i have to do to add a page or a content item or a menu link to the start page?
 - Is there a user / content editor documentation that explains theses things?

## Screenshots below

The screenshot below show the types and content items i created. 
![orchard_contentitems_manage_content](https://user-images.githubusercontent.com/1271555/34132699-61ecf1d2-e451-11e7-91b1-1444d990b12f.png)

![orchard_content_types](https://user-images.githubusercontent.com/1271555/34133159-83a96a92-e453-11e7-8893-7a7dfc2d1258.png)

**Comment by sfmskywalker** [comment]
A quick short note for now: ensure you have the TitlePart attaches to your content type.
