### ISSUE TITLE
BagPart programatically added to a ContentType does not take ContainedContentTypes into account

### ISSUE THREAD

**Issue by ldimitrijevic** [OrchardCMS/OrchardCore#13033]
### Describe the bug
I want to create a carousel type. Therefore i created a module where i register a new ContentType in the migrations file. The carousel is composed a bagpart which should filter the parts that can be used with the carousel. For now i've only created a TestimonialCardPart. 

Migration.cs

```
_contentDefinitionManager.AlterTypeDefinition("Carousel", type => type
            .Creatable()
            .Listable()
            .WithPart(nameof(BagPart), part => part
                .WithDisplayName("Carousel items")
                .WithSettings<BagPartSettings>(new BagPartSettings
                {
                    ContainedContentTypes = new[] { nameof(TestimonialCardPart) }
                })
            )
         );
```
In the database i have the definition configured well:

```
"Name": "Carousel",

"DisplayName": "Carousel",
    "Settings": {
        "ContentTypeSettings": {
            "Creatable": true,
            "Listable": true
        }
    },
    "ContentTypePartDefinitionRecords": [{
            "PartName": "BagPart",
            "Name": "BagPart",
            "Settings": {
                "ContentTypePartSettings": {
                    "DisplayName": "Carousel items",
                    "Description": "Provides a collection behavior for your content item where you can place other content items."
                },
                "BagPartSettings": {
                    "ContainedContentTypes": ["TestimonialCardPart"],
                    "ContainedStereotypes": []
                }
            }
        }
    ]

```
But in the admin, the TestimonialCard checkbox is not checked, and I cannot add a card when adding a carousel.
Clicking the checkbox in the admin makes it work nicely.

### To Reproduce
1. Create a type by code and add it a bagpart
2. Add a ContainedContentTypes via the BagPartSettings
3. Deploy the module
4. The part is not checked in the admin.

### Expected behavior
The checkbox should be checked and the carousel type should be configured when the module is activated

**Comment by MikeAlhayek** [comment]
The line expects an array of content type not name of parts.
```
                    ContainedContentTypes = new[] { nameof(TestimonialCardPart) }
```

Assuming `TestimonialCardPart` already defined, you may need to change your migration to look something like this instead

```
_contentDefinitionManager.AlterTypeDefinition("CarouselItem", type => type
    .WithPart('TestimonialCardPart')
 );

_contentDefinitionManager.AlterTypeDefinition("Carousel", type => type
    .Creatable()
    .Listable()
    .WithPart(nameof(BagPart), part => part
        .WithDisplayName("Carousel items")
        .WithSettings<BagPartSettings>(new BagPartSettings
        {
            ContainedContentTypes = new[] { "CarouselItem" }
        })
    )
 );
```

**Comment by ldimitrijevic** [comment]
Hello,

thanks for the reply. Of course ! It says ContentTypes not ContentParts !! 

Thanks a lot.

**Comment by MikeAlhayek** [comment]
Think of a content type as a class that you can instantiate. Content item would be an instance of the class. Content part think of it as a property on the class.

**Comment by Skrypt** [comment]
Content Type Field would be a property but Content Part would be more like a Dictionary of internal parts that can mutate the Content Type itself.
