### ISSUE TITLE
Add user friendly title to background tasks instead of showing the technical name

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13045]
### Is your feature request related to a problem? Please describe.
Currently, a background name/technical name is the full name of the `C#` class. This is not a user friendly name for a UI. I think the long Technical Name (aka task Id) should not be visible to the UI. I mean why should the user care about the technical name of the background task.

### Describe the solution you'd like
Add a user friendly title to every background tasks. We can continue to use the current "name" in the URL and to locate the task.

**Comment by hyzx86** [comment]
That's a great idea. There are also instance  name of workflow. They should be able to generate name according to rules like TitlePart.
