### ISSUE TITLE
Use ListContent permission in the Content list action instead of ViewContent

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13053]
### Describe the bug
Currently, we use `ViewContent` as a min permission to list the contents in the content items UI. We use the same permission to also show the "Content >> Content Items" admin menu. IMO, `List Content` permission should be used not `View Content`. What if someone wants to allow a user to view content using direct link, but does not want them to list the contents in the UI? Currently, this isn't possible.

Additionally, `ViewContent` is granted to all `Anonymous` and `Authenticated` roles which is fine. But, I think access to list contents should by granted by the `ListContent` permission to avoid allowing listing content without explicit permission grant.

Side note: a thought that came to mind, maybe `ViewContent` should also be implied by `ListContent` which isn't the case today. I think we can leave that as is just for added flexibility in case for some reason someone wants to allow listing contents but NOT viewing them which sounds weird at the moment. But, who knows all use cases. 

If I get agreement on this change, I'll submit a PR and document the change in the release notes.

**Comment by sebastienros** [comment]
Ok, using ListContent is better than ViewContent in the List method of Contents/AdminController
