### ISSUE TITLE
Using a media profile the quality parameter has no effect.

### ISSUE THREAD

**Issue by michaelschiller** [OrchardCMS/OrchardCore#13079]
When using the Liquid filter `resize_url` the quality parameter of a media profile will have no effect for jpg/webp.
Version affected: OrchardCore 1.5.0 with builtin ImageSharp.Web 2  

The issue can easily be fixed by moving the quality parameter behind format parameter.  

To fix the `resize_url` filter a change to the ordering of parameters in
`OrchardCore.Media.Services.MediaProfileService.GetMediaProfileCommands(string name)`  
may be required.

Please see https://github.com/michaelschiller/OcIcQualityParameter for a demo project.

**Comment by hishamco** [comment]
@michaelschiller could you please push a PR for it
