### ISSUE TITLE
The `CreateApiViewModel`'s `IsNewTenant` attribute always set to true

### ISSUE THREAD

**Issue by MZole** [OrchardCMS/OrchardCore#13085]
### Describe the bug

Before validating a `CreateApiViewModel` in the `OrchardCore.Tenants ApiController`, the model's `IsNewTenant` attribute is set to true in this [line](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Tenants/Controllers/ApiController.cs#L117). Since this is always set to true, it's impossible to get a Tenant's setup token after the first time the API call was sent, and the following model error is raised: `"A tenant with the same name already exists."` and [this code](https://github.com/OrchardCMS/OrchardCore/blob/e864d820cecbe5f5dac84cd35c4f866bd91e4931/src/OrchardCore.Modules/OrchardCore.Tenants/Services/TenantValidator.cs#L91) is never reached.

### Expected behavior
The `IsNewTenant` attribute shouldn't be set in the controller.

**Comment by hishamco** [comment]
We will check
