### ISSUE TITLE
Side nav floats above editor in fullscreen mode

### ISSUE THREAD

**Issue by daveblack101** [OrchardCMS/OrchardCore#13102]
### The side nav's z-index is higher than the fullscreen view editor.

I have checked Markdown and Trumbowyg and they are both affected.

### Screenshots
![image](https://user-images.githubusercontent.com/1476149/213013772-216bb5b6-77b4-416d-b887-d77eb5c8943c.png)

**Comment by hishamco** [comment]
Could you please submit a PR for this?

**Comment by daveblack101** [comment]
Sure. I'll submit one tomorrow.

**Comment by daveblack101** [comment]
One heckuva day! I might have to attend to this tomorrow 🙏

**Comment by daveblack101** [comment]
I was too late and it had been fixed by someone else

**Comment by Piedone** [comment]
Great then!
