### ISSUE TITLE
Page Title Shape is appending TitlePart

### ISSUE THREAD

**Issue by kgwadu** [OrchardCMS/OrchardCore#13103]
In my template i set the page title with the below:

```
{% assign pageTitle = "My Page Title" %}

<!-- Required to render Title tag in Head -->
<input type="hidden" value="{% page_title pageTitle %}" />
```

In my layout i render the title with the below:

```
<!-- Page Title Shape -->
<title>{{ "PageTitle" | shape_new | shape_stringify }}</title>
```

Now for some reason, on some of the templates the title is rendered like this:

`<title>My Page Title - My Title Part</title>`

On other templates its fine and renders like this (expected behaviour):

`<title>My Page Title</title>`

I cant figure out why but on some templates the TitlePart value is being appended to the Page Title Shape.

**Comment by Skrypt** [comment]
Works as intended. Take a look at your Layout.liquid page. These titles are incremental.

**Comment by kgwadu** [comment]
@Skrypt can you clarify? i was under the assumption that whatever value is set here is used for the title. Why would it randomly append the title tag for some templates and not otherwise. Can you perhaps provide some guidance on how i can stop this behaviour?

Im working on an urgent SEO update and this issue is currently blocking my progress.

```
<!-- Required to render Title tag in Head -->
<input type="hidden" value="{% page_title pageTitle %}" />
```

**Comment by Skrypt** [comment]
Refer yourself to documentation here: https://docs.orchardcore.net/en/main/docs/reference/modules/Liquid/#page_title
I can't help much more than that. These titles are incremental by design.

**Comment by kgwadu** [comment]
In case someone else comes across the same situation and is struggling to find a solution, the below is what ultimately fulfilled my requirements.

On your layout liquid file, use the below:
```
<!-- Page Title Shape -->
<title>{% render_section "PageTitle", required: false %}</title>
```

On your individual content type liquid templates, use the below:
```
{% assign pageTitle = "Only this should render in my title tag" %}

<!-- Required to render Title tag in Head -->
{% zone "PageTitle" %}{{ pageTitle | raw }}{% endzone %}
```
