### ISSUE TITLE
https://docs.orchardcore.net docs redirects to https://docs.orchardcore.net/en/latest/

### ISSUE THREAD

**Issue by Rick-Anderson** [OrchardCMS/OrchardCore#13114]
How do you open issues on the docs? Why does https://docs.orchardcore.net docs redirect to https://docs.orchardcore.net/en/latest/ ? When you remove the `en` culture, you get a 404.

https://github.com/dotnet/AspNetCore.Docs/pull/28136/files

I'd be happy to contribute to the doc's but I don't see how.

**Comment by hishamco** [comment]
Thanks @Rick-Anderson for reporting this, all the docs are in `src/docs` folder, but I don't think it's related. @agriffard could you please set the domain, so it can works without specifying the default culture
