### ISSUE TITLE
`Update()` endpoint for the Tenant's ApiController

### ISSUE THREAD

**Issue by MZole** [OrchardCMS/OrchardCore#13110]
### Is your feature request related to a problem? Please describe.
This is kind of related to #13085. Currently, there is no way to update tenant settings from API calls.

### Describe the solution you'd like
There could be an `Update()` endpoint in the Tenant's ApiController, which takes care of this and enable us to modify the tenant settings either if the tenant is uninitialized or running. The updateable properties should be the same as what is displayed on the tenant editor on the Admin UI.

**Comment by hishamco** [comment]
I planned to file this issue while I'm working on #13085, I will fix it then

**Comment by MZole** [comment]
Awesome, thanks!

**Comment by Piedone** [comment]
Would you like to work on this ASAP @hishamco?
