### ISSUE TITLE
The Audit Trail does not add new records to the database on the exception handler page.

### ISSUE THREAD

**Issue by vitaliy00000** [OrchardCMS/OrchardCore#13127]
### Describe the bug
I use Orchard Core as decoupled CMS. I am trying to use the Audit Trail to save the errors that occur. I can save the error if the code is wrapped in a try catch construction. But it doesn't work inside the exception handler page.The code works without exception, but the new record is not added to the database.

### To Reproduce
Exception handler page
`[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    private readonly IEnumerable<IErrorEvent> _errorEvent;
    private readonly ILogger _logger;

    public ErrorModel(
        IEnumerable<IErrorEvent> errorEvent,
        ILogger<ErrorModel> logger)
    {
        _errorEvent = errorEvent;
        _logger = logger;
    }

    public Task<IActionResult> OnGetAsync()
    {
        return LogPageErrorAsync();
    }

    public Task<IActionResult> OnPostAsync()
    {
        return LogPageErrorAsync();
    }

    private async Task<IActionResult> LogPageErrorAsync()
    {
        var context = HttpContext.Features.Get<IExceptionHandlerFeature>();
        if (context != null)
        {
            string path;
            if (context is ExceptionHandlerFeature exceptionHandlerFeature)
            {
                path = exceptionHandlerFeature.Path;
            }
            else
            {
                path = HttpContext?.Request?.Path;
            }

            var error = new PageErrorModel
            {
                Message = context.Error?.Message,
                InnerExceptionMessage = context.Error?.InnerException?.Message,
                StackTrace = context.Error?.StackTrace,
                Path = path
            };

            await _errorEvent.InvokeAsync((e) => e.LogPageErrorAsync(error), _logger);
        }

        return Page();
    }
}`

Custom event
`public interface IErrorEvent
{
    Task LogPageErrorAsync(PageErrorModel model);
}`

`public class AuditTrailErrorEventHandler : IErrorEvent
{

    private readonly IAuditTrailManager _auditTrailManager;

    public AuditTrailErrorEventHandler(
        IAuditTrailManager auditTrailManager)
    {
        _auditTrailManager = auditTrailManager;
    }

    public Task LogPageErrorAsync(PageErrorModel model)
    {
        return RecordEventAsync(model, AuditTrailErrorEventConfiguration.PageError);
    }

    private async Task RecordEventAsync(PageErrorModel model, string eventName)
    {
        await _auditTrailManager.RecordEventAsync(
                    new AuditTrailContext<AuditTrailErrorEvent>
                    (
                        name: eventName,
                        category: AuditTrailErrorEventConfiguration.Errors,
                        correlationId: string.Empty,
                        userId: string.Empty,
                        userName: string.Empty,
                        new AuditTrailErrorEvent
                        {
                            InnerExceptionMessage = model.InnerExceptionMessage,
                            Message = model.Message,
                            StackTrace = model.StackTrace,
                            Path = model.Path
                        }
                    ));
    }
}`

`public class AuditTrailErrorEventConfiguration : IConfigureOptions<AuditTrailOptions>
{
    public const string Errors = nameof(Errors);
    public const string PageError = nameof(PageError);

    public void Configure(AuditTrailOptions options)
    {
        options.For<AuditTrailErrorEventConfiguration>(Errors, S => S["Errors"])
            .WithEvent(PageError, S => S["Page Error"], S => S["An error occurred while creating the page"], true);
    }
}`

**Comment by Piedone** [comment]
Audit Trail is not really for logging errors. The ambient transaction of the request will be rolled back on an uncaught exceptio.
