### ISSUE TITLE
Hide a recipe documentation

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#13130]
In the documentation for recipes it says you can hide  recipe by settings isetuprecipe to false but it doesn't mention anything about tagging it with hidden.

Please add a note to say you can hide a recipe by tagging is with hidden like so:

`  "tags": [
    "hidden"
  ],`

**Comment by MikeAlhayek** [comment]
@JoshTango do you want to contribute to this project? You can submit a PR for this fair request.
