### ISSUE TITLE
Too many cookie chuncks cause a long request

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13142]
### Describe the bug
I have an app that is running on Azure Web App service. I have a site called `site3` and uses a subdomain like `site3.mydomain.com`. when a user logs in, they get a white page. When I look at the cookie that the request created, I notice 10 different chucks for one cookie. 

![image](https://user-images.githubusercontent.com/24724371/214620061-d7e5faac-35f1-4a43-b54e-97a76fadc547.png)

In other user 7 chunks were created and the site still works. I am guessing when 10+ chunks are created causes long request which is why the app does not respond. 

Here is an example of a user with 7 chunks, but the site works for him

![image](https://user-images.githubusercontent.com/24724371/214620606-a94eea8d-6334-4ce0-887c-1c6722af6e9c.png)

I am guessing this is due to too many claims for roles. Investigating…

**Comment by ns8482e** [comment]
Fixed here #12322 Enable feature Users Authentication Ticket Store

**Comment by MikeAlhayek** [comment]
@ns8482e thank you! Indeed enabling `Users Authentication Ticket Store` feature fixes this issue!

**Comment by Skrypt** [comment]
@ns8482e Is it documented?

**Comment by MikeAlhayek** [comment]
@Skrypt nope, this is just one of those hidden gems :) 

It should be documented
