### ISSUE TITLE
Create Dropdown link

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#1316]
How can we Create Dropdown link under Menu Items?

**Comment by agriffard** [comment]
Each menu element is draggable so you can move one below a parent by clicking, holding and moving on the right.

**Comment by lthoa** [comment]
Thank you, but I mean is Dropdown menu in Nav bar:

![dropdown-menu](https://user-images.githubusercontent.com/6874322/34380702-11cd3a72-eb36-11e7-9b8e-caa7f9957b47.png)

**Comment by agriffard** [comment]
Then, the theme that is used needs to handle the sub-menu elements correctly, which is not the case for the moment for TheBlogTheme.

**Comment by lthoa** [comment]
I know we need to change some in Template to handle the sub-menu:
`
 {% for menuItem in Model.ContentItem.Content.MenuItems.ContentItems %}        
          {% if menuItem.MenuItem.SubMenuItems == null %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{ menuItem.MenuItem.Link.Text }}">{{ menuItem.TitlePart.Title }}</a>          
          </li>
          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{{ menuItem.MenuItem.Link.Text }}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ menuItem.TitlePart.Title }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% for subMenuItem in menuItem.MenuItem.SubMenuItems %}
                  <a class="dropdown-item" href="{{ subMenuItem.MenuItem.Link.Text }}">{{ subMenuItem.TitlePart.Title }}</a>
              {% endfor %}            
            </div>
          </li>
          {% endif %}        
        {% endfor %}
`

But I don't know how to add a SubMenuItem field in to MenuItem Content Types as an list of MenuItem

**Comment by sebastienros** [comment]
If the theme doesn't support that, then we won't. It's a third party theme, we just replicate what it does. If we decided to extend it then it would be hard to maintain any changes that would be applied to it. We might have some other themes later on that will provide this feature.
