### ISSUE TITLE
Add widget UI problem

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#13161]
### Steps to reproduce the behavior:

-Open Orchard Admin
-Open Design->Desig->Settings->Zones
-Add multiple Zones
-Then Navigate to Design->Widgets
-Click Add Widget button

**Affected Versions
Orchard 1.5**

### Expected behavior
Another "Add Widget" button should not overlay a menu

## Screenshots
![image](https://user-images.githubusercontent.com/13991195/215159553-d147710d-06c1-47c1-8f31-e15b074c8add.png)

**Comment by hishamco** [comment]
It's z-index issue, thanks for reporting, @rserj are you plan to push a PR?

**Comment by hishamco** [comment]
It's z-index issue, thanks for reporting, @rserj are you plan to push a PR?

**Comment by MikeAlhayek** [comment]
This is a duplicate of https://github.com/OrchardCMS/OrchardCore/issues/11969
