### ISSUE TITLE
OrchardCore_Media_AmazonS3 - BasePath folder name issue with multi-tenant

### ISSUE THREAD

**Issue by kylgarmor** [OrchardCMS/OrchardCore#13177]
### Describe the bug
When configuring the Feature `OrchardCore_Media_AmazonS3` I have configured the `BasePath` value as below:  
```
"BasePath": "{{ ShellSettings.Name }}/Media",
```
My expectation was that for each Tenant, there would be a subfolder created for each Tenant with a unique name.  What is happening though is that the folder in the S3 bucket is actually being generated as below:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/63015960/215571718-6c3ec1ab-04af-4b7f-9be4-265269789a48.png">
The Liquid value is never being interpreted.  The files still get uploaded, but they all get dropped in that same incorrectly named (and shared) folder.

### Expected behavior
If I have 2 tenants named `Tenant01` and `Tenant02` I expect two subfolders be created off of the root of the site.  The Media for those tenant sites will be dropped in the relevant folder for the tenant.

### Possible solution
I made two changes locally to test a theory
- `OrchardCore\OrchardCore.FileSTorage.AmazonS3\AwsFileStorage.cs` : constructor is modified to use `IOptions<AwsStorageOptions> instead of just `AwsStorageOptions`
```
    public AwsFileStore(IClock clock, IOptions<AwsStorageOptions> options, IAmazonS3 amazonS3Client)
    {
        _options = options.Value;
```
- `OrchardCore.Modules\OrchardCore.Media.AmazonS3\Startup.cs : alter the initialization of the `AwsFileStore` as follows:  
```
                IOptions<AwsStorageOptions> options = serviceProvider.GetRequiredService<IOptions<AwsStorageOptions>>();
                var fileStore = new AwsFileStore(clock, options, amazonS3Client);
```

**Comment by kylgarmor** [comment]
On reflection this fix could be made to just the `OrchardCore.Modules\OrchardCore.Media.AmazonS3\Startup.cs` file : alter the initialization of the AwsFileStore` as follows:
```
                IOptions<AwsStorageOptions> options = serviceProvider.GetRequiredService<IOptions<AwsStorageOptions>>();
                var fileStore = new AwsFileStore(clock, options.Value, amazonS3Client);
```
Then the `AwsFileStorage` change becomes unnecessary

**Comment by jtkech** [comment]
Yes you are right, this is in `AwsStorageOptionsConfiguration` that the Liquid part is evaluated.

Can you suggest a Pull Request to fix it?

**Comment by kylgarmor** [comment]
This is a PR for the smaller scope fix   
https://github.com/OrchardCMS/OrchardCore/pull/13178
