### ISSUE TITLE
Setup page - Validation Summary needs some styling

### ISSUE THREAD

**Issue by muzzi-w** [OrchardCMS/OrchardCore#13215]
### Describe the bug
On the Setup page, the Validation Summary tag doesn't have any styling, so it's possible that you do not immediately see the displayed error message. 
A class does get rendered... _class="validation-summary-errors"_  but there' no matching css style. 
It would be good to clearly draw attention to the message which could be done by applying a Bootstrap 'alert' class or by creating a custom 'validation-summary-errors' style.
I've added a 'dismiss' button but maybe not necessary.   

Current...
`<div asp-validation-summary="ModelOnly" ></div>`

![setup-before](https://user-images.githubusercontent.com/12488547/217756870-25562427-be7f-4cb5-a4e9-e779e6a681af.jpg)

New...
```
<div asp-validation-summary="ModelOnly" class="alert alert-warning alert-dismissible fade show mt-2" role="alert">        
        <h5 class="alert-heading">Cannot create site. Please correct the following errors</h5> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
 </div>
```

![setup-after](https://user-images.githubusercontent.com/12488547/217756905-da099a64-803c-47dc-ab47-e8ff972e4c03.jpg)

**Comment by hishamco** [comment]
Please screenshot (before + after)

**Comment by sebastienros** [comment]
> but there' no matching css style.

Sounds like a bug, so maybe a PR too at the same time as the screenshot when the fix is applied?
