### ISSUE TITLE
OrchardCore.Media editors not working outside the Admin area

### ISSUE THREAD

**Issue by ericrrichards** [OrchardCMS/OrchardCore#13210]
### Describe the bug
For assorted reasons, we don't want most of our users in the Admin section of OrchardCore, but they need to be able to create some kinds of content.
I've created some non-admin controllers and views for the necessary operations following the pattern of the OrchardCore.Contents module
```csharp
    public async Task<IActionResult> Create(string id) {
        if (String.IsNullOrWhiteSpace(id) || id == "undefined") {
            return NotFound();
        }

        var contentItem = await CreateContentItemForOwnedByCurrentAsync(id);

        if (!await IsAuthorizedAsync(CommonPermissions.EditContent, contentItem)) {
            return Forbid();
        }

        var model = await _contentItemDisplayManager.BuildEditorAsync(contentItem, _updateModelAccessor.ModelUpdater, true);

        return View(model);
    }
```
With some CSS and JS to patch some differences between our user-facing and TheAdmin themes, this works well for most kinds of content.

I'm running into a problem with content types that have either a non-attached MediaField or which has one of the WYSIWYG markdown or html editors.  The Vue code inside of OrchardCore.Media's media.js initializeMediaApplication() method is breaking.  It appears to be something related to getting folder paths inside the Media Library, but I can't figure out what the piece I am missing here is.

Non-Admin editor UI:
![image](https://user-images.githubusercontent.com/2787661/217068661-ad3213e6-0da2-4ca6-bf76-9e42d07b99bb.png)
Try to add a media item, and the modal is blank
![image](https://user-images.githubusercontent.com/2787661/217068803-974b1f66-7a7a-4f08-bf6a-4fa7e00830f9.png)

Vue error in JS console:
![image](https://user-images.githubusercontent.com/2787661/217069135-9846cc04-aa5a-4002-8e88-e7ae23f377d5.png)

This would appear to be from OrchardCore.Media/Assets/js/MediaApp/app.js https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/MediaApp/app.js#:~:text=mounted%3A%20function,%7D%2C
```js
                mounted: function () {
                    this.$refs.rootFolder.toggle();
                },
```

The request that initializeMediaApplication() makes to /Admin/Media/MediaApplication appears correct and identical to the result that the normal Admin Create page would receive.  I don't understand Vue very well, I will admit.  Scripts appear to be loaded into the page in the expected order and our theme has the same set of zones that TheAdmin's layout renders

I'm having the same issue with the markdown and html WYSIWYG editors
![image](https://user-images.githubusercontent.com/2787661/217071954-22bf40d4-45d2-4a04-8ce0-7a8c9743a397.png)
![image](https://user-images.githubusercontent.com/2787661/217071997-27dc0710-2d08-402f-b5eb-c1838baaaa9f.png)

However MediaFields which have the Attached editor type are working as expected

Any assistance would be greatly appreciated

**Comment by hishamco** [comment]
Did you configure `MediaOptions` to set the assets path?

**Comment by ericrrichards** [comment]
@hishamco I haven't done anything unusual in the Media Options, as far as I can see
![image](https://user-images.githubusercontent.com/2787661/217078648-acc4d924-8797-4400-9dd6-c98d529dedcc.png)

It works fine if the Media Library modal is launched somewhere in the Admin area
![image](https://user-images.githubusercontent.com/2787661/217078527-7ee8de94-241f-4b45-bf16-3d225aacfc3b.png)

It fails to initialize the modal correctly outside the Admin area

**Comment by hishamco** [comment]
```csharp
routes.MapAreaControllerRoute(
    name: "Media.MediaApplication",
    areaName: "OrchardCore.Media",
    pattern: _adminOptions.AdminUrlPrefix + "/Media/MediaApplication",
    defaults: new { controller = adminControllerName, action = nameof(AdminController.MediaApplication) }
    );
```

The media application run on the admin by default, could you please let us know the use case you are trying to do, because the intend to be used from the admin

**Comment by ericrrichards** [comment]
Is there a specific reason that it is required to be used in the Admin area?

There are a lot of use-cases where I want users to be able to create and edit content items without having them go into the full-blown Orchard Admin area, and being able to use the very good Orchard editor UI saves a lot of frustration and rework.  Makes it much easier to keep a consistent look-and-feel.

Seems like this is very close, and there's some little piece of something I'm missing.
- Role permissions seem fine
- I've got the same scripts loading in the same order on my page as the Admin page (building and rendering the Editor shapes for a ContentItem does almost all of this automatically)
- mediaApplicationPrefs in browser local storage look fine in both areas

I've figured out that I ought to have a .ta-content class somewhere on the enclosing div that this is rendering to, but it is still not quite there. 
$refs is always empty and the Vue component bombs out in this mount event.

I could use Attached MediaFields in some cases, since those do work, but then I'll still have issues with the WYSIWYG editors and adding screenshots and images in there is rather important.

**Comment by ericrrichards** [comment]
Somewhere while I was fighting with this I added a <div id="mediaApp"> and that appears to be the source of the problem with the Vue mounting and $refs being empty.  
I think I was trying to suppress this warning:
` [Vue warn]: Cannot find element: #mediaApp`
which appears if something calls the media,js  initializeMediaApplication() function and there isn't a **.ta-content** element for it to append onto.

Seems to be working now, thanks for the assistance, I'll close this.
