### ISSUE TITLE
Building custom Orchard2 module

### ISSUE THREAD

**Issue by babadro** [OrchardCMS/OrchardCore#1321]
What shall i do to create my own module for Orchard2 and be able to see it in admin panel?

I looked up this topic in documentation, but it can't help me.

No matter how I wrote the module - it doesn't appear in the dashboard.

**Comment by jpiquot** [comment]
Hi,
Did you create your admin menu using the INavigationProvider, like its done in OrchardCore.Tenants ?

Regards,
Jérôme Piquot
[Flexmind France](http://www.flexmind.fr)

```
namespace OrchardCore.Tenants
{
    public class AdminMenu : INavigationProvider
    {
        private readonly ShellSettings _shellSettings;

        public AdminMenu(IStringLocalizer<AdminMenu> localizer, ShellSettings shellSettings)
        {
            _shellSettings = shellSettings;
            T = localizer;
        }

        public IStringLocalizer T { get; set; }

        public void BuildNavigation(string name, NavigationBuilder builder)
        {
            if (!String.Equals(name, "admin", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            // Don't add the menu item on non-default tenants
            if (_shellSettings.Name != ShellHelper.DefaultShellName)
            {
                return;
            }

            builder
                .Add(T["Design"], "10", design => design
                    .AddClass("menu-design").Id("design")
                    .Add(T["Tenants"], "5", deployment => deployment
                        .Action("Index", "Admin", new { area = "OrchardCore.Tenants" })
                        .Permission(Permissions.ManageTenants)
                        .LocalNav()
                    )
                );
        }
    }
}

```

**Comment by babadro** [comment]
No. I just want to create basic Orhcard module that does nothing. Like was described in this article for Orhard 1.4:
http://www.ideliverable.com/blog/writing-an-orchard-webshop-module-from-scratch-part-3
Steps:
1)	Get source code of Orchard2
2)	Create Class library.
3)	Create Module.txt
But if I do it, this does not work.
Ok. Let’s try a little differently.
In another article (for Orchard2) author doesn’t use a source code. Instead he get Orchard2 by nuget.
And then he create a module, that he can see in usual dashboard panel in Orchard (Design - Modules):
http://www.ideliverable.com/blog/orchard-core-and-service-fabric/part-4
But if I do the same steps it doesn’t work too! I have no idea why.

That’s interesting, the source code for last article works fine:
https://github.com/sfmskywalker/BooksUnlimited
I want to do the same thing - to use OrchardCMS, then create module and want to see it in admin panel, but can’t.

**Comment by jpiquot** [comment]
Hi,

Could you share your module and web projects csproj files? You may not have referenced the orchard targets packages.

Regards,
Jérôme Piquot
[Flexmind France](http://www.flexmind.fr)

**Comment by jtkech** [comment]
Just for additional infos, maybe a mix with package versions. See on [gitter](https://gitter.im/OrchardCMS/OrchardCore) the last discussion i had with @JoshLefebvre  to get it working. See the web app `Startup.cs` and `Program.cs`  we are showing and the `.csproj` which references a simple module (`Module1`) grabbed from [OrchardCore.Samples](https://github.com/OrchardCMS/OrchardCore.Samples).

Don't take into account the very last comments where we talk about using the full source code.

**Comment by babadro** [comment]
Thank you, guys!
The problem was solved!
Yes, @JoshLefebvre is right.
If you want to build own module for orchard cms and use nugget packages for this, you have to use same version packages in csproj files (module project and web host project).

If you want to do the same but use source code (not nugget packages), you have to import props file to your custom module like this:
<Import Project="..\OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.props" />
To do it, I had to edit  CustomModule.cproj file in Visual Studio 2017 directly.

And you need to reference OrchardCore.Module.Targets.csproj to your module project of course.

"Don't take into account the very last comments where we talk about using the full source code."
Why? It works great!
