### ISSUE TITLE
module.asset.map file generation error

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#1323]
Hi,
When the modules target more than one framework, I have an issue with the module.assets.map file.
The map file path does not contain the target, so it tries to overwrite the same file for each target.

My project contains:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup Label="Orchard Packages References" Condition=" '$(OrchardCoreType)' != 'Source' ">
    <PackageReference Include="OrchardCore.Module.Targets" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Mvc.Core" Version="$(OrchardCoreVersion)" />
  </ItemGroup>
  <!-- Necessary if we reference the Orchard source project and not the nuget package -->
  <Import Condition=" '$(OrchardCoreType)' == 'Source' " Project="..\..\..\..\OrchardCore\src\OrchardCore\OrchardCore.Application.Targets\OrchardCore.Application.Targets.targets" />
  <ItemGroup Label="Orchard Source References" Condition=" '$(OrchardCoreType)' == 'Source' ">
    <ProjectReference Include="..\..\..\..\OrchardCore\src\OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.csproj" />
    <ProjectReference Include="..\..\..\..\OrchardCore\src\OrchardCore\OrchardCore.Mvc.Core\OrchardCore.Mvc.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Flexmind.Framework.Controller\Flexmind.Framework.Controller.csproj" />
    <ProjectReference Include="..\..\Core\Flexmind.Framework.Helper\Flexmind.Framework.Helper.csproj" />
  </ItemGroup>
</Project>

```
**> 10>C:\Users\FXD000666\.nuget\packages\orchardcore.module.targets\1.0.0-beta2-3946\build\netstandard2.0\OrchardCore.Module.Targets.props(37,5): warning MSB3491: Could not write lines to file "obj\module.assets.map". The process cannot access the file 'C:\Dev\Flexmind.ServiceDesk\Flexmind.Framework\Flexmind.Framework\src\Modules\Flexmind.Framework\obj\module.assets.map' because it is being used by another process.**

Regards,
Jérôme Piquot
[Flexmind France](http://www.flexmind.fr)

**Comment by jtkech** [comment]
Yes, i could repro with the demo module when specifying 2 frameworks as you. I think because there are 2 building in parallel on the same project.

So, it could also happen when we generate a manifest file (e.g Module.txt) (if it doesn't exists). I couldn't repro the issue for this file maybe because it is very small.

You're right, one solution is to use a path based on the targetted framework. Humm, maybe just use a prefix for the file name and then embbed the file with its original name.

I will fix it this night, thanks.

**Comment by jpiquot** [comment]
Hi,
Thank you for the very quick answer.
I did not have any issues with the module.txt file either. As you said, the operation is too quick to conflict.

Regards,
Jérôme Piquot
[Flexmind France](http://www.flexmind.fr)
