### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.1.23107.4] Build with Error ASP0019,ASP0023 after retargeting to .NET 8.0 for OrchardCMS app

### ISSUE THREAD

**Issue by Junjun-zhao** [OrchardCMS/OrchardCore#13263]
When retarget the app to .NET 8.0, the app will build failed with following error:
 
![image](https://user-images.githubusercontent.com/83067197/219308597-c019ba17-bcd4-453f-bbf0-0cd28d139bd0.png)

This is a new change in .NET 8.  [Add analyzer and code fix to recommend against IHeaderDictionary.Add](https://github.com/dotnet/aspnetcore/pull/44463)

**Recommend Action:**
use IHeaderDictionary.Append() method to replace the IDictionary.Add() method

More detailed discussion and about the resolution, please refer below links:

-  [[dotnet-sdk-8.0.100-preview.1.23107.4] Build with Error ASP0019,ASP0023 after retargeting to .NET 8.0 for OrchardCMS app · Issue #46642 · dotnet/aspnetcore (github.com)](https://github.com/dotnet/aspnetcore/issues/46642)

- [ASP0019: Suggest using IHeaderDictionary.Append or the indexer](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0019?view=aspnetcore-7.0)

**Comment by hishamco** [comment]
FYI .NET `8.0` is still in preview, the plan to target `7.0` then we can migrate to `8.0` on the future
