### ISSUE TITLE
Filtering by a role that contains space does not return result in the Users UI

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13276]
### Describe the bug
The role filter in the Users UI does not return records if you filter for a role name that contains a space.

reason that breaks is we create a filter that looks like this `role:role name` but it should be `role:"role name"`

### To Reproduce
1. Create a role with a name that contains a space
2. Give at least one user access to the new role.
3. Go to the users UI, use the filter to filter by the new role.

I am guessing this issue exists into all any filter “including contents filter” where the filterable value contains a space. We should wrap every filterable value with double quote when the value contains at least one space.

**Comment by hishamco** [comment]
Is this could be done in `QueryFilterResult`?

**Comment by MikeAlhayek** [comment]
I think it has to be done on the UI because space would used to separate filters.

**Comment by MikeAlhayek** [comment]
When you wrap the string with double quotes, the whole string including a space is treated as a value. If you don't, a space is used to separate each filter I believe.

**Comment by hishamco** [comment]
> When you wrap the string with double quotes, the whole string including a space is treated as a value

Exactly, but I'm asking who evaluate that if it's YesSQL that means we could wrap the value with double quote from OC

**Comment by MikeAlhayek** [comment]
I think in OC we use the YesSql parser `IQueryParser<User>` to parse the filter. Look at the https://github.com/sebastienros/yessql/blob/6681e3d7053f1d8d0fac623aa78bf7dda6ff75a6/src/YesSql.Filters.Abstractions/Services/FilterResult.cs
