### ISSUE TITLE
Sharing violation on github build action

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#13270]
@sebastienros 

Sometimes we have the following on a PR build action

    The process cannot access the file because it is being used by another process.

We had the same before when using multiple TFMs including 5.x and 3.x as I remember, I needed to update the related script to build each TFM after each other, then we didn't need this with only 6.0.

Looks like we now have the same problem with the 2 TFMs 7.0 and 6.0.

---

Also but not sure, for the following PropertyGroup used for each TFM, we always use a condition on the TFM.

    <PropertyGroup Condition="$(TargetFramework) == 'net6.0'">
      <AspNetCorePackagesVersion>6.0.14</AspNetCorePackagesVersion>
      <MicrosoftExtensionsPackagesVersion>6.0.14</MicrosoftExtensionsPackagesVersion>
    </PropertyGroup>

But at some point the condition on the TFM was not used for the first PropertyGroup used to preset the above versions for the default TFM, the condition was only used for other TFM(s). I don't remember why so not sure it is important, maybe because in some evaluation phases the TFM may be empty, will see.

**Comment by sebastienros** [comment]
Try to remove the condition for the default case then, it's possible that some restore steps don't set the TFM, or add another one that states `$(TargetFramework) == ''` with net7.0 (the new default).

It's possible that there is a race condition in some msbuild steps when they run in parallel due to multiple TFMs.

**Comment by sebastienros** [comment]
If the violation always happens on the same build steps, we can try to run two command lines, one for 6 and one for 7.

**Comment by jtkech** [comment]
Yes, I think we have to do this, the violation already happened to me 3 times.

**Comment by jtkech** [comment]
Just experienced again, will try to update it this week end.
