### ISSUE TITLE
Feature suggestion: ：Provide Admin module to set Admin login path.

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1329]
1:Provide Admin module to set Admin login path.For example: "localhost **/ admin**" changed to ”localhost **/ Login** `"

`1.提供Admin 模块设置  Admin登陆路径.例如："localhost/admin" 修改为localhost/Login `

2. Login page Remember me, it seems invalid.
`2.登陆页面的 Remember me，好像无效。`

**Comment by sebastienros** [comment]
Probably not a module but some static configuration, from a configuration file, or environment variable.
And maybe could be set for each tenant too.

**Comment by hishamco** [comment]
Configuration file is a good option in this case I saw many content management systems such as Umbraco which already had similar feature
