### ISSUE TITLE
Templates don't have a valid <TargetFramework> value

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#13301]
Probably due to the multiple TFMs changes.

**Comment by sebastienros** [comment]
Also these json files need the extra TFM 
https://github.com/OrchardCMS/OrchardCore/blob/13dfce144f8fa0ace701c38acd0541b5be15c680/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Module/.template.config.src/template.json#L12-L24

**Comment by sebastienros** [comment]
Maybe this value is empty right now
https://github.com/OrchardCMS/OrchardCore/blob/13dfce144f8fa0ace701c38acd0541b5be15c680/src/Templates/OrchardCore.ProjectTemplates/OrchardCore.ProjectTemplates.csproj#L96

**Comment by sebastienros** [comment]
To test templates locally:

Create all the packages in a temp folder:

```
cd .\orchardcore
dotnet pack -c Release -p:Version=1.6.0 -p:TreatWarningsAsErrors=false
Get-ChildItem ./src -Recurse -filter *.nupkg | Copy-Item -Destination c:\temp\ocpackages
```

Install and generate a template

```
dotnet new install OrchardCore.ProjectTemplates --nuget-source c:\temp\ocpackages
dotnet new occms
```

Edit the project file to use the temp folder as nuget package source

```xml
  <PropertyGroup>
    <RestoreAdditionalProjectSources>c:\temp\ocpackages</RestoreAdditionalProjectSources>
  </PropertyGroup>
```

**Comment by jtkech** [comment]
I will look at it this week end by first checking what we were used to do when supporting multiple TFMs.
