### ISSUE TITLE
Require element name for Input, Select, and TexArea to avoid exception

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13326]
### Describe the bug
If you add Input element to a form without specifying a name to the field, the content is saved. However, because it is missing a field name, it throws an exception when rendering it.

### Expected behavior
an input widget should require at least a field name before saving.

**Comment by sebastienros** [comment]
Or fix the exception when there is no name?

**Comment by MikeAlhayek** [comment]
@sebastienros as discussed during the meeting, it does not make sense to have HTML element without a name. Id is still optional.

I submitted an PR that require a name for HTML element.
