### ISSUE TITLE
Error activating Nancy : IContentDefinitionService specified multiple times

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#1334]
Hi,

When I activate the orchard module "Nancy", I can not access to the web site anymore. 

The Nancy module startup seems to try to register multiple times the content definition service here:

```
 public static class ModularApplicationBuilderExtensions
 {
        public static ModularApplicationBuilder UseNancyModules(this ModularApplicationBuilder modularApp)
        {
            modularApp.Configure(app =>
            {
                var contextAccessor =
                    app.ApplicationServices.GetRequiredService<IHttpContextAccessor>();

                app.UseOwin(x => x.UseNancy(no =>
                {
                    no.Bootstrapper = new ModularNancyBootstrapper(
                        new[] {
                            (IAssemblyCatalog)new DependencyContextAssemblyCatalog(),
                            (IAssemblyCatalog)new AmbientAssemblyCatalog(contextAccessor)
                        });
                }));
            });
            return modularApp;
        }
 }
 ```
Regards,
Jérôme Piquot
[Flexmind France](http://www.flexmind.fr)

**Exception:**
An unhandled exception occurred while processing the request.
ArgumentException: types: The same implementation type cannot be specified multiple times for OrchardCore.ContentTypes.Services.IContentDefinitionService

OrchardCore.ContentTypes.Services.ContentDefinitionService
Nancy.TinyIoc.TinyIoCContainer.RegisterMultiple(Type registrationType, IEnumerable<Type> implementationTypes)
Stack Query Cookies Headers 
ArgumentException: types: The same implementation type cannot be specified multiple times for OrchardCore.ContentTypes.Services.IContentDefinitionService OrchardCore.ContentTypes.Services.ContentDefinitionService
Nancy.TinyIoc.TinyIoCContainer.RegisterMultiple(Type registrationType, IEnumerable<Type> implementationTypes)
Nancy.TinyIoc.TinyIoCContainer.AutoRegisterInternal(IEnumerable<Assembly> assemblies, DuplicateImplementationActions duplicateAction, Func<Type, bool> registrationPredicate)
Nancy.Bootstrapper.NancyBootstrapperBase.Initialise()
Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)
Nancy.Owin.DelegateExtensions.UseNancy(Action<Func<Func<IDictionary<string, object>, Task>, Func<IDictionary<string, object>, Task>>> builder, NancyOptions options)
OrchardCore.Nancy.ModularApplicationBuilderExtensions+<>c__DisplayClass0_0.<UseNancyModules>b__1(Action<Func<Func<IDictionary<string, object>, Task>, Func<IDictionary<string, object>, Task>>> x)
Microsoft.AspNetCore.Builder.OwinExtensions.UseOwin(IApplicationBuilder builder, Action<Action<Func<Func<IDictionary<string, object>, Task>, Func<IDictionary<string, object>, Task>>>> pipeline)
OrchardCore.Nancy.ModularApplicationBuilderExtensions+<>c.<UseNancyModules>b__0_0(IApplicationBuilder app)
OrchardCore.Modules.ModularApplicationBuilder.Configure(Action<IApplicationBuilder> configuration)
OrchardCore.Nancy.ModularApplicationBuilderExtensions.UseNancyModules(ModularApplicationBuilder modularApp)
OrchardCore.Nancy.Startup+<>c.<Configure>b__1_0(ModularApplicationBuilder apb)
Microsoft.AspNetCore.Builder.ModularApplicationBuilderExtensions.ConfigureModules(IApplicationBuilder app, Action<ModularApplicationBuilder> modules)
OrchardCore.Nancy.Startup.Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline(ShellSettings shellSettings, IServiceProvider serviceProvider)
OrchardCore.Modules.ModularTenantRouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OrchardCore.Modules.ModularTenantContainerMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
OrchardCore.Modules.ModularTenantContainerMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by sebastienros** [comment]
Jerome, you don't need to sign each of your messages ;)

**Comment by sebastienros** [comment]
Have you tried without using the CMS?

Would be interesting to try an app with both MVC and Nancy at the same time.

**Comment by jpiquot** [comment]
Hi Sebastien,
No, I did not try without the CMS. My application needs Nancy only to handle batch requests ("api/batch") as Syncfusion controls use them. 

I will try to debug this and give you a feedback as soon as I can.

**Comment by jpiquot** [comment]
Hi,

I think that the issue comes from the GetAssemblies method below. For me it returns 1280 assemblies instead of 59. If i add the Distinct() call in the assembly query to remove duplicates, I dont have the error anymore.

```
namespace OrchardCore.Nancy.AssemblyCatalogs
{
    public class AmbientAssemblyCatalog : IAssemblyCatalog
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        /// <summary>
        /// Initializes a new instance of the <see cref="AmbientAssemblyCatalog"/> class.
        /// </summary>
        public AmbientAssemblyCatalog(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        /// <summary>
        /// Gets all <see cref="Assembly"/> instances in the catalog.
        /// </summary>
        /// <returns>An <see cref="IReadOnlyCollection{T}"/> of <see cref="Assembly"/> instances.</returns>
        public IReadOnlyCollection<Assembly> GetAssemblies()
        {
            var shellBluePrint = _httpContextAccessor.HttpContext.RequestServices.GetRequiredService<ShellBlueprint>();
            return shellBluePrint.Dependencies.Keys
                .Select(type => type.Assembly)
Add--->         .Distinct()
                .ToArray();
        }
    }
}

```

**Comment by jtkech** [comment]
Maybe 1st copied from this [line of code](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Mvc.Core/ShellFeatureApplicationPart.cs#L48) but where we need to return all types, not the assemblies as here. But indeed here many types share the same assemblies ... Good catch, thanks.

**Comment by jpiquot** [comment]
You are welcome ;)
