### ISSUE TITLE
Guidance for .net 7 Program.cs

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#13355]
What is the guidance for a new asp.net project in .net 7?
We don't have a startup file anymore and instead just have a program.cs.
The documentation has a gif showing the steps for I assume pre .net 7?

**Comment by JoshTango** [comment]
Here si the code generated by visual studio which I assume we can remove some of these lines:

`var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();`

**Comment by jtkech** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/a04a6bebc606e81c4d8cd21f8186b2b20ccfb0c0/src/OrchardCore.Cms.Web/Program.cs#L1-L22

**Comment by JoshTango** [comment]
Ok thanks.  Then the documentation needs upgraded I guess.

**Comment by jtkech** [comment]
Yes ;)

**Comment by hishamco** [comment]
> Ok thanks. Then the documentation needs upgraded I guess.

Where? what I see in https://docs.orchardcore.net/en/latest/docs/getting-started/ is correct

**Comment by JoshTango** [comment]
this one:

https://docs.orchardcore.net/en/latest/docs/getting-started/templates/

**Comment by JoshTango** [comment]
there is a step in 
https://docs.orchardcore.net/en/latest/docs/getting-started/templates/
called so:

Finally, we will need to register Orchard CMS service in our Startup.cs file like this:

**Comment by hishamco** [comment]
@JoshTango could you please open a PR?

**Comment by hishamco** [comment]
@agriffard did `docs.orchardcore.net` contains the latest update from the nightly builds?

**Comment by agriffard** [comment]
> @agriffard did `docs.orchardcore.net` contains the latest update from the nightly builds?

https://docs.orchardcore.net/en/latest/... is built based on the main branch.

**Comment by Piedone** [comment]
This was done in https://github.com/OrchardCMS/OrchardCore/pull/13380.
