### ISSUE TITLE
Razor pages wont render html

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#13368]
Recently I started getting this error on razor pages inside my modules when I press the submit button on a page:

Your browser sent a request that this server could not understand.

When I look at the page source it looks exactly like the markup:

    <form method="post">
        Prompt:
        <input asp-for="Title" />    
        <input type="submit" />
    </form>

It also is not rendering the AntiforgeryToken token.

This started about a week ago with all my modules with razor pages.
I did do a few updates with visual studio and not sure if this is the source of the problem.

Just thought  would post this and see if anyone else has the same issue?

**Comment by jtkech** [comment]
Just tried some Razor Pages rendering/form submit with the last version, by referencing and then enabling the `OC.Demo` module, it seems to work as expected.

Maybe related to large cookies, can you try to clear your browser cookies.

Maybe related #12142.

**Comment by sebastienros** [comment]
Needs repro steps
