### ISSUE TITLE
Use Script for Username setting ignored - Azure AD

### ISSUE THREAD

**Issue by GeeksGoneBad** [OrchardCMS/OrchardCore#13379]
Selecting the "Use a script to generate userName based on external provider claims " in the Security -> User Registration area does not make the system use the script

### To Reproduce
1. Go to Security -> User Registration
2. Click on '"Use a script to generate userName based on external provider claims "
3. Uncomment lines in the script or even just make one entry for a log entry
4. Log in through Azure AD
5.  User gets created with the default "azad" UUID type username no matter what you put in the script... and custom log messages do not get entered in the log (tells me it's just not running the script at all)

### Expected behavior
I would expect the username to be changed per the script, and also my custom log messages to be entered in the log

**Comment by ns8482e** [comment]
Based on your description it seems that the script is executing as expected as it's generating user is as `aazad-############`
