### ISSUE TITLE
Exception: Shape type 'Widget_DetailAdmin' not found

### ISSUE THREAD

**Issue by parxal** [OrchardCMS/OrchardCore#1337]
I was trying to create a list of a content type to be display inside a widget.

Steps : 
Create a content type 
- Display Name : ListWidget
- Stereotype : Widget
- Remove Creatable
- Remove Listable 
- Add Part 'List'  / choose another content type in List Contained Content Types for the list

Go to Layers
In content Add Widget 'ListWidget' named 'Home Links'

Now in Layers page click in 'Home Links' that error appers.

**Comment by arkadiuszwojcik** [comment]
I have the same problem but for ContentPart. Looks like default DetailAdmin view is not generated for custom parts. Error I get is `Shape type 'ContentPart_DetailAdmin' not found`

**Comment by arkadiuszwojcik** [comment]
Regarding my problem, is it possible because there is no `ContentPart.DetailAdmin.cshtml` file in: `OrchardCore.Modules/OrchardCore.Contents/Views` ?

**Comment by arkadiuszwojcik** [comment]
I get similar exception but for `ContentPart`. Looks like default DetailAdmin view is not generated for custom parts. Error I get is `Shape type 'ContentPart_DetailAdmin' not found`. After spending some time on this I found that there is no `ContentPart.DetailAdmin.cshtml` in project: `OrchardCore.Modules/OrchardCore.Contents/Views`. Widget module is also missing DetailAdmin view.

**Comment by sebastienros** [comment]
Might a recent bug as we introduced support for theming custom content part last month.
