### ISSUE TITLE
Getting Orchard Core into the Red Hat Ecosystem Catalog

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#13370]
### Is your feature request related to a problem? Please describe.
Not really a problem, just about improving Orchard's visibility in a circle where it's probably unknown, outside of the .NET community.

### Describe the solution you'd like
Red Hat has an [Ecosystem Catalog](https://catalog.redhat.com/) that contains all kinds of software and hardware that somehow builds on, runs on, or is related to Red Hat's platforms (like Enterprise Linux or the contain platform OpenShift). Among these, there are [blog engines and CMS](https://catalog.redhat.com/software/search?functionalCategories=Blog%20%26%20CMS&p=1) too.

So, unless anybody objects, I'd create an Orchard organization and work on getting Orchard Core listed there. This most possibly needs demonstrating that it can run on Red Hat Enterprise Linux (RHEL), which should be no issue, since Orchard happily runs under Linux and .NET [supports RHEL too](https://learn.microsoft.com/en-us/dotnet/core/install/linux-rhel).

This can pave the way to further marketing options to evangelize Orchard, [see here](https://connect.redhat.com/en/partner-with-us/partner-benefits/certification-marketing-benefits).

### Describe alternatives you've considered
Not doing this, but getting the basics done seems like a low hanging fruit.

**Comment by Piedone** [comment]
Anybody with an objection, speak up! I'll go ahead and cerate the profile otherwise.

**Comment by sebastienros** [comment]
It would mean that whenever we ship we need to update this too, including security releases. So just more work?

**Comment by Piedone** [comment]
I don't know if all releases need to be verified but I'd guess not, since none of the CMS software listed in the Catalog has a corresponding version of the CMS. They have a corresponding RHEL version though, so that'd need to be done if new (at least major) versions come out. I think though getting Orchard certified once would already provide the benefit that it's perpetually in the Catalog.

**Comment by Piedone** [comment]
I've signed up under https://connect.redhat.com/user/register/lookup. If you'd like to be invited to the Orchard org, let me know.

**Comment by Piedone** [comment]
Do we have some kind of central e-mail for Orchard that multiple people can receive? I've seen orchard@microsoft.com but I'm not sure where that goes or if it works.

I checked out whether we can have a discussion for this in a GitHub project, that people can write to (using the Reply-To address that you can reply to when getting an e-mail notification from GitHub). That actually works, but it'll post a message in your name (since these Reply-To addresses are apparently unique for everyone). So, not something usable.

I've used crew@lombiq.com for the "corporate profile" for now.

**Comment by Piedone** [comment]
I checked out doing a container app certification. We can't do that with [the OC Docker image](https://hub.docker.com/r/orchardproject/orchardcore-cms-linux), since Red Hat required Podman.

So, I created a non-containerized app certification. I completed the certification and am now waiting for the results.

Quick docs: Once the basics are set up on the portal, these are the steps:

1. Create an Azure RHEL (latest major version, currently 9) Azure VM. You can find this by searching for "Red Hat Enterprise Linux" in the Marketplace, and then setting up the official image provided by Red Hat. Be sure to keep HTTP and HTTPS ports open.
2. Connect with MobaXterm, using the VM’s public IP, “azureuser” as the user, and the private key PEM file Azure lets you download when creating the VM.
3. Open up port 80:
```console
sudo systemctl status firewalld
sudo firewall-cmd --zone=public --add-port=80/tcp --permanent
sudo firewall-cmd --reload
```
4. Open the full OC source that was released, and publish it. Use Release Configuration, self-contained, with the Target Runtime `linux-x64`. You can do this with right click-Publish from Visual Studio as well. Upload the publish folder to the VM (what you can do from the file browser of MobaXterm).
5. Test running the app with:
```console
sudo mkdir -m 777 App_Data
sudo mkdir -m 777 wwwroot
sudo chmod 777  ./OrchardCore.Cms.Web
sudo ./OrchardCore.Cms.Web --urls http://*:80 --wwwroot
```
6. Open the IP of the VM in a web browser; you should see the setup screen and should be able to run the setup too.
7. Open a new SSH window while keeping Orchard running, and follow https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.61/html/red_hat_software_certification_workflow_guide/proc_certification-workflow-for-non-containerized-application_openshift-sw-cert-workflow-onboarding-certification-partners#certification_testing
  - Run **all commands** prefixed with `sudo` since you can't use the `root` user.
  - If you get "Ignoring request to attach. It is disabled for org ... because of the content access mode setting." then Simple Content Access needs to be disabled under https://access.redhat.com/management. Then you can try attaching again.
8. Once the certification is done and confirmed by Red Hat, delete the VM and all the corresponding resources, as well as the system from under https://access.redhat.com/management/systems.

**Comment by Piedone** [comment]
Certification done: https://catalog.redhat.com/software/applications/detail/223797 However, I can't seem to be able to publish the product page due to some glitch yet, am on it.

**Comment by Piedone** [comment]
And here it is! https://catalog.redhat.com/software/applications/detail/223797 I also added a documentation page for the whole process.

**Comment by RomBrz** [comment]
Hi, just to have a update about the container app certification. Do you intend to make it? Can run on podman too?

**Comment by Piedone** [comment]
Most possibly Orchard does work with podman, but I don't have the capacity to set this up, test, and get the certification done. However, if you're interested to do it, please tell!
