### ISSUE TITLE
UserTaskEventContentDriver throws exception when invoke UpdateEditorAsync in a request whose ContentType is application/json

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#13388]
### Describe the bug
```
UserTaskEventContentDriver thrown from UpdateEditorAsync by InvalidOperationException
System.InvalidOperationException: Incorrect Content-Type: application/json
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()
   at OrchardCore.Workflows.UserTasks.Drivers.UserTaskEventContentDriver.UpdateAsync(ContentItem model, IUpdateModel updater)
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.UpdateEditorAsync(ContentItem contentItem, UpdateEditorContext context)
```
### To Reproduce
1. Send a request with Content-Type is application/json
2. In the handling action, call ContentItemDisplayCoordinator.UpdateEditorAsync
3. The exception should be shown in the log

### Expected behavior
UserTaskEventContentDriver do nothing.

**Comment by HengzheLi** [comment]
```
public override async Task<IDisplayResult> UpdateAsync(ContentItem model, IUpdateModel updater)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            var action = (string)httpContext.Request.Form["submit.Save"] ?? httpContext.Request.Form["submit.Publish"];
            ......
        }
```
httpContext.Request.Form["submit.Save"] does not work when the request is application/json content type.

**Comment by sebastienros** [comment]
Because this driver is not supposed to be invoked by front-end code but from the part editor in the admin while editing a content item.

Can you describe what you are trying to implement so we can either find a solution or provide an alternative approach?

**Comment by Piedone** [comment]
Closing due to author not replying.
