### ISSUE TITLE
TitlePart pattern not applied when options is set to 'Title is editable'

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#13394]
From titlePart settings of the TitlePart is editable and there is a pattern to be set the pattern does not get applied.

Solution .
Apply pattern   as long as the titelpart has not been set already.

**Comment by MikeAlhayek** [comment]
I don't think this is an issue. This is the expected behavior. If you want to use a pattern, you should use an options that starts with `Generated` like `GeneratedDisabled` or `GeneratedHidden`.

**Comment by MikeAlhayek** [comment]
@giannik did you test 1.6? Can we close this issue?

**Comment by giannik** [comment]
yes @MikeAlhayek we can close it.
