### ISSUE TITLE
dynamically added menu items in Customized MainMenu using INavigationProvider are not rendered

### ISSUE THREAD

**Issue by Digisaman** [OrchardCMS/OrchardCore#13409]
I have an issue with navigation, I'm trying to change the MainMenu Items based on the logged-in user's Role ( add menu items specific to a role) I've tried 2 approaches
1 : using INavigationProvider in theme to dynamically add Menu Items based on Role,
2: Adding the menu Items in admin dashboard and then decide not to render some menus based on role in Menu.cshtml in theme.

Both Approaches work correctly in dev environment(Visual Studio 2022), but When I publish to my local IIS, Or the remote WebServer, it doesn't work!! (the dynamically added menus are not displayed ), There is no error log, so I don't understand what is causing the issue.
I've been stuck on this issue for weeks, please help me

Here is the code for approach 1:
I Customized "TheTheme" Project
Added this line in Menu.cshtml : 
tag.InnerHtml.AppendHtml(await DisplayAsync(await New.Navigation(MenuName: "main-menu", RouteData: @ViewContext.RouteData)));

Added this class:
public class MainMenu : INavigationProvider
{
    private readonly IStringLocalizer S;
    private readonly IHttpContextAccessor _httpContext;

    public MainMenu(IStringLocalizer<MainMenu> localizer,
        IHttpContextAccessor httpContext)
    {
        S = localizer;
        _httpContext = httpContext;
    }

    public Task BuildNavigationAsync(string name, NavigationBuilder builder)
    {
        //if (!String.Equals(name, "main-menu", StringComparison.OrdinalIgnoreCase))
        //{
        //    return Task.CompletedTask;
        //}

        if (_httpContext.HttpContext.User.IsInRole("Administrator") ) 
        {
            builder.Remove(c => c.Url == "/FreelancerProfile/Index");

            builder.Remove(c => c.Url == "/CompanyProfile/Index");
        }

        if (_httpContext.HttpContext.User.IsInRole("Freelancer"))
        {
            builder
                 .Add(S["Freelancer Profile"], S["FreelancerProfile"], layers => layers
                .Action("Index", "FreelancerProfile", new { area = "FrogsNetwork.Freelancing" })
                .LocalNav());
            builder.Remove(c => c.Url == "/CompanyProfile/Index");
        }
        else if (_httpContext.HttpContext.User.IsInRole("Company"))
        {
            builder
                 .Add(S["Company Profile"], S["ComapanyProfile"], layers => layers
                .Action("Index", "CompanyProfile", new { area = "FrogsNetwork.Freelancing" })
                .LocalNav());
            builder.Remove(c => c.Url == "/FreelancerProfile/Index");
        }
        //}
        return Task.CompletedTask;
    }
}

**Comment by rjpowers10** [comment]
This doesn't directly address your question but I would suggest creating custom permissions and mapping those permissions to roles. Then you specify which permission is required for each menu item. If the role doesn't have the required permission the menu item will be hidden. You would also want to use `IAuthorizationService` inside your `FreelancerProfile` and `CompanyProfile` controllers to enforce the permission there, in the event the user manually navigated there through the address bar or a bookmark.

[Example menu item](https://github.com/OrchardCMS/OrchardCore/blob/65aac3ec6fded70a494b25e2369108ec2de5622d/src/OrchardCore.Modules/OrchardCore.Cors/AdminMenu.cs#L30)

[Example permission](https://github.com/OrchardCMS/OrchardCore/blob/65aac3ec6fded70a494b25e2369108ec2de5622d/src/OrchardCore.Modules/OrchardCore.Cors/Permissions.cs#L10)

[Example controller](https://github.com/OrchardCMS/OrchardCore/blob/65aac3ec6fded70a494b25e2369108ec2de5622d/src/OrchardCore.Modules/OrchardCore.Cors/Controllers/AdminController.cs#L47)

**Comment by Skrypt** [comment]
I would guess first that the user roles are not deployed on the production server if they don't work.

**Comment by Digisaman** [comment]
> This doesn't directly address your question but I would suggest creating custom permissions and mapping those permissions to roles. Then you specify which permission is required for each menu item. If the role doesn't have the required permission the menu item will be hidden. You would also want to use `IAuthorizationService` inside your `FreelancerProfile` and `CompanyProfile` controllers to enforce the permission there, in the event the user manually navigated there through the address bar or a bookmark.
> 
> [Example menu item](https://github.com/OrchardCMS/OrchardCore/blob/65aac3ec6fded70a494b25e2369108ec2de5622d/src/OrchardCore.Modules/OrchardCore.Cors/AdminMenu.cs#L30)
> 
> [Example permission](https://github.com/OrchardCMS/OrchardCore/blob/65aac3ec6fded70a494b25e2369108ec2de5622d/src/OrchardCore.Modules/OrchardCore.Cors/Permissions.cs#L10)
> 
> [Example controller](https://github.com/OrchardCMS/OrchardCore/blob/65aac3ec6fded70a494b25e2369108ec2de5622d/src/OrchardCore.Modules/OrchardCore.Cors/Controllers/AdminController.cs#L47)

Hi, Thank you for your suggestion, I tried It (Menu/Controller/Permission) and It works in Development Environment, But When I Publish I Still have the same Issue! The Menus do appear correctly (based on role permissions) in Visual Studio Debug ( IIS Express ) But in IIS They are not displayed!!! And There is no error log to indicate where the error is coming from.

**Comment by Digisaman** [comment]
> @Digisaman is it similar to #13408 ?

Yes, It's the same issue

**Comment by hishamco** [comment]
I will close it then

**Comment by Digisaman** [comment]
@hishamco do you have any idea why the code works in development environment, But behaves differently in IIS? I tried to debug the issue by attaching Visual Studio to the IIS Worker process and debug while the application is running in IIS, But my breakpoints are not hit, so no Luck!!

**Comment by hishamco** [comment]
Do you have a minimal repo?

> But behaves differently in IIS

How it behaves?

**Comment by Digisaman** [comment]
what do you mean by minima repos?
I forked the OrchardCore Repo and added modules to it

**Comment by hishamco** [comment]
Please share the module if it's possible or add it as branch in your fork, so I can test it

**Comment by Digisaman** [comment]
@hishamco I Can share it, How do I Send it to you?

**Comment by jtkech** [comment]
In case it is because a `.cshtml` shape view that you override, check in your project files if there are some extra item groups (e.g. added by Visual Studio) that would prevent the shape view to be embedded in the assembly, this is a scenario where it would work in dev but not in production.

Also, if you are using one of our tag helper, your project needs to reference the project that defines this tag helper, a missing reference is another scenario where it would work in dev but not in production.

**Comment by hishamco** [comment]
@Digisaman try to follow JT suggestion first

**Comment by Digisaman** [comment]
I've modified "TheTheme" project, so the structure is completely the same, I haven't overridden any views / classes
And I do have a reference to my module,
I've added a MainMenu File, Implementing INaviationProvider, I have edited Menu.cshtml in the Theme Project, which references Permissions in a Module I Created, But the Issue still persists : (Works in Dev, Does NOT work in IIS Publish)

Here's My Main Menu class:
public class MainMenu : INavigationProvider
{
    private readonly IStringLocalizer S;
    private readonly IHttpContextAccessor _httpContext;

    public MainMenu(IStringLocalizer<MainMenu> localizer,
        IHttpContextAccessor httpContext)
    {
        S = localizer;
        _httpContext = httpContext;
    }

    public Task BuildNavigationAsync(string name, NavigationBuilder builder)
    {
        if (!String.Equals(name, "main-menu", StringComparison.OrdinalIgnoreCase))
        {
            return Task.CompletedTask;
        }


        builder
             .Add(S["Freelancer Profile"], S["FreelancerProfile"], layers => layers
            .Action("Index", "FreelancerProfile", new { area = "FrogsNetwork.Freelancing" })
            .Permission(FrogsNetwork.Freelancing.Permissions.ManageFreelancerProfile)
            .LocalNav());

        builder
             .Add(S["Company Profile"], S["ComapanyProfile"], layers => layers
            .Action("Index", "CompanyProfile", new { area = "FrogsNetwork.Freelancing" })
             .Permission(FrogsNetwork.Freelancing.Permissions.ManageCompanyProfile)
            .LocalNav());

        return Task.CompletedTask;
    }
}

Here's the  Menu.cshtml View : 
@{
    // By using a tag builder, sub items can alter the
    // menu element. Note how Display is called on the menu
    // items before the tag is actually rendered.

    TagBuilder tag = Tag(Model, "ul");
    tag.AddCssClass("navbar-nav ms-auto");
    foreach (var item in Model.Items)
    {
        tag.InnerHtml.AppendHtml(await DisplayAsync(item));
    }
   
    if (User.Identity.IsAuthenticated)
    {
        tag.InnerHtml.AppendHtml(await DisplayAsync(await New.Navigation(MenuName: "main-menu", RouteData: @ViewContext.RouteData)));
    }
}
@tag


and Here's the Permission class in the Module I Created : 
namespace FrogsNetwork.Freelancing;
public class Permissions : IPermissionProvider
{
    public static readonly Permission ManageFreelancerProfile = new Permission("ManageFreelancerProfile", "Manage profile information for freelancers", true);

    public static readonly Permission ManageCompanyProfile = new Permission("ManageCompanyProfile", "Manage profile information for companies", true);

    private readonly IRoleService _roleService;

    public Permissions(IRoleService roleService)
    {
        _roleService = roleService;
    }

    public IEnumerable<PermissionStereotype> GetDefaultStereotypes()
    {
        return new[] {
                new PermissionStereotype {
                    Name = nameof(Roles.Freelancer),
                    Permissions = new[] { ManageFreelancerProfile }
                },
                new PermissionStereotype {
                    Name = nameof(Roles.Company),
                    Permissions = new[] { ManageCompanyProfile }
                }
            };
    }

    public async Task<IEnumerable<Permission>> GetPermissionsAsync()
    {
        var list = new List<Permission>
            {
                ManageFreelancerProfile,
                ManageCompanyProfile
            };
        return list;
    }
}

**Comment by jtkech** [comment]
Hmm, if it works in dev I assume that you are well registering your nav provider, permissions and so on. Hmm, in case you don't publish the same database, is your module still enabled in production?

**Comment by hishamco** [comment]
@Digisaman I'm suggesting creating a repo that contains your module with all the setup needed, you could use SQLite for simplicity, then we can quickly test it

**Comment by Digisaman** [comment]
@hishamco the project is forked from orchardcore repo
It's public, you can view it here : 
https://github.com/Digisaman/FrogsNetworkCore

**Comment by hishamco** [comment]
I will check today, you tell me the issue occurs on IIS, right?

**Comment by Digisaman** [comment]
> I will check today, you tell me the issue occurs on IIS, right?
> 
> Is there anything else you added except [FrogsNetwork.Freelancing](https://github.com/Digisaman/FrogsNetworkCore/tree/main/src/FrogsNetwork.Modules/FrogsNetwork.Freelancing)?

Yes, I Just Added the FrogsNetwork.Freelancing Module and Customized the "TheTheme" project and the Issue happens only when I run it in IIS

**Comment by hishamco** [comment]
@Digisaman I am able to run the app, with FrogsNetwork.Freelancing module enabled nothing but I didn't see any menu except I saw the admin menu on the front-end with a custom green header

Am I miss something?

**Comment by Digisaman** [comment]
The menus are based on the user's role, I''ve setup the register page to take a URL query string parameter, specifying the user's role.
 so if you register a user with Freelancer Role : 
https://localhost:44300/register?role=Freelancer
the user is automatically assigned the "Freelancer" role, the same is true with the "Company" role:
https://localhost:44300/register?role=Company
then if you sign in with a user with Freelancer Role, you should see a frontend menu item called "Freelancer Profile" for the user  and then if you logout and log back in with a user in "Company" role you should see a frontend menu item called "Company Profile", which is the expected behavior.  But when you publish the same project to IIS, the menus are not rendered based on users's role. they are not displayed at all

**Comment by hishamco** [comment]
> This is All I Want to do, If you have any other approach on how to have different items in the frontend menu based on the logged-in user's Role, please let me know.

Simply you can add menu from the admin, then set a certain permission to display it in the front-end

**Comment by hishamco** [comment]
> so if you register a user with Freelancer Role :
https://localhost:44300/register?role=Freelancer
the user is automatically assigned the "Freelancer" role, the same is true with the "Company" role:

I got "The page is not found", please fix the sample to save the time to fix the main issue or try my above suggestion

**Comment by Digisaman** [comment]
> > This is All I Want to do, If you have any other approach on how to have different items in the frontend menu based on the logged-in user's Role, please let me know.
> 
> Simply you can add menu from the admin, then set a certain permission to display it in the front-end

I can add menus from admin, But now, the permissions I set are ignored and menus are always displayed, even for the UnAuthenticated User,   How do I Set the permission for some menu Items to appear for "Freelancer" role and other menus to appear for "Compnay" role?

**Comment by Digisaman** [comment]
> `IAuthorizationService`

I am using the IAuthorizationService on controllers, the permissions are checked correctly, But that does NOT solve the Issue,  Eventough I've Set permissions on the menus, to appear for a certain role, Either they are not displayed ( when I added them dynamically ) or they are always displayed (when I add them in admin panel ) But they are not displayed according to role, which is what I want.

Is there a way to add menus with the admin panel and Also set permissions on them so they only appear when the user with the correct role is logged in?

**Comment by Digisaman** [comment]
Ok. Tanx, I still think this is a bug and it's something that should be checked/fixed in future releases
Basically INavigaionProvider.BuildNavigationAsync is workin as expected in Dev Mode, but when it get's published on IIS, it doesn't work, and there is no error log to find out why

**Comment by Digisaman** [comment]
TheBolgTheme menu works when you always want to display the frontend menu items, "TheTheme" Menu also works in local & IIS.

But when I try to customize the menu items based on role, I have this Issue.

**Comment by hishamco** [comment]
I might create a quick demo, checking this if I have a time

**Comment by Digisaman** [comment]
Tanx, I'd appreciate it.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jtkech** [comment]
@Digisaman Any feedback?

Beyond other things, I think that you can fix your issue by removing in `Layout.cshtml` the shape caching of the  `main-menu`, or in place of `Menu.cshtml` use another shape to render your custom navigation.

For testing you can first remove the `main-menu` shape caching by just using 

    <menu alias="alias:main-menu" />

In place of

    <menu alias="alias:main-menu"
        cache-id="main-menu"
        cache-fixed-duration="00:05:00"
        cache-tag="alias:main-menu" />

As said, it works in debug mode because by default there is no shape caching in a development env.

Let us know ;)

**Comment by Digisaman** [comment]
Tanx @jtkech  , It's working now on IIS. although the dynamically added menu is not aligned with static menus correctly. which I guess could be fixed by adding a class to the Menu. I'll work on it

![image](https://user-images.githubusercontent.com/12669884/226694245-1dea107c-a6ef-4bb0-a39b-0bb0fd5c0459.png)

And I'll also fix my code with your remarks about async & await.
 Thank you again for your time

**Comment by Digisaman** [comment]
The UI Issue was solved by adding "navbar-link" class to the dynamically added menus, tanx @hishamco @jtkech
