### ISSUE TITLE
Lucene does not indexing media file paths 

### ISSUE THREAD

**Issue by smemis** [OrchardCMS/OrchardCore#13424]
Hello there,

I'm working on a following use case:

I have pretty complex entities which combine many different fields and content parts. What I'd like is to have a kind of a card component on the frontend which shows only the name, short description, title and an image contained in the entity and list the cards on the page. What I want to avoid tho is querying all Documents on the page load since I don't need the 80% of the entities' content parts and fields while listing the cards.

For text fields I simply added them to the lucene index to retrieve them from there, but I struggle with finding a way of adding media path to index to retrieve it using a Razor helper. Is there a way to do that? 

To extend on that discussion - is it even reasonable to try minimize the data flowing between db and server, by loading only fields necessary for the view model while using SQLite in production?

_Originally posted by @Cinnam00n in https://github.com/OrchardCMS/OrchardCore/discussions/13032_

**Comment by smemis** [comment]
Person content type definition:

{
  "name": "ContentDefinition",
  "ContentTypes": [
    {
      "Name": "Person",
      "DisplayName": "Person",
      "Settings": {
        "ContentTypeSettings": {
          "Creatable": true,
          "Listable": true,
          "Draftable": true,
          "Versionable": true,
          "Securable": true
        },
        "FullTextAspectSettings": {
          
        }
      },
      "ContentTypePartDefinitionRecords": [
        {
          "PartName": "Person",
          "Name": "Person",
          "Settings": {
            "ContentTypePartSettings": {
              "Position": "1"
            }
          }
        },
        {
          "PartName": "HtmlBodyPart",
          "Name": "HtmlBodyPart",
          "Settings": {
            "ContentTypePartSettings": {
              "Position": "2"
            }
          }
        },
        {
          "PartName": "TitlePart",
          "Name": "TitlePart",
          "Settings": {
            "ContentTypePartSettings": {
              "Position": "0"
            }
          }
        }
      ]
    }
  ],
  "ContentParts": [
    {
      "Name": "Person",
      "Settings": {
        
      },
      "ContentPartFieldDefinitionRecords": [
        {
          "FieldName": "TextField",
          "Name": "FirstName",
          "Settings": {
            "ContentPartFieldSettings": {
              "DisplayName": "First Name",
              "Position": "0"
            },
            "TextFieldSettings": {
              
            },
            "LuceneContentIndexSettings": {
              "Included": true,
              "Stored": true,
              "Keyword": true
            }
          }
        },
        {
          "FieldName": "TextField",
          "Name": "LastName",
          "Settings": {
            "ContentPartFieldSettings": {
              "DisplayName": "Last Name",
              "Position": "1"
            },
            "TextFieldSettings": {
              
            },
            "LuceneContentIndexSettings": {
              "Included": true,
              "Stored": true
            }
          }
        },
        {
          "FieldName": "MediaField",
          "Name": "Photo",
          "Settings": {
            "ContentPartFieldSettings": {
              "DisplayName": "Photo",
              "Position": "2"
            },
            "MediaFieldSettings": {
              "Multiple": false
            },
            "LuceneContentIndexSettings": {
              "Included": true,
              "Stored": true
            }
          }
        }
      ]
    }
  ]
}

**Comment by Skrypt** [comment]
I need to remember if we index the path or not. But @piedone added the ability to index the content of a media file when it is a PDF as an example.

**Comment by smemis** [comment]
@Skrypt , @Piedone Can you show an example of how I can do this or some code I can review? this will be very helpful, thanks in advance for your help

**Comment by Piedone** [comment]
Check out [`MediaFieldIndexHandler`](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Media/Indexing/MediaFieldIndexHandler.cs).

**Comment by smemis** [comment]
Thanks @Skrypt , @Piedone working code below

<pre>
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using OrchardCore.Indexing;
using OrchardCore.Media;
using OrchardCore.Media.Fields;

namespace OrchardCore.Persons.Indexing
{
    public class MediaFieldPathIndexHandler : ContentFieldIndexHandler<MediaField>
    {

        public MediaFieldPathIndexHandler()
        {
        }

        public override Task BuildIndexAsync(MediaField field, BuildFieldIndexContext context)
        {
            var options = context.Settings.ToOptions();

            if (field.Paths?.Length > 0)
            {
                context.DocumentIndex.Set("Person.Photo", field.Paths[0], options);
            }

            return Task.CompletedTask;
        }
    }
}
</pre>

**Comment by Piedone** [comment]
Thanks for sharing!
