### ISSUE TITLE
AlterAsync doesn't support named parts like Alter does

### ISSUE THREAD

**Issue by AydinE** [OrchardCMS/OrchardCore#13458]
### Describe the bug
We are running into an issue where we are trying to use AlterAsync from one of our custom API controllers.
It seems like it's not possible to get a named BagPart the same way as you can with Alter.

**Edit**: Refering to Alter in OrchardCore.ContentManagement.ContentExtensions which takes a string name as an argument
https://github.com/OrchardCMS/OrchardCore/blob/c8b2954e038aaa54963b60bc6cfe193cfea54799/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs#L232

```c#
    /// <summary>Modifies a new or existing content element by name.</summary>
    /// <param name="contentElement">The <see cref="T:OrchardCore.ContentManagement.ContentElement" />.</param>
    /// <param name="name">The name of the content element to update.</param>
    /// <param name="action">An action to apply on the content element.</param>
    /// <typeparam name="TElement">The type of the part to be altered.</typeparam>
    /// <returns>The current <see cref="T:OrchardCore.ContentManagement.ContentElement" /> instance.</returns>
    public static ContentElement Alter<TElement>(
      this ContentElement contentElement,
      string name,
      Action<TElement> action)
      where TElement : ContentElement, new()
    {
      TElement element = contentElement.GetOrCreate<TElement>(name);
      action(element);
      contentElement.Apply(name, (ContentElement) element);
      return contentElement;
    }
```

### To Reproduce
1. Create a named bagpart on any contentitem
2. Create an API controller that does some action to alter a BagPart on the contentitem.
3. When using the alter method like below everything works fine.
4. When using the AlterAsync method like below it actually just creates a new BagPart on the contentitem

### Expected behavior
We would expect to be able to call AlterAsync the same way as Alter
```c#
contentItem.Alter<BagPart>("NamedBag", x =>
{
    // Do things ...
});

////////////////////////////////////////////////

contentItem.AlterAsync<BagPart>("NamedBag", x =>
{
    // Do things ...
});
```

### Screenshots
N/A

**Comment by hishamco** [comment]
If you notice

https://github.com/OrchardCMS/OrchardCore/blob/6120831ce3c00ec7d4bc0598eab39ce4b409d424/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentItemExtensions.cs#L74-L81

https://github.com/OrchardCMS/OrchardCore/blob/6120831ce3c00ec7d4bc0598eab39ce4b409d424/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentItemExtensions.cs#L90-L97

both are same except the second one await for the action

**Comment by hishamco** [comment]
Did you try it with unamed part?

**Comment by AydinE** [comment]
Actually referring to this alter in ContentExtensions which takes a string name 
```c#
    /// <summary>Modifies a new or existing content element by name.</summary>
    /// <param name="contentElement">The <see cref="T:OrchardCore.ContentManagement.ContentElement" />.</param>
    /// <param name="name">The name of the content element to update.</param>
    /// <param name="action">An action to apply on the content element.</param>
    /// <typeparam name="TElement">The type of the part to be altered.</typeparam>
    /// <returns>The current <see cref="T:OrchardCore.ContentManagement.ContentElement" /> instance.</returns>
    public static ContentElement Alter<TElement>(
      this ContentElement contentElement,
      string name,
      Action<TElement> action)
      where TElement : ContentElement, new()
    {
      TElement element = contentElement.GetOrCreate<TElement>(name);
      action(element);
      contentElement.Apply(name, (ContentElement) element);
      return contentElement;
    }
```

**Comment by hishamco** [comment]
It's clear now

**Comment by ns8482e** [comment]
Usage is incorrect, Notice that AlterAsync is Func and not Action. Either use async/await on action or return task from your action.

```
contentItem.AlterAsync<BagPart>("NamedBag", async(x) =>
{
    // Do await able things ...
});
```

**Comment by hishamco** [comment]
@ns8482e it seems we forgot to add the `async` version for the named part, the one I referred to above accepts a content item not a named part

**Comment by ns8482e** [comment]
I guess @AydinE is missing async on AlterAsync

**Comment by hishamco** [comment]
@AydinE I pushed a PR, hope to merge it today as the triage meeting

**Comment by AydinE** [comment]
> @AydinE I pushed a PR, hope to merge it today as the triage meeting

Thanks so much for the quick responses and PR on this!
