### ISSUE TITLE
NumericFieldSettings.Edit.cshtml limits scale to max of 5

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/OrchardCore#13460]
Hi,

it is not possible to select a scale greater then 5 when editing a numeric field.
The value should not be fixed 5 but IMO NumericFieldSettings.Scale

![image](https://user-images.githubusercontent.com/1379660/227199746-1ddff8c6-91e9-4600-8d33-05d769582cf2.png)

Thanks,
Dieter

**Comment by hishamco** [comment]
It's a good option to move it into a settings with default value 5, @dpomt can you push a PR for that

One more thing we need to consider how many digits after decimal point can most databases support to avoid `OverflowException`

**Comment by hishamco** [comment]
I will check ...
