### ISSUE TITLE
ContentPart filter does not work in placement when the shape is a content field.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13476]
### Describe the bug
I want to create a content type called `Article` with multiple parts (i.e., `ArticleInfoPart`,`ArticleDatesPart`, and `ArticleSource`)

The part `ArticleInfoPart` has the following fields
- Good **BooleanField**
- ShouldAlwayBeVisible **TextField**
- AnotherText **TextField**
- When **DateField**

The part `ArticleDatesPart` has the following fields
- SomeOtherDate **DateField**

The part `ArticleSource` has the following fields
- Source  **TextField**

I want to create a placement rule that would hide all `TextField` field from being visible using `Detail` mode from the `ArticleSource` So I added the following in `placement.json` file

```json
{
  "TextField":[
    {
      "place":"-",
      "displayType":"Detail",
      "differentiator":null,
      "alternates":null,
      "wrappers":null,
      "shape":null,
      "contentType":[
        "Article"
      ],
      "contentPart":[
        "ArticleSource"
      ]
    }
  ]
}
```

However, that above rule hid ALL `TextField` from all the parts on the `Article` content type. I am expecting to hide `Source` field since that is the only text-field on the `ArticleSource` part.

I tried the same to do the same thing by hiding this time the `DateField` from `ArticleDatesPart` part only. Again, this hid all the `DateField` from all parts not just from the `ArticleDatesPart` part as expected.

```json
{
  "DateField":[
    {
      "place":"-",
      "displayType":"Detail",
      "differentiator":null,
      "alternates":null,
      "wrappers":null,
      "shape":null,
      "contentType":[
        "Article"
      ],
      "contentPart":[
        "ArticleDatesPart"
      ]
    }
  ]
}
```
I was able to hide one field at a time by specificity differentiator. but this isn't good approach specially if there are lots of fields.

Here is how I specified differentiator 

```json
[
  {
    "place": "-",
    "displayType": "Detail",
    "differentiator": "ArticleSource-SomeOtherDate",
    "wrappers": null,
    "shape": null,
    "contentType": [
      "Article"
    ]
  }
]
``` 
### To Reproduce
1. Start a new tenant or use existing tenant.
2. Import the following recipe
```json
{
  "steps": [
    {
      "name": "Feature",
      "enable": [
        "OrchardCore.Admin",
        "OrchardCore.ContentTypes",
        "OrchardCore.Contents",
        "OrchardCore.Title",
        "OrchardCore.Placements"
      ]
    },
    {
      "name": "ContentDefinition",
      "ContentTypes": [
        {
          "Name": "Article",
          "DisplayName": "Article",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true,
              "Draftable": true,
              "Versionable": true,
              "Securable": true
            }
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "Article",
              "Name": "Article",
              "Settings": {}
            },
            {
              "PartName": "ArticleInfoPart",
              "Name": "ArticleInfoPart",
              "Settings": {}
            },
            {
              "PartName": "ArticleSource",
              "Name": "ArticleSource",
              "Settings": {}
            },
            {
              "PartName": "TitlePart",
              "Name": "TitlePart",
              "Settings": {}
            },
            {
              "PartName": "ArticleDatesPart",
              "Name": "ArticleDatesPart",
              "Settings": {}
            }
          ]
        }
      ],
      "ContentParts": [
        {
          "Name": "ArticleSource",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true
            }
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "TextField",
              "Name": "Source",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Source",
                  "Editor": "PredefinedList"
                },
                "TextFieldSettings": {},
                "TextFieldPredefinedListEditorSettings": {
                  "Options": [
                    {
                      "name": "First",
                      "value": "first"
                    },
                    {
                      "name": "Second",
                      "value": "second"
                    }
                  ]
                }
              }
            }
          ]
        },
        {
          "Name": "ArticleInfoPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true
            }
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "BooleanField",
              "Name": "Good",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Good?",
                  "Position": "0"
                }
              }
            },
            {
              "FieldName": "DateField",
              "Name": "When",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "When",
                  "Position": "3"
                }
              }
            },
            {
              "FieldName": "TextField",
              "Name": "ShouldAlwayBeVisible",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "ShouldAlwayBeVisible",
                  "Editor": "TextArea",
                  "Position": "1"
                },
                "TextFieldSettings": {}
              }
            },
            {
              "FieldName": "TextField",
              "Name": "AnotherText",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "AnotherText",
                  "Position": "2"
                }
              }
            }
          ]
        },
        {
          "Name": "ArticleDatesPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true
            }
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "DateField",
              "Name": "SomeOtherDate",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Some Other Date"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "name": "content",
      "data": [
        {
          "ContentItemId": "4kteqej1wh5x1xz72v4hftn9ch",
          "ContentItemVersionId": "4yc1y1qb6pyhwyyhcn2209a0n4",
          "ContentType": "Article",
          "DisplayText": "Some title for this article",
          "Latest": true,
          "Published": true,
          "ModifiedUtc": "2023-03-27T22:01:32.0301177Z",
          "PublishedUtc": "2023-03-27T22:01:32.0387401Z",
          "CreatedUtc": "2023-03-27T21:57:41.9597296Z",
          "Owner": "48aty9sqhkjab37kwhpr552cxt",
          "Author": "malhayek",
          "Article": {},
          "ArticleInfoPart": {
            "Good": {
              "Value": true
            },
            "When": {
              "Value": "2023-03-14T00:00:00Z"
            },
            "ShouldAlwayBeVisible": {
              "Text": "This text should always be visble"
            },
            "AnotherText": {
              "Text": "this is a second text that should not be visible on the front end"
            }
          },
          "ArticleSource": {
            "Source": {
              "Text": "first"
            }
          },
          "TitlePart": {
            "Title": "Some title for this article"
          },
          "ArticleDatesPart": {
            "SomeOtherDate": {
              "Value": "2023-03-30T00:00:00Z"
            }
          }
        }
      ]
    }
  ]
}
```

3. add `placement.json` file with the following json
```
{
  "TextField":[
    {
      "place":"-",
      "displayType":"Detail",
      "differentiator":null,
      "alternates":null,
      "wrappers":null,
      "shape":null,
      "contentType":[
        "Article"
      ],
      "contentPart":[
        "ArticleSource"
      ]
    }
  ]
}
```
5. Alternatively to step 3 you may add the following placement rule to by going to **Dashboard** >> **Design** >> **Placements** >> **Add Placement**
   - SahepType: TextField
   - Placement rule 
```json
[
  {
    "place": "-",
    "displayType": "Detail",
    "wrappers": null,
    "shape": null,
    "contentType": [
      "Article"
    ],
    "contentPart": [
    	"ArticleSource"  
    ]
  }
]
```

### Expected behavior
I am expected all the `TextField` to not show up when I navigate to `/Contents/ContentItems/4kteqej1wh5x1xz72v4hftn9ch`

**Comment by ns8482e** [comment]
I guess the ContentPart and contentType rule applies with OR meaning if you have defined multiple contentType (A, B) the placement rule applies if content type is either A or B. Similar logic is applied for ContentPart.

To apply AND logic you should use differentiator. That allows you to combine (content-type/part-name) (content-part/field-name)

**Comment by MikeAlhayek** [comment]
@ns8482e I do not see OR logic in the code. A LINQ extension called Aggregate is called on all filters.

I believe filters should be using AND logic to filter down shapes. Alternatively, we can add a logic operator in the placement that allow us to specify AND or OR logic. But, I do not think we are using OR logic here.

**Comment by ns8482e** [comment]
@MikeAlhayek I believe it's inherited logic from oc 1

https://github.com/OrchardCMS/OrchardCore/blob/afc99f106b97b50439f73636bd9c124923d41311/src/OrchardCore/OrchardCore.ContentManagement.Display/Placement/ContentPlacementNodeFilterProviders.cs#L58

**Comment by MikeAlhayek** [comment]
@ns8482e the code you shared looks at the contentTypes array and check if the given contentType is contained in that array "this is fine". If you look at the `ShapePlacementStrategy`, you'll see how all the matches filters are aggregated which used `AND` logic. ContentPart if a filter and the ContentType is another filter. All filters are computed into an `AND` logic to select the shape before placement is applied.

https://github.com/OrchardCMS/OrchardCore/blob/4afaae8dcb14a2ed3755b6c5a491d89de1199802/src/OrchardCore/OrchardCore.DisplayManagement/Descriptors/ShapePlacementStrategy/ShapePlacementParsingStrategy.cs#L88

**Comment by ns8482e** [comment]
As per my previous comment Logic is same for all ContentPart and other filter / predicate match uses any

For content part see https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.ContentManagement.Display/Placement/ContentPlacementNodeFilterProviders.cs#L26

I believe use of any is by design inherited from orchard Cms 1.x

**Comment by MikeAlhayek** [comment]
The logic you shared is the filter for the contentParts. That filter apply contains logic on the contentPart array not on all filters provided in the placement

**Comment by ns8482e** [comment]
Correct, I didn't share code for all filter rules - just sharing the logic how it's implemented. 

The logic is same for all other filter predicate, match is based on Any (ie OR logic).

**Comment by sebastienros** [comment]
Maybe "TextField" can be replaced with "*" to hide all shapes that the filter matches, so the shape types are not repeated in the placement file.

**Comment by MikeAlhayek** [comment]
@sebastienros `*` does not work. Please check the PR #13505 I submitted which fixes this issue.

When multiple rules are set, `ALL` of the have to be true. If one provides multiple `contentTypes` or `contentParts`, we still apply `ANY` logic to check if the array of `contentTypes` contains the content type being displayed OR if the array of `contentParts` contains the content-part being displayed. 

```
{
  "TextField":[
    {
      "place":"-",
      "displayType":"Detail",
      "differentiator":null,
      "alternates":null,
      "wrappers":null,
      "shape":null,
      "contentType":[
        "Article",
        "Blog"
      ],
      "contentPart":[
        "ArticleSource",
        "BlogSource"
      ]
    }
  ]
}
```

So in the above example, we hide the shape when ALL the following rules were met
- displayType is **Detail**
- contentType either **Article** or **Blog**
- contentPart is **ArticleSource** or **BlogSource**

**Comment by jtkech** [comment]
The contentType and contentPart filters are applied at the contentItem level, they match any element whose Type is in the provided types AND , if parts are provided, having a part among the provided parts.

Then the placements are applied on the selected items, okay to be Type specific as any item only has one Type, but to be Part specific, as @ns8482e said and as you tried, you need to use the `differentiator`.

> I was able to hide one field at a time by specificity differentiator. but this isn't good approach specially if there are lots of fields.

If you only have a few fields to hide/render that's okay with the `differentiator`, but yes if you have both many fields to hide and many fields to render it is a little annoying, but most of the time that's okay.

So the current behavior is to first select items and then apply placements on fields for which we can provide `differentiators`. I understand the goal but changing the behavior will no longer allow for example to hide a field of a given Part1 (e.g. using the differentiator) but only for items having another Part2.

What I did on my side is a custom `IShapeTableHarvester` that parses placement files (with custom names) where the root properties are contentTypes, so that when under a given contentType we don't have to specify it multiple times, only the `differentiators`, can be used alongside the regular placement files.

**Comment by MikeAlhayek** [comment]
@jtkech not sure I fully understand your comment.

But, based on my understanding to the code, we first check if the current item being displayed matches the DisplayType.

Second, we match the differentiator. 

Third, we evaluate all `IPlacementNodeFilterProvider`, when all of match, we apply the placement.

If I understand your comment, you are saying that the contentParts filter is useless without a differentiator.

I think the idea with filters is to be able to select any shape you want and control its position. If this isn't the case, I am wondering why do we have contentParts filter?

**Comment by jtkech** [comment]
>  I am wondering why do we have contentParts filter?

Personnaly I never used it, but it is just a filter to only includes items having a part from a given set.

You can filter items by Type(s) and/or you may want to filter items by types having Part(s).

**Comment by MikeAlhayek** [comment]
@jtkech so my understanding is correct. Based on the original issue here, shouldn't any text-field on the Source part become hidden?

**Comment by jtkech** [comment]
Based on your first placements example, all Text fields of all Parts will be hidden, but this only on items of Type Article and having an ArticleSource Part.

**Comment by MikeAlhayek** [comment]
I guess this is what I am struggling to understand. Why would all TextFiels on Article content item be hidden if I am using another filter to also ensure there is a contentPart called ArticleSource

```json
{
  "TextField":[
    {
      "place":"-",
      "displayType":"Detail",
      "differentiator":null,
      "alternates":null,
      "wrappers":null,
      "shape":null,
      "contentType":[
        "Article"
      ],
      "contentPart":[
        "ArticleSource"
      ]
    }
  ]
}
```

**Comment by jtkech** [comment]
> contentPart (Optional): A single ContentPart or an of array of ContentParts that the content item from which the shape was built should contain.

It is used to filter the content items on which the placements will be applied, not to filter the parts on which the placements will be applied on these filtered content items.

**Comment by MikeAlhayek** [comment]
The shape is TextField which is built from a contentItem of an Article type. The statement from the docs to me means, if the contentItem contains a part called ArticleSource, it'll be selected as long as the other filters are also met.

I am not sure what I am missing here.

**Comment by MikeAlhayek** [comment]
I think I get it now. Since The source part is always attached to the Article type, this will always be true.

I think what I need is to probably add a new filter called something like "belongsToPart" which check the definition of the content type to see if the field belongs to a given part. Otherwise use a differentiator

**Comment by jtkech** [comment]
Yes exactly, maybe like the contentPart filter but by retrieving the current contentPart (if any and if possible) from the placement context, this in place of the contentItem.
