### ISSUE TITLE
Do not auto create dummy content item when AdminDashboard feature is enabled

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13485]
### Is your feature request related to a problem? Please describe.
When `AdminDahsboard` feature is enabled for the first time, for some reason we create a dummy dashboard item. There is no way to avoid this for new tenants currently. 

### Describe the solution you'd like
I don't think adding a content item by default is a good idea because the admin will almost always have to remove it. Remove the `Orchard Core` admin widget from the recipe.

**Comment by hishamco** [comment]
I think @agriffard created that module, I'm sure there's a reason for shows some default HTML widgets

**Comment by MikeAlhayek** [comment]
@ns8482e a good place for an ready state is a startup recipe not a sub-recipe that is called from a migration. I want to create a recipe that provides my own dashboard widgets by default. I can't do exactly that because I'll always will have to remove the default widget manually. If we feel we need to have a placeholder, then we may want to add it to an existing startup recipe or add a new startup recipe with a Dashboard default.

**Comment by ns8482e** [comment]
IMHO dashboard feature is Orchard Core's Admin Feature(not for front end or startup recipes) Enabling this feature adds HTML dashboard with content specific to orchard core Cms. So default content item should not be removed. If customization is needed you can always customize using editor or using custom recipe.

**Comment by MikeAlhayek** [comment]
A recipe is something you use to create a full site (i.e., Front end, admin, features, default content,settings....).

When you providing a SaaS product, you want to deliver a complete product "as much as possible" out of the box. So if my recipe create the site with multiple admin dashboards, why should I have to also show the default/placeholder widget? I think default contents should be part of optional recipe. Either a startup recipe or a partial recipe that gets called as needed but not forced upon you. If we at least hardcode the content item id, we can probably delete the content by its hard codes id from a recipe.  Either way, I strongly believe this should be removed

**Comment by hishamco** [comment]
I think it was a sample use case for how the dashboard widgets should look, maybe it needs a better design.

> If we at least hardcode the content item id, we can probably delete the content by its hard codes id from a recipe. Either way, I strongly believe this should be removed

While the feature management doesn't have sort of checklist for some default settings, the solution either leave it as its or remove it

**Comment by ns8482e** [comment]
You are correct in your point of view, where you would like to make enhancements on top of what orchard core cms. 

At the other end, orchard core cms is not just saas framework rather complete ready to use cms application. The OOTB dashboard content html item is ready to use dashboard is for non technical cms users.

When the ask here is to remove OOTB dashboard item feature, means to remove a dashboard feature for non techie cms users.

**Comment by MikeAlhayek** [comment]
I still believe that the default content should be part of a recipe like the blog recipe where the user gets a starting point. But we should have a way to opt out default content.

**Comment by ns8482e** [comment]
Correct - request is genuine, removing feature for non tech users from module is not good idea. As after this change, enabling the feature does nothing and will show blank dashboard page that is confusing to CMS non-developer end users

**Comment by MikeAlhayek** [comment]
What do you suggest we do then?

**Comment by myetginbal** [comment]
I kinda agree with @MikeAlhayek, the default content may be a part of a pre-defined recipe but not a blank one. Afaik, the dashboard item is still being automatically generated even after you import a custom recipe that does not contain it. I believe, at least it should not show up after a custom recipe is imported.

**Comment by ns8482e** [comment]
One idea that I think of is to repurpose current Admin Dashboard to provide tools to manage 
Dashboard and create another module like orchard core cms dashboard - that will create dashboard content items specific to OOTB orchard core cms - with dependency on current admin dashboard - and enabled by default by OOTB setup recipes. 

As SaaS provider you can exclude orchard cms dashboard from your custom saas recipe.

**Comment by hishamco** [comment]
@MikeAlhayek we could do this on the next triage meeting

**Comment by sebastienros** [comment]
During the meeting we suggested to create a sample recipe with the current content. This can then be called independently of the enable action.

**Comment by MikeAlhayek** [comment]
@sebastienros a recipe was added. I also update the 1.7 release notes with the changes in the PR
