### ISSUE TITLE
StackExchange.Redis Outdated

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#13494]
StackExchange.Redis 2.2.4 will be used (due to Microsoft.Extensions.Caching.StackExchangeRedis) but there have been [important fixes](https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes) over the many releases since then.  Microsoft.Extensions.Caching.StackExchangeRedis has the version requirement as >= 2.2.4 so running a more recent version should work fine.  

Having a properly maintained explicit version should be considered as this is a very important dependency for larger-scale OC usage.

**Comment by MikeAlhayek** [comment]
@ShaneCourtrille you want to submit a PR for this?

**Comment by hishamco** [comment]
@jtkech your thought about this, while you worked on Redis? Shall we have a dependency on StackExchange.Redis?

**Comment by ShaneCourtrille** [comment]
@MikeAlhayek I can once @jtkech gives his opinion and we complete our own internal testing as we're making the change on our version.

**Comment by jtkech** [comment]
Looks good, I will look at it, I'm first working on #13531 ;)

**Comment by jtkech** [comment]
@ShaneCourtrille 

Okay, integrated in #13531 where we now reference the `2.6.104` version.

So if you try this branch, we will also see if it works well with this version.

**Comment by ShaneCourtrille** [comment]
We're going to start checking both changes out today.  Thanks!
