### ISSUE TITLE
TaxonomyField - change to allow easy customization of the display driver

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#13493]
I like to do a code change in the module `OrchardCore.Taxonomies` in the `Startup.cs` to allow eventually customization of the display driver.

I would like to change this lines of code from this:

https://github.com/OrchardCMS/OrchardCore/blob/afc99f106b97b50439f73636bd9c124923d41311/src/OrchardCore.Modules/OrchardCore.Taxonomies/Startup.cs#L72-L74

to this: 

```
services.AddContentField<TaxonomyField>()
                .UseDisplayDriver<TaxonomyFieldDisplayDriver>(d => string.IsNullOrEmpty(d))
                .AddHandler<TaxonomyFieldHandler>(); 
```

If is it ok I can prepare the PR.

Thank you.

**Comment by MikeAlhayek** [comment]
You can achieve the same thing by adding the following in your own module.
```
services.AddContentField<TaxonomyField>()
                .RemoveDisplayDriver<TaxonomyFieldDisplayDriver>
                .UseDisplayDriver<TaxonomyFieldDisplayDriver>(d => string.IsNullOrEmpty(d))
                .AddHandler<TaxonomyFieldHandler>(); 
```

**Comment by MikeAlhayek** [comment]
@PiemP can we close this issue?

**Comment by PiemP** [comment]
@MikeAlhayek if this change is not necessary for the community can be closed
