### ISSUE TITLE
Configure pass-trought for Nancy module

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#1350]
Hi,
If you activate the OrchardCore.Nancy module, all CMS url will return a 404 not found. Adding PassThroughWhenStatusCodesAre lets see Orchard CMS pages but there is an issue on login.

Have you planned that the Nancy module must be used on standalone? Or, is this behavior a bug?

[Nancy](https://github.com/NancyFx/Nancy/wiki/Hosting-nancy-with-owin):
> Nancy in an OWIN pipeline is, by default, terminating. That is, when it fails to resolve a handler or static content, it will complete the request and return a 404. Subsequent middleware will not be invoked.

```
namespace OrchardCore.Nancy
{
    public static class ModularApplicationBuilderExtensions
    {
        public static ModularApplicationBuilder UseNancyModules(this ModularApplicationBuilder modularApp)
        {
            modularApp.Configure(app =>
            {
                var contextAccessor =
                    app.ApplicationServices.GetRequiredService<IHttpContextAccessor>();

                app.UseOwin(x => x.UseNancy(no =>
                {
                    no.Bootstrapper = new ModularNancyBootstrapper(
                        new[] {
                            (IAssemblyCatalog)new DependencyContextAssemblyCatalog(),
                            (IAssemblyCatalog)new AmbientAssemblyCatalog(contextAccessor)
                        });
Added--->           no.PassThroughWhenStatusCodesAre(HttpStatusCode.NotFound);
                }));
            });

            return modularApp;
        }
    }
}

```

**Comment by infofromca** [comment]
stripe off this module, IMO

**Comment by sebastienros** [comment]
Yes, we are removing it. It's not maintained anymore and the devs have started another project. But it's nice to show that the modular framework can also work without something else than MVC.
