### ISSUE TITLE
Backend workflows pages takes several seconds to load

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore#13525]
### Describe the bug
It takes several seconds to load the `/Admin/Workflows/Types` and `/Admin/Workflows/Types/{TypeId}/Instances` pages when there is a fairly large amount (testing size: 500_000) rows in WorkflowIndex.

In `WorkflowTypeController` line 129, the following query is running, which goes through the whole table of WorkflowIndex to then calculate (group by) in the code how many workflows are there per each type.
```sql
SELECT * FROM [WorkflowIndex] AS [WorkflowIndex_a1] WHERE [WorkflowIndex_a1].[WorkflowTypeId] IN ('4vn35yvjtmrft5ng3pedsexb5r', '40ka9pz8q3d0945vg5v4yd08nq', '4t07avan1z089vmk9eyd2mchx0', '4qyjq7q61fehhvy5frce3wrvmb', '4syp57rcmh4mp5shfr5s24zedw', '40w32fg0e9dbhvme6w8qbbewc4', '4yg9wg6haxtf0t8b1fskqjvxx9', '4j5kp2z01s98c47ytxmh1wbg4b', '4t3ktqsnk2e706dt47pzkcb245', '4f6pje7pgg5gv00hxy33rb2rme') 
```

In `WorkflowController` line 124 with the `await query.CountAsync()` it is for the same purpose but for only one workflow type, but this uses some additional joins which makes it even slower.

Create a ReduceIndex for counting the number of workflow items just like UserByRoleNameIndex and use that instead of the whole table of WorkflowIndex.

### To Reproduce
Have a fairly large number of finished workflows. Load the workflows page, or the type-specific workflow item list page. See that it takes several seconds to load. Use miniprofiler to detect the long taking query.

### Expected behavior, suggestion
Create a ReduceIndex for counting the number of workflow items just like UserByRoleNameIndex and use that instead of the whole table of WorkflowIndex.

Add migration step that generates the ReduceIndex indexes for the already existing workflow items.

**Comment by wAsnk** [comment]
I'm working on this currently in my fork and I'll open a PR soon.

I'm stuck with generating `ReduceIndex` for the already existing workflow items. When I try to save the workflow with `ISession.Save` first it gets reduced correctly, but then it gets deleted.
What I found is that YesSql will delete and then insert updated documents, so whenever I try to save the workflow with the ISession.Save function the deletion will trigger the `ReduceIndex` provider `Delete` method.

**Comment by sebastienros** [comment]
I believe we should not count, or use the paging setting that allows to skip counting and generate a pager based on the max count. Or just prev/next pagers.

**Comment by wAsnk** [comment]
Looks like this has not been released yet, do I see that right?

**Comment by Piedone** [comment]
While the involved controllers have seen changes since then, it was. You can check out the source that's 1.8 [under the tagged commit](https://github.com/OrchardCMS/OrchardCore/tree/b8d6d960aa387e9e7fcaffd39ea293fc5537c683).

**Comment by wAsnk** [comment]
Oh yeah, it was already in 1.7 but I didn't see it in the changelog... My bad.
