### ISSUE TITLE
Rendering liquid templates fails when the view doesn't have a model

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1353]
The user will get an ugly 502 Bad Gateway error.

This is a particular problem for the `NotFound` template, but will happen for any view that does not have a model.

**Comment by sebastienros** [comment]
You mean when the model is `null` ?

**Comment by paynecrl97** [comment]
Yes. I'm pushing a fix now

**Comment by paynecrl97** [comment]
Oh I think I misunderstood your question. But the answer is still yes- if the model is null, it'll throw a NRE which causes this issue. Additionally, if a model is not provided (i.e. controller returns `View("MyViewName")`, the same NRE will be thrown.

The fix I pushed handles both cases, and if the model could potentially be null, the consuming view will need to do something like this:

```
{% if Model %}
    Model is not null
{% else %}
    Model is null
{% endif %}
```
