### ISSUE TITLE
WidgetList Part does not work OC 1.5.0

### ISSUE THREAD

**Issue by smemis** [OrchardCMS/OrchardCore#13533]
### To Reproduce
1. I add Page Content Type to WidgetList Part.
2. When I click on the + icon of the WidgetList Part on the page that opens to create a new Page content item, the widget selected from the popup that opens is not added, I get a 500 error

### Expected behavior
It should work as in Flow Part

### Screenshots
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/4637285/230564999-79e8fd61-4c65-4a64-89f2-829023e39027.png">

**Comment by MikeAlhayek** [comment]
@smemis I tried this with the latest 1.6 previews and I do not see any issues. You may want to click on the `Netword` tab, and inspect the server response for additional info. Also you may be able to inspect the log file to see if you can give us more clues on the cause.

**Comment by smemis** [comment]
> @smemis I tried this with the latest 1.6 previews and I do not see any issues. You may want to click on the `Netword` tab, and inspect the server response for additional info. Also you may be able to inspect the log file to see if you can give us more clues on the cause.

yes there is no problem with 1.6.0-preview-17368. I'll be using the 1.6.0-preview-17368 until it's released.
@MikeAlhayek Thank you for your interest and help.
