### ISSUE TITLE
invalidOperationException: Scheme already exists: OpenIdConnect

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#13541]
### Describe the bug
If Azure Active directory module and Open Id Client module both enabled got error

invalidOperationException: Scheme already exists: OpenIdConnect

### To Reproduce
update to latest nuget
enable openid
enabled azure ad login

### Screenshots

![image](https://user-images.githubusercontent.com/61165619/230850914-ddb43a58-ad60-41ca-b937-e0122fa7a34f.png)

**Comment by sebastienros** [comment]
Could use some of your help to fix it if you have some time.

**Comment by MichaelPetrinolis** [comment]
@sebastienros sure, I will try to send a fix during the weekend

**Comment by MichaelPetrinolis** [comment]
sent two PRs, one for release and one for main. 
@vitalybrandes  please give it a try if it fixes your issue.

**Comment by vitalybrandes** [comment]
> sent two PRs, one for release and one for main. @vitalybrandes please give it a try if it fixes your issue.

@MichaelPetrinolis Is it available on nightly nuget?

**Comment by MichaelPetrinolis** [comment]
It will be available as soon as it gets merged.
