### ISSUE TITLE
When a user has "AccessAdminPanel" but not to "AccessAdminDashboard", render AdminDashboard shape

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13548]
### Is your feature request related to a problem? Please describe.
Currently, when AdminDashboard feature is enabled, the `/admin` route is handled by `Index` action in `DashboardController` controller. This works great when the user has permission to `AccessAdminDashboard`. However when they don't, they get the generic fobid error message. 

In some case, we don't want to give the user access to the admin widgets, but want them to still access the admin dashboard.  In this case they will not be able to see the dashboard unless they type the exact path they want to access in the browser. 

Also, add `ViewContent` check to be able to allow some user to not view all widgets.

### Describe the solution you'd like
In the `DashboardController/Index` method, instead of returning `Forbid()` when `AccessAdminDashboard` is not granted, return `View("~/OrchardCore.Admin/Views/Admin/Index.cshtml")` which will simply render `AdminDashboard` shape.

**Comment by hishamco** [comment]
If the user has `AccessAdminPanel` but not `AccessAdminDashboard` the user should be able to access the admin site except the dashboard, but this is inconsistent IMHO because the default page in the admin after login is `AdminDashboard`, so the user will get 403 for an unknown reason

I suggest `AccessAdminDashboard` should depends on `AccessAdminPanel`

**Comment by hishamco** [comment]
> This will not allow us to handle a scenario of a user access the admin-panel without viewing the dashboard.

Could you please let me know what will happen if the user logged in?

**Comment by MikeAlhayek** [comment]
Currently if they don't have access to the dashboard, they get a 401. With the new PR, instead of 401 we just render the AdminDashboard shape.

You may want to try it out and then try the PR I submitted

**Comment by hishamco** [comment]
> Currently if they don't have access to the dashboard, they get a 401. With the new PR, instead of 401 we just render the AdminDashboard shape.

Looks good but from user's point of view it might think there's no dashboard that should be rendered that's why `401` make sense to me

Let us hear folks feedback ..

**Comment by MikeAlhayek** [comment]
Yes. The problem with returning a 401 is that the `/admin` is the home route of the dashboard. It just can't throw an error. Typically users will click on "Dashboard" from the front end to end up at /admin. you don't want to send the user to a 401. this is just a bad user experience. Since we have 2 modules that control the `/admin` route, we should handle it in a way that does not return 401 as the user may have other permission in the admin.

**Comment by ns8482e** [comment]
Shouldn't AccessAdminPanel should allow to dashboard page?

**Comment by MikeAlhayek** [comment]
@ns8482e yes and it does. The dashboard landing page is `/admin` and if permitted if you have `AccessAdminDashboard` permission. This landing page renders `AdminDashboard` by default.

```
@await DisplayAsync(await New.AdminDashboard())
```

However, when one enables the DashboardWidgets feature the same dashboard landing page `/admin` now requires `AccessAdminDashboard`. So if you have  `AccessAdminDashboard` permission but not `AccessAdminDashboard`, you get a 401 when you go to `/admin`. It's like giving someone access to all your site pages but not giving them access to the main page.
