### ISSUE TITLE
Make OpenId rolling tokens configurable on administration menu

### ISSUE THREAD

**Issue by jardg** [OrchardCMS/OrchardCore#1355]
#1327 
Useful to revoke the refresh token on the refresh flow and get a new one.

**Comment by PinpointTownes** [comment]
As discussed in https://github.com/OrchardCMS/OrchardCore/issues/1327, this is a simple change that would make a perfect first contribution. Do you want to take it? :smile:

**Comment by jardg** [comment]
Sure.I'll try to pr soon
