### ISSUE TITLE
AdminDashboard widgets are not scrollable when the content is long

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13550]
### Describe the bug
Currently, the AdminDashobard widgets are set to hide any horizontal and vertical overflow. This works good when you can control the content of your widget based on that you can specify the best height/width of each widget.

Some times you may want to create a widget without being able to control the length. For example, recent contents/post, most viewed contents, etc. All these example of a widget with uncontrollable content. In that case, it does not make sense to hide the overflow content vertically. We can still hide the horizontal overflow and the widget since that is something each widget can design for. But, the vertical overflow should be set to auto.

### To Reproduce
1. Create a widget that list that last 10 contentItems. and make the size and the width of the widget 1 x 1.

### Screenshots

![image](https://user-images.githubusercontent.com/24724371/231253142-da206a96-2bb2-418a-9a90-8a7e81dd3a58.png)

And as you can see below, when setting the vertical overflow to auto, we get a scroll bar for the widgets when the content is larger than expected 

![image](https://user-images.githubusercontent.com/24724371/231253497-1a76b3cb-01f4-4af3-857f-e1f730c255a4.png)

**Comment by hishamco** [comment]
I assume this because each widget takes a certain height and width

/cc @agriffard

**Comment by MikeAlhayek** [comment]
The height/widget are not the issue here since we are using grid by default. I submitted PR #13552 which fixes this issue
