### ISSUE TITLE
Unable to find package OrchardCore.Localization.Abstractions with version (>= 1.6.0)

### ISSUE THREAD

**Issue by ngoquoctoandev** [OrchardCMS/OrchardCore#13564]
### Nearest version: 1.5.0

![image](https://user-images.githubusercontent.com/78490340/232052557-d3f5a176-9f34-4f33-a3e5-77094e07cd8f.png)

**Comment by TehNolz** [comment]
Just ran to this as well. Seems the latest version of the Abstractions package on nuget is still on 1.5.0, while the Core package requires 1.6.0.

**Comment by hishamco** [comment]
Strange!!

**Comment by ngoquoctoandev** [comment]
I just added an image to the notification. I have double checked the OrchardCore.Localization.Abstractions package on nuget is still not updated, the latest version is currently 1.5.0 published 5 months ago

**Comment by MikeAlhayek** [comment]
Yes. the 1.6 release failed midway and not all 1.6 packages are available on nuget. 

> error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).

@sebastienros @Skrypt @jtkech I am not sure what is the best approach to fix this. I am trying to re-run the job again and see if it'll work this time around

**Comment by jtkech** [comment]
We may need to re-generate the Nuget API key

**Comment by ns8482e** [comment]
@sebastienros nuget package deploy has failed

**Comment by MikeAlhayek** [comment]
It's just strange how the API key worked for some packages and then stopped.

**Comment by jtkech** [comment]
Yes, maybe something else

**Comment by sebastienros** [comment]
I re-created the API key and restarted the job, but it was brand new from another requirement. I double-checked that the key allows the creation of new packages (it's failing on the new Search modules). Note that this is the exact same issue that we had on translations, and I had to upload the packages manually for them to be created.

**Comment by sebastienros** [comment]
I think I found the reason ... working on it

**Comment by jtkech** [comment]
Would it be a permission issue with a new referenced package?

**Comment by sebastienros** [comment]
The OrchardCore prefix is owned by my account and the API keys were made for the "Orchard" organization. I believe the API key hence doesn't have the rights to add new packages on this prefix. I asked the nuget team to add Orchard to the owners of the prefix.

**Comment by jtkech** [comment]
Ah okay

**Comment by hishamco** [comment]
Woohoo, all the OC packages are now 1.6

Thanks for `SystemUpdate` feature that notify me :)

**Comment by hishamco** [comment]
I just notice that there are some packages that still target `1.5.0` including the themes

**Comment by vipwan** [comment]
It doesn't seem to be solved yet 😿

**Comment by sebastienros** [comment]
After so many attempts it's now fixed
