### ISSUE TITLE
AutoroutePart.SetHomepage set to false for homepage

### ISSUE THREAD

**Issue by mwentz** [OrchardCMS/OrchardCore#13567]
When I access Model.ContentItem.Content.AutoroutePart.SetHomepage in a Content.chstml template or do a content export, the homepage's value for that field is false.

I tried changing the homepage and also disabling and reenabling the Home Route module, neither fixed the problem. I also tried refreshing the path which also did not fix the problem.

In addition, I exported the page, updated the SetHomePage field to true, made a content change, and imported the recipe. The content change was there, but the SetHomepage field was still false.

I am using the latest 1.5.0 release.

**Comment by mwentz** [comment]
Got it. If that's the case, how can I target the homepage for content differences? The only way I have been able to figure out so far would be with Widget Layers, but as far as I can tell those can only be placed in zones in the Layout.cshtml file but I need to do this at a Content.cshtml level.

**Comment by jtkech** [comment]
You can check the current `context.Request.Path.Value`, if it is empty or equal to `/`.

**Comment by mwentz** [comment]
Thank you @jtkech, I was hoping to not have to fall back to this since the homepage always has two URLs (e.g. "/" and "/home-page"). For my uses this is a very minor concern and I can work with it, but overall I think this is problematic behavior.

I was trying to figure out if there is any way to access HomeRoute > contentItemId from a template file, but I can't figure out a way to do it.

I can imagine using something like:
`@if (Site.HomeRoute.ItemId = Model.ContentItem.Id) {  }`

But I can't find any way to do that.

**Comment by jtkech** [comment]
@inject ISiteService SiteService

    @{
        var homeRoute = (await SiteService.GetSiteSettingsAsync()).HomeRoute;
        var homeContentItemId = homeRoute["contentItemId"]?.ToString();
    }

    @if (Model.ContentItem.ContentItemId == homeContentItemId)

**Comment by mwentz** [comment]
Yes, that's the ticket! Thank you so much for all the help!
