### ISSUE TITLE
Roles list are empty even that defined in permission.cs

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#13575]
Moved from 1.5 to 1.6 
Clean start of the app.
Different roles defined in custom module
No roles in recipe
while app start up, no roles appear in the roles list:

![image](https://user-images.githubusercontent.com/61165619/233075890-36ea0335-b5a9-4934-b7dd-d1b8e3696ffd.png)

if i add single role to recipe its there!

**Comment by MikeAlhayek** [comment]
@vitalybrandes in your setup recipe you'll just need to define which roles you want to use for example,

```
    {
      "name": "Roles",
      "Roles": [
        {
          "Name": "Administrator",
          "Description": "Administrator",
          "Permissions": []
        },
        {
          "Name": "Moderator",
          "Description": "Moderator",
          "Permissions": []
        },
        {
          "Name": "Editor",
          "Description": "Editor",
          "Permissions": []
        },
        {
          "Name": "Author",
          "Description": "Author",
          "Permissions": []
        },
        {
          "Name": "Contributor",
          "Description": "Contributor",
          "Permissions": []
        },
        {
          "Name": "Authenticated",
          "Description": "Authenticated",
          "Permissions": []
        },
        {
          "Name": "Anonymous",
          "Description": "Anonymous",
          "Permissions": []
        }
      ]
    }
```

The fact that you are not explicitly setting permissions here, it'll load all the permissions defined by the permission providers for you.

**Comment by vitalybrandes** [comment]
I think that this part must get **BOLD** focus in documentation.

**Comment by MikeAlhayek** [comment]
@vitalybrandes we’ll try to highlight braking changes better next time. By I feel that everyone should be reading breaking changes notes prior upgrading.
