### ISSUE TITLE
Translation of some expressions of po files is not done correctly

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/OrchardCore#13579]
Hello to all
Translation of some expressions of po files is not done correctly1
For example, some error messages in the AsemanniliCore.Users.po file on the register page or login page are not translated correctly. like the phrase:
`msgctxt "AsemanniliCore.Users.ViewModels.RegisterViewModel"`
`msgid "Invalid Email."`

**Comment by sebastienros** [comment]
You can contribute to the localization file on this website: https://crowdin.com/project/orchard-core
