### ISSUE TITLE
@html.Partial + Partial Taghelper ignoring IViewLocationExpanderProvider

### ISSUE THREAD

**Issue by FreshRob** [OrchardCMS/OrchardCore#1358]
Version: 1.0.0-beta1-3667
Packages: 
- OrchardCore.Application.Mvc.Targets
- OrchardCore.Module.Targets
- OrchardCore.Mvc.Core

I have setup a custom IViewLocationExpanderProvider for my custom view location which works perfectly for getting views but does not work for partials.
The structure is Features\Controller\Tenant\.cshtml or Features\Controller\.cshtml

### When unable to find a view
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
Company.Program\Features\Home\TheTenant\Index.cshtml
Company.Program\Features\Home\Index.cshtml
Company.Program\Features\Index.cshtml
Company.Program\Features\Shared\TheTenant\Index.cshtml
Company.Program\Features\Shared\Index.cshtml
Company.Program\TagHelpers\Index\TheTenant\Index.cshtml
Company.Program\TagHelpers\Index\Index.cshtml
Company.Program\TagHelpers\Form\TheTenant\Index\Index.cshtml
Company.Program\TagHelpers\Form\Index\Index.cshtml
Company.Program\Index.cshtml
Company.Program\TheTenant\Index.cshtml
Packages\Company.Program\Features\Home\TheTenant\Index.cshtml
Packages\Company.Program\Features\Home\Index.cshtml
Packages\Company.Program\Features\Index.cshtml
Packages\Company.Program\Features\Shared\TheTenant\Index.cshtml
Packages\Company.Program\Features\Shared\Index.cshtml
Packages\Company.Program\TagHelpers\Index\TheTenant\Index.cshtml
Packages\Company.Program\TagHelpers\Index\Index.cshtml
Packages\Company.Program\TagHelpers\Form\TheTenant\Index\Index.cshtml
Packages\Company.Program\TagHelpers\Form\Index\Index.cshtml
Packages\Company.Program\Index.cshtml
Packages\Company.Program\TheTenant\Index.cshtml

### When unable to find a partial
InvalidOperationException: The partial view 'Partials/_HomeHeader.cshtml' was not found. The following locations were searched:
 
/Packages/Company.Program/Features/Home/Partials/_HomeHeader.cshtml

### Update
09-01-2017 4:16pm Works fine when requesting a partial in Features/Shared/_layout.cshtml

**Help would be greatly appreciated.**

### Code
```
 @Html.Partial("Partials/_HomeHeader.cshtml")
<partial name="Partials/_HomeHeader.cshtml"/>
```

`services.AddScoped<IViewLocationExpanderProvider, FeatureViewLocationExpanderProvider>();
`

```
 public class FeatureViewLocationExpanderProvider : IViewLocationExpanderProvider
    {
        private readonly IExtensionManager _extensionManager;
        private readonly ShellSettings _shellSettings;
        public FeatureViewLocationExpanderProvider(IExtensionManager extensionManager, ShellSettings shellSettings)
        {
            _extensionManager = extensionManager;
            _shellSettings = shellSettings;
        }
        public int Priority => 0;    
        public void PopulateValues(ViewLocationExpanderContext context)
        {
        }
        public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
        {
            var tenant = _shellSettings["Site"];
            if (tenant == null) throw new NullReferenceException("Tenant property Site cannot be null.");

            var extension = _extensionManager.GetExtension(context.AreaName);

            var start = Path.Combine(Path.DirectorySeparatorChar + extension.SubPath);

            return new List<string>
            {
                Path.Combine(start, "Features", "{1}", tenant , "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "Features", "{1}", "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "Features", "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "Features", "Shared", tenant , "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "Features", "Shared", "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "TagHelpers", "{0}", tenant,  "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "TagHelpers", "{0}", "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "TagHelpers", "Form", tenant, "{0}", "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "TagHelpers", "Form", "{0}", "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, "{0}" + RazorViewEngine.ViewExtension),
                Path.Combine(start, tenant, "{0}" + RazorViewEngine.ViewExtension)
            };
        }

    }
```

**Comment by sebastienros** [comment]
@jtkech in case you have nothing to look at

**Comment by jtkech** [comment]
Ok, no problem, i will take a look soon.

**Comment by jtkech** [comment]
First, for your tenant, i think it is better to use `_shellSettings.Name`.

So, i tried it 1st without any additionnal view locations.

    - Views
        - Controller
            - Action.cshtml
            - Partials
                - Test.cshtml

    @Html.Partial("Partials/Test.cshtml") // works

Then

    - Views
        - Controller
            - Action.cshtml
     - Shared
        - Test.cshtml

    @Html.Partial("Test.cshtml") // doesn't work
    @Html.Partial("Shared/Test.cshtml") // doesn't work
    @Html.Partial("../Shared/Test.cshtml") // works
    @Html.Partial("Test") // works (notice without file extension)

Then

    - Views
        - Controller
            - Action.cshtml
     - Partials
        - Test.cshtml

    @Html.Partial("Test.cshtml") // doesn't work
    @Html.Partial("Partials/Test.cshtml") // doesn't work
    @Html.Partial("../Partials/Test.cshtml") // works
    @Html.Partial("Test") // doesn't work

But if i add this location in our view location expander

    result.Add(extensionViewsPath + "/Partials/{0}" + RazorViewEngine.ViewExtension);

Then

    @Html.Partial("Test") // this now works

Then if i add this location in our view location expander

    result.Add(extensionViewsPath + "/Partials/{1}/{0}" + RazorViewEngine.ViewExtension);

Then

    - Views
        - Controller
            - Action.cshtml
     - Partials
         - Controller
            - Test.cshtml

    @Html.Partial("Test") // works

But the controller view might be in different locations, that's why we use a `/Shared` folder, but you can use another one e.g `/Partials` and relying on some logic ...

Where is physically located your partial view?

**Comment by hishamco** [comment]
@jtkech I think this has been answered, if no action is required please close it
