### ISSUE TITLE
Unable to move BagPart completely into a placement tab

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#13606]
### To Reproduce
1. Create a `Placement.json`
2. Arrange the `BagPart` to be located in a new tab
4. The `BagPart` is partially moved, the hint is still in the first tab

### Expected behavior
A `BagPart` moved into a new tab

**Comment by MikeAlhayek** [comment]
@hishamco try using ContentPart shape to target BagPart.

```

"ContentPart_Edit": [
    {
      "place": "Parts:5",
      "contentPart": "BagPart",
      "contentType": [ "YourContentType" ]
    }
]
```

**Comment by hishamco** [comment]
I'm using the following

```json
  "BagPart_Edit": [
    {
      "place": "Parts:2#Themes;0",
      "contentType": [
        "Course"
      ]
    }
```

Even I added `"contentPart": "BagPart",` nothing changed :(

**Comment by MikeAlhayek** [comment]
Try this instead

```
"ContentPart_Edit": [
    {
      "place": "Parts:2#Themes;1",
      "contentPart": "BagPart",
      "contentType": [ "Course" ]
    }
]
```

**Comment by hishamco** [comment]
Finally, it works :) A new type for today use Content_Part for all the part, then specify the part name using `contentPart`

**Comment by jtkech** [comment]
We are using the following with differentiators

    "BagPart_Edit": [
      {
        "place": "Parts:3",
        "differentiator": "Products",
        ...
      },
      {
        "place": "Parts:7",
        "differentiator": "Credits",
        ...
      }

**Comment by jtkech** [comment]
In a given content type you can only have one part of a given content part type, e.g. AliasPart.

Unless for a named part as the BagPart is, you can have multiple BagPart in a given content type.

In that case a Differentiator is used to differenciate them.

The differentiator can also be used for fields because a content type or part can have multiple fields of the same type, e.g. multiple TextField.

**Comment by MikeAlhayek** [comment]
@jtkech will that move the BagPart wrapper? I think it'll only move the BagPart but not the wrapper which contains the bag description when you use named part.

**Comment by jtkech** [comment]
I don't remember but we use it, but not from the last version, with 1.4.0 and recently 1.5.0. Hmm, but isn't the Description part of the `typePartDefinition`, only used when listing the parts of a content type?

Okay, just saw that you introduced `ContentPart-BagPart.Edit` in the `OC.Contents` module, hmm maybe better to have these dedicated shapes in their related modules.

Hmm `ContentPart__BagPart_Edit` is an alternate but the shape type is still `BagPart_Edit`, so it may work but not sure, would need to be tried.

Okay just tried, seems to work ;)

**Comment by MikeAlhayek** [comment]
Did you actually try it using a named part? Just curious. I had issues with it in the past. The only way I was able to get it to behave was by using ContentPart_Edit.

**Comment by jtkech** [comment]
Yes with the last version, with the BagPart named "Services" in the Agency Theme

**Comment by MikeAlhayek** [comment]
Great to know! Thanks
