### ISSUE TITLE
Trumbowyg editor breaks in full screen mode

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13614]
### Describe the bug
When trying to edit text in `Trumbowyg` editor using full-screen mode, it covers the menu but does not show the editor.

### To Reproduce
1. Create a creatable content type by adding HtmlPart with the `Trumbowyg` editor.
2. create to create content item of the content type.
3. In the Trumbowyg editor, click full-screen mode.

### Expected behavior
I expect to be able to edit/type in a very large editor that covers the entire screen

**Comment by mdameer** [comment]
@MikeAlhayek This issue no longer appears to be valid, I cannot reproduce it with the latest code on the main branch.

**Comment by MikeAlhayek** [comment]
Yes I fixed this issue when I upgraded TheAdmin theme to bootstrap 5.3. I guess we forgot to close this issue.

Thank you for noticing it. I'll close it.
