### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1363]
This issue is here to collect features and ideas about the Workflows module. Workflows will be ported form Orchard 1 to Orchard Core, but we should also take this opportunity to make it even better. Below is a list of features that I can think of right now, but feel free to add more ideas.

**New features**
- More control flow activities such as _For Each_ and _For_
- More HTTP activities to enable HTTP request handling
- Allow workflow instances to execute on any context, not just content items.
- Execute Workflow activity that allows a workflow to invoke other workflows
- Support multiple _Inputs_ and _Outputs_ of a workflow.
- Versioning (prevents halted workflow instances from breaking)
- Workflow Execution Tracing (with extensibility points for custom handlers)

See the [Workflows project](https://github.com/OrchardCMS/OrchardCore/projects/4) for recorded tasks and their status.

**Comment by giannik** [comment]
+1 for versioning. This was a pain in Orchard 1.
Ideally each content item instance attached with a workflow that is long
running will hold the version number of the workflow definition it started
with.
And will end with this version regardless of changes made  to the workflow
definition.
Is this what you had in mind ?
Giannis.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sebastienros** [comment]
A general remark, don't try to put too much at first. Iterate.

Is there a custom middleware to support http requests?

**Comment by sfmskywalker** [comment]
Exactly, that's how I think it should be implemented. Nice and easy.

**Comment by sfmskywalker** [comment]
@sebastienros Agreed, I won't implement calling workflows and versioning just yet, Regarding the HTTP requests, I'm using routing (associating paths with a controller a la autoroute) - do you think it would be better as a middleware? Might make sense.

**Comment by sebastienros** [comment]
Middleware is more lightweight. Unless you want to trigger on urls defined with parameters like route templates in MVC, "products/{id}" and let the engine detect it. But still it might be able to do it from a middleware. They are working on a feature that will help but it's not for 2.1.

**Comment by sebastienros** [comment]
Do you have a simple `Redirect` activity that returns a redirection? (url based on a liquid "token")

**Comment by sfmskywalker** [comment]
We currently have 2 HTTP Request activities:

- HTTP Request
- HTTP Request Filter

**HTTP Request** allows the user to specify any path. When a request comes in matching that path, the workflow executes. Semantically this is like a middleware executing on a request, so it does make sense to do this from a middleware.

**HTTP Request Filter** allows the user to specify a route (controller, action and area). When a request comes in matching that route, the workflow executes. Semantically (and technically) this is like an action filter.

**Comment by sfmskywalker** [comment]
Yes, we have an **HTTP Redirect** activity that allows the user to redirect to a path and even specify whether it should be a permanent (301) or temporary (302) redirect.

**Comment by sfmskywalker** [comment]
The Redirect URL is currently based on script, but I will update all activities to use liquid syntax instead.

**Comment by sfmskywalker** [comment]
Here is the Trello board with stuff I have on my list: https://trello.com/b/PCB2QeeF/orchard-core-workflows

**Comment by giannik** [comment]
Another interesting feature, which I have not found in any other workflow tool in the market , is the ability to Undo (rollback) a workflow that has executed. Usefull when you  are testing or realize that a workflow instance should not exist. This would be driven from the UI (like an undo button for each workflow instance). Now how would this be implemented ? I think if task can expose an IUndoable Interface so that activity author can supply the code logic when undo is called . So the workflow instance will execute backwards, calling each tasks IUndo implementation.  If its something you would consider adding in the core I can work on it , once the main workflow has been placed into dev branch.
Thanks.

**Comment by sebastienros** [comment]
@giannik no way, way too complex, and with so many caveats. Sending emails, script execution, http requests. This could work in a rudimentary WF module with a specific list of linear tasks, not in our case. @sfmskywalker don't even think about it.

**Comment by giannik** [comment]
yeah, I understand the complexities.
Maybe as a custom module.

**Comment by sfmskywalker** [comment]
😀
