### ISSUE TITLE
NLog Failed to create file appender.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#13634]
If multiple instances run on the same file system, adding `concurrentWrites = "true"` in `NLog.config` prevents from having a bunch of  `NLog Failed to create file appender`.

Can be fixed by #13540.

**Comment by jtkech** [comment]
> Already now you are getting a new log-file each day.

Good point, as a reminder can you add a comment in #13540?

**Comment by sebastienros** [comment]
> If multiple instances run on the same file system

What is the scenario where multiple instances use the same filesystem? 
- One machine, multiple Orchard processes from the same binaries?
- Multiple machines using a shared filesystem? This might be the case in Azure App Service with scale out option.

**Comment by jtkech** [comment]
> This might be the case in Azure App Service with scale out option.

Yes.

Note: I saw the "issue" while testing work on OC.Clusters where I run multiple instances.

**Comment by sebastienros** [comment]
I think that if this was for some kind of non-obvious topology or test then it shouldn't be a new default setting value, just a documentation to explain how to solve this issue in uncommon cases.

The same way we can use sqlite, but if it's multi-node then someone shouldn't, and we won't try to fix sqlite or how we use it to make it happen.

**Comment by jtkech** [comment]
Okay but yes I was thinking about the Azure scale out and thought it may be worth.

But I understand.

**Comment by sebastienros** [comment]
We might already have some options for Azure App Service, for instance in the docker image. OR when in App Service and ENV might already exist and we could dectect that. If not we could just have an extra doc paragraph to explain the recommendations.

**Comment by jtkech** [comment]
Okay

**Comment by sebastienros** [comment]
Example, last paragraph https://hub.docker.com/r/orchardproject/orchardcore-cms-linux/#!
