### ISSUE TITLE
Unexpected behaviour for exception handling in driver for Content Type

### ISSUE THREAD

**Issue by lucabertoni** [OrchardCMS/OrchardCore#13649]
### Describe the bug
Good morning,

I have recently started [a discussion (#13642)](https://github.com/OrchardCMS/OrchardCore/discussions/13642) about field validation.
I paste the code:
```c#
public class MyDriver : ContentDisplayDriver
{
    private readonly IStringLocalizer S;

    public MyDriver(IStringLocalizer<MyDriver> localizer)
    {
        S = localizer;
    }

    public override bool CanHandleModel(ContentItem model)
    {
        return (model.ContentType == "MyContentType")
    }

    public override async Task<IDisplayResult> UpdateAsync(ContentItem model, IUpdateModel updater)
    {
        await ValidateItemsAsync(model, updater);

        return await EditAsync(model, updater);
    }

    private async Task<bool> ValidateItemsAsync(ContentItem model, IUpdateModel updater)
    {
        // retrieve value of field
        TextField MyTextField = new TextField();
        await updater.TryUpdateModelAsync(
            MyTextField,
            string.Format("MyPart.MyTextField", _type),
            f => f.Text
        );

        bool IsValid = false;

        if ((MyTextField.Text is not null) && MyTextField.Text.Length > 160)
        {
            updater.ModelState.AddModelError(
                string.Format("MyPart.MyTextField.Text", _type),
                S["MyTextField allows a maximum of 160 characters. " +
                "You have inserted {0} characters.",
                MyTextField.Text.Length.ToString()]
            );
        }else{
            IsValid = true;
        }

        return IsValid;        
    }
}
``` 

If at the line:
```c#
if ((MyTextField.Text is not null) && MyTextField.Text.Length > 160)
``` 
I do not check for `MyTextField.Text is not null`, and I have not compiled the field with some text, resulting in a null value for _MyTextField.Text_, a _System.NullReferenceException_ is thrown and handled somewhere (I am not able to step into OC code, kindly explain how to do it if it can be useful).
But this does not prevent the Content Item from being created.

### Expected behavior
An alert reporting something like "An internal error occurred" should be displayed.
The Content Item should not be created.

My current version: OrchardCore 1.5.0

**Comment by sebastienros** [comment]
> But this does not prevent the Content Item from being created.

This is by design. Handlers' exceptions don't prevent the full set of handlers to work. It is your responsibility to use AddModelError to cancel the current transaction/action.

Note: you are implementing ContentDisplayDriver, the field name would be computed automatically if you used a ContentDisplayDriver<TextField> for instance.

If you want to debug the code, you need to clone this repository and start your site with the source code instead of the nuget packages. OR you can just configure the Debugger to disable "Enable Just my Code" so it can step in external code.
