### ISSUE TITLE
why the `CreateFileFromStreamAsync ` only support create in new directory?

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#13647]
Is there a logical problem here?

``` c#
  if (Directory.Exists(physicalPath))
  {
      throw new FileStoreException($"Cannot create file '{path}' because it already exists as a directory.");
  }

  // Create directory path if it doesn't exist.
  var physicalDirectoryPath = Path.GetDirectoryName(physicalPath);
  Directory.CreateDirectory(physicalDirectoryPath);
```

https://github.com/OrchardCMS/OrchardCore/blob/c1c25d89526153527aa22c98d83d5a37ca23f44e/src/OrchardCore/OrchardCore.FileStorage.FileSystem/FileSystemStore.cs#L301C1-L308

**Comment by sebastienros** [comment]
Looks like it should be `File.Exists`

**Comment by sebastienros** [comment]
Actually the code is checking if the requested filename is an existing folder.

This should not be an issue, are you facing this exception? If so please provide repro steps.

**Comment by hishamco** [comment]
> Actually the code is checking if the requested filename is an existing folder.

I think what @hyzx86 mean is whenever you create a file it should create a new directory as a parent for that file, I need to verify it allows creating a file in the root of the media folder otherwise it will be a bug

**Comment by hishamco** [comment]
I think the code is fine because if the path

- `Media\Test.txt` will try to create "Media" folder otherwise it creates a file inside it
- `Media\Test\Test.txt` will try to create "Media\Test" folder otherwise it create a file inside it

@hyzx86 could you please tell what's the case that doesn't work with you?

**Comment by hyzx86** [comment]
looks like this is not a bug , I re-tested and found that I could create folder paths directly

The problem I had earlier was probably due to data stream operations. I forgot to close the issue after solving it, and there is no problem from the current test results


```js
$ext.writeTextToFile({
    content: "testStrings" ,
    encoding: "gbk",
    StreamSource: "FileStore",
    FilePath: 'folder1/folder2/' + "NSR-Text.txt"
})
```

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/5f507554-c440-471a-8a50-407475b7465c)

**Comment by hyzx86** [comment]
oh， Come to think of it, there might be another problem, which is appending to an existing file

Currently it can only be rebuilt by deletion

**Comment by hishamco** [comment]
If there's another issue please file an issue describing the new one
