### ISSUE TITLE
Duplicated method CamelFriendly

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#13660]
There are `CamelFriendly` extension methods in 2 places:

https://github.com/OrchardCMS/OrchardCore/blob/7c46ab267ee0b4884e5f2724447d1ede1c850ec3/src/OrchardCore/OrchardCore.Mvc.Core/Utilities/StringExtensions.cs#L16

https://github.com/OrchardCMS/OrchardCore/blob/7c46ab267ee0b4884e5f2724447d1ede1c850ec3/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/Utilities/StringExtensions.cs#L14

Can we have a unique method?

**Comment by hishamco** [comment]
We have already cleanup duplicate methods in https://github.com/OrchardCMS/OrchardCore/pull/13613/files 

Let me check this one

**Comment by hishamco** [comment]
Can we move this class to `OC.Infrastrcture.Abstractions` because such methods could be utilized from various modules

**Comment by sebastienros** [comment]
Let's not move it in Infrastructure, it contains mostly services.
It's used in Views only, so Mvc.Core makes sense, let's keep it. The other one is used only once to create a technical content type definition. It could be renamed to not mention Camel casing (it's an implementation details in this case) and made internal so it's not used by other modules.

**Comment by hishamco** [comment]
It's not matter of `CamelFriendly` only, there are several duplicate methods, I will create a PR to remove them from `OC.ContentManagement.Abstractions`

**Comment by hishamco** [comment]
I just notice that some methods need to be used on `OC.ContentManagement` I don't think referencing `OC.Mvc.Core` is a good idea, that is why I suggested moving it to `OC.Infrastructure` ya it contains mostly service but also have some extensions if the case required that

**Comment by hishamco** [comment]
I just notice that some methods need to be used on `OC.ContentManagement` I don't think referencing `OC.Mvc.Core` is a good idea, that is why I suggested moving it to `OC.Infrastructure` ya it contains mostly service but also have some extensions if the case required that

**Comment by hishamco** [comment]
I just notice that some methods need to be used on `OC.ContentManagement` I don't think referencing `OC.Mvc.Core` is a good idea, that is why I suggested moving it to `OC.Infrastructure` ya it contains mostly service but also have some extensions if the case required that
