### ISSUE TITLE
Setting Authority value in OpenId server does not reflect server endpoints in the well-known info

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13671]
### Describe the bug
When using OpenId Server feature, one of the available settings is **Authority** or **Issuer**. When providing a specific value, the values the URI's showing for `authorization_endpoint`, `token_endpoint`, `introspection_endpoint`, `end_session_endpoint`, `revocation_endpoint`, `userinfo_endpoint`, and `jwks_uri` will still reflect the current site URL. For example, my OC app is running locally using `https://custom-domain.NET` this domain is accessible only when users on the internal network access my app. However, external apps must use `https://custom-domain.COM` in order to get to the same website. To allow external apps to connect to my app, I set the `Issuer` to `https://custom-domain.com/` which is the domain anyone can use to connect to my server. However, the value for the other endpoints still reflect the `.NET` domain not the `.COM` as I would expect. Here is the output of the `https://custom-domain.com/.well-known/openid-configuration`

```
{
  "issuer": "https://custom-domain.com/",
  "authorization_endpoint": "https://custom-domain.NET/connect/authorize",
  "token_endpoint": "https://custom-domain.NET/connect/token",
  "introspection_endpoint": "https://custom-domain.NET/connect/introspect",
  "end_session_endpoint": "https://custom-domain.NET/connect/logout",
  "revocation_endpoint": "https://custom-domain.NET/connect/revoke",
  "userinfo_endpoint": "https://custom-domain.NET/connect/userinfo",
  "jwks_uri": "https://custom-domain.NET/.well-known/jwks",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token"
  ],
  "response_types_supported": [
    "code"
  ],
  "response_modes_supported": [
    "form_post",
    "fragment",
    "query"
  ],
  "scopes_supported": [
    "openid",
    "offline_access",
    "email",
    "phone",
    "profile",
    "roles"
  ],
  "claims_supported": [
    "aud",
    "exp",
    "iat",
    "iss",
    "sub"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "code_challenge_methods_supported": [
    "S256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "introspection_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "revocation_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "claims_parameter_supported": false,
  "request_parameter_supported": false,
  "request_uri_parameter_supported": false,
  "authorization_response_iss_parameter_supported": true
}
```
### Expected behavior
I think anytime an `Authority` settings is different than the current host, the value for  `authorization_endpoint`, `token_endpoint`, `introspection_endpoint`, `end_session_endpoint`, `revocation_endpoint`, `userinfo_endpoint`, and `jwks_uri` should be based on the Issue not the current site.

**Comment by ns8482e** [comment]
I guess, It's expected behavior it returns current requested host. 

In your scenario the external facing site (.COM) still sends the request to internal domain (.NET). So site hosted on internal domain see host header as internal dns

To have reflect external domain in reverse proxy scenario to internal site, enable reverse proxy feature and enable host and proto option.

#Your external facing site(proxy) must forward the original host header- in IIS you can achieve by setting preserveHostHeaders
