### ISSUE TITLE
centos 7 can't load setup.min.js,setup.min.css,font-awesome.min.css 

### ISSUE THREAD

**Issue by EagleSmith** [OrchardCMS/OrchardCore#1367]
OS:centos 7
dotnet run --no-launch--profile
open localhost:5000 setup page ,no css,js loaded.

**Comment by jtkech** [comment]
And then, could you complete the setup? Were the static files correctly served after the setup? Do you use the full source code, if so which branch? Or only package references, if so which version? Do you use our web app or a custom one?

If necessary i will re-try it at least under Ubuntu through a Window Bash command, but i did it a while ago and i'm not confortable with unix commands.

**Comment by jtkech** [comment]
Just for infos because it doesn't prove that it works on centos 7, but at least i could get the last dev branch working on a simulated Ubuntu machine, this by using a windows 10 bash command.

- So, under the `/Orchard2` solution folder i did a `sudo dotnet restore`.

- Then, under the `OrchardCore.Cms.Web` folder i did a `sudo dotnet build`.

- Then in the same folder i did a `sudo dotnet bin/debug/netcoreapp2.0/OrchardCore.Cms.Web.dll`.

- **Note**: To get it working i always need to start my commands with `sudo`.

![ubuntu4](https://user-images.githubusercontent.com/8586360/34910742-0db16376-f8bc-11e7-9d60-031c1288799d.png)


- I also tried in the same folder `sudo dotnet run` which is longer, i got 2 warnings but it also worked.

![ubuntu6](https://user-images.githubusercontent.com/8586360/34910749-23230cfa-f8bc-11e7-9280-c83023d127d4.png)

**Comment by EagleSmith** [comment]
i used nginx ,maybe nginx conf file was wrong.

**Comment by EagleSmith** [comment]
[root@localhost ~]# cd /data/wwwroot/OrchardCore/src/OrchardCore.Cms.Web/
[root@localhost OrchardCore.Cms.Web]# dotnet bin/Debug/netcoreapp2.0/OrchardCore.Cms.Web.dll
Hosting environment: Production
Content root path: /data/wwwroot/OrchardCore/src/OrchardCore.Cms.Web
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

`[root@localhost OrchardCore.Cms.Web]# vi /usr/local/nginx/conf/nginx.conf
  gzip_proxied any;
  gzip_vary on;
  gzip_types
    text/xml application/xml application/atom+xml application/rss+xml application/xhtml+xml image/svg+xml
    text/javascript application/javascript application/x-javascript
    text/x-json application/json application/x-web-app-manifest+json
    text/css text/plain text/x-component
    font/opentype application/x-font-ttf application/vnd.ms-fontobject
    image/x-icon;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";

  #If you have a lot of static files to serve through Nginx then caching of the files' metadata (not the actual files' contents) can save some latency.
  open_file_cache max=1000 inactive=20s;
  open_file_cache_valid 30s;
  open_file_cache_min_uses 2;
  open_file_cache_errors on;

######################## default ############################
  server {
    listen 80;
    server_name _;
    access_log /data/wwwlogs/access_nginx.log combined;
    error_log /data/wwwlogs/error_nginx.log;
    root /data/wwwroot/OrchardCore;
    index index.html index.htm index.php;
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    location /nginx_status {
      stub_status on;
      access_log off;
      allow 127.0.0.1;
      deny all;
    }
    location ~ [^/]\.php(/|$) {
      #fastcgi_pass remote_php_ip:9000;
      fastcgi_pass unix:/dev/shm/php-cgi.sock;
      fastcgi_index index.php;
      include fastcgi.conf;
    }
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
      expires 30d;
      access_log off;
    }
    location ~ .*\.(js|css)?$ {
      expires 7d;
      access_log off;
    }
    location ~ /\.ht {
      deny all;
    }
    location / {
 location ~ /\.ht {
      deny all;
    }
    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
########################## vhost #############################
  include vhost/*.conf;

`

**Comment by EagleSmith** [comment]
modify the conf file 
************************
server {
    listen 80;
    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
    }
}
************************

it's working now.
thanks
