### ISSUE TITLE
GroupId checks in DisplayDriver.UpdaetAsync are case sensitive, but URLs are not

### ISSUE THREAD

**Issue by ryanwawr** [OrchardCMS/OrchardCore#13684]
### Describe the bug
If I go to a settings page in the Orchard Core admin panel that has a corresponding DisplayDriver, the URL of the page is not case sensitive, but the `if (context.GroupId == GroupId)` check in the override of DisplayDriver.UpdateAsync is case sensitive. This means that I can enter two different URLs for a settings page, both of which will work, but only one of which will actually cause any updates to be applied when the form is submitted. When I searched for that line of code across the Orchard Core 1.5.0 solution (which is what I'm currently running on), I find it in 16 drivers, so I would expect this issue affects all of them.

### To Reproduce
1. In the admin panel of any Orchard Core site, go to ~/Admin/Settings/general
2. Update the site name and hit Save. You should see your changes applied.
3. Change the URL to ~/Admin/Settings/**General**
4. The page should load correctly, but the hidden GroupId field is now set to "General" rather than "general"
5. Update the site name again and hit Save. You should see a message indicating that the settings have been updated, but they haven't actually been applied.

### Expected behavior
The GroupId comparison in DisplayDriver.UpdateAsync should be case insensitive. If the page loads correctly for a given URL, submitting the page should work as expected rather than mysteriously failing to update the settings.

### Screenshots
Link to GIF of described reproduction steps
https://i.imgur.com/Pd1lU27.gif

**Comment by hishamco** [comment]
Could you please submit a PR for it?

**Comment by jtkech** [comment]
Yes, I can repro

Or check the same in the edit method so that it is as a non existing group id.

        public override Task<IDisplayResult> EditAsync(ISite site, BuildEditorContext context)
        {
            if (context.GroupId != GroupId)
            {
                return Task.FromResult<IDisplayResult>(null);
            }
