### ISSUE TITLE
The Admin Culture Picker  is not displaying correctly on the workflow  page

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#13706]
It just doesn't show up properly in the workflow list, but it looks fine on other pages

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/d6a6cd18-41d2-4a52-8f79-bda9d387918a)

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/c0a6c3a4-c34d-4994-840f-f65fd8edf033)

**Comment by hishamco** [comment]
Thanks for reporting this, seems there is a custom style in WF that affects the admin culture picker. Hope to fix it, if you don't fix it before me :)

**Comment by hyzx86** [comment]
I tried, but I couldn't find any conflicting styles

My front-end skills are weak🤣

**Comment by hishamco** [comment]
No problem, I might have a look

**Comment by mdameer** [comment]
@hishamco @hyzx86 This issue no longer appears to be valid, I cannot reproduce it with the latest code on the main branch.
