### ISSUE TITLE
hosting orchard on IIS

### ISSUE THREAD

**Issue by tripurarisingh1** [OrchardCMS/OrchardCore#13708]
I am hosting Orchard CMS on IIS and getting this error, kindly let me know how to fix it.

info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
2023-05-18 07:25:55.1791|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
2023-05-18 07:25:55.2105|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2023-05-18 07:25:55.2148|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\inetpub\wwwroot\website\
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\inetpub\wwwroot\website\
2023-05-18 07:28:54.9214|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

**Comment by hishamco** [comment]
Strange!! can you check the logs

**Comment by tripurarisingh1** [comment]
Logs----------

warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {a0db66d3-78b8-4087-bbb3-450052c14976} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
2023-05-18 06:23:52.0619|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
2023-05-18 06:23:52.0619|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2023-05-18 06:23:52.0642|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\inetpub\wwwroot\website\
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\inetpub\wwwroot\website\
2023-05-18 06:26:07.9076|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

**Comment by hishamco** [comment]
This [link ](https://stackoverflow.com/questions/40783170/neither-user-profile-nor-hklm-registry-available-using-an-ephemeral-key-reposit) might help

**Comment by tripurarisingh1** [comment]
**I tried but after that getting this logs.**

info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
2023-05-18 07:25:55.1791|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
2023-05-18 07:25:55.2105|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2023-05-18 07:25:55.2148|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\inetpub\wwwroot\orchard.test.tglserver.net\
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\inetpub\wwwroot\orchard.test.tglserver.net\
2023-05-18 07:28:54.9214|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

**Comment by hishamco** [comment]
Is it a new installation or do you import content from another website and you get this error?

**Comment by tripurarisingh1** [comment]
it's import export data from Another tenant with same website.

**Comment by hishamco** [comment]
I see, seems the issue is with the data protection key, I remember @piedone replied to a similar issue in the past

**Comment by tripurarisingh1** [comment]
How we can resolve this  @Piedone  Can you please guide us ?
it's urgent for us we are working on it past few hours and did not resolved this.

**Comment by hishamco** [comment]
No need to push anyone, I understand your situation and hope someone can help you. I'm still expecting the issue to be from some of your content have been decrypted using another key

**Comment by hishamco** [comment]
BTW @tripurarisingh1 you can submit your issue in the Gitter (Element) may be you get a quick answer there

**Comment by Piedone** [comment]
While you have some warnings, neither are errors that prevent you from running the app. Rather, the app shuts down after 3 minutes. Don't you have idle timeout configured in IIS?

**Comment by tripurarisingh1** [comment]
We are using default settings IIS, 
We tried newly installation on same server and it's working fine.

if issue in IIS settings then every website will face same issues. we setup new code on same server it's working fine.

**Comment by tripurarisingh1** [comment]
Enable logs in details and now getting this error:

warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {bd490136-0c6d-4132-887b-1cb18ffd9f33} with creation date 2023-05-19 08:20:42Z, activation date 2023-05-19 08:20:42Z, and expiration date 2023-08-17 08:20:42Z.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {bd490136-0c6d-4132-887b-1cb18ffd9f33} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
2023-05-19 13:50:42.4020|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
2023-05-19 13:50:42.4028|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]

**Comment by hyzx86** [comment]
@tripurarisingh1 
Have you ever checked Windows application logs? There may be more detailed information there

**Comment by tripurarisingh1** [comment]
yes, that checked and application is running successfully.

**Comment by tripurarisingh1** [comment]
That issue not fixed but I tried with new installation on server and it's working now.

**Comment by MikeAlhayek** [comment]
@tripurarisingh1 
You likely are having permissions issue. Make sure the `IIS_IUSRS` has write access to the `App_Data` folder. If that does not work, try running the app using command line as `Administrator`. Right click your command line console, and select `Run as Administrator`. Then run `dotnet YourWebProjectName.dll`.

If the app run with no problems, stop it and try running it from IIS. When it runs as admin it'll create the necessary folders inside the `App_Data` folder.
