### ISSUE TITLE
CultureNotFoundException: Culture is not supported. (Parameter 'name')

### ISSUE THREAD

**Issue by w55156** [OrchardCMS/OrchardCore#13700]
### Describe the bug
CultureNotFoundException: Culture is not supported. (Parameter 'name')
zh-Hans-CN is an invalid culture identifier.
System.Globalization.CultureInfo..ctor(string name, bool useUserOverride)
### To Reproduce
1. New project cms.web
2. install packaages OrchardCore.Application.Cms.Targets 1.6 or 1.7 (the same error)
3. F5 Run

### Expected behavior
CultureNotFoundException: Culture is not supported. (Parameter 'name') zh-Hans-CN is an invalid culture identifier.
System.Globalization.CultureInfo..ctor(string name, bool useUserOverride)
OrchardCore.Localization.LocalizationOptionsUpdater.AddSupportedCultures(string[] cultures)
OrchardCore.Setup.Startup.Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
OrchardCore.Modules.ModularTenantRouterMiddleware+<>c__DisplayClass7_0.<ConfigureTenantPipeline>b__1(IEndpointRouteBuilder routes)
Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)
OrchardCore.Modules.ModularTenantRouterMiddleware.ConfigureTenantPipeline(IApplicationBuilder appBuilder)
Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline()
OrchardCore.Modules.ModularTenantRouterMiddleware.InitializePipelineAsync(ShellContext shellContext)
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
OrchardCore.Modules.ModularTenantContainerMiddleware+<>c__DisplayClass4_0+<<Invoke>b__0>d.MoveNext()
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/8390481/1357fc28-8de0-403f-bab3-9068b2a6c659)

**Comment by hishamco** [comment]
I presume your system culture is `zh-Hans-CN` right? Could you please run `dotnet --version` then show me the output

**Comment by hishamco** [comment]
Strange!! can you create a normal ASP.NET Core Razor Page and display the current culture, I presume it should display `zh-Hans-CN`

**Comment by w55156** [comment]
![image](https://github.com/OrchardCMS/OrchardCore/assets/8390481/1a0ac107-f170-42d5-9589-78046c501802)

it display zh-CN

**Comment by hyzx86** [comment]
@w55156  Have you submit anything  on  setup page?  

Also, did you setup oc in a new directory?
Yesterday, I met a person with the same problem as you in QQ group, but his problem was the problem of using the new version of OC to run the old version of data

**Comment by hyzx86** [comment]
I know the current latest version doesn't work with zh-Hans-CN, but zh-CN works fine

@w55156  You should check your browser's default language, not the system's default language

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/337c7fb2-84d2-474c-bdcb-066f6f2a7721)

**Comment by hishamco** [comment]
Still I'm surprising why `zh-Hans-CN` is invalid culture?!!

**Comment by hyzx86** [comment]
I don't know~ 😥
You can try with this settings
![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/087c10c7-ab57-4f5f-91de-a0584d50e2b1)

**Comment by hishamco** [comment]
Waiting for @w55156 reply, I'm not sure if he already setup an OC or the exception thrown before setup

Thanks for your input @hyzx86

**Comment by hyzx86** [comment]
@hishamco  
I use the below code to create a new site 
``` powershell
dotnet new occms -n TestLocal
cd .\TestLocal\
dotnet run .\TestLocal.csproj
```

I think the possible reason is because `zh-Hans-CN` is not added here

But since my browser was unable to add the zh-Hans-CN option, I was unable to reproduce the problem


![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/e5bb6511-deb5-4990-9041-786feffac404)

**Comment by hishamco** [comment]
We added `zh-Hans` & `zh-Hant` If I remember to make it easier to fall back to the right culture. Let us wait for @w55156 feedback

Thanks again

**Comment by w55156** [comment]
> 



> @w55156 Have you submit anything on setup page? @w55156 您在设置页面上提交了任何内容吗？
> 
> Also, did you setup oc in a new directory? ❗ 🔄 Yesterday, I met a person with the same problem as you in QQ group, but his problem was the problem of using the new version of OC to run the old version of data昨天我在QQ群里遇到了一个和你有同样问题的人，不过他的问题是用新版OC运行旧版数据的问题

That is me, the problem is using the new version (1.6) of OC to run a new project first, but cant, so i use then version1.5 instead,that is ok, and i want to know why  the version1.6 cant not ?

**Comment by w55156** [comment]
> I know the current latest version doesn't work with zh-Hans-CN, but zh-CN works fine
> 
> @w55156 You should check your browser's default language, not the system's default language
> 
> ![image](https://user-images.githubusercontent.com/15613121/238952151-337c7fb2-84d2-474c-bdcb-066f6f2a7721.png)

![image](https://github.com/OrchardCMS/OrchardCore/assets/8390481/bdcf36da-7353-40b2-9f86-d4b0f4ce3be3)

**Comment by hishamco** [comment]
@w55156 could you please confirm if the issue still exists?

/cc @hyzx86

**Comment by hyzx86** [comment]
@hishamco   Everything's fine on my end
