### ISSUE TITLE
Add a way for modules to add liquid tags

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1370]
`ILiquidFilter` allows modules to add their own filters; we need an equivalent for liquid tags.

Additionally, we should add the tag `{% anti_forgery_token %}` so that the login page (and any other page with a form that requires this value) can be themed with liquid.

**Comment by jtkech** [comment]
I don't remember well but maybe it already exist.

            LiquidViewTemplate.Factory.RegisterTag<SomeTag>("some_tag");

**Comment by sebastienros** [comment]
This might be too intrusive. Filters can be added contextually, the grammar is shared for all tenants.

**Comment by sebastienros** [comment]
But we definitely need the form related tags, including rendering action url and antiforgery.

**Comment by paynecrl97** [comment]
Yeah I had a quick go at implementing it this morning, it’s trickier than you might first think. 

LiquidViewTemplate.Factory.RegisterTag<SomeTag>("some_tag");
^^ that would also require the module to take a dependency on liquid, which ILiquidFilter does not. 
If we’re happy just to add the tags that would be required to get login working, I can do that. I make it 3 items to be added:
A filter that will give you a url {{ “actionname” | action_url: url params etc }}
A filter that can get values from the view data {{ “returnurl” | view_data }}
A tag that renders the anti forgery token input element {% anti_forgery_token %}

**Comment by jtkech** [comment]
Oh just for infos, as i remember we already have a bridge between asp and liquid helpers, i don't remember well, maybe something like this `{% helper "taghelpername", ...other arguments %}`, e.g for a form, which is not a self closed tag, something like this `{% block "form", ...other arguments %}`. As i remember, then for asp arguments we need to use `_` in place of `-` to be compatible with liquid syntax.

**Comment by sebastienros** [comment]
Better to have specific liquid tags for common scenarios, without having to bridge to tag helpers which can be expensive. I would suggest to follow shopify tags too when possible.

I am fine with these right now:
```
{% form ... %}
...
{% endform%}
```

and  ``` {% anti_forgery_token %} ```

If the method is POST then the antiforgery token should be generated automatically (like ASP.NET is doing).

For the other ones, I am not sure filters are better than tags. Let's see what shopify does in this case.

**Comment by sebastienros** [comment]
OR maybe we don't need the form tag, and can just use one for `{% action_url %}`

**Comment by jtkech** [comment]
Okay.

But as i remember we already use this bridge to found our own taghelpers. Or to be less expensive, maybe better to not use the "full" bridge by just retrieving our own taghelpers as `shape`, `zone` ...

Otherwise, would need to be tried, but if we do this.

    Factory.RegisterBlock<NamedHelperBlock>("form");

Then maybe we could already use `{% form ... %} ... {% endform%}`

**Comment by sebastienros** [comment]
- it has to make sense (not sure form makes sense as a tag in liquid, we can just fo <form>
- it has to be fast, the bridge is nice so we don't block users, but if something is commonly used then we should support it natively for perf reasons. The is a lot of reflection involved
- it has to look intuitive, tag vs. filter, and parameter names, if possible mathcing shopify/jekyll

**Comment by jtkech** [comment]
Yes, it makes sense, it was just to point out what already exists ;)

Oh, so for perf is it worth to also implement natively `zone`, `shape` ... which are frequently used.

**Comment by sebastienros** [comment]
Yes. Ideally we should measure it. You remember how?

**Comment by jtkech** [comment]
Yes, but i 1st need to do a native version i want to compare with. I noted it and i will check it asap.

Another thing i saw is that the bridge hits some c# compilation, so we always need the `refs` folder in a published context, normally we could get rid of it when razor views are precompiled.

**Comment by paynecrl97** [comment]
Another way to do this would be add values to the local scope, possibly via `ILiquidTemplateEventHandler`. eg:

```
<form action="{{ LoginPostUrl }}" method="post">
{{ AntiForgeryToken | raw }}
```

I think this works well for things like the login URL, but the anti forgery token is a bit awkward as it's not really a value.

For the time being, could we add `LoginPostUrl` as a value to the local scope, and add an `AntiForgeryToken` tag, with caveat that it would be shared between tenants?
