### ISSUE TITLE
Add possibility to open a selected content item in a ContentPickerField in a new tab

### ISSUE THREAD

**Issue by dannyd89** [OrchardCMS/OrchardCore#13715]
### Is your feature request related to a problem? Please describe.
We are using a lot of ContentPickerFields in our solution and sometimes you lose track on what exactly one item contains
versus another one. To actually know this now, you would need to navigate to the item list of the type and view it and then navigate back to where you were before. This can be tedious if done a lot of times.

### Describe the solution you'd like
It would be nice to be able to open the selected item in a ContentPickerField via a button right next to the "Remove" button.
![image](https://github.com/OrchardCMS/OrchardCore/assets/15252548/15ab2b80-934d-45aa-b05e-ead1258ee2de)

### Describe alternatives you've considered
An alternative would be to write our own ContentPickerField with its own View etc

**Comment by sebastienros** [comment]
I would suggest to create a custom Editor Display type for this field. Feel free to start PR if you feel like it.

**Comment by dannyd89** [comment]
I will be a bit busy the next weeks but I can try to tackle it after, if noone else wants to take it on

**Comment by jtkech** [comment]
For a project we had to support this, so if you start a PR I may be able to help ;)
