### ISSUE TITLE
Theme implementation like Orchard 1.10

### ISSUE THREAD

**Issue by Jalalx** [OrchardCMS/OrchardCore#1371]
Does old themes based on Orchard 1.10 will be supported by the new version of Orchard Core? Or we need to reimplement existing themes for this new version?

**Comment by infofromca** [comment]
I think it is on road map beta 2

**Comment by sebastienros** [comment]
It's definitely on the roadmap that we won't provide an automatic migrations. But migrating should be quite easy as all the concepts remain the same. People already find it easier to theme in OC.
