### ISSUE TITLE
Remove font-awesome 6.4 CDN from resources

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13717]
### Describe the bug
font-awesome 6.4 does not have a CDN but one is defined in the resources. Instead, maybe use the local resource using `.SetUrl()`

https://www.jsdelivr.com/package/npm/@fortawesome/fontawesome-free

When I used font 6.4 in production, I get issue with the integrity token 
@agriffard

**Comment by hishamco** [comment]
> When I used font 6.4 in production, I get issue with the integrity token

Maybe the issue with the hash itself, it happens many times in the past

**Comment by agriffard** [comment]
> Maybe the issue with the hash itself, it happens many times in the past

Sorry, my bad.
We still need a way to check SRIs.

**Comment by hishamco** [comment]
> We still need a way to check SRIs.

No worry, I will try to update my old PR that I started long time back

**Comment by agriffard** [comment]
FYI, I use this tool to get a SRI from a URL:
https://www.srihash.org/
