### ISSUE TITLE
Bug of `Users Authentication Ticket Store` Feature 

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#13726]
oc version ：preview-latest

### Describe the bug

After enabling the `Users Authentication Ticket Store` feature, 
whenever any other feature is enabled. The user is always redirected to the login page.

**Comment by hyzx86** [comment]
It looks like this is always null
![Uploading image.png…]()

**Comment by hyzx86** [comment]
I Debug the code and see that the following method is called after `ShellScope.UsingAsync`

OrchardCore.Users.Authentication.CacheTicketStore.RetrieveAsync


https://github.com/OrchardCMS/OrchardCore/blob/edccca0b92228d55ec70ef32deda5c47e5bdfb99/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs#L224

**Comment by hishamco** [comment]
Into your plate @ns8482e :)

**Comment by hyzx86** [comment]
So, should we save the Token to the database without Redis enabled?

At the moment, it seems that this problem will only arise on the site Settings changed

**Comment by hyzx86** [comment]
@sebastienros This is not a very urgent issue in my scenario right now; After all, it's reasonable to tell users that a configuration change caused them to log back in 😁

I actually feel like this part of the code is a little hard for me to change
Maybe we can add some documentation and close it, or someone else can fix the problem

**Comment by hyzx86** [comment]
> We could also have an implementation that is based on SQL

Well, if we start with that, it's really not difficult. I can try it

**Comment by hyzx86** [comment]
To achieve this, should I re-implement a SqlDistributedCache? It's like

https://learn.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-6.0

This seems a bit complicated, but for distributed caching, shouldn't we make it a higher priority, such as enabling it only from the default site, and then separate the distributed caching object from the specific tenant?

**Comment by Piedone** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/16149 covers SQL Distributed Cache, so we don't need to do anything specific for this module, and rather work on that.
