### ISSUE TITLE
High memory usage and High Private bytes consumption detected

### ISSUE THREAD

**Issue by vmahant** [OrchardCMS/OrchardCore#13741]
### Performance Issue
Code Optimizations found code recommendations:

<html>
<body>

Type | Performance issue | Component | Count | Impact | Role
-- | -- | -- | -- | -- | --
Memory | EndpointRoutingMiddleware.InitializeCoreAsync is causing high Memory | OrchardCore.Diagnostics.DiagnosticsStartupFilter.Configure | 2 | 12.48% | 
Memory | ContentExtensions.Get is causing high Memory | OrchardCore.ContentManagement.Handlers.ContentPartHandlerCoordinator.LoadingAsync | 34 | 10.39% | 
Memory | Enumerable.ToArray is causing high Memory | OrchardCore.Diagnostics.DiagnosticsStartupFilter.Configure | 3 | 3.45% | 

</body>
</html>

### Description
EndpointRoutingMiddleware.InitializeCoreAsync is causing unusually high memory allocations.
Enumerable.ToArray is causing unusually high memory allocations.

#### Current condition
13% of your Memory was spent in EndpointRoutingMiddleware.InitializeCoreAsync, We expected this value to be <7%.
11% of your Memory was spent in Enumerable.ToArray, We expected this value to be <3%.

Please Note: 

 sometimes %ages are higher than 20%

### Recommendations
Consider investigating why EndpointRoutingMiddleware.InitializeCoreAsync is causing higher-than-expected memory allocations.

NOTE: We are currently working on refining the details of this recommendation. In the meantime please click [here](https://aka.ms/profiler/perflens/recommendation/memory) to get general information about memory performance optimization.

### Screenshots

![Screenshot 2023-05-24 164106](https://github.com/OrchardCMS/OrchardCore/assets/31914591/f19f71fd-087f-4103-97ff-a173ff35fa82)
![Screenshot 2023-05-24 165040](https://github.com/OrchardCMS/OrchardCore/assets/31914591/fff74139-e177-4ac6-8500-a2997e4df39b)
![Screenshot 2023-05-24 165545](https://github.com/OrchardCMS/OrchardCore/assets/31914591/8de9c3be-3b36-4cf9-bce3-baebd6a6b7b3)

**Comment by vmahant** [comment]
Today more memory consumption for the same modules

![Screenshot 2023-05-25 091906](https://github.com/OrchardCMS/OrchardCore/assets/31914591/b64448ef-7a9b-4eae-b58c-ed5c80d16308)

**Comment by sebastienros** [comment]
These percentages are completely subjective and I would assume that some applications will definitely not match the expectations. However we can certainly take a hint and check if everything is normal.

The routing memory is maybe only due to the number of routes in the app. What happens if you create an empty aspnet app with hundreds of routes, does it show the same problem?

Maybe start checking where the Arrays are coming, then also if Get calls are expected (I believe they are, we are loading JSON documents so that is expected to allocate memory).

**Comment by Piedone** [comment]
Closing due to no reply from the author.
