### ISSUE TITLE
ZoneInfo GMT Standard Time

### ISSUE THREAD

**Issue by DJSADERS** [OrchardCMS/OrchardCore#1374]
The zoneinfo GMT Standard Time doesn't exist on CentOS7

The work about is to make a symbolic link from GMT Standard Time to GMT

The options are:

GB
GB-Eire
GMT
GMT0
GMT-0
GMT+0
Greenwich

**Comment by sebastienros** [comment]
Do you know where it's used in the code right now? Is it why OC doesn't work on centos ?

**Comment by DJSADERS** [comment]
Im not sure where it's used (I haven't looked) but it crashed the site right after the installer

The solution i found was to just make a symbolic link on my machine pointing to GMT, it runs fine after this is in place

**Comment by sebastienros** [comment]
Can you describe your machine? OS, default language.

**Comment by DJSADERS** [comment]
it's a basic CentOS 7.1 install with English UK as the language

**Comment by sebastienros** [comment]
Would have some trace/log of the exception, it would help me identify where it's set. It might be in Jint but I am not sure.

**Comment by Skrypt** [comment]
I think we can close this one since we are now using NodaTime TimeZones.
