### ISSUE TITLE
Templates feature should allow users to define resources

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1375]
The templates feature is a great way to allow users to edit markup from the admin panel. I think it should also allow users to define script and style resources. These resources could then be included in pages with the standard tags.

This would allow resources to be shared between multiple templates.

**Comment by sebastienros** [comment]
I think we already have this. Take a look at the Blog theme layout page. And documentation for the Liquid module.

**Comment by sebastienros** [comment]
I could find the example I mentioned and the documentation. Please reopen if you are not satisfied with it.

**Comment by paynecrl97** [comment]
Sorry I've not replied sooner, I've had a busy week.

I think there might be a misunderstanding here (either that or I'm failing to find the documentation). I can't see in the documentation a way to do what I proposed, but I think I might have been unclear.

There are liquid tags for `script` and `style`, but when you invoke those, you need to pass the name of or a path to a predefined script or style. That script or style must live in either a theme or a module at present.

I'm proposing allowing users to write the JS or CSS inside the admin section of their site (just like they can write their own liquid templates from the admin section). 

e.g. A user logs in to the admin section, and can create a new script (or edit an existing one) called `MyScript`. They'd then be able to use `{% script name="MyScript" %} from within their templates.

**Comment by sebastienros** [comment]
Harder, but you can already write inline script with these tags, targeting head and footer. Then you can call this shape from your other templates. I'd rather keep js and css customization at the theme level, we already have a design for this in another issue that might be better than anything.
