### ISSUE TITLE
Menu - When adding a menu item, menu unpublishes

### ISSUE THREAD

**Issue by websitewill** [OrchardCMS/OrchardCore#1377]
Not sure if this is desired behavior or not.
If I add a menu item to an existing (published) menu, and publish the menu item, the menu itself disappears. I have to publish the menu itself for it to show back up.

**Comment by sebastienros** [comment]
Sounds like a bug. However I am not sure how you "publish" a menu item. I don't remember we expose this action.

**Comment by sebastienros** [comment]
Ok. We might need to use a custom Entity for menu items instead of content items.

**Comment by sebastienros** [comment]
Fixed, menu items have the `MenuItem` stereotype

**Comment by sebastienros** [comment]
Actually the issue can't be reproduced anymore, adding a menu item creates a new Draft, which can then be published
