### ISSUE TITLE
ReverseProxy feature should give options to specify allowed hosts to prevent spoofing

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13795]
### Describe the bug
When running OC project behind proxy or load balancer, the ReverseProxy feature settings allow us to enable `X-Forwarded-Host` but there is no option to set the `AllowedHosts`

Trusting  `X-Forwarded-Host` but not specifying trusted hosts may lead to [IP spoofing](https://www.iplocation.net/ip-spoofing) attacks.

If the user checks `X-Forwarded-Host`  we should show a textarea box that would allow the user to provided one trusted host per line.

**Comment by ns8482e** [comment]
I guess you need to set `RequestUrlHost` for your tenants (or default tenant)

**Comment by sebastienros** [comment]
Isn't it https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Cms.Web/appsettings.json#LL8C44-L8C44
