### ISSUE TITLE
Publishing current bits on dev doesn create packages folder

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#1381]
On previous versions when we execute sth like that:
`dotnet publish --configuration Release --output d:\publish\ OrchardCore.Cms.Web.csproj`

At the first attempt we didn't get packages folder in d:\publish folder. But if we repeat the operation packages folder with the modules folders and its resources appear there. 
After update to latest bits of dev branch it doesn't work, so we cannot deploy the app with ther result of a publish.

Previously to publish step we execute: 
```
git clean -xdf
dotnet restore
src\OrchardCore.Cms.Web\dotnet restore
```

Any help?

**Comment by sebastienros** [comment]
We improved the system and don't require the `packages` folder anymore. All static resources are embedded in the assemblies.

**Comment by Jetski5822** [comment]
Whoah - I didn’t know that change happened!!! That’s awesome!!!

**Comment by sebastienros** [comment]
@Jetski5822 you should join us at the weekly meetings when we announce this kind of things, do you want a pointer to the youtube video ;)

**Comment by jersiovic** [comment]
That's great!
Thank you
cc: @jardg
