### ISSUE TITLE
orchardcore.net SSL certificate has expired

### ISSUE THREAD

**Issue by seancallinan** [OrchardCMS/OrchardCore#13836]
### To Reproduce
1. Go to 'https://orchardcore.net'
2. Browser shows an SSL warning because the certificate has expired

### Expected behavior
Browsing to the project website should not bring up an SSL warning :)

### Screenshots

![image](https://github.com/OrchardCMS/OrchardCore/assets/1139665/395de9aa-c505-4995-87b2-941778229cf8)

**Comment by hishamco** [comment]
Thanks, I already sent a message via Gitter to @agriffard

**Comment by Piedone** [comment]
We should rather use Cloudflare in front of the site. Among others, this also provides auto-updating SSL. I can set this up if you'd like @agriffard.

**Comment by MikeAlhayek** [comment]
fixed.

**Comment by Piedone** [comment]
How did you fix it?

**Comment by Piedone** [comment]
I see, thanks.
