### ISSUE TITLE
Sitemaps should not require `BaseUrl`

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13833]
### Is your feature request related to a problem? Please describe.
Today sitemaps will not work if the site settings does not have `BaseUrl` set. I am guessing that this requirement was implemented to ensure we index canonical urls. Maybe @deanmarcussen  has a better reason.

### Describe the solution you'd like
I don't think sitemaps should depend on using `BaseUrl`. If `BaseUrl`  is not set, we should be able to generate permalink using current host value otherwise we use `BaseUrl`.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/e8f52e95-e63a-48c0-a13e-90f9dcfe063d)

**Comment by hishamco** [comment]
> we should be able to generate permalink using current host value otherwise we use BaseUrl

Right, but what if I need to generate a sitemap per tenant?

**Comment by MikeAlhayek** [comment]
Sitemaps are generated per UI for each tenant just like anything else

**Comment by deanmarcussen** [comment]
it's to force a user to have to provide a value that fits their domain model.

seen too many sites screw up seo by ending up with ws1.company.com discovered by google, and then spent months getting the real site's url at the top of the search ranking.

**Comment by MikeAlhayek** [comment]
@deanmarcussen but is that a problem we have to solve for the site owners? I mean even if users want to have multiple domains, they would use canonical url to identify the main page.

**Comment by sebastienros** [comment]
Too risky because some sites might have the requirement to use baseurl, like with multiple domains and you really want a single one to be used at all times in the sitemap.

An improvement could be in the UI to explain why and provide a link to the settings.
