### ISSUE TITLE
NopCssMinifier.cs

### ISSUE THREAD

**Issue by bambuca** [OrchardCMS/OrchardCore#13837]
### Describe the bug
In branch 4.60.3, the [NopCssMinifer](https://github.com/nopSolutions/nopCommerce/commit/d36fddfaa7ac7ae3452c0d92ebc1472e6b1a2a12) class traverses files ending in ".min.js". It should correctly be ".min.css" as it is in the develop branch.

**Comment by Piedone** [comment]
It seems that your bug report is of nopCommerce, but this is Orchard Core :). I suggest you open an issue here instead: https://github.com/nopSolutions/nopCommerce/issues/new
