### ISSUE TITLE
Navigation Providers Don't Work As Expected

### ISSUE THREAD

**Issue by websitewill** [OrchardCMS/OrchardCore#1385]
It is my understanding that a registered INavigationProvider should be called on both the admin and "normal" side of things. However, it appears they are only called while I am on admin pages.

I am trying to dynamically add menu items to my main site menu, the same as I would do for admin navigation, but it doesn't seem to work.

Here is a sample INavigationProvider I am using:
public class MainMenu : INavigationProvider
    {
        public MainMenu(IStringLocalizer<MainMenu> localizer)
        {
            T = localizer;
        }

        public IStringLocalizer T { get; set; }

        public void BuildNavigation(string name, NavigationBuilder builder)
        {
            if (!String.Equals(name, "main", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            if (!String.Equals(name, "main-menu", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }
        }
    }

**Comment by jtkech** [comment]
Yes, because currently a navigation shape is only created when we are in the admin, [this by code here](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Admin/AdminMenuFilter.cs#L51).

So, maybe, as suggested by @sebastienros on gitter, you just need to do the same in the front end, e.g by adding in your layout theme something like this.

    @await DisplayAsync(await New.Navigation(MenuName: "main", RouteData: Context.RouteData))

And maybe you will need to override in your theme some navigation shapes as done in theAdmin theme.

**Comment by sebastienros** [comment]
I supposed @websitewill had done that when I asked him to file the issue. I'll try (unless you do @jtkech )

**Comment by websitewill** [comment]
I had, and I had not.
At that point I was back to using this to display the menu on the front end.
<menu alias="alias:main-menu" cache-id="main-menu" cache-duration="00:00:00" cache-tag="alias:main-menu"></menu>

The suggested code for DisplayAsync doesn't compile - doesn't like Context.RouteData. I suspect it should be ViewContext.RouteData, which I tried. That does trigger my INavigationProvider.

Now I am throwing in the overrides I need for Navigation, NavigationItem and NavigationItemLink, but it seems like this is going to work (ish).

Since my INavigationProvider is now being called, I think we can close this one.

I'll post follow-up question on Gitter.

**Comment by jtkech** [comment]
@sebastienros i was just going to try it.
@websitewill cool, so i don't need to try it.
Let know us if you have other issues.
