### ISSUE TITLE
Add Shell Extensions Helpers

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#13861]
Allowing to replace for example

    if (_shellSettings.State == TenantState.Running)
    ...
    var settings = new ShellSettings()
    {
        Name = ShellHelper.DefaultShellName,
        State = TenantState.Running
    };

By

    if (_shellSettings.IsRunning())
    ...
    var settings = new ShellSettings()
        .AsDefaultShell()
        .AsRunning();

And so on

**Comment by sebastienros** [comment]
Looks like constructor arguments though ...

**Comment by jtkech** [comment]
But not only if you look at the PR, I thought it could have been useful but no problem ;)
