### ISSUE TITLE
Be Tenant pathBase aware

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#13874]
There are some remaining places where the tenant `PathBase` (that may include a virtual folder) is not taken into account, for example OC.Templates preview doesn't work if under a virtual folder.

In OC.Templates preview there is also an encoding issue when the virtual folder or the tenant prefix contains a special char, or if we navigate to a content item whose path contains a special char.

**Comment by rjpowers10** [comment]
[userPreferencesPersistor](https://github.com/OrchardCMS/OrchardCore/blob/8258c91094ff32995709a3bfbf6795db0707ca0a/src/OrchardCore.Themes/TheAdmin/Assets/js/userPreferencesPersistor.js#LL13C13-L13C13) isn't tenant PathBase aware but probably should be.
