### ISSUE TITLE
Add a way to search contents with fields other than just displayText

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13886]
### Is your feature request related to a problem? Please describe.
Currently, when searching for contents we search the `DisplayText` property. In many case, I want to search content items for other fields like stock number or serial number. Currently, the only way to do this is by adding any info we want to search to the title. This may be acceptable is some case, but not all case.

### Describe the solution you'd like
I would like to be able somehow search other properties. One way to do this is implement a new proper that isn't visible where we can use to search. Now sure what other ideas do we have to solve this challenge? 

@sebastienros I would like to talk about this during Steering committee meeting.

**Comment by hishamco** [comment]
What if added a simple option "Searchable" allows the field value to be indexed?

**Comment by jtkech** [comment]
Just saw the last meeting.

A filter has a term to be used like this `term:word`, logical operators `OR`and `AND` can already be used if multiple words `term:word1 AND word2`. There is a `DefaultTermNode` that defines a default `TermName` (if no term is specified) and an implicit `Operation` (if no operator) which are currently `text:` and `OR`.

We already can defines custom filters using for example custom index tables.

        BuildArtistFilter(builder);
        BuildCatalogFilter(builder);
        BuildLabelFilter(builder);
        BuildGenreFilter(builder);
        BuildCountryFilter(builder);
        BuildCultureGroupFilter(builder);
        BuildLanguageFilter(builder);
        BuildInstrumentFilter(builder);
        BuildRecordingEraFilter(builder);
        BuildSeriesFilter(builder);

        builder
            .WithDefaultTerm("releasetext", builder => builder
                .ManyCondition(
                    (val, query) => query.With<ReleaseIndex>(i =>
                        i.DisplayText.Contains(val) ||
                        i.CatalogNumber.Contains(val) ||
                        i.ArtistDisplayName.Contains(val)),
                    (val, query) => query.With<ReleaseIndex>(i =>
                        i.DisplayText.NotContains(val) &&
                        i.CatalogNumber.NotContains(val) &&
                        i.ArtistDisplayName.NotContains(val))
                ));

Maybe what is missing is to be able to dynamically redefine the default term and operation, for example with the last above filter to not have to input `releasetext:`, but the default implementation of `IContentsAdminListQueryService` was easy to override with a custom one.

In which we set a new `DefaultTermNode` whose term name is based on the selected content type (if any), for example `releasetext:` if the `Release` content type is selected. Also if no explicit `OR` or `AND` operators are used, we opted to consider multiple words belonging to the same fully quoted string.

        // Use an unary operator based on a full quoted string.
        defaultOperator = new UnaryNode(defaultTermNode.ToString(), OperateNodeQuotes.Double);

**Comment by MikeAlhayek** [comment]
@jtkech I am aware of the ability to add filters and execute multiple logic. However, I am hoping for a way to change where the `text` filter is applied on. For example if I want to search for a product by title, serial or stock number, I don't want to have to type the following

```
text:"some title" OR serial:abc123 OR stock:xyz
```

Since I know in advance there are 3 way a product is searched, I want to be able to type 

```
Some title

```
Or 

```
Abc123

```
Or

```
Xyz

```

And the search will understand that this `text` should be applied on multiple columns or indexes somehow. 

Asking a non-technical person to type 

```
serial:abc123

``` 
Does not provide a good user experience.

**Comment by jtkech** [comment]
Yes, this is what I described in the last part of my previous comment, and where I tried to explain how we fixed it by using a custom `IContentsAdminListQueryService`, this for example to dynamically define a default term, so that you don't have to specify `serial:` (in my case `releasetext:`), and so on.

**Comment by jtkech** [comment]
My above filter is just an example, can be anything else using any other index tables and/or other logics.

In our overridden `IContentsAdminListQueryService` we change (but not only) the default term name from `text:` to another value, so if a search string doesn't contain any term name, the part of the query looking for the display text will not be used because `text:` is no longer the default term name.

**Comment by MikeAlhayek** [comment]
Would it be possible for you to share your implementation of `IContentsAdminListQueryService`?

**Comment by jtkech** [comment]
[QuotedSearchTextQueryService.txt](https://github.com/OrchardCMS/OrchardCore/files/11875192/QuotedSearchTextQueryService.txt)
