### ISSUE TITLE
Make 2FA requirement extensible

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13888]
### Is your feature request related to a problem? Please describe.
Currently, two factor authentication is decided the settings found in `LoginSettings.RequireTwoFactorAuthentication`. In some case, a user may have additional logic to determine if 2FA should be required or not. Here are some examples

 - Require authentication after x amount of login.
 - Require 2FA if the user is on external network.
 - Require 2FA if the user is not on a known network.

### Describe the solution you'd like
Use handler to determine 2FA should be required or not.

**Comment by hishamco** [comment]
> Require authentication after x amount of login.

Usually, the identity system locks the user after x attempts

**Comment by MikeAlhayek** [comment]
Yes it does. The example in this issue id about requiring 2FA after logging for X amount of time.
