### ISSUE TITLE
Enable Security Headers for Orchard Core Website

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#13896]
We already added a Security module in OC, it would be nice to have such headers enables, check the result [here](https://securityheaders.com/?q=https%3A%2F%2Forchardcore.net%2F&hide=on&followRedirects=on) which is shame :)

@agriffard can we take a step for this?

**Comment by MikeAlhayek** [comment]
even when the security feature enabled, it does not solve everything. This is still outstanding

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/e0d26a2c-7e3e-41a9-8c8e-08c49f013cee)

**Comment by hishamco** [comment]
You need to set the headers

**Comment by MikeAlhayek** [comment]
> > I do not see an option to set the X-Frame-Options anywhere
> 
> CPS contains `frame-ancestors` directive which obsoleted `X-Frame-Options`

Maybe we should add this in the security docs :)

**Comment by ericrrichards** [comment]
I was curious exactly how the HSTS header for the HTTPS module is supposed to work, especially in multi-tenant setups.
- Is it intended to be set on the root tenant? Or can you just enable it on a child tenant?
- Does it matter whether you are using a subdomain for the tenant (tenant.domain.com) vs a prefix tenant (domain.com/tenant)?
- Do you need to completely restart the Orchard application to get it to apply?

My experience has been that I can't reliably get the HSTS headers to show up in responses by changing the settings at runtime.  I don't know if this is expected or if it is somehow related to running OrchardCore on a zone-redundant Azure App service with a Redis backing cache.

The HTTP->HTTPS redirection works just fine.
