### ISSUE TITLE
Add a DataProtection package/module making IDataProtectionProvider tenant-aware

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#1391]
This can be easily implemented as a module (assuming the Data Protection services are registered at the host level, as currently):

```csharp
public class Startup : StartupBase
{
    private readonly IDataProtectionProvider _dataProtectionProvider;

    public Startup(
        IDataProtectionProvider dataProtectionProvider,
        ShellSettings shellSettings)
    {
        _dataProtectionProvider = dataProtectionProvider.CreateProtector(shellSettings.Name);
    }

    public override void ConfigureServices(IServiceCollection services)
    {
        // Replace the global data protection provider by a tenant-aware instance so that modules that
        // internally rely on IDataProtector/IDataProtectionProvider automatically and transparently get
        // an isolated instance that doesn't allow decrypting payloads encrypted by another tenant.
        services.Replace(ServiceDescriptor.Singleton(typeof(IDataProtectionProvider), _dataProtectionProvider));
    }
}
```

@sebastienros you said you preferred a classical package instead of a module. Do you have an idea how you'd implement that concretely?

**Comment by sfmskywalker** [comment]
That's looking good. Will you create a PR? I think a classical package is simply a class library like the various abstractions projects, although I don't know if there's anything more to it.

**Comment by PinpointTownes** [comment]
If we opt for the module option, yep, I can send a PR. But I think @sebastienros would prefer an `IServiceCollection` extension. And in this case, I'm not sure how it could be trivially implemented.

**Comment by PinpointTownes** [comment]
Hum, this approach will make retrieving a non-isolated `IDataProtectionProvider` a bit harder since a module will have to resolve it via its `Startup` constructor and hold it in a field for later consumption.

Related topic: https://github.com/OrchardCMS/OrchardCore/issues/1402#issuecomment-359967180 (to be able to share tokens between tenants, we'll need a way to disable the default tenant isolation logic).

**Comment by sebastienros** [comment]
@PinpointTownes Why? `services.AddDataProtectionPRoviders` will just register the services in DI and each component can then resolve it.

**Comment by PinpointTownes** [comment]
Because if we replace `IDataProtectionProvider` by a tenant-aware service in a module (as demonstrated in my snippet), the non-tenant-aware provider is no longer available inside modules components.

**Comment by sebastienros** [comment]
I see, we can then have a custom service that is providing different implementations:
`IDataProtectionProviderService` with `HostDataProtectionProvider`, `TenantDataProtectionProvider`, ...

**Comment by PinpointTownes** [comment]
We can certainly do that, but in this case, components that take an `IDataProtectionProvider` must be re-registered to take an `IDataProtectionProviderService`, otherwise the DI container will always inject the default non-tenant-aware provider.

And in this case, I'm not sure it's really simpler than what we currently have in the Users/OpenID modules.

**Comment by sebastienros** [comment]
What about a default DPP that is tenant aware and that naive client can use, and a service for specialized ones (host, timed, ...) ?

**Comment by PinpointTownes** [comment]
We can do that too. Folks who need a non-isolated DPP would have to inject it via the Startup constructor, which is pretty much the opposite of https://github.com/OrchardCMS/OrchardCore/issues/1391#issuecomment-359969331.

Note: you can very easily create a timed protector from a normal protector using `protector.ToTimeLimitedDataProtector()`. It's not really a problem for our scenario, no matter what's the option we choose.

**Comment by sebastienros** [comment]
I forgot one, can the one that is tenant specific be also cross machines?

**Comment by PinpointTownes** [comment]
If you synchronize the Data Protection key ring across your machines (and use the same "application name"), yep.

https://stackoverflow.com/questions/44844139/asos-token-validation-is-not-working-when-having-separate-authorization-server/44845613#44845613

**Comment by sebastienros** [comment]
Adding some pointer for configuration

https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x

**Comment by PinpointTownes** [comment]
@sebastienros too complicated to implement, and not really in the spirit of the new Data Protection lib, that uses a key ring instead of a static key.

Why not simply changing the default key ring location to the App_Data folder?

**Comment by sebastienros** [comment]
Good idea. What is the recommended solution when two nodes don't have a common shared folder? Are there any other service supported and already implemented?

**Comment by PinpointTownes** [comment]
> What is the recommended solution when two nodes don't have a common shared folder?

Currently, only Azure Blob Storage and Redis are officially supported by MSFT (well, the Redis storage provider is still a pre-release thing...). 2.1 will come with a third provider for Azure Key Vault.

There are also a few providers developed by the community to support 3rd-party services, including [AWS S3](https://www.nuget.org/packages/AspNetCore.DataProtection.Aws.S3/) and [AWS KMS](https://www.nuget.org/packages/AspNetCore.DataProtection.Aws.Kms/) (I use them in production and they work like a charm).

It's probable that AKV will become the recommended option in 2.1. You should pay @blowdart a visit and talk with him to confirm that.

**Comment by blowdart** [comment]
Not exactly. Protection and storage are two different things. Azure Key Vault is the protection part, it's not a key storage.

So blob storage, or just create one suitable for your SQL database, it's only a single interface.

**Comment by PinpointTownes** [comment]
> Azure Key Vault is the protection part, it's not a key storage.

Wait, are you saying the keys are not stored in AKV (as secrets) but simply KWed by AKV?

**Comment by blowdart** [comment]
Yes. Have you looked at the AKV API? We'd have to make a call for every key in a key ring to load it, no-one wants that type of startup delay.

**Comment by PinpointTownes** [comment]
> Yes.

Oooooh, that sucks :sweat: 

> We'd have to make a call for every key in a key ring to load it, no-one wants that type of startup delay.

Not sure why? You could store multiple keys in a single secret (IIRC, the limit is 25KB, so you could store approx. 12/13 keys).

Thanks for the info (that's really unfortunate as it makes the DP AKV package much less attractive if it's just for key encryption...)

**Comment by blowdart** [comment]
Even then the API let us down

1. We create keys a lot. 12-13 is going to be hit in a year by default.
2. The API for getting the secret versions and their URIs still involves pagination
3. And then a call to get each version.

Just no. We spent a lot of time with the AKV folks and key wrapping was their suggestion, so there you go.

**Comment by PinpointTownes** [comment]
> Just no.

Well, that's exactly what you guys did for the AKV configuration source, which has the perf implications 😅 

But I get your point. Too bad the AKV folks didn't make that better (e.g by allowing larger secrets).

**Comment by PinpointTownes** [comment]
A few words about the plan the way I envision it:

  - We'll have a new `OrchardCore.DataProtection.Core` package containing `ISharedDataProtectionProvider` and `SharedDataProtectionProvider` (a simple wrapper around the `IDataProtectionProvider` provided by the host. i.e the non-isolated one).

  - A new `DataProtection` module will be introduced to care care of replacing `IDataProtectionProvider` by a tenant-isolated instance and preserving the original provider via `ISharedDataProtectionProvider`. This will allow us to simplify the `Users` and `OpenId` modules as we'll no longer have to manually replace the default provider in the Identity cookies/OpenIddict options.

```csharp
/// <summary>
/// Represents a non-isolated ASP.NET Core Data Protection provider
/// that can be used to encrypt/decrypt data between separate tenants.
/// </summary>
public interface ISharedDataProtectionProvider : IDataProtectionProvider { }
```

```csharp
public class SharedDataProtectionProvider : ISharedDataProtectionProvider
{
    private readonly IDataProtectionProvider _dataProtectionProvider;

    public SharedDataProtectionProvider(IDataProtectionProvider dataProtectionProvider)
    {
        _dataProtectionProvider = dataProtectionProvider;
    }

    public IDataProtector CreateProtector(string purpose)
        => _dataProtectionProvider.CreateProtector(purpose);
}
```

```csharp
public class Startup : StartupBase
{
    private readonly IDataProtectionProvider _dataProtectionProvider;
    private readonly ShellSettings _shellSettings;

    public Startup(
        IDataProtectionProvider dataProtectionProvider,
        ShellSettings shellSettings)
    {
        _dataProtectionProvider = dataProtectionProvider;
        _shellSettings = shellSettings;
    }

    public override void ConfigureServices(IServiceCollection services)
    {
        // Replace the global data protection provider by a tenant-aware instance so that modules that
        // internally rely on IDataProtector/IDataProtectionProvider automatically and transparently get
        // an isolated instance that doesn't allow decrypting payloads encrypted by another tenant.
        // Services that need to retrieve a non-isolated protector can use ISharedDataProtectionProvider.
        services.TryAddSingleton<ISharedDataProtectionProvider>(
            new SharedDataProtectionProvider(_dataProtectionProvider));

        services.Replace(ServiceDescriptor.Singleton(typeof(IDataProtectionProvider),
            _dataProtectionProvider.CreateProtector(_shellSettings.Name)));
    }
}
```

  - Now that antiforgery cookies will be protected by tenant-specific data protectors, we'll need to replace the default cookie names to be tenant-specific to avoid collisions (exactly like what the `Users` module does with the Identity cookies). A new `Antiforgery` module will be responsible of that:

```csharp
public class Startup : StartupBase
{
    private readonly string _tenantName;
    private readonly string _tenantPrefix;

    public Startup(ShellSettings shellSettings)
    {
        _tenantName = shellSettings.Name;
        _tenantPrefix = "/" + shellSettings.RequestUrlPrefix;
    }

    public override void ConfigureServices(IServiceCollection services)
    {
        services.AddAntiforgery(options =>
        {
            options.Cookie.Name = "orchantiforgery_" + _tenantName;
            options.Cookie.Path = _tenantPrefix;
        });
    }
}
```

**Comment by PinpointTownes** [comment]
> We'll have a new OrchardCore.DataProtection.Core package containing ISharedDataProtectionProvider and SharedDataProtectionProvider (a simple wrapper around the IDataProtectionProvider provided by the host. i.e the non-isolated one).

I almost miss the good old days when we used to have named services... :trollface: 

```csharp
public class Service
{
    private readonly IDataProtectionProvider _dataProtectionProvider;

    public Service([KeyFilter("Shared")] IDataProtectionProvider dataProtectionProvider)
    {
        _dataProtectionProvider = dataProtectionProvider;
    }
}
```

**Comment by PinpointTownes** [comment]
Change of plan: @sebastienros prefers the "one key ring per tenant" approach.

While there's no benefit from a security perspective (because well... tenants are hosted in the same process, so they can access each other's rings if one of them contains malicious code), this gives a bit more flexibility for export scenarios, where a tenant from an Orchard site A is moved to an Orchard site B with its master keys.
