### ISSUE TITLE
[graphQL] named part fields return nulls when Collapsed is checked

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#13926]
When you will add Named Part to the **ContentType** and also check "Collapse" checkbox, data is not returned using GraphQL.

Steps to reproduce:
1. create new **ContentPart** and add at least one field,
2. create new **ContentType** and add newly created named part, mark **Collapse** checkbox in part settings,
3. create new **ContentItem** and fill all fields,
4. enable **GraphQL** feature and try to query the data.

Here is the result:
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/6db4a8ea-089d-4da3-b781-3674dd37b185)

I've just fixed this issue and will create PR soon.

Also there is an issue when you will try to add many parts with same field names, if those parts are also "collapsed" this will result with an exception:
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/d557c603-d2d2-4a8f-a17e-e45ddfe4c184)

To solve this problem, I've added a few methods to prevent fields name collisions:
- graphQL field name is build based on part it belongs to,
- graphQL field name is build using defined prefix,
- graphQL field name is build using defined suffix.

Here is simple example, first option is selected to prevent graphQL fields name colliosions:
[graphql.webm](https://github.com/OrchardCMS/OrchardCore/assets/6403130/397fd2bf-cfd0-49cf-839e-4ad00f679a15)

**Comment by lampersky** [comment]
repro recipe:

```
{
  "name": "",
  "displayName": "",
  "description": "",
  "author": "",
  "website": "",
  "version": "",
  "issetuprecipe": false,
  "categories": [],
  "tags": [],
  "steps": [
    {
      "name": "ContentDefinition",
      "ContentTypes": [
        {
          "Name": "Test",
          "DisplayName": "Test",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true
            },
            "FullTextAspectSettings": {
              "IncludeBodyAspect": false,
              "IncludeDisplayText": false
            },
            "GraphQLContentTypeSettings": {}
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "Test",
              "Name": "Test",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            },
            {
              "PartName": "MyCustomPart",
              "Name": "FirstCustomPart",
              "Settings": {
                "ContentTypePartSettings": {
                  "DisplayName": "FirstCustomPart",
                  "Position": "1"
                },
                "GraphQLContentTypePartSettings": {
                  "Collapse": true
                }
              }
            }
          ]
        }
      ],
      "ContentParts": [
        {
          "Name": "MyCustomPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true,
              "Reusable": true
            }
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "TextField",
              "Name": "MyTextField",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "MyTextField",
                  "Position": "0"
                }
              }
            },
            {
              "FieldName": "NumericField",
              "Name": "MyNumericField",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "MyNumericField",
                  "Position": "1"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "name": "content",
      "data": [
        {
          "ContentItemId": "4v1fbrhmge59363b2xazhvqzn7",
          "ContentItemVersionId": "477dyvm4pwe08sxy0dr9zn8fds",
          "ContentType": "Test",
          "DisplayText": null,
          "Latest": true,
          "Published": true,
          "ModifiedUtc": "2023-06-28T20:09:45.4796976Z",
          "PublishedUtc": "2023-06-28T20:09:45.5341524Z",
          "CreatedUtc": "2023-06-28T18:48:34.9074555Z",
          "Owner": "4n9sky1p11g7k22vrsh878zang",
          "Author": "lampersky",
          "Test": {},
          "FirstCustomPart": {
            "MyTextField": {
              "Text": "t1"
            },
            "MyNumericField": {
              "Value": 1234.0
            }
          },
          "SecondCustomPart": {
            "MyTextField": {
              "Text": "t2"
            },
            "MyNumericField": {
              "Value": 2345.0
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by sebastienros** [comment]
`PreventFieldNameCollisionMethod` I wonder why we would not want that to be always true, when would you want collisions that don't work? Or is that a breaking change that existing field names are now difference with the PR? Maybe at least for named parts always include the name of the part in the schema where I assume the Part name was used for non-named parts? That would solve everything while not requiring custom settings. Also I believe it should not break because it was already broken?

**Comment by lampersky** [comment]
> `PreventFieldNameCollisionMethod` I wonder why we would not want that to be always true

yes, it could be always true, but I implemented this in a bit more flexible way, so the user can choose when and which method to use, sometimes you may want field names to **not** be prefixed with part name, this could be useful when you only have one named part and you are 100% sure that there is no collision with other fields, so the final field name in graphql is super simple like **myTextField**, if we always include part name, this name will be a bit longer **partNameMyTextField**

> Also I believe it should not break because it was already broken?

exactly

@sebastienros if you want me to get rid of custom settings and always include part name in schema for collapsed fields, just let me know and I will adjust the PR.

**Comment by sebastienros** [comment]
I think this is necessary for backward compatibility at least. And the default value should be `none`.

**Comment by lampersky** [comment]
I've just removed all those **PreventFieldNameCollisionMethods**, now it is just simple checkbox, visible only when **collapsed** checkbox is checked. So, you can decide, whether to prevent collisions or not. 

[prevent-name-collisions.webm](https://github.com/OrchardCMS/OrchardCore/assets/6403130/8cff8b00-4e66-42eb-a551-a7867522826a)
