### ISSUE TITLE
Move app.UseAuthentication() to a separate OrchardCore.Authentication module

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#1392]
In ASP.NET Core 2.0, all the individual authentication middleware have been replaced by multiple handlers + a single "dispatcher" called `AuthenticationMiddleware`, that can be registered only once in the pipeline (otherwise, very weird things happen).

Currently, this middleware is registered by the Users module but is indirectly used by the OpenID module for both the OIDC server and token validation features.

While it's not a big deal for the OIDC server feature since it can't be used without the Users module, the token validation feature doesn't need it to work (in a future PR, we're going to split the server/validation features). But since the authentication middleware is only registered by the Users module, one has to enable it for automatic authentication to work correctly.

This is far from ideal. To fix that, I suggest moving `app.UseAuthentication()` to a separate module and updating OrchardCore.Users and OrchardCore.OpenId to depend on it.

**Comment by PinpointTownes** [comment]
@sebastienros no objection?

**Comment by sebastienros** [comment]
GTG
