### ISSUE TITLE
Liquid & JavaScript Editor ViewComponents

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1393]
While working on the Workflows module, I have been copy and pasting CodeMirror initialization code on a few occasions in order to display a rich code editor into which users can enter script or Liquid. Instead of keeping this duplicated code, I propose we build one or two reusable view components. We could have one for JS and one for Liquid, or we could have a more general-purpose CodeMirror view component that is configurable.

**Comment by sebastienros** [comment]
Not sure it's very hard to create a code mirror editor. And we might have different behaviors for live preview, and custom syntax highlighting. Point me to some code you had to copy paste. If it's just 1 or 2 lines then I don't think you'd gain much.
