### ISSUE TITLE
Setup Problem: SqlException: Invalid object name 'Document'.

### ISSUE THREAD

**Issue by adamongithub** [OrchardCMS/OrchardCore#1395]
When attempting to setup a new site with a locally hosted Sql Server. Obtaining the connection string via Visual Studio 2017's Sql Server Object Explorer proceeds, but then throws the following exception:

`An unhandled exception occurred while processing the request.
SqlException: Invalid object name 'Document'.
System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__108_0(Task<SqlDataReader> result)

Stack Query Cookies Headers
SqlException: Invalid object name 'Document'.
System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__108_0(Task<SqlDataReader> result)
System.Threading.Tasks.ContinuationResultTaskFromResultTask.InnerInvoke()
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state)
System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Dapper.SqlMapper+<QueryAsync>d__23.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
YesSql.Services.DefaultQuery+Query+<>c__DisplayClass3_1+<<FirstOrDefaultImpl>b__1>d.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
YesSql.Store+<ProduceAsync>d__30.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
YesSql.Services.DefaultQuery+Query+<FirstOrDefaultImpl>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager+<GetShellDescriptorAsync>d__6.MoveNext() in ShellDescriptorManager.cs
+
                _shellDescriptor = await _session.Query<ShellDescriptor>().FirstOrDefaultAsync();
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager+<UpdateShellDescriptorAsync>d__7.MoveNext() in ShellDescriptorManager.cs
+
            var shellDescriptorRecord = await GetShellDescriptorAsync();
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OrchardCore.Setup.Services.SetupService+<SetupInternalAsync>d__14.MoveNext() in SetupService.cs
+
                    await scope
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
OrchardCore.Setup.Controllers.SetupController+<IndexPOST>d__10.MoveNext() in SetupController.cs
+
            var executionId = await _setupService.SetupAsync(setupContext);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
lambda_method(Closure , object )
Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OrchardCore.DeferredTasks.DeferredTaskMiddleware+<Invoke>d__3.MoveNext() in DeferredTaskMiddleware.cs
+
            await _next.Invoke(httpContext);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OrchardCore.Modules.ModularTenantRouterMiddleware+<Invoke>d__4.MoveNext() in ModularTenantRouterMiddleware.cs
+
            await pipeline.Invoke(httpContext);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OrchardCore.Modules.ModularTenantContainerMiddleware+<Invoke>d__4.MoveNext() in ModularTenantContainerMiddleware.cs
+
                        await _next.Invoke(httpContext);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
OrchardCore.Modules.ModularTenantContainerMiddleware+<Invoke>d__4.MoveNext() in ModularTenantContainerMiddleware.cs
+
                    }
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()`

**Comment by jtkech** [comment]
Yes, it works with sqlite but i got exactly the same with sql server.

There have been some recent changes on `yessql`, @sebastienros will fix it soon.

Maybe when adding more spaces in the `SqlServerDialect`, maybe a missing leading space [in this line](https://github.com/sebastienros/yessql/blob/8bf596fe297b332758da67fc4ef7527b09cf1585/src/YesSql.Provider.SqlServer/SqlServerDialect.cs#L121).

**Comment by ashishpd** [comment]
Are there any instructions on getting the beta build?

**Comment by jtkech** [comment]
The changes i'm referring are not related to the `Master` branch, they concern the `Dev` branch which produce `1.0.0-beta2-****` nightly build packages on myget. If you use this feed you may need to fallback temporarily to a previous version. Sorry for the inconvenience.

**Comment by sebastienros** [comment]
The issue is with Table prefix, I already fixed it in YesSql, should be in Orchard very soon.

**Comment by jtkech** [comment]
👍
