### ISSUE TITLE
Add a way for admins to disable 2FA for a user

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13954]
### Is your feature request related to a problem? Please describe.
There are times where a user can no longer use 2FA and has no more access to the recovery codes. And admin should have a way to disable 2FA from the Users admin UI.

Also when the `Two-Factor Email Method` feature is enabled, it may be helpful to add an option to email the user a single recovery code to login with.

I think we should Add a new `Actions` button next to the user and move both `Delete` and `Edit Password` into the `Actions` button. Additionally, inject `Disable two-factor` item in the Actions menu when `Two-Factor Authentication Services` feature is enabled.

And when the  `Two-Factor Email Method` feature is enabled, add another item to allow sending the user a single recovery code when the user has a confirmed email.

@Piedone

**Comment by Piedone** [comment]
A single-use recovery code would be great, though I think a simple disable 2FA is also enough: At this point, you as an admin should do whatever specific to the use-case you can do to make sure the user is legit. I'm not sure if another e-mail helps too much here.

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/13955
