### ISSUE TITLE
AutoSetup issue with "/" RequestUrlPrefix

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#13952]
AutoSetup throws a validation error when trying to create a tenant with "/" RequestUrlPreix.

The ultimate intent is to create a default tenant at /default and the auth server tenant at /.

cc @jtkech

**Comment by devlife** [comment]
To clarify this a bit, we want the default tenant _not_ to be at the root and to have another tenant at the root.

**Comment by Skrypt** [comment]
And here it prevents us from doing so : 

https://github.com/OrchardCMS/OrchardCore/blob/d41754184659c0d17246092edaeb8dc775479c3c/src/OrchardCore.Modules/OrchardCore.AutoSetup/Options/TenantSetupOptions.cs#L119-L122

**Comment by devlife** [comment]
Yes I did try that @jtkech. No matter what we put for the default tenant `RequestUrlPrefix` it always ends up empty and we are not allowed to have an empty value for the non-default tenant that we want to live at the root.

**Comment by jtkech** [comment]
Ah okay I see, I will look at it this night, hmm and also allow this scenario through the admin and api controllers.

**Comment by jtkech** [comment]
@Skrypt @devlife

Okay done through #13958, if you have time to try it remember to not set any prefix including a `/`.

**Comment by devlife** [comment]
This worked great! It created all three tenants as expected. The default tenant had a non-blank url prefix, another tenant with a blank url prefix, and a third tenant just for the heck of it.

**Comment by jtkech** [comment]
Cool, thanks for trying
