### ISSUE TITLE
Liquid 'sort' filter issues

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1397]
I'm having some difficulty  in getting the `sort` filter to work as expected when trying to sort content items. I think it **might** be related to `MemberAccessStrategies`.

Repro:

1. Create a query that pulls back content items. The rest of the repro steps assume that the `TitlePart` is attached.
1. Try and sort the results of the query by title, the items will not be sorted correctly:

```
        {% assign content = "Content" | query | sort: "Content.TitlePart.Title" %}
        {% for c in content %}
        <li>
            {{ c.Content.TitlePart.Title }}
        </li>
        {% endfor %}
```

I created a copy of the sort filter so that I could attach a debugger:

```
var member = arguments.At(0).ToStringValue();

return new ArrayValue(input.Enumerate().OrderBy(x => x.GetValue(member, context).ToObjectValue()).ToArray());
```

`x.GetValue(member, context)` returns a `NilValue`, where `x` is an instance of `ContentItem` and member is `Content.TitlePart.Title`, which is what leads me to think this is a member access issue.

**Comment by sebastienros** [comment]
I am looking at the code for the sort filter and it might be that it is that I was not expecting expressions in the argument. The current unit tests already sorts on a property, so it works, I will see with expressions.
