### ISSUE TITLE
Rename Azure AD wording to Microsoft Entra ID

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#13990]
### Is your feature request related to a problem? Please describe.
Since naming products was never a strong point of Microsoft, they're renaming Azure AD to Microsoft Entra ID, see https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-is-becoming-microsoft-entra-id/ba-p/2520436. This necessitates that we also rename the Azure AD-related terminology.

### Describe the solution you'd like
Rename the user-facing strings (but not technical IDs) of the [Azure AD feature](https://docs.orchardcore.net/en/latest/docs/reference/modules/Microsoft.Authentication/#azure-active-directory), both in the code and in the docs. Also include the old name though, so people searching for Azure AD will still be able to find everything. Mike did something similar under [this PR](https://github.com/OrchardCMS/OrchardCore/pull/13852) for Facebook -> Meta.

### Describe alternatives you've considered
Also renaming the technical IDs, but that would be a breaking change. It'd get rid of some technical debt though.

**Comment by hishamco** [comment]
Seems I'm late to log this one :)
