### ISSUE TITLE
Make DocumentId and Id properties long instead of int

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13997]
### Is your feature request related to a problem? Please describe.
By default, we use `long` as the default type for the database key. But, we are still using `int` for the ContentItem.

I'll submit a PR for this.

**Comment by jtkech** [comment]
Oops, looks like there are much more places to update

If we search for `public int Id` we get 19 results , for example in `User.cs`.

If we search for `public int DocumentId` we get 9 results , e.g. in `UserIndex` and `ContentItemIndex`.

---

Also with `Sqlite`, the `DocumentId` of an index table (related to the `Id` of the `Document` table) is also a long, but the `Id` of the index table itself is still an int. This is not the case with `Sql Server`, maybe a problem on `YesSql` side or a limitation of `Sqlite`.

---

For the special `IndexingTask` table, anyway we still create explicitly an `Id` column of type int.

            SchemaBuilder.CreateTable(nameof(IndexingTask), table => table
                .Column<int>(nameof(IndexingTask.Id), col => col.PrimaryKey().Identity())
                ...
           );

We should use the current `IdentityColumnSize` option.

            var identityColumnSize = _shellSettings.GetIdentityColumnSize();
            SchemaBuilder.CreateTable(nameof(IndexingTask), table => table
                .Column(identityColumnSize, nameof(IndexingTask.Id), col => col.PrimaryKey().Identity())
                ...
           );

**Comment by MikeAlhayek** [comment]
@jtkech you are right. I made more changes to the PR to change all the Id/DocumentId properties in many places.
