### ISSUE TITLE
ContentManager.GetAsync(string[]) returns inconsistent results when there are duplicate ids

### ISSUE THREAD

**Issue by MEllis-Bethany** [OrchardCMS/OrchardCore#14018]
### Describe the bug
If the `GetAsync(string[])` is called multiple times with a string array containing duplicate content item ids, the results are inconsistent.
The first time the function is called, each content item is returned only once; even if the id is given twice.
Every call after that, duplicate content items appear if the id is passed into the function twice.

### To Reproduce
1. Call `ContentManager.GetAsync(string[])` with some string array with duplicate ids. e.g. `["ContentItemId-A", "ContentItemId-A"]`
2. Call `ContentManager.GetAsync(string[])` with the same string array with duplicate ids. (The calls can be made one after another with the same array.)
3. The first call will only return 1 result. The second call will return 2 results.

### Expected behavior
The duplicate content items are NOT returned. It should be a list with only distinct content items.

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/77845944/7eedc371-a9a7-4f84-b7d4-5df4df8eb9e7)
![image](https://github.com/OrchardCMS/OrchardCore/assets/77845944/0a187e16-b2bc-418a-a3d1-e7b123ecf3f2)

**Comment by hishamco** [comment]
Thanks for reporting this, could you please elaborate what's the difference between both arrays, so I can reproduce the issue

**Comment by jtkech** [comment]
@MEllis-Bethany Yes maybe a problem when it retrieves items from the scoped session cache, if so I will look at it and fix it this night.

**Comment by MEllis-Bethany** [comment]
@hishamco ArrayA has "Report Process Flow" once, ArrayB has it twice.

**Comment by sebastienros** [comment]
Drafts vs published items. Seems like a bug in the session cache that doesn't distinguish correctly.

**Comment by jtkech** [comment]
Okay, I could repro and fixed it locally, I will provide a PR soon.

**Comment by hishamco** [comment]
Seems JK was so fast to get this done :)
