### ISSUE TITLE
Running dev database no longer working with Docker after upgrading from 1.4 to 1.6

### ISSUE THREAD

**Issue by djjohnsonplymouth** [OrchardCMS/OrchardCore#14017]
I tend to run a docker container to host my database when developing. Specifically, a SqlServer database. I use SqlServer databases from Azure in production and this helps me identify data related bugs more easily in development.

Recently, I upgraded from 1.4 to 1.6 and auto setup seemed to only create the Document and Identifier tables and nothing works, when using a docker container. 

However, the classic SQLite works.

I notice that there were some breaking changes in 1.5 regarding YesSql where we were advised to add the "TrustServerCertificate=True" or "Encrypt=false". I have tried both of these settings. 

Here is my connection string with redacted passwords etc....: 

```
{
"ConnectionString": "Server=tcp:localhost; Database=******; User=****; Password=***********; MultipleActiveResultSets=True; Encrypt=false;",
  "DatabaseProvider": "SqlConnection",
}
```

I have been using this setup for well over a year with no problems on several other projects. Projects which haven't been upgraded to Orchard 1.6 seem fine.

Any help would be very much appreciated.

**Comment by hishamco** [comment]
Before `1.6.0`, nothing needs to be added regarding the trust certificate

**Comment by djjohnsonplymouth** [comment]
Hi @hishamco Thanks for your reply. I have just tried with 1.5, this worked as normal. It successfully creates the sqlite database and, once I change the connection string to use my docker db, the setup works as it always has. 
However, when I try with 1.6, sqlite is fine but my sqlserver docker db only creates the document and identifier tables and nothing more. No setup recipes, just plain old fashioned cos project run. My browser shows "This localhost page can’t be found". The console reports 404, clearly because the db is only partially populated. I am tempted to say that this might be an issue in either the OrchardCore or the YesSql code base. Nothing is reported in my orchard logs. Browser only reports 404. Any other thoughts at all?

**Comment by hishamco** [comment]
> because the db is only partially populated

This is means the connection is worked as expected, could you please check the OC logs

**Comment by djjohnsonplymouth** [comment]
I also notice that the following lines have been added to the app settings in app_data folder. 
`"DocumentTable": "Document",
  "IdentityColumnSize": "Int64",
  "TableNameSeparator": "_"`
Could anyone explain why this has been added?

**Comment by djjohnsonplymouth** [comment]
@hishamco Yes, the connection is fine but the creation of the database fails part way through. Nothing in the OC Logs unfortunately. The database only seems to have the duo.Document and db.Identifiers tables. When it should have loads more. Here is a screenshot of what it is creating with 1.5:

![Orchard1-5-SQLServer](https://github.com/OrchardCMS/OrchardCore/assets/34646578/e00a8fcd-86bc-4db5-844f-fcd6b0ee4890)

 and here is a screenshot of what if created with 1.6:

![Orchard1-6-SQLServer](https://github.com/OrchardCMS/OrchardCore/assets/34646578/2af7ff9e-c199-4b03-88d9-c34b9d8abb6c)

**Comment by hishamco** [comment]
Could you try to reproduce the issue locally (without using docker)?

**Comment by djjohnsonplymouth** [comment]
@hishamco I am not sure what difference that would make? I am using a Mac with Azure data studio and docker running on Localhost.

**Comment by hishamco** [comment]
I just want to reproduce the issue locally

**Comment by djjohnsonplymouth** [comment]
Here is my setup.

1. I first setup a server on azure data studio. Then, create an empty database in this server on localhost using this SQL script: CREATE DATABASE <NAME_OF_YOUR_DATABASE>

2. Setup docker instance (this will depend on what environment you are using).

`docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=<YOURPASSWORD>' -e 'MSSQL_PID=Developer' -e 'MSSQL_USER=<YOURUSER>' -p 1433:1433 -d --name=sql mcr.microsoft.com/azure-sql-edge`

3. Start the container.

4. Create a new OrchardCore 1.6 CMS project.

5. Run it.

6. Check the SQLite db has been created as expected in the App_Data/Sites/Default folder.

7. Change connection string in App_Data/Sites/Default/appsettings.json to this (change for your setup).

`{
  "ConnectionString": "Server=tcp:localhost; Database=<YOURDATABASENAME>; User=<YOURUSER>; Password=<YOUR_PASSWORD>; MultipleActiveResultSets=True; Encrypt=false;",
  "DatabaseProvider": "SqlConnection"
}`

or

`{
  "ConnectionString": "Server=tcp:localhost; Database=<YOURDATABASENAME>; User=<YOURUSER>; Password=<YOUR_PASSWORD>; MultipleActiveResultSets=True; Encrypt=false;",
  "DatabaseProvider": "SqlConnection",
"DocumentTable": "Document",
  "IdentityColumnSize": "Int64",
  "TableNameSeparator": "_"
}`

Re-run the project. Setup as usual. Partial database fail and 404 reported in browser. Nothing in the OC logs.

**Comment by djjohnsonplymouth** [comment]
I think it may have something to do with mapping the Index tables.

**Comment by djjohnsonplymouth** [comment]
Further points to consider. I actually think this is likely an Apple M1 issue, relating to my Docker instance.
I have replicated on another M1 computer.
However, an intel computer works fine. Therefore, I will close this bug and dig into my docker instance instead.
Thanks for your help @hishamco Very much appreciated.

**Comment by jtkech** [comment]
We had an issue with MySQL depending on the collation that we fixed quite recently, I will check it this night ;)

**Comment by jtkech** [comment]
@djjohnsonplymouth 

Here the related PR I mentioned https://github.com/OrchardCMS/OrchardCore/pull/13585#issuecomment-1553700024

Also from memory, we don't recommend to use `MultipleActiveResultSets`, some people used it to prevent locking issues but most of the time it was due to a bad code pattern in a given scope, resulting for example in non awaited tasks.
