### ISSUE TITLE
need more  libraries to determine the mime

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#14024]
### Describe the bug

Go to 'Microsoft.AspNetCore.StaticFiles.IContentTypeProvider'
_contentTypeProvider.TryGetContentType(mediaFile.Name, out var contentType);

### Expected behavior
it seeems that in .net core,   _contentTypeProvider.TryGetContentType(mediaFile.Name, out var contentType); cannot give out the required contentType for all contentTypes, maybe we need more way, such as MimeKit or other libraries to determine the mime if the calling return false

**Comment by sebastienros** [comment]
Examples of files that don't work?
