### ISSUE TITLE
Suggestions on Modules management

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#1403]
1. Renaming module `/Content` folders to `wwwroot` to be clearer about its usage.

2. Because now assets are embedded, maybe we could make things lighter in many areas, **loaders**, **search locations** ... We could still have a module under the web app (or any other location) if the web app use the right `AddExtensionLocation()`, but it is useless if the project reference `OC.Module.Targets`.

- So, e.g search locations seems to be only useful for a theme without any assembly (not compiled).

3. Get rid of `Module.txt` manifest files by using e.g assembly attributes. But in this case, a theme couldn't be without any assembly as mentioned above, it should be compiled.

4. Finally, because now `README.md` files are also embedded (we could exclude them) we could think about **an embedded doc**. Maybe through the existing `OC.Features` by adding in the `Modules` page a `Doc` button for the main feature of each module to display the related `README.md`.

I will start to rename module `/Content` folders to `wwwroot`, unless you think it is not worth. Hmm, because of the special name of `wwwroot`, i hope that msbuild will not bother us.

**Comment by sfmskywalker** [comment]
1. Not sure `wwwroot` is a good name to use in modules, because traditionally there's supposed to be a single such folder. In other words, it might potentially be confusing by thinking that somehow there are multiple `wwwroot`s. Do you think `/Content` is confusing because of the `OrchardCore.Contents` module?

2. Lighter sounds definitely good, but I'm unsure what you're proposing.

3. The Module manifest has a nice format especially for declaring dependencies per feature. What would this look like when expressed completely by assembly attributes?

4. What would be the advantage of an embedded doc? Display inside the admin?

**Comment by jtkech** [comment]
@sfmskywalker Thanks for your feedback, no time right now but i will complete my answer this night.

> Not sure wwwroot is a good name

Me too, just heard @sebastienros talking about it in a meeting video.

**Comment by Jetski5822** [comment]
We spoke about getting rid of module manifest files before in favour of something else... like assembly attributes. I dont remember why we stuck with module.txt files.

**Comment by sebastienros** [comment]
@Jetski5822 because at that time we were loading modules dynamically, so we needed a way to find the folder that were actually modules. Now we reference them, so we can just use some assembly attributes and browser all the loaded one for these attributes.

I suggested `wwwroot` because that the default for a standard app, and if follows the way we shape modules to be micro-applications, following exactly what you would do in a standard app. `/Content` is exactly what `wwwroot` is.

**Comment by sebastienros** [comment]
@jtkech Please do these changes in separate PRs because we might change our mind when we discover some issues or realize how wrong we were.

**Comment by Jetski5822** [comment]
Perfect!!! Let’s do it :)

**Comment by sfmskywalker** [comment]
>  if follows the way we shape modules to be micro-applications, following exactly what you would do in a standard app. /Content is exactly what wwwroot is.

That makes sense.

**Comment by jtkech** [comment]
Okay, i will do separate PRs.

- **1. wwwroot**: So, seems to be ok, i will start with it.

- **3. Module.txt**: I don't want to do it if @sfmskywalker doesn't agree.

@sfmskywalker as you asked about 3. and 4.

> Lighter sounds definitely good, but I'm unsure what you're proposing.

Need to be seen more in depth but i first thought about extension loaders and extension expander locations. When i will have more thinkings on this i will let you know, maybe in another issue / PR.

> What would be the advantage of an embedded doc? Display inside the admin?

Yes in the admin, e.g in the `Modules` page a button for each module main feature just to display the readme markdown file. I don't know if it could be useful, just a suggestion because right now readme files are also embedded, so just because they are there and available.

**Comment by sebastienros** [comment]
Please file a bug to track these two tasks. The optimisations don't need a bug. And I don't like the embedded documentation idea. Thanks.

**Comment by jtkech** [comment]
Okay cool, i will do. As said, i will start with `wwwroot` after having opened an issue for it.

Finally i will remove `Module.txt` even @sfmskywalker doesn't agree ;)

No, its arguments are relevant, so good to also open an issue for it to have more feedbaks. Anyway i think i will need some help to finalize it if we do it.

**Comment by sfmskywalker** [comment]
I don’t disagree with replacing module manifest txt with assembly attributes, nor do I agree. I was just wondering how it would look in the form of assembly attributes when you declare a feature and it’s dependencies. But come to think of it, it would probably as simple as:  `[Feature( Name=“”, DisplayName=“”, Description=“”, Dependencies=“Feature1, Feature2, etc...”)]`

Could be good!

**Comment by sebastienros** [comment]
I think @Jetski5822 made some suggestions a while ago. We should iterate on the format too, @jtkech can come with some proposal, but I expect there will be some negotiations.

**Comment by jtkech** [comment]
I didn't start to work on it, just saw that for an assembly attribute you can pass a string or an array of strings. So, as a starting point, just tried the following which compiles.

Note: i used `AllowMultiple = true`.

    using System.Reflection;

    [assembly: ModuleFeature(new string[]
    {
        "OrchardCore.Lucene:",
            "Name: Lucene",
            "Description: Introduces a preconfigured container-enabled content type.",
            "Category: Content Management",
            "Dependencies: OrchardCore.Indexing, OrchardCore.Liquid",
    })]

    [assembly: ModuleFeature(new string[]
    {
        "OrchardCore.Lucene.Worker:",
            "Name: Lucene Worker",
            "Description: Provides a background task to keep local indices in sync with other instances.",
            "Category: Content Management",
            "Dependencies: OrchardCore.Lucene"
    })]

    namespace System.Reflection
    {
        [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
        public sealed class ModuleFeatureAttribute : Attribute
        {
            public ModuleFeatureAttribute(string[] feature)
            {
                Feature = feature;
            }

            public string[] Feature { get; }
        }
    }

**Comment by sebastienros** [comment]
What about dedicated classes for module and features? Then to can build
them with a 'new' keyword. Like Json.
