### ISSUE TITLE
Orchard setup error when deleting only database

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#1404]
To repro this you need to have a default site folder from a previous installation and remove only the sqllite database in that folder to be able to complete the setup. On the next screen you will get :  
![image](https://user-images.githubusercontent.com/3228637/35307844-eab3a758-0072-11e8-9956-44a4687ad281.png)

It seems to also break the recipes from getting applied afterward.
![image](https://user-images.githubusercontent.com/3228637/35307938-345e90b6-0073-11e8-8e4f-dfcd85bde274.png)

Suggested change in MediaStep.cs :  

```C#
                    if (!File.Exists(file.Path))
                    {
                        await _mediaFileStore.CreateFileFromStream(file.Path, stream);
                    }
```

Though maybe it would be best to catch the exception and ask for either overwriting files or not.

Other suggestion IS to just use the overwrite = true param of that function: 

```C#
await _mediaFileStore.CreateFileFromStream(file.Path, stream, true);
```
Doing this would mean that we assume that running any recipe would overwrite any files.

**Comment by sebastienros** [comment]
So you are trying to go through a recipe and a media is already existing.

I assume we should just overwrite the existing file, or rename the previous one, and maybe do that using an option in the recipe step, like `Overwrite: false` with a default to `true`.

**Comment by Skrypt** [comment]
I actually just changed from one branch to another and did a reset on the local changes. Normally it should have found that I had a previous succesfull installation of a "default" website tenant. So there's 2 issues there I think.

**Comment by Skrypt** [comment]
I think this issue is fixed since now if the setup fails it will set the setup in a state that we can get back to it to complete the installation. @jtkech
