### ISSUE TITLE
cannot see custom features

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#14071]
### To Reproduce
1. Go to 'on current dev branch, Add any community module or my own Module to the Orchardcore sln'
2.  'run it'

cannot see custom features
### Expected behavior
should see the features from community or my module as before

**Comment by MikeAlhayek** [comment]
I think you have to add the module to the `.Cms.Web` or the `.Mvc.Web` project depending which one is set at your start up.

**Comment by infofromca** [comment]
oh, yes, my mistake. forgot something
