### ISSUE TITLE
WYSIWYG editor icons not displaying

### ISSUE THREAD

**Issue by jhdrn** [OrchardCMS/OrchardCore#1408]
The icons for the WYSIWYG editor is not showing up. Trumbowyg tries to load it's icons from /OrchardCore.Resources/Scripts//ui/icons.svg which results in a 404 Not found. When the double slash in the path is replaced with a single slash, the file is served correctly. 

This seems to be an issue with Trumbowyg and I created a pull request https://github.com/Alex-D/Trumbowyg/pull/701 with a fix. 

In the meantime I guess the SVG path could be set manually according to the docs: https://alex-d.github.io/Trumbowyg/documentation/#svg-icons.

**Comment by jhdrn** [comment]
The Trumbowyg pull request was accepted so I guess we'll have to wait for a new release and update the dependency.

**Comment by agriffard** [comment]
I tested and even if the path is //ui/icons.svg, this is working for me.

**Comment by jtkech** [comment]
I could repro.

While in dev mode we still serve static files from physical locations, otherwise we use a custom file provider, so i could repro by starting the app from the command line.

I think it is easy to fix, just replace `//` with `/`, just need to do be sure if it's normal to allow this but seems to be allowed by the physical file provider, or maybe at a lower lever by the file system.

No time right now, i will search on this this night and then fix it.

**Comment by sebastienros** [comment]
In the same topic, the visibility toggle for the connection string is broken since a recent update of BS.

**Comment by jtkech** [comment]
The visibility toggle also works for me when doing a setup in debug mode or through the command line.

**Comment by sebastienros** [comment]
CAn you share a screenshot of this toggle? It was ugly on my machine. Maybe I need to refresh the css files, but I can't start OC anymore ;/

**Comment by jtkech** [comment]
- Before toggling

![toggle1](https://user-images.githubusercontent.com/8586360/35364922-1ccc5050-0172-11e8-9d6b-3777a68f9d16.png)

- After toggling

![toggle2](https://user-images.githubusercontent.com/8586360/35364927-2130a4de-0172-11e8-906a-ad4652fb97c5.png)

**Comment by sebastienros** [comment]
Sure it works, but it was more beautiful. And the icon gave some UI hint about the state.

**Comment by jtkech** [comment]
Ah okay, i don't remember well how it was.
First i don't see any network issue.
Need to think about this.

**Comment by sebastienros** [comment]
Here it is : https://www.youtube.com/watch?v=HeDjv3blBjQ&feature=youtu.be&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&t=2026

**Comment by jtkech** [comment]
Ah okay

> gave some UI hint about the state

You mean not the same icon if showed or hidden

Before installing node modules and run gulp tasks, did you try to update static files by running gulp?

**Comment by jtkech** [comment]
What i see is that we replaced `tether.js` with `popper.js`. Need to see what they do

**Comment by jtkech** [comment]
Too lazy to install things to use gulp, maybe tomorrow.
But maybe we need the help of @agriffard if he has time.

That said, i saw this on the bootstrap repo where they say

> We've dropped .input-group-addon and .input-group-btn for two new classes, .input-group-prepend and .input-group-append

And the toggle button use the `input-group-addon` class.
