### ISSUE TITLE
LoginSettings not found in Assembly Orchard.Users

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/OrchardCore#14095]
### Describe the bug
I have a deployment step "Login Settings", and after updating Orchard from 1.6.0 to 1.7.0, I'm getting this exception when trying to load the list od Deployment plans:

```
Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'OrchardCore.Settings.Deployment.SiteSettingsPropertyDeploymentStep`1[[OrchardCore.Users.Models.LoginSettings, OrchardCore.Users]], OrchardCore.Settings.Core'. Path 'DeploymentSteps[6].$type', line 1, position 1332.
 ---&gt; Newtonsoft.Json.JsonSerializationException: Could not find type 'OrchardCore.Settings.Deployment.SiteSettingsPropertyDeploymentStep`1[[OrchardCore.Users.Models.LoginSettings, OrchardCore.Users]]' in assembly 'OrchardCore.Settings.Core, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null'.
 ---&gt; Newtonsoft.Json.JsonSerializationException: Could not find type 'OrchardCore.Users.Models.LoginSettings' in assembly 'OrchardCore.Users, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null'.
```

How can I resolve this issue?

**Comment by hishamco** [comment]
`LoginSettings` is now located in `OrchardCore.Users.Core`, it seems that PR #13704 breaks the old migration

/cc @MikeAlhayek

**Comment by MikeAlhayek** [comment]
the `LoginSettings` is needed by the `UserService` which also found in the core project.

https://github.com/OrchardCMS/OrchardCore/blob/83ada8fbb11e208caab7d3111b33deb056009d1a/src/OrchardCore/OrchardCore.Users.Core/Services/UserService.cs#L50

I am not familiar with deployment play so not sure how we would go about fixing this.

**Comment by hishamco** [comment]
I will try to reproduce the issue

**Comment by sebastienros** [comment]
There should be a migration that converts Deployment Plans to use the new schema. Iterating each node to look for this step and convert it to the new format.

**Comment by MikeAlhayek** [comment]
@SzymonSel if you can provide recipe that I can use to re-produce the problem, I can fix it. But, if you want to fix it, please submit a PR for this. This is the only issue now that is blocking the release of 1.7.

**Comment by SzymonSel** [comment]
I haven't exported the deployment plan with LoginSettings. I've worked my way around by downgrading the OC version, removing the step, bringing the OC version back up again and adding the step.

If it helps, I can try recreating the bug.

**Comment by jtkech** [comment]
The `Type` column of the `Document` table not only includes the namespace but also the assembly name, so, if the model definition has been moved, we need a migration.

From memory @Skrypt did such a migration when we renamed the `Search.Lucene`  module.

**Comment by sebastienros** [comment]
This is what needs to be done, but for a single type so much simpler

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Search.Lucene/Migrations.cs#L150C3-L209

**Comment by MikeAlhayek** [comment]
@SzymonSel a fix was put in place for this. Are you able to test the latest release before Thursday just to confirm this is no longer an issue for you? If you confirm before Thursday, we may be able to release 1.7 then. If you want to test it out soon on your end, wait like 1 hour just to allow the preview packages to generate.

Thank you

**Comment by SzymonSel** [comment]
LGTM
