### ISSUE TITLE
Auto warmup tenants with enabled background tasks

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14094]
### Is your feature request related to a problem? Please describe.
Typically tenant site is created on the very first HTTP request to the site. However, this logic would cause an issue to a low traffic site that depends on times Background tasks.

For example, let's say we have a background task that runs every minute on a site with very low traffic. When the application pool gets restarted and the tenant instance for that site is no longer available, all the background tasks will no longer run since the tenant application does not work.

### Describe the solution you'd like
It may not be a bad idea to auto warm up tenants that have at least one background task running. Maybe we can store a new property `AutoStartup` in the `appsettings.json` file for the tenant which will auto load the site when value is set to `true`.

### Describe alternatives you've considered
Add some sort of a health check process that pings the site very X amount of time (which issues an HTTP request to the site).

**Comment by hishamco** [comment]
I think Orchard CMS already has a sort of warmup, but frankly I don't have any idea what it was for

**Comment by MikeAlhayek** [comment]
Yes it came to my attention that there is a settings called `OrchardCore_BackgroundService.ShellWarmup` which warms up the tenant.

**Comment by MikeAlhayek** [comment]
Here are the scenarios that make sense to me

 1. Any tenant that has at least 1 enabled background task, we should auto warmup even if Warmup option is false.
 2. Any tenant that is warmed up (manually without the first Http request), we **should** build the pipeline. Regardless how we start the background tasks, the pipeline should be built. 

I don't think the Warmup option in the settings is needed. That decision should should be based on if there are enabled background tasks or not. Background tasks are useless if the site isn't built and ready.

**Comment by sebastienros** [comment]
Maybe we need 3 options:
- Always warmup (don't wait for the first request)
- Never warmup (waits for a request to start background tasks) (current default)
- Warmup if there is at least one background task enabled

**Comment by jtkech** [comment]
About shell warmup we have to consider.

- Build the shell container: There is already an option.

- Build the shell pipeline: It needs to be run in the background but only to be able to generate routed urls, as done in #14105 in a light way but for now only if it is already built. So do we want to also build the shell pipeline?

    If so I think we need a separate option, building a shell pipeline takes more time and resources, so would be useful if we have background tasks but that don't need to generate routed urls.

- Run the shell pipeline in the background itself: As said, to be able to generate routed urls, as done in #14105 and by using a light middleware to shortcut the pipeline and then to make it lighter and faster. So no problem as soon as the shell pipeline is built.

- Auto warmup if a background task is defined: But at least for now, to know that a background task is defined, we need an already built shell container ;)

Note: The shell configuration is also lazily built.

**Comment by Piedone** [comment]
The default should be never warmup, as today IMO. The point of lazily starting tenants is that they don't consume any resources unless they're used, including background tasks.

**Comment by sebastienros** [comment]
> The default should be never warmup

Agreed
