### ISSUE TITLE
Configuring instance of `IShapeTableProvider` does not to the IoC container correctly without `[Feature()]` attribute

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14103]
### Describe the bug

I have the following startup class

```
[Feature("CrestApps.Components.User.Avatars")]
public class AvatarStartup : StartupBase
{
    public override void ConfigureServices(IServiceCollection services)
    {
       //....
        services.AddScoped<IShapeTableProvider, AvatarShapeTableProvider>();
    }
}
```

If I enable the `CrestApps.Components.User.Avatars` feature, the `AvatarShapeTableProvider` is registered correctly. If I disable the feature after that, the ShellContext is released. However, the `AvatarShapeTableProvider` does not get removed from the IoC even when the `AvatarStartup` does not get called again. It's like it gets cached or registered in a global `IoC` container instead of the tenant's container which is very strange.

To solve the problem, I had to explicitly add the `[Feature("CrestApps.Components.User.Avatars")]` to the `AvatarShapeTableProvider` class. 

It is my understanding that `[Feature("...")]` attribute is required on the controller only.

@jtkech have you seen this issue before? It is very strange to have to add `[Feature("...")]` for every implementation of `IShapeTableProvider`. Using `ConfigureServices()` should be all that we have to do.

**Comment by jtkech** [comment]
Yes, shape descriptors are cached among all tenants, then the shape table including descriptors and binding strategies is cached per tenant theme, so the strategy injection is only needed when first building the shape table, but somewhere they are tied to features so that if a feature is disabled the related strategy is not concretely executed (if this strategy is tied to this feature).

**Comment by MikeAlhayek** [comment]
Very strange to cache descriptors across all tenants like this. Is there a good reason to do that instead of caching it per tenant... we'll beside the extra memory/cache storage?

**Comment by jtkech** [comment]
Across all tenants not in the memory cache, for perf so that a shape descriptor is built once even if it is no longer used. In the memory cache of a given tenant we only set the shape table with descriptors and strategies related to a given tenant (and their related features) and per theme.

**Comment by jtkech** [comment]
Also sharing descriptors decrease a lot memory allocations.
