### ISSUE TITLE
Translate error when applying 'zh-CN (Chinese (Simplified, China))' culture in Localization

### ISSUE THREAD

**Issue by yqzhen1990** [OrchardCMS/OrchardCore#14110]
### To Reproduce
1. Go to 'Configuration->Settings->Localization->Cultures'
2. Select "zh-CN (Chinese (Simplified, China))" 
3. Click on 'Save'
4. The Menu "Configuration" does not translate to Chinese

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/14266657/6f06099c-004b-468d-9de9-434c8d263a30)

**Comment by hishamco** [comment]
Check if there's already a translation in https://crowdin.com/project/orchard-core/zh-CN

**Comment by sebastienros** [comment]
First explanation: We are not calling the ILocalizer on `"Configuration"` but we checked and it's done correctly
Second explanation: The `"Configuiration"` string is not translated in the Chinese files. (my guess)

**Comment by hishamco** [comment]
@hyzx86 could you please confirm if this still exists

**Comment by hyzx86** [comment]
The translation looks quite correct from the latest version

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/ac5f9f7d-f209-42f1-b54c-ca0e358a1371)

**Comment by hishamco** [comment]
Thanks a lot Tony
