### ISSUE TITLE
SqLite database schema is locked

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#1414]
- After a fresh setup, if you enable `Lucene` then `Lucene Worker`, it works

- If you enable first `Lucene Worker`, it works with `sql express`.

- But with `Sqlite` i get the following error (see below).

Then, if in `BackgroundTaskService` i deffer a little the bgTask timer, it works even with sqlite.

     timer.Change(TimeSpan.FromSeconds(10), period);

I think it's no good to start immediately bgTasks when a tenant get running. E.g, even if groups have different periods, they all start at the same time. So, even more, i think we could do that.

     timer.Change(period, period);

Let me know, i will integrate this in #1372.
**Update**: Finally, in #1372 i just added a deffered time of 1s.

![sqlite](https://user-images.githubusercontent.com/8586360/35419067-3e99515a-0236-11e8-844f-d6a007e49049.png)

**Comment by sfmskywalker** [comment]
I’ve seen something similar with TimerBackgroundTask in the Workflows branch. I wonder if your suggestion will fix the issue there as well.

**Comment by jtkech** [comment]
Normally, fixed by #1471
