### ISSUE TITLE
Validate Media base path

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#14145]
When under a virtual folder and we use the `ShellWarmup` option, if the shell container is built in the background, the media file store is not correctly registered, this because it uses the pathBase.

The problem is that it is a singleton, so the registered service resolution using the pathBase only happens once, not on each scope. Maybe too late and too complex to make it a scoped service but I saw that this pathBase is only used in one method that seems to be only used in a scope context.

So, as we do for our `IDocumentManager`s that are registered as singletons but where methods are executed in a scope context that we retrieve, the solution is to validate once this pathBase on a first real http request.

**Comment by sebastienros** [comment]
Then the pathBase should be an option that the background task can read, like it can read the base url. Same issue, same solution. Otherwise we would need to do that everywhere pathBase is required, the same way we would do for the base url (and we don't).

**Comment by jtkech** [comment]
This is what we already do but the base url may not be set correctly.

The media file store is the only place where the pathBase it retrieved once while resolving the service.

Other services take into account the pathBase dynamically on a given http request.

Here we validate it once to not change the startup and the class ctor (we could have injected an IHttpContextAccessor).
