### ISSUE TITLE
Unable to search multiple PDF file in Elasticsearch

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14153]
We support searching PDF file in Elasticsearch. We do this by reading the text of the PDF file found in MediaField and saving the text from the PDF file into an custom index in Elasticsearch. This is great because now anytime a user searches for a text found in the PDF file, we return the contentItems where the PDF belongs in!

The problem is that we only store the text of the first attached PDF file not all of them which sucks.

### Solution
When trying to index a Text/String based field, we should concatenate all values for the same index key. This will allow the content of multiple files to be indexed as expected.

**Comment by sebastienros** [comment]
> concatenate all values for the same index key

Wouldn't adding all the values to the same index key work?
