### ISSUE TITLE
Media links broken

### ISSUE THREAD

**Issue by jhdrn** [OrchardCMS/OrchardCore#1415]
I created a tenant site with a site prefix "test" and noticed that all media links were broken (both in the frontend and the admin area). It does seem to work when the query string i removed though.

Example URL: http://localhost:5000/test/media/image-35.jpeg?width=240&height=240

Stack trace:

ArgumentOutOfRangeException: The specified URL is not inside the URL scope of the file store.
 Parameter name: publicUrl
OrchardCore.Media.Services.MediaFileStore.MapPublicUrlToPath(string publicUrl) in MediaFileStore.cs
-
        public string MapPublicUrlToPath(string publicUrl)
        {
            if (!publicUrl.StartsWith(_publicUrlBase, StringComparison.OrdinalIgnoreCase))
                throw new ArgumentOutOfRangeException(nameof(publicUrl), "The specified URL is not inside the URL scope of the file store.");
            return publicUrl.Substring(_publicUrlBase.Length);
        }
    }
}
OrchardCore.Media.Processing.MediaFileSystemResolver+<ResolveImageAsync>d__12.MoveNext() in MediaFileSystemResolver.cs
-
        /// <inheritdoc/>
        public async Task<byte[]> ResolveImageAsync(HttpContext context, ILogger logger)
        {
            // Path has already been correctly parsed before here.
            var filePath = _mediaStore.MapPublicUrlToPath(context.Request.Path.Value);
            var file = await _mediaStore.GetFileInfoAsync(filePath);
            // Check to see if the file exists.
            if (file == null)
            {
                return null;

When debugging I noticed that the publicUrl argument was "/media/image-35.jpeg" and _publicUrlBase was "/test/media" which explains why the exception is thrown. I noticed that Request.Path is changed in ModularTenantRouterMiddleware which leads me to believe that _publicUrl shouln't contain the site prefix?

**Comment by sebastienros** [comment]
Before trying to fix this issue we need to understand which change in the git history introduced it.

**Comment by jhdrn** [comment]
`MapPublicUrlToPath` was added in https://github.com/OrchardCMS/OrchardCore/pull/1186.

**Comment by sebastienros** [comment]
Do you want to test the branch where I submitted the fix?

**Comment by jhdrn** [comment]
Yes, I tested it. Now it works!
