### ISSUE TITLE
Add event for Creating new tenant

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14170]
I need a way to setup integrations with external apps when a new tenant is setup and ready.

Today we have `ISetupEventHandler` which allows us to perform action while creating the tenant and report errors any. We also have `IModularTenantEvents` which allows us to hook into the process of activating or building the site before it can be used.

But, I do not see a way to hook into the process of creating the site.

### New `ITenantEvent`
I think we should have a new interface `ITenantEvent` which allows us to hook into the process. The interface will look something like this

```C#
public interface ITenantEvent
{
    Task CreatingAsync(ShellCreatingContext content);
    Task CreatedAsync(ShellCreatingContext content);

    Task RemovingAsync(ShellRemovingContext context);
    Task RemovedAsync(ShellRemovingContext context);
}
```

Note the `Task RemovingAsync(ShellRemovingContext context)` exists in `IModularTenantEvents`. I think it should be removed from `IModularTenantEvents` and added into the new `ITenantEvent` as it seems to be a better fit there since these event only happen once during the lifetime of the tenant.

### Improve `ISetupEventHandler`
 I think this interface is missing `ShellSettings` instance. Maybe it should be enhanced to change the signature from 

```
Task Setup(IDictionary<string, object> properties, Action<string, string> reportError)
```
to

```
Task Setup(SetupContext context)
```

Note that `SetupContext` add more value and has ShellSettings and other useful info.

@jtkech I know you did lots of these interfaces. Is there an event that I missed that help us hook into created tenant? If not, can you share some thoughts about the presented change here?

**Comment by jtkech** [comment]
Would need to better know what your integrations do, if tenant services are needed or not.

In a `ModularTenantEvents` you can check current states including `ShellSettings`, persisted states from database or from caches, and so on, for example this is how we run some migrations once.

Hmm, not sure about having new `Creating` and `Created` events knowing that we can create tenants with only partial settings and not ready to be used at all.

So it looks like an `ISetupEventHandler` is more what you need.

In a `ISetupEventHandler` you can inject `ShellSettings` or any other services.

What you could also have is a `ISetupEventHandler` just to trigger a `BackgroundJob` (executed after the end of the setup request, so once), in which you could check the tenant state and so on.

**Comment by MikeAlhayek** [comment]
@jtkech for example, for every tenant I create in OC, I also want to also create an application in Sendbird using an API call. I don't want to create this tenant in Sendbird unless the tenant was successfully setup. Calling `ISetupEventHandler.Setup` here does not guarantee that the tenant was successfully setup.


> In a ModularTenantEvents you can check current states including ShellSettings, persisted states from database or from caches, and so on, for example this is how we run some migrations once.

How can you be sure that the tenant was just created here using `ModularTenantEvents`? If there is a way for me to know that this is the first time we are setting up the tenant, then sure this would work.

**Comment by jtkech** [comment]
> How can you be sure that the tenant was just created

By persisting some state on first execution and that you could check afterwards.

But as said I would use the following

> What you could also have is an `ISetupEventHandler` just to trigger a `BackgroundJob` (executed after the end of the setup request, so once), in which you could check the tenant state and so on.

    await HttpBackgroundJob.ExecuteAfterEndOfRequestAsync("integrations", async (scope) =>
    {
        // Your stuff.
    });

**Comment by MikeAlhayek** [comment]
> By persisting some state on first execution and that you could check afterwards.

you mean adding a feature or an Item in the `HttpContext` just before I call `HttpBackgroundJob.ExecuteAfterEndOfRequestAsync`? Will that all happen on the same HttpContext?

**Comment by jtkech** [comment]
> you mean adding a feature or an Item in the HttpContext

No, for example some settings in the shared database, but this only if you are using a `ModularTenantEvents`.

Not needed if you use a `ISetupEventHandler` that triggers a background job.

> Will that all happen on the same HttpContext?

No, because the fired and forgotten background job will wait that the current httpContext completes, then the job will be executed only if the tenant is running (a new shell is built because of the setup, and is running if the setup was okay), then it will provide a shellScope to retrieve anything you may need.
