### ISSUE TITLE
Hints in Background Edit settings

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#14183]
https://github.com/OrchardCMS/OrchardCore/blob/7d50c3efe37f22545dc0b47ed2572ac5086963c3/src/OrchardCore.Modules/OrchardCore.BackgroundTasks/Views/BackgroundTask/Edit.cshtml#L53
`Wether `=> `Whether`
May be rephrase (put the `or not` at the end)?

https://github.com/OrchardCMS/OrchardCore/blob/7d50c3efe37f22545dc0b47ed2572ac5086963c3/src/OrchardCore.Modules/OrchardCore.BackgroundTasks/Views/BackgroundTask/Edit.cshtml#L54
`This to configure endpoints and then to allow route urls generation` => `Check this ...` ?

Do we need two hints, one below the other?

@jtkech I let you fix it. 

Other English speakers can suggest changes to make the hint more understandable.

**Comment by MikeAlhayek** [comment]
@agriffard check out this comment https://github.com/OrchardCMS/OrchardCore/pull/14105#discussion_r1298499471

**Comment by jtkech** [comment]
> Wether => Whether

Yes there is the same typo in 25 other places, I will fix them.

> May be rephrase (put the or not at the end)?

I think that's okay if the description of the alternative is long.

> Do we need two hints, one below the other?

They are rendered inline, not one below the other, just to not have a too long line in the code.

> This to configure endpoints and then to allow route urls generation => Check this ... ?

Here `this` is related to `building and execute the pipeline`, I will rephrase it.

**Comment by agriffard** [comment]
Thank you @jtkech.

Other `Wether` are in comments so less problematic but good job noticing it.
