### ISSUE TITLE
script tag mime type is changed

### ISSUE THREAD

**Issue by ldimitrijevic** [OrchardCMS/OrchardCore#14196]
Hello,

I have a strange behavior with script tags.
I am writing a Matomo Tag Manager module. This module outputs JavaScript in a filter. To be compliant with UE laws about cookies, i need that this javascript is not run unless the user accept the cookies that comes from Matomo. The solution is to mark the script tag  with a text/plain type so that it does not run. My cookie consent script needs also this MIME type to be set to work.
The problem is that when the page is rendered the script tag has his MIME type changed to text/javascript.
The same happens when i set a script tag manually in the layout page.

I have tested a VS out of the box ASP.Net WebSite added a text/plain script tag in the header and it woks as expected.

Does anyone has an idea about the issue? A solution?

Thanks for your replies

**Comment by sebastienros** [comment]
Can you provide an example of what you are doing? Just rendering a simple script and what you are seeing. Thanks

**Comment by ldimitrijevic** [comment]
I will close this one. Strange but it works today. I did nothing more than pushing a string to the output. The only thing i've changed so far was creating a middleware rather than using a filter. I don't know if that was the issue.
