### ISSUE TITLE
Constants should be pascal cased

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#14198]
I believe this block should be removed:

```
# Define the 'private_const_fields_ignore_camel_case_leading_underscore' naming rule.
dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.severity = none
dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.symbols = private_const_fields
dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.style = camel_case_leading_underscore
```

c.f. https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names
And check aspnetcore and runtime soruce code.

**Comment by jtkech** [comment]
At some point we defined a group for `private fields` and a rule on this group to use `camel case` with a `leading slash` for private fields.

    # Define the 'private_fields' symbol group.
    dotnet_naming_symbols.private_fields.applicable_kinds = field
    dotnet_naming_symbols.private_fields.applicable_accessibilities = private

    # Define the 'private_fields_should_be_camel_case_leading_underscore' naming rule.
    dotnet_naming_rule.private_fields_should_be_camel_case_leading_underscore.severity = suggestion
    dotnet_naming_rule.private_fields_should_be_camel_case_leading_underscore.symbols = private_fields
    dotnet_naming_rule.private_fields_should_be_camel_case_leading_underscore.style = camel_case_leading_underscore

I added a group for `private const fields` just before the rule (that you mentioned) on this new group, this to remove the `camel case` constraint for `private const`, which allows to use `pascal case` but without forcing it.

    # Define the 'private_const_fields' symbol group.
    dotnet_naming_symbols.private_const_fields.applicable_kinds = field
    dotnet_naming_symbols.private_const_fields.applicable_accessibilities = private
    dotnet_naming_symbols.private_const_fields.required_modifiers = const

    # Define the 'private_const_fields_ignore_camel_case_leading_underscore' naming rule.
    dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.severity = none
    dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.symbols = 
    private_const_fields
    dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.style = camel_case_leading_underscore

So currently we already can use `pascal case` for `private const`. If we want to force it we should define a new rule accordingly. But only removing the mentioned rule will force again to use a `underscore + camel case` for `private const`.

**Comment by jtkech** [comment]
Yes these discussions are good to define step by step and when we want:

1. Rules that we want to remove.
2. Recommendations without adding rules => Nothing to do or cleaning files gradually.
3. Rules that we want to add (suggestions, errors or warnings).

So, here:

- Nothing to do for `1.`, yes the mentioned rule is for `private_const` but with `.severity = none` precisely to remove the `camelCase` rule for private const that was added for all private fields.

    So currently we already can use `PascalCase` for private const, when I worked on rules the goal was to remove as much as possible the violations, I didn't add any new rule, only removed this one.

- So nothing to do for `2.` if we only want to recommend `PascalCase` for private const.

    Before removing the `PascalCase` for private const some files may have been updated in the meantime, so maybe only update these files to follow again the recommendation.

- So nothing to do if we only want `1.` and `2.`, if we really want `3.` then yes a new `PascalCase` rule for private const needs to be added and then the new violations would need to be removed.

**Comment by sebastienros** [comment]
I don't know where the discussions and PRs are at, I'll let you merge anything related as long as you are in an agreement.
