### ISSUE TITLE
Get rid of module manifest files

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#1420]
Here a separate issue coming from the closed discussion #1403.

Here the last comment of @sebastienros on this issue on my answer.

> What about dedicated classes for module and features? Then to can build
them with a 'new' keyword. Like Json.

Yes, you're right, would be easier, just thought that you wanted only attributes.
Maybe good to still have assembly attributes to mark modules as `Module / Theme`.
Maybe easier to use if we want to use this to grab modules from runtime assemblies.
Hmm, but they already reference `OC.Modules/Themes.Targets`, need to think about this.
Then, as before the module `Id` would be always equal to `AssemblyName` = `ProjectName`.
Then indeed, all other manifest properties could be provided by dedicated classes.
If not provided, the module `Name` would be equal to `AssemblyName` = `Id`.
I will open an issue to discuss on this one.

> with a 'new' keyword. Like Json.

Do you think about like `new JObject()`?
Maybe interfaces / classes which embeds a `JObject` or derives from `IEntity`.
Or more dedicated ones with well known and restricted properties.

**Comment by jtkech** [comment]
I think i will start on it this night.

Good 1st new, when building the main app, in our msbuild script we need to grab module project references. One solution would be to call a target on all project references and then only modules would return a value. But until now this was not possible because msbuild was failing on the first project which didn't define this target.

So, we had to check fo each project location if a manifest file exists. But now, when calling the same target on multiple projects, there is a new `SkipNonexistentTargets` property that we can use. So now, at least for building, we don't need anymore to check and then we don't need the presence of manifest files.

**Comment by Jetski5822** [comment]
@jtkech do you ever sleep?

**Comment by jtkech** [comment]
😉

**Comment by jtkech** [comment]
- So, the simplest way seems to use only one `Module / Theme` attribute which gives the type, and which is an assembly attribute which is easier and faster to grab.


- I begin to have things working with the 2 following examples (see below) where an attribute is defined by using a `verbatim json string` which is parsed at runtime and then used through `JObject`.

- **Before going further i think i will wait for some of my PRs to be merged (if approved)**, those which are also updating extension manager, manifest files, msbuild scripts ... This to prevent from having too much conflicts to resolve and then forgot some details.

`Manifest.cs` files examples

    using System.Reflection;

    [assembly: Module(
    @"{
        Name: 'Features',
        Author: 'The Orchard Team',
        Website: 'http://orchardproject.net',
        Version: '2.0.0',
        Category: 'Infrastructure',
        Features:
        {
            'OrchardCore.Features':
            {
                Description: 'Standard module and feature management.',
                Dependencies: 'OrchardCore.Resources',
                Category: 'Infrastructure'
            }
        }
    }")]

---

    using System.Reflection;

    [assembly: Module(
    @"{
        Name: 'Body',
        Author: 'The Orchard Team',
        Website: 'http://orchardproject.net',
        Version: '2.0.0',
        Description: 'The body module enables content items to have bodies.',
        Dependencies: 'OrchardCore.Contents, OrchardCore.ContentTypes, OrchardCore.Liquid',
        Category: 'Content Management'
    }")]

**Comment by sfmskywalker** [comment]
Or what about individual assembly attributes, like:

```csharp
[assembly: ModuleName("Body")]
[assembly: ModuleAuthor("The Orchard Team")]
[assembly: ModuleWebsite("http://orchardproject.net")]
[assembly: ModuleVersion("2.0.0")]
[assembly: ModuleDescription("The body module enables content items to have bodies.")]
[assembly: ModuleDependencies("OrchardCore.Contents, OrchardCore.ContentTypes, OrchardCore.Liquid")]
[assembly: ModuleCategory("Content Management")]
```
In any case, if we go with the verbatim JSON string, I suggest that the Dependencies field be an array, e.g.

```csharp
[assembly: Module(
@"{
    Name: 'Body',
    Author: 'The Orchard Team',
    Website: 'http://orchardproject.net',
    Version: '2.0.0',
    Description: 'The body module enables content items to have bodies.',
    Dependencies: ['OrchardCore.Contents', 'OrchardCore.ContentTypes', 'OrchardCore.Liquid'],
    Category: 'Content Management'
}")]
```

**Comment by jtkech** [comment]
> Or what about individual assembly attributes

Yes you're right, i started with this but right now i am not aware of properties, i just provide them when requested by names, this through a json object created from only one json string. I did this because  i kept the feature provider which requests these properties by names and then parses them as before.

Also, the feature provider is great because it uses feature builder events, so, e.g for a theme, specific properties are requested as `BaseTheme` and we can't know by advance all possible specific attributes.

But i agree we could have individual attributes for well known properties and maybe a json string for specific data. That said, how to define a collection of features, i thought about multiple `Feature` attributes but we would need e.g a `FeatureDescription` and pass the feature name to which it is tied ...

So, if we don't keep the json string, because if a module doesn't define features it is itself a feature, i'm also thinking to only have a `Feature` attribute which we can use multiple times, and use named params.

    [assembly: Feature(
        Name: "Body",
        Author: "The Orchard Team",
        Website: "http://orchardproject.net",
        Version: "2.0.0",
        Description: "The body module enables content items to have bodies.",
        Dependencies: "OrchardCore.Contents, OrchardCore.ContentTypes, OrchardCore.Liquid",
        Category: "Content Management",
    )]

And because an attribute can be derived, we could have e.g a `ThemeFeature` with additional named params, e.g `BaseTheme`. Then, a feature builder event could cast to the desired type.

> In any case, if we go with the verbatim JSON string, I suggest that the Dependencies field be an array

You're right, i just need to update the current feature provider which is not waiting for an array.

**Comment by sfmskywalker** [comment]
I really like that Feature attribute you posted above. If we would keep a Module attribute, it should follow that design, and not the individual Module* attributes I initially suggested. But maybe you're right and we only need a Feature (and descendants such as ThemeFeature). 

Looks pretty slick to me!

**Comment by jtkech** [comment]
@sfmskywalker thanks.

So, i have a testing version that fully works with this kind of manifest definitions.

**A theme**

    using OrchardCore.DisplayManagement.Manifest;

    [assembly: Theme(
        name: "The Agency Theme",
        author: "The Orchard Team",
        website: "http://orchardproject.net",
        version: "2.0.0",
        description: "A theme adapted for agency websites."
    )]

**A module that defines only one feature by itself**

    using OrchardCore.Modules.Manifest;

    [assembly: Module(
        name: "Body",
        author: "The Orchard Team",
        website: "http://orchardproject.net",
        version: "2.0.0",
        description: "The body module enables content items to have bodies.",
        dependencies: "OrchardCore.ContentTypes, OrchardCore.Liquid",
        category: "Content Management"
    )]

**A module that defines features**

    [assembly: Module(
        name: "Features",
        author: "The Orchard Team",
        website: "http://orchardproject.net",
        version: "2.0.0"
    )]

    [assembly: Feature(
        id: "OrchardCore.Features",
        description: "The Features module enables the administrator of the site to manage ...",
        dependencies: "OrchardCore.Resources",
        category: "Infrastructure"
    )]

    [assembly: Feature(
        id: "OrchardCore.Features.OtherFeature",
        description: "Other description",
        dependencies: "OrchardCore.Resources",
        category: "Infrastructure"
    )]


**Notice that a `Manifest.cs` file is not required**, these attributes can be defined in any file.

**Comment by sfmskywalker** [comment]
Awesome. @sebastienros  what do you think?

**Comment by sebastienros** [comment]
Exactly what I imagined. Please use PascalCase.

**Comment by jtkech** [comment]
@sfmskywalker @sebastienros thanks.

For `PascalCase` it is just to not have names conflicts with the properties of the attribute class.

But not a big problem, indeed `PascalCase` is better, i will change it.

**Comment by sfmskywalker** [comment]
But these are constructor arguments. Is it conventional to declare them using `PascalCase`?

**Comment by jtkech** [comment]
Yes, there are constructor arguments and the convention is `camelCase`. And i have properties of the same names but already defined with `PascalCase`.

Here i can't use a new operator like this.

    [assembly: new Module {
        Name: "Features",
        Author: "The Orchard Team",
        Website: "http://orchardproject.net",
        Version: "2.0.0"
    }]

So, to have the following with `PascalCase`, i would need to define the inner class properties in `camelCase` or with different names, e.g `ModuleName`.

    [assembly: Module(
        Name: "Features",
        Author: "The Orchard Team",
        Website: "http://orchardproject.net",
        Version: "2.0.0"
    )]

**Comment by Jetski5822** [comment]
Sweet, does this get automatically inserted when you reference the target?

**Comment by jtkech** [comment]
Just before leaving.

@Jetski5822 yes but during `msbuild` building, then the main app assembly embeds the list of modules. Could be done at runtime but still quite long to lookup for a type or an attribute in all referenced assemblies, you remember in all references of the references ;) But it is doable.

@sebastienros @sfmskywalker named parameters with `PascalCase` done.

I already have a full version which works with this, need more checking, i also have other updates in some PRs that i need to take into account, need also to think about things i can remove or better to keep.

Quite cool to edit manifest file with colors and intellisense. Can be edited in any csharp file.

![manifest](https://user-images.githubusercontent.com/8586360/36059630-45aae528-0e3c-11e8-9bad-1df32d84847d.png)

**Comment by sfmskywalker** [comment]
This looks awesome.

**Comment by jtkech** [comment]
@sebastienros @sfmskywalker 
@Jetski5822 you let me think of the following

I also tried to get rid of the `modules.names.map` file (updated on building) by using the `DependencyContext` that we already use in `ShellFeatureApplicationPart`. This to grab all modules names at runtime.

With the following, which doesn't load assemblies, i could grab all modules names. We could filter with well known names starting with `System`, `runtime`, `Microsoft` but this doesn't seem to make it faster.

So, the following adds about 50 ms, do you think it is worth to do that?

Note: Right now for testing i use hard coded strings, particularly for theme targets, and i needed to exclude the theme targets because it references the module targets.

            var test1 = DependencyContext.Default.RuntimeLibraries
                .Where(lib =>
                    lib.Name != "OrchardCore.Theme.Targets" &&
                    lib.Dependencies.Any(dep =>
                        dep.Name == "OrchardCore.Module.Targets" ||
                        dep.Name == "OrchardCore.Theme.Targets"))
                .Select(lib => lib.Name).ToList();

Here i got 3 modules less, this let me saw that they don't reference `OC.Module.Targets` directly but through a reference to another module, i will do a patch for this.
