### ISSUE TITLE
Set on/off for PhonNumber function or allow blank

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#14227]
The ability to add phone numbers to user information is useful, but it is not suitable for all scenarios

In some cases, it is not necessary to force the user to set the phone number.

I have upgrade OC's  package to the latest preview version, 
when I need to manually update existing users,I  need to specify a formatted phone number for them, and it is mandatory to fill in, and must conform to the correct number format.

**Comment by MikeAlhayek** [comment]
This was fix in PR #14194 which was merged 4 days ago. Please update your preview packages. Note, you don't need to confirm the phone number unless you are using the SMS Two-Factor authentication feature.
