### ISSUE TITLE
Migration issue when updating a content item and an index table does not yet exist

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#14226]
### Describe the bug
This is a tricky situation where migration A updates a content item while a later migration, migration B, adds an index table. Module B depends on module A.

### To Reproduce
1. Migration A updates one or more content items with IContentManager.UpdateAsync
2. Calling IContentManager.UpdateAsync triggers one or more IContentHandler.UpdatedAsync calls
3. OrchardCore.Contents.Workflows.Handlers.UpdatedAsync calls IWorkflowManager.TriggerEventAsync
4. OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync calls IWorkflowStore.ListByActivityNameAsync
5. The ListByActivityNameAsync method causes a flush on YesSql
6. The flush triggers a statement like this (some details omitted for brevity):
```
delete from [IndexCreatedByMigrationB] where [DocumentId] = @Id_1;insert into [IndexCratedByMigrationB] (...) values (...) ;update [Document] set [Content] = @Content_12, [Version] = @Version_12 where [Id] = @Id_12;
```
7. Migration A fails because the index table from migration B hasn't been created yet.
8. The transaction is rolled back and all migrations silently don't do anything (because the exception was caught by `InvokeExtensions.InvokeAsync` and so the exception doesn't bubble up to the logging statement that reports that the migration fails).

Is there a recommended way to work around this? One thought I had was to use `ISession.Save` instead of `IContentManager.UpdateAsync`, which would avoid the workflow event handler, but more generally I think this could happen anywhere a flush is triggered before the index table by migration B is created. Do I want to wrap the code in migration A with `ShellScope.AddDeferredTask`?

**Comment by MikeAlhayek** [comment]
Typically updating content items from a migration is done using a recipe file. This works because that code is executed in a differed task. If you want to update the content items from with in a migration file using code, you should execute your update logic/code in a `ShellScope.AddDeferredTask` this way you give the priority to first create indexes then using another scope update the content items.

**Comment by rjpowers10** [comment]
If the deferred task fails is that going to cause the migration to fail? Or will the migration be marked successful before the deferred task runs?

**Comment by MikeAlhayek** [comment]
The Deferred task will be executed in a new child scope. If it fails, it should not impact the migration that is running on the main scope. You may give it a try to be sure.

@jtkech can you confirm what I said here?
