### ISSUE TITLE
how to batch update Document table

### ISSUE THREAD

**Issue by yiji** [OrchardCMS/OrchardCore#1424]
is there a method to batch update document table,sql statement？

**Comment by sebastienros** [comment]
Yes, you can do SQL statements directly using the connection exposed by a `Session`. You can also use Dapper if you prefer. SQL should be built using the `dialect` property in the session to handle different databases if necessary. There should be a sample in the Lucene module.

**Comment by yiji** [comment]
i want to batch update certain type data in "Document" table, not excute a sql query

**Comment by sebastienros** [comment]
Load all the documents in memory, do a loop to update the documents, dispose the session.

You can use paging when you load the documents.

**Comment by yiji** [comment]
I use yessql encountered problems, pull report directly from the database using sql statement can not use the **Document** table, how to set the Index table  foreign key when get data from the **Index** table ?now I save another **Index** table id as foreign key instead of **Document** Id，can't use Document table data。

**Comment by sebastienros** [comment]
I don't understand what you are trying to explain. If it's better for you just provide some code that you are using and which shows the issue, or some code using another library that would do the same thing.
