### ISSUE TITLE
PageTitleBuilder: empty value, GenerateTitle doesn't work as expected

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#14284]
### Describe the bug

ORCHARD CORE VERSION 1.6.0 

in the `PageTitleBuilder` class the function `GenerateTitle` doesn't work as expected because the property **_title**, if you have one title part, have an "empty" value (see the image). 

![PageTitleBuilder_bug](https://github.com/OrchardCMS/OrchardCore/assets/2736009/48037e99-a6d0-4183-931c-dbe29baa9288)

the "empty" type is an 'HtmlContentBuilder'. 

This check:

https://github.com/OrchardCMS/OrchardCore/blob/1fac3e7632b32ece9e22bfbaed53eac91fa32e94/src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs#L51-L54 

return true and if you have title parts set in your `PageTitleBuilder`, you can never see this values. The behavior is fixed when you call `AddSegment` function that reset the **_title** property.

The `PageTitleBuilder` code is almost the same in 1.7.0 ... but I don't know if is introduced something to avoid this issue.

### Expected behavior
The ugly solution could be replace the chek with this one: 

```
            if (_title != null && System.String.Empty != _title.GetString())
            {
                return _title;
            }
```

Where `GetString` is defined in this way: 

```
    public static class IHtmlContentExtensions
    { 
        public static string GetString(this IHtmlContent content)
        {
            using var writer = new System.IO.StringWriter();
            content.WriteTo(writer, HtmlEncoder.Default);
            return writer.ToString();
        }
    }
```

replace the `Clear` method with this one to maintain the same behavior:

```
        public void Clear()
        {
            _fixedTitle = null;
            _title = null;
            _titleParts.Clear();
        }
```

I can't understand where the "empty" value come out or the ratio behind this. This fix should not introduce a bug because there is this check:

https://github.com/OrchardCMS/OrchardCore/blob/1fac3e7632b32ece9e22bfbaed53eac91fa32e94/src/OrchardCore/OrchardCore.DisplayManagement/Title/PageTitleBuilder.cs#L62-L65 

that avoid NullReferenceException, but I don't know if this behavior is something desired.

**Comment by hishamco** [comment]
@PiemP could you please push a PR?

**Comment by jtkech** [comment]
So if `_title` is not null, even if it is "empty", it would mean that `GenerateTitle()` has already been called before adding any segment (or "empty" ones) with `AddSegment(s)()`.

So looks like you are adding title parts after `GenerateTitle()` has already been called, which would explain why calling again `GenerateTitle()` has no effect.

`GenerateTitle()` is called by `RenderTitleSegments` that we use in razor files, e.g. in the `Layout`.

And in our hard coded `PageTitleShapes` but only if you don't provide any `siteSettings.PageTitleFormat` and for now we only use this shape in Liquid files. As a side note this means that the `PageTitleFormat` setting is only used by Themes using the `PageTitle` shape.

**Comment by jtkech** [comment]
Indeed under the admin many views are calling the razor page `RenderTitleSegments()` which calls `AddSegment()` that reset the title and then calls `GenerateTitle()`.

Maybe `IPageTitleBuilder` is missing a `RenderTitleSegments()` method, but yes for now by code you need to call `AddSegment()` meaning that the page title has changed, and then `GenerateTitle()`.

What do you want to do with the `Title` property of your `breadcrumbsShape`? Is it to act on the Title of the Page or just used to render something by the `breadcrumbsShape` itself?

**Comment by PiemP** [comment]
I would like to get the title of the page and print it as the last element of the breadcrumbs. Only print it. No other things. Probably I do it in a bad way. But I don't want to be stressful you every 5 minutes with my stupid questions.

I believe that I have try to get the title by call `RenderTitleSegments()` with an empty string as argument in the `AdminBreadcrumbs` shape, but it give to me an empty string: I suppose for the reason in this comment https://github.com/OrchardCMS/OrchardCore/pull/14295#issuecomment-1714269331 .

Exists 2 `RenderTitleSegments()` methods: 

- one that add segments in every cases
- one that add segments only if the string as argument is not empty

I don't have already insvestigated about what kind of `RenderTitleSegments()` is called in my situations. But seems a strange things have 2 method with the same name, arguments and different behaviors.

Thank you for your support.

**Comment by jtkech** [comment]
Okay I understand, you don't want to collaborate to the Title of the Page but only want to retrieve it.

One `RenderTitleSegments()` has an `IHtmlContent segment` parameter, the other a `string segment` for which we can easily check if it is empty.

Hmm, but if you call `GenerateTitle()` after it has been called by a `RenderTitleSegments()`, normally you can retrieve it as it is, and if at this point it is an empty `IHtmlContent` this is another problem.

**Comment by jtkech** [comment]
Okay I understand each time an `IHtmlContent` is concretely outputed (rendered) from a razor file it gets flushed, that why it becomes empty. I tried the following where we assume that the html content has not been yet rendered and that we have title part segments.

    @{
        // Here you get a non empty html content, and you don't render / flush it.
        var test = PageTitleBuilder.GenerateTitle(null);
    }
    @* Here you render something (even if no segment is added) and you flush the html content. *@
    <title>@RenderTitleSegments(Site.SiteName, "before")</title>
    @{
        // Here you get an empty html content because it has been flushed.
        var test2 = PageTitleBuilder.GenerateTitle(null);
    }

---

We don't see the flush for the title parts html content because when adding string segments we embed them in our `HtmlContentString` which doesn't flush anything on `WriteTo()`, which is not the case of an `HtmlContentBuilder`.

Note: But we can add `IHtmlContent` segments, so potentialy they can be flushed, in that case any re-generation would not work.

---

So yes the Title html content is not intended to be built / rendered too often, normally only once, unless we add a new segment meaning that it should be regenerated.

This is what happen in the admin, it is first rendered in some admin views to the `Title Zone` and then in the Layout to the `Head title` where it is regenerated because here a new segment is added.

Note: As said above, this works because for the first rendering we only have added string segments.

So maybe the title builder is not intended to be used as we want here, hmm maybe just a new dedicated method to generate a Title html content without checking the current `_title` and without updating it, and assuming that we only have added simple string segments.

I will think about it tomorrow.

**Comment by PiemP** [comment]
There no enough icon to thank you for that. I have put the PR in draft and I wait for your decision about that.

Thank you.

**Comment by jtkech** [comment]
@PiemP 

Okay this is when the html builder is moved to the view buffer that its entries are cleared.

    public void MoveTo(IHtmlContentBuilder destination)
    {
        if (destination == null)
        {
            throw new ArgumentNullException(nameof(destination));
        }

        var count = Entries.Count;
        for (var i = 0; i < count; i++)
        {
            var entry = Entries[i];

            if (entry is string entryAsString)
            {
                destination.Append(entryAsString);
            }
            else if (entry is IHtmlContentContainer entryAsContainer)
            {
                // Since we're moving, do a deep flatten.
                entryAsContainer.MoveTo(destination);
            }
            else
            {
                // Only string, IHtmlContent values can be added to the buffer.
                destination.AppendHtml((IHtmlContent)entry);
            }
        }

        Entries.Clear(); // <= Here.
    }

---

I think I found a good compromise by only updating 1 line of code in the title builder.

**Comment by jtkech** [comment]
@PiemP Here the suggestion in `PageTitleBuilder`.

        public IHtmlContent GenerateTitle(IHtmlContent separator)
        {
            if (_fixedTitle != null)
            {
                return _fixedTitle;
            }

            // Check if the title is not null and not empty.
            if (_title is HtmlContentBuilder { Count: > 0 })
            {
                return _title;
            }
            ...
            ...

**Comment by jtkech** [comment]
Then with the above you have the choice to subscribe to the `Layout` `OnDisplaying()`, or `OnDisplayed()` if you want to retrieve the full Page Title including the segment added by the Layout itself.
