### ISSUE TITLE
MapPublicUrlToPath throws ArgumentOutOfRangeException exception when accessing media files for non-default tenant

### ISSUE THREAD

**Issue by ydenega** [OrchardCMS/OrchardCore#1428]
PathBase of the Request should be taken into account.

**Comment by ydenega** [comment]
Steps to reproduce:
Create non-default Tenent using Agency recipe.
When browsing to the Site's URL, jpg files from media folder fail to load.

**Comment by ydenega** [comment]
Closed accidentally. Reopened.

**Comment by sebastienros** [comment]
I merged a fix an hour ago, have you tried it?

**Comment by ydenega** [comment]
Not yet. I have a personal emergency, hopefully will try tomorrow.

**Comment by sebastienros** [comment]
I am closing it for now as I tested it after my change. Please reopen if you can still repro.

**Comment by ydenega** [comment]
Thank you. I tested it and it works now.
