### ISSUE TITLE
Two alerts displayed in admin settings to reload the current tenant

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#14286]
The `/Admin/Settings/email` page displays 2 identical warning alerts:
`The current tenant will be reloaded when the settings are saved.`

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/9bb991d8-938f-429b-a0f3-6716c0a24db3)

**Comment by agriffard** [comment]
`/Admin/Settings/localization` too.

**Comment by ns8482e** [comment]
Maybe added twice by notifier service?

**Comment by jtkech** [comment]
The easiest way is to remove the alert from `Settings-General.Wrapper.cshtml` where it has been added, and re-add the alert in `Settings.Edit.cshtml`. So that we don't have to check where we need or not to remove the alert in all other dedicated settings shape views.

**Comment by MikeAlhayek** [comment]
@jtkech the notification is needed in the wrapper. But we should only apply the wrapper when the group is `general`. I'll submit a PR

**Comment by jtkech** [comment]
Okay so maybe the right fix is in the driver

            if (context.GroupId.Equals(GroupId, StringComparison.OrdinalIgnoreCase))
            {
                context.Shape.Metadata.Wrappers.Add("Settings_Wrapper__General");
            }

**Comment by jtkech** [comment]
Or just

            if (!context.GroupId.Equals(GroupId, StringComparison.OrdinalIgnoreCase))
            {
                return Task.FromResult<IDisplayResult>(null);
            }

**Comment by MikeAlhayek** [comment]
@jtkech yes that is what I suggested in the PR  #14315

**Comment by jtkech** [comment]
Okay then
