### ISSUE TITLE
Query in Liquid template not working

### ISSUE THREAD

**Issue by devenliu** [OrchardCMS/OrchardCore#14296]
### Describe the bug
According to the documentation for the `Query` feature, using the `Queries.RecentBlogPosts | query` syntax in `Liquid Page` is not working properly.

### To Reproduce
1. Create a new CMS Web App project version 1.7.0
2. Use Blog Recipe
3. Create a Liquid Page Content Type
4. Create a Liquid Page Content Item
5. Set body content to 
```liquid
{% assign recentBlogPosts = Queries.RecentBlogPosts | query %}
{% for item in recentBlogPosts %}
{{ item | display_text }}
{% endfor %}
```
6. Access this Liquid Page
7. There is nothing on the page

I refer to the following documents and videos:
- https://docs.orchardcore.net/en/latest/docs/reference/modules/Queries/
- https://www.youtube.com/watch?v=6ZaqWmq8Pog&t=2891s
- https://www.youtube.com/watch?v=JYES1i6BdWs

### Expected behavior
Normally display RecentBlogPosts list items on the page.

### Screenshots

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/3464dd4f-8247-4be6-9ea5-8066c6243292)

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/e5665e2f-586c-461f-a354-e6809999a1c3)

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/e815221f-0597-4723-a979-7d5d6aefe48c)

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/574f6528-b241-4eb4-ac44-3164139ddd96)

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/7728957c-1894-4acd-b65b-4ccbbb122538)

**Comment by devenliu** [comment]
There is no prompt message in the console. 
I don't know why it works normally in the video, but nothing happens here.
Any help will be greatly appreciated.

**Comment by devenliu** [comment]
When I modified the Body of Liquid Page as shown below, the console printed out the array. The number of arrays was correct, but the elements in the array did not have any attributes.

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/2f1efa81-e6d5-4de7-8756-6a0e5ccd8717)


![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/ef524811-9a5c-45c0-a088-648c90aa5a88)

**Comment by jtkech** [comment]
Just tried, the items of the `SqlQueryResults` are not `ContentItem` but are `JObject` having a `DisplayText` property among others.

![SqlQueryResult](https://github.com/OrchardCMS/OrchardCore/assets/8586360/4768a474-05c8-41b6-a572-e6785b9e79c8)

So it works if you use the following query.

    {% assign recentBlogPosts = Queries.RecentBlogPosts | query %}
    {% for item in recentBlogPosts %}
    {{ item.ItemDisplayText }}
    {% endfor %}

To make it returning `ContentItem` you need to edit the query and check `Return Documents`, in that case your query using `{{ item | display_text }}` will work.

**Comment by devenliu** [comment]
@jtkech 
This is the answer to the Issue, and it indeed resolves the problem. 
Thank you very much for your assistance. 
Much appreciated!

**Comment by jtkech** [comment]
Oops, sorry for the typo ;)
