### ISSUE TITLE
orchardcore.net SSL certificate has expired 

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#14300]
Same as https://github.com/OrchardCMS/OrchardCore/issues/13836. @agriffard @sebastienros I thought this was fixed for good.

As I mentioned then, I think we should rather use Cloudflare in front of the site. Among others, this also provides auto-updating SSL. I can set this up.

**Comment by sebastienros** [comment]
The binding in Azure Web Site was still using the Let's Encrypt Certificate, it's now configured to point to the Azure Managed one which was correctly renewed a while ago.
