### ISSUE TITLE
Add new settings to AdminSettings to visit the site on the same page

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14319]
Currently, when a user clicks on "Visit Site" on the navbar on the admin theme, a new tab opens every time. For some users, it is better to visit the site on the same page. Adding an option on `AdminSettings`  like this will be helpful. 

```c#
public bool VisitSiteOnNewTab { get; set; } = true
```

**Comment by hishamco** [comment]
I disagree for better UX it should open the site in a new tab so the current user doesn't lost the current context

**Comment by MikeAlhayek** [comment]
@hishamco yes I agree with you. but this is opinion/preference based. We should keep it to open in a new tab by default but give the admin the option to change it.

**Comment by hishamco** [comment]
Maybe a better option is to create such links as menu items that can be controlled: title, link, IsOpenInNewTab ... etc

**Comment by MikeAlhayek** [comment]
That would be a good option if the admin top navbar items were a shape like we did recently for the UserMenu. Then the user can change the behavior of that shape. But, either way making this a settings based is a fair ask and make sense to me. We'll see what others think about this

**Comment by sebastienros** [comment]
Does everything have to be a setting? What if someone doesn't like the font of the link? Or doesn't like the link? I'd rather have it customizable through theming, so a shape. Shouldn't be hard to do?

**Comment by hishamco** [comment]
As Seb said not everything should be in the admin settings

**Comment by MikeAlhayek** [comment]
@sebastienros Anyone can change a
Setting from the UI. Shapes however, need a developer that know what they are doing. But, yeah sure we can make the menu items as a shape here too.

**Comment by sebastienros** [comment]
What about changing the default target such that users can decide to open in new windows or not?
Example: Wordpress opens in place and I couldn't find an option to change the behavior.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1165805/b7ff2b68-fb0d-439a-ac86-fa94777c6299)
