### ISSUE TITLE
Can't access database in another container

### ISSUE THREAD

**Issue by devenliu** [OrchardCMS/OrchardCore#14311]
### Describe the bug
I created two container services, cms and sqlserver, using compose file, 
and configured ConnectionString for AutoSetup in the environment of the cms service. 

However, after the container is started, cms cannot access the database in another container.

So I configured the same ConnectionString from the Setup page, but still the same problem.

### To Reproduce

```plain
Server=mssql;Database=orchardcore_database;User Id=sa;Password=****;
```

The 'mssql' is another container in which sqlserver is running.

I also tried changing `Server` from the `mssql` alias to the `cms` container's local IP in the docker network, but still.

### Expected behavior
The `cms` container can access the `mssql` database container by configuring the `ConnectionString` option

**Comment by MikeAlhayek** [comment]
I don't think this has to do anything with OrchardCore. It has to do with how you created your containers. I think you should use the `depends_on` directive to ensure that the database container starts first before the CMS container. Also, you may need to ensure that both container are in the same internal network. 

You may find this link helpful https://blog.christian-schou.dk/dockerize-net-core-web-api-with-ms-sql-server/

**Comment by devenliu** [comment]
> Are you able to access the database container from host or any other non-orchard application?
> 
> This could be most likely due to mssql not running on default port or port not exposed in dockerfile or docker port not mapped to the host port while running the container

@ns8482e Thanks for your reply!

I'm sure the `mssql` container is running properly because I can connect normally through the sqlcmd cli and other clients, and a database named "orchardcore_database" has also been created.

`cms` and `mssql` are defined under the `services` section of the `compose.yml` file. I am sure that they can access each other, and I used `ping mssql` in `cms` to prove it. Their networks are interconnected.

**Comment by devenliu** [comment]
I solved this issue by adding `TrustServerCertificate = true` to the ConnectionString, but I still appreciate your help~
