### ISSUE TITLE
crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by devenliu** [OrchardCMS/OrchardCore#14312]
### Describe the bug
When I access the media library and upload a file, nothing happens and I get the error `Uncaught TypeError: crypto.randomUUID is not a function` in the console.

`orchardproject/orchardcore-cms-linux:1.7.0`

### To Reproduce
1. Enable Media feature
2. Access `Content/Media Library`

### Expected behavior
Can upload media files.

### Screenshots

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/304e624c-91f3-436b-b592-b4000633b203)

![image](https://github.com/OrchardCMS/OrchardCore/assets/32150676/5d1c22f1-e326-406a-976b-44223c35cff3)

**Comment by devenliu** [comment]
Debugging the `OrchardCore.Cms.Web` project in the solution in the source code through Visual Studio does not have this problem.

**Comment by sebastienros** [comment]
Based on this doc you can check what browser version you need https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

Which one is that? Works locally for me (Edge). We might need a polyfill if not all modern browsers support it.

**Comment by devenliu** [comment]
> Based on this doc you can check what browser version you need https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
> 
> Which one is that? Works locally for me (Edge). We might need a polyfill if not all modern browsers support it.

Edge - 116.0.1938.81 x64

**Comment by devenliu** [comment]
It seems that only container images hosted on Docker Hub have this issue.

**Comment by dministro** [comment]
I'm not sure but this can be the reason from the [crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) documentation:
![image](https://github.com/OrchardCMS/OrchardCore/assets/15349881/1ba6df50-da19-4462-b853-b2e694697b6b)

When you run the app from a docker container, the app is listening on http(80) and not https.
See in dockerfile: https://github.com/OrchardCMS/OrchardCore/blob/5c7854ccb67900b9127fd8ed983f2996fc82a07b/Dockerfile#L12

**Comment by sebastienros** [comment]
That seems very possible, good catch!

**Comment by sebastienros** [comment]
I verified it and this is it, tried in an F12 JS console for both https://glowingoldfunspell.neverssl.com/online/ and http://glowingoldfunspell.neverssl.com/online/ and got this:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1165805/0be87948-1fb7-4a85-9c02-495577ad0f3d)

![image](https://github.com/OrchardCMS/OrchardCore/assets/1165805/0a504e0e-724c-4b42-9864-c8d496bb0d9e)

**Comment by devenliu** [comment]
@sebastienros @dministro 
I think this should be the problem.
Thank you so much for your help.

**Comment by devenliu** [comment]
@dministro @sebastienros 
I think this should be the problem.
Thank you so much for your help.

**Comment by dministro** [comment]
Do we need a workaround(polyfill) for this?

@sebastienros

**Comment by sebastienros** [comment]
I think we should wrap this, we didn't say OC would not work without https.
