### ISSUE TITLE
Image thumbnails in media library and media fields on content types not being displayed in admin area

### ISSUE THREAD

**Issue by richb8** [OrchardCMS/OrchardCore#1431]
Anybody else experiencing this problem?

The src on the img element seems absolutely fine, for example: http://localhost:52705/media/book-img.png?width=240&height=240

If i open the img link in a new tab in my browser, the following exception is thrown:

`ArgumentNullException: Value cannot be null.
 Parameter name: path1
System.IO.Path.Combine(string path1, string path2)
SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache+<SetAsync>d__12.MoveNext()`

However, if i remove the query string (http://localhost:52705/media/book-img.png) the image is loaded fine.

I am currently using build: 1.0.0-beta2-4390

Also, this was working fine when i was a previous release.

**Comment by sebastienros** [comment]
Do you have a `wwwroot` folder?
Are you using the latest dev branch or myget feed?

**Comment by richb8** [comment]
That was the problem! My wwwroot folder had been mistakenly deleted!

Thank you!

**Comment by sebastienros** [comment]
I will file an issue in ImageSharp.
