### ISSUE TITLE
Db Validation is not Azure App Insights friendly

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#14314]
Since updating to 1.5 we have started seeing dependency failures in App Insights when we provision new clients with the following exception "Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Document'."  

I've traced this to the the Db validation step executing a select TOP against this table which does not yet exist.

It would be nice if OC could work without extraneous failures being logged in external telemetry systems as I suspect other systems like App Dynamics and what have you will also detect the same failure.

**Comment by Piedone** [comment]
Do you mean this is an exception during setup of a tenant, right? Because in Application Insights while that shows up in Live metrics for some reason, it's not actually logged (it shouldn't, it's caught).

**Comment by ShaneCourtrille** [comment]
@Piedone It shows up as a Dependency failure when you look at Requests or if you go look into the Failures / Dependency view

**Comment by Piedone** [comment]
Indeed, you're correct. What I remembered is that they don't cause request failures.

**Comment by sebastienros** [comment]
Is there a way to create faulty SQL queries, and mark them as expected in App Insight?

**Comment by Piedone** [comment]
These can be filtered out with a telemetry processor, see [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling?tabs=javascriptwebsdkloaderscript). I've created an issue for our AI module: https://github.com/Lombiq/Orchard-Azure-Application-Insights/issues/68 I don't think this is a bug in Orchard but rather a peculiarity of collecting telemetry with AI.

**Comment by ShaneCourtrille** [comment]
Yeah, we've tried this for the other "already an object named Identifiers in the database" but I wasn't happy with the end result.  I'll take another look to see if I can solve both at the same time.

**Comment by Piedone** [comment]
We've done it in our module here: https://github.com/Lombiq/Orchard-Azure-Application-Insights/pull/69.

**Comment by Piedone** [comment]
Better than excluding such telemetry fully is to mark it as a success, see: https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling?tabs=javascriptwebsdkloaderscript#addmodify-properties-itelemetryinitializer. So we've added a feature for doing this in general to our module: https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/dev/Lombiq.Hosting.Azure.ApplicationInsights/ApplicationInsightsOptions.cs#L82
