### ISSUE TITLE
The Workflow module page gives an error when using PostgreSQL with OC 1.7.0 version.

### ISSUE THREAD

**Issue by emrahtokalak** [OrchardCMS/OrchardCore#14334]
### Describe the bug

Error: "PostgresException: 42703: column "workflowtypeid" does not exist"

When a new Orchard Core 1.7 application using PostgreSQL is started, the Workflow page gives an error when opening. I noticed this error when upgrading my 1.6 project using PostgreSQL to 1.7. I did a clean installation via the Orchard Core repo and I encountered this error again when using PostgreSQL.

I did not encounter this problem in a different installation using Sqlite. I think it's a situation that occurs when using PostgreSQL.

### To Reproduce
1. Create new project using version 1.7 and PostgreSQL.
2. Try to open the Workflow module via the panel.

### Expected behavior
I'm waiting for the Worklow list to open properly.

### Screenshots

<img width="1332" alt="Screenshot 2023-09-14 at 22 55 01" src="https://github.com/OrchardCMS/OrchardCore/assets/90242/a5819341-a8e0-44dc-971d-6dc2e261e2df">

<img width="1981" alt="Screenshot 2023-09-14 at 22 56 28" src="https://github.com/OrchardCMS/OrchardCore/assets/90242/5b4ca03d-25a4-4aca-9cf1-cd4c6911bfea">

**Comment by sebastienros** [comment]
The fix for the issue will also require adding a functional test.

**Comment by sebastienros** [comment]
This should also be shipped as 1.7.x
