### ISSUE TITLE
Script function  .NET object‘s method call problem in Jint v3.0.0-beta-2051 

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#14346]
noticed that I was using the latest version of Jint, but I found a problem with method calls on.net objects

The following script works fine in v3.0.0-beta-2049, but 2051 shows that the method does not exist
`useDb()` will return a.net object and subsequent chain calls will all be.NET methods 

```js
var count = useDb().selectTypedQuery("UserProfile")
.where("UserName='Admin'")
.count();
return count!=0
```
So far I have rolled back the reference version of OC to 1.8.0-preview-17635

The relevant issues in Jint's repo, I guess they should be related

https://github.com/sebastienros/jint/issues/1626

**Comment by hyzx86** [comment]
@hishamco  updated in https://github.com/OrchardCMS/OrchardCore/pull/14369

**Comment by hyzx86** [comment]
@hishamco  pls reopen this issue ,   the problem still exists~ 
https://github.com/sebastienros/jint/issues/1637

and  https://github.com/sebastienros/jint/pull/1638

**Comment by sebastienros** [comment]
Waiting for a new release of Jint
