### ISSUE TITLE
Not possible to configure module's root path for Razor Pages?

### ISSUE THREAD

**Issue by mikoskinen** [OrchardCMS/OrchardCore#1434]
We're using OrchardCore Modules in a custom ASP.NET Core app. It's working nicely but from what we have gathered, there doesn't seem to be a way to set a custom root path for a module?

What I mean that if we have a module:
ProjectName.Modules.Account

And the ProjectName.Modules.Account contains ~15 Razor pages, we can access these using:

http://localhost/ProjectName.Modules.Account/MyTestPage
http://localhost/ProjectName.Modules.Account/AnotherTestPage
etc.

What we would like to have is that each Razor page inside the module is available from the following url:

http://localhost/Account/*

So for example:

http://localhost/Account/MyTestPage
http://localhost/Account/AnotherTestPage

The AddModularPageRoute -functionality seems to be only for single pages. So we could write something like the following for each page but it seems little tedious:

options.Conventions.AddModularPageRoute("/ProjectName.Modules.Account/Pages/TestPage", "Account/TestPage");

Any way to do this? Thanks in advance.

**Comment by sebastienros** [comment]
Apparently there is a way to define it in `RazorPageOptions` for an MVC app, we'll have to check if we can have multiple values for each module.

**Comment by sebastienros** [comment]
You can also define custom routes for each page. Hopefully there is a way to define a conventional route for pages, and this way this could be limited to specific areas (aka modules).

**Comment by jtkech** [comment]
As i remember we have

    /TheModule/Pages/PageName

Then, through `RazorPageOptions` we apply a default convention for all modules.

    /TheModule/PageName

And indeed, we can use some `AddModularPageRoute()` for each individual module page.


Humm, would it fit your needs if could define an helper which allow to define a convention for all pages of a given module? I think it is easy to do.

**Comment by jtkech** [comment]
For the above one, i think we just need to use the mvc `AddFolderRouteModelConvention()` in place of `AddPageRouteModelConvention()`.

**Comment by jtkech** [comment]
**Update**

`/TheModule/Pages/PageName` doesn't work, i didn't keep it because you would need to use `.Modules/TheModule/Pages/PageName`.

- So, i will add the default convention `/TheModule/Pages/PageName` (Already done, it works).

- We will still have the other default convention `/TheModule/PageName`.

- Then i will add an helper to define a folder convention, e.g `/TheModule/Pages/* => /SomeName/*`.
