### ISSUE TITLE
Some Fontawesome icon variants aren't loaded 

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/OrchardCore#14340]
### To Reproduce
1. In Media Library add any file which can't have a thumbnail
2. Missing `fa-file-o`

### Expected behavior
Render any fontawesome icon

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/9480863/37054aa2-0697-421d-a638-71b5cbcc931c)

**Comment by MikeAlhayek** [comment]
I thought I fixed this at some point. which version are you using?

**Comment by hishamco** [comment]
I fixed the issue, I will push a PR soon ..
