### ISSUE TITLE
crypto.randomUUID is not a function when uploading images

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14370]
after uploading image to the media, I get the following error in console

```
crypto.randomUUID is not a function
```

It seems that `crypto.randomUUID()` function is only available in HTTPS context not HTTP

**Comment by lampersky** [comment]
@MikeAlhayek there is already related issue https://github.com/OrchardCMS/OrchardCore/issues/14312

**Comment by ns8482e** [comment]
Should be this considered hotfix for 1.7?

**Comment by MikeAlhayek** [comment]
@ns8482e first we need to probably merge that PR. @sebastienros this only impact users who use unsecure connection HTTP. Should be release 1.7.1 to include this and other minor fixes we had?
