### ISSUE TITLE
UI of WidgetsListPart is broken when no FlowPart attached to the ContentType

### ISSUE THREAD

**Issue by yaricrolletservico** [OrchardCMS/OrchardCore#14374]
### Describe the bug

We have a ContentType with a ListPart attached to it. When we go to the editor the ui is a bit broken.

![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/cc7c3c59-2cd9-424b-bada-99bea8ae721f)

We think it's because the flows.edit.css files are not loaded without a FlowPart so when we attach a FlowPart to the ContentType it works.

![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/c03a23dc-f1f7-4d2c-9813-9e53064ad744)

We are working in OrchardCore V1.7

### To Reproduce
1. Create a ContentType with a WidgetsListPart
2. Try creating an instance of this ContentType
3. UI looks broken
4. Attach a FlowPart to the ContentType
5. UI looks good

### Expected behavior
UI should be good when only a WidgetsListPart is attached to the ContentType

### Possible fix

FlowPart.Edit.cshtml has a reference to the following styles and scripts:
![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/8fc58ba4-d4e1-4d35-9b79-dcb70e5c5ba9)

WidgetListPart.Edit.cshtml has a reference to the following styles and scripts:
![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/beee8592-b470-43ea-9d25-40eb943fd15b)

We think the problem is fixed by adding the flow.edit.css style references in the WidgetsList.Edit.cshtml view

**Comment by ns8482e** [comment]
Not sure why widget list needs to be depend on flow? Flow and widget list both parts are independent are in separate modules. Flow depends on widget module.

**Comment by sebastienros** [comment]
@ns8482e are you saying that there is no bug? That's how I read it

**Comment by craftyweb** [comment]
Hello, 

I'm not saying it's a major bug but we had the comment from one of our clients. It look like the functionalities are working just fine. It's only the UI that is not in the right place as you can see in my first screenshot. 

I agree that it's not necessary to have a dependency on Flows but it looks like some of the styling rules from the flows.edit.css file fix the UI for the WidgetsList. 

Maybe it is possible to add these styling rules to the widgetslist.edit.css file.

Maybe the bug label is a bit too much but I wasn't sure which label to use.

**Comment by ns8482e** [comment]
@sebastienros I mean to say fix needs to be done in widget list css and not to add flow css in widget part

**Comment by sebastienros** [comment]
@yaricrolletservico @craftyweb would appreciate if you could help with a PR to fix the issue in the css

**Comment by craftyweb** [comment]
@sebastienros will do!

**Comment by MikeAlhayek** [comment]
@craftyweb I do not see that being an issue in 1.8.previews. I am wondering if this is something we accidentally fixed while migration to bootstrap 5.3.2?

Here is a WidgetList on 1.8-preview or main branch
![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/465d2a96-cf56-42ef-8de2-888b7be50a6a)

**Comment by craftyweb** [comment]
@MikeAlhayek Your Form Widget has a FlowPart right? We encountered the problem only when we had a ContentType with just a WidgetsListPart. The PR above will describe what it looks like with only a WidgetsList attached to the ContentType. The fix was to copy a few lines of css code that were not bootstrap related from the flows.edit.scss file to the widgetslist.edit.scss file

**Comment by MikeAlhayek** [comment]
No. Here is an updated screenshot (1.8.0-preview)

Only WidgetList on a test content type. 
![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/dc9909bf-f85c-4626-b080-4d6cb35f5c22)

**Comment by craftyweb** [comment]
@MikeAlhayek Great! Maybe someone else fixed it already then. So my PR is not necessary I guess

**Comment by MikeAlhayek** [comment]
@craftyweb you should test it out on a fresh 1.7 installation. If this is indeed an issue in 1.7, we may need to merge it into 1.7.1 but not main.

**Comment by craftyweb** [comment]
@MikeAlhayek we've tested it on a clean 1.7 solution and there is the issue still visible. 
Do we need to submit a new Pull Request or can we modify our existing PR?

**Comment by MikeAlhayek** [comment]
I think you need to create a new PR that targets branch release/1.7 not main.

This will be a temporary patch for 1.7 and will be ignored in 1.8 since it is not an issue there

**Comment by craftyweb** [comment]
@MikeAlhayek All right! Thanks for the feedback!

**Comment by yaricrolletservico** [comment]
@MikeAlhayek just to be sure. Your WidgetsList in your clean ContentType does not contain a widget with a FlowPart attached to it? Even when there  are no widgets added to the WidgetsList but for example the Form widget option is available when pressing on the '+' button it is enough to fix the issue.

We went looking to the current status of the WidgetsList editor and stylesheets so far and in our opinion the problem would still be there. 

Just want to be sure before changing the PR

**Comment by MikeAlhayek** [comment]
@yaricrolletservico I was able to reproduce the issue. I also confirmed that your PR is valid.
