### ISSUE TITLE
Dark mode: Wysiwyg editor broken

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#14396]
Wysiwyg editor is broken after merging latest BS 5.3 branch.

### Screenshots

![image](https://github.com/OrchardCMS/OrchardCore/assets/3228637/e9e9b463-8409-4e4c-93dd-2ca2b04ddd02)

@agriffard

**Comment by MikeAlhayek** [comment]
@Skrypt did you clear out your temp file or maybe CTRL + F5 to force new assets to load? It's working for me with no issues.

**Comment by MikeAlhayek** [comment]
@Skrypt 
Here is what I am seeing using latest nuget packages on cloudsmith

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/cc45a010-5177-4690-b572-952d6600bb22)

**Comment by Skrypt** [comment]
Ok, the issue is only on my Vue 3 branch then. I will take a look.
