### ISSUE TITLE
How do you add the Menu to a (non-liquid) layout page

### ISSUE THREAD

**Issue by konstrui** [OrchardCMS/OrchardCore#1439]
How do you add the Menu to a (non-liquid) layout page?
There is no 'Menu widget' you can place inside a Layer, so I only see how it was done inside the Blog Theme in the Layout.liquid, but I wasn't quite sure how to do this in a normal Layout page with e.g. Razor?

**Comment by jtkech** [comment]
[Here an example](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheTheme/Views/Layout.cshtml#L40) of the usage of the related razor taghelper.
[And you need this](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheTheme/_ViewImports.cshtml#L9) in your view or your `_ViewImports.cshtml`.

**Comment by konstrui** [comment]
OK, got it.

Maybe you also have an idea on how to do the following:
I've created a website based on the agency theme, which is a one page design. Now I'd like to add a blog  to this website, which is a separate page.

I'd like to add the menu to this page also, but not sure where to add this. Since the Layout.cshtml is also used for the one page layout, which means that I would get probably two Main Menus.

Hope you understand what I'm trying to achieve?
Or is it not possible yet, due to the lack of e.g. a Menu Widget etc?

**Comment by sebastienros** [comment]
We need to rewrite the agency theme to support this scenario by default. Can someone link to the already open issue for this?
