### ISSUE TITLE
Minor AdminTheme issues on small screen

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#14404]
We still see the part of the page under the left menu

![Mobile 2](https://github.com/OrchardCMS/OrchardCore/assets/8586360/68dafdd0-5444-4ef4-a329-ed3fff173ca6)

No left margin

![Mobile 1](https://github.com/OrchardCMS/OrchardCore/assets/8586360/6f80977f-2c04-4dd6-bb22-de258501152d)

**Comment by hishamco** [comment]
Oops, did you clear your browser cache?

**Comment by jtkech** [comment]
Yes for sure

**Comment by MikeAlhayek** [comment]
I see the issue with the login screen but the first issue I can't reproduce it. Maybe you are not using the latest css

Here is a quick demo from on main branch.

![admin-menu](https://github.com/OrchardCMS/OrchardCore/assets/24724371/28cf614e-edf8-49e4-b9a8-e39cb245d2e4)

**Comment by MikeAlhayek** [comment]
@jtkech okay. I am able to reproduce it now. Fix is on it's way.
