### ISSUE TITLE
binderName is Async when binder.Name ends with Async

### ISSUE THREAD

**Issue by vjacquet** [OrchardCMS/OrchardCore#14405]
https://github.com/OrchardCMS/OrchardCore/blob/9a76299c6f981730e96653fd5615e35cea13325b/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultShapeFactory.cs#L39-L42

Unless I am mistaken, the intent of the code is to trim the Async suffix, yet it does the opposite, keeping only the Async

```csharp
var binderName = "TestAsync";
if (binderName.EndsWith("Async", StringComparison.Ordinal))
{
    binderName = binderName[^"Async".Length..];
    Debug.Assert(binderName != "Async", "binderName is set to Async");
}
```
Line 41 should be
```csharp
    binderName = binderName[..^"Async".Length];
```

**Comment by hishamco** [comment]
You are right, could you please send a PR
