### ISSUE TITLE
`Creating a modular ASP.NET Core application` tutorial does not work

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#14413]
### Describe the bug
I tried following the tutorial [Creating a modular ASP.NET Core application](https://docs.orchardcore.net/en/latest/docs/guides/create-modular-application-mvc/) and it does not work.
Module startup class never runs

### To Reproduce
Follow the tutorial

### Expected behavior
Tutorial describes all the steps to create a modular app skeleton

**Comment by xperiandri** [comment]
[Reproduction project.zip](https://github.com/OrchardCMS/OrchardCore/files/12778107/OrchardCoreModulesTest.zip)

**Comment by jtkech** [comment]
Your web app should reference your module.

**Comment by agriffard** [comment]
You didn't add the routing in the startup.cs of your module:

routes.MapAreaControllerRoute(
```
    name: "Home",
    areaName: "OrchardCore.Mvc.HelloWorld",
    pattern: "",
    defaults: new { controller = "Home", action = "Index" }
);
```

**Comment by xperiandri** [comment]
OK, but what if I don't want to register any routing to my module?

**Comment by xperiandri** [comment]
Ah stupid mistake, thanks!

**Comment by xperiandri** [comment]
Could you have a look at #14414, please?

**Comment by xperiandri** [comment]
Created the PR #14415 to prevent such issues that I had
