### ISSUE TITLE
sending email with invalid smtp certificate

### ISSUE THREAD

**Issue by sergeor** [OrchardCMS/OrchardCore#14442]
Mailkit supports sending email when the server's smtp certificate is invalid. Maybe this function should be integrated into OrchardCore.

`smtp.ServerCertificateValidationCallback = (mysender, certificate, chain, sslPolicyErrors) => { return true; };
smtp.CheckCertificateRevocation = false;`

**Comment by hishamco** [comment]
It's already there

https://github.com/OrchardCMS/OrchardCore/blob/d312e24c58474e63462862981000375cb77ce76d/src/OrchardCore/OrchardCore.Email.Core/Services/SmtpService.cs#L242-L269

**Comment by hishamco** [comment]
Maybe the current issue is you can't send the email when there's error

**Comment by sergeor** [comment]
Yes, but I would like to have the choice (with a check box from the mail server settings in the admin area) to be able to bypass the invalid or self-signed certificate.
The code that i read is just check if certificate is valid and if not return false and stop send.

**Comment by hishamco** [comment]
Check my related PR

**Comment by hishamco** [comment]
I reopen this will be closed automatically once the PR is merged
