### ISSUE TITLE
Migrate from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#14456]
I've noticed there isn't a public issue to track what needs to be done to move over from Json.NET to STJ. I'd like to collect all information into one issue to see if/when this move will be possible and what it will entail, so please chime in.  This is also research for https://github.com/OrchardCMS/OrchardCore.Commerce/issues/362.

# Blockers
Can we collect any dependencies outside of OC that block this move? Here is what I know of so far:
- [YesSql](https://github.com/sebastienros/yessql#yessql): https://github.com/sebastienros/yessql/issues/227

# Things to Change
- [OrchardCore.Entities.IEntity](https://github.com/OrchardCMS/OrchardCore/blob/d312e24c58474e63462862981000375cb77ce76d/src/OrchardCore/OrchardCore.Infrastructure.Abstractions/Entities/IEntity.cs#L5)
- Lots of `Newtonsoft.Json.Linq` (`JToken`, `JObject`, `JArray`) usages that can be trivially converted to their `System.Text.Json.Nodes` counterparts.
- Converters:
  - [`OrchardCore.ContentManagement.ContentItemConverter`](https://github.com/OrchardCMS/OrchardCore/blob/d312e24c58474e63462862981000375cb77ce76d/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentItemConverter.cs#L7)
  - [`OrchardCore.DisplayManagement.Notify.NotifyEntryConverter`](https://github.com/OrchardCMS/OrchardCore/blob/d312e24c58474e63462862981000375cb77ce76d/src/OrchardCore/OrchardCore.DisplayManagement/Notify/NotifyEntryConverter.cs#L11)
  - [`OrchardCore.Workflows.Abstractions.Converters.LocalizedStringConverter`](https://github.com/OrchardCMS/OrchardCore/blob/d312e24c58474e63462862981000375cb77ce76d/src/OrchardCore/OrchardCore.Workflows.Abstractions/Converters/LocalizedStringConverter.cs#L11)

**Comment by MikeAlhayek** [comment]
We have been slowly migrating to System.Text.Json in OC. Feel free to submit PRs that would convert.

**Comment by hishamco** [comment]
@MikeAlhayek I will start a PR on https://github.com/sebastienros/yessql/issues/227 then we can work here too to avoid any consequences

**Comment by DAud-IcI** [comment]
> Feel free to submit PRs that would convert.

Sure, that's my plan. I just opened this issue to check if there are any known blockers I might have missed, and to know if someone may already be working on this.

**Comment by hishamco** [comment]
@DAud-IcI do you want work on this or we might work together to make this done

**Comment by DAud-IcI** [comment]
We can work together too, whatever is fastest.

**Comment by hishamco** [comment]
I started working on the Converters

**Comment by sebastienros** [comment]
Really looking forward to it, thanks to all for working on this.

**Comment by Piedone** [comment]
This was done in https://github.com/OrchardCMS/OrchardCore/pull/14572.

**Comment by MikeAlhayek** [comment]
Also, in the 1.9 release notes we tried to document all the required steps under the breaking changes section ti help users migrate successfully.

**Comment by MikeAlhayek** [comment]
Here is the reference to the 1.9.0 release notes 
https://docs.orchardcore.net/en/latest/docs/releases/1.9.0/
