### ISSUE TITLE
Silent Media Upload Failure on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by cmedcoff** [OrchardCMS/OrchardCore#14455]
Upon attempting to upload a file, even a copy of what is already in the media library from the default install, no errors are repored in the UI or in the log file, no exceptions thrown.

### To Reproduce
Log in as admin
Navigate to Media library
Attempt to upload file
observe no new file and no error reported.

### Expected behavior
I would expect either an error is reported in both the UI and/or the log files as to the root cause of the failure.

### Screenshots
None

**Comment by MikeAlhayek** [comment]
What version on OC are you using. Also, are you using HTTP or HTTPS?

**Comment by cmedcoff** [comment]
HTTP, I'm running a "DEV" environment via ...

dotnet run --urls https://0.0.0.0:8080

Versiom info from the project file ...

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
    <Folder Include="Localization\" />
  </ItemGroup>

  
  <ItemGroup>
      <Watch Include="**\*.cs" Exclude="Recipes\**;Assets\**;node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Logging.NLog" Version="1.7.0" />
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.7.0" />
   </ItemGroup>

</Project>

**Comment by MikeAlhayek** [comment]
This issue will be fixed in 1.7.1.
https://github.com/OrchardCMS/OrchardCore/pull/14371

Meanwhile, you can use 1.8.0-previews or use HTTPS instead of HTTP.
