### ISSUE TITLE
Add a way to restart an instance of workflow

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14469]
### Is your feature request related to a problem? Please describe.
Sometimes, workflow instance fails for some reason. Or if we have a workflow that sends an email and failed. it would be helpful if we can restart the instance.

### Describe the solution you'd like
Add a button next to the "Delete" button names "Restart" when the instance failed. This will take the current workflow state and restart it.

**Comment by MikeAlhayek** [comment]
@sfmskywalker do you see any issue from allowing this? Thoughts on the PR #14470?

**Comment by Piedone** [comment]
I like this. Perhaps also have some kind of auto-retry?
