### ISSUE TITLE
Documentation on creating a module

### ISSUE THREAD

**Issue by konstrui** [OrchardCMS/OrchardCore#1447]
Is there already documentation on how creating a module?
What I need is a simple module that I can activate, so that I can call a simple action on a controller.

I'd like to run some custom code to import blogposts to Orchard.

**Comment by brogits** [comment]
Is it possible to access the ShellSetting and an instance of OrchardHost (IShellHost) in a custom module controller?

My goal is to be able to query the tenants role associated with the current User. Is this possible? Thanks.

**Comment by sebastienros** [comment]
@brogits just inject these in the controller's constructor.

**Comment by brogits** [comment]
@sebastienros thank you for the response. May I ask which package should I install from myget.org to be able to inject ShellSettings, IShellHost and IShellSettingsManager.

My solution is based on a new VS2017 dotnetcore project which references OrchardCore.Cms from myget.org (https://www.myget.org/F/orchardcore-preview/api/v3/index.json).

I find out that if i use the github source OrchardCore.Web.CMS.Web, it doesnt show my custom modules in the modules List. On the other hand the same modules will show on a new solution under Uncategories list.

**Comment by brogits** [comment]
@sebastienros injecting ShellSettings to my controller gets me this  error:

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'OrchardCore.Environment.Extensions.ExtensionExpanderOptions' from assembly 'OrchardCore.Environment.Extensions.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=OrchardCore.Environment.Extensions
  StackTrace:
   at OrchardCore.Environment.Extensions.ServiceCollectionExtensions.AddExtensionLocation(IServiceCollection services, String subPath)
   at Microsoft.Extensions.DependencyInjection.ServiceExtensions.AddOrchardCms(IServiceCollection services, IConfiguration configuration)
   at OrchardCMSApp.Startup.ConfigureServices(IServiceCollection services) 

Any Idea what package I am missing here ?

Thanks again

**Comment by brogits** [comment]
@sebastienros  thanks for the response. I have to use OrchardCore.Module.Target as package to have this working. And no the Environemnt.Shell.Abstractions isn't yet reference I have to add it manually for me to be able to inject those classes.

Anyhow, may I ask again another question. How does OrchardCore  implements web api that will be consumed by mobile devices? Is this possible to do as module? 

Thanks and more power
