### ISSUE TITLE
localization doesn't exist in content parts in Orchard Core

### ISSUE THREAD

**Issue by ImanBahrampour** [OrchardCMS/OrchardCore#14479]
After I activated the Content Localization feature in the Orchard core admin, the Localization part was not displayed in the content parts section.
Until now, I have been working on the previous decoupled CMS version(1.5) and updated to the latest version(1.7).

**Comment by hishamco** [comment]
![Screenshot 2023-10-11 174714](https://github.com/OrchardCMS/OrchardCore/assets/3237266/c8a989d4-01ba-42ad-9d5d-388f5f02d497)

It's there, you can find it when you trying to edit a content type

**Comment by ImanBahrampour** [comment]
There is no Localization content type.
https://github.com/OrchardCMS/OrchardCore/assets/32621006/47e7eaa7-4525-4945-8ac2-d0e839d84b83

**Comment by hishamco** [comment]
As I said before you will be able to attach the `LocalizationPart` from within the content type

**Comment by ImanBahrampour** [comment]
For example in the HTML Menu Item content type:

![image](https://github.com/OrchardCMS/OrchardCore/assets/32621006/f58c173a-dca7-4fa0-b074-a07f333e3eeb)

The LocalizationPart isn't there to attach

**Comment by hishamco** [comment]
![Screenshot 2023-10-13 122917](https://github.com/OrchardCMS/OrchardCore/assets/3237266/50cc32d4-d5cc-4f0d-ac16-175bca54aade)

It should be there, make sure you enable the Content Localization feature first

**Comment by ImanBahrampour** [comment]
In the first comment, I said I enabled the Content Localization feature(As demonstrated in the attached video).

**Comment by hishamco** [comment]
How's working with me ;) could you please try the latest bits

**Comment by ImanBahrampour** [comment]
If I create a new project with Orchard Core decoupled then it works!!
In these four years that I have been working with Orchard Core, this was very strange!!

**Comment by hishamco** [comment]
Without steps to reproduce and version we might not help you. That's why I told you to use the latest bits

**Comment by ImanBahrampour** [comment]
I have been working on the previous decoupled CMS version(1.5) and updated to the latest version(1.7).

**Comment by hishamco** [comment]
Can anyone else confirm if the issue exists?

/cc @agriffard @MikeAlhayek

**Comment by ImanBahrampour** [comment]
As I demonstrate in the attached video, I'm sure that the feature is enabled.
If I add a new content part and name it LocalizationPart then the Orchard Core gives an error: 
A part with the same technical name already exists.
I think this part exists but is hidden!

**Comment by MikeAlhayek** [comment]
@ImanBahrampour I hope you are running into this issue locally. If now, please try running this code "any where you want like a test temporary controller"

```
            var typeNames = new HashSet<string>(GetTypes().Select(ctd => ctd.Name));

            // User-defined parts.
            // Except for those parts with the same name as a type (implicit type's part or a mistake).
            var userContentParts = _contentDefinitionManager.ListPartDefinitions()
                .Where(cpd => !typeNames.Contains(cpd.Name))
                .Select(cpd => new EditPartViewModel(cpd))
                .ToDictionary(
                    k => k.Name,
                    v => v);

            // Code-defined parts.
            var codeDefinedParts = metadataPartsOnly
                ? Enumerable.Empty<EditPartViewModel>()
                : _contentPartTypes
                        .Where(cpd => !userContentParts.ContainsKey(cpd.Name))
                        .Select(cpi => new EditPartViewModel { Name = cpi.Name, DisplayName = cpi.Name })
                    .ToList();

            // Order by display name.
            var results = codeDefinedParts
                .Union(userContentParts.Values)
                .OrderBy(m => m.DisplayName);
```

Step through the code on your end and see what is preventing the part from showing up. This will help us understand why the part is not showing up even when it already exists.

**Comment by ImanBahrampour** [comment]
Codes have the following errors:
![image](https://github.com/OrchardCMS/OrchardCore/assets/32621006/60946188-4b63-4810-b340-0869f527c9c1)

**Comment by MikeAlhayek** [comment]
@ImanBahrampour 
inject `IEnumerable<ContentField> contentFields` in your constructor, then define `_contentFieldTypes = contentFields.Select(cf => cf.GetType());`

Also, use this `GetTypes()` method.
```
        public IEnumerable<EditTypeViewModel> GetTypes()
        {
            return _contentDefinitionManager
                .ListTypeDefinitions()
                .Select(ctd => new EditTypeViewModel(ctd))
                .OrderBy(m => m.DisplayName);
        }
```

**Comment by ImanBahrampour** [comment]
```
public class IndexModel : PageModel
    {
        private IContentDefinitionManager _contentDefinitionManager { get; set; }
        public IEnumerable<ContentField> _contentFields { get; set; }
        public IndexModel(IContentDefinitionManager contentDefinitionManager, IEnumerable<ContentField> contentFields)
        {
            _contentDefinitionManager = contentDefinitionManager;
            _contentFields = contentFields;
        }
        public void OnGet()
        {
            var _contentPartTypes = _contentFields.Select(cf => cf.GetType());
            var typeNames = new HashSet<string>(GetTypes().Select(ctd => ctd.Name));
            var userContentParts = _contentDefinitionManager.ListPartDefinitions()
                .Where(cpd => !typeNames.Contains(cpd.Name))
                .Select(cpd => new EditPartViewModel(cpd))
                .ToDictionary(
                    k => k.Name,
                    v => v);
            var codeDefinedParts = _contentPartTypes
                        .Where(cpd => !userContentParts.ContainsKey(cpd.Name))
                        .Select(cpi => new EditPartViewModel { Name = cpi.Name, DisplayName = cpi.Name })
                    .ToList();
            var results = codeDefinedParts
                .Union(userContentParts.Values)
                .OrderBy(m => m.DisplayName);
        }
        public IEnumerable<EditTypeViewModel> GetTypes()
        {
            return _contentDefinitionManager
                .ListTypeDefinitions()
                .Select(ctd => new EditTypeViewModel(ctd))
                .OrderBy(m => m.DisplayName);
        }
    }
```
The userContentParts:

![usercontent](https://github.com/OrchardCMS/OrchardCore/assets/32621006/bfeaf742-7e51-4fbb-85ff-01e57b98b5bb)

The codeDefinedParts:

![image](https://github.com/OrchardCMS/OrchardCore/assets/32621006/755e52c9-e1b5-4a83-86c5-b46e9ad8531f)

**Comment by MikeAlhayek** [comment]
@ImanBahrampour you need to do the debugging so you can find out where does it get lost. 

Does `userContentParts` have an entry with a `LocalizationPart` key? If not, check `var t = _contentDefinitionManager.ListPartDefinitions().Select(cpd => cpd.Name).ToList();` and see if `t` contains `LocalizationPart` 

My best guess is that you have a **content-type** called `LocalizationPart` which is why you do not see it. If that is the case, delete the content-type and you should see the part.

**Comment by ImanBahrampour** [comment]
The result is:

![image](https://github.com/OrchardCMS/OrchardCore/assets/32621006/ae8b6633-e1ee-40f7-803a-5e5230f18619)

There is no `LocalizationPart `!!

**Comment by MikeAlhayek** [comment]
Not sure. Export your content definition and I'll try to reproduce the issue.

**Comment by ImanBahrampour** [comment]
[ContentDefinition.json](https://github.com/OrchardCMS/OrchardCore/files/12900620/ContentDefinition.json)

**Comment by jtkech** [comment]
Can you check in your database if there is a `LocalizedContentItemIndex` table, to be sure that the `OC.ContentLocalization` migration has been executed.

**Comment by ImanBahrampour** [comment]
The database contains `LocalizedContentItemIndex  `

![image](https://github.com/OrchardCMS/OrchardCore/assets/32621006/0ffd33bb-238e-4333-900a-4316db54fcb4)

**Comment by MikeAlhayek** [comment]
@ImanBahrampour is there an index called `IDX_LocalizationPartIndex_DocumentId` on your `LocalizedContentItemIndex` table?

I am guessing there is. which tells me that the migration step worked as expected and created an entry of `LocalizationPart`. If both `LocalizedContentItemIndex` table and `IDX_LocalizationPartIndex_DocumentId` index exists, then the only story that makes sense is that you accidentally deleted the `LocalizationPart` manually from your site. 

To fix your issue meanwhile, execute the following recipe 

```
{
  "steps": [
    {
        "name": "ContentDefinition",
        "ContentParts": [
        {
          "Name": "LocalizationPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true,
              "DisplayName": "Localization",
              "Description": "Provides a way to create localized version of content."
            }
          }
        }
      ]
    }
  ]
}
```

### Why can't you manually add it through the UI?
When we add new content-part from the UI, we ensure that the content part does not exists in the user-defined parts or the code-defined parts.

However, when we list attachable part, we only list user-defined parts. When you manually remove the `LocalizationPart` from your definition, then the part is assumed to be code-defined and so you can't create it but also we don't list it.

**code-defined part:** is a part that is added to the options like this `services.AddContentPart<LocalizationPart>()` but has no content definition. 
**user-defined part:** is a part that is added to the content definitions even if it has  `services.AddContentPart<LocalizationPart>()` 

I am closing this one for now.

**Comment by ImanBahrampour** [comment]
The IDX_LocalizationPartIndex_DocumentId  index exists in the LocalizedContentItemIndex table.
After checking Git, I realized that the ContentDefinition file had not changed at all!!
After adding these lines to the ContentPartDefinitionRecords section of ContentDefinition the issue was fixed:
```
{
      "Name": "LocalizationPart",
      "Settings": {
        "ContentPartSettings": {
          "Attachable": true,
          "DisplayName": "Localization",
          "Description": "Provides a way to create a localized version of content."
        }
      },
      "ContentPartFieldDefinitionRecords": []
    }
```
Thank you all.
