### ISSUE TITLE
RTL Issues

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#14483]
After the last update in Bootstrap I noticed there were many things broken in RTL especially, did we test before merging it?

I'm not sure if CSS classes were added inline intentionally or for a purpose because all know the classes that affect the language direction is matter

/cc @agriffard @MikeAlhayek @Skrypt

**Comment by Skrypt** [comment]
They probably forgot to test RTL if it is broken. At least it is on the dev branch and will require to be fixed before releasing any new version.

**Comment by hishamco** [comment]
@MikeAlhayek could you please recheck if I missed something on my end
