### ISSUE TITLE
Add new `Navbar` shape to allow other to easily inject item into the top navigation bar

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14487]
### Is your feature request related to a problem? Please describe.
It is hard to current inject custom items into the Navbar. We also seems to have multiple shapes to act as menu items. 

Introduce a single `Navbar` shape like we did in `UserMenu` which allow us to easily inject items using driver instead of global filters.

**Comment by agriffard** [comment]
The front displays the culture picker with a dropdownmenu (the text is the current culture and the list contains the other cultures):

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/9938465e-c14d-418a-b351-16691ca251c4)

while the admin uses a select dropdownlist (with all cultures)

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/66adeee0-de7a-4365-aa29-b0ebd6132a92)

Should we also use a dropdown menu in admin?

**Comment by MikeAlhayek** [comment]
> Should we also use a dropdown menu in admin?
I agree that we should. But, maybe in a separate PR. In the PR I submitted, the idea was to introduce the Navbar and inject the shapes when the modules are enabled.

> If we can a have the razor/liquid equivalent of each shape in the docs (like we did for the AdminBranding), that would be great.
There are too many items to document. Is there a specific shape you want to document? It's like anything else in OC. Not sure if we want to document every shape

**Comment by agriffard** [comment]
I mean the Navbar shapes: `VisitSiteNavbarItem` for example.

**Comment by MikeAlhayek** [comment]
@agriffard where would you document that? release notes?

**Comment by MikeAlhayek** [comment]
@agriffard I added the docs. Please review the PR and approve it is you see no further issues.
