### ISSUE TITLE
Make it possible to save config in ShellSettings with more then one section

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore#14481]
Currently, it is not possible to save settings to the ShellSettings with a key that has more sections. E.g. saving `TestSection:TestSubSection:TestKey: "TestValue"` is not possible. Because of this in [ShellSettingsManager](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore/Shell/ShellSettingsManager.cs#L185-L187):
```csharp
var sections = settings.ShellConfiguration.GetChildren()
  .Where(s => !s.GetChildren().Any())
  .ToArray();
```

So basically when calling this example controller:

```csharp
    public async Task<IActionResult> Test()
    {
        if (!_shellHost.TryGetSettings("Default", out var shellSettings))
        {
            return NotFound();
        }

        shellSettings["SimpleKey"] = "SimpleValue";
        shellSettings["Not:So:Simple:Key"] = "NotSoSimpleValue";
        shellSettings["Default:Not:So:Simple:Key"] = "TenantSpecificNotSoSimpleValue";

        await _shellHost.UpdateShellSettingsAsync(shellSettings);

        if (!_shellHost.TryGetSettings("Default", out var shellSettingsNew))
        {
            return NotFound();
        }

        var result = $"{shellSettingsNew["SimpleKey"]}, {shellSettingsNew["Not:So:Simple:Key"]}, {shellSettingsNew["Default:Not:So:Simple:Key"]}";
        return Json(result);
    }
```

You will get this as a result:
![image](https://github.com/OrchardCMS/OrchardCore/assets/19938236/fdcc2adc-2b1f-455e-ad0a-d86379919c03)

Is there any specific reason why only keys without children are possible to save currently?

**Comment by Piedone** [comment]
More context [here](https://github.com/Lombiq/Hosting-Tenants/pull/84#discussion_r1348232079).

This necessitates going directly to `IShellConfigurationSources` [in `Lombiq.Hosting.Tenants.Management`](https://github.com/Lombiq/Hosting-Tenants/blob/e183f5a04f23f309d6010e0a9bce310792449103/Lombiq.Hosting.Tenants.Management/Controllers/ShellSettingsEditorController.cs#L119).

**Comment by jtkech** [comment]
@Piedone @wAsnk 

Okay, locally I did a very simple first draft that works, see #14490 where in `ShellSettingsManager` I used `AsEnumerable()` on the `ShellConfiguration` because it keeps for each key the full section path.

Here the test

    shellSettings["SimpleKey"] = "SimpleValue2";
    shellSettings["Not:So:Key"] = "NotSoValue2";
    shellSettings["Not:So:Simple:Key"] = "NotSoSimpleValue2";

    await shellHost.UpdateShellSettingsAsync(shellSettings);

In the main appsettings to check existing values and so on.

    "SimpleKey": "SimpleValue",
    "Not": {
      "So": {
        "Key": "NotSoValue",
        "Simple": {
          "Key": "NotSoSimpleValue"
        }
      }
    }

Here the result

    {
      "DatabaseProvider": "Sqlite",
      ...
      "SimpleKey": "SimpleValue2",
      "Not:So:Simple:Key": "NotSoSimpleValue2",
      "Not:So:Key": "NotSoValue2"
    }

For now configs are saved in a flat way, would need a json converter, but I think that's okay, this file is not intended to be edited directly, it can still be but it will be reformatted in a flat way on the next save.
