### ISSUE TITLE
Rendering child content types within a named part

### ISSUE THREAD

**Issue by richb8** [OrchardCMS/OrchardCore#1448]
Not sure if i'm missing something here...

I have a content type that represents the landing page on my website and have created an alternate named Content-LandingPage.cshtml. I'm using razor to access the various named parts and am rendering the relevant HTML and content items within those named parts like in the example below:

`
 @foreach (var service in Model.ContentItem.Content.ServicesSection.ContentItems)
                {

                    <div class="services-content col">
                        <img class="img-fluid" src="@OrchardCore.AssetUrl((string)service.Service.Image.Paths[0])" height="90" width="90" alt="@service.TitlePart.Title" />
                        <hr />
                        <h1>@service.TitlePart.Title</h1>
                        <p>@service.BodyPart.Body</p>
                        <a class="btn btn-secondary" href="@Url.Content((string)service.Service.ButtonLink.Url)">@service.Service.ButtonLink.Text</a>
                    </div>
                }
`

This is absolutely fine and works a treat but I can't seem to figure out how to render the child content items of the named part by using it's own template/alternate, for example Content-Service.cshtml.

Taking the example above, I was hoping I could just loop through the services in my Content-LandingPage.cshtml alternate and call DisplayAsync which would then render the html in Content-Service.cshtml:

`@await DisplayAsync(service)`

Sorry for the noob question, but I might be missing something here??

**Comment by jtkech** [comment]
To better understand, it's good to edit the `LandingPage` template, then start a preview and then for testing do some update. See the images below where you can see on the left the tested variables and on the right their values or their types if they are not rendered.

So, when you start from `Model.ContentItem` you have a content item.

![valuetype1](https://user-images.githubusercontent.com/8586360/35835543-8e328990-0adb-11e8-8cc6-29bb0f6dbcc8.png)


Then with `Model.ContentItem.Content` you get a json object which contains other json objects which are not shapes, so you can't render them directly with `DisplayAsync()`.

![valuetype2](https://user-images.githubusercontent.com/8586360/35835646-324409be-0adc-11e8-99a7-e32677a7556f.png)

So, with `Model.ContentItem.Content.ServicesSection.ContentItems`, each individual item is not a shape neither a `ContentItem`, so you would need to first build a `ContentItem` with something like this `jObject.ToObject<ContentItem>()`, then build a shape with `displayManager.BuildDisplayAsync()`. This before using `DisplayAsync()`. If you are in liquid, there is a `build_display` filter which do both, see the code in `BuildDisplayFilter.cs` as an example.

But, if you start from `Model` you get a `ZoneHolding` which is a shape. Then `Model.Content` here is also a shape which contains other shape items. Then here `Model.Content.Services` is a `BagPartViewModel` which is also a shape that you can render directly with `DisplayAsync()`.

![valuetype3](https://user-images.githubusercontent.com/8586360/35836006-30ad395c-0ade-11e8-8415-b4f03a193346.png)

![valuetype4](https://user-images.githubusercontent.com/8586360/35836009-36bbbd14-0ade-11e8-8c0f-82a59e36009e.png)

![valuetype5](https://user-images.githubusercontent.com/8586360/35836014-3f4b2406-0ade-11e8-84f7-67ea2af8b52c.png)

So, `Model.Content.Services` is a view model which is a shape that you can render with `DisplayAsync()` and here which contains a collection of `ContentItems` (not shapes). See in `BagPart.cshtml` how `BuildDisplayAsync()` is used on each `ContentItem`.

Finally, i think you can also override the `BagPart` view for the `LandingPage` type. This if you want more control on how each item is rendered, and so on.

**Comment by richb8** [comment]
Excellent, thank you for the explanation. BuildDisplayAsync was what I was after 👍🏻

**Comment by iyhammad** [comment]
I've the exact same issue here and trying to follow the excellent explanation you give.
When I edit the `LandingPage` Template, I found `Model.Content.Services` is of type `Castle.Proxies.BagPartViewModelProxy` as expected however, in my `Content-LandingPage.cshtml` Page I always have `Model.Content.Services` equals to null and because of this If I try to use `DisplayAsync()` it gives me an exception.
Am I doing something wrong?

**Comment by sebastienros** [comment]
In Razor `Model.Services` will be what you are looking for I think.

**Comment by jtkech** [comment]
As i remember, in case of a razor this is not the same accessor, try to use

    Model.Content.Named("Services")

**Comment by iyhammad** [comment]
Thanks. It works
