### ISSUE TITLE
Exception when BucketName is empty in AWS configuration

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#14485]
https://github.com/OrchardCMS/OrchardCore/blob/234f476cf241e5e1c2d5e5d95923fef6c7e67ac6/src/OrchardCore.Modules/OrchardCore.Media.AmazonS3/AwsStorageOptionsConfiguration.cs#L49

![image](https://github.com/OrchardCMS/OrchardCore/assets/1165805/55e96ec6-f30c-46c6-88a7-e02482fab87a)

We could throw a more specific exception when the value is null before using it.

**Comment by sebastienros** [comment]
Well, apparently it's already the case: https://github.com/OrchardCMS/OrchardCore/blob/234f476cf241e5e1c2d5e5d95923fef6c7e67ac6/src/OrchardCore.Modules/OrchardCore.Media.AmazonS3/AwsStorageOptionsConfiguration.cs#L59

**Comment by hishamco** [comment]
I assume to use config validation. One more thing is the AWS media settings shows a warning message?

**Comment by fatimaatharkhan** [comment]
Is this a good first issue for me as I am a junior, completing my Bachelor's degree in CS and this will be my first contribution. If not, can you assign an issue to me from this project that might be beginner friendly?

**Comment by hishamco** [comment]
Go for it @fatimaatharkhan

**Comment by fatimaatharkhan** [comment]
Thank you, I'm on it! I'll connect with you in case of any issues.

**Comment by Piedone** [comment]
In the latest source this doesn't happen anymore, and instead an error is logged: "S3 Media configuration validation failed with errors: BucketName is required attribute for S3 storage. fallback to local file storage."
