### ISSUE TITLE
ContentsAdminList filter by stereotype not working when already filtered by contenttype

### ISSUE THREAD

**Issue by yaricrolletservico** [OrchardCMS/OrchardCore#14480]
### Describe the bug

When we are in the admin dashboard on a list of a specific content type and we click on an url to filter the contents only for a specific StereoType the current page will be filtered instead of going to a complete new page.

### To Reproduce
1. We have the following url in our custom Admin Menu.
(/Admin/Contents/ContentItems/Product)
![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/d00b02c4-d0f2-4760-a305-f9dc34ebb7aa)

2. We have also an url that shows all modifiers. (There are multiple ContentTypes with stereotype Modifier in our project)
(/Admin/Contents/ContentItems?stereotype=Modifier)
![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/beda7589-953d-40b8-b986-1263b17dda66)

3. When we click on the "Modifiers" tab in our menu from the Products page we get the following url and result
(/Admin/Contents/ContentItems/Product?stereotype=Modifier)
![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/814b8b7c-57bf-47b9-88b6-d096f4c93014)

### Expected behavior
We would like to be able to go from a filtered ContentsList to our ContentsList filtered by stereotype.

### Screenshots
See screenshots above

**Comment by yaricrolletservico** [comment]
@MikeAlhayek I saw you submitted the PR. Is this something that can be fixed or did we implement it the wrong way.

**Comment by yaricrolletservico** [comment]
I've made a video and hopefully the issue is now clear.

1. I'm going with my custom AdminMenu to an overview page of all the Modifier stereotypes
2. I'm going with my custom AdminMenu to an overview page of all the Product content items
3. From that page I want to go back using my custom AdminMenu to the Modifier stereotypes overview page but instead we stay on the products overview page but with ?stereotype=Modifier in the querystring.


https://github.com/OrchardCMS/OrchardCore/assets/101557629/4c635b15-e174-4ed4-9b00-5c19fd67970f

**Comment by MikeAlhayek** [comment]
Can you please share with me the admin menu items you created? I can't reproduce the issue. I am guessing you are hard coding your "Product" link instead of using content Item link.

**Comment by yaricrolletservico** [comment]
Sure. This is the one for my Products
![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/490f3130-53b3-40e3-a666-44cc6b9e598a)

And this is the one for the Modifiers
![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/efd2c027-93ee-4990-93bf-2e7ddf261e55)

**Comment by yaricrolletservico** [comment]
Yes! this is kind of the solution for my problem but the other way around. I need to clear the contentTypeId when I want to show only content items of a specific stereotype. 

The problem was navigating from the products page to the overview page of the modifiers. 
The following solved my issue

![image](https://github.com/OrchardCMS/OrchardCore/assets/101557629/ed91372d-5a69-4c00-afcf-38ab0760ab86)
