### ISSUE TITLE
Add a shortcode for cache busting

### ISSUE THREAD

**Issue by DemeSzabolcs** [OrchardCMS/OrchardCore#14498]
### Is your feature request related to a problem? Please describe.
Here are the current image shortcodes: https://docs.orchardcore.net/en/latest/docs/reference/modules/Shortcodes/#available-shortcodes

There is no option to add a shortcode for cache busting. For reference, you can add cache busting in a `cshtml` file like this: `@Orchard.AssetUrl(assetPath: path, appendVersion: true)`.

So if somebody uses an image in (for example) an HTML Body part, there is no way to add cache busting with a shortcode.

### Describe the solution you'd like
Adding a shortcode that allows cache busting.

### Describe alternatives you've considered
...

**Comment by sebastienros** [comment]
@DemeSzabolcs please submit a PR for this

**Comment by DemeSzabolcs** [comment]
Sorry for the late response. I will!
