### ISSUE TITLE
Toggles password visibility on Theme login form (w/ workaround)

### ISSUE THREAD

**Issue by elaurentin** [OrchardCMS/OrchardCore#14510]
### Describe the bug
This may be the same previous bug as described here:
Toggles password visibility on login form #7008
**Bug:** The main issue here <script at="Foot"> is inserted multiple times.
I found a solution while preparing this report. Hope this is helpful for somebody.

### To Reproduce
1. Create a custom login page (just duplicate the one in OrchardCore.Users):
Views\OrchardCore.Users\Account\LogIn.cshtml
2. Make sure you include the script tag (<script at="Foot")
3. Toggle password button doesn't work

> [!NOTE]
After investigation, removing the ```at="Foot"``` works or adding the script tag inside of a zone https://github.com/OrchardCMS/OrchardCore/issues/13887

### Expected behavior
Toggle Password button should work

### Screenshots
![OrchardCore-Report1](https://github.com/OrchardCMS/OrchardCore/assets/5598813/c62210ae-adbd-4947-b480-c9fd6bcc7365)

**Comment by hishamco** [comment]
We need to check

**Comment by hishamco** [comment]
> I found a solution while preparing this report. Hope this is helpful for somebody.

Can you send a PR for it?

**Comment by hishamco** [comment]
Do you plan to create a PR to fix this?

**Comment by Piedone** [comment]
Awesome! Check out these if you haven't already: https://github.com/Lombiq/Orchard-Ambassadors-Toolboxand https://github.com/OrchardCMS/OrchardCore/discussions/14191.
