### ISSUE TITLE
Make PR as draft non-built from CI.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#14533]
I think it would be better for CI to not build automatically pull requests that are draft so that it costs less resources on the CI.

Just a perf adjustment that I think would make sense.

@sebastienros

**Comment by Piedone** [comment]
A PR being draft is an indication that it's not ready to be reviewed. That doesn't necessarily mean you don't want builds, since a passing build is also one of the things you need to consider a PR ready to be reviewed.

If you don't want the build to run for your commit (and all commits before that since the last push) then you can add `[skip ci]` to the commit message.

**Comment by Skrypt** [comment]
I don't think it makes sense to say that a PR needs to pass the build before considering it is ready because of the fact that it can be broken by other PRs that got merged in the meantime. The goal of a draft PR is to be able to work on it and set a list of things to do on it before making it ready to be reviewed. Normally, having it built locally and executing tests locally should be enough to make a draft as published. You are not supposed to rely on the CI to tell you if it builds or not or if the tests pass. Of course, the CI may have some discrepancies which can be fixed once the PR is published and built on the CI; but all these commits that are done on a PR while it is in a "draft" state never need to be tested/built against the CI.

Here, we are using a free service for building/testing but I'm pretty sure that if we were paying for this we would consider it.
I don't want to add a [skip ci] on every commit I do. The way I work is that when I think a feature is ready; I commit it. Segregating work in different commits the more I can so I can revert some of them if required later on.

**Comment by Piedone** [comment]
> I don't think it makes sense to say that a PR needs to pass the build before considering it is ready because of the fact that it can be broken by other PRs that got merged in the meantime.

Having a passing CI build is a really fundamental QA step that I don't see how one would skip to say a PR is ready for review. Running tests locally is good, but the CI workflow does this in a standardized way, including functional tests for multiple environments. That's really why we have CI and not rely on people running what happens there locally. If PRs merged in the meantime break a PR, then that PR needs attention and be fixed before review too. (Though you'd only notice this after a merge.)

> Here, we are using a free service for building/testing but I'm pretty sure that if we were paying for this we would consider it.

We certainly should be mindful of these resources we get for free, but the developer experience is also a point to consider. BTW at Lombiq we had this discussion at one point too, while paying for each build, and we arrived at the conclusion to have builds for draft PRs.

> I don't want to add a [skip ci] on every commit I do.

You don't need to. You only need to do this once for the last commit of your push.

> The way I work is that when I think a feature is ready; I commit it. Segregating work in different commits the more I can so I can revert some of them if required later on.

I do the same :).

> Also, a lot of stale PRs that we have here could be set to drafts so that it doesn't try to rebuild them every time we merge a PR.

I'm not sure what you're referring to here. The CI build is not re-run for open PRs after a merge to their target branch.

**Comment by Skrypt** [comment]
> Having a passing CI build is a really fundamental QA step that I don't see how one would skip to say a PR is ready for review.

I think having CI build passing is fundamental to getting it merged only. Not to get the PR reviewed. I agree it is better to have it, however, it taxes the CI queue pipeline a lot.

> I'm not sure what you're referring to here. The CI build is not re-run for open PRs after a merge to their target branch.

You are right, it doesn't happen anymore but at some point, I remember it did.

Look at my PR here for Vue 3 : https://github.com/OrchardCMS/OrchardCore/pull/14256

None of these commits needed to be built from the CI because I'm not done with the work. When I am ready to test it with the CI I will publish the PR and see if it builds with the CI. Then, it can break at any point even if I fix the build because of other PRs getting merged meaning it is not fundamental to have it building while we are working on it but fundamental to have it to get it merged.

**Comment by Piedone** [comment]
How about something like a "Skip CI" label that you can add to the PR if you want?

**Comment by sebastienros** [comment]
Thanks for the suggestion, but I agree that the CI is useful for draft PR and so far hasn't taken too much resources.
