### ISSUE TITLE
Use less ugly routes for the OpenID module actions

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#1453]
To work correctly with the default routes, the OpenID module currently uses `OrchardCore.OpenId/Access/Authorize`, `OrchardCore.OpenId/Access/Token` and `OrchardCore.OpenId/Access/Logout` as the authorization, token and end session endpoints.

Since these URLs are public and not very OIDC-ish, we should consider replacing them by better routes:
  - Authorization endpoint: `/connect/authorize`
  - Token endpoint: `/connect/token`
  - Logout endpoint `/connect/logout` or `/connect/end_session`

**Comment by sebastienros** [comment]
Sure
