### ISSUE TITLE
can't access fields wrappers separately for named parts and regular parts

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#14546]
Not sure if this is a bug or by design but I have a reusable part (named: **MyCustom**) attached multiple times to my **ContentType** (parts names: **FirstNamedPart** and **SecondNamedPart**) and also attached as a regular part. This part has just two fields (text field and boolean field).

So in general my **ContentType** looks like this:
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/890d5259-7441-4a79-a0f3-f92058e7a84c)

Now, let's say I want to style **fields** or **fields wrappers** via CSS separately, different styling for named part fields and different for regular parts. And it looks like this is currently not possible what I can read from the source code. All fields are using part technical names.

![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/80939c13-e8b8-40f7-8b42-235f05b12da4)

I've adjusted the code and now different classes are used for named parts and different for regular parts, so you can easily target them separately (via CSS or JS), here it is an example:

![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/cd3b320b-a1c7-456b-a789-c2ac62d4feb7)

If anyone is interested, please let me know I will prepare PR.
Here is the [code](https://github.com/OrchardCMS/OrchardCore/compare/main...lampersky:OrchardCore:lampersky/unique-class-for-named-parts).

This styling thing is just an example, I have a bit more complicated use case, but in general it can be simplified to what I've described here.

/cc @MikeAlhayek

**Comment by MikeAlhayek** [comment]
@lampersky i can't tell the different between both screen shoots in the generated class name.

I suggest that you show current behavior and requested behavior. Maybe submit a PR. At the very least, you are are cleaning up the views.

**Comment by lampersky** [comment]
@MikeAlhayek 

> I suggest that you show current behavior and requested behavior

This is exactly what I did above, maybe you were missed this slightly difference in class names, but let me explain again.

Before that change, whenever you will use reusable part it will get classes like this:
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/81c0a312-2abf-46cb-9d24-c7052cc43236)

which produces class names like: 
- for regular part (MyCustomPart): field-wrapper-**my-custom-part**-my-text-field,
- for named part (MyCustomPart with name FirstNamedPart): field-wrapper-**my-custom-part**-my-text-field,
- for named part (MyCustomPart with name SecondNamedPart): field-wrapper-**my-custom-part**-my-text-field.

After that change, field class name will be built like this:
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/39e46205-3a38-415d-8a34-6d1e91be0bae)

and this produces class names like: 
- for regular part (MyCustomPart): field-wrapper-**my-custom-part**-my-text-field,
- for named part (MyCustomPart with name FirstNamedPart): field-wrapper-**first-named-part**-my-text-field,
- for named part (MyCustomPart with name SecondNamedPart): field-wrapper-**second-named-part**-my-text-field.

> At the very least, you are are cleaning up the views.

Yes, I also noticed that this pattern for creating unique names is used in every field view, that's why I also cleaned views a bit.

To be able to use technical name of named parts, those changes were required: 
 
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/7738e7f3-39a5-477c-afe2-2bb3b8d459f9)
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/58a90211-30e8-4bf7-93f0-ee508920579a)

Please let me know if now it is clear.

**Comment by MikeAlhayek** [comment]
@lampersky why do you need to change the class name when you can target the id of the wrapper when it is reused?

Alternatively you can add a new wrapper class, but you would have to keep the existing one to avoid breaking others.

**Comment by lampersky** [comment]
> @lampersky why do you need to change the class name when you can target the id of the wrapper when it is reused?

@MikeAlhayek I'm working on some generic mechanism which needs all available **field wrapper selectors** or **part wrapper selectors** for particular **contentType**, and I wanted to generate them in the driver and pass to the view to later use them in JS code, but the thing is that I can't use **id** to target wrappers, because razor "Html.IdFor()" helper can't be used from outside views

![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/9c9ef696-1f1a-4d1c-8966-79b64c85cc8d)

that's why I ended up with something like this (pseudo code):
![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/b7f98535-4311-4202-91a3-bfea54aaacc0)

where I wanted to create full list of selectors for given contentType, but  then I realized that "uniqueName" is generated using **PartName Technical Name** no matter if we have **Named Part** or **regular Part**, and I think this is wrong, because this way we can't distinguish those field wrappers using classes

I hope now you will see where the problem is.

**Comment by MikeAlhayek** [comment]
@lampersky 
You could inject `IHtmlHelper` or `IHtmlHelper<ViewModel>` into your service and still use `_helper.Idfor(x=>x.Property)`

As previously mentioned, in your PR, you should not change the classes that are being used now. Some one may need the name of the content-part to apply specific styles regardless if it attached ones or many times. If you want to add these new classes, you'll have to check if the part is named, then add a new class name with the unique name.

for current `uniqueName` will be changes to `fullname` but the current class will stay the same. In addition to that, you would check if the part is named, then you would add a another class with the unique name

**Comment by lampersky** [comment]
@MikeAlhayek Consider it from another perspective:
what if I have two named **BagParts**, and I want to apply different styling to them? BagParts don't have "id" so you can't target them via "id"

![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/831fc5d2-84ec-4619-818b-55650be6aa2a)

**Comment by MikeAlhayek** [comment]
Are you saying we are missing an ID of a BagPart? It's worth adding an Id to that wrapper as well. Maybe that'll solve your problem.

**Comment by sebastienros** [comment]
Can yo provide a PR which would add the class with the named part too?

**Comment by lampersky** [comment]
> Can yo provide a PR which would add the class with the named part too?

@sebastienros it is here https://github.com/OrchardCMS/OrchardCore/pull/14547
