### ISSUE TITLE
Overriding Error Pages from the Template feature

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14548]
### Is your feature request related to a problem? Please describe.
I want to be able to override the error pages using the Template feature. 

### Describe the solution you'd like
Compose the error views as shapes instead of a standard MVC-action view.

### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/14543

**Comment by hishamco** [comment]
> Compose the error views as shapes instead of a standard MVC-action view.

What's wrong with overriding the views from the theme or web app?

**Comment by MikeAlhayek** [comment]
@hishamco 
Using a theme is a great default choice. But, what would you do if a tenant want to modify the default message? This is the power of shapes and the beauty of the Templates feature.

**Comment by hishamco** [comment]
We might need extra docs or guides on shapes because it's something special to OC, not ASP.NET Core dev. While I'm not using shapes to much I need a way to override views like normal ASP.NET Core application

**Comment by MikeAlhayek** [comment]
> We might need extra docs or guides on shapes because it's something special to OC, not ASP.NET Core dev. While I'm not using shapes to much I need a way to override views like normal ASP.NET Core application

Maybe all you need is to actually use Shapes and OC in a project, so you can learn all about them :)

**Comment by hishamco** [comment]
I used them when I create `AdminCulturePicker` but you destroy everything dude :)

**Comment by MikeAlhayek** [comment]
> I used them when I create AdminCulturePicker but you destroy everything dude :). 

Actually I just improved them even more by simplifying their injection process. What you did was good. Anyhow, if it is still a confusing topic for you, maybe use them more often so you can get comfortable. Either way, these comments are off the topic of this PR. Ping me separately if you have questions/comments around Shapes.

**Comment by hishamco** [comment]
I'm just kidding

> Ping me separately if you have questions/comments around Shapes.

Thanks

**Comment by sebastienros** [comment]
Only because the PR adds nice features, not because it's easier to customize
