### ISSUE TITLE
Configuring authentication per tenant

### ISSUE THREAD

**Issue by RolandGuijt** [OrchardCMS/OrchardCore#1455]
Is it possible to configure authentication per tenant using ASP.NET Core 2? 
For example add OpenIdConnect to the container and let each tenant use it's own ClientId and ClientSecret?
I need to support multiple authentication options, not just OpenIdConnect but also WS-Fed etc.

When I try it now the auth middleware just doesn't see the configured auth providers and when I use the auth middleware for each tenant the app explodes.

**Comment by sebastienros** [comment]
Will be done as part of https://github.com/OrchardCMS/OrchardCore/issues/2029
