### ISSUE TITLE
Document Dashboard widgets creation

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#14588]

**Comment by agriffard** [comment]
Example with TheBlogTheme: 
Create a Liquid Dashboard widget in Content types.
Enable Sql Query feature.
Create a Sql Query to list the blog post order by creation date desc.
Add a widget to display the N latest blog posts on the Dashboard.

**Comment by agriffard** [comment]
Is there anyone that wants to help writing such a guide in the docs?

- Explain the goal.
- Describe the steps.
- Make screenshots.
