### ISSUE TITLE
Evaluate using Contributors-Readme-Action to maintain Contributors.md

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#14586]
### Is your feature request related to a problem? Please describe.
The [Contributors.md file](https://github.com/OrchardCMS/OrchardCore/blob/main/Contributors.md) is currently maintained manually, by @agriffard. This could be automated.

### Describe the solution you'd like
The [Contributors-Readme-Action](https://github.com/akhilmhdh/contributors-readme-action) does this. It doesn't produce the same table though, only a simpler one, with just basic contributor details.

### Describe alternatives you've considered
Keeping the manual approach.

**Comment by Piedone** [comment]
@agriffard what do you think?

**Comment by agriffard** [comment]
You can put it in place.

**Comment by Piedone** [comment]
OK, thanks!

**Comment by Piedone** [comment]
Not so fast.

- https://github.com/akhilmhdh/contributors-readme-action wasn't updated for two years and will soon break due to https://github.com/akhilmhdh/contributors-readme-action/issues/67.
- https://github.com/jaywcjlove/github-action-contributors looks nice too though soon it'll need to upgrade to Node 20: https://github.com/jaywcjlove/github-action-contributors/issues/23.
- https://github.com/BobAnkh/add-contributors hasn't been updated for two years.
- https://github.com/marketplace/actions/contributors-action is more technical and less about recognition of contributors. It would be good with at least https://github.com/github/contributors/issues/23 added, possibly also https://github.com/github/contributors/issues/13 and https://github.com/github/contributors/issues/25.
- https://github.com/marketplace/actions/list-contributors wasn't updated for two years.
- https://github.com/marketplace/actions/contributor_list wasn't updated for three years.
- Cool map: https://github.com/marketplace/actions/contributor-map.
- https://github.com/marketplace/actions/contributors-list wasn't updated for two years.
- https://github.com/marketplace/actions/github-contributors-action not updated for three years.

None of these are better than https://allcontributors.org/ what we currently use. However, I'll add a mention about this, and try out Contributor Map.

Also:
@all-contributors please add @viktoriamagyar for eventOrganizing

**Comment by Piedone** [comment]
Check out https://github.com/OrchardCMS/OrchardCore/pull/15037.
