### ISSUE TITLE
Evaluate using the Issue Metrics Action

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#14585]
### Is your feature request related to a problem? Please describe.

This is more related to https://github.com/OrchardCMS/OrchardCore/discussions/14274. It's not related to a problem that I know of but may be useful for us to track community activity. I'm really not sure though, hence "evaluate".

### Describe the solution you'd like

The [Issue Metrics Action](https://github.com/github/issue-metrics) can generate metrics for issues and discussions like Time to First Response, Time to Close, and Time to Answer for discussions.

Related action: https://github.com/github/contributors

### Describe alternatives you've considered

Not having any metrics, like we do currently. This may be just fine, I'm not sure if we really need this.

**Comment by sebastienros** [comment]
No harm in doing it, right?

**Comment by Piedone** [comment]
I don't think so, unless it'll be useless noise.

**Comment by Piedone** [comment]
Tried it, looks useful! We need a bug of it fixed first I think, see here for details and issues it created for issue and PR metrics: https://github.com/OrchardCMS/OrchardCore/pull/15041#issuecomment-1885933870

**Comment by Piedone** [comment]
Opened https://github.com/github/issue-metrics/issues/190 as we discussed during the meeting today.
