### ISSUE TITLE
GraphQL - DynamicContentTypeBuilder: Broken when typed part is registered

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#14592]
### Describe the bug
Dynamic content type builder generates duplicate fields directly to content type. This happens when you register custom content part as typed, when it has fields registered in CMS.

### To Reproduce
1. Create a part in CMS with fields, add to Content type
2. Register custom ObjectGraphType for this part
3. Open GraphiQL console
4. View Content type - now it has fields both in registered custom part and directly in content type (as when you collapse part)

After debugging I think problem is here:
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/DynamicContentTypeBuilder.cs#L85

![image](https://github.com/OrchardCMS/OrchardCore/assets/52829889/3ebcedc4-9a60-49f0-83d7-f2ed6b51f221)

Builder already has handling for existing parts. But it does not add missing fields to part. Instead, it adds all fields, even when they are already in part, directly to content type. It checks missing fields against content type instead of content part.

### Expected behavior
When custom ObjectGraphType is registered, dynamic builder...
* Should not duplicate existing fields and place them directly under content type
* Should either do nothing with existing part OR better - it should add only missing fields under given part.

### Screenshots

![image](https://github.com/OrchardCMS/OrchardCore/assets/52829889/c1a09b28-0e15-4860-861f-f0d0cc1c8df4)

Highlighted props are from dynamic content type builder.

**Comment by lampersky** [comment]
@MikeKry please have a look if this is a similar problem to this one https://github.com/OrchardCMS/OrchardCore/issues/13926#issue-1782804459

**Comment by MikeKry** [comment]
@lampersky 

The one you mention will not fix this issue - if field does not exist in part, it will still add it to base content type

![image](https://github.com/OrchardCMS/OrchardCore/assets/52829889/6d4f401c-24ec-4f46-a172-fadfd4bb3900)

this would need to be handled - add it to part instead of type.
(this issue refers to non-collapsed parts only)

**Comment by MikeKry** [comment]
For my current project I have done following:
* copy DynamicContentTypeBuilder - comment out the line with adding fields to content type
* created publicly visible DynamicPartGraphType, so I can use it as a decorator around my custom content part

It works like this, but I guess it could be done better when handled directly in DynamicContentTypeBuilder

**Comment by sebastienros** [comment]
Do you want to suggest a PR?
