### ISSUE TITLE
Monaco editor widget error

### ISSUE THREAD

**Issue by spyraklas** [OrchardCMS/OrchardCore#14594]
### To Reproduce
1. Create a content type widget named -> "Js Editor"
2.  Add a text field called "Script".
3.  In the settings of the text field set editor "Monaco Editor" and editor options 
`{
  "automaticLayout": true,
  "language": "javascript"
}`
4.  Create a content type "Page" with a flow part
5.  Go to your content items and create a new "Page"
6. Take a look on your browser console. you should be able to see the following error
![error](https://github.com/OrchardCMS/OrchardCore/assets/93044877/fb45c364-f445-4b8b-a2b6-f8654718edc8)
`Uncaught TypeError: Cannot read properties of null (reading 'parentNode')`

I reason of the error is that monaco editor script try to initialize the text fiend that is not yet within the page DOM.

The same issue should happen if you add a widget using body part or html field and set the monaco editor within your settings.

### Propose solution
To solve the issue you can change the javascript code on the following views of the OrchardCore.ContentFields module files:
1. TextField-Monaco.Edit.cshtml
2. HtmlField-Monaco.Edit.cshtml

and OrchardCore.Html module file: 
1. HtmlBodyPart-Monaco.Edit.cshtml

Add within the `require(['vs/editor/editor.main'], function () {` function on top
`var divEditor = document.getElementById('@Html.IdFor(x => x.Text)_editor');`

and below check if the div editor exist.
`if (divEditor != null || divEditor != undefined)`

Wrap the if statement around the javascript initialize code and change the create statement to
`var editor = monaco.editor.create(divEditor, settings);`

I hope that helps.

**Comment by giannik** [comment]
i confirm this happens too  , woth latest  code.

**Comment by agriffard** [comment]
Thank you @spyraklas for creating the issue, giving some reproduction steps and suggesting a solution.

Do you want to create a PR in order to provide a fix?

**Comment by giannik** [comment]
@spyraklas   there is a UrlHelperExtensions.ToAbsoluteUrl    to convert a relative to absolute url.

**Comment by spyraklas** [comment]
Thanks @agriffard happy to help. 

I am new to your project and I got no access permissions to push my branch and create a PR with the code fix I had propose. Is there a process to become a contributor?

Hi @giannik thanks for point me to the UrlHelperExtensions. Although I am not sure how converting a relative to absolute url  will help in this case.

**Comment by sebastienros** [comment]
> I got no access permissions to push my branch and create a PR

Every one does, you just don't know how yet!

Create a fork. Do the changes on your fork. Commit the change. And create a PR from your fork. If it's not clear you should find some video tutorials online by googling for "Create PR github".

**Comment by spyraklas** [comment]
@sebastienros thanks for the guide. here is the PR https://github.com/OrchardCMS/OrchardCore/pull/14624
