### ISSUE TITLE
Validation errors are not correctly rendered with the default admin theme

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#1461]
For some reasons, validation `span`s end up being styled with `display: none`, which prevents the browser from displaying them.

![image](https://user-images.githubusercontent.com/6998306/35867921-5cee18ce-0b5b-11e8-8bad-da9a69ccb7b8.png)

@agriffard could that be caused by a recent change in Bootstrap or is it something we should fix in the Sass file?

**Comment by PinpointTownes** [comment]
@agriffard ping.

**Comment by agriffard** [comment]
I extended the `is-invalid` Bootstrap css class for validation errors in admin :
https://getbootstrap.com/docs/4.0/components/forms/#server-side

**Comment by PinpointTownes** [comment]
Great, thanks @agriffard!

**Comment by PinpointTownes** [comment]
Looks like this has (recently?) regressed as the infamous `display: none` is back:

![image](https://user-images.githubusercontent.com/6998306/46259613-f9a4a900-c4db-11e8-8e00-a771153d4595.png)

**Comment by PinpointTownes** [comment]
@sebastienros it's a very serious bug: we should really fix that in beta3. Currently, error messages are invisible so it's impossible to figure out what's going on when a field is not valid.

**Comment by sebastienros** [comment]
Thanks

**Comment by PinpointTownes** [comment]
> I found the problem.

Nice!

> The changes are made on my machine but I will wait that #2820 is merged to submit a PR because some views using codemirror will change.

Could https://github.com/OrchardCMS/OrchardCore/pull/2827 be merged as part of beta3, is it too early for that?

**Comment by agriffard** [comment]
#2827 could be merged so it should be good for beta3.
