### ISSUE TITLE
Menu Tag Helper

### ISSUE THREAD

**Issue by DJSADERS** [OrchardCMS/OrchardCore#1465]
There seems to be an issue with the Menu tag helper, i have the tag used as follows:

`menu alias="alias:topmenu" /`

and a view of:
`
Menu-topmenu.cshtml`

however it is loading the default tag helper razor view rather than the alternate view in the theme.

**Comment by DJSADERS** [comment]
You can repoduce this by adding the menu tag helper with a custom menu, and then created an alternate view of Menu-menuname.cshtml in the theme.

OrchardCore should be using the Alternate view however it loads the default tag helper view.

Adding a breakpoint in MenuShape.cs in OrchardCore.Modules.CMS.Menu you can follow through and see that it loads the views as follows:

[0] Default taghelper view
[1] Alternate view

**Comment by jtkech** [comment]
After a quick look, in `MenuShapes.cs` the added alternate would be related to a e.g a `Menu-alias:main-menu.liquid` file which is not a valid file name. So for testing, if we remove the `alias:` term.

                        menu.Metadata.Alternates.Add("Menu__" + EncodeAlternateElement(identifier)
                            .Replace("alias:", ""));

Then the `Menu-main-menu.liquid` template view works on my side.

**Comment by DJSADERS** [comment]
I'm working with Razor Views so i would presume it would ahve the same effect?

**Comment by sebastienros** [comment]
After the PR is merged this will become `Menu-MainMenu`
