### ISSUE TITLE
OpenID Server not adding claims to identity token based on requested scopes (e.g. profile, email)

### ISSUE THREAD

**Issue by mvarblow** [OrchardCMS/OrchardCore#14655]
### Describe the bug

The OpenID Server module is not adding claims to the identity token based on requested scopes (profile, email) as it should.

### To Reproduce

The setup for this is a bit complicated because it requires both an Orchard Core site acting as the OIDC Identity Server and another application acting as the client/relying party. Some notes on the setup:
* I'm using a plain Orchard Core 1.7 site with the Open ID Authorization Server feature enabled. 
* I'm using the Authorization Code Flow and the JSON Web Token "Token Format" setting.
* I've added profile and email scopes through the management interface (seems like they should be included automatically, but I am not able to complete the next step without adding them myself as valid scopes).
* I've added an application and granted it access to the Authorization Code Flow and the profile and email scopes. (I also set the consent type to "Impicit consent" and provided the redirect URI.

It took a bit of sleuthing to determine how this all holds together, but here's what I was able to determine after stepping through the OrchardCore and OpenIddict code a few times.

My client (relying part) application redirects the user to the Open ID Authorization Server authorization endpoint (OrchardCore.OpenId.Controllers.AccessController.Authorize). The first time through, the user is redirected to the normal Orchard Core sign-in page and then redirected back to the Open ID authorization endpoint. This time, the controller first grabs the Orchard Core claims identity. It includes the following claims (AccessController.cs line 83):

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/0a185852-3f40-4ebc-99f0-bca01b8ba24f)

The AccessController.Authorize method the supplements those claims by adding the granted scopes, resources, etc. Now on line 137 the claims collection looks like this:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/da8a5e36-660d-44ee-a665-7e44261da891)

The Authorize method has looped through all the claims to set a .destinations property on each claim. This property identifies which tokens should include the claim. The determination of token destinations for each claim is made by the GetDestinations method which is hard coded in AccessController.cs (I wish this were overrideable, oh well):

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/2a89b134-b72b-479f-8597-a5ed75889437)

Note that both the name and email claims have the .destinations property set to include both id_token and access_token as expected.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/9aaf2fdf-c36c-4e5e-936c-5ab407c39cf2)

The relying party (my client application) receives an authorization code and makes the call to the token endpoint. (The standard OIDC authorization code flow). The token endpoint (OrchardCore.OpenId.Controllers.AccessController.Token) sees that this is an authorization code flow so it calls ExchangeAuthorizationCodeOrRefreshTokenGrantType. That method first calls AuthenticateAsync using the OpenIddict authentication scheme and gets back a claims principle containing all the claims that were set earlier by the authorization endpoint. The claims collection on the principle looks like this:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/8b6dc0a7-d70f-448c-bf9e-db7be5c6a1fe)

Note that it includes the granted scopes (oi_scp claims) and the claims include the .destination property. The name and email claims both have the .destination property set correctly at this point to include both the id and access tokens.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/0b3fa89c-9c94-450e-aae0-1dd795450d21)

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/2e1504f9-053b-4851-a182-7b03fdf96580)

Here's where we run into a problem. The AccessController.ExchangeAuthorizationCodeOrRefreshTokenGrantType method includes this interesting code which was added back in 2019:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/dd0c338d-c32d-49b4-97c7-c57e3ea333ca)

Getting fresh data is good in case the sign-in happened a while ago. However, all the scopes and the properties (such as .destinations) which were added earlier to the claims list by the OpenIddict OAuth pipeline are lost! The claims list is rest back to only include the original claims from the Orchard identity principal.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/eb32325d-2a5a-4db2-a4d9-5b284e326b13)

The identity token received by the calling application does not include the name or email claims as it should. They only non-protocol claim we get is the subject (sub) claim because that one is always included. Claims for the requested scopes are not included because the code block in ExchangeAuthorizationCodeOrRefreshTokenGrantType stripped away all the scope claims and the destinations. The destinations are recomputed at the end of ExchangeAuthorizationCodeOrRefreshTokenGrantType but they are recomputed incorrectly because the claims for the granted scopes were removed by that "refresh" code block (see above).

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/4f1e515f-5c25-4065-ad4f-e796d8643f94)

### Expected behavior
The identity token returned from the token endpoint using the authorization code flow should include the name claim if the profile scope is requested. It should include the email claim if the email scope is requested. And it should include role claims if the roles claim is requested.

### Screenshots

See above.

**Comment by rafaelrph** [comment]
@sebastienros and @jtkech 
This issue is very similar to the one that I'm having now after upgrading to 1.7.0

The Media Security doesn't work as it was before the upgrade.
If I login to a userX, create a page with a media and get the media URL. The media is accessible for any authenticated users by the URL, even if the page is published or not, and also when the user doesn't have access to the page.

My application has its own controller to handle these media requests, which is almost the same as this file:
https://github.com/OrchardCMS/OrchardCore/blob/03dd2f72c82f85ce213642286f8165f24022baa2/src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs

When the request arrives, the HttpContext.User doesn't have any claims or any custom data.
The logic just by-passes the authentication and returns the media that it should not return.

**Comment by mvarblow** [comment]
@rafaelrph: this seems like a separate issue. The issue I reported here is specific to using the Open ID Server module with the authorization code flow.

I just submitted a pull request that seemed to fix the problem for me. The fix was to -- when exchanging an authorization code for a token -- copy the granted scopes and resources from the original authorization code to the new/refreshed principal.

cc @sebastienros and @jtkech

**Comment by jtkech** [comment]
@mvarblow Yes I saw your PR, I asked @kevinchalet for a review.

@rafaelrph I will try to repro your use case.

**Comment by rafaelrph** [comment]
@jtkech the issue has been fixed in our side. Thanks for the help

**Comment by jtkech** [comment]
Cool then, thanks
