### ISSUE TITLE
Admin content item list ordering

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1468]
The ordering of the list of content items in the admin panel seems to have reversed (i.e. it's showing most recently edited content last). This is a relatively recent regression.

The admin controller appears to be trying to order the items correctly, but without success: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/AdminController.cs#L130. I wonder if the recent changes to YesSQL to allow paging without specifying an order have caused this?

**Comment by sebastienros** [comment]
Correct, now if no order is specified it's using the `Id`, I assume that did it. We need to add the `ModifiedUtc` by default. (for now).

**Comment by paynecrl97** [comment]
Modifiedutc descending is the default. It looks like it’s not have an effect

**Comment by sebastienros** [comment]
Ah, thanks, probably a bug, I will check.
