### ISSUE TITLE
Obsolete reference to Dependencies.AspNetContrib.props

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#1469]
Hi,

In the solution folder build you have a reference to a file that does not exist anymore (Dependencies.AspNetContrib.props).

**Comment by PinpointTownes** [comment]
Hey,

Thanks for reporting that.
Fixed by https://github.com/OrchardCMS/OrchardCore/commit/5b47c1a232b65d7ad09343434cd7a86c9c4ec7c6.

**Comment by jpiquot** [comment]
Thanks.
