### ISSUE TITLE
Add support for Azure Email Communication Services

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/OrchardCore#14699]
### Is your feature request related to a problem? Please describe.
Azure now has a new set of resources under the Communication Services (ACS) umbrella, [Email Communication Services](https://learn.microsoft.com/en-us/azure/communication-services/concepts/email/email-overview) being one of them. This is a cheaper, Azure-native alternative to SendGrid.

### Describe the solution you'd like
The primary way to use it is not through traditional SMTP-server configuration, but a connection string (of two components, endpoint and access key) provided the ACS resource, which allows access to the specific communication service resources attached to it (for example an Email Communication Services instance). This requires a custom implementation to send emails using the corresponding [SDK](https://learn.microsoft.com/en-us/azure/communication-services/concepts/email/sdk-features).
OrchardCore.Email doesn't seem to support this scenario at its current state and needs a bit of refactoring (can take inspiration from [the structure in O1](https://github.com/OrchardCMS/Orchard/tree/1.10.x/src/Orchard.Web/Modules/Orchard.Email/Services) for better extensibility). Initial ideas for implementation:
- Rename [ISmtpService](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.Email.Abstractions/ISmtpService.cs) to IEmailService for clarity.
- Move some of the logic (mostly related to validation) out of [SmtpService](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.Email.Core/Services/SmtpService.cs) to make it reusable. EmailService base class?
- Implement email sending through Azure Email Communication Services in OrchardCore.Email.Azure (new).
- As for the settings screen, add "Azure Communication Services" as a new "Delivery method" (although the existing two options are wired in via [SmtpDeliveryMethod](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.Email.Abstractions/SmtpDeliveryMethod.cs) and `SmtpService` in its current state will throw an error for any other delivery method) and "Azure delivery options" needs only two fields (endpoint and access key). Also make it possible to read these from app configuration.

### Describe alternatives you've considered
Traditional SMTP-servers, like SendGrid are still available and ACS also supports sending emails through SMTP, but [the setup for that is very tedious](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email-smtp/smtp-authentication).

**Comment by hishamco** [comment]
I was thinking about both email and SMS azure services

I might handle those if no one planned

**Comment by BenedekFarkas** [comment]
I'd rather keep this issue focused on the email functionality, but keeping further features and extensibility in mind is definitely a plus. On a related note, the base configuration should go to a separate `OrchardCore.Azure.Communications` module or something like that.

> I might handle those if no one planned

Sounds great! :)

**Comment by Piedone** [comment]
One more thing: for this feature, we'd need `IShellConfiguration`-based configuration, like it is possible for all the other Azure services. I don't think we need site settings; if you're using anything more complex than a simple SMTP server, than you're already involved with hosting your app, and at that point, environmental configuration is better.

**Comment by hishamco** [comment]
That's what I thought about

**Comment by BenedekFarkas** [comment]
Sounds good as the same applies to Azure Blob Storage too.

There needs to be a clear distinction that this feature is in effect, so the current (SMTP-based) email functionality should not be enabled for this to work (or indicate that it's behavior is overridden) and make sure that SMTP-based email functionality can remain operational alongside ACS, not force an update on users, e.g., if someone wants to use ACS for SMS 2FA, but wants to stick to their current SMTP-settings for email sending.

**Comment by hishamco** [comment]
> Sounds good as the same applies to Azure Blob Storage too.

Exactly

**Comment by BenedekFarkas** [comment]
Please keep it focused on the basic integration and email functionality for now, but with the possibility of adding further ACS-based features in the future.

**Comment by Piedone** [comment]
Yeah.

And as for the UX, I imagine exactly the same as with Azure Media Storage: We have the basic (current) SMTP functionality enabled by the Email module, and if you enable the ACS, then it'll override that, with a similar indication than this:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/0f9dfcf9-1d1c-43ac-893e-80b4e508e37d)

**Comment by hishamco** [comment]
What I already did is something similar, whereas the ACS settings come from `appsettings.json`.

If we look closely into AECS the new thing should be added is the connection string, so the sender will be shared for both modules, and while the new should works independently either we have a dependency on `OC.Email` module to utilize the same sender or add the ability to override it from within the `OC.Email.Azure` module

**Comment by hishamco** [comment]
@BenedekFarkas @Piedone What I already did in the draft PR is separate the basic email settings (Default Sender) - we could add a display name later if we want - from the SMTP settings, this way AECS does not depend on the SMTP feature at all but email feature.

Once AECS is enabled it shows the default send from the email feature but we could override it from within the `appsettings.json`

Please let me know if we need to change anything else

**Comment by Piedone** [comment]
Sounds good!

**Comment by hishamco** [comment]
The PR is almost ready I just need to add few tests

**Comment by hishamco** [comment]
I tested the `AzureEmailService` using ECS and works as expected, can we do an initial review

**Comment by Piedone** [comment]
Is the code as far as you're concerned complete?

**Comment by hishamco** [comment]
Yep, I got some comments from that might change the implementation from what we thought about

Please have a look and let me know your comments

**Comment by Piedone** [comment]
Done in https://github.com/OrchardCMS/OrchardCore/pull/15254.
