### ISSUE TITLE
Drop support for .NET 6/7

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14694]
Is there a reason to keep support for .NET 6 and .NET 7 that .NET 8 is already supported?

@jtkech @agriffard  @Piedone @Skrypt any objections?

**Comment by Skrypt** [comment]
I think the rule is to support at least one LTS version. So we should drop at least 6.0

**Comment by Piedone** [comment]
While I'm not a time traveler like Jasmin to have .NET 7 EOL :), I agree. We always only support the latest LTS, and if it's not the latest version altogether, then additionally that too (hence .NET 6 and 7).

So yeah, remove .NET 6/7, and then I think only the `8.0.100-rc.2.23502.2` references JT added [here](https://github.com/OrchardCMS/OrchardCore/pull/14058/files) need to be changed to `8.0.100`.

I'll do that.

**Comment by jtkech** [comment]
Yes, or remove them just before shipping the next OC release.

**Comment by Skrypt** [comment]
ah yeah were in 2023 still lmao. 😄

**Comment by MikeAlhayek** [comment]
After we drop the support of .NET 6 and 7, we should also drop support for Microsoft.Extensions.Http.Polly package. Instead, we can use 
[Microsoft.Extensions.Http.Resilience](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.http.resilience?view=dotnet-plat-ext-8.0)

**Comment by hishamco** [comment]
I might against to drop both 6 & 7, I think it's fine to have the latest LTS version, but that doesn't mean we should drop 7

Again we could use preprocessor directive in case we want to use a new API for a particular case
