### ISSUE TITLE
Deploy preview docker image for Windows setp in the "Preview - CI" is failing

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14703]
Strange error in the CI. It's failing. I am wondering if it is pulling from cache for some reason. The same step works on Ubuntu.

https://github.com/OrchardCMS/OrchardCore/actions/runs/6881515041/job/18718018240#step:13:230

```
 Sending build context to Docker daemon  580.4MB

Step 1/6 : FROM mcr.microsoft.com/dotnet/aspnet:8.0
8.0: Pulling from dotnet/aspnet
no matching manifest for windows/amd64 10.0.20348 in the manifest list entries
Login Succeeded
An image does not exist locally with the tag: ***/orchardcore-cms-windows
The push refers to repository [docker.io/***/orchardcore-cms-windows]
Error: Process completed with exit code 1.
```

@sebastienros  @jtkech any idea why this step is failing?

**Comment by sebastienros** [comment]
https://github.com/dotnet/dotnet-docker/issues/5009

**Comment by sebastienros** [comment]
Solution:

Detect the target os:
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/

With `8.0-nanoserver-1809` on Windows (what 7.0 was pointing to before that change).

**Comment by MikeAlhayek** [comment]
@sebastienros this is still failing after the fix was merged.

**Comment by hishamco** [comment]
I think the issue still exists

**Comment by MikeAlhayek** [comment]
@hishamco yes that is what I said in my last comment and is why I re-opened the issue.

I'll research it more later on. I think we need to specify `--platform` parameter to the `docker build` command but not sure.

**Comment by sebastienros** [comment]
I'll @jtkech close the issue if he thinks this is fixed

**Comment by jtkech** [comment]
I may have some last tweaks to do but yes, it seems to work so I'm closing this issue.
