### ISSUE TITLE
Bug: Media middleware intercepts non-media requests and crashes

### ISSUE THREAD

**Issue by jhdrn** [OrchardCMS/OrchardCore#1472]
This is a quite severe bug with the media module: Whenever a query string is appended to a path containing a by ImageSharp supported file extension, the ImageSharp middleware will intercept the request and then throw an exception. 

I noticed this behaviour when I tried to edit a content item in the admin area and it crashed repeatedly (the content item id contained the character sequence triggering the bug). I debugged the source and this is what I found:

1. Whenever a query string is found in the request URI, the ImageSharp.Web middleware will try to parse it for "commands" (it will add any query params into a dictionary). It will then call `OnValidate` which will trigger configuration in OrchardCore.Media/Startup.cs where the command `max` will be added (because ImageSharp.Web added a command with the key of whatever was found in the query string). 

OrchardCore.Media/Startup.cs:
```
if (validation.Commands.Count > 0)
{
    if (!validation.Commands.ContainsKey(ResizeWebProcessor.Mode))
    {
        validation.Commands[ResizeWebProcessor.Mode] = "max";
    }
...
```

2. After OrchardCore.Media has added the "max" command, ImageSharp.Web will check if there are any known commands that it should process. It will ignore the invalid command added from "whatever" in the query string, but as OrchardCore.Media added the known command "max", ImageSharp.Web will continue it's request processing.

This is the ImageSharp.Web middleware source:
```
if (!commands.Any() || !commands.Keys.Intersect(this.knownCommands).Any())
{
    // Nothing to do. call the next delegate/middleware in the pipeline
    await this.next(context);
    return;
}
```

3. When ImageSharp.Web continues it's request processing, it will resolve an `IImageResolver`, i.e. `OrchardCore.Media.Processing.MediaFileSystemResolver` and call `IsValidRequestAsync` on it. 

The problem here though is that FormatHelpers.GetExtension will check THE WHOLE PATH for a matching extension (not just the ending):
```
    public Task<bool> IsValidRequestAsync(HttpContext context, ILogger logger)
    {
        return Task.FromResult(FormatHelpers.GetExtension(this.options.Configuration, context.Request.Path) != null);
    }
```
4. As `IsValidRequestAsync` returns true, ImageSharp.Web middleware will continue it's processing and try to load the "media", ultimately ending in an exception in OrchardCore's `IMediaFileStore.MapPublicUrlToPath` which thinks the path is invalid.

This bug can be triggered quite easily by just enabling the media module and enter a URL with a by ImageSharp known file extension somewhere in the path together with any query string, for example:

`http://localhost:5000/tenantpath/jpg?foo`
`http://localhost:5000/tenantpath/Admin/Contents/ContentItems/4ppqyv37zrrbm3nksa8tjbz354/Edit?returnUrl=...` - this was the URL that failed for me. Why? It contains the string "bm" which ImageSharp thinks is a bitmap file extension.

**Comment by sebastienros** [comment]
TODO: Ensure we are using the latest ISWeb version

**Comment by jtkech** [comment]
So, i put a breakpoint here.

      validation.Commands[ResizeWebProcessor.Mode] = "max";

And i tried the following.

    // Doesn't hit the breakpoint but no error, only 404
    https://localhost:44300/media/logos/.jpg
    https://localhost:44300/media/logos/.jpg?
    https://localhost:44300/media/logos/.jpg?foo
    https://localhost:44300/media/logos/.jpg?foo=100

    // Idem but displays the image
    https://localhost:44300/media/logos/envato.jpg
    https://localhost:44300/media/logos/envato.jpg?
    https://localhost:44300/media/logos/envato.jpg?foo
    https://localhost:44300/media/logos/envato.jpg?foo=100

    // Hit the breakpoint
    https://localhost:44300/media/logos/envato.jpg?width // no effect on the size
    https://localhost:44300/media/logos/envato.jpg?width=150 // works as expected

This also works but you said that it depends on the character sequence of the content item id.

    https://localhost:44300/Admin/Contents/ContentItems/49sqacg9qv36v0avrfang7s4nt/Edit?returnUrl=%2FAdmin%2FContents%2FContentItems

The only way to log an error was to use a valid command on an non existing file (or just the extension) which seems to be normal.

    https://localhost:44300/media/logos/.jpg?width=100
    https://localhost:44300/media/logos/envato123.jpg?width=100

    2018-06-13 03:11:53.2653|None|0HLEGP3D1F3SP:00000003||SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware|ERROR|The image 'https://localhost:44300/media/logos/.jpg?width=100' could not be resolved

**Comment by jtkech** [comment]
@sebastienros i did some tests and i would say.

    We close it but feel free to re-open it if it is still an issue for you.
