### ISSUE TITLE
Move IdGenerator from ContentManagement to a more common place

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1473]
The ContentManagement module contains a convenient service called `IdGenerator`  that generates unique IDs that are shorter than GUIDs. Ideally, we can leverage that service for Workflows and potentially other modules as well.

If others agree, then the question is: where should it be moved to?

**Comment by sebastienros** [comment]
In a library that is common for Orchard resources. Not in a module for sure, even though modules should be able to override it.

**Comment by sfmskywalker** [comment]
OK, so I'll move both the interface as well as a default implementation to a common package. There doesn't seem to be an existing library to where it should belong though, but creating a new library called OrchardCore.IdGenerator seems a bit overkill. I also don't want to create a mother library of all trades either. Suggestions? Perhaps OrchardCore.Data?
