### ISSUE TITLE
Import content items, is not importing everything due missing Authors

### ISSUE THREAD

**Issue by ColinRaaijmakers** [OrchardCMS/OrchardCore#14769]
I have a strange behaviour while deploying content from our OrchardCore website in Test environment to our OrchardCore website in Acceptance environment.

I have a deployment plan to export Content Items, like Taxonomies and other (standard) content types.

Some of the content items are imported, but some of them are not.

When I change the Author in the recipe.json, they will be imported.
But, I guess, when the Author is non-existing, the content items aren't imported.

Can someone explain this behaviour? Is this a bug in OrchardCore, or in the recipe?

Please, help me out!

**Comment by hishamco** [comment]
>  "Owner": "[js: parameters('AdminUserId')]",
          "Author": "[js: parameters('AdminUsername')]",

I thought you did a fallback in the code when the author is not exist

**Comment by MikeAlhayek** [comment]
I am closing this one. If you have more feedback, feel free to reopen it
