### ISSUE TITLE
In dark mode, the CodeMirror input automatically sets an incorrect white background color.

### ISSUE THREAD

**Issue by FadiAlhayek** [OrchardCMS/OrchardCore#14775]
When you modify the Title Content Part, the pattern field in CodeMirror turns background color to white when using dark mode.

![image](https://github.com/OrchardCMS/OrchardCore/assets/152227310/71b099f4-7612-4140-8d5a-46cb4c040007)

**Comment by MikeAlhayek** [comment]
This issue should be already fixed in 1.8 previews.
