### ISSUE TITLE
Support static Razor compilation

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#1478]
I used  <MvcBuildViews>true</MvcBuildViews> inside .csproj,
 but can not detect the  error on razor page.

=================
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    
    <ErrorReport>prompt</ErrorReport>
    <MvcBuildViews>true</MvcBuildViews>
    <WarningLevel>4</WarningLevel>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.1" />
    <PackageReference Include="SixLabors.ImageSharp.Web" Version="1.0.0-beta0002" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OrchardCore\OrchardCore.ContentManagement.Abstractions\OrchardCore.ContentManagement.Abstractions.csproj" />
    <ProjectReference Include="..\..\OrchardCore\OrchardCore.ContentManagement.Display\OrchardCore.ContentManagement.Display.csproj" />
    <ProjectReference Include="..\..\OrchardCore\OrchardCore.ContentTypes.Abstractions\OrchardCore.ContentTypes.Abstractions.csproj" />
    <ProjectReference Include="..\OrchardCore.ContentTypes\OrchardCore.ContentTypes.csproj" />
    <ProjectReference Include="..\OrchardCore.Media\OrchardCore.Media.csproj" />
  </ItemGroup>

</Project>

```

**Comment by sebastienros** [comment]
Is it how it's supposed to work, that it build the views when you build the csproj?
We currently already use razor compilation, but it's done on Publish.

**Comment by jtkech** [comment]
I will take a look on this as i have time. Would be awesome to be able not only to embed razor views but also make them precompiled at the module level.

**Comment by sebastienros** [comment]
What? They are not precompiled ???? I thought they were.

**Comment by jtkech** [comment]
Yes they are but as you said only on publishing the app by using the view precompilation tool which can't be used (as far as i know) at the module library level.

So, the view precompilation tool generates a `OrchardCore.Cms.Web.PrecompiledViews.dll` at the app level.

**Comment by sebastienros** [comment]
good then

**Comment by jtkech** [comment]
So, we don't really need this at the module level but it could allow a module to provide its own views as precompiled even if a developper doesn't use the precompilation tool at the app level.

Hmm, at least this would need an additional assembly for each module. Note: i think it was possible when we were using `Sdk="Microsoft.NET.Sdk.Web"` also for modules. Anyway better to use `"Microsoft.NET.Sdk"` for module libraries, will see if it is still possible.

**Comment by jtkech** [comment]
@sebastienros @infofromca copied from somewhere

It's not currently possible. ASP.NET Core MVC lacks the MvcBuildViews property which ASP.NET 4.x has: https://blogs.msdn.microsoft.com/jimlamb/2010/04/20/turn-on-compile-time-view-checking-for-asp-net-mvc-projects-in-tfs-build-2010/. There's an issue asking for this compilation-on-build feature. Please give it a thumbs up and/or add comments to express your interest: https://github.com/aspnet/MvcPrecompilation/issues/214.

Then the open issue has been moved to https://github.com/aspnet/Razor/issues/1809
