### ISSUE TITLE
Adding IsDevelopment property in liquid

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore#14794]
### Is your feature request related to a problem? Please describe.
Currently, you can't check if you are in Development or Production in liquid.

### Describe the solution you'd like
Add IsDevelopment property that would return a boolean of the `IHostEnvironment.IsDevelopment()` result.

**Comment by hishamco** [comment]
Yep, this is one of the features missing in OC, that's why I created `OCC.Liquid` module

https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/tree/main/src/OrchardCoreContrib.Liquid

**Comment by hishamco** [comment]
If this is something need to add in the OC I can create a PR for it, otherwise we can use 3rd party module

/cc @sebastienros

**Comment by Piedone** [comment]
This is pretty fundamental so I'd like to see it as part of OC.

**Comment by hishamco** [comment]
`OCC.Liquid` will be deprecated then :)

**Comment by Piedone** [comment]
Any news here, Hisham?

**Comment by hishamco** [comment]
It's in my list @Piedone, hope to send a PR ASAP

**Comment by Piedone** [comment]
Great, thanks!
