### ISSUE TITLE
Email format validation error shows incorrectly upon registering

### ISSUE THREAD

**Issue by MZole** [OrchardCMS/OrchardCore#14828]
### Describe the bug
The registration page renders the email format validation error incorrectly.

### To Reproduce
1. Enable the `Users Registration` feature
2. Configure the Users Registration settings to allow registration
3. Try to register with an invalid email format

### Expected behavior
The validation error should describe the error.

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/99020631/62f33c35-70b8-4515-b0d0-79b7840ba6fb)

**Comment by MikeAlhayek** [comment]
Confirmed it's an issue. PR #14832 fixes it

**Comment by BenedekFarkas** [comment]
That was super fast, thanks! :)
