### ISSUE TITLE
middleware must be in execution pipeline before UseRouting to 'Configure(...)' in the application startup code.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14829]
@jtkech maybe this issue due to #14801

But, when I run my app now I get this error

> middleware must be in execution pipeline before UseRouting to 'Configure(...)' in the application startup code.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/f8c881c9-0f9c-4264-80e5-f50b0c9671c6)

I am using `IStartupFilter`

```
services.AddSingleton<IStartupFilter, DetectionStartupFilter>();
```

```
public class DetectionStartupFilter : IStartupFilter
{
    public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
    {
        return app =>
        {
            app.UseDetection();

            next(app);
        };
    }
}
```

The error is thrown here https://github.com/wangkanai/wangkanai/blob/2abff4ffcaf15a024b2c0705c941fb9353f2205d/Hosting/src/DependencyInjection/ApplicationBuilderExtensions.cs#L36

**Comment by MikeAlhayek** [comment]
@jtkech I think `configure(builder);` should be called before `await ConfigurePipelineAsync(builder);` for this to work.

https://github.com/OrchardCMS/OrchardCore/blob/ed991296c486e6774561ba678b880ed021b27298/src/OrchardCore/OrchardCore/Modules/Extensions/ShellPipelineExtensions.cs#L61-L63

**Comment by jtkech** [comment]
Yes, my bad
