### ISSUE TITLE
language switcher in admin not working

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#14834]
With the recent code the language switcher in the admin is not working. It stays on the same language.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/9c2dc67f-ea9a-430f-b740-59af6280ac74)

@hishamco @MikeAlhayek

**Comment by hishamco** [comment]
I will check ...

**Comment by giannik** [comment]
@hishamco  any news. can you repro?

**Comment by hishamco** [comment]
Oops, I forgot. It's on my plate now :)

**Comment by hishamco** [comment]
@giannik I can reproduce the issue, I will work on it then

**Comment by hishamco** [comment]
This happen due the change in the PR #14716

**Comment by MikeAlhayek** [comment]
@hishamco does this fix need to be part of 1.8 release?

**Comment by hishamco** [comment]
believe it or not I need to ping you regarding this one, if there's a patch release `1.8.2` we might need to add this one because it breaks the admin culture picker
