### ISSUE TITLE
How to get physical path of MediaField.Paths,please?

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#14833]
Hi:
How to get physical path of MediaField.Paths,please?

Can you provide PhysicalPath property of IMediaFileStore?

Thanks.

**Comment by effapp** [comment]
![fileinfo](https://github.com/OrchardCMS/OrchardCore/assets/51013754/79e45db1-14d8-49f8-9055-30884dea5ff3)

How to obtain the value of non-public member _fileInfo,please?

**Comment by hishamco** [comment]
I think for security purposes we don't expose the actual path. @errapp why do you need to access the physical file?

**Comment by effapp** [comment]
> I think for security purposes we don't expose the actual path. @errapp why do you need to access the physical file?

Hi hishamco:
      I want to download the file through coding. I'll read bytes from the physical file then return File(path) in the controller.

**Comment by sebastienros** [comment]
`IMediaFileStore` inherits from `IFileStore` which has `GetFileStreamAsync(string path)`. That how you get the content.
