### ISSUE TITLE
Lucene index fails on reset and then rebuild

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#1484]
Repro

- Create an index
- Reset it and then Rebuild it

![luceneexception](https://user-images.githubusercontent.com/8586360/36140919-415a7e98-10a3-11e8-8ad5-135a0caadd6a.png)

**Comment by sebastienros** [comment]
what did you break, it was working perfectly ;)

**Comment by jtkech** [comment]
I don't know :) i will re-try.

**Comment by sebastienros** [comment]
`LuceneIndexManager.Rebuild` and `Reset` can be called concurrently and issue a write lock.
We need to lock these methods, per index, and also add a lock on `ProcessContentItemsAsync`.
We can't use `lock` as there is an async method.
