### ISSUE TITLE
Web defined ContentPart within web defined ContentType does not use liquid template

### ISSUE THREAD

**Issue by bashuss** [OrchardCMS/OrchardCore#1487]
Hi - new here, but testing for a while with orchard core now.
I tried to define a custom ContentType from the Management page (Event).
Inside that ContentType I wanted to have custom ContentPart (MetaImage), which allows to have and Image combined with Image Copyright and Footer text.

Adding the ContentPart to the ContentType offered me the Chance to create the liquid template Event__MetaImage.

I also created a liquid template Content__Event in which referenced the MetaImage by {{ Model.ContentItem.Content.MetaImage }} and by {% display Model.ContentItem.Content.MetaImage %} but None of uses the Event__MetaImage template to render.

How is this supposed to work? Could not find clear info in the documentation.
Debugger tells me, that it does not work because it is a ContentPart and not a ContentType - an ID is missing and so renderer returns nothing (but I am not sure - Debugging is not that easy with all that async stuff.)

Thanks for you help in advance...
Bernd

**Comment by sebastienros** [comment]
`{% display Model.Content.MetaImage %}`

c.f. http://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Templates/README/#liquid

The idea is that in the template of a content item (`Content__Event`) the `Content` property is a list of shapes which have been added by all the drivers. There is a driver that will create a shape for each part of your content item, and their name is usually based on the part name (unless you are giving it a custom name). So here we just ask to render the shape named `MetaImage` from all the shapes in `Model.Content`.

**Comment by bashuss** [comment]
Yes, I have read and tried both, but there is no shape available at Model.Content.MetaImage. The only Thing available is the json representation at Model.ContentItem.Content.MetaImage. 
I guess this is because I configured the ContentPart in the Backend, but did not write and deploy any Code (the Driver you talk about?).
When looking at the backend and at the documentation, I would not have expected, that I need to do more than configure a ContentPart to make it work with templates.

**Comment by jtkech** [comment]
@bashuss  i defined a part `TestPart` (technical name) from the admin ui. Then added to it a text field `Text1` (technical name). Then added this part to the article content type.

This is working.

    Test: {% display Model.Content["TestPart-Text1"] %}

So, when created from the UI you get these kind of names `ThePart-TheField`, `ThePart-OtherField` ... and you don't have a shape for the part but one for each field.

Here i think that `Model.Content.TestPart-Text1` doesn't work in liquid because of the `-` character, so we need to use `["Name"]`. Maybe good that our custom accessor allows `Model.Content.TestPart_Text1`.

**Comment by bashuss** [comment]
Thanks - good to know.

So, which way to go, if  I need to use a template for a ContentPart  (needn't be liquid)? Where can I find an example of a fully coded ContentPart in the VisualStudio-solution?
Or should I even define a ContentField instead? I had a try with this: a DateTimeField/DateField/TimeField - though not happy with that yet. Is this on your plan for the standard fields?

What I plan with "MetaImage" would have a quite complex template (it is supposed to also allow multiple Images with an in-place slide-show, some behaviors for viewing a larger Versions ...). 
I want to use MetaImage for nearly each Image in the Content of the Website. Using the possible way shown by you above, would spread lot's of template Code into other templates. 
I'd like to avoid that, as you will understand for sure.

**Comment by sebastienros** [comment]
Reopening so we can track it's being documented.

**Comment by jtkech** [comment]
@bashuss 

> Where can I find an example of a fully coded ContentPart in the VisualStudio-solution?

In the source code there are many example where a part is implemented through a module, see e.g the `OrchardCore.Body` module as an example for driver / handler / migrations ...

> Or should I even define a ContentField instead? ... Is this on your plan for the standard fields?

Yes, you can make a custom field, see the `OrchardCore.ContentFields` module for samples. For the others i don't know which are planned, maybe those for date and time.

> I want to use MetaImage for nearly each Image in the Content of the Website. Using the possible way shown by you above, would spread lot's of template Code into other templates.
I'd like to avoid that, as you will understand for sure.

Yes i understand, i will think about this.

That said, i re-tried it with a `TestPart1` **created through the ui** and with a `Text1` text field. So here we can't override the part itself but at least, i could override with a db template the rendering of this text field used for the `TestPart1`. I used this template name: `TestPart1__Text1`, and a more specialized one `Article_Detail__TestPart1__Text1` with content and display types.

Note: See the doc, if you use a template file, these types are at the end of the file name.

So, if your complex template just needs the image field infos, you could just override the media field when used with your part (and optionally for a given content type and / or display type).

Something important to know. Normally through `Model.Content` you get shapes on which you can use `{% display %}`. But through `Model.ContentItem.Content` you get json objects, so this will never work.

    {% display Model.ContentItem.Content.SomePart %}

By default, most of the time the shapes are used but e.g see `TheBlogTheme`, some content types are overriden by some templates files in which some parts are rendered by accessing the related json objects, and other parts by using `{% display %}` on the related shapes.

So, to make the following working, in `Content-Article.liquid`, i needed to add.

    {% display Model.Content["TestPart1-Text1"] %}

![templates5](https://user-images.githubusercontent.com/8586360/36364244-397d1ee8-1543-11e8-8626-6cc94733432c.png)

But if your complex template needs infos from other fields, there is no direct way to trigger a template which only have these fields in the model. Although we have helpers to display individual shapes items (which are sub shapes), remove some, change the shape type or add alternates to trigger a given template, we can also add wrappers as we add alternates ...

But there are so many things that i'm sure that there is a way to fit your needs. So finally, not tried but just thinking about to use a custom widget by creating a content type specifying a `Stereotype` of `Widget` and which uses an image and other fields. Then you could add and place your widget (multiple times) when editing any item whose content type has a `FlowPart` (which allows this) ... Then, i think you will have more alternates templates to override for the flow part and / or your custom widget ...

Note: you also have the `BagPart` which does the same kind of things, but in place of adding `Widgets` it allows you to add / place items of different content types, this while editing an item whose content type has a `BagPart`. Here your custom type would not have to be a widget.

**Comment by sebastienros** [comment]
I hope this explains everything:
https://github.com/OrchardCMS/OrchardCore/pull/1968
