### ISSUE TITLE
How do I pass values to Page ContentItem in Orchard CMS,please?

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#14876]
Hi:
   How do I pass values to Page ContentItem in Orchard CMS,please? 
And then How do I receive values in the  Page ContentItem?

Thanks!

**Comment by hishamco** [comment]
The `ContentItem` has `Content` property that you can access the item properties dynamically

**Comment by effapp** [comment]
for example, http redirect task in the workflow redirect url of Page, then How does I pass values to the Page？

**Comment by sebastienros** [comment]
Sorry but it is hard to understand your question. Please try to rephrase it, or provide examples, screenshots, ... anything that could help.

**Comment by effapp** [comment]
> Sorry but it is hard to understand your question. Please try to rephrase it, or provide examples, screenshots, ... anything that could help.

Hi:

1 How do I pass values to ContentItem display page ? 
Example:  Https://localhost:5001/Contents/ContentItem/contentItemId?param=xxxxx

2 How do I receive query string param in the ContentItem display page?

**Comment by sebastienros** [comment]
You need to create a custom view for this content type, see this doc https://docs.orchardcore.net/en/latest/docs/reference/modules/Templates/#content-templates
