### ISSUE TITLE
Error when accessing a blog post belonging to a deleted blog

### ISSUE THREAD

**Issue by ggkoning** [OrchardCMS/OrchardCore#14882]
### To Reproduce
1. Use 'Blog recipe'
2. Create 'a blog'
3. Create 'a blog post in the previous created blog'
4. Delete 'the previous created blog'
5. Go to 'the previous create blog post'
6. See error

### Expected behaviour
The blog post should be entirely deleted or should remain accessible.

### Context
I am using orchard core version 1.7.2 and for the database postgres:latest

### Screenshots
<img width="1309" alt="Screenshot 2023-12-11 at 17 18 32" src="https://github.com/OrchardCMS/OrchardCore/assets/60574784/e4538296-2b20-43e2-83c9-737b905efd2c">

**Comment by MikeAlhayek** [comment]
This issue was fixed in 1.8 previews. I do not recall which PR fixed it. I know I submitted the PR. I also confirmed that the issue does not exists in 1.8-previews.

**Comment by hishamco** [comment]
@ggkoning please recheck on the latest bits

**Comment by ggkoning** [comment]
> @ggkoning please recheck on the latest bits

What do you mean with "latest bits"?

**Comment by hishamco** [comment]
I mean nightly builds
