### ISSUE TITLE
The method PositionWrapper.AddAsync not implemented.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#14896]
I am seeing this in my log file

```
115365:2023-12-14 14:35:45.3067|us|00-52e8d3559962e864e6b802b71da88ff3-e95ca432b6052d61-00||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An exception was thrown attempting to execute the error handler. System.NotImplementedException: The method or operation is not implemented.
115366-   at OrchardCore.DisplayManagement.PositionWrapper.AddAsync(Object item, String position)
115367-   at OrchardCore.DisplayManagement.Theming.ThemeLayout.ExecuteAsync()
```
The methosd AddAsync is indeed not implemented. https://github.com/OrchardCMS/OrchardCore/blob/d6fb9e9994ff7b3e399e3cdc831a3ec47ec5ab58/src/OrchardCore/OrchardCore.DisplayManagement/PositionWrapper.cs#L51

I do not see a note why it should not be implemented. The `AddAsync` method seems to be called by the `ThemeLayout.ExecuteAsync` https://github.com/OrchardCMS/OrchardCore/blob/d6fb9e9994ff7b3e399e3cdc831a3ec47ec5ab58/src/OrchardCore/OrchardCore.DisplayManagement/Theming/ThemeLayout.cs#L27

I think it should be implemented.

**Comment by MikeAlhayek** [comment]
Maybe same implementation as the one we have here

https://github.com/OrchardCMS/OrchardCore/blob/5a26240a0a3421fbb63fcdb44b004583afc4d44d/src/OrchardCore/OrchardCore.DisplayManagement/Views/ShapeViewModel.cs#L11

**Comment by sebastienros** [comment]
I am wondering why a Zone ("Content") is wrapped in a PositionWrapper in the first place. PositionWrapper is done for shapes that don't have a Position property, like "strings". This is why it's not implemented. We need to understand when it get wrapped.

**Comment by ns8482e** [comment]
@MikeAlhayek  `PositionWrapper` is used to wrap pre-rendered items like `IHtmlContent` and `string` and  shape should not be used with `PositionWrapper`.   

`AddAsync` not implemented is intentional and `PositionWrapper` should not contain any items.

**Comment by MikeAlhayek** [comment]
Yeah. Too bad how can't recall how to reproduce the issue. Something was calling that method.

**Comment by sebastienros** [comment]
Please re-open when you can repro.
