### ISSUE TITLE
Unable to load the Orchard Core project

### ISSUE THREAD

**Issue by ArnimSharma007** [OrchardCMS/OrchardCore#14914]
I was unable to load the orchard core project when I install the setup for the first time. I have been facing the below issue
![Screenshot 2023-12-18 182821](https://github.com/OrchardCMS/OrchardCore/assets/122224071/9b2550d7-d57d-403f-a10f-da82454dde6d)

Help me to resolve this issue.

**Comment by rjpowers10** [comment]
What you're seeing is a much broader topic than Orchard Core. This is [NuGet Auditing](https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages) and the reason why it's suddenly appearing now is it rolled out with .NET 8 / Visual Studio 17.8.

**Comment by ArnimSharma007** [comment]
We have tried installing the latest versions of those packages, but the issue still exists. 
The .NET SDK version we are using is 7.0.404 but issue still exists. 
Is there any way you can solve the issue?

**Comment by hishamco** [comment]
OC is moved to `.net 8.0` so previous versions are no longer supported

**Comment by sebastienros** [comment]
You can forcibly ignore these errors by adding `/p:TreatWarningsAsErrors=false` to your command lines.
Or you can add `<NuGetAudit>false</NuGetAudit>` in the main project as explained in the linked documentation.
