### ISSUE TITLE
reuse the exist contentpart 

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#1491]
suppose I have address contentpart.
1---I filled in my address abc in orchard system  today.
2---my roommate in the same address abc need to fill in the address info for his profile tomorrow. 
3---and he do not want to type the redundant address , but want to get the address info which I just filled in.

**Comment by sebastienros** [comment]
There are named parts, to reuse the part definition, but there is nothing to reuse the state of a part. You would need to create a custom part that stores all its instances as independent content items, like we do with widgets.
