### ISSUE TITLE
does orchard core generate sitemap.xml?where?

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#1493]

**Comment by khoshroomahdi** [comment]
like nopcommerce that generate flexable sitemap that I can change it easily and use for webmaster tools.

**Comment by infofromca** [comment]
O1, there was  a community module.
O2, I think no.

**Comment by khoshroomahdi** [comment]
I means O2?

**Comment by sebastienros** [comment]
Let's use this issue as the task to support this.

**Comment by agriffard** [comment]
Sitemaps module added in #4450
