### ISSUE TITLE
Unable to apply OC DataMigration in new environment after upgrade to OC 1.7.0

### ISSUE THREAD

**Issue by jsquared2** [OrchardCMS/OrchardCore#14930]
### Describe the bug

This issue manifests after upgrade from OC 1.5.0 to 1.7.0. When starting the application on a new environment (new database and no site configurations) the `Document` table is created with `Id` column of data type `int` instead of `long`.

This results in a failure to apply OC `DataMigration` involving creation of tables that have a `DocumentId` foreign key column of data type `long` that references the `Document.Id` column.

We can work around this issue by defaulting the `IdentityColumnSize` configuration to `Int64` in `ShellSettingsExtensions.cs`.

This issue is related to #14929 and is manifested when the workaround for that issue is applied.

### To Reproduce
1. Provision new environment (new database, no site configuration)
2. Start application in Visual Studio.
3. See exceptions in Visual Studio indicating failure to apply various OC `DataMigration`.

### Expected behavior
All OC `DataMigration` are applied.

### Screenshots
`

**Comment by sebastienros** [comment]
> This issue manifests after upgrade from OC 1.5.0 to 1.7.0.

I am confused by the repro that states "new environment". Is it migrating a site from 1.5 to 1.7 or creating a new site on 1.7?

**Comment by jsquared2** [comment]
Sorry for the confusion. The scenario is creating a new site on 1.7.

**Comment by sebastienros** [comment]
> Steps to reproduce the behavior:
Provision new environment (new database, no site configuration)
Start application in Visual Studio.
See exceptions in Visual Studio indicating failure to apply various OC DataMigration.


Creating a new site from 1.7 works, unless you can provide more detailed steps. We have functional tests for all the recipes we ship.

**Comment by MikeAlhayek** [comment]
@jsquared2 is this still an issue or can we close this issue?

**Comment by jsquared2** [comment]
> @jsquared2 is this still an issue or can we close this issue?

I think it can be closed for now, thanks.
