### ISSUE TITLE
Default Agency Template has bug in Content__LandingPage

### ISSUE THREAD

**Issue by adopilot** [OrchardCMS/OrchardCore#1494]
On intial install when when user chose Default Agency Template 
There is bug in template for section cleints in Content__LandingPage template
When HREF is crating razor does not use **client.Client.Url.Text** and then Clients click does not work as urls.
Here is part of code of default layout whit is Content__LandingPage

In orginal deployed code razor for creating href does not use **client** object on creating text for hrefs

```
{% if Model.ContentItem.Content.Clients.ContentItems.size > 0 %}
<!-- Clients -->
<section class="py-5">
  <div class="container">
    <div class="row">
      {% for client in Model.ContentItem.Content.Clients.ContentItems %}
      <div class="col-md-3 col-sm-6">
        <a href="{{ client.Client.Url.Text }}">
          <img class="img-fluid d-block mx-auto" src="{{ client.Client.Logo.Paths.first | asset_url }}" alt="">
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}

**Comment by sebastienros** [comment]
Would you mind creating a PR to fix this? Might be tricky as we base64 encode the template in the recipe.

**Comment by adopilot** [comment]
I'll love to try,
But unfortunately I can't find source of Content__LandingPage anyhere in Code
If I fund it all try to make correction

**Comment by adopilot** [comment]
I fund code
OrchardCore/src/OrchardCore.Themes/TheAgencyTheme/Recipes/agency.recipe.json

https://github.com/OrchardCMS/OrchardCore/blob/25ca92f3d8269858676845ea4020c076040cc16e/src/OrchardCore.Themes/TheAgencyTheme/Recipes/agency.recipe.json#L1896

When I do decode using 
https://www.base64encode.org/
I get clear results.
I need to try again encode it and paste back.

Shoud I use UTF-8 output charset when encodin ?

**Comment by jeremycook** [comment]
@adopilot Be sure to use https://www.base64decode.org/ to decode and https://www.base64encode.org/ to encode, or you can use C# like this:

```csharp
string html = Encoding.UTF8.GetString(Convert.FromBase64String("eyUgaWY...3IgJX0="));
string base64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(html));
```
