### ISSUE TITLE
Cannot remove multiple items from rendering in liquid view

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#1495]
Adding two calls to {% display Model.Content | remove_item: "XXX" %} in a template only removes one item.

Steps to reproduce using the blog theme:

1. Add a media field HeaderImage to the Blog content type
1. Edit the Blog and add an image
1. In Content-Blog.liquid, add before the call to remove the body part
{% display Model.Content | remove_item: "Blog-HeaderImage" %}

The blog page should now show the body part content again.

**Comment by sebastienros** [comment]
Should be fixed with this PR ... which will break your world BTW
https://github.com/OrchardCMS/OrchardCore/pull/1433

**Comment by sebastienros** [comment]
It's been merged, please let us know how if the new tags work for you now

**Comment by petedavis** [comment]
Tested and working. Thanks
