### ISSUE TITLE
Inject the IStore.IConfiguration into the DI to make it modifiable

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#14959]
Hi @MikeAlhayek , 

Are there any problems if we inject this configuration into DI? 
I'm trying to implement dynamic indexing https://github.com/sebastienros/yessql/pull/521

So I need to change the `Store.Configuation`

https://github.com/OrchardCMS/OrchardCore/blob/f477647f067ad68701a3ae26e0d41419fa1526db/src/OrchardCore/OrchardCore.Data.YesSql/OrchardCoreBuilderExtensions.cs#L66C33-L66C33

**Comment by hishamco** [comment]
I think this needs to be moved into YesSQL repo

> So I need to change the Store.Configuation

Why?

**Comment by hyzx86** [comment]
Just open up some Configuation for developers to change, 
The current configuration information is a bit closed, 
And if you haven't noticed, Yessql's ORM capabilities are weak, so I'd like to make some enhancements in this feature

**Comment by hyzx86** [comment]
> I think this needs to be moved into YesSQL repo

Yes , here https://github.com/sebastienros/yessql/pull/521


And  I remember that improvement suggestion you were talking about. Why didn't I find...
Because I'm not on the project?

**Comment by MikeAlhayek** [comment]
@hyzx86 if you want to change the configurations of YesSQL in your project, you may do so by configuring [YesSqlOptions](https://github.com/OrchardCMS/OrchardCore/blob/da337435feb9ad8f9351b356426f64c1c636b7d9/src/OrchardCore/OrchardCore.Data.YesSql.Abstractions/YesSqlOptions.cs).

If you need to access the configuration, you can do so by injection an `ISession` and access it like this `_session.Store.Configuration`

If you want to suggest improvements to YesSql, you may file and issue and follow it with PR in the YesSQL repository.

**Comment by hyzx86** [comment]
I saw that type, but it constrained me to configure Yessql freely when testing dynamic indexes.
My solution is based on OC, but it relies on third-party components such as FreeSql (for generating dynamic index types and index data).

Actually going back to the original idea, I just wanted to implement a method like this

```c#
public class PropertyIndexProvider : IndexProvider<Property>
{
    public override void Describe(DescribeContext<ContentItem> context)
    {
       Type myType= getMyType(contentItem);
        context
            .For(myType)// make here support dynamic type
            .Map(property => new PropertyIndex
            {
                Name = property.Name,
                ForRent = property.ForRent,
                IsOccupied = property.IsOccupied,
                Location = property.Location
            });
    }
}
```

The Yessql code is a bit complicated, and I'm trying to figure out the logic

**Comment by hyzx86** [comment]
Use another solution https://github.com/sebastienros/yessql/pull/525
