### ISSUE TITLE
{{ Site.BaseUrl }} is empty in Body part of Email task activity !

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#14986]
### Describe the bug
{{ Site.BaseUrl }} is empty in Body part of Email task activity !

It shoud be not empty!

**Comment by sebastienros** [comment]
Probably the email template is not filled with these property. That's a valid ask and should not be hard to do if you want to try.

**Comment by effapp** [comment]
> Probably the email template is not filled with these property. That's a valid ask and should not be hard to do if you want to try.

I replaced {{ Site.BaseUrl }}  with https://{{ Request.Host }}, It's ok.
