### ISSUE TITLE
Editing a field of a content type causes the display name to change directly to the technical name.

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#14985]
V1.8.0 
![image](https://github.com/OrchardCMS/OrchardCore/assets/16968103/0daabc0d-7f0a-476d-a1d4-e02c5ef7e24a)
![image](https://github.com/OrchardCMS/OrchardCore/assets/16968103/fb0503ca-ec51-4b53-9082-194a4081ef23)

**Comment by giannik** [comment]
can confirm this happens

**Comment by giannik** [comment]
seems it is caused from this pr : 
https://github.com/OrchardCMS/OrchardCore/pull/14571



@MikeAlhayek  maybe a check should be done if displayname is null before explicitly setting the displayname to fieldname ?
