### ISSUE TITLE
Form in a custom widget possible?

### ISSUE THREAD

**Issue by valconi** [OrchardCMS/OrchardCore#1499]
I'm trying to create a module that has a widget that allows an anonymous user to perform CRUD operations on an entity through the front end (not admin). These entities are external to Orchard and accessed via a web api.
I am currently inheriting from ContentPartDisplayDriver which seems to provide functionality to Display on the front end and Edit and Update on the admin area of the site. It does not seem to provide any functionality for a "DisplayUpdate" type method to be called when the front end submits the form.

I have achieved the functionality required by using Controllers / Views in the module, however it is required that this is in a widget / Content Type to allow customisation of which pages this is displayed on and alongside similar CRUD type widgets for different entities.

Is this type of functionality possible in Orchard Core? Should I be inheriting from a different type of Driver or Is it possible to wrap the controller / views as a Widget?
NB - New to Orchard, sorry if the question is in the wrong place or the answer is obvious - Thanks in advance!

**Comment by sebastienros** [comment]
I will just close this issue in favor of the one where we track the design of this feature.
