### ISSUE TITLE
The File Content Definition cannot generate ContentDefinition.json

### ISSUE THREAD

**Issue by giantpenguin** [OrchardCMS/OrchardCore#14994]
### Describe the bug

enable the File Content Definition feature, but file ContentDefinition.json is not generated or be generated with un-usable data likes
`{
  "ContentTypeDefinitionRecords": [],
  "ContentPartDefinitionRecords": [
    {
      "Name": "PublishLaterPart",
      "Settings": {
        "ContentPartSettings": {
          "Attachable": true,
          "Description": "Adds the ability to schedule content items to be published at a given future date and time."
        }
      },
      "ContentPartFieldDefinitionRecords": []
    }
  ],
  "Identifier": "4pkwq8kekdarfx3zxx0nrx39xe"
}`

The OrchardCore.Commerce.Web reference OrchardCore 1.7.0
![image](https://github.com/OrchardCMS/OrchardCore/assets/7245621/1d1a229b-4af6-433b-8c2d-92d2844af4e8)

### To Reproduce
1. Run a new OrchardCore.Commerce.Web for setting up a site with the "Orchard Core Commerce - Development" recipe
2. The setting-up site step success, you can see the start page with some test content
3. Go to the Admin and **enable** the "File Content Definition" feature
4. Go out to view the start page => see exception
5. Check the App_Data/Sites/Default/ContentDefinition.json
6. Go to the Admin and **disable** the "File Content Definition" feature => site will work again

**Comment by hishamco** [comment]
Could you try to reproduce it on an ASP.NET Core app or move this to `OC.Commerce` repo

**Comment by giantpenguin** [comment]
> Could you try to reproduce it on an ASP.NET Core app or move this to `OC.Commerce` repo

Regarding the phrase "reproduce it on an ASP.NET Core app", I will try later to see any difference.

**Comment by giantpenguin** [comment]
Clone this to OC.Commerce repo
