### ISSUE TITLE
htmlbody display problem

### ISSUE THREAD

**Issue by HoHeo** [OrchardCMS/OrchardCore#15009]
After I downloaded the 1.8 version source code and installed the blog template, the page did not display the content in the htmlbody after replacing the markdown in the blogpost content item with htmlbody.

**Comment by MikeAlhayek** [comment]
@HoHeo can you please update the issue with the following so we can help you?

### To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

### Expected behavior
A clear and concise description of what you expected to happen.
