### ISSUE TITLE
change admin font base on locolaization

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#1502]
fro example local font is not suitable for rtl langaugaes special Arabic or Persian. and we have many beautiful font that i can suggest it for example for Arabic vazir font is a nice choice.

**Comment by khoshroomahdi** [comment]
it would be customizable in admin area

**Comment by sebastienros** [comment]
We do not have support for RTL right now, we do in Orchard 1 and we know what we need to do though.
Our technique is to inject the language and RTL flag in the `<html>` tag, which let's us (for the admin) or you (on the front end) to use different styles based on this class.

**Comment by khoshroomahdi** [comment]
Thanks. it was just an idea to make better cms.
