### ISSUE TITLE
"This branch is out-of-date with the base branch" message under PRs

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#15031]
Today I noticed that the PRs show the following message **This branch is out-of-date with the base branch** is this something because of the latest patch release or is there something else happening?!!

/cc @MikeAlhayek @Piedone @sebastienros

**Comment by MikeAlhayek** [comment]
I think @sebastienros changed the repo settings. I am guessing he enabled "Requires branches to be up to date before merging" settings yesterday.

**Comment by Piedone** [comment]
Yep, that's it. I didn't change it. It's useful though (and as a core contributor you can bypass it too).

**Comment by MikeAlhayek** [comment]
@sebastienros this option is pretty annoying :). Can we disable it?

It would be nice to have an optional button that would allow us to rebase a PR from UI. But it is annoying that you can't merge a PR without having to rebase even when there is no conflicts. Like if you want to merge PR's back to back. Currently, if you have 2 PRs that you want to merge, you have to merge the first one, rebase the second, then merge the second.

**Comment by Piedone** [comment]
You can bypass it if you deem the merge safe: 
![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/16a04c2a-f10c-49ef-98d9-261495d61def)

**Comment by MikeAlhayek** [comment]
@Piedone you must have more access than I do on the project. I Can't by pass it. also it seems that I am only able to update my own branches not others.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/e7c63e2f-c36a-4c64-80ad-79ee1fd7c1ca)

**Comment by Piedone** [comment]
Ah, I see, Hmm, this is dumb like this.

I just learned that there is an "Always suggest updating pull request branches" config that displays this button even without branch protection. So, I enabled that and disabled this from the branch protection rule.

So now you have this:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/578a5862-fdc7-4896-bd99-75187f7b1027)

I think we have the crisis averted, but @sebastienros feel free to reopen and argue, but it seems this just annoys those people who do the most work.
