### ISSUE TITLE
Search Form does not show up when using Azure Search AI

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#15033]
There is a bug in the `TheBlogTheme` theme that I have no explanation for as of now. If you enable `Azure Search AI` and `Search` features, the search form does NOT show up. 

To workaround this issue, you have to enabled either `Lucene` or `Elasticsearch` features for the search bar to show up. 

When the request is made to `/search` endpoint, the line is reached https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Search/Controllers/SearchController.cs#L91

which returns the Search.cshtml view https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Search/Views/Search/Search.cshtml

That view would render `Search__List` shape, which then renders `Search__Form` and `Search__Results` shapes. What could be causing this views not to render?

Everything works using other themes like TheDefault theme which tells me that there is something about the blog theme that isn't working as it should.

![azure-cognitive-search-4](https://github.com/OrchardCMS/OrchardCore/assets/24724371/f934c216-8e5e-4519-8c67-f66f9070c90e)

@Skrypt Do you have any idea why this could be happening?

**Comment by Skrypt** [comment]
Shapes not instanciated or it throws a NRE somewhere. Would need to debug it.

**Comment by MikeAlhayek** [comment]
@Skrypt shapes are instantiated from the Search module not the Search provider modules. Also, there is not error in the logs. The fact that everything works as expected in TheDefault theme tells me that the code is doing what it suppose. I am just puzzled with why the BlogTheme experience this behavior. TheBlogTheme is created using Liquid where as TheDefaultTheme is using Razor. I am not sure if this is an issue. I do not see any special liquid helpers that depends on the search providers either.

**Comment by MikeAlhayek** [comment]
I figure out the issue finally. 

Each provider was registering this independently

```
services.Configure<TemplateOptions>(o =>
{
    o.MemberAccessStrategy.Register<SearchIndexViewModel>();
    o.MemberAccessStrategy.Register<SearchFormViewModel>();
    o.MemberAccessStrategy.Register<SearchResultsViewModel>();
});
```

**Comment by Skrypt** [comment]
Yes these are ShapeViewModels ... strongly typed ones.
