### ISSUE TITLE
Run Orchard Core Website in sub folder?

### ISSUE THREAD

**Issue by hongbangsoft** [OrchardCMS/OrchardCore#15030]
I can run the website fine with the localhost.
But when I to move it to a subdirectory like mysite and I try to run it with url localhost/mysite, I get a 500 error.
How can I handle this issue?

**Comment by hishamco** [comment]
Of course, you will get an error because you are not in the root, in case you want to use `localhost/mysite` you need to create a tenant from within the admin

**Comment by sebastienros** [comment]
Or use IIS which supports virtual directories.
