### ISSUE TITLE
Forms and Workflows

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1505]
As a user, I want to be able to add forms to a page and then handle form submissions in a variety of ways. Examples are:

- Contact form -> When submitted, a workflow will send an email.
- Suggestion Form -> When submitted, a workflow will create a Suggestion content item and send an email to the site moderator.
- Newsletter Signup form -> When submitted, a workflow will register the provided email address with MailChimp.
- Poll -> When submitted, a workflow will store the answers in Google Survey.
- Signup form -> When submitted, a workflow will create a new User.
- Signin form -> When submitted, a workflow will validate provided credentials and sign in the user.

The above scenarios are already possible to implement today, since we can add HTML / Liquid widgets to a given page that renders the <FORM> element which could point to a Workflow HTTP endpoint URL.

However, to make creating custom forms and handling their submissions easier, we should do the following things:

- Add various form element widgets to the Widgets module (perhaps as part of a separate feature) such as **input**, **select** and **submit**.
- Add a form element as well as a Liquid tag that renders an anti-forgery token.
- Add a Workflows activity that validates the posted anti-forgery token.
- Add a Workflows activity or JS function that can add content items to a List content item.

**Comment by valconi** [comment]
I think this may share some similarities with a question I posted #1499 
When you say:
> The above scenarios are already possible to implement today, since we can add HTML / Liquid widgets to a given page that renders the element which could point to a Workflow HTTP endpoint URL.

Are there any examples of this in the repository? Are Workflows available? Thanks!

**Comment by sfmskywalker** [comment]
Thanks, that's definitely related.

There are no examples right now, but I'll be working on that as part of this issue. Workflows is not yet merged into the dev branch, but should be soon. Once it's available, you could expose a workflow as an HTTP endpoint in the form of a URL and have a <form> tag with an action attribute pointing to that URL. All the posted fields will be available to the workflow, which means you can do whatever you want with it.

However, that's all a bit raw in its current shape and form. The goal of this issue is to add a few components in the form of widgets, JS functions and workflow activities to make creating custom forms and handling their submissions more smoothly.
