### ISSUE TITLE
Disable Wiki

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15061]
### Is your feature request related to a problem? Please describe.
[The wiki](https://github.com/OrchardCMS/OrchardCore/wiki) had its place in the very beginning, but now it's outdated and unnecessary due to [the docs site](https://docs.orchardcore.net/en/latest/). 

### Describe the solution you'd like
Let's disable the feature on GitHub and thus remove the Wiki tab. The Roadmap there is outdated too and [issue milestones](https://github.com/OrchardCMS/OrchardCore/milestones) serve this purpose better anyway.

### Describe alternatives you've considered
Updating it, but I don't really see the point.

**Comment by MikeAlhayek** [comment]
Agreed. The fact we have doc page, we should not need to use Wiki. Once you disable it, be sure to remove the mention of it on the project readme file

**Comment by agriffard** [comment]
Wiki disabled in the Settings.

**Comment by Piedone** [comment]
Thanks!
