### ISSUE TITLE
Automation to notify PR authors that their PR has a merge conflict

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15060]
### Is your feature request related to a problem? Please describe.
When a PR has merge conflicts, the reviewer has to point that out if the author doesn't check back. Otherwise, the author wouldn't know that since they opened it, they PR got a merge conflict.

### Describe the solution you'd like
Automate this. Similar to what [Lombiq's `validate-pull-request`](https://github.com/Lombiq/GitHub-Actions/blob/dev/Docs/Workflows/Productivity/ValidatePullRequest.md) workflows does (but with `pull_request_target`), we could use [`eps1lon/actions-label-merge-conflict`](https://github.com/eps1lon/actions-label-merge-conflict) to label conflicting PRs, and add a comment under them. See [example](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/check-merge-conflict/action.yml#L13).

### Describe alternatives you've considered
Perhaps there are other usable automation for this but the mentioned action works well.

**Comment by hishamco** [comment]
Go for it
