### ISSUE TITLE
Create custom liquid tag to update a pager shape

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1506]
`{% set_properties Model.Pager previous_text: previousText, next_text: nextText, next_text: nextText, previous_class: previousClass, next_class: nextClass %} previous_class: previousClass, next_class: nextClass %}`

Should be a specific tag for pagers.
And remove `set_properties`.

**Comment by agriffard** [comment]
Done in the latest Liquid branch by @jtkech : `shape_pager`

**Comment by agriffard** [comment]
@jtkech : I updated my application with the latest version of OC and changed my liquid templates in admin.
The only thing I don't manage to do anymore is to add ItemClasses to a pager in a ListPart template :
```
{% assign itemClasses = "page-item" | split: " " %}
{% shape_pager Model.Pager previous_text: previousText, next_text: nextText, previous_class: previousClass, next_class: nextClass, item_classes: itemClasses %}
``` 
The ShapePagerTag doesn't have this property: 
`private static readonly string[] _properties = { "PreviousText", "NextText", "PreviousClass", "NextClass" };`

**Comment by jtkech** [comment]
@agriffard yes, i only used specific properties of the pager.

So you may have to use before these tags `shape_clear_classes` and / or `shape_add_classes`.

**Comment by agriffard** [comment]
I use `shape_add_classes` but to add a `pagination` class.
How can I add 'page-item' on each item?

**Comment by agriffard** [comment]
I forgot to mention that this doesn't work Blog-ListPart.liquid :
`{{ shape_display Model.Pager | shape_render }}`
I ahad to replace it by:
`{{ Model.Pager | shape_render }}`

**Comment by jtkech** [comment]
I did a patch which removes `shape_display`.
I will take a look for classes.

**Comment by jtkech** [comment]
Okay there are not shape classes but item classes.
I added this property in my current branch and tried it.
Maybe i would need to do a separate PR.
