### ISSUE TITLE
Possibility of disabling Redis SSL/TLS certificate validation

### ISSUE THREAD

**Issue by ovekaaven** [OrchardCMS/OrchardCore#15077]
We'd like to use "Heroku Data for Redis", which offers Redis connections with and without TLS. However, the server certificate is self-signed and the Heroku documentation states you have to disable certificate verification. This can't be done with the connection string, according to StackOverflow answers it can only be done by changing the StackExchange.Redis connection options after parsing but before connecting. But I can't find a way to do that in Orchard Core. Could it be done, or are we stuck with unencrypted Redis connections?

**Comment by MikeAlhayek** [comment]
@ovekaaven you can submit a PR with a new configuration option "DisableSSLCertificate" which disables the validation after the parsing.

**Comment by ovekaaven** [comment]
Ok, but if I'm supposed to write this myself it might take a while, because in order to test it I'd first have to upgrade our deployment to the newest version of Orchard Core, which probably won't happen right away. But once that happens, I can look at it if nobody else has by then, I suppose.

**Comment by ovekaaven** [comment]
I suppose you're right. I've never before tried running Orchard Core directly from its own source tree instead of from a separate project, but it turns out it's not that hard if you choose to build and run the OrchardCore.Cms.Web project within the source directory. Pull request created, hopefully it's OK.
