### ISSUE TITLE
Enabling Amazon S3 storage provider without configuration causes exception

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/OrchardCore#15079]
### Describe the bug

As the title says, the reason to change this is UX. Other, similar external providers give you a warning on their settings page about missing configuration instead.

### To Reproduce
1. Run OC on the latest main commit (8852c986b95464f5070a09e7cfdf9740d318a2f7 in my case).
2. Set up the site with any recipe.
3. Enable the Amazon Media Storage feature.
4. Go to Configuration -> Media -> Amazon S3 Options

### Expected behavior
I should see the configuration screen without errors, but with a notification that warns me about missing configuration.

### Actual behavior
Instead, this error is thrown:
```
ArgumentNullException: Value cannot be null. (Parameter 'buffer')
Parlot.Scanner..ctor(string buffer)
Fluid.Parser.FluidParseContext..ctor(string text)
Fluid.FluidParserExtensions.Parse(FluidParser parser, string template)
OrchardCore.Media.AmazonS3.AwsStorageOptionsConfiguration.ParseBucketName(AwsStorageOptions options, TemplateContext templateContext) in AwsStorageOptionsConfiguration.cs
-
    private void ParseBucketName(AwsStorageOptions options, TemplateContext templateContext)
    {
        // Use Fluid directly as this is transient and cannot invoke _liquidTemplateManager.
        try
        {
            var template = _fluidParser.Parse(options.BucketName);
            options.BucketName = template
                .Render(templateContext, NullEncoder.Default)
                .Replace("\r", string.Empty)
                .Replace("\n", string.Empty)
                .Trim();
```

**Comment by hishamco** [comment]
@neglectedvalue could you please check this while you are the one who worked on this module?

**Comment by neglectedvalue** [comment]
Sure, I'll take a look, sorry for a long reply(caught a flu and was away from PC).

**Comment by hishamco** [comment]
I see, hope you recover ASAP
