### ISSUE TITLE
Add an explicit deny permission

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#15082]
### Is your feature request related to a problem? Please describe.
In my site I have two roles: anonymous and authenticated. I have many content types, and the anonymous role should be able to view all of them except one that requires the user to be authenticated.

### Describe the solution you'd like
A way deny anonymous access to that content type. Basically, it would mean adding a new checkbox to the roles page so I could allow or deny.

### Describe alternatives you've considered
The workaround is to uncheck "view all content" for the anonymous role, then check "view {content_type} by others" for all other content types. This is a bit of a pain, and you have to remember to check it for new content types as they are added.

I'm sure this wouldn't be trivial to implement, but I thought I'd share one of (fairly mild) my pain points.

**Comment by MikeAlhayek** [comment]
@rjpowers10 why can't you specify which roles you want to allow in the roles recipe?

In theory the following will not give the use the "view all content" permission by default, instead will only grant them `view {content_type} by others`.

```
{
    "name": "roles",
    "Roles": [
        {
            "Name": "anonymous ",
            "Permissions": [ "view {content_type} by others"]
        }
    ]
}
```

**Comment by rjpowers10** [comment]
@MikeAlhayek that's a perfectly fine solution and it does work. I was also a little unclear in my original post. I don't really have to uncheck "view all content" because you are correct it won't be checked by default (unless specified in the recipe).

The problem with the recipe approach is I have to add _all_ my other content types into the list, of which I have many. It would be a lot simpler if I could just deny the one. I also have to remember to maintain the recipe as new content types are added.

Again, this is a rather mild complaint. More of a QoL thing. But I understand it could be a lot of effort to implement.

**Comment by MikeAlhayek** [comment]
>> "view all content" because you are correct it won't be checked by default (unless specified in the recipe).

correction, it will be checked by default **unless** you explicitly specify at least 1 permission.

If you want to contribute here, I think it would be nice to add an option to control the behavior of the roles recipe.

```
{
    "name": "roles",
    "strategy":"replace", // 'replace' would be the default. But you can also specify 'merge' or 'remove'
    "Roles": [
        {
            "Name": "Anonymous",
            "Permissions": [ "view {content_type} by others"]
        }
    ]
}
```

The `strategy` will give us behavior control on what to do with the defined permission with `replace` being the default since it is the default strategy we use today. 

    However, I don't think this will solve your problem. I think the best approach to list app the permissions you want. Additionally, you may specify your own custom authorization-handler that would change the default behavior. Take a look how the `ContentTypeAuthorizationHandler` is implemented and you should be able to define your own logic and accomplish what you want.

**Comment by MikeAlhayek** [comment]
@rjpowers10 is this still needed or can we close it?
