### ISSUE TITLE
Lock Admin Account

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#15105]
I came across a strange issue when I was trying to log in to OC web app, accidentally I tried many times with the wrong password, then the account was locked.

While the user is an admin we need a better experience to recover the password

**Comment by MikeAlhayek** [comment]
if you enabled the reset password feature, you can reset the admin password. The default identity implementation locks the account after X (I think 5 within 10 mins by default) amount of invalid attempts. These type of locks are temporary and will be auto unlocked

**Comment by hishamco** [comment]
> if you enabled the reset password feature, you can reset the admin password.

Right

> These type of locks are temporary and will be auto unlocked

I thought that I needed to enable it myself, I will close this if the account has been unlocked :)

**Comment by MikeAlhayek** [comment]
@hishamco of your account auto unlocked, please close this issue.
