### ISSUE TITLE
Update GraphQL for .NET to latest

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15104]
### Is your feature request related to a problem? Please describe.
[GraphQL for .NET](https://github.com/graphql-dotnet/graphql-dotnet) is currently on v7.7.2 while we use 4.8.0. While this is not hugely old (it [was released in March 2022](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/4.8.0)) but it still is, and we're too much behind.

### Describe the solution you'd like
Upgrade to the latest version. This will be a pain I'd guess. Perhaps we could ask somebody from the GraphQL for .NET team to help?

### Describe alternatives you've considered
I really don't know of any.

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/12295.

**Comment by hishamco** [comment]
I already have a PR #13255 but I might need help there because there're many breaking changes

@hyzx86 let me know if you can help me in related PR

**Comment by hyzx86** [comment]
@hishamco  Wow, I just started researching Graphql.Relay recently

But its version relies on Graphql 7.x, so I tried to downgrade graphql.relay to an earlier version.

**Comment by hyzx86** [comment]
> @hyzx86 let me know if you can help me in the related PR

Let me have a look first.

**Comment by hyzx86** [comment]
Done at https://github.com/OrchardCMS/OrchardCore/pull/15129
it's ready to review

**Comment by ShaneCourtrille** [comment]
@sebastienros Do you expect this to be included in 1.9?  We're going to start working on performance issues and this is a requirement for that so trying to decide if we just pull this in by itself or not.

**Comment by sebastienros** [comment]
It's merged, so this will be part of the next release, 1.9

**Comment by sebastienros** [comment]
You can already use the main branch of the nightly feed to work with it
