### ISSUE TITLE
SectionDisplayDriver should override the HtmlPrefix with the TSectionName

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#15116]
Currently the `SectionDisplayDriver` uses `TSection` for it's `Entity` property name :
https://github.com/OrchardCMS/OrchardCore/blob/ae2f9525e29f533b1a993d7279c9a45d06ac5198/src/OrchardCore/OrchardCore.DisplayManagement/Entities/SectionDisplayDriver.cs#L28

However, it does not override the default `Prefix` value, which remains as per the base class `Prefix = typeof(TModel).Name;`

This creates ambiguity on the field names, where it is easily possible to have multiple keys of the same name, if classes used on `IEntity` have the same property names.

e.g.

```
public record PropertyA(bool Allow);
public record PropertyB(bool Allow);
```

`PropertyA` and `PropertyB` will be stored seperately in the properties dictionary correctly, but the views will create a form post with identical names.

**Comment by MikeAlhayek** [comment]
Agreed. Specially if you want to inject multiple things into the shape like. I had to implement a wrong around for this on couple places already. Here is one https://github.com/OrchardCMS/OrchardCore/blob/43111680a4e7baa42703fbe90632e68db4e6a257/src/OrchardCore.Modules/OrchardCore.Search.AzureAI/Drivers/AzureAISearchSettingsDisplayDriver.cs#L109

It may be also best to use both the TEntiry_TSecrion. Like if we are using site setting it should be ISite_SiteSettings.  It is on my to do, but a PR from you would be nice.
