### ISSUE TITLE
ISiteThemeService GetSiteThemeAsync() returns the front-end theme on the Admin page

### ISSUE THREAD

**Issue by Psichorex** [OrchardCMS/OrchardCore#15150]
### Describe the bug
Injecting `ISiteThemeService siteThemeService` or `IThemeManager` and calling either `GetSiteThemeAsync` or `GetThemeAsync()` will return the Front-end theme instead of the admin theme.

I want to determine inside of a Middlaware whether the Current Theme is using Lombiq.BaseTheme as its BaseTheme.
If yes I want to remove bootstrap resources.

The problem here is now that I can't determine if I am on the admin page because the above described services will not return TheAdminTheme but the frontend theme only.

So my problem is that I want to get the CurrentTheme that is now being displayed and if that is the TheAdminTheme I don't want to remove bootstrap as it will destroy the admin page.
### To Reproduce
1. Create something that will call either `IThemeManager GetThemeAsync()` or `ISiteThemeService GetSiteThemeAsync()`
2. Navigate to the Admin page and place a breakpoint on the call
3. Refresh the admin page to hit the breakpoint
4. You should see in the IDE locals that the Theme returned is the Front-end theme in my case TheBlogTheme

### Expected behavior
It should return TheAdminTheme

### Screenshots
Screenshots are made from a fresh clone of the OrchardCMS repository so it is not my local project.
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/0c5f3f2a-ae43-4b17-a507-1781c0078e5d)
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/18d4fd6c-de37-4b68-a869-0e23bb5f5bf8)

**Comment by hishamco** [comment]
Please use `IAdminThemeService` instead

**Comment by Psichorex** [comment]
> Please use `IAdminThemeService` instead

I checked `IAdminThemeService` and I don't see a method in it for my usecase.
So sorry for the lack of information I am adding this part to the issue description:

I want to determine inside of a Middlaware whether the Current Theme is using Lombiq.BaseTheme as its BaseTheme.
If yes I want to remove bootstrap resources.

The problem here is now that I can't determine if I am on the admin page because the above described services will not return `TheAdminTheme` but the frontend theme only.

So my problem is that I want to get the CurrentTheme that is now being displayed and if that is the `TheAdminTheme` I don't want to remove bootstrap as it will destroy the admin page.

So after debugging into `IAdminThemeService` it will give me the `IExtensionInfo` but I don't see the way it could determine whether that is being actually displayed.

**Comment by hishamco** [comment]
Use `ISiteThemeService` to check the site theme or `IAdminThemeService` if you want to check the current admin theme

**Comment by Piedone** [comment]
`ISiteThemeService` is for the site, i.e. not admin, theme. However, `IThemeManager.GetThemeAsync()` should return the current theme regardless, i.e. the site theme (most possibly) on the frontend, and the admin theme on the dashboard. I just checked with the latest source and this is what happens too.

However, I believe we tried that during our debugging session @Psichorex and it also always returned the site theme, even when on the dashboard. Please check with the latest source though.

**Comment by Psichorex** [comment]
This is what happens when I am making a call with `IThemeManager.GetThemeAsync()` in the latest source:
Admin becomes totally unusable
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/468abbf8-a611-4971-9a55-64470c529e4a)

**Comment by Piedone** [comment]
Please tell how it works for you as mentioned above.

**Comment by Psichorex** [comment]
Yes I can now reassure that if I use `IThemeManager.GetThemeAsync()` anywere in the code in the latest source the following page pops up when I am trying to access the admin:
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/58390ad7-9911-4ea0-a317-180b6fb04da2)

**Comment by ns8482e** [comment]
That's because middleware runs before filters.

Creating MVC action filter instead of middleware will solve your problem

**Comment by Psichorex** [comment]
As per @ns8482e said I couldn't use `IThemeManager` in a Middleware.
Also our problem rooted from OC moving out bootstrap from the `TheAdmin.css` we solved that locally.
