### ISSUE TITLE
Keep `yessql.db` as the fallback name for sqlite for backward compatability

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#15154]
@hishamco PR #7446 introduced a breaking change. All of my local tenants that use Sqlite are failing because they are expecting a file called `yessql.db` and not the app is looking for `OrchardCore.db`.

Here is what we should do. When creating new sites that use Sqllite, save `"DatabaseName": "OrchardCore.db",` to the shellSettings. If the shell-settings does not have `DatabaseName` value, then use `yessql.db`. This way we keep it backward compatible and only change it for new tenants. Ping me when you get this fix

**Comment by hishamco** [comment]
I mentioned that in the breaking changes section, I will fix that soon

**Comment by hishamco** [comment]
> Here is what we should do. When creating new sites that use Sqllite, save "DatabaseName": "OrchardCore.db", to the shellSettings. If the shell-settings does not have DatabaseName value, then use yessql.db. This way we keep it backward compatible and only change it for new tenants. Ping me when you get this fix

Let me check ..

**Comment by hishamco** [comment]
> Here is what we should do. When creating new sites that use Sqllite, save "DatabaseName": "OrchardCore.db", to the shellSettings.

This is already done

**Comment by MikeAlhayek** [comment]
@hishamco I don't think so. Where do you store that value when a new tenant is setup? This should be done in the SetupService. You'll need somethis like 

```
shellSettings["DatabaseName"] = context.Properties.TryGetValue(SetupConstants.DatabaseName, out var dbName) ? dbName?.ToString() : null;
```

on line 162.


Look where `SetupConstants.DatabaseTablePrefix` is used, and you'll likely need to add `SetupConstants.DatabaseName` there too.


I think you'll need to remove the default value from `SqliteOptions DatabaseName` then in the `SqliteHelper` you can check if the app settings contains `DatabaseName` and use it otherwise use `yessql`

**Comment by hishamco** [comment]
>  I don't think so.

You can create a new tenant :)

**Comment by MikeAlhayek** [comment]
@hishamco I just did as you can see the databasename is not written to the Shellsettings of the tenants.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/2ecfa9dd-9c6e-4116-8205-7457d781bc1b)

**Comment by hishamco** [comment]
Ya, even before the my PR, please refer to the related PR

**Comment by MikeAlhayek** [comment]
correct. So what I am suggestion is that for new tenants, you shoud write entry in that file "DatabaseName": "orchardcore.db". If that property exists, then we use the name listed in the settings, otherwise, we use `yessql.db`.

**Comment by Piedone** [comment]
The original change was reverted in https://github.com/OrchardCMS/OrchardCore/commit/ea5ada38b31c2e344fbf38639983d3c93aec5017 so this is not applicable anymore.
