### ISSUE TITLE
    Invalid login attempt.

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#1516]
after setup orchard core i have this error and i can't login anyway. i try in different way based on agency or blog or saas.

![untitled](https://user-images.githubusercontent.com/20259070/36564638-35671ef6-1833-11e8-902b-8f5e86210b25.png)

**Comment by sfmskywalker** [comment]
Did you try email address?

**Comment by jtkech** [comment]
Go to the browser dev tools and remove any cookies. you may have one related to an https connection.

**Comment by khoshroomahdi** [comment]
@sfmskywalker yes i tried by email and user name.

**Comment by sebastienros** [comment]
Use HTTPS, you have an old cookie that was created under it and now you are using HTTPS. OR clear your https cookies for this domain

**Comment by khoshroomahdi** [comment]
@sebastienros i clear all cookies but doesn't work
