### ISSUE TITLE
wrong placement is applied

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#15166]
Using **OrchardCore.Placement** module, I've created a placement and then remove it, but I'm still getting **some** placement applied. Looks like old cached value. I would expect the original value from placement.json file.

Steps to reproduce:
- create new content type **PlacementTest**,
- go to content item editor of that type and check if default placement is applied, by default I mean this one from **OrchardCore.Contents** placement.json, 
- create new placement via AdminUI with shape type **Content_PublishButton**:
```
{
  "place": "-",
  "displayType": "Edit",
  "contentType": [ "PlacementTest" ]
}
```
- check if it is applied correctly, save button shouldn't be visible,
- remove previously created placement,
- check if is not applied anymore, save button should be visible again.

/cc: @sebastienros @ns8482e

**Comment by microposmp** [comment]
I've tried to figure out the reason for this issue and found some other side effects. When the placement for the content type "PlacementTest" in the example above was resolved once it would resolve the placement hiding the publish button for all content types.
