### ISSUE TITLE
How to do HttpPost to custom module controller

### ISSUE THREAD

**Issue by adopilot** [OrchardCMS/OrchardCore#1517]
I am trying to make custom module with CRUD operations.
What I did is:
Download module from samples.
Extract module in OrchardCore.Module folder
Enable it on admin portal.

All changes I did is 
Installed  entity framework core and added content in startup
```
public override void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<Module1.Models.orc1Context>(
                options => options.UseSqlServer("Server =connstring ")
                );
        }
```
I did create controller incinerating  `: Controller`

When I do HttpGet my controller works perfectly.
I am able to get data from db context, I am able to return views, json and so on.
My param mappings works ok  for Get requests.

But when I try to **HttpPost** or **HttpPut** to that same controller 
I do always get  400 Bad Request
Even when I intended miss route I get 400 Bad Request.

Is there any clue what I need to do to my module accepts HttpPosts ?

All from debug i get is in output window of vs something like this.

`Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2018-02-22T22:42:19.0432798Z","tags":{"ai.operation.name":"POST Home/ContactForm [area]","ai.operation.id":"c71e1405-4057075ea49aba97","ai.location.ip":"::1","ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"adinLaptop","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.internal.nodeName":"adinLaptop"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|c71e1405-4057075ea49aba97.","name":"POST Home/ContactForm [area]","duration":"00:00:00.0069833","success":false,"responseCode":"400","url":"http://localhost:2918/Module1/Home/ContactForm","properties":{"AspNetCoreEnvironment":"Development","httpMethod":"POST","DeveloperMode":"true"}}}}
`

**Comment by awyl** [comment]
I had similar experience. Do you have the anti-forgery token in the http post?

**Comment by adopilot** [comment]
@awyl I did not try adding anti-forgery. I am going to try add it and post.  I'll let you know results

**Comment by sebastienros** [comment]
By default all POST requests will validate this token in Orchard, you will need to call `@Html.AntiforgeryToken` inside the form in the razor template. Unless you are using the <form> tag helper which does it automatically.
