### ISSUE TITLE
Sitemap.xml uses invalid datetime separator

### ISSUE THREAD

**Issue by JMalaprade** [OrchardCMS/OrchardCore#15172]
Noticed that sitemap.xml returns "invalid date" errors in a Google Console's sitemap verification tool. I believe this happens because the sitemap uses a wrong datetime separator: dots instead of colons.

Example of the current situation:
`<url>
<loc>
https://www.domain.fi/somehting
</loc>
<lastmod>2023-11-27T06.07.36+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>`

That should be (YYYY-MM-DDThh:mm:ss.sTZD):
`<url>
<loc>
https://www.domain.fi/somehting
</loc>
<lastmod>2023-11-27T06:07:36+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>`

**Comment by MikeAlhayek** [comment]
@JMalaprade what version are you using?

Looking at the code briefly, seems that we are using the correct format 

https://github.com/OrchardCMS/OrchardCore/blob/b23ec3e0f87fc7d97a8429d0726f9723f3c8d04f/src/OrchardCore.Modules/OrchardCore.Contents/Sitemaps/ContentTypesSitemapSourceBuilder.cs#L165

and 

https://github.com/OrchardCMS/OrchardCore/blob/b23ec3e0f87fc7d97a8429d0726f9723f3c8d04f/src/OrchardCore.Modules/OrchardCore.Sitemaps/Builders/CustomPathSitemapSourceBuilder.cs#L72

**Comment by sebastienros** [comment]
@MikeAlhayek the first sample you point to is missing CultureInfo.InvariantCulture. Without it it will use the local culture, which is the issue that is described.

**Comment by MikeAlhayek** [comment]
uh! I missed that. good catch
