### ISSUE TITLE
[OC 1.8.2] Slow saving of content item

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#15171]
After update to OC 1.8.2 from OC 1.6 (also from 1.7). Saving of content item became slower than before.

For same content item, it takes ~5s to save on OC 1.6. Saving on OC 1.8 takes ~15s. It is 3-5 times slower even on small content items without widgets.

I tried to search for feature that could do this, but without luck. Maybe memory leaks fix can have something to do with this?

**Comment by MikeKry** [comment]
It seems it might be related to media - library is very slow, maybe it has something in common.

**Comment by MikeAlhayek** [comment]
@MikeKry can you please try to use the Mini profiler feature to see what is actually taking longer than usual to process? 

Also, you may want to try a simple site using blog recipe and see if you get the same slow behavior just to ensure it is OC and not anything specific to your project?

**Comment by MikeKry** [comment]
@MikeAlhayek 

I tried mini profiler, it seems there are multiple duplicate queries when saving items. I tried also to disable all project specific modules, but it has no effect.

Here is export from mini profiler after saving content item that is basically empty.
[OrchardCore.Contents_Admin_Edit (6107.8 ms) - Profiling Results.pdf](https://github.com/OrchardCMS/OrchardCore/files/14096471/OrchardCore.Contents_Admin_Edit.6107.8.ms.-.Profiling.Results.pdf)

**Comment by MikeKry** [comment]
@MikeAlhayek 

I tried to compare it to older project, most queries look exactly the same. But all of them are slower. 

Deletions from indexes 22 ms vs 4164ms. Updates 1-5 ms vs 30-50 ms.

So it seems that database is the problem. But both projects are running on same server, so it might be something in yessql? You did not notice this problem yet?

**Comment by MikeKry** [comment]
@Skrypt 

Ok, I will try to do some more debugging. So far I have found out that it only happens when using MSSQL. I tried SQLite and it works ok.

**Comment by MikeKry** [comment]
Here are results for MSSQL: 
[MSSQL_OrchardCore.Contents_Admin_Edit (11368.77 ms) - Profiling Results.pdf](https://github.com/OrchardCMS/OrchardCore/files/14101706/MSSQL_OrchardCore.Contents_Admin_Edit.11368.77.ms.-.Profiling.Results.pdf)

and for SQLITE:
[SQLITE_OrchardCore.Contents_Admin_Edit (4426.16 ms) - Profiling Results.pdf](https://github.com/OrchardCMS/OrchardCore/files/14101709/SQLITE_OrchardCore.Contents_Admin_Edit.4426.16.ms.-.Profiling.Results.pdf)


Same page, same setup - this time I run on **main branch** of OrchardCore repo.

Note that page is pretty big - with nested widgets etc. There are lots of calls to content pickers and media pickers. Each of them takes some time

**Comment by Skrypt** [comment]
A full height page screenshot would give an idea of the size of that FlowPart editor. I'm assuming that it is what you are using. Then, you may have handlers work happening in there.

**Comment by MikeKry** [comment]
@Skrypt 

Sure here it is.
![screencapture-localhost-44300-testsite-Admin-Contents-ContentItems-4nqz90a5rfr8n66jbna8bm75c1-Edit-2024-01-30-18_42_12](https://github.com/OrchardCMS/OrchardCore/assets/52829889/6aafc3fc-4566-4279-8d8a-d01d9146d403)

I would like to highlight that also empty pages of this content type are slower for me.

**Comment by Skrypt** [comment]
Ok, could you provide us with a repro solution with a database backup so that we can investigate where the perf issue is?

**Comment by MikeKry** [comment]
@Skrypt  

Not sure I can share that. I will check. 

But I have performed another tests and narrowed down suspicious parts. Tests have been performed on new content type which contains only flow part. Content types without flow part seem to not have an issue.

1/ Content types - slowing down 5 times
When I upload a bunch of content types, everytime I save something it gets slower. It seems that content type definitions get loaded every time from database and it is slow.  Maybe it is loaded for each possible widget in flow part?

When I activate filesystem content definition, speed is OK. (same as it was on versions before)

So i think this is the root cause, maybe some incorrect transition to GetTypeDefinitionAsync? 

2/ Workflows + HTTP Workflows Activities are slowing down page save by 300 ms

3/ some other modules like content indexing and audit trail, but they have only a slight impact.

**Comment by Skrypt** [comment]
Try updating the ContentDefinitions in your DB from the file. Maybe it is really slow trying to parse that JSON because there is an issue with it. But that would be a first, normally it would simply fail to parse it. Else, the issue seams to be also related with caching the ContentTypeDefinitions if it does a SQL Query every time (which should not be the case).

**Comment by Skrypt** [comment]
![image](https://github.com/OrchardCMS/OrchardCore/assets/3228637/27b30e2a-feb8-48e1-b0ae-2d54630b8cad)

Maybe the recipe is failing to import the content item there because I get nothing in that FlowPart.

**Comment by Skrypt** [comment]
I'd probably need to have that content item that is slow else it may take time for me to reproduce by creating lots of content like you did there.

**Comment by MikeKry** [comment]
@Skrypt 

Okay, that is interesting - screen you sent is OK. 

But this is results I get.. are you also on main branch of orchardcore?
![image](https://github.com/OrchardCMS/OrchardCore/assets/52829889/86294204-b805-4adf-a941-dc652b4e43fb)

**Comment by MikeKry** [comment]
if it works for you, maybe it is just a coincidence and the problem will be in our database connection. I will try to check it again..

**Comment by MikeKry** [comment]
@Skrypt 

OK. Main problem is definitely in connection to database. It has ~30 ms latency... So sorry for wasting your time and thanks for helping me figure this one out. 

Anyway, I wonder why total time increases with each content type..?
