### ISSUE TITLE
Adding optional media field to exiting content type crashes

### ISSUE THREAD

**Issue by etcetraw** [OrchardCMS/OrchardCore#1518]
If I have an existing content type and have some content items of that type and I add new optional media field to it. It seems to crash even if it is not required.

**Comment by sebastienros** [comment]
Can't repro on dev, probably fixed.

**Comment by muratcabuk** [comment]
today I tested the issue and I got same error.

step 1: I created a content type A
step 2: I created a content type B and I added a List part contains Type A
step 3: I added some content to B
step 4: I edited content type B by adding media field.

after steps I tried to edit a content item that added content type b and I got error.
