### ISSUE TITLE
contentpreview-edit.js doesn't declare jQuery as its dependency

### ISSUE THREAD

**Issue by Psichorex** [OrchardCMS/OrchardCore#15181]
### Describe the bug
After upgrading to Orchard Core 1.8 some preview buttons inside of content item editors become broken.
They are broken because the driving script behind it called `contentpreview-edit` has an exception of:
![6587e414-77ca-4ba6-bb94-96c3be0bf8d1](https://github.com/OrchardCMS/OrchardCore/assets/92299130/bcb8fe72-e6c4-4d8b-b6d8-5191d0041ad7)
`$ is not defined` is almost always due to a script being called before `jQuery` is registered.
Same happens in Orchard Core as the problematic content items have `contentpreview-edit` script registered prior to `jquery.js`
Making a code that brings `jquery` in front resolved the problem.

`contentpreview-edit` doesn't declare `jquery` as it's dependency:
Nor in its corresponding ResourceManagementOptionsConfiguration
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.ContentPreview/ResourceManagementOptionsConfiguration.cs#L14-L17
Nor in the script inclusion in the Razor.
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.ContentPreview/Views/ContentPreview.Button.cshtml#L22

I can't write a direct way of reproducing this because when I am creating a Content Type from the Admin page it works but Content Types that are coming from Migrations and custom code are broken.

Either way `contentpreview-edit` should have `jquery` declared as its dependency.

**Comment by Piedone** [comment]
Please provide repro steps so we can check it being broken and indeed fixed after adding a dependency.

**Comment by Psichorex** [comment]
@Piedone I can only provide reprosteps for our OSOCE repository.
But it's basically go to ContentItems list and open any custom type:
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/bf2c8d1b-deea-4ad0-a076-94146558e783)
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/15d2d27f-2209-4740-950e-ced014cbbc8f)
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/da5d79a0-f2c6-412a-9ca2-0ee38153cc56)


Also there are pages where it's working:

![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/01c2bbe8-5d63-45c0-98b5-461d7980d67f)


Where it's not working all those pages have `contentpreview-edit` registered first and `jquery` just after.

**Comment by Piedone** [comment]
Please provide an export of the content type you're using. Something is different than the built-in Blog Post, since if you check that with the latest source, this doesn't happen.

**Comment by Piedone** [comment]
And first make sure that this also happens with the OC source, i.e. it's not caused by anything in the custom solution.

**Comment by MikeAlhayek** [comment]
This is probably an issue after upgrading the admin theme. Can you submit a PR to adding to this?
@Psichorex  can you submit a PR by adding the line `.SetDependencies("jQuery")` to this?

https://github.com/OrchardCMS/OrchardCore/blob/f843b91d479e222474a067573fcb5022814af6ed/src/OrchardCore.Modules/OrchardCore.ContentPreview/ResourceManagementOptionsConfiguration.cs#L15

We should spend time to remove jQuery from these older scripts.

**Comment by Psichorex** [comment]
> This is probably an issue after upgrading the admin theme. Can you submit a PR to adding to this? @Psichorex can you submit a PR by adding the line `.SetDependencies("jQuery")` to this?
> 
> https://github.com/OrchardCMS/OrchardCore/blob/f843b91d479e222474a067573fcb5022814af6ed/src/OrchardCore.Modules/OrchardCore.ContentPreview/ResourceManagementOptionsConfiguration.cs#L17
> 
> We should spend time to remove jQuery from these older scripts.

@MikeAlhayek Seems like I don't have the permission to commit. I thought I was added as a contributor. TL:DR I can't open a PR.

**Comment by Piedone** [comment]
You need to work in a fork.

**Comment by Psichorex** [comment]
I will add this in our fork.

**Comment by MikeAlhayek** [comment]
yes create a branch out of your fork. then create a cross repository into OC main branch. Feel free to ping me when you create the PR.

**Comment by Psichorex** [comment]
@MikeAlhayek here is the PR in our Fork
https://github.com/OrchardCMS/OrchardCore/pull/15183
