### ISSUE TITLE
Inconsistent ContentDefinition and content recipe steps

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1519]
In the ContentDefinition step the type settings represents booleans as string:
```
"Creatable": "True",
"Draftable": "True",
"Versionable": "True",
"Listable": "True",
"Securable": "True"
```
But in the content step the representation is bool:
```
"Latest": true,
"Published": true,
```

It looks like it's interchangeable but it's less confusing if something is consistent.

Another minor thing is that the ContentDefinition step name starts with upper case and the content step name with lower case. Probably it's also doesn't matter but can be confusing too.

**Comment by sebastienros** [comment]
wip on sebros/records
