### ISSUE TITLE
Document using  "Encrypt=false" in the connection string on the Orchard Setup Page.

### ISSUE THREAD

**Issue by Psichorex** [OrchardCMS/OrchardCore#15201]
![image](https://github.com/OrchardCMS/OrchardCore/assets/92299130/3b50adb6-c47a-43bb-a93b-b90c39069eb8)
There could be some documentation indicating the usage of `Encrypt=false` for local development on the Orchard Core setup page because it is possible that if someone tries to use a SQL db without that as the original documentation suggests they would not be able to connect to the DB.

### Describe the solution you'd like
Document `Encrypt=false` in the Hint below the TextField.

**Comment by MikeAlhayek** [comment]
`Encrypt=false` is for development only and not for production. I do not think it is a good idea to put that as part of the string sample because we don't want to encourage people to use it by default or accidentally in production.

**Comment by hishamco** [comment]
Should be fixed in #13792

**Comment by hishamco** [comment]
> I do not think it is a good idea to put that as part of the string sample because we don't want to encourage people to use it by default or accidentally in production.

It could be a hint as Seb mentioned in the related PR
