### ISSUE TITLE
Orchard does not accept MAILTO <tag> in the HTML

### ISSUE THREAD

**Issue by YoumnaJ** [OrchardCMS/OrchardCore#15236]
Hi, I need to put MAILTO <tag> in the HTML of a content type in my orchard core cms solution, But when I add  MailTo to html and After clicking  publish button  the html tag <MAILTO> does not appear  can someone give me the reason of what is happening or a solution that resolves my problem ?
![image](https://github.com/OrchardCMS/OrchardCore/assets/154245181/6de8f932-60df-43e1-90c6-554923542b92)

thank you,

**Comment by hishamco** [comment]
`mailto` is an HTML thing it isn't related to Orchard Core, 

Could you please let me know are you using HTML body and place the link there?

**Comment by rjpowers10** [comment]
@YoumnaJ the "mailto" is being stripped out by the HTML sanitizer.

[Here is an example of allowing the "mailto".](https://docs.orchardcore.net/en/latest/docs/reference/core/Sanitizer/#configuring-the-sanitizer)

**Comment by hishamco** [comment]
That's why I want to say @rjpowers10 if he is answering my above question

**Comment by hishamco** [comment]
Have a look to the [docs](https://docs.orchardcore.net/en/latest/docs/reference/core/Sanitizer/)
