### ISSUE TITLE
Compilation issue "SkipNonExistentTargets"

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#1523]
I'm on dev branch latest commit 25ca92f3d8269858676845ea4020c076040cc16e. The 'SkipNonExistentTargets' parameter is not supported by the 'MSBuild' task. Maybe a VS Mac specific issue. I'm running on .net core 2.1.4

<img width="1118" alt="capture d ecran 2018-02-24 a 14 29 54" src="https://user-images.githubusercontent.com/3228637/36634219-46dec476-196f-11e8-8d21-27311e271bef.png">

I just tried on Windows 10 with VS 2017 and I have the same error.

**Comment by Skrypt** [comment]
For resolving this issue on Windows you need to update Visual Studio to version 15.5.7 which will update MSbuild to latest version that support this new parameter. On Mac OS with Visual Studio version 7.3.3 (build 23) it's not supported yet.

**Comment by Skrypt** [comment]
I'm reopening for people that runs into the same problem to find the solution quicker. I'm not sure if writing a Wiki would be relevant since this is a Visual Studio + MSbuild "issue".

**Comment by jtkech** [comment]
@Skrypt thanks for looking into this

**Comment by sfmskywalker** [comment]
I'm getting this exact same issue on Visual Studio 2017 version 15.7.0 Preview 4.0.

**Comment by Skrypt** [comment]
That's a MSBuild version issue. I'm surprised it doesn't work with latest version.

**Comment by B-Esmaili** [comment]
So what is the solution for this problem?

**Comment by Skrypt** [comment]
I'd say wait for the official release of .NET Core 2.1 and tools if you want to be sure this works else it's previews ... but latest preview versions should normally work.

**Comment by moh-hassan** [comment]
I faced this problem in vs 2017 update 3. It raised when i check `Generate nuget package on build` in the project properties ->Package.

I unchecked this property and the error  disappeared.
I  pack the package by nuget tool not from vs to avoid this issue "SkipNonExistentTargets.

I tried vs 2017 update 5, and it's working fine and issue "SkipNonExistentTargets is resolved.
