### ISSUE TITLE
Trigger build Documentation not effective anymore

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#15242]
The webhook between GitHub and ReadTheDocs that is supposed to trigger the build of the documentation when a PR is merged to main does not work anymore (Last working build happended 3 days ago) and I don't manage to solve it.

We are going to need to think about building the docs with a GitHub actions and deploy on GitHub Pages.

If someone wants to be in charge of this task, please comment.

We also need to check which change we will have to make on the docs.orchardcore.net DNS mapping.

**Comment by MikeAlhayek** [comment]
@agriffard could it be because the SSL certificate is invalid on https://orchardcore.net/?

**Comment by agriffard** [comment]
> @agriffard could it be because the SSL certificate is invalid on https://orchardcore.net/?

No, I don't think it is related.

**Comment by agriffard** [comment]
I configured it again and I think I managed to make it work, it is not in error anymore.

I launched a build manually.

**Comment by MikeAlhayek** [comment]
awesome! thank you
