### ISSUE TITLE
Incorrect certificate on orchardcore.net

### ISSUE THREAD

**Issue by fowl2** [OrchardCMS/OrchardCore#15243]
Hi team, apologies for the drive by, but it appears orchardcore.net is serving the wrong certificate, and is therefore showing this error:

![IMG_2595](https://github.com/OrchardCMS/OrchardCore/assets/12844147/ec933a4d-6d77-433a-99f3-054fc6a6eba7)

**Comment by MikeAlhayek** [comment]
yes @sebastienros is working on it.

**Comment by hishamco** [comment]
It happened one more time #14300

**Comment by Piedone** [comment]
Since this keeps happening, again, why don't we put the site behind Cloudflare, that handles certificate updates automatically (and much more)? I can do it.

**Comment by MikeAlhayek** [comment]
@Piedone i think in Azure there is an option that does it automatically. I think @sebastienros has it set to auto renew (it auto renewed last year). But there is some wrong that prevented it from auto renewing. At least this is what I understood from last meeting.

**Comment by Piedone** [comment]
Yeah, but apparently it failed thrice already, so it's not really reliable, while Cloudflare is.

**Comment by sebastienros** [comment]
The issue is the DNS record that is wrong and the public IP changed. It's DNF who can fix it and I contacted them. Waiting now. The certificates are correctly renewed, see www, but this one failed because the IP doesn't match the record.

**Comment by agriffard** [comment]
Certificate renewed.
