### ISSUE TITLE
AdminMenuNavigationProvidersCoordinator issue in main branch

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#15246]
I'm getting a lot of these in logs.

``` 
2024-02-03 12:39:15.9619|Default|00-4bc7e8b97123fe0446aeb1b4d56c3eee-022055cef940b42d-00||OrchardCore.AdminMenu.Services.AdminMenuNavigationProvidersCoordinator|ERROR|No Builder registered for admin node of type 'AdminNode' 
```

**Comment by hishamco** [comment]
@MikeAlhayek I think you did some changes recently on the navigations APIs

**Comment by MikeAlhayek** [comment]
@sebastienros is this our fist issue after merging STJ PR?

**Comment by hishamco** [comment]
How is this related to STJ

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/6baa536b17a9641b3da72218dfaf643613f9e680/src/OrchardCore.Modules/OrchardCore.AdminMenu/Services/AdminMenuNavigationProvidersCoordinator.cs#L60-L75

**Comment by MikeAlhayek** [comment]
Because the admin nodes are stored in a document that has to be serialized.  I yet had to test it, but you can put a break point in the adminMenuService and see if the nodes mapped to the objects are as expected or not

**Comment by MikeAlhayek** [comment]
@Skrypt in your project, do you have a custom implementation of node type? If so, you'll need to register it like this 
```
services.AddAdminNode<CustomAdminNode>();
```

**Comment by MikeAlhayek** [comment]
Thanks for the feedback. I added a fix to this issue in #15261

**Comment by Piedone** [comment]
This still happens on the latest `main` (9e66231f22ef397b70c9d0deab885ea0a2fe31fd).

1. Run fresh setup with the Blog recipe.
2. Go to /Admin.
3. 3 such log entries.

**Comment by hyzx86** [comment]
Hi @Skrypt , Does your application still have this problem? My application keeps outputting the same log, even if I use the latest preview package

**Comment by hyzx86** [comment]
> Hi @Skrypt , Does your application still have this problem? My application keeps outputting the same log, even if I use the latest preview package

Well, I need to clear out the Redis cache
