### ISSUE TITLE
Bug with CORS Policy renderings in admin

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#15259]
The latest version has some ui issues with   vue js and does not show policy name in index and detail view 

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/77cf9db5-d00f-46eb-80d3-ebd8b7360801)

**Comment by MikeAlhayek** [comment]
@giannik it maybe a element that isn't added to the screen. Can you submit a PR to fix this?

**Comment by giannik** [comment]
@MikeAlhayek i'll try . my vue skills are limited 😁

**Comment by lampersky** [comment]
> @MikeAlhayek i'll try . my vue skills are limited 😁

@giannik ping me if you need help or if you are busy with other things, let me know so I will fix it
