### ISSUE TITLE
When using the TimeZone feature too many sql requests are made

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#15263]
When using the TimeZone feature, and the user does not have a TimeZone set (which is the default for new users), any requests looking to use `ILocalClock` will make a database query for the user, fail to find a timezone, and fail to set a cache value.

the issue is in this code
```
    public async Task<string> GetCurrentUserTimeZoneIdAsync()
        {
            var userName = _httpContextAccessor.HttpContext.User?.Identity?.Name;

            if (string.IsNullOrEmpty(userName))
            {
                return null;
            }

            var key = GetCacheKey(userName);
            var timeZoneId = await _distributedCache.GetStringAsync(key);

            if (string.IsNullOrEmpty(timeZoneId))
            {
                var user = await _userManager.FindByNameAsync(userName) as User;
                timeZoneId = user.As<UserTimeZone>()?.TimeZoneId;

                if (!string.IsNullOrEmpty(timeZoneId))
                {
                    await _distributedCache.SetStringAsync(key, timeZoneId, new DistributedCacheEntryOptions { SlidingExpiration = _slidingExpiration });
                }
            }

            return timeZoneId;
        }
```

where it might be appropriate to set a `NoValueFound` cache value, to prevent this.

current workaround is to use user event handlers to force set the usertime zone as they are created to the sites timezone,  but this has other issues.

the code above looks like it needs a rework, as it's sliding at one minute, which is a bit low if you're expecting performance.

**Comment by Skrypt** [comment]
Or here we should assume that if a User has a Null TimeZoneId that we should be using the Site TimeZone instead. And also, instead of using the userManager on every request we could cache the `UserName's | TimeZoneId's` and refresh that cache every time a user is modified/deleted.
