### ISSUE TITLE
Migrate to Minimal APIs

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#15274]
Minimal APIs would provide better performance with minimal disruption since we are already organized as modules. I'd like to see someone trying to convert a simple module to it and see if it improves performance or find issues during the process.

**Comment by Piedone** [comment]
Can you elaborate? Like, from MVC controllers? Filling out the issues template would've helped ;).

**Comment by sebastienros** [comment]
> Like, from MVC controllers

Yes, that's what we use, and minimal apis is an alternative to them.
