### ISSUE TITLE
Css and js override from child theme/module

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1527]
Like in O1, where you can override the base theme's css from a child theme (by creating a Site.css).
Will be this a supported scenario?

**Comment by sebastienros** [comment]
This is not supported. We need to talk about how useful this is compared to changing the links to new files. This adds lots of overhead.

**Comment by alberthajdu** [comment]
@sebastienros what about approaching this from `IResourceManifestProvider`s? We could add a new method (`Override()`) and property to `ResourceDefinition.cs` and the `ResourceManager.cs` could use this property to decide which resource to use. This wouldn't add any overhead.
There is a workaroud to override resources by adding a resource with the same name but a higher version number. My proposed soultion essentially would do the same thing but with a dedicated property: if there's 2 resources with the same name and one of them says that I'm an override then it will be applied.

I'm not sure what to do when there are more than 2 resources and how to involve module dependencies into this concept but this could be a good starting point.

What do you think?

**Comment by awyl** [comment]
+1 for `Override()`

My use case is that ajax.googleapis.com was blocked in china.  I need to replace the predefined resources with cdnjs.com.

**Comment by Piedone** [comment]
This was duplicated by https://github.com/OrchardCMS/OrchardCore/issues/3038 but since there's a lot more activity, I'm closing this one.
