### ISSUE TITLE
Error after click Finish Setup

### ISSUE THREAD

**Issue by RatJak** [OrchardCMS/OrchardCore#1528]
I clone project from git and start project in VS 2017, I start in OrchardCore.Cms.Web

I put info about web page:

Name: MySuperSite
Recipe: Agency

Database: Sql Server
Table Prefix: OrchardCoreDB
Connection string: Data Source=ratjakpc\\\\SQLEXPRESS;Initial Catalog=OrchardCoreDB;User Id=userid;Password=password

Super user: my login, mail and password

after click to Finish Setup button in concosle show error:
Failed to load resource: the server responded with a status of 404 (Not Found)

Some ideas?

**Comment by sebastienros** [comment]
Can;t repro
