### ISSUE TITLE
Error handling in migrations

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1530]
If something goes wrong in a migration there's no info in the log about the exception.

Only the following 3 lines. So there's 3 messages about the same error but no info about the actual exception.

![migrations](https://user-images.githubusercontent.com/12067180/36725225-ea15eca8-1bb5-11e8-9b0c-7499883f53a6.png)

**Comment by Piedone** [comment]
Migration exceptions are properly logged in the latest version.
