### ISSUE TITLE
build on Ubuntu is failing occasionally

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#15308]
sometimes build is failing on Ubuntu, here it is an example:

https://github.com/OrchardCMS/OrchardCore/actions/runs/7862582347/job/21452217647?pr=15305#step:6:27

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: An item with the same key has already been added. Key: PartName
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
         at OrchardCore.ContentManagement.GraphQL.FieldTypeExtensions.WithMetaData(FieldType fieldType, String name, Object value) in /_/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Extensions/FieldTypeExtensions.cs:line [26](https://github.com/OrchardCMS/OrchardCore/actions/runs/7862582347/job/21452217647?pr=15305#step:6:27)
```

**Comment by hishamco** [comment]
I notice a flaky tests few days ago

**Comment by MikeAlhayek** [comment]
@sebastienros I think there is a concurrent issue here.

The `ISchemaFactory` is being registered as singleton which calls `IEnumerable<ISchemaBuilder>`

https://github.com/OrchardCMS/OrchardCore/blob/f8a086bb83c22202ae009f7dc385b80aa8b5d882/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Startup.cs#L36

One of the ISchemaBuilders is not thread safe as it calls the following extension.

https://github.com/OrchardCMS/OrchardCore/blob/f8a086bb83c22202ae009f7dc385b80aa8b5d882/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Extensions/FieldTypeExtensions.cs#L26

The Medadata here is a Dictionary<> which isn't thread safe.

I quick fix would be to using .TryAdd() here

https://github.com/OrchardCMS/OrchardCore/blob/f8a086bb83c22202ae009f7dc385b80aa8b5d882/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Extensions/FieldTypeExtensions.cs#L26

or, change the registration if `ISchemaFactory` to scoped.

I am not very familiar with the GraphQL implementation so not sure if we can change how `ISchemaFactory` is registered in this case or should we just go for the quick fix?

**Comment by sebastienros** [comment]
If it's a thread safety issue then you can't call `TryAdd` either, it's still not thread-safe, if will just prevent the exception that `Add` is finding the issue already exists. Either a lock, or understanding why two concurrent calls were issued here would be a solution. Note there is a semaphore at a higher level, maybe it's at that point that the lock should be. But resolving a cache (outside of the semaphore) might assume there is no write at that point.
