### ISSUE TITLE
Remove content liquid filter

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1532]
We shouldn't be using liquid filters to retrieve data.

I suggest that content can be fetched by alias from liquid by using scoped values. Something along the lines of `{{ Content.MyContentAlias | display_text }}`.

To decide: 

- Is `Content.MyContentAlias` correct? Do we want some other naming convention? Maybe `Data.Content.MyContentAlias` (which would allows us to put other site data (e.g. queries) on the Data property too)
- How do we retrieve by content item ID? Do we want to allow this at all? Is it fair to assume that anyone who wants to retrieve content from a template/view should be using aliases?

**Comment by paynecrl97** [comment]
Closing in favour of #1529

**Comment by sebastienros** [comment]
For complex aliases we can use this syntax:

- `Content["alias:main-menu"]` // Alias handler
- `Content.Alias["main-menu"]`  // Alias part, not the handler directly
- `Content.Slug["/blog/my-post"]` // Autoroute index
- `Content.ContentItemId["4abcdefgh"]` // Content manager API

**Comment by paynecrl97** [comment]
Are there any examples I can look at to implement that dictionary style syntax?

**Comment by paynecrl97** [comment]
Progress so far: https://github.com/OrchardCMS/OrchardCore/compare/1532/liquid_content?expand=1

Still to do:

- [ ] Get rid of `GetAwaiter().GetResult()` (requires https://github.com/sebastienros/fluid/pull/67)
- [ ] Remove old `Content` filter
- [ ] Allow a specific version/ latest version of a content item to be retrieved. Or don't. I'm not too sure if this has any genuine use cases?

**Sample liquid markup:**
```
<ol>
  <li>{{ Content["alias:myarticle"] | display_text }}</li>
  <li>{{ Content.Alias["myarticle"] | display_text }}</li>
  <li>{{ Content.Slug["/wow-what-a-title"] | display_text }}</li>
  <li>{{ Content.ContentItemId["49gq8g6zndfc736x0az3zsp4w3"] | display_text }}</li>
</ol>
```

_As Alan Partridge (almost) once said:_ "This is liquid content!"

**Comment by paynecrl97** [comment]
The current `content` filter (that this work is replacing) allows a specific version/ the latest version of a content item to be retrieved by passing the appropriate parameters (something along the lines of `{{ "content-id" | content: isLatest: true }}`)

Does anyone have any opinion on whether we need to keep this functionality? And if so, what should the syntax look like?

**Comment by paynecrl97** [comment]
I added `Latest` and `ContentItemVersionId` properties:

```
<ol>
  <li>{{ Content["alias:myarticle"] | display_text }}</li>
  <li>{{ Content.Latest["alias:myarticle"] | display_text }}</li>
  <li>{{ Content.Alias["myarticle"] | display_text }}</li>
  <li>{{ Content.Slug["/wow-what-a-title"] | display_text }}</li>
  <li>{{ Content.ContentItemId["49gq8g6zndfc736x0az3zsp4w3"] | display_text }}</li>
  <li>{{ Content.ContentItemVersionId["4v71x37q9g1k83c9qeydnkjvmd"] | display_text }}</li>
</ol>
```
