### ISSUE TITLE
Allow 2FA for non-admin users too

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15335]
### Is your feature request related to a problem? Please describe.
2FA setup is only linked from the admin profile menu, and more importantly, setting it up is only authorized to admin users ([`TwoFactorAuthenticationController`](https://github.com/OrchardCMS/OrchardCore/blob/bfa748702d4cfd286a59d3e07f3c00761923dddc/src/OrchardCore.Modules/OrchardCore.Users/Controllers/TwoFactorAuthenticationController.cs)'s actions are marked with `[Admin]`). This is an issue because ordinary (frontend) users could benefit from 2FA the same. If you make somebody admin temporarily, then after setting up 2FA they'll be able to log in with it without being an admin then anyway.

### Describe the solution you'd like
Allow non-admin users to set up 2FA options too. This is a permission management issue and the routing of some `TwoFactorAuthenticationController` actions need to change too.

### Describe alternatives you've considered
I don't think there is an alternative to 2FA.

**Comment by Piedone** [comment]
@MikeAlhayek was there a specific reason not to allow non-admins to set up 2FA?

**Comment by MikeAlhayek** [comment]
@Piedone the 2FA uses the AdminTheme. The user does not have to be an admin to enable 2FA. For example if you require 2FA for all users, then when any user logs in, they will have to go through and enable 2FA using the admin theme. I don't recall why specifically The Admin theme. But, one reason could be that all sites use the admin theme and making a single template is easier than having to create a template for all the themes that we currently support.

**Comment by Piedone** [comment]
Non-admin users can't access /TwoFactor due to it having the `[Admin]` attribute so I don't see how they could set up 2FA. They can log in with it if already set up (by temporarily making them admin).

**Comment by MikeAlhayek** [comment]
`[Admin]` does not have any permission checks associated with it.  `[Admin]` just indicate to render the Admin theme. Permission check happens in the action itself.

In that example of `TwoFactorAuthenticationController` if the use got that far, they are already authenticated "but 2FA is not enabled yet."

**Comment by Piedone** [comment]
It [checks for `AccessAdminPanel`](https://github.com/OrchardCMS/OrchardCore/blob/bfa748702d4cfd286a59d3e07f3c00761923dddc/src/OrchardCore.Modules/OrchardCore.Admin/AdminFilter.cs#L58) apart from affecting the theme selection. Why I opened this issue is because I tried to set up 2FA with a non-admin user and got an access denied.

So then I guess the authorization is not intentional?

**Comment by MikeAlhayek** [comment]
hummm. yeah was not aware of that.

I think here we can safely not use the `[Admin]` attribute. Then tweak the `UsersThemeSelector` to return admin theme when dealing with any 2FA. Or we could add a new attribute for the 2fa routes.

**Comment by Piedone** [comment]
OK then!
