### ISSUE TITLE
Custom Model saving process using SectionDisplayDriver

### ISSUE THREAD

**Issue by cocoke** [OrchardCMS/OrchardCore#1534]
I started to develop on OrchardCore and I need some details.
I'm trying to extend the user model by adding two properties : 

```
public class CustomUser
{
        public string Client { get; set; }
        public string Adress { get; set; }
}
```

And implementing a driver to manage it :
```
public class CustomUserDisplayDriver : SectionDisplayDriver<User, CustomUser>
{
        public override IDisplayResult Edit(CustomUser customUser, BuildEditorContext context)
        {
            return Shape<CustomUserViewModel>("CustomUser_Edit", model =>
            {
                model.Adress = customUser.Adress;
                model.Client = customUser.Client;
            }).Location("Content:2");
        }

       public override async Task<IDisplayResult> UpdateAsync(CustomUser customUser, IUpdateModel updater, BuildEditorContext context)
       {
            var model = new CustomUserViewModel();
            if (await context.Updater.TryUpdateModelAsync(model, Prefix))
            {
                customUser.Adress = model.Adress;
                customUser.Client = model.Client;
            }
            return Edit(customUser);
        }
}
```

I took inspiration on the demo module and I don't understand how the save process work.
Can someone explain me the right process to follow ?

**Comment by sebastienros** [comment]
Is it an issue about it not working, or just that you want more details about how the magic happens?

**Comment by cocoke** [comment]
The current code (taken from the demo module and a bit modified) doesn't work. 

The process is unclear for me, do I have to create the columns in the database or to add an extra layer to save the custom properties or the magic handles everything itself ?

Thanks for the quick answer.

**Comment by sebastienros** [comment]
First, Orchard content management and UI are all about composition. There is a concept of `Entity` that is a class that can have any properties, like a dictionary, and internally it's using a `JObject`. We use this as a base class when we want something to be composable dynamically.

A `User` class inherits from it, and has specific properties too which are not removable. When we try to render the editor or the display of a User in the admin controller, we use an API that will call any `Driver` for `User` to provide the UI, or update the object.

We provide a special king of `Driver`, the `SectionDisplayDriver` that will be able to act specifically on `Entity` based classes and __weave__ some class to this entity. In your case you are trying to weave a `CustomUser` object to a `User` entity. The driver will then add all the properties of your class to the user object's properties.

After that, Orchard will store this user object by serializing it in JSon and storing it in the database as a document. Orchard uses YesSql which is also able to build indices for your data if you need to query it. The class `User` comes with its own index, represented by the class `UserIndex`. If you need to query based on your own properties then you can create an index too.

A typical issue if it doesn't work is that you may have forgotten to register the driver class in the DI. Look at the startup of your module.

**Comment by cocoke** [comment]
Problem solved : some package were missing and I didn't noticed the viewport content which I think is important : 

```
@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
@addTagHelper *, OrchardCore.Demo
```

After adding this content and fix dependancies, the custom properties were saved successfully.
Thanks for the explanations.
