### ISSUE TITLE
Allow setting Autoroute.Path to "/" if AutoroutePart.SetHomepage is true

### ISSUE THREAD

**Issue by M-Lipin** [OrchardCMS/OrchardCore#15356]
### Is your feature request related to a problem? Please describe.
There is an issue when trying to set some content as a homepage content with empty path so need to add some postfix to "/" to save valid permalink.

### Describe the solution you'd like
It seems to me that we can allow setting "/" permalink for content which is a homepage content.

### Describe alternatives you've considered
As an alternative we can use a redirect but this is a temporary solution.

![image](https://github.com/OrchardCMS/OrchardCore/assets/23213980/e648ce09-9940-4e30-b9ee-be755082b4e8)

**Comment by Skrypt** [comment]
It should then become an alias of that page.

**Comment by Piedone** [comment]
Why is it not OK to provide a valid permalink (that's auto-generated from the title anyway)?
