### ISSUE TITLE
OrchardCore.Contents API: Admin user is not able to GET a content, an error 401 unauthorized is returned, but if I grant all privileges to the "anonymous" user role, it works

### ISSUE THREAD

**Issue by MarGraz** [OrchardCMS/OrchardCore#15381]
### Describe the bug

According to what discussed [here](https://github.com/OrchardCMS/OrchardCore/discussions/15372#discussioncomment-8544179) with @hishamco, I'm opening this issue to verify it.

The module `OrchardCore.Contents` exposes an `ApiController.cs` with endpoints to _create_, _update_, and _delete_ content items created in the "Admin" backoffice. Using _Postman_, it's possible to call the `ApiController.cs` endpoints after configuring the "OpenID Connect" `OpenID Authorization Server` module.

I tested this using the "Try Orchard" website. **The authentication** process **is successful**, and I receive a valid OAuth 2 token. **But, when attempting to use the "Admin" user**, which is supposed to have the highest privileges, **I cannot perform GET, UPDATE, or DELETE operations**, I receive a 401 unauthorized error. **Instead, if I grant all privileges to the "anonymous" user role** to call the API, and remove the OAuth token, **it works**.

### To Reproduce

NOTE: _As mentioned, I'm using a temporary "try.orchardcore" website, which is why I'm sharing the credentials here. They will expire along with the temporary website._

1. Import the Postman collection attached [Test.postman_collection.zip](https://github.com/OrchardCMS/OrchardCore/files/14362999/Test.postman_collection.zip) (it already contains the Client Id and Secret);
2. Get an authorization token via Postman "Authorization" blade (all the fields should be already set)
3. Try to call this endpoint using GET method: https://try.orchardcore.net/jgjn0h2r/api/content/455vmd500wgrj7nqqpysw3px4s
4. You will get error 401 Unauthorized

### Expected behavior
The "Admin" user**, which is supposed to have the highest privileges, must be able to retrieve a content from the GET endpoint.

### Screenshots
Postman Authorization blade configuration

![image](https://github.com/OrchardCMS/OrchardCore/assets/19241483/26058490-0add-404f-8481-b2c4a0f35871)

**Comment by MarGraz** [comment]
If you want to reproduce this in a new Orchard Core installation, you need to install and configure the "OpenID Connect" `OpenID Authorization Server` module. Mine is configured like in the screenshot below.

![image](https://github.com/OrchardCMS/OrchardCore/assets/19241483/0e45e87f-e7e8-4fbe-8443-e7d6f8e1ff0d)

**Comment by hishamco** [comment]
@kevinchalet any idea before I try to reproduce the issue, coz you our OpenID guru :)

**Comment by kevinchalet** [comment]
A 401 HTTP response returned by the OpenIddict validation stack typically indicates a missing or invalid token but in this case, there's no trace of a `WWW-Authenticate` header in the response, which is the sure sign the challenge wasn't actually handled by OpenIddict:

![image](https://github.com/OrchardCMS/OrchardCore/assets/6998306/447e90b4-04e3-4587-a8af-11003fff8371)

@MarGraz have you enabled the OpenID validation feature? It's required if you want to use bearer token authentication in the same tenant as the authorization server.

**Comment by kevinchalet** [comment]
> I thought it was implicit for the server to validate tokens. I expected to activate and use the "OpenId Token Validation" feature for the "OpenId Client", and not for the authorization server.

Actually, the OpenID server feature only validates tokens for endpoints it controls (e.g the userinfo endpoint). For any other endpoint, it's the OpenID token validation feature that takes care of that (there's no relationship between the token validation feature and the client feature, which is completely separate).

> Maybe it's necessary to clarify in the description of the "OpenId Authorization Server" feature, or in the "OpenId Token Validation" feature, that activating the "OpenId Token Validation" is necessary to get tokens validated in this case.

Sure, feel free to send a PR to clarify the descriptions 👍🏻

**Comment by kevinchalet** [comment]
The description has been fixed in https://github.com/OrchardCMS/OrchardCore/pull/15407. Closing.
