### ISSUE TITLE
YesSql.Core with version 2.0.0-beta-1192 does not exist

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#1538]
Hi,

Orchardcore reference a YesSql version that does not exist (lastest = 1189).. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package YesSql.Core with version (>= 2.0.0-beta-1192)
  - Found 101 version(s) in NuGet [ Nearest version: 2.0.0-beta-1189 ]
  - Found 0 version(s) in Syncfusion.Local
  - Found 0 version(s) in OrchardCore	Flexmind.Framework.Database	C:\Dev\WEBCSCORE\Flexmind.Framework\Flexmind.Framework\src\Core\Flexmind.Framework.Database\Flexmind.Framework.Database.csproj	1

**Comment by alberthajdu** [comment]
This is present in packages versions: 1.0.0-beta2-4663, 1.0.0-beta2-4673, 1.0.0-beta2-4676.
So above 1.0.0-beta2-4657.
