### ISSUE TITLE
Use Hashcode.Combine

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#15412]
To replace [our own logic](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore/Extensions/Features/FeatureHash.cs#L33C17-L33C67)

https://learn.microsoft.com/en-us/dotnet/api/system.hashcode.combine?view=net-8.0

**Comment by hishamco** [comment]
Luckily you reminded me of an old usage of  `HashCode.Combine()` in localization

https://github.com/OrchardCMS/OrchardCore/blob/721f8ad204b0a5176a4d30b19899a532a9cb0d33/src/OrchardCore/OrchardCore.Localization.Abstractions/CultureDictionaryRecordKey.cs#L59
