### ISSUE TITLE
Restarting instance of a workflow starting with the Content Created event fails with InvalidCastException

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/OrchardCore#15411]
### Describe the bug

Restarting instance of a workflow starting with the Content Created event fails with `InvalidCastException`.
It doesn't matter what else happens in the workflow (I initially tested with a real-world use-case, not just an event without actions).

### To Reproduce
1. Set up fresh site using any recipe, I tested with Blank and Blog.
2. Enable the Workflows feature and create a workflow with the Content Created event. Select all content types for the event and set it as the Startup task.
3. Create a content item of any type, observe that the workflow instance runs successfully.
4. Go to the list of workflow instances and restart the instance.
5. The following exception is thrown:
```
`InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'OrchardCore.ContentManagement.IContent'.`
```
Call stack:
```
OrchardCore.Workflows.Helpers.DictionaryExtensions.GetValue<TValue>(IDictionary<string, object> dictionary, string key) in DictionaryExtensions.cs
24. return (TValue)value;

OrchardCore.Contents.Workflows.Activities.ContentActivity.GetContentAsync(WorkflowExecutionContext workflowContext) in ContentActivity.cs
138. content = workflowContext.Input.GetValue<IContent>(ContentEventConstants.ContentItemInputKey)

OrchardCore.Contents.Workflows.Activities.ContentEvent.CanExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in ContentEvent.cs
30. var content = await GetContentAsync(workflowContext);

OrchardCore.Workflows.Services.WorkflowManager.RestartWorkflowAsync(WorkflowType workflowType, IDictionary<string, object> input, string correlationId) in WorkflowManager.cs
335. if (!await activityContext.Activity.CanExecuteAsync(workflowContext, activityContext))

OrchardCore.Workflows.Controllers.WorkflowController.Restart(long id) in WorkflowController.cs
287. await _workflowManager.RestartWorkflowAsync(workflow, workflowType);

OrchardCore.Workflows.Controllers.WorkflowController.Restart(long id) in WorkflowController.cs
290. }
```

### Expected behavior
The instance is restarted and runs without error.

**Comment by Piedone** [comment]
This looks like a STJ migration issue, what do you think, @MikeAlhayek @sebastienros?

Note that this is a `ContentActivity` issue. I tried restarting workflows with other start events and they worked.

**Comment by MikeAlhayek** [comment]
@BenedekFarkas  I did a quick look. I think we need to modify the following extension by adding 

```
services.AddJsonDerivedTypeInfo<TActivity, ContentActivity>();
```

But should first check to see how the JSON was previously saved to ensure we are using the correct base type.

https://github.com/OrchardCMS/OrchardCore/blob/c75ed73353d0744b1855e2007862bf89ad42d493/src/OrchardCore/OrchardCore.Workflows.Abstractions/Helpers/ServiceCollectionExtensions.cs#L12

Are you able to test it?

**Comment by Piedone** [comment]
This reproduces with `main` with a newly created workflow too, so it's not a problem with previously existing data.

**Comment by BenedekFarkas** [comment]
When I opened the issue I was running the latest main commit and with a fresh setup.
I tried again on the current latest commit (77c69c6201e1b7e932c6fc2af263ec7b4387f44d), but with a modified version of Mike's suggestion, because `OrchardCore.Workflows.Abstractions` cannot reference `ContentActivity` (because it's in `OrchardCore.Contents`), so instead I added

`services.AddJsonDerivedTypeInfo<ContentCreatedEvent, ContentActivity>();`

after

https://github.com/OrchardCMS/OrchardCore/blob/77c69c6201e1b7e932c6fc2af263ec7b4387f44d/src/OrchardCore.Modules/OrchardCore.Contents/Workflows/Startup.cs#L17

but the result is the same.

**Comment by MikeAlhayek** [comment]
@BenedekFarkas Can you please try `Activity` instead of `ContentActivity`?

**Comment by BenedekFarkas** [comment]
> @BenedekFarkas Can you please try `Activity` instead of `ContentActivity`?

Yeah, I tried that too, but forgot to mention it - same result.
