### ISSUE TITLE
Some media file names break liquid resize_url

### ISSUE THREAD

**Issue by bashuss** [OrchardCMS/OrchardCore#15423]
### Describe the bug

1. OC Version 1.7
2. Images in the media library that contain a space (" ") in the name seem to break the resize_url feature.
3. Renaming the file with "-" instead of " " makes it work again.
4. The disfunction with " " still delivers an image derived from the original source, but not the requested one. So this may be a problem of accessing the correct cached resized image.

Easy workaround - the problem is, that you need to find out the reason, before you can fix it. Took me while.

### To Reproduce
1. upload a file "anyname 01.jpg"
2. access it by a `<picture>`-tag giving several different resized versions of the url by liquid `| asset_url | resize_url` - in my case this code:
```
{% assign imgPath = "anyname 01.jpg" %}
<picture>
  <source media="(min-width:1200px)" srcset="{{ imgPath | asset_url  | resize_url: width:1200, height:1200, mode:MAX }}" />
  <source media="(min-width:992px)" srcset="{{ imgPath | asset_url  | resize_url: width:992, height:992, mode:MAX }}" />
  <source media="(min-width:768px)" srcset="{{ imgPath | asset_url  |  resize_url: width:768, height:768, mode:MAX }}" />
  <source media="(min-width:576px)" srcset="{{ imgPath | asset_url  | resize_url: width:576, height:576, mode:MAX }}" />
  <img src="{{ imgPath | asset_url  | resize_url: width:420, height:420, mode:MAX }}" alt="myImage" />
</picture>
```
3. Resize the window, so the different sources of <picture> are shown.
4. In my case, it was always the same size - it was the 420px size.
5. Changing the filename to "anytime-01.jpg" in media library and code fixed the behavior

### Expected behavior
All file names accepted in the media library must work with resize url.

**Comment by sebastienros** [comment]
Maybe some url encoding is necessary in one of these filters
