### ISSUE TITLE
Add BBCode implementation

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1542]

**Comment by sebastienros** [comment]
can you give some example? Why not liquid?

**Comment by Jetski5822** [comment]
I can give tests and code!

**Comment by Jetski5822** [comment]
Bbcode to support my existing stack. Path of least resistance when moving across

**Comment by sebastienros** [comment]
Doesn't make sense to add more things if liquid is already supported. Or as a specific extension that should not be in core.

**Comment by agriffard** [comment]
Shortcodes feature has been added.
