### ISSUE TITLE
que: create custom menu by role

### ISSUE THREAD

**Issue by lghinet** [OrchardCMS/OrchardCore#1543]
hello, 
i want to render different menu items, on the frontend, by user role

i tried implementing `inavigationprovider `using my module permissions,
but that worked only for admin menu
any ideas?
thanks

**Comment by lghinet** [comment]
or something similar to `Content Item Permissions` Module

**Comment by jpiquot** [comment]
Hello,

I tried to use role based layers that would include a menu widget but it did not work for me.

Regards,

**Comment by lghinet** [comment]
@jpiquot  something like this ? 
http://www.c-sharpcorner.com/blogs/orchard-cms-role-based-menu 
have you found any solutions ?

**Comment by jpiquot** [comment]
Yes, like the described method in the link you gave. But it did not work for me.
I am sure its not the good way but for the moment I use this in my layout :
```
               @if (User.IsInRole("Operator"))
                {
                    <menu alias="alias:operatormenu" cache-id="operatormenu" cache-duration="00:05:00" cache-tag="alias:operatormenu" name="operatormenu" id="operatormenu" />
                }
               else ….

```

**Comment by sebastienros** [comment]
You can also use Widgets with custom layers for roles.
