### ISSUE TITLE
CodeRabbit for AI code reviews

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15439]
**Attention, contributors:** See https://github.com/OrchardCMS/OrchardCore/issues/15439#issuecomment-2073645591.

### Is your feature request related to a problem? Please describe.
PRs usually sit open for too long (related: https://github.com/OrchardCMS/OrchardCore/issues/15029), partially due to nobody coming to review earlier.

### Describe the solution you'd like
We could try [CodeRabbit](https://coderabbit.ai/), which is an AI code review bot: it uses ChatGPT and perhaps other similar LLM tools to provide code review comments. Additionally:

- You can have a discussion with it. 
- Tt's capable of learning the habits of a project.
- When there's an issue linked, it can verify whether the PR addresses the issue.
- It can summarize the changes of a PR.
- Reviews are done either automatically or on-demand (requested with a comment).
- It's free for open-source projects.

For a while now we at Lombiq tested it on a couple of repositories. It's a mixed bag, with perhaps 50-50 useful and useless comments, but the experience varies greatly PR by PR. Some examples:

- [Useful comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/649#discussion_r1443087533).
- [Mixed bag for the whole PR](https://github.com/Lombiq/Helpful-Libraries/pull/231).
- [Mostly useful comments](https://github.com/Lombiq/UI-Testing-Toolbox/pull/216#pullrequestreview-1799255257)
- [No actionable comments despite enough code changes](https://github.com/Lombiq/GitHub-Actions/pull/302#pullrequestreview-1828069907)

So, I'm not entirely convinced, but we could try if it's useful for us and helps with reviews, or it's more like noise.

- [x] Set it up first just from the CodeRabbit UI so it can be tested immediately.
- [x] Once we figured out how to configure it, move the config to a file. See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/662/files for a good starting point.
- [x] Document it for contributors that you'll get AI reviews, and take them the same as human reviews. See https://github.com/OrchardCMS/OrchardCore/issues/15029 for contribution docs too.

This will throw off our [community metrics](https://github.com/OrchardCMS/OrchardCore/issues?q=is%3Aopen+is%3Aissue+label%3A%22community+metrics%22) a bit, since the time to first reply for PRs will be down to a few minutes, so we won't be able to track the time to human reviews (and the useful remaining metric will be time to close). Also, if as a reviewer you scan for PRs to review by looking at the number of comments (as an indicator that somebody else reviewed already) then that won't apply anymore. Using the ["No reviews" filter](https://github.com/OrchardCMS/OrchardCore/pulls?q=is%3Apr+is%3Aopen+review%3Anone) can be appropriate, but a "review" here is a changes requested/approved flag, what some people don't use during review (but they just comment).

### Describe alternatives you've considered
Perhaps there are other such tools that we can check.

**Comment by MikeAlhayek** [comment]
It would be nice to give it a try. Are you going to implement it to see how it does?

**Comment by Piedone** [comment]
Sure, it's just a few minutes.

**Comment by Piedone** [comment]
I've set it up, as an experiment for now: all non-draft PRs will get CodeRabbit review when opened, and you can ask it to review existing PRs too with `https://github.com/coderabbitai review`. If you think that CodeRabbit is annoying, or otherwise the feedback it provides under pull requests is not worth it, then **please add a comment below**!

**Core contributors:** You should be able to log in under https://app.coderabbit.ai/ with your GitHub account and see the OC repo settings. But this shouldn't be necessary going forward, since CodeRabbit can also be configured from code, what I did under https://github.com/OrchardCMS/OrchardCore/pull/15813.

**Comment by Piedone** [comment]
The bot comments don't skew the PR metrics, since they're excluded, only human replies count for "Time to first response": https://github.com/OrchardCMS/OrchardCore/issues/15929

**Comment by Piedone** [comment]
Please vote: https://github.com/OrchardCMS/OrchardCore/discussions/15935.

**Comment by Piedone** [comment]
I've disabled automatic reviews for now, but am waiting a bit more on https://github.com/OrchardCMS/OrchardCore/discussions/15935.

**Comment by hishamco** [comment]
CodeRabbit is good and bad, sometimes I find it annoying rather than it helps someone :)

**Comment by Piedone** [comment]
Yeah, same.

**Comment by MikeAlhayek** [comment]
I am okay with keeping it if we trigger it manually.

**Comment by hishamco** [comment]
Sometimes the suggestion is excellent, thanks for having this experiment, we can leave before releasing `2.0` until we get more feedback then we can decide

**Comment by Piedone** [comment]
I've finalized the config and docs under https://github.com/OrchardCMS/OrchardCore/pull/15813, then, please review. It's off by default but available.
