### ISSUE TITLE
No required field identification in admin and inconsistent error messages

### ISSUE THREAD

**Issue by xtomas** [OrchardCMS/OrchardCore#15434]
### Describe the bug
* content fields and some parts added to to content type, can be set as required, but there is no visualization before submitting changes
* validation error messages for required fields has inconsistent text messages (some contains dot at the end, some don't, some are using '' for value some has explicit value name in the text
* validation error messages are included in validation summary only, and not under the required field, but for example in TitlePart is everything correct

### To Reproduce
1. Make some text field, date filed, numeric field, title part, etc. required on some content type
2. Click on create new item of modified content type
3. See validation summary and required fields UX behavior

### Expected behavior
* all error messages should be written in the same format and text like for example: Please add value for '{0}', this should be rewritten also in localizations...
* at least some css class should be added on all required fields label to be able to identify required fields in the content item form
* required validation messages should be displayed under each validated field

### Screenshots
I've created Article content type with required TitlePart, Perex, Image media field and taxonomy fields Consumers and Topics.

On the screenshot bellow you can see variable validation messages, no validation messages under inputs and red border only on some fields (nothing on taxonomy fields)

![c2e9c327-77b7-46b3-bdc9-9532c395a7e6](https://github.com/OrchardCMS/OrchardCore/assets/10938220/fd687ae6-aee1-46bf-bcec-64bd5b05473e)

### Solution?

I think it's easy to add css required class into edit view for all required-able files using @Orchard.GetLabelCssClasses and PartFieldDefinition.GetSettings<T> with required identification accessible inside view. Addition of validation messages under fields inputs is also possible for most of fields. Only in taxonomy field there is some vue.js component and it does not work for me yet. Red borders can be I think also added. Textation can be also rewritten in same way.
I've tried to use some overrides inside custom theme but I find it difficult to maintain in the future because of new versions, behavior... I think it will be better to have it out of the box.

**Comment by Skrypt** [comment]
I think the validation is there for each of these Content Fields but when it throws it highlights only the first element that needs to be fixed while it should display all of the faulty ones.

**Comment by xtomas** [comment]
I've tested it now and all text fields marked as required are highlighted (currently selected one tab with more required text fields). Note that this is my testing overriden version views version with validation messages under text field inputs.

![Screenshot 2024-03-01 at 17 22 52](https://github.com/OrchardCMS/OrchardCore/assets/10938220/ac975ee1-40d4-4990-a96f-3749b8da2b02)

**Comment by sebastienros** [comment]
> Note that this is my testing overriden version views version with validation messages

Is this something you could provide as a PR if you think that won't break any feature.

**Comment by xtomas** [comment]
> > Note that this is my testing overriden version views version with validation messages
> 
> Is this something you could provide as a PR if you think that won't break any feature.

Hello, yes I will try to prepare PR.

**Comment by xtomas** [comment]
> > > Note that this is my testing overriden version views version with validation messages
> > 
> > 
> > Is this something you could provide as a PR if you think that won't break any feature.
> 
> Yes, I will try to prepare PR.

Hello @sebastienros, I've created my local feature branch based on main in my local git clone, but I'm not able to push it into orchard core repository to create pull request.

![image](https://github.com/OrchardCMS/OrchardCore/assets/10938220/18cf8837-3b75-4950-990d-b8240a8d6657)

**Comment by sebastienros** [comment]
Contributions to oss projects are done in forks
