### ISSUE TITLE
It is incorrect display when editing home page, there is a error "net::ERR_CONTENT_DECODING_FAILED" in console.

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#15455]
It is incorrect display when editing home page, there is a error "net::ERR_CONTENT_DECODING_FAILED" in console.

![image](https://github.com/EtchUK/Etch.OrchardCore.Widgets/assets/51013754/c8763c50-39ab-4535-a95d-248af90413f2)

serveral action icon don't display:

![image](https://github.com/EtchUK/Etch.OrchardCore.Widgets/assets/51013754/bfafc94c-f660-485d-b634-7148c25781a7)

**Comment by sebastienros** [comment]
Is this with the main branch? If so then it could mean there is an issue with JSON serialization.

**Comment by effapp** [comment]
> Is this with the main branch? If so then it could mean there is an issue with JSON serialization.

Yes, It is main branch. This error came up when editing page, it is correct when displaying page.

**Comment by sebastienros** [comment]
I could not reproduce the error. Can you share some repro steps?

**Comment by effapp** [comment]
Hi @sebastienros ,
This error has disappeared when I downgrade OrchardCore to version 1.7.2
