### ISSUE TITLE
Create Feature Profile doesn't work on the latest preview

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#15451]
### Describe the bug

Looks like it creates a new feature profile but doesn't store it. (I've noticed this while validating `Lombiq.Hosting.Tenants.FeaturesGuard` in anticipation of OC 1.9.)

EDIT: Also forgot to mention that even if I add a feature profile [from a setup recipe](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/8594ac72f0c65d61a8edc07a6eb1ca914116bf22/src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json#L220-L244) it doesn't show up in the Feature Profiles list.

### To Reproduce

1. Set up a new site.
2. Enable _Tenants_ and _Tenant Feature Profiles_ features.
3. Go to Admin > Multi-Tenancy > Feature Profiles.
4. Click "Add Feature Profile" button.
5. Give it any name and copy the example rules from the text under the Rules field.
6. Click "Save and Continue".
7. Get redirected to a Not Found page and there are no error logs.
8. Go back to the Feature Profiles page and the list is empty.

### Expected behavior
It should create and store a new Feature Profile.

### Screenshots

![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/8aceb8d4-9d59-4dd2-80f6-cb3920442516)
![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/b6686960-36b4-4b79-b934-0230e331468a)

Despite my initial guess, the JSON is correctly parsed:
![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/be1b9fe1-533e-4b07-b0f9-86af31e27aa8)

**Comment by MikeAlhayek** [comment]
its is a serialization issue. Fixed by #15465
