### ISSUE TITLE
SqlException when querying content items with more than 5000 item

### ISSUE THREAD

**Issue by tonydev24** [OrchardCMS/OrchardCore#15466]
### Describe the bug
When querying content items to display them in a page, if the number of items is high an SqlExecption is thrown.

### To Reproduce
1. Create a content item and fill (import) 5000 items
2. Query the items this way:
` @{
    var query = await QueryManager.GetQueryAsync("MyQuery");
    var contentItems = await QueryManager.ExecuteQueryAsync(query, new Dictionary<string, object>());
    var datasource = contentItems.Items;
}`

4. The following exception is thrown
An unhandled exception occurred while processing the request.
SqlException: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)
Dapper.SqlMapper.QueryAsync<T>(IDbConnection cnn, Type effectiveType, CommandDefinition command) in SqlMapper.Async.cs
YesSql.Store.ProduceAsync<T, TState>(WorkerQueryKey key, Func<TState, Task<T>> work, TState state)
YesSql.Session.GetAsync<T>(long[] ids, string collection)
YesSql.Session.GetAsync<T>(long[] ids, string collection)
OrchardCore.Queries.Sql.SqlQuerySource.ExecuteQueryAsync(Query query, IDictionary<string, object> parameters)
OrchardCore.Queries.Sql.SqlQuerySource.ExecuteQueryAsync(Query query, IDictionary<string, object> parameters)
AspNetCoreGeneratedDocument.Views_Widget_InstrumentDataGrid.ExecuteAsync() in Widget-InstrumentDataGrid.cshtml
var contentItems = await QueryManager.ExecuteQueryAsync(query, parameters);

**Comment by douwinga** [comment]
I think this is an issue with the Return Documents option of the SQL queries
![image](https://github.com/OrchardCMS/OrchardCore/assets/11961383/8b380c29-9e5f-4af8-b288-5a55e2457f6a)

If your query finds more than 2100 content items you will hit this error. I believe this is due to the `ContentManager.GetAsync` having more than 2100 content item ids and it therefore generating more than 2100 sql parameters since each content item id is a parameter.

**Comment by douwinga** [comment]
The `ContentManager` likely has the same issue with `GetAsync` when you pass on more than 2100 content item IDs.

**Comment by douwinga** [comment]
Without it checked though, you won't get the full content items. So unchecking that doesn't fix the bug

**Comment by tonydev24** [comment]
Ok i'll keep it open for the team to check

**Comment by sebastienros** [comment]
Use paging
