### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by JeanCollas** [OrchardCMS/OrchardCore#1546]
1st of all: is there a discussion channel/forum/... to ask questions about Orchard?

I understood there were many issues related to localization, however it is not clear to me yet how everything works for each of them, or how it is planned to be implemented:
- Taxonomy (probably the main issue)
- General UI (messages, error messages, ...)
- Modules
- Content

Is there a way to clarify this? :)

I have a website I consider to migrate to Orchard.

On my side, I handle everything with keys:
- every text has a key + a default translation, defined in a dictionary at the top of each pages (default translation because I have seen too many website failing to translate and displaying keys instead of texts)
- just after defining these default translations, if the culture is not English, the dictionary is passed to a method which loads the translation for all the keys (if not available, the default text is kept), the default method is implemented to load from DB
- every text from the page is rendered using T("Key", params) or in some cases T_html("",) or T_js("",) as they require different encodings.

This behavior is defined in a base page that is used for every page of my site (called in _ViewImports `@inherits MyBasePage<TModel>` )

I could also go for a lazy loading of translations to make things faster but I don't need it yet.

Thanks in advance for your clarifications!

**Comment by khoshroomahdi** [comment]
Orchard core use PO file for localization.

**Comment by PinpointTownes** [comment]
> 1st of all: is there a discussion channel/forum/... to ask questions about Orchard?

Sure. You can join us on https://gitter.im/OrchardCMS/OrchardCore.

**Comment by JeanCollas** [comment]
@PinpointTownes Thanks, I did not find it when searching for it. Now I see the icon on it, but it may worth mentioning it more explicitly in the readme.md.

**Comment by sebastienros** [comment]
I'd say that we already support everything you mentioned in your description, but the JavaScript specific encoding. We expose a `T[]` in our base view page, and you can also resolve one from strings only. I will look into the JS one as it's an interesting idea, which could be solved by using a custom encoder, but so far we haven't had any issue with what we are using.

**Comment by sebastienros** [comment]
I actually like the idea of a JS localizer. I will talk about it with the PMs in the aspnet team.

**Comment by sebastienros** [comment]
Note about JS translation, the recommendation is to use hidden html tags, the Html localizer, and read the value from JS.

**Comment by hishamco** [comment]
I think this issue is more generic, AFAIK there 're many issues filed for each point in the first thread, so I think we need to close this while there 's one for each
