### ISSUE TITLE
Better razor pages support

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1547]
# Authorize
```
services.Configure<RazorPagesOptions>(options =>
            {
                options.Conventions.AddModularPageRoute("/ModuleId/Pages/Test", "test");
// The next line doesn't work.
                options.Conventions.AuthorizePage("/test");
            });
```

# Recipes
HomeRoute should support razor pages.

**Comment by agriffard** [comment]
Isn't it possible to set a Razor page as the HomeRoute? With a Recipe Step?

**Comment by sebastienros** [comment]
@jtkech how can we set a razor page with HomeRoute?

@alberthajdu what is `options.Conventions.AuthorizePage("/test");` supposed to do?

**Comment by jtkech** [comment]
`Autoroute` map routes to content items and just provides a way to define an home route through settings. Then `HomeRoute` is a concrete implementation that uses these settings to map the home route to a content item.

So we would need another feature to define an home page differently, or update `Autoroute` to have additional options, and then another feature to map these settings to a razor page by updating the route values e.g with the `page` specific value, the area value and so on, or update `HomeRoute` to use these additional options.

That said we can already define a razor page as an home page by using `@page "/"`

Or through the following mvc helper as commented in the demo module

                // This declaration would define an home page
                //options.Conventions.AddAreaPageRoute("OrchardCore.Demo", "/Hello", "");
