### ISSUE TITLE
The `OrchardCore.Cors` module seems to be broken. 

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#15485]
The `OrchardCore.Cors` module seems to be broken. 
After adding the following code in Program.cs, the cross-domain access works fine

```C#
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(builder =>
    {
        builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader();
    });
});
....
app.UseCors();
```

**Comment by hyzx86** [comment]
relate ：https://github.com/OrchardCMS/OrchardCore/issues/15416#issuecomment-1988259635

**Comment by hyzx86** [comment]
I remember this was a problem a year ago, but it was fixed, and now it's back

**Comment by hishamco** [comment]
Could you please submit a PR?

I remembered there was a PR related to CORS, I'm not sure if it's the main reason for this issue

**Comment by hyzx86** [comment]
> Could you please submit a PR?
> 
> I remembered there was a PR related to CORS, I'm not sure if it's the main reason for this issue

Sorry, it was hardcoded in my 'Program.cs' file and I haven't found the real reason yet.
Probably because of the order in which modules are loaded.

**Comment by hishamco** [comment]
I'm not sure if it's related to #15486, @hyzx86 could you please write the steps to reproduce, I might investigate on this

**Comment by hyzx86** [comment]
> I'm not sure if it's related to #15486, @hyzx86 could you please write the steps to reproduce, I might investigate on this

I'm trying to locate the problem,
Initially I got the package from Nuget and found that the cross-origin feature wasn't working,
Then I packaged from the source code locally and replaced the dll file in my native solution, the problem still existed.
Notice that your code seems to be tweaking the bundling process, so this issue probably has nothing to do with the bundling process

**Comment by hyzx86** [comment]
Using the following recipe test, it turns out that this problem does not exist in the OC source code, the problem may be in my custom code, I need to check where is incompatible with the existing code.

Here is my recipe 
[cors-domaintest.Recipe.json](https://github.com/OrchardCMS/OrchardCore/files/14562346/cors-domaintest.Recipe.json)

**Comment by hishamco** [comment]
Happy to hear that
