### ISSUE TITLE
The Cors module supports ExposedHeaders

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#15499]
### Is your feature request related to a problem? Please describe.

Asynchronous file download scenarios require the api to include the file name in the response header.
Just like `attachment; filename="myfile.xlsx";`

Because some scenarios may need to generate download files through user submitted data, but this request is a cross-domain request initiated through WebApi.
Then in this case, do we hardcode `ContentDisposition` for the default policy directly after the user has enabled the Cors module, or provide an option for the user to fill in,  just like the `Origin` property?

### Describe the solution you'd like

My recommendation is to configure directly to the default policy

```C#
policy.ExposedHeaders.Add(HeaderNames.ContentDisposition);
```

### Describe alternatives you've considered

Providing a drop-down menu or text box for the user to choose from may increase the cost of development and learning.
Or provide a Json version for the user to configure directly

**Comment by sebastienros** [comment]
Are there any existing APIs in Orchard that generate files and don't set this header?

**Comment by hyzx86** [comment]
> Are there any existing APIs in Orchard that generate files and don't set this header?

Probably not, because most OCs are currently used directly through MVC pages, so they are of the same origin, and this configuration needs to be configured only for cross-domain requests

**Comment by hyzx86** [comment]
Indeed, it should be implemented in custom code
