### ISSUE TITLE
Cannot clone the repository

### ISSUE THREAD

**Issue by mmadushanka** [OrchardCMS/OrchardCore#15508]
Hi Team,

I am trying to clone OrchardCore CMS for developing a CMS website,
But I cannot clone the repository in git hub.

Please help me to do that.
I was trying that using different internet connections, but didn't work.

Check this screenshot

![Uploading Screenshot 2024-03-14-Cannot clone the repositoty.jpg…]()

But I can clone some other CMS platforms.
I can download CoFoundry CMS here properly. Why I cannot do that for OrchardCore
Check this screenshot

![Screenshot 2024-03-14-Can clone some other CMS repsotitories](https://github.com/OrchardCMS/OrchardCore/assets/13145064/a14e5968-a5cf-4bed-af1d-552bbd82894d)

What is the reason behind this?

Please advise me.

Regards,
Manula

**Comment by hyzx86** [comment]
Sorry, this may be a network problem for you. If it is confirmed that it is not a network problem, you can contact Github for official support. It is not a problem with this repository.

**Comment by hyzx86** [comment]
I used a vpn and had no problems

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/b4e9fd7f-a79a-4ccd-9cd7-a33070837c86)

**Comment by mmadushanka** [comment]
Hi

Can I clone this without a VPN ?

Or it is needed a VPN to download or clone this

**Comment by hyzx86** [comment]
Where are you from and you can search for github accelerated proxies on the web in your country
jsut like https://mirror.ghproxy.com/

**Comment by mmadushanka** [comment]
Can you give me English  version of this

**Comment by hyzx86** [comment]
No, please search by yourself. I don't know your network
Please close this issue
