### ISSUE TITLE
Inconsistent JObject.SelectNode() behavior and feature loss

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#15505]
### Describe the bug

I have a few concerns with the new `JObject.SelectNode()` extension method:

If you try to use it on a content part's `Content` property, it won't work unless you re-serialize the JSON object first, e.g.:
```csharp
var content = (JsonObject)contentElement.Content;
content.SelectNode(path); // This is null.
JsonSerializer.SerializeToNode(content).SelectNode(path); // This is not null.
```

Also you can't chain `SelectNode` calls, the second call will still search from the same position, e.g.:
![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/feae5df1-1a00-4f3a-86f4-2a77e63680a3)

I think when you query a `JsonObject`, it tries to query from its document root instead of the current element. This is unexpected.

Finally, I'm not sure if anyone is affected, but after the migration to STJ we have lost full compliant JSONPath query support. The documentation of `JObject.SelectNode()` extension method [claims that it searches using "a JSON path"](https://github.com/OrchardCMS/OrchardCore/blob/50583b0644fe90f0a7253c78885504c910c4175a/src/OrchardCore/OrchardCore.Abstractions/Json/Nodes/JObject.cs#L89), however this is misleading because it's compliant with [the JSONPath specification](https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html). An example of a query that should work but doesn't (using the same JSON as above):

```csharp
var data = JsonNode.Parse("{\"SelectedContentItem\":{\"ContentItemIds\":[\"48yrgcwkhv7hkwarvtzpw3ccms\"]},\"Name\":\"My Content\"}");
data.SelectNode("SelectedContentItem.ContentItemIds"); // works, result: [ "48yrgcwkhv7hkwarvtzpw3ccms" ]
data.SelectNode("$.SelectedContentItem.ContentItemIds"); // works, result: [ "48yrgcwkhv7hkwarvtzpw3ccms" ]
data.SelectNode("$..ContentItemIds"); // doesn't work, result is null but it should be the same as above
```
You can verify that the last one should work using the [JSONPath Online Evaluator](https://jsonpath.com/):
![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/1d32f137-b6f1-42b7-aaa2-388e39824a9e) Also it works with Newtonsoft:

![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/cb74eef3-1283-4009-9e77-721891a603a2)

### Expected behavior

- `SelectNode` should query from the current element.
- Ideally it should keep supporting full JSONPath.

### Suggestion

Beyond fixing `JObject.SelectNode` to search from the current node, the documentation should be updated:
- The documentation comment I linked above should include a `<remarks>` section explaining what is and what isn't supported by the current implementation.
- The 1.9 release notes should mention this breaking change in [the "Drop Newtonsoft.Json Support" section](https://github.com/OrchardCMS/OrchardCore/blob/50583b0644fe90f0a7253c78885504c910c4175a/src/docs/releases/1.9.0.md#drop-newtonsoftjson-support).

Consider if there is a JSONPath library we can use instead of a homebrew implementation. I haven't used it yet, but [JsonPath.Net](https://www.nuget.org/packages/JsonPath.Net/0.1.3) of the [json-everything](https://github.com/gregsdennis/json-everything) project might be suitable? It's for STJ, MIT licensed and it seems to be actively maintained.

**Comment by hyzx86** [comment]
Good catch, 
@hishamco  maybe we can add some method on  `JsonDynamicObject` class to resolve some relation problems

**Comment by hishamco** [comment]
@hyzx86 if your PR fixes both issues, then I need to close my PR then

**Comment by hyzx86** [comment]
> @hyzx86 if your PR fixes both issues, then I need to close my PR then

Ok ， but let me chek first.

**Comment by hyzx86** [comment]
@hishamco , There seems to be a problem with the logic of the remove menu on the main branch, so let me merge your branches

**Comment by hyzx86** [comment]
Or you can merge your branches first, and my branch can solve another problem

**Comment by sebastienros** [comment]
Can you @sarahelsaig / @hyzx86 fix the SelectNode() behavior by using JsonPath.Net ?

**Comment by sarahelsaig** [comment]
I think so. I will give it a try.

**Comment by sarahelsaig** [comment]
@sebastienros I've replaced the SelectNode() internals with JsonPath.Net (see PR #15524).
Now queries work as I'd expect and it's less code for us to maintain. :)
