### ISSUE TITLE
Document Site object properties

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1551]
Seems like we are missing the list of available properties on the `Site` object in liquid

http://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Liquid/README/#site

**Comment by jeremycook** [comment]
I'll update it. Should I talk about the `ISite` interface or the `SiteSettings` class?

> Gives access to the current site settings, e.g `Site.SiteName`.
> 
> The following properties are available on the `SiteSettings` object.
> 
> [I'll add the table of properties here]

Here's the rendering code. Presumably site.GetType() resolves to SiteSettings.

```csharp
public async Task RenderingAsync(TemplateContext context)
{
    var site = await _siteService.GetSiteSettingsAsync();
    context.MemberAccessStrategy.Register(site.GetType());
    context.LocalScope.SetValue("Site", site);
}
```

**Comment by sebastienros** [comment]
No need for mentioning `ISite` or `SiteSettings`. Using `SiteSettings` properties is fine.
Not sure how we expose it in Razor, if not then a line on resolving `ISite` is good.

**Comment by jeremycook** [comment]
Pull #1555
