### ISSUE TITLE
Content parts with get-only collections can't retain their values (JOptions configuration)

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#15533]
### Describe the bug

Right now if your content elements contain any get-only collections, those don't get populated by System.Text.Json. they are just left empty. This is an unintended breaking change compared to Newtonsoft.

Why have get-only collection props in the first place? See the explanation in the static code analysis warning [CA2227: Collection properties should be read only](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227).

### To Reproduce

1. Have a model that contains a get-only collection property, such as [this one](https://github.com/Lombiq/Orchard-Content-Editors/blob/6a34914d01a82401ad77b0a39145601a704ef092/Lombiq.ContentEditors/Models/AsyncEditorPart.cs#L6).
2. Add it to a content type, create and save a content item with some strings in the collection property.
3. Load it back from the DB.
4. Observe that the collection is now empty

### Expected behavior

In Newtonsoft get-only collections (lists, dictionaries, etc) are automatically populated (see mode on the comparison [here](https://github.com/dotnet/runtime/issues/78556#:~:text=Suggestion%20for%20System.Text.Json%20with%20comparison%20with%20Newtonsoft.JSON)).

### Solution

[`JOptions.Base`](https://github.com/OrchardCMS/OrchardCore/blob/a2d529ec5309ad9478222c75182d265ee4c57e69/src/OrchardCore/OrchardCore.Abstractions/Json/JOptions.cs#L13) should contain the configurations:
- `PreferredObjectCreationHandling = JsonObjectCreationHandling.Populate`
- `ReferenceHandler = null`

Note: I'm not entirely sure what the second one means, but it's necessary otherwise the site crashes with the message "System.InvalidOperationException: JsonObjectCreationHandling.Populate is incompatible with reference handling." ([see](https://github.com/dotnet/runtime/blob/0935105e91450a1bad02b5b2f83be52bea2bcf59/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs#L560)). I suspect it's about handling circular references, but I'm not sure. If anyone has some insight, please chime in.

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/51f7ed41-c0eb-4c34-89ab-93468b977d64)
A minimal sample (not using OC) to show the problem (the "B.Items") and solution (the "B.Items (with options)").

![image](https://github.com/OrchardCMS/OrchardCore/assets/4007293/f4c701e3-1884-4a6b-8d45-22afa7b6c32e)
A real life example in [Lombiq Content Editors for Orchard Core](https://github.com/Lombiq/Orchard-Content-Editors).

**Comment by MikeAlhayek** [comment]
Yes. As a workaround, add `init;` to the property and it will get populated. This is also documented in the 1.9 release. Your fix is good, but not sure if it has impact to other options.
