### ISSUE TITLE
Rename Themes to Templates

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1554]
Not in the code but in the UI for the recipes and the project names.

The idea is that we are not creating Themes to apply on any site, but actual website recipes, which happen to have a dedicated set of style. These websites can be reused, altered, but the content configuration (content definition, settings) is specific to how it is rendered. For instance the Clean Blog theme we are using is expecting a subtitle in a Blog Post type. This as a theme would not make sense and break any other site that is using it.

This would also encourage people to create more templates to tackle specific business needs. And also allow for more customization of these templates, like customizing header images, colors, ...

**Comment by sebastienros** [comment]
Another example, the Agency "template" has a form in the footer, we would then create a Workflow as part of the recipe to handle it. 

Also each template would come with a tutorial on how it was built.

**Comment by khoshroomahdi** [comment]
I agree. It's better to be evey thing in this section like layout theme editor and...

**Comment by agriffard** [comment]
Now that Theme, Template and Recipe are explained in the glossary, I think it can be closed.
