### ISSUE TITLE
Add optional target='_blank' to the Menus and AdminMenus

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#15541]
In some cases we need to always open external links in new pages

**Comment by rjpowers10** [comment]
A way to do this directly in Orchard Core may be nice, but in the meantime you can do something like this in your code through a shape table provider. This is how I added `target='_blank'` to certain admin menu items.

```cs
public class Shapes : IShapeTableProvider
{
    public void Discover(ShapeTableBuilder builder)
    {
        builder.Describe("NavigationItemLink__admin")
            .OnDisplaying(displaying =>
            {
                string id = displaying.Shape.Id;
                if (id == "some_menu_id")
                {
                    displaying.Shape.Attributes.Add("target", "_blank");
                }
            });
    }
}
```

**Comment by Piedone** [comment]
Do you mean to add an option for menu items to generate the anchor with target blank?

**Comment by hyzx86** [comment]
> Do you mean to add an option for menu items to generate the anchor with target blank?

Yes, the menu items of OC support external links, but we can only open them in the current window.

**Comment by MikeAlhayek** [comment]
Adding a settings will be useful where users can alternate between `_self` (default), `_blank`, `_parent`, `_top`

@hyzx86 will you submit a PR for this?

**Comment by hyzx86** [comment]
I'm thinking about how to design this interaction... 
The average user may be overwhelmed by so many options, and if a predefined drop-down menu is used, it may not be enough for developers
