### ISSUE TITLE
Yahoo Authentication

### ISSUE THREAD

**Issue by hassan123-dev** [OrchardCMS/OrchardCore#15557]
Need a feature that allows Authenticates users with their **Yahoo** Account.

Is there any quick way to implement this by re-using any existing authentication project like Github/Twitter?

[ Yahoo Oauth Guide](https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html)

**Comment by MichaelPetrinolis** [comment]
You could read how it is done for twitter (Microsoft.AspNetCore.Authentication.Twitter and OrchardCore.Twitter) and make a PR

**Comment by hassan123-dev** [comment]
I don't have any expertise on this. I was hoping that someone could implement this feature.

I am looking for an open-source CMS with Yahoo Authentication.

**Comment by hishamco** [comment]
It's good for an open-source project, you could add this feature in OCC https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules  I can guide you to implement if you have an interest

**Comment by hassan123-dev** [comment]
@hishamco 
Please share the guidelines. I will try my best.

**Comment by hishamco** [comment]
Please share an issue in OCC. Modules and let's continue there
