### ISSUE TITLE
Content shape alternate targeting a specific item with ContentItemId 

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15572]
### Is your feature request related to a problem? Please describe.
You can override the `Content` shape of a given content item with the `Content__[Id]` alternate, which is added in [`OrchardCore.Contents.Shapes`](https://github.com/OrchardCMS/OrchardCore/blob/d524386b2f792f35773324ae482247e80a944266/src/OrchardCore.Modules/OrchardCore.Contents/Shapes.cs#L37). This is useful, but since it uses `ContentItem.Id`, i.e. the numeric ID of the item in the DB, it's not portable: an override will only apply with one specific DB, and if you move the content item (like import it) to another DB, it won't.

### Describe the solution you'd like
Add a new alternate, `Content__[ContentItemId]`, that uses the alphanumeric and portable `ContentItem.ContentItemId`. Also document it under https://docs.orchardcore.net/en/latest/docs/reference/modules/Templates/#content-templates.

We can keep the current alternate for backward compatibility, but it shouldn't really be used, so let's keep it undocumented.

### Describe alternatives you've considered
Changing the existing alternate, but that would be a breaking change.

**Comment by sebastienros** [comment]
We had that in orchard 1, why not.

**Comment by Piedone** [comment]
Ooops, closed by mistake.

**Comment by MichaelPetrinolis** [comment]
Is this something that will be included in v2.0.0 ?

**Comment by Piedone** [comment]
Only if you contribute it ;).

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/2866.

**Comment by Piedone** [comment]
We have Alias and Autoroute alternates now, which are generally better approaches. See the discussion under https://github.com/OrchardCMS/OrchardCore/pull/16679.
