### ISSUE TITLE
Remove usage of <section> for Page

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1559]
Most website template already use this tag, and having it for flow pages messes up with the theme style.
I suggest we use `<div class="flow">`

**Comment by sebastienros** [comment]
The more global issue is that our front-end module views should not interfere with the website templates we are building.

Examples:
- Login/Register views
- Flow/Widget templates
- Content template

**Comment by jeremycook** [comment]
1. I'm not sure I follow. Are you saying there are themes that specify CSS for the section element, and that's causing undesirable side-effects? If that is the case I would suggest that those themes not style the section element, or if they do style section then they should limit its affect by scoping it somehow. Perhaps a specific example would help me understand.

Supposing I understand correctly, here is my suggestion for theming:

Bad: `section { ... }`
OK, but can still have undesirable side-effects: `.some-scope-that-my-theme-controls section { ... }`
Best: `.my-theme-section { /* which could be applied to a section element */ }`

2. I may agree that section elements should be replaced with a div in some places in the code base, but possibly not for the same reasons.

Consider http://html5doctor.com/the-section-element/

**Comment by sebastienros** [comment]
Here is the example in the Agency theme https://github.com/BlackrockDigital/startbootstrap-agency/blob/master/scss/_global.scss#L33

I was trying to create a Page in OC, which uses widgets. It creates a `<section>` for each widget, but because of this style, there is a huge gap between them. So maybe instead of expecting the themes to use isolated styles for section, we could be ourselves isolated, and create the specific OC css rules in the theme when necessary. In this case, using a simple div with a class would have worked OOB.

**Comment by sebastienros** [comment]
Another related issue, when some modules render a full view, like the Login page, we don't have a convention to wrap the content in specific tags, and I think it would be useful as a theme usually needs some specific style to mark the content. In the case of Agency we need to wrap the single content in a section and boostrap divs. We can't do that globally as some pages need multiple sections.

For instance in the case of Agency, what we need to generate

Login.cshtml

```
<section id="service">
   <div class="container">
     <div class="row">
       <div class="col-lg-12">
         login form
  </div>
</section>
```

Home

```
<section id="service">
   <div class="container">
     <div class="row">
       <div class="col-lg-12">
         content of the section
</section>

<section id="portfolio">
   <div class="container">
     <div class="row">
       <div class="col-lg-12">
         content of the section
</section>
```

I suggest we a convention to use a specific div and class to wrap a block when we render views. This way we can customize the theme with a style that would apply the correct container styling for the block. In this case we would repro the style of section/container/row/col-lg-12 or use a mixin. This would prevent users from having to create a new Login page template completely.

**Comment by Skrypt** [comment]
There's an issue there made in that theme by assigning a padding to a HTML semantic element. They should have done something like : 

```CSS
section .specific-zone-or-page{
    padding: 150px 0;
}
```

**Comment by sebastienros** [comment]
I will file an issue on their repository

**Comment by scleaver** [comment]
Can I also add some thoughts here:

I notice that HTML produced by widgets in a flow page are quite liberally using article tags (and section tags) which is not correct use of both section and article. Widgets are best to use div unless the content specifically calls for use of special tags such as section and article tags.

For example this is the code of the text block:

```
<article class="widget widget-html-widget widget-align-justify widget-size-50 html-widget">
<div class="field field-type-htmlfield field-name-html-widget-content">
    Test
</div>
</article>
```

This is not a valid use of the article tag as this content does not encapsulate the elements of an article. A list of blog post content would be a valid use of article for instance.

It would be rare that the content block or the image widget (or most other widgets in fact) by themselves would contain the elements of an article. I think the team should to stick to more generic html tags, like div and span, unless it is semantically correct to do so. Also it would be good if tags ing general could be get too a minimum so that page source doesn't get littered with tags and classes like it tends too in other applications eg. Wordpress.

**Comment by konstrui** [comment]
So regarding this issue: how would I create a liquid override for the Flow part, to change the <section> to <div>?

**Comment by sebastienros** [comment]
You can copy the Flow shape template in your theme or web project and change what it renders.
