### ISSUE TITLE
Liquid filters and comparison stopped working after upgrade to 1.9

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/OrchardCore#15625]
### Describe the bug
Another breaking change is in our Liquid views. What stopped working:

````
{% assign my_variable_1 = "some_stuff" %}
{% assign my_variable_2 = "some_stuff" %}
{% if my_variable_1 == my_variable_2 %}
   {{ "Never here" }}
{% endif %}
````

`{% assign formated_datetime = Model.ContentItem.CreatedAtUtc | date: "%y-%M-%d" %}` this return and empty string

UNLESS a do some hacking and use the `raw` filter like so:
````
{% assign my_variable_1 = "some_stuff" | raw %}
{% assign my_variable_2 = "some_stuff" | raw %}
{% if my_variable_1 == my_variable_2 %}
   {{ "Success" }}
{% endif %}
````
`{% assign formated_datetime = Model.ContentItem.CreatedAtUtc | raw | date: "%y-%M-%d" %}`

**Comment by MikeAlhayek** [comment]
@sebastienros thoughts?

**Comment by MikeAlhayek** [comment]
@SzymonSel 
In https://github.com/OrchardCMS/OrchardCore/commit/980f322c62210d3390c8005c27bf9560fa7b996d we change the Liquid options to allow functions `new FluidParserOptions() { AllowFunctions = true }` I am wondering if that caused the issue.

Can you try using `1.9.0-preview-18130` which was the last package before that change

**Comment by sebastienros** [comment]
@MikeAlhayek I tried the fluid tests with this option and it worked. Will have to debug that in OC.

**Comment by sebastienros** [comment]
Works for me in main, @SzymonSel we need a more details repro

![image](https://github.com/OrchardCMS/OrchardCore/assets/1165805/c622117a-adbf-4e88-8ea0-9f166d1d84d0)

**Comment by SzymonSel** [comment]
Got a another one when when trying to devide integer by decimal. Not very forgiving...

I create a more detailed description shortly.

```
InvalidCastException: Unable to cast object of type 'System.Text.Json.Nodes.JsonValuePrimitive`1[System.Text.Json.JsonElement]' to type 'System.IConvertible'.

System.Convert.ToDecimal(object value)

    Stack Query Cookies Headers Routing 

    InvalidCastException: Unable to cast object of type 'System.Text.Json.Nodes.JsonValuePrimitive`1[System.Text.Json.JsonElement]' to type 'System.IConvertible'.
        System.Convert.ToDecimal(object value)
        Fluid.Values.ObjectValueBase.ToNumberValue()
        Fluid.Filters.NumberFilters.DividedBy(FluidValue input, FilterArguments arguments, TemplateContext context)
```

**Comment by MikeAlhayek** [comment]
@sebastienros I am facing the same problem with OC preview "before merging STJ"

I added a workflow that would create a content type 

```
{
   "RecordKeeper": {
      "Type": {
         "Text": "{{ Request.Form.Scenarios | escape }}"
      },
      "CaseNumber": {
         "Text":"{{ Request.Form.CaseNumber | escape }}"
      },
      "VerifiedEmail": {
         "Value": {% if Request.Form.VerifiedEmail == "yes" %}true{% else %}false{% endif %}
      },
      "PreviouslyUpdatedCustomer": {
         "Value": {% if Request.Form.PreviouslyUpdatedCustomer == "yes" %}true{% else %}false{% endif %}
      },
      "CustomerInteractedInEmailMarketing": {
         "Value": {% if Request.Form.CustomerInteractedInEmailMarketing == "yes" %}true{% else %}false{% endif %}
      },
      "HasAtLeastOnePurchase": {
         "Value": {% if Request.Form.HasAtLeastOnePurchase == "yes" %}true{% else %}false{% endif %}
      },
      "IsLessThan40": {
         "Value": {% if Request.Form.IsLessThan40 == "yes" %}true{% else %}false{% endif %}
      },
      "IsLessThan100": {
         "Value": {% if Request.Form.IsLessThan100 == "yes" %}true{% else %}false{% endif %}
      },
      "IsGreetingCard": {
         "Value": {% if Request.Form.IsGreetingCard == "yes" %}true{% else %}false{% endif %}
      },
      "IsBroken": {
         "Value": {% if Request.Form.IsBroken == "yes" %}true{% else %}false{% endif %}
      },
      "Result": {
         "Text": "{{ Workflow.Properties["actionResult"] | escape }}"
      }
   }
}
```

Assigning the Text works. But `{% if Request.Form.IsBroken == "yes" %}true{% else %}false{% endif %}` always returns `false`

**Comment by sebastienros** [comment]
3 different issues to me though. The first one I proved it was working, I will need a better repro.

The second one is a JSON conversion issue in Fluid. Could use a repro, but maybe I can try to guess how this would happen. Probably a JsonValue number is used as the input.

The 3rd one looks like a property/class no registered (allowed) in the templates.

**Comment by MikeAlhayek** [comment]
I have to look more. not sure. The following test works

```
{
    [Fact]
    public async Task RenderString_WhenComparingString_ReturnedCorrectValue()
    {
        var context = new SiteContext();
        await context.InitializeAsync();
        await context.UsingTenantScopeAsync(async scope =>
        {
            var liquidTemplateManager = scope.ServiceProvider.GetRequiredService<ILiquidTemplateManager>();
            var result = await liquidTemplateManager.RenderStringAsync("{% if IsLessThan40 == \"yes\" %}true{% else %}false{% endif %}",
                NullEncoder.Default,
                new Dictionary<string, FluidValue>() { ["IsLessThan40"] = new StringValue("yes") }
                );

            Assert.Equal("true", result);
        });
    }
```

**Comment by MikeAlhayek** [comment]
@sebastienros 
> The 3rd one looks like a property/class no registered (allowed) in the templates.

By this one are you referring to the issue I posted here https://github.com/OrchardCMS/OrchardCore/issues/15625#issuecomment-2067323387 ?

That data is coming from a form and is in `Request.Form` so there is no class to register.  In fact, I logged the data from the workflow just to confirm the expected data.

I added this to the Log Task just before creating the content item.

```
{{ Request.Form | json | append: 'CustomerInteractedInEmailMarketing >>' | append: Request.Form.CustomerInteractedInEmailMarketing }}
```

As you can see in the logs I am getting the expected value of `yes`.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/7773bf7f-9295-497d-8a6f-85149cc8d320)

So the Liquid `{{ Request.Form.CustomerInteractedInEmailMarketing }}` prints the correct `yes` value. But evaluation `{% if Request.Form.CustomerInteractedInEmailMarketing == "yes" %}true{% else %}false{% endif %}` always returns false.

**Comment by MikeAlhayek** [comment]
Okay. I think I found my issue `{{ Request.Form.CustomerInteractedInEmailMarketing }}` prints the first value in the collection from the request. However, the `Request.Form.CustomerInteractedInEmailMarketing == "yes"` would return false because the value is not a string but a collection of strings.

So changing 

```
{% if Request.Form["CustomerInteractedInEmailMarketing"] == "yes" %}true{% else %}false{% endif %}
```
to 

```
{% if Request.Form["CustomerInteractedInEmailMarketing"] contains "yes" %}true{% else %}false{% endif %}
```

fixes the problem for me. @sebastienros in this the expected results? printing `{{ Request.Form.CustomerInteractedInEmailMarketing }}` as the first value seems misleading here.

**Comment by sebastienros** [comment]
```c#
InvalidCastException: Unable to cast object of type 'System.Text.Json.Nodes.JsonValuePrimitive`1[System.Text.Json.JsonElement]' to type 'System.IConvertible'.
        System.Convert.ToDecimal(object value)
        Fluid.Values.ObjectValueBase.ToNumberValue()
        Fluid.Filters.NumberFilters.DividedBy(FluidValue input, FilterArguments arguments, TemplateContext context)
```

I need to check in Fluid how these STJ nodes get converted to FluidValue. It's possible that Newtonsoft was implementing IConvertible and not STJ.

**Comment by SzymonSel** [comment]
So I've tested this on a vanilla OC, latest nightly build.
I created a simple content type with just one field. And I created a template like so:
![image](https://github.com/OrchardCMS/OrchardCore/assets/9480863/ca068b29-0460-488b-8d9a-e3b906f78172)

![image](https://github.com/OrchardCMS/OrchardCore/assets/9480863/252a1c79-ce8d-448d-a793-108ebf5933db)

Now after a small change in the template:
![image](https://github.com/OrchardCMS/OrchardCore/assets/9480863/3d1ed350-c2d6-4e87-840e-d8ccbda5afeb)
![image](https://github.com/OrchardCMS/OrchardCore/assets/9480863/289312f7-7fc8-4bdf-9bdb-865451169ec5)

**Comment by sebastienros** [comment]
` | raw` is rendering the value, hence converting to a string, so the comparison will work.
The fact that `Value == ""` where `Value` is a DateTime is a good question though. Are you saying it's working on **1.8.3** but not **main**?

I would need to check with the Liquid language if that's expected. In a way we could assume that comparing a string to a datetime should try to compare the datetime values by parsing the string.

**Comment by SzymonSel** [comment]
Correct, it worked until the switch from `Newtonsoft.Json` to `System.Text.Json`

Oh, I don't get decived by the `DateTimeField`, the same goes for other fields and even checking the `ContentType` when comparing to string.

**Comment by sebastienros** [comment]
It's highly probable that [this PR](https://github.com/OrchardCMS/OrchardCore/pull/15816) will fix it.

Can you or @gvkries try it?

**Comment by SzymonSel** [comment]
Sure, I'll give it go! Thanks!

**Comment by SzymonSel** [comment]
Sadly, no. I've additionally tested this with a simple TextField and a List
![image](https://github.com/OrchardCMS/OrchardCore/assets/9480863/8e85b4ff-49b5-4379-a978-79b23160584c)
![image](https://github.com/OrchardCMS/OrchardCore/assets/9480863/26921c1a-5720-4a71-92e2-d362da27746a)

**Comment by sebastienros** [comment]
I will debug that then

**Comment by gvkries** [comment]
I've created #16053 as a starting point for a solution. But I'm not sure about the date and time values, or how they should be supported in Liquid. 
I've also added some rudimentary unit tests, but I'm also not sure where to put them. Are there already tests as I haven't found any?
