### ISSUE TITLE
 'OrchardCore.Deployment.DeploymentStep' can't be serialized.

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/OrchardCore#15624]
### Describe the bug
After upgradeing our systems from 1.8 to latest nightly build (1.9*) I'm getting this error in randomly on different instances of the same app and different Views. Most notably when trying to browse ContentItems or Deployment Plans.

> `System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'OrchardCore.Deployment.DeploymentStep'. Path: $.DeploymentSteps[0] | LineNumber: 0 | BytePositionInLine: 151.
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'OrchardCore.Deployment.DeploymentStep'.`

Can't realy tell how to reproduce this, nor how to debug this.

**Comment by hyzx86** [comment]
You may have the answer here

https://github.com/OrchardCMS/OrchardCore/issues/15416

and 

https://github.com/OrchardCMS/OrchardCore/blob/main/src/docs/releases/1.9.0.md

**Comment by SzymonSel** [comment]
Fanstastic, the first one is where I've come from, but the release notes, saved my day!

Thank you kindly!

**Comment by SzymonSel** [comment]
Fanstastic, the first one is where I've come from, but the release notes, saved my day!

Thank you kindly!
