### ISSUE TITLE
Sql query error result

### ISSUE THREAD

**Issue by hamdiRuwiss** [OrchardCMS/OrchardCore#1567]
I created sql query named Articles

select DocumentId
from ContentItemIndex 
where Published = 'true' and ContentType = 'Article'
order by CreatedUtc DESC

When i run it i get :
An error occured while executing the SQL query: Invalid column name 'true'.
 Invalid column name 'Article'.

When i run it against the database it works

if i write it like this : 
select DocumentId
from ContentItemIndex 
where Published = true
order by CreatedUtc DESC

it works;but if i wirte it like this :
select DocumentId
from ContentItemIndex 
where ContentType = 'Article'
order by CreatedUtc DESC
 
i get :
An error occured while executing the SQL query: Invalid column name 'Article'.

**Comment by sebastienros** [comment]
Maybe like this:

```sql
select DocumentId
from ContentItemIndex
where Published = true and ContentType = 'Article'
order by CreatedUtc DESC
```

**Comment by zl2fxy** [comment]
Because ContentItemIndex just has field of documentid,and "Published" is bool.

**Comment by hamdiRuwiss** [comment]
I tried:
select DocumentId
from ContentItemIndex
where Published = true and ContentType = "Article"
order by CreatedUtc DESC
 
It doesn't work

**Comment by sebastienros** [comment]
I can repro with SQL Server, it works with Sqlite, must be an issue in YesSql dialects then ... fixing
