### ISSUE TITLE
Content items actions placement in admin

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#15674]
With the latest version of the source code, when I open the Content items admin page, some actions (ex: Unpublish, Delete, Clone) do not appear in the Actions dropdown button as they should: 

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/e6febfc2-dfa6-4542-a378-a08efd56558d)

**Comment by Piedone** [comment]
@MikeAlhayek @sebastienros you worked a lot related to (content) shapes lately. Isn't this and https://github.com/OrchardCMS/OrchardCore/issues/15673 related to something like that? E.g. https://github.com/OrchardCMS/OrchardCore/pull/15651, https://github.com/OrchardCMS/OrchardCore/pull/15622, https://github.com/OrchardCMS/OrchardCore/pull/15620, https://github.com/OrchardCMS/OrchardCore/pull/15652

**Comment by MikeAlhayek** [comment]
@agriffard any error in the logs that could indicate why they are no longer being added?

**Comment by sebastienros** [comment]
Most probably. We'll fix it. Should be ready to find which commit by checking out the recent history.
