### ISSUE TITLE
Error with Content Culture Picker and TheTheme

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#15673]
When I enable the `Content Culture Picker` and use the Default theme, there is an error on the home page (Saas recipe):

`RuntimeBinderException: 'OrchardCore.DisplayManagement.Views.ShapeViewModel<OrchardCore.Admin.Models.Navbar>' does not contain a definition for 'CurrentCulture'`

```
AspNetCoreGeneratedDocument.Views_ContentCulturePicker.ExecuteAsync() in ContentCulturePicker.cshtml
line 23            if (culture.Name != Model.CurrentCulture.Name)
```

![image](https://github.com/OrchardCMS/OrchardCore/assets/703248/db70bb59-7313-4f02-b67e-8c5da541d669)

**Comment by hishamco** [comment]
Is the `navbar` shape added?

**Comment by agriffard** [comment]
> Is the `navbar` shape added?

Yes, it is using the TheTheme: 

https://github.com/OrchardCMS/OrchardCore/blob/b6acaef39adf62445136769343103e89a7d402f9/src/OrchardCore.Themes/TheTheme/Views/Layout.cshtml#L54

**Comment by agriffard** [comment]
I tested on another project with a theme copy/pasted from TheTheme and I have the same error using the preview packages version 1.9.0-preview-18167
