### ISSUE TITLE
Have a better way to auto-update dependencies

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15694]
### Is your feature request related to a problem? Please describe.
Dependabot is currently enabled and it updates some dependencies automatically. However, this is not ideal, see [from here](https://github.com/OrchardCMS/OrchardCore/pull/15641#issuecomment-2043231255).

### Describe the solution you'd like
Perhaps we should disable Dependabot, or use [Renovate](https://github.com/renovatebot/renovate).

See this issue with some ideas: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/703

### Describe alternatives you've considered
Just disabling Dependabot.

**Comment by hishamco** [comment]
This could be done automatically but again, there's no testing well be involved, right :)

**Comment by Piedone** [comment]
Yep, and while the update itself can be automated (which is I think only worthwhile in itself if it's about some urgent security update), this can happen only up to a point of opening a PR. Then somebody still needs to check that, and as Antoine told under the linked thread, Gulp also run.

**Comment by Piedone** [comment]
We _should_ test them manually. When I review such a PR, I always also test it, but of course, the author should do this foremost, since that's most of the work usually anyway. I also ask for that.

I created a UI test suite for this before: https://github.com/OrchardCMS/OrchardCore/pull/11194 But since then the only thing we could progress on was "maybe let's use Playwright". We really need a UI test suite, because we had dozens of regressions lately that would basically all be caught by just a few UI tests.

**Comment by Skrypt** [comment]
I don't mind. But as I said. If you break something by updating these then take responsibility into fixing it afterward too. That's the part that this dependabot will not do. I personnally just don't like it.

**Comment by BenedekFarkas** [comment]
BTW there are 16 Dependabot security alerts at the moment and 9 of them has a PR that was closed. If those packages have been updated in another PR that adds other (necessary) changes, then the corresponding alerts should be marked as resolved with a link to the PR.

**Comment by Piedone** [comment]
Those alerts should auto-resolve themselves if a fix is in `main`. So that indicates that those weren't fixed in other PRs.

**Comment by BenedekFarkas** [comment]
OK, then that's not very ideal (I mean that they were closed without action).
