### ISSUE TITLE
media library ,delete file not success

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#15698]
### Describe the bug
In the media library, if I delete a file and then upload another file with the same name but different content, the library still displays the deleted file. Why is this happening?

i want displays the upload another file.

**Comment by Skrypt** [comment]
Either browser cache or ImageSharp cache related.

**Comment by Piedone** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/15273. This is fixed and will be part of 1.9.

In case you're experiencing this with the latest source in `main`, not with <=1.8.2, please reopen.

**Comment by jnucpz** [comment]
thanks.
