### ISSUE TITLE
Liquid syntax errors always report the error at line 0

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1570]
Create a liquid view file with a syntax error- you'll get a white screen with an incorrect line number (and I think col number might be incorrect too)

**Comment by sebastienros** [comment]
https://github.com/sebastienros/fluid/issues/69

**Comment by hishamco** [comment]
This need to be closed while the original bug has been fixed in https://github.com/sebastienros/fluid/commit/3b7801e54ecc7ae290dad39409bcd85325f48b55
