### ISSUE TITLE
"The options are written in an incorrect format." when saving Trumbowyg settings

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15703]
### Describe the bug

When saving the Trumbowyg settings, at least for Html Field, you get the "The options are written in an incorrect format." error with the default options.

### To Reproduce

1. Set up a fresh site from `main` with the Blog recipe.
2. Go to /Admin/ContentTypes/Edit/RawHtml.
3. Edit the Content Field.
4. What type of editor should be used? -> Trumbowyg editor.
5. Change nothing, Save.
6. See the "The options are written in an incorrect format." validation error.

### Expected behavior
The default options just work.

### Screenshots

https://github.com/OrchardCMS/OrchardCore/assets/1976647/a113c851-aaf5-4d3c-853e-a40124f00afd

**Comment by Piedone** [comment]
This is a regression since 1.8.2.

**Comment by Piedone** [comment]
@MikeAlhayek this looks like a JSON issue too.

**Comment by Skrypt** [comment]
That's a good example of update regression. :smile:

**Comment by MikeAlhayek** [comment]
I am guessing that Json contains a trailing comma or contains comments.

**Comment by Piedone** [comment]
The problem is that since https://github.com/OrchardCMS/OrchardCore/commit/1ee808fd7c29eb18922f018dfa48fdffcc627094 the Trumbowyg editor's settings (and since then, a lot of other code using `IsJson()`) is validated as JSON. However, those settings aren't, and never were, actually JSON. Since this is not JSON, but otherwise a valid JS object:

```js
{
    autogrow: true,
    btns: [
        ["viewHTML"],
        ["undo", "redo"],
        ["formatting"],
        ["strong", "em", "del"],
        ["foreColor", "backColor"],
        ["superscript", "subscript"],
        ["link"],
        ["insertShortcode"],
        ["image"],
        ["align"],
        ["unorderedList", "orderedList"],
        ["horizontalRule"],
        ["removeformat"],
        ["fullscreen"]
    ],
    btnsDef: {
        align: {
            dropdown: ["justifyLeft", "justifyCenter", "justifyRight", "justifyFull"]
            ico: "justifyLeft"
        },
        image: {
            dropdown: ["insertImage", "base64", "noembed"],
            ico: "insertImage"
        }
    }
}
```

We need to keep this for Trumbowyg.

So, for these, maybe we need JS, not JSON validation instead? Either Jint `Engine.PrepareScript()`, or going one lower, what it does with `new JavaScriptParser().ParseScript()` (we mustn't try to execute the script, of course), and similarly catching the exception on error.
