### ISSUE TITLE
Email SMTP Settings - Test Settings fails

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrchardCMS/OrchardCore#1571]
When first entering SMTP settings into the Admin configuration, the 'Test Settings' is enabled but generates and exception if clicked before the settings have been saved: _options.DefaultSender is null

**Comment by sebastienros** [comment]
Probably related to the recent changes /cc @jeremycook

**Comment by jeremycook** [comment]
I'll take a look

**Comment by jeremycook** [comment]
@sebastienros I get the same error with my changes and before my changes. This bit of code in `SmtpSettingsConfiguration` results in the `settings` variable being null. What should happen in this case? I think this is in the vein of #1306 

```
...
public void Configure(SmtpSettings options)
{
    var settings = _site.GetSiteSettingsAsync()
        .GetAwaiter().GetResult()
        .As<SmtpSettings>();

    options.DefaultSender = settings.DefaultSender;
...
```

**Comment by paynecrl97** [comment]
Yep, more than likely related to #1306. This has tripped me up a few times, and I know it's tripped others up too.

If we're happy if the suggestion I put forward in #1306, we can look to getting a fix ready.

**Comment by GadgetGeekUK** [comment]
Good work, thanks.
