### ISSUE TITLE
Culture and LocalizationSet are not set for LocalizationPart if content is created programmatically

### ISSUE THREAD

**Issue by M-Lipin** [OrchardCMS/OrchardCore#15713]
### Describe the bug
Culture and LocalizationSet are not set for LocalizationPart if content is created programmatically.

### To Reproduce
1. Create some content with LocalizationPart programmatically without specifying Culture and LocalizationSet.
2. Navigate to the list of contents.
3. Observe the newly created content.

### Expected behavior
Localization settings are available for newly created content.

### Screenshots
Localization settings are not available for newly created content.
![image](https://github.com/OrchardCMS/OrchardCore/assets/23213980/a58d9011-58a0-471e-ae0b-3444511ffd8f)

**Comment by hishamco** [comment]
> Create some content with LocalizationPart programmatically without specifying Culture and LocalizationSet.

Can you show me how you create your content programatically?

**Comment by M-Lipin** [comment]
This can be done for instance via custom mutation:
```
        Resolver = new AsyncFieldResolver<object, ContentItem>(async (context) =>
        {
            var modelValues = context.GetArgument<object>(ModelArgument);
            var contentManager = httpContextAccessor.HttpContext!.RequestServices.GetRequiredService<IContentManager>();
            var contentItem = await contentManager.NewAsync(contentType);

            inputGraphType.Enrich(contentItem, modelValues);

            var result = await contentManager.UpdateValidateAndCreateAsync(contentItem, VersionOptions.Draft);
            if (!result.Succeeded)
            {
                context.Errors.AddRange(result.Errors.Select(err =>
                    new ExecutionError(err.ErrorMessage!)));
                return null;
            }
            
            return contentItem;
```

**Comment by hishamco** [comment]
I thought you create it via a normal migration

**Comment by M-Lipin** [comment]
Is any chance to approve related MR https://github.com/OrchardCMS/OrchardCore/pull/15714?

**Comment by hishamco** [comment]
I'm still waiting for a unit test or I code snippet to reproduce the issue

**Comment by Piedone** [comment]
The above code snippet should be enough, Hisham.

**Comment by hishamco** [comment]
I will try to create another migration for a content type that has a `LocalizationPart` then check, unless you see that changes are fine please approve

**Comment by Piedone** [comment]
Please do that.

**Comment by Piedone** [comment]
Great then!
