### ISSUE TITLE
Should we add Version property to ContentItem class to get optimistic lock work properly?

### ISSUE THREAD

**Issue by aaronamm** [OrchardCMS/OrchardCore#15729]
### Is your feature request related to a problem? Please describe.
So right now OC checks optimistic lock when saving a content item. 
However, we can't manually set version value to a content item.
Therefore, we can't do optimistic lock over content item object. 

### Describe the solution you'd like
I think we should add `public long Version` to `ContentItem.cs`.
This allow us to set Version's value from form's input when saving a content item and prevent multiple users trying to update a content item at the same time.

FYI, I started this topic as discuss and found it should be a new PR but I want to get idea/feedback before implementing it.
Please check.
https://github.com/OrchardCMS/OrchardCore/discussions/15721

**Comment by aaronamm** [comment]
CC @sebastienros  @Skrypt

**Comment by hishamco** [comment]
AFAIK the content lock is a missing feature

**Comment by aaronamm** [comment]
@hishamco if I understand it correctly, YesSQL supports this feature. 
However our ContentItem class does not have Version property to get optimistic lock work property. 
We can make a very simple PR to fix this but I only want to make sure if there is other ideas/suggestions on the issue.

**Comment by aaronamm** [comment]
@hishamco please also check this link. https://github.com/OrchardCMS/OrchardCore/discussions/15721

**Comment by hishamco** [comment]
> We can make a very simple PR to fix this but I only want to make sure if there is other ideas/suggestions on the issue.

AFAIK Seb mentioned content lock long time a ago, we can use SignalR, so once the user starts to edit a content item it should trigger anyone else opening the same page to lock the content temporarily, so once he saves or cancels the update process, others can start editing

**Comment by aaronamm** [comment]
@hishamco  I got your idea. However, for a simple application that does not allow two administrators to override the same content, using optimistic lock is a good option. 
IMHO, I don't think we need SignalR for a simple app, even though it is easy to add to an application.

**Comment by hishamco** [comment]
You could propose a PR

**Comment by aaronamm** [comment]
@hishamco thank you for your suggestion.

**Comment by Piedone** [comment]
What's the use case, exactly? Two people saving a content item at the same time and overwriting each others' changes?
