### ISSUE TITLE
Shortcode icon not aligned properly

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#15738]
![image](https://github.com/OrchardCMS/OrchardCore/assets/3228637/7e84fa9c-9824-48be-bc54-8f55402a3921)

![image](https://github.com/OrchardCMS/OrchardCore/assets/3228637/784dcc72-df58-498b-9d82-dc4244566800)

@MikeAlhayek Here, found one.

**Comment by MikeAlhayek** [comment]
I also noticed it. Did not have time to try to fix it. 

Feel free to submit a fix

**Comment by Skrypt** [comment]
Same for me. I'm busy with other bigger fishes.
