### ISSUE TITLE
Render Markdown field in cshtml View

### ISSUE THREAD

**Issue by iyhammad** [OrchardCMS/OrchardCore#1573]
I've a content type with Markdown named field. I can see the Markdown text in the View But I don't know how to render it.
Is there a ready-made way to render this Markdown? Currently I'm using external library to convert from Markdown to HTML and then render the Raw HTML.
Thanks,

**Comment by paynecrl97** [comment]
Can you post a few lines from your view showing how you're accessing the markdown field?

**Comment by sebastienros** [comment]
http://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Liquid/README/#markdownify

**Comment by iyhammad** [comment]
Sorry @sebastienros I forgot to mention that I'm doing this in cshtml View 
and here is a sample of what I'm doing.
```
@for (var productIndex = 0; productIndex < Model.BagPart.ContentItems.Count; productIndex++)
{
    var product = Model.BagPart.ContentItems[productIndex];
    var productItem = (OrchardCore.ContentManagement.ContentElement)product;
    <section class="white-bg page-section-pt service-04">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 align-self-center">
                    <div class="section-title">
                        <h2>@productItem.Content.TitlePart.Title</h2>
                    </div>
                    <p>@Html.Raw(CommonMark.CommonMarkConverter.Convert(productItem.Content.Product.Description.Markdown.ToString()))</p>
                    <a class="button icon-color mt-20" href="@productItem.Content.Product.MoreDetailsLink.Url">@productItem.Content.Product.MoreDetailsLink.Text<i class="fa fa-angle-right"></i></a>
                </div>
                <div class="col-lg-6 p-5 col-md-6 m-0 m-md-5 service-04-video xs-mt-30">
                    <img class="img-fluid mx-auto" src="/media/@productItem.Content.Product.Image.Paths[0]" alt="">
                </div>
            </div>
        </div>
    </section>
}
```

**Comment by KuulArt** [comment]
@iyhammad 
I have stumbled across the same need to represent Markdown in cshtml. Had a look through the source code and from the looks of it seems that they are using [markdig](https://github.com/lunet-io/markdig) library. Correct me if I am wrong.
`namespace OrchardCore.Markdown.Filters
{
    public class Markdownify : ILiquidFilter
    {
        public Task<FluidValue> ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext ctx)
        {
            return Task.FromResult<FluidValue>(new StringValue(Markdig.Markdown.ToHtml(input.ToStringValue())));
        }
    }
}`
