### ISSUE TITLE
how i custom the shown role list without changing the user module.

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#1574]
how i custom the shown role list without changing the user module. 
When i add a user in admin, i just want two roles render, not all roles. Different user can add user having different role lists.

**Comment by paynecrl97** [comment]
I'm not sure this is possible at the moment.

I think it's a limitation that at the moment, any user that can edit/ assign roles can add any permission or role to any role or user.

e.g. a user than can assign roles, could in theory assign themselves the `Administrator` role, and therefore gain wider access to the site than they were originally granted.

Any change to this would be part of a larger piece of work. One option would be a `WithGrant` flag on role and permission assignments. Users could be assigned any roles, but could only assign roles to others/themselves if they are assigned the role with grant.
