### ISSUE TITLE
Null reference exception in the Admin theme

### ISSUE THREAD

**Issue by ItaloFSS** [OrchardCMS/OrchardCore#15752]
While upgrading our website from 1.6 to 1.82, we ran into an issue with the Admin theme. Line 12 in NavigationItemLink-admin.cshtml is not checking for null, which prevents the theme from rendering.

Original:

 if (Model.Href.ToString() == "#")

Changed to:

 if ( ( Model.Href?.ToString() ?? "#" ) == "#")

Thanks

**Comment by Piedone** [comment]
Shouldn't we rather throw a custom exception (not an ad-hoc NRE) if `Href` is null or empty? Since does it make sense for it to every not have a string?

**Comment by ItaloFSS** [comment]
I'm not sure why, but the menu item with the issue is "Azure Blob Options." Throwing an exception will prevent the theme from rendering, making the admin inaccessible.

**Comment by Piedone** [comment]
I can't reproduce this with the latest `main` or with v1.8.2. Are you sure it's not some custom code of your that causes this?

**Comment by ItaloFSS** [comment]
There's no custom code for that module. That's the only one with a null HREF.

![image](https://github.com/OrchardCMS/OrchardCore/assets/130403/e91e6a42-44b9-4ee7-b3dc-ec0b71bcc46c)

**Comment by Piedone** [comment]
Don't you have any other custom code in the solution that could affect this though? Because that link [specifies a `Href`](https://github.com/OrchardCMS/OrchardCore/blob/b406d50be4043912c117a7be1d4aeaf1a96b4087/src/OrchardCore.Modules/OrchardCore.Media.Azure/AdminMenu.cs#L26) (this is the same in 1.8.2), and this properly works in vanilla OC both on 1.8.2 and latest `main` for me (the URL is there on the UI, visible `Href`, and no exception is thrown).

What I can imagine is that perhaps you have a custom `INavigationProvider` that affects this?

**Comment by MikeAlhayek** [comment]
@ItaloFSS 

Can you please expand these two nodes? I am looking for more clues on what created this menu item.

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/704ce7ce-0fb6-4aca-bbd3-dea2ad985d2a)

**Comment by ItaloFSS** [comment]
The issue was that the Admin controller was not registering, so no action URL was being generated. I was able to fix it by disabling and reenabling the module.

You should still check for null. The entire admin module was inaccessible. At least, it should render an error for the user.

Thanks for the help!

**Comment by MikeAlhayek** [comment]
@ItaloFSS 

> The issue was that the Admin controller was not registering,

Maybe there is a dependency issue. Which admin controller was not available? or which feature you enabled to fix the issue?

**Comment by ItaloFSS** [comment]
The Admin controller in OrchardCore.Media.Azure.

![image](https://github.com/OrchardCMS/OrchardCore/assets/130403/5ecd97a9-91be-48df-b9bc-e23db5fc06b3)

**Comment by MikeAlhayek** [comment]
We are missing something here. I am wondering if you were registering the AdminMenu class in your project somehow 

https://github.com/OrchardCMS/OrchardCore/blob/42267bfb95e17ca8f40ccaa2ccceca68c36726b0/src/OrchardCore.Modules/OrchardCore.Media.Azure/AdminMenu.cs#L7

This class what added the menu item which appears to be that caused your issue. That class would not be registered unless the `OrchardCore.Media.Azure.Storage` is activated.  And when it is activated, the controller routes will then be available. 

Based on your explanation, it seems that that AdminMenu was registered while the feature was not which does not make sense "at least from what I can see in OC code".

**Comment by ItaloFSS** [comment]
We don't have an INavigationProvider that's adding the menu item. I looked everywhere for it.

Could it be security? When I disabled and reenabled the module, the claims were added to my identity.

**Comment by MikeAlhayek** [comment]
I am not sure. Try disabling the feature that fixed your issue and see if you can do some tracing to see what is actually adding that menu item. Maybe look at the logs to see if there are any additional clues
