### ISSUE TITLE
Use HttpMethods instead of string comparison

### ISSUE THREAD

**Issue by Icidis** [OrchardCMS/OrchardCore#1578]
https://github.com/OrchardCMS/OrchardCore/blob/e64191cb19346afe1fd28a1ca28a2aaa00d19d52/src/OrchardCore/OrchardCore.Mvc.Core/ActionConstraints/FormValueRequiredAttribute.cs#L18

Just a small thing but shouldn't the above be change to:

```
if (!HttpMethods.IsPost(routeContext.HttpContext.Request.Method))
```

Reference to Microsoft Docs:
[HttpMethods Class (Microsoft.AspNetCore.Http)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpmethods?view=aspnetcore-2.0)

Let me know your thoughts.

**Comment by PinpointTownes** [comment]
Yep. Plus there was really no reason to use a case-sensitive comparaison here.

Would you be interested in submitting a PR?

**Comment by Icidis** [comment]
I'll fork the project and do a pull request shortly.

**Comment by PinpointTownes** [comment]
@Icidis much appreciated :+1:

**Comment by sebastienros** [comment]
I checked the source code for POST, GET and PUT strings, could only find this instance of POST.

**Comment by PinpointTownes** [comment]
Merged, thanks :+1:
