### ISSUE TITLE
Use Permissions.ViewContent for GetEndpoint

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#15785]
### To Reproduce
1. Go to 'Content GET API'

2. See error
DIFF PERMISSION  in whole site
### Expected behavior
tHIS GET API SHOULD HAVE THE SAME PERMISSION AS 👍 public async Task<IActionResult> Display(string contentItemId, string jsonPath)
{
    var contentItem = await _contentManager.GetAsync(contentItemId, jsonPath);

    if (contentItem == null)
    {
        return NotFound();
    }

    if (!await _authorizationService.AuthorizeAsync(User, **_CommonPermissions.ViewContent_**, contentItem))
    {
        return this.ChallengeOrForbid();
    }

    var model = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, this);

    return View(model);
}

**Comment by MikeAlhayek** [comment]
Not really. We use both permissions. First we make sure you have permission to access the API. Then we check to see if you have permission to view the requested content item.
