### ISSUE TITLE
how i show new navigation style without changing original module code.

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#1582]
I want just show Tenants menu ,not show Cofiguration menu. if i don't change the module code , in my custom module , how i make it work?   
example for : 
builder .Add(T["Configuration"], "10", configuration => configuration
                    .AddClass("menu-configuration").Id("configuration")
                    .Add(T["Tenants"], "5", deployment => deployment
                        .Action("Index", "Admin", new { area = "OrchardCore.Tenants" })
                        .Permission(Permissions.ManageTenants)
                        .LocalNav()
                    )
                );

**Comment by paynecrl97** [comment]
Off the top of my head, you should be able to create your own implementation of `OrchardCore.Environment.Navigation.INavigationProvider`, and then replace `OrchardCore.Tenants.AdminMenu` with your new implementation from your module's startup class.

**Comment by jnucpz** [comment]
@paynecrl97 , thank you . my implementation INavigationProvider can't override the  OrchardCore.Tenants.AdminMenu. It will show two tenants menu,  how can i rid of it ?

**Comment by jnucpz** [comment]
@Skrypt thanks, it works..
