### ISSUE TITLE
Changing user name removes author name when republishing blog posts

### ISSUE THREAD

**Issue by BennieCopeland** [OrchardCMS/OrchardCore#1590]
I'm using Beta1 on Ubuntu and just created my site. I didn't realize that the username (admin in this case) would be used as the author name for the blog entries. I changed my username under Design > Security > Users.

When editing and republishing an existing blog entry, the author name gets blanked out.
When creating a new blog entry, the name remains as "admin" instead of my name, and blanks out if republishing.

**Comment by BennieCopeland** [comment]
I noticed my name in the admin screen was still "admin", so I logged off and logged back in. That fixes the author name when creating a new blog entry, but it still gets blanked out when republishing an existing entry.

**Comment by BennieCopeland** [comment]
> The author property is an historical data, we don't change it automatically.

Makes sense. The problem with the blanking out of the author name doesn't seem to be happening on the dev branch, at least on windows. My ubuntu version is running a published version of the Beta1.

**Comment by agriffard** [comment]
Can this be closed? The owner can be edited from the Common part.
