### ISSUE TITLE
Indexing and Search

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1591]
When I try to Index contents:
- I previously had existing content items.
- I enable Indexing and Lucene.
- I create a 'Search' index.
- In BlogPost Content Definition, on TitlePart settings, I check 'Include this element index' and then 'Stored' and 'Analyzed'.
- I Reset or Rebuild my 'Search' Index.
- I test a Lucene query in '/OrchardCore.Lucene/Admin/Query' clicking on 'Match All query to search all document'
=> The query doesn't return any items.
 
I need to re-publish the items in order to add them to the index.

- I edit the 'Search' Settings with 'Content.ContentItemMetadata.DisplayText' in 'Default searched fields'
- I test the url '/Search' with a text that has been indexed in a title => It doesn't work.
- I change the 'Search' Settings with 'TitlePart' with 'Default searched fields' => It returns items.

- In BlogPost Content Definition, on BodyPart settings, I check 'Include this element index' and then 'Stored' and 'Analyzed'.
- I edit the 'Search' Settings with 'Content.BodyAspect.Body' in 'Default searched fields'.
- I re-publish some posts. I rebuild the index. 
- I test the url '/Search' with a text that has been indexed in a body => It doesn't work.

- In an Article Content Definition, on TitlePart settings, I check 'Include this element index' and then 'Stored' and 'Analyzed'.
- In /OrchardCore.Lucene/Admin/Query, I test a Lucene Query on the 'Search' Index.
=> Indexed Items are displayed but the BlogPost have an extra column, for the Body, with the text 'Body' inside and no Column Name.

**Comment by agriffard** [comment]
I tested again.
The search does work so it could be closed.

As I explained, it is just that the display when you test a Lucene query in admin is a bit weird:
Indexed items are displayed but the BlogPost have extra columns with a name in the header: 
1 with a date and one with the text of the 'Body' inside.

Also, there is a problem because it is a large table and because of the footer taht has been added, if you want to scroll horizontally, you have to scroll to the bottom to see the horizontal scroll bar. (or else, you can use left and right key to move the horizontal position).

**Comment by Skrypt** [comment]
This issue still needs to be fixed. The issue is that when we publish a content item it will add an IndexingTask record in the DB. If we create the Search index after creating some content items ; those won't have any IndexingTask records in the DB. We need to see if we want to add all content items that never been added to the IndexingTask DB records if we rebuild or reset an index.
