### ISSUE TITLE
Custom themes cannot override ShapeView in 1.9.x

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#15924]
Noticing that 1.9.x-preview extracts a few HTML elements from the landing page into shapes, 
I updated my theme with the latest template
But I found that the ShapeView part didn't render successfully. I tried to add a feature in the theme module using the following method, but it didn't work
“Layout” could not be found

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/8efc8240-2df5-4ca7-b1aa-883553dd936e)

It appears that the content of `LoginFormCredentials.Edit.cshtml` is not functioning as expected. 
At this point, I would recommend performing a specific set of operations. 
Would it be necessary to render this block of content separately in its own module? 
However, if switching themes, what should one do.

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/f1406eb3-a5e4-44cc-a8a5-efeea8a503eb)

**Comment by MikeAlhayek** [comment]
I don't think I understand what you are trying to do or what the issue is. But you should be aware of the User Module changes https://docs.orchardcore.net/en/latest/releases/1.9.0/

If you are overriding `Login.cshtml` in your solution or theme, then make sure you follow the change done in this PR https://github.com/OrchardCMS/OrchardCore/pull/15701/files#diff-96085c1f65af07a38df0a90afc8d8b4da49b63382c30aaa6fef204fdbd36ff8d

Now if you like to style `LoginFormCredentials` you should do so by creating `LoginFormCredentials.cshtml` not `LoginFormCredentials.Edit.cshtml`

**Comment by hyzx86** [comment]
> Now if you like to style `LoginFormCredentials` you should do so by creating `LoginFormCredentials.cshtml` not `LoginFormCredentials.Edit.cshtml`

I'm sorry I made a mistake，I'll try right away.

**Comment by hyzx86** [comment]
Great!🎉🎉🎉🎉🎉  It works, thanks for the correction! 
![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/bfcca0c6-c2ed-4b4c-ab8f-2cb0ef69608e)

**Comment by hishamco** [comment]
Great it works with, you, also you can have a look to

https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.Themes.Admin/Views/Layout-Login.cshtml

https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.Themes.Admin/Views/OrchardCore.Users/Account/Login.cshtml

**Comment by hyzx86** [comment]
> Great it works with, you, also you can have a look to
> 
> https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.Themes.Admin/Views/Layout-Login.cshtml
> 


@hishamco, 
Thanks for sharing, but your implementation is no longer available in the latest version of OC.

It will prompt the Model type, which is inconsistent with the expected type.😄

**Comment by hishamco** [comment]
> Thanks for sharing, but your implementation is no longer available in the latest version of OC.

I just started updating to `1.8.3`, I'm glad if you open a  PR for it

**Comment by hyzx86** [comment]
I'm adapting 1.9.x, mainly because the Graphql enhancements are useful to me 😁

**Comment by hishamco** [comment]
I see :)
