### ISSUE TITLE
Asset Admin - Media Library Tree view drill-down not functioning

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrchardCMS/OrchardCore#1594]
Started a blank site with the Agency theme (from Dev branch, dated today). In the Content - Assets admin section there is no response when trying to drill down into the 'Media Library' folder (no sub-folders are displayed even though they exist).

I can see the following call being made when clicking on the 'Media Library' text (no parameter values appear to be supplied), and I get a valid response for the root level Media Library folder items, clicking on the '>' icon has no effect :

GetMediaItems?path=

**Comment by Skrypt** [comment]
My fault. Will fix it. It's a regression after upgrading FontAwesome that now replaces everything with .svg files.

**Comment by GadgetGeekUK** [comment]
landingpage.iquid line 59: 
mode: 'strech'
Should be spelled 'stretch' ;)
