### ISSUE TITLE
Liquid TempleContext AmbientValues not available in autoroute pattern

### ISSUE THREAD

**Issue by ThisNetWorks** [OrchardCMS/OrchardCore#1596]
I was trying to use the display_url & content_url liquid filters in an autoroute pattern, but the templatecontext.UrlHelper hasn't been applied, and isn't available at that point.

I was trying to generate a container slug based on it's parent url (they're nested contained parts)

Wrote another filter which just checks the autoroute part on the parent, however was interested to know if there was another alternative?

**Comment by sebastienros** [comment]
There are other ways to build such a pattern, have you looked at the way blog posts do it by reusing their blog container?

**Comment by ThisNetWorks** [comment]
Yes, I looked at the way blog posts do it, and while it didn't work for my requirements, I wrote a filter that does fit the purpose.

Was more curious to understand if there was anyway to know which filters would work in which context's (it was always a bit of trial and error with Orchard 1 tokens), however I've looked further at the source, and have a better sense of what / when and how the ambient values will make it into the context
