### ISSUE TITLE
still need  Newtonsoft.Json

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#15962]
### Is your feature request related to a problem? Please describe.

after the commit of remove  Newtonsoft.Json, my api could not give the correct json to client side . I tried many ways and made sure only  Newtonsoft.Json can reach my purpose.
### Describe the solution you'd like
are there any way to comparable both  Newtonsoft.Json and System.Text.Json

### Describe alternatives you've considered
Now I only  go inside src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs and add back builder.AddNewtonsoftJson(); , which is  not elegant.

```
// Add a route endpoint selector policy.
services.AddSingleton<MatcherPolicy, FormValueRequiredMatcherPolicy>();

// There are some issues when using the default formatters based on
// System.Text.Json. Here, we manually add JSON.NET based formatters.
builder.AddNewtonsoftJson();
services.AddModularRazorPages();
```

**Comment by MikeAlhayek** [comment]
> after the commit of remove Newtonsoft.Json, my api could not give the correct json to client side . I tried many ways and made sure only Newtonsoft.Json can reach my purpose.

What does your API returns now and what is it supposed to return? It would be good to share JSON response sample.

**Comment by Piedone** [comment]
Can you please provide further information, @infofromca? This potentially blocks the 2.0 release.

**Comment by infofromca** [comment]
Sorry, I cannot provide the data which belongs to a bank

**Comment by hishamco** [comment]
Please provide a sample not necessarily actual data to make it easier to see the bug if there is

**Comment by Piedone** [comment]
Unfortunately, we'll only be able to help if we get more information from you, because this is not something we can work with at this point.

And yeah, we'd need a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) as a starting point. While creating that, you might discover that the issue is specific to some custom code of yours.

**Comment by Piedone** [comment]
And maybe you could give a demo of the app, to an extent possible to do publicly, on the Tuesday meeting, so we can say a bank uses OC :).

**Comment by hishamco** [comment]
Lol

**Comment by infofromca** [comment]
Although it was not elegant, I found a workaround about it.
I add the following code  in the startup.cs of my custom module:
var builder = services.AddMvc();
           
// There are some issues when using the default formatters based on
// System.Text.Json. Here, we manually add JSON.NET based formatters.
builder.AddNewtonsoftJson(options =>
{
    // Use the default property (Pascal) casing
    // options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
});

**Comment by hishamco** [comment]
Please check different options in `JsonSerializationIOptions` https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions?view=net-8.0

**Comment by Piedone** [comment]
And check this too: https://github.com/OrchardCMS/OrchardCore/blob/35c450b333b578fe02a740dd8ac607750b624157/src/OrchardCore/OrchardCore.Abstractions/Json/JOptions.cs.

**Comment by MikeAlhayek** [comment]
@infofromca any updates here? Can we close this issue or you think there is something else that needs to be done?

**Comment by infofromca** [comment]
if we need note on  the doc, we can add it. otherwise , close it

**Comment by Piedone** [comment]
Docs about using `JsonSerializerOptions`, do you mean?

**Comment by infofromca** [comment]
Maybe it is not neccesary for the doc. just close it
