### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#15977]
Warnings on some packages in `Installed` tab of Nuget packages in VS:

https://www.nuget.org/packages/NEST/7.17.5
Suggested Alternatives
[Elastic.Clients.Elasticsearch](https://www.nuget.org/packages/Elastic.Clients.Elasticsearch/)

https://www.nuget.org/packages/Irony.Core/1.0.7
Suggested Alternatives
[Irony](https://www.nuget.org/packages/Irony/)

**Comment by hishamco** [comment]
I notice that there's an issue with `Irony.Core`, so let us change the packages

@Skrypt what about NEST?

**Comment by hishamco** [comment]
FYI the `Irony.Core` has been replaced with `Irony` in #16012

**Comment by hishamco** [comment]
@Skrypt still waiting for your reply

**Comment by Skrypt** [comment]
No we can't replace NEST with the new Elasticsearch client without refactoring some parts of the Elasticsearch module. It will also remove support to some older versions of Elasticsearch so I see this upgrade as an OC.Elasticsearch 2.0 module. Meaning, we would need to keep the old module for those who want to still have support to older versions on Elasticsearch.

**Comment by agriffard** [comment]
It seems Irony.Core has been replaced.

**Comment by hishamco** [comment]
Yes it is
