### ISSUE TITLE
Feature Profile configs are not respected

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#15975]
### Describe the bug

Somewhat a followup from #15451. You are able to create a feature profile, but it doesn't take effect.

### To Reproduce

1. Set up a new site using the latest preview packages.
2. Enable _Tenants_ and _Tenant Feature Profiles_ features.
3. Go to Admin > Multi-Tenancy > Feature Profiles.
4. Click "Add Feature Profile" button.
5. Give it any name and copy the example rules from the text under the Rules field. (`[{"Rule":"Exclude","Expression":"OrchardCore.Flows"}]`)
6. Click "Save and Continue".
7. Go to Admin > Multi-Tenancy > Tenants
8. Click "Add Tenant" button
9. Set any name and URL prefix, select the "Software as a Service" recipe (for convenience), Sqlite database and the feature profile we've just created.
10. Click the "Create" and then the "Setup" buttons.
11. Set up the site.
12. Log in and go to Admin > Configuration > Features.
13. Observe that "Flows (`OrchardCore.Flows`)" is still on the list.
14. Enable Flows.
15. Observe that it was successfully enabled even though it's excluded by the feature profile.

Additional note: The same happens when the feature profile is imported from a recipe such as [this one](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/issue/OSOE-795/src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json#L226-L249).

### Expected behavior

The feature with the "Exclude" rule should not show up in the tenant's feature list.

**Comment by TonyWoo** [comment]
Based on my testing(main branch), it turns out the profile rule didn't get saved.
