### ISSUE TITLE
Getting content element by name and type can fail even if valid

### ISSUE THREAD

**Issue by tropcicstefan** [OrchardCMS/OrchardCore#15973]
### Describe the bug
When you try to get some content part lets say BlogPart from content item you can use extension method ContentExtensions.Get . Bug occurs when there are multiple valid casts of content part.
### To Reproduce
1. make a Blog content item with BlogPart
2. in code get content part as ContentPart (base class of every part) `contentItem.Get<ContentPart>("BlogPart")`
3. then try to get content part as BlogPart `contentItem.Get<BlogPart>("BlogPart")`
4. InvalidCastException

### Expected behavior
casts are valid should recast object

**Comment by MikeAlhayek** [comment]
Why are you calling contentItem.Get<ContentPart>("BlogPart") to begin with?

shouldn’t you use this instead contentItem.As<BagPart>() ?

**Comment by tropcicstefan** [comment]
I am trying to read some properties from basically all parts in content item but in graphql where those parts are already loaded with dynamic providers(e.g. [this](https://github.com/OrchardCMS/OrchardCore/blob/dcf83bca479ad06eeb41b9a09292a67fa26a2b21/src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Fields/ContentFieldsProvider.cs#L105))

**Comment by gvkries** [comment]
I think this is currently by design, but quite unfortunate. The first usage of `Get<TElement>()` determines the type for deserialization. No way to get a more specific type afterwards. Maybe we should allow to get derived types after an initial deserialization.

**Comment by MikeAlhayek** [comment]
> I think this is currently by design, but quite unfortunate. The first usage of Get<TElement>() determines the type for deserialization. No way to get a more specific type afterwards. Maybe we should allow to get derived types after an initial deserialization.

Maybe add a new method that does not check the cache. At least whom ever consumes it, will hopefully have a good reason to use it.

**Comment by hishamco** [comment]
> shouldn’t you use this instead contentItem.As<BagPart>()?

I still didn't understand what was wrong with `As<TPart>()` or you are trying to fix an existing bug

**Comment by tropcicstefan** [comment]
> > shouldn’t you use this instead contentItem.As()?
> 
> I still didn't understand what was wrong with `As<TPart>()` or you are trying to fix an existing bug

As<> in the end uses this Get and won't work if you ever read content with different type

**Comment by gvkries** [comment]
To make it more clear, the following test will throw. Not sure if we want to allow this:

```C#
[Fact]
public void ShouldDeserializeMoreSpecificTypes()
{
    var contentItem = new ContentItem();
    var myPart = new MyPart { Text = "test" };
    contentItem.Weld(myPart);

    var json = JConvert.SerializeObject(contentItem);

    var contentItem2 = JConvert.DeserializeObject<ContentItem>(json);

    // act
    var contentPart = contentItem2.Get<ContentPart>(nameof(MyPart));
    // This will throw
    var actualMyPart = contentItem2.Get<MyPart>(nameof(MyPart));

    // assert
    Assert.NotNull(actualMyPart);
}
```

**Comment by gvkries** [comment]
To make it more clear, the following test will throw. Not sure if we want to allow this:

```C#
[Fact]
public void ShouldDeserializeMoreSpecificTypes()
{
    var contentItem = new ContentItem();
    var myPart = new MyPart { Text = "test" };
    contentItem.Weld(myPart);

    var json = JConvert.SerializeObject(contentItem);

    var contentItem2 = JConvert.DeserializeObject<ContentItem>(json);

    // act
    var contentPart = contentItem2.Get<ContentPart>(nameof(MyPart));
    // This will throw
    var actualMyPart = contentItem2.Get<MyPart>(nameof(MyPart));

    // assert
    Assert.NotNull(actualMyPart);
}
```
