### ISSUE TITLE
Mac OS > Admin settings : OpenId

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#1597]
<img width="1272" alt="capture d ecran 2018-03-11 a 14 04 23" src="https://user-images.githubusercontent.com/3228637/37256735-2a335216-2535-11e8-80f7-4f7d183b7712.png">

**Comment by PinpointTownes** [comment]
Thanks for reporting this X-plat issue. It will be fixed as part of https://github.com/OrchardCMS/OrchardCore/pull/1602 (well... I just added a big/try catch :trollface:)

**Comment by Skrypt** [comment]
That good old and ugly try catch 👍

**Comment by Skrypt** [comment]
Certificate stores location on Linux and Mac OS : 
https://superuser.com/questions/992167/where-are-digital-certificates-physically-stored-on-a-mac-os-x-machine
https://serverfault.com/questions/62496/ssl-certificate-location-on-unix-linux
