### ISSUE TITLE
Expose SQL Queries in GraphQL too

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#16008]
### Is your feature request related to a problem? Please describe.
Related: https://github.com/OrchardCMS/OrchardCore/discussions/15959. Lucene and Elasticsearch Queries are accessible from GraphQL, see [here](https://docs.orchardcore.net/en/main/reference/modules/Queries/#graphql). This makes it possible to expose arbitrary content lists in GraphQL. However, the same feature is not available for SQL Queries.

### Describe the solution you'd like
Have the same kind of GraphQL integration for SQL Queries that we have for the other two.

### Describe alternatives you've considered
Alternatively, we could somehow expose field querying with Content Fields Indexing (SQL) in GraphQL, also see https://github.com/OrchardCMS/OrchardCore/discussions/15959#discussioncomment-9322540 and https://github.com/OrchardCMS/OrchardCore/issues/7047, https://github.com/OrchardCMS/OrchardCore/issues/12781 about this.

**Comment by hyzx86** [comment]
I've introduced this Orm framework into my framework, mainly for implementing full table indexing, but this feature should be available for reference

```c#
DynamicFilterInfo dyfilter = JsonConvert.DeserializeObject<DynamicFilterInfo>(@"
{
  ""Logic"": ""And"",
  ""Filters"":
  [
    { ""Field"": ""id"", ""Operator"": ""Equals"", ""Value"": 1 },
    {
      ""Logic"": ""Or"",
      ""Filters"":
      [
        { ""Field"": ""id"", ""Operator"": ""Equals"", ""Value"": 2 },
        { ""Field"": ""id"", ""Operator"": ""Equals"", ""Value"": 3 }
      ]
    }
  ]
}");
fsql.Select<Region>().WhereDynamicFilter(dyfilter).ToList();
//WHERE id = 1 AND (id = 2 OR id = 3)

```

https://freesql.net/guide/dynamic.html#%E5%8A%A8%E6%80%81%E6%9D%A1%E4%BB%B6

 
![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/55493afa-4f6d-4b9f-a211-2a3765450805)

**Comment by hyzx86** [comment]
Works great with some front-end component libraries
![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/59ad3c67-36b3-444f-8caf-d006bb9d0866)


https://aisuda.bce.baidu.com/amis/zh-CN/components/form/condition-builder#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95

**Comment by Piedone** [comment]
Thanks for sharing! So you're doing kind of embedded queries in GraphQL?

**Comment by hyzx86** [comment]
> Thanks for sharing! So you're doing kind of embedded queries in GraphQL?

I don't quite understand your reference to "embedded queries", I used a ContentHandler to create the full table indexes.

The following code hasn't been updated in a while, in the new version I only indexed the latest version and removed the unreleased version, then inserted the data using the dictionary method The following code uses reflection, which is very low performance

https://github.com/EasyOC/EasyOC/blob/51e3f3690bdc3c0ebf8c42ab1546f83f9d6af1a5/src/Modules/EasyOC.DynamicTypeIndex/Handlers/DynamicIndexTableHandler.cs#L93-L108

Then use FreeSql's own Api to implement the dynamic filtering.

The following is an implementation of PagedContentItemsQuery. It also doesn't require a lot of code since it only needs to query a single table.
https://github.com/EasyOC/EasyOC/blob/main/src/Modules/EasyOC.GraphQL/Queries/PagedContentItemsQuery.cs

To achieve the same effect in OC, you may have to generate some complex query statements

**Comment by Piedone** [comment]
What I mean is that with `dynamicFilter`, you have something like a custom query within the GraphQL query.

Any reason you opted for this instead of extending GraphQL directly?

**Comment by hyzx86** [comment]
Because Yessql's dynamic indexes are too cumbersome, first of all, the business system I'm working on, it needs to communicate with external databases frequently, such as cross-database correlation queries If I use Yessql, I may need to correlate each field with a table.

**Comment by Piedone** [comment]
OK, so you use a different ORM than YesSql to access the YesSql tables, have a UI query builder to generate queries for it, and you allow GraphQL queries to include expressions for these queries. Do I understand correctly?

**Comment by hyzx86** [comment]
> OK, so you use a different ORM than YesSql to access the YesSql tables, have a UI query builder to generate queries for it, and you allow GraphQL queries to include expressions for these queries. Do I understand correctly? 

Yes, exactly.

**Comment by Piedone** [comment]
OK, thanks!

**Comment by hyzx86** [comment]
Oh no, it's not a direct access to Yessql's index table, I use another ORM to map some tables to the required types, add the necessary fields to the tables, and these table definitions can be generated automatically following the type definitions.

The Graphql query just queries my dynamically created type data mapping table , and then associates the ContentItemIndex to return the document.

**Comment by Piedone** [comment]
Ah OK.

**Comment by guanwu** [comment]
> I've introduced this Orm framework into my framework, mainly for implementing full table indexing, but this feature should be available for reference
> 
> ```cs
> DynamicFilterInfo dyfilter = JsonConvert.DeserializeObject<DynamicFilterInfo>(@"
> {
>   ""Logic"": ""And"",
>   ""Filters"":
>   [
>     { ""Field"": ""id"", ""Operator"": ""Equals"", ""Value"": 1 },
>     {
>       ""Logic"": ""Or"",
>       ""Filters"":
>       [
>         { ""Field"": ""id"", ""Operator"": ""Equals"", ""Value"": 2 },
>         { ""Field"": ""id"", ""Operator"": ""Equals"", ""Value"": 3 }
>       ]
>     }
>   ]
> }");
> fsql.Select<Region>().WhereDynamicFilter(dyfilter).ToList();
> //WHERE id = 1 AND (id = 2 OR id = 3)
> ```
> 
> https://freesql.net/guide/dynamic.html#%E5%8A%A8%E6%80%81%E6%9D%A1%E4%BB%B6
> 
> ![image](https://private-user-images.githubusercontent.com/15613121/328768433-c9d212fc-f459-4e6c-92e5-8c334b8362a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDQ2MjksIm5iZiI6MTcxNTQwNDMyOSwicGF0aCI6Ii8xNTYxMzEyMS8zMjg3Njg0MzMtYzlkMjEyZmMtZjQ1OS00ZTZjLTkyZTUtOGMzMzRiODM2MmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA1MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZjc3Y2Q1Mzk3YTRlZWU3M2Q1NmRiZTY3YzAxMTQ0YTY5MDUwNDY5ODlhY2FkNTEwMGQ2YWRiNTZjNGNlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.60XXm7KPQd7OEac_KDHwa-bNVmN0XjhYe0XenQB64VA)

A very interesting solution that can enhance the value in the business field! I shall continue to track the progress of your work.

**Comment by Piedone** [comment]
Hmm, the documentation is actually wrong, SQL Queries **are** exposed in GraphQL! However, I'm not sure if this ever worked?

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/24dffeab-db97-4034-a928-41ca5a65217b)

Note how the exception message actually includes the correct list of content items that the query matches.

**Comment by gvkries** [comment]
It's actually documented and works as described. You just need to check "Return Documents" on your SQL query as well.

But it is unfortunate, that the unsupported queries are exposed in the GraphQL schema, as they will always fail if they do not return documents.

**Comment by Piedone** [comment]
Ah, I see.
