### ISSUE TITLE
Queries: Access /api from Postman

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1600]
When I try to access locally in my browser to `api/queries/RecentBlogPosts`, the only url that works is the one with `https://localhost:44300/`.
`http://localhost:2918/api/queries/RecentBlogPosts` returns 'The page could not be found.'

Although, if I try to get the json data from this url `https://localhost:44300/api/queries/RecentBlogPosts` in Postman with a header `Content-Type: application/json` or from an HttpClient, it returns the content of the page 'The page could not be found.'

**Comment by Skrypt** [comment]
Have you tried adding the tenant prefix to the url?

**Comment by sebastienros** [comment]
Permissions? Maybe you are authenticated in https only. Allow anonymous access to the query and test again.

**Comment by agriffard** [comment]
OK, if I allow the Anonymous Role on the query, it now works.
