### ISSUE TITLE
RecentBlogPostsQueryTests.ShouldListBlogPostWhenCallingAQuery is flaky

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#16018]
### Describe the bug

The `RecentBlogPostsQueryTests.ShouldListBlogPostWhenCallingAQuery` test can fail randomly, without the code it tests being wrong, and then succeed on the nest run. I.e., it's flaky.

### To Reproduce
I assume that if you run it enough times, eventually, you'll see a random fail. This happened during [this build](https://github.com/OrchardCMS/OrchardCore/actions/runs/9003004131/job/24732624592?pr=16015) too:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/ff56d616-2fc6-44fe-9d55-590175f7752f)

A rerun fixed it. I can't reproduce this locally.

I've seen unit tests being flaky before too, but can't recall any specifics. Please add them here if you notice anything else.

### Expected behavior
The test only fails if the code is incorrect.

### Screenshots
See above.

**Comment by gvkries** [comment]
I think this can happen if the test is executed very fast (faster the the clock resolution). In that case both blog post may have the same `CreatedUtc` and ordering becomes random.
