### ISSUE TITLE
Liquid templates ContentItems property names became case insensitive

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/OrchardCore#16016]
After upgrading from 1.9 to 2.0 we've noticed some of our liquid templates failing with a the error

```ArgumentException: An item with the same key has already been added. Key: Camelcase (Parameter 'propertyName')```

This happend because we are calling ```{{ field.MyProperty.CamelCase.Text }}```

This just so happens that in some time during design and development we misstyped the name of the field and later changed it from ```Camelcase``` to ```CamelCase``` which left us with some harmless rubish in the JSON content... well at least until we upgraded to OC 2.0

{"CamelCase":{"Text":null},"Camelcase":{"Text":null}} 

Is this switch, to case-insensitiveness was done intentionally?

**Comment by Piedone** [comment]
@MikeAlhayek can you comment on this, please?

**Comment by hishamco** [comment]
Might the naming policy have been change after introducing STJ

https://github.com/OrchardCMS/OrchardCore/blob/23ee4f18f6dfda40fa366f58ce2559e270d23b55/src/OrchardCore/OrchardCore.Abstractions/Json/JOptions.cs#L44-L47

**Comment by hishamco** [comment]
I just notice 

https://github.com/OrchardCMS/OrchardCore/blob/23ee4f18f6dfda40fa366f58ce2559e270d23b55/src/OrchardCore/OrchardCore.Abstractions/Json/JOptions.cs#L19

@MikeAlhayek it's on your plate while you complete the JT PR

**Comment by Piedone** [comment]
That's not something we want to change, though. It seems that while the previous de/serialization logic was more forgiving, in the end, the code had a bug that's now surfaced. That's good. We may make the exception more user-friendly though if feasible.

**Comment by SzymonSel** [comment]
What's the bug in particular? 

It is true, that previous de/serialization logic was more forgiving, but the CaseInsesitivity is a mystery for me. I can't see it's purpose.

How do we ensure, this doesn't happen again? The user interface shouldn't allow this.

**Comment by Piedone** [comment]
The code is in your code :). I don't think there is one in OC. Identifiers everywhere in C# and OC are case-sensitive apart from selected cases, so I don't see why we would try to allow case insensitivity for part or field names (which are case-sensitive anyway) in Liquid. (To clarify, what this issue is about is case-sensitivity, not case-**in**sensitivity, since your code worked because previously the serializer was case-insensitive.)

**Comment by MikeAlhayek** [comment]
@hishamco I don't think `PropertyNameCaseInsensitive = true,` has anything to do with this. 

When the `PropertyNameCaseInsensitive` property is set to true during deserializing, it allows you to map a property from any form back into the object.

For example, if you have this class

```
public class Person
{
    public string FirstName { get; set; }	
}
```

you can deserialize this with no problem.

```
{"FirstName":"Mike"}
```

But, the following will only be deserialize correctly if  `PropertyNameCaseInsensitive = true`.
```
{"firstName":"Mike"}
```

I am not very familiar Fluid project which may be the cause of the issue. @sebastienros

**Comment by SzymonSel** [comment]
> The bug is in your code :). I don't think there is one in OC. Identifiers everywhere in C# and OC are case-sensitive apart from selected cases, so I don't see why we would try to allow case insensitivity for part or field names (which are case-sensitive anyway) in Liquid. (To clarify, what this issue is about is case-sensitivity, not case-**in**sensitivity, since your code worked because previously the serializer was case-insensitive.)

- No, you understood me wrong. It's the other way around. I want the indentifiers to be case sensitive, but they aren't anymore in Liquid Templates. Hence after an update to OC 2.0, we started having the above problem. 

We created a field named "Camelcase", then we created some contentItems, the we removed the field "Camelcase" and created a new one named "CamelCase". Everything worked fine until we upgraded to OC 2.0

**Comment by Piedone** [comment]
Ah OK, got it, sorry about the confusion.

**Comment by sebastienros** [comment]
> ArgumentException: An item with the same key has already been added. Key: Camelcase (Parameter 'propertyName')

What is the full stack trace to understand which component is not happy?

**Comment by sebastienros** [comment]
They behave the same, case sensitive https://dotnetfiddle.net/CxK4ls

**Comment by MikeAlhayek** [comment]
@SzymonSel  can you please address the last comments from @sebastienros.

**Comment by SzymonSel** [comment]
Sure, I'll be back shortly with a reply!

**Comment by sebastienros** [comment]
Having the conflicting property names and case insensitivity support works fine with STJ, so this shouldn't be the problem, we'll wait for the stacktrace to understand where it's coming from:

[Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAAwCwAUEQIwX7EAE+VALANy0NMB0AKgKYAPBFwBSAZwD2MdpU5Veg4eKlcAchIx8xMigDcIyegGMIYPgBsAwhDF96AXnow+Ad3rKYAZT7IoEc1AAXj4A8gAOCFBSYgAUAJT0FPQA3onk9BkZAArIEmE+CACeqqawAOZZEgFGhQ7ukjAlYOWV1YVc1mZWNnxwaZn0OXkFxaZ81rYAkjC2M1CRunaOCGh8SQC+rGl6BvQAVg11AEQnSZnJR50WJrZHIEfAR3CXY9239xBH6xQnRzIDO0MYTqHm8vn8QR8XAAIlofH4AsEADxZHwNAB8MQOUj6Ji6Ez4cRkTAAnDEwh1XgSiZlaABmRiEQZoqQUZJnDL4BlMBhXN52ZJlPgIVi2EXfcgSihAA=)

**Comment by sebastienros** [comment]
If possible see the liquid template that failed with such data. To get the data, create a TextField then another one with the similar name (might need to remove the previous one, the data will be kept in the json document)

**Comment by SzymonSel** [comment]
> If possible see the liquid template that failed with such data. To get the data, create a TextField then another one with the similar name (might need to remove the previous one, the data will be kept in the json document)

I'm unable to recreate the error (due to time constraints). I played around a bit and couldn't recreate the issue without manualy changing the JSON in the DB, hence this was a distant edge case. When migrating feom some older OC version.

I doubt anyone will ever experience it again.

Case closed!
