### ISSUE TITLE
Creating Own content

### ISSUE THREAD

**Issue by DJ-Paxton** [OrchardCMS/OrchardCore#16022]
Hi all, I'm trying to do a collaborative website where multiple people can create and update content.
In a previous project I created roles for specific `ContentTypes` and that worked fine, but because of the nature of this actual project I need multiple users to work with the same types and I found my workaround with Ownership.

So, what I'm doing at the moment is using my Admin account to change the `owner` of the content item with the owner editor,

![Screenshot 2024-05-10 115523](https://github.com/OrchardCMS/OrchardCore/assets/61999532/98942a3e-852e-4041-884d-ff77c125dde7)
![Screenshot 2024-05-10 115610](https://github.com/OrchardCMS/OrchardCore/assets/61999532/19632b77-a6bc-4e98-a2b4-2533089ca46f)

and I created a role that only allows to Edit Own content.

![Screenshot 2024-05-10 115724](https://github.com/OrchardCMS/OrchardCore/assets/61999532/1f3879b4-1bcd-47ad-94f8-9ed2dd222d0a)

![Screenshot 2024-05-10 113734](https://github.com/OrchardCMS/OrchardCore/assets/61999532/f7138875-7a18-48bc-aef7-686085bd389a)

The issue is I want that user to be able to `create` content, 
The Owner Role has the `Edit and Publish or unpublish Own content` permission enabled but it doesn't allow to create content (in green), then I can enable `Edit or Publish for others` (in red) and the user will be able to create content, but also modify content that's not owned by him.

![Screenshot 2024-05-10 114145](https://github.com/OrchardCMS/OrchardCore/assets/61999532/005d52af-ea45-4cd2-9e5b-77e9c2581b07)

When I save the for others permissions:

![Screenshot 2024-05-10 114826](https://github.com/OrchardCMS/OrchardCore/assets/61999532/97b4eccb-e02a-4ca6-9d08-a745dd8cbacc)

The user can create content (green) which is good, but also modify content that doesn't belong to him (red) which is bad.

Is there any option that I'm missing or some permission I'm doing wrong?
Thanks for the help!

**Comment by hishamco** [comment]
Try to logout then login after you apply the permissions changes

**Comment by sebastienros** [comment]
I believe "Edit and Publish or unpublish Own content" should be sufficient to create a new content item.

What I think is happening is that we always check for the common permission (not "own") and then a handler will grant it if the corresponding "own" permission is set and the content item is owned by the current user. However here there is no content item yet, so we can't rely on the handler, hence the Creation checks should check for either role without a content item.

But we also need to check if the issue is not only in the UI (not rendering the button because of that) and the actual controller is accepting this call just fine.

**Comment by gvkries** [comment]
Works for me with the main branch... 🤷‍♂️

**Comment by Piedone** [comment]
So, this may be already fixed. @DJ-Paxton could you please check with the [latest preview packages](https://docs.orchardcore.net/en/latest/getting-started/preview-package-source/) or with the source in `main`?

**Comment by DJ-Paxton** [comment]
Sorry, I couldn't test the latest version, you can close this. Thanks for your help!

**Comment by Piedone** [comment]
Thanks!
