### ISSUE TITLE
Unnecessary placement rules in OrchardCore.Contents

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#16028]
Currently in OrchardCore.Contents module there is  a placement rule in placements. json as so : 

```
 "Content_PublishButton": [
    {
      "place": "Actions:5" // Same as in the driver
    }
  ], 

```
Apart from that the placement is already set from the driver this prevents other modules to add there own placement rule for this shape unless they take a dependency on this module. 

Also there  is a placement rule : 

```
  "Content_SaveButton": [
    {
      "place": "Actions:6" // Move the save button after the publish
    }
  ],

```

that is not used anywhere as there is no shape with this name.
 I propose to remove these 2 rules.

**Comment by Piedone** [comment]
To clarify, do you only suggest removing the two Placement.json rules, or do you think the dependency being needed is also a bug? I agree with the former, not the latter.

**Comment by giannik** [comment]
no ,  adding a dependency is not a bug. But my understanding is that the 2 placement rules serve no purpose so just remove them to avoid confusion and the need to add the dependency.

**Comment by Piedone** [comment]
OK, thanks for the clarification!
