### ISSUE TITLE
`OrchardCore.Users` - a service to decide which kind of parameter use to link external login to existing account in the second check

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#16026]
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/16023

Each module that add an extenal login provider (like GitHub or OpenID) can specify the value of `ClaimTypes.NameIdentifier` to link the external login information to an existing OrchardCore account. 

But in this line of code, OrchardCore force another check over external login data that could redirect a user to a view that ask about link external login data to an existing account by checking the email value returned by the login provider.

https://github.com/OrchardCMS/OrchardCore/blob/649b7404d3b1d387be936d2d77430e387c5aee20/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AccountController.cs#L387-L415

I would like each module that add an external login can manage this behavior by a dedicated service. If a module doesn't implement this service:  the actual behavior is applied.

Probably could be useful to have a settings to disable this code.

I'm not sure if this "second check" over external login data is correct or it's nature: seems a second chance to connect external login data to user account.

**Comment by PiemP** [comment]
> Would you like to venture into contributing this?

Yes... this week I have some issue at home but next week I try to build something that, I hope, are acceptable.

**Comment by Piedone** [comment]
Thank you!

**Comment by Piedone** [comment]
See https://github.com/OrchardCMS/OrchardCore/pull/16110#discussion_r1640060216 for a description of the use case of this issue in detail.
