### ISSUE TITLE
Allow Multi Part Tenant URLs 

### ISSUE THREAD

**Issue by clmcgrath** [OrchardCMS/OrchardCore#1603]
Currently  if you try to use a slash in a tenant URL it will give an error disallowing you to use the url 
ie http://www.testsite.local:8080/tenants/MyTenantSite

I f you try to force it in by using the domain name and prefix it completely breaks,  and in some cases put the port number in the wrong place if using a port number in the domain prefix 

 ie entering localhost:1058/artists/ as the hostname results in urls being misformatted to http://localhost:1058/artists:1058/krista-herzog

if try using the expected url it redirects to the root site 
ie http://localhost:1058/artists/krista-herzog  return the content for  http://localhost:1058/

![image](https://user-images.githubusercontent.com/452012/37311448-a4291fc2-261d-11e8-9472-aa39974f6e7d.png)

**Comment by cwojke** [comment]
I encountered similar issue, I needed to set context.Request.PathBase because I needed to access tenants on prefixed path behind reverse proxy.  

Anyway I know where this issue comes from. There is a method GetHostAndPrefix in RunningShellTable class and it takes only the first segment of the path as tenant prefix:

```
// appRelativePath starts with /
var firstSegmentIndex = appRelativePath.IndexOf('/', 1);
```

**Comment by jtkech** [comment]
Yes this is a wrong usage of the host name

Yes the tenant prefix allows only one segment

Behind a proxy, it depends on the allowed configurations, you may have to use a map / use middleware to act on the request `PathBase` and or `Path`.

And some little tweaks has been done around the host name string

Feel free to re-open the issue if you still have any problem
