### ISSUE TITLE
The href of ContentLinkTagHelper is none when customizing list page include two kind of content type.

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#16042]
### Describe the bug
The href of ContentLinkTagHelper is none when customizing list page include two kind of content type.
### To Reproduce
1. Create a query of contentItem include two kind of content type
2. Create two customizing .Summary.cshtml, code snippet as follow:
// Content-contentType1.Summary.cshtml and Content-contentType1.Summary.cshtml is same
```
@inject IContentItemDisplayManager _contentItemDisplayManager
@using OrchardCore.ContentManagement
@using OrchardCore.ContentManagement.Display
@using OrchardCore.Media.Processing
@using OrchardCore.Mvc.Utilities
@{
    var titleText = Model.ContentItem.DisplayText;
}

    <a display-for="@Model.ContentItem" aria-current="true">
        <span>@titleText</span>
    </a>

```
3. The list page nomally render list of <a> link
4. The href of <a> link from contentType1 is nomal
5. The href of <a> link from contentType2 is none

**Comment by effapp** [comment]
OrchardCore version : 1.8.3
ContentType1 <a> render result:
![image](https://github.com/OrchardCMS/OrchardCore/assets/51013754/9d2e3761-6b0e-470a-afc0-ee83721521f6)
ContentType2 <a> render result:
![image](https://github.com/OrchardCMS/OrchardCore/assets/51013754/f226f627-d6da-44eb-a3a5-332c95f721f7)

**Comment by sebastienros** [comment]
Looks like the tag helper is not rendered which is usually because the tag helper namespace is not imported. However it works in the first view. Are the two views in the same folder such that the _ViewStart works for both (and imports the tag helper)?

**Comment by effapp** [comment]
The two views aren't in the same folder. It works after importing the tag helper in _ViewStart of second views.
Thanks.
