### ISSUE TITLE
Show recipe error instead if throwing an exeption

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16056]
Currently when importing a recipe and something goes throw, an exception is thrown. In a production environment, the user gets a white page which leaves them lost on what had happened. 

Instead, we should catch these exceptions and show the error to the user so they have feedback instead of dumping exception or a white page.

**Comment by MikeAlhayek** [comment]
@hyzx86 I thought you had a PR or an issue for this that i can't find. If not, do you like to submit a PR for this?

**Comment by hyzx86** [comment]
But how do we do that? Do we just output the description of the internal exception to the user? Use `Notify.ErrorAsync`?

**Comment by MikeAlhayek** [comment]
@hyzx86 you can just use ModelState to add an error to the recipe input.

**Comment by hyzx86** [comment]
Just like this ?

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/40b0e414-b8f6-4d02-9c5f-5d0296da6464)

**Comment by Piedone** [comment]
That looks good, just please don't output the exception message.

**Comment by MikeAlhayek** [comment]
Yes that looks good to me. Probably better not to color the JSON on the input.

At least with this we get feedback on what the error could be.

**Comment by hyzx86** [comment]
Just like : `Import failed, see the server log for details.`  ？

But if the error message is not displayed, the user has to check the server log. 

I feel that the import function should be for administrators, even if some security related information is exported in between.

**Comment by MikeAlhayek** [comment]
I think we should write the message from the exception. Each step controls the message of the exception so I think it is safe to make that visible. Otherwise, yes the user has no idea why it failed. The importing user may not have visibility into the log file in most cases 

@Piedone thoughts since you suggested against that?

**Comment by Piedone** [comment]
The problem is that an exception can potentially include technical details that the user can't do anything about, or worse, expose private information. If we have a specific type of exception just for this (in O1 we had one with a localized message) then OK, but displaying just any exception is risky.

**Comment by MikeAlhayek** [comment]
@Piedone Another options would be to add a new property to https://github.com/OrchardCMS/OrchardCore/blob/6679b28e0b3cd2a5246b12ab50ed331e9efaf84e/src/OrchardCore/OrchardCore.Recipes.Abstractions/Models/RecipeExecutionContext.cs#L6 that would collect errors like a Dictionary of some sort So that this way each implementation of IRecipeStepHandler can add an error instead of throwing an exception. 

Then in the controller, we can say step ABC failed with these errors. and if there is an exception with no errors provided by the step, we can display a generic message like "Failed to import the given recipe due to unknown error."

But we should try to provide guidance with these errors otherwise the user will be in the dark since the recipe can fail for many reasons.

**Comment by Piedone** [comment]
That would be an option too, or a `ModelStateDictionary`. Note though that some issues must halt the import process between two steps, so if not with exceptions, then somehow else that should still happen.

**Comment by MikeAlhayek** [comment]
in the recipe executor, we can check for errors before proceeding to the next step to ensure the existing logic stay intact. This chance will need to be documented [here](https://docs.orchardcore.net/en/latest/reference/modules/Recipes/#recipe-steps) and also added to the change log so that anyone is implementing a custom step, they can set the errors instead of throwing exceptions.

**Comment by hishamco** [comment]
@MikeAlhayek I remembered @hyzx86 submitted a PR for this last few weeks, right?

**Comment by MikeAlhayek** [comment]
No. There was a PR that throws an exception. Here we write exception and provide guidance instances of throwing an exception
