### ISSUE TITLE
Template Preview doesn't show anything

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#16072]
### To Reproduce
1. Go to 'Design'
2. Click on 'Templates'
3. Create a new template
4. Click on 'Preview'

### Expected behavior
Shows a template for a certain content type

**Comment by hishamco** [comment]
@Piedone this is not my first issue, seems the bot drink something, so it doesn't aware about the old issues :)

**Comment by hishamco** [comment]
I just noticed this while I was working on `OrchardCore.Website`, @agriffard could you please confirm or it's due a permission restriction

**Comment by Piedone** [comment]
Oh wait, I misunderstood, and tried content preview. Template preview indeed is broken.

Looking at the Template module's `PreviewController`, I don't really see how it was ever supposed to work.

**Comment by hishamco** [comment]
> Oh wait, I misunderstood, and tried content preview. Template preview indeed is broken.

I expect that :)

> Looking at the Template module's PreviewController, I don't really see how it was ever supposed to work.

I will have a look. I'm not sure how the template is rendering without data?!! Maybe to see what it looks like

**Comment by MikeAlhayek** [comment]
> this is not my first issue, seems the bot drank something, so it isn't aware of the old issues :)

This is just a wake up call so you can submit more issues :)

**Comment by hishamco** [comment]
[This](https://github.com/OrchardCMS/OrchardCore/pull/9889/files#diff-1f97f7afe498a1f42c763e9f486208557c21a1fd579fb7edabe7f624cc017fb8L7) was the first issue I just found, seems no one click that button from 3 years :)

**Comment by MikeAlhayek** [comment]
@hishamco I think this issue was introduced after the major BS 5.3 upgrade

**Comment by hishamco** [comment]
I don't know but the script reference is missing
