### ISSUE TITLE
Wrong example in RecipesStep

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1608]
There's a comment in OrchardCore.Recipes.RecipeSteps.RecipesStep as example usage but it's wrong since the step will be casted to an `InternalStep` which doesn't have a recipes property, only a Values property. So either rename the property or fix the comment. A documentation about this step would be useful too.
```
         {
            "name": "recipes",
            "recipes": [
                { "executionid": "OrchardCore.Setup", name="Core" }
            ]
         }
```

A sentence about what to set as the executionid would be useful too.

**Comment by jtkech** [comment]
Yes, you're right, maybe you want to do a PR for this, otherwise i will do a patch.

**Comment by sebastienros** [comment]
@alberthajdu not sure how familiar you are with GH's web interface, you can do little changes like this directly from the browser and do a PR in one click. We usually pull these kind of PRs in a matter of hours, or as soon as we see it.

**Comment by alberthajdu** [comment]
@sebastienros thank you for the tip I will try it next time, it's probably quicker than trying to explain it in an issue.

**Comment by alberthajdu** [comment]
Fixed in https://github.com/OrchardCMS/OrchardCore/pull/1642
