### ISSUE TITLE
Consider introducing ShellSettings.Id

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#1610]
We're currently using `ShellSettings.Name` as a stable tenant identifier for the Data Protection services (it's also heavily used in my last PR to determine token audiences).

Unfortunately, this is not an ideal candidate as the tenant name can be accidentally re-assigned to another tenant (after deleting the existing one). It has security implications if the tenant is managed by someone else, as data encrypted by the removed tenant could be decrypted by the new tenant (since they share the same name).

To fix that, I suggest introducing a new opaque `Id` property (typically... a GUID) we can safely use for isolation purposes.

/cc @sebastienros

**Comment by sebastienros** [comment]
We actually have private keys in this files, or at least we have an issue to generate it. I can show you how it is in O1. I think we should use it, but the idea is exactly the same so I agree with the initiative.

**Comment by sebastienros** [comment]
It's not about privacy of the value, it's that we already need a key for secrets anyhow, and it's stored in the same file, ~~and we already have a field for it~~. 

Well apparently we didn't create the field yet, so it's fine creating a new Id in the shell settings.
Around here: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Setup/Services/SetupService.cs#L116

Just add a property to `ShellSettings` and it should be stored automatically.

**Comment by sebastienros** [comment]
As part of your PR?

**Comment by PinpointTownes** [comment]
What should we use? A GUID? Or a shorter thing?

**Comment by sebastienros** [comment]
you can use the `IIdGenerator` if it's available (shorter, readable guid). Otherwise guid.

**Comment by PinpointTownes** [comment]
Nice. Looks like `OrchardCore.Entities` is indirectly referenced by the setup module, so that's fine.

**Comment by sebastienros** [comment]
The workflow branch is moving it to a more common package. This won't be an issue either.

**Comment by PinpointTownes** [comment]
I'll do that in a future PR, as this is a quite massive change that deserves a dedicated PR.

**Comment by PinpointTownes** [comment]
Note: now that tenants have their own key ring, doing that is way less interesting (since the keys wouldn't be preserved after re-creating a tenant with the same name, the new tenant couldn't decrypt payloads encrypted by the former tenant)

**Comment by sebastienros** [comment]
Close if you think that's not necessary anymore.

**Comment by PinpointTownes** [comment]
Reopening for consideration, as it would be very useful in some scenarios: https://github.com/OrchardCMS/OrchardCore/pull/4309#issuecomment-532668220

**Comment by sebastienros** [comment]
Ok, I am fine with it. Tenant names can be spoofed, not automatically generated guids (or at least not without system privileges).

Guid is fine, also is the format for content item ids (guids to base26 with improvements). Can be defined when the new tenants are created.

**Comment by agriffard** [comment]
Shell Settings has an Identifier:
https://github.com/OrchardCMS/OrchardCore/blob/efa351a3ebd2cf32a18ca089ffcfa3b8984b902b/src/OrchardCore/OrchardCore.Abstractions/Shell/ShellSettings.cs#L41

Can this be closed @kevinchalet ?

**Comment by kevinchalet** [comment]
@agriffard looks like it's very recent so I suspect none of the code paths we discussed have been updated to benefit from it. Things like cookie names in the Users module or tenant audiences in the OpenID module would be great candidates.

Also, do we know why a `string` rather than a `GUID`, that would have less encoding implications?

**Comment by jtkech** [comment]
@kevinchalet @agriffard 

I introduced it but not for the same purpose ;) It's not to identify a given tenant, It's for consistency checking when we update its shell settings, so it changes each time we update the shell settings of a given tenant.

                settings = await _shellSettingsManager.LoadSettingsAsync(settings.Name);

                // Consistency: We may have been the last to add the shell but not with the last settings.
                if (settings.Identifier == currentIdentifier)
                {
                    return;
                }

**Comment by kevinchalet** [comment]
@jtkech hum, then maybe `Version`, `Timestamp` or `ConcurrencyCheck` would have been better names? If we decide to introduce a real ID property later, having both `Id` and `Identifier` will be very confusing.

**Comment by jtkech** [comment]
@kevinchalet i agree, i will do it
