### ISSUE TITLE
How to embed template inside a template

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#1611]
I created 2 tempaltes:
- Common template named is **Content__About**
- Private template named **LandingPage__About** for **Content__LandingPage**.
How can I use 2 template inside **Content__LandingPage** template?

**Comment by Skrypt** [comment]
As stated in the Liquid documentation you should use {% include 'template_name' %}

http://www.rubydoc.info/github/Shopify/liquid/Liquid/Include

Not sure if this works though I've not tested.

**Comment by lthoa** [comment]
Thank you. It not works.

This is Home page tempalte on web editor of TheAgencyTheme.
The "Content__LandingPage" template too long with many modules inside, I want to break it into modules-templates separate

**Comment by sebastienros** [comment]
These are shape templates, try to render a shape with this name, like `{% shape "foo_bar" %}`

**Comment by lthoa** [comment]
How can I passing data to a shape and using received data?
The example below does not work:

In Content__LandingPage template:
{% shape "Content__About" for Model.ContentItem.Content.About %}

In Content__About template:
{% if Model.ContentItem.Content.About.ContentItems.size > 0 %}
....
