### ISSUE TITLE
Unable to enable 2FA using email when the email is not verified

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16129]
### To Reproduce
1. add user
2. make sure the user email is not verified 
3. let the user try to enable 2FA using email method.
4. This generated a very long token that isn't numeric. So it's can't be used for verification.

### Expected behavior
The token should be a 6 digit numeric valid

**Comment by hishamco** [comment]
How the 2FA code will be send if the email is not configured?

**Comment by MikeAlhayek** [comment]
The email will be already configured. The issue isn’t sending the message. The issue is with the generated token. The referenced PR fixed the issue.

**Comment by Piedone** [comment]
I'd rather display a message that you should verify your email first, and prevent enabling 2FA until then. Otherwise, we can't make sure the email will actually arrive.

**Comment by MikeAlhayek** [comment]
> I'd rather display a message that you should verify your email first, and prevent enabling 2FA until then. Otherwise, we can't make sure the email will actually arrive.

I did exactly that in the referenced PR.
