### ISSUE TITLE
Create a blog post, add a media image to the body, and do not display pictures after posting

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1612]
Create a blog post, add a media image to the body, and do not display pictures after posting。
`创建博客文章，Body 中添加媒体图片，发布后，不显示图片
`

Insert a picture in the Wysiwyg editor editor, the picture capture path "192.168.1.6/blog/blogPost.jpg"
The real path is "192.168.1.6/media/blogPost.jpg"
```
Wysiwyg editor 编辑器中插入图片，图片获取路径“192.168.1.6/blog/blogPost.jpg”
而 真实路径是“192.168.1.6/media/blogPost.jpg”
```

**Comment by Skrypt** [comment]
I just tested and it works for me.
When adding the image with the editor it appended {{ "drib3b.jpg" | asset_url | img_tag }} to the content. When I published the post it converted it to <img src="/theblog/media/drib3b.jpg" />

**Comment by pgy866** [comment]
@Skryp   
![1](https://user-images.githubusercontent.com/28694676/37470129-cb5dc242-28a1-11e8-8197-97ffea33bf7d.gif)

**Comment by sebastienros** [comment]
Good catch, that's a bug
