### ISSUE TITLE
Cannot login to admin area in a clean nuget base OC instance

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#1613]
Just updated nuget packages to beta2-4892 and can no longer login to the admin area. When entering a valid username and password, I am returned to the login screen with no error. If I enter an invalid login, I return to the login screen with an error.

I just created a new project and followed the basic steps to create an OC application (http://www.ideliverable.com/blog/getting-started-with-orchard-core-as-a-nuget-package) and replicated the issue.

**Comment by sebastienros** [comment]
You logged once in https, not you are on http, and the cookie can't be set because it already exists, but you are in http so you don't see the https ones. Try to use the https endpoint, or clear you cookies then go back to http.

**Comment by sebastienros** [comment]
Maybe I closed it too quickly, just reopen if my instincts were wrong
