### ISSUE TITLE
Background and foreground colors for hovered wysiwig/trumbowyg editor buttons are almost indistinguishable

### ISSUE THREAD

**Issue by rwawr** [OrchardCMS/OrchardCore#16137]
### Describe the bug
In dark mode, the foreground color of the wysiwig/trumbowyg editor buttons is almost indistinguishable from the background color when hovered or focused. This does not appear to affect 1.7.2, but I believe it does affect 1.8.0 and up.
![image](https://github.com/OrchardCMS/OrchardCore/assets/153218770/d8fdeb11-ca75-4e4e-92a7-597e1b6d2537)

### To Reproduce

1. Cook a new Orchard Core 1.8.2 site using the "Agency" recipe
2. In the admin panel, go to **Content > Content Definition > Content Types**, and Edit the Html widget type
3. Edit the "Content" HtmlField field and select "Trumbowyg editor" or "Wysiwig editor" for "What type of editor should be used?"
4. On the **Design > Widgets** page, add an Html Widget
6. Set the admin theme to dark mode and notice that hovering over any of the buttons in the trumbowyg/wysiwig editor makes the background white but does not adjust the foreground color to stand out against the white background.

### Expected Behavior
Editor buttons should have a foreground color that stands out from background when focused/hovered.

**Comment by hishamco** [comment]
@rwawr did you try it in the latest bits?

**Comment by rwawr** [comment]
@hishamco Yes, I just synced my fork and tried again, and the issue is still occurring for me.
