### ISSUE TITLE
Changes made in admin not visible after save (until the page is refreshed) if Redis caching is enabled

### ISSUE THREAD

**Issue by mvarblow** [OrchardCMS/OrchardCore#16146]
### Describe the bug

If I enable the Redis caching module and then make a change in the site admin, the change is saved but not reflected immediately. Specifically, this behavior seems to be consistent when changes are made to a role or to audit trail settings. In both cases, after POSTing the change, Orchard Core redirects to a GET endpoint. The "document" that's rendered by the GET endpoint does not reflect the update that was applied by the POST. However, if I refresh the page, then it does reflect the change.

I noticed this problem when trying to add a simple database cache (IDistributedCache) to avoid the Redis requirement when deploying multiple instances. The problem manifested but it didn't seem to be caused specifically by the IDistributedCache implementation I created (very simple). So I cloned the OrchardCore dev branch this morning and fired it up using the Agency theme with Redis configured in appsettings. The same problem occurs with the Redis distributed cache feature enabled. So it doesn't seem to be the IDistributedCache implementation that's the problem. It must be something about how OrchardCore is using the cache. 
 
### To Reproduce

1. Clone the OrchardCore dev branch.
2. In OrchardCore.Cms.Web\appsettings.json, uncomment the OrchardCore_Redis section and configure it to use a local (or cloud) redis installation. I used podman with the docker.io/redis container image.
3. Start OrchardCore and complete setup. I used the Agency theme.
4. Sign in to the OrchardCore admin and enable the Redis Cache feature.
5. Go to the Roles page. 
6. Click edit on a role (e.g. Moderator). Change the role description (e.g. from Moderator to Moderators).
7. Press Save. You're taken back to the Roles index. Notice that the role description has not changed. It still shows the original value (e.g. Moderator).
8. Refresh the page. Notice that the role description now *does* reflect your change (e.g. Moderators).

If you enable the Audit Trail feature then the problem is even more pronounced on the audit trail settings page. 
1. Uncheck a few boxes and press save.
2. The response in this case, after POSTing the changes, is a redirect to a GET of the audit trail settings. It should reflect your changes. It does not. This behavior is even more confusing for the user on this page.

### Expected behavior
After making a change in the admin, the change should immediately be reflected on the page that's returned.

### Screenshots

Roles list before making changes:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/ac102551-dd12-4bad-a2e8-7699046de333)

Edit the role description:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/44674e27-474c-4893-8abb-ee59f4087d7c)

Saved the change; the change is not reflect in the response:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/0bb4d70d-6289-42ce-b449-c849e56b3fff)

Refresh the page; the change is now reflected in the response:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/e24d3db8-fdaa-4b61-91f8-aea287e373a4)

Initial audit trail settings:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/9338b232-ba4f-4271-9c44-469eab5540ac)

Make some changes. Before pressing save it looks like this (for example):
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/458e4521-d287-4b9d-9281-db4913ab656b)

Press Save. Your changes appear to be lost:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/44dbe3be-1446-4271-a56d-e0b9512e5197)

You could easily save again and lose your changes. Or you could refresh the page and suddenly your changes appear:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/454fc823-6160-417f-bcfc-0f510b332745)

**Comment by mvarblow** [comment]
By the way, the same behavior exists in 1.8.3. That's where I initially saw the problem before I tried to reproduce it (see above) in the dev branch with the latest commits.

**Comment by mvarblow** [comment]
Another note: this problem is difficult to debug. For example, just setting a breakpoint here is enough to make the problem not reproduceable:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/a79cb69a-bc48-4213-9c73-cd4d80a1bf17)

Stepping through the code in general seems to make the problem go away. It seemed to me that the above line of code must be executing too late. I was surprised to find that if I only break at this one location then I still cannot reproduce the problem. In fact, even if I move my breakpoint down after that line, I still can't reproduce the problem with the breakpoint set.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/2086d99b-9c93-4574-ad27-8e4c2eae8649)

However, disable the breakpoint (run with no breakpoints active) and it happens for me every time.

**Comment by mvarblow** [comment]
It turns out that you can't reproduce it if you hit a breakpoint because of the 1 second in-memory cache.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1827487/f02c4a11-855d-4c1a-9492-a8849b074fb0)

If you break for more than a second then that cache times out and you read from the distributed cache which has been invalidated. The problem is that when OrchardCore invalidates the cache, it was *only invalidating the distributed cache. It needs to *also* invalidate the in-memory cache. See my pull request which updates the DocumentManager.InvalidateInternalAsync method to invalidate both caches if there is a distributed cache in use.

**Comment by mvarblow** [comment]
@Piedone I'm surprised you haven't run into this problem on your DotNest platform? I assume you must be using the Redis cache? 

I could reproduce this consistently on the roles page with just a single instance, though I expect that the problem would also manifest on and off (or consistently with sticky session ARR) when running with multiple instances. With a single instance, it only goes away if things are slowed down (e.g. the redirect to the GET endpoint takes long enough that the 1s in-memory cache expires). With multiple instances, you wouldn't see the problem if the GET request was sent to another instance which didn't have a fresh copy of document in the local (1 second) in-memory cache. So it might happen less consistently with multiple instances but would still happen at least sometimes. 

Reducing the synchronization latency to a few milliseconds (from the default 1 second) might work around the problem, though I wonder what other problems that might introduce and would prefer not to use that workaround.

**Comment by Piedone** [comment]
We don't use Redis with DotNest. Thanks for the fix, we checked it during today's [triage meeting](https://docs.orchardcore.net/en/latest/docs/resources/meeting/).

**Comment by mvarblow** [comment]
@Piedone Interesting. May I ask, if you don't use Redis, have you found that you don't need it to run on multiple instances? Or perhaps you don't currently run individual tenants concurrently on multiple instances? 

There doesn't seem to be any comprehensive documentation today on setting up Orchard Core to run on multiple instances. And I'd actually prefer to be able to do so _without_ having to add another infrastructure component (e.g. Redis). I was planning to use a SQL Distributed Cache implementation (along with a SQL-based distributed lock and distributed signals implementation). But I'm curious about the experience others have had with running Orchard Core on multiple instances.

**Comment by Piedone** [comment]
Since we use [idle shutdown of tenants](https://github.com/Lombiq/Hosting-Tenants/tree/dev/Lombiq.Hosting.Tenants.IdleTenantManagement), the number of tenants actually running at a given time is a fraction of the total tenants. So, no horizontal scaling was needed (and in fact no automatic scaling at all).

Good point about not having to use Redis. This is not the first time this came up, so I opened https://github.com/OrchardCMS/OrchardCore/issues/16149, please share your experiences there.

Also see https://github.com/OrchardCMS/OrchardCore/discussions/16046.
