### ISSUE TITLE
/Localization/[CultureName]/[ModuleId].po PO file location doesn't work

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#16153]
### To Reproduce
 Hi all, I've found that this rule mentioned in this document https://docs.orchardcore.net/en/latest/reference/modules/Localize/ doesn't seem to work
`/Localization/[CultureName]/[ModuleId].po`
This is a module based on OC 1.8.3
![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/f3a896e4-d2e7-4bbd-b09b-8ecb5326e259)

But when I use `Localisation/zh-CN.po` it works fine

Since this template `Localisation/[CultureName].po`  will overwrite the translation files of the other modules when compiled and packaged.
I would prefer that the template `/Localisation/[CultureName]/[ModuleId].po` works.
When I run it on 1.8x it doesn't work as expected.

**Comment by hishamco** [comment]
Seems you started a PR for this, if you are interested it's in your plate otherwise I will create another one

**Comment by hyzx86** [comment]
> Seems you started a PR for this, if you are interested it's in your plate otherwise I will create another one

I am not familiar with this aspect.

**Comment by Piedone** [comment]
Shouldn't these locations rather work, @hishamco?

**Comment by hishamco** [comment]
They should, but we need to ensure the case that Tony reported still worked as expected, @hyzx86 I suggest creating a minimal repo, and then we can check.

**Comment by hishamco** [comment]
What I'm asking for is a repo to ensure that there's a bug, but not miss configuration by you :)

**Comment by sebastienros** [comment]
The code that loads these files is in `ModularPoFileLocationProvider`. A breakpoint should help understand why the file is not loaded.

**Comment by JulioAmestica** [comment]
the problem could be the ZH-CN language is not present in DefaultPluralRuleProvider. question, why are the languages hard coded??
By the way (the iso 639-1 defines languages codes)[https://www.andiamo.co.uk/resources/iso-language-codes/]

**Comment by hishamco** [comment]
This should handle Chinese cultures

https://github.com/OrchardCMS/OrchardCore/blob/ba5e8c03c8f3aef138651184317e4859dab7adfd/src/OrchardCore/OrchardCore.Localization.Core/DefaultPluralRuleProvider.cs#L61-L73

**Comment by hishamco** [comment]
@hyzx86 please is this still happening with you

**Comment by hyzx86** [comment]
> the problem could be the ZH-CN language is not present in DefaultPluralRuleProvider. question, why are the languages hard coded?? 

Like Hisham mentioned, code, because there's also a concept of hierarchy here

@hishamco It may be necessary to add some unit tests to ensure that `zh-CN` is recognised as `cn`.

**Comment by hishamco** [comment]
(https://github.com/OrchardCMS/OrchardCore/blob/2772ac6abbddd5af4f6444420bfc6ef031595409/test/OrchardCore.Tests/Localization/DefaultPluralRuleProviderTests.cs#L7-L27)

**Comment by hyzx86** [comment]
First , we do not support the format `/Localisation/[CultureName]/[ModuleId].po` as mentioned in the documentation.

So I added this logic here, but it still doesn't seem to work https://github.com/OrchardCMS/OrchardCore/pull/16154/files#r1670823332

The debugging information is as follows

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/53e0b725-c4e9-4e4a-87f7-3f878aa053fa)

The full test code is here 
https://github.com/OrchardCMS/OrchardCore/pull/16154/files#diff-96bb404a36e5e90d674923486169524bd90cc1a6a7d6f58f1f9aa7f3b22968ba
