### ISSUE TITLE
Page load incomplete for some backend templates

### ISSUE THREAD

**Issue by bashuss** [OrchardCMS/OrchardCore#16179]
Version 2.0.0-preview-18222
### Describe the bug
When opening existing liquid templates from the backend, some are not loaded correctly. In some cases reloading the page in the browser will solve the problem, in some cases it does not. To me this looks like a kind of race condition, dependent on the content of the template.
Some templates load just fine, others always create problems, some can be fixed by reload, other templates don't don't even all the page loading at all: window stays white and empty.
The whole page seems to be loaded incompletely, as the save dropdown does not work, when content is missing.

I do use backend templates quite a lot (60 templates!) in this tenant. This may also make a difference for reproducing race conditions.
It may be related to filtering the templates with search first.

![image](https://github.com/OrchardCMS/OrchardCore/assets/36511996/ac720772-4c19-49ce-9298-a4dc4dedd84e)

### To Reproduce
1. Go to /admin
2. Go to "Design" -> "Templates"
3. Type a part of the template's name into the search
4. Open the template by click on the name
5. See error - or not

### Expected behavior
should always load properly

**Comment by Piedone** [comment]
Since I can't reproduce it with some mock templates, I guess the issue has something to do with the content of the templates.

1. Can you please try to reproduce this with the dev console open, and see if any JS or other errors show up there?
2. Can you share the details of a template (all details, name, description, content), with which you've seen this happening?

**Comment by Piedone** [comment]
Thanks!

1. I mean, do you see such errors?

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/d60ebac4-7e4e-439c-9d98-6e74f225e704)

Or perhaps under Network (these are all successful requests, unsuccessful ones will show up in red):

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/396e1ba5-c228-4cb2-ba07-9451a07381db)

2. You can just copy-paste the three fields' values here in a fenced code block. A single template will be enough for now.

**Comment by sebastienros** [comment]
We need to confirm it's working with the same amount of templates (or more). If we store all the templates in a single document that could be a problem.

**Comment by bashuss** [comment]
> 1. I mean, do you see such errors?
> 
No, I did not see any Javascript errors - just what I posted. But I am not used to working with Edge Browser developer tools, which currently is the only browser on my development system. I hope I did not miss it.
I'll double check this weekend.

I'll also post some content for this then:
> 2. You can just copy-paste the three fields' values here in a fenced code block. A single template will be enough for now.

**Comment by Piedone** [comment]
Thank you!

And just to confirm: You see all of this with an app running locally, without any users, using SQLite, right?

**Comment by bashuss** [comment]
No, not SQLite - DataBase is a web based SqlServer. OC is running locally in Debug from VS2022. TheAdmin Theme is used from nugget packages with the rest of OC, so it should be the latest version, too.

**Comment by bashuss** [comment]
>2. You can just copy-paste the three fields' values here in a fenced code block. A single template will be enough for now.

This is the data corresponding to my initial screenshot above. Currently this data loads without any trouble, but others do not load properly now. I do not think, that it depends on the data. 
It **may** be related to the search before opening the template, as templates seem to open properly from the normal listing. I just observed this:
When I start the OC go directly to templates, go directly to search "menu" and open from that result page, I get the problem. When I go back to full templates listing, go thru the pages to the template that did not work before, I could open it properly. Trying to open the same template after a search like before seems to work now.
When restarting OC, I get the loading problems again, but it may be on different templates.

Here the data:

**Name:** `MenuHandling`
**Beschreibung:** `ShortCut Shape for Handling replacement of the main menu`
**Inhalt:**
```


{% assign menuid = Model.Menu.ContentItemIds.first %}
{% if menuid %}
{% else %}
    {% assign menuid = Site.Properties.ExtraPageSettings.ExtraPageSettings.StandardMainMenu.ContentItemIds.first %}
{% endif %}

{% assign menu = Content.ContentItemId[menuid] %}
{% assign alias = menu.ContentItem.Content.AliasPart.Alias %}
{% assign aliastag = "alias:" | append: alias %}

{% styleblock name:"SiteLogo" %}
a.navbar-brand img.SiteLogo {
    height:100px; width:100px;
    margin-top:-20px;
    margin-bottom:-27px;
}
a.navbar-brand .SiteName {
    display: none;
}

@media (max-width: 991px)
{
    a.navbar-brand img.SiteLogo {
    height:50px; width:50px;
    margin-top:-5px;
    margin-bottom:-5px;
}
a.navbar-brand .SiteName {
    display: inline;
}
}
{% endstyleblock%}

{% zone "SiteLogo" %}
<img class="SiteLogo" src="{{ 'PageDesign/logo web itwh.png' | asset_url | resize_url: width:100, height:100 }}" title="{{ Site.SiteName }}" alt="{{ Site.SiteName }}"/>
<span class="SiteName">{{ Site.SiteName }}</span>
{% endzone %}
{% zone "Menu" %}
{% assign menushape = "Menu2" | shape_new: Menu: menu.ContentItem.Content %}
{%comment%}{% shape_cache menu cache_id: alias, cache_tag: aliastag %}{%endcomment%}
{{ menushape | shape_render }}
{% endzone  %}
```

> 1. Or perhaps under Network (these are all successful requests, unsuccessful ones will show up in red):

Network only shows Code 200 Ok entries. But the response entry of the main page does not show content:
<img width="666" alt="image" src="https://github.com/OrchardCMS/OrchardCore/assets/36511996/5862d878-5db0-49d9-af0b-34bf815162c9">

**Comment by Piedone** [comment]
Thanks!

Can you share the OC logs, do they have anything?

That `ERR_CONTENT_DECODING_FAILED` may be the symptom of the issue, then. What's in your web project's `Program`? Did you enable any kind of compression or custom middleware?

**Comment by sebastienros** [comment]
@bashuss to follow-up on @Piedone 's question, here is the reasoning: https://stackoverflow.com/questions/14039804/error-330-neterr-content-decoding-failed

Looks like something on the server says the content is compressed, but might not be actually. And OC doesn't do compression by default, it's opt-in, and would be a Kestrel feature.

**Comment by bashuss** [comment]
**program.cs**
```
using Microsoft.AspNetCore.StaticFiles;
using OrchardCore.Logging;
using OrchardCore.Sitemaps.Models;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);

ConfigureLogging(builder.Logging, builder.Environment, builder.Configuration);

builder.Host.UseNLogHost();

var services = builder.Services;

// Add services to the container.
services.AddOrchardCms()
    //.AddSetupFeatures("OrchardCore.AutoSetup")
    ;
var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
var provider = new FileExtensionContentTypeProvider();
// Add new mappings
provider.Mappings[".vue"] = "application/javascript";

app.UseStaticFiles(new StaticFileOptions
{
	ContentTypeProvider = provider
});
app.UseOrchardCore();

// app.UseRateLimiter(); // DNTCaptcha in Anleitung verlangt... warum?

app.Run();



void ConfigureLogging(ILoggingBuilder logging, IHostEnvironment env, IConfiguration configuration)
{
    logging.ClearProviders();

    logging.AddDebug();

    if (env.IsDevelopment())
    {
        logging.AddConsole();
    }

    logging.AddConfiguration(configuration.GetSection("Logging"));
}
```

**Log** : No entries at all for my time working with OC 2.0.0-preview, but entries for my try with 1.8.3 directly before that (no support for `{% navber = Navbar() ...`).

**Comment by bashuss** [comment]
>Looks like something on the server says the content is compressed, but might not be actually. And OC doesn't do compression by default, it's opt-in, and would be a Kestrel feature.
Shouldn't this be more consistent then? Some work, others not, reloading sometimes fixes the problem, sometimes not. And some workflow or accidental thing seems "fix" the whole thing, so it does not show up with the following tries.
**Response Header in case of failed page loading and in case of success:**
```
Cache-Control:
no-cache, no-store

Content-Encoding:
br
Content-Language:
de-DE
Content-Type:
text/html; charset=utf-8
Date:
Fri, 31 May 2024 07:18:20 GMT
Pragma:
no-cache
Server:
Kestrel
Set-Cookie:
admin_Default=-185905124; path=/
Set-Cookie:
.AspNetCore.Mvc.CookieTempDataProvider=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/t4h; samesite=lax; httponly
Vary:
Accept-Encoding
X-Powered-By:
OrchardCore
```

**Comment by Piedone** [comment]
The issue is most possibly the Brotli compression you have enabled with response compression somewhere, which is apparently not the `Program` class, what is also referenced in the log. That also hints at what may be behind the issue: the Browser Link feature of Visual Studio.

So, my guess is that you have response compression enabled, which by default uses Brotli. This in turn causes Browser Link to break, which causes the random issues with the Templates module you see. If indeed, then this is not an issue with OC, and I suggest disabling Browser Link, or disabling response compression for the Development environment (that you can check for where response compression is enabled in the code, similar to what you have in `Program`: `env.IsDevelopment()`).

The location of the log files, if you use NLog (what seems to be the case) is set by the NLog.config file. The default, as used by the development app here and generated for your apps with the codegen template is App_Data/logs, as demonstrated [here](https://github.com/OrchardCMS/OrchardCore/blob/main/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Web/NLog.config#L16). That you have some files in App_Data/App_Data/logs is strange: didn't you change the NLog.config file by chance? I don't see any issues with the latest `main`, and the dates of the log files on your screenshot indicates that something was different (correct) on the 28th.

**Comment by sebastienros** [comment]
There is a feature named ResponseCompression in OC, it wouldn't show up in the code if you enabled it in the admin or via a recipe, check your active features for it.

**Comment by sebastienros** [comment]
Or disable BrowserLink to see if all the issues disapear https://www.mankier.com/1/dotnet-watch#Description-Response_compression

**Comment by bashuss** [comment]
> I don't see any issues with the latest `main`, and the dates of the log files on your screenshot indicates that something was different (correct) on the 28th.

Yes, 28th was testing Version 1.8.3. Then I simply did a nuget upgrade to 2.0.0-preview. 
The wrongly located logfiles before 28th were also with version 2.0.0, but I had to reset the solution (not the AppData), as something went wrong with my first try to upgrade.

**Comment by bashuss** [comment]
>There is a feature named ResponseCompression in OC, it wouldn't show up in the code if you enabled it in the admin or via a recipe, check your active features for it.

Yes, this feature is active. When I disable it, the problem does not occur.
Can this be fixed from within the feature? E.g. no compression, when dev?

**Comment by bashuss** [comment]
Seems like the logging path was fixed after the nuget package was created, as the fix in the history shows the source of the error. So it was a bug, is already fixed, but not yet available.
https://github.com/OrchardCMS/OrchardCore/commit/6aac96debc0d2fca77280a2ddd8dcd49782588cb

**Comment by Piedone** [comment]
Ah, we have a feature for Response Compression? Nice, didn't know that.

This is an incompatibility between ASP.NET Core's Response Compression, and Visual Studio's Browser Link. I don't think we can do anything. You my bring it up with either project, but most appropriate would be a VS bug report.

If you need Browser Link, just don't enable Response Compression locally. Locally it's recommended to work with a different configuration anyway, since that and what's needed for production will always be different (and you should definitely use a separate DB for local development).

**Comment by gaojianzhuang** [comment]
Can anyone help figure out how to resolve this issue? Thanks so much.

**Comment by Piedone** [comment]
You have the solutions above.
