### ISSUE TITLE
ControllerTypeExtensions ControllerName should look for ControllerBase

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#16186]
ControllerTypeExtensions ControllerName should look for ControllerBase type instead of Controller.

https://github.com/OrchardCMS/OrchardCore/blob/a95a876e3f0cf8ac459926dea48ce7201f40ca10/src/OrchardCore/OrchardCore.Mvc.Core/Utilities/ControllerTypeExtensions.cs#L10-L13

ApiController should also inherit from ControllerBase instead of Controller.

**Comment by sebastienros** [comment]
https://stackoverflow.com/questions/55239380/why-derive-from-controllerbase-vs-controller-for-asp-net-core-web-api

**Comment by Skrypt** [comment]
Yes ControllerBase here should support both.

**Comment by Skrypt** [comment]
@sebastienros Unless what you meant is that I should revert the change so that we can keep the ControllerBase as clean as possible?
