### ISSUE TITLE
Should [shortcode] be resolved to an actual value when converting HtmlBodyPart or MarkdownBodyPart is graphql?

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16196]
When we have shortcodes like [site_name], [image]file1.jpg[/image] or any other shortcode in HtmlBodyPart or MarkdownBodyPart, shouldn't we process the shortcodes and return the raw value?

When we return content using REST API, returning the '[shortcode]` is not as useful as returning the resolved values.

Thoughts?

**Comment by Piedone** [comment]
I don't think we should return this processed content where we return the source currently, but we can have new fields to produce it. Kind of like `rendered`.

**Comment by MikeAlhayek** [comment]
I agree with you. `render` property for these two parts is a good choice to allow us to be able to render both versions of the part.

**Comment by MikeAlhayek** [comment]
After looking more at the code, it turn out that we already process the HTML and markdown part/field from shortcodes. This is a false alarm.

https://github.com/OrchardCMS/OrchardCore/blob/39c970e0eb47eff96d0b091bd95390a11eeba44a/src/OrchardCore.Modules/OrchardCore.Html/GraphQL/HtmlBodyQueryObjectType.cs#L59

https://github.com/OrchardCMS/OrchardCore/blob/39c970e0eb47eff96d0b091bd95390a11eeba44a/src/OrchardCore.Modules/OrchardCore.Markdown/GraphQL/MarkdownFieldQueryObjectType.cs#L88

https://github.com/OrchardCMS/OrchardCore/blob/39c970e0eb47eff96d0b091bd95390a11eeba44a/src/OrchardCore.Modules/OrchardCore.Markdown/GraphQL/MarkdownFieldQueryObjectType.cs#L88
