### ISSUE TITLE
Issue with Non-Gregorian Dates in Sitemap Causing Errors in Google Search Console

### ISSUE THREAD

**Issue by hamid-reza67** [OrchardCMS/OrchardCore#16197]
Hi everyone. There is a problem with the sitemap. When a non-Gregorian calendar is used (such as the Jalali or Hijri calendar), the **lastmod** date in the sitemap is also set to the non-Gregorian calendar, which causes an error in Google Search Console. Apparently, Google considers non-Gregorian dates to be invalid for sitemaps.
![2024-05-30_11-17-19](https://github.com/OrchardCMS/OrchardCore/assets/30426533/38c13397-3708-43e8-b382-00a0dd3a57da)

![2024-05-30_11-15-15](https://github.com/OrchardCMS/OrchardCore/assets/30426533/a6a46ea4-9bb4-480a-8ca2-cb76e5f30eab)

**Comment by Piedone** [comment]
Please provide reproduction steps.

**Comment by hamid-reza67** [comment]
1. Change the culture to one that uses a non-Gregorian calendar (I changed it to fa-IR (Persian)).
2. Republish one of the articles that is present in the sitemap.
3. Now, check the details of that article in the sitemap.
You will see that the **lastmod** field has a Jalali (non-Gregorian) date.

**Comment by Piedone** [comment]
Thanks! So, it seems when generating the `lastmod` we need to force a specific format regardless of the culture, [W3C Datetime](http://www.w3.org/TR/NOTE-datetime) format, see [the docs](https://www.sitemaps.org/protocol.html).

Is this something you'd venture into contributing?

**Comment by gvkries** [comment]
This does not occur on the main branch anymore. There have been several related fixes, e.g. recently https://github.com/OrchardCMS/OrchardCore/pull/15229.

**Comment by Piedone** [comment]
Oh, great!
