### ISSUE TITLE
Documentation: "Customize Admin Branding" code sample is unclear

### ISSUE THREAD

**Issue by ccnicholls99** [OrchardCMS/OrchardCore#16198]
DocLink: https://docs.orchardcore.net/en/latest/reference/modules/Admin/
Section: Customize Admin branding, code sample.

Code Sample includes the use of @Site.SiteName but does not give reference on how to access the symbol "@Site". I was able to work it out by digging through past issues and code but, there goes another 30 minutes of my life ;-) 

### Expected behavior
One way I found (perhaps there is a better way?) was just add these lines to the view...
`@inject OrchardCore.Settings.ISiteService SiteService

@{
    var Site = await SiteService.GetSiteSettingsAsync();
}
`
These lines added to the Code sample might save future explorers some time.

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/26383029/ac575a3d-63ea-4ba4-ac45-53182f7a01d4)

**Comment by Piedone** [comment]
You shouldn't really need to do that. The [default shape template](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Admin/Views/AdminBranding.cshtml) does the same as the code sample in the docs. `Site` is a property [on the view](https://github.com/OrchardCMS/OrchardCore/blob/39c970e0eb47eff96d0b091bd95390a11eeba44a/src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorPage.cs#L327) and thus available by default.

Probably you need this line in your theme's `_ViewImports.cshtml` (see [the built-in one](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Admin/Views/_ViewImports.cshtml))?

```
@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>
```

**Comment by ccnicholls99** [comment]
OK. Nice thanks for the heads-up, I was there was something I was missing.
 
Although if I put that in _ViewImports.cshtml then every other Razor Page in my project backed by a model will throw an error. If I put it in just the _Layout.cshtml instead, then it appears to work without issue. 

Either way, it would be helpful to have the above advice in the documentation page I highlighted.

**Comment by Piedone** [comment]
Sorry, I'm confused about what exactly you're doing. Can you share the code? 

Because I don't understand how you're using Razor Pages. Or by "Razor Page" do you mean a Razor view template? Do you have a custom Admin theme as explained [here](https://docs.orchardcore.net/en/latest/guides/create-admin-theme/)? You shouldn't need a _Layout file there, and that's definitely not the recommended approach.

**Comment by ccnicholls99** [comment]
All I am trying to point out is that the code sample presented in the documentation page is missing the details on how to get a reference to the Symbol @Site.Sitename.  I think you could clarifiy this by adding one or two lines of extra code to the sample...(razor example) to make it obvious where the @Site symbol is coming from...

```
@* ...In a custom Admin theme: Site variable is automatically available using... *@
@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>
```

```
@* ...from a random layout or view...inject the SiteService...*@
@inject OrchardCore.Settings.ISiteService SiteService
@{  var Site = await SiteService.GetSiteSettingsAsync(); }
```

[rest of Code Sample]

**Comment by Piedone** [comment]
OK, thanks for explaining. Though neither should really be needed:

- If you're in an (admin) theme, then this `inherits` is already implied (at least if you generated the theme with the OC codegen templates or followed the docs). So the `Site` property should be available.
- In other cases, while indeed you need to resolve `ISiteService` to access the site settings, that's not about customizing the admin branding anymore. For that, you need an admin theme.

So I'm just confused about what exactly are you doing and thus unclear about which part of the documentation needs to be updated.
