### ISSUE TITLE
`JsonDynamicValue' does not contain a definition for 'ToObject'

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16221]
Now sure how to reproduce this issue. Adding it here for now.

scanning my logs after deploying 2.0 I see the following errors

```
OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay|ERROR|Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by RuntimeBinderException Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Text.Json.Dynamic.JsonDynamicValue' does not contain a definition for 'ToObject'
```

**Comment by Piedone** [comment]
Are you sure all the DLLs of OC got updated during deployment?

**Comment by MikeAlhayek** [comment]
I deploy using docker containers. So all dlls are pulled directly from nuget.

**Comment by gvkries** [comment]
I think this must be in one of your *.cshtml templates, which may use a dynamic value. I don't find any `ToObject` from a JsonDynamicValue in Orchards cshtml files.

This basically comes down to the same discussion we had in https://github.com/OrchardCMS/OrchardCore/issues/15816#issuecomment-2113009597: Should we add functionality back that Newtonsoft had, even if it is not used by our own code?

**Comment by MikeAlhayek** [comment]
@gvkries I have to try to find where it's being used. I don't think this is something I have in my code. But, I'll try to see if I can find where it being called

**Comment by gvkries** [comment]
@MikeAlhayek I used a file search for `ToObject` once more and didn't found this case.  But in the documentation, I found this: https://github.com/OrchardCMS/OrchardCore/blob/7196b5b1c6c0180b17bb4dabe944232001b0a681/src/docs/reference/modules/Media/README.md?plain=1#L456 I guess using that will fail as well.

**Comment by Piedone** [comment]
Yeah, I don't think we should add back shims for easier migration from Json.NET unless we'd use them otherwise as well.

**Comment by MikeAlhayek** [comment]
I don’t think this issue in OC. Closing it
