### ISSUE TITLE
Add ExposedHeaders in CORS module

### ISSUE THREAD

**Issue by vsezima** [OrchardCMS/OrchardCore#16232]
### Is your feature request related to a problem? Please describe.
Currently in CORS module isn't option to set [Exposed headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers).

### Describe the solution you'd like
Add field in [Index.cshtml view](https://github.com/OrchardCMS/OrchardCore/blob/d39c9030af3436a61011ac8117475f082ad35818/src/OrchardCore.Modules/OrchardCore.Cors/Views/Admin/Index.cshtml) to set which headers should be exposed (similar to other fields for adding origins, headers etc.) and then in [CorsOptionsConfiguration](https://github.com/OrchardCMS/OrchardCore/blob/d39c9030af3436a61011ac8117475f082ad35818/src/OrchardCore.Modules/OrchardCore.Cors/Services/CorsOptionsConfiguration.cs) use configurePolicy.WithExposedHeaders() (this method already exists but isn't used).

**Comment by hyzx86** [comment]
Reference #15499

**Comment by MikeAlhayek** [comment]
@vsezima do you like to submit a PR for this?

**Comment by vsezima** [comment]
> @vsezima do you like to submit a PR for this?

I have it ready locally in separate branch, but can't push it to make PR.
It fails because of 403 Permission denied
![image](https://github.com/OrchardCMS/OrchardCore/assets/15254338/8ec5c997-fc36-422c-857a-485ce1ed921d)

**Comment by MikeAlhayek** [comment]
@vsezima fork OrchardCore project. create a new branch from your fork and then submit a across project pull-request
