### ISSUE TITLE
razor view does  allow dynamic casting of property values using system.text.json

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#16233]
Using the new system.text.json seems to not cast to dynamic in razor views , so you cannot access dynamically property values like previously .

See in below image when looping in a razor view over some content items i cannot extract dynamically the ContentItemId Property value like before.  is there a way to cast to dynamic like before ?

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/b91d1787-c56a-4144-a4c7-bca09dfa113d)

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/41d7ca19-b5d7-43f7-b75a-d6f89e9f15cc)

**Comment by Piedone** [comment]
Did you try `foreach (dynamic faq...`?

**Comment by giannik** [comment]
@Piedone yes i did , same result . 

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/71447aab-ca7e-44e6-94cb-c4c600ac7b6e)

**Comment by giannik** [comment]
the object is there but cannot access dynamicall properties using dot notation : @faq.ContentItemId

**Comment by Piedone** [comment]
How should this be approached with STJ, @MikeAlhayek @sebastienros?

**Comment by gvkries** [comment]
I would expect `ContentItems` to return `JsonDynamicObject` instead of `JsonObject`. What's the definition of `ForTutors`?

**Comment by giannik** [comment]
@gvkries  ForTutors is BagPart named 'Tutors' with a collection of content items.

**Comment by gvkries** [comment]
Okay, I think this happens because `JsonDynamicArray` only implements `IEnumerable<JsonNode>`, which breaks dynamic behavior when using `foreach`:

https://github.com/OrchardCMS/OrchardCore/blob/77fa6e08434c9509bb7e724d86ba60903e2406eb/src/OrchardCore/OrchardCore.Abstractions/Json/Dynamic/JsonDynamicArray.cs#L14

**Comment by giannik** [comment]
@gvkries  thanks for the fix.
It partially works .It can read now a property but in the following case (where SusbscriptionElements is BagPart) when it tries to read again through the .Content property it sends an error 
for example 

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/ee189b9a-e0e2-455a-88c0-527f5f274f7b)


![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/d34bf8f9-b833-4a72-a830-abd5a1de8874)

**Comment by gvkries** [comment]
Hmm, I'll have a look...

**Comment by gvkries** [comment]
It's not a `ContentItem` anymore at that point, you have to remove the `Content` part and access `SubscriptionElement` directly.

**Comment by giannik** [comment]
@gvkries  I tried removing the .Content part with no luck : 
![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/b002ffb2-cb3f-4107-aa84-accb3f74e7e9)

**Comment by gvkries** [comment]
You can cast that `JsonDynamicValue` to `string`.

Was all of this working before with NewtonSoft.Json?

**Comment by giannik** [comment]
@gvkries  yes it was working with newtonsoft..

the issue is that event without .Content it cannot resolve using dot notation.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1516981/fd81f1be-3a40-43dc-8e2c-56aac2007635)

**Comment by gvkries** [comment]
In comparison to Newtonsoft JSON, the primary limitation when using dynamics is the lack of direct value comparison. For instance, a straightforward comparison like `if (subscriptionElement.SubscriptionElement.TargetUserProfile.Text == "Trainer")` no longer works out of the box. Instead, it necessitates casting to the target type, such as `if ((string)subscriptionElement.SubscriptionElement.TargetUserProfile.Text == "Trainer")`.

Regarding the usage of `.Content`, it seems improbable that this would have worked with Newtonsoft JSON either. `ContentItems` is essentially a dynamic JSON object and not a `ContentElement`, which holds true when using Newtonsoft as well.

**Comment by giannik** [comment]
yes , you are right about the string comparison : 
You need to do : 
```
  if (subscriptionElement.SubscriptionElement.TargetUserProfile.Text.ToString() == "Trainer")  //this works 

  if (subscriptionElement.SubscriptionElement.TargetUserProfile.Text == "Trainer") //this does'nt work 

```

But what i am finding is that the previous api that did a 1-1 mapping of the json with api now does'nt exist : 

for instance  in previous api you could be stronly typed access to fields as so : 
```
var mapsToSubscriptionPlanField = subscriptionElement.Get<ContentPart>("SubscriptionElement")?.Get<ContentPickerField>
/("MapstoSubscriptionPlan");
 if (mapsToSubscriptionPlanField?.ContentItemIds.Length == 1)
              {
                  subscriptionPriceContentItemId = mapsToSubscriptionPlanField?.ContentItemIds[0];   
              }
```
Now you cannot have this  api access , right ? you would have to use  stj helpers like json.selectNode(.....) . . correct ?

Please tell me i am wrong ...

**Comment by giannik** [comment]
@gvkries would it make sence to add an extension method like jsonobject.ToContentItem() to convert to contentitem and then use  the same api again ?

**Comment by gvkries** [comment]
Yes, I think that is missing and we should add support for it back. Not sure if an extension method is enough though, we may need to support this on the dynamic wrappers too.

**Comment by giannik** [comment]
@gvkries thanks. the extension method also solves it too.
