### ISSUE TITLE
Sql query not working when using it in liqued page as query filter

### ISSUE THREAD

**Issue by hamdiRuwiss** [OrchardCMS/OrchardCore#1623]
This is the sql query workin fine when when running it or using query api 
```
select DocumentId
from ContentItemIndex 
where Published = true and ContentType = 'Article'
order by CreatedUtc DESC

```
This is the liquid page body :
```
{% assign RecentArticles = 'Articles' | query: type: 'Article'%}
{% for item in RecentArticles %}
{{ item | display_text }}
{% endfor %}
```

I Tested it also in an html widget and added it in the always Layer but nothing is showing

**Comment by paynecrl97** [comment]
If you're using the latest dev, you'll need to switch to the new liquid syntax for queries: https://github.com/OrchardCMS/OrchardCore/pull/1581

**Comment by hamdiRuwiss** [comment]
So my query should be like this :
```
{% for item in Queries.RecentArticles | query take: 3 %}
{{ item | display_text }}
{% endfor %}
```

**Comment by paynecrl97** [comment]
If `take` is meant to be a parameter for the query then it'll need to be `Queries.RecentArticles | query: take: 3`. (i.e. colon after `query`)

**Comment by hamdiRuwiss** [comment]
```
{% for item in Queries.RecentArticles | query %}
{{ item | display_text }}
{% endfor %}
```
same error
```
{% for item in Queries.RecentArticles | query: take: 3 %}
{{ item | display_text }}
{% endfor %}
```
same error

**Comment by paynecrl97** [comment]
I'm not 100% sure if you can apply a filter inside the opening statement of a for loop. Try assigning the query before using it in the for loop.

```
{% assign RecentArticles = Queries.RecentArticles | query: take: 3 %}
{% for item in RecentArticles %}
{{ item | display_text }}
{% endfor %}
```

**Comment by paynecrl97** [comment]
Docs: https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Queries

**Comment by hamdiRuwiss** [comment]
That is right :
{% assign RecentArticles = Queries.RecentArticles | query: take: 3 %}
{% for item in RecentArticles %}
{{ item | display_text }}
{% endfor %}
