### ISSUE TITLE
LinkGenerator does not take in consederation the site prefix

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16259]
### Describe the bug
This is something that require investigation. When when using LinkGenerator to create a link for a tenant that use "prefix" for the host. It generates a path without the /tenant-prefix.

 like this for example:

If you have a tenant setup with no host but with `blog1` prefix. then creating a link like this

var url = _linkGenerator.GetPathByAction("Index", "Admin", new { area = "OrchardCore.Settings", groupId = "admin" });

creates 

```
/Admin/Settings/admin
```

instead of 

```
blog1/Admin/Settings/admin
```

### Expected behavior
I expect the generated URL to be as follow

```
blog1/Admin/Settings/admin
```

**Comment by Piedone** [comment]
Latest `main`?

**Comment by MikeAlhayek** [comment]
Yes

**Comment by MikeAlhayek** [comment]
I think this is a limitation of the extension method used. If you look at the implementation, it does not use the HttpContext when generating the URL 

https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Routing/ControllerLinkGeneratorExtensions.cs#L187-L204

The problem with that for us is that the URL-prefix will never be considered here since this is something we add to the HttpContext.

The workaround is to use the extension method that accepts the HttpContext as the first argument. 

https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Routing/ControllerLinkGeneratorExtensions.cs#L134-L160

So instead of doing this 

```
var url = _linkGenerator.GetPathByAction("Index", "Admin", new { area = "OrchardCore.Settings", groupId = "admin" });
```

do this

```
var url = _linkGenerator.GetPathByAction(_httpContextAccessor.HttpContext, "Index", "Admin", new { area = "OrchardCore.Settings", groupId = "admin" });
```

**Comment by sebastienros** [comment]
So there is no issue, right? We just need to call the extension method with the HttpContext when using LinkGenerator. Please re-open if I missunderstood.
