### ISSUE TITLE
Field override by field type and content type

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1626]
From the docs http://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Templates/README/#content-field-templates it looks like it's not supported but I think it's a common scenario.

For example when you have a type and you want to override all textfields on it regardless their names, how would you do that?

Is this supported or will be supported?

**Comment by alberthajdu** [comment]
@pgy866 this issue is about a completely different thing. 
Check out the link in the description and you'll see that this is about overriding field shapes. Basically I would like to modify the html markup of fields. And I would like to target by field type and content type which looks like isn't supported yet.

**Comment by Skrypt** [comment]
From which side would you like to achieve this ? Is it from the admin UI or in your own client side theme ?

**Comment by alberthajdu** [comment]
@Skrypt before you make those tests just to clarify: based on the docs it looks like that this scenario is **not** supported because it's not documented (and all the other scenarios are well documented). I tried all possible namings to achieve my goal but with no luck so I opened this issue.

I would like to override a field (both edit and display) by targeting the **field type** and **content type**. For example: "override all textfields on the Page content type (but don't override it on the other types)".

It looks like Sébastien was able to understand my comments and confirmed that this is an existing issue but if someone need more clarification I could try explain it better.

**Comment by Skrypt** [comment]
Yeah it's fine, my tests we're not inconclusive. I thought the Textfield example would work but no.

**Comment by sebastienros** [comment]
This is defined in `ContentFieldDisplayDriver<TField>` if you want to create a PR

**Comment by alberthajdu** [comment]
@sebastienros I added the display alternate but got confused with the field editors. It looks like both part editor alternates and field editor alternates are a missing feature. Am I right?

**Comment by alberthajdu** [comment]
@sebastienros I think you missed my previous comment.

**Comment by sebastienros** [comment]
I don't think there is any alternate for editors. In O1 it would not make sense as you can't use a different admin theme, but in OC I understand it could make sense, if you want to change the editor of specific fields or parts ...

There is already some sort of extensibility in fields that let you chose the editor for each field (take a look at TextField for instance) which is defined by the field itself using shape morphing and shape discovery. This is driven by the users, in the field settings. Using alternate would allow to force specific shape templates instead at the application level. I assume both make sense. So if you want to add a small set of editor alternates I am ok with it. Realize though that the new templates will have to be in the admin theme file system. You might want to use base themes to handle this.

Something I want to add also, is a way for custom field editors to have settings, there is an issue open for that.

**Comment by alberthajdu** [comment]
@sebastienros I can't see the reason why can't fields have a same editor alternates system as display alternates have?

Most of the time when I used O1 the content editing happened **outside of the admin dashboard** because you just can't let in regular users in that dashboard. (I never used fields in these cases because of a lot of bugs, but wanted to)

What if I would like to display an editor built with fields outside of the admin dashboard? I can't see why can't I just throw in some liquid editor alternate templates with the desired HTML? Usable fields would make life so much easier.
