### ISSUE TITLE
Notification editor doesn't close when saving a draft

### ISSUE THREAD

**Issue by maksim-markin** [OrchardCMS/OrchardCore#16267]
### Describe the bug
There is an issue with updating content item: when there is a change content item with current culture changing the notification editor doesn't close.

### Orchard Core version

1.8.2.

### To Reproduce
1. Go to Manage Content page
2. Click Add New Global Notification
3. Set some Html text and Content localization to English
4. Еhere is a parameter "returnUrl" in the address bar
5. Press Publish button
6. On Manage Content page select published notification for editing
7. Change Current culture to other language (in this step we are losing a parameter "returnUrl") and change Html text
8. Press Publish button again

### Expected behavior
The editor window should close and return to Manage Content page.

### Logs and screenshots
![Issue_close_window_1](https://github.com/OrchardCMS/OrchardCore/assets/172181395/5f012c11-b05f-4429-8383-9b8376ebbfa4)
![Issue_close_window_2](https://github.com/OrchardCMS/OrchardCore/assets/172181395/5cc7e766-cb90-4bee-bfd5-49f01ecc570a)
![Issue_close_window_3](https://github.com/OrchardCMS/OrchardCore/assets/172181395/e1442ebe-024a-49fc-9255-4267fb695f68)
![Issue_close_window_4](https://github.com/OrchardCMS/OrchardCore/assets/172181395/5d854628-f86a-408e-ae1e-24ac7ac5649f)
![Issue_close_window_5](https://github.com/OrchardCMS/OrchardCore/assets/172181395/6d1d0b41-009a-4969-990b-a64865103f2b)

**Comment by hishamco** [comment]
@MikeAlhayek is this by design?

**Comment by MikeAlhayek** [comment]
I am not sure. I did not design the culture feature

**Comment by hishamco** [comment]
I thought it was notification-related. I will have a look then

**Comment by maksim-markin** [comment]
This behavior actual with every content type not for only notification

**Comment by hishamco** [comment]
Please another screenshot

**Comment by maksim-markin** [comment]
1. Open Manage Content (type = page)
![pic1](https://github.com/OrchardCMS/OrchardCore/assets/172181395/ffbdcf35-8e83-45f6-ae3b-eb1a044cb605)

2. Edit some page (there is a returnUrl param) and change current localization
![pic2](https://github.com/OrchardCMS/OrchardCore/assets/172181395/97d9d62d-c68d-41dd-a9c7-8518cf85eb14)

3. Localized version has been created (there is no returnUrl param)
![pic3](https://github.com/OrchardCMS/OrchardCore/assets/172181395/15557e40-947d-4563-9045-75816f1b97da)

4. After published, page doesn`t close
![pic4](https://github.com/OrchardCMS/OrchardCore/assets/172181395/1006b60f-512f-4156-9c3b-a0b1cea11c6c)

**Comment by sebastienros** [comment]
@maksim-markin We understand that you created a type name "Global Notification" and this is not related to the notifications module (that was confusing so I prefer the state it).

My understanding of the issue is that the return url is lost when we switch languages, so publishing a new localized version won't go back to the content items page like when create a new content item does.

**Comment by sebastienros** [comment]
I kind of agree with the expectation, that we should return to the previous returnUrl value if there was one.

**Comment by maksim-markin** [comment]
> @maksim-markin We understand that you created a type name "Global Notification" and this is not related to the notifications module (that was confusing so I prefer the state it).
> 
> My understanding of the issue is that the return url is lost when we switch languages, so publishing a new localized version won't go back to the content items page like when create a new content item does.

This behavior actual with every content type not for only notification
See screens above

**Comment by maksim-markin** [comment]
Related Pull Request: https://github.com/OrchardCMS/OrchardCore/pull/16325

**Comment by hishamco** [comment]
I unassigned myself while you started a PR
