### ISSUE TITLE
OrchardCoreCmsWeb Only runs one time, second run giving page not found error

### ISSUE THREAD

**Issue by Fusion-Priyakant** [OrchardCMS/OrchardCore#16289]
Navigate to ./OrchardCore/src/OrchardCore.Cms.Web.
Run dotnet run.
Open the http://localhost:5000 URL in your browser.
Stop the App

Again Run the application a second time and browse the URL "http://localhost:5000", it will show a page not found error.

**Comment by Piedone** [comment]
I can reproduce this with a fresh clone of the latest `main` (3d3f172dd99aa552caf7e7a21ce6ceea6a4c003f) under Windows (you need to actually run `dotnet run --framework net8.0`).

**Comment by Fusion-Priyakant** [comment]
I have already tried running with --framework, however it still fails
second time.

Also if you download the latest version from GitHub release it's working
perfectly fine.

The issue is occurring on latest GitHub main branch.

Can you please confirm you can run twice and able to browse the
application? Also please try with --no-build as well.

I have noticed one thing if delete app_data folder then it will work, again
Stop the application, delete app_data and run again, it will work. But on
every run i have to delete app_data folder.

**Comment by Fusion-Priyakant** [comment]
Thanks for the confirmation.

So what's now?
Any timelines?

**Comment by Piedone** [comment]
See https://docs.orchardcore.net/en/latest/guides/contributing/managing-issues/#what-happens-after-you-open-an-issue.

**Comment by gvkries** [comment]
Looks like this is caused by #15793. I'll have a look.

**Comment by Piedone** [comment]
Thank you!

**Comment by gvkries** [comment]
> Thank you!

I broke it, so I'm trying to fix it 🙈😇 Hopefully this is the last mistake of this kind...
