### ISSUE TITLE
Getting value from JsonDynamicValue  in Jint

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#16290]
Problem when using ` contentItem.Content.TestPart.TextFeildProp.Text` to assign values to other objects

 

I use the following code in the `ScriptTask` of the workflow to call other queries, and I use the data of a content item to build parameters for a query

```js
 const result =  executeQuery('myQuery', {
         prop1 : contentItem.Content.TestPart.TextFeildProp.Text
    });
```

With NSJ it is possible to get the actual value directly, but in the latest version of OC 2.0 additional operations must be added to get the actual value

```c#
    public class JsonTests
    {
        [Fact]
        public void ExpandoObjectSerializeTest()
        {
            dynamic expandoValue = new ExpandoObject();

            var contentItem = new ContentItem();
            contentItem.Alter<TestPart>(part =>
            {
                part.TextFeildProp = new TextField { Text = "test" };
            });

            expandoValue.stringValue = contentItem.Content.TestPart.TextFeildProp.Text;

            var jsonStr = JConvert.SerializeObject((ExpandoObject)expandoValue);
            // Actual:"{\"stringValue\":{\"JsonValue\":\"test\"}}"
            Assert.Equal("{\"stringValue\":\"strValue\"}", jsonStr);
        }

    }
    public class TestPart : ContentPart
    {
        public TextField TextFeildProp { get; set; }
    }
```

![image](https://github.com/OrchardCMS/OrchardCore/assets/15613121/f2f00489-ffb3-4d50-8ca6-5759b5dc4715)

This was discussed in PR #15816, but supposedly the above scenario was not considered

_Originally posted by @sebastienros in https://github.com/OrchardCMS/OrchardCore/issues/15816#issuecomment-2113009597_

**Comment by hyzx86** [comment]
contentItem.Content.TestPart.TextFeildProp.Text.GetType().FullName
_> "System.Text.Json.Dynamic.JsonDynamicValue"

**Comment by hyzx86** [comment]
Hi @gvkries , is there a recommended solution for this problem? Thanks!

**Comment by gvkries** [comment]
You can cast `Text` to string I think. Also maybe try #16292 I just created, maybe it helps here as well.

**Comment by hyzx86** [comment]
> You can cast `Text` to string I think. Also maybe try #16292 I just created, maybe it helps here as well. 

Dude, you're so cool.  🫡

**Comment by gvkries** [comment]
> Dude, you're so cool. 🫡

🤭

**Comment by hyzx86** [comment]
Hi @MikeAlhayek  , pls  reopen it , this issue is pending for #16298
