### ISSUE TITLE
Rebuilding elastic index takes a lot of time

### ISSUE THREAD

**Issue by konika-jindal** [OrchardCMS/OrchardCore#16308]
I am having almost 25000 data for an elasticsearch index to rebuild , it takes almost 12-14 hours to rebuild , if I want to add just a small change and rebuild or reset then it takes almost 12-14 hours to rebuild . I want to reduce its time . How can I do that?

**Comment by sebastienros** [comment]
@konika-jindal do you have suggestions to improve it? Have you tried debugging the background indexing task and see what part was taking too much time? For instance could you try to change the batch size to see if it has any effect.

Maybe there is a way to batch the documents that are sent to ES, it could be a way to improve perf. Or maybe other best practices on how to optimize big numbers of documents to ES. Could try to you investigate?

**Comment by konika-jindal** [comment]
Yes sure , I will try out these ways and let you know for same .

**Comment by hyzx86** [comment]
This PR may be related to this issue, but I don't have time to deal with them at the moment.

https://github.com/OrchardCMS/OrchardCore/pull/14063

**Comment by konika-jindal** [comment]
I am not getting anything in background task as required , is there another way to go?

**Comment by Skrypt** [comment]
We need to have unit tests for ElasticSearch. Populate database with X amount of Content Items and track performance.
