### ISSUE TITLE
More user functionalities

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1630]
As a user besides changing my password I would like to:

1. Change my e-mail address.
2. Delete my account.
3. Create a new password if I forgot my password.

**Comment by alberthajdu** [comment]
Some work has been made (https://github.com/OrchardCMS/OrchardCore/pull/1662) on the forgot password feature but the reset token sending is a bit over complicated.
Now there's a ResetPassword and a ForgotPassword action, the ForgotPassword works well but the ResetPassword looks like a leftover code.

These basic functionalities should be well tested and optimal.

**Comment by sebastienros** [comment]
All these features seem fine. They would also require a setting to be enabled or not.

"Change my e-mail address." will go in the same feature as the password reset as it required the Email feature. Baked by an option to enable/disable this.
"Delete my account" will go in the User feature.  Option to enable/disable this feature. Option to soft delete the account.

**Comment by alberthajdu** [comment]
1. I just don't understand what's the difference between resetting a password and forgotting a password.

2. And as you mentioned in the PR ("I doubt this is the simplest way to get the html ... I will look into it.") the SendResetTokenAsync should be much simpler. A shapefactory + a displaymanager wouldn't be a better solution to get the html?

**Comment by sfmskywalker** [comment]
1. **Resetting a password** is something that a user does when she is logged-in. Depending on the user's role, she can reset her own password, or in the case of an admin user, she can reset passwords for others.  **Forgot password** is the scenario where a user forgot her password and clicks the "Forgot password" link, which will send an email with a "reset password" link. clicking that link will give the user the opportunity to specify a new password.

**Comment by alberthajdu** [comment]
@sfmskywalker thanks for the clarification, so it's not a leftover code just doesn't work. It throws and ArgumentNullException because there's no ResetToken. And the mentioned admin reset is also a missing piece.
