### ISSUE TITLE
ShellScope RegisterBeforeDispose should support sequential inserts

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#16306]
### Describe the bug

`ShellScope.RegisterBeforeDispose` currently does this 
```
internal void BeforeDispose(Func<ShellScope, Task> callback) => _beforeDispose.Insert(0, callback);
```

inserting the added callback at position zero in the list.

if using multiple `RegisterBeforeDispose` in a shell scope, it would be useful if you could actually insert a callback at the end of the list, rather than always at the beginning.

We have a number of tasks which need to be deferred till after the session has been disposed (mostly signalr events, which then trigger callbacks to read commited data), but they need to happen in the correct sequence, where inserting them at the start breaks the sequence.

An overload that supported ` _beforeDispose.Add(callback);` would be ideal.

**Comment by gvkries** [comment]
You can always insert in reverse order, but it doesn't seem necessary to insert at the start in general as the order cannot be guaranteed anyways.

**Comment by sebastienros** [comment]
Let's add a new overload `void BeforeDispose(Func<ShellScope, Task> callback, bool last)` that will populate a `_beforeDisposeLate` collection (lazily initialized) with a `_beforeDisposeLate.Add` call instead. This way we don't break the current behavior, and you can register specifically at the end of everything. Noting that you won't still be able to manage exactly when compared to other callbacks in the same bucket.
