### ISSUE TITLE
E-mail confirmation during user registration

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1632]

**Comment by alberthajdu** [comment]
In https://github.com/OrchardCMS/OrchardCore/blob/11201cfa89f2b96a36c104a762a308f056dbc671/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AccountController.cs#L117 the e-mail stuff is commented out so currently you don't have to confirm your e-mail address in order to be able to sign in.

**Comment by sebastienros** [comment]
#1299

**Comment by alberthajdu** [comment]
The reset password works now somehow thanks to the above issue but the registration confirmation is still missing.

**Comment by sebastienros** [comment]
Like in Orchard 1 then: If the option to validate email is on, then the user is not valid until the email is verified. Unless for the admin at setup which gets its email validated automatically.

**Comment by agriffard** [comment]
User registration with email confirmation implemented in #1789

**Comment by alberthajdu** [comment]
Fixed in #1789
