### ISSUE TITLE
Too many scopes created

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1634]
We are going in the `ModularTenantContainerMiddleware` and creating a service scope even for serving a static file.

**Comment by sebastienros** [comment]
After all I am not really sure that's an issue. I assume the static file middleware also requires it?

**Comment by jtkech** [comment]
So here we would need to register `IModuleStaticFileProvider` at the `builder.ApplicationServices` level, just tried it works. And enlist the related middleware at the app level, not through the tenant pipeline that will be executed in a scope context, just tried it works. The only problem is that it is no more tenant aware, make sense for shared static files but we commonly generate url including the tenant url prefix, so we would need to remove this tenant prefix.

Note: There are other custom static file providers that should be tenant aware and whose urls should contain the prefix.

Another solution is to run a middleware after the app level ones but before our tenant and router middlewares, just to update the request `PathBase` according to the tenant (currently updated in the tenant router middleware), then use the static file middleware based on our `IModuleStaticFileProvider`, and finally our tenant and router middlewares.

**Yes it is doable, let me know if it is worth doing it**

That said, creating a new scope (on an already activated shell) is fast and not expensive if you don't resolve any services, and our `ModuleEmbeddedStaticFileProvider` and `ModuleProjectStaticFileProvider` are stateless and don't resolve any services.

**Comment by Piedone** [comment]
Yes, it's necessary to create scopes even for static file requests. This is required to do anything else in the request apart from serving the file, including collecting telemetry or authorization.
