### ISSUE TITLE
Target attribute on menus breaks HTML validation

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#16340]
### Describe the bug

Since `target` attribute has been added to menu links (#15541) validation via `html-validate` fails. This is because if there is no target specified, it creates an empty attribute, like `<a class="nav-link px-lg-3 py-3 py-lg-4" href="/" target="">Home</a>`. This is not valid. If there is no target specified, the attribute should be omitted.

Note: [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target) the default is `target="_self"` so falling back to that value is also acceptable when omitting the `target` attribute would be complicated.

### Orchard Core version

Latest preview, at least TheBlogTheme package is affected.

### Expected behavior

Menu should produce valid HTML.

### Logs and screenshots

An example entry of the validation report:
```json
{
  "ruleId": "attribute-allowed-values",
  "severity": 2,
  "message": "Attribute \"target\" has invalid value \"\"",
  "offset": 2331,
  "line": 55,
  "column": 6,
  "size": 1,
  "selector": "#navbarResponsive > ul > li:nth-child(2) > a",
  "ruleUrl": "https://html-validate.org/rules/attribute-allowed-values.html",
  "context": {
    "element": "a",
    "attribute": "target",
    "value": "",
    "allowed": {
      "enum": [
        {},
        "_blank",
        "_self",
        "_parent",
        "_top"
      ]
    }
  }
}
```

**Comment by hyzx86** [comment]
@sarahelsaig Looks like we're duplicating our work~
