### ISSUE TITLE
Task-type Workflows Activities an also be set as startup task

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#16345]
### Describe the bug

You can set Task-type Activities as startup tasks on the workflow canvas. However, this doesn't make sense, since a Task can't start a workflow, only an Event can.

### Orchard Core version

22fbbb491068316a71b2feff7014dd828a73a654

### To Reproduce
1. Add any Task like Notify to a workflow.
2. Notice that you can set it as a startup task.

### Expected behavior
The startup task button only appears for events. Also, the terminology "startup _task_" is incorrect as well, since it should say "startup _event_".

### Logs and screenshots

E.g. a Notify Task can't start a workflow, but you can set it as a startup task:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/59632e3f-9e31-4c2b-812f-1c7f23202cf2)

**Comment by MikeAlhayek** [comment]
@Piedone I think this issue should remain open. I agree that the first thing that should be added to a workflow is an event. This is something Elsa workflow does well. However, the highlighted power button in your screenshot is to enable/disable task or event. We can't remove the power button unless we was to abandon the idea to enable/disable a task.

removing the power button will prevent us from enabling any task. Please see issue #16512

**Comment by Piedone** [comment]
Why do we need this issue open if there's https://github.com/OrchardCMS/OrchardCore/issues/16512.
