### ISSUE TITLE
Can't deserialize LocalizedString and LocalizedHtmlString out of the box

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#16359]
The problem is that you can serialize these two types, but you can't deserialize them because there is no empty constructor. It was easy to implement custom converters in client code with Newtonsoft, but I had problems making it work reliably in STJ, because you can't alter a JsonSerializerOptions instance after it's been already used. If possible, I'd like to push my implementation for these two converters into upstream OC.

**Comment by Piedone** [comment]
What's the use case for this?

**Comment by hishamco** [comment]
Could you please elaborate with examples? Do you serialize/deserialize the values of localizers or the localizers themselves?

**Comment by sarahelsaig** [comment]
> Do you serialize/deserialize the values of localizers or the localizers themselves?

The values. `LocalizedString`, not `IStringLocalizer`.

> What's the use case for this?

It's used in OrchardCore.Commerce, e.g. [here](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/36676621498f4286b1ece84f0dfe6127a726f1fb/src/Modules/OrchardCore.Commerce/Events/WorkflowShoppingCartEvents.cs). Also recently it was discussed that in a headless environment OC could be used as a localization server, at which case this would've been useful.

**Comment by hishamco** [comment]
Do we serialize those before?

**Comment by sarahelsaig** [comment]
Sorry, I don't understand the question.

**Comment by hishamco** [comment]
Do we serialize `LocalizedString` before we move to STJ?

**Comment by sarahelsaig** [comment]
Not in OC. But `LocalizedHtmlString` is serialized in OrchardCore.Commerce as I mentioned above, that used Newtonsoft under OC 1.8.

**Comment by hishamco** [comment]
Thanks that my memory still fresh ;) for that I prefer to have such converter in Orchard Commerce instead, unless @sebastienros has another opinion

**Comment by sebastienros** [comment]
Can you not serialize these? They have nothing to do in the db, this could even be seen as a bug since the localized value would be stored and not localized again.

**Comment by sarahelsaig** [comment]
> Can you not serialize these?

You can serialize both types, but can't deserialize them because they don't have parameterless constructors.

> They have nothing to do in the db

Is `JOptions` only for the db? I thought you are supposed to use these for any kind of JSON serialization/deserialization for consistent behavior.

> this could even be seen as a bug since the localized value would be stored and not localized again.

Sure, this could be a logic error in many common cases, but not always. For example it would be desirable behavior for Versionable content. In any case having such commonly handled types as LocalizedString and LocalizedHtmlString break serialization feels inconsiderate.

**Comment by sebastienros** [comment]
> Can you not serialize these?

I believe you misunderstood my comment: "why do you have to serialize these properties/types?"
You should not serialize localized string instances, so the problem of deserializing it would not exist.

Trying to understand if there was an actual reason for creating the problem in the first place.

**Comment by sebastienros** [comment]
In OC we never had to do it, so trying to find how you got there.

**Comment by sarahelsaig** [comment]
One of the events OCC uses hooks into the shopping cart view-model before it gets displayed. This can be used to alter the layout, e.g. add custom columns in the table. It's pretty extensible. The shopping cart view-model uses LocalizedHtmlStrings for the column headers, then identifies the matching cells in the column by referring to the value of the LocalizedHtmlString.Name (to be locale agnostic), so both Name and Value are relevant.
If the workflow feature is enabled, it also triggers via workflow events. So you can hook into this system from the admin without C#. It needs to be able to serialize/deserialize between workflow steps, in case someone added a custom header using JInt or something. I realize it's a pretty niche use, and we could've introduced an intermediate type with the same properties, but that would've been an unnecessary major breaking change.

**Comment by hishamco** [comment]
If the columns need to be added at runtime this sort of dynamic localization, right?

**Comment by sarahelsaig** [comment]
yes

**Comment by hishamco** [comment]
For that I suggest to wait for #4466 to be merged, no need to add such converters IMHO

**Comment by sarahelsaig** [comment]
I meant that dynamic localization is involved, but it's not all what it does. You can also change which columns to display based on business logic by altering this array of headers. For example add completely new columns, or toggle existing ones based on site/user settings. So https://github.com/OrchardCMS/OrchardCore/pull/4466 will be super useful here, but we still need the converters one way or another.

**Comment by hishamco** [comment]
I might need to look deeply into your shopping cart implementation to check if we can fix the issue without JSON convertors

**Comment by sarahelsaig** [comment]
Sure, like I wrote above we could introduce an intermediate type that has the same properties as `LocalizedHtmlString`. Then I can convert between it and `LocalizedHtmlString` in the workflow activity code in C#. I can work around it if we are really unwilling to add JSON converters. It's just extra work and complexity for seemingly no reason.
I still don't understand what's problematic about adding the converters though. Why do you want to avoid adding two more, when there are already several converters added to `JOptions.Default`?

**Comment by sebastienros** [comment]
Please join us on Tuesday and show us the feature and how it's implemented. Then you may convince me. But right now I'd just say change your code to store the Name of the localized string, not the localization itself.

> I still don't understand what's problematic about adding the converters though

Because nobody should be able to do it. If you need it in OCC customize the options, but I still disagree with it.

**Comment by sarahelsaig** [comment]
I wasn't trying to turn this into a debate or argument. I just want to understand what's problematic about adding the converters, _why_ nobody should be able to do it? I'm asking for clarification.
