### ISSUE TITLE
Allow users to enter custom list of items for each content item

### ISSUE THREAD

**Issue by mdameer** [OrchardCMS/OrchardCore#16352]
### Is your feature request related to a problem? Please describe.

Currently, no field allows users to enter a custom list of items for each content item.

### Describe the solution you'd like

Enhance the `MultiTextField` with a new editor called `EditableList`, which will let users define default items (Array of strings not options like current editors) for new content items, then can be managed from the content item edit screen, allowing users to add, remove, or edit items as needed.

### Describe alternatives you've considered

Adding a new field to handle this feature, but extending `MultiTextField` seems feasible and efficient.

**Comment by Piedone** [comment]
What's your use case, exactly? Also, wouldn't Taxonomies cover this?

**Comment by mdameer** [comment]
@Piedone I have a case where I want to add a list of items to describe the content item but without restricting the user to have all those items predefined in the field settings, so he can add different list per content item, like this image:

![image](https://github.com/OrchardCMS/OrchardCore/assets/2022320/40e4c8fd-b99e-41a3-b316-3fdc1c6719be)

**Comment by Piedone** [comment]
I understand _what_ you'd like to do, but I don't understand _why_ you'd like to do it. If you can explain it, it would help all of us assess better how to address your needs, what might not be doing exactly what you envision right now.

**Comment by hishamco** [comment]
> Currently, no field allows users to enter a custom list of items for each content item.

Why you didn't use `ContentItemList`?

**Comment by sebastienros** [comment]
We said we would never do this because it would mean we'd need to do it for any field type. You can use a bagpart for that. Or you can come with a better solution that would allow any field to be wrapped in a custom multi-everything editor. But it's a bag part ...
