### ISSUE TITLE
FE theme dlls missing in custom bin folder in release build

### ISSUE THREAD

**Issue by bashuss** [OrchardCMS/OrchardCore#16358]
### Describe the bug
As I have two versions of my main project file in the same folder, I configured a custom build target folder (instead of 'bin') for one of these project files. This works fine for DEBUG builds, but in RELEASE the front end theme dlls are missing.

### Orchard Core version
2.0.0-preview-18248

### To Reproduce
1. Create a full git checkout of OC
2. Go to `OrchardCore.Cms.Web` project folder
3. Copy the project file and rename it to `OrchardCore.Cms.Web.Nuget`
4. Include the new project in the solution and open its property page
5. Change output path from "bin\" to "bin-nuget\"
6. Remove the project reference `OrchardCore.Application.Cms.Targets` from `OrchardCore.Cms.Web.Nuget` project
7. Add nuget package `OrchardCore.Application.Cms.Targets` to `OrchardCore.Cms.Web.Nuget` project
8. Build `OrchardCore.Cms.Web.Nuget` as debug and build as release
9. Compare files in `bin-nuget\Debug\net8.0\` and `bin-nuget\Release\net8.0\`
10. Here the front end theme files are present in debug build, but missing in release build.

### Expected behavior
theme files should be present also in the release build directory.

**Comment by bashuss** [comment]
Well - strange enough, after several builds confirming what I wrote, I finally have a release build folder containing the files. Still they were not shown in the admin as available themes.

After stopping the website, deleting the Release folder and starting the project again, the files were created in the new Release folder and now they are available in admin/themes.

This may be trouble with the "shared" object folder between the two project files sharing the source. But this does not explain, why the admin did not show the themes, when they were there.

I am confused.

**Comment by Piedone** [comment]
While I don't have an answer, I highly recommend you follow standard, simple setups, like having a separate solution/app in a separate folder for using OC from NuGet, and not mixing it with the full source.,
