### ISSUE TITLE
Shell blueprint is missing dependencies

### ISSUE THREAD

**Issue by gvkries** [OrchardCMS/OrchardCore#16375]
### Describe the bug

During startup, the `ShellContainerFactory` is relying on the `ShellBlueprint.Dependencies` property to get all startup classes that needs to be added to DI. But if an extension contains only features that do not match the extension ID, dependencies without any feature assignment are not added to the blueprint at all. 

That means that some startup classes not executed at all.

### Orchard Core version

Reproducible in `1.8.3` and later. I didn't check earlier versions. 

### To Reproduce

1. Enable the features `Microsoft Entra ID Authentication` and `Deployment`. 
2. Create a deployment plan and add steps to it. The `Microsoft Entra ID` step is missing there, because its startup class `OrchardCore.Microsoft.Authentication.DeploymentStartup` is not executed.

### Expected behavior
All startup classes which meet their dependencies should be executed.

**Comment by Piedone** [comment]
Did you notice any other features affected in the current source?

**Comment by gvkries** [comment]
This is a general issue, but I didn't searched for other cases explicitly.
