### ISSUE TITLE
Support HTML in Markdown by default

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16376]
### Describe the bug
Markdown is convert to HTML using the `DefaultMarkdownService` implementation of `IMarkdownService`. However, by default we do not support HTML. https://github.com/OrchardCMS/OrchardCore/blob/51eb7b8f2481de0b05592b79cc4feb1c390cc0be/src/OrchardCore.Modules/OrchardCore.Markdown/Startup.cs#L27

However, is MarkdownBodyPart and MarkdownFieldPart we give the user an option weather or not to sanitize HTML. If we strip HTML by default, then that option to sanitize is useless since we always sanitize the markdown input.

### Orchard Core version

2.0

### To Reproduce
1. Create content type with MarkdownBodyPart. Edit the MarkdownBodyPart settings and uncheck the "Sanitize HTML" option. Save the changes.
2. Create new content item by providing HTML into the markdown input. Then publish the item.
3. View the published item. you'll see the HTML being printed as text.

### Expected behavior
If I do not sanitize HTML then HTML should be printed as-is.

There are two ways to solve this issue.
- Option 1: enable HTML support in markdown service by default.
- Options 2: keep HTML disabled by default in Markdown service, but create a new implementation of `IMarkdownService` to support HTML by default and use it in `MarkdownBodyPart` and `MarkdownFieldPart`

I'll submit a PR for Option 1.

**Comment by sebastienros** [comment]
I believe it's a missunderstanding of the settings and features. The default markdown service still return html (pre, p, bold, ...) even though it can also escape some HTML from the input. We do need the sanitize setting for this reason, and when custom implementations are provided, and if users change the `nohtml` setting.
