### ISSUE TITLE
Orchard corrupts Elastic stemmer configuration

### ISSUE THREAD

**Issue by Lenar-Avia** [OrchardCMS/OrchardCore#16384]
### Describe the bug
Customer Elastic analyzers configuration from OrchardCore_Elasticsearch block gets corrupt

### Orchard Core version
1.8.2

### To Reproduce
1. Go to 'OrchardCore_Elasticsearch' section in configuration
2. Try to set up simple stemmer analyzer, SPANISH for example, as explained at:
 https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#spanish-analyzer
3. Make sure you have both "analyzer" and "filter" sections inside "analysis" block
4. Save and apply configuration
5. Check out current GET .../_settings of elastic - to find out there is no "analysis.filter" area.
i.e. actual settings now do not contain "filter" area (on the same level as "analyzer")
6. Check out the termvectors to see that no handling happened to substrings. 

### Expected behavior
I would expect the termvectors to be created using stemmer.
When directly setting config using PUT ../_settings , custom morphological analyzer can be applied. 

### Logs and screenshots
Please try to reproduce the following settings using OrchardCore_Elasticsearch:
```

"analysis": {
  "filter": {
	"spanish_stop": {
	  "type":       "stop",
	  "stopwords":  "_spanish_" 
	},
	"spanish_stemmer": {
	  "type":       "stemmer",
	  "language":   "light_spanish"
	}
  },
  "analyzer": {
	"default": {
	  "tokenizer":  "standard",
	  "filter": [
		"lowercase",
		"spanish_stop",
		"spanish_stemmer"
	  ]
	}
  }
}
```

**Comment by MikeAlhayek** [comment]
@Lenar-Avia I am not sure I follow your steps. But in order to create `rebuilt_spanish` you referenced, your configuration should look like the following:

```
"OrchardCore_Elasticsearch": {
  "ConnectionType": "SingleNodeConnectionPool",
  "Url": "http://localhost",
  "Ports": [ 9200 ],
  "CloudId": "Orchard_Core_deployment:ZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbTo0NDMkNmMxZGQ4YzBrQ2Y2NDI5ZDkyNzc1MTUxN2IyYjZkYTgkMTJmMjA1MzBlOTU0NDgyNDlkZWVmZWYzNmZlY2Q5Yjc=",
  "Username": "admin",
  "Password": "admin",
  "CertificateFingerprint": "75:21:E7:92:8F:D5:7A:27:06:38:8E:A4:35:FE:F5:17:D7:37:F4:DF:F0:9A:D2:C0:C4:B6:FF:EE:D1:EA:2B:A7",
  "EnableApiVersioningHeader": false,
  "IndexPrefix": "",
  "Analyzers": {
    "rebuilt_spanish": {
      "tokenizer":  "standard",
      "filter": [
        "lowercase",
        "spanish_stop",
        "spanish_keywords",
        "spanish_stemmer"
      ]
    }
  }
}
```

[Here is a reference](https://docs.orchardcore.net/en/latest/reference/modules/Elasticsearch/#elasticsearch-configuration) from our documentation

**Comment by MikeAlhayek** [comment]
Filters is not something we support in OC. Feel free to submit a PR that would add filters support in addition to the analyzers.
