### ISSUE TITLE
Turkish Characters in URL Slug

### ISSUE THREAD

**Issue by fabrikamedya** [OrchardCMS/OrchardCore#16393]
### Describe the bug
I am using OrchardCore in Turkish. In Turkish, there are characters such as ı, I, ş, Ş, ö, Ö, ü, Ü, ğ, Ğ, ç, and Ç. I am experiencing an issue where, when I use Turkish characters (ı) in titles, the URL slug is also created with Turkish characters. 

### Orchard Core version
orchardcore-cms-linux:1.8.2

Add the version of the Orchard Core NuGet packages you use, or the commit hash if you can reproduce this with the source code.

### To Reproduce
1. Create new Page
2. Add a Title, in Turkish Language, like: "Başlık" after click to publish
3. Check the URL Slug

### Expected behavior
When I create a title with Turkish characters, I want the URL slug to be generated with English characters as it normally should be.

### Logs and screenshots
<img width="316" alt="Screenshot 2024-07-02 at 10 49 23" src="https://github.com/OrchardCMS/OrchardCore/assets/74364943/640c2b4e-6abc-41e7-9bc4-e36c4fac06a3">

**Comment by hishamco** [comment]
This is because the `SlugService` removes the diacritics, have a look to this test

https://github.com/OrchardCMS/OrchardCore/blob/fd02d1167ead26829d1112c170bf4d66933b638c/test/OrchardCore.Tests/Tokens.Content/SlugServiceTests.cs#L62-L67

**Comment by Piedone** [comment]
Hisham, the issue here is that `SlugService` doesn't remove the Turkish diacritics.

**Comment by hishamco** [comment]
Maybe I am confused with the "I" symbol in the screenshot, I will try to reproduce the issue

**Comment by hishamco** [comment]
@fabrikamedya ignore my first comment

**Comment by emrahtokalak** [comment]
I wrote my own liquid filter for this problem. All it does is convert the character "i" to "i".

<img width="796" alt="Screenshot 2024-07-04 at 09 42 54" src="https://github.com/OrchardCMS/OrchardCore/assets/90242/22fce262-f3f8-4cf6-b8e9-b5f82d933120">

**Comment by fabrikamedya** [comment]
> I wrote my own liquid filter for this problem. All it does is convert the character "i" to "i".
> 
> <img alt="Screenshot 2024-07-04 at 09 42 54" width="796" src="https://private-user-images.githubusercontent.com/90242/345723804-22fce262-f3f8-4cf6-b8e9-b5f82d933120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzYxOTgsIm5iZiI6MTcyMDA3NTg5OCwicGF0aCI6Ii85MDI0Mi8zNDU3MjM4MDQtMjJmY2UyNjItZjNmOC00Y2Y2LWI4ZTktYjVmODJkOTMzMTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA2NTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZDUzMjA3NjM0OGZiY2FhNDU0OTJhYTExNDZhNjZlMWZmYTEyYmFjN2E0ZjMwZjVmODg3N2ZiOWE5ZGExOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OX7EYxkJ_zCvac4o6pIHNepByRg6owRcnC79qkHAWiA">

Great! Thank you.

**Comment by hishamco** [comment]
@emrahtokalak that's not enough, the fix should remove all Turkish diacritics

**Comment by arkadiuszwojcik** [comment]
Duplication of #4874 ?

**Comment by Piedone** [comment]
Yes, this is actually a duplicate of https://github.com/OrchardCMS/OrchardCore/issues/4874. Let's continue there.

**Comment by hishamco** [comment]
Related to https://github.com/OrchardCoreContrib/OrchardCoreContrib/issues/11
