### ISSUE TITLE
After add SeoMeta to page, page title is not displayed

### ISSUE THREAD

**Issue by sayyad84** [OrchardCMS/OrchardCore#16408]
### Describe the bug
Hi,
I am using version 1.8.3 of the software. After add SeoMeta to page, page title is not displayed on browser tab.
Page title in settings:
{% page_title Site.SiteName, position: "before", separator: "|" %}

### Orchard Core version
1.8.3

### To Reproduce
Add SeoMeta part to Page ContentItem

### Expected behavior
The title of the page should be displayed correctly and in the following format or the meta title should be used instead of the page title:
{% page_title Site.SiteName, position: "before", separator: "|" %}

**Comment by sayyad84** [comment]
Screen shots:
![2024-07-08_173054](https://github.com/OrchardCMS/OrchardCore/assets/57654948/8bd47bcd-9882-48a0-8e26-cc37b41d6cd9)
![2024-07-08_173155](https://github.com/OrchardCMS/OrchardCore/assets/57654948/6c7227cc-a312-4fdc-b261-4d4e1e1bcd69)

**Comment by Piedone** [comment]
I still can't reproduce (this is 1.8.3), looks correct:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/c26ed372-12ae-440c-87f8-480148d10558)


Something is specific to your application. Please check with a vanilla OC 1.8.3.

**Comment by sayyad84** [comment]
Thanks for reply.
Can you enable the options in SeoMeta part one and try again? from Edit button for SeoMeta part in Page content item.

**Comment by Piedone** [comment]
I enabled all of them, same thing:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/1bf3e424-ad4e-4ecc-ad77-974500f339a3)

Please provide precise reproduction steps with a vanilla 1.8.3 app, or better, the latest source from `main`.

**Comment by sayyad84** [comment]
I have a bilingual site, one of its languages ​​is Farsi (right to left), if possible, check this mode as well.

**Comment by Piedone** [comment]
Please provide precise reproduction steps with a vanilla 1.8.3 app, or better, the latest source from main.
