### ISSUE TITLE
Improve setup UX when using a password manager

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#16465]
### Is your feature request related to a problem? Please describe.

During local development you will want to reuse saved admin credentials. Using the browser's password manager is helpful here, but the setup screen fails to anticipate this scenario. As you fill in the saved password, the strength bar under the password field doesn't update and the "Finish Setup" button won't do anything, as if broken. You have to click into the password field and press a key. This is a minor annoyance, but it's persistent and irritating when you work with OC a lot.

[setup-doesnt-respect-stored-passwords.webm](https://github.com/user-attachments/assets/bfe406a6-f236-46b9-93bf-8995d91a13ac)

### Describe the solution you'd like

The strength function should handle `change` events too, not just `keydown` and `keyup`. Also clicking on the "Finish Setup" button should trigger it as well, instead of silently failing.

**Comment by Piedone** [comment]
While this is indeed annoying, if you do a lot of OC setups, rather you should automate it. I thought about this for reviews of OC PRs, and I'm not yet satisfied with either:

- Configure Auto Setup for myself but don't commit it (like appsettings changes) to run the setup on on the first request.
- Add [Setup Extensions](https://github.com/Lombiq/Setup-Extensions) and script the setup but don't commit it.
- I haven't tried but script the setup with Selenium or something (this won't be part of the repo anyway).

**Comment by Piedone** [comment]
Hmm, actually yed, since Auto Setup is added in the Program file, it should be configurable from env vars too.

**Comment by sarahelsaig** [comment]
I think user secrets are the way to go for configuring AutoSetup. They are straight forward to set up and use, can't be committed into git, don't seep into other projects. You only have to add a single line of [`<UserSecretsId>{random GUID}</UserSecretsId>`](https://github.com/OrchardCMS/OrchardCore/pull/16466/commits/a0d8688707c6a081db54d010411ee0f8f5507dd0) to the startup project's csproj which is safe and not intrusive. I've [updated the AutoSetup docs](https://github.com/OrchardCMS/OrchardCore/pull/16466/files#diff-ed001d9b08e75b42c3b00f2e4b33f5907ad3fb1bb879ced1b1c0a91c172feac9) in the PR to mention this option.
