### ISSUE TITLE
Safely enter in a new service scope on a non released shell context.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#1646]
`EnterServiceScope()` fails if the shell context is released but `GetOrCreateShellContext()` return a non released context. That said, potentially, between the 2 following calls a shell context could be released.

    shellContext = _orchardHost.GetOrCreateShellContext(shellSettings);
    using (var scope = shellContext.EnterServiceScope())

- So maybe worth to create a new method to return a tracked scope atomically.

- Then, maybe worth to also check in `AddDependentShell()` if the shell context is released before adding a dependent, and then release the dependent or just throw as we do in `EnterServiceScope()`.

**Comment by jtkech** [comment]
@sebastienros just for infos on some tests around the shell.

The main test i did, while enabling / disabling a module (so the shell is removed from the dictionary), is to start an apache bench of 1000 requests with a concurrency level of 10.

- The result is that **many context are created** and not added to the dictionary, so at some point this is the **GC which disposes them through their finalizers**.

- Moreover, doing this i had different issues, invalid serial number, Null reference ... And **i could crash the application** without being able to restart it, i needed to redo a fresh setup.

- Then using a **dictionnary of lazy values fixed these issues**.

---

Then after this, when doing a setup i still saw 3 or 4 times that a shell is diposed through its finalizer. And when starting the application there was still one case.

- One case is when we explicitly create a temporary shell context (not added and never removed from the dictionary and never released) and use it temporarily by entering in a scope, then when exiting the scope, because the shell is not released, it is not disposed.

- I could get rid of this by adding in 2 or 3 places `shellContext.Release()` just before exiting the scope and when we know that this shell context will not be used anymore.

- Another use case i saw is when we remove from the dictionary a shell which has no active scope. Then we release it but there is no scope to dispose it afterwards.

- In fact, in `Release()`, at the end we dispose it if `_refCount == 0`, but before we check if `_dependents == null`. So i could easily fix this use case **and then, during a setup or a regular start, the shell context finalizer was no longer called, always disposed by their last scope**.

- Note: Hmm, because in `Release()` we can call `Dispose()` (here in a lock block), i need to think about the case we do this just while the last scope is doing it concurrently.

---

I also read some articles around disposing and finalizers, e.g a great one from `Stephen Cleary`. Based on what i understood, here some suggestions.

- I think the `ServiceScopeWrapper` doesn't need a finalizer and a call on `GC.SuppressFinalize()`. During all my tests, its finalizer was never called. Here, we are quite sure that an using block pattern is used.

- We saw above that the `ShellContext` finalizer could be called but, if we do things correctly, maybe here also we don't need a finalizer. At least, after the fix with lazy values the finalizer would be much less called. And if we take care to release temporary shells when they will not be used anymore, maybe all will be ok. But, maybe the best compromise is to keep the finalizer, maybe with some little changes.

I will do some suggestions on all of this in a PR.

**Comment by jtkech** [comment]
@PinpointTownes @sebastienros just for infos and as a reminder, nothing urgent for me.

Regarding the following comment which i splitted in 2 parts.

    // 1. If the other tenant is released, ensure the current tenant is also restarted as it
    // relies on a data protection provider whose lifetime is managed by the other tenant.

    // 2. To make sure the other tenant is not disposed before all the pending requests are
    // processed by the current tenant, a tenant dependency is manually added.

I think that currently we implement 1. but not 2. Here, when the other tenant is released (marked to be disposed) the current tenant is released. Then the other tenant will be disposed only if there are no active scope on it but, currently, it will not wait that there is no active scope on its dependents.

Hmm, maybe not so simple to do, if a tenant is released and removed from the shells list, if we defer its disposing it could be garbage collected, unless if its dependents have a reference on it ... We would need to implement a little more complex dependency graph, but interesting.

---

Then in the following code (without comments and using the new `EnterServiceScope()` i'm testing)

    var shellSettings = _shellSettingsManager.GetSettings(settings.Tenant);
    // Here we would need to check if shellSettings.State == TenantState.Running
    using (var scope = _shellHost.EnterServiceScope(shellSettings, out var context))
    {
        context.AddDependentShell(_shellHost.GetOrCreateShellContext(_shellSettings));
        // Otherwise, here the scope.ServiceProvider might be null
        options.DataProtectionProvider = scope.ServiceProvider.GetDataProtectionProvider();
    }

**I will do a suggestion** in my PR #1669, please review it, e.g maybe good to have a warning message.

---

Finally, in the following code

    model.AvailableTenants =
        // Here we would need to filter running tenants.
        (from tenant in _shellSettingsManager.LoadSettings().AsParallel()
        // Otherwise, here the provider might be null
        // Also, just after this the tenant could be released and then disposed.
        // So, we could use the new EnterServiceScope() we want to do to get a scope atomically
        let provider = _shellHost.GetOrCreateShellContext(tenant).ServiceProvider
        // And then use this tracked scope to resolve this service
        let descriptor = provider.GetRequiredService<ShellDescriptor>()
        where descriptor.Features.Any(feature => feature.Id == OpenIdConstants.Features.Server)
        select tenant.Name).ToList();

**I will do a suggestion**.

Finally, i asked me if here it would be better to use `_shellHost.ListShellContexts().Where(...` as i do right now in the background service branch. Knowing that on startup all valid tenants are created and added to the list, and, at least through the UI, when a tenant is released (e.g by changing a feature) it is created again and re-added to the list through the request due to the UI redirection (unless the tenant is disabled).

But now when a given tenant releases its dependents, this is not the case for these dependents until a next request on them. So here maybe better to keep `GetOrCreateShellContext()`, here i was just a little afraid to create too many tenants at once (if many are released but not yet re-created). **And maybe i will do the same in the background, otherwise the bg tasks of a dependent might not be executed anymore**.

**Comment by PinpointTownes** [comment]
> I did a suggestion in #1669, please review it, e.g maybe good to have a warning message.

Thanks, I'll take a look :clap:
