### ISSUE TITLE
Truncatewords breaks in markdownify

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/OrchardCore#16475]
- `{{ Model.Content.Person.About.Markdown | truncate: 400  | markdownify | raw  }}` work as expedcted
- `{{ assigned_author.Content.Person.About.Markdown | truncatewords: 40  | markdownify | raw  }}` doesn't render markdown
- `{{ assigned_author.Content.Person.About.Markdown  | split: " " | slice: 0, 40 | join: " " | append: "..." | markdownify | raw }}` working workaround

When hacking a workaround, I've got a hunch it's something to do with the "..." ie. When I place the `append` filter at the end, then the markdown breaks.

Not sure if this is a `Fluid` or `OrchardCore` issue.

**Comment by MikeAlhayek** [comment]
@SzymonSel are you able to provide a report for this? A test case will help identifying the issue

**Comment by SzymonSel** [comment]
Sorry, perhaps I wasn't too clear. What I meant was, that I'm not sure whether it's `markdownify` or `truncateword` the culprit.

A test case scenario:
- Create a `ContentType` with a `MarkdownField` ie MarkdownTest
- Create a Liquid Template ie. `Content__MyTestContentType`
- Provide the template code as such:
    - `{{ Model.ContentItem.Content.MyTestContentType.MarkdownTest.Markdown | truncate: 400  | markdownify | raw  }}` work as expedcted
    - `{{ Model.ContentItem.Content.MyTestContentType.MarkdownTest.Markdown | truncatewords: 40  | markdownify | raw  }}` doesn't render markdown
    - `{{ Model.ContentItem.Content.MyTestContentType.MarkdownTest.Markdown  | split: " " | slice: 0, 40 | join: " " | append: "..." | markdownify | raw }}` working workaround

**Comment by SzymonSel** [comment]
Ok, ok! geesh!
Example: 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
```
Output 1, `truncate: 100`:
Lorem ipsum dolor sit amet, consectetur adipiscing elit,
>sed do eiusmod tempor incididunt ut l...

Output 2, `truncate_words: 12`:
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

Output3, hacked. This is what I would expect trunctate_word and markdownify to do:
Lorem ipsum dolor sit amet, consectetur adipiscing elit,
>sed do eiusmod tempor...

**Comment by sebastienros** [comment]
So it looks like `truncate_words` is not doing anything?

Have you tried the actual filter named `truncatewords`, I don't think `truncate_words` exists ;)

**Comment by sebastienros** [comment]
https://shopify.github.io/liquid/filters/truncatewords/

**Comment by SzymonSel** [comment]
Yes, you are correct :) I've corrected my example - the problem still stands, though slightly different

**Comment by sebastienros** [comment]
Output1 results look fine
Output2 results look fine

> Output 3, hacked. This is what I would expect trunctatewords + markdownify to do:

So in this case it's `truncatewords: 12 | markdownify` ? And you made up what you expect? What do you actually get?

**Comment by SzymonSel** [comment]
No. Output 2 doesnt get "interpreted" and just displas the raw, truncated text as if mardownify didn't work.

**Comment by sebastienros** [comment]
> No. Output 2 doesnt get "interpreted" and just displas the raw, truncated text as if mardownify didn't work.

This is not compatible with what you wrote in the issue:

![image](https://github.com/user-attachments/assets/d7eb5199-8923-4d50-b772-4c5422c15d8a)

I have still no idea if you are using markdownify in these examples, and if it's the case then what is the output from truncate? These should be two different concerns, and only one should be described as the issue. Your examples suggest they only use truncatewords. Skype me if you want to show what you are doing and getting.

**Comment by SzymonSel** [comment]
Ok, I'll try again. I was referering to the original examples. From the top:

Example value of `Model.ContentItem.Content.MyTestContentType.MarkdownTest.Markdown`:

````
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
````

1. `{{ Model.ContentItem.Content.MyTestContentType.MarkdownTest.Markdown | truncate: 400  | markdownify | raw  }}`
    Output 1:

      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      >sed do eiusmod tempor incididunt ut l...



2. `{{ Model.ContentItem.Content.MyTestContentType.MarkdownTest.Markdown | truncatewords: 40  | markdownify | raw  }}`
    Output 2:

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, \>sed do eiusmod tempor incididunt ut l...
 

3. `{{ Model.ContentItem.Content.MyTestContentType.MarkdownTest.Markdown  | split: " " | slice: 0, 40 | join: " " | append: "..." | markdownify | raw }}`
     Output 3:
   
     Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     >sed do eiusmod tempor...

**Comment by sebastienros** [comment]
`truncatewords` removed the line break, making the markdown invalid.

Repro-ing:

```
{% assign md = "Lorem ipsum dolor sit amet, consectetur adipiscing elit,\n>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " %}
{{ md | replace: "\n", "###"}}
---
{{ md | truncatewords: 12  | replace: "\n", "###"}}
```

Outputs:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit,###>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit, >sed do eiusmod tempor...
```

Verified on https://shopify.dev/docs/api/liquid by pasting the example above.

`truncatewords`, like `truncate` will mess-up the html/markdown. You can't assume it will be valid after that, even if it was not removing libre breaks, it could remove a `__` or `#`, (or break an HTML tag). The solution is to remove any tagging then apply the truncation.

**Comment by SzymonSel** [comment]
Well, but `truncate` didn't mess up anything - but I guess it's a matter of finding an example which will break it.

So to conclude: `truncate` and  `truncatewords` don't mix and match with `markdownify` unless someone feals lucky ;)

**Comment by sebastienros** [comment]
Exactly. For HTML that's why there is a filter to remove all the tags. You could contribute the same thing for markdown if you want.

**Comment by sebastienros** [comment]
check this warning on the Shopify website for truncatewords:

```
Caution

HTML tags are treated as words, so you should strip any HTML from truncated content. If you don't strip HTML, then closing HTML tags can be removed, which can result in unexpected behavior.
```

**Comment by SzymonSel** [comment]
True true. Thanks for your time Seb!
I'll make a note to myself to make the contribution in the future not so far away :)

**Comment by sebastienros** [comment]
> Well, but truncate didn't mess up anything

It did! It remove the line break right before the markdown quote `>` and thus it's not a valid markdown quote anymore.

**Comment by SzymonSel** [comment]
"Output 1" looks fine to me, it's "Output 2" that's lost a line break

**Comment by sebastienros** [comment]
Sorry, didn't realize you mentioned `truncate` specifically, correct. It seems it doesn't remove line breaks by design, checked on shopify. It will still be an issue with formatted text.
