### ISSUE TITLE
Zone not found while invoking 'render_section': Header

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#16478]
### Describe the bug

It throwed "invalidOperationException: Zone not found while invoking 'render_section': Header" when Adding Header, Footer zone again after  deleting initial all of zones.

### Orchard Core version

1.8.3

### To Reproduce
1. Go to 'Design->Settings->Zones'
2. Delete all of zones
3. Click on 'Save'
4. Go to 'Design->Settings->Zones'
5. Add zones: Header,Footer
6. Click on 'Save'
7. Go to Home Page
8. See error

![image](https://github.com/user-attachments/assets/f2a65dd5-475a-43f6-826e-937e7b3c6af9)

**Comment by Piedone** [comment]
Can't reproduce with vanilla 1.8.3 with the Blog theme, despite changing it to have a `{% render_section "Header", required: true %}`.

Note that this exception is thrown if you try to render the zone with `{% render_section "Header", required: true %}` but the zone is empty, i.e. it doesn't have any shapes or widgets. If you want to allow empty zones, you need to render it with `{% render_section "Header", required: false %}`.

**Comment by effapp** [comment]
Hi @Piedone,
     Yes, I have changed it to have  '{% render_section "Header", required: true %}' and there's a test html widget in Header Zone.

At first, it was normal, but after I deleted the Header，Footer zone, saved it, and then re-added the Header,Footer zone and added widgets to these zone,  then the error occurred.

**Comment by Piedone** [comment]
Can't reproduce with a widget either (having a widget in the zone causes this exception not be thrown anyway).

Please provide a screen recording of you reproducing this, starting from an empty app, and showing the whole browser window.

**Comment by effapp** [comment]
Hi @Piedone,
There is a abnormal appearance : 
After Deleting all of zones, the widgets in the zones still exists. As follows:
steps:
1. delete all of zones and click on 'Save'
![image](https://github.com/user-attachments/assets/70261f84-39ec-4bf2-b8c0-ec1cc6ae8281)

2. Go to 'Design -> widgets', As follows:
![image](https://github.com/user-attachments/assets/b3f505f2-92ea-4147-a08b-7172dc244b9b)

3. Re-added zones and click on 'Save', as follows:
![image](https://github.com/user-attachments/assets/da5188ac-0591-4d64-8359-fd3f581c318c)

4. Go to 'Design -> Widgets', the previous widgets have reappeared , as follows:
![image](https://github.com/user-attachments/assets/d4567253-7425-4bd2-9081-2d25faf80cb7)

5. Go to home page , error occured, as follows:
![image](https://github.com/user-attachments/assets/8616c523-da9c-46e5-9426-92e33978a2e0)

6. Delete all of widgets in zones, re-added other widgets in zones and save
7. Go to home page , error occured, as follows:
![image](https://github.com/user-attachments/assets/8616c523-da9c-46e5-9426-92e33978a2e0)

**Comment by Piedone** [comment]
Thank you for the details! However, I still can't reproduce with vanilla 1.8.3 (nor do I see how this can happen with the 1.8.3 code). Could you try to reproduce it with a vanilla 1.8.3 as well, including the changes you make to e.g. the Blog theme? Or share the full solution with us, including not just the source but the DB.

**Comment by effapp** [comment]
I deleted the site and reinstalled it, and all the issues was resolved. Thanks.

**Comment by effapp** [comment]
I deleted the site and reinstalled it, and all the issues was resolved. Thanks.
