### ISSUE TITLE
Silently omit exception from Redis

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#16483]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Currently if the Redis is enabled and Redis server is not available, the whole site will fail in the beginning.

### Describe the solution you'd like

it should not influence the **_whole_** site. 

```
==========
An unhandled exception occurred while processing the request.
RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
StackExchange.Redis.ConnectionMultiplexer.ConnectImplAsync(ConfigurationOptions configuration, TextWriter writer, Nullable<ServerType> serverType) in ConnectionMultiplexer.cs, line 620

Stack Query Cookies Headers Routing
RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
StackExchange.Redis.ConnectionMultiplexer.ConnectImplAsync(ConfigurationOptions configuration, TextWriter writer, Nullable<ServerType> serverType) in ConnectionMultiplexer.cs
OrchardCore.Redis.Services.RedisDatabaseFactory+<>c__DisplayClass6_0+<<CreateAsync>b__0>d.MoveNext()
OrchardCore.Redis.Services.RedisService.ConnectAsync()
OrchardCore.Environment.Shell.Scope.ShellScope+<>c+<<ActivateShellInternalAsync>b__43_0>d.MoveNext()
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell)
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

Show raw exception details
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImplAsync(ConfigurationOptions configuration, TextWriter writer, Nullable`1 serverType) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 620
   at OrchardCore.Redis.Services.RedisDatabaseFactory.<>c__DisplayClass6_0.<<CreateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Redis.Services.RedisService.ConnectAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.<>c.<<ActivateShellInternalAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by hishamco** [comment]
Please steps to reproduce

**Comment by infofromca** [comment]
1--enable Redis feature
2--no redis server 
3--got result
![屏幕截图 2024-07-24 110705](https://github.com/user-attachments/assets/5b73ff9a-f6f0-496b-a72c-014491bb4b2b)

**Comment by MikeAlhayek** [comment]
It sounds like your Redis server is not reachable from your localhost

>  RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.

**Comment by infofromca** [comment]
the home page of the site did not call IRedisService or any other Redis stuff.  
why even for home page , the site was down. 
IMO, the pages which are not related with redis, should run well

**Comment by MikeAlhayek** [comment]
I think if the Redis feature is enabled, it'll attempt to make a connection to the server which could be causing your issue. So I don't think you need to hit a page that uses IRedisService to encounter an issue with the connection string.

**Comment by infofromca** [comment]
The pages which use db as data source should keep working as normal.
and the page use redis should fail as expected. 
in this way, the whole can run silently and smoothly in my view.

**Comment by MikeAlhayek** [comment]
@infofromca 

Based on what I can see, if you only enabled the Redis module, you should not get an exception. If the connection fails we log an error but we catch the exception so it should not break you app.

https://github.com/OrchardCMS/OrchardCore/blob/84ae5cb0c8e0ec297a645f32b39695c3ea7003a3/src/OrchardCore.Modules/OrchardCore.Redis/Services/RedisDatabaseFactory.cs#L38-L55

The error you shared, what that displayed on the UI or you got that from the logs? I expect it to be in the logs only but the UI should not break.

**Comment by infofromca** [comment]
The UI was broken on home page. See the screenshot above

**Comment by infofromca** [comment]
Ok. May be the home page called Iredisservice

**Comment by infofromca** [comment]
after double check , my home page use Article contentType which only includes those 4 parts :
Title Provides a Title for your content item. 
Alias Provides a way to define custom aliases for content items. 
Autoroute Provides a custom url for your content item. 
HtmlBody Provides an HTML Body for your content item.

those 4 parts are not related with Redis  I think.
but when I run the site,  it hit redis stuff on the home page which cause the UI broken. reopen this issue.
![屏幕截图 2024-07-24 175033](https://github.com/user-attachments/assets/9cabdb69-4b3c-4731-b89f-a66c511f7402)

**Comment by infofromca** [comment]
this is the code the home page hit:
private IDatabase? GetRedisDatabase()
{
    IDatabase? database = null;
    var redisService = _serviceProvider.GetService<**IRedisService**>();
    if (redisService != null)
    {
        database = redisService.Database;
    }

    return database;
}

**Comment by MikeAlhayek** [comment]
@infofromca I think there is something invalid on your end (somewhere).

I can't reproduce this issue in OC. I created the a new tenant using the blog recipe. I then configured Redis with wrong credentials, enabled Redis and Redis Cache. When the app started I do see the error you encountered in my logs, but the UI did not break as expected since we catch the connection exception.

**Comment by infofromca** [comment]
@MikeAlhayek Thanks, it happened on my custom layout. so close this
