### ISSUE TITLE
Trouble with hot reload in OC 1.8.3 and net8.0

### ISSUE THREAD

**Issue by DavidStania** [OrchardCMS/OrchardCore#16504]
Hello everyone,
I have a problem with HotReload in VS2022 17.10.5 (current).
No changes are applied. The application has to be restarted again and again to apply changes.

I have made several attempts:
1. Asp Net Core WebApp with .net8.0 without OC
No problems! All changes are applied immediately.
2. Asp Net Core WebApp with .net7.0 with OC 1.7.2
No problems! All changes are applied immediately. Also changes in the modules themselves.
3. Asp Net Core WebApp with .net8.0 with OC 1.8.3
No changes are applied. However, HotReload registers changes.

I have recorded a [video ](https://youtu.be/LY8NhuP7iTo) to demonstrate this. I currently have the problem on 4 independent computers. 

I would be grateful for any advice!

**Comment by Piedone** [comment]
Could you please check with the latest `main`? This is what I see there, it works for me:

https://github.com/user-attachments/assets/ad126189-dc79-4269-bc98-2c0d38d4ece3

Note that apart from saving the cshtml file, I didn't do anything, the browser reloaded itself.

**Comment by DavidStania** [comment]
I have tested it with the latest version. Exactly the same result.
I noticed that when I executed the `dotnet watch` command, the following message appeared: "`Skipping configuring browser-refresh middleware since the target framework version is not supported. For more information see 'https://aka.ms/dotnet/watch/unsupported-tfm'.`"
So I had to specify the command with the framework `dotnet watch --framework net8.0`. The browser is also reloaded. As can be seen in your video. But without any changes.

**Comment by Piedone** [comment]
Just to confirm, you did the same as I did, with the latest main, with the latest VS, and in contrast to the video, don't seem changes to a cshtml file appear?

**Comment by DavidStania** [comment]
I can confirm. 100% the same like you did.

https://github.com/user-attachments/assets/d6ce983a-d5bd-4370-b270-4caecba598c9

**Comment by Piedone** [comment]
Hmm. This looks like more of an issue with Razor Runtime Compilation rather than Hot Reload.

A couple of things:

1. Is [this line](https://github.com/OrchardCMS/OrchardCore/blob/1b4bb4441856a15485f90bdbaeae4a1a4b222875/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L107) hit for you?
2. What happens if you turn Hot Reload _off_ under Options -> Debugging -> General?

**Comment by DavidStania** [comment]
![image](https://github.com/user-attachments/assets/55be9a57-003e-4acd-8c54-346c4fa282ec)

This line is not hit cause 'refs' folder not exists! But I don't know why.

**Comment by Piedone** [comment]
Hmm. What happens if you turn Hot Reload off under Options -> Debugging -> General?

**Comment by DavidStania** [comment]
Strange!

Hot reload is disabled in global settings
![image](https://github.com/user-attachments/assets/8deeb98e-3dee-4e7f-ba2f-b5b53293e883)
And also in startprofile
![image](https://github.com/user-attachments/assets/ba110e65-926d-4698-bdc2-30a698f4f317)
But if changes exists:
![image](https://github.com/user-attachments/assets/3ddae380-199b-45b6-ba78-407f3f352753)

**Comment by Piedone** [comment]
I don't know what's happening.

**Comment by DavidStania** [comment]
I told you. Very strange! And this is happens on 4 independent development machines.

**Comment by shinexyt** [comment]
Same issue: #15946

**Comment by Piedone** [comment]
Indeed, closing as a duplicate.
