### ISSUE TITLE
Unable to enable/disable workflow task from the workflow editor

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16512]
### Describe the bug
When editing workflow, clicking on any event does not give you the power button where you can enable disable the event. The power button works for events but not for tasks.

### Orchard Core version
2.0.0-preview

Add the version of the Orchard Core NuGet packages you use, or the commit hash if you can reproduce this with the source code.

### To Reproduce
1. create a workflow
2. add task and try to enable it.

### Expected behavior
I should be able to enable/disable both task or event.

### Logs and screenshots

![image](https://github.com/user-attachments/assets/71d990da-dcd5-4571-86dd-e91816fe1acf)

![image](https://github.com/user-attachments/assets/4f0f4ddb-6d8a-4430-93d0-52e4a5b016ee)

**Comment by MikeAlhayek** [comment]
I think this PR is causing this issue

https://github.com/OrchardCMS/OrchardCore/pull/16351

**Comment by Piedone** [comment]
The button says "Startup task". How is that enabling/disabling a Task?

**Comment by MikeAlhayek** [comment]
maybe we need to re-name it to "Enable/Disable" instead

**Comment by MikeAlhayek** [comment]
Never mind. We discussed this in the meeting and it was just a long misunderstanding and old bug.

**Comment by Piedone** [comment]
I see. What's the bug?
