### ISSUE TITLE
Jalali date time in sitemap.xml

### ISSUE THREAD

**Issue by sayyad84** [OrchardCMS/OrchardCore#16520]
Describe the bug
Hi,
In the site map, instead of the Gregorian date, the solar calendar is displayed, which cannot be used in search engines. Our site is bilingual and its main language is Farsi (right to left).
Like:
https://t-one-net.com/fa-IR/%D8%AA%D9%85%D8%A7%D8%B3-%D8%A8%D8%A7-%D9%85%D8%A7 1401-07-04T09:39:34+00:00 daily 0.5
Orchard Core version
1.8.3

To Reproduce

Expected behavior
Show Gregorian datetime in sitemap.xml

**Comment by MikeAlhayek** [comment]
I think PR #15229 fixes this issue. This fix is part of OC 2.0.0 preview. Are you able to try it with the 2.0.0 previews?

**Comment by sayyad84** [comment]
I added the relevant module to the project along with the mentioned change and the problem was solved. 
Thank you.

**Comment by Piedone** [comment]
Great, thanks for the feedback.
