### ISSUE TITLE
CreateContentTask evaluation will not remove illegal characters

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#16542]
While upgrading to 2.0 i had a workflow with a CreateContentTask  activity to create a specific content type with following liquid expression : 

```


{% capture full_name %}
{{Workflow.Input.User.Properties.UserProfileSettings.UserProfileSettings.FirstName.Text}} {{Workflow.Input.User.Properties.UserProfileSettings.UserProfileSettings.LastName.Text}}
{% endcapture %}

{
  "DisplayText":  "{{full_name}}",
  "Owner":"{{Workflow.Input.User.UserId}}",
  "Author": "{{Workflow.Input.User.UserName}}",
 
}

```

when ContentProperties is evaluated from : 

```
   var contentProperties = await _expressionEvaluator.EvaluateAsync(ContentProperties, workflowContext, _javaScriptEncoder);
```
the json to be merged  is returned like this (with carriage return inside the json) : 

```

{
  "DisplayText":  "
qqqqqqqqfname qqqqqqqqlname
",
}
```
this results in the following error when merging with content item : 

```
System.Text.Json.JsonReaderException: '0x0D' (CARRIAGE RETURN) is invalid within a JSON string. The string should be correctly escaped.
```

This was handeled automatically before 2.0 . Is there a way to remove automatically invalid json characters like previous ?

**Comment by MikeAlhayek** [comment]
I think this is due to the extra trailing comma in your json.

**Comment by hishamco** [comment]
Is it matter?

**Comment by MikeAlhayek** [comment]
@giannik can you please try out this PR and see if that fixes your issue? https://github.com/OrchardCMS/OrchardCore/pull/16543

**Comment by sebastienros** [comment]
If the liquid is generated from a generic liquid task, then it doesn't know that the properties should be encoded in JSON.

What may happen in 2.0 is that the parser won't be as permissive as before (NewtonSoft.JSON) and will fail when it finds an invalid char.

The solution, which will also work with the previous version is to correctly encode the values using the `json` filter like so:
- use `| json` such that the properties are well-formed for json
- remove the trailing comma after Author
- exclude new lines in the capture using `-%`

```
{% capture full_name -%}
{{Workflow.Input.User.Properties.UserProfileSettings.UserProfileSettings.FirstName.Text}} {{Workflow.Input.User.Properties.UserProfileSettings.UserProfileSettings.LastName.Text}}
{%- endcapture %}

{
  "DisplayText":  "{{full_name | json}}",
  "Owner":"{{Workflow.Input.User.UserId | json}}",
  "Author": "{{Workflow.Input.User.UserName | json}}"
}
```

**Comment by sebastienros** [comment]
Feel free to re-open if you have more information that would invalidate the explanation

**Comment by giannik** [comment]
@sebastienros @MikeAlhayek   
thanks guys. 

adding  this to remove whitespaces from left and right fixes it : 


```
{%- capture full_name -%}
{{Workflow.Input.User.Properties.UserProfileSettings.UserProfileSettings.FirstName.Text}} {{Workflow.Input.User.Properties.UserProfileSettings.UserProfileSettings.LastName.Text}}
{%- endcapture %}
```

**Comment by sebastienros** [comment]
But you should also add the json filters. Try with a name containing a double quote. It could be a security issue otherwise
