### ISSUE TITLE
Sitemap format

### ISSUE THREAD

**Issue by sayyad84** [OrchardCMS/OrchardCore#16579]
Hi,
The sitemap generated by the software needs to be changed, especially for multilingual sites, and Google suggests the following format for it. I would be grateful if you would make the necessary changes in the software to produce a site map in this format:
https://developers.google.com/search/docs/specialty/international/localized-versions

**Comment by Piedone** [comment]
Please tell in detail what kind of changes the current sitemap generation logic should have in your opinion.

**Comment by sayyad84** [comment]
Something similar to Google's offer in link:
`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc>https://www.example.com/english/page.html</loc>
    <xhtml:link
               rel="alternate"
               hreflang="de"
               href="https://www.example.de/deutsch/page.html"/>
    <xhtml:link
               rel="alternate"
               hreflang="de-ch"
               href="https://www.example.de/schweiz-deutsch/page.html"/>
    <xhtml:link
               rel="alternate"
               hreflang="en"
               href="https://www.example.com/english/page.html"/>
  </url>
  <url>
    <loc>https://www.example.de/deutsch/page.html</loc>
    <xhtml:link
               rel="alternate"
               hreflang="de"
               href="https://www.example.de/deutsch/page.html"/>
    <xhtml:link
               rel="alternate"
               hreflang="de-ch"
               href="https://www.example.de/schweiz-deutsch/page.html"/>
    <xhtml:link
               rel="alternate"
               hreflang="en"
               href="https://www.example.com/english/page.html"/>
  </url>
  <url>
    <loc>https://www.example.de/schweiz-deutsch/page.html</loc>
    <xhtml:link
               rel="alternate"
               hreflang="de"
               href="https://www.example.de/deutsch/page.html"/>
    <xhtml:link
               rel="alternate"
               hreflang="de-ch"
               href="https://www.example.de/schweiz-deutsch/page.html"/>
    <xhtml:link
               rel="alternate"
               hreflang="en"
               href="https://www.example.com/english/page.html"/>
  </url>
</urlset>`

**Comment by gvkries** [comment]
That is already supported, you just need to enable the `OrchardCore.ContentLocalization.Sitemaps` feature.

**Comment by sayyad84** [comment]
There is a sitemap, but it is not the same as the one suggested by Google for multilingual sites.
![image](https://github.com/user-attachments/assets/7d550785-d001-4038-aa18-6f3068f95634)

**Comment by gvkries** [comment]
I don't know why, but the browser is just not formatting the XML document correctly. Look at the actual HTTP response, that looks correct.

**Comment by sayyad84** [comment]
But the sitemap is displayed correctly in other websites. Meanwhile, most of my emphasis in this request is for the multilingual section, where the URLs are inserted as follows:
<xhtml:link rel="alternate" hreflang="de" href="https://www.example.de/deutsch/page.html"/>

**Comment by gvkries** [comment]
That's correct on your site too:
![image](https://github.com/user-attachments/assets/d95c1f96-fb25-46e2-823e-e40bbb796b3e)
