### ISSUE TITLE
Check if  `OrchardCore.Layers.AdminController.Index(LayersIndexViewModel)` can be refactored

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#16570]
There is an argument in this method which might not be necessary.

Description in this comment:
https://github.com/OrchardCMS/OrchardCore/pull/16567#discussion_r1718451707

**Comment by sebastienros** [comment]
Might even be able to remove the whole action.

**Comment by MikeAlhayek** [comment]
Yes I don't think the Post Action method is needed. It should be removed. and if you think it could break someone, we should remove it before releasing 2.0 otherwise we would have to wait for 3.0
