### ISSUE TITLE
Breaking shape name resolution regarding menu shape

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#16585]
### Describe the bug

I found this undocumented breaking change regarding the "menu" shape (potentially all non PascalCase shapes).

### Orchard Core version

Latest `main`.

### To Reproduce

1. Set up an OC 2.0 site with any recipe that creates a `main-menu` content item (e.g. Blog).
2. Create a content type with a Liquid part.
3. Create a content item with the Liquid content `{% shape "menu", alias: "alias:main-menu" %}`
4. Go to Admin > Design > Templates.
5. Create a template called "Menu" with any content.
6. Display the content item, observe that the shape is not overridden.
7. Delete the "Menu" template and create a "menu" template instead.
8. Display the content item again, observe that the shape is successfully overridden.
9. Now do the same again in OC 1.8, observe that in 1.8 the menu shape is overridden by the "menu" template but not the "Menu" template, in other words it's the opposite.

| override works | menu | Menu |
|--------|------|------|
| OC 1.8 | ❌    | ✅    |
| OC 2.0 | ✅    | ❌    |

Additional note: btw you can't create `menu` and `Menu` templates at the same time in Admin > Design > Templates. You have to delete one first to create the other. Is this intentional? Seems like the template creation is checked case-insensitively, but the template evaluation is case-sensitive.

### Expected behavior

Either "Menu" template override should keep working. It would be even better if both "Menu" and "menu" worked. Maybe it should first try the shape type case sensitively and if it's not found then case insensitively? (that's what I do with media library themes in Lombiq.Hosting.MediaTheme [here](https://github.com/Lombiq/Hosting-Media-Theme/blob/7fb210ebb07516a61fbf4d4f3b110b33436ed6a6/Lombiq.Hosting.MediaTheme.Bridge/Services/MediaThemeManager.cs#L84-L95))

If that's not possible, then please document the breaking change in the [2.0.0.md](https://github.com/OrchardCMS/OrchardCore/blob/3fe9612adb08b03114177a485ecc02e52091030c/src/docs/releases/2.0.0.md?plain=1) release notes.

**Comment by sebastienros** [comment]
I personally would suggest it should work with all cases. That would also fix the breaking change.
If the solution is to be case sensitive then the solution would be to use the same case as the content type, which would also fix the breaking change.

**Comment by sebastienros** [comment]
@sarahelsaig Looked at the linked PR and it seems that the issue is only for admin templates? That would reduce considerably the scope of the problem and help find out when it changed. That could also mean that it's store dependent: Linux vs Windows vs blob storage vs database.

**Comment by sarahelsaig** [comment]
I agree, the problem is only for admin templates. I did some testing, and it looks like file templates in the Views folder (both cshtml and liquid) are resolved case-insensitively. Even on Linux, so that side is not filesystem dependent.

So I think it would be best if the admin templates get resolved case-insensitively as well. For consistency.

**Comment by sebastienros** [comment]
I am surprised that admin templates are based on the filesystem, I thought we were storing them in database by default ... Or are they in a single "document" in the database and then it's not an issue with the filesystem but the way we search for them.

**Comment by sarahelsaig** [comment]
I've investigated further and `TemplatesDocument.Templates` [is already](https://github.com/OrchardCMS/OrchardCore/blob/4395dbb793cc166c3179049fc01d3121c603cf72/src/OrchardCore.Modules/OrchardCore.Templates/Models/TemplatesDocument.cs#L7) `StringComparer.OrdinalIgnoreCase`. But somehow this is not respected and the default generic comparer is used instead:
![image](https://github.com/user-attachments/assets/1e8349f2-fd92-49ec-903e-17b2b1922bcd)

This is a problem when a model contains a dictionary with a setter, because STJ just creates a new dictionary with the default comparer instead of updating the existing setter with the provided values.
