### ISSUE TITLE
When creating a template for a content type, part or field, the template name should be automatically suggested

### ISSUE THREAD

**Issue by AndreaPiovanelli** [OrchardCMS/OrchardCore#16605]
When I add, via back office, a new template for the (e.g.) summary of a content type, if there is no template the template edit page is completely empty. 
![image](https://github.com/user-attachments/assets/90937a67-993b-4361-bd18-23bb5fdd5362)

It would be very useful providing the default template name field automatically, based on the previous selection:
![image](https://github.com/user-attachments/assets/9a837ae1-08ba-4117-ba95-7d42ec20af0e)
This would help unexperienced users a lot to begin to understand the naming of templates and shapes.

**Comment by hishamco** [comment]
I think it's a good addition, Do you plan to submit a PR for it?

**Comment by microposmp** [comment]
Hi, a fix for this was made in #15145. The name is prefilled in the main branch and will be included in the next release.

**Comment by AndreaPiovanelli** [comment]
> Hi, a fix for this was made in #15145. The name is prefilled in the main branch and will be included in the next release.

Thank you very much for the information.
