### ISSUE TITLE
Ability to remove OpenID Redirect Uri Validation

### ISSUE THREAD

**Issue by kdudley21** [OrchardCMS/OrchardCore#16608]
Right now the OpenId/Applications Edit/New page (Admin/OpenId/Application/Edit/) check to make sure that the redirect uris are valid uris and if they arent valid it removes them

Is there a way to make it so it doesnt validate the uri ? I would like to use wildcards so for example https://127.*.0.1/signin-oidc and it isnt saving these uris.

**Comment by hishamco** [comment]
I will close this while you already opened a discussion [here](https://github.com/OrchardCMS/OrchardCore/discussions/16609)

**Comment by kdudley21** [comment]
Thanks !
