### ISSUE TITLE
OrchardCoreBuilderExtensions Exception "Missing Method YesSql.IStore.CreateSession()" after YesSql Update

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#16604]
OC Version: 1.8.3

Lucene Indexes didn't work anymore after the update to 1.8.3, because they were correctly built, but didn't show any result in Content Picker Fields.
Log Error:
`Unable to resolve service for type 'OrchardCore.Search.Elasticsearch.Core.Services.ElasticIndexManager' while attempting to activate 'OrchardCore.Search.Elasticsearch.Core.Providers.ElasticContentPickerResultProvider'.`

So i was thinking, i just try to update some Nuget Packages and maybe it works afterwards.
I updated YesSql from **5.0.0-beta-0001** to **5.1.1**, but now i get this Exception when starting OC:
`MissingMethodException: Method not found: 'YesSql.ISession YesSql.IStore.CreateSession()'.`

I'm pretty sure it's caused here:
[https://github.com/OrchardCMS/OrchardCore/blob/d14d6510304686ed070cd95e4d68410c255eed2e/src/OrchardCore/OrchardCore.Data.YesSql/OrchardCoreBuilderExtensions.cs#L149](url)

If i go back to **5.0.0-beta-0001** OC works fine, except the Lucene Indexes of course.

**Comment by Piedone** [comment]
You shouldn't update YesSql, since that may clash with the version OC uses, as you've observed.

Now for the indexing error: You say Lucene doesn't work, but the exception is about Elasticsearch. What happens if you disable all the Elasticsearch features?

**Comment by Flarescape** [comment]
@Piedone Thanks for that information, i thought that i can always update YesSql with OC to the newest version.
Funny thing is, that the "Missing Method" is still in the same place, same file, same namespace from what i saw last time i checked.

For Lucene: I deactivated Elasticsearch and now Lucene works again.
The thing is, that neither Content Picker Fields (based on Lucene as source) nor the Content Definitions view work, when Elasticsearch and Lucene are activated.
So maybe a thing to look into.
If i can provide any further information, feel free to contact me.
