### ISSUE TITLE
New invalid HTML warning in general settings when using the latest Chrome

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#16606]
### Describe the bug

In the latest version of Chrome, visiting ~/Admin/Settings/general raises the following warnings in the browser console:
```
[Warning] https://localhost:9067/Admin/Settings/general 2168 A em tag was parsed inside of a <select> which was not inserted into the document. This is not valid HTML and the behavior may be changed in future versions of chrome.
[Warning] https://localhost:9067/Admin/Settings/general 2182 A em tag was parsed inside of a <select> which was not inserted into the document. This is not valid HTML and the behavior may be changed in future versions of chrome.
```

### To Reproduce
1. Update to Chrome v128
2. Go to Admin > Configuration > Settings > General
3. Press F12 and switch to the Console tab.
4. Observer the warnings mentioned above.

Note: the same warnings don't show up in Chrome v127.

### Expected behavior

Valid HTML.

### Logs and screenshots

![image](https://github.com/user-attachments/assets/a081e609-d30d-4ad1-853f-25c282c13d00)

**Comment by gvkries** [comment]
Yes, that is invalid HTML and ignored. It is defined in a localization string:

https://github.com/OrchardCMS/OrchardCore/blob/d14d6510304686ed070cd95e4d68410c255eed2e/src/OrchardCore.Modules/OrchardCore.Settings/Views/Settings-Resources.Edit.cshtml#L32
