### ISSUE TITLE
UserTimeZoneService needs an interface

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#16613]
annoying to mock

`UserTimeZoneService`

**Comment by sebastienros** [comment]
What exactly do you need to mock in your tests?
I would have assumed that only `ITimeZoneSelector` would be useful to change, because only `UserTimeZoneDisplayDriver` is using `UserTimeZoneService`.

**Comment by deanmarcussen** [comment]
and yet we extend orchard core way past what is in the orchard core repository :)

which means we use `UserTimeZoneService` in many more places than just the `UserTimeZoneDisplayDriver`

Is that a good thing or not? I don't know, but its easier to use the orchard core services that are available, than copying hte code into our repository

**Comment by sebastienros** [comment]
Does Moq support mocking this class? Methods are not overridable so probably no possible?

Adding an interface to a public service would mean that we'll add interface to any public service when someone asks for it. We should have made this type internal if we thought it would not be used externally (and mocked). If mocking works, even if that's not easy, I would not add an interface.

Another point of view is that we may actually want it to be public if someone wants to create a feature enhances/uses this feature. In that case we could add the interface.

**Comment by hishamco** [comment]
I will try to write a unit test mocking this service
