### ISSUE TITLE
Injecting CMS Parameters on Startup

### ISSUE THREAD

**Issue by pnda489** [OrchardCMS/OrchardCore#1661]
Hi,

i want to skip the initialization Part and directly inject all the Parameters like SQL String, Password an so on by Code or by a configuration File.
The purpose is to use a Buildscript that directly builds for the right Tenant and uses the specific SQL String and so on.

I found that there are some Modules like "Setup", "Environment.Shell", "ShellSettings" which seems to define this process. Still I couldn't figure out how to intercept the process and maybe inject into the middleware or directly provide the File or Context to the CMS.

Is there already a built in option? How could I archive my goal?

I don't want to use built in multi tenancy.
Just to be clear:
 **Starting a new Orchard CMS and inject all the Parameters needed into the CMS by Code or Configuration.**

Thanks
Michael

**Comment by Skrypt** [comment]
Isn't that already the **Recipe** feature?

**Comment by sebastienros** [comment]
Orchard can be run in command line too, and custom commands can be defined in modules. Look for classes implementing `ICommandHandler`. There is a Recipe one, which is listing all recipes. I suggest you try to create a Setup command in the Setup module and use it in your scripts. Please create a PR so we can include it too.

@Jetski5822 might help on how to run them, he implemented the feature

**Comment by pnda489** [comment]
Thanks for your fast replies.

@Skrypt Which Service do you mean and how to use it directly in startup.cs ? I get many errors and null references trying to mock the services to use the setup by code.

@sebastienros I am not sure if I understand your answer the right way. Let me first sum up your answer:
Implementing own Command in Setup Module , now we can use all the Interface cause we are in the right Context and then u said "_use it in your scripts_" how? By command line? **Is there an example on how to use it with command line and injecting parameters?**

Our current way to go is to copy the database from a deployed CMS to a new one and copy a new settings.txt into the CMS with the new (correct) SQL connection string.

_By the way, why is settings.txt a *.txt file and not *.json ?_

I would like to add a Command which inits a CMS by code but for me it is hard to guess which services i need. **Is it enough to nearly copy the SetupService.cs and to use it as a Command where I can inject parameters by command line?** Should it inherit from "DefaultCommand" ?

**Comment by infofromca** [comment]
another similar case:
options.AddPolicy("AllowSpecificOrigins",
builder =>
{
    builder.WithOrigins("http://example.com", "http://www.contoso.com");
});

need inject  "http://example.com", "http://www.contoso.com"..........

**Comment by sebastienros** [comment]
TODO: Create site setup commands. Extract some of the logic from the Setup module to reuse in a command.

**Comment by sebastienros** [comment]
@infofromca this is a different concern, you can do it already from your host application, by doing `AddOrchardCore().ConfigureServices(services => { ... } )`

**Comment by infofromca** [comment]
@sebastienros 
by doing AddOrchardCore().ConfigureServices(services => { ... } )
can I inject "http://example.com", "http://www.contoso.com" for tenant 1
and inject "http://xyz.com" for tenant2
in the same host app.

**Comment by infofromca** [comment]
I can use
RegisterTenantServices
or services.ConfigureTenantServices
I think

**Comment by infofromca** [comment]
but for my tenant10000, I do not know its  target site "http://xyz10000.com" name before coding on
RegisterTenantServices
or services.ConfigureTenantServices

**Comment by infofromca** [comment]
ok, in my case, I should create a class like
public class MyConfiguration : IConfigureOptions<myOptions>

**Comment by sebastienros** [comment]
We have a REST api to setup tenants. Optionally you can create modules that create tenants.
