### ISSUE TITLE
Firefox Edge show sliding animations on first load of most admin pages

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1664]
Hi,
Open Firefox, go to admin.
Navigate to any of the "New" pages.
The page loads with an sliding animation. 
This occurs on Edge too. And occurs on many other pages of the admin.
And not sure if it is related, but I tried on IE11 and it was even unable to load many pages.  For example, I tried with the Agency theme. Navigated to New:Page, and the page does not load. It warns about a long running script causing an issue.

**Comment by Skrypt** [comment]
This is a CSS transition, I'm surprised that it's causing this effect.

**Comment by matiasmolleja** [comment]
I just quickly tried this : 
https://css-tricks.com/transitions-only-after-page-load/
And it seems to work.

**Comment by Skrypt** [comment]
Did the same here quickly. It seems that Firefox and Edge are executing animations on page load. Though Chrome doesn't.

**Comment by Skrypt** [comment]
Also noticed on Firefox that some pages are getting scrolled down from the start.

**Comment by matiasmolleja** [comment]
I can add the fix on the previous link to the PR I'm preparing with the minimizable sidebar?
Can you tell me one of the pages with the scrolling down issue ? Just to confirm it is the same thing I see.

**Comment by Skrypt** [comment]
Content Types, Content Parts pages. But strangely only on Firefox Mac.
