### ISSUE TITLE
Use value task in INavigationProvider

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16646]
Currently, the navigation provider returns a `Task`.

```
public interface INavigationProvider
{
    Task BuildNavigationAsync(string name, NavigationBuilder builder);
}
```

In most implementations we do not need a task. I suggest changing that to return `ValueTask` instead. `INavigationProvider` is evaluated on every request and we could benefit from this optimization.

**Comment by Piedone** [comment]
Agree.
