### ISSUE TITLE
Setup page throws error on bad user-name, despite creating db tables

### ISSUE THREAD

**Issue by MikaelElkiaer** [OrchardCMS/OrchardCore#1665]
Using the latest Docker image for linux, I am experiencing an error when filling out the setup page.
I entered the username: 'MikaelElkiær' and upon submit it spent some time creating the tables, and then it comes back with an error: 'User name is requried'. Re-opening the page will confirm that everything was created successfully though, so the error is false.

**Update:** When trying to sign in with the user 'MikaelElkiær' I am met with 'Invalid login attempt'.

**Update:** Same is true for user-name with space(s), e.g. 'Mikael Elkiaer'.

**Comment by Skrypt** [comment]
Try cleaning your cookies and let me know if it fixed the issue.

**Comment by sebastienros** [comment]
TODO: We need to try and repro this

**Comment by sebastienros** [comment]
I can still repro. In the admin when trying to create a new user it fails at server-side validation, I assume from aspnet identity. We should do the same validation on javascript and on the server at least to prevent getting into a bad state.

**Comment by hishamco** [comment]
I will try to do the validation on both client & server, but I think we need to support Unicode characters in username after 1.0.0 at least

**Comment by hishamco** [comment]
![Setup](https://user-images.githubusercontent.com/3237266/64666195-0b1d6180-d45e-11e9-8302-d06a3d84baff.png)

This is a related issue when the validation is show up, I see the pre-filled configuration fields are show up which is totally wrong

**Comment by hishamco** [comment]
I fixed the issue that mentioned above, nothing but I don't think the client-side validation is a good idea, what we should do is to force `TenantState` to be `Uninitialized` if a validation error occurs

/cc @jtkech

**Comment by jtkech** [comment]
Normally, this is what we do in `SetupAsync`.

                if (context.Errors.Any())
                {
                    context.ShellSettings.State = initialState;
                }

Also, just saw in the setup controller

            if (!ModelState.IsValid)
            {
                CopyShellSettingsValues(model);
                return View(model);
            }

Need to be tried but maybe we could just do

            if (!ModelState.IsValid)
            {
                return View(model);
            }

So that the user could retrieve the form fields that have been filled.

Otherwise here, as @sebastienros said, it seems that there are some missing checks on the user name that we would need to do before attempting to run the setup recipe.

**Comment by jtkech** [comment]
For infos, in aspnetcore identity i saw this options class

    public class UserOptions
    {
        /// <summary>
        /// Gets or sets the list of allowed characters in the username used to validate user names. Defaults to abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+
        /// </summary>
        /// <value>
        /// The list of allowed characters in the username used to validate user names.
        /// </value>
        public string AllowedUserNameCharacters { get; set; } = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";

        /// <summary>
        /// Gets or sets a flag indicating whether the application requires unique emails for its users. Defaults to false.
        /// </summary>
        /// <value>
        /// True if the application requires each user to have their own, unique email, otherwise false.
        /// </value>
        public bool RequireUniqueEmail { get; set; }
    }


There is also an `IUserValidator<TUser>` that maybe we could use.

    public interface IUserValidator<TUser> where TUser : class
    {
        /// <summary>
        /// Validates the specified <paramref name="user"/> as an asynchronous operation.
        /// </summary>
        /// <param name="manager">The <see cref="UserManager{TUser}"/> that can be used to retrieve user properties.</param>
        /// <param name="user">The user to validate.</param>
        /// <returns>The <see cref="Task"/> that represents the asynchronous operation, containing the <see cref="IdentityResult"/> of the validation operation.</returns>
        Task<IdentityResult> ValidateAsync(UserManager<TUser> manager, TUser user);
    }

Or mimic it if no `TUser` is available on setup.

**Comment by hishamco** [comment]
@MikaelElkiaer this can be fixed by adding `ae` into `UserOptions.AllowedUserNameCharacters`, for now we ca validate username before the recipe run
