### ISSUE TITLE
Razor Pages documentation / example project

### ISSUE THREAD

**Issue by Healios** [OrchardCMS/OrchardCore#1666]
I've been trying to setup a modular Razor Pages application, but I just can't get it to work while following the approach showcased by Sébastien Ros in the following [video](https://www.youtube.com/watch?v=LoPlECp31Oo) (I realize the video is a year old and also for the MVC application template).

I found the following project, [Advanced Example Project](https://github.com/reyze/Orchard-Core-Modules), but it uses an MVC application template instead of the Razor Pages template, and I've also not been able to replicate the project setup to successfully access a page stored in a module.

Could anyone provide an example project or add documentation for OrchardCore's Razor Pages functionality?

**Comment by sebastienros** [comment]
Here is a module with Razor Pages, https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Demo/Pages

**Comment by JoshTango** [comment]
@Skrypt module link doesn't work anymore.
