### ISSUE TITLE
Refactor Culture and supported_cultures

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#16675]
In this PR https://github.com/OrchardCMS/OrchardCore/pull/16208

1. `Culture` was introduced to represent the selected culture for the context. We should just be able to return a new ObjectValue with the current culture in it and not have to proxy every property since `CultureInfo` is already registered.
1. `supported_cultures` should not be a filter, because it's not using the `input`. We could pass anything to it and it would still work. I suggest we register a FluidValue like `SupportedCultures` so we can write `for cultures in SupportedCultures`.
1. We should find a better way or improve Fluid to be able to register values and resolve its properties with lambdas. Instead of creating a `XXXFluidAccessor` then register it, like `Environment`, `Culture`, ...

**Comment by sebastienros** [comment]
@hishamco Wondering if it would make sense to expose `SupportedCultures` like `Culture.SupportedCultures` instead. Would it feel more natural to have it under a common thing.

And another comment about something that might not work with the recent PR we merged, we should be able to pipeline `SupportedCultures` (in any form we decide to expose it) with the properties on a `CultureInfo` like `Name`, `Dir`, ... So we need to add a converter from `CultureInfo` to `CultureValue`, but one that saves its culture as a state, so what you had done initially ...

**Comment by hishamco** [comment]
> @hishamco Wondering if it would make sense to expose SupportedCultures like Culture.SupportedCultures instead. Would it feel more natural to have it under a common thing.

Could be

> So we need to add a converter from CultureInfo to CultureValue, but one that saves its culture as a state, so what you had done initially ...

Let me start a new PR and ping you then

**Comment by hishamco** [comment]
> So we need to add a converter from CultureInfo to CultureValue

@sebastienros I'm not sure if it's doable now after you removed the `CultureInfo` from the `CultureValue` constructor

**Comment by sebastienros** [comment]
Almost done on my side

**Comment by hishamco** [comment]
I will wait for your PR, coz I already working on a new branch :) I will save the time and wait until you push your PR
