### ISSUE TITLE
Blazor sample

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#16686]
About https://docs.orchardcore.net/en/latest/guides/create-blazor-cms/

The last sentence is:
The source code for this guide is available at [github.com/OrchardCMS/OrchardCore.Samples](https://github.com/OrchardCMS/OrchardCore.Samples)

but the sample is not merged yet, it is stils a pull request:
https://github.com/OrchardCMS/OrchardCore.Samples/pull/45

**Comment by Piedone** [comment]
What's really to do here? The PR needs to be finished and merged I think, but nothing else that we need to do separately.
