### ISSUE TITLE
Lucene query throws ArgumentException while having taxonomy field

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#16691]
### Describe the bug

Lucene query throwed the ArgumentException while having toxonomy field

OrchardCore throwed the ArgumentException: "Can not add property ArticleItemForPublic.Category.Inherited to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object" when it executed  lucene query that include taxonomy field index.

### Orchard Core version
1.8.4 and 1.8.3

![image](https://github.com/user-attachments/assets/f2bdf2dc-a1ed-4a70-ad3e-9817e2242b51)

**Comment by hishamco** [comment]
Please steps to reproduce

**Comment by MikeAlhayek** [comment]
@effapp I am guessing you are using the latest preview. Correct?

Please share the code for your `ContentQueryAsync` extension, and also the Widget-ContentFeedByTaxonomy.cshtml code. 


I am guessing in your `entity.Add("key", obj)` instead of `entity["key"] = obj` which is causing the exception. I just want to be sure it is not OC code that is causing this issue.

**Comment by effapp** [comment]
Hi @MikeAlhayek ,

I am using release 1.8.4 of OC. 

It can execute correctly while replacing  from  lucene index and query to ElasticSearch index and query.

A pieces of code as follows:

var queryParams = new Dictionary<string, object>() { { "size", fetchCount }, { "from", from } };    
if (!string.IsNullOrEmpty(categoryId))
{
    queryParams["CategoryId"] = categoryId;  // the error is same while using queryParams.Add("CategoryId",  categoryId);
}    
string query = (string)Model.ContentItem.Content.ContentFeedByTaxonomy.Items.Value;
var items = await Orchard.ContentQueryAsync(query, queryParams);

**Comment by MikeAlhayek** [comment]
@effapp 

> queryParams["CategoryId"] = categoryId;

There this isn't the line that is causing the exception. Are
You able to reproduce this using OC branch? I would start there so you can understand the cause of the issue.

Another thing to try, is to try upgrading to OC 2.0 preview and see if you encounter the same issue. In 2.0 Newtonsoft.Json was removed from OC and YesSql.

**Comment by effapp** [comment]
> @effapp
> 
> > queryParams["CategoryId"] = categoryId;
> 
> There this isn't the line that is causing the exception. Are You able to reproduce this using OC branch? I would start there so you can understand the cause of the issue.
> 
> Another thing to try, is to try upgrading to OC 2.0 preview and see if you encounter the same issue. In 2.0 Newtonsoft.Json was removed from OC and YesSql.

But there is not the issue in index and query of ElasticSearch, still using Newtonsoft.Json.

**Comment by effapp** [comment]
The lucene query can execute correctly in admin UI  but throw exception by calling code : "var items = await Orchard.ContentQueryAsync(query, queryParams);"

the code "var items = await Orchard.ContentQueryAsync(query, queryParams);" is correctly in elasticsearch query.

**Comment by effapp** [comment]
The cause of issue has been identified: deleting "filter:[]" is normal.
