### ISSUE TITLE
media.scss is importing all boostrap.scss

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1671]
Hi,
It does that in order to extend a few bootstrap classes.
It increases file of the generated media.css. 
But the real issue is that depending of the order in wich the css files are loaded by the admin, sometimes the boostrap part of media.css overrrides some rules set by other css files.
One example of that was the #1511 issue.  The bootstrap rules included in media.css were overriding the way the expand-collapse buttons had to work, expressed in flows.edit.css,

One way to solve that could be removing the "@import full bootstrap" line, and explicitly include only the rules from bootstrap that we want to override. That would be easy.

Unless there is some trick in the processing pipeline that I don't know about, that enables extending bootstrap's classes on a module without importing the full library in the resulting css file.

What do you think?

**Comment by Skrypt** [comment]
We could also move the media.scss directly into the admin theme as a SASS module. Since we are talking about admin side of things it's less important but normally we should try to have only 1 resulting css file instead of one for each module. Maybe there is something that we could do to import the SASS files inside modules to be included into the admin themes using a gulp task.

**Comment by matiasmolleja** [comment]
I've found a similar issue on the admin theme project itself.
Filed a different issue : #1674

**Comment by agriffard** [comment]
@matiasmolleja  Is this issue solved and can be closed?

**Comment by matiasmolleja** [comment]
HI, 
Not yet on media. Only on TheAdmin. Media  is still importing the full bootstrap css. I want to add the fix to the changes I'm doing on the media module.

**Comment by matiasmolleja** [comment]
@sebastienros  Just to know if I'm going to break something.
In media.scss you use "@extend .row" , "@extend .col-md-9" etc...
Is there any special reason to do that? Doing like this requires importing the full bootstrap.scss into the media file, and is causing the issue of including boostrap twice.
Can we simply remove the "extend" lines and  then in the markup, use the corresponding  class="row, "class="col-md-9",  class="card",  etc...

**Comment by matiasmolleja** [comment]
I think that the lines where there when you first added the media module:
https://github.com/OrchardCMS/OrchardCore/commit/bf772afee00246d762b71624ddf1092b46af11b7

**Comment by Skrypt** [comment]
The only way I see that we could still use @extend and not @import the whole Bootstrap would be to make this media.scss a module of the TheAdmin theme main Sass file.

**Comment by Skrypt** [comment]
I agree with the easy fix. The other option is more complex but something we should look into later.
