### ISSUE TITLE
Orchard System information module

### ISSUE THREAD

**Issue by brunoAltinet** [OrchardCMS/OrchardCore#16726]
### Is your feature request related to a problem? Please describe.
After updating my Orchard, i wanted to see if all the migrations have been executed, but i don't know how to do that.

### Describe the solution you'd like
It would be great if we had some sort of "System information" page where we could see all the latest migration "numbers" for every module, what modules are enabled, etc. Just a huge raw text file that is easy to search and review for admin's eyes only.

### Describe alternatives you've considered
I would have to query that info from the database i think?

**Comment by agriffard** [comment]
@hisham made a System information module:
https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.System/README.md

**Comment by agriffard** [comment]
The migrations are in the `Document` table.
You will find the latest version of each migration in the one with the type `OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data`

**Comment by brunoAltinet** [comment]
This is awesome and essential. Any chance this gets pulled into main with aforementioned feature updates?

**Comment by agriffard** [comment]
I guess @hishamco wants to keep his module on [https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules](https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.System/README.md)

The second one would be another module.

**Comment by agriffard** [comment]
Now that you know where the migrations are, you can check the table.
I understand that you would like to have it displayed in the admin, but in the case of a developer that has access to the database (99% of the time, I guess), that is what you would do directly.

**Comment by hishamco** [comment]
It seems I'm too late to reply due to the time-zone difference :) thanks @agriffard for pointing to the repo, @brunoAltinet if you have any enhancements to OCC System Info feel free to file an issue in the [OCC.Modules repo](https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.System/README.md)

**Comment by brunoAltinet** [comment]
Will do. The info inside the database is too obscure, it's a long string that needs to get parsed  or dumped somewhere, and it's essential for debugging any orchard site. @hishamco's idea is great and on the right track, i'll expand on it.
