### ISSUE TITLE
ContainedPartIndex fails when DisplayText over 255 chars long

### ISSUE THREAD

**Issue by XopcT** [OrchardCMS/OrchardCore#16739]
Hi! There's a bug in ContainedPartIndex. It fails when you try to add an item with very long DisplayText (over 255 chars) to the component's list. It happens as ContainedPartIndex.DisplayText column has maximum length of 255 chars but provider does not truncate lengs of display text

### To Reproduce
1. Create an item with List part
2. Try to create item in the list with title longer than 255 chars

### Expected behavior
Item is created

### Actual behavior
Item is not created

**Comment by XopcT** [comment]
Fixed by this PR: https://github.com/OrchardCMS/OrchardCore/pull/16738

**Comment by Piedone** [comment]
Next time, please connect the PR to the issue with `Fixes #16739` in its description, so it'll be auto-closed and show links on both ends.
