### ISSUE TITLE
AssignRoleToUsers should not be implied by EditUsers

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16756]
In the permission structure we currently have. The `AssignRoleToUsers` permission should NOT be implied by `EditUser`. `AssignRoleToUsers` should be explicitly granted instead.

Change

https://github.com/OrchardCMS/OrchardCore/blob/dd03cf8c998b014303728e20b398239e49ff3dc8/src/OrchardCore/OrchardCore.Users.Core/CommonPermissions.cs#L24

to 

```
    public static readonly Permission AssignRoleToUsers = new("AssignRoleToUsers", "Assign any role to users", true);
```

**Comment by sebastienros** [comment]
I agree with the issue description.

However I think it may be fine as a non-breaking change. Kind of a fix. Would the fix also add the permission by default to the roles that have Edit Users?

**Comment by MikeAlhayek** [comment]
If we provide a migration to grant the permission for all the roles, then we won't break anything. But we would have to make sure that migration does run for new tenants.
