### ISSUE TITLE
ILocalClock.LocalNowAsync causes a VSTHRD003 code analysis warning

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#16751]
### Describe the bug
Calls to `ILocalClock.LocalNowAsync` [causes a VSTHRD003 code analysis warning.](https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD003.md)

> Avoid awaiting or returning a Task representing work that was not started within your context as that can lead to deadlocks.

### Orchard Core version
Orchard Core 1.8.2

### To Reproduce
1. Add a package reference to `Microsoft.VisualStudio.Threading.Analyzers` version 17.11.20
2. Call `ILocalClock.LocalNowAsync`

### Expected behavior
No code analysis warning is thrown.

I'm not super knowledgeable in this area but I suspect the issue is because the `LocalNowAsync` property isn't actually `async`. As far as I know async properties are not a thing in C#. Making this an `async` method would probably resolve the issue. Either that or this is a false positive, but I don't know enough to say.

The implementation of the property simply calls the private `GetLocalNowAsync` method. Presumably if that method was made public I could call it instead and avoid the warning.

**Comment by Piedone** [comment]
This looks just like a mistaken design decision. We shouldn't really have properties returning `Task`s.

**Comment by hishamco** [comment]
Right, as I said in the related PR this is the first time I saw async property!! I'm not sure if there's reason for that
