### ISSUE TITLE
Add Unit Test for RedisCacheWrapper shouldn't implement IDisposable 

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#16761]
Watch the last Orchard Core meeting and see @sebastienros comment about this

Related to #16720

**Comment by AhmadMahmoodRana** [comment]
download
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by hishamco** [comment]
@Piedone this is not my first issue :) or this is the first time I added an issue after your setup the workflow

**Comment by Piedone** [comment]
I guess this will happen just this last time. Please link to the timestamp where this is discussed: https://www.youtube.com/watch?v=tH-NtcKxZU4 And/or elaborate.

**Comment by hishamco** [comment]
42:00
