### ISSUE TITLE
Timezone error after upgrade to 2.0

### ISSUE THREAD

**Issue by emrahtokalak** [OrchardCMS/OrchardCore#16776]
### Describe the bug

After upgrading my 1.8.3 project to 2.0, I am getting an error that I think is caused by the "OrchardCore.Users.TimeZone" module. Each user's setting is "local time zone" and the application's global time zone setting is "GMT+3".

These settings, which worked fine in 1.8.3, are causing me to get errors on the content items page and at many points where the "GetLocalTimeZoneAsync" method is called.

### Orchard Core version

2.0

### To Reproduce

- Upgrade your project from 1.8.3 to 2.0.

- Set your users in your project to the default timezone option.

- Activate the "OrchardCore.Users.TimeZone" module.

- You will see that many mechanisms, especially content items, do not work correctly.

### Logs and screenshots

<img width="1302" alt="Screenshot 2024-09-21 at 00 02 48" src="https://github.com/user-attachments/assets/de673ab2-192a-4f6f-a37a-c376960a0b7b">

<img width="958" alt="Screenshot 2024-09-21 at 00 08 24" src="https://github.com/user-attachments/assets/cdad697d-9960-4146-be7d-4763c282883f">

While timezone is active, I cannot call a SQL query with the "api/queries" endpoint, it throws an error caused by timezone.

<img width="1298" alt="Screenshot 2024-09-21 at 00 16 45" src="https://github.com/user-attachments/assets/9862d396-b938-461d-831c-4177b60236bd">

**Comment by Piedone** [comment]
I can see the issue. It's because we get an NRE here:

![{101D0C80-DE93-477C-AAF6-38BE3D85AB75}](https://github.com/user-attachments/assets/f03c6339-7556-4b48-bf84-ac02a817384a)

This is only when the user's time zone is set as "Use site's time zone":

![{5B102FEE-BA17-4147-A5CC-6D2B636A3D77}](https://github.com/user-attachments/assets/5c0a7754-f616-401a-b6f2-16782446bae5)

**Comment by Piedone** [comment]
This is a regression, so we need to fix it for 2.1.0 at least, perhaps also release it as a 2.1.1.

**Comment by Piedone** [comment]
This isn't just for an ugpraded site, BTW, even a vanilla 2.0 site has this issue.

BTW a workaround you can use for now is to either set the time zone of the affected users to something else than the site's, or to disable `OrchardCore.Users.TimeZone` altogether for now.

**Comment by emrahtokalak** [comment]
> This isn't just for an ugpraded site, BTW, even a vanilla 2.0 site has this issue.
> 
> BTW a workaround you can use for now is to either set the time zone of the affected users to something else than the site's, or to disable `OrchardCore.Users.TimeZone` altogether for now.

Yes, I later realized that there was a problem with the vanilla installation too.

**Comment by MikeAlhayek** [comment]
I think @Piedone meant to fix this and release 2.0.1 not 2.1.1.

**Comment by Piedone** [comment]
Yep!
