### ISSUE TITLE
 Lucene Query search result limited 10 records

### ISSUE THREAD

**Issue by gaojianzhuang** [OrchardCMS/OrchardCore#16779]
### Describe the bug
In the Lucene Query, if I run the match all and the result only displays 10 records the actual results count is 21.

![image](https://github.com/user-attachments/assets/7c3900b2-879b-4eb3-ac3e-d6b10d69001d)

### Orchard Core version
1.8.4
![image](https://github.com/user-attachments/assets/06129627-c1d8-414d-ad1f-e74c6892d302)

Add the version of the Orchard Core NuGet packages you use, or the commit hash if you can reproduce this with the source code.

### To Reproduce
1. Go to 'Admin/Search/Lucene Indices'
2. Click on 'Query' and click the "Match All query"
3. Go to the search result and ensure the contents exceed 10 records.

### Logs and screenshots
If applicable, add log files, browser console logs, and screenshots (or screen recording videos) to help explain your problem.

**Comment by Piedone** [comment]
10 is the default. You need to specify the `size` (and potentially `from` and `sort`) parameter in the query for a larger result set. E.g.:

```json
{
  "query": {
    "match_all": { }
  },
  "size": 20
}
```

So, this is not a bug. Do you find anything can be improved to make this better discoverable?

**Comment by gaojianzhuang** [comment]
> , this is not a bug. Do you find anythin

Thanks so much. If that is, could you please update the default query body with the default size of 10 when the user click the "Match All query" link? I think that more makes  sense. Thanks. :)

**Comment by Piedone** [comment]
Sure. So the task here is to update the default "Match All query" to the below one, making it apparent that there's a limit:

```json
{
  "query": {
    "match_all": { }
  },
  "size": 10
}
```

**Comment by Piedone** [comment]
This isn't completed.

**Comment by jbytes1027** [comment]
Was completed by #17129. I believe this can be closed.

**Comment by gvkries** [comment]
> Was completed by #17129. I believe this can be closed.

Yes, thank you.

**Comment by Piedone** [comment]
Please next time use the "Fix #number" pattern in the PR description so it'll auto-close the issue.
