### ISSUE TITLE
ConcurrencyException in SearchContentItems API with ContentPickerFields

### ISSUE THREAD

**Issue by dannyd89** [OrchardCMS/OrchardCore#16784]
### Describe the bug
Currently if you have multiple `ContentPickerField`s using the same `DisplayedContentTypes` set to them, you get very annoying problems:

1. If you have an item already set to the `ContentPickerField` then the field might not render the `DisplayText`, because the item wasn't loaded
2. The `ContentPickerField`s don't show any items to select if you click in them. Sometimes some show some items and the other one doesn't. If you input a search string into the `ContentPickerField` it will successfully show the list of chooseable items.
3. In Sentry I see the exception thrown in the screenshot below

### Orchard Core version
2.0

### To Reproduce
My setup is:
- Hosted in an Azure App Service with the basic dev plans, so it's rather slow
- Using MySql as DB
- Using multiple tenants
- Using distributed tenants (multiple servers, one DB)
- The types were generated in code
- We do have a lot of content items (>10000)
- Locally with Sqlite and in a tenant this problem occurs too

### Expected behavior
`ContentPickerField`s work as in 1.8.x and show the expected content

### Logs and screenshots
Sentry error
![image](https://github.com/user-attachments/assets/08cabf83-6871-438c-aa66-fadc255a307b)
Example in the CMS
![image](https://github.com/user-attachments/assets/04339ebd-22d8-4eb7-8229-1b02efe6ba8d)

**Comment by dannyd89** [comment]
This might have been fixed on main with #16757

**Comment by Piedone** [comment]
Thaks for the detailed report. Yep, this seems to be the same as https://github.com/OrchardCMS/OrchardCore/issues/16741. And yep, we'll need to have a 2.0.1: https://github.com/OrchardCMS/OrchardCore/issues/16786.
