### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by fuzzbuzzz** [OrchardCMS/OrchardCore#16793]
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/16366

<div type='discussions-op-text'>

<sup>Originally posted by **tcobbfis** June 24, 2024</sup>
In order to meet security requirements (45 day password expire), I need to change the users module (login function).   When trying to edit and build with source code I get the error below.  

Also, is editing the source the right way to make this change?  I tried creating an altered users module over the weekend, but had trouble when trying to replace the built in users module with it.  

PS C:\Repos\Orchard> docker compose up --build
2024/06/24 11:32:47 http2: server: error reading preface from client //./pipe/dockerDesktopLinuxEngine: file has already been closed
[+] Building 15.2s (9/9) FINISHED                                                                                                                                                    docker:desktop-linux
 => [fisorchard internal] load build definition from Dockerfile                                                                                                                                      0.0s
 => => transferring dockerfile: 371B                                                                                                                                                                 0.0s
 => [fisorchard internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0                                                                                                                         0.9s
 => [fisorchard internal] load .dockerignore                                                                                                                                                         0.1s
 => => transferring context: 291B                                                                                                                                                                    0.0s
 => [fisorchard build-env 1/5] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:3189e564f19e016a43838a46609fc81349f07322fdf6bc3299bd13f0dca9e647                                                         0.0s
 => [fisorchard internal] load build context                                                                                                                                                         1.8s
 => => transferring context: 1.12MB                                                                                                                                                                  1.7s
 => CACHED [fisorchard build-env 2/5] WORKDIR /app                                                                                                                                                   0.0s
 => CACHED [fisorchard build-env 3/5] COPY ./src /app                                                                                                                                                0.0s
 => CACHED [fisorchard build-env 4/5] COPY Directory.Build.props /                                                                                                                                   0.0s
 => ERROR [fisorchard build-env 5/5] RUN dotnet publish /app/OrchardCore.Cms.Web -c Release -o ./build/release --framework net8.0 /p:RunAnalyzers=false                                             12.3s
------
 > [fisorchard build-env 5/5] RUN dotnet publish /app/OrchardCore.Cms.Web -c Release -o ./build/release --framework net8.0 /p:RunAnalyzers=false:
1.384   Determining projects to restore...
11.73 /usr/share/dotnet/sdk/8.0.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(96,5): error NETSDK1013: The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [/app/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj]
------
failed to solve: process "/bin/sh -c dotnet publish /app/OrchardCore.Cms.Web -c Release -o ./build/release --framework net8.0 /p:RunAnalyzers=false" did not complete successfully: exit code: 1
</div>

**Comment by fuzzbuzzz** [comment]
hi there,

When I have forked the 2.0.0 release branch (https://github.com/OrchardCMS/OrchardCore/releases/tag/v2.0.0) and executing the `docker build .` command, I'm receiving this error:

` => ERROR [build-env 5/5] RUN dotnet publish /app/OrchardCore.Cms.Web -c Release -o ./build/release --framework net8.0 /p:RunAnalyzers=false                                                                                                                                                 2.6s
------                                                                                                                                                                                                                                                                                            
 > [build-env 5/5] RUN dotnet publish /app/OrchardCore.Cms.Web -c Release -o ./build/release --framework net8.0 /p:RunAnalyzers=false:                                                                                                                                                            
0.507   Determining projects to restore...                                                                                                                                                                                                                                                        
2.565 /usr/share/dotnet/sdk/8.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(96,5): error NETSDK1013: The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [/app/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj]
------
Dockerfile:12
--------------------
  10 |     COPY Directory.Build.props /
  11 |     
  12 | >>> RUN dotnet publish /app/OrchardCore.Cms.Web -c Release -o ./build/release --framework net8.0 /p:RunAnalyzers=false
  13 |     
  14 |     # Build runtime image
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet publish /app/OrchardCore.Cms.Web -c Release -o ./build/release --framework net8.0 /p:RunAnalyzers=false" did not complete successfully: exit code: 1
`

Can someone advise? 💯 

Thank you

**Comment by sebastienros** [comment]
I can reproduce the issue locally. I am having issue copying the `Directory.Packages.props` file which is required.
