### ISSUE TITLE
Protection Key is not removed during tenant removal

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16799]
### Describe the bug
When we remove a tenant using the UI, the database and the host container are cleared of the tenant. But the Protection key is not removed.

### Orchard Core version

Add the version of the Orchard Core NuGet packages you use, or the commit hash if you can reproduce this with the source code.

### To Reproduce
1. Create a tenant
2. Set it up
3. Disable it
4. Remove it
5. Check the protection key `DataProtectionKeys.xml` it will exists. I tested this when data protection are stored in Azure Blob storage "not sure if locally we have the same problem".

### Expected behavior
I would expect everything related to the tenant being removed to be removed.

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/16403

**Comment by sebastienros** [comment]
Same solution as the related issue, create an `IShellRemovingHandler` to handle it. And for any data protection provider.
