### ISSUE TITLE
Chinese is escaped, how not escaped?

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#16810]
### Describe the bug
![image](https://github.com/user-attachments/assets/3ab62a28-6098-461f-99f0-c9cb8d8318fd)

### Orchard Core version
v2.0.2
 
### Expected behavior
![image](https://github.com/user-attachments/assets/d19ad28b-b96f-438d-8914-4cf885b35ab2)

**Comment by hishamco** [comment]
Please steps to reproduce

**Comment by chinasqzl** [comment]
V2.0.2,    Any content is saved in Chinese, and the serialized Chinese will be escaped

![image](https://github.com/user-attachments/assets/11753bf8-2d96-4c6e-a866-19550b360d0d)

![image](https://github.com/user-attachments/assets/af81864a-20dc-44eb-94b1-9db60e3deff5)

**Comment by Piedone** [comment]
Where does this cause an issue for you? Isn't this a standard escaping of Chinese characters?

Also, could you please paste those two characters into a comment here, so we can reproduce?

**Comment by chinasqzl** [comment]
中文，    Don't want to be escaped, already have production data，JSON is also unreadable.

**Comment by gvkries** [comment]
This is by design, but maybe we can allow additional character ranges to be serialized directly. See https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/character-encoding

**Comment by chinasqzl** [comment]
Yes, it works, but I still want it to be the same as before 1.8.3     @Piedone 

services.Configure<DocumentJsonSerializerOptions>(options => {
	options.SerializerOptions.Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping;
});
It doesn't work   @gvkries

**Comment by hishamco** [comment]
I will check this myself, I think there reason that we don't use serialization options in many places

**Comment by Piedone** [comment]
You need to override `DocumentJsonSerializerOptions` to set this (see from here: https://github.com/OrchardCMS/OrchardCore/blob/d0bce2b354ac1a08c2f749d4b6c08b0c2f757e58/src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs#L153). Let us know what works for you. But I wouldn't really change the default now.

**Comment by hishamco** [comment]
@chinasqzl you can try the Zoltan's suggestion before me :)

**Comment by chinasqzl** [comment]
![image](https://github.com/user-attachments/assets/74b886bb-b8aa-4b3c-954d-f79fa27e2997)

services.Replace(ServiceDescriptor.Transient<IConfigureOptions<DocumentJsonSerializerOptions>, DocumentJsonSerializerOptionsConfiguration1>());


@Piedone  It doesn't work

**Comment by Piedone** [comment]
In what way it doesn't work? Is your custom implementation called, to begin with (you can check with the debugger)?

**Comment by gvkries** [comment]
You should be able to change the serializer configuration e.g. from a module by using `PostConfigure<T>()`:

```csharp
services.PostConfigure<DocumentJsonSerializerOptions>(options =>
{
    options.SerializerOptions.Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping;
});
```

**Comment by gvkries** [comment]
I thought you were talking about the database. The output in the views are a different thing, e.g. the "view as json" functionality just uses `ToString` on a `JsonObject`. Not easily to configure without changing the source.
And when using unescaped JSON in HTML it comes with security issues, so I think we should not change that.

**Comment by chinasqzl** [comment]
Yes, the database is fine, and I'm okay with that.
