### ISSUE TITLE
Separate admin setup user from orchardcore.users feature.

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#16817]
I want to create a custom setup recipe to install my own version of admin user and not use the default provided by Orchardcore.users Feature. 
But this is not possible because the admin user Setup event handler is tied to the  users feature. 
I want to opt-out from the admin user setup when enabling the Users feature.

So i think we should place this in a separate feature . For the built in setup recipes just include this new feature to not break anything.

**Comment by MikeAlhayek** [comment]
Just remove it from the IoC in a feature that depends on `OrchardCore.Users` with something like this

        var oldProvider = services.FirstOrDefault(x => x.ServiceType == typeof(ISetupEventHandler) && x.ImplementationType == typeof(SetupEventHandler));

        if (oldProvider is not null)
        {
            services.Remove(oldProvider);
        }

**Comment by giannik** [comment]
that works for me. closing pr
