### ISSUE TITLE
Assets index page should display the root folder expanded by default

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1683]
I think that would be nice.
The first thing I have to do each time I navigate to the Assets index page is to click on the small "Media Library" toggler icon to expand the subfolders.

**Comment by Skrypt** [comment]
Maybe open the first folder and leave the others closed? If there is a lot of those folders ; having them all opened might be harder to reach the ones in the bottom quicker. In 01 we we're displaying a gallery of the most recent images when opening the Media Library.

**Comment by Skrypt** [comment]
Right the Media Library root folder should not be displayed if we can't create other root folders.

**Comment by sebastienros** [comment]
We might want other root folder later, like a Users folder. Or a Recent media one ...
