### ISSUE TITLE
"The node already has a parent." exception when setting JsonNode in Workflows ForEach Task

### ISSUE THREAD

**Issue by zl2fxy** [OrchardCMS/OrchardCore#16846]
Title: System.InvalidOperationException: The node already has a parent. when setting JsonNode in OrchardCore Workflows

Description: I encountered a System.InvalidOperationException: The node already has a parent. when working with JsonNode in OrchardCore workflows. The error occurs when setting a JsonNode as the current value in a ForEachTask activity. It seems that the same JsonNode is being assigned to multiple parents, which causes the exception.

Error Message:

```
mathematica
复制代码
System.InvalidOperationException
  HResult=0x80131509
  Message=The node already has a parent.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeAlreadyHasParent()
   at System.Text.Json.Nodes.JsonObject.SetItem(String propertyName, JsonNode value)
   at OrchardCore.Workflows.Activities.Activity.SetProperty(Object value, String name) in E:\Test\test-orchard-core1\src\OrchardCore\OrchardCore.Workflows.Abstractions\Activities\Activity.cs:line 149
   at OrchardCore.Workflows.Activities.ForEachTask.set_Current(Object value) in E:\Test\test-orchard-core1\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\ForEachTask.cs:line 47
   at OrchardCore.Workflows.Activities.ForEachTask.<ExecuteAsync>d__20.MoveNext() in E:\Test\test-orchard-core1\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\ForEachTask.cs:line 74
```

Steps to Reproduce:

Create a workflow in OrchardCore that includes a ForEachTask activity.
Iterate over a collection of JsonNode objects.
Set a JsonNode object as the current value of the task in each iteration.
The exception is thrown because the JsonNode has already been assigned to a parent.
Expected Behavior: There should be no exception when setting a JsonNode in each iteration of the ForEachTask. Either JsonNode should be cloned or detached from its current parent before being reassigned.

Actual Behavior: An exception is thrown because JsonNode is being reused and assigned to multiple parents.

Possible Solutions:

Clone the JsonNode using DeepClone() before assigning it to avoid parent conflicts.
Remove the JsonNode from its current parent before reassigning it.

Environment:

OrchardCore version: 2.0
.NET version: .net8.0
Operating System: windows

**Comment by sebastienros** [comment]
I assume that's a technical limitation to STJ and you just can't copy these nodes.
You either have to extract the information (strings, ...) yourself or clone the json node before you reuse it.

**Comment by zl2fxy** [comment]
> I assume that's a technical limitation to STJ and you just can't copy these nodes. You either have to extract the information (strings, ...) yourself or clone the json node before you reuse it.

Yes, I have already dealt with this issue, so do I need to submit a pull reset now?

**Comment by sebastienros** [comment]
@zl2fxy if you think there is a product defect (a bug) somewhere in OC feel free to open one. It didn't seem like there is one to me, but maybe it will clear it out by seeing a PR.
