### ISSUE TITLE
Frontend menu disappear when enable localization for the frontend menu

### ISSUE THREAD

**Issue by gaojianzhuang** [OrchardCMS/OrchardCore#16869]
### Describe the bug
After I added the localization part for the menu content type(Content Types -> Menu -> Edit), the frontend menu disappeared.
![image](https://github.com/user-attachments/assets/d2ec35b9-5bfe-4ccc-9c6b-a8877f5b41a2)

![image](https://github.com/user-attachments/assets/3bc7face-48cb-4671-88c5-952e3eb63038)

### Orchard Core version
version: 2.0.0
![image](https://github.com/user-attachments/assets/ec02bff8-9767-4a14-8dd8-a1d11b4052ed)

### To Reproduce
1. Go to 'Content Types -> Menu -> Edit.'
2. Add "Localizaiton" part.
3. Update the Menu content.
4. The frontend UI menu disappears.

### Expected behavior
The menu should display well, if I change the language, the menu should render with the language.

### Logs and screenshots

![image](https://github.com/user-attachments/assets/045859be-d50b-4850-b6a2-21a9904e8b5a)

The layout template codes:
```
{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_fixed_duration: "00:05:00", cache_tag: "alias:main-menu" %}
{% assign cultures = Culture | supported_cultures %}
<div class="culture-picker dropdown">
    <button class="btn btn-success btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">{{Culture.Name}}</button>
    <ul class="dropdown-menu dropdown-menu-end shadow">
        {% for culture in cultures %}
            {% if culture.Name != Culture.Name  %}
            <li><a class="dropdown-item" href="{{ culture.Name | switch_culture_url }}">{{ culture.Name }}</a></li>
            {% else %}
            <li><a class="dropdown-item active" href="{{ culture.Name | switch_culture_url }}">{{ culture.Name | t }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
</div>
```

**Comment by gaojianzhuang** [comment]
I think I found the root cause.
{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_fixed_duration: "00:05:00", cache_tag: "alias:main-menu" %}
The menu alias changed, I need to update the logic. The alias should be dynamic with the culture.

**Comment by Piedone** [comment]
Thanks for the update!
