### ISSUE TITLE
Publish or save or delete content will cause the application crash and shut down

### ISSUE THREAD

**Issue by gaojianzhuang** [OrchardCMS/OrchardCore#16877]
### Describe the bug
Version: orchardcore 2.0.2
DB: SQLite

### Orchard Core version

Add the version of the Orchard Core NuGet packages you use, or the commit hash if you can reproduce this with the source code.
![image](https://github.com/user-attachments/assets/0253f174-c572-43eb-92fd-33e3cee555c4)

### To Reproduce
1. Go to 'feature' and enable the localization-related features.
2. Go to the "Widgets"
3. Click on 'Footer' and edit
4. Click the "Publish" button and the application will crash and the console will shut down without any log message
5. See error

### Logs and screenshots
![20241013104834 00_00_04--00_00_24](https://github.com/user-attachments/assets/814cc3e8-5f49-4a17-a3b0-cb30197ce8aa)

**Comment by MikeAlhayek** [comment]
@gaojianzhuang is there specific feature we should enable to encounter this issue? I can't reproduce it and I enabled all the feature that are related to localization.

![image](https://github.com/user-attachments/assets/e2220685-8f42-4a29-b651-30a5abbf7f5d)

**Comment by Piedone** [comment]
Also, please check the logs if there's anything related.
