### ISSUE TITLE
`Recipe step -> OpenIdServerSettings -> AccessTokenFormat` doesn't work

### ISSUE THREAD

**Issue by hieucd04** [OrchardCMS/OrchardCore#16879]
### Describe the bug
`Recipe step -> OpenIdServerSettings -> AccessTokenFormat` doesn't work!

### Orchard Core version
2.0.2

### To Reproduce
1. Go to https://docs.orchardcore.net/en/main/reference/modules/OpenId/
2. Search for `AccessTokenFormat` (see image below)

### What happened
The docs said that `AccessTokenFormat` can be set to value `"JsonWebToken"`. However, it didn't work. Instead, I had to set it to `1`. I suspect there is a Json deserialization issue involving C# enum. 

### Expected behavior
Either `Recipe step -> OpenIdServerSettings -> AccessTokenFormat` works as the docs said or the docs needs to be updated.

![bug](https://github.com/user-attachments/assets/d3d7af71-3da5-4a97-9cde-f9df53c4d923)

**Comment by Piedone** [comment]
This looks like a JSON serialization issue, no @MikeAlhayek?

**Comment by hishamco** [comment]
@hieucd04 could you please try it on the nightly build, I came across this issue a few days ago, and I hope it got fixed, otherwise let us know

**Comment by MikeAlhayek** [comment]
I think this is a serializer option. We don't include a two way enum converter.

**Comment by hishamco** [comment]
Let me first check if I can reproduce the issue in the nightly build

**Comment by hieucd04** [comment]
@hishamco I tried to look for `prerelease` versions of `OrchardCore.*` nuget packages to install but couldn't find any.
Let me know if you need any other info on this. I think I can help test this issue on my side but I need the `version-to-be-tested` to be available on nuget.

**Comment by hishamco** [comment]
Thanks, I hope to find time today to revisit this issue
