### ISSUE TITLE
Small UI issues on media module

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1690]
Hi,
I see some small things on the ui and I've been working on fixing them.
I changed some alignments and sizes and added a delete button to each thumbnail to make the task easy. Right now the user has to select the media,maybe at the bottom of the page, and then go up to click the delete button.
I applied the changes on the list of media items, and on the edit media field. The modal looks the same.
Please let me know what do you think before submitting the PR.

![issues](https://user-images.githubusercontent.com/2589629/38947102-cae447fa-433b-11e8-8d43-7f1ec6b6599a.jpg)

Fixes:

![changes](https://user-images.githubusercontent.com/2589629/38947116-d6281df8-433b-11e8-9604-a7abcb5c5815.jpg)

**Comment by matiasmolleja** [comment]
![table](https://user-images.githubusercontent.com/2589629/40250485-b6a2953c-5ad6-11e8-9ba1-83e6bc58dcde.gif)

**Comment by matiasmolleja** [comment]
Agree. That will reduce the width of the navbar too. 
I need to fix the overflow of the table on the modal that you can see on the video too.

Not directly related with that: The files are getting too big as I added features. I'd like to split app.js in other smaller files, as you did with the folder component. But I can't because localization. We are using @T[""]  on the .cshtml and that is not possible on .js files.
Do you know a good way to solve that? I was thinking in having the texts provided by the controller as json. But then there are different ways of doing that...
Not sure if It its better to wait until we have fixed a "official" way of doing that.

**Comment by sebastienros** [comment]
For localization, render divs with attributes containing localized strings. Then load the text from javascript using ids and read the attribute.

The table view needs some more love too, looks kind of ugly but I know it's needed too. Take a look at WP for ideas.
