### ISSUE TITLE
Can't POST to Custom Module Controller Action

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrchardCMS/OrchardCore#1692]
I must be losing the plot, but having created a simple module, with route and controller action I can successfully GET an action method, but not POST data to one. Currently using Postman to send the data and getting '400 Bad Request'. I'm sure I've used every combination:

In Startup.cs:
```
    public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
    {
           routes.MapAreaRoute(
                name: "DataPoint",
                areaName: "MyModule.MyEndpoint",
                template: "Home/{action}",
                defaults: new { controller = "Home", action = "Index" }
            );
            routes.MapAreaRoute(
                name: "AnotherDataPoint",
                areaName: "MyModule.MyEndpoint",
                template: "SendSomething",
                defaults: new { controller = "Home", action = "SendSomething" }
            );
        }
```

In Home controller for GET:
```
        [HttpGet]
        public IActionResult Index()
        {
            return Content("Get this.");
        }
```

for POST:
```
        [HttpPost]
        public IActionResult Index([FromBody]string message)
        {
            return Content($"Sent {message}.");
        }
```

OR
```
        [HttpPost]
        public IActionResult Index(MessageModel message)
        {
            return Content($"Sent {message.Message}.");
        }
```

OR
```
        [HttpPost]
        public IActionResult Index([FromBody]MessageModel message)
        {
            return Content($"Sent {message.Message}.");
        }
```

which uses a simple data class:
```
    public class MessageModel
    {
        public string Message { get; set; }
    }
```

OR
```
        [HttpPost]
        public async Task<IActionResult> SendSomething(MessageModel model)
        {
            return Ok();
        }
```

OR
```
        [HttpPost]
        public async Task<IActionResult> SendSomething([FromBody]MessageModel model)
        {
            return Ok();
        }
```

Bearing in mind that GET works, if I do a simple POST with:
```
    Accept: */*
    Content-Type: application/json
```
Body (Raw) JSON:
`{
   "message" : "say something"
}`

I get 400 Bad Request. The same POST to a newly created .NET Core MVC works...

**Comment by sebastienros** [comment]
You are certainly forgetting to pass the anti forgery token.

**Comment by GadgetGeekUK** [comment]
Darn, knew I'd missed something, I'll give it a go!

Thanks again, sanity saved...almost

**Comment by GadgetGeekUK** [comment]
Just having issues creating the token as the form is in a liquid template, JavaScript submits the form (using jQuery $.ajax, so I need to get the Token name/value and add it to the ajax POST.

**Comment by sebastienros** [comment]
There is a way in MVC to configure the token to be available in a header, so that JS scripts can read it, maybe we could expose it too.

**Comment by stantoxt** [comment]
I had the same problem,I changed the code like this 
`$.ajaxPrefilter(function (options, originalOptions, jqXhr) {
        if (options.type.toUpperCase() === "POST") {
            var token = $("input:hidden[name^=__RequestVerificationToken]").first();
            if (!token.length) return;
            jqXhr.setRequestHeader("RequestVerificationToken", token.val());
        }
    });`

**Comment by Dean-ZhenYao-Wang** [comment]
> MVC中有一種將令牌配置為可在標頭中使用的方式，以便JS腳本可以讀取它，也許我們也可以公開它。

And it didn't work.
![image](https://user-images.githubusercontent.com/26154837/76783394-c1d31380-67ec-11ea-8264-b051b8bafcc9.png)

**Comment by RockNHawk** [comment]
@Dean-ZhenYao-Wang you can add a [IgnoreAntiforgeryToken]  Attribute on method to ignore AntiforgeryToken.

**Comment by aaronamm** [comment]
@Dean-ZhenYao-Wang not sure if you have fixed this error. It happens to me and I couldn't fix it with:
```js
header
'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',

form data
__RequestVerificationToken: antiforgeryToken
```
However, setting `RequestVerificationToken` works for me.

FYI, I use axios.post()
