### ISSUE TITLE
sort and where liquid filters stopped working

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/OrchardCore#16922]
### Describe the bug

After upgrading to OrchardCore 2 (STJ) the where and sort filters stopped working

```liquid
{% assign hotActions = articleListItems
| where: "Content.HotActionsPart.AddtoHotActionsMenu.Value", true
| sort: "Content.HotActionsPart.Order.Value" %}
```

the above code used to work in OC 1.8

### Orchard Core version

2.0.2

### To Reproduce

create a liquid template and try filtering and sorting

### Expected behavior

The array should contain the filtered elements, sorted

**Comment by MichaelPetrinolis** [comment]
> @MichaelPetrinolis what is the easiest way to repro? A shape template, a query? With a Boolean Field?

@sebastienros yes,a content item with a part that has two fields, one boolean and one numeric. We used the numeric for sorting and the bool for filtering. Also the items come from a query inside the liquid template.

**Comment by MichaelPetrinolis** [comment]
@sebastienros I added some tests that reproduce the bug with 'sort' and 'where' liquid filters

**Comment by sebastienros** [comment]
So the issue looks like ordering on deserialized json. With all the automatic type conversion that was added since the switch it makes me a little sad. But the test will help a lot, thanks.
