### ISSUE TITLE
Localize BagPart not working

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#16937]
### Describe the bug

Unable to localize BagPart

### Orchard Core version

2.0.2

### To Reproduce

1. Add content type named "FAQ"
2. Add another content type named "FAQ Item"
3. Add Localization part to  "FAQ Item"
4. Add BagPart of  "FAQ Item" into "FAQ" type
5. Create a content item for "FAQ"
6. Click Publish (after adding a few cultures)
7. Select another culture
8. See error 

### Logs and screenshots

The page could not be found.

**Comment by hishamco** [comment]
For me localizing "FAQ" content item fixes the issues, we might not allow localize `BagPart` by design unless there's a reason for that

**Comment by Piedone** [comment]
Please provide a screen recording (some video so we an pause and seek it, not gif) for steps 5-8, because I don't understand what you're doing and what you expect to happen.

**Comment by hishamco** [comment]
Seems embedded content items not support localization at all, I will try to provide a mp4 recording
