### ISSUE TITLE
Data Type Mismatch Issue After Upgrade from 1.6.0 to 1.7.2

### ISSUE THREAD

**Issue by naomi-earle** [OrchardCMS/OrchardCore#16931]
### Describe the bug

After upgrading a project from Orchard Core version 1.6.0 to 1.7.2, we noticed that data types for certain fields were changed from int to long starting with version 1.7.0. However, there was no migration step provided to alter the existing database columns accordingly.

When creating a new database from versions 1.7.0 or 1.7.2, the columns are correctly set to bigint, but our existing database retains the int type. While it appears that there are work-arounds in place and backward compatibility has been addressed, we are concerned that this mismatch could lead to bugs or issues in future updates.

### Orchard Core version

1.7.2 (upgraded from 1.6.0)

### To Reproduce

1. Upgrade an Orchard Core project with a database to 1.7.0 from an earlier version.
2. Inspect the data types of columns in the existing database.
3. Compare with a newly created database from version 1.7.0.

### Expected behavior

Data types for all relevant columns in the existing database should match those in the new database, specifically, being of type bigint instead of int.

### Additional context

I found a related bug report from June (https://github.com/OrchardCMS/OrchardCore/issues/16580) that addresses similar concerns, and a fix was implemented (https://github.com/OrchardCMS/OrchardCore/pull/16234/files). However, without a migration step for existing databases, I am worried about ongoing issues stemming from this data type mismatch.

**Comment by MikeAlhayek** [comment]
> After upgrading a project from Orchard Core version 1.6.0 to 1.7.2, we noticed that data types for certain fields were changed from int to long starting with version 1.7.0. However, there was no migration step provided to alter the existing database columns accordingly.

You should not run into a mismatch. If your site was created before 1.7 release, then it'll always be int even if you create new tables. However, if your site was created 1.7+, then the new default will be bigint.

Are you seeing a specific issue?

**Comment by sebastienros** [comment]
As long as YesSql has this option alive this will work

https://github.com/sebastienros/yessql/blob/d2f941d1049224ddbb082a83ddac19d376bc0ae1/src/YesSql.Core/Configuration.cs#L46
