### ISSUE TITLE
ElasticSearch Query Result not displaying anymore

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#16933]
![image](https://github.com/user-attachments/assets/656cf2da-f454-44f5-8eaf-d97558190a18)

The ElasticSearch Queries are not showing results anymore. Any reason why?

@MikeAlhayek

**Comment by MikeAlhayek** [comment]
Not sure. I don't see others reporting this being an issue. Are there any errors in the log file? 

I can try to reproduce the issue if you share the exact step to reproduce it.

**Comment by Skrypt** [comment]
Just pull latest dev branch and install blog recipe then setup ElasticSearch. Create an index and query it with a match all query like it does.

**Comment by Piedone** [comment]
We have a UI test testing Elasticsearch and it works with 2.0.1 BTW.

**Comment by Piedone** [comment]
Might be related that someone [sees the same with Lucene](https://discord.com/channels/551136772243980291/551137154705653775/1299023220766281759).

**Comment by PBMikeW** [comment]
Latest dev and blank site recipe I'm unable to replicate the issue. Did you tick store source data in index?

![image](https://github.com/user-attachments/assets/48866a7a-9a94-4973-808e-515f1f8741ba)

**Comment by Skrypt** [comment]
I did not. But it should return results still.

**Comment by PBMikeW** [comment]
I tested unticking store source and as per your screenshot you get result numbers but no actual results. The way you wrote 
![image](https://github.com/user-attachments/assets/411d62e7-6f19-4c70-add7-7a934e975dcc)
led me to believe this was intentional.

**Comment by Piedone** [comment]
Are we talking about this?

![image](https://github.com/user-attachments/assets/b2cef82e-7a2f-465f-866c-dbf82eeab229)

Yeah, this should definitely be ticked.

**Comment by PBMikeW** [comment]
> Are we talking about this?
> Yeah, this should definitely be ticked.

Yes thats what I'm referring to. Unticking gives the result that Skrypt is seeing and I thought it was intentional.

**Comment by Skrypt** [comment]
Memory fails. Maybe you guys are right. But else, I'm pretty sure at some point it was working. Source is just the data stored in the index. Else, just like Lucene works ; it should return results and display them.

**Comment by Skrypt** [comment]
I'm closing this issue as there is a workaround. I will open a new one if I find something else.

**Comment by MikeAlhayek** [comment]
I don't use this UI. But I would expect it to return at least the content item id if there is no source
