### ISSUE TITLE
IUserTimeZoneService no longer caches user requests

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#16932]
this pr  #16614 has made some changes to how the users time zones are cached which makes the cache useless.

this code in `UserTimeZoneSelector` now retrieves the current user on every request, before trying to get a timezone for the user.

(or in fact if a timezone calcation is done more than once on a page, which is a common usage, then it queries for the user multiple times)
```
        var currentUser = await _userManager.GetUserAsync(_httpContextAccessor.HttpContext.User);
```

the previous arrangement where `UserTimeZoneService` held the cache for  the database query to lookup the user (to get their timezone) was a useful cache. Now it's irrelevant, because the componet calling into that cache is doing all the work.

**Comment by Skrypt** [comment]
Remembers me something I had fixed once.

**Comment by sebastienros** [comment]
We need to remove the cache from the `IUserTimeZoneService` implementation and move it to the `UserTimezoneSelector` instead, which will prevent it from loading the user. The key will be the username which is fetched from the HttpContext.

**Comment by sebastienros** [comment]
@deanmarcussen I suggest you watch today's meeting when it's available, we review the latest PR. My suggestion is to remove this service and put whatever it does (caching) in `UserTimeZoneSelector`. I explain my reasons during the meeting. The other option we have is to keep what @MikeAlhayek has done in the new PR, which fixes the caching issue (like my suggestion it's a breaking change).

**Comment by MikeAlhayek** [comment]
@sebastienros additionally, removing the `IUserTimeZoneService` will be a breaking change and can't be done in 2.x. unless we want to leave it there as useless code for 2.x and remove it in 3.0.
