### ISSUE TITLE
Use Microsoft.IO.RecyclableMemoryStream

### ISSUE THREAD

**Issue by adamradocz** [OrchardCMS/OrchardCore#16946]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
In the code, new `MemoryStream()`s could be optimized with pooling by using the [Microsoft.IO.RecyclableMemoryStream](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream) nuget.

**Comment by hishamco** [comment]
I noticed that you suggested this in Oqtane Framework too :) I just read about the `RecyclableMemoryStream` I never mind letting you push a PR if @sebastienros has no objection

**Comment by sebastienros** [comment]
I am very familiar with `RecyclableMemoryStream` and find it very well-done. I personally use it as an `IBufferWriter` which is supports too (not just `Stream`).

From the PR I see we use `MemoryStream` mostly with existing arrays. In that case `MemoryStream` is not allocating anything so using the RMS is useless, assuming we are not adding more data to the stream.

However there might be other places where we don't use `MemoryStream` explicitly and could benefit from this library, like template generation. Let's see...
