### ISSUE TITLE
OrchardCore.Forms throws InvalidOperationException when restoring checkboxes from ModelState

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#16975]
### Describe the bug
`OrchardCore.Forms` leverages `ModelStateHelpers.SerializeModelState` and `ModelStateHelpers.DeserializeModelState` to preserve ModelState across web requests. This is broken for checkboxes since `System.Text.Json` was introduced in 2.0.0.

```
InvalidOperationException: The parameter conversion from type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Boolean' failed because no type converter can convert between these types
```

### Orchard Core version

2.0.2

### To Reproduce
In my app I'm not actually using the form content item, but I do use `OrchardCore.Forms` solely for the ModelState preservation "trick". But I imagine you can reproduce this in OC with a simple form content item with a checkbox. You also need the form to be invalid so the ModelState preservation trick gets invoked and the user gets redirected back to the form.

Here's a simple console app that demonstrates the issue by comparing what happens with Newtonsoft.Json to System.Text.Json.

```
using Microsoft.Extensions.Primitives;

var checkbox = new ModelStateTransferValue
{
    Key = "MyCheckbox",
    AttemptedValue = bool.FalseString,
    RawValue = new StringValues(bool.FalseString) // Checkboxes in .NET set the RawValue to a StringValues object
};

// ModelStateHelpers.SerializeModelState
string newtonsoftJson = Newtonsoft.Json.JsonConvert.SerializeObject(checkbox);
string stjJson = System.Text.Json.JsonSerializer.Serialize(checkbox);

// ModelStateHelpers.DeserializeModelState
var newtonsoftModel = Newtonsoft.Json.JsonConvert.DeserializeObject<ModelStateTransferValue>(newtonsoftJson);
var stjModel = System.Text.Json.JsonSerializer.Deserialize<ModelStateTransferValue>(stjJson);

Console.WriteLine($"Type of Newtonsoft RawValue: {newtonsoftModel.RawValue.GetType()}"); // Outputs: Newtonsoft.Json.Linq.JArray
Console.WriteLine($"Newtonsoft RawValue is JArray: {newtonsoftModel.RawValue is Newtonsoft.Json.Linq.JArray}"); // Outputs: True
Console.WriteLine();
Console.WriteLine($"Type of STJ RawValue: {stjModel.RawValue.GetType()}"); // Outputs: System.Text.Json.JsonElement
Console.WriteLine($"STJ RawValue is JsonArray: {stjModel.RawValue is System.Text.Json.Nodes.JsonArray}"); // Output: False

public sealed class ModelStateTransferValue
{
    public string Key { get; set; }
    public string AttemptedValue { get; set; }
    public object RawValue { get; set; }
}
```

Running this console app produces the following output:
```
Type of Newtonsoft RawValue: Newtonsoft.Json.Linq.JArray
Newtonsoft RawValue is JArray: True

Type of STJ RawValue: System.Text.Json.JsonElement
STJ RawValue is JsonArray: False
```

[The key is this line in ModelStateHelpers.](https://github.com/OrchardCMS/OrchardCore/blob/3811a44415f07dc20d1a5f596a1b80a05fb8b90f/src/OrchardCore.Modules/OrchardCore.Forms/Helpers/ModelStateHelpers.cs#L29C13-L29C109)

The Newtonsoft.Json version of the key line is
```
item.RawValue = item.RawValue is JArray jarray ? jarray.ToObject<object[]>() : item.RawValue;
```

The STJ version of the key line is
```
item.RawValue = item.RawValue is JsonArray jarray ? jarray.ToObject<object[]>() : item.RawValue;
```

- With Newtonsoft.Json `is JArray` is true for a checkbox, so the value is converted to `object[]`.
- With STJ `is JsonArray` is false for a checkbox, so the value is left as `JsonArray`.

[Over in .NET we look at ModelBindingHelper.UnwrapPossibleArrayType](https://github.com/dotnet/aspnetcore/blob/2221ef824f4c25b3395fd0f691d81a2c8b5fad71/src/Mvc/Mvc.Core/src/ModelBinding/ModelBindingHelper.cs#L630C28-L630C51). With STJ we end up passing down `List<object>`, which it does not know how to unwrap and so it falls into case 4. Then we get an exception because it doesn't know to convert a list to a checkbox.

**Comment by rjpowers10** [comment]
Just remembered something like this happened before #7256

**Comment by sebastienros** [comment]
Do you think you can provide a PR fixing the conversion?
And if there a way to add a test (unit or functional) to ensure we don't regress that?

**Comment by rjpowers10** [comment]
I started looking into a fix, however I was unable to reproduce my problem exactly in stock OC. I didn't get the exception, but also the checkbox state was not reserved. If I checked the box and submitted the form, I got redirected back but the checkbox remained unchecked.

Need to look into it more.

**Comment by rjpowers10** [comment]
Stock OC example from the main branch

1. Create a new site using the blog recipe.
1. Enable the OrchardCore.Forms feature.
1. Add a new form widget to the "content" zone and "always" layer. In the form's flow:
   1. Add the Validation Summary widget.
   2. Add the Input widget.
      1. Name: Name
      2. ID: Name
      3. Label option: Standard
      4. Label text: Name
      5. Type: Input
      6. Validation option: Standard
   3. Add the Input widget.
      1. Name: MyCheckbox
      2. ID: MyCheckbox
      4. Label option: Standard
      5. Label text: Click me
      6. Type: Checkbox
      7. Validation option: Standard
   3. Add the Button widget
      1. Name: MyButton
      2. ID: MyButton
      3. Text: Submit
      4. Type: Submit
   4. Add a new workflow like the image below. The idea is to submit the form and force a validation error on the checkbox, then redirect back to the form to display the error.
   5. Copy the action from the Http Request Event and set that as the form action back in the form widget.
   6. Uncheck "validate antiforgery token" from the Http Request Event. 

If you get stuck I modified the example "contact" form [from the OC docs](https://docs.orchardcore.net/en/latest/reference/modules/Forms/)

![image](https://github.com/user-attachments/assets/75991b26-0e60-461e-96ad-8f7fc4f15f0b)

View the form
![image](https://github.com/user-attachments/assets/f9323ed0-747c-48d9-9352-8a8eaf08cd21)

Fill out the form
![image](https://github.com/user-attachments/assets/56ec3eda-32c7-4c61-bb79-d7bca57bad9c)

Submit the form. The text input state is preserved. The checkbox state is not preserved.
![image](https://github.com/user-attachments/assets/48385b70-d7c4-4db6-a2ad-2b686a486b75)

Maybe this is a different symptom of the same problem. I don't get the InvalidOperationException, although my checkbox state is also not preserved for the invalid form.

**Comment by rjpowers10** [comment]
Apologies everyone. The original issue I submitted may be in my own code. But I do think there is an OC bug with checkbox state not being preserved in OrchardCore.Forms. I'm going to submit a new issue and PR for that.

**Comment by sebastienros** [comment]
Thanks for investigating!
