### ISSUE TITLE
Release 2.0.3

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#16986]
The SMS Azure Module is missing in `2.0.1` and `2.0.2` which were merged on Sept 26

SMS Azure was introduced in #15539 and merged on Sept 16, this patch release adds the missing support. FYI I verified that the feature is missing with two clients

**Comment by hishamco** [comment]
@sebastienros  @MikeAlhayek please the patch release steps if there's no objection

**Comment by MikeAlhayek** [comment]
@hishamco 
Why isn't it included in 2.0? If it is not in 2.0.2, why would it be in 2.0.3? I suggest opening an issue, address the problem and then we can talk about a patch.

**Comment by hishamco** [comment]
That's why I opened this issue

> Why isn't it included in 2.0? If it is not in 2.0.2, why would it be in 2.0.3?

AFAIK the SMS Azure shipped after `2.0.0`, then you shipped `2.0.1` and Seb reverted some changes in `2.0.2` I think the commit was not included accidentally

Try to check in `2.0.2` NuGet Packages

**Comment by MikeAlhayek** [comment]
This issue is a request to release a new patch. You should have another issue explaining the problem so we can first fix it, then we can use this PR to ship the patch.

**Comment by hishamco** [comment]
Done!!

#16988

**Comment by MikeAlhayek** [comment]
I don't think this is needed "at least not at this time".
