### ISSUE TITLE
OrchardCMS beta2 workflow- Passing values from event to Task

### ISSUE THREAD

**Issue by devanathan2017** [OrchardCMS/OrchardCore#1702]
Hi ,
I have a "Http Request Event" for Get and which have few query string values. I am able to extract those values see the below image.
![image](https://user-images.githubusercontent.com/34333687/39122034-2de41212-4711-11e8-9fd7-c6fa976b4020.png)
Now, I want to pass these values to any of the task for ex the below custom task I have created
![image](https://user-images.githubusercontent.com/34333687/39122305-1c3a56ec-4712-11e8-835d-05ac54594d4d.png)
How to get those query string values in here?... let me know if its possible.

Thanks
Dev

**Comment by sfmskywalker** [comment]
Have your first activity read the query string value (as you're already doing) and then add it as a _property_ to the `workflowContext.Properties` collection. Other activities can then read from that. Another way is to have your activity set the query string value as the "LastResult", which is another property of the workflow context.

Here's a blog post I just published that walks you through setting up a content approval workflow that might interest you: http://www.ideliverable.com/blog/orchard-core-workflows-walkthrough-content-approval

**Comment by devanathan2017** [comment]
I am triggering the workflow events from the button click in the view. Once the workflow is done , Is there a way i can pass some values from the task to front end(cshtml View)? let me know your suggestion.
  ```
public override ActivityExecutionResult Execute(WorkflowExecutionContext workflowContext, ActivityContext activityContext)
        {
// from here i need to pass the values to the view.
return Outcomes("Done");
}
```

**Comment by sfmskywalker** [comment]
There is latent support for this, but we would have to unlock this. Right now, if you invoke a specific workflow, you get back a workflow context from which you can access its `Output` property, which is a dictionary. From within an activity, you can add items to it via the `workflowContext` parameter.

But when you trigger a workflow via `IWorkflowManager.TriggerEventAsync`, the caller won;t know how many workflows will have been created and resumed - unless we return those things to the caller. Perhaps we should, and then it's up to you (the caller) to determine what to do with the list of started/resumed workflow instances.

Alternatively, you can do the triggering yourself from your view today, like so:

```csharp
// Load the workflow definition you want to invoke.
var workflowType = await workflowTypeStore.GetAsync(workflowTypeId); // you would have to hardcode the workflow type ID, which isn't ideal obviously.

// Invoke the workflow.
var workflowContext = await workflowManager.StartWorkflowAsync(workflowType);

// Inspect Outputs:
var outputs = workflowContext.Outputs; // IDictionary<string, object>.
```

**Comment by devanathan2017** [comment]
I have tried the same ,but not able to invoke the workflow. getting the faulted state with indexout of range error. and also the output and lastresult values are null. 

 ```
//assigning values from the work flow task:
workflowContext.Output["Foo"] = "test";
                string[] param = { "Done", "2", "3" };
                workflowContext.LastResult = param;
                return `Outcomes("Done");`
```
![workflow](https://user-images.githubusercontent.com/34333687/39855551-fa4da120-5449-11e8-991a-afeef03179ba.png)
