### ISSUE TITLE
Release v

### ISSUE THREAD

**Issue by kaizhutongxie** [OrchardCMS/OrchardCore#17042]
visual studio 2022 mysql 5.7 contos8 X64  OrchardCore.Application.Cms.Core.Targets 2.0.2
All other functions are good, 
but when I tried to log in to/admin,
 I couldn't log in and the redirect page kept being the/admin page

**Comment by kaizhutongxie** [comment]
log:info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
dbug: Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider[1]
      The temp data cookie .AspNetCore.Mvc.CookieTempDataProvider was not found.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[103]
      Executed action method OrchardCore.Users.Controllers.AccountController.Login (OrchardCore.Users), returned result Microsoft.AspNetCore.Mvc.ViewResult in 17.309ms.

**Comment by hishamco** [comment]
Please choose a proper title, and then mention steps to reproduce
