### ISSUE TITLE
OpenID application with the Administrator role isn't authorized for all permissions anymore

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#17083]
### Describe the bug

When an OpendID application is configured for the Administrator Client Credentials Role, it's not authorizing as if it had all the permissions and thus authorization fails.

I suspect this is coming from https://github.com/OrchardCMS/OrchardCore/pull/16781 @MikeAlhayek.

### Orchard Core version

v2.1.1 but latest `main` too.

### To Reproduce

1. Set up a site with the SaaS recipe and enable the Deployment feature.
2. Import [this recipe](https://github.com/Lombiq/Orchard-Core-API-Client/blob/087d4ecce54fc4ef8ed9a1effceacce5d2730fd6/Lombiq.OrchardCoreApiClient.Tester/Recipes/Lombiq.OrchardCoreApiClient.Tester.OpenId.recipe.json) to set up an OpenID application.
3. Run [this app](https://github.com/Lombiq/Orchard-Core-API-Client/tree/087d4ecce54fc4ef8ed9a1effceacce5d2730fd6/Lombiq.OrchardCoreApiClient.Tester) after changing the port in `Program` to your OC instance's. For your convenience, I'm including a Windows executable below, configured for the vanilla OC from `main` (just run `Lombiq.OrchardCoreApiClient.Tester.exe` from the CLI). This app accesses the OC tenant and content management APIs.
4. Observe an exception that the tenant creation failed with unauthorized:
![{6470DA25-2D54-486B-BFFF-32FDA2BCBC87}](https://github.com/user-attachments/assets/0e87aecc-a3ec-4901-a92a-1e482cb45a84)

This is because this authorization fails, what you can also observe from the debugger:

https://github.com/OrchardCMS/OrchardCore/blob/2355c102ad8f931b86ed5e090b81bd280fd7c801/src/OrchardCore.Modules/OrchardCore.Tenants/Controllers/TenantApiController.cs#L92

The executable:

[net8.0.zip](https://github.com/user-attachments/files/17927435/net8.0.zip)

If you instead use a role that explicitly has the Manage Tenants permission, then the authorization works.

### Expected behavior

The API authorization, and thus tenant creation, continues to work with the Administrator role.

**Comment by MikeAlhayek** [comment]
@kevinchalet I'll try to look into this in the morning, but do we handle permissions check using OpenId implementation different that what we do in OC? With the latest update, we don't store permission claims when a user with Administrator role logs in. In an Authorization handler we added this check https://github.com/OrchardCMS/OrchardCore/blob/2355c102ad8f931b86ed5e090b81bd280fd7c801/src/OrchardCore.Modules/OrchardCore.Settings/Services/SuperUserHandler.cs#L28

When an Admin user logs in we grant them this Owner permission https://github.com/OrchardCMS/OrchardCore/blob/2355c102ad8f931b86ed5e090b81bd280fd7c801/src/OrchardCore.Modules/OrchardCore.Roles/Services/RoleClaimsProvider.cs#L40

I don't think OpenId does anything different and handler permission just like we do in other places

**Comment by kevinchalet** [comment]
> @kevinchalet I'll try to look into this in the morning, but do we handle permissions check using OpenId implementation different that what we do in OC?

No.

The issue described here is likely caused by the fact we're not injecting that new special claim for the client credentials grant, which is a user-less flow but for which we nevertheless allow attaching "role claims" to the access token as a way to control permissions:

https://github.com/OrchardCMS/OrchardCore/blob/2355c102ad8f931b86ed5e090b81bd280fd7c801/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs#L454-L471

Now... it's not clear to me why this "site owner" has a special treatment and isn't exposed as a regular role...
