### ISSUE TITLE
Deployment with queries content items step can't be created

### ISSUE THREAD

**Issue by yqzhen1990** [OrchardCMS/OrchardCore#17102]
### Describe the bug
Deployment with queries content items step can't be created

### Orchard Core version
 v2.1.2

### To Reproduce
1. Go to 'Configurations'
2. Click on 'Import/Export'
3. Scroll down to 'Deployment Plans'
4. Create a deployment plan and manage steps.
5. Add "Queried Content Items"
6. Choose a query and click "create"
7. Then you can see the error.

### Logs and screenshots
![image](https://github.com/user-attachments/assets/6b93ccfc-b749-4547-9b7f-e710f16c84d0)
![image](https://github.com/user-attachments/assets/fc5f6122-8b0e-4066-8d5b-5f5870970055)
![image](https://github.com/user-attachments/assets/f8993168-6a43-47f6-bbcc-deda311d1502)
The "query.CanReturnContentItems" is always "false".

**Comment by Piedone** [comment]
Thanks for the details bug report! Fixed it in the linked PR.

**Comment by hishamco** [comment]
I was working on a PR :)

**Comment by yqzhen1990** [comment]
![Image](https://github.com/user-attachments/assets/68d800de-8b6d-4104-87b5-06e3c594551c)
This logic is still in latest release.

**Comment by Piedone** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/17120 is not yet released, it'll be part of v3.
