### ISSUE TITLE
Submenu items silently fail to delete

### ISSUE THREAD

**Issue by jbytes1027** [OrchardCMS/OrchardCore#17122]
### Describe the bug

Published submenu item's can't be deleted.

### Orchard Core version

    OrchardCore.Application.Cms.Targets      2.0.2

Using default blogs template with sqlite.

### To Reproduce

Add or move menu item to submenu. Publish. Delete.

### Expected behavior

Item should be deleteable.

### Logs and screenshots

https://github.com/user-attachments/assets/6b906e67-6d34-48ee-be17-639c27f76495

**Comment by MikeAlhayek** [comment]
@jbytes1027 Thank you for reporting this issue. I think this issue was fixed in 2.1 via #16990  Are you able to upgrade to 2.1 and test it out?

Related to #16989
