### ISSUE TITLE
Expose ITrackingConsentFeature properties in Liquid

### ISSUE THREAD

**Issue by gvkries** [OrchardCMS/OrchardCore#17134]
When building cookie-consent functionality with Liquid, it would be helpful to expose the functionality or at least some of the properties of the `ITrackingConsentFeature`. E.g. `CanTrack`, `IsConsentNeeded` and the consent cookie name and value would allow to build a JS consent dialog.

**Comment by MikeAlhayek** [comment]
Are you submitting a PR? I would follow what we did with Culture

**Comment by gvkries** [comment]
Yes, I have something locally. Will submit soon...

**Comment by Piedone** [comment]
Great! I wanted to have this too (https://github.com/Lombiq/Orchard-Privacy/issues/63) but didn't get around doing it.
