### ISSUE TITLE
OC throws InvalidOperationException after I upgrated OC from v1.8.4 to v2.1.2 in runtime

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore#17198]
### Describe the bug

OC throws InvalidOperationException after I upgrated OC from v1.8.4 to v2.1.2 in runtime

An unhandled exception occurred while processing the request.
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'OrchardCore.DisplayManagement.Zones.ZoneHolding', but this ViewDataDictionary instance requires a model item of type 'OrchardCore.Users.ViewModels.LoginViewModel'.
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, object model, Type declaredModelType)

### To Reproduce
1. Go to home page
2. Go to /admin
3. Throws InvalidOperationException

![Internal Server Error](https://github.com/user-attachments/assets/14ffd2af-f142-49f6-b590-55fd43ad2b90)

**Comment by Piedone** [comment]
Do you have a login form-overriding template? Because that changed in 2.0, and you'll need to take the latest source as the baseline for the override: https://docs.orchardcore.net/en/latest/releases/2.0.0/#users-module

**Comment by MikeAlhayek** [comment]
I am guessing you have a template overriding the `login.cshtml` which uses to accept `LoginViewModel` and now it accepts `IShape` instead.

Make sure your custom `login.cshtml` looks like this https://github.com/OrchardCMS/OrchardCore/blob/d21acb2f024616c084ece928de7acea3f0f9a097/src/OrchardCore.Modules/OrchardCore.Users/Views/Account/Login.cshtml#L4

**Comment by effapp** [comment]
Hi @Piedone @MikeAlhayek ,
Good, I have a  login form-overriding template. Thanks!
