### ISSUE TITLE
Custom roles overwritten after upgrading to OC 2.1.x

### ISSUE THREAD

**Issue by intellimedhu** [OrchardCMS/OrchardCore#17216]
I am using custom roles where RoleClaims is empty (director, sales manager):
![image](https://github.com/user-attachments/assets/43704a4a-4276-4bf4-a9af-550dd95198af)

After upgrading to Orchard Core 2.1.x (from 2.0.2), I noticed that all users are assigned the `Administrator` role.

I suspect the issue is related to the following line of code:
https://github.com/OrchardCMS/OrchardCore/blob/4ab7c345f3c1f57e8fe4f7bcf173e86ad41aa5d8/src/OrchardCore.Modules/OrchardCore.Roles/Migrations/RolesMigrations.cs#L46

**Comment by MikeAlhayek** [comment]
Did any of the roles `director` `sales manager` has the `OwnerPermission` granted to it? https://docs.orchardcore.net/en/latest/releases/2.1.0/#site-owner-permission-deprecated-administrator-role-retained-as-a-system-role

**Comment by intellimedhu** [comment]
Roles are not assigned any permissions, including OwnerPermission.

**Steps to reproduce:**

1. Using OC 2.0.2 create roles in the admin: `Director`, `Sales Manager`
2. Do not assign any permissions to these roles.
3. Still in the admin dashboard, create some users and assign them only the Director or Sales Manager role (no other roles are given).
4. Upgrade to OC 2.1.0 (or higher), build, and run the application.
5. The `Administrator` role is now assigned to the users created in step 3.

**Comment by gvkries** [comment]
This is a security critical bug, it adds users to the admin role during unintentionally!

Note that it looks like PR #17089 also added the same buggy behavior here too, because the `SiteOwner` claim is also required by the `RolesMigrations` and is now never assigned - I told you, rushing the removal of that claim is a mistake ;-)

**Comment by MikeAlhayek** [comment]
> This is a security critical bug, it adds users to the admin role during migration unintentionally

It is a bad security bug that will needs to be patched today.

> Note that it looks like PR https://github.com/OrchardCMS/OrchardCore/pull/17089 also added the same buggy behavior here too, because the SiteOwner claim is also required by the RolesMigrations and is now never assigned - I told you, rushing the removal of that claim is a mistake ;-)

It actually has nothing to do with that PR. It's a bug introduced by the original PR https://github.com/OrchardCMS/OrchardCore/pull/16781/files#diff-b72d3d57af6cb699ce3d2df36090731745456797fac627681ae3714a08c85cb9R44-R47

**Comment by gvkries** [comment]
> It actually has nothing to do with that PR. It's a bug introduced by the original PR https://github.com/OrchardCMS/OrchardCore/pull/16781/files#diff-b72d3d57af6cb699ce3d2df36090731745456797fac627681ae3714a08c85cb9R44-R47

You're right, I got confused by reading `SiteOwner` claim type, but it's the value... Sorry :-)

**Comment by intellimedhu** [comment]
Thank you!
