### ISSUE TITLE
OpenId.Validation feature configuration does not allow authorities from Settings UI

### ISSUE THREAD

**Issue by salmattia** [OrchardCMS/OrchardCore#17233]
### Describe the bug

OpenId Validation settings UI displays an error when I try to save settings with a valid authority (which is my external IDP) and leaving "Tenant" field empty. As documented here [https://docs.orchardcore.net/en/main/reference/modules/OpenId/#openid-connect-token-validation](https://docs.orchardcore.net/en/main/reference/modules/OpenId/#openid-connect-token-validation) other trusted servers are allowed. So I wouldn't expect a tenant is required.
It looks to me a bug in display driver Update method, because configuration with authority and no tenant is perfectly working by running OpenIdValidationSettings recipe step.

### Orchard Core version

This is not working in version 2.1.2

### To Reproduce

1. Enable feature OrchardCore.OpenId.Validation
2. Go to feature settings UI (Security/OpenId Connect/Settings/Token Validation)
3. Set a valid authority and an audience, leave tenant field empty.
4. Save. => "Tenant is required" error is displayed

### Expected behavior

I would expect that only one of Tenant or Authority fields must be filled out. 
If I configure the feature with its recipe step like this, everything is working as expected and tokens issued by my IDP are correctly validated

```json
{
      "name": "OpenIdValidationSettings",
      "Authority": "https://myidp",
      "Audience": "my-audience "
}
```

Thank you!

**Comment by sebastienros** [comment]
Do you think you could create a PR that would fix the validation?

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.OpenId/Drivers/OpenIdValidationSettingsDisplayDriver.cs#L73

@kevinchalet do you agree with the assumption?

**Comment by kevinchalet** [comment]
> @kevinchalet do you agree with the assumption?

Yeah, this scenario used to work correctly but it seems we broke it with https://github.com/OrchardCMS/OrchardCore/pull/16651 (not sure how I missed that...).

We should definitely fix it and release a new major/patch version urgently.
