### ISSUE TITLE
 Warn Skipping unknown node: extensions

### ISSUE THREAD

**Issue by kookle** [OrchardCMS/OrchardCore#1726]
what is the solution for this error ? thank you.

**Comment by sebastienros** [comment]
Can you explain how to repro the issue?

**Comment by kookle** [comment]
![image](https://user-images.githubusercontent.com/4568525/39431709-3108567c-4c9a-11e8-879b-ace181667a25.png)

**Comment by kookle** [comment]
when click finish setup button is not working.

**Comment by sebastienros** [comment]
Looks like you are using an old version, probably the master branch. If you use the dev branch (or the myget feed) then you'll find out that the issue is in the password complexity.
