### ISSUE TITLE
align right doesn't work 

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#1740]
when i want to publish a post with persian language that is RTL align right doesn't work.
you can see last line that is start from left .
![untitled](https://user-images.githubusercontent.com/20259070/39360558-04b367fa-4a34-11e8-9957-68862dc58d64.jpg)

**Comment by Skrypt** [comment]
That's an issue with the theme itself I think. This theme should reverse the content by using a Flexbox if we are in a RTL culture. This needs to be added to the body of the page like we did in 01.

```C#
System.Globalization.CultureInfo.CurrentCulture.TextInfo.IsRightToLeft
or
HttpContext.Current.Features.Get<IRequestCultureFeature>()?.RequestCulture.Culture.TextInfo.IsRightToLeft
```

**Comment by hishamco** [comment]
Can we add an extension method for that?
