### ISSUE TITLE
How to use Session in OrchardCore.Mvc.Web?

### ISSUE THREAD

**Issue by china-live** [OrchardCMS/OrchardCore#1744]
It is recommended to modify the ModularServiceCollectionExtensions.AddMvcModules return value IServiceCollection in the source code OrchardCore.Mvc.Core to MvcBuilder.
![qq 20180430085505](https://user-images.githubusercontent.com/12002799/39412839-c1c5af5c-4c54-11e8-9f4a-9bb89fa6e399.png)
![qq 20180430085719](https://user-images.githubusercontent.com/12002799/39412840-c83da6c8-4c54-11e8-8965-3bf549d35bfa.png)

**Comment by jrestall** [comment]
You should be able to just call AddMvc() again in your module since it uses the TryAdd pattern when adding services, so won't add anything twice. You don't need to modify ModularServiceCollectionExtensions.cs.

So just do this in your module startup:
```
services.AddMvc().AddSessionStateTempDataProvider();
```

**Comment by dodyg** [comment]
I tried solution but it doesn't really work (using on Beta -3)
