### ISSUE TITLE
SqlException: Incorrect syntax near 'OFFSET'.  

### ISSUE THREAD

**Issue by kookle** [OrchardCMS/OrchardCore#1746]
Invalid usage of the option NEXT in the FETCH statement.

OrchardCore.Contents.Controllers.AdminController+<List>d__20.MoveNext() in AdminController.cs

Line 159.

![image](https://user-images.githubusercontent.com/4568525/39466468-ddab4096-4d31-11e8-97fb-7ae6b87f0ac9.png)

**Comment by sebastienros** [comment]
What version are you using?

**Comment by sebastienros** [comment]
Can someone try to use the pager in the content items page? Just to try to repro.

**Comment by TonyWoo** [comment]
@kookle I think you missed “order by”, when use the offset we need to specify the order field.

**Comment by snoopyfield** [comment]
Try to click Content Items from Admin menu after a fresh setup could repro this issue.

I am using the lastest beta2-5572 package.

**Comment by sebastienros** [comment]
What database where you using?

**Comment by sebastienros** [comment]
I created 15 content items and used the pager without issues, using Sql Server 2016.
Maybe it's your database server that is not supported, please confirm which version you were using, or an old bug in yessql that has been fixed.

Please reopen with more information if you can still repro.

**Comment by DaveEmmerson** [comment]
This is an issue if you're running 2008 R2. The syntax being generated relies on it being 2012+

**Comment by hishamco** [comment]
Just I reopen to check this on 2008 R2, unless YesSQL is generate the syntax rely on 2012+

/cc @sebastienros

**Comment by hishamco** [comment]
Seems I already did a PR https://github.com/sebastienros/yessql/pull/64 long time ago

I think I need to revise it

**Comment by sebastienros** [comment]
I think we already talked about it, and decided to keep the current version compatibility. I don't think it's worth handling older versions for now.

**Comment by DaveEmmerson** [comment]
That's fair enough... 2008 R2 is out of extended support even. We're looking at other options. Thanks for looking again.
