### ISSUE TITLE
Using admin theme in IE11 crashes the browser

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#1747]
Hi,

Using `1.0.0-beta2-5407` 
IE11 `11.371.16299.0` Update `11.0.60` 

The culprit is a Vue model which has a infinite while loop on IE11.

The file is located here ` OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app.js `

Offending snippet:

```
                computed: {
                    isHome: function () {
                        return this.selectedFolder == root;
                    },
                    parents: function () {
                        var p = [];
                        parent = this.selectedFolder;
                        while (parent && parent != root) {
                            p.unshift(parent);
                            parent = parent.parent;
                        }
                        return p;
                    },
                    root: function () {
                        return root;
                    }
                },
```

For some reason on IE11, the window object has a parent property which appears to self reference back to the window object. So that `parents` function effectively is an infinite while loop filling up memory until IE crashes the tab.

Edit:

Looking at the file, I'm not sure if the window object was ever intended to become part of that loop. Regardless though, it does in IE11.

**Comment by matiasmolleja** [comment]
I can repro. Added a PR with your suggestion. Renamed ".parent" to ".parentFolder".
