### ISSUE TITLE
Could add a batch Enable/Disable button on Admin/Features page

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#1752]
just set up a tenant using saas recipe by mistake. Then I found that I need to enable so many features one by one for making my tenant to act as a Blog or Agency.

It would be nice if there is a batch enable button like O1.

**Comment by sfmskywalker** [comment]
Definitely a must.

**Comment by agriffard** [comment]
@sfmskywalker also want some bulk actions for workflows in #1715

**Comment by sfmskywalker** [comment]
Definitely - I added it to the list in #1715 👍
