### ISSUE TITLE
Update HttpRequestEvent with configurability of the SAS token lifetime

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1753]
A time limit should be set by default with a reasonable lifetime.

**Comment by sfmskywalker** [comment]
Working on this.

**Comment by sfmskywalker** [comment]
I could do it completely correct where the created token does not carry a time limit when a "never expire" option is checked, or I could keep it simple and simply do TimeSpan.Max when "never expire" is chosen. 

If we want to be pure however, we should only include a time limit as part of the token if the user provided a time limit. If not, then no time limit should be included as part of the token. We then need to either augment the token with some character (let's say "T" for "time-limited and "P" for "plain token")  so that we know whether or not to use a TimeLimitedProtector or not. Alternatively, I create a "wrapper" object into which I store the user payload + metadata, e.g. information about whether there's a time limit or not. If not, then I ignore the time limit validation.

I'll do the simple implementation first (using TimeSpan.Max), then we can always go the fancy route if we want.

**Comment by sebastienros** [comment]
Be careful with `.Max`, there might be serialization issues. You can use a very big constant value though, one we know we'll be dead before so nobody can blame us if the site is still running.
