### ISSUE TITLE
Problem with validation on Landing Page

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1757]
On a newly setup site.
Go to edit landing page.
Remove a picture from a Team member.
Click publish. There is a warning about a picture being required. Fix the error by adding another image.
Click publish. 
Expected: The content item is saved.
Achieved: There are new warnings about pictures required for all the media fields that are under the team member that caused the first validadation error.

**Comment by agriffard** [comment]
Does this validation error still occurs?

**Comment by matiasmolleja** [comment]
It does. I will look at it.
