### ISSUE TITLE
Leftmenubar:  when collapsed It's too difficult to get to the submenu 

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1759]
Hi,
I've been working on a fix for a quite annoying issue. Please let me know if you think it is OK before I create a PR.

The issue is this:
![diag-movement](https://user-images.githubusercontent.com/2589629/39591786-1c759e8c-4f05-11e8-95e7-2eeaae01248b.jpg)

![before-dropdown](https://user-images.githubusercontent.com/2589629/39591804-296c9fe6-4f05-11e8-8a47-3b4f1df43935.gif)

After the fix it looks like this (red lines are visible now to show the "safe areas"). 

![after-dropdown](https://user-images.githubusercontent.com/2589629/39591925-8ea2e7b2-4f05-11e8-9aa5-0635e3478fc0.gif)

It's done following the solution explained here: http://www.positioniseverything.net/css-dropdowns-red.html
It adds a little bit of complexity to the markup but I think it's worthwhile

**Comment by matiasmolleja** [comment]
Hi Seb,
Sorry, I don't get your comment :)
 
Just to be sure that we are talking about the same issue.

The issue is that when you hover over an icon, "Content" for example, and you want to click on "Queries" you normally go straight to the "Queries" link.  In the exact moment that you hover over the "Content Types" icon that is under "Content ", the submenu suddenly dissappear.
With the little zone added we add a "safe path" to the mouse.

I added an extra "safe area" too to be sure that the submenu only dissapears when the user moves deliberately the mouse out of it.

**Comment by matiasmolleja** [comment]
Now I think I understand what you say. But that will force the user to keep clicking ouside of submenus all the time?
By the way, on mobiles it work that way right now. The user clicks on an icon. The submenu appears. And only dissapear when the user clicks away, or in a different link. No hover on mobile.

**Comment by sebastienros** [comment]
I don't like popups on hovering, as you see it's error prone

**Comment by matiasmolleja** [comment]
So. Do you want I simply remove the hover functionnality?
Click on an icon, display the submenu.
Clicking outside, hides the submenu.

**Comment by sebastienros** [comment]
Yes, click outside, or on a link (which opens the page).

What's your opinion about it, don't just do what I say, I may be wrong.

**Comment by matiasmolleja** [comment]
Yes, you are wrong :satisfied:
No. I think it is a matter of personal preference. I prefer hover, fewer clicks. Better user experience even when this add more code to the theme . When I look at admin templates they tend to use it.
I think that what we have now is OK. Only that it is a little "nervous". So I was trying to polish a little the experience.
Maybe I should create the PR and you can try it. After all I already did the changes in a branch.
