### ISSUE TITLE
Support Request.Form.Keys in Liquid

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1764]
In order to support the following Liquid code:

```liquid
{% for key in Request.Form.Keys %}
<p>{{ key }}: {{ Request.Form[key] }}</p>
{% endfor %}
```

We need to update the global member access strategy for the `FormCollection` type to support this. Currently, it maps every member access to accessing an item in the Forms collection, which prevents us from accessing the `Keys` property. To add support for that, I propose the following change in `RequestLiquidTemplateEventHandler`:

Before:
```csharp
TemplateContext.GlobalMemberAccessStrategy.Register<FormCollection, string[]>((forms, name) => forms[name].ToArray());
``
After:
```csharp
TemplateContext.GlobalMemberAccessStrategy.Register<FormCollection, FluidValue>((forms, name) =>
{
    if(name == "Keys")
    {
        return new ArrayValue(forms.Keys.Select(x => new StringValue(x)));
    }

    return new ArrayValue(forms[name].Select(x => new StringValue(x)).ToArray());
});
```

This kind of does the same thing, except that if the `Keys` property is requested, it returns an array of keys. If anything else is requested, it is interpreted as a request to get a value from the Forms collection itself.

**Comment by sebastienros** [comment]
So if a form contains `Keys` then you can't read it ;)
Isn't there a way that `FormCollection` would return it as the default value, and the indexer would access a property? I think it's doable.

**Comment by sebastienros** [comment]
Or maybe it needs to implement IEnumerable of some sort, I know we support something like this in Fluid, because you actually want to enumerate it to get the list of keys. If it's blocking then we can merge it and file an issue in the meantime.

**Comment by sfmskywalker** [comment]
That sounds like the ideal solution (to be able to just `for` over the `Request.Form` directly. It's not a blocking issue right now, so I'll check to see if I can manage to do it.

**Comment by hishamco** [comment]
@sfmskywalker is there a need to make this open, while there's no blocking from Fluid?!!

**Comment by sfmskywalker** [comment]
Not sure I understand your question. In any case I completely lost sight of this issue so it probably still needs to be fixed if you need to be able to loop over a form collection.

**Comment by hishamco** [comment]
I think there's a merged PR for it

**Comment by SipkeSchoorstraRTL** [comment]
Great, then we should close this issue.

**Comment by sfmskywalker** [comment]
Great, then I'll close this.
