### ISSUE TITLE
Make a better looking SaaS login

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#1767]
This : 

![image](https://user-images.githubusercontent.com/3228637/39666755-d1a8e09e-5076-11e8-9677-666d695f909f.png)

Redirected to this by default : 

![image](https://user-images.githubusercontent.com/3228637/39666819-d4fa3d5a-5077-11e8-8261-2297e175f515.png)

Should be something like this : 

![image](https://user-images.githubusercontent.com/3228637/39666793-8092e5b4-5077-11e8-8576-04a9316ddcb0.png)

@matiasmolleja

**Comment by Skrypt** [comment]
lol yeah I do typos like that 😄

**Comment by sebastienros** [comment]
The idea is to change the SaaS recipe to redirect automatically to /admin if the page doesn't exist. Let's create a feature for that, that won't have any front-end page other than the login page (and password management).

**Comment by agriffard** [comment]
The login page is not using the current theme anymore so I guess we can close this.

**Comment by sebastienros** [comment]
Just to precise that it's about the box/card, and not the moose.

**Comment by Skrypt** [comment]
I'm closing this issue since I think the current design is appropriate. Now that we can use the current frontend theme for the Login we can customize it.
