### ISSUE TITLE
Change Request for Audit Trail - don't leak storage implementation detail

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#178]
As an Audit Trail developer, I would like to be able to control where the records are stored.
Currently in Orchard 1, the Audit Trail Manager leaks its storage mechanism implementation by returning the created record object. Although not a road blocker, it would probably be more hygienic if returned a storage-agnostic object instead.

**Comment by bakintunde** [comment]
This is an old thread but there's no mention of Audit Trail in the roadmap for OrchardCore yet. 
I might be interested in porting it to OrchardCore. It's important for me at the moment.

**Comment by sebastienros** [comment]
Yes, please work on this if you can. I assume the same features could be migrated. You might want to start with a small subset though to get some feedback in case OC provides better ways to do this (it might as a document is represented fully in json).

**Comment by Piedone** [comment]
I don't think this is relevant anymore, right @sfmskywalker?

**Comment by sfmskywalker** [comment]
Yeah, it’s nice to have, but there are probably more important things to do. Let’s close this for now until someone needs it.

**Comment by Piedone** [comment]
I mean, I don't think the issue mentioned here is there anymore.

**Comment by sfmskywalker** [comment]
Oh, sorry. I don’t know but you’re probably right. Haven’t looked at the Audit Trail implementation.
