### ISSUE TITLE
Roadmap is out of date

### ISSUE THREAD

**Issue by mikeytinks** [OrchardCMS/OrchardCore#1781]
The [roadmap](https://github.com/OrchardCMS/OrchardCore/wiki/Roadmap) seems to be out of date.
Beta2 is scheduled for March and RC is May.
Its May now and the current release is still Beta1.

Would be great to have the [RoadMap](https://github.com/OrchardCMS/OrchardCore/wiki/Roadmap) updated with new revised scheduled dates.

Thanks

**Comment by pgy866** [comment]
Don't worry about those details

**Comment by sfmskywalker** [comment]
Yes, we should update the roadmap.

**Comment by sfmskywalker** [comment]
@sebastienros

**Comment by sfmskywalker** [comment]
Suggested timelines:

- Beta 2: June
- RC: August

**Comment by sfmskywalker** [comment]
And I think we should rename *Dynamic Forms* to just *Forms*  (which is the name I used in the *feature/forms* branch: *OrchardCore.Forms*.

**Comment by sebastienros** [comment]
Fixed
