### ISSUE TITLE
Theme inheritance

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1784]
Ex: Create a theme that inherits for TheTheme.
Then, I'd like to add a stylesheet link to a Bootswatch css.
I guess I would have to override the layout.

Is it possible to inherit from a base theme in OC?

**Comment by sebastienros** [comment]
It works. What doesn't work is overriding css and js files like shapes do. You need to update the Layout to be able to do it, which means clone the Layout completely (and lose the inheritance)
