### ISSUE TITLE
Could you use Entity framework Core as orm

### ISSUE THREAD

**Issue by TimWu1104** [OrchardCMS/OrchardCore#1793]
Except create a data module use entity framework core. yesSql not extensive used for me and others

**Comment by Jetski5822** [comment]
In the early days we wanted to use EF.

In O1 we tried, it didn’t work.

In OC, we tried, but the end solution was so complicated and only partially worked.

Some modules do have EF components, but the cms will remain as yessql.

**Comment by Jetski5822** [comment]
Oh, YesSql is sat on top of Dapper, which runs stackoverflow and is super quick
