### ISSUE TITLE
Error when editing menu containing menu items whose content type has been deleted

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1794]
Repro steps:

1. Create a new content type with stereotype = "MenuItem".
2. Add a menu item of that type to a menu.
3. Delete the content type created in step 1.
4. Go back to the menu you created in step 2.
5. Observe a Null Reference Exception.

**Comment by sfmskywalker** [comment]
Looking at the `ContentDefinitionManager`, it deletes all content items referencing the content type being deleted. So probably there should be a content item event handler that handles the Deleted event and update the MenuItemsListParts and remove the deleted item from there as well.

**Comment by sfmskywalker** [comment]
Looking again, I see that actually it is the `ContentDefinitionService` that does the delete. And here's the problem:

- ContentDefinitionService.RemoveType() first deletes content part definitions, then the type definition, and then all content items using that type are deleted *directly using a DB session*

So there are no content handlers being invoked, effectively making it impossible to "clean up" MenuItemItemsListPart content items.

Here's what I think should happen instead in the `RemoveType` method:

1. **First** delete all content items using the type to be deleted.
2. Instead of deleting content items directly using a DB session, it needs to happen via `IContentManager`.

This way, we can now implement a content handler that responds to the content item deleted event and remove that content item from any `MenuItemListParts.MenuItems` collection.

**Comment by deanmarcussen** [comment]
Related https://github.com/OrchardCMS/OrchardCore/issues/1014

Solution on https://github.com/OrchardCMS/OrchardCore/issues/1014
