### ISSUE TITLE
Make IContentDefinitionHandler async

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1795]
Same exercise as with `IContentHandler`.

**Comment by sebastienros** [comment]
You mean this? `IContentDefinitionEventHandler`
Any specific reason?

**Comment by sfmskywalker** [comment]
Right, that one. Well, when troubleshooting some other bug (#1794) I thought that probably we need a content definition event handler to handle content type deletions so that we can delete content items using it. I no longer believe that is the correct fix however, so I would be fine closing this issue. Except of course when the time comes someone needs to handle a content definition event and execute some async code. We could reopen this at that time.

**Comment by jeanbaptistedalle** [comment]
Hi ! We just face the issue mentionned by Sipke, in our app, we need to notify that some changes happened with types or parts by publishing an event in a service bus that other apps will consumme. I will see with my team to push a pull request to make the handlers asynchronous
