### ISSUE TITLE
Lucene index rebuild / reset fails if there are any unpublished content items

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/OrchardCore#1800]
This issue just came up this week after attempting a Lucene index rebuild on a production app. 

If you try to rebuild or reset the index it will fail as soon as it hits an unpublished content item with an "Object reference not set to an instance of an object" error.

I understand that there is still a decent amount of work to be done as there are some "TODO"s here and there in the Lucene implementation code. I just wanted to put this issue on the radar. I will try to get a PR created when I get the chance.

It appears to be caused by the following lines of the LuceneIndexingService. 
https://github.com/OrchardCMS/OrchardCore/blob/0d0a9f018ab7faff03aa64cc22c240db9f078c37/src/OrchardCore.Modules/OrchardCore.Lucene/LuceneIndexingService.cs#L106-L107

contentManager.GetAsync() specifies to get the published version only. Since there is no published version, contentItem is null. On the next line there is an attempt to get the contentType from the contentItem that is null. This causes the object reference exception.

**Comment by sebastienros** [comment]
Easy fix, easy PR?

The same issue we've had on O1 many times ... I will never learn.
