### ISSUE TITLE
ContentTypesDeployment Step fails due to error in view 

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1803]
See below image:

![image](https://user-images.githubusercontent.com/938393/40127405-9a85e208-592f-11e8-8e26-fd8203e4f157.png)

This happens when you add the Content Types deployment step.
I'll send a fix shortly, including a better name. Although I understand the reasoning for the name, "content type" is easily confused with "content definition", so I suggest to rename the step (and relevant files) to just "content deployment step". I would further propose to merge the "all content" step with the "content" step, from where the user can choose to export content of all types, or of a certain type, or maybe even by specifying a query.

**Comment by sebastienros** [comment]
Probably due to the Shape methods changes. You should try the other steps.
