### ISSUE TITLE
Can we associate controllers with features?

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1809]
Currently, we can associate a feature with services by annotating the `Startup` class with a `[Feature]` attribute. Orchard will then only execute those startup classes whose associated features are enabled.

But since controllers are automatically registered (not via a module's startup class), how can we associate controller classes with features (such that the DI container only registers those associated with an enabled feature)?

**Comment by jtkech** [comment]
Yes we can by decorating the controller class with a given `[Feature("TheFeature")]` attribute.

When we compose the `ShellBlueprint` in `CompositionStrategy.ComposeAsync()` we get.

    public class ShellBlueprint
    {
        public ShellSettings Settings { get; set; }
        public ShellDescriptor Descriptor { get; set; }

        public IDictionary<Type, FeatureEntry> Dependencies { get; set; }
    }

    public abstract class FeatureEntry
    {
        public IFeatureInfo FeatureInfo { get; protected set; }
        public IEnumerable<Type> ExportedTypes { get; protected set; } // Your controller type is here
    }

Then using `GetFeatureForDependency()` of the following interface you can retrieve the feature associated with your controller type.

    public interface ITypeFeatureProvider
    {
        IFeatureInfo GetFeatureForDependency(Type dependency);
        void TryAdd(Type type, IFeatureInfo feature);
    }

**Comment by sebastienros** [comment]
Last time we tried (actually @jtkech implemented and tried it) it was working. See what @agriffard did with the Orchard.User.Password feature in the PR

**Comment by sebastienros** [comment]
Still to be tested again, as I don't think we have a test. A functional test would be awesome for this.

**Comment by agriffard** [comment]
@jtkech : If you have time, please join us on Skype for Business in Orchard meeting room, we are making bug triage and PR reviews until 22:00.

**Comment by jtkech** [comment]
Oups, too late. I will install Skype for Business to join the meeting the next week if i can.

**Comment by agriffard** [comment]
@jtkech : Will you join us today for the triage meeting at 21:00?

**Comment by jtkech** [comment]
@agriffard thanks but sorry i couldn't, not the best time for me.
