### ISSUE TITLE
Creating a new tenant with the same database: relation "IX_Type" already exists

### ISSUE THREAD

**Issue by philippe-lavoie** [OrchardCMS/OrchardCore#1812]
I want to have 1000 tenants, I don't want to create 1,000 databases and instead I want to rely on the table prefix. Is that possible ? 

To be fair, I'm not sure why I need so many tables / databases for each tenant. I was assuming that tenantId was a column that could be used to differentiate between all of them.

**Comment by sebastienros** [comment]
As for the TenantId column, this is something that has been asked and we will look into it, it shouldn't be very hard to implement in YesSql. But you should not be afraid of table prefixes, I run a site with 800 tenants in Orchard 1, which had way more tables than Orchard Core.

**Comment by sebastienros** [comment]
Keeping this issue open for the index which doesn't work on PostgreSql

**Comment by sebastienros** [comment]
https://github.com/sebastienros/yessql/issues/107
