### ISSUE TITLE
Tabbed UI for editor views

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#1822]
Not only for widgets displayed in Flows, but for any content item, we should have a way to designate a shape to a tab. The `PlacementInfo` type already has support for this (via the `GetTab` method), but as far as I could tell, there's no UI yet that takes advantage of this. So that would be the scope of this issue.

**Comment by agriffard** [comment]
User Edit could have the user infos in a tab and the roles of the user in another tab.

**Comment by sfmskywalker** [comment]
Yeah that's another nice example of how this would be useful.

**Comment by sebastienros** [comment]
My only issue with tabs is how to handle validation. First, all editors (tabs) should be rendered on the client, but if one field has validation issues, how do we render it? I am sure we can find a solution. Any example from other CMSs?

**Comment by sfmskywalker** [comment]
We could render a validation summary outside of the tabs group?

**Comment by hishamco** [comment]
@deanmarcussen I think you already done this. Am I right?

**Comment by deanmarcussen** [comment]
Yes, unless @sebastienros left it open for a reason. Possibly re the question of validation summary, which is currently rendered outside the tabs group

**Comment by agriffard** [comment]
@deanmarcussen This would need some documentation in https://docs.orchardcore.net/en/dev/docs/reference/core/Placement/
