### ISSUE TITLE
DateTime : local liquid filter

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1831]
I tested this after adding a DateTimeField on a Milestone content type
`{{ milestone.Milestone.DateTime.Value  | local }}`
but this liquid filter doesn't seem to work : the current time is returned, not the one that has been stored.

**Comment by Skrypt** [comment]
TimeZoneFilter.cs change @ line 56 to

return new ObjectValue(await _localClock.ConvertToLocalAsync(value));

**Comment by Skrypt** [comment]
Fixed in 2f9c23d36f6fb2037c23a6acc74e2f06873832ed
