### ISSUE TITLE
Update TheTheme to Bootstrap 4

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1832]
I will submit a PR to migrate TheTheme to Bootstrap 4:
- Change structure and css classes.
- Change alternates for menu and menu items.
- Add a footer.

I'd like that the 3 themes have common Zones:
- Header
- Content
- Footer

at least and may be a zone in the Head to add custom metas, css or script.

Thanks to this, TheTheme would be a good viable minimal theme.
We could also add another recipe with simple content types (Page, LiquidPage)

**Comment by sebastienros** [comment]
And change it to a SaaS theme with controller and view to only support admin access.
