### ISSUE TITLE
how to create json data like menu's json data

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#1841]
{
    "Sector": {
      "Item": {
        "Name": "1",
        "ContemtItemId": "",
        "IsSelect": "true"
      },
      "SectorList": {
        "SecorItems": [
          {
            "SectorItem": {
              "Name": "2-1",
              "ContemtItemId": "",
              "IsSelect": "true"
            },
            "SecorList": {
              "SectorItems": [
                {
                  "SectorItem": {
                    "Name": "3-1",
                    "ContemtItemId": "",
                    "IsSelect": "true"
                  },
                  "SectorList": {
                    "SectorItems": [
                      {
                        "SectorItem": {
                          "Name": "4-1",
                          "ContemtItemId": "",
                          "IsSelect": "true"
                        }
                      }
                    ]
                  }
                },
                {
                  "SectorItem": {
                    "Name": "3-2",
                    "ContemtItemId": "",
                    "IsSelect": "true"
                  }
                },
                {
                  "SectorItem": {
                    "Name": "3-3",
                    "ContemtItemId": "",
                    "IsSelect": "true"
                  }
                }
              ]
            }
          }
        ]
      }
    }
  },
How to Create above json data without ContentPart

**Comment by sebastienros** [comment]
No idea what your issue is, it needs more context.

**Comment by mmdqq** [comment]
![p9 48k f aywm u mvb 1](https://user-images.githubusercontent.com/4881282/40526112-d8c1ace4-6016-11e8-8d84-a5793b07947c.png)
![u e2ve1agk8ti _j21q xh](https://user-images.githubusercontent.com/4881282/40526114-d915d490-6016-11e8-807d-0653c83951dd.png)
I want add Sector to User,but I don't know Save The selected Sector data with current user

**Comment by Skrypt** [comment]
I think he's trying to use the User.Properties JSON object and permit to edit it directly and add data to it. Maybe not the best idea unless it would be a managed C# object.

**Comment by mmdqq** [comment]
yes  I added a User.Propertity :public JObject Sector{get;set;},but I don't konw how create the JObject with Multiple selected data
