### ISSUE TITLE
ContentFields do not work wit fluid templates

### ISSUE THREAD

**Issue by dschmid** [OrchardCMS/OrchardCore#1842]
Namely the TextField but argueably all ContentFields does not provide support accessing the content by fluid templates. (e.g `{{ Model.Field.Text }}` )

According to an answer from Sipke Schoorstra on StackOverflow (https://stackoverflow.com/questions/50484226/a-way-access-field-content-with-liquid/) the Component does not register correctly with liquid.

1. The Registration `TemplateContext.GlobalMemberAccessStrategy.Register<DisplayTextFieldViewModel>();` is obsolete

2. The ComponentField should register like `TemplateContext.GlobalMemberAccessStrategy.Register<TextField>();`

**Comment by sebastienros** [comment]
Maybe there is an issue only with text, I will test.

**Comment by sebastienros** [comment]
For instance I tried it yesterday on the DateTimeField and it was working, I will add functional tests to be sure we don't break anything.

example: `{{ Model.ContentItem.Content.Appointment.Scheduled.Value | local }}`

**Comment by sebastienros** [comment]
I understand the issue now. The view models don't need to be exposed explicitly as they are exposed automatically. At the same time the fields are not, and if the view models don't have the data directly (like Html and DateTime do) then it's useless. What you are suggesting will fix the issue. I will fix it.

**Comment by jtkech** [comment]
In an `Article-TextField.liquid` template, this is working.

    {{ Model.Part.Content.Subtitle.Text }}

But take care, in the blog theme the `Content-Article.liquid` template doesn't render the text field as a shape that you can override. For testing, in this file i needed to add the following to render all the parts / fields as shapes.

     {{ Model.Content | shape_render }}

**Comment by sebastienros** [comment]
Please take a look at the commit that fixed this issue. It's adding documentation for fields and also templates.

**Comment by jtkech** [comment]
Okay cool, here just for infos what was already working before the fix.

Regarding the related SO issue, it is still useful to register `DisplayTextFieldViewModel` so that you can access it from a parent shape e.g `Content-Article.liquid`.

    {{ Model.Content["Article-Subtitle"].Part.Content.Subtitle.Text }}

Ho, just saw that this was also working.

    {{ Model.Content["Article-Subtitle"].Field.Content.Text }}

So, in the `Article-TextField.liquid` template i think this was already working.

    {{ Model.Field.Content.Text }}

**But with the fix of @sebastienros you will just have to do.**

    {{ Model.Field.Text }}
