### ISSUE TITLE
Purpose of User.Create.cshtml is unclear

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1845]
It isn't used anywhere. So why is it there? It's content is the same as the content of User.Edit.cshtml.
As far as I can tell User.Edit.cshtml is a conventional container shape name and you can't build an editor based on User.Create.cshtml so it may confuse people.

**Comment by sebastienros** [comment]
You are probably right, we should be able to delete the `User.Create.cshtml` file since User is an entity and `User.Edit.cshtml` is the main shape template for displaying a user editor.
