### ISSUE TITLE
Suggestion: Make SqlLite the default value at setup

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1848]
I think SqlLite should be selected by default on setup screens. Reasoning:

- It reduces the number of fields on the page, thereby slightly reducing the learning curve for new users
- It's probably the most common option in local dev environments, and it's a safe bet that the setup process is performed most often in local dev environments
- Something has to be picked by default (unless we add an `unselected` option), and I think this is the most logical choice

**Comment by sebastienros** [comment]
Agreed, I also mentioned that in a meeting.

**Comment by sebastienros** [comment]
Also, the table prefix should not be displayed in this case.

**Comment by paynecrl97** [comment]
I’ll make the changes and push up
