### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by TonyWoo** [OrchardCMS/OrchardCore#1851]
After created a new user and assign the role "Author" to this user, user can see below menus.

![image](https://user-images.githubusercontent.com/689710/40570480-fcd28728-60bd-11e8-9d8d-73ca52f3aca2.png)

If clicked any one of the menu items, it show the error "An error occured while executing this request". I'm in dev branch. Thanks.

**Comment by sebastienros** [comment]
We need to check for more permissions before rendering the menu items.

**Comment by agriffard** [comment]
The menu checks the Permissions.EditOwnContent permission, that an Author has.

but then, the Create content page requires the Permissions.EditContent permission.

In OrchardCore.Contents\AdminController, the Create method should allow the Permissions.EditOwnContent or the authors will never be able to create a content.

For the same reason, the CreateAndPublishPOST should allow the Permissions.PublishOwnContent.

**Comment by sebastienros** [comment]
Let's look at what O1 is doing. I think we added CreateContentPermissions for some related reason.

**Comment by agriffard** [comment]
In Content/Permissions.cs, EditOwnContent is implied by EditContent : https://github.com/OrchardCMS/OrchardCore/blob/cf45ad0a1044694731560926dc19d1c34e53d9b2/src/OrchardCore.Modules/OrchardCore.Contents/Permissions.cs#L15

so it should work (or there is something not working in OC), but I don't really understand where do we check that the current user is the owner when it is edited and published in AdminController.EditAndPublishPOST :
https://github.com/OrchardCMS/OrchardCore/blob/cf45ad0a1044694731560926dc19d1c34e53d9b2/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/AdminController.cs#L440

Looking in O1, it seems that there are classes inheriting from IAuthorizationServiceEventHandler, like :
https://github.com/OrchardCMS/Orchard/blob/4bf5c8ee4f6f69e57d355d85c99cd11f2ee9835e/src/Orchard.Web/Modules/Orchard.ContentPermissions/Security/ContentPermissionsPartAuthorizationEventHandler.cs#L106
but it is currently commented, so not effective in OC: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Security/AuthorizationEventHandler.cs
