### ISSUE TITLE
How to save the custom User.Propertie

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#1852]
![p9 48k f aywm u mvb 1](https://user-images.githubusercontent.com/4881282/40571616-9bbcb01a-60ce-11e8-8d6f-c35a0628194c.png)
I added Sector to User.Propertie,but I don't know How to save the selected Sector data to current user

**Comment by Skrypt** [comment]
duplicate #1841

**Comment by mmdqq** [comment]
Thank you ,I'm trying
