### ISSUE TITLE
Function Recommendations: Enhanced Mailbox Modules

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1863]
Function Recommendations: Enhanced Mailbox Modules
Are you planning to enhance the basic sending and receiving management functions of the mailbox module?

功能建议：邮箱模块功能增强
是否计划增强邮箱模块的基本收发等管理功能呢？

![2](https://user-images.githubusercontent.com/28694676/40584873-7e0850de-61db-11e8-9a90-f7cccbc632be.gif)

**Comment by pgy866** [comment]
@sfmskywalker Thank you so much for all the contributors, and I don't write code (I'm not a programmer)
I'm sorry I can't contribute,Thank you guys.

**Comment by sfmskywalker** [comment]
On the contrary, you're an invaluable contributor too by using the platform, providing feedback and raising issues!

**Comment by Skrypt** [comment]
I'm sorry but what is this mail client that is showed ?

**Comment by pgy866** [comment]
Sending and receiving emails and records?

**Comment by Skrypt** [comment]
I mean what is the software displayed in your screenshot.

**Comment by pgy866** [comment]
@Skrypt      It is this      http://www.kooboo.com/
Desktop Version

**Comment by sebastienros** [comment]
We won't do this, but we would be supportive of someone implementing it externally.

**Comment by pgy866** [comment]
Thank you!
