### ISSUE TITLE
Basic data access problems and workflows module

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1865]
You can easily break things because the data access in general could be better.

1. In /Admin/Workflows/Types/Edit/1021210 there's an NRE.
2. Or in WorkflowController.Details: `var workflow = await _workflowStore.GetAsync(id);` calls a `_session.GetAsync<Workflow>(id);` there's a null check `if (workflow == null)` but it's useless because if you give it an id which is an existing document's id but not a workflow's (let's say it's a User ID) you got an empty workflow (because it's casted but what you really have is that document with the given id) and if you display the editor then save it then the User will be overridden!
3. The same applies to the WorkflowTypeController.Delete action, there's a null check but it's useless, one with a ManageWorkflows permission could wipe the whole db by replacing the id in the delete button.
4. I'm sure there's much more of these because devs assume that data access services are better than they are. I know they are not bad just too generic but then we probably need one more layer above YesSql?

We need an official way to type safely get items/Entities (with content items you can check the content type).

I bumped into this while trying to display entity editors in the front end.

**Comment by sebastienros** [comment]
2. sounds like a bug

Feel free to file bugs in yessql too if you think there are issues. And there are a lot I am sure, it's sad but that the reality of using new products.

**Comment by sebastienros** [comment]
I fixed it, you can do a PR to update to `beta-1199` all yessql packages.

**Comment by alberthajdu** [comment]
I'll do it but beta-1199 isn't available on NuGet yet.

**Comment by sebastienros** [comment]
It's available on myget, just change the version numbers on the dev branch and it should work.

**Comment by alberthajdu** [comment]
Nope, changing the version number is not enough.
The NuGet.config doesn't contain your yessql feed and it's not available from the gallery (https://www.myget.org/gallery). Maybe it's private?

**Comment by sebastienros** [comment]
> The NuGet.config doesn't contain your yessql feed

it's referenced as a proxy from the orchard core dev feed, you don't see it but it's there, I will try to see what's the issue

**Comment by sebastienros** [comment]
I fixed it. It's possible that I never merged the PR I had created, and no packages were published on myget. My bad.

**Comment by alberthajdu** [comment]
I checked it and get is type safe now, thanks. Howewer 1. is still needs to be fixed so I'll open a new issue for that.
