### ISSUE TITLE
Ability to disable cache during development

### ISSUE THREAD

**Issue by d-miles** [OrchardCMS/OrchardCore#1868]
Would like to see the ability to disable caching during development, either with a setting or even a variable on the Layout or something like that.

Issue is that I have a landing page with lots of cached pieces, each having a different context as well as different expirations. If I want to modify the markup of these pieces, I have to find a way to invalidate them all, or change the name and the expiration, then change back later.

Also one thing I've noticed is that if I have a named cached block with a expiration:
```
{% cache "my-cache", expires_after: "06:00:00" %}
Hello world
{% endcache %}
```

I can't invalidate this block by setting `expires_after` to a lower value, like `00:00:01` (by the way `00:00:00` is invalid, but is valid for `{% shape %}` caching, may want to make it consistent), unless I change the name of the cached block. Basically, I think that maybe the cached block's name should include the expiration or depend on the expiration so that if I change it, it resets it or at least adheres to the new expiration?

Would like to have some kind of discussion regarding this!

**Comment by sebastienros** [comment]
/cc @paynecrl97 

I think it's a very good idea. Not sure how it should be designed, maybe like we handle CDN in O1, with a setting that would have these:

- Enabled (cache is enabled)
- Disabled (cache is disabled)
- Production only (enabled in production, disabled in development)

Also should it apply to all cached data (fragments, output cache), I think so, but other cached business data, just html cache.

This should be relatively easy to implement. As a setting on the `ISite` object. Any html caching module should take the value into account.

**Comment by paynecrl97** [comment]
Agree, and yeah- it should be easy enough to do.

Maybe the three options should be

- Enabled
- Disabled
- From Config (the config file determines whether or not it's enabled)

**Comment by paynecrl97** [comment]
FYI as a workaround- the `{% cache ... %}` tags are designed to work with or without the dynamic cache feature enabled.

In theory, you should be able to just disable that feature locally and the tags will just fall through as if they weren't there.
