### ISSUE TITLE
How to target a specific part to be rendered in a different content zone in O2 ?

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#1869]
I would like to render TitlePart in a different content zone , like in O1.
Here are the steps I am taking :
1. In custom theme added an override file Content.cshtml 
2 . Added a new content zone under Model.Header as so :
```	
	@await DisplayAsync(Model.SubHeader) 
```	
3. In placement.json added : 
```
	"TitlePart": [
    {
       "display-type": "Detail",
       "place": "SubHeader:5"
     } ]
```
But I don't see the TitlePart rendered in SubHeader zone.
Am I doing it wrong ?
My second question is how to target the titlepart to be rendered in custom zone only for specific ContentType ?
This was also supported in O1 in placement.info

**Comment by sebastienros** [comment]
What is not supported today is to filter by content type, but this example should work, so it must be broken right now.

However the recommendation is to go through a template where you can do it now.
From the template you can hide specific shapes, and render them elsewhere. 

We still need to look into why it doesn't work though, please try to debug it.
