### ISSUE TITLE
OrchardCore.DynamicCache : Use IDistributedCache directly in DefaultDynamicCacheService

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#1872]
Now that IDistributedCache is set as a Singleton we don't need anymore to create a separate singleton instance of the IDistributedCache through IDynamicCache and DefaultDynamicCache.
@paynecrl97

**Comment by sebastienros** [comment]
We do, the goal is to be able to replace only this part where cached fragments are stored.
