### ISSUE TITLE
jqBootstrapValidation is obsolete

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#1876]
Our template are using the jqBootstrapValidation library, probably because of StartBootstrap templates, but this library is using a wrong email validation. 

c.f. https://github.com/ReactiveRaven/jqBootstrapValidation/issues/185

**Comment by hishamco** [comment]
@agriffard after the updates that you made on the templates are we still rely on jqBoostrapValidation?!!

**Comment by agriffard** [comment]
We are not using the contact_me.js from SB.Agency.
