### ISSUE TITLE
Tenant setup page can fail to load

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1886]
I noticed this while working on #1848:

Create a new tenant, pick SQLServer as the DB type, don't enter a connection string, save.

The tenant setup page now fails (it expects a connection string)

**Comment by sebastienros** [comment]
The tenant page should require the connection string if the provider needs one. I tried other ways but it didn't work.

**Comment by paynecrl97** [comment]
Also- I don't think we should be exposing the connection string in a hidden field on the setup page.

**Comment by sebastienros** [comment]
Right. It should stay in the shell settings. We might need to treat Unitialized specifically, and then only take it into account when it's "Initializing". I will take care of it.
