### ISSUE TITLE
Preview when using trumbowyg editor is out of sync

### ISSUE THREAD

**Issue by chillibug** [OrchardCMS/OrchardCore#1889]
When I edit content in the trumbowyg editor and click preview, the preview window is missing the last character.

Tested on Orchard Core v1.0.0-beta2-5965

Steps to replicate issue:
- From the admin area click 'New' then 'Page'
- Give page a title
- add a paragraph widget 
- type abc in to the editor
- click 'Preview'

When the preview page loads the character c is missing

I can go back and edit but the last character edit is always missing on preview.

**Comment by Skrypt** [comment]
I confirm I can repro

**Comment by agriffard** [comment]
What I can reproduce is that the preview is 1 letter late compared to what is typed in the editor.

**Comment by chillibug** [comment]
Yes and just to note the raw HTML widget works as expected

**Comment by matiasmolleja** [comment]
I think its fixed now with #1948 @sebastienros
