### ISSUE TITLE
is there a free shopping module for orchard?

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#1890]
is there a free shopping module for orchard? Or is it possible to you start a new project based orchard core for shopping?

**Comment by khoshroomahdi** [comment]
something like Woocommerce in Wordpress.

**Comment by khoshroomahdi** [comment]
Or is there anyway to convert Wordpress module to orchard core?

**Comment by psijkof** [comment]
SimplCommerce might be a good candidate for a orchard module https://github.com/simplcommerce/SimplCommerce?

**Comment by bleroy** [comment]
https://github.com/bleroy/nwazet.commerce It's Orchard 1, not Core, but we would welcome a Core branch...

**Comment by Skrypt** [comment]
I'd be interested in contributing on this. I've worked with Stripe on my last website. I know the API. Though I've never really worked with Nwazet extensively to understand how it works. I've started looking at it 2 weeks ago and there's a lot to do to migrate it to .NET Core "I think".

**Comment by bleroy** [comment]
I created this issue on Nwazet Commerce to track this: https://github.com/bleroy/Nwazet.Commerce/issues/148

**Comment by agriffard** [comment]
https://github.com/OrchardCMS/OrchardCore.Commerce
