### ISSUE TITLE
Allow shell settings to be stored in a location other than App_Data

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1893]
In O1 we can use Azure blob storage to allow for sites to be hosted in a multi node environment. We need something similar for OC.

A few options for storage:

- Azure blob
- Azure key vault
- SQL DB
- Redis
- ... and a tonne of other options

I think we should support at least one. I imagine it working along the lines of:

```
services.AddOrchardCms();
services.WithAzureKeyVaultShellSettings();
```

I like the idea of supporting key vault instead of blob storage because a) that's what it's designed to do; and b) we can store the connection string as a secret.

**Comment by sebastienros** [comment]
You can already change the folder name in case it helps.

Also ideally it could use a single file/blob, for performance reasons.

**Comment by gyanendrarijal** [comment]
@sebastienros can you please explain a bit how we can achieve this in OrchardCore?

**Comment by jasonchester** [comment]
PR #5678 - Database and Azure blob shells configuration has been merged to dev. Should this issue be resolved?

@deanmarcussen @jtkech

**Comment by jtkech** [comment]
Yes we can close it, thanks
