### ISSUE TITLE
Update ImageSharp

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/OrchardCore#1894]
There's a bug in the current version of ImageSharp that can be triggered if a host app (or third party module) meets certain criteria: https://github.com/SixLabors/ImageSharp/issues/569.

I tested the latest dev build of ImageSharp and the problem is fixed as the linked issue suggests.

We can either update to the latest dev nightly build, or we can wait until the next beta release of ImageSharp is released before we update.

**Comment by sebastienros** [comment]
We are already pointing to their myget feed, you can just update the version. We will ensure we are not using anything from myget before merging in master. Last time we just created our own package on nuget (with an OrchardCore prefix).

**Comment by chillibug** [comment]
I think the following is cause by this issue

I ran through the [Orchard Core and Service Fabric]( http://www.ideliverable.com/blog/orchard-core-and-service-fabric/introduction) tutorial. After setting up the agency site on the recipe page, I get the following error:

```
An unhandled exception occurred while processing the request.
FileLoadException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
SixLabors.ImageSharp.Processing.Dithering.KnownDiffusers..cctor()
```

To me it looks like the same error reported in  [SixLabors/ImageSharp#569](https://github.com/SixLabors/ImageSharp/issues/569), but please let me know if I should raise this as a new issue.
