### ISSUE TITLE
ummm... where's the dashboard, please?

### ISSUE THREAD

**Issue by kimballjohnson** [OrchardCMS/OrchardCore#1898]
Thrilled to see you migrated to the core.

but when I build and run, I get the nice design page (seen that one before somewhere), but I can't get the dashboard or the reported 'admin link'. 

please hurry, I can't wait to get down to unfolding your new abstractions!

Thanks,

**Comment by sfmskywalker** [comment]
What's the reported admin link pointing to?
You should be able to get to the dashboard by navigating to /admin.

**Comment by kimballjohnson** [comment]
Yes, thank you. That was it.
