### ISSUE TITLE
Admin: Edit content layout

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1907]
In an admin edit page, the layout could display the actions on the right if the screen is large enough.

We could simply change OrchardCore.Contents\Views\Content.Edit.cshtml and replace the classes by Bootstrap grid classes with `row`, `col-xl-9` for the primary local zone and `col-xl-3` for the secondary actions.

![media](https://user-images.githubusercontent.com/703248/41191619-a32acfa6-6bf2-11e8-9be7-c3e429778b8f.gif)

**Comment by agriffard** [comment]
The `Sidebar` local zone could be put on the left of the screen and could be used in admin pages that need to display additional information on the left (think about an inner menu for example).

One use I have in mind would be to display the filters of the page that lists the content items on the left of the page if it is large enough.

The column sizes could adapt themselves depending on if the local zones are null or not:
Content + Actions => col-9 | col-3
Sidebar + Content => col-3 | col-9
Sidebar + Content + Actions => col-3 | col-6 | col-3

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1670

If not wide enough, when the page is not high enough,
fixed Will the footer be better?

**Comment by sebastienros** [comment]
How does it look like in wordpress when it's minimized

**Comment by agriffard** [comment]
Reminder: Let's decide how we want the actions buttons to be displayed on Create/Edit page depending on screen size.

**Comment by ns8482e** [comment]
In PR #4870, changes has been made to have Sidebar CSS classes responsive.

**Comment by ns8482e** [comment]
Related #4955

**Comment by agriffard** [comment]
See #6509

**Comment by hishamco** [comment]
@agriffard I will close this for now, because what you showed in the previous screenshot can be done using the PR #6509
