### ISSUE TITLE
Update OrchardCore.Modules documentation

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1908]
app.UseModules() => app.UseOrchardCore();

**Comment by agriffard** [comment]
Still needs some adjustements :
- AddModuleServices does not exist anymore
- Remove references to Module.txt

**Comment by agriffard** [comment]
@Jetski5822 Could you update this Modules documentation?

**Comment by agriffard** [comment]
I updated the modules documentation but its content can be considered of the beginning of a 'Getting started' topic and should have its own page, while this one should appear in the 'Core modules' section.

**Comment by Skrypt** [comment]
We should copy some content from https://github.com/Skrypt/OrchardCore.Samples README file.

**Comment by agriffard** [comment]
Yes, but in another page. 

If you want, you can create a 'Getting-started.md' in src/docs and put images in src/docs/assets.
Add it to the mkdocs.yml below the 'About Orchard Core' node.

**Comment by Skrypt** [comment]
Added here https://github.com/OrchardCMS/OrchardCore/blob/doc-getting-started/src/docs/getting-started.md

**Comment by agriffard** [comment]
Even if the dotnet new templates are merged, I think we need to explain how you can quickly start from zero.
I will explain it in #1999.
Your doc will be more interesting in a Readme in the Template project.

**Comment by Skrypt** [comment]
Let me delete my new branch and do a PR against your dotnetNewTemplates branch then.
