### ISSUE TITLE
Tenant setup with sqlite preselected shows connection string.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#1925]
After having created a tenant with sqlite, when doing a setup on this tenant where sqlite is pre-selected, the connection string is showed up. I will fix it as i have time.

**Comment by agriffard** [comment]
I tested a tenant creation with sqLite: 
It is shown but as the select is disabled, the value is not transmitted and the setup fails saying no Provider is selected.

**Comment by agriffard** [comment]
Fixed in #1940
