### ISSUE TITLE
GDPR Support

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#1927]
Given that [GDPR support has been added to the asp.net core 2.1](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1), this feature could become an Orchard Core feature.

Some feature ideas that could be provided by the feature:

- Out of the box cookie consent view based on the default aspnet core version
- Provide personal data page on the user account management page like the OpenId accounts management page.
- Download user data document that contains data associated to a user.
- Configurable delete user feature that can delete a user and all content, or maybe reassign content to a default "forgotten user" to leave content behind. Possibly configurable per content type?

**Comment by giannik** [comment]
I like it!.

**Comment by alberthajdu** [comment]
Supporting GDPR out of the box would be really attractive for EU/enterprise clients. And these features should be basic anyway so I think it's worth a module.

**Comment by agriffard** [comment]
Related to #3580

**Comment by hishamco** [comment]
Duplicate of #3580
