### ISSUE TITLE
NRE in workflow type edit

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1932]
In /Admin/Workflows/Types/Edit/1021210 there's an NRE.

I buped into this while investigating data access problems here https://github.com/OrchardCMS/OrchardCore/issues/1865 There's a lot of code in the workflow module and can break easily.

**Comment by sebastienros** [comment]
How can we repro it, the link seems to be just an edit link to a random workflow identifier.

**Comment by alberthajdu** [comment]
Exactly, just use a random non-existent id.
