### ISSUE TITLE
Setup fails when using sqlite

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1942]
Hi,
Setup page does not submit the form anymore if sqlite is selected.
I think it's because the connection string input is not available in that case?
@jtkech   @sebastienros

**Comment by sebastienros** [comment]
Works for me. Pull the latest dev. Also functional tests worked fine.

**Comment by matiasmolleja** [comment]
I'm sorry. It works.

It was a js warning complaining about the input with the id "ConnectionString" not being focusable.
But I tried again and its working.
Maybe a cached javascript file on my pc?
