### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [OrchardCMS/OrchardCore#1943]
Greetings @orchardcms ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by agriffard** [comment]
I am not a Designer but here is what I've done a few weeks ago:
![orchardcore-logo](https://user-images.githubusercontent.com/703248/41318618-3ab44782-6e99-11e8-9c7a-84d82a667041.png)

![orchard-core-logo-1](https://user-images.githubusercontent.com/703248/41318638-4218223c-6e99-11e8-80d3-42277fbb9b3d.png)

![orchardcorelogosquared](https://user-images.githubusercontent.com/703248/41318645-4d226430-6e99-11e8-8c9e-e1cd46abce30.png)

I have been inspired by what has been done for the ASP.NET Core logos.
https://github.com/campusMVP/dotnetCoreLogoPack

Again, I am not good at designing logos and I guess we will need are high quality graphics, svg, ....
https://github.com/OrchardCMS/OrchardDoc/tree/master/docs/Attachments/walkthroughs : OrchardLogos.zip

In the end, we will also need small logos for the admin (header/footer) and favicons.

I remember Orchard 1 had those kind of assets:
![orchardlogos](https://user-images.githubusercontent.com/703248/41319019-bb7f2052-6e9a-11e8-8222-823d570a06be.png)

**Comment by sebastienros** [comment]
@LuigiBaute no need to close this, all contributions are welcome. If you have ideas to make it better you can always share them, like @agriffard shared his.

**Comment by LuigiBaute** [comment]
Great @agriffard  , @sebastienros ,

Before proceeding towards the logo-making process I'll give you some questions that would help us create a wonderful logo that suits this project best.

What's the name that should be displayed on the logo/icon ?

What's the purpose/goal of this project ? (details of the project can work too)

What's the message you would like the logo/icon to transmit?

I'll be looking forward to your reply! hopefully something good can come out of this work!

**Comment by agriffard** [comment]
Closed in favor of #6279
