### ISSUE TITLE
Media grid layout is broken when using Media Azure BlobStorage

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#1953]
Hi,
When using BlobStorage the images don't resize based on the querystring parameters:
example:  "image.jpg?width=240&amp;height=240".
The images are returned in full size. My layout on the admin is not ready for that and the layout is broken.
I'm preparing a PR for fixing the layout issue, but I'm not sure how to fix the real issue of the images not being resized when using blob storage. I will file another issue for that.

**Comment by sebastienros** [comment]
Don't patch your module. We'll take the time to fix the Azure storage one.

**Comment by sebastienros** [comment]
ok, as long as it's safe

**Comment by sebastienros** [comment]
I think the idea with azure blob storage is that when there is a transformation to apply then we need to process it by reading the file and return the local content instead. I have to check how we expose the urls when rendering the media items. Maybe using the `GetPublicUrl` (or whatever it's called) from the storage provider is not the correct way in this case. I'll keep this issue open for tracking.
