### ISSUE TITLE
Login provider

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1958]
Login.cshtml has been modified recently.

It now displays this button: `Identity.TwoFactorUserId`

![capture](https://user-images.githubusercontent.com/703248/41371281-271f8dc4-6f4a-11e8-895e-6ef9293315d5.PNG)

When you click on it, it redirects to `https://localhost:44300/Account/Login?ReturnUrl=%2FOrchardCore.Users%2FAccount%2FExternalLoginCallback`

How is it supposing to behave?

**Comment by sebastienros** [comment]
Saw that too, and tried to fix it but couldn't, it's still redirecting to a not found page.
Also I would have expected that there is not provider, so this would not show up by default.
/cc @MichaelPetrinolis

**Comment by MichaelPetrinolis** [comment]
Should we ignore it in the list of providers we display at login.cshtml or we should not register it in the first place? 

It is registered in the ConfigureServices method of [OrchardCore.Users.Startup,] https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/Startup.cs) but seems that we don't use it anywhere in the code...

`
.AddCookie(IdentityConstants.TwoFactorUserIdScheme, IdentityConstants.TwoFactorUserIdScheme, options =>
            {
                options.Cookie.Name = IdentityConstants.TwoFactorUserIdScheme;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
            });
`

**Comment by sebastienros** [comment]
If it's not used by default, then it should in a separate feature. But honestly I have no idea what it is and what it's for.

**Comment by MichaelPetrinolis** [comment]
Me neither, I saw this [Passwordless Authentication](https://www.scottbrady91.com/ASPNET-Identity/Implementing-Mediums-Passwordless-Authentication-using-ASPNET-Core-Identity) blog post that uses it in order to keep some claims for the authenticated user. I will make a PR to remove it from the Users Startup.

**Comment by PinpointTownes** [comment]
@sebastienros pinged me about this issue and I believe the right fix simply consists in replacing `.AddCookie(IdentityConstants.TwoFactorUserIdScheme, IdentityConstants.TwoFactorUserIdScheme, options =>` by `.AddCookie(IdentityConstants.TwoFactorUserIdScheme, options =>` to ensure no display name is associated with the 2-FA scheme used by Identity (so it doesn't appear in the schemes list).

**Comment by sebastienros** [comment]
c.f. what Identity is doing by default: https://github.com/aspnet/Identity/blob/dev/src/Identity/IdentityServiceCollectionExtensions.cs#L72-L76

We need to check (and understand, and write down) why we can't use the default `AddIdentity` even if we know we have to call so extra custom services and options. It used not to work, but it might work fine now (2.1).

**Comment by MichaelPetrinolis** [comment]
@PinpointTownes good catch, in my eyes it seemed exactly the same as the previous .AddCookie statement yesterday night!

Regarding the .AddIdentity , I suppose that the UserIndexProvider needs a Singleton registration for ILookupNormalizer and the AddIdentity method registers it scoped. I modified the #1961 PR to use the AddIdentity and it seems ok
