### ISSUE TITLE
NLog not working

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#1972]
There is no log file generated.  However relevant logs can be seen in console.

**Comment by jtkech** [comment]
Just tried this in the media controller index action

    _logger.LogError("TEST");

And i got

    2018-06-15 02:30:09.3675|None|0HLEIARQ5433I:00000006||OrchardCore.Media.Controllers.AdminController|ERROR|TEST

**Comment by sebastienros** [comment]
@awyl it might be that your console logging and NLog have different min level of logging?

**Comment by awyl** [comment]
So I found out more about issue.  The log actually went to another location in my case.

I had this.
```xml
<target xsi:type="File" name="usernameCheckLog" fileName="${var:configDir}/App_Data/Sites/${orchard-tenant-name}/config/usernamechecklog.txt"
       layout="${shortdate} ${message}" />
```

I was looking at the tenant folder, but it actually log to `None` folder.   `${orchard-tenant-name}` returns `None`.

@jtkech 
Your example shows "None" too?

I tried, but couldn't repo using the source code.  Source code version seems fine.  Did I miss a package??  It used to work before updating to latest bit.

**Comment by jtkech** [comment]
Okay, i got it. We have the following.

    // If there is no ShellSettings in the Features then the log is rendered from the Host
    var tenantName = context.Features.Get<ShellSettings>()?.Name ?? "None";

But now in the `context.Features` we don't have a `ShellSettings` anymore, we have a `ShellContext` which has a `ShellSettings` property. I will fix it tomorrow night.

**Comment by awyl** [comment]
Since it is a simple change.  I will send a PR.
