### ISSUE TITLE
Error in Media picker

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1978]
When I create a content with a MediaField, there is a js error when I open the modal to select a media:
`[Vue warn]: Property or method "smallThumbs" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.`

**Comment by agriffard** [comment]
There is a similar warning when I want to create a new Page:
`[Vue warn]: Property or method "errors" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.`

**Comment by matiasmolleja** [comment]
Sorry, I can' repro.
Can you tell me how do you try it?
I cloned the repo, and run from VS. Debug and Release modes.

**Comment by agriffard** [comment]
OK, I refreshed the browser cache (but I was sure I had done it the first time), retried and it works.

Just one remaining error: It tries to load Admin/Contents/ContentTypes/Images/drag-thumbnail.png

In the Create page for example.
I guess it works for you in the Assets page but when it is executed elsewhere it doesn't. 

This code must be the cause:
`self.dragDropThumbnail.src = '../Images/drag-thumbnail.png'`

**Comment by matiasmolleja** [comment]
Yes I saw that. At the moment I was not sure of the best way to reference the png from the module to be used elsewhere. And later I forgot to fix it. 
I will look at it. Maybe it's better when beta2 is released to avoid breaking anything now.

**Comment by matiasmolleja** [comment]
Fixed on #2013

**Comment by agriffard** [comment]
Please @matiasmolleja : Do not close issue like this. 
Add a comment in your PR `Fixes #IssueID` and when it will be merged, it will be closed automatically:
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by matiasmolleja** [comment]
Nice. Thank you.
