### ISSUE TITLE
Update the applications management UI to support setting scope permissions

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#1981]
Currently, the OpenID server feature is configured to ignore scope permissions. Once the management UI is updated to allow defining the scopes an application is allowed to request, we should enforce scope permissions.

**Comment by PinpointTownes** [comment]
I added the scopes management UI some time ago, so this can now be implemented.

Things to do as part of this task:

  - Remove https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs#L108.

  - Update https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ApplicationController.cs to support selecting scopes, that can be retrieved by resolving `IOpenIdScopeManager` and using `ListAsync()`. It should work pretty much like roles, that are selected using good old checkboxes.

Scopes permissions are granted by adding a permission named `OpenIddictConstants.Permissions.Prefixes.Scope + "scope_name"` to `descriptor.Permissions`.

**Comment by PinpointTownes** [comment]
Note: it should ideally be done for RTM, as changing that later will be a functional breaking change.

**Comment by hishamco** [comment]
An updates on this?

**Comment by Skrypt** [comment]
It's up for grab and I don't think anyone took it so far...

**Comment by timlunev** [comment]
@kevinchalet Could you clarify:

- Do you expect to see anything like this? 
- If your answer is yes about the UI, do we expect to have anything like A-Z amount of scopes? 
- Are there any requirements or restrictions for the visibility of the checkboxes?

![image](https://user-images.githubusercontent.com/14817393/77574832-4c95cb80-6edb-11ea-8fa5-a428ed4a4331.png)

**Comment by kevinchalet** [comment]
Woooops @timlunev, for some reasons, I missed your reply. Sorry for that 😭 

If you're still interested in contributing:

> Do you expect to see anything like this?

Yeah, it's perfect.

> If your answer is yes about the UI, do we expect to have anything like A-Z amount of scopes?

Do you mean a select all/none option?

> Are there any requirements or restrictions for the visibility of the checkboxes?

Nope 😃

**Comment by timlunev** [comment]
@kevinchalet yes I'm still interested, thank you for the answer, it is clear now. I'll add the changes in few next weeks

**Comment by jptissot** [comment]
@kevinchalet @timlunev Any updates on this one ?

**Comment by timlunev** [comment]
@jptissot nope, there is no any.

**Comment by kevinchalet** [comment]
@jptissot @Skrypt and I chatted about this item and he seemed interested to give it a try 😃

**Comment by Skrypt** [comment]
When I'm done with 3 other PR's. If someone is faster than me to do the fix then go on 😄

**Comment by Tsjerno** [comment]
I will add the scopes, working on improvements of openID

**Comment by Tsjerno** [comment]
How to deal with the standard scopes like email, roles? Changing the code, breaks my current applications where these scopes are used. Or does everyone needs to add this scopes manually to the scopes list?

**Comment by kevinchalet** [comment]
Standard scopes can be created using the scopes controller. OpenIddict itself doesn't make any difference between "custom" scopes and "standard" ones, except `openid` and `offline_access`, that are a bit special.

**Comment by Skrypt** [comment]
Can we close this now that #7938 is merged?
