### ISSUE TITLE
Remove OrchardCore.OpenId.EntityFrameworkCore and OrchardCore.OpenId.Core.EntityFrameworkCore

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#1982]
Now that we support tenant services registered from the main host `Startup`, we should remove the `OrchardCore.OpenId.EntityFrameworkCore`  module and introduce new extensions in `OrchardCore.OpenId.EntityFrameworkCore.Core` to allow registering the EF Core stores.

**Comment by PinpointTownes** [comment]
New plan: remove the two EF Core packages (the core stuff and the module) and update the managers to support non-OrchardCore stores, which will allow using any provider supported by OpenIddict without requiring any OC artifact (which includes EF 6, MongoDB and NHibernate).

I'll do that as part of 1.0 RTM.

**Comment by MatthijsKrempel** [comment]
This would be a most welcome feature

**Comment by hishamco** [comment]
@PinpointTownes I think it's the time for doing this

**Comment by PinpointTownes** [comment]
I demonstrated how to do that in the OpenIddict 3.0 migration PR: https://github.com/OrchardCMS/OrchardCore/pull/4720. I just need to find some time to extract these changes for the current version (no promise, I'm quite busy these days).

**Comment by MatthijsKrempel** [comment]
I'll have a look Kévin.
________________________________

**Comment by PinpointTownes** [comment]
@MatthijsKrempel thanks, much appreciate. For that, you'll need to:

  - Remove the two OpenID EF Core packages (core+module).

  - Port the cast-based changes from the 3.0 PR. E.g: https://github.com/OrchardCMS/OrchardCore/pull/4720/files#diff-acb7ff72bffc469850e6e8f0b9c83102R47. Ignore the `Task` -> `ValueTask`/`Task<ImmutableArray<T>>` -> `IAsyncEnumerable<T>` changes, they are for 3.0-only.

  - Add the 4 store resolvers I introduced here: https://github.com/OrchardCMS/OrchardCore/pull/4720/files#diff-31588d5aab1210ef6af833abf7953a72

   - Add these extensions: https://github.com/OrchardCMS/OrchardCore/pull/4720/files#diff-629d2d6c77d4bc16bbf34c0adc99e6f5R14

  - Update the OpenID module to use them: https://github.com/OrchardCMS/OrchardCore/pull/4720/files#diff-b79c33e5d2e5eb76a9b2fa9caa3b82e3R45

**Comment by MatthijsKrempel** [comment]
@PinpointTownes I'm swamped at work, so I will have to break my promise, sorry :(

**Comment by PinpointTownes** [comment]
@MatthijsKrempel no problem.

@sebastienros do we still have some time before 1.0's release?

**Comment by sebastienros** [comment]
Some time for what?
