### ISSUE TITLE
Add reference tokens support

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#1983]
Reference tokens are random identifiers - generated by a crypto-secure RNG - for which the actual token payload is stored (encrypted) in the database.

Now that the OpenID module targets OpenIddict RC3 and its shiny new validation handler, we can easily add support for that by setting `options.UseReferenceTokens = true` in both the server and validation options. We should have a dedicated setting in `OpenIdServerSettings` and a corresponding entry in the settings UI.

**Comment by dborovsky** [comment]
Collegues, i would like to complete this task.

**Comment by PinpointTownes** [comment]
@dborovsky thanks! Technically, I can't assign it to you, but it's all yours. Let us know if you have any question.

**Comment by PinpointTownes** [comment]
@ninad-k negative 😄

**Comment by dborovsky** [comment]
@PinpointTownes I am sorry.  I tried but I did not understand until exactly about UI settings. If is it still actual, i can implement next week. But tell me please, what need I add in ui setting for OpenIdServerSettings?

**Comment by timlunev** [comment]
@kevinchalet Should **UseReferenceTokens** be enabled/visible in OpenIdServerSettings.Edit.cshtml only when the **Encrypted** access token format was choosen?

**Comment by kevinchalet** [comment]
@timlunev **for the time being, yes**. OpenIddict 2.x will throw an exception if you use JWT with reference tokens, but it's a restriction that disappeared in 3.x. We'll be able to remove that when migrating to 3.0.

It's also worth noting that in 3.0, all tokens are reference by default, except access tokens. That's why the option was renamed to `UseReferenceAccessTokens` in 3.0.

**Comment by timlunev** [comment]
@kevinchalet could you give me a hand testing the changes?
I've already added UseReferenceTokens to the OpenIdServerSettings and OpenIdValidationSettings so now I can manage them through the Orchard back-office.
I'd add some integration or functional tests for this logic to be sure that everything is working as expected. Or at least can we use/create some manual test script

**Comment by timlunev** [comment]
@kevinchalet let me clarify one thing: 

1. Should we have a dedicated `UseReferenceTokens` setting only in the server settings UI and in this case if it is enabled the `OpenIddictValidationOptions.UseReferenceTokens` will be enabled too?
2. Or the `UseReferenceTokens` setting should be present on both Server and Validation UIs?

**Comment by kevinchalet** [comment]
@timlunev sorry for not getting back to you earlier (I've been busy with tons of other things lately).

Option 1 is indeed the right approach, so that we can keep the validation settings as simple as possible.

**Comment by timlunev** [comment]
@kevinchalet thanks for the answer!

**Comment by timlunev** [comment]
@kevinchalet could you review the changes in #5774 when you have time, please?

**Comment by sebastienros** [comment]
Close ?

**Comment by timlunev** [comment]
@sebastienros yes
