### ISSUE TITLE
should we use High-performance logging with LoggerMessage ?

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#1988]
replace with High-performance logging with LoggerMessage gradually?

**Comment by sebastienros** [comment]
What is that?

**Comment by Skrypt** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-2.1

**Comment by sebastienros** [comment]
Wouldn't it add some complexity to the development? We would need to make it the default for all the development, how important is it?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
