### ISSUE TITLE
<style asp-src=""> from  a custom module not working

### ISSUE THREAD

**Issue by etcetraw** [OrchardCMS/OrchardCore#1994]
It works if I add the same style taghelper in bodypart view, but does not work if I add it to a view in  my custom module. Following seems to be the problem:
There is a bug in the resourcemanager, It seems to be calling ResolveRequiredResources for stylesheets before custom module's stylesheets are added to the _required collection.

**Comment by sebastienros** [comment]
Have you added the corresponding `_ViewImports.cshtml` entries?

**Comment by etcetraw** [comment]
Yes

**Comment by sebastienros** [comment]
More details to repro? We use this from modules without issues

**Comment by etcetraw** [comment]
https://github.com/etcetraw/OcoreStyleTest

**Comment by etcetraw** [comment]
Comments by Jean-Thierry Kéchichian @jtkech on the gitter:
    
"Hmm, maybe i understand, look at the ThemeLayout class, the layout body (which renders the main part of the Content zone) is pre-executed. So if your view is an alternate to a widget which is included in a content item whose type has a FlowPart, it should work. But if your widget is in a layer / zone (e.g Content or Footer), i think it's too late."

**Comment by sebastienros** [comment]
Let's see if we can delay the layout rendering, I think this is what we do in O1.

**Comment by marlon-tucker** [comment]
FYI we had this issue, and we worked around it be rendering out of order:

```
@inject OrchardCore.Settings.ISiteService SiteService
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@{
    var site = await SiteService.GetSiteSettingsAsync();
    var forgeryToken = Xsrf.GetAndStoreTokens(Context).RequestToken;
    var pageTitle = RenderTitleSegments(site.SiteName, "before");

    // We need to render these out of document order, so styles can be registered with the Orchard system before dependencies are calculated
    var headerSection = await RenderSectionAsync("Header", required: false);
    var messageContent = await RenderSectionAsync("Messages", required: false);
    var beforeContent = await RenderSectionAsync("BeforeContent", required: true);
    var bodyContent = await RenderBodyAsync();
    var afterContent = await RenderSectionAsync("AfterContent", required: true);
    var footerContent = await RenderSectionAsync("Footer", required: true);
}
<!DOCTYPE html>
<html>
<head>
    <title>@pageTitle</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script asp-name="base-theme-script" at="Foot"></script>
    <style asp-name="base-theme-style" at="Head"></style>

    @headerSection

    <resources type="Meta" />
    <resources type="HeadLink" />
    <resources type="Stylesheet" />
    <resources type="HeadScript" />
</head>
<body class="loading" data-forgery-token="@forgeryToken">

    <div class="container mb-4">
        @messageContent
        @beforeContent
        @bodyContent
        @afterContent
    </div>

    <div class="container">
        @footerContent
    </div>

</body>
</html>
```

Layout cut down for brevity

**Comment by ns8482e** [comment]
The issue is when style sheet is defined in other than ContentZone, Layout and resources on `<head>` rendered before the zone that defines it hence ResourceManager has no knowledge about the styles

related #3947
