### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1999]
Create some 'Getting started ' documentation.

**Comment by agriffard** [comment]
Quick start documentation to explain how to create an OC application in 5 minutes:

- Create empty Web application. Ex: CMS.Web
- If you want the dev packages, add OrchardCore-preview myget source
- Add reference to `OrchardCore.Cms.Web.Targets` package
- Configure Startup.cs
- Launch Setup. (Explain briefly the available options)

1 screenshot or code sample for each step.
Add images to src/docs/assets/getting-started, so every page will have its own assets folder.

**Comment by sebastienros** [comment]
Maybe copy http://www.ideliverable.com/blog/getting-started-with-orchard-core-as-a-nuget-package and at the top mention that this is coming from this url. 

@paynecrl97 is that ok?

**Comment by agriffard** [comment]
Also @paynecrl97 , can you please update your article with latest OC beta 2 changes:
ASP.NET Core 2.0 => ASP.NET Core 2.1
`app.UseModules();` => `app.UseOrchardCore();`

**Comment by paynecrl97** [comment]
Yep that's fine. I'll look to update it soon
