### ISSUE TITLE
Create Release Notes

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2003]
When we release a new version, let's try to create a new Release Notes page in the documentation like in O1.

At least, add a link to the milestone issues.

A most complete version would include the main features added, the contributors, ...

**Comment by agriffard** [comment]
Need some more changes I assume.

Add the date when the Release is done.

**Comment by sebastienros** [comment]
We'll finalize it during the meetings. We can also just create a link to the Github release page, and only have to manage the content on one location.
