### ISSUE TITLE
All projects targeting netstandart2.0 do not load

### ISSUE THREAD

**Issue by Diman96** [OrchardCMS/OrchardCore#2004]
Used latest dev
![image](https://user-images.githubusercontent.com/12182810/41560934-3b9c64e2-7351-11e8-8e39-7311960c3363.png)
...OrchardCore \ src \ OrchardCore.Modules \ OrchardCore.Email \ OrchardCore.Email.csproj: error: The project file is incomplete. The expected import statement is missing.

**Comment by domonkosgabor** [comment]
@Diman96 Please install the latest versions (current) for both Runtime and SDK of .NET Core from this page [https://www.microsoft.com/net/download/core](https://www.microsoft.com/net/download/core)

**Comment by Diman96** [comment]
I installed latest versions, but problem is not gone.
![image](https://user-images.githubusercontent.com/12182810/41585420-afeda160-73b2-11e8-8641-df37e785b832.png)

**Comment by alexbocharov** [comment]
**2.1.300-preview1-008174** is not latest

**Comment by alexbocharov** [comment]
@Diman96 Reinstall https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.300-windows-x64-installer

**Comment by Diman96** [comment]
thanks you all, now it works.
