### ISSUE TITLE
add HSTS support

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#2006]

**Comment by jrestall** [comment]
I started work on this at https://github.com/OrchardCMS/OrchardCore/pull/1680/commits/5f6770827e80ae51826557b3df5388ecd2ebfacf but need to find time to update the pull request and finish it off.

I'm also hoping the aspnet team will complete https://github.com/aspnet/BasicMiddleware/issues/323  then we aren't duplicating effort.
