### ISSUE TITLE
MyGet packages not updated

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2010]
It seems that the packages on Myget OrchardCore preview are not generated for the last 9 days.

Is there any problem since we updated the build?
@alexbocharov @sebastienros

**Comment by alexbocharov** [comment]
@agriffard I'll fix it.

**Comment by alexbocharov** [comment]
@agriffard Is fixed.

**Comment by agriffard** [comment]
Thank you @alexbocharov
