### ISSUE TITLE
Media: Error rendering images url with parameters

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2011]
I created a new OC application and selected the Agency recipe in the setup.

The assets are not displayed on front or in admin.

When I open this url: `https://localhost:44343/media/portfolio/01-full.jpg?&width=400&height=300&rmode=stretch`

There is an error:
`MissingMethodException: Method not found: 'System.Span`1<!!1> System.MemoryExtensions.NonPortableCast(System.Span`1<!!0>)'.`

If I use the url without parameters, it works: `https://localhost:44343/media/portfolio/01-full.jpg`

**Comment by matiasmolleja** [comment]
Right now It seems to work for me.
Maybe it's related to this ?
https://github.com/SixLabors/ImageSharp/issues/510#issuecomment-393911300

**Comment by agriffard** [comment]
OK, thank you. 
Now that @alexbocharov fixed the build and the packages are generated to MyGet, it works because it uses ImageSharp Beta4.
