### ISSUE TITLE
Exclude App_Data from dotnet publish.

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#2012]
How do I set it up?

Tried.
```xml
<ResolvedFileToPublish Remove="App_Data\Sites\**\*" />
```

and 
```xml
<None Include="App_Data\Sites\**\*" CopyToOutputDirectory="Never" />
```

**Comment by sebastienros** [comment]
We intentionally deploy the app_data by default.

@jtkech do you know how to configure the project to prevent it? I will then document it.

**Comment by jtkech** [comment]
As i remember we do things in a targets file which is run last, this to also prevent `App_Data` from being showed in the solution. So we can't override it in the somplest way.

But we can still do it with a not so complex little target in the application project file.

    <Target Name="DoNotPublishAppData" BeforeTargets="BeforePublish">
      <ItemGroup> <ResolvedFileToPublish Remove="App_Data\**" /> </ItemGroup>
    </Target>

Just tried with our cms web application, it works.

**Comment by awyl** [comment]
Thanks.  It works.  But I also wants to get rid of wwwroot\is-cache, using the same method doesn't work.

```xml
  <Target Name="DoNotPublishAppData" BeforeTargets="BeforePublish">
    <ItemGroup>
      <ResolvedFileToPublish Remove="App_Data\**" />
      <ResolvedFileToPublish Remove="wwwroot\is-cache\**" />
    </ItemGroup>
  </Target>
```

App_Data disappeared, but `is-cache` is still copied.

**Comment by jtkech** [comment]
Hmm, for this one try to use.


    <PropertyGroup>
      <DefaultItemExcludes>$(DefaultItemExcludes);wwwroot\is-cache\**</DefaultItemExcludes>
    </PropertyGroup>

**Comment by awyl** [comment]
Perfect!!!  Thanks!

**Comment by jtkech** [comment]
Your welcome ;)
