### ISSUE TITLE
Setup screen should fit without scrolling

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/OrchardCore#2019]
It happens on a Surface 4 Pro screen.

![image](https://user-images.githubusercontent.com/1871551/41627950-3d98c174-73d7-11e8-811d-113d07d7ddb1.png)

**Comment by agriffard** [comment]
Let's replace this Jumbotron by a simple h1.

**Comment by hishamco** [comment]
> Let's replace this Jumbotron by a simple h1.

Even though, the scroll will still, perhaps setup wizard will fix the issue

**Comment by Skrypt** [comment]
I don't see why scrolling is an issue. I think it should be kept in one page unless we require more steps because we want to apply transformations that requires it. We can almost do everything right now with Recipes.

**Comment by hishamco** [comment]
> I don't see why scrolling is an issue.

Yep .. isn't not a big issue

**Comment by hishamco** [comment]
Can we close this one or move to backlog while it's not an issue
