### ISSUE TITLE
Inserting a Media in a Markdown editor does it on all visible editors

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2023]
Repro:
- Add a Markdown field and a Markdown Body Part with Wysiwyg editor
- Insert a media in the second editor

Result:
The media is added to both elements.

Issue is in `simplemde.media.js`

**Comment by matiasmolleja** [comment]
I see too that it's added twice if you repeat again. I think it is because we are binding a new event handler on each click.
