### ISSUE TITLE
Problem publishing OC

### ISSUE THREAD

**Issue by dschmid** [OrchardCMS/OrchardCore#2031]
I used to deploy OC by publishing a self contained asp.net core project. Since the move from aspnetcore2.0 to aspnetcore2.1 this does not work anymore.

Apparently some parts of the app don't get published.
* If I deploy to my web site, the site site  setup page shows without any styling. The browser console says _SCRIPT5009: SCRIPT5009: '$' is not defined_.
* Reloading the page fails with a stack trace saying that the anti forgery token cannot be decrypted.

I generate the self contained Web App with the following command line:
`dotnet publish -r win10-x64 -c Release --self-contained`

My web host provider does support asp.net core only with self contained web apps.
I am not absolutely certain that the problems I experience are caused by OC. I'm kind of guessing here. But I need this problem solved

I attach following documentations:

1. _setup.html.txt_ - the setup page generated on the hosted site (giving error because of undefined '$' and doesn't show styling. [setup.html.txt](https://github.com/OrchardCMS/OrchardCore/files/2123040/setup.html.txt)
1. _setup.png_ - the screenshot of the setup page including error message. ![setup](https://user-images.githubusercontent.com/13175239/41711904-8f3a9d40-7549-11e8-9986-d60bcd7a09bf.PNG)
1. _orchard-log-2018-06-21.log_ - The error log after reloading the page. [orchard-log-2018-06-21.log](https://github.com/OrchardCMS/OrchardCore/files/2123045/orchard-log-2018-06-21.log)

I hope this helps to track the problem and find a solution. If anything more I can do, just let me know.

**Comment by Skrypt** [comment]
Seems like an issue related with DataProtection key.

**Comment by sebastienros** [comment]
I can't repro with the dev branch.

Please try with a clean repository. In the meantime I will also try when using the myget packages.

**Comment by sebastienros** [comment]
Works fine too with the packages, and the templates.
