### ISSUE TITLE
Forms doesn't appear in the list of features

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2032]
/cc @jtkech @sfmskywalker in case you find the issue before me

**Comment by sebastienros** [comment]
Only with the packages

**Comment by sebastienros** [comment]
The Cms target doesn't reference Forms

**Comment by jonvee** [comment]
Looks like it's referenced, but has no PrivateAssets attribute... 
<ProjectReference Include="..\..\OrchardCore.Modules\OrchardCore.Forms\OrchardCore.Forms.csproj" />

**Comment by jonvee** [comment]
If adding PrivateAssets="none" is all that's needed to fix the reference, how should I make a PR?
"Commit directly to the dev branch" (I'm assuming that wouldn't work), or
"Create a new branch and start a pull request"?

**Comment by sebastienros** [comment]
I am fixing it, and also reordering the references

**Comment by jonvee** [comment]
👍
