### ISSUE TITLE
about pagger

### ISSUE THREAD

**Issue by vongzh** [OrchardCMS/OrchardCore#2041]
```
  private async Task<PagerSlim> GetPagerAsync(IUpdateModel updater, ListPart part)
        {
            var settings = GetSettings(part);
            PagerSlimParameters pagerParameters = new PagerSlimParameters();
            await updater.TryUpdateModelAsync(pagerParameters);

            PagerSlim pager = new PagerSlim(pagerParameters, settings.PageSize);

            return pager;
        }
```

I want to change the pagination style,but the pagination define the before and after,i want to use the page index and page size.how to change to.

**Comment by sebastienros** [comment]
Could you share some examples for this request? I am trying to understand how useful it would be to support the two pager modes. Or at least to return two different pager shapes (slim and full) such that you can decide which one to hide/show with placement.info.

Right now the pager shape is inside the List view model, where it could actually be a separate shape. in the combined results.

**Comment by vongzh** [comment]
Thank you for your reply,orchard is a wonderful project.I should understand first and then change it,not now.So I am trying to learn his model,until i'm understand.I will trying change it by the shape,Thank you again for your guidance.
