### ISSUE TITLE
External logins

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2046]
Starting from zero, if I create a OC app and choose the Sass recipe, the menu have an item `External logins`.

By default, the page is empty. 

Is it possible to hide it when no external login provider is enabled?
What module enable and how configure an external login provider?

**Comment by MichaelPetrinolis** [comment]
Check https://github.com/OrchardCMS/OrchardCore/issues/1960 
If no external oidc provider is defined, there is nothing to show. That's 
Why we should hide it.

**Comment by sebastienros** [comment]
I confirm the issue, but that's not a major one, -> beta3

**Comment by sebastienros** [comment]
I find it weird to generate a link to do this here. Ideally we should have a Profile page, that can be extended with custom drivers, and this will be one of the things to display, and this custom link would just be removed. But we already track that somewhere, and right now it's ok to just display the link conditionally, though removing it altogether would just be as fine, as we can't even access it anywhere else AFAIK.
