### ISSUE TITLE
Use a CQRS pattern for event bus.

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#206]
This will lead to a simpler and faster implementation.

**Comment by sebastienros** [comment]
I am not sure if MediatR supports loose type matching, like if the class names match then it works. In O1 and O2 currently messages (method calls) match by name and can have different arguments.
A solution like MediatR would then need to map the two types of objects, it could use some sort of serialization to do so, like Json.NET.

Or stop supporting it and have the event classes in the Abstractions modules.

As a side note, because class implementing multiple interfaces is a hard issue with ASP.NET DI, I think we should avoid having a class implement a service interface, and also an event handler. Event handler should be independent services, and request the other one or its state as needed.

**Comment by infofromca** [comment]
how about brighter?
https://github.com/BrighterCommand/Brighter

**Comment by alexbocharov** [comment]
Alternative https://github.com/dotnet-architecture/eShopOnContainers
