### ISSUE TITLE
Bad formatting of Item without children on left menu

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#2060]
Visible when workflow module is enabled. We did not tested the case of a first level menu item without children.
![menuitem](https://user-images.githubusercontent.com/2589629/41822617-e701cf66-77f2-11e8-9ded-1b8e673e5004.png)

/cc  @Skrypt

**Comment by sfmskywalker** [comment]
Weird, I has fixed that as part of the Forms branch.

**Comment by matiasmolleja** [comment]
I think we can close this one. It was fixed by the amazing @Skrypt  here #2610  :)

**Comment by Skrypt** [comment]
It's worth a link to this amazing song 😄 
https://www.youtube.com/watch?v=zSmOvYzSeaQ
