### ISSUE TITLE
Add ability for recipes to mark features as hidden, so those features do not appear on the admin page.

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#2063]
Hello,

We are using a custom user management module which uses OpenID Connect to authenticate against an external system. This means the `OrchardCore.Users` feature is disabled in our recipe - however it still appears in the feature list in the admin page. If a admin user does enable this feature by accident, it overrides the authentication scheme, meaning if they don't immediately disable it again, they won't be able to get back into the admin page to do so.

I realise features are discovered at run time, so we could remove the `OrchardCore.Users` after publishing, but having the ability for a recipe to define a feature as being hidden or permanently disabled would be a better solution in my opinion.

**Comment by sebastienros** [comment]
As a workaround you can also reference specific packages from your own solution instead of the CMS metapackage.

But we should still think about ways to mark some features as protected, so it would require a second step for activating them. Or like in O1 a set of allowed features.

**Comment by sebastienros** [comment]
Also related to this issue: https://github.com/OrchardCMS/OrchardCore/issues/2029

**Comment by Piedone** [comment]
Tenant Feature Profiles serve this now.
