### ISSUE TITLE
Fix allocaty code

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2065]
This one:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Media/Recipes/MediaStep.cs#L38

Use streams only, so the contents are buffered and not loaded in memory as a whole.
c.f. https://github.com/aspnet/benchmarks/blob/dev/src/BenchmarksServer/Controllers/JobsController.cs#L296

**Comment by deanmarcussen** [comment]
Think is as stream optimized as it can get, unless the `Base64` feature is dropped.

**Comment by Piedone** [comment]
So, nothing to do here, then?
