### ISSUE TITLE
Site is not available in liquid widgets

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2067]
If I want to use Liquid syntax in a Widget, it is not interpreted.

Repro: On a site using TheAgency recipe, edit the Footer layer and to replace the copyright content with:
`<span class="copyright">Copyright &copy; {{ Site.SiteName }}</span>`

Result: The Liquid tag is not interpreted, only `Copyright ©` is displayed.

**Comment by sebastienros** [comment]
Create a Widget using the Liquid part?

**Comment by agriffard** [comment]
I thought an HtmlField was interpreting Liquid since this change: #1066

**Comment by sebastienros** [comment]
Yes, HtmlBodyPart and HtmlField should interpret liquid, because we need it to insert images.

**Comment by agriffard** [comment]
An image in liquid works in a Paragraph widget that has an HTML field with a wysiwyg editor but not in a RawHTML widget that has a HTML field with a multiline editor.

`{{ Site.SiteName }}` does not work in any widget though.
