### ISSUE TITLE
Moving Assets module to new style

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#2068]
This issue is just to ask for your feeback.
I've been using the Assets module as a testbed to see how the new design we have been talking about could look like ( #2037 ).
 This is what I have so far:

![media-fluent-progress](https://user-images.githubusercontent.com/2589629/42105814-16058d92-7bd2-11e8-848e-a2f2abd162c5.png)

My idea was to try this on the Assets module, and if we think its OK, start adding a few styles on theAdmin so that on each module we can opt-in to use them.

One issue I've found is that Fontawesome standard icons look weird with this design. They are solid and "bold" whereas the icons that  VSTS uses are very thin. I think that VSTS use [Fabric MDL2 icons](https://developer.microsoft.com/en-us/fabric#/resources) and I think we can't use them on Orchard. Unless someone with better contacts in Microsoft tell me we can ;)

Other alternatives to use these style of outline icons I've found are:
- http://simplelineicons.com/ (this one is used by coreUI)
- https://iconos8.es/line-awesome (seems to be MIT)
- Of course fontawesome outline version icons.

All of them make the design look way better that solid fontawesome, but I'm not sure if it worth.
For me the design it is acceptable without the icons, we can use the links only, until we found a better alternative. Anyway the standard buttons we are using now from bootstrap don't have icons.

**Comment by agriffard** [comment]
Do you know http://xtoolkit.github.io/Micon/ ?

**Comment by matiasmolleja** [comment]
I did not know it. But I don't like the only issue on the repo:
https://github.com/xtoolkit/Micon/issues/9
I filed a couple of issues on line awesome and simple line icons repos to be sure, but the maintainers did not answered yet.

**Comment by matiasmolleja** [comment]
I think that in case we think it is worth we should choose [line-awesome](https://icons8.com/line-awesome).
It works [mainly without changing our markup](https://icons8.com/articles/line-awesome/#fn-19357-1). 
It is from a company that has a lot more icons and that seems to be [friendly to open source projects](https://icons8.com/articles/weve-contributed-an-icon-to-imageoptim/), maybe we can even build our own icon webfont tailored for our needs choosing from their icon catalog. They have an impressive Windows 10 style icon set.
We could contact them in case we think it is worth.
Here is an screenshot of both icon styles, font-awesome-free and line-awesome.  :confused:

![font-awesome-vs-line-awesome](https://user-images.githubusercontent.com/2589629/42137979-fcba098a-7d75-11e8-832a-7aa9601fa485.png)

**Comment by sebastienros** [comment]
font-awesome only, MIT for code a CC-BY 4 for icons. The line-awesome can only be used from their CDN, so not redistributable.

**Comment by agriffard** [comment]
Would you consider submitting a PR about this improvement? Even if the icons are still using Font awesome.

**Comment by matiasmolleja** [comment]
Sorry, I did not see your message.
I will made a PR as soon as I get the admin tree PR merged.  I'd like to expend some more time on this.
