### ISSUE TITLE
GraphQL module

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#2069]
In #2062 @sebastienros mentioned GraphQL.
There are commits from @Jetski5822 6 months ago.
Does someone plan to implement it?

**Comment by Jetski5822** [comment]
GraphQL Done https://github.com/OrchardCMS/OrchardCore/pull/1689 - just need to fix one test for the JSONApi endpoint

**Comment by Jetski5822** [comment]
btw - last commit was 19 days ago?

**Comment by xperiandri** [comment]
Ah, wow!
I see you did an amazing job!
I just hadn't known that your branch is called `jsonapi`, so the last commit I've found with GraphQL mentioning was that.

**Comment by xperiandri** [comment]
Which community podcast does have a demo of it?

**Comment by sebastienros** [comment]
Demos here: https://t.co/gzqJqa8lJZ
