### ISSUE TITLE
Create/Display widgets inside cshtml page

### ISSUE THREAD

**Issue by cocoke** [OrchardCMS/OrchardCore#2070]
Hello, I'm trying to create and display widgets only from files so I try to understand how the demowidget from the OrchardCore.Demo module works. 
Unfortunately I'm not abble to make the widget work, I tried to setup a new OrchardCore website to test it but the demowidget called inside the /Home/Cache page doesn't show up.

https://github.com/OrchardCMS/OrchardCore/blob/01391e20b0e47fb11925d31be5a3cdccd2079555/src/OrchardCore.Modules/OrchardCore.Demo/Views/Home/Cache.cshtml#L12

Is there something special to do to make this work ?

**Comment by sebastienros** [comment]
Try with `<shape type="...">` instead, looks like `typeof` is a typo.
