### ISSUE TITLE
AddResourceManagement no-longer works outside of OrchardCoreCMS?

### ISSUE THREAD

**Issue by mcapewell** [OrchardCMS/OrchardCore#2071]
I was successfully using Resource Management in Beta 1 but have tried to upgrade to Beta 2 and now get the following compile error:

'IServiceCollection' does not contain a definition for 'AddResourceManagement' and the best extension method overload 'OrchardCoreBuilderExtenstions.AddResourceManagement(OrchardCoreBuilder)' requires a receiver of type 'OrchardCoreBuilder'

Have I missed something? Do I now need to do something differently to use Resource Management in a plain vanilla ASP.NET Core web app?

**Comment by jtkech** [comment]
Exactly 👍
