### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.NETCore.App' in prod

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#2072]
It's related to the upgrade to 2.1. The exception doesn't occur in dev time only after publish.

Repro

1. In OrchardCore.Cms.Web folder run: dotnet publish -c Release -o site
2. Then run: dotnet .\site\OrchardCore.Cms.Web.dll
3. InvalidOperationException: Cannot find compilation library location for package 'Microsoft.NETCore.App'

There's an unresolved issue related to this: https://github.com/dotnet/core/issues/1725

There's a fix in here https://stackoverflow.com/questions/51021011/cannot-find-compilation-library-location-for-package-microsoft-netcore-app/51078720
"Just set MvcRazorExcludeRefAssembliesFromPublish to false in your .csproj file and that should fix the issue."
The above fix works for me but I don't know whether this is the soultion. But if this is the solution then we should update OrchardCore.Cms.Web.csproj and OrchardCore.Templates.Cms.Web.csproj too.

**Comment by jtkech** [comment]
No, again ? Normally we don't need it anymore because we don't trigger any razor compilation at runtime. And we did all the tests, but, indeed, not just after the upgrade to 2.1.

I will check it again this night.

**Comment by alberthajdu** [comment]
@jtkech I noticed that it happens only when ASPNETCORE_ENVIRONMENT is Development. If I set it to Production it works well. Is this the expected behavior?

I'm using the latest dev.

This issue came up in production in Azure and MvcRazorExcludeRefAssembliesFromPublish solved it so either something wrong with my Azure setup or with OC.

Here's my dotnet --info output, once this problem came up I uninstalled all previous versions and reinstalled the latest SDK.
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by jtkech** [comment]
Okay i understand, and all is ok with your dotnet installation.

If `_hostingEnvironment.IsDevelopment()` we don't take into account precompiled views and razor compilation is done at runtime, moreover it will try to get the content from your project locations.

While in debug mode you have this file `OrchardCore.Cms.Web.runtimeconfig.dev.json` which provides `additionalProbingPaths`. But when doing dotnet publish this file is not outputed under the published folder and to do razor compilation at runtime you would need the `refs` folder with compilation libraries.

So, i would say that when running your application in a published context, the environment variable `ASPNETCORE_ENVIRONMENT` should not be set to `Development`. But i will ask to Sebastien what he think about this when he comes back.

**Comment by alberthajdu** [comment]
I tested again and in case MvcRazorExcludeRefAssembliesFromPublish isn't there it's still throwing exception in Azure.

Can someone try it in Azure too?

**Comment by jtkech** [comment]
From the last dev branch, just published, the [cms web app on azure](http://orchardcorecmsweb20180704110901.azurewebsites.net/), this through web deploy under VS. I used the blog recipe to setup the site and then it was working.

**Comment by alberthajdu** [comment]
Yes I tried too and it works for me as well. Even my custom app works well with the blog recipe.

**Comment by alberthajdu** [comment]
@jtkech Version="2.1.1" was missing from <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" /> and this caused the error.
I generated a new theme with octheme and noticed the difference.

Thank you for your help!

**Comment by peterkeating** [comment]
Came across this issue when deploying to a web app within Azure. 

Fix was to add the following to the CMS `csproj` file (https://github.com/moov2/website-core/commit/9111efdbec0c4c54c0536fb2b0ff3e2b307f840b)

`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`

**Comment by jtkech** [comment]
We don't use it assuming that all razor views are precompiled.

At the module level that's ok if using `Microsoft.NET.Sdk.Razor` **and also reference directly** in the module project file `Microsoft.AspNetCore.Mvc`, see #3064.

If you define razor views at the app level that's ok if using `Microsoft.NET.Sdk.Web`. But it may depend on the other options you are using and / or another sdk.

    <MvcRazorExcludeRefAssembliesFromPublish>***</MvcRazorExcludeRefAssembliesFromPublish>
    <RazorCompileOnBuild>***</RazorCompileOnBuild>
    <RazorCompileOnPublish>***</RazorCompileOnPublish>
    <MvcRazorExcludeViewFilesFromPublish>***</MvcRazorExcludeViewFilesFromPublish>

Note: at least with the dev branch because at some point we were using it by default because the usage of a liquid tag helper (using the same mvc factory) was hitting a little csharp compilation.

**Comment by stantoxt** [comment]
> We don't use it assuming that all razor views are precompiled.
> 
> At the module level that's ok if using `Microsoft.NET.Sdk.Razor` **and also reference directly** in the module project file `Microsoft.AspNetCore.Mvc`, see #3064.
> 
> If you define razor views at the app level that's ok if using `Microsoft.NET.Sdk.Web`. But it may depend on the other options you are using and / or another sdk.
> 
> ```
> <MvcRazorExcludeRefAssembliesFromPublish>***</MvcRazorExcludeRefAssembliesFromPublish>
> <RazorCompileOnBuild>***</RazorCompileOnBuild>
> <RazorCompileOnPublish>***</RazorCompileOnPublish>
> <MvcRazorExcludeViewFilesFromPublish>***</MvcRazorExcludeViewFilesFromPublish>
> ```
> Note: at least with the dev branch because at some point we were using it by default because the usage of a liquid tag helper (using the same mvc factory) was hitting a little csharp compilation.

I will check if my custom module has `Microsoft.AspNetCore.Mvc` reference.

**Comment by jtkech** [comment]
Okay cool, let us know.

About sdk i was talking about specifying e.g `Microsoft.NET.Sdk.Razor` in a module project file, or `Microsoft.NET.Sdk.Web` in the app project file.

**Comment by stantoxt** [comment]
@jtkech That's working perfectly.Thanks very much

**Comment by rserj** [comment]
I face the same issue.
I'm lunching Orchard Core on AWS Fargate, it will be REALLY convenient to be able to pul Orchard core from Dockerhub and lunch it in Development mode/enviroment for troubleshooting.
