### ISSUE TITLE
Blog recipe : Social icons not displayed

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#2075]
@agriffard @Skrypt @matiasmolleja just for infos

- Do a blog recipe setup

- Social icons are not displayed.

**Update**: just published the [cms web app on azure](http://orchardcorecmsweb20180704110901.azurewebsites.net/) to show what i mean.

**Comment by Skrypt** [comment]
I get the same locally while debugging. Maybe a font-awesome issue.
