### ISSUE TITLE
brute force detection

### ISSUE THREAD

**Issue by sbiaudet** [OrchardCMS/OrchardCore#2078]
We are writing a chatbot with a backend powered by orchardcore. Our application was audited by white hat hacker missioned by my Customer. 

They have detect a miss in login. Brute force detection is not implemented.

How can I implement this in orchardcore or/and is it possible to have a fix quickly for this point ?

**Comment by sebastienros** [comment]
We are using ASP.NET Core identity, so I would start looking at what the recommendation is for brute Force protection, probably nothing and it's relying on the hashing complexity to limit the rate. Or enabling 2FA, which is supported OOB but needs to be configured in Orchard.

**Comment by Jetski5822** [comment]
Out of interest, could you share the report?

**Comment by sbiaudet** [comment]
Sorry, I can't share the report, I've privacy clause. Nothing really important only brut force remark.


Perhaps, we could implement Something like this with an incremental delay.

http://jasonwatmore.com/post/2015/06/03/csharp-incremental-delay-to-prevent-brute-force-or-dictionary-attack

or a module with this feature https://github.com/oazabir/HackerSpray

**Comment by PinpointTownes** [comment]
Account lockout feature is not perfect either. Actually, it's even a great way for an attacker to prevent a victim from accessing his/her account. Not a big deal for many sites, but imagine you're developing a multiplayer game... and you'll immediately see it's not always a good idea :smile:

**Comment by sbiaudet** [comment]
In this case it's not a definitive lockout but just a lockout during a period 5 minutes after 5 attempts in my previous comment. So not really blocking for users. just slowly for the hacker 😄

**Comment by PinpointTownes** [comment]
And what prevents me from writing a script that will send wrong passwords every 5mn so that the account is permanently marked as « locked out »?

**Comment by PinpointTownes** [comment]
:+1: for reCAPTCHA. Tweaking the iterations count of the PBKDF alg used by ASP.NET Core Identity to make the password validation logic slower is also a good option.

**Comment by ArashSade** [comment]
Just to be complete I'll try to summarize what we do for our brute-force protection.

Internet facing applications must protect its (user) accounts from brute-force attacks. A process must be in place to detect abusive behavior and a process must be in place to react upon the abuse.

Possible origins:
• Brute-forcing the password per account.
• Brute-forcing the accounts by fixating a password or PIN and brute-forcing this on all accounts.

Possible actions:
• Detect (rapid) automated login attempts and react by blocking the IP address temporarily. Report to security office center.
• After detecting abusive behavior; force the account to logon with a CAPTCHA. Report to security office center.
• After detecting abusive behavior; force the account to logon with a second factor. This option assumes there is an opportunity to use SMS or another out of band communication method. Report to security office center.

Regards,
Arash

**Comment by Skrypt** [comment]
We are missing a Liquid tag for the ReCaptcha. It works with razor but not with Liquid.
