### ISSUE TITLE
Collection Body Text Disappears After Changes

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#2084]
I have deployed the prerelease beta3 OrchardCore Website to an Ubuntu 16.04 Azure VM.   Everything looks cool after I run the setup page.   I am using a SQLite database.  I also had this issue with beta2.

![image](https://user-images.githubusercontent.com/26497457/42502211-0a38b47c-83fb-11e8-82d4-682923ad461b.png)

However, when I change anything on the lists the body text disappears from the Services and other collections as well.   Even if I type something in the body for a service it doesn't show up in the collection item after I publish it:

![image](https://user-images.githubusercontent.com/26497457/42502595-1ec4c3c6-83fc-11e8-85f2-1d44e2816271.png)

![image](https://user-images.githubusercontent.com/26497457/42502462-b61dd344-83fb-11e8-8ba2-68275c21bf29.png)

**Comment by jtkech** [comment]
Yes, i could repro.

After the change of `BodyPart` to `HtmlBodyPart`, in the `agency.recipe.json` file and the `Snippets/landingpage.liquid`, which are used to configure the landing page when using the agency setup recipe, there are some remaining `Body` properties that need to be replaced to `Html`.

I will fix it.

Meanwhile, in the admin in `Configuration/Templates`, you can edit the `Content__LandingPage` template and replace each occurence of `HtmlBodyPart.Body` with `HtmlBodyPart.Html`.

**Comment by mdockal** [comment]
Yea, I discovered that It seems to be confined to The Agency Theme after posting this.   Thanks for the fix!
