### ISSUE TITLE
X-Frame-Options header not set

### ISSUE THREAD

**Issue by ArashSade** [OrchardCMS/OrchardCore#2085]
Hi,

I came across a medium risk security issue in the SaaS website. But probably it's not specific to SaaS website.
According to our basic pentest X-Frame-Options header is not included in the HTTP response to protect against 'ClickJacking' attacks.

Most modern Web browsers support the X-Frame-Options HTTP header. Ensure it's set on all web pages returned by your site (if you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. ALLOW-FROM allows specific websites to frame the web page in supported web browsers).

You can find more info in this post: https://blogs.msdn.microsoft.com/ieinternals/2010/03/30/combating-clickjacking-with-x-frame-options/

Regards,
Arash

**Comment by sebastienros** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/854
