### ISSUE TITLE
Cookie No HttpOnly Flag

### ISSUE THREAD

**Issue by ArashSade** [OrchardCMS/OrchardCore#2086]
Hi,

I found a low risk security issue which I wanted to report.
As far as I can see on the login page the cookie does not have a HttpOnly flag set. This means that the cookie can be accessed by JavaScript. If a malicious script can be run on the page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible.

For more info see: https://www.owasp.org/index.php/HttpOnly

Regards,
Arash

**Comment by sebastienros** [comment]
@PinpointTownes What's the recommendation in the cookie middleware, I would have thought it to be the default, but because it's not there must be a reason.

**Comment by ArashSade** [comment]
It seems to be a false-negative from our ZAP scan. As PinpointTownes stated, the HttpOnly flag is set on the Orchard cookie. I'm closing this issue.
