### ISSUE TITLE
Exception while enabling Title feature

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#2094]
Repro:
1. Latest dev, saas recipe, sql server.
2. Enable title module.
3. InvalidOperationException: Unable to resolve service for type 'OrchardCore.ContentManagement.Metadata.IContentDefinitionManager' while attempting to activate 'OrchardCore.Title.Migrations'.
4. Site throws this exception on all routes so it stucks in an unrecoverable state. I think in this case we should rollback to a working state.

**Comment by sebastienros** [comment]
Maybe there is a missing required dependency that is actually already enabled with the other recipes.

**Comment by agriffard** [comment]
IContentDefinitionManager is injected here:
https://github.com/OrchardCMS/OrchardCore/blob/1598e8a6e3a8414dbb5f934ae53bee557e59d95c/src/OrchardCore.Modules/OrchardCore.Contents/Startup.cs#L40

So any module that uses IContentDefinitionManager (ex: in Migrations.cs with `_contentDefinitionManager.AlterPartDefinition`) should have a dependency on OrchardCore.Contents
