### ISSUE TITLE
VS2017: Self-Signed Certificate Error

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#2097]
Ugh, when I try to clone this project in latest version Visual Studio 2017 community from https://github.com/OrchardCMS/OrchardCore.git

I get the following error:

Git failed with a fatal error.
unable to access 'https://github.com/OrchardCMS/OrchardCore.git/': SSL certificate problem: self signed certificate in certificate chain

I used to not get this error until the GitHub URL changed from Orchard2 to OrchardCore

**Comment by jtkech** [comment]
Try to update Git Credential Manager for Windows v1.14.0 [here](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.14.0).
