### ISSUE TITLE
Help us help others

### ISSUE THREAD

**Issue by ArashSade** [OrchardCMS/OrchardCore#2100]
Too many open source projects rely on or expect from the developers learning from the code, unit tests, Wiki or overly simple demo apps. For us Orchard-newbies the biggest challenge for the learning 
and adoption of OrchardCore is the lack of meaningful demo or reference applications or even blogs and tutorials to give us a good starting point. When we know how to use things, we will use them, extend them, improve them, write about them in our blogs and teach them to others. That's the spirit of community.

I remember a talk of Jorg Janke the founder of Compiere ERP years ago. When he said that 'adaption is a two-way street and my biggest mistake was to expect developers to learn Compiere without my help'.

I wonder if anyone except the core team would ever be able to use all power of OrchardCore. Just because it is so hard and time-consuming to get to know each module, learn to use and combine it with other modules appropriately.

But we won't give up just yet and will continue spending most of our spare time trying to learn it. Hopefully we can conquer it eventually.  In the mean time, any serious example of OrchardCore is more than welcome and will be appreciated.

Thanks in advance.

**Comment by Skrypt** [comment]
Orchard Core is still in beta so it is more likely that in that state you will face road blockers as the community still has to develop some facets of it. Though, I'd say, at this point, if some documentation is missing you should ask for help or pointers here as we don't have a community forum anymore. For the more complete code examples I think some of them are in discussion right now. Maybe you should just try to create an issue where it would list which things you would like that we improve.

**Comment by ArashSade** [comment]
Closing this because up until now there are already more than 108 registered issues about documentation of the features. Besides it's not important to us anymore.
