### ISSUE TITLE
Odd Pager behavior in Content List Page

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#2101]
Repro:
1- List all content items (you should have more than 10).
2 - Go to page 2.
3 - Filter to show only content items of type landing page.

Expected: I should be on page 1. No pager shown.
Achieved: I'm on an empty page. Pager is shown.  Page 2 in on querystring. I can click "go to previous" on the pager and I go to the first page where I can see my landing page.

**Comment by hishamco** [comment]
I verified from this on the latest bits but with filtering with different content type, seems it works as expected "No pager will show up"

@matiasmolleja  could you please verify from your side again?

**Comment by Skrypt** [comment]
I think something could be fixed though. When we navigate back after doing a search in the admin we get an error page. Mostly because we use Form Post and the values are not kept.
