### ISSUE TITLE
[Fields] Display Mode

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2105]
The general idea is to add a Display Mode in fields settings and to be able to add settings on them.

**Comment by sebastienros** [comment]
NO. WE. DON'T. 

😄  ❤️

**Comment by sebastienros** [comment]
Best way to understand the difference, implement the feature ;)

**Comment by Skrypt** [comment]
I see what you mean then.

**Comment by agriffard** [comment]
It will allow a lot of new possible options:

For most display modes
	
- Liquid : Templates to display the field, may be allow to access to other field values.
    - Summary/Details: Depend of the kind of shape.
    - Zone/Position: Send the display to a specific zone and position.

Text Field

- Truncate: number of caracters/words.
- Meta: Add it to the Head ressources.
- Syntax Highlight: Select in which language.
- Translate

Date, Time Fields

- 	Format
- 	Time ago
- 	<time> markup
- 	Timezone

	
Numeric Field

- Money format
- Currency

	
Boolean Field
	
- Labels depending on boolean value

	
Media Field
	
- Carousel
- LightBox

**Comment by agriffard** [comment]
It would be great if we could summarize some of the settings in the list of fields when we watch the Content Type definition in admin, without needing to go in each field details page.

**Comment by sebastienros** [comment]
@agriffard you see how it's much better than having that many different fields?

**Comment by agriffard** [comment]
Me when I understand what we will be able to do with Fields display modes:
![im-gonna-make-some-weird-shit](https://user-images.githubusercontent.com/703248/47245014-e197b980-d3f7-11e8-8881-c8888000282a.jpg)

**Comment by Skrypt** [comment]
omg @sebastienros has freed the Kraken
