### ISSUE TITLE
Media Gallery file paths not working

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2109]
When using Orchard Core as a Nuget package the media url paths don't seem to resolve to any route.
The same works with source code with IIS Express.

![image](https://user-images.githubusercontent.com/3228637/42712579-3460c7fa-86ba-11e8-9272-f37809ae828f.png)

**Comment by jtkech** [comment]
It works on my side by referencing the last `1.0.0-beta3-67732`.

**Comment by Skrypt** [comment]
I'm referencing 1.0.0-beta3-* so normallly it should get latest all the time. But I will retry.

**Comment by Skrypt** [comment]
Same thing. I'm upgrading .NET Core SDK to 2.1.302 maybe that's the issue.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/42718980-1041d47c-86dd-11e8-8f25-790c6588179e.png)

Issue is happening with url's that are images generated by ImageSharp.

**Comment by Skrypt** [comment]
Ok the issue is that I was missing my wwwroot folder in my csproj file and the cache is getting built there so the images we're not displaying. Problem solved. Issue was in front on the PC 😉

**Comment by jtkech** [comment]
;)
