### ISSUE TITLE
Customzing the tenant setup for SAAS application

### ISSUE THREAD

**Issue by siyamandayubi** [OrchardCMS/OrchardCore#2114]
The current implementation of tenant-creation is for specific use-case. I am looking for a way to customize the creation and setup of tenants in such a way that it can be used for variety of SAAS applications.
## Current Scenario
Currently, the admin of the root site can create a tenant (with some settings such as database connectionstring and so...), then by navigating to the tenant url, one can setup the tenant.

## New Scenario for SAAS Apps
There are lot's of scenarios, this is a simple one
1. User fills a form in the root site for creating a tenant
2. System sends a validation email to the user with a token Id that will be expired after few minutes
3. After clicking on the confirmation link in the email, user will be navigated to the Tenant setup page
4. Such users don't provide and don't have access to technical fields such as connection-string.

## Minimum Required changes
-  An anonymous user must not be able to navigate to the setup page of a tenant without some custom validation (such as confirming an email)
- The OrchardCore provides a basic implementation for "Registration Form", "Confirming user", "Database creation" and one can extend the default implementation with custom one.

The question is, is it possible to support such use-case in OrchardCore and how much effort does one need to implement such use-case?

**Comment by zl2fxy** [comment]
Hi,
I think you can do like this,if you are a developer。you can do a activity for WorkFlows Modules in your Tenant Modules.and you just a little to do,you can do somethings in ExecuteAsync().You also read the [Readme.Md](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Workflows/README.md)。

**Comment by siyamandayubi** [comment]
I guess it needs more than implementing an Activity in the workflow as current Tenant setup page allows everyone to setup the tenant and choose fields like Recipe. I think only Admin in the main root, or the user who owns the email of the tenant should be able to setup the tenant.

**Comment by Skrypt** [comment]
First I found that there's maybe an issue in the Tenant module since we never register the IPermissionProvider that is in Permissions.cs of that module. So adding this in startup.cs of that project will enable having User/Roles permissions for Tenants creation.

```C#
        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<IPermissionProvider, Permissions>();
        }
```

**Comment by zl2fxy** [comment]
I think it is wrong that current Tenant setup page allows everyone to setup the tenant and choose fields like Recipe，you can do something like as "securized" in the WorkFlow. In the Workflows ,you can create a HttpRequestTask before your custom Activity about TenantSetting.

**Comment by siyamandayubi** [comment]
@zl2fxy I mean: 

1. Create a tenant in code or UI.
2. Log out or in a different browser navigates to the tenant page. You can simply setup the tenant without any validation

**Comment by sebastienros** [comment]
Suggestion:
- Be able to set the recipe (or list of recipes) from the tenant creation form, like we do already for the database connection.
- Change the Setup url on the tenant screen to use a SAS token. The service that lists the tenants needs to be able to return a setup url so that other features can send it by email for instance.
