### ISSUE TITLE
Pager: Add all links even when not available

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#2116]
Hi,
I would like to have a pager shape with all their link shapes on it. 
For example, right now if we are on page 1, we don't add the "Pager_First" shape.
The result is that as the user clicks through a list of pages, the pager's layout changes. And the position of the buttons change too. That makes difficult to click on the buttons as you browse the list of pages.

I think its better experience to place the cursor over the next button, and start clicking on it to go to the next page again and again.
I would like to have all the shapes, and "disable" the buttons that link to unavailable pages.

Like this for example:
![sin titulo-1](https://user-images.githubusercontent.com/2589629/42838326-cd4e054c-8a00-11e8-8f72-f7e029f74b15.png)

Is there a way to do that other than changing the code on "OrchardCore.Navigation.PagerShapes.cs" ?

**Comment by sebastienros** [comment]
So we could refactor the pager to render Page_Firts, but it would be the responsibility of Page_First to not render anything by default for page 1. You can then change the template to still render something?

**Comment by matiasmolleja** [comment]
I think that ideally a designer using the pager should be able to style it by using css only.
Right now the pager is itself generating the anchor tags. 
I would refactor to generate,  for "valid" links:
<a href="whatever">

For non-valid links:
<a href="#" class="disabled" ...
This is what nopcommerce is doing for example.
