### ISSUE TITLE
DisplayDriver doesn't display SectionDisplayDrivers elements after validation error

### ISSUE THREAD

**Issue by cocoke** [OrchardCMS/OrchardCore#2118]
Hello, I'm facing an issue with the ``SectionDisplayDriver``, after a validation error only base displaydriver's elements are displayed.
I encountered this problem with my modules but I've tested the OrchardCore.Demo module and same issue occured:

### Before sending :
![image](https://user-images.githubusercontent.com/6980626/42991104-ecf226a2-8c04-11e8-85a4-8859fe6347e1.png)

### After saving and triggering validation error :
![image](https://user-images.githubusercontent.com/6980626/42991114-f354664a-8c04-11e8-89b7-e6314c05a179.png)

We see here that the demo user sectiondisplaydriver's inputs (name and age) aren't displayed when a validation error occured.

Is it normal or can it be fixed ?

**Comment by sebastienros** [comment]
I think this has been fixed, can you check again?

**Comment by deanmarcussen** [comment]
Confirmed this is fixed.
