### ISSUE TITLE
Permalink auto-generate Wrong 

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2129]
Contents  >>  ContentItems  >>  Blog  >>  create  >>  Blog Post
Title:中文标题测试Chinese title test
Permalink:
Body:中文标题测试Chinese title test
publish
Browse this Blog Post does not display Body content。

![2](https://user-images.githubusercontent.com/28694676/43138020-34b49780-8f80-11e8-82ce-401401617550.gif)

Here is a project that is handled like this, maybe it can help
https://github.com/Tsingbo-Kooboo/Kooboo.CMS.Toolkit/tree/master/Kooboo.CMS.Content.UserKeyGenerator.Chinese

http://kooboo-cms.ru/articles/detail/what-is-userkey-url-on-russian/

![2](https://user-images.githubusercontent.com/28694676/43138294-f02ce1ca-8f80-11e8-9ffa-c36d60ba40da.gif)

**Comment by hishamco** [comment]
@pgy866 is this still happening with the latest bits?

**Comment by sebastienros** [comment]
We might need two things:
- support unicode chars in the generated autoroute
- provide a transliteration liquid filter that could be used in the autoroute pattern

**Comment by hishamco** [comment]
It's working

![unicode-autoroute](https://user-images.githubusercontent.com/3237266/64215122-f8ce8100-cebb-11e9-8067-d96ab9bf06ef.png)

**Comment by sebastienros** [comment]
Thanks for testing. Created this one to follow-up on the transliteration filter. https://github.com/OrchardCMS/OrchardCore/issues/4151
