### ISSUE TITLE
Static Website Page Migration to Orchard Core Documentation Tutorial

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2131]
hope someone can help, in Software as a Service, completely use Liquid templates to migrate a static HTML blog site to Orchard Core, graphic tutorial。

**Comment by pgy866** [comment]
Iagree with the point here.
https://github.com/OrchardCMS/OrchardCore/issues/2100

**Comment by sebastienros** [comment]
What is the question, or issue?
