### ISSUE TITLE
UUID Global Method Provider resgistered with TryAddSingleton

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#2136]
Hi,

I wrote an implementation of `IGlobalMethodProvider`, but adding it to our project broke our recipe deployment, due to the recipe executor no longer being able to find `uuid`.

Investigating, the problem is with this code:

```
public static IServiceCollection AddIdGeneration(this IServiceCollection services)
        {
            services.TryAddSingleton<IIdGenerator, DefaultIdGenerator>();
            services.TryAddSingleton<IGlobalMethodProvider, IdGeneratorMethod>();
            return services;
}
```
in: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Entities/ServiceCollectionExtensions.cs

If any implementations of `IGlobalMethodProvider` are registered before this code runs, `IdGeneratorMethod` won't get registered due to how `TryAddSingleton` works, detailed in this SO answer: https://stackoverflow.com/a/48187842/182568

**Comment by jtkech** [comment]
If you register it through a module startup, there is an order property that you could use. If you were registering it at the app level, there is an helper which allows you to register it at the tenant level and which also have an order parameter. Not closed to my computer, i will show you if you need it.

**Comment by marlon-tucker** [comment]
I just followed another implementation of `IGlobalMethodProvider` as an example, all the others in the OrchardCore code base are registered via `AddSingleton` rather than the above `TryAddSingleton`. 

I'm almost certain the above code snippet should read as follows:

```
public static IServiceCollection AddIdGeneration(this IServiceCollection services)
{
            services.TryAddSingleton<IIdGenerator, DefaultIdGenerator>();
            services.AddSingleton<IGlobalMethodProvider, IdGeneratorMethod>();
            return services;
}
```

If multiple places are calling `AddIdGeneration` and the original code was trying to guard against that, an alternative mechanism needs to be used IMO.

**Comment by jtkech** [comment]
Yes, you're right, good catch, i will think about another pattern, thanks.

**Comment by jtkech** [comment]
So, i suggest to use the following which also checks the implementation type.

    services.TryAddEnumerable(
        ServiceDescriptor.Singleton<IGlobalMethodProvider, IdGeneratorMethod>());

I will try it.

**Comment by marlon-tucker** [comment]
Oh ok, that's new to me as well, interesting.
