### ISSUE TITLE
How to minimze  the OrchardCore ?

### ISSUE THREAD

**Issue by wjkhappy14** [OrchardCMS/OrchardCore#2140]
maybe  orchardcore is too complex,just want   some nessary  core projects, so how   to do ?   Is anyone  has the same idea ?

**Comment by psijkof** [comment]
A good way to get to know Orchard Core is just creating an empty web site project and add a reference to for example OrchardCore.Application.Cms.Targets via NuGet, change the startup to .AddOrchardCms() and .UseOrchadCore() and run the project.

Then your exploration can start and more and more documentation is completed and blogs appear.

I guess over time when the code stabilizes and is feature complete, more guidance can be found (or contribute!)

**Comment by sebastienros** [comment]
All these projects are necessary.
