### ISSUE TITLE
How to specify additional HTTP content types for static files?

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#2144]
I try to run Ooui front end in my theme
It required `wasm` and `dll` extension to be servable

How to enable this?

Tryed following code, but without any luck
``` C#
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.StaticFiles;
using OrchardCore.Modules;

namespace TheConferenceTheme
{
    public class Startup : StartupBase
    {
        public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            var provider = new FileExtensionContentTypeProvider();
            provider.Mappings[".wasm"] = "application/wasm";
            provider.Mappings[".dll"] = "application/dll";
            app.UseStaticFiles(new StaticFileOptions { ContentTypeProvider = provider });
        }
    }
}
```

**Comment by jtkech** [comment]
@sebastienros

So, currently we use.

    app.UseStaticFiles(new StaticFileOptions
    {
        RequestPath = "",
        FileProvider = fileProvider
     });

Hmm, maybe we would need to use.

    var options = serviceProvider.GetRequiredService<IOptions<StaticFileOptions>>().Value;
    options.RequestPath = "";
    options.FileProvider = fileProvider;
    app.UseStaticFiles(options);

So that people could use something like this.

    services.Configure<StaticFileOptions>(options =>
    {
        var provider = options.ContentTypeProvider as FileExtensionContentTypeProvider ??
            new FileExtensionContentTypeProvider();

        provider.Mappings[".wasm"] = "application/wasm";
        provider.Mappings[".dll"] = "application/dll";
        options.ContentTypeProvider = provider;
    });
