### ISSUE TITLE
Body Part in Blog Post

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#2145]
The Text Editor is not suitable for RRL Languages because I can't change Text direction.

**Comment by sebastienros** [comment]
Is the issue with the current editor we are using, or we are just missing some configuration?
Would you like to improve it in a PR?

**Comment by khoshroomahdi** [comment]
Yes. The current editor. There isnt any option for change Text direction. RTL or LTR

**Comment by agriffard** [comment]
@Skrypt In the culture settings branch, do you have some kind of CultureManager that allows you to determine if the current culture is LTR or RTL?
Then, can you make an improvement on the Wysiwyg Editor to use it? 
With trumbowyg, it seems you can have this option in the langs: `_dir: 'rtl'`

**Comment by agriffard** [comment]
Related: #1740

**Comment by Skrypt** [comment]
Exactly

**Comment by sebastienros** [comment]
Now we have the RTL information based on the current culture, please try to update the editor to add the `dir` property to it.

**Comment by sebastienros** [comment]
You can also work on making the admin theme working in RTL too, by changing the css with the `.rtl` class. Are you interested in helping with it?

**Comment by hishamco** [comment]
@sebastienros correct me if I'm wrong, I think I resolve this issue after we support RTL to TheAdmin theme
