### ISSUE TITLE
Categories Blog Posts

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#2146]
How can I Add a category for Blog Post

**Comment by khoshroomahdi** [comment]
It would be as Blog Post Item by default. another thing I think keywords are necessary for Blog Post it should be enabled by default

**Comment by pgy866** [comment]
This is the way I used to categorize blog posts. I don't know if the correct way is this.....

Look,
Can you meet your needs?

![2](https://user-images.githubusercontent.com/28694676/43334161-2e6947be-91ff-11e8-9e72-1c1eb866b108.gif)

**Comment by pgy866** [comment]
In addition, when editing Edit BlogPostType, you can fill in the name of the category in the Permalink field.Change the URL path value of the classification

**Comment by sebastienros** [comment]
I am actively working on TAxonomies support, in the meantime you can only create a text field and add coma separated values to it

**Comment by pgy866** [comment]
I saw at Roadmap that Taxonomies was implemented from the beginning, to the final Backlog, would he be implemented?

**Comment by sebastienros** [comment]
Taxonomies is in the Backlog, it was never implemented, and I am currently doing it.
