### ISSUE TITLE
Autoroute (OrchardCore.Autoroute) More flexible custom URL path settings

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2147]
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Autoroute/README/
Autoroute (OrchardCore.Autoroute) More flexible custom URL path settings
![_20180727223056](https://user-images.githubusercontent.com/28694676/43328612-0c2b33c8-91f1-11e8-8c87-2f62eea41af0.png)

**Comment by sebastienros** [comment]
We are using Liquid which is the outmost flexible solution
