### ISSUE TITLE
How do I add a count field for article traffic in an article and store it in the database?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2149]
How do I add a count field for article traffic in an article and store it in the database?

**Comment by pgy866** [comment]
Google Analytics is designed to analyze the source of site visitors! very good!

Used to record statistics on accessing member homepages between members in the station! For example, A member and b member visit the c member's homepage! c members can enter their own member interface to display the member name and statistical visits of a.b members who have access to their homepage. It seems that this is a bit complicated!


To be a member background interface for the members in the station! Each member has their own home page and backstage! A bit like some simple parts of Facebook! Of course, if the orchard core background menu can freely set each access permission and display hiding of the menu, it will be even better!

**Comment by sebastienros** [comment]
You can create a custom part to count the views and store the result in the database if you can't use an analytics tool.
