### ISSUE TITLE
Is there an Orchard Core CMS marketplace for additional themes?

### ISSUE THREAD

**Issue by adrian109** [OrchardCMS/OrchardCore#2157]
Hi,

I am a .NET developer who has been asked by a local youth football club to redesign their website [www.pinewoodfc.com](www.pinewoodfc.com) ideally using a CMS so that they can administer there own content.

I have been looking into .NET CMS options in no particular order:
1. DotNetNuke (DDN)
2. Umbraco
3. Orchard Core CMS

I would like to use Orchard Core CMS for the following reasons:
1. It's being rebuilt on .NET Core
2. Good community contributions

I'm not 100% sure the best approach for implementing a new CMS website using Orchard Core CMS.

I found this post:
 [http://www.ideliverable.com/blog/getting-started-with-orchard-core-as-a-nuget-package](http://www.ideliverable.com/blog/getting-started-with-orchard-core-as-a-nuget-package)

Essentially the steps for creating the site are as follows:
1. Create a new empty .NET Core web app
2. Add a nuget package reference to
**OrchardCore.Application.CMS.Targets** 
3. Modify the **Startup.cs**  class

Add the line: ```services.AddOrchardCms();```
to the **ConfigureServices**  method.

Next, in the **Configure**  method, replace the lines
```
app.Run(async (context) =>
{
await context.Response.WriteAsync("Hello World!");
});
```
with ```app.UseOrchardCore();```

Following the steps above has got me to the point of loading the Orchard site setup screen.

I selected a Blog site.

I would like to know:
1. Are there any marketplace sites that have additional recipes and/or themes that I could use instead of the Blog receipe and the default themes?
2. If I have to create my own recipe and theme what's the best approach for doing this?
3. How can I visualise the positions for the content zones within the layers, is there a theme editor tool?

Ideally I want to change the images and colours to match those of the football club and need a way forward to achieve this.  Is there a way to copy an existing recipe / theme and modify it to my needs?

**Comment by sebastienros** [comment]
You can duplicate one of the themes (we want to call them templates) and adapt them to your needs.
The ultimate goal is to have more themes/templates available in Nuget directly. We will also provide more themes in the core solution.

There is no good article to create a site from scratch right now.
Maybe take a look at his article: https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Themes/README/

**Comment by sebastienros** [comment]
Creating this generic issue: https://github.com/OrchardCMS/OrchardCore/issues/2173
