### ISSUE TITLE
How i deploy my orchard website as a html static website?

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#2159]
#2119 ,thanks to @sebastienros ,but it is not what i want.
   There are  many Static Site Generators,like jekyll, i want deploy my orchard website to two server, one is orchard website, the other is html static webiste which is generated by orchard website. 
In orchardcore,there is liquid template, whether is there a soltion to generate html website?

**Comment by jnucpz** [comment]
@siyamandayubi thanks. it is necessary to take care of Website Security .

**Comment by siyamandayubi** [comment]
why not using two instances of Orchard. One front-end and one back-end. And exporting content from backend and import it into the front-end? Does the same thing, isn't it?

**Comment by jnucpz** [comment]
@siyamandayubi  ,Yes, this solution works for security.

 How i export content and import it between two instances?  thanks for your answer.

**Comment by siyamandayubi** [comment]
@jnucpz In the admin mode, 
1) Navigate to the Content -> Import Export -> Deployment Plans,
2) Create a new Deployment Plan
3) Then in the list of Deployment Plans, click on it (not on the Edit button, but on the name of the Plan)
4) Add necessary steps such as all ContentTypes, Content etc
5) Then you can run the plan, the result is a zip file containing a recipe file
6) You can import the recipe in another instance

**Comment by pgy866** [comment]
I also need this one, there is such a plugin in WordPress,
"https://wordpress.org/plugins/super-static-cache/"
"https://github.com/hitoy/super-static-cache",
Orchard Core is very fast, this demand is safe, and better SEO

**Comment by jnucpz** [comment]
@siyamandayubi thank you. I want  a solution like Jekyll. With orchard, i don't know how to reach this goal.

**Comment by sebastienros** [comment]
There is no existing way to do this right now. 

Your solutions:
- Use a site download like https://www.httrack.com/ to generate a static copy of the Orchard site
- Use the GraphQL module to query content from local scripts, some extensions exist in sites generators like Hugo, Jekyll to use GraphQL data
- Create a module that exports your content to Jekyll documents

You can also create a custom Deployment step that would generate a static site.

**Comment by Skrypt** [comment]
Jekyll uses Liquid templates so basically using Orchard Liquid templates and exporting them to a Jekyll solution should also work at some point. I'm sure there's more details about it ; and it's never been tested.

**Comment by jnucpz** [comment]
thanks ,i will test it @sebastienros ,@Skrypt

**Comment by pgy866** [comment]
https://github.com/Wyamio/Wyam/issues/300

**Comment by surfmuggle** [comment]
> [Wyamio/Wyam#300](https://github.com/Wyamio/Wyam/issues/300)

Wyam is a simple to use, highly modular, and extremely configurable static content generator that can be used to generate web sites, produce documentation, create ebooks, and much more. 
https://github.com/Wyamio/Wyam

**Comment by surfmuggle** [comment]
> Maybe it is better to explain a little more, why do you want to do that. what is the requirement. If the concern is performance, enabling the caching is a solution

@siyamandayubi 
A static html page reduces the attack surface and the requirements on the hosting server.

**Comment by sebastienros** [comment]
FYI I demoed some integration between Orchard and Wyam today. It included using the graphql endpoint and input sources, and some liquid module to render the content with Liquid (if you prefer it to Razor). I'll release a sample project soon, once I have pushed my modules to the wyam project.
