### ISSUE TITLE
Does Orchard core automatically back up the copy and recovery features of the site on a regular basis?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2160]
Is there a plan to automatically back up the site's copy and recovery features in Orchard core?

**Comment by sebastienros** [comment]
No it doesn't, but you can create a deployment to extract all the content. We have an open issue to create Workflow activities to automate it.

https://github.com/OrchardCMS/OrchardCore/pull/2156

**Comment by pgy866** [comment]
Thank you, in the recent study, I saw this method, very good.
