### ISSUE TITLE
Consider using Singleton Schema for GraphQL

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#2164]
Probably we should use Singleton GraphQL schema instead Scoped one.
I tried to integrate GraphQL Web Socket Subscriptions
https://github.com/graphql-dotnet/server to current GraphQL implementation in Orchard Core.
I face to an issue that `GraphQLWebSocketsMiddleware` and `GraphQLHttpMiddleware` relie on Singleton schema please see 
https://github.com/graphql-dotnet/server/issues/56
I tried to create my own Middleware instead of  GraphQLWebSocketsMiddleware but it wasn't that easy because of dependency chains. Eventually, it was easier to make our ContentSchema as a singleton.

Benefits I see
- It may allow as to get rid off from our own GraphQLMiddleWare and use which is out of the box (not sure about this need to check).
- Probably we do not need ISchemaService in our implementation and it will be easier to create/use multiple GraphQL Schemas (not only ContentSchema)
- It may help us with futher integration like GraphQL WebSockets

**Comment by rserj** [comment]
>Maybe when you use the word 'singleton' you mean in the context of the DI.
Yes, I meant Single instance per Tenant

**Comment by sebastienros** [comment]
It is, all services registered as singleton are per tenant.

**Comment by Jetski5822** [comment]
Uh we want multiple schemas? 🤔

**Comment by sebastienros** [comment]
Well, one per tenant obviously (at least), which has always been the case

**Comment by rserj** [comment]
I was thinking about using standart Middleware like below
```
app.UseGraphQLHttp<ContentSchema>(new GraphQLHttpOptions(){Path = "/api/graphql" });
app.UseGraphQLHttp<BusinessSchema>(new GraphQLHttpOptions(){Path = "/api/myEndPoint" });
```
UseGraphQLHttp register [GraphQLHttpMiddleware](https://github.com/graphql-dotnet/server/blob/c69c6dcb15b3722dc40d6c908f944d96c5a6d656/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs), GraphQLHttpMiddleware  accepting TSchema in a constructor, as I know only Singleton registered instances can be resolved in Middleware constructors.

The same happening with [UseGraphQLWebSocket<TSchema>](https://github.com/graphql-dotnet/server/blob/c69c6dcb15b3722dc40d6c908f944d96c5a6d656/src/Transports.Subscriptions.WebSockets/GraphQlWebSocketsMiddleware.cs), for GraphQL Websocket subscriptions, I must have singleton registered schema. Personally I also not happy about this, I would prefer scoped schema and caching, like we have now, but it doesnt work with current [WebSocket ](https://github.com/graphql-dotnet/server) implementation, please see https://github.com/graphql-dotnet/server/issues/56

**Comment by sebastienros** [comment]
I think that should work. Middleware are also registered uniquely per tenant. We just need to make the single instance use `IHttpContextAccessor` to resolve the types. But the issue is when the schema changes dynamically (new part, new type, ...) then the schema is not updated. This pattern in the library is just wrong, it should have required a factory of some sort to retrieve the schema, not the schema itself.

**Comment by sebastienros** [comment]
Oh, and now I see where the inspiration for the middleware is coming from. And I am glad that my optimizations are in the original mw too ;) I will file an issue on their repos.

**Comment by rserj** [comment]
Thank you @sebastienros, this is what I did for now. I registered Schema and All dependent: Mutations, Queries and Subscriptions as Singleton, and I'm using IHttpContextAccessor to resolve scoped services.
It works for me but I'm not sure if we should do the same in Orchard, because of dynamical structure of ContentTypes and Parts, theoretically, we could register Schema as Singleton and rebuild it once something gets changed.

**Comment by jtkech** [comment]
Just for infos, currently the problem i see is that the `ContentSchema` holds some graphql types which are scoped services and which use other scoped services (which can be disposed) through their `Resolver`, e.g `IContentManager`, `ISession` ... So, what i'm first trying to do for testing is to make all these types as transient services which use `IHttpContextAccessor` and can be cached. There is also a `IDependencyResolver` that i register for testing as a singleton (or transient) and which also use `IHttpContextAccessor`.

Some unit tests are now working but not all.

**Comment by rserj** [comment]
@jtkech Yeh I played with IDependencyResolver too, I face to issue when scoped instances are Disposed but I still get the same instances via DI and getting AlreadyDisposed exceptions, while trying use them, I didn't experiment deeply, probably you can find a solution. Thanks

**Comment by sebastienros** [comment]
I updated their existing issue with a small change that would solve it: https://github.com/graphql-dotnet/server/issues/107

I also have some local changes for the `IHttpContextAccessor` which I will push, but I have some other concerns about the classes that inherit from `QueryFieldType`. I think we should not use DI for these, just instantiate them (see `ContentItemQuery`) or just have the `IQueryFieldTypeProvider` interface.

**Comment by jtkech** [comment]
Just for infos, i was just forgetting some types but now all unit tests pass.

This by using all graphQL types as singleton but using `IHttpContextAccessor`.

I will retry with all as transient services.
