### ISSUE TITLE
the orchardCore support soap or wcf?

### ISSUE THREAD

**Issue by HuangWeidong1** [OrchardCMS/OrchardCore#2174]
Does The orchardCore support soap ?

**Comment by Skrypt** [comment]
Most of Orchard Core Webservices uses REST API's but I believe that you can still use SOAP with .NET Core. Though what would you need to use SOAP for?

**Comment by sfmskywalker** [comment]
I had a use case for SOAP in .NET Core a while back when implementing a web hook handler for Salesforce. There’s an open source library that implements soap in .NET Core, but ultimately ran into a limitation with it and ended up parsing the Salesforce XML messages myself (bypassing soap protocols entirely and just going straight to the notification elements).

**Comment by Skrypt** [comment]
You can use REST with SOAP but not the opposite. Plus SOAP is more "rigid" as it needs a contract on the client side and will fail if there's any change on the server side.
