### ISSUE TITLE
Developer tools

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2178]
- Action to dump a full content item document from the content items list, including drafts or old versions
- Action to dump a content type/part definition for recipes

Or maybe just advertise the fact that it can be done with deployments?

**Comment by agriffard** [comment]
Implemented in `console_log` Liquid filter: https://docs.orchardcore.net/en/dev/docs/reference/modules/Contents/#logging-to-the-browser-console
