### ISSUE TITLE
Replacing IRunningShellTable beta1 -> beta2

### ISSUE THREAD

**Issue by FreshRob** [OrchardCMS/OrchardCore#2183]
### in 1.0.0-beta1-3667 this worked

```csharp
 services.AddModules(msc =>
            {
                msc.WithConfiguration(Configuration);
                msc.WithTenants();
                msc.Configure(service =>
                {
                    service.Replace(ServiceDescriptor.Singleton<IRunningShellTable, SiteNameRunningShellTable>());
                    AdditionalModuleConfiguration(services);
                });
            });
```

###  in 1.0.0-beta2-67581 no luck

```csharp          
services.AddOrchardCore().WithTenants().AddMvc().ConfigureServices(service =>
 {
         service.Replace(ServiceDescriptor.Singleton<IRunningShellTable, SiteNameRunningShellTable>());
         AdditionalModuleConfiguration(services);
});
```

**Comment by jtkech** [comment]
As i remember `msc.Configure()` was just retrieving the `ApplicationServices`.

So now, normally you can just use.

    services.AddOrchardCore().WithTenants().AddMvc();
    services.Replace(ServiceDescriptor.Singleton<IRunningShellTable, ...>());

Or.

    services.AddOrchardCore().WithTenants().AddMvc()
        .ApplicationServices.Replace(ServiceDescriptor.Singleton<IRunningShellTable, ...>());

Then, if `AdditionalModuleConfiguration()` really needs to act on the tenant services collection (not app services) as a module would do, you have to use our `ConfigureServices()` which have an optional order parameter. But if it also needs to act on the application services, just do.

    services.AddOrchardCore().WithTenants().AddMvc();
    services.Replace(ServiceDescriptor.Singleton<IRunningShellTable, ...>());
    AdditionalModuleConfiguration(services);

You can also do an helper which acts on an `OrchardCoreBuilder` and in which you can retrieve `builder.ApplicationServices` and, but just if you really need it, also use our `ConfigureServices()`.

**Comment by FreshRob** [comment]
@sebastienros we use custom headers to define the tenant

**Comment by jtkech** [comment]
@FreshRob cool, happy to know that it works.
