### ISSUE TITLE
Deployment steps missing

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2186]
- [X] Site settings (checkbox for each of the core ones)
- [X] Home Route (site settings step)
- [ ] Assets (per folder, including root)
- [x] Workflows (workflow types, not instances)
- [X] Queries
- [X] Templates

**Comment by siyamandayubi** [comment]
I am volunteer to work on workflows in case there is no work in progress already

**Comment by siyamandayubi** [comment]
PR #2281 has been created

**Comment by psijkof** [comment]
Are custom settings supposed to be deployed/exported as regular contenttypes and content?

**Comment by sebastienros** [comment]
To export the assets in a media field, we should have a handler when a content item is exported, and the field would provide an implementation that would add the asset to the export context.
