### ISSUE TITLE
Contents permission Exact Parts？

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2190]
Exact Contents Feature's permission control "Exact Contents Parts" can be added to the "Content Type", Exact control content type permission control。
Can it be done like this? Very good

![3](https://user-images.githubusercontent.com/28694676/43816052-7dbab122-9b05-11e8-9190-8e992e7cb94b.gif)
![3](https://user-images.githubusercontent.com/28694676/43816616-3070d704-9b08-11e8-80df-5726f69ab133.gif)

**Comment by sebastienros** [comment]
No, too much work, we'd need to find groups of permissions to be able to create the columns that are in common. But thank you for the suggestion.

**Comment by HengzheLi** [comment]
@pgy866    haha, odoo? good. as I still want to integrate it with OC in the future.

**Comment by pgy866** [comment]
@HengzheLi I'm surprised! If integrated odoo! What a wonderful job!

**Comment by pgy866** [comment]
@sebastienros Precise control of permissions should be important to a content management system! The workload is a bit big! Can open the markup backlog?
As a result of the improvement in the future?
