### ISSUE TITLE
User adds extensible attribute field support

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2191]
Add extensible attribute field support for users (eg user avatar images, user addresses, user descriptions, etc.)

Or   can directly add an existing content type to the extended content field for the user attribute.

**Comment by Skrypt** [comment]
Right now you can do this by creating a module that extends the IUser interface. Look at the demo project for an example. Also, I'm not sure we want to be able to set the IUser fields through having an exposed content type like we had in 01.

**Comment by pgy866** [comment]
Look at the demo project for an example? Is it source code? Still have help documentation in this regard?

**Comment by agriffard** [comment]
You can now use Cutsom User Settings.
