### ISSUE TITLE
Consolidate all mandatory OrchardCore projects

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2195]
And have `OrchardCore` and `OrchardCore.Abstractions`.
- all `OrchardCore.Environment.XYZ` 
- Modularity

We keep the ones related to modules, data access, or web stacks (mvc, nancy) separate.

@Jetski5822 @jtkech What do you think

**Comment by jtkech** [comment]
Okay, i will think about it but not sure i fully understand, i will need some clarifications.

**Comment by Jetski5822** [comment]
Not sure I like to be honest.

Why do we want to consolidate?

**Comment by sebastienros** [comment]
Faster build time, and restore. In the end it's just a few projects that are merged. I'll show you on Tuesday. It also let me find some projects references that were wrong, or component in wrong places.

The projects that got merged were in the end all in the transitive dependency graph (module, extensions, tenants, shell, cache, commands, entity).

**Comment by Skrypt** [comment]
Just tested building this branch to see if it was compiling faster than what we actually have. I have seen a small difference of 5 seconds on the first build since it's retrieving Nuget packages. After that the building time is almost equal from what we have already.

**Comment by agriffard** [comment]
Can be closed since #2199 has been merged?
