### ISSUE TITLE
Can have POST action in apicontroller(s) in branch jsonapi

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#2196]
Currently, seems that all apicontroller's action are only accept GET method. 

Is it possible to accept POST method or this have been on the plan?

And by the way, can I query site's setting using api in current jsonapi branch's code

Thanks

**Comment by sebastienros** [comment]
I assume that's fine to accept POST too. Please create a PR with the apis you found like this.
Why are you mentioning the jsonapi branch, is that specific to this branch?

I don't think there is an endpoint for site settings. Maybe it should be part of a graphql query, that would also check for permissions.

**Comment by HengzheLi** [comment]
I thought all the api related things are located in jsonapi branch as it is not merged into dev yet. 

So where should the PR go if I can make it? JSONAPI or DEV

**Comment by HengzheLi** [comment]
By the way, where is the SiteSetting stored? I thought it is some kind of contentitem like O1. But I have check all of database table and still can not find it.

**Comment by Skrypt** [comment]
It's in the document table stored as json in the "content" column. One of the rows is the sitesettings you can find the right row by finding "OrchardCore.Settings.SiteSettings, OrchardCore.Settings" in the "Type" column.

**Comment by HengzheLi** [comment]
OK. I got it. Thanks a lot.

**Comment by HengzheLi** [comment]
Seems like that the GraphQL Mutation can do the same thing as POST method will do (Insert, Update, Delete).
After learning the graphql code I think there is no need to implementation POST method and  this issue can be closed as the Insert, Update and Delete thing can be perform using graphql mutation sentence.
