### ISSUE TITLE
Cultures caching

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#2197]
After PR #1892 seems we need to cache the culture that used in `AvailableSystemCultures` or move into underlying localization APIs

**Comment by Skrypt** [comment]
Those culture are already cached, I'm not sure what you mean.

**Comment by hishamco** [comment]
@Skrypt can you show me where they 're cached?

**Comment by Skrypt** [comment]
https://github.com/aspnet/Localization/blob/9834a277280f53afc88f1c17110ff2fd7ea8e802/src/CultureInfoGenerator/Program.cs

**Comment by hishamco** [comment]
I remembered `CultureInfoList` from the early days of ASP.NET 5, but it was deprecated and removed from the underlying localization APIs, so we need to provider a supported cultures ourselves when we configure localization options

So that's why I asked for caching the cultures earlier

**Comment by Skrypt** [comment]
From what I understand after reading this long issue posts. Now you get the culture list from CultureInfo.GetCultures like we do in Orchard Core. .NET Core will cache already the list of culture your OS is returning from your OS and also allow for any other unknown culture. It does so with Windows and Unix based systems. Though there is still some issues about retrieving the InstalledUICulture from Unix based systems like OS X (an other topic).

The SupportedCultures are required by the .NET Core provided Localization Middleware. The Middleware uses RequestCultureProviders to be able to alter the CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture based on default providers already implemented as part of the Middleware. The Middleware includes QueryString, Cookie, AcceptLanguageHeader providers as soon as you add it to the DI service chain. The DefaultCulture + (SupportedCultures + SupportedUICultures) set ; are the cultures that your website will allow. Those cultures cannot be added without restarting the Localization Middleware itself. Also there is a RouteDataRequestCultureProvider implemented that is part of the Localization extensions provided in the .Net Core framework.

**Comment by hishamco** [comment]
AFAIK while working on localization APIs in ASP.NET Core from the early days, `CultureInfoList` are introduced to cache all the cultures, and after awhile this was deprecated because there's no guarantee that all the cached cultures will not change, because each OS update may affect on cultures, languages, borders and sort type of things

FYI you can check the issue https://github.com/aspnet/Localization/issues/98 at the end the team decide to do this https://github.com/aspnet/Localization/issues/111 where we say good bye for `CultureInfoCache.CultureInfoList` 😄

**Comment by sebastienros** [comment]
I looked at the code and it seems to me that this list is only used in the view to add culture. If that's the case then there is no reason to cache anything. Or is it used in a hot path?

**Comment by hishamco** [comment]
IMHO we can provide those cultures from the underlying localization APIs as first class for any reason that is required, because hitting `Culture()` action coz to call that list again and again

**Comment by sebastienros** [comment]
The same way many pages work. This one will be hit once every year on a live site, and there is not even proof that it's slow. So nothing to worry about here. We can fix it when we actually need to.

**Comment by hishamco** [comment]
Ok Seb
