### ISSUE TITLE
CultureInfo.InstalledUICulture on Mac OS X

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2198]
On Mac OS X this always returns InvariantCulture. This is one of the reasons why by default I was setting the culture to InvariantCulture unless CultureInfo.InstalledUICulture would return a proper value this would fix it. Also, as you can see the Culture Providers are returning also an InvariantCulture by default instead since it never found the InstalledUICulture.

<img width="1378" alt="capture d ecran 2018-08-09 a 09 20 20" src="https://user-images.githubusercontent.com/3228637/43901440-7db9d1ac-9bb5-11e8-9326-c34ecd8d145d.png">

Here is the logic of how it works : https://github.com/dotnet/coreclr/tree/0fbd855e38bc3ec269479b5f6bf561dcfd67cbb6/src/System.Private.CoreLib/src/System/Globalization
As we can see it behaves differently from Windows to Unix systems intentionnally.

**Comment by Skrypt** [comment]
Here is what I did to fix the issue simply without changing the behavior of System.Globalization and the Localization middleware.

```C#
@model SiteSettingsViewModel
@inject OrchardCore.Modules.IClock Clock
@using System.Globalization
@using System.Runtime.InteropServices

<fieldset class="form-group" asp-validation-class-for="SiteName">
    <label asp-for="SiteName">@T["Site name"] <span asp-validation-for="SiteName"></span></label>
    <input asp-for="SiteName" class="form-control" />
    <span class="hint">@T["The site name."]</span>
</fieldset>

<fieldset class="form-group" asp-validation-class-for="BaseUrl">
    <label asp-for="BaseUrl">@T["Base url"] <span asp-validation-for="BaseUrl"></span></label>
    <input asp-for="BaseUrl" class="form-control" />
    <span class="hint">@T["Enter the fully qualified base URL of the web site."]</span>
</fieldset>

<div class="row">
    <fieldset class="form-group col-lg-6" asp-validation-class-for="TimeZone">
        <label asp-for="TimeZone">@T["Default Time Zone"] <span asp-validation-for="TimeZone"></span></label>
        <select asp-for="TimeZone" class="form-control">
            <option value="">@T["Local to server"]</option>
            @foreach (var timezone in Clock.GetTimeZones())
            {
                <option value="@timezone.TimeZoneId" selected="@(Model.TimeZone == timezone.TimeZoneId)">
                    @timezone
                </option>
            }
        </select>
        <span class="hint">@T["Determines the default time zone used when displaying and editing dates and times."]</span>
    </fieldset>

    <fieldset class="form-group col-lg-6" asp-validation-class-for="Culture">
        <label asp-for="Culture">@T["Default Culture"] <span asp-validation-for="Culture"></span></label>
        <select asp-for="Culture" class="form-control">
            @if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {

                <option value="">@T["System ({0} | {1})", CultureInfo.InstalledUICulture.Name, CultureInfo.InstalledUICulture.DisplayName]</option>
            }
            else
            {
                <option value="">@T["System ({0})", CultureInfo.CurrentCulture.NativeName]</option>
            }

            @foreach (var culture in Model.SiteCultures)
            {
                <option value="@culture" selected="@String.Equals(Model.Culture, culture.Name, StringComparison.OrdinalIgnoreCase)">
                    @culture.Name | @culture.DisplayName
                </option>
            }
        </select>
        <span class="hint">@T["Determines the default culture used"]</span>
        <p>@Html.ActionLink(T["Add or remove supported cultures for the site"].Value, "Culture")</p>
    </fieldset>
</div>
```

**Comment by Skrypt** [comment]
@hishamco What's your opinion on that one? I just found that you posted a lot of blog posts about localization on .NET Core.

**Comment by Skrypt** [comment]
Tested this on Ubuntu 18.04.1 LTS (Bionic Beaver) and it's working as expected.
Maybe the issue is only with Mac OS X.

**Comment by hishamco** [comment]
@Skrypt Yep there 're some confusions & issues in localization & cultures in OSs, but I'm not sure why you set the default culture instead of pick it up from underlying localization APIs using:
```csharp
var requestCultureFeature = context.Features.Get<IRequestCultureFeature>();
var requestCulture = requestCultureFeature.RequestCulture;
```

**Comment by sebastienros** [comment]
We need to display the name of the culture that would be used if no culture was set in SuppotedCultures, a.k.a the System Culture, the one from the server OS.

**Comment by Skrypt** [comment]
The Localization Middleware affects the CultureInfo.CurrentCulture and CultureInfo.CurrentUICulture and also sets the context.Features.Set<IRequestCultureFeature> so we can retrieve the current culture by these 2 different methods. We found out that using CultureInfo.CurrentCulture was working properly. I know that the documentation states that we should be using context.Features.Get<IRequestCultureFeature>() to avoid having issues in some middleware that could have been called before the Localization Middleware but it's not an issue since we set the Localization module to be called with a priority of -10. We removed the code that was using context.Features.Get<IRequestCultureFeature>() that was in a separate class "LocalCulture.GetCurrentCulture()".

@sebastienros yes, but seems like in OS X the systems returns nothing to the .NET Core Globalization API.

**Comment by sebastienros** [comment]
@Skrypt I was just answering @hishamco

**Comment by hishamco** [comment]
@sebastienros AFAIK from the early days of ASP.NET that default cultures are:
```
Culture: English (United States) (en-US)
UI Culture English (United Kingdom) (en-GB)
```
the same thing happen if no culture was set in `SuppotedCultures`

Thanks @Skrypt for you detailed explanation, seems there's a little change in Orchard Localization from ASP.NET Core Localization, so I will try to investigate on that by creating a minimal repo with the help of Travis CI to reproduce the issue while I don't have Mac OS in my laptop

**Comment by Skrypt** [comment]
I investigated a little by trying to find if I could get the value of the current OS culture from an environment var with the Mac OS X Terminal by doing a `printenv`. I found out that there's a "LANG" value in the environment vars that is outputing exactly my current OS culture "fr_CA.UTF8". Though I'm not able to get this environment var from C# through Environment.GetEnvironmentVariable("LANG") nor able to find it by doing Environment.GetEnvironmentVariables(). Theres also a var that is "USER" that I can retreive with Environment.GetEnvironmentVariable("USER"). Not sure if this is helping or not. The list of cultures itself in UNIX based OSs comes from libicu and this part seems to be fine.

**Comment by hishamco** [comment]
> Though I'm not able to get this environment var from C# through `Environment.GetEnvironmentVariable("LANG")` nor able to find it by doing `Environment.GetEnvironmentVariables()`

Strange!!

**Comment by Skrypt** [comment]
https://github.com/dotnet/corefx/issues/31808

**Comment by Skrypt** [comment]
I'm closing this since it's not a bug in Orchard Core.
