### ISSUE TITLE
empty 200 always returned , shouldn't it be 404

### ISSUE THREAD

**Issue by FreshRob** [OrchardCMS/OrchardCore#2205]
Orchard beta2

When no Default or Default stopped visiting / returns and empty 200 and not a 404

Tenants.json
```json
{
  "Default": {
    "State" :  "Stopped" 
  } ,

  "BroadbandChoicesLocal": {
    "State": "Running",
    "RequestUrlPrefix": "moo",
    "Site": "Moo",
    "Features": [
      "Site",
      "OrchardCore.Mvc"
    ]
  },
  "BroadbandChoicesLocal2": {
    "State": "Running",
    "Site": "Moo2",
    "RequestUrlPrefix": "moo2",
    "Features": [
      "Site",
      "OrchardCore.Mvc"
    ]
  }
}

```
Visit / 200 returned when Default tenant is stopped

startup.cs
```csharp
 services.AddOrchardCore().WithTenants().AddMvc();
app.UseOrchardCore();

```

homeController
```
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
```

**Comment by sebastienros** [comment]
Have you tried with the dev branch, I think we fixed it here:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Modules/ModularTenantContainerMiddleware.cs#L47

Looks like we return a 503 now. And it's a recent change.
