### ISSUE TITLE
Make Login views extensible

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2207]
Use display manager to compose the UI for the Login page and shapes for each component of this page and the others (reset password, registration).

**Comment by MatthijsKrempel** [comment]
I made a first draft here; https://github.com/OrchardCMS/OrchardCore/pull/2192/commits/4125b89d450e2d5b7c05756c5d6f935a21ee7e6a

**Comment by sebastienros** [comment]
@MatthijsKrempel why are you linking to a commit, you should link the PR, much more useful. If people start commenting on it only bad things can happen ;)

https://github.com/OrchardCMS/OrchardCore/pull/2192

**Comment by MatthijsKrempel** [comment]
Changed, next time will do it correct right away. ;)

**Comment by hishamco** [comment]
@MatthijsKrempel  did you made any progress on this one?

**Comment by MatthijsKrempel** [comment]
> @MatthijsKrempel  did you made any progress on this one?

Yes, you can look at the Login page in the OrhcardCore.Users module and see that there is room to inject additional UI components.
An example of this injection can be found in the OrchardCore.ReCaptcha module with the ReCaptchaLoginFilter.

**Comment by hishamco** [comment]
If you are interested on this one, you can push a PR

**Comment by MatthijsKrempel** [comment]
@hishamco I think it is already in?

**Comment by hishamco** [comment]
Could you please refer me to the PR if you did it?

If is that we need to close this one

**Comment by MatthijsKrempel** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/2192

**Comment by MatthijsKrempel** [comment]
Unless you want more extension points?

**Comment by hishamco** [comment]
I thought that related to ReCaptcha only, Seb if this resolve the issue, please close it

**Comment by sebastienros** [comment]
I just checked and the PR satisfies this issue.

What we need though is to document these sections:
`AfterLogin`, ... and point to the code that shows how to inject shapes in it at least.
