### ISSUE TITLE
Error with Theme from nuget and Site published and hosted on IIS

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2214]
I made an OC theme based on https://blackrockdigital.github.io/startbootstrap-resume/
The repository is available here : https://github.com/agriffard/Resume.OrchardCore

I tried to make it generated and uploaded using appveyor. To do so, I add Common.props, Directory.Build.props and a file link to Package.Build.props.

First problem was that it didn't include all the files, the result was a small .nupkg.
So, I generated it locally.

With this one, the second problem was that it didn't include the folder and file `build/Resume.OrchardCore.props`.
So, I edited it and added manually the file.

I uploaded the corresponding nuget package here: https://www.nuget.org/packages/Resume.OrchardCore/1.0.0-beta3-1

My goal is to use it in an application using OC.Cms.Targets as a custom theme by referencing the nuget package and then use the Resume recipe to create a site.
When I create such app, it works when I launch it with IISExpress, but if I published it in a folder and try to host it on IIS, using the ANCM, there is a error 500 and nothing in the logs.

@jtkech Can you help me this issue? Can you reproduce the same behavior?

**Comment by agriffard** [comment]
OK, after a few changes, there is no more Error 500.

Locally, I debugged it by executing `dotnet .\Cms.dll` and it was not working because it needed some security permissions to work. I moved it from my c:\inetpub\wwwroot\Cms to D:\Cms and it worked.
On my server, it wa because I forgot to install the latest .NET SDK.

I am still interesting if you can help me on configuring appveyor to generate the nuget package properly (Include all the files and add the buid/Resume.OrchardCore.props folder).

**Comment by jtkech** [comment]
Sorry, not so confortable with appveyor scripts, maybe i did little things around this but i don't remember very well. I think the bests for this are @sebastienros and @alexbocharov.

**Comment by agriffard** [comment]
When I execute a `dotnet build`, the result is a small dll. 
What do I have to configure to include the wwwroot files from a OC theme project?

**Comment by agriffard** [comment]
OK, I added explicitly the files I wanted as EmbeddedResource and now it works:

```  
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\css\**" />
    <EmbeddedResource Include="wwwroot\img\**" />
    <EmbeddedResource Include="wwwroot\js\**" />
    <EmbeddedResource Include="wwwroot\vendor\jquery-easing\**" />
    <EmbeddedResource Include="wwwroot\theme.png" />
  </ItemGroup>
```

The last thing I need to understand is how can I include the build\Resume.OrchardCore.props.

**Comment by jtkech** [comment]
- `OC.Commons.targets` is only common project / package properties that you can put in your project file directly, depending on your needs, but there are not mandatory. Notice that for modules / themes, in the `Build.props`, the `DebugType` is overridden to `embedded`, and we also define `EmbedAllSources = true`. But here also it's only if you want to allow people to debug into your source code.

- When you reference `OC.Theme.Targets` as a package, you don't have to import `Module.Targets.targets` neither `Theme.Targets.targets`.

- You don't have to specify the files under `wwwroot` as `EmbeddedResource`, it is done automatically. That said, when you add / remove files you have to do a real rebuild, or update a compilation item as a source file or the project file itself, what you may need to do to produce an updated package.

- Try to remove the item group which specify embedded resources in your project file and try it again. Let me know if you still have problems, then i could fork your repo and try it directly.

**Comment by agriffard** [comment]
I added this to Common.props:
```
    <DebugType>embedded</DebugType>
    <EmbedAllSources>true</EmbedAllSources>
```

Even without this, the dll was already correctly generated if I do right-click>Build (Is that what you call  real 'build' ?)
But If I execute `dotnet build` or `dotnet pack` in a cmd line, the result is a small dll and that is what appveyor.yml is configured to do.

And there is also the last problem: the build\netstandar2.0\Resume.OrchardCore.props is not packed in the .nupkg so it will not be recognized in the admin themes page when I will reference it from nuget in an OC application.

**Comment by jtkech** [comment]
Okay i will try your repo directly this night.

**Comment by jtkech** [comment]
Yes, i could repro.

- It's weird because i added a testing target to display `PackagePath` properties on building / packing. Then i could see that `Package.Build.props` is taken into account and correctly renamed to be packed with the right path `build\netstandar2.0\Resume.OrchardCore.props`. But when packing under VS, this file is not packed.

![resume](https://user-images.githubusercontent.com/8586360/44059451-bfd5a6c0-9f51-11e8-86c6-4b0ebd205a32.png)

- Then, you're right doing dotnet build / pack produces very little dll because it doesn't embed asset files, which is not the case under VS. Here seems to be a dotnet / msbuild issue.

Need more investigation.

**Comment by sebastienros** [comment]
FYI you can an older ask by putting a global.json file in the second folder. Maybe there is a regression, like in the SDK.

**Comment by jtkech** [comment]
Okay, i will try by forcing different sdk versions through a global.json.

**Comment by jtkech** [comment]
Wait a minute, i got it working.

- First i removed your .props files, appveyor.yml and so on.

- But i mainly create an empty solution folder with only nuget.config, then put your project (without the above files) under a `Resume.OrchardCore` subfolder.

- Then the asset files are now embedded through VS and the cli, and `build\netstandar2.0\Resume.OrchardCore.props` is also packed.

Maybe it's only due to the folders structure, so i will retry it by reusing the files i removed.

**Comment by sebastienros** [comment]
One if the best feelings, narrowing down an issue one step at a time, it's like hunting.

**Comment by jtkech** [comment]
So, same issues when reusing your files.

In fact it was due to this line in your `Common.props` file.

    <TargetFrameworks>netstandard2.0</TargetFrameworks>

Replacing it with `TargetFramework` without the `s` or removing the line, then it works.

**Comment by agriffard** [comment]
Thank you so much @jtkech, it works now. I just removed without the 's'.
