### ISSUE TITLE
Wysiwyg editor not reediting well html with liquid syntax

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2218]
Such a code is not displayed well in source mode when you reedit it with an HtmWidget whose HtmlField has a Wysiwyg Editor:
`<img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{ "img/Profile.jpg" | asset_url }}" alt="">`

It shows this:
`<img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{ " img="" Profile.jpg"="" |="" asset_url="" }}"="" alt="">`

**Comment by grzegorzb1990** [comment]
The problem lies in trumbowyg.js (WYSIWYG editor). The source code is parsed to dom nodes. There 
is need to write pluggin to Trumbowyg or change editor. Unfortunately I can't find another editor with liquid  support.

**Comment by sebastienros** [comment]
Code Mirror is no __WYSIWYG__ ;) But we do use it everywhere we need to edit code or html, or razor or liquid.

**Comment by hishamco** [comment]
Oops, you are right seb 😄

**Comment by Franklin89** [comment]
I just came across the same issue while writing a blog post. I wanted to copy paste a snippet of a liquid template that contained the following:
```
{{ Model.Content.ContentsMetadata | shape_render }}
```

If you click save draft an exception is thrown and the post will not be saved.

![image](https://user-images.githubusercontent.com/4151467/44343191-927fe780-a48d-11e8-81e7-c2c0c946a916.png)

**Comment by agriffard** [comment]
Same format problem still existing with the latest version of Trumbowyg when you put Liquid code in html attributes.

**Comment by jtkech** [comment]
@agriffard 

> Such a code is not displayed well in source mode when you reedit it with an HtmWidget whose HtmlField has a Wysiwyg Editor:

    `<img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{ "img/Profile.jpg" | asset_url }}" alt="">``

Just tried through mr PR #4708 where i added a liquid validation. It fails to parse your liquid, you need to replace `src="{{ "img/Profile.jpg" | asset_url }}"` with `src="{{ 'img/Profile.jpg' | asset_url }}"`. Then it works.

@Franklin89 

It is du to an incomplete template contextualization where the `Model` is not set, so it fails when using it through `Model.Content.ContentsMetadata`. This is also fixed through #4708, but only for parts, not yet for field.

**Comment by agriffard** [comment]
ok, it works with quotes aroiund the first parameter instead of double quotes.
