### ISSUE TITLE
api/contentitem not exposed?

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2224]
There is an API to retrieve a content item by its id, but it doesn't seem to be exposed with a friendly route. I know I have demoed it by the past though.

Also document it.

**Comment by agriffard** [comment]
`api/content/{contentItemId}` seems to be a friendly route.

https://github.com/OrchardCMS/OrchardCore/blob/96eb928724673c9335399954e090840bf2f6eaeb/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs#L26

but, yes, there should be some documentation about the available api methods.
