### ISSUE TITLE
Razor layout doesn't work

### ISSUE THREAD

**Issue by kamikyo** [OrchardCMS/OrchardCore#2225]
![image](https://user-images.githubusercontent.com/7645337/44082064-d85fad80-9fe2-11e8-852d-045dcf6fe7e0.png)
Login as a module
Get.cshtml like this:
```
@{ 
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "_Layout";
}
```
I always get the error:
```
InvalidOperationException: The layout view '_Layout' could not be located. The following locations were searched:
/.Modules/Login/Views/Index/_Layout.cshtml
/.Modules/Login/Views/Shared/_Layout.cshtml
/Areas/Login/Views/Index/_Layout.zh-CN.cshtml
/Areas/Login/Views/Index/_Layout.zh-CHS.cshtml
/Areas/Login/Views/Index/_Layout.zh-Hans.cshtml
/Areas/Login/Views/Index/_Layout.zh.cshtml
/Areas/Login/Views/Index/_Layout.cshtml
/Areas/Login/Views/Shared/_Layout.zh-CN.cshtml
/Areas/Login/Views/Shared/_Layout.zh-CHS.cshtml
/Areas/Login/Views/Shared/_Layout.zh-Hans.cshtml
/Areas/Login/Views/Shared/_Layout.zh.cshtml
/Areas/Login/Views/Shared/_Layout.cshtml
/Views/Shared/_Layout.zh-CN.cshtml
/Views/Shared/_Layout.zh-CHS.cshtml
/Views/Shared/_Layout.zh-Hans.cshtml
/Views/Shared/_Layout.zh.cshtml
/Views/Shared/_Layout.cshtml
/Shared/_Layout.zh-CN.cshtml
/Shared/_Layout.zh-CHS.cshtml
/Shared/_Layout.zh-Hans.cshtml
/Shared/_Layout.zh.cshtml
/Shared/_Layout.cshtml
```

What's wrong with me?

**Comment by jtkech** [comment]
Razor views are harvested through custom file providers in the modules, not the application. But the application is a module itself whose path is `/.Modules/YourApplicationName`. So, try the following.

    @inject Microsoft.AspNetCore.Hosting.IHostingEnvironment Environment

    @{
        Layout = $"/.Modules/{Environment.ApplicationName}/Views/Shared/_Layout.cshtml";
    }

**Comment by kamikyo** [comment]
@jtkech Thank you so much for your timely answer.You are right,it is working fine.
This is because I do not understand the mechanism of the Orchardcore module.
Orchardcore documents are scarce.

> The application is a module

If you hadn't told me, I didn't know I could do it like this.
Looks like it's time to learn Orchardcore's source code.
Finally, thanks again for your help!
PS:It is a challenge for me to digest this source code.

**Comment by xperiandri** [comment]
Has anything changed?
I tried to set layout to `Layout = "/.Modules/<name of my dll with theme>/Views/Shared/_Layout.cshtml";` but it doesn't work.
How to debug this issue?
