### ISSUE TITLE
Share Content Types across tenants

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#2229]
@sebastienros is there ability in Orchard Core to share a content type across multiple tenants?

**Comment by sebastienros** [comment]
We can already import and export them, and do it over the network automatically, using Deployment Plans.

**Comment by hishamco** [comment]
I knew from Orchard 1 that we have export & import content, I'm asking if there's a way to choose the tenants during the content creation or for instance make a content type global in all the tenants, I see such feature in `Craft CMS`

**Comment by sebastienros** [comment]
> I knew from Orchard 1 that we have export & import content

But the question is on OC, and there are a thousand things that are not possible on OC that people ask for.

But like in O1 there is no sharing of content type across tenants :trollface: 

What you can do if have these content types come from a module, and enable the same module on all tenants, or use the same recipe when creating the tenants.

**Comment by hishamco** [comment]
> But like in O1 there is no sharing of content type across tenants :trollface:

Yep, I was talking about importing & exporting

> What you can do if have these content types come from a module, and enable the same module on all tenants, or use the same recipe when creating the tenants.

This may useful in some cases, but making content type as Global, will save time and effort instead of adding the content type multiple times, or importing them or enable the module again and again

**Comment by pgy866** [comment]
The global content type is very good, sometimes very useful, but it seems that Orchard Core does not support him.
