### ISSUE TITLE
Jint dependency warning

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#2234]
Hi,
It seems that the version of the Jint package needs to be updated.

`Warning	NU1603	OrchardCore.Scripting.JavaScript 1.0.0-beta3-68048 depends on Jint (>= 3.0.0-beta-1247) but Jint 3.0.0-beta-1247 was not found. An approximate best match of Jint 3.0.0-beta-1249 was resolved.	`

**Comment by sebastienros** [comment]
Looks like you are not using the myget feed, where this version is available.
