### ISSUE TITLE
 Inserting media  file only generate a " img_tag"

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#2238]
In editor, Inserting media  file only generate a " img_tag", if insert other type file,doc, rar , it should also generate a link to other type file. is it?

**Comment by AcellaEDU** [comment]
It isn't working. May be, I am mistake.

![image](https://user-images.githubusercontent.com/6829626/56660069-57325a00-66a7-11e9-8c49-3668ea4bfa25.png)

![image](https://user-images.githubusercontent.com/6829626/56660094-687b6680-66a7-11e9-999f-c5783e246582.png)

Preview result:
![image](https://user-images.githubusercontent.com/6829626/56662886-a085a800-66ad-11e9-9d0a-336443bf442f.png)
