### ISSUE TITLE
Contact form in the agency

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2241]
@sfmskywalker 
Would it be possible to make the contact form work in the agency theme using a workflow activity and a dynamic form?
Can we configure it from a recipe?

A basic process would be to create content items (ContactFormSubmission).

**Comment by agriffard** [comment]
It would also be great if we could send emails.

We could manage the email settings using:
- appsettings.json file with email section.
- the setup: Enhance it to enter the settings during the setup.
- an EmailRecipeStep to configure the email settings from a recipe.

**Comment by sfmskywalker** [comment]
Definitely. As soon as Workflows supports recipes, we can do it. I'm tracking a card for it here: https://github.com/OrchardCMS/OrchardCore/projects/4#card-9909657.

**Comment by agriffard** [comment]
To do this, I also commented the contactme.js script in Layout.liquid. It is submitting in Ajax to a contact.php url and uses jQuery validation. 
Should we use workflow activities to validate the inputs?

**Comment by agriffard** [comment]
I created a Worklow that validates the input values and sends an email as explained here : https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Forms/README/ 

We need a way to add a validation summary in Liquid code when we redirect with errors.

**Comment by sfmskywalker** [comment]
Yeah exactly. All the support for this scenario is there. The ValidationSummary widget should be a good example of what it would take to access the model validation state when implementing a Liquid tag that renders these errors. It works even when redirecting thanks to an action filter that adds model validation to TempData and reads from it automatically.

**Comment by sebastienros** [comment]
Example to be taken from TheComingSoon theme.

**Comment by jtkech** [comment]
@sebastienros @agriffard @sfmskywalker @Skrypt ...

Just to say that we have a bridge between razor and liquid tag, see #2736 for more details and how to use those whose names are not yet registered for the liquid parser.

- So, the `ValidationSummaryPart.cshtml` razor template.

      <div asp-validation-summary="All"></div>

- Can be replaced by a `ValidationSummaryPart.liquid` liquid template.

      {% block "div", validation_summary:"All" %}{% endblock %}

    Just tried, it works.
