### ISSUE TITLE
Update async methods to accept a CancellationToken

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#2250]

**Comment by sebastienros** [comment]
Any good reason? Because usually the pattern I saw with that is to pass the current request's one, which is kind of bad I have been told. And it adds noise everywhere if you want to do it correctly.

**Comment by sfmskywalker** [comment]
Just to do it correctly.

**Comment by sebastienros** [comment]
So you want to be able to cancel a workflow? While it's running? How would it be triggered?
Also it means all tasks should react to it?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
