### ISSUE TITLE
Tenants set Default Culture, output HTML will not change

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2256]
Tenants set Default Culture, output HTML will not change
@Skrypt I hope to help repair, thank you
![1](https://user-images.githubusercontent.com/28694676/44408858-ccd3ac80-a593-11e8-955d-72ceb7075590.gif)

**Comment by Skrypt** [comment]
You probably forgot to enable the localization module on your tenant.

**Comment by pgy866** [comment]
@Skrypt Thank you, everything works fine after the tenant turns on localization.
