### ISSUE TITLE
TextField with predefined list: Use input text and datalist for autocomplete

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2258]
@Skrypt When the field editors PR is merged and you want to use them to make a predefined list editor associated to a TextField, here is an idea: Make an editor using an input text and a datalist.

See http://blog.teamtreehouse.com/creating-autocomplete-dropdowns-datalist-element and the CodePen https://codepen.io/matt-west/full/jKnzG

It will allow you to easily obtain a textbox with an autocomplete.

Then, as in the example, an even better idea to retrieve this list would be to allow to point to an url returning json, to load the datalist elements.

Now imagine: If you enable the graphQL module, it could be a way to get easily an autocomplete textbox retrieving existing content items from a query.

It might also give us some ideas for the content picker.

**Comment by Skrypt** [comment]
I like the idea about retrieving the data from a Query. Though for the textfield should we do this since this is exactly the role of the content picker?

**Comment by sebastienros** [comment]
You could have an editor that is just a liquid template ;) and it could use queries and define what the value is (like a content item id).

**Comment by Skrypt** [comment]
First I want to know if I should merge @jtkech branch. I'll see with him tonight. He basically just made a ViewModel that is the same as a model, but maybe I'm missing something. Should we wait for using GraphQL or just use a straight Query? Somehow would make sense to retrieve only DisplayName, Value for most of frontend lists. Can we do SELECT Field as DisplayName, OtherField as Value in Queries?

**Comment by Skrypt** [comment]
Also @sebastienros do you want me to start a PR with my branch or should we use yours?

**Comment by Skrypt** [comment]
I created 2 different content types. Within each of them I created the same Field (name). I saved settings on both successfully. For me adding the ViewModel like @jtkech did doesn't work. I can save the settings but it doesn't display them in the View afterward.

**Comment by Skrypt** [comment]
Added the Datalist editor. I've not been able to use a ViewModel like @jtkech did for the Predefined List. I ran into errors when trying to display the saved settings on the form view.

**Comment by jtkech** [comment]
@Skrypt could you try it again so that i can see the code and try to find why it fails.

E.g in your driver did you use this pattern?

    var model = new TextFieldXXXEditorSettingsViewModel();
    await context.Updater.TryUpdateModelAsync(model, Prefix);
    context.Builder.WithSettings(model.TextFieldXXXEditorSettings);

E.g it would not work if for the last line you still use.

    context.Builder.WithSettings(model);

**Comment by Skrypt** [comment]
Yes, that's what I did.

**Comment by sebastienros** [comment]
The conflicts issue that @jtkech has detailed are now fixed. The settings can't conflict anymore.

**Comment by Skrypt** [comment]
We are waiting for the Datalist to be supported in MVC framework. Though I think we can do the same kind of control with BS4 or VueJS controls. The idea is having an autocomplete for textfield.

**Comment by sebastienros** [comment]
We can add the Datalist option like we already have Radio/DropDown
