### ISSUE TITLE
Trying to define a new shape

### ISSUE THREAD

**Issue by RTS340** [OrchardCMS/OrchardCore#2259]
Hi,

I am trying to define a new shape as done in this video created by the orchard team, he creates a shape called heading : https://www.youtube.com/watch?v=bt3Stgb_wbI

Its around 23m20s.

I have created a new shape in cshtml and calling it using the @await DisplayAsync(New.SHAPENAME).

But I am getting the OrchardCore.DisplayManagement.Implementation.DefaultShapeFactory'

Thanks

**Comment by giannik** [comment]
@await DisplayAsync(await New.AdminDashboard())

**Comment by RTS340** [comment]
Thanks

**Comment by RTS340** [comment]
Also in the video he states being able to declare using a shape as follows:
<SHAPE />

But this does not seem to render the defined shape.

**Comment by awyl** [comment]
Take a look at this.

https://github.com/OrchardCMS/OrchardCore/blob/f11800158f1883badeae1d17a4805cf6027b157c/src/OrchardCore.Modules/OrchardCore.Demo/TagHelpers/BazTagHelper.cs#L7-L15
