### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by nour-s** [OrchardCMS/OrchardCore#2263]
Navigate to:
https://orchardcore.readthedocs.io/en/latest/OrchardCore/OrchardCore.Modules/README/

If you click on the links in the following paragraph, it will take you to 404 page:

> You can find an sample application here: [OrchardCore.Mvc.Web](https://orchardcore.readthedocs.io/en/latest/OrchardCore/OrchardCore.Modules/..../OrchardCore.Mvc.Web/Startup.cs)

and also:

> You can find an sample application here: [OrchardCore.Nancy.Web](https://orchardcore.readthedocs.io/en/latest/OrchardCore/OrchardCore.Modules/..../OrchardCore.Nancy.Web/Startup.cs)

Addiotionally, the link that takes you to the GitHub repository to edit the page is also broken:

![image](https://user-images.githubusercontent.com/1418564/44492376-514a2c00-a675-11e8-8f47-1c22a3a2938d.png)

**Comment by agriffard** [comment]
It has been fixed on the dev branch: https://orchardcore.readthedocs.io/en/dev/OrchardCore/OrchardCore.Modules/README/
