### ISSUE TITLE
Customizing Part templates and Customizing Field templates

### ISSUE THREAD

**Issue by RTS340** [OrchardCMS/OrchardCore#2265]
Hi,

I have been using the docs for reference on how to use alternates: https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Themes/README/

I think you have an issue with the section `Customizing Field templates`, the Url text field sits under project not portfolio so I think it should be `Project-Url.cshtml` and the the code snippet should be `<a href="@Model.Field.Text">External url</a>`

Thanks

**Comment by RTS340** [comment]
sorry just updated the issue @sebastienros

**Comment by sebastienros** [comment]
Please give us more details

**Comment by RTS340** [comment]
In the documentation link above it states:

"In our case, the Portfolio has a Text field named Url. The best shape to override in this case is Portfolio__Url which will match the template Portfolio-Url.cshtml."

But this is not true, project is the thing that has a URL text field.

**Comment by sebastienros** [comment]
You are right, the doc is wrong. Url is on the Project type/part.
