### ISSUE TITLE
create ContentItems by Lucene Query

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#2271]
Refactor search controller to create ContentItems by Lucene Query by a interface.
in this way, I can use my own custom  complicated lucene query   to create ContentItems , then paging in the search
controller

**Comment by sebastienros** [comment]
Note that to be completely reusable this interface should be in an abstractions project. We might also be able to add a custom Razor helper later on.

**Comment by sebastienros** [comment]
Documentation: https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.ContentTypes/README/#adding-content-fields-to-a-part
