### ISSUE TITLE
add ContentType as a prefix of index key

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#2274]
in ContentItemIndexCoordinator.cs , we already manipulated the index under
`var contentTypeDefinition = _contentDefinitionManager.GetTypeDefinition(context.ContentItem.ContentType);
`
so, it is better we add ContentType as a prefix of index key. in this way, the indice wont be mixed and the search for the index will be faster.

**Comment by sebastienros** [comment]
1- But then we can't do cross-type searches. 
2- I don't see why it would be faster. Unless you have numbers to share

**Comment by infofromca** [comment]
We  need a balance to search the contents under one content type ( in huge site with a lot of types) and cross-type. 
For faster, Search will narrow under the type

**Comment by sebastienros** [comment]
My solution allows you to filter on the content type too, it's just another field. You can add multiple criteria on the query. Hence the best balance you can get.

**Comment by infofromca** [comment]
will try it in this way.
thanks, close it now
andy
