### ISSUE TITLE
Feature/Controller issue with version 1.0.0-beta3-68191

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#2276]
Hi,
I have an issue when using the build 68191. When initializing a new instance (App_Data/Sites directory deleted), I have the message below. I do not have any errors if I use 1.0.0-beta3-68190.

The MetadataController is in a thid party package (Microsoft.AspNetCore.OData 7.0.1).

How can I avoid this error?

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Could not resolve feature for type MetadataController
OrchardCore.Environment.Extensions.TypeFeatureProvider.GetFeatureForDependency(Type dependency) in TypeFeatureProvider.cs, line 21

Stack Query Cookies Headers
InvalidOperationException: Could not resolve feature for type MetadataController
OrchardCore.Environment.Extensions.TypeFeatureProvider.GetFeatureForDependency(Type dependency) in TypeFeatureProvider.cs
OrchardCore.Mvc.ModularApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext context) in ModularApplicationModelProvider.cs
Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in ModularTenantRouterMiddleware.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by jpiquot** [comment]
Hi,
How can I identify the commits that have been included in  1.0.0-beta3-68191?

I really need to find this issue root cause.

Regards,

**Comment by sebastienros** [comment]
This version was created on Sat, 25 Aug 2018 01:18:47 GMT

**Comment by sebastienros** [comment]
Looks like this commit https://github.com/OrchardCMS/OrchardCore/commit/7a9a9686863055ad41141ee6fea6e65fa51e89ee

**Comment by jtkech** [comment]
Just tried by only using package references with the above version, it works on my machine. On a new setup i only get the lucene errors (in the log file) which have been fixed recently.

Here the project file.

    <Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">

      <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <TieredCompilation>true</TieredCompilation>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      </PropertyGroup>

      <ItemGroup>
        <Folder Include="wwwroot\" />
      </ItemGroup>

      <ItemGroup>
        <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-beta3-68191" />
        <PackageReference Include="OrchardCore.Hosting.Console" Version="1.0.0-beta3-68191" />
        <PackageReference Include="OrchardCore.Logging.NLog" Version="1.0.0-beta3-68191" />
      </ItemGroup>

      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.App" />
      </ItemGroup>

      <ItemGroup>
        <Content Update="NLog.config">
          <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
      </ItemGroup>

    </Project>

**Comment by FreshRob** [comment]
I too am getting a similar error.
Changed my dependencies from beta2 -> dev branch source code

TypeFeatureProvider.cs
System.InvalidOperationException: 'Could not resolve feature for type SectionHomePageController'

said controller exists in a module in my codebase

from the _features list , it appears to have no dependencies from the module SectionHomePageController exists in

**Comment by sebastienros** [comment]
@jpiquot Can you provide repro steps? (database, OS version, nuget or dev branch, ...)

**Comment by jpiquot** [comment]
@sebastienros , I don't have much time now as I am in a staging process of the application. But I will try next week to create a simple test project that reproduce the issue.

**Comment by sebastienros** [comment]
Closing until we get repro steps, we can't repro locally.

**Comment by jpiquot** [comment]
Hi,

I can see in the OrchardCore source code, that Assembly.ExportedTypes is used to get modules types. This will not get types referenced by the module (nuget packages).

If my module has a controller from a nuget nuget package (for example :ODataMetaDataController from "Microsoft.AspNetCore.OData" package). Orchad does not see it.

From OrchardCore.Environment.Extensions.ExtensionManager.EnsureInitialized()
```
                Parallel.ForEach(modules, new ParallelOptions { MaxDegreeOfParallelism = 8 }, (module) =>
                {
                    if (!module.ModuleInfo.Exists)
                    {
                        return;
                    }
                    var manifestInfo = new ManifestInfo(module.ModuleInfo);

                    var extensionInfo = new ExtensionInfo(module.SubPath, manifestInfo, (mi, ei) => {
                        return _featuresProvider.GetFeatures(ei, mi);
                    });

                    var entry = new ExtensionEntry
                    {
                        ExtensionInfo = extensionInfo,
                        Assembly = module.Assembly,
                        ExportedTypes = module.Assembly.ExportedTypes
                    };

                    loadedExtensions.TryAdd(module.Name, entry);
                });

```

**Comment by jpiquot** [comment]
When replacing the ModularApplicationContext by a custom one where I hardcoded the the Add of the OData module, it works!


```

       private IEnumerable<Module> GetModules()
        {
            var modules = new List<Module>
            {
                new Module(_environment.ApplicationName, true)
            };

            foreach (IModuleNamesProvider provider in _moduleNamesProviders)
            {
                modules.AddRange(provider.GetModuleNames().Select(name => new Module(name, name == _environment.ApplicationName)));
            }
            modules.Add(new Module("Microsoft.AspNetCore.OData", false));
            return modules;
        }

```

**Comment by jtkech** [comment]
Yes, we expose only public types and only those defined by module features (a module may have only one feature, itself) which are enabled. E.g for a controller we automatically set an "area" route value to the module id. Otherwise a type could be tied to the wrong feature, and the application (which is now a specific module) would always expose all types.

Hmm, maybe this issue is since we made the application itself behaving as a module.

Your testing code is very interesting, so a solution would be to define a simple `IModuleNamesProvider` for the assembly name(s) you need. But you would need to register it at the app level in your app startup.

For doing this through a module, we would need something like our `AddTagHelpers()` helper which allows a module to "define" a tag helper even it is defined in a referenced assembly. See what we do around `ITagHelpersProvider` and how there are added to the shell blueprint in `ShellFeatureApplicationPart`.

So, maybe an helper which allows a module to add controller types or a list of any types, and / or all exported types of an assembly ... So that when a module feature is enabled, it also exposes these types. Hmm, and we would need to tie these types to this feature, at least for some types e.g controller types.

**Comment by jpiquot** [comment]
Thanks you @jtkech for your very complete answer.

I know that it is not very common to add controllers from external packages but I think that it would be nice to be able to declare external features inside the manifest file if a module require them.

**Comment by jtkech** [comment]
@jpiquot thanks.

Very good idea to use the manifest with some new attributes specifying referenced assemblies, or with new properties on the existing attributes. I will work on it asap.

Note: Someone else requested the same for views defined in an external package, but harder to implement.

**Comment by jpiquot** [comment]
@sebastienros Could we keep this feature request open?
