### ISSUE TITLE
HTTP Error 502.5 - Process Failure when launching Orchard

### ISSUE THREAD

**Issue by dsopko** [OrchardCMS/OrchardCore#2279]
IIS crashes when I start OrchardCore.Cms.Web with this message

> HTTP Error 502.5 - Process Failure 
> 
> **Common causes of this issue:** 
> The application process failed to start 
> The application process started but then stopped 
> The application process started but failed to listen on the configured port 
> 
> **Troubleshooting steps:** 
> Check the system event log for error messages 

The event log shows an error with the source 'IIS Express AspNetCore Module'

[IISErrorLog.txt](https://github.com/OrchardCMS/OrchardCore/files/2322211/IISErrorLog.txt)

[tmp4B44.tmp.txt](https://github.com/OrchardCMS/OrchardCore/files/2322212/tmp4B44.tmp.txt)

**Comment by dsopko** [comment]
I'm also getting this in 1.0.0-beta2 what could be different with my environment that OrchardCore.Cms.Web will not run.

**Comment by sebastienros** [comment]
repro steps?
