### ISSUE TITLE
Developing on IIS, tenants

### ISSUE THREAD

**Issue by konstrui** [OrchardCMS/OrchardCore#2286]
Hi all,

Just a question about multiple tenants.
I'd like to test this in my local environment. Would it be neccesary to use IIS, to test e.g. the following:

www.mydomain.com
portal.mydomain.com
portal.myotherdomain.com

Or how would you configure OrchardCore to do so?

Thanks,
Daniel

**Comment by Skrypt** [comment]
On each tenants settings ; you can setup multiple hostnames (separated by a ','). IIS is not necessary for doing this, Orchard Core tenants are hosting instances themselves. The only difference is that a Tenant will also register default services (DI) required for OC to run properly.

**Comment by sebastienros** [comment]
Just define your host names in the `hosts.etc` file (if you are using windows, or the hosts file on linux).

And in Orchard create multiple tenants, and provide a single domain for each tenant. The "Default" tenant is a fall back and doesn't need a domain to be registered. Also it supports `*` domains like `*.foo.domain.com`

**Comment by awyl** [comment]
You can either use IIS, IIS Express or just console.  It doesn't matter for multi tenants.  What matter is how you resolve the URLs.

3 ways that I have used.
1) Modify hosts files as suggested above.
2) Use a local proxy with a custom local dns, then you can specify any domain for any ip.
3) Add these as your tenants hostname for local testing, like, {portal}.127-0-0-1.org.uk.   Everything will resolve to 127.0.0.1.

**Comment by konstrui** [comment]
And in IIS I just point to the wwwroot folder of the Orchard.Cms.Web project?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by Skrypt** [comment]
If you use IIS you will need to add all the domains that your website with resolve like you would do normally. Orchard Core will take care of dispatching the requests per domain/tenants.

**Comment by sebastienros** [comment]
You don't need IIS to test this setup, you can use Kestrel directly.
