### ISSUE TITLE
Setup and configuration with tenants / custom modules

### ISSUE THREAD

**Issue by konstrui** [OrchardCMS/OrchardCore#2288]
Maybe this question is for ASP.NET Core, but anyway...

I want to achieve the following:

www.mydomain.com - Marketing website
portal.mydomain1.com - Portal for company 1
portal.mydomain2.com - Portal for company 2

All in the same instance of a website.
Is this doable within Orchard with help of custom modules / tenants?

**Comment by Skrypt** [comment]
You will just need to install the SAAS recipe as your first website that points to www.mydomain.com and in that first tenant configure 2 more tenants pointing to the other 2 domains. The SAAS recipe is made for these kind of scenarios.

**Comment by awyl** [comment]
Doable with Orchard, no need custom modules, unless you need features that are not in the repo.

Enable the tenant module.  Then you can setup tenants, like.

Host site enables tenant module.  Then create 3 tenants
- hostname: www.mydomain.com
- hostname: portal.mydomain1.com
- hostname: portal.mydomain2.com

You can also configure 2 tenants, and use the "host site" as one your site.
