### ISSUE TITLE
Routing with custom modules / tenants

### ISSUE THREAD

**Issue by konstrui** [OrchardCMS/OrchardCore#2289]
I have created a custom module as in the examples.

The module works as I can call my action through this URL:
https://localhost:44300/Custom.Portal/Home/Index

What if I want to 'route' this to:
https://localhost:44300/portal/home/index

I tried this code, but it doesn't seem to have any effect:

    public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            routes.MapAreaRoute(
                name: "Portal",
                areaName: "Custom.Portal",
                template: "portal",
                defaults: new { controller = "Home", action = "Index" }
            );
        }

This is placed in the Startup.cs class in my custom module project.

Am I missing something?

**Comment by awyl** [comment]
Try
```csharp
template: "portal/{controller}/{action}"
```

**Comment by Skrypt** [comment]
or why not using 'Portal' as the area name?

**Comment by sebastienros** [comment]
@awyl 's suggestion is correct.
