### ISSUE TITLE
Order of steps in deployment export file incorrect

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2294]
The 'features' step gets exported, but should appear as the first step in the json file.
Using the json file as is for the recipe file, will result in a failure when executing the recipe.

**Comment by psijkof** [comment]
Default order, but adjustable?

**Comment by sebastienros** [comment]
This kind of things doesn't work ;) Right now the simplest is to have priorities of the sources. That will handle most issues. Otherwise users might not know that some steps need to be first.

**Comment by jptissot** [comment]
Related to https://github.com/OrchardCMS/OrchardCore/issues/4393

**Comment by agriffard** [comment]
See also #4518

**Comment by sebastienros** [comment]
Closing as we have more detailed issues to track it
