### ISSUE TITLE
CustomSettings content does not get exported

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2295]
Using the CustomSettings module and stereotype on a contenttype, works great.
But exporting (deployment) is only exporting the types not the content.

**Comment by agriffard** [comment]
There is a CustomSettings deployment step but it is not listing the available ones.

**Comment by deanmarcussen** [comment]
Works fine for me w/ stereotype of `CustomSettings`
```
  "steps": [
    {
      "name": "custom-settings",
      "MyCustomSetting": {
        "ContentItemId": "49q8d2ry1r19swnnby0x95kecq",
        "ContentItemVersionId": null,
        "ContentType": "MyCustomSetting",
        "DisplayText": "test",
        "Latest": false,
        "Published": false,
        "ModifiedUtc": "2020-02-09T16:27:16.5256052Z",
        "PublishedUtc": null,
        "CreatedUtc": null,
        "Owner": null,
        "Author": "admin",
        "MyCustomSetting": {},
        "TitlePart": {
          "Title": "test"
        }
      }
    }
  ]
```

**Note** the recipe step only updates the site settings values.

You should also export and import the contenttypes separately, and of course the content definitions.

So a good deployment plan would be 
- features
- content type definitions
- contents of type (the custom settings types)
- custom settings deployment step
