### ISSUE TITLE
Setting the homepage should resolve the content item's Display route

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2300]
This code:
https://github.com/OrchardCMS/OrchardCore/blob/d729a2048a4390380d99e7be9f7968ff8f8e9271/src/OrchardCore.Modules/OrchardCore.Autoroute/Handlers/AutoroutePartHandler.cs#L56

Should not try to infer the route for a content item. It might be redefined.

**Comment by Piedone** [comment]
This was fixed at some point.
