### ISSUE TITLE
Extending Container / Fluid Container

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#2304]
Hello,

Is anyone able to point me to where the Container & Fluid Container are defined in the source code please. We have the requirement to add additional properties to these which can be set when creating or editing a page. 

Searching for "Container" yields no display drivers (unless I'm being blind), so are these more of a core part of Orchard, if so what would be my best option if I wanted to replicate their behavior but add additional features to them?

![Example](https://puu.sh/BmRrf/4c24e87f85.png "Example")

Regards

Marlon

**Comment by sebastienros** [comment]
The editors and content management support is in https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Flows

The Widgets you are mentioning are created by recipes, probably the Blog recipe, which creates new content type using the `BagPart` and the `FlowPart` (what you call Fluid?)
