### ISSUE TITLE
Duplicate Aliases

### ISSUE THREAD

**Issue by ThisNetWorks** [OrchardCMS/OrchardCore#2310]
I've been starting to use AliasPart's combined with some custom liquid filters to build routes/inks inside HtmlBody's (and in the content menu - linking to alias rather than route).

Is this what they're intended for?

If so, should the driver be querying the index to avoid duplicates, like the autoroutedriver does?

**Comment by sebastienros** [comment]
Probably

**Comment by deanmarcussen** [comment]
This could close - fixed in https://github.com/OrchardCMS/OrchardCore/pull/3095
