### ISSUE TITLE
Empty template of contenttype overrides file based template

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2311]
We define a contenttype, e.g. Slider, mark it as Widget (stereotype) and edit the detail template in the admin.
Later we decide we want the liquid code in a file named Widget-[contenttypename].liquid and delete the liquid from the backoffice. (NOTE: You cannot delete the detail template in the admin)
We just delete the liquid from the backoffice, in the hope it will not be used.....
But you guess right, the .liquid file does not get loaded.

Shouldn't the template in the backoffice have an option to be deleted?

**Comment by psijkof** [comment]
The empty template is stored, even though it shouldn't I think:
"Widget__Slider":{"Content":null,"Description":null

**Comment by sebastienros** [comment]
File templates are onle loaded on startup. So you need to restart the app. And admin templates will always win over file ones.

I am keeping this issue open to track the other problem you are mentioning.

**Comment by jtkech** [comment]
You can fully remove a database template from the UI but you loose your work. What you can do is just rename it, e.g `Widget__Slider_deleted`.

**Comment by sebastienros** [comment]
Oh I see, you tried to remove the content hoping it would not be taken into account. Well that is by design, what if you actually want to hide something by just not displaying anything? So I would agree with @jtkech  on the recommendation.

> Shouldn't the template in the backoffice have an option to be deleted?

Do you mean there is no "delete" button? Well that would be a big issue ;)

**Comment by psijkof** [comment]
Yes, no delete button. You can edit the liquid (and leave no character, or if you prefer, an empty string). But that would still be 'rendered' over a file with the same 'name' (I know file names are different right now, but the 'same' template id). 

So I guess renaming it in the admin would do it for now, till the delete button arrives :)

**Comment by sebastienros** [comment]
I can delete templates just fine. Not sure what the issue is anymore.
