### ISSUE TITLE
ModuleProjectRazorFileProvider should return composite tokens

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2315]
For filters that contain "*" mapping, we need to return the same filter for all modules, in a composite token. This is passed when MVC looks for Razor Pages (not views) to detect for new files.

**Comment by sebastienros** [comment]
The goal is to detect changes in `Pages` folders, including new files and not have to restart the application.

**Comment by jtkech** [comment]
I think that we can close tis one, [see here](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Mvc.Core/ModuleProjectRazorFileProvider.cs#L244).
