### ISSUE TITLE
Content Type names with underscores don't work with Widget template overrides

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#2322]
Hi,

I had a content type named `Container_360`. following a few examples from the Forms module I see underscores get translated to full stops / periods in the view template names. This worked when overriding the `FlowPart` template, with a template file name of `Container.360-FlowPart.cshtml`. However when trying to override the Widget behaviour with a file name of `Widget-Container.360.cshtml` that template was not used.

Changing my content type to be named `Container360` and subsequently the Widget template to be called `Widget-Container360.cshtml` resolved the issue in my case.

I think how it works should be consistent though.

**Comment by sebastienros** [comment]
I think we ensure content types don't have `_` or `-` in O1.

**Comment by deanmarcussen** [comment]
@marlon-tucker how did you create this content type?

I checked the `.ToSafeName()` and it is basically the code from O1, so does strip `_` and `-`, so I cannot seem to make a Content Type that has either of these characters in it.

The Display Name will allow it, but the Technical Name successfully strips it as far as I can tell.

**Comment by marlon-tucker** [comment]
It was created via a data migration in the widget:

`_contentDefinitionManager.AlterTypeDefinition("Container_360", type => type .... );`

I notice you say it strips them, would that infer the template name would of been `Widget-Container360.chtml`

**Comment by deanmarcussen** [comment]
thanks @marlon-tucker 

It's well validated in the UI (where it is easier to display with errors) but I don't see that same code in the extensions when creating a type definition.

I suspect it may be creatable via a migration with the invalid characters.

You could check by running your migration again, and looking at the `ContentDefinition.json` file 

I think maybe @jptissot managed to create one with a recipe which was invalid as well
