### ISSUE TITLE
A document per token on the same table as Contents maybe is too much

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#233]
Currently each tokens issued is stored in as a content in the db so the Content table will be plenty of those contents. 
![image](https://cloud.githubusercontent.com/assets/4950766/18179710/1032f4b4-7084-11e6-9473-8c5ca59bee65.png)
Don't you think it would'nt be better to store it in a different location. YesSql allow that?

**Comment by sebastienros** [comment]
Right, the solution is to create a single document, or one per app, but have an index project all tokens to another index table (map/reduce index) with all the information you need. This way you can query the index table directly without having to load the document.
Another straightforward solution is to create a custom table like you would have with the index, but query and create rows with Dapper directly.

**Comment by jersiovic** [comment]
We have to take into account concurrency. If Orchard provides multiple tokens at the same time with first approach there is risk of losing tokens because two threads store an outdated version of the document because it doesn't include the token provided by the other thread.

**Comment by sebastienros** [comment]
Ok, then go with the Dapper option. I will see if I need to provide some helpers in YesSql to support this scenario.

**Comment by jersiovic** [comment]
When this issues are solved in YesSql https://github.com/sebastienros/yessql/issues/22 and https://github.com/sebastienros/yessql/issues/21 Iwill be able to offer a navigation property in OpenIdApplication called Tokens that points to tokes stored in separated documents in another table.

**Comment by jersiovic** [comment]
@sebastienros now that yessql supports collections I want to use it with OpenId tokens.
Should I create a collection called "OpenId" or better a "TmpData", currently I prefer second option and wait to see what other data fits in this TmpData to decide if we prefer to have more concrete collections.

Following YesSql tests I see we need to call InitializeCollectionAsync and ExecuteMigration for the new collection: https://github.com/sebastienros/yessql/blob/3cdb9765e7bd2f70d9dd56138e41e835abf19b92/test/YesSql.Tests/CoreTests.cs

If we call the new collection "TmpData" we can intitialize collection in SetupService after callling store.InitializeAsync(). And we can call ExecuteMigration for that collection in DataMigrationManager.UpdateAsync. But it is not clear to me how we are going to determine which migrations will be executed for each collection. Maybe with an extra property in DataMigration saying for which collection it is.

If we call it "OpenId" we need to isolate code handling this collection in Orchard.OpenId module. Can we intitialize it within Orchard.OpenId migrations? In this case we still will need support in DataMigrationManager.UpdateAsync for executing migrations for other collection different than the default one. 

If Where should I have to execute _store.InitializeCollectionAsync("TmpData) ?

**Comment by sebastienros** [comment]
My brain is still warming up, I have no idea what you are talking about ;) will look at it again later.
I know I also wanted to use configuration to set which class uses which collection, and that right now you need to use a `using` statement.

**Comment by PinpointTownes** [comment]
On a related note, have you considered moving the YesSql OpenIddict stores to a separate package?
They'd make a good candidate for an `OpenIddict.YesSql` package :smile: 

We should also consider porting the signatures you added in the custom `IOpenIdXYZStore` stores back to the OpenIddict interfaces (e.g `DeleteAsync`).

**Comment by PinpointTownes** [comment]
I'm closing this thread as rolling tokens are no longer enabled by default, which should heavily mitigate the initial concern. We'll also introduce a background task to automatically remove the obsolete token entries: https://github.com/OrchardCMS/OrchardCore/issues/1116.

Feel free to re-open if you're still concerned about this issue.
