### ISSUE TITLE
Disable autocomplete for User Secret field in OpenID Connect module

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#2330]
When you create an application in OpenID Connect module it allows autocompleting previous secrets.
Please, disable this for security reasons.

**Comment by PinpointTownes** [comment]
Very good idea. Would you like to submit a PR to fix that?

**Comment by xperiandri** [comment]
OK, I'll try

**Comment by xperiandri** [comment]
This week
