### ISSUE TITLE
Add a UI interface to the module with a custom field name and value?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2338]
Add a UI interface to the module with a custom field name and value?
(eg: settings, users, etc...)And provide access methods
For example, if the user module adds this, it can be solved, such as: user avatar photo, user gender, etc. Of course, other modules that are needed can also have this. Is this feasible?
![3](https://user-images.githubusercontent.com/28694676/45101117-620e9d80-b15d-11e8-9c1c-b305787858f4.gif)

**Comment by sebastienros** [comment]
Are you talking about profiles for users? 

@paynecrl97 we have Custom site settings already, don't we have that too for the User?

**Comment by pgy866** [comment]
User module's custom field extension settings, and provides an interface to access the value, just an example,
Whether the custom extension interface can be used as a unified interface, and can be used in any module if needed.

**Comment by Piedone** [comment]
Custom Settings provide this functionality now.
