### ISSUE TITLE
An SPA sample harnessing new OpenId module

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#234]
Well as the title says, to have a sample page with an SPA app using new OpenId module to get access to non public data provided by Orchard.

**Comment by xperiandri** [comment]
Do you mean a sample of SPA client side on top of Orchard API?

**Comment by sebastienros** [comment]
@xperiandri yes, that's the idea.

**Comment by Jetski5822** [comment]
+1

**Comment by xperiandri** [comment]
When could it happen?

**Comment by sebastienros** [comment]
First one to do it wins. Nobody is assigned to it yet. If you want to help that would be a nice way to help and also learn about the OpendID module

**Comment by xperiandri** [comment]
OpenID is not a big deal.
I have no idea of how Orchard works and its API.
Do you have Swagger enabled?
So if someone can mentor me it will be more efficient.

**Comment by jersiovic** [comment]
No, Swagger is not enabled, the point is as far as I know still there is not a generic Rest API for consuming/managing orchard contents and types. That topic IMO should have its own issue to discuss about it. 
When I created this issue I was thinking on sth small as a point of start for anyone interested on using an SPA for consuming Orchard APIs based on authorization. 
An start could be simply providing within Orchard.Demo an small SPA that allows to login through Orchar.OpenId module and consume any action we want to include in this controller https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore.Modules/Orchard.Demo/Controllers/ContentApiController.cs

**Comment by xperiandri** [comment]
OK, I want to do this.
However now I don't understand how should I set up a page that returns SPA app bootstrapper?

For example I have this [page template](http://www.free-css.com/free-css-templates/page211/bazinger) and I want to return is as Aurelia SPA as a first simple step.
What do I have to do in order to achieve this in terms of Orchard Core?

Authenticating with OpenId Connect is absolutely trivial. Nothing to care about.

**Comment by ropstah** [comment]
Would these be two equally interesting scenarios? 

One where the SPA is _served from an `unauthenticated OC backend`_ in which the SPA is an OpenId client (implicit flow), and one where the SPA is _served from an `authenticated OC backend`_ in which the OC backend is an OpenId client (hybrid/authorization code flows)?

**Comment by agriffard** [comment]
See "Orchard Core Headless CMS with Angular 9 Client using GraphQL" https://www.youtube.com/watch?v=GifdPhc_OWU&feature=youtu.be

**Comment by johnrom** [comment]
@agriffard that example doesn't show how to use OpenId at all with an SPA? might be the wrong link?

**Comment by MichaelPetrinolis** [comment]
Hi @johnrom, you can find multiple examples on https://www.youtube.com/c/orchardskills channel for authenticating with OpenID from a SPA, eg. https://www.youtube.com/watch?v=VQwCHYmopeQ
