### ISSUE TITLE
Incorrect name for deployment step

### ISSUE THREAD

**Issue by AidosMarcos** [OrchardCMS/OrchardCore#2340]
When creating a deployment plan noticed that Content Step, where you can select specific content to be exported, when added then it shows "Content Types" as name, which could mislead in what it will be the recipe outcome. 
Just "Content" would be more accurate.

**Comment by AidosMarcos** [comment]
Created pull request 
https://github.com/OrchardCMS/OrchardCore/pull/2343/commits/537248df18c9a6057dbdf271eb13aaab5639f276

**Comment by sebastienros** [comment]
I would say that "Content Types" is correct, it's listing content type names. You can add more "hint" text about what will happen when a content type is selected, as in that all the content items from this content type will be selected.

**Comment by psijkof** [comment]
You select the **content** of some of the contenttypes in the store. The step in the plan says 'content type', which is misleading, as there is another step to export content type(s).

**Comment by sebastienros** [comment]
Got it, I thought it was for the step editor, thanks for clarifying.
