### ISSUE TITLE
Check creatability for the New menu

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2342]
c.f. https://github.com/OrchardCMS/OrchardCore/pull/2334

When display the link to create a content item, we need to check the content can be created by making a new one and testing the permission `EditContent` for the current user. (this is what the controller is doing too). And only show the `New` menu if any of them can be created.

This requires the INavigationProvider to be async.

**Comment by sebastienros** [comment]
@matiasmolleja you might want to make the navigation provider async as part of your current work.

**Comment by hishamco** [comment]
Isn't fixed?!!

**Comment by sebastienros** [comment]
Maybe, I need to check, and there is a PR also related (@matiasmolleja )

**Comment by matiasmolleja** [comment]
I think you can close this one. I fixed it after you implemented dynamic permissions for content types.
