### ISSUE TITLE
Monaco editor

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2345]
Looks way more polished with better editor experience.

**Comment by sebastienros** [comment]
Note that Monaco doesn't work correctly on mobile.

**Comment by sebastienros** [comment]
We can't get rid of codemirror but we could have an extra editor based on it assuming people don't need mobile view.

**Comment by agriffard** [comment]
Anyone wants to contribute to a Monaco Editor for Html field and part?

**Comment by MichaelPetrinolis** [comment]
Hello, i created #8266 to use Monaco in HTML and Text fields. I added monaco in the Recources project, it works with cdn and local scripts. To load monaco last and avoid conflicts with other scripts, i added a special dependency '*' that places the scripts with it last when loading (#8265). A property LoadLast would be better, but i prefered to use the existing properties.

**Comment by MichaelPetrinolis** [comment]
@hishamco thanx, is nice to have monaco in the CMS, especially in the resources, eg. we could use the diffEditor in the audit trail module to display differences and many other use cases. Don't know what to make a gif about, it is just another editor for TextField and HtmlField, with settings to define a json configuration for creating the editor.

**Comment by sebastienros** [comment]
- These are custom editors that we can pick in the field/part settings?
- For other places like json editors, it would be great to be able to leverage the json schemas. At least if defined when the resource is imported, like it's done for codemirror.
- There is  a Liquid extension in VsCode, would it be possible that it works there too?
- What about the Workflow JavaScript/Json editors?

**Comment by sebastienros** [comment]
And finally, how does it look like in mobile mode? I tried it recently and it was fine, but how about in OC.

**Comment by MichaelPetrinolis** [comment]
@sebastienros,

- This PR provides Monaco editor as option for TextField And HTML Field
- It seems that we can configure JSON language support and provide schemas (https://github.com/Microsoft/monaco-json). I could test it with Monaco editor options in this PR. Now for JSON configuration, I used code mirror.
- Unfortunately, VSCode extensions do not work for Monaco. But with Monarch we could configure a custom language and provide IntelliSense for Liquid (https://microsoft.github.io/monaco-editor/monarch.html)
- We could use Monaco for Workflow JavaScript/Json editors and provide JS hints and JSON schema validation and IntelliSense, but personally I have not tested it.
- If we enable automaticLayout option, works nice. To look better in mobile, one could disable minimap and/or line numbers, but this is configurable.

**Comment by MichaelPetrinolis** [comment]
could not find json schema for monaco, so i created a json file with typescript-json-schema and this is the result
![image](https://user-images.githubusercontent.com/9623255/104121940-b8520380-534a-11eb-8281-8f105298b874.png)

**Comment by agriffard** [comment]
See #8266

**Comment by sebastienros** [comment]
I noticed it doesn't trigger preview updates
