### ISSUE TITLE
Attaching fields to content type from a migration does not show up in the admin UI.

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#2346]
after running a sample migration

public int UpdateFrom2()
        {
            _contentDefinitionManager.AlterTypeDefinition("FreeFormSlide", type => type
                .DisplayedAs("Free Form Slide")
                .WithPart("HtmlBodyPart")
                .WithPart(nameof(FreeFormSlidePart))
                .Stereotype("Widget"));
       _contentDefinitionManager.AlterPartDefinition("FreeFormSlide", part => part
                .WithField("Title", field => field
                    .OfType("TextField")
                    .WithDisplayName("Title")
                    .WithSetting("Position", "0")) 
            );         return 3;
}
the attached field does not show in the Content Type UI from the admin.

If I go from the UI and add a dummy field to the content type and refresh the field from the migration shows up.

**Comment by sebastienros** [comment]
`.WithPart(nameof(FreeFormSlidePart))` => `.WithPart(nameof(FreeFormSlide))`

**Comment by sebastienros** [comment]
Fields are attached to a fake part that has the same name as the type.

**Comment by sebastienros** [comment]
Documentation: https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.ContentTypes/README/#adding-content-fields-to-a-part
