### ISSUE TITLE
Create a font-awesome picker

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2347]
Replace a text input with the actual icon, and a selector to display them to chose from a visual list.

Could then be used as an editor for text fields.

**Comment by agriffard** [comment]
https://farbelous.io/fontawesome-iconpicker/

**Comment by douwinga** [comment]
We did something like this in O1. Below is an example. Is this what you are thinking?

![font-awesome-picker](https://user-images.githubusercontent.com/11961383/45113580-c6f3d480-b118-11e8-8a36-1a7843d4b539.gif)

**Comment by sebastienros** [comment]
@douwinga this is exactly what I am thinking about, and the link @agriffard provided is the perfect solution IMO.

**Comment by konstrui** [comment]
I created an Editor for the Text field and I'm currently trying to create a custom field out of it. But for now this works pretty well

![2018-09-07_17-41-28](https://user-images.githubusercontent.com/1482375/45229186-779ed700-b2c5-11e8-8f0d-d31f5be2610c.gif)

![font-picker](https://user-images.githubusercontent.com/1482375/45229212-85ecf300-b2c5-11e8-8865-7cfb4bbb3213.PNG)

**Comment by sebastienros** [comment]
Looks great! I don't think a custom field is necessary. I know it might not be optimal right now to find it, but we might change how we display the types of fields by exposing the editors directly at some point. The only reason to have a custom field would be to create one called Css Class, but I don't think it makes much sense.

**Comment by sebastienros** [comment]
When do you create the PR for the editor?

**Comment by zimplerconsulting** [comment]
@sebastienros I've some troubles in the case when you use multiple versions of the Icon Picker.
For example:

- How would you insert scripts and/or styles just one time? If I insert scripts inside the TextField-IconPicker.Edit.cshtml file, it will repeat itself when having multiple items.

Any idea?

```
<script asp-name="bootstrap" at="Foot" depends-on="admin"></script>
<script name="fontpickerScript" depends-on="admin" asp-src="/OrchardCore.ContentFields/Scripts/fontawesome-iconpicker.min.js" debug-src="/OrchardCore.ContentFields/Scripts/fontawesome-iconpicker.js" at="Foot"></script>
<style name="fontpickerStyle" at="Head" asp-src="/OrchardCore.ContentFields/Styles/fontawesome-iconpicker-min.css" debug-src="/OrchardCore.ContentFields/Styles/fontawesome-iconpicker.css"></style>
```
