### ISSUE TITLE
Approach to shape alternates not clear

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2351]
Working on #2056 (Modern Business), it's not clear how to construct/name the contenttypes and .liquid/.cshtml files to achieve multiple shapes for the ListPart part of the Portfolio contenttype.

The documentation on shapes is very minimal and only a relative straight forward example exists.

We want modern business to become a not so straightforward example, but we need a little push.

**Comment by sebastienros** [comment]
What kind of customization where you looking for specifically? I want to see if I can point you to the exact documentation line. I know I have written most of the rules that are in place.

Or is it that you don't know that you can do it, and need more discoverability?

We could add something like the Shape Designer (an O1 feature) that would display a toolbox over every rendered shapes with all the ways to configure it. I am hesitant though as I think it would be much simpler to create some better documentation.

**Comment by psijkof** [comment]
Some better documentation.
Use cases. For example now, we have a Portfolio, with ListPart and Project that are part of the list.
We have more than one way to display them (a page with a paged result list formatted in 3 columns, another page with a paged result list formatted in 2 columns, etc.)
Antoine Griffard suggested we use alternates, but the documentation is a bit, well, minimalistic.
We were not able to understand how it will work.
I suggest to get some help on the modern business template and do it the recommend way, so it can use as another documentation/sample?
