### ISSUE TITLE
Bulk enabling/disabling of modules and features

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2354]
Bulk enabling/disabling would be an awesome feature to have.
![image](https://user-images.githubusercontent.com/25638593/45095630-6f546980-b116-11e8-9add-631cfb50d315.png)
Reminding @sebastienros about a demo he did recently  :)

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1752
https://github.com/OrchardCMS/OrchardCore/issues/1715

**Comment by psijkof** [comment]
Is duplicate
