### ISSUE TITLE
List of content items should be sortable.

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2355]
They can be sorted in the recipe, but not in the admin.
![image](https://user-images.githubusercontent.com/25638593/45214805-5de49c00-b293-11e8-8e22-d6c868138617.png)

**Comment by hishamco** [comment]
Why it should be sortable?!!

**Comment by psijkof** [comment]
> Why it should be sortable?!!

The contained items in list have an order attribute. By allowing to sort in the UI, this could be populated accordingly.

**Comment by hishamco** [comment]
Aha if you mean is displays them in order and not allow them to be sorted in admin UI, it's OK

**Comment by Skrypt** [comment]
Lists should be sortable through the admin UI. But only "Lists" from the "Lists" module since it's the reason why they exist.

**Comment by deanmarcussen** [comment]
@Skrypt Might do a bit of work on this - it's been bugging me for a while not being able to sort, I managed it with a custom field, but it's unwieldy.

Would it be like O1 where you have to set the list as sortable (enabled positioning I think it was) before you can sort?

And would you think we should do an ajax call to set the sort orders automatically, or have a save button that appears when items have been resorted?

**Comment by Skrypt** [comment]
Ajax yes, look at the admin menu module where we can reorder items using a Vue.js component to do so.

**Comment by deanmarcussen** [comment]
Cool, yeah the sorting itself is not too hard.

But need to know whether to do a setting on the `ListPartSettings` for `CanSort` or should they just always be sortable, because that affects the implementation a lot?

**Comment by Skrypt** [comment]
I think in 01 you could set it as sortable or not. Though with the Vue.js component you can set to allow it or not https://github.com/SortableJS/Vue.Draggable#all-sortable-options.
