### ISSUE TITLE
Previewing Template in Tenant site results in 404

### ISSUE THREAD

**Issue by DannyT** [OrchardCMS/OrchardCore#2366]
As demonstrated during the Building a theme video @1h48m  
https://www.youtube.com/watch?v=wtAIgn4gYXc&t=6480s

I get this same issue when previewing a template on a tenant. Works when previewing on a master site though.

**Comment by pgy866** [comment]
There seems to be a lot of small places in the tenant, which involves incorrect access to the path.

**Comment by sebastienros** [comment]
That's it then ;) thanks
