### ISSUE TITLE
DataProtection:the key {GUID} was not found in the key ring

### ISSUE THREAD

**Issue by kamikyo** [OrchardCMS/OrchardCore#2368]
I have another question about DataProtection
My project looks like this：
![image](https://user-images.githubusercontent.com/7645337/45405614-30825e80-b696-11e8-86f5-03851be8874e.png)
My entry's Startup.cs like this (ps:this site i call it A):
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddDataProtection()
                .SetApplicationName("App Name")
                .PersistKeysToFileSystem(new DirectoryInfo(@"phisical path"))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(36500));

            services.AddOrchardCore()
                .AddMvc();
        }
```
I use IDataProtector to encrypt data on another website (ps:this site i call it B).
I will get an exception when using IDataProtector.Unprotect on site A,like this:
```
System.Security.Cryptography.CryptographicException
  HResult=0x80131430
  Message=The key {2ac4ef1f-05f7-444e-b1cd-7ad490bebacf} was not found in the key ring.
  Source=Microsoft.AspNetCore.DataProtection
  StackTrace:
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
```
But when I moved the following code to the module's Startup.cs
```
services.AddDataProtection()
                .SetApplicationName("App Name")
                .PersistKeysToFileSystem(new DirectoryInfo(@"phisical path"))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(36500));
```
The error didn't happen,it was worked fine.
Of course, I am using IDataProtector.Unprotect in the module of site A.
Why are there such problems?

**Comment by jtkech** [comment]
I think you need to do this in the context of a tenant (we have at least one `Default` tenant) which is done when doing this in the module's startup. Also, in your startup good to override the `Order` property to a value > 0 to ensure it runs after the default configuration.

Then from the application we have some helpers (which act on an `OrchardCoreBuilder`) to register `ConfigureServices()` and `Configure()` so that for all tenants they are executed in their context, as done by an enabled module. And these helpers also have an `Order` parameter.

For example

            services.AddOrchardCms(builder =>
            {
                builder.ConfigureServices((collection, serviceProvider) =>
                {
                    var settings = serviceProvider.GetRequiredService<ShellSettings>();
                    var options = serviceProvider.GetRequiredService<IOptions<ShellOptions>>();
                    ...
                    collection.AddDataProtection();
                    ...
                }, 10); // the order parameter
            });

Note: if you have multiple tenants you will have to set a different application name, see what we do in our default `AddDataProtection()` helper in the source code.

**Comment by kamikyo** [comment]
@jtkech Forgive me for not describing the problem clearly.

### Scene A
**console app**
Main.cs
```
var serviceCollection = new ServiceCollection();
serviceCollection.AddDataProtection()
    .SetApplicationName("MT5API")
    .PersistKeysToFileSystem(new System.IO.DirectoryInfo(path))
    .SetDefaultKeyLifetime(TimeSpan.FromDays(36500));
var services = serviceCollection.BuildServiceProvider();
```
Encrypted data：
`IDataProtector.Protect("some text");`

**OrchardCore site**
entry's Startup.cs
```
...
services.AddDataProtection()
    .SetApplicationName("MT5API")
    .PersistKeysToFileSystem(new DirectoryInfo(_env.ContentRootPath))
    .SetDefaultKeyLifetime(TimeSpan.FromDays(36500));

services.AddOrchardCore()
    .AddMvc();
...
```
module's Startup.cs
```
none
```
Decrypt data(used in modules)：
`IDataProtector.Unprotect("some text");`

Exception:
```
System.Security.Cryptography.CryptographicException
  HResult=0x80131430
  Message=The key {2ac4ef1f-05f7-444e-b1cd-7ad490bebacf} was not found in the key ring.
  Source=Microsoft.AspNetCore.DataProtection
  StackTrace:
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
```


### Scene B
**console app**
`NO CHANGE`

**OrchardCore site**
entry's Startup.cs
```
...
services.AddOrchardCore()
    .AddMvc();
...
```
module's Startup.cs
```
services.AddDataProtection()
    .SetApplicationName("MT5API")
    .PersistKeysToFileSystem(new DirectoryInfo(_env.ContentRootPath))
    .SetDefaultKeyLifetime(TimeSpan.FromDays(36500));
```
Decrypt data(used in modules)：
`IDataProtector.Unprotect("some text");`
Worked fine

At your prompt, I looked at the source code.
DataProtection has been configured in AddOrchardCore.Is this causing the problem?
Does this mean that each module needs to configure its own DataProtection separately?

Thank you for taking the time to answer my stupid question.

**Comment by jtkech** [comment]
No problem.

I was talking about multi tenants (idem as multi sites) in which you can enable the modules features you want, e.g enable a feature of your module which overrides the config but not on all tenants.

Each tenant inherits of app services but runs in a child container configured by startups of its enabled modules / features which can register isolated services, override app level ones ...

Then, even you have only one tenant (the default one is named `Default`), because our default DP config is done in a tenant context (this allow to have different application names per tenant), you need to call `AddDataProtection()` in a tenant context (using its isolated service collection). And after the call of the default DP config to be able to override it.

This means that you would need to do it through a module. But we have helpers to registers things at the app level but which run in tenant contexts, as done by a module which would be enabled for all tenants.

So, in your mvc app i would use

            var builder = services
                .AddOrchardCore()
                .AddMvc();

            // Using this helper on the 'OrchardCoreBuilder' allow to execute the delegate
            // in a tenant context, as it is done by the startup of a module which is enabled.
            builder.ConfigureServices((collection) =>
            {
                // do not use 'services' here but 'collection'.
                collection.AddDataProtection()
                   .SetApplicationName("MT5API")
                      .PersistKeysToFileSystem(new DirectoryInfo(_env.ContentRootPath))
                       .SetDefaultKeyLifetime(TimeSpan.FromDays(36500)); 
            }, 10); // the order parameter > 0 to ensure it runs after the default configuration

Our default DP config uses the same helper. When using this helper the default order property is 0 as for module startups. But for the same order value, module startups run after the pseudo startups registered by this helper. That's why it was working with your module without overriding its startup order property.

**Comment by kamikyo** [comment]
@jtkech Thank you very much for your patience and help.
I understand.
You made me have a better understanding of OrchardCore's framework.

**Comment by roopicareington** [comment]
Even I am getting the same error which is occuring for 50 percent of the time. Some api calls are yeilding the data but for some api calls i am getting the same error. 

I have tried the exact   same solution but it didnt work. When you say that keys are created per tenant, in DB I only see one key getting created in DataProtectionKeys Table 

Could you help me on this ?

```

  builder.Services.AddOrchardCore().AddMvc().WithTenants().ConfigureServices((tenantServices, serviceProvider) =>
{
    var shellConfiguration = serviceProvider.GetRequiredService<IShellConfiguration>();

  // Add a DbContext to store your Database Keys
  tenantServices.AddDbContext<MyDBContext>(options =>
      options.UseSqlServer(
          builder.Configuration.GetConnectionString("MyDBConnectionString")));



  // using Microsoft.AspNetCore.DataProtection;
  tenantServices.AddDataProtection().SetApplicationName(shellConfiguration.GetValue<string>("CustomTitle"))
      .PersistKeysToDbContext<MyDBContext>().SetDefaultKeyLifetime(TimeSpan.FromDays(365));
      
      }, 10);
```

**Comment by itharoopteja** [comment]
Even I am getting the same error which is occurring for 50 percent of the time. Some api calls are yielding the data but for some api calls I am getting the same error.

I have tried the exact same solution but it didn't work. When you say that keys are created per tenant, in DB I only see one key getting created in DataProtectionKeys Table no matter how many tenants I use

Could you help me on this ?

```

  builder.Services.AddOrchardCore().AddMvc().WithTenants().ConfigureServices((tenantServices, serviceProvider) =>
{
    var shellConfiguration = serviceProvider.GetRequiredService<IShellConfiguration>();

  // Add a DbContext to store your Database Keys
  tenantServices.AddDbContext<MyDBContext>(options =>
      options.UseSqlServer(
          builder.Configuration.GetConnectionString("MyDBConnectionString")));



  // using Microsoft.AspNetCore.DataProtection;
  tenantServices.AddDataProtection().SetApplicationName(shellConfiguration.GetValue<string>("CustomTitle"))
      .PersistKeysToDbContext<MyDBContext>().SetDefaultKeyLifetime(TimeSpan.FromDays(365));
      
      }, 10);
```
