### ISSUE TITLE
Setting up default instance with custom theme fails with sqllite

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2369]
Hit the following error:
```
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
OrchardCore.DisplayManagement.BaseDisplayManager.BindPlacementAsync(IBuildShapeContext context) in BaseDisplayManager.cs, line 29
```

**Repo:**
Clone the OC repo
Add a theme to the src\OrchardCore.Themes folder with 
```
dotnet new octheme -o defaultemptytheme
```
Replace references to nuget packages in the newly created project with project references
Add a placeholder.cs (or copy from another theme and make sure you rename the namespace)
Add reference to the theme project from the orchardcore.cms.web project (and make sure it is the startup project)
Build, run and in setup use the sqllite provider

**Comment by sebastienros** [comment]
I have the same exception when no Active theme is defined in the site. And I am currently fixing it for themeless sites, by chance.
