### ISSUE TITLE
Separate Login services for admin/front-end

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2380]
c.f. the discussion during this meeting: https://youtu.be/dyFNRnd8dMo?t=3034

The idea is that sharing the same APIs for front-end users and back-end ones might be an issue. The best example is an e-commerce where the site's admins should not be mixed with users. And maybe the stores should be also different, some being put in common. Or maybe the external login providers could be different.

Right now the default behavior is to have a single store and set of APIs. A solution would be to have an optional feature and configuration dedicated for the front-end.

**Comment by rserj** [comment]
This is actually what we do now in O1.
We rewrite the membership system by using external services to store Users and Admins separately we also use different interfaces to manage Admins vs Users.
We host Admin Tool separately from Users facing site. Admins have different roles, like tech support Admin or Forms reviewer Admin,...
I think such separation make sense for scenarios, like Banking or Insurance.

**Comment by sebastienros** [comment]
Suggestion:
- Internal and External users should be able to have different ways to authenticate. Internal might require AD, while external ones would be able to use db pw/login or Facebook.

**Comment by rserj** [comment]
I think we should maximum reuse our current implementation of asp.net identity/openId, we might need different configuration/implementation for Stores and Managers. It will be nice to have an ability to

-Configure different Authentication methods/oauth-flows for Admins vs Front end users 
(for now, coockie based auth for Admins will be enough)
- Configure different Password policy
-Ability to store Admin users in a different DB

**Comment by remesq** [comment]
I've been following recent discussions on Gitter about this. In 1.x I used a variety of things to handle log-ins:

- Extended Registration and User Profile Modules (forget if they were separate or one and the same) - this helped with providing a front-end registration method.
- Using a Local Redirect I would secure a website based on whether the user was authenticated.
- I used a Layout Filter with "Layout__Account" to provide users with a log-in mechanism, and supplemented it with my own LogOn.cshtml page and other code.

My suggestions would be to keep any User within the OC module/DB. Maybe allow an Admin the ability to create a separate type of user. Sebastien suggested "Customer", but if you hard code that you lock people in. Giving people the mechanism to create their own might be more open-ended. And keeping them within OC might prevent dozens of variations of the same type of module. Additionally, if you provide hooks for external log-in mechanisms you provide the Admin with options (stock, customizable, external).

For Registration, it could be similar in that you provide a stock registration (back-end), a customizable one (front-end), and access to an external one.

In either case, if Users or Registration have extensibility hooks, the high-end developers can customize code to their needs while allowing less-abled users (such as myself) the ability to tap into common functionality available to everyone. A common base would benefit everyone.

All of the pages related to Users and Registration can then be opened to Themes, allowing the Admin to customize the styling with .cshtml files and keeping it uniform within OC.

Just my two cents

**Comment by webmosphere** [comment]
I am desperately in need of this feature. Do we have a rough ETA?

**Comment by sebastienros** [comment]
@webmosphere can you provide an ETA? ;)

Nobody has accepted the challenge yet.

**Comment by sallenkov** [comment]
any updates or solutions?

**Comment by Piedone** [comment]
You can override the login form to display different SSO options (we do this too) based on the URL, for example, so you can customize that. I don't see how the user store being common would be an issue.

So, is still still applicable?
