### ISSUE TITLE
Order By clause in SQL query has no effect when returning Documents

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2382]
When specifying an order by clause, like ´order by DisplayText´ in a SQL query with the option "Return Documents" checked, does not order the items returned.

**Comment by psijkof** [comment]
I believe that when sorting on a property of the contentitem, not in the index, it does work correctly.
What is the reason for that?

**Comment by sebastienros** [comment]
After talking with @psijkof it seems to be an issue with the way sqlite accepts columns that don't exist in its queries: https://github.com/sebastienros/yessql/issues/122
