### ISSUE TITLE
Can trigger a controller of a disabled module.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#2389]
Maybe not so important because the module services are not registered and its custom routes are not configured, but if a controller doesn't use any of these services, you can trigger it even if the related module is disabled. Note: it is filtered for module razor pages.

Are we missing a filter?

**Comment by sebastienros** [comment]
Maybe using an ActionSelector ?

**Comment by jtkech** [comment]
I fixed it in #2397.
