### ISSUE TITLE
Implement UI composition for editing users

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#239]
Right now the Orchard.Users module is handling the whole user edition experience by rendering its properties and the roles.
If we want to support extensibility on this screen we need to implement a custom base driver class for it. This could also support front end user display and edition with a custom display type, aka profiles.

NB: The idea is that UI composition doesn't require entities to be content items.

**Comment by agriffard** [comment]
User extensibility done in #1054 ?

**Comment by sebastienros** [comment]
Yes
