### ISSUE TITLE
Access Azure Blob Storage with shared access key

### ISSUE THREAD

**Issue by ThisNetWorks** [OrchardCMS/OrchardCore#2394]
Is it possible to access Azure Blob Storage with a Shared Access Key (set on the container itself), rather than providing the storage account master key.

e.g. if I try to connect to blob storage using Shared Access Key credentials like
`"ConnectionString":"BlobEndpoint=https://xyz.blob.core.windows.net;SharedAccessSignature=sv=etc al"`
access fails because the Shared Access Key does not allow Orchard to set container permissions, or create the container. However in this case it already exists, and has signature has read/write/list/delete access - the most it can be given.

It all works fine if I use the blob storage master key credentials e.g.

`"ConnectionString": "DefaultEndpointsProtocol=https;AccountName=xyz;AccountKey=xyz==;EndpointSuffix=core.windows.net;"`

However that then allows access to the entire blob storage account, which has numerous other blobl containers in it, with restricted access

**Comment by sebastienros** [comment]
So we just need to check if the container exists before trying to create it, which won't require the API key.

**Comment by ThisNetWorks** [comment]
Yes, I don't think we can check container existence with a Shared Access Key, we can only check for existence of files in a container. I see there's a stub file that gets put in the root of the container, so we could check for that.
I can have a look and put a pull request in. 
Am thinking that we'll check for the stub file first, if it exists, then skip the other container checks, but if it doesn't carry on with trying to create the container and assign permissions, and put a note in the readme as to the different behaviours?

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/issues/3537
