### ISSUE TITLE
Landing page  poblem

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#2396]
i installed agency cms. when i want to edit item like a team or other landing page items, the information all don't show for me after saving the edit.and if i add new item o create new landing page it has the same problem and i cant see the new information items.

**Comment by psijkof** [comment]
What version are you using?
Working with nuget packages or the repo? What version?
What did you do that lead to this situation?

**Comment by aghili371** [comment]
I have got the last version from git and I compile the source. I got the Master branch. 
just I edit o remove an item from lead sections. for example, I deleted one member from the team. when I save the information and come back again to edit the lead, no item shown.
one week ago it was working but get the last update from GitHub and I got this problem. I can see the information in the database. but the application not able to show data in admin and compile end page.

**Comment by sebastienros** [comment]
Please use the dev branch which has all the fixes.

**Comment by sebastienros** [comment]
Also maybe an issue with Draft vs Publish. Save is just saving a draft, and the changes won't be rendered on the site until it gets Published.

**Comment by aghili371** [comment]
i published the project. i will test again.
