### ISSUE TITLE
Document all global methods

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2403]

**Comment by agriffard** [comment]
http://docs.orchardcore.net/en/dev/docs/reference/modules/Scripting/#methods

Variables and Parameters still need to be documented.

**Comment by hishamco** [comment]
If the intend of this code documentation, I already started to document some projects some PRs are still not merged, but I will continue into to document other projects

**Comment by sebastienros** [comment]
@hishamco this is not about code docs.

**Comment by hishamco** [comment]
Ok, got it :)
