### ISSUE TITLE
Remove usage of JSon() action responses

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2405]
This can lead to thread pool exhaustion.
Prefer to return the object directly, with potentially a `ActionResult<T>` response type.

/cc @PinpointTownes @matiasmolleja @sebastienros

**Comment by PinpointTownes** [comment]
Interesting. Can you please share more details?

**Comment by PinpointTownes** [comment]
Looks like a MVC bug that could be fixed on their end without us having to change anything. 

TBH, I personally like using `Json()` for APIs that don’t need content negotiation, which is the case for the userinfo endpoint where we’re using this method.

I’m not opposed to changing that: we already use the `[Produces]` attribute to ensure we always return JSON, no matter what’s requested by the client.
