### ISSUE TITLE
Bag existing items

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#2410]
Will bag have the ability to add existing items also in time?  Are items in a bag only suppose to have one parent?  I read in comments that people expect Bag to be used for hierarchies.  Documentation is needed to give simple scenarios of how bag, list, or whatever need to be used.

**Comment by sebastienros** [comment]
Bags contain content items which can be shared (composition). You can use Lists to reference independent content items, but right now it's missing the functionality to select other content items.

Or use the Content Field Picker to reference a content item, like Bags but with references.

**Comment by sebastienros** [comment]
Don't use a Bag. Use the Content Item Picker

Create all you lessons.
Create a Module type and add a Content Item Picker field. Edit the field properties and only allow Lesson.

**Comment by JoshTango** [comment]
Ok and if I want to display the list in a linear fashion and sort it will that functionality come in time?
