### ISSUE TITLE
Azure Blob Storage w/ImageSharp Resizing Middleware

### ISSUE THREAD

**Issue by ThisNetWorks** [OrchardCMS/OrchardCore#2413]
Using blob storage means ImageSharp middleware doesn't seem to work - because the url gets rewritten immediately to the azure storage endpoint, so it doesn't pass through the orchard server to get caught by the middleware.
Is there any further configuration that can / needs to be done to get it to pass through the middleware?

And if we do pass it through the middleware do we then miss out on the performance advantage of serving direct from blob storage (or cdn if configured)

**Comment by sebastienros** [comment]
We should not expose the public url of the blobs. We should instead copy the blob locally so it's served from Orchard instead, as a local cache. We need to find a way to invalidate the local files. Mayne ImageSharp.Web has a solution for that.

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/issues/3537
