### ISSUE TITLE
Invalid configuration exceptions are thrown when enabling the OpenID server feature for the first time

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#2414]
Our recent changes in the OpenID module making the routes configurable have unfortunately broken it for new installations, as theses line will result in an exception being thrown when the OpenIddict server options are not in a valid state (which is typically what happens when the OpenID server settings are unitialized):

https://github.com/OrchardCMS/OrchardCore/blob/18bf308d33b8f64c431e612b902d8301d1134888/src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs#L109-L115

![image](https://user-images.githubusercontent.com/6998306/45955327-e0998500-c00f-11e8-94a3-d7db45da85f4.png)

The bad thing is that an exception thrown at this place will make the entire tenant unusable (existing tenants with the OpenID server correctly configured are not affected).

Possible workarounds:
  - Use a try/catch to swallow exceptions: ugly but simple to implement. 
  - Store the endpoint paths are properties in `OpenIdServerSettings` and call `OpenIdServerService.ValidateSettingsAsync(settings)` to validate settings before registering the MVC actions (clearly my favorite option).

/cc @sebastienros @MatthijsKrempel

**Comment by sebastienros** [comment]
We need to validate the settings before doing anything with it. And when the settings are set, the tenant is restarted and everything will be setup.

**Comment by MatthijsKrempel** [comment]
Will have a look.

**Comment by PinpointTownes** [comment]
I'll take care of fixing it.
