### ISSUE TITLE
OIDC ExternalLogin throws 404

### ISSUE THREAD

**Issue by robsrip** [OrchardCMS/OrchardCore#2416]
I'm trying to configure Azure AD as an external provider and after setting up all the endpoints the OrchardCore POST to ExternalLogin is throwing a 404 with the following IOException: 

"Unable to retrieve document from: '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'."

Has anyone seen this error before when configuring external auth?

**Comment by MichaelPetrinolis** [comment]
Have you followed the steps described on this article? https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect/

**Comment by MichaelPetrinolis** [comment]
Create a new azure ad application, and in home page use this address http://localhost:5000/signin-oidc
When you enable OIDC in orchard, as clientid put the ApplicationID,
as authority from the endpoints put https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx and use the id_token response type.

This should work without more configuration on the manifest.

Login and link in the external logins your AzureAD

**Comment by robsrip** [comment]
Thank you Michael. I believe I was using the wrong endpoint address. I'm now getting passed to Azure AD for authentication, and am now digging into how a user is then registered or matched with an existing OC User.

**Comment by sebastienros** [comment]
Should we add some documentation, or a blog post tutorial to show how to do it?

**Comment by robsrip** [comment]
Once I get my head wrapped around it I'd be happy to help with a setup tutorial.

**Comment by robsrip** [comment]
I'm also trying to configure an Azure AD B2C instance to test that out.

**Comment by robsrip** [comment]
I got an Azure AD B2C instance connected to my OrchardCore dev site, but to do so I had to remove the 'profile' scope from the OpenIdConnectOptions in the OpenIdClientConfiguration.Configure() method because B2C doesn't accept that scope.  If you don't remove it, you get the following exception:

OpenIdConnectProtocolException: Message contains error: 'invalid_request', error_description: 'AADB2C90012: The scope 'openid profile' provided in request is not supported.

**Comment by MichaelPetrinolis** [comment]
For openid connect the openid scope is required. https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest the profile scope is requested in order to receive the email claim and match/create a local user. You might change the manifest and allow the profile scope in the azure B2C. On the other hand, we should remove the profile scope and allow the user to add it in the extra scopes field.

**Comment by robsrip** [comment]
I'm still looking through the source code to see where the profile scope is getting added. It doesn't appear to me that the profile scope contains the email but a list of other profile related claims.

profile
OPTIONAL. This scope value requests access to the End-User's default profile Claims, which are: name, family_name, given_name, middle_name, nickname, preferred_username, profile, picture, website, gender, birthdate, zoneinfo, locale, and updated_at.

https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims

**Comment by MichaelPetrinolis** [comment]
The reason that you can't find it is because it is the default behavior of the OpenIdConnect client.

https://github.com/aspnet/Security/blob/release/2.1/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs 

The spec states '*Scope values used that are not understood by an implementation SHOULD be ignored*' so it seems that the Azure AD B2C should ignore the profile scope. Maybe there is some config option in Azure.

**Comment by robsrip** [comment]
Thanks Michael. I'll keep digging into the B2C documentation. It might require a custom policy

**Comment by robsrip** [comment]
Ok I finally believe I've got this sorted. I was using what I think was an older version of the B2C endpoint, and once I updated it to the v2.0 it looks like it's behaving as expected. 

If you are setting up an Azure AD B2C instance in the OrchardCore.OpenId.ClientOrchard, make sure your Authority property is formatted as https://{AzureAdB2CInstance}.b2clogin.com/{Tenant}.onmicrosoft.com/{Policy}/v2.0

Hat tip to the Azure-sample: https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp

**Comment by tigergus** [comment]
@robsrip 
Thanks for this tip. The missing "/v2.0" was the cause of problem for me :). This was while I was configuring Identity server 4 to connect to Azure B2C.
