### ISSUE TITLE
GetContentItemByAliasAsync expects "alias:" prefix, which is counter intuitive IMHO

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2420]
```
ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary<TKey, TValue>.FindEntry(TKey key
``` 
When using like:
`var welcomeContent = await Orchard.GetContentItemByAliasAsync("welcome");`

Anything I can do, or is this a bug?

**Comment by awyl** [comment]
did you try `alas:welcome`?

**Comment by psijkof** [comment]
Thank you @awyl , Using "alias:welcome" returned the right ContentItem.

I will change the title to counter intuitive, because I think getting an Alias, wouldn't require specifying "alias:" as a prefix.

**Comment by sebastienros** [comment]
Well, there are many kinds of aliases, like `autoroute`, `alias` (from the alias part), `contentItemId` ...
But I agree with the confusion. Maybe the Alias part should be renamed `HandlePart`, or the method.

**Comment by psijkof** [comment]
GetContentItemByHandleAsync, sounds good to me

**Comment by sebastienros** [comment]
I would have suggested to change the method name to something that doesn't use "alias", because otherwise we would have to change the part.

`GetContentItemByNameAsync` or ByHandle, ... anything else than alias ...
