### ISSUE TITLE
ASP Tag Helpers Not Resolving from Base Theme

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#2421]
I have a Razor view in my base theme (call it Theme A) which contains the following tag markup (simplified):

```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inherits OrchardCore.DisplayManagement.Razor.RazorPage;

<a class="dropdown-item" asp-route-area="OrchardCore.Users" asp-controller="Account" asp-action="ChangePassword"><i class="fa fa-lock fa-fw"></i> @T["Change Password"]</a>
```

I have a theme which inherits this base theme (call it Theme B). The asp-route is not resolved when used this way. The output HTML markup contains all of the tags without resolving them

However, if I copy this exact razor view into the theme which inherits the base theme (i.e. Theme B), everything works out and the asp-route is resolved. It seems the Tag Helpers are not resolved from the base theme when it is inherited. Has anyone else experienced this / have a work around?

**Comment by jtkech** [comment]
Just tried, it works on my side.

I created an empty `TestTheme` with no code and no views.

    <Project Sdk="Microsoft.NET.Sdk.Razor">

      <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
      </PropertyGroup>

      <ItemGroup>
        <ProjectReference Include="..\..\OrchardCore\OrchardCore.Theme.Targets\OrchardCore.Theme.Targets.csproj" />
        <ProjectReference Include="..\..\OrchardCore\OrchardCore.DisplayManagement\OrchardCore.DisplayManagement.csproj" />
      </ItemGroup>

      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc" />
      </ItemGroup>

    </Project>

Only a manifest file which defines `BaseTheme = "TheTheme"`.

    using OrchardCore.DisplayManagement.Manifest;

    [assembly: Theme(
        Name = "The Test Theme",
        Author = "The Orchard Team",
        Website = "http://orchardproject.net",
        Version = "2.0.0",
        Description = "The Test Theme",
        BaseTheme = "TheTheme"
    )]

Then i selected `TestTheme` as the current theme, and i checked that the `ChangePassword` link works.

- So, because the view is still executed through the base theme, does the link work if the base theme is selected as the current theme? Maybe something is missing in the base theme itself.

**Comment by sebastienros** [comment]
Thanks. Feel free to commit this in the samples.

**Comment by jeffolmstead** [comment]
@jtkech I was using Orchard via Nuget packages and it looks like according to your ProjectReference you are utilizing the source code. However, I have reattempted this again and it is working now, so sorry. I had tried a couple of times and I can't now tell you what the difference was. Thanks for checking on this!

**Comment by sebastienros** [comment]
It could be from a very recent work that @jtkech did.

**Comment by jtkech** [comment]
@jeffolmstead no worries ;)
