### ISSUE TITLE
Media picker field : predefined folder

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2430]
I have a use case where I need to save images in a predefined folder. I think it would be relevant to either have settings on the current media picker for predefining a folder where it would save medias and also restrict by media types. Else, we could also have a more adequate upload control for that matter.

@matiasmolleja

**Comment by sebastienros** [comment]
It requires a new field editor which would only allow to upload new images as they are owned/contained by the content item. these media can't be shared. It would use a special folder in the Assets, that could be hidden from the UI (if not in a special mode). Once a media is removed from this field, it's deleted. 

Deleted media should go in a recycle bin to prevent users from losing their images when they just want to try to remove them from the field.

**Comment by matiasmolleja** [comment]
I like the editor approach, your "field editors" feature seems perfect for that  ;)
We should provide a way to assign files on that hidden folder a unique name right?



> Deleted media should go in a recycle bin to prevent users from losing their images when they just want to try to remove them from the field.

I don't get that, sorry. What do you mean by trying to remove?

**Comment by sebastienros** [comment]
@matiasmolleja 

> delete the image

Why do you delete the image? You can just remove it from the list. Removing the image, even in the main Assets page will break existing content items.

**Comment by matiasmolleja** [comment]
@Skrypt  @sebastienros can we close it?
I forgot to add the "Fixes" when I created the attached media field PR. This issue was the origin of the PR.

**Comment by Skrypt** [comment]
Yes
