### ISSUE TITLE
Content items in a bag part are not indexed

### ISSUE THREAD

**Issue by hswami** [OrchardCMS/OrchardCore#2431]
The current indexing implementation doesn't include content items that are in a bag part in the index.

**Comment by sebastienros** [comment]
Note that fixing it will add all indexed content to the container of the bag part. Which should be fine in most cases. Like a Landing Page will have all the content of its inner content items.

**Comment by hswami** [comment]
I submitted a PR #2436 for this. Please review and provide feedback.
