### ISSUE TITLE
Integrate MVC "Make FileVersionProvider Replaceable" Improvements When Available

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#2435]
Once MVC 2.2 is available and integrated with Orchard Core, should update OrchardCore.ResourceManagement.TagHelpers.StyleTagHelper in order to append a "version" onto the CSS (and likely JS) files to allow for automated cache busting. Here is the MVC 2.2 issue discussion: https://github.com/aspnet/Mvc/pull/8455/files

Currently: /style/site.css
Future:     /style/site.css?v={Hash}

**Comment by deanmarcussen** [comment]
Can we close this, support was added in https://github.com/OrchardCMS/OrchardCore/pull/3581

**Comment by jeffolmstead** [comment]
Agreed.
