### ISSUE TITLE
Existing site: Redirected to Setup

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2439]
@aodl said on gitter he had some trouble after updating an OC application with the latest version of the packages: https://gitter.im/OrchardCMS/OrchardCore?at=5bad10e04d320a463b025808

I also have the same issue with my site, created with a SqLite db: The connecting string field isn't being displayed. 
It may come from the changes that @siyamandayubi did on the setup (DatabaseConfigurationPreset)?

I added the missing properties in settings.txt but it doesn't fix it:
```
  Secret: ~
  RecipeName: ~
```

Any idea to fix this bug or migrate my site?

With a site created from zero, it does not occur, but I can see the differences between my app and a new one.

**Comment by giannik** [comment]
same here. Either that or the recent Orchardcore.setup refactoring is
causing the issue.

**Comment by agriffard** [comment]
The cause must be the renaming of namespaces with the OrcharCore.Abstractions change.

In the 2 first row of the Document table, the value in the `Type` column have to be changed according to this new namespace:

```
OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Environment.Shell.Abstractions
```
should now be:
```
OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Abstractions
```
And
```
OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Environment.Shell.Abstractions
```
should now be:
```
OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Abstractions
```

This fix allows to launch the site.

I let the issue open until this change is explained.

**Comment by giannik** [comment]
Yes, that fixes it.
Thank you, Antoine.

**Comment by aodl** [comment]
Brilliant, thanks for looking into it

**Comment by siyamandayubi** [comment]
Sqllite has a connectionString support in orchard core?

https://github.com/OrchardCMS/OrchardCore/blob/8c45dd1ac5a68eae4d3931d304ac9ae1d4d8c6e6/src/OrchardCore/OrchardCore.Data/OrchardCoreBuilderExtensions.cs#L33

**Comment by agriffard** [comment]
Should we write some kind of Migration notes for Beta 3 explaining what to do to update the data and fix the issue?
