### ISSUE TITLE
Document OrchardCore.Tenants.FileProvider

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2440]
Create documentation about the `OrchardCore.Tenants.FileProvider` feature.

**Comment by sebastienros** [comment]
Note to myself: we can have a wwwroot in each tenant app_data that will only be served for this tenant. And it can be used to override css files for instance.

**Comment by agriffard** [comment]
See https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Tenants/
