### ISSUE TITLE
Workflow: Tenant activity, events and tasks

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2442]
@sfmskywalker : Should we create classes in the Tenants module, similar to Content workflow elements?

In a Workflow folder:
	TenantActivity
	CreateTenantTask, DeleteTenantTask
	TenantCreatedEvent
		Drivers
		ViewModels
		Views/Items
			TenantCreatedEvent.Fields.Design.cshtml
			TenantCreatedEvent.Fields.Edit.cshtml
			TenantCreatedEvent.Fields.Thumbnail.cshtml

**Comment by sebastienros** [comment]
Yes you can. As long as you only depend on the Workflows abstractions, and the feature `[Requires]` the Workflow feature to be enabled.
