### ISSUE TITLE
In Master branch ： The type 'RazorViewAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#2443]
`An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
Generated Code

The type 'RazorViewAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/.Modules/OrchardCore.Setup/Views/Setup/Index.cshtml", typeof(AspNetCore.__Modules_OrchardCore_Setup_Views_Setup_Index))]
The type '__Modules_OrchardCore_Setup_Views_Setup_Index' already contains a definition for '__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper;
The type 'FormTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
The type 'RenderAtEndOfFormTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.LabelTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_LabelTagHelper;
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper;
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.ValidationMessageTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper;
The type 'SelectTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper;
The type 'SelectTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper;
The type 'OptionTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper;
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'RazorInjectAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                                                                   Write(T["The site name is required."]);
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    EndContext();
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                        await __tagHelperExecutionContext.SetOutputContentAsync();
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                        if (!__tagHelperExecutionContext.Output.IsContentModified)
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                        __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "3f23e353aa8a40018a89094688cd038d", async() => {
The type 'OptionTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                        if (!__tagHelperExecutionContext.Output.IsContentModified)
Cannot assign to 'Value' because it is a 'method group'
+
                        EndContext();
Argument 2: cannot convert from 'method group' to 'object'
+
#line 130 "C:\Users\hyzx8\Pictures\AP\OrchardCore-master\src\OrchardCore.Modules\OrchardCore.Setup\Views\Setup\Index.cshtml"
The type 'OptionTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    EndContext();
Cannot assign to 'Value' because it is a 'method group'
+
#line 120 "C:\Users\hyzx8\Pictures\AP\OrchardCore-master\src\OrchardCore.Modules\OrchardCore.Setup\Views\Setup\Index.cshtml"
Argument 2: cannot convert from 'method group' to 'object'
+
__OrchardCore_DisplayManagement_TagHelpers_ValidationMessageTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.SiteTimeZone);
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                EndContext();
The type 'SelectTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                EndContext();
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                BeginContext(6065, 54, true);
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                WriteLiteral("\n            <span class=\"text-muted form-text small\">");
The type 'SelectTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                WriteLiteral("\n            <span class=\"text-muted form-text small\">");
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                EndContext();
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
#line hidden
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                EndContext();
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                EndContext();
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
The type 'OptionTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                EndContext();
Cannot assign to 'Value' because it is a 'method group'
+
Argument 2: cannot convert from 'method group' to 'object'
+
#line default
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                    __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_LabelTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
The type 'SelectTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_LabelTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                    await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
The type 'SelectTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                    {
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                    BeginContext(7163, 17, true);
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                    WriteLiteral("\n                ");
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
+
                    WriteLiteral("\n                ");
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    {
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                __tagHelperExecutionContext.Add(__OrchardCore_DisplayManagement_TagHelpers_ValidationMessageTagHelper);
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("fieldset", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "846ebd0c61d74f1b934241379acb4e9a", async() => {
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    }
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
#line hidden
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    EndContext();
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
#line default
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    Write(__tagHelperExecutionContext.Output);
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_9);
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                {
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    BeginContext(9461, 13, true);
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    __tagHelperExecutionContext = __tagHelperScopeManager.End();
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    Write(__tagHelperExecutionContext.Output);
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
                    BeginContext(10020, 13, true);
The type 'LabelTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
__Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.PasswordConfirmation);
The type 'InputTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
__OrchardCore_DisplayManagement_TagHelpers_ValidationMessageTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.PasswordConfirmation);
The type 'ValidationMessageTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
The type 'FormTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        public Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer T { get; private set; }
The type 'RenderAtEndOfFormTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
+
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
Cannot assign to 'Action' because it is a 'method group'
+
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }

Show compilation source
C:\Users\hyzx8\Pictures\AP\OrchardCore-master\src\OrchardCore.Modules\OrchardCore.Setup\Views\Setup\Index.cshtml

Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'
Ambiguity between '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper' and '__Modules_OrchardCore_Setup_Views_Setup_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper'

Show compilation source`

**Comment by jrestall** [comment]
This should help you: https://github.com/OrchardCMS/OrchardCore/issues/2336#issuecomment-419271572

**Comment by hyzx86** [comment]
> This should help you: [#2336 (comment)](https://github.com/OrchardCMS/OrchardCore/issues/2336#issuecomment-419271572)

Thank you, but there are too many conflicting assemblies. I've switched to the dev branch and running successed.

**Comment by sebastienros** [comment]
Duplicate
