### ISSUE TITLE
Assign role(s) on users registration

### ISSUE THREAD

**Issue by sipronunciaaigor** [OrchardCMS/OrchardCore#2449]
What do you think about giving the opportunity to the admin to chose which default role(s) a new registered user must have?

i.e.: https://github.com/OrchardCMS/OrchardCore/compare/dev...sipronunciaaigor:sipronunciaaigor/user-default-role

Of course it should be a solution where a dropdown menu or a list of input box must be available... the referred commit is just a working prototype of what I mean

**Comment by sebastienros** [comment]
It might already be doable with workflow. Can you check is there is a workflow event for user registration? If not we could use a PR ;)

**Comment by sipronunciaaigor** [comment]
If it is possible I think I didn't get how to do it with the workflows and, almost sure, I didn't get how to properly customize them.
My non-working steps:
 - New role "UserLevel1"
 - New workflow
 - New Event of type User Task (the only available for users)
 - Set Actions to CreateUser (which is the name of the method of the user class... and I think this is where my logic starts to flow and where my misunderstanding of workflows begins) and assigned to Admin and Anonymous roles
 - New Task of type Set Property (I need to add a value in IList<RoleNames>user property)
 - Set name of the property to RoleNames
 - Set value of the property to UserLevel1

I don't know where to start to create a new workflow event.
Would it be enough to refer to https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Workflows/README/#developing-custom-activities?

**Comment by MichaelPetrinolis** [comment]
you can check #2450 PR which contains events and tasks

**Comment by agriffard** [comment]
We should at least be able to specify if we want to assign a default role on User registration because currently a user witout a role cannot even log into the admin dashboard because of lack of permissions.

It is a bit complicated if we have to make a form with a workflow jut to do this.

A `User created` event would also be useful.

**Comment by sebastienros** [comment]
Solution is to add Workflow event for that
