### ISSUE TITLE
Existing tenants cannot start after updating to beta3-68610 and up.

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#2455]
Introduced by #2199.

You will see setup screen instead.

In the database, document table, ID 1 and 2.  Need to change the assembly name.

```
"OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Environment.Shell.Abstractions"
"OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Environment.Shell.Abstractions"
```
change to
```
"OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Abstractions"
"OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Abstractions"
```

**Comment by agriffard** [comment]
#2439 issue detailled here.

**Comment by sebastienros** [comment]
Duplicate

**Comment by jeffolmstead** [comment]
This may be obvious, but I made the change while my server was running and it didn't take care of it. Need to restart the server for this change to take effect. If you are looking for actual manual "fix" for this you would run a script like this against your database table (replace the {Your Table Prefix} and of course, use at own risk of course):

```
UPDATE [dbo].[{Your Table Prefix}_Document]
SET Type = 'OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Abstractions'
WHERE Id = 1

UPDATE [dbo].[{Your Table Prefix}_Document]
SET Type = 'OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Abstractions'
WHERE Id = 2
```
