### ISSUE TITLE
My fingers slipped on the keyboard

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#2458]
@sebastienros not intentionally but i just did it :)

![shellhost](https://user-images.githubusercontent.com/8586360/46451896-2a653680-c799-11e8-8d27-a0a1a6172bda.png)

**Comment by Skrypt** [comment]
Don't use slippy fingers then 🚎 :trollface:

**Comment by sebastienros** [comment]
@jtkech So did you fix it?

**Comment by jtkech** [comment]
Done through #2463.
