### ISSUE TITLE
Youtube field is always required

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2472]
When trying to post an content item from the admin side that has a youtube field it always fails form validation because the field is required if it's left empty. This field should be required only when specified ; not required all the time.

**Comment by zimplerconsulting** [comment]
I have added a Required setting to the Youtube field, so you can now disable/enable this. It is within PR #2429

**Comment by sebastienros** [comment]
Can you create a distinct PR for that?
