### ISSUE TITLE
`RazorViewAttribute` exists in multiple places.

### ISSUE THREAD

**Issue by kieronlanning** [OrchardCMS/OrchardCore#2474]
I've just created a new empty .NET Core 2.1 solution, added the latest preview bits from NuGet.org and I get the following error:

```
The type 'RazorViewAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

I've checked and tried various solutions in #2443 and the linked issues in there, but nothing works.

To make it clear, this is a blank page project. 

VS2017 -> New Project -> Add the beta 2 bits -> Call the Use/Add orchard extensions in Startup followed by run.

![image](https://user-images.githubusercontent.com/5364423/46654643-49046c80-cba1-11e8-96b3-06b6680117d4.png)

![image](https://user-images.githubusercontent.com/5364423/46658059-b7e5c380-cba9-11e8-9a14-383f2206a312.png)

**Comment by psijkof** [comment]
You need to update one of the references. 
It could mean that for using the beta2 bits, you should downgrade your project to 2.1.2 for Microsoft.AspNetCore.Mvc.Razor

**Comment by kieronlanning** [comment]
I'm going to close this, updating to the `beta3` build available on `myget` solved the problem.

**Comment by jean** [comment]
How does one update to the `beta3` build available on `myget`? I'm still dead in the water.

**Comment by Skrypt** [comment]
In your csproj you need to set version of assemblies to beta 3.
