### ISSUE TITLE
Asp-src taghelper not tenant aware?

### ISSUE THREAD

**Issue by AidosMarcos** [OrchardCMS/OrchardCore#2476]
Created a OC Module with AddPart
Added wwroot with assets
In the .Edit.cshtml added some script with taghelper asp-src
Using the moduelName/Assets/file.css or .js
Running the back-office for a tenant shows errors that is trying to find this files in the default tenant
Example:
`<script asp-src="~/TestTagPart.OrchardCore/Assets/js/jquery.min.js" at="Head"></script>`
Results in error in browser:

> HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
> GET - http://localhost:62470/TestTagPart.OrchardCore/Assets/js/jquery.min.js

Expected it would get: 

> http://localhost:62470/TenantName/TestTagPart.OrchardCore/Assets/js/jquery.min.js

**Comment by sebastienros** [comment]
No, static files are not prefixed by tenant.

**Comment by AidosMarcos** [comment]
Ok, but this only started happening after we updated nugget packages to lastest version, after roleback started working again.
Also static files are only applied to the part module that can be enabled or disabled depending on the tenant, how would a part have its own static files?

**Comment by AidosMarcos** [comment]
Yes, it works like you say. I was the one that was broken. :)
