### ISSUE TITLE
Create Content Task: Allow all content types

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2490]
When you add a task 'Create content' in a Workflow, you need to select the Content type you want to create.
The list only contains the Content types that are creatable but sometimes, we will want to generate a Content type that does not appear in the 'New' menu item the Admin UI, for example if it is only a Workflow that will create it or if it is inside a Container like a List.

So, may be we could list all the content types?

Also, the types should be ordered by name.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Workflows/Drivers/CreateContentTaskDisplay.cs#L23

Just need to remove that line. I will do a PR.
