### ISSUE TITLE
Text Field Editors

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2492]
Now that field editors are available, should we add more editors to a Text Field, like the input type: `text`, `email`, `tel`, `url` ... ?

We could also provide more options, like: `placeholder`, `maxlength`, ... ?

If the Color setting was just an example, we should remove it.

**Comment by sebastienros** [comment]
Placeholder is an option for an editor (fine for the default editor for instance)
MaxLength should be in the main driver. And editor can render some hint if they wish to.
