### ISSUE TITLE
When to release beta3？

### ISSUE THREAD

**Issue by geffzhang** [OrchardCMS/OrchardCore#2499]
When to release beta3,  https://github.com/OrchardCMS/OrchardCore/milestone/5 to complete 38%, roadmap beta3（https://github.com/OrchardCMS/OrchardCore/wiki/Roadmap） should be at the end of August

**Comment by geffzhang** [comment]
@remesq  Beta 3 Nuget doesn't mean myget, what I see on nuget.org is still Beta2.

**Comment by psijkof** [comment]
Check the docs on the dev branch: [docs dev branch](https://orchardcore.readthedocs.io/en/dev/)
You will also find how to use the latest nuget packages.

**Comment by sebastienros** [comment]
I updated the roadmap. Historically we were waiting for Taxonomies and GraphQL to be ready.

**Comment by sebastienros** [comment]
GraphQL is now merged. Taxonomies should follow soon.

**Comment by KANekT** [comment]
I think it is worth waiting for at least another release net core 2.2 :)

**Comment by sebastienros** [comment]
I also think so, I think we should aim for a common release date with 2.2 which is not far away now. If we shipped before we would have to re-release when 2.2 is out. At the same time we are almost ready for beta3, we are just waiting for my Taxonomies PR to be merged, and the other open ones I am working on actively.

**Comment by KANekT** [comment]
Due by December 03, 2018

May be change date for Due this midlestone ?

i think release 2.2 in 4 or 5 December on MS Connect 2018 :)
