### ISSUE TITLE
How to add a content part to user module

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#2502]
I want to make a module, it allows the administrator to dynamically set user attributes, and then the user can fill out these information, and can be indexed and queries. Just like we define a content components, but I don't know how to do it. Who can provide some advice and guidance?

**Comment by sebastienros** [comment]
Create a custom part and driver like this: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Demo/Drivers/UserProfileDisplayDriver.cs

This will only be editable in the admin, but you can create your own controller and view to display these values and change them on the front end.

**Comment by hyzx86** [comment]
Thanks @sebastienros 
This is just an example of how to add a fixed field, and I want to add the ability to dynamically manage the field here

The functionality I wanted to implement would probably include two pages:
1. The administrator can manage user attributes, just like we defined a Content Type or Content Part, and can manage different fields completely in the background
2. Users can fill in these contents, and of course administrators can modify the values of these contents through the user management-> Edit function.

**Comment by pgy866** [comment]
@hyzx86 I also agree to extend user attributes to content types and content management docking, which is very flexible.

**Comment by pgy866** [comment]
In theory, all locations can be understood as content (ie data), just like KOOBOO CMS, including user modules, if used for flexible design that can be extended to content type docking, managing dynamic user attributes is of course good at Umbraco There is a Membership Module that is separate from the site user. It is equivalent to a content type. It can be freely designed and extended. For Orchard core, they seem to have user modules at the same time, but orchard core provides an extended interface, because I am not Programmers don't write code, they can't help you, sorry. Online below this link has a duplicate "https://github.com/OrchardCMS/OrchardCore/issues/1235"

**Comment by pgy866** [comment]
There should be another method, which is to design a content type that a member needs in content management, and directly refer to the content type to the rights management, as a registration of the front-end registered user members of the website, personal homepage, personal information, etc.

But I don't know if he is feasible, theoretically possible.

**Comment by hyzx86** [comment]
Yes, but I think that's not easy to implement.

**Comment by hyzx86** [comment]
Today saw a statistics. In all languages of github, making c # thumb ICONS with the least amount of.. We should try to change to this situation

**Comment by sebastienros** [comment]
I assume you managed to add a custom part to your users as I saw another issue with custom properties. So I am closing this one.

**Comment by vitalybrandes** [comment]
> 
> 
> I want to make a module, it allows the administrator to dynamically set user attributes, and then the user can fill out these information, and can be indexed and queries. Just like we define a content components, but I don't know how to do it. Who can provide some advice and guidance?

Hi,
Did you find the solution for your question? 
Can you share please?
