### ISSUE TITLE
Provide support for eagerly loading related Content Items

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#251]
I have added an issue on YesSQL GitHub to provide a feature that helps Orchard 2 to have a transparent way of avoid N+1 queries when dealing with Content Items with fields pointing to other Content Items, that I thing you could be interested on discussing.

This is the issue https://github.com/sebastienros/yessql/issues/21

**Comment by Piedone** [comment]
You can easily eager load items with a query, what we do all the time in the codebase. Please elaborate if that's not suitable, and what exactly you'd imagine.
