### ISSUE TITLE
OrchardCore.Abstractions migration issue

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2512]
When I upgrade an OC application that was previously referencing beta3 packages before the OrchardCore.Abstractions change, there is an error when I launch the Web project:
`The type 'ModuleNameAttribute' exists in both 'OrchardCore.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'OrchardCore.Modules.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	MyApp.Web	...\MyApp.Web\obj\Debug\netcoreapp2.1\MyApp.Web.AssemblyInfo.cs`

There is a custom theme and a custom module also referenced but even if I clean everything, the error messages are still displayed, even if there is no reference to OrchardCore.Modules.Abstractions anywhere.

**Comment by Skrypt** [comment]
Could you still have a reference to that module in the DB?

**Comment by sebastienros** [comment]
Send me the zip file with everything (without app_data)
