### ISSUE TITLE
BackgroundTaskService.SetDelay should be able to restart timer optionally

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#2528]
I am trying to create a background task that runs in every second instead of the default 1 minute interval. I see that there is a SetDelay method on the IBackgroundTaskService which looks like a good way to achieve this. I've called it in the Startup.Configure() method of my module, however, it made my background task stop immediately. When I called the BackgroundTaskService.Activate() it restarted and works fine, however, it reactivates all the background tasks. I am not perfectly sure if it will be an issue if there are multiple background tasks but it will definitely restart all the timers.

Maybe there's another way to achieve this, if yes, please point me to the right direction. However, I think one simple solution would be to add an (optional) parameter to the SetDelay method which prevents the Timer to stop and will just keep working with the new period.

**Comment by sebastienros** [comment]
@jtkech has a branch with an improved background task service that support any cron definition. Can you try this branch?

**Comment by barthamark** [comment]
Which branch should I try? I didn't find it.

**Comment by jtkech** [comment]
`hostedService` branch, see #1572. Schedules can be defined through attributes, see in the code for an example. And there is a feature which allows to defined them through the admin UI.

Hmm, but we use crontab whose granularity is one minute. Here we would need another library which allows to specify seconds.

**Comment by barthamark** [comment]
Thank you! I'll check that branch. If this provides extensibility for replacing the library to use 1 second intervals it's probably fine.

**Comment by sebastienros** [comment]
@barthamark what is the scenario that would require seconds?

**Comment by barthamark** [comment]
Polling an external API on backend (in a background task) and broadcasting the value real-time to frontend clients using SignalR if the content coming from the API has been changed.
Actually, 5 or 10 seconds seem to be safer but cron still won't work in my case with the one minute granularity. Now it works fine with the current Background Task implementation that uses Timer but I am still investigating other possibilities.

**Comment by barthamark** [comment]
I think this has been answered thank you both for the help.
