### ISSUE TITLE
Is this a version merge error?

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#2536]
After adjusting the management of the predefined list , is  this code not needed？
I remember that the previous version seems to have been deleted.

\OrchardCore\src\OrchardCore.Modules\OrchardCore.ContentFields\Views\TextFieldPredefinedListEditorSettings.Edit.cshtml

![image](https://user-images.githubusercontent.com/15613121/47198388-78d02300-d39e-11e8-8414-34999f44a7a1.png)

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/2527
Part of this PR. What is the issue? Could you hop on Gitter for asking questions if they are not issues?
