### ISSUE TITLE
(Question) EntityFrameworkCore per tenant DbContext confgiuration

### ISSUE THREAD

**Issue by pjc89** [OrchardCMS/OrchardCore#2539]
Hello,

I'm trying to build a multi-tenant application with OrchardCore, i was able to setup a little MVC application with 2 tenants, now i would like to register a DbContext that should use a different connection string for each Tenant. 

Is there a way access tenants specific configuration during application startup? Should i use a Factory and read the information i need from ShellSettings? If you needed to do something like this how would you implement it with OrchardCore? 

Thanks in advance for your attention,  OrchardCore is awesome, can't wait for the stable release ^_^

**Comment by PinpointTownes** [comment]
Hey,

https://github.com/OrchardCMS/OrchardCore/issues/1343 should put you on the right track.

**Comment by pjc89** [comment]
Ok, That helps. Thank You.
