### ISSUE TITLE
Installing Custom Theme fails

### ISSUE THREAD

**Issue by sddev-dotnet** [OrchardCMS/OrchardCore#2550]
I am trying to create a new theme following the youtube video "Building a theme for Orchard Core from scratch." I have added the new project reference to the OrchardCore.CMS.Web and tried to run the application from visual studio. The site starts up but the new theme doesn't show up in the admin panel. My project file looks like: 

```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\OrchardCore.DisplayManagement.csproj" />
    <ProjectReference Include="..\OrchardCore\src\OrchardCore\OrchardCore.Theme.Targets\OrchardCore.Theme.Targets.csproj" />
  </ItemGroup>

</Project>
```

I have also tried building the theme using the dotnet cli command `dotnet new octheme`, and when I try and reference it in the web project I get an exception about not finding OrchardCore.Module.Abstractions dll. 

Does the theme project have to live in a specific directory? I noticed the other themes are not referenced in the web project, is that still the right way to include it?

**Comment by jtkech** [comment]
You theme can be anywhere but when you reference `Theme.Targets` as a project you need to import some msbuild scripts. This is done automatically when you use package references.

See the .props and .targets files in the `OC.Themes` folder of the solution. What you can do is to copy paste these files in a parent directory containing your theme. If you use the full files with all imports you will not need anymore to specify the mvc package version.
