### ISSUE TITLE
Enabling Data Protection (Azure Storage) module renders instance unusable

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2563]
Repro:
Create a new instance or tenant
Enable 'Data Protection (Azure Storage)'
Site breaks and is not accessible after (including admin).
Exception thrown:
```
ArgumentNullException: Value cannot be null.
Parameter name: connectionString
Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(string connectionString) in CloudStorageAccount.cs, line 529
```

**Comment by psijkof** [comment]
I understand this is a critical issue. But enabling this module before having the setting in place shouldn't break the app imho.

I see this is logged:
`"Unable to connect to Azure Storage to configure data protection storage. Ensure that an application setting containing a valid Azure Storage connection string is available at `Modules:OrchardCore.DataProtection.Azure:ConnectionString`."`

Can't we make a view for this module to either display this error message and/or allow the admin to enter the setting?

**Comment by psijkof** [comment]
In general, imho it looks bad when enabling a module renders the admin useless. 
Of course we can restore this by either disabling the module in the database, or by providing the right settings... but … shouldn't the admin be the place that is in control?

**Comment by PinpointTownes** [comment]
I'm tempted to think we should at least add a `return;` here: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.DataProtection.Azure/Startup.cs#L47

**Comment by psijkof** [comment]
Created PR with simple fix. Enabling doesn't break site. It just logs a critical error.
