### ISSUE TITLE
ContentPickerResult missing display text

### ISSUE THREAD

**Issue by aodl** [OrchardCMS/OrchardCore#2571]
When selecting a content item from the content picker dropdown, it is entirely possible (and seemingly not unlikely) that the display text can be blank for some options, which is confusing and not very helpful.

This is because the default implementation of IContentPickerResultProvider gets the display text directly from the contentItem.DisplayText property. This seems to only be populated when the content item has a Title part (or some other part that is in charge of setting DisplayText).

**Comment by sebastienros** [comment]
I assume it should display the content type and the content item id in this case.

**Comment by aodl** [comment]
The pull request that I raised displays the content type, and the content item's display text if available. I did a Google to see how others had got around similar issues with DisplayText, and it seems that ContentType and DisplayText are frequently used together when representing a content item.

This makes me think that it would be nice if contentItem.ToString() did this work for us
