### ISSUE TITLE
In place updates, Shopping Cart support

### ISSUE THREAD

**Issue by papyr** [OrchardCMS/OrchardCore#2573]
Hello, I wanted to refer to some features updates that 1) WP has and also some newer libs for tenant filters etc. So, that the features set use is more customer/user friendly 

Please take a look at [ABP](https://github.com/aspnetboilerplate/aspnetboilerplate) which has exceeded the Orchards user base and also sadly turned heavily commercial. or Serenity, which both have some very nice features in the framework. I'm sure 15 mins poking around would give some new ideas.

Also, WP has easy add ons like a shopping cart, would be great if we could an module in OC2 or atleast extensions for that.

Lastly, please include a diagram on how shapes/pages are composed from a dev perspective. This would help the dev. have a checklist to ensure he can implement the widgets or pages as needed.

**Comment by sebastienros** [comment]
You should create some issues with the features you think are missing, or should be improved.

In parallel I would also suggest to come on the chat on gitter, or join our meetings to start some discussions. I'd love to know what is this tenants filter that you mention in WP, or the features from ABP that would be missing in Orchard.

**Comment by jeffolmstead** [comment]
@papyr there is a pretty good discussion going right now about commerce [over here](https://github.com/OrchardCMS/OrchardCore.Commerce), join in.

**Comment by Jetski5822** [comment]
Wow - that new?

**Comment by weedkiller** [comment]
1. Scaffolder with UI (include checkboxes for optional components as we build widgets/modules)
2. 2 simple Diagrams 1) Developer building modules for [e.g.](url![image](https://user-images.githubusercontent.com/21086190/47586592-ab45c700-d92e-11e8-8158-3ddd89ba1a19.png)
& 2) Editor creating pages/content on what can be composed and how it can be reused. I also think this is a very powerful part of Orchard thats not understood well.
5. Tenants - with audit filters, projects, 
6. inplace updates & rollback
7. On the left you will see some features [here](https://aspnetboilerplate.com/Pages/Documents)
8. Jetpack like spam protection
9. Yeost like publication
10. Wordfence Engine like threat protection DDOS, Spam, Bruteforce rules

I will come over there and add more

**Comment by jeffolmstead** [comment]
> Wow - that new?

@Jetski5822 Quite new, in planning stage at the moment, contribute away!

**Comment by bleroy** [comment]
It's both new and old :) We are building a new Core commerce platform from a clean slate, but we have a massive amount of code and experience to pull from (Nwazet.Commerce).

**Comment by papyr** [comment]
hi any update on this

**Comment by bleroy** [comment]
You can always check out the repository: https://github.com/OrchardCMS/OrchardCore.Commerce

**Comment by papyr** [comment]
thanks
