### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by zmarsel1** [OrchardCMS/OrchardCore#2577]
i cannot build orchardcore from master branch. same problem when using nuget package OrchardCore.Application.Cms.Targets

error:
The type 'RazorViewAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by psijkof** [comment]
Try the dev branch?

**Comment by Skrypt** [comment]
Please fix your csprof file to target 2.1.3 on all your themes and modules this will fix the issue. You are trying to use 2 different versions of the .NET Core framework.
