### ISSUE TITLE
Problem in create new theme

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#2585]
i create new project add generate new them by code dotnet new octheme -n "ThemeName.OrchardCore" .
and then i add the theme project to my solution.

![solution](https://user-images.githubusercontent.com/24512878/47606311-698e4c80-da12-11e8-8f19-079b11e8efc7.JPG)

after running project, i got this error:
An error occurred while starting the application.
FileNotFoundException: Could not load file or assembly 'OrchardCore.Modules.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
System.ModuleHandle.ResolveType(RuntimeModule module, int typeToken, IntPtr* typeInstArgs, int typeInstCount, IntPtr* methodInstArgs, int methodInstCount, ObjectHandleOnStack type)

FileNotFoundException: Could not load file or assembly 'OrchardCore.Modules.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by Skrypt** [comment]
Make sure you are using Beta-4-* on every dependency. Clear nuget cache, clean the solution and rebuild

**Comment by aghili371** [comment]
> Make sure you are using Beta-4-* on every dependency. Clear nuget cache, clean the solution and rebuild

where i can find this references? beta-2-* is leats version in nuget update.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/47606785-9bd58500-d9e5-11e8-9958-050b38f8ecef.png)

**Comment by aghili371** [comment]
thank you it works fine for me.i changed theme references to beta-3.* 

    <PackageReference Include="OrchardCore.Theme.Targets" Version="1.0.0-beta3-*" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="1.0.0-beta3-*" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="1.0.0-beta3-*" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="1.0.0-beta3-*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
