### ISSUE TITLE
Theme deployment problem

### ISSUE THREAD

**Issue by dschmid** [OrchardCMS/OrchardCore#2589]
I created a OC project and a OC theme within VisualStudio. Published self-contained site to a host. Setting up the site as usual and then changing the Theme to the new Theme returns a http 500 error. I don't have any more information.
I then tried to do it with the command line tools, created occsms and octheme projects and deployed the self-contained site again. Changing the Theme works now.
So:

- what is wrong?
- why does the command-line tool create a recipe?

I think, the beauty of OC theming was the simplicity creating them in VisualStudio. I really will miss that if it's gone.

**Comment by Skrypt** [comment]
I think the thing missing with command line tool is adding the theme automatically to the Orchard.Cms.Web csproj

**Comment by dschmid** [comment]
Automizing this step would not be feasable, I guess. It would not make much sense. Maybe a new template that creates both, the main and the module/theme projects would be able to automate this. But would make Things more complicated and not solve much.

My concern is that until a few days ago it was possible to create very simple projects in VisualStudio. With very small changes they could be turned into a OC cms and OC theme project.
Aparently things turned to be more complicated.

---
Daniel SCHMID
Hauptstrasse 43
5027 Herznach
Schweiz
Tel: +41 62 878 20 16
Mobile: +41 79 232 16 60
www: dschmid.ch

________________________________
Von: Jasmin Savard <notifications@github.com>
Gesendet: Sunday, October 28, 2018 5:38:02 PM
An: OrchardCMS/OrchardCore
Cc: dschmid; Author
Betreff: Re: [OrchardCMS/OrchardCore] Theme deployment problem (#2589)


I think the thing missing with command line tool is adding the theme automatically to the Orchard.Cms.Web csproj

**Comment by Skrypt** [comment]
I've not looked into it yet ; but it's supposed to be feasable. @agriffard

**Comment by sebastienros** [comment]
Not to OrchardCore.Cms.Web but maybe added to your web project

**Comment by Skrypt** [comment]
Yes I confirm that. Confusion is that my own "custom" web project is Orchard.Cms.Web.csproj too ; of course not referencing anything that is related to source code since it would be different procedure to make it work.

**Comment by Piedone** [comment]
With the `dotnet` CLI commands now being there for everything, hopefully today it's much clearer how the commands work. And they shouldn't try to do more. If you want to generate a solution too, see https://github.com/Lombiq/Utility-Scripts/blob/dev/OrchardCore/Initialize-OrchardCoreSolution/Initialize-OrchardCoreSolution.psm1.
