### ISSUE TITLE
Liquid Script Not Rendering without at:"Foot"

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#2598]
When using the liquid script notation as seen here:

```
{% script name:"jquery", use_cdn:"true", at:"Foot" %}
```

Everything works fine. But if you do not include the 'at:"Foot" then no script is rendered. 

```
{% script name:"jquery", use_cdn:"true" %}
```

My belief is that it would render still at the location it exists in the liquid file. 

Please note, it also will not render on a local script such as this:

```
{% script source: "/My-Theme/js/my-script.js" %}
```

**Comment by Skrypt** [comment]
Somehow if you don't need to be rendered somewhere else... but yes it should work since we have options on those tags like the use_cdn and also it should use a minified version on prod only.

**Comment by Skrypt** [comment]
You can close if it's fixed.
