### ISSUE TITLE
Question: Orchard CMS + Custom module with data access

### ISSUE THREAD

**Issue by brikibsw** [OrchardCMS/OrchardCore#2599]
How can one make a custom module with using OrchardCore data access. I have to build a something like Meetup but also need cms.

Is it possible, or will i have to make my own ef context for custom module?.

**Comment by MatthijsKrempel** [comment]
Yes it is entirely possible, there is no requirement that you must use yessql.

**Comment by brikibsw** [comment]
@Skrypt @MatthijsKrempel  Thank's for the answer, and I have another one :)
Is there any documentation for creating custom module with custom data to store ( EF or YesSQL ) ??

**Comment by MatthijsKrempel** [comment]
@brikibsw not that I am aware of,.
