### ISSUE TITLE
Autoroute Patterns (1: Won't update; 2: How display field?)

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/OrchardCore#2603]
I noticed an issue with Autoroute and Patterns. I also have a question about Patterns with Fields below.

**Issue**: If you update the Pattern in the Admin (Edit Part - Autoroute), and even if you re-publish the Content Item, the Permalink will not update. This is the case whether or not you select "Allow custom path" as an option in the Edit Part - Autoroute view. 

The way I updated was to allow a custom path and then delete the old Permalink, then Publish the Content Item. This would properly update the Permalink to the new pattern.

Now, this could be by design, but I wasn't sure. If not, re-publishing should update the Permalink when you update the Pattern.

NOTE: If you edit the pattern and it doesn't return anything, the Permalink shows up blank, but in the Content Item List using the "View" link brings you to the previously saved pattern that worked. This makes sense if you mess up the pattern as it keeps the old pattern.

**Question**: Is it possible to add a Field to the Pattern? Such that if ContentTypeA has a Field named FieldA, I could apply that Field to the Pattern? I tried variations on what I saw in the documentation for Autoroute as well as some of the Liquid examples for displaying Fields, but nothing works and either this is not possible or I am getting the pattern wrong. Any suggestions?

**Comment by sebastienros** [comment]
This should work `{{ ContentItem.Content.PART.FIELD.Value | display_text | slugify }}`

Also you need to delete the permalink so it can be regenerated

**Comment by remesq** [comment]
Thanks for responding. Unfortunately, that is not working.


Given "ContentA" and "FieldA" (a Text Field), I tried the following:

`{{ ContentItem.Content.ContentAPart.FieldA.Value … }}`
`{{ ContentItem.Content.ContentA.FieldA.Value … }}`
`{{ ContentItem.Content.ContentAPart.FieldA.Text … }}`
`{{ ContentItem.Content.ContentA.FieldA.Text … }}`

None of which worked. :(

**Comment by sebastienros** [comment]
It works for me. Here is an example: 
`{{ ContentItem | display_text | slugify }}/{{ ContentItem.Content.Product.Color.Text | slugify }}`

![image](https://user-images.githubusercontent.com/1165805/49903881-62ce6400-fe1d-11e8-9cba-d1b5c525f3eb.png)

I am adding this example in the documentation.

**Comment by sebastienros** [comment]
I am also thinking we should allow for refreshing the path without having to allow for custom path. I will add a checkbox too.
