### ISSUE TITLE
Adding a user control on the AgencyTheme?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2604]
I try to add the user dropdown list to the liquid page of the AgencyTheme but it doesn't work.
However this dropdown list is available in the default theme. 

So the question is how to make this user dropdown menu available in the AgencyTheme?

Many thanks!!

**Comment by sebastienros** [comment]
You can clone the theme, and change the `layout.liquid` file to add anything you want.
