### ISSUE TITLE
 multi-level image galley

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#2605]
i need a multi-level image galley, how can I develop this in orchard core?
fo example in need to have a galley for football matches:
germany> bundesliga> byenmunich> game1 >>>list  images 
in any level i need list and i need too develop sitemap in up of page.

please if you any module or solution inform me.

**Comment by sebastienros** [comment]
What I would do:
- Create a Team content type. It can have a title, it could have a list of players, a logo, ...
- Create a Championship content type which will represent the competitions (League1, Cup, Coupe de France, ...)
- A Team has a Content Item Picker of Championships
- Create a Championships taxonomy, which will define a hierarchy of Leagues/Championship(3 levels), select the championship content type for this taxonomy.
- Create a Match content type, which has two picker fields to select the home team and guest team, and add a Media Picker field for the images.

**Comment by aghili371** [comment]
sorry , what do you mean about 'taxonomy' ? how i can do this?
