### ISSUE TITLE
Error: Menu does not render

### ISSUE THREAD

**Issue by dschmid** [OrchardCMS/OrchardCore#2606]
I created a occms and a octheme project with the commandline tool. 

within VisualStudio everything works fine.
When the Project is published, the menu doesn't get rendered. Instead the line
`<menu alias="alias:main-menu" cache-id="main-menu" cache-duration="00:05:00" cache-tag="alias:main-menu" ></menu>`
is rendered unmodified in the output.

What could be the reason for this? Where do I have to look at?
Many thanks in advance

**Comment by sebastienros** [comment]
You need to reference the tag helpers from the menu module in your view or in your view imports.

**Comment by dschmid** [comment]
I did reference it I'm quite sure. This is the content of my _ViewImports.cshtml file:

`@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
@addTagHelper *, OrchardCore.Menu
@addTagHelper *, OrchardCore.Media
`

**Comment by dschmid** [comment]
Apparently I had to reference the NuGet package OrchardCore.Menu
Thank you very much for pointing me to the right direction. Unfortunately there was no warning or error that could give me this hint
