### ISSUE TITLE
Let's Encrypt Integration

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/OrchardCore#2607]
As discussed in triage, it would be great if there was built in Let's Encrypt functionality. Ideally this would auto renew, but at a minimum it should have a button to renew. We will need to figure out a way to install the cert with only rebooting the tenant rather than the whole host.

https://github.com/aspnet/Benchmarks/blob/3b7cb361785fb1fcf0e44d46cb385483fcc1e769/src/Benchmarks/Program.cs#L281

**Comment by douwinga** [comment]
@sebastienros do you have links to what you found? Are you still thinking of supporting Azure only to start? I am not sure there will be a consistent way to install the certs on each platform.

**Comment by sebastienros** [comment]
Nothing specific to Azure. 

https://github.com/natemcmaster/LetsEncrypt

And this is the place where we can plug a custom selector to pick a certificate for each tenant, on a per requests basis. https://github.com/natemcmaster/LetsEncrypt/blob/master/src/McMaster.AspNetCore.LetsEncrypt/Internal/KestrelOptionsSetup.cs#L23

**Comment by sebastienros** [comment]
There are two ways to do it:
- Azure App Service integration where we use Azure APIs to register the certificate in the Azure portal (IIS)
- Kestrel termination, where we use a local certificate store and use the callback to select the certificate dynamically

**Comment by Piedone** [comment]
Azure provides free certificates, and you can use e.g. Cloudflare in front of any web app to get free SSL. Do we still need this?

**Comment by douwinga** [comment]
Closing as this is not needed anymore
