### ISSUE TITLE
Logo image can't display?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2611]
Try to place a logo in a custom Theme - as shown below, however the logo can't display in the website. 
What's wrong with the code? Many thanks!

`<body dir="@Orchard.CultureDir()">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container">
            <a class="logo" href="~/#">
                <img src="~/wwwroot/img/logo.jpg" />
            </a>
...................`

**Comment by sebastienros** [comment]
`src=MODULENAME/FILENAME_UNDER_WWWROOT`

For instance if you have `wwwroot/img/foo.png` your tag will be `<img src="YourTheme/img/foo.png" />`
