### ISSUE TITLE
Inactive registration page redirects to logon with return URL of 404 page

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#2612]
When you enable the feature to allow users to register, and dont go into settings and enable the setting that lets users register. Then the /register url will redirect to login to see the 404 page.

This I believe will have something to do with all login pages now being part of the admin theme for headless/no theme support?

Another point though, if you enable this feature, should the default settings be that registration is enabled? And then require email verification also enabled by default taking the "secure by default" view point??

**Comment by TFleury** [comment]
> When you enable the feature to allow users to register, and dont go into settings and enable the setting that lets users register. Then the /register url will redirect to login to see the 404 page.

It's a theme issue. You should not display registration link if setting is disabled (see #3204)

> This I believe will have something to do with all login pages now being part of the admin theme for headless/no theme support?

Done in #3218
