### ISSUE TITLE
Possible of extending the Users module with a custom module?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2614]
I have enabled the Users and User Registration module; now I'd like to write a custom module which can extend some functions, such as manage user-own documents (user can upload their documents and only visible to their own and site Administrators).

The question is how to do that in Orchard Core? 

Many thanks!

**Comment by sebastienros** [comment]
We don't have and don't intend to do such modules, but you can create these features yourself with standard MVC controllers and views. You can even reuse the existing user APIs to store the custom values in the user object (if it makes sense).

**Comment by orchardc** [comment]
Thank you for the response. My scenario is:
1. I'd like to utilize the Users module, instead of re-write it completely;
2. I'd like to extend the User module, and adding new fields for users;
3. I don't want portal users to use the Admin panel to manage their profile; instead they should use a custom MVC page to manage their profile (basic info from Users module + custom fields).

Is it possible to do s - what is your recommendation?

Many thanks in advance !
