### ISSUE TITLE
ReduceIndex for parts

### ISSUE THREAD

**Issue by sylord0803** [OrchardCMS/OrchardCore#2628]
I have a content type with a part called ExamPart which has a Date property. I'd like to creating reduce index to easily query exams in a specific week of year. I got an error when saving a content item which has no ExamPart.

Any idea to solve this issue or is my approach totally wrong?
@sebastienros 

```
    public class ExamPart : ContentPart
    {
        public DateTime Date { get; set; }
    }

    public class ExamByWeekIndex : ReduceIndex
    {
        public string YearAndWeek { get; set; }
        public int Count { get; set; }
    }

    public class ExamByWeekIndexProvider : IndexProvider<ContentItem>
    {
        public override void Describe(DescribeContext<ContentItem> context)
        {
            context.For<ExamByWeekIndex, string>()
               .Map(contentItem =>
               {
                   var part = contentItem.As<ExamPart>();
                   if (part == null)
                   {
                       return null;
                   }

                   return new ExamByWeekIndex()
                   {
                       Count = 1,
                       YearAndWeek = part.Date.Year + ";" + part.Date.GetWeekOfYear();
                   };
               })
               .Group(x => x.YearAndWeek)
               .Reduce(group => new ExamByWeekIndex()
               {
                   YearAndWeek = group.Key,
                   Count = group.Sum(x => x.Count)
               })
               .Delete((index, map) =>
               {
                   index.Count -= map.Sum(x => x.Count);
                   return index.Count > 0 ? index : null;
               });
        }
    }
```

**Comment by Skrypt** [comment]
Try this :  

```
if (part == null || part.Date != null){

}
```

I think your issue is that the part will never be null. The date though could be.

**Comment by sebastienros** [comment]
Please debug your code to see where the null ref is coming from.

**Comment by sylord0803** [comment]
DateTime is struct. It isn't nullable type.

There is no exception if the code returns a "default" value instead of null in the Map method, but I don't think this would be the best solution:

`new ExamByWeekIndex() { Count = 0, YearAndWeek = "NaN;NaN" }`

I think there is something with content items. Did anyone else try to ever create reduce index for a content part?

When I do the same without Orchard using only YesSql everything is fine.

**Comment by sylord0803** [comment]
First of all, thank you for the answers.

Everything you mentioned is true, but if you have noticed my code above the type of my property isn't DateTime? but DateTime, so its value can be never null and you can not pass a DateTime? to it. Otherwise, I tested you suggestion and I still have the exception.

The problem is the following: if a have a different content type with different parts and I publish a content item with this type then the delegate in Map() method will result null because this type doesn't have ExamPart and not because the Date is null.

**Comment by sylord0803** [comment]
I found the solution: There was necessary to return an instance instead of null and the key (YearAndWeek) can not be null. Now I set empty string for the key. In this case index is ignored.

**Comment by Skrypt** [comment]
There is still something strange as normally if the part = null it should simply return null and never need to reduce the data since there is no need. What you are doing is forcing an empty string so that it reduces nothing in the end.
