### ISSUE TITLE
Error updating packages from MyGet

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2629]
When I try to update the OC Nuget packages on MyGet, an error occured:

`The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).	`

**Comment by agriffard** [comment]
The error code NU3005 leads to this page: 
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3005?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Dfr-FR%26k%3Dk(NU3005)%26rd%3Dtrue

**Comment by sebastienros** [comment]
Maybe a transient issue with one of the packages. I merged a few PRs that should update them.

**Comment by agriffard** [comment]
I tried multiple times these last days and laways add the error with different versions.
I just tried on another project and it works though.
