### ISSUE TITLE
Replace menu tag helper with a more generic one

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2632]
We need a tag helper that would render a content item, with an optional display type and cache metadata. c.f. #2623

And it's so obvious that we might already have it and I just forgot ;)

**Comment by sebastienros** [comment]
I think I did it based on a shape to be able to cache even the loading of the content item. Such that if the shape is cached it would not try to load the menu item.

So the new tag should be able to handle cache properties, or we could also just handle it with outer cache tags, for simplicity.

**Comment by jptissot** [comment]
I will try to do this this weekend

**Comment by sebastienros** [comment]
A weekend has passed ...

**Comment by jptissot** [comment]
I did not touch a computer this weekend :) I might have some time this week :)

**Comment by jptissot** [comment]
Does this sound like what we want to do ? 
Create a liquid filter called `content_render` Usage: `{{ Content["alias:some-alias"] | content_render "detail" }}` I am not sure how to integrate caching in this one.

Create a tag helper `<content-item  alias="some-alias" />`  We could extend BaseShapeTagHelper to get the caching properties potentially ?

**Comment by sebastienros** [comment]
for the caching we don't need to do anything special, we can just rely on other existing tags for now, so don't worry about it

**Comment by jptissot** [comment]
I think we already have a tag helper 

<shape Type="ContentItem" alias="alias:my-alias" display-type="Detail" />

This worked.

**Comment by jptissot** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Shapes.cs#L43

**Comment by jptissot** [comment]
Do you think it's worth creating another Tag helper for this or documenting this usage is fine ?

**Comment by jptissot** [comment]
Like you mentionned, we could leverage the [Cache Tag Helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/cache-tag-helper?view=aspnetcore-2.2) for caching the TagHelper contents. 

It would be beneficial to add caching to the liquid filter though.

**Comment by jptissot** [comment]
Well, this worked as well: 

```   
{% shape "ContentItem", alias: "alias:my-alias", cache_id: "my-alias", cache_fixed_duration: "00:05:00", cache_tag: "alias:my-alias" %}
```

**Comment by jtkech** [comment]
And that's what we use for the menu itself in the blog theme liquid layout.

    {% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", ... %}

Hmm, i think here we could also use something like this `{% helper "menu, alias :..."`

**Comment by sebastienros** [comment]
Tell me that I made this content item shape already ;) and I just didn't remember ... Oh my

**Comment by sebastienros** [comment]
So maybe have the same in liquid (without the tag helper bridge) and reuse the same code if possible by externalizing it

**Comment by jptissot** [comment]
Ok will do. And will also document it ;)

**Comment by sebastienros** [comment]
We might need to think on how to get a culture content item too. That might incur some changes in the format of the filter. Maybe we'll need to make it extensible. But I assume we already have a service to retrieve a content item with a specific culture, and we can use its id then. Though ideally we should be able to set `alias:foo` and `culture:fr`. So maybe a small interface to resolve these segments and return a content item id might be useful.

**Comment by sebastienros** [comment]
My previous comment is based on how people will deal with the menu when building a multi-lingual website, and need different menus

**Comment by jptissot** [comment]
I am not sure I understand why we would need something special for cultures in this case. The aliases will need to be unique and the convention is specific to each project. 
My convention is to add -{culture.name} to the alias. Currently doing this in our liquid templates: 
```
{% assign brand_alias = "alias:brand-" | append: Culture.Name %}
{% shape "ContentItem", alias: brand_alias %}
```
My Brand content type does not have a Localization Part.. maybe that is considered a hack and maybe i should not even be using alias in this case. 

Maybe we need alias to behave differently when used on a ContentItem that has a localization part ?

**Comment by sebastienros** [comment]
`{% contentitem "alias:main-menu" cache-id: "main-menu" %}`

`<contentitem alias="alias:main-menu" cache-id="main-menu" />`

**Comment by sebastienros** [comment]
As a matter of fact we can't remove the menu shape right now and replace it with a simple contentitem one, as the menu shape also adds useful alternates for menu and menu items to ease the theming. Not sure though if there is a guide to customize the theme for this specific one.
