### ISSUE TITLE
Adding a custom js file to a custom module doesn't work?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2641]
I have a custom module and I try to add a js file within this module; so I created a folder call "Content" of the root of the module project, then put js in it. 

Reference the js in a MVC view: <script src="/MyModule/Content/my.js"></script>
But it doesn't work. 

Anything wrong with the reference?

Many thanks!

**Comment by sebastienros** [comment]
Static files are only served from a `wwwroot` folder, unless you decide to add your custom static files middleware for other folders.
