### ISSUE TITLE
RAD tool needed for Orchard Core

### ISSUE THREAD

**Issue by papyr** [OrchardCMS/OrchardCore#2644]
Hello, this would really help drive adoption of orchard core with a RAD tool!!

I believe there is a scaffolder already, it would be really great if we could get a scaffolder with a GUI, to start it could just be entities, and then expand over to Widgets/Plugins

Please see [this reference on RAD tool](https://www.youtube.com/watch?v=lqu7AVBTepw) to quickly build-up entities (and plugins now)

**Comment by Skrypt** [comment]
I like the idea. This should be using CLI for configuring different parts of the settings or content types/parts.

**Comment by sebastienros** [comment]
I am not sure we need any scaffolder like this, everything is dynamic (not code generated) and we can already do what you just showed, only from the web app directly. What could it generate?

**Comment by papyr** [comment]
Can you re-open this, it would really help speed up use and development, Please see the link above.

Orchardidezer does not work anymore

**Comment by Skrypt** [comment]
We have dotnet new templates for this now. We would need to add options or you could create your own dotnet new templates ...

**Comment by papyr** [comment]
Thanks for helping me understand whats the missing part.

I have seen more people adapt some of those frameworks simply because it allowed them to start with low/0 learning curve - following which they would add/update and learn.

I have been a strong proponent of Orchard, **unfortunately we could not even get one developer to join my team to help.** So, my manager completely abandoned Orchard.

As time progresses it will fall behind if Orchard Tooling/Features don't adapt!

**Comment by Skrypt** [comment]
Well, we need to first ship a version 1.0. These kinds of tools are generally contributions from community. Somehow we are still developping the framework so it doesn't make much sense pushing much work on this right now. I think dotnet new is the key here. One thing though that I liked in that video is the ability to run db migrations in a command shell. Migrations in OC are done in OrchardCore.Data.Migration, so this tool could use what is in there and execute the migration from a command shell. There's a lot of good ideas in there.
