### ISSUE TITLE
Lucene error when files are not found

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2645]
When doing git clean -xdf on a website that has the Lucene module enabled ; it will delete all the Lucene files in the App_Data folder of all websites. Rebuilding the indexes fixes the issue but we should be able to handle this error more gracefully ... for 🦄 and ⛄️... 😄

**Comment by sebastienros** [comment]
Are you actually deleting an App_data folder while running the site?

**Comment by Skrypt** [comment]
No just the App_Data/Lucene folder as I thought those files should never be included in my repository.

**Comment by sebastienros** [comment]
Just stop the server then first, it's used by the app, you should not delete it while it running
