### ISSUE TITLE
Adding Liquid Widget in Flow Causes Empty Page Title Elements

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#2650]
Replicate:

1. Use any of the existing Themes (i.e. Agency, Blog, etc.)
2. Create a page with a Flow
3. Add in multiple "Liquid" widgets with some content and publish page
4. View page and you will see there are empty spots (separated by your "separator" of choice, typically "-") in the page title

I have not pinned down where this is coming from yet, just reporting it. Let me know if you know where this is coming from.

**Comment by jeffolmstead** [comment]
**Alternate approach to the above method**, could also alter:

\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Title\PageTitleBuilder.cs

to change the AddSegment method to not any empty "titlePart" if it is a change that should be made globally:

```
            if (!string.IsNullOrWhiteSpace(titlePart.ToString()))
            {
                _title = null;

                _titleParts.Add(new PositionalTitlePart
                {
                    Value = titlePart,
                    Position = position
                });
            }
```
I feel this would be the better way (note I didn't test this but seems like it would work out right).

**Comment by sebastienros** [comment]
Still an issue?

**Comment by jeffolmstead** [comment]
Yes, no fix has been applied that I have noticed.
