### ISSUE TITLE
Order is not preserved when returning documents from SQL query

### ISSUE THREAD

**Issue by jameshawkins** [OrchardCMS/OrchardCore#2651]
When checking the option to return documents from a SQL query, the documents returned are not in the same order as the document ids returned from the query.

This is because the SQL that is generated is something like `SELECT * FROM Document WHERE [Id] IN @Ids` which appears to return the rows in ascending order by Id (tested with SQL Server and SQLite).

This appears to be the real cause of #2382 and also effects getting content items by a list of content item ids.

**Comment by sebastienros** [comment]
I disagree with the related issue, because it was really what I fixed in YesSql ;) But welcome back! We missed you.

**Comment by jameshawkins** [comment]
Thanks :)
