### ISSUE TITLE
Permissions.cs in custom Module

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/OrchardCore#2654]
I'm probably making a sub-rookie mistake. I cannot see my custom permissions on the Admin dashboard.

I created a `Permissions.cs` file (copied from an existing OC file).

I added the `services.AddScoped<IPermissionProvider, Permissions>();` in my module's `Starup.cs` file. Again, I saw this in an OC module, thought it was the problem initially.

I added the module as a project reference in my WebApp.

I enabled the module in the Admin.

I have not seen anything after searching around as to whether or not Permissions were not working/implemented yet.

What am I missing? Many thanks in advance.

**Comment by zl2fxy** [comment]
ReBuild OrchardCore.  App_data will record Permission if it has somethings before

**Comment by Skrypt** [comment]
I think it's not yet implemented. Everything related to permissions might have things not yet completely implemented.

**Comment by sebastienros** [comment]
It works just fine. In settings, security, roles.

**Comment by sebastienros** [comment]
Please provide some repro steps if you still experience the issue

**Comment by remesq** [comment]
The steps I outlined above for creating the Permissions seem to work BUT ONLY on a newly spun up site.

In other words, enabling the module in an existing site doesn't seem to populate the Permissions in Settings > Security > Roles. In my case, the module already existed and was already enabled but then AFTER I created the Permissions.cs file and it would not add the new roles.

But on a new site, when I enable the module it works.

My take is that on an existing module, if you then add Permissions.cs it does not seem to add the new roles, but on a module that is created with Permissions.cs and THEN enabled on the site it adds the roles. If that makes sense?

**Comment by sebastienros** [comment]
Makes sense now, that's known issue, it's also like this in O1.

Maybe we can handle that with migrations, by calling the service that registers the default permissions for each role.

**Comment by Piedone** [comment]
Slightly off: @Skrypt this is the reason why there's no AccessFrontend permission and dynamic content type permissions either (and content item permissions)?

**Comment by Skrypt** [comment]
Yes, as you can see here the DynamicPermission.cs file code has been commented out for now : 
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/DynamicPermissions.cs

And there's a branch I started working on for content item permissions has reported here : https://github.com/OrchardCMS/OrchardCore/issues/1091

**Comment by Piedone** [comment]
I see, thanks. Is the lack of AccessFrontend a design decision, or just not yet implemented? Can't find any issue or discussion about it.

**Comment by Skrypt** [comment]
Probably just missing but I think the entire feature would be worth having discussions about it with @sebastienros to relevate details that could be enhancements over what we had in 01.

**Comment by sondli** [comment]
> Makes sense now, that's known issue, it's also like this in O1.
> 
> Maybe we can handle that with migrations, by calling the service that registers the default permissions for each role.

Are migrations still the best way to handle this issue?
