### ISSUE TITLE
how generate  url and set meta keywords

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#2662]
i want to call group from landing pageand show group information in new page, how can i generate the url?      <a  href="{{ MasterGroup.display_url }}">

and how can i set meta tags?

![goup](https://user-images.githubusercontent.com/24512878/48316752-0c84c000-e5e8-11e8-80e5-5d2d46ee50e0.JPG)
```

   {% for MasterGroup in Model.ContentItem.Content.MasterGroups.ContentItems %} 
			  <div class="col-sm-4">
                <div class="groupitem">
                    <img class="mx-auto rounded-circle" src="{{ MasterGroup.MasterGroup.Image.Paths.first | asset_url | resize_url: width:240, height: 240, mode: 'stretch' }}" alt="">
                  <a  href="{{ MasterGroup.display_url }}">  <h4>{{ MasterGroup.DisplayText }}</h4> </a>
				 
                </div>
            </div>
		 
            {% endfor %}

```

**Comment by Skrypt** [comment]
The Autoroute is what will generate your url. 
https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Autoroute/README/
You can use Liquid in the Autoroute settings of your content type. There is no current content parts for META tags or keywords. Maybe a contribution module could add this feature eventually.

Else, I need to read more carefully what you just sent to understand the subtleties of what you are trying to achieve.

**Comment by aghili371** [comment]
in landing page i want to open project info in a new page, currently, it opens in module box. 
i have read this document but I can't use that.

**Comment by Skrypt** [comment]
You should use a content picker then instead of a Flow part (bagPart). Also you will need to add an AutoroutePart to your "Project" content type to generate it's url's.

**Comment by Skrypt** [comment]
Ok there's a bug I just tried what I said there and it's not working even if I add the autoroute part to a Project content type. The isssue I think is that since it's in a Bagpart it's not creating any Alias.

**Comment by aghili371** [comment]
why you don't have tutorials? it's difficult to do new things in this CMS.

i want to access to autoroute , how i should set the href?

i create new content 'mastergoup' and i added this section to the landing page. i need to have a link in landing page when i click that going to new page and show the mastergoup information. 

` {% for MasterGroup in Model.ContentItem.Content.MasterGroups.ContentItems %}  
                  <a  href="{{ my poblem }}">  <h4>{{ MasterGroup.DisplayText }}</h4> </a>
 {% endfor %}`

**Comment by Skrypt** [comment]
Well, what you did is fine, though I think there is a bug so I'm sorry for the inconvenience ; maybe you could submit a pull request that fixes the issue, else we will discuss about it in the next triage.

**Comment by aghili371** [comment]
i think it not difficult, just i don't know the orchard structure to get data from the autoroute

**Comment by sebastienros** [comment]
This is not supported yet. You can only point the the main content item. A solution would be to change the main content item template to take a query string argument containing the identifier of the bag part item you want to read, then in the template, seek this bag part item and render it individually.

**Comment by sebastienros** [comment]
I filed this bug instead https://github.com/OrchardCMS/OrchardCore/issues/2688
