### ISSUE TITLE
Stacking context usage and z-index clashes

### ISSUE THREAD

**Issue by aodl** [OrchardCMS/OrchardCore#2663]
Relates to #2591 

## Issue Context

I've come across another case similar to to #2590, where a template for a content part contains elements with high z-indexes but it does not wrap them inside a [stacking context](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) element that has `z-index: auto`.

This causes z-index clashes like the following:

![image](https://user-images.githubusercontent.com/14985227/48317127-82d3f300-e5e5-11e8-9333-4c17df51696c.png)

![image](https://user-images.githubusercontent.com/14985227/48317131-98e1b380-e5e5-11e8-9aec-aa25d1c028c0.png)

In this particular case the flow part template sets a higher than default z-index for the checked radio buttons. This is fine in context of the template by itself, but it doesn't take into account the fact that this template (template **A**) will sit on a page that may have other another template (**B**) with high z-index elements that are required to 'pop over' or 'drop down' over template **A** while in use.

In the images above, 'template B' is the content picker part, which has a dropdown element that should really be displayed above the flow part radio buttons. *(Actually in this case template B is actually rendered inside template A, because that's what the flow part does, but you get the point)*

## Underlying Problem

Solving particular cases of this problem is relatively simple (setting the dropdown z-index higher, or radio button z-index lower), but really this is just moving the issue around and it's not a permanent solution to the underlying problem -  that **orchard templates need to avoid z-index clashes with other templates that it doesn't know about in advance**.

The only reasonable way of achieving this seems to be to get templates that have high z-index elements (that are always on display), to wrap all of the relevant template contents in their own stacking context.

This blog post gives a really good summary of [z-index stacking contexts](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/)

So if a parent element in the flow part template either had:
 - `Position: relative`
- or `Opacity: 0.9999`

... then the radio button z-index would continue to function as it currently does inside the parent element (for whatever the original reason was that it was given that specific z-index in the first place), but it will be treated outside the context of the parent element as though it has a z-index of 'auto' (so long as the parent element has `z-index: auto`), and therefore dropdowns and popovers will happily be displayed on top.

## Solutions?

Rather than altering the flow part template directly, perhaps there is a more permanent fix that can solve this issue in other places where it may not have been noticed yet, and also avoid this issue from cropping up in the future, by solving the **underlying problem**.

- Maybe something like I'm a template wrapper that gives all individual templates their own stacking context by default *(probably a bad idea as might cause certain templates to break for other reasons)*...
- Maybe a test suite that renders each template on a test page, asserting that `<div style='position:absolute; top: 0; bottom; 0; left: 0; right: 0; z-index: 1;'></div>` successfully obscures (is rendered on top of) the template in question *(probably more trouble that it's worth)*
- Maybe just some documentation / coding guidelines for this scenario

Could do with some brain storming... Or maybe this is all overkill and I've drank too much coffee today?

**Comment by Skrypt** [comment]
Why not just setting a z-index that is higher starting from top to bottom widgets. For the controls themselves they woud just need to inherit their parent.

**Comment by aodl** [comment]
That sounds like a flow part specific fix (which is good, but would be great if could solve the problem in all cases - but maybe not possible). 

Also Bootstrap popover's sometimes extend upward rather than downward (I think bootstrap tooltips go upward by default).

**Comment by matiasmolleja** [comment]
There is a known issue with z-index of vue multiselect:
https://github.com/shentao/vue-multiselect/issues/662

I fixed that thing only. 
@aodl  I understand your point. But I think that maybe we can try to avoid z-index issues the easy way and resort to more complex things only when we see we have more issues of this kind. 

I think that if we stick to the [z-index](https://getbootstrap.com/docs/4.1/layout/overview/#z-index) defaults that Bootstrap recommends maybe we don't need that.
