### ISSUE TITLE
Nested MenuItem.Level is always 0

### ISSUE THREAD

**Issue by bridgesquared** [OrchardCMS/OrchardCore#2671]
Hi, I've been looking at building a corporate theme for Orchard Core and I've been trying to get menus working properly with Bootstrap 4.

I tried using different templates for different levels as detailed in MenuItem Alternates but it wasn't working.

I've tracked the issue to:

https://github.com/OrchardCMS/OrchardCore/blob/5744fafe9636149ca75ef3549d9d331f0dd79337/src/OrchardCore.Modules/OrchardCore.Menu/MenuShapes.cs#L108-L114

The error is that the Level property is being set to `Level = 0` for all levels of menu item, instead of using `Level = level +1` and thereby incrementing the level each time the code handles a new level, which prevents us rendering the Level 1 menu items differently from the Level 0 items.

I can put together a PR to cover this, but can't work out where, or even how, I should write an appropriate test. Any thoughts would be gratefully received. Thanks.

**Comment by sebastienros** [comment]
It seems you are right. Please submit a PR fix the fix, and test it on your site, if it fixes your issue and the fix seems legitimate then that's fine.

We could do a functional test that renders a menu with many levels and their Level property to be sure it has the correct value. But it's too much work for now, I prefer you just validate it locally.

**Comment by sebastienros** [comment]
Did you delete the PR you created?
