### ISSUE TITLE
How to properly index custom Content Types?

### ISSUE THREAD

**Issue by andreflourenco** [OrchardCMS/OrchardCore#2675]
I've created pages with custom Content Types but cannot query them by their content with Lucene queries. The queries work only with the standard parts like TitlePart and AutoroutePart. 

Here's the structure of one of the custom Content Types - DetailPageColumns:

```json
{
	"DetailPageColumns": {},
	"TitlePart":
	{
		"Title": "<hidden>"
	},
	"AutoroutePart":
	{
		"Path": "<hidden>",
		"SetHomepage": false
	},
	"Paragraphs":
	{
		"ContentItems": [
			{
				"Id": 0,
				"ContentItemId": "4nasbz47wb20jww2fvy3esztdy",
				"ContentItemVersionId": null,
				"ContentType": "Paragraph",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.6911589Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"Paragraph":
				{
					"Content":
					{
						"Html": "<hidden>"
					}
				}
			}
		]
	},
	"Banners":
	{
		"ContentItems": [
			{
				"Id": 0,
				"ContentItemId": "4f634bxts49mc5736hmq13bmdq",
				"ContentItemVersionId": null,
				"ContentType": "BannerInfo",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.6923145Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"BannerInfo":
				{
					"SubTitle":
					{
						"Text": "<hidden>"
					},
					"ButtonUrl":
					{
						"Text": "<hidden>"
					},
					"ButtonText":
					{
						"Text": "<hidden>"
					},
					"ButtonOpeninnewwindow":
					{
						"Value": false
					}
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			}
		]
	},
	"SideBarBanners":
	{
		"ContentItems": [
			{
				"Id": 0,
				"ContentItemId": "4q95n2w29bns62ntzvea1a7c4z",
				"ContentItemVersionId": null,
				"ContentType": "BannerInfo",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.6952736Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"BannerInfo":
				{
					"SubTitle":
					{
						"Text": "<hidden>"
					},
					"ButtonUrl":
					{
						"Text": null
					},
					"ButtonText":
					{
						"Text": "<hidden>"
					},
					"ButtonOpeninnewwindow":
					{
						"Value": false
					}
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			},
			{
				"Id": 0,
				"ContentItemId": "46yfzmbyxqncds1vn37zagam51",
				"ContentItemVersionId": null,
				"ContentType": "BannerInfo",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.6996313Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"BannerInfo":
				{
					"SubTitle":
					{
						"Text": "<hidden>"
					},
					"ButtonUrl":
					{
						"Text": "<hidden>"
					},
					"ButtonText":
					{
						"Text": "<hidden>"
					},
					"ButtonOpeninnewwindow":
					{
						"Value": false
					}
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			},
			{
				"Id": 0,
				"ContentItemId": "4jw3757k5e3q3r1c4sb5fww4wy",
				"ContentItemVersionId": null,
				"ContentType": "BannerInfo",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.7021901Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"BannerInfo":
				{
					"SubTitle":
					{
						"Text": "<hidden>"
					},
					"ButtonUrl":
					{
						"Text": "<hidden>"
					},
					"ButtonText":
					{
						"Text": "<hidden>"
					},
					"ButtonOpeninnewwindow":
					{
						"Value": false
					}
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			}
		]
	},
	"FAQ":
	{
		"ContentItems": [
			{
				"Id": 0,
				"ContentItemId": "4kfc4493vgybfzbz5hdy9ggzny",
				"ContentItemVersionId": null,
				"ContentType": "Question",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.7056468Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"Question": {},
				"HtmlBodyPart":
				{
					"Html": "<hidden>"
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			},
			{
				"Id": 0,
				"ContentItemId": "4tps2b5ycq5gzy5yfagn7wzqmt",
				"ContentItemVersionId": null,
				"ContentType": "Question",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.7068827Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"Question": {},
				"HtmlBodyPart":
				{
					"Html": "<hidden>"
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			},
			{
				"Id": 0,
				"ContentItemId": "4j92364cc3qdh6wd9se027pnw1",
				"ContentItemVersionId": null,
				"ContentType": "Question",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.7081653Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"Question": {},
				"HtmlBodyPart":
				{
					"Html": "<hidden>"
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			},
			{
				"Id": 0,
				"ContentItemId": "4099gxg4d8az0y96n9shepe2xy",
				"ContentItemVersionId": null,
				"ContentType": "Question",
				"Latest": false,
				"Published": false,
				"ModifiedUtc": "2018-11-13T13:38:55.7093002Z",
				"PublishedUtc": null,
				"CreatedUtc": null,
				"Owner": null,
				"Author": "admin",
				"Question": {},
				"HtmlBodyPart":
				{
					"Html": "<hidden>"
				},
				"TitlePart":
				{
					"Title": "<hidden>"
				}
			}
		]
	}
}
```

I'd like to be able to search the Paragraphs content, BannerInfos subtitle and FAQs HtmlBodyPart.

**Comment by sebastienros** [comment]
Have you looked in the Content Type settings, where you can change in which index they are added?

**Comment by andreflourenco** [comment]
Hi Sebastien, I wasn't aware of that option but found it after your comment. 

You are referring to the "Include this element index (Check to include the value of this element in the index.)" checkbox, right?

I have selected the options Stored and Analyzed for fields that do not contain markdown/html and Stored, Analyzed and Sanitized for fields that contain.

Tried resetting, rebuilding the index and publishing all pages again, but it seems no new information was added to the index (I'm viewing the index structure with Luke 5.3.0).

In which index fields should I be seeing the new information?

**Comment by andreflourenco** [comment]
Hello @Skrypt , I did use the import/export but I don't think that's the problem, because I have republished all of my pages after the import. 

All pages are indexed, what I cannot find in the index are the custom fields and content types I have created, even after checking the "Include in index option" as mentioned in the last comment.

Luke 5.3.0, shows only the following fields in my index:

LiquidPart
Content.ContentItemMetadata.DisplayText.Analyzed
Content.ContentItem.ContentItemVersionId
Content.ContentItem.ModifiedUtc
TitlePart
Content.ContentItem.ContentItemId
Content.ContentItem.CreatedUtc
Content.ContentItemMetadata.DisplayText
ContentItemId
Content.ContentItem.PublishedUtc
AutoroutePart
Content.ContentItem.ContentType
Content.ContentItem.Owner
AliasPart
Content.ContentItem.Author
Content.ContentItem.Latest
Content.ContentItem.Published

**Comment by Skrypt** [comment]
Have you tried the option "store" on the index ; to store the values in the index?

**Comment by sebastienros** [comment]
Store has nothing to do with whether it's indexed or not. But when it's indexed, it will also store the original value for later usage in search results.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/48720128-0ba5ec80-ebed-11e8-9dee-945997dcb841.png)
Here is the result I get with Luke 5.5.0 after going to set the indexation on the Service BagPart on a LandingPage from TheAgencyTheme.

**Comment by Skrypt** [comment]
Ok, my first guess right now is that it may be due to the changes we made last week on BagParts for GraphQL since it was working. @jtkech

**Comment by hswami** [comment]
The "Include in index" has to happen on multiple levels - the individual field, the bag part, the content type/part containing the bag part, and so on until you reach the very top. If that has been done, then it deserves investigation.

**Comment by andreflourenco** [comment]
@hswami I believe the "Include index" option is selected throughout the content type structure. 

Here's a link to the structure of one of the custom content types and the corresponding index with Luke 5.3.0: 
![detailpagecolumns](https://user-images.githubusercontent.com/5647325/48733167-eb941e80-ec28-11e8-9914-ab90c0cab1ae.png)

**Comment by sebastienros** [comment]
Best issue repro ever!

**Comment by hswami** [comment]
So here are some debugging tips.

1. Place a breakpoint inside `BagPartIndexHandler.BuildIndexAsync()` (in `src\OrchardCore.Modules\OrchardCore.Flows\Indexing\BagPartIndexHandler.cs` and see if that breakpoint is reached if you republish an item (just hitting the **Publish** button again should do it).
2. If that breakpoint doesn't hit, place on the next method up the chain: `ContentPartIndexHandler<T>.BuildIndexAsync()` (in `src\OrchardCore\OrchardCore.Indexing.Abstractions\ContentPartIndexHandler.cs`) - this one is an explicit interface impl.
3. Next up the chain would be `ContentItemIndexCoordinator.BuildIndexAsync()` (in `src\OrchardCore.Modules\OrchardCore.Contents\Indexing\ContentItemIndexCoordinator.cs`)

Let me know what you find.

**Comment by andreflourenco** [comment]
I've just tested this with the latest code from the dev branch and it seems to be working, Luke shows new fields like: Paragraphs.Paragraph.Content, FAQ.Question.HtmlBodyPart...

My previous tests were with Beta2-67846 release since I'm using Orchard with NuGet packages. Tried the new Beta2-69590 that was released a few days ago too but did not work either. 

Which version should I be using? Is there any other package source with newer releases?

**Comment by sebastienros** [comment]
That makes sense. Use the beta3 ones which are available on myget (it's documented i assume) and corresponds to the dev branch.

**Comment by Skrypt** [comment]
I personnally was on latest dev branch when I tested this.

**Comment by hswami** [comment]
Any results from the debugging tips I provided? Do the breakpoints hit when run in debug mode? I would recommend starting with the OC code repo, re-creating your content types and content (you could import them in as a package), and then debugging. This way, it will eliminate some things. Also, in your site setup, ensure that you have the OC indexing features enabled.
