### ISSUE TITLE
GraphiQL History Label Doesn't Appear Immediately

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#2683]
Learning a few of the GraphiQL features and noticed that when I add a label to a history item the label does not appear immediately. However, if I navigate to another menu item in the Dashboard and then back to GraphiQL and view the history the label appears.

Tried this in both Safari and Chrome with the same results.

**Comment by jrestall** [comment]
Best to raise this issue against graphiql https://github.com/graphql/graphiql/issues and then once fixed we can update the referenced library.

**Comment by sebastienros** [comment]
I will trust @jrestall and say it's a GraphiQL bug, so I close it.
