### ISSUE TITLE
Change to relative hrefs instead of absolute

### ISSUE THREAD

**Issue by inhumator** [OrchardCMS/OrchardCore#2695]
HREFs like

```
<link type="image/x-icon" rel="shortcut icon" href="/TheAdmin/favicon.ico" /> 
<link rel="stylesheet" href="/TheAdmin/Styles/TheAdmin.css">
<script type="text/javascript" src="/TheAdmin/Scripts/userPreferencesLoader.js"></script>
```

and at least 70 other instances don't work if Orchard is deployed in a sub-folder (like "https://host.com/Orchard") and not the root folder.

**Comment by sebastienros** [comment]
The issue is that these resources can be added from any location, so we have to generate absolute urls for static assets.

But we could provide a solution with a custom setting that would be added to the tenant settings, and added to the `Request.PathBase` in addition to the url prefix.
