### ISSUE TITLE
What I'm doing wrong with Orchard Core?

### ISSUE THREAD

**Issue by lurumad** [OrchardCMS/OrchardCore#2696]
Hi folks,

I'm a newbie with Orchard Core and I've tried to create my first Orchard Core Framework playground, it's working but I cant's see the layout page:

![image](https://user-images.githubusercontent.com/1729519/48623971-939cb400-e9ab-11e8-8bce-08a79e57bdcb.png)

What I'm doing wrong?

[Playgrounds.zip](https://github.com/OrchardCMS/OrchardCore/files/2589424/Playgrounds.zip)

I've attach the solution.

Regards!

**Comment by Skrypt** [comment]
First you should read : https://orchardcore.readthedocs.io/en/latest/Templates/README/  

Or look in that folder to see how the default templates are made : 
https://github.com/OrchardCMS/OrchardCore/tree/dev/src/Templates/OrchardCore.Cms.Templates

**Comment by Skrypt** [comment]
Here is the solution working : 
[Playgrounds.zip](https://github.com/OrchardCMS/OrchardCore/files/2590876/Playgrounds.zip)
