### ISSUE TITLE
Package Import not Working

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#2698]
I am working on a new theme.  So I exported some content types in a Blog Tenant (TheBlogTheme) like in #2558:
Article | Liquid Page | Blog Post | Blog | Container | Blockquote | Liquid | Page.

Downloaded the deployment file and navigated to the default tenant(TheNewTheme) and tried to import the deployment file and it said it imported it successfully, but the content types were not there.   I was able to copy what was exported into TheNewTheme recipie.    I thought the import process would be more convenient but I couldn't get it to do anything.

**Comment by sebastienros** [comment]
Repro steps? (what you did, what you saw, what you expected to see). As simple as possible.

Many you should have also exported the content definitions?

**Comment by sebastienros** [comment]
Without the type definition, a content item won't be displayed.
