### ISSUE TITLE
scrolling in media module

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#2702]
in select media if we have some files, the scroll doesn't appear.
![mediascoll](https://user-images.githubusercontent.com/24512878/48659305-378b6b80-ea4f-11e8-9c8a-5166e9987093.JPG)

**Comment by matiasmolleja** [comment]
There is a scroll bar on the right of the full web page so you can reach to the bottom of the dialog using it.
I guess you mean that It would be better to have scrollbars inside the body of the modal, having the "OK" and "Cancel" buttons always visible? 
I agree it could be better that way.

**Comment by aghili371** [comment]
in some pages, it doesn't work, but I think scroll inside it's more user-friendly and effective.

**Comment by Skrypt** [comment]
Can we have a pager instead? Else those page might become quite long to scroll if you have something like 1000 images in a folder.

**Comment by aghili371** [comment]
i agree, it better to have a pager. but fo solve scroll just need to set overload scroll for content and left box(tree folders).

**Comment by matiasmolleja** [comment]
Yes. We are needing a pager. That would require some work on the backend part, as right now we don't have that feature ("take", "skip").  Unless we want to keep getting everything on one request, and do the paging thing only on the frontend.
Regarding the scrolling inside the modal, i think I initially tried to do that. Not sure why I did not finally apply it. I'll look at it again.

**Comment by sebastienros** [comment]
+1 for Pager, but just Next/Prev, not by number (or you would have to count all items).
