### ISSUE TITLE
SEO strategy

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#2703]
the important thing for any CMS to have a good strategy and digital marketing and content marketing plan. 
i can't find any things about Meta keywords, description, shear in social networks tags and ,....

please in you have any suggestions, confirm me. i think we need a module to do all think automatically just by get information.

**Comment by Skrypt** [comment]
I agree that this should be a contrib module. Not necessary to be a Core module though since there is multiple SEO tools out there that could be integrated ; and those Meta Keywords, Descriptions part should be part of that module migration file. First thing is to find which one would be the most relevant as of now.

**Comment by aghili371** [comment]
thank you, i will do a small one., but it's really necessary for CMS. i think it should improving and developing step by step.

**Comment by sebastienros** [comment]
Let's list all the features we could add here. Feel free to get some examples from other CMSs.

- Sitemap
- ...

**Comment by Jetski5822** [comment]
Canonical Tags
Prev/Next tags for pagination

**Comment by agriffard** [comment]
See also #3229 and 3214

**Comment by aghili371** [comment]
we need to manage keywords and description for the web site too(default page or pages doesn't have these meta tags), it should be in the localization settings menu to set for any different language.

**Comment by scleaver** [comment]
Looking to complete #3214

**Comment by agriffard** [comment]
Splitted in different modules.
