### ISSUE TITLE
Interesting library for replacing Rest or GraphQL api per MVVM ViewModels based on SignalR

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#2704]
I've been using for some weeks a library and I'm very impresed how things are simplified having reactive viewmodels in C# as source of data and behavior for React.js, Vue.js or Knockout.js views instead of consuming a WebAPI or a Graphql one.
This is the library http://dotnetify.net/ . Pleasedon't forget to take a look to dotNetify-Elements, not only dotNetify-Core. Dotnetify is developed by @dsuryd

I don't say we don't need Rest or GraphQL webapis, but this resulted a more straight forward path in cases when you don't need to deal with third parties.
Another interesting feature its is ability to define viewmodels dynamically through Reactive properties, it could fit very well with the dynamic nature of Orchard.
Finally it makes harnessing SignalR easy as eating a peace of cake.

Hope this info can be interesting for you

**Comment by sebastienros** [comment]
Nothing to act upon. You should make a blog post about it, or a module?

**Comment by HengzheLi** [comment]
@jersiovic Are you still using dotnetify? I am using dotnetify(version 5.3.0) and OrchardCore to build my application and encounter an issue.
Dotnetify changes the MVC to use DI to activate the controller https://github.com/dsuryd/dotNetify/blob/fa00c472c5c1c1eee809205d3b166dc748972568/DotNetifyLib.SignalR/Extensions/ServiceCollectionExtensions.cs#L69. 
But seems OrchardCore does not register any controller to DI. So after Dotnetify added, all request to OrchardCore are return 404. 
Have you ever encounter this issue and any idea to workaround it?
