### ISSUE TITLE
Only allow users will specific role to access a custom page?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2706]
In a custom module, I only want Orchard users who have the "Editor" role to access a page, so I added the following in the code in the page's controller, but it doesn't seem to work.
[Authorize (Roles ="Editor")]  

Any idea?

**Comment by sebastienros** [comment]
We work with permissions. A role is only a set of permission. You need to filter with the permission, there are lots of examples in most controllers.

What we are missing though is an attribute that would do it. Today we need to call a service.
