### ISSUE TITLE
Workflow timer issue

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#2708]
Hi,

I have created a workflow type with a starting TimerEvent (1 * * * *). The Done endpoint of this event is attached to a task activity. 

The workflow executes once and then stays in a halted state.

The calculated next occurence in TimerEvent/IsExpired is incorrect. It seems to ignore the time part of the datetime variable in the GetNextOccurrence(startedUtc.Value) call : 

```
       private bool IsExpired()
        {
            var startedUtc = StartedUtc;

            if (StartedUtc == null)
            {
                StartedUtc = StartAtUtc ?? _clock.UtcNow;
            }

            var schedule = CrontabSchedule.Parse(CronExpression);
            var whenUtc = schedule.GetNextOccurrence(StartedUtc.Value);

            return _clock.UtcNow >= whenUtc;
        }

```
PS: the first variable is not used, so the first line could be deleted.

I have also opened an issue in GitHub/NCronTab project : 

[https://github.com/atifaziz/NCrontab/issues/42](https://github.com/atifaziz/NCrontab/issues/42
)
Version 3.3.0
ASP NET Core 2.1

Code :
var schedule = CrontabSchedule.Parse(CronExpression); // 1 * * * *
var whenUtc = schedule.GetNextOccurrence(StartedUtc.Value); // 11/19/2018 11:09:23 AM

Result : whenUtc = 11/19/2018 12:01:00 PM
Expected Result : whenUtc = 11/19/2018 11:10:23 AM

the schedule._minutes = 1 and all other variables have a *. The parse is correct but not the next occurrence.

**Comment by jpiquot** [comment]
My cron expression was false. The correct one is */1 * * * *.

Maybe the default value of timer should be set to */5 * * * * (every five minutes), instead of 5 * * * * (every hour at the 5th minute).

**Comment by sebastienros** [comment]
Can you provide a PR to fix the default value?
