### ISSUE TITLE
Content Picker: Does Not Return Items in Order Selected

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#2712]
The Content Picker in O1 returns the items in the order selected, but this isn't the case in Orchard Core. I think it's reasonable to expect the items will be returned in the order selected.

I added 5 Pages to a Content Picker, called Related, in the order of Page 1 -> Page 5 to the Landing Page in The Agency Theme:

<img width="554" alt="content-picker" src="https://user-images.githubusercontent.com/96801/48801710-0f17a180-ecdb-11e8-914e-ccab2ff78e2d.png">

and using both a liquid template and a GraphQL query the items are not returned in order.

```twig
{% assign items = Model.ContentItem.Content.LandingPage.Related.ContentItemIds | content_item_id %}
<ul>
{% for item in items %}
<li>{{ item | display_text }}
{% endfor %}
</ul>
```

<img width="102" alt="liquid" src="https://user-images.githubusercontent.com/96801/48801899-9238f780-ecdb-11e8-8d3f-f648b87395dc.png">

```GraphQL
{
  landingPage {
    related {
      contentItems {
        displayText
      }
    }
  }
}
```

```JSON
{
  "data": {
    "landingPage": [
      {
        "related": {
          "contentItems": [
            {
              "displayText": "Page 1"
            },
            {
              "displayText": "Page 2"
            },
            {
              "displayText": "Page 4"
            },
            {
              "displayText": "Page 5"
            },
            {
              "displayText": "Page 3"
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by jameshawkins** [comment]
I noticed that too. The issue is that the `content_item_id` liquid filter doesn't return the items in the order that it receives them. I proposed a fix here but i think it got lost in the shuffle: https://github.com/OrchardCMS/OrchardCore/pull/2652
