### ISSUE TITLE
Content Picker: Cannot Re-Order Items

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#2713]
In O1 we had the ability to re-order the items in the Content Picker, this is not the case in Orchard Core. This is really only necessary if the order is important ( https://github.com/OrchardCMS/OrchardCore/issues/2712 ), which I think should be the case.

I added 5 Pages to a Content Picker in the order of Page 1 -> Page 5 to the Landing Page in The Agency Theme. My only option is to delete an existing item or add a new one to the end of the list. I don't have the ability to insert an item between existing items or drag and drop items to different locations in the list.

<img width="554" alt="content-picker" src="https://user-images.githubusercontent.com/96801/48802688-f2309d80-ecdd-11e8-9bb4-36b183f6229b.png">

**Comment by sebastienros** [comment]
Not sure we don't have an issue for this already. But the idea is that we need a new default picker that will behave like the Enumeration Editor for the text field. And would also accept a liquid template for the items in the list.

**Comment by davidhayden** [comment]
I looked and couldn't find an open issue like this specifically using the phrase _content picker_. Can't find an issue mentioning _Enumeration Editor_ either.

I think it will surprise existing developers and users if reordering isn't part of the Content Picker since that is the case in O1, but if there are logical reasons for not including it in favor of using another editor I could be persuaded.
