### ISSUE TITLE
Consider listing code owners for this repository

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#2720]
When submitting a PR updating code you're not familiar with, it's not always easy to determine who's the right person it should be assigned to for review (e.g when modifying the modular middleware, chances are fairly high you'll want JTK to take a look :smile:).

To fix that, I suggest establishing a list of code owners who will be automatically pinged when code they own is updated by a PR: https://blog.github.com/2017-07-06-introducing-code-owners/

Needless to say, I'm applying to be one of the code owners of the OpenID module/core components :sweat_smile:

**Comment by sebastienros** [comment]
I agree, let's just add @jtkech at the root folder

**Comment by jtkech** [comment]
> This means he'll have to review every submitted PR

I disagree 😉

**Comment by agriffard** [comment]
Ex: https://github.com/dotnet/aspnetcore/blob/master/docs/area-owners.md
