### ISSUE TITLE
Remove OrchardCore.Registration from facebook dependencies

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2722]
That would be great if we could avoid depending on the Users module. Ideally, the social providers modules (like FB) should be usable as a standalone module since the ultimate plan is to support external authentication-only scenarios, where you don't have a local users DB (and thus, no Users-like module).

_Originally posted by @PinpointTownes in https://github.com/OrchardCMS/OrchardCore/pull/2715#issuecomment-440681281_

**Comment by MichaelPetrinolis** [comment]
Facebook module does not have any dependency to Users. OpenId has a dependency to User Abstractions because it uses the IUserService for the Resource Owner Password Flow.

**Comment by MichaelPetrinolis** [comment]
Yes, but shouldn't the other module have an account controller that can challenge the external provider? This module just configures the external provider.

**Comment by PinpointTownes** [comment]
@sebastienros I'll take a look tomorrow, but I believe @MichaelPetrinolis addressed my concern by removing the feature dependency in his latest commits. If so, I'll close this ticket and label it as "fixed".
