### ISSUE TITLE
Update UserInfoController to support mapped claims when using JWT as the access token format

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#2726]
hi Kevin

we tried to use OrchardCore as Identity Provider. i upgraded to latest version on  Dev (nuget package: beta3 69674)and userData.Sub Always return null. i debugged and find a fix as below:

UserInfoController

line 60: 
claims[OpenIdConnectConstants.Claims.Subject] =principal.FindFirst(OpenIdConnectConstants.Claims.Subject)?.Value; //sub alway null

i changed to 

 claims[OpenIdConnectConstants.Claims.Subject] = principal.FindFirst(OpenIdConnectConstants.Claims.Subject)?.Value ??
               principal.FindFirst(ClaimTypes.NameIdentifier)?.Value ??
               principal.FindFirst(ClaimTypes.Upn)?.Value;

as suggestion from access controller and it worked.

can you update and build a new nuget package for this fix. we are using and struggle with that issue.

Thanks
Alex

**Comment by petedavis** [comment]
I just fixed the same issue. I'll send a pull requet

**Comment by petedavis** [comment]
@PinpointTownes this issue should now be able to be closed.

**Comment by PinpointTownes** [comment]
Thanks for the fix, @petedavis! :+1:
