### ISSUE TITLE
User roles issue accessing admin panel

### ISSUE THREAD

**Issue by cocoke** [OrchardCMS/OrchardCore#2727]
Hi, 
I've just updated my website to the latest OrchardCore beta 3 version and I'm facing an issue while accessing the admin panel with a different user than the superuser. The user has administrator rights but is redirected to the login page when he try to access the backend.

I've tried to create an empty project with just the OrchardCore cms target package and the issue is still present.

So I tried to decrease the package version and I noticed that the error appears between ``1.0.0-beta3-69634`` and ``1.0.0-beta3-69652``

Can you take a look at it ?

**Comment by matiasmolleja** [comment]
I was going to create a new issue with a gif, and found this one. Just putting the gif here to display repro steps:
![cant-login](https://user-images.githubusercontent.com/2589629/49039767-fb7ba780-f1c0-11e8-8c54-8706090f5858.gif)

**Comment by jtkech** [comment]
For infos, just tried before these 2 commits, same issue, only the site owner can access the admin.

**Comment by sebastienros** [comment]
Cool, go back further ;) And whoever implements the fix, add a functional tests to the existing ones.
