### ISSUE TITLE
No content displayed when setting up with theme recipes

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#2728]
On the latest dev (1235deb434f6065b055b8cb956a3cbb56485fa18) this is how it looks after setting up the site with the Agency recipe, no content is displayed:

![image](https://user-images.githubusercontent.com/1976647/48918705-af61f780-ee8e-11e8-9838-f1311e720277.png)

The content is actually properly imported as far as I can tell, e.g.:
![image](https://user-images.githubusercontent.com/1976647/48918728-d3bdd400-ee8e-11e8-94a5-e29e66068146.png)

Same with the Blog:

![image](https://user-images.githubusercontent.com/1976647/48919210-bc341a80-ee91-11e8-9fc0-8739a70e213e.png)

Coming Soon looks OK, though there's not much to show any way:

![image](https://user-images.githubusercontent.com/1976647/48919301-467c7e80-ee92-11e8-9750-1b5c8b9262fd.png)

No errors in the log, using SQLite. I suspect this has to do something with the templates rather than the recipes.

**Comment by Skrypt** [comment]
Just tried and can't repro.

**Comment by sebastienros** [comment]
I also tried successfully, after checking out the latest dev, and a `git clean -xdf`.

**Comment by Piedone** [comment]
Still the same. This is what I've done:

1. `git clean -xdf`
2. Open solution in VS 15.9.2 (latest as far as I'm concerned).
3. Make OrchardCore.Cms.Web the startup project.
4. Right click on solution node in Solution Explorer and Rebuild Solution (I wanted to make sure exactly this happens).
5. Run Rebuild Solution again after I get some temporary build errors of the "Metadata file 'E:\OrchardCore\src\OrchardCore\OrchardCore\bin\Debug\netstandard2.0\OrchardCore.dll' could not be found	OrchardCore.Infrastructure" kind. Build succeeds.
6. Ctrl + F5 to run with IIS Express.
7. Site starts in Chrome. I run the setup with the following details: 
![image](https://user-images.githubusercontent.com/1976647/48921084-90b72d00-ee9d-11e8-847d-00e2218e2feb.png)

8. I see what's above. Same in Edge just to be sure, but there is no content in the HTML output so that doesn't matter (output below).

Did the same with a new clone to a separate location, same.

Where should I look for the issue?

```
<!DOCTYPE html>
<!-- saved from url=(0024)https://localhost:44300/ -->
<html lang="en-US"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Orchard Core Dev</title>

    <!-- javascript -->


    <!-- CSS -->

    <!-- Custom fonts for this template -->
    <link href="./Orchard Core Dev_files/css" rel="stylesheet" type="text/css">
    <link href="./Orchard Core Dev_files/css(1)" rel="stylesheet" type="text/css">
    <link href="./Orchard Core Dev_files/css(2)" rel="stylesheet" type="text/css">
    <link href="./Orchard Core Dev_files/css(3)" rel="stylesheet" type="text/css">
    

<link crossorigin="anonymous" href="./Orchard Core Dev_files/bootstrap.css" integrity="sha384-2QMA5oZ3MEXJddkHyZE/e/C1bd30ZUPdzqHrsaHMP3aGDbPA9yh77XDHXC9Imxw+" rel="stylesheet" type="text/css">
<link crossorigin="anonymous" href="./Orchard Core Dev_files/font-awesome.css" integrity="sha384-FckWOBo7yuyMS7In0aXZ0aoVvnInlnFMwCv77x9sZpFgOonQgnBj1uLwenWVtsEj" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="./Orchard Core Dev_files/bootstrap-grid-ext.min.css">
    <link href="./Orchard Core Dev_files/agency.min.css" rel="stylesheet">
</head>
<body id="page-top" dir="">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="https://localhost:44300/#page-top">Orchard Core Dev</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu <i class="fa fa-bars"></i>
            </button>
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav text-uppercase ml-auto">
        <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="https://localhost:44300/#services">Services</a>
</li>
        <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="https://localhost:44300/#portfolio">Portfolio</a>
</li>
        <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="https://localhost:44300/#about">About</a>
</li>
        <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="https://localhost:44300/#team">Team</a>
</li>
        <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="https://localhost:44300/#contact">Contact</a>
</li>
    </ul>
</div>        </div>
    </nav>
    <div class="container" id="main" style="padding-top: 150px;">

    </div>


<div class="widget-container">

    <div class="widget widget-html-widget">
    <div class="widget-body">
    


<div class="field field-type-htmlfield field-name-html-widget-content">
    <!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright © Your Website 2018</span>
            </div>
            <div class="col-md-4">
                <ul class="list-inline social-buttons">
                    <li class="list-inline-item">
                        <a href="https://localhost:44300/#">
                            <i class="fa fa-twitter"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://localhost:44300/#">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://localhost:44300/#">
                            <i class="fa fa-linkedin"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks">
                    <li class="list-inline-item">
                        <a href="https://localhost:44300/#">Privacy Policy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://localhost:44300/#">Terms of Use</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
</div>
    </div>
</div>

</div>
<script crossorigin="anonymous" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" src="./Orchard Core Dev_files/jquery-3.3.1.js.download" type="text/javascript"></script>
<script crossorigin="anonymous" integrity="sha384-AsJUT69WgSCIrLgOnMRkNjLvBl0aoHtB3vBDnAEOKRfxKMm7gvmSTJUZCefoYWdA" src="./Orchard Core Dev_files/popper.js.download" type="text/javascript"></script>
<script crossorigin="anonymous" integrity="sha384-DWBJ4L0qV7ffH95jHsoooM04DWR2qtntWspYadu41Wx5kw6d0Cs7W+7C2v2bh7vX" src="./Orchard Core Dev_files/bootstrap.bundle.js.download" type="text/javascript"></script>
<script src="./Orchard Core Dev_files/jquery.easing.js.download" type="text/javascript"></script>
<script src="./Orchard Core Dev_files/agency.js.download" type="text/javascript"></script>

</body></html>
```

**Comment by Skrypt** [comment]
Which version of .NET Core you are running on ?

**Comment by Piedone** [comment]
SDK is 2.1.500, runtime 2.1.6, so latest.

Do you mean https://www.myget.org/F/orchardcore-dev/api/v3/index.json? That's configured in VS as a package source.

The only thing I could find without debugging which might be slightly related to similar issues (but with Razor) is that I have an accented character in my Windows username (Zoltán), which can mess with Razor compilation. But given that otherwise Razor templates work (as do Liquid templates), and other apps, any custom Orchard Core code (and recipe) as well, I'm baffled. I just noticed this by chance.

**Comment by Piedone** [comment]
Hmm, it's just the LandingPage content type that doesn't display anything. It's not just BagPart, because if I add an HtmlBody it won't get displayed either. It's not displaying anything with other themes either. It has to do something with the `Content__LandingPage` template.

**Comment by sebastienros** [comment]
Ping me on skype if you want to debug the issue together

**Comment by Piedone** [comment]
Thanks, will do.

**Comment by Piedone** [comment]
In the meantime any pointers on where the zone block's execution happens? I see that it's registered in `LiquidViewTemplate`, but `NamedHelperBlock` is not the actual implementation. I thought maybe `ZoneTagHelper` would run for it, but no.

**Comment by Piedone** [comment]
After debugging it with Sebastien we found that this is caused by some strange difference in how strings are handled under the Hungarian culture (the culture setting of my Windows):

![Uploading upload.png…]()

Sebastien is changing such string comparisons to `Ordinal` in Fluid. Re-opening this to track when the updates arrive into Orchard.
