### ISSUE TITLE
How to use DataMigration and IRecipeMigrator

### ISSUE THREAD

**Issue by tom-mckinney** [OrchardCMS/OrchardCore#2733]
Hi, I can not figure out how to configure the `IRecipeMigrator` in a project I'm working on. I've read the [docs](https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Recipes/#recipe-migrations) on this subject numerous times, but every time I try to invoke `IRecipeMigrator.ExecuteAsync` in my Migrations file I get the following exception:
```
The file Areas/UpstreamCode/Migrations/migration.recipe.json does not exist.
```
My understanding of this feature is that the `Create` method of a `DataMigration` class should create the initial recipe migration; however, I could have also misinterpreted the docs. I've included my Migrations and Startup files below.

Migrations.cs:
```csharp
public class Migrations : DataMigration
{
    private readonly IRecipeMigrator _recipeMigrator;

    public Migrations(IRecipeMigrator recipeMigrator)
    {
        _recipeMigrator = recipeMigrator;
    }

    public async Task<int> CreateAsync()
    {
        await _recipeMigrator.ExecuteAsync("migration.recipe.json", this);

        return 1;
    }
}
```

Startup.cs:
```csharp
public class Startup : StartupBase
{
    public override void ConfigureServices(IServiceCollection services)
    {
        services.AddScoped<IDataMigration, Migrations>();
    }
}
```

**Comment by davidhayden** [comment]
The code looks good. You're getting a **file not found** error. Per the documentation, did you create a _Migrations_ Folder at the root of your project and place the _migration.recipe.json_ file in it? I tested Recipe Migrations recently and wrote a quick blog post on it.

[Recipe Migrations in Orchard Core CMS](https://www.davidhayden.me/blog/recipe-migrations-in-orchard-core-cms)

**Comment by tom-mckinney** [comment]
@davidhayden thanks for replying! It runs without any exceptions if I add an empty `Migrations/migration.recipe.json` file; however, I cannot figure out how to get the `IRecipeMigrator` to write to this file. I imagined this feature would function similarly to Entity Framework migrations, in that it would generate a recipe migration from the current state of the application. Is this correct? If not, what is the recommended method of generating a recipe migration? It seems a bit tedious to manually write these json files.

**Comment by davidhayden** [comment]
@tom-mckinney Oh, i see. It doesn't work that way. `IRecipeMigrator` reads the recipe file and makes any changes to your Orchard tenant based on the steps and changes you have in the file.

The best way to create recipes is to create a **Deployment Plan**. You add whatever steps you want as part of the deployment and it will create a recipe file for you. The feature has not been documented yet, but if you login to your Orchard tenant as an admin you will see a menu item called **Import/Export** with a submenu called **Deployment Plans**.

**Comment by tom-mckinney** [comment]
@davidhayden Awesome, thank you for the info! I'll definitely read up on this.
