### ISSUE TITLE
Liquid tag for constructing app-relative URLs

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#2736]
If you have a tenant under an URL prefix like /tenant then from Liquid templates you can't construct content URLs that would be aware of that prefix (at least I haven't found a way to do this). So for example if in Liquid you'd like to display a link to the admin you'll need to hard-code the "/tenant/admin" URL instead of being able to write "~/admin" that would work in any case.

For this we could have a tag similar to the Razor `Href()` helper ([like we've done before](https://github.com/Lombiq/Orchard-Liquid-Markup/tree/dev#helpers) in our O1 Liquid module). We could even have a tag to provide what the `Url` helper does (so be able to also construct e.g. action URLs too apart from content URLs). Alternatively we could mimic the [anchor tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.1).

Note: while there is already an `a` tag that's only for content item links. We could possibly extend that as well (or rather, have a generic `a` tag and extend that with content-item specific features).

**Comment by jtkech** [comment]
Just tried under a tenant, the following works in a liquid template.

    {% a href:"~/admin" %}Testing link{%enda%}
    <a href={{ "~/admin" | href }}>Testing link</a>
    <a href="admin">Testing link</a>

**Comment by Piedone** [comment]
Wow, really, this out of the box?

**Comment by jtkech** [comment]
Yes.

If the razor or liquid implementation exists you just have to register the tag name. There is an helper to register filters from a module. For tags you can use a static ctor to do as in `LiquidViewTemplate.cs`.

            Factory.RegisterTag<HelperTag>("helper");
            Factory.RegisterTag<NamedHelperTag>("shape");
            Factory.RegisterTag<NamedHelperTag>("link");
            ...

            Factory.RegisterBlock<HelperBlock>("block");
            Factory.RegisterBlock<NamedHelperBlock>("a");
            Factory.RegisterBlock<NamedHelperBlock>("zone");
            Factory.RegisterBlock<NamedHelperBlock>("scriptblock");

Before, if a tag can be used with content or not (as a block or not) we had to provide 2 implementations. Now we just have to register 2 names whose one has the `block` suffix, as for the above `scriptblock`.

Finally, if a tag name (used as a block or not) is not registered, you can still use it like this.

    {% helper "sometag", attr_name:"..." %}
    {% block "sometag", attr_name:"..." %}...{% endblock %}

**Comment by Piedone** [comment]
Ah great, thank you! Then nothing to do here.
