### ISSUE TITLE
GraphQL query musings

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#2738]
- Ability to flatten a single content part, i.e. ArticlePart in to Article...
- Descriptions at the top level, on all parts and even on the Content Item Interface
- Rename the Parts... I dont want to Query a `SectionPart`, I want to query a `Section`. External Clients wouldnt know what a `Part` is
- stop some core parts from being exposed

**Comment by sebastienros** [comment]
Done?

**Comment by Jetski5822** [comment]
Nope - two more items left, I’m going to address one tomorrow

**Comment by gvkries** [comment]
This seems to be outdated.

**Comment by gvkries** [comment]
IMHO this has been completed, please reopen if I'm mistaken.
