### ISSUE TITLE
Packages missing for versions > 1.0.0-beta3-69719

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#2751]
Hi,

It seems that there are packages missing for versions over 1.0.0-beta3-69719

Regards,
![image](https://user-images.githubusercontent.com/6775094/49096517-04c14e80-f26b-11e8-9079-689c58dc4ec1.png)

**Comment by Skrypt** [comment]
The packages seems to be on MyGet. Try cleaning your solution or your Nuget cache.

**Comment by infofromca** [comment]
http://www.ideliverable.com/blog/getting-started-with-orchard-core-as-a-nuget-package

**Comment by jpiquot** [comment]
@Skrypt  , Thanks for the clear command but I can not use it as I need to keep the 1.0.0-beta3-69719 packages that do not exist anymore in myget. Next packages have the content item type issue with SQLite.

The myget issue with 1.0.0-beta3-69736 does not exist anymore, everything is ok this morning.

**Comment by Skrypt** [comment]
Yes, sometimes it takes some time for MyGet to refresh their feed. 😉
