### ISSUE TITLE
Cannot use MiddlewareFilter attribute on a controller action

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/OrchardCore#2752]
When using a `MiddlewareFilter` attribute (ex: `[MiddlewareFilter(typeof(MyPipeline))]`) on a controller action I get the following error:
`InvalidOperationException: The 'ApplicationBuilder' property cannot be null.`

It appears that the `MiddlewareFilterBuilderStartupFilter` is never executed since Orchard never calls `.UseMvc()` on startup
https://github.com/aspnet/Mvc/blob/1521f9298bc44e70d0fc5f9bc0814e101bbcc479/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L282

The code for `MiddlewareFilterBuilderStartupFilter`:
https://github.com/aspnet/Mvc/blob/8d66f104f7f2ca42ee8b21f75b0e2b3e1abe2e00/src/Microsoft.AspNetCore.Mvc.Core/Filters/MiddlewareFilterBuilderStartupFilter.cs

I am not sure what kind of issues adding `.UseMvc()` would cause with routing, especially tenant routes.

As a workaround I am current doing something like this in my module's startup:
```
public override void Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider)
{
     var middlewarePipelineBuilder = builder.ApplicationServices.GetRequiredService<MiddlewareFilterBuilder>();
     middlewarePipelineBuilder.ApplicationBuilder = builder.New();
}
```

**Comment by jtkech** [comment]
@douwinga which version, i think things have changed around this.

Just tried, we can see that `MiddlewareFilterBuilderStartupFilter` is applied.

![middleware](https://user-images.githubusercontent.com/8586360/51079870-33d33880-16d0-11e9-801e-d09bf244af18.png)

Then, in `OC.Contents` i defined a `MyPipeline` which do nothing, and decorated the `List` action.

        [MiddlewareFilter(typeof(MyPipeline))]
        public async Task<IActionResult> List(ListContentsViewModel model, ...)

Then, going to the admin contents, my pipeline is executed with a non null `ApplicationBuilder`.

![middleware1](https://user-images.githubusercontent.com/8586360/51079884-b2c87100-16d0-11e9-99bf-9340a17dfc88.png)

**Comment by sebastienros** [comment]
@douwinga ?
