### ISSUE TITLE
Expose IDbConnection through DI

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#2757]
I tried to access the DBConnection directly in a module so I can use dapper.contrib to add custom tables in my module.  I added the following code in Startup.cs

```
 public override void Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider)
{
     var connection = serviceProvider.GetRequiredService<IDbConnection>();
     //var connection = serviceProvider.GetService<IDbConnection>();
}
```

Got the following exception: 
InvalidOperationException: No service for type 'System.Data.IDbConnection' has been registered.  

I think this would also resolve #2248

**Comment by infofromca** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1401
