### ISSUE TITLE
Indentation of menu items in admin menu

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#2767]
Right now all are the same indentation and style, which is confusing. It's difficult to know the hierarchy.
/cc @Skrypt

**Comment by sebastienros** [comment]
+1

Also, I don't remember if it's by design, but I couldn't set the icon on a subitem with an admin tree node.

**Comment by matiasmolleja** [comment]
We should close this one. The changes that @Skrypt  did fixed the issue
