### ISSUE TITLE
We are missing a Liquid tag for the ReCaptcha. It works with razor but not with Liquid.

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2768]
_Originally posted by @Skrypt in https://github.com/OrchardCMS/OrchardCore/issues/2078#issuecomment-441551059_

**Comment by agriffard** [comment]
Still needed: Recatcha Liquid filter

**Comment by ns8482e** [comment]
I guess it should work using {% helper “captcha” %}

**Comment by Diman96** [comment]
When will reCaptcha be added to Liquid? Or how it can be used in Liquid pages?  This construction doesnt work `{% helper “captcha” %}`

**Comment by hishamco** [comment]
@Diman96 can you send a PR for it, seems it requires a liquid registration

**Comment by Diman96** [comment]
@hishamco colud you should me sample of liquid helper?

**Comment by Piedone** [comment]
Following up from https://github.com/OrchardCMS/OrchardCore/discussions/6875#discussioncomment-50039.

It turns out the TagHelper wasn't registered at all. I don't know why it worked in Razor though. Fixed it in the linked PR, @Diman96 test it please.
