### ISSUE TITLE
Add default paging to GraphQL queries

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2771]
To prevent from loading all the content items, we need a max page size, and a default one. The default is applied if none is set, and the max is to prevent one that is to big.

/cc @jrestall @Jetski5822

**Comment by Piedone** [comment]
Is there such a default paging for Queries BTW?

**Comment by sebastienros** [comment]
No "unlimited" paging. If you want all content items you'll just do multiple calls.
The risk otherwise is to be able to load to many things in memory.

**Comment by Skrypt** [comment]
If you are talking only about paging then I agree.

**Comment by Skrypt** [comment]
In Lucene Queries there is "from" : {{ from }}, "size" : {{ size }},

**Comment by carlwoodhouse** [comment]
this is very much needed, and some consistent way to return useful paging data.

I've been looking into this recently trying to think of  a solution, and came across this that explains implementing it the same as fbook relay spec.

http://corstianboerman.com/2019-03-08/implementing-pagination-with-graphql-net-and-relay.html

Thoughts ? if we come up with an ideal solution i can look into implementing it as part of workstream here :)

**Comment by sebastienros** [comment]
This should be a setting

**Comment by jrestall** [comment]
I'm thinking this will be a matter of implementing a maximum `first` parameter value of 1,000 that comes from settings.

It would be simplest to make the default the maximum.

If a user wants to retrieve more than 1,000 they could use the `skip` parameter and make multiple requests:
```
query {
  page(status: PUBLISHED, skip: 1000, first: 1000) {
    ...Page
  }
}
```

**Comment by carlwoodhouse** [comment]
i assume we also want to make the default page size (different to max) configurable ? suggestions on a config name

**Comment by carlwoodhouse** [comment]
Draft pr open ^

**Comment by sebastienros** [comment]
> the default page size

Where do we use it in GraphQL? I can't think of where we would have it already, as I thought we only had `first`, `last`, and `skip`

**Comment by carlwoodhouse** [comment]
another query, should we allow both first and last to be specified at the same time ? because we do currently ...

current behaviour is first and skip are ignored if last is specified
