### ISSUE TITLE
Copying of content items?

### ISSUE THREAD

**Issue by cbadger360** [OrchardCMS/OrchardCore#2773]
Is there no facility for creating a new content item by copying an existing content item?  We can add/delete, but there's no copy feature that I can see.  This seems like a pretty fundamental feature that would be expected from any CMS.

**Comment by sebastienros** [comment]
Right now you can do it by exporting and importing the content again.
But yes we need it.

**Comment by cbadger360** [comment]
Appreciate the quick response.  Very excited about the potential of Orchard Core.
