### ISSUE TITLE
Lucene indexation : convention on null field values

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2778]
By playing around with the Lucene Queries I've noticed that when we are not providing a value for a text field ; it will not index it even if we explicitly configure it to be "stored". The issue I had with this is that if I want to filter my content items by using a ElasticSearch Wildcard Query then it will return nothing.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html

So, as stated in the documentation of ElasticSearch here : 
https://www.elastic.co/guide/en/elasticsearch/guide/current/_dealing_with_null_values.html
We should then normally index a "NULL" value that is decided by convention.

Right now I've modified simply the TextFieldIndexHandler and the ContentPickerFieldIndexHandler so that it index a "NULL" string.

```C#
using System.Threading.Tasks;
using OrchardCore.ContentFields.Fields;
using OrchardCore.Indexing;

namespace OrchardCore.ContentFields.Indexing
{
    public class TextFieldIndexHandler : ContentFieldIndexHandler<TextField>
    {
        public override Task BuildIndexAsync(TextField field, BuildFieldIndexContext context)
        {
            var options = context.Settings.ToOptions();

            foreach (var key in context.Keys)
            {
                context.DocumentIndex.Set(key, field.Text ?? "NULL", options);
            }

            return Task.CompletedTask;
        }
    }
}
```

The question is : **should we set a value convention here or is there known alternatives for this through the usage of ElasticSearch Queries?**

## Repro

Create a field and enable indexing + store option. Create an item of that content type without providing any value for the TestField.

![image](https://user-images.githubusercontent.com/3228637/49400449-4db54f00-f712-11e8-9b87-837d6f1ad7ea.png)

Lucene Query without "NULL" value indexed (what we currently have in dev branch) : 

![image](https://user-images.githubusercontent.com/3228637/49400818-65d99e00-f713-11e8-94ba-d845f47fe6ba.png)

On the picture underneat ; we can see that I have content items if I'm not filtering by using a wildcard.

![image](https://user-images.githubusercontent.com/3228637/49400585-b13f7c80-f712-11e8-96b8-bd30a45ac8bb.png)

Though if I want to filter by saying that I want all Acme content items that have a field with ANY value : 

![image](https://user-images.githubusercontent.com/3228637/49400546-93721780-f712-11e8-9f80-93d0149ebca8.png)

I get no results because as you can see nothing is indexed for that field. Though, normally this Lucene Query should return all content items still.

---

Here is the result if I index a default "NULL" string value on Acme.TestField.

![image](https://user-images.githubusercontent.com/3228637/49400699-15fad700-f713-11e8-8d0d-c90afdf0d1b4.png)

**Comment by sebastienros** [comment]
We should try with `""`.

**Comment by Skrypt** [comment]
Solution is to use Exists Queries.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html
