### ISSUE TITLE
Some admin panel sections escape from the /Admin/ url

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2779]
Related to : 
https://github.com/OrchardCMS/Orchard/issues/5905

Example : 
https://localhost:44300/OrchardCore.Features/Admin/Features
should be at least : 
https://localhost:44300/admin/OrchardCore.Features/Admin/Features

**Comment by hishamco** [comment]
I think almost the modules missing that, I will fix this one
