### ISSUE TITLE
Can aggregation queries be implemented at this moment?

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#2782]
Can I currently implement aggregate queries, or do I have such a plan? Should I introduce elasticsearch?

**Comment by sebastienros** [comment]
You can do aggregates in SQL. Anything else you have in mind related to search?

**Comment by Skrypt** [comment]
If you want to aggregate 2 content types you can use Lucene Queries.

```
{
  "query": {
    "bool" : {
      "should" : [
        { "term" : { "Content.ContentItem.ContentType" : "BlogPost" } },
        { "term" : { "Content.ContentItem.ContentType" : "Article" } }
      ]
    }
  }
}
```

Something like this "should" work.

**Comment by chinasqzl** [comment]
@sebastienros is to do some sum,count kind of query, type customization, no xxindex table
