### ISSUE TITLE
Auth cookie not removed during OpenID signout

### ISSUE THREAD

**Issue by simon-d** [OrchardCMS/OrchardCore#2793]
It seems that the Orchard Core authentication cookie is not being removed during the OpenId sign out process.

In LogoutAccept method on OpenId AccessController, the call to HttpContext.SignOutAsync() doesn't actually clear the current authentication cookie.

Explicitly providing an authentication scheme to the sign out seems to resolve this issue and the cookie is correctly removed during singout.

`HttpContext.SignOutAsync("Identity.Application");`

**Comment by PinpointTownes** [comment]
@sebastienros definitely!

**Comment by sebastienros** [comment]
@simon-d could you please create a PR for this?
