### ISSUE TITLE
Ignore case sensitive when check module if exsit in ModuleEmbeddedStaticFileProvider.cs

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#2794]
For function GetFileInfo in ModuleEmbeddedStaticFileProvider.cs, I think it would be better if it can ignore the character case when it checks the module if exisit.

>                 // Check if it is an existing module.
                if (application.Modules.Any(m=> m.Name == module))
                {
                    // Resolve the embedded file subpath: "wwwroot/**/*.*"
                    var fileSubPath = Module.WebRoot + path.Substring(index + 1);

It is common to only use lower character for path to refer resource file in view. However, if the module name has some upper character, the above if will be false.

**Comment by HengzheLi** [comment]
Oh yes. It is a point.
Could it be only ignore case in windows?

**Comment by Jetski5822** [comment]
Then you end up with a system with multiple behaviours - soz.

**Comment by HengzheLi** [comment]
OK. I see it. so bad :(
