### ISSUE TITLE
Wrong content parts order on content item display.

### ISSUE THREAD

**Issue by inhumator** [OrchardCMS/OrchardCore#2796]
It seems placement order for content parts is no longer respected when displaying a content item.
It works fine while editing a content item (the parts are in the order defined in ContentType) but when displaying it the content parts are in a wrong order.

![obraz](https://user-images.githubusercontent.com/1639568/49501452-2e820300-f873-11e8-9b54-d1443c4ae53a.png)

If I understand correctly the position is determined in display drivers with ShapeResult.Location(), is there a way to override it so it uses ContentPartDefinition.Settings["Position"] ?

**Comment by sebastienros** [comment]
I might have broken it last week. I only patched the edit experience, completely forgot about the front end.

**Comment by sebastienros** [comment]
Actually I don't think it ever worked like you are describing. We have always relied on the driver's location, and the placement files.

**Comment by sebastienros** [comment]
You need to use placement info files. We don't provide a way to change the order from the admin, but it's technically doable. @douwinga and his co-workers are working on something like this.

https://orchardcore.readthedocs.io/en/dev/OrchardCore/OrchardCore.DisplayManagement/
