### ISSUE TITLE
How to replace default login view

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#2798]
say I have custom theme and want to create a custom login page. As the Login.cshtml is return by the Login action of AccountController. It is not a shape. so I can replace it using shape mechanism.

And I try create a new view with the same file and folder name under my theme's Views folder. But this does not work.

Is there a way to achieve the replacement?

**Comment by HengzheLi** [comment]
OK. I achieve this by create another folder with the same name of the module name OrchardCore.Users then put the Account/Login.cshtml under this folder.

**Comment by Skrypt** [comment]
I think it has changed. One solution is to use the ?returnurl=something for redirecting to your custom dashboard or secured frontend content pages.

**Comment by HengzheLi** [comment]
![image](https://user-images.githubusercontent.com/491759/51649363-1602af00-1fbf-11e9-9055-db1035ae5c59.png)
@szilardcsere89 Hope this help.

Since the accountcontroller is marked as Admin, I think you need to place your Login file in a admin theme as well

**Comment by szilardcsere89** [comment]
Sure. I haven't noticed the admin attribute. Thanks
