### ISSUE TITLE
Attribute to make resources self closing

### ISSUE THREAD

**Issue by emzyme20** [OrchardCMS/OrchardCore#2799]
When you declare the resources to be used using the OrchardCore.ResourceManagement is it possible to specify that the tag being output is self closing?

```
foreach (var path in Model.Paths)
{
    <style asp-src="/dist/@path" at="Head"></style>
}
```
Could we specify a new property on the tag to indicate self-closing? 

e.g. **self-closing="true"**

When you output the resources using:

``` <resources type="HeadScript" />```

The resulting markup currently outputs the end tag:

```
<link href="path" rel="stylesheet" type="text/css"></link>
<link href="path" rel="stylesheet" type="text/css"></link>
```

What I would like it to output is:

```
<link href="path" rel="stylesheet" type="text/css" />
<link href="path" rel="stylesheet" type="text/css" />
```

**Comment by sebastienros** [comment]
Maybe we should just use slef-closing tags for `link` altogether, without the option. Any issue with that?

**Comment by emzyme20** [comment]
Hi,
That would work for me. 
Thanks

**Comment by emzyme20** [comment]
Hi Sebastien,
Would this be able to be changed in the beta2 candidate or will you have to schedule it for a future release?

**Comment by emzyme20** [comment]
I've created pull request #2817 for this issue.
