### ISSUE TITLE
OrchardCore.Nancy.HelloWorld in OrchardCore.Modules.Cms 

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#2806]
I create a module in OrchardCore.Modules.Cms such as OrchardCore.Nancy.HelloWorld,but it show me page no found,when i visit it throuth Hosturl/OrchardCore.Nancy.HelloWorld

**Comment by mmdqq** [comment]
How to use Nancy in Modules that on OrchardCore.Modules.Cms

**Comment by sebastienros** [comment]
We have nevrer tried to create a Nancy module with the Cms, as this one uses MVC.

@jtkech should it work?

**Comment by jtkech** [comment]
Oups, not sure, i will try it.

**Comment by jtkech** [comment]
So, just tried by adding this in the cms web project.

    <ProjectReference Include="..\OrchardCore\OrchardCore.Application.Nancy.Targets\OrchardCore.Application.Nancy.Targets.csproj" />
    <ProjectReference Include="..\OrchardCore.Modules\OrchardCore.Nancy.HelloWorld\OrchardCore.Nancy.HelloWorld.csproj" />

And this in the cms web startup.

            services.AddOrchardCms()
                .AddOrchardCore()
                .AddNancy()
                ;
It builds and runs but only nancy requests are served. If i go directly e.g to an admin page, i get the nancy 404 nancy page. I will try to find a way so that the nancy middleware is not blocking.

**Comment by jtkech** [comment]
@mmdqq @sebastienros 

I could get something working by using this in the `Startup` of `OrchardCore.Nancy.Core`.

    app.UseOwin(x => x.UseNancy(no =>
    {
        // Added line to not block the tenant pipeline. Hmm, maybe could be a configurable option.
        no.PerformPassThrough = context => context.Response.StatusCode == HttpStatusCode.NotFound;

        no.Bootstrapper = new ModularNancyBootstrapper(new[]
        {
                (IAssemblyCatalog)new DependencyContextAssemblyCatalog(),
                (IAssemblyCatalog)new AmbientAssemblyCatalog(contextAccessor)
        });
    }));

Then if i go to `/admin` i still get `My category is Admin` served from the nancy module, but if i use a more specialized url as `https://localhost:44300/Admin/Contents/ContentItems` i was able to go to the cms admin.

**Comment by sebastienros** [comment]
Looks good.

@Jetski5822 was suggesting to drop Nancy. It's either done or dead, no updates for a long time, and no stable version either. My only concern is the time spent on its support compared to the actual usage. Initially is was added to prove the point that we support any kind of modular app. It might still be a reason to keep it.

**Comment by mmdqq** [comment]
Thank you both,but  i think It is necessary to provide a module of REST full , it's very useful to server miniprogram.

**Comment by jtkech** [comment]
For infos, in the dev branch we have a GraphQL module for this kind of things.

**Comment by jtkech** [comment]
So, just for infos, the final code in the startup of your web app would be e.g.

            services.AddOrchardCms()
                .AddOrchardCore()
                .AddNancy()
                .ConfigureServices(collection =>
                    collection.Configure<NancyOptions>(no =>
                        no.PassThroughWhenStatusCodesAre(
                            HttpStatusCode.NotFound,
                            HttpStatusCode.InternalServerError)));

But we still need to update the startup of `OC.Nancy.Core` so that it resolves and uses `NancyOptions`.

        public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            ...
            var options = serviceProvider.GetService<IOptions<NancyOptions>>();

            app.UseOwin(x => x.UseNancy(no =>
            {
                no.PerformPassThrough = options.Value.PerformPassThrough;
                no.EnableClientCertificates = options.Value.EnableClientCertificates;
                ...
            }));
        }

@sebastienros if you want i can do a PR for this little update in `OC.Nancy.Core`.

**Comment by sebastienros** [comment]
You mean micro services. And MVC Corebis the official framework to build API from Microsoft. There is nothing Nancy can do that MVC can't.

**Comment by mmdqq** [comment]
![api-login](https://user-images.githubusercontent.com/4881282/49627749-76438e80-fa1b-11e8-8b50-30bbc0a8513c.jpg)
Infact i want to offer a developer service by create a module in orchardcore cms

**Comment by mmdqq** [comment]
It's a plan in my mind long times,i think orchardcore is not only a content  cms,it can be a platform to create any applcation by integrate any interface from any Saas or Paas system.

**Comment by mmdqq** [comment]
OK i will be  try two ways ,think you very much
