### ISSUE TITLE
Semantic use of fieldset in admin

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#2809]
I don't want to be the semantic police but fieldset is being used quite incorrectly in OC admin and this may cause accessibility issues later down the track if OC is opted by any organisations who have accessibility requirements. I am thinking it would be best to address this now rather than down the track.

I am happy to work on this an create a PR if you like.

Take for example (and probably heaps of others): https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Autoroute/Views/AutoroutePartSettings.Edit.cshtml

Each field is wrapped in a fieldset and does not container a legend. This is an incorrect use of fieldset (and legend) which should only be used tie related form fields together in a way that is accessible to people who cannot see the visual layout of the form.

**When to use a fieldset and legend**
- You have a single multiple choice question (using radio buttons or checkboxes).
- You have several questions relating to the same topic (like text boxes, or any other type of field).

**When not to use a fieldset and legend**
- You have a single form field that asks for a single piece of information.

**Applicable references:**
- https://www.w3.org/WAI/tutorials/forms/grouping/
- https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/

For example this:

```
<fieldset class="form-group">
    <div class="row col-lg">
        <label asp-for="Pattern">@T["Pattern"]</label>
        <input asp-for="Pattern" class="form-control" />
        <span class="hint">@T["The pattern used to render the custom url of this content type."]</span>
    </div>
</fieldset>
```

Should really be this when combining semantics and bootstrap:

```
<div class="form-group row">
    <div class="col-lg">
        <label asp-for="Pattern">@T["Pattern"]</label>
        <input asp-for="Pattern" class="form-control" />
        <span class="form-text text-muted">@T["The pattern used to render the custom url of this content type."]</span>
    </div>
</div>
```

Like I said... happy to assist here.

**Comment by sebastienros** [comment]
Yes please.

Also, why is `<span class="form-text text-muted">` better than `<span class="hint">`

**Comment by sebastienros** [comment]
If you do it, apply it by steps, or the risk is that it gets blocked or that there is always a module with conflicts. We should start with one module also, such that we have a guideline for the new ones that would be done in the meantime.

**Comment by scleaver** [comment]
Yes hint is fine.

**Comment by scleaver** [comment]
@sebastienros This is a big big job... fieldsets being used everywhere :( Additionally, as I am going through this I am finding that in edit and setting screens, different width and sizing strategies are being used everywhere. This is going to make it a headache for people like me who in future want to re-theme the backend. For example, just this screen - on this simple form there is 4 different column sizes applied across the form:

![image](https://user-images.githubusercontent.com/2867511/49976682-b1e7d680-ff8e-11e8-8a81-2713afb61dcc.png)

I am not going to fix the sizing issues in this PR, I think it should be separate, but what I might do is work on a guideline document like you sent me from WordPress, get this solidified so that contributors can refer to that so that the problem just doesn't keep growing. If I work on that quickly I can then get back to removing the fieldsets in a few days.

**Comment by hishamco** [comment]
@scleaver could you please let us know what's remaining to close this one? At least I can help you close it if there's something still pending ..

**Comment by hishamco** [comment]
Any update one this?!!

**Comment by sebastienros** [comment]
There is (or was) a PR that applied it to one page, but it should be done everywhere.

**Comment by hishamco** [comment]
I will check it if we didn't get a reply from Seth

**Comment by scleaver** [comment]
@hishamco - I started on this but it is a huge task... I mean massive. There are so many views that need to be fixed.

**Comment by hishamco** [comment]
You can categorize them by module, also I can work with you on this if you want

**Comment by hishamco** [comment]
Seems I will start on this by module with the alphabetic order that shown here https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules
