### ISSUE TITLE
UI design: missing cancel buttons

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#2810]
I don't know if this is a recent change but it seems like all the cancel buttons have been removed from the backend UI. It kind of leaves the user thinking "what should I do here???" when they go into a view and then decide that they don't want to change anything.

What's the intention... is OC assuming that users should use the browser back button?

**Comment by sebastienros** [comment]
We just add them when we feel like it's missing. Some screens have Cancel buttons.

**Comment by scleaver** [comment]
![image](https://user-images.githubusercontent.com/2867511/49623918-4eecc180-fa1b-11e8-9f4f-3986a0d29c6a.png)

So for example I was editing the Autoroute part settings this morning on a content type. For me if I put on my "regular Joe at the office editing my website" hat, I feel like UIs like this should have some sort of "nope i don't want to touch this" action - whether this is a cancel button or a go back button.

The main places I find it is missing is when you are editing content types and parts.

**Comment by scleaver** [comment]
It's not a big one, just a thought.

**Comment by matiasmolleja** [comment]
This is one case where the cancel button is a good idea.

Related to this: 
In the edit content type view I find that the workflow is a little disconnected. 
As soon as we click on "edit field" or "edit part" buttons we loose completely the context.  We are in a new view where there is no information about the global task we are doing or the concrete content type we are editing. Maybe we should think of ways to avoid that. 
For example, having a breadcrumb on that "child" task view. Or putting it on a  modal? Or in a "slide" view?
Having said that, I understand that is harder to maintain.

**Comment by matiasmolleja** [comment]
Tabs is a good idea to separate for example: 
1. General : Type name, Creatable, Listable etc...
2. Fields: 
3. Parts:
4. (Just thinking) Templates?: Maybe it would be nice to have the liquid template editor here too, in order to avoid that "disconnection" I talked about?

Regarding the issue with "disconnected" child view, a breadcrumb is the easiest solution.
So you don't like the idea of having an slider as other CMS do for these kind of "secondary" tasks?
Maybe we could implement that using a Zone in the main view?

**Comment by sebastienros** [comment]
Show me an example of a "slider"

**Comment by sebastienros** [comment]
Ok found it. Not a fan of sliders. It reminds me too much of Drupal and I don't find very practical.
