### ISSUE TITLE
How to display content items associated to a Taxonomy Term

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2818]
Context:
- Create a `Category `content type with TitlePart.
- In the BlogPost content type, add a TaxonomyField Categories using it.
- Edit a blog post and add some terms.

In the `Content_Summary__BlogPost`, add this to display the terms:
```
{% assign fields = Model.ContentItem.Content[Model.ContentItem.ContentType] %}
      {% assign categories = fields.Categories | taxonomy_terms %}      
      {% for cat in categories %}
         <a class="tag badge badge-secondary" href="category/{{ cat | slugify }}">{{ cat }}</a>
      {% endfor %}
```

1) How can I create a page `categories` with a list of the blog posts grouped by taxonomy term?

- I tried to add an Autoroute with a pattern `category/{{ ContentItem | display_text | slugify }}` on the Category Type but it doesn't seem the way to do it because when I want to display the page of a term using its slug, it returns a 404

2) How can I call an url `category/myterm` that would list the associated items of this term?

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2755#issuecomment-442540147

**Comment by sebastienros** [comment]
New suggestion, use a Razor Page that take the term's slug in the route.

Maybe we should look into being able to register routable items based on templates. Maybe EndpointRouting allows that (2.2 and 3.0)

**Comment by sebastienros** [comment]
Create a new kind of entity (not a content item) that renders content items by taxonomy. Which would have a custom alternate to customize the whole list or the items inside. Also configure paging.

**Comment by sebastienros** [comment]
We need to be able to select which fields the query should take into account when rendering the content items?

Example:
Taxonomy named `categories` with `science`, `politics`, `sports`, `sports/soccer`...

The url `categories` should render all the terms with a summary display type and a custom alternate for this page. Only if this property is enabled on the taxonomy. Some sites might not want to list the terms in a specific page. We might want to leverage autoroute to define a custom url. And optionally render a shape from the TaxonomyPart driver to render the terms.

The url `categories/science` should display all content items with this term. Only for the selected fields of the "public page" option on the taxonomy. Each term needs a custom __handle__ to define its part of the url. However in this case we can't have two pages that would render different fields. This could only be solved by creating a distinct routable entity which would define it's own url.

**Comment by sebastienros** [comment]
Should we extend autoroute to support templated routes, like `foo/{bar}` which would then be available in a content item like Liquid Page to render custom queries based on `{bar}`

**Comment by deanmarcussen** [comment]
Can this be closed now @agriffard ?

(we have another issue to support the idea of templated routes)
