### ISSUE TITLE
route.MapAreaRoute() doesn't work

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#282]
I'm trying to use it route.MapAreaRoute() for mapping actions to urls following REST standard problem is route.MapAreaRoute() is ignored by Orchard.

The point is I find route.MapAreaRoute() used in meany parts of the Orchard2 core, so it is sensible to think it is working properly. An example:

```
routes.MapAreaRoute(
                name: "Home",
                area: "Orchard.Demo",
                template: "Home/Index",
                controller: "Home",
                action: "Index"
            );
```

The point is all the MapAreaRoute calls I have found are like this code. They don't do anything because the maps a route to an action that is the same used by mvc by default for that action so if you remove those lines nothing change.
However if you change the template to sth different than the default route:

```
routes.MapAreaRoute(
                name: "Home",
                area: "Orchard.Demo",
                template: "Home/Test",
                controller: "Home",
                action: "Index"
            );
```

When you access to that route `http://localhost:2918/Orchard.Demo/Home/Test` page is not found.

**Comment by jersiovic** [comment]
I have found how to make it work. Simply adding the area to the template:

```
routes.MapAreaRoute(
                name: "Home",
                area: "Orchard.Demo",
                template: "Orchard.Demo/Home/Test",
                controller: "Home",
                action: "Index"
            );
'''
I leave open the issue only because I consider current MapAreaRoute calls in Orchard code are useless and in my opinion they should be removed. What do you think?

**Comment by sebastienros** [comment]
I can't repro this. It works fine for me, here is the example:

https://github.com/OrchardCMS/Orchard2/blob/export/src/Orchard.Cms.Web/Modules/Orchard.Deployment/Startup.cs#L41

you can see that I am using a REST compliant route.

And this is how I render the url:

```
<a asp-action="Delete" 
           asp-controller="Step" 
           asp-route-id="@Model.DeploymentPlanId" 
           asp-route-stepId="@Model.DeploymentStep.Id" 
           class="btn btn-danger btn-sm" 
           itemprop="RemoveUrl UnsafeUrl">@T["Delete"]</a>
```

And the generated url

`href="/Deployment/DeploymentPlan/121/Step/b796613f2ad94173a95fa0153094bfd7/Delete"`

In this example specifying the area on the link generation doesn't matter. I don't know why but it might be related. Try to add the area information in your link generation logic. I assume if the link is from a different area then you need to specify it.

**Comment by richb8** [comment]
I'm also experiencing this with all the modules I've created.

The only way for me to get it to work is to have the area name the same as the module namespace and to also prefix the template with the same area.

For example:

` 
routes.MapAreaRoute(
                name: "Contact",
                areaName: "My.OrchardCore.Modules.SimpleContactForm",
                template: "My.OrchardCore.Modules.SimpleContactForm/Contact/{action}",
                defaults: new { controller = "Contact", action = "Index" }
            );
`

**Comment by sebastienros** [comment]
We have so many routes already working, would be interesting to find why yours doesn't work. Also the template you are using is actually the default one, so even if you removed this route definition it would still work.

**Comment by richb8** [comment]
Yeah it's one I can't quite figure out because like you say, it should work. Will investigate.

**Comment by richb8** [comment]
OK, i'm really confused. It seems to be all working now. Not sure what was going on. Maybe the rebuild did the trick.

The route i'm using for the module is:

```
routes.MapAreaRoute(
                name: "Contact",
                areaName: "My.OrchardCore.Modules.SimpleContactForm",
                template: "Contact/{action}",
                defaults: new { controller = "Contact", action = "Index" }
            );
```
