### ISSUE TITLE
SunEditor: Wysiwyg editor

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2821]
Stumbled upon this Wysiwyg editor with MIT license: 
http://suneditor.com/sample/index.html

It seems to have nice features.

**Comment by sebastienros** [comment]
I already mentioned another editor that is now used in the most used cms. @Skrypt which one was it?

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2634

**Comment by agriffard** [comment]
#2828
