### ISSUE TITLE
How to export a custom theme for others to install??

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2823]
I followed [this article](https://orchardcore.readthedocs.io/en/dev/docs/getting-started/theme/) created a OrchardCore theme (2 projects: 1 web + 1 class for theme).
Question is how to export and distribute it to someone else who can install on their OrchardCore instance?

**Comment by sebastienros** [comment]
you need to build a Nuget package by running `dotnet pack`. You can then either share the nupkg directly, on put it on a gallery, like Nuget.org or Myget.
