### ISSUE TITLE
Install nuget package of the custom Theme onto a Production envrionemnt??

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2825]
I built a custom Theme then pack as a nuget package using "dotnet pack" from the development environment.

Now I send it to someone for installation on the existing Orchard environment (same orchard/.net version with DEV).

How can that person load this nuget package to install on the production environment? I can't find any useful information about this topic.

(Link to the topic : https://github.com/OrchardCMS/OrchardCore/issues/2823)

Many thanks!

**Comment by sebastienros** [comment]
Have you tried to reference the package from the web project? Like any other DotNet class library. Then redeploy.

**Comment by orchardc** [comment]
Hi Sébastien, I can deploy to a .nuget package - no problem.  But the problem is really about how do they (normal people) install the nuget package without visual studio?

**Comment by orchardc** [comment]
Any suggestion is highly appreciated!

**Comment by sebastienros** [comment]
There is no other way

**Comment by orchardc** [comment]
I might mis-understood it - but I think there must a way to deploy a package? Previously in Orchard CMS, it was possible to package a module or theme, then upload/install to another environment.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2732
