### ISSUE TITLE
Implement Avatars support

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2829]
Allow to add a picture for a user.

Display it in admin, next to the name.

Provide Liquid filters to easily create one in templates.

Possible to use it in when a User picker will be started.

Allow multiple implementations.
A first implementation could be to use Gravatar, based on the email.

**Comment by sebastienros** [comment]
I assume we can already add it to our admin top bar without any much work.

**Comment by Skrypt** [comment]
Here is a javascript function to achieve something while not using Gravatar

```javacript
var stringToColour = function (str) {
    var hash = 0;
    for (var i = 0; i < str.length; i++) {
        hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    var colour = '#';
    for (var i = 0; i < 3; i++) {
        var value = (hash >> (i * 8)) & 0xFF;
        colour += ('00' + value.toString(16)).substr(-2);
    }
    return colour;
}
```

**Comment by hishamco** [comment]
Fixed in https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/pull/74

We can demo it next week, then see if we can have it in OC
