### ISSUE TITLE
Publicly accessible RedirectToLocal Controller extension method

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#2830]
There is a RedirectToLocal private helper method in the AccountController.cs in OrchardCore.Users module. How about making it a publicly accessible extension method?

**Comment by sebastienros** [comment]
It's risky to have to own such things, and you can 
- easily add it to your code
- use the existing way to do it: `if (IsLocal) Redirect("foo")`

Change my mind
