### ISSUE TITLE
- at the start of hints should be added as a pseudo element

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#2837]
Small one but currently "- " is being added at the start of some hints (see samples below) within Admin. This should be added by a pseudo element using :before in CSS rather than hard coded into the solution as this does not allow flexibility for the admin to be themed. If a custom Admin theme is applied which calls for a different placement of the hint where having "- " at the start does not make sense then "- " is almost impossible to remove without modifying the views or using JS.

Rather the "- " should be applied using a CSS rule creating a pseudo element so that it's use can easily be controlled in future without changing the underlying views.

![image](https://user-images.githubusercontent.com/2867511/49757420-19402500-fd08-11e8-8746-f2a2712f5b01.png)

![image](https://user-images.githubusercontent.com/2867511/49757423-1cd3ac00-fd08-11e8-9eac-d846edff6446.png)

Solution: remove "— {0}", from the hint and instead update admin theme CSS with:

 .custom-checkbox .hint:before
  {
   content: "—";
   margin-right: 0.5rem;
  }

This is not a huge issue but just a cleanup task. Happy to claim this after completing other HTML fixes.

**Comment by sebastienros** [comment]
Good. Also it will work with RTL which is nice. Only issue I see in this snippet that is not related to your bug, is that a user-provided text should not be localized like this. Just use `@settings.Hint`.

**Comment by hishamco** [comment]
The simplest way is to take the hyphen out of the translation, moving it to external is good and bad, because on each change we need to do `gulp build`

**Comment by Piedone** [comment]
Alternatively, we could have a `<hint>` tag helper or something, similar to `Html.Hint()` in Orchard 1, so all of this can be DRY.

**Comment by sebastienros** [comment]
Closing the issue as this has been solved by removing it from the translated text, but @Piedone please file an issue with your suggestion, looks good for this use case as it's specific to orchard.

**Comment by Piedone** [comment]
OK, done it: https://github.com/OrchardCMS/OrchardCore/issues/5804
