### ISSUE TITLE
TitlePart placement and Form elements

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2839]
Let's say I want to put the Title of a content in another zone by using a placement.json in a theme:

```
{
  "TitlePart": [
    {
      "display-type": "Detail",
      "place": "/Header"
    }
  ]
}
```

Problem : When I create a Form, the title of the form is also added in this zone.

**Comment by sebastienros** [comment]
Let's say on a Page 

It would have a TitlePart and we add a Form as a new widget.

1- This should not already render 2 Titles. 
2- Do the two titles only appear when you move one this is another issue?

**Comment by ns8482e** [comment]
@agriffard you can specify content criteria in placement.
