### ISSUE TITLE
Razor Page Custom Route With arguments does not work when published

### ISSUE THREAD

**Issue by nukedbit** [OrchardCMS/OrchardCore#2850]
On my project i have a razor page with a custom route defined as 

`@page "/technologies/{alias}/"`

It works fine while debugging, but once i publish it either locally and running it with dotnet or remotely on a iis server the route no longer works and the page is not found.
I got it working by adding this instruction on the Startup.cs

`services.AddMvc().AddRazorPagesOptions(s => s.Conventions.AddPageRoute("/Technologies", "/technologies/{alias}"));`

**Comment by sebastienros** [comment]
@jtkech

**Comment by jtkech** [comment]
@sebastienros @nukedbit 

Okay, i could repro with an application razor page and in a published context where this razor page is precompiled. The route using the razor page file name still works but not the custom route template. Maybe something has changed.

In this context we have a custom file provider which lookup in the precompiled assembly to find precompiled items from which we can get paths. But it seems that they may also contain route attributes, see the image. So, i think we will have to also use this lookup where we build route templates.

![alias](https://user-images.githubusercontent.com/8586360/49906256-6986c680-fe71-11e8-92c8-5a0a15e5103c.png)

I could repro even in a dev context by copy pasting the precompiled assembly and not using the razor page file. So, it will be easier to fix. I will fix it asap.

**Comment by sebastienros** [comment]
> maybe something has changed

2.2 ?

**Comment by jtkech** [comment]
Maybe

**Comment by nukedbit** [comment]
Yes sorry i forgot to mention i'm in 2.2 with orchard beta3
