### ISSUE TITLE
To have the option of deploying Orchard 2 as a windows service

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#286]
In order to take the easy path we can use this new feature in Mvc 6  that requires frameworks net461 to work.
http://stackoverflow.com/questions/30277991/mvc-6-install-as-a-windows-service-asp-net-core-1-0-0/34567682#34567682

Now we use "portable-net451+win8" Do we plan to  move to net461 soon?

**Comment by jersiovic** [comment]
Sorry I think I made a mistake. Currently Orchard uses framework "netcoreapp1.0" .
Do we need to move to "net461" ?

**Comment by sebastienros** [comment]
You can target net461 too. But I would not worry about it right now.

**Comment by jersiovic** [comment]
Targeting net461 produced many compilation problems. So, I discarded that path.
Finally, with the help of this library https://github.com/dasMulli/dotnet-win32-service I've been able to execute orchard as a windows service without the need of IIS and without many changes to Orchard.
I will send a PR to show you the result.

**Comment by agriffard** [comment]
Closing because no efforts made in that way.
