### ISSUE TITLE
Alternates per content item

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#2866]
My scenario is that I have create pages using Page contenttype. I want these pages to use different template to rendered. e.g. there is a page named userlogin and another named userregister. I want my custom login template to render userlogin page and my custom register template to render userregister page.

I remember in O1, there was an alternates that looks like Content-Item-[ContentId]. But this has to depend on the content item's id. And another approach is using Alias in placementinfo file to specify a alternates. But this seems not be implemented according this document https://orchardcore.readthedocs.io/en/latest/OrchardCore/OrchardCore.DisplayManagement/README/
in OC.

Is there another way to do that?

**Comment by sebastienros** [comment]
We could add an alternate with the Alias module, good idea.

**Comment by flew2bits** [comment]
I know this is an old issue, but is the goal here to add an alternate formatted like `Content__[ContentType]__[Alias]`? For example, a `Page` with an alias of `my-page` would have an alternate of `Content__Page__my-page`. Would any other alternates be appropriate? Should this take into account the content type stereotype as well?

**Comment by barthamark** [comment]
The `Content__[ContentType]__[Alias]` looks like a good solution to me. I'll try to add it as part of the Harvest hackathon.
