### ISSUE TITLE
Comments Module

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardCore#287]
Discussed in todays weekly meeting. There weren't many voices speaking up but the general view was:
- Build a Disqus based module for the first iteration, eg Orchard.Comments.Disqus
- Then build a native comments module after eg Orchard.Comments

Other social comments systems mentioned were Bazaarvoice & Facebook comments

Looking for feedback on the following:
- Do you think we need a native Orchard.Comments module for v1 of O2?
- Does it need threaded comments?

**Comment by agriffard** [comment]
I will make a Disqus module for OrchardCore soon,
