### ISSUE TITLE
Suggestion for Admin Trees: Find a new name

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2870]
The Admin Trees module is great but we should consider finding a more meaningful name for the users who do not get instantly what a navigation tree is and how it can help them to organize the menu and add custom links.

We could rename it by something like 'Admin links', 'Admin menu' or 'Custom menu'.

**Comment by matiasmolleja** [comment]
Yes, I'ts weird. 

I started trying to do something similar to the Content tree from O1. Then it evolved to be more like a tree of links on the admin. And I hoped that some day we could do a "real" content tree so I wanted to keep that name unused.

I like the 3 options you mentioned.

**Comment by sebastienros** [comment]
We have `Menu` already, `Admin menu` would work I think

**Comment by Skrypt** [comment]
What's the final decision?

**Comment by sebastienros** [comment]
Admin menu

**Comment by agriffard** [comment]
I also choose 'Admin menu'.
