### ISSUE TITLE
Load Placement.json file with Configuration Provider

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#288]
Use the aspnet configuration providers for all the things!

**Comment by sebastienros** [comment]
Is the format compatible at least? Or will it make it ugly? 
What is the problem that this would solve?

**Comment by Jetski5822** [comment]
As long as its valid JSON it shouldnt be an issue. What it means is that we could also have a placement.xml file if we so wished without doing any extra work.

or a placement.yaml file etc..... maybe we need a placement provider!?

**Comment by sebastienros** [comment]
Using Configuration won't let you switch between json and xml, because both format actually have different ways of representing placements, look at the examples. I showed the new format at the meeting, we talked about it a bit and nobody disliked it.
