### ISSUE TITLE
Mobile friendliness

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2885]
There are issues with mobile view:
- List actions are not responsive

![image](https://user-images.githubusercontent.com/1165805/50122729-c63c0580-0212-11e9-8686-84a44ec66d1d.png)

- The asset management if wider than the view

![image](https://user-images.githubusercontent.com/1165805/50122703-a99fcd80-0212-11e9-9bb1-5367cd917d15.png)

- The navigation doesn't provide scrolling

![image](https://user-images.githubusercontent.com/1165805/50122680-8d039580-0212-11e9-8940-34254fd20768.png)

We should probably go over every page once in a while to check.

**Comment by hyzx86** [comment]
And Activity's buttons on workflow canvas  

![workflowEdit](https://user-images.githubusercontent.com/15613121/55309200-a235c480-548f-11e9-8dc5-ba551b74a95f.gif)

**Comment by sebastienros** [comment]
@hishamco did you just create a new Label UI/UX, I don't recall we did this one

**Comment by hishamco** [comment]
Yep, to classify those UI related bugs, coz I need to close many of them

**Comment by sebastienros** [comment]
Don't create tags, or tag items aggressively. We have weekly triage meetings and use the updated time to find the issues we need to look into, and today it was a pain to find what to look at because tens of them had been updated.

**Comment by hishamco** [comment]
Sorry, my aim was to classify the issues to filter them easily, hope to catch you guys next week on the triage

**Comment by sebastienros** [comment]
We should check all the pages work on mobile

**Comment by hishamco** [comment]
Of course, I can handle that after polish the admin pages. BTW I already started with one issue that I pinged you few days ago

**Comment by Skrypt** [comment]
Closing this one and reopening https://github.com/OrchardCMS/OrchardCore/issues/5449 as the only remaining issue.
