### ISSUE TITLE
Fix modules that don't correctly use PathBase-relative root paths

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#2891]
Many modules - like the setup module - reference CSS and JS files using root-relative paths. E.g:

```html
<link type="text/css" rel="stylesheet" href="/OrchardCore.Setup/Styles/setup.min.css" />
```

Sadly, this doesn't work (at all) when hosting your application under a virtual path (for instance, `http://localhost/orchard`).

To fix that, all the assets should be referenced using the `PathBase`-relative syntax (`~/`). E.g:

```html
<link type="text/css" rel="stylesheet" href="~/OrchardCore.Setup/Styles/setup.min.css" />
```

In this case, MVC will correctly compute the asset URL based on the `PathBase` defined by the IIS integration middleware.

@sebastienros I marked this ticket with P0 as it basically makes any OC deployment hosted under a virtual path unusable.

**Comment by PinpointTownes** [comment]
FYI: the resource management feature is also broken and updating `ResourceManifest` to use `~/` instead of `/` is not enough to fix the issue.

**Comment by PinpointTownes** [comment]
FYI, there's still a bug:

https://github.com/OrchardCMS/OrchardCore/blob/05b49eeb7f91235c60c8ac285405fa6a53f1354f/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs#L48-L55

```csharp
httpContext.Request.Path.ToString().Substring(httpContext.Request.PathBase.Value.Length)
'httpContext.Request.Path.ToString().Substring(httpContext.Request.PathBase.Value.Length)' threw an exception of type 'System.ArgumentOutOfRangeException'
    ActualValue: null
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233086
    HelpLink: null
    InnerException: null
    Message: "startIndex cannot be larger than length of string.\r\nParameter name: startIndex"
    ParamName: "startIndex"
    Source: "System.Private.CoreLib"
    StackTrace: "   at System.String.Substring(Int32 startIndex, Int32 length)"
    TargetSite: {System.String Substring(Int32, Int32)}
```

**Comment by PinpointTownes** [comment]
![image](https://user-images.githubusercontent.com/6998306/51054067-d958b000-15db-11e9-83d5-07d663a1e4f0.png)

![image](https://user-images.githubusercontent.com/6998306/51054075-e1b0eb00-15db-11e9-9a6c-91afbec9f703.png)

**Comment by sebastienros** [comment]
repro ?

**Comment by PinpointTownes** [comment]
Same as last time: create an IIS website with a virtual directory, create a tenant with a URL and watch OC assplode :trollface:

**Comment by PinpointTownes** [comment]
Something like that should fix it for good but it will need some testing to ensure it doesn't regress something else:

```csharp
if (!String.IsNullOrEmpty(shellContext.Settings.RequestUrlPrefix))
{
    PathString prefix = "/" + shellContext.Settings.RequestUrlPrefix;
    httpContext.Request.PathBase += prefix;
    httpContext.Request.Path.StartsWithSegments(prefix, out PathString remainingPath);
    httpContext.Request.Path = remainingPath;
}
```

**Comment by PinpointTownes** [comment]
While we're at virtual path issues, the `GetTenantUrl` Razor helper in the `Index` view of the `Tenants` module doesn't take the `PathBase` into account, which generate invalid URLs (e.g the setup button doesn't work).

**Comment by infofromca** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2695

**Comment by jtkech** [comment]
Just took a quick look, so not sure.

> the GetTenantUrl Razor helper in the Index view of the Tenants module doesn't take the PathBase into account.

And, because it is done through the `Default` tenant, we would have to remove from the `PathBase` at the end the segment related to the default tenant prefix if it has one.

**Comment by jtkech** [comment]
Maybe idem in the `GetTenantUrl()` method in the `ApiController` of the Tenants module.

**Comment by 8VAid8** [comment]
Still have the issue: setup page can't load css and js when app is running behind nginx reverse proxy.
Links looks like that:
`<link type="text/css" rel="stylesheet" href="/OrchardCore.Setup/Styles/setup.min.css" />`
I tried remove '/'. In that case stiles is loading properly - 
``<link type="text/css" rel="stylesheet" href="OrchardCore.Setup/Styles/setup.min.css" />``

P.S. I've used docker image (orchardcore-cms-linux) with tags latest and dev -

**Comment by jtkech** [comment]
Which version do you use, in both dev / master branches we use a `~` char.

    <link type="text/css" rel="stylesheet" href="~/OrchardCore.Setup/Styles/setup.min.css" />

**Comment by 8VAid8** [comment]
I used latest docker [image](https://hub.docker.com/layers/orchardproject/orchardcore-cms-linux/latest/images/sha256-6f284db1a79729118831b93861d43a47d5e52c33717127557b9cb15a63f8e102)

Yes, i checked repo and also found a ~ char.
But when i run image i get a Setup Page without styles and js.
my nginx config looks like that:
```
server {
 listen 80;
 server_name mysite.com;
 if ($ssl_protocol = "") {rewrite ^ https://$server_name$request_uri? permanent;}

 location /api/ {
 proxy_pass http://localhost:5001/api/;
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection keep-alive;
 proxy_set_header Host $host;
 proxy_cache_bypass $http_upgrade;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 client_max_body_size 2M;
 }

 location /ru/blog/ {
 proxy_pass http://localhost:5003/;
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection keep-alive;
 proxy_set_header Host $host;
 proxy_cache_bypass $http_upgrade;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 client_max_body_size 2M;
 }

 location / {
 proxy_pass http://localhost:8080/;
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection keep-alive;
 proxy_set_header Host $host;
 proxy_cache_bypass $http_upgrade;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 client_max_body_size 2M;
 }

}
```
I use "/ru/blog/" location for Orchard project.

**Comment by jtkech** [comment]
Maybe you need our `OC.ReverseProxy` feature but that is not available during a setup. We have an helper to add a feature to the setup but `OC.ReverseProxy` doesn't use config source (e.g appsettings) to initialize the `ForwardedHeadersOptions`, it uses settings that needs to be set through the admin.

You would need to do it yourself from the app by using our helpers to do things at the tenant level.

            services.AddOrchardCms()
                .AddOrchardCore()
                //.AddSetupFeatures("OrchardCore.ReverseProxy")
                .ConfigureServices(s =>
                {
                    s.Configure<ForwardedHeadersOptions>(o =>
                    {
                        // ...
                    });
                })
                .Configure(builder =>
                {
                    builder.UseForwardedHeaders();
                });

**Comment by 8VAid8** [comment]
I tried this solution, but i got error if use ".AddSetupFeatures("OrchardCore.ReverseProxy")": 

> An unhandled exception occurred while processing the request.

> InvalidOperationException: Unable to resolve service for type 'OrchardCore.Settings.ISiteService' while attempting to activate 'OrchardCore.ReverseProxy.Services.ReverseProxyService'.

> 
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, int slot)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory+<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, int slot)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory+<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, int slot)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory+<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, int slot)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory+<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
    System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
    Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
    Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)
    Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, object[] parameters)
    Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
    Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
    OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline() in ModularTenantRouterMiddleware.cs
    OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in ModularTenantRouterMiddleware.cs
    OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
    OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by 8VAid8** [comment]
I also tried to do it in different way:
1. Run Orchard Core on / location (example.com)
2. Setup, add path base example.com/blog/, add proxy module
3. Change nginx location for Orchard - /blog/

It works, but all links is wrong again. They mounted to a root - example.com.

**Comment by jtkech** [comment]
Yes, as said it uses site settings that needs to be set through the admin, so it needs `OrchardCore.Settings.ISiteService` that can't be resolved when starting the setup.

That's why i commented it out in my above example and suggested to configure things yourself by using the `Configure()` and `ConfigureServices()` helper to do things at the tenant level, so without using our reverse proxy module.
