### ISSUE TITLE
Null reference in ShellFeatureApplicationPart/Types

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#2892]
```

       public IEnumerable<TypeInfo> Types
        {
            get
            {
                **var services = _httpContextAccessor.HttpContext.RequestServices;**

                if (services == null)
                {
                    return Enumerable.Empty<TypeInfo>();
                }


```
![image](https://user-images.githubusercontent.com/6775094/50164227-585f0f00-02e2-11e9-9283-1a5ffc358843.png)

Call stack:

 	OrchardCore.Mvc.Core.dll!OrchardCore.Mvc.ShellFeatureApplicationPart.Types.get()	C#	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPart> parts = {unknown}, Microsoft.AspNetCore.Mvc.Controllers.ControllerFeature feature = {unknown})	C#
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature(TFeature feature = {unknown})	C#
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()	C#
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()	C#
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()	C#
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(Microsoft.AspNetCore.Mvc.Abstractions.ActionDescriptorProviderContext context = {unknown})	C#
 	Microsoft.AspNetCore.Mvc.Core.dll!Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()	C#
 	Microsoft.Extensions.Primitives.dll!<>c__DisplayClass0_0.AnonymousMethod(System.Object s = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext = {unknown}, System.Threading.ContextCallback callback = {unknown}, System.Object state = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(bool throwOnFirstException = {unknown})	C#
 	Microsoft.Extensions.Primitives.dll!Microsoft.Extensions.Primitives.CompositeChangeToken.OnChange(System.Object state = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext = {unknown}, System.Threading.ContextCallback callback = {unknown}, System.Object state = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(bool throwOnFirstException = {unknown})	C#
 	Microsoft.Extensions.Primitives.dll!Microsoft.Extensions.Primitives.CompositeChangeToken.OnChange(System.Object state = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext = {unknown}, System.Threading.ContextCallback callback = {unknown}, System.Object state = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(bool throwOnFirstException = {unknown})	C#
 	Microsoft.Extensions.Primitives.dll!Microsoft.Extensions.Primitives.CompositeChangeToken.OnChange(System.Object state = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(bool throwOnFirstException = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext = {unknown}, System.Threading.ContextCallback callback = {unknown}, System.Object state = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot = {unknown})	C#
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	C#

**Comment by sebastienros** [comment]
Repro steps?
