### ISSUE TITLE
ResourceManager should not depend on IHttpContextAccessor

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2894]
Right now it requires to be executed from an ASP.NET request because of that.

- `RegisterUrl(string resourceType, string resourcePath, string resourceDebugPath, string relativeFromPath)` should use `relativeFromPath` instead of `Request.PathBase`. 
- The default value for `relativeFromPath` should be defined using an option

When configured from an ASP.NET we can then use the `PathBase` as the default value for the option

**Comment by hishamco** [comment]
>  should use relativeFromPath instead of Request.PathBase

I think you mean `resourcePath` not `relativeFromPath`

**Comment by sebastienros** [comment]
Replaced by #4120
