### ISSUE TITLE
Media picker overflows

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2898]
![image](https://user-images.githubusercontent.com/1165805/50194250-df19e900-02ee-11e9-8288-4347a2b42ca8.png)

**Comment by sebastienros** [comment]
Probably not responsive enough

**Comment by matiasmolleja** [comment]
Maybe it's because your puppies are too ugly?
:stuck_out_tongue_winking_eye:

Try https://pixabay.com/en/

**Comment by sebastienros** [comment]
Please tag the issues your PRs are fixing with `Fixes #1234`

**Comment by matiasmolleja** [comment]
I thought I was doing it right. 
I added a text in the first comment of the PR: Fixes #2898
Do I need to do something more?
