### ISSUE TITLE
ClockExtensions creates dateTimeUtc variable and ignores it?

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#2902]
@sebastienros This feels like a bug to me:

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Abstractions/Modules/Services/ClockExtension.cs

Shouldnt the dateTimeUtc be passed to the clock, not the dateTime parameter?

**Comment by Skrypt** [comment]
We can't prevent someone sending a DateTime that is not DateTimeKind.Utc.
If you do var date = new DateTime() and you try to pass it to the Clock instance then this date will not be DateTimeKind.Utc so we are just preventing that this happens by converting the date type to DateTimeKind.Utc.
