### ISSUE TITLE
How to use orchard core as headless and return content as JSON

### ISSUE THREAD

**Issue by nyghtrocker** [OrchardCMS/OrchardCore#2904]
Hi, I want to use orchard core  as headless CMS.  I want to remove orchard UI and return the content as JSON. How to create localize content problematically and return these content using API.

**Comment by infofromca** [comment]
check them:
https://www.youtube.com/channel/UCDVUxCz2RvkgTbA0wAYKwRA

**Comment by infofromca** [comment]
https://www.youtube.com/watch?v=yWpz8p-oaKg&t=3711s

**Comment by nikonast** [comment]
Decoupled isn't headless.

**Comment by ns8482e** [comment]
@nikonast Orchard Core CMS is really a hybrid cms - that provides best of both world.  Orchard  Core CMS is delivered as nuget package that you can add it into your exiting web application to make it as content service application.

- Using [GraphQL](https://docs.orchardcore.net/en/dev/docs/reference/modules/Apis.GraphQL/) and OpenId you can truly use it as `headless` in different scenarios i.e. web or device app - separate from your Orchard Core Web App. 
- Using [Orchard Razor Helper](https://docs.orchardcore.net/en/dev/docs/reference/core/Razor/#razor-helpers) you can use it as decoupled within your orchard core web app
- Orchard Core CMS also provides a Content Management related abstraction and implementations that allows you to customize content management according to your needs.
