### ISSUE TITLE
LayerMetadataWelder welds to widgets within container widget

### ISSUE THREAD

**Issue by KeithRaven** [OrchardCMS/OrchardCore#2908]
- Add a container widget (using container from blog theme) to a layer. This correctly gets LayerMetadata welded. 
- Then add other widgets to the container.  On save all the widgets get LayerMetadata welded on incorrectly, with all instances get updated with the same values.

This is due to the prefix in the LayerMetadataWelder not taking account of context:

https://github.com/OrchardCMS/OrchardCore/blob/8c500ad6794e02c434ee32e996abe3083bc8d5ff/src/OrchardCore.Modules/OrchardCore.Layers/Drivers/LayerMetadataWelder.cs#L25-L28

![image](https://user-images.githubusercontent.com/9599649/50247531-01376800-03d0-11e9-81ff-0090640e1e19.png)

I have a PR to submit for this but thought I should probably raise an issue first.  Is it preferable to do this or is a PR first fine?

A similar thing is also happening with ContainerPart whereby on items which are parented when using the Lists module, their child widgets get the ContainerPart welded on incorrectly, again due to prefix issues.  This is less obvious as the ContainerPart only renders a hidden field in the editor currently.  I also have a seperate PR I can submit for this.

**Comment by sebastienros** [comment]
I did some changes on the prefixes two days ago ... did I break it?

**Comment by KeithRaven** [comment]
No it was already broken.

It's because LayerMetadataWelder inherits ContentDisplayDriver which inherits DisplayDriver<ContentItem..> and so it has to  override BuildPrefix in order to correct the naming (which uses TModle) but misses out:

https://github.com/OrchardCMS/OrchardCore/blob/7cdd1499feff476710f94f25d8066470f3d893e0/src/OrchardCore/OrchardCore.DisplayManagement/Handlers/DisplayDriver.cs#L121-L124

**Comment by KeithRaven** [comment]
After a little digging... There are 3 drivers that inherit ContentDisplayDriver that use modelbinding as part of UpdateAsync:

- LayerMetadataWelder - Issue described above
- FlowMetadataDisplay - This doesn't override BuildPrefix and so the form names are in the format '0238562c71c64416b872a5c6129dc660.ContentItem.Alignment' ie with ContentItem as the base prefix as this is first type argument passed to its base class. This works fine but would seem open to name conflicts if others where to do the same
- ContainedPartDisplayDriver - This doesn't use the Prefix property but instead uses nameof(ListPart) as the prefix in TryUpdateModel. As mentioned above is also causing problems although not visible.

In my working fix for ContainedPartDisplayDriver, I brought it into line with LayerMetadataWelder , overridding BuildPrefix and adding the lines from the previous comment.

It feels like they all need to be able to override this line:
https://github.com/OrchardCMS/OrchardCore/blob/1e3aa303577e8f0a31994fefe4c94975bd4ad40c/src/OrchardCore/OrchardCore.DisplayManagement/Handlers/DisplayDriver.cs#L119 

Would it make sense if this class used a  'PrefixRoot' property that defaults to typeof(TModel).Name but that could be overwritten by subclasses?

Replacing the line with:
`Prefix = PrefixRoot;`

This would avoid the need to overide BuildPrefix and repeat the lines that check/add the htmlFieldPrefix.

I'm happy to pr a fix if you let me know your preference.

**Comment by jtkech** [comment]
Yes, doing a PR is fine, thanks.

Note: it's one of the 3 last issues to be fixed before releasing beta3.

**Comment by sebastienros** [comment]
Can someone try to repro the issue?

**Comment by jtkech** [comment]
Just tried, yes i could repro as described above

**Comment by hishamco** [comment]
@KeithRaven are your still interested to send a PR for this?
