### ISSUE TITLE
Allow assignment of permissions to roles during setup

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/OrchardCore#2909]
Not sure if this is available already, but i don't think it is.

It would be great if we could assign permissions to a role when executing a setup recipe. Ie i might have a recipe that has graphql enabled and i wanna assign the permission for running graphql to the anonymous role not just admins.

If it doesn't exist happy to take a look and provide a pr

**Comment by sebastienros** [comment]
Recipe step, and deployment. Whichever is not already implemented.

**Comment by sebastienros** [comment]
Fine for beta3 if someone does it in time.

**Comment by carlwoodhouse** [comment]
turns out this does exist already ... (RolesStep) and uses ...

```
 {
      "name": "roles",
      "Roles": [
        {
          "Name": "Anonymous",
          "Permissions": [ "ExecuteGraphQL" ]
        }
      ]
    }```
this syntax according to the readme, doesn't work at all though as it tries to deserialize it to something totally different .. writing a fix, will provide pr.
