### ISSUE TITLE
Read content type / part from MVC view?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#2915]
I create a custom Theme using MVC,  and then configure a content type which contains two content parts, structure like this:
MyContentType
__MyContentPart1
__MyContentPart2

Question is, how to read data from MyContentPart in my MVC code (View and Controller)?

**Comment by sebastienros** [comment]
First you need to access a content item from your controller or view. The you can do `contentItem.Content.MyContentPart1`
