### ISSUE TITLE
The question of Queries

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#2917]
Recently I've been learning Queries Documentation.
**Below is the demo:**

{% assign recentBlogPosts = Queries.RecentBlogPosts | query %}
{% for item in recentBlogPosts %}
{{ item | display_text }}
{% endfor %}

now,I  create a Liquid Page and use Queries.
My question is that how can I know the detail of 'item' from the demo;

Thank you very much.

**Comment by Skrypt** [comment]
{{ item.Content }}

**Comment by cellpaddding** [comment]
> {{ item.Content }}
Yes, it works!

**Blow is the result:**
{
  "TitlePart": {
    "Title": "苏NC6861"
  },
  "Car": {
    "CarType": {
      "TaxonomyContentItemId": "49hs72z4937x94y51zk5en3kcv",
      "TermContentItemIds": [
        "4rp0xxa71k7r0yrdkbepc57mmy"
      ]
    },
    "Driver": {
      "ContentItemIds": [
        "chenchen"
      ]
    },
    "SeatingCapacity": {
      "Value": 5.0
    },
    "Source": {
      "TaxonomyContentItemId": "4cva7r8dxmsej5bttzx4nwahww",
      "TermContentItemIds": [
        "4z0ex3ts761td78q9pqqtvjvd7"
      ]
    },
    "FuelCard": {
      "Value": 15105946.0
    },
    "Photo": {
      "Paths": [
        "Car_Images/电工师傅小程序二维码.jpg"
      ]
    },
    "Status": {
      "Value": true
    },
    "InUse": {
      "Value": false
    },
    "Brand": {
      "Text": "大众"
    }
  },
  "ListPart": {
    "FeedProxyUrl": null,
    "FeedItemsCount": 20
  }
}

My question is that how to get the value of 'Driver' node.
Thank you.

**Comment by Skrypt** [comment]
https://jsoneditoronline.org/?id=fc46a69812be458a878f01b0a0eda4b8

{{ item.Content.Car.Driver.ContentItemIds }}

if you look at documentation you can retreive a content item using this method : 

https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Contents/README/#loading-from-a-content-item-id

so : 

{% assign my_content = Content.ContentItemId[item.Content.Car.Driver.ContentItemIds[0]] %}
