### ISSUE TITLE
Validation logic does not exist in one place

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/OrchardCore#2925]
In facebook, twitter, MicrosoftAuthentication and OpenId, validation rules for settings are defined multiple times.

**Comment by Piedone** [comment]
What kind of validation are you referring to? Is this still applicable?

**Comment by hishamco** [comment]
@MichaelPetrinolis is this #13151 PR is what you are looking for?

**Comment by hishamco** [comment]
@MichaelPetrinolis can you verify that related PR doesn't break anything if you had tried all the social AUTH before, because I remember I stuck with Twitter last time
