### ISSUE TITLE
Range sliders

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2926]
Consider using this nice library for range sliders which is MIT.
https://github.com/IonDen/ion.rangeSlider

**Comment by agriffard** [comment]
We could also consider https://github.com/leongersen/noUiSlider/ as an alternative.

**Comment by jtkech** [comment]
Related to #2266 about localization concerns.

**Comment by Skrypt** [comment]
Too old, I'm closing. Refer to #2266 as this control should be localizable.
