### ISSUE TITLE
Optimizing ShellBlueprint 

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#293]
It's currently held by a `ShellContext` object. Does it make sense to keep it around in memory once the shell context has been built and activated?

Also, it contains the list of Types and Features for the shell, should it be used instead of the `ITypeFeatureProvider`? It seems we have the same information twice here.

**Comment by Jetski5822** [comment]
Will add to my branch

**Comment by sebastienros** [comment]
Are you sure you don't want to do a separate one, or is it conflicting?

**Comment by Jetski5822** [comment]
Your right, I'll do separate. Can you review my branch?

**Comment by sebastienros** [comment]
On wednesday
