### ISSUE TITLE
Admin Trees creates an administrator menu panel based on different user rights roles？

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2931]
I released the latest ORCHARD CORE using VS 2019.
The Admin Trees module is great.
Can I create an administrator menu panel based on user role permissions?

Or other methods to achieve it?Documentation? Or an example?

**Comment by pgy866** [comment]
perfect! If implemented, it will facilitate rapid development, and many application scenarios can be used to him!

**Comment by Piedone** [comment]
This is possible now.
