### ISSUE TITLE
placement.json TextField is displayed in the Summaryadmin template, not successful, why?

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#2935]
![86af6e94-5fe9-421c-8437-928d3b7d8f1e](https://user-images.githubusercontent.com/16968103/50388971-73a4a100-075e-11e9-9420-9b6d81620335.png)
![image](https://user-images.githubusercontent.com/16968103/50388992-9d5dc800-075e-11e9-9f7b-961edd3a2076.png)
![image](https://user-images.githubusercontent.com/16968103/50388997-aea6d480-075e-11e9-967a-e226a964de0f.png)

**Comment by sebastienros** [comment]
I don't think the placement.info is applied in the admin.
