### ISSUE TITLE
To prevent brute force password cracking

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#2936]
To prevent brute force password cracking, is it necessary to increase user lock settings?

![qq 20181224173438](https://user-images.githubusercontent.com/28694676/50396049-4bd72c80-07a2-11e9-9f8d-a597c9996d67.jpg)

**Comment by Piedone** [comment]
Lockout covers this now: https://docs.orchardcore.net/en/latest/docs/guides/lockout-configuration/
