### ISSUE TITLE
Anonymous callers can create posts using content API, corrupt admin

### ISSUE THREAD

**Issue by jakenuts** [OrchardCMS/OrchardCore#2951]
While trying to determine how to authenticate with OpenId I discovered that any POST to /api/content will generate a new document in the database despite not passing a bearer token.  In ApiController.cs the creation of a document (and it's associated parts) precedes the call to AuthorizeAsync. The documents were accepted as-is (is there validation?) so the resulting content resulted in errors in the admin interface.

1.) Clone latest source & create CMS app 
2.) Enable OpenId (may not be necessary)
3.) Post a document to api/content

**Comment by sebastienros** [comment]
I assume you still get a 401, right? https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs#L78

But some content is still created.
