### ISSUE TITLE
Update of nuget package causes Admin UI issues

### ISSUE THREAD

**Issue by ksks88** [OrchardCMS/OrchardCore#2956]
As I said I updated OrchardCore.Application.Cms.Targets package to build 70326 and weird UI issues appeared I also tried creating a new site:

![image](https://user-images.githubusercontent.com/4154182/50542919-b506d780-0bc8-11e9-8abe-33e0fd9749c1.png)

I'm using Firefox developer edition.

**Comment by Skrypt** [comment]
Refresh your browser cache

**Comment by ksks88** [comment]
Yes it did, thanks.
