### ISSUE TITLE
datetime Tag Helper Not Implemented?

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#2965]
Even though it is documented, I cannot see in code where this tag helper is implemented:

``<datetime utc="@contentItem.CreatedUtc" />``

Same would go for the equivalent "timespan" helper.

I went looking for it after I could not get it to work. I see the Shape code is in there (e.g. OrchardCore.DisplayManagement.Shapes.DateTimeShapes) just no TagHelper code.

**Comment by sebastienros** [comment]
Also maybe it should be called `LocalDateTime` as I assume this is the goal of this __shape__

**Comment by jeffolmstead** [comment]
I have locally implemented these Tag Helpers (e.g. DateTimeTagHelper and TimeSpanTagHelper) but it also hit me these are just "Shapes" so they could be displayed using the shape tag with properties. In other words, at what point is it worth having a custom tag helper versus just documenting how to get the same effect another way. Here is an example:

```
{% helper "datetime" %}
```
is equivalent to 
```
{% shape "datetime" %}
```

and 

```
{% helper "datetime", format: "MM/dd/yyyy" %}
```
is equivalent to 
```
{{ "datetime" | shape_new | shape_properties: format: "MM/dd/yyyy" | shape_render }}
```

So it just makes me wonder whether I should put in a pull request with my code changes or if instead the documentation should be updated. Obviously the TagHelpers make it easier but then they need maintained also should things change.

**Comment by agriffard** [comment]
`datetime` Liquid filter still to be done.
A 'timeago' filter could be also useful.

**Comment by jeffolmstead** [comment]
@agriffard I already have the code done for a "datetime" tag helper. I was just wondering if we even need it as we are duplicating another method which provides the same exact effect (see my comment above yours). If it is still deemed to be valuable, I can put in a pull request for the "datetime" Liquid filter. If you let me know what the expectations are on a "timeago" filter, I could likely wire that up also.

**Comment by Skrypt** [comment]
Yes please if you can do this it would be easier for everyone trying to follow the Liquid documentation else we need to create our own documentation too for explaining the alternatives if it doesn't exist.

**Comment by agriffard** [comment]
The "timeago" filter allows you to display "N minutes ago" instead of a the datetime.
