### ISSUE TITLE
I never set permissions to a role,but some menu trees always show.

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#2982]
I create a role,and set some permissions to it.
below picture shows the permissions  that I set to the role.
![qq 20190107150758](https://user-images.githubusercontent.com/16536053/50753772-0e889980-128e-11e9-9fe9-bd16c4c8f242.png)

The strange thing is that there are some menus  always show.
Below is the picture:
![qq 20190107150945](https://user-images.githubusercontent.com/16536053/50753903-a7b7b000-128e-11e9-8d55-067bb1b5aed0.png)

How to let them disappear?
What's the reason of it?
thank you!

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2931
This is related, the default menu after some role permissions: such as adding content, settings, etc. should not be displayed under the role permissions configuration.
It seems that no documentation has been found in this regard.
这是相关的，默认一些角色权限后的菜单：如添加内容，设置等等应该在角色权限配置下不显示。
好像没有发现这方面的说明文档

**Comment by cellpaddding** [comment]
> #2931
> This is related, the default menu after some role permissions: such as adding content, settings, etc. should not be displayed under the role permissions configuration.
> It seems that no documentation has been found in this regard.
> 这是相关的，默认一些角色权限后的菜单：如添加内容，设置等等应该在角色权限配置下不显示。
> 好像没有发现这方面的说明文档

这些权限似乎没有地方去控制。

**Comment by cellpaddding** [comment]
@pgy866 估计内容的创建等模块不受权限控制的。

**Comment by pgy866** [comment]
The role-based management menu seems to be still being implemented.

As for the content? This is relevant,
https://github.com/OrchardCMS/OrchardCore/issues/1211
Content creation should be controlled by the role, based on the role of precise control of permissions to a content type (such as news articles) (or blog posts), and even extended to control permissions to the field, may need to follow the RC



```
基于角色的管理菜单好像还在实施中。

至于内容吗？这是相关的，
https://github.com/OrchardCMS/OrchardCore/issues/1211
内容的创建应该是可以由角色控制，基于角色精确控制权限到某个内容类型（比如新闻文章）（或者博客文章），甚至延申到控制权限精确到字段，可能需要后续RC之后了
```

**Comment by Skrypt** [comment]
It needs work. I'm looking at it right now.

**Comment by cellpaddding** [comment]
It's a bug?

**Comment by Skrypt** [comment]
It's just not yet implemented. There's dynamic permissions for hiding each dynamic content types per role which is a class that is currently all commented out. And there are adjustments needed with the different permissions related to content.

**Comment by Piedone** [comment]
The menus items have proper authorization now.
