### ISSUE TITLE
One exception on installing the recipe

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#2984]
I custom my recipe, and I prepare some default data in my recipe.The number of the default data is tow,and the data type are all Taxonomy.I install my recipe,it run successfully.
But,when I prepare one default data of Taxonomy,I install the recipe,an exception is thrown.
Here are my data and the exception:
![20190108132350](https://user-images.githubusercontent.com/16536053/50811698-874d2b80-134a-11e9-8b88-3621aef8aee2.png)
![qq 20190108132639](https://user-images.githubusercontent.com/16536053/50811706-8c11df80-134a-11e9-8c10-19b556da11a1.png)
thank you.

**Comment by sebastienros** [comment]
Did you find the reason ?
