### ISSUE TITLE
Cannot use swagger for custom API modules

### ISSUE THREAD

**Issue by Tsjerno** [OrchardCMS/OrchardCore#2985]
The ApiController of the Tenants module contains a public function (GetTenantUrl) which does not have HTTPVERB.
Shouldn't this be a private method?

Now my swagger returns the following exception:
NotSupportedException: Ambiguous HTTP method for action - OrchardCore.Tenants.Controllers.ApiController.GetTenantUrl (OrchardCore.Tenants). Actions require an explicit HttpMethod binding for Swagger 2.0

**Comment by sebastienros** [comment]
Can you provide a PR ?
Also can you check the other methods that would potentially break swagger too?

**Comment by Tsjerno** [comment]
I have enabled all modules and changed three controllers to make the swagger work
See https://github.com/OrchardCMS/OrchardCore/pull/3328
