### ISSUE TITLE
Documentation: Beta3 Tag Reference

### ISSUE THREAD

**Issue by anorborg** [OrchardCMS/OrchardCore#2997]
The documentation references the beta3 release with a link here:

https://orchardcore.readthedocs.io/en/dev/#status

However it appears it isn't released yet.

**Comment by sebastienros** [comment]
Correct, it's because this documentation branch correspond to our dev branch, which is targetting beta3. As soon as we merge dev into master, the dev branch will target RC, and the documentation of the dev branch will reflect that.
