### ISSUE TITLE
Create Title and Body upgrade steps

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#2998]
Test from a beta 2 site.

At that point this can still be an automatic step instead of a custom action, as there shouldn't be that many content items in the wild. We can still batch them, and use JObject with YesSql to make it easier. Should be super fast.

`TitlePart.Title` should be copied to `Title`
`BodyPart` should be renamed to `HtmlBodyPart`

**Comment by themattkenney** [comment]
Thank you @sebastienros
