### ISSUE TITLE
lock _tasksQueue in IndexingTaskManager.cs

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#2999]
inside FlushAsync()
line 112:
await transaction.Connection.ExecuteAsync(insertCmd, _tasksQueue, transaction);

_tasksQueue is not locked , so it can happen that the deleted ContentItemIds  does not include the ContentItemId which just added to _tasksQueue.
====
actually, here we should use .WaitAync() of SemophoreSlim

**Comment by sebastienros** [comment]
Is there a way to repro the isue?

**Comment by infofromca** [comment]
now locked after this change, so close it
 lock (_tasksQueue)
            {
                if (_tasksQueue.Count == 0)
                {
                    ShellScope.AddDeferredTask(scope => FlushAsync(scope, _tasksQueue));
                }

                _tasksQueue.Add(indexingTask);
            }
