### ISSUE TITLE
Improve Tenants management

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3005]
The tenants admin page should have some basic features like:
- Add pagination, list only 10 tenants per page.
- Select multiple tenants and execute batch actions (Disable).
- Be able to find a tenant by its name or url host/prefix.
- List only the ones in a specific state (Running, Disabled, Setup, Uninitialized).
- May be, allow to delete a tenant?

I already asked in another issue but it would be interesting to have more informations about the tenants:
- Creation date (retrieve the date from the folder?)
- Display the type of SQL provider that is used?
- Display / Edit a description for the tenant.

It is also a bit slow when there are many tenants to list, because it needs to get the informations from every site. 
Discussing about this with @sebastienros, he said that when the configuration PR is merged, it should be quicker because it will be stored in only one file.

**Comment by scleaver** [comment]
These are good points. I agree with @agriffard - more details for tenants is required. Tried to delete a tenant yesterday and could not.
