### ISSUE TITLE
Why MapPublicUrlToPath limit the media scope to "media"

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#3007]
Can it be customized?

I used some downloaded template as theme. These themes have itself file structure to refer image file. Their paths do not match the pattern of "[TenantName]/media". So it have to replace all of path to match MapPublicUrlToPath's scope.

I can't read out the point that limit the scope to "[TenantName]/media". Can someone provide more information?

**Comment by sebastienros** [comment]
You can just use `[ThemeName]/media`. Otherwise I don't really understand the question, would you mind giving more details?

**Comment by HengzheLi** [comment]
Sorry for my bad expression.

I think I had two questions:
1. Can the scope be customized? Like [ThemeName]/assets/media or [ThemeName]/content. Or Add multiple folder path into the scope.
2. What is the purpose to limit the path to a scope?

**Comment by sebastienros** [comment]
Your question is confusing, now I think I understand you refer to the `/media` folder. Is that you want to be able to change the name of this prefix?

**Comment by HengzheLi** [comment]
This is the "scope" I call
![image](https://user-images.githubusercontent.com/491759/51367200-5a580000-1b24-11e9-84d1-6016b38ec00c.png)

Yes. I want to be able to change it and want to understand what the "MapPublicUrlToPath" used for. If someone can explain or provide some link about it, that will be appreciated.

**Comment by sebastienros** [comment]
You can use this method if you want to find the name of the media, based on its public url. For example if the media stsorage is Azure, the public url will be an https://blobs.windows.net url (or something similar), but internally Orchard will use only a `folder + filename` name so we can be independent from the public url (and the actual storage engine that might change overtime).
