### ISSUE TITLE
DefaultContentManager/PublishAsync save before update

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3008]
Hi,

It seems that they may be a code line inversion. The previous contentitem is modified after it is saved. Is this by purpose or a bug?

![image](https://user-images.githubusercontent.com/6775094/51086125-b268be00-1742-11e9-95cb-fcffa8687dfc.png)

**Comment by infofromca** [comment]
as I remember, because the YESSQL system, 
the both of them are the same effective.
'previouse.Published = false;
_session.Save(previouse);'

**Comment by sebastienros** [comment]
As explained by @infofromca
