### ISSUE TITLE
lucene api parameters not work

### ISSUE THREAD

**Issue by xiaolizi007** [OrchardCMS/OrchardCore#3020]
this url size parameter  not work ， this will return many items not one as expect
```
https://localhost:44300/api/lucene/content?indexName=search&query={ "query": { "match_all": { } }&parameters={ size: `1}`
```

this will work 
```
https://localhost:44300/api/lucene/content?indexName=search&query={ "query": { "match_all" : { } } ,"size" : 1}

```
and  i tried http post method , it's not work as http get , i guess maybe something wrong with the code as below 

OrchardCore.Lucene/controllers/apiController.cs
```
        [HttpPost, HttpGet]
        [Route("content")]
        public async Task<IActionResult> Content(
            string indexName,
            string query,
            string parameters)
```

**Comment by Skrypt** [comment]
This works as expected. You pass the Size and From params in the controller action `parameters` and in your Query you set a liquid var to your Size and From filters.

**Comment by sebastienros** [comment]
This is not well documented, the idea is that the `parameters` argument will be available as liquid values if you query is a liquid template. You query can then be something like:

```
{ 
  "query": 
    { "match_all": { } },
    "size" : {{ x }}
}
```

and you can then use `{ x: 1}` as the parameters.
