### ISSUE TITLE
HTTPS redirection is not working

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#3026]
Activated the HTTPS module and selected "require https" - the site is not redirected to https.

![image](https://user-images.githubusercontent.com/2867511/51214983-3d2c0180-196b-11e9-84d0-7d1d9040ada4.png)

**Comment by Skrypt** [comment]
I'm not sure if this module is still relevant.

**Comment by scleaver** [comment]
How so?

**Comment by PinpointTownes** [comment]
I tested and it worked fine on my machine (TM). Any chance you could share more info about your environment (and ideally, capture a small video of the entire flow, from enabling HTTPS to visiting a non-HTTPS endpoint?)

**Comment by scleaver** [comment]
Azure App Service, Windows, SqlLite. Let'sEncrypt SSL. Https not forced by Azure application settings as I believe the HTTPS should do it for you by the looks. I will get a video. OC 1.0.0-beta3-70463

**Comment by scleaver** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/vIliN04jG4A?rel=0&amp;showinfo=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by sebastienros** [comment]
Maybe an issue in Azure App Service, it has its own option to force https. I don't disagree it should still work.

Orthogonal question, how did you configure LetsEncrypt?

**Comment by scleaver** [comment]
Https works but you have to manually change the address.

LetsEncrypt is setup to auto install/renew SSL certs using a schedule webjob in Azure across all sites using this https://github.com/sjkp/letsencrypt-siteextension

**Comment by sebastienros** [comment]
Ok, I use the same extension.

**Comment by sebastienros** [comment]
Wouldn't it be awesome if Let's Encrypt was supported OOB in Orchard, including automatic renewal? /cc @douwinga 😄 

It will be in eventually, obviously before RC

**Comment by scleaver** [comment]
That would be awesome!

**Comment by TFleury** [comment]
I had same issue (also on Azure) and it seems the SSL Port setting is mandatory to get it working.

**Comment by TFleury** [comment]
It seems to be related to aspnet/Announcements#301
443 is no longer user used as the default HTTPS port, and middleware fails to determinate it on Azure.
We should encourage user to set it.
