### ISSUE TITLE
Serilog 2.8.0 - netstandard2.0

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/OrchardCore#3034]
Serilog released v2.8.0 which targets netstandard2.0 

When Serilog.Sinks.RollingFile and Serilog.Sinks.Console target netstandard2.0, 
it would be good time to upgrade in order to shrink the dependency graph

**Comment by kimballjohnson** [comment]
The Serilog implementation in orechardcore dev 3.0 seems like it should work. 
But I cannot tell whether including OrchardCore.Logging.Serilog and the other configuration descriptions in the ReadTheDocs.io dev version will enable the logger throughout the entire code or just in the the CMS.Web. 
Does this implementation piggy-back on the Microsoft.Extensions logging infrastructure?
How do I instantiate a serlog-based logger in any static or non-static orchardcore class I want to inspect?
Could you add a usage example to the docs, please?
Thanks...

**Comment by MichaelPetrinolis** [comment]
Hi, @kimballjohnson , this issue is for tracking when to upgrade to latest Serilog (which is netstandard2 lib and will shrink the dependency graph). By using Serilog or NLog, each ILogger injected in the constructor of a class is created from the registered logging library. If you have more questions, consider opening a new Issue.
