### ISSUE TITLE
Add feature to allow for control of CacheControl header for static files

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#3035]
Be great if OC could support configuring a tenants default cachecontrol headers for different types of files.

For example, you might want to set 365 days for css and jss resources and 7 days for images. Generally min of 7 days is recommended for static resources.

Additionally, be great if browser or proxy (cdn) cache duration could be set differently. No-cache would have to be specified when content editing to ensure editor is seeing the latest content.

Cache busting might need to implemented for css/jss assets. https://andrewlock.net/adding-cache-control-headers-to-static-files-in-asp-net-core/

At the moment I am just using the following to set 7 days in the startup.cs:
app.UseStaticFiles(new StaticFileOptions
            {
                OnPrepareResponse = ctx =>
                {
                    const int durationInSeconds = 60 * 60 * 24 * 7;
                    ctx.Context.Response.Headers[HeaderNames.CacheControl] =
                        "public,max-age=" + durationInSeconds;
                }
            });

**Comment by sebastienros** [comment]
I have defined default a few weeks ago. Are you using the latest version?

Also once we have a good configuration story (there is a PR ready) we'll pass these parameters by configuration.

**Comment by scleaver** [comment]
You are like reading my mind right now @sebastienros 

I think what you have done for now is great and to tell you the truth it will work for my needs in Orchard Core. Maybe someday we can add a UI for those that want to get crazy per tenant but actually what you have done will work for me.

I am a bit scared of those "SupportedSizes" restrictions though cause for my plans I need way more possibilities and specific sizes. I know something like this is needed for DDOS but I am wondering if there is a better way. The imagerizer guys have found a way to limit DDOS without limiting resizing options https://imageresizing.net/benefits/stable

**Comment by scleaver** [comment]
In a previous life, I was working on a solution for another application. What we ended up doing was having a bunch of tag helpers that generated a signature in the url that could only be created by the application for a specific set of resizing params. We also allowed the content editor to specify image resizes in the application which could then be used in the tag helpers by name. This was good actually because it modified the url of the image with the edition of the thumbnail name and meant that you avoided param caching issues when using CDNS

**Comment by jtkech** [comment]
Just to say that you will be able to change the default values in different config sources (e.g json files), to be applied to all tenants and / or for a given tenant if under a subsection whose name is the tenant name.

Not yet documented but all of these configs will need to be under a parent section named `OrchardCore`.

**Comment by marlon-tucker** [comment]
At the moment, the defaults for theme/module resources is a max-age of a year. As well as sending a version hash in an ETag header.

What are the chances of modifying the ResourceManagement module to render resource links with a version hash, so if the files are updated, the clients automatically cache-bust. On Chome, the max-age takes precedence over the ETag header, so a max-age of a year effectively makes the ETag irrelevant. 

By rendering a version hash, I mean something like this:

```
<script src="/ExampleModule/ExampleScript.js?v=FileHashHere" type="text/javascript"></script>
```

I understand the resource module has a concept of versions at the moment, but that concept is only generally useful for external/cdn resources as those tend to have versions embedded in the Uri. For locally built resources, having a hash would be ideal really.

**Comment by sebastienros** [comment]
Right now the mitigation is to introduce the version in the url itself like you are suggesting, even if it's your own script. Can you provide an example in our template that you can't redefine?

I am worried that if we rendered the hash dynamically we would have to compute it for every request. So maybe just updating the definitions themselves should be enough.

**Comment by marlon-tucker** [comment]
Ideally I don't want to have to define a version for the script, as its built when the module assembly is built, so effectively it's the same version as that assembly. 

The module has a `ResourceManifest` file which registers it's internal client-side code with Orchard's ResourceManager, as that takes care of managing dependencies for us etc.

Example:
```
manifest.DefineScript("SomeModuleCore")
                .SetDependencies("knockout", "tslib", "rxjs")
                .SetUrl("/SomeModule/build/SomeModuleCore.js")
                .SetVersion("1.0.0");
```

Our client side code is built using webpack, so we could have webpack append a version to the final output. But that would mean having to "search" the assemblies embedded resources to find the final filename that webpack generated before it was embedded into the assembly, then using that filename in the `SetUrl` method above. 

All that is entirely doable, just strikes me as a long winded process for something I would expect to be a common use case for client side code built as part of an Orchard module. 

You say you would have to generate the hash for every request, but I don't think this is the case. Embedded resources are not going to change throughout the applications lifetime, so it would be safe to use MemoryCache to cache the initial hash result. 

Orchard would need a way for the ResourceManager to determine if a resource is embedded into a module assembly though.

**Comment by marlon-tucker** [comment]
FYI we have been affected by this on the admin portal, the client side scripts are cached for a year, and going to RC1 meant clients hard to manually hard refresh the browser in order to get the correct admin scripts to be pulled down.

**Comment by deanmarcussen** [comment]
I think this issue is resolved, and can be closed.

For info @marlon-tucker we implemented cache busting.

You can turn it on all resources by default as a setting in the _admin -> configuration -> general_ where you can turn it on by default.

(it is on by default on new setups, but not on an old database)

The other part of the issue regarding setting cache headers also works with `IConfiguration` as I use it on my own site (and is documented)
