### ISSUE TITLE
Recommended WYSIWYG editor improvements

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#3049]
Using the WYSIWYG editor this week I had a few frustrations OOTB which I thought I would put up for consideration. I know I can override the OOTB but I feel these ones should be considered for the default behaviours:

1. The HtmlBodyPart cannot be given a specific label and hint text which is not great for content editors who may need some guidance as to what this field is used for. Instead, the field is just labelled "HtmlBody" with hint text is "The body of the content item". I know this makes sense for us but not the average Joe. IMHO would could default to these values but you should be able to set them via the UI to say "Main Content" or whatever makes sense for the implementation.

2. If possible the "formatting" button should be converted OOTB to a select input or similar which indicates the format applied to the area where the cursor currently is. To lay people the icon is not easily recognisable and it is frustrating to have to click the button to see which heading level etc the text being manipulated is currently set too (actually currently even after clicking the button you can't see what is being applied but it should be working this way).

3. The editor is crazy about the p tag. I know it is not good practice but not often, but occasionally, you just have to use a div with a class in the editor. I pasted some content with a class applied to a div and the editor converted it to a p tag. Likewise, I had to use a span for something as well and the editor would not allow me to have a span without p around it. Same with hr... I didn't want my hr to have a p around it but the editor refused to let me have a hr without a p around it - this changes the spacing etc. and is not necessary.

4. The editor hates i tags too. It's quite popular to use i tag with icons such as font-awesome... the editor converts these to em.

5. Last one is a suggestion - how cool would it be to take advantage of the Monaco Editor https://microsoft.github.io/monaco-editor/ used in Visual Studio Code to help people edit HTML with intellisense whenever a HTML field is plain HTML or the WYSIWYG editor is in "view HTML" mode.

**Comment by sebastienros** [comment]
We are thinking about using this editor instead as the default: https://github.com/OrchardCMS/OrchardCore/issues/2828

We can't use Monaco because it doesn't support mobile.

**Comment by sebastienros** [comment]
If you want to try and integrate the Slatejs editor, that could work. It should be easy to do by copy pasting what is done for the other ones.

**Comment by sebastienros** [comment]
I think it's a good idea to add a custom label and an hint for body parts (markdown and html).

**Comment by scleaver** [comment]
Could monaco be disabled when it detects a mobile device?

**Comment by cwojke** [comment]
Monaco seems great... and if it were an addition, not replacement, not supporting mobile shouldn't be an issue.

**Comment by pgy866** [comment]
Add a hint content text setting for all field types so that when you design a content type, you can add hints to the field to make it easier to add or edit content.

Or add a module as a setting property of the field type, enable and disable it at any time.

**Comment by scleaver** [comment]
I agre @pgy866 a hint on all fields AND the ability to set the field label for all fields alike is needed.

**Comment by sebastienros** [comment]
@scleaver @pgy866 unless I don't understand what you mean with you latest comments we already have a Hint and Display name proeprties that do exactly what you are asking for.
