### ISSUE TITLE
Unable to update content item title using XmlRpc

### ISSUE THREAD

**Issue by Erranaxx** [OrchardCMS/OrchardCore#3050]
Orchard Core does not correctly update the TitlePart when submitting changes via XmlRpc (such as Open Live Writer). The fix appears to be simply updating the DisplayText property after updating the Title in the TitleMetaWeblogDriver. This brings it inline with the TitlePartDisplayDriver where the DisplayText is also updated with changes to the title.

`contentItem.Alter<TitlePart>(x => x.Title = rpcStruct.Optional<string>("title"));`
`contentItem.DisplayText = rpcStruct.Optional<string>("title");`

I have a PR ready but do not have permission to publish branches.

**Comment by Skrypt** [comment]
The way to create a PR is to fork this repo in your account and to create a branch on your fork. Then you will be able to create a PR from your fork to this main repo.

**Comment by Erranaxx** [comment]
Thank you, I have submitted PR [#3051](https://github.com/OrchardCMS/OrchardCore/pull/3051)

**Comment by scleaver** [comment]
@Erranaxx this article is quite helpful: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by Erranaxx** [comment]
@scleaver Thank you! I'm a long time Orchard follower but this is the first time I have contributed (on GitHub for that matter). Any help is greatly appreciated.

Closing this issue as it can be tracked via PR [#3051](https://github.com/OrchardCMS/OrchardCore/pull/3051)
