### ISSUE TITLE
Login for docker image on docker hub

### ISSUE THREAD

**Issue by parlock** [OrchardCMS/OrchardCore#3056]
The docker image on docker hub didn't run through the setup.  So don't know what account/password to use to login to the image when I run it in docker.

**Comment by parlock** [comment]
The dev version of the docker image doesn't run the setup.  Its like it was already setup when it was made.  I tried the latest and it runs the setup, but I wanted to try the nightly dev too see the current.

**Comment by sebastienros** [comment]
Weird, we didn't change it. I will test it.

**Comment by sebastienros** [comment]
If you tried the linux image, it seems that it hasn't been built in a month. Apparently only the PRs got built on travis, I just fixed the settings, it will build a new image then I will test it again. The current image is broken because it can't find the mvc version.

**Comment by parlock** [comment]
In my case I was trying the Windows image for dev tag...

**Comment by sebastienros** [comment]
So there might still be an issue, I will confirm with the Linux image once it's built.

**Comment by sebastienros** [comment]
The new images are deployed now, can you try again?

**Comment by sebastienros** [comment]
I just tried an it's still not fixed, almost there though

**Comment by sebastienros** [comment]
Fixed!!!

**Comment by parlock** [comment]
Working for me. sorry it took time to get around to testing it again...
