### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rjamesnw** [OrchardCMS/OrchardCore#3065]
I don't see any place to change the menu to display a logo on the default template.  I can't even find the template file(s).  I looked under `App_Data` and sub-folders as well.

Edit: I got the gist that I can use "wwwroot/[module or theme name]/[resource file path]" to override the site files.  I'm guessing the files are embedded in the assemblies. If this is the case, I can probably get them from the source.  Is copying the template from the source to my local wwwroot folder the proper way to do it? I just want to edit the menu code as well.

**Comment by sebastienros** [comment]
This is done in the TheAdmin theme. You can create your own admin theme by copy-pasting it and changing it like you need. The long term goal is to make it customizable.

**Comment by rjamesnw** [comment]
Yeah, figured that out after, thanks. ;)
