### ISSUE TITLE
Date metadata on the main page

### ISSUE THREAD

**Issue by rjamesnw** [OrchardCMS/OrchardCore#3066]
Why on earth would there be a date/time stamp on a page content type on the main page?  A blog post perhaps, yes, but not a page.  How do I turn it off (using the TheThemeMachine template)? I tried creating a "parts" file to filter out the metadata but it doesn't work, and the documentation is lacking - there's no way to even know what the proper syntax for that would be from information scattered everywhere.

**Comment by awyl** [comment]
The easiest way is to disable the corresponding shape with a placement file.

https://orchardcore.readthedocs.io/en/dev/OrchardCore/OrchardCore.DisplayManagement/

**Comment by rjamesnw** [comment]
Thanks for the linked info - I’ll review it. So how would I find the part names in order to know what name to use?

**Comment by rjamesnw** [comment]
@sebastienros The date is on my page here: inossis.com (notice the date under the home tab, which should not be on a page content in my opinion.

**Comment by sebastienros** [comment]
It's a site on Orchard 1.
