### ISSUE TITLE
Can't set CreatedUtc with ContentManager

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3069]
While importing data with the contentManager when I try to set the CreatedUtc directly in code it get overriden by this line in the ContentsHandler. Commenting out this line fix the issue, but I'm questionning myself on why we are having this condition in the code. Maybe we could verify first that the CreatedUtc datetime == null if the intent was to provide a date when Creating + Publishing a content item for the first time.

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement/Handlers/ContentsHandler.cs#L68

**Comment by sebastienros** [comment]
Yes, if not we should also have an editor, we have it in O1 that is shown based on a per content type setting.

**Comment by Skrypt** [comment]
You mean the Datetime Picker to change the created date if we set on the content type settings to allow changing that value.

**Comment by agriffard** [comment]
Also related to this: #1121

**Comment by sebastienros** [comment]
Use the CommonPart
