### ISSUE TITLE
[Design] Indexing/Search

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#307]
Please share any concern, issue or comments about this feature. Or expose new scenarios that we should take into account.

My current plan is to take most of what is already done in O1. But I aslo want to remove the Search API abstractions and expose the Lucene API directly. It doesn't really make sense to create an abstraction layer that is totally tied to Lucene. This would mean that the Orchard.Search and Lucene modules will be merge into one called Orchard.Search.Lucene or something like this. The Indexing module should remain the same.

Related issues on O1:
- [Users needs to exclude elements in layouts from being indexed](https://github.com/OrchardCMS/Orchard/issues/6926)
- [Enhancing ISearchbuilder to accept array as value field](https://github.com/OrchardCMS/Orchard/issues/5764)
- [Lucene search indexes content of enumeration field separated](https://github.com/OrchardCMS/Orchard/issues/4095)
- [Search / Lucene Modules does not work with accentuated characters](https://github.com/OrchardCMS/Orchard/issues/3887)

Other concerns
- Security: it's a recurring request to filter the search results using the current logged user rights. (TODO: find the related issue on O1 which contains the recommended solution)
- Extensibility: if Indexing is the only reusable module (and maybe the search page), make it such that it can work with Elasticsearch and Azure Search.

/cc @DamienLaw @sfmskywalker @Piedone

**Comment by Piedone** [comment]
Security is a general concern about listing content items I think. Thus I'd cover it unrelated to search, probably in Projections (and at a lower level).

But related to Projections I'd add a Search filter, but this is done (just would add it to the core selection): https://github.com/Lombiq/Helpful-Extensions/blob/dev/Extensions/Projections/SearchFilter.cs

**Comment by sebastienros** [comment]
I already have included search scenarios and more in the Projection design notes I have locally and will share when dealing with it.

I think content filtering is specifically related to search too. At least the way it could be handled natively, not by doing too service calls, one to search for content, and one to filter (see paging issues). But the solution should be the same, which is to attach the list of roles that should be allowed to see the items, and when doing a query pass the roles of the target user to filter it too. The same way we filter on culture, we don't ask for all of them then ask for each content item what their culture is. This would be the same strategy for content item, store an index with roles allowed to see the content. There are implementation issues though, like content item permissions, or changing permissions which would mean reindex the items.

**Comment by sebastienros** [comment]
Another alternative for security, is to just have helper methods to handle filtered paging that would reissue queries (search and projections) when content has been filtered out. But this also means the page count and pagers couldn't be displayed correctly. I would say than in the case we want to apply security filter, then we could just forget about a paged pager, and just use a Prev/Next one.

**Comment by Jetski5822** [comment]
A few requests from me:

1 - Ability to use a different analyser and selecting that through the UI. The analyser should be a setting attached to the index.

2 - Luke.net embedded in to the UI

3 - an analyser is tokenizer + stemmer + stop-words filter. It would be awesome if some how we could have modules provide custom implementations of each one, then we use the UI to build a custom tokenizer.

**Comment by sebastienros** [comment]
You haven't looked at the module, right ? ;)

I made the analyzer a setting (it can't be changed for now as I am about to work on Settings UI).
There is an embedded Luke, because there isn't any for Lucene 4.8 format on .NET. See screenshot on Gitter.

If 3. is only about extending the available analyzers (as 1. already is supported) then yes, makes sense. Will do it at the same time as Settings implementation.

**Comment by agriffard** [comment]
@Piedone When the possibility to choose an analyser is done in O1, it would be interesting to have it in O2.

**Comment by Piedone** [comment]
It's done in O1, up in 1.10.x.
