### ISSUE TITLE
Localization file discovery format

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3070]
@Skrypt I saw the new different file format you added to discover the localization files.
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Localization/

We should add one matching the format exported by Crowdin which is:
`[filename]-[culture].po`
It would be similar to an existing one but with a `-` instead of a '.' to separate the culture  : 
`/App_Data/Localization/[ModuleId]-[CultureName].po`

**Comment by Skrypt** [comment]
Did we not change it already for "." ?

**Comment by agriffard** [comment]
OK, so it is the doc that is wrong:
`/App_Data/Localization/[ModuleId].[CultureName].po`

**Comment by sebastienros** [comment]
This is what @Skrypt is saying. The only thing saying otherwise is your issue comment.

**Comment by HengzheLi** [comment]
Does translation for DataAnnotation follow this discovery format?
