### ISSUE TITLE
Media modal not displayed when the editor is maximized

### ISSUE THREAD

**Issue by Loneve** [OrchardCMS/OrchardCore#3082]
![123](https://user-images.githubusercontent.com/44474195/51624891-cbf5db00-1f76-11e9-81f0-c110aa6fcb43.gif)
It's the same in edge,chrome and firefox

**Comment by Loneve** [comment]
in the TheAdmin.css 
![qq 20190124084245](https://user-images.githubusercontent.com/44474195/51646589-2b261080-1fb4-11e9-8a7e-551aa803fac2.png)
fixed it

**Comment by sebastienros** [comment]
@Skrypt says we should not have to override .modal. We'll need to look at when we introduced it so we don't break it when it's removed.
