### ISSUE TITLE
ContentStep doesn't update content when running deployment plan

### ISSUE THREAD

**Issue by ThisNetWorks** [OrchardCMS/OrchardCore#3089]
When running a deployment plan the content step doesn't update existing content.

The ContentStep code goes something like this

                var contentItem = token.ToObject<ContentItem>();

                var existing = await _contentManager.GetVersionAsync(contentItem.ContentItemVersionId);
                if (existing == null)
                {
                    // Initializes the Id as it could be interpreted as an updated object when added back to YesSql
                    contentItem.Id = 0;
                    await _contentManager.CreateAsync(contentItem);
                }
                else
                {
                    // Replaces the id to force the current item to be updated
                    //existing.Id = contentItem.Id;
                    //_session.Save(existing);
                }

It creates ok, but in the else, saves back the existing object (contentItem.Id is always null in my exports)
Changing to 
`await _contentManager.UpdateAsync(contentItem);`

updates the content item successfully. 

I haven't found much document on the recipe steps, are they intended to be a bit smarter and only update content if changed? or dates are greater, or are they intended to simply update all content?

**Comment by ThisNetWorks** [comment]
ah, I see one of the things going on here.

The content item in question isn't versioned, but the content step is based around versioned content.

**Comment by ThisNetWorks** [comment]
So after testing this further, and converting the document type in question to be versioned, the step is now succesfully importing the updated version of the content, but not marking the previous version as Latest:false, so the content lists now shows multiple versions.

**Comment by sebastienros** [comment]
Some reflection needs to happen here. Maybe the step needs to be more specific like "Update" or "Create" which would force a new version all the time. This is important for idempotency. Maybe based on the presence of `ContentItemId` and `ContentItemVersionId`. If `ContentItemVersionId` is provided it should just update the version, and if `ContentItemId` is provided then it would create a new version, and take the `Published` and `Latest` flags into account.

**Comment by sebastienros** [comment]
Though I don't think it should always create a new version ,and we should rely on a mandatory `ContentItemVersionId` to be sure that executing the step twice will create a single version.

**Comment by hishamco** [comment]
I will look to this after #1121 got fixed
