### ISSUE TITLE
dotnet publish errors when targetting win10-x64 runtime

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3097]
> D:\Dev\WEBCSCORE\Framework.Net\OrchardCore\src\OrchardCore.Cms.Web>dotnet publish OrchardCore.Cms.Web.csproj -r win10-x64 --configuration Release -o ./bin/publish

dotnet publish breaks with many errors NU1605 : 

`D:\Dev\WEBCSCORE\Framework.Net\OrchardCore\src\OrchardCore\OrchardCore.Users.Core\OrchardCore.Users.Core.csproj : error NU1605:  OrchardCore.Users.Core -> OrchardCore.Infrastructure -> OrchardCore -> OrchardCore.Abstractions -> ncrontab 3.3.0 -> System.Net.Primitives 4.0.11 -> System.Runtime.Handles (>= 4.0.1) [D:\Dev\WEBCSCORE\Framework.Net\OrchardCore\src\OrchardCore.Cms.Web\OrchardCore.Cms.Web.csproj]`

**Comment by sebastienros** [comment]
Note for myself: Also check that nuget packages based solutions export themes correctly.

**Comment by Skrypt** [comment]
No need to test Themes. The issue I had was that when published, a website Razor views takes precedence over Liquid views if you mix them in the same theme. Though when on dev the issue was not happening because of how Razor views are compiled.

**Comment by sebastienros** [comment]
This should be fixed when this PR is merged and shipped. In the meantime I will define specific references.
https://github.com/atifaziz/NCrontab/pull/45
