### ISSUE TITLE
WorkflowExecutionContext key value error.

### ISSUE THREAD

**Issue by justlucky** [OrchardCMS/OrchardCore#3100]
var workflowContextValue = context.GetValue(nameof(WorkflowExecutionContext));

It's Null

**Comment by sebastienros** [comment]
Can you provide some repro steps?

**Comment by justlucky** [comment]
var workflowContextValue = context.GetValue(nameof(WorkflowExecutionContext));

replace

var workflowContextValue = context.GetValue("Workflow");

**Comment by sebastienros** [comment]
Not "fix" steps, but "repro" steps, what should we do while using Orchard to experience a problem that is due to this line of code?
