### ISSUE TITLE
[GraphQL] Content Types Fields Predefined Lists

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3103]
When using a Text Field we can do Predefined List. It would be nice to be able to retrieve those lists by using GraphQL.

**Comment by sebastienros** [comment]
Will probably make sense with Taxonomies (or tags) as we'll be able to know it can only have specific values. For TextField the predefined values are just from a custom editor, which are hints for the editor not actual limitations.

**Comment by sebastienros** [comment]
Keeping the issue so we can think about it for Taxonomies

**Comment by Skrypt** [comment]
Closing as it makes more sense with Taxonomies.
