### ISSUE TITLE
Create Content Task: Lack of Setting DisplayText Operation

### ISSUE THREAD

**Issue by justlucky** [OrchardCMS/OrchardCore#3104]
Dear,

Workflow Module CreateContentTask

Lack of Setting DisplayText Operation

**Comment by sebastienros** [comment]
Repharsing: "No way to set the DisplayText from a Create Content task"

**Comment by jptissot** [comment]
I am setting DisplayText just fine in the Create Content Task like this : 

```
{
  "DisplayText": "{{ Workflow.Properties.formData.lastname }}, {{ Workflow.Properties.formData.firstname }}",
}
```
