### ISSUE TITLE
How is localization implemented when different content items, headings are displayed differently?

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#3105]
Different content items, the display of the title is different, orchard I remember can be implemented through localization, orchardcore How to achieve, sorry, I can not find an example, could you give an example? How do you write in PO?

Example：
New[ContentType]-Title[TitlePart]=>title[DisplayText]
Product[ContentType]-Title[TitlePart]=>Product Title[DisplayText]

.po?

**Comment by sebastienros** [comment]
Static texts use .po files. For content item we need to implement the "Content Localization" feature which has not started yet.
