### ISSUE TITLE
System.Resources.MissingManifestResourceException when password is invalid

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#3110]
```
Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "OrchardCore.Setup.Controllers.SetupController.resources" was correctly embedded or linked into assembly "OrchardCore.Setup" at compile time, or that all the satellite assemblies required are loadable and fully signed.
```

Not blocking, but we can see it if the debuger is enabled and intercepts exceptions.

**Comment by jtkech** [comment]
If i enable this exception to be intercepted, it happens everywhere we use a localizer. Enabling the localization module fix the issue.

Maybe we need some default services to be registered, i will dig into it tomorrow.

**Comment by jtkech** [comment]
For infos registering a default factory that returns a no op localizer fixes the issue.


        internal class NullStringLocalizer : IStringLocalizer
        {
            public LocalizedString this[string name]
                => new LocalizedString(name, name);

            public LocalizedString this[string name, params object[] arguments]
                => new LocalizedString(name, string.Format(name, arguments));

            public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
                => Enumerable.Empty<LocalizedString>();

            public IStringLocalizer WithCulture(CultureInfo culture)
                => new NullStringLocalizer();
        }

**Comment by jtkech** [comment]
I will check this asap

**Comment by jtkech** [comment]
@sebastienros 

1st, currently we do

            builder.AddViewLocalization();
            builder.AddDataAnnotationsLocalization();

Which could be done in one pass by using

            builder.AddMvcLocalization();

Then, we have the following

    `AddMvcLocalization()` => `AddDataAnnotationsLocalization()` => `AddLocalization()`.


But  `AddMvcLocalization()` is not called by default by mvc. But right now, if we remove it it fails because we use e.g `IViewLocalizer` in razor / liquid templates.

This is `AddLocalization()` that we also call directly at the app level  which registers the `ResourceManagerStringLocalizerFactory`.

**Comment by agriffard** [comment]
Is it still occuring @jtkech ?

**Comment by jtkech** [comment]
That's okay as we now register default null localizers
