### ISSUE TITLE
Document existing layer rules

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#3111]

**Comment by agriffard** [comment]
Suggestions:

- In Zones (/Admin/Settings/zones), add a link to explain that the zones will be listed and displayed in this order in Layers + link to /OrchardCore.Layers/Admin/Index.
- Add a link to the Layers documentation where we explain how to render a section in Razor and in Liquid.
- In Layers, explain where you can add Zones + link (especially if there are no zones defined).
- Add a link to the Layers documentation where we explain how to define Layers (Rule Condition, ...)

**Comment by agriffard** [comment]
Todo in https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Layers/
