### ISSUE TITLE
API module doesn't work properly inside Orchard Core

### ISSUE THREAD

**Issue by arsenikstiger** [OrchardCMS/OrchardCore#3114]
Hi,

I’m trying to create a multi-tenant modular API with OrchardCore.

I have problems with some actions which doesn't work.

I have a controller :
```
[Produces("application/json")]
public class CustomisationsController : Controller {...}
```
and some actions in it :
```
[HttpGet]
public async Task<IActionResult> GetAllAsync()

[HttpGet("{id:int")]
public async Task<IActionResult> GetAsync(int id)

[HttpGet, ActionName("Keywords")]
public async Task<IActionResult> GetAvailableKeywords()
```

The action GetAvailableKeywords works great with the ActionName attribute.

But actions GetAllAsync and GetAsync doesn’t work and returns 404.
I guess it’s because there is no ActionName but I don’t know what to put in it and I don’t really found how routing works inside Orchard Core.
I tried Route and ActionName attributes with some random values (string.Empty, “~/”) but it doesn’t work neither.

Why Orchard doesn’t match my routes : 
-	GET tenant/module/Customisations with GetAllAsync ?
-	GET tenant/module/Customisations/12 with GetAsync ?

How to get rid of ActionName("action") and use an easier HttpGet("action") as usual ?

Regards,

**Comment by sebastienros** [comment]
Have you tried custom `[Route]` attributes instead?

I think you will get the results you expect if your controller starts with `Api` which will trigger some default conventions to be applied.

**Comment by arsenikstiger** [comment]
Thanks for your reply.

I ever tried [Route] and [ApiController] attributes, without success.
With your answer I understand it is not a known limitation.

I will continue looking for a solution at this problem, because Orchard Core suits almost all my needs.

And so many french in the core team is a guaranty of quality :)

**Comment by arsenikstiger** [comment]
Hi,

After many hours spent trying to fix this problem, there is an evidence : OrchardCore has only been designed for building frontal web application.
I don't think it would be very difficult to make it a good choice for API, but the AddMVC method has to be changed :
- Don't force AddAntiforgeryToken for API methods
- Keep the API convention based routing

I will try to update the method myself and will post a PR I can make it working.

**Comment by sebastienros** [comment]
I think the convention you are looking for is applied when the controller begins with Api or when it has the ApiController attribute. I might be wrong though, will check.

**Comment by sebastienros** [comment]
Sorry, missed the comment where you said you had tried it already.

**Comment by sebastienros** [comment]
It works for me with this sample:

```c#
    [Produces("application/json")]
    [Route("api/custom")]
    public class CustomApiController : Controller
    {
        [HttpGet]
        public Task<string[]> GetAllAsync()
        {
            return Task.FromResult(new string[] { "a", "b", "c" });
        }


        [HttpGet("{id:int}")]
        public Task<string> GetAsync(int id)
        {
            return Task.FromResult($"Result: {id}");
        }
    }
```

Then I can request `/api/customapi` which returns the "only" GET method without arguments, and `/api/customapi/1`.

If I add another GET method without arguments it can't resolve which one to use.

**Comment by sebastienros** [comment]
And I could access these actions withou the `Route` attribute like this: `http://localhost:17458/OrchardCore.Mvc.HelloWorld/CustomApi/GetAllAsync`

**Comment by sebastienros** [comment]
For me everything works.

**Comment by arsenikstiger** [comment]
Thank you for these many responses !
I tried everything possible today, so I'm pretty sure of my problems.
First thing, I'm trying  to use it through a module area.
Second thing, I didn't try with api appearing in the controller name, but I will tomorrow.

I still think Orchard can be a marvellous base for back or front projects other than CMS.
It is only missing a real life sample, more than an only helloworld one.

Thanks again

**Comment by arsenikstiger** [comment]
I have created a sample repo to speak of the same thing together :
https://github.com/arsenikstiger/OrchardCore-samples

Maybe the problem lies into the StartupBase of Module.Api, where I can set a specific AreaRoute.
It's not clear if I need it or not, so I tried with and without it.

**Comment by sebastienros** [comment]
The area is needed for all routes.

**Comment by vkoman** [comment]
Hi All. Following your example from "**Module.Api**" module, how to access "**ValuesApiController**" and its **Get** or **Post** method? Because, when I launch this sample project on localhost and trying to navigate the method by URL, there is no result. What is the appropriate URL for it?

**Comment by sebastienros** [comment]
Can you read this guide on how to create a custom route in a custom module?  Does it solve the issue or do you need a custom guide for APIs? https://orchardcore.readthedocs.io/en/dev/docs/guides/create-modular-application-mvc/

**Comment by topdeveloper1001** [comment]
Hi @sebastienros 
I tried to custom api module to headless cms.
at first i added new module named CustomApi to my orchardcore cms.
i followed this guide. 
https://orchardcore.readthedocs.io/en/dev/docs/guides/create-modular-application-mvc/
but http://localhost:5000/CustomApi/Home/Index return "not found".
could you help me?
