### ISSUE TITLE
Setup: Take culture into account

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3117]
I create an OC instance (I test with the source code) with the Saas recipe, enable Localization, add fr-FR culture and select it in the settings, create src\OrchardCore.Cms.Web\App_Data\Localization and add OrchardCore.Admin-fr.po and OrchardCore.Setup-fr.po.

When I go to /admin, the strings are localized.

When I create a tenant and go to the setup, I expect that the strings are localized but they are not, even if I add in the querystring `&culture=fr-fr`

**Comment by sebastienros** [comment]
I assume this is because the Setup context doesn't enable localization by default. It's not using the modules enabled in the default tenant, so enabling the Localization module on the default tenant will have no effects. 

But sure we should find a way to get it to translate the Setup too.

**Comment by hishamco** [comment]
What if:

1. Enable localization module (by default)
2. Add a languages drop down list in the setup screen, so the user will be able to select the default language for the setup (such as DNN)
3. Disable the localization module (if it's needed)

**Comment by sebastienros** [comment]
We don't need to provide a drop down, it's a different option. We need the Localization feature to be enabled by default in the setup. We already enable Recipe and some others. Then the po files would be taken into account, based on the requested culture (cookie, request, ...).

Providing languages in a drop down list would make sense to define the default culture of the new tenant, which today is based on the default system culture. I am not saying it's not a good idea, but it's different than the current issue.

**Comment by hishamco** [comment]
I will try to investigate and do some work on this and see what can I come up with

**Comment by hishamco** [comment]
> Then the po files would be taken into account, based on the requested culture (cookie, request, ...).

By default the culture will be the default culture unless someone add a querystring or cookie to set the culture. Me as a user I don't think that I need to do such thing to localize the setup screen, but providing a drop down will be easier for all off us

I never ever seen any CMS that localize the setup screen using cookies, querystring .. etc, the only doable choice is HTTP header but again this need the user to set the appropriate culture in internet options dialog

let us think twice to provide a better an easy option for usability and accessibility for the CMS users

**Comment by hishamco** [comment]
Another thing that I forgot is how we can add the supported cultures?!! but for my suggestion we can the most request: Chinese, Spanish, Arabic, French along side with the English
