### ISSUE TITLE
Missing Admin Attribute

### ISSUE THREAD

**Issue by SpencerWaz** [OrchardCMS/OrchardCore#3123]
ExportFileController in the OrchardCore.Deployment module is missing the Admin attribute

**Comment by sebastienros** [comment]
Why do you think it's missing? Doesn't look like it's necessary to me

**Comment by SpencerWaz** [comment]
From what I understand, the Admin attribute will be applied automatically if the Controller name starts with Admin. If it doesn't, it seems necessary & convention to mark all controllers intended for the Admin Site with the Admin attribute. 

For my requirements, I'm required to use a custom cookie implementation, but it should only be used when the request is not intended for the Admin site however. 

So we use a filter to intercept the request and determine if the Admin attribute is applied.  The ExportFileController is the only instance I've came across so far that has caused us any issues. 

When I go to export my content, the custom cookie implementation is used.. resulting in a 401.

**Comment by sebastienros** [comment]
ok
