### ISSUE TITLE
Get a template content from code?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#3126]
I defined a Template under "Configuration / Templates", call it **myTemplate1**. the content in there is just simple HTML code.

Question: how to get those HTML code from a custom module? 

`        [HttpGet]
        public IActionResult Index()
        {
            var html = ????myTemplate1??
            return View();
        }`

Thanks!

**Comment by Skrypt** [comment]
Look at other OrchardCore.Demo module for examples. This is standard MVC design pattern that you should learn to work with first.

**Comment by orchardc** [comment]
Hi @Skrypt , thanks for your response. It's not about MVC design pattern, which I'm family with. My question is about which API/function should I call to get the Template content?

**Comment by orchardc** [comment]
OK, I found the solution, it's **TemplatesManager**. 

var templatesDocument = await _templatesManager.GetTemplatesDocumentAsync();
var template = templatesDocument.Templates.Where(x => x.Key.Equals("myTemplate1")).Select(x => x.Value.Content).FirstOrDefault();
