### ISSUE TITLE
Testing sql server concurrent writes

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#3128]
@sebastienros 

I was not able to repro the issue you showed to me when **editing and publishing** multiple `Article`.

 Then, when **creating** multiple `Article` in the same time, i got an issue in `IndexingTaskManager.Dispose()` => `FlushAsync()` => `transaction.Connection` is null. As you see in the below image, `Connection` is null but not `_connection` because `IsZombied = true` meaning that `_internalTransaction.IsCompleted`.

![sqldbtest1](https://user-images.githubusercontent.com/8586360/52160329-fdc41b80-26b3-11e9-85c3-449d696e72d7.png)

So, because `Connection` is null, it fails here in yessql.

        public static ISqlDialect For(DbConnection connection)
        {
            return For(connection.GetType());
        }

Then disabling lucene and indexing.

![sqldbtest2](https://user-images.githubusercontent.com/8586360/52160330-0288cf80-26b4-11e9-9d02-fa78b8eea6de.png)

Here it fails in `YesSql.Session.Dispose()` when doing `_transaction.Commit()` for the same `IsZombied` reason.

---

When creating an item we **redirect to the editing** of this item.

- A first workaround was to not redirect to the editing but the index page.

- Then doing a `_session.CommitAsync()` just before redirecting to the editing also fix the issue.

**Comment by jtkech** [comment]
@sebastienros 

- I was not able to repro with concurrent **edits**, only with concurrent **creates**.

- I had already tried **without the indexing feature**, it still fails see the 2nd screenhost. The exception is just thrown in another place but for the same reason that the transaction `IsZombied` meaning that its inner transaction has already completed.

- In the trace of #3130 there are also exceptions thrown by `SqlTransaction.ZombieCheck()`.

Just for infos because i didn't search yet more in depth.

**Comment by sebastienros** [comment]
I already started to work on it. The issue should be that the flush happens in the disposal, but the session itself might already be disposed. I am now deferring the Index tasks creation and using a different db connection.

**Comment by sebastienros** [comment]
This should be easy to understand why. Like addi g some log when the session is disposed. Worst case by referencing yessql source code and placing more logging. I will try to repro.

**Comment by jtkech** [comment]
It seems that we can use (through a pooled session) a zombied transaction which is not null but completed.

I don't know enough yessql so not sure, but maybe because when we commit the session we would have to also release the transaction and set it to null.

I will try to copy yessql source code to be able to change things for testing.
