### ISSUE TITLE
ListContentItems Permissions Error

### ISSUE THREAD

**Issue by justlucky** [OrchardCMS/OrchardCore#3129]
Hello

Contents Module AdminController
    GetListableTypesAsync method

var authorized = await _authorizationService.AuthorizeAsync(User, Permissions.EditContent, await _contentManager.NewAsync(ctd.Name));

It should be replaced by

var authorized = await _authorizationService.AuthorizeAsync(User, Permissions.ViewContent, await _contentManager.NewAsync(ctd.Name));

How to Authorize Content Types and Specific Contents

**Comment by Skrypt** [comment]
duplicate
