### ISSUE TITLE
The model item passed into the dictionary is of type 'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel', but this dictionary requires a model item of type 'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel'.

### ISSUE THREAD

**Issue by deepak0418** [OrchardCMS/OrchardCore#3135]
I am getting the below error in Ocrhard CMS v.1.8.1.0 while creating the new articles.

### The model item passed into the dictionary is of type 'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel', but this dictionary requires a model item of type 'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel'.

**Source File:** \xyz.xyz.com\orchard\Live\CMS\Modules\Orchard.News\Views\Content.Edit.cshtml
Line: 16

**Source Error at Line 16:**

```
Line 14:         @if (Model.Content != null) {
Line 15:             <div class="edit-item-content">
Line 16:                 @Display(Model.Content)
Line 17:             </div>
Line 18:         }
```

**Scenario:**

Currently We have 2 webservers example Web01 and Web02, both servers are using the same code from common network location (\xyz.xyz.com\orchard\Live\CMS\Modules), One webserver that is Web02 everything is working fine but in another webserver Web01 I am unable to create new article.

**Note:** I can login into the CMS application I can explorer the CMS application but problem only while creating the New Articles.

**Creating the New Articles URL:**

http://Web**01**:5014/Admin/Contents/Create/FundswireArticle -- Getting error

http://Web**02**:5014/Admin/Contents/Create/FundswireArticle -- Working fine

I have added the error screenshot as below ![cms---](https://user-images.githubusercontent.com/41731743/52195336-76c29f00-287d-11e9-8481-12eee6705a9e.JPG)

If you see the error message

dictionary is of type **'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel'** and dictionary requires a model item of type **'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel'** both are same.

**'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel' 'Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel'**

Code is below for Content.Edit.cshtml Page:

```
@using Orchard.ContentManagement
@using Orchard.Core.Contents;


@Html.Partial("Content.SubmitButtons.OrchardNews")

<div class="edit-item">
    <div class="edit-item-primary">
        @if (Model.Content != null) {
            <div class="edit-item-content">
                @Display(Model.Content)
            </div>
        }
    </div>
</div>
```

Below code for **Contrib.ChoiceList.cshtml** page override from Orchard **Contrib.ChoiceList** model to my custom module.

```
@model Contrib.ChoiceList.ViewModels.ChoiceListFieldViewModel
@using System.Web.Mvc
@using FluentNHibernate.Utils
@using Orchard.Utility.Extensions;
@using SelectListItem = System.Web.WebPages.Html.SelectListItem
@{
    //this template override hides the choice list field if there's only single option specified
    var shouldDisplayField = !string.IsNullOrEmpty(Model.Options) && Model.Options.Split(';').Length > 1;
}

<fieldset style="display: @(shouldDisplayField ? "block":"none")">
    <legend>@Model.Name</legend>

    @if( Model.ListMode == "radio" )
    {
        foreach (var option in Model.Options.Split(';'))
        {
            if( string.IsNullOrWhiteSpace(option) )
            {
                <label>@Html.RadioButton("SelectedValue", "", string.IsNullOrWhiteSpace(Model.SelectedValue))<i>unset</i></label>

            }
            else
            {
                <label>@Html.RadioButton("SelectedValue", option, (option == Model.SelectedValue))@option</label>
            }
        }
    }
    else if (Model.ListMode == "dropdown")
    {
        var optionSplits = Model.Options.Split(';');
        var displayNameSplits = Model.DisplayNames.Split(';');

        var items = new List<SelectListItem>();
        for (int i = 0; i < optionSplits.Count(); i++)
        {
            var item = new SelectListItem {Text = displayNameSplits[i], Value = optionSplits[i]};
            items.Add(item);
        }

        @Html.DropDownListFor(m => m.SelectedValue, new SelectList(items, "Value", "Text",  Model.SelectedValue));
        @Html.ValidationMessageFor(m=>m.SelectedValue)
    }
    else if (Model.ListMode == "listBoxes")
    {
        var optionSplits = Model.Options.Split(';');
        var displayNameSplits = Model.DisplayNames.Split(';');
        var selectedValues = Model.SelectedValue == null ? string.Empty : Model.SelectedValue;
        Model.SelectedValues = selectedValues.Split(';').ToList();
        var items = new List<SelectListItem>();
        for (int i = 0; i < optionSplits.Count(); i++)
        {
            var item = new SelectListItem {Text = displayNameSplits[i], Value = optionSplits[i]};
            items.Add(item);
        }

        @Html.ListBoxFor(x => Model.SelectedValues, new SelectList(items, "Value", "Text", Model.SelectedValue), new { Multiple = "multiple" });
    }
</fieldset>
```

Please help. Thanks in advanced.

**Comment by Skrypt** [comment]
I think you submitted this issue in the wrong place. This is for 01. I can't see any issue in the code you posted by looking quickly. This looks like an issue with the ViewModel binding itself. Maybe you have the same ViewModel twice in your code or referencing the same ViewModel from a different project. That's my first guest, else I don't know just by looking at this.

**Comment by deepak0418** [comment]
> I think you submitted this issue in the wrong place. This is for 01. I can't see any issue in the code you posted by looking quickly. This looks like an issue with the ViewModel binding itself. Maybe you have the same ViewModel twice in your code or referencing the same ViewModel from a different project. That's my first guest, else I don't know just by looking at this.


Hi Skrypt,
Thanks for your time, I fixed the issue now.

As i mentioned we are using common code location for all webservers, problem was in common location(network location).
We were using FQDN (fully qualified domain name), now changed to sort name and it started.

\xyz.xyz.com\orchard\Live\CMS\Modules - FQDN (before we were using)
\xyz\orchard\Live\CMS\Modules - Sort (Now we are using)
