### ISSUE TITLE
Implementing a widget which has a collection in its settings?

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#3144]
Hi all,

I'm not super familiar with the in's and out's of Orchard so I'm looking for guidance.

We want to implement a Widget which has a collection attached to its backing ContentPart. In the past we have had to fudge it a bit by limiting the Edit shape to a fixed number of rows and using some client side javascript to hide / show the table rows as needed.

I was wondering if there was a better way this could be achieved.

I had a quick look around the issue log here and found #2480 but I am unsure if it's related or not.

Any help would be greatly appreciated.

**Comment by sebastienros** [comment]
You can already create types that behave as collection, using the Bag Part for instance. Then if you want to be able to limit the number of elements you could create a custom editor (there are many examples for fields already), and copy paste the current editor but customize it with your settings. Another option is to add settings to the Bap part directly, to improve it, I assume that could be part of the default settings.

Even better, show us what you want to do, it's not really obvious from your description.

**Comment by marlon-tucker** [comment]
The widget will show a collection of items, and each item requires it's own set of parameters defining how the items behave. Then the widget itself has top level settings which define how the widget behaves.

An example ContentPart class def would be

```
public class WidgetSettingsPart : ContentPart 
{
    public string TopLevelSetting1 { get; set; }
    public string TopLevelSetting2 { get; set; }

    public List<WidgetItemSettings> Items { get; set; }
}
```

My main question is how can I get a nice UI for the editing of the widget settings, ideally with add/remove buttons for the `List<WidgetItemSettings>` collection. Would a Bag Part be able to accomplish this?

My usual goto method would be to implement something in knockout (or another client side framework) but as the data is sent down using standard MVC views which expect data to be submitted using standard forms, using correct prefixes and such, it makes that a somewhat tricky proposition.

**Comment by marlon-tucker** [comment]
Hi, 

I have experimented a little with the BagPart, it looks like it'll do what I want. 

I have used a FlowPart in the past, and that has a nice functionality in that it displays the child item's Title in the widget editors container header in the admin page. The BagPart doesn't look like it has this functionality enabled. Ideally I need this behavior as it makes using the admin page a lot easier for users, they don't have to expand each item in the BagPart to see which item it is etc.

Looking at the code, it seems FlowPart expects Widgets, which as a Stereotype means they are guaranteed to have TitleParts. But for the BagPart, it just has a list of ContentTypes so I expect it can't infer the child has a TitlePart attached to it.

Is there anything I can do to enable this functionality?

**Comment by sebastienros** [comment]
You don't need to rely on the TitlePart, use the `DisplayText` property of the content item, they all have one. The TitlePart is here to let you edit this value.

**Comment by marlon-tucker** [comment]
I added a TitlePart to the Content Item which went inside the BagPart, but
when that was edited in the admin side when say editing a page etc., that
didn't update the container title like it does for a FlowPart?

**Comment by sebastienros** [comment]
Please file another issue for the display text which should be render in the header of a bagpart.
