### ISSUE TITLE
Describe in IShapeTableProvider not hit when rendering Shape from Liquid

### ISSUE THREAD

**Issue by jan-chvojka** [OrchardCMS/OrchardCore#3145]
When I create a liquid Template in Admin named **TestShape** with code:
```
TEST {{ Model.A }}
```
and try to render it in another liquid template **Content__LandingPage** of clean AgencyTheme with:
```
{% assign test = "TestShape" | shape_new %}
{{ test | shape_render }}
{% shape "TestShape" %}
```
It ignores code defined in IShapeTableProvider like **OnProcessing** or **OnDisplaying**. Its not hit in debug and A is not set.

```
            builder.Describe("TestShape")
                .OnProcessing(ctx =>
                {
                    var a = 1;
                    ctx.Shape.A = a;
                });

            builder.Describe("TestShape")
                .OnDisplaying(ctx =>
                {
                    var a = 2;
                    ctx.Shape.A = a;
                });
```

I repro with source, commit _c0d998fb9ebed0d8a58d10d44392f1c565a4fc72_, AgencyTheme and SqlLite.

I din't create a module, just used Discover method of OrchardCore.Menu.MenuShapes. Describe works on `builder.Describe("MenuItem")` and its hit so it's not caused by the concrete IShapeTableProvider.

**Comment by jtkech** [comment]
It's a known "issue", as i remember (i copy pasted a part of my comment in #2631).

- `TemplatesShapeBindingResolver.BuildShapeBinding()` create an incomplete `ShapeDescriptor`, so some of its events, e.g `DisplayingAsync()` or `ProcessingAsync()`, may not be called.
