### ISSUE TITLE
Find Liquid JSON paths with Queries best practice usage

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3147]
Add documentation on how we should use SQL Queries to prevent SQL injection by using @parameters. Also show some examples with the usage of a LIKE.

```Liquid
{% assign typeFilter = Request.Query.ContentType | append: "%" %}
{% assign fiveBlogPosts = Queries.ContentByType | query: contentType: typeFilter, limit: 5 %}

{% for item in fiveBlogPosts %}
{{ item | display_text }}
{% endfor %}
```

```SQL
SELECT DocumentId FROM ContentItemIndex WHERE ContentType LIKE @contentType
```

This method also prevent parameters from getting UrlEncoded.

**Comment by aghili371** [comment]
i add a field to get a picture of blog post called 'logo'.

how can i access this image?

`{% assign recentBlogPosts = Queries.RecentBlogPosts | query %}
<div class="row">
{% for item in recentBlogPosts %}
  <div class="col-md-4">
    <a href="{{ item | display_url }}">
       <img class="img-fluid" src="{{ item.logo.Paths.first  | resize_url: width:480, height: 480, mode: 'stretch' }}" alt="{{ item.DisplayText }}">
      <h2>{{ item | display_text }}</h2>
    </a>
   </div>
{% endfor %}
  
  </div>`

**Comment by Skrypt** [comment]
`<img class="img-fluid" src="{{ item.logo.Paths.first | asset_url | resize_url: width:480, height: 480, mode: 'stretch' }}" alt="{{ item.DisplayText }}" /> `

**Comment by aghili371** [comment]
`< img class="img-fluid" src="/media/?&amp;width=480&amp;height=480&amp;rmode=stretch" alt="titletest" >`

i have this element in render page.

**Comment by Skrypt** [comment]
Try `item.logo.Paths[0]`

**Comment by aghili371** [comment]
it is same as item.logo.Paths.first and doesn't show the image.

**Comment by Skrypt** [comment]
Have your tried to see the actual JSON data by doing simply {{ item }} on your Liquid template? Maybe you need to do item.Content.Paths.first. I don't know from where you are doing this. First thing is to actually find a way to display all the JSON data in your page to get all the values that are available.

**Comment by aghili371** [comment]
i create liquid page and set this code :
 
```
{% assign recentBlogPosts = Queries.RecentBlogPosts | query %}
<div class="row">
{% for item in recentBlogPosts %}
   <div class="col-md-4">
     {{ item.Content }} 
       </div>
  <div class="col-md-4">
     
    <a href="{{ item | display_url }}">
     <img class="img-fluid" src="{{ item.Content.logo.Paths.first | asset_url | resize_url: width:480, height: 480, mode: 'stretch' }}" alt="{{ item.DisplayText }}" />
      <h2>{{ item | display_text }}</h2>
    </a>
   </div>
{% endfor %}
  
  </div>
```


i can access JSON data by  {{ item.Content }} .

```
     {
  "BlogPost": {
    "Subtitle": {
      "Text": "test sub"
    },
    "logo": {
      "Paths": [
        "about/3.jpg"
      ]
    },
    "tags": {
      "ContentItemIds": [
        "4xa5g1aegj4fxzxa7z4zagwpmy",
        "4xwdh5zv58h5dzvqx09zhsxvw8",
        "481m44rc65wza4zktww9enb0de"
      ]
    },
    "led": {
      "Html": "لید خبر"
    }
  },
  "AutoroutePart": {
    "Path": "blog/نوجوانان-کیا-خبر",
    "SetHomepage": false
  },
  "MarkdownBodyPart": {
    "Markdown": "متن"
  },
  "TitlePart": {
    "Title": "نوجوانان کیا خلاصه سال"
  },
  "HtmlBodyPart": {
    "Html": "متن بهتر خبر"
  },
  "ContainedPart": {
    "ListContentItemId": "47fye5798c8ct00kk5prbdn54q",
    "Order": 0
  }
}
```

**Comment by Skrypt** [comment]
And this is still not working?

**Comment by aghili371** [comment]
no, it doesn't work.

**Comment by Skrypt** [comment]
Does it still give you no path at all in the resulting src? I'm trying to figure out which part doesn't work. To me what you have should work. If you remove the resize_url and asset_url?

**Comment by aghili371** [comment]
i tested all: 
```
     <img class="img-fluid" src="{{ item.Content.logo.Paths.first | asset_url | resize_url: width:480, height: 480, mode: 'stretch' }}" alt="{{ item.DisplayText }}" />
     <img class="img-fluid" src="{{ item.Content.logo.Paths.first | resize_url: width:480, height: 480, mode: 'stretch' }}" alt="{{ item.DisplayText }}" />
     <img class="img-fluid" src="{{ item.Content.logo.Paths.first | asset_url }}" alt="{{ item.DisplayText }}" />
     <img class="img-fluid" src="{{ item.Content.logo.Paths.Paths[0] | asset_url | resize_url: width:480, height: 480, mode: 'stretch' }}" alt="{{ item.DisplayText }}" />
     <img class="img-fluid" src="{{ item.logo.Paths.Paths[0] | resize_url: width:480, height: 480, mode: 'stretch' }}" alt="{{ item.DisplayText }}" />
     <img class="img-fluid" src="{{ item.logo.Paths.Paths[0] | asset_url }}" alt="{{ item.DisplayText }}" />
    
```

```

<a href="/blog/نوجوانان-کیا-خبر">
     <img class="img-fluid" src="/media/?&amp;width=480&amp;height=480&amp;rmode=stretch" alt="نوجوانان کیا خلاصه سال">
     <img class="img-fluid" src="?&amp;width=480&amp;height=480&amp;rmode=stretch" alt="نوجوانان کیا خلاصه سال">
     <img class="img-fluid" src="/media/" alt="نوجوانان کیا خلاصه سال">
     <img class="img-fluid" src="/media/?&amp;width=480&amp;height=480&amp;rmode=stretch" alt="نوجوانان کیا خلاصه سال">
     <img class="img-fluid" src="?&amp;width=480&amp;height=480&amp;rmode=stretch" alt="نوجوانان کیا خلاصه سال">
     <img class="img-fluid" src="/media/" alt="نوجوانان کیا خلاصه سال">
     
    </a>
```

**Comment by sebastienros** [comment]
`item.Content.BlogPost.logo.Paths.first`

Look at your json,the field in on the BlogPost property

**Comment by aghili371** [comment]
@sebastienros thank's it works now.

**Comment by Skrypt** [comment]
https://jsoneditoronline.org/?id=2204f2903f09482db559ae987d178ead
Use this to find your JSON paths.

**Comment by aghili371** [comment]
@Skrypt  thank you very much.

**Comment by sebastienros** [comment]
@Skrypt can you create a new issue and close this one, this has been hijacked by a side conversation.
