### ISSUE TITLE
multi-level image galley

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3150]
in i asked about multi-level galery #2605 .

i need a multi-level image galley, how can I develop this in orchard core?
fo example in need to have a galley for football matches:
germany> bundesliga> byenmunich> game1 >>>list images

@sebastienros you gave me this solution :
What I would do:

* Create a Team content type. It can have a title, it could have a list of players, a logo, ...
* Create a Championship content type which will represent the competitions (League1, Cup, Coupe de France, ...)
* A Team has a Content Item Picker of Championships
* Create a Championships taxonomy, which will define a hierarchy of Leagues/Championship(3 levels), select the championship content type for this taxonomy.
* Create a Match content type, which has two picker fields to select the home team and guest team, and add a Media Picker field for the images.

how can show the site map?  it's important for me to show the sitemap in every page for this grouping level. 
how can i show TAXONOMY?

**Comment by sebastienros** [comment]
"Team" content type
"Championship" content type with a Country property.
"Game" content type with a reference to Team, Championship and Media Field.

Create a custom controller and view.
