### ISSUE TITLE
ContentTypePartDefinitionBuilder.WithSettings<T>(...) puts settings in the wrong position

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#3153]
Hi,

Using `1.0.0-beta3-70622`

I've been experimenting with building a ContentPartDefinition with a `BagPart` attached to it using the `IContentDefinitionManager` interface. However when using the following syntax:

```
            _contentDefinitionManager.AlterTypeDefinition(_lettingsApplicationsWidgetContentTypeName, builder => builder
                .WithPart(nameof(LettingApplicationsWidgetSettingsPart), part => part
                    .WithDisplayName("Property Applications Widget Settings"))
                .WithPart("BagPart", part => part
                    .WithSettings(new BagPartSettings {  ContainedContentTypes = new [] { _lettingsApplicationSlotContentTypeName }}))
                .Stereotype("Widget"));
```

The resulting structure for the `BagPart` is this:
```
                {
                    "PartName": "BagPart",
                    "Name": "BagPart",
                    "Settings": {
                        "DisplayName": "Displayed Applications",
                        "BagPartSettings": {
                            "ContainedContentTypes": [
                                "360LettingApplicationSlot"
                            ]
                        }
                    }
                }
```

Note `BagPartSettings` has been put inside the `Settings` structure. This results in Orchard not seeing these settings, and when I manually go in and edit the ContentType and save it, this is the structure Orchard saves:

```
                {
                    "PartName": "BagPart",
                    "Name": "BagPart",
                    "Settings": {
                        "DisplayName": "Displayed Applications",
                        "BagPartSettings": {
                            "ContainedContentTypes": [
                                "360LettingApplicationSlot"
                            ]
                        },
                        "Description": "Provides a collection behavior for your content item.",
                        "Editor": null,
                        "ContainedContentTypes": [
                            "360LettingApplicationSlot"
                        ],
                        "DisplayType": null,
                        "Position": "1"
                    }
                }
```

So it is expecting those settings to live inside the `Settings` structure.

**Comment by sebastienros** [comment]
We should fix it an move it to the `"Settings"` property like you did in the first example. It also means we'll need to migrate the current settings with a migration step.

It's a bigger issue than just the BagPart: https://github.com/OrchardCMS/OrchardCore/issues/1134

**Comment by marlon-tucker** [comment]
Yes I believe putting the ContentPart's custom settings into a sub property under the Orchard Settings property is the right move as it separates user defined settings from Orchard's system side settings, so it avoids the possibility of the user defining a setting which has the same name as one of Orchard's system settings, e.g. `Position` etc.

To this end, I would put the part's settings underneath another property which Orchard knows about, as with the way it currently works, if someone saves a settings class which happens to be named `Position`, it'll still cause a conflict within Orchard.

For example, I advice something like this:
```
    {
        "PartName": "BagPart",
        "Name": "BagPart",
        "Settings": {
            "DisplayName": "Displayed Applications",
            "PartSettings": {
                "BagPartSettings": {
                    "ContainedContentTypes": [
                        "360LettingApplicationSlot"
                    ]
                }
            }
        }
    }
``` 

That way Orchard is in full control and there's no chance of accidental property name conflicts.

**Comment by barthamark** [comment]
@sebastienros I agree with @marlon-tucker that moving specific settings to a sub-property is better choice since there is a chance that different part settings will have the properties with a same name at some point.

Other issue is that currently handling these are inconsistent in Orchard Core, for example AutoroutePart merges their settings properties to the root Settings object, AliasPart will use sub-property. Because of this inconsistency you won't know how to add settings from migrations unless you dig into the source code to find out which one will work for a ContentPartSettings.
Also we should find a preferred way of doing these so custom modules will follow that. Currently we prefer the sub-property solution (`.WithSettings<T>()`).

**Comment by sebastienros** [comment]
There is an issue open for this "migration", can you find it?
If we migrate to custom properties (with the help of the helper method) then we also need to create a migration to move the existing values to this other property, in a custom migration probably.

**Comment by sebastienros** [comment]
Oh, it's already linked in a previous comment.
