### ISSUE TITLE
ContentTypes within a BagPart which have a TitlePart do not update the container headers in the Admin UI

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#3161]
Using `1.0.0-beta3-70622`

If you have a ContentType which has a BagPart attached to it, and in that BagPart you have another ContentType which has a TitlePart attached to it. The Admin UI for the BagPart does not update the container titles for the contained ContentTypes belonging to the BagPart collection.

See image:

![image](https://user-images.githubusercontent.com/1166915/52477142-ce704b80-2b98-11e9-891a-1861e25dd578.png)

Oddly they seem to just render a series of dashes as the container header.

**Comment by marlon-tucker** [comment]
Just to add, when you Save/Publish the ContentType, the Titles are correctly displayed on the headers.

So the bug is just them dynamically updating when they are edited.

**Comment by sebastienros** [comment]
By design for now, so putting it in backlog.

**Comment by ns8482e** [comment]
@marlon-tucker did you try on dev?

**Comment by marlon-tucker** [comment]
Not recently no, does this now work for you @ns8482e ?

**Comment by Piedone** [comment]
They do update the headers now.
