### ISSUE TITLE
Configure default file size limit for media

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#3163]
By default the requests can't exceed 30MB. We need to create a custom filter for the Media/Upload action that will reset it to a configurable value, by copying this filter: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/RequestSizeLimitAttribute.cs

Then create a `MediaOption` class that will contain the max file size. The default value will be the one from aspnet. It will allow to set it by appsettings, or by code. This will also allow to add more settings, like the allowed file extensions.

**Comment by sebastienros** [comment]
@matiasmolleja if you feel like you have too much free time, it's yours ;)

**Comment by matiasmolleja** [comment]
Just wondering if it's really necessary a filter for this.
Can't we check for each IFormFile.Length property here?
https://github.com/OrchardCMS/OrchardCore/blob/af70ffc5ba99679f77121a830e620c72f9c5f3d0/src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs#L137

**Comment by sebastienros** [comment]
No, it's blocked before it reaches the action.
