### ISSUE TITLE
Implement Liquid money filters

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3166]
https://help.shopify.com/en/themes/liquid/filters/money-filters
https://help.shopify.com/en/manual/payments/currency-formatting

**Comment by hishamco** [comment]
@sebastienros can we implement this at Fluid level or OrchardCore level?

**Comment by sebastienros** [comment]
I am ok with adding these in fluid, as long as they are in a specific set of classes, are opt-in (AddShopifyMoneyFilters()) and have their own test sets.

**Comment by Skrypt** [comment]
Should we create a MoneyShapes.cs in OC.DisplayManagement so that we can format double ou decimals to currency values based on the CultureInfo.CurrentUICulture ?

**Comment by Skrypt** [comment]
Update on this?

**Comment by Skrypt** [comment]
Should be a setting since currencies need to be converted. $10 USD is not equal to 10$ CAD for example. So the culture affects the way a number or currency is displayed but it is not relevant to rely on the current culture to display a proper price because of exchange rates. Displaying a price as 10$ could also add more confusion than anything. The code I did there is relevant only if we are displaying prices with a single currency so this is not the appropriate implementation. We probably should check on OrchardCore.Commerce currency implementation and rely on it for this.

@bleroy

**Comment by Skrypt** [comment]
Closing as it should be moved to Fluid repo
