### ISSUE TITLE
asp-append-version="true" does not work in theme files

### ISSUE THREAD

**Issue by ThisNetWorks** [OrchardCMS/OrchardCore#3169]
the mvc tag helper asp-append-version doesn't work in templates, because the helper relies on the HostingEnvironment.WebRootFileProvider (which is the .cms project) - refer mvc issue https://github.com/aspnet/Mvc/issues/7459

This limits our ability to reference theme static files (css / js) in the layout files and cache bust them with asp-append-version

The workaround suggested works in terms of getting a version hash, but breaks in delivering the file, as the routing no longer works
```
var compositeProvider = new CompositeFileProvider(_env.WebRootFileProvider, new PhysicalFileProvider(Path.Combine("path-to-theme", "wwwroot")));
_env.WebRootFileProvider = compositeProvider;
var options = new StaticFileOptions()
{
    FileProvider = compositeProvider,
    RequestPath = "/ThemeName/"
};
app.UseStaticFiles(options);
```
I suspect adapting ModuleEmbeddedStaticFileProvider might work however that has other implications.

Do we need to have a customised version of asp-append-version to provide cache busting for theme (and media files)

**Comment by cocoke** [comment]
Hello, 
I need to use the ``asp-append-version`` feature in my custom admin theme css but I didn't succeed, file version never appeared. 

Can you explain how did you make it work ?

**Comment by dodyg** [comment]
`asp-append-version` doesn't work at the simplest orchard core module usage. Here's an example.

https://github.com/dodyg/practical-aspnetcore/tree/master/projects/orchard-core/static-files

**Comment by jtkech** [comment]
there is a pending PR #3169 that will be merged after beta3.

**Comment by deanmarcussen** [comment]
This can close now from PR https://github.com/OrchardCMS/OrchardCore/pull/3581
