### ISSUE TITLE
Suggestion: Liquid Cheat Sheet

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/OrchardCore#3170]
It would be great to provide a page like/based on https://www.shopify.com/partners/shopify-cheat-sheet 
with orchard specific tags. This would be helpful with OrchardCore.Commerce also.

**Comment by sebastienros** [comment]
Also related;
http://sebastienros.github.io/CheatSheet/

**Comment by hishamco** [comment]
I think this issue need to be closed

**Comment by sebastienros** [comment]
> I think this issue need to be closed

no, I don't see anything that solved it

**Comment by hishamco** [comment]
What about the CheatSheet that you created

**Comment by sebastienros** [comment]
It's orchard 1

**Comment by hishamco** [comment]
OMG seems I was out of coverage 😁

**Comment by agriffard** [comment]
https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/
