### ISSUE TITLE
create  Conditionalis field ,

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3171]
it's possible to create a condition for loading data in adding a field?
i want to just call special data in any content.

 for example, i have a group and teams related to the group. so I want to have two dropdowns and by selecting a group, just showing the related teams in the second drop down.

**Comment by sebastienros** [comment]
You can try the Taxonomy module that lets you create some hierarchies of content items and select them with a taxonomy field.

On you can use a Text Field with the Predefined editor, where you would put options grouped together. You can also create a custom editor for a text field, or for a content picker field depending on the type of data you are modeling.

**Comment by aghili371** [comment]
i can't use taxonomy.it's not clear for me, do you have better help for me?

**Comment by sebastienros** [comment]
Create a type A.
Enable the taxonomy module.
Create a new Taxonomy, and configure it to have content type A
Add terms to the taxonomy
Add a Taxonomy Field to another type, select the taxonomy you created.
