### ISSUE TITLE
Highlight a field in bag part sub-item on failed validation

### ISSUE THREAD

**Issue by inhumator** [OrchardCMS/OrchardCore#3176]
Is it possible to highlight a missing required field in a subitem of a bag part ?

From what I found, the ModelState does contain a field key with guid prefix, but those prefixes seem to get regenerated on reload and can't be used to display validation message.

**Comment by ns8482e** [comment]
I guess should be fixed with PR #5989 and #5653  
/cc @deanmarcussen

**Comment by Piedone** [comment]
Should be fixed now.
