### ISSUE TITLE
Why is the OrchardCore.Environment.Shell.Abstractions not update in myget since 5 months ago??

### ISSUE THREAD

**Issue by davidxchen** [OrchardCMS/OrchardCore#3180]
Current main version in myget is 1.0.0-beta3-70668 which updated 2 days ago. However, this OrchardCore.Environment.Shell.Abstractions is still 1.0.0-beta3-68605.

**Comment by awyl** [comment]
I believe it has been consolidated into OrchardCore.Abstractions.
https://github.com/OrchardCMS/OrchardCore/pull/2199

**Comment by sebastienros** [comment]
Correct answer.
