### ISSUE TITLE
 error NU1101: Unable to find package OrchardCore.ProjectTemplates.

### ISSUE THREAD

**Issue by nigel-dewar** [OrchardCMS/OrchardCore#3182]
Hi, following the instructions here https://orchardcore.readthedocs.io/en/dev/docs/templates/
I install the template dotnet new -i OrchardCore.ProjectTemplates::1.0.0-beta3-*

but..... does not work

 Restoring packages for C:\Users\ndewar\.templateengine\dotnetcli\v2.1.503\scratch\restore.csproj...
C:\Users\ndewar\.templateengine\dotnetcli\v2.1.503\scratch\restore.csproj : error NU1101: Unable to find package OrchardCore.ProjectTemplates. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder, Microsoft Visual Studio Offline Packages, nuget.org
  Generating MSBuild file C:\Users\ndewar\.templateengine\dotnetcli\v2.1.503\scratch\obj\restore.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\ndewar\.templateengine\dotnetcli\v2.1.503\scratch\obj\restore.csproj.nuget.g.targets.
  Restore failed in 1.31 sec for C:\Users\ndewar\.templateengine\dotnetcli\v2.1.503\scratch\restore.csproj.

Is the documentation out of date or are the install templates broken?

Cheers

**Comment by sebastienros** [comment]
you need .NET Core 2.2

I tried this and it worked:

```
dotnet new -i OrchardCore.ProjectTemplates::1.0.0-beta3-* --nuget-source https://www.myget.org/F/orchardcore-preview/api/v3/index.json

dotnet new occms -o myproject

cd myproject

dotnet run
```

**Comment by nigel-dewar** [comment]
Thank you.

**Comment by nfarrell** [comment]
Worked for me, not sure if it was deliberately installing the [.net 2.2 runtime](https://dotnet.microsoft.com/download/dotnet-core/2.2) or just copy and pasting @sebastienros snippet above, but did both and worked as expected 👍
