### ISSUE TITLE
IndexingTask Table Not Correct in IndexingTaskManager Code

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#3183]
I believe there was a recent change in OrchardCore.Indexing.Services.IndexingTaskManager.cs and I am now receiving the following error (I removed a lot of the extra code):

```
An error occurred while creating an index System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'OrchardCoreLWCIndexingTask'.
...
   at OrchardCore.Indexing.Services.IndexingTaskManager.GetIndexingTasksAsync(Int32 afterTaskId, Int32 count) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Indexing\IndexingTaskManager.cs:line 182
```

To reproduce, just go add a new Lucene Index and it should throw the above error. The actual table name should not be 'OrchardCoreLWCIndexingTask', instead it should be 'OrchardCoreLWC_IndexingTask' so it looks it is just not adding in the '_'.

**Comment by TFleury** [comment]
Same issue in `FlushAsync` static method.

**Comment by sebastienros** [comment]
It would be fixed now
