### ISSUE TITLE
access data of content field picker to many content types

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3188]
i added tags field to get multi-content items.i defined that by content field picker to many content types. how can i access these tags and show title and linked to any item items?

i can access the id of these items by this code:
`{{ Model.ContentItem.Content.BlogPost.tags}}`

but i need to have list and loop to access full data of any item which the code is in this list exist.

please give me a solution to set loop and condition to find a type of an item to set different design and link.

```
{
  "BlogPost": {
    "Subtitle": {
      "Text": "test sub"
    },
    "logo": {
      "Paths": [
        "89/nonahalan/kia-steghlal/970824-12832-40-0636.jpg"
      ]
    },
    "tags": {
      "ContentItemIds": [
        "4xa5g1aegj4fxzxa7z4zagwpmy",
        "4xwdh5zv58h5dzvqx09zhsxvw8",
        "481m44rc65wza4zktww9enb0de"
      ]
    },
    "led": {
      "Html": "لید خبر"
    }
  },
  "AutoroutePart": {
    "Path": "blog/نوجوانان-کیا-خبر",
    "SetHomepage": false
  },
  "TitlePart": {
    "Title": "نوجوانان کیا خلاصه سال"
  },
  "HtmlBodyPart": {
    "Html": "متن بهتر خبر"
  },
  "ContainedPart": {
    "ListContentItemId": "47fye5798c8ct00kk5prbdn54q",
    "Order": 0
  }
}
```

**Comment by sebastienros** [comment]
This is explained i the documentation here: https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Contents/

Please do not create issues for general questions, you can ask questions on the Gitter chat. Thanks.
