### ISSUE TITLE
Code generation template octheme is outdated

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#3196]
Code generation template for theme is outdated.
- Theme.recipe.json references removed parts and module. Running the recipe out of the box creates a crashing instance (empty site, and the admin is unusable).
- Layout file references missing files (favicon.ico, sticky-footer-navbar.css)

**Comment by TFleury** [comment]
For discussion :
- base recipe could be simpler (just a "Page" ContentType)
- use Razor instead of liquid (or a mix like in Module template)
- provide a css/js pipeline

**Comment by Skrypt** [comment]
I tried mixing Liquid and Razor views in my theme and in dev/debug mode it works but once published the Razor files will be taking precendence over the Liquid templates. Need to test again. If you want to try let me know what's your results when publishing as self contained.
