### ISSUE TITLE
PluralFormNotFoundException

### ISSUE THREAD

**Issue by jan-chvojka** [OrchardCMS/OrchardCore#3201]
I have my own .po files which cover some basic stuff in admin. It's not complete but it's sufficient for my usage. I updated to the latest version 3b7bb2a85cdb3bdb4b789d3d3e4a2f9153413af8 and now I get errors in Admin / Content Item List.

```
Plural form '2' doesn't exist in values provided by the IStringLocalizer.Plural method. Provided values: System.String[]
```
I checked the code and I don't see any reason for throwing an exception. Don't know if it's a bug or if it's intentional, but not having a pluralized translations should not matter. Now I need to have explicit translations for pluralized strings or to face random errors.

**Comment by sebastienros** [comment]
Can you provide a repro?

It looks like it should only happen when `.Plural` is called. 
Maybe a Log would be better in this case?

/cc @lukaskabrt

**Comment by DSMaslov** [comment]
Hello, I have the same error. I debug and found, that error in class DateTimeShapes.cs

When call plural form of time (example:)
`if (time.TotalSeconds > 60)
`
`return H.Plural(time.Minutes, "1 minute ago", "{0} minutes ago");
`

to arguments parameter transfer 2 form, but Plural process 3 form (1, less 5, great 5) and so exception throws.

**Comment by sebastienros** [comment]
Thanks @DSMaslov for the repro, will try it asap.
