### ISSUE TITLE
when count is -1,0 condition in english and others same plual rule return plure,In my opinion return single means better

### ISSUE THREAD

**Issue by liaozhiwen06** [OrchardCMS/OrchardCore#3203]
I think is may means better when count is in -1,0.it return single.
I use below to solve my problem.

I'm beginner so the code is not well ,some one could retfactor it

 //fixed the bug for 0 and -1 conditions which would return plual
        
                if (count > 0 || count < -1)
                {
                    return ViewLocalizerExtensions.Plural(localizer, count, singular, plural, arguments);
                }

                else
                {
                    if (arguments == null)
                    { return localizer[singular, count]; }

                    else
                    {
                        int argumentsCount = arguments.Length;

                        object[] newArguments = new object[argumentsCount + 1];

                        //add count to the new arguments
                        newArguments[0] = count;

                        //append arguments to new argumets
                        for (int i = 0; i < argumentsCount; i++)
                        {
                            newArguments[i + 1] = arguments[i];
                        }
                        return localizer[singular, newArguments];
                    }

                }

**Comment by Piedone** [comment]
I don't think we'll do this.
