### ISSUE TITLE
Cannot specify the location of the X.509 certificate store and it's name using recipes

### ISSUE THREAD

**Issue by domonkosgabor** [OrchardCMS/OrchardCore#3205]
When providing the Open ID Server Setting using a recipe file, you can have a section like this:
```
{
      "name": "OpenIdServerSettings",
      "EnableTokenEndpoint": true,
      "AllowClientCredentialsFlow": true
},
```
When importing a recipe, the [OpenIdServerSettingsStep](https://github.com/OrchardCMS/OrchardCore/blob/32a277a5bb8acd24d0714d1165ecd615ab03b312/src/OrchardCore.Modules/OrchardCore.OpenId/Recipes/OpenIdServerSettingsStep.cs#L31) handler will execute the context and creates a model using the `OpenIdServerSettingsStepModel` POCO.
In this POCO, the `CertificateStoreLocation` and `CertificateStoreName` properties are enums, therefore you have to set the certificate store location to CurrentUser or to LocalMachine.
Let's say you do not want to work with certificates. Then you can set the certificate store location to None using the dashboard, but you cannot do that using a recipe, like:
```
{
      "name": "OpenIdServerSettings",
      "CertificateStoreLocation": null,
      "CertificateStoreName": null
},
```
because you will get an exception:

> ArgumentNullException: Value cannot be null.
Parameter name: value
System.Enum.ToObject(Type enumType, object value)
JsonSerializationException: Error converting value {null} to type 'System.Security.Cryptography.X509Certificates.StoreLocation'. Path 'CertificateStoreLocation', line 165, position 38.

If you haven't provide any value for them, the auto-property initializers will take action and add a value to these.

**Comment by sebastienros** [comment]
@PinpointTownes  ?

**Comment by PinpointTownes** [comment]
Let's make them nullable and remove the default values. @domonkosgabor would you be interested in fixing that by sending a PR? That would be much appreciated 👏

**Comment by domonkosgabor** [comment]
Yes, I could fix that. But I am quite busy nowadays, so I think I could start to work on this at the end of next week. If someone would like to fix this sooner, feel free.

**Comment by sebastienros** [comment]
beta3 or rc ?

**Comment by PinpointTownes** [comment]
It sounds fairly easy to fix, AFAICT, so maybe it's a good candidate for beta3.

**Comment by santoshyadav198613** [comment]
Hi @PinpointTownes ,

Let me take care, looks like an easy fix, first time contributor here.

**Comment by PinpointTownes** [comment]
@santoshyadav198613 I can't "formally" assign it to you because you're not the original poster but it's all yours!

> first time contributor here.

Thanks for contributing. Let us know if you have any question.

**Comment by santoshyadav198613** [comment]
Hi @PinpointTownes ,
If i am not wrong we have to make below 2 properties nullable.

"CertificateStoreLocation": null,
"CertificateStoreName": null

Please confirm.
