### ISSUE TITLE
View not found for ViewComponent

### ISSUE THREAD

**Issue by kamikyo** [OrchardCMS/OrchardCore#3208]
This issue is different #1274
The final error message is：
```
A view component named 'XXXX' could not be found. 
A view component must be a public non-abstract class, not contain any generic parameters, 
and either be decorated with 'ViewComponentAttribute' or have a class name ending with the 'ViewComponent' suffix. 
A view component must not be decorated with 'NonViewComponentAttribute'.
```
**Reproduce:**

- ModuleA
_/ModuleA/Home/Index.cshtml_:
```
<ul>
    <li>@await Component.InvokeAsync("Profile")</li>
    <li>@await Component.InvokeAsync("Another")</li> <!--this line of code will throw an error-->
</ul>
```
_ProfileViewComponent.cs_:
```
public class ProfileViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return Content("ProfileViewComponent");
    }
}
```

- ModuleB
 _AnotherViewCompoent.cs_:
```
public class AnotherViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return Content("AnotherViewComponent");
    }
}
```

This exception will appear in 1.0.0-beta3-70681,70701,70710,70714,70715.
**But in 1.0.0-beta3-69568, everything's fine.**
So I suspect all the 1.0.0-beta3-7xxx have such a problem.

**Comment by sebastienros** [comment]
@jtkech ?

**Comment by jtkech** [comment]
Just tried, it works on my side.

![component1](https://user-images.githubusercontent.com/8586360/53207289-a3bfd180-3633-11e9-8bbf-757f814fb03f.png)

![component2](https://user-images.githubusercontent.com/8586360/53207308-ab7f7600-3633-11e9-843f-068536b8d968.png)

![component3](https://user-images.githubusercontent.com/8586360/53207329-b20ded80-3633-11e9-9d08-27b89be219ac.png)

Try to rebuild your modules, check the names, check that **both modules are enabled**.

**Comment by kamikyo** [comment]
@jtkech Thank you very much for taking time out of your busy schedule to help me.
Yes,you are right.
**The ModuleB was disabled**,when I change it enabled, the code worked very well.
The version 1.0.0-beta3-69568 does not need to be enable ModuleB to run normally.
Therefore, I did not notice this detail in the 1.0.0-beta3-7xxx version.
I'm sorry to waste your time.
