### ISSUE TITLE
Handle UnauthorizedResult

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#3209]
When trying to access an unauthorized ContentItem in front-end, `ItemController` returns an `UnauthorizedResult`.

Until there, it's correct. However, UnauthorizedResult is treated as any other error and an error message is returned : "An error occured while executing this request." leaving us thinking there is a bug.

What's the expected behavior ? Should we redirect to authentication page (if not already authenticated) or at least return a dedicated message (like "You are not authorized to view this content.")

**Comment by TFleury** [comment]
Use cases :
#### Allow only authenticated users to view content
- Remove 'View all content' permission for 'Anonymous'
- Browse as anonymous

Current behavior : Error message "An error occured while executing this request."
With PR : You are redirected to Login
#### Send a preview link to a collaborator
- Create a draft content
- Browse preview URL as anonymous

Current behavior : Error message "An error occured while executing this request."
With PR : You are redirected to Login. If account don't have 'Preview content' permission, error message "You are not authorized to view this content."

**Comment by TFleury** [comment]
@sebastienros could we fix that for beta3 ?
It just needs a decision on the expected behavior (redirect all or only unauthanticated users ?)

**Comment by sebastienros** [comment]
We need to replace all occurrences of `return Unauthorized();` by `return User.Identity.IsAuthenticated ? Forbid() : Challenge();`.

We can also make an extension method on `Controller` to simplify it.

**Comment by sebastienros** [comment]
Note that sometimes we really need to send a 401 directly.

**Comment by MatthijsKrempel** [comment]
By all, you mean Orchard Core ALL, or you mean the ones related to ContentItems?
