### ISSUE TITLE
Allow theming for Login/Registration/ResetPassword

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#3212]
Since #2371 Login/Registration/ResetPassword Controllers use Admin theme for headless/themeless usages.
This implies creating an admin theme if you need to customize those pages.

Proposal :
- Move `[Login|Registration|ResetPassword]Controller` to `Base[Login|Registration|ResetPassword]Controller` as abstract controllers.
- Inherit those controllers for site usages as `[Login|Registration|ResetPassword]Controller` without `AdminAttribute` => uses site theme and view overrides.
- Inherit those controllers for admin usages as `Admin[Login|Registration|ResetPassword]Controller` with `AdminAttribute` => uses admin theme.

We also have to find a way to redirect `/login` route to the right controller depending if there is an active site theme or not.

**Comment by sebastienros** [comment]
The reason is that for an "empty" site without themes, you would not be able to authenticate.
But I acknowledge this is a concern. Can I suggest we create a feature that would force the login controllers to use the front-end theme instead?

**Comment by sebastienros** [comment]
It should be as easy as creating another `IThemeSelector` that would force the front-end one for these controllers.

**Comment by TFleury** [comment]
It would be a better/simpler solution 👍

**Comment by Skrypt** [comment]
I need that now 🤓

**Comment by TFleury** [comment]
Having a setting to prevent users to change their password could be a good idea. Should I make a different PR for that ?

Use case : same account shared by multiple users.
