### ISSUE TITLE
Create module for page and social metadata

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#3213]
Page and social metadata is important for SEO and enabling web pages to be rich objects in social graphs. Orchard Core needs a module that allows metadata to be associated with content items.

I have started work on this module.

Here is a record of the minimum set but the solution should allow for additional metadata fields to be added:
https://gist.github.com/scleaver/90e0a27fdaffb42f00e7a7d214b84cbd

**Comment by scleaver** [comment]
Pull request #3214

**Comment by sebastienros** [comment]
In your example there are metadata that could be set on each content item, and some that are global to the site. Should the module provide management for both, as a Part for content items, and as Settings for the global ones?

**Comment by sebastienros** [comment]
I see twitter-specific values. What about instagram, pinterest, facebook, ... anything else? Should these be coming from specific features instead that would extend the default SEO part?

**Comment by Piedone** [comment]
This is now covered by the SEO module.
