### ISSUE TITLE
Sitemap & Robots generation/management

### ISSUE THREAD

**Issue by ThisNetWorks** [OrchardCMS/OrchardCore#3219]
Does the OrchardCore community want sitemap & robots (and other seo related functionality as part of the core project?

I put some work in last weekend on a module loosely inspired by the IDeliverable Seo O1 module, and currently have support for robots.txt management through settings, and automatic sitemap generation.

If community would like it in as part of core project I'll wrap it into a pull request and we can get some more features in it?

**Comment by Skrypt** [comment]
You could sync with @scleaver to see if you guys are not doing the same thing and take the best of both PR into 1.

**Comment by sebastienros** [comment]
He did

**Comment by ThisNetWorks** [comment]
I need to sync further with @scleaver on the meta - which I've not done much with yet, but we have covered some of the same areas.

I think Sitemap and Robots should probably go in as independant modules
