### ISSUE TITLE
got error use mvc and cms 

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3220]
I want to add a new controller but I got an error.
after I set   .AddMvc(); i got this error.

```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms()
                 .AddMvc();
        }
```

```
InvalidOperationException: The partial view '/Areas/KiaTheme/Views/Content-page.cshtml' was not found. The following locations were searched:
/Areas/KiaTheme/Views/Content-page.cshtml
```

i need to create new pages for register with extra fields. what i should do? it's better to create new 
 Modules or you have other solutions?

**Comment by aghili371** [comment]
please, if anybody could help me. i need to improve my application.

**Comment by sebastienros** [comment]
Don't call AddMvc, just add the controller to your project. AddOrchardCms already adds MVC.
