### ISSUE TITLE
Add a dynamic adjustment tab setting box, for example: I want 15 tenants to paginate

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#3225]
Pagination also added to this page when you have more than 10 tenants.
Add a dynamic adjustment tab setting box, for example: I want 15 tenants to paginate。
And, jump to the "number of pages" input box。
Will it be better?
当您有超过10个租户时，分页也会添加到此页面。
添加一个动态调整分页的设置框，比如：我要15个租户分页。
以及，跳转到“第几页”的输入框。
会不会更好呢？
![image](https://user-images.githubusercontent.com/28694676/53253417-2744f580-36fc-11e9-8a63-56ccdc5f53b2.png)

![image](https://user-images.githubusercontent.com/28694676/53253883-35474600-36fd-11e9-8dc2-f8a31761c3e3.png)

**Comment by agriffard** [comment]
See Pager PageSize #5744
