### ISSUE TITLE
Blazor theme

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#3239]
Is there any example of creating blazor theme for orchard core?

**Comment by sebastienros** [comment]
I am not aware of any attempt to do some Blazor development with Orchard so far. Are you talking about Razor Components?

**Comment by dodyg** [comment]
I don't think Razor Component (or Server Side Blazor) can be implemented in Orchard at the moment. It will require upgrade to ASP.NET Core 3.0 and Orchard Core Framework doesn't work on ASP.NET Core 3.0 (AFAIK - I've tried and failed to make it work)

**Comment by sebastienros** [comment]
@dodyg there is a PR started to migrate to 3.0, but there are too many moving pieces right now to support it. Hopefully when it's "go live". And last week they introduced other breaking changes that will ship in next preview.

**Comment by dodyg** [comment]
Yeah ASP.NET Core 3 is still in a raging changes phase. 

I am trying right now to just port the "Orchard Core Framework" part of Orchard

- OrchardCore
- OrchardCore.Abstractions
- OrchardCore.DisplayManagement.Abstractions
- OrchardCore.Mvc.Core

and currently stuck on this issue
https://github.com/aspnet/AspNetCore/issues/8678#issuecomment-479580878

**Comment by sebastienros** [comment]
Then you were correct to follow up with the PR that JT created

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/2966

**Comment by hishamco** [comment]
I will close this for now according to the Seb comment [here](https://github.com/OrchardCMS/OrchardCore/issues/2966#issuecomment-598386167)
