### ISSUE TITLE
 Media Library： about non-image media 

### ISSUE THREAD

**Issue by Loneve** [OrchardCMS/OrchardCore#3240]
1. Currently, when you upload non-image files, the media list looks like this:
![default](https://user-images.githubusercontent.com/44474195/53457539-b2601b80-3a6d-11e9-8d6b-96f3264ad8b7.png)

Is it possible to display the default icon?

2. When inserting media in the Wysywig Editor, currently only `<img>` tag are generated, and tags like `<a>` should be generated.

**Comment by pgy866** [comment]
Very good if you support custom file formats and default icon settings。
That will allow you to customize any of your own file formats and thumbnails.

**Comment by sebastienros** [comment]
If the file content type is an image we can use the `img` tag otherwise we should use an icon,
