### ISSUE TITLE
Menu and Media dependencies on OrchardCore.Title

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/OrchardCore#3243]
Is there a reason for the dependency on OrchardCore.Title in OrchardCore.Menu and OrchardCore.Media ... i can see menu uses it in its recipe though im not entirely sure why :| cant see that media uses it at all, is this a hangover ?

Trying to stop titlepart getting added in a seriously cut down recipe i have ... Media is probably the one causing the issue but wonder if menu really needs it too ?

Happy to provide a pr if we dont think its required.

**Comment by sebastienros** [comment]
When you edit a menu you can change its title, hence it's here.

**Comment by sebastienros** [comment]
Can be removed from Media safely I think

**Comment by carlwoodhouse** [comment]
Ok. That makes sense! The menu I found the reference to it in so figured as
much, couldn’t see any in media other then the dependency
