### ISSUE TITLE
Module compiled views not always being served in dev

### ISSUE THREAD

**Issue by mcapewell** [OrchardCMS/OrchardCore#3244]
I think the following line breaks any views that are brought into a project via NuGet:

https://github.com/OrchardCMS/OrchardCore/blob/1fb1e46fc2cafdc1b6df20d12d5cf95a9949c068/src/OrchardCore/OrchardCore.Mvc.Core/ShellViewFeatureProvider.cs#L51

So the project is indeed running in development mode, but both the file system ("local" views) and the module compiled views (NuGet module views) must be served.

**Comment by jtkech** [comment]
Yes, but view contents are also embedded in the module assembly, so through a package we can still serve them to be compiled once at runtime.

**Comment by mcapewell** [comment]
Hi @jtkech, thanks for your reply but I'm not sure I understand what is going on. Which code serves the embedded views from the module assemblies whilst in development mode? I'm sorry if I'm missing something and getting confused, but it isn't working for me.

**Comment by jtkech** [comment]
No worries ;)

> Which code serves the embedded views from the module assemblies whilst in development mode?

The custom `ModuleEmbeddedFileProvider` that we compose with the content root provider.

            env.ContentRootFileProvider = new CompositeFileProvider(
                new ModuleEmbeddedFileProvider(appContext),
                env.ContentRootFileProvider);

> but it isn't working for me.

Many people make apps that reference the cms as a package and start them from VS in debug mode.

So, i need more infos, is the referenced package an OC module, your custom module or maybe another library which doesn't embed any view contents? If it is a custom module, can you check its project file, maybe some item groups exclude some razor views ...

**Comment by mcapewell** [comment]
Thank you very much for the information. I now understand how it is all working.

I'm working with a custom module which I have now got working! So I'm happy to report the OrchardCore code seems to be working correctly.

Thanks for all your help.
