### ISSUE TITLE
OpenId :it is return Unauthorized when use Access Token to get userinfo, why??????

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#3251]
![_20190301010922](https://user-images.githubusercontent.com/4881282/53584672-180fed00-3bbf-11e9-9d75-21c1951fd7b2.png)
![_20190301010952](https://user-images.githubusercontent.com/4881282/53584684-1e9e6480-3bbf-11e9-9b71-69084cc2822d.png)
![_20190301011056](https://user-images.githubusercontent.com/4881282/53584690-22ca8200-3bbf-11e9-9b66-12571dc212b5.png)
why?
why?
why?

**Comment by sebastienros** [comment]
Have you enabled the Token Validation module?

![image](https://user-images.githubusercontent.com/1165805/53606195-d5bebf80-3b6e-11e9-9c03-e12b0e647555.png)

**Comment by PinpointTownes** [comment]
The error returned as part of the `WWW-Authenticate` response header indicates it's an issuer validation error. Did you do anything special WRT to routing or did you configure an explicit authority in the OIDC server settings?

Here's the code responsible of validating the issuer when you don't configure an explicit authority in the OIDC server: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs#L167-L181

**Comment by Skrypt** [comment]
I can repro this locally on the Macbook

**Comment by PinpointTownes** [comment]
Did we change anything in the routing stuff recently?

@Skrypt did you have a chance to put a breakpoint in the issuer validator to confirm it's indeed what's causing the issue?

**Comment by Skrypt** [comment]
If you have time call me on Skype.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/53610768-15e76780-3b9a-11e9-9b62-6494dd6df1a4.png)

![image](https://user-images.githubusercontent.com/3228637/53610757-0bc56900-3b9a-11e9-8a22-477ea51624c7.png)

![image](https://user-images.githubusercontent.com/3228637/53610743-fb14f300-3b99-11e9-81d3-9033e2213d1e.png)

![image](https://user-images.githubusercontent.com/3228637/53610728-f2242180-3b99-11e9-85fa-68b166ad51fc.png)

**Comment by Skrypt** [comment]
Is it just me doing something wrong?

**Comment by mmdqq** [comment]
![qq 20190301112624](https://user-images.githubusercontent.com/4881282/53614444-fe00f980-3c14-11e9-8b6e-6496614777ed.png)
![qq 20190301112634](https://user-images.githubusercontent.com/4881282/53614447-01948080-3c15-11e9-8396-367841565f12.png)
![qq 20190301112654](https://user-images.githubusercontent.com/4881282/53614451-03f6da80-3c15-11e9-9d77-9b851d1e744f.png)
![qq 20190301112545](https://user-images.githubusercontent.com/4881282/53614465-0a855200-3c15-11e9-93cd-548e7964f61e.png)
it still showme invalid_token

**Comment by PinpointTownes** [comment]
I’ll take a look later today.

**Comment by PinpointTownes** [comment]
I identified the root cause. It’s a configuration issue: the OP didn’t add a trailing slash at the end of its authority. Yet, the server component uses Uri, which normalized the address and adds a /. The JWT handler doesn’t and uses simple string comparison, which causes the issue.

**Comment by sebastienros** [comment]
Happened to me yesterday, and I almost changed the hint to show that, on all the videos we had I didn't have to set the /. Do you suggest we should handle these correctly, or just add an example. At first I wanted to render what would be this url based on the current request, but got lazy.

**Comment by PinpointTownes** [comment]
Yeah, we should handle that. The fix is quite simple: we should use `System.Uri` everywhere, in both the client, server and validation settings. I've prepared a PR for that and @Skrypt will torture it for me 😅

**Comment by mmdqq** [comment]
It's Ok，thanks all of you ,i can continue to complete my program.
![qq 20190302225121](https://user-images.githubusercontent.com/4881282/53683648-4b2cba80-3d3e-11e9-9867-b0aa713366b2.png)
![qq 20190302225209](https://user-images.githubusercontent.com/4881282/53683652-54b62280-3d3e-11e9-8c7b-61a51a7df553.png)
