### ISSUE TITLE
[GraphQl] Query the contentitem of a contentpicker field doesnt expose all fields/parts

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#3252]
Considering the following simple contenttypes
**Person**
- Name field, text
- Favorite Movies, content picker for Movie type

**Movie**
- Name field, text
- Release Year, text

When issuing the query
```
{
  person {
    name
    favoriteMovies { 
      contentItems {
        name
      }
    }
  }
}
```

The error is:
```
Cannot query field \"name\" on type \"ContentItem\".
```

Would it be hard to make sure we can query on the actual type the content picker returns?

**Comment by psijkof** [comment]
With fragments it seems to be that I can work around this issue, if it is in fact an issue.

**Comment by sebastienros** [comment]
It's by design, I remember now. We can't know what is the type of the linked item, so you have to project it to a known one).

Would be cool to have some doc about it though.

**Comment by psijkof** [comment]
Thought so
