### ISSUE TITLE
Add nightly builds download page for Orachra Core

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#3257]
Orachra Core is slowly becoming very powerful, but we have some users (non-developers) who can experience the latest OrchardCore.Cms without installing VS and other huge developer software, only for using CMS and other functions.
Would you like to build a page like "http://nightly.odoo.com/" for Orachra Core and publish the OrchardCore.Cms.Web distribution every day. Orachra Core nightly builds.

**Comment by sebastienros** [comment]
We already publish Orchard on Docker Hub, and you can also use https://try.orchardproject.net. It's also on myget.

**Comment by pgy866** [comment]
thank you very much!
I found this.
The command line build speed is very amazing, and the release speed in VS is too slow. unbearable



Command line
Install the latest versions (current) for both Runtime and SDK of .NET Core from this page https://www.microsoft.com/net/download/core
Navigate to D:\OrchardCore\src\OrchardCore.Cms.Web or wherever your respective folder is on the command line in Administrator mode.

run：
Call dotnet run. 
Then open the http://localhost:5000 URL in your browser.


publish
Call dotnet publish.
Then open the D:\OrchardCore\src\OrchardCore.Cms.Web\bin\Debug\netcoreapp2.2\publish

**Comment by Skrypt** [comment]
Yes dotnet run on published folder is always faster than when debugging with VS. Though the trick is to try to not using full source code when using VS if you can. Then it will just need to compile your custom modules/themes and load precompiled OC from nuget/myget. This is why we always recommend to not use full source code unless you really need it.
