### ISSUE TITLE
IThemeSelector samples or docs

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#3260]
Are there any docs or samples for IThemeSelector?
Especially about login/register/reset password templating

**Comment by Skrypt** [comment]
There's a PR that just been merged. Look at site settings to enable it.

**Comment by petedavis** [comment]
Specifically for the login pages etc, there are two options. 

1. Create an admin theme that is based on the default admin theme so you can override the public facing templates in the new admin theme and inherit everything else.
1. Override them in the site theme you are using and then enable the new setting in the admin, and keep the default admin theme. 
![image](https://user-images.githubusercontent.com/164331/53691000-6393e800-3dc5-11e9-840a-1d764370c5a6.png)
