### ISSUE TITLE
[Menu] LinkMenuItemPart is not registered

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#3276]
`menu.recipe.json` registers `LinkMenuItem` content type with `LinkMenuItemPart`.

But if you want to build a custom 'MenuItem' content type, you are not able to add `LinkMenuItemPart`.

Furthermore 'Part Definition' link in content part edit sends you to page not found.

**Comment by TFleury** [comment]
Is there a reason to have a recipe migration instead of using ContentDefinitionManager here ?

**Comment by TFleury** [comment]
`MenuPart` and `MenuItemsListPart` are not either registered.

**Comment by sebastienros** [comment]
Is the solution to register the content part types only?

It's using a recipe because we can ;)

**Comment by TFleury** [comment]
> Is the solution to register the content part types only?

I think so.

> It's using a recipe because we can ;)

Ok, personalIy I prefer the "classical" way ;-)

**Comment by sebastienros** [comment]
The parts are registered, I have no idea what issue you are describing.
Can you provide some repro steps? I tried with the Blog recipe.

**Comment by TFleury** [comment]
Repro steps :
- Setup instance with "Blog" recipe
- Goto : Admin => ContentDefinition => Content Parts
`LinkMenuItemPart`, `MenuPart` and `MenuItemsListPart` are not here.
- Goto : Admin => ContentDefinition => Content Types
- Edit "Link Menu Item" then "LinkMenuItemPart"
- Click on the "Part Definition" link in the green alert box => 404
- Same steps for "MenuPart" and "MenuItemsListPart" of "Menu" Content Type

Let's guess that we want to create a new MenuItem content type (the same than default one with an additional field)
- Goto : Admin => ContentDefinition => Content Types => Create new type
- Name it "Icon Link Menu Item", Create
- You can't reuse `LinkMenuItemPart` (it was not registered)

Same issue if you want to create a customized "Menu" content type, you won't be able to reuse `MenuPart` and `MenuItemsListPart`.

The fix is just to properly register the ContentParts we use. (`ContentDefinitionManager.AlterPartDefinition`)
