### ISSUE TITLE
Asset Library & AzureBlob does not list dir / files 

### ISSUE THREAD

**Issue by idontbyte** [OrchardCMS/OrchardCore#3280]
In my experience, when working with OrchardCore.Media.Azure, the Asset Library will not list the Directories + Files in blob storage unless you use the BasePath variable.

**Comment by jtkech** [comment]
I worked recently on #3200 to fix an issue with `Media`, but about `Media.Azure`, as i could not test it directly, I kept some points hanging.

Maybe we could work together to finalize #3200 and fix this issue. When i will have some time to return back to this, i will have some questions.

**Comment by jtkech** [comment]
I saw that `BlobStorageOptions` has a `BasePath` property. In #3200 i thought about using it to make distinctions between tenants, e.g equal to `media/{tenant}` if not provided by the configuration, globally or for a given tenant.

> unless you use the BasePath variable

Did you just add a `BasePath` to the config file, globally or for a given tenant? And / or did you have to update the code?

**Comment by idontbyte** [comment]
@jtkech In order to make the asset library list files I had to add a base path to my appsettings.json and add a corresponding folder to my azure blob storage.

**Comment by TFleury** [comment]
It's just caused by the _directory marker file_ that is missing in the root container.
