### ISSUE TITLE
Stackoverflow exception with OC > beta3-70808

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3281]
Hi,
Just after posting the OC Setup form, OC crashes wit a StackOverflow exception.

I have no issues with versions lower than beta3-70812. It seems that a commit done February, 28th is the route cause of my issue.

![image](https://user-images.githubusercontent.com/6775094/53768566-87e0e900-3ed9-11e9-899d-d0428b101a2b.png)

![image](https://user-images.githubusercontent.com/6775094/53768682-d1c9cf00-3ed9-11e9-928a-b0dd06faa65d.png)

**Comment by sebastienros** [comment]
@agriffard is that what you are experiencing too?

**Comment by sebastienros** [comment]
@jpiquot What recipe are you using?

Are you setting up taxonomies in this recipe? Or enabling it?

**Comment by sebastienros** [comment]
I just pushed a change that should fix it. Can you check once it's on myget?

**Comment by agriffard** [comment]
No more stackoverflow exception but another error:
```
NullReferenceException: Object reference not set to an instance of an object.
YesSql.QueryExtensions.Query<T>(ISession session) in QueryExtensions.cs, line 11

YesSql.QueryExtensions.Query<T>(ISession session) in QueryExtensions.cs
OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.GetShellDescriptorAsync() in ShellDescriptorManager.cs
OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in ShellContextFactory.cs
OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in ShellHost.cs
OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync() in ShellHost.cs
OrchardCore.Environment.Shell.ShellHost.InitializeAsync() in ShellHost.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by agriffard** [comment]
OK, I updated and tested again and there is no more Stackoverflow exception with the latest version of the nuget packages.

**Comment by jpiquot** [comment]
Ok for me with latest version. Thanks!

![image](https://user-images.githubusercontent.com/6775094/53812338-92dc5d80-3f5b-11e9-87b8-58263db8a2df.png)
