### ISSUE TITLE
Admin UI: enhancement on content pickers

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3283]
Add the ability to make content pickers interact with each others. Example: If I select Country = Canada in one content picker then it should only list States that are in that country.

Another example is : I have a Content Type named TeamYear which list all players of that Team for each year that they been active in a League. I want to create a Match for a specific year. Then in my Match I have a list of players that comes from that list of TeamYear. This TeamYear should only be an "hidden" content picker list that fills a second one so that I can pick players from that list to that Match. So we should be able to make a link between content types that also have List(s) ContentPart(s) through Content Pickers.

* Content Type A : 
   *  ListPart of Content Type B
* Content Type C : 
   * Content Picker of Content Type B filtered by Content Picker of Content Type A

**Comment by sebastienros** [comment]
As suggested in the chat, we should improve Taxonomies instead
