### ISSUE TITLE
Layerfilter.cs throwing null reference exception in latest builds

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#3287]
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
OrchardCore.Layers.Services.LayerFilter.OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next) in LayerFilter.cs, line 67

repro:
create empty web app in vs. add oc.cms.targets, run app.
after initial setup, the site does not come up, but above exception is thrown.

**Comment by sebastienros** [comment]
It happens if you don't have a front-end theme apparently

**Comment by psijkof** [comment]
Yes, the blank site recipe :)
And again you fixed it before I could, so thanks!
