### ISSUE TITLE
SetUp screen error with sql server

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#3288]
Using a clean install from dev branch I get the following error upon setup:

![image](https://user-images.githubusercontent.com/1516981/53910527-b3d8a780-405c-11e9-9ef2-81e0c3c2e515.png)

**Comment by sebastienros** [comment]
Fix your connection string

**Comment by giannik** [comment]
thanks. Did it.

**Comment by OksXen** [comment]
@sebastienros - When I enter an incorrect connection string in the Initital Set Up Page, it allows me to click on "Finish Setup" button and then the page goes to a blank page "This page isn’t working" -(Chrome). 

The error message in the log file is: 
 "Login failed for user 'occms_test'.  Reason: The password of the account must be changed.". 

I'm using a DEV Branch (Fork). 
Should I be seeing a descriptive SQL Server error message before I could click on the "Finish Setup" button?

Thanks, 
-OX
