### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#3289]
After performing npm install gulp build seems to fail as shown below : 

![image](https://user-images.githubusercontent.com/1516981/53910898-acfe6480-405d-11e9-8225-f79a2d8fbfce.png)

**Comment by sebastienros** [comment]
Do you have the latest `npm` version?
Have you done and `npm install` ?

**Comment by giannik** [comment]
Yes I have latest version of node and npm.
Did npm install first then gulp build.
Also using latest dev branch.

**Comment by MichaelPetrinolis** [comment]
try to install gulp globally - npm install -g gulp

**Comment by giannik** [comment]
Yes , that resolved the issue. Working now!
Euxaristo patrioti.
