### ISSUE TITLE
Possible to rewrite system URL?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#3291]
Hi, 

Is it possible to rewrite system URL ?

For example, if user access the Admin panel, http://MySite/Admin/,   
I'd like to redirect the user to:
http://MySite/OrchardCore.Users/Admin/Index

The following code in my custom Theme's Startup.cs cause HTTP500 error.

            routes.MapAreaRoute
            (
                name: "Admin",
                areaName: "MyTheme",
                template: "Admin",
                defaults: new { controller = "OrchardCore.Users", action = "Index" }
            );

**Comment by jtkech** [comment]
Just tried the following that seems to work.

    public class Startup : StartupBase
    {
        public override int Order => -1; // run earlier, so my route has a higher priority.

        public override void Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            routes.MapAreaRoute(
                name: "MyAdmin", // prevents duplicate route name.
                areaName: "OrchardCore.Users", // need to be still OC.Users.
                template: "admin",
                defaults: new { controller = "Admin", action = "Index" }
            );
        }

        public override void ConfigureServices(IServiceCollection services)
        {
        }
    }

**Comment by orchardc** [comment]
Thanks a lot Jean-Thierry, it works great! :)

**Comment by jtkech** [comment]
Okay cool !!! So i close this issue
