### ISSUE TITLE
SQLite database locked

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3292]
Hi,

I seen the #1414 #775 issues and understand that we can't have in OC two concurrent writes with SQLite. But when this situation arrives, OC session does not retry a connection and is in an unstable state.

After a database locked error, you can not write anymore in the database. Updates from OC pages don't show errors, just as if everything is OK, but the database is not updated. You need to restart the OC server to be able to do updates again.

Could we implement a reopen connection when connection has failed?

For example : 
My workflow is activated, I uncheck enabled and click on save : 
![image](https://user-images.githubusercontent.com/6775094/53951741-7103e780-40cf-11e9-8d2e-aec41079de95.png)

I have no message error, but the update has not been not persisted.

![image](https://user-images.githubusercontent.com/6775094/53951785-89740200-40cf-11e9-9d36-43298015a562.png)

**Comment by siyamandayubi** [comment]
I had the similar issue. It will be fixed by this PR https://github.com/sebastienros/yessql/pull/163
