### ISSUE TITLE
How can i add options to the SelectPart?

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#3297]
I'm using the forms module and work flow module to save form data.
When i add the select part to my form,i find that i can't add options to the select part.
How can i do it?
Thank you.

**Comment by sebastienros** [comment]
I assume we are missing the SELECT and OPTION form elements.

https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Forms/Models

Feel free to create a PR to add these, or even a "Custom" Form element where you could render custom tags.
