### ISSUE TITLE
Need manage user information field in admin page

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/OrchardCore#3299]
The administrators can manage user information field at admin page.
like this:

| fieldname | fieldtype |  |
| ------ | ------ | ------ |
| age | number |  -eidit -delete |
| sex  | text |-eidit -delete |
| picture  | meida image  |-eidit -delete |

**Comment by cellpaddding** [comment]
Orchard 支持这个功能，需要启用Users模块。

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2502

I think the content of the user information module, in addition to the user name, password and other key fields, the rest should be linked to the content item, you can freely design the extended field content information of the user information module, the data is stored in the content management module, just like freely create content Same type

我认为用户信息模块的内容，除了用户名，密码等关键字段，其余应该链接到内容项目，可以自由设计用户信息模块的扩展字段内容信息，数据存储在内容管理模块中，就像自由创建内容类型一样

**Comment by sebastienros** [comment]
related to #3141

**Comment by agriffard** [comment]
See Custom user settings.

/cc @deanmarcussen
