### ISSUE TITLE
NullLocalizer feature

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#3301]
Create a feature in the localization module which would create a NullLocalizerFactory in order to replace the default ResourceManagerLocalizer which is resource consuming and useless as we don't have resx files in our projects. This would be enabled in our recipes.

**Comment by hishamco** [comment]
If we create a `NullLocalizer` how this will enable setup screen localization. IMHO either we need to enable localization feature by default or use sort of configuration file to localize the setup screen
