### ISSUE TITLE
OrchardCore AntiForgery Token 

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3304]
How can I retrieve the anti-forgery token set by OrchardCore? In my instance it is `orchantiforgery_Default`.

I am using OrchardCore framework and right now I can't make any POST to my ajax controller in the module because I can't get the right token.

Code such as 
```
 var tokens = _antiforgery.GetTokens(HttpContext);
```

doesn't work because it generate different tokens than what's available in `orchantiforgery_Default`

**Comment by sebastienros** [comment]
Using the standard aspnet API to generate it?

**Comment by jtkech** [comment]
For infos just tried the following.

Assuming that the cookie token has already been generated, i was able to retrieve it like this.

            var test1 = HttpContext.Request.Cookies["orchantiforgery_Default"];
            var test2 = _antiforgeryTokenStore.GetCookieToken(HttpContext);

**Comment by jtkech** [comment]
For infos, if it is what you want to do, see the ajax call in the `List.cshtml` of the `OC.AdminMenu` module, and how the `__RequestVerificationToken` is retrieved.

        var url = "@Url.Action("MoveNode", "Node", new { area = "OrchardCore.AdminMenu"})";
        $.ajax({
            url: url,
            method: 'POST',
            data: {
                __RequestVerificationToken: $("input[name='__RequestVerificationToken']").val(),
                treeId: AdminMenuId,
                nodeToMoveId: nodeToMoveId,
                destinationNodeId: destinationNodeId,
                position: position
            },
            success: function () {
                location.reload(true);
            },
            error: function (error) {                
                alert($('#move-error-message').data("message"));
            }
        });

**Comment by sebastienros** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.2

**Comment by dodyg** [comment]
I will write a sample produce to replicate. Right now I have to resort to [IgnoreAntiforgeryToken].

I am using OrchardCore.Module to create a LOB app in a separate project. The main web project uses OrchardCore in Decoupled mode.

This API controller is located at the Module.

**Comment by sebastienros** [comment]
Even if decoupled, when you generate a form you can use the MVC tag helper. When using it it will generate an AFT for you in the form. 

If you are not using a form but an Ajax call, then you can still generate the token with `@Html.AntiForgeryToken()` and then use javasctipt to read this value.

Optionally the value can be injected in a header like this: https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.2#antiforgery-options

**Comment by sebastienros** [comment]
Please reopen if you think we haven't answered the question.

**Comment by xumix** [comment]
What is the preferred way to store and use Orchard's AntiForgeryToken with SPA's like React and Angular? `orchantiforgery_Default` is HttpOnly so I can't access it within my app

**Comment by Skrypt** [comment]
@Html.AntiForgeryToken() and then use javasctipt to read this value

**Comment by xumix** [comment]
@Skrypt I don't have any views in my app, so I can't use this helper. Even if I add it - it is not secure without the cookie.

**Comment by Skrypt** [comment]
Ok, and you say you can't expose `orchantiforgery_Default` because it is HttpOnly.
I think we closed the issue because it's not related to OC directly but more related with how to handle this with ASP.NET MVC. The documentation link looks like explaining how to achieve this, have you tried it yet?

**Comment by xumix** [comment]
@Skrypt sure I did look at the docs, will this approach work https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.2#angularjs ?
I'm going to use the token within several apps so I must set the 
`options.HeaderName` and `options.CookieName` for the Antiforgery

**Comment by Skrypt** [comment]
I can't say as I've never tried but it seems like the appropriate documentation. I think there is someone who customized OC a lot for SPA usage please look at the community standing videos on Youtube for details. I need to investigate more to see if it would not be duplicate work.
