### ISSUE TITLE
Page structure, is hierarchical/tree/parent/child structure planned for OrchardCore?

### ISSUE THREAD

**Issue by ftrMorri** [OrchardCMS/OrchardCore#3306]
I was trying to figure out how to create a traditional site structure ( parent/child pages ), but I quess this is not currently possible?

Are there any plans to implement such a feature in the future?

**Comment by Craige** [comment]
How do you mean a "traditional site structure"?

**Comment by sebastienros** [comment]
Also, the menu itself is hierarchical and you can organize the pages as you want in the menu.
