### ISSUE TITLE
Recipe schema to invoke other recipes

### ISSUE THREAD

**Issue by Craige** [OrchardCMS/OrchardCore#3311]
Is it possible to have a recipe.json file invoke another (set of) recipe(s) upon execution?

For example, you might have a theme with a recipe.json file, which uses ContentTypes provided by a (set of) module(s). It would make sense to be able to execute other recipes files from the currently executing recipe.

```
  "steps": [
    {
      "name": "feature",
      "disable": [],
      "enable": [
        "SomeModule",

        "TheAgencyTheme",
        "TheAdmin",
        "SafeMode"
      ]
    },
    {
      "name": "recipes",
      "executeBefore" : [
          "SomeModule:SomeRecipe"
      ]
    },
  }
```
It seems weird to "enable" other features here, but not have them initialized (whatever that means for that feature).

**Comment by sebastienros** [comment]
Yes, it's already supported
See the `RecipeStep` class
```
         {
            "name": "recipes",
            "Values": [
                { "executionid": "OrchardCore.Setup", name="Core" }
            ]
         }
```

**Comment by Craige** [comment]
Right, though it should be:

```
     {
            "name": "recipes",
            "Values": [
                { "executionid": "OrchardCore.Setup", "name": "Core" }
            ]
         }
```
The documentation in RecpipeStep.cs is invalid JSON:

https://github.com/OrchardCMS/OrchardCore/blob/d729a2048a4390380d99e7be9f7968ff8f8e9271/src/OrchardCore.Modules/OrchardCore.Recipes/RecipeSteps/RecipesStep.cs#L30
