### ISSUE TITLE
Refresh and access token keep growing on each exchange with a few bytes

### ISSUE THREAD

**Issue by Tsjerno** [OrchardCMS/OrchardCore#3327]
Each exchange of the refresh token for an access token makes the access token and refresh token grow. 
After a while this results in large tokens which are not accepted by ingress, request/response headers are too large.

See https://github.com/OrchardCMS/OrchardCore/pull/3326 for a solution.
@PinpointTownes with this change the token(s) stop growing. For the access_token I understand that this works. I don't understand why the refresh_token also stops growing. Can you explain (or give some urls) with what information the refreshtoken is generated?

**Comment by PinpointTownes** [comment]
Nice catch (and thanks for submitting a PR!)

This is indeed the right thing to do. It likely regressed when I decoupled the OpenID module from Users/Roles:
  - Before that change, the `ClaimsPrincipal` was always re-created from scratch by calling Identity's `CreateUserPrincipalAsync` each time we handled an authorization code or refresh token request.

  - Now, we re-use the `ClaimsPrincipal` that was initially set by the authentication stack (e.g the one contained in the authentication cookie for an interactive flow or the one returned by `AuthenticateAsync` for the password grant type).

I'll update your PR to improve that a bit, by allowing the `ClaimsPrincipal` to be "refreshed" if the user service is available when handling an authorization code or refresh token.
