### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#3329]
**Module** "OrchardCore.Google", **file** "GoogleAuthenticationSettings.Edit.cshtml".

**note remark:** <span asp-validation-for="ClientSecret"></span>

![image](https://user-images.githubusercontent.com/6829626/54365560-198dea80-4680-11e9-9a57-c26d9db80a28.png)

**Comment by PinpointTownes** [comment]
@AcellaEDU thanks for reporting this issue! Would you like to submit a PR to fix it?
