### ISSUE TITLE
CDN resource load very slow in some network

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#3330]
The admin menu display is not normal.
The reason is that the my network access the use.fontawesome.com CDN resource is very slow, because I am in China.
 
I used a ping test with a Chinese website that automatically tested different locations of the network to the same address.
http://ping.chinaz.com/use.fontawesome.com
The results include some overseas network tests.
The fastest is only 1 ms form the US
But the picture is less rosy in China and elsewhere.Besides, the file is quite large.
It is recommended to do a range of network speed tests when using CDN.
The following is a screenshot of the test
For more [http://ping.chinaz.com/use.fontawesome.com](url)
![image](https://user-images.githubusercontent.com/15613121/54412772-fbcb8e80-472e-11e9-9439-134c7e3a40e1.png)
![image](https://user-images.githubusercontent.com/15613121/54412787-07b75080-472f-11e9-866f-869f288fceef.png)

**Comment by cellpaddding** [comment]
I think maybe the Great Firewall let it request let it slow.

**Comment by pgy866** [comment]
I think  should add a settings window that can be directly replaced with a local resource. This way we can set or change whether to use local resources at any time (and can update related resources at any time in the background)

**Comment by hyzx86** [comment]
自己解决这个问题的方式：
从官方下载压缩包解压到站点的wwwroot 目录下

![image](https://user-images.githubusercontent.com/15613121/54426574-2b8c8d80-4753-11e9-9613-95e5972510fc.png)

然后创建一个类：ResourceManifest.cs

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OrchardCore.ResourceManagement;

namespace OrchardCore.Cms.Web
{
    public class ResourceManifest : IResourceManifestProvider
    {
        public void BuildManifests(IResourceManifestBuilder builder)
        {
            var manifest = builder.Add();


            manifest
                .DefineStyle("font-awesome")
                .SetUrl("~/fontawesome-free-5.7.2-web/v5.5.0/css/all.css") 
                .SetVersion("5.7.2")
                ;

            manifest
                .DefineScript("font-awesome")
                .SetCdn("~/fontawesome-free-5.7.2-web/js/all.js") 
              .SetVersion("5.7.2")
                ;

            manifest
                .DefineScript("font-awesome-v4-shims")
                .SetUrl("~/fontawesome-free-5.7.2-web/js/v4-shims.js") 
                .SetVersion("5.7.2")
                ;
        }
    }
}
`

**Comment by hyzx86** [comment]
> I think maybe the Great Firewall let it request slowly.
如果是墙，早被隔离了。
只是因为这个CDN 服务器没有覆盖到中国

**Comment by hyzx86** [comment]
> I think should add a settings window that can be directly replaced with a local resource. This way we can set or change whether to use local resources at any time (and can update related resources at any time in the background)

你可以管理自己的资源，但是内置的资源一般来说不需要修改

**Comment by jimaek** [comment]
jsDelivr has servers in mainland China including an ICP license to avoid throttling. It should be much faster. Example URL https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css

**Comment by pgy866** [comment]
> > 我认为应该添加一个可以直接替换为本地资源的设置窗口。这样我们就可以随时设置或更改是否使用本地资源（并且可以在后台随时更新相关资源）
> 
> 你可以管理自己的资源，但是内置的资源一般来说不需要修改

哎，这个会由于第三方资源网络断开而影响ORCHARD CORE的系统使用，并不觉的很美好。如果可以在某些情况下可以配置多好

**Comment by sebastienros** [comment]
Maybe we can find a CDN source that works well for most users.

However the ideal solution in that case is to create a separate module that would contain the static assets locally, or that would point to better CDNs for each region. I don't want to have to deal with these, because it would be a lot of work, we don't know the impact on other regions, and it add some legal issues. At least not in the ResourceManagement module.

I am open to having a distinct package containing FontAwesome only, and it would define the local assets. Note that we already have a setting that lets you choose between local and cdn assets, it's just that we don't have FA locally. We would need to handle the licensing issue though (we are redistributing it this way). Also it opens the door to having to do it for lots of libraries.

**Comment by hyzx86** [comment]
> jsDelivr has servers in mainland China including an ICP license to avoid throttling. It should be much faster. Example URL https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
> 
> ![china](https://user-images.githubusercontent.com/1834071/54428951-670d6480-471f-11e9-93ef-f4303e8a66c1.png)

The jsDelivr CDN haven't incloud version 5.5.0 ?

**Comment by hyzx86** [comment]
@sebastienros So , can I change to cdn.jsdelivr.net ?
like this :
`https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.7.2/js/all.js`

**Comment by sebastienros** [comment]
Looks like jsdelivr is a good cdn overall. https://www.cdnperf.com/
