### ISSUE TITLE
Dead link in the Orchard Core Documentation

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#3331]
Good afternoon!

Found a broken link in the [OrchardCore Documentation](https://orchardcore.readthedocs.io/en/dev/)
![image](https://user-images.githubusercontent.com/6829626/54415151-77681400-470c-11e9-81ae-a366e6645c6c.png)

I understand that beta3 isn't released.
--

**Comment by hyzx86** [comment]
And Here  : https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Workflows/
 
![image](https://user-images.githubusercontent.com/15613121/54441895-9a301200-4778-11e9-94c5-2af8e7e5d140.png)
