### ISSUE TITLE
MediaField not working

### ISSUE THREAD

**Issue by jan-chvojka** [OrchardCMS/OrchardCore#3333]
Media Field won't save selected files. I noticed it in my project and I'm able to reproduce it with clean latest source code (commit b625ffad3f0a6ffb4ca4366ae22a276bd4c3b70c).

**How to reproduce**
1. Setup site with Blank Theme and with sqlite.
2. Create some Content Type.
3. Create Media Field on it.
4. Create Content Item and try to add an Image.
5. After Publishing/Saving Draft, the field is empty.

**Info**
- The paths are passed to the MediaFieldDriver, I have debugged it.
- Sometimes the image is saved, but then you can't get rid of it. I could not reproduce why.
- No exceptions thrown.

**Comment by matiasmolleja** [comment]
It seems it started after merging #3310 
cc/ @sebastienros

**Comment by sebastienros** [comment]
:/ Will check, thanks for the detailed repro steps.

**Comment by sebastienros** [comment]
It's all the fields
