### ISSUE TITLE
Pre-fill field "recipe" of "create tenant" page from appsetings.json

### ISSUE THREAD

**Issue by R-Ballester** [OrchardCMS/OrchardCore#3334]
I would like to pre-populate the "recipe" field of the "create tenat" page from the "appsetings.json" file of my web application.
I have already configured the "DatabaseProvider" and "ConnectionString" by:
   "OrchardCore": {
     "DatabaseProvider": "SqlConnection",
     "ConnectionString": "Data Source = xxx; Initial Catalog = xxx; User Id = xxx; Password = xxx"
   }
Is it possible to do the same thing for the recipe field?

**Comment by jtkech** [comment]
@R-Ballester normally just add this field (can't right now but i will retry it this night).

    "RecipeName": "Blog",

**Comment by jtkech** [comment]
@R-Ballester i sent an email to Arnaud with more technical infos and how to fix the use case that you showed me, let me know by email if you received it, otherwise i could send you a copy. (see my email address on my profile).

**Comment by R-Ballester** [comment]
> @R-Ballester normally just add this field (can't right now but i will retry it this night).
> 
> ```
> "RecipeName": "Blog",
> ```

Well done : "RecipeName" work

**Comment by jtkech** [comment]
Okay cool
