### ISSUE TITLE
Blank theme missing from OrchardCore.Application.Cms.Targets latest version

### ISSUE THREAD

**Issue by nigel-dewar** [OrchardCMS/OrchardCore#3338]
Hi There,

Blank theme is missing from OrchardCore.Application.Cms.Targets latest version.

Steps to reproduce.

Spin up Fresh .net core empty project using v 2.2

Install OrchardCore.Application.Cms.Targets via nuget, latest version 1.0.0-beta2-69590

Add Orchard bits to Startup.cs

Fire up orchard core , setup, 

You will see there is no blank theme.

Even if you create your own Pages folder and put some razor files in there, it gets ignored.

So no way for you to develop your own cutomized version of orchard without having to use the Full OrchardCore repo which is a pain, because its much slower.

Remedy

Can you please add the blank setup template to orchard core cms targets nuget package?

Cheers

**Comment by sebastienros** [comment]
You should use the packages from myget until we push to nuget:

https://myget.org/feed/orchardcore-preview/package/nuget/OrchardCore.Application.Cms.Targets

**Comment by nigel-dewar** [comment]
Ok thank you I will use this cheers
