### ISSUE TITLE
OrchardCore.Mvc.Web Sample Not Working still in 2019

### ISSUE THREAD

**Issue by nigel-dewar** [OrchardCMS/OrchardCore#3339]
I have latest dev branch downloaded.

I try to run the sample MVC project found here

![image](https://user-images.githubusercontent.com/9402456/54466844-81058080-47cd-11e9-8a27-089413b57366.png)

It doesnt work. I get this error

![image](https://user-images.githubusercontent.com/9402456/54466850-8d89d900-47cd-11e9-9cb7-78c8cf1fd18a.png)

What is it talking about?

Is this a bug?

**Comment by nigel-dewar** [comment]
Update - I managed to fix by removing reference of this in the web.config file. and can now run the sample

But how do I get to /admin now?

I cannot use /admin, it goes no-where

How do I trigger the setup of Orchard?  Is there some /setup route hidden I need to know about?

Cheers

**Comment by jtkech** [comment]
For all of this, you need to use the `OrchardCore.Cms.Web` application.

**Comment by sebastienros** [comment]
We need to remove the web.config from this sample. It will be generated automatically. 
And also add `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`

**Comment by nigel-dewar** [comment]
Ok thank you!

**Comment by sebastienros** [comment]
@nigel-dewar this sample is not meant to run the CMS, it shows how to build a modular MVC app, so the /admin won't work as is. The /admin endpoint is defined in the OrchardCore.Admin module, which you can use in any modular application though. You are not supposed to edit this sample, but create your own application that can be inspired from this one.
