### ISSUE TITLE
MVC targets seems to be completely ignored 

### ISSUE THREAD

**Issue by nigel-dewar** [OrchardCMS/OrchardCore#3340]
Using latest version 'myget' .

I have a fresh .net core project setup. Added CMS targets, and MVC Targets. Setup a blank theme site so I can create my own controllers, pages etc. This works fine.

By MVC routes seem to be completely ignored

My startup file looks like so

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication8
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms().AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseOrchardCore();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}

```
When I fire up project it keeps saying page not found. 

![image](https://user-images.githubusercontent.com/9402456/54468624-38a08f80-47da-11e9-8298-cab513a8a61f.png)

My project is really standard for MVC and looks like so

![image](https://user-images.githubusercontent.com/9402456/54468630-4b1ac900-47da-11e9-8c38-7755fb58575d.png)

Does OrchardCore ignore mvc routes?

**Comment by sebastienros** [comment]
First you don't need to call `AddMvc` as it's part of `AddOrchardCms`. Then for the same reason you need to configure the routes in the context of the tenant that Orchard Core is configuring. 

Follow this link for an example:

https://github.com/OrchardCMS/OrchardCore/issues/3231#issuecomment-472077940

**Comment by jtkech** [comment]
Please, see my comments in this closed issue #3231

**Comment by sebastienros** [comment]
I was faster by 5 seconds

**Comment by jtkech** [comment]
😄

**Comment by nigel-dewar** [comment]
Sorry this does not work.

I set things up like so

```
services.AddOrchardCms()
                .AddOrchardCore()
            .Configure((tenantAppBuilder, tenantRouteBuilder, tenantScopeServiceProvier) =>
            {
                // Configure the tenant pipeline.
                tenantRouteBuilder.MapAreaRoute(
                    name: "default",
                    areaName: "Website",
                    template: "{controller=Home}/{action=Index}/{id?}"
                );
            })
            .ConfigureServices(tenantServices =>
            {
                // Add services to the tenant container.
            });
```
Run it and get this error

![image](https://user-images.githubusercontent.com/9402456/54468946-8d91d500-47dd-11e9-8458-73530590a5df.png)

Orchard core seems to just not want to display my index page

I also noticed. If I add a Pages file and add a razor page, I can use this. But as for MVC, it just doesnt work

**Comment by nigel-dewar** [comment]
I've got some paid training with Seth coming up on the 19th, so most likely these basic questions can be answered. 

But I am sure you are getting tired of these basic issues.

Is there any plans to do more work on the docs?_

**Comment by nigel-dewar** [comment]
The only thing that seems to work out of the box is to add a Pages folder, and add a razor page. Traditional Style MVC, I have no idea how Im supposed to make this work with Orchard. and the docs doesnt explain it either.

**Comment by nigel-dewar** [comment]
Awwwwwh Snap! I got it.

Default name must be reserved for Orchard

I use this and it worked

![image](https://user-images.githubusercontent.com/9402456/54469083-31c84b80-47df-11e9-901a-5c7bb9eb181f.png)

**Comment by jtkech** [comment]
Yes, we have a `Default` route name per isolated tenant ;)

            // The default route is added to each tenant as a template route, with a prefix
            builder.Routes.Add(new Route(
                builder.DefaultHandler,
                "Default",
                "{area:exists}/{controller}/{action}/{id?}",
                null,
                null,
                null,
                inlineConstraintResolver)
            );

**Comment by nigel-dewar** [comment]
Ok thank you.

Things were working, then defaulted back to this

![image](https://user-images.githubusercontent.com/9402456/54469317-34787000-47e2-11e9-97b8-104ba53ea601.png)

Orchard wants to resist running my controllers and views. So strange!

**Comment by nigel-dewar** [comment]
I also noticed spafallbacks dont work

tenantRouteBuilder.MapSpaFallbackRoute(
                          name: "spa-fallback",
                          defaults: new { controller = "Home", action = "Index" }
                );

**Comment by nigel-dewar** [comment]
AHHHHHHHHHHHHH My bad,

You must include these on controller ( reference for others facing this issue ) 

  [Route("")]
        [Route("Home")]
        [Route("Home/Index")]
