### ISSUE TITLE
MapSpaFallbackRoute does not work 

### ISSUE THREAD

**Issue by nigel-dewar** [OrchardCMS/OrchardCore#3341]
This is minor bug, but one that will pop as people try to use Orchard with spa frameworks.

If you set a MapSpaFallbackRoute when using MVC, it gets ignored.

So if you visit your home page, and your spa kicks in and adds say a round like /cart, this works fine on load up.

But if you do a manual browser refresh, it doesnt work. The fallback is ignored

tenantRouteBuilder.MapSpaFallbackRoute(
                          name: "spa-fallback",
                          defaults: new { controller = "Home", action = "Index" }
                );

And sends you to

![image](https://user-images.githubusercontent.com/9402456/54469550-1bbd8980-47e5-11e9-873e-a13e0b01cd84.png)

**Comment by jtkech** [comment]
The following is just as a reminder for a possible solution, but not sure at all.

- After a quick search, it seems that `MapSpaFallbackRoute ()` would need to be called last.

- Modules startup has an `Order` property, and for the application's module the `Configure()` helper also has an optional `Order` parameter. So we can act on the order in which routes are registered.

- Infortunately we add e.g our `Default` route in the `Configure()` of our `ModularTenantRouteBuilder` that we always call after all module startup `Configure()` (including the app's module).

- So, maybe the solution is to move what `ModularTenantRouteBuilder` do in its `Configure()` to the `Configure()` of our `OC.Mvc.Core.Startup` class (which currently only defines `ConfigureServices()`).

- This way a module (including the app'module) would be able to register routes last.

- The `OC.Mvc.Core.Startup` would need to have a quite high `Order` value for the execution of its new `Configure()`, but it already has an `Order` of -200 to execute 1st its `ConfigureServices()`. So we would need to split it in 2 startups classes (with different `Order`) and register them, which is easy to do.

**Comment by nigel-dewar** [comment]
Hi @jtkech ,

Thanks for your reply. So do you rekon this a bug or just configuration education/doco thing?

**Comment by jtkech** [comment]
I would say not really a bug but something to refactor beyond the spa thing.

I will do it asap then i would need your help to confirm that it works for you.

**Comment by matiasmolleja** [comment]
Just in case it's of any help with this. In any case it's a good read.
https://weblog.west-wind.com/posts/2017/aug/07/handling-html5-client-route-fallbacks-in-aspnet-core

**Comment by jtkech** [comment]
thanks for the link

**Comment by jtkech** [comment]
Hi @nigel-dewar 

I made #3345 so that a module or the application through the `Configure()` helper can add a route after the default mvc ones. To do this you need to pass an `Order` parameter higher than 200 when using the `Configure()` helper at the app level. E.g based on your code.

            services.AddOrchardCms()
                .AddOrchardCore()
                .Configure((app, routes) =>
                {
                    routes.MapSpaFallbackRoute(
                    name: "spa-fallback",
                    defaults: new { controller = "Home", action = "Index" });
                }, order: 201);

It would be fine if you could give it a try.

**Comment by Piedone** [comment]
This shouldn't be an issue anymore.
