### ISSUE TITLE
How to insert a javascript or custom HTML into the automatically generated shape definition

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#3342]
When we create content through a workflow, there are only a few lines of json. It's just an example

I want to add a function that can get the last row of data data of the ContentItem in the ContentType selected by the user through Ajax as a Json template, automatically formatted and populated into Content Properties, replacing the current fixed content.

This way we don't need to query the database to get the data structure.

![image](https://user-images.githubusercontent.com/15613121/54478413-bbfac900-484c-11e9-9856-5bb54caf6f7c.png)
 
I looked at the code structure, but I don't know how to start it.
The display fields of all CreateContetTask Activity are automatically generated.

How to add a JS on the page that edits the Activity?

In addition, the API method should be placed there, there is no reference content. Or a better way
The same function, we can add it to the ContentType definition page.

**Comment by sebastienros** [comment]
I don't understand what you are asking for.

**Comment by hyzx86** [comment]
@sebastienros 
I want to get json data for a content via JavaScript on this page. Where should I add it? What are the ways to get content data through JS? Is there a ready-made Web API?

**Comment by sebastienros** [comment]
There are already REST Apis, like api/content/{id} and also GraphQL, and lucene/sql queries can also be exposed as API (see in permissions).
