### ISSUE TITLE
ContentItemId and other properties are not set when creating a content item using the content API

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#3343]
Let's say you have a content type and you want to create an item using the content API (POST request to /api/content). The content item parameter looks like this:

`{
    "ContentType": "Test",
    "Owner": "admin",
    "Author": "admin",
    "TitlePart": {
        "Title": "Test From API"
    },
    "TestPart": {
        "Summary": {
            "Text": "Test Summary"
        }
    }
}`

I expect that the ContentItemId will be automatically generated along with the DisplayText, ModifiedUtc, PublishedUtc, CreatedUtc properties.

The ContentItemVersionId is generated but the ContentItemId not. It's the bigger issue since it breaks the application - you won't be able to access the content list on the dashboard anymore.

The other mentioned properties are not generated either. I understand that the Owner and the Author properties can't be determined, however, the DisplayText could be set inside the Title module and the date values could be set to the current date. Maybe if these are already set in the request then use them but otherwise set them - or alternatively send a validation error response.

**Comment by sebastienros** [comment]
The display text is not generated automatically. The title part doesn't have any data anymore, it's just an editor. What you set in the title part should be in the display text instead.

The content item id not being generated might be because this API behaves like it creates a new version. But either we should have multiple APIs then or set the contentitem id, so I agree with the issue here.

**Comment by sebastienros** [comment]
We should also change this API with idempotency in mind.

**Comment by barthamark** [comment]
That makes sense. So ideally we should add a PUT method here which will create a new content item and it will call the ContentManager.NewAsync method which does everything required for initializing a content item (including the ID generation).

About the other properties, in the meantime I realized that we can set the Owner (actually, it will be done if we call the NewAsync). How about the others?

About the DisplayText: Makes sense now thank you.

**Comment by Piedone** [comment]
Just adding that POST is RESTful APIs serve to create, PUT to update items, so this should still work accordingly.

**Comment by sebastienros** [comment]
Also, I think we could also use PATCH to update a fragment of the document (like the display text?).

I am not opposed to use PUT for the updates, but it might be simpler to use a single verb, knowing that the body will have to be different in create vs update, so we already know what the payload is intended to do (we NEED a version id for updates). Also the client wouldn't have to switch verbs to manage content items.

But having two verbs can also help the client not make mistake, and we could validate the presence of the correct ids based on the verbs.

I think Azure RM uses POSTs for both, can you confirm?

**Comment by Piedone** [comment]
[It does](https://docs.microsoft.com/en-us/rest/api/resources/resources/createorupdate), but for the reasons outlined above and under the linked SO topic I'd keep create and update under separate verbs for clarity.

**Comment by sebastienros** [comment]
All good! @barthamark you know what to do now.

**Comment by Piedone** [comment]
Can you show the API response, as well as the JSON document created in the DB, when you test the API request Márk has shown?

**Comment by BanzragchUchral** [comment]
The API response from Postman:  
![image](https://user-images.githubusercontent.com/79921246/154579715-7f7051bc-874f-420e-bece-157bd2c1532b.png)

DB: 
```json
{
   "ContentItemId":"41p1vwxt02chr56s1bnaqjnk4t",
   "ContentItemVersionId":"45e7m10z9madprw4n9rk2e9hwq",
   "ContentType":"Test",
   "DisplayText":"",
   "Latest":true,
   "Published":true,
   "ModifiedUtc":"2022-02-17T22:08:01.1751948Z",
   "PublishedUtc":"2022-02-17T22:08:01.1768189Z",
   "CreatedUtc":"2022-02-17T22:08:01.1751948Z",
   "Owner":"admin",
   "Author":"admin",
   "Test":{
      
   },
   "TitlePart":{
      "Title":"Test From API"
   },
   "TestPart":{
      "Summary":{
         "Text":"Test Summary"
      }
   }
```

**Comment by BanzragchUchral** [comment]
Yes, you are right. It gets returned and saved too. 

The API request:
{ "ContentType": "Test", "DisplayText": "Test", "Owner": "admin", "Author": "admin", "TitlePart": { "Title": "Test From API" }, "TestPart": { "Summary": { "Text": "Test Summary" } } }

The response: 
![image](https://user-images.githubusercontent.com/79921246/154674473-dfe32ece-83ca-419f-9161-f1cd3cfdcc0e.png)

DB:
```json
{
   "ContentItemId":"45nydrwzcg51cxmr07b8tcnhxg",
   "ContentItemVersionId":"425a46efazx6w0b6am0wp174cg",
   "ContentType":"Test",
   "DisplayText":"Test",
   "Latest":true,
   "Published":true,
   "ModifiedUtc":"2022-02-18T11:27:03.5193936Z",
   "PublishedUtc":"2022-02-18T11:27:03.5637431Z",
   "CreatedUtc":"2022-02-18T11:27:03.5193936Z",
   "Owner":"admin",
   "Author":"admin",
   "Test":{
      
   },
   "TitlePart":{
      "Title":"Test From API"
   },
   "TestPart":{
      "Summary":{
         "Text":"Test Summary"
      }
   }
}
  ```

**Comment by Skrypt** [comment]
Yes to the original question. It would be more appropriate to use different verbs for Create (POST) and Update (PUT).

**Comment by Piedone** [comment]
The behavior looks good to me then.

@Skrypt the [current controller](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs#L88) is pretty compact. Are you sure you'd introduce a breaking change just for a different verb? I agree with the theory but I wouldn't break the API for this.

**Comment by BanzragchUchral** [comment]
So what is the conclusion here? Can we close this issue?
