### ISSUE TITLE
Theme Layout not recognized after setup

### ISSUE THREAD

**Issue by Craige** [OrchardCMS/OrchardCore#3346]
It appears that under some instances, themes may not be completely initialized during a tenant setup.

When creating a new tenant and setting the default recipe to a custom theme, after completing the setup the site may throw an exception `System.Exception: Shape type 'Layout' not found`.

The theme has the appropriate `Layout.liquid` file, and the recipe seems to be configured correctly.

From the admin interface, changing to another theme (e.g. Safe Mode) and then back to the theme specified in the setup resolves the issue, which leads me to believe this is likely an issue with the setup process.

**Comment by siyamandayubi** [comment]
Can you provide more information regarding how to reproduce the issue, maybe uploading a testing theme as it doesn't happen for the build-in themes.

**Comment by Craige** [comment]
Sure. Let me see if I can narrow down the offending area of my theme and get some steps to reproduce.

The theme. I'm constructing _used_ to initialize fine from the setup screen, so I'll see if I can trace down what broke the Recipe/theme.

**Comment by matiaskusack** [comment]
Hi, I just had a similar issue (same error message).

The thing was that Theme was not being correctly enabled but was declared as Site default Theme.

Instead of the name of the folder containing the Theme, I was using the name defined above.

**Comment by deanmarcussen** [comment]
can you share the section of the recipe that setup the theme @matiaskusack ?

**Comment by Craige** [comment]
Being almost a year ago, I'm not 100% sure what I did to resolve this, but I'm somewhat suspect that the problem was an invalid Recipe file. I could also be completely wrong.

**Comment by JoshTango** [comment]
I am having the same problem.  It works as a non tenant but my custom theme wont work as a tenant.  Same error.

**Comment by deanmarcussen** [comment]
dup of https://github.com/OrchardCMS/OrchardCore/issues/5476

**Comment by JoshTango** [comment]
Ok I had the same problem and realized my custom theme was not listed in the steps/enable section of the recipe.  If you list your theme there the layout exception will go away
