### ISSUE TITLE
Why OrchardCore can't save array data in Create Content Task?

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#3351]
I custom a Content type and with a content task in my workflow to save some data.
There is an array in the content task that was customed by me.
But the workflow can't save it.
![QQ截图20190318103303](https://user-images.githubusercontent.com/16536053/54503307-9e6f5180-4969-11e9-8ae9-5c6f5514ef41.png)

**Comment by psijkof** [comment]
Shouldn't the outcome be:
`"Paths": [ "John", "Paul", "George", "Ringo" ]`

**Comment by sebastienros** [comment]
There are other filters to join a list of values, correct. And don't forget to use the json and raw ones too if they are strings.

**Comment by cellpaddding** [comment]
> There are other filters to join a list of values, correct. And don't forget to use the json and raw ones too if they are strings.

Sorry,I can not understand what your opinion,can you give me some keywords?

**Comment by cellpaddding** [comment]
> Shouldn't the outcome be:
> `"Paths": [ "John", "Paul", "George", "Ringo" ]`
> Could script that with for each...

It's output,not input.

**Comment by psijkof** [comment]
> There are other filters to join a list of values, correct. And don't forget to use the json and raw ones too if they are strings.

`join` (standard liquid) and `json` (orchard filter) could be used to produce the required output:

`"Paths": [ {{ names | json | join ", "  }} ]`

**Comment by cellpaddding** [comment]
> > There are other filters to join a list of values, correct. And don't forget to use the json and raw ones too if they are strings.
> 
> `join` (standard liquid) and `json` (orchard filter) could be used to produce the required output:
> 
> `"Paths": [ {{ names | json | join ", " }} ]`

Thank for your answer.
I try the code like what you write:'[ {{ names | json | join: " , " }} ]'
But,it  seems does not work.

**Comment by psijkof** [comment]
I updated my answer

**Comment by cellpaddding** [comment]
> I updated my answer

I am not sure that are you understand my requirement.
I use the  'Create Content Task' function in a workflow that I custom.
The 'Create Content Task' receives data from form page and converts to a content type .
Last,save the data into database.
Thank you.

**Comment by psijkof** [comment]
You want to generate JSON with Liquid?
If that is the case, then using the `json` filter could simplify the output generation, ex:
`"Text": {{ Request.Form.ContactNumber | json}}` or use `| raw` depending on the content.
Then processing the array, you could use:
` {% for name in names %}
    {{ name | json }},
  {% endfor %}`
It would leave a `,` at the end, which in the last element you don't need, but probably it will not be an issue?

**Comment by sebastienros** [comment]
I think the question is quite well answered now.

**Comment by cellpaddding** [comment]
> You want to generate JSON with Liquid?
> If that is the case, then using the `json` filter could simplify the output generation, ex:
> `"Text": {{ Request.Form.ContactNumber | json}}` or use `| raw` depending on the content.
> Then processing the array, you could use:
> `"Paths": [ {% for name in names %} {{ name | json }}, {% endfor %} ]`
> It would leave a `,` at the end, which in the last element you don't need, but probably it will not be an issue?
> or perhaps, you can try:
> `"Paths": [ "{{ names | join "\", \
