### ISSUE TITLE
Allow upload image from frontend

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3352]
Right now we can upload images if we enable the permission "can access admin" only on a role. Though, I'd like to be able to let the Media role permissions work without needing it. The idea is to be able to also upload from a frontend controller that would use the Media controller upload action. Right now the Media module is only having an AdminController.cs file which is automatically filtered as an admin controller through the AdminFilter.cs file.

**Comment by sebastienros** [comment]
Create a custom controller in your module.

**Comment by Skrypt** [comment]
Yes I could do so but, I guess, I'd also need to copy all the Vue.js component and change their access point to that controller.

**Comment by sebastienros** [comment]
The media module is made for the back-end, if you try to reuse it you will face issues anyhow, or we'll break you eventually. Build you own controller that only does what you need. Also this is weird to add media from the front-end, looks like you don't want them to access the CMS. That's wrong.

**Comment by Skrypt** [comment]
Well I wouldn't mind giving them accces if we could restrict permissions per content type but right now if they find the /admin url they can create all kind of contents which are not restrictable per role. I understand your point. That's why I created the issue. So the proper fix would be to implement simply the content type permission roles to fix my issue.

**Comment by sebastienros** [comment]
If your issue is the content type permissions, then yes. And it will be much simpler to implement too.
