### ISSUE TITLE
Current user unavailable in IRegistrationFormEvents.RegisteredAsync and ILoginFormEvent.LoggedInAsync

### ISSUE THREAD

**Issue by Wej1971** [OrchardCMS/OrchardCore#3353]
I've created a user registration event (implementing _IRegistrationFormEvents_) and a logged in event (implementing _ILoginFormEvent_) and used the following code to get the newly logged in user: -

```
            var principal = _httpContextAccessor.HttpContext.User;
            var user = await _userManager.GetUserAsync(principal);
```

In both cases, the current principal does not reflect the current user, it reflects the previously logged on user (if one exists and did not log out), or a default principal if no previously logged in user existed.

This means that in the first case, the user retrieved from the user manager isn't the current user, and in the second case, the user ends up being null. 

So, if I log in as 'MyUser' and then register a new user, the principal in RegisteredAsync() is as follows: -

```
{System.Security.Claims.ClaimsIdentity}
    Actor: null
    AuthenticationType: "Identity.Application"
    BootstrapContext: null
    Claims: Count = 5
    CustomSerializationData: null
    IsAuthenticated: true
    Label: null
    Name: "MyUser"
    NameClaimType: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
    RoleClaimType: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
```

If the previous user logged out, the principal in RegisteredAsync() is: -
```
{System.Security.Claims.ClaimsIdentity}
    Actor: null
    AuthenticationType: null
    BootstrapContext: null
    Claims: Count = 0
    CustomSerializationData: null
    IsAuthenticated: false
    Label: null
    Name: null
    NameClaimType: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
    RoleClaimType: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
```

Is this because the event is raised before the context is correctly updated with the principal information relating to the current user? Either way, we need a way in these events to get the user for the 'just registered' or 'just logged on' user, rather than the previous user or null

**Comment by Wej1971** [comment]
The other option of course would be to pass in the event, i.e.: -

```
    public interface IRegistrationFormEvents
    {
        Task RegistrationValidationAsync(Action<string, string> reportError);
        Task RegisteredAsync(IUser user);
    }
```

and

```
    public interface ILoginFormEvent
    {
        Task LoggingInAsync(Action<string, string> reportError);
        Task LoggingInFailedAsync();
        Task LoggedInAsync(IUser user);
    }
```

**Comment by sebastienros** [comment]
I agree with the suggestion

TODO: Write a guide on how to customize the registration page with custom fields. It will show the pain points and
