### ISSUE TITLE
WEB API

### ISSUE THREAD

**Issue by mpadula1990** [OrchardCMS/OrchardCore#3356]
I want to consume a web API, this CMS have this posibility??

**Comment by sebastienros** [comment]
Yes, create an MVC controller like in any ASP.NET application.

**Comment by sebastienros** [comment]
Example: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs#L26
