### ISSUE TITLE
Why re-implement Orchard CMS on .NET Core instead of porting older versions?

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#3358]
Older versions of Orchard CMS already have quite powerful features and many third-party modules. The new re-implemented version is brand new and ultra-fast, but unfortunately the old modules are no longer reusable.

So, Why re-implement Orchard CMS on .NET Core instead of porting older versions?

I really want to know what caused this decision.

Thanks!

**Comment by petedavis** [comment]
Start here: https://www.youtube.com/watch?v=TK6a_HfD0O8

**Comment by sebastienros** [comment]
Modules for .NET Framework 4.7 __can't__ work with the ones for dotnet core. It would have been impossible to not break existing modules. They all rely on System.Web which is a totally different set of services than in core.
