### ISSUE TITLE
Workflow expression on DateTime field causes invalid date format exception

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#3359]
I have a content type with a DateTime field, and a workflow activity that a date expression that returns a date time:
```
public WorkflowExpression<DateTime> Start 
{
            get => GetProperty(() => new WorkflowExpression<DateTime?>());
            set => SetProperty(value);
}
```

However there is an issue trying to convert the datetime value stored on the field.

The database stores the UTC value correctly `"Start":{"Value":"2019-03-20T03:30:00Z"}`

When using `WorkflowExpression<string>``to investigate the issue, the following behaviour was discovered:

`{{ Workflow.Input.ContentItem.Content.MyPart.Start }}` returns  `{\\r\\n  \\u0022Value\\u0022: \\u00222019-03-21T02:30:00Z\\u0022\\r\\n}`

and

`{{ Workflow.Input.ContentItem.Content.MyPart.Start.Value }}` returns  `21\\/03\\/2019 2:30:00 AM`

Therefore when trying to create a datetime from `21\\/03\\/2019 2:30:00 AM` it is not in the correct format and causes the exception.

I would expect the Value property to return the string `2019-03-21T02:30:00Z`

**Comment by sebastienros** [comment]
Try that:

`{{ Workflow.Input.ContentItem.Content.MyPart.Start | json |raw  }}` or `{{ Workflow.Input.ContentItem.Content.MyPart.Start | raw }}` if you don't want the `"` added around the date.

**Comment by sebastienros** [comment]
Anything that is between `{{ }}` tags in a template that return json/javascript will be encoded if you are not using `| raw`

**Comment by sebastienros** [comment]
Solved ?
