### ISSUE TITLE
Hosting on Windows with IIS

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#336]
There are 2 pages in the wiki that explain how to run O2 on Docker and Linux. 
We also need a documentation to describe what prerequisites and steps are required to host an O2 instance on Windows with IIS.

Here are 2 interesting articles about publishing and running an ASP.NET Core application with IIS:
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis
https://weblog.west-wind.com/posts/2016/Jun/06/Publishing-and-Running-ASPNET-Core-Applications-with-IIS

I tried to make it work on my local IIS (even if they say it is not really recommended).

Requirements:
- Install .NET Core Windows Server Hosting bundle on IIS
- Restart IIS

Configuration:
- Create a website pointing to a folder containing a published version of the application.
- Set application pool '.NET CLR Version' to 'No Managed code'.
- Configure web.config <aspNetCore /> section.

Will this be a similar process for O2?
or Can I host the application by only copy/pasting the source code?

Orchard.Cms.Web project.json doesn't contain a postpublish script like Orchard.Mvc.Web:
`dotnet publish-iis ...`

Am I supposed to use what is generated by build.cmd?
The 'artifacts' folder seems to contain only dlls.

**Comment by jersiovic** [comment]
> Will this be a similar process for O2?

Yes it is a similar process for O2

> Am I supposed to use what is generated by build.cmd?

You can execute following command from src\Orchard.Cms.Web\ to get what you need to put on the IIS deploy folder:
`dotnet publish --configuration Release --output c:\deployfolder`

**Comment by agriffard** [comment]
When I execute 'dotnet publish', it compiles the projects but there is this message :
`Task 'publish' is not in your gulpfile`
and the command doesn't finish.

**Comment by jersiovic** [comment]
It works for me in the head of master branch. 
If it helps, I'm using Visual Studio 2015 Version 14.0.25421.03 Update 3
Did you installed .NetCore Tools ?
https://www.microsoft.com/net/core#windowsvs2015

**Comment by agriffard** [comment]
OK. It was just really long to finish.

But the project.json should not ontains these scripts because there is no publish task in gulp.js anymore:
```
"scripts": {
    "prepublish": [ "gulp publish" ],
    "postrestore": [ "gulp publish" ]
  }
```
because of this, there is no 'wwwroot' folder generated .

**Comment by agriffard** [comment]
I configured a web site on IIS et published the application in the folder.
I modified the web.config:
```
<system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Orchard.Cms.Web.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
```
but the homepage stays blank and nothing is logged.

Same thing if I execute '`dotnet Orchard.Cms.Web.dll`', it is launched on http://localhost:5000 but nothing appears.
