### ISSUE TITLE
Workflow template expression syntax no longer working

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#3360]
I think there has been a breaking change in dev.

`{{ Workflow.Input.ContentItem.ContentItemId }}` returns null, however:
`{{ WorkflowExecutionContext.Input.ContentItem.ContentItemId }}` works.

Current dev documentation states that `{{ Workflow.Input.ContentItem.ContentItemId }}` is correct.

**Comment by jameshawkins** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/commit/8b339fea85d6a3575198858e6a5a2596994d1764#r32839346

**Comment by sebastienros** [comment]
Can so someone provide a PR that would fix both issues?

**Comment by sebastienros** [comment]
Fixed
