### ISSUE TITLE
Fix workflow documentation

### ISSUE THREAD

**Issue by siyamandayubi** [OrchardCMS/OrchardCore#3363]
In the OrchardCore documentation for workflows, (in Liquid Expressions) we have a table that shows how to access workflow parameters in Liquid expressions.

It must be {{ Workf.ow.Properties["Foo"] }} instead of  {{ Properties["Foo"] }}

**Comment by sebastienros** [comment]
Where is the PR?

**Comment by siyamandayubi** [comment]
In the Readme files it is fixed, but in the online documentation, we have to update it
https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Workflows/README/

**Comment by sebastienros** [comment]
You are using a wrong link, try this one: https://orchardcore.readthedocs.io
