### ISSUE TITLE
Encoding Issue by LiquidWorkflowExpressionEvaluator in Workflows

### ISSUE THREAD

**Issue by siyamandayubi** [OrchardCMS/OrchardCore#3364]
LiquidWorkflowExpressionEvaluator in Workflow has been changed to use System.Text.Encodings.Web.JavaScriptEncoder. It causes a problem in case of sending back the json data, because System.Text.Encodings.Web.JavaScriptEncoder will change the "{, } [ ]" characters to Unicode.  I think here it should be HtmlEncoder like the other places that we have LiquidExpression.

We can reproduce it by trying to pass json string through the Liquid Expression in Workflows.

It has been changed in #3315.

**Comment by sebastienros** [comment]
I want a repro, I still think it's doing it right and you just don't kow how to handle this.

The idea is that your liquid template would be something like:

```
{
  "property": "{{ value }}"
}
```

or 

```
{
 {{ propertAndValue | raw }}
}
```

**Comment by siyamandayubi** [comment]
Yep, with the raw filter it works, I just have to change my workflows :)

**Comment by sebastienros** [comment]
Just think that now it's safer by default ...
