### ISSUE TITLE
Accessing and Rendering external data

### ISSUE THREAD

**Issue by Levivda** [OrchardCMS/OrchardCore#3370]
How to acces data from external database and show in template?

**Comment by PaulEpitomy** [comment]
There are many ways to achieve this, one is to manually construct a ContentItem with data from your own services. This allows you to benefit from Orchards layout/theming

1. Define your own content type using an IDataMigration implementation to add the appropriate Parts/Fields
	NOTE: if you skip this step you will get a NRE when calling BuildDisplayAsync.

```
_contentDefinitionManager.AlterPartDefinition(nameof(YourContentPart), builder => { });
_contentDefinitionManager.AlterTypeDefinition("YourContentType", builder =>
{
	builder.WithPart(nameof(YourContentPart));
});
```

2. Create a controller to access your data e.g. and populate the Parts/Fields

```
public class YourController : Controller, IUpdateModel
{
	private readonly IContentManager _contentManager;
	private readonly IContentItemDisplayManager _contentItemDisplayManager;
	
	//... ctr ommited

	public async Task<ActionResult> GetExternalData(string id)
	{
		var contentItem = await _contentManager.NewAsync("YourContentType");

		var yourContentPart = new YourContentPart
		{
			Data = await _externalDataService.GetData(id)
		};
		contentItem.Apply(yourContentPart);

		var shape = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, this);
		return View(shape);
	}
}

public class YourContentPart : ContentPart
{
	public object Data { get; set; }
}
```

3. Create a View for the Action View\Your\GetExternalData.cshtml

```
@await DisplayAsync(Model)
```

4. You can then treat this like any custom ContentPart with handler/drivers
	
As an alternative to retrieving data in the controller you could implement an IContentPartHandler.

**Comment by Levivda** [comment]
Many thanks!! But can you explain step 3 and 4 please
