### ISSUE TITLE
Shapehelper

### ISSUE THREAD

**Issue by Levivda** [OrchardCMS/OrchardCore#3371]
Does orchard core has a shapehelper to add a property to a shape?

**Comment by sebastienros** [comment]
I think we should have custom properties on the Shape, like we already have `Attributes` and `Classes`, but we could have `Properties`. Another option is to use `Attributes` and add something like `data-foo` that can be read from the shape template.

**Comment by hishamco** [comment]
While the shape is a dynamic object you could add properties as many as you want, @sebastienros I'm not sure why we need to have `Properties` while we can add them directly?

**Comment by sebastienros** [comment]
In OC shapes are not all dynamic objects base on Expando anymore. This is why I am suggesting to add thie `Properties` member, which is the equivalent as the `ViewBag` for views.

**Comment by sebastienros** [comment]
Example: `HtmlBodyPartViewModel` is used to create a sub-class (proxy) and is not a dynamic object.

**Comment by hishamco** [comment]
> In OC shapes are not all dynamic objects base on Expando anymore

Oh really!! I thought it is .. if is that we need to

**Comment by jtkech** [comment]
For infos the `IShape` that are `Shape` inherit from `Composite` that already have a `Properties` property.

**Comment by hishamco** [comment]
> For infos the IShape that are Shape inherit from Composite that already have a Properties property.

If is that we need to close this one

**Comment by sebastienros** [comment]
No we need to add the declaration to the interface for it to be complete.
