### ISSUE TITLE
Clicking on the menu "Blog" is reset instead of locating the current

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#3372]
@matiasmolleja 

![2](https://user-images.githubusercontent.com/28694676/54815296-9ba79000-4ccc-11e9-9a21-d855e7280a54.gif)

**Comment by sebastienros** [comment]
Expected behavior, it's listing all the blogs. The solution is to remove the Listable option from this type.

**Comment by pgy866** [comment]
There is no problem with the content list. When you click "BLOG", the menu will return to the main menu. It is not like the other menus.
