### ISSUE TITLE
Workflow javascript functions not works

### ISSUE THREAD

**Issue by MohitNaroliya** [OrchardCMS/OrchardCore#3373]
When I tried to set If/Else condition control flow to check my published content input properties, workflow throw fault exception with Input is not defined fault message. 
I am able to get all input properties in liquid but can't able to get in javascript expression.

**Comment by jptissot** [comment]
Did you try property('propertyName') ?

**Comment by sebastienros** [comment]
Please provide more details about your issue and how we can repro it.
