### ISSUE TITLE
Liquid Editor display is abnormal

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#3376]
![liquidEdtiorError](https://user-images.githubusercontent.com/15613121/54844634-4bebb780-4d12-11e9-9eab-1776b1ea4783.gif)

**Comment by sebastienros** [comment]
I can't repro, looks good for me, can you check your console and network tab?

![image](https://user-images.githubusercontent.com/1165805/54856037-e23dc000-4cb5-11e9-9fe6-677bcdd9a602.png)

**Comment by sebastienros** [comment]
Scratch that, I can actually repro it too, when we reload the page and expand the widget

**Comment by sebastienros** [comment]
![image](https://user-images.githubusercontent.com/1165805/54856106-2cbf3c80-4cb6-11e9-8fd9-4a439f72d338.png)
