### ISSUE TITLE
Safari UI Issue on Collapsible Admin Menu Items

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#3377]
Appears to look fine in Chrome and Firefox, but when in Safari on macOS there is a little _visual disturbance_ that appears on collapsible admin menu items.

This is using the latest Dev Branch and Blog Recipe for the default tenant.

<img width="276" alt="safari" src="https://user-images.githubusercontent.com/96801/54845997-3db97f00-4cb1-11e9-9cf1-e223aa33723f.png">

<img width="259" alt="safari2" src="https://user-images.githubusercontent.com/96801/54846079-6b9ec380-4cb1-11e9-9cb1-9258a24028d8.png">

**Comment by Skrypt** [comment]
Could you try and refresh your browser cache because this is something that reminds me that.

**Comment by Skrypt** [comment]
I just tested on Safari Mac and I can't repro

**Comment by davidhayden** [comment]
Good call. Clearing the browser cache solved the problem. Thank you. I'll remember to do that when noticing any UI disturbances.
