### ISSUE TITLE
Support Arabic Translation

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3391]
Based on the @agriffard's comment https://github.com/OrchardCMS/OrchardCore/issues/3015#issuecomment-476393261 I was interested to add an Arabic translation, but this is the first time I see `Crowdin`, could you please add the Arabic, so I can start the translation  ..

**Comment by sebastienros** [comment]
Can we also add the other languages we already have for O1 ?

**Comment by agriffard** [comment]
Ok, cultures added. 
You need to create an account on Crowdin and ask to be added to a target language.

**Comment by sebastienros** [comment]
@hishamco how are "Arabic" and "Arabic, Yemen" different? IS that comparable to English-UK and English-US?

**Comment by hishamco** [comment]
I'm working on Arabic right now, which is make sense for all Arabic cultures, @agriffard you can delete **Arabic, Yemen**

**Comment by sebastienros** [comment]
@hishamco 

If you need to test it, here is the PR with the guide on how to do it

https://github.com/OrchardCMS/OrchardCore/pull/3397/files

**Comment by hishamco** [comment]
Thanks so much Seb
