### ISSUE TITLE
Unable to create content of type taxonomy

### ISSUE THREAD

**Issue by idontbyte** [OrchardCMS/OrchardCore#3402]
Attempting to use the taxonomy module, however I am completely stuck -

Instructions i have been given -
> Taxonomy is a content type, you can create instances of it. To list them you use the Content Items page. To edit one you just click edit on one.

The problem -
I can find no way of enabling a taxonomy content type, I cannot create one, or create a definition that is a taxonomy as far as I can tell.

Using the Nuget feed, latest.

**Comment by idontbyte** [comment]
I have just created a new blank project and used SqlLite db and after I enable Taxonomy module I can see the Taxonomy Content Type straight away, so it must be something to do with my project.
I am using an Azure SQL database, but otherwise I can't find any differences between the two, I will test Azure DB in a third project.

**Comment by idontbyte** [comment]
Looks like Taxonomies doesn't work with the following module:
File Content Definition
Stores Content Definition in a local file.

**Comment by sebastienros** [comment]
File Content Definition is the default provider.
What version are you using?

**Comment by idontbyte** [comment]
1.0.0-beta3-71025
Reproducible with a fresh site, works ok if you use DB instead of file for content types.

**Comment by sebastienros** [comment]
Thanks, will try to repro, though many are using this feature

**Comment by sebastienros** [comment]
Haven't had a chance to try an repro it yet

**Comment by jptissot** [comment]
@sebastienros  I just tried a repro, everything seems to work fine on latest dev

1. Setup new tenant with blank recipe
2. Login to admin, enable taxonomy module
3. Create TaxType ContentType with TitlePart
4. Create new Taxonomy and assign the TermType to the Taxonomy. 
5. Save Draft taxonomy
6. Create a bunch of terms

**Comment by jptissot** [comment]
[TaxonomiesRecipe.zip](https://github.com/OrchardCMS/OrchardCore/files/3521642/TaxonomiesRecipe.zip)

**Comment by jptissot** [comment]
What I did find however is that when Running a DeploymentPlan for a taxonomy, the terms do not get exported properly in the json. IE: The child terms are not exported at all.
Also, if you try to import the zip I just posted, the Taxonomy ContentItem is not restored.

**Comment by jptissot** [comment]
Just tried this on our dev instance deployed on kubernetes (which is using Postgresql) and everything works as expected (we mount a Volume to `/App_Data`.

**Comment by jptissot** [comment]
@idontbyte Maybe a write permission issue on the App_Data folder ?

**Comment by sebastienros** [comment]
@idontbyte if you can still repro please share some steps and reopen this issue
