### ISSUE TITLE
Disabled Recipe module, broke site

### ISSUE THREAD

**Issue by idontbyte** [OrchardCMS/OrchardCore#3403]
After I disabled the recipe module I got this error:
InvalidOperationException: Unable to resolve service for type 'OrchardCore.Recipes.Services.IRecipeMigrator' while attempting to activate 'OrchardCore.Menu.Migrations'.

I re-enabled recipe module in the database but it did not fix the error.

**Comment by idontbyte** [comment]
Also disabling 'Navigation' module breaks site with error:
Exception: Shape type 'Navigation' not found
Tried re-enabling in database, but error persists, trying to find out what was modified when disabling these modules so I can flip it back

**Comment by idontbyte** [comment]
Found out you have to add back to database in orchard__Documents - type OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Abstractions 
and also flip back on in type OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Abstractions 

It seems dangerous that turning off modules can break the admin area, not sure what the best fix would be though.

**Comment by idontbyte** [comment]
Had some thoughts about this..
If you disable the minimum required modules to run the CMS (ignoring warnings) then when you visit /admin the system could prompt to re-enable them automatically given a successful login.

**Comment by davidxchen** [comment]
How do you re-enable the recipes module? I just accidentally disabled mine. Now, the whole site is showing a blank page.

**Comment by sebastienros** [comment]
@jtkech can you check what is the manual operation to do to re-enable it from the db?

**Comment by jtkech** [comment]
Sorry jut came back.

In the `ShellDescriptor` table re-add

    {"Id":"OrchardCore.Recipes","AlwaysEnabled":false},

In the `ShellState` table replace

    {"Id":"OrchardCore.Recipes","InstallState":"Up","EnableState":"Down"},

With

    {"Id":"OrchardCore.Recipes","InstallState":"Up","EnableState":"Up"},

**Comment by MatthijsKrempel** [comment]
Is it an idea to make a property on the FeatureAttribute like a FeatureTypeEnum (Setup, Extension, CMS, Core, etc..) and prevent Core features from being disabled?

**Comment by jtkech** [comment]
Just for infos, if the `Category = "Core"`, it doesn't prevent the feature from being disabled but at least in the admin `Features` page it doesn't show up the disable button.

Maybe the `Category` of some features could be changed to `Core` and / or update the checking in `Features.cshtml`.

**Comment by MatthijsKrempel** [comment]
I see that there is already a boolean in place to not allow certain features not to be disabled, I think the course of action would be to use that boolean and add more modules to it.

**Comment by MatthijsKrempel** [comment]
@agriffard @sebastienros  I think this can be closed.

**Comment by deanmarcussen** [comment]
Closed by https://github.com/OrchardCMS/OrchardCore/pull/4259
