### ISSUE TITLE
Import/Export module with IScopedIndexProvider Primary Key constraint violation

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3405]
I'm getting this issue when using SQL Server and using the Import/Export module. I'm trying to import data from an export I made. It fails when it tries to execute my custom IScopedIndexProvider. I tried adding a record manually in the admin and it works without any issue. So, the issue is only happening when I'm trying to import data with the Import/Export module.

I thought that issue was that I was missing a IRecipeStepHandler but the issue remains after adding one.

```
SqlException: Violation of PRIMARY KEY constraint 'PK__Document__3214EC072F90175E'. Cannot insert duplicate key in object 'dbo.Document'. The duplicate key value is (1581).
The statement has been terminated.
```

**Comment by Skrypt** [comment]
I think I found where the issue is. I need to implement a IRecipeStepHandler for my custom IScopedIndexProvider.

**Comment by Skrypt** [comment]
Issue is related with the fact that RecipeExecutor is not adding content item versions of Versionable content type items.

**Comment by Skrypt** [comment]
This is the issue with the IndexProvider that could block merging

https://github.com/OrchardCMS/OrchardCore/pull/3133

Though, I've not had issues with the field indexing and import/export module using the code in that PR. Just had issue with a different custom index that requires using the ContentManager to index different values depending on the Content Type indexed.

**Comment by jptissot** [comment]
@Skrypt I would be curious to see if this is still an issue. I have seen something similar in workflows (i forget exactly what I was doing) But if I remember correctly, Sebastien or Jean-Thierry fixed something in the Shell or YesSql that fixed the issue.

**Comment by Skrypt** [comment]
I think the issues still remains. We need to check in the RecipeExecutor if it can import drafts (content items with a ContentItemVersionId). We need to first verify if it makes sense to import those drafts. I don't remember exactly what it was doing in 01. Though here the issue is that when we are importing content items it lists also the drafted content items and tries to add duplicates since we never import a ContentItemVersionId. This has nothing to do with the IScopeIndexProvider which got fixed by adding a Session.CommitAsync on it's dispose directly.

**Comment by jptissot** [comment]
I think we ran into this yesterday. We accidently ran a recipe that had the ContentItemId's hardcoded and it created duplicates and the content items would dissapear from the admin. I had to manually go into the db and set the Latest and Published flags manually.

**Comment by deanmarcussen** [comment]
> just had issue with a different custom index that requires using the ContentManager to index different values depending on the Content Type indexed.

@Skrypt I see where the potential for issues exists if you're using the ContentManager to Get versions of a content item in your indexer (due to the `contentmanagersession`)

Can you share a bit of code that actually does this, so I can understand why?

**Comment by Skrypt** [comment]
@sebastion does the Document table version column could have fixed this issue?
