### ISSUE TITLE
Custom editors for TitlePart, AliasPart and AutoroutePart

### ISSUE THREAD

**Issue by inhumator** [OrchardCMS/OrchardCore#3406]
Could you help me in creating custom editors for TitlePart, AliasPart and AutoroutePart ?

I managed to add a custom HtmlBodyPart and TextField editor views but I have trouble with TitlePart, AliasPart and AutoroutePart. My custom option does show up in config dropdown but after selecting it the parts are still rendered using the default built-in editors.

Regards.

**Comment by sebastienros** [comment]
Can you share your code somewhere?

**Comment by agriffard** [comment]
Closing because no answers after a long period of time.
