### ISSUE TITLE
SendMail Error

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#3407]
HOST smtp.exmail.qq.com ，Enable SSL，Port 465

This server is not mail.qq.com , it's a Tencent mail server for  enterprise .

We can use the mail box on Outlook , Foxmail , windows 10 mail client and other email clients.
[https://service.exmail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1000564#2](url)

But it cann't run on OrchardCore. 

```An error occurred while sending an email: 'Syntax error, command unrecognized. The server response was: ' ```

I cann't get more infomation form this error .

**Comment by hyzx86** [comment]
Found the class at msdn 
[https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?redirectedfrom=MSDN&view=netcore-3.0](url)

`[System.Obsolete("SmtpClient and its network of types are poorly designed, we strongly recommend you use https://github.com/jstedfast/MailKit and https://github.com/jstedfast/MimeKit instead")]
public class SmtpClient : IDisposable`

Should we replace system.net.mailwith MailKit?

 

> All of the other .NET IMAP client implementations that I could find suffer from major architectural problems such as ignoring unexpected untagged responses, assuming that literal string tokens will never be used for anything other than message bodies (when in fact they could be used for pretty much any string token in a response), assuming that the way to find the end of a message body in a FETCH response is by scanning for ") UID", and not properly handling mailbox names with international characters to simply name a few.

**Comment by sebastienros** [comment]
Sounds good.

**Comment by hyzx86** [comment]
https://github.com/dotnet/corefx/issues/33480

There is a patch here, but I don't know when it will take effect.

**Comment by hyzx86** [comment]
It  only fixed in version 3.0 ..

**Comment by hishamco** [comment]
Can we replace it with the default one or shall create a new module ``OrchardCore.Email.MailKit`?

**Comment by hyzx86** [comment]
> Can we replace it with the default one or shall create a new module ``OrchardCore.Email.MailKit`?

I have tried , but there is many module depend on  Email Module.
and I havent deep undstand all of the Mailkit's parameters, 
only rewrited the sendmail codes

https://github.com/hyzx86/OrchardCore/blob/fd1787a585efe6b735e3b71c18f10e7976ee4548/src/OrchardCore.Modules/OrchardCore.Email/Services/SmtpService.cs#L30

**Comment by hishamco** [comment]
There 're many params and features in MailKit, I already did an experiment to make this work, waiting for @sebastienros to answer my earlier question, because modifying this many needs some refactoring, because we will not rely on `System.Mail.SmptClient` anymore
