### ISSUE TITLE
Media Liquid Filter 'resize_url' Not Utilizing 'mode' in Position 3

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#3408]
The [documentation](https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Media/README/#arguments) shows that "mode" can just be the third argument, but the actual C# code shows:

```
var mode = arguments["mode"];
```

It seems like it should be this way to work properly:
```
var mode = arguments["mode"].Or(arguments.At(2));
```

To see this in action, the following will not resolve with "rmode=" appended:
```
<img src="{{ imagePath | asset_url | resize_url: 1024, 600, "min" }}" />
```

But this will:
```
<img src="{{ imagePath | asset_url | resize_url: width:1024, height:600, mode:"min" }}" />
```

**Comment by sebastienros** [comment]
I agree with the suggested fix
