### ISSUE TITLE
Bug: In the workflow, use "Join Task", when selecting "WaitAll", use Normal, when "WaitAny" is selected, the program crashes.

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#3409]
In the workflow, use "Join Task", when selecting "WaitAll", use Normal, when "WaitAny" is selected, the program crashes.
![image](https://user-images.githubusercontent.com/16968103/55206368-2d555700-5211-11e9-9ea3-395fa54c0c6e.png)
![image](https://user-images.githubusercontent.com/16968103/55206400-465e0800-5211-11e9-9d32-507557a60a37.png)

**Comment by agriffard** [comment]
No errors in my tests.
