### ISSUE TITLE
What is Orchard Core Framework?

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3417]
Is it fair to say that Orchard Core Framework is essentially these three packages?

- OrchardCore
- OrchardCore.Abstractions
- OrchardCore.Mvc.Core

**Comment by sebastienros** [comment]
You can do modular app without MVC too. However \nNot sure if the dependency isn't still necessary.

You could also say that the modules that are not CMS modules are part of the framework, or it's just an ecosystem of module for the base framework. Like Localization, ResourceManagement, Theming, all these are optional parts of the framework and can be used independently of the CMS.
