### ISSUE TITLE
Problem with script and stylesheet tags from widgets used in layers

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/OrchardCore#3418]
Following issue #3198 , the workaround did not solve my problem, neither by prerendering the zones in the layout.liquid nor prerendering the zones in ThemeLayout.cs .

I have created a Module that defines some map widgets. In the part's template, I add  the css and the js based on the map that the user wants to show. If it is used in a Flow, it works as expected.
eg The ComingSoonTheme. If it is used in a layer, it does not. eg. AgencyTheme.

Is there any solution to this problem?

**Comment by jeffolmstead** [comment]
@MichaelPetrinolis do you have the zones pre-rendered before rendering your resources? Here is an example that seems to work fine in Liquid:

```
  {% comment %} Precompile zones so any embedded resources are resolved {% endcomment %}
  {% assign messagesZone = Model.Messages | shape_stringify %}
  {% assign beforeContentZone = Model.BeforeContent | shape_stringify %}
  {% assign contentZone = Model.Content | shape_stringify %}
  {% assign afterContentZone = Model.AfterContent | shape_stringify %}
  {% assign beforeFooterZone = Model.BeforeFooter | shape_stringify %}
  {% assign footerZone = Model.Footer | shape_stringify %}
  
  <!-- Resources -->
  {% resources type: "HeadScript" %}
  {% resources type: "HeadLink" %}
  {% resources type: "Stylesheet" %}
```
All of this is in the "head" tags. Just add in all the zones you need pre-rendered. Look forward to hearing back.

**Comment by MichaelPetrinolis** [comment]
Thank you @jeffolmstead , it seems that it failed because I did not shape_stringify the zones in the head tag before the resources tags. I tested and works as expected.

**Comment by sebastienros** [comment]
If you can, don't use Layers, prefer a custom Section content type that is based on Flows, give it an alias, and render it directly in your themes like we do for the menu, based on some condition (the same as in javascript). It will be faster to render, and you can even cache it's content to prevent the section from being loaded from the database.

**Comment by MichaelPetrinolis** [comment]
@sebastienros thank you, will do so. Maybe we should modify one of the two OOB templates (agency or blog) and change the footer layer to footer content item ?
