### ISSUE TITLE
OrchardCore.OpenId Error: Could not run migrations automatically

### ISSUE THREAD

**Issue by Chris533** [OrchardCMS/OrchardCore#3421]
```
warn: OrchardCore.OpenId.EntityFrameworkCore.Startup[0]
      The OpenID Connect module is not correctly configured.
fail: OrchardCore.Data.Migration.DataMigrationManager[0]
      Could not run migrations automatically on 'OrchardCore.OpenId.Management'
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in /../src/OrchardCore/OrchardCore.Data/Migration/DataMigrationManager.cs:line 175
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAllFeaturesAsync() in /../src/OrchardCore/OrchardCore.Data/Migration/DataMigrationManager.cs:line 364

```

**Comment by sebastienros** [comment]
Can you share some repro steps?

**Comment by Chris533** [comment]
Hi, thanks for your reply.
normal configuration with fresh installation,
error in -post /connect/token, 
both of default and tenant.

Steps(MacOS)
1. Clone and build
```
git clone https://github.com/OrchardCMS/OrchardCore.git XCMS && cd $_
dotnet build
cd src/OrchardCore.Cms.Web && dotnet run
```
2. Enable OpenID Modules and Settings(default, tenant).
3. Test in Postman
```
POST /connect/token x-www-form-urlencoded
   
grant_type:password
client_id:...
client_secret:...
username:...
password:...


Variable | Value
-- | --
Accept | */*
Accept-Encoding | gzip, deflate
Cache-Control | no-cache
Connection | keep-alive
Content-Length | 91
Content-Type | application/x-www-form-urlencoded
Host | localhost:5000
Postman-Token | e070838f-e8a3-4fa9-890f-ae9826cbbdbb
User-Agent | PostmanRuntime/7.6.1


```
error

>An unhandled exception occurred while processing the request.
>
>MySqlException: Table 'dbname.prefix_openidauthorizationindex' doesn't exist
>MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task<ArraySegment<byte>> task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs, line 1240
>
>MySqlException: Table 'dbname.prefix_openidauthorizationindex' doesn't exist
>MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs, line 74

**Comment by Chris533** [comment]
PS: also error in Save http://localhost:5000/OrchardCore.OpenId/Scope/Create or http://localhost:5000/tenant/OrchardCore.OpenId/Scope/Create

>An unhandled exception occurred while processing the request.
>MySqlException: Table 'mydbname.myprefix_openidscopeindex' doesn't exist
>MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task<ArraySegment<byte>> task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs, line 1240
>
>MySqlException: Table 'mydbname.myprefix_openidscopeindex' doesn't exist
>MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs, line 74

**Comment by Piedone** [comment]
This doesn't seem to be the issue with the current version. Please reopen if it is.
