### ISSUE TITLE
Form value count limit 1024 exceeded.

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#3422]
I have a content type with a bag part.  It is a complicated bag.  For one content item, my client has put in many many things in to this bag part, and she gets this exception in the log when she submit the form.

> Microsoft.AspNetCore.Server.Kestrel|ERROR|Connection id "0HLLL4GE8UNN3", Request id "0HLLL4GE8UNN3:00000001": An unhandled exception was thrown by the application. System.IO.InvalidDataException: Form value count limit 1024 exceeded.

I have tried adding the following to the main project's `startup.cs`, but it doesn't take effect.
```
services.Configure<FormOptions>( options => {
                options.ValueCountLimit = 4096;
            });
```

What is the correct way to fix this?

Thanks!

**Comment by MichaelPetrinolis** [comment]
when I faced this problem, this worked for me. 
```     public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<FormOptions>(x => x.ValueCountLimit = 2048);
            services.AddOrchardCms();
        }
```

**Comment by awyl** [comment]
Thanks. It works now.
