### ISSUE TITLE
AutoroutePart not registering URL when creating new contentItem

### ISSUE THREAD

**Issue by MohitNaroliya** [OrchardCMS/OrchardCore#3433]
When I  trying to add an Autoroute Part to a Content Type item AutoroutePartIndex not creating but when I trying to update same entry with same content type item it's work, I assume this is a bug and this AutoRoutPartIndex should register when create new contentItem. 

Below code for creating new Content Type Item - 
```C#
var contentItem = await _contentManager.NewAsync(_id);
var advForm = new AdvancedForm(viewModel.Description, viewModel.Instructions, viewModel.Container, viewModel.Title, viewModel.Header, viewModel.Footer, viewModel.Type, 
                viewModel.AdminContainer, viewModel.HtmlContainer, viewModel.AdminHtmlContainer);

contentItem.Content.AdvancedForm = JToken.FromObject(advForm);
contentItem.DisplayText = viewModel.Title;
contentItem.Content.AutoroutePart.Path = CreatePath(viewModel.Title);

await _contentManager.CreateAsync(contentItem, VersionOptions.Draft);
await conditionallyPublish(contentItem);
```

above code creating content type item but not creating autoroutpart index record. this code was working 2 weeks ago but now no longer works. 

Below is created content type update code - 
```C#
string contentItemId = viewModel.Id;
var contentItem = await _contentManager.GetAsync(contentItemId, VersionOptions.DraftRequired);
var advForm = new AdvancedForm(viewModel.Description, viewModel.Instructions,
                viewModel.Container, viewModel.Title, viewModel.Header, viewModel.Footer, viewModel.Type, 
                viewModel.AdminContainer, viewModel.HtmlContainer, viewModel.AdminHtmlContainer);

contentItem.Content.AdvancedForm = JToken.FromObject(advForm);
contentItem.DisplayText = viewModel.Title;
contentItem.Content.AutoroutePart.Path = CreatePath(viewModel.Title);

await conditionallyPublish(contentItem);
_session.Save(contentItem);
var typeDefinition = _contentDefinitionManager.GetTypeDefinition(contentItem.ContentType);
```

this issue looks same as [#2755](https://github.com/OrchardCMS/OrchardCore/issues/2755)

**Comment by Skrypt** [comment]
Why are you calling `_session.save(contentItem);` in the update code? The `conditionallyPublish(contentItem);` code already does it.

**Comment by MohitNaroliya** [comment]
Hi @Skrypt - Thanks for your reply 
![image](https://user-images.githubusercontent.com/26460323/55555989-1aa4bb80-5704-11e9-8bc8-a539d5cd21f2.png)
in above image I have set contentItem.Content.AutoroutePart.Path value but when I see in the contentItem element autoroutpart value path have null, value not set up. If I set path value in run time direction in contentItem element autoroutpart directly it saved successfully. Could you please suggest what I am missing there?

**Comment by Skrypt** [comment]
What does your CreatePath returns?

**Comment by MohitNaroliya** [comment]
It returns "AdvancedForms/Test-Advanced-forms" string, that path value you can seen in Content value.

**Comment by Skrypt** [comment]
We can see it in Data value too. I'm wondering what your CreatePath() method simply returns there because it feels like some values are attributed to the AutoroutePart but not to the Path property.

**Comment by Skrypt** [comment]
Try contentItem.AutoroutePart.Path instead.

**Comment by MohitNaroliya** [comment]
You mean instead of contentItem.Content.AutoroutePart.Path

**Comment by Skrypt** [comment]
Forget my last comment ;)

**Comment by Skrypt** [comment]
Can you show me what the CreatePath method returns by setting a watcher on it?

**Comment by MohitNaroliya** [comment]
Sure
![image](https://user-images.githubusercontent.com/26460323/55557117-bf27fd00-5706-11e9-8899-fb8380d133ec.png)

**Comment by MohitNaroliya** [comment]
2 weeks ago I had OC packages upgrad than that code no longer works :(

**Comment by Skrypt** [comment]
The issue happens with a Nuget package solution that uses latest packages. I looked at the solution debugger and it's not generating any autoroutePart even from the DisplayText value which should be taken from the TitlePart of it's content type definition.

**Comment by jptissot** [comment]
Related to this maybe ? #3419

**Comment by jptissot** [comment]
Anytime we set the content via json the indexes are not properly created because the part properties are null.

**Comment by sebastienros** [comment]
When an `AutoroutePart` is created from a content item it has taken the value from json. If you then update the json directly, then the `AutoroutePart` instance doesn't get it, you need to either clear all the cached parts, or update the `AutoroutePart` instead of changing the json. You can use the `Alter` extension method to simplify that.

**Comment by Skrypt** [comment]
It used to work with the AutoroutePart.

**Comment by sebastienros** [comment]
I explained on the chat that this doesn't work since my changes on the cached parts.

**Comment by sebastienros** [comment]
TODO: Add method to clear the parts cache

**Comment by MohitNaroliya** [comment]
`contentItem.Alter<OrchardCore.Autoroute.Model.AutoroutePart>(x => x.Path = path);`
Above code does works and changed AutoroutePart Path, so that I assume it as temporary fix?
Thanks for your reply.

**Comment by sebastienros** [comment]
Can we still repro this?
