### ISSUE TITLE
Workflows and Forms : Accessing Form Data

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrchardCMS/OrchardCore#3446]
I've set up a form that posts to a Workflow HttpRequest endpoint, yet I cannot retrieve the form data. I've tried accessing using {{ Request.Form.Email }} etc. and using this to create a content item, but I don't get any data.

If I POST JSON data I can get that using the JSON data (as per the docs). Just not form data.

**Comment by MichaelPetrinolis** [comment]
Check The Coming Soon template, The User Registration workflow accesses the posted form data

**Comment by GadgetGeekUK** [comment]
Yes, I've tried a bind, and at the moment a simple log of the value submitted.
![image](https://user-images.githubusercontent.com/13166551/55723784-c6e6ea80-5a01-11e9-9fe7-54790317af5f.png)

**Comment by GadgetGeekUK** [comment]
The logging works, for the following Content Item, what do I specify in order to populate the 'Email' Field?
![image](https://user-images.githubusercontent.com/13166551/55785440-57790580-5aaa-11e9-9868-99eea6c695bc.png)
I've tried, amongst others:
`
{
  "ContactRequest": {
    "Name": "Email",
    "Value": "{{ Request.Form.Email }}"
  }
}
`

`
{
  "ContactRequest": {
    "Email": "{{ Request.Form.Email }}"
  }
}
`

**Comment by Skrypt** [comment]
I'm using a javascript function to convert my Form Data values to JSON. That would replace the BIND element of your workflow. Please look at the documentation to find javascript methods that you can use.

**Comment by GadgetGeekUK** [comment]
REF: https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Forms/
The documentation for Forms already shows the use of form data e.g. {{ Request.Form.Email }} however there is not an explicit example of matching form data to a new Content Items Parts/Fields.

Given my above example, what is the correct JSON format to be used in the Create Content Workflow task?

**Comment by GadgetGeekUK** [comment]
It turns out that the correct answer is:
`{
  "ContactRequest" : {
  	"Email": {
  		"Text": "{{ Request.Form.Email }}"
	}
  }
}`

I was missing the property of the content part.

Hopefully these current issues will help make this sort of thing easier:
https://github.com/OrchardCMS/OrchardCore/issues/1820
https://github.com/OrchardCMS/OrchardCore/issues/1505
