### ISSUE TITLE
Form/workflow in recipe linked via token and http request event doesn't work unless token is regenerated

### ISSUE THREAD

**Issue by Wej1971** [OrchardCMS/OrchardCore#3447]
I have a workflow that uses an HTTP request event with a token, and a form that posts to the same token. These are in a recipe, and are set up correctly by the recipe. However, the Workflow never activates and I get a not found error instead. If I then regenerate the token in the HTTP request event and then paste this new token in the form, the workflow will then activate correctly.

How do I get this to work without going into the workflow and form post recipe setup and regenerating the token?

**Comment by MichaelPetrinolis** [comment]
Check how the Coming Soon recipe creates the token
          "FormPart": {
            "Action": "[js: getUrlPrefix('/workflows/invoke/' + encodeURI(createWorkflowToken(variables('workflowTypeId'), variables('workflowActivityId'))))]",
            "Method": "POST"
          }

**Comment by Skrypt** [comment]
I have the same issue where I exported my Worflows but I needed to regenerated the HttpRequest event token url so that it works. Maybe it's by design or something needs to be fixed.
@sfmskywalker

**Comment by sfmskywalker** [comment]
Sounds like a bug that ought to be fixed.

**Comment by Wej1971** [comment]
Works fine using the method described by @MichaelPetrinolis - thank you

**Comment by arkadiuszwojcik** [comment]
@sfmskywalker @Skrypt @Wej1971 I think this issue should be reopen. This is related to current implementation of createWorkflowToken. Right now it is creating 7 days valid token so it means that after 7 day generated URL is not valid. Don't know wht is proper soultion but at least there should be comment in Coming Soon theme recipe that token will be valid just 7 days.

**Comment by Skrypt** [comment]
You sure this is valid for only 7 days? @sfmskywalker

**Comment by arkadiuszwojcik** [comment]
So according to source code: [SignalMethodProvider](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Workflows/Http/Scripting/SignalMethodProvider.cs) and function: `createWorkflowToken ` when timespan parsing fails - and in case of recipe script we are not passing timetamp (so I'm assuming null or "") then line: `timespan = TimeSpan.FromDays(7);` is executed;

**Comment by Skrypt** [comment]
From a recipe then.

**Comment by arkadiuszwojcik** [comment]
@Skrypt I just debugged TheComingSoon theme on my PC, and when `createWorkflowToken ` is hit `lifetime `fuction argument is null so 7 days expiration token is generated.
