### ISSUE TITLE
Coming soon: Wrong link to confirm email

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3448]
I tried the Coming soon theme and there are some errors with the confirmation link sent from a workflow when you fill the form on the homepage:
- If you are in a tenant, the link does not contain the prefix url.
- The email send does not have any subject.
- The generated link in the email contains a wrong character, may be due to a bad encoding: `https://localhost:44300//OrchardCore.Users/Registration//ConfirmEmail?userId=12\u0026code=...`
`\u0026` instead of `&`

**Comment by Skrypt** [comment]
use liquid | raw

**Comment by agriffard** [comment]
Ok, changing in the workiflow activity to `{{ Workflow.Properties.EmailConfirmationUrl | raw }}` fixes the format of the url but when I click on the url, it returns a 404.

The code does not seem to be correct because if I click on 'Send verification email' from the admin users page, it is different in the generated link.

**Comment by DavidStania** [comment]
This bug seems to still exist. I receive an email but the link itself is empty.
