### ISSUE TITLE
Maybe FormPart Need a Content-Type Parameter

### ISSUE THREAD

**Issue by xiaolizi007** [OrchardCMS/OrchardCore#3461]
In OrchardCore.Form  Module , FormPart has no Content-Type parameter field to set , the default value is "Content-Type: application/x-www-form-urlencoded" , but the application/json type is  what the workflow module need to parse for next step used . 

If i use form submit to workflow , it will rais a exception "Unexpected end of input" .

**Comment by ns8482e** [comment]
@sebastienros @agriffard shouldn't this be closed? fixed in PR #6053

**Comment by deanmarcussen** [comment]
Closed by https://github.com/OrchardCMS/OrchardCore/pull/6053
