### ISSUE TITLE
RuntimeBinderException : Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3464]
![image](https://user-images.githubusercontent.com/3228637/56071563-56bbca00-5d5d-11e9-914d-e1bf5494377a.png)

This started happening on Azure Web App since I added the option to have the /refs folder on my published code. This happens only when the website is warming up on first load after a restart of the app.

**Comment by dlidstrom** [comment]
I see this too in my local macOS. Happened after initial Setup was completed (I chose Blog recipe). I see the tables in postgres have been created.

**Comment by sebastienros** [comment]
> since I added the option to have the /refs folder on my published code

remind me why you need that?

**Comment by Skrypt** [comment]
I don't need it anymore. Just reporting the issue since it seems related to app warmup or tenants initialization.

**Comment by Skrypt** [comment]
Resolved by removing

```xml
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
```

In my OrchardCore.Cms.Wep .csproj file.
