### ISSUE TITLE
Exception：Unable to cast object of type 'OrchardCore.ContentManagement.ContentPart' to type......

### ISSUE THREAD

**Issue by Loneve** [OrchardCMS/OrchardCore#3466]
Upgrade to beta3, there is an exception when running:
`var part = contentItem.As<MyPart>();`

**System.InvalidCastException:“Unable to cast object of type 'OrchardCore.ContentManagement.ContentPart' to type...**

in the file: \OrchardCore-1.0.0-beta3\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\ContentExtensions.cs

Change the Method `Get` to:

![Get](https://user-images.githubusercontent.com/44474195/56077576-765ffa80-5e10-11e9-8822-9764d955b87f.png)

**And then it works well.**

Is there something wrong with `contentElement.Elements.TryGetValue()`?

ps:
Define `MyPart` using `.WithField()`,ex: TaxonomyField,LinkField...

**Comment by sebastienros** [comment]
Can you provide more details for a repro?

The internal issue is that a part instance was created without a strong type (ContentPart) but then at some point "you" are trying to read is with a type, and the instance doesn't match the requested type.

Another solution would be to test if element is of the requested type before returning it, or just discard it.

**Comment by Loneve** [comment]
Thanks.
This is a simple module for demo:
[TestContentPart.zip](https://github.com/OrchardCMS/OrchardCore/files/3096946/TestContentPart.zip)

1.enbale module TestContentPart,
2.New a Taxonomy item for TaxonomyField AdvPositoin.
3.Edit filed AdvType's options.
4.New -- MyAdv --Publish
`var part = contentItem.As<AdvPart>();  // An exception is thrown when saving the AdvContent item`

**Comment by MichaelPetrinolis** [comment]
in the startup.cs try to register the content part
services.AddSingleton<ContentPart, AdvPart>();

**Comment by Loneve** [comment]
@MichaelPetrinolis thanks, it is working.
