### ISSUE TITLE
Localizations not working when used in String.Format

### ISSUE THREAD

**Issue by MasihAkbari** [OrchardCMS/OrchardCore#3470]
I'm using `OrchardCore.Localization.Core` NuGet package for localizations with PO files, everything works but when i use a localization with `String.Format` localization not working and instead of filling localized word it just shows `Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString`  
  
**PO file**
```
msgid "TestMsg"
msgstr "This is {0}"
```

**Index.cshtml**
```
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<p>@String.Format(Localizer["TestMsg"].ToString(), "My Name")</p>
```

**result**
![image](https://user-images.githubusercontent.com/8469800/56097549-0c784b80-5f0b-11e9-8b6f-ac4563817bdf.png)

even just using Localizer["TestMsg"] alone in a view results on breaking html.
I'm thinking this is happening because {#} on words mixed up with plural mechanism, is there a way to using {#}'s in po files?

**Update**
Also i want to note that this kind of strings (with {#}'s) works great with data annotations already, but the same word is not working with `String.Format`.

**Update 2**
I did some extra examines, if PO file and view looks like this:

**PO file**
```
msgid "TestMsg"
msgstr "This is _HOLDER_"
```
**Index.cshtml**
```
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<p>@(Localizer["TestMsg"])</p>
```

It's ok and looks right but when i change view into this:

**Index.cshtml**
```
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<p>@(Localizer["TestMsg"].ToString().Replace("_HOLDER_", "Name"))</p>
```

again it's show like `Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString`   in view so i suspect that converting LocalizedHtmlString into string is to blame in here, how can i fix this?

**Comment by MasihAkbari** [comment]
So i found out that when dealing with `LocalizedHtmlString` you shouldn't use `ToString()` and must use `.Value` to convert it to string and now all is working perfectly.

**Comment by sebastienros** [comment]
Your solution is wrong too, you should do `<p>@Localizer["TestMsg", parameter0]</p>`

**Comment by sebastienros** [comment]
But it's even better if the Localization and value are the same in your default language, this way it's easier to understand what the key means, like "this is {0}"

**Comment by MasihAkbari** [comment]
ok, thanks for your attention
