### ISSUE TITLE
Polish the admin site

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3473]
This include:

- Give login a better look and feel
- Display OrchardCore features in admin dashboard
- Colorize the admin menu bar

![Login](https://user-images.githubusercontent.com/3237266/56193734-05039000-603a-11e9-8beb-5beff5a0c72a.png)

![Dashboard-CollapsedMenu](https://user-images.githubusercontent.com/3237266/56193751-0fbe2500-603a-11e9-98ed-89584596f2c9.png)

![Dashboard-ExpandedMenu](https://user-images.githubusercontent.com/3237266/56193777-1c427d80-603a-11e9-91cc-f19b227bd0e0.png)

Your thoughts @sebastienros @jtkech @Skrypt @Jetski5822 @agriffard

**Comment by agriffard** [comment]
As far as I am concerned, I don't like this background color since O1.

The login form is designed to be minimal on purpose and can be overriden from the theme if needed.

For the dashboard, an issue is open to allow to manage the items that appear on the admin homepage: #2246 
I agree that we need more information on that screen but I don't think it has to be some technical content.

**Comment by Skrypt** [comment]
I like what you did with the login page. Though the green color makes it look military which I'm not a fan of. For the dashboard, I myself too made changes in that dashboard and my changes got refused and the reason is quite simple, the dashboard should be customizable. So, right now the dashboard is kept simple until someone works on it. The only thing I would consider merging is the login customization since it can be overriden.

**Comment by hishamco** [comment]
> As far as I am concerned, I don't like this background color since O1.

> Though the green color makes it look military which I'm not a fan of. 

The military color 😄 as @Skrypt  mentioned earlier is the current color for Orchard logo, we can changes it when the logo change or Orchard CMS re branded

Regarding the dashboard I will clean it up until we enhance it to support droplets aka widgets. For that I will make a PR for the login page and changing the admin menu bar if everyone happy with the changes

**Comment by sebastienros** [comment]
How does it look like when the "front end" login feature is enabled?
I like it how it is right now, we should probably work on making it extensible instead.

**Comment by Skrypt** [comment]
I believe that there are also alternate logo's of Orchard that are in shades of grey and that's not a reason to use that everywhere. The general idea for the admin design is AFAIK to mimic Azure DevOps aka VSTS new design. I'd say that what you did is a great alternate design for the admin but I wouldn't use it for myself or for a corporate use where you want to keep the design as un-opiniated as possible or as common as possible. That green color just makes it look military...

**Comment by hishamco** [comment]
> How does it look like when the "front end" login feature is enabled?

I didn't try it, but we should have different style for each one, because the front-end login controlled by site them

> I'd say that what you did is a great alternate design for the admin but I wouldn't use it for myself or for a corporate use where you want to keep the design as un-opiniated as possible or as common as possible. That green color just makes it look military...

Everyone has it's own opinion, so choose the theme you like 😄

**Comment by Skrypt** [comment]
> Everyone has it's own opinion, so choose the theme you like

That's not much about my taste but more about the fact that we started using VSTS as a design guideline. What you are trying to do with your PR is to make us use it as the default theme. A contrib theme would be more appropriate. Your PR doesn't let me choose.

**Comment by hishamco** [comment]
Is there any Orchard Core.Contrib repo for stuff that's driven by the community and not committed in the original repo?

**Comment by Skrypt** [comment]
We don't have any theme and/or module gallery but the first step would be to create a repo with you contrib theme under your own Github account simply. I think we will have people create a list of contrib modules untill we get a proper gallery.

**Comment by hishamco** [comment]
But we need a place at least to refer these repos, so everyone can know the available modules, themes, language packages .. etc

**Comment by Skrypt** [comment]
Something like this could be done easily for now : 
https://github.com/thangchung/awesome-dotnet-core

**Comment by Skrypt** [comment]
Also, I've not tried it, but once @jtkech will be mostly done with his PR on migrating to .NET Core 3.0 we will be able to start looking back at prototypes for loading/unloading modules dynamically. Which will make more sense if we have want a Gallery.

**Comment by sebastienros** [comment]
> looking back at prototypes for loading/unloading modules on runtime

no we won't

**Comment by Skrypt** [comment]
That closes the off topic 😄
