### ISSUE TITLE
problem in using resize_url and caching

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3474]
sometimes it shows a resized picture and doesn't show an original file. I'm calling the original picture.

some times it doesn't resize the picture

[please check this gallery](http://www.fckia.com/Contents/ContentItems/4f6zc090wx9c7zkj2d851ay4nh#pid=26)

   ```
       {% for pic in Model.ContentItem.Content.SportMatch.pictures.Paths %}

          <a href="{{ pic | asset_url  }}">
            <img  style="padding: 4px;"   src="{{ pic | asset_url | resize_url: width:240, height:160, mode:'max' }}" alt="{{ Model.ContentItem.DisplayText }}" />
          </a>

          {% endfor %}
```

![1](https://user-images.githubusercontent.com/24512878/56232839-f80a8f00-6081-11e9-9fe2-848dca31413d.JPG)
![2](https://user-images.githubusercontent.com/24512878/56232849-ff319d00-6081-11e9-9998-2a8869c4c474.JPG)
![3](https://user-images.githubusercontent.com/24512878/56232850-ff319d00-6081-11e9-8e78-36c23bdf463d.JPG)

**Comment by Skrypt** [comment]
These are the supported sizes :

```C#
public static int[] DefaultSizes = new[] { 16, 32, 50, 100, 160, 240, 480, 600, 1024, 2048 };
```

I personnally use the 'crop' resize mode. If I look at your code it should resize them.

**Comment by aghili371** [comment]
@Skrypt it works but i don't know why it set resized on the original picture.

i   cleared cache by ctrl+f5.

this problem in caching pictures in CMS. how does it work?

**Comment by aghili371** [comment]
if I show the picture in a new tab and press ctrl+f5 and come back again in the gallery and refresh the page, it shows the correct original picture. 

it has shown the problem in caching strategy.

**Comment by Skrypt** [comment]
Have you tried also with 'ctrl + r' ? At least with Google Chrome that's what I do normally to clear the browser cache of the current page. I need to test what you did. Maybe, if you are looking at the full width image it changes the cached picture. We need to repro.

**Comment by aghili371** [comment]
yes, the problem is still.

**Comment by sebastienros** [comment]
Maybe you have old files locally? They are served with a local cache header. Or could this header be confusing and the cached entry be only based on the file name and not the query string parameters? In which case it would load a local version that doesn't have the same parameters?

**Comment by aghili371** [comment]
> Maybe you have old files locally? They are served with a local cache header. Or could this header be confusing and the cached entry be only based on the file name and not the query string parameters? In which case it would load a local version that doesn't have the same parameters?

no, I don't have local files and they are new on the published server. the problem with the query string. 
problem in this line:
```
<img  style="padding: 4px;max-width:240px; max-height:240px;"  
			src="{{ pic | asset_url | resize_url: width:240, height:160, mode:'max' }}" alt="{{ Model.ContentItem.DisplayText }}" />
         
```
now I changed my code and I used the orginal file for thumbnails. 
```
  <img  style="padding: 4px;max-width:240px; max-height:160px;"  
			src="{{ pic | asset_url }}" alt="{{ Model.ContentItem.DisplayText }}" />
```
it works fine. but i have to load big size photos.

**Comment by jtkech** [comment]
Maybe related to #3459. Did you create a `wwwroot` folder under you app with a placeholder file. This is required by ImageSharp fo caching when resizing images.

**Comment by Skrypt** [comment]
I don't think it's related. We found that ImageSharp is also caching full sized images (that's the issue found here). For the image gallery it is normal that it will show resized images if in the image gallery you are using a resize_url. You need to load full sized images in that case.

**Comment by jtkech** [comment]
@Skrypt okay.

I fixed it in my PR through the `MediaFileProvider.IsValidRequest()` that checks if there is at least one of the mandatory resizing parameters (width or height).

**Comment by sebastienros** [comment]
@jtkech if we want to server the file directly if there is no resize argument, it needs to be changed here: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Media/Startup.cs#L125 and not in the IsValidRequest.

**Comment by sebastienros** [comment]
Keeping this issue open to track the fact IS is not rendering (and caching) raw images.

**Comment by jtkech** [comment]
Okay, i will take a look asap.

**Comment by jtkech** [comment]
I did it there because of [this line in their middleware](https://github.com/SixLabors/ImageSharp.Web/blob/master/src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs#L160).

I will take a look at your suggestion.

**Comment by jtkech** [comment]
@sebastienros what i saw.

- If no resizing parameters, this code `OnParseCommands` is not executed and the full image is cahed.

- If there are parameters but not supported sizes, okay it is not resized but the full image is cached.

So, `IsValidRequest()` seems to be the right place to check if there is at least one of the mandatory resizing parameters, **but also to check if there are supported sizes**.

**Comment by sebastienros** [comment]
Please do the change then, but not in the same PR

**Comment by jtkech** [comment]
Okay.
