### ISSUE TITLE
Does Workflow support query in Script Task?

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#3475]
Does Workflow support query in Script Task?
No documents.

**Comment by sebastienros** [comment]
If not then we could add a custom extension for that. But I assume it would only run predefined queries, or accept a SQL92 one.

**Comment by jptissot** [comment]
Docs here: https://docs.orchardcore.net/en/dev/docs/reference/modules/Queries/#scripting
