### ISSUE TITLE
Use Azure Pipeline for CI/CD

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3479]

**Comment by psijkof** [comment]
Not sure what this issue is about. 
If we would be able to describe how a typical devops org would be like with OC, specifying how we would deal with ContentDefinition, Content and Code, to provide consistent Prod, UserAcceptance, QA/Test and Dev environments, that  would be awesome and greatly appreciated.

**Comment by sebastienros** [comment]
Can we install docker on it in order to build docker images as part of the CI?
Can we install Sql Server/PostgreSql, MySql for when we want to enable integration testing with it? Right now we are using sqlite only.

**Comment by carlwoodhouse** [comment]
@sebastienros you can definitely build docker images with it, we (patient) use it to build our images. Dunno about the sql stuff as we just use sql lite for tests too.

**Comment by SpencerWaz** [comment]
@sebastienros You could do the integration tests in docker with a CI specific docker-compose file that uses the sqlserver, mysql etc. images

**Comment by webmedia1012** [comment]
Hi @sebastienros  Any advise how I can restore the package on azure devops? I'm able do a build on my local machine for this version 1.0.0-rc1-13240, but once it's restoring on devops it can't find that version.

Thanks very much.

**Comment by deanmarcussen** [comment]
You need to specify a location for the myget feed from a `NuGet.config` and set the `dotnet restore` task to use the `NuGet.config`

![dotnetrestore](https://user-images.githubusercontent.com/13782679/82567389-34f26080-9b75-11ea-9726-bab66a280c10.png)

**Comment by webmedia1012** [comment]
Thanks so much Dean, is it in .NET Core? (OrchardCore) coz when I open my repo I couldn't see nuget.config, but I'll try your solution right now.

**Comment by webmedia1012** [comment]
Ok here's what I got
![nugetrestore_issue](https://user-images.githubusercontent.com/2730217/82573350-816c7a80-9b3a-11ea-99c3-72e17276c75f.PNG)

**Comment by deanmarcussen** [comment]
Yeah no, you need to make yourself a `NuGet.config` - that's your job ;)

Here's an example
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
 <add key="MyGet" value="https://www.myget.org/F/orchardcore-preview/api/v3/index.json" />
 </packageSources>
</configuration>
```

**Comment by webmedia1012** [comment]
Oh ok, now I get it!! Thank you so much.

**Comment by webmedia1012** [comment]
Just an update that solution worked!! Thanks again @deanmarcussen !

**Comment by agriffard** [comment]
We are now more in favor of GitHub Actions.
