### ISSUE TITLE
Error editing a blog post on published site

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3480]
When I edit a blog post on site that uses the beta 3 version of the nuget packages, this error occurs:

`An unhandled exception has occurred while executing the request. System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.AspNet.WebApi.Client'`

There is the same version of the .NET sdk on my machine and the server on which I host the site: 2.2.203

**Comment by agriffard** [comment]
Also, in that case, two admin menus are displayed on the left.

**Comment by sebastienros** [comment]
https://github.com/dotnet/sdk/issues/2442

I assume you have a module with views that is not using the razor sdk.

**Comment by agriffard** [comment]
I updated this `<Project Sdk="Microsoft.NET.Sdk">` to that `<Project Sdk="Microsoft.NET.Sdk.Razor">` in a module and republished but it didn't solve the problem.

**Comment by sebastienros** [comment]
Can you check there isn't any other package with the other sdk and that would have compiled views?

**Comment by agriffard** [comment]
No, there isn't any other package.

When I remove the DisqusPart from the Content type, there is no more errors when I edit a BlogPost.

@jtkech could you please test it (https://github.com/agriffard/disqus.orchardcore) and tell me what I am missing?

**Comment by jtkech** [comment]
@agriffard 

Your module project need a direct reference to `Microsoft.AspNetCore.Mvc`, it's a requirement for the `NET.Sdk.Razor`, otherwise your views are not pre-compiled and outputed in `TheModule.Views.dll`. Then at runtime it tries to compile the views whose contents are embedded in `TheModule.dll`.

**Comment by agriffard** [comment]
ok thank you @jtkech , it works.
