### ISSUE TITLE
Issues with loading theme if build name is differ from project name

### ISSUE THREAD

**Issue by JuliaPileva** [OrchardCMS/OrchardCore#3482]
I created a Theme. My project name is `Loyalty.Theme` and my assembly name is `SecretCircle.Loyalty.Theme.dll`. But Orchard looks for `Loyalty.Theme.dll`.
How to tell Orchard to look for the right assembly?

**Comment by sebastienros** [comment]
Not sure it's doable. In the meantime you should named them the same.

@jtkech is that possible?

**Comment by jtkech** [comment]
@JuliaPileva @sebastienros 

- It is like this from the beginning but at least now we are not dependent on the location, the project folder doesn't need to have the same name.

- In our **module** msbuild script we use `$(MSBuildProjectName)` (which is the file name of the project file without the file name extension) for virtual asset paths under a virtual area, and for the module id.

- In our **application** msbuild script we use `%(ModuleProjectReferences.FileName)` to retrieve the modules ids. For packages we use the `$(PackageId)`. Then we use module ids to load assemblies.

- So here, i assume you have used `<AssemblyName>AnotherName</AssemblyName>` in your theme project. That's ok for `$(PackageId)` which reflects the assembly name. Then for a project reference we would have to use the `$(AssemblyName)` property, seems to be easy.

- Hmm, this is for the **application** msbuild script that each module would need to pass its `$(AssemblyName)`, currently it provides its `$(MSBuildProjectFullPath)`, which is enlisted in `ModuleProjectReferences` and from wich we use the `FileName` metadata. Hmm, seems to be doable to just pass its `$(AssemblyName)`. Need to check if this property is automatically set if we don't specify it.

So, seems to be not so hard to do, but not sure, need to be tried in all scenarios.
