### ISSUE TITLE
showing WYSIWYG editor menu in wiget. 

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3486]
why in create content doesn't show the menu in WYSIWYG  HTML wiget.
![Capture](https://user-images.githubusercontent.com/24512878/56418808-6163eb00-6298-11e9-928b-013391342160.JPG)

and i need to show formatting text at the end but it clear the HTML tags and just showing the text.
`          {{ Model.Content | shape_render }} 
`

what i should do to have formatting text with images?

**Comment by sebastienros** [comment]
it's an option on the field to select which editor you want.
