### ISSUE TITLE
Changing username doesn't assign new owner to it's owned content items.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3492]
Looking at this issue we should maybe think about adding an immutable User Id for marking content items owner instead of using it's username. Else, we will need to add something that will reassign content items to the new user username all the time. This doesn't look optimal for performance. Tell me which approach you guys prefer using and I will work on this.

**Comment by zl2fxy** [comment]
UserName will as a user property，Doesn't as User Key.It is good.
I think that we can create a user property like as user nikename,then UserName as key to store,and it's not to change.
The solution to this problem I encountered before。

**Comment by Skrypt** [comment]
The issue I found is that we store the UserName in the database in the Owner property of every document or ContentItemIndex row. But if someone requires to change it's UserName then the User account associated with these content items are going to be left as orphans. 

UserName should be a User Account property (not mandatory). And Email should also be a User Account property (mandatory). But neither the email or username should be used as an identifier for a User Account. It should be an immutable Identifier like an int or a guid / sku.

**Comment by hishamco** [comment]
I am not sure why there is ability to change the username while it represents the identity of that user?!!

**Comment by Skrypt** [comment]
It's not his identity it's just that we use it for the Owner everywhere. We could at least use the User Id that comes from the database but I think that this Id is not safe enough since it could be different from a staging server and a prod server. Right now, we can't import/export users because we could end up with mismatching User Id's.

**Comment by hishamco** [comment]
I think we shouldn't allow changing the username or email if we use it as identity

**Comment by Skrypt** [comment]
Changing a username or email on a user account should be pretty standard things to be able to achieve right?

**Comment by hishamco** [comment]
No .. especially if the intend to use it as identity, you can checkout the other CMSs

**Comment by Skrypt** [comment]
Well, without looking. The idea is to have a separate identity guid to avoid needing to update all the Owner records when a UserName changes. Be standard or not. Should we keep the actual design or should we change it? Which other CMS's uses username as an identity?

**Comment by Skrypt** [comment]
> No .. especially if the intend to use it as identity, you can checkout the other CMSs

To be honest this comment feels like trolling

**Comment by chinasqzl** [comment]
In China, Email is not a common tool, Email must be filled in is not in line with China's national conditions.

**Comment by hishamco** [comment]
@Skrypt introducing a guid is a good idea too, but my question why we need to change the username? Setting email as username could be optional like what I have seen in Umbraco

**Comment by Skrypt** [comment]
I think that neither of those 2 should be an identifier for a user account because they can change. A user could want to change it's email because it's no longer active. Though changing the UserName like in Github can have side effects that are not wanted.

https://help.github.com/en/articles/what-happens-when-i-change-my-username

GitHub cannot set up redirects for:

@mentions using your old username
Links to Gists with your old username

So using the UserName as an identifier can have side effects that are unwanted because if you allow people to change it then you need to run SQL Queries to alter all the records in a Database that has a reference to that UserName. And just like Github if we allow to change that UserName then we need to at least have these SQL Queries made automatically.

Though, if we'd be using a Guid that would not be necessary. The only thing we would need is to parse posts that have @Skrypt and replace it when stored to DB as @UserGuid and when displaying that would just need to be replaced with the actual @UserName.

Setting Email as UserName for login purpose is an other topic. I think there's already a PR that has been created for that matter.

**Comment by hishamco** [comment]
Sounds good, but did think it's good idea to replace user guid with username everywhere!! What about the search indexing as example?

**Comment by Skrypt** [comment]
Lucene Indexes the ContentItemIndex table which has currently the Owner and Author columns which have a UserName in them. If we change these 2 we would need to resolve the current UserName from the UserIndex table each time we index a new document with Lucene (there is no issue there).

Though changing a UserName would require at least that we reindex all the documents owned by this user account. This could potentially take a lot of computing ressources since indexing with Lucene is quite slow. But that's the trade-off for having it working. I mean, this is probably what Github does somehow.

**Comment by Skrypt** [comment]
I must add here that for me the UserName is not mandatory since the users that are loging in my websites have extended User profiles which includes their "Name". They never need to use a UserName, only their email / password. This is mainly why I'm questionning the usage of that UserName as an identifier.

**Comment by sebastienros** [comment]
1- Isn't the username a user id already? In which case we might not be able to change it.
2- Should the username be seen as some friendly information like a display name "Jasmin Savard" and we should be able to change it. In which case we need an identifier that is not used for display purpose, but then add something else to be displayed.
3- Maybe we could keep the username as it is right now, and just create a new "Display name" property that the user could change? The username would be immutable, like the "id" in 2.

This is an "historical information" which we can't change. For instance each version has its own value, and we don't want to lose these. If a user is deleted, this value should also be kept even if there is no match. The solution is to have a custom feature that lets us reassign a specific username to another one. But it would be a manual operation, not automatic.

**Comment by hishamco** [comment]
I agree with @sebastienros, regarding deleting users I saw many scenarios out there some delete the user and keep it's username for all relared things like blogs and some remove the user and use `Unknown` instead

**Comment by jersiovic** [comment]
I agree with the option of using username as an unmutable identifier. And if it is needed to have a mutable Display Name.
@Skrypt currently our users only provide the email, then we set an internal username that they are not aware of.

**Comment by Skrypt** [comment]
I made a PR for changing the Owner of content items when changing a UserName. But, I also, for my website did some handlers to reindex content items related with these Users. ASP.NET Identity framework allows changing a UserName so I think the proper solution would be to have a unique immutable "guid" like identifier for a User. Then change the Owner field to store that guid instead of the UserName. There is a lot of issues, right now, related by the fact we are using the UserName only.

**Comment by hishamco** [comment]
+1 for introducing a unique user identifier

**Comment by Skrypt** [comment]
Closing as userId is now merged.
