### ISSUE TITLE
Azure Website : Lucene rebuild cause request timeout

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3497]
Azure Lucene rebuild cause request timeout

**Comment by sebastienros** [comment]
Timeout because it's too slow. We probably need to do redirects to itself to process the next batch. With a small batch size. Could be done in ajax (like the updates/upgrades steps in Orchard 1).

**Comment by Skrypt** [comment]
You fixed it?

**Comment by Skrypt** [comment]
Mitigated by #3809 
We could change the priority as this should happen less often now.
This could still happen but it would require a **really huge** amount of data to be indexed.
