### ISSUE TITLE
 services.AddOrchardCore().AddMvc() then without AddControllersAsServices，i need it

### ISSUE THREAD

**Issue by daodol** [OrchardCMS/OrchardCore#3498]

**Comment by daoqiang** [comment]
This orchard core conflicts with autofac. When using orchard core, Autofac injection is unsuccessful.

**Comment by sebastienros** [comment]
@jtkech do we need `AddControllersAsServices` ?

**Comment by jtkech** [comment]
Not by default but here we are missing an extensibility on the mvcBuilder allowing to do.

            services
                .AddOrchardCore()
                .AddMvc(mvcBuilder => mvcBuilder.AddOtherServices)
                ;

We could do an helper for this but currently our AddMvc() only register the mvc startup which, when executing, can't be aware of any configure lambda.

But i think it is doable if we really want this extension.

**Comment by jtkech** [comment]
Can you try the following?

            services
                .AddOrchardCore()
                .AddMvc()
                .ConfigureServices(s =>
                {
                    s.AddMvcCore()
                        .AddControllersAsServices();
                });

It will run after our mvc startup, the 2nd `AddMvcCore()` using the `TryAdd` pattern will not re-add services, and looking at the code it will not re-create a `PartManager` but retrieve it [from the service collection](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L55).

This is something we do to see if our `OrchardCoreBuilder` has been built, we could also do the same thing to retrieve the `IMvcBuilder or IMvcCoreBuilder` to be used in some helpers that would accept some config lambdas to add more things on them. And then be able to do it as in my previous comment.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
