### ISSUE TITLE
Web API - Return Status Code instead of Redirecting to Login Page

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#3499]
Hey, as the title says, I'm creating a module that implements a simple Web API that uses an external OpenId provider.

The token validation itself works just fine but after the validation fails my request gets redirected to the login page. In this case I would like to simple return a 401 status code.

Is there any way to configure this behaviour?

I've tried configuring the application cookie with no success (see code below).

Another issue I'm having is that any subsequent requests (using Postman) will automatically redirect me to the login page without showing any token validation being done in the console.

````
services.ConfigureApplicationCookie(config =>
{
  config.Events = new CookieAuthenticationEvents
  {
    OnRedirectToLogin = context =>
    {
      if (context.Request.Path.StartsWithSegments("/api"))
      {
        context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
      }
      else
      {
        context.Response.Redirect(context.RedirectUri);
      }

        return Task.FromResult(0);
      }
  };
});
````

Thanks for any help.

**Comment by sebastienros** [comment]
I think the solution is in this PR https://github.com/OrchardCMS/OrchardCore/pull/3215

Because of the value in the cookie options. Try to apply this change and let us know if that fixes it too.

**Comment by nuno-tiago-reis** [comment]
It hasn't fixed the issue. From analyzing the logs it seems that it's applying both the Cookie Authentication and the Bearer Authentication schemes (even though I have setup the controller to use Bearer).
````
[Route("/api/[controller]/")]
[Authorize(AuthenticationSchemes = IdentityServerAuthenticationDefaults.AuthenticationScheme)]
[ApiController]
````

Shouldn't Bearer be the only authentication scheme being invoked this way?
The strange behaviour I wrote about before is still happening, if the JWT Tokens being provided are valid the API will reply correctly, but as soon as I send an invalid token the API will start ignoring the Bearer scheme and only invoke the Cookie Authentication scheme.

**Comment by naammeinkyahai** [comment]
@nuno-tiago-reis 
Try 

`[ApiController]`
`[Authorize(AuthenticationSchemes = "Api"), IgnoreAntiforgeryToken]`

**Comment by naammeinkyahai** [comment]
Hmm those two attributes worked fine for my API Controller

**Comment by nuno-tiago-reis** [comment]
Is this API auth scheme defined anywhere or are you suggesting me to rename my authentication scheme to API?

**Comment by naammeinkyahai** [comment]
Yes, this scheme is defined within OrchardCore, I am not simply suggesting a rename.

You have to specifically write 
`[ApiController]`
`[Authorize(AuthenticationSchemes = "Api"), IgnoreAntiforgeryToken]`

And nothing else. Please ensure you include `IgnoreAntiforgeryToken`

**Comment by nuno-tiago-reis** [comment]
I tried renaming my authentication scheme to API and now instead of redirecting me to the login page I simply get redirected to the Diagnostics controller and to the Error action.

**Comment by naammeinkyahai** [comment]
Please don't rename your authentication scheme. You need your authentication scheme here at all, the API scheme is supported inside OrchardCore. Did you enable and configure oauth token validation module?

**Comment by naammeinkyahai** [comment]
What does your controller attribute look like now?

And is this path `/api/content` something you defined in your controller? Because the exact same path is also defined within OrchardCore.

**Comment by nuno-tiago-reis** [comment]
[Route("/api/[controller]/")]
[Authorize(AuthenticationSchemes = "Api"), IgnoreAntiforgeryToken]
[ApiController]

And my Controller is named like this: 'ContentController'.

**Comment by naammeinkyahai** [comment]
Can you please try renaming the controller to something like `AbcController` and try the new path `/api/abc?filter=welcome&filterType=alias` ?
You might be running into conflict with the [inbuilt API](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs).

The exact setup you have now is working very well for us. We haven't defined any custom authentication scheme. With respect to authorization, we have 0 lines in our Startup.cs

**Comment by nuno-tiago-reis** [comment]
Is your API defined in a module?

**Comment by nuno-tiago-reis** [comment]
I just created a new project with the bare minimum and I managed to get it working. I must've configured something wrong, thanks for all your help!
