### ISSUE TITLE
Recipe and import content

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#350]
Will there be in a deployment plan an option to export a recipe that define also the 'schema' of a content type?

Then, will there be an admin UI to import a recipe?

**Comment by sebastienros** [comment]
Yes, we need more "deployment steps".

**Comment by agriffard** [comment]
Will there be a new RecipeExecutionStep in Orchard.ContentTypes that allows to import a 'schema'?

**Comment by sebastienros** [comment]
There will be one, once someone creates it. And it should be simple as the content types definition is already stored as a json document in the database. So exporting/importing should be straighforward, and the import might just work with the JObject.Merge method.

**Comment by agriffard** [comment]
In order to migrate my existing blog, I will try to generate the json data to include in a recipe to import (during the setup, because for for he moment, there is no import page) the existing blog and blogpost.

One way to achieve this would be to create a Migration module in O1 that allows to export the data by serializing them in json.

**Comment by agriffard** [comment]
I am currently working on an O1 module that allows you to export the contents to a json recipe that you can import with Orchard Core.
I already managed to export the blog posts and generate a OC 'setup like' recipe.

**Comment by atiq-cs** [comment]
Is there an easy way to import from Orchard 1.10.2 ?

**Comment by Jetski5822** [comment]
Not yet!!! In the works :)
