### ISSUE TITLE
razor pages

### ISSUE THREAD

**Issue by LatinaAtanasova** [OrchardCMS/OrchardCore#3501]
Hello,

I am currently working on this project and it is completely new to me. I've started a decoupled one as the idea is to use a separate views for pages. According to Sebastien's video "Using Orchard Core as a Decoupled CMS" I made a simple structure in the web project:
Pages/Index.cshtml
Pages/Contacts.cshtml
Pages/_ViewStart.cshtml
Pages/_ViewImports.cshtml
Views/Shared/_Layout.cshtml.

In Pages/_ViewImports.cshtml i have the following:
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
@addTagHelper *, OrchardCore.Menu

and the site is build fine, but when i want to use Site.SiteName and everything that is inherited from OrchardCore.DisplayManagement.Razor.RazorPage<TModel> and i insert it in ViewImports it says that pages are razor (have @page).
So, if i remove them, I can reach Site.SiteName and all other things but... the project starts with blank page.

What am i missing?

**Comment by jtkech** [comment]
In your `Pages/_ViewImports` add

    @inherits OrchardCore.DisplayManagement.RazorPages.Page

Then you will get some helpers but not some available in a razor view (`Razor.RazorPage`) as `ISite`. You need to inject the following service (as i remember, not re-tried).

    @inject OrchardCore.Settings.ISiteService SiteService

    @{
        var site = await SiteService.GetSiteSettingsAsync();
    }

**Comment by LatinaAtanasova** [comment]
Thank you very much. I'll try this service.
