### ISSUE TITLE
TestContentPartA of OrchardCore.Demo missing Injection 

### ISSUE THREAD

**Issue by evendou** [OrchardCMS/OrchardCore#3502]
when i study the OrchardCore.Demo,  i found the HomeController.Index(string text) throw error:

InvalidCastException: Unable to cast object of type 'OrchardCore.ContentManagement.ContentPart' to type 'OrchardCore.Demo.Models.TestContentPartA'.

to fixed the bug, add services.AddSingleton<ContentPart, TestContentPartA>();  to Startup.ConfigureServices(IServiceCollection services)

**Comment by sebastienros** [comment]
Good catch
