### ISSUE TITLE
Tenant Routes

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#3503]
**1)** Create a site with tenants, example:

![image](https://user-images.githubusercontent.com/6829626/56657964-0835f600-66a2-11e9-9adc-6cce5fff20cf.png)

**2)**  Edit "Url Prefix" from "testA" to "testD".
![image](https://user-images.githubusercontent.com/6829626/56658412-408a0400-66a3-11e9-9e60-c5de12a64881.png)

_**Note:**_ How to edit a tenant name? It's locked

**3)** Now, tenant "testA" is available at "https://localhost:44300/testA" and "https://localhost:44300/testD". Why?

I think that route "https://localhost:44300/testA" must be unaccessed.

![image](https://user-images.githubusercontent.com/6829626/56658891-711e6d80-66a4-11e9-85ea-d562e5d805f7.png)
![image](https://user-images.githubusercontent.com/6829626/56658903-7bd90280-66a4-11e9-8ca8-88dc6bc03c87.png)

What to do if I want to change the url in Tenants? Is it a bug?

**Comment by jtkech** [comment]
- Yes, you can't re-edit the tenant name.

- For the tenant url prefix, yes i can repro. When changing the tenant settings we remove the previous one from the `RunningShellTable` dictionary **but whose keys rely on the url prefix!** So we don't remove it if the url prefix has changed.

So, yes right now you have to restart the site, then it works, only the new url is served.

**Comment by sebastienros** [comment]
Someone might request that we provide an automatic redirection. But I assume this could be a totally separate module that lets us handle redirects.

**Comment by jtkech** [comment]
Maybe we could at least really remove the previous settings from the running shell table, even when the url prefix has been changed, which is not the case currently. This by being able to retrieve it also by the tenant name, not only by a key based on the url and the prefix.
