### ISSUE TITLE
Default shape for custom content items

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3505]
I may be wrong or missed something, but isn't it intended that there is a default shape for each custom content item ?

Short explanation of my problem:
I've created a custom content type "Landing Page" with a bag part called "Slider".
This bag part is configured to allow only content items of type "Slider Item".
Now if i want to create a new Landing Page and click on it in the main menu of the admin panel, the DisplayManagement throws an exception "Shape type SliderItem_Edit not found".

**Comment by Skrypt** [comment]
You are missing a SliderItem.Edit.cshtml Razor View.

**Comment by Flarescape** [comment]
Hi Skrypt!
Thank you, i know, but i thought that it isn't supposed to crash if don't have this view.
I mean, in Orchard 1 you don't had to make an extra Edit-View for a new content item, created trough the backend, to use it.
In that case, a normal Editor who is only working with the backend and creating content without programming always needs a "developer" to create and use new content items ?!

**Comment by sebastienros** [comment]
Definitely a bug, and I don't trust you, because everything would be broken otherwise ;) Do you mind sharing some repro steps? It should automatically use `Content_Edit` if `SliderItem_Edit` doesn't exist. It's just an alternate.

**Comment by Flarescape** [comment]
I think i've found my mistake for this bug, but i'm still not completely sure, if it should behave like this.
I've added an stereotype to the Slider Item named "SliderItem", but i thought that there is a fallback to the Content_Edit view.
Of course, if i remove the stereotype it works.
Repro:
1.) Create content type "Some Item" that is "Listable" and "Securable", with title part, fields "Image" (media, single select), "Text" (text field), "Link" (link field) and Stereotype "SomeItem"
2.) Create content type "SomePage" with title part, autoroute part, and a bag part called "Some Items" that allows only content items of type "Some Item"

After that if you want to create a new "SomePage" an Exception occurs and you have to stop debugging after a few steps because the debugger only lets you stop or edit the "BagPart.Edit.cshtml" because of the error: Adding 'namespace' will prevent the debug session from continuing.	OrchardCore.Flows

**Comment by sebastienros** [comment]
Are you still seeing the issue?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
