### ISSUE TITLE
Discussion: Forms Module

### ISSUE THREAD

**Issue by TheBaffledOne** [OrchardCMS/OrchardCore#3507]
I have a few questions about the forms module. I have a multi page wizard style form I would like to implement. 

Can a form authored using the builder be statically defined for subsequent reuse e.g. in a recipe?

Do I need to pass IFormCollection into my own controller method to process the data if I choose not to use workflow?

Does client side validation occur if I add the validation widgets. Initial tests indicate not. 

Thanks

**Comment by sebastienros** [comment]
> Can a form authored using the builder be statically defined for subsequent reuse e.g. in a recipe?

Yes, the TheComingSoon recipe has an example

> Do I need to pass IFormCollection into my own controller method to process the data if I choose not to use workflow?

I assume you can just use `Request.Forms`

> Does client side validation occur if I add the validation widgets. Initial tests indicate not.

I am not sure if we already have it. Maybe for a few elements. 


I think it should be easy to an a new Form element that would allow for a wizard like experience.
Then each form widget could also be improved to support client side validation (if the option is selected).

**Comment by TheBaffledOne** [comment]
I am not sure if we already have it. Maybe for a few elements.

I have attached validation widgets to the input fields on a sample form but these don't seem to activate on from submission. I'm not sure if that is intentional or a issue?

I think the additional of a new "wizard" form element for a multi page form would be a valuable enhancement to the forms module. As it stands, I think I will have to implement my own form as seperate views with next & previous buttons for custom navigation. Also this will have to do validation as well, which is not ideal.

**Comment by jonvee** [comment]
The select widget in Forms is not complete. I can open a separate issue, but wasn't sure if it was being discussed or handled by someone already.

**Comment by sebastienros** [comment]
@jonvee feel free to start a new issue with what's missing
