### ISSUE TITLE
Localization packages

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3508]
According to the roadmap
> Localization packages (Chinese, Spanish, Arabic, French are the most requested)

I suggest to add ability to add language packs from within TheAdmin site, the package should have a metadata similar to module manifest, it could be versionable

@sebastienros your thoughts about this, or do you have another idea of how we can implement this

**Comment by sebastienros** [comment]
The idea I had was to create nuget packages for each language, and from the application you would reference it like any other module. That would extract its contents (po files) in the correct folder.

That's the simplest way to make localization as other options would require storing the entries in the database.

**Comment by sebastienros** [comment]
This could be done in a different repository and have its own CI so we can publish only the languages that have changed, and when they have changed. @agriffard can you create the repository? I would build the CI scripts (appveyor). master branch as the default branch.

Repository: OrchardCore.Translations
Packages: OrchardCore.Translations.ar,  OrchardCore.Translations.cn-ZH, OrchardCore.Translations.cn-TW

Also the repository might just contain the appveyor script that would download the po file zips and build packages automatically.

**Comment by hishamco** [comment]
What about import and export language packs from within the admin? !!

**Comment by agriffard** [comment]
Here is what I did:
- Create the repository https://github.com/OrchardCMS/OrchardCore.Translations .
- Add the .pot files in a App_Data_Localization folder.
- Activate the integration between Crowdin and Github.
- Specify the generation of the translated files with the pattern: `/lang/%two_letters_code%/%file_name%.%two_letters_code%.po`
- Sync the translations => Generate the file in the `l10n_master` branch.
- Merge a PR that has been created between the branch `l10n_master` and `master`.
- Move the translations on Crowdin in the master/App_Data/Localization folder.

Next steps:
- How do we create the nuget packages? (appveyor script)

**Comment by sebastienros** [comment]
TODO: appveyor script that creates a package per language folder, and publish it on nuget.
The i10n branch needs to be merged to master.

We need to detect the changes for each language so we don't push packages for every commit.

**Comment by jptissot** [comment]
@agriffard How can I generate the po / pot files for my modules ?

**Comment by hishamco** [comment]
@jptissot if am not wrong there's a tool that scan the modules to extract the resources.. give me few minutes to look and send the link

**Comment by hishamco** [comment]
Have a look https://github.com/lukaskabrt/PoExtractor

**Comment by jptissot** [comment]
@hishamco thanks! I will have a look.

**Comment by agriffard** [comment]
Yes, exactly: 
`dotnet tool install --global PoExtractor.OrchardCore`
Then
`extractpo-oc C:\Path\OrchardCore C:\temp\OrchardCore --liquid`

**Comment by hishamco** [comment]
@agriffard can we add these commands to README.mk for the localization module?

**Comment by sebastienros** [comment]
I can't find an advantage of having them as embedded resources as the dlls would still be copied on the filesystem and deployed.

**Comment by sebastienros** [comment]
Depends on https://github.com/OrchardCMS/OrchardCore/issues/4014

Then have the po files extracted in the localization folder. These packages are not modules/features.

**Comment by agriffard** [comment]
If we manage to generate some .nupkg packages with .po files inside (ex: OrchardCore.Translations.Fr) and reference it in an app, will it work when we publish it?

/cc @jtkech

**Comment by jtkech** [comment]
There are different ways but based on the above comments a solution would be.

- A localization package could hold po files (not embedded in the assembly but part of the package) and **an msbuild script** so that, when building an application that references it, the po files would be copied to the app `Localization` folder.

- Then, output this folder on publishing, as it is already done and with some tweaks in #4088.

**Comment by hishamco** [comment]
What if we could imported via Admin section?

**Comment by hishamco** [comment]
@sebastienros is this should be closed after we merge this https://github.com/OrchardCMS/OrchardCore.Translations/pull/13
