### ISSUE TITLE
Is there any tools to define a recipe.json file?

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#3509]

**Comment by mmdqq** [comment]
![image](https://user-images.githubusercontent.com/4881282/56717534-6c72bb80-676f-11e9-86d0-f883cdb0181e.png)
 Such as this  tool ,It generates a json file according to the rules of the mini pragrom.so i think is there any tools to generate a recipe.json file according to the rules of orchardcore.

**Comment by sebastienros** [comment]
The closest thing to a tool is the Deployment Plan which lets you select recipe steps and configure them, then generate a recipe from it.
