### ISSUE TITLE
Razor section doesnt work

### ISSUE THREAD

**Issue by Diman96** [OrchardCMS/OrchardCore#3520]
Sections on the razor page are not displayed, I use like this in Layout.cshtml  `@await RenderSectionAsync("Header", required: false)`, in Content-Page.cshtm `@section Header{Text}`, in _ViewImports.cshtml `@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>`

**Comment by psijkof** [comment]
Declare your sections with `<zone>`?

**Comment by Diman96** [comment]
@psijkof No, where or how I must declare sections with `<zone>`?

**Comment by Diman96** [comment]
found solution in  https://github.com/OrchardCMS/OrchardCore/issues/3534.
