### ISSUE TITLE
Decoupled CMS with separate Authoring site

### ISSUE THREAD

**Issue by pbros** [OrchardCMS/OrchardCore#3521]
Hello,

I am wondering if the following is possible with Orchard Core for a deployment on premise.

I would like to have 2 sites, one internal that is used for authoring the CMS content, and one externally facing that consumes the CMS content for public display.

I know this is possible if I use Orchard Core in a headless mode, but I was hoping to be able to use it in a decoupled mode and have access to the APIs and tag helpers.

Both sites would be able to access the same database, but from what I can tell, Orchard Core also needs to have some files in the filesystem to setup a site.

Thank you

**Comment by psijkof** [comment]
Hello,

When you create an ASP.NET Core app using OrchardCore, you will have a public site and protected site (admin). The admin is where you author your content, the public site is what you make of it... (full service, using only OC ,decoupled or headless).

**Comment by pbros** [comment]
Hello,

My understanding is that the admin site runs on the same IIS website than the public website, but in the /admin directory and it protected by authentication.

What I would like to have is 2 separate IIS websites, running in separate VMs, one which would be internal.example.com, where I can access the administration site at internal.example.com/admin, and an external one, www.example.com, where the admin site does not even exist or is not exposed, and where I can use the content authored from internal.example.com.

Is this possible?

**Comment by dodyg** [comment]
The code for /admin is here https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Admin/Startup.cs

I can't remember if ASP.NET MVC Core routing table is read only or it can be modified. It's worth investigating.

**Comment by sebastienros** [comment]
The issue with that approach (decoupled) is that all the code for admin and front-end is the same because we didn't split it. The only thing you could do is remove the permissions to access the admin OR the front-end. But I don't see any advantage.
