### ISSUE TITLE
Implement content item permissions

### ISSUE THREAD

**Issue by pbros** [OrchardCMS/OrchardCore#3523]
Hello,

Is it possible to restrict content visibility to certain user groups? For example, some content is only visibility to anonymous users, other is for logged in, and some more is for a subset of logged in users (e.g. VIP Clients)

Thank you

**Comment by Skrypt** [comment]
You can use User Roles for that matter. But you need also to implement your controllers properly for making those permissions effective afterward.

**Comment by pbros** [comment]
Thank you! From what I can tell, I could manage access to different content types this way.

What I had in mind was more to restrict specific content to user groups. For example, I would have a blog post that is visible to all, another one that is visible to all authenticated users, and another one that is only visible to logged in VIP users.

Thanks again!

**Comment by Skrypt** [comment]
It's not implemented yet but that's called Content Item Permissions.

**Comment by sebastienros** [comment]
Or a permission by blog (dynamic permissions).
Or a module to select which types shoudl have dynamic permissions per content item. But that would be equivalent to content item permissions.

**Comment by cnoelker** [comment]
Related to this are page permissions. As far as I see, I can only implement this individually, not by configuring it.
If I restrict a page to a specific role, the navigation menu should be smart enough to hide the link to the page if the user is not authorized to see it. And the search should not include this in the search results if the user is not authorized to see it.
What's the status of this feature?

**Comment by Skrypt** [comment]
You mean restrictions per URL?

**Comment by cnoelker** [comment]
Yes, E.g. one role should have the permission to see a page while another role does not have the permission.

**Comment by agriffard** [comment]
In O1, the Content permissions Part looked like this in the admin:
![image](https://user-images.githubusercontent.com/703248/74087833-38634f80-4a90-11ea-8dae-2ab2cc742875.png)

**Comment by agriffard** [comment]
You could have a look at this module: https://github.com/EtchUK/Etch.OrchardCore.ContentPermissions

**Comment by pbros** [comment]
I implemented using https://github.com/EtchUK/Etch.OrchardCore.ContentPermissions
