### ISSUE TITLE
An error occured while executing the SQL query: “@limit”

### ISSUE THREAD

**Issue by evendou** [OrchardCMS/OrchardCore#3529]
this is the screenshot, when i run the query, an error occur.
![image](https://user-images.githubusercontent.com/6456732/56859687-09786300-69c1-11e9-987c-63dc455149f0.png)

**Comment by evendou** [comment]
i found the correct sql query syntax.
![image](https://user-images.githubusercontent.com/6456732/56860055-abe61580-69c4-11e9-8857-79a5d2e8a9b2.png)

**Comment by sebastienros** [comment]
This doesn't look like the correct syntax, I think the first one should have worked.

**Comment by hishamco** [comment]
This looks working fine at my end

![Query](https://user-images.githubusercontent.com/3237266/59028867-54f61a80-8865-11e9-92d0-23f6b433ae50.png)

**Comment by sebastienros** [comment]
Thanks @hishamco , I assume we fixed it in the meantime.

**Comment by evendou** [comment]
thanks, i will try again

**Comment by evendou** [comment]
perfect. thanks very much!
