### ISSUE TITLE
problem  custom theme with new update

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3530]
i updated to the new version, but i can't use and see my theme in active themes.

my current config:

main web project:
`    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-beta3-71077" />`

theme:
```
    <PackageReference Include="OrchardCore.DisplayManagement" Version="1.0.0-beta3-71077" />
    <PackageReference Include="OrchardCore.Theme.Targets" Version="1.0.0-beta3-71077" />
    <PackageReference Include="OrchardCore.Users.Abstractions" Version="1.0.0-beta3-71077" />
    <PackageReference Include="OrchardCore.Users.Core" Version="1.0.0-beta3-71077" />
```

**Comment by jtkech** [comment]
Do you reference your theme in your main web project?

**Comment by aghili371** [comment]
@jtkech yes i have  that, 
`    <ProjectReference Include="..\TheAgencyTheme\KiaTheme.csproj" />
`
i didn't change anythings just i update the references .

**Comment by jtkech** [comment]
Okay, i will try this scenario this night.

**Comment by aghili371** [comment]
it works now, just i updated again with newer versions.

**Comment by jtkech** [comment]
Okay cool.
