### ISSUE TITLE
Rendering liquid tag in Razor

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3532]
I am using decoupled approach.

The markdown editor returns a liquid tag when picking up media e.g `{{ "Blog/inno-labs-logo-small.jpg" | asset_url | img_tag }}.`

How can I render render tag this in a Razor template because `@Helper.MarkdownToHtml` simply process the markdown.

**Comment by sebastienros** [comment]
We need this as a service for decoupled cms.
