### ISSUE TITLE
Razor section doesnt work

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#3534]
![image](https://user-images.githubusercontent.com/4881282/56887213-972c7f00-6aa3-11e9-9049-0f985303821d.png)
![image](https://user-images.githubusercontent.com/4881282/56887232-a57a9b00-6aa3-11e9-92c3-809a5ac6b586.png)
![image](https://user-images.githubusercontent.com/4881282/56887245-b4614d80-6aa3-11e9-8a2b-40679f859eeb.png)

**Comment by psijkof** [comment]
In Index.cshtml, use <zone name="ControlSection"></zone>

**Comment by mmdqq** [comment]
Thanks but it can't to use Syncfusion.EJ2 ,maybe i must give up Syncfusion。I  want add a feature of edit DocX file to orchardcore,anyone knows  the best tools to edit office online?

**Comment by sebastienros** [comment]
The RenderSection is overwritten by our base class. Try base.base.RenderSection
