### ISSUE TITLE
How to run OrchardCore in a virtual folder in IIS?

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/OrchardCore#3535]
Hi,

Now that beta3 is available, I'm taking Orchard Core for a spin... Tried IIS Express, works fine.

Now I'm trying to run Orchard Core in a virtual folder in IIS called /OrchardCoreDemo.

Website is loaded, but images are not. Image url is for example http://localhost/media/logos/envato.jpg (obviously wrong). When I manually try to load http://localhost/OrchardCoreDemo/media/logos/envato.jpg (added the virtual folder) I get an ArgumentOutOfRangeException: The specified URL is not inside the URL scope of the file store.

Going to admin is also not working for me, probably for similar reasons.

How can I set the 'root' folder of my orchard core website?

With kind regards,

Steven Spits
Servico Computer Systems

**Comment by jtkech** [comment]
It has been fixed in the dev branch through #3200 and there is a pending pr #3533 to fix another issue in a specific scenario.

**Comment by netwavebe** [comment]
Thanks for your feedback!

**Comment by agriffard** [comment]
Closing it as related PRs have been merged.
