### ISSUE TITLE
Removing Recipes Module causes fatal error

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/OrchardCore#3538]
Disabling the recipes module causes this internal server error:

`System.InvalidOperationException: Unable to resolve service for type 'OrchardCore.Recipes.Services.IRecipeMigrator' while attempting to activate 'OrchardCore.Menu.Migrations'.`

References folders that doesn't exist:

`C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\AutomaticDataMigrations.cs`
and
`C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs`

Tested on Beta3, using CLI and templates on mac

**Comment by agriffard** [comment]
Recipes feature cannot be disabled anymore.
