### ISSUE TITLE
Lucene parameter

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3540]
In the Lucene Query admin UI there is an input for Parameters. How does one actually use it?

Template
``` javascript
{
  "query": {
    "term" : { "Content.ContentItem.ContentType" : "BlogPost" } 
  },
  "sort": { "BlogPost.PublishedOn": { "order": "asc" } },
  "size":  ??
}
```

Parameters
```
{ "size" : 1}
```

**Comment by jtkech** [comment]
As i remember without retrying it ` "size":  {{ size }}` but not sure ;)

**Comment by sebastienros** [comment]
Correct, there is no out of the box support for custom parameters in elasticsearch SDL, so we need to use the templating step.

There is also a helper for json strings to encode the external values correctly: `"size":  {{ size | json }}`

**Comment by dodyg** [comment]
Future reference for other people

![work-1](https://user-images.githubusercontent.com/1761249/56958637-16c15900-6b4b-11e9-9a2c-02b4ca68e2dd.png)

**Comment by Skrypt** [comment]
I thought this was already in the documentation.

**Comment by dodyg** [comment]
Unfortunately no. There is a documentation on how to pass parameter in  SQL Queries.

**Comment by Skrypt** [comment]
So we need more documentation on Lucene Queries then. You can open an issue if there is none about it. Title : Lucene Queries documentation.

**Comment by dodyg** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/3550
