### ISSUE TITLE
404 error when enabling features

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#3544]
I have managed to reproduce this issue twice now. Works fine on local host. I reverted the "Features Bulk Actions" changes and still managed to get the same error.

Steps to reproduce:

1. Open latest dev branch
1. Right click the OrchardCore.Cms.Web and click publish
1. Create a new app service to publish the site to
1. Setup the site once publish completes
1. Navigate to the admin area and enable a module

This should result in a 404 error.
![image](https://user-images.githubusercontent.com/164331/56942771-85a6ae00-6b5b-11e9-8805-efca938ace03.png)

The issue is that it is using GET rather than POST
![image](https://user-images.githubusercontent.com/164331/56943735-fd76d780-6b5f-11e9-958d-a7e6535a77c7.png)

**Comment by petedavis** [comment]
This is actually a common issue. After disabling the cache on localhost I now have replicated the issue. Must be a script issue where the cached one was working.

**Comment by jtkech** [comment]
I can repro it locally, 1st in a published folder, then yes even in dev mode.

**Comment by petedavis** [comment]
Yeah I must have had cached behaviour. 

Stepping through TheAdmin.js now to see what `itemprop="UnsafeUrl"` does to make a form POST button.

**Comment by petedavis** [comment]
Found it @jtkech 

The final form post was deleted.

![image](https://user-images.githubusercontent.com/164331/56944850-28fbc100-6b64-11e9-8e40-fc5baf997d89.png)

**Comment by jtkech** [comment]
Cool 👍
