### ISSUE TITLE
Make ContentPicker Vue components reusable

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3547]
I needed to pre-select a value from a ContentPicker through javascript but the Vue.js components we're not reusable from a different script than the contentPicker.js file.

I will provide a PR and an explanation later on.

See https://github.com/OrchardCMS/OrchardCore/pull/3548

**Comment by stevetayloruk** [comment]
@Skrypt I would like to reuse the ContentPickerField. I've extended `User` with some simple text fields but would like to assign a content item to each user.  Are you able to point me in the right direction?

**Comment by Skrypt** [comment]
You will need to create a sectionDisplayDriver.

**Comment by stevetayloruk** [comment]
Ah, thanks.  I thought there would be a better way than to just copy the implementation.  Isn't it reusable then?

**Comment by Skrypt** [comment]
Well here the PR was about to make the ContentPicker reusable in a later javascript call to be able to pre-select a content item. So the Vue.js component is reusable if you use the one provided in that ContentFields module. But it's always up to you to decide if you want to modify it in a different module. Maybe these Vue.js components could be eventually part of a Orchard.Components Vue.js library that could be shared across modules.
