### ISSUE TITLE
Duplicates Media when insert it in Html Body and Widget

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#3549]
_**Note:**_ Agency Theme

### Step 1
 Create a (new or edit) **Content Types** with **Flow** and **HtmlBody**. For example Page
![image](https://user-images.githubusercontent.com/6829626/56955105-1f189480-6b49-11e9-9487-bb89c517447e.png)

### Step 2
Edit editor type in the **HtmlBody** from **Standart** to **Wysiwyg**.
Edit editor type in the **Content** for **HtmlWidget** from **Multiline** to **Wysiwyg**.

![image](https://user-images.githubusercontent.com/6829626/56958506-247adc80-6b53-11e9-8e04-21f98db89492.png)
![image](https://user-images.githubusercontent.com/6829626/56958678-9d7a3400-6b53-11e9-9735-ef1782bcf368.png)

### Step 3
Create new page and add **Html Widget**.
![image](https://user-images.githubusercontent.com/6829626/56958781-fb0e8080-6b53-11e9-8ec4-9aa0b3fe2663.png)

### Act
Try to **Insert Media** in first **Html Content**, for example. 
Second **Html Content** will be contained media which we added in the previous **Html Content**. 

![image](https://user-images.githubusercontent.com/6829626/56959637-bd5f2700-6b56-11e9-8b97-7911ff256261.png)

### Assert
Is it ok?

**Comment by Skrypt** [comment]
Looks like it appends the image shortcode in both editors. Means that there is an issue in the jquery selector that will select every Wysiwyg editor contained in that page.

**Comment by Skrypt** [comment]
Issue is there : 

![image](https://user-images.githubusercontent.com/3228637/56960815-0c3d9a00-6b20-11e9-9593-d7ebf7a354c1.png)

**Comment by agriffard** [comment]
Is it still occuring?

**Comment by johnrom** [comment]
Yes, it's still occurring. Additionally, if you have two HTML widgets, the second one's modal will not work unless the first widget accordion is open. The fix is to move the whole media app and delegate event listeners as demonstrated in this [plugin for CKEditor 5](https://github.com/johnrom/ckeditor5-oc-media/blob/master/src/ckeditor5-oc-media.js).

**Comment by agriffard** [comment]
Tested. Not happening anymore.
