### ISSUE TITLE
Add font awesome icons to the admin site

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3563]
During low internet connection like what I'm facing nowadays , it would be nice if the admin menu bar icons show up even offline, we don't enforce anyone to have internet during development, but in production of course using online cdn is a better choice

**Comment by Skrypt** [comment]
I thought we could set it to not use CDN maybe it's not added to the ressource or there's no CDN associated with this ressource.

**Comment by sebastienros** [comment]
We intentionally don't include font-awesome as I am not sure we legally can redistribute it, or which version of it. And also because it's huge, and we'd have to update the files quite often.

**Comment by sebastienros** [comment]
What you can do, is an external module on nuget that will provide it and redefine the resource manager definition for it so it uses these files.

**Comment by hishamco** [comment]
Ya it's huge little bit, but same thing for media explorer all almost it's assets online. . I think we need a proper solution for such things

**Comment by hishamco** [comment]
@sebastienros if I used a named style that's already exist in `OrchardCore.Resources`, it works fine with me, the things I notice two icons are disappear but I fix their classes

Shall I push a PR for my changes?

**Comment by agriffard** [comment]
Font awesome is now included in OrchardCore.Resources
