### ISSUE TITLE
Fix RTL issue with Assets page

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3566]
On behalf of @aghili371 who report this bug [here](https://github.com/OrchardCMS/OrchardCore/pull/3457#issuecomment-488791146)

**Comment by aghili371** [comment]
thank you for fixing it, sorry i was busy to open an issue.

**Comment by hishamco** [comment]
No problem .. the fix is almost ready from yesterday, I will push a PR soon
