### ISSUE TITLE
Clean double encoding issues

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#3570]
For instance when rendering a link with this code: `Html.ActionLink(T["Close"].Value` the localized version will be double encoded.

Searching for `"].Value` shows many instances throughout the code and we should clean it.
Then replace with raw Html, like `<option>` instead of `SelectListItem` or `<a>` instead of `ActionLink`

**Comment by hishamco** [comment]
That's why I didn't see `SelectListItem` quite often .. but let us think about it, why this happen, what's the alternative solution, perhaps it's localization issue

**Comment by hishamco** [comment]
What about using anchor TagHelper instead of `Html.ActionLink`?

**Comment by sebastienros** [comment]
Same issue. Use <a>

**Comment by hishamco** [comment]
Could you please let me know why we need to use `T["Close"].Value` instead of `T["Close"]`?

**Comment by sebastienros** [comment]
What I said is that we can't use `T["Close"].Value` in a razor helper like `Html.ActionLink`.

**Comment by hishamco** [comment]
Why we can't .. I just use it now and it works fine, is this the case if the localized value is html?

**Comment by sebastienros** [comment]
Try with anything that will be encoded, like tags, or some international chars that can be encoded (eacute?)

**Comment by hishamco** [comment]
> What I said is that we can't use T["Close"].Value in a razor helper like Html.ActionLink.

Also in `TagHelper` but if there 're few places that where encoded is needed we can use `TagHelper` with `Html.Raw()` to fix the issue

**Comment by sebastienros** [comment]
There is no reason to call .value in tag helpers. But in razor helpers it only accepts a string so you are tempted to use it. Which is wrong.

**Comment by hishamco** [comment]
> There is no reason to call .value in tag helpers

Yep, I forgot, no need to use it
