### ISSUE TITLE
Create culture picker

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3572]
It would be nice if we have a culture picker / language switcher in the localization module. I'm interesting on this because I already did one for my own and other OSS projects

The picker will be useful for both front-end and back-end, some examples are setup screen, content localization .. etc

**Comment by hishamco** [comment]
https://github.com/hishamco/languageswitchertaghelper

**Comment by jptissot** [comment]
I am also interested in this.

**Comment by hishamco** [comment]
I can suggest some of the its features, you too and @sebastienros can share some of his thoughts about this

**Comment by jptissot** [comment]
I am mostly interested in a culture picker for the frontend right now. Should display a dropdown of the available cultures and store the value in a cookie. The cookie should be used by the localization middleware  to set the current thread culture. @Skrypt

**Comment by hishamco** [comment]
https://polylang.pro/doc/the-language-switcher/
https://wordpress.org/plugins/multisite-language-switcher/

**Comment by hishamco** [comment]
> I am mostly interested in a culture picker for the frontend right now. Should display a dropdown of the available cultures and store the value in a cookie

No need, we can use the ASP.NET Core localization cookie to set both `culture` and `ui-culture`, this way the localization middleware will aware about any changes

**Comment by Skrypt** [comment]
@hishamco Is it what your languageswitchertaghelper does or does it set a different cookie or browse to a different url (?culture=en-US) ?

**Comment by sebastienros** [comment]
you need to set a cookie. The one that aspnet understands

**Comment by hishamco** [comment]
@Skrypt is set the localization cookie behind the scenes

**Comment by hishamco** [comment]
Seems @jptissot  is already implement this one
