### ISSUE TITLE
Application using nuget packages: Localization files not taken into account

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3576]
When I test the latest version:
- Unzip fr localization files from Crowdin in App_Data\Localization\fr\...*.po .
- Enable Localization module.
- Add `fr` culture in the settings and set it as default.
=> The culture is not applied.

It only works if I add `?culture=fr` in the querystring and it is lost if the page is changed.

Same issue with the nuget packages (v 1.0.0-beta3-71285) or with the solution in source control.

**Comment by hishamco** [comment]
I saw a localization commit today, I am nit sure if it is the reason behind this bug .. let me check this issue and fix it

**Comment by hishamco** [comment]
I used `ar` culture which is not make any difference and it works fine on the dev branch, @Skrypt could you please verify from this one?

**Comment by Skrypt** [comment]
This is a totally different issue there. "fr" is not a proper culture setting and "ar" is not either. It will never resolve any valid culture in the framework when doing for example CultureInfo.GetCultureInfo("fr").

**Comment by agriffard** [comment]
OK. if I use `fr-fr`, it works.

But if I use the `System (fr-FR | French (France))`, it does not work.

And I guess some people will make the same mistake because `fr` is provided in the list of cultures you can add.

https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Localization/ :
`[CultureName] can is either the culture neutral part, e.g. fr, or the full one, e.g. fr-CA.` (typo to fix, btw). Now I understand it is only in the path of the .po files, not as the selected culture.

**Comment by Skrypt** [comment]
Well I will make some more tests because I'm not 100% sure of what I stated earlier about the fact that fr is not a proper culture. Let me test more. So far, after when adding "fr" to the supported culture it pass in the Regex validation and returns true. And it adds it properly in the culture list and is also displaying proper culture information in that list.

![image](https://user-images.githubusercontent.com/3228637/57183608-63739f80-6e7d-11e9-9fb9-9b244e103021.png)

![image](https://user-images.githubusercontent.com/3228637/57183623-a5044a80-6e7d-11e9-8dd0-3039622960b8.png)

**Comment by Skrypt** [comment]
https://localhost:44300/?culture=fr works.
Now will try to load the Crowdin localization files in my next test because it should work.

**Comment by Skrypt** [comment]
Sorry for the size of the gif but you can see my tests there : 
![orchard](https://user-images.githubusercontent.com/3228637/57183776-e1d14100-6e7f-11e9-848b-c3a0e0784d29.gif)

**Comment by Skrypt** [comment]
@agriffard please Skype me if the issue remains. Maybe you are not on latest commit or there is something different on your side.

**Comment by Skrypt** [comment]
I found maybe an issue but I'm not sure if it's one. I cloned the "fr" folder and renamed it to "fr-CA" and it doesn't seem to load it. Maybe an issue with the way I named my folder or I should do something specific in those .po files?

**Comment by agriffard** [comment]
It worked with the source code but it is not working with the nuget packages in admin.

Tested on my app for `Try OrchardCore fr` in which there is a module OrchardCore.Try which has a .po file in the App_Data of the module to translate the form on the homepage.

On the front, the selected culture (fr-fr) is loaded and the corresponding .po file in the module is used.

In the admin, the selected culture is not loaded, and the .po files are not applied even if I add `?culture=fr-fr` but I can see `<html lang="fr-FR" dir="ltr">` when I do 'view source'.

**Comment by hishamco** [comment]
@Skrypt natural culture should work without any issue, I always doing that with asp.net core.

**Comment by Skrypt** [comment]
@hishamco @agriffard Then that's an issue with the po file loader extension. I could be wrong but to be sure we need to see which CultureInfo.CurrentCulture or CultureInfo.CurrentUICulture is applied when it doesn't work and also look at what value the po file loader extension use to determine which culture it should load.

**Comment by Skrypt** [comment]
I think I found the issue. There is no fallback for .po files. It loads the cultures as they are named only.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/3574/files
You guys are funny you ; fix the issue and report the issue afterward. 😄

**Comment by hishamco** [comment]
> There is no fallback for .po files. It loads the cultures as they are named only

There was the fallback to the parent culture, so localizer look for culture first as a name of .po file if it's doesn't found it look for the parent culture

The bug I reported and fixed is expected .. I was thinking of it few days ago that there is no respect to the `RequestLocationOptions.FallBackToParentUICultures`

Hope it's clear 😄

**Comment by agriffard** [comment]
Reopen to make it work with nuget packages.

**Comment by hishamco** [comment]
@agriffard how the nuget packages are different from the App_Data one

**Comment by hishamco** [comment]
@agriffard is this issue still happening?
