### ISSUE TITLE
can not send email on server side

### ISSUE THREAD

**Issue by DaZiYuan** [OrchardCMS/OrchardCore#3583]
it works fine in local environment. but when I upload it to Ubuntu use the same config ,it just report error. I already opened the output port 587, somebody can help me?

sender: donotreply@snowlab.cn
host: smtp.exmail.qq.com
port: 587
password: UJfnLthLEexfgxHy

---
An error occurred while sending an email: 'An error occurred while attempting to establish an SSL or TLS connection. The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons: 1. The server is using a self-signed certificate which cannot be verified. 2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate. 3. The certificate presented by the server is expired or invalid. See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.'
---

**Comment by DaZiYuan** [comment]
![image](https://user-images.githubusercontent.com/80653/57215055-6ce83d80-701e-11e9-982b-080e42098bc8.png)

![image](https://user-images.githubusercontent.com/80653/57215201-c5b7d600-701e-11e9-92cf-707b213171ee.png)

**Comment by MichaelPetrinolis** [comment]
it is related to #3556 , it uses SSL over 587 which should use STARTTLS after connect
if you telnet smtp.exmail.qq.com 587 , you will see that the mail server requires STARTTLS
