### ISSUE TITLE
Media SupportedSizes error when not in ascending order

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3587]
We should log or throw exception on startup when `SupportedSizes` array is not in ascending order, and better document that, as it has caught a few of us now (@scleaver and me!)

@sebastienros Exception on Startup or LogError ?

**Comment by scleaver** [comment]
@deanmarcussen it's especially hard to work out the issue after a long day.

**Comment by scleaver** [comment]
However, I think that the guys said they might be getting rid of the SupportedSizes because it is not easy to add new sizes without changing config.

**Comment by deanmarcussen** [comment]
@scleaver Indeed!

How best to protect against DOS attacks then? I had one the other day (non OC site) that was slow enough not to trigger any of my IIS / Firewall configuration but still managed to chew up a bunch of resources

**Comment by sebastienros** [comment]
We might be able to do a feature that will work without these sizes, but some scenarios might still need it. Let's add a Warning log.
