### ISSUE TITLE
How to translate string with format

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3592]
All the hints in the Registration Settings page are not translated.

See in OrchardCore.Users/Views/RegistrationSettings.Edit.cshtml
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/Views/RegistrationSettings.Edit.cshtml

`@T["— {0}", "Display a link to allow the users to register on the site."]`

How should it be generated in the .po files?
And does it have to be detected and generated by @lukaskabrt po-extractor tool?

**Comment by lukaskabrt** [comment]
Additional arguments aren't processed in any way neither they are extracted by po-extractor. They are just passed to the `string.Format` function, which process the translated string. Arguments allow developers to add some additional data (e.g. name of the content item, items count ...) to the translated string, but they aren't intended to for this use case.

In this case `"— {0}"` is translated and then `string.Format` inserts `"Display a link to allow the users to register on the site."` to the translated text.

I would simply use:
`@T["— Display a link to allow the users to register on the site."]`

**Comment by Skrypt** [comment]
The "—" could be also moved out of that string since it should never require to get translated.

**Comment by sebastienros** [comment]
This should be `@T["— Display a link to allow the users to register on the site."]`.
There is no need for a parameter here. But the `—` needs to be in the string so that a RTL language can put it on the right.

**Comment by sebastienros** [comment]
We usually do `@T["— {0}", myVariable]` when it needs a variable value on the right, like Content Type, but here it's not the case. And even in this case we need the "—".

**Comment by hishamco** [comment]
> But the — needs to be in the string so that a RTL language can put it on the right.

No need, because the direction will flips automatically, so the translation will be "- اعرض رابط للسماح للمستخدمين بالتسجيل في الموقع."

So the `dir="rtl"` who will makes reading correct from right to left

I'm with @Skrypt no need to include symbols inside the translation unless if it's necessary

**Comment by sebastienros** [comment]
Your example is opposite to what you state. Can you double check?

**Comment by agriffard** [comment]
Are you asking this to me or to Hisham?
Yes, I checked what he said and, indeed, with an RTL culture set, the `—` is flipped and stays between the text and the checkbox.
![image](https://user-images.githubusercontent.com/703248/57466421-e7b09300-7280-11e9-9a1e-2b94af6144e8.png)

**Comment by hishamco** [comment]
Let me check it at my end coz the entire line is not fully translated

BTW the pic shows that there're some translations need to be fixed 😂

**Comment by hishamco** [comment]
It works without any issue ..

**Comment by Skrypt** [comment]
I'm guessing the container will flip it as long as it's entire string content start with the "—".
