### ISSUE TITLE
Workflow Create Content Task breaks Content Item Listing UI

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3593]
I created my first workflow, a simple one.

![screw-up](https://user-images.githubusercontent.com/1761249/57432047-012bed80-7235-11e9-99d5-103905fa1c8d.png)

I made a mistake in `Create Content Task` template.  When I submitted my contact form input, a workflow instance was created and executed. Now my Content Items listing UI is broken.

![screw-up-2](https://user-images.githubusercontent.com/1761249/57432056-05580b00-7235-11e9-9cf9-fcfede4e02f2.png)

This is my definition for `Create Content Task`. I forgot to use the `{{ }}` delimiters.

![screw-up-3](https://user-images.githubusercontent.com/1761249/57432058-07ba6500-7235-11e9-9659-24396c3d052a.png)

**Comment by dodyg** [comment]
I can fix this by removing the offending entries from the sqlite db. However if I were in a hosted scenario, this mistake would have ruined my CMS.

**Comment by dodyg** [comment]
This is the standard definition when you create a `Create Content Task`. I just leave it as it to test.

![screw-up-4](https://user-images.githubusercontent.com/1761249/57434034-430b6280-723a-11e9-84f6-d06062e87d0c.png)

This is the entry inserted in the DB

```
{"ContentItemId":"48xtce4mfzkr363t3g37nsva5y","ContentItemVersionId":"4ke7q4vpwfy7242d04545kp9ck","ContentType":"ContactUs","DisplayText":{"Name":"Enter a title","Value":"Enter a title","ResourceNotFound":false,"SearchedLocation":null},"Latest":true,"Published":false,"ModifiedUtc":"2019-05-09T07:08:47.3309073Z","PublishedUtc":null,"CreatedUtc":"2019-05-09T07:08:47.3309073Z","Owner":null,"Author":null,"ContactUs":{},"TitlePart":{}}
```

This Content Item generates the following exception at the Content Items listing UI

```
An unhandled exception occurred while processing the request.
JsonReaderException: Unexpected character encountered while parsing value: {. Path 'DisplayText', line 1, position 139.
Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
```

**Comment by dodyg** [comment]
I am using this version of Orchard Core

```
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-beta3-71319" />
```

**Comment by dodyg** [comment]
OK it works with just simple declaration like this. However the default value perhaps should be updated because people would just assume that the default will always work.

```
{
 "TitlePart": {
 "Title": "{{ ContactUs.name }}",
 }
}
```

**Comment by sebastienros** [comment]
Don't assign anything to titlepart. Use DisplayText at the root and assigned a string

**Comment by dodyg** [comment]
Then this default needs to be fixed.

![bug](https://user-images.githubusercontent.com/1761249/57544469-b35bd600-7357-11e9-81d1-301413dd863a.png)

**Comment by sebastienros** [comment]
Yeah that's crazy ;)

**Comment by Skrypt** [comment]
Maybe encoding issues related with the changes we made.

**Comment by sebastienros** [comment]
Fixed in the dev branch
