### ISSUE TITLE
need to fix: RTL for media style 

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3599]
@hishamco 
just in tree show the children on one side with the parent, I think it's better to have padding for children.
the pointer for open tree nods are in the right of the folder name, it should be float left and in another side of the folder name.

**Comment by hishamco** [comment]
AFAIK everything should be OK unless there's external style, please screenshot

**Comment by aghili371** [comment]
please have look on orginal and RTL. 
root folder (media library) should start from the right and the last folder should be left.
padding for subfolders it necessary.

![rtl1](https://user-images.githubusercontent.com/24512878/57557700-58d47100-737b-11e9-896a-76a827702fd9.JPG)
![rtl2](https://user-images.githubusercontent.com/24512878/57557701-58d47100-737b-11e9-9f71-9851b924b5dc.JPG)

**Comment by hishamco** [comment]
Let me check this one .. thanks

**Comment by hishamco** [comment]
I fixed one of the two unexpected issues:

~~1. Vue folder component sets the padding of the media tree to left~~
2. RTL gulp task seems negate the rotation angle, so that's why the arrow is flipped

The media now is look like
![Assets](https://user-images.githubusercontent.com/3237266/57570133-66cfd380-7407-11e9-96b3-52a8e6a3f40e.png)

**Comment by hishamco** [comment]
I will try to make a workaround for the second one

**Comment by hishamco** [comment]
Finally it works .. hope I didn't see any inline styles anywhere in other modules :)

**Comment by hishamco** [comment]
![Assets2](https://user-images.githubusercontent.com/3237266/57585814-f18efc00-74f5-11e9-844d-7ab5274a05d5.png)
