### ISSUE TITLE
Content culture picker

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3606]
This is useful for content localization, the user will be able to switch the content and it's translations if there's

**Comment by sebastienros** [comment]
For the front-end?

**Comment by hishamco** [comment]
I think the culture picker / language switcher is suited for front end .. this may suited for back-end

Your thoughts?

**Comment by sebastienros** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/3572

**Comment by sebastienros** [comment]
front-end is definitely needed, and back-end might be nice too but it's a niche IMO, as the browser's settings should be sufficient. Unless you prefer a language that your browser doesn't know about, and it's more a setting for the user profile in the admin than a picker that would be accessible everywhere. So lets only start with the front end. 

And maybe close this issue as it's a duplicate.

**Comment by hishamco** [comment]
OK, I was thinking of this as the one that allow us to switch the translation for a specific content but it's fine to close this
