### ISSUE TITLE
OpenID Connect - Synchronize Roles on Login from External Provider based on Claims

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#3610]
Hey, as the title says, I have an external identity provider and I've been able to configured Orchard to allow it to login using this external provider.

The only thing that I haven't been able to do is to dynamically update the users roles according to the claims returned by the identity server.

I've read the following issue: https://github.com/OrchardCMS/OrchardCore/issues/2029 and it seems that my use case is included in it somewhat. However is there any way (for now) to simply intercept the login somehow?

I've tried using ILoginFormEvent but I haven't quite been able to access the claims being returned by the identity server.

Thanks in advance.

**Comment by MichaelPetrinolis** [comment]
Until #2029 gets implemented, we can Introduce an interface to inform of a successful external login. The handlers should be called from Account Controller on successful ExternalLoginSignIn, and return a list of roles/permissions translated from the external principal that AccountController adds to the OC user.

**Comment by nuno-tiago-reis** [comment]
#3488 and #3722 fixed my issue, going to close this, thanks.
