### ISSUE TITLE
Not possible to delete content type

### ISSUE THREAD

**Issue by microposmp** [OrchardCMS/OrchardCore#3611]
The new modal dialog breaks delete content type functionallity.

![image](https://user-images.githubusercontent.com/49494169/57552544-88c84800-736c-11e9-9475-4bbea70601cf.png)

When pressing Ok the action is never performed and navigation to undefined page is taking place.

![image](https://user-images.githubusercontent.com/49494169/57552683-f6747400-736c-11e9-91f5-dd8d7c14ae40.png)

**Comment by hishamco** [comment]
Let me check this one

**Comment by scleaver** [comment]
I am also seeing this error.

**Comment by hishamco** [comment]
I can reproduce the issue, I'm trying to find a better way to cleanup the javascript code and make the bootstrap modal synchronised

**Comment by lukaskabrt** [comment]
@sebastienros it seems, that because of my comment, GitHub closes both issues, when have closed #3724. This one should remain open.

**Comment by sebastienros** [comment]
No, I merged the fix

**Comment by hishamco** [comment]
@lukaskabrt this is caused by bootstrap confirm dialog

**Comment by sebastienros** [comment]
@hishamco 

![image](https://user-images.githubusercontent.com/1165805/58599527-83f10880-8235-11e9-9a73-14557b7692da.png)

**Comment by hishamco** [comment]
Don't blame me .. nowadays I'm working with a very slow Internet 😊
