### ISSUE TITLE
Markdown editor should use same grey as rest of admin

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3624]
The markdown editor toolbar should use the same grey `#dee2e6` - bootstrap `$gray-300` as the rest of the admin borders

Currently uses `#bbb`

![markdown-editor](https://user-images.githubusercontent.com/13782679/57580225-e6f54800-749e-11e9-866e-ce84d27307bc.PNG)

**Note** class to override is `.editor-toolbar`

**Comment by deanmarcussen** [comment]
@Skrypt I just made this change. 
Do you think it's worthwhile to change the button styles and fonts to match the html editor (grey background and a white hover over the buttons) - does look much cleaner?

**Comment by Skrypt** [comment]
Can you send me a screenshot here?

**Comment by deanmarcussen** [comment]
After fixing the border...
![after-border-fix](https://user-images.githubusercontent.com/13782679/57676731-1c27a480-761d-11e9-9d99-c0d426e52544.PNG)

And the html editor toolbar looks like

![html-toolbar](https://user-images.githubusercontent.com/13782679/57676748-26e23980-761d-11e9-9f4e-5b46d2f46f1e.PNG)

Must go to work :)

**Comment by Skrypt** [comment]
Yes, it's fine, push a PR with those changes.
I think though that eventually we should try to look for an alternative if it's no longer maintained.

I found that one by looking quickly : 

https://github.com/benweet/stackedit.js
MIT Licence

**Comment by deanmarcussen** [comment]
@Skrypt Will push PR tonight. Cheers

**Comment by Skrypt** [comment]
Forget what I said about those 2 other editors. We should keep simplemde and customize it for our needs.
You can look at what they do in Ghost CMS for some ideas.

**Comment by deanmarcussen** [comment]
Yeah I'm having a tinker with the css for it, just needs a few tweaks. Have the toolbar actually working full screen and preview mode now, so that's a bonus

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2828

**Comment by deanmarcussen** [comment]
@sebastienros slate looks nice, but another piece of work!

I've kept simplemde and just tweaked some css and toolbar designs so at least it looks similar in style (and background color) to the html editor, and the rest of the admin. And works full screen /side-by-side (z-index's were below the orchard nav bar so lost to sight)

Now looks like
![markdown-editor](https://user-images.githubusercontent.com/13782679/57908663-7bcdbc00-7878-11e9-80ad-6558f539e00d.PNG)

And in full screen preview
![markdown-fullscreen](https://user-images.githubusercontent.com/13782679/57908682-85efba80-7878-11e9-96ca-9be939ea222e.PNG)

And works rtl

![markdownrtl](https://user-images.githubusercontent.com/13782679/57909336-6d809f80-787a-11e9-9cd1-fe8b52b72517.PNG)

And media picker still works properly with multiple markdown editors on the page

@Skrypt Just imported bootstrap variables with a tree walk so no gulp pipeline changes and css bloat as they're just functions and variables
```
@import "../../../../../node_modules/bootstrap/scss/functions";
@import "../../../../../node_modules/bootstrap/scss/variables";
```

**Comment by Skrypt** [comment]
Nice. Imports are fine as long as they don't transpile the whole Bootstrap 😉
