### ISSUE TITLE
Count Content Items by Type

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#3630]
Hey, as the title says, I'm trying to implement an API that provides content item querying using pagination and I need to query the database to know how many content items there are for a specific type.

Is there any way to do this?

Thanks in advance.

**Comment by Skrypt** [comment]
For a pager the recommended solution is to not use SELECT Count(*) from DB because it doesn't scale well. Instead you can do a Query that will do paging in the database with OFFSET x LIMIT x and pre-fetch the result of the pages you want to list in advance to make sure there is results in those pages.

**Comment by nuno-tiago-reis** [comment]
Since I'm using orchard as a headless cms I'm returning all of these results in a Web API.

Can I use the ISession interface to do those queries?

**Comment by sebastienros** [comment]
Yes, you should be able to run your own query by resolving ISession in a controller, and do a count.

**Comment by sebastienros** [comment]
You can also use the GraphQL endpoint to page content items. If you don't really need to "count" you can still page by querying an extra item on top of your page. For instance if you want to page by 10, query for 11, and if you get 11 items it means you can do a query for the next page of 10.

**Comment by nuno-tiago-reis** [comment]
Do I have to create a document type index? As far as I can see the Query method also expects a query type.

````
public static IQuery<T, TIndex> Query<T, TIndex>
````

**Comment by sebastienros** [comment]
No, to query for content types you need to use the `ContentItemIndex` which is in the OrchardCore.ContentManagement project.

**Comment by nuno-tiago-reis** [comment]
Alright, thank you that did the trick!
