### ISSUE TITLE
IIS crash on template editing with preview on

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3636]
`The program '[1792] iisexpress.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.`

This happens after a while when i'm playing around in preview mode.
**I'm sorry if it's my fault, but i couldn't find something inside the docs.**

Scenario (**everything inside backend**, orchard beta 3 source version):
`ContentItem SliderItem`
I've created a template for the `SliderItem` summary view (`Content_Summary__SliderItem`)

```
<div class="site-blocks-cover overlay" style="background-image: url('{{Model.ContentItem.Content.SliderItem.Image.Paths | asset_url}}');" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
        <h1 class="text-white font-weight-light">{{Model.ContentItem.Content.TitlePart.Title}}</h1>
        <p class="mb-5">{{Model.ContentItem.Content.SliderItem.Text.Text | raw}}</p>
        <p><a href="{{Model.ContentItem.Content.SliderItem.Link.Url}}" class="btn btn-primary py-3 px-5 text-white">{{Model.ContentItem.Content.SliderItem.Link.Text}}</a></p>
      </div>
    </div>
  </div>
</div>
```

`ContentItem LandingPage`
The `LandingPage` has a `BagPart` called `SliderItems` with content items of type `SliderItem`.
I've created a template for the `LandingPage `detail view (`Content__LandingPage`)
Inside this view i want to render all `SliderItems` from the `BagPart` with their previously created template `Content_Summary__SliderItem`

(**Sub question: how am i supposed to do that correctly because it doesn't render anything?** I didn't find an example.)

```
<div class="container overlap-section">
    <div class="row">
      {% for sliderItem in Model.ContentItem.Content.SliderItems.ContentItems %}
        {{ sliderItem | shape_render }}
      {% endfor %}
    </div>
  </div>
```

So when i was playing around inside the `for` because i couldn't find a working solution, IIS always crashes when you accidentally type `Model `instead of `sliderItem` in front of the `| shape_render`.

**Comment by sebastienros** [comment]
`{{ sliderItem | shape_build_display: "Summary" | shape_render }}`
