### ISSUE TITLE
Adding ListPart overrides all parts and fields inside existing content items of type

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3641]
Adding a `ListPart` to an already existing content item with parts and fields overrides everything inside the editor view.

Repro (simplified, because in my case, i have multiple content items, etc.):
Create a content item `SomeItem` with fields and parts (in my case, a `BagPart`)
Create another item `SomeSubItem` with fields.
Add a `BagPart` to `SomeItem` with `SomeSubItem` as content.
Create a `SomeItem` and add a few `SomeSubItem` to the `BagPart`.
Publish the `SomeItem`.
Add a `ListPart` to `SomeItem` with `SomeSubItem` as content.
Open the already existing `SomeItem` in **editor** mode.

In my case, it now only displays the `ListPart` and nothing else.
If i delete the `ListPart`, the content of the `SomeItem` is displayed as it should be in the editor view with all `SomeSubItem` in the `BagPart`.

**Comment by giannik** [comment]
maybe related to : #3469

**Comment by Flarescape** [comment]
@giannik Thank you!
Looks like the same problem.
