### ISSUE TITLE
Renaming BodyPart

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#365]
Should we rename `BodyPart` to `HtmlBodyPart` as we will also have a `MarkdownBodyPart` and a layout oriented body part. Any body part is a part that provide a `BodyAspect` value. An `HtmlBodyPart` is a body part that stores its content in HTML and provides an HTML editor.

**Comment by agriffard** [comment]
Still to be done if we want to avoid confusion.

**Comment by agriffard** [comment]
I updated my website using a sqlite db with the migration script.
I don't know if I made a wrong manipulation but some `Body` have been replaced by `HtmlHtmlHtmlBody` in content definitions and items.

Additional note: If you created Liquid Templates files or in the admin, do not forget to rename them (title and inside the templates).

**Comment by agriffard** [comment]
I tested on another website and again, it renamed some occurences `HtmlHtmlBody `and `MarkdownHtmlBody`.

**Comment by awyl** [comment]
That will happen if the migration somehow ran mulitple times.

**Comment by agriffard** [comment]
The second time, I am quiet sure I run it only once.

**Comment by awyl** [comment]
By any chance, you ran the update query before?

**Comment by agriffard** [comment]
No, not on those sites.

**Comment by agriffard** [comment]
Oh, you mean the migration? Yes, may it has been executed without knowing it. This might be the cause.

**Comment by sebastienros** [comment]
Also, the module/feature name has changed, hence I don't even understand how it would run in the first place, because it should just run `Create` and return 2. I am removing this migration and posting it there instead for the ones who need to upgrade their sites, manually.

**Comment by sebastienros** [comment]
```
        /// <summary>
        /// #1933 Renamed module OrchardCore.Body to OrchardCore.Html.  This migration takes care of name
        /// changes in content definitions and content in database.  Thus, it needs to run only for existing
        /// installation with versions below 1.0.0-beta2-6646.
        /// </summary>
        public int UpdateFrom1()
        {
            using (var conn = _store.Configuration.ConnectionFactory.CreateConnection())
            {
                var prefix = String.IsNullOrEmpty(_shellSettings.TablePrefix) ? "" : _shellSettings.TablePrefix + "_";
                var sql = $@"
                    --UPDATES Module definitions
                    UPDATE {prefix}Document SET Content = REPLACE(content, 'OrchardCore.Body', 'OrchardCore.Html') 
                    WHERE Type = 'OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Environment.Shell.Abstractions';

                    UPDATE {prefix}Document SET Content = REPLACE(content, 'OrchardCore.Body', 'OrchardCore.Html') 
                    WHERE Type = 'OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Environment.Shell.Abstractions';

                    --UPDATES migrations
                    UPDATE {prefix}Document SET Content = REPLACE(content, 'OrchardCore.Body.Migrations', 'OrchardCore.Html.Migrations') 
                    WHERE Type = 'OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data';


                    --UPDATES Content Type definitions
                    UPDATE {prefix}Document SET Content = REPLACE(content, 'BodyPart', 'HtmlBodyPart') 
                    WHERE Type = 'OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions';

                    UPDATE {prefix}Document SET Content = REPLACE(content, 'MarkdownPart', 'MarkdownBodyPart') 
                    WHERE Type = 'OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions';


                    --UPDATES content items
                    UPDATE {prefix}Document SET Content = REPLACE(content, 'BodyPart', 'HtmlBodyPart') 
                    WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';

                    UPDATE {prefix}Document SET Content = REPLACE(content, 'MarkdownPart', 'MarkdownBodyPart') 
                    WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';

                    UPDATE {prefix}Document SET Content = REPLACE(content, '{{""Body""', '{{""Html""') 
                    WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';
                    ";

                conn.Open();
                conn.Execute(sql);
            }
            return 2;
        }
```

**Comment by sebastienros** [comment]
There might still be a bug in how migrations are run, I am testing one to see.

**Comment by sebastienros** [comment]
I verified successfully that migrations steps are not run multiple times. I think we should still remove this step in case it actually breaks existing sites completely. What do you think?

**Comment by aderderian** [comment]
FYI, I had to do some casting for this to work.

``--UPDATES Module definitions
UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), 'OrchardCore.Body', 'OrchardCore.Html') as ntext) 
WHERE Type = 'OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Environment.Shell.Abstractions';

UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), 'OrchardCore.Body', 'OrchardCore.Html') as ntext) 
WHERE Type = 'OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Environment.Shell.Abstractions';

--UPDATES migrations
UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), 'OrchardCore.Body.Migrations', 'OrchardCore.Html.Migrations') as ntext) 
WHERE Type = 'OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data';


--UPDATES Content Type definitions
UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), 'BodyPart', 'HtmlBodyPart') as ntext) 
WHERE Type = 'OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions';

UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), 'MarkdownPart', 'MarkdownBodyPart') as ntext) 
WHERE Type = 'OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions';


--UPDATES content items
UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), 'BodyPart', 'HtmlBodyPart') as ntext) 
WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';

UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), 'MarkdownPart', 'MarkdownBodyPart') as ntext) 
WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';

UPDATE Document SET Content = cast(replace(cast(content as nvarchar(max)), '{{""Body""', '{{""Html""') as ntext) 
WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';``

**Comment by aderderian** [comment]
@sebastienros I ran this script and then updated to latest Beta3-70371. I am still not seeing HtmlBody Parts in the admin on content items. I am using nuget packages and not Orchard source, so wondering if there is a quick way for me to troubleshoot without having all the source local? This is for an existing production site.

**Comment by aderderian** [comment]
Thanks for the tip to enable the "new" module @sebastienros. That was the final step.

**Comment by aderderian** [comment]
Hey @sebastienros , I have a DB with Body Part and Title Part from Beta 2 time. I upgraded to Beta 3 latest as of today via Nuget. TitlePart migrated fine, but the Body Part did not migrate to HtmlBodyPart. I upgraded code, started the site, enabled the new HTML module, but my old Body fields did not migrate properly. I am still seeing nothing in the Admin templates rendering for older Body fields. The Body part still exists under content definition for my custom types and also canned types like Article still do not render HTML bodies in Admin.

**Comment by sebastienros** [comment]
Ok, I think I assumed the body part was already converted using previous raw sql queries I added as a migration step, but these were only for the ShellDescriptor. I will fix it for the Body parts too. Sorry for the hiccup.

**Comment by sebastienros** [comment]
@aderderian I think we migrated to HtmlBodyPart before beta2, which might explain why it worked for me, as I had used beta2 and the HtmlBodyPart was already there.

I am adding some code that should handle this, but there might be some bugs as I couldn't test it. Worst case you'll have to run the sql queries from above, or just share the db with me and I'll update them.

**Comment by sebastienros** [comment]
Also you need to enable the HtmlBody module to trigger the migration.
