### ISSUE TITLE
Content API reponse does not process HTML filter for image paths

### ISSUE THREAD

**Issue by naammeinkyahai** [OrchardCMS/OrchardCore#3650]
When we fetch the content using the inbuilt [content API](src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs), if the content item contains any HTML filter such as

`{{ "sample.png" | asset_url | img_tag }}`

then the Response body contains that filter as-is. There should be a way to specify that filter is processed and output contains the absolute URL to the media.

**Comment by dodyg** [comment]
Related case https://github.com/OrchardCMS/OrchardCore/issues/3532

**Comment by sebastienros** [comment]
The content API has no idea how to handle that. Only the HtmlBodyPart, or MarkdownBodyPart, so the only option would be to add an extensibility point to this endpoint but that's not its goal, it's purely data oriented.

The actual solution is to use GraphQL which already supports this scenario by exposing a `html` property which does the correct conversion for each part. Does it work for you?

**Comment by sebastienros** [comment]
It's the same auth story, still HTTP request, and can be a GET (querystring) or a POST (query in the body).

**Comment by naammeinkyahai** [comment]
Thank you @sebastienros, I will give this a try.

Moreover, OrchardCore is great so thank you to the entire team for spending time to build it

**Comment by naammeinkyahai** [comment]
Thank you @sebastienros 

I am in the middle of trying out the GraphQL API. I ran into a few issues and opened bugs (#3684 and #3695). I will test it out soon.

**Comment by naammeinkyahai** [comment]
@sebastienros With the Graphql where clause bugs fixed, I was able to give it a try. It is same auth story, HTTP request etc. 

However, the HtmlBodyPart is still returning the media gallery entry as 

`{{ "sample.png" | asset_url | img_tag }}`

My graphQL query is

```
{
  helpContent (where: { contentItemId: "blah"}){
    contentItemId
    displayText
    publishedUtc
    helpGeneralContent {
      description
      htmlBody
      plainTextBody
    }
    htmlBody {
         html
   }
  }
}
```
helpGeneralContent.htmlBody is a HTML field, while htmlBody is the HtmlBodyPart. For both cases, the graphql query is returning html filter as is.

What am I doing wrong here? Or is there a bug in parsing the html body part?
