### ISSUE TITLE
RTL issu in Lucene Query template box

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3652]
in RTL admin theme, the template box not selectable to edit.and should not be right aligned and should stay left align.
![Capture](https://user-images.githubusercontent.com/24512878/57888982-e14b8980-7833-11e9-8a65-b6be9e6b0cca.JPG)

**Comment by sebastienros** [comment]
Thanks for these bug reports, keep them coming, it really helps.

**Comment by aghili371** [comment]
@sebastienros i'm not good enough to improve the OC now, but i try to test and be helpful.

**Comment by hishamco** [comment]
Nice catch Ahmad!! who said you are not good to improve the OC, this kind is veryyyyyy helpful, especially for me 😄 

thanks

**Comment by hishamco** [comment]
@aghili371 please refer me to the view names or at least from where I can catch this view, because I found similar issue in the Query menu

**Comment by aghili371** [comment]
> Nice catch Ahmad!! who said you are not good to improve the OC, this kind is veryyyyyy helpful, especially for me 😄
> 
> thanks

thank bro :)

**Comment by aghili371** [comment]
> @aghili371 please refer me to the view names or at least from where I can catch this view, because I found similar issue in the Query menu

it in query. you have found it.

**Comment by hishamco** [comment]
I think this should be fixed by PR #3669 too, please try the latest bits and close this if it's fixed

**Comment by hishamco** [comment]
@aghili371 Any updates on this?

**Comment by aghili371** [comment]
> @aghili371 Any updates on this?

it works fine. i have other notes, i will file new issue.

thank for your great job.

**Comment by hishamco** [comment]
Sound good
