### ISSUE TITLE
how to get all content items from the controller to the view using the view model?

### ISSUE THREAD

**Issue by juniordev19** [OrchardCMS/OrchardCore#3656]
1) I am trying to get all articles from a database using queries. I don't want to use liquid. I need to get a list of all the elements in the controller and pass the list to the view model, then display the data using razor. I tried to use the following objects in the controller:

```C#
[Route("/articles")]
        public async Task<IActionResult> ArticleList()
        {
            //ISession
            var items = await _sqlSession.Query<ContentItem>()
                            .With<ContentItemIndex>(index => index.ContentType == "AllArticles")
                            //This is where you issue is the ContentType name is probably "Articles"
                            
                            .With<ContentItemIndex>(index => index.Published)
                            .ListAsync();
            return View(items);
            ---------------------------------
            //IQueryManager
            var items = await _queryManager.GetQueryAsync("AllArticles");
            return View(items);
            ---------------------------------
            //IOrchardHelper
            var items = await _orchardHelper.QueryAsync("AllArticles");
            return View(items);
            ---------------------------------


            return View(items);
        }
```

What type of data comes into the view model?

2) Are there any other ways to get list of content items by type other than using queries?

**Comment by juniordev19** [comment]
I found the answer to the first question.
maybe there is a better solution?

Controller:
`       [Route("/articles")]
        public async Task<IActionResult> ArticleList()
        {
            var query = await _queryManager.GetQueryAsync("AllArticles");
            var queryParameters = new Dictionary<string, object>();
            var result = await _queryManager.ExecuteQueryAsync(query, queryParameters);
            var resultList = ((IEnumerable)result).Cast<ContentItem>().ToList();
            return View(resultList);
        }
`

View:
`
@model List<OrchardCore.ContentManagement.ContentItem>

                @foreach (var item in Model)
                {
                    @item.Author                                    <br />
                    @item.Content.TitlePart.Title             <br />
                    @item.Content.HtmlBodyPart.Html   <br />

                }
`

the second question remains open.

**Comment by Skrypt** [comment]
You need to declare a ViewModel that will return the contentitems list shape and the other required fields. You then in your view set @model YourViewModel to be able to use the model databinding. And then if you want to do your foreach on your content items shape you can use your Model.ContentItems for example. But declaring you List of shapes as the ViewModel will prevent you from using things like asp-for or asp-items taghelpers.

**Comment by juniordev19** [comment]
thanks for the answer. I probably did not correctly formulated the second question. I mean, is it possible to extract a list of all content items without using queries (sql, lucene, graphiql) inside the controller?

**Comment by Skrypt** [comment]
You can use ISession and pass a SQL Query directly.
