### ISSUE TITLE
GetConfiguredCultures small change

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3661]
@sebastienros You will hate me but I found one from yesterday after thinking about it for the 1000th time.
We still need to not add the default system culture as supported if someone has selected manually a default culture.

```C#
        public static string[] GetConfiguredCultures(this ISite site)
        {
            return new[] { site.Culture ?? CultureInfo.InstalledUICulture.Name }.Union(site.SupportedCultures).ToArray();
        }
```

OR (equivalent)

```C#
        public static string[] GetConfiguredCultures(this ISite site)
        {
            if (site.Culture != null)
            {
                return site.SupportedCultures;
            }
            else
            {
                return new[] { site.Culture ?? CultureInfo.InstalledUICulture.Name }.Union(site.SupportedCultures).ToArray();
            }
        }
```

**Comment by hishamco** [comment]
I need to look on this, because I still need to test some cases, please stay tuned ...

**Comment by hishamco** [comment]
BTW for such thing I suggest to write a unit tests for all the cases and keep them update it, instead of change the code every time, please let us don't TRUST our manual test and use automated tests instead 😄

**Comment by Skrypt** [comment]
Yeah let's make unit tests while I'm at it.

**Comment by hishamco** [comment]
I will add some unit tests too 😊
