### ISSUE TITLE
Bulk Actions Select All Icon Placement

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3677]
@Skrypt The bulk actions select all icon's placement seems to be off.

Is this happening for you too, or is it just me?

Pulled from latest dev branch this morning.

![oc-bulk-actions](https://user-images.githubusercontent.com/13782679/58082132-472a6f00-7bae-11e9-8fd3-25e470c3a0c5.PNG)

**Comment by Skrypt** [comment]
Which browser?

**Comment by Skrypt** [comment]
Clearly something is wrong because mr-n2 doesn't work.

**Comment by deanmarcussen** [comment]
Chrome / Windows 

Isn't it mr-2 ?

**Comment by Skrypt** [comment]
Yeah issue seems to be with latest Sass compilation. mr-n2 works too it does a negative margin.

**Comment by Skrypt** [comment]
I tried locally, I recompiled my Sass TheAdmin.scss file and it fixed it.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/3679

**Comment by hishamco** [comment]
Yep I compile the assets when I test, but before the merge I rebase on dev and run gulp build. Is there any issue with I am doing?!!

**Comment by Skrypt** [comment]
Then maybe it's because you needed to redo a npm i for refreshing your package.lock.json files.

**Comment by hishamco** [comment]
May be .. thanks

**Comment by deanmarcussen** [comment]
> Yeah issue seems to be with latest Sass compilation. mr-n2 works too it does a negative margin.

Handy, must have a look at the bootstrap change logs. Cheers for #3678
