### ISSUE TITLE
Add breadcrumb to the admin site pages

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3687]
We need to add breadcrumb to the admin site pages, because I find it only in `OrchardCore.Settings/Admin/Culture`. 

Breadcrumb is very handy in the navigation between hierarchy of pages

**Comment by hishamco** [comment]
It could be before the page title
![Breadcrumb2](https://user-images.githubusercontent.com/3237266/58205943-59102d00-7ce8-11e9-9934-22b62afb45b6.png)

or in the nabar
![Breadcrumb1](https://user-images.githubusercontent.com/3237266/58205957-62999500-7ce8-11e9-877f-ebbc9ad85c17.png)

**Comment by hishamco** [comment]
I like the 2nd one 👍

**Comment by matiasmolleja** [comment]
I like the idea of a breacrumb. 
I would prefer the first one. The top bar could be a zone where modules could add buttons or dropdowns. Examples: The tenants module could add a list of tenants to quicky switch to one of them, the users module could add a list of recently edited content items etc...

**Comment by deanmarcussen** [comment]
Looks great, I like the idea of a breadcrumb as well.

What does it look like when editing content? 

Would really like to have navigation back to the parent content items when editing lists, especially when they are recursive.

I'm with @matiasmolleja on the first one, top bar should be free and should be a zone to put buttons and dropdowns into.

I assume it's a zone? Below top bar and above Messages

**Comment by hishamco** [comment]
> What does it look like when editing content?

This is not related to the content, so nothing show up on editing content. It could be static or dynamic.

> I'm with @matiasmolleja on the first one, top bar should be free and should be a zone to put buttons and dropdowns into.

No problem .. I love the community folks opinions unless it's incorrect 😄, your thoughts @sebastienros to finish this and start working on it

**Comment by EternityTeam** [comment]
This is a good improvement, or we can provide tabbed style management to improve efficiency

**Comment by hishamco** [comment]
My idea is to make static but moving this to dynamic may not in plan of Orchard Core 1 RTM, so the decisions to the PM 😊

**Comment by sebastienros** [comment]
My only comment is that we need a well defined location in the template where to place them. And each page is responsible for building the hierarachy.

**Comment by hishamco** [comment]
> My only comment is that we need a well defined location in the template where to place them. And each page is responsible for building the hierarachy.

That's why I preferred the navigation bar on because we already have a section on TheAdmin theme layout

**Comment by hishamco** [comment]
@sebastienros if it goes to the backlog, I think we need to remove the breadcrumb from the culture settings page for now

**Comment by sebastienros** [comment]
This is how it looks like in CraftCMS. They have it in the header, like your second suggestion. And the title is also move in the header. We can do it easily, and provide named zones for these. Including the side actions.

![image](https://user-images.githubusercontent.com/1165805/58660017-3af29000-82d9-11e9-9be0-fd2119205028.png)

The only thing we'd change from Craft is to be able to show/hide the sidebar. And the account information is moved on the left of the header. The sidebar goes at the bottom when the screen size is small. The login information is accessible when you expand the menu. The logo is part of the menu, so only visible if the menu is expanded.

I'll setup some contest for all of you to show some mockups with sidebar/header. The prize is my eternal respect.

**Comment by hishamco** [comment]
If we agreed to do it above, we can make of use the nav section that's already there in TheAdmin layout, but my concern now is to remove the breadcrumb from the cultures page now

**Comment by agriffard** [comment]
Breadcrumbs are useful when there are multiple levels of hierarchy.

Ex: 
- When you edit a content item, display a parent link to go the content items of the content type. 
- When you edit a content item with a type that has a ListPart, display a parent link to go to the page that list all the items contained by this ListPart.
- More generally, when you edit any object (DeploymentStep, Index, Query, Role, User, Widget), display a parent link to list that allows to manage all of them. 

See what is already done for Workflows.

**Comment by agriffard** [comment]
Currently, it looks like this:
![image](https://user-images.githubusercontent.com/703248/66257894-edae8f80-e79e-11e9-96d2-8af2f2a7b7cd.png)

We could wrap every breadcrumbs by a `<zone name="Breadcrumbs"></zone>` and then decide where we want to place it in the admin Layout: Leave it above the content like it is right now or put it next to the title.

Here is how it would look like in the top navbar with removing the grey background:
![image](https://user-images.githubusercontent.com/703248/66257872-927c9d00-e79e-11e9-8769-332626f25786.png)

**Comment by hishamco** [comment]
I like the first option because it will not overlap with the login status. One thing you can add if we expose the `Separator` as a property on tag helper, so anyone can customize it

Great work @agriffard
