### ISSUE TITLE
Organize headers in the admin site pages

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3688]
The headers in the admin site pages should be organized from h1 to h6

**Comment by hishamco** [comment]
Before
![HeadersOld](https://user-images.githubusercontent.com/3237266/58201824-b901d600-7cde-11e9-8a42-b4d837d77ec2.png)

After
![HeadersNew](https://user-images.githubusercontent.com/3237266/58201829-be5f2080-7cde-11e9-9c16-6089aa9f3595.png)

**Comment by agriffard** [comment]
As suggested recently, we might want to put the title in the top bar to gain more space.

**Comment by hishamco** [comment]
> to put the title in the top bar to gain more space

Do you mean beside the logo?

**Comment by sebastienros** [comment]
Yes. I think you created something like this at some point.

**Comment by sebastienros** [comment]
And make the top bar a custom theme zone (like "Content") such that any page or module can inject something here, like the links on the right.

**Comment by sebastienros** [comment]
Maybe it's the font, but the end result of the title in the top bar doesn't look good to me.

Here is how it's done in Azure DevOps

![image](https://user-images.githubusercontent.com/1165805/66678799-8d49a300-ec21-11e9-8e89-706b9bacd8b0.png)

And how it looks right now in OC

![image](https://user-images.githubusercontent.com/1165805/66678816-98043800-ec21-11e9-915b-004ba5262ffd.png)

Also, it's wrong in mobile

![image](https://user-images.githubusercontent.com/1165805/66678845-a7838100-ec21-11e9-9ffa-c2773806ae6a.png)

At least we have these zones available now for each view. But we need to find something that feels better than that.

**Comment by deanmarcussen** [comment]
For ideas, here is a mock I did some time ago when we were talking above moving the buttons to the top. It is loosely inspired by DevOps
The idea was too always/everywhere have space for two primary buttons, and everything else go into a dropdown context menu.

It still needed some more work I thought. 

But for ideas here it is :)

![mock](https://user-images.githubusercontent.com/13782679/66681695-26e97280-ec6b-11e9-8835-31fd46dc3040.png)

**Comment by sebastienros** [comment]
I have reverted the titles for now, we can continue to iterate on it before we do this change.

**Comment by Skrypt** [comment]
What we should have done like I said to @agriffard is to remove the top navbar and to integrate the Title in the page content. This is how CraftCMS does it.

**Comment by sebastienros** [comment]
@Skrypt where do you put the generic top right actions that appear on all pages then?

**Comment by Skrypt** [comment]
In the admin menu like in CraftCMS

**Comment by hishamco** [comment]
A lot of UI changes are happen since then, so time to close
