### ISSUE TITLE
Localization middleware implementation refactoring

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3694]
Notes from @sebastienros : 

> 
> 1. Move DefaultCulture and SupportedCultures settings in Localization module. Need to have it's own db table.
> 2. DefaultCutlure always has a defined value. When the feature is enabled it gets the current system culture by default.
> 
> When users need to localize the UI they need to enable this feature.

**Comment by hishamco** [comment]
> Move DefaultCulture and SupportedCultures settings in Localization module

From where the user is able to set those cultures?!!

> When users need to localize the UI they need to enable this feature

What about content localization?

**Comment by sebastienros** [comment]
> From where the user is able to set those cultures?!!

In the settings, like today, probably in a different tab/page.

> What about content localization?

Content localization will require Localization to be enabled to provide the supported culture list. This is will be in the abstractions project of Localization.

We could also decide to have two features in the localization module:
- Culture management: setting default and supported cultures)
- Culture detection: detecting the current culture and assigning it to the thread

But I don't think it's necessary.

**Comment by hishamco** [comment]
> In the settings, like today, probably in a different tab/page.

But they will not be a part of site settings, Am I right?

**Comment by sebastienros** [comment]
UI: We have a choice here. Either in the same "General" settings page, or on a custom "Localization" one, still under Settings. 

Code: They won't be in the SiteSettings class, but in a "part" that is plugged to the SiteSettings instance. Like other settings of other modules.

**Comment by hishamco** [comment]
@sebastienros Is anyone working on this?

**Comment by hishamco** [comment]
If no one working on this, I will start working on it ..

**Comment by sebastienros** [comment]
I am working on it

**Comment by hishamco** [comment]
OK ..
