### ISSUE TITLE
Unable to use Liquid filters in the AutoroutePart

### ISSUE THREAD

**Issue by lukaskabrt** [OrchardCMS/OrchardCore#3697]
Many filters (e.g. `ContentItemFilter`) use an `IServiceProvider` obtained from the `ctx.AmbientValues.TryGetValue("Services", out var services)` to resolve services, but this value isn't initialized in the `AutoroutePartHandler`.

I see the same problem also in other handlers.

**Comment by Skrypt** [comment]
Yes I had the same issue when I wanted to retrieve a content picker content item to form my autoroute with it's DisplayText value. I believe this issue has been reported elsewhere too by me.

Here I found it : duplicate of https://github.com/OrchardCMS/OrchardCore/issues/2781
