### ISSUE TITLE
Rename Culture.Dir()

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3698]
Just simple suggestion for make things clear the culture hasn't direction, the language is the one who has a direction

IMHO renaming this `LanguageDirection()` will be better, also we can introduce `enum` that contains `LTR` & `RTL` to avoid magic strings

**Comment by hishamco** [comment]
Seems this commit https://github.com/OrchardCMS/OrchardCore/pull/4039/commits/cd771b82cc50b36952923fce401eec4cd40450f7 will fix the issue

**Comment by sebastienros** [comment]
Didn't we merge this PR already? You are pointing to a commit and can't find where it's from

**Comment by hishamco** [comment]
> Didn't we merge this PR already?

Nope, here is the PR #4039

**Comment by agriffard** [comment]
#4039 has been merged.
