### ISSUE TITLE
Where clause not working in graphql. The multi-part identifier could not be bound.

### ISSUE THREAD

**Issue by meinvolk** [OrchardCMS/OrchardCore#3699]
I am having trouble executing a where clause on a content type. As you can see from one of the images I am able to pull the data. But when trying to use a where clause it throws an error of The multi-part identifier could not be bound. I am using this has a headless CMS and am only consuming JSON.
![ContentIdError](https://user-images.githubusercontent.com/29511796/58295832-03e32280-7d9f-11e9-86e0-238400ed9ba3.PNG)
![ContentId's](https://user-images.githubusercontent.com/29511796/58295833-03e32280-7d9f-11e9-89c6-89d6c9bc9b32.PNG)
![SQL](https://user-images.githubusercontent.com/29511796/58295834-03e32280-7d9f-11e9-935d-021ee59a8ffc.PNG)

**Comment by sebastienros** [comment]
I think there is another way to get a content item from its id.

/cc @carlwoodhouse @Jetski5822

**Comment by carlwoodhouse** [comment]
the query should work fine - looking at the error this issue should of been fixed by the PR's we merged yesterday #3692 and #3684 

Can you try with the latest version of dev ?

![image](https://user-images.githubusercontent.com/465424/58321230-81497a00-7e15-11e9-9439-ca7185cd327f.png)

**Comment by carlwoodhouse** [comment]
as a side note, if you skip 3 while filtering by id you're gonna get no results ;)

**Comment by carlwoodhouse** [comment]
and yes @sebastienros - you can also use 
![image](https://user-images.githubusercontent.com/465424/58321546-590e4b00-7e16-11e9-9b0d-41092647115b.png)

**Comment by meinvolk** [comment]
Yes that worked! I was using the compiled Nuget package, thank you guys! Great work on Orchard Core I am loving it so far.
