### ISSUE TITLE
Prevent new tenant initialization to run migrations

### ISSUE THREAD

**Issue by monoludic** [OrchardCMS/OrchardCore#3704]
Is it possible to prevent modules migrations when executing recipe during new tenant initialization ?

Currently one of our migration fails since a call to `_session.Query<SiteSettings>()` crashes. The database is not set up at that moment, and the table `ContentItemIndex` does not exist.

Anyway we don't need this migration since we got a fresh new database.

**Comment by sebastienros** [comment]
Can you give some repro steps to understand how it happens?

**Comment by Piedone** [comment]
This shouldn't be applicable anymore; if it is, please reopen.
