### ISSUE TITLE
email field "from" empty

### ISSUE THREAD

**Issue by LatinaAtanasova** [OrchardCMS/OrchardCore#3710]
Hello,
On decoupled project i have contact form that sends e-mails. Everything is fine but on receiving the email, the field "from" in inbox stays empty. There is no indication who sends the e-mail. 

![image](https://user-images.githubusercontent.com/32022885/58415630-bc52e400-8087-11e9-8d41-1a82d5370349.png)

So I have this in my razor page 
` var mailMessageToClient = new MailMessage
                {
                    Subject = subjectToClient,
                    Body = emailBodyТоClient,
                    From = smtpSettings.DefaultSender,
                    IsBodyHtml = true,
                    To = email,
                    ReplyTo = smtpSettings.DefaultSender
                };
                

                await _smtpService.SendAsync(mailMessageToClient);`

where From field is set, but when i debug in dev project there is a method where mimeMessage is set. However, "from" property there is readonly and can't be set. 
So, what is the solution if I want to visualize the sender in receiver's inbox?

**Comment by hishamco** [comment]
`MimeMessage.From` is read only, but `MailMessage.From` is read & write property

Just double check if `DefaultSender` is set correctly

**Comment by LatinaAtanasova** [comment]
It is set correctly, but fields for MailMessage are set first and then it goes to  
await _smtpService.SendAsync(mailMessageToClient). 
In SendAsync a new MimeMessage is declared and its properties are set then. So I have it first but then in it overridden in MimeMessage as null.

**Comment by MichaelPetrinolis** [comment]
The MimeMessage is created in the FromMailMessage and if you check https://github.com/OrchardCMS/OrchardCore/blob/8f0b283299d48a08406dc8eb8a00294482d4949a/src/OrchardCore.Modules/OrchardCore.Email/Services/SmtpService.cs#L73 it passes in the constructor the sender, in particular the Default Sender from options if message is null, otherwise message.From. Maybe you pass empty string in the From field? We could also check String.IsNullOrWhitespace instead of null to use DefaultSender from settings.

**Comment by hishamco** [comment]
> Maybe you pass empty string in the From field?

@LatinaAtanasova is said before that the sender is set.

Please try the latest bit .. or provide a repo to reproduce the issue

**Comment by LatinaAtanasova** [comment]
Hi,
What I mean is:
1. in my post method i have this:

![image](https://user-images.githubusercontent.com/32022885/58455433-58cdc280-812a-11e9-8885-ea6adf0924b3.png)

2. the return from private MimeMessage FromMailMessage(MailMessage message) is:

![image](https://user-images.githubusercontent.com/32022885/58455682-f88b5080-812a-11e9-8def-68045352d837.png)

So,
I have filled "From" property in MailMessage variable and filled "Sender" property in MimeMessage variable and i send e-mails correctly. But obviously I miss to fill the property which is responsible for filling the "Sender" in inbox. I only suppose that it is the "From" but in MimeMessage, which is not set in FromMailMessage(MailMessage message) method.
If this is not clear enough, I'll make a repo.
Thanks :)

**Comment by MichaelPetrinolis** [comment]
Thank you @LatinaAtanasova , I mistakenly thought that the MimeMessage would add the Sender in the From list. I will make a PR to add mimeMessage.From.Add(mimeMessage.Sender) to the FromMailMessage function

**Comment by LatinaAtanasova** [comment]
you are welcome :)
