### ISSUE TITLE
Injecting IContentManager to a ContentPartHandler causes circular dependency

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#3713]
When you inject IContentManager (or a service which uses IContentManager) into a ContentPartHandler will throw an exception because of circular dependency.

To simply reproduce this issue in a vanilla source code I've enabled the OrchardCore.Lists module and injected IContentManager to the ListPartHandler.

```
InvalidOperationException: A circular dependency was detected for the service of type 'OrchardCore.ContentManagement.IContentManager'.
OrchardCore.Navigation.INavigationManager(OrchardCore.Navigation.NavigationManager) ->
System.Collections.Generic.IEnumerable<OrchardCore.Navigation.INavigationProvider> ->
OrchardCore.Navigation.INavigationProvider(OrchardCore.Contents.AdminMenu) ->
OrchardCore.ContentManagement.IContentManager(OrchardCore.ContentManagement.DefaultContentManager) ->
System.Collections.Generic.IEnumerable<OrchardCore.ContentManagement.Handlers.IContentHandler> ->
OrchardCore.ContentManagement.Handlers.IContentHandler(OrchardCore.ContentManagement.Drivers.Coordinators.ContentPartHandlerCoordinator) ->
System.Collections.Generic.IEnumerable<OrchardCore.ContentManagement.Handlers.IContentPartHandler> ->
OrchardCore.ContentManagement.Handlers.IContentPartHandler(OrchardCore.Lists.Drivers.ListPartHandler) ->
OrchardCore.ContentManagement.IContentManager
```

**Comment by jtkech** [comment]
Yes, the `DefaultContentManager` injects itself an `IEnumerable<IContentHandler>` handlers.

Hmm, because there are both scoped services, i think it's ok that you inject an `IServiceProvider` so that you can resolve it dynamically when you need it.

**Comment by sebastienros** [comment]
Obviously this can't work, the solution is to lazily resolve it. Inject a `IServiceProvider` then once you actually need the CM (in the Editor or Display) call `serviceProvider.Resolve<IContentManager>` .

**Comment by Piedone** [comment]
Why don't we inject handlers as Lazy into `DefaultContentManager` instead, as in O1? This way we need to solve this once instead of every module developer needing to know about it. We shouldn't push such burdens onto module developers if there are simple solutions like this.

**Comment by deanmarcussen** [comment]
This is actually a non issue now @Piedone as content part handlers are now registered against their direct type via an `IOptions` class and resolved by an `IContentPartHandlerResolver` as and when required.

**Comment by Piedone** [comment]
Didn't you see this recently @barthamark ?

**Comment by barthamark** [comment]
This is a very new feature which I've seen already but not really familiar with it yet.

**Comment by sebastienros** [comment]
You should watch @domonkosgabor 's videos ;)
