### ISSUE TITLE
_ViewImport.cshtml conflict

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3716]
Hi,

When referncing a OC Module package in a custom module, I have a conflict between the _ViewImport.cshtml defined in the custom module and the same file defined in the referenced OC Module.

> Error CS0436: The type 'Views__ViewImports' in 'D:\Dev\WEBCSCORE\Framework.Net\Framework.Net\src\Modules\Framework.App\obj\Debug\netstandard2.0\Razor\Views\_ViewImports.g.cshtml.cs' conflicts with the imported type 'Views__ViewImports' in 'OrchardCore.Settings.Views, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'D:\Dev\WEBCSCORE\Framework.Net\Framework.Net\src\Modules\Framework.App\obj\Debug\netstandard2.0\Razor\Views\_ViewImports.g.cshtml.cs'. (1, 1)

**Comment by jtkech** [comment]
Yes, you're right, i will see if it is possible to remove this warning but only for imported razor view types.
