### ISSUE TITLE
Admin menu Issus

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3723]
there are some problems in the admin menu.

1- at first i just created agency receipt, and i added the menu items for the admin menu. but they didn't show in the menu. then i added the blog receipt and my old menu and blog admin menu shown.

2-the "Content Types" node, doesn't work with new "Manage Content" url and it needs some query strings to works.

3-set access for admin menu still not solved.  #3628

**Comment by sebastienros** [comment]
> i added the menu items for the admin menu. but they didn't show in the menu

can you give repro steps?

> the "Content Types" node, doesn't work with new "Manage Content" url and it needs some query strings to works.

repro steps? I don't understand what you mean

**Comment by aghili371** [comment]
just please create new blog receipt and click on menus. the URL which set for content items is different than old structure .new url has 3 new query string field and these important for search in content items.

if i add content type node:
![Capture](https://user-images.githubusercontent.com/24512878/58979897-5c6ae480-87cf-11e9-98bb-9010cbc15580.JPG)

it set this url:
https://localhost:44386/Admin/Contents/ContentItems/Page

but the correct url is:
https://localhost:44386/Admin/Contents/ContentItems/Page?Options.OrderBy=Modified&Options.ContentsStatus=Latest&Options.SelectedContentType=Page
