### ISSUE TITLE
Reviewing some Task.WhenAll() usages.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#3726]
- If we agree that using a session instance concurrently (not only recursively) may cause problems (e.g on auto-flush), there are some `.WhenAll()` usages that we would need to replace. E.g on `BuildDisplayAsync()` which may use the session and non thread safe scoped drivers / services.

      Users = await Task.WhenAll(
          results.Select(async x => 
              new UserEntry { Shape = await _userDisplayManager.BuildDisplayAsync(...) })),

- Another example using `_roleManager.FindByNameAsync()` that may imply a `_session.Query`. Hmm, this one also uses a `ContinueWith()`, need to check if it is ok in this context.

      foreach (var roleName in allRoleNames)
      {
          var task = _roleManager.FindByNameAsync(...).ContinueWith(async roleTask =>
          ...
          tasks.Add(task);
      }

      await Task.WhenAll(tasks);

**But maybe no problem if we really know that** a connection has already been created, that we only do readings without pending updates ... But using `.WhenAll()` on `BuildDisplayAsync()` may be more risky, here beyond the `ISession`.

@sebastienros do we need to replace some or all of them? If so i can do a PR.

**Comment by sebastienros** [comment]
Ok to replace these for safety reasons

**Comment by jtkech** [comment]
Okay
