### ISSUE TITLE
YesSql Session returning no record 

### ISSUE THREAD

**Issue by brogits** [OrchardCMS/OrchardCore#3728]
Hello,

I wonder what is the issue with the following code. When using ContentItem the query returns correct record but not when using a class that is inheriting from contentitem. The goal for me is to be able to map the record data to my class

This doesn't return record:

```
var list = await _session.Query<MemberDataModel>()
                    .With<ContentItemIndex>(x => x.ContentType == TypeContants.MemberContentTypeName && x.Published)
                    .ListAsync();
```

But this does return the correct records:

```
var members = await _session.Query<ContentItem>()
                    .With<ContentItemIndex>(x => x.ContentType == TypeContants.MemberContentTypeName && x.Published)
                    .ListAsync();

```

**Comment by sebastienros** [comment]
Your query should return a `ContentItem` as you are joining a `ContentItemIndex`. Then from this object, you can extract a `MemberDataModel` if you have a property that contains it. But looking at the other issue you filed, you should not need to do any query. The display driver would be able to extract it automatically from a custom Part.

You should look at some Part examples we have in the Demo module or the other ones.
