### ISSUE TITLE
how to use routes.MapAreaRoute with three parameters?

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#3730]
![image](https://user-images.githubusercontent.com/4881282/58643250-7caf2500-8331-11e9-92b0-24167f9c751e.png)
![image](https://user-images.githubusercontent.com/4881282/58643510-fd6e2100-8331-11e9-8bf2-86245d4bf37c.png)
But the website has not changed，when i visiting this page

**Comment by Skrypt** [comment]
string? menuItemId on the controller.

**Comment by sebastienros** [comment]
Please describe how to reproduce the issue, it is not obvious what the problem is
