### ISSUE TITLE
Build fails with OpenId issue on Visual Studio for Mac.

### ISSUE THREAD

**Issue by kevlyons** [OrchardCMS/OrchardCore#3734]
Cloned the latest dev branch as of 5 hrs old. Latest commit d51903a.

<img width="1019" alt="OrchardCore clone version" src="https://user-images.githubusercontent.com/1740222/58684538-f55ac380-83bb-11e9-8ef1-463a1435391a.png">

OrchardCore clone version

I have VS for Mac version 8.0.9. See below for details.

Wait for all the packages to restore.
Make sure OrchardCore.Cms.Web is set as solution startup project.
Try and Run.

Get build failure with following output.
/Users/kevin/Projects/OrchardCMS/OrchardCore/src/OrchardCore.Cms.Web/CSC: Error CS0006: Metadata file '/Users/kevin/Projects/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.OpenId/bin/Debug/netcoreapp2.2/OrchardCore.OpenId.dll' could not be found (CS0006) (OrchardCore.Cms.Web)

It seems to be using the wrong directory. I can build the OrchardCore.OpenId project separately and it produces bin\Debug\netstandard2.0\OrchardCore.OpenId.dll.

I've checked some other modules but OpenId doesn't seem any different, and there are no problems with them in the build, the output shows them building successfully.

I've kicked off a Build of Release config to see if there is a difference. Same error!

Might be an issue with the new version of Visual Studio!

Thoughts, anyone.
Regards,
Kevin

=== Visual Studio Community 2019 for Mac ===

Version 8.0.9 (build 5)
Installation UUID: d2bae2bd-b8e8-4cdf-955f-266907885e25
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

Package version: 518010003
=== Mono Framework MDK ===

Runtime:
Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
2.2.4
2.2.3
2.1.9
2.1.8
2.1.7
2.1.2
2.1.1
2.0.5
2.0.0
1.1.1
1.0.4
1.0.0
1.0.0-rc2-3002702
SDK: /usr/local/share/dotnet/sdk/2.2.106/Sdks
SDK Versions:
2.2.106
2.2.105
2.1.505
2.1.504
2.1.503
2.1.302
2.1.301
2.1.4
2.0.0
1.0.3
1.0.0-preview2-003121
1.0.0-preview1-002702
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin.iOS ===

Version: 12.8.0.2 (Visual Studio Community)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

=== Xamarin Designer ===

Version: 4.17.4.420
Hash: 0a2420845
Branch: remotes/origin/d16-0
Build date: 2019-05-23 23:40:02 UTC

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Community)
Android SDK: /Users/kevin/Library/Developer/Xamarin/android-sdk-mac_x86
Supported Android versions:
4.4 (API level 19)
6.0 (API level 23)

SDK Tools Version:
SDK Platform Tools Version: 25.0.6
SDK Build Tools Version: 23.0.1

Build Information:
Mono: mono/mono@5ac37cc
Java.Interop: xamarin/java.interop@c987483
LibZipSharp: grendello/LibZipSharp@44de300
LibZip: nih-at/libzip@b95cf3f
MXE: xamarin/mxe@b9cbb53
ProGuard: xamarin/proguard@905836d
SQLite: xamarin/sqlite@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/kevin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-05-28 18:18:20 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800090005
Git revision: 72a44477dd706608c2300a568f71e5769f89f7ef
Build date: 2019-05-29 15:19:54+00
Build branch: release-8.0
Xamarin extensions: 3e94aa3836143b8f5a5b9151b61a80e2fd278d62

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
Thu Apr 25 23:16:27 PDT 2019
root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by Skrypt** [comment]
Have you tried with Visual Studio Code without using VS for Mac at all?

**Comment by Skrypt** [comment]
I have tried and I can repro on VS for Mac 2019. Though it builds perfectly with VS Code.

**Comment by deanmarcussen** [comment]
It's related to the multi-targeting in the OpenId project

`<TargetFrameworks>netstandard2.0;netcoreapp2.2</TargetFrameworks>`

I couldn't say if it used to work, but VS for Mac apparently doesn't have good support for building multiple targets, it sounds like it only builds the first target listed, refer https://developercommunity.visualstudio.com/content/problem/113044/net-standard-multiple-targets-compilation-issue.html

If you remove the second target from the OpenId project it will build with VS for Mac

`<TargetFrameworks>netstandard2.0</TargetFrameworks>`

But I couldn't say what implications that has...

In the article it does say that command line MSBuild should work, so maybe that's the better option here

**Comment by PinpointTownes** [comment]
> But I couldn't say what implications that has...

If you remove the .NET Core App target, the OpenID module will be unable to generate X.509 certificates, which a quite annoying limitation.

It really sounds like a bug the VS Mac team should fix, but interestingly, you'll no longer be impacted once we migrate to .NET Core 3.0, as the 2 TFMs will be replaced by a single `netcoreapp3.0` (the change is already included in @jtkech's migration PR)

**Comment by kevlyons** [comment]
Thx @deanmarcussen, changed the TargetFrameworks to only have netstandard2.0.
Didn't build successfully the first time, some obscure error on the OpenId project. So after building the OpenId project first then the whole solution it worked. I haven't tested OpenId specific functionality though, so there might still be problems. The only conditional PropertyGroup was for a netcoreapp2.2 target, so I don't think there should be any problems. 

Just a interesting note about the order, the netstandard2.0 was listed first but it didn't build that one, it built the last one. So I might just swap the order and see if it still builds.

Thx everyone.

**Comment by deanmarcussen** [comment]
@kevlyons Glad you got it working, but just to say, I wasn't recommending you remove the TargetFramework, I was merely confirming that the problem is with Visual Studio For Mac, not OrchardCore.

Recommend you build from terminal with MSBuild, or report issue again to Visual Studio for Mac, or consider VS Code

**Comment by PinpointTownes** [comment]
Looks like the situation will get better with VS Mac 8.2: https://twitter.com/lastexitcode/status/1135143251638398976
