### ISSUE TITLE
Casting to Part with Fields Fails when Indexing

### ISSUE THREAD

**Issue by jameshawkins** [OrchardCMS/OrchardCore#3736]
The behavior of `.As<Part>()` has changed since updating my project from `1.0.0-beta3-70866` to `1.0.0-beta3-71558`.

It seems that `contentItem.As<MyPart>();` is no longer working correctly for a part that contains fields such as
```csharp
public class MyPart
{
    public TextField MyField { get; set; }
}
```
It works fine in a normal view, but in a yessql IndexProvider `MyField` always contains the previous value when updating the field value through the admin interface for example.

The correct, updated value can still be retrieved by using `.Get`
```csharp
var myPart = contentItem.As<MyPart>();
var myField = myPart.Get<TextField>("MyField");
```
or dynamically
```csharp
var myField = contentItem.Content.MyField.Text.Value;
```

I also tested with the AutoroutePart and it is working fine. The issue appears to be limited to fields.

**Comment by sebastienros** [comment]
I have never tried that ... Would you have a more complete example, like how is your driver looking? And how is that different than just a `public string MyField`, in terms of code you don't have to write.

**Comment by jameshawkins** [comment]
Yeah, an example i have is with a content type called BlogPost with fields just added to the default part. Added a class for the default part that looks like this:
```csharp
public class BlogPost : ContentPart
{
    public MediaField BannerImage { get; set; }
    public MediaField ContentImage { get; set; }
    public TextField ContentImageAltText { get; set; }
    public TextField Byline { get; set; }
    public TextField Summary { get; set; }
    public MarkdownField BlogPostContent { get; set; }
    public TextField ImageCaption { get; set; }
    public BooleanField HighlightPost { get; set; }
    public TaxonomyField Category { get; set; }
}
```
And an index like this:
```csharp
public class BlogPostIndex : MapIndex
{
    public string ContentItemId { get; set; }
    public bool FeaturedPost { get; set; }
    public DateTime? CreatedUtc { get; set; }
    public bool Published { get; set; }
}

public class BlogPostIndexProvider : IndexProvider<ContentItem>
{
    public override void Describe(DescribeContext<ContentItem> context)
    {
        context.For<BlogPostIndex>()
            .Map(contentItem =>
            {
                var blogPost = contentItem.As<BlogPost>();
                if (blogPost != null && contentItem.Published)
                {
                    return new BlogPostIndex
                    {
                        ContentItemId = contentItem.ContentItemId,
                        FeaturedPost = blogPost.HighlightPost?.Value ?? false,
                        CreatedUtc = contentItem.CreatedUtc,
                        Published = contentItem.Published
                    };
                }

                return null;
            });
    }
}
```

**Comment by jameshawkins** [comment]
Main advantage is that we get the field editors out of the box.

**Comment by sebastienros** [comment]
That and also autocompletion in razor views. I can see it working very well with a decoupled scenario. Is that how you are using it?

**Comment by jameshawkins** [comment]
Yeah exactly what we're doing in this case :)

**Comment by jameshawkins** [comment]
which has also broken the live preview for this content type... the field values are always null now in the context of a live preview

**Comment by sebastienros** [comment]
> which has also broken the live preview for this content type

How did you get it working in decoupled in the first place?

**Comment by jameshawkins** [comment]
I guess we're not completely decoupled in the case of blog posts since we're rendering them via `Content-BlogPost.cshtml`... I was thinking of the blog post list page which is just an mvc controller/view.

**Comment by jameshawkins** [comment]
but in `Content-BlogPost.cshtml` we're using `contentItem.As<BlogPost>()` to get at the values and that's what stopped working for the preview

**Comment by sebastienros** [comment]
If you have a front-end theme, then it's not completely decoupled. But we know how we can still get it working.

And I am not forgetting about the reason for this issue, I'll take a look.

**Comment by jameshawkins** [comment]
Thanks Sebastien :)

**Comment by jameshawkins** [comment]
@sebastienros I did some further digging and opened a pr with a proposed solution. Let me know what you think.
