### ISSUE TITLE
trumbowyg.js default settings

### ISSUE THREAD

**Issue by jonvee** [OrchardCMS/OrchardCore#3737]
Currently the default Trumbowyg settings allows pasting Word text without removing formatting.
Also when trying to write html, all "div" tags are converted to "p" tags. 
It's my opinion Word text should be cleared of formatting by default to avoid extra markup and conflicts with theme styles.
`removeformatPasted: true,`
It's also my opinion the semantic setting should not be "true", but rather:
`semantic: {
            'b': 'strong',
            'i': 'em',
            's': 'del',
            'strike': 'del',
            'div': 'div' // Editor does nothing on div tags now
        }`
If these changes are acceptable I'll submit a PR, but if not, what is the easiest way to add these changes separately?

**Comment by agriffard** [comment]
Note: If you want check what could be done, I previously submitted a PR #2882 to update trumbowyg and allow to customize some settings but it is now outdated.

**Comment by agriffard** [comment]
Related to #4651
Latest version of Trumbowyg cleans the text during a paste with a plugin.
