### ISSUE TITLE
INavigationProvider but for Razor Page

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3739]
Does `INavigationProvider ` support Razor Pages admin? Right now if I implemented the admin using Razor Page, it will open the page but the left hand side Admin menu disappears. 

`Action` in this code is pretty much just support MVC Views.
```
 public Task BuildNavigationAsync(string name, NavigationBuilder builder)
        {
            if (!String.Equals(name, "admin", StringComparison.OrdinalIgnoreCase))
            {
                return Task.CompletedTask;
            }

            builder.Add(T["Configuration"], configuration => configuration
                .Add(T["Crucible"], "1", settings => settings
                        .Action("Index", "Admin", new { area = "Crucible.Module" })
                        .Permission(Permissions.ManageSettings)
                        .LocalNav()
                )
            );

            return Task.CompletedTask;
        }
```

**Comment by sebastienros** [comment]
You still face the issue when using the `[Admin]` attribute? If so we need to change the MVC filter to also accept Razor Pages.

**Comment by dodyg** [comment]
The Admin attribute doesn't work for Razor Pages. So right now there is no way to implement an admin functionality using Razor Pages AFAIK.

**Comment by jtkech** [comment]
Yes, i thought about it at some point, but i said to me that nobody will ask for it ;)

**Comment by dodyg** [comment]
Yeah it is much nicer to work with Razor Pages than MVC.

**Comment by ns8482e** [comment]
Try with calling AdminAttribute.Apply()  OnPageHandlerSelectionAsync

**Comment by ns8482e** [comment]
> You still face the issue when using the `[Admin]` attribute? If so we need to change the MVC filter to also accept Razor Pages.

[Admin] attribute won't work as its ActionFilterAttribute, RazorPages needs PageFilter
