### ISSUE TITLE
How to force users to log in? 

### ISSUE THREAD

**Issue by alexdresko** [OrchardCMS/OrchardCore#3740]
In hopes of forcing users to log in, I disabled "View all content" for the Anonymous role. 

![image](https://user-images.githubusercontent.com/333022/58750900-b5501b00-8465-11e9-92d2-605f515510e4.png)

However, instead of redirecting users to the login page, I get this error (not the 401 document type)

![image](https://user-images.githubusercontent.com/333022/58750878-7cb04180-8465-11e9-8138-ae7324166771.png)

If I try to go to `/admin`, I am redirected to the login page. So I'm basically trying to do the same thing for all pages.

![image](https://user-images.githubusercontent.com/333022/58750943-3effe880-8466-11e9-8263-115c82a5a71d.png)

Any clue what I'm doing wrong here?

**Comment by alexdresko** [comment]
Maybe a dupe of https://github.com/OrchardCMS/OrchardCore/issues/3209

Maybe also related to https://github.com/OrchardCMS/OrchardCore/issues/985

**Comment by sebastienros** [comment]
Right, looks like  #3209 to me
