### ISSUE TITLE
Bootstrap 4.3.1 upgrade issues

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3742]
I'll open a new issue on this, as it maybe related to https://github.com/OrchardCMS/OrchardCore/issues/3725 but I suspect @Skrypt and I are talking about slightly different issues.

The Bootstrap 4.3.1 upgrade has a few version conflicts.

BS 4.3.1 still uses popper 1.14.7 but we have upgraded to popper 1.15.0 

The `ResourceManifest` has the `bootstrap-bundle` depending on `popper` but `bootstrap-bundle` ships `popper` 1.14.7 in it, so probably `bootstrap-bundle` only needs to depend on `jQuery` and `bootstrap` needs to take a dependency on `popper`

Lastly `npm install` with npm version 6.9.0 gives errors such as this because versions in `package.json` of the Setup / Admin / Resources are different. They resolve (mostly) by removing the 'package.lock.json' from the modules, or by doing an npm install in the modules folder directly, thereby updating the `package-lock.json` 

![npm-errors](https://user-images.githubusercontent.com/13782679/58759523-813b2f80-8523-11e9-97c6-869f173e0653.PNG)

Should we update these `package-lock.json` files in the modules and commit them?
And resolve the other version conflicts and rebuild `TheAdmin.js` etc

Caveat: Not an npm expert, just reporting what I'm seeing 😄

**Comment by Skrypt** [comment]
Yes please copy over your comments to #3725 as this is a duplicate.

**Comment by deanmarcussen** [comment]
Closed as dup of #3725
