### ISSUE TITLE
How to retrieve the url of the website in a IBackgroundTask ?

### ISSUE THREAD

**Issue by Nathanlme** [OrchardCMS/OrchardCore#3747]
I would like to retrieve the url of the back office of my website in an IBackgroundTask. I check in siteSettings or context but impossible to retrieve him. In my context, the url is always "localhost" even when my website is in production.

**Comment by jtkech** [comment]
You can set a `BaseUrl` through the admin under `Configuration => Settings => General`. And retrieve it by resolving `ISiteService` and then using `(await _siteService.GetSiteSettingsAsync()).BaseUrl`.

**Comment by jtkech** [comment]
![BaseUrl](https://user-images.githubusercontent.com/8586360/58824019-6360ee00-863b-11e9-81c8-cfa935967fca.png)

**Comment by Nathanlme** [comment]
It works, thank you very much.
