### ISSUE TITLE
Shape rendering in Razor versus Liquid

### ISSUE THREAD

**Issue by tom-mckinney** [OrchardCMS/OrchardCore#3749]
Hey all, this afternoon I stumbled upon what I found to be a confusing difference between rendering shapes in Razor versus Liquid. I spent a while scratching my head as to why this worked:

```liquid
{{ Model.Content.MarkdownBodyPart | shape_render }}
```

but this didn't:

```cshtml
@await DisplayAsync(Model.Content.MarkdownBodyPart)
```

I eventually found issue #3516 that led me to discover that this was the syntax that I was looking for:

```cshtml
@await DisplayAsync(Model.Content.Named("MarkdownBodyPart"))
```

However, I'm still unclear as to why this distinction is made. If shapes are dynamics, is there a reason why a part needs to be accessed through the `Named` method in Razor but can be accessed like a property in Liquid? It is especially confusing since the [documentation](https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Themes/README/#content-projectcshtml) does not render the parts in the same way.

**Comment by sebastienros** [comment]
Technically a "part" cannot be rendered, just shapes. What happens is that in last example, you access the shape named `"MarkdownBodyPart"` from the `Content` zone, and render it. It works in Liquid because apparently we implemented the shape discovery by the 'dot' accessor to a named shape, but didn't do it in Razor (or most correctly in C#). We could definitely add this discovery, as the `Content` property is a dynamic object, but I think it would be confusing, too much magic. For liquid we decided to do it this way though.

**Comment by tom-mckinney** [comment]
Thank you for replying @sebastienros. I see what you're saying about how there could be too much magic with overriding the dot accessor in `IShape`. However, I do feel that there's quite a bit of magic rolled into Shapes already. Hopefully as OrchardCore nears RC we can update some of the [C# documentation for themes](https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Themes/README/#content-projectcshtml) so that these differences are more clear.

**Comment by sebastienros** [comment]
I'd rather improve the documentation in this case.

**Comment by ns8482e** [comment]
Looks like this issue has been taken care in #4553

**Comment by sebastienros** [comment]
You tricked me

**Comment by ns8482e** [comment]
I was searching for easy ones to work next few days in 1.0 list :)

**Comment by captmomo** [comment]
When I use the .Named method, on my content item, I get an exception that JObject has no Named method.

```
        public async Task<IActionResult> DisplayAsync(string jsonData)
        {
            var contentItem = await _contentManager.NewAsync("Foo");

            // Explicit syntax
            var testPart = contentItem.As<DataTablePart>();
            testPart.JsonData = jsonData;
            contentItem.Apply(testPart);


            return View(contentItem);
        }
```

```
@model dynamic
@inject OrchardCore.ContentManagement.Display.IContentItemDisplayManager ContentItemDisplayManager


<div class="columns is-centered">
    <div class="column is-half">
        <div class="box">
            <div class="content">
                @await DisplayAsync(Model.Content.Named(nameof(DataTablePart))


                @await DisplayAsync(Model.Content)

            </div>
        </div>
    </div>

</div>
```

What am I doing wrong?
