### ISSUE TITLE
Modules with Views are broken in Production

### ISSUE THREAD

**Issue by monoludic** [OrchardCMS/OrchardCore#3752]
Since the new build rule (#3651), all our modules with views use Razor SDK. It works well on a dev machine.
Although when I set ASPNETCORE_ENVIRONMENT = "Production", some views are not built correctly.
The script tags with at="Foot" are not processed.

Any ideas on what's happening ?

**Comment by jtkech** [comment]
In dev mode module views are compiled at runtime in the context of the application. In production we use the precompiled views which have been compiled in the context of their module (when building the module). So, there are the following requirements.

Check that each module using the razor sdk also references directly (not transitively) the `Microsoft.AspNetCore.Mvc` package, that modules using our custom script tag reference `OrchardCore.ResourceManagement`, and that their `_ViewImports.cshtml` import the related tag helpers `@addTagHelper *, OrchardCore.ResourceManagement`.

**Comment by monoludic** [comment]
Thanks, the `OrchardCore.ResourceManagement` package reference was missing in the .csproj.
