### ISSUE TITLE
Reload a module

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#3762]
How to reload (run migration) a core module, for example, the **OrchardCore.User** in the **Agency Theme.** It is necessary for run migrations.

From the **Configuration** => **Module** => **Enable/Disable** is failure (instance/app).

![image](https://user-images.githubusercontent.com/6829626/58937467-2c91f180-877b-11e9-8af9-5835240de83a.png)

**Log**:

[orchard-log-2019-06-05.log](https://github.com/OrchardCMS/OrchardCore/files/3255963/orchard-log-2019-06-05.log)

![image](https://user-images.githubusercontent.com/6829626/58939135-2aca2d00-877f-11e9-96f7-9f8d5f32fc69.png)

**Comment by Skrypt** [comment]
```C#
        public int UpdateFrom2()
        {
            SchemaBuilder.CreateReduceIndexTable(nameof(UserByMemberNameIndex), table => table
                .Column<string>("MemberName")
                .Column<int>("Count"));
            return 3;
        }
```

**Comment by AcellaEDU** [comment]
@Skrypt Thanks. Migration successful
