### ISSUE TITLE
Azure Blob Storage AppSettings Configurations

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#3766]
I've been trying to configure the Azure Media Storage module and from what I could see in the source code these are the app settings that I should define:

````
[
  {
    "name": "Modules__OrchardCore.DataProtection.Azure__ConnectionString",
    "value": "***"
  },
  {
    "name": "Modules__OrchardCore.DataProtection.Azure__ContainerName",
    "value": "***"
  },
  {
    "name": "Modules__OrchardCore.Media.Azure__ConnectionString",
    "value": ***"
  },
  {
    "name": "Modules__OrchardCore.Media.Azure__ContainerName",
    "value": "***"
  }
]
````

My issue here is that apparently azure (at least web apps on linux) can't read these keys. I have had this problem before when using the '.' character in the app settings keys. Is this the correct configuration? If so, is there any way I can add these entries programmatically?

**Edit:**
The error I'm getting is "Azure Media Storage is enabled but not active because some settings are missing or invalid. Check the error log for details, then correct the settings and restart the application.

````
2019-06-05T18:24:33.897312326Z [41m[1m[37mcrit[39m[22m[49m: OrchardCore.DataProtection.Azure.Startup[0]
2019-06-05T18:24:33.907626096Z       No connection string was supplied for OrchardCore.DataProtection.Azure. Ensure that an application setting containing a valid Azure Storage connection string is available at `Modules:OrchardCore.DataProtection.Azure:ConnectionString`.
2019-06-05T18:24:33.919774979Z [41m[30mfail[39m[22m[49m: OrchardCore.Media.Azure.Startup[0]
2019-06-05T18:24:33.919802479Z       Azure Media Storage is enabled but not active because ConnectionString is missing or empty in application configuration.
2019-06-05T18:24:33.941332026Z [41m[30mfail[39m[22m[49m: OrchardCore.Media.Azure.Startup[0]
2019-06-05T18:24:33.976649867Z       Azure Media Storage is enabled but not active because ContainerName is missing or empty in application configuration.
````

**Comment by carlwoodhouse** [comment]
think you're right that it's the periods, had similar problems in azure web apps on linux in another app.

**Comment by jtkech** [comment]
What i already saw in the docs (but they were talking about env variables) is that it is better to use a double underscore for section separator, this in place of a colon `:` so that it is compatible for all platforms.

So, e.g in the `OrchardCore.DataProtection.Azure` startup we have

    _configuration.GetValue<string>("OrchardCore.DataProtection.Azure:ConnectionString");

I think it is better to 1st use a `GetSection("OrchardCore.DataProtection.Azure")` **without using a** `:`, as we do in the `OC.Media` startup, but not in the `OrchardCore.Media.Azure` startup.

**Comment by carlwoodhouse** [comment]
Yes ':' is the section sep '{' - however if you try to load any keys with period '.' in thekey; in linux docker containers in azure they fail as the os's dont support env variables with periods in them.

Our configuration keys should be supported by everything, its the point of IConfiguration right ;p

We actually replaces all the periods in ours with colon's ;)

eg ..

```       services.Configure<IdentityBridgeOptions>(x => _configuration.GetSection("Modules:QueryCore:IdentityBridge").Bind(x));
```

which would have this configfile if using appsettings
```
 "Modules": {
    "QueryCore": {
      "IdentityBridge": {
        "IdentityServerApi": "somevalue",
        "IdentityServerAuthority": "somevalue"
      }
}
```
or this env variable
```

```
QueryCore__IdentityBridge__IdentityServerAuthority
QueryCore__IdentityBridge__IdentityServerApi
```

PS. docker for appservices just converts appsettings to env-variables.

**Comment by carlwoodhouse** [comment]
I'll provide a pr for this to remove periods from configuration keys if we want - but how do we wanna handle the fact it will break existing config files ?

/cc @sebastienros @jtkech

**Comment by jtkech** [comment]
Okay, need more thinkings but if you start something i will help.

- In place of `IConfiguration`, we now use `IShellConfiguration` for orchard configs that are intended to be under a main section named `OrchardCore`, we don't use anymore the `Modules` section, and through the code we don't have to specify this `OrchardCore` main section, it is done automatically.

- Note: We allow tenant specific configs if they are under a subsection whose name matches a tenant name. So here a tenant name including a `.` might be a problem.

- We have different config sources, e.g the root `appsettings.json` but also an optional under `App_Data`. We also have one under each tenant folder, and the `tenants.json`, but they are not intended to be updated manually but by some mutable sources, e.g on setup or through the admin UI.

- So in your scenario, could you try to put your configs in an **`App_Data/appsettings.json`** file, under an `OrchardCore` main section (not `Modules`) and in the "regular" way without additional subsections.

    If not in the root `appsettings`, normally **these configs will not be converted to env-variables by docker for appservices**. Then try `IShellConfiguration` to grab configs without specifying the `OrchadCore` section.

**Comment by LMSSonos** [comment]
@nuno-tiago-reis I'm trying to make the same as you did. I made following steps

1) added nuget: OrchardCore.Media.Azure and OrchardCore.DataProtection.Azure
2) appsettings.json (in root of solution) added
"OrchardCore": {
    "OrchardCore.DataProtection.Azure": {
      "ConnectionString": "xxx",
      "ContainerName": "dataprotection"
    },
    "OrchardCore.Media.Azure": {
      "ConnectionString": "xxxx",
      "ContainerName": "media",
      "BasePath": "/xx/",
      "PublicHostName": ""
    }
  }

The result is, that in my case it still creates the protectionkeys in the App_Data folder. Do I have to register the Modules?

**Comment by jtkech** [comment]
At least you have to enable the related modules through the admin.

For data protection the default one do somewhere

    options.XmlRepository = new FileSystemXmlRepository(directory, loggerFactory);

Then `OrchardCore.DataProtection.Azure` is intended to run after (startup `Order` of 10) and to do.

    options.XmlRepository = new AzureBlobXmlRepository(blobRefFactory);

After enabling `OC.DataProtection.Azure`, if a file system folder and xml file already exist, normally there are no longer used,  try to delete them.

**Comment by LMSSonos** [comment]
Thanks for your help. I wasn't aware that this is required to activate first in the admin. The reason is, if you deploy it as zip (new deployment method on azure), you won't be able to write tu App_Data, so OrchardCore will fail in that deployment. So I was hoping by adding these packages I could reconfigure Orchard to write everything to the blob storage.

**Comment by carlwoodhouse** [comment]
thanks for the comments @jtkech - the explanation is useful; i'll add to my todo list to take a crack if no one gets there first .. but a long way down, have quite a bit of graphql stuff to sort first ;)

**Comment by sfmskywalker** [comment]
> I'll provide a pr for this to remove periods from configuration keys if we want - but how do we wanna handle the fact it will break existing config files ?

I'm ran into this issue today and it seems to be a blocking issue for me - currently I cannot store connection string values for the following keys:

* `OrchardCore:OrchardCore.DataProtection.Azure:ConnectionString`
* `OrchardCore:OrchardCore.Media.Azure:ConnectionString`

Due to the fact that Linux OS's don't support `.` in environment variable names, Azure can't pass these keys as-is and replaces them with an underscore `_`.

I propose we get rid of the periods in the key names and replace them with a single underscore.
In order to not break existing installations, perhaps we can still keep the current code as-is as a fallback. For example:

```csharp
// First try new format:
var connectionString = _configuration.GetValue<string>("OrchardCore_DataProtection_Azure:ConnectionString");

if(connectionString == null)
{
   // Try old format:
  connectionString = _configuration.GetValue<string>("OrchardCore.DataProtection.Azure:ConnectionString");
}

... The rest.
```

I'll submit a PR with the above applied to both the DataProtection/Azure and Media/Azure features.

**Comment by sfmskywalker** [comment]
I created a [PR with the proposed fix](#5918).

**Comment by stevo-knievo** [comment]
Hi, 
I'm using the RC1 orchardproject/orchardcore-cms-linux docker image with Azure App Service. I'm trying to set the Azure Blob Storage appsettings via environment variables.

```
{
    "OrchardCore_Media_Azure": {
    "ConnectionString": "DefaultEndpointsProtocol=https;...", 
    "ContainerName": "foo",
    "CreateContainer": false
  }
}
```

I tried a couple of combinations. e.g `OrchardCore__Media__Azure__ConnectionString="DefaultEndpointsProtocol=https;..."`

Here my local docker-composer attempt:

```
    environment: 
      - OrchardCore__Media__Azure__ConnectionString="DefaultEndpointsProtocol=https;..."
      - OrchardCore__Media__Azure__ContainerName="foo"
      - OrchardCore__Media__Azure__CreateContainer=false
```

Unfortunately without any luck.

Thanks

**Comment by jtkech** [comment]
Through an env variable you still need the `OrchardCore` main section, so as i remember, by only replacing the section separator from `:` to a double underscore `__`, not the simple underscores of `OrchardCore_Media_Azure`

    OrchardCore__OrchardCore_Media_Azure__ConnectionString

**Comment by stevo-knievo** [comment]
@jtkech Thanks for your quick replay! I much appreciate it! 

I change it. http://localhost:8080 is returning a 500er now.

`docker-compose logs --tail=all -f ` isn't showing any errors. I need to get the logging working. 

```
version: "3"

services:
  cms:
    image: orchardproject/orchardcore-cms-linux
    ports:
      - "8080:80"
    volumes:
      - ./cmsdata:/app/App_Data
    environment: 
      - OrchardCore__OrchardCore_Media_Azure__ConnectionString="DefaultEndpointsProtocol=https;..."
      - OrchardCore__OrchardCore_Media_Azure__ContainerName="foo"
      - OrchardCore__OrchardCore_Media_Azure__CreateContainer=false
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/var/lib/mysql
```

**Comment by jtkech** [comment]
At least now it is another issue ;)

Yes, would need more logging info, do you have something under `App_Data/logs`?

**Comment by stevo-knievo** [comment]
I got it!! Thank you so much @jtkech!

I needed to remove the double quotation marks:

`OrchardCore__OrchardCore_Media_Azure__ConnectionString=DefaultEndpointsProtocol=https;...`

**Comment by jtkech** [comment]
Cool ;)

**Comment by stevo-knievo** [comment]
I wonder if we should document that and where?

**Comment by jtkech** [comment]
I found [this here](https://github.com/OrchardCMS/OrchardCore/tree/dev/src/docs/reference/core/Configuration)

    Orchard Core stores all Configuration data under the OrchardCore section in appsettings.json files:

    {
      "OrchardCore": {
          ... module configurations ...
      }
    }
