### ISSUE TITLE
customize dashboard page.

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3767]
it possible to customize admin dashboard?

i think it should be editable like a liquid page. to set some summarize info o short lines there. 
the important part is should be customizable for any roles separated.

how can i create new page or module to edit this default dashboard?

**Comment by agriffard** [comment]
Related to #2246

**Comment by sebastienros** [comment]
Closing as duplicate. Note that you can still create a module that will handle the /admin route and display whatever you want instead of the current one.
