### ISSUE TITLE
Getting Razor Precompile Issue 

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3771]
The 'Microsoft.NET.Sdk.Razor' SDK is required on Themes and Modules for Razor files to be precompiled

**Comment by deanmarcussen** [comment]
See https://github.com/OrchardCMS/OrchardCore/issues/3752 for details on how you can resolve this

**Comment by RajasekarPR** [comment]
I followed the process what suggested in #3752  . But again i am getting the same issue.

I have included Microsoft.Net.SDK.Razor in the project along with Microsoft.AspnetCore.Mvc. But issue not solved :(

**Comment by deanmarcussen** [comment]
Can you share your .csproj file? And are you working with NuGet packages or OC source?

**Comment by RajasekarPR** [comment]
@deanmarcussen Issue resoved now.
