### ISSUE TITLE
Localize JavaScript strings

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3772]
I'd notice that we are heavily using `data-` attributes to localize values using `IHtmlLocalizer` or `IViewLocalizer` then fetching those translated strings from within java script.

It would be nice if create sort of `JavaScriptLocalizationService` that uses java script interoperability to localize the java script strings without extra hidden tags or attributes

/cc @sebastienros

**Comment by sebastienros** [comment]
Can you give an example? I don't understand how it would work.

**Comment by hishamco** [comment]
Sure .. something similar to what I did here https://github.com/hishamco/hishambinateya.com/blob/master/Posts/integrate-javascript-logging-with-blazor.md but in a reverse way

**Comment by hishamco** [comment]
Exactly something like
```csharp
[JSInvokable]
public static bool CheckEmailAvailability(string email)
{
     // Checking email availability logic
    ...
    return isAvailable;
}
```

in https://github.com/hishamco/hishambinateya.com/blob/master/Posts/part2-validation-controls-using-blazor-custom-validation-controls.md

**Comment by hishamco** [comment]
Is it acceptable? I don't see any issue with using this approach

**Comment by sebastienros** [comment]
I still don't understand, I have used it in Blazor but don't understand how it would work in MVC, and why it would be better that generating a custom tag when necessary.

**Comment by sebastienros** [comment]
I checked with some colleagues, it's only for Blazor.

**Comment by hishamco** [comment]
> I have used it in Blazor but don't understand how it would work in MVC

It should be similar while the JavaScript Interoperability APIs becomes a part of AspNetCore Extensions

> why it would be better that generating a custom tag when necessary

1- Avoid creating hidden tag or `data-` attribute for each localized resource
2- Easy to control, while all the java script will call a single method to localize the strings
3- Cleanup views from unnecessary or additional stuff

**Comment by hishamco** [comment]
> I checked with some colleagues, it's only for Blazor.

After checking the docs the primary use case is for applications built with Mono WebAssembly 😞, but still wondering why it doesn't support this while we have server-side blazor?!!
