### ISSUE TITLE
permission issu in admin panel

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3775]
@matiasmolleja  these menus should not show, like https menu  #3628
![Capture](https://user-images.githubusercontent.com/24512878/59057106-f0a17e00-8899-11e9-852f-ea44a91b5379.JPG)

**Comment by sebastienros** [comment]
I assume the issue is about hiding Localization and Reverse Proxy menu items with custom permissions?

**Comment by aghili371** [comment]
yes, these kind of menus just for management and actually for admin role user, but these show for the user without any access.

**Comment by aghili371** [comment]
@sebastienros  please merge this pull.i think it's ready.

**Comment by sebastienros** [comment]
Someone please comment on this issue after tomorrow so we don't forget about it.

**Comment by aghili371** [comment]
the "ContentCulturePicker" need to set permission, too.
