### ISSUE TITLE
AutoroutePart is not generated automatically

### ISSUE THREAD

**Issue by juniordev19** [OrchardCMS/OrchardCore#3789]
The permalink field does not record anything when I create a content item from the admin panel.
Why is it not possible to make the permalink field required if I have to enter the url manually?

**Comment by Skrypt** [comment]
Because when you remove the url completely from the field it will regenerate the autoroute automatically.

**Comment by juniordev19** [comment]
What is necessary to make the URL automatically generated?

**Comment by Skrypt** [comment]
You need to have a valid liquid pattern in the content type autoroute part setting.

**Comment by juniordev19** [comment]
What if I use a razor instead of liquid?

**Comment by Skrypt** [comment]
I don't understand your issue. Could you give me some repro steps?

**Comment by juniordev19** [comment]
This solution worked in my case

{{ ContentItem.Content.TitlePart.Title | slugify }}
