### ISSUE TITLE
Custom Setting in theme

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3792]
When I try to add a custom setting in a theme referenced by an OC application using the latest nuget packages, this kind of exception occurs when I open the page to edit the settings:
`Exception: Shape type 'BootstrapSettings_Edit' not found`

The `BootstrapSettings.Edit.cshtml` file exists in the Views folder and the project references `OrchardCore.DisplayManagement`.

The theme contains these files:
AdminMenu.cs
BootstrapSettingsDisplayDriver.cs
BootstrapSettings.cs
BootstrapSettingsViewModel.cs
Permissions.cs
Startup.cs

The EditAsync method in the driver looks like this:
```
public override async Task<IDisplayResult> EditAsync(BootstrapSettings settings, BuildEditorContext context)
        {
            var user = _httpContextAccessor.HttpContext?.User;

            if (!await _authorizationService.AuthorizeAsync(user, Permissions.ManageBootstrapSettings))
            {
                return null;
            }

            return Initialize<BootstrapSettingsViewModel>("BootstrapSettings_Edit", model =>
                {
                    model.Background = settings.Background;
                }).Location("Content:3").OnGroup(GroupId);
        }
```

**Comment by jtkech** [comment]
Can you repro it locally (in dev mode and / or from the command line) or just in production?

Can you share the code of your custom theme? At least to begin with your theme project file.

**Comment by agriffard** [comment]
Same error when I copy the files in the source code in TheTheme.

https://github.com/agriffard/TheBootstrapTheme.OrchardCore

**Comment by jtkech** [comment]
Okay cool, i will try it soon

**Comment by jtkech** [comment]
Hmm, maybe i see what happens.

For a given theme, the shape table contains the shapes of all enabled modules (not themes) and the shapes of the current theme (not the other ones). So you can't use your custom settings shape through the admin because the current theme is `TheAdmin`, unless your theme is an admin theme (seems to not be the case) that is selected for the admin.

**Comment by sebastienros** [comment]
The admin shapes can only come from a module or an admin theme. Because there can only be one theme at a time.
