### ISSUE TITLE
turning off the module breaks the site

### ISSUE THREAD

**Issue by juniordev19** [OrchardCMS/OrchardCore#3793]
If you turn off one of the modules listed below, the site crashes.
        Settings 
	Admin
	Features 
	Recipes - turning it off breaks the site if the 'Scripting' is enabled 
	Navigation 
	Roles 
	Users 
	Resources 
If these modules are vital for the work of Orchard Core, why not make them non-switchable?

**Comment by agriffard** [comment]
Recipes cannot be disabled now.
