### ISSUE TITLE
Content handlers discussion.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#3795]
Yesterday, @Skrypt showed me an use case

- Where he wanted to update the `CreatedUtc` of a content item after publishing but it was not persisted.

            return await CreatePOST(id, returnUrl, stayOnSamePage, async contentItem =>
            {
                await _contentManager.PublishAsync(contentItem);

                contentItem.CreatedUtc -= TimeSpan.FromDays(365);

- Just retried and i had the same "issue", then by disabling the `OC.Workflows` module it was working.

- Then, in `DefaultContentManager.PublishAsync()`, moving the session save at the end make it working in all cases, even if i enable again the `OC.Workflows` module.

            // _session.Save(contentItem);

            await ReversedHandlers.InvokeAsync(handler => handler.PublishedAsync(...);
            _session.Save(contentItem);
        }

**Analysis**

- Through the `OrchardCore.Contents.Workflows.Handlers.ContentsHandler.PublishedAsync()` there is a session query. So, without another session save, any further updates is not persisted.

**Is it an issue? Maybe not**

- If a `PublishedAsync()` of a content handler is not intended to modify the content item (as some `PublishingAsync()` do), that's ok, this is the dev that needs to do a session save in its code.

- Otherwise, such a handler would not be able to update the content item if its `PublishedAsync()` is executed after the `WorkFlows` one. If it is an issue, we would need to move the `_session.Save` in `DefaultContentManager.PublishAsync()`, as mentioned above.

Note: Maybe other session save to move in `DefaultContentManager`.

**Comment by sebastienros** [comment]
I will take some time to understand the issue

**Comment by jtkech** [comment]
No problem, nothing urgent for me and there is a workaround.

If you update a contentItem after publishing or through a published event handler (that may run after another one doing a query), to be sure that the change will be persisted you need to do a session save.

**Comment by infofromca** [comment]
it related with FlushAsync();
all get, query perform it first.for ex
```
public async Task<IEnumerable<T>> ListImpl()
            {
                // Flush any pending changes before doing a query (auto-flush)
                await _query._session.FlushAsync();
```
`  public async Task<IEnumerable<T>> GetAsync<T>(int[] ids) where T : class
        {
            if (ids == null || !ids.Any())
            {
                return Enumerable.Empty<T>();
            }

            CheckDisposed();

            // Auto-flush
            await FlushAsync();`

so, I have another idea:
how about we have 2 version get, query, one with FlushAsync(), another without it. and give them good name.

**Comment by sebastienros** [comment]
Does the new FlushAsync support solve this issue?

**Comment by jtkech** [comment]
i will

**Comment by jtkech** [comment]
Same behavior

But maybe not an issue if we have to know to do a session save if we want to update an item after publishing. Maybe at least move the session save in `DefaultContentManager.PublishAsync()` at the end so that a `PublishedAsync` event handler would be able to update an item, even if another one do a query before.

**Comment by jtkech** [comment]
Hmm, as i remember with the autoflush, after a query a given content item is no more enlisted to be saved. But it's not a big issue, as said above there is always a workaround by doing another `_session.Save()`.

But it would have been easy in `DefaultContentManager` to do our session saves as late as possible, e.g after handlers that may do a query, I had did a PR for this a while ago.
