### ISSUE TITLE
LocalizedContentAuthorizationHandler little issue

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#3796]
@jptissot @sebastienros 

Not sure on how `AuthorizationHandler` are intended to cooperate, but while debugging a little issue related to the `LocalizedContentAuthorizationHandler`, here some findings.

- So, it runs after `ContentTypeAuthorizationHandler`, okay because `OC.ContentLocalization` depends on `OC.Contents`. Then, seems to be ok that the handlers registered by **`OC.Users`** run last. **But seems to be only due to an alphabetic order**. Maybe better to use a startup order or a manifest priority.

- Then, in `LocalizedContentAuthorizationHandler` there is.

            if (contentItem != null)
            {
                if (HasOwnership(context.User, contentItem))
                {
                    requirement.Permission = Permissions.EditOwnLocalizedContent;
                }
            }

    The 1st issue is that it acts even if the contentItem has no localization part, which can be easily fixed by adding `contentItem.Has<LocalizationPart>()`. But the other issue is that it also acts when rendering (not editing) on the front end.

    So i was tempted to do a `GetOwnerVariation()` as in `ContentTypeAuthorizationHandler`, this by checking if the permission is `EditOwnContent`. But at this stage it may be a dynamic permission as `EditOwn_Article`. Hmm, maybe here just check that it starts with `EditOwn`.

But not sure how these permissions need to be applied, e.g if an owner has `EditOwnLocalizedContent` but not `EditOwn_Article` and so on, so i let you decide and fix what would need to be fixed.

**Comment by sebastienros** [comment]
The order should be based on dependencies. In the order of registration.

**Comment by jptissot** [comment]
Should there even be a permission to create Localized Content ? Shouldn't the Content permissions be used  in this case ?

**Comment by jtkech** [comment]
Yes, I also asked myself the same question.

Then there would be still the order of the security handlers registered by `OC.Users`.

> Then, seems to be ok that the handlers registered by `OC.Users` run last. But seems to be only due to an alphabetic order. Maybe better to use a startup order or a manifest priority.

> The order should be based on dependencies. In the order of registration.

The problem is that `OC.Users` depends on nothing in its manifest file, i will take a look on this
