### ISSUE TITLE
Compile error: The 'Microsoft.NET.Sdk.Razor' SDK is required on Themes and Modules for Razor files to be precompiled.

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#3799]
I got this error message when compiling a theme project, the error comes from a recent build.

In the theme's csproj file, I have this included already:

    <PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.2.0" />

The only solution I found is to comment the followings in the OrchardCore.Module.Targets.targets file, but the error will come back again with a new build.

  <Target Name="EnsureRazorSdk" BeforeTargets="BeforeBuild">
    <Error
      Condition="'@(RazorGenerate)' != '' and '$(ResolvedRazorCompileToolset)' != 'RazorSdk'"
      Text="The 'Microsoft.NET.Sdk.Razor' SDK is required on Themes and Modules for Razor files to be precompiled." />
  </Target>

**Comment by orchardc** [comment]
`  <Target Name="EnsureRazorSdk" BeforeTargets="BeforeBuild">
    <Error
      Condition="'@(RazorGenerate)' != '' and '$(ResolvedRazorCompileToolset)' != 'RazorSdk'"
      Text="The 'Microsoft.NET.Sdk.Razor' SDK is required on Themes and Modules for Razor files to be precompiled." />
  </Target>`

**Comment by zl2fxy** [comment]
you try to add it at your theme's csproj file;
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" />
  </ItemGroup>

**Comment by orchardc** [comment]
Those are included in csproj file already:

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.2.0" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Templates" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Theme.Targets" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Users" Version="1.0.0-beta3-71653" />
  </ItemGroup>

**Comment by orchardc** [comment]
`  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.2.0" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Templates" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Theme.Targets" Version="1.0.0-beta3-71653" />
    <PackageReference Include="OrchardCore.Users" Version="1.0.0-beta3-71653" />
  </ItemGroup>`

**Comment by orchardc** [comment]
All above were added via NuGet.

**Comment by jtkech** [comment]
You don't need a package reference on `Microsoft.NET.Sdk.Razor`. You need to specify it as the project sdk through the 1st line of your project file.

    <Project Sdk="Microsoft.NET.Sdk.Razor">

And as @zhhbo said you also need a direct package reference on `Microsoft.AspNetCore.Mvc`.

**Comment by orchardc** [comment]
problem solved, thanks both! :)

**Comment by daerogami** [comment]
> You don't need a package reference on `Microsoft.NET.Sdk.Razor`. You need to specify it as the project sdk through the 1st line of your project file.
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Razor">
> ```

@jtkech Is this still a valid solution? The above solution doesn't seem consistent with the themes in the RC2 source.

**Comment by jtkech** [comment]
@daerogami 

Yes we are still using the razor sdk for our themes, unless those that are only using liquid file, no razor files

**Comment by grayjeremy** [comment]
I came across this error while trying to replicate some tutorials.  I was able to fix with the following .csproj file in my module.  Note the `<Project Sdk="Microsoft.NET.Sdk.Web">` as well as `<OutputType>Library</OutputType>`.  If you create a class library these aren't the defaults. 
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-rc2-13450" />    
  </ItemGroup>

</Project>
```

**Comment by JoshTango** [comment]
any clarity on this issue in 2022?
