### ISSUE TITLE
Link Asset (.docx, .pdf)

### ISSUE THREAD

**Issue by LatinaAtanasova** [OrchardCMS/OrchardCore#3800]
Hello,

I have a HtmlBodyPart in a contentItem. I try to add a link so that a file to be openned or downloaded. The file is uploaded in Assets/docs:

![image](https://user-images.githubusercontent.com/32022885/59418035-000c5400-8dd1-11e9-94f4-9c800a7fdd50.png)

And when i publish it, I have the following Link:

![image](https://user-images.githubusercontent.com/32022885/59418500-cc7df980-8dd1-11e9-8b58-aa6b65bb4c0f.png)

My razorPage is AboutUs. In code i used Url.Content method which makes url absolute and everything is fine. How should I write in the url address in "Insert Link" (first picture). I tried ~/media/docs/Application.docs but it's not working either. 

Target field is for opening the link in a new tag or there are other options, also? Sorry if there is similar issue, i could't find info about it.

**Comment by sebastienros** [comment]
Do we have an `href` liquid filter for these links? You could also try `/media/...` but in this case it might not work with multi-tenancy. The `~/` is not interpreted directly, it would require some liquid tag too.

**Comment by deanmarcussen** [comment]
Refer https://github.com/OrchardCMS/OrchardCore/issues/7186 I suspect

**Comment by jlcummings** [comment]
I started working on something that might address this (from the perspective that I understand it).  The desire isn't to render the linked item, but to download it for saving or to open a separate application for further viewing/processing.    The current link-to short-code mechanism isn't intended for sharing or creating download links.

The 'share' short-code would take a URL and create an anchor-link with a download attribute set, which helps the browser deliver the content with better user experience.  The link can include an explicit description or it can be inferred by the filename of the URL.  Additional attributes can be set for controlling link appearance via class and title adornments.  All other attributes are stripped via the sanitizer.  Consideration of multi-tenancy and CDN is minimally included.  Additional query params are not necessarily passed along, but it isn't explicitly prohibited.  It is rough and needs cleaned up, but I will put up a pull request probably tonight.

**Comment by sebastienros** [comment]
@jlcummings what about adding a custom shortcode template in the admin that would use the `asset_url` liquid filter:
https://docs.orchardcore.net/en/dev/docs/reference/modules/Media/#input

**Comment by Piedone** [comment]
The `[asset_url]` shortcode and/or the Media Picker covers this currently. If not, please reopen with more specifics.
