### ISSUE TITLE
Extending ShellSettings to include parent child relationship between tenants

### ISSUE THREAD

**Issue by efeker** [OrchardCMS/OrchardCore#3802]
I would like to be able to extend ShellSettings to include parent child relationship between tenants, so that child tenants can inherit parent tenant's settings such as selected theme, layout etc. Additionally, child tenants should be able to have their own child tenants and users belonging to parent tenant should be able to access child tenants. What would be the best way to implement this?

**Comment by sebastienros** [comment]
I assume we can merge multiple settings files, that would solve the requirement. But we need to add a way to define a link to the settings to merge. Though the storage might be dynamic too. We could also define this inheritance (like a base tenant) such that its settings would be loaded from the parent too.

But inheriting a theme, or a layout might not be solved this way, as you can always go to the Themes page and select a custom one which will be set in the local settings. Or maybe have an option to select "the theme of another tenant".

**Comment by Piedone** [comment]
Such tenant-tenant inheritance would be really complex, and as mentioned, involve a lot more than shell settings.

You can add custom shell settings keys, so you can also implement your own logic for whatever tenant relationship you prefer.
