### ISSUE TITLE
.svg are skipping browser cache

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#3807]
Haven't investigated yet but for some reason .svg images are being given 60 secs unlike other images: https://www.webpagetest.org/performance_optimization.php?test=190613_9H_b7d2930e3ddf58dc72fe07172c5f96ed&run=1#cache_static_content

**Comment by jtkech** [comment]
I think because IS doesn't support svg files, there is a [prototype here](https://github.com/SixLabors/Svg). So, the IS caching config values are not used for these files.

**Comment by dodyg** [comment]
Is there any workaround for this?

**Comment by deanmarcussen** [comment]
@dodyg What cache control setting are you seeing with svg's ?

Static files which aren't managed by ImageSharp should be picking up the default configuration of 
```
var cacheControl = shellConfiguration.GetValue("StaticFileOptions:CacheControl", "public, max-age=2592000, s-max-age=31557600");
```

from the `ServiceCollectionExtensions` defaults but it might be that we need to apply the same options to `UseStaticFiles` in the Media `UseStaticFiles` for media that isn't handled by ImageSharp, and is missing this configuration

**Comment by jtkech** [comment]
> but it might be that we need to apply the same options to UseStaticFiles in the Media UseStaticFiles

Exactly 👍

**Comment by sebastienros** [comment]
humm, shouldn't we have one middleware for static files (including modules) and one for media?
We have different settings for these

**Comment by sebastienros** [comment]
Or is this svg file in a theme for instance, in which case this makes sense, as it's not a "media"

**Comment by jtkech** [comment]
> humm, shouldn't we have one middleware for static files (including modules) and one for media

This is what we have but the one for media (for assets not recognized as images by IS)  doesn't use any cache config values. So maybe other options (maybe confusing) or re-use the same shellConfiguration `StaticFileOptions`. Or, from the media cache options `MaxBrowserCacheDays` and `MaxCacheDays`, compute some max ages to be used through a StaticFileOptions for these non images "media" assets, but more complex.

I would opt to re-use the same `StaticFileOptions` but yes non image files that are in fact images is a special case.

**Comment by deanmarcussen** [comment]
I think maybe we can just use the media cache setting `MaxBrowserCacheDays` to calculate the `CacheControl`.

Because the Media StaticFileMiddleware will serve anything from `/media` that is not handled by ImageSharp, so svg's, plus also jpg's and png's that are not resized.

We don't need to worry about `MaxCacheDays` that is just used to validate refreshing the `is-cache` 

I'll put a PR in, but after blob, as it would muddy the waters to try and to it on the blob PR now.

And update the docs at the same time, so it's clear where to set `/media` cache values, and how to configure static resources from modules.

**Comment by scleaver** [comment]
Sounds like a plan. I also have an issue with compression for svgs but I'll raise in another ticket I think.
