### ISSUE TITLE
Widgets deletion is not working

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3810]
@sebastienros  @nguerrera Added widgetlist part(Available Zone : Content ) in one of my content item.

Tried to delete the widget in one of my content item.But it just refreshed the page without deleting the widget.

Screenshot. 

![image](https://user-images.githubusercontent.com/39621436/59504792-5eb0fb00-8ec1-11e9-988d-f39ede923630.png)

Kindly do the needful as soon as possible.

**Comment by jtkech** [comment]
I confirm
