### ISSUE TITLE
Layer Rules not allowing for multiple Url "value"

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3812]
Given two urls in layer rule creation. 

But it works for only one page not for another page.

Is Layer rule not allow the multiple url values ?

Example I have created : url("~/", "~/homepage")
Kindly do the needful.

**Comment by carlwoodhouse** [comment]
`url("/homepage") | url("/")`

i think - layer rules possibly need better documentation

**Comment by RajasekarPR** [comment]
@carlwoodhouse Now it works. Thanks a lot 💯

**Comment by agriffard** [comment]
Layers need documentation #3111
