### ISSUE TITLE
Text Field with PredefinedList editor: Select multiple values

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3815]
Would it be possible to allow to select multiple values in a TextField with PredefinedList?

The editor would allow to choose an EditorOption like `Checkboxes`, `Listbox` or a multi select component

/cc @Skrypt

**Comment by Skrypt** [comment]
Yes we could add the Content Picker like control for multi-select.

**Comment by sebastienros** [comment]
Different field: Multi-Value text. because different physical type (string[])

**Comment by Skrypt** [comment]
Yes I meant for the UI.

**Comment by Skrypt** [comment]
Oh but you are right this should be a multi-value text field then.

**Comment by zl2fxy** [comment]
> Oh but you are right this should be a multi-value text field then. The physical type stored in the database is a string and not an array of strings.

if we do it as your idea,
We need to  perform the conversion to process this value，example，get value with GraphQl，or where field 
I suggest that we should create a special field.
