### ISSUE TITLE
Error in Upload video

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3818]
i got an error in upload video files. i should do extra settings to be possible to add video in media?

![Capture](https://user-images.githubusercontent.com/24512878/59552941-b3ba4300-8f8d-11e9-9a0f-1f18b266fd84.JPG)

**Comment by aghili371** [comment]
i tested with other extensions like .txt, .xml,.. it doesn't work too.

**Comment by sebastienros** [comment]
There is a list of extensions you can upload, in the settings. Also note that the default size limit is 30MB, how to changed it is documented.

**Comment by aghili371** [comment]
thanks, and sorry for asking this question without looking on documents.
