### ISSUE TITLE
set meta tag

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3824]
i want to set keywords and description metatag. 

for example, i want to set the content title in the description, but it doesn't render the {{  Model.ContentItem.DisplayText }} ..

`{% meta name:"description", content:"{{  Model.ContentItem.DisplayText }}" %}`

how can i set the value?

**Comment by jtkech** [comment]
You first need to be in a view whose model holds a content item, this is true most of the time. Then you need to have this line at the right place in your layout.cshtml / liquid.

    {% resources type: "Meta" %}
