### ISSUE TITLE
Restrict number of items creatable in bag part

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#3825]
I've already made a content type named slide which is added to other content type named Owl Slider as bag part. I've added Owl slider content type to landing page as bag part. The problem is, the admin can add multiple owl slider in landing page, which is not good for website. I think it will be great if there was an option in the bag part setting which restrict the number of items creatable in bag part.

**Comment by Piedone** [comment]
You can add arbitrary validation logic from a custom handler or driver. Please elaborate on how exactly you think this feature would work, and why it's better than a handler.

**Comment by hishamco** [comment]
> The problem is, the admin can add multiple owl slider in landing page, which is not good for website.

It's not necessary to show all the `BagPart` items on your page, you can use use pagination, or follow @Piedone suggestion

IMHO no action need here
