### ISSUE TITLE
Couldn't able to add html to Themelayout header section

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3826]
@sebastienros Able to add html info in themelayout footer section

Ex : Themelayout.Footer.Add(metainfos);

But not worked for ThemeLayout.Header.Add(metainfos)

Is there any syntax for adding in to the header

**Comment by Skrypt** [comment]
Have you declared your Layer zone in the site settings?

**Comment by RajasekarPR** [comment]
@Skrypt Issue solved by using zone name="header"
