### ISSUE TITLE
Media picker in custom settings

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3827]
Would it be possible to reuse some of the available features in the Media module to use them in a Custom Settings Edit view?

The goal is to allow the user to select (or upload) a media from a Settings page.

**Comment by Skrypt** [comment]
Looks like a media attached field

**Comment by deanmarcussen** [comment]
This would be really great to have

I tried some time ago to attach a MediaField to a Setting, but struggled to get the drivers to load it - had to start injecting fielddrivers to try and render the field etc, and gave up.

Would the media attached field be more reusable in this way?

**Comment by sebastienros** [comment]
Design:

- Create a `Custom Settings` part. This will allow us to reuse the part/fields editor to add custom fields to it.
- Render an instance of this Part in a custom Settings page: "Custom Settings"

Then we should be able to cast the `ISite` to a `CustomSettingsPart` and access its fields.

This should be what we did in O1.

**Comment by sebastienros** [comment]
An alternative would be to implement https://github.com/OrchardCMS/OrchardCore/issues/438 which would be more powerful.

**Comment by sebastienros** [comment]
Closing as duplicate
