### ISSUE TITLE
Problem in managing widgets which contain bag part

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#3828]
“Title” and “The layer the widget should be associated with” are two default properties for all widgets. When we try to add widget which contained bag part, those two properties must be defined for the widget once. If widget contains a bag part, those two properties must be filled only once too. But, when we try to edit that widget, those properties appear for all of the items in the bag part of the widget. I guess there’s some kind of problem with widget “saving” and “import data” method.

**Comment by ampadashi** [comment]
when i save the widget, it will add this part 
`"LayerMetadata":{"Position":1.0,"Zone":"FooterTop","Layer":"Always Visible","RenderTitle":false}`
to all of items of the bag part in the widget. There's some kind of problem with widget save method.

**Comment by Piedone** [comment]
Looks good in the latest code:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/d76f7410-0703-44a0-ac00-60e7afe86404)

Works on the frontend too:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/d8e0220b-afee-424c-8fa9-b9da505e452a)

Please reopen if still an issue.
