### ISSUE TITLE
WebMarkupMin Orchard Core Error

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3839]
@sebastienros @davidhayden Used WebmarkupMin nuget package in my web app. It works fine as expected. Because of webmarkup min got issue in Assets module ( UI admin )

Why it so ?

Kindly advice on this.

**Comment by sebastienros** [comment]
Can you explain how you use it and what issue you are experiencing?

**Comment by RajasekarPR** [comment]
@sebastienros Used the WebMarkUpMin.AspnetCore nuget in my solution as per the below url

https://andrewlock.net/html-minification-using-webmarkupmin-in-asp-net-core/

But it also minfies the html in admin theme too.

Because of minification admin theme, I am getting below issue.

![image](https://user-images.githubusercontent.com/39621436/59923236-8ddee380-9450-11e9-8d51-acf37bf9d7a8.png)


Try to upload image in assets, but it disappers. :(

**Comment by RajasekarPR** [comment]
@sebastienros Right now i have excluded the admin url pages in WebmarkUpMin aspnet core html options . Now it's working fine.

**Comment by sebastienros** [comment]
I assume you can filter the middleware to not be used in the admin. Or maybe it's an issue because on the ajax calls?

**Comment by RajasekarPR** [comment]
@sebastienros Yeah i have filtered the urls using middleware now. works fine now
