### ISSUE TITLE
Markdown module and Markdig extensions

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#3846]
As far I can see Markdown module internally uses [Markdig ](https://github.com/lunet-io/markdig) library. Markdig have some [extensions ](https://github.com/lunet-io/markdig/tree/master/src/Markdig/Extensions) build in but those extensions are not part of default processing [pipeline](https://github.com/lunet-io/markdig/blob/master/src/Markdig/MarkdownExtensions.cs#L74) that OrchardCore  .MarkDown utilize. Should we add an option to Markdown module to enable those extensions? If we don't want to assume specyfic implementation of markdown processor then probably such option should be explicit: `EnableMarkdigExtensions`? Or maybe Markdig extensions should be enabled by default?

**Comment by sebastienros** [comment]
We could add custom editors that are dedicated for Markdig, and provide some custom options. The default editor would still use Markdig but with default options.

**Comment by deanmarcussen** [comment]
This can be closed as the feature has been implement as `IOptions<MarkdownPipelineOptions>` registrations on the `MarkdownPipeline`

e.g
```
services
    .AddOrchardCms()
    .ConfigureServices(tenantServices =>
        tenantServices.ConfigureMarkdownPipeline((pipeline) => 
        { 
            pipeline.UseAdvancedExtensions();
        }));
```

Docs coming very shortly
