### ISSUE TITLE
Liquid date formating using current culture

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#3849]
I would like to render DateTime object and format it using Liquid filter `date` with current culture settings so I can get polish names for months. As I can see right now it doesn't work. Quick investigation suggest that `TemplateContext.CultureInfo` field is never set (so invariant culture is always applied).

**Comment by Skrypt** [comment]
Please look at this example which uses a Shape filter.
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheBlogTheme/Views/Content-BlogPost.Summary.liquid#L11

**Comment by arkadiuszwojcik** [comment]
@Skrypt thanks, it works. Should we close it or is it still valid issue? [Fluid](https://github.com/sebastienros/fluid) library have ability to pass `CultureInfo` into `TemplateContext`, moreover current culture is passed [here](https://github.com/OrchardCMS/OrchardCore/blob/d6308f490f476e0958ae455b609551cfece0643e/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/CultureLiquidTemplateEventHandler.cs#L30)  but this is just metainformation and not something `TemplateContext` use internaly.

**Comment by jtkech** [comment]
@arkadiuszwojcik let it open and if you could try #3851 where we update `TemplateContext.CultureInfo`.

**Comment by arkadiuszwojcik** [comment]
@jtkech I confirm. Using your PR I tried to use `{{ Model.ContentItem.CreatedUtc | local | date: "%d %B %Y" }}` and it works, I get polish localized names for months.
