### ISSUE TITLE
Inject custom view in WidgetsList

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3850]
@sebastienros  @davidhayden Can we inject the custom view in WidgetsList ?  If so , can anyone help how to do that via code ?

On a briefer note :

Created two html widgets(via widgetlist) in one of the contentitem. Have to inject my custom view in between the two html widgets in code(via driver) not through admin ui.

kindly advice on this.

**Comment by sebastienros** [comment]
Can you ask this question on the forum? https://gitter.im/OrchardCMS/OrchardCore
