### ISSUE TITLE
Incorrect content type assigned to uploaded PDF in Azure Media Storage

### ISSUE THREAD

**Issue by dbnetlink** [OrchardCMS/OrchardCore#3853]
When uploading a PDF into Orchard the content type is set to "application/octet-stream" on the Azure blob when it should be "application/pdf" (this is the content type that Azure itself picks when you upload a PDF directly)

**Comment by deanmarcussen** [comment]
I can repro that.

It looks like everything is getting uploaded as `application/octet-stream` - images as well
