### ISSUE TITLE
WidgetList UI Misalignment

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#3867]
Getting below html widget when adding in widget list part. The below UI is not at all good.
![image](https://user-images.githubusercontent.com/39621436/60392519-41fffe80-9b22-11e9-9e22-c684b3a2ccd5.png)

Kindly do the needful.

**Comment by sebastienros** [comment]
Can you me more specific about the repro steps? Thanks

**Comment by RajasekarPR** [comment]
@sebastienros 

1. Added WidgetListPart in one of my custom content type.
2. Edited WidgetListPart and added Content in 'Available Zones' textbox.
3. Created a new content item and added the html widget. ( In html widget added two property along with wyswig editor)
4. On expanding the widget, the controls are aligning in horizontal instead of showing one by one in vertical.

**Comment by hishamco** [comment]
@RajasekarPR how you added two properties in step 3?

**Comment by sebastienros** [comment]
What is `WidgetListPart`? I am not aware of anything like this in OC

**Comment by sebastienros** [comment]
Found it, `WidgetsListPart`
I don't remember the goals of this part. I will investigate (I probably wrote that thing for a reason)

**Comment by agriffard** [comment]
Well displayed for me.
