### ISSUE TITLE
set icon for menu in module

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3870]
how can i set icon in this code?

```
 builder.Add(T["item name"],  list => list
                   .Action("TermSection", "Admin", new { area = "Academy.OrchardCore" })
                   .LocalNav()
                    );
```

**Comment by hishamco** [comment]
You can use `AddClass()` for the menu item, have a look to pre-defined modules

**Comment by aghili371** [comment]
@hishamco where i can find the list of icons?

**Comment by hishamco** [comment]
You to remember the font-awesome classes 😉

**Comment by aghili371** [comment]
i tested font-awesome classes, but it still doesn't work.
        builder.Add(T["لیست ثبت نام مدرسه فوتبال"], T["لیست ثبت نام مدرسه فوتبال"], list => list
                    .Action("listRegisterInAcademy", "Admin", new { area = "Academy.OrchardCore" })
                    .LocalNav()
                    .AddClass("fa-facebook")
                    .Permission(Permissions.ManageAcademy)
                      );

**Comment by hishamco** [comment]
No need to add the `fa` prefix if I'm not wrong

**Comment by aghili371** [comment]
i have tested .AddClass("facebook") but it doesn't work

**Comment by hishamco** [comment]
Try `.AddClass("user")` and let me know if it shows up

**Comment by aghili371** [comment]
no, it doesn't work

**Comment by jtkech** [comment]
@aghili371 

    .AddClass("icon-class-fa")
    .AddClass("icon-class-fa-user")

**Comment by ropstah** [comment]
@jtkech this worked! 

Rather hard to find in documentation how this works or how to add your own icon set.
