### ISSUE TITLE
how to use webpack-dev-middleware in a custom module with the HMR (Hotmodule reloader) connected

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#3872]
how to use webpack-dev-middleware in a custom module with the HMR (Hotmodule reloader) connected
I use Microsoft.AspNetCore.SpaServices ,this run OK in a single MVC project,but error in orchardcore 
![image](https://user-images.githubusercontent.com/4881282/60556575-9bf80280-9d74-11e9-9c8b-16321ee5be0d.png)
![image](https://user-images.githubusercontent.com/4881282/60556582-a914f180-9d74-11e9-983c-d391464c0b11.png)
![image](https://user-images.githubusercontent.com/4881282/60513878-d75de700-9d0a-11e9-8292-e23a2a8c5110.png)

**Comment by sebastienros** [comment]
Can you try to ask this question on gitter? You may find some more help: https://gitter.im/OrchardCMS/OrchardCore
