### ISSUE TITLE
is there any liquid expression of  display-for?

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#3877]
for example: use .liquid file to express
`<h2><a display-for="@Model.TitlePart.ContentItem">@Model.Title</a></h2>`

**Comment by sebastienros** [comment]
Found it on this page: https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Liquid/

`{{ Model.ContentItem | display_url }}`
