### ISSUE TITLE
different  layout design

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3884]
i have menu in default page with background and in other pages without background.

default page:
![bg](https://user-images.githubusercontent.com/24512878/60753832-af0b0c80-9fd8-11e9-8d07-077c6f95bf2b.JPG)

other pages:
![no bg](https://user-images.githubusercontent.com/24512878/60753827-a7e3fe80-9fd8-11e9-8b8f-3eea05196a6d.JPG)
how i can manage this design in layout page? i'm using liquid design.

we have any variable or setting to get default page in layout.liquid?

**Comment by sebastienros** [comment]
You can use a custom alternate for the Layout of the home page. `Layout-Home.liquid` or something similar. Otherwise there is a liquid filter that you can set in a content item template to override the name of the layout.

**Comment by aghili371** [comment]
> Otherwise there is a liquid filter that you can set in a content item template to override the name of the layout.

could you please send this filter for me?

**Comment by jtkech** [comment]
This is the `LayoutTag` that you can use like this

    {% layout "Layout2" %}

**Comment by nambisan** [comment]
here are the full set of steps that I had to follow to make it work for my needs
- Custom theme with Razor cshtml Layout files
- Different pages requiring different Layout
- e.g. I have a Dashboard Page that requires a custom layout

steps:
1. Copy the default Layout.cshtml to and rename the copied file to Layout-Default.cshtml
![image](https://user-images.githubusercontent.com/918163/190841972-8d17748d-d66d-478e-b3a2-2d995f8bd35d.png)

2. Add the Liquid Part to Page ContentType under Content Definition > Content Types > Page
![image](https://user-images.githubusercontent.com/918163/190842050-53600952-e70e-4945-a5ea-bd5833c5c047.png)

3. Add the Liquid snippet {% layout "Layout__Dashboard" %} to the Dashboard Content Item 
![image](https://user-images.githubusercontent.com/918163/190842083-eb5cda44-f01f-4862-8d27-51b557a76332.png)
