### ISSUE TITLE
Routing for Feature Controller

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3887]
I have a module with a Controller decorated with the `[Admin]` attribute.

I tried to split the module into two `Features` but now I can no longer access the Controller (returns a 404)

```
<a asp-action="Index" 
           asp-controller="Home"
           asp-route-area="MyFeature>@T["Test"]</a>
```

no longer generates a good route, but adding
```
route.MapAreaRoute
                name: "Test",
                area: "MyFeature",
                template: "Home/Test",
                controller: "Home",
                action: "Index"
            );
```
and removing the `[Admin]` attribute, and adding the `[Feature("MyFeature")]` attribute to the Controller generates a good route on the front end, but still only gives 404 errors from it.

Removing the `Features` and making it a standalone module made it all work fine again.

I assume I'm missing something in the routing?

**Comment by jtkech** [comment]
The `Area` is always tied to the module (all modules are under an `Areas` virtual folder), then, to validate a controller only if a given feature is enabled, you have to decorate it with the feature attribute.

**Comment by Skrypt** [comment]
I think that if he adds the [admin] attribute it will always pass in the AdminFilter.cs class. Though I'm not sure why it returns a 404. I may be totally wrong but that's my first guess that something happens in AdminFilter.cs.

**Comment by jtkech** [comment]
I was meaning that it can't work if the area is set to a feature name that is not equal to the module name.

**Comment by deanmarcussen** [comment]
So after getting this weeks nuget packages this has started working fine, by just adding the `[Feature]` attribute to the `Controller` along with the `[Admin]` attribute - no need to add any `route.MapAreaRoute`

I suspect a rebuild after pulling the latest nuget may have sorted it.

**Comment by Skrypt** [comment]
So this controller is only accessible in the admin right?

**Comment by jtkech** [comment]
> We might maybe consider supporting nested areas

Yes would be good. Hmm, easy to affect an area per feature but this is when building a module that virtual paths (`Areas/TheModule/...`) are built (e.g for views), and at this point we are not aware of its features.

**Comment by Skrypt** [comment]
Not necessarly it's features but if someone adds an "Areas" folder in it's module we should probably parse it simply and create the Area.

**Comment by jtkech** [comment]
Okay, need more thinkings but i see what you mean ;)

**Comment by deanmarcussen** [comment]
Ok, so I try this again this morning, and for anyone else coming across this, what I find is

If you are using `Features` in a module the `Controller` has to be decorated with the `[Feature]` attribute for correct routes to be built - without the attribute decoration routes don't seem to get built.

The `[Admin]` attribute works fine, so long as the `[Feature]` attribute is added as well.

**Comment by jtkech** [comment]
Yes, when at least one feature attribute is used, the module attribute itself doesn't define anymore a feature. Then the convention is to set the 1st feature id to the module assembly name, this is not mandatory but it allows to not decorate all controllers, those that are not decorated being tied to this 1st feature (considered as the main feature of the module).
