### ISSUE TITLE
Without localization module Admin Modified Dates are incorrect

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3889]
The localization module isn't enabled by default by most (all?) of the recipes which seems to cause the `TimeSpan` shapes to always return the singular, and never the plural version of a TimeSpan.

With localization off (the default) modifed date in admin is 1 week
![localization-off](https://user-images.githubusercontent.com/13782679/60823712-14f5c080-a1a0-11e9-8133-509ac9a9723a.PNG)

When turned on the correct modified date of 7 weeks is shown
![localization-on](https://user-images.githubusercontent.com/13782679/60823755-2dfe7180-a1a0-11e9-9c16-3135cb4b28d4.PNG)

Is there any reason we shouldn't enable the localization module by default in the standard recipes?

**Comment by Skrypt** [comment]
Good point. I think thought that we still need to support the use cases where the Localization module is disabled even if we would enable it by default. I need to look by @jtkech will probably do it before me 😉

**Comment by sebastienros** [comment]
Agreed, it should work without this module. Maybe some wrong default that triggers a bug.

**Comment by hishamco** [comment]
This happen because `NullStringLocalizer` doesn't support pluralization, I will send a PR for this soon ..
