### ISSUE TITLE
Document IShellConfiguration

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3899]
@jtkech has given a helpful description of `IShellConfiguration` and the options for using various `appsettings.json` in https://github.com/OrchardCMS/OrchardCore/issues/3766

I would like to document that, with further details, (being aware some details may change due to https://github.com/OrchardCMS/OrchardCore/issues/3766) in one of the `readme.md` files

Any suggestions on where it should go?

A guide, or one of the modules?

**Comment by jtkech** [comment]
I don't see any non core module for a more generic doc on `IShellConfiguration`.

So, maybe a readme under `src\OrchardCore\OrchardCore\Environment\Shell` that can be updated in the future with more advanced infos e.g on how mutable sources work and can be overridden.

But anyway starting with a guide looks good.
