### ISSUE TITLE
Use custom ASP.NET Core Identity implementation

### ISSUE THREAD

**Issue by neolution-ch** [OrchardCMS/OrchardCore#3900]
More of a question than an issue:

We're trying to add a custom ASP.NET Core Identity implementation to an OrchardCore CMS (not SaaS) site and are experiencing all sorts of problems. It should be used to authenticate requests to Razor Pages that are in the same project next to the CMS pages. But since the user database is from an external source we can't manage the users in Orchard.

Is it even possible to add another Identity implementation, since OC already uses an implementation internally?

**Comment by PinpointTownes** [comment]
@neolution-ch I assume you mean "custom stores" when you say "custom ASP.NET Core Identity implementation", right?

If so, you'll likely have to roll your own Users module, as the default one relies on the YesSql stores/models from `OrchardCore.Users.Core`.

I'm pretty sure we mentioned decoupling the Users module from YesSql - similarly to what we did in the OpenID module - but I'm not aware of any progress. I'll try to find the corresponding ticket 😄

**Comment by PinpointTownes** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1401

**Comment by neolution-ch** [comment]
@PinpointTownes yes this it 😉 What would you recommend as a workaround if we want to implement our scenario today? A custom authentication middleware?

**Comment by PinpointTownes** [comment]
A custom Users module based on the built-in one would work.
Or you could consider contributing and making it stores-agnostic so you wouldn't have to maintain your own one 😄

**Comment by neolution-ch** [comment]
We ended up using the default Authentication middleware but with a separate AuthenticationScheme. That was enough for our needs 👍

**Comment by bakintunde** [comment]
Hi @neolution-ch , could you share some more details on what you did?
How do you keep users for razor pages logically separate from admin users?
Also where did you have to plugin your code for the separate authenticationscheme?
Thanks.

**Comment by neolution-ch** [comment]
> Hi @neolution-ch , could you share some more details on what you did?
> How do you keep users for razor pages logically separate from admin users?
> Also where did you have to plugin your code for the separate authenticationscheme?
> Thanks.

Nothing fancy or special 🤔 [this article](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x) pretty much discusses all parts involved.

We just added a second cookie authentication with the `AddCookie()` extension which we use with the overload to define a custom auth scheme string. To use it, we added the `AuthorizeAttribute` with the `AuthenticationSchemes` property set in the Razor pages that we want to have separate.

**Comment by chadboettcher** [comment]
> > Hi @neolution-ch , could you share some more details on what you did?
> > How do you keep users for razor pages logically separate from admin users?
> > Also where did you have to plugin your code for the separate authenticationscheme?
> > Thanks.
> 
> Nothing fancy or special 🤔 [this article](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x) pretty much discusses all parts involved.
> 
> We just added a second cookie authentication with the `AddCookie()` extension which we use with the overload to define a custom auth scheme string. To use it, we added the `AuthorizeAttribute` with the `AuthenticationSchemes` property set in the Razor pages that we want to have separate.

Hi @neolution-ch,

Any chance you could post the code or link to a sample repo? I think this is exactly what I need.

Thanks so much.
