### ISSUE TITLE
Resources Integrity hash is html encoded

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3901]
In latest dev when I publish on Azure I get my integrity checks to fail because those hash gets html encoded.

Example that's for bootstrap-bundle asset : 

```
sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM
sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM&#x2B;B07jRM
```

(+ is html encoded to `&#x2B;`)

**Comment by jtkech** [comment]
Is it since a recent commit?

**Comment by jtkech** [comment]
i can repro under the admin, right now it's the same if revert back the commits until 8 days ago.

**Comment by Skrypt** [comment]
I think it comes from LiquidViewTemplate.cs but I could be wrong.

**Comment by Skrypt** [comment]
Hmm, it comes from the fact that now we do

```
await template.RenderAsync(options, services, page.Output, HtmlEncoder.Default, context);
```

This means that a Liquid template will always be Html Encoded.  We need to find a way to specify that we want to exclude html encoding from Fluid for things that comes from the ResourceManagement.

**Comment by jtkech** [comment]
So, this is the mvc `TagBuilder` (used in `ResourceDefinition`) that encodes its attributes on its `IHtmlContent.WriteTo()`. Maybe this is not an issue, i think that the browser html decode it before using it.

If in the in the `ResourceManifest` i removed the `+` from the `SetCdnIntegrity`, i get a `Failed to find a valid digest in the 'integrity' attribute for resource ... with computed SHA-256 integrity`. Then, if i re-use the `+`, even it is html encoded in the html source, i have no error.

**Comment by Skrypt** [comment]
I had errors on Azure where using the Html encoded hash was returning the same `Failed to find a valid digest in the 'integrity' attribute for resource ... with computed SHA-256 integrity.` error and thus was preventing me from downloading it.

**Comment by jtkech** [comment]
Ah okay.

But on localhost i have the issue if i remove the `+`.

How did you fix it on your side?

Hmm, i will try to do a tag builder wrapper that doesn't encode the integrity attribute.

**Comment by Skrypt** [comment]
I removed the integrity check hash on the ResourceManager for now.

**Comment by jtkech** [comment]
Okay, i found a fix, i will do a PR

**Comment by Skrypt** [comment]
II'm not sure what has been done to fix the issue as the PR that was meant for fixing it is closed. Though, I created a docker image to test latest dev and I can't repro.

**Comment by deanmarcussen** [comment]
@Skrypt the issue still exists. BUT the browsers I try this with (Chrome and Safari) don't seem to care, as they have no complaints about the integrity of the script

![scripts-hash](https://user-images.githubusercontent.com/13782679/72709683-573f8780-3b5d-11ea-9272-708b74d98d57.PNG)

**Comment by Skrypt** [comment]
Can you confirm that it is with latest dev? I don't understand what makes this happen. I'm trying to repro and I can't. Maybe I need to enable the localization module.

**Comment by deanmarcussen** [comment]
So if I `inspect` your website with the chrome devtools the jquery hash reads correctly.
e.g
```
<script crossorigin="anonymous" integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh" src="https://code.jquery.com/jquery-3.4.1.min.js" type="text/javascript"></script>
```
If I viewsource then it is encoded eg
```
<script crossorigin="anonymous" integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy&#x2B;L2Z&#x2B;SBxGYnUkunIxVxAv/UtMOhba/xskxh" src="https://code.jquery.com/jquery-3.4.1.min.js" type="text/javascript"></script>
```

I guess my point is that the browser (Chrome at least + Safari) seems to handle the encoded hash ok.

So maybe it is not an issue we need to fix?

Unless we can find a browser that will give the error?

**Comment by Skrypt** [comment]
It used to give the error and restrict the usage of these assets on Azure. It's probably a server config or something that I don't know of yet. Will try to find more information on that.

**Comment by deanmarcussen** [comment]
ok, it could have been that we just had a bad integrity hash back then (we did have a few once).

The site I tried it on this morning is running latest dev on azure

**Comment by Skrypt** [comment]
I'm closing this one as I can't repro the warning issue in any recent browser. Seems like it now works even if the hash is html encoded.
