### ISSUE TITLE
CustomSettings ContentPart not easily available via ISite.As<MySettings>();

### ISSUE THREAD

**Issue by johnrom** [OrchardCMS/OrchardCore#3904]
My description from Gitter:

> I went down the rabbit hole of CustomSettings, which ended up being pretty confusing without clear documentation, but in the end work great. Initially, I thought you could simply do siteSettings.As<MyCustomSettingPostType> where MyCustomSettingPostType : ContentPart and services.AddSingleton(ContentPart, MyCustomSettingPostType).
I hit my head numerous times because it actually instantiates a default version of that content part with fields and everything when you do this, but this is not possible. Instead, there is a CustomSettingsService which is hard-coded into the OrchardCore.CustomSettings module
> 
> The CustomSettingsService isn't exposed via an interface / abstractions, so you have to either replicate what it does or add a reference. What it does is instantiate a ContentItem from the Properties of the ISite directly, instead of using As(). Additionally, it doesn't actually take a Type, so you have to pass the name of your type. I wrote a wrapper for my project which will pass typeof(TSettings).Name, but I think it'd be nice to have OrchardCore.CustomSettings.Abstractions with an ICustomSettingsService.GetSettingsAsync<MyCustomSettingPostType>() or its own IOrchardHelper extension. Do you think that would be helpful for other folks?

Easier solution from @jtkech :

```c#
using OrchardCore.Entities;
// ...
var siteSettings = await _siteService.GetSiteSettingsAsync();
var settings1 = siteSettings.As<ContentItem>("Settings1");
var test = settings1.As<SomePart>();
// ...
```

I think this is kind of a weird approach, so I asked if a `GetCustomSettingsAsync()` method would be helpful. @Skrypt gave a 👍 and here we are.

**Comment by johnrom** [comment]
Since there is more functionality via Custom Settings than a helper can provide, I've updated the documentation instead.

**Comment by Skrypt** [comment]
Alright, I thought too that a helper would help but looks like not. 😉
