### ISSUE TITLE
Use Liquid to list all pages title,  order by published date?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#3916]
How to use liquid page to list all Pages(Content Type) title, order by published date?

I'm thinking something like below, but it doesn't work?

![image](https://user-images.githubusercontent.com/16193516/61112441-bd976f00-a483-11e9-8d56-f511a14bf86b.png)

**Comment by orchardc** [comment]
Page is just a simple content type as defined below:

![image](https://user-images.githubusercontent.com/16193516/61112549-051dfb00-a484-11e9-8a27-b690118d3c81.png)

**Comment by agriffard** [comment]
Create a SQL query that returns the content items where the type is `Page`.
Use the `query `Liquid filter witht the name of the query to get the results.

https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Queries/#liquid-templates

**Comment by orchardc** [comment]
Thanks @agriffard ,  I'm good on sql but but no clue which box to fill in? 
It's very helpful if you could provide an example.

![image](https://user-images.githubusercontent.com/16193516/61115051-8330d080-a489-11e9-99d8-b8c5eb1f8b77.png)

**Comment by agriffard** [comment]
cf https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Queries/#examples

Here is an example of a query that returns all published Blog Posts:

```
    select DocumentId
    from ContentItemIndex 
    where Published = true and ContentType = 'BlogPost'
```
By selecting the "Return documents" options, the content items associated with the resulting DocumentId values are loaded.

**Comment by orchardc** [comment]
Get it, thanks mate!
