### ISSUE TITLE
Create a liquid page in Visual studio, then use it on the portal?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#3923]
I know you can create a liquid page in the Admin panel as shown below; however, is there a way to create same liquid page using visual studio then directly used on the portal? i.e. http://localhost:1234/myLiquidPage

![image](https://user-images.githubusercontent.com/16193516/61170245-20f5cf80-a55e-11e9-96cc-3d83038692db.png)

**Comment by Skrypt** [comment]
Yes, please refer to documentation and Theme examples.

**Comment by orchardc** [comment]
Thanks Skrypt, can it be specific please? 

I look at both agency and blog theme samples, but still can't find out exactly how? It would be great if you could provide more hints?

**Comment by Skrypt** [comment]
https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Templates/README/#liquid

See this page for understanding how the templates needs to be named.

**Comment by orchardc** [comment]
Hi @Skrypt , I think my question is, say: for a custom MVC theme, I can create a controller and a view in visual studio, i.e. Views/Account/Index.cshtml, then the Index.cshtml can be directly accessed after active the custom theme. User can access my view by going to /account/index

But when adding a Liquid page in visual studio, say: Index.liquid , how to let users access this page directly?? This is the confused area I have.

**Comment by jtkech** [comment]
So for testing in `TheBlogTheme` i created this controller.

    using Microsoft.AspNetCore.Mvc;

    namespace TheBlogTheme.Controllers
    {
        public class DemoController : Controller
        {
            public IActionResult Index()
            {
                return View();
            }
        }
    }

Then, you can put an `Index.cshtml` or an `Index.liquid` as i did under `Views/Demo`.

At this point the route is `https://localhost:44300/TheBlogTheme/demo/index`, just tried it works.

Then, you can define a simpler route by using `routes.MapAreaRoute()` in your module / theme startup, see in the source code of our modules.

Or you can just decorate your controller like this.

    [Route("Demo/Index")]
    public class DemoController : Controller

**Comment by orchardc** [comment]
This is amazing, thanks @jtkech ! :)
