### ISSUE TITLE
Theme Template cache busting

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3924]
We should update also update the theme templates to use `asp-append-version`

**Comment by deanmarcussen** [comment]
Should we update the theme templates (and the media picker for the html and markdown editor) to use the liquid `append_version` filter by default, or should we as per https://github.com/OrchardCMS/OrchardCore/issues/3912
add a `OrchardCore.Media` `appsettings.json`  to control cache busting via a default setting?

**Comment by Piedone** [comment]
It seems this is already happening. E.g with TheBlogTheme:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/5611b33e-dbdd-4018-9196-f119963ac264)

TheTheme:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/1a1e1ff0-bb17-4044-bf85-34583b1efa69)

This is despite no explicit append version config BTW. I checked and that being on is not the default, but still, it works for some reason...

Anything else to do here?
