### ISSUE TITLE
Media Thumbnails Cache Busting

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3925]
We should also update the media library to support cache busting when it delivers the thumbnails

**Comment by agriffard** [comment]
Is the cache assets implemented @deanmarcussen ?

**Comment by deanmarcussen** [comment]
no the pr never got merged to use this in the admin, so I closed the pr

**Comment by Piedone** [comment]
Fixed in https://github.com/OrchardCMS/OrchardCore/pull/15276.
