### ISSUE TITLE
Style tag helper dependencies

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3926]
Just came across in the AdminMenus `List.cshtml`

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.AdminMenu/Views/Menu/List.cshtml

```
<style asp-src="~/OrchardCore.AdminMenu/Styles/admin-menu.min.css" depends-on="admin"></style>
<script asp-src="~/OrchardCore.AdminMenu/Scripts/admin-menu.min.js" depends-on="admin"></script>
```

The Style Tag Helper uses `dependencies`, whereas the Script Tag Helper uses `depends-on` to set css dependencies, so it needs to needs to be
```
<style asp-src="~/OrchardCore.AdminMenu/Styles/admin-menu.min.css" dependencies="admin"></style>
<script asp-src="~/OrchardCore.AdminMenu/Scripts/admin-menu.min.js" depends-on="admin"></script>
```

Rather than just fixing that in the admin menus should we update the Style Tag Helper to also use `depends-on` for better consistency?

Also same for the `Edit.cshtml`

**Comment by jtkech** [comment]
Yes would be better.

There are 6 other places to update, do a find of `depends-on` on all `*.cshtml`.

I also did a find of `depends_on` on all `*.liquid` but with no result.
