### ISSUE TITLE
Remove is-cache folder from publish

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#3929]
Currently `dotnet publish` will include all the files from the `is-cache` folder.

We should probably exclude those by default and just allow it to publish the `wwwroot` folder

I think it's probably something like

```
<ItemGroup>
    <Content Update="wwwroot\is-cache\**\*.*" CopyToPublishDirectory="Never" />
  </ItemGroup>
```

Maybe not necessary if we go with https://github.com/OrchardCMS/OrchardCore/pull/3517 as that moves all the caching to the tenants folder

**Comment by deanmarcussen** [comment]
@jtkech I think you have added this to the default item excludes? If so we could close

**Comment by jtkech** [comment]
You're right
