### ISSUE TITLE
ContentCulturePicker redirect: Localized content not found

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3936]
I tried the ContentCulturePicker:
- Enable the Content localization module.
- Added fr-FR and En culture.
- Set fr-FR as default culture.
- Define Content Type `Article` with Title, Autoroute, Localization and Flow parts.
- Create article with `fr-FR` culture and title ArticleFR.
- Localize it into `En` culture with title ArticleEn.
- Add the fr .po files in App-Data\Localization.
- Add this in TheTheme\Views\Layout.cshtml:

`                <shape type="ContentCulturePicker" />`

When I am on the `articlefr` url and click on the content culture picker, the url is redirected to:
https://localhost:44300/OrchardCore.ContentLocalization/ContentculturePicker/RedirectToLocalizedContent?targetculture=en&contentItemUrl=%2FArticleFr
and the message `La page n'a pu être trouvée.` is displayed.

What am I missing to make it work?

**Comment by jptissot** [comment]
I saw this issue when I did not have the feature enabled in the modules or if you are on a page that has no translation. 
This #3894 pr adds options to select the default redirect and sets the localization cookie.

**Comment by jptissot** [comment]
From the url you posted, it looks like the ContentCulturePicker feature is not enabled since you should get a smaller url (defined in Startup)

**Comment by agriffard** [comment]
OK, thank you. 
Indeed, the feature 'Content Culture Picker' was not enable.
It was not obvious for me that it was a separate feature.
