### ISSUE TITLE
Documentation: How to generate pot files for your modules

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#3938]
As mentionned https://github.com/OrchardCMS/OrchardCore/issues/3508#issuecomment-511777660 

> Yes, exactly:
dotnet tool install --global PoExtractor.OrchardCore
Then
extractpo-oc C:\Path\OrchardCore C:\temp\OrchardCore --liquid

**Comment by agriffard** [comment]
We could add it on the Localization doc page:
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Localization/
