### ISSUE TITLE
Brackets displays wrongly for right to left display style

### ISSUE THREAD

**Issue by domonkosgabor** [OrchardCMS/OrchardCore#3940]
The following HTML code:
```
<html dir="rtl">
<p>hello (world)</p>
</html>
```
renders the page in the way:
`(hello (world`
However if I add the LRM character after the last bracket (HTML entity: `&#x200E;`) the brackets display well.

Are there any solutions to this issue? I think it's not a valid scenario to add this content after every text, when the dir of the html is rtl.

**Comment by sebastienros** [comment]
My feeling is that in a truly rtl translation the parentheses would not be in this location.

**Comment by hishamco** [comment]
@domonkosgabor the above render is expected because English is LTR writing, but if you replace with Arabic text for instance it should render without any issue

**Comment by hishamco** [comment]
One more thing before I forget, closed parathesis may not like the one in the example above, especially if it comes at the end

**Comment by domonkosgabor** [comment]
@hishamco thank you for your answer, it's clear now.
