### ISSUE TITLE
Mention Orchard Core Training Demo module in the Guides

### ISSUE THREAD

**Issue by domonkosgabor** [OrchardCMS/OrchardCore#3941]
Lombiq has an [Orchard Core Training Demo](https://github.com/Lombiq/Orchard-Training-Demo-Module) module for training purposes guiding you to become an Orchard developer. It could be helpful to mention this module somewhere in the documentation of Orchard Core.
Maybe the best place to mention this module could be under the Tutorials section [of the Guides page](https://orchardcore.readthedocs.io/en/dev/docs/guides/) with a new section called Developer Tutorials. Or the Tutorials could contain a new list item which could be a hyperlink to the GitHub repository of this module.

Maybe you heard about Lombiq's blog posts, called "[This week in Orchard](https://orcharddojo.net/tag-nodes?TagNode=This%20week%20in%20Orchard)". By reading these posts you can get a quick recap about the recent news around Orchard and Orchard Core. Maybe this series could also worth a mention somehow because the content of these posts could be interesting for developers and for end-users too. What do you think?

**Comment by Piedone** [comment]
The PR was merged a while ago.
