### ISSUE TITLE
Create MetaTag with Liquid (Documentation missing?)

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3943]
I've tried this `{% meta name:"test", content:"test" %}` and debuged the MetaTagHelper.cs.
The tag is generated but doesn't show up at `{% resources type: "Meta" %}` in the `<head>` tag of the Layout.liquid

This question is similar to this one (no answer): #3824

**Comment by jtkech** [comment]
Just tried it works, do you have this line in your layout and in the right place

    {% resources type: "Meta" %}

This is where all your meta tags will be rendered, e.g if you define a meta tag in another view, this is here that it will be rendered. Otherwise, if you define it at the right place from the beginning, you can just use regular html meta tags and maybe with some liquid syntax to define some attribute values (if needed).

**Comment by Flarescape** [comment]
@jtkech thanks for your answer!
My idea is a little bit more "complex".
I have a `ContentPart` which has two text fields.
This part should be added to a `ContentItem` named `"Page"`. (should be a normal content page)

So, if you create a new `"Page"` and enter some values inside this two part fields, the liquid alternate behind the part should create meta tags out of these values.
Currently the liquid in the alternate is `{% meta name:"test", content:"test" %}` just for testing, but this does not add a meta tag to the head tag and yes, i have the `{% resources type: "Meta" %}` inside of the tag.

**Comment by jtkech** [comment]
Okay so it should work.

Can you share your testing code, your alternate using `{% meta name:"test", content:"test" %}` and your layout including `{% resources type: "Meta" %}`.

**Comment by Flarescape** [comment]
Before i post all my code here, i tried the simpler way to test, if this actually works!
So i added the liquid meta tag helper directly under the supposed "section".

The head tag of my Layout.liquid:
```
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% render_section "HeadMeta", required: false %}
    <title>{% page_title Site.SiteName, position: "before", separator: " - " %}</title>

    {% resources type: "Meta" %}

    {% meta name:"test", content:"test123" %}
    ...
```

The HTML output:
![image](https://user-images.githubusercontent.com/1375119/61807442-d582d180-ae39-11e9-9f31-9490755b721d.png)

As you can see, there is no meta tag underneath the title.
I've debugged the whole resource manager and the meta tag is generated and added to `_metas[index] = meta;` in the AppendMeta method.

**Comment by jtkech** [comment]
Meta tags need to run before the resources tag. When rendering a view that belongs to the `Content` zone of the `ThemeLayout`, in fact its code is pre-executed before being effectively rendered by the theme layout.

In your test, `{% meta name:"test", content:"test123" %}` needs to run first.

**Comment by Flarescape** [comment]
Thats nice to know, thanks!
So in my case, if i have my ContentPart with the two text fields and the alternate with my two dynamically filled meta tags, i have to display this part in the Head_Meta section ?

So this is my current solution:
**The Part:**

![image](https://user-images.githubusercontent.com/1375119/61811671-49c17300-ae42-11e9-80d7-285b70e9f9be.png)
--------------------------------

**The "Detail" View Template:**


![image](https://user-images.githubusercontent.com/1375119/61811750-6d84b900-ae42-11e9-89fc-391245b920e4.png)
--------------------------------
![image](https://user-images.githubusercontent.com/1375119/61811787-842b1000-ae42-11e9-8bf3-15f1f1381e2b.png)
--------------------------------

**The Placement.json:**


![image](https://user-images.githubusercontent.com/1375119/61811837-a0c74800-ae42-11e9-8493-f9ca1dad411c.png)

Am i doing something wrong?
I know that this example is without dynamic meta tag values.
It's not that easy with the current documentation :D

**Comment by jtkech** [comment]
Okay, just tried it works.

So i created an `SEOMetadat` part as you and added it to the `Article` type.

In `Content-Article.liquid` i added this to render the part

    {{ Model.Content.SEOMetadat | shape_render }}

Note: This is not necessary if the theme use the default way to render the child shapes of parts / fields of a content item, but `TheBlogTheme` templates only use the data they need from their model.

Then through the admin i created this `SEOMetadat` template.

    {% assign keywords = Model.SEOMetadat.Keywords.Text %}
    {% assign description = Model.SEOMetadat.Description.Text %}
    {% meta name:"keywords", content: keywords %}
    {% meta name:"description", content: description %}

**Comment by Flarescape** [comment]
@jtkech oh wow, i see my fault ...thank you so so much!

I misunderstood the rendering of the part.
I thought, that if i add the part to a random content type it works, but for sure i have to modify it's liquid to actually render the part...that's what i was missing...sry!

But again, thank you very much for your help and also it's now documented with an example!
