### ISSUE TITLE
Rendering stylesheets with style tag helper from widgets

### ISSUE THREAD

**Issue by domonkosgabor** [OrchardCMS/OrchardCore#3947]
Let's say you have a `MyWidget` content type with the `Widget` stereotype. Add this widget to a layer, like `Always`.

Now add a shape to the theme to customize the way and look of this widget. Let's call the shape template to `Widget-MyWidget.cshtml`.
The widget has its own styling, that I only want to render when we are on a page where the widget is visible so let's include the stylesheet using the style tag helper (`_ViewImports.cshtml` of course needed) in the following way:

`<style asp-src="~/MyTheme/widgetstyle.min.css" debug-src="~/MyTheme/widgetstyle.css"></style>`

By doing this for some reason the CSS is not included in the source. No problem, use the resources tag helper in the widget's shape template:

`<resources type="Stylesheet" />`

But whatever the resource type is, it's always be rendered inside the HTML body tag, near the content of the widget, instead of in the head tag of the HTML. The `Layout.cshtml` file contains the necessary resources tag helpers as well.
There are more workarounds to solve this issue. One is [described in here](https://github.com/OrchardCMS/OrchardCore/issues/3418#issuecomment-479709748) to do not use Layers, and the other one is to [pre-render the zones before rendering the resources](https://github.com/OrchardCMS/OrchardCore/issues/3418#issuecomment-479286364).

The source of this issue is that only the body is pre-executed and added to the layout `Content` zone, that's why it was not working with the style tag because the related resources tag helper is executed at the end of the layout. So, to be able to inject a style with a widget, the widget needs to belong to the **body**. But in my case, the widget doesn't belong to the body. [In this issue](https://github.com/OrchardCMS/OrchardCore/issues/3198#issuecomment-464502611), @jtkech explains this in detailed. By using the rendering order in Orchard 1.x, you can use widgets in layers and inject the stylesheets in their shape templates. That's the purpose of widgets, to place them in different zones on the page without having to write any Razor or Liquid code.

The goal will be here to provide a solution, where the rendering order is similar as you can see in Orchard 1.x.

**Comment by Piedone** [comment]
Is this unique to widgets or does this happen with all shapes not injected into the Content zone?

**Comment by domonkosgabor** [comment]
With all shapes not injected into the Content zone, the Widget stereotype is not needed.

**Comment by domonkosgabor** [comment]
And I also raised this issue in Gitter as well: https://gitter.im/OrchardCMS/OrchardCore?at=5d2f3338eab6cd776385d287

**Comment by Piedone** [comment]
Just to add, the solution described under https://github.com/OrchardCMS/OrchardCore/issues/3198#issuecomment-464502611 is not bulletproof. It'll make the shapes execute multiple times and also can't be used with conditional resource inclusions: if you e.g. include a stylesheet in the shape now, then that state will be "cached" (I don't know what actually happens) and the stylesheet will remain included even if in five minutes due to an `if` it's not included from the Razor code any more.

**Comment by Skrypt** [comment]
I'm going to look at this one but without reading all details it seems that normally this should work : 

```
<style asp-src="~/MyTheme/widgetstyle.min.css" debug-src="~/MyTheme/widgetstyle.css" at="Head"></style>
```

**Comment by ns8482e** [comment]
> Just to add, the solution described under [#3198 (comment)](https://github.com/OrchardCMS/OrchardCore/issues/3198#issuecomment-464502611) is not bulletproof

It seems based on solution above,  pre-rendering layout zones (and only layout zones) before rendering layout would solve the issue
