### ISSUE TITLE
The Blog content and SEO??

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#3948]
Hi,

For the blog theme, after you create a blog article, how to optimize SEO to ensure **every new blog post will be crawled and indexed by Google**?

Thanks!

**Comment by dodyg** [comment]
As long as your https://www.robotstxt.org/ allows Google to crawl your site, it will find them.

**Comment by orchardc** [comment]
Thanks @dodyg, Please correct me if I'm wrong but I thought the Blog post are Dynamic content (generate in the fly and load data from database via Liquid); how that is crawled?

**Comment by deanmarcussen** [comment]
Site crawls from Google work by crawling the html on the site, so anything that google can see because it has a link in an html page, google will find.

Refer https://support.google.com/webmasters/answer/70897?hl=en

See also https://github.com/OrchardCMS/OrchardCore/pull/3229

**Comment by orchardc** [comment]
Thanks @deanmarcussen , That is correct and my understanding is that the Blog post is dynamic page, rather than static pages.  So how Google can crawl the site??

**Comment by dodyg** [comment]
Google doesn't care whether it is a static or dynamic page. When it finds the blog posts linked from your main blog, it will follow and index them.

**Comment by orchardc** [comment]
Thanks @dodyg , does it mean we don't have to use sitemaps ? Instead just listing all Blog posts on the homepage? 

I'd expect a Orchard module that can optimize the SEO.

**Comment by dodyg** [comment]
Sitemaps (https://support.google.com/webmasters/answer/156184) would help but I am not sure if such Orchard module exists yet. Regardless, Google will find your blog posts.
