### ISSUE TITLE
Add parent id of a list item in Lucene index

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3949]
In the scenario of having multiple blogs in a site, there is no easy way to query the specific BlogPost Content Items that belong to a specific blog. 

https://github.com/OrchardCMS/OrchardCore/issues/3939#issuecomment-512620314

**Comment by sebastienros** [comment]
We talked about it recently, there might already be an issue for it.

**Comment by Piedone** [comment]
Fixed in https://github.com/OrchardCMS/OrchardCore/pull/4017.
