### ISSUE TITLE
Content item unpublished date modified not changed

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3950]
When unpublishing a content item the date of modification is not changed.

**Comment by sebastienros** [comment]
But should it be?

**Comment by sebastienros** [comment]
Is it in O1?

**Comment by Skrypt** [comment]
Well depends if we don't consider that unpublishing is a change.

**Comment by hishamco** [comment]
Changing the publish status is a change as I see in many CMSs such as Drupal
