### ISSUE TITLE
content picker issu

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3954]
why the content picker doesn't render in add new or edit content?
it was working, just i updated the references to the new version.

![c](https://user-images.githubusercontent.com/24512878/61565766-4c0a8280-aa7a-11e9-8277-e3fd9fd9dc48.JPG)

**Comment by Skrypt** [comment]
The controller of the ContentPicker is now marked with the attribute [Admin] so it is accessible only if your user has the permission to access the admin.

**Comment by jptissot** [comment]
I think this is due to the js not existing on the cdn. I think this was fixed recently. Can you update and see if the issue persists ?

**Comment by aghili371** [comment]
i think it solved now
