### ISSUE TITLE
Install extra components alert in VS 2019

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3956]
![Features](https://user-images.githubusercontent.com/3237266/61590756-4e79f300-abc6-11e9-8518-1447b1518dc4.png)

@sebastienros is this what you mean in the latest community standup, after adding .editorConfig?

**Comment by sebastienros** [comment]
Yes, if the solution worked for you before this change, we need to remove the components that it tries to install from the list.

**Comment by hishamco** [comment]
Is anyone see this alert again?

**Comment by sebastienros** [comment]
I fixed it.
