### ISSUE TITLE
Content Picker doesn't work , What's the reason?

### ISSUE THREAD

**Issue by yueqiniu** [OrchardCMS/OrchardCore#3957]
Here are the steps I set up，But no content was displayed after configuration. Is there anything wrong with my configuration？

**pic-1**

![image](https://user-images.githubusercontent.com/5414777/61594296-d4288d80-ac1c-11e9-91d2-cbd6e376be2e.png)

**pic-2**

![image](https://user-images.githubusercontent.com/5414777/61594298-dd195f00-ac1c-11e9-900e-2c33a1b7aa3f.png)

**pic-3**

![image](https://user-images.githubusercontent.com/5414777/61594299-e5719a00-ac1c-11e9-83a0-e745eb1c859b.png)

**pic-4**

![image](https://user-images.githubusercontent.com/5414777/61594305-f15d5c00-ac1c-11e9-8768-33cf97dbb09a.png)

**Comment by jtkech** [comment]
Just tried, it works on my side, but i use the last dev, which version do you use?

![BlogPosts](https://user-images.githubusercontent.com/8586360/61597978-7f364880-ac17-11e9-8182-0f8d3b241f67.png)

**Comment by yueqiniu** [comment]
I just downloaded the latest version，is working properly . Thank you very much !
