### ISSUE TITLE
BagPart's contained content types are overwritten by modules

### ISSUE THREAD

**Issue by szilardcsere89** [OrchardCMS/OrchardCore#3958]
I have a content type definition where the type has a BagPart and I add a type to the contained content types. My configuration in the module is the following:

```
_contentDefinitionManager.AlterTypeDefinition("MyType", builder => builder
    .WithPart("...")
    .WithPart("...")
    .WithPart(nameof(BagPart), part => part
        .ContainedContentTypes(new[] { "TypeA" })
    )
);
```

When I'd like to use this module **in another one** I can't extend the contained types of the bag only overwrite them:

```
_contentDefinitionManager.AlterTypeDefinition("MyType", builder => builder
    .WithPart(nameof(BagPart), part => part
        .ContainedContentTypes(new[] { "TypeB" })
    )
);
```

Finally, the contained content types are not merged and contain only "TypeB". How should I use it if I'd like to keep both of them?

**Comment by sebastienros** [comment]
we might need an overload of `ContentContentTypes` that allows to merge the items. Or change the behavior to only merge and add another method like `ClearContentTypes`. Please provide a PR for that.

**Comment by szilardcsere89** [comment]
#3978
