### ISSUE TITLE
Clear up "default theme" terminology

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#3959]
Currently "the default [site] theme" and "The Default Theme" are two different things and I think it could use some clarity. This has bugged me for a while :).

- It's not clear why the currently active theme is called "default" on the admin UI. Granted it can be overridden programmatically but this is not clear from the admin UI. If the terminology is sound it could use some clarification (like when the default theme can be overridden) in the yellow admin hint, or it could be renamed to active or current theme. It's named as "current theme" in the code anyway, I'd just call it like that. On a related note what the admin menu item calls "Active Themes" is rather something like "Available Themes" (as not all themes are active which are available in the instance).
- It's not clear why the Default Theme is called "default". It's not something that would be enabled by default (since setup recipes decide this) and it's not a fallback in case of no other theme either since that's the Safe Mode Theme. Maybe call it The Basic Theme or something?

Now I realize this is not priority number 1 but I guess we can agree that clear and consistent terminology is important throughout the app. Maybe my suggestions are not the best but the current ones are definitely unclear. Or am I missing something?

**Comment by jtkech** [comment]
I agree ;)

**Comment by sebastienros** [comment]
Basic sounds good to me.

**Comment by Piedone** [comment]
What about how to call the current site theme? (I.e. something like "current" as it's also in the code, or keep "default" as it's on the UI.)
