### ISSUE TITLE
Support parameterized recipes

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#396]
See https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates for an example. There are two important sections: `parameters` which describe the values that are expected, and how they should be provided (data type, validation, ...) and `variables` which are local expressions that can be reused in the json document.

A scenario would be to enhance the setup screen with these parameters, or to create recipes with dynamic logic like inject a `guid` automatically.

**Comment by sebastienros** [comment]
I implemented a very temporary solution to unblock my requirement, see `IRecipeInterpreter`. But it's extensible so some of it would be reusable when we decide to implement it correctly.

**Comment by agriffard** [comment]
Scipting modules and recipes implemented in #419. 
Still needs documentation.

**Comment by sebastienros** [comment]
Thanks for the reminder 👍
