### ISSUE TITLE
Nested layout for custom module

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3963]
I am creating a custom module and I want the pages in the admin section of the custom module to share common layout inside the theme layout.

[=========Admin Theme Layout =========]
...... [=======Module Shared Layout =====]
...............           [========Views========]

Does such feature exist?

I've read https://github.com/OrchardCMS/OrchardCore/issues/993 but the solution there is confusing and doesn't work.

I've tried in `CustomModule/Views/Shared/_Layout` but it doesn't work

```
@inject OrchardCore.ResourceManagement.IResourceManager ResourceManager
@inject OrchardCore.DisplayManagement.Theming.IThemeManager ThemeManager
@{
    var theme = await ThemeManager.GetThemeAsync();
    Layout = "/" + theme.SubPath + "/Views/Layout.cshtml";
}

@await RenderBodyAsync()
```

This one seems to get access to the Layout page of the theme however now it generates
```
InvalidOperationException: RenderBody has not been called for the page at '/Areas/Crucible.Module/Views/Shared/_Layout.cshtml'. To ignore call IgnoreBody().
```

**Comment by Skrypt** [comment]
I think only one Layout file is accepted / tested so far. Everything else would be a hack of some sort. since you can change the Layout I would suggest you consider having 2 different Layout files simply.

**Comment by dodyg** [comment]
I just need to share common UI elements/partial views because it's an admin section. In normal ASP.NET Core app I just use layout to achieve it. I am not sure how to do that in Orchard Core. 

I have full control on the front end because I use the decoupled approach. This one is for the admin part of the module.

**Comment by bakintunde** [comment]
@dodyg - has this been resolved? It would require being familiar with oc's displaymanagement features. The training demo module helped me with that.

That markup looks small enough to copy over to every page where it's required.

But in any case, you might want to look at the [training demo module](https://github.com/Lombiq/Orchard-Training-Demo-Module)'s [ShapeInjectionFilter.cs](https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/orchard-core/Filters/ShapeInjectionFilter.cs) to see an example of how to dynamically inject some markup into page's zones.

https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Themes/#content-zones-differentiators

**Comment by dodyg** [comment]
Thanks. Let me check the links.

**Comment by ns8482e** [comment]
@dodyg I hope, this has been resolved for you by now.  In case if you are still looking for the solution.

I had similar situation and I have used Zones and Shared Shapes.
Zones are on-demand, can be defined in any View and can be rendered using  `RenderSectionAsync`

I have only one layout for Views, but created reusable shared shapes that can be rendered from Views. 

**ViewXYZ.cshtml**

```
<zone name="MyHeader">
      <h1>My Header</h1>
</zone> 
<zone name="SubContent">
      content
</zone> 

 @
{
 var xyZone = await New.XyZone()
}

@await DisplayAsycn(xyZone)

```

**XyZone.cshtml**
Module shared shape renders on demand zones.
```
.....
@if (IsSectionDefined("MyHeader"))
{
    @await RenderSectionAsync("MyHeader", required: false)
}

@if (IsSectionDefined("SubContent"))
{
    @await RenderSectionAsync("SubContent", required: false)
}
.....
.....

```
