### ISSUE TITLE
Logout and change password menu item in admin theme

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3964]
1-in mobile view, the user name and logout menu are hidden. these are should be shown at the top of the page.

2-the seceond problem, i don't know why we don't have change password in the admin page. i think i we select service receipt, this menu and external login are shown in the layout. 

it's really useful to have change password in admin layout.

**Comment by aghili371** [comment]
@hishamco do you have time to solve this?

**Comment by hishamco** [comment]
I have something to do, but I 'll have a look to it ..
