### ISSUE TITLE
How to understand the "Shell"?

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#3969]
Can I understand the Shell is an instance of an OchardCore? But I saw the ShellHost class, it seems that the Shell could have more than one at runtime. So what does a Shell mean? 
Does it somehow equal to Tenant? I can understand the Tenant well. But the Shell, it confuses me.

**Comment by infofromca** [comment]
> Can I understand the Shell is an instance of an OchardCore? But I saw the ShellHost class, it seems that the Shell could have more than one at runtime. YES
> Does it somehow equal to Tenant? YES

**Comment by HengzheLi** [comment]
> > Can I understand the Shell is an instance of an OchardCore? But I saw the ShellHost class, it seems that the Shell could have more than one at runtime. YES
> > Does it somehow equal to Tenant? YES

Then, why recreate a new term: Shell instead of continuing to use the term: Tenant

**Comment by deanmarcussen** [comment]
So the tenant host is not exactly a tenant, i.e. you won't see it in the list of tenants. 
It is a `Shell`, which can manage other `Shells` , which might be tenants

(I think)

**Comment by HengzheLi** [comment]
> So the tenant host is not exactly a tenant, i.e. you won't see it in the list of tenants.
> It is a `Shell`, which can manage other `Shells` , which might be tenants
> 
> (I think)

ah, this makes more sense

**Comment by Skrypt** [comment]
A `Shell` is doing way more thing than just providing tenants ... 😉
