### ISSUE TITLE
Add Content-Language Header

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3973]
Localization again 😄, while `Accept-Language` header is useful for the request, `Content-Language` is very useful too for the response, there's no support for this yet. I already started a PR in AspNetCore meanwhile, I suggest to add this as a feature for a Localization Module. after that we can integrate with the `RequestLocalizationMiddleware`

If sound is good, I will send a PR for this one

/cc @sebastienros @Skrypt

**Comment by Skrypt** [comment]
Some reading : 
https://www.w3.org/International/questions/qa-http-and-lang

**Comment by hishamco** [comment]
Thanks, AFAIK send the `Content-Language` header via response is way better that using meta tag

**Comment by sebastienros** [comment]
I think this article is more descriptive of the issue: https://www.w3.org/International/questions/qa-text-processing-vs-metadata

It explains why the `lang` attribute and the `content-language` header are different.
