### ISSUE TITLE
Content Items with multiple stereotypes can't be displayed

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#3976]
When you add multiple stereotypes to a content type you won't be able to edit or display it anymore since the shape type what is looked for contains the full stereotype list including the comma separator.

E.g. add `Widget, Test` stereotypes and either try creating an item or display it using FlowPart (if one of the stereotypes is Widget). An exception will be thrown:

```
Exception: Shape type 'Widget, Test' not found
```

**Comment by barthamark** [comment]
I might misunderstood the hint under the Stereotype editor. Also based on the code it seems multiple stereotypes are not supported. Never tried this scenario before, not even in Orchard 1.x. If that is the case then we can close this issue.

**Comment by sebastienros** [comment]
By design you can have only one stereotype. We don't apply validation right now as it's any string. We could ensure it's a single word, no spaces or commas.

**Comment by hishamco** [comment]
While this is by design, we need sort of validation at least as @sebastienros mentioned earlier
