### ISSUE TITLE
it's possible to add extra css ,js file to admin them?

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3977]
How can I add extra CSS or js file in admin theme?
I don’t want to create a new admin theme.

**Comment by Skrypt** [comment]
Every .js file that are added in the /Assets/js folder of TheAdmin theme will be bundled by the gulp pipeline. Though if you want to customize some admin views you will also require to modify the TheAdmin theme. I strongly suggest that you create a new Admin theme by copying the TheAdmin theme and renaming it for doing this. Else you will run into merge conflicts if we change anything the the TheAdmin theme. Knowing that you are using OC as a Nuget package I think that this will be the most relevant way for doing this.

**Comment by aghili371** [comment]
so i have to create new admin them.

**Comment by jtkech** [comment]
Just for infos in your theme manifest you will need the admin tag and you can specify that your theme is based on `TheAdmin` theme so that you don't need to override again all the views.

    ...
    Tags = new [] { "admin" },
    BaseTheme = "TheAdmin"
    ...

**Comment by sebastienros** [comment]
TODO: Create a guide on how to create a custom admin theme.

**Comment by agriffard** [comment]
See #5380 issue to create an admin theme

**Comment by Piedone** [comment]
Done in https://github.com/OrchardCMS/OrchardCore/pull/5584.
