### ISSUE TITLE
iis crash messages in production

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#3979]
Upon deployment to a production web site I am getting the following error messages (stackoverflow) in windows event log :
![image](https://user-images.githubusercontent.com/1516981/61998524-29035280-b0ba-11e9-9948-83ba85fbc39a.png)

After more thorough investigation I discovered that when running under IIS the following exceptions were thrown from orchard : Looks like some threading issues in Autoroute.GetContentItemDisplayRoutes

![image](https://user-images.githubusercontent.com/1516981/61998541-58b25a80-b0ba-11e9-944e-064df14f5a15.png)

This is causing slow performance and sometimes crashing entire IIS.

**Comment by Skrypt** [comment]
How many items you have in your AutoroutePartIndex table and are you using it in a custom module? Because normally these records are cached on the server and should be retrieve pretty fast unless something tries to update/create/remove them concurrently.

**Comment by giannik** [comment]
This is just a simple Page content type with autoroute part. The autoroutepartIndex table has only 20 records and every path is unique.
Maybe this pr  https://github.com/OrchardCMS/OrchardCore/pull/3930 from @jtkech resolves this ??

**Comment by Skrypt** [comment]
Ok, so we need to be able to repro. Give us the more information you can about your deployment environment and how you compile/deploy so we can repro and isolate this bug.

**Comment by giannik** [comment]
Ok, so it has to do with some dependency injections issues in some custom display drivers,
Closing the issue.
