### ISSUE TITLE
Move default themes to a samples "opt-in" nuget package

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#3984]
When building an OC website from nuget packages with a custom theme, you cannot opt-out of having the default themes included in the build release when using the OrchardCore.Application.Cms.Targets package.

Propose creating a OrchardCore.Application.Cms.Samples.Targets package and moving TheTheme, TheBlogTheme, TheComingSoonTheme, and TheAgencyTheme over to the samples package?

Or leave OrchardCore.Application.Cms.Targets result as-is, and create a OrchardCore.Application.Cms.Core.Targets that it points to that is everything except the sample themes. This would be non breaking, but allow targeting OrchardCore.Application.Cms.Core.Targets to only have the admin and and safe mode themes available.

**Comment by sebastienros** [comment]
We can add more metapackages, and it makes sense to have one without themes as most sites will have their own. Not sure it should even have the safe mode one, might not be necessary like it was in o1. 

So yes, we could have an empty cms meta package. `Core` or `Empty`, `Blank`, `NoThemes` ... suggestions? Core seems redundant with Orchard Core maybe, or the way we name the projects that are not modules.

**Comment by petedavis** [comment]
The reason that I thought `Core` so that the `OrchardCore.Application.Cms.Targets` would then take a dependency on a new `OrchardCore.Application.Cms.Core.Targets` package, and the themes. Where the Cms.Core.Targets would be everything but themes.

So to opt out of the themes, you can just change `OrchardCore.Application.Cms.Targets` to `OrchardCore.Application.Cms.Core.Targets`

i.e. it is the core set of modules for a CMS.

Thoughts?

**Comment by sebastienros** [comment]
Ok then, nobody else commented so feel free to create this meta package. It should be as easy as copying current file and tweak the references.

**Comment by jtkech** [comment]
@petedavis good idea ! Then because of the transitive reference don't forget `PrivateAssets="none"`.
