### ISSUE TITLE
OpenID Connect Settings are not applied from recipe and are not exported into deployment plan

### ISSUE THREAD

**Issue by Diman96** [OrchardCMS/OrchardCore#3985]
I use exemple recipe from SaaS recipe and add modules 
`"OrchardCore.OpenId",
"OrchardCore.OpenId.Management", 
OrchardCore.OpenId.Server"` 
and i take exemple recipe step from documentation 
```
{
      "name": "openidsettings",
      "TestingModeEnabled": false,
      "AccessTokenFormat": "JWT", //JWT or Encrypted
      "Authority": "https://www.orchardproject.net",
      "Audiences": ["https://www.orchardproject.net","https://orchardharvest.org/"],
      "CertificateStoreLocation": "LocalMachine", //More info: https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.storelocation(v=vs.110).aspx
      "CertificateStoreName": "My", //More info: https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.storename(v=vs.110).aspx
      "CertificateThumbprint": "27CCA66EF38EF46CD9022431FB1FF0F2DF5CA1D7"
      "EnableTokenEndpoint": true,
      "EnableAuthorizationEndpoint": false,
      "EnableLogoutEndpoint": true,
      "EnableUserInfoEndpoint": true,
      "AllowPasswordFlow": true,
      "AllowClientCredentialsFlow": false,
      "AllowAuthorizationCodeFlow": false,
      "AllowRefreshTokenFlow": false,
      "AllowImplicitFlow": false
}
```
When I launch the site with this recipe OpenID server settings remain default. Also, I can't get the OpenID server settings through the deployment plan with the OpenID server settings.

**Comment by xperiandri** [comment]
@PinpointTownes do you have any ideas?

**Comment by PinpointTownes** [comment]
`"name": "openidsettings"` -> `"name": "OpenIdServerSettings"` maybe?

**Comment by hishamco** [comment]
Seems the registration was missing #4615

@Diman96 could you try now with the latest bits?

**Comment by MichaelPetrinolis** [comment]
#4615 is for the client, for the server settings the fix is what Kevin said.

**Comment by hishamco** [comment]
Ok, I'm working to fix both issues "openidsettings" and deployment one

**Comment by hishamco** [comment]
FYI the **README.md** has been modified to use `OpenIdServerSettings`, @agriffard could you please check the docs too
