### ISSUE TITLE
SQL parameters (limit) not working with ms sql database

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3986]
On Gitter, @deanmarcussen and I found out, that parameters are not working with **MS SQL database**.
Exact same example working fine with **SQLite**.

Template:
```sql
Select *
from ContentItemIndex
where ContentType = 'Blog'
limit @limit
```

Parameters:
```json
{ "limit": 2 }
```

Final SQL Query:
```sql
SELECT TOP @limit * 
FROM [ContentItemIndex] 
WHERE [ContentType] = 'Blog';
```

Error in `AdminController` at this line:
```c#
model.Documents = await connection.QueryAsync(rawQuery, parameters);
```

Error:

`An error occured while executing the SQL query: Incorrect syntax near '@limit'.`

**Comment by Flarescape** [comment]
From @deanmarcussen:
Yes, there's something about the generated sql `exec sp_executesql N'SELECT TOP @limit * FROM [ContentItemIndex] WHERE [DisplayText] LIKE ''Main Menu'';',N'@limit bigint',@limit=2` which sql server doesn't like.

**Comment by deanmarcussen** [comment]
Generated sql needs to be
`exec sp_executesql N'SELECT TOP (@limit) * FROM [ContentItemIndex] WHERE [DisplayText] LIKE ''Main Menu'';',N'@limit bigint',@limit=2`

Note the brackets around the variable name
