### ISSUE TITLE
Add Settings to FieldDefinition, MergeSettings()

### ISSUE THREAD

**Issue by zl2fxy** [OrchardCMS/OrchardCore#3996]
I add Settings to FieldDefinition,using ContentPartFieldDefinitionBuilder.MergeSettings(),
i try add a  data that type is Array or List,it will union OldValue and NewValue rather than replacing，because it set rules of merger at OrchardCore.ContentManagement.Metadata.Builders.ContentBuilderSettings.JsonMergeSettings.
and i try use WithSettings(),it can't set Name of Settings，it accepts only one parameter.

**Comment by sebastienros** [comment]
Can you try to rephrase? Maybe with an example? It's not clear what you are trying to do.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
