### ISSUE TITLE
date picker localize css problem

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4000]
i set in Persian localization the localize for date picker but it looks wrong in show UI.

![local](https://user-images.githubusercontent.com/24512878/62411886-6c9a1700-b5fa-11e9-8c31-d24b4050b094.JPG)

**Comment by hishamco** [comment]
Good catch .. this is a good shoot to me 😄

**Comment by hishamco** [comment]
This should be look like this

![datepicker](https://user-images.githubusercontent.com/3237266/62519698-c84fe480-b834-11e9-999d-bfa7cf45eca0.png)
