### ISSUE TITLE
graphql module issue.

### ISSUE THREAD

**Issue by topdeveloper1001** [OrchardCMS/OrchardCore#4004]
I tried to setup headless orchardcore cms to use graphql api.
I enabled graphql module, but when I try to use graphql there are some duplicated version errors.
[localhost-1565103628206.log](https://github.com/OrchardCMS/OrchardCore/files/3472900/localhost-1565103628206.log)
anyone can help me?

**Comment by carlwoodhouse** [comment]
seen this on prod sites in azure too but never locally, some graphiql issue (think it might have started when we added the explorer @jrestall).

To be clear this just effects the graphiql tool in admin, not the actual graphql api

**Comment by carlwoodhouse** [comment]
might also be what @sebastienros referred too on the last podcast about graphql not working in tryorchard ? @agriffard

**Comment by topdeveloper1001** [comment]
this issue is occurred in local host

**Comment by topdeveloper1001** [comment]
i referenced following video.
https://www.youtube.com/watch?v=4o9zG17cfa0

**Comment by jrestall** [comment]
We use the production build of react even in development so I would have expected to have seen this before since there shouldn't be any difference between dev and prod. Can look into it if you can provide more steps to reproduce.
