### ISSUE TITLE
Predefined list(enumeration) dropdown change doesn't trigger preview refresh

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#4005]
I have a custom widget with a predefined list as dropdown.
The widget has a custom template which outputs different html depending on the dropdown selection.
If i start the preview functionality and change the dropdown value, the preview doesn't refresh the site.

**Comment by sebastienros** [comment]
You might be able to provide a fix. Look at the other fields, they are calling jquery event when the values change.

**Comment by Skrypt** [comment]
As far as I remember when the values are changed in the Vue.js component but are not saved on every change made to the predefined list values/settings. Though if you would change the value selected it should normally work. Maybe something is missing, I never really looked at what the Preview code is doing but I believe it is calling a refresh of the render of the entire page in an IFrame so I suspect that either the values need to be saved on change or they require to have a special class or name for the preview to handle it.

**Comment by Flarescape** [comment]
@sebastienros @Skrypt i'll take a closer look at it and let you know, if i find a solution.

**Comment by Skrypt** [comment]
Ok, I can't repro the issue when adding a TextField with a Predefined List. The preview works appropriately.

![orchard](https://user-images.githubusercontent.com/3228637/62805478-1b889800-babe-11e9-82d9-25481f25438e.gif)

**Comment by Flarescape** [comment]
@Skrypt this only happens to me if the dropdown is inside a widget which is dynamically added to a flow part.
I don't know if that matters, but it's not about the dropdown value itself.
As i've sayed, the value of the dropdown is used to render different html. (liquid if)

**Comment by Skrypt** [comment]
I tried with a Flowpart and the value gets also updated. If you have a Liquid "if" it should also work fine as I think the page gets refreshed entirely in the preview. Please provide repro steps with a clean dev branch source code project or join us on Skype/Gitter.
