### ISSUE TITLE
How do I add a sidebar to the Blog theme?

### ISSUE THREAD

**Issue by lorddev** [OrchardCMS/OrchardCore#4006]
I see no "Widgets" section to install a sidebar (see http://docs.orchardproject.net/en/latest/Documentation/Managing-widgets/). Can you provide documentation on how to add a Sidebar (recent blogs or archive, for example) to the Blog theme in Orchard Core?

**Comment by sebastienros** [comment]
You need to add a custom Zone (RenderSection) in your layout, then add the name of this zone to the Zones settings, and it will be availble. Open the Layoutfile of your theme and look for "Footer" for instance.
