### ISSUE TITLE
The DisplayText is null

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#4008]
In Create Content Task:
{
  "DisplayText":"test",
  ...........
}

I debug in ContentItemIndex,I find that the value of DisplayText is null.

**Comment by sebastienros** [comment]
We would love it if you could give more details about how you are hitting these issues, preferably with repro steps so we can either understand what you are doing wrong, or see it locally so we can be sure about the fix.

**Comment by agriffard** [comment]
Please reopen if you have more repro steps.
