### ISSUE TITLE
Media field issue with white space character on the filename

### ISSUE THREAD

**Issue by mobinzk** [OrchardCMS/OrchardCore#4013]
There seems to be an issue with MediaField for when selecting an image that has white space on the filename. e.g. Profile/profile 1.png.
Selecting the image is fine and can successfully save the content item but after going back to edit the content item, the image doesn't get display and instead I get `Not Found, It will be discarded on saving`.

I've debugged this and found when js tries to get the image detail from `/OrchardCore.Media/Admin/GetMediaItem?path=` fails with error saying `redirected you too many times. `.

**Comment by sebastienros** [comment]
probably missing some encoding

**Comment by mobinzk** [comment]
Manage to debug this and the issue was with one of our custom modules. The media field itself doesn't have any issues.
