### ISSUE TITLE
[Question] about storage / Localization files

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4014]
I am deploying an instance of OC on kubernetes. We currently do not plan on scaling across pods (low traffic site).
The `App_Data` folder is mounted to a persistent volume claim to persist the Tenants and Asset files created at runtime. 
Since the Localization folder is included in the docker image and is localed under `App_Data/Localization` it get's hidden when we mount the PV to App_Data.

Some options to consider: 
- have a script that will copy the Localization to the PV upon creation
- moving the `Localization` folder out of `App_Data`
- moving other `App_Data` files to another storage (blob) I think this is already possible ? This is overkill for our use case.

**Comment by sebastienros** [comment]
c.f. we have the same issue in our docker images then: https://hub.docker.com/r/orchardproject/orchardcore-cms-linux/

**Comment by sebastienros** [comment]
Mitigation, implement a custom `ILocalizationFileLocationProvider` in a module that returns another static folder.

This could also be an issue if the deployment step contains seed data in the App_data.

**Comment by sebastienros** [comment]
We might need a different folder were we put file that are read-only, and not served publicly.

**Comment by sebastienros** [comment]
We might need to review this issue https://github.com/OrchardCMS/OrchardCore/issues/3508 such that the localization files are not exported in App_Data then.

**Comment by hishamco** [comment]
What if we create the localization folder during enabling localization module with suitable permissions, also provide away to import language packs at runtime, similar to what I described in the issues that @sebastienros refers to

**Comment by jptissot** [comment]
I like that idea @hishamco We could embed the po files in the assembly and when enabling the localization module, copy them to the tenant folder under App_Data ?

**Comment by hishamco** [comment]
But we need to take care about setting the right permission for `App_Data`, coz @sebastienros already has a doubt about exporting language packs directly into the `App_Data` folder for security purpose 😄

**Comment by deanmarcussen** [comment]
If you look at `ModularPoFileLocationProvider.cs` you'll see it already supports loading localization po files from embed'd assemblies.

For your current scenario @jptissot it wouldn't be difficult to implement one that searched one of your modules in the same way it currently searches `App_Data`, so you could just contain the localization files in a module. 

Until the nuget localization packages are available.

I think it currently searches each `feature` for it's own po files, but it would probably make more sense for them to be available via a different nuget package, as per #3508 

For custom localization for you own modules, I think the current way it searches modules, might actually work already (maybe).

**Comment by sebastienros** [comment]
I think to solve this issue we should just support another `localization` folder to put po files in. And probably change the documentation to suggest to put the files there, unless they need to be tenant specific, in which case they will be in the app_data, as they would be part of the tenant's state.

The language packages can just export their files in the `localization` folder too.

**Comment by sebastienros** [comment]
We might need to change the csproj to automate the fact that the localization folder will need to be deployed like the wwwroot is.
