### ISSUE TITLE
Nuget Package : Lucene Indexing slow

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#4020]
Need to find repro

**Comment by themattkenney** [comment]
We noticed quite a slow down on CRUD operations with the Lucerne module on.

**Comment by Skrypt** [comment]
It was taking around 7 seconds to do a Publish when there was 1 index and 14 seconds when there was 2 indices. I was suspecting that it was rebuilding the entire index on every publish. I've not been able to repro on the latest branch I worked on.

LuceneIndexingService.cs
```
public async Task ProcessContentItemsAsync(string indexName = default)
```

This method here process a specific index or all of them (for background tasks). Though, when publishing a single content item it's not supposed to call this function at all.

LuceneIndexingContentHandler.cs
```
        public override async Task PublishedAsync(PublishContentContext context)
        {
            var buildIndexContext = new BuildIndexContext(new DocumentIndex(context.ContentItem.ContentItemId), context.ContentItem, new string[] { context.ContentItem.ContentType });
            // Lazy resolution to prevent cyclic dependency 
            var contentItemIndexHandlers = _serviceProvider.GetServices<IContentItemIndexHandler>();
            await contentItemIndexHandlers.InvokeAsync(x => x.BuildIndexAsync(buildIndexContext), _logger);

            foreach (var index in _luceneIndexManager.List())
            {
                var indexSettings = _luceneIndexSettingsService.List().Where(x => x.IndexName == index).FirstOrDefault();
                if (indexSettings.IndexedContentTypes.Contains(context.ContentItem.ContentType))
                {
                    _luceneIndexManager.DeleteDocuments(index, new string[] { context.ContentItem.ContentItemId });
                    _luceneIndexManager.StoreDocuments(index, new DocumentIndex[] { buildIndexContext.DocumentIndex });
                }
            }
        }
```

This Handler is responsible for storing documents one by one. What you would need to check is if this Publish method is called often on every publish. And put also a breakpoint in the ProcessContentItemsAsync to see if it's not called by some custom code.

**Comment by sebastienros** [comment]
@themattkenney I am closing the issue, but will reopen if you can describe some repro steps.
