### ISSUE TITLE
Upgrade to .NET Core 3.0

### ISSUE THREAD

**Issue by maroonedsia** [OrchardCMS/OrchardCore#4022]
Hi, 

Reading the roadmap, OrchardCore RC is planned to be released in Q3 2019.
Now that .NET Core 3.0 will be also released in Q3 2019 (probably September) too, do you have a plan to upgrade and release your RC with .NET Core 3.0?

Thank you!

**Comment by maroonedsia** [comment]
I think this pull request has the answer: https://github.com/OrchardCMS/OrchardCore/pull/3398/commits 

I blame bad naming for not being able to find it before! :P :D

**Comment by sebastienros** [comment]
We announced the plan to ship RC with .NET Core 3.0 on Sept 23rd.
And ship an RTM after that, probably together with a service release of .ASP.NET 3.1 that would contain bug fixes.

**Comment by maroonedsia** [comment]
Thank you, @sebastienros! :-)
