### ISSUE TITLE
Make Lucene sort on multiple fields

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#4028]
Right now we can sort only on a single field. We should be able to sort by multiple fields like this :  

```
"sort": [
    { "Content.ContentItem.ModifiedUtc": { "order": "desc" } },
    { "Content.ContentItem.CreatedUtc": { "order": "desc" } }
  ]
```

**Comment by ampadashi** [comment]
There's another important problem in sorting fields using lucene query. If you make a numeric field, Lucene will not be able to sort with that field.

**Comment by Skrypt** [comment]
I will check but I think there is an issue with everything indexed as a numeric value including range queries who doesn't work as of now.
