### ISSUE TITLE
The translation of "Template for a {0} content item in detail views" this phrase will not apply in fa-IR translation.

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#4031]
I've just finished the translation for Persian language. The translation of the phrase "Template for a {0} content item in detail views" doesn't apply when i set  fa-IR culture as default.

**Comment by Skrypt** [comment]
Please look in Crowdin translations to find this specific string for your culture. If it's missing then it means that it's simply missing. Look for how to contribute on translation with @agriffard

**Comment by ampadashi** [comment]
I’ve just finished translating to persian and the status is now 100%. All the phrases have been translated by me carefully. but, this one has not been applied after download the language pack from Crawdin and set it up. I think there’s some kind of problem.

**Comment by hishamco** [comment]
I will have a look to this one and come back to you

**Comment by hishamco** [comment]
@ampadashi could please have a look to `OrchardCore.Templates.pot` in crowdin, if the above localized string is there?

**Comment by hishamco** [comment]
FYI I'm not able to edit this in Arabic, if that's your case, I need to ping @agriffard to check what's going on here

**Comment by agriffard** [comment]
The localization of these strings are not working in any language. Ex in French:
![image](https://user-images.githubusercontent.com/703248/63093652-5d09bf00-bf66-11e9-88fe-afc7584e8137.png)

They are loaded here: https://github.com/OrchardCMS/OrchardCore/blob/24bc9c898eb146b1d60d587a81a02cef1025aac7/src/OrchardCore.Modules/OrchardCore.Templates/Settings/TemplateContentTypeDefinitionDriver.cs#L34
but they are not taking the current culture.

How can we do this?
`S["The formatted string {0}", arg].Value` ?

**Comment by hishamco** [comment]
@agriffard if the localization strings in the `.po` file, I will have a look to this issue

**Comment by agriffard** [comment]
Yes they are in OrchardCore.Templates.po:

```
#. Description = S["Template for a {0} content item in detail views", contentTypeDefinition.DisplayName]
#: OrchardCore.Templates\Settings\TemplateContentTypeDefinitionDriver.cs:34
msgctxt "OrchardCore.Templates.Settings.TemplateContentTypeDefinitionDriver"
msgid "Template for a {0} content item in detail views"
msgstr "Modèle pour un élément de contenu de {0} dans les vues de détail"

#. Description = S["Template for a {0} content item in summary views", contentTypeDefinition.DisplayName]
#: OrchardCore.Templates\Settings\TemplateContentTypeDefinitionDriver.cs:41
msgctxt "OrchardCore.Templates.Settings.TemplateContentTypeDefinitionDriver"
msgid "Template for a {0} content item in summary views"
msgstr "Modèle pour un élément de contenu de {0} dans les vues summary"
```

**Comment by hishamco** [comment]
OK, just leave the other things to me, thanks a lot

**Comment by hishamco** [comment]
@agriffard again it's a copy paste issue, look to my PR, absolutely you will remember similar issue happened in the past

**Comment by agriffard** [comment]
Good catch
