### ISSUE TITLE
Navigation & menu in orchard core

### ISSUE THREAD

**Issue by sivakumar715** [OrchardCMS/OrchardCore#4036]
In the Orchard 1.x , We have feature called **Navigation and Menu** and can be able to add menus/sub menus easily. We can able to use the menu items in the custom menu widget.
http://docs.orchardproject.net/en/latest/Documentation/Navigation-and-menus/

Under Navigation Menu:
![image](https://user-images.githubusercontent.com/54092242/62999154-2c088c00-be8b-11e9-8abd-6960fd08e10c.png)

Under Custom Menu Widget:
![image](https://user-images.githubusercontent.com/54092242/62999274-8275ca80-be8b-11e9-8142-d38b71b02890.png)

Do we have similar feature in Orchard core?

**Comment by deanmarcussen** [comment]
Do you mean like this (sample from the blog theme) ?

![oc-menu](https://user-images.githubusercontent.com/13782679/63007188-12aa1480-be78-11e9-8233-8fb6e0920118.PNG)

The docs for menu are available at https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Menu/

For the widget question, you can now render the menu with a Razor tag helper, or Liquid filter, so you can choose how to render yourself. You could look at TheAgency or Blog sample themes for examples of this in liquid or TheTheme for a Razor example.

Does this answer your questions?

@sebastienros I notice that the menu migration recipe does not set the `Menu` content type to `Creatable` by default, so without changing the content type definition to `Creatable` you cannot create new menu's from the ui. Is this intended to be the default?

**Comment by sebastienros** [comment]
Maybe we used to have a link in the admin that would only list the menus, but even in this case it wouldn't have Listable. So I think we should have it Creatable. 

So either create a link to List/Manage the menus in the Content section, or make Menu both Creatable and Listable.

**Comment by sivakumar715** [comment]
Thanks for the quick update @deanmarcussen @sebastienros . Please let us know once the Menu content type updated with Creatable and Listable.
