### ISSUE TITLE
UTF-8 encode

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#4041]
Content stored in MySql server is UTF-8 but display in HTML source is UTF-8 encoded. How to fix this? Thanks!

**In MySql:**
![image](https://user-images.githubusercontent.com/6874322/63098225-99f0a880-bf9c-11e9-8cee-baba7f2b1c6d.png)

**Display in source code:**
![image](https://user-images.githubusercontent.com/6874322/63098408-12f00000-bf9d-11e9-8d5f-79820e89c858.png)

**Comment by sebastienros** [comment]
Can you provide some repro steps? Also does it work correctly with other databases?

**Comment by lthoa** [comment]
You can see here : https://lastella.edu.vn in source code. Some parts display with UTF-8 anh many parts display in encode. 

MySql was set to UTF-8 charset and it work good.

**Comment by sebastienros** [comment]
Repro steps means how should we do on our computer to reproduce the issue. For instance I assume you are using a module to render these. Or are you rendering them from your own template?

**Comment by lthoa** [comment]
The same problem if using origine Agency template built-in Orchard Code and update with Vietnamese content. Even the Admin page, HTML source code also displays heterogeneous if we using Vietnamses language UI (set culture to vi)

**Comment by hishamco** [comment]
Did you try to use UTF-8 Collation for the MySQL database?

**Comment by lthoa** [comment]
I have many apps using MySql UTF-8 and I sure MySql was set to run with UTF-8 charset. I think we need check YesSql

**Comment by hishamco** [comment]
I don't think YesSQL will change the collation, could you try to use YesSQL sample with your database to ensure if there's a bug in YesSQL or not

**Comment by lthoa** [comment]
**Startup.cs**
![image](https://user-images.githubusercontent.com/6874322/63249713-34e6cc80-c294-11e9-9d4a-5ec0c163b9fa.png)

**HomeController.cs**
![image](https://user-images.githubusercontent.com/6874322/63249800-6069b700-c294-11e9-9358-1f34568b3b85.png)

**Index.cshtml**
![image](https://user-images.githubusercontent.com/6874322/63249851-7d05ef00-c294-11e9-92ec-cb53eb9a1f17.png)

**And result in source code**
![image](https://user-images.githubusercontent.com/6874322/63249878-8e4efb80-c294-11e9-8265-f607fa249b1d.png)

The problem from ASP.NET Core?

**Comment by hishamco** [comment]
I 'm not sure, could you please create a repo for this sample including database scripts, I will check it myself

**Comment by lthoa** [comment]
This sample simply rendering some strings directly from the MVC web page, do not use the database.

**Comment by hishamco** [comment]
I see seems it's encoding issue

**Comment by hishamco** [comment]
![vi](https://user-images.githubusercontent.com/3237266/63254670-cfd3ac80-c27c-11e9-8318-e251ca0a50d3.png)

There's no issue related to OrchardCore nor YesSQL, if you talking about the html output, these are html entities because your are using extra symbols

**Comment by lthoa** [comment]
It is true that there is no problem regarding OrchardCore as well as YesSql, this is an issue of ASPNET Core. 
UTF-8 character set does not require HTML encoding,  all browsers display UTF-8 well in the page source and user interface. HTML encoding increases the webpage size more 2-3 times. 
My applications using the old ASP.NET platform do not encounter this problem.

**Comment by Skrypt** [comment]
It could be because of encoding we use with Liquid templates. They are using now HtmlEncoder.Default. But I'm surprised because here you say that this happens with a Razor template.

**Comment by deanmarcussen** [comment]
Maybe try with `@Html.Raw()` or is that too simplistic?

**Comment by sebastienros** [comment]
I think this is because the default `HtmlEncoder` in ASP.NET Core is much less permissive and doesn't take any risk. Look at this piece of code we are using in the benchmarks to opt-in the dash char:

https://github.com/aspnet/Benchmarks/blob/master/src/Benchmarks/Startup.cs#L142-L146

I think you should do the same thing with the range of unicode characters you want to allow.

**Comment by sebastienros** [comment]
However there is no option to change it globally for our liquid templates, we use the default html encoder for anything that is outputted as html. It can be changed too but most templates are rendered internally so you can't set the option. I think we should add a global option as for the html encoder to use in liquid.

**Comment by hishamco** [comment]
>  I think we should add a global option as for the html encoder to use in liquid

I think we add some encoding if I'm not wrong, let me check

**Comment by lthoa** [comment]
Adding:
services.Configure<WebEncoderOptions>(options => 
{
      options.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All);
});
https://github.com/aspnet/HttpAbstractions/issues/315

into ConfigureServices it works with strings rendered by the MVC controller, but with liquid it doesn't work.

**Comment by Skrypt** [comment]
That's because it is hardcoded
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/LiquidViewTemplate.cs#L114

**Comment by sebastienros** [comment]
We could use the same options instance

**Comment by linhdhvn** [comment]
![source-utf8-vietnamese](https://user-images.githubusercontent.com/24636781/69069699-83edfa80-0a59-11ea-8388-52fa1ff0f6b0.PNG)

Dear all,

I have done fix this bug by replace all HtmlEncoder.Default to HtmlEncoder.Create(new TextEncoderSettings(System.Text.Unicode.UnicodeRanges.All))

**Comment by Skrypt** [comment]
Ok but not the proper fix as explained in #4711 
Good to know it works for you.

**Comment by sebastienros** [comment]
I submitted this PR to fix it the best way: https://github.com/OrchardCMS/OrchardCore/pull/4832

**Comment by sebastienros** [comment]
`HtmlEncoder` happens to be registered as a singleton using the `TextEncoderSettings` defined in the `WebEncoderOptions`. 

c.f. https://github.com/aspnet/HtmlAbstractions/blob/master/src/Microsoft.Extensions.WebEncoders/EncoderServiceCollectionExtensions.cs/#L34-L35

**Comment by hishamco** [comment]
I didn't dig into the PR, is this will reflect to Fluid encoding?
