### ISSUE TITLE
LayoutTag bug or incorrect documentation

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#4046]
LayoutTag usage in documentation is shown as:

`{% layout "CustomLayout" %}`

but this is not working. What will work is:

`{% layout "Layout__CustomLayout" %}`

so either it is error in documentation or LayoutTag should internaly append "Layout__" string.

**Comment by hishamco** [comment]
I can confirm it's not a bug in Fluid, you could checkout with latest bits

**Comment by hishamco** [comment]
@sebastienros can you reproduce this bug, coz everything is working fine at my end
