### ISSUE TITLE
Administrator menu is not displayed when multi-tenant path prefix is used

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#4052]
![QQ截图20190816234201](https://user-images.githubusercontent.com/14150259/63179828-92ee9680-c07f-11e9-8c33-7a1e59976f68.png)

**Comment by hishamco** [comment]
Could you please provide the steps to reproduce the issue?

**Comment by EternityTeam** [comment]
I've tested that it's okay for new tenants to have URL prefix, possibly because of upgrades from existing tenants. Thank you for your reply.
