### ISSUE TITLE
Change parent admin menu for Lucene and SQL Queries and for Lucene indices 

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4058]
The parent admin menu for Lucene and SQL Queries and for Lucene indices should be something else than "Site" because it is too vague.

I suggest to make Queries a parent menu in which we will add: 
- The current Queries menu and call it All queries.
- The Lucene queries menu with the name "Test Lucene query"
- The Sql queries menu with the name "Test Sql query"

and make a menu Indexing for "Lucene indices" (or "Indexing" as parent and "Lucene indices" ad sub menu)

**Comment by sebastienros** [comment]
"Test Lucene queries"
