### ISSUE TITLE
can  we  abstract Azure Blob Storage as a module

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#4061]
so the OrchardCore.DataProtection.Azure and OrchardCore.Media.Azure can use it .
in future for keyvault ,  media service....

**Comment by sebastienros** [comment]
Do you mean to be able to reuse the Azure configuration across different azure services? Or reuse the same Blob Storage configuration for other modules that are dependent on blobs?

**Comment by sebastienros** [comment]
You can already define these settings for each module that uses Azure.

Example:
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.DataProtection.Azure/
