### ISSUE TITLE
Upgrade ImageSharp.Web

### ISSUE THREAD

**Issue by lahma** [OrchardCMS/OrchardCore#4073]
[The PR to reduce allocations](https://github.com/SixLabors/ImageSharp.Web/pull/69) was merged, need to wait for release.

**Comment by deanmarcussen** [comment]
Also for info
A further update to ImageSharp has improved no-op when no commands are present (for when an Image shouldn't be resized, or if it isn't an Image), so as and when the new release occurs, we can remove some of the extra validation work we do
