### ISSUE TITLE
Broke layers by deleting content definition

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#4080]
Hi!

I have a `layer` called `header` in which i added a `widget`.
I've deleted the `widget content definition`, because i didn't need it anymore and now i can't open the `layer` overview because it throws a `NullReferenceException`.

It's similar to this: #1014

**Comment by deanmarcussen** [comment]
I think the content type definition lookup is based on the technical name, so you maybe able to ressurect the definition by creating another with the same `technical name`, and then removing the widget from the layers list and then deleting again.

Note you may also need to add the parts back into the widget, which isn't ideal.

Solution 3 from #1014 sounds like the easier way forward

**Comment by Flarescape** [comment]
Ok, that's definitely the better solution.
I just deleted it directly in the db :D
