### ISSUE TITLE
How to programmatically create a custom Content Type instance?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#4081]
Assume I have defined a custom "ContentType", call MyPage, which contains the following 3 elements: Description, Image, Title.

Fields
- Description
- Image

Parts
- Title

**Question: How to programmatically create this content type instance in a custom module**? i.e. create a new MyPage instance.

Many thanks!

**Comment by sebastienros** [comment]
Either with a Recipe migration (example in Menu module) or with custom code in a Migration.cs file, example in https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Lists/Migrations.cs
