### ISSUE TITLE
Autoroute for content item inside bag part does not work

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#4082]
I don't know if this behavior is intended, but if you create a content item with a bag part which can hold content items with the autoroute part attached, the route will not be registered.
If you publish the content item with the bag part, which should publish the new content items inside the bag part too and afterwards open the bag part content via it's autoroute you get a 404 page not found.

**Comment by Skrypt** [comment]
I think there's an issue already reported/triaged for this.

**Comment by Flarescape** [comment]
Thanks, didn't saw that one.
So for now i have to find some other solution!

I think my workaround will be, that the bag part only contains content items with a simple content picker which holds the actual content item.

**Comment by sebastienros** [comment]
The mitigation is to use a Content Item Picker field in one of the bag items.

Duplicate

**Comment by Flarescape** [comment]
@sebastienros Thank you! I just did it that way and it seems to work for my purpose.
