### ISSUE TITLE
GitHub Issue labeling

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4087]
Discussion on how to organize github issues.

**Comment by jptissot** [comment]
Would it be possible to implement issue and pr templates for this project. We could have templates for bug, questions, etc .. and the templates could automatically tag the issues with a triage tag. Thoughts ?

**Comment by hishamco** [comment]
May be I label many issues aggressively, my aim was to classify them, but seems this made an issue while the last triage

I suggest to create more labels for modules such as `Orchard.Users`, `Orchard.Localization` .. etc. Also we could create a templates for bugs as @jptissot mentioned

**Comment by sebastienros** [comment]
Labels are nice as long as they are used/useful. We don't have clear owners for them, so they don't really add value for now, we don't even use the existing ones. Adding more would just be more work.

Change my mind

**Comment by sebastienros** [comment]
Templates, why not. But simple ones.

**Comment by Jetski5822** [comment]
Not a fan of templates;

Issue labels - we need to trim back to only the ones we use

**Comment by hishamco** [comment]
> Adding more would just be more work

I can do that, believe me it's easier to classify the issue by modules at least as well as bugs

**Comment by jptissot** [comment]
I was thinking 1 template for question (which would apply the question label), 1 template for bugs and 1 for feature request.
