### ISSUE TITLE
Feature request - add user permissions (not only via roles) 

### ISSUE THREAD

**Issue by os1r1s110** [OrchardCMS/OrchardCore#4089]
Sorry if this is already available and I haven't seen it. I'd like to know if it would  be possible to not only add roles to a user from which permissions would be "inherited" but also specify permissions directly for specific user(s).

This would add flexibility that would prevent having to create "over-specialized" roles just to effectively have some specific permissions applied to user(s)

**Comment by bakintunde** [comment]
Sounds related to the discussion at  #4040. 
Is there anything you'd like to add there?

**Comment by os1r1s110** [comment]
Not sure to see how it directly relates to content items permissions... I saw #4040 is about permissions enhancements but it didn't really seem to mention anything about adding a link between user and permissions to the existing user - > role - > permission link

**Comment by bakintunde** [comment]
You're right. That specific case is not mentioned in the issue yet. 
But it might be great to incorporate it into the mix as both issues talk about enhancements to permissions.
Better to consider as many sides in the approach so we can collaborate on the related issues.
I could incorporate it in any case.

Thanks.
