### ISSUE TITLE
Page Title for sub pages in Agency theme

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#4090]
In Layout.liquid page of the Agency theme we have: 
**<title>{% page_title Site.SiteName %}</title>**

If we create a page of Content Types (e.g: ContentDetail, template is Content__ContentDetail) with permalink and page title, when open the created page then page title always render only the SiteName, of course.

My temporary solution is:
Change in Layout.liquid to:
**<title>{% render_section "PageTitle", required: false %} - {% page_title Site.SiteName %}</title>**

and in the Content__ContentDetail template add:
**{% zone "PageTitle" %}
{{ Model.ContentItem }}
{% endzone %}**

Do you have a better solution?
Thanks.

**Comment by arkadiuszwojcik** [comment]
How do you render ContentDetail? I had simillar problem and had to render whole shape to make title appear in header. My code is:

`{% shape_remove_item Model.Content "ArticlePart" %}`
`{{ Model.Content | shape_render }}`

but when I was using code like this:

`{{ Model.Content.MarkdownBodyPart | shape_render }}`

it didn't work.

My guess is that TitlePart have to go through some shape processing pipeline.

**Comment by lthoa** [comment]
ContentDetail is a Content Types created in Admin page and Content__ContentDetail is template of the ContentDetail.

![image](https://user-images.githubusercontent.com/6874322/63820766-ac8fb800-c974-11e9-9a13-a1d34fc304d5.png)

You render ContentDetail by create a page from menu New/ContentDetail 

![image](https://user-images.githubusercontent.com/6874322/63820776-ba453d80-c974-11e9-9bef-ba55c03f48b7.png)

**Comment by sebastienros** [comment]
Is the question answered?

**Comment by cabbage89** [comment]
`await DisplayAsync(Model.Content.ContentsMetadata);`

Or

`{{ Model.Content.ContentsMetadata | shape_render }}`
