### ISSUE TITLE
Swagger not work well

### ISSUE THREAD

**Issue by zclmoon** [OrchardCMS/OrchardCore#4091]
Hi There,

I was trying to add a swagger module into my project build with OC. I failed after few hours try.

Here goes the startup of the new swagger OC module.

`    public class Startup : StartupBase
    {
        private readonly string _tenantName;

        public Startup(ShellSettings shellSettings)
        {
            _tenantName = shellSettings.Name;
        }

        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v0.1", new Info { Title = "Study Card API", Version = "v0.1" });
            });
        }

        public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            app.UseSwagger();

            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Study Card API V0.1");
                c.RoutePrefix = "swagger";
            });
        }
    }`

I got error "Not Found /swagger/v1/swagger.json", when try to access http://localhost/swagger/index.html

Could you please help for this? thanks.

BTW, is that a valid feature request to add the swagger module as one modules of the OC framework?

Thanks,
Richie

**Comment by deanmarcussen** [comment]
Are you using a tenant prefix, i.e. a multi tenant?

I'm not sure the swagger middleware would support that natively, so you may have to add the tenant name to the `c.RoutePrefix = `

**Comment by Jetski5822** [comment]
I did this like two years ago https://github.com/Jetski5822/ECom/blob/master/src/ECom.Modules/ECom.Swagger/Startup.cs at an experiment.

dunno if it still works.

**Comment by sebastienros** [comment]
Please let us know if the recommendations work for you

**Comment by MatthijsKrempel** [comment]
Have a look here;

https://github.com/OrchardCMS/OrchardCore/pull/4139

**Comment by zclmoon** [comment]
> I did this like two years ago https://github.com/Jetski5822/ECom/blob/master/src/ECom.Modules/ECom.Swagger/Startup.cs at an experiment.
> 
> dunno if it still works.

thanks, it is not work now.
