### ISSUE TITLE
Wrong sequence/order when redering parts through Model.Content

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#4093]
I have a LandingPage with 2 Parts, lets assume IntroPart and BlogPart (configured in that seqeunce). Then I have 

The template Content__LandingPage contains only following code:
` {{ Model.Content | shape_render }}`

The LandingPage__IntroPart and LandingPage__BlogPart template contain something like that
```
{% if Model.ContentItems.size > 0 %}
            {% for value in Model.ContentItems %}
some-html for drawing
```

With that setup I want that each part has it's own html-render logic, so I can reuse it in different orders on different templates without making a full template wih all logic every time.

In my case what happens is that the seqeunce is not as configured in the admin, BlogPart shows up before IntroPart. Any suggestion/ideas?
Thanks

**Comment by sebastienros** [comment]
I don't think we are applying the order that is specified in the content type definition for the front-end. I think it's just for the admin. For the front end we use Placement rules, including `placement.info` files. With this you will set the order of each shape. You can even hide them. And you won't need to create a custom template.

**Comment by LMSSonos** [comment]
Thanks for the information. Is there any documentation/example about the ```placement.info``` i tried to search the repo but could not find a helpful example. The other idea working around is to use a Bag and add the parts into the bag here the sorting looks good. I used then

```
{% for item in Model.ContentItem.Content.BagPart.ContentItems %}

{{ item | shape_render }}

{% endfor %}```

But in this case the issue is that the Part_Templates are not applied as described in first example. Is there a special naming required when they are withing a Bag?

**Comment by sebastienros** [comment]
https://orchardcore.readthedocs.io/en/dev/OrchardCore/OrchardCore.DisplayManagement/#placement-files
