### ISSUE TITLE
Forms Module - Select Widget not working/complete

### ISSUE THREAD

**Issue by jonvee** [OrchardCMS/OrchardCore#4094]
When using the Forms Module, the Select Widget only has fields for Name and ID. There is no means to add options or add an actual select element to the form. 
My current workaround is adding a liquid widget to the form and hard coding the html.

I only briefly looked at the source code and it appears unfinished.

**Comment by jptissot** [comment]
I had the same issue. I ended up creating a SelectInput type with a bag of SelectOption type and implementing the templates myself.

**Comment by urbanit** [comment]
Still issue active

**Comment by sebastienros** [comment]
PRs are open
