### ISSUE TITLE
make  the function of autoroute in widget enable (disable)

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#4100]
when i use `
 https://localhost:44300/Contents/ContentItems/47h74wd94nj3pt0rfmsepzz05a`

it can not render the shape,when it is a widget.
-------------
but  it can be showed when it is contentType.
-----
sometimes I need to show contentItem  for the widget.

**Comment by jptissot** [comment]
What are you trying to do? You are trying to render a content item but it's a widget?

**Comment by infofromca** [comment]
I think so. but maybe it is difficult

**Comment by sebastienros** [comment]
There is already an issue about, someone will add a link here. The idea is that it will require more changes to be able to do it, and if you need to link to sub items then you can use a Content Picker Field instead.
