### ISSUE TITLE
Liquid date format not working with time in seconds

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#4104]
Today I came across a strange, very specific problem.
Like many examples online, i just wanted to add days to a date "now".
The problem is, that the date parse works fine until you want to parse it back from seconds.
I've tried multiple solutions, but nothing will be displayed if you want to parse it back to a normal date or something.
This is the example i've found online:
```
{% assign days = 3 | times: 86400 %}
{{ "now" | date: "%s" | plus: days | date: "%Y, %m, %d" }}
```

_--copied from gitter_

**Comment by hishamco** [comment]
If this a bug, please move it to Fluid repo, I will check it then

**Comment by sebastienros** [comment]
Until OC is updated with this new version, you can reference the version `1.0.0-beta-9588` of the package from your own project and it will use this one instead.
