### ISSUE TITLE
Migrating to Tasks 2.0.0

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/OrchardCore#4105]
Should we upgrade tasks to version 2.0.0? 
[https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200](https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200)

**Comment by urbanit** [comment]
If so, possible candidate:
[https://github.com/urbanit/OrchardCore/blob/tasks_2/.vscode/tasks.json](https://github.com/urbanit/OrchardCore/blob/tasks_2/.vscode/tasks.json)

**Comment by hishamco** [comment]
Is there useful things that allow us to migrate?

**Comment by urbanit** [comment]
It wouldbe useful in Multi-root Workspaces in VS Code..

**Comment by agriffard** [comment]
Can this be closed since #7077 has been merged @Skrypt ?
