### ISSUE TITLE
Pager does not work in 1.0.0-beta3-72198

### ISSUE THREAD

**Issue by Habbni** [OrchardCMS/OrchardCore#4110]
Hi,
is this a known issue? the pager html is being rendered, but the (prev/next page) links are not being generated.

this can be reproduced easily: just load up a new application with build 72198. Change the blogs list size to 2. Enter three posts. Try the pager - nothing happens.

it stopped working somewhere between the beta3 release and the current dev 1.0.0-beta3-72198 i suppose

**Comment by deanmarcussen** [comment]
Yes, I can repro.

It's since https://github.com/OrchardCMS/OrchardCore/pull/3930

@jtkech for info I think it's recognising /blog as the homeroute in `AutoRouteRoute`, and returning.

The pager seems fine on a page which is not the homeroute

**Comment by jtkech** [comment]
Okay thanks, need to leave, i'll fix it this night.
