### ISSUE TITLE
Order of group on Admin Features page

### ISSUE THREAD

**Issue by jeremycook** [OrchardCMS/OrchardCore#4119]
The groups of features on the Admin Features page appear in some (seemingly) random order. I just created the default tenant and these are how the groups are sorted.

1. Application
2. Configuration
3. Infrastructure
4. Content Management
5. Api
6. ...

**Comment by sebastienros** [comment]
Should it be ordered alphabetically?

**Comment by jeremycook** [comment]
Yeah, alphabetically seems like the least surprising order.

**Comment by sebastienros** [comment]
Please create the PR if you find some time
