### ISSUE TITLE
Should ISlugService be moved in another Project

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4123]
It is currently in the Liquid module but I feel this belongs somewhere else? 

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Liquid/Services/SlugService.cs

**Comment by hishamco** [comment]
If it will play nicely with AutoRoute, I can suggest to move there

**Comment by Piedone** [comment]
It's now in `OrchardCore.Abstractions`.
