### ISSUE TITLE
Create an email address validation service

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#4124]
Following this pattern:
https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address

`IEmailAddressValidator` defined in `OrchardCore.Abstractions`

**Comment by hishamco** [comment]
Could we move it to `Orchard.Email` instead?

**Comment by sebastienros** [comment]
No actually. It can provide service for validating email addresses. For instance a login page, or a form element would need that, and not necessarily  the Email module.

**Comment by hishamco** [comment]
Make sense
