### ISSUE TITLE
Asset layout trouble

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#4127]
![image](https://user-images.githubusercontent.com/6829626/64016160-eb696d80-cb2e-11e9-88bb-ca3c492fdee4.png)

![image](https://user-images.githubusercontent.com/6829626/64016188-f91ef300-cb2e-11e9-8c53-7c655518d2aa.png)

**Comment by hishamco** [comment]
Could please try to remove browser cache and try again, coz sometimes is happen

**Comment by AcellaEDU** [comment]
Does not help

Also
![image](https://user-images.githubusercontent.com/6829626/64077955-252ca680-ccde-11e9-9fb5-0e562c7c4d15.png)

![image](https://user-images.githubusercontent.com/6829626/64077988-7a68b800-ccde-11e9-9942-c46259671e05.png)

![image](https://user-images.githubusercontent.com/6829626/64078005-8a809780-ccde-11e9-832a-730f35d5809f.png)
