### ISSUE TITLE
Route translations with dynamic routing

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4130]
Seems ASP.NET Core 3.0.0 Preview 7 introduces `MapDynamicControllerRoute` and `DynamicRouteValueTransformer` which makes localization routes easier.

This could be useful for multi tenant applications where tenant routes can be activated/deactivated at any point

Have a look to this great article https://www.strathweb.com/2019/08/dynamic-controller-routing-in-asp-net-core-3-0/ by @FilipW

**Comment by jtkech** [comment]
We use them in the 3.0 branch for the home route and autoroutes

**Comment by sebastienros** [comment]
I assume it's fine closing the issue as we already make use of it

**Comment by hishamco** [comment]
> We use them in the 3.0 branch for the home route and autoroutes

Happy to hear that, I'm fine Seb to close this one
