### ISSUE TITLE
Image cache control in /media doesn't work

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4134]
Orchard Core version `1.0.0-beta3-72166` decoupled

![cache-control-media](https://user-images.githubusercontent.com/1761249/64075658-429c4900-ccbb-11e9-852e-b0beede98453.png)

Because according to the docs, the cache should be by default 30 days https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Media/

![cache-settings](https://user-images.githubusercontent.com/1761249/64075719-277e0900-ccbc-11e9-9ec0-04db73a7e0f9.png)

**Comment by deanmarcussen** [comment]
Dup of https://github.com/OrchardCMS/OrchardCore/issues/3807

I have some time, I'll fix it now
