### ISSUE TITLE
How to programmatically create 100 pages from a custom module?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#4141]
I have defined a custom "ContentType", call MyPage, which contains the following 3 elements: Description, Image, Title.

Fields

    Description
    Image

Parts

    Title

Question: How to programmatically create 100 pages from a custom module? 

Many thanks!

**Comment by jrestall** [comment]
I know this doesn't directly answer your question, but one option is to use a recipes file that stores the details for each of the pages and will create them when run.

Here's an example at the end of this recipe:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheAgencyTheme/Recipes/agency.recipe.json

Add a few MyPage content items and then use the Deployment Plan Import/Export functionality to have Orchard generate the bulk of the recipe file for you.

And an example of running a recipe as a data migration:
https://github.com/OrchardCMS/OrchardCore/blob/master/src/OrchardCore.Modules/OrchardCore.Menu/Migrations.cs

If you want full programmatic control then look at IContentManager e.g. https://github.com/OrchardCMS/OrchardCore/blob/master/src/OrchardCore.Modules/OrchardCore.Demo/Controllers/HomeController.cs#L57

**Comment by hishamco** [comment]
Have a look to the ContentManagement APIs

**Comment by Skrypt** [comment]
Migration with a recipe file ; nice one. I'm learning every day.

**Comment by hishamco** [comment]
It depends on the scenario

**Comment by sebastienros** [comment]
You would need to inject the content manager in the migration and create these, but usually content created at runtime is not random and you probably have a set of data somewhere.

Recently someone showed me another way to create lots of content, by creating a custom workflow and then call the endpoint with some load generation tool and the values in the request (querystrings or form body).

**Comment by orchardc** [comment]
Thanks guys, all I want to do, is when clicking a button in my custom module (a MVC page), it will then create 100 pages content based on the custom ContentType template.  i.e. create 100 pages with same information. 

I'd think there is a API simply to do it? something like below:

```
for(int i=0; i< 100; i++)
{
    MyPage p = new MyPage();
    p.title = "hello";
    p.create();
}

```

**Comment by orchardc** [comment]
Thanks @sebastienros , I think workflow also works, only question is how to load 100 pages contents into the Content Property (as highlighted below). The page contents should be different per page. 


![image](https://user-images.githubusercontent.com/16193516/64206800-31a63000-ce93-11e9-93b6-39988c1fce92.png)
