### ISSUE TITLE
Implementation text search

### ISSUE THREAD

**Issue by mruslan97** [OrchardCMS/OrchardCore#4142]
This is my Lucene query 
`{
  "from" : {{from}}, 
  "size" : {{size}},
  "query": { 
    "bool": { 
      "must": [
        { "match": { "HtmlBodyPart":   "{{searchString}}"      }}        
      ]
    }
  }
}`
How i can use it? Any examples with forms or http workflows? thx

**Comment by mruslan97** [comment]
[https://github.com/EtchUK/Etch.OrchardCore.Search](Search module)

**Comment by dodyg** [comment]
Is this the correct way of implementing a site search?

1. Create Lucene Index
2. Create a liquid page. Use JavasScript to call (https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Lucene/)
3. Show results

**Comment by Skrypt** [comment]
There are many ways to achieve this and using javascript directly to make a call to the Queries module API is one of them. Right now the only example I built is with a Razor template and a controller that builds it's Query parameters from a form post values. The params passed to a Query is a Dictionnary of string, object so you can pass pretty much anything you want.

There is also, I believe a search page already built for the frontend which shows another example of use. But for a custom search, yes you need to POST some data to the Query API and display the data returned from that query basically.

**Comment by sebastienros** [comment]
Create an index named "Search" and configure it with the type you want. Go on /search on the front end.

I assume we could also expose this search endpoint as an API. For more advanced scenarios, the Lucene Queries will need to be used.

**Comment by dodyg** [comment]
I got 401 error when try to post to `api/lucene/content`. Is there any settings that I need to modify to enable this endpoint to be accessible publicly?

![search-api](https://user-images.githubusercontent.com/1761249/71781063-f6e40e00-2fd2-11ea-8287-27817791aecf.png)

**Comment by dodyg** [comment]
Also on GET

![search-api-get](https://user-images.githubusercontent.com/1761249/71781249-23992500-2fd5-11ea-9c8b-26dac5e15a56.png)

**Comment by dodyg** [comment]
> Create an index named "Search" and configure it with the type you want. Go on /search on the front end.

@sebastienros 

'/search' shows

![search-page](https://user-images.githubusercontent.com/1761249/71781366-9d7dde00-2fd6-11ea-9d8f-73ed0ab2f8a8.png)

**Comment by sebastienros** [comment]
@dodyg For the api, have you checked the permissions for the currently logged user? But we might have a regression also with authentication on api controllers.

**Comment by dodyg** [comment]
I need to implement a custom public search page so there is no logged in user.

**Comment by Skrypt** [comment]
Yes I confirm there is a regression on the /search page which returns a 505 error. When working with my latest PR for fixing the seach views I need to login to get this page to show. It is a regression from the latest changes on admin routes.

**Comment by deanmarcussen** [comment]
@Skrypt I think there is no routing regression here.

but by default the anonymous user does not have permissions to reach the search page.

![search](https://user-images.githubusercontent.com/13782679/72267340-d0982100-3617-11ea-8429-4d0f63644dde.PNG)

when I enable that it doesn't have a permissions error with anonymous.

maybe that anonymous permission needs to be on by default, or in the recipes for you working on in your PR?

**Comment by sebastienros** [comment]
Agreed with @deanmarcussen , the "Query lucene search" is the permission we are checking. Not sure it should have it on anonymous by default though. Looking at the code we can pass any index to this controller.

I think we should have some dynamic settings to clone this permission for each index. The recipe could set it to true for anonymous/search.

**Comment by Skrypt** [comment]
I worked last night on my PR and after merging latest dev the issue is gone.

**Comment by sebastienros** [comment]
TODO: the dynamic permissions, but if the index is the default one maybe allow it on the search page for anonymous users.
