### ISSUE TITLE
Resource Manifest bootstrap shouldn't be RTL generated

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4158]
The bootstrap and codemirror files in `OrchardCore.Resources` are generated RTL

This doesn't work as soon as you put a site into production as both these files also have a CDN value, and the CDN supplied version will not be RTL.

I think bootstrap probably should not be generated RTL. For the admin we import bootstrap as sass and RTL it there. Bootstrap in the resource manifest is only there for front end themes. If someone wants RTL they should generate it themselves from the bootstrap sass. We shouldn't be shipping an adulterated version of bootstrap and calling it bootstrap.

Codemirror I think is the same, it is built into the admin theme

cc @hishamco

**Comment by hishamco** [comment]
@deanmarcussen RTL is supported into many things bootstrap, Codemirror, trumbowysiwyg .. etc, but when these are using CDN it will break what we did before

Perhaps we need to think deeply about this to support RTL for both development & production environments

**Comment by deanmarcussen** [comment]
Let me try and clarify for you @hishamco because I think it help your understanding of how / where the resources are generated.

In Resources we define a bunch of `ResourceManifest` including bootstrap and codemirror.

These are **unused** by anything in the admin theme.
The admin theme imports bootstrap and codemirror independently in **it's own sass** and generates it's rtl because of the gulptask you wrote.

The Resources manifests are there for use in themes by using `style asp-name="bootstrap"` or a `depends-on` statement. 

The resource manifests should deliver what they say they are. bootstrap and codemirror. if someone wants a bootstrap-rtl they should generate it. Or if we really want to provide it we should define it as a manifest `bootstrap-rtl` and generate it as a file without a cdn reference.

Note I'm only talking about boostrap and codemirror. trumbow... and the bootstrap-slider etc which are in Resources but do not have a manifest definition are no issue.

Does that make sense?

**Comment by hishamco** [comment]
I got what you mean, let us hear @sebastienros thoughts about this one

**Comment by sebastienros** [comment]
Makes sense if done as described. Action is to remove RTL transformations Bootstrap from the resource module. The admin is using it's own copy which is fine to have RTL transformations applied to it.

Also agreed that if we generate a file from a known source, with rtl tranformation, then this asset should be named foo-rtl to prevent confusion. But I don't we will need this based on your comments.

**Comment by hishamco** [comment]
> Action is to remove RTL transformations Bootstrap from the resource module. The admin is using it's own copy which is fine to have RTL transformations applied to it.

Sounds good, but I need to revise my old RTL PRs to avoid UI issues

> Also agreed that if we generate a file from a known source, with rtl tranformation, then this asset should be named foo-rtl to prevent confusion. But I don't we will need this based on your comments.

If you remember I suggested that at the beginning but you insist to make one file :) anyhow I don't think it's an issue if we leave everything as its, but we should rethink about RTL with CDN

**Comment by sebastienros** [comment]
> If you remember I suggested that at the beginning but you insist to make one file

Then you haven't understood the action to take

What I understand from Dean is that for THIS file the RTL attributes are not necessary. There will still be one file. Just without any rtl variation inside it.

**Comment by hishamco** [comment]
What I understand from Dean is that we don't need to touch `bootstrap`, instead we can create a new one say `bootstrap-rtl`

**Comment by sebastienros** [comment]
No, that's not what "I think" he said. He's suggesting that the bootstrap file from the ResourceManager module should not have the RTL step applied to it, because this file is only used on the front-end themes. He says that the bootstrap file we use is already bundled in the admin.css file we generate.

Waht he suggested is that if one day, in the future, maybe, if some customer really need a BS with rtl file their themes, then they should generate a second file. But not us, not now.

**Comment by hishamco** [comment]
Got it
