### ISSUE TITLE
Wrong localization technique

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#4162]
~~https://github.com/OrchardCMS/OrchardCore/pull/2192/files#diff-ea4a2f43bc79cd708a28cb0b6a64d9e6R5~~

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ReCaptcha/Views/Items/ReCaptchaPart.Fields.Edit.cshtml

**Comment by hishamco** [comment]
Could you please elaborate?

**Comment by sebastienros** [comment]
It's doing a `T` on variables.

**Comment by hishamco** [comment]
How this could happen? we didn't support dynamic translation yet, Am I right?

**Comment by sebastienros** [comment]
This link is better to understand the issue:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ReCaptcha/Views/Items/ReCaptchaPart.Fields.Edit.cshtml

**Comment by MatthijsKrempel** [comment]
Fixed in; https://github.com/OrchardCMS/OrchardCore/pull/4159

**Comment by sebastienros** [comment]
TODO: I will finalize the PR https://github.com/OrchardCMS/OrchardCore/pull/4159

**Comment by hishamco** [comment]
I can finalize this if you have priority on other once
