### ISSUE TITLE
Any way to set Base url for admin UI?

### ISSUE THREAD

**Issue by xumix** [OrchardCMS/OrchardCore#4163]
I'm hosting orchard behind nginx as reverse proxy, so my admin url looks like http://site.name/cms/admin. How do I setup Orchard to actually work behind this url?
At the moment I'm redirected to http://site.name/Login.aspx which is abviously not present there.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2779

**Comment by hishamco** [comment]
This could be set from settings instead of use "Admin"

**Comment by xumix** [comment]
> 
> 
> #2779
@sebastienros @hishamco 
This is not exactly the problem I'm facing.
The problem is this: my orchard is hosted internally at `/` but it has external access as `/cms`
so I want all the URLs be relative to `/cms`
