### ISSUE TITLE
Change Admin Theme

### ISSUE THREAD

**Issue by mochirfan** [OrchardCMS/OrchardCore#4165]
How to change Admin Theme in Orchard Core ?

**Comment by hishamco** [comment]
You can modify The Admin theme or create a new one, after that you can simply change it from Themes menu in the admin section

**Comment by deanmarcussen** [comment]
@mochirfan To create a new admin theme you need to set some things in the manifest for the theme, so it is recognised as an admin theme.

For example (also uses the existing admin theme as a base theme). Note the Tags array which is how Orchard Core knows you registering an admin theme.

```
[assembly: Theme(
    Name = "ThisNetWorks Admin Theme",
    Author = "ThisNetWorks",
    Website = "http://www.theappspajamas.com",
    Version = "1.0.0",
    Description = "Custom admin theme from ThisNetWorks",
    BaseTheme = "TheAdmin",
    Tags = new[] { "admin" }
)]
```

Then you need to `Enable` the theme and `Set as active` in the theme admin area. (It is not currently very clear in the ui, but this is how the process works)

Sample (WIP) custom theme is here
https://github.com/ThisNetWorks/ThisNetWorks.OrchardCore.Themes/tree/develop

**Comment by hishamco** [comment]
FYI have a look to the docs https://orchardcore.readthedocs.io/en/dev/docs/getting-started/theme/
