### ISSUE TITLE
WidgetsListPart - Existing widgets are removed after adding new widget using Insert Widget(+) option

### ISSUE THREAD

**Issue by sivakumar715** [OrchardCMS/OrchardCore#4168]
**Issue:**  WidgetsListPart - Existing widgets are removed after adding new widget using Insert Widget(+) option

**Steps to reproduce:**

-  Create a new content type **TestType** with **WidgetsList** part.
-  Create few custom widgets (content type with Stereotype as Widget). Seg., TestWidget1,TestWidget2,TestWidget3 etc.,
-  Create a content item of type **TestType**
-  In that content item, add the above widgets using **Add Widget** option and publish.
-  Edit the above content item, add custom widget (say CustomWidget1) just after **TestWidget1** using **Insert Widget (+)** option which at top right corner of each widget and publish.
-  Browse the content item, you could see only one widget (TestWidget1) and remaing widgets(along with CustomWidget1) gets deleted automatically.

![image](https://user-images.githubusercontent.com/54092242/64322182-b4d49c80-cfdf-11e9-8c15-746083f9572e.png)

**Comment by jtkech** [comment]
Yes, i can repro with the insert button, it works with the add button.

**Comment by ns8482e** [comment]
The Zone info is missing for insert drop-down  when loaded from data store. 
I can work on it will create PR

**Comment by sebastienros** [comment]
Please do a PR for sure

**Comment by ns8482e** [comment]
This is simple fix to assign Zone in  WidgetsListPart.Edit.cshtml.

The part Widgets are removed and re-inserted in "UpdateAsync" of "WidgetsListPartDisplay". When it encounters Zone being null throws exception.

However, this leads to another important question at architecture level, why the null exception at Part update was not notified to parent Content Item update and the calling controller ? 

The controller should receive an exception so it should take fail action and should stop updating the database.

**Comment by sebastienros** [comment]
Please file another issue for your last comment, giving an example on how to trigger this issue.
