### ISSUE TITLE
Should Content Author be set during CreatingAsync?

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4170]
When creating content during a workflow, the Author property of a ContentItem is not set properly. which leads to the "By" field being blank in the ContentItem list.
![image](https://user-images.githubusercontent.com/4681586/64343569-c0fa3300-cfba-11e9-9653-7bee852e7f95.png)

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement/Handlers/ContentsHandler.cs#L30&L45

**Comment by Piedone** [comment]
`Author` is now set during `CreatingAsync()`.
