### ISSUE TITLE
404 page in Agency theme has style issue

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4174]
Steps to reproduce:

1. Create new Site with Agency Theme
2. Visit `https://localhost:5001//Admin`

the page will look like

![NotFound](https://user-images.githubusercontent.com/3237266/64425423-55948c00-d0b4-11e9-8453-3d2eecbc66e6.png)

**Comment by choXberg** [comment]
![agency-404](https://user-images.githubusercontent.com/836852/66269117-ef329300-e844-11e9-929a-7a96efa91d44.png)
