### ISSUE TITLE
SQL query: how to join two Content Types and return all data fields?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#4185]
I configured two Content Types: T1 and T2

T1 has a lookup filed to T2 via a Content Picker; so that users can select a T2 record from a T1 record.  It works perfectly.

However,  when doing SQL query, I need to join T1 and T2 together and bring all columns from T1 and T2. But I found that in T1, there is a "**Content**" column contains all data fields in JSON format, the reference to T2 is like this:

`,"T2Lookup":{"T2":{"ContentItemIds":["4hnq001ertvmq1wyhgnd9bkpch"]}}`

So how to join these two Content Types (T1 and T2) together and return all data fields?

Thanks!

**Comment by orchardc** [comment]
Solution found, use json_extract() function works fine!

**Comment by jptissot** [comment]
You might want to chck the content field indexing fr skrypt
