### ISSUE TITLE
Settings menu subitems should all be sorted alphabetically

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4188]
I was wondering why the https settings always appear first, when they have a sort order of `100` 

![settings-order](https://user-images.githubusercontent.com/13782679/64476451-9a88f300-d186-11e9-9c7e-9d93d44439b6.PNG)

But it is because everything else uses alphabetical sort eg
```
                .Add(T["Configuration"], configuration => configuration
                    .Add(T["Settings"], settings => settings
                       .Add(T["Smtp"], T["Smtp"], entry => entry
```

Except https and Reverse Proxy

**Comment by Skrypt** [comment]
I did reorder settings in #3809 please take a look and do a commit on top of that branch if there is something.

**Comment by deanmarcussen** [comment]
@Skrypt Cool, had a look at #3809 all good with me. 
This was only a couple of settings on the Settings submenu items.

But your top level menu changes are another good option for my suggestion on https://github.com/OrchardCMS/OrchardCore/issues/4190

See what you think maybe alphabetical is good / maybe just the right numbering as you have done is easier (and less changes!)

**Comment by Skrypt** [comment]
I think we should try to keep the most used ones on top for this menu. Things like Templates, Queries are sections that are susceptible of needing to go in back and forth quite a lot ... at least that I found for my usage. I've tried to rearrange the order with that in mind. We could drop a screenshot here of what I've done in that PR and decide if we want to change the order of some of them still. Let me know.

**Comment by deanmarcussen** [comment]
Cool, yeah I only opened the other issue because I was looking to put a top level menu item in, and was like, oh, they're all set at 1, this is a bit random.

Also agree that an actual order is better than alphabetical, Settings, would just be weird being at the top.
