### ISSUE TITLE
Sort Configuration Menu Items Alphabetically

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4190]
The menu items under `Configuration` are all in rather random order.

They use `1`, sometimes `1.51 for a sort order often, so appear based on module load order.

![config-sort-order](https://user-images.githubusercontent.com/13782679/64476589-42eb8700-d188-11e9-8a58-b9228c919e97.PNG)

Propose we keep `Settings` at `1` so it always stays at the top and move the rest to alphabetical sort orders `T[General]`

**Comment by hishamco** [comment]
@deanmarcussen could you please fix this one as same as #4188

**Comment by deanmarcussen** [comment]
Alternative (probably better) solution in https://github.com/OrchardCMS/OrchardCore/pull/3809
