### ISSUE TITLE
Admin menu not usable in IE

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4195]
Using IE 11, the Admin menu cannot be expanded.

**Comment by Skrypt** [comment]
You can try by adding this line on your Layout template : 

```
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

**Comment by Skrypt** [comment]
https://stackoverflow.com/questions/27678052/usage-of-the-backtick-character-in-javascript/27678299#27678299
