### ISSUE TITLE
Content Items mobile UI issues

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4198]
This include:
- Select All check box
- Resize Select All & Bulk Actions drop down

![ContentItems](https://user-images.githubusercontent.com/3237266/64488210-d5a22980-d24d-11e9-92d6-404f95f0ae2a.png)

**Comment by sebastienros** [comment]
Is the screenshot showing the issue or the solution?

**Comment by hishamco** [comment]
It shows the issue, I attach the screenshot after in every PR

**Comment by agriffard** [comment]
Fixed by #4359
