### ISSUE TITLE
Nuget Package for OrchardCore.ContentLocalization?

### ISSUE THREAD

**Issue by rthm93** [OrchardCMS/OrchardCore#4199]
I would like to implement `ContentCulturePicker` in my app, based on the [documentation](https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.ContentLocalization/), I need to enable `OrchardCore.Localization` module, but I dont seem to be able to find the nuget package for this module. 

Is my only option cloning this repo and add project reference to `OrchardCore.ContentLocalization` project? 

I have implemented [localization](https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Localization/) and it is working as I have expected when I access the site with `https://localhost:44377/?culture=zh-cn`, but I do not prefer to have the culture displayed in URL. Can I set the culture to a cookie instead?

**Comment by deanmarcussen** [comment]
Which version of Orchard Core nuget have you installed?

The beta3 on NuGet does not have content localization in it I think

So you have to use the myget feed https://orchardcore.readthedocs.io/en/dev/docs/getting-started/

I think the culture is based on your browser settings

**Comment by rthm93** [comment]
I am currently using this beta 3 `1.0.0-beta3-71077`. 
Hmm... AFAIK it is supposed to be passed to the server in request headers either via headers, uri or cookies, I will try to find out more on this

**Comment by rthm93** [comment]
Finally manage to find it, you could [set the culture of the request with cookie](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#cookierequestcultureprovider). 

Are there any plans to create a nuget package for `OrchardCore.ContentLocalization`?

**Comment by deanmarcussen** [comment]
See previous comment and link you need to use the dev myget feed
