### ISSUE TITLE
How to refer in a workflow a file uploaded through a created content 

### ISSUE THREAD

**Issue by jiangweiatgithub** [OrchardCMS/OrchardCore#4200]
Hi,

I am new to Orachard Core.  And I hope my first issue, or rather, a usage quesiton is not repeating an exisiting one. Here it is -

I created a new content type and I was successful in uploading a file by publishing, but how can I refer to this file's location on the disk in a task triggered by "content published" event in a workflow?

Thanks,
Wei

**Comment by jiangweiatgithub** [comment]
It seems that I am repeating this legacy issue:
https://github.com/OrchardCMS/OrchardCore/issues/2240

**Comment by hyzx86** [comment]
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Media/

**Comment by jiangweiatgithub** [comment]
> https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Media/

Thanks, but, how can I make any reference from the "workflow" environment?

**Comment by hyzx86** [comment]
你不是创建了一个ContentItem 么?
直接拿来用就好了啊，具体的用法我给的链接上有的啊
你是不知道怎么获取这个ContentItem？

**Comment by hyzx86** [comment]
你的媒体文件应该保存在 站点数据文件夹里面，如果要获取物理路径地址，可以直接拼接一个站点根目录

**Comment by jiangweiatgithub** [comment]
> 你不是创建了一个ContentItem 么?
> 直接拿来用就好了啊，具体的用法我给的链接上有的啊
> 你是不知道怎么获取这个ContentItem？

还不是。具体是这样的，我定制了一个Content类型，用户通过它，按“Publish”提交一个或多个文件，以及其他字段信息。我在Contentl列表里，可以看到相应的Content，并且看到这些文件被被保存到Asset文件夹下的某个自动生成的目录下。我现在想做的是，做个Workfllow，在"Content Published”事件触发后，通过Liquid表达式解析相关的信息以及文件位置，进行处理，然后把处理结果返给用户。现在就卡在了“Liquid表达式解析相关的信息以及文件位置”这一步。

**Comment by hyzx86** [comment]
Lquid 没办法直接解析文件吧？你要自己实现一个Activity

**Comment by jiangweiatgithub** [comment]
对的，就是在事件激发后，用Activity进行处理，比如通过Liquid表达式，将相应信息插如PPOST命令中，调用另一个服务器上的相应处理机制。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Tony Han <notifications@github.com>
发送时间: Monday, September 9, 2019 9:48:23 PM
收件人: OrchardCMS/OrchardCore <OrchardCore@noreply.github.com>
抄送: jiangweiatgithub <polytrans2000@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [OrchardCMS/OrchardCore] How to refer in a workflow a file uploaded thourgh a created content (#4200)


Lquid 没办法直接解析文件吧？你要自己实现一个Activity

―

**Comment by jiangweiatgithub** [comment]
对，不同的用户提交一个或多个 content，我需要相关信息对应起来。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Tony Han <notifications@github.com>
发送时间: Monday, September 9, 2019 9:42:02 PM
收件人: OrchardCMS/OrchardCore <OrchardCore@noreply.github.com>
抄送: jiangweiatgithub <polytrans2000@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [OrchardCMS/OrchardCore] How to refer in a workflow a file uploaded thourgh a created content (#4200)


你的媒体文件应该保存在 站点数据文件夹里面，如果要获取物理路径地址，可以直接拼接一个站点根目录

―

**Comment by sebastienros** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6027
