### ISSUE TITLE
Content Picker field in Widget

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#4222]
Hi guys, 

I have created a lot of Widget with a content picker field. 

For all this items, when I try to add a widget in a page, the content picker field is not shown until I save the page.

I think the problem come out from the fact that the field load items by javascript code...I don't know if there is some "right fix" for that but a workaround can be a first loading of Content Types in the Edit function of ContentPickerFieldDisplayDriver class.

**Comment by Skrypt** [comment]
hmmm strange one. But yes @jptissot changed the js scripts recently but maybe not related at all.

**Comment by jptissot** [comment]
I will try to repro.

**Comment by jptissot** [comment]
Problem is that I only initialize them on load. 
I broke this by removing the init function from the html and putting it all in the script. I forgot that widgets added dynamically needed to trigger the picker init script again.

**Comment by PiemP** [comment]
Sorry guys, 

this issue persist on dev branch.

**Comment by jptissot** [comment]
I tested it and it worked for me. Do you have repro steps?

**Comment by PiemP** [comment]
@jptissot you work on windows 10?

[4222.zip](https://github.com/OrchardCMS/OrchardCore/files/3609940/4222.zip)

Hope it can be more clear than me but I try to explain it by words.

I have created a Widget with a content picker field and, when I add it to a Page, the widget doesn't load the content picker field (doesn't load the content item list). If I save the page, the widget load the content item list correctly.

**Comment by jptissot** [comment]
Yes, I tested this using window 10. 
Hmm I just tried again with a fresh version of latest dev and it works fine in a widget.

If you are targeting the right version ? If you want the latest dev version that has DotnetCore 2.2 support, please use the version 1.0.0-beta3-72452 that is available on myget.

You might also need to force refresh your js (ctrl+f5)

**Comment by PiemP** [comment]
@jptissot I'm sorry (my written english lack a lot), the question about windows 10 is for the content of the zip package that I think it's work only under windows OS.

When I solve a strange issue with the recipe of my theme I try to test it another time. I'm on dev branch. Thanks

**Comment by PiemP** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️

damn cache! Sorry @jptissot my fault
