### ISSUE TITLE
Workflow Activity Double click issue

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4227]
I accidentally double clicked the add button when adding an activity to the workflow and it added the activity twice with the same ID, causing the UI to throw an exception, even after reloading the site. I had to go into the database document and remove the duplicate entry for the UI to unblock. Maybe we should disable the button on click.

**Comment by sebastienros** [comment]
I am thinking on a feature in the admin.js file that would automatically disable a form button, or link that morphes to a post,. We have this already in O1.

**Comment by tropcicstefan** [comment]
Would you like me to put O1 version in, like @Skrypt referenced...

```  
//Prevent multi submissions on forms
    $("body").on("submit", "form.no-multisubmit", function (e) {
        var submittingClass = "submitting";
        form = $(this);

        if (form.hasClass(submittingClass)) {
            e.preventDefault();
            return;
        }

        form.addClass(submittingClass);

        // safety-nest in case the form didn't refresh the page
        setTimeout(function () {
            form.removeClass(submittingClass);
        }, 5000);
    });
```

Or maybe change it into something like 
```$("body").on("submit", "form[method='post']", function (e) {```

**Comment by deanmarcussen** [comment]
> Would you like me to put O1 version in, like @Skrypt referenced...

yes please thank you

**Comment by weirdyang** [comment]
Can this be solved using lodash denounce method?

**Comment by Skrypt** [comment]
Yes, please contribute 😄
