### ISSUE TITLE
input control alignment in RTL is wrong

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4229]
![Capture](https://user-images.githubusercontent.com/24512878/64568047-07081b80-d35a-11e9-9c2d-78634f1c5ef3.JPG)

in RTL  the input value is aligned to left, it should be right-aligned.

**Comment by hishamco** [comment]
@aghili371 isn't working before?

**Comment by aghili371** [comment]
was RTL before new updates

**Comment by hishamco** [comment]
@deanmarcussen @jptissot seems one of your changes break the RTL work that I did before, could please your changes before I do it again

**Comment by sebastienros** [comment]
@deanmarcussen 🤦‍♂

**Comment by deanmarcussen** [comment]
No @hishamco you break this one :)

See your PR https://github.com/OrchardCMS/OrchardCore/pull/4039

Editor direction is being set to left on some fields when using an rtl langauge 

![oc-rtl](https://user-images.githubusercontent.com/13782679/64758157-c19b4800-d52b-11e9-8cc0-81a10858e6c9.PNG)

**Comment by deanmarcussen** [comment]
```
    public class CultureAspect
    {
        private static readonly CultureInfo _defaultCulture = CultureInfo.InstalledUICulture ?? CultureInfo.InvariantCulture;

        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        public CultureInfo Culture { get; set; } = CultureInfo.InstalledUICulture ?? CultureInfo.InvariantCulture;
    }
```

This is returning en-US even when there is only one language set in localization.

Also I don't think you can use a static here as it will be set to the default of the host, for every tenant, that running under the host.
