### ISSUE TITLE
Appsettings inheritance is not working for Azure Media settings

### ISSUE THREAD

**Issue by jxt-seth** [OrchardCMS/OrchardCore#4233]
In the base appsettings.json I put the base Azure media settings like so:
```
{
  "OrchardCore": {
    "OrchardCore.Media.Azure": {
      "ConnectionString":  "<!-- shared connection string -->",
      "ContainerName": "default",
      "BasePath": "media"
    }
  }
}
```
The plan was to override the container name for each tenant using the tenants appsettings.json like so:
```
{
  "OrchardCore": {
    "OrchardCore.Media.Azure": {
      "ContainerName": "Tenant1"
    }
  }
}
```
This didn't work so I tried this in the tenants appsettings.json:
```
{
  "OrchardCore": {

    "Tenant1": {
    "OrchardCore.Media.Azure": {
      "ContainerName": "Tenant1"
    }
  }
  }
}
```
This also didn't work so I tried the following in the base appsettings.json with no luck either:
```
{
  "OrchardCore": {
    "OrchardCore.Media.Azure": {
      "ConnectionString":  "<!-- shared connection string -->",
      "ContainerName": "default",
      "BasePath": "media"
    },
"Tenant1": {
    "OrchardCore.Media.Azure": {
      "ContainerName": "Tenant1"
    }
  }
}
```
For some reason the appsettings override functionality don't seem to be working for Azure Media as mentioned here: https://orcharddojo.net/blog/this-week-in-orchard-01-11-2019

**Comment by jxt-seth** [comment]
@deanmarcussen - otherwise you Azure resizing enhancements are awesomeness.

**Comment by scleaver** [comment]
@deanmarcussen - otherwise you Azure resizing enhancements are awesomeness.

**Comment by deanmarcussen** [comment]
Cool, cheers guys. Always a few teething problems :)

Ok, I look at your config. Check the docs for overrides here https://orchardcore.readthedocs.io/en/dev/OrchardCore/OrchardCore/Environment/Shell/

This should work, but I think you have the sections wrong. 

Tenants appsettings (if you mean `App_Data\Sites\Tenant1\appsettings.json` should be without the `OrchardCore` section, so like this
```
{
    "OrchardCore.Media.Azure": {
      "ContainerName": "Tenant1"
    }
}
```

To do the override in the main `appsettings.json` you need to include the tenant state so it is recognised as a tenant related setting.

```
{
  "OrchardCore": {
    "OrchardCore.Media.Azure": {
      "ConnectionString":  "<!-- shared connection string -->",
      "ContainerName": "default",
      "BasePath": "media"
    },
"Tenant1": {
     "State": "Placeholder",
    "OrchardCore.Media.Azure": {
      "ContainerName": "Tenant1"
    }
  }
}
```

**Comment by scleaver** [comment]
ha ha "guys" it was the same guy just two different accounts :D

**Comment by scleaver** [comment]
Oh thanks @deanmarcussen - let me test this. I followed the Lombiq dojo instruction which said "The other way is to define this in the appsettings.json file of the tenant (under App_Data/Sites/Default) **in the same format**." I will test!

**Comment by jxt-seth** [comment]
Thanks for your help Dean. Removing the OrchardCore node form the tenants app settings worked.

**Comment by scleaver** [comment]
Thanks for your help Dean. Removing the OrchardCore node form the tenants app settings worked - user error!
