### ISSUE TITLE
Improve ImageSharp no-op and handling

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4234]
Great to see the new ImageSharp version in @lahma 

Will you be doing any perf tests against it again?

There are some logic changes that were made to ImageSharp that could, if we tweaked a couple of settings, improve the no-op for Orchard.

But they are probably only worth doing if the command parser is still a performance bottle neck?

Note: There are some other changes we need to make regardless of perf, but nothing that is super important, as it all still works.

- We can remove our code to check if there are no commands, as ImageSharp will know handle that.
- Move request path matching to the IsMatch method is recommended

**Comment by lahma** [comment]
@deanmarcussen I can run profiling against the agency and blog templates as I don't have any my own production site to test against. They were enough to reveal the optimization opportunities for IS.Web, but if you have any pointers for larger test data I'd happily test that too.

**Comment by deanmarcussen** [comment]
@lahma that would be great thanks.

I think the blog template would be the best, as this would only be a worthwhile optimisation if the ImageSharp middleware still revealed a lot of good reasons to try and optimize further, and it would be only for no-op requests, which the blog is best suited for.

I imagine you will know pretty quickly based on your last pref tests if the improvements you have already done are enough.

Thanks

**Comment by lahma** [comment]
@deanmarcussen I did a quick sweep and didn't find anything super alarming when testing the blog template. I created https://github.com/OrchardCMS/OrchardCore/pull/4251 to show some things.

**Comment by lahma** [comment]
OK, looked at [ResourceManager]( https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ResourceManagement/ResourceManager.cs) , I think we could do better. `ResourceManager.FindResource` shows some slowness.

But again, not really related to ImageSharp 😃

**Comment by deanmarcussen** [comment]
Thanks @lahma appreciate your input. Very interesting reading your pr and comments.

I'll put another pr in separately to deal with the recommended logic changes and removal of some other code we don't need anymore :)
