### ISSUE TITLE
Import Deployment Package throws an exception when the imported is not zip file

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4235]

**Comment by DannyT** [comment]
Just to add to this, I would say error handling on imports probably needs some general love. Importing media files that aren't included in the zip will also throw a FileNotFoundException (which is correct, but should be elegantly handled).

**Comment by hishamco** [comment]
Thanks for adding your notes

**Comment by sebastienros** [comment]
So the solution is to add better error messages when an import fails.

**Comment by jptissot** [comment]
Would it be useful to also be able to import recipes directly ?
