### ISSUE TITLE
Add more search filters in Users page

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4243]
This including:
- Order by: Name, Email, Creation Date, Last Login
- Filter by: All, Approved, Pending

**Comment by agriffard** [comment]
To Order and Filter the users, we need the corresponding fields in the UserIndex.

For the moment. I had to comment them in the Users UI.

/cc @Skrypt

**Comment by jptissot** [comment]
The user search is broken. I have a manager user and a search for manager returns nothing.

**Comment by Skrypt** [comment]
Works for me. Please open a different issue with repro or logs.
