### ISSUE TITLE
Configuration / Settings / General / Default Culture add indicator that restart is required

### ISSUE THREAD

**Issue by surfmuggle** [OrchardCMS/OrchardCore#4246]
On try.orchard.fr i noticed that setting / changing the default culture requires a restart. 

![Configuration_Settings_General_Add_Culture_02](https://user-images.githubusercontent.com/1271555/64657024-e14e4580-d431-11e9-9fd1-5ff1f6ea429d.png)

On the overview page it would be ideal if there was an indicator that the restart still has to take place for the setting to work

![Configuration_Settings_General_03_new_Default_Culture](https://user-images.githubusercontent.com/1271555/64657062-004cd780-d432-11e9-81da-2007e2072700.png)

This is just a minor ui-tweak but hopefully a usefull one. 

@agriffard Thanks for setting up the page.

**Comment by hishamco** [comment]
Seems the version little bit old, we changed many things, General Settings now is look like:
![Settings](https://user-images.githubusercontent.com/3237266/64663147-8cbbc200-d453-11e9-805e-44ea67254339.png)

@agriffard seems we need to update the try.orchard.fr
