### ISSUE TITLE
Razor class library project as Module Target doesn't work

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4247]
I have created Razor class library project  "RazorUIClassLib" as per following link

https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio

and I can access the Page using url /MyFeature/Page1

After that I added Nuget reference of "OrchardCore.Module.Targets" to "RazorUIClassLib" project and converted it into OrchardCore Module and referenced the project in "OrchardCore.Cms.Web"

I can see the Module listed in "Features" in admin section and I can enable it.

However when enabled, The Page1 doesn't show up with either
Url  "/MyFeature/Page1" or "/RazorUIClassLib/MyFeature/Page1"

Am I missing anything?

**Comment by jtkech** [comment]
In OrchardCore a module is an area under the virtual folder `Areas/MyModule`, so your pages need to be under `Areas/MyModule/Pages`, physically under your module project `Pages` folder. And a module can't define sub areas.

A module has at least one feature, the main one, and can have additional features, a controller can be tied to a given feature, but not a razor page defined in a module, they all belong to the module.

In the docs when there are saying `MyFeature` and give the following path

    RazorUIClassLib\Areas\MyFeature\Pages\Shared\_Message.cshtml

So that, when referencing the RCL, the result is as you define the following in your app.

    MyApp\Areas\MyFeature\Pages\Shared\_Message.cshtml

Here, when referencing a module, the analogy would be

    MyApp\Areas\MyModule\Pages\Shared\_Message.cshtml

**Comment by ns8482e** [comment]
> In OrchardCore a module is an area under the virtual folder `Areas/MyModule`, so your pages need to be under `Areas/MyModule/Pages`, physically under your module project `Pages` folder. And a module can't define sub areas.

Similar to example in doc, the module has Pages are under "Aears/MyFeature/Pages

> 
> A module has at least one feature, the main one, and can have additional features, a controller can be tied to a given feature, but not a razor page defined in a module, they all belong to the module.
> 

Module is the the only Feature in Orchard Core.

That means Razor class library into Orchard Core module, I need to move files physically form "Areas\MyFeature" to Root of the module and delete the folder "Areas\MyFeature" so that OrchardCore Module can add "Areas" virtually?

I expected that  just adding reference of "OrchardCore.Module.Targets" the project would become compatible with orchardcore and I could package it and utilize as both as Razor library as well as Orchard Module for ASP.NET CORE MVC applications

**Comment by ns8482e** [comment]
Even when I decide not to use "OrchardCore.Module.Targets" and use it as RCL library directly on "OrchardCore.Cms.Web" I can't  access the Page using url /MyFeature/Page1 

If I create "Areas\MyFeature\Page1" within "OrchardCore.Cms.Web" that also doesn't work

**Comment by jtkech** [comment]
Yes, i understand what you mean.

But this aspect of modularity has been introduced by orchard before RCL ;)

I will think about making it compatible. Would be as easy (or not harder) than making it working when adding pages under the Application `Areas` folder. One of the current problems is that this folder is already managed as a virtual folder under which reside all modules.

**Comment by Piedone** [comment]
This doesn't seem to be a feature requested by many people, so I'll close now. Please reopen if you'd work on it as a contribution.
