### ISSUE TITLE
Unable to resolve service for type 'Microsoft.AspNetCore.Http.Features.IFeatureCollection' 

### ISSUE THREAD

**Issue by liugt34** [OrchardCMS/OrchardCore#4248]
when i inject the IFeatureCollection in a Module class, it meet this error? but when i run it in  the sample it worked well, i have not  see an DI of IFeatureCollection in the sample code, so how can i do?need help?

**Comment by infofromca** [comment]
search whole code for IFeatureCollection

**Comment by liugt34** [comment]
i've resove it by sending the app.ServiceFeature in UseMiddleWare @infofromca
