### ISSUE TITLE
Multi-tenant request log level

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#4249]
https://github.com/OrchardCMS/OrchardCore/blob/d1c9b264bf56c42a120159dbc9cf61a66f9645c8/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs#L45

I think this should be the debug level, because there are too many useless records in the log when the info level is turned on.

**Comment by hishamco** [comment]
Agree

**Comment by Piedone** [comment]
According to the [official docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=net-8.0#fields):

- Debug: "Logs that are used for interactive investigation during development. These logs should primarily contain information useful for debugging and have no long-term value."
- Info: "Logs that track the general flow of the application. These logs should have long-term value."

Up to interpretation :). But on a more serious note, the usual practical difference is that Info contains general information about what's happening, while Debug also contains information about the state of the application and inputs of the feature.

E.g., for a login feature, Info would be something like "User logged in." (what [we actually do](https://github.com/OrchardCMS/OrchardCore/blob/bcf2150114719ea0cd89068cc4eec742b611029c/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AccountController.cs#L201)), and Debug "User Piedone logged in by using the username-password authentication option."

So, I think Info there is appropriate. You can configure log levels for individual loggers (i.e. consumer classes like `ModularTenantRouterMiddleware`) from e.g. the appsettings file if it's too verbose for you (but Info is meant to be verbose).

Please reopen if you disagree.
