### ISSUE TITLE
Search: recipe, index, admin

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#425]
To be able to configure a Search index from a recipe, we need a SearchIndexRecipeStep, right?
- Create 'Search' index
- Search Settings : Default searched fields, Default searched fields

To be able to search content items in admin:
- Create 'Admin' index.
- Add filters in admin content search: By content type, By state (latest, published, draft), Order by.
- Allow ContentItem controller to search (same page) or implement it in a 'Admin Content Search' feature (other page) ?

**Comment by agriffard** [comment]
How will we implement search in admin?

**Comment by sebastienros** [comment]
Should be a custom feature, which creates its own index. Maybe with specific provider to automatically add content items to it.

**Comment by agriffard** [comment]
Could be closed when @Skrypt 's indexing and analyzers PRs are merged.

May be we should also add default Search settings in the recipe.

Some kind of Search form or widget would be great too in the Blog Theme (but a Search link could be enough).

Allow to Search in the admin, like in O1, could be postponed or explained in another issue.
