### ISSUE TITLE
edit content frizzing in chrome

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4253]
when i try to edit the content, the web site frizzing and i should refresh the page.

this problem just in chrome and i tested by Firefox, it works fine.

this problem happen in different laptops.

i think this issue become from last 2 weeks.

**Comment by sebastienros** [comment]
Can you provide some repro steps, or analyze the issue yourself?

**Comment by aghili371** [comment]
it looks has a loop or something like this in js files. I just tried to edit the content information. 

![1](https://user-images.githubusercontent.com/24512878/64735952-d820af80-d4e9-11e9-9f16-7e4693068e88.JPG)
![2](https://user-images.githubusercontent.com/24512878/64735953-d9ea7300-d4e9-11e9-9ca4-547d932f614b.JPG)

**Comment by sebastienros** [comment]
In the settings there is an option to force using debug versions of the scripts, which would help to see which line exactly is the issue.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
