### ISSUE TITLE
Alerts should be located in one place

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4256]
![alerts](https://user-images.githubusercontent.com/3237266/64777780-a77d5c00-d563-11e9-8963-6ec87ff46495.png)

**Comment by agriffard** [comment]
The difference is that the second one is always displayed as a warning before saving.

**Comment by hishamco** [comment]
Even thought, my issue was from UI perspective all the notification should be in one place, if you look to the attached image the alert was annoying
