### ISSUE TITLE
V2 migration and building parts, widgets

### ISSUE THREAD

**Issue by papyr** [OrchardCMS/OrchardCore#426]
A picture is worth a thousand words, there is a lot of text and complexity in the implementation. As the founders of orchard its easy for you, but to adopt and start its a whole different ball game!

When the documentation is created, **can you add a simple picture that shows how the parts are composed and rendered into the view/shapes.** 

This would clearly **help the developer follow and implement all the required dependencies and wireups needed to complete the part**. And to convert the part into a widget.

**Comment by Piedone** [comment]
We've added a lot of docs and [various tutorials](https://docs.orchardcore.net/en/latest/docs/resources/tutorials/) since then. Please reopen if still necessary.
