### ISSUE TITLE
CustomSettings - field not accesible from liquid

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#4265]
Hi guys, 

I've created a custom settings called ComuneData where i put some data by text/media fields.
When i try to display a field in my layout (es. {{ Site.Properties.ComuneData.logo.Paths[0] }} )  I can't see the value, but when i do something like this: 
```
{{ Site.Properties.ComuneData }}
```
I can see all the JSON object's data.

**Comment by hishamco** [comment]
Please write down the result of the JSON data

**Comment by PiemP** [comment]
```
{
  "ContentItemId": "49az4cq9kxgqz21n3n9p68335h",
  "ContentItemVersionId": null,
  "ContentType": "ComuneData",
  "DisplayText": "Dati del comune",
  "Latest": false,
  "Published": false,
  "ModifiedUtc": "2019-09-13T09:55:04.2621552Z",
  "PublishedUtc": null,
  "CreatedUtc": null,
  "Owner": null,
  "Author": "admin",
  "ComuneData": {
    "regione": {
      "Text": "lombardia"
    },
    "peculiarita": {
      "Text": "siamo il comune + bello d'Italia"
    },
    "indirizzo": {
      "Text": "Via le mà dal cùl"
    },
    "telefono": {
      "Text": "39048230984"
    },
    "fax": {
      "Text": "45374875438"
    },
    "logo": {
      "Paths": [
        "logo/thumbnail.jpg"
      ]
    },
    "regionelink": {
      "Url": null,
      "Text": null
    }
  },
  "TitlePart": {
    "Title": "Dati del comune"
  },
  "AliasPart": {
    "Alias": "site-data"
  }
}
```

**Comment by hishamco** [comment]
It should work, I tried something similar last week

@jtkech anything related after 3.0 update, which I don't think in particular

**Comment by jtkech** [comment]
Maybe a missing liquid access registration

    TemplateContext.GlobalMemberAccessStrategy.Register<NewTypeThatNeedsToBeAccessed>();

**Comment by PiemP** [comment]
The documentation doesn't talk about the necessity to have an object and register it in the Startup.cs.

I have declared the custom settings from a recipe, I don't have defined it by a class.

It's something bound to content fields and I need to use content parts to do that or it's necessary to write a custom module to define a custom settings and use it in a liquid template? 

Sorry guys, hope what I write is understandable and hope to be not rude (my written english lack a lot)

**Comment by deanmarcussen** [comment]
yes, you shouldn't need an extra liquid registration

I think your accessor should be
`{{ Site.Properties.ComuneData.ComuneData.logo.Paths[0] }}`

Because you have added a field directly to a content type, I think.

And content type fields are accessed through `ContentType.ContentType` as they are basically attached to a special fields part inside the content type.

**Comment by PiemP** [comment]
@deanmarcussen you are the man! I have forgot this behavior of the fields!

Thank you all and sorry.
