### ISSUE TITLE
Disable Feature popup

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4270]
When you disable a feature that has dependencies, they are displayed like this:

![image](https://user-images.githubusercontent.com/703248/64865421-85eea400-d639-11e9-9c54-ac9539884129.png)

Would it be possible to display them a better way, for example with a new line between each feature?

**Comment by hishamco** [comment]
Great to report that, I notice that when I was working on the features page, but I forgot to report this
