### ISSUE TITLE
Provide local file for all static resources

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#4271]
There are certain static resources in the built-in modules and themes that are only available from a CDN (for example: fonts.googleapis.com fonts, https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.7.2/js/all.js, https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.7.2/js/v4-shims.js, https://vuejs.org/js/vue.js). This is not a huge issue in most cases, but it's prohibitive for a portion of intranet, and especially offline, apps. (By "offline" I mean not connected to the internet; intranet web apps may serve a huge network still. But if you're giving a talk without reliable internet or are on a plane the same thing applies.) When running Orchard offline some issues are just cosmetic (icons missing), but e.g. the Assets feature is completely broken.

My suggestion would be to always, for every resource, provide local files as well, and only use CDNs when the "Use CDN (Content Delivery Network)" checkbox is ticked. This would allow all of Orchard's features to work offline, as well as provide additional security for those who want it by not using external resources.

I guess this is not by design any way, just these resource predate the Use CND config.
Related: #3537.

**Comment by sebastienros** [comment]
For font-awesome it was intentional, as I didn't want to ship it (licensing concerns) and it's also a lot of files. But if the licensing is not an issue to ship it then why not. And also the fact that we have to handle updates by ourselves too (harder than a version number to change).

**Comment by sayyad84** [comment]
Hi guys,
I have a problem with CDNs and some of them has limit access for me. for example fontawesome and vue.js not working and media app not opening:
![image](https://user-images.githubusercontent.com/57654948/71771333-6fed5200-2f4e-11ea-9549-4fb888fdd5b7.png)

**Comment by Piedone** [comment]
Nice work @deanmarcussen !
