### ISSUE TITLE
Empty recipe: Cannot access to admin

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4283]
With the latest version of OC, if I use the Blank recipe, after the setup, I can't access the admin.

I am always redirected to the login page.

**Comment by hishamco** [comment]
Oh really, we should fix this ASAP

**Comment by jtkech** [comment]
Already fixed but not commited yet

**Comment by hishamco** [comment]
I want to ping you, but your reply was faster 😁
