### ISSUE TITLE
Allow OpenIdValidation Audience to start with the special 'oct:' prefix

### ISSUE THREAD

**Issue by MatthijsKrempel** [OrchardCMS/OrchardCore#4287]
We run a remote OrchardCore OpenId server, so our audience starts with this prefix. Since there is no way to configure the audience on the server and it is required to enter an audience when you want to use the validation feature on the client, this check is preventing us from using the feature.

I will submit a PR to delete this check.

**Comment by Piedone** [comment]
Seeing how https://github.com/OrchardCMS/OrchardCore/pull/4309 was closed, and from the discussion under it, it seems that this is not a generally favored approach. Please reopen if you think it is and elaborate.
