### ISSUE TITLE
Add custom field on user setup form

### ISSUE THREAD

**Issue by NexawoShahid** [OrchardCMS/OrchardCore#4289]
Is it possible to add a custom field to the tenant user setup screen with its implementation.
As shown highlighted GroupName in attached snapshot.
![Tenant User Setup](https://user-images.githubusercontent.com/55389769/64959533-c99c1480-d8aa-11e9-9165-1527ab649e77.PNG)

**Comment by hishamco** [comment]
AFAIK there's no feature to do such thing, but we could make the setup view extensible by adding fields in dynamic fashion

**Comment by hishamco** [comment]
@ShahidUser1 as @sebatienros said in gitter before the easiest and the faster way is to implement your, for more info have a look to https://github.com/OrchardCMS/TryOrchardCore

**Comment by ShahidUser1** [comment]
@hishamco as @sebastienros  mentioned on gitter setup module isn't extensible now, if I need the same customization then I have to create my custom view and controller with copy pasting existing setup code with my custom changes
