### ISSUE TITLE
Workflow images regression

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4310]
Something in https://github.com/OrchardCMS/OrchardCore/pull/4187 has created a new `Images` folder in https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Workflows/wwwroot/Styles

so they're now dup'd in `Images` and `images`

Will figure out which capitalization it should be and resolve. 

Probably gulp on linux being better at capitalization @jptissot

**Comment by Skrypt** [comment]
Make it lowercase I'd say.
