### ISSUE TITLE
Media file moved away from temp folder but reported there

### ISSUE THREAD

**Issue by jiangweiatgithub** [OrchardCMS/OrchardCore#4312]
Hi,

This is a follow-up issue from https://github.com/OrchardCMS/OrchardCore/issues/2240 .

After I click "Save draft", the liquid expresson- {{ Workflow.Input.ContentItem.Content.UserRegister.MyPhoto.Paths }} - reports as follows:
mediafields/temp/ba299bda-cb4e-4f2c-b40a-c6c072ad4f38red prime.jpg

I see something is in the temp folder just for a split of a second, Then I see that image in obviously a different folder - mediafields\UserRegister\4808sw8v8g5wmzhrzj2m9ct0mp\8f3c2a7411a3578c7fe8eb2a4a63b6f4.jpg

When I browse the Content Items, and click "Edit" for that content, I see a message in red:
Not Found
It will be discarded on saving
mediafields/temp/ba299bda-cb4e-4f2c-b40a-c6c072

The same issue happens when I click "Publish." What have I done wrong? What I want to be notified by the liquid exporession is the final location of the meia file, not the "temp" one.

Thanks!
Wei

**Comment by jiangweiatgithub** [comment]
Now, after severial trials, the issues seems gone. Was it due to any cache? That is, the "paths" property is not updated in a timely manner?

**Comment by hishamco** [comment]
So, is this still reproducable or we can close it?

**Comment by jiangweiatgithub** [comment]
Sure!
