### ISSUE TITLE
Add Translation metapackage to Cms.Targets

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#4313]
Not in the Core.Targets.

Update the csproj file.

**Comment by hishamco** [comment]
Is this will reference `OrchardCore.Translations.All.nupkg`?

**Comment by sebastienros** [comment]
Yes

**Comment by agriffard** [comment]
https://www.myget.org/feed/orchardcore-preview/package/nuget/OrchardCore.Translations.All

**Comment by agriffard** [comment]
Upgrade it also to rc1 after the OrchardCore release and reinit to 10000.

**Comment by hishamco** [comment]
This is good and bad, good because you will no longer need to reference any translation package, and bad because you will have unnecessary translations, perhaps more than 95% are wastage, I am think for Azure, Amazon.. etc why I need to pay for tons of unnecessary po file

I agree this is very useful for development scenario

**Comment by sebastienros** [comment]
The goal is to only add it to the Cms package, not the Core one that doesn't have the themes either. So if you don't want these you can already use the Core target, which I assume you will still do for a new site as you don't want TheBlog and TheAgency.

It should just increase the package download by 5MB. What will you have to pay that you wouldn't if you didn't have these. 

My only concern is that we might load all the po files without looking at what languages are supported. OR that we might load them for all tenants. Ideally we should only load the ones for the supported cultures, and have the strings reused across all tenants. If you want to check that it would help.
