### ISSUE TITLE
Check OpenID, EF

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#4315]
And remove NETStandard.Library 1.6.1

**Comment by jtkech** [comment]
As i remember, we would also need to update yesSql that would have to reference an updated version of `Microsoft.Data.Sqlite` that doesn't reference an old netstandard.

**Comment by sebastienros** [comment]
I already published it on nuget before going home. I'll finish tomorrow. And my strategy is to just unreference the ef package from the target.
