### ISSUE TITLE
Implement ElasticSearch module

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#4316]
Same as Lucene

**Comment by hishamco** [comment]
You read my mind, yesterday I was read a great post on ElasticSearch

**Comment by hishamco** [comment]
FYI this is a good article https://khalidabuhakmeh.com/search-experiences-for-your-aspnet-core-apps-with-elasticsearch

**Comment by Mpdreamz** [comment]
Hi! I work for Elastic feel to to `@` me on PR's happy to help/answer questions.

**Comment by hishamco** [comment]
@Mpdreamz if you are interested you could start in the PR for this module

**Comment by Skrypt** [comment]
The ElasticSearch module should leverage Nest for Queries. We have now Lucene Queries which uses the Lucene Query API but ElasticSearc has already this done with Nest. So we should end up with ElasticSearch Queries that should be quite the same than Lucene Queries with some small differences here and there since Nest for example can use Exists Queries.

**Comment by Skrypt** [comment]
I think we need to first make a service to retrieve different Indexing Providers. And I think we should be able to still use Lucene and/or ElasticSearch at the same time.

**Comment by jtkech** [comment]
@Mpdreamz thanks for proposing to help us!

**Comment by caki0915** [comment]
+1 for this feature. 👏

**Comment by mickdelaney** [comment]
Is there an interface(s) I can implement to integrate Elasticsearch ?
Any docs etc to point us in the right direction ? 
Thanks again

**Comment by sebastienros** [comment]
@mickdelaney no special interface, just copy paste the lucene module and adapt to use elasticsearch instead.
Many things will be the same, like the index management, or search page, or queries. They could collide if they are enabled at the same time, but they are not supposed to be.
Feel free to ask questions on gitter or join the triage meetings when you are stuck.

**Comment by Sen-Gupta** [comment]
@sebastienros @jtkech @deanmarcussen @hishamco 

We have implemented ElasticSearch (Basic in place), Index, Create, Delete, Rebuild, Indexing and Query using DSL.
Both (Elastic and Lucene can co-exist) ;-)

There are couple of observations, though
1) Lucene Content Search Picker should be better named as "Search Content Picker"? and the result provide must be abstracted higher.
2) The queries module is wired to be a sub node of Lucene Search Module with **NavigationConstants.AdminMenuSearchPosition**.
So we can only see queries module when Lucene is enabled.

Please guide how to proceed on this.

The implementation is very basic/raw but does what is intended.

**Comment by jtkech** [comment]
@Sen-Gupta Cool !

@Skrypt is better placed to give you some feedbacks, as he is the Lucene expert

Anyway, feel free to open a PR with your suggested code

**Comment by Skrypt** [comment]
Well, first thing is to have a branch or PR to work with. Then, we can make the changes in that branch if needed.

**Comment by giannik** [comment]
@Sen-Gupta  is there a public repo to try out the elastic search module ?

**Comment by Sen-Gupta** [comment]
This should be pushed potentially tomorrow! Been stuck on another Solr Search Implementations!

**Comment by Sen-Gupta** [comment]
The PR can be seen here #9108

**Comment by yash1529** [comment]
Can u make a tutorial for a step by step how to enable elastic search for orcahrd core? I am not able to enable elastic search UI on my admin interface

**Comment by Piedone** [comment]
Did you see https://docs.orchardcore.net/en/latest/docs/reference/modules/Elasticsearch/?
