### ISSUE TITLE
Admin: add version in footer

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#432]
Display the current version of Orchard on the bottom right in the footer on admin layout.

**Comment by agriffard** [comment]
Do we retrieve the version from Orchard.Cms.Web Assembly?

**Comment by Jetski5822** [comment]
Hmmmm I recon so

**Comment by agriffard** [comment]
Which core module can we use to determine the version of Orchard Core?

**Comment by agriffard** [comment]
Will we simply use the OrchardCore.Admin package version and display it in the footer of the admin?
