### ISSUE TITLE
Unable to delete widget

### ISSUE THREAD

**Issue by m3awadhi** [OrchardCMS/OrchardCore#4324]
Hello ,
This is what am getting when i try to delete widget from a page.
![Capture](https://user-images.githubusercontent.com/3107444/65133252-59f56900-da13-11e9-81c3-b8ee13c4209d.png)

Any idea on how to resolve this ?
TargetFramework netcoreapp3.0 TargetFramework

PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-beta3-72585" 

PackageReference Include="OrchardCore.Application.Targets" Version="1.0.0-beta3-72585"

**Comment by hishamco** [comment]
Strange!! Let me look on this

**Comment by jptissot** [comment]
Same for me 

![image](https://user-images.githubusercontent.com/4681586/65149811-cf9c0d80-d9f0-11e9-969e-98e05f5cc1df.png)

**Comment by jptissot** [comment]
Looks like a regression to me

**Comment by hishamco** [comment]
@jptissot you can start work on, while I'm still blocking by the environment :(

**Comment by jptissot** [comment]
Ok I will check this this morning

**Comment by hishamco** [comment]
It's evening here, if the `dotnet` issue resolved, I will shoot the fix before you wake up :)

**Comment by emekaemego** [comment]
Still getting this issue on `1.0.0-beta3-72691`

**Comment by m3awadhi** [comment]
> Still getting this issue on `1.0.0-beta3-72691`
@emekaemego 
i am not facing this issue anymore
Try CTRL+F5  or clear your browser cache

**Comment by emekaemego** [comment]
> > Still getting this issue on `1.0.0-beta3-72691`
> > @emekaemego
> > i am not facing this issue anymore
> > Try CTRL+F5  or clear your browser cache

How did I miss that? Worked.
