### ISSUE TITLE
Localization packages need some msbuild scripts

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#4329]
About the localization packages.

As i remember, with the new nuget package system content files are not copied under the project, they are immutable contents that may be referenced but as link items. Hmm, maybe with the right option they can be outputed on building but they will be under the bin folder, not under the project root.

So, i think that the localization packages need to be packed with some msbuild `*.props and / or *.targets` scripts so that `*.po` files are copied on building and then on publishing.

As we did at some point for modules when they needed to be under the application project root.

**Comment by sebastienros** [comment]
Can't we just include the localization folder, like the wwwroot is? As part of the csproj. And do it in the template too?

**Comment by jtkech** [comment]
I don't think so, about `wwwroot` folders, each module embeds its own static assets, and for application static assets they need to be physically under the application `wwwroot` folder.

As i remember, the solution would be to inject for each localization an msbuild script file (with a different name) so that on building each package will  enlist itself its `*.po files` e.g in an msbuild `$(LocalizationFiles)` property, as we do for each module that enlists itself its name through the msbuild `ModulePackageNames` property.

Then, through `OrchardCore.Application.Targets` an msbuild script that would use the `$(LocalizationFiles)` property to copy them under the application `Localization` folder.

Then, some targets to delete them when doing a clean on a project, before doing a rebuild and so on.

**Comment by jtkech** [comment]
Just saw in the `OrchardCore.Translations` repo that packages are not built through `*.csproj` files.

If we keep things like this, i would have to explain to @hishamco how things are done for module so that it could reproduce what is done when using e.g the following in a `csproj` file.

    <ItemGroup>
      <None Include="$(MSBuildThisFileDirectory)Package.Build.props" Pack="true">
        <PackagePath>build\$(TargetFramework)\$(AssemblyName).props</PackagePath>
      </None>
    </ItemGroup>

Note: For localization packages, as i remember `$(TargetFramework)` could be replaced by `any`.

**Comment by jtkech** [comment]
Hmm, maybe just a simpler marker so that these packages are recognized as translation packages. Or simpler, just because their names start with `OrchardCore.Translations`.

I will try something without having to change the current localization packages.

**Comment by sebastienros** [comment]
This is what I see in the current OrchardCore.Cms.Web:

```
  <ItemGroup>
    <Folder Include="wwwroot\" />
    <Folder Include="Localization\" />
  </ItemGroup>
```

**Comment by jtkech** [comment]
Yes, this is necessary but not enough.

But as said above, i will try something without having to change the current localization packages.

**Comment by hishamco** [comment]
@jtkech try what's in your mind, or let me know what should I do

One point it needs a clarification, while the translations could be in different places, how the translation packages will aware about this?!!

**Comment by jtkech** [comment]
Okay.

Hmm, i think that to be used from other locations they have to be manually copied and then marked to be published. E.g, as i remember, for a given module under its `App_Data` folder, then here the *.po files will be embedded in the module assembly, so here no need to do anything on publishing.

**Comment by sebastienros** [comment]
I did that in the csproj and it worked:

```
    <Content Include="Localization\">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

**Comment by sebastienros** [comment]
But I can also confirm that the Translation projects didn't export their po files in my Localization contente, even before publishing /cc @hishamco

**Comment by hishamco** [comment]
Is that mean that the po files don't copied into the Localization folder?!!

**Comment by sebastienros** [comment]
@hishamco my last comment yes

**Comment by sebastienros** [comment]
Checkout the dev branch, it's supposed to copy these

**Comment by jtkech** [comment]
`CopyToOutputDirectory` just outputs what you **already have** under `Localization`, and then under the bin folder (not the app root), and do nothing on publishing

**Comment by hishamco** [comment]
Really!! could you please let me know what happen after you install any translation package?

> Checkout the dev branch, it's supposed to copy these

Now

**Comment by jtkech** [comment]
I did some progress, in a targets file i could grab all package dependencies (so even transitively referenced) whose name start with `OC.Translations`.

**Comment by jtkech** [comment]
> Checkout the dev branch, it's supposed to copy these

This was possible with the previous `package.config` system.

**Comment by hishamco** [comment]
> This was possible with the previous package.config system.

I referred to Microsoft Docs for that one, I will download a sample translation and come back to you

**Comment by sebastienros** [comment]
> CopyToOutputDirectory just outputs what you already have under Localization, and then under the bin folder (not the app root), and do nothing on publishing

I added a file in the Localization folder, called a `dotnet publish` and it got my file in the correct folder on the published target. Not in the bin, where I wanted it.

**Comment by hishamco** [comment]
https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files

I read before that the `contentFiles` is not necessary, it will pick up it's content automatically, but when I open any package with NuGet Explorer and export its metadata, it adds that tag and list all the files inside `content/{culture}`. Could this be the issue?

I remember I try it in another project and it's works as expect

**Comment by jtkech** [comment]
> I added a file in the Localization folder, called a dotnet publish and it got my file in the correct folder on the published target. Not in the bin, where I wanted it.

Yes because we also and already have

    <ResolvedFileToPublish Include="Localization\**">
      <RelativePath>Localization\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
    </ResolvedFileToPublish>
  </ItemGroup>

**Comment by jtkech** [comment]
Okay, in a targets file i could grab easily the full path of all package dependencies (so even if transitively referenced) by using the following. So, it will be possible to copy them if not done automatically.


![Translations](https://user-images.githubusercontent.com/8586360/65193477-8f35a180-da7b-11e9-8242-897ebe4eca6a.png)

**Comment by jtkech** [comment]
> .. list all the files inside content/{culture}.

Yes, i could see this under my local package storage.

> Could this be the issue?

I don't think so.

> I remember I try it in another project and it's works as expect

Wich kind of project? Maybe not with the `*.csproj` and `PackageReference` system.

**Comment by hishamco** [comment]
> Wich kind of project? Maybe not with the *.csproj and PackageReference system.

`*.csproj`

**Comment by jtkech** [comment]
So, i think i can do this by completing the `OrchardCore.Application.Cms.Core.Targets.targets` file. @sebastienros is it the right place?

**Comment by hishamco** [comment]
> Maybe before the project.json

Ya, because my aim was to check the extraction of the package itself, if is there anything we can do in the `pack.ps1` feel free to suggest the modification

**Comment by sebastienros** [comment]
I created another folder Foo, with some file in it. Added 

```
    <Content Include="Foo\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

And everything is published in the Foo folder on the destination, as expected

**Comment by hishamco** [comment]
😟 Is it a NuGet package or PackageReference issue or my issue :)

**Comment by jtkech** [comment]
> And everything is published in the Foo folder on the destination, as expected

Okay sorry, because content files are published. This is because in our targets file we also have a `Content Remove` to not show them all under the solution as for the `wwwroot`.

Yes the main issue was "just" that we need to 1st grab them from the localization packages.

**Comment by jtkech** [comment]
So, seems that for package dependencies we can only retrieve their names, e.g not their versions and then their full paths. There are some coded msbuild tasks that grab more infos from the `project.assets.json` cache but they are not exposed to the related msbuild items metadata.

So right now i think we need to do some changes to have the right metadata in the `.nuspec` files. [In this doc](https://docs.microsoft.com/fr-fr/nuget/reference/nuspec#including-content-files) search for `NuGet 4.0+ with PackageReference` to see how to use `contentFiles`, and attributes as `include, buildAction, copyToOutput` (and their default values), how to use `/contentFiles/any/any/...` to be `Language- and framework-agnostic` and so on. Here the example they provide.

    <metadata>
        ...
        <contentFiles>
            
            <files include="any/any/images/dnf.png" buildAction="EmbeddedResource" />
            <files include="any/any/images/ui.png" buildAction="EmbeddedResource" />

            
            <files include="cs/**/*.png" buildAction="EmbeddedResource" />

            
            <files include="cs/uap/config/config.xml" buildAction="None" copyToOutput="true" flatten="true" />

            
            <files include="cs/commands/run.cmd" buildAction="None" copyToOutput="true" flatten="false" />

            
            <files include="cs/net45/scripts/*" exclude="**/*.exe"  buildAction="None" copyToOutput="true" />
        </contentFiles>
    </metadata>

Having this kind of `.nuspec` i think we will be able to retrieve the **full paths of the linked items**.

I think `buildAction="Conent or None"` will just show or not the linked items under the solution.

Using `copyToOutput="true"` will output the files on building and then maybe also on publishing. That'ok in a published context, otherwise they will be copied under the bin folder not just under the project root folder. So, at run time we would have to look at the executing directory instead.

If it is not a problem we could have in the `.nuspec` e.g

    <files include="any/any/Localization/**/*.po" buildAction="None" copyToOutput="true" />

Otherwise we could use the following and then copy through a msbuild target these items under the `projectRoot/Localization` folder. Note: To be able to retrieve these items maybe we will need to use `buildAction="Content"` but i think that `None` is ok, will see.

    <files include="any/any/Localization/**/*.po" buildAction="None" />

If you think it's better to 1st do some tests by using a local feed, as i have time i can do these tests, let me know. Otherwise, i will wait for these changes to be available from myget.

**Comment by hishamco** [comment]
IMHO we can modify `_template.nuspec` and test one of the translation packages from artifacts after CI

@jtkech you could create a PR on translation repo to test the case that you, if you need any kind of help don't be hesitate

**Comment by sebastienros** [comment]
https://devblogs.microsoft.com/nuget/nuget-contentfiles-demystified/

This article explain how to change the packages such that the files are copied correctly. It can trigger a custom msbuild target too.

**Comment by jtkech** [comment]
Okay, i'm tying to do some local tests first.

**Comment by jtkech** [comment]
@sebastienros i know this article where we retrieve some similar infos but maybe a little outdated because they talk about **project.json** before the new `csproj` system.

Files will not be copied under the project root, they can be outputed on building but in the executing folder.


but then can be copied on building but to the executing directory

**Comment by jtkech** [comment]
Just restarted some tests, okay, i can test everything locally by updating some package .nuspec files and how their files are distributed, i will let you know what happens.

**Comment by jtkech** [comment]
So, i did some tests that confirms what i said above but with the additional info that it doesn't work when a translation package is referenced transitively. So, here i referenced, directly from the application, a translation package whose `.nuspec` file has this additional metadata.

    <contentFiles>
      <files include="any/any/Localization/**/*.po" buildAction="Content" copyToOutput="true" />
    </contentFiles>

Note: Using `Content` or `None` is the same, in both cases there are existing items that will be shown under the solution. Then i distributed the content files like this.

![Translations6](https://user-images.githubusercontent.com/8586360/65295059-794ddc80-db60-11e9-9a4e-9cfaa1cc62e4.png)

Then you can show the files under the solution (not the case without the updated `.nuspec` file) but there are linked items not physically under the project root (see the `Full Path` property).

![Translations2](https://user-images.githubusercontent.com/8586360/65294754-769eb780-db5f-11e9-867e-ef6c24fe2b02.png)

Then, because of the `copyToOutput` attribute, on building there are outputed but under the bin folder, not under the project root folder.

![Translations3](https://user-images.githubusercontent.com/8586360/65295232-08f38b00-db61-11e9-9681-22289911c084.png)

----

First, if we don't want the `*.po` files under the bin folder, we could use a msbuild script to copy them. Here we can do that because when the package is referenced directly i can retrieve all the full paths through the following script, was not possible when the package is referenced transitively.

![Translations4](https://user-images.githubusercontent.com/8586360/65295553-13faeb00-db62-11e9-94d3-6c2fb1118d1f.png)

But anyway, when referencing the package directly, i can retrieve the package full path, this was not possible when referenced transitively. So, in this case updating the `.nuspec` file would not be necessary.

![Translations5](https://user-images.githubusercontent.com/8586360/65295727-8c61ac00-db62-11e9-9869-6aada5bdc113.png)

---

Okay cool, but the main problem is that we want to reference the translation packages transitively, e.g through `OC.Application.Cms.Targets` => `OrchardCore.Translations.All`.

If so, i think we would need that each translation package embeds the same little `*.props` file (but with a different name based on the package name), as we do for modules but here i think under a `build/any` folder (i will check it). So that on building each package will enlist their `*.po` files in a shared collection that could be used in an msbuild script.

Tomorrow, i will create and test such a `*.props` file that could be used (with a different name) by each package. Note: script files under the `build` folder don't need to be sepcified in the `.nuspec` file.
