### ISSUE TITLE
>  I think we should add a global option as for the html encoder to use in liquid

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#4330]
>  I think we should add a global option as for the html encoder to use in liquid

I think we add some encoding if I'm not wrong, let me check

_Originally posted by @hishamco in https://github.com/OrchardCMS/OrchardCore/issues/4041#issuecomment-523160166_
----------------
Please add a global option so we can choose an alternative to "HtmlEncoder.Default" anywhere.

**Comment by hishamco** [comment]
This should be move to Fluid repo
