### ISSUE TITLE
Iterating all Parts of ContentItem in liquid

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4334]
I am trying to iterate all Parts in liquid as below - doesn't render anything

```
{% for item in Model.Parts.Items %}
<div class="col border border-secondary">
        {{ item | shape_render }}
</div>
 {% endfor %}
```
However below Razor Counter Parts works.

```
@foreach (var item in Model.Parts.Items)
    {     
            <div class="col border border-secondary" >
                @await DisplayAsync(item)
            </div>
        }
     
    }
```
Any Idea how do I loop through Model.Parts.Items in liquid?

**Comment by sebastienros** [comment]
Technically your are not iterating parts, but the shapes I think.
Wither we need to expose the `Items` property on Zones in liquid, or provide a way to get a named zone in liquid.

**Comment by ns8482e** [comment]
I was trying to create an alternate shape that would render any content item without using default Zone location like Header or Footer.
 
Also,  the name or list of parts are not known as the template could be used for any content.
