### ISSUE TITLE
HtmlBody can't be used as a reusable part

### ISSUE THREAD

**Issue by DaveEmmerson** [OrchardCMS/OrchardCore#4339]
I'm trying to have two HtmlBody parts, so that someone creating an instance of my content type can include some HTML content to be output in two separate sections of the resulting page.

It doesn't seem to be possible, unless I'm missing something?

Article parts:
![image](https://user-images.githubusercontent.com/2356855/65316351-b2eb0b80-db91-11e9-9b83-bac1bdc43616.png)

New Article:
![image](https://user-images.githubusercontent.com/2356855/65316378-c007fa80-db91-11e9-9ef1-d56e8953dfbe.png)

Add named part:
![image](https://user-images.githubusercontent.com/2356855/65316398-c8f8cc00-db91-11e9-97ca-b2a4afd8d084.png)

Article parts (with named HtmlBody 'Footer'):
![image](https://user-images.githubusercontent.com/2356855/65316417-d7df7e80-db91-11e9-8414-157057b05e4d.png)

New Article:
![image](https://user-images.githubusercontent.com/2356855/65316436-df9f2300-db91-11e9-83e2-c0ec97380e7c.png)

While writing this, I realise that perhaps I could use a Liquid block instead and provide two zones that the template can then pick up on? I'll try that as a workaround, but it'd be cleaner for the end user to be able to do it this way.

Thanks

Dave

**Comment by DaveEmmerson** [comment]
I see from another issue that if something isn't marked as reusable by whoever created it, then it probably shouldn't be marked as reusable by someone using it? In that case, should the 'reusable' check box be read only?

**Comment by deanmarcussen** [comment]
Normally we use the HtmlField when we need a second piece of html content.

I think it's probably non reusable because it can be used to generate a `BodyAspect`, which if there are two of them, would confuse the aspect arrangement.

So the primary piece of content is a HtmlPart, and other bits that make up extra content are fields

**Comment by DaveEmmerson** [comment]
@deanmarcussen ah, ok, fair enough. I've not managed to figure out how to actually render out the contents of an HTML field. Any hints? New to Orchard and getting lost in Content vs ContentItem vs ContentItem.Content, etc. :)

**Comment by deanmarcussen** [comment]
No worries.

Model.Content is where the shapes are
Model.ContentItem is the json of the content item

field accessors are
```
var fieldValue = Model.ContentItem.Content.Article.MyField.Text;
```

https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.ContentFields/

assuming you put the field on the content type, not one of the parts.

Dumping Model.ContentItem (or Model.ContentItem.Content - I actually can't remember of the top of my head which one sorry) in your template can be helpful, just to get the json showing up, so you can see which bits you need to navigate to.

**Comment by DaveEmmerson** [comment]
Thanks 👍 That's about where I got to. So I've got { "Html": "Hello \<b>world\</b>" } and I can get the template to output literally Hello \<b>world\</b> rather than Hello **world**.

{{ Model.ContentItem.Content.DocumentsPage.Header.Html }}

That's just text rather than a shape it seems,

{{ Model.Content.HtmlBodyPart | shape_render }} that works for the HtmlBody part

I thought maybe {{ Model.Content.DocumentsPage.Header | shape_render }}, but that didn't work.

**Comment by DaveEmmerson** [comment]
Ah...

{{ Model.Content["DocumentsPage-Header"] | shape_render }}

https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Templates/README/#content-field-differentiator

> To access or render the shapes for a field that is added to the content type directly, the [PartName] is equal to the content type. For instance, given a content type Article with a Text field named Description, the shapes for this field would be named "Article-Description". Render these shapes in Liquid would be:
>
>```
>{{ Model.Content["Article-Description"] | shape_render }}
>```

Thanks for looking into it for me
