### ISSUE TITLE
Unable to build dev branch with .NET Core 3 RC1 and VS 2019

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4340]
Unable to build dev branch with .NET Core SDK 3.0 RC1 installed with VS 2019 Professional

========== Build: 93 succeeded, 58 failed, 0 up-to-date, 0 skipped ==========

I am receiving following error for NullableTypes  for Razor files (.cshtml).

obj\Debug\netcoreapp3.0\Razor\Views\Admin\Features.cshtml.g.cs(15,2,15,10): error CS8652: The feature 'nullable reference types' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.

To build it successfully I had to change language version in OrchardCore.Commons.props as following 

`<LangVersion>preview</LangVersion>`

**Comment by hishamco** [comment]
I faced this issue too, last few days ago, after that I decided to use VS Code. Let me try your change

thanks

**Comment by hishamco** [comment]
I try it but the issue still :(

**Comment by sebastienros** [comment]
We might need to revert the change that removed these properties 3 days ago from @jtkech. But the CI doesn't complain so I wonder what makes it work for the other machines.

**Comment by deanmarcussen** [comment]
Are you guys using Visual Studio 2019, or the Visual Studio 2019 Preview 3?

I believe the recommendation from Microsoft is to use Preview 3

LangVersion preview would be required for the older VS 2019, because it doesn't support core 3

**Comment by hishamco** [comment]
>  so I wonder what makes it work for the other machines.

I'm using VS 2019 v 16.1.3

> I believe the recommendation from Microsoft is to use Preview 3

Ya, 16.3.x but I don't know why it doesn't work while I have the latest runtime & SDK?!!

**Comment by ns8482e** [comment]
I am using VS 2019 Professional 16.2.5
Changing LangVersion to preview works for me

**Comment by sebastienros** [comment]
Right now it seems we either need Visual Studio Preview 3 or VSCode, only in the case when you want to use the source solution and not the Nuget packages. I would say that is fine then and it was expected.

**Comment by sebastienros** [comment]
I am leaving this open right to get some feedback on this, if this is controversial.

**Comment by hishamco** [comment]
Seb I suggest to close this while no action needed and add a little tip in Readme file for RC tooling
