### ISSUE TITLE
Editor / Display mode "Standard" option duplicated for ContentPickerField

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4365]
It seems the "Standard" option is duplicated for ContentPickerField in the Editor / Display mode dropdowns.

I found that [this line](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ContentTypes/Views/Admin/EditField.cshtml#L14) is the issue.

Because we have a field called LocalizationSetContentPickerField. The editorShapes variables looks for shapes that start or end with the name "ContentPickerField"

So, `ContentPickerField__Option` matches both the `ContentPickerField.Option.cshtml`  and `LocalizationSetContentPickerField.Option.cshtml`

**Comment by hishamco** [comment]
You could fix it if you have time

**Comment by jptissot** [comment]
I would but I don't want to break other stuff. Maybe some other code depends on 
`|| x.EndsWith(Model.PartFieldDefinition.FieldDefinition.Name + "_Option", StringComparison.OrdinalIgnoreCase)` being present.

**Comment by hishamco** [comment]
We can do it after RC
