### ISSUE TITLE
Rendering of Widget ContentItem containing Bag throws exception 

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4372]
Error while rendering "widget" content item containing Bag Part. 
`
An unhandled exception occurred while processing the request.
Exception: Shape type 'Widget_Summary' not found
OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in DefaultHtmlDisplay.cs, line 125
`
To reproduce,

1. Create a widget content type "News"
2. Create a widget content type "News Roll", Add Bag Part and select "Contained Content Types" News.
3. Create New "News Roll" publish and click View.

Default display type should be Detail if display type is null

https://github.com/OrchardCMS/OrchardCore/blob/f832db952faf5c55e7f1d43ef74226214675dc88/src/OrchardCore.Modules/OrchardCore.Flows/Views/BagPart.cshtml#L9

**Comment by jptissot** [comment]
I had the same bug, you can mitigate by implementing in your theme: 

Shape name: `BagPart`

```liquid
{% for item in Model.BagPart.ContentItems %}
{{ item | shape_build_display | shape_render }}
{% endfor %}
```

**Comment by sebastienros** [comment]
@jptissot can you provide a fix as a PR if you agree with the change? I would take it for rc, seems low risk and an easy bug to get into

**Comment by deanmarcussen** [comment]
The other fix for this is just the set the display type you want, i.e. `Detail` in the `BagPartSettings`.

Probably we could consider a WidgetSummary shape, otherwise changing the default might affect all the other BagPart default displays

**Comment by sebastienros** [comment]
We can adda Summray template that has the same content as the DEtails one. @deanmarcussen you want to do it?

**Comment by ns8482e** [comment]
@deanmarcussen BagPart uses  BagPartSettings but it fallback to "Summary" only in event of null that resulted in this exception.

**Comment by deanmarcussen** [comment]
I’m not near the computer tonight so if someone else can?

**Comment by sebastienros** [comment]
I will then.
