### ISSUE TITLE
WidgetList -  Zone other than Content is not visible 

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4374]
I am puzzled on how Zone defined on WidgetList are displayed

I created, Content and Aside zone, but only widgets added on Content zone are visible 

 WidgetListDisplay driver only compare with Zones defined in LayoutShape i.e. Head, body, Tail and Content.

How do I add Aside zone? in the theme?

**Comment by sebastienros** [comment]
In the Layout file of your theme, you need to render a named zone, using `RenderSection`. You'll find examples in your existing layout.

**Comment by ns8482e** [comment]
So Zone in layout must match with Zones defined in Settings and Zones for widget list to be displayed?

**Comment by sebastienros** [comment]
Yes. The Layers puts widgets instances in "named" zones, and the Layout can render such named zones, where it needs to. Ideally the zones management should be available in the same widgets page. Or at least more easily accessible. And we could also point to some documentation. If you want to help with that we would appreciate a lot.
