### ISSUE TITLE
Is it possible to define table schema per ContentType instead of using Document table?

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4377]
In SQL for certain sensitive content type, is it possible to define separate table? so that MS SQL user/permission can be assigned to certain group to have access to such table instead of giving full Document table access?

**Comment by sebastienros** [comment]
It would probably be possible by class, but all content types are for the same class, ContentItem so I don't think that's possible. Also because the ContentItem index tables would also need to spread joins across many tables.
