### ISSUE TITLE
Custom Liquid Tag

### ISSUE THREAD

**Issue by pgodwin** [OrchardCMS/OrchardCore#4384]
I'm attempting to write a module so that user's can "star" content items. 

I've built a `TagHelper` for this
```cs
[HtmlTargetElement("star", Attributes = "class,contentItemId", TagStructure = TagStructure.WithoutEndTag)]
public class StarredItemTagHelper : TagHelper
{
...
}
```
And registered it in startup.cs via `services.AddTagHelpers<StarredItemTagHelper>();`

but I can't seem to work out how to call it from a Liquid template.

I get the following error:
```
Exception: Failed to parse liquid file /Areas/MySite.Theme/Views/Content-Homepage.liquid: Syntax error, expected: if, endif, elsif, else, unless, endunless, case, endcase, when, for, endfor, continue, break, comment, endcomment, raw, endraw, cycle, assign, capture, endcapture, increment, decrement, include, render_body, render_section, page_title, antiforgerytoken, layout, shape_clear_alternates, shape_add_alternates, shape_clear_wrappers, shape_add_wrappers, shape_clear_classes, shape_add_classes, shape_clear_attributes, shape_add_attributes, shape_type, shape_display_type, shape_position, shape_cache, shape_tab, shape_remove_item, shape_pager, helper, shape, link, meta, resources, script, style, block, endblock, a, enda, zone, endzone, scriptblock, endscriptblock, cache, endcache, cache_dependency, cache_expires_on, cache_expires_after, cache_expires_sliding at line:255, col:18

OrchardCore.DisplayManagement.Liquid.LiquidViewTemplate+<>c__DisplayClass5_0.<Parse>b__0(ICacheEntry entry) in LiquidViewTemplate.cs, line 122
```

How do I register a custom tag with the Liquid engine?

**Comment by jtkech** [comment]
For liquid you could create a filter, we have many examples in the source code.

We also have a bridge between razor and liquid.

As i remember, if it's a self closed tag

    {% helper "tagname", attr1:"...", attr2:"..." ...  %}

For attributes use camel case and replace all `-` with `_`.

If the tag has content, use `block` in place of `helper`.

**Comment by pgodwin** [comment]
Thanks @jtkech it worked!
`{% helper "star" %}` failed, but ` {% helper "star", class: "foo", contentItemId: "blah" %}` worked, so clearly my attributes need some work on the helper.

I think some wording for this in the documentation might be useful. I'll add a couple of lines and submit a pull request.

**Comment by sebastienros** [comment]
In O1 we implemented star voting by creating a custom part that would render the stars and own the controller to store the data on the content item. We also had a separate module named Voting to store data for a content item. It was just providing APIs and storage.
