### ISSUE TITLE
Input ID buildEditorUrl duplicated when FlowPart, BagPart and WidgetListPart used on same page

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4390]
While working on Pull request #4106 found a bug that <input> with same html id **buildEditorUrl** is generated multiple times

Due to this ajax request is sent to wrong controller as browser is taking only the first one.

**Comment by ns8482e** [comment]
Following line doesn't render hidden input for FlowPart if child widget has WidgetListPar or vice versa.

https://github.com/OrchardCMS/OrchardCore/blob/bf0d29929d9de777f20a2c8f6e71d300cee1ec20/src/OrchardCore.Modules/OrchardCore.Flows/Views/FlowPart.Edit.cshtml#L71

Isn't this line should start with @ as below to emit the rendering on Page??

`@await DisplayAsync(await ContentItemDisplayManager.BuildEditorAsync(contentItem, Model.Updater, true, "", Guid.NewGuid().ToString("n")));`

**Comment by deanmarcussen** [comment]
@ns8482e I think you only need the @ if you aren't already in a razor block.

**Comment by ns8482e** [comment]
I guess the intention is to emit rendering, but its not rendering on page- as its just calling like a C# function

**Comment by deanmarcussen** [comment]
I think if you read the comment above
`// Render a mock widget so that its resources are included in the page`

it's not intending to render the widget itself, just call display so that any script/style resources are called for the possible widgets

**Comment by sebastienros** [comment]
Correct, we don't want to actually render it, just guess what scripts/css it requires later to be rendered dynamically. We also talked recently about using some more specific way to register resources from an explicit service that widgets would have to implement to register custom script for the editors. And also to register to a javascript event such that it can run some javascript when a widget is added dynamically.

Using the service would prevent us from having to do a fake render. And using the Javascript event would fix a gap when we need to do some custom code for every new instance of the widget (I think codemirror needs it).

**Comment by ns8482e** [comment]
Ah, that's why the hidden inputs are not being rendered  which is needed for build editor url.
In PR#4106 the script evaluates as 'undefined' after updating input Ids 
In dev it sends request to wrong controller as same id is used

**Comment by sebastienros** [comment]
Does your PR fix this issue?

**Comment by ns8482e** [comment]
It will, I am checking in another commit, I thinking of removing input hidden and  storing editor url in data- attribute of DOM element

**Comment by ns8482e** [comment]
Fixed in PR #4106
