### ISSUE TITLE
Upgrade to .net core 3.0 with rc1-10004  error not compatible with netstandard2.0 

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#4391]
I just get VS2019 installed with .net core 3.0.

When using Nuget to upgrade Orchard Core from beta 3 to Rc1, it has error:

**Package OrchardCore.Users 1.0.0-rc1-10004 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package OrchardCore.Users 1.0.0-rc1-10004 supports: netcoreapp3.0** 

Does that mean I need to rewrite my Custom Module (which use .net 2.0)??

**Comment by jtkech** [comment]
Yes as soon as your module depends on an aspnetcore package and or an orchardcore package which is the case of a module.

**Comment by Skrypt** [comment]
Basically, netstandard 2.1 only supports .NET Core 3.0.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by jtkech** [comment]
Yes, a library targetting netstandard 2.1 can be referenced by a netcoreapp3.0 app, but then the library itself can't reference an aspnetcore 3.0 package.
