### ISSUE TITLE
Recipe steps fail silently when feature enablement isn't prioritized

### ISSUE THREAD

**Issue by jrestall** [OrchardCMS/OrchardCore#4393]
When I use the Export functionality and by mistake put the 'All Features' step at the bottom of the deployment plan, it isn't immediately obvious why the recipe doesn't work when being used as a setup recipe.

The reason is that the recipe executor runs each step in the recipe in order, so any steps that rely on specific features aren't run since the features are enabled in the last step.

That makes sense to me now, but a user shouldn't have to worry about such technicalities. We should either prioritize the feature enablement step in the recipe or improve messaging and/or logging to make it clearer why a recipe step isn't executed.

**Comment by deanmarcussen** [comment]
Also worth noting that the ContentDefinitions steps likes to be before Contents, so that would be another one to include in the ordering.

**Comment by jtkech** [comment]
Just for infos, some 1st thoughts i had on this and that i commented on gitter.

> about recipe steps ordering, we already have a feature dependency graph that we use to have ordered features, and any recipe step is tied to a feature. So, maybe we could use this graph to order recipe steps. Hmm, all features would need to depend on the Features feature, but we also have a feature Priority property, so in place of adding a dependency on Features everywhere, we could set a very low priority to the Features feature that depends on nothing => to be first in the graph.

**Comment by jtkech** [comment]
What i'm saying is that we already have services to get the enabled features in an order that rely on what we put in the `Manifest.cs` files for each feature about their dependencies and priority. So, maybe we could reuse this ordering (already implemented) to execute each recipe step (that is tied to a feature).

That said, looking in the `Manifest.cs` files, i saw that e.g `OC.Contentypes` depends on `OC.Contents`, meaning it is after in the ordering. So, maybe we would need to use the reverse order for recipe steps, or maybe this is a wrong dependency, maybe this is `Contents` that would need to depend on `Contentypes`. OR maybe one recipe step is in the wrong module but i don't think so.

This to execute `ContentDefinitionStep` before `ContentStep`.

Would need to be analyzed deeper

**Comment by sebastienros** [comment]
The execution should respect the recipe order. But I am not opposed to provide hints in the recipe generation ui to prevent such issues. Now how to define such relative ordering is interesting, because it means steps needs to know about each others. Or we use an `Order` hint with `0` being the default, and then some could have `-1000` like features enabling/disabling, or `Content` be after `ContentType`. 

Also it could just be an hint that would display a warning if the order of the steps in the plan doesn't match the "hinted" order. Like "The feature step should be put first", and you still really want to let it where it is then that's fine. IT also means that we need a UI to move deployment steps up and down.

**Comment by jptissot** [comment]
@sebastienros how about we create some metadata for some of the important steps and when adding them in the ui, they would place themselves automatically (features should always be inserted first for example).

**Comment by sebastienros** [comment]
"First" is a weird concept from my experience. There is always something that wants to be first, and something else too. I think the warning would be simpler to implement, and would not give too big promises that can't be fulfilled.

**Comment by jtkech** [comment]
Maybe after some adaptations, my sugestion was to **1st rely** on the features ordering using our utility `OrderByDependenciesAndPriorities`. Meaning that recipe steps could use the same ordering as drivers / handlers use, knowing that when a feature1 depends on feature2 it runs after.

No luck, currently `OC.ContentTypes` depends on `OC.Contents` but after a quick look in the code, i saw that the `OC.Content AdminController` use content type services, so maybe it is the opposite.

If so, this would mean that relying on the above ordering, e.g `ContentDefinitionStep` would run before `ContentStep`.

Just an idea, but as said would need more checkings.
