### ISSUE TITLE
Warning on RC1 Decoupled CMS

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4398]
![warning](https://user-images.githubusercontent.com/1761249/65613028-94cc4380-dfb5-11e9-9664-a5c5e9da7a1c.png)

**Comment by hishamco** [comment]
Could you please use `git clean -xdf` and rebuild the project again

**Comment by Skrypt** [comment]
Issue is coming from nuget packages
I'd say clean your nuget cache instead.

**Comment by dodyg** [comment]
![clear-1](https://user-images.githubusercontent.com/1761249/65618791-34da9a80-dfbf-11e9-9eaf-dc69d440a990.png)

I deleted `bin` and `obj` folders too.

![clear-2](https://user-images.githubusercontent.com/1761249/65618801-3906b800-dfbf-11e9-9d4c-c57992f7ff84.png)

**Comment by deanmarcussen** [comment]
Did you run dotnet clean as well? that has helped a lot

**Comment by dodyg** [comment]
![clear-3](https://user-images.githubusercontent.com/1761249/65619196-07dab780-dfc0-11e9-8c16-f83aa0fa92f5.png)

**Comment by jtkech** [comment]
we have already hidden this warning in an msbuild script but only at the module level

    <Target Name="NoWarnOnRazorViewImportedTypeConflicts" BeforeTargets="RazorCoreCompile">
      <PropertyGroup>
        <NoWarn>$(NoWarn);0436</NoWarn>
      </PropertyGroup>
    </Target>

Here it's related to a view defined at he app level, so we would need to do the same at the app level, i will take a look on it this night.
