### ISSUE TITLE
OrchardCore.ContentFields.Indexing.SQL.Migrations not run

### ISSUE THREAD

**Issue by pgodwin** [OrchardCMS/OrchardCore#4406]
I'm attempting to use the new Content Field Indexing under RC1. 

Upon querying using ISession I get the following error:
```
SqliteException: SQLite Error 1: 'no such table: ContentPickerFieldIndex'.
```

It looks like the migration doesn't run automatically for the indexer?

Steps taken:
1. Enabled the module in the admin cose.
2. Have a controller which calls the following:
```csharp
 var dashboards = await _session
                    .Query<ContentItem, ContentPickerFieldIndex>(x => x.ContentType == "Dashboard" && x.ContentItemId == categoryId)
                    .ListAsync();
```
Is there a step I need to make before using the content indexers?

**Comment by Skrypt** [comment]
Make sure the table is there. It probably isn't. Make also sure that your migration maps to the proper assembly name in your database.

**Comment by pgodwin** [comment]
The assembly and index are both from `OrchardCore.ContentFields` - specifically [ContentPickerFieldIndexHandler](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/ContentPickerFieldIndexHandler.cs).

I've confirmed the table hasn't been created, but unsure why the OrchardCore didn't create the index? Shouldn't switching on the SQL Indexing feature run the migration?

**Comment by pgodwin** [comment]
Should
https://github.com/OrchardCMS/OrchardCore/blob/c110128693ae52cd5a6864993df64f7f0db071b2/src/OrchardCore.Modules/OrchardCore.ContentFields/Startup.cs#L155

be 
```
services.AddScoped<IDataMigration, Indexing.SQL.Migrations.Migrations>();
```
instead?

**Comment by Skrypt** [comment]
Sure you are changing the migration name. Let me test from OC source code.

**Comment by Skrypt** [comment]
You are right. For some reason that's a regression made from a recent PR. We have now 2 migration files in that project.

**Comment by pgodwin** [comment]
Cheers thanks for verifying.
