### ISSUE TITLE
Role name with slash "/" character cannot be Edited nor Deleted

### ISSUE THREAD

**Issue by monoludic** [OrchardCMS/OrchardCore#4410]
1. Create a new role named "role/withSlash"
2. Try to Edit or Delete it

=> Error 404 : the page cannot be found.

**Comment by hishamco** [comment]
If this allowed I think it will throws an exception, we need to deny such input

**Comment by hishamco** [comment]
If this allowed I think it will throws an exception, we need to deny such input

**Comment by sebastienros** [comment]
Looks like it's correctly encoded, but something is blocking it

**Comment by hishamco** [comment]
Really!! at my side the issue the slash in the url

**Comment by sebastienros** [comment]
What I mean is that the slash is correctly "encoded" when the url is generated, but clicking the link triggers and issue which is not generated by OC. In OC it should just work. It might be blocked by IIS, or Kestrel, I have to check more.
