### ISSUE TITLE
Orchard Core Documentation "Edit on OrchardCMS/OrchardCore" links broken

### ISSUE THREAD

**Issue by jeremycook** [OrchardCMS/OrchardCore#4411]
The "Edit on OrchardCMS/OrchardCore" links are broken. For example, when viewing the https://orchardcore.readthedocs.io/en/dev/docs/getting-started/ "Edit on OrchardCMS/OrchardCore" links to https://github.com/OrchardCMS/OrchardCore/edit/master/docs/docs/getting-started/README.md but should link to https://github.com/OrchardCMS/OrchardCore/edit/dev/src/docs/getting-started/README.md

**Comment by Skrypt** [comment]
Fix it! 😄  ... please 😄

**Comment by agriffard** [comment]
OK, fixed in dev.

I had to add this in mkdocs.yml:
`edit_uri: edit/dev/src/`

unless it is automatically set to `edit/master/docs/`
See https://www.mkdocs.org/user-guide/configuration/#edit_uri

**Comment by jptissot** [comment]
Could we close this ?
