### ISSUE TITLE
The main-menu in the Layout.cshtml doesn't generate Menu any more.

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#4413]
After upgrade to .netcore3.0, with latest orchard core build: 

The below code in the "Layout.cshtml" file doesn't generate the Menu any more.

**Comment by orchardc** [comment]
`<menu alias="alias:main-menu" cache-id="main-menu" cache-fixed-duration="00:05:00" cache-tag="alias:main-menu" />`

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/4360/files

**Comment by sebastienros** [comment]
But we didn't change anything on the shape. And we are running things out of the new versions correctly

**Comment by orchardc** [comment]
Thank you both!

I tried ` <contentitem alias="alias:main-menu" cache-id="main-menu" />` but it also doesnt generate the Menu content...

**Comment by sebastienros** [comment]
ah, this is in razor ... so many it was broken? But it's definitely not <contentitem>, this should still be <menu>

**Comment by orchardc** [comment]
I remember this issue happened before, it might not be related to .net core 3.

**Comment by orchardc** [comment]
How can I provide more detail log about this issue? It is not showing the Menu, but the Menu content is there, no change. I also tried to publish the Menu content, without luck...

**Comment by jtkech** [comment]
This is exactly what we have in `TheTheme` that i just tried

    <menu alias="alias:main-menu" cache-id="main-menu" cache-fixed-duration= ..." />

Do you still have this in your `_ViewImports`

    @addTagHelper *, OrchardCore.Menu

And a reference on the `OC.Menu` module in your theme project file.

Also check if VS didn't add any item groups in your theme project file that would prevent your `_ViewImports` to be correctly embedded.

**Comment by orchardc** [comment]
Thank you @jtkech , it is indeed because of missing reference of OrchardCore.Menu. I now added it to via nuget, the menu is back now with `<menu alias="alias:main-menu" cache-id="main-menu" cache-fixed-duration="00:05:00" cache-tag="alias:main-menu" />`
