### ISSUE TITLE
A strange thing after moving to VS2019 + .netcore3

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#4414]
Previously when debugging my custom Theme, I can directly make changes to HTML page or CSS/JS files, then refresh the browser it will apply the change immediately; after VS2019 upgrade, such changes don't apply unless I stop debugging and re-run it. 

The environment variables are default:
![image](https://user-images.githubusercontent.com/16193516/65731124-58373f80-e0bc-11e9-8f8d-087b30be2e06.png)

Any idea?

**Comment by sebastienros** [comment]
@jtkech

**Comment by jtkech** [comment]
> I can directly make changes to HTML page

Do you mean razor or liquid views? If so i did it recently and it was working.

I will re-try it asap.

In your main app do you use

    <PreserveCompilationReferences>true</PreserveCompilationReferences>

It is now required, we check it before registering razor runtime compilation services

**Comment by awyl** [comment]
The env variable has changed name to `DOTNET_ENVIRONMENT`.

**Comment by jtkech** [comment]
Just tried in debug mode from VS, it works when updating a liquid / razor view template file.

In our `launchSettings.json` we still have

    "ASPNETCORE_ENVIRONMENT": "Development"

**Comment by jtkech** [comment]
Oh, do you meant that you were using env variables and that you had to change its name with the `DOTNET_` prefix?

**Comment by jtkech** [comment]
With `TheTheme` just tried to update a .css file, it also works afer doing a browser clear cache + refresh.

**Comment by jtkech** [comment]
If you still have the issue, maybe do a clean and / or rebuild on your theme and check in its project file if VS didn't add any item groups on your assets that would prevent them from being correctly embedded.

**Comment by jtkech** [comment]
Which version are you using? If the last based on netcore3.0, see our theme project files, e.g we use.

    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>

**Comment by orchardc** [comment]
Thanks @jtkech , you are right. 
`  "ASPNETCORE_ENVIRONMENT": "Development"` need to be added in the `launchSettings.json` file.

It is now works as before. Previously I didn't have this though.
