### ISSUE TITLE
Add Menu-ContentType with existing contentItem

### ISSUE THREAD

**Issue by stantoxt** [OrchardCMS/OrchardCore#4423]
![addmenucontentitemfromlink](https://github.com/stantoxt/MarkdownResource/raw/master/pictures/addmenucontentitemfromlink.gif)
At Now,we can just add Menu-ContentType ContentItem from custom link.
But I want to achieve this directly from existing not-menuContentType ContentItem.
Please give me some guide.I hope I can contribute on this.

**Comment by jtkech** [comment]
In your content type you need to specify the `MenuItem` stereotype.

**Comment by stantoxt** [comment]
> In your content type you need to specify the `MenuItem` stereotype.

Thanks,I will have a try.

**Comment by sebastienros** [comment]
You need a new type on Menu Item that would use a content picker to select a content item, and extract its address.
