### ISSUE TITLE
A Js issue

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#4427]
https://github.com/OrchardCMS/OrchardCore/blob/55d1e89a1b9d60815ece4a38130e834e0a2fdb43/src/OrchardCore.Themes/TheAdmin/Assets/js/admin.js#L1

IE does not support this syntax。

**Comment by deanmarcussen** [comment]
Recommend we try with https://www.npmjs.com/package/gulp-babel to see if we can't transpile this so we can still write es6 

perhaps after https://github.com/OrchardCMS/OrchardCore/pull/4425

**Comment by hishamco** [comment]
@EternityTeam thanks for reporting this, I just added this before RC, but seems @agriffard pushing a PR as @deanmarcussen mentioned before

I will keep tracking this after the PR got merged

thanks
