### ISSUE TITLE
Media editor fields regressions - buttons disappear or don't work

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4428]
Couple of regressions with the media editor and media attached field editor.

The delete button doesn't seem to work anymore (permanently disabled)
![image-delete](https://user-images.githubusercontent.com/13782679/65816217-e7457400-e1f0-11e9-92dd-236f8c64cf0c.gif)

And with the media attached field editor the add button doesn't reappear after deleting an image until you publish and re edit the page.

![image-add-missing](https://user-images.githubusercontent.com/13782679/65816231-0ba15080-e1f1-11e9-9a13-6abfbd67e549.gif)

**Comment by matiasmolleja** [comment]
Hi Dean!
I can repro the second one. I will look at it.

But I can't repro the first one, the one where the delete button is always disabled.
Is the issue that you can't select the image by clicking on it? This button is meant to work on selected items only. So if no item is selected it is disabled.

**Comment by jptissot** [comment]
@deanmarcussen do you have a url field on that page ?

**Comment by deanmarcussen** [comment]
Hi Matias,

No you're totally right, the first one isn't an issue at all. 
To be honest, I was just clicking around after I came across the second issue, to see if anything else might have happened to it and I just assumed because it had been set to allowmultiple=false and could only have one that the delete button would always be active, but if it's by design, all good
