### ISSUE TITLE
script at="foot" is no longer working at RC

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4432]
I am using 
```    
<PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-rc1-10064" />
```

Below code used to work. It is used inside a module's admin controllers' views.
```
<script at="Foot" src="~/Crucible.Module/js/admin/index-view/output.js" asp-append-version="true"></script>
<script at="Foot">
    System.import("admin/index-view/index");
</script>

**Comment by dodyg** [comment]
![render](https://user-images.githubusercontent.com/1761249/65817972-592bb680-e20d-11e9-88ee-112d8b2e87fd.png)

**Comment by sebastienros** [comment]
If a tag helper is not rendered it's usually because you are missing a addTagHelper directive in the viewimports

**Comment by giannik** [comment]
Don't know if related , but had the same issue in a Theme when publishing
the release version.The tag was not rendered , even though viewimports was
correct.
Once I added a reference to Orchard.ResourceManagement.csproj  it worked.
Debug version worked fine.

**Comment by dodyg** [comment]
Yup, adding this reference fix the issue.

```<PackageReference Include="OrchardCore.ResourceManagement" Version="1.0.0-rc1-10064" />```

I might have deleted the reference during upgrading to .NET Core 3.0.

**Comment by dodyg** [comment]
Now I realize why I didn't suspect that I was missing an assembly reference. I already had ```@addTagHelper *, OrchardCore.ResourceManagement``` properly set at `_ViewImports.cshtml` and assumed that ASP.NET Core would throw a compilation error if the assembly doesn't exist.

Well, no. `@addTagHelper` doesn't insist that the assembly specified exists. 

![non-existant-tags](https://user-images.githubusercontent.com/1761249/65829407-8c218900-e2a5-11e9-82fd-30ae25f1d338.png)

**Comment by jtkech** [comment]
Yes, a module view is precompiled in the context of the module, when building the module, and the razor compiler needs to find the tag helper assembly, that why here the module needs to reference it.

When a module razor view is compiled at runtime (as in dev mode), so in the context of the application, if the app already references the needed assembly, it works even if the module doesn't reference it.
