### ISSUE TITLE
BUG: Enabling Content Item Inside Tenant is now working

### ISSUE THREAD

**Issue by abomadi** [OrchardCMS/OrchardCore#4439]
For some reason if a tenant tried to enable Taxonomy Feature, it will not be enabled until the host tenant enable it.

**Comment by hishamco** [comment]
@Skrypt is this intentional or it's a bug?

**Comment by Skrypt** [comment]
bug

**Comment by deanmarcussen** [comment]
I can't repro this.

Can you provide some more information on your configuration?

Are you using a shared database between tenants or seperate databases?

**Comment by abomadi** [comment]
@deanmarcussen my bad as i was i reported it on hurry
i am using using rc-1-10004 nugets core and cms, unfortunately i have cleared the logs, separate databases, it throw an unhandled exception on the UI.
2 tenants 
Host Tenant > Taxonomy Disabled
Child Tenant > Taxonomy Enabled Crashes , Unless i enable it on Host Tenant.

**Comment by deanmarcussen** [comment]
@abomadi Could you retry and send the unhandled exception?

Without that it's dificult to track down the issue, as when I try and test it works fine.

**Comment by abomadi** [comment]
@deanmarcussen i will be closing this issue for now because it was on  rc-1-10004, i will give it a try on the dev build if it's still exists i will reopen.
Thanks
