### ISSUE TITLE
Unable to edit roles

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#4441]
Ver: 1.0.0-rc1-10075
![微信截图_20190929232258](https://user-images.githubusercontent.com/14150259/65834683-20c0d100-e310-11e9-9845-0c8905cfbcb5.png)

**Comment by hishamco** [comment]
Please refer to #4410

**Comment by hishamco** [comment]
Sorry I thought it's a duplicate for #4410, @EternityTeam could you please write the steps to reproduce this?

**Comment by EternityTeam** [comment]
I've found out that there's a permission definition. The permission appearing in the impliedBy parameter must be defined above。
![微信截图_20190930011253](https://user-images.githubusercontent.com/14150259/65835973-954f3c00-e31f-11e9-8fcf-936a3f383961.png)
This may not be a bug, but it's easy to make mistakes.

**Comment by hishamco** [comment]
Happy to hear that
