### ISSUE TITLE
Response compression module

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#446]
Will we use Microsoft.AspNetCore.ResponseCompression to make gzip compression ?

**Comment by sebastienros** [comment]
Yes, we can make it a module. Same for reponse caching, and the rewrite middleware. When there are options in these middleware we can make them settings.

**Comment by agriffard** [comment]
Do we make the same kind of feature for gzip compression that has been done for Response caching?

**Comment by agriffard** [comment]
How do we implement gzip compression?

Create a module and a setting to enable it?

**Comment by sebastienros** [comment]
New module (can be refactored to group similar features later) 

Custom feature, settings are the options for the middleware:
https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.1&tabs=aspnetcore2x

**Comment by sebastienros** [comment]
I might want to take a look and also cache setting for static files. These two are killing performance on standard browsers.
