### ISSUE TITLE
Restart tenant when changing the ReverseProxy settings

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4461]
The tenant needs to be restarted when changing the ReverseProxy module's settings.

Original issue: 
If the current scheme is https, the Setup button of the Tenants page should redirect to a url using https.

**Comment by jptissot** [comment]
Looking at the code, it seems the Request.Scheme is already being used to build the url. We are using Kubernetes to host this application, so maybe the scheme is not properly set because the internal communications between the reverse proxy and the Orchard Service / Pod are not encrypted.

**Comment by jptissot** [comment]
Also, the code is duplicated here: 

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Tenants/Controllers/ApiController.cs#L313
and here: 
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Tenants/Views/Admin/Index.cshtml#L24

**Comment by jptissot** [comment]
I think we could change these links to start with `//` instead of `http(s)://` that way the browser will take care of using the current scheme for the links

**Comment by sebastienros** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.0

UseForwardedHeaders

**Comment by deanmarcussen** [comment]
Don't we have those in the reverse proxy module?

**Comment by jptissot** [comment]
Ah, I think you are right @deanmarcussen

**Comment by sebastienros** [comment]
Boom! if you use a reverse proxy you need the reverse proxy module ;)

**Comment by jptissot** [comment]
Learn something new every day. 

I enabled the module, checked the options. It did not work. 

Went to site general settings, save to force tenant restart. It worked

**Comment by jtkech** [comment]
So, maybe the reverse proxy module is missing a tenant restart in its settings driver.

**Comment by sebastienros** [comment]
@jptissot do you think @jtkech is right and that would solve it?

**Comment by jptissot** [comment]
Yes, I will update the issue description

**Comment by MatthijsKrempel** [comment]
Assign it to me ;)
