### ISSUE TITLE
Required title in widget does not highlight

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4463]
The required title part of widgets present in a Flow / Bag part does not highlight properly when a title is not provided. We should support Bag / Widget validation with highlighting.

**Comment by agriffard** [comment]
@ns8482e Has this issue been fixed?

**Comment by ns8482e** [comment]
Yes, fixed in #6175

**Comment by jtkech** [comment]
So close it as it is fixed through #6175
