### ISSUE TITLE
More Wysiwyg editor: insert image from assets, see the image and resize it

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#4468]
Hi guys, 

my boss think that our customer can't understand the preview functionality and he ask me to improve the Wysiwyg editor in OrchardCore. He ask me about the possibility to see the image and resize it inside the editor. 

I have made it from a customization of the OrchardCore HtmlField editor, added the resize plugin of trumbowyg editor and other stuff inside the OrchardCore.ContentFields module. At the end I have created a javascript file that use the OrchardCore Media modal to add image in the HTML field from the assets. I have done it because I don't know how to use the MediaShapes class out of the OchardCore.ContentFields module for an HtmlField.

Now I would like to understand if it is the right way to customize and create a new version of the HtmlField Editor, if I can do a PR about it and how to improve it to give to you something useful and beautiful: I think about the possibilities to use the razor resize helper (to allow user to see his image on the HtmlField editor I have to write HTML inside it) and I don't know if the razor resize helper can be used in this way.

**Comment by sebastienros** [comment]
Inline resizing and image manipulation would be very useful. Have you checked how we did it in Orchard 1? That would be something to look at first IMO.

Then you can start by sharing a gif of the experience you implemented already. And surely create a Draft PR so we can see how you did it.

**Comment by PiemP** [comment]
I'm using the trumbowyg resize plugin that is not good like the tinymce image tools. Is not user friendly like the tinymce ones and to improve it I need to do some work but I have checked trumbowyg on image moving and it lack a lot. 

![demo](https://user-images.githubusercontent.com/2736009/66193682-67595700-e693-11e9-8f41-f306c48301ab.gif)

On the O1 demo I have seen that you use tinymce. If you don't see problem about it I can try to implement an HtmlField editor that use tinymce 5 and load image from the OrchardCore's assets. 

But I don't have a lot of free time to dedicate it...I would try to do my best...

**Comment by PiemP** [comment]
the tinyMCE version
![demo_tinymce](https://user-images.githubusercontent.com/2736009/66316302-bb746d80-e917-11e9-9b18-bd3b417a4d70.gif)

**Comment by sebastienros** [comment]
I am not talking about tinymce. In the Media page, there is an Edit button to do client side image editing. It's independent from the editor.

**Comment by PiemP** [comment]
For now I have do this...

![demo_2 0](https://user-images.githubusercontent.com/2736009/66767654-31954900-eeb1-11e9-820b-a22f67f1f591.gif)

Finally I've understand what you want and what have you do in O1. When I have more free time, I try to implement the O1 image editor.

**Comment by sebastienros** [comment]
Thanks

**Comment by meodemsao** [comment]
when i insert image from gallery editor return text like

{{ "product/image/basic-1280.jpg" | asset_url | img_tag }}

where i can config editor can return image tag like above

**Comment by agriffard** [comment]
@meodemsao See #2822

**Comment by meodemsao** [comment]
> @meodemsao See #2822

thanks, i hard fix for my current website. Hope pull request approve soon
