### ISSUE TITLE
Media Assets GraphQl query not working well with Azure Blob

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4469]
```
  mediaAssets(includeSubDirectories: true) {
    lastModifiedUtc
    path
}
```

returns no folders, or files, with Blob Storage. Works fine with local storage.

Will PR. 

Hmm more complicated than first thought. Might refer back to O1

**Comment by jrestall** [comment]
Good to see someone else is making use of these queries at least :)

**Comment by deanmarcussen** [comment]
Also good to see there are other kiwis using Orchard Core :)
