### ISSUE TITLE
Resources in custom templates (aka themes)

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#4472]
In these PRs:
- [X] TheAgencyTheme: https://github.com/OrchardCMS/OrchardCore/pull/4434 
- [x] TheBlogyTheme: https://github.com/OrchardCMS/OrchardCore/pull/4433
- [x] TheComingSoonTheme: https://github.com/OrchardCMS/OrchardCore/pull/4435 

Font-awesome is now added in the templates, the same way they are in the original ones from StartBootstrap. However historically we never took everything, like font-awesome, but were using the resource defined in the OrchardCore.Resources module, which for the requested version (5) only went on the CDN. We also have a 4.7 version of font-awesome in the Resources module, but it's not used from what I have seen.

I checked the licence and it seems fine to redistribute it. This is also what StartBootstrap is doing.

I am suggesting two actions:
- Define a custom Resource Manifest in each theme, that will use the local assets embedded in each theme, but also the corresponding CDN version (if available, for instance without any customization, which it shouldn't have btw). This way we'll be able to serve both local and remote files based on the site settings.
- In the OrchardCore.Resources module only have the assets that are used by the modules. Mostly admin assets in this case.

/cc @Skrypt @agriffard @deanmarcussen @jptissot

**Comment by agriffard** [comment]
Done in the Agency theme. 
In the ResourceManifest and layout.liquid, I prefixed the resources by `vendor-`to distinguish them from the ones in the OrchardCore Resources module.

**Comment by deanmarcussen** [comment]
I like the sound of it.

Font awesome 4.7 I imagine was just left over from the upgrade to 5 

What would you suggest to do with the non admin related scripts and sass in OrchardCore.Resources? 

- Remove and stop providing for custom themes (easiest for us, but breaking for some)
- Maybe move to a feature, and make something depend on that feature to activate it(with a note they're deprecated?)
- Or move the admin scripts to a feature? Just for some clear seperation

- Bootstrap
- Font awesome
- jQuery
(I doubt anyone is using code mirror on the front end)

and how do we feel about including the vue source and the font awesome code in the Resources module as well for admin related issues https://github.com/OrchardCMS/OrchardCore/issues/4271
