### ISSUE TITLE
Liquid page with negative slice using 0 offset

### ISSUE THREAD

**Issue by azGreg** [OrchardCMS/OrchardCore#4481]
**{{ "abcdefg" | slice: -3, 2 }}** outputs "ab" rather than "ef".

I simplified the issue to the following steps:
    create a new Agency site
    create a new page with liquid widget
    defined body of liquid page as
        {{ "abcdefg" | slice: -3, 2 }}

The associated test case in fluid works.

**Comment by azGreg** [comment]
This seems like a simple enough issue that I should be able to handle.
I am able to trace to line 238 of LiquidViewTemplate.cs, but I can't step into the following:
            // Otherwise, we don't need the view engine for rendering.
            return await template.RenderAsync(templateContext, encoder);

**Comment by hishamco** [comment]
Seems this related to fluid, I will try to reproduce that issue in the Fluid repo

**Comment by sebastienros** [comment]
The issue was that anything starting with a `-` would be interpreted as an identifier and not a negative number. So even `{{ -3 }}` would output nothing.

I fixed Fluid and will update the version.
