### ISSUE TITLE
Liquid TagHelpers mapping

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#4485]
I made some test regarding @jptissot question in #4426 thread.

Let say I have following TagHelper:

```
[HtmlTargetElement("form", Attributes = "oc-workflow-type-id")]
public class FormTagHelper : TagHelper
{
   public string OcWorkflowTypeId { get; set; }

   [HtmlAttributeName("oc-workflow-type-id")]
   public string WorkflowTypeId { get; set; }

    ...
}
```

And now I would like to use this tag helper in my liquid page:

```
{% block "form", method:'POST', oc-workflow-type-id:'4v7sbayf1x2mntg0qrynbcmmcf' %}
...
{% endblock %}
```

This will not work. TagHelper will execute but properties will not be mapped.

When I change code to:

```
{% block "form", method:'POST', oc_workflow_type_id:'4v7sbayf1x2mntg0qrynbcmmcf' %}
...
{% endblock %}
```

`_` insted of `-`  this will work but only `OcWorkflowTypeId ` property will be populated.

Questions:

1. Should using `-` be valid in liquid and right now there is some kind of error?
2. I would expect `[HtmlAttributeName("oc-workflow-type-id")]` annotation to work and map field but right now it doesn't

**Comment by sebastienros** [comment]
I don't know about the liquid syntax, will have to check.

**Comment by sebastienros** [comment]
@jtkech 

@jptissot says that when `props-*` is used in a tag helper, the bridge doesn't work.

**Comment by jtkech** [comment]
Okay, i think i found the issue, it now works.

I'll do more checks and a PR tomorrow
