### ISSUE TITLE
how we can do searching on a website which is built on orchardcore

### ISSUE THREAD

**Issue by shefeek-stratagile** [OrchardCMS/OrchardCore#4487]
Hi,
How can i do searching on a website using orchard core @sebastienros 
the whole website is controlled by orchrdcore

**Comment by shefeek-stratagile** [comment]
@davidhayden can u please guide me throw this

**Comment by hishamco** [comment]
This powered by Full-Text search, I will need to ping @Skrypt coz he is the guy that doing Full-Text stuff all the time :)

**Comment by sebastienros** [comment]
Open the /search url, if you have configured the Search Settings it will work.
