### ISSUE TITLE
[Feature Request] Add Lorem Ipsum to editor

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4488]
@sebastienros I think you suffer a lot when you trying to demo something y going to lorem Ipsum website, copy text, paste it here

Me and other folks too suffer from such thing, it would be nice if we add this as a feature to add a custom button on the trumbowyg editor, so when it's clicked you will have a lorem ipsum without leaving the current site .. this is cool for demos and create dummy data during development

**Comment by sebastienros** [comment]
I don't suffer, it's a choice. I could use a chrome extension if I wanted.

**Comment by hishamco** [comment]
Believe me almost if not all the designers and developers used when they create design time data
