### ISSUE TITLE
Content Field Indexing inclusion

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4491]
Are all the content fields automatically indexed when this module is enabled?

https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/

Because in this case, I only set `Include this element index` for `Occupation` and not the rest of the fields yet they appear in the index.

![text-index-2](https://user-images.githubusercontent.com/1761249/66326959-3e062880-e92a-11e9-8822-d26405386703.png)

**Comment by Skrypt** [comment]
The `Include this element index` option is for the Lucene index (search index) or also eventually ElasticSearch. This does not affect the SQL index for fields itself. Maybe to avoid confusion we could say that we are simply mapping content fields with that feature enabled. There is currently no configuration options, it will simply map all the content fields for you. Adding configuration options could be something to think about eventually. Also, if you need to map/index specific fields I suggest that you build your own IndexProviders and make it customized to your needs. This is always a better option if you don't want to make your db get too big over time.
