### ISSUE TITLE
Bug - Documentation not specifying which nuget package dependency to add

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4492]
There is a problem in the documentation section titled "Code Generation Templates" located here:
https://orchardcore.readthedocs.io/en/latest/Templates/README/

It used to specify the name of the nuget package.  It does not anymore.
Instead users rely on a animated gif to see which nuget package to add as a dependency.
This is a poor.

Please type the name of the nuget package dependency(s) using text in the documentation.

**Comment by agriffard** [comment]
Please, use this documentation instead: https://orchardcore.readthedocs.io/en/dev/docs/templates/

**Comment by sebastienros** [comment]
@JoshTango  How did you get the link to this?
I already updated the docs badge on the README in case that was it.

**Comment by JoshTango** [comment]
it was bookmarked from a while back !!

**Comment by sebastienros** [comment]
Thanks
