### ISSUE TITLE
The best way to relate hierarchical structure 

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4494]
For a structure such as 

Sector > Program > Project > Albums, what is the best way to design the relation between them?

I think using the container/list will make the UI too complex because of the nested structure. Right now the way I think about it is to create a text field (with predefined input) for each children content to relate to their parents. The problem of course this list needs to be maintained manually.

![text-input-list](https://user-images.githubusercontent.com/1761249/66380487-da2a4100-e9b7-11e9-94e5-7df94da7ff4b.png)

Therefore
- Program will have ProgramSector text field
- Project will have ProjectProgram text field
- Album will have AlbumProject text field

I wonder if there's a better way.

**Comment by dodyg** [comment]
Ok it looks like the better way is simply to do

- Sector -> ListPart of Program
- Program -> ListPart of Project
- Project -> ListPart of Album

**Comment by jptissot** [comment]
You can also use the ContentPicker.

**Comment by hishamco** [comment]
What about Tags & Taxonomies?

**Comment by dodyg** [comment]
> ContentPickerField

Oh I didn't know this. Excellent. 

>  Tags & Taxonomies

Sector > Program > Project > Albums. It's hard to accommodate this using taxonomies. The relations are direct.

**Comment by hishamco** [comment]
> Sector > Program > Project > Albums. It's hard to accommodate this using taxonomies. The relations are direct.

Ya if it represents an entity aka content type, so `ContentPickerField` is the a good option

**Comment by dodyg** [comment]
Wouldn't using `List` a more natural? Is there any downside of using List that I am not aware of?

**Comment by jptissot** [comment]
I don't think there are downsides. The only thing content picker field allows you to do is reuse a piece of content in many parents. For example, I am using the same form in many pages so I reference the form with a content picker.

**Comment by jptissot** [comment]
There is also a taxonomy picker field I believe.

**Comment by hishamco** [comment]
It would be nice to know when choose what, for instance Use `Taxonomy` for create tagging, `ListPart` for ... etc

**Comment by jptissot** [comment]
@dodyg There is also a LocalizationSetContentPicker for multilingual content.

Use case: 

Event that has LocalizationPart.
Team that does not have a LocalizationPart but relates to the event. 
Team would have a LocalizationSetContentPickerField that points to the event to be able to get the localized version based on the current culture when rendering.

**Comment by JoshTango** [comment]
I have been greatly interested in this ability for a while now, its important to hammer this out.
One of the other issues is if I am on a child how do I discover my parent?

**Comment by dodyg** [comment]
@JoshTango  

![parent-2](https://user-images.githubusercontent.com/1761249/67302547-544ae180-f4f1-11e9-9cad-cf5373fa3a9d.png)

The highlighted part is the content id of the parent, then you can use

```
{% assign my_content = Content.ContentItemId[Model.ContentItem.Content.ContainedPart.ListContentItemId] %}
```

to obtain the parent info.

**Comment by jptissot** [comment]
@dodyg this is specific to Lists. For the content picker(s) the code is a bit different see: 
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.ContentFields/#contentpickerfield

**Comment by jptissot** [comment]
@dodyg how did you end up implementing this one ?

**Comment by dodyg** [comment]
I am using ListPart for now but I am not sure whether this will be the final decision. I am still exploring.

**Comment by jptissot** [comment]
I am looking to do something similar as well. @sebastienros suggested I try with a taxonomy to define the hierarchy and just select the taxonomy term with a field in my types. This keeps all types flat but allows you to define a hierarchical structure of content without having lots of nesting.

**Comment by arkadiuszwojcik** [comment]
@dodyg in your hierarchical Content Items with `ListPart ` are you also have experiencing this #4749 (see second comment) ?

**Comment by dodyg** [comment]
@jptissot that looks like an interesting approach actually. I wonder how it will look like in being able to query them though.

If my hierarchy is Sector > Program > Projects, I will need to show

"Sector : Social Empowerment"

 - Program A
 - Program B
 - Program C

**Comment by dodyg** [comment]
@arkadiuszwojcik  I haven't gone far in this. I will keep you updated.

**Comment by jptissot** [comment]
I believe there is a way to get all ContentItems that are tagged with a Taxonomy term. We would need to investigate and try.

My use case was a Knowledge Base. So I had a Knowledge Base Article, which would be tagged with a Category.

**Comment by dodyg** [comment]
This is how to load related content based on Taxonomy

![anatomy-of-taxonomy](https://user-images.githubusercontent.com/1761249/68859296-9e3d7680-06ef-11ea-8417-7e1e06c284b6.png)

**Comment by dodyg** [comment]
So far, for this type of structure `Sector > Program > Project > Albums.`, ListPart is the most obvious way to structure them.

- Sector has ListPart of Program
- Program has ListPart of Project
- Project has ListPart of Albums

**Comment by dodyg** [comment]
The problem of using Taxonomy for `Sector > Program > Project > Albums.` structure can be seen here.

![taxonomy](https://user-images.githubusercontent.com/1761249/68880483-0605b880-0714-11ea-92b7-999b234f020f.png)

- The first level in the hierarchy is Sector
- The second level is Program

This display is a taxonomy field in the "Project" content type. As you can see from the UI, the field shows the whole hierarchy. User can pick the taxonomy term that is meant for Sector but there is no way to limit that user can only select program taxonomy term.

**Comment by sebastienros** [comment]
> there is no way to limit that user can only select "Program" taxonomy term.

Isn't there? At least in Orchard 1 we have an option to define which level of the taxonomy can be selected. Don't we have it here too? If not we could add it. I am pretty sure we can already limit to "leaves" (last level)

**Comment by dodyg** [comment]
> At least in Orchard 1 we have an option to define which level of the taxonomy can be selected. 
This doesn't exist at the moment

> I am pretty sure we can already limit to "leaves" (last level)
Yes this exists

**Comment by jptissot** [comment]
I assume it would be useful for your use case if the Taxonomy picker field could also be limited to display a subset of elements

**Comment by dodyg** [comment]
Yes. I can think of two ways:

- Filter by one or more levels, e.g. show level 2, 3 and 4 here.
- Filter by one or more of the properties of the Taxonomy Term properties, e.g. show me all the taxonomy terms that has `{Type : "Project"} `.

**Comment by dodyg** [comment]
An even better solution is to allow to populate these dropdowns based on custom queries. We can have a "Relation" Picker and have it powered by a custom query. This way we can have a nice way to relate one content to another.

**Comment by dodyg** [comment]
The larger issue here is finding the best way to relate one content to another.

Parent > Child (List Part)

Right now to associate a child content to a parent via ListPart is to create the child content through the List Items interface of the parent Content Item. This is very restrictive. There is no way current to create a child content and associate it to the parent item.

**Comment by JoshTango** [comment]
I'm going to throw in a different idea.  In the entity framework system if I have 2 entities with a relationship to each other we actually have 3 objects.  2 for the entities and 1 for the relationship.  I had thought about making a content definition type just for the relationship.  This is actually best for many to many relationships. 

I don't believe any of this relationship stuff was thought through properly when Orchard Core was designed.  The issue here is that I bet orchard core attracts a lot of developers where as drupal and wordpress attract a lot of web designers.  We are trying to be developers with orchard core which is good.

**Comment by dodyg** [comment]
I am trying to use Content Picker at the moment for 'Sector > Program > Project > Albums'.

So

- `Sector` has no Parent
- `Program` has `Parent Field` Content Picker of Content Type `Sector` or `Program`.
- `Project` has `Parent Field` Content Picker of Content Type `Program`.
- `Album` has  `Parent Field` Content Picker for `Project`.

So this solves the issue of editing child content and not knowing the parent (ListPart has this problem).

**Comment by dodyg** [comment]
# Summary of approaches to structure hierarchical content.

The structure required is `Sector > Program > Project > Albums`. 

## ListPart

This approach allows a Content Item to have children contents. Each child content is stored on its document.

To achieve our required structure, we need to do the following:

- `Sector` has ListPart of `Program`.
- `Program` has ListPart of `Project`.
- `Project` has ListPart of `Albums`.

### The Good Part

- The Admin section automatically create the interface to list the children contents.
- The Admin section automatically associate the parent content with the children content.
- From the children shape you can refer to the parent ContentItemId via `ContainedPart.ListContentItemId`.
- Since the child content is stored separately (in contrast of `Bag`), you can obtain and process them individually.

### The Bad Part

- When you are editing the child content, there is no information available at the UI about the parent content (contained type)
- You can't switch parent content. If your program A belongs to Sector B, you cannot switch to Sector C from the editor.

**Comment by willnationsdev** [comment]
I really like the design of the ContentPickerField solution. How about this?

1. Add a `ContentTree` ContentType.
    1. Has a list of allowed ContentTypes.
2. Add a `ParentContentPart` ContentPart.
    1. ContentPickerField "Tree" of `ContentTree` type.
    2. ContentPickerField "Parent' of any ContentType.
    3. Implements `IPositioned`. No field is rendered for Edit templates by default.
3. When editing the part, the user must first choose a Tree value. This populates the allowed types of the "Parent" field.
4. Define a `ParentChildrenMapIndex` that tracks which ContentItemIds are children of a given ContentItemId. Users can then optionally choose to render those children in various templates by quickly fetching them.
5. Define a `ContentTreeMapIndex` that tracks which ContentItemIds are members of a given ContentTree's ContentItemId AND describes a tree structure of them with a JObject field. Users can then easily do a batch query for all ContentItems associated with a given ContentTree and construct proper relationships between the elements, including positions in each branch, to construct whatever UI they want for the ContentTree. Could even potentially render it differently based on the ContentTypes of the various branch roots relative to those branch's immediate children, etc. Very flexible.

Also, with this solution, it is clearly possible to make a given ContentItem be parented to multiple kinds of trees depending on your needs.

Example uses:

- Admin
    - Have alternative ContentItem management pages in the admin that render a tree structure (e.g. indents rows of tabular data based on relationships, etc.).
- Frontend
    - Generates "child pages" at the bottom of frontend web pages.
    - Generates breadcrumb menus dynamically using the path in the tree to the current page.
    - Generates a sidebar navigation menu, optionally locally scoped to the current page and its children.

Thoughts?

**Comment by ricocsharp** [comment]
Is there any examples of how to use this Content Picker Programatically in Headless recipe

**Comment by ricocsharp** [comment]
Is there any examples of how to use this Content Picker Programatically in Headless recipe?

**Comment by ricocsharp** [comment]
Is there any examples of how to use this Content Picker Programatically in Headless recipe?

**Comment by ricocsharp** [comment]
Is there any examples of how to use this Content Picker Programatically in Headless recipe?

**Comment by Skrypt** [comment]
I think that ultimately we would need to adjust the UI of the ListPart to allow moving content items from one list to another. Also, allow adding content items that are already created in a list.

@dodyg I like what you did there, it should surely be copied over to a discussion "Show and tell" as a small guideline.

**Comment by Piedone** [comment]
We now have docs for this: https://docs.orchardcore.net/en/latest/docs/topics/content-relationships/.
