### ISSUE TITLE
Lost Password

### ISSUE THREAD

**Issue by thesecuritycompany** [OrchardCMS/OrchardCore#4496]
Hello, 

I've recently joined a company who need to update their Orchard content. Unfortunately the old developers who set it up have gone. 

I've tried following various guides online that suggest changing a field in the users table to "Clear" to remove the hashing. I've then changed the password to something like "Password#123" to try an gain access but to no avail. 

I'm wondering if these guides are old. Do you have a mechanism to reset passwords in the newer version of Orchard? Or can I inject a user in to the DB?

**Comment by sebastienros** [comment]
I answered in the other repos
