### ISSUE TITLE
Placement is not applied with Placement.json

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4499]
Filename placement.json is case sensitive. If someone creates file name with Placement.json or Placement.JSON then placement is not applied.

**Comment by hishamco** [comment]
Even the sorce using `placement.json`, the underlying FileSystem APIs are using `FileInfo.Exists` which is case sensitive

**Comment by sebastienros** [comment]
Eveyrthing is case sensitive, it has to work in linux too.
