### ISSUE TITLE
Template creation and Placement helpers

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4501]
During the meeting, we had a discussion about the templates and @sebastienros reminded us the great feature that was available in O1: The Shape Designer Tool.
It allowed us to create easily some alternate files in our themes.

When activated, the page was rendered with a wrapper around each shape inside. 
You could hover and click on a shape and a footer panel was displayed with the information of the shape.
Then, you could select which content type, part, field or display type (any metadata that you can use in an alternate) and create the corresponding file in your theme.

It would be great to have a similar feature in OC but may be just open the templates admin page with the name of the corresponding alternate you want to edit.

Another admin tool I would like to see would be a visual form in which you specify those metadata and other informations that you can use in an alternate (zone, url, ...) and it autogenerates the corresponding template name or the json that you need to target it in placement.json.

**Comment by sebastienros** [comment]
To get the differentiators of a field, we need a separate tab in the field settings to display a sample placement rule.

**Comment by agriffard** [comment]
@Piedone Please add a link to your Shapes tool.

**Comment by Piedone** [comment]
Here it is: https://github.com/OrchardCMS/OrchardCore/issues/6853#issuecomment-670985699

**Comment by agriffard** [comment]
https://docs.orchardcore.net/en/latest/docs/reference/modules/Templates/
https://docs.orchardcore.net/en/latest/docs/reference/modules/Placements/
