### ISSUE TITLE
Support setting HttpContext.Items items in liquid templates

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4504]
Add two liquid filters to set and get values from the HttpContext.Items dictionary. This will allow us to set values in a top level template and consume it in a deep hierarchy.

As an example, to access a value that comes from the Page ContentType inside a FieldTemplate that is rendered by a Widget. I need to pass the value in each of these templates:  
Page -> FlowPart -> Widget -> FieldTemplate

**Comment by sebastienros** [comment]
In `RequestLiquidTemplateEventHandler` add the `HttpContext` property (like `"Request"`).
Then expose the `Items` property and the collection so it can be read.

Create a new tag, `set_httpcontext_items` that takes a list of named arguments
