### ISSUE TITLE
Remove antiquated password complexity requirements from Setup page

### ISSUE THREAD

**Issue by angusmf** [OrchardCMS/OrchardCore#4506]
https://www.pluralsight.com/blog/security-professional/modern-password-guidelines

It's easy to show that longer password are more secure than shorter complex ones.

Imagine two password requirements, one that allows only decimal numbers, the other also allows hex values a-f, so an additional 6 characters of "complexity". A single character password allows 10 possible values under the first rule (0-9), and 16 under the second (0-f). So the second rule is "better" for short passwords. But, allowing two characters increases the possible combinations for the first rule to 10^2, which is of course much, much larger than 16.

The value comes in choosing passwords made of long, memorable but non-obvious phrases, such as:

"remove antiquated password complexity requirements from setup page"

Quite hard to guess. If you feel like adding lots of extra characters to it, go ahead:

"rem0ve ant!quated passWord complexity requirements from setup page111337"

Both are much better than:

"Ant!quated1"

**Comment by hishamco** [comment]
I don't think it's good idea, but I'd like to hear from the other folks

**Comment by sebastienros** [comment]
We are only using the defaults that are defined in the ASP.NET Identity library. And this can be configured to your own needs from the main Startup file.

Examples:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-3.0

https://adrientorris.github.io/aspnet-core/identity/configure-password-policy.html

**Comment by hishamco** [comment]
I think the question has been answered
