### ISSUE TITLE
OrchardCore loading in Program.cs?  Possible?

### ISSUE THREAD

**Issue by helzgate** [OrchardCMS/OrchardCore#4508]
MS Visual Studio Team just put out a video showcasing how amazing OrchardCore is for building modular, multi-tenant ASP.NET Core apps.  The [video is found here](https://www.youtube.com/watch?v=yrQaKv2mxFU&t=5s ).  They only show configuring your host application to use OcrhcardCore by loading the necessary bits within the Startup.cs.  Is there a way to load OrchardCore support earlier than the startup.cs and instead load it within the Program.cs?  I tried not to bother you guys and I asked this question on stackoverflow but I'm not getting any responses and a vote to close my question has started.  

Here is my current Startup.cs:

```
 public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCore();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseOrchardCore();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    Log.Information("returning Hello World...");
                    await context.Response.WriteAsync("Hello World!");
                });
                endpoints.MapGet("/hi", async context =>
                {
                    Log.Information("returning Hi...");
                    await context.Response.WriteAsync("Hi!");
                });
            });
            

        }
    }
```
I created a seperate library application that contains all the serilog essentials I need for logging.  I can then drop it into this host application and it works.  The problem is, I need to load serilog within the Program.cs because that is where the app starts and the guys at serilog suggest you start logging there as well in case there are errors starting your host in IIS.

**Comment by sebastienros** [comment]
We already have a sample using Serilog. It's actually part of the standard templates we ship. One with Nlog and one with Serilog. 

Here is a pointer to the documentation: https://github.com/OrchardCMS/OrchardCore/blob/0326e2a19fb49b16b53f1ef357be06b9cc8679bf/src/OrchardCore/OrchardCore.Logging.Serilog/readme.md

You should also be able to find it in the docs site, with the search box.

And here is the template where we expose it:
https://github.com/OrchardCMS/OrchardCore/tree/3ebcce93c634ab27f6970aaaf1fd6632d9cfd17a/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Web

**Comment by helzgate** [comment]
Perfect!  Thanks!

**Comment by helzgate** [comment]
The more I thought about it the more I realized this doesn't solve my desired approach.  I wasn't simply wanting to know how to incorporate Serilog in a multi-tenant way.  Matter fact, I don't even care about multi-tenant.  I am approaching this regarding a purely modular approach in reference to the the video from Microsoft Visual Studio Team I mentioned above.  

I'm wondering if I can create a libray project that has all the bits necessary for Serilog and then simply drop that into a host application using OrchardCore.  This way our company can build core modules our company needs for all future projects and our developers can simply drop in those modules with very little configuration.  I can already do this with OrchardCore because most required functionality can be loaded within the Startup.cs.  But Serilog is different, it requires you load within Program.cs and therein lies the problem, you can't load a library module within the Program.cs that I know of.

**Comment by sebastienros** [comment]
You have to chose if you want it in the Program.cs or not. If you want it in, put it there like I showed. If you don't, then use a module registering it, but you will lose the features you said will only work in the Program.cs.

**Comment by helzgate** [comment]
OK, thanks for the explanation!
