### ISSUE TITLE
Content items custom filtering extension?

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#4524]
I want to implement TitlePart.Title like 'or Code.Value like', can I customize FilterAsync or otherwise resolve it?

![image](https://user-images.githubusercontent.com/16968103/66733298-ab1d3f00-ee91-11e9-8dbb-cb4841e2735f.png)
![image](https://user-images.githubusercontent.com/16968103/66733419-1535e400-ee92-11e9-8cf1-2a164a960921.png)

![image](https://user-images.githubusercontent.com/16968103/66733611-b02ebe00-ee92-11e9-9f31-e7de175b9aad.png)

![image](https://user-images.githubusercontent.com/16968103/66733626-bde44380-ee92-11e9-9e2e-668c800e165d.png)

**Comment by chinasqzl** [comment]
Stupid method！！！
![image](https://user-images.githubusercontent.com/16968103/66794558-8ded7c80-ef34-11e9-9c32-50771726ce89.png)
![image](https://user-images.githubusercontent.com/16968103/66794600-aeb5d200-ef34-11e9-8c2d-1b9329c1cd85.png)

**Comment by sebastienros** [comment]
You can implement IContentAdminFilter with your own filter. But right now there is no way to add a UI element to this page, we might need to change it (make it composable with shapes). It would also allow use to add Culture filters. Yo ucan alreadt use QueryString if you want.
