### ISSUE TITLE
Autoroutepart pattern needs default value

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4526]
Right now the pattern field is empty when you add Autoroutepart to your Content Type hence it won't work at all at first try. This is not user friendly. One has to lookup the documentation (https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Autoroute/) to figure it out.

![autopart](https://user-images.githubusercontent.com/1761249/66755092-9774d700-ee97-11e9-8f24-712035a20eaf.png)

**Comment by sebastienros** [comment]
Good idea. Just a comment as I saw you using TitlePArt in many places already. you should use `ContentItem.DisplayText` instead. TitlePart assigns its value to it, and we will remove the content in `Content.TitlePart` eventually. See TitlePart as an editor for the DisplayText. we only kept it in the content  for backward compatibility.

**Comment by sebastienros** [comment]
`{{ ContentItem.DisplayText | slugify }}`
