### ISSUE TITLE
Question: For Spa Module

### ISSUE THREAD

**Issue by abomadi** [OrchardCMS/OrchardCore#4527]
i would like to know how to inject scripts from module controller, also to inject the module base href from the controller as well

**Comment by hishamco** [comment]
Resource management is responsible for manage scripts & styles. You can inject your scripts too

**Comment by abomadi** [comment]
Yeah but how ? an example or documentation how to include resources inside view controller page

**Comment by sebastienros** [comment]
Doc is here: https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Resources/
