### ISSUE TITLE
MemoryCache not Immutable

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4533]
While refactoring sitemaps I came across what may be an issue with how we are using `IMemoryCache` to maintain cached `Documents`.

Taking an example, the `QueriesManager` uses a store/manager pattern to update both the DocumentStore and and memory cache of the Document.

Updating the Document is happening in the Controller using lines like

```
var editor = await _displayManager.UpdateEditorAsync(query, updater: this, isNew: false);
if (ModelState.IsValid)
{
    await _queryManager.SaveQueryAsync(model.Name, query);
    _notifier.Success(H["Query updated successfully"]);
    return RedirectToAction("Index");
}
```

The problem is that items retrieved from `IMemoryCache` are pointers, so any update to them updates the actual object in the cache. 
Any validation errors may still update the cache object, but not the database object making the information out of sync.

It isd also dificult with this to get the original unchanged document from cache in the manager to compare original values vs updated values.

I wrote a simple test to confirm what I suspected

```
namespace MemoryCacheTests
{
    public class MemoryCacheTests : IClassFixture<WebApplicationFactory<MemoryCache.Startup>>
    {
        private readonly WebApplicationFactory<MemoryCache.Startup> _factory;

        public MemoryCacheTests(WebApplicationFactory<MemoryCache.Startup> factory)
        {
            _factory = factory;
        }

        [Fact]
        public void TestMemoryCache()
        {
            const string cacheKey = "CacheKey";
            using (var scope = _factory.Services.CreateScope())
            {
                var cache = _factory.Services.GetRequiredService<IMemoryCache>();
                // Make document
                var doc = new Document
                {
                    Foo = "original",
                    Item = new DocumentItem
                    {
                        Title = "original"
                    }
                };

                // Set in cache
                cache.Set(cacheKey, doc);

            }

            using (var scope = _factory.Services.CreateScope())
            {
                var cache = _factory.Services.GetRequiredService<IMemoryCache>();
                // Retrieve Document
                var doc = cache.Get<Document>(cacheKey);

                // Alter Document. 
                // Do not set back in cache.
                doc.Foo = "altered";
                doc.Item.Title = "altered";
            }

            using (var scope = _factory.Services.CreateScope())
            {
                var cache = _factory.Services.GetRequiredService<IMemoryCache>();
                // Retrieve Document
                var doc = cache.Get<Document>(cacheKey);
                Assert.Equal("original", doc.Item.Title);
                Assert.Equal("original", doc.Foo);

                /*
                Message: 
                Assert.Equal() Failure
                    ↓ (pos 0)
                Expected: original
                Actual:   altered
                    ↑ (pos 0)
                 */
            }
        }
    }
}
```

Not sure what the solution is, or if this is even considered an issue, but just expected behaviour.

DeepCloning when retrieving documents from cache?

**Comment by jtkech** [comment]
This is one of the goal of #4001 but not only, see e.g [my comment](https://github.com/OrchardCMS/OrchardCore/pull/4001#issuecomment-519758233) where i tried to define some caching rules. I need to reput my mind on it but e.g for the `QueriesDocument.Queries` i use an `IImmutableDictionary`.

**Comment by jtkech** [comment]
@deanmarcussen did you see my above comment?

Yes, i worked on this in #4001 with immutable collections and / or some cloning e.g when there are child collections and to not change too much things everywhere, e.g for admin menus and type definitions.

Then maybe in #4450 you will have to update accordling `SitemapManager`.

**Comment by deanmarcussen** [comment]
@jtkech Yes, as always you are 10 steps ahead of me.

Looks good for #4001 with the immutable collections, but I will pull down today to have a better look. 

Then I will apply Jt's Cache Rule No. 3 ! to sitemaps

The only concern I have initially is that the Immutable collections are Immutable, but the contents still are not. 

So if I adjust the test above, I think it will still fail, if an item inside the Immutable is changed.
But you have also changed the pattern to re read the document from the database store, before saving, so possibly it is not an issue, or at least if it is, it's a minor issue.

But I will pull #4001 today and try it first :)

**Comment by jtkech** [comment]
Yes, when you update an object and cache it, you need to work on a new instance. With an immutable collection that's ok for the collection itself, but the rule also apply to the contained objects. So, that's ok when you add / remove an item, but when you want to update an existing one you have to work on a new instance before setting it in the collection. And so on if an object itself holds a child collection.

E.g, because `MenuItem` is used in many places, for the `AdminNode` that inherits from it, in place of doing some deep cloning e.g by using an immutable collection for the child items, to not have to update the code everywhere, i did some shallow clonings but when updating the child items this is done on a new collection (but less optimized in term of allocations than an immutable collection).

**Comment by deanmarcussen** [comment]
Yes, add / remove it is no problem at all. It is always update that is more complicated.

I pulled #4001 and like the look of it, plus as you say it's not changing too much.

Regarding update, I look at a couple of places where we do it, `Templates` and `Queries`, as they are both simpler examples, due to no child collections.

Templates is without display drivers, which makes it simpler, and does exactly as you say, works on a new instance.
```
var template = new Template { Content = model.Content, Description = model.Description };

await (model.AdminTemplates
    ? _adminTemplatesManager.RemoveTemplateAsync(sourceName)
     : _templatesManager.RemoveTemplateAsync(sourceName)
);

await (model.AdminTemplates
     ? _adminTemplatesManager.UpdateTemplateAsync(model.Name, template)
      : _templatesManager.UpdateTemplateAsync(model.Name, template)
 );
```

Queries however does still work on the same instance during the update cycle, a call to the `DisplayManager` to perform the update on the memory cached mutable object. Then later a call to update it in the document store.
```
var editor = await _displayManager.UpdateEditorAsync(query, updater: this, isNew: false);

if (ModelState.IsValid)
{
    await _queryManager.SaveQueryAsync(model.Name, query);
    _notifier.Success(H["Query updated successfully"]);
    return RedirectToAction("Index");
}
```

The driver itself also does the update on the same object, rather than creating a new object / viewmodel as some other content part drivers do, so if validation partly fails, the object is mutated in memory, but will not be reconciled to the document store.

So this is maybe outside the scope of #4001 but is does seem to be a pattern we follow in many places.

Just for ideas we could do something like this
```
// if we removed the query from the document/cache here
await _queryManager.RemoveQueryAsync(model.Name, query);

// then updated it. it is a safe updated. because it's no longer in the cache.
var editor = await _displayManager.UpdateEditorAsync(query, updater: this, isNew: false);

if (ModelState.IsValid)
{
  // then we can re add it safely.
  await _queryManager.UpdateQueryAsync(model.Name, query);
}
```

But that also raises concurrency issues if there was a read (or execute) happening at the same time, so not a great idea, but a concept.

Another idea would be to activate a new instance of the query object, give it the identifier (name in queries case), pass it to the driver, update it, and then swap it in the Immutable Collections.

Or just make sure we use viewmodels in the displaydrivers rather than touching the object directly.

But just ideas, this was something I noticed in Sitemaps (which I will update to use ImmutableDictionary), which just didn't seem quite right, and equally may not be a particularly big issue.

**Comment by jtkech** [comment]
Oh yes, maybe because i started with `Templates` without drivers and then i missed it for `Queries`, good catch thanks. In that case, e.g see in `ContentDefinitionManager`, i use a scoped cache holding a clone value of the tenant singleton cache.

Sometimes i refrain myself from doing more things in a PR so that it stays "mergeable". But happy to see that someone want to do more around these concerns ;)

I will rework on it this night.

**Comment by deanmarcussen** [comment]
Cool @jtkech, just suggestions. 

I'll keep an eye on #4001  for implementing with sitemaps as well :)

It sounds like you have it totally under control, so I'll close this, and comment further on #4001
