### ISSUE TITLE
InputPart: Additional attributes

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4536]
When you add an Input in a Form, allow to specify some additional attributes?
autocomplete
autofocus
class
maxlength
min, max, step for Number
pattern
required
size
style

**Comment by jptissot** [comment]
Agreed. I had to implement my own widgets to do this.

**Comment by arkadiuszwojcik** [comment]
In my opinion this is too much as for 1.0 and #4426 would solve all those problems in much easier and more granular way. Basically building Forms using flows and widgets is very burdensome experience right now in OC without proper, feature rich form module. My current solution is based only on pure liquid and few TagHelpers:

```
{% block "form", method:'POST', oc_workflow_type_id:'4w7sn68kan411ztyr5ps4rvsss', oc_activity_id:'4v7ybayf1x2mbtg0qrynbcmmer' %}

<h2>Contact form</h2>

{% antiforgerytoken %}

<div class="form-group">
	<label for="Name" class="form-control">Name</label>
	{% helper "form-input", id:'Name', name:'Name', placeholder:'Enter your name', class:'form-control' %}
	{% helper "form-validation", for:'Name', class:'form-control' %}
</div>
....
</div>
```

So basically it is better to start with TagHelper that is responsible for model binding and validation so more flexible and then think if some better/detailed form designer should be actually in scope of OC core modules.

**Comment by jptissot** [comment]
A bit hacky but you can easily add an Attributes field and render it (sanitized, raw) into the markup ;)

**Comment by sebastienros** [comment]
@arkadiuszwojcik I think the two options have a reason to be. I agree that we should have ways to build any form from liquid. We can already do that from Razor. But I also think we should provide some basic Form support with Flows.

**Comment by sebastienros** [comment]
Let's try to add these properties in a different tab, and @agriffard suggested to use an open list like the Predefined editor:

![image](https://user-images.githubusercontent.com/1165805/67042206-3ee24b80-f0dc-11e9-9659-1320cbee71cc.png)

**Comment by sebastienros** [comment]
`Attributes` property on the stored model I assume with that

**Comment by ns8482e** [comment]
Users of Form designer are non-technical, like marketers, content editors they are least concerned about  developer features in Form designer,  Form designer should be simple enough to used by non technical users - rather than providing overwhelming features  that confuse users.

Developer can always customize and use liquid or cshtml or even create custom module

**Comment by ns8482e** [comment]
Personally I like even ID and Name of html id to be auto generated .

**Comment by sebastienros** [comment]
@ns8482e that's something that can be done at the same time. Maybe move `ID` to the list of dynamic attributes as it is not as required as the `name`. Also if we also add a `Label` property like it was requested in another issue, we should use the provided `id` in the `for` of the label.

**Comment by ns8482e** [comment]
You may find my comment irrelevant here do to my limited knowledge what you are trying to accomplish but - if you are required to to use liquid part or needs developer related attributes in Form then, why don't you use plain old html  `<form>` markup? It's simpler than making Form designer complicated.

**Comment by sebastienros** [comment]
@ns8482e as long as these attributes are not invasive in the UI, like in a separate tab, that will be fine for end users.

**Comment by sebastienros** [comment]
It's all about "the cliff" when you provide some settings, then you have to completely fallback to the code to fix a simple issue.

**Comment by TFleury** [comment]
Maybe we can use "classical" content fields for that, so we have text, number, boolean... fields available.

We just need to place the editors in a "Settings" zone.
