### ISSUE TITLE
Title and Render title are repeated on each Input add to a Form in a Widget.

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4537]
When you edit a Form, which has the stereotype Widget, each input has a 'Render title' checkbox but they have the same Name 'LayerMetadata_LayerMetadata_RenderTitle' so when you wan to uncheck one, the first one is toggled.

This is also a bit weird because the Form has a Title and the Widget as a Title as well.

![image](https://user-images.githubusercontent.com/703248/66836169-2a2d7880-ef61-11e9-8353-4f780d71fe3b.png)

**Comment by sebastienros** [comment]
@ns8482e this one is for you, right? You are the expert now ;)

**Comment by agriffard** [comment]
In fact, it only occurs when you use a form in a Widget, not on a Page that has a FlowPart. 
It seems that the widget's 'Title and checkbox' are added on every input in that case.

**Comment by ns8482e** [comment]
@sebastienros I have never worked on layers module yet, this could be nice opportunity to learn about layers module. However I think you guessed it right it may be related to flow, I have seen similar behavior due to Prefix for nested widgets in Flow module while working on Javascript.

**Comment by deanmarcussen** [comment]
@ns8482e For info there is this issue with the layers module which may have a connection, due to prefix issues. 

https://github.com/OrchardCMS/OrchardCore/issues/2908

**Comment by ns8482e** [comment]
#4079 this issue is also related.
