### ISSUE TITLE
Multi-user conflicts: How to resolve multiple versions of a content item

### ISSUE THREAD

**Issue by songbirdflies** [OrchardCMS/OrchardCore#4540]
Hello, 
We had two users updating a content item at the same time. One user published first and the other user then over-wrote the previously published version. The client asked if there was a way to be notified of new versions while working on the same content item. 

In the future, would it also be possible to revert to a previous version of a content item or compare the two side by side? 

Song

**Comment by Skrypt** [comment]
@sebastienros on Gitter : 

>the design we had designed in O1 would be to show a hint in the editor that it's already open, and optionally block the save (checkout). It's easy to implement with a custom feature that would use timestamps in database, and a local javascript poll script to check for checkouts. Or use signalr. So yes, if someone wants to work on it that shouldn't be hard to make.

**Comment by sebastienros** [comment]
I search in the O1 repos but couldn't find the issue, just a mention. Where I said we should create a Lease object in the database that can only last as long as the period between Lease Polls which are done with javascript. It would just be a warning (with a confirmation) in case someone forgets their browser instance open on a specific page.

**Comment by hishamco** [comment]
What if we:
- Create a virtual copy of the current edited content item (ContentItem.Updating)
- So when someone try to edit the same content item it will get notified in (ContentItem.Loaded)

If someone forget the browser instance open, we can set a timeout for that version, so if it exceeds that the notification will no longer show up

**Comment by sebastienros** [comment]
Two issues in this question:
- Prevent users from editing the same content item concurrently (database lease + timeout)
- Provide a UI to see/compare/restore previous versions
  - This one is implemented in O1, we should do it in OC too. I know some company is already working on it (audit trails). I'll ask if they are still doing it.
