### ISSUE TITLE
Unable to configure user settings via recipe

### ISSUE THREAD

**Issue by peterkeating** [OrchardCMS/OrchardCore#4542]
Currently there doesn't seem to be a way of modifying user settings (e.g. `UseSiteTheme` within `LoginSettings`) via a recipe so it needs to be configured manually. Would be great if the `LoginSettings`, `RegistrationSettings` & `ResetPasswordSettings` could have a deployment step to handle import/export which would remove the need to remember to configure them manually when setting up environments.

Had a quick look at the custom settings deployment step, but that doesn't seem like a way to achieve this.

**Comment by jptissot** [comment]
@peterkeating it is possible to modify / set the settings via a recipe. But indeed it is not possible to export those settings via a deployment plan.
I found this structure by looking in the database for the Settings document.

Here is an example

```
{
      "name": "Settings",
      "Calendar": null,
      "TimeZoneId": "America/New_York",
      "AppendVersion": true,
      "LocalizationSettings": {
        "DefaultCulture": "en",
        "SupportedCultures": [ "fr", "en" ]
      },
      "LoginSettings": {
        "UseSiteTheme": true
      },
      "ResetPasswordSettings": {
        "AllowResetPassword": true,
        "UseSiteTheme": true
      },
      "RegistrationSettings": {
        "UseSiteTheme": true,
        "UsersCanRegister": true
      },
      "SmtpSettings": {
        "AutoSelectEncryption": false,
        "DefaultSender": "...",
        "DeliveryMethod": 0,
        "EncryptionMethod": 0,
        "Host": "...",
        "PickupDirectoryLocation": null,
        "Port": 25,
        "RequireCredentials": false,
        "UseDefaultCredentials": false,
        "UserName": null
      }
    }
```

**Comment by peterkeating** [comment]
@jptissot Not sure why I didn't try that, works perfectly 👍
