### ISSUE TITLE
Error publishing package on myget

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#4543]
"NuGet" deployment for branch "master" has been skipped because current branch is "dev"
    Deploying using NuGet provider
    Publishing OrchardCore.1.0.0-rc1-10263.nupkg
        to https://www.myget.org/F/orchardcore- preview/api/v2/package...
    Error publishing package. NuGet server returned 413: The package size is too large.
        The feed owner may have to upgrade the MyGet subscription to resolve this issue.

**Comment by sebastienros** [comment]
Yeah :/ apparently the feed is too big now for nuget ... that includes my other projects though. I will try to clean, and start thinking about a more scalable solution.

**Comment by sebastienros** [comment]
I will try with GitHub package repositories today. I don't see any mention of limits.
