### ISSUE TITLE
Workflow HttpRequestFilterEvent does not trigger workflow

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4544]
I am unable to get a HttpRequestFilterEvent filter to trigger a workflow.

[TestHttpWorkflow.zip](https://github.com/OrchardCMS/OrchardCore/files/3732164/TestHttpWorkflow.zip)

I debugged the `OrchardCore.Workflows.Http.Filters.WorkflowActionFilter` and the current route is always the 404 even if I try to trigger the https://localhost:5001/OrchardCore.Tests/User/ValidateUser url that is defined in a workflow.

/cc @jtkech

**Comment by jtkech** [comment]
Just tried an `HttpRequestFilterEvent` with the `OC.Contents.ItemController.Display` `Get` action, then with the `OC.Users.AccountController.Login` `POST` action. It works in both cases.

**Comment by jtkech** [comment]
Is your controller action executed?

**Comment by jptissot** [comment]
Oh. Maybe i misunderstood what this does. I thought it could be used to define new routes that do not physically exist to extend the functionality.

**Comment by jptissot** [comment]
Basically I was looking for a way to add a new route via the workflow. I know i could have used the `HttpRequestEvent` but I was looking for an easier to read route.

**Comment by jtkech** [comment]
Yes, need to be tied to an existing controller action, otherwise you need to use an `HttpRequestEvent`.

**Comment by stevetayloruk** [comment]
I can't seem to get this to work for POST.  I've created a custom module with a route, controller and action and can get it to work for GET but not working for POST.  I've also tried using the LogOff action on OC.users with no affect.

I'm posting json to this endpoint and it doesnt fire.
