### ISSUE TITLE
OrchardCore.Theme.Targets fixed target framework

### ISSUE THREAD

**Issue by protoncm** [OrchardCMS/OrchardCore#4545]
In the `OrchardCore.Theme.Target.csproj` fixed target framework on package path. here is a part of the file. 
```
  <ItemGroup>
    <None Include="OrchardCore.Theme.Targets.props" Pack="true">
      <PackagePath>build\netcoreapp3.0\OrchardCore.Theme.Targets.props</PackagePath>
    </None>
  </ItemGroup>
```

It should be a parameter as `$(TargetFramework)` instead of  `netcoreapp3.0` ?

**Comment by jtkech** [comment]
Yes much better, good catch! thanks

I let you do a PR to update it if you want, you can do it from github directly by just editing the file.

**Comment by protoncm** [comment]
Sure i will
