### ISSUE TITLE
Liquid doesn't work

### ISSUE THREAD

**Issue by sunnysteam** [OrchardCMS/OrchardCore#4547]
I have configured Liquid,but in workflow,it doesn't work.
Liquid configuration:
![image](https://user-images.githubusercontent.com/19546500/66899951-772b5080-f02e-11e9-9fa4-95608cd39224.png)
Property Task:
![image](https://user-images.githubusercontent.com/19546500/66900137-ce312580-f02e-11e9-8daa-360bd6fba218.png)
Email Task:
![image](https://user-images.githubusercontent.com/19546500/66899921-611d9000-f02e-11e9-9f95-384d812dcffb.png)
Recived Email without Liquid:
![image](https://user-images.githubusercontent.com/19546500/66900084-b35eb100-f02e-11e9-91d8-e5b66d970b88.png)
It make a misstake:
![image](https://user-images.githubusercontent.com/19546500/66900204-f6208900-f02e-11e9-95be-abb352013f88.png)

**Comment by jptissot** [comment]
I think you need to do `Workflow.Properties.Article` not just `Article`

**Comment by sunnysteam** [comment]
> I think you need to do `Workflow.Properties.Article` not just `Article`

**Comment by sunnysteam** [comment]
> 我认为你需要做的`Workflow.Properties.Article`不只是`Article`

Thank you very much.I use this,can get the value.
