### ISSUE TITLE
is it possible to add catagories and sub-catagories and products in orchard cms ? 

### ISSUE THREAD

**Issue by MuhammadTalha10** [OrchardCMS/OrchardCore#4556]
i am new to orchard core and i want to create a site on orchard cms that have shown multiple products linked with categories and sub categories and manage them through admin dashboard. 
i also want to know is it possible to change(edit some functionalities like creating any crud) cms backend in asp.net core ?

**Comment by sebastienros** [comment]
Yes. Create a Product content type. Then enable the TAxonomies module and create a new Taxonomy named Categories. In the Product type then add a Taxonomy Field named Categories, using the Categories taxonomy.
