### ISSUE TITLE
Unit Test : SQL Query and Lucene Query that returns documents

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#4558]
Create unit test that assert that these types of queries will work in a Liquid template.

**Comment by vulfh** [comment]
Hi ,
I would like to take this issue as my first issue. With whom can I discuss it ?

**Comment by hishamco** [comment]
@vulfh AFAIK @Skrypt is the Lucene guy who I knew ;)

**Comment by vulfh** [comment]
@Skrypt  could you please give some details regarding the issue (I am new in the project, but I want to become a contributor)

**Comment by Skrypt** [comment]
We currently have functional tests to create a tenant which uses TheBlogTheme recipe. This recipe contains a Lucene Query which can sometimes fail to execute and return error on the CI while building. But we should have a Unit Test for this instead that can catch the error before executing this functional test. One Unit Test should mock a Liquid template which uses a Lucene Query and the other one a SQL Query and assert that these would return proper results on the rendered template. It could use "fake data" as long as this data is also indexed with Lucene. No need to create a whole tenant with database for that.

@sebastienros Please confirm, I've maybe forgot something since I opened this one since a while.

**Comment by vulfh** [comment]
@Skrypt - Thank you for your reply. Are you talking about ShouldListBlogPostWhenCallingAQuery test ? This is the only test I found execute the recentBlogPosts lucene query.

**Comment by Skrypt** [comment]
Yes this is the one

**Comment by Skrypt** [comment]
up

**Comment by vulfh** [comment]
@Skrypt - Do you mean it done by somebody else?

**Comment by Skrypt** [comment]
No I'm upping the issue in the list so that people can see it's a "good first issue" since it is hacktober fest like @sebastienros suggested yesterday. It's open for anyone to pick up. If you say you started working on it and close to having it done then I can simply assign you on the issue.

**Comment by vulfh** [comment]
@Skrypt  - I started to work on it, I am not close to have it done, but it would be great if you could assign it to me please

**Comment by vulfh** [comment]
@Skrypt  - I am bit stuck with LuceneIndex  creation and ShellSetting.Name assignment and would like to ask a question or 2  . Do you use this forum for technical conversation ?

**Comment by Skrypt** [comment]
Too old. Closing.
