### ISSUE TITLE
Project module created from CLI dotnet new command, with part option true, does not build

### ISSUE THREAD

**Issue by neman** [OrchardCMS/OrchardCore#4564]
I have `orchardcore.projecttemplates.1.0.0-rc1-10279` installed
**UPDATE**: I updated to `orchardcore.projecttemplates.1.0.0-rc1-10307` and stil got the same result.

Steps to reproduce:

1. `dotnet new ocmodulecms -n CmsPart -A true`
1. Open project folder e.g C:\Temp\CmsPart
1. Build project using `dotnet build`
1. Build failed with the following result
![image](https://user-images.githubusercontent.com/350314/67079836-2d5c7a80-f194-11e9-9e83-d1dbe23cb0a9.png)

When I open the project, I got usings which does not exists as files in project

![image](https://user-images.githubusercontent.com/350314/67080980-9513c500-f196-11e9-8964-6ff5e7d0220d.png)

> C:\Temp\CmsPart> dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   3.0.100
>  Commit:    04339c3a26
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.0.100\
> 
> Host (useful for support):
>   Version: 3.0.0
>   Commit:  7d57652f33
>

**Comment by neman** [comment]
And this line is the reason for the build error

https://github.com/OrchardCMS/OrchardCore/blob/f21b24cf4f2a7ab441bae03eba09f9322ab235f8/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Module/.template.config.src/template.json#L37

```json
"modifiers": [
        {
          "condition": "(PartName=='')",
          "exclude": [
            "Migrations.cs",
            "Drivers/MyTestPartDisplayDriver.cs",
            "Handlers/MyTestPartHandler.cs",
            "Models/MyTestPart.cs",
            "Settings/MyTestPartSettings.cs",
            "Settings/MyTestPartSettingsDisplayDriver.cs",
            "Settings/MyTestPartSettingsViewModel.cs",
            "ViewModels/MyTestPartViewModel.cs",
            "Views/_ViewImports.cshtml",
            "Views/MyTestPart.Edit.cshtml",
            "Views/MyTestPart.liquid",
            "Views/MyTestPart_Summary.liquid",
            "Views/MyTestPartSettings.Edit.cshtml"
          ]
        }
```

By Default part name is empty string, so these files are excluded from project.

**Comment by Skrypt** [comment]
It should not have added those lines if you don't have provided a AddPart=true

**Comment by Skrypt** [comment]
I understand but then if you don't provide a PartName then it should not try to create assets for you as you did not provide proper informations on your command. The other acceptable solution would be to always have a default PartName if none is provided.

**Comment by neman** [comment]
I think the best solution is to offer client seamless workflow. Either with not allowing creation of part without providing part name, or to have default name. 
Somebody should decide what is optimal and then can I try to create PR.

Also there should be some CI build check for this type of problems, later maybe.

**Comment by neman** [comment]
Now when I read this https://github.com/dotnet/templating/issues/1531 the only possible solution is to jave default part name. Currently is not possible to have conditionally required parameter.

**Comment by Skrypt** [comment]
Go for it! 😉

**Comment by sebastienros** [comment]
I think we should add the templates generation/build to the functional tests.

**Comment by neman** [comment]
Ok, I changed this in my local branch and tested the following scenarios:

1. `dotnet new ocmodulecms -n Part` -> no part files added
1. `dotnet new ocmodulecms -n Part -A true` -> added part files with default name **MyTest**
1. `dotnet new ocmodulecms -n Part -A true -P Neman` -> added part files with provided name **Neman**
1. `dotnet new ocmodulecms -n Part -P Neman` -> no part files added (basically the same as first one)

Should the description of parameters be changed now?
For example something like  _Add all files required for a part (with default name if not provided)_
or maybe to change AddPart description to _Add dependency injection for part in Startup.cs. If PartName is not provided, template will use default name_

![image](https://user-images.githubusercontent.com/350314/67147411-e3a78900-f294-11e9-8deb-1d006c68d21f.png)

![image](https://user-images.githubusercontent.com/350314/67147668-24080680-f297-11e9-855d-e8ef09e70b8d.png)

**Comment by Skrypt** [comment]
Create a Pull Request from your fork first.
And after, you can move forward with the adjustments on params description by adding an additional commit to your fork branch and it will be added to the Pull Request.

**Comment by neman** [comment]
I’m thinking now, why isn’t there only one parameter `AddPart` or `AddPartName` string type, instead of bool. I do not see point to have DI registration without necessary files for DI to have class to register. When I want to add part, it is more natural for me to provide PartName and that’s it. Why would I want to have DI only? 
Ok, now there is a default name for part, but it’s still awkward to have it in 2 steps. My 2 cents :)
