### ISSUE TITLE
"filter" is not implemented in the Lucene module

### ISSUE THREAD

**Issue by DaveEmmerson** [OrchardCMS/OrchardCore#4568]
In Lucene you can do a "filter", which is like "must", but does not affect the score and can also be cached which isn't the case for a "must".

https://lucene.apache.org/solr/guide/8_1/json-query-dsl.html#filter-queries

https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Queries/BooleanFilter.cs

**Comment by hishamco** [comment]
@Skrypt this for you too :)
