### ISSUE TITLE
couldn't access the admin page without https?

### ISSUE THREAD

**Issue by riyuexing** [OrchardCMS/OrchardCore#4569]
Today I created a web demo used OrchardCore according the guide.I installed OrchardCore.Application.Cms.Targets with nuget. Without https,I couldn't access the admin page.
In IIS this problem occured also. Could you help me to solve this problem?Thank you!

**Comment by jptissot** [comment]
I got the same issue a little while back. Had to clear chrome cache. Can you try another browser to see if the issue persists?

**Comment by riyuexing** [comment]
I have to add an https link with the demo web in IIS. It works fine with https. I don't know what's the problem.It may have nothing to do with the cache or browser.

**Comment by jtkech** [comment]
At least with Chrome, as soon as you have done a login under https, you can't do it through http.

It's related to how authentication and antiforgery cookies are managed. As @jptissot said try to clear the browser cache.

On my side, i completely close all the browser instances.

**Comment by riyuexing** [comment]
Thank you.I have got it.It's the problem of cookies.Just clear all,and it works now.
