### ISSUE TITLE
Module which uses separate/different database than OC Cms

### ISSUE THREAD

**Issue by neman** [OrchardCMS/OrchardCore#4575]
Can I create module/part for OC which uses different database than OC Cms?
And can I control which db provider will be used (Ef Core, Dapper...)

**Comment by hishamco** [comment]
AFAIK Orchard Core is heavily rely on YesSQL. Using other provider is need a lot of work if am not wrong. @sebastienros your thought

**Comment by sebastienros** [comment]
We have a module that uses Dapper directly. If you want a different database you just need to define the settings in appsettingsjson for instance, and do it. There is no limit for it.

**Comment by hishamco** [comment]
> We have a module that uses Dapper directly

Could you please refer it to me? coz I saw YesSQL primitives in many places in the code base, so I thought it is tightly coupled on it
