### ISSUE TITLE
lucene Query, compound filters wrong result 

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#4576]
![image](https://user-images.githubusercontent.com/16968103/67140682-85c47280-f28f-11e9-9e2a-99a076e98a82.png)

"Content.ContentItem.ContentType"="Project" and ("Content.ContentItem.DisplayText" like '%XXXXXXX%' or "Content.ContentItem.ContentItemId" like '%XXXXXXX%') "should" is invalid and the result is wrong ！

![image](https://user-images.githubusercontent.com/16968103/67140692-a8568b80-f28f-11e9-9622-d0ba19d38123.png)

**Comment by sebastienros** [comment]
you wrote 
` (ContentType = Project) OR ( (DisplayText = * ) OR (ContentItemId = *))`

Put the array of should inside the must, using an array too.

**Comment by chinasqzl** [comment]
{
  "query": {
    "bool": {
      "must": [
        {"term" : { "Content.ContentItem.ContentType" : "Project" }},
        {
          "bool":{
            "should": [
              {"wildcard" : { "Content.ContentItem.DisplayText" : "*{{search}}*" } },
              {"wildcard" : { "Project.Identifier" : "*{{search}}*" } }
            ]
          }
        }
      ]
  	}
  },
  "sort": { "Content.ContentItem.CreatedUtc": { "order": "desc" } },
  "size": 10
}
