### ISSUE TITLE
Rename Assets

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4582]
AFAIK "Assets" is a generic terminology used for scripts, styles, images .. etc, IMHO Media or Media Library is more clear than assets, and it has been used while for many CMSs

/cc @agriffard @Skrypt @sebastienros

**Comment by sebastienros** [comment]
It was called Media before, and we "decided", all together, to change it to Asset. So if this decision needs to be discussed you need to come with the arguments that we used to use Asset and what new arguments would make us change it back.

**Comment by sebastienros** [comment]
A link to the meeting (with timestamp) would also be valuable.

**Comment by hishamco** [comment]
> It was called Media before

I didn't know that

**Comment by agriffard** [comment]
https://www.youtube.com/watch?v=fOZGjZUcl00&index=50&list=PLuskKJW0FhJfOAN3dL0Y0KBMdG1pKESVn

https://github.com/OrchardCMS/OrchardCore/pull/1041

**Comment by agriffard** [comment]
We were already asking ourselves exactly the same questions 3 years ago.

https://www.youtube.com/watch?v=fOZGjZUcl00&list=PLuskKJW0FhJfOAN3dL0Y0KBMdG1pKESVn&index=163&t=1060s
