### ISSUE TITLE
issue in index lucence

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4587]
after update to the new version, i can not create or rebuild the indexes.

my website is stoped now, please give help to solve that.

`An unhandled exception occurred while processing the request.

ArgumentException: Codec '' cannot be loaded. If the codec is not in a Lucene.Net assembly, you must subclass Lucene.Net.Codecs.DefaultCodecFactory, override the Initialize() method, and call PutCodecType() or ScanForCodecs() to add the type manually. Call Lucene.Net.Codecs.Codec.SetCodecFactory() at application startup to initialize your custom codec.
Lucene.Net.Codecs.DefaultCodecFactory.GetCodecType(string name)
`

if i click on view in ContentItems, i get not found the page.

**Comment by Skrypt** [comment]
Rebuild your indexes.

**Comment by aghili371** [comment]
it is not possible i got an error too.

**Comment by Skrypt** [comment]
Delete the indexes in your App_Data folder to reset them.

**Comment by aghili371** [comment]
i did that before. i think it has a problem with the old database. i tested with the newer project, that worked fine. maybe it's better to have look at my repository if you have time.

**Comment by aghili371** [comment]
@sebastienros now i have a big problem, i cannot export data, i can not refresh the indexes. this project is online and i don't know what i should do.

**Comment by Skrypt** [comment]
If you made a backup of your database I strongly suggest you to take a look at this option. Else you could also try to pass over the exception to see if your website will render anything.

**Comment by aghili371** [comment]
@Skrypt @sebastienros  i did that. i set to old version but i got this error :
ArgumentException: Codec '' cannot be loaded. If the codec is not in a Lucene.Net assembly, you must subclass Lucene.Net.Codecs.DefaultCodecFactory, override the Initialize() method, and call PutCodecType() or ScanForCodecs() to add the type manually. Call Lucene.Net.Codecs.Codec.SetCodecFactory() at application startup to initialize your custom codec.
Lucene.Net.Codecs.DefaultCodecFactory.GetCodecType(string name)
`
i put my database in orchard source too, but it just looping and nothing happens. 
please check the log file maybe you fine some thinks there.
[orchard-log-20191022.txt](https://github.com/OrchardCMS/OrchardCore/files/3757354/orchard-log-20191022.txt)

**Comment by aghili371** [comment]
i rebuild the index ,after a long-time running, i got this error:

An unhandled exception occurred while processing the request.
FormatException: String '2019-07-31 03:24:55.2392615' was not recognized as a valid DateTime.
System.DateTimeParse.Parse(ReadOnlySpan<char> s, DateTimeFormatInfo dtfi, DateTimeStyles styles)

DataException: Error parsing column 2 (CreatedUtc=2019-07-31 03:24:55.2392615 - String)
Dapper.SqlMapper.ThrowDataException(Exception ex, int index, IDataReader reader, object value) in SqlMapper.cs, line 3633

**Comment by aghili371** [comment]
after some changes, i rebuild the index.
i run my database in the orchard source project.it can not show the content,

i have a big problem with my customer. 

i get export from the old one but it doesn't give me all the date, for example, ir doesn't export the users.
so what i can do? how you can help me?
please give me solution 
@sebastienros

**Comment by sebastienros** [comment]
https://github.com/StackExchange/Dapper/pull/1363

**Comment by aghili371** [comment]
@sebastienros @Skrypt 
i think i found my problem. the problem with the Permalink field. if I have Farsi words there, it doesn't show data. but with English words, it works fine.
please have look at Permalink render.

**Comment by hishamco** [comment]
While the issues is not related to Lucene, I think we need to close this one, feel free to file a new one with reproduced steps
