### ISSUE TITLE
error in add new blogpost

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4588]
i have this nee error in adding new blog post:

An unhandled exception occurred while processing the request.
SqliteException: SQLite Error 1: 'table Document has no column named Version'.

**Comment by muzzi-w** [comment]
@aghili371  this is probably related to...

YesSql update issues #4585

**Comment by hishamco** [comment]
Yep it's related, @deanmarcussen is your PR ready to merge?!!

**Comment by hishamco** [comment]
#4591
