### ISSUE TITLE
Autoroutepart pattern for localized content

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4589]
My goal is to achieve

- en/hello-world
- ar/hello-world
- fr/hello-world

What should I add to this pattern
```{{ ContentItem.DisplayText | slugify }}```

**Comment by dodyg** [comment]
I mean this pattern is not necessary if there is route based culture provider. I am only aware of the cookie one.

**Comment by jptissot** [comment]
Check out the Content culture picker feature. You can generate the autoroute with the LocalizationPart.Culture property.

**Comment by dodyg** [comment]
OK thanks.  So the working pattern is

```{{ContentItem.Content.LocalizationPart.Culture}}/{{ ContentItem.DisplayText | slugify }}```
