### ISSUE TITLE
Issues found by PVS-Studio

### ISSUE THREAD

**Issue by SashaSenichkin** [OrchardCMS/OrchardCore#4596]
Hello,
Developers of PVS-Studio C/C++/C#/Java static analyzer present their check report of the source code of 'Orchard Cms' in the article, containing the review of the most suspicious code fragments they discovered.

You can read article at the official site: https://www.viva64.com/en/b/0681/

The article doesn't cover all the issues that were found by the analyzer, so perhaps it would be interesting for you to review them yourself. In case you have questions, feel free to ask them.

Best regards,
Senichkin Aleksandr

**Comment by hishamco** [comment]
Thanks Senichkin for sharing this

/cc @sebastienros

**Comment by hishamco** [comment]
@SashaSenichkin thanks for the detailed report that I have read, but how we can have the whole list of the bugs, shall we download PVS-Studio? or is there another way to get the entire list

Thanks again

**Comment by SashaSenichkin** [comment]
sure, you can find full instruction here: https://www.viva64.com/en/b/0457/
download, https://www.viva64.com/en/pvs-studio-download/
register with:
Name: PVS-Studio Free
Key: FREE-FREE-FREE-FREE
i can send you my report, but you will need PVS extension to open it)

**Comment by hishamco** [comment]
Downloading ...

**Comment by sebastienros** [comment]
@SashaSenichkin I read your article and I think you got confused between Orchard 1 and Orchard Core as you still mention Outer Curve (probably from your previous article) and also as you say all the previous issues have been fixed. These are two different code base.

Thanks for the report, I hope can fix them.

**Comment by hishamco** [comment]
Why the extension is not enable me to use VS 2019?

**Comment by SashaSenichkin** [comment]
@hishamco some problem.. I'm use VS 2019 extension.. can you, please, describe your problem and how did you reach it?

**Comment by hishamco** [comment]
After downloading the extension to get the full report, the setup allow me to install it in 2015 & 2017 but the 2019 checkbox isn't checked. Are you target specific version of VS 2019?

**Comment by SashaSenichkin** [comment]
@hishamco can you, please, mail us to support@viva64.com to clear this situation up and discuss it there? Or we can mail you on the profile email address (hishamco_2007@hotmail.com) if it's more preferable.

**Comment by hishamco** [comment]
No problem you can email me

thanks

**Comment by Piedone** [comment]
I checked a few of the issues mentioned in the blog posts. These seem to be now outdated or initially invalid. We'll have proper static code analysis to uncover such issues on each build: https://github.com/OrchardCMS/OrchardCore/issues/7950.
