### ISSUE TITLE
Alias duplication check failure

### ISSUE THREAD

**Issue by pitaridis** [OrchardCMS/OrchardCore#4599]
I created a content type which contained Title, Html Body and Alias. For the Alias I used the following pattern so that it will automatically generate the slug using the display_text.

`{{ ContentItem | display_text | slugify }}`

It works only when we have a different display_text for each content. If I create two different contents with same title, Orchard will allow me to create these contents and the system will generate the same alias for both of them. 

If we try to edit and save one of the contents, an error message (Your alias is already in use.) will appear on the screen informing the user about the duplication. This check failed during the content creation.

**Comment by hishamco** [comment]
I think we need to avoid this case at least

**Comment by deanmarcussen** [comment]
PR is in for this but just for info @pitaridis the better pattern can be `{{ ContentItem.DisplayText | slugify }}`
