### ISSUE TITLE
Does not run on Azure App Service Linux

### ISSUE THREAD

**Issue by timheuer** [OrchardCMS/OrchardCore#4600]
Deploying OrchardCore to Azure App Service Linux works, but does not run properly.  This is likely due to SQLite and database being locked.  I'm not getting good logging to know if that is the case, but it has been with others.  Any task that attempts to write new data fails and crashes the app.

**Comment by Skrypt** [comment]
I'm surprised of this as we have docker images that works without requiring to make permissions adjustments. I think this one is an issue for @sebastienros as it is Azure specific. Unless you guys give me a Azure test account for free. 😋

**Comment by sebastienros** [comment]
We looked and confirmed that this is a known limitation of sqlite with CIFS on linux, the shared drive protocol that the Azure Web Service is using. There is nothing that can be done here, as any lock from sqlite (on any write) won't be released and the transaction will timeout eventually.
It's not an issue on Azure App Service for Windows. And another solution is to use SQL Server or any other server database when using Azure App service for Linux.

It will work on Docker as long as the sqlite file is not on a shared drive.
