### ISSUE TITLE
Features section filter needs to consider tags

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4601]
![localization-1](https://user-images.githubusercontent.com/1761249/67247131-c7584780-f460-11e9-8e78-29455849bd3d.png)

![localization-2](https://user-images.githubusercontent.com/1761249/67247141-ccb59200-f460-11e9-9a08-1b65a4cbac20.png)

Feature such as Content Culture Picker is important for localization but it doesn't show up when you search for localization in the Feature listing.

**Comment by dodyg** [comment]
Original discussion https://github.com/OrchardCMS/OrchardCore/issues/4594

**Comment by sebastienros** [comment]
Should it be part of the filter, or with a custom drop-down. I think in the filter would work just fine

**Comment by dodyg** [comment]
Yeah in the filter will work fine.
