### ISSUE TITLE
Initializing new Core FW project in VS

### ISSUE THREAD

**Issue by Budsy** [OrchardCMS/OrchardCore#4605]
I am trying to go through the project setup for the Orchard Core framework in Visual Studio 2019. When I run the startup project as recommended and submit the site configuration form that in boots into, it crashes on submit, apparently because of the SQL server connection I have defined by this connection string:

Data Source=.\\SQLEXPRESS;Initial Catalog=MyOrchard;User ID=MyOrchardUser;Password=xxxxx;MultipleActiveResultSets=true;

This is the error: InvalidOperationException: Instance failure.
Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, bool ignoreSniOpenTimeout, long timerExpire, bool encrypt, bool trustServerCert, bool integratedSecurity, bool withFailover, SqlAuthenticationMethod authType, SqlAuthenticationProviderManager sqlAuthProviderManager)

I've tried various flavors of this, taking off the MultipleActiveResultSets and some obvious stuff like that. It's using SQL Server 2016, and I have set up the database and user, and the user connects and works as expected, and I can work in the database with that login in SSMS.

I'm a bit nonplused by this... Intuitively it looks like my setup should work, because it's pretty standard. Any suggestions, folks?

Budsy

**Comment by hishamco** [comment]
Try `Server=.\SQLEXPRESS;Database=MyOrchard;User ID=MyOrchardUser;Password=xxxxx;MultipleActiveResultSets=true;` and check your connection without Orchard Core, seems it's a connection issue

**Comment by Budsy** [comment]
The problem was the double backslash in my string! My face is red. Thanks for the tip.

**Comment by hishamco** [comment]
No problem if it's fixed, please close this one
