### ISSUE TITLE
Error in updating Admin Menu

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4608]
After upgrading to version 1.0.0-rc1-10358

![error-1](https://user-images.githubusercontent.com/1761249/67320273-48214d00-f50e-11e9-9b2e-944b6acb5eaf.png)
![error-2](https://user-images.githubusercontent.com/1761249/67320275-48214d00-f50e-11e9-8c2d-4fb066e29fa7.png)
![error-3](https://user-images.githubusercontent.com/1761249/67320277-48214d00-f50e-11e9-8d06-83a2f869713a.png)

The Admin Menu item gets inserted properly after this error.

**Comment by sebastienros** [comment]
I broke yessql :/ again

**Comment by sebastienros** [comment]
I am reverting the version now, and will test with this issue

**Comment by dodyg** [comment]
1.0.0-rc1-10374 fixes this issue

**Comment by sebastienros** [comment]
I can't repro it, do you have specific steps?

**Comment by sebastienros** [comment]
I think I understand what could have happened, but I still could use some repro steps to validate this.

@jtkech it might be that the document that is in memory cache is changed then save in yessql, and if it comes from a previous request's session then yessql will say that it can't update something that already exists. In this case it would need to call Import. Or when something is updated, don't update the one in the memory cache (my preferred solution).

**Comment by jtkech** [comment]
Yes, with the current pattern each time we do a session save we also set the memory cache with the same object.

But maybe here the issue was only due to the `Version` column.

**Comment by sebastienros** [comment]
No issue, from the exception, is that Save(adminMennuList) is called on a session that didn't load the `adminMenuList`, which makes sense how it's done, as it takes the one from memorycache, then calls Save on it. But yessql will fail as it doesn't support that. So I was currently changing the code such that if a change is requested, it loads the document and saves it, then sets the new one in the cache.

**Comment by hishamco** [comment]
> But maybe here the issue was only due to the Version column.

Seb already reverting the YesSQL update

**Comment by sebastienros** [comment]
@hishamco  
![image](https://user-images.githubusercontent.com/1165805/67345639-958ec180-f4f0-11e9-88ae-debf22d0e512.png)

**Comment by dodyg** [comment]
@sebastienros  hmm I can't replicate it either after migrating to 1.0.0-rc1-10374

This is my upgrade path 

* 1.0.0-rc1-10222
* 1.0.0-rc1-10358 (breaks)
* 1.0.0-rc1-10374 (fixed the issue)

I downgrade again just now to `1.0.0-rc1-10358` to try to replicate it, but it worked normally.

**Comment by jtkech** [comment]
Yes, i was able to repro too but it was not always failing. It is due to another change in yessql (done before the one related to the `Version` column) that we don't use in the last dev.

In fact this change has revealed another issue related to the pattern we use to mutate and save some data, so it will be re-used when this other issue (that we are working on) will be fixed.
