### ISSUE TITLE
Consider making StartupBase.ConfigureServices/Configure async

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#461]
Both `Configure` and `ConfigureServices` could be updated to be `Task`-returning (and truly async as they are called from asynchronous methods). This would be useful in the OpenID module.

/cc @sebastienros @jersiovic

**Comment by sebastienros** [comment]
OMG, I was thinking about it during my commute! Because we own the calls and could just accept any.

**Comment by PinpointTownes** [comment]
If you like the change, I can send a PR (it seems trivial to do).

**Comment by sebastienros** [comment]
The guys in the team don't like it as it could give a wrong idea that it's actually doing something async, but it's not. We agree that it's only for style?

Well maybe not in our cases as our Startups don't have the same semantics as the standard one. The standard one is called by Main on the startup request, ours can be called standard requests to load a tenant.

**Comment by PinpointTownes** [comment]
> The guys in the team don't like it as it could give a wrong idea that it's actually doing something async, but it's not. We agree that it's only for style?

Well, it's also to avoid blocking on async calls :smile: 

If you think it's confusing, maybe it would be worth having a third method, `InitializeAsync`, that would be called before the two other ones.

**Comment by PinpointTownes** [comment]
> The standard one is called by Main on the startup request, ours can be called standard requests to load a tenant.

Yeah, that's exactly why I opened this thread (it wouldn't make much sense if the entire thing wasn't async).

**Comment by SimonCropp** [comment]
there is a high likelihood of ConfigureServices doing something that needs to be async. eg reading config from something that is IO bound. So it should absolutely support a Task based approach

**Comment by Piedone** [comment]
How about having both sync and async overloads (also for backwards compatibility)?

**Comment by Piedone** [comment]
`ConfigureAsync()` has been implemented for a while.
