### ISSUE TITLE
Share ViewData between modules

### ISSUE THREAD

**Issue by doticca** [OrchardCMS/OrchardCore#4616]
Is it possible to share ViewData between modules in an OrchardCore modular application?
For example is it possible to pass ViewData["Title"] from a module to the main _Layout content.

If not are there any alternatives?

**Comment by hishamco** [comment]
I think ithe is possible to pass `ViewData` from within module to layout

**Comment by doticca** [comment]
> I think it is possible to pass `ViewData` from within module to layout

In my tests, setting VieData works inside the same module but when trying to retrieve the value from a view in another module (main app) the result is always null.

**Comment by hishamco** [comment]
I'm not sure if this can happen, @jtkech any idea

**Comment by jtkech** [comment]
I would need more infos to test it, there are shape views, controller views with or without the theming engine, using an mvc layout or the current theme layout and so on.

What i already tried is to put the following in the `ItemController.Display` action of the `OC.Contents` module, which is hit each time we display a content item in the front end.

            ViewData["Message"] = "Your application description page.";

Then in the `Layout.cshtml` of the current theme

        Test: @ViewData["Message"]

And it works, knowing that a theme is a kind of module, that the app is also a module that also acts as a super theme.

**Comment by doticca** [comment]
Thank you both for your time.
The problem occurs in a modular application. I have created an application that is referencing OrchardCore.Application.Mvc.Targets then added a new project that references OrchardCore.Module.targets. The first project under pages/shared has a _Layout that sets title to ViewData["Title"]. Inside the module I have a Home controller and inside the Index view I set ViewData["Title"]. I followed using debug the process and although the ViewData["Title"] was set correctly inside the Index view of the module, when it goes back to the layout of the application it contains a null value.

**Comment by jtkech** [comment]
Okay just tried it works, the only difference is that because your index mvc view is used through a controller (it is an mvc view not a razor page) i used a `_Layout.cshtml` under the main mvc project `Views/Shared` folder.

**Comment by doticca** [comment]
> ay just tried it works, the only difference is that because your index mvc view is used through a controller (it is an mvc view not a razor page) i used a `_Layout.cshtml` under the main mvc project `Views/Shared` folder.

Genius! Thank you very much
