### ISSUE TITLE
Error editing text field settings

### ISSUE THREAD

**Issue by jameshawkins** [OrchardCMS/OrchardCore#4617]
Unable to edit a text field definition on latest dev. Can repro with the blog recipe by editing the Article content definition.

![image](https://user-images.githubusercontent.com/1388327/67418004-fde4ae00-f597-11e9-9a9f-40d39fd26312.png)

Clicking Edit on a text field results in a System.FormatException:

![image](https://user-images.githubusercontent.com/1388327/67417694-5f584d00-f597-11e9-9aa5-b5264fdf97c9.png)

I debugged it and the issue is caused by a localized string in `TextFieldPredefinedSettings.Edit.cshtml` (line 70):

`<span class="hint">@T["A JSON representation of the allowed values, e.g. {0}", "[ { name: 'First option', value: 'option1' }, { name: 'Second option', value: 'option2' } ]"]</span>`

The issue appears to have been introduced by #4559 which added `IHtmlLocalizerFactory` to `NullLocalizerFactory`. If i remove the DI registration of the `IHtmlLocalizerFactory` then it works.

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore/Modules/Extensions/ServiceCollectionExtensions.cs#L79

**Comment by sebastienros** [comment]
I see, the issue is that now it's correctly using a localization, and we might need to encode the parameter as it contains `{`. Maybe it's bug too in the localizer. Try to use `{{` and `}}` inside the json please.

**Comment by sebastienros** [comment]
That might be a bug in the localizer though, otherwise and variable that contains a `{` would just fail. It doesn't seem right. Like the variable gets called with String.Format, which shouldn't be the case.
