### ISSUE TITLE
change headings in 'TheAgencyTheme'

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/OrchardCore#4623]
in case this issue should be asked in a different Forum - my apologies - and thanks to direct me to a adequate forum!?
environment: W10, VS2019
I'm a user of OrchardCMS since the beginning and started now to familarize myself with rchardCore (1.0.0 RC1). I admire all the work you have done creating OrchardCore, thanks.

Starting with 'TheAgencyTheme' I wanted to change the very first screen. No problem to change the background picture , however, changing the 'headings' in 'landingpage.liquid' has NO effect.

- is there a cash .. somewhere?
- I can't find an 'alternate' (OrchardCMS!) in the views folder!

Question: how / where am I able to change these headings?

in the end, as usual, I miss a little stupid thing  ..
.. thanks for your time and help, ed

`{% zone "Header" %}

<header class="masthead">
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in">Welcome To Our Studio!</div>
            <div class="intro-heading text-uppercase">It's Nice To Meet You</div>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services">Tell Me More</a>
        </div>
    </div>
</header>
{% endzone %}`

**Comment by Skrypt** [comment]
Layout.liquid
