### ISSUE TITLE
Static File Provider not working on tenants besides default

### ISSUE THREAD

**Issue by pbeachlerif** [OrchardCMS/OrchardCore#4626]
I enabled the module on the main tenant and restarted the other tenants, but the module is not visible to enable in the other tenant, nor does the wwwroot folder seem to have automatically generated. I tried to create the folder manually and restart the tenant, but no luck. Please advise.

**Comment by deanmarcussen** [comment]
What version are you running?

It was changed to be able to be allowed for tenants a while ago.

I can see the `Static File Feature` feature listed in a tenants feature listing 

There is no requirement to enable the feature on the main tenant

**Comment by pbeachlerif** [comment]
I am currently on beta 3, a build from this summer I believe. It's most likely I did something incorrect during setup, but I'm not sure what.

**Comment by deanmarcussen** [comment]
Probably it is not working because of the version you are using

It was fixed (to work on all tenants not just the main tenant) on https://github.com/OrchardCMS/OrchardCore/pull/3581https://github.com/OrchardCMS/OrchardCore/pull/3581 so July

**Comment by sebastienros** [comment]
Please reopen if you can still repro with the latest bits.
