### ISSUE TITLE
Authentication / Users Providers

### ISSUE THREAD

**Issue by se** [OrchardCMS/OrchardCore#463]
Do you guys are planning an authentication / user provider system?

I want to authenticate my users with known authentication providers like LDAP, SAML2, OAuth2 and more...

**Comment by sebastienros** [comment]
We currently have an Orchard.Users module that uses ASP.NET Core Identity providers. Only CookieMiddleware is currently configured, but feel free to use any other ones. We need to make it configurable in the end. If you are up for the task we'd be glad to coach/support you.

Also @PinpointTownes and @jersiovic are working on an OpenId module that will allow your site to be an oauth2 provider.

**Comment by sebastienros** [comment]
Related to https://github.com/OrchardCMS/OrchardCore/issues/2029
