### ISSUE TITLE
Media/Assets

### ISSUE THREAD

**Issue by TimTracy** [OrchardCMS/OrchardCore#4639]
This is more of a end user type issue. I'm using the Blog Theme.
I have site up and running on Azure. I have uploaded assets - images and pdf's files.
When adding a page i am able to able to add a image widget and select a media item image (png,jpg) and it displays fine in the website.  I add another image and select a media item (pdf) and it will NOT display on website.  Any suggestion on dealing with pdf files?
Thanks,
Tim

**Comment by deanmarcussen** [comment]
What error message do you get in the browser console?

pdf's are in the allowed file extensions by default
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Media/

and should handle either case (.PDF or .pdf)
Can you use locally?

and are you using blob storage or file system on azure?

**Comment by TimTracy** [comment]
Loading into assets, so should be blob.
The pdf image shows a X like it cannot find the file.
The jpg image display correctly.

the html for pdf.
</article><article class="widget widget-image-widget widget-align-justify widget-size-100">
    <figure class="figure">
        <img src="/GaryTracyOD/media/Documents/SkinDeep.pdf" class="figure-img img-fluid rounded" alt="Patient form" />
        <figcaption class="figure-caption">Patient form</figcaption>
    </figure>
</article>

the html for jpg
<article class="widget widget-image-widget widget-align-justify widget-size-50">
    <figure class="figure">
        <img src="/GaryTracyOD/media/Images/BusinessWeek-Logo-300x63.jpg" class="figure-img img-fluid rounded" alt="" />
        <figcaption class="figure-caption"></figcaption>
    </figure>
</article>

**Comment by TimTracy** [comment]
I did try locally and got the same results as on Azure.  A pdf file loaded into assets will not display when you use a image widget on a page and select the pdf from assets.

**Comment by deanmarcussen** [comment]
but it does upload into assets ok, and is semi visible (i.e. not as a graphic) but is present in the assets browser?

ok I I am guessing here, but I think maybe what is going on is you are expecting the pdf to display in the html page, i.e. the view.

If that's the case, it won't. pdf's are not rendered by browsers as images, so you need to render them as a link, i.e.

```
<img src='http://foo.com/mypdf.pdf'/> --- will not work
<a href='http://foo.com/mypdf.pdf'>my pdf link</a> --- will generate an html link to the pdf
```

**Comment by TimTracy** [comment]
Inserted a link from paragraph widget and set url to:

Yourwebsite/media/Documents/Patient_Forms.pdf

Documents is a folder in Assets.
The link now opens the pdf I uploaded into assets.

Thanks!

**Comment by TimTracy** [comment]
Got the pdf to open using the link widget.
I closed issue.
Thanks,
Tim
