### ISSUE TITLE
Setup Defualt 404 Page in Decoupled OrcharCore

### ISSUE THREAD

**Issue by AKSExeed** [OrchardCMS/OrchardCore#4642]
Using Ordchard core in headless mode but want to setup a default 404 Page to route back to home page in case of incorrect URL. Is there  documentation to help setup the default 404 page?

**Comment by MichaelPetrinolis** [comment]
You can check this PR #3681 for headless mode
there is also a [demo](https://www.youtube.com/watch?v=rUGcATyPcvA&t=1532s)

**Comment by sebastienros** [comment]
You could write a middleware that would intercept the error and return a redirection. Or look at the Diagnostics middleware that does it.
