### ISSUE TITLE
Unit tests fails randomly

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4646]
I notice many times that some tests are fail randomly, one of them is **OrchardCore.Tests.Apis.GraphQL.Queries.RecentBlogPostsQueryTests.ShouldListBlogPostWhenCallingAQuery**

@jtkech any idea what's going on?

**Comment by jtkech** [comment]
Yes it's a known issue, we are tracking it, it is related to lucene queries.

Maybe sometimes we try to use a lucene query while lucene indexes building has not completed. In a given request scope, when we build lucene indexes, i already saw some file system activity even after the end of the request, i suspect (not sure) that sometimes it takes more time.

During the test we do a tenant setup => build indexes => use a lucene query, so maybe ...

It happens rarely on my machine but when it happens it is always the 1st time i run the tests.

**Comment by hishamco** [comment]
Thanks for your clarifiction

**Comment by Skrypt** [comment]
Worth tracking if this will be fixed by https://github.com/OrchardCMS/OrchardCore/pull/4628

**Comment by hishamco** [comment]
Hopefully, coz it's really annoying
