### ISSUE TITLE
Remove OrchardCore. prefix from admin URLs

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4647]
I don't see any value to have `OrchardCore.*` prefix in almost if not all the URLs in the admin, for instance https://localhost:5001/blog/**OrchardCore.Email**/Admin/Index `OrchardCore.Email` is reflect the module name, can we use alias name instead to become https://localhost:5001/blog/email/Admin/Index

/cc @agriffard @jtkech @sebastienros @Skrypt

**Comment by dodyg** [comment]
Being explicit makes it easier to find the source code of each module in the source code tree

**Comment by Skrypt** [comment]
Everything related with the admin should first be in /admin/...

**Comment by hishamco** [comment]
Also we could make the "admin" segment configurable, I have seen similar thing in Umbraco

**Comment by deanmarcussen** [comment]
@hishamco didn't you already start this on https://github.com/OrchardCMS/OrchardCore/pull/4086/files 

Maybe you could just take one of those as a new pr for the example as @agriffard suggests?

Also if you want `admin` to be configurable, that could just be an `IOptions` class

I am quite supportive of all admin routes, being under `/admin` or a well defined endpoint. Makes it much easier to restrict admin access, or host the admin site on another url. Which keeps coming up for us, as a nice to have feature

**Comment by agriffard** [comment]
Related #1329

**Comment by hishamco** [comment]
We should decide if we remove the prefix or continue with what suggest in #2779

**Comment by jeremycook** [comment]
@deanmarcussen I'm not sure if the following comment is valid even though I wish it was.

> I am quite supportive of all admin routes, being under `/admin` or a well defined endpoint. Makes it much easier to restrict admin access, or host the admin site on another url. Which keeps coming up for us, as a nice to have feature

With the /Admin routes we do have friendlier URLs but AFAIK the default routes will continue to work. Hence either "/OrchardCore.Users/Admin/Create" or the new "/Admin/Users/Create" can be used to access that action.
