### ISSUE TITLE
Permalink field issue with Persian words

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4653]
if I have Farsi words there, it doesn't show data. but with English words, it works fine.
please have look at Permalink render.

this is working fine
http://fckia.com/kitzbuhel-1-fckia-8

this has problem
http://fckia.com/%D8%A7%DA%A9%D8%A7%D8%AF%D9%85%DB%8C-%DA%A9%DB%8C%D8%A7-4-0-%D8%B3%D8%AA%D8%A7%D8%B1%DA%AF%D8%A7%D9%86

i updated the Permalink and i find that problem with this field.

**Comment by hishamco** [comment]
Could please give me a sample for Farsi words that you are used for permalink, so I can try it from my end?

**Comment by aghili371** [comment]
i have these titles, the url it made automatically if Permalink from the title.

مهدوی کیا : می‌خواهم مثل آلمانی‌ها باشیم

برنامه نویسی به سبک آلمانی
متین-بابل-0-4-اکادمی-کیا

**Comment by hishamco** [comment]
Last question did you try in many places or just a blog post?

**Comment by aghili371** [comment]
i have other content types. these are in the whole of my website.

**Comment by hishamco** [comment]
Ok, I will try it now

**Comment by hishamco** [comment]
This is happen for Arabic too, @sebastienros is the permalink needs `LocalizationPart`? or it doesn't respect the unicode chars?

/cc @jptissot

**Comment by deanmarcussen** [comment]
See the work @jtkech is doing on https://github.com/OrchardCMS/OrchardCore/pull/4479

I think that will solve the issue

**Comment by overstartup** [comment]
no any sulotion to solve this faster?

**Comment by aghili371** [comment]
@sebastienros  is not possible to solve this issue faster? all my websites have stopped. :(
