### ISSUE TITLE
Email settings regression

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4656]
The PR https://github.com/OrchardCMS/OrchardCore/pull/4637 has a couple of issues

It overrides UI settings, if email settings are supplied via appsettings, with no notification to the user

It tries to decrypt a password with the dataprotector from appsettings, but the password in appsettings will be in plain text, so will throw an exception

It creates an ambiguity as to where email is configured.

I looked at the code that introduced email to appsettings, and think it was testing code from when workflows were introduced on https://github.com/OrchardCMS/OrchardCore/pull/1378 

The correct way to it, I believe, is to only configure email from settings UI, but if someone wants to override that for development with a setting from configuration, they should implement their own `SmptOptions` in their own startup to override the UI settings

**Comment by hishamco** [comment]
IMHO we can try to solve the issues that you mention without reverting the entire PR

> It overrides UI settings, if email settings are supplied via appsettings, with no notification to the user

We can show a warning alert in the admin that email settings will be ignored

> It tries to decrypt a password with the dataprotector from appsettings, but the password in appsettings will be in plain text, so will throw an exception

I need to look to this one

> It creates an ambiguity as to where email is configured.

The previous alert will clarify the things

@jtkech @sebastienros your thoughts

**Comment by sebastienros** [comment]
Please revert the PR.

**Comment by hishamco** [comment]
@sebastienros could we think about support both `appsettings.json` and admin settings for almost modules?
