### ISSUE TITLE
Rebuilding OrchardCore on VS2019 for macOS

### ISSUE THREAD

**Issue by OlziiNaran** [OrchardCMS/OrchardCore#4660]
Q1:Rebuilding OrchardCore on VS2019 for macOS, the project cannot run after recompiling.
      Operating system:macOS Catalina v10.15
      VS : VS2019 for mac community v8.3.4

Q2:Module OrchardCore.Menu
     Module OrchardCore.Menu folder name conflicts with mac OS.menu.

**Comment by Skrypt** [comment]
You missed one emoticon there 😄 
I'll try on the macbook and tell you what I find but it was working.
You should try to clean your solution before trying to rebuild it first.

**Comment by OlziiNaran** [comment]
> You missed one emoticon there 😄
> I'll try on the macbook and tell you what I find but it was working.
> You should try to clean your solution before trying to rebuild it first.

Thank you, thank you very much.
