### ISSUE TITLE
Cannot Translate inner class by msgctxt

### ISSUE THREAD

**Issue by Ahmed-Galal85** [OrchardCMS/OrchardCore#4664]
[Fully Example to this bug](https://github.com/Ahmed-Galal85/TestAppForLocalization/tree/master/App.Web/App.Web)
Inner class not working: msgctxt "App.Web.Models.HomeVM.Index"

```
#: App.Web\Models\HomeVM.cs:13
#. [Display(Name = "العنوان")]
msgctxt "App.Web.Models.HomeVM.Index"
msgid "العنوان"
msgstr "Title"
```

```
namespace App.Web.Models
{
    public static class HomeVM
    {

        public class Index
        {
            [Display(Name = "العنوان")]//not working
            public string Title { get; set; }
        }
    }
}

```
normal class working well: msgctxt "App.Web.Models.PrivacyVM"

```
msgctxt "App.Web.Models.PrivacyVM"
msgid "عنوان الخصوصية"
msgstr "Privacy Title"

namespace App.Web.Models
{
    public class PrivacyVM
    {
        [Display(Name ="عنوان الخصوصية")]
        public string TitlePrivacy { get; set; }
    }
}
```

thanks

**Comment by hishamco** [comment]
@Ahmed-Galal85 I will try to create a unit test to reproduce the issue, if it's a bug

**Comment by hishamco** [comment]
Wait a minute, the data annotation localization is another thing, @sebastienros does the current implementation support this?

**Comment by Skrypt** [comment]
@hishamco I think you are right there's an issue with using Display data annotation. It's been reported before. I don't remember the details.

**Comment by hishamco** [comment]
Ok if is that I will create a PR for this one

**Comment by hishamco** [comment]
@Ahmed-Galal85 I don't think the issue is related to data annotations directly, so the issue with the inner classes

 Of course the fix will work fine if the data annotation bug is fixed
