### ISSUE TITLE
Admin navigation suggestions

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#468]
- use a different background and pad the inner sections
- add an independent scrollbar
- move the menu toggle on the left
- convert the top right links to a dropdown on small devices

Open question:
- how should the chevrons be rendered: still on the right? use different icons?
- should specific pages have their own navigation logic and collapse this one
  - Content, Media

**Comment by sebastienros** [comment]
During the meetings we suggested:
- Chevrons can remain on the right side if they are up/down arrows.
- Have a toggle icon always visible to collapse the menu to icons only.
- Have each admin page decide if it needs a custom extra menu (Content, Media).
- When a second navigation is open, it automatically collapses the main navigation. The toggle button can still make it appear.

**Comment by agriffard** [comment]
As a example, I really like this admin theme: 
http://themes-lab.com/make/admin/layout1/dashboard.html

It also has a theme builder that shows the available features:
http://themes-lab.com/make/admin-builder/index.html

So, here are some options I would like have or to be able to configure in the admin:
Sidebar
	Change size with collapse button : large, icons
	Content: Top (search, user), Widgets
	Fixed, Fluid
	Menus and sub-items on hover
Topbar: icons, menus
Colors: background, style

**Comment by matiasmolleja** [comment]
I like the VS Code side bar.
A few buttons covering the most comon tasks that an user would  want to do. That way we avoid having a too long list of links.
Clic one button,  menu  expand. Clic again, menu colapses. 
And for the sidebar maybe we can do more than simply display a tree of links. I mean, maybe a module can inject a shape that shows a miniform like the search menu in VS Code?
Or are the these kind of things too difficult or impractical to do?

**Comment by matiasmolleja** [comment]
If you think it can be useful, I can quickly draw some photoshop sketches that can be used to talk about. Just to have something visible that ensures we are all on the same page

**Comment by agriffard** [comment]
I like this admin template: https://github.com/pratikborsadiya/vali-admin and how it provides a responsible off-canvas menu and mini sidebar in javascript and css, quiete similar to adminLTE.

**Comment by sfmskywalker** [comment]
That vali-admin looks pretty good. Do you know if it supports RTL?

**Comment by agriffard** [comment]
There is no RTL support in this admin template for the moment.

**Comment by agriffard** [comment]
Closing it, as @matiasmolleja implemented these features for the menu.
