### ISSUE TITLE
how can i use the theme layout page resource 

### ISSUE THREAD

**Issue by kiventwang** [OrchardCMS/OrchardCore#4681]
ex:I found the  {% resources type: "FootScript" %} source code in the theme layout.cshtml.then I don't know how can I use the footscript tag.who can help me.
same:    {% resources type: "HeadScript" %}
    {% resources type: "HeadLink" %}
    {% resources type: "Stylesheet" %}

**Comment by dodyg** [comment]
I think it's like an area where you can add your script/link/style 

```
{% script src:"yoruscript" at:"FootScript" %}
```

So this way your script is located at the foot of the template.

**Comment by agriffard** [comment]
`{% script src:"/path/to/script" at:"Foot" %}`
https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Resources/#specify-location

**Comment by sebastienros** [comment]
I think it's been nswered
