### ISSUE TITLE
Create Layout Page content type to support out-of-the-box ( O1 Like Layout)

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4686]
As now Content Card PR #4470  is  merged to dev - It would be nice to have "Layout Page" content type created for out-of-the-box themes, as described in comments of the PR.

Create a Layout Page content type with BagPart contained with at least following four most used content types

 - 1 Column Row
 - 2 Column Row
 - 3 Column Row
 - 4 Column Row

**Comment by sebastienros** [comment]
Maybe not a content item itself.

**Comment by Piedone** [comment]
The point of Bag Part is that it's just an unordered container of content items. I don't we should make it manage anything about the layout, since we have Flow Part for that. What's missing from Flow Part to cover this use case?
