### ISSUE TITLE
Allocate menu to Page

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#4692]
Hi, I was wondering if there is any option to allocate menu to a page content type while creating as it was in old Orchard CMS.

**Comment by sebastienros** [comment]
If done then it should create a link menu item. And maybe be a checkbox like for the Set Homepage.

**Comment by khurram4u2** [comment]
Hi, Is there any change for this feature to be added or not?

**Comment by Piedone** [comment]
The Content Menu Item now does this.
