### ISSUE TITLE
No Recipes for Decoupled Web App?

### ISSUE THREAD

**Issue by gsbanner13** [OrchardCMS/OrchardCore#4695]
First, let me pre-apologize if this is not the appropriate place to ask this question.  I am new to Github and OrchardCore.  I am following the "Create a Decoupled CMS Site" tutorial located here: https://orchardcore.readthedocs.io/en/dev/docs/guides/decoupled-cms/

However, every time I get to the point where I launch the site, there are no recipes available.  Has anyone else encountered this?  Any ideas what I am missing?

![NoRecipes](https://user-images.githubusercontent.com/36817126/67955909-a793f280-fbc9-11e9-9d08-39b90f20036d.JPG)

**Comment by agriffard** [comment]
Please change your target package to `OrchardCore.Application.Cms.Targets` and you will be able to use the Blank recipe.
The `Cms.Core.Targets` does not contain any recipes.

It will be changed soon (new target will be available) and updated in the documentation.

**Comment by gsbanner13** [comment]
That did the trick.  Thanks!

**Comment by sebastienros** [comment]
@gsbanner13 please share your feedback on this thread if you find anything unclear or missing from the tutorial.

**Comment by sebastienros** [comment]
That's what this line is for:
```
  <PreserveCompilationReferences>true</PreserveCompilationReferences>
```

Can you check you have this ?

**Comment by sebastienros** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/4693

**Comment by gsbanner13** [comment]
I do have that line in my both my main csproj file as well as the csproj for the module.  If I go into the BlogPost.cshtml file and change the header from "<h1>This is the blog: @blogPost.DisplayText</h1>" to "<h1>This is the blog for all to see: @blogPost.DisplayText</h1>" and then save and then refresh my screen, nothing changes.  I tried it in Chrome and Firefox with the same results.

**Comment by JoelOnGithub** [comment]
@sebastienros the tutorial still states that the user should use `OrchardCore.Application.Cms.Core.Targets`.

Either tell the user to use `OrchardCore.Application.Cms.Targets`, or add steps to include a blank recipe.

Now the user will encounter the first error.
