### ISSUE TITLE
ContentPickerField Searching ContentItems Limitation

### ISSUE THREAD

**Issue by stantoxt** [OrchardCMS/OrchardCore#4699]
DefaultContentPickerResultProvider can only search 20 contentItems.We can't pick the desirable contentItem outside the 20 items.

**Comment by netwavebe** [comment]
I agree the value of 20 is too small. I changed it to 50 in my solution. There's also a mismatch: DefaultContentPickerResultProvider returns 20 results but LuceneContentPickerResultProvider returns 50 results.

@sebastienros: Would it make sense to create a PR to make DefaultContentPickerResultProvider return 50 results as well?

**Comment by sebastienros** [comment]
@netwavebe ok
