### ISSUE TITLE
Liquid Part grows beyond 100% width of parent element while editing

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4706]
When editing liquid page or any content item containing LiquidPart, if the content of Liquid part is greater than 100% width of parent element then input of all fields grows beyond 100% and shows horizontal scroll bar for the page.

It should not show the horizontal scroll bar for page, instead it should just show scroll bars for only liquid part.

![liquid](https://user-images.githubusercontent.com/23270244/68034864-821dec00-fc90-11e9-9006-1e9eab4458f1.gif)

![liquid-2](https://user-images.githubusercontent.com/23270244/68035948-b2ff2080-fc92-11e9-9158-4eb41050bc41.gif)

**Comment by sebastienros** [comment]
Looks like something to configure/fix in codemirror.

**Comment by ns8482e** [comment]
It seems the its growing because of `display:table-cell` in contents.css, Nice switch to flex.

Related issues #1907 #2255

Also I feel  
1. Sidebar and Actions zones  should be moved to [Edit.cshtml](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Views/Admin/Edit.cshtml) 
from Contents.Edit.chstml
2. ContentsDriver should only emit Button Shapes only for primary item being edited and not for child widget content items - ( Currently no way to identify if content item is primary or child widget item within ContentsDriver )
