### ISSUE TITLE
Html Wysiwyg is not RTL when the direction of current culture is RTL!!

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#4709]
When the direction of the default culture in CMS is RTL, the direction of the Html Wysiwyg is not RTL. Only text-align property is set to right. but, the direction property in editor is still LTR.

**Comment by hishamco** [comment]
@deanmarcussen I already fixed this long time ago, did you change anything related to RTL while working on gulp and resources

I remember you mentioned that before

**Comment by deanmarcussen** [comment]
@hishamco I think maybe the original fix is not enough.

as @ampadashi just setting the `text-align` property is not enough for the wysiwig editor

```
    @if (culture.IsRightToLeft())
    {
        <div style="text-align:right">
            <textarea asp-for="Html" class="form-control"></textarea>
        </div>
    }
    else
    {
        <textarea asp-for="Html" class="form-control"></textarea>
    }
```

That would work ok for the standard editor, but for trumbowyg it will not override any of the generated `trumbowyg` rtl css.

Correct me if I'm wrong?

**Comment by hishamco** [comment]
I was talking about `trumbowyg` style itself not the above markup, anyhow I will have a look again

**Comment by ampadashi** [comment]
Right now, only text-align property is set to right. Direction property should be set to rtl too. Another thing which needs to be considered is that the editor has an option letting us see the source of html. Source view must be LTR and normal view must be rtl in all rtl cultures.

**Comment by hishamco** [comment]
> Source view must be LTR and normal view must be rtl in all rtl cultures.

I don't think so while it has an HTML markup

@ampadashi could you please show us a screenshot for the RTL issue?

**Comment by ampadashi** [comment]
Please take a look at the photo below. Current culture is fa-IR which is RTL. Direction of HTML editor is still LTR. Only text-align was set to right.
![image](https://user-images.githubusercontent.com/32009041/68083829-eaacca80-fe42-11e9-94b2-98a3a31ac2d2.png)

**Comment by hishamco** [comment]
I see, I will try to handle this

**Comment by ampadashi** [comment]
Please consider the source view mode. It must stay LTR.

**Comment by hishamco** [comment]
@agriffard do you finished your PR that are related to `trumbowyg` coz I need to tweek it little bit for better RTL support

**Comment by ns8482e** [comment]
Trumbowyg language files are not included in OrchardCore.Resources

https://alex-d.github.io/Trumbowyg/documentation/#add-localization
