### ISSUE TITLE
Implementing login form in a widget.

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#4710]
I wonder if it is possible to use login form in a widget in special part of the page like the UI below:
![image](https://user-images.githubusercontent.com/32009041/68068545-2b391500-fd6b-11e9-821d-c88451d775fd.png)

**Comment by sebastienros** [comment]
As long as your form targets the correct controller, yes. Please copy the code from the existing views that render the login form.

**Comment by jptissot** [comment]
@sebastienros I think one issue will be that if any errors occur, the controller will redirect to the login page and not stay on the widget page.

**Comment by ampadashi** [comment]
@sebastienros Dear Seb, The Login view needs a model. If view copy all the codes from login.cshtml to for example MyLogin-widget.cshtml, an exception will be thrown telling us that the model is not present in MyLogin-Widget.cshtml.

**Comment by jptissot** [comment]
@ampadashi You just need to add a reference to `OrchardCore.Users` in your `.csproj` file

**Comment by jptissot** [comment]
I don't think you should design this as a widget to be honest. Any errors will redirect you to the full login page as per https://github.com/OrchardCMS/OrchardCore/blob/d06d95d061ebbd85a12c4d64ae1d465ec9c611f9/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AccountController.cs#L108 

What you could do instead is override the Login / registration view and load content via an alias from that page (your training courses).  Please see https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Templates/#overriding-login-view
