### ISSUE TITLE
Defining fields of special content part or content types for all available cultures.

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#4712]
When we are creating new content part or content types, there are some fields like Part Title or Hint that can be defined only for one culture. Let's suppose that our website have two cultures. One en-US and the other one fa-IR. If we define content parts and types for en-US first, all the defined fields will be the same for fa-IR culture. So, We will see a lot of English word in Farsi language. I think it would be great if we could define fields unique for all available cultures!

**Comment by hishamco** [comment]
> there are some fields like Part Title or Hint that can be defined only for one culture

You 're right, we already implment `CultureAspect` for the content fields

> I think it would be great if we could define fields unique for all available cultures!

Is that mean they are not change if the current culture changed?

**Comment by ampadashi** [comment]
As an example,  when we choose a text for hint field in en-US culture, that text will be shown for other cultures too. I think it’s better to be able to choose that text for each culture separately. So, When we change the culture in CMS, Everything will look nice.

**Comment by hishamco** [comment]
Make sense, is there anything else except Hint

**Comment by ampadashi** [comment]
Display Name is so important too!

**Comment by hishamco** [comment]
Don't be confused, there's another type of localization for dynamic data, I already started a PR for that one #4466

**Comment by hishamco** [comment]
BTW @ampadashi you could help the community to enhance the RTL by not submitting issues only, you  could create a PRs as well :smile:

**Comment by ampadashi** [comment]
It's so great! When are u going to join this PR to master branch? What about the menu item added by Admin Menu module?

**Comment by hishamco** [comment]
> When are u going to join this PR to master branch?

I can't promise coz there 're priorities, but you could help me and start submitting for the once that quite obvious

> What about the menu item added by Admin Menu module?

Could you elaborate?

**Comment by ampadashi** [comment]
> BTW @ampadashi you could help the community to enhance the RTL by not submitting issues only, you could create a PRs as well 😄

Dear @hishamco. I just started studying on the source of OC a month ago. Honestly, I'm wiling to help the community to enhance the RTL. With your help, I will do my best.

> Could you elaborate?
When we define items for Admin Menu, We are able to define one Link Text for that item and one Link Text doesn't look so good for using in all cultures.

**Comment by hishamco** [comment]
> When we define items for Admin Menu, We are able to define one Link Text for that item and one Link Text doesn't look so good for using in all cultures.

Please screen shoot

**Comment by ampadashi** [comment]
![image](https://user-images.githubusercontent.com/32009041/68084797-d3c0a500-fe4f-11e9-8a19-3531cb53a93f.png)
Regarding this photo, i can only choose one link text and for sure that text will look nice only for one culture. If we could localize the admin menu, we can make defined menus look nice in all the cultures.

**Comment by hishamco** [comment]
It's not the cultures list matter, this need something like content localization

/cc @jptissot

**Comment by sebastienros** [comment]
The only issue here is that you need Dynamic Data localization which is something that @hishamco is already working on. (and is blocked waiting for my review)

**Comment by hishamco** [comment]
Exactly, that's what I point to it above in my comment https://github.com/OrchardCMS/OrchardCore/issues/4712#issuecomment-549127672

**Comment by sebastienros** [comment]
closing as it's being tracked by another issue
