### ISSUE TITLE
Edit fields and parts definition settings on one page in Content type

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#472]
When you edit a content type, is it possible to display all the fields and parts definition settings on the same page (as in O1) and be able to change theme, instead of going to another page for each field or part?

**Comment by sebastienros** [comment]
The way you add/edit fields in Drupal might be a better solution actually. It relies on a client MVVM  library, we should have something like this. I kept it simple at first for an easier development model.

**Comment by agriffard** [comment]
Can we imagine to have a UI like this to manage the fields and parts in a content type definition?
A list of fields and parts on the left and on click, allow to edit the selected one:
https://i.octopus.com/blog/2019-08/octopus-release-2019.8/deployment-process-sidebar.gif

**Comment by sebastienros** [comment]
Have you looked at the Drupal one actually? There are some YT videos you can probably watch and link here.
