### ISSUE TITLE
HTTP Error 500.31 - ANCM Failed to Find Native Dependencies

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#4721]
after i publish the project, i got this Error:

`HTTP Error 500.31 - ANCM Failed to Find Native Dependencies
Common solutions to this issue:
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect`
i don't know why it has an error. it runs correctly in local but in a server, it gives me Error.

**Comment by ampadashi** [comment]
Would u please provide an screen shot of that error?

**Comment by deanmarcussen** [comment]
I suspect you need to publish as a self contained app.

I imagine you're publishing to Azure? Which does not yet (AFAIK) have the dotnet core 3 runtime, so you need to publish with the runtime.

If you are doing this from visual studio, you select `publish as self contained`

**Comment by ampadashi** [comment]
@overstartup If you've published your app as self-contained, There's file named Web.Config. If your are using .Net Core 2.2, few lines of web.config file are like photo below:
![image](https://user-images.githubusercontent.com/32009041/68084096-59d7ee00-fe46-11e9-974b-95d6cbeceb1c.png)
In the case remove V2 from `modules="AspNetCoreModuleV2"` and save the config file, then restart you app.
