### ISSUE TITLE
Pagination template for RTL cultures has some problems.

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore#4726]
The template of the list pagination has some problems in cultures which their direction is RTL.
![image](https://user-images.githubusercontent.com/32009041/68083940-41ff6a80-fe44-11e9-8054-d3ab2add7e53.png)
@hishamco

**Comment by hishamco** [comment]
@ampadashi this has been fixed

![Pagination RTL](https://user-images.githubusercontent.com/3237266/102140724-bc385600-3e70-11eb-82be-d02c8cc33c20.png)
