### ISSUE TITLE
A bagged item with taxonomy field isn't included in TaxonomyIndex

### ISSUE THREAD

**Issue by bluenex** [OrchardCMS/OrchardCore#4730]
According to the [docs](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Taxonomies/#taxonomy-index):

> The TaxonomyIndex SQL table contains a list of all content items that are associated with a Taxonomy field.

We want to query from `TaxonomyIndex` but it looks like if the taxonomy field is attached in a bagged item, they won't be available in `TaxonomyIndex`. 

Here is how the model looks like:

- `CompanyContentItem`
  - `Branches Bag`
    - `CompanyBranchBaggedItem`
      - `RegionTaxonomyField`

Just to note that the `taxonomy_terms` liquid filter gives the correct result as seen below:

```
Test Liquid Filter

Code:

{% assign allCompanies = Queries.AllCompanies | query %}
{% for comp in allCompanies %}
  {% assign companyBranches = comp.Content.Branches.ContentItems %}
  {{ comp }}
  {% for branch in companyBranches %}
    - {{ branch.DisplayText }}: {{ branch.Branch.Region | taxonomy_terms | join: ', ' }}
  {% endfor %}
{% endfor %}

Render:

Company B
- HQ: Region3, Sub-region5
- Branch A: Region3, Sub-region6

Company A
- HQ: Region1, Sub-region2
- Branch A: Region2, Sub-region3

```

Here is a recipe to reproduce: [taxonomy-repro.zip](https://github.com/OrchardCMS/OrchardCore/files/3802742/taxonomy-repro.zip)

**Comment by hishamco** [comment]
@agriffard could you please check the docs, or cc the one who worked on this

**Comment by Skrypt** [comment]
Of course a BagPart is contained in a content item itself so right now it is not indexed. In this case a BagPart is not a Field so it's not relevant to use this index. I guess one solution could be to have a ContentPart index for a BagPart that would index these different BagPart Fields. Right now, I don't think we have any ContentPart Field indexation but I'm not sure 100%.

The current SQL Field Indexing feature will right now map Content Type Fields.

**Comment by sebastienros** [comment]
You can't query bag items, and they are not indexes either. You might need a List if you need to manage these items individually.

If you just want to provide search then you can use the Full Text settings such that the main content can be searched from its bagged items.
