### ISSUE TITLE
Strange behaviour with case sensitive urls and SVGs

### ISSUE THREAD

**Issue by jxt-seth** [OrchardCMS/OrchardCore#4732]
This only happens with SVGs that are stored in Assets that I have seen so far. So if the folder you are storing the SVG in has an uppercase character like "Icons" and you use the liquid helper like so:

{{ 'icons/ico-instagram.svg' | asset_url | img_tag: alt: 'Instagram Logo' }}

This will result in a 404 within your webpage. 

However, if you load the URL in the browser with a uppercase "I" like so - https://www.test.com/media/Icons/ico-instagram.svg (no 404) and then change to a lowercase like so - https://www.test.com/media/icons/ico-instagram.svg you no longer get the 404 until the next time the cache is purged or deleted.

Can't seem to get this to occur with jpgs only SVGs so far. This is withy Azure Media Storage, no sure of other mechanisms.

**Comment by scleaver** [comment]
Whoops, wrong Github account.

**Comment by sebastienros** [comment]
the fact that you don't get it with jpgs might be related to the imagesharp cache. /cc @deanmarcussen

**Comment by deanmarcussen** [comment]
yes, svg's will be skipped by ImageSharp, whereas jpeg's will not, so maybe some weirdness with the blob middleware, combined with the static file middleware.

I'll will take a look tonight, maybe there's a case sensitivity that is missing.

**Comment by deanmarcussen** [comment]
this is an underlying aspnetcore / corefx / windows issue I suspect.

The `IFileProvider` used by the static file middleware, uses `FileInfo` which depending on operating system maybe case sensitive or not. On windows it is not case sensitive.

For example
```
            var Logo = new FileInfo("Logo\\example.svg");
            Console.WriteLine("Logo:" + Logo.Exists);
            var logo = new FileInfo("logo\\example.svg");
            Console.WriteLine("logo:" + logo.Exists);
```

This produces true for both of them.

Couple of old discussions here relating to it.

https://github.com/aspnet/FileSystem/issues/16
https://github.com/aspnet/Extensions/issues/825

However azure blob is case sensitive. And there are no options to changewith that.

So the answer is probably to use the correct casing for your svg files, as they were uploaded, and everything will work correctly, regardless of file system. 
But if you start mixing and matching casing, then you may get unexpected results.

The media field should be handling this correctly I believe.
