### ISSUE TITLE
Support reload on change for tenants appsettings.json

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4734]
Is there any reason we can't support reloadOnChange for tenants `appsettings.json` and `App_Data\appsettings.json` ?

The DefaultHostBuilder supports it for the startup projects `appsettings.json`, and because most (not all) configuration settings are loaded in via `IOptions` if we could support it, then a tenant restart would be enough to reapply the updated settings, rather than having to recycle the apppool etc al.

I did turn it on when I was working on blob but forgot to open an issue.

Just wondering if there would be some issue with the way they are mutated?

/cc @jtkech

**Comment by jtkech** [comment]
Yes, i already tried the `bReloadOnChange` option for json and it was working. I don't remember all details but we opted to not use it, maybe because some of our custom config / settings sources are mutable, not all config sources support this option, not totally safe and not well suited for distributed environment.

> ... then a tenant restart would be enough to reapply the updated settings ...

**This is what #4164 is doing**, here some of my comments.

> So, here when we update a tenant and reload it, the related shell settings are reloaded so that after having updated a given tenant through tenants.json or its specific appsettings.json, if i reload it through the admin i can see the changes under the tenants page (was not the case before).

> I think it's a more complete tenant reloading. Then in a distributed environment where a distributed event will be sent on a tenant reloading, on each instance this tenant will be reloaded by loading and using the updated settings coming e.g from a shared source.

Need to leave, i will think about it this night.

**Comment by deanmarcussen** [comment]
@jtkech that's great, looking forward to seeing #4164 in ;)

And yes, reloading the settings, on a tenant reload, is a much better practise, than reloading on change, not just for distributed, but as not everything using `IShellConfiguration` is configured via option singletons, so it would be hard to know exactly what needed a restart and what didn't.
