### ISSUE TITLE
Content Field Indexing documentation looks wrong

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4735]
This looks wrong to me

![indexing](https://user-images.githubusercontent.com/1761249/68236887-b1c15100-000e-11ea-9c84-f62a74d60241.png)

https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/SQL/

**Comment by dodyg** [comment]
Never mind.

**Comment by Skrypt** [comment]
When you are doing a SQL Query and you don't selected the option to return documents. It will return a `IEnumerable<JObject>` so there is no issue about doing this. Though if you want to return documents you SQL Query will need to do a `Select DocumentId FROM Table`.

**Comment by dodyg** [comment]
Yeah I think the doc is just a bit incomplete.

**Comment by Skrypt** [comment]
Agree on that but I don't think it's the proper place to explain this. Probably in the Query module doc.

**Comment by dodyg** [comment]
As an aside, I have 

```
{% assign total = Queries.BlogPostsSize | query : culture: Culture.Name %}

{{ total }}
```

and the output is  ```{ "Total": 5 }```. How can I access the value (5).

I tried

```
{{ total.Total }} 
```
but this doesn't work.

**Comment by dodyg** [comment]
Ok the answer is 

``` {{total.first.Total}}```

**Comment by sebastienros** [comment]
This sample focuses on what should be done, I don't see anything wrong. If we need more examples and documentation about queries then it's doable.
