### ISSUE TITLE
Error in template file MyTestPartSettingsDisplayDriver.cs

### ISSUE THREAD

**Issue by HarkinsDave** [OrchardCMS/OrchardCore#4736]
[src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Module/Settings/MyTestPartSettingsDisplayDriver.cs](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Module/Settings/MyTestPartSettingsDisplayDriver.cs)

The Code

        public override IDisplayResult Edit(ContentPartDefinition contentPartDefinition)
        {
            if (!String.Equals(nameof(MyTestPart), contentPartDefinition.Name, StringComparison.Ordinal))
            {
                return null;
            }

            return Initialize<MyTestPartSettingsViewModel>("MyTestPartSettings_Edit", model =>
            {
                var settings = contentPartDefinition.GetSettings<MyTestPartSettings>();

                model.MySetting = settings.MySetting;
                model.MyTestPartSettings = settings;

                return Task.CompletedTask;
            }).Location("Content");
        }
`

In VS 2019 (.Net Core 3) throws the following 3 Errors on the `return Task.CompletedTask;`

1. Error CS8030 Anonymous function converted to a void returning delegate cannot return a value
2. Error CS0029 Cannot implicitly convert type "System.Threading.Tasks.Task" to "System.Threading.Tasks.ValueTask"
3. Error CS1662 Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

**Comment by jtkech** [comment]
Good catch! We need to remove this line

    return Task.CompletedTask;

Already fixed in my PR #4708
