### ISSUE TITLE
The "New" action dropdown will fail when ContentItem list is filtered by Content Type

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4740]
In Admin Menu you can create a list of ContentItem by Content Type. In this case, the "New" action dropdown will go to the wrong url and return 404.

![failure](https://user-images.githubusercontent.com/1761249/68266562-210f6300-0058-11ea-9f89-200cc9b5856a.png)

**Comment by dodyg** [comment]
Ideally this "New" action will filter to the Content Type of the list. Hence in above case, you will only see "Album" in the "New" dropdown instead of the other Content Types.

**Comment by agriffard** [comment]
Only the creatable types are listed in the `New` dropdown.

On which action do you reach a 404?

**Comment by dodyg** [comment]
All of them. Remember this is not the standard Content Item list. This is Content Item List filtered by Content Type. This functionality is available via Admin Menu.
