### ISSUE TITLE
Why ConsoleLog()

### ISSUE THREAD

**Issue by xuj668** [OrchardCMS/OrchardCore#4742]
**i fellow this guide:**
https://orchardcore.readthedocs.io/en/dev/docs/guides/decoupled-cms/#accessing-the-other-properties-of-a-content-item

**after i add these code:**
`@Orchard.ConsoleLog(blogPost)`

**there are error:**

> 
> Pages/BlogPost.cshtml(11,15): error CS1061: 'IOrchardHelper' does not contain a definition for 'ConsoleLog' and no accessible extension method 'ConsoleLog' accepting a first argument of type 'IOrchardHelper' could be found (are you missing a using directive or an assembly reference?) [/home/recozo/Documents/DecoupledCms/DecoupledCms.csproj]
> 
> The build failed. Fix the build errors and run again.

i found out that the extension method ConsoleLog does exist in the project OrchardCore.ContentManagement.Display (razor/OrchardRazorHelperExtensions.cs),
and there is another OrchardRazorHelperExtensions.cs in the project OrchardCore.Media.

**Comment by deanmarcussen** [comment]
That is our fault. The `Console.Log` extension was added after the Release Candidate, which is the latest version on NuGet.

To use the latest dev branch, we release nightly builds to MyGet, which has the feature.

You can add `https://www.myget.org/F/orchardcore-preview/api/v3/index.json` to your nuget sources in Visual Studio, and get the latest dev build, which contains the extension method.

**Comment by xuj668** [comment]
And I found that there are many errors in the document. If I fellow purely according to the document, I can't learn, how can i help to correct it

**Comment by xuj668** [comment]
for example, 
`<ItemGroup>
  <PackageReference Include="OrchardCore.Application.Cms.Core.Targets" Version="1.0.0-rc1-10004" />
</ItemGroup>
`
i have to change to 
`<ItemGroup>
  <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-10004" />
</ItemGroup>`
Otherwise, there is no recipes option
