### ISSUE TITLE
Oauth2 and inline content editing

### ISSUE THREAD

**Issue by AdamJacks** [OrchardCMS/OrchardCore#4748]
Is Orchard Core capable of using Oauth2?

I haven't been able to find anything related to inline editing of HTML content in Orchard Core, is this possible?

**Comment by sebastienros** [comment]
OAuth2 is supported all the way, as a server or client. You'll find most external oauth providers supported already in the list of features. Or check for the OpenID features.

We don't support inline editing, but we do provide a Live PReview experience. When editing a content, click on Preview and keep this window open, as you do changes you will see them reflect using the front-end theme, which will show exactly how it will look like for the end-user.

**Comment by sebastienros** [comment]
By the way we have a forum on Gitter which is more adapted than creating issues.  https://gitter.im/OrchardCMS/OrchardCore

**Comment by AdamJacks** [comment]
My apologise for not using Gitter. I'm afraid I'm looking for something which supports inline editting, thank you anyway!
