### ISSUE TITLE
ListPart shape bug or just my missuse

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#4749]
Shapes still brings some confusion to me. I have `Book `content item that have `AliasPart` `AutoroutePart `and `ListPart `of `BookChapters`  then my `Content-Book.liquid` shape have such line:

`{% assign book_chapters = Model.Content.ListPart.ContentItems | contet_of_type: "BookChapter" %}`

When accesing Book by link thanks to `AutoroutePart `,  shape for ListPart is generated, so ListPart is populated with BookChapters. Thats is correct.

But in other place of my website I have such liquid code:

`{{ Content["alias:my-book"] | shape_build_display | shape_render }}`

This time book content itself is loaded, it also starts to render `Content-Book.liquid` shape, but  `ListPart `is not populated with `BookChapters `items.  This suggest that in this second case ListPart shape is not properly constucted, so it is not loadind `BookChapters `. 

Any thoughts on this?

**Comment by arkadiuszwojcik** [comment]
I have some extra clue. My hierarchy looks like this: `Author `-> List of `Book `-> List of `Chapters`  When I do experiments with `Author `itself and try to list all `Books `everything works fine. But when I go one level down (starting from Book level and trying to list all Chapters like described in first thread) then it doesn't work.

**Comment by deanmarcussen** [comment]
I have used ListPart's to nest content similarly to your heirachy, but mostly with Razor.

This confuses me
> {{ Content["alias:my-book"] | shape_build_display | shape_render }}

Are you intending to load a particular content item based on it's alias and render it?
Or have I misunderstood?

**Comment by arkadiuszwojcik** [comment]
@deanmarcussen exactly, and this content item contains ListPart of other objects.

**Comment by deanmarcussen** [comment]
How are you loading the content item you want?
With the `content_item_id` filter?

**Comment by arkadiuszwojcik** [comment]
No, by alias:  ` {{ Content["alias:my-book"] | shape_build_display | shape_render }}`   look at: `Content["alias:my-book"]`

**Comment by arkadiuszwojcik** [comment]
When I access very same Content Item but by it's URL then ListPart is loaded and everything works fine.

**Comment by sebastienros** [comment]
Depending on the type of the template you are editing, `Model.Content.ListPart` means different things. 
`Model.Content` could be the Json of a content item, and `.ContentItems` will be availble. But in a `Content-XYZ` template it will mean the ListPart shape in the `Content` zone, which might not have this property.

**Comment by arkadiuszwojcik** [comment]
@sebastienros I think you are right here my real use case is actually slightly diffrent (sorry for missing that):

`{{ Content["alias:my-book"] | shape_build_display "ListItem" | shape_render }}`  so it means that template engine will look for "ListPart.ListItem.liquid" while rendering `ListPart `for` Content-Book.ListItem.liquid` ? And it can't find one so ListPart is empty? If so is there any way to use ` Content-Book.ListItem.liquid` but force regular `ListPart `shape?
