### ISSUE TITLE
Can't add second language to my bag Items

### ISSUE THREAD

**Issue by sallenkov** [OrchardCMS/OrchardCore#4752]
this is an overview for my Content Item Services, 
![image](https://user-images.githubusercontent.com/17978153/68383318-b93f4200-0155-11ea-8973-2c222165834e.png),
When I add a new language to the  service, This happens:
![image](https://user-images.githubusercontent.com/17978153/68383356-ca884e80-0155-11ea-9044-fc4617acb230.png)

**Comment by hishamco** [comment]
Please list all the steps to reproduce the issue

**Comment by jptissot** [comment]
Yes, this is expected. You should not localize bag items but the container of those bags.

**Comment by sallenkov** [comment]
> Yes, this is expected. You should not localize bag items but the container of those bags.

my items should have both language, arabic and english version,if that's not the way to do it it shouldn't give an error.it should not give me the chance to do it anyway

**Comment by sebastienros** [comment]
They can, the idea is that you translate the whole document, not each bag individually. You shouldn't be blocked, if you are then let us know and we'll try to give you better steps to follow to achieve what you need.
