### ISSUE TITLE
Update the OpenID YesSql stores to support optimistic concurrency

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/OrchardCore#4757]
Now that YesSql supports optimistic concurrency for updates, we must update the 4 OpenID stores to support that.

**Comment by sebastienros** [comment]
Take that

**Comment by hishamco** [comment]
@PinpointTownes any updates on this?

**Comment by PinpointTownes** [comment]
@hishamco it's on my ever-growing list of things to do 😄 
That said, it should be a quite simple change, so feel free to take it if you have some spare time.

**Comment by hishamco** [comment]
I see, I will leave it to you coz I have a list of localization stuff that I need to do 😄
