### ISSUE TITLE
Make Site Page Size Editable in Admin

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#4758]
It appears there are a number of Site Settings which are not editable in the admin area (unless I am missing it). For example, "Page Size", "Max Page Size", "Max Paged Count", etc. Some Site Settings are exposed in Settings --> General in Admin area but it seems that not all of them are included. The fullest list I see is found in OrchardCore.Settings.SiteSettings. Since the "Page Size" can be [easily accessed through Liquid](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Liquid/#site), I would love to use it, but not if I cannot update it in the user interface.

**Comment by deanmarcussen** [comment]
@jeffolmstead Page Size just added in https://github.com/OrchardCMS/OrchardCore/pull/3286

The others could be added.

Worth noting that the listpart has it's own page size setting, which is also customisable in the part settings for it.

**Comment by jeffolmstead** [comment]
Thanks @deanmarcussen for letting me know about that, hadn't seen it yet.
