### ISSUE TITLE
OrchardCore.Media.Azure not working 1.0.0-rc1-10004

### ISSUE THREAD

**Issue by idontbyte** [OrchardCMS/OrchardCore#4762]
1.0.0-rc1-10004 - attempting to upgrade from 1.0.0-beta3-71025
Using Azure Blob Storage for images, configured in appsettings.json

```
"OrchardCore.Media.Azure": {
      "ConnectionString": "**removed**", // Set to your Azure Storage account connection string.
      "ContainerName": "live-media",
      "BasePath": "media" // Set to a path to store media in a subdirectory inside your container.
    }
```
The feature is also enabled in the CMS.

The images in my existing blob store are broken links and I have the following errors in my logs:

`2019-11-08 22:02:13.1449|Default|80000041-0006-fd00-b63f-84710c7967bb||SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware|ERROR|The image 'https://localhost:44351/media/Article Images 600/2019 Chelsea by Numbers.jpg?width=240&height=240' could not be resolved `

**Comment by idontbyte** [comment]
A small update to this issue -
I have noticed that when navigating the assets tree, images in 2nd level folders display ok, whereas images in folders residing in level 0 and 1 do not.

e.g. this image works:
/garden centres/bath/picture.jpg

this does not:
/images/picture.jpg

Most strange!

**Comment by deanmarcussen** [comment]
Can you check that you have the `Media Cache` feature also enabled?

There was a fix went in after RC, which was related to bad encoding of url's that contained accent characters and / or whitespace.

Refer https://github.com/OrchardCMS/OrchardCore/pull/4424

I suspect that may be related to your issue, as I can see some of your files / folders have whitespace in them

**Comment by idontbyte** [comment]
Media Cache was not enabled.

I have now enabled media cache and I have the same issue.

I can confirm that where files / folders have no whitespace they work at any level, but where they have whitespace they only work at level 2+.

**Comment by deanmarcussen** [comment]
Azure Media is now dependant on the Media Cache feature, but because this is an upgrade, it will not check dependant features and enable them on startup. So you do need to enable manually (for anyone else coming across this later)

The whitespace issue is fixed in https://github.com/OrchardCMS/OrchardCore/pull/4424 but that was after RC1, so you will need to upgrade to the dev packages on the myget feed to get support for whitespace characters.
