### ISSUE TITLE
Is XML-RPC working?

### ISSUE THREAD

**Issue by paule96** [OrchardCMS/OrchardCore#4770]
Hi Orchard Team,

I have try the feature XML RPC, so I can publish my content with Open Live Writer. But when I tried it I get the following error:

![image](https://user-images.githubusercontent.com/11291885/68546622-a4261580-03d8-11ea-8aa8-e9f474f42fc4.png)

I have tryed the following URLs:

`http://hostname/LiveWriter` <- The URL to my tenant
`http://hostname/LiveWriter/blog` <- The URL to my Blog
`http://hostname/LiveWriter/xmlrpc` <- The maybe direct Xml-RPC URL
`http://hostname/LiveWriter/blog/xmlrpc` <- The maybe direct Xml-RPC URL on the Blog
`http://hostname/LiveWriter/xmlrpc/metaweblog` <- with metaweblog
`http://hostname/LiveWriter/blog/xmlrpc/metaweblog` <- with metaweblog

Here you can also see what window I fill with the above URLs:

![image](https://user-images.githubusercontent.com/11291885/68546802-dafd2b00-03da-11ea-8800-56b7c6b1a8c1.png)

Also the documentation to this API are very hard to find or not written. 🤷‍♀️

Maybe you can help me with this problem. I only was able to find the release notes from the Alpha in Dec 2016 that indicates this features is implemented.

**Comment by agriffard** [comment]
When you enable the feature 'Remote publishing', the meta with the url `/xmlrpc/metaweblog` is added on a page that displays a ListPart (like a Blog) and also another like this: `/xmlrpc/metaweblog/{listId}/rsd` that says that Metaweblog is supported with `apiLink=".../xmlrpc"`.

**Comment by paule96** [comment]
yes I can see this response:

![image](https://user-images.githubusercontent.com/11291885/68547250-92943c00-03df-11ea-9a7f-27ed86e61053.png)

But that URL i already tried. It seems to be that is not compatible with live writer. 🤔

**Comment by sebastienros** [comment]
It was working when I made it, maybe it's broken

**Comment by paule96** [comment]
I don't know much about XML RPC. Maybe you can where I have to look. maybe I can fix it. 🤷‍♀️

**Comment by sebastienros** [comment]
You could try to debug this controller: https://github.com/OrchardCMS/OrchardCore/blob/d729a2048a4390380d99e7be9f7968ff8f8e9271/src/OrchardCore.Modules/OrchardCore.XmlRpc/Controllers/HomeController.cs

And any XmlRpc handler class.

**Comment by paule96** [comment]
okay thanks. will start this evening. maybe I see something 🤷‍♀️

**Comment by paule96** [comment]
Okay it was broke but the work for the fix was some kind of simple 👌 so I think it is fast reviewed and merged :)
