### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#4775]
This is a missprint in the [AdminMenu.cs](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Google/AdminMenu.cs) OrchardCore.Google?
![image](https://user-images.githubusercontent.com/6829626/68579439-29670400-0485-11ea-8cd7-30125a297051.png)

**Comment by sebastienros** [comment]
You are correct. You are very welcome to provide a PR if you can.

**Comment by hishamco** [comment]
Good catch, I think we need sort of code analyzers, I have seen such issues many times which affect the localization
