### ISSUE TITLE
Alias isn't checked when using Bulk Actions

### ISSUE THREAD

**Issue by johnrom** [OrchardCMS/OrchardCore#4780]
I had this occur in a project I'm working on, though I haven't had a chance to test it in vanilla OC. I used "clone" and bulk "publish" on a bunch of posts with `AliasPart`s and the aliases were duplicated instead of displaying "This alias is already in use."

This was from RC1 so it's possible this is fixed already upstream.

**Comment by deanmarcussen** [comment]
yes, I can repro on latest dev. my bad pr, will fix

(although fyi @johnrom RC1 didn't do any checking on alias uniqueness fyi)

**Comment by johnrom** [comment]
I must have had to update at some point. I'm using `1.0.0-rc1-10004`.
