### ISSUE TITLE
Get information from the user on Orchard core

### ISSUE THREAD

**Issue by sayyad84** [OrchardCMS/OrchardCore#4784]
I want to create a website with Orchard Core. On a page of that, information such as name,email,etc is obtained from the user and should be visible in admin page for review. Please guide me how to do this?

**Comment by dodyg** [comment]
If your users have nothing to do with the CMS, I suggest creating a custom module and store the User information in separate database.

**Comment by sebastienros** [comment]
Why a separate database? A different table would be sufficient.

@sayyad84 nothing is different here than with standard ASP.NET development. You would create a custom page and store it in the database.
