### ISSUE TITLE
Trumbowyg editor little issue

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#4787]
Maybe because i did a `git clean -xdf`.

Then, when editing an article the html body trumbowyg editor was not rendered, only a simple editor.

After adding a dependency on `jQuery` in the `OrchardCore.Resources` module, it was working.

            manifest
                .DefineScript("trumbowyg")
                .SetDependencies("jQuery")

Also for infos, i 1st tried to rebuil the assets through the task runner, then the team explorer / git extensions said to me that the `graphiql-orchard.js` file has changed.

@agriffard or any other expert of the UI team ;)

**Comment by agriffard** [comment]
Soory about this @jtkech . 
It happened after I removed the jquery-resizer dependency that had itself a dependency on jQuery.

After a `gulp rebuild`, I don't see any change of graphiql-orchard.js.

**Comment by agriffard** [comment]
But I don't see any log about graphiql at all.
I don't know how it is supposed to build graphiql-orchard.js from OrchardCore.Apis.GraphQL\Assets\js\App.tsx without an Assets.json

**Comment by agriffard** [comment]
It is using webpack so let's ask @jptissot and @deanmarcussen .

**Comment by deanmarcussen** [comment]
yes, not built with the gulp pipeline.
run `npm run-script build` in the graphql folder I think from memory, and it runs the webpack script
