### ISSUE TITLE
Resource dependencies not flowing through

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4789]
maybe this is an issue, maybe by design, but raised as a result of https://github.com/OrchardCMS/OrchardCore/pull/4788

where the trumbowyg.js resource registration takes a dependency on admin

admin has a dependency on jquery

but the dependency isn't flowing in the correct order

so the script load order is

1. trumbowyg.js first, even though it has an admin dependency
2. jquery next
3. admin last

when to me it seems like trumbowyg taking the admin dependency should make it load in this order

1. jquery
2. admin
3. trumbowyg

@agriffard has fixed the issue it created, but this still seems like unexpected behaviour

**Comment by jtkech** [comment]
I took a look in the code, when `Name != null && Src == null` we don't take into account `DependsOn`. I think we assume that when a resource is defined in a manifest its dependencies are specified there.

So 1st i think that in the resource manifest we need to keep the dependency of `trumbowyg` on `jQuery` if it really needs it.

But then, because of the above remark, we are not still sure that `trumbowyg` will be after `admin`.

Here **we would need a script require helper** as we have in O1 if i remember correctly.

**Comment by deanmarcussen** [comment]
> I took a look in the code, when `Name != null && Src == null` we don't take into account `DependsOn`. I think we assume that when a resource is defined in a manifest its dependencies are specified there.

Yes, this one confuses me everytime I look at it. And I am still not sure if it is correct. But see below because it must have been working once.

> So 1st i think that in the resource manifest we need to keep the dependency of `trumbowyg` on `jQuery` if it really needs it.

And yes the @agriffard fix is correct, regardless, because there is the possibility of a custom admin theme that also defines `admin` but doesn't use `jQuery` - hard to imagine, but possible ;)

> But then, because of the above remark, we are not still sure that `trumbowyg` will be after `admin`.

My point here is really not about `trumbowyg` at all, but using it as an example, it is more about using `depends-on` in custom themes / modules etc, and getting the behaviour you would expect.

But actually I find the issue. It was working, but this https://github.com/OrchardCMS/OrchardCore/pull/4292 looks like it has broken it.

If I reset back to before that PR the dependencies take into account prior dependencies, and all the load orders are respected. eg

```
<script src="/blog1/OrchardCore.Resources/Scripts/jquery.js?v=3si58EpBCY45eNOYy-tOYGvVIcYSCL43BoMG1XIbYcM" type="text/javascript"></script>
<script src="/blog1/OrchardCore.Resources/Scripts/jquery-ui.js?v=C61-OoAxJy904l6R1z9Qo-kPlybfMLOII7lPlW6oLGc" type="text/javascript"></script>
<script src="/blog1/OrchardCore.Resources/Scripts/jquery-ui-i18n.js?v=4f5WMW-Lg5t8pnjCaaUdx2vvj5bDHF0qp2L_FYDKC4M" type="text/javascript"></script>
<script src="/blog1/TheAdmin/Scripts/TheAdmin.js?v=dnw8mzg6OhDG-hsyNyunFg_up6O1Ct_mgqcWDm71CqA" type="text/javascript"></script>
<script src="/blog1/OrchardCore.Resources/Scripts/trumbowyg.js?v=FG-4AycU6-ADvjPQj4jlUbOqUTTiLQYRRKwBmwLGk3g" type="text/javascript"></script>
<script src="/blog1/OrchardCore.Html/Scripts/trumbowyg.media.js?v=hMePioIp0bm1f4KSctlQCaKyA7zH-W_lyPHH8tbmv0Q" type="text/javascript"></script>

**Comment by jtkech** [comment]
> But actually I find the issue. It was working, but this #4292 looks like it has broken it.

Not sure but as i can see in the `ScriptTagHelper` code, if the name is provided (named resource) and no source, the `DependsOn` property is not used, idem for a custom script where no name and also no source are provided.

If i'm right, all places where we use `depends-on` for these both cases are useless.

**Comment by deanmarcussen** [comment]
> > But actually I find the issue. It was working, but this #4292 looks like it has broken it.
> 
> If i'm right, all places where we use `depends-on` for these both cases are useless.

and you are right :). 
Actually the code for `trumbowyg` has changed since #4292 as it was registered inline with `asp-src` and is now registered via a `ResourceManifest`. So I was too quick to make that call, about it being a regression.

We agree then, `depends-on` has no effect on anything registered via a `ResourceManifest`, and all the places that use it are useless. 

What is more useless is that in all the places we use it (maybe 20-30), we don't need to!
- codemirror doesn't need `admin` (the css does, but not js)
- the new trumbowyg plugins need jquery, but not admin
- bootstrap-select (new also) does need bootstrap.js which is included in the admin, but because it has a dependency on jquery in it's definition gets loaded in the right order. (so actually it technically does need to depend on admin, but get's lucky because jquery is in the admin `depends-on`)

So I will do a PR to remove all of those, as even if `depends-on` did work, it is unnecessary.

But separately I will do another PR, so that `depends-on` can add to dependencies defined in a resource manifest, as I can 
- make it work quite easily and 
- think it is super confusing that it doesn't. 

Even though it makes way more sense to define the dependencies in the `ResourceManifest`, when every property is available on the script tag helper, and some properties are ineffective, we end up with the confusion we currently have.

I'll call the second PR optional, as you or Sebastien may disagree, as to it's my thinking.
