### ISSUE TITLE
Wrong layout in Article

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#4797]
I assume because it has Trumbowyg editor:

![image](https://user-images.githubusercontent.com/1165805/68720241-77ead000-0563-11ea-9237-6e633e824e2f.png)

**Comment by stantoxt** [comment]
I think this cause this problem.https://github.com/OrchardCMS/OrchardCore/pull/4800

**Comment by stantoxt** [comment]
#4800

**Comment by agriffard** [comment]
Also fixed by #4790

**Comment by stantoxt** [comment]
That's cool. @agriffard

**Comment by hishamco** [comment]
@agriffard can you please add Fix keyword to that PR, so this will be closed automatically

**Comment by agriffard** [comment]
@hishamco Done. Don't hesitate to edit yourself the description of my PRs when you want to reference a potential fixed issue.
