### ISSUE TITLE
Html in menu item

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#480]
Am I allowed to enter text with HTML in a Link menu item?
Ex: In the Name of a link menu item, enter `<i class="fa fa-twitter"></i>`
The text is encoded so it is not well displayed.

Do we have to change the view MenuItemLink-LinkMenuItem.cshtml ?
`<a href="@Url.Content(linkMenuItemPart.Url)">@Html.Raw(linkMenuItemPart.Name)</a>`
Or do we have to create another kind of menu item that allows HTML ?

**Comment by sebastienros** [comment]
Another kind of menu item. Html menu item. The name is only used on the menu editor, and the content of the menu item is rendered in Raw,

**Comment by agriffard** [comment]
Todo: Create an Html Menu item

**Comment by agriffard** [comment]
#480
