### ISSUE TITLE
Core nuget package / Theme / module meta package

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4801]
I asked this question on another semi related issue, but it got closed as the issue was resolved.

A couple of times now it's come up about renaming the Core package, possibly to
- Blank
- Bare
- Empty

When developing razor themes or custom modules, it would be useful to have a meta package, which has all the orchard core references in it, so you can take a reference on a content field, or a content part, etc.

You can't do that with the Core package, because it has MSBuild targets in it, which stop it working when it's not the main startup package that is referencing it.

Equally, it's hard to rename, as we have now published it too NuGet.

Proposing we turn the Core package into the Empty package, but keep the Core package as something we can reference from a custom theme or module.
Slightly breaking for existing users of the Core package, and documentation updates would be needed.

But less breaking now than after RTM.

Thoughts / better ideas?

**Comment by jtkech** [comment]
@deanmarcussen 

> You can't do that with the Core package, because it has MSBuild targets in it, which stop it working when it's not the main startup package that is referencing it.

Hmm, not tried but maybe we can by using `PrivateAssets="all"`

**Comment by sebastienros** [comment]
> You can't do that with the Core package

I don't believe you. This is even documented in the decoupled cms guide.

**Comment by deanmarcussen** [comment]
I am wrong.
Retried and it does work, and publish correctly.

It does create a Localization folder, but doesn't reference the localization packages, so it's empty, but that is no issue.
