### ISSUE TITLE
What is a proper way to localize main menu?

### ISSUE THREAD

**Issue by 8VAid8** [OrchardCMS/OrchardCore#4813]
I found out that main menu alias is hard-coded to Layout.liquid of the all themes.
But what can we do to localize it? I added Localization part to Menu Parts. Added new localized menu with another alias. But themes always shows the same menu.
 
So, i hard coded two menu shapes with locale-postfixes:

```
{% if Culture.Name == "en-US" %}
    {% shape "menu", alias: "alias:main-menu-en", cache_id: "main-menu-en", cache_fixed_duration: "00:05:00", cache_tag: "alias:main-menu-en" %}
{% endif %}
{% if Culture.Name == "ru" %}
    {% shape "menu", alias: "alias:main-menu-ru", cache_id: "main-menu-ru", cache_fixed_duration: "00:05:00", cache_tag: "alias:main-menu-ru" %}
{% endif %} 
```
Ofcorse, i can add for-statement with "if's" there. But it looks hacky. What is the proper way to localize menu?

**Comment by hishamco** [comment]
Wait for data localization https://github.com/OrchardCMS/OrchardCore/pull/4466
