### ISSUE TITLE
Dynamic widget based Dashboard - Parts or View Components

### ISSUE THREAD

**Issue by weedkiller** [OrchardCMS/OrchardCore#4816]
Hello, I would like to request a much needed feature to allow developers to build widgets and have a drag drop widget based dashboard. Something like or similar to [this ](http://bit.ly/2G4hAkM)

Its been a long wait for something like this.
It would be easy to add charts, graphs, stats, summaries, timelines etc.

**Comment by hishamco** [comment]
If I'm not wrong we already discussed that somewhere else

**Comment by sebastienros** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/2246
