### ISSUE TITLE
Add title attribute to admin navigation icon

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4819]
The icon only menu is amazing in saving space however it can be better if it has `title` attribute so browser can show tool-tips when you hover over the icon.

![title](https://user-images.githubusercontent.com/1761249/68992147-4712df80-0870-11ea-9f8a-91cad50d70fc.png)

**Comment by hishamco** [comment]
Agree

**Comment by sebastienros** [comment]
Also for accessibility
