### ISSUE TITLE
Search with parameters

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4825]
Please explain how to make a search page that queries the content items or a Lucene index or a sql query based on url parameters (retrieved in Liquid?).

Ex: If I have a blog, I want to be able to : 
- Query all the blog posts that contains a search term in different fields (by default)
- Query all the blog posts published by month/year
- Query all the blog posts associated to a List
- Query all the blog posts from an author
- Query all the blog posts with a specific tag

Talking about Content items and Lucene, here is a suggestion:
We could make a front route that, by default, allows us to pass querystring parameters like: 

- A term to search: `q`
- A content type to filter: `t` or an index: `i`
- Some fields to search into (FullText by default, Owner): `s`

The goal is to provide a straightforward and flexible way to find and display search results based on the url.

/cc @Skrypt

**Comment by Skrypt** [comment]
The only Lucene request I need to check if we can do it with Lucene.NET is the one that groups by month/year which would require "I think" having search aggregation in OC.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html

**Comment by Skrypt** [comment]
Here is quickly something that works for most of the above. I will update it later on today. 

```
{
  "from" : {{ from }}, "size" : {{ size }},
  "query": {
    "bool" : {
      "must" : [
        { "term" : { "Content.ContentItem.ContentType" : "BlogPost" }},
        { "term" : { "Content.ContentItem.Published" : "true" }},
        { "term" : { "Content.ContentItem.Latest" : "true" }},
        {%if fulltext != "" and fulltext != null and fulltext != "*" %}
        {
          "bool": {
            "should": [
        	  { "wildcard" : { "Content.ContentItem.DisplayText" : "*{{ fulltext }}*", "boost": 1 }},
        	  { "match" : { "Content.ContentItem.FullText" : { "value": "{{ fulltext }}", "boost": 2, "operator": "and" } }},
              { "term" : { "Content.ContentItem.Tag" : { "value": "{{ fulltext }}", "boost": 3 } }}
            ]
          }
        },
        {%endif%}
        {% if owner != "" and owner != null and owner != '*' %}
        { "term" : { "Content.ContentItem.Owner" : "{{ owner }}" } }
        {% endif %}
        {% if author != "" and author != null and author != '*' %}
        { "term" : { "Content.ContentItem.Author" : "{{ owner }}" } }
        {% endif %}
      ]
    }
  },
  "sort": [
    { "Content.ContentItem.ModifiedUtc": { "order": "desc" } },
    { "Content.ContentItem.CreatedUtc": { "order": "desc" } }
  ]
}
```

**Comment by sebastienros** [comment]
We need a guide for that

**Comment by Skrypt** [comment]
I am the guide 😝

**Comment by agriffard** [comment]
https://orchardcore.readthedocs.io/en/dev/docs/guides/implement-fulltext-search/

**Comment by agriffard** [comment]
https://docs.orchardcore.net/en/latest/docs/guides/implement-fulltext-search/
