### ISSUE TITLE
AutoRoute is not working when the content item is created via workflow

### ISSUE THREAD

**Issue by bluenex** [OrchardCMS/OrchardCore#4828]
Here are scenarios I have experienced:

- When the AutoRoute part is added to a content type, the route path of the existing items of that type will not be updated unless the item is republished in the content item editor in the backend.
  - Note that we use default pattern for AutoRoute: 

```liquid
{{ ContentItem.DisplayText | slugify }}
```

- When the item is created via a workflow, there are another 2 scenarios:
  1. Without `AutoRoute` part added. The route path is not generated unless the item is republished in the content item editor in the backend.
  2. With `AutoRoute` part added as seen below. The route path is showing on the content item UI. However, it is not possible to access that path. Republishing the content item doesn't help without checking `Refresh the path` to force an update.

```json
"AutoroutePart": {
  "Path": "{{ Request.Form.Title | slugify }}",
  "SetHomepage": false
},
```

Is this a bug or we did something wrong?

**Comment by MichaelPetrinolis** [comment]
The issue I see is that the update handlers are called from the editors but not from the CreateAsync method of IContentManager. I see the following quick solutions. 
1. move the code that autogenerates the alias or the autoroute path based on liquid templates to a method that would be called from create and update handlers. 
2. Call the also the update handlers from the CreateAsync of IContentManager 
3. Modify the workflow to call update after create. 

@sebastienros please tell me if there is a preferred or better option to make a PR
