### ISSUE TITLE
Passing parameters to query in API

### ISSUE THREAD

**Issue by ryacarini** [OrchardCMS/OrchardCore#4829]
Hello!

I have created a query to be used by API, and it works correctly with the parameters that are sent, when I test it from the module. But when invoking it as an API (using POSTMAN for example), it does not respect the parameters sent in the URL. What could be the reason?

In Queries Module:

![image](https://user-images.githubusercontent.com/31014422/69027035-69ede280-099b-11ea-875f-ff1ad79e3589.png)

In POSTMAN:

![image](https://user-images.githubusercontent.com/31014422/69027141-d79a0e80-099b-11ea-98b9-4802e569e616.png)

Andy how can hay use Schema field to return only the fields that I need?

Thanks in advance!

**Comment by Skrypt** [comment]
limit @limit:4
will render as limit 44 or limit 14 ...

**Comment by ryacarini** [comment]
Hello.

I found the problem. I forgot the word "parameters". For example, in my case i have to use:

https://localhost:44300/api/queries/Articles?**parameters=**{"tipo":"Casos","limit":1}

Thanks anyway!
