### ISSUE TITLE
SqlException: Cannot open database "XXXX" requested by the login

### ISSUE THREAD

**Issue by smantriconde** [OrchardCMS/OrchardCore#4834]
I am newbie in Orchard and Orchard core really attract me by looking some wonderful features, specially tenant and modular structure. 

After pulling the latest updates from GitHub repo, it is throwing an error while creating a new tenant. It's used to working fine. It started giving the SQL access issue after pulling the latest request. Also tried with server admin SQL user by passing User Id and Password in connection string. Please refer the below screenshot:

![image](https://user-images.githubusercontent.com/26825866/69110540-176aff80-0a49-11ea-9122-a95839b85917.png)

**Comment by scleaver** [comment]
@smantriconde Try changing the DB name to "Orchard-emark", I think I recall seeing this before and the problem is the underscore. Can you report back here the result.

**Comment by smantriconde** [comment]
Thank you @scleaver for quick response. I tried with Orchard-emark (without underscore). But still it is throwing the same error. It is used to working fine with following connection-string:
Server=(local);Database=Orchard_web1;Integrated Security=true; 
OR 
Server=(local);Database=Orchard_web1;User Id='XXX';Password='XXX'
 
![image](https://user-images.githubusercontent.com/26825866/69116223-8ea88f80-0a59-11ea-857d-4464405a571f.png)

**Comment by scleaver** [comment]
Did you create the database first and you user does have access?

**Comment by smantriconde** [comment]
I believe Orchard create the database if it is not exist. 
And yes, Orchard tenant setup working fine, if database already exist.

**Comment by deanmarcussen** [comment]
Orchard will not create the database if it does not exist.

If you are using a tenant_prefix to your existing database when creating tenants, then tenant setup will continue fine. But if you are using a different database name for the tenant you will need to create it manually.

**Comment by smantriconde** [comment]
Okay, got it. It means, database should be exist before running tenant setup. Hope in future, Orchard will add this feature "Provide the option to create database if does not exist" in tenant setup page.
