### ISSUE TITLE
Base url validation

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#4836]
@barthamark pointed out to me that the "base URL" setting should have the protocol. It does mention this in the comment "Enter the fully qualified base URL of the web site." under the field but I was thinking some users might miss this or misunderstand it.

Are you ok if I submit a PR to add validation to the field?

**Comment by hishamco** [comment]
Looks good

**Comment by deanmarcussen** [comment]
yes please, I am using it for sitemaps, and it would be much better if it had
- validation
- had an example of what a fully qualifed url looked like (for anyone unsure)
