### ISSUE TITLE
Updating SQL Query is broken

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4840]
`1.0.0-rc1-10771`

![broken-sql](https://user-images.githubusercontent.com/1761249/69158657-71be9b80-0aef-11ea-9396-78b1d63bb86a.png)

**Comment by jtkech** [comment]
Okay, i can repro.

Already fixed, there was a missing update where we need to use `LoadQueryAsync()` in place of `GetQueryAsync()`, i will do a PR tonight
