### ISSUE TITLE
Create helper to load ListPart items

### ISSUE THREAD

**Issue by sallenkov** [OrchardCMS/OrchardCore#4848]
Hello,
I am trying to get the list of questions based on the culture in a decoupled way.I used same approach as the Blog theme:
![image](https://user-images.githubusercontent.com/17978153/69253167-7c8f3400-0bb4-11ea-9f03-8d44273c3fdd.png)
here you can see that i have both languages
![image](https://user-images.githubusercontent.com/17978153/69253538-17880e00-0bb5-11ea-8807-a6a35c1a7980.png)
and for each list i have one Item 
![image](https://user-images.githubusercontent.com/17978153/69253571-21aa0c80-0bb5-11ea-9c7d-2be56fabc439.png)

But
in razor i always end up with the right set but an empty list
![image](https://user-images.githubusercontent.com/17978153/69253618-37b7cd00-0bb5-11ea-804a-79f08c1ec75b.png)

**Comment by hishamco** [comment]
Shoot it to you @jptissot :)

**Comment by sebastienros** [comment]
Your query only returned the list content item. To load its items you will need another query, that will filter content item with the `ListContentItemId` in the `ContainedPart`. There should be an index for it.

We might want to create a helper though to make it easier.
Changing the title and keeping it open.

**Comment by arkadiuszwojcik** [comment]
@sebastienros please add also Count helper - just count list items without loading them.

**Comment by sallenkov** [comment]
**GetRecentContentItemsByContentTypeAsync** with pagination can be a better approach for getting the ListPart
