### ISSUE TITLE
Question: How can a User confirm his email address?

### ISSUE THREAD

**Issue by neolution-ch** [OrchardCMS/OrchardCore#4850]
When we create a new user the email address is initially not confirmed ("EmailConfirmed" flag in documents that represent users). 

How can this be changed, how can a user confirm his email address?
- The user does not get an Email (SMTP is enabled and properly configured)
- We can't find an option in the Admin to see the confirmation status (Can only be found out by browsing the tables in the database directly)

**Comment by hishamco** [comment]
@jtkech did we miss this intentionally or is there something I don't know about it?

**Comment by Skrypt** [comment]
There's an option in security / registration to allow email confirmation on user account creation. Though the feature User registration needs to be enabled first.

**Comment by hishamco** [comment]
Thanks @Skrypt, I really forgot that there's a settings will be added after enabling User module

**Comment by neolution-ch** [comment]
Perfect, thanks! That was not clear to me. 

So, if I (as an admin) create a new user, the user will never receive an email? And also has therefore no option to confirm his email address?
