### ISSUE TITLE
Question: Filter return own view model

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#4851]
I've created a an own Liquid filter which returns a own made view model like following:

```
public class MyModel
{
    public TextField TestText{ get; set; }
}
```
In the filter i return something like this.

`return FluidValue.Create(new List<MyModel>{new MyModel{ TestText="asdf"}}).ToList());`

In the template I can access the result of it, but if I try to access `{{ item.TestText.Text }}` it always returns a blank string. If i output `{{ item }}` it will return what I add to the ToString() in the MyModel class. 

Is there anything special I need to make that my own viewmodel gets parsed correctly and I can access the attribues from the template?

**Comment by deanmarcussen** [comment]
You need to register the model for access

`TemplateContext.GlobalMemberAccessStrategy.Register<MyModel>();`

See fluid for options https://github.com/sebastienros/fluid

**Comment by LMSSonos** [comment]
Thank you, that was it!
