### ISSUE TITLE
Register ContentPartFieldDefinition for Liquid

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4852]
Can we register `ContentPartFieldDefinition` and other associated models for use with Liquid?

Was trying to add this to a taxonomy template for the blog / tags feature 
`class="tags {{ Model.PartFieldDefinition.Name | html_class }}"`

but because the models aren't registered, they have no access.

Just checking if there's a reason not to?

**Comment by Skrypt** [comment]
I'm surprised it's not there on the Model.Content.SomePart

**Comment by deanmarcussen** [comment]
Maybe I'm doing something wrong.

But I'm using the `DisplayTaxonomyFieldViewModel` and this `{{Model.PartFieldDefinition.Name}}` returns nothing.

If I register `TemplateContext.GlobalMemberAccessStrategy.Register<ContentPartFieldDefinition>();` then I can access the `Model.PartFieldDefinition`.

**Comment by sebastienros** [comment]
Sure
