### ISSUE TITLE
Accessing localized strings in a template

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4871]
Is there anyway to access localized strings from the template? e.g.

```
  {{ localized["name"] }} :  {{ Model.ContentItem.Content.Person.Name }} 
```

**Comment by jtkech** [comment]
There is a `t` filter => `{ Model.ContentItem.Content.Person.Name | t }`

**Comment by dodyg** [comment]
Oh great. I missed it in the doc (https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Liquid/#t)
