### ISSUE TITLE
Question: Group content items in Admin

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#4873]
I have like many pages (content items) in my project. Let's assume the structure is more or less like this

- About
  - About sub1
  - About sub2
...
  - About sub40
- Product
  - Product 1
  - Product 2
  ...
  - Product 100

I was thinking to create a new content type for the grouping with the content item AboutItems, ProductItems. These are lists containing the pages. Is that a way to go to group the items in the content item administration? Or is that bad practice? Is there any other way for this?

**Comment by dodyg** [comment]
Enable "Admin Menu" feature

**Comment by dodyg** [comment]
![admin-node](https://user-images.githubusercontent.com/1761249/69534941-77026700-0f83-11ea-9733-898f5d5be6d2.png)

**Comment by LMSSonos** [comment]
@dodyg thanks, this helps
