### ISSUE TITLE
razor layout error

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4883]
i got Errors in razor layout after update to the new version.

my dependencies:
```
    <PackageReference Include="OrchardCore.Media.Abstractions" Version="1.0.0-rc1-10861" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-rc1-10861" />

    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="1.0.0-rc1-10861" />
    <PackageReference Include="OrchardCore.Contents" Version="1.0.0-rc1-10861" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="1.0.0-rc1-10861" />
    <PackageReference Include="OrchardCore.Settings" Version="1.0.0-rc1-10861" />
    <PackageReference Include="OrchardCore.Users.Abstractions" Version="1.0.0-rc1-10861" />
    <PackageReference Include="OrchardCore.Users.Core" Version="1.0.0-rc1-10861" />
```

![1](https://user-images.githubusercontent.com/24512878/69572658-ea789880-0fc4-11ea-9c96-1999310d9921.JPG)

**Comment by aghili371** [comment]
this is the full error message:


`AspNetCore._Areas_OverStartUP_Pages_Users_Views_Shared_Layout.<ExecuteAsync>b__19_0() in Layout.cshtml
+
    <title>@RenderTitleSegments(Site.SiteName, "before")</title>
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
AspNetCore._Areas_OverStartUP_Pages_Users_Views_Shared_Layout.ExecuteAsync() in Layout.cshtml
+
<html lang="@Orchard.CultureName()">
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
OrchardCore.Facebook.ScriptsMiddleware.Invoke(HttpContext httpContext) in ScriptsMiddleware.cs
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
OrchardCore.Apis.GraphQL.GraphQLMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService, IAuthenticationService authenticationService, ISchemaFactory schemaService) in GraphQLMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
OrchardCore.Diagnostics.DiagnosticsStartupFilter+<>c__DisplayClass3_0+<<Configure>b__1>d.MoveNext() in DiagnosticsStartupFilter.cs
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
OrchardCore.ContentPreview.PreviewStartupFilter+<>c+<<Configure>b__1_1>d.MoveNext() in PreviewStartupFilter.cs
OrchardCore.Logging.SerilogTenantNameLoggingMiddleware.Invoke(HttpContext context) in SerilogTenantNameLoggingMiddleware.cs
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by aghili371** [comment]
@sebastienros Please if you have a solution inform me. 
i tested most versions before 1.0.0-rc1-10680 and those working fine. but the versions after this are not working.

i can not update to new versions and my project stopped. :(

this is the correct references which I'm using: 

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <TieredCompilation>true</TieredCompilation>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>612,618</WarningsNotAsErrors>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-10680" />
    <PackageReference Include="OrchardCore.Logging.Serilog" Version="1.0.0-rc1-10680" />
  </ItemGroup>`



my module:

```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="MD.PersianDateTime.Standard" Version="1.1.0" />
    <PackageReference Include="OrchardCore.Media.Abstractions" Version="1.0.0-rc1-10680" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-rc1-10680" />

    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="1.0.0-rc1-10680" />
    <PackageReference Include="OrchardCore.Contents" Version="1.0.0-rc1-10680" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="1.0.0-rc1-10680" />
    <PackageReference Include="OrchardCore.Settings" Version="1.0.0-rc1-10680" />
    <PackageReference Include="OrchardCore.Users.Abstractions" Version="1.0.0-rc1-10680" />
    <PackageReference Include="OrchardCore.Users.Core" Version="1.0.0-rc1-10680" />
    <PackageReference Include="RestSharp" Version="106.6.10" />
  </ItemGroup>

```

**Comment by jtkech** [comment]
Okay, some view features now are set through an `IAsyncActionFilter` that also needs to be an `IAsyncPageFilter` when we are in the context of a `@page` as it seems you are.

Already fixed on my side, i will do a PR soon.
