### ISSUE TITLE
wrong direction for New button in content management

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4884]
the menu of the new button should open in the right direction but it open in left direction.
![Capture](https://user-images.githubusercontent.com/24512878/69577818-81e2e900-0fcf-11ea-8146-9b90d008f28e.JPG)

**Comment by hishamco** [comment]
Yep, it's a UI bug

**Comment by hishamco** [comment]
@agriffard could you please check the new filter bar that you created, seems it doesn't work properl for RTL languages

**Comment by agriffard** [comment]
It is not a filter, it is the New button and I don't think I changed it at all.

**Comment by hishamco** [comment]
I thought you was 😊, no problem I will have a look

**Comment by Piedone** [comment]
This is fixed now:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/0f1243a0-32d3-4a1b-93f6-42a565c66bee)
