### ISSUE TITLE
Feature Request: Custom Recipe Parameters support

### ISSUE THREAD

**Issue by DariuS231** [OrchardCMS/OrchardCore#4889]
Would it be possible to have somehow support for Custom parameter values in the recipe? 
Something like:

in the appsettings.json

``` JSON
{
  "RecipeName": "Blank",
  "Secret": "...",
  "ConnectionString": "...",
  "DatabaseProvider": "Sqlite",
  "TablePrefix": "Test",
  "CustomParamAppID": "86eb5541-ba2b-4255-9344-54eb73cec375",
  "CustomParamTenantID": "4cc363b6-5254-4b8c-bc1b-e951a5fc85ac"
}
```
in the recipe

``` JSON
{
  "name": "Blank",
  "displayName": "Blank site",
  "description": "Creates a blank site with content management features.",
  "author": "The Orchard Team",
  "website": "https://orchardproject.net",
  "version": "2.0",
  "issetuprecipe": true,
  "categories": [ "default" ],
  "tags": [ "blank" ],

  "variables": {
  },
  "steps": [
    ... ,
     {
	"name": "azureADSettings",
	"appId": "[js: parameters('CustomParamAppID')]",
	"tenantId": "[js: parameters('CustomParamTenantID')]",
	"displayName": "Orchard Core AD App",	
	"callbackPath": "/signin-oidc"
      }
   ]
}
```
That way we can have features fully configured after tenant setup.

**Comment by MichaelPetrinolis** [comment]
you could create a custom module that executes the recipe passing a custom environment.
check IRecipeExecutor.ExecuteAsync

**Comment by DariuS231** [comment]
@MichaelPetrinolis agree, but I think there could be a lot of value having this feature natively.

**Comment by sebastienros** [comment]
There might be an open issue for that, we have suggested it already.
In a way that we could even plug it with some kind of Forms module, or at least with your own controller. Right now the simplest solution would be to just merge the two json documents, one with the recipe, and one with the variables, then execute this merged json document. Should be very easy.

What I had looked into was to actually describe the expected variables in the recipe itself, such that we could validate them before running the recipe. Or someone to even generate a form based on specific fields.

But the recipe service already accepts custom parameters AFAIR, and this is probably how we plugged the Setup form with the selected recipe.

Now, each variable can have a custom prefix, like `js:` to evaluate the variable as JavaScript. You could create a custom provider for `settings:[name]` that would take the value from the settings.

**Comment by hishamco** [comment]
> There might be an open issue for that,

AFAIK there is an issue that asking for similar thing but for the setup screen

**Comment by jtkech** [comment]
Normally when a setup is executing for a tenant, its `IShellConfiguration` has been registered and updated from the config sources, if configs are in the right sections, global or tenant specific ones.

So, as we already have a `VariablesMethodProvider` => `"[js: variables('blogContentItemId')]"`.

We could have a `ConfigurationMethodProvider` => `"[js: configuration('key')]"`. A provider that would inject and use `IShellConfiguration`. Hmm, would need to get the values from a section related to the running recipe.

Through the config sources (e.g `appsettings.json`),  we already can pre-configure e.g `ConnectionString`, `DatabaseProvider`, `TablePrefix`, for all tenants or a specific one, but beyond a given recipe name. If they are provided through a recipe section we would need to update the shell settings ...

**Comment by DariuS231** [comment]
I can work on a PR for this. 

Basically, create a  `ConfigurationMethodProvider` as @jtkech mentioned. The `ConfigurationMethodProvider` will receive the **ShellSettings** and retrieve the value to replace by `ShellSettings.ShellConfiguration["CustomPropertyKey"]`.

Would you be happy with this approach?
