### ISSUE TITLE
401 When editing taxonomy

### ISSUE THREAD

**Issue by devlife** [OrchardCMS/OrchardCore#4892]
I have google auth integration set up and when a user (has all built in roles selected, including `Administrator`) attempts to edit an existing taxonomy they get a `401`. Digging into this further, I don't see anything in the logs.

My logging config is currently set to the following. Please let me know if I should make any adjustments to get more detailed logs.

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
```
I am currently on version `1.0.0-rc1-10892`.

**Comment by devlife** [comment]
Any thoughts on this?

**Comment by MichaelPetrinolis** [comment]
If you login with local credentials and edit the taxonomy, you get the same error?
If you login with google can you create a new one and edit it ?

**Comment by devlife** [comment]
I do not get any errors when logged in with local credentials. Let me try creating one with google credentials.
