### ISSUE TITLE
Wysiwyg editor Insert media button not working

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4893]
I recently pulled latest code from dev, and noticed that Wysiwyg - Insert media button  is not working

**Comment by dodyg** [comment]
I can replicate this with version `1.0.0-rc1-10913`.

It happens at Trumbowyg editor

![xxxxx](https://user-images.githubusercontent.com/1761249/69787235-b8ce2000-11c4-11ea-938d-4b283bcb6878.png)


When you click on "Insert Media" it just shows a background fade and that's it.

![trumbogy](https://user-images.githubusercontent.com/1761249/69787265-cb485980-11c4-11ea-9341-15c229b8bc1f.png)

**Comment by agriffard** [comment]
Can you please refresh your browser cache and retry?
Tested on app with 1.0.0-rc1-10913 and it works for me.

Is it an HtmlBodyPart or an HtmlField?

In fact, if you use the Wysywig editor, you should ony see one 'Insert media' button.
With the 'Trumbowyg' editor setting and the default config, there will be 3 buttons.

**Comment by dodyg** [comment]
OK refreshing browser cache works now.

![works](https://user-images.githubusercontent.com/1761249/69807741-b41e6180-11ee-11ea-9c3c-9ce8226985b9.png)

How about you @ns8482e?

**Comment by ns8482e** [comment]
Refreshing browser did not work for me.

> In fact, if you use the Wysywig editor, you should ony see one 'Insert media' button.
I see only one button but clicking on that button does not open media 

> With the 'Trumbowyg' editor setting and the default config, there will be 3 buttons.
With Trumbowyg editor, I can see three buttons, - second and third button works, but "Insert Media" button doesn't work

**Comment by ns8482e** [comment]
Why there is two "Wysywig" and "Trumbowyg" editor options and both technically the same javascript "Trumbowyg" ?  It confuses more than it adds any value

**Comment by ns8482e** [comment]
Looks like this error seems because of different plugin behavior represented by same toolbar button, there should be two seperate buttons - "Insert Media - url" and "Insert Media - tag"
