### ISSUE TITLE
Question: File input form field

### ISSUE THREAD

**Issue by sayyad84** [OrchardCMS/OrchardCore#4896]
Hi,
What is the purpose of creating File input form field without implementing Upload it? Please provide details on how to implement Upload File input in workflow or other ways.
I created a workflow module to send the field value to the server via the File.Copy command, but it doesn't seem to be the right way.

**Comment by mst-dev** [comment]
Hi Orchard Team,

I found an Upload action in the following path in the project repo:
src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs

Does the built-in form use it?

I also tried using Input widget of type file to upload a file, but it seems not uploaded at all.

**Comment by dodyg** [comment]
@mst-dev check the code I uploaded at https://github.com/OrchardCMS/OrchardCore/issues/6027

**Comment by Piedone** [comment]
We have a File field for Forms now, so this can be closed. However, handling the file upload by Workflows after POST is not yet done, see https://github.com/OrchardCMS/OrchardCore/pull/12218.
