### ISSUE TITLE
GetInheritedTermsAsync does not exist in OrchardCore

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#4900]
I create a new View from Visual Studio and added the code snippet from https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Taxonomies/
```
@foreach(var termId in Model.TermContentItemIds)
{
    <div>
    @foreach(var parent in await OrchardCore.GetInheritedTermsAsync(Model.TaxonomyContentItemId, termId))
    {
        @parent
    }
    </div>
}
```
VS tells me, that the GetInheritedTermsAsync method does not exist in the namespace OrchardCore. I assume I have to inject something or add some extension method?

**Comment by dodyg** [comment]
You need to get `IOrchardHelper`.

https://github.com/OrchardCMS/OrchardCore/blob/688dbb32da17f8a3840f75485362104ea1a562b4/src/OrchardCore.Modules/OrchardCore.Taxonomies/Helper/TaxonomyOrchardHelperExtensions.cs

**Comment by deanmarcussen** [comment]
If it's normal cms mode (so with a theme), rather than decoupled the display helper is available in a view automatically as `Orchard.helper method`.

You will probably need to take a nuget reference on the Taxonomy module as well in your theme

**Comment by LMSSonos** [comment]
@dodyg thanks, this solved my issue. I use it in a filter so I had to inject it.
