### ISSUE TITLE
Profile Pages

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4901]
Whenever you start using a CMS the first big question is how to make profile pages for the authors of content.
Does Orchard Core have a default Author page?
If so the next issue would be to make custom modules or widgets just for the profile page to put things like latest content by the author.

**Comment by hishamco** [comment]
I think there's an old issue opened for user profile, hope to find it ..

**Comment by JoshTango** [comment]
I just want to know what the guidance is and how to add more features to it

**Comment by hishamco** [comment]
@agriffard is there any docs talking about the extensibility ?

**Comment by sebastienros** [comment]
@JoshTango do you mean something on the admin dashboard that could be customized by each user?

**Comment by JoshTango** [comment]
I actually meant a public profile page

**Comment by hishamco** [comment]
Seb seem this the same question that was asked during the latest standup meeting

**Comment by JoshTango** [comment]
Actually to be more clear.  This profile page acts as a "bridge" into social media.  Once each author has their own profile page you can start to make social media modules and widgets to create a social media app.  I think you just need a designated user page that is for the public and managed by the user.

**Comment by hishamco** [comment]
AFAIK profile is related to the User module, but other than that could e another module(s) for social media

**Comment by JoshTango** [comment]
does the user module have a public facing page?

**Comment by hishamco** [comment]
Nope, but you can extend it

**Comment by hishamco** [comment]
Related https://github.com/OrchardCMS/OrchardCore/pull/3141

**Comment by JoshTango** [comment]
I've actually worked on making one now.
