### ISSUE TITLE
Getting error message when trying to register ObjectGraphType for custom ContentPart 

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#4909]
So I have create a custom ContentType called Course, with a Content part called course Part:
Here is a part of my migration.cs:
```
            _contentDefinitionManager.AlterPartDefinition("CoursePart", builder => builder
                .Attachable()
                .WithDescription("CoursePart for fields related to courses")
                .WithField("CourseImageURL", f => f.OfType("MediaField").WithDisplayName("Course Image"))
                .WithField("CourseLogoImageURL", f => f.OfType("MediaField").WithDisplayName("Course Logo"))
            );

            _contentDefinitionManager.AlterTypeDefinition("Course", builder => builder
                .Draftable()
                .Versionable()
                .Creatable()
                .Listable()
                .WithPart("TitlePart", part => part.WithPosition("1"))
                .WithPart("CoursePart", part => part.WithPosition("2"))
           );
```
And here is my CoursePartQueryObjectType:
```
    public class CoursePartQueryObjectType : ObjectGraphType<CoursePart>
    {
        public CoursePartQueryObjectType(IStringLocalizer<CoursePartQueryObjectType> T)
        {
            Name = "CoursePart";
            Description = T["A CoursePart allows to add content items directly within another content item"];

            Field<StringGraphType>("FirstLectureId", "First Lecture Id", resolve: context => context.Source.FirstLectureId);
            Field<DecimalGraphType>("CoursePrice", "Course Price", resolve: context => context.Source.CoursePrice);
            Field<IntGraphType>("EstimatedTime", "Estimated Time", resolve: context => context.Source.EstimatedTime);
            Field<StringGraphType>("Category", "Category", resolve: context => context.Source.Category);
            Field<StringGraphType>("CourseShortDescription", "Course Short Description", resolve: context => context.Source.CourseShortDescription);
            Field<StringGraphType>("CourseDescription", "Course Description", resolve: context => context.Source.CourseDescription);

        }
    }
```

When I navigate to /admin/graphql I get the following Exception thrown: 
"A field with the name: course is already registered for GraphType: Course (Parameter 'Name')" 

Not sure where I went wrong as I am following existing examples for other ContentParts throughout the code

**Comment by carlwoodhouse** [comment]
The name of the part object graph type is conflicting with the contenttype name ... (as we trim 'Part' from parts in objectgraphtypes) in graphql ... you can fix it either by renaming the Name in your CoursePartQueryObjectType to CourseDetails or something, or by chosing the collapse option from graphql in your type configuration ...

as at the moment your query is going to look like 

```
course {
  displayText
  course {
    coursePrice
  }
}
```

Collapsing would change it to 

```
course {
  displayText
  coursePrice
}
```
or with renaming 
```
course {
  displayText
  courseDetails {
    coursePrice
  }
}
```

if you want to configure collapsing you would do it like so 
```
            _contentDefinitionManager.AlterTypeDefinition("Course", builder => builder
                .Draftable()
                .Versionable()
                .Creatable()
                .Listable()
                .WithPart("TitlePart", part => part.WithPosition("1"))
                .WithPart("CoursePart", part => part.WithPosition("2")      
                  .WithSettings(
                      new GraphQLContentTypePartSettings
                      {
                          Collapse = true
                      })))
           );
```

**Comment by JoshLefebvre** [comment]
Unfortunately neither of these solutions worked... When I change the part name to CourseDetailsPart I instead get the following error: 
`"A field with the name: courseDetails is already registered for GraphType: Course (Parameter 'Name')"`

The only thing that seems to work for me is removing the MediaField registrations in my migration.cs file:
```
            _contentDefinitionManager.AlterPartDefinition("CourseDetailsPart", builder => builder
                .Attachable()
                .WithDescription("CourseDetailsPart for fields related to courses")
                //.WithField("CourseImageURL", f => f.OfType("MediaField").WithDisplayName("Course Image"))
                //.WithField("CourseLogoImageURL", f => f.OfType("MediaField").WithDisplayName("Course Logo"))
            );
```

**Comment by jrestall** [comment]
The issue is likely that you are mixing both dynamic fields (CourseImageURL) and a typed part (CoursePartQueryObjectType). 

We have two ```IContentTypeBuilder ```, one for typed content parts and another for dynamic. We don't support mixing them as they will both try to add the same field name, resulting in "A field with the name: course is already registered for GraphType: Course (Parameter 'Name')".

https://github.com/OrchardCMS/OrchardCore/blob/24658f532014f33fa3f94094ee8029fc667368b7/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/TypedContentTypeBuilder.cs#L79

https://github.com/OrchardCMS/OrchardCore/blob/24658f532014f33fa3f94094ee8029fc667368b7/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/DynamicContentTypeBuilder.cs#L64

@carlwoodhouse option of collapsing should work if you do it on the course details part. Maybe like this,

```
_contentDefinitionManager.AlterTypeDefinition("Course", builder => builder
                .Draftable()
                .Versionable()
                .Creatable()
                .Listable()
                .WithPart("TitlePart", part => part.WithPosition("1"))
                .WithPart("CourseDetailsPart", part => part.WithPosition("2").WithSettings(
                      new GraphQLContentTypePartSettings
                      {
                          Collapse = true
                      }))
           );
``` 

It would be nice to support this scenario but it's not very easy.

**Comment by JoshLefebvre** [comment]
Ahhh ok was not aware of this! Anyways I have since added the dynamic fields to a separate part and all is good now besides the other issue of the dynamic fields https://github.com/OrchardCMS/OrchardCore/issues/4930 which you are currently looking into. 

Thanks again for the help. I will close this issue
