### ISSUE TITLE
divided_by filter wrong result

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4912]
Version `1.0.0-rc1-10913`.

The correct result for `{{ 5 | divide_by: 2 }}` is `2` (https://shopify.github.io/liquid/filters/divided_by/)  but that's not always the case.

![divided_by](https://user-images.githubusercontent.com/1761249/69806006-97802a80-11ea-11ea-909b-325f2bbf36d1.png)

This is how I call the shape

![divided_by_2](https://user-images.githubusercontent.com/1761249/69806257-268d4280-11eb-11ea-9eeb-e6d249c844a9.png)

**Comment by hishamco** [comment]
This is related to Fluid, let me have a look ..

**Comment by dodyg** [comment]
It's a weird bug. I had to add `floor` to the statement to make sure the result is as expected.

`{% assign total_pages = Model.TotalItems | divided_by: Model.PageSize | floor %}`

**Comment by hishamco** [comment]
Please hold on .. I will a push a PR now

**Comment by hishamco** [comment]
This should be fixed in https://github.com/sebastienros/fluid/pull/164

**Comment by osolvi** [comment]
Version `1.0.0-rc2-13700`

`{{ 5 | divided_by: 2.0 }}` returns `2` instead of `2.5`, but when `{{ 5 | divided_by: 2.01 }}` it works fine.

Expected that divided_by: 2.0 will return double result

**Comment by sebastienros** [comment]
I might have introduced a regression as the logic with floats changed in Fluid. I will try to add this specific example as a unit test. But it might also be that we need to update the version of Fluid.

**Comment by sebastienros** [comment]
@osolvi There are already some unit tests verifying that this is working correctly:

https://github.com/sebastienros/fluid/blob/dev/Fluid.Tests/ParserTests.cs#L285-L286

Can you try to reference this version: 1.0.0-beta-9672 of Fluid and test again? We might just need to update the reference to fix the issue.

**Comment by osolvi** [comment]
Hi @sebastienros,

I have checked with suggested version and it works fine.
