### ISSUE TITLE
Css '.fixed-top' class for #mainNav in TheBlogTheme does not show on scroll down

### ISSUE THREAD

**Issue by eflatz** [OrchardCMS/OrchardCore#4913]
On scrolling down #mainNav jQuery assigns is-fixed class but main nav stays out of view port due to negative top property in the CSS declaration:  

File src/OrchardCore.Themes/TheBlogTheme/wwwroot/css/clean-blog.css:

#mainNav.is-fixed {
    /* when the user scrolls down, we hide the header right above the viewport */  
    position: fixed;  
    top: -67px;  /* this needs to be removed*/  
    -webkit-transition: -webkit-transform 0.2s;  
    transition: -webkit-transform 0.2s;  
    transition: transform 0.2s;  
    transition: transform 0.2s, -webkit-transform 0.2s;  
    border-bottom: 1px solid white;  
    background-color: rgba(255, 255, 255, 0.9);  
  }

I fixed it by removing the top property from the CSS declaration.

Cheers,
e.

**Comment by Piedone** [comment]
Can you please elaborate what exactly does this fix, like with a screenshot of before-after? The current version of the The Blog Theme seems fine to me, also when scrolling down.
