### ISSUE TITLE
Localization settings issue

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4914]
While i'm testing my PR, I notice that whenever I enable the localization module, the localization settings doesn't load the cultures list, but the save button is there

I know the main reason for that at my side when the internet is slow, so the vue js view isn't loaded, so can we disable the button to avoid such issue or may be load the vue js from the local resource instead to pull them from CDN directly

![Localization settings](https://user-images.githubusercontent.com/3237266/69824547-2017be80-121d-11ea-95b2-3a9757eb9103.png)

/cc @sebastienros @deanmarcussen

**Comment by Skrypt** [comment]
I think the idea is to use the admin settings related to use a CDN or local resources but I can relate to that issue while I had a power outage in here I had some things not loading properly. One thing that we should test is to try to compile OC with internet and to disconnect internet while using it locally to figure out which scripts won't load if using local resources. Make also sure to flush your browser cache while doing so.

**Comment by hishamco** [comment]
> Make also sure to flush your browser cache while doing so.

I will have a try

**Comment by hishamco** [comment]
Seems the issue occurs frequently

**Comment by Piedone** [comment]
We now have CDN and Resource Debug Mode settings that should cover this. If not, please reopen.
