### ISSUE TITLE
Problem: Add reference to theme

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4916]
I generated a site using he code templates and I generated a theme also.

When I tried to right click on the project file to add a reference to the theme there was no option to add a reference to another project.  I am using vs2019.

Is this the experience for other people as well?

**Comment by agriffard** [comment]
Did you add the theme to your solution first?
Then, it will be available tp add it as a reference.

**Comment by JoshTango** [comment]
hmmm yes your probably right, the generator did not make a solution file. 
This explains it.

**Comment by JoshTango** [comment]
I am unable to see how to make a blank solution file in vs2019

**Comment by agriffard** [comment]
File > New > Project
There is a 'Blank solution' template.

Or else, If you have just a VS open with only one csproj, it suggests you to save a solution file when you close VS.

**Comment by JoshTango** [comment]
well I used the orchard templates to generate a website and it worked.
But I can not find a way to add a solution file.

**Comment by agriffard** [comment]
When you close Visual Studio, it will suggest you to save a solution file.
