### ISSUE TITLE
Move IDataMigrationManager.UpdateAsync() to an extension method

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4917]
While i'm working on data docs, I notice that `IDataMigrationManager` has two versions of `UpdateAsync()` one accept feature and the other one accepts a list of features

IMHO the `UpdateAsync(IEumerable<string> features)` could be an extension methods instead

/cc @jtkech

**Comment by Piedone** [comment]
I'd rather do it the other way around: `UpdateAsync(IEnumerable<string> featureIds)` can (and actually does) optimize updating multiple features and do it better than just call `UpdateAsync(string featureId)` in a loop.

**Comment by hishamco** [comment]
That's what I refer to, to make the one that accepts the `IEnumerable<string>` extension method that loops through each featureId
