### ISSUE TITLE
Features Demos

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4920]
It would be great to have demos to show the most used features ot the most interesting end-to-end scenarios.

A 5 min video could be a good way to demo the steps and actions to execute in VS or in admin.

If each week, we decide to keep the latest 5 min of the Tuesday meeting for this purpose, we will have 4-5 videos each month.

If the guys from Lombiq can edit the recording and upload the video on Youtube, then we can add it to the documentation easily. 

If some people are interested to prepare this kind of demo for a future meeting, please leave a comment.

You can also ask which feature you would like to see. 

The demo must have a limited scope and a well defined, quickly and simply achievable goal.

A few examples:

- Create a new theme, Liquid or Razor.
- Add a zone in a theme, configure a layer and add a widget.
- Create a new content type and edit the Details and the Summary template.
- Create a contact form with a workflow.
- Create a query and display the results.
- Configure the indexing and the search.
- Create a role with specific permissions.
- Configure an external authentication.
- Create a deployment plan, export data, create a recipe.
- Localize contents and add a content selector.

**Comment by hishamco** [comment]
I saw a new video for Tags using Taxonomies in Lompiq channel such videos is informative and cool
