### ISSUE TITLE
Question: Admin/Contents/ContentItems Group or Filter by Localization

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#4921]
Is there a way to filter by localization or group by localization. If you have 100 Content-Items per localization it starts to get big and would be good if you just see one localization

**Comment by hishamco** [comment]
I don't think we have this today. @agriffard did you add this in the new filter bar?

There are two things we can add to make this easier:

1. Add a filter in then content items page

2. There's a feature that I asked for "Translations Matrix", probably it's 1.1 feature, this will help you to know which translation is missing for a particular content item

**Comment by LMSSonos** [comment]
> Add a filter in then content items page

That would be a very handy feature!
