### ISSUE TITLE
OrchardCore.Layers docs is missing

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#4928]
https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Layers/

**Comment by agriffard** [comment]
Duplicate of #3111

Please check that there is no existing issue before creating one, with the 'documentation' label for example.
When I did the new docs, I even tried to link the missing docs in the corresponding page:
See TBD Layers and Zones in https://orchardcore.readthedocs.io/en/dev/docs/topics/content-management/

**Comment by hishamco** [comment]
> Please check that there is no existing issue before creating one, with the 'documentation' label for example.

Ok, thanks
