### ISSUE TITLE
Unable to query ContentFields using GraphQL

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#4930]
I have created a custom content type, with a custom part that is made up of a few contentfields in my migration.cs:

```

_contentDefinitionManager.AlterPartDefinition("CourseMediaPart", builder => builder
    .Attachable()
    .WithDescription("CourseMediaPart for images related to courses")
    .WithField("CourseImageURL", f => f.OfType("MediaField").WithDisplayName("Course Image"))
    .WithField("CourseLogoImageURL", f => f.OfType("MediaField").WithDisplayName("Course Logo"))
);

_contentDefinitionManager.AlterTypeDefinition("Course", builder => builder
    .Draftable()
    .Versionable()
    .Creatable()
    .Listable()
    .WithPart("TitlePart", part => part.WithPosition("1"))
    .WithPart("CourseDetailsPart", part => part.WithPosition("2"))
    .WithPart("CourseMediaPart", part => part.WithPosition("3"))
    .WithPart("ListPart", part => part.WithPosition("4").WithSetting("ContainedContentTypes", new string[] { "Module", "Quiz" }))
);
```

However despite creating content items with the contentfields in CourseMediaPart populated with image paths (and ensuring they are stored properly in the db), the following graphql query is always returning null:
![image](https://user-images.githubusercontent.com/22512098/69908081-43bf3e00-13b0-11ea-953d-b6f3baa913f9.png)

I tested out the same scenario using a text field instead media field, and I am getting the same behaviour

**Comment by jrestall** [comment]
Hey @JoshLefebvre,

Can you try lowercase the field names just as a guess. e.g. ```.WithField("courseImageURL"```.

Otherwise you will have to debug through and see why it isn't returning a value.

**Comment by JoshLefebvre** [comment]
Tried with the lower case field name and still the same behavior. When I set a breakpoint at the line you have suggested, it seems to be unable to resolve the contentPart:

```
var typeToResolve = context.ReturnType.GetType().BaseType.GetGenericArguments().First();

var contentPart = context.Source.Get(typeof(ContentPart), field.PartDefinition.Name); //Returns null
var contentField = contentPart?.Get(typeToResolve, context.FieldName.ToPascalCase());
return contentField;
```

field.PartDefinitionName is set to "CourseMediaPart" and it is unable to be resolved by using contentElement.Data[name] in the image below:

![image](https://user-images.githubusercontent.com/22512098/69924372-0d012a80-1479-11ea-9ef2-66c6edc5958b.png)
