### ISSUE TITLE
OrchardCore.Users Module NotSupportedException

### ISSUE THREAD

**Issue by justlucky** [OrchardCMS/OrchardCore#4932]
![a](https://user-images.githubusercontent.com/247791/69933427-ac6dfe00-1509-11ea-841c-81649ba019da.jpg)

throw new NotSupportedException(Resources.StoreNotIUserAuthenticationTokenStore);

**Comment by hishamco** [comment]
Are you sure that the exception came from Users module, could you please check the stack trace, seems it's ASP.NET Core exception

**Comment by justlucky** [comment]
the OrchardCore.Users module has UserStore class, not implemented IUserAuthenticationTokenStore interface.

**Comment by hishamco** [comment]
Please explain your scenario, so the other folks can understand the issue and help you

**Comment by Piedone** [comment]
Closing due to no reply from the author.
