### ISSUE TITLE
Table 'xxx.xxx_numericfieldindex' doesn't exist

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#4938]
Hi,I get the OrchardCore source code and run today (the git last commit dat is 2019-12-03 10:25), I create a ContentPart, ContentType and add a field, after this, I modified the field and check the 'Include this element in the index ' On,then I creat a new ContnetItem get this error 'Table 'orchardc_h.oc_numericfieldindex' doesn't exist.

![image](https://user-images.githubusercontent.com/3222379/70024368-cd4f5580-15d4-11ea-8a7e-ef9050a1ef54.png)

**Comment by dodyg** [comment]
That's weird because `Include this element in the index` is supposed to be only relevant for Lucene index.

**Comment by Skrypt** [comment]
DB name prefix issue more likely. Or table name length issue. Not sure but not related with Lucene at all.

**Comment by RockNHawk** [comment]
this issue fixed in new dev version
