### ISSUE TITLE
Mutable recipe variable

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#494]
It would be useful we can set a value for a variable in a recipe from a command step.

In my scenario I will provide a command for creating an autogenerated certificate. This command will set thumbprint and certification store name to variables. I will use these variable to set Orchard open id settings.

It would be interesting also that I can use a parammeter value as a parammeter for calling a command.

**Comment by Piedone** [comment]
This is now covered by JavasScript functions in recipes.
