### ISSUE TITLE
Inconsistency in media file extension filtering

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#4941]
MediaFileStoreResolverMiddleware (only used with Azure Media Storage) introduces a file extension check that we don't have with the default media file storage.

So, with default media file storage you can serve all file extensions, but with azure media storage you are limited to allowed file extensions.

I think we should remove the check from `MediaFileStoreResolverMiddleware` because it's not its responsibility.

@deanmarcussen do you agree ?

**Comment by deanmarcussen** [comment]
Yeah, I'm fine with that. When we spoke about it Sebastien said that the original intention with the allowed file extensions was to restrict it in the admin, but still allow a developer to manually rename the file in the file system, or in this case blob, and still have the file served.
