### ISSUE TITLE
A list of public OrchardCore CMS Websites 

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4943]
https://fly.eg/

- Decoupled CMS (English & Arabic).
- Two custom modules

**Comment by hishamco** [comment]
Wow Egyptian Website, @dodgy are you in the Egypt?

**Comment by sebastienros** [comment]
Did you use content the localization module?

**Comment by dodyg** [comment]
@hishamco  yes, Cairo.
@sebastienros  yes.

**Comment by hishamco** [comment]
@agriffard @sebastienros can we list Orchard Core websites in the websites or docs as "Build With ♥ using Orchard Core"?

**Comment by sebastienros** [comment]
https://showorchard.com/gallery/category/orchard-core

**Comment by cmrdY** [comment]
@dodyg I am really interested in how that website was implemented using Orchard Core. Do you have a blog or something I can follow?
Thanks in advance

**Comment by hishamco** [comment]
Can we have a better way to manage the websites that powered by OC so we can easily move them to https://showorchard.com/gallery/category/orchard-core?

/cc @agriffard @Piedone

**Comment by Piedone** [comment]
Well, if somebody lets me know here or via crew@showorchard.com we'll publish it within hours :). This site has been in the Show Orchard gallery for quite a while.
