### ISSUE TITLE
 Need an equivalent of Url.Action in Liquid

### ISSUE THREAD

**Issue by Michelangela** [OrchardCMS/OrchardCore#4944]
I have an issue on my localhost if I use tenants: routing works with  an URL like https://localhost:6001/mytenant/ , but it does not work for https://localhost:6001/mytenant as it routes using the root URL, losing the tenant in the URL. 

The suggestion is to have an equivalent of Url.Action(...) be implemented in Liquid.

**Comment by agriffard** [comment]
You can use: `{{ '~/' | href }}`
