### ISSUE TITLE
Document table content size issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#4951]
Some people have reported that using the FlowPart and BagPart might cause the Document.Content column to slow down the SQL Queries. In fact, recently I looked at one DB where they had around 50k lines of JSON data for a single row. The result makes querying with _session.Query<ContentItem, ContentItemIndex>() quite slow. One solution is to create a custom index provider to map the Content Fields that are needed for filtering and to only Query that table to return a list of DocumentId's to retrieve on a second Query. But that's not optimal as the Document table queries is the base of almost all Queries that are made. One solution proposed on Gitter was to use SQL Server column compression. Which could fasten up the network transactions for these queries by compressing the data before sending it. Though, a nvarchar(max) can contain up to 2gb of data, which makes the previous solution not appropriate. I'm thinking that the BagParts and FlowPart might require eventually to be saved in a different table that is lazy loaded instead to fix completely the main issue. This BagPart table could then be using a compressed column.

//cc @themattkenney

**Comment by sebastienros** [comment]
Is it because some queries don't actually need to fetch the data but it still gets read? Do you have an example where we could repro this behavior?

**Comment by Skrypt** [comment]
Ask @themattkenney he has an example of this issue in one of his project. He has a database that takes around 40 seconds for doing a "SELECT TOP(5) FROM Document"

**Comment by sebastienros** [comment]
Or you are talking about a different query that is systemic in OC, other than the example you gave.

**Comment by Skrypt** [comment]
Yes just for filtering to mitigate querying the document table. But as I said that would not be the best solution. Another mitigation is to compress the content column data at the same time but it's still not the best approach to keep the Document queryable fast.

The best approach that is against the principle of the BagPart/FlowPart would be to externalize it's content to a different table since that this is what makes it grow in volume. You want to query the Document table quick but then you can decide if you want or not to query it's content. OR Maybe, something like _session.Query<ContentItemIndex, FlowPartIndex>()

**Comment by sebastienros** [comment]
So you are actually saying that this is because some queries do download the Documents when they are not necessary. And I want an example so I can investigate that.

**Comment by Skrypt** [comment]
I'll try to create a repro. Though easy way would be to have a dump of @themattkenney database to reproduce the issue.

**Comment by themattkenney** [comment]
@Skrypt @sebastienros sorry I have been on vacation away from the cell and web and just getting caught up. @sebastienros I can get you a copy of the DB to reproduce. Any recommendations would be appreciated. We are working on ways to speed it up while still using the OC document table, but with only 4,000 records and running into issues, I am concerned for a large DB.

**Comment by Skrypt** [comment]
Large DB is relative here.

**Comment by themattkenney** [comment]
@Skrypt and @sebastienros  you should both have access to a private repo to see what we are experiencing.

**Comment by Skrypt** [comment]
I'll have some time more like this week-end.

**Comment by themattkenney** [comment]
@Skrypt & @sebastienros I am sure there are still some optimizations that can happen, but since we implemented index tables we have not had any issues.

**Comment by Skrypt** [comment]
I'm closing as I think using IndexingProviders is the solution.
