### ISSUE TITLE
Is it possible to inject IFileProvider in Controller or Service?

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#4954]
I have a  JSON file with some data,  in  root of my module project. which gets embedded into the assembly on build. I want to read content of this file in singleton Service of the module
 
I found that there is "ModuleEmbeddedFileProvider" which provides implementation of IFileProvider.  I am trying to use that to read embedded content from module.

Here is how I am registering my service in module

**Service**
```
public class HerosService : IHerosService
    {
        private IFileProvider _fileProvider;

        public HerosService(IFileProvider fileProvider)
        {
            _fileProvider = fileProvider;
        }

    }

```

**Statup**

```
 public class Startup : StartupBase
    {
        public override void ConfigureServices(IServiceCollection services)
        {

            services.AddSingleton<IHerosService, HerosService>();
       }

    }
```

However I am getting following exception 
`InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.FileProviders.IFileProvider' while attempting to activate "HerosService"`

It seems IFileProvider is not available in service collection, How do I access the instance of ModuleEmbeddedFileProvider from DI?

**Comment by jtkech** [comment]
You need to inject `IHostEnvironment` and use its `ContentRootFileProvider` that in our case is a `CompositeFileProvider` including our `ModuleEmbeddedFileProvider`.

Then you will be able to access your file under the virtual folder `Areas/YourModule/...`.

**Comment by ns8482e** [comment]
@jtkech It worked - Thank you.

However I am curious to know that -  when I keep file at "Assets\Heros.json" it did not embed but at "Data\Heros.json" it gets embedded regardless of whether I chose to embed via Visual studio or not.

It's embedding all files except under "Assets"

Shouldn't it be opt-in strategy to embed files to avoid accidental embedding files?

**Comment by jtkech** [comment]
We embed most of the files but not all, see in `OrchardCore.Module.Targets.props`.

    <ModuleAssetExcludes>Assets.*;Assets\**;**\*.props;**\*.targets</ModuleAssetExcludes>
    <ModuleDefaultAssetExcludes>$(ModuleAssetExcludes);**\node_modules\**;node_modules\**</ModuleDefaultAssetExcludes>
    <ModuleDefaultAssetExcludes>$(ModuleDefaultAssetExcludes);**\jspm_packages\**;jspm_packages\**</ModuleDefaultAssetExcludes>
    <ModuleDefaultAssetExcludes>$(ModuleDefaultAssetExcludes);**\bower_components\**;bower_components\**</ModuleDefaultAssetExcludes>

We embed all files under the module `wwwroot` folder but not those under the `Assets` folder that are only intended to be the inputs files of the gulp pipeline that will output the generated files (on a gulp build command) under the module `wwwroot` folder.

So yes you need to use any other folder but not the `Assets` one.

**Comment by ns8482e** [comment]
> We embed most of the files but not all, see in `OrchardCore.Module.Targets.props`.
Understood. 

I am trying to understand why Orchard Module Target needs to include all  with exclude list?
 `<EmbeddedResource Include="**\*"`

Shouldn't it be wise to use only include list for items that orchard core needs and everything else is excluded by default?  So module developer can decide what to embed and  avoid accidental embedding sensitive dev only files if any?

**Comment by jtkech** [comment]
Yes maybe but without knowing what we could need in the future we 1st opted to include "everything", then we used some custom variables and also some standard msbuild ones to still exclude the same kind of files that are also excluded when we do a publish on a web project, bin and obj folders, source files, folders as `.vs`, `.git`, `node_modules` and so on.

    <EmbeddedResource Include="**\*" Exclude="$(ModuleDefaultAssetExcludes);$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />

So that people don't have to add any embedded resources and they can remove some items by adding them e.g to the `DefaultItemExcludes` msbuild property in their module project file.

The exception being the `Assets` folder, sorry ;)

Note: But because now we define the above in a `.props` file that is evaluated before your module project file, finally i think that now you can add / remove items directly from the `EmbeddedResource` collection. So, if you really want your json file under the `Assets` folder, try this in your module project file.

    <EmbeddedResource Include="Assets\MyFile.json" ... />

**Comment by ns8482e** [comment]
@jtkech Thank you for your detail explanation, It surely helps a lot.
