### ISSUE TITLE
Content Picker Field is broken on the latest build

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4956]
All my Content Picker Field stops working after upgrading to `1.0.0-rc1-10998`.

![no-results](https://user-images.githubusercontent.com/1761249/70220426-3f4baa00-174f-11ea-89e9-76397274a9d4.png)

The problem happens to all Content Types that use Content Picker Field. 

I am using Standard Editor, not Lucene.

**Comment by deanmarcussen** [comment]
@dodyg seems to be working fine for me.

Can you try with latest build, a new version of bootstrap was merged last night?

Any console errors?

**Comment by Skrypt** [comment]
Works fine for me and I merged latest dev last night in my website project. Though @jtkech changed the way we are retrieving paths in the ContentPicker view. If you have custom implementations the javascript has also changed so it might be only an issue where the ContentPicker doesn't find the proper path (error 404) to your API to retrieve records.

**Comment by dodyg** [comment]
![work-now](https://user-images.githubusercontent.com/1761249/70373224-00088f00-18f0-11ea-930c-c16773740f18.png)

I restarted my computer and now it works. I didn't change a thing - still on version `1.0.0-rc1-10998`.             I am going to quit programming.
