### ISSUE TITLE
Admin Menu by Content Type is broken 

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#4958]
On `1.0.0-rc1-10998`, the admin menu link is broken after you filter the content items.

![broken-link](https://user-images.githubusercontent.com/1761249/70231181-7d9e9480-1762-11ea-9d01-d632a98667df.png)

![broken-link-2](https://user-images.githubusercontent.com/1761249/70231184-81321b80-1762-11ea-961a-06a1b884186a.png)

**Comment by jtkech** [comment]
Okay, i found the issue.

Yes, in each menu item by content type url we add a content type segment, but when already displaying a page listing items of a given type there is already a `contentTypeId` in the ambient route values, this ends up with 2 content types segments in the url.

Already fixed on my side, but i want to fix it in a better way, right now for these items we are using an mvc helper but only to generate a base url on which we add a content type segment, it is better to use the helper to always generate a full url for each item.

I will do a PR tonight.
