### ISSUE TITLE
Workflow content creation fix bug

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#4964]
![image](https://user-images.githubusercontent.com/16968103/70297145-ca986e80-1827-11ea-8d2f-d7b67d6b055e.png)

![image](https://user-images.githubusercontent.com/16968103/70296708-5c06e100-1826-11ea-9002-4eaf63488a98.png)
![image](https://user-images.githubusercontent.com/16968103/70296891-de8fa080-1826-11ea-963d-22fe048ac2b7.png)

**Comment by deanmarcussen** [comment]
What we might have to do is apply both regular content via json.merge and then apply the elements additionally

something like
```
                var propertyObject = JObject.Parse(contentProperties);

                ((JObject)contentItem.Content).Merge(propertyObject);
                var contentItemFromJson = propertyObject.ToObject<ContentItem>();
                contentItem.Apply(contentItemFromJson);
```

/cc @Skrypt 

Also related https://github.com/OrchardCMS/OrchardCore/issues/4963

**Comment by Skrypt** [comment]
To be honest I need to test from source code and repro. The Owner and Author could be assigned in a Handler with custom code so there's nothing asserting that this can be repro for now.
