### ISSUE TITLE
Taxonomy field editor generates bad html

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#4965]
Depending on how many taxonomy terms you have in a taxonomy the field editor adds the correct number of opening divs but does not always add the correct number of closing divs.

This means that any content item parts after the field editor get rendered as part of the field editors containing div.

The issue is in this code. https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Taxonomies/Views/TaxonomyField.Edit.cshtml
```
    if (entry.Level == previousLevel + 1)
    {
        WriteLiteral("<div class=\"pl-3\">");
    }
    
    for (var e = entry.Level; e < previousLevel; e++)
    {
        WriteLiteral("</div>");
    }
```

To repro add two root terms, with two child terms each.

Suggest that rather than fixing we replace the field editor with a vue multiselect tree editor https://vue-treeselect.js.org/ which is similar to the editor proposed for tags, but features a tree mode. There look to be enough good configuration options on the editor to support all we need with taxonomies, i.e. leaf selection only, auto expand all branches, multiple/single.

If agreed will try and do so after I've demoed tags again

![tree select](https://user-images.githubusercontent.com/13782679/70313755-1b02d280-180e-11ea-8af7-5e4c18561d0b.PNG)

**Comment by chinasqzl** [comment]
Adding a new Edit Option to Taxonomy Field doesn't work. Such as:
TaxonomyField-TreeSelect.Option.cshtml  @deanmarcussen

**Comment by deanmarcussen** [comment]
Adding custom editors does work, but there are some fixes for it in the tags branch, and may have to rework those tweaks a bit further.

At the moment the normal editor will show as well, as any other editor option.

**Comment by sebastienros** [comment]
Yes, please fix the current editor.
