### ISSUE TITLE
Question: Title Tag rendering with custom template

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#4966]
As an example, I have a content Type called `TextPage`, it has a Title-Part and a Markdown field. 
Then I added a new Template called `Content__TextPage`. In this one I add some logic to render the data like this:

```
<div id="contact">
  <h1>{{ Model.ContentItem.Content.TitlePart.Title }}</h1>
  {{ Model.ContentItem.Content.MarkdownBodyPart.Markdown | markdownify | newline_to_br | raw }}
</div>
```

In the `Layout.Liquid` file I have added following code to render the title:
`    <title>{{ "PageTitle" | shape_new | shape_stringify }}</title>`

If I navigate to a TextPage, no title is rendered. But if simply add  ` {{ Model.Content | shape_render }}`  after the last div in the template, it works. 

Is this correct that in custom templates you have always to call the shape_render for the model content? I think it's related to #4090

**Comment by sebastienros** [comment]
Use `{{ Model.ContentItem.DisplayText}}` to get the title.

Or to render the H1 and in the <title> tag use the shape from TitlePart:

`{{ Model.Content.TitlePart | shapre_render }}`

**Comment by LMSSonos** [comment]
In the end I solved it differntly by adding many if's into a loop, not nice, but works... so we can close this one.
