### ISSUE TITLE
Culture in a Widget takes culture from browser and not from content item

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#4970]
I have a contentitem that represents the page and that item has localization. I have localized it to DE (german) and EN (english). I added a widget which is rendered in a zone. The widget contains only `{{ Culture }}`

If I'm on an the german contentitem, my expectation is, that the outputted Culture is "de", but in my case it's "en". The reason, my browser favorite language is English, if I add German and move it to the top, then {{ culture }} outputs "de". 

Is this the expected behavior? If so, is there a option to access the current page Localization from the widget?

Thanks

**Comment by hishamco** [comment]
@jptissot is there an option that you made to pickup the right culture from content localization module?

**Comment by LMSSonos** [comment]
I just made following test, created a new CMS with the Agency templated, added Content Localization Feature and added Localization to the LandingPage. When I launch it in German on the top, where the Layout.liquid contains following code:

`<html lang="{{ Culture.Name }}">`

it outputs

`<html lang="en">`

expectaiton was that it outputs "de"

**Comment by Skrypt** [comment]
try with your url /?culture=de

**Comment by LMSSonos** [comment]
@Skrypt remains still <html lang="en">

**Comment by hishamco** [comment]
> try with your url /?culture=de

This should work, unless @jptissot override the default behavior or use some settings in the content localization module

I think I need to have a look ...

**Comment by Skrypt** [comment]
That's supposed to be the behavior of the Localization provider. If it doesn't work then you probably did not add the "de" culture in the culture list settings.

**Comment by hishamco** [comment]
> probably did not add the "de" culture in the culture list settings.

May be

**Comment by hishamco** [comment]
@LMSSonos

**Comment by hishamco** [comment]
Sorry I close it accidentally

@LMSSonos please let us know if you add the Dutch culture from the localization settings before doing a further investigation on this

**Comment by LMSSonos** [comment]
Steps to reproduce
1) Created new OrchardCMS v1.0.0-rc1-10004
2) Selecting Agency Theme (sqlite)
3) Admin > Configuration > Features > Enable content localization
![image](https://user-images.githubusercontent.com/19758451/70387323-3ef81c80-19a4-11ea-984c-9dc731c23c77.png)
4) Settings > Localization > Add culture
![image](https://user-images.githubusercontent.com/19758451/70387495-ec1f6480-19a5-11ea-8c70-48ec0572102a.png)
5) Content Items > LandingPage > Edit - Add localization part
![image](https://user-images.githubusercontent.com/19758451/70387336-867ea880-19a4-11ea-97aa-c877b8ff16ec.png)
6) Adding new LandingPage (de)
![image](https://user-images.githubusercontent.com/19758451/70387509-1a04a900-19a6-11ea-833c-a089430e2bbb.png)
7) calling in browser `/test2` => output `<html lang="en">`
8) calling in browser `test2?culture=de` => output `<html lang="de">`
9) adding language `de` to browser
![image](https://user-images.githubusercontent.com/19758451/70387424-83d08300-19a5-11ea-8d31-409d0819d341.png)
10) calling in browser `/test2` => output `<html lang="de">`
11) calling in browser `test2?culture=de` => output `<html lang="de">`

Personally I think, this behavior is wrong. Because the language is defined in the Localization of the StartPage Item, so the lang in the HTML code should always be identical, doesn't matter what the user adds to the query string or not. Maybe there is another correct way to access the localization of the current content-item from the liquid layout page?

**Comment by hishamco** [comment]
Thanks for the details, try to set `de` as default culture by choose the radio button in step 4

**Comment by LMSSonos** [comment]
description mentioned was with `de` as default, but now tested with `en` and behavior is the same. My confusion is, that the item localization is DE, but Config.Culture does not reflect that within the layout. So my initial question is (probably I was not clear) how do I access the content item localization form the liquid template like the AgencyTheme to get the right Culture or how do I make the same from a widget (probably it's the same logic)

**Comment by jtkech** [comment]
Yes, there are different culture providers depending on the enabled features and with different priorities.

Try to enable the `OrchardCore.ContentLocalization.ContentCulturePicker` feature, it provides a culture picker shape for the frontend that you are not forced to use, but it also adds an `ContentRequestCultureProvider` that  sets the Culture of a request from the `LocalizationPart.Culture` property.

**Comment by hishamco** [comment]
> Yes, there are different culture providers depending on the enabled features and with different priorities.

That's why I ping Jean at the beginning, coz I'm sure he did something to override the default behavior

**Comment by jptissot** [comment]
Yes, what @jtkech  mentions is correct. Maybe we should split the ContentCulturePicker and the ContentRequestCultureProvider into two features.

**Comment by Skrypt** [comment]
That same conversation happened a while ago. And we decided to not change the default behavior of the Localization Middleware which works fine. If you need to override it's behavior then you can do it in a custom module per your need. Activating the ContentCulturePicker on top of it should be fine enough for most people.

**Comment by LMSSonos** [comment]
> Try to enable the `OrchardCore.ContentLocalization.ContentCulturePicker` feature, it provides a culture picker shape for the frontend that you are not forced to use, but it also adds an `ContentRequestCultureProvider` that sets the Culture of a request from the `LocalizationPart.Culture` property.

@jtkech Thanks for this hint, i added the feature and the Culture is now as I would have expected it.  So for me it solves as workaround.

> There's no real need to deactivate one LocalizationProvider in the end if what you need is just to see a page in a specific culture explicitely.

@Skrypt I fully agree and was the behavior I expected
