### ISSUE TITLE
blogPost next and previous navigation

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4971]
How can i have navigation in a blogpost? i need to get the previews and next post to create the navigation blogpost page.

**Comment by dodyg** [comment]
Can you please clarify? Are you referring to providing navigation on a blog (a list of blogposts)?

**Comment by aghili371** [comment]
@dodyg i want in the blogpost page at the end of the page, have to links on to go to next blogpost and others to go to the previous blog post.
it keeps the user stay more on the website.

**Comment by hishamco** [comment]
It's there, please check the `Blog-ListPart.liquid`

**Comment by aghili371** [comment]
> Blog-ListPart.liquid

it is not what i want, this is the list of blogposts.

i need in showing the blogpost page, have 2 links to next and previous
![post](https://user-images.githubusercontent.com/24512878/70381216-d038a600-1946-11ea-8fee-960a8971a1a1.png)
 posts.

**Comment by hishamco** [comment]
I think you can do similar thing using liquid or Razor

**Comment by aghili371** [comment]
i think it is not a good way to get the list and then find that, if we have a query to get the current content position, it will be faster.

**Comment by hishamco** [comment]
I think you can do that using query module

**Comment by dodyg** [comment]
You can query `ContentItemIndex` for this.
