### ISSUE TITLE
Markdown Table

### ISSUE THREAD

**Issue by usloog** [OrchardCMS/OrchardCore#4974]
![image](https://user-images.githubusercontent.com/11717508/70386043-1e918780-19cf-11ea-8b15-26e0369a5da4.png)

Why?

**Comment by hishamco** [comment]
Seems you forgot a line break at the first line, I prefer to check markdown docs

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/70697890-58c99480-1d01-11ea-854e-6d3ae4555c94.png)
![image](https://user-images.githubusercontent.com/16968103/70697956-73037280-1d01-11ea-862a-20922764889b.png)
![image](https://user-images.githubusercontent.com/16968103/70697983-844c7f00-1d01-11ea-9505-976b870d29df.png)
![image](https://user-images.githubusercontent.com/16968103/70698011-929a9b00-1d01-11ea-975b-08b9292f158c.png) @hishamco

**Comment by dodyg** [comment]
`markdownify` doesn't support markdown table. I had to add an extra filter `markdownify2` (https://github.com/OrchardCMS/OrchardCore/issues/5017)

**Comment by arkadiuszwojcik** [comment]
closely related: #3846

**Comment by sebastienros** [comment]
We need to add this by default I assume, and optionally to provide a way to extend the markdig options by creating a custom editor that would expose most MarkDig options: https://github.com/lunet-io/markdig

**Comment by deanmarcussen** [comment]
This should be possible now as the feature has been implemented as `IOptions<MarkdownPipelineOptions>` registrations on the `MarkdownPipeline`

e.g
```
services
    .AddOrchardCms()
    .ConfigureServices(tenantServices =>
        tenantServices.ConfigureMarkdownPipeline((pipeline) => 
        { 
            pipeline.UseAdvancedExtensions();
        }));
```

Docs coming very shortly
