### ISSUE TITLE
Minify in vs2019

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4975]
I have made a copy of the agency theme in the source control and wish to modify it.
I noticed a gulpfile.
How am I suppose to regenerate the .min files?

Is there a recommended solution?  What are other people doing working on this project to regenerate the min files?

Was the agency.css.min file generated on someone's computer and then uploaded into the source control?

**Comment by hishamco** [comment]
Nooooooo,  you just need to `npm build`

**Comment by JoshTango** [comment]
No I generated a theme using the theme template, then I copied in the files from the agency theme
there is no package.json

**Comment by hishamco** [comment]
If you copy it from OC source, please copy `package.json` too

**Comment by JoshTango** [comment]
I did, its weird

**Comment by JoshTango** [comment]
I need time to fiddle with it

**Comment by hishamco** [comment]
@deanmarcussen is there a better way instead of copying the `package.json` ourselves?

**Comment by JoshTango** [comment]
it says it cant find the package.json

**Comment by JoshTango** [comment]
ok maybe I solved my minify problem byt downloading and using an extension
but I cant run the theme, I get errors

**Comment by JoshTango** [comment]
you can close this as I opened a new one here:

https://github.com/OrchardCMS/OrchardCore/issues/4982
