### ISSUE TITLE
Multi language web site

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4977]
I need to add another language to my web site.

i read this help :
https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/ContentLocalization/

i added this code, but it doesn't show my cultures:

```
<ul>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="oc-culture-picker" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{Model.CurrentCulture.DisplayName}}</a>
        <div class="dropdown-menu" aria-labelledby="oc-culture-picker">
        {% for culture in Model.SupportedCultures %}
            {% if culture.Name != Model.CurrentCulture.Name  %}
            <a class="dropdown-item" href="{{culture.Name | switch_culture_url }}">{{culture.DisplayName}}</a>
            {% endif %}
        {% endfor %}
        </div>
    </li>
</ul>
```

with this shape it shows the cultures :
	{% shape "ContentCulturePicker" %}

if i change the culture it shows the content for that culture but after going to another page it with the change to default culture.

how can i fix the culture?

do you have better help to do a multi-language web site?

**Comment by dodyg** [comment]
You can find my implementation notes here https://github.com/OrchardCMS/OrchardCore/issues/4121. It contains a lot of info regarding website implementation including multi lingual implementation.

**Comment by dodyg** [comment]
Further discussion about culture switching can be found here https://github.com/OrchardCMS/OrchardCore/issues/4594

**Comment by aghili371** [comment]
@dodyg i followed the topics, but it doesn't work. i think it needs better documentation.

**Comment by hishamco** [comment]
Thanks @dodyg for your reply, hope to add some of your notes to the docs if it's possible

@aghili371 what exactly doesn't work with you?

**Comment by dodyg** [comment]
> hope to add some of your notes to the docs if it's possible

Feel free to repackage anything I've written.

**Comment by hishamco** [comment]
I mean hope you add some of your notes in the docs 😊

**Comment by aghili371** [comment]
> @aghili371 what exactly doesn't work with you?

i think it doesn't save the current language. after running in next time, it doesn't know the selected language.

**Comment by hishamco** [comment]
Do you mean the current cultures picker?

**Comment by dodyg** [comment]
@aghili371 check this https://github.com/OrchardCMS/OrchardCore/issues/4594#issuecomment-563903664

**Comment by aghili371** [comment]
> Do you mean the current cultures picker?

yes that is true. so if i visit the web site and selected my language, why i should change the language in the next visit on other days? i think it needs to save the currently selected culture in user browser

**Comment by hishamco** [comment]
> why i should change the language in the next visit on other days?

The language is not saved, this the behavior common for almost websites if not all, what you said is suitable for admin language

**Comment by aghili371** [comment]
i checked Microsoft website, they just using culture in URLs. 
`products.office.com/**en**/compare-all-microsoft-office-products?=&activetab=tab%3Aprimaryr2&market=af`

**Comment by hishamco** [comment]
Ya, this is a querstring which already supported, but I'm not sure if @jptissot is use it or he used Cookie instead

**Comment by dodyg** [comment]
Cookie '.AspNetCore.Culture'

**Comment by hishamco** [comment]
As expected

**Comment by aghili371** [comment]
this is correct?
`<body  dir="{{Culture.Dir}}" >`

it doesn't work for me:
`<body dir="" data-gr-c-s-loaded="true">`

**Comment by hishamco** [comment]
How the culture fallback to invariant culture?!!

**Comment by aghili371** [comment]
![s](https://user-images.githubusercontent.com/24512878/71207393-0fe88180-22a7-11ea-9113-241cc9b61b90.JPG)

i selected invariant  language, it is empty.

**Comment by hishamco** [comment]
Why you do that?

**Comment by aghili371** [comment]
i need to add de, fa-ir, ar too.

**Comment by hishamco** [comment]
Why you didn't add them directly to the supported cultures list?

**Comment by Skrypt** [comment]
The Invariant culture name is String.Empty(). That's a small display issue.

**Comment by hishamco** [comment]
> The Invariant culture name is String.Empty()

Ya, but still wondering why he added it, while the intend is support `de`, `ar` and `fa-IR` cultures

**Comment by Skrypt** [comment]
I think that on Mac OS or some Linux distributions if it doesn't find a proper InstalledUICulture it will install the fallback culture which is the Invariant one. That's probably why he has it.

**Comment by jptissot** [comment]
Be careful as an empty dir attribute on the html element is Invalid html

**Comment by aghili371** [comment]
> > The Invariant culture name is String.Empty()
> 
> Ya, but still wondering why he added it, while the intend is support `de`, `ar` and `fa-IR` cultures

i just wanted to show you that. i have en and de.

**Comment by hishamco** [comment]
> the problem in getting empty dir by {{Culture.Dir}}

Try to print out the `CultureInfo.CurrentUICulture`

**Comment by aghili371** [comment]
Do we have the ability to localize site settings for every culture? for example, the site name is there, so it is not correct to use same name for all cultures.

**Comment by hishamco** [comment]
AFAIK everything should be localized except the once that data related, there's already a draft PR for data localization support

**Comment by jptissot** [comment]
It would be super useful to have the ability to add custom key value pairs for simple localized strings.
Then be able to refer them like site settings but it would get a localized version based on the current culture:

```
{{Site.LocalizedStrings.SomeKey}}
```
or 
```
{{Site.LocalizedStrings['fr'].SomeKey}}
```

**Comment by aghili371** [comment]
> CultureInfo.CurrentUICulture

i used this:
`<body  dir="{{CultureInfo.CurrentUICulture}}" >`
it still empty

**Comment by hishamco** [comment]
This will not happen unless you are using `InvariantCulture`!!

**Comment by Skrypt** [comment]
{{ CultureInfo.CurrentUICulture }} won't work. You need to debug and see what {{Culture.Dir}} returns and why.

**Comment by Skrypt** [comment]
See CultureLiquidTemplateEventHandler.cs
It sets the dir to string.empty when the culture is LTR. Proper fix is to set it to "ltr" or to not render a dir attribute at all when it's LTR as it is the default taken by HTML standards.

**Comment by hishamco** [comment]
I didn't realize that we have the same bug that we faced in Razor, @aghili371 you could use the latest bits and the `lang` will be `rtl`

Is there any further questions?

**Comment by aghili371** [comment]
how can i use .po in jquery?
i need to show  messages in multi culture :
`   $("#msg" + type).html("Please add your Email*");`

**Comment by hishamco** [comment]
I suggest to file a new issue, coz the original issue was about multilingual websites, but I notice it moves to another direction

**Comment by aghili371** [comment]
> I suggest to file a new issue, coz the original issue was about multilingual websites, but I notice it moves to another direction

okey i will file a new issue

**Comment by hishamco** [comment]
Is there any further thing here, or shall I close this?

**Comment by aghili371** [comment]
> Is there any further thing here, or shall I close this?

i just do a multilingual website and report the problems here, but if you think it will better to file new for any problem, close this.

**Comment by hishamco** [comment]
I will close this for now, bu t feel free to create new issues if you find any problems or bugs
