### ISSUE TITLE
Admin Site - Specific content type list, allow only new content item of the selected type

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#4985]
Hi everyone, 

I have created a custom Admin Menu with some nodes dedicated to list a specific content type: like Admin Menu interfaces allow to do.

My issue is related about the fact that when i click over the Admin Menu node dedicated to a specific content type it send me to a page where is listed all the items related to this content type but the "New" button allow me to create every content type is creatable in Orchard Core (this list is filtered by user permission?).
![admin_menu](https://user-images.githubusercontent.com/2736009/70457753-009c5380-1ab1-11ea-97ed-11100f67701c.jpg)

I would like to modify this functionality to allow user to create a content item of the content type listed without see other content type creatable.   

I have seen the code and I believe can do it if you allow me.

**Comment by sebastienros** [comment]
I think it shouldn't be hard to grab the current filter and change the way the New button renders if a filter is applied.

**Comment by PiemP** [comment]
For now my approach is "minimum impact": obtain the result without touch the razor file that render the button.

This fix is already done it in the PR https://github.com/OrchardCMS/OrchardCore/pull/5020. I'm waiting for you feedback about it.
