### ISSUE TITLE
Improvement needed: theme manifest file variable needed

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4986]
In the theme manifest file for example using the Agency theme is this line:
    .SetUrl("~/TheAgencyTheme/vendor/jquery/jquery.min.js", "~/TheAgencyTheme/vendor/jquery/jquery.js")

The string "TheAgencyTheme" gets repeated many times.

Please create a variable for this string and reference the variable in all the lines of code.

**Comment by hishamco** [comment]
Make sense

**Comment by Piedone** [comment]
How would you use this const? The theme name will never change. Or is your issue solely about the dislike of the string literal being repeated?
