### ISSUE TITLE
get permission to save cookie in user browser

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4987]
Regarding European roles, the user should accept save a cookie in his browser. 

is orchard save a cookie in user browser?
i have seen this message in the orchard before but it looks doesn't exist.

please if it is necessary to use, inform me where i can find this script?

**Comment by hishamco** [comment]
If am not wrong I already filed an issue long time back about cookies consent

I will search for it because this is a duplicate

**Comment by hishamco** [comment]
Duplicate of #3580, I think I will start on this before 1.0
