### ISSUE TITLE
Breaking AspNetCore change handling SameSite.None cookies

### ISSUE THREAD

**Issue by MatthijsKrempel** [OrchardCMS/OrchardCore#4993]
Since https://github.com/aspnet/Announcements/issues/390 certain external tools are not yet compliant, that means that they can't authenticate with OpenIdConnect.
I suggest removing the code, since this reverts it back to undefined.
We will have to look into this into more detail.

cc; @PinpointTownes

**Comment by EternityTeam** [comment]
I have similar problems in the old browser, users can't log in!
related articles:
[https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1](url)

**Comment by sebastienros** [comment]
I merged the PR yesterday, can you try using the latest dev branch? It's using dotnet 3.1 also since yesteday.

**Comment by PinpointTownes** [comment]
Are we sure this didn't break the OpenID module? (`prompt=none` authorization requests sent from hidden iframe, more specifically).

I remember @MatthijsKrempel and I chatted about that change and I'm pretty sure my conclusion was that this couldn't be as easy as simply removing `options.Cookie.SameSite = SameSiteMode.None;`.
While the ASP.NET team changed the default value to `Unspecified`, the cookie handler still uses `Lax`, which is not enough for `prompt=none` scenarios to work correctly.

I suspect we'll likely need to introduce some sort of user agent sniffing... eventually.

**Comment by MatthijsKrempel** [comment]
I specifically tested it with the OpenID module, the only thing that worked for us was to remove the line of code. In the documentation they talk about setting the setting to undefined, but that is not part of the enum. The only way to set it to undefined is not to set it.
________________________________

**Comment by PinpointTownes** [comment]
> I specifically tested it with the OpenID module, the only thing that worked for us was to remove the line of code.

Have you tried with `prompt=none` requests sent in an iframe?

> In the documentation they talk about setting the setting to undefined, but that is not part of the enum. The only way to set it to undefined is not to set it.

Weird, this flag was introduced in 3.1: https://github.com/aspnet/AspNetCore/commit/0a1e208c7637b1895a75b086f938861ed90457a3#diff-13ab2eef84a0162d2661d6c3f01f5dc1

**Comment by sebastienros** [comment]
The PR was created before we migrated to 3.1. I believe it should appear "now"

**Comment by PinpointTownes** [comment]
It's worth noting that `options.Cookie.SameSite = SameSiteMode.Unspecified;` should make the OpenID module work correctly with existing browsers, but it will stop working when new versions of Chrome and Firefox ship in January/February, since they'll assume that no same-site attribute (i.e unspecified) means `Lax`.

**Comment by MatthijsKrempel** [comment]
So we need a way to inject user agents and their prefered way of handling samesite cookies.

It's not something to look forward to, since they change it willy nilly.

**Comment by hishamco** [comment]
FYI there's a patch according to https://github.com/aspnet/Announcements/issues/390#issuecomment-575385338, but I'm not sure if it fixes the issue

**Comment by sebastienros** [comment]
Instructions: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

**Comment by MatthijsKrempel** [comment]
I'll have a look at Blowdart's recommendations ;)
