### ISSUE TITLE
How to detect current page is homepage in liquid

### ISSUE THREAD

**Issue by stantoxt** [OrchardCMS/OrchardCore#4996]
I want to detect that if current page is homepage in layout.I want to use request.path equal "/" in layout. Is there any liquid value out of box?

**Comment by sebastienros** [comment]
Does it solve your question? https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Liquid/#request

`Request.Path`

**Comment by stantoxt** [comment]
I can use {%if Request.Path="/"  %} in layout,but is there any  {%if CurrentPage.IsHome  %}  liquid syntax and I don't if this is the best way to judge currentpage is homepage.

**Comment by dodyg** [comment]
Yea `{% if Request.Path == "/" %}` will do the trick.

**Comment by stantoxt** [comment]
@dodyg thanks
