### ISSUE TITLE
How to use angular to create ContentItem?

### ISSUE THREAD

**Issue by stantoxt** [OrchardCMS/OrchardCore#4997]
I want to create a angular project to just create contentItems.Can oc team give some idea?I think the default creation of contentitem is difficult to understand by customer or editor who just need create or edit a contentitem.

**Comment by stantoxt** [comment]
Is this possible create customized contentItem page to submit json formatted contentitem using ajax.

**Comment by deanmarcussen** [comment]
You would use the OpenId module to provide authentication for you angular app, and the Workflow ContentCreateTask would provide a good endpoint to submit the data from you angular app.

The workflow Content Create Task takes json, so suits angular

**Comment by stantoxt** [comment]
@deanmarcussen thanks, I will have a try.
