### ISSUE TITLE
Liquid style/script notation does not work inside Admin Templates

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/OrchardCore#5004]
Steps to reproduce:
1. Add new template from UI(same as Layout.liquid file) inluding style/script notations like ```{% style name:"vendor-font-awesome", version:"5" %}```
2. Add a new content template based on previous
3. Render the content -> Empty lines where style/scripts should exist.

**Comment by sebastienros** [comment]
I don't understand what `Add a new content template based on previous
` means

**Comment by urbanit** [comment]
![image](https://user-images.githubusercontent.com/1871551/70747793-639c1d80-1d31-11ea-97a1-dd7069437eb1.png)

**Comment by urbanit** [comment]
So, there is a "Conference" layout template that has style/script notations. And the content template use the "Conference" template as layout... The result is empty css/javascript line...

**Comment by ns8482e** [comment]
In your case Content__Conference is Alternate shape for Content Shape for Content type Conference.
`Layout` is also a Shape hence setting ` {% layout "Conference" %}` in `Content__Conference`  won't work.

Instead you add alternate for "Layout" shape, e.g. Layout__Conference

**Comment by ns8482e** [comment]
I believe  `Content__Conference` content shape and `Conference` Layout shape are for front-end are applied from "Template" feature. Are you creating your templates in "Template" feature?

"Admin Templates" are for Admin theme not for front-end.

**Comment by jtkech** [comment]
Yes you can do that because the `layout` tag add a new layout alternate at the end of the list.

Just tried with the blog theme by adding templates through the admin UI of the `Template` feature, not the `Admin Template` as @ns8482e said that is related to override shapes for the admin theme.

So, i added a `Content__Article` template and a `Conference` layout template, a copy paste of the orginal one where i added a style line for testing. Then it worked.

**Comment by mouldt** [comment]
Same issue but not using {% layout %}
1. Created agency themed site
2. In admin created a Layout liquid template using the templates feature. Into this template I copied the content from the Layout.liquid file from the agency theme codebase.
![image](https://user-images.githubusercontent.com/1070461/72355516-8f6b4400-36df-11ea-9b25-0793f18e9ac8.png)

The effect should be benign as the two templates are identical. Just that admin created Layout template will take precedence over the theme embedded layout.liquid.

However instead I get a 500 error page.
"InvalidOperationException: Could not find a resource of type 'script' named 'theagencytheme-vendor-jquery' with version 'any." 
![image](https://user-images.githubusercontent.com/1070461/72355547-98f4ac00-36df-11ea-938f-83f4b3ce5992.png)

If I comment out the scripts and styles that reference a named bundle from the resource manager manifest
e.g.
{% style name:"theagencytheme-bootstrap-oc", version:"1" %}
then the error disappears.
Explicitly pathed scripts and styles load without any error e.g.
{% style src:"~/TheAgencyTheme/css/agency.min.css", debug_src:"~/TheAgencyTheme/css/agency.css" %}

so its a combination of the templates feature and named resource bundle usage that gives the error.

So the workaround might be to not use the named resource bundles and instead explicitly path any scripts and styles used in the template

**Comment by deanmarcussen** [comment]
@mouldt what version are you using? 

If it is the nuget version `RC1-1004` then the resource manifest file for those scripts did not exist then. It has recently been adding to the dev branch and nightly builds, so the templates have diverged a bit.

**Comment by mouldt** [comment]
@deanmarcussen - yes I'm using RC1-1004 and that was the issue thanks for the correction.
