### ISSUE TITLE
How to assign DisplayText to a Field for metadata content type when TitlePart is not used?

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5006]
I have created a Contact content type with Name and Phone# field using Admin UI ,  I am not using TitlePart for the content type. On list page all records shows as "Contact".  

How do I  assign "Name"  to be a DisplayText for content item?

![image](https://user-images.githubusercontent.com/23270244/70581013-5806f600-1b7b-11ea-9db3-60e8c5702bfe.png)

**Comment by sebastienros** [comment]
We did a feature for this recently. It might be on the TitlePart settings, you can provide a custom template. And also hide the Title editor so that you can't even change it manually.

**Comment by sebastienros** [comment]
I just confirmed it.

**Comment by ns8482e** [comment]
So there is no OOTB  way to show DisplayText without using TitlePart?

**Comment by sebastienros** [comment]
You don't "show" DisplayText, it's a value that has to be assigned to a content item. And we chose TitlePart to do it. But in your case it doesn't have to show an editor, just go in the setting and set which property should be copied to the DisplayText.

**Comment by ns8482e** [comment]
Understood...  However I am still wonder why not have the DisplayText pattern available directly on ContentTypeSettingsViewModel and completely remove dependency on TitlePart?
