### ISSUE TITLE
Create custom Taxonomy part

### ISSUE THREAD

**Issue by OlziiNaran** [OrchardCMS/OrchardCore#5007]
Q: 
1. I create a custom taxonomy part，called mkTaxonomy. 
![TIM截图20191211095816](https://user-images.githubusercontent.com/39524174/70584653-ca6bea80-1bfc-11ea-875c-400657e586ec.jpg)
2. I Need nest taxonomy. Added taxonomy Field. 
![TIM截图20191211100020](https://user-images.githubusercontent.com/39524174/70584754-10c14980-1bfd-11ea-924c-7491e11933b1.jpg)
3. But new Taxonomy Failed.
![TIM截图20191211100231](https://user-images.githubusercontent.com/39524174/70584898-80cfcf80-1bfd-11ea-8d8d-67592acf5b9c.jpg)
Help me, thank you!

**Comment by dodyg** [comment]
You can already create hierarchy of your taxonomy terms.

1. Create a taxonomy.
2. Select one or more Content Item as term(s).
3. Add your terms and organize them via drag and drop.

**Comment by OlziiNaran** [comment]
> You can already create hierarchy of your taxonomy terms.
> 
> 1. Create a taxonomy.
> 2. Select one or more Content Item as term(s).
> 3. Add your terms and organize them via drag and drop.

Okey, Thank you.

**Comment by hishamco** [comment]
@OlziiNaran please close this if your question is answered
