### ISSUE TITLE
Bypass Setup Page via Code

### ISSUE THREAD

**Issue by K-Bains** [OrchardCMS/OrchardCore#5011]
Q: is it possible to bypass the setup page and add the details via code? im hoping i can set up my site without any user interaction.

**Comment by hishamco** [comment]
I think @MatthijsKrempel pointed to that before

**Comment by agriffard** [comment]
See #4567 but not sure it is related.

**Comment by hishamco** [comment]
Exactly

**Comment by K-Bains** [comment]
Thank you very much hopefully this will get merged soon.
