### ISSUE TITLE
ResourceManifest.cs question for theme copy

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5012]
I have generated a new theme using the templates.
Then I copied over the Agency theme files from the source control including the manifest resource files.
My natural instinct was to go into the ResouirceManifest.cs and change all the "TheAgencyTheme" strings into the name of my new theme.
It doesn't work though.
Is this because its borrowing the theme files from another module?
Hhow should I configure this manifest file if it is now part of anew theme?

**Comment by deanmarcussen** [comment]
You should do eactly what you say you have done.

Adjust the `.SetUrl` property to point to your new theme.
and make sure the files you are pointing to exist in your new theme.

These questions better suited to gitter https://gitter.im/OrchardCMS/OrchardCore
