### ISSUE TITLE
Question: transactions?

### ISSUE THREAD

**Issue by vector-man** [OrchardCMS/OrchardCore#5015]
How does Orchard Core handle transactions when querying? I need to limit entries into a game, so I need transactions to prevent duplicate or too many entries.

**Comment by hishamco** [comment]
Have a look to this sample https://github.com/sebastienros/yessql/blob/de07b2237c14efd1630b35eb6e6ade962902d6cd/samples/YesSql.Samples.Gating/Program.cs#L60-L73

**Comment by sebastienros** [comment]
The default database access uses `ISession` which uses a single transaction for a request (unless others are started explicitly).

To prevent duplicates you can just call `session.Cancel()` if you find another "game" with the same properties. You could also create a custom UPDATE statement with a WHERE clause that matches the existing entry. 

For limiting the number of entries, I don't think transactions would be of any help.
