### ISSUE TITLE
How to replace an existing fluid filter

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5017]
`markdownify` filter doesn't support pipe table so I am trying to replace it with a markdig configuration

At first try, I introduce a new tag `markdownify2`. It works fine but it is annoying.
``` csharp
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
            services.AddLiquidFilter<Markdownify2>("markdownify2");
       }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();
            app.UseOrchardCore();
        }
    }
```

So now I am trying to replace the existing `markdownify`
``` csharp
   public class Markdownify2 : ILiquidFilter
    {
        static readonly MarkdownPipeline _pipeline = new MarkdownPipelineBuilder().UsePipeTables().Build();
        
        public ValueTask<FluidValue> ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext ctx)
        {
            return new ValueTask<FluidValue>(new StringValue(Markdig.Markdown.ToHtml(input.ToStringValue(), _pipeline)));
        }
    }

    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection ReplaceLiquidFilter<T>(this IServiceCollection services, string name) where T : class, ILiquidFilter
        {
            services.Configure((Action<LiquidOptions>)delegate (LiquidOptions options)
            {
                if (options.FilterRegistrations.ContainsKey(name))
                {
                    options.FilterRegistrations[name] = typeof(T);
                }
            });
            services.AddScoped<T>();
            return services;
        }
    }
```

``` csharp
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
            services.ReplaceLiquidFilter<Markdownify2>("markdownify");
       }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();
            app.UseOrchardCore();
        }
    }
```

This doesn't work because `if (options.FilterRegistrations.ContainsKey(name))` is always false because `options.FilterRegistrations` is always 0. My question is there any place where I can call `services.ReplaceLiquidFilter` when all the filters have been registered?

**Comment by ns8482e** [comment]
@dodyg Look  at following to see what AddLiquidFilter is doing. https://github.com/OrchardCMS/OrchardCore/blob/d729a2048a4390380d99e7be9f7968ff8f8e9271/src/OrchardCore/OrchardCore.Liquid.Abstractions/ServiceExtensions.cs#L7  

It configures `LiquidOptions ` and `AddScoped` service

Try to replace existing service with your own in your module -  and replace LiquidOptions

**Comment by sebastienros** [comment]
AddLiquidFilter should be able to replace an existing named filter. If it doesn't then we can change it.

**Comment by jtkech** [comment]
`AddLiquidFilter` uses `options.FilterRegistrations.Add(name, typeof(T))`.

It would have to use `options.FilterRegistrations[name] = typeof(T)`.

And to override the filter, the related module startup would have to run last, e.g by depending (in the manifest) on the feature that defines the original one.

**Comment by dodyg** [comment]
> And to override the filter, the related module startup would have to run last, e.g by depending (in the manifest) on the feature that defines the original one.

@jtkech is there anyway to configure this? This is the main problem with my `ReplaceLiquidFilter` implementation. It runs early.

**Comment by ns8482e** [comment]
@dodyg  I have not tried - but my guess is - It's runs early because you configure sevice in web application and not in module-  if you create a module that depends on other modules then dependency loaded before your module. 

Try creating  `ReplaceLiquidFilter ` in a module and add  Dependencies to Markdown module in Manifest.cs of your module

**Comment by jtkech** [comment]
Yes, when a module depends on another one, its startup is run after. For modules that don't depend on each other it will just depend on an alphabetic order. But you also have an `Order` and a `ConfigureOrder` properties that you can override in your startup class.

But it seems that you are doing things from the app, so in your app startup try something like this

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddOrchardCms()
            .AddOrchardCore()
            .ConfigureServices(s =>
                s.AddLiquidFilter<Markdownify2>("markdownify2")
                , order: 100);
    }

**Comment by dodyg** [comment]
Yes this works except that you can't use `AddLiquidFilter` because it will throw `ArgumentException: An item with the same key has already been added. Key: markdownify`

So this is a complete solution on how to replace the default `markdownify` implementation with your own custom implementation. It will work for any other filter as well. It's awesome!

`Startup.cs` at the app

```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using OrchardCore.Liquid;

namespace XXX.Web
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms()
                .AddOrchardCore()
                .ConfigureServices(s => s.AddLiquidFilter<Markdownify2>("markdownify"), order: 100);
        } 

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();
            app.UseOrchardCore();
        }
    }
}
```

`ExtraFilter.cs`

```
using Fluid;
using Fluid.Values;
using Markdig;
using Microsoft.Extensions.DependencyInjection;
using OrchardCore.Liquid;
using System;
using System.Threading.Tasks;

namespace XXX.Web
{
    public class Markdownify2 : ILiquidFilter
    {
        static readonly MarkdownPipeline _pipeline = new MarkdownPipelineBuilder().UsePipeTables().Build();
        
        public ValueTask<FluidValue> ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext ctx)
        {
            return new ValueTask<FluidValue>(new StringValue(Markdig.Markdown.ToHtml(input.ToStringValue(), _pipeline)));
        }
    }

    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection ReplaceLiquidFilter<T>(this IServiceCollection services, string name) where T : class, ILiquidFilter
        {
            services.Configure((Action<LiquidOptions>)delegate (LiquidOptions options)
            {
                if (options.FilterRegistrations.ContainsKey(name))
                {
                    options.FilterRegistrations[name] = typeof(T);
                }
            });
            services.AddScoped<T>();
            return services;
        }
    }
}
```

**Comment by jtkech** [comment]
> Yes this works except that you can't use AddLiquidFilter because it will throw

Oh yes my mistake, i wanted to specify `ReplaceLiquidFilter` ;)

I will do a PR so that you will be able to just use `AddLiquidFilter`.
