### ISSUE TITLE
Developer friendly modular widgets for data visualization

### ISSUE THREAD

**Issue by papyr** [OrchardCMS/OrchardCore#5021]
In this day and age you have to be more developer friendly.

_Many new trends are forcing people to re-evaluate the use of Orchard as a CMS_, while others implement, widgets and dashboards for e.g. via Tableau, Power BI etc.

We are clearly not that segment, but what is preventing us from implementing support for easy data visualization, or drag drop widgets. 

Its also fairly hard to learn and develop in Orchard. The use case has to make it easier for developers.

**Please let users and developers turn their own data/tables/view-models/modules into live data graphical widgets easily**

**Comment by sebastienros** [comment]
Looks like a vertical module that could be built with custom front-end widget to render data. But right now it's out of scope as it's too much work. I'd suggest you start working on that if you need it.

**Comment by papyr** [comment]
Thanks for the response. 

Its not a vertical module, just another content type widget for data visualization. DNN, site point and others already have this as a dashboard.

The C# and orchard framework lets us write the custom code, we need a container or an example on the very least to be able to add a graphing widget or plugin.
