### ISSUE TITLE
Theme static files mixing

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#5025]
For infos before i forget it.

As said on gitter

> at least there is problem when 2 enabled themes regiter the same resource name, the manager prevents duplicates so the first wins. E.g in the following image you can see that TheTheme uses a TheBlogTheme static file path ;)

Maybe we just need that each theme, in its `ResourceManifest.cs`, registers its resources with different names, maybe the theme name as a prefix.

Here the image where you can see that `TheTheme` uses a `TheBlogTheme` satic file path.

![Theme Manifest](https://user-images.githubusercontent.com/8586360/70772053-99fa8c80-1d73-11ea-9cf7-57558e959d96.png)

**Comment by hishamco** [comment]
> Maybe we just need that each theme, in its ResourceManifest.cs, registers its resources with different names, maybe the theme name as a prefix.

This simply done by using prefix as you said, but how we can ensure that name - with prefix - is not used somewhere else?

**Comment by hishamco** [comment]
I think this is what @JoshTango is asking for in #4988

**Comment by jtkech** [comment]
> This simply done by using prefix as you said, but how we can ensure that name - with prefix - is not used somewhere else?

Because we can't have 2 module / theme with the same name == assembly name

> I think this is what @JoshTango is asking for in #4988

Not exactly, here it's not a path conflict, it's a resource resolution mixing

**Comment by hishamco** [comment]
> Because we can't have 2 module / theme with the same name == assembly name

Right, I thought there's a way to use to extend an existing theme

**Comment by Skrypt** [comment]
I made a test which fails. I copied the TheAgencyTheme ResourceManifest.cs and Startup.cs files. Renamed the Namespace to match my theme name. So far no issues on the frontend when using that theme. Though, when going to the admin content list and user list I get an issue with the ResouceManager stating that it can't find the resource(s).

**Comment by JoshTango** [comment]
I removed the ResourceManifest.cs file and have moved on

**Comment by deanmarcussen** [comment]
And yet this is interesting.

@jtkech you will know this. 
Does enabling two themes mean both of their `Startup` files will be called? 
Or does the `Startup` only run when it is set to current?

If it's the first, then yes, we should use better naming on the theme `ResourceManifest` files that got added recently, otherwise I don't see the problem.

**Comment by jtkech** [comment]
> Does enabling two themes mean both of their Startup files will be called?

Yes for all enabled themes, not only the current one, after all modules startups because themes depend implicitly on all modules, but they don't depend on each other unless one theme has a `BaseTheme`. Otherwise the order of theme statups will only depend on an alphabetic order if we don't override the `Order` and / or `ConfigureOrder` properties of their startups.

Then there are different scenarios depending on the duplicate resources, the theme names, the kind of resources by urls / file paths, if each theme actually hold the related resource in its wwwroot or not ...

> If it's the first, then yes, we should use better naming on the theme ResourceManifest files that got added recently, otherwise I don't see the problem.

We could consider it's not a problem if it works for a `ThemeB` that defines a "duplicate" resource even if it grabs the exact same file but from another `ThemeA`, and this even if it doesn't have this resource in its own `wwwroot` folder. But in that last case, if you write the exact same `ThemeB` but with another name e.g `BTheme`, or if you remove `ThemeA`, it will win to register its own resource path but it will fail because it doesn't hold the related static file.

**Comment by deanmarcussen** [comment]
> We could consider it's not a problem if it works for a `ThemeB` that defines a "duplicate" resource even if it grabs the exact same file but from another `ThemeA`, and this even if it doesn't have this resource in its own `wwwroot` folder. But in that last case, if you write the exact same `ThemeB` but with another name e.g `BTheme`, or if you remove `ThemeA`, it will win to register its own resource path but it will fail because it doesn't hold the related static file.

Thanks for the info @jtkech 
I wanted to make sure that this wasn't what had been causing the odd `Resource not found with a given key` issue that's been reported a few times.

I think, based on your description, that actually this behaviour is both useful and desirable (but also good to know it happens!)

For example when using a custom admin theme that uses `TheAdmin` as a base because you want to provide some different css, it's actually useful that another module earlier in the pipeline could override `TheAdmin` css with it's own version of the resource, without having to override the `Layout` file in `TheAdmin. 
I'd done this recently with a custom AdminTheme, which then got broken when I bought in dev a month later, because the Layout file had changed.

Easier to do the override with the resource manager this way than trying to replace the `ResourceManifest.cs` in DI.

It probably is a very minor issue the for the sample themes, so makes sense to apply a prefix to the resources, i.e. `thetheme-bootstrap-oc`, knowing then that these resources names would still be overridable if one wanted to.

I might make a pr to that effect.

**Comment by jtkech** [comment]
Currently the 1st one that registers a resource wins, hmm, **maybe better that the last one wins** so that, without solving all scenarios, a theme would be able to override a resource of its base theme without having to use another module (because it runs before all themes).

So 1st, maybe allow to override a resource in a startup running after, easy to do in `DefineResource()`.

Then and only for themes, because the startup ordering is aware of dependencies but is not aware of the current theme, maybe some scoped dynamic resources relying on the current theme. But it may have a too big perf impact. I will think about it.

In fact they are all scoped services but there is an `IResourceManifestState` singleton that caches the manifests, so the scoped `BuildManifests()` are called once. Otherwise each one could check if it is the current theme or a base theme of the current one.

Hmm, maybe an event when we change the current theme to clear this cache, but this would be another thing to keep in sync when we will re-work on the distributed services. When i think of this kind of sync problem, when it could make sense one solution is to restart the tenant because we will have a tenant restart distributed message.

**Yes, maybe a good compromise**.

- In a theme `IResourceManifestProvider` check if it is the current theme or a base theme of the current one, if so build the resources, otherwise do nothing.

- When we change the current theme, restart the tenant as we do when we enable / disable a theme, so that a theme `BuildManifests()` will be re-called and will do the same check.

- Change `ResourceDefinition.DefineResource()` to allow a resource to be overridden, this to allow a theme to override the resources of its base theme..

**Comment by jtkech** [comment]
Just for infos, in fact when there are multiple resources with the same name, the resource manager takes the one with the highest version, if multiple with the same version, as said it takes the 1st registered.

    // Use the highest version of all matches
    if (resource == null
        || (resourceDefinition.Version != null && new Version(resource.Version) < version))
    {
        resource = resourceDefinition;
    }

Note: If we change `< version` with `<= version` it would take the last one.

But that's okay about allowing a theme to override a resource of its base theme, knowing the above it can do it, it just has to provide an higher version !
