### ISSUE TITLE
Little concerns about the different localizers.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#5028]
As i remember what i saw while working on #4933, see also my test and comment in #4962.

- First `IViewLocalizer` just uses an inner `IHtmlLocalizer` that uses an inner `IStringLocalizer` but whose types are based on the executing view.

- The main point is that when using the `@` razor directive on an `IViewLocalizer` that returns an `LocalizedHtmlString : IHtmlContent`, the called `WriteTo()` doesn't encode the base string, only the passed arguments are resolved and then encoded. This allows to use `@T["<h3>Text with an {0} arg</h3>", arg]` where only the passed argument will be encoded when rendering. Notice that here the translated base string would need to be already encoded if needed (but not the tags).

- To encode the whole when rendering, as maybe we thought that it was intended to do, we would have better to use an `IStringLocalizer` that return a `LocalizedString` whose `.Value` and implicit `.ToString()` return the actual string that is translated and formatted. Then, when using on it the `@` directive, the whole string will be encoded. Here the problem is to get the right `IStringLocalizer<RightType>`, see below.

    Notice that for a `LocalizedHtmlString`, `.Value` is the resource string but not formatted yet. And `.ToString()` just returns the full name of its type.

- **So, when using `@` on an `LocalizedHtmlString` returned by an `IViewLocalizer`, if there is no arguments nothing will be encoded. So we could use its `.Value` that is a `String` and that will be encoded, but if there are arguments there would not be resolved**.

    @sebastienros in the last meeting i saw that you used `HtmlEncoder.Encode(T["expand"].Value)`. So same comment but here it seems that you init a string that contains an html tag, so i assume that you then use e.g `Html.Raw(theString)`, that would be why you need to encode it. So here the only problem would be that an argument would not be resolved, but here there are no arguments.

- Finally, as said above, if we just want to encode the whole translated string with or without args, we would have better to use an `IStringLocalizer<RightType>`. We can do this indirectly by using the `IViewLoalizer.GetString(...)` that returns the inner `IStringLocalizer[...]` that is a `LocalizedString` whose `.Value` and implicit `.ToString()` return a tranlated and formatted string that will be encoded.

    Maybe an helper component to use the inner `IStringLocalizer` of the `IViewLocalizer` so that we could still use `[...]` in place of having to use `GetString(...)`.

    Notice that **this is what the liquid localizer filter `t` does => `localizer.GetString(...)`**. And this is what we should do, both in liquid and razor, if it is not for rendering but e.g just to init a shape string property e.g the `Format` of a `DateTime` shape, otherwise the `LocalizedHtmlString.ToString()` will just provide the full name of its type and its `.Value` a translated string but not yet formatted.

     And if we still want to use in some places the `IViewLocalizer[...]` directly as it works, we can do it for razor but for liquid we would need a 2nd localizer filter.

Sorry for the long story and some redundant things, i would need more time ;)

**Comment by Skrypt** [comment]
related? https://github.com/OrchardCMS/OrchardCore/pull/4750#issuecomment-565519632

**Comment by jtkech** [comment]
#4750 is not related to localizer functionalities but how we declare the class fields / properties of a given localizer type, e.g a property or a private field, but without changing the localizer type.

**Comment by jtkech** [comment]
Will see if we will have reported issues

**Comment by hishamco** [comment]
Why it's closed? I'm still testing few cases
