### ISSUE TITLE
Localized templates

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#5033]
Besides the option to use [localized strings in a template](https://github.com/OrchardCMS/OrchardCore/issues/4871) (if they are already defined), is there any other way to define localized templates?

Do we need to create our own localization [*.po files ](https://docs.orchardcore.net/en/dev/docs/reference/modules/Localize/#po-files-locations)in order to use any kind of localization in a template? No other (simpler) way around? Thanks.

**Comment by hishamco** [comment]
> is there any other way to define localized templates?

Do you mean in Liquid? Or general?

> Do we need to create our own localization *.po files in order to use any kind of localization in a template?

You 're free to create your own *.po files

> No other (simpler) way around?

Could you please elaborate or let us know your scenario so we can help

**Comment by sebastienros** [comment]
Technically it's doable, based on alternates. The solution would be to build custom alternates strings for each supported culture. This way you could do something like `Layout-culture-en` or `Content-Page-culture-en`.

You can try with a `IShapeTableProvider` implementation like in `MenuShapes.cs` for instance.

**Comment by jagbarcelo** [comment]
Thanks, but since that requires some programming too, I think the logical step would be going for creating .po files (instead of twisting the framework into doing something).

Now I have created my own Theme project (using the steps provided in [Getting started with an Orchard Core Theme](https://orchardcore.readthedocs.io/en/dev/docs/getting-started/theme/) ) and created a quite simple file at /Localization/es/myTheme.po (at the root of the theme project).

> #. Description = T["A simple sentence"];
msgctxt "myTheme"
msgid "A simple sentence"
msgstr "Una frase sencilla"


 I have also followed the steps for [Publishing Localization Files](https://docs.orchardcore.net/en/dev/docs/reference/modules/Localize/#publishing-localization-files) and did:
><ItemGroup>
    <Content Include="Localization\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


However, I have also a Template (using liquid syntax) with (among other things):

> {{ "A simple sentence" | t }}

… but it is not translated in pages where the language is Spanish. The original (english text) is always shown. Am I missing something? Are there more detailed steps for creating a Theme with localization support?

**Comment by jptissot** [comment]
I think your msgctxt is not correct. 
Use https://github.com/lukaskabrt/PoExtractor to extract the po files

**Comment by jptissot** [comment]
https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Localize/#extract-translations-to-po-files

**Comment by jagbarcelo** [comment]
It seems I go from one problem to another. When I run in myTheme project it throws this exception:

```
extractpo-oc G:\Documentos\GitLab\mySolution\myTheme G:\Documentos\TEMP --liquid
extractpo-oc : Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Fluid.Values.FluidValue> Fluid.Ast.Expression.EvaluateAsync(Fluid.TemplateContext)'.
En línea: 1 Carácter: 1
+ extractpo-oc G:\Documentos\GitLab\mySolution\myTheme G:\Docume ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...plateContext)'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at PoExtractor.Liquid.LiquidStringExtractor.TryExtract(LiquidExpressionContext expressionContext, LocalizableStringOccurence& result)
   at PoExtractor.Liquid.ExtractingLiquidWalker.ProcessFilterExpression(FilterExpression filter) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 110
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Expression expression) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 96
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Statement node)
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Statement node) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 69
   at PoExtractor.Liquid.LiquidProjectProcessor.Process(String path, String basePath, LocalizableStringCollection strings) in D:\a\1\s\PoExtractor.Liquid\LiquidProjectProcessor.cs:line 38
   at PoExtractor.OrchardCore.Program.Main(String[] args) in D:\a\1\s\PoExtractor.OrchardCore\Program.cs:line 52
```

**Comment by jptissot** [comment]
You should be able to manually set the msgctxt 

Here is an example from my project:

```
#: BootstrapTheme\Views\Widget-AccountWidget.liquid:0
msgctxt "BootstrapTheme.Views.Widget-AccountWidget"
msgid "Your email"
msgstr "Votre email"
```

**Comment by jptissot** [comment]
When running the command, I point to the root of the solution and not the theme directly.

**Comment by jagbarcelo** [comment]
When I point to the root of the solution the rest of projects (most of them have nothing to do with OrchardCore nor Themes) are parsed fine. When it reaches the Theme project, the same exception is shown:
```
PS C:\> extractpo-oc G:\Documentos\GitLab\mySolution G:\Documentos\TEMP --liquid
myLibrary.CalcClient: Found 0 strings.
myLibrary.CalcServer: Found 0 strings.
myLibrary.Model: Found 0 strings.
myLibrary.Resources: Found 0 strings.
myLibrary.ViewModel: Found 0 strings.
myLibrary.WebServices: Found 0 strings.
myLibrary.xUnitTest: Found 0 strings.
extractpo-oc : Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Fluid.Values.FluidValue> Fluid.Ast.Expression.EvaluateAsync(Fluid.TemplateContext)'.
En línea: 1 Carácter: 1
+ extractpo-oc G:\Documentos\GitLab\MySolution G:\Documentos\TEM ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...plateContext)'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at PoExtractor.Liquid.LiquidStringExtractor.TryExtract(LiquidExpressionContext expressionContext, LocalizableStringOccurence& result)
   at PoExtractor.Liquid.ExtractingLiquidWalker.ProcessFilterExpression(FilterExpression filter) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 110
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Expression expression) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 96
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Statement node)
   at PoExtractor.Liquid.ExtractingLiquidWalker.Visit(Statement node) in D:\a\1\s\PoExtractor.Liquid\ExtractingLiquidWalker.cs:line 69
   at PoExtractor.Liquid.LiquidProjectProcessor.Process(String path, String basePath, LocalizableStringCollection strings) in D:\a\1\s\PoExtractor.Liquid\LiquidProjectProcessor.cs:line 38
   at PoExtractor.OrchardCore.Program.Main(String[] args) in D:\a\1\s\PoExtractor.OrchardCore\Program.cs:line 52
```

**Comment by hishamco** [comment]
@jagbarcelo please post your previous exception into PoExtractor repo, for now you can follow what @jptissot is suggested

**Comment by jptissot** [comment]
@jagbarcelo do you have     <PackageReference Include="OrchardCore.Theme.Targets" Version="1.0.0-rc1-*" /> in your theme .csproj ?

**Comment by jagbarcelo** [comment]
After some bumps in the road, I finally managed to run `extractpo-oc` successfully. It generated a file, like this one:
>#: myTheme\Recipes\Snippets\releasenotes.liquid:0
msgctxt "myTheme.Recipes.Snippets.releasenotes"
msgid "A simple sentence from myTheme project"
msgstr ""

... that I used that as a template to create a file called `myTheme.po` in`/Localization/es/` right under `myTheme `project:
>#: myTheme\Recipes\Snippets\releasenotes.liquid:0
msgctxt "myTheme.Recipes.Snippets.releasenotes"
msgid "A simple sentence from myTheme project"
msgstr "Una frase sencilla del tema myTheme"

Nonetheless, the translation is not shown in Spanish "Release notes" pages, where the following liquid snippet is used:
> {{ "A simple sentence from myTheme project" | t }}

Any ideas?

**Comment by jptissot** [comment]
Is the html lang attribute set to es?

**Comment by jptissot** [comment]
Would need to test but maybe we expect projects to use PascalCase ?

**Comment by sebastienros** [comment]
We should implement the culture alternates feature. However, there is a simpler solution.

In the main template, like `Content-Page.cshtml`, just use shape morphing, by rendering a different shape with alternate of the current culture:

```
@{
  var shape = await New.CultureContentPage();
  shape.Metadata.Aternates.Add("CultureContentPage__" + Orchard.CultureName);
}

@await DisplayAsync(shape)
```

This way you create a `CultureContentPage.cshtml` file for the default language, and `CultureContentPage-en` specifically for English.

Same works with Liquid.

**Comment by jagbarcelo** [comment]
> Is the html lang attribute set to es?

Yes. It is set to `<html lang="es-ES">` via `Views/Layout.liquid` file in the theme project, containing the line `<html lang="{{ Culture.Name }}">`. This piece is confirmed to be working.

**Comment by jagbarcelo** [comment]
> Would need to test but maybe we expect projects to use PascalCase ?

I've just tried to use PascalCase both in the .liquid files names and in the .po file msgctxt tags with no luck either. I even tried to apply a different theme and back to myTheme again and, as last resource, tried to run the theme recipe too. No luck either way.

**Comment by jagbarcelo** [comment]
@sebastienros I've been trying your option too but I'm quite new in Liquid scripting and I do not know how to convert the Razor piece of code you gave into Liquid syntax. I've started with a simple:

```
{% assign shape = await New.CultureContentPage() %}
{% shape.Metadata.Aternates.Add("Summary__ReleaseNotes_" + Orchard.CultureName) %}
{% await DisplayAsync(shape) %}
```
But all I get are syntax error messages. I've tried with several minor variations without any luck.

**Comment by jtkech** [comment]
Just on the fly before going to sleep ;)

`myTheme\Recipes\Snippets\releasenotes.liquid:0` seems to be related to a snippet that is only used during a recipe execution, so maybe a message context problem when the message is actually rendered but in another context. For testing, try to remove the `msgctxt` line.

**Comment by jagbarcelo** [comment]
@jtkech No difference at all without using the `msgctxt` line. Thanks for getting involved.

**Comment by jtkech** [comment]
Okay, as i have time i will try it but so many things to do ;)

Are your template coming from a liquid file or from the database if defined through the UI with the templates feature?

**Comment by jtkech** [comment]
So, just did some tests that are working.

For this 1st location, they come from the referenced localization packages, so if you update it it will be grabbed again from the related package on each build, e.g

    appRoot\Localization\fr\*.po

But there are multiple places where you can add custom po files, e.g

    appRoot\Localization\fr-FR.po
    appRoot\Localization\ModuleOrTheme\fr-FR.po
    appRoot\Localization\ModuleOrTheme-fr-FR.po
    appRoot\App_Data\Sites\Tenant1\Localization\fr-FR.po

If you update one of these files you just have to restart the tenant from the UI, or restart the app.

Note: i may have did some typos ;)
Note: Maybe `ModuleOrTheme` can also be the app name because the app is a module.

Finally as you tried, custom po files can be under a module or theme but in that case the path is e.g

    ModuleOrTheme\Localization\fr-FR.po

These files are embedded in the module / theme assembly, so if you update it you have to rebuild the module / theme.

---

So in `TheBlogTheme` in the `Content-Article.liquid` i added these lines (as for a blog post)

    {% assign dateTime = "DateTime" | shape_new: utc: Model.ContentItem.CreatedUtc, format: format | shape_stringify %}
    {{ "Posted by" | t }} <a href="#">{{ Model.ContentItem.Owner }}</a> {{ "on {0}" | t: dateTime | raw }}

First it was not working, then in `appRoot\Localization\fr\TheBlogTheme.po` i added

    #: TheBlogTheme\Views\Content-Article.liquid:0
    msgctxt "TheBlogTheme.Views.Content-Article"
    msgid "Posted by"
    msgstr "Posté par123456"

    #: TheBlogTheme\Views\Content-Article.liquid:0
    msgctxt "TheBlogTheme.Views.Content-Article"
    msgid "on {0}"
    msgstr "le {0}"

And it was working. Then i did the same but by putting the above in a new `TheBlogTheme\Localization\fr-FR.po` file and it was also working.

Hope this will help.

**Comment by jagbarcelo** [comment]
Thanks @jtkech . Finally, it was the location of my .po file that was wrong. I had it under /myTheme/Localization/es-ES/myTheme.po and it should have been under /myTheme/Localization/es-ES.po (as you pointed out).

Maybe there should be a sample Theme with some (minor) Localization so that anyone that needs to make its own theme could pick as sample and know where and how to put their .po files without too much playing around.

Again, thansk a lot.
