### ISSUE TITLE
Make AliasPart form controls hide like TitlePart

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#5036]
![image](https://user-images.githubusercontent.com/16968103/70844784-d2d45780-1e80-11ea-945a-d12e6ca34319.png)

You can use Liquid, so it's as good as TitlePart.

**Comment by deanmarcussen** [comment]
Can you provide a bit more information on what you're asking for?

**Comment by chinasqzl** [comment]
For example, for the project number, I use liquid to generate P-2019-0001 as an alias, 0001 self-increasing，which does not need to be entered.

**Comment by Skrypt** [comment]
@chinasqzl But this is the TitlePart configuration page. So I updated the title of your issue to match your request.
