### ISSUE TITLE
 Content Picker Field Doesn't fill content

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5038]
i have Players — Content Picker Field in my content type. it was working, but it doesn't show data now .

![content field](https://user-images.githubusercontent.com/24512878/70847546-ddcdbe80-1e65-11ea-95aa-f5288ab755d4.JPG)

it has a javascript error. please check this.

**Comment by dodyg** [comment]
what version are you using?

**Comment by aghili371** [comment]
> what version are you using?

The last versions have this issue. i'm using this version:1.0.0-rc1-11061
but i tested with some older version, it has an error on those versions too.

**Comment by Skrypt** [comment]
Please update your code to reflect recent changes in your views. I tested with the latest dev branch by using the default editor and the Lucene editor for a content picker field and it works.
