### ISSUE TITLE
Feature Proposal: Replace "Main Menu" in admin menu to "Menus"

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/OrchardCore#5042]
1. "Menus" content type to be creatable by default
2. Optional(?) feature to set a menu as default (should it be per locale?)

**Comment by deanmarcussen** [comment]
This one has popped up a few times and we've never been able to agree on making it creatable by default.

Last time it cropped on on another issue, the best suggestion from @sebastienros was to make a `Navigation` menu entry that would list all menus in the system, and allow creating a new one.
But leaving the `Menu` content type not creatable, so it wouldn't show up in the standard contents `new` listing.

I'll see about a pr for that (hopefully)

For info @urbanit the `Main Menu` entry is actually a custom `AdminMenu` entry added by the theme recipes, just to give easy quick access to that one particular `Main Menu` entry item.

**Comment by Skrypt** [comment]
The reason why it's not creatable is because we make it so in our recipes but you could easily change that in your owns.

**Comment by urbanit** [comment]
@Skrypt it was made clear.. The proposal is about having a more user-friendly approach.

**Comment by deanmarcussen** [comment]
@urbanit have a look at the associated pr, and see if it works for you

**Comment by urbanit** [comment]
Looks perfect to me :-)
