### ISSUE TITLE
Add liquid ConsoleLog and document

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5045]
Follow on from https://github.com/OrchardCMS/OrchardCore/pull/4495 to remind me.

Need to add a `ConsoleLog` liquid filter, and doc the existing Razor `ConsoleLog` helper

**Comment by agriffard** [comment]
Feedback from meeting:
Replace StringBuilder, StringWriter by other Html builder
Inject HtmlEncoder
