### ISSUE TITLE
The layout is resolved before  Controller Item.Display(contentitemId)  is executed

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#5052]
A recent change in a filter from this pull request 
https://github.com/OrchardCMS/OrchardCore/pull/4804
calls the  layoutAccessor.GetLayoutAsync() before the action is executed. 
I had some code in the action that set some properties to  _httpContextAccessor.HttpContext.Items dictionairy in order to use this in a custom theme selector to set the current theme.
before this change it worked because previously  the filter was executed in in the   OnResultExecution event.
So I am puzzled how to handle this. 
Should I create my own action filter to do what i want or do you think there is a better way?

**Comment by jtkech** [comment]
Yes sorry, there are things that we needed to initialize earlier to provide more contextual data for some Liquid evaluations that may happen through drivers before the action is executed.

So the `RazorViewFeature` holding the `ThemeLayout` is set earlier, for infos it is a regular httpcontext feature that you can change afterwards. But if you don't want to force the layout and still pass through your theme selector, maybe an action filter that would have to run before, or maybe just put the logic in your theme selector using an `IHttpContextAccessor` and or an `IActionContextAccessor` ...

For sure there will be a solution but i would need more infos on your logic so that i could help you.

**Comment by giannik** [comment]
Thanks jtkech.
To give more context i was setting the contentitem in a global variable as shown below :

//set to a global variable"
_httpContextAccessor.HttpContext.Items["CurrentContentItem"] =contentItem;

then in my custom theme selector i would inspect the contenttype property of the content item and set the theme accordingly.
This way i did not have to issue another query to get the contenttype of the current content item.
So my guessing it that now I should change my theme selector to issue a select query that would return the contenttype based on the contentitemid.

Or do think there is a better way?
Thanks 
Giannis

**Comment by deanmarcussen** [comment]
If you are using the `DefaultContentManager` and calling `.GetAsync(xxx)` then the `DefaultContentManagerSession` https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManagerSession.cs will actually cache these requests, per http request.

So calling it multiple times during a request won't actually make multiple database calls, it'll return from the session cache.

Does that provide an easier way to not create N+1 calls for you?

**Comment by giannik** [comment]
So if I use in my theme selector : 
       var contentItem = _contentManager.GetAsync(xxxxx);

Then when the call to controller  :
        ItemController.Display(xxxxx);

is made it will use the contentItem already available from the cache?

That would be cool, because I did'nt want to load the whole document  with the json dataobject to avoid the overhead.
I was thinking of using the 
     _session.QueryIndex<ContentItemIndex>

for better performance , 
But with what you say I should just using the _ContentManager.GetAsync() and no extra database overhead will occur ?
Thanks Dean.

**Comment by deanmarcussen** [comment]
Yeah that should be it.

You can confirm by using the mini profiler module (it'll tell you how many sql calls are being made)

using `_session.QueryIndex` won't be cached as far as I know, but `_contentManager.GetAsync(x)` should be.

And probably the content item id is available from the `RouteValues` of the `HttpRequest` - but I imagine you already know this ;)

**Comment by giannik** [comment]
Yeah, RouteValues is the only way I know to grab the contentItemId,
Will try it out.
Thanks again, mate.

**Comment by giannik** [comment]
worked like a charm.
Also confirmed that the query is run only once using  _contentManager.GetAsync().
Thanks @jtkech @deanmarcussen .
