### ISSUE TITLE
question: how can access to log information?

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5053]
OC has a log mechanism to save user activity?

if it has, how i can access that?

where i can find an example to use that for my modules?

**Comment by hishamco** [comment]
OC supports NLog & SeriLog, but you implement your own, so the logged information depends on the active logger provider

**Comment by Skrypt** [comment]
There is no events logged for user activity yet. This is an "Audit Trail" module that should be migrated from 01 which will take some time investment to complete.

**Comment by hishamco** [comment]
Aha if you mean user activity as @Skrypt said no module to provide such thing

**Comment by aghili371** [comment]
@hishamco i'm using serilog but i need that user activity log to have more security in the project.

@Skrypt  that will be useful if we have that.

**Comment by hishamco** [comment]
You can implement your own Audit module, or tr to migrate the one from Orchard 1

**Comment by aghili371** [comment]
> You can implement your own Audit module, or tr to migrate the one from Orchard 1

i try to have look in "Audit Trail "
