### ISSUE TITLE
[Feature] User Impersonation

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5055]
Usually during development, and sometimes in production, it is useful to quickly login as another user.

This feature for admins only

**Comment by pgy866** [comment]
Used for developer self-check permission settings, great
用于开发者自我检查权限设置，非常棒

**Comment by agriffard** [comment]
See https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules and
https://orcharddojo.net/blog/user-impersonation-export-content-to-deployment-target-this-week-in-orchard-07-08-2020

**Comment by hishamco** [comment]
@pgy866 if you have any comments or suggestion about User Impersonation module, please file an issue with the repo that @agriffard refers to

Thanks
