### ISSUE TITLE
Want to package and link some online style resources and source code locally

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#5058]
I hope that some online style resources and source code are packaged and linked to the local together, and a setting entry is added to quickly set whether to use the latest online style resources, such as some JS. CSS

Some online resources in some areas cannot be linked, which will cause you to experience a bad feeling right after you start using it

希望把在线的一些样式资源和源码一起打包链接到本地，增加一个设置入口，可以直接快速设置是否使用最新的在线样式资源，如果某些JS 。CSS

部分地区某些在线资源无法链接，会造成刚开始使用就体验不美好的感觉

![截图_选择区域_20191216175805](https://user-images.githubusercontent.com/28694676/70897748-35b72180-202e-11ea-9ef8-aa58b60e2ff1.png)

https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/i18n/jquery-ui-i18n.min.js

**Comment by deanmarcussen** [comment]
if you are using the `Use Framework CDN` setting in `Configuration -> Settings` the https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/i18n/jquery-ui-i18n.min.js loads fine for me on the latest dev branch.

Have you set some specific CORS rules up which would be affecting that?

And which version are you using?

**Comment by pgy866** [comment]
OrchardCore.Application.Cms.Targets 1.0.0-rc1-11111
All are the default settings. However, I think that the JS and CSS resources used in the background are packaged locally, and the relevant CDN is set by default. This will provide a better experience when there is a network obstacle, otherwise the network obstacle will cause resource loading problems and the entire system will be paralyzed.

全部是默认设置。但是我认为把后台使用的资源JS，CSS打包本地，默认设置相关CDN在本地，这样有网络障碍时会更好的体验，否则网络障碍导致资源加载问题，整个系统瘫痪

**Comment by deanmarcussen** [comment]
ok, my guess here is that we're running into the China firewall, because it works fine for me.

I can't test behind the firewall so can you do a couple of things.

go to https://www.srihash.org/ and put the https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/i18n/jquery-ui-i18n.min.js url in

and verify that the hash matches the hash we use below.

`sha384-0rV7y4NH7acVmq+7Y9GM6evymvReojk9li+7BYb/ug61uqPSsXJ4uIScVY+N9qtd`

Also verify that you can download the js file directly without a hash from your browser.

I know we've had problems with these cdn's in the past, so maybe we need to use a different cdn for this resource.

**Comment by sebastienros** [comment]
WE usually try to use a cdn that is compliant with the Chinese firewall. Didn't we do it for jquery too?

**Comment by deanmarcussen** [comment]
yes, for jquery we used code.jquery.com as the cdn.

but for the ui-i18n someone used a different cdn.

I've found it on code.jquery.com so I'll PR that.

If that doesn't resolve it, the other issue that may be causing it is https://github.com/OrchardCMS/OrchardCore/issues/3901 which might be browser specific in this case, as the encoded hash works for me on chrome windows / mac

**Comment by sebastienros** [comment]
Are we actually using the file then? We found this class in OC : https://github.com/OrchardCMS/Orchard/blob/5b5eda6ae36dc2d7906599882165ef1e985cdc8c/src/Orchard.Web/Modules/Orchard.Localization/Providers/LocalizationDateTimeFormatProvider.cs that is used to be able to provide date and time localization using po files. Then it's easy to create custom js files if necessary that are compatible with out way to localize stuff.
