### ISSUE TITLE
Versions History

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#506]
If a content is versionable, it would be interesting to display a list of the versions and allow to switch between each of them and see the changes made and compare between two version.

**Comment by Jetski5822** [comment]
I was thinking about this.... you could go back in history and then start from there again, but instead of replacing the other versions, you just branch off again. Similar to git version history.

**Comment by Jetski5822** [comment]
^^^ This way a user could compare two outcomes

**Comment by agriffard** [comment]
@jtkech : When the versionable stereotype is checked, would it be possible to have the history of a content in the admin?

**Comment by jtkech** [comment]
@agriffard yes i think it would not be so difficult, as i remember, as long as the items are in the db we can query them e.g based on a given `ContentItemId` then before a given `CreatedUtc` and so on ...

            var test = await _session
                .Query<ContentItem, ContentItemIndex>(x => x.ContentItemId == id &&
                    x.CreatedUtc < date && ...).Take(n).ListAsync();

This even if the content type is not versionable because it could have been versionable before.

**Comment by sebastienros** [comment]
Audit Trail module.

**Comment by sebastienros** [comment]
Or limit it to just listing all versions in a separate view for now.

**Comment by infofromca** [comment]
may we go a little further?
CRUD on different version according to different permission. something like **wiki**

**Comment by Skrypt** [comment]
Hubspot has a TimeLine API that has maybe some things we could get ideas from.
https://developers.hubspot.com/docs/methods/timeline/timeline-overview

**Comment by infofromca** [comment]
#1976

**Comment by Piedone** [comment]
This will be available with https://github.com/OrchardCMS/OrchardCore/issues/4620.
