### ISSUE TITLE
"Flow "  disappear in RTL culture

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5064]
if i have rtl admin, the flow doesn't usable.

LTR Culture
![1](https://user-images.githubusercontent.com/24512878/71018747-5ac49680-20f9-11ea-8ada-659a518627e8.JPG)

RTL Culture
![2](https://user-images.githubusercontent.com/24512878/71018784-6d3ed000-20f9-11ea-8f6c-cfea59010738.JPG)

**Comment by hishamco** [comment]
@ns8482e could please have a look while you are the one who has expert in Flow?

**Comment by ns8482e** [comment]
I can look into, However I don't know, How to change the culture for Admin UI?

**Comment by ns8482e** [comment]
Nevermind - I found it - will create PR soon.

**Comment by hishamco** [comment]
Thanks Nerag

**Comment by sebastienros** [comment]
Who is Nerag ;)

**Comment by hishamco** [comment]
I fix his name 😊, BTW Seb hope you checked my comment on his PR
