### ISSUE TITLE
ContentRequestCultureProvider issue

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5065]
I have seen cases where the cookie and Content Culture were off sync (cookie set to english but current page is french because of ContentRequestCultureProvider). This causes weird issues with the ContentCulturePicker and non content links.

For example: I am on a french page, cookie is set to english. When I click on a login link, the text will be in english.

To fix this, I had to add this line of javascript that will set the cookie based on the html lang attribute: 
```
document.cookie = '.AspNetCore.Culture=c%3D'+document.documentElement.lang+'%7Cuic%3D'+document.documentElement.lang +';path=/';
```

Any ideas on a better fix ?

**Comment by Skrypt** [comment]
That's what I was afraid of with this type of culture picker. But it does what it's allowed to do too. It changes the current page culture not the global culture.

**Comment by jptissot** [comment]
I am wondering if we should set the cookie in the ContentRequestCultureProvider itself ? That would solve the issue.

**Comment by Skrypt** [comment]
Make it a setting on that provider.

**Comment by hishamco** [comment]
I am not sure why this behavior is happening? If the current picker set the cookie I expect all the views read the current cultures,  because the layout is already set the `dir` and `lang` properties

**Comment by sebastienros** [comment]
The ContentRequestCultureProvider should remove the cookie

**Comment by jptissot** [comment]
> The ContentRequestCultureProvider should remove the cookie

But then, the next request would fallback to the browser culture ? I want it to stay the same as the current culture.

**Comment by OrchardSkills** [comment]
Any update on this issue?

**Comment by hishamco** [comment]
@OrchardSkills It's in backlog, but I will try to have a look if I have a time

**Comment by juergen-de** [comment]
Is that the reason you do not keep the selected language when you switch to another culture and the keep browsing the site?
An why should the cookie be removed?

**Comment by jptissot** [comment]
@sebastienros what do you think of this fix: https://github.com/StatCan/StatCan.OrchardCore/pull/275/files#diff-ea23d41128a4ede6b035dc02f936c24356764ae36150bd0fa1a49b96819e426cR37

Here is the scenario that this fixes: 

1. User has the cookie set to English from a previous visit to the site.
2. User goes to directly to a french page on his next visit, the page displays in french. On the page there is a client side form that does an ajax call to a controller / workflow. The user submits a form that has a mistake and a server side validation error occurs. The error is displayed in english since the cookie is english.
