### ISSUE TITLE
Bug maybe: Footer Layer

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5066]
I keep running the Agency Recipe over and over again and each time I do I seem to get a new footer layer added.
I now have over 20 footers when you click on layers in configuration.
Also my website has 20 footers on the bottom of it lol

**Comment by hishamco** [comment]
I will try to reproduce the issue

**Comment by hishamco** [comment]
I'm able to reproduce the bug, I will try to fix it

**Comment by hishamco** [comment]
A simple fix for this by setting a uuid for html widget`contentItemVersionId` property in the agency recipe, you will find something similar in coming soon recipe

@Skrypt is this an acceptable fix to send a PR or is there a better way to fix

**Comment by deanmarcussen** [comment]
Seems strange to be running a setup recipe over and over again.

it is a setup recipe, intended to be run once during setup.

would have thought you'd end up with lots of multiples if you run it repeatedly.
menus, content items etc al.

**Comment by jptissot** [comment]
See https://github.com/OrchardCMS/OrchardCore/issues/1970

**Comment by JoshTango** [comment]
I am in vs2019 creating my own recipe.
I started with the Agency recipe.
I re-run it over and over as I make changes to it.

**Comment by jptissot** [comment]
@JoshTango I personally use multi tenancy to help build setup recipes. Setup a site with the SaaS recipe and then create a new tenant each time to test your recipe

**Comment by hishamco** [comment]
@jptissot create a tenant each time is doable but tedious

> Seems strange to be running a setup recipe over and over again.

@JoshTango as @deanmarcussen said before this is a setup recipe (not best practice to run them over and over again) but nothing stop use from run them while its there in the admin site, for that I will close that because the issues already mentioned in #1970

**Comment by JoshTango** [comment]
meaning you wont fix the bug?

**Comment by hishamco** [comment]
I told you with the simple fix in my earlier comment, but this issue is duplicate and already known, hope you understand why I closed this one

**Comment by sebastienros** [comment]
@JoshTango have you tried to set a `contentItemVersionId` on the layer like it was suggested? Or on the widget, whichever is created multiple times.

**Comment by JoshTango** [comment]
I am not concerned for myself.
I just wanted to make sure you guys have a plan to eventually solve this.

**Comment by sebastienros** [comment]
Right, I don't see this as a bug, just to be aware how to build idempotent recipes. The other issue tracks that.
