### ISSUE TITLE
ArgumentException: The path must be absolute. (Parameter 'root')

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5072]
I get an exception when I add a module in a Library project containing razor pages to a OC site hosted with docker compose in docker desktop. When I run the site in iisexpress it all works fine.

The stacktrace and repo are attached.

[ModuleException.zip](https://github.com/OrchardCMS/OrchardCore/files/3979065/ModuleException.zip)
[stacktrace.txt](https://github.com/OrchardCMS/OrchardCore/files/3979066/stacktrace.txt)

**Comment by ArieGato** [comment]
Here's the code from the ModuleProjectRazorFileProvider.

`var root = asset.ProjectAssetPath.Substring(0, asset.ProjectAssetPath.Length - filePath.Length);

// Get the first module project asset which is under a "Pages" folder.
var page = assets.FirstOrDefault(a => a.ProjectAssetPath.Contains("/Pages/"));

// Check if the module project may have a razor page.
if (page != null)
{
    // Razor pages are not watched in the same way as other razor views.
    // We need a physical file provider on the "{ModuleProjectDirectory}".
    _pageFileProviders.Add(new PhysicalFileProvider(root));
}`

I did some further investigating and root is an absolute Windows path.  e.g. c:\repos\... The container is running as a linux container. The PhysicalFileProvider is throwing the exception.

**Comment by jtkech** [comment]
The `ModuleProjectRazorFileProvider` is only used when `_hostingEnvironment.IsDevelopment()`, this means that in your hosted environment the `ASPNETCORE_ENVIRONMENT` variable coming from environment variables (or from any other config source) is still configured to `Development`.

**Comment by ArieGato** [comment]
But I am developing. What should it be set to then?

**Comment by jtkech** [comment]
Yes, the dev mode is used to take into account asset file changes at runtime, project asset paths are generated on building, so you can run in dev mode only in the env in which the app has been built.

Hmm, but for pages we could add a `Directory.Exists()` check, as we do afterwards for razor views.

**Comment by ArieGato** [comment]
Changing the environment setting causes another issue during development.

System.InvalidOperationException: 'Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

**Comment by jtkech** [comment]
Ah okay, in your hosted env can you install dotnet and run tools as `dotnet dev-certs https --trust` ?

Hmm, anyway maybe better to always allow to run in dev mode. I will do a PR to fix the `new PhysicalFileProvider(root)` issue, maybe we miss something else but will see.
