### ISSUE TITLE
Developing with MSSQL LocalDB

### ISSUE THREAD

**Issue by aaroncalderon** [OrchardCMS/OrchardCore#5076]
Is there support to develop with a MSSQL LocalDB?

**Comment by hishamco** [comment]
Why not?!! Orchard Core uses YesSQL under the hood which supports SQLite, SQL Server, MySQL and Postgres

**Comment by hishamco** [comment]
Just use Choose SQL Server during the setup process then enter your `ConnectionString` and ready to go
