### ISSUE TITLE
How to load OrchardCore modules dynamically ?

### ISSUE THREAD

**Issue by oromand** [OrchardCMS/OrchardCore#5082]
Hello guys, I got amazed by the video showcasing the OrchardCore integration on Visual studio channel.
I gave it a try and it works great. 
I'm wondering how I can dynamically load another OrchardCore module dll dynamically; without adding a referenced project in my IDE. My use case would be to dynamically enrich my main solution with a set of plugins if there're present.
My first guess was to look at  
> Assembly.Load

, with no success.
Would you guys be kind to point to the right direction ? What is this black magic happening behind the scenes when a module is referenced ?
Thanks for your answer.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/451

**Comment by awyl** [comment]
Not sure if this is what you are looking for.  I have created a docker image with stock orchard core nugets and load my dlls in a separate folder.  It works fine my use cases.

Note that your modules have to be built with the same version as the image.

[awyl/Docker-OrchardCore](https://github.com/awyl/Docker-OrchardCore)

**Comment by sebastienros** [comment]
We don't support dynamically loaded modules. Because some components like MVC require some build step information (precompiled views, custom references). We tried and failed. It might be doable with newer dotnet versions but it's too much work to maintain while providing few benefits.

**Comment by oromand** [comment]
Thanks for these answers guys. 
I wasn't aware of such limitations. I would look at the opportunities pointed;
