### ISSUE TITLE
Feature request: CodeMirror editor for TextField

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5087]
Implement a TextField editor (with settings) for CodeMirror

**Comment by deanmarcussen** [comment]
agreed we should also use CodeMirror for the HtmlField (when not wysiwyg) and the HtmlBodyPart for the same

**Comment by agriffard** [comment]
Do we also need a TextField editor with CodeMirror?

**Comment by sebastienros** [comment]
@agriffard yes
