### ISSUE TITLE
Setting prop-* for shape tag helper throws an error

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5090]
While experimenting with shape tag helper for #4955, I am trying to set kind property to have value "form", when I used prop-* as below, 

`<shape Type="SubLayout" prop-kind="form"> `

throws an error, Am I using it incorrectly?

```
The name 'form' does not exist in the current context
+ <shape type="SubLayout" prop-kind="form" >

```

**Comment by hishamco** [comment]
Could you please show us the tag helper implementation or at least `prop-*` property?

**Comment by ns8482e** [comment]
It’s ootb ShapeTagHelper

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by hishamco** [comment]
I see you derived from `BaseShapeTagHelper`, could you show the exception details

**Comment by ns8482e** [comment]
Sorry for confusion, It's compiler error - It won't let me use `prop-kind="form"` throwing error `The name 'form' does not exist in the current context`

**Comment by hishamco** [comment]
Let me create a new TagHelper and check if I got the same error

**Comment by ns8482e** [comment]
> new TagHelper

BTW, I have not created new TagHelper, I am trying to use OOTB [ShapeTagHelper](https://github.com/OrchardCMS/OrchardCore/blob/adce8a8db7e0605546f96f55f799345451efff69/src/OrchardCore/OrchardCore.DisplayManagement/TagHelpers/ShapeTagHelper.cs)

**Comment by hishamco** [comment]
It supposed to be work if it inherits from `BaseShapeTagHelper`

**Comment by hishamco** [comment]
I can confirm this behavior too, the reason why this happening because the property expect an `Object` instead of `String`

I will push a PR now to fix this

**Comment by ns8482e** [comment]
I guess then it should asp-prop-* to differentiate between asp object with attribute prop-*

**Comment by hishamco** [comment]
> I guess then it should asp-prop-*

I don't think so, it's not asp thing, may be `oc-prop` but I don't see any conflict yet

**Comment by giannik** [comment]
sebastien explains the usage of prop-* here 
https://www.youtube.com/watch?v=G5qPmYmLaGY&t=1392s

Just use <shape Type="SubLayout" kind="form">
to pass the property into shape as string.

**Comment by hishamco** [comment]
> <shape Type="SubLayout" kind="form">

This is confusing little bit for those who working with TagHelpers before, I'm not sure how this will be distinguish from normal properties, or perhaps it needs sort of documentation

/cc @sebastienros

**Comment by jtkech** [comment]
`<shape Type="SubLayout" prop-kind=@("form")>`

**Comment by hishamco** [comment]
> <shape Type="SubLayout" prop-kind=@("form")>

This syntax looks ugly little bit :) I like this one `<shape Type="SubLayout" prop-kind="form">` or `<shape Type="SubLayout" kind="form">`

**Comment by jtkech** [comment]
This is the regular mvc way with prefixed properties, or

                @{ 
                    var myString = "form";
                }

               <shape Type="SubLayout" prop-kind="@myString">

**Comment by hishamco** [comment]
Ya, right .. but I expect write the property value directly, this not valid because the dictionary requires `Object` not `String`

**Comment by jtkech** [comment]
yes ;)

**Comment by hishamco** [comment]
but still waiting for Seb, coz he doesn't like the change or he wanna explain something

**Comment by sebastienros** [comment]
About this issue, not the comments;
- you can use `prop-xyz` with a variable, to keep the type of the variable. in your case `form` should have been a variable.
- if you don't care about the type then use `xyz=` directly

**Comment by ns8482e** [comment]
> it's not asp thing

It's not about brand prefix, it's common understanding that if property starts with asp-* then it has something to do with some asp.net engine processing and not a regular html attribute

**Comment by ns8482e** [comment]
> * if you don't care about the type then use `xyz=` directly

It worked - Thank you.

**Comment by ns8482e** [comment]
@giannik Thank you for the video link

**Comment by ns8482e** [comment]
@sebastienros Also, It would be nice to define shape html within the shape tag, similar to `<zone>` tag, currently `<shape>` tag ignoring its content

**Comment by ns8482e** [comment]
HtmlAttributeName - HTML attribute name missing,  it is required to use with PR #5099 to access prop-* property from liquid.

**Comment by sebastienros** [comment]
What would be the value of a shape tag with inner content, compared to just `<span>with content</span>` as I assume such a section could not be overrided by another template.

**Comment by sebastienros** [comment]
@sfmskywalker  let me know that maybe what you want is just to be able to access the child content of a shape tag, and your own template would be able to use it. Is that it?

**Comment by ns8482e** [comment]
> What would be the value of a shape tag with inner content, compared to just `<span>with content</span>` as I assume such a section could not be overrided by another template.

I guess This discussion is related to #4955 not related to this issue

While researching based on your comments - https://github.com/OrchardCMS/OrchardCore/issues/4955#issuecomment-562727479 

First, I thought to make changes in "Contents" module, But then I thought to create a new module that adds new functionality for contents screen without modifying existing "Contents" module code.  However, realized I can't override MVC views #5128 in module.

It's just an idea, if i have shape type "SubLayout" but do not want to define core shape in any module as it varies by content of page - but defines specific alternate.

First try was `<zone>` tag that supports inline content, but it doesn't support alternate. So Now I am seeing `<shape>` tag it supports alternate but it doesn't support inline shape definition - but requires me to define "`SubLayout.cshtml`" shape in a module.

If I could define `Edit.cshtml` in `OrchardCore.Contents` as following with minimum changes without defining "`SubLayout.cshtml`"

```
<shape Type="SubLayout" prop-ChildContent="Model" FormAction="Edit">
    <metadata>
        <add-alternate name="@($"{controller}{action}__SubLayout")" />
        <add-alternate name="@($"{contentTypeDefinition.Name}__{controller}{action}__SubLayout")" />
    </metadata>

<form asp-action="Edit" asp-route-contentitemid="@contentItem.ContentItemId" asp-route-returnUrl="@Context.Request.Query["ReturnUrl"]" method="post" enctype="multipart/form-data">


    @Html.ValidationSummary()
    @await DisplayAsync(Model)
</form>



</shape>
```
  
I could simply create `AdminEdit__SubLayout ` or `Page__AdminEdit__SubLayout` using AdminTemplate.

**Comment by ns8482e** [comment]
> HtmlAttributeName - HTML attribute name missing, it is required to use with PR #5099 to access prop-* property from liquid.

For This issue - I'll add "Name" and create PR so that dictionary values can be accessed  using #5099
