### ISSUE TITLE
OrchardCore.Mvc.Web - Doesn't trigger the set up page

### ISSUE THREAD

**Issue by captmomo** [OrchardCMS/OrchardCore#5091]
https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Mvc.Web

Hi,
I'm currently exploring OrhardCore. I noticed that with the .AddMvc(), the set up page isn't trigged on start up. How do I do the set up for this sample?

**Comment by deanmarcussen** [comment]
If you're running of the dev branch you should use
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Cms.Web/Startup.cs

as your startup project.

The `OrchardCore.Mvc.Web` project is actually a framework module, that will get called as a module by the code in the `OrchardCore.Cms.Web/Startup.cs`

The framework module concept allowed us to use things like Nancy as a framework (when that still existed)

**Comment by hishamco** [comment]
`AddOrchardCms()` is adding the required services by OC, so as @deanmarcussen referred above you should use `OrchardCore.Cms.Web/Startup.cs` instead
