### ISSUE TITLE
Send email task issue

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5097]
Using liquid in the Send email task Subject field throws  NRE

**Comment by jptissot** [comment]
When we have multiple email tasks in a Workflow and 1 email task fails, no email is sent.

**Comment by jtkech** [comment]
As i have time i will try it but meanwhile can you show us your liquid part?

Because looking at `LiquidWorkflowExpressionEvaluator`, this is the only place where we don't do `context.SetValue("Model", model)` but `context.SetValue("Workflow", workflowContext)`.

**Comment by jtkech** [comment]
Just tried by injecting some liquid in the body and the subject and it was working.

That said i just used a simple liquid expression `Testing {{ 1 + 3 }}` but that has been resolved.

**Comment by jptissot** [comment]
I will try to make a repro.

**Comment by jptissot** [comment]
Unable to repro with a simple form and workflow. Must be something else going on.
