### ISSUE TITLE
Dynamic templates should use Handlebars

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#510]
Because it's the language for tokens, and it provides a sandboxed language.

**Comment by jtkech** [comment]
@sebastienros 

Some progress on this one, see below what i begin to be able to do with helpers.

If i cache compilations in a static dictionary, handlebars files changes are not taken into account. We would need a files watcher or e.g also cache the file date and then check if it has been updated.

If i cache compilations at the scope / request level it's ok, then compilation is done only once but on each request. **Question**: Do we need to implement handlebars files changes?

    <nav>
        <ul class="nav navbar-nav">
            {{#each Items}}
                {{{DisplayAsync ..}}}{{/DisplayAsync}}
            {{/each}}
        </ul>
    </nav>

    <h1>{{Title}}</h1>
    <h3>{{ContentItem.Author}}</h3>
    <h3>{{Metadata.DisplayType}}</h3>
    <h3>{{{Url "~/page1"}}}{{/Url}}</h3>

Best.

**Comment by sebastienros** [comment]
Apparently there is another syntax you might want to test:

{{{DisplayAsync shape=Items}}}

**Comment by jtkech** [comment]
Yes, i'm trying all possibilities. Named parameters was not working as expected but it was just because i was using spaces before and after the equal operator, now it's ok ...

But first, one question, do we need to implement handlebars files changes without restarting the app?

**Comment by sebastienros** [comment]
bonus, like for razor shapes

**Comment by sebastienros** [comment]
Don't do that for now, because we might need to make it optional for performance reasons. Tracking files is expensive.

**Comment by jtkech** [comment]
Ok. The other solution i'm using for testing is to only cache compilations at the request level. But at the end i will cache them in a static dictionary to prevent compilation on each request.

**Comment by agriffard** [comment]
Can be closed since Liquid has been implemented?
