### ISSUE TITLE
Bug Maybe: Content Rendering Order

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5109]
I made a content type with a bag first and a html body second.
The content rendered in this order.
I decided I wanted the order reversed.
So I went into the content definition editor and moved the html body above the bag and saved.
The content editor showed the html body first and the bag second which was good.
I republished.
The content view did not reflect the change.
The bag was still first and the html body second.

**Comment by deanmarcussen** [comment]
The orders in the admin are only used for admin editing (this is documented somewhere)

For ordering on the front end, you should use placement. https://orchardcore.readthedocs.io/en/dev/docs/reference/core/Placement/#placement-files

**Comment by ns8482e** [comment]
HtmlBodyPart
https://github.com/OrchardCMS/OrchardCore/blob/3e221778f8b670fb16d6ffb5565526913ccc0411/src/OrchardCore.Modules/OrchardCore.Html/Drivers/HtmlBodyPartDisplay.cs#L33

BagPart

https://github.com/OrchardCMS/OrchardCore/blob/3501367a6dc7dbfd2fef8de36ab2df5862e842ba/src/OrchardCore.Modules/OrchardCore.Flows/Drivers/BagPartDisplay.cs#L45

Default location of Both Part is "Content:5" hence there is tie, I guess that could be the reason BagPart comes first. 

As @deanmarcussen suggested using placement.json if you change order of HtmlBody to 4 then it will show HtmlBody before Bag.

**Comment by sebastienros** [comment]
If there is a tie, we might want to use the shape name after that, to have a constant result.

**Comment by Piedone** [comment]
You can use https://docs.orchardcore.net/en/latest/reference/core/Placement/ to affect the ordering.
