### ISSUE TITLE
Create article part and get article title list

### ISSUE THREAD

**Issue by OlziiNaran** [OrchardCMS/OrchardCore#5115]
I create a article content type and a new Page, want get article content title list and show in page, but not show in the page, why? 
![image](https://user-images.githubusercontent.com/39524174/71365810-10e91e00-25db-11ea-92f2-f033dd7177e1.png)
![image](https://user-images.githubusercontent.com/39524174/71365932-6b827a00-25db-11ea-89a3-a88687f4ac8a.png)

Model.ContentItem.Content.Article.ContentItems.size not return value

**Comment by OlziiNaran** [comment]
I am from China and cannot access youtube

**Comment by OlziiNaran** [comment]
It is best to recommend a graphic explanation

**Comment by OlziiNaran** [comment]
I'm used Agency theme

**Comment by dodyg** [comment]
You need to loop

``` 
   {% for article in Model.ContentItem.Content.Article.ContentItems %}
      {{ article.DisplayText }}
   {% endfor %}
```

**Comment by OlziiNaran** [comment]
@dodyg I'm didnt get article list
![image](https://user-images.githubusercontent.com/39524174/71388167-29385780-2632-11ea-86a7-d82a678a2de8.png)
![image](https://user-images.githubusercontent.com/39524174/71388180-36eddd00-2632-11ea-8a18-ccd38dd16177.png)

**Comment by OlziiNaran** [comment]
I'm didnt get article list

![Uploading image.png…]()

**Comment by OlziiNaran** [comment]
@dodyg I'm don't get article list.
![image](https://user-images.githubusercontent.com/39524174/71388478-7ff26100-2633-11ea-9b61-e7a097c0f28e.png)
![image](https://user-images.githubusercontent.com/39524174/71388599-fe4f0300-2633-11ea-9ae9-0ab102b3485f.png)

**Comment by Skrypt** [comment]
You can create a Lucene or SQL Query to get the List of Articles. Else, you can also use the ListPart to attach to a content type. Look at the Blog content type to see an example of that.

**Comment by OlziiNaran** [comment]
> You can create a Lucene or SQL Query to get the List of Articles. Else, you can also use the ListPart to attach to a content type. Look at the Blog content type to see an example of that.

Any explanation? Best video explanation
