### ISSUE TITLE
Creating content from a script task in a workflow does not fill the owner field

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5116]
![image](https://user-images.githubusercontent.com/4681586/71368094-f1b7a580-2574-11ea-915f-91051d7a9b1f.png)

```
createContentItem("SomeType", true, {...});
```

I think we need to look at what is done with the ContentAdminController and replicate the logic. 

Maybe related to https://github.com/OrchardCMS/OrchardCore/issues/3343

**Comment by deanmarcussen** [comment]
@jptissot see this pr https://github.com/OrchardCMS/OrchardCore/pull/5000, (and the other issues related issues I referenced) and maybe make some comments.

You're actually using this, so maybe know better what is needed ;)

**Comment by jptissot** [comment]
I am pretty sure I saw a similar issue when implementing cloning. The issue being that the ContentItem.Data property is updated but the part / field class properties are not. I believe @sebastienros mentionned that he implemented something to "flush" the values from data to the properties (ContentPart.Apply?). In this case, we would need a ContentItem.Apply() method that would iterate the parts and set the properties of all parts / fields of the type from the values present in the Data property. This is just a guess though. Would need to test it.

**Comment by mawendel** [comment]
I have a similar issue, where my bag items does not get any Content Item fields. It will simply add the fields from the json, but never realise that the bag items are content types too (it seems).

**Comment by Skrypt** [comment]
Ok will take a second look on that and will report if I find a proper solution.
