### ISSUE TITLE
Feature Request - Technical name on content definition

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5118]
I noticed when I edit a field part it shows me the technical name in a greyed out box.
I would like this technical name to be displayed below the content definition display name as well.
I think its required to since the display name could be changed at any time.

**Comment by Piedone** [comment]
Do you mean to change it like this?

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/1152d56c-9665-4904-a8b4-4bd6979436ca)

I think it's quite important that the display name can change: that's for humans, so the content type editor should also reflect that, what people interact with (as opposed to identifiers in the code, what the technical name is for, and what shouldn't change).

Can you explain the rationale behind this suggestion?
