### ISSUE TITLE
pattern edd sing s to render the display text of this content type. With support Liquid

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#5123]
I have a content type called "Product" that consists of a TitlePart and a SKU field,
TitlePart.Title = "Product1"
Sku = "sku1"
DisplayText = '[sku1] Product1'

pattern edd sing s to render the display text of this content type. With support Liquid!

**Comment by ns8482e** [comment]
TitlePart is used to assign display text to a content item, here's @sebastienros 's comment on similar issue. https://github.com/OrchardCMS/OrchardCore/issues/5006#issuecomment-564330493

You can create Two text fileds - ProductName and SKU and add TitlePart - you don't show the title part but provide liquid template to generate '[sku] [productname] combination for DisplayText
