### ISSUE TITLE
Uniform button shape names for Admin

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5126]
For Admin, Different button shapes are used, It would be nice to have standard naming convention for all these button shapes, so that developer can create predictable alternates for Admin Theme.

e.g.
- ContentPreview_Button
- Content_PublishButton
- Content_SaveDraftButton

For example, I would like to show "Actions" zone as drop-down similar to https://github.com/OrchardCMS/OrchardCore/issues/3688#issuecomment-541206623 and overriding above shapes with alternates.  As following

`Content-Dropdown.PublishButton.cshtml` ( Content_PublishButton__Dropdown)
`Content-Dropdown.SaveDraftButton.cshtml` (Content_SaveDraftButton__Dropdown)

However for preview naming is different than above,

`ContentPreview-Dropdown.Button.cshtml `( ContentPreview_Button__Dropdown )

Notice the position of `-` in filenames above, its confusing.
 
I suggest to have all button shape uniform naming.

**Comment by agriffard** [comment]
Can you provide a PR?

**Comment by ns8482e** [comment]
Fix in PR #7086 is also related, due to not having uniform naming and shape type contains `__` and `_`
The original shape type should not contain `__` or `_`

I could wok on PR to change shape type  to not contain `_` or `__`.  
Also note that here prefix `Content` is not used to represent  `stereotype` of the content item

So change would be as as following, 

ContentPreview_Button --> ContentPreviewButton
Content_PublishButton --> ContentPublishButton
Content_SaveDraftButton --> ContentSaveDraftButton

**Comment by agriffard** [comment]
Can this be closed?
