### ISSUE TITLE
Is it possible to override Razor MVC Views in module?

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5128]
As per documentation [overriding razor view is possible in theme](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Templates/#overriding-views)

But it doesn't explain on how to override views in a module. 

If i create `Views/{2}/{1}/{0}.cshtml`  in module it doesn't work. I'd like to create `Module B` which depends on `Module A` which enhance the UI functionality of `Module A` where I need to override razor views.

**Comment by Skrypt** [comment]
I think your module B needs to reference module A. Then you can use the /Views folder of the module B to override module A views. You can test this by renaming the views you want to override temporarly in module A to see the list of path where it tries to resolve this view. You can also override views in a theme by using /views/module.folder/moduleviews.cshtml

**Comment by ns8482e** [comment]
`Module B` has reference to `Module A`

Module A has  `/Views/Controller/Action.cshtml` that I am trying to override in Module B as `/Views/ModuleA/Controller/Action.cshtml`, it doesn't work and still taking views from Module A

However If Create Theme, and places views as `/Views/ModuleA/Controller/Action.cshtml` then it overrides. 
 
But I need to implement  functionality as module not as Theme

**Comment by Skrypt** [comment]
Have you tried by using the /views folder directly in module B? If it doesn't I'll take a look in OC Modules code.

**Comment by sebastienros** [comment]
It doesn't need a reference, but a feature dependency, can you confirm?

**Comment by ns8482e** [comment]
Yes, I have both - reference and dependency in manifest for Module A.

From doc
> The ThemeViewLocationExpanderProvider.cs file defines the search paths used by the RazorViewEngine.

But I guess as filename suggests in doc, It seems its just only for the Themes, and not implemented for Modules

**Comment by sebastienros** [comment]
It should be the same. Theme are only different in being last in the dependency chain by default, to apply custom views even if no specific dependency is defined to modules.

**Comment by ns8482e** [comment]
> It should be the same. Theme are only different in being last in the dependency chain by default,

Yes, I can override shape views in module for sure, but not Razor MVC Views i.e. `Controller/Action.cshtml`

**Comment by jtkech** [comment]
As i remember this is to not have too many view locations (related to all modules) for each mvc views, so right now we only share mvc views across modules like this => `"/Views/Shared/{0}.cshtml"` so that we can detect which modules has a shared folder and then only add the view locations of these modules.

**Comment by ns8482e** [comment]
Closing this as I guess `/Views/Shared` is enough.  - the base module can have `cshtml` placed in `Shared` if required to be overridden by dependent module.
