### ISSUE TITLE
How to preserve query string in language switcher

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5129]
I have url a url like this `/en/media-center/sector?alias=sector-education-and-scholarships`.

Unfortunately `switch_culture_url` produces `https://localhost:44335/RedirectToLocalizedContent?targetculture=ar-EG&contentItemUrl=%2Fen%2Fmedia-center%2Fsector`, which eliminates the query string values. 

Is there any way to preserve the query string in the redirection?

**Comment by hishamco** [comment]
This bug is already reported, I will try to fix it unless @jptissot already start on the fix

**Comment by ns8482e** [comment]
@dodyg how about using Request.QueryString and append to generated url?

**Comment by dodyg** [comment]
That doesn't work unfortunately.

Both combinations fail
```https://localhost:44335/RedirectToLocalizedContent?targetculture=ar-EG&contentItemUrl=%2Fen%2Fmedia-center%2Fsector&alias=sector-education-and-scholarships```

https://localhost:44335/RedirectToLocalizedContent?targetculture=ar-EG&contentItemUrl=%2Fen%2Fmedia-center%2Fsector?alias=sector-education-and-scholarships```

**Comment by ns8482e** [comment]
> ```
> https://localhost:44335/RedirectToLocalizedContent?targetculture=ar-EG&contentItemUrl=%2Fen%2Fmedia-center%2Fsector?alias=sector-education-and-scholarships
> ```

you are close replace second `?` with `%3F`

`https://localhost:44335/RedirectToLocalizedContent?targetculture=ar-EG&contentItemUrl=%2Fen%2Fmedia-center%2Fsector%3Falias=sector-education-and-scholarships
`

**Comment by dodyg** [comment]
@ns8482e  this doesn't work either. The `ContentItemUrl` seems to match the string exactly hence if you add anything to the query string value, it will not be able to find the target `Content Item`.

**Comment by sebastienros** [comment]
The solution is to fix the localization controller to extract the correct part of the url to match the content item, and then restore the query string?

**Comment by hishamco** [comment]
I will try to have a look

**Comment by hishamco** [comment]
I just fixed the issue except one little issue why such url `https://localhost:44300/blog/blog/post-1%3Fid=5` shows page not found?

@Skrypt an idea why the Url encoding is not working?

**Comment by jtkech** [comment]
As i have time i will take a look on this.

There are different things, what the picker controller has to do, preserve the query string, how the `switch_culture_url` liquid filter generate / encode or not the url ...

There are things to be careful, not so simple on mvc side, e.g when a `PathString` is converted to a string it is url encoded, but this is not the case for a `QueryString` that needs to be built from an already escaped string OR by using some utilities helpers.

**Comment by hishamco** [comment]
I tried a `ContentCulturePicker` seems it miss a querystring, I successfully passed the QueryString, but seems the anchore tag helper encode the Uri

**Comment by hishamco** [comment]
Similar thing will happen IMHO in the `switch_culture_url`

**Comment by hishamco** [comment]
As expected the `?` of the querystring has been encoded, but my question again, why it shows the page not found while the url is valid (but encoded)?

**Comment by jtkech** [comment]
Okay, can't right now but i will try it this night

**Comment by hishamco** [comment]
What I notice is the Url encode after sending to the server, so it's fine when it renders the link, @sebastienros I think we faced similar issue in edit or delete role long time back, I'm not sure how this should be fixed? And wh the encoded URL shows 404?

**Comment by hishamco** [comment]
> Okay, can't right now but i will try it this night

No problem I will try to find away ...

**Comment by sebastienros** [comment]
Can someone tell me what PR we should look at? I see two of them.

**Comment by jtkech** [comment]
#5207 

I closed #5202
