### ISSUE TITLE
Feature Request- Check to edit the technical name

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5134]
I would like the ability to edit the technical name of a content definition.
I suppose this would go in the common part edit page?
It will only update the content definition file and not the database.
It should probably come with a warning that this is only for advanced users.
I realize the exiting content in the database will not be updated but that's ok.

**Comment by ns8482e** [comment]
Content definition is stored at following location.
 `App_Data\Sites\[SITENAME]\ContentDefinition.json`

You can change the technical name in the file and restart your app.

**Comment by JoshTango** [comment]
Yes I have been doing that and that's why I asked for the feature lol.
You should put this in the backlog as it is not a huge priority

**Comment by ns8482e** [comment]
👎 Technical name, should not be changed once created, as you will use it to create shapes in your modules, themes or build a custom solution. Once your solution is developed and ready for production, you may never want to change the technical name via UI to avoid disaster.

If you need to change Technical name during development, for any reasons, change directly in content definition file or Delete and Recreate  - as it's is safest way.

**Comment by sebastienros** [comment]
Worst case some console application that would convert your content and the type itself. Everything is impacted, even the templates.

**Comment by JoshTango** [comment]
I am aware there would be an impact, that's why I said a warning saying fore advanced users only
