### ISSUE TITLE
Question: Delete Tenant

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5137]
I see no way to delete a tenant in the admin UI.
To delete it manually do I delete the folder and remove it from the tenants json file?
Is that it?
I noticed you guys have talked about this before but still no delete ability?

**Comment by hishamco** [comment]
Duplicate of #1212

**Comment by JoshTango** [comment]
well I choose separate SQLite database for each tenant so that means just delete the folder yes?

**Comment by hishamco** [comment]
Also you should delete it's entry from `tenants.json`

**Comment by JoshTango** [comment]
yes that's what I asked.
I tried and it all worked fine.
Delete folder and entry in tenants.json
