### ISSUE TITLE
using .po in Jquery 

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5143]
how can i use .po in jquery?
i need to show messages in multi culture :
$("#msg" + type).html("Please add your Email*");

**Comment by hishamco** [comment]
The pattern we are using in OC via `data-*` attributes, for instance have a look to how confirm modal dialog is localized

https://github.com/OrchardCMS/OrchardCore/blob/96b06f7ee9b3c79e9ae59952b1eaadf12b4ba223/src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml#L60

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheAdmin/Assets/js/admin.js#L5-L27

**Comment by aghili371** [comment]
> The pattern we are using in OC via `data-*` attributes, for instance have a look to how confirm modal dialog is localized
> 
> https://github.com/OrchardCMS/OrchardCore/blob/96b06f7ee9b3c79e9ae59952b1eaadf12b4ba223/src/OrchardCore.Themes/TheAdmin/Views/Layout.cshtml#L60
> 
> https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheAdmin/Assets/js/admin.js#L5-L27

you meant I should put all messages in data- attributes? 
so i can not have a dynamic message? or i should return the message by function result?

**Comment by sebastienros** [comment]
Put all your translations in `data-*` attributes

```
<div id="translations" data-email="@T["Please add your Email"]"></div>
```
then from javascript, where you call into jquery, something like this:

```
var translations = @('#translations')
$("#msg" + type).html(translations.data("email");
```

**Comment by aghili371** [comment]
> Put all your translations in `data-*` attributes
> 
> ```
> <div id="translations" data-email="@T["Please add your Email"]"></div>
> ```
 
it works by :

`<div id="translations" data-email= "{{"Please add your Email" | t }}"></div>`

**Comment by hishamco** [comment]
> <div id="translations" data-email="@T["Please add your Email"]"></div>
That's Razor and the one you wrote is liquid ;)
