### ISSUE TITLE
Headless CMS & REST API

### ISSUE THREAD

**Issue by lurumad** [OrchardCMS/OrchardCore#5144]
Hi @sebastienros 

I've read in the docs site:

> Headless CMS. The site only manages the content, and you create a separate application that will fetch the managed content using GraphQL or **REST APIs**. Ref: https://www.youtube.com/watch?v=4o9zG17cfa0

I would like to know where I can find docs about REST API.

Regards!

**Comment by jersiovic** [comment]
I've been out of Orchard for a while but it used to be the source code best place to get info. In the modules folder https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/ go to the folder of the module you are interested in and take a look to their ApiControllerrs. For example https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/ApiController.cs 
Same releated to GraphQL

**Comment by sebastienros** [comment]
If you search for REST API in the documentation you will find different ones like Lucene, Queries. But it seems we are missing the content item ones. You can also add your own in the main application or in a custom module.
