### ISSUE TITLE
Question: Liquid template href prefix for tenants

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5147]
I have a liquid templat ein configuration with the following button:
<a class="btn btn-primary btn-xl js-scroll-trigger" href="/{{ Model.ContentItem.Content.Page.TopicName.Text"</a>

It worked until I started making tenants.
Now this href wont work in a tenant because the tenant name wont show up at the start of the href.
is there something I should prefix my href with to get the tenant name to show up?
When I use tilda it does show the tenant name but it also shows the tilda lol

**Comment by ns8482e** [comment]
Use `absolute_url`

**Comment by jptissot** [comment]
`| href` if what you are looking for

**Comment by JoshTango** [comment]
It did not work.
It completely stripped the url name.
This is what I typed:

/{{absolute_url | href}}/

**Comment by JoshTango** [comment]
NVM the problems seems to be I had a slash at the start of my href.
When I removed the slash the tenant name showed up in the url.
