### ISSUE TITLE
Shape type naming convention

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#5151]
`[Stereotype]_[DisplayType]__[Subject]`
Each element should not contain `__` or `_`.

Example: `Content_SummaryAdmin__ActionButtons` instead of `Content_SummaryAdmin__Button__Actions`

For editor/display modes, we should use explicit driver registrations, which will drive the shapes to edit/display following the same rule.

**Comment by ns8482e** [comment]
Related #5126 

Also, All Parts in Form Modules, e.g `ButtonPart_Fields_Edit` should be `ButtonPart_Edit`

**Comment by sebastienros** [comment]
Might not be necessary anymore as JT found a solution to the issue that triggered this suggestion.

But the editor/display mode part is still valid.

**Comment by deanmarcussen** [comment]
possible fix for the editor/display explicit registration on https://github.com/OrchardCMS/OrchardCore/pull/4361

**Comment by Piedone** [comment]
Is there anything still necessary here?
