### ISSUE TITLE
TheBlogTheme and TheAgencyTheme Bootstrap has two bootstrap css files

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5154]
The Blog theme and The Agency theme defines two separate set of bootstrap Why?

`TheBlogTheme/wwwroot/vendor/bootstrap/css/bootstrap.css`
`TheBlogTheme/wwwroot/css/bootstrap-oc.css`

and Both are registered in ResourceManifest.cs

TheBlogTheme-vendor-bootstrap
TheBlogTheme-bootstrap-oc

Also both themes have their own gulpfile.js that builds css and js in "vendor" folder then why use Assets.json that only builds bootstrap-oc.css?

**Comment by Skrypt** [comment]
This is for overriding the base theme. The base theme will get eventually updates and we want to separate our customizations of the base theme itself. If we change the files directly then updating the theme will require more work for merging everything together.

**Comment by ns8482e** [comment]
But If bootstrap-oc.css includes everything from bootstrap + customizations then why include bootstrap.css in the theme source code and resource manifest when it has no use? 

Including bootstrap.css is useful only if bootstrap-oc.css contains only customization and not complete bootstrap.

The `gulpfile.js` of base theme builds `css `and `js `both in vendor folder then why use assets.json just to build just `bootstrap-oc.scss`. Even after using assets.json, It is still required to run `gulpfile.js` to build vendor `js` files - which is also converts scss to css.

**Comment by Skrypt** [comment]
The theme is built by someone else than us. So the gulpfile.js file of the different themes are kept for those who would want to customize the theme for their own needs. We don't alter this gulpfile because it could be overwritten on an eventual update of the theme itself.

So in OC we rely on our gulp pipeline to build all assets through the usage of a Assets.json file for every module/themes that require some customizations on top of the libraries that are used in those modules.

Yes, bootstrap-oc.scss has an @import of the main bootstrap scss files because some of our .scss files  requires to extend the base BS4 classes. But as you can see we include in the layout.liquid files only the bootstrap-oc.css file too.

**Comment by ns8482e** [comment]
>  gulpfile.js file of the different themes are kept for those who would want to customize the theme

Exactly, that's the intention and I see the same [Readme](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheAgencyTheme/wwwroot/README.md#advanced-usage) included in OrchardCore.Themes - TheAgencyTheme. 

But the Readme doesn't mention anything about `bootstrap-oc.scss` but layout.cshtml uses it.

It's very confusing and unclear for who whats to take TheAgencyTheme or TheBlogTheme as an example to start with to create their own theme.

**Comment by sebastienros** [comment]
I think we should remove the entries that are not used in the resource manifest. But also document what the other css files are.

**Comment by ns8482e** [comment]
How about keeping original bootstrap file and using mixins with `@include` instead of `@extend` for `bootstrap-oc` customization? 

The agency gulpfile is capable of building all *.scss files -

e.g
```
.flow {
    @include make-row;
}
```
and creating task for theme's gulpfile.build in main gulpfile? As theme's gulpfile is exported as node module and can be called using require().  

```
agencytheme = require('./src/OrchardCore.Themes/TheAgencyTheme/wwwroot/gulpfile');
gulp.task("agency", function(done){
	var cwd = process.cwd();	
	process.chdir('./src/OrchardCore.Themes/TheAgencyTheme/wwwroot');
	agencytheme.build();
	process.chdir(cwd);		
	done()
});
```

**Comment by Skrypt** [comment]
Try it, if that works then that might be a solution.
