### ISSUE TITLE
Proposal: Consider adding Category field to Widget metadata

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#5157]
Right now when I have planty of widdgets it is sometimes inconvenient to select them from drop down list in FlowPart. It would be quite nice if Widgets could have Category field (regular string type) so they can be grouped. For example Widgets like: "Form", "InputField", "TextboxField", "Label" could have category: "Forms".  Other widgets like: "Paragraph", "Blockquote", "Codeblock" could be in category: "Typography" etc. So later on Widgets dropdown can be rendered in more descriptive way by particular groups. It will be also easier to find out from which module some Widgets come from. So for example if I have CustomBanners module I would like put all my widgets to "CustomBanners" category so user have quick inidication in Widgets dropdown.

**Comment by ns8482e** [comment]
Are you looking something similar to #3558 ?

**Comment by arkadiuszwojcik** [comment]
Thank you, this is exactly what I was thinking about. Closing this issue as duplicate.
