### ISSUE TITLE
Integration with Nextcloud

### ISSUE THREAD

**Issue by mruslan97** [OrchardCMS/OrchardCore#5159]
I want to connect Assets with Nextcloud. Does anyone have experience with webdav or Nextcloud api? Probably new module which override default files implementation. I would like to know any information. Regards!

**Comment by hishamco** [comment]
I think you need to implement `Orchard Core.Media.Abstractions`, regarding Nextcloud you need to check there docs

`Orchard Core.Media.Azure` implementation may a good resource to see how it works

**Comment by sebastienros** [comment]
Here is the example for Azure: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs

**Comment by hishamco** [comment]
OMG I thought you are talking about Media, if the intend is file storage, as Seb said before have a look to file storage abstractions
