### ISSUE TITLE
HTTP 500 after the Setup page ( Azure container app service )

### ISSUE THREAD

**Issue by maxrizwork** [OrchardCMS/OrchardCore#5164]
I installed ( initially with the same problem ) and used for a couple of months the RC1  on Azure as Container App Service , with a SQLLite db.

Then I started to see again the first Setup page and my website is gone.

I tried to reinstall again using both the latest and dev docker image but I always have the same behaviour. I can install and open the Setup page, but after I click I get an HTTP 500 error. 

The environment variable ORCHARD_APP_DATA is there.
I tried both with WEBSITES_ENABLE_APP_SERVICE_STORAGE with true and false but nothing.

Anyone experienced the same problem? 

Update
After other experiments I found out that:
- the same docker container on another machine is working perfectly
- it's related to sqllite option as database
- if I use SQL Server for example, it works
- looking the file share mounted I see that it creates yesssql.db, an empty DataProtection-Keys folder and a temporary file yessql-db-journal. After the error yessql-db-journal is gone and all the other files are not created

**Comment by sebastienros** [comment]
Seems like you are using a Linux App Service plan, in which case Sqlite won't work. It's officially unsupported (on the Azure side) as sqlite can't handle the file share protocol that Azure is using, so file locks will never be released.

There is an option in the connection string to ignore locks, but I haven't tried it, it's hard to set in OC, and any concurrent access to the db will corrupt it.
