### ISSUE TITLE
Lucene : Implement Tokenized and Sanitized

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#5179]
Implement Tokenized and Sanitized

**Comment by Skrypt** [comment]
@sebastienros please, correct me if I'm wrong but I think the FullText aspect now can be used for this?
What was doing Tokenizing and Sanitizing in 01?

**Comment by sebastienros** [comment]
Remove Tokenized and Sanitized from the fields since this can be done with full text options.
Keep stored and analyzed.
