### ISSUE TITLE
Taxonomy index disposed scope exception

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5204]
While getting the admin routes working for taxonomies came across this exception

![taxonomyindex](https://user-images.githubusercontent.com/13782679/71765362-9332e580-2eeb-11ea-8885-923c02350d0c.PNG)

Occurs during saving a new `TermPart`

@jtkech I've stepped back as far as https://github.com/OrchardCMS/OrchardCore/pull/4933 and is still occuring, will step back a bit more when I have time and see where it's from

**Comment by jtkech** [comment]
I can't repro, i would need to check it in the same branch where you saw this issue.

Regarding the trace i see that when the session is disposing it does a `FlushAsync()` meaning it has no been committed yet => is committed when disposing (through the shellScope disposing) => The issue we had with scoped index provider that resolve scoped sevices through the scoped service provider but while the scope is disposing.

So i think that there is another issue => shellScope `BeforeDispose()` that is intended to commit the session is not executed => session will be committed but only when disposing.

**Comment by deanmarcussen** [comment]
@jtkech sorry, I must have caused this with bad routing, as I can't repro this morning either.
Will close and if I see again will look at further based on your comments

**Comment by deanmarcussen** [comment]
@jtkech This was caused by trying to add a Term  that had an `AliasPart` on it, as I was in a bit of a rush at the time, and just randomly picked an existing `ContentType` for the Terms.

I won't reopen as I think we've already looked at that and decided that `AliasPart` and `AutoroutePart` had no place on a taxonomy
