### ISSUE TITLE
Empty Alias is not generated with the correct value.

### ISSUE THREAD

**Issue by DamienLaw** [OrchardCMS/OrchardCore#5205]
I'm using the latest commit of the _dev_ branch and following this [guide](https://orchardcore.readthedocs.io/en/dev/docs/guides/decoupled-cms/#loading-a-blog-post-from-a-custom-slug).

I added the **AliasPart** to the content type **BlogPost** and specified `{{ ContentItem.DisplayText | slugify }}` as its pattern.

However, when adding a new BlogPost, the empty Alias (which was intentionally left blank) was not correctly generated upon saving. It produced a value `-1` instead of a value that makes more sense such as `happy-new-year`.

The screenshot below was taken after saving the blog post with an empty Alias.

![image](https://user-images.githubusercontent.com/14930009/71767615-fc951180-2f48-11ea-8a4a-53d97780622c.png)

**Comment by deanmarcussen** [comment]
Yes, this is a recent regression.

There is a fix in the works but in the short term you can use {{ Model.ContentItem }} in the pattern until the old pattern is available again

**Comment by sebastienros** [comment]
Fixed
