### ISSUE TITLE
Move AdminConstraint to Feature

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5211]
I don't think this needs any extension points @sebastienros as it is just an `MvcOptions` `Convention` so applying or extending it would only be a matter of changing the `IOptions<MvcOptions>` to apply a different convention.

This would resolve the issue where we cannot force users to map routes to the `AdminUrlPrefix`, but if they use the feature, then they will have the warnings logged, so they know to map their admin routes correctly.

**Comment by hishamco** [comment]
> we cannot force users to map routes to the AdminUrlPrefix

IMHO all the admin routes should use the prefix, but the users have an option to change the `AdminUrlPrefix` according their needs

**Comment by deanmarcussen** [comment]
yes @hishamco I didn't explain that very clearly.

All our routes should use the `AdminUrlPrefix` but there are many users who have made their own `AdminController` or used the `[Admin]` which will not have the mapping done on these controllers.

And as already evidenced this change was quite breaking for some, and therefore it is better to be a feature to restrict the admin routes that can be enabled if a user wants it, than forcing a breaking change on them.
