### ISSUE TITLE
Render javascript in HtmlBody Should Stop

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5215]
if you have javascript in HtmlBody, it will render. so if this script renders a new iframe or redirects page to another page, you can not edit your content after saving the content.

i think it's better to have HTML, edit and view mode or stop render javascript in edit mode.

**Comment by sebastienros** [comment]
Maybe an option of Trumbowyg?

**Comment by ns8482e** [comment]
@aghili371  see if this can help,  https://github.com/Alex-D/Trumbowyg/issues/793

**Comment by aghili371** [comment]
> Maybe an option of Trumbowyg?

i can not find any option there.

**Comment by aghili371** [comment]
> @aghili371 see if this can help, [Alex-D/Trumbowyg#793](https://github.com/Alex-D/Trumbowyg/issues/793)

> When you are embedding the tweet, make sure you do not include the twitter script tag. Use the Twitter script code only when you are rendering your UI.
> 
> Do not include <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> while embedding your tweet.
> 

i think this is not a general solution.

**Comment by sebastienros** [comment]
Can you provide some repro steps to understand what issue it's actually causing? Or a small video?

**Comment by agriffard** [comment]
It would now be sanitized unless the option is disabled.
Can this be closed?

**Comment by Piedone** [comment]
Yep, we have sanitization for this now.
