### ISSUE TITLE
auto replace <DIV> to <p> in HtmlBody  

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5216]
if i add div tag in HTML mode and change the view mode to view, HtmlBody replaces tags. i think it is better to keep tags.

**Comment by agriffard** [comment]
https://alex-d.github.io/Trumbowyg/documentation/#semantic

You can use a `Trumbowyg` Editor in the HtmlBody settings with this config:
```
{
    semantic: {
        'div': 'div'
    }
}
```
