### ISSUE TITLE
Pass Params to Widgets

### ISSUE THREAD

**Issue by ahmedtabba** [OrchardCMS/OrchardCore#5217]
Can I Pass Params to Widget to be able to render widget dynamiclly according to params In Passed

**Comment by sebastienros** [comment]
You actually mean to render the template of a widget with a custom view model (shape) as a widget is a content item per se, with its own state.

And then yes, call `@await DisplayAsync(New.WidgetName(contentItem))`

But I don't think you really need widgets in this case, I would think that you just want to render any custom template. Right?

**Comment by ns8482e** [comment]
You mean Request Params? You can access using Liquid widget  https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#request
