### ISSUE TITLE
Default display option for fields without Standard display

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5219]
If you want to add a Display option for a field that does not have a Standard one, when you re-edit the settings and save, the new one will be selected even if you don't want it.

Should we add a Standard option for all the fields or find a way to offer to select an empty one when there is only a custom one available?

**Comment by sebastienros** [comment]
Correct, and implementing it should not be much difficult. Also @deanmarcussen is refactoring how these drivers are registered.

**Comment by sebastienros** [comment]
@deanmarcussen So each time we register a driver, we should set for which modes it is used ("Default", "Custom1"). This way we can either be called on a specific mode, or even be added to existing drivers of a mode. Should we be able to replace the drivers of an existing mode? I'd say yes, as it's easy and could be useful for a module to override the "default" editor.

**Comment by deanmarcussen** [comment]
@sebastienros yes that's how I've implemented it on https://github.com/OrchardCMS/OrchardCore/pull/4361 (maybe you don't like that PR? or you haven't looked yet)

By default registration is `*` to indicate all display modes.

Other options include registering as 
```
services.AddContentField<MarkdownField>()
    .WithDisplayDriver<MarkdownFieldDisplayDriver>(o =>
    {
        o.ForDisplayModes("*"); // use this driver for all display modes
        o.ForDisplayModes("standard", "my-custom-display-mode"); // use this driver for standard and custom
        o.ForDisplayModes("my-custom-display-mode"); // just my custom mode
});
```

and I've left the `IOptions` hashsets open so it's possible to adjust registrations, i.e. removing a driver type completely, to replace it with another, or adjusting a display mode / editor to no longer be `*` and just for `standard`, to allow a custom driver to handle a particular mode

**Comment by deanmarcussen** [comment]
@agriffard will you add these default standard display options for the fields?

What I am doing with the display driver registration won't fix the need for the shapes

**Comment by agriffard** [comment]
@deanmarcussen Yes, I will add them if they are needed.

Do I have to wait that your PR is merged?

**Comment by deanmarcussen** [comment]
No, not at all, (but I saw the issue you described when I looked at your code, so it makes sense.) 

I think the way to do it is just add a Standard option for all fields (because we will need the shape views)
