### ISSUE TITLE
ContentPreview became slow

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#5226]
Working on another PR i noticed that a `ContentPreview` (tried with an article type) became slow.

The execution time of the `PreviewController.Render()` seems okay but it takes a long time to be triggered, i just opened the dev tools and saw that a `jquery xhr.send` take a long time, around 1s.

**Comment by Skrypt** [comment]
I calls UpdateEditorAsync which will call the Lucene Indexer btw.

**Comment by jtkech** [comment]
Oh yes, good catch, just tried if i disable lucene then it becomes again faster.

So we would need to find a way to prevent this when updating but in a preview context.

Hmm, as i remember when previewing we have a fake item with `ContentItem.Id = -1`.

I will try it.

**Comment by jtkech** [comment]
Okay fixed, we just need to use

        private Task AddContextAsync(ContentContextBase context)
        {
            if (context.ContentItem.Id == -1)
            {
                return Task.CompletedTask;
            }

Maybe with a null check, maybe not i don't remember if the item may be null here

**Comment by Skrypt** [comment]
Add the nullcheck we never know. ;)

**Comment by jtkech** [comment]
Too late, i did the PR ;)

I didn't check it because aftewards in the deferred task i saw that we use e.g `c.ContentItem.ContentItemId` without null check.

But yes maybe better to add a null check, i will see tomorrow, and then maybe also in the other places.
