### ISSUE TITLE
OrchardCore With React Redux [SPA] in Module

### ISSUE THREAD

**Issue by EugeneBoom** [OrchardCMS/OrchardCore#5227]
Is it possible create a SPA module? if yes how startup class should look like?

**Comment by EugeneBoom** [comment]
I've created a test app with several modules. One of them contains react client application. 

As a result I get an error Failed to start 'npm'. I suppose I have problems with routes in module and I don't know how to relosve it.

![module](https://user-images.githubusercontent.com/35485786/71905860-05205e80-317a-11ea-915e-b08827e1dbed.png)
Startup class in SpaModule4 looks like this
`   public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // In production, the React files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/build";
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseSpaStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller}/{action=Index}/{id?}");
            });

            app.Map("/spamodule4", config =>
            {
                app.UseSpa(config =>
                {
                    config.Options.SourcePath = "ClientApp";

                    if (env.IsDevelopment())
                    {
                        config.UseReactDevelopmentServer(npmScript: "start");
                    }
                });
            });
        }
    }`

**Comment by deanmarcussen** [comment]
here's a sample angular one I got running the other day.

You're pretty close ;)
```
    public class Startup : StartupBase
    {
        private readonly IHostEnvironment _env;

        public Startup(IHostEnvironment environment)
        {
            _env = environment;
        }

        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddSpaStaticFiles(spa => spa.RootPath = "../ThisNetWorks.OrchardCore.Spa/ClientApp");
        }

        public override void Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
        {
            app.UseSpaStaticFiles();
            app.Map("/app", spaApp =>
            {
                spaApp.UseSpa(spa =>
                {
                    spa.Options.SourcePath = Path.Join(_env.ContentRootPath, "../ThisNetWorks.OrchardCore.Spa/ClientApp");

                    if (_env.IsDevelopment())
                    {
                        spa.UseAngularCliServer(npmScript: "start --base-href=/app/ --serve-path=/");
                    }
                });
            });
        }
    }
```

**Comment by EugeneBoom** [comment]
It works nice. Thank you!)

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/tree/skrypt/webpack-hmr
I did that a while ago too.

**Comment by abdurahmanus** [comment]
What if I have several SPA modules? Will it work?

**Comment by deanmarcussen** [comment]
@abdurahmanus yes, should do. If they're mapped under different routing routes.

You're essentially getting into SpaServices there, so if you can do it with aspnetcore, then it should work under Orchard Core

**Comment by eugene-latarevich** [comment]
It works fine for several SPA apps. I tested it for two React apps. You have to configure your startup classes as shown above and also change a spa app public path in webpack.config. It depends on your map route.
In my project it looks like:
const publicPath = isEnvProduction
    ? paths.servedPath
    : isEnvDevelopment && '/learning/';

**Comment by abdurahmanus** [comment]
@eugene-latarevich how did you change public path in React app? Did you eject it?

**Comment by eugene-latarevich** [comment]
If you create react app via npm it will create node_modules folder in your client app folder. In VS the folder is hidden. In that folder you should follow /react-scripts/config/webpack.config.js. There is a variable publicPath.

**Comment by SzymonSel** [comment]
> here's a sample angular one I got running the other day.
> 
> You're pretty close ;)
> 
> ```
>     public class Startup : StartupBase
>     {
>         private readonly IHostEnvironment _env;
> 
>         public Startup(IHostEnvironment environment)
>         {
>             _env = environment;
>         }
> 
>         public override void ConfigureServices(IServiceCollection services)
>         {
>             services.AddSpaStaticFiles(spa => spa.RootPath = "../ThisNetWorks.OrchardCore.Spa/ClientApp");
>         }
> 
>         public override void Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
>         {
>             app.UseSpaStaticFiles();
>             app.Map("/app", spaApp =>
>             {
>                 spaApp.UseSpa(spa =>
>                 {
>                     spa.Options.SourcePath = Path.Join(_env.ContentRootPath, "../ThisNetWorks.OrchardCore.Spa/ClientApp");
> 
>                     if (_env.IsDevelopment())
>                     {
>                         spa.UseAngularCliServer(npmScript: "start --base-href=/app/ --serve-path=/");
>                     }
>                 });
>             });
>         }
>     }
> ```

@deanmarcussen I followed your solution and got it up and running. I've placed the code in my Modules' `Startup.cs`. It work "on my machine" however once I deploy it to Azure I get "An error occurred while executing this request."

I've made sure to build angular and copy it to the server. So my server file structure looks somewhat like this:
- App_Data
- OrcharCore.AngularModule
- - ClientApp
- - - { all the dist content like *.js, *.html, assets, *.css }
- runtimes
- Orchard.cms.dll
- OrchardCore.CMS.dll
- {and many many more dll's}

Sadly I'm stuck, and the app logs are empty.
