### ISSUE TITLE
Import does not seem to do anything

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#5230]
We have a set of documents (based on a custom ContentType) that we need to bulk-update. We thought that the following steps would do the job:

1. Create a DeploymentPlan for contents of that particular ContentType.
2. Run it and download the zip file.
3. Extract the zip file.
4. Edit the json file doing a simple search and replace.
5. Compress it again into a new zip file.
6. Import the new zip file back in Orchard.

However, when we do the import, nothing happens. It seems to be run successfully (green bar on top stating 'import package succesfully imported') but the **old** contents are still there and not the changes we wanted (1st test).

We also tested deleting the existing documents first and then doing the import, but in that case **they are not created at all** (2nd test).

As last resort, we simply tried importing the original zip file (without our modifications), with the same results: nothing is imported (3rd test).

We had a backup of the yessql.db file so no actual loss occurr, but we thought that at least the restoration of the original file would work.

Any ideas about what might be happening? During the restoration of documents, is any check done that might prevent them from being updated? Maybe if they have the same ContentItemVersionId are skipped? Or ModifiedUtc is checked?
Anyway none of that would apply in case the documents were deleted and needed to be simply inserted (our 2nd and 3rd tests).

We are running RC1. Thanks.

**Comment by hishamco** [comment]
>We are running RC1

Did you try it it with the latest bits?

**Comment by jagbarcelo** [comment]
I have just updated to 1.0.0-rc1-11436 using the URL posted in #5080 by @sebastienros and it shows the same behaviour for the 3 test cases formerly described.

**Comment by agriffard** [comment]
Related to #1970
