### ISSUE TITLE
Workflows : Disabled Time Based workflow still executes scheduled workflow

### ISSUE THREAD

**Issue by aderderian** [OrchardCMS/OrchardCore#5231]
After disabling a workflow where a Timer is the starting Task, the workflow task still executes. This seems to happen since a Workflow Type queues a new Workflow event and the Timer task queues a Halted Workflow item prior to it executing. Then when it comes time to execute the timed event, even though the workflow is disabled, it still executes.

I would argue it should remove this queued item or at least not execute until it is Enabled again.

**Comment by jtkech** [comment]
Yes, i think i already saw this, as i remember the workaround was to list the existing instances and delete them.

**Comment by aderderian** [comment]
So I think on disable, we should just query for items that are queued and remove then right?

**Comment by jtkech** [comment]
Yes i agree
