### ISSUE TITLE
OIDC Authentication Client - SignOut

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#5232]
Hello, I think there are two issues with the logout when logging in using an external identity provider.

The first one is that when I log out from the admin portal I'm redirected to the root path instead of the configured one (in my case it would be /admin).
The second one is that I'm not logged out from the external provider.

**Comment by hishamco** [comment]
> instead of the configured one (in my case it would be /admin).

Which configuration settings do you mean `AdminUrlPrefix` or something else?

**Comment by nuno-tiago-reis** [comment]
I mean the 'SignedOut Redirect Uri' setting in the OpenID Connect > Settings > Authentication Client menu.

**Comment by bcampardou** [comment]
> The second one is that I'm not logged out from the external provider.

What about this point ?
Is there a way to disconnect from IDP (ie /connect/endsession endpoint) ?

**Comment by sebastienros** [comment]
Closing because too old, might need more repro steps
