### ISSUE TITLE
Is there any way to implement CRUD of Content Item via webapi?

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#5240]
If I want to create a single page application to manage content items via webapi, can Orchard Core do it?
Is there a WebAPI like this ? 
I did not find the relevant instructions in the documentation

**Comment by Skrypt** [comment]
Look at an ApiController.cs in the source code to see an example. I believe what you mean is to use a REST API to do CRUD operations. You can do that.

**Comment by hyzx86** [comment]
@Skrypt  Got it, Thank you !
