### ISSUE TITLE
Localization and canonicalization

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#5241]
We are trying to setup a two-language site, with base URLs for each locale being "/en" and "/es".
We have also customised the menus for each language, everything shown correctly for most of the pages… however for some URLs the language being shown is wrong. For example:

| URL | Should be | Is shown in | Comment |
|---|---|---|---|
| /  | English | English | Homepage |
| /en | English | English | English home, same as / |
| /es | Spanish | Spanish | Spanish home, translated from /en |
| /en/release-notes | English | English | Ok |
| /es/release-notes | Spanish | Spanish | Ok |
| /en/ | English | Spanish | Wrong. It shows the contents from /en with the localization (translations) of Spanish |
| /es/ | Spanish | Spanish | Ok, but might be better to redirect to /es |
| /en/release-notes/ | English | Spanish | Wrong. It shows the contents of /en/release-notes but using the Spanish translations |

As you can see, all the weird cases happen when the URL ends with a slash (/) other than the homepage. For the sake of canonicalization, maybe it should simply behave doing a 301 redirect to the same URL but without the ending slash (or maybe insert a rel=canonical tag in the response, but it would require more work and discussion).

Please note that those URLs ending with **/** are manually crafted and thrown to the server just for testing (they are not generated at all by OrchardCore).

The native localization of our servers and developing machines is Spanish, though we want the website to have English as default language.

Please also note that the case **/es/** being shown in Spanish might be due to our servers and/or default browser language being in Spanish. For other users this case might yield a wrong result, i.e. **/es/** might be shown in English (this is just a guess, not tested).

We are running OrchardCore 1.0.0-rc1-11436

**Comment by hishamco** [comment]
@jtkech I think you trimmed the slash at the end in the last PR that we're working on. Am I right?

**Comment by jagbarcelo** [comment]
The ContentItemId being picked in every case seems to be correct. It is the locale of the returned pages what is (sometimes) wrong:

**/en/** shows the contents of the **/en** page but all the translations in that page are in Spanish (and the html lang tag too).

**Comment by jtkech** [comment]
Yes, there is a good chance that it will be fixed through #5207 where we saw the same issue and fixed it,  with a trailing slash the routing works but the localized item is not found.

**Comment by sebastienros** [comment]
We need a tutorial that explains which patterns to use, can be used, and how to implement them.
Also maybe a feature to define custom redirections for the homepage based on the accept headers. A more generic rewrite rule could work too, but might be slower and more complex to configure.

**Comment by jagbarcelo** [comment]
@hishamco Now it works fine. With the new bits (1.0.0-rc1-11871) the issue dealing with trailing slashes has gone (the content, menus and translations are shown in the expected language).

There is however the part of canonicalization. Will OrchardCore will address this in any way?
Maybe those manually crafted URLs (ending with /) should have a <link rel="canonical"> to their non-trailing-slash URLs. What's the mainstream opinion about this?
