### ISSUE TITLE
CDN's limit access issue

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#5244]
Hi guys,
I have a problem with CDNs and some of them has limit access for me. for example fontawesome and vue.js not working and media app not opening:
![image](https://user-images.githubusercontent.com/57654948/71771333-6fed5200-2f4e-11ea-9549-4fb888fdd5b7.png)
Thanks for your efforts

_Originally posted by @sayyad84 in https://github.com/OrchardCMS/OrchardCore/issues/4271#issuecomment-570817379_

**Comment by deanmarcussen** [comment]
Are we up for making font awesome and vuejs and plugins available locally?
To work around cdn related issues

I think we already did a local font awesome for the themes, but not yet OrchardCore.Resources

**Comment by sebastienros** [comment]
I am ok with that as licences allow. The main issue was only for Fontawesome which was cleared out.
