### ISSUE TITLE
Pager issue on search page

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#5246]
> Create an index named "Search" and configure it with the type you want. Go on /search on the front end.

@sebastienros 

`/search` shows

![search-page](https://user-images.githubusercontent.com/1761249/71781366-9d7dde00-2fd6-11ea-9d8f-73ed0ab2f8a8.png)
 

Based on `1.0.0-rc1-11395`

_Originally posted by @dodyg in https://github.com/OrchardCMS/OrchardCore/issues/4142#issuecomment-570916394_

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/5181
