### ISSUE TITLE
ApiController not handling auth cookie

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#5247]
I got 401 error when try to post to `api/lucene/content` (based on this [doc](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Lucene/#web-apis)) 

Is there any settings that I need to modify to enable this endpoint to be accessible publicly? I am calling this from a JavasScript inside a Liquid Page.

![search-api](https://user-images.githubusercontent.com/1761249/71781063-f6e40e00-2fd2-11ea-8287-27817791aecf.png)

Based on `1.0.0-rc1-11395`

_Originally posted by @dodyg in https://github.com/OrchardCMS/OrchardCore/issues/4142#issuecomment-570914357_

**Comment by carlwoodhouse** [comment]
is this not by design ? as far as i know the api controllers all only auth against the Api authentication scheme; which explicitly looks for bearer

**Comment by carlwoodhouse** [comment]
@sebastienros see - https://github.com/OrchardCMS/OrchardCore/issues/3158 for reasons why it is by design ;)

**Comment by sebastienros** [comment]
Mystery solved. OpenId is required to authenticate ApiController.

@dodyg does it answer your question?

Now, one could ask:
- How to get a token representing the currently logged user
- Is there a way to allow anonymous users to still call this endpoint without auth
