### ISSUE TITLE
Date/time picker : Edit Creation Date

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#525]
Please give your suggestions about what kind of client-side component we should choose to select a date/time.

There is a lot of pre-requisite work to do before because it will need to use the current culture and timezone (and later, the calendar settings as in O1).

It will be used for the date time field and for the editor of the 'creation date'.

**Comment by agriffard** [comment]
See #434 to manage the cultures.

**Comment by sebastienros** [comment]
@DanielStolt and I have recently talked about datetime localization offline. First thing is to reference the issue that was opened in O1 related to the types of fields we actually need (Date, Time and DateTime AFAIR). It explained why. We might not have to care about Cultures for now if you want to make some progress on the fields. Timezone is already supported so you can use it at least.

**Comment by agriffard** [comment]
there is an issue when you add a content item: if the owner part is displayed and you enter a user name, it will create the item using the current one, not the specified one.

**Comment by agriffard** [comment]
Now that the DateTimeField and the Timezone setting exist, we should also think to the editor of the CreatedUtc in CommonPart-Date.Edit.cshtml.
Should we just use an input with type="datetime-local"?

**Comment by agriffard** [comment]
Also: When a date is manually set on creation or update, do we have to convert it to Utc when we store it and convert it to the current timezone when we display and re-edit it, like the DateTimeField ?

**Comment by Skrypt** [comment]
Yes save to DB as UTC and display with LocalClock.ConvertToLocal()

**Comment by agriffard** [comment]
In Edit, we should format it to not display the milliseconds.

**Comment by Skrypt** [comment]
That's maybe just a string.format

**Comment by agriffard** [comment]
I removed the step="1" because it can lead to a  client validation error in Chrome.
https://stackoverflow.com/questions/41373682/input-type-datetime-local-doesnt-support-seconds-in-chrome
