### ISSUE TITLE
[GraphQL] Reusing dynamic parts on multiple types wont resolve

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/OrchardCore#5250]
Reproduction:

Create a part in the admin `nameclashpart`
Add a text field to said part called `namefield`
Create two new contenttypes `nameclash1`, `nameclash2` in and add the `nameclashpart`
Try to query both types in graphql

![image](https://user-images.githubusercontent.com/465424/72162735-646cb180-33ba-11ea-99a1-70ae3942e1c1.png)

The second one will always fail with the above error.

reported on gitter by @jeffolmstead

**Comment by carlwoodhouse** [comment]
Some investigation later it reveals that it's because the dynamic type builder basically tries to register an identical fieldtype twice,but the resolver always tries to resolve the first registration. Doesnt occured in the strong typed parts as they use DI to always get the right registration.

**Comment by jptissot** [comment]
I ran into the same bug
