### ISSUE TITLE
Remove IUpdateModel from AdminController and use ControllerModelUpdater instead

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5253]
Remove `IUpdateModel` from following
`public class AdminController : Controller, IUpdateModel`

and instead of passing `this` in BuildEditor

`var model = await _contentItemDisplayManager.BuildEditorAsync(contentItem, this, true);`

Inject  `IUpdateModelAccessor updateModelAccessor` and pass updater from service.

```
var updater = _updateModelAccessor.ModelUpdater;
var model = await _contentItemDisplayManager.BuildEditorAsync(contentItem, updater , true);
```

This would allows flexibility to add/modify  IUpdateModel interface definition or override methods for e.g. `TryUpdateModelAsync` in `ControllerModelUpdater` without overriding every controllers. Also it stays consistent with other areas of orchard core.

**Comment by hishamco** [comment]
Good, your thoughts @sebastienros @jtkech @deanmarcussen @Skrypt

**Comment by jtkech** [comment]
Looks like a good idea

**Comment by sebastienros** [comment]
I have no idea how it is better. You can add custom extension methods to the interface if necessary, and the code after this PR is much more complex.

I initially thought that you would just remove the implementation of this interface on controllers, and inject it using `IUpdateModelAccessor` only.

@jtkech how is that a good idea? The code is so much more complex after.
Unless it fixes an actual issue which I don't understand here.

**Comment by ns8482e** [comment]
> I initially thought that you would just remove the implementation of this interface on controllers, and inject it using `IUpdateModelAccessor` only.

@sebastienros yes that's the Idea. I used `explicit operator `so that code can have minimum changes. 
If you don't like `explicit operator ` I will inject `IUpdateModelAccessor`  in constructor and use local variable `updater` instead of `this`

**Comment by deanmarcussen** [comment]
From the triage meeting last night it was unclear what issue you were trying to fix here.

But injecting `IUpdateModelAccessor` was the preferred option.

However if it was to fix https://github.com/OrchardCMS/OrchardCore/issues/5149 a `stereotype` placement rule would be the better option, if that solves the issue as well?

**Comment by ns8482e** [comment]
> But injecting `IUpdateModelAccessor` was the preferred option.

I am using dependency injection only by using `GetService`  inside`explicit operator`

```
 public static explicit operator ControllerModelUpdater(AdminController controller)
 {
            var updater = (IUpdateModelAccessor)controller.HttpContext.RequestServices.GetService(typeof(IUpdateModelAccessor));
            return (ControllerModelUpdater)updater.ModelUpdater;
}
```
So comparing following statement 

```
var model = await _contentItemDisplayManager.BuildEditorAsync(contentItem, (ControllerModelUpdater)this, true);
```
With below lines is technically the same

```
var updater = _updateModelAccessor.ModelUpdater;
var model = await _contentItemDisplayManager.BuildEditorAsync(contentItem, updater , true);
```

If it looks more complicated then I'll remove `explicit operator `

**Comment by ns8482e** [comment]
> However if it was to fix #5149 a `stereotype` placement rule would be the better option, if that solves the issue as well?

I need to differentiate `IUpdateModel` inside `ContentsDriver` not to create button shapes for widgets or mock widgets by adding a property `IsPrimaryContent ` in `IUpdateModel`


**ControllerModelUpdater**
`pblic bool IsPrimaryContent => true;`

**ModelStateWrapperUpdater**
`public bool IsPrimaryContent =>  !(_updater is ModelStateWrapperUpdater) && _updater.IsPrimaryContent ;`

**ContentsDriver**
```
if(!updater.IsPrimaryContent)
 {
                return null;
 }
```

**Comment by ns8482e** [comment]
@sebastienros  @deanmarcussen  removed `explicit operator` as requested

**Comment by sebastienros** [comment]
I merged the PR, but I am not convinced about the change on `IUdapteModel` that you are suggesting.
I will dive in once you have done the PR to understand what's wrong.

**Comment by ns8482e** [comment]
@sebastienros I agree with you, I started with small change but it turned out to be more changes so I split changes into multiple PRs - will create PRs soon.
