### ISSUE TITLE
CreateContentItem GlobalMethod bug

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5260]
`createContentItem` global method does not update the DisplayText property on the indexes.

**Comment by jptissot** [comment]
I also noticed that the owner field is not properly set (it's null) when creating the content from this scripting method.

**Comment by jptissot** [comment]
I am not sure if this is related, but it seems the Content data passed to the CreateContentItem method does not contain all the field values, only the values that are specified in the content argument. 

For example: 

If my type has a Selected field but I do not specify it when using this scripting method, the json in the database will not contain the hierarchy for the selected field.

```
createContentItem(  {
"ParticipantPart": {
    "FirstName": {
      "Text": "John"
    },
    "LastName": {
      "Text": "Doe"
    },
    "Email": {
      "Text": "john.doe@email.com"
    },
},
}, true);
```
This will result in the `{"Selected":{"Value": false} }` to not be present in the db.

**Comment by deanmarcussen** [comment]
@jptissot @MichaelPetrinolis had the right fix for this in https://github.com/OrchardCMS/OrchardCore/pull/5000 (call `.Apply()` on the elements)

**Comment by jptissot** [comment]
It seems some important logic is placed in the Contents.Admin Controller but should be part of a service.

**Comment by Skrypt** [comment]
Wait we are going back to this one? I'm pretty sure it worked when we tested this last time.

**Comment by MichaelPetrinolis** [comment]
@Skrypt the issue on the first place was not the awaiting of the update method, but with merging the contents of the contentItem. Merge does not fill each typed part properties so the yessql indexes do not work. eg AliasPart.Alias is null, but AliasPart.Content.Alias will have a value after merge.

**Comment by Skrypt** [comment]
What I had tested worked with the DisplayText and TitlePart. I don't doubt that what you are doing will fix the issue differently. Though, it should not be required.
