### ISSUE TITLE
Content definition editor is broken

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5261]
Version `1.0.0-rc1-11459`

Hard reload with empty cache doesn't fix

![content-definition-broken](https://user-images.githubusercontent.com/1761249/72233323-5348be00-35cf-11ea-8b14-6b5bda05696f.png)

**Comment by Skrypt** [comment]
Yes I can repro

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/72235169-976f9a80-359e-11ea-9085-6b6f3d301103.png)

The issue is with part and fields.

**Comment by dodyg** [comment]
> I can repro the non-unique id warning message. Though I can't repro the Cannot read property error. Please give repro steps.

Maybe this is related https://github.com/OrchardCMS/OrchardCore/issues/5262

**Comment by dodyg** [comment]
> Cannot read property error.

This happens to all content item definitions.

**Comment by deanmarcussen** [comment]
I can't repro the property error from codemirror either.

The non-unique id is just a warning (which we could resolve), because that's how aspnet is generating the id's for the array (using `asp-for="the_array"`)

But the error you're seeing is probably the codemirror script for the `ContentTypeDefinition_FullTextTemplate` field.

can you see if you have an id for `ContentTypeDefinition_FullTextTemplate`
and see if this returns null in the console `document.getElementById('ContentTypeDefinition_FullTextTemplate')`

**Comment by jtkech** [comment]
Not sure so just for infos, after updating to a new version i already had this kind of issue, but i just needed to do a full rebuild of the web app. Then, if it doesn't work and you are working with the full source code, try to do a `git clean -xdf` under the root of your solution.

**Comment by dodyg** [comment]
@deanmarcussen 

![content-type-definition](https://user-images.githubusercontent.com/1761249/72445558-90bd6f00-37ba-11ea-98ba-276410b992d3.png)

**Comment by deanmarcussen** [comment]
@dodyg weird. can you give me one more screen shot like below. I'm looking to see if you have the circled field rendered. (if you have it, can you check it's id as well)

![index](https://user-images.githubusercontent.com/13782679/72448730-69ad7000-37af-11ea-9ffb-ca954702dd5b.PNG)

**Comment by dodyg** [comment]
![content-type-definition-2](https://user-images.githubusercontent.com/1761249/72449166-e5fc7f00-37c0-11ea-97c2-0c5825767ddb.png)

**Comment by dodyg** [comment]
OK I found the problem. 

![found-the-problem](https://user-images.githubusercontent.com/1761249/72449396-412e7180-37c1-11ea-835d-98d1170940fb.png)

One of my module uses this. I didn't realize this impact globally. Is there anyway to isolate this just to the module?

**Comment by deanmarcussen** [comment]
ah, I see, but still it is weird.
the id that we're using there is generated with the helper `@Html.IdFor(x => x.FullTextTemplate)` so I would have thought it picked up any custom generator you had used.

maybe you can try your id generator with the `@Html.IdFor()` on a field and see what it generates?

I can't imagine there's an easy way to isolate this to just your module, unless you write a wrapper around it which uses the default generator on any module that isn't yours. 

But equally, as I said above, I would have imagined that `@Html.IdFor()` would also use the generator you have written, and generate

**Comment by dodyg** [comment]
Yeah @Html.IdFor uses the lower case id Html Generator hence broken scripts at admin.
