### ISSUE TITLE
Programmatically alter order of ContentParts within a ContentType Definition?

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#5265]
Hello,

Using the RC1 version.

I'm having to update one of our widget definitions using a migration. 

It's going from this:

```
            _contentDefinitionManager.AlterTypeDefinition("Container360", type => type
                .DisplayedAs("360 Container")
                .WithPart("TitlePart")
                .WithPart("WithDisplayRulesPart")
                .WithPart("FlowPart")
                .Stereotype("Widget"));
```

To This:

```
            _contentDefinitionManager.AlterTypeDefinition("Container360", type => type
                .DisplayedAs("360 Container")
                .WithPart("TitlePart")
                .WithPart("Container360SettingsPart")
                .WithPart("WithDisplayRulesPart")
                .WithPart("FlowPart")
                .Stereotype("Widget"));
```

Note, the `Container360SettingsPart` is after the `TitlePart`. However when the migration is applied, the `Container360SettingsPart` is displayed at the end of the part collection. To fix this I have to go into the Content Types in the admin portal and manually re-order the parts there.

Is there any way I can achieve the correct order with a migration?

**Comment by deanmarcussen** [comment]
use the `WithPosition` extension should allow you to set a position, e.g.
```
type.WithPart("TitlePart", part =>
{
    part.WithPosition("0");
});
```

you will probably want to set all the positions to be exact

**Comment by marlon-tucker** [comment]
Hi, 

I tried running the migration with this:

```
_contentDefinitionManager.AlterTypeDefinition("Container360", type => type
                .DisplayedAs("360 Container")
                .WithPart("TitlePart", part => part.WithPosition("0"))
                .WithPart("Container360SettingsPart", part => part.WithPosition("1"))
                .WithPart("WithDisplayRulesPart", part => part.WithPosition("2"))
                .WithPart("FlowPart", part => part.WithPosition("3"))
                .Stereotype("Widget"));
```

But the `Container360SettingsPart` was still appended to the end of the part collection.

**Comment by deanmarcussen** [comment]
Are you sure the migration ran?

This worked fine for me

```
    {
      "Name": "Container360",
      "DisplayName": "360 Container",
      "Settings": {},
      "ContentTypePartDefinitionRecords": [
        {
          "PartName": "TitlePart",
          "Name": "TitlePart",
          "Settings": {
            "ContentTypePartSettings": {
              "Position": "5"
            }
          }
        },
        {
          "PartName": "FlowPart",
          "Name": "FlowPart",
          "Settings": {
            "ContentTypePartSettings": {
              "Position": "3"
            }
          }
        }
      ]
    }
```

**Comment by marlon-tucker** [comment]
Strange, it does get run yes as I restore the database and confirmed the restored version doesn't have an entry for `Container360SettingsPart`. Are you using the RC1 version from nuget?

**Comment by deanmarcussen** [comment]
no I'm on dev. But I wrote that code just before RC1 and it hasn't changed, or had any issues (as far as I know).

Underlying the extension uses `builder.MergeSettings<ContentTypePartSettings>(x => x.Position = position)` so you can try that, and debug it to see what the value of the `_settings` `jObject` in the builder is after setting.

**Comment by marlon-tucker** [comment]
Found the issue, not found out the work around yet. 

My migration is being run before the system migration defined in `OrchardCore.ContentManagement.Records.Migrations` -> `UpdateFrom3`. This migration then deletes my positional changes.

**Comment by deanmarcussen** [comment]
ah, that might do it.

Change the `Order` in your startup to run later, i.e. `Order => 10` should probably resolve that.

**Comment by marlon-tucker** [comment]
Sorry how do you set the order? The property is read only.

**Comment by deanmarcussen** [comment]
in your `Startup` class 

`public override int Order => 10;`

I think this should override the registration order of the migration, meaning it should come in later in the sequence.

**Comment by marlon-tucker** [comment]
Doh ok that was pretty rookie of me. 

Yep that all works now. Thank you for your help @deanmarcussen

**Comment by jtkech** [comment]
The module startup methods are first ordered by module dependencies, then yes, between modules that don't depend on each other, we can adjust the ordering of `ConfigureServices()` and / or `Configure()` by overriding the `Order` and / or `ConfigureOrder` properties.

So, and for other reasons, try to just add in your `Manifest.cs` file a direct or transitive dependency on `OC.Contents`, as we do in many of our module manifest files.

    Dependencies = new [] { "OrchardCore.ContentTypes" }

Knowing that `OC.ContentTypes` depends on `OC.Contents`

**Comment by marlon-tucker** [comment]
Is there any reason not to have migrations internal to Orchard run first? To save on customer modules having to have explicit dependencies on Orchard modules in order for their migrations to work correctly.

I don't see this as an pre RC issue either, Orchard is going to have to have further migrations it needs to do in the future for whatever reason. When customers update to those versions it should be safe to assume the Orchard migrations will run first.

But thank you for the extra info, I think I'll do that instead of overriding `Order` as this particular module is shared with a number of our other modules so adding the dependency is neater.
