### ISSUE TITLE
Markdown in graphql

### ISSUE THREAD

**Issue by sallenkov** [OrchardCMS/OrchardCore#5266]
I wonder if i am missing something , but i couldn't make Markdown body appears in graphql, you will find attached the result of me query:
![image](https://user-images.githubusercontent.com/17978153/72257536-2ebf0700-360c-11ea-8f83-c3fac182c347.png)

And this is the content of Events;I tried markdownbody as part and field
![screencapture-dev-uaesme-digitalresearch-ae-Admin-Contents-ContentItems-4hjd2ryjpwcgr1f0jy8qzddc5q-Edit-2020-01-13-13_55_26](https://user-images.githubusercontent.com/17978153/72257638-67f77700-360c-11ea-9c88-9f538871af84.png)

**ps : ** when i target only eventItem i get the markdownbody
![image](https://user-images.githubusercontent.com/17978153/72258654-e7864580-360e-11ea-88fc-ff2b9f352738.png)

**Comment by sebastienros** [comment]
@carlwoodhouse any idea?

**Comment by carlwoodhouse** [comment]
@sebastienros honestly no .. will see if I can replicate .. id expect to at least be seeing null or some kind of error ....

**Comment by carlwoodhouse** [comment]
I assume here ‘description’ is a markdown field ?

**Comment by carlwoodhouse** [comment]
@sebastienros -

Honestly i don't seem to be able to replicate, tried setting up some contenttypes that look similar to this setup

types:
event 
* markdownbodypart
* markdown field description
* localizationpart

events 
* listpart (constrained to a list of event)
* localizationpart

first with no constraints
![image](https://user-images.githubusercontent.com/465424/73026104-b389fc00-3e28-11ea-911e-f3af9a612f04.png)

constrained by culture
![image](https://user-images.githubusercontent.com/465424/73026272-05328680-3e29-11ea-80e6-966f2ffd27d8.png)

aliasing constrained by culture ...
![image](https://user-images.githubusercontent.com/465424/73026424-4a56b880-3e29-11ea-8554-fe92f9fae860.png)

what version of ocore are you using @sallenkov ?

**Comment by sallenkov** [comment]
> I assume here ‘description’ is a markdown field ?

yes it is

**Comment by sallenkov** [comment]
> @sebastienros -
> 
> Honestly i don't seem to be able to replicate, tried setting up some contenttypes that look similar to this setup
> 
> types:
> event
> 
> * markdownbodypart
> * markdown field description
> * localizationpart
> 
> events
> 
> * listpart (constrained to a list of event)
> * localizationpart
> 
> first with no constraints
> ![image](https://user-images.githubusercontent.com/465424/73026104-b389fc00-3e28-11ea-911e-f3af9a612f04.png)
> 
> constrained by culture
> ![image](https://user-images.githubusercontent.com/465424/73026272-05328680-3e29-11ea-80e6-966f2ffd27d8.png)
> 
> aliasing constrained by culture ...
> ![image](https://user-images.githubusercontent.com/465424/73026424-4a56b880-3e29-11ea-8554-fe92f9fae860.png)
> 
> what version of ocore are you using @sallenkov ?

It works fine now,I don't know how, maybe i had an error within my object,i will reopen this issue if i reproduce it
