### ISSUE TITLE
GaphQL localized contentItem

### ISSUE THREAD

**Issue by sallenkov** [OrchardCMS/OrchardCore#5268]
Is there a way to get the ID of the same item in different language if it's available and not only the current  localization proprieties 
Example; i need english version of this event: 
![image](https://user-images.githubusercontent.com/17978153/72263736-beb77d80-3619-11ea-9324-9c966f293235.png)

**Comment by carlwoodhouse** [comment]
hmm; dont think so ... shouldnt be too bad to add in though!

**Comment by pbros** [comment]
Hello,

I would need something similar as well. 

Is there a way to at least get the contentids of the related localized items? For example, if I get a content item by alias, then I would get the IDs of the content items that localized that content item.

**Comment by sebastienros** [comment]
We need a query that can filter based on `localization.culture` and `localizationSet`, and also ensure we can get the localization set.
Also ideally a sub-property `localizationSet` that could be expanded with the other localizations. I don't think a data loader is necessary as usually you only look for one content item and its localization

**Comment by pbros** [comment]
If we add

```csharp
Field(x => x.LocalizationSet).Description(S["The localization set for your content item."]);
```
to here https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ContentLocalization/GraphQL/LocalizationInputObjectType.cs#L15

It would make the LocalizationSet available as a where clause in the GraphQL query.

That way, we would be able to handle this with 2 calls: 1 to get the base version and retreive the LocalizationSetId using the path for example, and the other to get the content item using the LocalizationSetId and the Culture

Ex:
```
query QueryA {
  page(where: {path: "abc"}) {
    localization {
      localizationSet
    }
  }
}
query QueryB{
  page(where: {localization: {localizationSet: "xxxxxxx", culture: "fr-CA"}}) {
    localization {
      localizationSet
      culture
    }
    displayText
  }
}```


What do you think?

**Comment by sebastienros** [comment]
That solves one of my recommendations, that's good. Do you want to create a PR? And at the same time adding an extra property to drill-down into other content items should be easy, like this example for Media:

```
    public class MediaFieldQueryObjectType : ObjectGraphType<MediaField>
    {
        public MediaFieldQueryObjectType()
        {
            Name = nameof(MediaField);

            Field<ListGraphType<StringGraphType>, IEnumerable<string>>()
                .Name("paths")
                .Description("the media paths")
                .PagingArguments()
                .Resolve(x => x.Page(x.Source.Paths));
            
            Field<ListGraphType<StringGraphType>, IEnumerable<string>>()
                .Name("urls")
                .Description("the absolute urls of the media items")
                .PagingArguments()
                .Resolve(x =>
                {
                    var paths = x.Page(x.Source.Paths);
                    var context = (GraphQLContext)x.UserContext;
                    var mediaFileStore = context.ServiceProvider.GetService<IMediaFileStore>();
                    return paths.Select(p => mediaFileStore.MapPathToPublicUrl(p));
                });
        }
    }
```

The second `Resolve` method could load all related content items, and it could accept a specific culture to only load one too, instead of the paging arguments.

**Comment by sebastienros** [comment]
if you want to do something in a single query, you need to create a new custom query (like `contentItem`, `blog`) that would only get a contentItemId, or a localizationSet, and a culture. Optionally a status (draft, published, ...)

**Comment by carlwoodhouse** [comment]
if its loading related contentitems it probably should use a dataloader @sebastienros @pbros

**Comment by carlwoodhouse** [comment]
i possibly need to understand how localization works better to know why we think this needs 2 queries ? as opposed to just loading the localized versions in a field that can be filtered (maybe this is what @sebastienros) is suggesting - though we should also allow it at the top level as suggested.

**Comment by carlwoodhouse** [comment]
i mean i really feel like id be wanting to write it more like this ..

```query QueryA {
  page(where: {path: "abc"}) {
    localization {
      set(culture: "fr-Ca") { // this would be contentiteminterface, or without the filter would return all in the set
         displayText
      }
     culture
    }
  }
}

**Comment by carlwoodhouse** [comment]
i mean if you wanted to get really funky that would also allow something like

```  page(where: {path: "abc"}) {
    localization {
      frenchCanadian: set(culture: "fr-Ca") { // this would be contentiteminterface, or without the filter would return all in the set
         displayText
      }
      englishGb: set(culture: "en-gb") { // this would be contentiteminterface, or without the filter would return all in the set
         displayText
      }
     culture
    }
  }
}```

etc

**Comment by sebastienros** [comment]
it's two queries because a localized content item is a different document, and you can only query the localized version if you get the localization set of the first content item.

You can use a data loader, but usually you want a localized item from a single content item, it's rare that you want to load the localized version of a bunch of content items, so I think it's not very necessary right now.

And to prevent the two queries we need a custom top level graphql query.

**Comment by pbros** [comment]
@sebastienros  I created PR #5384 using your recommendation of the second query. Take a look and let me know if it's ok.
