### ISSUE TITLE
Autoroute and Routes validation

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5269]
Is there a way to validate autoroute with non autoroute routes ?

We defined a route named `team/{*id}` in a module startup and a ContentItem with an autoroute of `team`. We were getting a 404. Maybe a warning or validation message would be useful. Not sure if this is possible though.

**Comment by sebastienros** [comment]
> We were getting a 404.

On which url?

**Comment by jptissot** [comment]
404 on the autoroute url. Basically it was hitting the module's route and that one was giving a 404

**Comment by deanmarcussen** [comment]
so the url that won (in terms of matching) was the defined route `team/{*id}` but that url produced a 404 because the route didn't have an id when it tried to bind against it?

**Comment by jptissot** [comment]
Yes

**Comment by Piedone** [comment]
So, the idea would be to display a validation message when saving a content item whose Autoroute path clashes with an existing route, right? What would happen if you add a route later and that clashes with existing content item paths?
