### ISSUE TITLE
GraphQL if MarkdownField is null

### ISSUE THREAD

**Issue by Sibren** [OrchardCMS/OrchardCore#5274]
Hi,

If I try to use GraphQL with a MarkdownField and it contains nothing, it gives me errors:
`"errors": [
    {
      "message": "GraphQL.ExecutionError: Error trying to resolve html.\r\n ---> System.ArgumentNullException: Value cannot be null. (Parameter 'markdown')\r\n   at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline)\r\n   at OrchardCore.Markdown.GraphQL.MarkdownFieldQueryObjectType.ToHtml(ResolveFieldContext`1 ctx) in C:\\projects\\orchardcore\\src\\OrchardCore.Modules\\OrchardCore.Markdown\\GraphQL\\MarkdownFieldQueryObjectType.cs:line 39\r\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)\r\n   --- End of inner exception stack trace ---",
      "locations": [
        {
          "line": 20,
          "column": 39
        }
      ],
      "path": [
        "contentItem",
        "bag",
        "contentItems",
        "1",
        "intro",
        "html"
      ],
      "extensions": {
        "code": "ARGUMENT_NULL"
      }
    }
  ]
}`

Can it return null, or do I need to adjust my GraphQL-code?

**Comment by sebastienros** [comment]
Do you want to submit a PR? The stacktrace describes exactly what to fix.

**Comment by carlwoodhouse** [comment]
PR Submitted
