### ISSUE TITLE
Unable to call Post Method of OrchardCore Custom Module

### ISSUE THREAD

**Issue by vikaspol** [OrchardCMS/OrchardCore#5280]
I have created the custom Registration module for business need. 
Created the form in admin section, added the action name, selected the post method. 
Added the input fields and submit button.  Published Page. Now opened the page and filled all field of the form and clicked on submit, It Postback and call the custom module post method.
Now, I want to call the same method using Ajax. but not succeed. Could you please suggest any solution.

**Comment by sebastienros** [comment]
You are probably missing the antiforgery token in the post request.
