### ISSUE TITLE
Widget settings in OrchardCore

### ISSUE THREAD

**Issue by vikaspol** [OrchardCMS/OrchardCore#5281]
How can we add the widget size to (10, 20, 40, 60)% in admin section. currently it has (25, 33, 50, 66, 75, 100)%. Please suggest the solution for that.

**Comment by ns8482e** [comment]
In most cases 25, 33, 50, 66, 75, 100% is enough, However you need to define your own values you can do that by creating your own admin theme.

Override FlowMetadata_Edit shape by creating FlowMetadata.Edit.cshtml in your admin theme. See https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Flows/Views/

You also need to provide your own CSS for each values that you define

**Comment by vikaspol** [comment]
Great!! Thanks so much for your valuable help.
