### ISSUE TITLE
Custom Api Related Stuff

### ISSUE THREAD

**Issue by vikaspol** [OrchardCMS/OrchardCore#5283]
I have a running portal. I want to show the content of the portal in OrchardCore Cms site. Also want some registration,booking, tracking functionality. To cover all this should I required to create orchard core module or it can be manageable with Html, ContentPart, ContentType and Ajax with help of custom API for getting content?

**Comment by sebastienros** [comment]
There is already some graphql endpoints to get the content.
Registration is supported.
The rest will require a custom module for now.
