### ISSUE TITLE
Difference between Api Validation when using PUT/GET

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#5286]
Hey, I'm using several custom controllers to provide several APIs that are attached as modules to Orcahrd. To use authorization I'm using the OpenID validation scheme "Api" that is provided by Orchard.

When using the "Api" authentication scheme requests made using the HTTP method 'GET' return a 401 status code when no JWT token is provided. However when the method is 'PUT' a 400 is returned instead.

**Comment by carlwoodhouse** [comment]
Have you also used the IgnoreAntiForgery attribute on the `PUT` ? as it will need it; its probably throwing the 400 because it cant find an AF token.

**Comment by nuno-tiago-reis** [comment]
I'm using IgnoreAntiForgery  on the controller so it should be applying to every method.

**Comment by sebastienros** [comment]
From the client, you need to set a AFT value in the payload so that the controller which ensures it's there can find it.
