### ISSUE TITLE
Having some trouble using asp-append-version in custom module

### ISSUE THREAD

**Issue by cocoke** [OrchardCMS/OrchardCore#5287]
Hello, 

I'm trying to use `asp-append-version` for a css file localized inside the wwwroot folder in a custom OrchardCore module.

Code from the cshtml in the Views folder inside the module:
`<link rel="stylesheet" asp-src="~/Module.name/style.css" asp-append-version="true" />`

When I try to make a change inside the css file, the token don't change, event after a tenant reload.
So the css changes are applied only if I clear the site cache (CTRL + F5)

Do I need to specify this specific folder/file to be watched ? And how to ?

**Comment by jtkech** [comment]
Hmm, maybe you are not using our link tag helper but the mvc one, did you add the `OC.ResourceManagement` tag helpers in your module `_ViewImports` and then did you reference `OC.ResourceManagement` in your module project file?

**Comment by cocoke** [comment]
> Hmm, maybe you are not using our link tag helper but the mvc one, did you add the `OC.ResourceManagement` tag helpers in your module `_ViewImports` and then did you reference `OC.ResourceManagement` in your module project file?

Yes, both of them are present and I even tried to remove the mvc one to be sure but without success :

![image](https://user-images.githubusercontent.com/6980626/72417340-fa1c8e00-3778-11ea-8a7c-5d07ffec0516.png)

![image](https://user-images.githubusercontent.com/6980626/72417410-1caea700-3779-11ea-9692-41d602f17277.png)

**Comment by deanmarcussen** [comment]
I assume you are getting a version appended when you use the tag helper?

We wrote it to work with both the mvc tag helpers, and the Orchard Core `<style>` tag helper which offers some better features, but it should work with both.

Is it just not refreshing when the file has changed?

Is you environment `Development` ?

The watcher should automatically kick in, but I think only will work in `Development`

**Comment by cocoke** [comment]
Yes, a version is present but it don't take changes into account, the token appened by the AppendVersion is still the same even after a tenant reload 😞 

My environment is well puted on `Development`

**Comment by deanmarcussen** [comment]
@jtkech it's been so long since you helped me with this but I don't think the `ModuleProjectStaticFileProvider` for development supports watchers (as in it returns a `NullChangeToken.Singleton`)

I think when we did this we acknowledged that it wouldn't watch local module files, but that it would watch files served from `App_Data`, i.e. Media files

@cocoke if I remember correctly the intention was more to cache bust in production, not so much development.

But we maybe able to implement a watcher on the `ModuleProjectStaticFileProvider` perhaps

**Comment by jtkech** [comment]
@cocoke  @deanmarcussen oh yes we missed this one.

Watching is already done for `ModuleProjectRazorFileProvider` and `ModuleProjectLiquidFileProvider` to support runtime razor compilation on change. But originally it was not required for static files.

Quite busy right now but i will do a PR soon.
