### ISSUE TITLE
Multi-tenant MVC setup

### ISSUE THREAD

**Issue by fenngineering** [OrchardCMS/OrchardCore#5297]
Hello, I'm new to Orchard so please be kind ;)

Correct me if i'm miss reading the documentation, this is what i'm trying to setup.

"A MVC multi-tenant CMS, which will be used to run 2 independent blogs from the same application"

Right so I've completed the installation following the automated method. And everything spins up as expected ie. http://<server>:<port>/blog1 - (goes to mod1 \home\index); http://<server>:<port>/blog2 - (goes to mod1 \home\index)

The issue I have is that I can not setup each blog what so ever. All that is displaying is the home\index of the module. If i browse to http://<server>:<port>/blog1/admin i get "page cannot be displayed"

What I expected is when I go to http://<server>:<port>/blog1 I would be presented with the setup of blog1. And vise versa for blog2.

I have a Web App and a Module App. 

This is what I have configured to the modules app:- (this uses OrchardCore.Module.Targets)
1) Added the routing to the home\index - this works perfectly
2) Added the code for the Admin Menu.

This is what I have configured for the web app:- (this uses OrchardCore.Application.Mvc.Targets)
1) Added the tenants to the appsetting.json file and added the modules to the features.
2) Modified the startup.cs to include services.AddOrchardCore().AddMvc().WithTenants(); &  app.UseOrchardCore(); to the correct methods.

The app starts and then I can navigate to each tenants \home\index page but I am not presented with the setup of the tenants.
 
What am i doing wrong?

Thanks
Andy

**Comment by Skrypt** [comment]
Remove any custom routes you made and test it back.

**Comment by fenngineering** [comment]
@Skrypt Thanks for your reply, this throws an exception:-
![image](https://user-images.githubusercontent.com/35530714/72551195-44426400-388c-11ea-8a11-a6aee27f7305.png)

**Comment by fenngineering** [comment]
I have added my code to github if you want to check what I have done? 

https://github.com/fenngineering/FennasCMS

**Comment by jtkech** [comment]
Yes, with `OrchardCore.Application.Mvc.Targets` and 1st following what is done in `OrchardCore.Mvc.Web`, you can then build many things but it's a little like starting from scratch. Also `.WithTenants()` is intended to be used with preconfigured tenants with a fixed set of features.

To have a more complete CMS experience you could rather use `OrchardCore.Application.Cms.Targets` and follow what is done in our `OrchardCore.Cms.Web` application, not the `OrchardCore.Mvc.Web` sample. Then in the admin you will be able to enable the `Tenants` feature and then you will be able to add tenants and setup them.

Maybe the name of the `OrchardCore.Samples` folder is confusing, the main sample being the `OrchardCore.Cms.Web` sample that is not in this folder

**Comment by fenngineering** [comment]
Thanks for your reply. I have managed to get the SaaS setup for the default tenant. However there are no menus available on the page though. It’s completely blank. Now my issue is how do I add the menus for the admin page so I can add multiple tenants and configure the default tenant ?

**Comment by fenngineering** [comment]
I am presented with this, i'm scratching my head now...
![image](https://user-images.githubusercontent.com/35530714/72643264-319c5d80-3966-11ea-850c-d245c301f2d6.png)

**Comment by jtkech** [comment]
Delete the `App_Data` that has been created so that you can re-do a fresh setup, then rather choose the `Blog` recipe in place of the `Saas` ;)

**Comment by Piedone** [comment]
Please reopen if you still have questions.

**Comment by rafaelmohedano** [comment]
> Yes, with `OrchardCore.Application.Mvc.Targets` and 1st following what is done in `OrchardCore.Mvc.Web`, you can then build many things but it's a little like starting from scratch. Also `.WithTenants()` is intended to be used with preconfigured tenants with a fixed set of features.
> 
> To have a more complete CMS experience you could rather use `OrchardCore.Application.Cms.Targets` and follow what is done in our `OrchardCore.Cms.Web` application, not the `OrchardCore.Mvc.Web` sample. Then in the admin you will be able to enable the `Tenants` feature and then you will be able to add tenants and setup them.
> 
> Maybe the name of the `OrchardCore.Samples` folder is confusing, the main sample being the `OrchardCore.Cms.Web` sample that is not in this folder

I am working on the Decoupled CMS model, including only the` OrchardCore.Application.Cms.Core.Targets` package.
In order to dynamically create and manage tenants, would I have to use the Full model? Can I just include the `OrchardCore.Application.Cms.Targets` package and continue development as I describe in the documentation? (Https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/)

**Comment by Piedone** [comment]
It's better to open a new discussion than to revive a closed issue :).

No, what you have should be enough to create tenants.
