### ISSUE TITLE
React (spa) template as a module

### ISSUE THREAD

**Issue by abdurahmanus** [OrchardCMS/OrchardCore#5298]
I'm trying to create a modular app using standard ASP.NET Core Web Application template with React.js from Visual Studio Community 2019 as a module. This template has lots of boilerplate code in Startup class with stuff such as app.UseSpaStaticFiles(); and app.UseSpa(...). 
Is it really possible to make it work?

**Comment by deanmarcussen** [comment]
see the example from this issue https://github.com/OrchardCMS/OrchardCore/issues/5227
