### ISSUE TITLE
Fix DefaultUserClaimsPrincipalFactory to use ClaimValueTypes.Boolean for email_verified

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#5307]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Users.Core/Services/DefaultUserClaimsPrincipalFactory.cs#L39

Since it doesn't have the appropriate value type, this claim is not correctly serialized when it is copied to a JWT access token. E.g:

![image](https://user-images.githubusercontent.com/6998306/72570663-c9923c80-38bd-11ea-85f6-04e03bf3779b.png)

**Comment by dborovsky** [comment]
@PinpointTownes  I would like to solve this issue. I will do PR.

**Comment by dborovsky** [comment]
@PinpointTownes  I would like to do this task. I can't catch this bug. Where can I find logic to test it?

**Comment by timlunev** [comment]
@kevinchalet @sebastienros could we close the issue?
