### ISSUE TITLE
TitlePart - create setting to make it required

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#5315]
Hi all, 

I have see that from a couple of months TitlePart is not required when you insert or edit a new content item. Can I add a checkbox in the TitlePart settings to allow this field to be required if it is editable?

If you allow me, I can do a PR with this modify and the code to fix this issue https://github.com/OrchardCMS/OrchardCore/issues/5036

**Comment by ns8482e** [comment]
I suggest you to use some other Field as required field and use TitlePart with liquid template to assign display text to a content item.

**Comment by sebastienros** [comment]
I think we still need this feature. We might have lost this with the PR that added templated values.
