### ISSUE TITLE
Menu Preview

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5317]
When you edit a menu, open the preview window and order the menu items, the menu is not updated on the preview.

**Comment by sebastienros** [comment]
Maybe just remove the preview button for the menu (placement) or have some way to customize which page to use (homepage) as the menu is not displayed directly, or need more context as it's usually embedded in a very specific zone, and not the Content zone.

Well, we already have something called PreviewPart which might solve that, by setting the page to open on Menu (`/`)

**Comment by agriffard** [comment]
It does not work when you add a PreviewPart with `/` in the pattern of the autoroute preview.

How can you remove the Preview button form a specific Content type?

**Comment by Skrypt** [comment]
I think you need to remove it from the shape in the controller/driver that returns it, or in the view.

**Comment by sebastienros** [comment]
placement file 
https://docs.orchardcore.net/en/dev/docs/reference/core/Placement/#placement-files

But if it exists in placement files then it's available by code, either with a predicate, or a custom placement rule.
