### ISSUE TITLE
Lucene : SearchShapes

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#5320]
Would be nice to have a basic SearchShape.
I'm creating this issue for keeping track of the feature.

**Comment by RNovachkov** [comment]
Hello, I am trying to implement custom liquid template for the "/search" View page (OrchardCore.Lucene/Views/Search/Index.cshtml). According the "How to" documentation I need SearchResults.liquid file in my Theme/Views folder. Is there a problem or I miss something from the docs.

**Comment by jtkech** [comment]
Because it's not a shape but an mvc view tied to a controller, as i remember try

    Theme/Views/OrchardCore.Lucene/Search/Index.cshtml

But maybe you have better to override `Search-Form.cshtml` and `Search-Results.cshtml` that are shapes so just under your theme views folder.

**Comment by RNovachkov** [comment]
Thank you @jtkech, for your response. My colleague found It, couple of hours after I posted my comment. It is **"(Theme)/Views/OrchardCore.Lucene/Search/Index.liquid"**

**Comment by Skrypt** [comment]
Actually you are probably running on RC1 and not latest dev that's why the doc is not accurate for you. You need to be on latest dev to be able to use the latest bits.
