### ISSUE TITLE
Enforce unique username and email address for registration?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#5323]
Dear all,

It would be great to have a feature that when registering a new user, both UserName and Email will be checked for uniqueness.

Currently, only the UserName get checked, and multiple users could use the same email address to register.

Can we enforce it as a setting? Will it available in the 1.0 release?

**Comment by jptissot** [comment]
It is already possible, please use this in your web project Startup

```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
            services.Configure<IdentityOptions>(options =>
            {
               options.User.RequireUniqueEmail = true;
            });
        }
```

**Comment by orchardc** [comment]
Thanks @jptissot ,

I tried it works, however, the default error message is "Unexpected error: 'DuplicateEmail'."

How to make a custom error message, so more user-friendly?

**Comment by orchardc** [comment]
Any update on this question ?

**Comment by sebastienros** [comment]
This needs to be added here:
https://github.com/OrchardCMS/OrchardCore/blob/5ed3e9c3ccc4517399e16c569da4a6cd101c7de3/src/OrchardCore/OrchardCore.Users.Core/Services/UserService.cs#L236

And then we will be able to customize it with localization files.
We should also check that there is no other new value that should be handled.

**Comment by agriffard** [comment]
From the admin, there is an email existence check:
https://github.com/OrchardCMS/OrchardCore/blob/791f8552e8fa56c84f5a3beca4ba3b656691bf12/src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserDisplayDriver.cs#L122
