### ISSUE TITLE
Named BagPart - Templates - unable to create shape for display it

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#5327]
Hi guys, 

I'm trying to create a shape to render a BagPart in the same way because the same type of object is associated to many of my content types. 
I have named my BagPart Pluto and I have created this shape files: 
```
Arg-Pluto.liquid
BagPart-Pluto.liquid
BagPart.liquid
Pluto.liquid
```
(Arg is the name of one contenttype that contains the BagPart).
I have inserted a test text to see if one of the templates works, but this test text is not showed. 
I have test this liquid code: 
```
{{ Model.Content | shape_render }}
```
And it shows all the shape but not render the BagPart's one.
I have used the code: 
```
{% for shape in Model.Content.Items %}
  {{ shape }}<br/>
{% endfor %}
```
To see which kind of class I can find inside the Model and it display the class name `Castle.Proxies.BagPartViewModelProxy` between all the classes.

What I'm doing wrong?

(Related: https://github.com/OrchardCMS/OrchardCore/issues/4841)

**Comment by sebastienros** [comment]
TODO: test and document how to customize the template for a BagPart, and a named BagPart.
