### ISSUE TITLE
Pager Shape in Liquid

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#5331]
Perhaps I am missing something obvious, but it seems the "Pager" shape should be able to be rendered via Liquid (i.e. generating a new shape - I know it can be altered from the List). Here are my code snippets:

```
<h2>Pager Slim</h2>
{{ "PagerSlim" | shape_new: before: "12345", after: "78910", pageSize: 10 | shape_render }}

<h2>Pager</h2>
{{ "Pager" | shape_new: page: 5, pageSize: 10, defaultPageSize: 100 | shape_render }}
```

Pager Slim renders fine, but Pager doesn't render anything. I have looked through the code, and tried to even debug, but am not sure why "Pager" doesn't output anything...

**Comment by Skrypt** [comment]
Maybe you are missing totalcount?

**Comment by jeffolmstead** [comment]
Tried adding it in:

```
<h2>Pager (unstyled)</h2>
{{ "Pager" | shape_new: page: 5, pageSize: 10, defaultPageSize: 100, totalCount: 100 | shape_render }}
```

Still didn't work. Too bad. It seems it should work, just can't find all the parameters / where it is failing in the code.

**Comment by Skrypt** [comment]
TotalItemCount

**Comment by jeffolmstead** [comment]
@Skrypt I owe you one! That solves my problem 2 ways:

1. I can now use the Pager shape
2. I had forgotten it resolves to "Pager_Links" which is why I was missing the required parameter

Thanks so much!

**Comment by Skrypt** [comment]
We need documentation

**Comment by Skrypt** [comment]
https://docs.orchardcore.net/en/dev/docs/reference/modules/Navigation/#pager
Already documented

**Comment by adrianyadav** [comment]
@jeffolmstead  Do you have any code examples with using the pager?  I got mine to appear using
`{{ "Pager" | shape_new: page: 5, pageSize: 10, defaultPageSize: 100, totalItemCount: 100 | shape_render }}

however clicking on any page number doesn't work 
`

**Comment by jeffolmstead** [comment]
@adrianyadav sorry, I have been away from the project for about 5 years and am not sure what I presented above still works with the current release. Wish I could be of more assistance.
