### ISSUE TITLE
error showing when try to add New Razor Page

### ISSUE THREAD

**Issue by ziyadsv** [OrchardCMS/OrchardCore#5338]
When i tried to add new Razor Page under Page Folder.Its Showing Error..

There was an error running the selected code generator:
'Pacckage restore Failed'

**Comment by sebastienros** [comment]
Can someone confirm?

**Comment by jtkech** [comment]
Just tried to add a page under the app, then under a module, both work.

Seems rather to be a package restore issue when trying to compile the new items.

**Comment by Skrypt** [comment]
Or the project itself is not having `<Project Sdk="Microsoft.NET.Sdk.Razor">`

**Comment by jtkech** [comment]
Yes

Or `Sdk.Web` if at the app level

**Comment by ziyadsv** [comment]
I miss the <Project Sdk="Microsoft.NET.Sdk.Razor"> . thank you
