### ISSUE TITLE
Broken default routing to the Index.cshtml 

### ISSUE THREAD

**Issue by ivpdotnet** [OrchardCMS/OrchardCore#5342]
In the PageConventionCollectionExtensions was changed the part of code where we check the template of routes. Now its looks like:

`var areaFolder = areaName + folderPath;                                            `
`...                                                                                                           `
`var route = selector.AttributeRouteModel;                                          `
`...                                                                                                           `
`if (route.Template.StartsWith(areaFolder, StringComparison.Ordinal))`

In this case we lost route to the Index page by default (`http://yourdomain.com/`) and can reach the Index page only browsing `http://yourdomain.com/index` .

Area folder route for the root of module sets in the class ModularPageRazorPagesOptionsSetup: 

`// Add a custom folder route to serve the application's module pages from the root.             options.Conventions.AddAreaFolderRoute(_applicationContext.Application.Name, "/", "");` 

where `_applicationContext.Application.Name` is `areaName` and `/` is `folderPath`. 

Index page has two routes defined one for the file without extension and one with empty string represinting the file. So, last one will never be reached because route to the file by default is just `areaName` without slash. Looks like we try to compare ` 'AreaName'.StartsWith('AreaName/') ` what always false

**Comment by jtkech** [comment]
Okay i will fix it, thanks for the feedback
