### ISSUE TITLE
Connecting to same database after restarting container with OrchardCore fails

### ISSUE THREAD

**Issue by Ujinjinjin** [OrchardCMS/OrchardCore#5344]
Hello, I am currently looking for a way to connect to the same database after restarting docker container with OrchardCore. I am using MS Sql Server as external database.

As was suggested [here](https://stackoverflow.com/questions/4781063/where-to-change-the-database-connection-settings-in-orchard-mvc-cms) I tried to place `settings.txt` with following content:

```
Name: Default
DataProvider: SqlServer
DataConnectionString: Data Source=servername;Initial Catalog=dbname;User Id=username;Password=password;
```

into folder `App_Data\Sites\Default`. Also tried to configure CMS and then look into containers file system and found database connection strings in `App_Data\Sites\Default\appsettings.json`, tried to place it there on container build, but still, Orchard shows Setup page on every start.

So, how do I connect to the same database after I restart my container?

**Comment by deanmarcussen** [comment]
`settings.txt` is very old now, so you do want to be looking for the `appsettings.json` file - that's what it was replaced with.

However you'll also want all of the other `App_Data` content, inc `tenants.json` and the data protection keys.

**Comment by Ujinjinjin** [comment]
@deanmarcussen thanks for your reply, I also replaced `appsettings.json`, but it seemed like it was overridden after container start. But I figured it finally out: i had to bind App_Data folder to path outside of container. So basically, had to start container with following command:

`docker run -p IP_ADDRESS:PORT:80 -d --mount type=bind,source=/local/path,target=/in_container/path IMAGE_ID`

**Comment by deanmarcussen** [comment]
great, for info you can also pass the `ORCHARD_APP_DATA` path through as an environment variable

http://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/
