### ISSUE TITLE
Execute Recipe by importing a file from admin

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5346]
Goal: Provide a way to import a recipe file from the admin and execute it.

Currently, a harvester is in charge of gathering all the *.recipe.json files in every modules and the UI list them and allows to execute a recipe.

**Comment by agriffard** [comment]
Adding a *.recipe.json in the App_Date\Sites\Default\Media\Recipes folder doesn't make it appear in the recipes.

In which folder should we import a recipe file?

**Comment by deanmarcussen** [comment]
How is this different from using `Package Import`? 
In the Import / Export

I think the harvester only looks like assemblies for recipes.

**Comment by agriffard** [comment]
Ok, that is a start.
It is just that it is a bit less straightforward because you can only import a zip file that contains a Recipe.json file inside.

**Comment by Skrypt** [comment]
Make it detect if it's a zip file or not.

**Comment by jtkech** [comment]
For infos there is an `ApplicationRecipeHarvester` so normally you can use a `/Recipes` folder under the application root.

**Comment by agriffard** [comment]
Reminder: check file name and add instructions hint to import
