### ISSUE TITLE
Export a Content in json

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5348]
Goal: Provide an Export action in the content items list that generates a {contentid}.recipe.json file with the appropriate structure and deployment step that you can then import thanks to the Recipes page.

**Comment by agriffard** [comment]
If you can select multiple content items and export them in one file with a batch action, that is even better.

**Comment by deanmarcussen** [comment]
It would be great to be able to add content to a deployment queue, so you could batch up multiple selections into one queue (deployment destination, be it file or a remote deployment source).
