### ISSUE TITLE
ListPart: Improve admin UI

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5349]
Implement a similar UI for the items of a ListPart than the one used for the content items:

- Checkboxes and batch actions
- Pagination (at least number of items)
- Search?
- Filters?

**Comment by carlwoodhouse** [comment]
it would be nice if you could also attach an existing item to a list rather then having to create a new one (or maybe you can already and i can't find it in the ui!)

**Comment by sebastienros** [comment]
Quick note that displaying (actually retrieving it) the number of items is bad for perf as it makes SQL count all of them. For lists that might be fine.

**Comment by agriffard** [comment]
> it would be nice if you could also attach an existing item to a list rather then having to create a new one (or maybe you can already and i can't find it in the ui!)

See #2299

**Comment by hishamco** [comment]
Can I try this if I have a time?

**Comment by agriffard** [comment]
Sure you can. 
I am just warning that it won't be as easy as the other admin pages and could be limited by the current implementation.

I'd love to see a Numeric Pager instead of the Previous/Next one for a List.

**Comment by hishamco** [comment]
So what's your suggestion?

**Comment by agriffard** [comment]
I don't have any suggestions. I said it is complicated.
