### ISSUE TITLE
Add BindNever attribute to ShapeViewModel properties

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#5351]
It might not be the best approach to use model updater on a ShapeViewModel but still it's a valid option if you want to render an editor using a view model inherited from ShapeViewModel to keep its capabilities. Also we could restrict the model updater to update only our newly added properties in the inherited class but we don't know for sure how the developers will use it.
I think it would be safer to add [BindNever] attributes to ShapeViewModel properties so the users can't post ShapeViewModel-specific field values after intentionally changing DOM such as "Metadata.Type".

**Comment by Skrypt** [comment]
Makes sense. Though is it causing an actual issue if we change this value? Maybe someone could intentionally wants to shape morph a shape?

**Comment by barthamark** [comment]
Yes that was exactly my thought.

**Comment by sebastienros** [comment]
I will need a more concrete example to understand the issue, show me some html please.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
