### ISSUE TITLE
Unable to login to in admin after upgrade from 1.0.0-beta3-72408 to 1.0.0-rc1-11643

### ISSUE THREAD

**Issue by xumix** [OrchardCMS/OrchardCore#5356]
Just after trying to login I'm receiving this:

`An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.`

`C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Users\Views\Account\Login.cshtml
Cannot implicitly convert type 'OrchardCore.Users.Models.UserRegistrationType' to 'bool'`

```
<input asp-for="RememberMe" class="form-check-input" tabindex="3" />
                    <label asp-for="RememberMe" class="form-check-label">@T["Remember me"]</label>
                </div>
                @await RenderSectionAsync("AfterLogin", required: false)
                <div ></div>
                <button type="submit" class="btn btn-primary" tabindex="4">@T["Log in"]</button>

>>>>>>>                @if (userCanRegister) <<<<<<<<<============= here
                {
                    <div class="mt-4">
                        <a asp-controller="Registration" asp-action="Register" asp-route-returnurl="@ViewData["ReturnUrl"]">@T["Register as a new user"]</a>
                    </div>
                }
            </form>
```

**Comment by deanmarcussen** [comment]
have you upgraded to visual studio 2019 - the latest? to support .netcore3

Can you try a dotnet clean?

**Comment by xumix** [comment]
Yeah, I've tried deleting bin/obj folders, also I launch as Debug from latest VS2019

**Comment by deanmarcussen** [comment]
ok, I see where the issue must have come from.

The `UsersCanRegister` setting was changed from a bool to an enum in https://github.com/OrchardCMS/OrchardCore/pull/3488 and you must have (at some point enabled the User Registration feature and have the old bool in the Settings document, so you're getting a Json error converting it.

The only fix I can recommend is to edit your settings Document in the database.
In the Document table there will be a record listed as Type
`OrchardCore.Settings.SiteSettings, OrchardCore.Settings`

Edit this and convert the `UsersCanRegister` property from `false` (or `true`) to a value from the enum (0,1, or 2)

**Comment by xumix** [comment]
@deanmarcussen I suppose the error is not in the settings but in the VIew, since the setting is converted as Enum but the View expects a boolean.

**Comment by deanmarcussen** [comment]
I can't repro. 

You are using myget packages not the source code directly?

**Comment by xumix** [comment]
@deanmarcussen Yes, I've used myget packages. I've downgraded to 1.0.0-rc1-10004 and the issue is gone

**Comment by sebastienros** [comment]
You have such an old site settings that I would suggest to update the settings manually in the database, in the Documents table, finding the record with type `SiteSettings`, then change the property to a valid number or string.

**Comment by xumix** [comment]
But why is there no upgrade path here? The rc1version  works

**Comment by xumix** [comment]
@deanmarcussen wtf, why is there no upgrade path? Also there is no such property in `OrchardCore.Settings.SiteSettings`, it is located in `OrchardCore.Users.Models.RegistrationSettings` but there is not such setting in my databse

**Comment by Skrypt** [comment]
That's the tradeback from living on the edge of a software that is in dev. We don't make all migrations automatic. Once we get to 1.0 it will be taken more seriously moving forward. But for now, to make things go faster we don't.

**Comment by deanmarcussen** [comment]
Please look at the instructions I gave above (and again below)

> The only fix I can recommend is to edit your settings Document in the database.
In the Document table there will be a record listed as Type
OrchardCore.Settings.SiteSettings, OrchardCore.Settings

> Edit this and convert the UsersCanRegister property from false (or true) to a value from the enum (0,1, or 2)

Or post the contents of it here

Crucially you will find the registration settings saved in the database under the type `OrchardCore.Settings.SiteSettings`. that is how YesSql works with `IEntity` properties

I can't reproduce your issue, so until we can understand it, we cannot make an upgrade path

**Comment by xumix** [comment]
I apologize, somehow Rider got old dlls/pdbs into the build dir even after nuget updates and clean. Now it is fixed.

**Comment by deanmarcussen** [comment]
Glad you got it sorted
