### ISSUE TITLE
Question: Which VPS better to run Orchard core?

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5360]
I'm interested to know Linux or windows VPS better to run several OC websites?
currently, I'm using windows VPS and it works great, so what do you think about Linux VPS?

if Linux is effective, what tools and Softwares I need to install?

**Comment by sebastienros** [comment]
If you are using Sqlite, Linux seems to perform better, otherwise Windows is usually faster for dotnet apps. (It's my job to measure these things).

**Comment by aghili371** [comment]
i have https://www.fairintheair.de/ in Linux and http://fckia.com/ in windows VPS.both using SQLite.
both look fast. 
but for myself windows in easier to manage.
unfortunately,  windows is expensive to have more storage and resources.

do you have any good help to run a stable and secure Linux server for the .netcore Webhosting server?
thank you for @sebastienros for feedback.

**Comment by hishamco** [comment]
> do you have any good help to run a stable and secure Linux server for the .netcore Webhosting server?

May be this question is better forwarded to AspNetCore repo, or you can find a useful information in the AspNetCore Docs
