### ISSUE TITLE
Required attribute for the filed that was true could not set to false

### ISSUE THREAD

**Issue by artemsv** [OrchardCMS/OrchardCore#5369]
The field was required. And the site was deployed. I have changed the field to be non Required, but it was not changed when I imported package taken from local env (where it is already non Required) to the deployed to the Internet site. I am sure I have exported the fullest deployment plan that is possible - All Content, All features etc.

**Comment by sebastienros** [comment]
What you mean is that the field settings are lost when exporting/importing them? Did you export using a Deployment Plan as a file?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
