### ISSUE TITLE
Role Names are capitalized when imported

### ISSUE THREAD

**Issue by artemsv** [OrchardCMS/OrchardCore#5371]
Imported 
![image](https://user-images.githubusercontent.com/1922262/73128902-09f16900-3fe8-11ea-94c8-da285d59cdc1.png)

Sourse
![image](https://user-images.githubusercontent.com/1922262/73128909-2a212800-3fe8-11ea-81b4-6e035b036c5b.png)

**Comment by artemsv** [comment]
I see that in the receipe.json to import all roles are in capital case

![image](https://user-images.githubusercontent.com/1922262/73128920-6b193c80-3fe8-11ea-9740-45fead6b811b.png)

So it means it capitalizes only new roles that are created by the import...

**Comment by agriffard** [comment]
This is because the RoleName is stored in UpperCase in the database.

**Comment by Skrypt** [comment]
Normalized in UpperCase

**Comment by sebastienros** [comment]
Sure it's normalized for querying, but we must have the original data somewhere as we display it correctly in the UI. And this is what should be exported.

**Comment by Skrypt** [comment]
Right I miscliked the wrong button simply.
