### ISSUE TITLE
Multiple Layout pages

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5375]
How do I make multiple layout pages and then tell a template which layout to use?

**Comment by dodyg** [comment]
In your theme just create another layout e.g. layout2.liquid

Then you can use the `{% layout %}` tag as specified [here](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Liquid/#layout-tags)

**Comment by JoshTango** [comment]
Where do I put this tag?  I tried putting it in the content template at the top but it did not work?

**Comment by JoshTango** [comment]
ok I got it to work finally

**Comment by JoshTango** [comment]
I agree with the feature request to make a layout part

**Comment by remesq** [comment]
@JoshTango, can you share how you got multiple layout pages to work by using the {% layout %} tag? I'm assuming you used in a template (either Admin created, or a .liquid/.cshtml file in your theme), but I just wanted to know if you had a Content Template, what you inserted there to get it to work.

**Comment by JoshTango** [comment]
I used:
{% layout "Layout2" %}
at the top of the content page for my content type.
