### ISSUE TITLE
How to create admin Theme?

### ISSUE THREAD

**Issue by kyahyan** [OrchardCMS/OrchardCore#5380]

**Comment by deanmarcussen** [comment]
Create a theme following this guide https://orchardcore.readthedocs.io/en/dev/docs/getting-started/theme/

In the `Manifest.cs` file add the following property `Tags = new [] { "admin" }`

You can also specify that the existing admin theme is used as a base theme with the property
`BaseTheme = "TheAdmin"` which is also placed in the `Manifest.cs`

Leaving this open as we should add this to the docs
