### ISSUE TITLE
Admin controllers being rendered using site theme

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#5387]
This appears to be an issue with controllers with the name `AdminMyTypeController` rather than just `AdminController`.

Can reproduce by:

1. Adding a controller `AdminItemController` to the Demo project and return a simple view from `Index` action.
1. Update one of the admin menu items to use the `AdminItemController` rather than `AdminController`.
1. Access the updated admin menu item will result in the `Index` action page being rendered using the site theme, not the admin area theme with the admin menu.

**Comment by jtkech** [comment]
Yes, as said on gitter the convention now is that the controller name is equal to `Admin` or it is decorated with the `[Admin]` attribute. For a razor page we also check the `[Admin]` attribute and, a razor page being not related to a controller but a `PageActionDescriptor`, we check that the page path has a segment exactly equal to `/Admin/`.

But we can easily revert to the old convention.

Then the **default** routes and only the default ones will be automatically prefixed with the configured admin prefix without having to define an additional conventional route e.g if we don't want any admin route whitout an admin prefix. Already done for razor pages through #5255 and will be done for controller actions when #5225 will be merged.
