### ISSUE TITLE
User with Author role can't access the admin

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#539]
If I create a user with only Author role, I can't log to the admin, I am redirected to the login page.

**Comment by agriffard** [comment]
I retried after @paynecrl97 changes on menus.
Still can't see the admin but now there is a 401 Unauthorized, like in #985

**Comment by sebastienros** [comment]
Looking at the code, it seems that only Administrator get the AccessAdminPanel by default.

**Comment by sebastienros** [comment]
For now we can let users add it using the UI if they need it. We'll fix in beta2 as we might need to go over all the permissions for the default roles.
