### ISSUE TITLE
font-awesome always loads from CDN

### ISSUE THREAD

**Issue by julrichkieffer** [OrchardCMS/OrchardCore#5390]
Placing the following into `Layout.liquid` ...
```liquid
{% style  at:"Head", name:"font-awesome" %}
{% script at:"Foot", name:"font-awesome" %}
```
... always generates the following HTML:
```html
<link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/css/all.css" integrity="sha384-FozkkIZqRmr4BfooWVG/w7UbmmhssZ8jGI0fImoQjxxMCR49K3wuhkAl4L3Pm8Jr" rel="stylesheet" type="text/css" />
<script crossorigin="anonymous" integrity="sha384-4yJXyYcQJQynz08thMlmIdGJtc1pH25IWEUxeXk25FYh7YxDQqu1NCAbhCC7zip6" src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/js/all.js" type="text/javascript"></script>
```

As per [OrchardCore Documentation](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Resources/), I would expect the...
* `use_cdn:"false"` override at template, OR
* `UseCdn` site setting

... to control this behaviour, but neither has any affect on the generated output.

**Comment by deanmarcussen** [comment]
resolved yesterday ;) 
in https://github.com/OrchardCMS/OrchardCore/pull/5382

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/73295333-7aa9a880-41d5-11ea-8c4f-4494e7abd13d.png)
![image](https://user-images.githubusercontent.com/3228637/73295343-809f8980-41d5-11ea-8e02-3e63db1b1b86.png)
