### ISSUE TITLE
User authentication nonpersistant 

### ISSUE THREAD

**Issue by Craige** [OrchardCMS/OrchardCore#5391]
Occasionally when logging into the Admin area, authentication does not persist between the login page and the redirect. When logging in, Orchard Core reports:

```
2020-01-13 11:56:09.4716|Project|0HLSO94CLKOHG:00000009||OrchardCore.Users.Controllers.AccountController|INFO|User logged in.
2020-01-13 11:56:09.4725|Project|0HLSO94CLKOHG:00000009||Microsoft.AspNetCore.Mvc.Infrastructure.RedirectResultExecutor|INFO|Executing RedirectResult, redirecting to /Admin/Contents/ContentItems/4ajjqwrs0dg29yj2q2jqsa6t5e/Edit?returnUrl=%2FAdmin%2FContents%2FContentItems%3Fadmin%3D-596689919.
```
But the immediate subsequent request (from the redirect) then kicks the user back out to the login page. This loop can only be broken by deleting all cookies from the browser.

**Comment by deanmarcussen** [comment]
Is this in development or production that you are experiencing this?

**Comment by Craige** [comment]
Both. It started in development, and I thought it _could_ have been related to switching back and forth between local dotnet and testing a docker container. Now that I've pushed to production, I see this there as well.

All three of these environments have been using the same host name, which I suspect is likely the trigger. Likely triggering an invalidation based on an antiforgery token?

**Comment by deanmarcussen** [comment]
ok, maybe based on dataprotectionkeys being missing from one or other system as you are swapping them around a bit.

dataprotectionkeys are used to encrypt the cookie and (I think) anti forgery token.

Have you tried using the DataProtection.Azure module?

**Comment by Skrypt** [comment]
I get this issue often when using localhost with a Docker image. I can repro. If I'm logging in Orchard Core when debugging from Visual Studio then I can't login on the Docker image. The only difference between both is the port. So, I think the issue is the fact that both are using the same domain name but have different data protection keys. So if I log in from localhost:44300 it sets the cookie for the localhost domain and validates against the protection key standing in my repo tenant folder.

So, I think this is a none issue as the protection key is there for preventing domain name spoofing. It basically does what it should. Now, resolution would be to do like @deanmarcussen said. Move over the protection keys from your tenants and try it.

**Comment by Craige** [comment]
For myself, the data protection keys are the same. I link app_data in as a docker volume, so it should be pulling the same data-protection key from there.

**Comment by Skrypt** [comment]
Ok, then are these tenants using the same database and tenant configs?

**Comment by Craige** [comment]
Yep. Sqlite for convenience at this point (scale isn't really an issue for me right now), which is also located in the App_Data directory.

**Comment by Skrypt** [comment]
Ok maybe there is an issue then.

**Comment by sebastienros** [comment]
Not reading the whole thread, is there a consistent repro we can follow?

**Comment by Skrypt** [comment]
Make 2 Docker images with the same config and try to logon on both.

**Comment by deanmarcussen** [comment]
I can't repro this.

Configuration used. two docker images, and a dotnet run instance, all sharing the same `App_Data` folder, i.e. DataProtectionKeys, http, not https.

I am able to log on to all 3 of them regularly and consistently.

@Craige can you confirm this is still occuring, and provide some more repro steps (i.e. you say occasionally, how occasionaly?)

You also say you are seeing it in production. Can you detail more your configuration that is causing this?

**Comment by Craige** [comment]
I will try to reproduce this again.

**Comment by sebastienros** [comment]
Please reopen if you can repro
