### ISSUE TITLE
Discussion on a potential issue reported in a meeting

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#5392]
@agriffard @sebastienros 

So, in one of the last meetings you were talking about the following line of code saying that it may be a caching issue.

    // Refresh the local part variable in case it has been altered
    part = _contentDefinitionManager.LoadTypeDefinition(id).Parts.FirstOrDefault(x => x.Name == viewModel.Name);

- Seems to be related to reusable / named parts and there is already the same line of code since a long time for fields that can be re-used / re-named by nature.

- So my question is, @agriffard did you add this line to fix a real issue or just to do the same as for field? Then is it worth to check it more in depth?

- If we don't check it more in depth, this line makes sense as it is consistent with what we are doing for fields.

**Comment by agriffard** [comment]
@deanmarcussen made this change on m'y PR.

**Comment by jtkech** [comment]
Okay thanks, then same question to @deanmarcussen ;)

**Comment by deanmarcussen** [comment]
Haha was just writing my reply ;)

Yes, I add this because the problem was that the `Editor` setting was not being updated when `viewModel.Shape = await _contentDefinitionDisplayManager.UpdateTypePartEditorAsync(part, this);` (the next line) was being called.

What that meant was that when the `Editor` setting was change, the new value wasn't reflected when the `UpdateTypePartEditorAsync` was called.

So I change it to be consistent with how we work with fields.

However both what we do with fields and (now) parts does have a caching issue.

If validation fails, the new setting is still applied, and stays changed in the content definition manager cache (concurrent dictionary), but I imagine the change is not persisted to disk as we do a `_session.cancel` if the model state fails.

```
            _contentDefinitionService.AlterTypePart(viewModel); -> this line the issue

            // Refresh the local part variable in case it has been altered
            part = _contentDefinitionManager.LoadTypeDefinition(id).Parts.FirstOrDefault(x => x.Name == viewModel.Name);
```

To repro I try with both html field and html body.
- set as standard editor and save
- set as Trumbowyg and change the json to be bad json, e.g. `{`
- save
- validation error
- go of the part and back into it's setting. 
- `Trumbowyg` is now editor.

Haven't had time to check the `ContentDefinition.json` file.

**Comment by jtkech** [comment]
Okay i will dig into it by using your repro, thanks.

> If validation fails, the new setting is still applied, and stays changed in the content definition manager cache (concurrent dictionary), but I imagine the change is not persisted to disk as we do a _session.cancel if the model state fails.

Okay but when we are using the file definition store it is not aware of a session cancel. I remember that i suggested to have a kind of file store cancel.

**Comment by jtkech** [comment]
Okay just did some tests

> What that meant was that when the Editor setting was change, the new value wasn't reflected when the UpdateTypePartEditorAsync was called.

So to build the editor shape when the model is not valid. First for clarification, when we do a `Load` this is not a `Get` from a shared cache but a `Load` from the store but that has its own scoped cache so that we can do multiple updates on the same object in a given scope.

For infos this is quite the same for types definitions and there is also the **built type definitions** that have their own caches that we clear when we alter the types definitions as they need to be rebuilt.

That said when we do an `AlterTypePart()` we use builders and at some point the part is removed from the list and then re-added but as a result of a builder that is a new object.

        public ContentTypeDefinitionBuilder WithPart(...)
        {
            ...
            if (existingPart != null)
            {
                _parts.Remove(existingPart);
            }
            ...
            _parts.Add(configurer.Build());
            return this;
        }

The build() returning a new object

        public override ContentTypePartDefinition Build()
        {
            return new ContentTypePartDefinition(Current.Name, _partDefinition, _settings)
            {
                ContentTypeDefinition = Current.ContentTypeDefinition,
            };
        }

**So here this is not our original part that is altered but a new object that we need to retrieve. So for this point i think the current code is okay**.

> If validation fails, the new setting is still applied, and stays changed in the content definition manager cache (concurrent dictionary), but I imagine the change is not persisted to disk as we do a _session.cancel if the model state fails.

Yes this is **the only issue that we may have to fix** when using `FileContentDefinitionStore` that is not aware of the session cancel. **It works with the** `DatabaseContentDefinitionStore`.

Maybe we would need to have a kind of `IDocumentStore` that we could use for the file store that would have to implement `Cancel()` and `CommitAsync()`, as i did in an old PR.

Hmm, i think i will work on `IDocumentStore` or `IDataStore` as i may need it in #5249 to have a generic service that keeps in sync a distributed cache with a given type of data store.

**Comment by jtkech** [comment]
Okay, we know what happens, this is not a big issue and we still have the ability to use the database definition store, so i close it.
