### ISSUE TITLE
DisplayDriverBase.Dynamic shape result factory with the async factory overload is not working

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#5393]
When I use the Dynamic factory to generate my ShapeResult in the Driver where the initialize action is not async it works fine. E.g.

```
Dynamic("MyShape", shape =>
{
    shape.MyProperty = GetMyPropertyValue();
})
```

However, when I want to do an asnychronous operation in the shape factory and I use the other overload of the Dynamic helper it won't be executed. E.g.

```                   
Dynamic("MyShape", async shape =>
{
    shape.MyProperty = await GetMyPropertyValueAsync();
})
```

The latter overload ([here](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.DisplayManagement/Handlers/DisplayDriverBase.cs#L70)) passes the Func to [this IShapeFactory.CreateAsync](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.DisplayManagement/IShapeFactory.cs#L37) extension method where the second parameter is not a Func but it's an TModel.

My workaround (and could be actually the fix for this issue) was implementing it the way the non-async overload uses this factory:

```
return Factory(shapeType,
    async ctx =>
    {
        dynamic shape = await ctx.ShapeFactory.CreateAsync(shapeType);
        await initializeAsync(shape);
        return shape;
    });
```

**Comment by jtkech** [comment]
Yes LGTM 👍
