### ISSUE TITLE
OpenId warning in ExternalLoginCallback not shown

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5397]
I'm trying to add IdentityServer4 as openid connect server. I also configured the Identity Server server as token validation authority in the feature: OpenID Token Validation.
When I log into IdentityServer and return to the OrchardCore Cms site, I'm redirected to the Login page without any error or warning message. When I look in the console I see a warning message: "OrchardCore.Users.Controllers.AccountController: Warning: Site does not allow user registration.".
I analyzed the issue and the message is added to the model state in ExternalLoginCallback, but a RedirectToAction is performed at the end to Login. So the message is lost.

**Comment by MichaelPetrinolis** [comment]
You must enable Users Registration feature and configure it appropriate. 
If you do not allow users to self register, then you must include the email in the requested scopes in order to match local users based on it.

**Comment by ArieGato** [comment]
Thanks for the info. I'll go ahead with that angle. My point was that the warning/error message is not shown.
