### ISSUE TITLE
How to delete "+new" Content Items in Role?

### ISSUE THREAD

**Issue by kyahyan** [OrchardCMS/OrchardCore#5398]
<img width="260" alt="Screen Shot 2020-01-29 at 11 36 00 PM" src="https://user-images.githubusercontent.com/23460968/73371147-3959eb80-42f0-11ea-9336-f6e9710453e4.png">

**Comment by deanmarcussen** [comment]
Can you clarify the question please? 

I do not understand what you want to achieve

**Comment by kyahyan** [comment]
in admin menu, how to remove "+ new" ? by disabling in user Role

**Comment by deanmarcussen** [comment]
ok so the permission this relates to is `PublishContent`

However this permission only affects the menu items under `+ New`, not the top level menu itself.

So if the `PublishedContent` permission is not allowed, then the items will not show, but the top level menu still will.

We could do also permission check for the top level menu, and if the result is no on all content type definitions, we could not show the menu
