### ISSUE TITLE
View for my module not found?

### ISSUE THREAD

**Issue by ibiza240** [OrchardCMS/OrchardCore#5399]
I am getting this sort of error with my own little module as a first test...

![image](https://user-images.githubusercontent.com/6589646/73373355-82755580-4286-11ea-9143-2e4cdc18b035.png)

Not sure why it is not looking at the right place..?

![image](https://user-images.githubusercontent.com/6589646/73373411-91f49e80-4286-11ea-87ef-f64140e6d96c.png)

Thanks :)

**Comment by Skrypt** [comment]
Does your module .csproj have this in the first line? 

`<Project Sdk="Microsoft.NET.Sdk.Razor">`

**Comment by ibiza240** [comment]
It didn't. Now with it, it's working!

Many little subtle things to know...

Thank you so much :)

**Comment by Skrypt** [comment]
You can ask these kinds of questions on Gitter instead of opening issues as they are not issues related with OC but with it's learning curve.
