### ISSUE TITLE
Reduce Length of Indexes (Round 2?)

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#5401]
Pull Request #5357 was intended to take care of the issue of index keys being too long but on my Microsoft SQL server instance the TextFieldIndex "Text" column is of type nvarchar which means there are 2 bits / character so the longest the text length can be is 450 instead of 900 (not sure if MySQL has an nvarchar equivalent or not). As an alternative, if I change my SQL server column type to be varchar(768) instead of nvarchar(768) then everything works as expected since I am only using 1 bit / character. However, I don't know if most users will be comfortable doing this and wondering if we should drop down to a length of 450? It would be even lower if MySQL has an nvarchar (i.e. half of 768) but I don't believe it has such a column type.

cc: @deanmarcussen

**Comment by deanmarcussen** [comment]
@jeffolmstead so went to quite a bit of testing to make sure that #5357 was suitable BUT if it is wrong then we should correct it.

However I'm confused, and maybe we are coming up against environment differences.

By default on my SQL Server instance (v13.0.4259.0), with YesSQL, the Content Fields feature creates Non-Clustered indexes, which is what I would expect.

They have (and again there is some variance with versions) a max key length of 1700 bytes.
That adds up to a max length of 850 for MS SQL

Which should fit with the max length of 768 (chosen for MySql) which I chose for the index lengths.

There's an extensive bunch of tests for YesSQL over here proving the sizes for both MySql and MS SQL https://github.com/sebastienros/yessql/pull/223
The tests also pass on the sql server version in appveyor

So in this issue there's a lot to do with versions of sql server, and database collation choices.

Questions I would ask you to confirm
- what version of sql are you running?
- do you have non clustered indexes for the columns (I can't see how they'd be anything else.)

If we are coming up against version differences, can you be quite specific about which version you are running in both development and intend to for production?

One possibility that we could do here (I considered this, but it seemed over complicated) is offer these max sizes as a configuration variable, so they could be adjusted up and down for different database needs. 

Seemed like a last resort though

**Comment by jeffolmstead** [comment]
I am local SQL Server (v12.0.4522) at the moment and ultimately on SQL Azure in production. My SQL server instance also creates Non-Clustered indexes. And, it is crazy, I see on [Microsoft documentation](https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-ver15) the same thing, that nonclustered indexes should support up to 1,700 bytes per index key.

Ok, so the issue on my end is that I am basically on SQL Server 2014 and the nonclustered indexes were not upgraded to 1,700 bytes per index key until SQL Server 2016. With that being the case, I believe it is safe to consider this a "local" problem and not anything worth changing in Orchard itself (I just need to upgrade). Thanks for getting back to me on this one.
