### ISSUE TITLE
Split (A/B) Testing

### ISSUE THREAD

**Issue by techmouse84** [OrchardCMS/OrchardCore#5403]
Hi , 
Basically i'm looking for the feature where i can create a set of multi variant pages and be able to configure different traffic to view variants of the pages. A common use case is to know what would interest people to navigate the site after the initial landing. The final result would be to be able to visualize that 50% of the people that landed on page with design A browsed the site, but only 10% of the people that landed on page with design B browsed the site. 
There's many other scenarios, like conversions, interests , call to action, etc. 

I want to check if this is in the roadmap. 
Any suggestion on how this can be achieved?

**Comment by Skrypt** [comment]
Nothing planned but I like the idea. Basically a set of rules that would affect the display of content. Could be altering the current template of the page or parts of it.

**Comment by sebastienros** [comment]
You could write a custom theme provider, and some logic to swtich which theme to use. A theme could customize a layout, or a specific view ... And these themes could also be based on a common one if most things are common.

Look at implementing `IThemeSelector` for that.

**Comment by Skrypt** [comment]
Something that is common in e-commerce. You have a landing page that displays different products for different regions or even things like black friday rebates that applies at different percentile per region. So these are set with rules and sometimes it requires to build an alternate homepage layout that gets enabled on a specific date and that turns down also on a specific date. So, I think that it looks like this kind of feature.

**Comment by ns8482e** [comment]
@techmouse84 you can implement variant of pages in Orchard Core easily for same content. 

**1. Implement `IThemeSelector `** 
 @sebastienros  suggested you can create multiple themes and implement `IThemeSelector ` and add conditional logic based on route values that selects a Theme. See  [User's module for example](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/Services/UsersThemeSelector.cs)

**2. Same theme different layout**
In case you plan to use same theme but different design, you could use different layout in same theme and change layout in template based on conditional logic based on route values. ( I wish layers feature would have option to select layout based on rule)

**in cshtml** 
`ViewLayout = "Layout__DesignOne";`

**In liquid**
`{% layout "Layout__DesignOne" %}`

**2. Using Same Theme and Layout but different Views for content item**
 If you want same theme and layout but want to change design of an content item you could create multiple alternates for the content item i.e. Product-DesignOne.chstml, Product-DesignTwo.cshtml
and based on route values add conditional logic to add alternates to a shape.

`xyzShape.Metadata.Alternates.Add("Product__DesignOne");`

For tracking, and dashboard of A/B testing - There is nothing like one size fits all,  you still need to use third party page tracking tools (or build your own solution e.g.  Google Analytics or Microsoft App Insight) with custom events and data that you want to track.

**Comment by Skrypt** [comment]
@ns8482e 
That tells him how to work with different themes and layouts but the most part of his request is about collecting stats and analyze them to display different kind of content which can be done partly with Google Analytics and Insight but I believe that he will probably also need Azure Machine Learning to analyze these stats.

**Comment by sebastienros** [comment]
@Skrypt sure, then each method that customizes the page can then also render a different javascript call to the google api.
