### ISSUE TITLE
How to Create Bag Content item through Create Content Task in workflow???

### ISSUE THREAD

**Issue by kyahyan** [OrchardCMS/OrchardCore#5404]
Content Properties

```
"Message": {
    "ContentItems": [
        {
            "MessageItem": {
                "ContentItems": [
                    {
                        "MessageItem": {
                            "InputFielName": {
                                "Text": "{{ Request.Form.Name }}"
                            }
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by Skrypt** [comment]
Create one content item with a bag part item and look in the database to get a sample. Or simply export it.

**Comment by BenPool** [comment]
"Message" Content Type is already created with bag part  "MessageItem" which have 4 fields.
We're trying to get the inputs from the form using the workflow task " Create Content Task" and put them in the MessageItem fields.

We can't figure out the JSON codes to create Message content type and have the bag part already added.

![Capture](https://user-images.githubusercontent.com/59591238/73426828-4e765f00-4370-11ea-9d7e-e3122633cf11.PNG)

**Comment by Skrypt** [comment]
Ok create one content item of this Content Type. Make sure you add a MessageItem to this content item. Then open this content item to edit it. Look at the url and copy the GUID part of this url which tells you the ContentItemId of this content item. Then open up your database and look at the ContentItemIndex table and do `SELECT * FROM ContentItemIndex LEFT JOIN Document ON ContentItemIndex.DocumentId = Document.Id WHERE ContentItemIndex = 'YOUR COPIED GUID'`.
Copy the Document.Content column content and paste it on this nice online json editor : 
https://jsoneditoronline.org/
Then look at the JSON structure and try to copy it in your Workflow.

**Comment by BenPool** [comment]
![working](https://user-images.githubusercontent.com/59591238/73629450-1df33580-468e-11ea-936e-5268d1ecb77c.PNG)

It works, Thank you. (Y)

**Comment by Skrypt** [comment]
Related #5439
