### ISSUE TITLE
Multi Langauge the Name T does not exisit on currect context

### ISSUE THREAD

**Issue by bekgroupservice** [OrchardCMS/OrchardCore#5418]
Hi,

i added T for translate for htmls files on a project. 

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | CS0103 | The name 'T' does not exist in the current context | .... | ......\Views\Home\messagefeedback.cshtml | 8 | Active

**Comment by Skrypt** [comment]
You are missing dependencies on your project to make it work. Please look at modules to see examples.

**Comment by hishamco** [comment]
This is duplicate for another issue that I answer it yesterday

You should inherent from `RazorPage <TModel>` which should be placed in `_ViewImports.cshtml`

**Comment by hishamco** [comment]
This is duplicate for #5424
