### ISSUE TITLE
Menu active item

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#542]
Todo: Improve the menu view to add an 'active' css class on the menu item corresponding to the current displayed page (url == autoroute permalink).

**Comment by agriffard** [comment]
We need to set the Selected property of the MenuItem shape to be able to do as in the NavigationItem :
```
        if ((bool) Model.Selected) {
            Model.Classes.Add("active");
        }
```
but I don't really understand where to do this.

**Comment by jhdrn** [comment]
Any updates on this? I'm trying to figure this out too...

**Comment by sebastienros** [comment]
Note to myself, fix the caching issue that is related (new event when rendered from cache, or cache per page).

**Comment by agriffard** [comment]
Possible solution: add `data-localpath` attribute and in javascript, add an `active` css class if it matches with the current url.

**Comment by sebastienros** [comment]
If it's based on JS the new attribute might not be necessary and just use the href.
