### ISSUE TITLE
GraphQL Issue with "Reserved" Names

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#5420]
This is not a large issue, but documenting in case it can be fixed. Here is the example:

1. Make a new content type
2. Add a Text Field of 'Owner'

That might be enough for GraphQL to throw a fit, didn't check yet. In my case I did more steps:

3. Go to an existing content type (or a new one) and add a Named Part with "Contained Content Types" of the content type made in step 1

This will crash GraphQL as, I believe, "Owner" already exists on the Content Item level and now there is a new field called "Owner". Probably this happens with other fields that are on every Content Item (e.g. "Author"??).

Again, not "huge" since I hadn't used the field yet, but if I had a LOT of data in the system, would have been hard to create a new field called something other than "Owner".

**Comment by carlwoodhouse** [comment]
Yeah i ran into it with 'Author' basically it's because it's adding a field named 'owner' to something that already has that field registered (its on the base contentitemtype)

I'll have a think about if there's a way to fix it.
