### ISSUE TITLE
Confirm unsaved changes before leaving

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5426]
When you leave an admin page without saving your content, there should be a warning popup suggesting you to save your changes before leaving.

**Comment by hishamco** [comment]
If am not wrong, there's already similar issue filed, hope to find it and write down its link

**Comment by sebastienros** [comment]
We should be able to detect any change by using the existing preview event that is triggered when some content is changed.

**Comment by agriffard** [comment]
Duplicate of #1008
