### ISSUE TITLE
ListsPartSettings updates causes error on ordering listpart update.

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#5428]
When changing listpartsettings and hitting save this error occurs : 
` IContentTypePartDefinitionDisplayDriver thrown from OrchardCore.Lists.Settings.ListPartSettingsDisplayDriver by ObjectDisposedException System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Session'.
   at YesSql.Session.CheckDisposed()
   at YesSql.Session.DemandAsync()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()`

which is caused from this section  : 

`	var containerItems =  await _containerService.GetContainerItemsAsync(contentTypePartDefinition.ContentTypeDefinition.Name) ;
	foreach (var containerItem in containerItems)
	{
		var containedItems = await _containerService.GetContainedItemsAsync(containerItem.ContentItemId);
		await  _containerService.UpdateContentItemOrdersAsync(containedItems, 0) ;
	}`

Removing the await and adding  .GetAwaiter().GetResult() to async methods solves the error but I dont think this is the right fix.

@deanmarcussen

**Comment by deanmarcussen** [comment]
Hmm I'm having difficulty repro this error.

Can you tell me a bit more about your environment?

What database
and what is the design of your list part (plus how how list parents do you have?)

I'm trying with the blog theme and Sqlite 

I can see a possible null ref issue with drafted items when initial ordering is done which I will look into

**Comment by giannik** [comment]
Im using ms sql express with some existing content items that are beeing updated.
My schema is : 
 Policy (Content Type))    - with list of 
      PolicySection(ContentType)
The PolicySection contenttype is marked as non versionable (Versionable = false)

As mentioned if i replace the first 2 async with .GetAwaiter().GetResult() like this : 

`if (settings.EnableOrdering != model.EnableOrdering && model.EnableOrdering == true)
                {
                    var containerItems =  _containerService.GetContainerItemsAsync(contentTypePartDefinition.ContentTypeDefinition.Name).GetAwaiter().GetResult() ;
                    foreach (var containerItem in containerItems)
                    {
                        var containedItems =   _containerService.GetContainedItemsAsync(containerItem.ContentItemId).GetAwaiter().GetResult();
                        await  _containerService.UpdateContentItemOrdersAsync(containedItems, 0) ;
                    }
                }`

it works.
This is why i hate async/await. Cant picture in my head what is going on.

**Comment by deanmarcussen** [comment]
how many Policy (parent list items) do you have?

and approx how many child items would each parent have?

**Comment by giannik** [comment]
not much. 
I only have 2 policy records and each policyrecord had 2-3 policySection record (as connected listpart items).

**Comment by jtkech** [comment]
@deanmarcussen after a quick look i noticed 2 things in the following code

    await _contentManager.UpdateAsync(contentItem);

    // Keep the published and draft orders the same to avoid confusion in the admin list.
    if (!contentItem.IsPublished())
    {
        var publishedItem = await _contentManager.GetAsync(contentItem.ContentItemId, ...);
        publishedItem.Alter<ContainedPart>(x => x.Order = orderOfFirstItem + i);

        await _contentManager.UpdateAsync(publishedItem);
    }

- After having done the 1st `UpdateAsync(contentItem)` that does a session save, if you do `GetAsync()` and if it does a session query (not cached) that does a flush, the session save would need to be done again. So i think that the 1st `UpdateAsync(contentItem)` would need to be after the if block.

- Then, when a content type is not versionable, as @giannik uses for its contained types, if a content item is saved as a draft then there is no published item anymore, **so `publishedItem` may be null**.
