### ISSUE TITLE
Orchard.OpenId name conflict

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#543]
I think Orchard.OpenId in orchard 2 (which is server) is diff from Orchard.OpenId in orchard1(which is client), so it will create potencial conflict in future

**Comment by jersiovic** [comment]
I think that when a client module is going to be created in Orchard 2 we can name it Orchard.OpenId.Client and even we can rename existing one to Orchard.OpenId.Server. Other option is to left it as it is and merge client features in current Orchard.OpenId as an extra feature. The point is Orchard 1 and Orchard 2 are separate solutions with different modules I don't see why name in Orchard 1 should affect name in Orchard 2.

**Comment by infofromca** [comment]
I think this option is good
I think that when a client module is going to be created in Orchard 2 we can name it Orchard.OpenId.Client and even we can rename existing one to Orchard.OpenId.Server
====
but merge is not good idea because the user maybe only need logon by google.
or the user only create token as third party server

**Comment by PinpointTownes** [comment]
Closing as all the Orchard Core/2 packages have been renamed to `OrchardCore.[Module]`, including the OpenID module which is now named `OrchardCore.OpenId`.
