### ISSUE TITLE
Library with GraphQL wrapper included

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5434]
If people want to consume Orchard Core contents from an external project, it would be interesting to provide a Shared library that allows you to specify (in Configuration) the url and may be the OpenId token to provide in order to retrieve some content(s) by alias, by content type or from a query by sending a GraphQL call.

If the content types are declared somewhere (as in Migrations) and shared, they could be deserialized as objects in order to easily access their properties (Parts, Fields, Metadatas) when they are retrieved with a Generic method.

That would be useful in the context of a Blazor project for example.

**Comment by carlwoodhouse** [comment]
At our place we use https://github.com/Husqvik/GraphQlClientGenerator to generate strongly typed packages for out internal nuget.

The problem a little is the dynamic nature of orchard on a per site / tenant basis; as you alude too different parts, types, etc ...

Im sure we could include something with 'default' stuff; but even that depends on the recipe, permissions, etc a little.

**Comment by agriffard** [comment]
See #6639 to export the GraphQL Schema.
