### ISSUE TITLE
Issue in admin menu when mapping url of controller's first action

### ISSUE THREAD

**Issue by cocoke** [OrchardCMS/OrchardCore#5437]
Hey,

I've some difficulties since last commits about the admin menu.

The first action in the AdminController doesn't have url :
![image](https://user-images.githubusercontent.com/6980626/73600037-5fc79300-454b-11ea-90c8-06f85dea7a8b.png)

If I add a dummy action at the first position, the one that didn't work works again:
![image](https://user-images.githubusercontent.com/6980626/73600120-5ab71380-454c-11ea-8e49-f97cee50aa5e.png)

Code inside the AdminController :
```
public IActionResult Dummy() => View(); //Without this, the "IndexFaq" menu doesn't have url
public async Task<IActionResult> IndexFaq(){...}
```

I've done some search about the route mapping but doesn't find why the mapping behaves like this only for my first action (I have others action's menu inside this same controller that are working)

Any ideas ? 😃

**Comment by jtkech** [comment]
For people that don't want any admin route without the admin prefix, now the default route of an Admin controller is automatically prefixed with the configurable admin prefix that is by default `Admin`.

Then you still have the choice to define other routes with or without the admin prefix, this through a conventional route in your startup or by using the route attribute.

**Comment by deanmarcussen** [comment]
How are you building the urls you show above?

I assume it's in an `INavigationProvider` ? Can you share the code

The `UrlHelper` / `LinkGenerator` should build for your controller a url of
`/Admin/K2.Faq/Admin` for your first `IndexFaq` action as the first (default) action of the controller.

The next actions will by default be `/Admin/K2.Faq/Admin/NextAction`

**Comment by giannik** [comment]
I can confirm this as well.
Had a controller named  ExplorerTreeListController with GetFoldersByFolderType action as the first action. No route in startup configured, just relying on standard mvc conventions.
In my  razor view had a tag calling : 

`<input type="hidden" value="@Url.Action("GetFoldersByFolderType", "ExplorerTreeList", new { area = "My.CustomModuleArea" })" />`

Url rendered was the  default "\"  , not the expected.
After adding a route prefix on the controller action     [Route("ExplorerTreeList/GetFoldersByFolderType")] it worked as expected.

I think others will stumble on this as well. 
I was scratching my head why it was working for all other actions except this one.

**Comment by cocoke** [comment]
> How are you building the urls you show above?

I'm not building it, it's an admin menu entry, declared inside a ```INavigationProvider``` with the following code :
```
builder
    .Add(T["Knowledges"], "0", knowledges => knowledges
            .Add(T["Smart FAQ"], "0", faq => faq
                .Action("IndexFaq", "Admin", "K2.Faq")
                .Permission(Permissions.K2_SmartFAQ_Show)
                .LocalNav()
            )
    );
```

With or without declaring ```MapAreaControllerRoute``` in the startup.cs, this menu entry doesn't work if it's the first action in the AdminController.

> After adding a route prefix on the controller action [Route("ExplorerTreeList/GetFoldersByFolderType")] it worked as expected.

It works after adding ```[Route(...)]``` attribute 😕

**Comment by Skrypt** [comment]
Well first you say that your controller is named AdminController and that your route defines the controller name as ExplorerTreeList which normally should never work.

**Comment by cocoke** [comment]
@Skrypt ```ExplorerTreeList``` is the controller used by @giannik. 
In my project, the ```AdminController``` is named ```AdminController``` everywhere, even in my route definition 😃

**Comment by jtkech** [comment]
Okay i did some tests

- So, in the admin controller of `OC.Contents` i created a 1st action `Test1` and a second one `Test2`.

    Without any route maping in the startup, the following urls are generated.

      https://localhost:44300/OrchardCore.Contents/Admin/Test1
      https://localhost:44300/OrchardCore.Contents/Admin/Test2

    It works but i would have expected the following ones that we generate automatically, they work but there are not used for link generation. So it seems that the above urls that we don't map anymore for an admin controller still exist.

      https://localhost:44300/Admin/OrchardCore.Contents/Admin/Test1
      https://localhost:44300/Admin/OrchardCore.Contents/Admin/Test2

- Then, i added 2 routes in the statup with the following pattern

      pattern: _adminOptions.AdminUrlPrefix + "/{area}/{controller}/{action}/{id?}",
      defaults: new { controller = adminControllerName, action = nameof(AdminController.Test1) 

      pattern: _adminOptions.AdminUrlPrefix + "/{area}/{controller}/{action}/{id?}",
      defaults: new { controller = adminControllerName, action = nameof(AdminController.Test2) 

    Then i got the following generated urls, so same issue

      https://localhost:44300/Admin
      https://localhost:44300/Admin/OrchardCore.Contents/Admin/Test2


- Note: The url helper / link generator / anchor tag helper generate the same url as the navigation provider.

I will dig into it

**Comment by jtkech** [comment]
Okay

- When you define a route it has to be more specialized than the default ones that are registered automatically with or without an admin prefix, it works if we don't use `{action}`.

      pattern: _adminOptions.AdminUrlPrefix + "/{area}/admin/test1/{id?}",
      pattern: _adminOptions.AdminUrlPrefix + "/{area}/admin/test2/{id?}",

- Then we have to do the same in our automatic mappers, e.g

      _defaultAreaPattern = adminUrlPrefix + "/{area}/{controller}/{action}/{id?}";
      ...
          pattern: _defaultAreaPattern.Replace("{action}", descriptor.ActionName)

- Then by doing the above we can still register another route in the startup with at least the same specialization, if the specialization is the same the 1st registered wins (the one in the module startup).

- The last think for an admin controller is that the default non prefixed url is still reachable, i will look at it. At least, if no other more specialized route is registered, with the above change the generated url is the default one we register with the admin prefix.
