### ISSUE TITLE
All permissions are implicitly, effectively allowed for Administrator users - is this intended?

### ISSUE THREAD

**Issue by jaketyb** [OrchardCMS/OrchardCore#5447]
Hi

We've added a new permission and the desire is that it should be disabled for all users/roles by default. However we've noticed that for the Administrator user the permission is ticked under 'Effective', even though the `GetDefaultStereotypes()` does not return this permission for any role.

Is it intended that all permissions are effectively allowed for Administrators, regardless of whether `GetDefaultStereotypes()` returns them or not?

Just to add a bit of context, if it helps:

We're looking to add a permission to force certain users to perform an additional action, e.g. `ForceActionX`. This would be enabled/disabled by the Administrators of our site. The permission would need to be disabled by default across all roles - we'll be upgrading existing sites and they should behave the same post-upgrade. Obviously if Administrators are granted all permissions then `ForceActionX` would be enabled for them, which is not desired.
The alternative is to invert the permission, so that it becomes `BypassActionX`, but the problem with doing this is that we would need to have this permission enabled by default for all roles. We should be able to do this via a migration by iterating over all the roles set up on the site and allowing it for each of them, but this seems a bit clunky, and if an Admin then decides to add a new role it would still have to be explicitly allowed.

Thanks

**Comment by deanmarcussen** [comment]
This is probably because the current logged in user is the super user, which automatically gets all permissions.

Try creating a new administrator account that is not the account used to setup the site, and check the permissions on that account

The super user is the account which setup the site. It is mapped in SiteSettings. You can remove it at your discretion.
