### ISSUE TITLE
Menu : responsive behavior issues

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#5449]
The collapsed menu doesn't provide scrolling

![image](https://user-images.githubusercontent.com/1165805/50122680-8d039580-0212-11e9-8940-34254fd20768.png)

Also when we are opening a sub-menu from the bottom of that collapsed menu the items are not accessible. We should open the sub-menu reversed or something like it.

**Comment by agriffard** [comment]
![image](https://user-images.githubusercontent.com/703248/91443461-abd57e80-e873-11ea-9720-a1d518715fd8.png)

The collapsed menu does provide scrolling.

**Comment by Skrypt** [comment]
Try to narrow down your browser height and open that same "Configuration" menu you will see that even if the sub-menu have a scrollbar you can't reach the elements which are in the bottom of that sub-menu. It would require that the sub-menu open reversed (down to top).
