### ISSUE TITLE
Culture picker with a flag

### ISSUE THREAD

**Issue by bekgroupservice** [OrchardCMS/OrchardCore#5453]
Hi mate,

anyone know how may i add a flag for each langauge ? 

      <ol class="breadcrumb  lighten-4">

                        {% for culture in Site.Properties["LocalizationSettings"].SupportedCultures %}
                        <li class="breadcrumb-item active"><a href="{{ culture | switch_culture_url }}">{{ culture | t}}</a></li>
                        {% endfor %}
                    </ol>

**Comment by sebastienros** [comment]
You need to download the flags as images, or as a font that contains them, and use these images/icons.
Each file would have a filename like `{culture}.png` and you would be a dynamic link to this.
