### ISSUE TITLE
Menu sterotype 

### ISSUE THREAD

**Issue by matiaskusack** [OrchardCMS/OrchardCore#5454]
Hi, I'm having a problem and don't know how to solve it.

I've defined a Category content type witch has some parts (Title, Autoroute, Common, Flow and another custom called SEO).
There's another content type called Subcategory, witch has same parts and a ContentPicker field to reference a Category as parent.

The thing is that I want to list it with a menu with links to the hierarchie, so I set Category Stereotype to MenuItem but when I go to Content Items page in Admin, it shows this exception.

`System.Exception: Shape type 'MenuItem_SummaryAdmin' not found`

I've already tried to create templates for *MenuItem_SummaryAdmin__Category*, *MenuItem_Summary__Category* , *MenuItem__Category* but nothing worked.
I think I might be doing something wrong. I'm thinking the error says it doesn't have a shape defined, so I tried to define shapes inside templates, but they don't even fired.

What am I doing wrong?
Thanks

**Comment by sebastienros** [comment]
Have you tried using a Taxonomy instead of using content pickers?
At which point there are some example on other issues (and maybe the doc) to render the taxonomy on the front-end.

**Comment by matiaskusack** [comment]
Hi, thanks for answering.

I've tried with taxonomies, but for what I read in #2688 and #2755 it's not implemented yet.
So following @dodyg summary in #4494 I decided to start this by using our own content types to tag elements.

Anyway, I think I was wrong about how to use Stereotypes and I now get what I was getting wrong. I didn't had a shape to render...

Regards.
