### ISSUE TITLE
MediaField: Remove button is only enabled when a media is selected

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5458]
When you edit a Content item with a MediaField, the remove button is disabled.

 `v-bind:class="{ disabled : !selectedMedia }"` seems to not be evaluated correctly.

**Comment by agriffard** [comment]
@deanmarcussen said;
> The media item just needs to be selected for the remove button to show up.

**Comment by agriffard** [comment]
I'd rather have a remove button on each media or at least it should be selected automatically when the field allows only one media, it is a bit weird to select the media and then to remove it.

**Comment by deanmarcussen** [comment]
I agree @agriffard 

It might be weird for it to be autoselected (because it would put a border around it - and the it would be possible for it to be unselected

But if the remove button was always enabled when only one item is present, then that might work (and might be easy)
