### ISSUE TITLE
Deploy and Error

### ISSUE THREAD

**Issue by bekgroupservice** [OrchardCMS/OrchardCore#5465]
Hi 

I got a error on build 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Detected package downgrade: OrchardCore.ContentTypes.Abstractions from 1.0.0-rc1-11779 to 1.0.0-rc1-11677. Reference the package directly from the project to select a different version. 
 RechnerModule -> OrchardCore.Autoroute 1.0.0-rc1-11779 -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11779) 
 RechnerModule -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11235)	WebProjectFairIntheAir	C:\Users\Administrator\source\repos\xx\WebFairIntheAir\RechnerModule\RechnerModule.csproj	0	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Detected package downgrade: OrchardCore.ContentTypes.Abstractions from 1.0.0-rc1-11779 to 1.0.0-rc1-11677. Reference the package directly from the project to select a different version. 
 WebProjectFairIntheAir -> RechnerModule -> OrchardCore.Autoroute 1.0.0-rc1-11779 -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11779) 
 WebProjectFairIntheAir -> RechnerModule -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11235)	WebProjectFairIntheAir	C:\Users\Administrator\source\repos\xx\WebFairIntheAir\WebProjectFairIntheAir\WebProjectFairIntheAir.csproj	0	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Detected package downgrade: OrchardCore.ContentTypes.Abstractions from 1.0.0-rc1-11779 to 1.0.0-rc1-11677. Reference the package directly from the project to select a different version. 
 WebProjectFairIntheAir -> RechnerModule -> OrchardCore.Autoroute 1.0.0-rc1-11779 -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11779) 
 WebProjectFairIntheAir -> RechnerModule -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11235)	WebProjectFairIntheAir	C:\Users\Administrator\source\repos\xx\WebFairIntheAir\WebProjectFairIntheAir\WebProjectFairIntheAir.csproj	0	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: OrchardCore.ContentTypes.Abstractions from 1.0.0-rc1-11779 to 1.0.0-rc1-11677. Reference the package directly from the project to select a different version. 
 RechnerModule -> OrchardCore.Autoroute 1.0.0-rc1-11779 -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11779) 
 RechnerModule -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11235)	RechnerModule	C:\Users\Administrator\source\repos\Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: OrchardCore.ContentTypes.Abstractions from 1.0.0-rc1-11779 to 1.0.0-rc1-11677. Reference the package directly from the project to select a different version. 
 RechnerModule -> OrchardCore.Autoroute 1.0.0-rc1-11779 -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11779) 
 RechnerModule -> OrchardCore.ContentTypes.Abstractions (>= 1.0.0-rc1-11235)	RechnerModule	C:\Users\Administrator\source\repos\FairIntheAirGitV3\WebFairIntheAir\RechnerModule\RechnerModule.csproj	1	
\WebFairIntheAir\RechnerModule\RechnerModule.csproj	1

**Comment by deanmarcussen** [comment]
Can you upgrade to 1.0.0-rc1-11850 on the myget server as there was an issue with space and see if that resolves

**Comment by bekgroupservice** [comment]
thanks its works ;)
