### ISSUE TITLE
Tenant Recipe not working

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5476]
I have an issue that was reported in #3346
Here is how to reproduce the problem:
Generate a theme using the template generator.
Copy over the files and folders from TheAgencyTheme into you new custom theme.
Modify the recipe file you copied over 
Try and run the recipe as a tenant
It wont work.
You will get the layout exception.
To fix it you then go to themes and enable a different theme and then go back to themes and enable your custom theme
problem fixed.
It would be nice if the recipe worked first.
There must be something in the recipe file that needs to be changed that is being missed.

**Comment by JoshTango** [comment]
Here is the top part of my recipe

{
  "name": "TheCombinationRecipe",
  "displayName": "The Combination Theme",
  "description": "Ready to use company website.",
  "author": "The Combination Team",
  "website": "https://somesite.net",
  "version": "2.0",
  "issetuprecipe": true,
  "categories": [ "default" ],
  "tags": [ "agency" ],

  // The variables are evaluated the first time they are accessed, and reused across steps
  "variables": {
    "landingContentItemId": "[js:uuid()]"
    // "now": "[js: new Date().toISOString()]"
  },

  "steps": [
    {
      "name": "feature",
      "disable": [],
      "enable": [
        // SaaS
        "OrchardCore.HomeRoute",
        "OrchardCore.Admin",
        "OrchardCore.Diagnostics",
        "OrchardCore.DynamicCache",
        "OrchardCore.Features",
        "OrchardCore.Navigation",
        "OrchardCore.Recipes",
        "OrchardCore.Resources",
        "OrchardCore.Roles",
        "OrchardCore.Settings",
        "OrchardCore.Themes",
        "OrchardCore.Users",

        // Content Management
        "OrchardCore.Alias",
        "OrchardCore.Autoroute",
        "OrchardCore.Html",
        "OrchardCore.ContentFields",
        "OrchardCore.ContentPreview",
        "OrchardCore.Contents",
        "OrchardCore.Contents.FileContentDefinition",
        "OrchardCore.ContentTypes",
        "OrchardCore.CustomSettings",
        "OrchardCore.Deployment",
        "OrchardCore.Deployment.Remote",
        "OrchardCore.Feeds",
        "OrchardCore.Flows",
        "OrchardCore.Layers",
        "OrchardCore.Lists",
        "OrchardCore.Liquid",
        "OrchardCore.Markdown",
        "OrchardCore.Media",
        "OrchardCore.Menu",
        "OrchardCore.Queries",
        "OrchardCore.Title",
        "OrchardCore.Templates",
        "OrchardCore.Widgets",

        // Themes
        "TheAgencyTheme",
        "TheAdmin",
        "SafeMode"
      ]
    },
    {
      "name": "themes",
      "admin": "TheAdmin",
      "site": "TheCombinationTheme"
    },
    {
      "name": "settings",
      "HomeRoute": {
        "Action": "Display",
        "Controller": "Item",
        "Area": "OrchardCore.Contents",
        "ContentItemId": "[js: variables('landingContentItemId')]"
      },
      "LayerSettings": {
        "Zones": [ "Footer" ]
      }
    },

**Comment by JoshTango** [comment]
Ok I think I found the issue for #3346 and mine , will report soon if I am sure

**Comment by deanmarcussen** [comment]
Your `CombinationTheme` isn't listed in the features block
```
    // Themes
    "TheAgencyTheme", <= probably remove this line
    "TheAdmin",
    "SafeMode",
    "CombinationTheme" <= Add this line
```

**Comment by JoshTango** [comment]
yes that's the issue, I just found that out and I think its the same thing for #3346
