### ISSUE TITLE
Hint banners

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#5478]
In the Widgets page, we could display a banner with a link to the settings, by default, but that any user could "discard" so it doesn't show up later on. Probably stored on the user profile such that it flows across browser.

This pattern could be applied in many screens, like Search too.
Some settings page would allow to see/change/reset the choices in the admin (optional).

**Comment by Piedone** [comment]
What kind of settings do you mean would it link to?
