### ISSUE TITLE
The process cannot access the file 'App_Data\Sites\Default\ContentDefinition.json' because it is being used by another process.

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#5480]
Hi,

Sometimes when I modify the ContentDefinition in dashboard, this exception occurred:

    The process cannot access the file 'Xxxxxx\App_Data\Sites\Default\ContentDefinition.json' because it is being used by another process.

It happened multi times, a simple retry will be work.

Orchard Core version: dev branch 20200206

**Comment by sebastienros** [comment]
Could it be that there is an anti-virus running? Or that another server process is running on the same file system, in which case you need to use the Database version of this file.

**Comment by RockNHawk** [comment]
@sebastienros Yes `Avast` and `HuoRong` (https://www.huorong.cn/) is runing, and no multi Orchard process running, this file can be a database ?

**Comment by sebastienros** [comment]
So one of your antivirus is reading the file ... and potentially more with its content ...
Try to disable the antivirus or exclude your orchard folder from it.
Or just use Windows Defender, it's very good, and you can define exclusions.

**Comment by RockNHawk** [comment]
It seems that it is really caused by anti-virus software, it works fine after publishing to the server.
Thank you !!
