### ISSUE TITLE
Documentation Bug Maybe - Custom Theme Docs need a note about tenant enabling 

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5483]
This is in regards to #3346 and #5476
If you make a custom theme and want to use it in a tenant as part of a recipe you must enable it.
The reason why this is not understood is because most people including myself made a custom theme project and then referenced it in our main web app.  Because we referenced it I am going to guess it did not need to be "enabled".  This is why nobody saw a problem when they ran their recipe in non tenant mode.

The problem only materializes when you try to run the same recipe as a tenant.

**Comment by agriffard** [comment]
Would you like a note to be added after these sections to explain that if you create a new theme, you need to enable it in the Feature step? :
https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Recipes/#feature-step
https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Recipes/#themes-step

**Comment by JoshTango** [comment]
I will leave it up to you, I am just explain what lead to the issue
generally speaking I think its bad to develop a recipe against a non tenant based on what I am learning about orchard core, I am now developing a recipe using tenants only

**Comment by JoshTango** [comment]
Actually I think a note should go in the custom theme documentation
