### ISSUE TITLE
LINUX DEEPIN UOS:dotnet publish error : Failed to retrieve information about from remote source 

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#5485]
LINUX DEEPIN UOS:dotnet publish error : Failed to retrieve information about from remote source 

![截图录屏_dde-desktop_20200208142159](https://user-images.githubusercontent.com/28694676/74080372-63dd3e80-4a7e-11ea-9ee1-86b810f900c0.jpg)
![截图录屏_dde-desktop_20200208141541](https://user-images.githubusercontent.com/28694676/74080373-650e6b80-4a7e-11ea-945a-1023afa90e3a.jpg)

[dotnet publish.txt](https://github.com/OrchardCMS/OrchardCore/files/4173853/dotnet.publish.txt)

**Comment by Skrypt** [comment]
Looks like a temporar network issue. Maybe having issue reaching MyGet servers.

**Comment by pgy866** [comment]
After several attempts in the virtual machine UOS (linux deepin uos), the problem still exists.
It is normal to open those timeout or wrong links in the browser.

When the virtual machine WINDWOS server 2019 is normal.

What went wrong?
@Skrypt 
![截图录屏_选择区域_20200208173942](https://user-images.githubusercontent.com/28694676/74083049-aa409680-4a9a-11ea-8724-dfc3e8014c77.gif)

**Comment by Skrypt** [comment]
I can't really say. I'm not even sure this OS is supported or not by Microsoft for .NET Core. This is something you need to look at with those who built this Linux Distro I think. You could run OC inside Docker instead too. That be more lightweight than a full blown Linux distro with a desktop. And this could be an issue with VMWare and the network stack of Linux Deepin UOS. There's many possibilities.

**Comment by pgy866** [comment]
WINDOWS can be built normally. In a previous version of ORCHARD, it could be built in Linux DEEPIN UOS.

The following is built in WINDOWS, and runs perfectly in linux deepin uos,

But in Linux deepin uos build is not successful, I do not know what the problem is? ? ?

![截图录屏_dde-desktop_20200208225817](https://user-images.githubusercontent.com/28694676/74087420-05887e00-4ac7-11ea-9fbc-0235715dbbdd.gif)

**Comment by Skrypt** [comment]
We had issues with the Myget server last week. It could be related. Make sure you are trying to build latest dev since now it’s fixed

**Comment by pgy866** [comment]
Today, I re-downloaded the test and installed CORE 2.1 and 2.2. The normal build was great. Put a few test charts, thank you  @@skrypt


![1](https://user-images.githubusercontent.com/28694676/74130736-b739c300-4c1d-11ea-9523-617ddd04a49d.gif)
![2](https://user-images.githubusercontent.com/28694676/74130740-b86af000-4c1d-11ea-8c28-732100fa055f.gif)
![3](https://user-images.githubusercontent.com/28694676/74130742-b99c1d00-4c1d-11ea-8ded-45c7cc834b62.gif)
![4](https://user-images.githubusercontent.com/28694676/74130765-ccaeed00-4c1d-11ea-818e-c6468d98d2a7.jpg)
