### ISSUE TITLE
Question: Domain Pointers in regards to tenants

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5488]
If we host a multi tenant application using Orchard Core I assume we dont need to make use of the hosters domain pointers or redirects mechanisms because Orchard will automatically take care of this for us if we enter the hostnames?

I want people to be able to point their custom domains names to their corresponding tenant sub folder.

Is this correct?

**Comment by deanmarcussen** [comment]
Yes. Please follow the directions on the hint when creating a tenant.

`Example: If host is "orchardproject.net", the tenant site URL is "https://orchardproject.net/" You may define multiple domains using the comma (,) as a separator. Use the '*.' prefix to map all subdomains.`

Please ask questions like this on https://gitter.im/OrchardCMS/OrchardCore there are many people there who will help
