### ISSUE TITLE
Export/Import Smtp Settings and decrypt Global method

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5493]
There should be a Deployment step to export the SMTP settings.

As it can contain some credentials (user/password), it would be interesting to have a way to specify an encrypted string for the password and a `[js:decrypt(...)]` Global method that you can use in the recipe.

What kind of encryption should we use?
Would there be an admin page to generate an encrypted string?

**Comment by hishamco** [comment]
May be I will implement this one

**Comment by agriffard** [comment]
Related to #5325 to export all missing site settings.

**Comment by agriffard** [comment]
I started to look at it: Import/Export Smtp Settings.

**Comment by hishamco** [comment]
Ok it's your Antoine if you are already started
