### ISSUE TITLE
Workflow token: Global method

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5495]
There should be a `[js:workflowtoken()]` Global method to generate a workflow token.

That would allow you to assign it in a variable of recipe and use it in a Http request event and in a Form url action.

**Comment by sebastienros** [comment]
I think it's more than a token that is necessary, more the url to hit this workflow activity (and it will contain the SAS token)

**Comment by agriffard** [comment]
Use Secrets
