### ISSUE TITLE
how about encripting the content from client(Form, Driver..) or URL for whole site?

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#5497]
I know we can have https.
but how about getting double insurance?
I think the same base code can be used for #5495, #5493
This is only for server side Razor, Blazor.
For SPA, we use Interface to default it doing nothing

**Comment by sebastienros** [comment]
Can you provide more example of what you would like ? I don't totally understand this question

**Comment by infofromca** [comment]
something like those:
https://www.codeproject.com/articles/519301/automatic-encryption-of-secure-form-field-data
https://www.c-sharpcorner.com/uploadfile/4d9083/encrypt-in-javascript-and-decrypt-in-c-sharp-with-aes-algorithm-i/
--------
and also for URL

**Comment by sebastienros** [comment]
Https is the ony way. If you need something different then you will have to build it yourself, it won't be out of the box in OC.
