### ISSUE TITLE
how about creating a base project

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#5498]
move all of utilities, ..... inside it as a dll
and even other sln can use it
ref #5497

**Comment by sebastienros** [comment]
It's already published as a nuget packages, what else do you need?

**Comment by infofromca** [comment]
internal static async Task<bool> SendEmailAsync(this Controller controller, string email, string subject, IShape model)

under 
namespace OrchardCore.Users.Controllers
{
    internal static class ControllerExtensions
should be in more general place

**Comment by Piedone** [comment]
Given that only the Users module sends e-mails from a shape, the use case doesn't seem generic enough.

Related: https://github.com/OrchardCMS/OrchardCore/pull/14772.
