### ISSUE TITLE
Notification Hub

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5500]
An example of use could be to have a Notification Hub that allows you to send a notification to everyone that is currently on an admin page.

We would add a Toast UI library and a Workflow task that could trigger a new notification.

And maybe a chat room between users and could also a good feature to add.

**Comment by sebastienros** [comment]
For notifications we could adapt the current notifications to be able to target all users, with a timeout such that they are not displayed too long in the future. On a refresh this list can just be rendered, and not cleared like we do for the current notifications.

**Comment by miguelhasse** [comment]
I've recently built a module to support sending events thru SignalR (On-premesis or Azure SignalR Services) and Notificatio Hubs.
Code available here... https://github.com/miguelhasse/OrchardCoreContrib

**Comment by agriffard** [comment]
https://docs.orchardcore.net/en/latest/docs/reference/modules/Notifications/
