### ISSUE TITLE
App Metrics module

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5501]
I really like https://www.app-metrics.io/ that allows you to manage metrics like counters, gauges, and data series in general.

We could find different uses of library:
- Create dashboards and graphs.
- Manage global counters with tags.
- Create workflow activities to send data.

If it is not something that we want in the core solution, I could do it in a custom module.

**Comment by sebastienros** [comment]
- API to gather metrics, that any module could use to store data. For instance the Ecommerce module would record when a user add an item in the cart, or fulfills a sale. Or when a user logs in, successfully or  not. This is what AppMetrix does, and also knows how to store these in different stores.
- Tools to configure visualizations of the stored data, in dashboard for instance. A user would then create a KPI for sales. But a module could also provide pre-defined templates based on the data it gathers. We could limit it to a small set of widgets, as more advanced usages would require dedicated apps (Kibana, Graphana, PowerBI)

**Comment by agriffard** [comment]
A new Metrics Api will be added in .NET 6, based on open telemetry:
https://devblogs.microsoft.com/dotnet/new-dotnet-6-apis-driven-by-the-developer-community/#new-metrics-api

**Comment by stoyandimov** [comment]
> A new Metrics Api will be added in .NET 6, based on open telemetry: https://devblogs.microsoft.com/dotnet/new-dotnet-6-apis-driven-by-the-developer-community/#new-metrics-api

Yep, it's there now: [Collect metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection) and there is already [Prometheus exporter for OpenTelemetry](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection#configure-the-example-application-to-use-opentelemetrys-prometheus-exporter)
