### ISSUE TITLE
JS function executeQuery() result not usable

### ISSUE THREAD

**Issue by mawendel** [OrchardCMS/OrchardCore#5510]
The javascript function:
executeQuery(name: String, parameters: Dictionary<string,object>): IEnumerable<object>

..returns an object that i'm unable to get a length/count or data[x] on. I've tried a number of different things to try and achieve this.

Reproduction is simple. 
1. Create a SQL Query that returns X amount of hits (return documents not enabled). 
2. Use executeQuery in a Workflow SetProperty task and save it. 
```
"Results": [
        {
          "DocumentId": 461
        },
        {
          "DocumentId": 3025
        },
        {
          "DocumentId": 3027
        },
        {
          "DocumentId": 3030
        },
        {
          "DocumentId": 3033
        }
      ]

```

3. Test using a Workflow Script Task as shown below

```
// [Source](https://stackoverflow.com/questions/5223/length-of-a-javascript-object/6700#6700)
Object.size = function(obj) {
    var size = 0, key;
    for (key in obj) {
        if (obj.hasOwnProperty(key)) size++;
    }
    return size;
};

var result = property("ExecuteQueryResult");

output("result.type", typeof result);
output("result.length", result.length);
output("result.Object.keys.length", Object.keys(result).length);
output("result.Object.size", Object.size(result));
output("result[0]", result[0]); // crash with "No matching indexer found."
output("result.parse", JSON.parse(result)); // crash with "No matching indexer found."
```

After execution STATE shows
```
    "Output": {
      "result.type": "object",
      "result.length": null,
      "result.Object.keys.length": 0.0,
      "result.Object.size": 0.0
    },

```

I would expect to be able to do a count of the array and to iterate through the items as i normally would in javascript. But none of these methods seems to work here.

The js method ".length" seems to only work with integer arrays, so it makes sense that the non-integer result for executeQuery wouldnt work here. 

But what to do then?

**Comment by MichaelPetrinolis** [comment]
Try var arr=new Array(query Results)

**Comment by mawendel** [comment]
@MichaelPetrinolis that seems to work, thanks!
I would still say that the object itself should be presented as an array from the start from OC. But at least this way it is possible to make it yourself.

An example of how to do this could be added to the docs in the meantime.
