### ISSUE TITLE
Timezone mismatch on MacOS

### ISSUE THREAD

**Issue by ltvan** [OrchardCMS/OrchardCore#5511]
On Mac, netcore 3.1, I tried Clock.GetSystemTimeZone(), it returns "Asia/Saigon". While Clock.GetTimeZones() returns "Asia/Ho_Chi_Minh". This leads to incorrect active timezone dropdown in Setup page.

The GetSystemTimeZone() should use canonical ID in order to get proper ID.

```csharp
TzdbDateTimeZoneSource.Default.CanonicalIdMap[currentTimezone.Id]
```

**Comment by Skrypt** [comment]
Maybe worth looking if you are right. Though last time I checked it was an issue related with Mac OS and Mono not retrieving the proper culture in the system vars of the OS.

**Comment by ltvan** [comment]
This fixes my case:

```diff
diff --git a/src/OrchardCore/OrchardCore/Modules/Services/Clock.cs b/src/OrchardCore/OrchardCore/Modules/Services/Clock.cs
index 9b5de58434db4b36283707f8ebe1f6ae5b410e97..57c28da81386d746f7f0ed73e884d8374ae26fb7 100644
--- a/src/OrchardCore/OrchardCore/Modules/Services/Clock.cs
+++ b/src/OrchardCore/OrchardCore/Modules/Services/Clock.cs
@@ -49,6 +49,11 @@ namespace OrchardCore.Modules
         public ITimeZone GetSystemTimeZone()
         {
             var timezone = DateTimeZoneProviders.Tzdb.GetSystemDefault();
+            if (TzdbDateTimeZoneSource.Default.CanonicalIdMap.ContainsKey(timezone.Id))
+            {
+                var canonicalTimeZoneId = TzdbDateTimeZoneSource.Default.CanonicalIdMap[timezone.Id];
+                timezone = GetDateTimeZone(canonicalTimeZoneId);
+            }
             return CreateTimeZone(timezone);
         }
```

**Comment by Skrypt** [comment]
That's a patch but should it not already return it from `DateTimeZoneProviders.Tzdb.GetSystemDefault()`?

**Comment by Skrypt** [comment]
`Asia/Ho_Chi_Minh` is the canonical timezone.
Though DateTimeZoneProviders.Tzdb.GetSystemDefault() returns `Asia/Saigon` which is not a canonical time zone it's an "alias" time zone.

![image](https://user-images.githubusercontent.com/3228637/74212567-c727c600-4c62-11ea-9c16-9cc811688834.png)

So here the proper thing is to use `Asia/Ho_Chi_Minh`. I'd say that this would be an appropriate fix but we need to test what will happen on Windows and Linux if we do this change.
