### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by dewebeloper** [OrchardCMS/OrchardCore#5513]
Hi, 
I'm newbie in OrchadCore, but great tool. 
I start to use CMS and found on strange behavior. When I create content type (Site Default Page) and then create content based on that content type on Manage Content page in list I get two same names for page.
Version: OrchardCore.Application.Cms.Targets 1.0.0-rc1-11937

![screenshot-localhost_5001-2020 02 10-14_50_29](https://user-images.githubusercontent.com/3725912/74155931-a7b67c00-4c15-11ea-8efc-69ba3a42eee4.png)

**Comment by sfmskywalker** [comment]
I think that’s by design. There is a TitlePart that you should add, whose handler will provide the content item’s display text.

**Comment by dewebeloper** [comment]
Looks like you are right :)
