### ISSUE TITLE
Multiple Select in Content Item -> List

### ISSUE THREAD

**Issue by kyahyan** [OrchardCMS/OrchardCore#5514]
Select item -> Bulk Action

![Screen Shot 2020-02-10 at 11 46 19 PM](https://user-images.githubusercontent.com/23460968/74165159-a6aa3c80-4c5f-11ea-9f81-87a9261be9d4.png)

**Comment by agriffard** [comment]
The Bulk Actions list is available when at least 2 checkboxes are selected.
When you want to run an action on only one content, use an action button on each line.
