### ISSUE TITLE
Support SendGrid as Email SMTP provider

### ISSUE THREAD

**Issue by dansiegel** [OrchardCMS/OrchardCore#5515]
Some servers may not support a local pickup directory and you may not want to constantly be authenticating with your email account's SMTP server. It would be great to have a built in option here that supports SendGrid out of the box as it is a commonly used provider and generally the go to for apps hosted in Azure.

**Comment by Skrypt** [comment]
Sendgrid should work without an issue.

**Comment by dansiegel** [comment]
@Skrypt is there documentation on this somewhere where/how to configure it? I hadn't seen any.

**Comment by Skrypt** [comment]
On the SMTP settings you should be able to enter your Sendmail mail server credentials just like you would do with any mail server.

**Comment by dansiegel** [comment]
@Skrypt perhaps one of us is missing something. To the best of my knowledge SendGrid does not offer a classic SMTP endpoint... hence the issue here... They work via a web api with an [auth token](https://github.com/sendgrid/sendgrid-csharp#hello-email)...

**Comment by sfmskywalker** [comment]
@dansiegel Sendgrid most certainly supports the SMTP protocol, in addition to its HTTP apis.

**Comment by sfmskywalker** [comment]
https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html

**Comment by sfmskywalker** [comment]
Here’s a better guide: https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html

**Comment by dansiegel** [comment]
@sfmskywalker thanks for that... I had been looking for something like that but hadn't found those docs... Thanks for pointing me in the right direction!
