### ISSUE TITLE
Liquid "limit" and "offset" No Longer Work

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#5517]
In earlier versions of Orchared Core (maybe it is Fluid related, not sure) "limit" and "offset" worked fine. However, using this made up example you can test that it no longer works:

```
{% assign array = '1,2,3,4' | split: ',' %}
{{ array | size }} {% comment %} outputs 4 {% endcomment %}
{% for item in array limit:2 %} 
  {{ item }}
{% endfor %}
{% for item in array offset:2 %} 
  {{ item }}
{% endfor %}
```

Instead, it throws this error:

```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
```

The issue stems from the "limit" filter or "offset" filter (both used to work and now neither seems to). I have not traced it back to see if it is Orchard Core or Fluid...

**Comment by hishamco** [comment]
Could you please check Fluid unit tests?

**Comment by jeffolmstead** [comment]
@hishamco the Fluid unit tests on https://github.com/sebastienros/fluid seem fine (I downloaded and stepped through them even). I expected they would as this used to work in Orchard Core but no longer does. Do you know where in Orchard Core the expression get's passed over to the Fluid DLL for analysis? I suspect something there is preventing "limit" and "offset" from functioning properly.

**Comment by jeffolmstead** [comment]
@hishamco actually, I will have to change my prior statement. It is crashing on the Fluid side in the DefaultFluidParser. In the "BuildForStatement" method you have this:

```
foreach (var option in context.Tag.ChildNodes[2].ChildNodes)
{
    switch (option.Term.Name)
    {
        case "limit":
            limit = BuildExpression(option.ChildNodes[0]);
            break;
        case "offset":
            offset = BuildExpression(option.ChildNodes[0]);
            break;
        case "reversed":
            reversed = true;
            break;
    }
}
```

And this line in particular you select the first ChildNode:
```
limit = BuildExpression(option.ChildNodes[0]);
```

However, in the "BuildExpression" method, you again select the first ChildNode (which doesn't exist and throws an error):

```
public static Expression BuildExpression(ParseTreeNode node)
{
    var child = node.ChildNodes[0];
```

I suspect the change should be made like this (on "BuildForStatement" method):
```
case "limit":
    limit = BuildExpression(option);
    break;
case "offset":
    offset = BuildExpression(option);
    break;
```
I tried it out and that change makes everything work. Should this issue request be transferred over to the Fluid repository or can it be addressed from here?

**Comment by hishamco** [comment]
Could you please try your change at Fluid side and create a unit test to ensure it doesn't break anything, otherwise I will have a look

**Comment by jeffolmstead** [comment]
I have a pull request here: https://github.com/sebastienros/fluid/pull/175

**Comment by sebastienros** [comment]
We just need to update Fluid

**Comment by agriffard** [comment]
@sebastienros  The PR sebastienros/fluid#175 has been merged 13 days ago but there is no package on nuget after https://www.nuget.org/packages/Fluid.Core/1.0.0-beta-9634 2 months ago.

**Comment by sebastienros** [comment]
Forgot to merge to master. Done now, so it should be available soon.
