### ISSUE TITLE
OPTIONS HTTP Request to connect/token returns 400 Bad Request.

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#5518]
Hi,

I make a `OPTIONS` request to `connect/token` in Postman, OpenId Server returns 400 Bad Request, if I change to `POST` request, it works well.

    {
        "error": "invalid_request",
        "error_description": "The specified HTTP method is not valid."
    }

![image](https://user-images.githubusercontent.com/3222379/74211065-3e904080-4cc9-11ea-8758-d15d9a99421f.png)

if I change to `POST` request, it works well:
![image](https://user-images.githubusercontent.com/3222379/74211152-8d3dda80-4cc9-11ea-87e9-b4a37d074104.png)

The OpenId Client is a browser application in another domain, so the openId Login request must make a `OPTIONS` request, but now can't send `OPTIONS` request to OpenId Server.

**Comment by RockNHawk** [comment]
I have add Cors options in Startup.cs in main application, sitll have this issue:

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();

            var origins = new[]
            {
                "https://localhost:44300/",
                "http://localhost:2918/",
                "http://localhost:8081/"
            };
            services.AddCors(options =>
                options.AddPolicy("AllowAnyCorsPolicy2", builder => builder.AllowAnyHeader()
                    //.AllowAnyOrigin()
                    .WithOrigins(origins)
                    /*
                     * The CORS protocol does not allow specifying a wildcard (any) origin and credentials at the same time.
                     * Configure the CORS policy by listing individual origins if credentials needs to be supported.
                     */
                    .AllowCredentials() // fix mvc sec limit
                    .AllowAnyHeader()
                    .AllowAnyMethod())
            );
        }

        public void Configure(IApplicationBuilder app, IHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();

            app.UseOrchardCore();

            app.UseCors("AllowAnyCorsPolicy2");
        }

**Comment by RockNHawk** [comment]
I'v found that no header add to Response with app.UseCors("AllowAnyCorsPolicy2") in Orchard Core (it works in normal ASP.NET Core project), I use a mibbleware to force add Header to response resolved my problem.

    public class CorsMiddleware
    {
        private readonly RequestDelegate _next;

        public CorsMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public Task Invoke(HttpContext httpContext)
        {
            var origins = new[]
            {
                "https://localhost:44300/",
                "http://localhost:2918/",
                "http://localhost:8081/"
            };

//            httpContext.Response.Headers["Access-Control-Allow-Origin"] = string.Join(",", origins);
            httpContext.Response.Headers["Access-Control-Allow-Origin"] = "*";
            httpContext.Response.Headers["Access-Control-Allow-Headers"] = "*";
//            httpContext.Response.Headers["Access-Control-Allow-Headers"] = string.Join(",", new []
//            {
//                "Content-Type","Accept","Authorization","X-Requested-With"
//            });
            httpContext.Response.Headers["Access-Control-Allow-Methods"] = "*";


            return _next.Invoke(httpContext);
        }
    }


    public class Startup : StartupBase
    {

        public override void Configure(IApplicationBuilder builder, IEndpointRouteBuilder routes,
            IServiceProvider serviceProvider)
        {
            builder.UseMiddleware<CorsMiddleware>();
        }
    }

**Comment by kevinchalet** [comment]
> I make a OPTIONS request to connect/token in Postman, OpenId Server returns 400 Bad Request, if I change to POST request, it works well.

It's 100% expected: OpenIddict - the OIDC implementation used by Orchard - will reject all the requests that don't use the POST verb, as required by the specification.

I'm not really surprised your custom "CORS middleware" has no effect, as it doesn't handle OPTIONS/preflight requests: they'll still be handled by OpenIddict later in the pipeline and you'll still get an error.

That said, it should work with the official ASP.NET Core CORS middleware (used in your previous post). If it doesn't, try to tweak the `Order` of your custom Orchard module to ensure it's executed early enough (i.e before OpenIddict rejects the preflight request).

**Comment by RockNHawk** [comment]
Cors request is necessary in a corss-domain web client, so it's a general requirement.

**Comment by kevinchalet** [comment]
Closing, as I believe I answered your question (i.e change the order of your custom module using the official ASP.NET Core CORS middleware to ensure it's called early enough). If it still doesn't work, feel free to reply here and I'll reopen the thread.

**Comment by RockNHawk** [comment]
> Closing, as I believe I answered your question (i.e change the order of your custom module using the official ASP.NET Core CORS middleware to ensure it's called early enough). If it still doesn't work, feel free to reply here and I'll reopen the thread.

Okay, I will have a try, thank you very much !
