### ISSUE TITLE
Trumbowyg is broken: Cannot read property 'x-small' of undefined

### ISSUE THREAD

**Issue by marc3lsk** [OrchardCMS/OrchardCore#5522]
With latest preview nuget, when I choose trumbowyg as HTML editor, there is only empty textarea with following error in console:
Uncaught TypeError: Cannot read property 'x-small' of undefined
    at String.<anonymous> (trumbowyg-plugins.js?v=4PAOJjGgwwaNinsO0B7XBZrJ9d_lTVizlnxiHBl3eac:1531)
    at Function.each (jquery-3.4.1.js:367)
    at t (trumbowyg-plugins.js?v=4PAOJjGgwwaNinsO0B7XBZrJ9d_lTVizlnxiHBl3eac:1529)
    at Object.init (trumbowyg-plugins.js?v=4PAOJjGgwwaNinsO0B7XBZrJ9d_lTVizlnxiHBl3eac:1741)
    at Object.<anonymous> (trumbowyg.js:1910)
    at Function.each (jquery-3.4.1.js:373)
    at Trumbowyg.initPlugins (trumbowyg.js:1908)
    at Trumbowyg.init (trumbowyg.js:476)
    at new Trumbowyg (trumbowyg.js:460)
    at HTMLTextAreaElement.<anonymous> (trumbowyg.js:144)

file: OrchardCore.Modules\OrchardCore.Resources\Assets\trumbowyg\plugins\fontsize\trumbowyg.fontsize.js
line 222: text: '<span style="font-size: ' + size + ';">' + (trumbowyg.lang.fontsizes[size] || size) + '</span>',

**Comment by agriffard** [comment]
Not yet solved. It only works when the current culture is different than `en` for the moment.

**Comment by ChocoMachine** [comment]
We have this issue again in Version="1.0.0-rc2-13809"...

![image](https://user-images.githubusercontent.com/7971514/87390481-48a5ca80-c5ec-11ea-8303-fe3f827aa0b9.png)

**Comment by ChocoMachine** [comment]
![image](https://user-images.githubusercontent.com/7971514/87391029-5445c100-c5ed-11ea-9b60-f48fbc9bd2c6.png)


and lang = "ltr"
![image](https://user-images.githubusercontent.com/7971514/87391145-8c4d0400-c5ed-11ea-99cb-d9331549cc5c.png)

**Comment by deanmarcussen** [comment]
Yes, I just fixed the issue here for another pr.

Someone has added this code in a few places.
```
        jQuery.trumbowyg.langs.@culture.TwoLetterISOLanguageName = {
            _dir: '@culture.GetLanguageDirection()'
        };
```

which is overwriting the entire trumbowyg lang dictionary.

Equally I don't understand what adding this `_dir` would do to trumbowyg.

@hishamco did you add this?

the fix is to do this instead
```
        var langs = jQuery.trumbowyg.langs.@culture.TwoLetterISOLanguageName;
        langs['_dir'] = '@culture.GetLanguageDirection()';
```

but I would like to know what adding this achieves

**Comment by hishamco** [comment]
If I'm not wrong I did that long time ago, for RTL issues, but what's the wrong with that, while it relies on the current culture?

**Comment by deanmarcussen** [comment]
> If I'm not wrong I did that long time ago, for RTL issues, but what's the wrong with that, while it relies on the current culture?

Ok, yes, i had a read of the trumbowyg docs.

The problem here (and in their docs) is you have replaced the entire trumbowyg lang dictionary, where you needed to just add a key.

I fixed it in https://github.com/OrchardCMS/OrchardCore/pull/6661

**Comment by hishamco** [comment]
I see, thanks

**Comment by hishamco** [comment]
> @hishamco did you add this?

#4709
