### ISSUE TITLE
should we set the maxCount as 1 in the SemaphoreSlim

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#5523]
for example, in the ModularTenantRouterMiddleware.cs, should we use new SemaphoreSlim(1,1);

 ```
private void InitializePipeline(ShellContext shellContext)
        {
            var semaphore = _semaphores.GetOrAdd(shellContext.Settings.Name, (name) => new SemaphoreSlim(1));

            // Building a pipeline for a given shell can't be done by two requests.
            semaphore.Wait();
```

**Comment by sebastienros** [comment]
@jtkech  ? The documentation confuses me

**Comment by jtkech** [comment]
That's okay

The semaphore counter value is the number of threads that are not blocked
The `initialCount` set an initial value to this counter (we use 1)
`Wait()` decrements the counter and `Release()` increments the counter

Based on some logic, this is when we use e.g `Release(n)`, incrementing the counter n times, that `maxCount` (max value of the counter) may be useful.

But we always use `Wait()` and `Release()` in pair, so the semaphore counter is equal to 1, then 0, then 1, then 0, then 1 and so on. So in our case the `maxCount` can be anything that is >= 1.
