### ISSUE TITLE
Domain path

### ISSUE THREAD

**Issue by dewebeloper** [OrchardCMS/OrchardCore#5524]
I'm trying to setup OpenGraph tags and I stuck with image full path.
How I get domain path in order to get full image path like https>//www.domainname.com/media/image.jpg in liquid template?

**Comment by deanmarcussen** [comment]
I use the `Site.BaseUrl` property for this.

You can set it in the admin under the Configuration -> Settings -> General menu

**Comment by dewebeloper** [comment]
Cool. Thanks.
Is there any way how I can define some other KeyValue variables?

**Comment by deanmarcussen** [comment]
The custom settings module is really good for that
https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/CustomSettings/

or if you are making your own module you can also make your own site settings for the module.

Have a look at the `OrchardCore.Demo` module for some examples of that

**Comment by dewebeloper** [comment]
Cool. Thanks,.
