### ISSUE TITLE
Make User.Id to String type

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#5527]
I saw `User.Id` entity is a `int` type, it's not friendly to some application, `String` is more flexible than `int` and can adapt to more application scenarios, Orchard Core project possible to change `User.Id` to a `String` type ?

**Comment by Skrypt** [comment]
This is not supposed to be an issue and there will be some refactoring of the IUser done before shipping OC 1.0. I'm closing this as an int or a string should never be an issue. What we need is a unique immutable identifier which will be a "guid" string.

**Comment by RockNHawk** [comment]
@Skrypt yes,if `Id` is a string type, we can make Guid or TimeStamp+Seq as the `Id`

**Comment by Skrypt** [comment]
Yes, but like I said I'm closing because we have other issues that elaborates about this issue. And we will probably use a uuid like we do with content items.

**Comment by RockNHawk** [comment]
Thank you for taking the time to answer!
