### ISSUE TITLE
Menu item with Display rule

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5530]
Would it be possible to implement a MenuItem that has a display Rule, like the one in a Layer, in which we can set a globalMethod that returns a boolean? 
Or would there be a performance issue or a conflict with the caching?

**Comment by sebastienros** [comment]
It's doable, but then the menu tag will need to be changed such that the cache depends on the role. Or anything that could vary within the menu.

**Comment by vip924** [comment]
Is there any way to show and hide menu items based on the roles given to the content items?

I have created 2 content types and linked them to 2 menu items in the Orchard Core menu content type.

I added a new role, set permission to only a specific content item and removed the view permission of the other content item.

Still, both the content items are shown in the menu. But the 2nd content item is now showing "You do not have access to this resource." in the view page when I click the menu.
