### ISSUE TITLE
Reduce allocations on IAsyncResultFilters

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5532]
While working on the display options for parts and fields I noticed how many requests (more so to the admin, than a content item display request) are creating a lot of unnecessary allocations, particularly around the use of `IAsyncResultFilters` 

An admin request to edit a page will often make 3-4 requests, the first to retrieve the content, then subsequent to retrieve media from the MediaController. These later request are not `ViewResult` or `PageResult` so the `Layers` filter and the `AdminMenuFilter` passes on these almost immediately.

In the case of the `AdminMenuFilter` it injects the `INavigationManager` which in turn injects all the `INavigationProviders` etc.

However these filters are instance per request, so the constructor injected dependencies are instantiated for every request, even though for a lot of requests, these filters will no-op very quickly, and never use the dependencies

It might an over optimisation, but suggest we consider refactoring to resolve necessary dependencies from the service provider, after the filter has chosen to execute, rather than no-op

**Comment by jtkech** [comment]
Yes, looks like a good idea, so we would have to resolve them dynamically through a scoped provider, and maybe cache them in local variables of the related scoped service, if it may be called multiple times.

We already do this in some services where we cache the scoped resolutions, as i remember particularly when we are using `ShellScope.Services` for the scoped service provider.
