### ISSUE TITLE
Ajax call to 'api/queries/{name}' fails

### ISSUE THREAD

**Issue by sht1rlitz** [OrchardCMS/OrchardCore#5533]
Hello everyone,

I'm currently trying to receive query results using an AJAX call:
```javascript
var products = $.ajax({
            type: "POST",
            url: "api/queries/ProductList",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: JSON.stringify({ parameters: { from: 0, size: 8 }}),
        });
```
but it fails with _"System.InvalidCastException: Null object cannot be converted to a value type."_

This happens because ```Task<IActionResult> Query( string name,  string parameters)``` always get ```parameters``` equals to ```null``` and instantiate an empty ```Dictionary```.

 ```LuceneQueryService``` tries to get the value at the ```var size = sizeProperty?.Value<int>() ?? 50;``` line and fails.

All the required permissions for Queries are granted.
Could someone point me on what I'm doing wrong, please?

**Comment by Skrypt** [comment]
JSON.stringify({ from: 0, size: 8 })

**Comment by sht1rlitz** [comment]
Hi Skrypt,
I've already tried this case too, but result unfortunately is the same.

**Comment by sht1rlitz** [comment]
Hasn't anyone faced this issue? I guess requesting query result via ajax is a widespread scenario.
Perhaps, it is not a bug, but rather a documentation gap.

**Comment by sht1rlitz** [comment]
Hello everyone,

I've figured out, that current implementation only allows querying results with GET, like
```javascript
var products = $.getJSON( "api/queries/ProductList?parameters={from:0,size:8}");
```
I'm really confused at this moment as I've never seen passing objects into GET query.
Moreover, [current documentation](https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Queries/) assures me that both methods are supported 

> Verbs: POST and GET

So my assumptions were: 
1) If my _Query_ isn't parameterized I'm supposed to use GET-request
2) If I have a complex object as a _Query_ parameter, I need to use POST instead

**Comment by sebastienros** [comment]
>  I've never seen passing objects into GET query

For instance GraphQL supports GETs too, like this.

It would be ok to support POST though and read the parameters from the body (like GraphQL does it too)
