### ISSUE TITLE
Lucene module isn't using my custom Search.liquid view

### ISSUE THREAD

**Issue by markjourdan** [OrchardCMS/OrchardCore#5534]
I have a custom search template for my theme. When I go to the search page, it doesn't render my **search.liquid** template. It seems to be using the default template in the [Lucene module](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Lucene/Views/Search/Search.cshtml)

Here is my template

```
{% zone "Header" %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="masthead" style="background-image: url('{{ "~/MJ.BlogTheme/img/post-bg.jpg" | href }}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>{{ Model.ContentItem.DisplayText }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endzone %}
{{ Model.SearchForm | shape_render }}
{{ Model.SearchResults | shape_render }}
{{ Model.Pager | shape_render }}

```
![image](https://user-images.githubusercontent.com/27870132/74376626-1aeff780-4da8-11ea-9e69-90a9faa231a5.png)

It looks like the header section isn't being rendered from my template.

![image](https://user-images.githubusercontent.com/27870132/74376370-9604de00-4da7-11ea-9313-0b9e19a9fcb7.png)

I expected to see the following header section appear and its not
![image](https://user-images.githubusercontent.com/27870132/74376577-057acd80-4da8-11ea-8c23-e90015be2ed0.png)

**Comment by Skrypt** [comment]
Are you on latest dev?

**Comment by markjourdan** [comment]
I'm on 1.0.0-rc1

**Comment by Skrypt** [comment]
Yeah this won't work on RC1 you need the latest dev as I did the PR and documentation for this.
