### ISSUE TITLE
Media: Delete does not work from Insert popup

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5540]
When you want to insert a Media in a Wysiwyg editor, a popup opens. 
Deleting a media does not work in this popup.

**Comment by agriffard** [comment]
This is because the confirm delete modal dialog is rendered below the media picker.

**Comment by agriffard** [comment]
Still todo: the confirm delete modal dialog is rendered below the media picker.

**Comment by hishamco** [comment]
I just started on this and find the main issue, I will open my laptop and share it with you

**Comment by hishamco** [comment]
The issue comes from media app, especially

https://github.com/OrchardCMS/OrchardCore/blob/37818e468d0a1e1c9a2bac0e2ba46d9df823068e/src/OrchardCore.Modules/OrchardCore.Media/Assets/scss/_modal-view.scss#L46-L51

I did a tiny fix but I need to do more tests to ensure that's working in trumbowyg is full screen and with confirm popup

**Comment by hishamco** [comment]
![ConfirmPopup](https://user-images.githubusercontent.com/3237266/93001216-32f24a00-f536-11ea-9eef-d4dadc2a33c7.gif)

As shown above the confirm popup works fine, but still struggling to make the overlay work as well

**Comment by agriffard** [comment]
Reminder for @hishamco

**Comment by hishamco** [comment]
Thanks for reminder @agriffard, I already started on a PR 3 months ago, but still there are few things I need to manage. Hopefully I can fix it this week, I gave this a low priority in the past

**Comment by agriffard** [comment]
@hishamco Can you please submit a PR to fix this issue?

**Comment by hishamco** [comment]
Sorry @agriffard I started a branch few months agos, but seems I lost the local branch after my old HD is crashed, then I started another one nothing but few things has been changed in the styles, @Skrypt if you want to have a look I will be thankful, coz I'm totally busy with the SQL Parser ;)

**Comment by Skrypt** [comment]
Okay, assign me this one.
