### ISSUE TITLE
Taxonomy Queries

### ISSUE THREAD

**Issue by IamMarek** [OrchardCMS/OrchardCore#5541]
I have a ContentType Post with numeric property Rating and taxonomy property Category. I would like to query all posts in a category ordered by the rating. What is an Orchard way of doing that? 

I've tried: 
```
var items = await _orchardHelper.QueryCategorizedContentItemsAsync(query =>
             {
                 query.Skip(1);
                 query.Take(1);
                 return query
                    .Where(x => x.TermContentItemId == "45vj5vhgfpjk1rpx1e28bja94z");
             });
```
But this does not allow me to order by the rating and get the total query count. Also, I've noticed that the method QueryCategorizedContentItemsAsync retrieves the content items one by one which does not seem to be very efficient.

**Comment by deanmarcussen** [comment]
The `QueryCategorizedContentItemsAsync` is a helper to query specifically against the `TaxonomyFieldIndex` so the where clause is only going to be against the values in the `TaxonomyFieldIndex`

So if you want to do a specific query against the taxonomy field, and another kind of field on the content item you should combine it with the `Content Fields SQL indexing` feature, and make your own `ISession.Query`, which joins against both indexes you want.

As far as I know (having used it regularly) the helper will make one sql call for all content items.

**Comment by IamMarek** [comment]
Thank you! I've created a custom index and index provider according to the `LocalizedContentItemIndexProvider`, created the index table `SchemaBuilder.CreateMapIndexTable` and it works with `_session.Query<ContentItem, PostIndex>()`. I've also found a way to reindex existing content items in https://github.com/sebastienros/yessql/issues/115
