### ISSUE TITLE
HTTP Request Workflow doesn't work

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#5542]
I need it POST a request to a controller action but the code below isn't executed. it means the TEST() action isn't triggered.

`[HttpPost]
public async Task<IActionResult> TEST()
{
 //some code here...
}`

Here's the configuration of Workflow, any idea?

![image](https://user-images.githubusercontent.com/16193516/74471719-8fcd3b00-4e55-11ea-8d27-b3a1867d2c18.png)

**Comment by dodyg** [comment]
Try

```
{
   "test" : "test value"
}
```

I think it is expecting a json payload.

**Comment by orchardc** [comment]
Thanks @dodyg , it doesn't work.

I'm now thinking that it's something to do with the controller:
**[HttpPost] public async Task<IActionResult> TEST() { //some code here... }**

As the above code has never been triggered, even by PostMan.

**Comment by sebastienros** [comment]
Antiforgery token?

**Comment by orchardc** [comment]
I don't have the Antiforgery token, it's simply : 

[HttpPost] public async Task<IActionResult> TEST() { //some code here... }

Is it required? Can you guys reproduce it at all?

**Comment by sebastienros** [comment]
AFT are required by default in ASP.NET, so if you want to request it from a workflow or from postman, then you need to disable in on your action or controller

**Comment by orchardc** [comment]
Thanks @sebastienros , it means I need AFT. So I change the controller to the following:

[HttpPost]
[ValidateAntiForgeryToken]
public async Task TEST()
{ //some code here... }


**Then, the question is how to config the Workflow to post the AFT?**

**Comment by sebastienros** [comment]
It can't, the AFTs are for browsers and use cookies. In this case you decide how you want to protect your API, like with a private token.

**Comment by orchardc** [comment]
Hi @sebastienros , are you suggesting that the Workflow function can't call the AFT -enabled controller? and the only way to do it would be disable the AFT on the action?

**Comment by sebastienros** [comment]
Yes, an API call can't handle AFTs. It's not a limitation of the workflow. A way to see this issues is how would you call your API from Postman. Then workflow can do the same as Postman. Like with a private token.

**Comment by sebastienros** [comment]
Another solution would be to use Open Id and then have a workflow task that would generate a token to be used in the HttpRequest workflow task. Even using something like Client Credentials.
