### ISSUE TITLE
Blocks do not collapse when I edit a LandingPage of AgencyTheme.

### ISSUE THREAD

**Issue by danis-arslanov** [OrchardCMS/OrchardCore#5553]
Blocks do not collapse when I edit a LandingPage of AgencyTheme.

**Comment by danis-arslanov** [comment]
![agency](https://user-images.githubusercontent.com/37458556/74589117-8c7fae00-5013-11ea-9112-0fe1cccc39bd.jpg)

**Comment by danis-arslanov** [comment]
![agency2](https://user-images.githubusercontent.com/37458556/74589156-d49ed080-5013-11ea-8090-4e097603ec26.jpg)

**Comment by danis-arslanov** [comment]
I installed dev-version and it works there, it doesn't work in Orchard Core RC 1 only.

**Comment by sebastienros** [comment]
Fixed in dev branch
