### ISSUE TITLE
Two Questions: Themes and security

### ISSUE THREAD

**Issue by bigtfromaz** [OrchardCMS/OrchardCore#5566]
I tried out beta-1 back in 2017 and built a theme.  I liked what I saw but it was too green at that time for us to commit much time.  We came close to just going with it anyway.  Release candidate is not too early for us so I am preparing to build an OrchardCore CMS site, with our content, and have a couple of questions.

**_Have there been any breaking changes related to themes since Beta 1? In other words I changed the old csproj file to .net Core 3.1,, updated NeGet packages and it builds OK.  Is there anything that changed in the structure I need to know about?_**

Also, our site was "amended" by a weakness in DNN that allowed the hackers to add content to the site file system (not the database). They then used us to redirect traffic to various nefarious sites which helped them to hide their users' IP addresses.  That lasted a while before we discovered the traffic.  

We plugged the hole in triage by deleting the content from the file system and removed all write permissions from the site's service accounts.  Of course, that broke the ability to perform several DNN functions.  So, we became a static site while we performed an upgrade that resolved the issue. So...

**_Can we run OrchardCore CMS using service accounts with read-only access to the file system?  Our latest mantra here is zero-trust so I must grant permissions, as needed, from the bottom up with a default deny at the end._**

If there's another forum I should be using, close this, let me know, and I'll post there.

Thanks for any guidance you can send my way.

**Comment by sebastienros** [comment]
A few breaking changes, but mostly in the HtmlBodyBody part that has been renamed.

You can run with readonly if:
- you setup the site in staging (it will create an App_Data folder)
- you use blob storage for media
- you don't use lucene (or you build an Elastic Search provider)

**Comment by bigtfromaz** [comment]
@sebastienros I don't know the details but you can find more on the DNN site.  In short the attacker was able to fool DNN into storing new php files into the data/ folder.  As a result, we were logging traffic from places around the world hitting https://ourHost/data/index12 3.php.  From I could see, the scripts were in turn redirecting those browser sessions to various add images for "dating" sites.

I think they were using our IP address to remain anonymous.

It's been 12 days since I plugged the hole and we are still seeing GETs for those URL's.  Of course now we're responding with HTTP 404 responses.

**Comment by sebastienros** [comment]
I see. In dotnet core you can't run pages as is anymore, they have to be precompiled. But I assume that as long as you can put custom files in the folder there will always be a way to escalate to do something wrong.

**Comment by bigtfromaz** [comment]
Good to know.
