### ISSUE TITLE
need to change IFileStore

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#5567]
should we change from
Task<string> CreateFileFromStreamAsync(string path, Stream inputStream, bool overwrite = false);
to
Task<string> CreateFileFromStreamAsync(MediaCreatingContext context, Stream inputStream, bool overwrite = false);

instantiate MediaCreatingContext context inside DefaultMediaFileStore will let the code less flexible.
@deanmarcussen Your opinion?

**Comment by deanmarcussen** [comment]
I am ok with it as it is, but you are welcome to convince me otherwise.

The intention was to not change the interfaces too much, particularly this close to a release.

If you could show me some code where what we have done will not work that would help.

**Comment by infofromca** [comment]
np, I already created one in my module
