### ISSUE TITLE
Orchard Core &transplant  Orchard.Gallery?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#5568]
Whether Orchard Core provides a platform, share more https://github.com/OrchardCMS/Orchard.Gallery

Or e.g. KOOBOO CMS http://thetheme.com/

Import and export all modules or templates of the website and their demo data, so that non-developers can easily use it。

Any ideas?

[GIF截图录屏_vmware_20200217173029.zip](https://github.com/OrchardCMS/OrchardCore/files/4212952/GIF._vmware_20200217173029.zip)

**Comment by hishamco** [comment]
I think @sebastienros was talked about Orchard Gallery few months ago in the Podcast, I'm not sure if there's any updates on this

/cc @agriffard

**Comment by sebastienros** [comment]
We won't support automatic install of code. A gallery will only be a list of available extensions and links to their locations.
