### ISSUE TITLE
Settings view not found

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5575]
When the project name of a module differs from the assembly name, the views for settings are not found.

I created a cms module with some settings. I received 
To illustrate I created a small repo.

[SettingsViewIssue.zip](https://github.com/OrchardCMS/OrchardCore/files/4215246/SettingsViewIssue.zip)

Start the MySettingsCms project
Create a site
Enable the features Module1 and Module2
Navigate to the settings of both modules
Module1 is throwing an exception: Exception: Shape type 'MySettings1_Edit' not found
Module2 is showing the view correctly.

**Edit**
Did some further investigation and decompiling the assembly shows that the resources in the dll are missing the MyCompany prefix.

**Comment by ArieGato** [comment]
I think the problem is the targets file in OrchardCore.Module.Targets.

$(MSBuildProjectName) should be replaced by $(RootNameSpace) in the OrchardCore.Module.Targets.targets file

**Comment by jtkech** [comment]
Just tried it

First i updated the module csproj files like this

    <Project Sdk="Microsoft.NET.Sdk.Razor">

      <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
        <AssemblyName>MyCompany.Module1</AssemblyName>
      </PropertyGroup>

      <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
      </ItemGroup>

    ...

    </Project>

Then in the drivers you were using and async keyword without using an await, so i used the non async versions.


        public override IDisplayResult Edit(MySettings1 settings, BuildEditorContext context)
        {
            var user = _httpContextAccessor.HttpContext?.User;
            if (user == null)
            {
                return null;
            }

            return Initialize<MySettings1ViewModel>("MySettings1_Edit",
                    model =>
                    {
                        model.ApiUri = settings.ApiUri;
                    })
                .Location("Content:2").OnGroup(SettingsGroupId);
        }

            ...
            ...

            return Edit(settings, context);

---

That said, i don't remember the details and you may are right, but AFAIK you can define an assembly name that is different from the project file name but the constraint we have is that the module id (that becomes the area name) needs to match the name of the project file (here `Module1`).

So, i tried it with the following manifest and it was working

    [assembly: Module(
        Id = "Module1",
        Name = "MyCompany.Module1 or any other name",
        Author = "Arjan Vermunt",
        Version = "0.1.0",
        Description = "My Company Module 1.",
        Category = "My Company Modules"
    )]

**Comment by ArieGato** [comment]
Okay, got it, the Id in the Manifest must match the project name by convention.

this fixed the issue:
```
    Id = "Module1",
```

**Comment by jtkech** [comment]
Okay cool ;)
