### ISSUE TITLE
RenderBodyAsync() does not work when layout is called from a Razor Page

### ISSUE THREAD

**Issue by mawendel** [OrchardCMS/OrchardCore#5576]
I have a Razor Page in /Pages/MyPage.cshtml that sets 
```
@{
    Layout = "_MyLayout";
}
```
The _ViewImports.cshtml includes the Razor Page
```
@inherits OrchardCore.DisplayManagement.RazorPages.Page

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
@addTagHelper *, OrchardCore.Contents.TagHelpers
```

In /Views/Shared/_MyLayout.cshtml i have the rendering of the body
```
...
    <main>
        <div class="container-fluid mt-5">
            @await RenderSectionAsync("Messages", required: false)
            @await RenderBodyAsync()
        </div>
    </main>
...
```

And i have of course set the /Views/_ViewImports.cshtml to
```
@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
@addTagHelper *, OrchardCore.Menu
```

This however does not help as it gives the following error
```
An unhandled exception occurred while processing the request.
InvalidOperationException: RenderBody has not been called for the page at '/Areas/DarkModeTheme/Views/Shared/_MyLayout.cshtml'. To ignore call IgnoreBody().
Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
```
It seems like it is still using the Razor Page inherits?

If i change `@await RenderBodyAsync()` to `@RenderBody()` it works. But then i will not be rendering the majority of the site content async? I'm unsure how exactly Orchard benefits from RenderBodyAsync().

Does anyone know how to fix this?
..or if it is fine to just use @RenderBody()?

**Comment by jtkech** [comment]
As i remember, when using the theme engine we use a precompiled layout view that will render the theme layout shape, so, if you still want to use it to be able to use correctly e.g `RenderSectionAsync()` and `RenderBodyAsync()`, you would need to override the theme layout shape, not the layout view.

So, try to use `ViewLayout = ...` instead

**Comment by mawendel** [comment]
@jtkech setting ViewLayout does nothing.

I can even set it to some layout that isnt there and it will still just render the default layout.
```
@{
    ViewLayout  = "asdf";
}
```
So i am guessing it does not work or it needs to be used in some other way?

**Comment by jtkech** [comment]
So, because here it has to be found as a Shape, not an mvc view, your layout need to be just under `YourModule/Views` folder.

Just tried with the `Hello` page of the `OC.Demo` module


    @{ 
        ViewLayout = "MyLayout";
    }

And created a `OC.Demo/Views/MyLayout.cshtml` file

    @await RenderSectionAsync("Header", required: false)
    <div class="container-fluid mt-5">
        Testing @await RenderBodyAsync()
    </div>

And it works ;)

**Comment by mawendel** [comment]
Ok i moved the layout to the folder and at first it still didnt work. The issue was that i had a 'dash' in my name (Layout-SomeName), and i dont think the shape naming liked that. After renaming it to _LayoutSomeName it now actually gets the layout, thanks!

However, now it wont render my menus. 
`<menu alias="alias:SideMenu" />`

Ive also tried
```
_ViewImports: @addTagHelper *, OrchardCore.Contents

<contentitem alias="alias:SideMenu" display-type="Detail" />
```

but neither of them works. It will just output the menu tag itself. Any idea whats wrong?

**Comment by jtkech** [comment]
Yes, about the template name conventions, with `Layout-SomeName` you need to use `ViewLayout = "Layout__SomeName"`.

Then just tried the following in `MyLayout` that works

    @await RenderSectionAsync("Header", required: false)

    <div class="collapse navbar-collapse" id="navbar">
        <menu alias="alias:main-menu" cache-id="main-menu" cache-fixed-duration="00:05:00" cache-tag="alias:main-menu" />
    </div>
    <div class="container-fluid mt-5">
        Testing @await RenderBodyAsync()
    </div>

If in `Development` mode e.g in debug mode through VStudio you just need to register tag helpers through the `_ViewImports`, if not in `Development` mode that may be the case e.g through the command line, you also need to reference in your module project file the project / package that defines the tag helper.

Here `OC.Menu` and depending on your version `OC.Contents` or `OrchardCore.Contents.TagHelpers` where the contentitem tag helper is now defined.

**Comment by mawendel** [comment]
Ah.. i had added `@addTagHelper *, OrchardCore.Menu` in my theme. But not in my module that now has the layout/razor page.

Thanks for all your help!
