### ISSUE TITLE
Container creation fails in Azure Media Storage if name contains uppercase chars

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#5578]
When creating folders or uploading images with Azure Media Storage an error is thrown: "the specified resource name contains invalid characters". 

My settings are as follows:
```
"OrchardCore.Media.Azure": 
{ "ContainerName": "{{ ShellSettings.Name }}", 
"BasePath": "media", 
"CreateContainer": true },
```

I have found out the issue is with the storage container creation. When creating a tenant I will name the tenant like MyCompany but containers names have to be lower case in Azure.

Azure Data Protection also fails with the same issue if your template for container has uppercase.

**Comment by Skrypt** [comment]
`{{ ShellSettings.Name  | downcase }}`

**Comment by scleaver** [comment]
@Skrypt but should we put this into the code to do this automatically?
