### ISSUE TITLE
Reboot tenant button in AdminUI

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#558]
After a investigate dependencies of OpenIdSettings on Microsoft.AspNetCore.Builder.JwtBearerOptions and AspNet.Security.OAuth.Validation.OAuthValidationOptions @sebastienros saw there is no other alternative to restart the tenant if we want changes on those settings take effect.

How a user not always can restart the server we need to provide a button for restarting it. That button will be only available to users with an specific permission.

**Comment by jersiovic** [comment]
I would add a method to ShellDescriptorManager that allows to restart a tenant without the need of enable or disable a module. Like this https://github.com/OrchardCMS/Orchard2/pull/553/commits/849d3bafa6501b2144d4cade54f15cdd28ce9a8f

The question is where do you think should be added the code (view, controller, ...) for that button? In the Orchard.Environment.Shell project or in an extra module?

**Comment by sebastienros** [comment]
I don't think there is any method to add anywhere. Use `IOrchardHost.ReloadShellContext()` and pass the `ShellSettings` that is resolved from DI.
Next request will reload the tenant.

**Comment by sebastienros** [comment]
As I commented, we know have a way to restart the site when a setting changes. We just need to warn the user on the screens that will do it.
