### ISSUE TITLE
Feature Request: Add to Head

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5582]
people need to insert google script into the head section of pages for analytics and advertising.
We should not have to make a theme just to do this.
There should be given a way to add to head.
There is a lot of work done on this subject with drupal.
I can elaborate on this subject more later on but no theme should be required.
For example in an advanced version you can choose which text to add to which content types or taxonomy types.

**Comment by deanmarcussen** [comment]
Do we not have support for Google Analytics with a feature already?

There is also an issue to improve it https://github.com/OrchardCMS/OrchardCore/issues/5385

**Comment by JoshTango** [comment]
ok well let me go a bit more in-depth.
For Google analytics the script you paste into the head of your page is the typically the same for EVERY single page in your site.  Therefore its an easier feature to implement.

BUT, Google AdSense is not the same for each page.  For example you dont want ads on your home page maybe, therefore there would be no AdSense script on the homepage.

You most likely do want ads on the content pages but you might want a different script for each content type in the head of the page.  Same for taxonomy.

Drupal has a way to decide which scripts go on which type, etc,

**Comment by deanmarcussen** [comment]
ok, so what I hear you saying is that you want to apply different scripts to different ad-slots, is that correct?

One presumes you have templates for your content types or taxonomies.

Could you not use the resource manager script tags in your templates to include the ad-slot scripts as you wish 
i.e.
`<script At="Head">`

https://orchardcore.readthedocs.io/en/dev/docs/reference/modules/Resources/

**Comment by JoshTango** [comment]
I will find the drupal explanation and paste the link.
One should not have to create a whole template for this.
It should just be inserted into the head I  think.

**Comment by Skrypt** [comment]
I do this for my website and it's pretty much scripts embedded in my different content types templates.

**Comment by JoshTango** [comment]
seems like overkill

**Comment by JoshTango** [comment]
Here is the link to a drupal module I have used before:
https://www.drupal.org/project/add_to_head

I allows you to narrow or filter to certain paths.

**Comment by JoshTango** [comment]
Its suppose to be for path aliases because this is a SEO thing.
Usually the person responsible for SEO would decide which scripts get inserted into the HEAD sections of what pages.

**Comment by deanmarcussen** [comment]
I had some time to look at the link you provided.

I think everything that the plugin you described can be done with the layers module, and a liquid widget, in terms of providing scripts at head, based on url rulesets.

All you need to do is render a head script in the footer zone, specifying `At="Head"` and it will be rendered by the layout, providing your layout renders headscripts.

For a per content item basis, again attaching a liquid part to a content item would allow you to provide scripts via liquid, rather than digging into the templates.

Although for rulesets based on content type you may be better of creating more specific templates, or settings on a content type as you require.

**Comment by JoshTango** [comment]
I also noticed you have SEO coming up after version 1 is released.
Typically a SEO manager of a website would just deal with paths only and not be aware of the underlying implementation of a website like layers, widgets or blocks etc.
If there were a SEO role then the SEO feature would be available to people with that role and it should be presentable in a way that makes sense to SEO people.

**Comment by ns8482e** [comment]
- I have `{% resources type: "HeadScript" %}` in `<head>` tag of my layout.

- I defined all `sections` needed by my site using `{% render_section "mysection", required: false %}` in layout.

- I defined all `zones` that can be configured using `layers` from admin menu "Design -> Settings -> Zones".  `e.g. Footer, Content, mysection`

- I created new layer from Widgets admin menu - "Design -> Widgets" e.g. `Advertise` with `Rule` url("~/my-content/*")
- On widget page, under my  zone `mysection` added  liquid widget.
- In liquid widget, added code 

```
{% scriptblock at: "Head" %}
    //my custom script
{% endscriptblock %}
```

My custom script is render only for pages that starts with url  `~/my-content/` and script was placed inside `<head>`. It didn't required to create any content template.

**Comment by JoshTango** [comment]
that's good, but I think the SEO feature should be designed for non technical people like SEO managers

**Comment by ns8482e** [comment]
@JoshTango IMHO Layers and Widgets are for non technical people and doesn’t require any developer skills to use them

**Comment by sebastienros** [comment]
User Layers, or create a custom content item that contains HTML and that users can edit directly. Then in your Layout load this content item and inject its content in the head zone.

**Comment by JoshTango** [comment]
Ok I followed @ns8482e advice and used his snippet in my widget and it added:
<script type="text/javascript">  
in front of my script for some reason.
Also it added widget container html code that I dont want in my head.
