### ISSUE TITLE
Templates: Bug or docup?

### ISSUE THREAD

**Issue by bigtfromaz** [OrchardCMS/OrchardCore#5589]
`dotnet new -i OrchardCore.ProjectTemplates::1.0.0-rc1-* --nuget-source https://www.myget.org/F/orchardcore-preview/api/v3/index.json  
`

`dotnet new occms -logger nlog`

Yields:
```
Invalid input switch:
  -logger
  nlog 
```

However `dotnet new occms -lo nlog`  works correctly.

**Comment by agriffard** [comment]
`--logger`

https://docs.orchardcore.net/en/dev/docs/getting-started/templates/#from-command-shell-automated-way
