### ISSUE TITLE
Unable to parse email with diacritics

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5591]
While I'm working with #5474, I see a weird issue, seems MailKit unable to parse an email with display name that contains diacritics

The email that I used is **Sébastien Ros <<sebastienros@gmail.com>>**

I will investigate on this and push a fix soon

**Comment by sebastienros** [comment]
Could be related to this? https://github.com/jstedfast/MimeKit/issues/536

Please try to update the reference to verify.

**Comment by sebastienros** [comment]
I could repro the issue with version < 2.5.0, so updating to the latest version should fix it.

**Comment by hishamco** [comment]
I will try to update the reference and try this one

**Comment by hishamco** [comment]
Seems it's updated in my PR

**Comment by sebastienros** [comment]
You can merge the PR if the issue is fixed

**Comment by hishamco** [comment]
Sure

**Comment by hishamco** [comment]
Fixed by #5474
