### ISSUE TITLE
What happens to the website in MS SQL database when APP_Data is deleted?

### ISSUE THREAD

**Issue by OksXen** [OrchardCMS/OrchardCore#5592]
Hello, 

If we have OrchardCore's website data saved in, e.g. MS SQL and APP_Data's content were deleted, could we restore the website with MS SQL's data?

Thanks, 
-Ferdinand.

**Comment by sebastienros** [comment]
Not everything. 
The App_data contains an encryption keys, so you will have to re-enter SMTP secrets for instance. Use passwords are OK as they are not encrypted, but not sure if it would still work, worst case you would need to enable the Reset email feature for users to re-create a password.

The main thing I can think about is the Content Type definitions that is in App_data, unless you enable the feature to store them in the database.

The easiest way to proceed at that point is to create a new site, then edit the Settings.txt file to update the connection string to the existing database (don't use it during setup, use a new db).

**Comment by sebastienros** [comment]
If you are in deep, skype me I will help you.

**Comment by OksXen** [comment]
Thanks Sébastien. I haven't built the site yet - I'm still in R&D - _trying to get SAP (AngularOrReactJs to work)._ 

Even though we could configure the "App_Data" folder to be outside of the root web application, there is still a risk that it could get deleted because it it just happens - accidents. 

I guess, to prevent the scenario from potentially loosing the website or fixing it, it's recommended to have a regular backup of the APP_Data folder. 

Would creating a new site and configuring the settings to connect to existing DB, after the initial setup, accept existing admin password?

Regards, 
-Ferdinand.

**Comment by sebastienros** [comment]
Haven't tried it, but I believe it would work.

You should do a backup of this folder too, right, and enable the Database Content Type Definition feature.

**Comment by OksXen** [comment]
Thanks - I'll remember - "enable the Database Content Type Definition"

**Comment by vitalybrandes** [comment]
@sebastienros can you please point me where do I need to enable that definition?

**Comment by fenngineering** [comment]
I can't seem to find it either, @OksXen please can you point me in the right direction?

**Comment by deanmarcussen** [comment]
The feature you want to disable is called `File Content Definition`

This will enable the database content definition which is the default.

Recommended way to migrate is to 
- Make a deployment plan of your existing content definition (content definition step).
- Disable the `File Content Definition` feature
- Import your deployment plan

**Comment by fenngineering** [comment]
As i understand it, my File Content Definition feature is disabled does this mean everything is stored in the database?

**Comment by deanmarcussen** [comment]
should be. you can check with a sql query (something like, depending on your type of sql
```
SELECT [Id]
      ,[Type]
      ,[Content]
      ,[Version]
  FROM [Document]
  WHERE [Type] = 'OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions'
```
