### ISSUE TITLE
Missing features, roadmap questions

### ISSUE THREAD

**Issue by mehdiibrahim** [OrchardCMS/OrchardCore#5597]
We are considering Orchard Core CMS for our needs. There are three features that appear to have been supported in legacy Orchard - the ability to version content, schedule publishing and audit trails, but none of these appear to be available in Orchard Core CMS OOB.

How can functionality for the three features be accomplished in Orchard Core? Would they have to be done through the use of workflows or custom modules? Any insight into whether these features are on the roadmap?

Also, when will Orchard Core move from RC to official release 1.0?

**Comment by sebastienros** [comment]
Content versioning is already implemented. There is no UI to list previous versions right now. There is an issue filed to track it.
Scheduled publishing can already be implemented using workflows, but there is an issue to track a more integrated solution, like in O1.
Audit trails is on the roadmap but not yet started.

1.0 will be shipped when all issues currently tagged with 1.0 and P0,P1,P2 flags have been implemented.

**Comment by AmadeuAntunes** [comment]
Do will be available any ui to navigate between document versions?  
Audit trails will notify admins when someone changed a document ?

**Comment by Skrypt** [comment]
1- Nothing planned.
2 - This can be done already by using Workflows.
