### ISSUE TITLE
Sharing assets across sites

### ISSUE THREAD

**Issue by mehdiibrahim** [OrchardCMS/OrchardCore#5598]
I want to use a SaaS recipe, with multiple tenants underneath it - each with it's own site. Is there a way to share the media library and assets across these sites? I would think logically, if I upload something to the media library of the parent SaaS site, it would be available automatically to the children sites. Is this not possible in OC, or am I just not understanding how to do this?

What is the best way to approach this?

Thanks!

**Comment by mawendel** [comment]
The default media library uses local files saved under App_Data/ for that specific tenant. If you want to share them across sites, you would first of all need to use Azure Blob storage and then i think you can set it up to use the same blob. Mind you i havnt tried this, but in theory i think it should work.

**Comment by JoshTango** [comment]
maybe http handlers can be created each with their own separate url but the handlers all point to the same blob or asset

**Comment by sebastienros** [comment]
Using a shared folder or blob storage is the solution IMO.
