### ISSUE TITLE
Officially supported darkmode theme

### ISSUE THREAD

**Issue by mawendel** [OrchardCMS/OrchardCore#5605]
**I would like to see an officially supported darkmode admin theme. I'm hoping we can get more than a few to chime in and make this happen.**

After briefly looking at how to implement my own darkmode admin theme, my first thoughts are that it looks pretty tough coming from the outside, with no prio knowledge of how the admin theme is built up.

I tried using the compiled bootstrap.css from https://bootswatch.com/darkly/ with no luck, there are too many custom tags overriding what should otherwise take precedence. It seems like it would take me a lot of time to figure out what things are overriden, where it comes from and how to target the individual tags.

The maintaining of my own separate version could also become quite the chore, considering that any changes made to the official TheAdmin theme could be quite opaque. Then having to dig through thousands of lines of css tags to figure out how to make your admin theme work again..

_It does not have to be the Darkly skin we use, it was merely a way to test it. In fact im not sure im sold on the white background for all inputs._

**Comment by Skrypt** [comment]
I'm surprised to hear that. Would you send us some screenshots of this attempt? The only part that is strongly designed is the left menu navbar to be honest. Maybe some other zones too like the header navbar. But generally we stick to BS4 classes for most of the work.

**Comment by deanmarcussen** [comment]
It may just need to be compiled from sass with the rtl support from the gulpfile, that's generally what is changing the bootstrap tags

**Comment by Skrypt** [comment]
I'm trying exactly that right now

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/74965613-8f97e700-53e3-11ea-99fe-ce51478b0d43.png)

Just like what I thought

**Comment by mawendel** [comment]
I didnt even get that. But i also only referenced the bootstrap.css in my Layout. If you used some custom sass compilation or something else that might explain why yours looks partly there?

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/74970520-7e9fa380-53ec-11ea-989d-a5a27879fb6f.png)

Yes I used the sass files and created an alternate TheAdminDark.scss file with it.

**Comment by sebastienros** [comment]
@Skrypt people are asking for it, maybe make it official in the admin theme, with a setting that is stored in a cookie. It should just be a scss file that we can update for this option.

**Comment by hishamco** [comment]
We could support light and dark themes out of the box, making an option to add new themes and switches between them from within the admin site

**Comment by mawendel** [comment]
I have been using darkreader for a good while. Now despite that even the best attempt for darkreader will never reach the same level a real theme can do, i agree it can be serviceable for most pages. Content items with a lot of flow parts are difficult to see though. But maybe that is another discussion for increasing readability for the flow views.

The issue is, that while i want the admin theme that is glaringly white to be in darkmode, the site theme is custom made in darker colors. So when i swap between admin and front-site whenever i'm setting something up/designing html, i have to keep enabling and disabling it.

But as you say, it is quite difficult to make a darkmode theme, so perhaps its not worth the time at the moment vs. other features/fixes.
