### ISSUE TITLE
Upgrading to .NET Core 3.1 SDK (v3.1.102) breaks Orchard Core Azure DevOps builds with NuGets

### ISSUE THREAD

**Issue by OrchardSkills** [OrchardCMS/OrchardCore#5614]
Upgrading to .NET Core 3.1 SDK (v3.1.102) breaks Orchard Core Azure DevOps builds with NuGets

:43.3542670Z ##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
2020-02-22T15:28:43.3566392Z ##[error]Packages failed to restore
2020-02-22T15:28

Attached Log File:
[restore.txt](https://github.com/OrchardCMS/OrchardCore/files/4239629/restore.txt)

**Comment by Skrypt** [comment]
Publishing as self contained fails too

```cmd
dotnet publish src\OrchardCore.Cms.Web\OrchardCore.Cms.Web.csproj -o build\release -c release --self-contained true --framework netcoreapp3.0 --runtime linux-x64
```
