### ISSUE TITLE
Share content across sites in multi-tenant environment?

### ISSUE THREAD

**Issue by mehdiibrahim** [OrchardCMS/OrchardCore#5616]
@sebastienros  I know this question has been asked a number of times in the past, but wanted to see if anything has changed now that we're in 2020 :)  I have a multi-tenant SaaS setup. On the home page of each site, there are 4 HTML paragraphs/cards that always need to be in sync. We may have 10,000+ sites, so a deployment plan to push content updates to each site is just not practical. What is the best way to share content for these 4 paragraphs across all sites? thanks!

**Comment by infofromca** [comment]
+1, need a point to turn on and off.
and the first step is to share the User Identity across tenants

**Comment by hishamco** [comment]
@mehdiibrahim I think there's an open issue address the same thing

**Comment by zl2fxy** [comment]
we have some web apis for managing these activites.
we can implement a controller method that it will call deployment plan。
every tenant will use this method to sync content,
and a principal tenant watch activites completion.

**Comment by sebastienros** [comment]
You don't need to keep the content in sync, what you should do is manage the content on the Default tenant, or any specific tenant that would contain the common content. Then you can resolve services from other tenants in your own module or razor view, to query the content from the Default tenant. You can also cache it if necessary.

Some hints:

First get the shellsetting from a tenant name: IShellHost.TryGetSettings() then create a scope, and don't forget to dispose it, and there is an UsingAsync() extension to well use it shellScope.UsingAsync(scope => ...))
