### ISSUE TITLE
Suggestion: Move OrchardCore.Demo to separate repository

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5620]
`OrchardCore.Demo` contains very useful samples that developer can take source code reference.  
It would be nice `OrchardCore.Demo` to have it's own repository so It doesn't require to clone complete Orchard Core source code.

I think it would be bit scary "thought" for "some" who uses nuget packages  for orchard core - and forced to clone source code just for `OrchardCore.Demo`  

We can add documentation for `OrchardCore.Demo` that directly links to it's own repository.

**Comment by hishamco** [comment]
@sebastienros can we move this into OrchardCore.Samples instead of Modules, coz I want to suggest the same thing before

**Comment by sebastienros** [comment]
It's more of a way to test features locally without having to create a new project every time. I'd like to keep it for now. Maybe not at this place in the solution. Or move everything in a Functional tests project.

**Comment by hishamco** [comment]
Move it to a functional tests is a good option

**Comment by Piedone** [comment]
Nothing needs to be done for now.
