### ISSUE TITLE
Make libraries target .NET Standard

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#5621]
The usual practice for libraries is to target .NET Standard and not .NET Core so they can more widely be consumed. However, all projects in the solution use the same target which is currently .NET Core 3.1. This means that one can only add Orchard NuGet packages from an app if all consuming projects are also on .NET Core 3.1 and a package can only depend on parts of Orchard if it also targets .NET Core only.

Thus I suggest the "libraries" of Orchard, i.e. everything under the OrchardCore solution folder, to target .NET Standard 2.0 (this is not an issue for modules since you'd use them in some kind of ASP.NET Core app anyway); I'd assume 2.1 is not really needed. This would open up compatibility with pre-3.1 .NET Core projects, .NET Framework projects, and allow library authors who want to target .NET Standard depend on Orchard.  Case in point the latter is what we want to do with [Hastlayer](https://github.com/Lombiq/Hastlayer-SDK/issues/34) but this rules Orchard out.

**Comment by kevinchalet** [comment]
Sadly, targeting .NET Standard (2.0 or 2.1) is impossible without decoupling the core packages from ASP.NET Core, which was discussed here: https://github.com/OrchardCMS/OrchardCore/issues/2971.

**Comment by JoshTango** [comment]
when .net5 is out they can target that
problem solved

**Comment by kevinchalet** [comment]
@JoshTango not sure how it's conceptually different from targeting `netcoreapp3.1` (well, if you target `netcoreapp5.0`, your library can only be used on .NET 5.0, which is even worse).

@Piedone's ask is precisely to support .NET Framework and pre-.NET Core 3.1 projects, which is certainly not something targeting `netcoreapp5.0` would solve 😄

**Comment by Piedone** [comment]
Decoupling from ASP.NET is a good point, I totally didn't think about that.

Yeah, .NET 5 won't really help. There is an immense amount of .NET apps out there that are not on .NET Core 3.1 (and most of which presumably won't be quickly migrated to .NET 5 either, should that actually ship by the end of this year).

**Comment by JoshTango** [comment]
nvm then, I have moved beyond the old framework and want to forget about it, sorry
