### ISSUE TITLE
Updating a ContentItem with bag items, causes all bag ContentItemId's to be changed

### ISSUE THREAD

**Issue by mawendel** [OrchardCMS/OrchardCore#5633]
For some reason all bag items have their ContentItemId's updated if you save through the admin UI. 

If i save through updateContentItem() from a workflow script task they are not changed which is exactly what i need and would expect.

**Comment by sebastienros** [comment]
> For some reason

The reason is that when you update the content item in the editor, the server will re-create the content item completely. When you update the json by yourself, you are only changing the parts you care about.

Why is it an issue? Eventually we could remove all the content item ids from the payload, it should not break anything. So the next question is why are you using these ids?

**Comment by mawendel** [comment]
Because i'm referencing the ContentItemId in the bag from another separate content item. 

ContentItem
- Bag1
-- Bag1ContentItemId: asdf234wrefg5
-- Bag2ContentItemId: dsfghdrth3443
-- Bag3ContentItemId: sdfghhw45624

Then from another content item i reference the ContentItemId + the Bag2ContentItemId to get the subselection.

**Comment by sebastienros** [comment]
Did you create your own "picker"

You should use an alias part instead. This is how we will solve routing for items in bag parts too.

@deanmarcussen but I have a doubt now, do we need ids to be constant when there is no alias?

**Comment by mawendel** [comment]
Ok, a little context.

- For the top content item, there can be several thousands. 
- The content items in the bag part, is completely controlled by the user (from a specific content type of course). So they can setup how many they want and config these with typical 2-10.
- Other users can then view these options and select one of them (through front-end Views).

Normally you would have a FK to this table. But here i would just iterate through all the bag items to find the correct one based on its ContentItemId.

However, i guess i could use a generated alias (custom id) if it was possible to reference nested bag items? Maybe i misunderstand the implementation, but i dont see a way to use the alias though. It saves just a ContentItemId in the AliasPartIndex, but is that the parent content item or the bag part content item? 

This also only assumes one level of bag items. If you have nested two bag items then it would need to save three ContentItemId's. ParentId, FirstBagId, FinalBagSelectionId. Unless of course an alias could be searched iteratively:

```
var parentItem = getItemByAlias("UserPage1234");
var firstBagItem = getBagItemByAlias(parentItem, "SubSelection1");
var secondBagItem = getBagItemByAlias(firstBagItem, "SubSelection2");
```

This wont allow for direct lookups though. In any case, if you believe that the ContentItemIds will either be removed or that the admin will keep doing a full replace, i will just have to make my own custom id's for them. 

But please let me know what you think, as it would be pretty fundamental to how i do lookups in my system.

**Comment by deanmarcussen** [comment]
@sebastienros yes, this is going to cause some issues in contained routing. if we use a default `HandlerAspect` for an `4g0c8e9zd9529t67eg18rr3b4e-displayText` route, as it would change.

However as I am moving all the workings into the `AutoroutePart`, I was also considering making the `AutoroutePart` required on the contained items, if people wanted routing. It actually makes the configuration somewhat easier for the user (less options to tick, it just works, if the child items have an `AutoroutePart`, and doesn't if they don't). I will see what fits better.

@mawendel 
> Normally you would have a FK to this table. But here i would just iterate through all the bag items to find the correct one based on its ContentItemId.

This does suggest that the `ListPart` might have been more appropriate for your design. However...

> However, i guess i could use a generated alias (custom id) if it was possible to reference nested bag items? Maybe i misunderstand the implementation, but i dont see a way to use the alias though. It saves just a ContentItemId in the AliasPartIndex, but is that the parent content item or the bag part content item?

What might work for you is using the Alias, but being aware that like `AutoroutePart` it doesn't support the concept of contained items, from a lookup point of view.
Will see how contained routing goes first, before looking at options with Alias.

So using the Alias in your scenario (and I would have to test this)
- You would have to know the container content item id, and then search it for the alias inside it.
- The alias index will not be especially useful, as it will only know about, and index container content items.
- it would have to be generated (and guaranteed unique by the generation)
- Perhaps you would build a liquid filter which uses the `IdGenerator` service to generate the Alias pattern.
- Or you might also use a generated title to do the same, knowing it will not check for uniqueness (but also knowing that the `AliasPart` uniqueness checks are not very useful in this scenario.

We should (if we don't already) have a text field that supports liquid pattern generation. That would be helpful in this scenario

**Comment by mawendel** [comment]
> > Normally you would have a FK to this table. But here i would just iterate through all the bag items to find the correct one based on its ContentItemId.
> 
> This does suggest that the `ListPart` might have been more appropriate for your design. However...

Sure, but, first of all i want to utilize the whole documentdb paradigm and advantages (bundling data/few lookups). So in the bag i'm including a few things other than just the ContentItemId that are essentially status types and other important information.

But even if i wanted/could just use a list, it is only possible to include one ListPart in a ContentType. I have already designated the available slot for an Articles list. So perhaps being able to add a Named List would be a good idea (if possible) in the future. 
 
> > However, i guess i could use a generated alias (custom id) if it was possible to reference nested bag items? Maybe i misunderstand the implementation, but i dont see a way to use the alias though. It saves just a ContentItemId in the AliasPartIndex, but is that the parent content item or the bag part content item?
> 
> What might work for you is using the Alias, but being aware that like `AutoroutePart` it doesn't support the concept of contained items, from a lookup point of view.
> Will see how contained routing goes first, before looking at options with Alias.

Right, so this is probably why i'm also using this approach right now. I dont need a contained id, since i will be iterating from the top down (and thus know the parents). When a user selection is made, it saves both the primary content id and the selection id. So its ContentItemId -> NamedSelectionBag -> SubContentItemId

Also i've made custom mappings with Razor Pages mapping. So i'm doing `/userpage/{userpageid}/selection/{selectionid}`
For the page that gives the user the possibility to apply for the selection. I'm not using AutoroutePart anymore after moving to Razor Pages for the majority of the pages (what you are talking about would still be really useful for another project i'm on).
 
> So using the Alias in your scenario (and I would have to test this)
> 
> * You would have to know the container content item id, and then search it for the alias inside it.

And then my questions would be. What difference would it make to use the ContentItemId vs. an Alias? Whenever i see an item Id, i expect it to be the same until i delete it. Otherwise its not really an Identification of something in the normal sense if it changes on each save. That is at least my view on Ids.

> * The alias index will not be especially useful, as it will only know about, and index container content items.
> * it would have to be generated (and guaranteed unique by the generation)
> * Perhaps you would build a liquid filter which uses the `IdGenerator` service to generate the Alias pattern.
> * Or you might also use a generated title to do the same, knowing it will not check for uniqueness (but also knowing that the `AliasPart` uniqueness checks are not very useful in this scenario.

> 
> We should (if we don't already) have a text field that supports liquid pattern generation. That would be helpful in this scenario

I'm not sure if im understanding you correctly. But if what i'm hearing you say, is that you want to generate some pattern based on the actual place of the content item then thats crazy enough to might work. Like the id for a triple nested bag item:

`ContentItemId_NamedBag.ContentItemId_SubNamedBag.ContentItemId_SubSubNamedBag.ContentItemId
`

And then having the parser be able to traverse the data itself to get that bag item, that would be damn genius!

...

Anway, I'm not sure the alias approach would work really well as it is now.. and I'd rather not use the auto updating ContentItemId if it stays (or gets removed completely). I can easily make my own content item Id, its not really that big of a difference. But before i go that way, how close are you guys to deciding if the bag content item id's will stay/go/keep getting updated etc.?
