### ISSUE TITLE
Readme.md rendering difference between github and orchard core

### ISSUE THREAD

**Issue by AndrewFraser95** [OrchardCMS/OrchardCore#5637]
Hi, super minor issue but thought I would point it out as it could be a fairly quick win.

Nested bullet-points are not currently rendering correctly on orchardcore.net from the readme.md files found on Github.

Example location (Starts at "A placement rule contains two sets of data:"): 
[Working on GitHub](https://github.com/OrchardCMS/OrchardCore/blob/b6b6fde37ba4dc0d003c1dd39a0afad40c57ee00/src/docs/reference/core/Placement/README.md)
[Not Working on OrchardCore](https://docs.orchardcore.net/en/dev/docs/reference/core/Placement/)

Thanks!

**Comment by hishamco** [comment]
@agriffard seems MkDocs doesn't render nested bullet-list correctly, any idea?

**Comment by agriffard** [comment]
Fixed by #5659
