### ISSUE TITLE
Add a description to the tenant list

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#5638]
Add a description to the tenant list

![截图录屏_选择区域_20200226201124](https://user-images.githubusercontent.com/28694676/75343885-5d4f2380-58d4-11ea-94ab-ccaac8f4736a.jpg)

**Comment by hishamco** [comment]
Perhaps we need an optional description

**Comment by hishamco** [comment]
Im suggesting to add a health status for each tenant instead or with the description

**Comment by mawendel** [comment]
I would really love a description as well. It would help describe the people responsible for the site, who to contact and other such information.

**Comment by sebastienros** [comment]
Should be fine to add a description.

Health checks is another good idea, but I assume we should have a feature for that.

**Comment by hishamco** [comment]
I will add a description for now and leave the Health checks for `1.0.x`

**Comment by agriffard** [comment]
Todos: 
- Add a Description to a tenant. ShellSetting?
- You can set it when you Create/Edit a tenant. May be Setup?
- Displayed in the tenant admin page below the title. Can be searched in the filter?
- Add the Expression Property in the CreateTenant Workflow activity.

**Comment by hishamco** [comment]
I started on the first three points yesterday, but I don't think it will be searchable and I didn't think about the WorkFlow

Hope to cover all in my PR

Thanks Antoine

**Comment by agriffard** [comment]
@hishamco Do you already have something to push?

**Comment by hishamco** [comment]
Yep, I think I will start with a draft PR, coz I faced issue with retrieved the descriptions, it returns `null` all the time, no worry I will try it again after I push my changes on the #5684
