### ISSUE TITLE
Flow part needs "expands all" functionality

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5640]
It's hard to use at the moment because you always have to expand each widget item individual. It's quite annoying and it breaks editing flow .

![expand](https://user-images.githubusercontent.com/1761249/75419901-8658ce00-593f-11ea-9d34-ccc36ef195a4.png)

**Comment by deanmarcussen** [comment]
Agree, think I suggested this somewhere else

Expand all and collapse all would make the experience much better

**Comment by mawendel** [comment]
Yes, i have also sorely needed this.

**Comment by ns8482e** [comment]
Very easy to implement - simply toggleClass for widget-editor in jquery
`$('.widget.widget-editor.card').toggleClass('collapsed')`

**Comment by hishamco** [comment]
@ns8482e could please push a PR if you don't mind

**Comment by agriffard** [comment]
Example of Toggle All Widgets button in FlowPart:
![media](https://user-images.githubusercontent.com/703248/75983897-ac571300-5ee9-11ea-97e4-5f0eeb4f8e75.gif)

Understand that it is a Toggle, not a Expand all or Collapse all button.
If one widget is expanded whille other are collapsed, the toggle will invert the collapse state of each widget.

Questions:
Where do we put the button: On top, on the right, one on each line?
Is it always displayed or only when 1 or 2 widgets are added.
Does it toggle only the associated FlowPart or all the widgets in the page (ex: the ones in a WidgetsList)?

**Comment by mawendel** [comment]
Looks good!


> Questions:
> Where do we put the button: On top, on the right, one on each line?
> Is it always displayed or only when 1 or 2 widgets are added.
> Does it toggle only the associated FlowPart or all the widgets in the page (ex: the ones in a WidgetsList)?

I would prefer having both the option to expand all widgets, as well as a single top-level widget and all its children. 

For instance, i have one page with 8 top-level widgets that each have three levels. Expanding them all would be too much, if i just wanted to see number five and its children.

So per your example, i would like to see one such button to the right of each widget, as well as one above the top widget to expand everything (for easy overview of smaller widget pages).

**Comment by ns8482e** [comment]
@agriffard looks good. It would  be nice expand all button placed on hover-line next to add new widget dropdown.

**Comment by agriffard** [comment]
Example of a Form with 2 child elements with buttons on 'Add widget line' on the right, each line on the right, on 'Insert Widget' line in the middle:

![media](https://user-images.githubusercontent.com/703248/75993797-550d6e80-5efa-11ea-99be-13b5ee4941b6.gif)

**Comment by mawendel** [comment]
I have two comments on the user experience:
1. I'm not sure i like the hover line for expand all or that it is particularly intuitive for a user. Hover line is to insert/edit a single line/widget and mixing in a toggle for all lines might be confusing? 
2. The widget expand button is a bit too close to the delete button for my comfort. It might just be visually and work fine in practice though.

**Comment by agriffard** [comment]
> I'm not sure i like the hover line for expand all or that it is particularly intuitive for a user. 

It was to show @ns8482e  how it could look like on the hover lines.
We can remove them if not necesary.

> The widget expand button is a bit too close to the delete button for my comfort

It is because it is in a btn-group. We can separate them like this and put the toggle button at the end:
![image](https://user-images.githubusercontent.com/703248/75996743-9d2e9000-5efe-11ea-82f9-e4b726df436b.png)

**Comment by mawendel** [comment]
> > I'm not sure i like the hover line for expand all or that it is particularly intuitive for a user.
> 
> It was to show @ns8482e how it could look like on the hover lines.
> We can remove them if not necesary.
> 

Sure, it might also not look great if we put the expand all button above the Flow. We do need the "expand all" somewhere, its just a question of where it is the least disruptive while still being readily available. Not an easy task i know :-)

> > The widget expand button is a bit too close to the delete button for my comfort
> 
> It is because it is in a btn-group. We can separate them like this and put the toggle button at the end:
> ![image](https://user-images.githubusercontent.com/703248/75996743-9d2e9000-5efe-11ea-82f9-e4b726df436b.png)

I like that a lot more. But now that you are talking about btn-groups, perhaps it could be put on the right of the existing expand button, so we have `[+] [>] [>>]`

**Comment by agriffard** [comment]
> perhaps it could be put on the right of the existing expand button

![image](https://user-images.githubusercontent.com/703248/75999361-6195c500-5f02-11ea-87b0-bcdc4533a0cd.png)
![image](https://user-images.githubusercontent.com/703248/75998922-d3214380-5f01-11ea-8980-5ac6770c4ccb.png)

I don't really like it on the left.

![image](https://user-images.githubusercontent.com/703248/75999295-4d51c800-5f02-11ea-8b83-ddbd14f2822d.png)
![image](https://user-images.githubusercontent.com/703248/75999188-285d5500-5f02-11ea-8f16-7ff9aefc068d.png)

Even in a group.

**Comment by mawendel** [comment]
Yeah, it does look a bit too noisy.

I would go with this suggestion then, unless anyone else has a better idea
> > ![image](https://user-images.githubusercontent.com/703248/75996743-9d2e9000-5efe-11ea-82f9-e4b726df436b.png)

**Comment by ns8482e** [comment]
IMO it’s confusing for user to have two buttons for expand/collapse on card header

I like button on hover-line button can be placed on left, similar to document outline in vs code

**Comment by hishamco** [comment]
What if we click the header toggle the state either expand or collapse

**Comment by agriffard** [comment]
The simpler, the better. I think I will just add a 'toggle all widgets' button in the 'Insert widget' hover line.
![image](https://user-images.githubusercontent.com/703248/76091479-f01b4c80-5fbd-11ea-8a75-1d55b0076e57.png)
