### ISSUE TITLE
Cannot find Razor Pages ViewComponent View

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5642]
When using a ViewComponent in a razor page, the module isn't detected as ComponentView containing module.

It appears that the ComponentViewLocationExpanderProvider only checks for razor files in "/Views/Shared/Components". I think the location for views of ViewComponents in Razor Pages is: "/Pages/Components".

When I add a dummy cshtml file in the /Views/Shared/Components folder, the module is included to the search paths, but only "/Views/Shared/Components" and not "/Pages/Components".

The screenshot displays the list of paths. The view component from the module Idella.Cms.Module is displayed in the Idella.ExternalProfiles module.

![image](https://user-images.githubusercontent.com/1059562/75450421-0fd3c480-596f-11ea-8084-cb6f080cb52d.png)

ps. The culture variants are also not added to the search paths.

**Comment by ns8482e** [comment]
@ArieGato  IMHO a view component is to create something you can use in multiple places and can be accessed from controller views, shape views and razor pages and liquid. So It makes the most sense to put your view component in the Views folder's Shared folder.

If your component is discoverable from `/Views/Shared/Component` then I guess its good enough for OC module and you need not place your components anywhere else.

**Comment by ArieGato** [comment]
I don't mind placing the views in the Views/Shared/Components folder. I was following the example on the Microsoft docs. Because I was using Razor Pages the most logical place for the views of the ViewComponent for me was the Pages/Components folder.

**Comment by ns8482e** [comment]
I see! My understanding from Microsoft docs is that if you have project created with only Razor Pages template then the location is `/Pages/Shared/Components,` but you have both MVC and Razor Pages then suggested location is `/Views/Shared/Components/`

I guess you will get same above error, if you are not using orchard core cms and place your Components under Pages and try to use it from Controller views.

Orchard core modules supports both MVC controllers and Razor Pages so having view location`/Pages/Shared/Components,`  seems unnecessary.
