### ISSUE TITLE
Setting ViewContext on Liquid TagHelper 

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#5648]
In LiquidTagHelperActivator it should check for `[ViewContext]` attribute not the property name.

https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/TagHelpers/LiquidTagHelperActivator.cs#L58

As its possible that developer have given some different name. for example.

```
[ViewContext]
public ViewContext Vc { get; set; }
```

**Comment by hishamco** [comment]
If you have a look here

https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/TagHelpers/LiquidTagHelperActivator.cs#L41-L52

how `ViewContext` will be an attribute decorated with `HtmlAttributeNameAttribute`?!!

/cc @jtkech

**Comment by ns8482e** [comment]
See. https://github.com/aspnet/Mvc/issues/4744

**Comment by hishamco** [comment]
Pushing a PR soon ...
