### ISSUE TITLE
Multiple inconsistent ContentDefinitionRecord documents are being created during setup

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#5652]
It is still hard to make a stable repro for this bug but still, in some cases, when I am setting up the website where my modules bring contents to the website (e.g. from code in a Migrations for example a taxonomy item or using IRecipeMigrator to add a content item) a new version of ContentDefinitionRecord is being created. It causes NREs since some of the Content Types added to the first version of the ContentDefinitionRecord is not present in the second one and other migrations might fail because of this.

Example:
* ModuleA registers ContentTypeA
* ModuleB dependent on ModuleA, imports content items with ContentTypeA using IRecipeMigrator successfully.
* ModuleB also registers ContentTypeB
* ModuleC dependent on ModuleB, tries to import content items with ContentTypeB using IRecipeMigrator but FAILS because ContentTypeB does not exist (even if I've seen it registered using the debugger before the ModuleC migration is being executed).

**Comment by deanmarcussen** [comment]
A stable repro would be very helpful :)

But can you confirm whether you are using the FileDefinitionStore or Database Store?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
