### ISSUE TITLE
Feature Request - Import Package

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5658]
I noticed you added the ability to allow importing of a json file without being compressed which is good.
However I unzipped a export and then made changes to the json files and then I rezipped it.
The admin page threw an error when I tried to import a compressed folder of recipes that were zipped with Windows 10.

**Comment by deanmarcussen** [comment]
A zipped recipe file can only have one `recipe.json` in it.

From what I read here, you are requesting to have multiple `recipe.json` files imported at once.

I don't think this would work, as there would be no way to know which `recipe.json` should be imported first

**Comment by sebastienros** [comment]
I think you can reference other recipe files from the recipe.json. Have you tried it ?
