### ISSUE TITLE
Widgets rearranged themselves after adding more than 15 widgets for content type (WidgetsListPart)

### ISSUE THREAD

**Issue by sivakumar715** [OrchardCMS/OrchardCore#5672]
Widget rearranged themselves after adding more than 15 widgets for content type (WidgetsListPart)
Below are the steps to reproduce.
**Reproduce steps:**
- Created a content type called 'CustomPage' with WidgetsListPart
- Created a content item of above content type called 'AboutUs'  and added multiple widgets (html , other widgets etc.,)
- Once the number **widgets increase more than 15** , the widgets rearranged themselves in 'AboutUs' page.

![image](https://user-images.githubusercontent.com/54092242/75975493-9dc72680-5efe-11ea-968c-aa3562373a06.png)

Below is the Orchard Core package version: 
OrchardCore.Application.Cms.Targets 1.0.0-beta3-72452

Please let us know if  you need any further information.

**Comment by deanmarcussen** [comment]
Please could you try with the latest dev as so many great improvements have been made to Widgets since beta3
