### ISSUE TITLE
How to get User.Identity in liquid page

### ISSUE THREAD

**Issue by dewebeloper** [OrchardCMS/OrchardCore#5673]
In my app I have Login, Register or My App buttons, dependes if user is authenticated or not.

How I can get User.Identity.IsAuthenticated in liquid page?

**Comment by mawendel** [comment]
There is no variable or filter you can use. But if User.Identity.Name is null, then there is no authentication for the current httpcontext.

**Comment by dewebeloper** [comment]
Ok. But where User.Identity.Name stands in liquid content?

**Comment by mawendel** [comment]
Take a look at the docs for liquid:
https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/

**Comment by dewebeloper** [comment]
Cool, thanks.

**Comment by agriffard** [comment]
@dewebeloper please close your issue if it has been answered.
