### ISSUE TITLE
RC1 gitignore file creates build issues

### ISSUE THREAD

**Issue by mwentz** [OrchardCMS/OrchardCore#5675]
If you download the source zip file for RC1 and create a repository, the code pulled from the repository will fail to build and run in Visual Studio.

It looks like this was fixed in commit fa86b7f0c4430e49bd67169084d951b90bbbe66f 

Workaround: grab the .gitignore file from the dev branch and commit the .cs files that were missing.

**Comment by sebastienros** [comment]
TODO: Close the issue once 1.0 is released
