### ISSUE TITLE
Menu as widget not rendering

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5677]
I'm trying to add a menu on a Layer to show different menus per Layer. I add StereoType Widget to the menu content type of TheBlogTheme. I then want to select an existing Menu content item in the Layer interface. That doesn't seem possible.
But also when I add a new menu to a Zone I can add Menu Items, but those are not rendered in the site. Is this by design?

**Comment by deanmarcussen** [comment]
Yes, menu's don't render directly, they have be called like is done in `TheBlogTheme` `Layout.liquid`
`{% shape "menu", alias: "alias:main-menu", cache_id: "main-menu", cache_fixed_duration: "00:05:00", cache_tag: "alias:main-menu" %}`

So for what you are wanting to do, I would create your menus as normal menus (not as a widget), then use a `Liquid Widget` in the layers / zones, to render the menu you want, using the code above in the `Liquid Widget` but with the name of the menu you want to render

**Comment by ArieGato** [comment]
Thnx! It worked like a charm.
