### ISSUE TITLE
Creating a SASS site then running the Blog recipie causes issues

### ISSUE THREAD

**Issue by garthtee** [OrchardCMS/OrchardCore#5681]
When I create a SASS site then run the Blog recipie, some the admin menu items don't work. For example; `Content -> Media Library` and `Design -> Widgets`.

If I create the site from scratch again, and select blog first from the site creation page, all of the admin menu items work fine.

**Comment by hishamco** [comment]
Are you using the latest bits?

@agriffard any idea?

**Comment by sebastienros** [comment]
There might be a bug, but that's very uncommon to do such thing. While we try to find the issue you should actually create a new tenant with this recipe. Right now don't try to run a Setup recipe on an existing tenant. There might be some incompatible steps that we haven't discovered yet.

**Comment by agriffard** [comment]
Setup recipe are not listed anymore in the Recipes admin page.
