### ISSUE TITLE
Select All checkbox should react to selected items

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5682]
Almost the index pages in the admin site have a notion of select all items, but the tiny little issue from UI/UX perspective is whenever the user select some items the checked state for the select all checkbox doesn't react to the selected items. The following screen shots will show you a use case in Tenants page

**Before**
![Before](https://user-images.githubusercontent.com/3237266/76161860-68157e00-6148-11ea-891a-82c1c6a6c578.gif)

**After**
![After](https://user-images.githubusercontent.com/3237266/76161875-7c597b00-6148-11ea-895e-188878d4be5b.gif)

@agriffard you 're the one who did an enhancements on the filter bar and prettify the items look and feel, so should I push a PR to fix the UI/UX issues everywhere or shall I group them into small managed PRs?

**Comment by hishamco** [comment]
FYI I introduced an intermediate state to make this looks exact same as GitHub selector

Just waiting for your reply to push my changes ...

**Comment by agriffard** [comment]
Ok, it should also display '1 selected' but it is a bit complicated because it should handle the singular/plural in javascript (ex: in French => 1 sélectionné, 2 sélectionnés).
To separate the 2 localizations, may be we should display @T["selected item"] and @T["selected items"]

**Comment by agriffard** [comment]
> should I push a PR to fix the UI/UX issues everywhere or shall I group them into small managed PRs?

One PR should be enough ofr all the admin pages having a 'select all' checkbox.

**Comment by hishamco** [comment]
Sure, I will take care about the checkbox states in this PR, we could add a localization enhancement then

**Comment by agriffard** [comment]
The List admin page should also have the new UI: See #5349.

**Comment by hishamco** [comment]
Should I wait until we fix #5349 or we can merge this for now, then apply this change in all needed pages?
