### ISSUE TITLE
'OrchardCore.Microsoft.Authentication' module not enabled through recipe file

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#5685]
I have included 'OrchardCore.Microsoft.Authentication' in a recipe file and tried to run the application.

The above module is not enabled in admin screen. Is there any other step to enable this module ?

Kindly do the needful.

**Comment by agriffard** [comment]
Duplicate. Already listed in #5558

**Comment by timlunev** [comment]
@RajasekarPR the Microsoft Authentication should be included in your recipe file with "OrchardCore.Microsoft.Authentication.MicrosoftAccount" string, for example: 
```json
{
  "steps": [
    {
      "name": "Feature",
      "enable": [		
        "OrchardCore.Microsoft.Authentication.MicrosoftAccount"
      ],
    }
  ]
}
```

**Comment by RajasekarPR** [comment]
@timlunev It works as expected. Thanks tim

**Comment by timlunev** [comment]
@agriffard we can close the issue
