### ISSUE TITLE
How to filter content by taxonomy ID

### ISSUE THREAD

**Issue by fuxiaojun0203** [OrchardCMS/OrchardCore#5686]
I want to filter out all articles in a taxonomy category

**Comment by hishamco** [comment]
@dodyg I think you address this before if I'm not wrong

**Comment by dodyg** [comment]
It's here

https://github.com/OrchardCMS/OrchardCore/issues/4494#issuecomment-553877942

**Comment by hishamco** [comment]
Thanks so much Dody

**Comment by deanmarcussen** [comment]
You can also use the `QueryCategorizedContentItemsAsync` Orchard Helper extension to make a query directly in Razor `var items = await @Orchard.QueryCategorizedContentItemsAsync()`

I'll reopen this and add to the docs tomorrow

**Comment by hishamco** [comment]
Thank Dean
