### ISSUE TITLE
How to render a shape without a theme

### ISSUE THREAD

**Issue by ItaloFSS** [OrchardCMS/OrchardCore#5687]
I'm trying to render a shape in a controller action without the website theme. In orchard 1, there was a Theme attribute that did this. Is there a way in core?

	IShape shape = await _shapeFactory.New.SearchResult( Test1: 1, Test2: "test2" );
	using var sb = StringBuilderPool.GetInstance();
	await using var sw = new StringWriter( sb.Builder );
	var htmlContent = await _displayHelper.ShapeExecuteAsync( shape );
	htmlContent.WriteTo( sw, HtmlEncoder.Default );

**Comment by sebastienros** [comment]
Apparently we are missing it. You can still render something without a theme manually in the meantime:

```
                    // Build shape
                    var displayManager = serviceProvider.GetRequiredService<IContentItemDisplayManager>();
                    var updateModelAccessor = serviceProvider.GetRequiredService<IUpdateModelAccessor>();
                    var model = await displayManager.BuildDisplayAsync(context.Source, updateModelAccessor.ModelUpdater);

                    var displayHelper = serviceProvider.GetRequiredService<IDisplayHelper>();
                    var htmlEncoder = serviceProvider.GetRequiredService<HtmlEncoder>();

                    using (var sb = StringBuilderPool.GetInstance())
                    {
                        using (var sw = new StringWriter(sb.Builder))
                        {
                            var htmlContent = await displayHelper.ShapeExecuteAsync(model);
                            htmlContent.WriteTo(sw, htmlEncoder);

                            await sw.FlushAsync();
                            return sw.ToString();
                        }
                    }
```

**Comment by ns8482e** [comment]
> var model = await displayManager.BuildDisplayAsync(context.Source, updateModelAccessor.ModelUpdater);

BuildDisplay uses layout

**Comment by sebastienros** [comment]
@ItaloFSS right, as @ns8482e mentions, don't use `BuildDisplay` from my sample, just use the shape you created.

**Comment by GlenLodewyckx** [comment]
Was this implemented in 1.0?

**Comment by sebastienros** [comment]
/cc @netwavebe 

Also wondering what it would mean to not use any theme, since shapes can only render things into zones.
From an API point of view we could just render every piece on a custom property of json:

```json
{
  "content": "<p>Hello</p>",
  "footer": "<script>...</script>",
  "meta": "<link .../>"
```

Even if you just want the content zone, `"Content"` is just a convention between the Layout and Placement from drivers. So I could imagine an method to take the zone name into account, or just return all the zones in a Dictionary, the same way I was suggesting the Json API.

**Comment by ns8482e** [comment]
@netwavebe Have you tried with  creating `Views/Shared/_ViewStart.cshtml` with Layout = null ?.

**Comment by deanmarcussen** [comment]
Sure remind me tomorrow on gitter. Also useful is a PartialViewResult. I use that to dynamically fetch and then compile as vue components sometimes

**Comment by ns8482e** [comment]
It's not a problem If using controller View - as you can set Layout or ThemeLayout or `ViewLayout` before shape execute.

**Comment by netwavebe** [comment]
@ns8482e I registered your example in startup without a filter condition, so I would expect theming to be gone everywhere but that's not the case. Breakpoints in `NoThemeFilter` are not hit. How do I 'apply' this filter?

**Comment by ns8482e** [comment]
@netwavebe try adding  `services.Configure<MvcOptions>(c => c.Filters.Add<NoThemeFilter>())`

I guess you still need to use Theme to identify which shape binding to render, so don't set theme to null, instead set ThemeLayout to null as suggested by @sebastienros 

```
 if (razorViewFeature.ThemeLayout != null)
            {
                razorViewFeature.Theme = null;
            }  
```

**Comment by netwavebe** [comment]
Mmmm, it seems it's working correctly IF there is a custom template... Here's what I did/tried...

This is a part of my code:
```
public async Task<IEnumerable<string>> RenderProducts(IEnumerable<ContentItem> products)
{
	var renderedProducts = new List<string>();

	foreach (var product in products)
	{
		var productShape = await _contentItemDisplayManager.BuildDisplayAsync(product, _updateModelAccessor.ModelUpdater, "Summary");
		var renderedProduct = await _displayHelper.ShapeExecuteAsync(productShape);

		using (var stringBuilder = StringBuilderPool.GetInstance())
		{
			using (var stringWriter = new StringWriter(stringBuilder.Builder))
			{
				renderedProduct.WriteTo(stringWriter, HtmlEncoder.Default);

				await stringWriter.FlushAsync();

				renderedProducts.Add(stringWriter.ToString());
			}
		}
	}

	return renderedProducts;
}
```

I'm calling this method in an API controller with a bunch of product content items. The result is send in JSON to an Angular client.

This is what Angular receives:

![image](https://user-images.githubusercontent.com/3008547/137537489-62e64a18-14e2-4508-ac1c-6ccf7daaada3.png)

First = "Summary" view of a product, embedded in the theme
Second = "Summary" view of a product (no theming applied)

This changes when creating a custom template:

![image](https://user-images.githubusercontent.com/3008547/137538112-9e0976b8-243c-46f7-88c8-a74708819b1d.png)

This is what Angular receives with the above template in place:

![image](https://user-images.githubusercontent.com/3008547/137538251-e968e026-3d95-4d2a-af67-6c337a61b1f2.png)

This is exactly what I want. I'm not sure why this happens? Why does it render theming for the "default" template, but not for my custom template? Not that I'm complaining... 😉

**Comment by sebastienros** [comment]
I assume the default template is a Razor file?

**Comment by sebastienros** [comment]
but would it mean that if the Blog theme for instance was built in Razor, and we were to render the list of Blog Posts with Summary, then it would render the layout for each? That seems odd. I will have to debug it to understand how it works again.

**Comment by dpomt** [comment]
Exactly the same issue here.

The rendered shape is embedded within the theme, the second, third etc. are without surrounding theme as expected.

![image](https://github.com/OrchardCMS/OrchardCore/assets/1379660/80734905-ffc1-4d3b-b21a-1fa9a5a4408a)

![image](https://github.com/OrchardCMS/OrchardCore/assets/1379660/06d0ee9c-bc04-49e4-8458-9adb2b268e31)

![image](https://github.com/OrchardCMS/OrchardCore/assets/1379660/a35f46b9-f42d-4974-b548-386bfc4b9008)

Any ideas how to solve this?

**Comment by netwavebe** [comment]
@dpomt Create a template via the admin dashboard and it will work correctly.

**Comment by Piedone** [comment]
It seems to me that the questions were discussed. If there are concrete improvement suggestions, please open issues for them.
