### ISSUE TITLE
GraphiQL exception when using a malformed Query Schema 

### ISSUE THREAD

**Issue by Fermain** [OrchardCMS/OrchardCore#5689]
When defining [Lucene Queries](https://docs.orchardcore.net/en/dev/docs/reference/modules/Queries/), the Schema field can cause GraphiQL to return an exception:

`Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined`

Issue can be reproduced by inserting a schema with an inappropriate content item name:

`{
    "type": "ContentItem/SomeContentItemType"
}`

**Comment by mkgn** [comment]
This problem still happens. Refer my last comments to #5782. After that, I did a brand new installation with empty Postgres db. Lucene & GraphQL modules enabled but I haven't added any Lucene queries. Only the index is created. Still when I go to GraphQL section I get the error.
