### ISSUE TITLE
Admin shouldn't render Header inside <head>

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5698]
As pointed out by @bleroy on gitter `TheAdmin` Layout has a header section / zone which is rendered inside the `<head> section, and would produce invalid html if rendered too.

```
    @await RenderSectionAsync("Header", required: false)
</head>
```
The `SafeMode` theme has the same issue.

We just need to figure out where a `Header` zone should be rendered in `TheAdmin`
i.e. before main content, or before side navigation (probably just before main content), or if we should remove the zone entirely.

**Comment by hishamco** [comment]
AFAIK `HEADER` should be rendered inside `<head>` unless it means the header of the website

**Comment by bleroy** [comment]
FWIW, the admin theme seems to already be rendering something called headmast in there. Browsers will render it and ignore the HTML error it constitutes. They just consider the body started early. It seems like it all works because the zone is last in the head. That means probably the best place to move it is first thing in the body. That would at least be the least disruptive to current behavior.

**Comment by ns8482e** [comment]
@deanmarcussen I guess `header` `<zone>` is for to  add `HTML` content via Layers  (eg meta, link) and ` <resources type="Header" /> ` to render registered resources.

**Comment by deanmarcussen** [comment]
@bleroy am struggling to find the headmast you mention. I wonder if it's coming from a feature I have not enabled, but searching the code I cannot find a reference to it.

If you have the html easily available to post, I'd quite like to figure out what's generating it, as it seems strange.

@ns8482e the `Header` zone is a reasonably well defined concept in Orchard, but as part of the `<body>` section not the `<head>`. The resource tag helpers, i.e. with `<resource type="Header"/>` should be enough to render any `<head>` meta data, or registered resources, as required. 

You did the pr recently which pre renders all the zones, so anything pushed into the `<head>` by a resource tag helper (scripts, meta helper etc) should be more than sufficient regardless the zone that it is called from. i.e. a css or meta tag helper should just be rendered in any zone, and automatically pushed to the head by the `at="Head"` modifier, if required, in the case of scripts, and by default in the case of meta.

We should have all the tag helpers for links, meta etc to suffice. If there is anything we are missing we should add that, rather than have a zone rendered in the `<head>`.

**Comment by ns8482e** [comment]
@deanmarcussen we use both, `<resource type="Header"/>` using style/script tag helper and `<zone name=“Header”>` to add adhoc styles/scripts/meta/base within shape templates with intention to render in `<head>` tag for admin. 

AFIK style tag Helper doesn’t support child content only url to css file is supported.

I guess it’s browser’s default behavior to render `HTML`  If `<head>` contains renderable HTML tags

IMO we need to keep `<zone name=“Header”>` in <head>

**Comment by bleroy** [comment]
OK, so I was wrong on one thing: it's not all admin pages, but here's the beginning of the markup I got from a content item creation page:

```html
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
    <title>Ye Olde shoppe - New Order</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link type="image/x-icon" rel="shortcut icon" href="/TheAdmin/favicon.ico" />

    <!-- Bootstrap CSS -->
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    
    
    
    <link href="/OrchardCore.Contents/Styles/Contents.css" rel="stylesheet" type="text/css" />
<link href="/OrchardCore.Resources/Styles/trumbowyg.css" rel="stylesheet" type="text/css" />
<link href="/OrchardCore.Media/Styles/media.css" rel="stylesheet" type="text/css" />
<link href="/OrchardCore.Resources/Styles/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="/TheAdmin/Styles/TheAdmin.css" rel="stylesheet" type="text/css" />

    <!-- This script can't wait to the footer -->
    <script src="/TheAdmin/Scripts/userPreferencesLoader.js" type="text/javascript"></script>

    
    <header class="masthead">
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in"></div>
                <div class="intro-heading text-uppercase">Order items</div>
            </div>
        </div>
    </header>

</head>
<body class="preload">
    <div class="ta-wrapper">
        <div class="ta-navbar-top">
            <a class="ta-navbar-brand" href="/"><span>Ye Olde shoppe</span></a>
            <div class="collapse navbar-collapse" id="navbar-links">
                <div class="mr-auto">
                    
                </div>
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link"><span><i class="fa fa-user" aria-hidden="true"></i></span><span> bleroy</span></a>
                    </li>
                </ul>
                <form method="post" class="form-inline" action="/Users/LogOff">
                    <button type="submit" class="btn btn-link nav-link" role="button"><i class="fa fa-sign-out" aria-hidden="true"></i> Log off</button>
                <input name="__RequestVerificationToken" type="hidden" value="CfDJ8PlgAF1vLg1IrzBECaMhQ_U1YpMxINP43lmLrZSwr1ubeXfb6WzM_yiHPbf4Ed1lhk-GZLfPx0CXpOywtxXp14dyWrLxilZLcD_029a0N12DptGfudEi98jIBzGLqFNtDzvSId-Y3FhD_NlAmEvhlkADAwS9KiA4RiE-BwrMS-NS-qZymdFQeTX1o98RsR8H6g" /></form>
            </div>
        </div>
```

**Comment by bleroy** [comment]
So bottomline: this is in principle my bad. However, I think the name "Header" for this zone is an absolutely terrible choice: "header" is an existing concept in HTML, and so is "head". This is confusing those two.

Note: `OrchardCore.Demo/Views/Shared/Header.cshtml` is also sending non-head only legal in body HTML into the "Header" zone, thus promoting bad practice in what looks like it should be a canonical example.

**Comment by agriffard** [comment]
https://github.com/OrchardCMS/OrchardCore.Commerce/blob/bf42dad2c787da94479a2feaa27e2b736f4dfcfb/Views/ShoppingCart/Index.cshtml#L4

**Comment by agriffard** [comment]
In some of my themes, I call this zone `Meta` or `HeadMeta`.

**Comment by bleroy** [comment]
I like those names 100% better.

**Comment by bleroy** [comment]
(yup, thanks Antoine, I have a couple of templates to fix in the module.)

**Comment by ns8482e** [comment]
> Note: `OrchardCore.Demo/Views/Shared/Header.cshtml`

Actually It depends on the Layout of the theme,  here in demo module it’s referring header zone defined in body tag of Agency theme so header.cshtml is valid

**Comment by ns8482e** [comment]
> In some of my themes, I call this zone `Meta` or `HeadMeta`.

It would be nice if all oc provided themes use uniform naming for zones

**Comment by bleroy** [comment]
I agree it depends on the layout of the theme, but that in turn adds inconsistency and confusion, so pleads for changing the name in the admin theme at least.

+1 on uniformity and consistency.

**Comment by deanmarcussen** [comment]
Ok, so confusion sorted.

Let's get a bit of uniformity and consistency, and see if we can please everyone.

I hope we can agree that the `Header` zone has both historically, with O1, and in the current OC front end themes refers to a zone that should be rendered early in the `<body>`

I don't think it's great practise to have a zone in the `<head>` section where invalid html can be rendered, however it seems we have this zone already in `TheAgencyTheme`.

Best practise is definitely the use of the Resource Tag Helpers. That's why we have them.

> AFIK style tag Helper doesn’t support child content only url to css file is supported.

**We should add this Niraj if it is missing and useful.**

Equally I don't want to break what users are currently doing... and if used with care not to produce invalid html...

So will do a small pr, and move the `Header` zone where it should be in `TheAdmin` (it does have to be before `Messages`, or with the navbar css nothing will render) and add a `HeadMeta` zone.
