### ISSUE TITLE
Bug? No template for bag item?

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5700]
When you render a bunch of items in a bag it seems to use the standard content template which adds a header to the top of the page for each piece of content.  So if you have 20 items in your bag you will have 20 headers?  Seems like a template just for a bag item is needed where it does not add a header.  This happened with the clean blog theme and the agency theme.

**Comment by sebastienros** [comment]
Can you share a piece of html with the issue, I don't really understand what headers you are talking about, like admin, front-end, ...

**Comment by JoshTango** [comment]
{% zone "Header" %}
<header class="masthead">
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in"></div>
            <div class="intro-heading text-uppercase">{{ Model.ContentItem | display_text }}</div>
      </div>
    </div>
</header>
{% endzone %}



<section>
  <div class="container">
      {{ Model.Content | shape_render }}
  </div>
</section>

**Comment by JoshTango** [comment]
that's from content.liquid
it injects something into the Header zone

**Comment by JoshTango** [comment]
regardless I am getting extra headers at top of page

**Comment by ns8482e** [comment]
> {% zone "Header" %}
> 
> {{ Model.ContentItem | display_text }}
> {% endzone %}
> {{ Model.Content | shape_render }}

Is this your custom template? 

Btw, All content shape fallback to content.liquid. So if you want to move title to header zone either use placement for the content type or create custom template for your content type instead of content.liquid

**Comment by JoshTango** [comment]
No this is not my custom template.  Its the code in clean blog and agency theme.

**Comment by JoshTango** [comment]
use clean blog and make a bag and add 5 items to the bag.  Then view it.  You will see 5 headers at top of page.

**Comment by deanmarcussen** [comment]
This is not a bug.

You need to make a content template for your bag items that doesn't render the title in the header

Something like `Content-MyBagItem.liquid` or with the Templates feature

As @ns8482e has said the fallback will always be `Content.liquid`, but when the default doesn't suit your needs, you need to make a template.

**Comment by JoshTango** [comment]
I did make a template for my specific content type in the bag

**Comment by JoshTango** [comment]
let me look further into it

**Comment by JoshTango** [comment]
Ok I still think it is a bug.  there should be a template fall back for bag items that is not the content.liquid template.

**Comment by JoshTango** [comment]
What I think you need is some situation awareness.  If the content it page level then it falls back to content.liquid but if the content is an item in a bag then it falls back to bag-item-content.liquid?

**Comment by ns8482e** [comment]
Renaming Content.liquid to Content-Page.liquid will solve your problem

**Comment by JoshTango** [comment]
@ns8482e then you guys should fix this in the clean blog and agency themes

**Comment by hishamco** [comment]
@ns8482e could please open a PR for this or let me do it if you can't

**Comment by JoshTango** [comment]
In time I hope to contribute but not now.  After I have written my first module.
If you do make a change please provide page level and non page level content templates in the themes.

**Comment by ns8482e** [comment]
@hishamco will create PR

**Comment by sebastienros** [comment]
In triage we decided that we should have a `Content_Contained` shape that would be used as a fallback to any bag part item that doesn't have a custom template. And add an alternate like `Content_Contained__[ContentType]` to each contained item, at the time it's rendered (in BagPart.cshtml).
