### ISSUE TITLE
Blog view counter

### ISSUE THREAD

**Issue by dewebeloper** [OrchardCMS/OrchardCore#5706]
How could I create blog view counter? 
I have blog and I want to track views of each blog post, after that I would like to create widget and select top 5 blog post by count of views.
What is approach to do this?

**Comment by hishamco** [comment]
You can track this in the front-end by increment a counter in page load and store it. Then you can use Queries to select top 5 for each blog post by count

**Comment by dewebeloper** [comment]
@hishamco thanks for info, I'm quite new with OC.  
Can you elaborate this in some details likw how I can track this on front-end? Do you have any example somewhere?

**Comment by Skrypt** [comment]
Use Google Analytics for that. Incrementing a counter which would write in the Database on each page view would be a wrong approach.

**Comment by hishamco** [comment]
Google Analytics is another approach. @Skrypt regarding writing into a database I saw many implementations out there, furthermore the rendered data comes from database

Anyhow you can use any approach that suitable for you

**Comment by dewebeloper** [comment]
@hishamco is there any example of implementations of this case?
I have no ideaeven how to start?

**Comment by hishamco** [comment]
Please first have a look to the Blog Theme

**Comment by dewebeloper** [comment]
Yes, I'm looking just into that example. I found Queries example and that looks like can do partial job.
Except, in my projevt I'm not able to see Queries link in side bar. How I can turn on that feature in my project?

**Comment by hishamco** [comment]
There are many types of queries: Lucene Query, SQL Query .. etc. You can use search feature to check in which features they are
