### ISSUE TITLE
How to create Application Panel like Admin Panel

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#5707]
I'm trying to create Application Panel to managing private application pages with path is /App/ and display Navigation with name="app" not "admin":
1. Create new theme with  @await RenderSectionAsync("Navigation", required: false)
2. Create new module to filter "app" menu, path, controlers, pages base on OrchardCore.Admin module.

Is that the right direction?

**Comment by Skrypt** [comment]
Which Theme it will use?

**Comment by lthoa** [comment]
> Which Theme it will use?

Create a new private theme. We can set to use this theme by manual in ThemeSelector

**Comment by Skrypt** [comment]
Admin Theme or Frontend Theme?

**Comment by lthoa** [comment]
> Admin Theme or Frontend Theme?

Is Frontend Theme but has Navbar menu like Admin Panel and we can control menu items display by enable Modules in Features. All pages run with "/App/" path instead of "/Admin/ path as in Admin panel.

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1329

**Comment by agriffard** [comment]
https://docs.orchardcore.net/en/dev/docs/reference/modules/Admin/#custom-admin-prefix

**Comment by lthoa** [comment]
> https://docs.orchardcore.net/en/dev/docs/reference/modules/Admin/#custom-admin-prefix

Thank you, but I want a new panel (Aplication Dasboard) separate with Admin panel.

**Comment by ns8482e** [comment]
So you want to create `/app` page that has left menu similar to admin ui?

**Comment by ns8482e** [comment]
You can create a new menu from admin and use menu shape in your `/app/index.cshtml` 
That will render your menus

**Comment by Skrypt** [comment]
You create a custom module using the dotnet new ocmodule command like we documented.
Then in your startup.cs file you will create a route that points to a custom controller that points to /app and then it will use the frontend theme.
