### ISSUE TITLE
Update Flow Widgets to maintain content item id

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5714]
Related to https://github.com/OrchardCMS/OrchardCore/issues/4620

Discussed in the meeting was the need to maintain flow widgets (and probably layer widgets) Content Item Id's between saves, as we have done for BagPart, in order to produce a good json diff between two parent content items containing widgets.

Also as the CreatedDate is modified during the update we should maintain that as well

**Comment by ns8482e** [comment]
+WidgetListPart

**Comment by jptissot** [comment]
This will be super useful in implementing a content item syncing feature for localized content.
