### ISSUE TITLE
Preserve authentication tokens stored in external authentication cookies

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5715]
Hi,

I'm trying to get access to the tokens issued by an Open ID Connect server. I configured a Hybrid Flow client with code id_token token.
The following code is always returning null for the tokens.
```
    var token = await _httpContextAccessor.HttpContext.GetTokenAsync("id_token");
    var rt = await _httpContextAccessor.HttpContext.GetTokenAsync("refresh_token");
```

I tested the code in a test aspnet core web app and then it works fine. I already tested by setting SaveTokens to true., but no success. Any suggestions?

Thnx,
Arjan

**Comment by kevinchalet** [comment]
Setting `SaveTokens` to true should definitely work. If it doesn't, we have a bug somewhere.

@ArieGato do you have a repro we can try to test it locally?

**Comment by ArieGato** [comment]
I don't think it's a problem with OpenIdDict. And it's quite difficult to create a repro with OrchardCore with an external OpenId Connect server. What do you need to see the behavior? Can it be a clone of the OrchardCore repo?

**Comment by kevinchalet** [comment]
@ArieGato yeah, a clone of OC using the OpenID client feature is fine.

**Comment by ArieGato** [comment]
I forked OC here: [Repro](https://github.com/ArieGato/OrchardCore)
A readme file is added to the OrchardCore.Cms.Web project to reproduce. I'm assuming you have an OpenID Connect Server lying around somewhere ;-)

**Comment by ArieGato** [comment]
@kevinchalet forgot to mention you for the repro

**Comment by kevinchalet** [comment]
@ArieGato I'll take a look when I have a moment.

**Comment by ArieGato** [comment]
> @ArieGato thanks, I'll take a look when I have a moment.

@kevinchalet did you see any chance to look into the issue?

**Comment by kevinchalet** [comment]
I did: the tokens are correctly stored by the OIDC handler in the "external authentication cookie", but they are not flowed by Identity when creating the "application cookie" (which is a quite common issue and not specific to Orchard: https://github.com/aspnet/Identity/issues/628).

If we wanted to flow the tokens as authentication properties from the external to the application cookies, we'd have to override the default `SignInManager` used by Identity. It's doable, but it also means there's a high risk the final application cookie will be quite big.

Alternatively, we could update the account controller to store the tokens retrieved from `ExternalLoginInfo` in the database. Because the last authentication process overrides the previous tokens, it won't work for every use case - e.g if you need to retrieve a token associated to a particular authentication session - but it should be fine in most cases. And it's easy to implement using Identity's `UpdateExternalAuthenticationTokensAsync()`.

**Comment by kevinchalet** [comment]
@MichaelPetrinolis FYI

**Comment by ArieGato** [comment]
> Alternatively, we could update the account controller to store the tokens retrieved from `ExternalLoginInfo` in the database.

That sounds great!

I have a question about updating the tokens when a new access token is requested. When I request a new access token, a new refresh token is issued and the old one is invalidated. So all the tokens need to be updated somehow. I think we need some sort of token management that handles those actions. Or is it as simple as calling ```UpdateExternalAuthenticationTokensAsync()```

**Comment by ArieGato** [comment]
@kevinchalet can you give your thoughts on this?

**Comment by ArieGato** [comment]
@kevinchalet Is there any way I can work around the issue until it is implemented?

**Comment by kevinchalet** [comment]
Nope, I'm afraid. If it's an important scenario for you, consider contributing by sending a PR to implement it (you'll also need to update the Identity YesSql user store to implement `IUserAuthenticationTokenStore`).

**Comment by ArieGato** [comment]
I wouldn't mind trying to implement this feature, but I would need some guidance. A breakdown what needs to be added/modified.

**Comment by ArieGato** [comment]
I added a UserToken entity to the YesSql user store. Implemented IUserAuthenticationTokenStore on  UserStore. Now I'm trying to find where to add the magic of storing the tokens. Where do I call ```UpdateExternalAuthenticationTokensAsync```

**Comment by ArieGato** [comment]
@kevinchalet I can't find where to update the tokens in the OC database. In the ExternalLoginCallback of the AccountController
```csharp
    var info = await _signInManager.GetExternalLoginInfoAsync();
```
```info.AuthenticationTokens``` is an empty array.
Any suggestions?

**Comment by ArieGato** [comment]
It's my first time I contribute, how do I contribute to OC? Should I fork the repo and create a PR from there, or do I create a branch in the main repo?

**Comment by sfmskywalker** [comment]
Hi @arkadiuszwojcik , the way to contribute code is indeed to fork the repo and create a PR from there.
