### ISSUE TITLE
Bug - html body text box in bag

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5716]
In a bag I enter the htmlbody content.
Then I save the item.
If I refresh and come back to the page and open the bag item the htmlbody is empty.
But as soon as a I click inside the text box the text will show up.

**Comment by agriffard** [comment]
I will have a look a it.
It might work if we add the autorefresh parameter of Code Mirror everywhere its is missing.

/cc @deanmarcussen
