### ISSUE TITLE
Add Cultures Picker in Setup page

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5726]
I saw a request from someone in gitter yesterday, then @Skrypt remind me with one of m old PR to add such feature, so I decide to file an issue for this

IMHO setup has some usability issue, so no one will know that the setup is localized until he looked into the code, then the user needs to add a querystring to make this happen, which is weird!! adding such feature will add some value

**Comment by hishamco** [comment]
What I'm planning to do is to add `CulturePicker` that retrieve all the supported culture from `appsettings.json`, whenever the user select one I will add a culture querstring or inject a localization cookie to make setup screen localized immediately

**Comment by agriffard** [comment]
Good idea.
Could it also detect the culture of the browser and load automatically the correct culture if it is in the appsettings.json?

**Comment by hishamco** [comment]
> Could it also detect the culture of the browser and load automatically

It could, but we can load it automatically unless it's a supported culture
