### ISSUE TITLE
Bug? Sitemap extra item

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5728]
I get this extra item in my sitemap.xml for some reason:

<url>
<loc>/Contents/ContentItems/4wt69grzzxm1ms2dxx0zkkecd0</loc>
<lastmod>2019-12-16T22:52:45+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0</priority>
</url>

**Comment by hishamco** [comment]
@deanmarcussen any idea

**Comment by deanmarcussen** [comment]
Perhaps you added `Autoroute` to an existing content type and did not publish one of the content items.

Try going to the edit url for the item
e.g.
`Admin/Contents/ContentItems/4wt69grzzxm1ms2dxx0zkkecd0/Edit` and seeing which item it is, then see if it has a valid `Autoroute` path, and publish it again.

**Comment by sebastienros** [comment]
Should be that it's missing an autoroute value. Please reopen if it was not the case.

**Comment by JoshTango** [comment]
Yes @deanmarcussen was correct.  I published and the problem went away.
