### ISSUE TITLE
DefaultContentManager outcome consistency issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#5731]
Here a sample module to test the outcome of creating new content items using the DefaultContentManager. There are inconsistencies in the outcome where sometimes the item created will be marked as published and drafted and sometimes will be marked as published. Also when using `contentItem.As<SomePart>.PartField = "something"` won't be affected in all cases.

I need to figure out if the issues comes from the .Merge method or if it comes from the DefaultContentManager or the Events that are called. Here in this module we try to set an AliasPart.Alias value as an example.

[AliasGenerator.zip](https://github.com/OrchardCMS/OrchardCore/files/4334776/AliasGenerator.zip)

**Comment by ropstah** [comment]
Regarding published/draft indicator in the Admin Contents List UI:

I create a new item and `Merge()` it with some previously constructed data (in my case some aliaspart)

```
var newItem = await _contentManager.NewAsync("Entity");
newItem = newItem.Merge(item);
await _contentManager.UpdateAndCreateAsync(newItem, VersionOptions.Published);
```

![image](https://user-images.githubusercontent.com/5072557/76912763-51dc9000-68b5-11ea-8d08-3b0a79a9a0e0.png)

It shows as both published and draft in the Admin UI
![image](https://user-images.githubusercontent.com/5072557/76912774-599c3480-68b5-11ea-935d-f257a12784e8.png)

If i load the entity via `QueryContentItemsAsync` then it looks like this:
![image](https://user-images.githubusercontent.com/5072557/76912857-9d8f3980-68b5-11ea-8ba1-23c22aae4a93.png)

**Comment by sebastienros** [comment]
We need more unit tests and documentation about how to use the content manager to do specific tasks on the items.

**Comment by deanmarcussen** [comment]
While I am looking at https://github.com/OrchardCMS/OrchardCore/pull/5487 I will circle back round to this issue soon.

Initially it looks to me like there is a couple of possible issues.

1. Call `.Apply()` after altering the alias part, or use `.Alter()`
2. Possible issues with `Merge()`
3. `UpdateAndCreateAsync()` is a strange concept, I know why it got there, but with handlers out of order like that I'm not sure how well `Alias` and `Autoroute` unicity is being properly maintained.

@ropstah it would be helpful if I could see more of the code you are using, and understand if you are always trying to create new items, or update existing items?

**Comment by Skrypt** [comment]
> UpdateAndCreateAsync() is a strange concept, I know why it got there @Skrypt , but with handlers out of order like that I'm not sure how well Alias and Autoroute unicity is being properly maintained.

They are not out of order. If you look at the OrchardCore.Contents AdminController you will see that we always call UpdateEditorAsync before doing a _contentManager.Create(contentIem). So actually by using this UpdateAndCreateAsync() we ensure that we use the proper order of calling event handlers.

Alias and Autoroute unicity is an other issue that I think is not related directly with these events order as they are respected.

**Comment by ropstah** [comment]
I looked a little bit more at the `Merge()` and `ContentElement` concepts and found a bit more detail on what doesn't work.

What I tried to do was:
```
item.Merge(otherItem) //both of type ContentItem
```
This produces the contentitem in both published/draft state and after publishing it in the admin UI the contentitem is essentially rendered unusable.

What actually does work is:
```
item.Merge(otherItem.Content as object) //Content being the JObject from Data property returned as dynamic, hence the cast to object is required
```

This produces a normally working contentitem as either published _or_ draft and it can published/saved afterwards.

**Comment by ropstah** [comment]
@deanmarcussen I'm really just playing around hypothetically. At this point only creating items but I will definitely also be updating existing items. I think the main point is that I would like to use the `ContentItem` class as is done in the `ApiController` in the `Orchard.Contents` module... Using it as a viewmodel that binds to the request values and merge those values into either a new or existing content item.
