### ISSUE TITLE
Generating absolute URL in a background task

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#5739]
To build an absolute URL we need either the the scheme and host provided by the HttpContext.Request object or the BaseUrl property of the Orchard Core site settings. 

When we are in a background task we have a fake HttpContext built in BackgroundService.cs but it fills the Request object with only shell-level URL data like RequestUrlPrefix which is not enough to build an absolute URL. In Orchard 1 the fake HttpContext was built by using the BaseUrl site setting.

Not sure what would be the best approach to this since in Orchard Core the site settings are given in the OrchardCore.Settings and not in the framework core. I was trying to build an IHttpContextAccessor decorator to provide another fake HttpContext as a workaround, however, I wouldn't replace the originally generated HttpContext, I'd like to extend it somehow.

It would be even better to make it part of the framework. Using an event handler maybe where in OrchardCore.Settings we extend the fake HttpContext using the BaseUrl maybe?

Please let me know your suggestions.

**Comment by Sen-Gupta** [comment]
Hey @barthamark  @sebastienros , is there a work-around for it?

**Comment by barthamark** [comment]
I built an `IHttpContextAccessor` decorator as a workaround. It looks like this:

```
    public class HttpContextAccessorDecorator : IHttpContextAccessor
    {
        private readonly IHttpContextAccessor _hca;
        private readonly IServiceProvider _serviceProvider;

        public HttpContext HttpContext { get => GetHttpContext(); set => _hca.HttpContext = value; }

        public HttpContextAccessorDecorator(IHttpContextAccessor hca, IServiceProvider serviceProvider)
        {
            _hca = hca;
            _serviceProvider = serviceProvider;
        }

        private HttpContext GetHttpContext()
        {
            var httpContext = _hca.HttpContext;
            if (httpContext != null && (httpContext.Items["IsBackground"] as bool?) != true) return httpContext;

            var siteService = _serviceProvider.GetService<ISiteService>();
            var siteSettings = siteService.GetSiteSettingsAsync().Result;
            var url = string.IsNullOrEmpty(siteSettings.BaseUrl) ||
                !Uri.IsWellFormedUriString(siteSettings.BaseUrl, UriKind.Absolute) ?
                "http://localhost" : siteSettings.BaseUrl;
            var uri = new Uri(url, UriKind.Absolute);

            httpContext ??= new DefaultHttpContext().UseShellScopeServices();

            httpContext.Request.Scheme = uri.Scheme;
            httpContext.Request.Host = new HostString(uri.Host, uri.Port);
            httpContext.Request.PathBase = uri.AbsolutePath;
            httpContext.Request.QueryString = new QueryString(uri.Query);
            httpContext.Request.Path = "/";
            httpContext.Items["IsBackground"] = true;

            return httpContext;
        }
    }
```

In the `Startup.cs` I've registered it like this:

```
services.Decorate<IHttpContextAccessor, HttpContextAccessorDecorator>();
```

The `.Decorate` extension method is coming from the [Scrutor](https://github.com/khellang/Scrutor) library, however, it's not mandatory to use.

**Comment by Sen-Gupta** [comment]
@barthamark Thank you so much! I like the approach you have taken.

**Comment by jtkech** [comment]
Interesting, added to my list
