### ISSUE TITLE
Design: Improved modules/features management UI

### ISSUE THREAD

**Issue by DaRosenberg** [OrchardCMS/OrchardCore#574]
In Orchard Core it would be great if we could provide a better UI for this than what we have in Orchard 1.x.

In particular I would love the following enhancements:

- Move from a card/grid based layout to a tree list where the hierarchy is based on feature ID namespace. This will make many features such as "Google" more clear because they will be shown in the context of "OpenID".
- Visualize modules as well as features, along with key module metadata such as author and version
- When enabling features, show a dialog with a list of features that will be enabled (including dependencies)
- When disabling features, show a dialog with a list of features that will be disabled (including dependents)
- ~~Render each feature in a way that does not assume an absolute height (because descriptions currently get truncated)~~ Already fixed in Orchard Core
- Display feature ID (e.g. `Orchard.Layouts`) for each feature, and allow filtering on feature ID
- Improve the bulk action controls. Instead of 3 clicks (dropdown, selection, button) let's just show one button for each action (1 click).

I will try to create a mockup with a suggested design.

**Comment by sebastienros** [comment]
Take a look at Drupal

**Comment by DanielStolt** [comment]
Drupal schmupal, let's discuss how we want in Orchard. Do you agree with the suggestions?

**Comment by sebastienros** [comment]
Then you look at Drupal's solution and you decide to change your suggestions ;)

**Comment by psijkof** [comment]
Bulk enabling/disabling would be an awesome feature to have.
![image](https://user-images.githubusercontent.com/25638593/45095630-6f546980-b116-11e8-9add-631cfb50d315.png)
Reminding @sebastienros about a demo he did recently  :)

**Comment by sebastienros** [comment]
@psijkof Please file a separate issue

**Comment by agriffard** [comment]
See #1752 : batch Enable/Disable features
