### ISSUE TITLE
Bug Sitemap URL

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5742]
Google search console says my sitemap.xml has several errors.  All urls are invalid it says.

**Comment by JoshTango** [comment]
I think this is you @deanmarcussen

**Comment by JoshTango** [comment]
Maybe your suppose to put the name of the website in front of the relative url?

**Comment by Skrypt** [comment]
You need to set the baseurl of your tenant for that. And I think the module show a warning about that. So I don't think there is any issue else than that. Without any repro we close the issue.

**Comment by JoshTango** [comment]
thanks, sorry my bad
