### ISSUE TITLE
Exception registering external user

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#5745]
Hi,

I'm getting an exception when registering an external user.

Exception:
```
InvalidOperationException: Could not create an instance of type 'OrchardCore.Users.ViewModels.RegisterExternalLoginViewModel'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, give the 'model' parameter a non-null default value.
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinder.CreateModel(ModelBindingContext bindingContext)
```

Repro:

1. go to login page
2. choose the external IDP
3. login with a user that is not registered yet
4. on returning to OC (/OrchardCore.Users/Account/ExternalLoginCallback) set the user name and click Register

Logfile: [orchard-log-2020-03-17.log](https://github.com/OrchardCMS/OrchardCore/files/4344206/orchard-log-2020-03-17.log)

Arjan

**Comment by deanmarcussen** [comment]
Regression from https://github.com/OrchardCMS/OrchardCore/pull/5710

It probably needed to be implemented with `IValidatableObject `

**Comment by ArieGato** [comment]
Is it even possible to use DI in a ViewModel?

**Comment by hishamco** [comment]
@deanmarcussen how this is related to `IEmailServiceValidator`?!!

**Comment by kevinchalet** [comment]
@hishamco you've updated `RegisterExternalLoginViewModel` and `EditUserViewModel` to use a non-default constructor taking an `IEmailServiceValidator` instance, which breaks the default model binder, that doesn't resolve constructor parameters of view models from the DI container.

As @deanmarcussen said, you'll need to remove the constructors and resolve `IEmailServiceValidator` from `ValidationContext` instead.

**Comment by hishamco** [comment]
I will address @deanmarcussen feedback now
