### ISSUE TITLE
new content items are gone

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#5747]
I can still see the data, but the content Items we're gone, I checked the user permission and all it can see are the old content that I've created and the new one is not displaying.

**Comment by sebastienros** [comment]
Repro steps?

**Comment by webmedia1012** [comment]
Hi Seb, thank you for your reply, unfortunately, I can't recreate the steps since there's no error, I'm thinking could it be the tenant? since we moved the box to DMZ , before it was on our dev server on prem not exposed externally, if that's the case, how do I trace that? - Thank you for all you do. OrchardCore is amazing!
