### ISSUE TITLE
Question: Add existing content item to list?

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5750]
Is a feature coming where we can add an existing content item to list?

**Comment by sebastienros** [comment]
Would be cool addition. With a link to open a popup and select an item from a search box. Like the content item picker.

**Comment by JoshTango** [comment]
yes, I found my self adding some items to the list then I decided to remove them.
Then I changed my mind and wanted to re-add them but I had no ability to do so.

**Comment by Registeel** [comment]
It's been almost 4 years on this. Anybody know if this functionality exists yet?

**Comment by hishamco** [comment]
Which list to do you refer to?

**Comment by sebastienros** [comment]
THE list ;) ListPart (e.g. Blog -> Blog Posts)

**Comment by hishamco** [comment]
@Registeel can you create a PR for this?

**Comment by Registeel** [comment]
> @Registeel can you create a PR for this?

I haven't built the functionality for this. It seems like a fair size change and I'm not familiar enough with the code base yet. I'm still just using it for a project. Maybe look into developing this when I have some downtime if nobody else is working on it.

**Comment by hishamco** [comment]
It's your if no one take it :)

**Comment by Piedone** [comment]
Issue for the opposite: https://github.com/OrchardCMS/OrchardCore/issues/3667. So, let's keep these under one issue, there.
