### ISSUE TITLE
After the content publishing is successful, you should skip to adminRouteValues by default, not Edit

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#5752]
The contents of the ticket, can not be modified after publication, after the publication is successful, I will modify the permissions, and modify the adminRouteValues。

var adminRouteValues = (await _contentManager.PopulateAspectAsync<ContentItemMetadata>(contentItem)).AdminRouteValues;

![image](https://user-images.githubusercontent.com/16968103/77036816-ee547e80-69ea-11ea-91dc-b15a7c05850c.png)

**Comment by chinasqzl** [comment]
Same as CreatePOST：

if ((!string.IsNullOrEmpty(returnUrl)) && (!stayOnSamePage))
            {
                return LocalRedirect(returnUrl);
            }

            var adminRouteValues = (await _contentManager.PopulateAspectAsync<ContentItemMetadata>(contentItem)).AdminRouteValues;

            if (!string.IsNullOrEmpty(returnUrl))
            {
                adminRouteValues.Add("returnUrl", returnUrl);
            }

            return RedirectToRoute(adminRouteValues);

**Comment by sebastienros** [comment]
Can you provide some repro steps and what you would expect to see. It's hard to understand what issue you are describing here.

**Comment by chinasqzl** [comment]
Inventory management
warehousing entry 、 outbound delivery order  
Cannot be changed after publication, nor can administrators @sebastienros

**Comment by sebastienros** [comment]
I think the request here is to redirect to the content item list instead of staying on the edit page, when publish is invoked. But I might be wrong :/

**Comment by Piedone** [comment]
Closing due to no reply from the author.
