### ISSUE TITLE
Archive Later functionality

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#5754]
Analogous to Publish Later (https://github.com/OrchardCMS/OrchardCore/issues/3991): Have a way to unpublish content items at a given time. Can be developed by mimicking what Publish Later does or refactoring it so it offers both features.

Thinking about it, I think the best is to copy the Publish Later module and modify it, dirty as it sounds. I don't see building on the same codebase being feasible if we want a single content item to potentially have scheduled publishing and scheduled archiving at the same time (if we want only one of them it gets easier).

**Comment by remesq** [comment]
There was an Archive Later module for Orchard 1.2. 

http://gallery.orchardproject.net/Packages/Orchard.Module.Orchard.ArchiveLater/1.2.41

I don't know if that helps.

**Comment by Piedone** [comment]
Yep, the idea is to have the same functionality in Orchard Core (just as the Publish Later module provides the same as the module in O1).

**Comment by hishamco** [comment]
I prefer to do it another module, coz the name is matter and could be confuse the audience. May be find away to abstract the common APIs

**Comment by Piedone** [comment]
That's what I think too.
