### ISSUE TITLE
Improve Deployment Plan Execution

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5756]
As I see from the following lines:

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Deployment.Core/Services/DeploymentManager.cs#L26-L32

`ExecuteDeploymentPlanAsync()` take unnecessary iterations during the execution

### Before

1. Assume each deployment source has **10 x DS** deployment steps

| Deployment Sources | Deployment Steps |
|---|---|
| DS<sub>1</sup> | 10 |
| DS<sub>2</sup> | 20 |
| DS<sub>3</sup> | 30 |
| DS<sub>..</sup> | .. |
| DS<sub>10</sup> | 100 |

**Total Iterations = 10 x 550 = 5550**

2. Assume each deployment source has **100 x DS** deployment steps

| Deployment Sources | Deployment Steps |
|---|---|
| DS<sub>1</sup> | 100 |
| DS<sub>2</sup> | 200 |
| DS<sub>3</sup> | 300 |
| DS<sub>..</sup> | .. |
| DS<sub>10</sup> | 1000 |

**Total Iterations = 10 x 5500 = 55000**

This is only for **10** deployment source, What about **1000**?!!

| Deployment Sources | Deployment Steps |
|---|---|
| DS<sub>1</sup> | 100 |
| DS<sub>2</sup> | 200 |
| DS<sub>3</sup> | 300 |
| DS<sub>..</sup> | .. |
| DS<sub>100</sup> | 10000 |

**Total Iterations = 100 x 505000 = 50500000**

This is **HUGE**, while we still refactor both the `DeploymentSource` and `DeploymentStep` to execute the needed iterations only

### After

1. Assume each deployment source has **10 x DS** deployment steps

| Deployment Sources | Deployment Steps |
|---|---|
| DS<sub>1</sup> | 10 |
| DS<sub>2</sup> | 20 |
| DS<sub>3</sup> | 30 |
| DS<sub>..</sup> | .. |
| DS<sub>10</sup> | 100 |

**Total Iterations = 550**

2. Assume each deployment source has **100 x DS** deployment steps

| Deployment Sources | Deployment Steps |
|---|---|
| DS<sub>1</sup> | 100 |
| DS<sub>2</sup> | 200 |
| DS<sub>3</sup> | 300 |
| DS<sub>..</sup> | .. |
| DS<sub>10</sup> | 1000 |

**Total Iterations = 5500**

This is only for **10** deployment source, What about **1000**?!!

| Deployment Sources | Deployment Steps |
|---|---|
| DS<sub>1</sup> | 100 |
| DS<sub>2</sup> | 200 |
| DS<sub>3</sup> | 300 |
| DS<sub>..</sup> | .. |
| DS<sub>100</sup> | 10000 |

**Total Iterations = 505000**

In nutshell we want to reduce the number of iterations from n x m into Σ<sub>n</sub>m

Your thoughts @jtkech @sebastienros

**Comment by jtkech** [comment]
Would need to see more in details the deployment source code

But after a quick look, an `IDeploymentSource` only processes a given type of `DeploymentStep`, so yes all iterations are there but most of them just does nothing. To limit the iterations maybe we would need to register a generic service `IDeploymentSource<>` + a factory, and then resolve and use the right `IDeploymentSource<TDeploymentStep>` for a given `DeploymentStep` type.

Sorry i don't fully understand your comment, from where does the number `550` come from?

For me, if we have n steps and m sources, the number of iterations will be always `n * m`, knowing that `(n * m) - n` will just do nothing, only `n` of them will do something.

**Comment by hishamco** [comment]
> Sorry i don't fully understand your comment, from where does the number 550 come from?

550 is the summation of the deployment steps

A very simple example could be

DSrc 1 -> 3 DStp
DSrc 2 -> 2 DStp
DSrc 3 -> 4 DStp

The current implementation will iterate 3 * 9 = 27 times, while the proper iterations should be 3 + 2 + 4 = 9 times

Hope this clarify the issue

**Comment by hishamco** [comment]
> the number of iterations will be always n * m

This is correct if all the deployment sources have exact same number of deployment steps

**Comment by jtkech** [comment]
Okay i understand but as i saw a deployment source doesn't have deployment steps, it is there to process a given type of deployment step.

As i can see the number of steps is the count of `deploymentPlan.DeploymentSteps`, and the number of itérations is always equal to this number multiplied by the number of sources.

**Comment by hishamco** [comment]
> Okay i understand but as i saw a deployment source doesn't have deployment steps, it is there to process a given type of deployment step.

That's why I asked for refactoring if it's possible ;)

**Comment by deanmarcussen** [comment]
Maybe there is some confusion about what a deployment step is and a deployment source?

For a recipe when it is executed, it may have 10 steps.
Then it will iterate each step, and iterate the sources finding the source that will provide data to that step.

So the math is 10 steps * 20 Deployment sources (there are approx 20)

10 * 20 = 200, so not so many iterations.

Unless I'm misunderstanding something else you have seen @hishamco ?

@jtkech suggest we could have a factory resolver, like was done recently for the display drivers, but this is a not a heavily used method, and only used rarely in the admin, so I'm not sure there's much to gain

**Comment by hishamco** [comment]
If you think it's used rarely, then it's fine, but I was thinking for a scale app with tons of deployment sources and steps, also if it executes on remotes
