### ISSUE TITLE
FlowPart: no icon for 'toggle all' button

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/OrchardCore#5760]
I updated my solution to the latest code. I'm not seeing an icon for the 'toggle all' button:

![flow-noicon](https://user-images.githubusercontent.com/3008547/77158383-7bf3a500-6aa3-11ea-8fee-133a6c8ec087.png)

Discussed this with Antoine. It's working on his side. It's not clear what's the difference, since we should be running the same code.

**Comment by agriffard** [comment]
The style is in the view:

```
<style>
.toggleAll:after {
font-family: 'FontAwesome';
content: "\f102";
}
.toggleAll.collapsed:after {
content: "\f103";
}
</style>
```

I will try to add it directly in theAdmin css.

**Comment by ns8482e** [comment]
@agriffard you can add it to Scss file https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Flows/Assets/scss/flows.edit.scss

**Comment by netwavebe** [comment]
I wonder, how are other users seeing this? Is there an icon, or not?

**Comment by netwavebe** [comment]
I fetched the latest version (with https://github.com/OrchardCMS/OrchardCore/pull/5759 and
https://github.com/OrchardCMS/OrchardCore/pull/5764) but it made no difference:

![flow-noicon](https://user-images.githubusercontent.com/3008547/77223173-6ab99f80-6b5a-11ea-92ed-3b2a3eaf3d51.png)

Styling is now coming from the .css:

![flow-noicon2](https://user-images.githubusercontent.com/3008547/77223180-79a05200-6b5a-11ea-81db-e06e8f532674.png)

**Comment by agriffard** [comment]
This works for me in an html file:
```
<style>.toggleAll:after{font-family:FontAwesome;content:"\f102"}.toggleAll.collapsed:after{content:"\f103"}</style>
<button class="toggleAll btn btn-secondary btn-sm collapsed" onclick="toggleWidgets(); return false;" title="Toggle all widgets"></button>
<script type="text/javascript">
    function toggleWidgets(){
        $('.toggleAll').toggleClass('collapsed');
    }
</script>
```
so I must have something like a cache of fontawesome.

Can you please try it and also with this:

```
<script crossorigin="anonymous" integrity="sha384-4yJXyYcQJQynz08thMlmIdGJtc1pH25IWEUxeXk25FYh7YxDQqu1NCAbhCC7zip6" src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/js/all.js" type="text/javascript"></script>
<script crossorigin="anonymous" integrity="sha384-GRL&#x2B;whSFS4qAoUG6xDB/5buVvCJ9ZN9jms&#x2B;GfJYWRNUm0eq2/KRYX9qRJcwxGo&#x2B;Y" src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/js/v4-shims.js" type="text/javascript"></script>
```

**Comment by netwavebe** [comment]
I tried this html locally:

`
<html>
<head>
<title>Test</title>
</head>
<body>

<style>.toggleAll:after{font-family:FontAwesome;content:"\f102"}.toggleAll.collapsed:after{content:"\f103"}</style>

<button class="toggleAll btn btn-secondary btn-sm collapsed" onclick="toggleWidgets(); return false;" title="Toggle all widgets"></button>
<button class="btn btn-secondary btn-sm collapsed" onclick="toggleWidgets(); return false;" title="Toggle all widgets"><i class="fas fa-angle-double-up"></i></button>

<script type="text/javascript">
    function toggleWidgets(){
        $('.toggleAll').toggleClass('collapsed');
    }
</script>

<script crossorigin="anonymous" integrity="sha384-4yJXyYcQJQynz08thMlmIdGJtc1pH25IWEUxeXk25FYh7YxDQqu1NCAbhCC7zip6" src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/js/all.js" type="text/javascript"></script>
<script crossorigin="anonymous" integrity="sha384-GRL&#x2B;whSFS4qAoUG6xDB/5buVvCJ9ZN9jms&#x2B;GfJYWRNUm0eq2/KRYX9qRJcwxGo&#x2B;Y" src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/js/v4-shims.js" type="text/javascript"></script>

</body>
</html>
`

The result:
![flow-noicon3](https://user-images.githubusercontent.com/3008547/77227673-38239d00-6b82-11ea-8473-fbfe667b596a.png)

**Comment by agriffard** [comment]
I updated ResourceManifest, it was missing in my previous PR.
```
<script crossorigin="anonymous" integrity="sha384-4yJXyYcQJQynz08thMlmIdGJtc1pH25IWEUxeXk25FYh7YxDQqu1NCAbhCC7zip6" src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/js/all.js" type="text/javascript"></script>
<script crossorigin="anonymous" integrity="sha384-GRL&#x2B;whSFS4qAoUG6xDB/5buVvCJ9ZN9jms&#x2B;GfJYWRNUm0eq2/KRYX9qRJcwxGo&#x2B;Y" src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.0/js/v4-shims.js" type="text/javascript"></script>
```
There is a little problem because the `+` int the integrity are encoded into `&#x2B;` but it should work.

**Comment by netwavebe** [comment]
I assume fortawesome works by replacing fa-xxx classes with inline vsg images. When using :after there is nothing to replace.

**Comment by sebastienros** [comment]
https://jsfiddle.net/Laxsrvnt/

**Comment by agriffard** [comment]
Solution:
https://stackoverflow.com/questions/48753688/font-awesome-5-shows-empty-square-when-using-the-jssvg-version
https://jsfiddle.net/bv4msf0d/1/
