### ISSUE TITLE
FlowPart: layout for second HTML widget is broken

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/OrchardCore#5761]
When adding two widgets with an HTML field to a FlowPart, layout is broken for the second widget:

![flow-layout](https://user-images.githubusercontent.com/3008547/77164819-540b3e00-6ab1-11ea-9280-786bf6c9c37f.png)

It's working fine when adding the widget, this happens when you edit an existing item.

**Comment by ns8482e** [comment]
In PR #4910, I am hiding label if it’s only child element of editor part to reduce white spacing (right HTML widget)

But it seems for some reason from somewhere else it’s adding another child tag other than label for the first left HTML widget so the css to hide label is not applied in above screenshot. Need to investigate.

**Comment by TFleury** [comment]
Hi @ns8482e
I found a fix, could you review #6000 ?

**Comment by ns8482e** [comment]
@TFleury awesome Thank you.  It's nice idea to have model at Footer. 
Also there is an open issue #4893 related to media - Does your fix #6000 fixes that too?

**Comment by TFleury** [comment]
The issue in #4893 is not clear to me, and I was unable to reproduce it.
I don't think #6000 fixes it, but it should probably be closed unless someone can reproduce it.
