### ISSUE TITLE
Read me file with explanation to demo module

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#5763]
Demo module include allot of relevant and helpfull stuff, but the problem is that you need doing deep research to understand what is what (especially if you new to orchard core).
It will be nice to comment / add notes to that module (similar like Lombiq did to the demo they create)

Also, I think this module is amazing, and the video from YouTube really help to learn Orchard core , especially for the teams that moving from Joomla / WordPress.

Thanks!

**Comment by vitalybrandes** [comment]
Adding the url to Lombiq demo module

**Comment by hishamco** [comment]
@agriffard could please the URL to the suitable place on the docs, or refer it to me and I will add it

**Comment by agriffard** [comment]
> could please the URL to the suitable place on the docs, or refer it to me and I will add it

@hishamco : @domonkosgabor made a PR #3955 to add such a link.
I will probably close this PR and try to find a more appropriate section to add any external learning material on OC.

> the video from YouTube really help to learn Orchard core

What YouTube video are you talking about @vitalybrandes ?

**Comment by vitalybrandes** [comment]
I am just saying that I am moving from Joomla to OC, all videos from @sebastienros  in Lombiq Chanel's  have some example.
Just cut / paste with relevant search attributes, and this will really help to move forward with orchard much faster.
My opinion .
Regarding the demo module, the module exits, but any comment or readme that I found 🤷🏼‍♂️
