### ISSUE TITLE
Latest orchard core package ( Issues )

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#5783]
With the latest orchard core package ( 1.0.0-rc1-12449) facing below two issues.

1. Widget stereotypes has been lost for existing widgets. 
2. Technical name s not same as display name for previous fields ( example it showing as  html field, boolean field )

Kindly do the needful.

**Comment by sebastienros** [comment]
Can you provide some repro steps?

If that's an upgrade, what versions are you upgrading from and to?

**Comment by lazcool** [comment]
I too am hitting the second issue with the latest preview packages. Started happening a few days ago.

If I add a field to a content type like so..
![image](https://user-images.githubusercontent.com/12608907/77747729-0c3b6800-7017-11ea-8220-65cfbe150466.png)

after saving and then editing the new field, the technical name is set to the field type...
![image](https://user-images.githubusercontent.com/12608907/77747811-2e34ea80-7017-11ea-9567-e6f355910de0.png)

If I then add a second field of the same type, it replaces the first field, as it's given the same technical name.

Content types created through recipes are fine.

**Comment by jtkech** [comment]
Just tried with the las dev source code, i can't repro

**Comment by Piedone** [comment]
Let's roll out the current dev as RC2 then: https://github.com/OrchardCMS/OrchardCore/issues/5814

**Comment by deanmarcussen** [comment]
I can't repro this either. 

@RajasekarPR can you please provide some repro steps

@lazcool I opened an issue on your repository where I can see the custom content definition service is to blame.

**Comment by lazcool** [comment]
Cheers @deanmarcussen you're a star!

**Comment by jtkech** [comment]
So i assume it is solved for you, so i close it, re-open it if i misunderstood ;)
