### ISSUE TITLE
OIDC Authentication Client - Unable to SignOut

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#5784]
Hello, I think there is an issue when logging in when the user has no role that gives him access to the administration pages.

Currently the user gets redirected to a 403 error page (which is fine) but the issue is that afterwards I can't logout and login with another user unless I manually delete the cookies.

Is there any way to "shortcircuit" the external login process if the user has no roles that allow him to access the administration pages?

**Comment by ArieGato** [comment]
If you didn't disable the local password login in the Login settings you could navigate to ~/login. Then you can login as administrator. Otherwise you should first manually logout from the oidc server and then navigate to ~/login.

**Comment by nuno-tiago-reis** [comment]
Yes I have done that before but I think that if he user has no roles to access the administration panel then I should be able to shortcircuit the whole login process and redirect him back to the login page.

**Comment by MichaelPetrinolis** [comment]
some pages on front end could be visible only for authenticated users. The user is authenticated, but has no access to admin panel. You could add a logout link on your theme for authenticated users, so that one could logout...

**Comment by sebastienros** [comment]
There is already a POST action at `/Users/LogOff` that you can use from your site.
