### ISSUE TITLE
Email Feature Setting not visible on Tenants  

### ISSUE THREAD

**Issue by fenngineering** [OrchardCMS/OrchardCore#5788]
I have an issue where by the email (smpt) settings are not visible on tenant when the feature has been enabled.  Please advise.

Kind regards
Andy

**Comment by jtkech** [comment]
Just tried, it works.

> when the feature has been enabled

 Did you enable the feature under the related tenant?

**Comment by hishamco** [comment]
May be you enable it on the default tenant, so as Jean said be sure you enable it for the related tenant

**Comment by fenngineering** [comment]
So I had to disable it 1st then re-enable it, in my appsettings i have got the recipe set to agent in visual studio, some sort of defect there but it seems to be enabled now - with setting to configure  the smpt on the tenant.

Thanks for your support :)

**Comment by jtkech** [comment]
Okay, fell free to re-open it if you still have any issue
