### ISSUE TITLE
A user without the ManageTenants permission can access to the tenants

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5790]
Repro: Create a user with the Moderator role and go to the admin, you will be able to see the Tenants menu.

**Comment by sebastienros** [comment]
Menu item or page?

**Comment by deanmarcussen** [comment]
@agriffard I can see that the `Index` methods (Get and Post) of the `AdminController` do not have authorization checks (they should!) but the menu item itself doesn't show for me.

**Comment by agriffard** [comment]
Both

**Comment by agriffard** [comment]
Ok, on the instance that I tested, the permission is effective:
![image](https://user-images.githubusercontent.com/703248/77408826-98038900-6db8-11ea-877f-5083b4d218c0.png)
I don't know where it is coming from.

On another instance, it is not effective so the menu is not displayed but you can access the page because the permission check is missing,

I will make a PR to fix it.
