### ISSUE TITLE
Fields to fill out on the add user page are not displayed

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#5792]
Hi!
I can't add user on the / Admin / Users / Create page, I see only the "Save" and "cancel" buttons are displayed. No any fields are visible.
How can this be fixed?

![IkJHb8gR 1](https://user-images.githubusercontent.com/20708134/77412468-1d526200-6de8-11ea-9dc5-b58fe1aff4b9.png)

**Comment by hishamco** [comment]
Strange!! could please refresh your browser cache

**Comment by niknikita** [comment]
> Strange!! could please refresh your browser cache

Updated, did not help

**Comment by timlunev** [comment]
@niknikita Do you have any errors in browser dev console? You should see in your html markup `<div class="edit-item-primary">`, do you have it?

**Comment by niknikita** [comment]
> @niknikita Do you have any errors in browser dev console? You should see in your html markup `<div class="edit-item-primary">`, do you have it?


No errors, tag <div class = "edit-item-primary"> </div> empty

**Comment by deanmarcussen** [comment]
Please update to the latest myget feed @hishamco you fixed this already (`EditUsersViewModel`)

**Comment by niknikita** [comment]
> Please update to the latest myget feed @hishamco you fixed this already (`EditUsersViewModel`)

Thanks a lot! Updated to the latest version and all earned!

**Comment by hishamco** [comment]
> @hishamco you fixed this already (EditUsersViewModel)

Yep I did

I thought he already has the latest ;)
