### ISSUE TITLE
How to render a page with culture?

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#5795]
Hi!
How to render a page with culture? for example:
localhost/en/index
localhost/en/page
...
localhost/ru/How
localhost/en/index
localhost/en/page
...
localhost/ru/

how to configure routing for a page render with the specified culture?

**Comment by hishamco** [comment]
For more details about localization & routing please follow the [this](https://github.com/OrchardCMS/OrchardCore/issues/5125)

**Comment by sebastienros** [comment]
@niknikita 

Enable the Localization feature
Then in the Localization settings, add the languages you want to support
Add the Localization part to the types you want to be localizable
In the AutoroutePart of the type, use something like `{{ ContentItem.Content.LocalizationPart.Culture }}/{{ ContentItem | display_text | slugify }}`

Then create content items and localize them. Their routes will have the culture in the prefix.
