### ISSUE TITLE
Debugging JS

### ISSUE THREAD

**Issue by ItaloFSS** [OrchardCMS/OrchardCore#5796]
Has anyone been able to get JS breakpoints to work with Chrome or Edge? It works with IE11, but not Chrome. An Orchard 1 project works fine, but I cannot get a Core project to work. I get the message "Breakpoint set but not bound". 

It also works for a plain ASP.NET Core project. 

Thanks

**Comment by Piedone** [comment]
It would be quite strange for Orchard to have any particular effect on JS debugging. What exactly are you trying to debug?

**Comment by ItaloFSS** [comment]
I don’t believe is caused by Orchard. Is something to do with JS in library projects. JS breakpoints never hit.    Thanks,Italo From: Zoltán LehóczkySent: Saturday, March 28, 2020 12:56 PMTo: OrchardCMS/OrchardCoreCc: ItaloFSS; AuthorSubject: Re: [OrchardCMS/OrchardCore] Debugging JS (#5796) It would be quite strange for Orchard to have any particular effect on JS debugging. What exactly are you trying to debug?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Piedone** [comment]
Ah OK. If you can't figure it out and need help or if you think it is indeed caused by Orchard then please re-open this issue.

**Comment by Skrypt** [comment]
I think you are confusing javascript with CSS which can't be debugged with a javascript debugger.

**Comment by Piedone** [comment]
I wanted to say the same thing but I think the CSS you see there was just added by Outlook when Italo replied to the GitHub notification via e-mail :).

**Comment by Skrypt** [comment]
Would make more sense :smile:

**Comment by ItaloFSS** [comment]
Replying by email obviously doesn't work. My reply was:

I don’t believe is caused by Orchard. It is something to do with JS in library projects. JS breakpoints never hit. Is anyone else having the same issue, I have tried multiple computers, nothing works.

![js](https://user-images.githubusercontent.com/130403/77833413-7fc29f80-7113-11ea-82ee-c12422c39b78.png)

Thanks,
Italo
