### ISSUE TITLE
Empty theme are missing on .Cms.Core.Targets

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#5800]
Using 
 PackageReference Include="OrchardCore.Application.Cms.Core.Targets" Version="1.0.0-rc1-12487" 

and found that Empty theme are missing:

![11](https://user-images.githubusercontent.com/61165619/77637609-9a074c80-6f5e-11ea-8558-7a532985987d.PNG)

**Comment by agriffard** [comment]
When you use the Blank recipe, there is no homepage created.
You can go to /admin and create your content.
