### ISSUE TITLE
Managing pages with a large number of languages

### ISSUE THREAD

**Issue by randaratceridian** [OrchardCMS/OrchardCore#5805]
We are planning to use Orchard Core to build sites that will need to manage a large number of cultures for a small number (for now) of pages.

The problem is that with Orchard Core, the process seems to be:

1. Create the page (say in English)
1. Create the pages for each language (i.e. French, German, Spanish, etc.)

But if I now go and add a new Container or Paragraph, it looks like I have to add it to each of the pages for other cultures. This makes maintenance significant.

Options we are looking at:

1. Keeping the pages in synch via code. As a widget is added, moved, deleted, etc., all related pages would also get changed.
1. Paragraph is our most important widget. Trying to re-write it to support entering multiple languages at once. So within the widget, enter the text in English, toggle it to German, enter German, etc.
1. Anything else we should consider?

**Comment by hishamco** [comment]
Could you please enable `OrchardCore.ContentLocalization` module it supposed to do what you want easily, please refer to our docs for further information

**Comment by sebastienros** [comment]
@hishamco they are already using it apparently.

@randaratceridian you are right, once the localized content item is created, new widgets won't be added. Some will see it as an advantage as it means each language can be customized. We handle synchronization of contents already at the fields level (afaik) such that a field can be configured as "culture neutral" and its value will be synched on each other language.

For your scenario, creating a custom paragraph widget would not work, as adding it would not add it to other content items. What I suggest is to use a recipe instead, that will let you apply a change to many content items. This is more involved as you need to create a json document that will contain the widget for each culture by copy pasting it.

Another option would be to create a custom part, or feature  that would be added to a type or a bag part settings,, and which could detect differences in a bag part and create the widgets automatically in all other langagues. Should not be very hard to do, and i assume it's limited to WidgetList. This way whenever one of the content items is updated, it would also load all other localization and create it again. You would need a logical identifier though to be able to match widgets by this id. But this handler would be able to add it.

Issue is that if someday you don't want one of the localization to have another paragraph, then you will be blocked. I would suggest instead to have some sort of localization version and show all the localization on the same page with each version number to see if everything is already translated.
