### ISSUE TITLE
Page title not recognized by liquid page_title when title part is rendered in template

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#5809]
As described on gitter:
The liquid page_title just renders the `SiteName` without the TitlePart when I render the `TitlePart` inside a template.
The TitlePart value is only added to the page_title segments if I do `{{Model.Content | shape_render}}` but i don't want to render the whole content else I wouldn't have made a custom template.

This is inside my **"Content__Job"** template:
`{{ Model.Content.TitlePart | shape_render }}`

This inside my **Layout.liquid** in the Theme:
`<title>{% page_title Site.SiteName, position: "after", separator: " | " %}</title>`

I've just debugged the `RenderTitleSegmentTag.cs` in a clean source code version with the agency theme.
If I add `{{Model.Content.TitlePart | shape_render}}` to the theme defined template **"Content__LandingPage"** it is still not recognized by `page_title` helper or the `PageTitleBuilder.cs` .
The segments are just the site name from the settings, the seperator and then a third segment that is null.

**Comment by jtkech** [comment]
In your template you need to call the following that adds the title segment

    {{ Model.Content.ContentsMetadata | shape_render }}

**Comment by Flarescape** [comment]
@jtkech Thank you so so much! I've tried so many things.
