### ISSUE TITLE
Workflow Timer Event creates X amount of "HALTED" workflows

### ISSUE THREAD

**Issue by mawendel** [OrchardCMS/OrchardCore#5810]
I have created a Timer Event in a workflow that is only supposed to run once a day at 00:00 using 
CRON: `0 0 * * *`
https://crontab.guru/every-night

However, at every minute when the background task runs, it creates a new HALTED workflow for this workflow type. After a couple of hours i had a lot..

So in order to test it out, I tried creating another Timer Event with
CRON: `*/5 * * * *` to make it easier to see what would happen.
https://crontab.guru/every-5-minutes

Result:
This will create a HALTED workflow every minute. Then, on the fifth event firing, it will create a new workflow as before but then execute all five at the same time.  So either i'm doing something completely wrong or the cron/event task is seriously bugged?

**Comment by sebastienros** [comment]
Can you share the log where you see these?

**Comment by mawendel** [comment]
Its now 23:58
![image](https://user-images.githubusercontent.com/5569961/77807054-e64dac00-7086-11ea-91fd-8e7287514f91.png)

Its now 23:59
![image](https://user-images.githubusercontent.com/5569961/77807100-0b421f00-7087-11ea-99de-801433cce870.png)

Its now 00:00, and despite the CRON being setup to fire every five minute and zero second, it fires somewhere at the 40 second. Probably because the background task is using the start time of the problem/app?
![image](https://user-images.githubusercontent.com/5569961/77807133-27de5700-7087-11ea-9339-07870e471e8f.png)

It has now fired off the previous 5 workflows.

**Comment by jtkech** [comment]
Not sure but i think that I already saw this

The `TimerBackgroundTask` call `TriggerEventAsync`, so **the timer event is rised every minute**, the activity itself only runs if elapsed or we get an halted WF, but here a WF instance has been created.

Can you try through the admin to set your WF as a singleton not allowing multiple instances.

**Comment by sebastienros** [comment]
So this look like there is an issue, as we don't want to save a document every minute for nothing, but at least the workflow is not really executed.

**Comment by jtkech** [comment]
> So this look like there is an issue

Yes, i think this is at the time the timer bgTask runs that we would need to evaluate if a given timer has elapsed, and then trigger the event only accordingly.

Meanwhile, good to check if it works when the WF is marked as a single instance

**Comment by mawendel** [comment]
@jtkech so using Singleton seems to mitigate the many instances. It will still create a HALTED workflow before it is supposed to actually fire, but now it will keep it at one instance.

@sebastienros actually all of the halted instances will fire off at once once the CRON match is met. Meaning that in my flow i have a Create Content task, and suddenly instead of only creating one task every five minutes, it will create five at the fifth minute.

**Comment by mawendel** [comment]
Im trying out the singleton now on my five minute cron timer. The timing looks really strange:

![image](https://user-images.githubusercontent.com/5569961/77808718-d933bb80-708c-11ea-95b3-6f813c0c32b7.png)

The new workflow then gets created later within that minute, when the background task gets executed (i assume)
![image](https://user-images.githubusercontent.com/5569961/77808773-10a26800-708d-11ea-91e8-25203e73fca8.png)

**Comment by jtkech** [comment]
It is due to the one minute granulometry of the bg task and another little think that i don't remember the details, let me find the comments i did in another issue.

**Comment by jtkech** [comment]
See [from this comment](https://github.com/OrchardCMS/OrchardCore/pull/1378#issuecomment-381358746) a discussion about the timer interval

**Comment by mawendel** [comment]
Yeah that makes sense. It would be a good idea to make a timer that functions as you would normally expect CRON to do (i was certainly confused). I remember using the Quartz scheduler a long time ago when i needed something like this.

It still leaves the issues with why it is creating a HALTED workflow before it is supposed to trigger and of course creating a HALTED workflow each minute and then executing them all at the same time. But these two are related, so fixing one should fix the other i suppose.

**Comment by jtkech** [comment]
As soon as i have time i will fix it ;)
