### ISSUE TITLE
Let's have a release! (RC2 and 1.0)

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#5814]
Since the release of RC1 .NET Core 3.0 became unsupported so we absolutely need to do a new release with 3.1. I don't think anything is necessary for this if this would be an RC2, the current dev branch can be a release and that's it. This would also greatly simplify the upcoming workshops since attendees could just grab the latest packages from NuGet (as opposed to the nightly builds on MyGet that roll out and become inaccessible in a few days).

Also, for some customers (especially larger corporate ones) the version number matters a lot. Even though Orchard is in a state that it can be used in production, as evidenced by all the apps running in production already, the simple fact that the version number in the assemblies is <1.0 they won't consider it at all (been there, tried to convince them, didn't work).

Out of the [168 open issues for 1.0](https://github.com/OrchardCMS/OrchardCore/milestone/8) IMO only a handful are actually critical, most of them are "nice to have". If we'd select the 10 or so most critical issues out of these, focused on fixing them, and called the result 1.0 I don't think it would be dishonest: With new issues added to this milestone continuously it gets longer and longer as strudel dough as we say here in Hungary but the bulk of the new issues are also just "nice to have" (out of the 168 issues only 4 are considered P1 but even P1-P3 are 13 issues altogether).

What do you think?

CC @larremp since we've talked about this too.

**Comment by infofromca** [comment]
+RC2

**Comment by deanmarcussen** [comment]
I would support an RC2.

I think there are a lot of people still using RC1 and it would provide an opportunity for them to upgrade, and us to get a bigger user base testing and using the codebase before we went for V1

I would like to see this issue resolved https://github.com/OrchardCMS/OrchardCore/issues/5712 (there is a pr nearly ready for it so should not be hard)
before cutting an RC2 though.

**Comment by agriffard** [comment]
Let's face it: It wouldn't be a good time to release a 1.0.
Also, people are waiting for a new version because RC1 is quite old.

A RC2 version would give us some more time to release 1.0 and people could test a newer stable version.

**Comment by Piedone** [comment]
Why would it be not a good time to release 1.0 Antoine? Not right now as I said, but after addressing the top issues open for it.

**Comment by hishamco** [comment]
I think it's time to release RC2, then we have time for stabilization and polish the UI if it's possible

**Comment by Piedone** [comment]
RC1 targets a dead framework, thus strictly speaking the currently latest released version of Orchard, RC1, is unusable. Thus we can't delay a release.

As for 1.0: A software is never finished. If we release a production-ready 1.0 (which as I see, the current dev almost entirely is, given there are no huge breaking changes planned) then we'll have a lot more users to tell where polishing is needed and developers to keep polishing Orchard with us for eternity :). 1.0 doesn't need to mean it's perfect (it never will be of course).

**Comment by hishamco** [comment]
> RC1 targets a dead framework

Yep, but @agriffard already update to the latest framework, so RC2 or 1.0.0 will target a LST version

**Comment by Piedone** [comment]
OK, I'm sorry, I misread your comment along the lines of "it's time to release RC2 when we had polished it", so scratch what I've written.

**Comment by hishamco** [comment]
No problem Zoltan, our goal is to make OC more stabilized, robust and secure as usual ;)

**Comment by Skrypt** [comment]
Makes sense but we are so close to 1.0. Maybe all we need is other people to step up and take issues and PR's and work on them up untill they get merged. Assign 1 person to each issue and we are done in a week or 2. But we keep pushing the dateline because there's always new things. I'd say, fix everything that is reported to be fixed on 1.0 and that is assigned to a Px label and make it RC2. But, I don't think we are ready for 1.0 if we still have 166 issues opened there : 

https://github.com/OrchardCMS/OrchardCore/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0

**Comment by Piedone** [comment]
Yeah, new things get added all the time. That's why I'm suggesting to draw the line at critical issues. Out of the issues for 1.0, as you also say, only a handful of them are actually critical. I agree to fix those for 1.0. But why for RC2? RC2 would be already much better than RC1, there still no promise to it that it should be perfect. Then we can fix the P1-3 issues for a 1.0 (and since other such issues will pop up in the meantime this will, of course, take longer than expected; but we desperately need an RC2). And then we can take all the time to fix all the lower priority bugs and implement all the great other features in 1.0.1 and 1.1, and 1.2, and so on.

**Comment by lazcool** [comment]
A 1.0 release would be really helpful for those places that don't allow pre-production software into prod 😉.

**Comment by fMichaleczek** [comment]
+RC2

**Comment by sebastienros** [comment]
An RC2 would not impact the 1.0 schedule. I asked the same question a few weeks ago during a meeting but there was no clear voice for it. I assume it's ok to decide otherwise as 1.0 is progressing too slowly.

**Comment by carlwoodhouse** [comment]
+1 for an RC2 mostly due to the fact RC1 targets EOL dotnet 3.0.

We use RC1 in prod because we cant keep updating to the dev packages for every prod build (as old builds expire off myget) and we can't retest every single dev release. but RC1 is very out of date now :)

**Comment by sebastienros** [comment]
Closing as it has been approved. It also has a custom mileston.
