### ISSUE TITLE
Registered styles are not rendered in Head section  when using OrchardCore TagHelpers

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#5819]
I am using the  Orchard Tag helper to render a content item by its slug as follows 
```
<contentitem alias="slug:my-contentitemId" />  
```
The content item beeing rendered  has a custom part and its .cshtml file has the following style tag to render some custom styles in the head 
```
  <style asp-name="trumbowyg"  ></style> 
```

But this style does not render when  content is called from the tag helper.

If I call as a content item as a full page request it works as expected.

The same applied if i use the  orchard  ```<menu/>``` tag helper.

Is this intended or can there any way to make it work ?

I found this pr #5436 which kind of solved a similar issue.
@ns8482e

**Comment by sebastienros** [comment]
Where are you inserting this `<contentitem alias="slug:my-contentitemId" />` ? Which template, and where in the template?

**Comment by giannik** [comment]
Here is a bit more context : 

1.In the themes Layout.cshtml I have the following 

```
  @await DisplayAsync(await New.DirectMessagesSideBar())  
```

2. In DirectMessagesSideBar.cshtml there is the tag helper : 
```
  <contentitem alias="slug:my-contentitemid" display-type="Detail" />  
```
3. for the content type beeing rendered by the tag helper there is a custom part who's display driver (MyCustomPart.cshtml)  has : 
```
<style asp-name="trumbowyg"  at="Head" ></style>   
``` 

When the whole page is rendred the style is not picked up as shown below (no styles folder appears)


![qqq](https://user-images.githubusercontent.com/1516981/78388703-1d254400-75ea-11ea-9ddb-a6727b21bd80.jpg)


4. If I move the tag helper from DirectMessagesSideBar.cshtml to Content-Page.cshtml (which is an alternate for the content shape for page content type in the theme)

Content-Page.cshtml
```
<contentitem alias="slug:currentuser-messagerooms" display-type="Detail" /> 
```
then the style tag IS rendered as shown below :
 
![qqq9999](https://user-images.githubusercontent.com/1516981/78389301-2ebb1b80-75eb-11ea-9047-06dfd6a6347d.jpg)

So it looks like the issue occurs at a level deeper in the shapes hierarchy of the main content shape.

Hope this helps.

**Comment by giannik** [comment]
Oh , I tested by adding the script tag in the part view : 
```
 <style asp-name="trumbowyg"  at="Head" ></style>      
 <script asp-name="trumbowyg"  at="Foot" ></script>
```
and noticed that script tag DID render properly.

So it looks like the issue is only with the style tag.

**Comment by deanmarcussen** [comment]
Because you are rendering this `DirectMessagesSideBar` directly in your layout file, you need to render it (call DisplayAsync) before the `<resources type="Stylesheet" />` tag helper is called, or it will not know about the new stylesheet you have requested with `At="Head"`

You could do this in your layout instead and it should work

Before `<resources type="Stylesheet" />`
```
@{
    var sidebar = await DisplayAsync(await New.DirectMessagesSideBar()) ;
}
```

Where you want to render the sidebar in your layout
```
@sidebar
```

**Comment by giannik** [comment]
@deanmarcussen Yes dean that did it !!! 
Thank you. 
Always learning something new.

**Comment by ns8482e** [comment]
@giannik to avoid writing pre render code in layout I would suggest to always use render section in layout and use `zone` tag helper to render shape to target specific zone

**Comment by ns8482e** [comment]
See https://github.com/OrchardCMS/OrchardCore/issues/3963#issuecomment-580754019

**Comment by giannik** [comment]
@neman That would be a more elegant solution.
I tried it but does'nt work for my case.
It does work if i place the zone tag helper in the content.cshtml file.
But when placing the  zone tag helper in DirectMessagesSideBar.cshtml it does'nt get picked up for the reasons @deanmarcussen mentinoed.
