### ISSUE TITLE
Suggestion for a new API for the Session.Delete to accept IDs

### ISSUE THREAD

**Issue by domonkosgabor** [OrchardCMS/OrchardCore#5821]
There is an issue in the YesSql repository sebastienros/yessql/issues/103 about using a different API for the delete scenario when we would like to delete a bunch of content items:

> await _session.DeleteAsync<OpenIdAuthorization, OpenIdAuthorizationIndex>(
>     authorization => authorization.Status != OpenIddictConstants.Statuses.Valid ||
>    (authorization.Type == OpenIddictConstants.AuthorizationTypes.AdHoc &&
>     authorization.AuthorizationId.IsNotIn<OpenIdTokenIndex>(
>         token => token.AuthorizationId,
>         token => token.Status == OpenIddictConstants.Statuses.Valid)));

This way we don't have to get the list of the content items and then call the `_session.Delete()` multiple times. If we would like to delete 1000 content items, there will be 1000 `_session.Delete()` requests against the SQL server, that means multiple `delete from table where Id = @Id;"` commands.

However, to be able to use the `_session.Delete()` command, we need to pass objects, but there are different scenarios where I know that I don't have any index table and I really just want to delete the items with these IDs. Maybe there could be a new override for the `_session.Delete()` method to accept a list of IDs.

The [IndexingTaskManager](https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore.Modules/OrchardCore.Indexing/IndexingTaskManager.cs#L139) in Orchard Core does quite a similar thing. It executes the delete command in bunches. I wondered to use the same scenario too. But of course, it will not delete the corresponding index table(s). OK, nevermind, delete them. But for that, I have to write another logic to retrieve the name of the tables that holds the index data for my content item. I tried that and as far as I know, there is no way to get the `MapIndex` or `ReduceIndex` instances based on a content item or an entity.

**Comment by sebastienros** [comment]
I think I can fix it in yessql by optimizing the batching of delete commands. I can also add a delete that takes many ids, but internally it will still call Delete(id) for each of them. Because the indexes have to be processed too.

The indexing taks manager doesn't use documents, just raw tables and dapper, which is why it's doing its own queries. 

It shouldn't be long to fix...

**Comment by sebastienros** [comment]
Good progress so far: https://github.com/sebastienros/yessql/pull/228

Handles batching creation and deletion of documents, and deletion of map indexes.
Should be a little bit more involved for creation of Map ad Reduce indexes but I will try.

And it's all transparent, no breaking API.

**Comment by Piedone** [comment]
Awesome! The lack of single-query updated and deletes is the one reason why sometimes we need to add batching logic (and was the same with Orchard 1).

**Comment by Piedone** [comment]
Now that batching is done, after updated YesSql does this mean that such serial deletes should work better? However, looking at what happens with these commands (https://github.com/sebastienros/yessql/blob/da785fdebc7d2d9cf14400e2fabc1d13bbd41265/src/YesSql.Core/Session.cs#L672) I'm not sure I see the efficiency gain since these queries will still be executed one by one.

**Comment by jtkech** [comment]
@Piedone 

Yes it executes all commands but all or part of them may have been batched through `  BatchCommands()`, see https://github.com/sebastienros/yessql/blob/47702652f14931e18dd13f4480d71f5ef5eadd10/src/YesSql.Core/Session.cs#L724

**Comment by Piedone** [comment]
Great then!

**Comment by jtkech** [comment]
So, can we close this one @Piedone ?

**Comment by Piedone** [comment]
I think so, since with batching done in YesSql and it being updated here nothing else is necessary.
