### ISSUE TITLE
Lucene: lucene.settings.json configuration is not stored in SQL database

### ISSUE THREAD

**Issue by vkoman** [OrchardCMS/OrchardCore#5822]
Having SQL database configuration, the "lucene.settings.json" file is still stored in the App_Data folder for each tenant.

It causes an issue, that all our indexes disappear from the indexes list. To re-index our data - we need to add a new Index, to make our old indexes visible, and then "Rebuild" them.

Are there some specific steps for migrating Lucene Indexes to SQL DB?

**Comment by Skrypt** [comment]
If you are using the latest dev they are stored in the database. But using `git clean -xdf` for example will empty the /App_Data/tenant/lucene/ folders where all the indices are stored. We need to make sure to recreate those folders else we end up with a NRE. To migrate lucene.settings.json file to database there is no migration path as it should never been used that way.

**Comment by vkoman** [comment]
Is this functionality included in 1.0.0-rc1-12542 build?

**Comment by vkoman** [comment]
I have updated to the latest version (1.0.0-rc1-12542).
Manually deleted the App_Data folder, re-created a clean database, have set up default site from scratch.

Launched application on localhost - index successfully created, data also has been indexed.
folder "App_Data\Sites\tenant\Lucene\IndexName" exists
file "lucene.status.json" in "App_Data\Sites\tenant" also exists

When I stop localhost, run it again, and after a couple of times re-launching my localhost, unfortunately, my indexes still disappear from Indexes list and newly created data are not indexed.

**Comment by vkoman** [comment]
To see the list of my indexes - I still need manually "Add new Index", then reset my old indexes

**Comment by sebastienros** [comment]
Implemented in dev
