### ISSUE TITLE
Loading from an contenttype?

### ISSUE THREAD

**Issue by jaliao** [OrchardCMS/OrchardCore#5826]
Hi,

I need to load the data from a content type named "Home Carousel" on the homepage.

I know we can load the data from an alias
<https://docs.orchardcore.net/en/dev/docs/reference/modules/Contents/>

so do we have the way like this? 

{% assign my_contents = Content["contenttype:HomeCarousel"] %}

or another way? thanks!

Best regards,
Justin

**Comment by TFleury** [comment]
Hi,

You should take a look at [Queries](https://docs.orchardcore.net/en/dev/docs/reference/modules/Queries)

**Comment by jaliao** [comment]
thank you. let me check.
