### ISSUE TITLE
Orchard Core Workflow - Http Redirect

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#5831]
Hi All,

I want to redirect the one specific url to another url through workflow ( ex: /register to /register-test)

How to do that via orchard core workflow. Please do the needful

**Comment by devlife** [comment]
Looking at the docs [here ](https://orchardcore.readthedocs.io/en/latest/docs/reference/modules/Workflows/#activity) it looks like you can create an http request activity and filter to the url that you want and then use http redirect activity.

![image](https://user-images.githubusercontent.com/237369/78198616-1a461a00-7457-11ea-862a-b8d7fb9934ba.png)

**Comment by lengockyquang** [comment]
what should i do if i want to open new tab with url that config workflow redirect task
