### ISSUE TITLE
Enable Content Culture Picker Error

### ISSUE THREAD

**Issue by siaochuenchong** [OrchardCMS/OrchardCore#5833]
Hi, when I enable content culture picker, it throws an error. 
This is the issue. May I know how to solve this?
I just download it 2 days ago for exercise purposes. I have done some widget and recipe.
![image](https://user-images.githubusercontent.com/57893076/78205518-e1e22280-74ce-11ea-8287-eb7d0cd07b54.png)
@hishamco

**Comment by deanmarcussen** [comment]
Can you check you have the Autoroute feature enabled

**Comment by hishamco** [comment]
Please check if autoroute is enabled as Dean mentioned earlier

**Comment by hishamco** [comment]
BTW @deanmarcussen how the CCP is added without enabling the Autoroute feature I though there's a dependency to avoid such issue

**Comment by siaochuenchong** [comment]
Hi guys! Thanks for your help! 
Enable Autoroute did solve the problem! :D

**Comment by hishamco** [comment]
I reopen this because there's a PR to resolve the issue automatically without the need of enabling `Autoroure` manually
