### ISSUE TITLE
Media library can't show new created folders on centos7

### ISSUE THREAD

**Issue by staymo** [OrchardCMS/OrchardCore#5834]
Hello:
I found an issue that when working on windows, everything is OK with the media library. But when I have deployed it to a centos7 server, when I create a new folder in media library, this new folder will just disappear after I refresh the page. However, the directory is in fact created in the system, and cause an error like "can't create a folder because one with the same name already exists" when I try to create it again.  
If I remember clearly, it works for the first time, then failed after that.
My OrchardCore references info:
`  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.8" />
    <PackageReference Include="OrchardCore.Application.Cms.Core.Targets" Version="1.0.0-rc1-12530" />
    <PackageReference Include="OrchardCore.Logging.NLog" Version="1.0.0-rc1-12542" />
  </ItemGroup>`

Thank you for your attension! Looking forwards to any response, Regards.

**Comment by staymo** [comment]
Some additonal infomation:
When I found the problem, I was using Chrome and Firefox. And I just tried edge(not the Chromium core one), found that although it's very slow when operating the medias comparing to Chrome, it's working fine basically. And BTW, it's much fasting in the selecting culture page than chrome and firefox though, those two just like freeze there for 10 seconds. That's another issue of course.
One more thing, when I met the problem using chrome or firefox, I didn't see any js errors.
And another difference between my local Windows environment and the testing Centos7 server is that the later is not enabled SSL. I don't know if it's relevant.
Thanks.

**Comment by deanmarcussen** [comment]
This is likely permissions related

Can you do `ls -a` and report back with a list of the permissions that have been granted to a working folder and a folder that is not working (to create a working folder, please try creating it manually on the server)

**Comment by staymo** [comment]
No, there are no difference:

root@23a9eca6f3fa:/app/App_Data/Sites/Default/Media/News# ls -al
total 28
drwxr-xr-x  7 root root 4096 Apr  2 07:30 .
drwxr-xr-x  5 root root 4096 Apr  2 03:42 ..
drwxr-xr-x  2 root root 4096 Apr  2 07:30 2019
drwxr-xr-x  3 root root 4096 Apr  2 04:52 2020
drwxr-xr-x 17 root root 4096 Apr  2 02:31 old
drwxr-xr-x  3 root root 4096 Apr  2 04:21 old2
drwxr-xr-x  2 root root 4096 Apr  2 07:28 test

Among the sub directories under News, only "old" is the original one copied from Windows; and the "2019", "2020" and "old2" are created in Media Library by browser; the last one "test" is manually created by mkdir.  
The interesting thing is, like I described before, it's like "browser specific" problem, for I can see the manually created "test" in Media Library if I am using Edge, by contrast, I can only see "old" if I am using Chrome.

**Comment by deanmarcussen** [comment]
Did you say that your deployed centos site is not using ssl?

If so can you try with version `1.0.0-rc1-12577`. 

We updated something related to the Chrome SameSite changes recently, specifically around http only traffic.

Since you say it is browser specific can you also check both your chrome network tab and console for errors

**Comment by staymo** [comment]
New found:
It's should be related to the browser cache. I just clean up the cache data (Ctrl+Shift+Del in Chrome), and even the "test" shown.
But I can't achieve the same by even Ctrl+F5. Any setting I can do to avoid this? It's not a good user experience to clear browser cache every time I upload some pictures...

**Comment by staymo** [comment]
OK, I will try 12577. Thanks!

**Comment by staymo** [comment]
I updated to 12577, and sadly, the browser (chrome) acts as the same. I still need to Ctrl+Shift+Del to make a newly created folder show again after page refreshed.

**Comment by deanmarcussen** [comment]
You will need to see if it is chrome choosing to cache or your server settings (presumably nginx).

I suspect your server configuration.

Look in the network tab at the ajax requests for `GetFolders` and see what cache headers are getting set on the response.

**Comment by staymo** [comment]
Yeah, I am using nginx. I feel that you are right this time... thanks for your suggestion, I will check it.

**Comment by staymo** [comment]
Yes, It's because I have an "add_header X-Cache..." statement in my nginx config file. Now I know how I can handle this, thanks!
