### ISSUE TITLE
Multilingual Button

### ISSUE THREAD

**Issue by siaochuenchong** [OrchardCMS/OrchardCore#5846]
Hi guys, 

I enable the content culture picker and localization button, but I couldn't find a way to make the multilingual button appear in the homepage. 

I just add the localization and autoroute in the content part. Do you guys have documentation on how to do this? If yes, please share with me :) Thanks alot!

**Comment by hishamco** [comment]
There's a `ContentCulturePicker` that you can use in the front-end

**Comment by hishamco** [comment]
Fore more information have a look to our docs https://docs.orchardcore.net/en/dev/docs/reference/modules/ContentLocalization/
