### ISSUE TITLE
Microsoft AAD is not working

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#5849]
Hi,

Enabled and configured the below settings in orchard admin. 

![image](https://user-images.githubusercontent.com/39621436/78362596-02e26a80-75d8-11ea-9e3c-d2b376033b03.png)

But when i login through Orchard Core AAD App, it authenticates and redirected to login page again instead of navigating to admin page.

kindly do the needful. Do i need to need to any other settings ?

**Comment by MichaelPetrinolis** [comment]
please check https://docs.orchardcore.net/en/dev/docs/reference/modules/Microsoft.Authentication/ and review the callbackpath you use.

**Comment by RajasekarPR** [comment]
Thanks @MichaelPetrinolis got it and it works perfectly :)
