### ISSUE TITLE
Bug? Page_title not work when bag present

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5851]
This line in my layout.liquid does not work when I have a bag in my page:
 <title>{% page_title Site.SiteName %}</title>
Site.sitename works but not page_title

I thinkits because I am using Title Part in my bag items?
That might be the bug?

**Comment by JoshTango** [comment]
Ok I can reproduce this bug and I found the error.  I will explain it soon.

**Comment by remesq** [comment]
For posterity, if you are using a Template, add this to fix the problem:
`{{ Model.Content.ContentsMetadata | shape_render }}`
I found this here: https://github.com/OrchardCMS/OrchardCore/issues/5809#issuecomment-605312371
