### ISSUE TITLE
Update module manifest url and maybe version?

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5857]
As @hishamco pointed out on https://github.com/OrchardCMS/OrchardCore/pull/5815

the manifests for the modules are all set to v2.0.0, and the website also could be updated to `https://orchardcore.net`
```
    Website = "https://orchardproject.net",
    Version = "2.0.0"
```

What version number do we want to release with?

**Comment by jtkech** [comment]
Hmm, maybe we put 2.0.0 just because when we started OrchardCore it was named Orchard2

In Orchard1  we have 2 versions

    Version: 1.10.2
    OrchardVersion: 1.9

In OrchardCore, because of nuget packages i think we only need one Version, the one that is published on Nuget, and that would be the same for all modules.

So here, i would put `Version = "1.0.0"` that would need to be changed on each new release on Nuget, so i suggest to use a shared const Version string that would be used in each manifest, something like

    Version = OrchardCoreVersion

**Comment by hishamco** [comment]
> Hmm, maybe we put 2.0.0 just because when we started OrchardCore it was named Orchard2

Is this Orchard version or Module version?!!

**Comment by Skrypt** [comment]
If I follow @jtkech that would mean that : 

Version = Orchard Core version
OrchardVersion = module version

Maybe for OC we should rename these to :

OrchardVersion = Orchard Core version
ModuleVersion = module version

**Comment by sebastienros** [comment]
I think we should keep the current names, Version for the module, and OrchardVersion for the minimal required OC version.
We could potentially remove Version as we have a Nuget version now, but it might still be useful if we want to create a modules directory, so we can parse the file when the directory references a GH repository.

**Comment by sebastienros** [comment]
So I assume an action would be to update all the URLs. 
We can also reset all the manifest versions to 1.0 for both the Version and OrchardVersion.

**Comment by sebastienros** [comment]
Or RC2 as this is the next release.

**Comment by hishamco** [comment]
> So I assume an action would be to update all the URLs.
We can also reset all the manifest versions to 1.0 for both the Version and OrchardVersion.

I can update them, but if what if we have a beta or rc release shall we include them in the version `1.0.0-RC2`?

**Comment by Skrypt** [comment]
It's been assigned to RC2 milestone.
