### ISSUE TITLE
Redirect URI for Azure AD external login does not respect baseurl

### ISSUE THREAD

**Issue by CBrams** [OrchardCMS/OrchardCore#5860]
Hi there

I'm setting up a test system, and would like to use Azure AD authentication, so I enabled this in the feature menu (running the dev branch).

The configuration is straightforward, but does not appear to mention that this runs the implicit flow (why? This should easily be able to be configured as a another flow, like an auth-token), but that does not matter.

What matters is that Azure AD applications require a https redirection uri, (or localhost) when configuring them, but despite setting the baseurl to https in site settings, the server keeps sending a redirection uri with the http uri for the server - invalidating the configured login.

Hope you can help clear up where I can control the scheme for the redirection uri.

Best, Christian

**Comment by CBrams** [comment]
It seems that it still thinks (despite the base url being set to a https scheme), that it should autodirect me to an unsecure version at first login. If I access the login page from a fresh browser using the https protocol, it will redirect me to the http protocol. If I then add the s again to the http protocol, it is secure, but I still cannot get it to think that I am using a secure connection.

**Comment by CBrams** [comment]
I think it might be because the load balancer I put in front of it only communicates with the orchard server on port 80. I'll look into it, and close it if it fixed like that.

**Comment by devlife** [comment]
FWIW I was able to use https without any issues on one of my projects.

**Comment by CBrams** [comment]
We were just trying out the build on the docker hub, but it seems like that only exposes port 80 of the container, and thus will not work. If I understand the code correctly (and there is a high likelyhood that I don't), it seems as if the code looks at the request scheme when it decides how to generate the redirect_uri for the login, so as long as I am connecting on port 80, it will generate a http scheme?

**Comment by deanmarcussen** [comment]
Try enabling the Reverse Proxy Feature it should take care of the forwarded headers from your load balancer

**Comment by CBrams** [comment]
Thanks @deanmarcussen , that seemed to work :).. 

It gives me an error 500 still when using OpenId configured login to use Auth Code, and just boots me to the login page if using the built in azure ad authentication -- but at least now it recognizes that it is https
