### ISSUE TITLE
Culture vuejs select is slow

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5864]
The vuejs Culture Select is slow to select new cultures.

To select an item from the cultures list when localization is enabled takes around 25 seconds for the add method to complete, and the culture to become selectable.

I haven't had time for a good look, but I can see from the code we have fallen into a `v-for` and `v-if` trap. https://vuejs.org/v2/guide/list.html#v-for-with-v-if

However I suspect it's the add method that is running slowly.

Must be a regression as it wasn't running this slowly last time I used it.

**Comment by deanmarcussen** [comment]
Tested this

It slows down (a lot!) on the font awesome pseudo elements commit https://github.com/OrchardCMS/OrchardCore/pull/5813

**Comment by hishamco** [comment]
I saw similar behavior with 3 cultures in slow internet .. let me check if I can improve this ...

**Comment by agriffard** [comment]
https://stackoverflow.com/questions/50976897/fontawesome-5-svg-icons-data-search-pseudo-elements-causes-100x-slowdown-in-ren

**Comment by agriffard** [comment]
> Although you can use pseudo-elements with SVG and JS we do not recommend using this method. It does not provide as many usage options, is difficult to configure, and is the slowest method of using Font Awesome. (Painfully slow in some cases.)
https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements

We will need to get rid of it.

**Comment by dodyg** [comment]
Is this why the Admin section on the latest build unusable?

**Comment by deanmarcussen** [comment]
Yes @dodyg
