### ISSUE TITLE
Code mirror for Html Field Editor

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5865]
We changed the default editor for the `HtmlBodyPart` to use Code Mirror recently, but didn't do the same for the `HtmlFieldEditor`.

There we have editor options of 
- Standard
- Multiline
- Trumbowyg
- Wysiwyg

I'd quite like a CodeMirror editor for the html field. 

Do we want another editor option for it, or could we replace the `Multiline` editor with CodeMirror?

/cc @agriffard

**Comment by agriffard** [comment]
It is done in the Standard HtmlField.Edit.cshtml.

Try it with some html to see the highlighting.

**Comment by deanmarcussen** [comment]
Nice one thanks @agriffard Just didn't notice it until I got some html in it.
