### ISSUE TITLE
Question: author view permission?

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5866]
How do I set it so only an author can see their content if they are signed in?

**Comment by hishamco** [comment]
Please check the users and permissions from Admin site

**Comment by JoshTango** [comment]
yes and i am confused by what I see

**Comment by JoshTango** [comment]
nvm i will experiment
it looks like its a global roles permissions setup

**Comment by hishamco** [comment]
Each module can provides its own permission, please have a look to the source of any module, you will find a `Permissions` class, try to have a look for how permissions are implemented

**Comment by sebastienros** [comment]
Only check the "View Own Content" permission, and not "View Content"

**Comment by sebastienros** [comment]
Please reopen if that doesn't work.
