### ISSUE TITLE
Feature Request: Overrides for themes

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5867]
In Drupal if I choose a theme there are text boxes below the enable button to override certain values.
For example: If I choose the Agency theme I do not want the default theme color of yellow.  I want red instead.  In Drupal there is a text box called primary theme color and you can enter the hex value for red.

In other words themes need the ability to expose certain properties which will show up on the Admin UI. @sebastienros

**Comment by hishamco** [comment]
Till now we don't support changing color scheme from the admin site UI, the only way you can do it now from within sass files

I could try this as DEMO but there's no promise it will be shipped as a built-in feature in OC

**Comment by JoshTango** [comment]
it doesnt have to be for first version

**Comment by vitalybrandes** [comment]
> Till now we don't support changing color scheme from the admin site UI, the only way you can do it now from within sass files
> 
> I could try this as DEMO but there's no promise it will be shipped as a built-in feature in OC

> Till now we don't support changing color scheme from the admin site UI, the only way you can do it now from within sass files
> 
> I could try this as DEMO but there's no promise it will be shipped as a built-in feature in OC

Idea - just add place with "customer.css" file that can override main one.
Something similar is in the gantry framework.
http://gantry.org/

**Comment by hishamco** [comment]
Thanks @vitalybrandes, I will have a look, but what @JoshTango suggested is to provide such a textboxes or color picker to change the colors that are used by each theme

I think this could be doable if there's a standard for theming in OC

**Comment by vitalybrandes** [comment]
> Thanks @vitalybrandes, I will have a look, but what @JoshTango suggested is to provide such a textboxes or color picker to change the colors that are used by each theme
> 
> I think this could be doable if there's a standard for theming in OC

Check the gantry, it's cool ,
Regarding the colors,
OC more for developers, and adopt css on run sound like more right. Just for.me

**Comment by JoshTango** [comment]
In Drupal its not just for colors.
The other main text box is to change the path of the logo.png file.

**Comment by hishamco** [comment]
Ya, but in the first thread you was focused on colors & themes

**Comment by JoshTango** [comment]
i am focused on themes.
In Drupal they allow you to over ride ANYTHING in the theme.
The 2 most popular are colors and logo path.
Maybe the logo path is part of a background image for a css style?

**Comment by JoshTango** [comment]
Lets use Agency theme and go with the custom.css idea.
If the custom.css contain a class for logo with the background set to a path for logo.png and a class for primary color and a class for secondary color.
Then the Admin UI could scan this custom.css file and show a textbox for each value in the custom.css.
If it sensed a color then it could show a color picker instead of a textbox.

**Comment by sebastienros** [comment]
It's already doable. A theme is like any module, it can expose custom settings. If a css had to be dynamic. We just decided not to do it in the default themes as it has some performance penalty, and it would have made it more complex.

**Comment by JoshTango** [comment]
Well some guidance would be nice on how to do it if it is already doable.
I have another issue open for a News Theme and I would like to have some custom settings for that one
