### ISSUE TITLE
Feature Request? Content specific assets

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5869]
I'm not sure if this exists.
I want the ability to upload assets such as images or movie clips or whatever that are specific to a content item.
I think possibly this would be referred to as an AssetsPart.
Then in the html of the content item you can reference these assets.

**Comment by agriffard** [comment]
`MediaField` is what you are looking for.

**Comment by JoshTango** [comment]
I'm not sure about media field as that is defined in the content definition template.
I mean what if you wanted to add a image aas part of your html on the fly?
How is that image stored? @agriffard

**Comment by agriffard** [comment]
There is an image button in the Wysiwyg editor tollbar that opens a modal that is the equivalent of the media library with the ability to select an image to include in the Html.

**Comment by JoshTango** [comment]
yes but where does that image then get stored? @agriffard
