### ISSUE TITLE
Issue with showing image from module

### ISSUE THREAD

**Issue by dewebeloper** [OrchardCMS/OrchardCore#5874]
In this very simple example, there is issue with showing image if image is in wwwroot of module. It looks like that doesn't work at all.

![OrchardCore2](https://user-images.githubusercontent.com/3725912/78636667-10824380-78a9-11ea-83b6-2628f07fb8c5.PNG)

**Comment by dodyg** [comment]
Try this https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/orchard-core/static-files
