### ISSUE TITLE
Query Content Item 

### ISSUE THREAD

**Issue by jaliao** [OrchardCMS/OrchardCore#5879]
Hi,

I have same issues need to confirm.

I use SQL query at admin
```sql
SELECT * FROM ContentItemIndex where ContentType = 'HomeCarousel'
```
and return three records as bellow

```json
{"Id":451,"DocumentId":100,"ContentItemId":"4r97x7tpjhb46s7kd9176ezedv","ContentItemVersionId":"44259ftx0h2je2bfrms5yzehdt","Latest":0,"Published":0,"ContentType":"HomeCarousel","ModifiedUtc":"2020-03-31 07:21:52.0809306","PublishedUtc":"2020-03-31 07:21:52.0857645","CreatedUtc":"2020-03-31 07:21:52.0809306","Owner":"admin","Author":"admin","DisplayText":"Live Music Nights \u003cbr\u003e@The Central Boulevard"}
{"Id":452,"DocumentId":101,"ContentItemId":"4r97x7tpjhb46s7kd9176ezedv","ContentItemVersionId":"4c1cq08te7262svwsnbg9w924a","Latest":1,"Published":1,"ContentType":"HomeCarousel","ModifiedUtc":"2020-03-31 07:21:59.6344893","PublishedUtc":"2020-03-31 07:21:59.650207","CreatedUtc":"2020-03-31 07:21:52.0809306","Owner":"admin","Author":"admin","DisplayText":"Live Music Nights \u003cbr\u003e@The Central Boulevard"}
{"Id":475,"DocumentId":107,"ContentItemId":"4zybdbnt1yyyyyrpyak34ddbm5","ContentItemVersionId":"4ehr2s9n52gt12hsg7tfac7fnr","Latest":1,"Published":1,"ContentType":"HomeCarousel","ModifiedUtc":"2020-04-07 15:12:14.1931484","PublishedUtc":"2020-04-07 15:12:14.1979616","CreatedUtc":"2020-04-07 15:12:14.1931484","Owner":"admin","Author":"admin","DisplayText":"test"}
```
save it named "QueryHomeCarousel"

and i back to liquid page at front-end page coding

``` liquid
	{% assign recentBlogPosts = Queries.QueryHomeCarousel | query %}
	{% if recentBlogPosts == nil%}
	null
	{% endif %}
	<ul>
	{% for item in recentBlogPosts %}
	<li>{{ item | display_text }} - {{ item.Content }}</li>
	{% endfor %}
	</ul>
```

and it return null.

why?
anyone can help me?
thanks

best regards,
Justin

**Comment by uussoft** [comment]
你查詢的是ContentItemIndex表，此表中不存在字段Content，另外，display_text過濾器只可以在内容項中使用，此處應該使用 item.DisplayText

**Comment by dodyg** [comment]
![how-to](https://user-images.githubusercontent.com/1761249/78768410-2c124a80-798c-11ea-842a-86bc3e655ad2.png)

**Comment by jaliao** [comment]
@dodyg  thanks for your response. you help me a lot. thanks.

it works. but one more question.

how to get localization contents with SQL? 
or can you help me to finger out document URL?

**Comment by jaliao** [comment]
Another question

I am interested on you SQL command
I try to Query  this table ContentPickerFieldIndex.
but...

![ContentPickerFieldIndex](https://user-images.githubusercontent.com/12048035/78807156-42ed8700-79f6-11ea-9110-6385b697ab8e.PNG)

what happen?

many thanks
Justin

**Comment by dodyg** [comment]
You can find my notes here https://github.com/OrchardCMS/OrchardCore/issues/4121#issuecomment-550126247

**Comment by jaliao** [comment]
thanks, let me try and study.
