### ISSUE TITLE
dotnet-ubuntu.16.10-x64.1.0.0.tar.gz can't downloaded

### ISSUE THREAD

**Issue by EagleSmith** [OrchardCMS/OrchardCore#588]
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0/dotnet-ubuntu.16.10-x64.1.0.0.tar.gz
dotnet_install: Error: Download failed

**Comment by Skrypt** [comment]
If you are trying to install by following the Wiki post I'm not 100% sure this will work since I wrote it when we we're on pre-releases of .NET Core.
