### ISSUE TITLE
添加一个ContentType内容时，选择Taxonomy，存储到数据库时，同时保存Taxonomy的alias

### ISSUE THREAD

**Issue by fuxiaojun0203** [OrchardCMS/OrchardCore#5881]
我在添加文章的时候选择了Taxonomy，现在是在数据库存储文章数据的时候，只存了TermContentItemIds，如何保存这个文章数据的时候，保存Taxonomy的Alias

**Comment by deanmarcussen** [comment]
I will assume this is duplicate of https://github.com/OrchardCMS/OrchardCore/issues/5882 and close this one
