### ISSUE TITLE
Adding Custom Cshtml files

### ISSUE THREAD

**Issue by adelemam** [OrchardCMS/OrchardCore#5886]
I am getting crazy with this, when Adding Cshtml files in Pages folder at the source code it works fine, 
But if I used the nuget to make My Main Project uses "OrchardCore.Application.Cms.Targets" 
if i tried to add Pages folder and cshtml files inside it , It doesn't work ,

If I tried to make a module and add those pages it work if the Hosting is MVC app not CMS , 
so any one have a clue how i can add my custom Pages in either case?

**Comment by deanmarcussen** [comment]
Is it possible you have called `.AddRazorPages()` in your `Startup.cs` or something similar?

There is a very good guide to creating a decoupled cms here https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/

**Comment by adelemam** [comment]
i went  through this guidline and it work like sharm when building the github code, but i want to work with empty project and support it with Targets nugets.

I tried adding AddRazorPages and it works but the core CMS and the public site are not working , 
here are my codre: ` public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
          
             app.UseStaticFiles();
            app.UseOrchardCore();
        }
    }`.

**Comment by adelemam** [comment]
when i called . AddRazorPages() , the page already displayed, but public and admin pages gave error "InvalidOperationException: The view 'Display' was not found. The following locations were searched:
/Areas/OrchardCore.Contents/Views/Item/Display.cshtml
/Areas/OrchardCore.Contents/Views/Shared/Display.cshtml
/Views/Shared/Display.cshtml
/Pages/Shared/Display.cshtml"

**Comment by sebastienros** [comment]
Can you share a simple module you are trying to create on GH so we can see what is wrong with it?

**Comment by ns8482e** [comment]
You do not need to call  `. AddRazorPages() ` 

All Pages/Views  are placed under "/Areas/" so default route will be "/[ModuleName]/Pages" and Your web application is a super module

If you are not using `@page "/url-to-page"` for route mapping, then you can change default route for all pages using conversions as below

```
services.Configure<RazorPagesOptions>(options =>
{
 // This declaration would define an home page
 //options.Conventions.AddAreaPageRoute("OrchardCore.Demo", "/Hello", "");
 });
```
