### ISSUE TITLE
Development of Custom Input Forms

### ISSUE THREAD

**Issue by saif859** [OrchardCMS/OrchardCore#5889]
Dear Team,

I'm very new to OrchardCore and want some help from you guys. I want create a custom input form on website and show the user data to admin or some other role. I have implemented your feedback example given in docs but that doesn't meet my criteria because all feedbacks go to configured email. Please help me.

**Comment by hishamco** [comment]
Basically you can use the Forms module with conjunction with Workflow module to do most if not all what you want

**Comment by saif859** [comment]
> Basically you can use the Forms module with conjunction with Workflow module to do most if not all what you want

Dear hishamco, can you provide any example?

**Comment by agriffard** [comment]
https://docs.orchardcore.net/en/dev/docs/reference/modules/Forms/

**Comment by saif859** [comment]
> https://docs.orchardcore.net/en/dev/docs/reference/modules/Forms/

I implemented this example already. I want to submit data into database and show to admin while in this example data emailed to admin.

**Comment by agriffard** [comment]
Ok: You will have to replace the 'Send email' activity by a 'Create Content' activity.

Use the properties of the form to create a json content.

**Comment by hishamco** [comment]
@saif859 please refer to @agriffard comment

**Comment by gaurav151299** [comment]
dear @agriffard, we have replace the 'Send email' activity by a 'Create Content' activity. but in create content activity, we have not found resources to submit the record of form in database. i have attached the screens, kinldy suggest if any activity is missing or any other activity is required.

**Step1. Forms**
![image](https://user-images.githubusercontent.com/63450365/78982830-d9de4000-7ad7-11ea-9624-afdceb5451dd.png)

**step2. Workflow**
![image](https://user-images.githubusercontent.com/63450365/78982948-0befa200-7ad8-11ea-9905-66df721fdca9.png)

**Step3. create content**
![image](https://user-images.githubusercontent.com/63450365/78983002-2b86ca80-7ad8-11ea-977c-261975eb4a40.png)

**Comment by agriffard** [comment]
You can retrieve the Properties of the Form with the Liquid syntax: 
`{{ Request.Form.Name }}`

You need to figure out how one of your content items looks like when it is serialized in JSON and reproduce the same structure.

To do this, you could, for example, create one manually, then, create a deployment plan that exports the content items with your content type.
You could also check a recipe to see how the content are imported.

It seems that you added Name and Mobile fields to your content so it could look like this if your content type name is 'Feedback':

```
{
          "ContentType": "Feedback",
          "DisplayText": "{{ Request.Form.Name }}",
          "Owner": "admin",
          "Author": "admin",
          "Feedback": {
            "Name": {
              "Text": "{{ Request.Form.Name }}"
            },
            "Mobile": {
              "Text": "{{ Request.Form.Mobile }}"
            }
}
```

**Comment by gaurav151299** [comment]
dear @agriffard 
we are using  (
{{ Request.Form.Name }} ) but this is not retrieve the value of textbox. after submit, this {{ Request.Form.Name }} ) is inserting in database as plain string.  
kindly suggest what am i doing wrong?
![image](https://user-images.githubusercontent.com/63450365/78999433-749e4500-7aff-11ea-8f6d-aa27fb7ae0b8.png)

**Comment by agriffard** [comment]
> {{ Request.Form.Name }} ) is inserting in database as plain string

I don't know why.

You can remove: `"ContentType": "Feedback",`

And replace this : `"Feedback": {`
by the technical name of your content type, probably something like this:
`"Page_Feedback_Form": {`

**Comment by gaurav151299** [comment]
Dear Team,
As i share in previous comment that {{ Request.Form.Name }} can not retrieve the value of textbox during the content creation. after submit, this {{ Request.Form.Name }} ) is inserting in database as plain string. this problem is persist. I am sharing all screenshots of Form and workflow, kindly suggest me where am i wrong.
![image](https://user-images.githubusercontent.com/63450365/79101377-3ed6a780-7d1d-11ea-9f32-e364738d0f7e.png)

![image](https://user-images.githubusercontent.com/63450365/79101571-a7be1f80-7d1d-11ea-8eaa-751c5410bdc8.png)

![image](https://user-images.githubusercontent.com/63450365/79101601-bad0ef80-7d1d-11ea-98e5-7acd9d1db70a.png)

![image](https://user-images.githubusercontent.com/63450365/79101638-d50acd80-7d1d-11ea-8eae-2d838695b846.png)

**Comment by kakashi0807** [comment]
@gaurav151299  you can try with {{Request.Form["Name"]}}
