### ISSUE TITLE
Documentation for Linux deployment

### ISSUE THREAD

**Issue by EagleSmith** [OrchardCMS/OrchardCore#589]
thanks!

**Comment by Skrypt** [comment]
It is there https://github.com/OrchardCMS/Orchard2/wiki/Running-on-Linux
But it needs to be refreshed

**Comment by Jetski5822** [comment]
Yeah, we probably need to update this :/

**Comment by Piedone** [comment]
This isn't really applicable anymore; you just run OC under Linux like any other ASP.NET Core app (and nothing special compared to Windows).
