### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by adelemam** [OrchardCMS/OrchardCore#5890]
After enabling Localiztion and Content Localization , and Adding Localization Part to a Content Type, 
After Filling One culture and save and when Try to add the second culture it redirect me to page 
"OrchardCore.ContentLocalization/Admin/Localize" giving me **The page could not be found.**

Any idea?

**Comment by hishamco** [comment]
Please add a your content, then choose the culture that you need to localize to, from the drop down after that you will be able to localize the content with the selected culture

**Comment by adelemam** [comment]
thanks hisham ,
https://drive.google.com/open?id=1ApdWBbv9WHp7d6wm_JOizicrB_7fkfDL
above is a video link of what is happening with me , as i am doing what you are saying as i think , can you help please?

**Comment by hishamco** [comment]
Are working on the latest bits? or beta NuGet packages?

**Comment by adelemam** [comment]
nuget package 
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-10004" />

**Comment by adelemam** [comment]
<PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-10004" />

**Comment by adelemam** [comment]
source code here:
https://drive.google.com/open?id=1_4zr7zDi3jwfInstNwvXqkRBJv5qcemS

**Comment by hishamco** [comment]
Please try the latest bits, coz I already saw this issue before and I fix it

I will try to reference it if I find it

**Comment by hishamco** [comment]
FYI https://github.com/OrchardCMS/OrchardCore/pull/5197

**Comment by adelemam** [comment]
thanks a lot hesham , but i just get the last code from github and tried run it , With same issue unfortunately, Any Idea?

**Comment by adelemam** [comment]
@hishamco I took  the language part address url and paste it in the browser 
"http://localhost:5000/OrchardCore.ContentLocalization/Admin/Localize?contentItemId=4tp7abfrbh50k5ym9j2vhegwn0&targetCulture=ar-EG"

and it give me **"An Error Occurred while executing the request"**
this is a fresh code , I didn't change anything on it

**Comment by adelemam** [comment]
@hishamco  i got the issue , i added localization Part on linkMneu Item not the whole menu, that was giving me the issue ( despite i think it should be handled from the system and that it is a bug) 

now my question , when i am changing between culture i cannot see my localized menu appear? how can i do  it ?

**Comment by hishamco** [comment]
I will have a try ..

**Comment by sebastienros** [comment]
Menu doesn't support content localization. You will need to create as many menus as languages, and switch them in the layout.

**Comment by hishamco** [comment]
> Menu doesn't support content localization

I see, so it's moved to backlog ...

**Comment by hishamco** [comment]
@sebastienros I think it would be nice to mention what's not localizable in our docs, at least we will save time instead of asking this many times

/cc @agriffard

**Comment by adelemam** [comment]
thanks a lot I have workaround it with solution Like @sebastienros  mentioned and it worked  ( some issue appeared but I will add another issue .
thanks for your help guys

**Comment by hishamco** [comment]
Feel free to open any issue you are facing
