### ISSUE TITLE
How to create a ContentType with 2 sub section inside of the ContentType.

### ISSUE THREAD

**Issue by lcf007** [OrchardCMS/OrchardCore#5892]
A question, I want to create a ContentType that can have 2 subsections inside of a container, those 2 subsections are required to show on half of the space for each, basically 50% for each. also, I want the user can see the layout while editing, not in preview.

is there a way to do this without modifying code?
Thanks.

**Comment by sebastienros** [comment]
>  I want the user can see the layout while editing, not in preview

If you use the Preview feature, you can see the layout while editing, but in a different window. OC doesn't provide front-end inline editing.

Also you should use the Page type that ships in the default recipes (Agency, Blog) as it will allow to create custom sections. If you want to force only two sections, you can use two HTML fields on a custom content type.

**Comment by lcf007** [comment]
Thank you for your reply.
I tried Agency, none of the items have a Container and Child relationship, eg, Services change size and position by the template. 
What I want to do is a Container and have multiple children added at the same time in Edit Mode, not one by one, if I want to have 2 children, then I will have 2  items inside of the Container created at the same time and split to 50/50. 
There might be multiple ways to do this based on what I learned from OrchardCore:
1. In the content definition, is it possible to have a Container that already has 2 children inside, so when I create the container, it will create all of them?
2. Another thinking is if I only modify flows.edit.js file, when I create one item, I will also send 2 other create request after 1st one created. the issue in this way is I don't know how to change the FlowMetadata to make it display 50/50.
3. The last way will be to add another Controller just like BuildEditor in OrchardCore.Flows/Admincontroller.cs, it can create a list of the item. 
I don't want to change the code because it will be hard to maintain if OrchardCore gets updated.
So please give me a suggestion on how to achieve my goal, the less code modification requirement will be the best.

Thank you very much.

**Comment by sebastienros** [comment]
What about a Content Type that has two fields, and then a BagPart of this Content Type.

**Comment by ns8482e** [comment]
@lcf007 It seems you are looking for Orchard 1 like layout  (Issue #4686)
You can easily achieve by creating custom content type. See "Layout Page" example in this comment https://github.com/OrchardCMS/OrchardCore/pull/4470#issuecomment-540891941
