### ISSUE TITLE
Feature Request: Flow setting for auto expand

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5895]
I would like a Flow Part setting added for expanding or not expanding the flow accordion.
There should be a check box that when checked means the Flow Part will be automatically expanded in the Admin UI when you edit a content item.

I am tired of having to open up the accordion looking for the pieces of info I want expanded.

**Comment by agriffard** [comment]
In the dev branch, there is now a 'toogle all' icon when your mouse is hover.

See #5640

**Comment by JoshTango** [comment]
ok thats nice I just checked that out, bit i would still prefer a setting
@agriffard
