### ISSUE TITLE
Can not configure culture in admin page

### ISSUE THREAD

**Issue by lzw5399** [OrchardCMS/OrchardCore#5898]
**Question**
1. The culture configuration item could not be found
![image](https://user-images.githubusercontent.com/45249999/78889570-7b44a200-7a96-11ea-9852-2ed7ed10ea5d.png)

![image](https://user-images.githubusercontent.com/45249999/78889360-1b4dfb80-7a96-11ea-87de-2dcb9b536e4d.png)

**Reproduce Steps**

- Use docker to run the latest image according to the documentation
`docker run -d -p xxxx:80 --name orchardcms orchardproject/orchardcore-cms-linux:latest`
- Configure the connection string (Mysql 8.0.17)
- Select "Agency Theme"
- Enable all localization-related functionality
![image](https://user-images.githubusercontent.com/45249999/78889726-d2e30d80-7a96-11ea-8554-f71bbda6096a.png)

Did I miss something? Thanks for any help

**Comment by deanmarcussen** [comment]
Sorry, it got moved to _Configuration -> Settings -> Cultures_

We need to update that guide

**Comment by hishamco** [comment]
@deanmarcussen I have a look to our docs, seems it was changed since then, @agriffard is there a second to inform the readers from where they can add the supported cultures or we need to add a new section for that?

**Comment by deanmarcussen** [comment]
@hishamco  here's the guide link that needs updating https://docs.orchardcore.net/en/dev/docs/guides/install-localization-files/
