### ISSUE TITLE
Resource resolution between themes and modules

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5907]
We are building a module that includes a script that depends on jQuery.  We also have a Theme that defines it's own version of jQuery (ThemeName-vendor-jQuery) in the resource manifest and includes it in the `Layout`. Is there a clean way for my module to define it's jQuery dependency and still have the theme provide it's own implementation of jQuery ?

**Comment by deanmarcussen** [comment]
It depends how you want your module to reference `jQuery`.

You could define all the `jQuery` versions with a version property, and the same name.

Then in your theme or module specify that you want `jQuery` of a specific version.

i.e. `{% script name:"jQuery", version:"3.4.1" %}`

**Comment by agriffard** [comment]
Ok, keep both versions in ResourceManifest but didn't change the themes as they still have their own '-vendor-jQuery' resource.

**Comment by sebastienros** [comment]
You can make a third module that contains the resources for your themes and modules, and they will reference the same jquery resource definition.
