### ISSUE TITLE
Not possible to erase Youtube field value

### ISSUE THREAD

**Issue by PixPunch** [OrchardCMS/OrchardCore#5908]
Hi, from an orchard beginner :)

Found not exact case, but maybe related to the one I have:
[https://github.com/OrchardCMS/OrchardCore/issues/2472](url)

My issue that youtube field should be optional, and I want user to erase a value of youtube field if it should not be shown. So if the value is blank - video player at front office shouldn't be shown.

**Steps to reproduce**

- Create a new content type, add a title and youtube field to it (it should not be required).
- Create a post "Demo post" based on content type, where URL for youtube field is, for ex. "https://www.youtube...."
- Publish. Title, Youtube player is renders, everything is fine.
- Enter "Demo post", remove value "https://www.youtube...." and publish again.
- If you check "Demo post" at front/back offices the value is still exist at youtube field.

Do I misunderstand how youtube field works or is it a bug?
Thank you in advance.

**Comment by jptissot** [comment]
Did you modify the Field settings to make the url optional ?

**Comment by jptissot** [comment]
Looking at the code, it seems that once you set an address, it does not get reset if you remove the value: 
https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore.Modules/OrchardCore.ContentFields/Drivers/YoutubeFieldDisplayDriver.cs#L61

**Comment by PixPunch** [comment]
Thank you, works as expected!
