### ISSUE TITLE
Error shell descriptor using Orchard CMS with an MVC Module

### ISSUE THREAD

**Issue by blqck11** [OrchardCMS/OrchardCore#5914]
Hi 
I want to be able to use the CMS backend for managing content and writing my own MVC Controllers to display data into a custom theme.
I am using the Sample projects provided in the solution:

- NewAppCMS
- MVCProject
- TheBestTheme

so what i did , is creating a new theme , then reference it in the CMSProject.. eveything works fine until here.i added an mvc project to the solution, added a reference in the cms, i modified the startup.cs file of the mvcproject like this 

```
public class Startup : StartupBase
    {
        private readonly IConfiguration _configuration;

        public Startup(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public override void Configure(IApplicationBuilder builder, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
        {

            routes.MapAreaControllerRoute
            (
                name: "Home",
                areaName: "MVCProject",
                pattern: "",
                defaults: new { controller = "Home", action = "Index" }
            );
        }

    }
```

when I run the webapp the theme works fine , but i cant access to the result returned by the controller unstead i get "The page could not be found." message...
when i activated the module in the admin panel (the enable button still appear and the i got the confirmation message for enabling... i think it never got activated) i got      

    InvalidOperationException: Invalid serial number for shell descriptor

**Comment by sebastienros** [comment]
You create a class library (not an mvc project) as a module. I assume you referenced the Targets.Module package correctly.

This exception might happen if something went bad while enabling a feature. Try to restart the app.

Are you using the latest version from MyGet ?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
