### ISSUE TITLE
There is a bug in RSS feeds

### ISSUE THREAD

**Issue by ReddewYoung** [OrchardCMS/OrchardCore#5915]
There is a bug in RSS feeds, all the posts description are the same as the first post.

![mmexport1586669690916](https://user-images.githubusercontent.com/3390662/79061432-d0fd9200-7cc2-11ea-9175-2c42d351e2ee.jpg)

@agriffard @sebastienros @deanmarcussen

**Comment by hishamco** [comment]
I will check this soon, thanks @ReddewYoung for reporting this

**Comment by hishamco** [comment]
I can reproduce the bug, hope to fix it soon
