### ISSUE TITLE
Remove Manifest.txt files

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#592]
We dont need them.

I suggest we move most things to the Assembly Info file.

Name = AssemblyTitle
Version = AssemblyVersion
Orchard Version = Obsolete... as we rely on nuget package compatibility.

Sure there will be more

**Comment by sebastienros** [comment]
Didn't we talk about it and found that we needed them ;)

**Comment by sebastienros** [comment]
oh, we said we needed the information but it could be assembly metadata or custom service, cool.

**Comment by Jetski5822** [comment]
Yup! - The pipeline will be quicker, cleaner... however, lots to change to do it.

**Comment by sebastienros** [comment]
It's dependent on the fact that we are using references to modules too, so it has to be based on this change. Maybe after we merge your mvcless PR.

**Comment by jtkech** [comment]
To share some thinkings.

**Manifest.txt**

- Great idea. Indeed, modules will not be really dynamically loaded, so all runtime assemblies will be naturally in the default dependency context.

- So, maybe other things can be simplified, e.g `GetExtensions()` could be processed by simply using `DependencyContext.Default.RuntimeLibraries` filtered by extensions ids.

- We could also deduct modules inter-dependencies through runtime assemblies references. Maybe we could have a convention for modules assembly names, e.g starting with `OrchardCore.Module...` ...

- On another side i'm also thinking about lightweight extensions without any assembly (e.g a theme with only views). Note: this scenario already works (only a little error is logged).

**mvcless**

- So, about defined types to be used through mvc we can have: `module => module => mvc`. But we can't have `module => core project / other package => mvc`. So, as done for shape helpers, in a given module the rule would be to define inherited types `as public MyDefinedClass : LibraryClass`.

- Can be discussed after merging mvcless but do you think it's ok or do we need to re-consider this? If so, we would need to re-use more modules dependencies, those which reference mvc.

Best.

**Comment by DanielStolt** [comment]
I love this idea. We would need to add some custom assembly attributes beyond the ones that are normally included in AssemblyInfo.cs I'm guessing.

But one question: `Module.txt` currently also declares the *features* of a module. Are you suggesting we move this into assembly metadata too? If so, how do we handle the cardinality of 1-to-n, i.e. how do we add metadata for n number of features to just one assembly metadata?

**Comment by sebastienros** [comment]
We are not thinking about metadata, but a POCO with some fluent methods, like the `SchemaBuilder` does for migration:
```
Manifest.Module("FooModule", module =>module
    .Version("1.0.0")
    .Feature("Feature1", f => f
    .Description(T["This feature does things"])
    .Category(T["Content"])
    .Dependencies("F1", "F2") 
  )
)
```

**Comment by DanielStolt** [comment]
Hmm... ok, interesting. So if you have a module DLL, how do you extract this metadata without actually loading the DLL into the process first?

**Comment by sebastienros** [comment]
You don't, you can't, but all modules are loaded statically, why would you want to do such things?

**Comment by DanielStolt** [comment]
You're right - I forgot I managed to get dynamic loading removed. :)

But then, what does it have to do with AssemblyInfo? When/how would the above code get called?

**Comment by sebastienros** [comment]
It has nothing to do with it. I assume Nick suggested AssemblyInfo, but I think we can do it this way. just the way I am suggesting.

**Comment by Jetski5822** [comment]
That looks like a nice design there @sebastienros 

I still dont see why we cant do this even if we still have dynamic loading... which I am determined to put back - at some stage :)

**Comment by Jetski5822** [comment]
Maybe something like this...

```
[assembly: ModuleDependencies("F1", "F2")]
[assembly: ModuleFeature("Orchard.Feature1", (cfg) => cfg
   .WithName("Feature 1")
   .WithDependencies("F1", "F2"))]
```

**Comment by Jetski5822** [comment]
What about something like this?

```
[assembly: Module]
[assembly: ModuleType("theme")]
[assembly: ModuleDependency("F1")]
[assembly: ModuleDependency("F2")]
[assembly: ModuleFeature("Name", "Description", "Category", new[] { "F1", "F3" })]
```

So benefits of having it in the Assembly is that this information gets compiled in to the assembly manifest... You can right click on the assembly, view details and there is it. Again, im not sure... something about this bugs me too.... Ideas!?

**Comment by sebastienros** [comment]
It's not intuitive. We'd better embed the manifest.txt in the assembly at that point.

There are no issues with having a simple interface to implement.

**Comment by Jetski5822** [comment]
Okay so extending on yours

```
Manifest.Module((cfg) => cfg
	.WithDependencies("F1", "F3")
    .WithFeature("Feature One", fcfg => fcfg
		.WithDescription(T["This feature does things"])
		.WithCategory(T["Content"])
		.WithDependencies("F1", "F2"))
    .WithFeature("Feature Two", fcfg => fcfg
		.WithDescription(T["This feature does things"])
		.WithCategory(T["Content"])
		.WithDependencies("F2"))
	// optional
	.WithDescription(T["This module does things"]) // By default obtain from the AssemblyInfo
	.WithCategory(T["Content"]) // By default obtain from the AssemblyInfo
	// Theme
	.AsTheme() // .WithType("theme") // default will be .WithType("module")
	.WithBaseTheme("TheBaseTheme")
)
```

**Comment by jtkech** [comment]
And maybe `.WithPriority()`.

Forgot what i said above, i was too polarized on assemblies deps and then not on features ones.

> I still dont see why we cant do this even if we still have dynamic loading...

You're right. I was thinking, when a precompiled module is dyn loaded, that it's still useful e.g to inhibit a module by renaming / deleting its manifest file.

> dynamic loading... which I am determined to put back - at some stage

Wow. We already do this (in master) when a precompiled module has no project.json file. So, we don't use the project model and lookup in its bin folder. Note that, when dyn compiled, the bin folder has been populated in a structured way as publish do, this to deal with specific runtime lib (native ones are ignored).

**Note**: Maybe we have to consider the flexibility of the manifest file, e.g to change the priority, but i still think it's a good idea to grab features infos from the extension assembly.

-----

Finally, as a last idea, maybe also possible from a module assembly to automatically detect its features and their dependencies (without manifest infos). E.g by still using orchard attributes, then feature types, then by looking in their baseTypes to find dependencies ...

In some tests (which pointed me on some wrong namespaces and missing deps in manifest files) i could retrieve some dependencies on some regular features. One difficulty was to retrieve dependencies on features as `Orchard.Contents` which, among other things, register core services.

Need more thinking but maybe we could have primary Orchard modules, and, with some conventions on features / namespaces names, when a feature depends on some core services types, we could deduct that it depends on the related primary Orchard modules.

Best.

**Comment by agriffard** [comment]
Done with recent changes from @jtkech : There are now Manifest.cs files in each Module and Theme with a corresponding attribute.
