### ISSUE TITLE
Custom Theme with Custom Module

### ISSUE THREAD

**Issue by blqck11** [OrchardCMS/OrchardCore#5922]
Hi 
Im building a 3 projects : 

- 1 OrchardCore cms project
- 2 Custom OrchardCore Theme project
- 3 Custom MVC project 
- 

so the CMS project works fine with my custom theme, so i added a simple project with a simple controller which return a string and i did the routing stuff in the mvc project.

but , when i run the application , always the theme is displayed without the message coming from the controller, so i added a break point into the controller , and i found that its being called when i access the route , but nothing ever is displayed from that controller...
i think the theme engine is overriding it or something like that.

Am i missing something ??

**Comment by Piedone** [comment]
If your controller is called (is also the action called or did you just put a breakpoint into the ctor?) then you've setup up your module correctly so the question is why you don't see the output. Can you show the code of the controller?

**Comment by sebastienros** [comment]
Duplicate

**Comment by Piedone** [comment]
Hmm, what is this a duplicate of @sebastienros ?
