### ISSUE TITLE
Development of Dynamic Form in Orchard Core CMS

### ISSUE THREAD

**Issue by gaurav151299** [OrchardCMS/OrchardCore#5923]
Dear Team,
I am very new in OrchardCore and want some help. I want to create a input form for storing the record in database. In my form there is three input fields (Name, Mobile, Feedback) and i want to store the data in user defined table not in predefined tables of OrchardCore.
Kindly suggest us a better way to implement this feature.

**Comment by Piedone** [comment]
You can just implement the form fully in code pretty much as in standard ASP.NET Core MVC and then you have control over everything, including how it is stored. Or would you utilize Orchard's Flow Part to build an admin-editable form?

**Comment by gaurav151299** [comment]
dear @Piedone, 
can you provide an example to implement Orchard's Flow Part to build an admin-editable form.

**Comment by infofromca** [comment]
for db, see IndexingTaskManager, change IndexingTask to your table, also ref migration for table in db.
for  ASP.NET Core MVC with OrchardCore, there are 2 sample projects, one is OrchardCore.Cms.Web
, also search on google

**Comment by dodyg** [comment]
@gaurav151299 try this https://github.com/OrchardCMS/OrchardCore.Samples
