### ISSUE TITLE
Container routing question

### ISSUE THREAD

**Issue by jkulubya** [OrchardCMS/OrchardCore#5924]
We've got a site in development, with multiple page (content) types and we've so far ignored the issue of a tree-like/container page structures as discussed in other issues as we trained the content editors to manually input the urls of content (which they don't enjoy). We've had a look at the contained items routing work that was merged last week and it might be our solution.

Our most straightforward path from here on is making a taxonomy, with "categories" as the contained type, and attaching the taxonomy to each page type, and asking the editors to select a single category from the taxonomy. 

If we were displaying the categories of a taxonomy as pages of their own, it would be perfect, because the urls are generated as expected, with a "parent/child/grandchild" structure, but we aren't, we're just using them to tag the pages, so what we have to do is then generate a url using info from both the attached taxonomy term and the page itself.

More practically speaking, if I have a content item, with both a taxonomy part attached (set up for container routing), and an autoroute part (to route the content item itself), how can I get the url of my content item to be ```[url from taxonomy item, ie category including its ancestors]/[any pattern from "local" autoroute eg display_text]```.

Thanks

**Comment by jkulubya** [comment]
```Model.ContentItem.Content.NewsItem.Category | taxonomy_terms | first | json``` on a liquid page gets me access to this (I assume the same info is available in the autoroute pattern in the backend)

```
{
  "ContentItemId": "4x4t36mjw71eww0wkpqqw9tdm8",
  "ContentItemVersionId": null,
  "ContentType": "SiteCategory",
  "DisplayText": "Test",
  "Latest": false,
  "Published": false,
  "ModifiedUtc": "2020-04-12T16:06:07.7696459Z",
  "PublishedUtc": null,
  "CreatedUtc": null,
  "Owner": "admin",
  "Author": "admin",
  "SiteCategory": {
    "ShortDescription": {
      "Text": "Test"
    },
    "FullDescription": {
      "Html": "<p>Test</p>"
    }
  },
  "CommonPart": {},
  "TitlePart": {
    "Title": "Test"
  },
  "AutoroutePart": {
    "Path": "test",
    "SetHomepage": false,
    "Disabled": false,
    "RouteContainedItems": true,
    "Absolute": false
  },
  "TermPart": {
    "TaxonomyContentItemId": "4h9yghcdm5adm2qxp9ncx1mwdx"
  },
  "@WeldedPartSettings": {
    "TermPart": {}
  },
  "Terms": [
    {
      "ContentItemId": "4j7gctj6egxk4231527b49w24n",
      "ContentItemVersionId": null,
      "ContentType": "SiteCategory",
      "DisplayText": "2 Test 2",
      "Latest": false,
      "Published": false,
      "ModifiedUtc": "2020-04-12T16:08:55.6935723Z",
      "PublishedUtc": null,
      "CreatedUtc": null,
      "Owner": "admin",
      "Author": "admin",
      "SiteCategory": {
        "ShortDescription": {
          "Text": "2 Test 2"
        },
        "FullDescription": {
          "Html": "<p>2 Test 2</p>"
        }
      },
      "CommonPart": {},
      "TitlePart": {
        "Title": "2 Test 2"
      },
      "AutoroutePart": {
        "Path": "2-test-2",
        "SetHomepage": false,
        "Disabled": false,
        "RouteContainedItems": false,
        "Absolute": false
      },
      "TermPart": {
        "TaxonomyContentItemId": "4h9yghcdm5adm2qxp9ncx1mwdx"
      },
      "@WeldedPartSettings": {
        "TermPart": {}
      }
    }
  ]
}
```

The autoroute part is available but the path is just the path of the taxonomy term without any of its ancestors.

**Comment by hishamco** [comment]
Shoot it to you @deanmarcussen ;)

**Comment by deanmarcussen** [comment]
You just need to get a little creative with the liquid pattern for your content item `Autoroute`.

Here's an example that I think does what you are trying to do
```
{% assign parent_segments = ContentItem.Content.CategoryPart.Category.TermContentItemIds[0] | inherited_terms: ContentItem.Content.CategoryPart.Category.TaxonomyContentItemId | reverse %}
{% for seg in parent_segments %}    
    {% if parent_segments.last != seg %}
        {{ seg.DisplayText | downcase | slugify | append: '/' }}
    {% else %}
        {{ ContentItem.DisplayText | downcase | slugify }}  
    {% endif %}
{% endfor %}
```

**Comment by jkulubya** [comment]
I had to tweak it for our specific use case but that pointed me in the right direction.
Do you know why I have to include the content type like so ContentItem.Content.**_NewsItem_**.Part...? I've tried copying what you posted and a few other examples in the docs, but I've never gotten any liquid call to work without it.
