### ISSUE TITLE
Module nested in CMS page, is it possible?

### ISSUE THREAD

**Issue by dewebeloper** [OrchardCMS/OrchardCore#5929]
I created one custom module (MVC app) which read data from external db. I also referenec that on host project which has OrchardCore.Application.Cms.Targets. All is setup, connected and links works.
However, my question is can contnet from module be nested in CMS page in order to have something like:
[=========CMS page content (widget, html, whatever) =========]
[===============Module content =========== =========]
[=========CMS page content (widget, html, whatever) =========]

If that is possible shat is way to accomplish that.
Thanks.

**Comment by Piedone** [comment]
Yes: If you create a controller and return a view from an action then it'll be inserted into the Content zone of the theme.

**Comment by dewebeloper** [comment]
Thanks for info, I still trying to put together all pieces of OrchardCore and I still doesn't see a whole picture. 
I have modeule, I can see content of module view trough url /module/controller/action, that is clear. But your answer doesn't put any light on how to embed that content on CMS page content.
Right now I can't see way how to handle module content inside CMS page. 
Should I create widget and how? Shoudl I create some other kind of Content Type?
Canb you please bring some light on my doubts? 
Thanks

**Comment by Piedone** [comment]
As I said you don't need to do anything to embed your own module's output into the Orchard layout. If you want to create content types from your module you can also do that, the easiest being if you create the content types from the admin, export them to a recipe and then add the recipe to your module. These are [documented](https://docs.orchardcore.net/) and if you check out the code of the built-in themes' you'll see such recipes.

If you want to create content types like widgets to put onto the layout and those widgets need to run your own code (i.e. you don't just want to cobble them together from existing content parts) then you'll need to create a content part. Check out the [Training Demo](https://github.com/Lombiq/Orchard-Training-Demo-Module) for a tutorial on this.

**Comment by dewebeloper** [comment]
Cool. Thanks.

**Comment by dewebeloper** [comment]
I look at training demo and I found a lot of usefull thing there.
Now, I have one more doubt. 
If I want to show, let say on my homepage, products from external database (erp database) what is way to do that?

**Comment by Piedone** [comment]
You can do the same thing and hook up your controller action to the ~/ route. However, I suppose that product list would be embedded into a page surrounded by other kinds of content, right? In that case I'd create a widget, then add it to the Page providing the homepage.

**Comment by dewebeloper** [comment]
Yes, correct, idea is to crate product list which would be embedded into page surrounded by other content. 
Now on that training demo there is no anything abut creating widget. What is way to create widget which has access to external database?
Is there any guide /example how to that?
Can you give any clue?

**Comment by Piedone** [comment]
The Training Demo shows how to develop a content part and how to create a content type with it. The sole difference between a "normal" content type and a widget is that its Stereotype property is "Widget", something that you can also change from under the type editor on the admin.

In the driver of the content part you can produce any data you want to then display, including fetching data from an external system. Check out the drivers on how the view models are built there.

**Comment by Piedone** [comment]
I've also written a blog post about this: https://orcharddojo.net/blog/4-ways-to-display-something-from-your-module-nested-within-a-page-in-orchard-core-orchard-nuggets

**Comment by ns8482e** [comment]
@dewebeloper if you are looking for nested reusable content see solution provided in #3963 

For accessing  external data see demo module for sample code https://github.com/OrchardCMS/OrchardCore/blob/ece1f0182517d944d1b9af2a47c8069a616f1670/src/OrchardCore.Modules/OrchardCore.Demo/Pages/Foo/List.cshtml#L38

Demo uses `_session` but you could inject and use `external service` or `dbcontext ` instead of `_session`

**Comment by dewebeloper** [comment]
Thanks @Piedone for blog post, it's usefull.
Thanks @ns8482e but looks like your example is same as Creating a whole page from you module, so that doesn't look like sollution for my problem.
However, looks like in 

> In the driver of the content part you can produce any data you want to then display, including fetching data from an external system

lies a clue for solution.
I'm still researching it.

**Comment by dewebeloper** [comment]
@Piedone could be possible to somehow overwrite Feed proxy Url and there do things with external base and then just get back data in xml and show them trough some template?

Currently with Feed proxy url we can access to https://localhost:5001/Contents/Lists/4g4zf1s9mb29kx82v5nsfx86ce/rss so if we are able to write some custom code for access to external database, that could be soultion nested reusable content?

**Comment by Piedone** [comment]
It's really much easier than that, as I've explained in the blog post. But you can also have your own API endpoints (RESTful and GraphQL) or create an RSS feed. These would allow you to fetch the site's content programmatically if you're building a client-side SPA or mobile app to consume it for example. But it's not necessary if you just want to get some data from an external service behind the scene and display it withing an Orchard page.

**Comment by dewebeloper** [comment]
Yes, indeed. I finally managed to sort all and reach IDisplayResult Display trough content page. Thanks.
