### ISSUE TITLE
Is there a way to add a button on all widgets that will open a modal popup

### ISSUE THREAD

**Issue by SteeveDumais** [OrchardCMS/OrchardCore#5931]
I need to open up a model popup for all widgets I create.  Is there a way to do this

**Comment by sebastienros** [comment]
You could override the default template for widgets wrappers. That means you will need a custom admin theme, or provide a custom template with the Admin Templates feature.

**Comment by ns8482e** [comment]
@SteeveDumais  If you are asking for "Edit" in Admin then yes you can achieve by adding ContentCard alternate shape for ContentType, Example here https://github.com/OrchardCMS/OrchardCore/pull/4470#issuecomment-542354018
