### ISSUE TITLE
Localize Display Name for Content Types

### ISSUE THREAD

**Issue by randaratceridian** [OrchardCMS/OrchardCore#5937]
Is there any way to localize the Display Name for a Content Type? If we want to have the admin site support another languge, the Display Name is used in quite a few places.

Nouveau -> Landing Page is not what a French user would expect.

**Comment by hishamco** [comment]
The dynamic data localization is not supported yet, please follow this #4466 pr to track this issue

**Comment by sebastienros** [comment]
Duplicate
