### ISSUE TITLE
Difficulties creating a stateless multi-tenant CMS with OpenIdConnect

### ISSUE THREAD

**Issue by andrewlock** [OrchardCMS/OrchardCore#5947]
I've been exploring setting up an Orchard application for use in an existing SaaS product. Unfortunately I've run into a couple of issues, some of which seem to be blockers and bugs. There may well be existing issues for some of these, but wanted to describe everything I've struggled with in one place. I'm new to Orchard, so there may well be solutions I'm just not aware of 🙂

## Background

We have a SaaS product, that runs primarily on .NET Core linux containers in Kubernetes. We use an IdentityServer implementation for authentication, which has been customised quite heavily to allow features such as multiple "accounts" associated with a single username-password pair. i.e. you login with your username and password, then choose which tenant you want to use, before completing authentication. We also have two types of user: internal (admin) users, and client users.

We are using Postgres as the sql database for all apps, with apps primarily segregated by schema. For the Orchard deployment, we would be using a completely separate database instance. 

We want to provide the ability for clients to manage their own CMS for their individual tenant. I used the "SaaS" recipe to configure the app, and then additional tenants from the admin menu.

I ran into a variety of issues, but I think I've boiled it down to two blockers:

## Stateless deployment for tenants

The first issue is running as a stateless service (for easier hosting in kubernetes). I know there's a lot of work been done on this (e.g. https://github.com/OrchardCMS/OrchardCore/pull/5815 and https://github.com/OrchardCMS/OrchardCore/pull/5249), so I'm using the preview builds from MyGet. The new "shell settings in the database" work seems to work OK,  but when I create a new tenant a whole load of files are still written to App_Data. Should be being written to the database instead now (i.e. there's a bug), or is additional work required?

## OIDC Client configuration

Orchard seems to require each tenant to be configured as a separate client in IdentityServer? As each tenant uses its own callback URL (which can be added dynamically at runtime) we can't just use the same client details for each tenant. It's not really feasible to configure a separate IdentityServer client for every individual Orchard tenant.

Ideally, I want to set up Orchard as a single client in IdentityServer. On login, Orchard should direct users to the correct tenant based on a claim in the id_token (and forbid users from accessing the "wrong" tenant). Is that achievable? It's not clear to me that it is, but hopefully I'm wrong 🙂 

Thanks for your help, as I say I'm new to Orchard, so I'm hoping there are solutions here I'm just not finding!

**Comment by kevinchalet** [comment]
> Orchard seems to require each tenant to be configured as a separate client in IdentityServer?

Technically, nothing prevents you from reusing the same client registration across multiple Orchard tenants, but the validation part - consisting in rejecting authorization or token responses based on an identity token claim - is something you'll have to implement yourself, likely using the events model of the OIDC handler (`TokenValidated` is probably what you're looking for).

If you need more flexibility, you can also create your own OIDC module.

Personally, I wouldn't opt for this approach, specially if the Orchard tenants are managed by different parties. If they all share the same client registration, it will be likely way more difficult for end users to properly manage their authorizations (e.g you can't easily revoke the access granted to a particular tenant).

**Comment by andrewlock** [comment]
Thanks for the quick reply @kevinchalet!

> Technically, nothing prevents you from reusing the same client registration across multiple Orchard tenants.

Hmmm, ok, so I can use a single return URL for all tenants i.e. the `/signin-oidc` URL (for the "master/admin" tenant)? Currently, if I have two tenants, `/site1` and `/site2`, their return URLs have to be `/site1/signin-oidc` and `/site2/signin-oidc` currently..

I guess I don't really understand how the users would work in the case of a shared client registration, as the tenants all manage their own users separately, but we'd be redirecting to a single URL in the "main" tenant? To be honest, we don't really want local users at all, that's all going to be managed externally, so I'm doing my best to hide the existence of local accounts all together!

> If they all share the same client registration, it will be likely way more difficult for end users to properly manage their authorizations (e.g you can't easily revoke the access granted to a particular tenant).

I'm pretty sure this isn't an issue for us - we will likely manage access to the CMS separately, so tenants would lose access to login at the same time. 

The best case scenario I think (I'm not sure if this is possible) is that we have a _single_ set of users _across all tenants_ (as that most closely reflects our Identity server configuration), where access to a given tenant is controlled based on a claim in the id_token. i.e. only users with the claim `tenant_name=site1` can access the `site1` tenant etc. 

I'm happy to write custom modules etc to handle these things, just not sure what is technically possible, as haven't really got my head around Orchard yet!

**Comment by kevinchalet** [comment]
> Hmmm, ok, so I can use a single return URL for all tenants i.e. the /signin-oidc URL (for the "master/admin" tenant)? Currently, if I have two tenants, /site1 and /site2, their return URLs have to be /site1/signin-oidc and /site2/signin-oidc currently..

The `/signin-oidc` path is static and won't change across tenants, but if you want to implement that, you'll indeed need to change something in IdSrv to allow redirecting to trusted domains (e.g `https://domain1.com/signin-oidc`) or path bases (e.g `https://shareddomain.com/site1/signin-oidc`).

Alternatively, you could enable the OIDC server feature in the "main" tenant to serve as a proxy between your OC tenants and IdSrv.

> I guess I don't really understand how the users would work in the case of a shared client registration, as the tenants all manage their own users separately.

Currently, that's how it works. https://github.com/OrchardCMS/OrchardCore/issues/2029 tracks future improvements that would allow using OC without any local users database (scenarios 3 and 4). If this is something you'd like to contribute to, let us know!

Out of curiosity, why can't you have an IdSrv client per Orchard tenant? It would probably make things much simpler.

**Comment by deanmarcussen** [comment]
> The new "shell settings in the database" work seems to work OK, but when I create a new tenant a whole load of files are still written to App_Data. Should be being written to the database instead now (i.e. there's a bug), or is additional work required?

What files are you seeing written to the `App_Data` ? 

The Database or Azure Shells configuration option is only designed to handle the `tenants.json` and each tenants `appsettings.json`

For the data protection keys you will need to use the Azure data protection keys, and for media the Azure media.

Lucene is also currently stored in the tenants `App_Data`

**Comment by andrewlock** [comment]
> Alternatively, you could enable the OIDC server feature in the "main" tenant to serve as a proxy between your OC tenants and IdSrv.

I think this is the way it would have to work, I guess I just don't know _how_ that would plug in to Orchard 🙂 I've worked with the oidc integration in aspnetcore in general, just not sure where it fits in to Orchard's concepts?

> Currently, that's how it works. #2029 tracks future improvements

Yeah I found that one thanks, 3 and 4 definitely would be useful, but sounds like it isn't on the immediate road map (and I can understand why it would be tricky!)

> Out of curiosity, why can't you have an IdSrv client per Orchard tenant? It would probably make things much simpler.

Primarily it would be the operational overhead - it's not simple to achieve with our IdSrv implementation at the moment. 

It also feels like it's adding a lot of unnecessary overhead everywhere though - we will have potentially hundreds of tenants, and each tenant will only have a handful of users. Having to maintain a separate client for each doesn't seem simpler than the proxying approach you described..

**Comment by andrewlock** [comment]
Thanks @deanmarcussen.

> What files are you seeing written to the App_Data ?

Media files and lucene files, as you say. We're using AWS not azure, so I've already written a custom dataprotection service to store keys in s3, I guess I need to do the same for the media files. 

How should I handle the Lucene files?

**Comment by kevinchalet** [comment]
> I think this is the way it would have to work, I guess I just don't know how that would plug in to Orchard 🙂

For that, you need to:
  - Enable the OIDC client, server, management features in the main tenant and configure it to use IdSrv as the OIDC provider in the client settings.

  - Enable the OIDC client feature in the other tenants and create a client per tenant. This can be done programmatically using `IOpenIdApplicationManager` or using the GUI (management > applications).

  - Enable the OIDC client in each tenant. Currently, the configuration story is not as good as what we have for the validation feature, where you just have to select the server tenant in the list, so you'll have to add the server URL, client_id/client_secret manually. Future improvements to make that much simpler are planned.

> It also feels like it's adding a lot of unnecessary overhead everywhere though - we will have potentially hundreds of tenants, and each tenant will only have a handful of users. Having to maintain a separate client for each doesn't seem simpler than the proxying approach you described..

The approach I mentioned wouldn't save you from having to add client registrations, but you'd do that in Orchard (using the OpenIddict APIs) instead of in IdSrv.

**Comment by deanmarcussen** [comment]
> How should I handle the Lucene files?

There is a background service called Lucene Worker to keep different instances in sync (locally) and we have an issue https://github.com/OrchardCMS/OrchardCore/issues/4316 to track an elastic search implementation

**Comment by Skrypt** [comment]
@andrewlock I did not have time to run asynchronous tests with the Lucene module. I think @jtkech did but this is something I'm planning on doing. Though, the App_Data folder can be shared across Docker containers by using the same folder for each of them. Normally it should work fine unless we missed some locking mechanism in our asynchronous implementation.

Alternatively you could easily implement something around ElasticSearch simply by using the IDocumentIndex abstraction we have in OC. Also, you will probably need to implement a Distributed Cache or could contribute to @jtkech current PR work.

**Comment by jtkech** [comment]
So about Lucene as i remember

- So that's okay when runing only one instance and it is thraed safe.

- That's okay if running multilple instances but that don't share the same file system, as said by @deanmarcussen for each instance its Lucene worker background task will keep in sync its indexes.

- I tried to make it working with multiple instances sharing the same file system by using the underlying file locking system of Lucene, but because Lucene is not intended to work like this we opted to not implement it. Hmm, maybe we could reconsider this.

    Another suggestion by @sebastienros would be to create a different folder for each instance based e.g on the current process id, but that would need to be cleaned up.

    Otherwise as suggested by @Skrypt something around ElasticSearch e.g through a module.

**Comment by sebastienros** [comment]
Lucene indexation is "eventally consistent", and that's fine IMO. The "eventully" is instantaneous when editing content, and as long as the indexing runs if the index is rebuilt, which is quick too.

**Comment by Skrypt** [comment]
Ok, I'm wrong with the Status ID's. If each instance has it's own lucene.status.json file it won't make any difference as long as the IndexingTaskTable is consistent on each instances. Though, I need to check if we are using a cache on this. Maybe have a DistributedCache on the IndexingTaskTable would be sufficient for this to work properly with the background task simply.

**Comment by sebastienros** [comment]
Each node needs its own folder also containing the status id. The Index table shouldn't be cached.

**Comment by jtkech** [comment]
Maybe my next todo ;)

Because I'm quite ready with #5249 but needs more tests and with a concrete implementation of a distributed cache as done in #5815. So maybe i will do a local testing branch or just wait after RC2.

**Comment by andrewlock** [comment]
@kevinchalet thanks for the oidc overview - I understand now - make the main tenant's oidc server federate to our idsrv. After thinking it over, I think you're right RE our best options. That's a lot of additional complexity for little gain really. We'll make changes to idsrv to support the separate client registration per tenant instead. Thanks for the input. 

@jtkech @Skrypt @sebastienros Thanks for the Lucene heads up. We'll be running orchard in containers, so the easiest approach from our point of view is to have isolated file systems for App_Data. I assume there would be no need for process ids etc in that case?

 My understanding is that the Lucene background worker would detect changes in 1 container's lucene files, and propagate that to the other containers. Is that correct? The eventual consistency may be frustrating I guess, but as long as it's not a problem while actually editing I don't think that's a big deal.

I'm also happy to help out with the ElasticSearch integration, especially if Lucene proves to problematic. It sounds like that may be a more scalable solution? Though as an OC noob, creating an ES version of the `OrchardCore.Lucene` module is bit daunting! 😀😱

**Comment by Piedone** [comment]
For Lucene another option would be to use shared indices with the likes of [AzureDirectory](https://github.com/azure-contrib/AzureDirectory) that stores them in Blob Storage. I don't know what would be suitable similarly for AWS.

**Comment by jtkech** [comment]
Just as a reminder

And it seems that this `AzureDirectory` uses **local files for caching** as we use e.g for Azure Media, and not for the same reason as we also use for Sitemap. So for all of these we will have to think about what we want to support when there are **multiples running instances that share the same file system**.

E.g @sebastienros said a while ago that we don't want to support it for Lucene, but recently he had some ideas, then what about azure media, sitemap and so on. So 1st we have to decide what is worth to support, then it seems that we prefer [distributed] lock free solutions, e.g by using **different folder names** by process and some logic to cleanup these shared local files.

But I would need to focus more on it.

**Comment by kevinchalet** [comment]
Doing some housecleaning. Feel free to re-open if necessary.
