### ISSUE TITLE
Import and use React within OrchardCore

### ISSUE THREAD

**Issue by jackliDev** [OrchardCMS/OrchardCore#5956]
How can I import and use React within OrchardCore? It's possible to use React via HTML tag reference but I want to import React.

**Comment by deanmarcussen** [comment]
I assume you want to use SpaServices to host your react app

Please see this issue for details on how to do that https://github.com/OrchardCMS/OrchardCore/issues/5227

**Comment by jackliDev** [comment]
Is there a way to add React by adding it to the OrchardCore.Resources module instead?
