### ISSUE TITLE
I can’t get nothing to delete or rename in Media Library

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#5957]
Hi!
I can’t get nothing to delete or rename in Media Library. How can I fix this problem?

**Comment by Skrypt** [comment]
Maybe permissions related. There is not enough details on how to repro the actual issue.
Please provide more details.

**Comment by niknikita** [comment]
> Maybe permissions related. There is not enough details on how to repro the actual issue.
> Please provide more details.

When I click on the delete button, nothing happens, the file / folder remains in place. How can I fix it?

![image](https://user-images.githubusercontent.com/20708134/79621507-81d9b600-8135-11ea-80a6-cd71af6d5f41.png)

**Comment by hishamco** [comment]
@niknikita are you using the latest nightly bits or RC1?

**Comment by deanmarcussen** [comment]
Please can you check your browser console for errors

and let us know in which kind of environment this is happening?

I.e. development locally, or on production, if production what kind of server you are running this on . 

Please also check your logs in `App_Data`, and provide details.

As @Skrypt says this is likely permission related, to the `App_Data` folder

**Comment by niknikita** [comment]
> Please can you check your browser console for errors
> 
> and let us know in which kind of environment this is happening?
> 
> I.e. development locally, or on production, if production what kind of server you are running this on .
> 
> Please also check your logs in `App_Data`, and provide details.
> 
> As @Skrypt says this is likely permission related, to the `App_Data` folder

![image](https://user-images.githubusercontent.com/20708134/79642168-cb6de380-81bd-11ea-971f-8d82a5a22dfc.png)
production server
windows server 2012
IIS8

**Comment by niknikita** [comment]
@Skrypt @deanmarcussen Thanks a lot! The problem really was in the folder permissions problem!) The problem is solved!
