### ISSUE TITLE
View link on content item editor

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#5958]
In Orchard 1 we have this "View" link on the editor for the permalink: 
![image](https://user-images.githubusercontent.com/1976647/79497165-86b04400-8027-11ea-98ed-108f7e37669c.png)

While in Core we do have a View link in content items lists there is no such link in the editor. It would be great to have such a link so after saving a content item (or just when editing it) you could quickly open the page or copy a link to it (as opposed to copying the generated permalink and concatenating it with the site's base URL by hand).

Seems like a good first issue.

**Comment by sebastienros** [comment]
Maybe an icon on the right side of the textbox

**Comment by agriffard** [comment]
https://fontawesome.com/icons/external-link-alt

**Comment by dustyhoppe** [comment]
I'm interested in contributing and taking on this issue. Could someone provide a little more detail on exactly what should be accomplished to resolve this issue?

**Comment by Piedone** [comment]
Good that you're thinking about contributing @dustyhoppe! Two pointers:

- The permalink editor comes from the OrchardCore.Autoroute module, you'll find it in a shape (view) template there.
- You can see an example of generating a view link for a content item on the admin content list, which you can find in OrchardCore.Contents (just search for "View", including the quotes).

But! Now that I think about it just as the view link in the admin content list, this could be more generic than tying it to Autoroute, since you can very well present a content item on the frontend without Aoutroute Part.

So this could possibly be a shape that is displayed in the editor just by itself, much how the Preview button is displayed from OrchardCore.ContentPreview (but this wouldn't be a button but a link, with the icon Antoine linked to, positioned roughly after AutoroutePart). This part will be a bit tricky but once you have it displayed somewhere on the editor mimicking what the Preview button does it'll be a good start.

**Comment by ns8482e** [comment]
You take code from  following file - to display view link on content detail page

https://github.com/OrchardCMS/OrchardCore/blob/b50be75bae36aa5b3a779386d13927f3d6469937/src/OrchardCore.Modules/OrchardCore.Contents/Views/Contents-Button-Edit.SummaryAdmin.cshtml#L11-L14

**Comment by Piedone** [comment]
Thank you Antoine!
