### ISSUE TITLE
Editor-only "DisplayText" for certain widgets

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#5959]
For example when you build a complex Flow Part layout with a lot of Container widgets then you'll end up with something like this:
![image](https://user-images.githubusercontent.com/1976647/79497461-076f4000-8028-11ea-9e25-9c3dc1e4cd51.png)
This is hard to work with and gets incomprehensible at one point.

My proposal would be to offer some kind of DisplayText functionality for such widgets that don't otherwise use Title Part so we can have something like this:
![image](https://user-images.githubusercontent.com/1976647/79497799-9bd9a280-8028-11ea-99d7-0df52e02edcd.png)
These texts wouldn't be displayed on the frontend though.

Alternatively, we can display these on the frontend too, as a title attribute for the respective elements. With this approach, we could reuse Title Part for every such widget but disable its placement, however, use its value in the attribute.

**Comment by Skrypt** [comment]
//cc @ns8482e

**Comment by ns8482e** [comment]
Exactly the same issue I reported earlier #5006,  

In my module I am using  DisplayText pattern on CotentType without using TitlePart  https://github.com/OrchardCMS/OrchardCore/issues/5006#issuecomment-564350530

**Comment by Piedone** [comment]
I'm not sure I understand how Title Part solves this @sebastienros. I'm actually talking about displaying this text on the admin only, so it's only the editor where it should be displayed. It doesn't need to be generated by a pattern (I don't think that would create sensible titles since the problem to begin with is that all widgets are very similar) but provided by the user.

But as I said we can utilize Title Part but its placement needs to be disabled and its value possible displayed in the given widget's element's `title` attribute.

**Comment by ns8482e** [comment]
@Piedone  another option is to use Workflows and assign value to DisplayText.  See comments in #4972

**Comment by Piedone** [comment]
Well yeah but that's very cumbersome.

**Comment by sebastienros** [comment]
You want to change Container so it has a field to change its DisplayText property. This can be implemented by adding a TitlePart, but a side effect is that it might be displayed on the front end (apparently it is not for widgets).

The TitlePart is supposed to be an editor for DisplayText, but today always renders a shape. I'd suggest (@deanmarcussen agrees as of today) that we add a setting on the TitlePart to not render anything. 

Then we can just add TitlePart to Container, with this setting turned on.

**Comment by Piedone** [comment]
Thinking about it I don't think we need a setting. The modules providing the affected widgets (which is just Container as of now) could just add it, disable its placement, and display its value in the given widget's element's `title` attribute (like `<div title="Container widget title here">`.

Seems super simple. If there are no better ideas, I'll submit a PR.

**Comment by ns8482e** [comment]
@Piedone It seems, you are not really concerned about value of TitlePart or DisplayText, instead you are only concerned to show some text from content on Card Title or on Title attribute in Edit mode.

**Comment by deanmarcussen** [comment]
For infos @Piedone the `FlowWidget` `ContentCard-FlowPart.Edit` shape will render a content items display text already (here)

`<span data-content-type-display-text="@contentTypeDisplayText" class="widget-editor-header-text">@T["{0} {1}", contentItemDisplayText, contentTypeDisplayText]</span>`

Maybe you know this, maybe not. 

I think @ns8482e does because he wrote it ;)

So what @ns8482e is suggesting could also work, if you don't want to type this `display text` in, and have it pre populated.

When speaking with @sebastienros we were interested in a solution, that would resolve this, plus other issues, where the `TitlePart` is the only editor for a content items display text, but sometimes you want to have a display text value without it being rendered anywhere.

Hence the suggestion for a setting.

In this scenario, it will resolve it for all widgets (noting that `Container` is not a templated widget per say, it is just a definition), that want to have the ability to include some kind of admin display value, without worrying about it turning up on the front end.

**Comment by ns8482e** [comment]
@deanmarcussen thank you clarifying the exact location of the code.

@Piedone You also have option to create alternate for each ContentCard widget type that you want to customize Card Title  i.e. ContentCard-Container.Edit

https://github.com/OrchardCMS/OrchardCore/blob/19c2ffec988b468290636dde12abcf83095548bb/src/OrchardCore.Modules/OrchardCore.Widgets/ContentCardShapes.cs#L35-L36

**Comment by Piedone** [comment]
Yeah, I know about the DisplayText being rendered on the admin, hence why I suggest using Title Part with the frontend placement disabled. And yes, overrides would also be an option @ns8482e though only necessary if we really want to display the title somehow for the widget, like the `title` attribute as I mentioned.

But I feel like I'm not getting the point across well enough because this seems to be trivial. I wanted to submit a PR but then it occurred to me that the Container widget type is only defined in certain recipes. We copied it to the Helpful Extensions module for reusability a while ago. So I'm now demonstrating what I'm talking about here: https://github.com/Lombiq/Helpful-Extensions/commit/224f80b2a5f0a85ddff018c04e798ef65ac88804

So, on contrary to what I thought when I've opened this issue (mistakenly remembering that Container is a reusable widget) now I think nothing really is needed here, the capabilities are already there, and using them is very simple. Potentially we could have a typepart setting instead of the placement but I'd consider that only something low prio.

**Comment by ns8482e** [comment]
> The TitlePart is supposed to be an editor for DisplayText, but today always renders a shape.

@sebastienros If all orchard core built templates use `DisplayText` for front-end rendering then How about adding "Render Title" true/false on TitlePart setting with default to `false `that will not to generate TitlePart shape in TitlePartDisplay driver?

```
public override IDisplayResult Display(TitlePart titlePart, BuildPartDisplayContext context)
        {
            var settings = context.TypePartDefinition.GetSettings<TitlePartSettings>();
            if (settings.RenderTitle)
            {
                return Initialize<TitlePartViewModel>(GetDisplayShapeType(context), model =>
               {
                   model.Title = titlePart.ContentItem.DisplayText;
                   model.TitlePart = titlePart;
               })
               .Location("Detail", "Header:5")
               .Location("Summary", "Header:5");
            }

            return null;

        } 
```
