### ISSUE TITLE
Shell / Tenant naming conventions

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#5961]
After watching the last meeting video talking about the `Shells` document in the docs. Yes maybe better to include it in a more global `Tenants` document and / or in a `Stateless / Distributed` guide.

That's said this is not the goal of this discussion. Here the question is what is the better name to use in our code? `Shell` or `Tenant` or keep both as it is?

- Personally i have no preference but naturally i already had updated some variables and maybe some classes by using the term `Tenant` but reverted these changes (maybe on demand).

- When we talk about tenants it is more natural to talk about a `Tenant` than a `Shell`. One funny thing is that the min set of`ShellSettings` are in a `tenants.json` file ;)

- So, maybe better to have `TenantHost`, `TenantContext`, `TenantScope`, `TenantOptions`, `TenantSettings`, `TenantConfiguration`, `ITenantvents` ...

- Or the opposite as we have less cases using the `Tenant` term e.g `IModularTenantEvents`, but we use it frequently in our comments.

- Finally, for those that already use the `Tenant` term, I don't like so much the term `Modular`, maybe better to have `ITenantEvents`, `TenantContainerMiddleware`, `TenantRouterMiddleware` ...

But maybe too many place to update and better to live with both `Shell` and `Tenant` ;)

**Comment by sebastienros** [comment]
@kevinchalet and @Piedone will tell you that a shell is not a tenant

**Comment by jtkech** [comment]
Okay, maybe when considering a tenant as a whole having also e.g site settings and so on

But e.g `TenantHost`, `TenantContext`, `TenantConfiguration` ... don't hurt me

**Comment by kevinchalet** [comment]
> @kevinchalet and @Piedone will tell you that a shell is not a tenant

I have no strong opinion on which one is better, but yeah, the inconsistency is not great... 😄

**Comment by Piedone** [comment]
I think at one point we had the same discussion with O1 too :D.

IMO "tenant" is the expression for the logical entity of a subsite. I.e. if your app has subsites, then I'd call them tenants. E.g. "My Orchard site has three tenants for my friends' blogs."

The "shell" is a concrete instance ("object", though it's not a particular one in the code) of that tenant that's currently executing. It's the runtime of a given tenant. I.e. a tenant has a shell or it can even have multiple ones (you can just start more but if your app is multi-node then there will be one shell for reach tenant on each server). E.g. "My Orchard site has three tenants for my friends' blogs apart from the Default tenant. It's deployed to two nodes so at a given time there are 8 shells running."

I'd only change tenants.json, that has bothered me for a while :) (ShellSettings.json). The Shell* classes in code thus are fine, as is the admin referring to "tenant".

**Comment by jtkech** [comment]
Yes, maybe not so important and anyway maybe too late ;) But because i thought about it multiple times, i wanted to have some feebacks, so thanks for your answers.

> I think at one point we had the same discussion with O1 too :D.

Good to know, i didn't remember ;)

> The "shell" is a concrete instance (...) of that tenant that's currently executing. It's the runtime of a given tenant. I.e. a tenant has a shell or it can even have multiple ones

Yes but in fact it is not a `Shell` it is a `ShellContext`, so here the suggestion would be that a tenant can have multiple `TenantContext`. Then, as under a `ShellContext` we can have multiple `ShellScope`, under a `TenantContext` we could have multiple `TenantScope`.

> I'd only change tenants.json, that has bothered me for a while :) (ShellSettings.json)

I agree if we only keep the `Shell` term but maybe `tenants.json` is clearer for people.

> The Shell* classes in code thus are fine

I'm not against the `Shell` term and I like theses classes too. But if we keep this term, i would then prefer to not use `TenantContainerMiddleware`, `TenantRouterMiddleware`, `IModularTenantEvents` but `ShellContainerMiddleware`, `ShellRouterMiddleware`, `IShellEvents`.

But anyway i'm fine with the code as it is, only some suggestions to be sure we use a good compromise.

**Comment by Piedone** [comment]
Yeah, I agree that the services you mention in your last but one paragraph should rather refer to shells.

**Comment by Piedone** [comment]
We had the exact same discussion 3 years ago, starting from here: https://github.com/OrchardCMS/OrchardCore/pull/627#issuecomment-288078065-

**Comment by jtkech** [comment]
Thanks for the link

Yes i understand the unicity of a Tenant but i thought that we could have for a given Tenant e.g. multiple TenantContext if multiple running instances, and in a given instance e.g. multiple TenantScope ...

But anyway i think it's too late ;) and i'm fine with how it is done

I just wanted to know what other people was thinking about it
