### ISSUE TITLE
Media view link should open a new tab

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#5966]
... or you could lose all your edits.

Repro:
- Create a blog post, spend 2 hours working on it
- Click on the image banner button
- By mistake, click on the View link of an image, you are redirected and your content is lost

Might be related to local storage draft backup feature.

**Comment by hishamco** [comment]
Opening in the link in a new tab is simple for now

**Comment by hishamco** [comment]
For sure we need to save the content on the local storage during the edit process
