### ISSUE TITLE
How can I rename these menu items in the admin panel

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#5968]
Hi!
How can I rename these menu items in the admin panel? I need to rename these items for several different languages. If I need to do this in language files, then where exactly?

In which language file and which line do I need to edit to change for example the main menu item "Content"?

![image](https://user-images.githubusercontent.com/20708134/79642073-310da000-81bd-11ea-876d-bb0ce8575b53.png)

**Comment by hishamco** [comment]
Seems the picture is similar to what in #5957?!! Could you please elaborate which menu you refer to?

**Comment by niknikita** [comment]
> Seems the picture is similar to what in #5957?!! Could you please elaborate which menu you refer to?

Извините, случайно прикрепил не тот скриншот) Добавил актуальный

**Comment by hishamco** [comment]
All static strings can be localized using `PortableObjectLocalizer` all the supported translations located in `Localization` folder, please check our docs and [Crowdin](https://crowdin.com/project/orchard-core/) for the current supported cultures

**Comment by sebastienros** [comment]
Create a custom localization file for each language if you don't want to use the public ones.
