### ISSUE TITLE
some Recipes js expression cause ArgumentNullException 

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#5971]
Hi while I run "Blog" Recipes, an ArgumentNullException occurred.

I've debugged the error, because this js expression from recpie.json

    [js: parameters('AdminUsername')]

Orchard Core version: dev latest.

error stack:

ArgumentNullException: Value cannot be null. (Parameter 'value')

    Jint.Runtime.ExceptionHelper.ThrowMeaningfulException(Engine engine, TargetInvocationException exception)
    Jint.Runtime.Interop.DelegateWrapper.Call(JsValue thisObject, JsValue[] jsArguments)
    Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal()
    Jint.Runtime.Interpreter.Expressions.JintExpression.Evaluate()
    Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue()
    Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal()
    Jint.Runtime.Interpreter.JintStatementList.Execute()
    Jint.Engine.Execute(Program program)
    OrchardCore.Scripting.JavaScript.JavaScriptEngine.Evaluate(IScriptingScope scope, string script) in JavaScriptEngine.cs
    +
                var result = jsScope.Engine.Execute(parsedAst).GetCompletionValue()?.ToObject();
    OrchardCore.Scripting.DefaultScriptingManager.Evaluate(string directive, IFileProvider fileProvider, string basePath, IEnumerable<IGlobalMethodProvider> scopedMethodProviders) in DefaultScriptingManager.cs
    +
                return engine.Evaluate(scope, script);

**Comment by deanmarcussen** [comment]
Can you let us know where you are running the recipe from?

i.e. from a 
- Site Setup
- Tenant Setup
- The recipes menu in the admin area
- From code?

**Comment by RockNHawk** [comment]
> Can you let us know where you are running the recipe from?
> 
> i.e. from a
> 
> * Site Setup
> * Tenant Setup
> * The recipes menu in the admin area
> * From code?

I run from `The recipes menu in the admin area`.

**Comment by deanmarcussen** [comment]
I was not able to repro.

Can you let me know which recipe you initially ran when you set the site up?

**Comment by RockNHawk** [comment]
Thank you for your reply, I run the `Blank Site` recipe when set the site up.

**Comment by deanmarcussen** [comment]
The AdminUsername property is set by the recipe executor to the current users name.

So if you are debugging, put a break point in the Recipes/AdminController at line 108

```
                await _recipeExecutor.ExecuteAsync(executionId, recipe, new
                {
                    site.SiteName,
                    AdminUsername = User.Identity.Name,
                },
```

As i said I couldn't repro, so I would suggest to rerun site setup with the correct recipe initially, if you are unable to resolve the issue

**Comment by RockNHawk** [comment]
Thank you very much! I will have a try!

**Comment by RockNHawk** [comment]
after I re setup site with another recipes, it works well.

**Comment by Graph2133** [comment]
Hi! Are there any updates on this bug ?
I'm trying to access  `[js: parameters('AdminUsername')]` from DataMigration registered as
` services.AddScoped<IDataMigration, MyMigration>() ` which is using IRecipeMigrator
```
public async Task<int> UpdateFrom10Async()
{
        await recipeMigrator.ExecuteAsync("myMigration.recipe.json", this);
}
```
and getting the same issue as @RockNHawk .
Is there a possibility to pass AdminUsername directly from my configuration file in framework?
I think that the problem might be that it's working only with setupService.SetupAsync and as an workaround I should use ContentManager to update ContentItem.

Please note that issue is not reproducible from startup recipe (with flag "issetuprecipe": true).
