### ISSUE TITLE
Please add edits to the documentation

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#5973]
Please add to the documentation information that after editing a language file (.po) you need to restart tenant otherwise the changes will not take effect

**Comment by hishamco** [comment]
Agree, but whenever you add a new culture the UI tells that you need to restart the tenant

**Comment by niknikita** [comment]
> Agree, but whenever you add a new culture the UI tells that you need to restart the tenant

I agree, but the message will appear during the installation of the culture, but when you need to change something in the language file, not everyone will guess to restart the tenant

**Comment by hishamco** [comment]
Right

**Comment by hishamco** [comment]
@agriffard can I add this as a note in the localization docs?
