### ISSUE TITLE
azure media storage

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/OrchardCore#5974]
When I am able to get this process to work, I will be updating the documents so dumb people like me can use the instructions without trouble. It seems to be my special purpose in the orchard project. 

I want to enable using azure blob storage for storing media.
1. I created a storage account and got the connection string, see below with username and key removed:
DefaultEndpointsProtocol=https;AccountName=xxxx;AccountKey=xxxx;EndpointSuffix=core.windows.net

2. I added section to the appsettings.json of the OrchardCore.Cms.Web project

{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "OrchardCore": {
    "OrchardCore_Media_Azure": {
      "ConnectionString": "DefaultEndpointsProtocol=https;AccountName=xxxx;AccountKey=xxxx;EndpointSuffix=core.windows.net",
      "ContainerName": "mycontainername",
      "BasePath": "mybasepath",
      "CreateContainer": true
    }

    }
  }

3. I enable the azure media storage feature
4. in the log I get the following error
2020-04-18 14:24:53.7405|None|8000009b-0004-ff00-b63f-84710c7967bb||OrchardCore.Media.Azure.Startup|ERROR|Azure Media Storage is enabled but not active because the 'ConnectionString' is missing or empty in application configuration. 
2020-04-18 14:24:53.7596|None|8000009b-0004-ff00-b63f-84710c7967bb||OrchardCore.Media.Azure.Startup|ERROR|Azure Media Storage is enabled but not active because the 'ContainerName' is missing or empty in application configuration. 

I am sure I am missing something very simple and basic but I am not able to do this with the current documentation and I would like to fix it.

**Comment by jtkech** [comment]
Which version are you using?

The section names have been changed recently to be compatible under linux, this by using `_` in place of `.`

So, depending on your version, you may have to still use `OrchardCore.Media.Azure`

**Comment by roballred** [comment]
@jtkech, impressive. Not only did you help me this fast but the documentation is so up to date. Thanks.

**Comment by roballred** [comment]
closing
