### ISSUE TITLE
ArgumentException: numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#5983]
![image](https://user-images.githubusercontent.com/297675/79693863-1c6fed00-823b-11ea-95a6-809304243f9f.png)

**Comment by sebastienros** [comment]
Repro steps?

**Comment by Skrypt** [comment]
I think I know, I will fix that one. It's because there is no Lucene index files created.

**Comment by PauloSRH** [comment]
Hello, just a side note. I had the same exception, and the problem was that I set the From and Size of the elastic search query to 0. To solve it I just change the Size varible to 10.

**Comment by sebastienros** [comment]
If you are willing to add some validation to the code that would be nice.

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/5984 Already exists I need to review it. By the mean time you can use this PR to patch the issue on your side. Else, I might make some changes to it.
