### ISSUE TITLE
Exception when using 'Send Email' task twice in workflow

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/OrchardCore#5986]
I need to send two emails in my workflow: one to the customer and one to the website owner:

![image](https://user-images.githubusercontent.com/3008547/79695721-c883f900-8278-11ea-8d10-b11f681c9f89.png)

The second email fails with an exception:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
```

The complete log:
[orchard-log-2020-04-19.log](https://github.com/OrchardCMS/OrchardCore/files/4499878/orchard-log-2020-04-19.log)

**Comment by jtkech** [comment]
Which version? Just tried without any issue

How can you use a send email as a **starting** activity?

**Comment by netwavebe** [comment]
My mistake, I wanted to start the workflow in a 'fire and forget' manner:

```
var workflowType = await _session.Query<WorkflowType, WorkflowTypeIndex>().Where(x => x.Name == "MyName").FirstOrDefaultAsync();

if (workflowType != null)
{
    var input = new Dictionary<string, object>();
    input.Add("UserProfile", userProfile);
    _ = _workflowManager.StartWorkflowAsync(workflowType, null, input);
}
```

when I use `await` all works fine.

Need to find some other way to start this workflow.

**Comment by netwavebe** [comment]
I will close this issue
