### ISSUE TITLE
Deployment plans search

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#5990]
I just noticed that `DeploymentPlans` did not get the new look for the search filters that was added everywhere else some time ago

![deployment plans](https://user-images.githubusercontent.com/13782679/79729323-37983680-82e7-11ea-9d9d-293bb0629426.PNG)

//cc @agriffard

**Comment by hishamco** [comment]
I just assigned this to me, I notice that somewhere else I will fix them
