### ISSUE TITLE
Suggestion to move Login settings to Design menu

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#5998]
Suggestion to move Login settings from Security to Design menu item as this is more design issue than security.

![loginsettings](https://user-images.githubusercontent.com/61165619/79847323-3db21400-83c8-11ea-8349-005463a4a8e1.PNG)

**Comment by hishamco** [comment]
How it's design related?

**Comment by vitalybrandes** [comment]
Use site theme for login page — Requires an active site theme.

At least this one related to Theme.
I think that Design is more nature for this menu item.

**Comment by agriffard** [comment]
Not relevant.
