### ISSUE TITLE
Feature Request: Admin Settings for admin options

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#6001]
I would like an admin settings page that gives options of how the admin should function.
For example if I want icons on content types or not.

Possibly I also want an extension ability.

This way developers could write extensions and put settings options in an admin section to turn features on or off.

**Comment by Skrypt** [comment]
The extensibility point already exist and it is ISite implemented with SiteSettings class which inherits from Entity which has a `public JObject Properties { get; set; } = new JObject();` that can be used to extend the SiteSettings options. All you need is to create a driver to extend it.

**Comment by JoshTango** [comment]
I have 2 features I want.

1. One is to attach an icon to a content type so that that icon show sup in the content items list in the admin.
2. The other is in the admin menu.  When you click on ContentItems in the menu I want the treeview to open up further to show content types so I cant click on a content type and only see those in the list.  I know you can click on which content types to show in the header of the list but I dont like that

**Comment by Skrypt** [comment]
There's an option in the Admin Menu module to add content types to a menu item. You could use that. For attaching an icon to a content type, you will need to look at ContentTypeDefinition -> Settings field inherited from ContentDefinition class.

**Comment by JoshTango** [comment]
Could you tell me how to navigate to this ability to add content types to a menu item.
I want this to show up in the admin menu only.

**Comment by sebastienros** [comment]
You have filed an issue for the icons, and the second question is answered, so I am closing this one.
