### ISSUE TITLE
Cannot get Taxonomy Tree in GraphQL

### ISSUE THREAD

**Issue by pbros** [OrchardCMS/OrchardCore#6010]
Hello,

I'm trying to retrieve a Taxonomy Tree using GraphQL, but all I can get is the first level of terms.

Here is my Taxonomy (Help-Center, with Help-Topics for terms)

![image](https://user-images.githubusercontent.com/17840445/79910723-2a656f80-83ed-11ea-8f4b-e29132452cc8.png)

QUERY:
```
query MyQuery {
  helpTopic {
    createdUtc
    displayText
  }
  taxonomy {
    displayText
    path
    taxonomy {
      termContentType
      contentItems {
        displayText
        contentType
        ... on HelpTopic {
          displayText
          contentType
        }
        ... on Taxonomy {
          createdUtc
          displayText
          taxonomy {
            contentItems {
              displayText
            }
            termContentType
          }
        }
      }
    }
  }
}


```

RESULT
```
{
  "data": {
    "helpTopic": [],
    "taxonomy": [
      {
        "displayText": "Help Center",
        "path": "help-center",
        "taxonomy": {
          "termContentType": "HelpTopic",
          "contentItems": [
            {
              "displayText": "User Settings",
              "contentType": "HelpTopic"
            },
            {
              "displayText": "Client Account",
              "contentType": "HelpTopic"
            }
          ]
        }
      }
    ]
  }
}
```
I can't seem to fetch the help-topics directly either

Is this supported or not yet?

**Comment by deanmarcussen** [comment]
Yes, the sub Terms, are stored as (numerous) JSON Array inside the typed `TaxonomyPart.Terms` list of content items. 

I don't think we have an accessor with GraphQL to access JSON properties directly?

However as the taxonomy itself is one single content item, you may find just retrieving the content item directly from the content api more useful, as you can then parse the arrays of terms as required.

/cc @carlwoodhouse

**Comment by sebastienros** [comment]
Do we think that accessing the whole taxonomy is a sufficient solution?

**Comment by pbros** [comment]
From my side, if it's easy to implement, I could get the whole taxonomy and cache it. Ideally however, I would like to be able to get the child nodes of any other node in a tree. For example, if a user is browsing something in Level 2, I would fetch the nodes under it to display them as navigation.

If I want to create a PR for this, how should I be fetching the whole taxonomy?

**Comment by pbros** [comment]
Hi,

So from what I can tell, exposing the whole taxonomy would require adding a property to `TaxonomyPartQueryObjectType`. There seems to be a few helpers in `TaxonomyOrchardHelperExtensions` that might be useful.

I could simply add a Field called "TermHierarchy" to `TaxonomyPartQueryObjectType` but I'm not sure how I could return the Terms JArray that @deanmarcussen referenced. It seems like the current "Terms" being returned would come from that source, but it only provides the first level

```csharp
Field<ListGraphType<ContentItemInterface>, IEnumerable<ContentItem>>()
                .Name("contentItems")
                .Description("the content items")
                .PagingArguments()
                .Resolve(x => x.Page(x.Source.Terms));
```

/cc @sebastienros @carlwoodhouse

**Comment by pbros** [comment]
Hi,

So I've managed to expose the Terms Hiearchy in JSON by adding the following to `TaxonomyPartQueryObjectType`

```csharp
Field<StringGraphType>()
                .Name("contentItemsTermsJson")
                .Description("the content items terms")
                .PagingArguments()
                .Resolve(ctx =>
                {
                    if (ctx.Source.Content.Terms is JArray termsArray)
                    {
                        return termsArray.ToString();
                    }

                    return null;
                });
```


This allows me to get the full hierarchy, but not the "content" or render of the terms. I could parse the json in my client application, however there is no current mechanism to fetch a term in the hierachy via GraphQL and we cannot query them directly via their content type either. This limits the usefullness since I can really get the content of the Terms (which have their own parts and widgets)

I will continue working on this, but if anybody has any insights it would be appreciated.

**Comment by pbros** [comment]
I have changed my approach and instead use the templates on the CMS to render the correct HTML that already includes what I need
