### ISSUE TITLE
How can I group elements of competing elements by tags

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#6012]
How can I group elements of competing elements by tags to filter them by these tags in the future? And a similar localization filter.
I need functionality similar to the one I painted in the screenshot.
Tell me how can all this be done?
![image](https://user-images.githubusercontent.com/20708134/79918532-641a9280-844e-11ea-9f83-f2ca33ff92ed.png)

**Comment by sebastienros** [comment]
Create an interface that modules can implement to alter the content items query like in O1. Create some shape zones in this view to let other modules inject custom filters.

**Comment by niknikita** [comment]
> Create an interface that modules can implement to alter the content items query like in O1. Create some shape zones in this view to let other modules inject custom filters.

Thanks for the answer.
But is there an example of how to do this?
