### ISSUE TITLE
HtmlPart with standard editor error in FlowPart

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6013]
See https://github.com/OrchardCMS/OrchardCore/pull/6006#issuecomment-617426850

js error with code mirror.

/cc @ns8482e

**Comment by ns8482e** [comment]
@agriffard However I am not using Standard editor

**Comment by agriffard** [comment]
This is only occurring whne you add a widget with HtmlPart in a FlowPart on the fly?
After saving it and reloaded, there is no error, right?

**Comment by ns8482e** [comment]
No, when I try to create new Page content type or edit existing Page content typ it gives this error
