### ISSUE TITLE
Language Localization in Orchard Core CMS

### ISSUE THREAD

**Issue by gaurav151299** [OrchardCMS/OrchardCore#6014]
Dear Team,
I am new in Orchard Core development. Kindly share us a example of implementing hindi and english language as culture localization.

**Comment by hishamco** [comment]
Please refer to our docs https://docs.orchardcore.net/en/dev/docs/guides/install-localization-files/ also you could read about Content Localization module

**Comment by gaurav151299** [comment]
Dear @hishamco,
This link is for admin section but i have been need to implement localization on our content of website. Kindly provide us an example for content localization.

**Comment by hishamco** [comment]
>  but i have been need to implement localization on our content of website. Kindly provide us an example for content localization.

That's why I told you to read about Content Localization module before ;) check the docs again for more details about this module, but I don't think there's a sample for that yet

FYI @dodyg is already discussed that in some issues

**Comment by agriffard** [comment]
Related: #4096

**Comment by dodyg** [comment]
@gaurav151299 This issue has an extensive discussion on localization.
