### ISSUE TITLE
Question - How to Query  (SQL) UserIndex 

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6017]
How can i programmable and / or liquid query UserIndex table?
Using:
`SELECT [DocumentID] FROM [UserIndex];`

In SQL Query I get the document number,
now i need the content of this document?

**Comment by dodyg** [comment]
![query](https://user-images.githubusercontent.com/1761249/80272255-f8435e80-86c7-11ea-919f-a05199b1d737.png)

**Comment by vitalybrandes** [comment]
It is working with ContentItemIndex, but I cannot get nothing from UserIndex table.

**Comment by Skrypt** [comment]
``` SQL
SELECT * FROM UserIndex JOIN Document ON UserIndex.DocumentId = Document.Id
```

Works perfectly fine in SQL Server.

**Comment by sebastienros** [comment]
We should probably have a section in the documentation with the database schema for each module.
