### ISSUE TITLE
Is there a way to create a project to contain all my widget overrides

### ISSUE THREAD

**Issue by SteeveDumais** [OrchardCMS/OrchardCore#6026]
I am trying to create a solution to hold all my widgets cshtml, js scss etc files.  I do not want to put them in the themes.  Is there a way to do this in orchard core?  Where does the code look for overwrites of the default widget cshtml?

**Comment by deanmarcussen** [comment]
You may place them in a module, and when you do that, you should take a dependency in the manifest on the modules views you are overriding (or depending on...), i.e. `OrchardCore.Widgets`, which will ensure that it is taken into account when building the shape tables overrides, and alternates etc.

**Comment by SteeveDumais** [comment]
Thanks that did it
