### ISSUE TITLE
How do I modify the model of a widget

### ISSUE THREAD

**Issue by SteeveDumais** [OrchardCMS/OrchardCore#6032]
I need to add more fields to the model of one of my Widgets. These fields would be filled with a service call. Is there a way to do this?

**Comment by deanmarcussen** [comment]
A widget is a content item, so you can add any content part to it.

Depending on how you want to make your service call, you could do this form a field view (override the template, and make the call there), or by creating a custom part

**Comment by SteeveDumais** [comment]
When a content type is created it creates a part.  The contentType widget I created is called alert and it creates a part alert.  I was trying to use it to override the model.  I created a AlertPartDisplayDriver.cs in drivers, I created an AlertEditViewModel.cs and AlertPartViewModel.cs under viewModel but I can not seem to hit them.  

What do I need to do to hit them?

**Comment by deanmarcussen** [comment]
I think from what you are describing you are talking about the default `alert` part that would be added to a content item to contain its fields.

This part you cannot hit by creating a driver. (it is dynamic, and managed separately).

The best way for you to understand how to create your own part is to use the code generation templates to generate a module. 
https://docs.orchardcore.net/en/dev/docs/getting-started/templates/

You will then have a default part created, and you can see all the code than manages a part, driver, startup registrations, views, etc
