### ISSUE TITLE
Consider using the default same-site mode in the OpenID module

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#6033]
To allow SPAs to use silent authorization requests (i.e `prompt=none` requests sent in an iframe), the OpenID module currently disables the same-site feature, that would prevent the Orchard authentication cookie from being sent as part of the iframe request.

This works well and was until now the recommended way for SPAs to get new access tokens without using refresh tokens. Unfortunately, this approach will soon be impossible, due to major browsers now banning third-party cookies:
  - https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/
  - https://techcrunch.com/2020/01/14/google-wants-to-phase-out-support-for-third-party-cookies-in-chrome-within-two-years/

We should consider removing the same-site logic and encourage SPAs to use refresh tokens, which is consistent with what other actors in the industry are heading to: https://auth0.com/blog/securing-single-page-applications-with-refresh-token-rotation/

**Comment by rneto** [comment]
For those who cannot currently deal with a secure token refresh flow in SPAs, another alternative might be to host Orchard Core CMS and the SPA in a _same-site_ enviroment like _spa.web.dev_ and _orchard.web.dev_.
