### ISSUE TITLE
can't select Content Type page

### ISSUE THREAD

**Issue by Nowhk** [OrchardCMS/OrchardCore#6035]
I've created 2 custom content type, called Pages and Devices:

![image](https://user-images.githubusercontent.com/19835752/80284602-d37ad580-871f-11ea-9bf2-45367b19f0b6.png)
But when I click on Pages (or Devices), it redirect to Content -> Content Items, not "staying" on Pages (or Devices).

i.e. here I clicked on Pages:

![image](https://user-images.githubusercontent.com/19835752/80284671-2b194100-8720-11ea-8ae5-ab49da2ab978.png)

But the menu item "Pages" its not highlighted.... Content -> Content Items is.

I remember I used to do this in the past...

**Comment by Nowhk** [comment]
It seems it works if you place the menu item "under" the Content Type. I think that's a bug :)

**Comment by deanmarcussen** [comment]
Can you let us know which version you are on? I believe this was resolved after RC1

**Comment by Nowhk** [comment]
Are you able to reproduce? Nice.
Not sure which version.
I dotnet new occms from template, added yesterday using dotnet new -i OrchardCore.ProjectTemplates::1.0.0-rc1-*

It helps?

**Comment by deanmarcussen** [comment]
Can you try with the myget dev feed?

I checked, it is resolved there. You should see in your url a query string param `?admin=88337225`

`/Admin/Contents/ContentItems/467h0xrtddg0ts9757aaykm1m3/Display?admin=88337225`

Which is how it has been managed.

The myget feed is available with `dotnet new -i OrchardCore.ProjectTemplates::1.0.0-rc1-* --nuget-source https://www.myget.org/F/orchardcore-preview/api/v3/index.json`

Or see the docs for a more complete example https://docs.orchardcore.net/en/dev/docs/getting-started/templates/

**Comment by Nowhk** [comment]
Can't try now. I'll try in the future with a new version, too see if this has been fixed. Thanks

**Comment by deanmarcussen** [comment]
Please reopen if you can repro it with the dev feed
