### ISSUE TITLE
Entity Relationship: One To Many & One To One ?

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#6039]
Hi,

Does Orchard Core supports `One To Many` & `One To One` relationship by `reference` (do not seralize the referenced entity to json document ) ?

**Comment by ns8482e** [comment]
Orchard core data is stored as documents in JSON format. For one to may relation between content items, you could use content picker field

**Comment by RockNHawk** [comment]
Thank you for reply, I define a custom `Entity`, and in Orchard 1.x version, 1 n and n n relations is supported, in Orchard Core, underlying use yessql seems no relations support.

**Comment by RockNHawk** [comment]
@ns8482e 
Thank you for reply, I define a custom `Entity`, and in Orchard 1.x version, 1 n and n n relations is supported, in Orchard Core, underlying use yessql seems no relations support.

**Comment by ns8482e** [comment]
> @ns8482e
> Thank you for reply, I define a custom `Entity`, and in Orchard 1.x version, 1 n and n n relations is supported, in Orchard Core, underlying use yessql seems no relations support.

Yes, orchard core is document based approach where contents are stored as documents

**Comment by Skrypt** [comment]
You can use a YesSQL IndexProvider if you want to build a one to one or one to many relationship between records. You could also use Dapper directly for doing so. Nothing is impossible. But by default OC uses a map/reduce design pattern. When we are storing data in the document table it's is considered as reducing the data. And when you use an IndexingProvider you can "map" these json fields into actual database tables. This question has been asked often. I'm closing as the answer can also be found by searching on the same topic.
