### ISSUE TITLE
Workflow execution becomes very slow due to Lucene index building, how to optimize?

### ISSUE THREAD

**Issue by claudesitorus** [OrchardCMS/OrchardCore#6042]
I have two content types in the CMS:

1. Voucher : has three fields 
- Voucher Code (Text Field)
- Voucher Quantity (Numeric Field)

2. Voucher Redemption: has three fields
- Voucher (Content Picker Field -> Voucher Content Type)
- Member Card Number (Text Field)
- Redeemed At (DateTime Field)

The member information (including card number) is stored in my other application. The requirement is to redeem a voucher in the CMS, based on the member card number in my other application. 

Therefore, I want this application to trigger a workflow in the CMS that will:

1. Check if the Voucher item with specific Voucher Code exists 
2. If Voucher exists, get the count of Voucher Redemption items for the specific Voucher
3. If count is less than Voucher Quantity: create a new Voucher Redemption content item

_Note: Voucher Code and Member Card Number values are sent in the `HttpRequest` that triggers the workflow_

I am using **Lucene** query to search the Voucher and Voucher Redemption items based on the Voucher Code, meaning I have added indexes for those content types. Everything works fine in the beginning with small number of redemption items in the CMS, but as the number of item increases (>1000), the workflow execution becomes awfully slow because of the index building. 

Is there a better alternative, in terms of execution speed, to query content items based on a specific field value? If not, how to optimize Lucene index building process?

**Comment by Skrypt** [comment]
Normally those content items (Vouchers and Voucher Redemptions) are indexed when you publish them. So, indexing a content item normally is quite fast if you batch it and this is why @jtkech made a defered task to index them in batch instead of one by one.

So here, you say that you are searching in a Lucene Index and that it gets slow when you reach over 1000 items per "query"? I'm suprised of that to be honest because here it should not be "building" the index every time you query it. If something is slow that's more likely because there is something you did wrong. Querying fields with Lucene should always be faster than doing a SQL Query.

**Comment by claudesitorus** [comment]
> you are searching in a Lucene Index and that it gets slow when you reach over 1000 items per "query"? I'm suprised of that to be honest because here it should not be "building" the index every time you query it. If something is slow that's more likely because there is something you did wrong. Querying fields with Lucene should always be faster than doing a SQL Query.

Sorry for not being clear enough, but the slowness that I am experiencing is for the execution of the whole workflow and not just the Lucene query. I agree that the querying part is actually very fast but the workflow ends in an item being created (and published) and hence the indexing process runs. Initially I thought that the workflow will end and returns an `HttpResponse` right after the content item creation, but apparently it has to wait for indexing process to finish before doing so and what I observed is that with an increase in the number of items in the CMS, the indexing takes more and more time. 

So on one hand, I would like to utilize the Lucene query in my workflow, but on the other hand, due to indexing process that takes place after content item creation, the workflow execution becomes very slow.

**Comment by deanmarcussen** [comment]
Can I ask what version of OC you are using?

And how many content items are being indexed by Lucene, during your workflow?

It feels like somehow you are reindexing them all, rather than just the updated content item

**Comment by Skrypt** [comment]
We had an issue in RC with that. I would not be surprised that the issue lies in the fact he's using RC.

**Comment by claudesitorus** [comment]
> We had an issue in RC with that. I would not be surprised that the issue lies in the fact he's using RC.

@Skrypt Yes, I am currently using RC. So, in RC there is an issue in indexing?

> And how many content items are being indexed by Lucene, during your workflow?

> It feels like somehow you are reindexing them all, rather than just the updated content item

@deanmarcussen Actually it is only one, the newly created content item

**Comment by Skrypt** [comment]
The entire module had a rework for fixing perd issues and adding options

**Comment by jtkech** [comment]
@claudesitorus

 yes the indexing process has been improved in the dev, **and items are now indexed in a deferred task**

**Comment by sebastienros** [comment]
Please let us know if RC2 fixed the issue
