### ISSUE TITLE
Added field to ViewModel, how can I find the value in Model object?

### ISSUE THREAD

**Issue by jackliDev** [OrchardCMS/OrchardCore#6043]
I added the following field to my view model,

` public string test { get {
                return "TEST";
            } }`

Where can I find this in my Model?

ex) I put a breakpoint on the first line of this code and I want to determine where in Model my field is.
`<div class="alert-widget-react" data-json='@Json.Serialize(Model.ContentItem.Content)' prefixValue-json='@Json.Serialize(Model.Metadata.Prefix)'>>
        <div class="loader"></div>
    </div>`

**Comment by Skrypt** [comment]
Here your Model is "dynamic" so you won't see it from the debugger. You can "write" your model in your view by doing @Model.Content or you could make your Controller return a strongly typed ViewModel that inherits from ShapeViewModel. See SearchFormViewModel.
