### ISSUE TITLE
Client performance problems (Admin UI) when loading complex structures

### ISSUE THREAD

**Issue by CBrams** [OrchardCMS/OrchardCore#6046]
Hi there

We are trying to create a pretty simple structure for books that have reusable parts. A book contains chapters, which contain sections which hold the markdownformatted text. pretty simple. Some of the chapters are instead "lookups", that just targets a chapter created outside the book.

We set this up as the book containing a bag of chapters, which contains a bag of sections.

Our problem is that when loading the book, not being large (about 10 chapters with maybe 2-4 sections each), it has horrible performance. Currently it is taking well over a minute just to load the page to drag and drop (or edit) the chapters. It is not the server taking this long, but the client machine running the UI javascript.

If I analyze the performance in chrome, it gives me the following results
```
195 ms - Loading
85344 ms - Scripting
140 ms - Rendering
13 ms - Painting
330 ms - System
371 ms - Idle
86394 ms - Total
```

80019.9 ms, or 93.4 % is just from "Animation Frame Fired", called from the minified font-awesome-free script. I assume this might be something like the fontawesome changing of `<i>` tags to `<svg>` tags for the icons to work, or something related to that, as there is no animation upon loading the edit page in the admin view.

Is there any way to fix this? I tried looking at the code, but it seems horribly ineffecient from font-awesome, which usually works just fine. Maybe it has something to do with how Orchard loads the content items?

Best, Christian

**Comment by Skrypt** [comment]
This issue has been fixed in the latest dev I assume @agriffard

**Comment by agriffard** [comment]
Are you testing with source code or packages?
If you use packages, which version are you using?

Please try with the latest dev packages.

**Comment by CBrams** [comment]
We're running the build from the docker hub:
orchardproject/orchardcore-cms-linux:dev

**Comment by Skrypt** [comment]
When did you update this image locally last time.

**Comment by CBrams** [comment]
All right, thanks a lot, it seemed I was using an old image. It is working now 👍 . I'm closing this issue, thanks a lot.
