### ISSUE TITLE
Bug with External (Azure AD) authentication redirect

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#6049]
When using an external login provider to login to a site, on the first request (after the login callback) the Page does not reflect the fact that the user is authenticated. Refreshing the page manually works as expected. 

I tried stepping through the code and everything looks good.
https://github.com/OrchardCMS/OrchardCore/blob/acee23ef121a09568198ebda164d591ae9f084ed/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AccountController.cs#L387

This line get's called with `returnUrl= null` which triggers this line https://github.com/OrchardCMS/OrchardCore/blob/acee23ef121a09568198ebda164d591ae9f084ed/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AccountController.cs#L276

But, on the frontend, I still see the Log In button as you can see in the gif below. However, clicking on the URL bar and hitting enter loads the user just fine. The gif below is using Azure AD authentication but we saw the same behavior with Github authentication.

![oc_login_bug](https://user-images.githubusercontent.com/4681586/80494166-5d02f100-8934-11ea-80aa-98406e0068f1.gif)

**Comment by jptissot** [comment]
I found the culprit... it's the cookie policy. 

https://github.com/OrchardCMS/OrchardCore/blob/ebfb9071d98f00c883e75f3132fe88dc618d8c61/src/OrchardCore.Modules/OrchardCore.Users/Startup.cs#L153

This should be set to `options.Cookie.SameSite = SameSiteMode.None;` for all external login providers. Currently, it's only being set for the OpenID module.

**Comment by deanmarcussen** [comment]
@jptissot you should just be able to call 
```
            services.ConfigureApplicationCookie(options =>
            {
              options.Cookie.SameSite = SameSiteMode.None;
            }
```

and modify the options anywhere in your pipeline (after users).

The Microsoft.Authentication feature should be able to do the same

**Comment by deanmarcussen** [comment]
The change to the users module was needed to be able to access the site through http with the google chrome changes, otherwise you can only get in via https.

so I would suggest adding to the external login providers (they all need https anyway I imagine?)

Can you try with `ConfigureApplicationCookie` instead of the cookie policy middleware. Should work as well
```
            services.ConfigureApplicationCookie(options =>
            {
                 options.Cookie.SameSite = SameSiteMode.None;
            }
```

**Comment by jptissot** [comment]
Is there value in only changing the `SameSiteMode.None` for the orchauth_ cookies as is done here? https://github.com/OrchardCMS/OrchardCore/blob/ebfb9071d98f00c883e75f3132fe88dc618d8c61/src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs#L84
