### ISSUE TITLE
How can I create a custom Stereotype?

### ISSUE THREAD

**Issue by jackliDev** [OrchardCMS/OrchardCore#6051]
For example, we can assign a content type a stereotype of "Widget". Can I create my own custom stereotype?

**Comment by deanmarcussen** [comment]
A Stereotype is a string identifier on a content type definition, so you can make any Stereotype you wish, and you are then able to use that Stereotype to query the content definition manager for types.

This is how the Flow and Widgets (and Menus) modules identify content types that can be consumed by them

Gitter is a really good place for questions like this https://gitter.im/OrchardCMS/OrchardCore
