### ISSUE TITLE
How to change the expiration of content localization cookies?

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#6059]
Hi!
How to change the expiration of content localization cookies?
I need to set for 1 day.
At the moment, the cookie lifetime is set to 14 days, this can be seen in the code at the link below
https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore.Modules/OrchardCore.ContentLocalization/Controllers/ContentCulturePickerControl62.

Is there a way around this limitation?

I ask the developers to add the cookie lifetime to the settings in the admin panel so that we can conveniently set it at our discretion.

**Comment by hishamco** [comment]
I will handle this, @sebastienros can we add this as a part of configuration or settings from the admin site or both?

**Comment by sebastienros** [comment]
Just configuration for this one.
