### ISSUE TITLE
Creating Theme Using Code Generation Templates does not result in a working theme

### ISSUE THREAD

**Issue by ChocoMachine** [OrchardCMS/OrchardCore#6063]
I had an attempt at creating a theme using https://docs.orchardcore.net/en/dev/docs/getting-started/theme/

My experience was the project files generated did not match those listed in the instructions. No menu liquid templates generated and no Recipes folder generated.

Theme did not appear on initialization page, (even thou referenced from CMS project). Thou the theme did appear as an option in the admin console. Updating to latest NuGet references didn't fix this.  I tired multiple times, deleting the App_Data folder between each try.

The generated theme, returns a "The Page Could not be found" message with a 404. I have added content Item and marked as landing page. Didn't make a difference.

I have created a theme using the developer branch source code, which I managed to get working as expected. I would prefer to work from nuget packages thou. Unless I missed something, I will have to work off the source code, which makes updating my dependencies more problematic.

That's my feedback..

Not forgetting ... Cheers for all the good work, :-)

**Comment by ChocoMachine** [comment]
Just an update:
 because the theme wasn't listed I chose blank site, then changed to the custom theme in the admin module. Then it returned the " not found 404"

I noticed that if I chose a different theme, such as Landing Page, then changed to the custom theme, the error never appeared.

I suspect if the theme appeared in the start up screen, it might behave differently and is ultimately influenced by previous themes, when changing themes.

**Comment by jtkech** [comment]
To appear in the setup screen your theme need to have a recipe file, look at our theme as an example, then in this recipe you have to enable your theme and make it the current one.

The blank site recipe is for headless site with only admin pages, so in the front end no page is found.

**Comment by deanmarcussen** [comment]
> My experience was the project files generated did not match those listed in the instructions. No menu liquid templates generated and no Recipes folder generated.

Yes, a generated theme only contains a layout template, and does not create a recipes folder, or recipe.

This as @jtkech says is why you do not see it on your setup screen.

The intention behind recipes, is that you would create one, after you have themed your site, and generated some content.

One quite good way to get started is with an empty theme, like you have generated, then to run some of the other recipes (the blog recipe for example), and start to bring in some of the templates from the blog theme to see how they all work, and are customisable.

Action : We should update the image in the docs to show an actual generated theme, not the one currently showing with the recipe, and menu links.

**Comment by ChocoMachine** [comment]
If the template generation tool also added a minimal recipe, it would be good, as new dev's will have a working template/theme (thou pretty empty) straight out of the box. Which would provide a better starting experience. I'm only just learning thou...
