### ISSUE TITLE
Question:What's the correct way to create a custom shape type in Orchard Core ?

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#6064]
Hi,
I'v create a custom shape type:

    dynamic layout = await _layoutAccessor.GetLayoutAsync();
    var afterRegister = layout.Zones["AfterRegister"];
    afterRegister.Add(await _shapeFactory.New.Shape123());

----

    public class Shapes : IShapeTableProvider
    {
        //Card Shape
        private const string Shape123 = "Shape123";

        public void Discover(ShapeTableBuilder builder)
        { 
            builder.Describe(Shape123 )
               .OnDisplaying(context =>
               {
                   IShape shape = context.Shape;
                   shape.Metadata.Alternates.Add($"{Shape123}");
               });
        }
    }

     
----
       services.AddScoped<IShapeTableProvider, Shapes>();

But it not works, throw Exception:`Shape type 'Shape123' not found`

**Comment by hishamco** [comment]
Please have a look to the navigation / menu module

**Comment by deanmarcussen** [comment]
You need to create the actual Shape somewhere (at the moment you're just describing it)

A view `Shape123.cshtml` is the easiest way

**Comment by RockNHawk** [comment]
![image](https://user-images.githubusercontent.com/3222379/80721232-930cc480-8b30-11ea-9f0a-110b9c54d863.png)

**Comment by RockNHawk** [comment]
Uh, I see, the Shape123.cshtml's file `Build Action` is `None`, should be `Embbed Resource`. 
😢😅
