### ISSUE TITLE
Layers UI suggested changes

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#607]
I had a conversation with Seb in gitter about this topic. He suggested to file an issue for future reference.
When using the Layers feature I find what I think are some usability issues.

I designed an sketch that addresses some of them so that you can evaluate if the changes make sense.  Please don't pay attention to the adminLTE that it is using. I used it only because it's easier for me.
![20170312_193929](https://cloud.githubusercontent.com/assets/2589629/23834879/e3a77bba-075d-11e7-942f-b7809568c219.gif)

The main differences with what we have right now:

- Wording: I think that It is better if we use "Layers and zones" as a title, instead of "Layers". If it is too long, I even prefer the word "Zones" over "Layers". I think the main purpose of the feature is placing widgets in zones. The ability to enable-disable them based on a rule seems a secondary thing to me. 

- Layers on the left. My personal preference.

- Ability to enable-disable the visibility of widgets on a given layer. That allows working on a single layer without being distracted by the others. Plus, the user can understand better what a layer is: a way to enable-disable visibility of widgets.

- Locked Layers: "Always" and "Never". I know the names are controversial, at least I did not included a "sometimes" one. :)
That is because I think that in many cases the user will come here only to place widgets in zones, without using the layers at all. So it makes sense having a "hardcoded" default one. 
The "never" layer can be useful for example to keep temporary widgets for wich the user does not want to loose track. 
The "never" layer can be used too to contain widgets that become "orphan" when the user deletes its layer. Right now the UI forces the user to remove the widgets before deleting the layer. But maybe is better if we simply delete the layer and warns the user that the widgets will be hidden.

- Move widgets from a layer to the other by simply drag and drop from the zones panel, to the layers panel. That would be a good addition. We talked about using a dropdown on the widget to change its layer , but drag and drop seems more natural.

- Finally, I think that the "undo" feature is not an optimal solution. It would be better if the user can work without saving changes, and only when everything is OK, click a "save" button. But I understand that this would be quite difficult to implement.

**Comment by DanielStolt** [comment]
Great mockup!

I agree with pretty much every suggestion you are making. The suggestion to enable/disable visibility per layer raises an interesting challenge though: what is the defined relationship to the hidden widgets when dragging and dropping to reorder only the **visible** widgets within a given zone? How will the visible widgets be ordered versus the hidden widgets?

**Comment by matiasmolleja** [comment]
Yes. To be honest I did not noticed that :(

I think that the question here is  : does the order of the widgets in this page affect the rendering in the frontend? 
I tried changing the order and it does not seem to affect the position of the widgets when rendered in frontend. Maybe I'm missing something.

If the order here does not affect the rendering maybe we can use a solution like this :
![positioning](https://cloud.githubusercontent.com/assets/2589629/23965365/07603dce-09b8-11e7-9ae5-f357380124ea.jpg)



I mean, the drag part indicates which widget are we moving, but on the drop side, we should only highlight the target zone as a whole. When the drop occurs we refresh the zone list with the default sorting. 
That default sorting can be alphabetic based on the widget name.Or, if we think is better, based on the widget layer name. That second sorting maybe makes things more clear to the user when switching layers on-off on the left sidebar.

**Comment by sebastienros** [comment]
The order of the widgets is respected in the output. I tried it multiple times and showed it during Harvest on purpose. Or it's broken.

**Comment by matiasmolleja** [comment]
I will test again then. Maybe I did something wrong. I can not test again right now. VS is updating now.
And then,  everything I wrote is wrong. :(

**Comment by matiasmolleja** [comment]
I think this can solve the issue. Or is it confusing?

![20170315_191004](https://cloud.githubusercontent.com/assets/2589629/23966529/fb7df7ea-09bb-11e7-8d58-c192efb7b965.gif)

**Comment by matiasmolleja** [comment]
OK, I don't know if it is broken or it is the expected behavior. When you use published content items positioning works right.
But if you save a draft to a widget, then it is the draft version which appears in the layers page. And then changing the position of that item does not not reflect anymore on the frontend. Until you discard or publish the draft.
Should I file an issue?
