### ISSUE TITLE
GraphQL Type Caching on RC1

### ISSUE THREAD

**Issue by johnrom** [OrchardCMS/OrchardCore#6071]
Apologies if this is fixed already (haven't had time to check latest `dev`). When modifying Content Parts and Content Types on `1.0.0-rc1-12542`, it seems like the types get cached and won't return new parts for a while. I ran into an issue where I performed some modifications, modified my queries to match, and wasn't getting the new parts back at all in GraphiQL or API queries. I woke up this morning and tried again, and they were there.

If I run into the issue again, I'll add more debug info / check against latest dev, but I can't now because it resolved itself overnight.

**Comment by carlwoodhouse** [comment]
would need some replication steps because the schema caching should be evicted on content definition change

**Comment by johnrom** [comment]
I'll see if I can replicate on latest `dev` tomorrow and give reproduction steps. I was specifically modifying Content Parts, adding new fields and modifying old fields' "Flatten Fields" setting if I remember correctly, and types with those Parts were not updating correctly, as though the Type was Cached even though the Parts were updated.

**Comment by carlwoodhouse** [comment]
oh interesting - must be something in the dynamic type builder going a miss; will see if i can get to the bottom of it (exact repo steps will still be good tho)

**Comment by johnrom** [comment]
Exact repro steps using Agency recipe.

- Enable GraphQL Feature
- Open GraphiQL
- Enter the following:

  ```
query MyQuery {
  landingPage {
    portfolio {
      contentItems {
        ... on Project {
          image {
            urls
          }
          category
          htmlBody {
            html
          }
        }
      }
    }
  }
}
  ```
- Run Query
- Edit Project Content Type
  - Edit HTML Part
    - [x] Collapsible

- Re-run query
  - Will receive error (schema generated correctly)
- Run modified query
  ```
query MyQuery {
  landingPage {
    portfolio {
      contentItems {
        ... on Project {
          image {
            urls
          }
          category
          html
        }
      }
    }
  }
}
  ```
- Notice that `html` is actually completely missing.
- Restart CMS Project
- `html` returns

**Comment by carlwoodhouse** [comment]
Cheers will take a look!

**Comment by Piedone** [comment]
This doesn't seem to be still a bug, so I'll close now. Please reopen if you still experience this.
