### ISSUE TITLE
How to deploy on Azure using Hybrid connection

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#6073]
Hey guys, I know that the settings for db can be configure on "app_data/sites/default/appsettings.json", on-prem this is not a problem but deploying to azure, I can't seem to get it to work. Any ideas on how to go around this? -Thank you.

**Comment by deanmarcussen** [comment]
Do you mean you don't have access to a volume using a Hybrid Connection?

We would need some details as to what you have tried, and what is actually not working.

There are alternatives to configuring your default host through Configuration, documented here https://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/

but you will still need an `App_Data` volume somewhere, for the other things that are stored in it.

**Comment by webmedia1012** [comment]
Hi Dean, thank you so much for replying quickly, when you say I don't have "access to volume using a hybrid connection" do you mean that app_data settings is not reaching the hybrid connection?.

Here's my setup: , so I go to azure resources->web, then went to Network and added a hybrid connection, then went ahead and setup my connection manager on our SQL box, everything went good connection and all, so I deployed a simple web app with DB connection and a simple query and everything works still at this point.

So I thought no problem, I can just deploy the Orchard Core CMS, but to my surprise, it's not getting connected. Nothing was showing on the site. Any ideas on how I can trace the logs? so I can see the actual error?

Thank you!
