### ISSUE TITLE
Adding widget to flowpart does not consider the IsNew context used from driver.

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#6076]
Adding a widget to a flow part with various fields that allow setting default values when new instance is created  (like numeric field, boolean field) is not respected.
Example:
Add a widget with a nemric field and set its default value to 100\. Then add the widget to the flow part .
The default value in editor is ignored.
This is because of 
 
https://github.com/OrchardCMS/OrchardCore/blob/acee23ef121a09568198ebda164d591ae9f084ed/src/OrchardCore.Modules/OrchardCore.Widgets/Views/ContentCard.cshtml#L22
 
setting the Isnew context variable to false.

**Comment by agriffard** [comment]
Sorry misread #6077. Reopening it.
