### ISSUE TITLE
Extend activate-links js to support nested items and action url's and add documentation

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/OrchardCore#6089]
Currently using the activatelinks.js script there is no way to expand a nested menu item if the active url is in a sub navigation item.

Also if you have an active menu link like for example /todo-items , and navigate to an action from there like /todo-items/Create or /todo-items/Edit/{id} and the url does not appear in menu, no item is active in the menu.

**Comment by Piedone** [comment]
I'd rather move the whole logic to determine which link is active to the server-side and use it to generate breadcrumbs too: https://github.com/OrchardCMS/OrchardCore/issues/5936

**Comment by MichaelPetrinolis** [comment]
I see but meanwhile I made a PR to extend the existing functionality (with javascript) and document how to use it from a theme :)

**Comment by deanmarcussen** [comment]
How would you handle the cache aspect of the menu if you moved things server side @Piedone ?

I have tended to use js like @MichaelPetrinolis is suggesting

**Comment by Piedone** [comment]
That's a good question, I simply didn't think about that :D. Apart from something trivial like caching per page, I can't quickly think of a good approach.
