### ISSUE TITLE
Beta2 version of OpenIddict throws an exception editing a Confidential Application

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#609]
Problems is it requires we provide a client secret for confidential applications but it doesn't provides an UpdateAsync overload accepting the client secret parameter.

On the other hand user could want to edit a confidential application without setting a new client secret, so current UpdateAsync overload without password shouldn't throw an exception, an simply update application without changing password.

**Comment by PinpointTownes** [comment]
I'll take care of it, thanks for reporting it.

**Comment by PinpointTownes** [comment]
Reopening, as we need to use the new `UpdateAsync` overload in Orchard.

**Comment by PinpointTownes** [comment]
Done: https://github.com/OrchardCMS/Orchard2/commit/c4ab7f306e2eef68a99486b5f9ba6866de09d5f8.

**Comment by jersiovic** [comment]
After the PR still is not possible to update a confidential app without providing a password because the EditOpenIdApplicationViewModel has this annotation [StringLength(100, MinimumLength = 6)] for the client secret.
When this validation fails the user doesn't see nothing because the input of the password and its text alerting of the error is hidden.
I'm going to add a PR for fixing it

**Comment by PinpointTownes** [comment]
Note that this attribute is ignored when the value is null (it's why it's often used with `[Required]`), so this shouldn't be a problem.

**Comment by sebastienros** [comment]
Try not to use data annotation, it's terrible with localization, prefer adding validation in the controller.

**Comment by jersiovic** [comment]
@PinpointTownes you are right that was not the problem. I have fixed it finally only improving js. https://github.com/OrchardCMS/Orchard2/compare/oauth2...%23609saveConfidentialApp?expand=1
@sebastienros I see, I will do it tomorrow.

**Comment by PinpointTownes** [comment]
@jersiovic was that fixed as part of the big PR?

**Comment by jersiovic** [comment]
No, after that I faced other problems testing web and I forgot about that. Now I'm a bit busy ... maybe on next days. But if you want to do it, feel free to assign it to you.

**Comment by sebastienros** [comment]
Can we close this?

**Comment by PinpointTownes** [comment]
The original bug in OpenIddict was fixed in March, but not sure about the JS issue. @jersiovic surely knows :sweat_smile:

**Comment by jersiovic** [comment]
Yes it looks I fixed it in the past the annotation `[StringLength(100, MinimumLength = 6)]` is not used anymore
