### ISSUE TITLE
Multi-lingual Website in Orchard Core

### ISSUE THREAD

**Issue by rajputshilpa** [OrchardCMS/OrchardCore#6097]
Hi There,
We have created a bilingual website using Orchard Core CMS with a local language along with English.
Is it possible in Orchard Core to manually enter the translated contents in translated version of web page? We are able to create the page using auto-translation but looking forward to be able to enter the contents manually. Is it possible?

**Comment by dodyg** [comment]
Add Localization Part to your content definition.

**Comment by rajputshilpa** [comment]
Thanks so much for the response. We tried to explore related documentation describing the implementation of the localization part but could't find any. Can you please suggest where can we find related documentation or can you throw some light on this process for us? 
Thanks!!

**Comment by dodyg** [comment]
Check this thread https://github.com/OrchardCMS/OrchardCore/issues/4121

**Comment by sebastienros** [comment]
> We have created a bilingual website using Orchard Core CMS with a local language along with English.

Please note that English is just a local language for most people in this world, and everyone knows that French is the only one true language 😄

**Comment by rajputshilpa** [comment]
> Check this thread #4121

Thank you! We'll surely check this out and will update.

**Comment by hishamco** [comment]
I will close this for now, feel free to reopen if you face any issues

Thanks
