### ISSUE TITLE
Cannot import content items after delete?

### ISSUE THREAD

**Issue by minhdn2** [OrchardCMS/OrchardCore#6098]
Hello,
Could anyone please help to advise me on how to import content items correctly?

In this scenario I'm using the same package.
For the first time, everything works perfectly fine. However, I **removed** content items and content types after that.
Then I tried to re-import again but this time, only **content types** are added to the CMS, all the **content items** are missing.

Please help,
Many thanks in advance.

**Comment by deanmarcussen** [comment]
Which version are you using?

Some major changes happened a few days ago to the import of content items from recipes, when you are repeating the import as you are.

Can you try with the dev myget feed?

**Comment by minhdn2** [comment]
Hi @deanmarcussen ,

I created the Orchard Core CMS with .NET Core CLI command. The .NET Core version of the project is **3.1**.
When initial the CMS, my setup was **Headless site** with **Sql Server** for database.
Then I publish the site to IIS.

After done creating content types and items, my deployment plan was:
![image](https://user-images.githubusercontent.com/35803003/81029510-70233d00-8eaf-11ea-825d-c1f22a2d06c4.png)

Could you please help to advise on how can I get and implement the new Orchard Core changes for my already running site? 
Not sure what you mean by "try with the dev myget feed"

Thanks.

**Comment by deanmarcussen** [comment]
The dev/myget feed is available at https://www.myget.org/F/orchardcore-preview/api/v3/index.json

or here in the docs for more information https://docs.orchardcore.net/en/dev/docs/getting-started/

**Comment by leone-91** [comment]
Hi,
I am dealing with the same kind of issue, so I am wondering if you found a solution since back then? The import functionnality is not working and I cannot find the recipe I created with my deployment plan in te "Recipes" Section so I wonder how I can upload the content of my published website with the content of my local cms.
Thanks in advance for your help!

**Comment by leone-91** [comment]
I managed to import the content items and definitions but it seems like I cannot use it. When I try to create a new content from one of my imported definition I have an error.

**Comment by sebastienros** [comment]
Please provide repro steps and errors that you are facing.
