### ISSUE TITLE
Add ContentMenuItem Custom ObjectGraphType for replacing the default DynamicContentTypeBuilder

### ISSUE THREAD

**Issue by stantoxt** [OrchardCMS/OrchardCore#6100]
The default `ContentMenuItem` selection for graphiql is too simple,it needs name and url selection for  graphql api.

**Comment by deanmarcussen** [comment]
@stantoxt try having a look at the `GraphQLContentOptions` where you can `IgnoreFields`, and `ConfigurePart`, and then maybe you can register a custom resolver

```
            services.Configure<GraphQLContentOptions>(options =>
            {
                options.ConfigurePart<ContentMenuItemPart>(partOptions =>
                {
                    partOptions.Hidden = true;
                });
            });
```

**Comment by stantoxt** [comment]
@deanmarcussen thanks,I will try it.

**Comment by Piedone** [comment]
Nothing else seem to be needed here.
