### ISSUE TITLE
Media Field loses value when publishing before Edit Page is fully loaded (RC1)

### ISSUE THREAD

**Issue by johnrom** [OrchardCMS/OrchardCore#6102]
In the AdminTheme, adding some media to a Media Field, publishing, then immediately publishing again will cause the media field to be empty if the second publish happens early enough in the page load process. 

This can happen any time a publish happens fast enough during page load, even with content that's been there for months. I discovered this because I recently updated some Content Types, went through and republished every page on a website to add the new Parts to GraphQL, then had no media left on the site 😢.

**Comment by hishamco** [comment]
@deanmarcussen did you notice that behavior before?

**Comment by sebastienros** [comment]
The generated html should at least have the previous state so the delay of the vuejs app doesn't impact it. Or it might be that vuejs updates the data multiple times, like reinitializing it then setting it.

**Comment by johnrom** [comment]
@skrypt I just reproduced this directly on Dev branch

- Windows 10 Pro (64-bit)
- Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- VS Code -> web debug
- Install using Agency Recipe + SQLite
- Edit main Landing Page
- Refresh the page, click the title and hit enter as fast as possible. 

Depending on the speed of your PC, you may initialize Vue faster than it's possible to perform this interaction, but if you keep trying or switch to a lower power machine it will be easier. It definitely seems like Vue initializes a temporary string while it does some math, or the value isn't loaded until Vue has initialized.

**Comment by Skrypt** [comment]
Ok so while the Vue.js component initialize itself the values are not present in the form hidden inputs leading to removing the images if you are for example double clicking the publish button.

2 things here. 

- We should probably initialize those hidden inputs outside of the Vue.js component to have them rendered before rendering the Vue.js component.

- We should use something like `e.preventDefault();` on form post to prevent double form posts.

**Comment by jtkech** [comment]
> Refresh the page, click the title and hit enter as fast as possible.

For infos just tried and i could repro by doing this

**Comment by johnrom** [comment]
Agree with server side filling of input values.

Never noticed the ability to double post, but duplicate submissions should be blocked on both the front-end and back-end. In WordPress, if a second person starts editing a post, the site keeps track of what is being edited and blocks a second person from editing a post (and asks them if they want to take over). If the lock version submitted with the form submit does not match, submit fails.

**Comment by jtkech** [comment]
@johnrom can you try #6361 (opened 13 days ago) to confirm (or not) that it fixes your issue, and then add a comment in this PR #6361 to describe your results, thanks
