### ISSUE TITLE
[Question] How to resolve media files URL to absolute URL.

### ISSUE THREAD

**Issue by lcf007** [OrchardCMS/OrchardCore#6103]
Orchard Core is using related URL for media files, so while integrating Orchard Core to another application, the URL of media files are resolved to the other application's URL.

Is there a simple way to use Absolute URL for media?

Thank you very much.

**Comment by Piedone** [comment]
Where exactly would you like to use the absolute URL? Also, what do you mean by integrating Orchard Core into another app?

You can inject the `IMediaFileStore` service and use its `MapPathToPublicUrl()` method to get the public URL of given file or do the same with the image tag helper by writing `<img assset-src="file path">`.

**Comment by deanmarcussen** [comment]
As @Piedone says it is unclear exactly what you are needing to do.

However it could be that the `CdnBaseUrl` configuration option for media could do what you are asking. It is intended to prefix media url's with an absolute path

https://docs.orchardcore.net/en/dev/docs/reference/modules/Media/#configuration

**Comment by lcf007** [comment]
Thank you, finally, I did some change while adding MediaFileStore, changed mediaUrlBase with full URL from HttpContext. CdnBaseUrl is not I wanted because I just want the current domain.
