### ISSUE TITLE
Is there anyway to customize the content item list item details at the admin?

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#6114]
Right now all the content item list just show the title of the content item. Is there a way to display extra information on the list item?

![customization-listing](https://user-images.githubusercontent.com/1761249/81082174-370cbc00-8ef3-11ea-8d12-8ee4490cc769.png)

**Comment by sebastienros** [comment]
Yes, with a driver that will add shapes for the SummaryAdmin display type.
All the zones are available in this file: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Views/Content.SummaryAdmin.cshtml

**Comment by dodyg** [comment]
I don't really get what a "driver" is. Is this a code base solution or can I just override some template?

**Comment by sebastienros** [comment]
Code-based. It's a component that injects shapes in zones when a content item is rendered.
Here is the one that injects the default buttons and text that you see in the admin list view:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Drivers/ContentsDriver.cs#L51-L54

And this one adds the culture from the Localization Part:
https://github.com/OrchardCMS/OrchardCore/blob/f4c4c31dd1935b4db57abbef1ddbfd7bab6bba40/src/OrchardCore.Modules/OrchardCore.ContentLocalization/Drivers/LocalizationPartDriver.cs#L37

**Comment by dodyg** [comment]
OK thanks. Let me try them.
