### ISSUE TITLE
Add docs to solution

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6116]
While the docs are currently part of the folder structure of the solution, what's more, they're under the src folder too, the docs files are not part of the VS solution. This has the following negative implications:

- Doc files are harder to edit from VS. Them being Markdown files mostly you can edit them with any text editor of course, but you could use VS as a text editor too (like by using the excellent [Markdown Editor](https://github.com/madskristensen/MarkdownEditor) extension to provide real-time rendering).
- Docs are less discoverable this way, including that they can go easier out of sync with the code: If the docs are part of the solution then they'll also show up in search, both when you're searching for a solution and when you're renaming something. This would make the utility and maintainability of the docs easier.
- Search and replace would be easier via VS (of course, you can do this otherwise but in VS everything is there for this too).

Suggestion: Adding a whole folder to a solution is as a solution folder is not feasible since it would need to be kept up to date with every new file added, like with the old csproj format. Instead, we could have a "docs" solution folder with a single `OrchardCore.Docs` csproj, containing nothing than the content of the docs folder. While a bit hackish I don't see a better solution due to the capabilities of the sln file format.

**Comment by agriffard** [comment]
I like the idea.

**Comment by agriffard** [comment]
![image](https://user-images.githubusercontent.com/703248/81119999-2462a900-8f2c-11ea-9ff7-4ccf110882a6.png)

**Comment by Piedone** [comment]
Perfect!
