### ISSUE TITLE
Workflow Liquid evaluator: JavaScriptEncoder vs HtmlEncoder

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/OrchardCore#6122]
I'm using workflows to send a bunch of emails when an order is placed.

Liquid is used to construct the body of the emails. The input data has `"Country": "België"` that I'm rendering with `{{order.UserProfile.Country}}<br />`.

However, workflow liquid evaluator is using JavaScriptEncoder rather than HtmlEncoder, see https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Workflows/Expressions/LiquidWorkflowExpressionEvaluator.cs#L39

This results in an email with `Belgi\u00EB` in the body.

In some case using JavaScriptEncoder could make sense (as workflow uses Javascript) but in this context HtmlEncoder would be the preferred option.

I think developers should be able to choose which encoder to use in a workflow.

**Comment by jptissot** [comment]
I had the same issue. I believe there was a way to fix it with either `| raw` or `| html | raw`, I forget. 

I agree that some Task / Activity fields should use the HtmlEncoder by default.

**Comment by netwavebe** [comment]
@sebastienros are you sure this issue needs to be closed?

`| raw` does not produce valid html; it outputs `België` but it needs to be `Belgi&euml;`

**Comment by netwavebe** [comment]
In my case, it's the confirmation email of an order, using 292 lines of liquid with data from various sources (product, customer, ...).

There are a lot of places where the JavaScriptEncoder might produce invalid html (product description, client name or address, ...).

I know it's possible to write a custom liquid filter, but I would need to use it almost everywhere.

In the case of an email activity, using HtmlEncoder would make more sense I think.

**Comment by sebastienros** [comment]
| html_encode | raw

**Comment by sebastienros** [comment]
So you are using an Email task? And the body of the email contains liquid?
So yes it should not have been evaluated by the workflow expression.

Reopening to understand why it has been.

**Comment by netwavebe** [comment]
Correct, I'm using an email task and the body contains liquid. This is evaluated by LiquidWorkflowExpressionEvaluator that uses JavaScriptEncoder.

**Comment by deanmarcussen** [comment]
I think the workflow evaluator needs an overload for the encoder (defaults to JavaScript) and the email task can provide the html encoder.
Also the javascript encoder should be loaded from di.

**Comment by sebastienros** [comment]
@deanmarcussen that's it. I assume that when I refactored all the encodings I thought that this service was only called by tasks that were using json. But I see that some other tasks still need the "workflow" properties in the templates. So we should require an encore when calling it. And it's logical to inject the javascript decoder as we do it for the html encoder already.

**Comment by sebastienros** [comment]
Currently working on the PR
