### ISSUE TITLE
I created a Blank Site, I enabled Taxonomies from the feature, but there is no Taxonomy in ContentType, what should I do?

### ISSUE THREAD

**Issue by fuxiaojun0203** [OrchardCMS/OrchardCore#6132]

**Comment by hishamco** [comment]
I think here's a taxonomy part that you need to attach to your content type, @deanmarcussen correct me if I'm wrong

**Comment by deanmarcussen** [comment]
There is no need to add a taxonomy part to anything.

When the feature is enabled you should see New -> Taxonomy list in the Admin area.

If you do not see this can you check your logs for an error

**Comment by hishamco** [comment]
> There is no need to add a taxonomy part to anything.

I thought a part is needed for everything, that's what I know from `LocalizationPart` ;) that's why I ping you coz I never used taxonomies

**Comment by hishamco** [comment]
In addition with what Dean's said earlier, [this](https://www.davidhayden.me/blog/taxonomies-in-orchard-core-cms) is a very detail blog post for using taxonomies

**Comment by fuxiaojun0203** [comment]
![11](https://user-images.githubusercontent.com/25946521/81359368-8af1ed80-910b-11ea-84de-ad7c631b355c.png)
![22](https://user-images.githubusercontent.com/25946521/81359371-8cbbb100-910b-11ea-9412-b248601599d4.png)
![33](https://user-images.githubusercontent.com/25946521/81359376-8f1e0b00-910b-11ea-98cb-b1047c5b9ca9.png)
