### ISSUE TITLE
I enabled Taxonomies from feature, but there is no Taxonomy in the new creation, which prevents me from creating a new Taxonomy.

### ISSUE THREAD

**Issue by fuxiaojun0203** [OrchardCMS/OrchardCore#6134]
![11](https://user-images.githubusercontent.com/25946521/81359495-db694b00-910b-11ea-8500-8dda98b1f2b6.png)
![22](https://user-images.githubusercontent.com/25946521/81359501-dd330e80-910b-11ea-9081-a7b9330bbc8c.png)
![33](https://user-images.githubusercontent.com/25946521/81359504-ddcba500-910b-11ea-9749-3fe425306ce9.png)

**Comment by hishamco** [comment]
I think we already replied in #6134 but we didn't  get any comment from your side
