### ISSUE TITLE
trumbowyg media url: strange image moltiplication when add more than one image

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#6137]
Hi guys, 

I have check this issue in my OC installation. If I add an image one time in the trumbowyg html editor configured to add image by url it work well, but if I add another image the editor add multiple image.

![issue_trumbowyg_media_url](https://user-images.githubusercontent.com/2736009/81420295-12f9e680-9150-11ea-8466-87a170772caa.gif)

I believe is necessary to edit `trumbowyg.media.url.js` to delete contents in the trumbowyg range before add another image.

If you want I can do a PR about it. 

I'm working on the latest dev branch.

**Comment by hishamco** [comment]
@PiemP of course you can send a PR for it

**Comment by PiemP** [comment]
done ;-)
