### ISSUE TITLE
HttpRequestFilterEvent can't be used as a waiting activity

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#6141]
Can only be used as a starting activity

I fixed it and will do a PR

**Update:** Fixed by #6142

**Comment by sebastienros** [comment]
IS this about ensuring it "can only be used as a starting activity" or that it can also be used as a waiting activity.

**Comment by jtkech** [comment]
@sebastienros 

> IS this about ensuring it "can only be used as a starting activity" or that it can also be used as a waiting activity.

**It can also be used as a waiting activity.**

**Comment by jtkech** [comment]
Also fixed by #6156
