### ISSUE TITLE
Media module building error

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#6143]
Hi!
An error appears while building the media module
Error	CS0535	'MediaResizingFileProvider' does not implement interface member 'IImageProvider.ProcessingBehavior'	
 in the file MediaResizingFileProvider.cs
The latest version of the module, connected today.
http://skrinshoter.ru/s/090520/lINfGfMy?a
module dependency list
    
![image](https://user-images.githubusercontent.com/20708134/81459591-9522f300-91c2-11ea-8b8e-07a6dbb32186.png)

How to fix?

**Comment by niknikita** [comment]
Figured out what was the problem
The error appears if you update the SixLabors library. ImageSharp to the latest version (1.0.0-rc0001).
It works stably with the beta version (1.0.0-beta0009)

**Comment by deanmarcussen** [comment]
For info the `ImageSharp.Web` upgrade to ImageSharp.RC1 has already been performed on dev, and (seems to be) working fine.

Suggest you may need to clean and rebuild to get the correct nugets installed. Or if you have built a custom version of the media module, update it to as per the latest dev source code, where we have implemented the new interface method
