### ISSUE TITLE
Graphiql NO SCHEMA AVAILABLE

### ISSUE THREAD

**Issue by niknikita** [OrchardCMS/OrchardCore#6148]
Hi!
Help deal with Graphiql
The explorer section does not display the circuit. How to fix?
![image](https://user-images.githubusercontent.com/20708134/81492427-4d32c780-92b9-11ea-81e4-bd2502935583.png)

When executing a request, such an error appears
![image](https://user-images.githubusercontent.com/20708134/81494938-642fe480-92ce-11ea-8a6f-000fe14cf1a4.png)

**Comment by jptissot** [comment]
Do you have a lot of custom content definitions ?

**Comment by deanmarcussen** [comment]
The error here is (I suspect) because you have added a `Content Field` to the `LinkMenuItem`, so it is now being registered dynamically, and by it's own registration.

You should be able to exclude the dynamic registration by using the

```
            services.Configure<GraphQLContentOptions>(options =>
            {
                options.ConfigurePart<LinkMenuItemPart>(partOptions =>
                {
                    partOptions.Hidden = true;
                });
            });
```

**Comment by niknikita** [comment]
> Do you have a lot of custom content definitions ?

yes

**Comment by niknikita** [comment]
> The error here is (I suspect) because you have added a `Content Field` to the `LinkMenuItem`, so it is now being registered dynamically, and by it's own registration.
> 
> You should be able to exclude the dynamic registration by using this (or a variation of it)
> 
> ```
>             services.Configure<GraphQLContentOptions>(options =>
>             {
>                 options.ConfigurePart<LinkMenuItemPart>(partOptions =>
>                 {
>                     partOptions.Hidden = true;
>                 });
>             });
> ```



> The error here is (I suspect) because you have added a `Content Field` to the `LinkMenuItem`, so it is now being registered dynamically, and by it's own registration.
> 
> You should be able to exclude the dynamic registration by using this (or a variation of it)
> 
> ```
>             services.Configure<GraphQLContentOptions>(options =>
>             {
>                 options.ConfigurePart<LinkMenuItemPart>(partOptions =>
>                 {
>                     partOptions.Hidden = true;
>                 });
>             });
> ```

Added your code, unfortunately the problem persists

**Comment by niknikita** [comment]
> > The error here is (I suspect) because you have added a `Content Field` to the `LinkMenuItem`, so it is now being registered dynamically, and by it's own registration.
> > You should be able to exclude the dynamic registration by using this (or a variation of it)
> > ```
> >             services.Configure<GraphQLContentOptions>(options =>
> >             {
> >                 options.ConfigurePart<LinkMenuItemPart>(partOptions =>
> >                 {
> >                     partOptions.Hidden = true;
> >                 });
> >             });
> > ```
> 
> Added your code, unfortunately the problem persists

but the following error appeared
But I have many custom content definitions
![image](https://user-images.githubusercontent.com/20708134/81598188-b9f8af80-93e8-11ea-8544-fc289aa53e6d.png)

**Comment by niknikita** [comment]
> The error here is (I suspect) because you have added a `Content Field` to the `LinkMenuItem`, so it is now being registered dynamically, and by it's own registration.
> 
> You should be able to exclude the dynamic registration by using this (or a variation of it)
> 
> ```
>             services.Configure<GraphQLContentOptions>(options =>
>             {
>                 options.ConfigurePart<LinkMenuItemPart>(partOptions =>
>                 {
>                     partOptions.Hidden = true;
>                 });
>             });
> ```

Thank you very much!! Everything worked!)
