### ISSUE TITLE
Workflow: When a content record created, send email to a recipient.

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#6149]
I need a workflow to send email when a content record created.
How can I set the email message from content record's fields? i.e.:
email.title = content record's title;
email.from = content records's 'from' field
email.to= content records's 'to' field
email.subject = content records's 'subject' field
email.body= content records's 'body' field

![image](https://user-images.githubusercontent.com/16193516/81498825-f92ae180-92be-11ea-850a-915901114459.png)

**Comment by hishamco** [comment]
You can set the email fields from the workflow module, but in case if you want to fill them from contents I may ping @jtkech because it may requires to go to the code to achieve that

**Comment by dodyg** [comment]
@orchardc  read this case https://github.com/OrchardCMS/OrchardCore/issues/6027#issuecomment-619513468

**Comment by orchardc** [comment]
> You can set the email fields from the workflow module, but in case if you want to fill them from contents I may ping @jtkech because it may requires to go to the code to achieve that

Thanks, the workflow module has already enabled. I can't see any options to get content value  from previous step.

**Comment by jtkech** [comment]
@orchardc as i remember so not sure of the details

You could define e.g. a **`Message` content type** having some fields, here as an example a **`TextField` named `Subject`**. Then when you create a content item of this content type, a `ContentCreatedEvent` is triggered, so you could use this event to start a Workflow. Then, because the created content item has been passed to the workflow input property, the `SendEmailTask` will be able to retrieve and use it.

Then you will have to edit the `SendEmailTask` to define its properties that support the Liquid syntax which allows to retrieve contextual data. E.g. to retrieve the email subject.

    {% assign contentItem = Workflow.Input["ContentItem"] %}
    {{ contentItem.Content.Message.Subject.Text }}

**Comment by orchardc** [comment]
Hi @jtkech ,

I have a content type call: "Message", there is a field call "Body"
![image](https://user-images.githubusercontent.com/16193516/81545923-875fa000-9371-11ea-8e7b-b32f038ae927.png)

I tried the code as pictured, but received: **Fault Message - Object reference not set to an instance of an object.**

![image](https://user-images.githubusercontent.com/16193516/81545831-64cd8700-9371-11ea-9df4-a0f0a5f1e665.png)

**Comment by orchardc** [comment]
I have a content type call "Message", in which there is a field call "Body"
![image](https://user-images.githubusercontent.com/16193516/81546007-a9592280-9371-11ea-9a86-5448456e80e9.png)
I have the following workflow designed, very simple:
![image](https://user-images.githubusercontent.com/16193516/81546281-0bb22300-9372-11ea-9bd0-4c5ae1f66eec.png)

In the Email Task:
![image](https://user-images.githubusercontent.com/16193516/81546139-d574a380-9371-11ea-8cf4-f4da4c3fdb1b.png)

When it runs, workflow has **Fault Message** **Object reference not set to an instance of an object.**

**Comment by jtkech** [comment]
Maybe just because you don't provide any `Recipients` and `Subject` that are required fields.
For testing you can set simple values without using Liquid syntax.
Try first to also set the body without liquid syntax, to see if it works

Which version do you use? Depending on your version, in place of

    Workflow.Input["ContentItem"].Content.Message.Body.Text

Try one of the following

    WorkflowExecutionContext.Input["Content"].Content.Message.Body.Text
    Input["Content"].Content.Message.Body.Text
    Content.Content.Message.Body.Text

**Comment by orchardc** [comment]
@jtkech , thank you so much, indeed because I didn't provide the required subject field!!
Now it's working with your original soluion: Workflow.Input["ContentItem"].Content.Message.Body.Text

Can I ask, at the last step, after email sent, I'd like to delete the Message content. But what should put into the Expression field?
![image](https://user-images.githubusercontent.com/16193516/81608619-814bdc80-93ce-11ea-8da2-7699c1b0807d.png)

Thanks!

**Comment by jtkech** [comment]
In this context the script expression could be `input("ContentItem")` or `correlationId()`

But here the created content item has not been persisted yet, so you will delete nothing. Hmm, one solution is to defer the delete task by using a timer event before. But the timer event used as a waiting activity doesn't work in a workflow that is correlated to a content item, so before the timer event you will have to use a `Correlate` task with an empty string value.

So, if you set the timer to one minute (the granularity of the timer event), your message content item will be deleted in one or 2 minutes.

Here the workflow

- `ContentCreatedEvent` + `EmailTask`

- `CorrelateTask` with a `Value` equal to `""`

- `Timer event` (not marked as a starting activity) with a one minute expression `* * * * *`

- `DeleteContentTask` with an expression equal to `input("ContentItem")`. Note: Here we can't use the `correlationId()` as it has been cleared by the correlate task.

**Comment by orchardc** [comment]
Thank you very much jtkech, this works like a charm! :)
