### ISSUE TITLE
How to use the "url (url: String): Boolean" method in Layers?

### ISSUE THREAD

**Issue by fuxiaojun0203** [OrchardCMS/OrchardCore#6158]

**Comment by Piedone** [comment]
Well, what's your confusion? `url("/my/url")`

**Comment by sebastienros** [comment]
Maybe add a few examples in the doc:
https://docs.orchardcore.net/en/dev/docs/reference/modules/Layers/

**Comment by agriffard** [comment]
No that there is a Rules module, add an example in the corresponding doc?
https://docs.orchardcore.net/en/dev/docs/reference/modules/Rules/

**Comment by Piedone** [comment]
We use the Rules module now where this is done via the UI.
