### ISSUE TITLE
Add ContentSaveEvent

### ISSUE THREAD

**Issue by lazcool** [OrchardCMS/OrchardCore#6159]
It would be useful, if within workflows, an event was published when a draft version is saved (after having passed server side validation).

Here's the [suggestion to create this issue](https://gitter.im/OrchardCMS/OrchardCore?at=5eb4c2f99f0c955d7daf845d) (by @jtkech).

**Comment by jtkech** [comment]
Added on my list but first i have to finalize some other PRs that may be related

**Comment by sebastienros** [comment]
@jtkech didn't you fix this by having the ContentItemVersioned event?

**Comment by jtkech** [comment]
No, i only fixed the fact that the already existing `ContentItemVersioned` event was not triggering the already existing `ContentVersionedEvent` WF event
