### ISSUE TITLE
How to automatically set up emails for AzureAD external users?

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#6161]
We are trying to set up the following scenario: We want our AzureAD users to be able to automatically create their users in OC without having to re-enter their names, emails and a local password, since that all is already in AD.

We have enabled the following features:
* Users Registration
* Microsoft Azure Active Directory Authentication
* Forms (just in case)

In the Settings -> Registration settings we have selected:
* Configure users registration : AllowOnlyExternalUsers
* [x] Use a script to generate userName based on external provider claims
```
/* Uncomment to map AzureAD */
switch (context.loginProvider) {
    case "AzureAD":
        //context.userName = "azad" + Date.now().toString();
        context.externalClaims.forEach(claim => {
            //context.userName = claim.subject;
            log("Warning", "Claim:(subject:" + claim.subject + ", type:" + claim.type + ", value:" + claim.value + ")");
            if (claim.type === "name") {
                context.userName = claim.value.replace(/ /g,".").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
            }
            if (claim.type === "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn") {
                context.email = claim.value; /* THIS DOES NOT WORK */
            }
        });    
        break;
    default:
        log("Warning", "Provider " + loginProvider + " was not handled");
        break;
}
```
* [x] Do not ask username 
* [x] Do not ask email address
* [x] Do not create local password for external users

We've managed to work around the issue with diacriticts and spaces in the user's names with the line
`context.userName = claim.value.replace(/ /g,".").normalize("NFD").replace(/[\u0300-\u036f]/g, "");`

We've also placed a line for logging all possible claims and be able to check their values for our AD App registration. The output is something like this (actual values obfuscated for security):

```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {area = "OrchardCore.Users", action = "ExternalLoginCallback", controller = "Account"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] ExternalLoginCallback(System.String, System.String) on controller OrchardCore.Users.Controllers.AccountController (OrchardCore.Users).
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:aio, value:AZURE-INTERNAL-ONLY-NUMBER-HERE)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.microsoft.com/claims/authnmethodsreferences, value:pwd)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname, value:My Users SurName)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname, value:My UserName)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:name, value:My UserName My Users SurName)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.microsoft.com/identity/claims/objectidentifier, value:GUID-NUMBER-HERE)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:onprem_sid, value:SID-NUMBER-HERE)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:rh, value:ANOTHER-NUMBER-HERE)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier, value:NAME-IDENTIFIER-NUMBER-HERE)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.microsoft.com/identity/claims/tenantid, value:OUR-DIRECTORY-TENANT-ID)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, value:myusername@mydomain.com)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn, value:myusername@mydomain.com)
warn: OrchardCore.Scripting.Providers.LogProvider[0]
      Claim:(subject:myusername@mydomain.com, type:uti, value:ANOTHER-INTERNAL-CLAIM-USED-BY-AZURE)
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
      AuthenticationScheme: Identity.Application signed in.
```

As you can see the email of the user is passed along in every claim (in the subject) and also in the value of claims of the following types:
* http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
* http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn

There is no trace of any http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress claim, that might be the one you are expecting in order to use it and automatically insert the email address for the new user.

Is there anything that we could do in our script in order to fix the line marked with *THIS DOES NOT WORK* so that we could set the email for the new user being created?

Thanks.

**Comment by jptissot** [comment]
I have azure AD setup with orchard core and the email comes through. It may be a setting in the azure application. I think it worked after allowing email access in the azure portal.

**Comment by jagbarcelo** [comment]
Can you please elaborate a bit? Do you recall where that 'allowing email' might be in the Azure portal?

So far, I have set up a new **App registration** for *My organization only*, set up the *Redirect URIs*. In the Manage->Authentication section, *Implicit grant* is set to *[x] ID tokens* only.

Everything else is at their default values. Cannot see anything about *email access* in any of the sections of the **App registration**.

Thanks.

**Comment by jptissot** [comment]
This is what I had to set: 

![image](https://user-images.githubusercontent.com/4681586/81625361-accac900-93c6-11ea-869e-178abb4e3b04.png)
