### ISSUE TITLE
Feature Request: Subscription and Ecommerce Module

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#6168]
I would like a basic subscription module built into OC that allows a user to sing up for a paid area after they have subscribed and paid.  The module can provide hooks or a document how to integrate ecommerce into it.

I would also like an ecommerce module that is decoupled from the subscription module in case people want a different version of ecommerce.

**Comment by jptissot** [comment]
I believe https://github.com/OrchardCMS/OrchardCore.Commerce is the Commerce module that is being developped.

**Comment by JoshTango** [comment]
thanks
