### ISSUE TITLE
MediaField: multiple fields in one contentitem cause DOM multiple Id error

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#6172]
Hi guys, 

I have a contenttype with multiple MediaField and I see, in my browser console, that it cause an error on DOM structure because every media field have some hidden input used for validation messages (I suppose) with the same value in the Id attribute.

If you want, I can do a PR to solve this issue: if doesn't exist any other activity that would fix on this problem.

The issue come from MediaFieldEditLocalization.cshtml file in the relative module.

PS. The best solution is to put MediaFieldEditLocalization.cshtml in the "Edit template" for all the MediaField in the contentitem but now I don't know how to do that

**Comment by PiemP** [comment]
Hi guys,

I have found another issue with Media in Attached mode that disable the possibilities to move selected text or a images inside a textarea or into Html editor. Now I'm working on a PR #6167, I have to create another PR to solve this issue or I can merge the solution for this problem into the PR #6167?

Thank you

**Comment by deanmarcussen** [comment]
Not sure of the issue you have found here @PiemP but one way to avoid the multiple id warnings (though these are generally just warnings, not errors), so I'm not sure if it is your issue) on the `MediaFieldEditLocalization` is to add it via a shape provider just once, like is done for the modals

https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore.Modules/OrchardCore.Html/Media/MediaShapes.cs

But again, not sure of the details of the actual issue you are experiencing, so this may not be relevant

**Comment by PiemP** [comment]
@deanmarcussen The problem with the DOM, at the moment, doesn't give other problems than the remarks on the browser console, but It could create issue in usage because the `MediaFieldEditLocalization` issue is all over MediaField code...
At this moment I don't have repro because I'm working on the second issue I have found in  `MediaField-Attached.Edit.cshtml` file. In the `initializeAttachedMediaField` function are bind and prevented the `drop` and the `dragover` events over all the DOM document and this cause the impossibilities of move selected image and selected text inside html editor in the same contentype. 

I'm looking a the `MediaShapes` to repro this good practice. 

Hope all I have write is understandable.

Thank you.

PS. I'm preparing a new PR for fix all this issue in the MediaField.

**Comment by agriffard** [comment]
Reopened because @sebastienros argued about the related PR during the meeting that the use of the shapes was a complex solution and might be hard to understand why we did it like this in the future.            
Ex: `editor.Metadata.Wrappers.Add("Resource_Wrapper__MediaField");`

**Comment by agriffard** [comment]
Also, @PiemP please find shorter titles for your future PRs ;-)

**Comment by PiemP** [comment]
> Also, @PiemP please find shorter titles for your future PRs ;-)

I try to do my best ... be clear with words is not my feature 🤣

>Reopened because @sebastienros argued about the related PR during the meeting that the use of the shapes was a complex solution and might be hard to understand why we did it like this in the future.
Ex: editor.Metadata.Wrappers.Add("Resource_Wrapper__MediaField");

If you have some example in code I could try to do a PR to fix the loading of multiple scripts and localization labels with the preferred method.

**Comment by deanmarcussen** [comment]
Mostly it is some formatting issues @PiemP and with the wrappers.

It is easier to just do a pr than explain, so I will do one, and put some comments on so you can review, and perhaps test
