### ISSUE TITLE
Invalid fields are not highlighted while editing content item.

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6174]
When editing content item in admin - if fields/parts has validation error validation summary is displayed but invalid fields/parts are not highlighted.

### Fields

- [x] TextField
- [x] ContentPickerField
- [x] LocalizationSetContentPickerField
- [x] HtmlField
- [x] LinkField
- [x] NumericField
- [x] YoutubeField
- [x] MarkdownField
- [x] MediaField
- [x] DateField
- [x] TimeField
- [x] DateTimeField

### Parts

- [x] TitlePart
- [x] HtmlBodyPart  
- [x] LiquidPart
- [x] MarkdownPart

**Comment by jptissot** [comment]
And flow / bag are not highlighted properly. It would be ideal if we could click the summary and it would open the flow / bags

**Comment by ns8482e** [comment]
@jptissot It's due to incorrect ModelState key, I tried to fix some of them in PR #6175
