### ISSUE TITLE
Missing dependencies or checks on disabling features.

### ISSUE THREAD

**Issue by DjTeo** [OrchardCMS/OrchardCore#6179]
Default headless recipe if I disable 'Roles' feature or 'Users' Feature (maybe and others), Orchard throw an unhandled exception: 

> InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.IRoleStore`1[OrchardCore.Security.IRole]' while attempting to activate 'Microsoft.AspNetCore.Identity.RoleManager`1[OrchardCore.Security.IRole]'

Maybe remove the ability to disable core features.
I don't know how to enable it again so I can continue to work on my site.

I want to propose an Idea with this in mind. When a module fails to load and throws an exception have the ability to disable that module.

**Comment by hishamco** [comment]
It make sense, if the one module depends on others

**Comment by DjTeo** [comment]
> It make sense, if the one module depends on others

Shouldn't prevent you from disabling it or disable others modules too?

**Comment by sebastienros** [comment]
Looks like a module depends on it. We need to understand what component is failing in this case, the stack trace is too small here.

**Comment by sebastienros** [comment]
And if we don't want to depend on a specific module, at least have a default implementation that does nothing (for IRoleService in this case)

**Comment by Piedone** [comment]
This doesn't seem to be still a bug, so I'll close now. Please reopen if you still experience this.
