### ISSUE TITLE
Expose Route property on HttpRequest through Liquid

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/OrchardCore#6184]
Similar to the way the `HttpRequest` object is exposed via properties like `QueryString`, `Query`, `Cookies` etc, we should expose `Route`. Which becomes extra useful in combination with #5305

**Comment by agriffard** [comment]
Would we be able to create a SQL Query that lists contents for a specific month/year (ex: blog posts) and then specify that a url like `archive/2020/06` would call a Liquid page passing the parameters to the query and displaying the results?

/cc @deanmarcussen
