### ISSUE TITLE
[Question] Why ask for email on ResetPassword screen

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#6188]
Why is it necessary to ask for the user's email on the Reset Password page ? Would it be possible to remove the email from the form to improve the User Experience ?

**Comment by Piedone** [comment]
I'm not sure I'm following. How would we otherwise know who the user is?

**Comment by jptissot** [comment]
I mean, after sending the token, on the page they reset the password after having recieved a link. We ask for the email again along with both the new password fields.

**Comment by Piedone** [comment]
I see. However, the ASP.NET `UserManager.ResetPasswordAsync()` needs a user object. Since the token is only handled by `UserManager` we'd need to store the token too, under the user, to be able to retrieve the user by just the token.
