### ISSUE TITLE
Non-module library shows up as module feature on admin

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6190]
Take [this project](https://github.com/Lombiq/Helpful-Libraries/tree/orchard-core-preview) which is a class library referencing Orchard Core packages but it's not a module, it doesn't have a manifest. Nevertheless, it'll show up on the Orchard admin under Configuration/Features:
![image](https://user-images.githubusercontent.com/1976647/81991421-7a78d000-9641-11ea-84dd-f355ada3c2fc.png)
This also happens without it being a direct dependency of the root web project.

I think assemblies without a manifest (i.e. at least a `Module` attribute) shouldn't show up here.

**Comment by hishamco** [comment]
I though that any assembly that has `ManifestAttribute` should be discoverable as a module

**Comment by jtkech** [comment]
Yes, this is because @sebastienros didn't want to force people to have to create a manifest file, just have to reference `OrchardCore.Module.Targets`, at some point we were creating this file automatically, now it's no more needed.

So, if your project references `OrchardCore.Module.Targets` it becomes a module.

**Comment by Piedone** [comment]
I see, thanks for explaining. However, I don't see how this is good.

If you don't have a manifest then there's a lot of metadata missing about the module so UX aspects aside (you'll have an uncategorized, technically named feature show up without a description) the lack of dependency declarations cane make this unpredictable too.

**Comment by jtkech** [comment]
Yes i agree and i have no closed opinion ;)

It was to allow people to easily do a module from a simple project by only referencing `OrchardCore.Module.Targets`. And yes i agree, as soon as you need a dependency, you need to use the `Module` attribute, **can be in any csharp file, not necessarily in a manifest file**.

**Comment by sebastienros** [comment]
If it's not a module (i.e. it doesn't have a reference to the targets) it shouldn't be displayed as a module.

**Comment by Piedone** [comment]
It does have a reference to Targets. My point is, however, that without a manifest a library shouldn't be considered a module.

**Comment by sebastienros** [comment]
A library with a Module.Targets is a module. Remove it if you don't want the library to be a module.

**Comment by Piedone** [comment]
Well, that's a question of definition. What I'm saying is that without a manifest that library won't be properly usable as a module anyway.

I wanted to say that Module.Targets acts as a useful meta-package shortcut to multiple other packages but I stand corrected, it doesn't do this. I confused it with something else.

**Comment by Piedone** [comment]
Let's leave this as is.
