### ISSUE TITLE
[Feature] Implement wordpress shortcodes

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#6199]
These code snippets allow content editors to inject specially constructed html like media, twitter embeds, youtube videos, ... 

https://wordpress.com/support/shortcodes/

Right now a content editor would need to use liquid tags. This can also be done with pre-existing shortcodes like `[media]` (https://github.com/OrchardCMS/OrchardCore/pull/6016).

The suggestion is 
- To enhance the `IShortCodeService` with a service that lists existing  shortcodes and their usage. This would allow features that allow for them to provide a window with the list of available ones.
- Create an admin view where "custom" shortcodes can be created or modified. This would allow to create custom ones, using Liquid.
- Create a Shortcode widget that allows to reuse these shortcodes in Flow Part or layers.

**Orchard 1 Tokens**

This could be seen as very similar to token in O1.

One advantage is that the shortcodes don't have the same scope, for instance autoroute will still use Liquid. Shortcodes are targetting content editors.

Another difference is that they should be editable, such that complex ones can be created easily by an admin. This means that if a shortcode is missing a useful argument, or needs to be lower cased, a custom one can be added, or an existing one edited. 

They can be imported/exported.

TODO:
Evaluate all issues that tokens have in O1 and see how shortcodes reflect with it

**Comment by sebastienros** [comment]
From https://developer.wordpress.org/reference/functions/add_shortcode/#more-information

> The shortcode callback will be passed three arguments: the shortcode attributes, the shortcode content (if any), and the name of the shortcode.
Shortcode attribute names are always converted to lowercase before they are passed into the handler function. Values are untouched.

A shortcode parser should allow for inner shortcodes, building a tree that is processed in post-order (https://en.wikipedia.org/wiki/Tree_traversal#Post-order_(LRN)).

Escaping: https://diveinwp.com/escape-shortcodes-in-wordpress/

Sample UI:
![image](https://user-images.githubusercontent.com/1165805/82126167-c3bf4180-975f-11ea-8194-75d0ceaee2f3.png)

A custom implementation could use Razor templates from a specific folder. Could also include liquid files. Or be based on shapes and a special prefix. But that might allow for security issues, and it would be hard to define metadata (description).

**Comment by jptissot** [comment]
Would it be possible to have access to a context object / pass multiple arguments to shortcodes. I was thinking of using shortcodes to add inline translation support to a ContentItem. 

I am building a `LocalizedTextPart` which contains a List of {key, [ {culture, value}]} objects and wanted to use shortcodes to access these values inside some other Parts/Fields of the same ContentType. 

For example, you could use a textual value for the "Label" portion of a FormInput widget by writing this: `[translate]translationKey[/translate]` in the admin. This shortcode would lookup the LocalizedTextPart, value based on the passed key and current culture. 
This would require us to have access to the current ContentItem (or parent ContentItem, if using flow / bags) inside of the shortcode implementation. It would also be useful for this feature to be able to pass some additional arguments to the shortcode if one of the translation values needs some formatting.

Is this a good use-case for Shortcodes or should this be using liquid ?


Another idea I had was to inline translations using shortcodes. For sites without many languages, we could have a shortcode that would encapsulate a locale inside a single field's value. 

Html Editor value:
```
[en:] ENGLISH HTML HERE [en]
[fr:] French HTML HERE [fr]
```

**Comment by deanmarcussen** [comment]
For notes on O1 tokens.

Here's the current list from O1, which is a good indicator of where they were used, and maybe useful. Noting that many of these currently have very appropriate liquid equivalents, so there is no suggestion they should go everywhere...

![tokenspage1](https://user-images.githubusercontent.com/13782679/87416558-c951d000-c5c6-11ea-9e0d-6bda16502a7a.PNG)
![tokenspage2](https://user-images.githubusercontent.com/13782679/87416580-ceaf1a80-c5c6-11ea-9277-09d03d0574ba.PNG)
![tokenspage3](https://user-images.githubusercontent.com/13782679/87416585-d1117480-c5c6-11ea-89aa-f928aa92e833.PNG)

**Comment by agriffard** [comment]
It is also very clear to me than the equivalent of 01 tokens are Liquid filters.

Shortcodes are a way to render more complex html from a simple tag under bracket with parameter(s).

**Comment by agriffard** [comment]
Sometimes, we will have to make a choice, for example with some helper that generates a small amount of html from a parameter.

Let's think about a Gravatar link that generates an `<img/>` from an email address: 
Do we provide a Liquid filter, a Shortcode or both?

- Liquid is interesting because it can be used in HtmlBody, Markdown and Liquid (Parts and Fields).
- Shortcode is interesting because it is simple to write and understand.

**Comment by deanmarcussen** [comment]
For me the difference is shortcodes are discoverable, and liquid will not be.
so shortcodes are more for content editors (i.e. html fields etc al), and liquid filters are for developers (of templates / site etc).

shortcodes are always considered safe
