### ISSUE TITLE
HTML field - style broken when copy paste (ctrl + v)

### ISSUE THREAD

**Issue by minhdn2** [OrchardCMS/OrchardCore#6208]
Hi,

I'm having and issue with HTML field, when I hit `ctrl + v` the current style of the content inside the HTML field will be broken.

**before:**
![image](https://user-images.githubusercontent.com/35803003/82203267-45b09580-992d-11ea-99bd-53d3f29288eb.png)

**after:**
![image](https://user-images.githubusercontent.com/35803003/82203686-cff8f980-992d-11ea-9c10-d903156ea57a.png)

Is this an issue or a feature? If it is a feature, how can I turn it off?

Please help to check and advise,
Many thanks in advance.

**Comment by devlife** [comment]
Not a direct answer to your question but I always copy and paste using the code view instead of the editor view.

**Comment by minhdn2** [comment]
But in my case, the users don't know about HTML or coding, typically end-users.
Please help to check and advise,
Thanks.

**Comment by devlife** [comment]
I don't know what the correct answer is but they don't need to know HTML or any other programming language. Just tell them to click the `< >` button before they copy/paste and then click it again to see the content. Copying/pasting in WYSIWYG is never a good idea. Without seeing the HTML that you're trying to copy and the end result I can't really give you any other advice other than maybe check out which editor you're using for the content field. If you're using the trumbowyg editor then maybe see if there is an additional plugin you need to use: https://alex-d.github.io/Trumbowyg/demos/

**Comment by agriffard** [comment]
It seems it happens with the `Trumbowyg` editor but not with the `Wysiwyg `editor (which is supposed to be the same but without options defined).

**Comment by agriffard** [comment]
Tested with:
```
<h1 style="text-align: center;">Enjoy and Save</h1>
<p style="text-align: center;">
As a member:
</p>
```

**Comment by minhdn2** [comment]
hi @agriffard ,

I'm using Trumbowyg because it allows me to config it to not automatically change <div> tags to <p> tags.
Can I do the same with Wysiwyg? If yes, please help to check and advise,

Many thanks in advance.

**Comment by micnyk** [comment]
+1 
I'm facing the same issue

**Comment by agriffard** [comment]
When the cleanpaste plugin is added, this behaviour occurs.

You can test here: https://alex-d.github.io/Trumbowyg/demos/#plugins-cleanpaste

**Comment by Piedone** [comment]
Is the problem that formatting will be copied into the Trumbowyg editor too? You can avoid that with Ctrl+Shift+V BTW. What do you want to achieve, exactly?
