### ISSUE TITLE
Metadata.Name is null when Shape is created with New shapefactory

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6211]
When shape is created as following and added to zone. Doesn't assign Shape Name to `shape.Metadata.Name`

```
var shape = await New.ToolWidgetSettings()
Model.Foolter.Add( shape )

```
So when called later as 

`Model.Foolter.ToolWidgetSettings` throws `RuntimeBinderException: Cannot perform runtime binding on a null reference`

**Comment by Piedone** [comment]
I don't believe this was meant to work like that. Currently, you'll simply get `null` BTW (you need to use `AddAsync()` though).

Please reopen if you think this isn't the intended behavior, linking to where you see that information.
