### ISSUE TITLE
How to allow anonymous user access on Page (content type)??

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#6213]
For some unknown reason, all Orchard Pages (content type) I created requires user login to view; but I want to allow anonymous access.

Any idea?

**Comment by deanmarcussen** [comment]
It depends on what recipe you ran to set this up, but perhaps you ran one with restricted access to content, or have changed the permissions?

Regardless you can check the View all content security for the `Anonymous` role and see if it is selected.

**Comment by orchardc** [comment]
Hi @deanmarcussen, I use the agent template, there is no view but liquid template in Orchard. For some reason all liquid page need authorized to see..

**Comment by orchardc** [comment]
Any idea?

**Comment by orchardc** [comment]
This is a very strange problem.

I create a page call: test

![image](https://user-images.githubusercontent.com/16193516/82496661-02992280-9ae5-11ea-8486-01660e9be494.png)

Then when browse the link (http://localhost:2020/test) without login, I will be redirected to the login page.

How can I troubleshot this issue?

Many thanks!

**Comment by hishamco** [comment]
Strange!! which version you are using, I will try to test it with the nightly build

**Comment by orchardc** [comment]
Hi @hishamco I'm using the latest version but I think it's not that. I try it without my solution it works just fine. How can I debug it so that I can see which code cause this? In my controller pages it works all fine, only the Orchard pages have this issue.

**Comment by hishamco** [comment]
Please share steps - or minimal repo - to reproduce

**Comment by orchardc** [comment]
I feel it's not possible to reproduce as this problem happens for a few months but I didn't notice.  If I create a new database with Agent template again, the problem disappears immediately.

**Comment by orchardc** [comment]
Problem solved. It's about the security role: Anonymous

For some reasons, all checkbox for that role were unselected. I then select "View all contents", it works fine now. Thank you for your attention.
