### ISSUE TITLE
Is it possbile to have a controller to accept HttpPost from external web service?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#6214]
For example, I want external webservice to call the following method which is hosted in my Orchard project (a controller). But I receive HTTP 400 error.

[HttpPost]
public async void Callback()
{
 //code ...
}

**Comment by ns8482e** [comment]
Disable anti forgery token for your controller

**Comment by orchardc** [comment]
Thanks @ns8482e , I added the following but it still doesn't work.

[HttpPost]
[IgnoreAntiforgeryToken(Order = 2000)]
public async void Callback()
{
//code ...
}

**Comment by ns8482e** [comment]
Try this
```
[AutoValidateAntiforgeryToken]

public class ManageController : Controller
{
    [HttpPost]
    [IgnoreAntiforgeryToken]
    public async Task<IActionResult> DoSomethingSafe(SomeViewModel model)
    {
        // no antiforgery token required
    }
}
```

**Comment by orchardc** [comment]
I got the same 400 error when calling this action from an external app (Postman)

![image](https://user-images.githubusercontent.com/16193516/82297606-ca8dc480-99aa-11ea-96a1-42a385632064.png)

**Comment by orchardc** [comment]
Any idea? Can Orchard controller accept HttpPost from external service?

**Comment by orchardc** [comment]
@jtkech  could you help?

**Comment by sebastienros** [comment]
Try a GET. If it works then the issue is with the antiforgery token.

**Comment by orchardc** [comment]
Get works just fine! Thanks @sebastienros , now the question is how to solve the antiforgery token from external service (like postman), and can I not turn it off - only for this TEST action?

![image](https://user-images.githubusercontent.com/16193516/82606442-05604a00-9baf-11ea-9927-eb087e96c868.png)

**Comment by sebastienros** [comment]
Make Test return something like the index is doing

**Comment by orchardc** [comment]
That's still the same 400 result @sebastienros 
![image](https://user-images.githubusercontent.com/16193516/82614541-08b00180-9bc0-11ea-8231-fb8ba338c8f8.png)

**Comment by ns8482e** [comment]
I am not sure, should work. 

This how I have defined and it's working for me.
 ```
       [HttpPost, IgnoreAntiforgeryToken]
        public async Task<IActionResult> Submit(string id)
        {
        }
```

**Comment by orchardc** [comment]
This is same result, unfortunately. Maybe you can paste a screenshot of how Postman works in your environment - could be parameter issue?

![image](https://user-images.githubusercontent.com/16193516/82645166-5e110080-9c0a-11ea-93de-5bfed472d560.png)

**Comment by orchardc** [comment]
Gents,

I'm able to post now, thank you for your support.

![image](https://user-images.githubusercontent.com/16193516/82657109-b51fd100-9c1c-11ea-8702-d33ac1cb2274.png)


It's because I didn't add the route!

![image](https://user-images.githubusercontent.com/16193516/82657155-d1237280-9c1c-11ea-9584-049ae6783871.png)
