### ISSUE TITLE
Taxonomy and Tagging

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#6215]
Hi Guys, 

Quick question, I can't seem to find the taxonomy type, I enabled the taxonomy as a feature but then I don't know where it is on the new content type definition, I added a part called taxonomy field but that seems incorrect. Please help, will be launching the site soon and I just wanted to enable to search functionality using tags.  Thank you so much.

**Comment by deanmarcussen** [comment]
When `Taxonomies` are enabled in the `New` menu you should see a listing for `Taxonomy`

Note it is not a Part that you add to a content type, it is it's own content type.

Here is a good blog to help you get started with them https://www.davidhayden.me/blog/taxonomies-in-orchard-core-cms

**Comment by webmedia1012** [comment]
Thank you @dean for the reply, on the 1004rc version it's not visible until you get to content definition and then you can see the taxonomy type, on the new version however of OrchardCms, you can  see it, however you can't distinguish the name on Manage Taxonomy Content, they all say Taxonomy. And when you attached to a content type, you and edit, you see all the taxonomy content but no name just (unique identitfier).
![taxonomy](https://user-images.githubusercontent.com/2730217/82387874-021d6080-99ed-11ea-841c-8d342fff0297.PNG)

**Comment by deanmarcussen** [comment]
You just need to add a `TitlePart` to your `Taxonomy` `Term` Content Type Definition.

**Comment by webmedia1012** [comment]
Hi Dean, thank you again. As you can see from the screenshot I did have a title part on my Taxonomy Term Am I missing something? 

![txn_topic](https://user-images.githubusercontent.com/2730217/82450311-6417ad80-9a61-11ea-918a-d80f1c91612e.PNG)

**Comment by webmedia1012** [comment]
Once I've completed this project I'm going to release a video tutorial to help out those that might encounter some issues, so I'm thankful for your help.

**Comment by deanmarcussen** [comment]
Somehow it feels like you didn't enter a Title for your taxonomy (or maybe called it `Taxonomy` and it didn't like that. ?)

here is a working example from `TheBlogTheme` 

Perhaps if you are still struggling you should just setup a new site based on `TheBlogTheme` as it has both `Tags` and normal `Taxonomies` in it, which may help you figure out what you're missing

![Screenshot 2020-05-20 at 14 29 02](https://user-images.githubusercontent.com/13782679/82451917-85e75380-9aa6-11ea-92b0-13644c9f5706.png)

**Comment by webmedia1012** [comment]
Hi Dean, thank you for the tip, just one last question, what version of OrchardCore cms is this? Coz my version does not show that, the recent release passed 1004rc. Regards

**Comment by webmedia1012** [comment]
Looks like this when you create a new one.
![taxonomy](https://user-images.githubusercontent.com/2730217/82459675-130db680-9a6d-11ea-8d4c-a71bf2967c24.PNG)

**Comment by webmedia1012** [comment]
Ok I figured it out. When you enable Taxonomy for the first time, you have to Edit and Add in Title Part. Then the only thing that's checked is createable. Thank you again!

**Comment by agriffard** [comment]
Please close the issue if your question has been answered.

**Comment by deanmarcussen** [comment]
Closing as question has been answered
