### ISSUE TITLE
Bug: style override in template

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#6216]
I made a liquid template for a bag item and sued the following at the top:
{% styleblock name:"custom-style" %}
    p {
        margin: 0;
		color: red;
    }
{% endstyleblock %}

I am using clean blog.
The red color showed up but the margin I set to zero did not override the 30 px set in the clean blog css file

**Comment by JoshTango** [comment]
Also when I inspect the element the margin property has a strike through line right through it.

**Comment by ns8482e** [comment]
@JoshTango if your color style is applying then the styleblock is working. May be some other styles for margin is taking precedence over your style. Try with !important

**Comment by JoshTango** [comment]
thank you that worked @ns8482e

**Comment by JoshTango** [comment]
or not i'm getting confused

**Comment by ns8482e** [comment]
It don’t think it’s bug in `styleblock`. I am using it and it’s working for me without any issue. 

Your style may not override other style that could be because of style order applied in browser, you can easily find that out using browser’s developer tools.

**Comment by JoshTango** [comment]
ok i got it working again.
