### ISSUE TITLE
Bag of Bags: slow edit UI

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#6219]
Hi guys, 

I have a strange issue over some browser like the new edge, chrome and firefox. If I try to order or edit my contenttype with a bag field that contains elements with a bag field too, the interface become slow if I go over some number of saved elements ( more o less 30 ) in the bag.

I attach a gif to better explain the issue. 
![bag of bags slow](https://user-images.githubusercontent.com/2736009/82326241-ced2d580-99dc-11ea-8cfd-6083bc06205d.gif)

Any suggestion is appreciated. 
Thank you.

**Comment by PiemP** [comment]
I have update the perfect-scrollbar in the admin template and seems work better ... but I'm really far to understand what can cause this slowiness at the page loading

**Comment by ns8482e** [comment]
@PiemP Are you seeing slow on drag while sorting?

**Comment by PiemP** [comment]
Sorting and when I open an accordion. Seems all the interface been slow, above all when page be loaded. The first browser that give this problem to us is the "new edge". But the other browsers show this behavior too. The console in the example gif is the chrome's console.

**Comment by Piedone** [comment]
Can you please confirm if this is still an issue? Since it's a bit inconvenient to try to reproduce.
