### ISSUE TITLE
YesSql Session Concerns

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#6223]
There are some scenarios where the 2 following issues can happen, without going into details, some of them will be introduced by #6054 but this PR fixes other issues where the application can crash.

- A save followed by a query, and then a mutation, needs another save to persist the last mutation.

    It's because the query does an auto flush that is useful to retrieve the non committed but updated items, but that clears the saved / updated collections. **I didn't find a simple fix on YesSql side**, we would need to check that a previously saved item has changed and then needs to be saved again.

    **So my suggestion is to do a session save before `Xxxed` handlers**, as already done most of the time, **and also after the `Xxxed` handlers** as done but only in some places. Maybe not everywhere but where i found that the issue may happen, i will do a PR to show what i mean, or maybe include it in #6054 as i will need it in this PR.

- A cancel followed by a query, a mutation and then a save, needs another cancel to not persist the last mutation. That's okay if the cancel is the last thing we do, but there are others scenarios.

    **Maybe a solution on YesSql side, i tried a simple fix that works**, but not sure there is no side effects. In `Session` `DemandAsync()` i just removed [this line](https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Core/Session.cs#L1052) where `_cancel` is set to false.

**Comment by sebastienros** [comment]
Yes, I think I mentioned it during the last triage, and this is how I described a potential fix in yessql. Not sure about this line exactly but will check.

To be sure about side effects it to run the unit tests, or just create a PR and it will run it for you. Even better add another unit test to check the scenario that didn't work. And issue however is that all itemds will need to be rechecked for changes if there is an auto-flush. That might hurt perf, but in the case of OC it should only be for one object.

**Comment by sebastienros** [comment]
If you look at this PR where I added some unit tests you'll see that it works already. Can you fix my tests to make them fail?

https://github.com/sebastienros/yessql/pull/232

**Comment by jtkech** [comment]
> If you look at this PR where I added some unit tests you'll see that it works already. Can you fix my tests to make them fail?

So it's about the 1st concern, okay i will commit a change to make them fail

> To be sure about side effects it to run the unit tests

So it's about the 2nd concern, i had already forked YesSql, removing the line where _cancel is set to false doesn't break unit tests.

> That might hurt perf, but in the case of OC it should only be for one object.

So maybe worth to find a compromise on OC side, maybe only when acting on a content item through the content manager / display manager that call drivers / handlers. And in the other cases let the code having the responsability to do another save if before a query + mutation have been done.

**Comment by jtkech** [comment]
@sebastienros 

I was not able to commit my change to your `sebros/saveflush` branch, so here the 2 unit tests where i changed one line to make them failing

        [Fact]
        public async Task AutoflushCanHappenMultipleTimes()
        {
            _store.RegisterIndexes<ArticleIndexProvider>();

            using (var session = _store.CreateSession())
            {
                var d1 = new Article { PublishedUtc = new DateTime(2011, 11, 1) };
                var d2 = new Article { PublishedUtc = new DateTime(2011, 11, 1) };

                session.Save(d1);
                session.Save(d2);

                // Change this line
                var article = session.Query<Article, ArticlesByDay>(x => x.DayOfYear == 305).FirstOrDefaultAsync();

                d1.PublishedUtc = new DateTime(2011, 11, 2);

                // And update this line
                var articles = session.Query<Article, ArticlesByDay>(x => x.DayOfYear == 306);

                Assert.Equal(1, await articles.CountAsync());
            }
        }

        [Fact]
        public async Task ChangesAfterAutoflushAreSaved()
        {
            _store.RegisterIndexes<ArticleIndexProvider>();

            using (var session = _store.CreateSession())
            {
                var d1 = new Article { PublishedUtc = new DateTime(2011, 11, 1) };
                var d2 = new Article { PublishedUtc = new DateTime(2011, 11, 1) };

                session.Save(d1);
                session.Save(d2);

                // Change this line
                var articles = await session.Query<Article, ArticlesByDay>(x => x.DayOfYear == 305).ListAsync();

                d1.PublishedUtc = new DateTime(2011, 11, 2);
            }

            using (var session = _store.CreateSession())
            {
                var articles = session.Query<Article, ArticlesByDay>(x => x.DayOfYear == 306);
                Assert.Equal(1, await articles.CountAsync());
            }
        }

**Comment by sebastienros** [comment]
Oops!

**Comment by jtkech** [comment]
Fixed through https://github.com/OrchardCMS/OrchardCore/commit/ea2c37859654f432597ef060043701009b879ef3
