### ISSUE TITLE
Required Annotation without custom error message cannot be localized

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#6228]
I've checked out head of dev branch.
Then added my es-ES.po to a module which is enabled.
Then set site culture to es-ES
An enable reset password feature and enable its related setting
The po file contains following lines:
```
msgid "The {0} field is required."
msgstr "Translation 1"

msgid "RequiredAttribute_ValidationError"
msgstr "Translation 2"
```
Viewmodel at head of dev looks like that:
```
public class ForgotPasswordViewModel
    {
        [Required]
        public string UserIdentifier { get; set; }
    }
```
Then I fulfill the form with blank email, the error message that is rendered is the default one in English: ´The UserIdentifier field is required.´

This is weird cause I would expect `Translation 1` should have been rendered. Because msgid `"The {0} field is required."` is the string currently used by default by .NET as can be seen in the source code: https://github.com/microsoft/referencesource/search?q=RequiredAttribute_ValidationError&unscoped_q=RequiredAttribute_ValidationError

A workaround for that problem is to provide an error message to the annotation. It is crazy because if I provide the exact message .NET uses it works. 
```
public class ForgotPasswordViewModel
    {
        //[Required(ErrorMessage = "The {0} field is required.")]
        [Required]
        public string UserIdentifier { get; set; }
    }
```
I've been debugging and I've set breakpoints at `PortableObjectStringLocalizer.this[string name]` and `PortableObjectStringLocalizer.this[string name, params object[] arguments]` methods and I found that those methods are not called for the annottation when it doesn't have a custom erro message. However I found they are called when the error message is set. No matter if that message is exactly the same as the default one.

**Comment by hishamco** [comment]
YES, that's why I'm still fighting to accept my PR #467 ;)

**Comment by jersiovic** [comment]
:) which one? That one that you point is old and merged

**Comment by hishamco** [comment]
Nah I forgot the last digit ;) it is #4675

**Comment by jersiovic** [comment]
I would like to add that this "small" problem is a pain in the ass, cause only for that I need to have my own controller and viewmodels version of any Orchard controller I want to localice if it uses an annotation at its viewmodel that is not localizable because has no custom error. , cause I need a new  viewmodel with custom error message to the [required] annotation to avoid this bug.

**Comment by Piedone** [comment]
@hishamco this is done now, right?

**Comment by hishamco** [comment]
I think so, coz I remember at the time implemented the localization for `DataAnnotations` in #4675, so let us close this

@jersiovic feel free to open if there is issue related

**Comment by Piedone** [comment]
Great!
