### ISSUE TITLE
Consider removing IPluralRuleProvider.Order

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6229]
While I'm revising localization APIs, I just find there's a default implementation of `IPluralRuleProvider` called `DefaultPluralRuleProvider`. I don't think there will be a new implementation for that because all the cultures have fixed rule

The question is why do we need the `Order` property?!!

> Set the <see cref="Order"/> to a negative value in order to get called before the default implementation, or a positive value to be used as a fallback one.

according to the comment, if we need to add a new implementation - which I don't think why, but it could - we need to set that property, so the new implementation win, so I think the default technique that we are doing almost the time is to replace the service, with that I'm suggesting to delete this property unless there are something I don't know about

/cc @lukaskabrt @sebastienros

**Comment by Piedone** [comment]
Does this cause any issues for you? It's a point of extensibility, like `Startup.Order`, so if it bothers nobody, we can just keep it.

**Comment by hishamco** [comment]
I never got feedback from @lukaskabrt who is the author of this if I'm not wrong, it might be similar to `Startup.Order` but while we provide a default and comprehensive implementation for almost if not all the cultures, the `Order` could be useless

**Comment by Piedone** [comment]
Perhaps, but it's been out in the wild for a while and we can't know which implementations exist.

But then again, why remove it? We already have it. It can be useful and people may use it. It doesn't bother anybody.

**Comment by hishamco** [comment]
No problem let us close it
