### ISSUE TITLE
Question - User login records

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6232]
How can i know when user authorized via UI or open ID?
Log or records?

**Comment by hishamco** [comment]
You could use `HttpContext.User.Identity.IsAuthenticated`

**Comment by vitalybrandes** [comment]
> 
> 
> You could use `HttpContext.User.Identity.IsAuthenticated`

Yeah, but i am searching for the way to present list of logins per specific user.
Lets say,
user JohnD   20/05/2019  15:30 login

also, how can i check by code that user allowed to login to Dashboard?

thanks

**Comment by vitalybrandes** [comment]
> 
> 
> > Yeah, but i am searching for the way to present list of logins per specific user.
> 
> Seems you are referring to auditing
Well, kind of ;-)
Dose orchard store this kind of data?
Mostly i am interested in OpenID.
> 
> > how can i check by code that user allowed to login to Dashboard?
> 
> You can do that by using permissions

**Comment by Piedone** [comment]
If you want to log when users logged in then this will be possible with Audit Trail: https://github.com/OrchardCMS/OrchardCore/issues/4620

**Comment by vitalybrandes** [comment]
> 
> 
> If you want to log when users logged in then this will be possible with Audit Trail: #4620

Yes, this is exactly what i need (Open ID login)

**Comment by Piedone** [comment]
That will also be available for Open ID logins. Please watch that issue and try the module out once we have it published!

**Comment by vitalybrandes** [comment]
> 
> 
> That will also be available for Open ID logins. Please watch that issue and try the module out once we have it published!

@Piedone 
Hi
Is it available?

**Comment by Piedone** [comment]
Not yet integrated into the dev branch but yes, check it out here: https://github.com/OrchardCMS/OrchardCore/pull/6679
