### ISSUE TITLE
How to customiz MapIndex table name

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#6233]
For MapIndex, the table name is "[PartName]Index". This looks like a defaut pattern provided by YesSql during the table creation using CreateMapIndexTable in migration. 
So must it has this kind of name for YesSql to find the right table when it does the query operation?
Has a way to customize the table?

**Comment by hishamco** [comment]
Please move your question to YesSQL repo

**Comment by HengzheLi** [comment]
Ok. moving it

**Comment by sebastienros** [comment]
The table name is defined by each module that creates the part. Each module is free to use the table name it likes. You can only change the table names for the indexes you create.
