### ISSUE TITLE
Setup favicon invisible on light browser UIs

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6237]
I'd like to complain about the setup screen improvements as asked by @sebastienros under https://github.com/OrchardCMS/OrchardCore/pull/5781#issuecomment-606937463. The new favicon is good on dark browser UIs but invisible on light ones:
![image](https://user-images.githubusercontent.com/1976647/82598226-97198880-9baa-11ea-98ab-946db7d8e6cb.png)
This is when the tab is not in focus:
![image](https://user-images.githubusercontent.com/1976647/82598252-a6003b00-9baa-11ea-9cde-5196a5eb74bc.png)

**Comment by sebastienros** [comment]
Great, now fix it

**Comment by Piedone** [comment]
I'm still working on my PhD in Gimp so I'll be able to do that :|.

**Comment by Piedone** [comment]
Antoine is already a postdoc!
