### ISSUE TITLE
Incomplete information in Localization documentation?

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#6240]
Here https://docs.orchardcore.net/en/dev/docs/reference/modules/Localize/#publishing-localization-files docs say 

> Add the following configurations to your [Web Project].csproj file to include them as Content

However, when I'm creating a new module that I want to provide localizations within the module, that doesn't work like that. The .po file has to be included in the project as an embbeded resource if not it is not taken into account as localization file

**Comment by hishamco** [comment]
That's what I expect `embedded` not `content`, I will fix it soon

Thanks

**Comment by sebastienros** [comment]
Our maybe I didn't understand the issue

**Comment by jtkech** [comment]
@sebastienros 

This is when a module itself provides localizations files under its `Localization` folder, as @jersiovic said they need to be embedded, but this is done automatically.

Note: VStudio may add some item groups in the project file e.g. after having copy / paste some po files, in that case, in place of having to mark these resources as embedded through VStudio commands, you just have to remove these extra item groups from the project file.

**Comment by jersiovic** [comment]
Problem happened in combination with problem I reported in other issue with validation annotations. 
How they doesn't work with default error message, I read multiple times the docs to find what was the problem. Reading that I have to set po files as content didn't help me at all. Because the problem was even more difficult to understand after doing that

**Comment by sebastienros** [comment]
Is it known how to add custom localization files in a module?
- to change existing localization strings of other modules
- to define custom localization strings for this module

If not possible then we need to solve it. Otherwise it's about documentation
