### ISSUE TITLE
Which ORM is used in OrchardCore?

### ISSUE THREAD

**Issue by mehranrezaei** [OrchardCMS/OrchardCore#6246]
I started reviewing this project today. I have to say I'm completely confused.
I could not figure out what ORM was used in this project. I know YesSQL is used, but does YesSQL play an ORM role?
Isn't nHibernate or EF Core used anymore?

I am proficient in the architecture and structure of the Orchard 1.x, but I don't understand much about OrchardCore. Can anyone explain in this regard, especially how to communicate with the database without any familiar ORM?

**Comment by sebastienros** [comment]
YesSql is the ORM. It's actually mapping object to documents (like a document database).
A few modules that don't require document storage but just raw table use Dapper.

**Comment by mehranrezaei** [comment]
As far as I know, document storage is not suitable for all purposes, including searching one or more specific fields.
Also as I know Dapper provides much less functionality than Entity Framework does.
What is the superiority of Dapper over EF? Why did you prefer it for a multi-purpose project like OrchardCore?

**Comment by ns8482e** [comment]
@mehranrezaei you are not restricted to use only `YesSql` or `Dapper` for data storage. You can use `EntityFramework` in your custom module

**Comment by Piedone** [comment]
If you check out the [YesSQL docs](https://github.com/sebastienros/yessql) you'll see what makes querying possible (search for `IndexProvider`s in Orchard).

Dapper is very lightweight. As you can see in the code there is very little non-YesSQL querying in Orchard so it's suitable for that. If you want to store something in the DB and not manage it in documents, nor is it enough for you to query it with ADO.NET and map to an object with Dapper then you're free to use any ORM you like. The current DB connection is available everywhere: https://docs.orchardcore.net/en/dev/docs/reference/core/Data/#example

**Comment by mehranrezaei** [comment]
@ns8482e, @Piedone
I know I can use any ORM in my module, But I use a framework or CMS to make development easier and more standardized.

It is not very interesting that in each module we have to set up and configure ORM and there are no integrated settings at the solution level.

Also, as I know, Dapper does not handle database migrations. Has this feature (automatic database migrations) been removed in the new version of Orchard?

In the end, I emphasize that I am confident in the ability and knowledge of the Orchard team. If you prefer to use this method, it must have been the right decision. But that's a big change, and updating hundreds of modules will probably be difficult.

Please let me know if you have any documents, tutorials, guides or suitable examples for learning new structure and architecture and how to develop modules for OrchardCore.

For example, this article series ```http://www.ideliverable.com/blog/writing-an-orchard-webshop-module-from-scratch-part-1``` helped me a lot when I started reading Orchard 1.x. I would be very happy if such articles exist for OrchardCore.

Dear Zoltán, Also the content of your site and the modules you developed was a great guide for learning how to develop Orchard 1. I hope you continue on the same way for the OrchardCore.

**Comment by Piedone** [comment]
As we've written above, Orchard does use an ORM, YesSQL :). This is the built-in, standardized way. Dapper is a lightweight alternative for simpler use-cases. If all of this is not suitable for you then you can use any other ORM but you don't have to start by selecting an ORM for each of your modules.

Yes, database migrations are available (regardless of what kind of ORM you use for the table).

We've updated the Training Demo module for Orchard Core here: https://github.com/Lombiq/Orchard-Training-Demo-Module So welcome back :). This post might help you too: https://bearandhammer.net/2020/05/16/poking-around-with-orchard-core/

**Comment by ns8482e** [comment]
@mehranrezaei If you  need to use built in CMS features then yes it uses YesSQL.  

If you don't need CMS features then there is way to use your own choice of database and ORM without needing to use YesSQL to store your data.

Configure scoped data access service in startup, and use that directly in your controller in your modules.

**Comment by Piedone** [comment]
Please re-open if you have still questions.

**Comment by CrestApps** [comment]
Is it possible to use YesSql for the standard CMS function yet build my own module that uses other ORM to store data in a non-document database? If yes, can I still utilize the DisplayDrivers along with models outside of yessql to allow the users to control where each part of the app go and where it should be visible? I am interested in orchardcore CMS but need a way to store special data in a non-document database yet to be able to allow the user to control where to display features and widgets

**Comment by hishamco** [comment]
> Is it possible to use YesSql for the standard CMS function yet build my own module that uses other ORM to store data in a non-document database?

YesSQL is an abstraction layer that allow you to store documents in SQL databases. AFAIK OrchardCore is using YesSQL heavily

> am interested in orchardcore CMS but need a way to store special data in a non-document database yet to be able to allow the user to control where to display features and widgets

As I said before YesSQL is used for SQL database, so the question whats prevent you from doing what you want?

**Comment by Piedone** [comment]
You're free to use any DB with and ORM or other DAL, including the SQL DB Orchard is using (since you have access to the underlying DB connection at the low level, which allows you to do whatever you want with the DB). If you want to write content parts then you'll need to do it in the provided way. If you just want to write Display Drivers (i.e. modularized and compartmentalized way of building the output for models) then you can do that without YesSQL too (you can create a driver for any class).

**Comment by ns8482e** [comment]
CMS features are built on YesSQL. If your module doesn’t need to use any content management features then you can use any any database or external rest api without using YesSQL.

E.g. you can create Shape that could render data from external sources. Using display management features, You can change placement and zones for the shape. You can use widgets and layers to place your shape to any zone of your layout

**Comment by hishamco** [comment]
> then you can do that without YesSQL

@Piedone but there are many places tightly couple on YesSQL `ISession`

**Comment by Piedone** [comment]
I'm talking about drivers. You don't need `ISession` (or anything with any DB for that matter) to implement a `DisplayDriver<T>`. I was reflecting on the "can I still utilize the DisplayDrivers" part of the question.

**Comment by hishamco** [comment]
Got it, thanks
