### ISSUE TITLE
Remove Lists projects dependency on the Contents Module

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6247]
The `OrchardCore.Lists` project has a dependency directly on the `OrchardCore.Contents module.

This can be removed, by migrating some more of the `ContentTypePermissions.CreateDynamicPermission` helpers to the `OrchardCore.Contents.Core` project

and referencing more of the abstractions projects for `GraphQl` and `Feeds` etc

(I think this might be the last module, that is referencing another module)

**Comment by sebastienros** [comment]
There are abstractions for the permissions already, so this might not even be needed.
Unless it's actually creating new dynamic permissions, which I assume is the case ;)

**Comment by deanmarcussen** [comment]
Yes, the issue is it's creating new dynamic permissions, so will move that to core

**Comment by agriffard** [comment]
Is it fixed @deanmarcussen ?

**Comment by deanmarcussen** [comment]
No, I was waiting till @jtkech fixed the feature dependency issue, before I sorted this.

Just need to move some more of the dynamic permission code to core.
