### ISSUE TITLE
Adding a ObjectGraphType for a ContentPart that has ContentField(s) causes a "field already added" exception

### ISSUE THREAD

**Issue by kadamgreene** [OrchardCMS/OrchardCore#6253]
I created a `ContentPart` and added 2 `DateTimeFields` to it.  Because it has other, non-field properties, I created a `ObjectGraphType<SchedulePart>`.  But during the building of the `Schema`, it first adds my ObjectGraphType (via `TypedContentTypeBuilder`) and names it `schedule` (via ToFieldName extension method).  But every place where it checks to see if a field already exists, it does this:
```
if (contentItemType.HasField(partName)) continue;
```
which will look for `SchedulePart` not `schedule`.   This especially happens in `DynamicContentTypeBuilder` where the exception happens.

I think the code should be:
```
if (contentItemType.HasField(partName.ToFieldName())) continue;
```
Wherever it is doing the check for existing fields.

**Comment by jtkech** [comment]
Looks good, could you open a new PR to fix it so that a graphQL expert can review it
