### ISSUE TITLE
[HttpPost] Not working with OrchardModuleMVC and Web Api

### ISSUE THREAD

**Issue by Tanveer-Singh** [OrchardCMS/OrchardCore#6258]
Using OrchardCore MVC Module
1.0.0-rc1-10004 => NuGet package
Using .net core 3.0 Web API 
When making the Http Post request is giving me 400 Bad requests whereas Get request is working fine 
Here is the sample code -  
`  
   [ApiController]
    [Produces("application/json")]
    [Route("api/WeatherForecast")]
    public class WeatherForecastController : ControllerBase
    {

        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        [Route("[action]/{id}")]
        public IEnumerable<WeatherForecast> GetDetails(string id)
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
                {
                    Date = DateTime.Now.AddDays(index),
                    TemperatureC = rng.Next(-20, 55),
                    Summary = Summaries[rng.Next(Summaries.Length)]
                })
                .ToArray();
        }

        [HttpPost]
        [Route("PostDetails")]
        public JsonResult PostDetails([FromBody] string uvm)
        {
            var result = new CreatedAtActionResult("PostDetails", "statuscodeobjects", "",
                new { message = "201 Created", currentDate = DateTime.Now });
            return new JsonResult(true);
        }
`

Startup.cs - empty
Get -  http://localhost:8080/api/weatherforecast/GetDetails/1 (working fine)
Post  http://localhost:8080/api/weatherforecast/PostDetails  
When posting it just says Bad request

**Comment by Piedone** [comment]
Probably this requires an XSS prevention token (though I'm not sure it should by default). Anything in the logs or any error details? What happens if you put `[IgnoreAntiforgeryToken(Order = 2000)]` on the controller (do note that this will make the controller susceptible to XSS attacks so only use it if this is an API for external apps)?

**Comment by Tanveer-Singh** [comment]
Yes, I figured it out
it requires both attributes on the top of the Controller class
Fix -
 `    [ApiController]
    [Route("api/[controller]")]
    [IgnoreAntiforgeryToken, AllowAnonymous]
`
It has been fixed we close it.

**Comment by Piedone** [comment]
Great then!
