### ISSUE TITLE
How to deploy for tenant

### ISSUE THREAD

**Issue by sunnykachwala** [OrchardCMS/OrchardCore#6259]
Hi,
I have created three website 
1) host https://host.sunnykachwala.com/
2) blog https://blog.sunnykachwala.com/
3) agency https://agency.sunnykachwala.com/

for the host is not working but working in local 
created two tenants and for that I would like to host a website.

how can this be achived?

**Comment by hishamco** [comment]
did you map them into your sub domains?

**Comment by Skrypt** [comment]
Each tenants needs to have the proper subdomain set for them on the tenant configuration for this to work.

**Comment by sunnykachwala** [comment]
this is host website 
I updated CName records for tenant website 
This is a tenant website 
https://sunnykachwala.com
What else I need to do?

**Comment by Skrypt** [comment]
On the tenants configuration. There is **Hostname** field in which you need to set your subdomain for each tenants that you want to be resolved with this specific subdomain. Else the tenants resolution won't work. You subdomains needs to point to the same ip address than your main domain in your DNS records.
