### ISSUE TITLE
Sanitize Html removes css classes

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6260]
1) When you use an HtmlField in a content type with a Widget Stereotype, the css classes are removed.

2) With ou without 'Sanitize Html' checked, the line breaks are also removed.

**Comment by deanmarcussen** [comment]
1. Yes, classes are considered susceptible to class jacking (https://html5sec.org/#123) so removed from the sanitizer by default

There's a unit test showing how to configure the sanitizer to accept classes, and other attributes.
https://github.com/OrchardCMS/OrchardCore/blob/736cdd5977196baf7ca2d5f9a77ec28ad3af4e22/test/OrchardCore.Tests/Html/HtmlSanitizerTests.cs#L27

Maybe we could accept classes by default, I admin I'm not sure how class jacking could be used in our scenario?

2. I couldn't repro this?

**Comment by jptissot** [comment]
Do we have some docs related to the sanitizer? I was searching how to configure it recently,thanks for the tip Dean.

**Comment by agriffard** [comment]
Yes, please accept classes by default.

**Comment by deanmarcussen** [comment]
Haven't got docs yet :(

Can you do a bit of research @agriffard and see if classes are going to be safe for us?

I think they will because there's nowhere for the user to enter a malicious script that could be used to classjack.

It is easy to configure this by default, so pending some research I'll put a pr in :)

**Comment by agriffard** [comment]
It might be safe, you can not inject javascript with the class attribute, only with scripts, `on` events, img src or a href.
