### ISSUE TITLE
Rawhtml attributes gets deleted automatically.

### ISSUE THREAD

**Issue by quiary** [OrchardCMS/OrchardCore#6265]
I've been playing with rc version, and I found that after 1.0.0-rc1-13240, when I edit the rawhtml widget, all the html attributes gets deleted automatically.  For example:

`<div class="copyright">copyright</div>`

but after I clicked publish, the result is 

`<div>copyright</div>`

I don't what happened. Had anyone encounter the same problem?

**Comment by agriffard** [comment]
Duplicate of #6260

**Comment by quiary** [comment]
Thanks.
