### ISSUE TITLE
No support for serverless

### ISSUE THREAD

**Issue by Shilpa-V** [OrchardCMS/OrchardCore#6269]
We are using `orchardcore.localization` package for a few of our localization projects and trying to get it into one of our serverless dotnet core projects which use Azure.WebJobs. It doesn't hit our custom implementation of `ILocalizationFileLocationProvider` and won't be able to load all the PO files for translations.
I think it is because of the `IHostEnvironment` dependency of `ILocalizationFileLocationProvider` to get the `FileProvider`.
Is there any way I would load PO files in a serverless project which is configured on `IFunctionsHostBuilder`?
Can you think on to remove this `IHostEnvironment` dependency?

**Comment by hishamco** [comment]
I didn't work with `IFunctionsHostBuilder`, nothing but `ILocalizationFileLocationProvider` doesn't depend on `IHostEnvironment` but `ContentRootPoFileLocationProvider` depend on it, so I suggest to create a custom implementation that fits your need

/cc @sebastienros

**Comment by Shilpa-V** [comment]
Ya, I found that. Have implemented with custom implementation. Thanks.
