### ISSUE TITLE
FileSystemStore issues

### ISSUE THREAD

**Issue by vesko-k** [OrchardCMS/OrchardCore#6272]
When getting file system info a relative path is passed to the FileSystemStoreEntry. 
```csharp
        public Task<IFileStoreEntry> GetFileInfoAsync(string path)
        {
            var physicalPath = GetPhysicalPath(path);
            var fileInfo = new PhysicalFileInfo(new FileInfo(physicalPath));

            if (fileInfo.Exists)
            {
                return Task.FromResult<IFileStoreEntry>(new FileSystemStoreEntry(path, fileInfo));
            }

            return Task.FromResult<IFileStoreEntry>(null);
        }
```
When calling 
```csharp
        public Task<Stream> GetFileStreamAsync(IFileStoreEntry fileStoreEntry)
        {
            if (!File.Exists(fileStoreEntry.Path))
            {
                throw new FileStoreException($"Cannot get file stream because the file '{fileStoreEntry.Path}' does not exist.");
            }

            var stream = File.OpenRead(fileStoreEntry.Path);

            return Task.FromResult<Stream>(stream);
        }
```
File operations are made with relative path. I think path must be converted to physical one or in FileStoreEntry ctor a physical one should be passed.

**Comment by deanmarcussen** [comment]
Can you explain the actual problem you are experiencing?

The `FileSystemStore` is wrapped for the `MediaFileStore` which resolves a base path, which is the intended usage.

**Comment by vesko-k** [comment]
The problem is when you call 
```csharp
        public Task<Stream> GetFileStreamAsync(string path)
        {
            var physicalPath = GetPhysicalPath(path);

            if (!File.Exists(physicalPath))
            {
                throw new FileStoreException($"Cannot get file stream because the file '{path}' does not exist.");
            }

            var stream = File.OpenRead(physicalPath);

            return Task.FromResult<Stream>(stream);
        }
```

the `filename` is translated to physical path and File operations work as assumed. But when you pass FileSystemStoreEntry, which is obtained through the 'GetFileInfoAsync' the Path member contains relative path, then when you pass 'FileSystemStoreEntry' to any operation e.g. `GetFileStreamAsync(IFileStoreEntry fileStoreEntry)`, the FileStoreEntry.Path is used and not translated to the physical one. In the concrete example an exception is thrown because of missing file. But if you use ` Task<Stream> GetFileStreamAsync(string path)`, the elative path is correctly translated to physical and everything is ok.

**Comment by deanmarcussen** [comment]
Hmm, yes I understand.

We can't expose the absolute `Path` directly, because this interface is exposed by `GraphQl` and the design is to never expose an underlying path.

I wrote this for `BlogFileStore` some time ago, and may have only tested it with blob storage, so it might be that it's not correctly implemented for the `FileSystemStore`.

What it should do, probably, is `var physicalPath = GetPhysicalPath(fileStoreEntry.Path);` in the `GetFileStreamAsync(IFileStoreEntry fileStoreEntry)`

If you want to put a pr together that would be great.
