### ISSUE TITLE
Content Types with restricted FlowParts are only enforced the first time

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#6276]
We have created a custom ContentType with the following parts:
* Title
* Autoroute
* Flow
* Location

We have also restricted the FlowPart so that it can only contain *Html* ContentType instances.

When we create a new content of this new type, the available types to use are in fact restricted to just *Html*.

Howerver, after having inserted the first (restricted) one, if we try to further add more widgets to that very same content, they are not restricted: all of them are available.

We are using OC 1.0.0-rc1-13168. Can someone confirm or are we doing something wrong?

**Comment by sebastienros** [comment]
Probably that the drop down lists that are dynamically generated don't comply with that constraint.

**Comment by ns8482e** [comment]
@jagbarcelo restriction applied to the `Content Type` only. If you have defined restriction to `Page` then `FlowPart` within `Page` has restriction. If you allow `Container` within `Page`  and if you don't have restriction on `Container`  then it will allow any `Widgets` inside `Container` within `Page`

**Comment by sebastienros** [comment]
Good find. but it means the restrictions are almost vain if Container is not part of this list too ...

**Comment by ns8482e** [comment]
> Good find. but it means the restrictions are almost vain if Container is not part of this list too ...

And drag/drop too. Widgets from one `FlowPart` can be dropped to any `FlowPart`

**Comment by jagbarcelo** [comment]
> @jagbarcelo restriction applied to the `Content Type` only. If you have defined restriction to `Page` then `FlowPart` within `Page` has restriction. If you allow `Container` within `Page` and if you don't have restriction on `Container` then it will allow any `Widgets` inside `Container` within `Page`

We have applied the restriction to the `Part` within the `RestrictedPage`  (or new content type). The restriction for that `Part` is that it can only contain `Html` widgets. Nothing more is allowed:

![image](https://user-images.githubusercontent.com/6704109/83015611-fb13d500-a020-11ea-99e3-0afa2b5e9649.png)

The first time the drow down list is restricted (Ok):

![image](https://user-images.githubusercontent.com/6704109/83015833-53e36d80-a021-11ea-8967-e8eca157a4be.png)

Below it, the dropdown is still restricted (Ok):

![image](https://user-images.githubusercontent.com/6704109/83016027-a15fda80-a021-11ea-9272-d78e677c426d.png)

But above all of them, everything is usable (Wrong):

![image](https://user-images.githubusercontent.com/6704109/83016159-cf451f00-a021-11ea-84ab-d5dd1796734d.png)

Does it make any sense?

**Comment by ns8482e** [comment]
@jagbarcelo oh ! It seems `Add` below showing your selection, but `Insert` above is not showing all options. I'll create PR soon

**Comment by jagbarcelo** [comment]
FYI, as per OC 1.0.0-rc2-14477 dated 2020-09-23, just updated, this issue is still happening.
None of the former two merge requests referencing this issue solved it: `Insert` above still shows all options (not filtered).

**Comment by ns8482e** [comment]
@jagbarcelo is still open pull request  and has not been merged yet :)
