### ISSUE TITLE
It seems Orchard OpenId certificate is not supported on an Azure App Service based on a linux container

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#6290]
This scenario is not supported by Orchard. It expects to load OpenId certificate from windows stores instead of the concrete path provided for linux containers

https://stackoverflow.com/questions/56702393/loading-a-tls-certificate-uploaded-to-the-azure-portal-into-a-linux-app-service

**Comment by sebastienros** [comment]
Can you point to the part of the code which should be changed? In case someone want to look at it.

**Comment by kevinchalet** [comment]
The OpenID module uses `X509Store`, which is expected to also work on Linux/macOS.

Closing, but feel free to re-open if you're still seeing an issue.
