### ISSUE TITLE
Media Library: column for last modified date time

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#6291]
Hello guys,

Could interest to show last modified date time of a file in the media library and sort by this column? If yes, could I do a PR to add this functionality?

Thank you.

**Comment by PiemP** [comment]
Some image to clarify what I intent.
before:
![before](https://user-images.githubusercontent.com/2736009/83231679-2cf57a80-a18c-11ea-90c4-9d4aa385e070.jpg)

after:
![after](https://user-images.githubusercontent.com/2736009/83231691-3383f200-a18c-11ea-948c-2bc5e32989ba.jpg)

**Comment by Skrypt** [comment]
Ok, are you changing the last modified date on this file when it's uploaded on the server. I mean, you need to modify it's last modified date with the upload date to make this relevant? Should we do this or simply wait for a proper audit trail on file uploads?

**Comment by PiemP** [comment]
I don't know the behavior on other system like azure or Linux server but on my dev Windows server the LastModify field have the value of the moment when the file is uploaded: without do anything. 

The reason of this is to have a way to identify the last file uploaded on the system, I don't know if could be useful for other guys: we have this necessity and I try to ask to you if exists the same interest on "orchard side" :-D .

I know exists the search engine and other way to order items, but my boss is lazy and want to have this feature. If exist common interest about it: is useful to me have a good feedback about what I have done and, I hope, is useful to you to have something more.

**Comment by deanmarcussen** [comment]
> I don't know the behavior on other system like azure or Linux server but on my dev Windows server the LastModify field have the value of the moment when the file is uploaded: without do anything.

The issue might be that on Azure the `LastModifiedDate` is actually the uploaded date, not the `LastModifiedDate`

The last modified date on windows is actually the last time the file was edited, and is preserved when uploading an image to the local file system, but not to azure. 

So I wouldn't think `LastModifiedDate` is a good consistent / accurate value to use.

**Comment by PiemP** [comment]
> The issue might be that on Azure the LastModifiedDate is actually the uploaded date, not the LastModifiedDate

I believe to have write something wrong in English 😅 ... btw the behavior on the windows server is the same of the Azure ones ... `LastModifiedDate` is actually the uploaded date.

If you believe is better to edit file information on the upload I could try to do it. But for what I have seen, If you upload file from media library, the file already have `LastModifiedDate` to the uploaded date.

Miss a Linux test about this, but I believe the behavior doesn't change because it create a new file on upload and alter all the file information.

**Comment by Skrypt** [comment]
Share a PR so that we can test this.

**Comment by PiemP** [comment]
#6341

I add a gif that show the behavior that I see when I upload an image to media library:
![upload image](https://user-images.githubusercontent.com/2736009/83733197-860e5400-a64d-11ea-935a-ea5caf3cf93b.gif)
