### ISSUE TITLE
Rename Media Short Code

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6292]
We should consider renaming the `[media]` short code to `[image]` because it generates an img tag.

We will also need a `[link]` short code to generate an `a` tag to an asset, for example a pdf.

We should not have a short code that just returns the file path as this is not sanitizable

This also gives us the possiblities to have short codes for `[audio]` and `[video]` and other tag types.

**Comment by sebastienros** [comment]
> We should not have a short code that just returns the file path as this is not sanitizable

How can't it be safe? What's the attack vector?

**Comment by deanmarcussen** [comment]
> How can't it be safe? What's the attack vector?

Maybe it is ok, we originally said any of the short codes, should always be safe.

So we can't sanitize a short code that doesn't produce an html snippet (to sanitize), but probably it will be picked up by the sanitizer editing it anyway, unless the short codes ever make it somewhere that isn't an html field, in which case, there would be the opportunity to play games with `onload=` without tags (which would be html escaped out)
