### ISSUE TITLE
Issue with multi_match elastic search

### ISSUE THREAD

**Issue by PauloSRH** [OrchardCMS/OrchardCore#6295]
When performing the following lucene query, in the admin interface of OrchardCore, I have issues.

```JSON
{
  "query": {
    "multi_match" : {
      "query":    "test", 
      "fields": [ "TitlePart", "AliasPart" ] 
    }
  }
}
```

I get the error: "Invalid query : Object reference not set to an instance of an object."
And the logs: 

> 2020-05-28 14:24:48.5028|Default||6214155b-40613ff860a8383a.||OrchardCore.Lucene.Controllers.AdminController|ERROR|Error while executing query System.NullReferenceException: Object reference not set to an instance of an object.
>    at Lucene.Net.Search.IndexSearcher.Rewrite(Query original)
>    at Lucene.Net.Search.IndexSearcher.CreateNormalizedWeight(Query query)
>    at Lucene.Net.Search.IndexSearcher.Search(Query query, Int32 n, Sort sort)
>    at OrchardCore.Lucene.LuceneQueryService.SearchAsync(LuceneQueryContext context, JObject queryObj) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Lucene.Core\LuceneQueryService.cs:line 82
>    at OrchardCore.Lucene.Controllers.AdminController.<>c__DisplayClass24_0.<<Query>b__0>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Controllers\AdminController.cs:line 361    at Lucene.Net.Search.IndexSearcher.Rewrite(Query original)
>    at Lucene.Net.Search.IndexSearcher.CreateNormalizedWeight(Query query)
>    at Lucene.Net.Search.IndexSearcher.Search(Query query, Int32 n, Sort sort)
>    at OrchardCore.Lucene.LuceneQueryService.SearchAsync(LuceneQueryContext context, JObject queryObj) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Lucene.Core\LuceneQueryService.cs:line 82
>    at OrchardCore.Lucene.Controllers.AdminController.<>c__DisplayClass24_0.<<Query>b__0>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Controllers\AdminController.cs:line 361

Note: If I performed the query individually like this:

```JSON
{
    "query": {
        "match" : {
            "AliasPart" : "test"
        }
    }
}
```

It works fine.

**Comment by Skrypt** [comment]
"multi_match" is not currently supported.

**Comment by PauloSRH** [comment]
Ok, thank you for the response.

**Comment by sebastienros** [comment]
@PauloSRH if you are willing to, maybe you could try adding it. It shouldn't be difficult once you understand how the other ones are done.
