### ISSUE TITLE
MySQL Exception in basic OrchardCore CMS deployment without any customization

### ISSUE THREAD

**Issue by ExeedFit** [OrchardCMS/OrchardCore#6296]
Any Idea why I am getting following exception in Debug console.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Diagnostics.Process.dll'. Symbols loaded.
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Runtime.Serialization.Formatters.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Runtime.Numerics.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Runtime.Serialization.Primitives.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.ContentManagement.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.Deployment.Core.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.Feeds.Core.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.Lucene.Core.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.Media.Services.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\SixLabors.Core.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.Identity.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.Authentication.Cookies.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.FileStorage.FileSystem.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.Media.Core.dll'. Symbols loaded.
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.Metadata.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.IO.Compression.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Microsoft.AspNetCore.JsonPatch.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Microsoft.AspNetCore.Mvc.Razor.Extensions.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Microsoft.CodeAnalysis.Razor.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Microsoft.CodeAnalysis.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Microsoft.CodeAnalysis.CSharp.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Microsoft.Extensions.DependencyModel.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.Razor.Runtime.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Globalization.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.Extensions.FileProviders.Embedded.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\SixLabors.ImageSharp.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Diagnostics.Debug.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.WebUtilities.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.AspNetCore.Http.Extensions.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Lucene.Net.Analysis.Common.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\OrchardCore.Contents.Core.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\Microsoft.CSharp.dll'. Symbols loaded.
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Castle.Core.dll'. 
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.TypeExtensions.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.Extensions.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.Emit.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'DynamicProxyGenAssembly2'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Jint.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'E:\GitHub\ExeedFit\KareOptions\KareCMS\karecms\bin\Debug\netcoreapp3.0\Esprima.dll'. 
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'yehsmo2w.3p4'. 
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Net.WebSockets.dll'. Symbols loaded.

**Comment by Piedone** [comment]
I don't see any exception details here. Could you share the Orchard logs (App_Data/logs)?

**Comment by sebastienros** [comment]
Looks like you are not using .NET 3.1 which is a requirement. Might be the issue.
Otherwise please share some repro steps.
