### ISSUE TITLE
Coming soon: Form issue

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6305]
The form is generated two times causing this problem:

![image](https://user-images.githubusercontent.com/703248/83284331-d2383f00-a1dc-11ea-98df-4f81192a8a13.png)

**Comment by ArieGato** [comment]
Is this related? #6267

**Comment by agriffard** [comment]
It must be because of the change that introduced a Form.Wrapper:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Forms/Views/Form.Wrapper.cshtml

@ns8482e Can you please have a look?

**Comment by ns8482e** [comment]
> It must be because of the change that introduced a Form.Wrapper:
> https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Forms/Views/Form.Wrapper.cshtml


@agriffard in the original issue #5801

>If you add the form content part to your custom content type it won't render a form


And required to define `<form>` in every custom content type template to use form part.

After PR #6053  Now, It’s no longer required to define `<form> ` In custom template of content type that has `FormPart` and need to update recipe to remove form tag

**Comment by ns8482e** [comment]
> Is this related? #6267

It Possibly 

> Is this related? #6267

Possible!  try removing `<form>`  tag from the template above and see if it solves #6267 too?

**Comment by ArieGato** [comment]
> > Is this related? #6267
> 
> Possible! try removing `<form>` tag from the template above and see if it solves #6267 too?

Removing the form tag **and** the ```{% antiforgerytoken %}``` solves that issue.
