### ISSUE TITLE
Cannot filter Content Item by TaxonomyField in GraphQL

### ISSUE THREAD

**Issue by pbros** [OrchardCMS/OrchardCore#6306]
I have created a taxonomy and added a Taxonomy Field to a Content Type.

Using GraphQL, I can see the values of the Taxonomy Field (TaxonomyContentItemId and TermContentItemIds). However, there is no way to include these values in a where clause.

I tried creating a `WhereInputObjectGraphType` using `TaxonomyField`, but this does not seem to work, as only the input types referring a Part seem to work as per the code in `TypedContentTypeBuilder`. In the Build() method, it looks for `IInputObjectGraphType` for the "Part", but since this is a field on the content item itself and not a part, it doesn't find the registered `TaxonomyFieldInputObjectType`

```csharp
public class TaxonomyFieldInputObjectType : WhereInputObjectGraphType<TaxonomyField>
    {
        public TaxonomyFieldInputObjectType(IStringLocalizer<TaxonomyField> S)
        {
            Name = "TaxonomyFieldInput";
            Description = S["the taxonomy field of the content item"];

            Field(x => x.TaxonomyContentItemId);
            Field(x => x.TermContentItemIds);
        }
    }
```

If the TaxonomyField was designed as a TaxonomyFieldPart instead, then it would make this possible but require schema change.

This Related to #6010 where after getting the full taxonomy tree, I would need to find the articles in a specific node

**Comment by sebastienros** [comment]
What kind of query are you trying to make? Listing all content item from a taxonomy field?

You can also create a custom SQL Query in the admin and expose it as a graphql one. This way it will do exactly what you want.

**Comment by pbros** [comment]
I wound up creating a new API controller to get the Taxonomy Terms by autoroute path to achieve my objective since the recursive logic was a bit complex (navigating the Taxonomy Term tree). In my case the controller renders the HTML, but it could also have returned the ContentItemId which would then have been used in a GraphQL query.

**Comment by RockNHawk** [comment]
@sebastienros 
I have create a `SQL Query` in the admin, but how can I expose it as a graphql ? I can't find relevant documentation.
