### ISSUE TITLE
Release of ModernBusiness.OrchardCore

### ISSUE THREAD

**Issue by jwu-au** [OrchardCMS/OrchardCore#6308]
Hello Everyone,

In the past a couple of weeks, I have used my spare time to learn OC2, and I have developed a theme as my learning outcome. I'm happy to share with you, and continually learn from you. If you're interested in it, you can head to:
https://github.com/jwu-au/ModernBusiness.OrchardCore

Many thanks to the Orchard Team, and the community.

**Comment by hishamco** [comment]
Thanks @jwu-au for sharing this, I'm glad to add your theme into https://github.com/OrchardCoreContrib/OrchardCoreContrib.Themes if you're interested

**Comment by jwu-au** [comment]
Hi @hishamco , I'm more than happy if you add in. Thank you.

**Comment by hishamco** [comment]
Let me arrange this with you or let you add a PR

**Comment by jwu-au** [comment]
Sure thing, I can definitely do a PR, let me know how do you plan to arrange it such as the folder structure, any special content in readme, and etc. One more thing is that I prefer to maintain one repo for any further updates, and what's your thinking for this?

**Comment by hishamco** [comment]
> let me know how do you plan to arrange it such as the folder structure, any special content in readme, and etc

Sure, let me update the `README.md`

Can we chat on gitter for further details?

**Comment by hishamco** [comment]
@jwu-au I updated the `README.md`, feel free to share your them with Orchard Core community

Thanks

**Comment by hishamco** [comment]
> One more thing is that I prefer to maintain one repo for any further updates, and what's your thinking for this?

You could maintain it in the OCC repo, it's not my or your repo only, it's built for OC community, so it's our repo ;)

In case you need to maintain further details into your repo, no problem we can link to your repo

**Comment by jwu-au** [comment]
@hishamco I created the PR as per your instructions.
https://github.com/OrchardCoreContrib/OrchardCoreContrib.Themes/pull/1
Let me know anything you want me to update. And if you can add a back link to my repo somewhere would be great. 
Ping me anytime in gitter if you want, I'll get back to you as soon as I can. 
Thank you.

**Comment by hishamco** [comment]
Thanks a lot

**Comment by sebastienros** [comment]
Thanks @jwu-au
