### ISSUE TITLE
OpenCart integration

### ISSUE THREAD

**Issue by aprokopyev** [OrchardCMS/OrchardCore#6309]
Hello,

It seems OpenCart is the most advanced open source cart and much better than nopCommerce in terms of amount of plugins.

Please suggest what is the best method to integrate it with your CMS?

There are ready integrations with Wordpress and other PHP CMSes:

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32346
https://wordpress.org/plugins/single-sign-on-sso/

but I need an ASP.net based CMS for a custom programming, I am only a DotNet coder and prefer VB.net or C# over any other programming language.

DotNet code for OneAll looks very old:
https://github.com/oneall/dot-net-sdk

Can you please look at it and give me an idea on how difficult it is integrate that old DotNet OneAll code into your OrchardCore CMS to allow integration with OpenCart?

**Comment by hishamco** [comment]
OpenCart is an ecommerce solution, the Orchard team working on OrchardCore.Commerce module, please follow up its repo https://github.com/OrchardCMS/OrchardCore.Commerce
