### ISSUE TITLE
Store tokens in Document table still is too much

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#6318]
Currently the tokens and authorizations issued are stores at Content table.
As I mentioned in the past, this is too much https://github.com/OrchardCMS/OrchardCore/issues/233

In fact, in the issue mentioned it was solved with a background task that removes outdated tokens.
However I still think this can cause problems with a big site with a lot of grow which consumes the ids counter quickly. At least if you are going to have an app with many users, and all of them obtaining tokens. 
This, together with the fact that maybe your application store some types of documents that will be grow quickly it could lead too soon to be near fo the limits of an int.

So, my proposal is first to send a PR that  moves authorizations and tokens to another document table, using YesSQL Collection.
I've done it for our proyect in a private module, so I can do the same in a PR.

**Comment by jersiovic** [comment]
Well, I will provide that PR if this other PR at YesSQL #241 is approved cause I need the feature added to YesSql for fixing this at Orchard.

In fact if that is done I see feasible in a future PR to add a feature that allows to make configurable the collections where entities of a module are stored

**Comment by jersiovic** [comment]
@kevinchalet is it completly necessary to store all the tokens on db?
In my roadmap I wanted to work on a filter that allows to the server revoke any user issued for an user that has a token creation date before a date.
In that way I don't need to store access tokens in db to revoke them, And  I only need to store revokations for the days can last based on the days you give to its expiration date.
With the new approach for OpenIddict 3.0 you are forcing the server to access db on each request. With that you are killing one of the advantages of using tokens to check identity that is we don't need access db for that.
Doing what I propose you can store in cache revoked tokens while arrive their expiration date. And that cache is queried by the filter to decide if a token is valid.
It is not expected you have too much revocations so its acceptable they are on memory.

**Comment by kevinchalet** [comment]
> @kevinchalet is it completly necessary to store all the tokens on db?

Nothing is 100% definitive. I can and may change the design based on feedback collected during beta1 😄 

> With the new approach for OpenIddict 3.0 you are forcing the server to access db on each request. With that you are killing one of the advantages of using tokens to check identity that is we don't need access db for that.

The **OpenIddict validation handler won't do any DB request by default**. Developers who want to check the token status for each request will have to enable it using `options.EnableTokenEntryValidation()`. A similar option named `options.EnableAuthorizationEntryValidation()` exists for authorization validation.

Also, when I mean token entry, it's only metadata in most cases: only reference tokens are stored with their payload in the database.

**Comment by kevinchalet** [comment]
Looks like YesSql now supports having separate tables per entity. @jersiovic if it's still something you're interesting in implementing, we should probably do it before RTM. Otherwise, it will be a massive breaking change.

**Comment by kevinchalet** [comment]
@sebastienros how complicated would it be to implement a different table per entity type in the OpenID module?

**Comment by sebastienros** [comment]
Can't be simpler. A migration step needs to create table by calling `_store.InitializeCollectionAsync("tokens")` and then use `Save("myToken, "tokens")` or `Query<Token>("tokens")`. There is also an argument in `CreateMapIndexTable` and `RegisterIndexes`.

**Comment by sebastienros** [comment]
Note that a collection can still contain anything, and doesn't enforce a single type. You can even put the same class instances in different collections.
