### ISSUE TITLE
Content Items with Listpart is Confusing

### ISSUE THREAD

**Issue by ziyadsv** [OrchardCMS/OrchardCore#6319]
Instead of naming Edit button, How can I give a different name[Master Page] for the ContentItems with ListPart.

When I click Content - >Content Items ,  Content Items with Listpart and without is showing same. To differentiate i wish to give some other name instead of "Edit" button.

**Comment by hishamco** [comment]
Can you give me an example of what you did? Which content types that are created? Why you need to change the `Edit` label?

**Comment by ziyadsv** [comment]
I have a ContentType named "Projects" having a list (ListPart) of another ContentType "Project". 
lets say another ContentType named "About" 

when we click ContentItems, both Projects and About will listed and showing same design with Title link,Edit,Action button .
 if we click the Titlelink  of About it will show detail page of About. but If we on Projects, it will show anther list of Project (ListPart) and for edit the Project detail we need to click on Edit button.

Here clients get confused. we need some clue to differentiate between the ContentType with **Listpart** and without. So i thought the easiest way is rename the Edit button of ContentType with ListPart. But I dont know how to do.

**Comment by devlife** [comment]
I found this feature incredibly confusing as well. For every other content item I just click the content item name to view/edit it's fields. IMO it would be better to make all of the fields/parts display when you click that link _in addition_ to showing the list part contents. Or even just add a link to the page where you edit the list part contents.

**Comment by hishamco** [comment]
We may add a badge like a stereotype, widget .. etc at least

**Comment by ziyadsv** [comment]
yeah the best way is an additional button or link to show list part contents.

**Comment by ziyadsv** [comment]
@hishamco You are awesome.Thank you ,You save my day ... it working well

**Comment by hishamco** [comment]
I reopen this, it will be closed when the PR is merge ;)

**Comment by deanmarcussen** [comment]
I would suggest that we could consider a button to the right called `List Items` as we did in O1

I dislike the idea of a random badge
