### ISSUE TITLE
Categorized BagPart in Admin

### ISSUE THREAD

**Issue by ziyadsv** [OrchardCMS/OrchardCore#6320]
How can i Categorize the Bagpart with Heading inside the Admin page. Am using multiple Bagpart in one ContentItem. I need to show the bagpart with heading 

I go through the following link to achieve it but unfortunately graphiql  showing error
https://www.davidhayden.me/blog/orchard-core-cms-graphql-using-graphiql

**Comment by deanmarcussen** [comment]
Sounds like two questions in one.

- For the Heading, perhaps you need to add a TitlePart?
- for a graphiql error you might need to check your logs and see what the error is

**Comment by ziyadsv** [comment]
I miss the Titlepart. Thank you very much
