### ISSUE TITLE
ShortCodes Improvements

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6323]
Yesterday I started playing with shortcode, there's already work done by @deanmarcussen in this area, this is just a continuation of what we already have

The aim is to improve many areas including:

- [x] Create Rich APIs, that allow us to manipulate with each piece in shortcode such as tags, attributes .. etc

- [ ] Enhance shortcode by adding `Attributes` collection coz some advance scenario will need to have them

- [x] Make shortcode development easier, so we should focus on the functionality and leave the heavy lifting to the abstraction APIs to do it the repetitive stuff such as shortcodes parsing

- [x] Allow to target multiple shortcodes

This list may increase according to our needs

**Comment by sebastienros** [comment]
Duplicate of #6199
