### ISSUE TITLE
Form Arabic Data not correct when sending Email

### ISSUE THREAD

**Issue by adelemam** [OrchardCMS/OrchardCore#6328]
When Making a form to send an email ( using work flow) , 
all data in Arabic appears at email as rabbish data , like 
**\u0625\u0633\u062A\u0641\u0633\u0627\u0631**

can you help please
@hishamco  ( hope you can help as you are aware of Arabic )

**Comment by sebastienros** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6122
