### ISSUE TITLE
Matomo analytics module

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#6329]
I wrote a matomo analytics module that is very similar to google analytics. Should something like this be in OrchardCore ? If yes, I can make a PR.

https://github.com/StatCan/StatCan.OrchardCore/tree/master/src/Modules/StatCan.OrchardCore.Matomo

**Comment by hishamco** [comment]
If YES I'm happy to be in OC, if NO, I'm glad to add it into OCC https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules

**Comment by Piedone** [comment]
I wouldn't add such very specific features to the official codebase. Probably more along the lines of a generic feature to inject analytics scripts, like our O1 Simple Analytics module: https://github.com/Lombiq/Orchard-Simple-Analytics This has an admin textbox for the analytics script (will be wrapped into `<script>` if it doesn't contain the tag already) and a checkbox to enable it on the admin.

**Comment by Skrypt** [comment]
I really like this module honestly. Great work @jptissot

**Comment by sebastienros** [comment]
Thanks

**Comment by hishamco** [comment]
@jptissot please let me know if you can share this with OCC https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules or I can add it in your behalf

**Comment by jptissot** [comment]
I will most likely publish these to nuget / cloudsmith in the future, so maybe OCC can have a documented link to it ?

**Comment by hishamco** [comment]
No problem, @jptissot coz the aim of OCC is to provide modules, themes and translation that not officially support by OC, but may could, of course we need to point out to the original repo and list him in the credits

Thanks
