### ISSUE TITLE
Cache tag helpers should have environment option

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6331]
When working with menu templates that are cached you have to put `enabled=false` to disable the cache tag helper, or the template changes are not respected.

This is then something you have to disable when finished with the templates, which is easy to forget, and easy to forget when you are working on templates again.

I can use the `<environment` tag helper to alter this behaviour, but it is long winded, and we don't have a similar feature for liquid.

It would be useful to be able to apply an attribute like `cache-environment-exclude="Development">`, and the same for liquid to make this process a bit more seamless.

**Comment by Piedone** [comment]
Probably have this similar to the CDN option?

**Comment by deanmarcussen** [comment]
Yeah good idea, might be better as a system default.

Least that ways when you want to test the cache is working, you can just turn it on and off somewhere

**Comment by sebastienros** [comment]
Setting, based on environment, there is an issue for that already ;)

**Comment by sebastienros** [comment]
I mean a global setting

**Comment by Piedone** [comment]
Site settings and `IOptions` for flexible overrides (per tenant/global/per environment)?

**Comment by sebastienros** [comment]
I'd suggest to do exactly like CDN. Just in the UI, and per tenant. Doesn't need to be more complex. 

Disabled
Enabled
Environment based (prod on, dev off)

I think there is already an option to purge the cache. And if not there might also be an opportunity.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/1868
