### ISSUE TITLE
Controls of "Publish Later" are disappearing on submitting the form with validation errors.

### ISSUE THREAD

**Issue by szilardcsere89** [OrchardCMS/OrchardCore#6332]
# Before submit:
![image](https://user-images.githubusercontent.com/5823033/83654149-fa4ce700-a5bc-11ea-8b64-309b60125e44.png)

---

# After submit:
![image](https://user-images.githubusercontent.com/5823033/83654323-3b44fb80-a5bd-11ea-905b-765c176d3044.png)

It doesn't matter which submit button is clicked.

**Comment by deanmarcussen** [comment]
The `Update` part of the driver is returning to the wrong `Edit` method. It needs to return the same signature as the `Edit` implementation

**Comment by Piedone** [comment]
It used the right one before *somebody* changed it :D. Fixed.
