### ISSUE TITLE
Sometimes Admin Left menu doesn't respond 

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6334]
Sometimes, Admin left menu doesn't respond when click to open sub-menu or try to expand/collapse.
![leftnav](https://user-images.githubusercontent.com/23270244/83659371-09b23d00-a589-11ea-8616-a9d9d69ea43e.gif)

**Comment by ns8482e** [comment]
> That means that this particular page has a javascript error happening before executing the menu javascript.

No error reported in console

**Comment by Skrypt** [comment]
Repro?

**Comment by ns8482e** [comment]
yes its random

**Comment by sebastienros** [comment]
Closing until someone else can experience it, or repro
