### ISSUE TITLE
Create Content Type > Add Html Field > Multiline only shows plain text

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/OrchardCore#6336]
Not sure if this is intended, but if you create an Html Field and select "Mutliline" as the editor in the settings it only shows plain text in the Content Item editor. Whereas if you select "Standard" as the editor, the Html is "prettified".

Here is a screen shot in the Content Item editor showing what I mean:
![image](https://user-images.githubusercontent.com/727061/83694986-338a5480-a5c7-11ea-9f3a-6fdfe31931ea.png)
The top field is using the "Multiline" editor, the bottom is using "Standard".

**Comment by ns8482e** [comment]
That’s awesome isn’t it?  You can configure `HTML Field` Editor to `Multiline` for content type A and `Standard` for content type `B`

**Comment by remesq** [comment]
Actually, that's the same Content Type "A", with two HTML Fields, one with Multiline, the other with Standard. I just thought the behavior was weird. Standard expands with the text you input, but it also doesn't add a line space and formats the HTML, whereas the multiline does neither and is a set height.

**Comment by remesq** [comment]
Woops, did not mean to close unless your comment meant that this behavior is intended.

**Comment by sebastienros** [comment]
@remesq 

@ns8482e was being sarcastic I think. What he means is that each field can provide many ways to edit the content, and if you think an editor is not sufficient then you can always add more to your own system. There are a few out of the box and they definitely don't cover all the requirements.

**Comment by sebastienros** [comment]
And yes, this behavior is what is expected. Not everyone wants or can use codemirror

**Comment by ns8482e** [comment]
> @remesq
> 
> @ns8482e was being sarcastic I think. What he means is that each field can provide many ways to edit the content, and if you think an editor is not sufficient then you can always add more to your own system. There are a few out of the box and they definitely don't cover all the requirements.

 @sebastienros @remesq sorry if you feel that way! Neither intend to offend anyone nor being sarcastic, just exited about having a functionality that can be configured differently

**Comment by sebastienros** [comment]
@ns8482e 

When you said "That’s awesome isn’t it?" about an "issue", I found it sarcastic, and I liked it ;)

**Comment by remesq** [comment]
No worries @ns8482e.
