### ISSUE TITLE
There is no preview part to add

### ISSUE THREAD

**Issue by devhomecali** [OrchardCMS/OrchardCore#6338]
Configuring the Preview feature for Blog Posts [this guide](https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/), you describe: 

- Edit the content definition of Blog Post, click Add Parts, then select Preview. Click Save.
- In the list of parts, for Preview, click on Edit to change its settings for this content type.
- In the Pattern textbox, enter /blogpost/{{ ContentItem.Content.AliasPart.Alias }} which is the way to generate the same URL as the route which is configured in the Razor page.
 

But there is no **Preview Part** at that list of Content Parts.

How can I add the preview part to PostBlog definition type?

[Screenshot](https://github.com/devhomecali/OrchardCore/blob/master/PreviwPart-NoFound.png)

**Comment by deanmarcussen** [comment]
You probably need to upgrade to the preview package feed as I think we added the `Preview Part` after RC1

See the guide here
https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/

**Comment by devhomecali** [comment]
@deanmarcussen Following your suggestion I installed the preview version: **_OrchardCore.Application.Cms.Tarjets v1.0.0-rc1-13380_**. But although the Preview part can now be added to the definition of the BlogPost, it did not solve the described problem. Doing the settings described in the guide for the preview does not have any effect, the custom url does not look: the standard url of the preview is shown.

Image 1: [Preview is added to BlogPost definition](https://github.com/devhomecali/OrchardCore/blob/master/PreviewPart-OnBlogPostDefinition-1.png)

Image 2: [Pattern for Preview](https://github.com/devhomecali/OrchardCore/blob/master/PreviewPart-OnBlogPostDefinition-2.png)

Image 3: [Normal URL for BlogPost content](https://github.com/devhomecali/OrchardCore/blob/master/PreviewPart-OnBlogPostDefinition-3.png)

Image4: [Preview url is not the slug alias pattern](https://github.com/devhomecali/OrchardCore/blob/master/PreviewPart-OnBlogPostDefinition-4.png)

**Comment by sebastienros** [comment]
Can someone else confirm it's broken?

**Comment by ns8482e** [comment]
@devhomecali `Preview` part allows you to configure `PreviewUrl` for `Preview` button in add/edit screen. 

It doesn’t replace ootb content management UI.

You are still able see `view` OOTB screen.

**Comment by deanmarcussen** [comment]
I can confirm the `PreviewPart` is working fine.

![image](https://user-images.githubusercontent.com/13782679/87672141-5ed99500-c76a-11ea-98db-2f7dd6082392.png)

What @devhomecali is expecting as shown in the image above is that the Content Admin List's `View` button would also reflect the url configured in the `PreviewPart`, rather than the standard Content Controller routes.

i.e. the view link being `/blogpost/slug` rather than `Contents/ContentItems/4cqfernmc5qmvz689jnvyen6xh`
