### ISSUE TITLE
When will the final version be released?

### ISSUE THREAD

**Issue by AntonOttoIQ** [OrchardCMS/OrchardCore#6342]
As per your roadmap the initial release was suppose to be in October 2019. Could you please indicate when the final release will be available? The latest release is 1.0.0-RC1

**Comment by jptissot** [comment]
Please see: 
https://github.com/OrchardCMS/OrchardCore/issues/5080
https://github.com/OrchardCMS/OrchardCore/issues/5841

RC2 will be released soon. Everyone is welcome to pitch in and help with PR's to get us closer to an official release.
