### ISSUE TITLE
WidgetsList Part shuffles in UI

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#6344]
Added a WidgetList Part in Custom Content Type and tried to add a widgets more than 15, when previewing the order shuffles. 

Kindly do the needful.

Note : When the number of widgets < 16, the UI works perfectly.

**Comment by thomasebsmith** [comment]
I've noticed the same bug when adding widgets to zones. I'm not very familiar with Orchard Core's codebase, but I did some investigating and it seems like the sorting in [Shape.cs ](https://github.com/OrchardCMS/OrchardCore/blob/a202ae204ac02b40de1c82d6af16468f54e7ccc6/src/OrchardCore/OrchardCore.DisplayManagement/Shapes/Shape.cs) is the problem.

When [widgets are added to a content zone](https://github.com/OrchardCMS/OrchardCore/blob/a202ae204ac02b40de1c82d6af16468f54e7ccc6/src/OrchardCore.Modules/OrchardCore.Layers/Services/LayerFilter.cs#L142), their position is not given to the content zone. Shape.cs calls `List<T>.Sort`, which is not stable for more than 16 elements (see "Remarks" [here](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.sort?view=netcore-3.1)). So, when there are enough widgets, the sort becomes unstable and widgets get out of order.

### Reproducing
1. Create a new Orchard Core CMS project.
2. Start the site, and initialize it with the blog recipe.
3. In the admin settings, add 15 distinguishable paragraph widgets to the "Content" zone.
4. Load the homepage. Note that the widgets are in order.
5. In the admin settings, add 1 more paragraph widget to the "Content" zone, bringing the total to 16.
6. Load the homepage. Note that the widgets are out of order compared to their order in the admin settings.

### Screenshots
![16-widgets-admin](https://user-images.githubusercontent.com/42979377/83771048-5d985100-a671-11ea-98f8-2dbfa6d322df.png)
![16-widgets-homepage](https://user-images.githubusercontent.com/42979377/83771045-5d985100-a671-11ea-9c1a-8707b8466bce.png)

**Comment by ns8482e** [comment]
@sebastienros @deanmarcussen  It seems `WidgetListPart` is missing driver to edit `WidgetMetadata`. It's attaching while saving it but no way to change the position.

`contentItem.Weld(new WidgetMetadata());`

**Comment by TestThej** [comment]
to resolve the above issue in my application i have updated the nuget packages and tested the application , still the issue is persisted. Does anyone tested in these code changes and working fine?

**Comment by jtkech** [comment]
Maybe you updated them from nuget but the fix is only included in the dev branch whose packages are available from the cloudsmith feed, see this commented line in our `Nuget.config` file
