### ISSUE TITLE
Content of BlogPost in not updated

### ISSUE THREAD

**Issue by devhomecali** [OrchardCMS/OrchardCore#6348]
Following the guide https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/#configuring-the-preview-feature-for-blog-posts. 

Following @deanmarcussen's suggestion to solve the problem of (https://github.com/OrchardCMS/OrchardCore/issues/6338), I installed **OrchardCore.Application.Cms.Tarjets package version v1.0.0-rc1-13380**.

But now, the modifications to the content of the post are not recorded. 
[See this video](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Save-BlogPost-Content-no-updated.gif)

**Comment by sebastienros** [comment]
Can to try to go through a new Setup? A Blog recipe has way more fields these days.

**Comment by devhomecali** [comment]
**Describe the bug**
@sebastienros error in new setup

**To Reproduce**
Steps to reproduce the behavior:

1. [Follow this guide](https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/). Configure **LocalDb\MsSqlLocalDb** database and use **dm3** prefix for tables.
2. Change the package: install preview version: **_OrchardCore.Application.Cms.Tarjets v1.0.0-rc1-13380_**.
3. Delete **Sites** subfolder and the file **tenants.json** from the **App_Data** folder 
4. Compile and run the application. 
5. Use the same data from the first Setup: username, email, password, etc, including the same database connection; except that now as a prefix of the tables use **db3-1**.

**Expected behavior**
The database installation must create in the same database all the tables with the prefix db3-1 to differentiate them from those with the prefix db3.

**Screenshots**
[Image](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Re-Setup-SameDatabase.png). The image shows on the left side the tables with the db3 prefix created in the first setup. From the second setup it was only possible to create two tables **dm3-1_Document** and **dm3-1_Identifiers**. The error message is displayed on the right side of the image.

[File: Error detail](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Setup2.pdf)

**Desktop (please complete the following information):**
- OS: Window 10 Pro x64 1809 updated to date
- Browser: Edge  83.0.478.44

**Comment by hishamco** [comment]
@devhomecali we answered to your question about previous error in another thread
