### ISSUE TITLE
Coming Soon with other content type

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6353]
I tried coming soon theme today with custom content types. It seems it’s not usable for content preparation and preview before final theme change at site launch.

**Comment by sebastienros** [comment]
We mentioned that during the triage meeting yesterday and I personally think it's totally fine. It's not meant to be a theme that can be used to create other content types. It's a "single page" site that shows how to use setup a workflow to register email addresses. If we start and try to handle more than that, then it's a never ending story, and we don't have the capacity to support every scenario in every theme. We also mentioned last week the same issue with the Blog recipe, and talked about not applying every single feature we do for a theme to the other ones. I'd rather see guides explaining how to implement something as an example, even if we take a specific template as a base.

I assume we should be clear somewhere in the documentation about this goal. For the end users and also the contributors.

**Comment by ns8482e** [comment]
Ok. my assumption was that `ComingSoon`  theme will allow site owner to set coming soon page and continue to build the website back-end with ability to preview content without changing the theme.

If that is not the intention of the `ComingSoon` theme then, I'll close this issue.
