### ISSUE TITLE
Error installation of the master branch

### ISSUE THREAD

**Issue by devhomecali** [OrchardCMS/OrchardCore#6360]
**Describe the bug**
The installation of the master branch generates an error related to the Drapper component.

**To Reproduce**

1. [Follow this guide Lombiq Training Demo for Orchard Core - Using a full Orchard Core source](https://github.com/Lombiq/Orchard-Training-Demo-Module). Only Point 1: Download master branch.
2. Run command: git clone -b master --single-branch https://github.com/OrchardCMS/OrchardCore.git
3. Run windows command prompt and go to folder **OrchardCore\src\OrchardCore.Cms.Web**. 
4. Run command: dotnet run --urls=http://localhost:5010/
5. Set up the website with the same data from your other OrchardCore CMS setups: super user, email, recipe (Agency) and connection string: configure **LocalDb\MsSqlLocalDb** database and use **dm4** prefix for tables. There are no tables in the database with the prefix dm4, but there are others.

**Expected behavior**
The database installation must create in the same database all the tables with the prefix db4.

**Screenshots**
[Image](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Setup-MasterBranch-1.png).

**Files**

[File: Error detail](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Setup-MasterBranch-1.pdf)

**Desktop (please complete the following information):**
- OS: Window 10 Pro x64 1809 updated to date
- Browser: Edge  83.0.478.44

**Comment by Piedone** [comment]
First of all, thank you for the very thorough bugreport.

Can you confirm this is only an issue with LocalDB? (So e.g. SQL Server or SQLite works?)

**Comment by hishamco** [comment]
I tried to use LocalDb with the `dev` branch and everything work as expected!!

@devhomecali could please try the nightly build instead, may there was a bug in the RC1 release, more specifically in YesSQL

Also check you can check your connection string, before doing anything else
