### ISSUE TITLE
Content item type UI Listing

### ISSUE THREAD

**Issue by hamdiRuwiss** [OrchardCMS/OrchardCore#6363]
Hello, If I make the content type unlistable i don't see it the content items list when the user is admin, but if the user is in another role like contributor or author i still see the content type listable

another question? is it possible for the user in role to manage his own content in the dashboard ,I can see a permission for media to manage his own , but nothing similar for content items. of course apart from writing your own module. thank you

**Comment by hishamco** [comment]
> but if the user is in another role like contributor or author i still see the content type listable

This is weird!!

> I think there's a permission, let me check

**Comment by hishamco** [comment]
FYI there's `Edit own content`, `Delete own content`,  `View own content ` and `Clone own content` permissions, which manage everything related to your content

**Comment by hishamco** [comment]
I can reproduce the bug for show, non listable content
