### ISSUE TITLE
Add ability to reset the admin user from the default tenant

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6365]
I think it's useful if we have an option to reset the tenant admin password from within the default tenant, coz if the password is forgotten for any reason there's no way to access the tenant

**Comment by jptissot** [comment]
You can always reset it in the database. Just replace the hashed password with a hash of a known password ;)

**Comment by Piedone** [comment]
You can use [Lombiq Hosting - Tenants Admin Login](https://github.com/Lombiq/Hosting-Tenants/tree/dev/Lombiq.Hosting.Tenants.Admin.Login) to log in with that admin BTW:

**Comment by hishamco** [comment]
Do you mean user impersonation?

**Comment by Piedone** [comment]
Yes, but across tenants.

**Comment by hishamco** [comment]
I already implemented that a long time ago before, the issue I'm facing is if you setup OC and  accidentally forget the admin there's no option to reset the password, I'm not sure if there's an option to send a OTP to email or SMS for recovery purpose

FYI the question was too old

**Comment by hishamco** [comment]
Seems we added a password recovery through email, so no action needed here
