### ISSUE TITLE
Widget Header Button Toggle Problem

### ISSUE THREAD

**Issue by boraster** [OrchardCMS/OrchardCore#6371]
I am on OrchardCore-1.0.0-rc1 . Expand and collapse buttons are visible at the same time and not working at all.

![widgetslist](https://user-images.githubusercontent.com/31406913/84015956-46b17180-a985-11ea-8847-e555ac5d2a16.png)

Is there anyone else reproducing the same problem?

**Comment by deanmarcussen** [comment]
This was an issue on RC1 which I believe has been resolved on the latest dev.

Please try with the preview feed and reopen if you still have an issue https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/

**Comment by boraster** [comment]
@deanmarcussen Thanks for the reply.
I still experience the problem after preview feed update.
Do I need to update something else additionally?

![preview](https://user-images.githubusercontent.com/31406913/84127179-9193bd80-aa47-11ea-88db-7b43bd4e2199.png)

**Comment by deanmarcussen** [comment]
Did you update your nuget references to use the versions on cloudsmith?

**Comment by boraster** [comment]
@deanmarcussen Yes, I did. Therefore, it seems weird to be still experiencing this problem.

**Comment by deanmarcussen** [comment]
did you clear your cache?

**Comment by boraster** [comment]
Cleared the cache, restarted VS, then restarted PC. Now, I will try to update VS; there seems to be a pending update. Maybe, this is the reason for the weird issue.

**Comment by boraster** [comment]
I cleared the Nuget cache several times after VS update and tried to update the packages in the PowerShell by "Update-Package" command, but it says "no updates are available".

I think I am missing something.
