### ISSUE TITLE
'TwitterClient could not be located' error.

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6373]
Error occuring with the latest version of the source code when I login to the admin:

Error while processing background task 'OrchardCore.Workflows.Timers.TimerBackgroundTask' on tenant 'Default'. System.InvalidOperationException: A suitable constructor for type 'OrchardCore.Twitter.Services.TwitterClient' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

In OrchardCore.Workflows.Services.ActivityLibrary line 22

The Twitter features are enabled.

**Comment by deanmarcussen** [comment]
It's a minor regression from the encoders change. Have commented on the original pr

**Comment by sebastienros** [comment]
Yes, probably go back with HttpClientFactory. We'll have to ensure that it's correctly done though, I changed the code because I think it was not the correct way to do it. It was disposing the HttpClient. But maybe it's ok to do so when using HttpClientFactory.

**Comment by MichaelPetrinolis** [comment]
in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#httpclient-and-lifetime-management says that IHttpClientFactory tracks and disposes resources used by httpclient instances. The TwitterClientMessageHandler instances are pooled and used by created HttpClient instances. And also mentions that keeping a single HttpClient instance for a long duration is unnecessary after migrating to IHttpClientFactory
