### ISSUE TITLE
Displaying .cshmtl files (i.e., partials) through Layout.cshtml

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/OrchardCore#6376]
I'm getting a Shape type "Resources" not found error in my custom Theme layout, where I have a `Resources.cshtml` file in my `~/Views/Shared` folder. 

I am trying to insert it like this:
`@{ await DisplayAsync(await New.Resources()); }`

at the top of my `Layout.cshtml` page, or within that layout `<body>` thusly: 
`@await DisplayAsync(await New.Resources()).` 

I think I saw the answer as to how to fix this here, but now after searching endlessly I cannot find it. 
Currently, I am just using `<partial name="Resources">`, which works. 

So my question is how can I get the Shape to be found using the former techniques?

Thanks in advance.

**Comment by jtkech** [comment]
Only mvc view files can be found under `Views/Shared`, not **shape** template files.

Shape templates are only harvested from the following folders

    public IEnumerable<string> SubPaths()
    {
        return new[] { "Views", "Views/Items", "Views/Parts", "Views/Fields", "Views/Elements" };
    }

As i remember, concretely our modules / themes only have shapes under `Views` and `Views/Items`.

**Comment by remesq** [comment]
Thank you for eliminating my confusion @jktech.
