### ISSUE TITLE
ArgumentNullException for PortableObjectStringLocalizer.

### ISSUE THREAD

**Issue by Shilpa-V** [OrchardCMS/OrchardCore#6382]
I am looking to create custom PortableObjectStringLocalizer for my dotnet core project, which doesn't throw `ArgumentNullException` for null values.
Instead, it should return null for null values. Is this possible?

**Comment by Skrypt** [comment]
Example? I mean, normally these localizations are all strings so how do you plan to set a "null" value for a term?

**Comment by Shilpa-V** [comment]
We are using this for a few dynamic data for which we have created PO file entries. 
At some places we are using dynamic data such as `S[validateExchangeResult.SelectedCommodityName]` so, we need to do explicit check like:

`validateExchangeResult.SelectedCommodityName = !validateExchangeResult.SelectedCommodityName.IsNullOrEmpty() 
? S[validateExchangeResult.SelectedCommodityName] 
: validateExchangeResult.SelectedCommodityName;`

If, we would be able to override the `PortableObjectStringLocalizer` we can have safe call to :
`S[validateExchangeResult.SelectedCommodityName]` without any null check.

**Comment by Skrypt** [comment]
Ok but using dynamic data is not advised to be used for localizable strings. Main reason is that we have a tool that harvests localizable strings to automate the creation of .PO files in your projects. Also, obviously it can throw NRE and if you want to keep using dynamic strings then you should totally make null checks because it's not logical to request for localization of a NULL string... it should never even call the method simply.

**Comment by Shilpa-V** [comment]
Most of the dynamic data we use are reference data and we have defined Enum for them. We wanted to have the responsibility of the caller to check for NRE.

**Comment by Skrypt** [comment]
Well, wait for @sebastienros answer on that one.

**Comment by hishamco** [comment]
IMHO dynamic data is fine, it doesn't support yet in OC, but hopefully after 1.0.0 release, for your case you could simply subclass the `PortableObjectStringLocalizer` and do the null check there, so it will be central and no need to do it everywhere

Another options we can go for it if everyone agree, to introduce lookup behavior, in case the value is missing:

- Return the key

- Throws an exception

also we could accept in this case

**Comment by Shilpa-V** [comment]
Dynamic data is working fine for me in my case. Subclassing the `PortableObjectStringLocalizer` is enough or will it also require to create `CustomPortableObjectStringLocalizerFactory`.

**Comment by hishamco** [comment]
Unfortunately you need to create a custom `PortableObjectStringLocalizerFactory` to instantiate the localizer, I think we need to modify it to make it easier to extend, something like what I did before here https://github.com/hishamco/My.Extensions.Localization.Json/blob/master/src/My.Extensions.Localization.Json/JsonStringLocalizerFactory.cs#L78-L87

**Comment by Shilpa-V** [comment]
Anyway, I succeed to resolve my issue without the need of extending `PortablePbjectStringLocalizer.cs`.
Just FYI, I have extended `StringLocalizer` and it worked for me.
Thanks for the help and time.

**Comment by hishamco** [comment]
How? while you are working with PO files?

**Comment by Shilpa-V** [comment]
As on the initial stage when I am loading an instance of `IStringLocalizer<T>` within my constructor DI, it is getting loaded with `StringLocalizer` instance.
Hence, before it hits `PortableObjectStringLocalizer`'s indexer, it hits `StringLoclizer`'s indexer.

**Comment by hishamco** [comment]
I see .. so I will close this
