### ISSUE TITLE
I want to Change the route of CMS admin Panel ! 

### ISSUE THREAD

**Issue by MuhammadTalha10** [OrchardCMS/OrchardCore#6392]
The current route is "/admin" is there any possibility that i can change it to something like "/cms" or "/adminpanel" ?

**Comment by MuhammadTalha10** [comment]
@jtkech  its still same this is my appsetting.json
`{
  "ConnectionString": "Server=tcp:magna.database.windows.net,1433;Initial Catalog=Magna;Persist Security Info=False;User ID=alchemative;Password=Avaya@1209;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;",
  "DatabaseProvider": "SqlConnection",
  "OrchardCore.Media.Azure": {
    "ConnectionString": "DefaultEndpointsProtocol=https;AccountName=magnastorageaccount;AccountKey=FpJmROX6TY3UBUyHUs7NVe2eHLnXMPS6iZJ5fs4Jc+kC/2nsPIeUoa7m/Zjyhxc+w8grPBqlM17t6/gofZPeGQ==;EndpointSuffix=core.windows.net",
    "ContainerName": "magna"
  },
  "OrchardCore": {
    "OrchardCore_Admin": {
      "AdminUrlPrefix": "MagnaAlche"
    }
  }
}`

**Comment by deanmarcussen** [comment]
What version of OC are you using ?

**Comment by MuhammadTalha10** [comment]
OrchardCore.Application.Cms.Targets 1.0.0-rc1-10004

**Comment by deanmarcussen** [comment]
The feature you are trying to use was added after RC1 was release.

You can upgrade to the preview feed here https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/

**Comment by MuhammadTalha10** [comment]
its working fine with RC2 latest prerelaese. thanks @deanmarcussen

**Comment by Jetski5822** [comment]
@MuhammadTalha10 you might want to hide those credentials in your post

**Comment by BenedekFarkas** [comment]
> @MuhammadTalha10 you might want to hide those credentials in your post

It's no longer valid, but I removed it from that message, because it shows up as a secret scanning alert.
BTW good job GitHub. :)
