### ISSUE TITLE
MySQL Migration Error with Agency Theme

### ISSUE THREAD

**Issue by boraster** [OrchardCMS/OrchardCore#6398]
I ran into an error recently. There is no problem with Sqlite. Blog theme does not cause any error as well both in Sqlite and MySQL. I didn't try out other themes.

I am on Preview Feed (rc2-13391) and used a couple of fresh install to make sure. 
MySQL version is 5.7.28
When I check the Debug.log I see several "**Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll"** error back to back with **"Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll"**

Then, the first meaningful message is **"OrchardCore.Data.Migration.DataMigrationManager: Error: Error while running migration version 0 for 'OrchardCore.Liquid'."**

There is no InnerException message available (it is null). By the way, DataMigrations array is also null at the db table.

**Comment by Skrypt** [comment]
Probably related with the creation of indexes and their length.

I would recommend, for now, using PostgreSQL as it seems we have some details to fix with MySQL.

**Comment by hishamco** [comment]
> Blog theme does not cause any error as well both in Sqlite and MySQL.

@boraster Could please let us know which theme causes the error?

If there's a typo and you meant the blog theme has causes the issue, I will try with my local MySQL version

**Comment by boraster** [comment]
@Skrypt  thank you for the suggestion. Where do you think the problem might arise from? As I looked thru the previous issues, index length problem seems to be solved sometimes ago. 

@hishamco I tried both Agency and Blog themes with both Sqlite and MySQL (local). Only Agency theme seems to have problem with MySQL; other combinations work as expected.

**Comment by boraster** [comment]
I got the same errors with Agency theme and PostgreSQL (local) as well. 

_Version:_ PostgreSQL 9.1 
_Port:_ 5432
_Theme:_ Agency
_Errors:_ **Exception thrown: 'Npgsql.PostgresException' in Npgsql.dll** && **Exception thrown: 'Npgsql.PostgresException' in System.Private.CoreLib.dll** (Several times back to back like MYSQL) _Then:_ **OrchardCore.Data.Migration.DataMigrationManager: Error: Error while running migration version 0 for 'OrchardCore.Liquid'**

With Blog Theme, I see same errors mentioned above also several times, but then migrations are being completed and system works as expected.
![Ek Açıklama 2020-06-13 150425](https://user-images.githubusercontent.com/31406913/84568316-36373780-ad87-11ea-8380-3a164a2e0604.png)

**Comment by hishamco** [comment]
I got confused little bit, when the exception shows up, before or after the setup?

**Comment by boraster** [comment]
@hishamco exceptions occur during setup. The only difference between Blog and Agency seems to be that Agency fails with DataMigration problem, yet Blog goes thru and completes the setup and works as expected.

**Comment by hishamco** [comment]
Let me try both, I will try them with the latest bits ...

**Comment by hishamco** [comment]
I test both with MySQL 5.7.14, all are working as expected

**Comment by hishamco** [comment]
I don't think there will be a major changes on 5.7.28, while it's a bug fixing release

**Comment by boraster** [comment]
@hishamco Can you please tell me your steps for cross-checking my configuration?

**Comment by hishamco** [comment]
I create SAAS app using the source with the mentioned database version, nothing fancy here

**Comment by boraster** [comment]
@hishamco I am able to successfully create Agency with MySQL after setting up SaaS, yet it is not possible to directly set up an Agency theme as a "stand-alone" recipe. Can you please confirm if this is the case with you?

**Comment by hishamco** [comment]
Hopefully I will check it today ...

**Comment by hishamco** [comment]
@boraster I tried the blog theme with the latest source everything is fine, you could try too.

I will close this for now, feel free if this issue happen again
