### ISSUE TITLE
Description for NuGet packages

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6404]
All packages just have "Package Description" now. However, we don't want to write descriptions for all individual packages (unless someone is masochistic enough) so a better thing would be to generate it somehow.

- For projects with a Manifest include the descriptions from there.
- For other projects use a common template.

In both cases, the text could include something like:

> Orchard Core is an open-source, modular, multi-tenant application framework and CMS for ASP.NET Core. For detailed information about Orchard Core, and for documentation on how to use it and integrate it into your app see https://www.orchardcore.net/.

**Comment by sebastienros** [comment]
Also add tags /cc @ns8482e

**Comment by hishamco** [comment]
@ns8482e is this done?!! I saw both issue are closed?

**Comment by ns8482e** [comment]
> @ns8482e is this done?!! I saw both issue are closed?

Working on it! Other linked are closed as are duplicates of this
