### ISSUE TITLE
Can't override ZoneShapes

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6407]
I was trying to override the `ContentZone` implementation in `ZoneShapes.cs` to get some different behaviour for some tabbed shapes, but could not, because it is not attributed with 
`[Feature(Application.DefaultFeatureId)]`

I've just removed the service descriptors for it instead, but was there a reason it didn't get attributed along with the other core shapes @jtkech ?

**Comment by jtkech** [comment]
Yes we created `Application.DefaultFeatureId` to allow core shapes to be overridden (#4210)

> but was there a reason it didn't get attributed

No, just because i missed it, maybe just because `ZoneShapes.cs` is not in the same folder ;)

**Comment by ns8482e** [comment]
I guess you can define alternate and wrappers.
