### ISSUE TITLE
Exception: MessageId can't be empty. 

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#6409]
I just added new culture to my web site, then I got this error.

![l1](https://user-images.githubusercontent.com/24512878/84498168-67910400-acb0-11ea-877d-71b9215557ec.JPG)
![l2](https://user-images.githubusercontent.com/24512878/84498170-695ac780-acb0-11ea-9c74-b716de4bc38b.JPG)

**Comment by hishamco** [comment]
Are using the latest bits? If YES, please let us know the reproduce steps

**Comment by aghili371** [comment]
> Are using the latest bits? If YES, please let us know the reproduce steps

mm. i don't know which version was. but it was about one week ago. i will test again with same database.

**Comment by agriffard** [comment]
Reopen if it is still occuring, with repro steps.

**Comment by intellimedhu** [comment]
@aghili371
Do you remember what was the solution? I have the same issue after upgrade (net6, 1.4.0)
