### ISSUE TITLE
Timer Event halt the workflow and will not resume it

### ISSUE THREAD

**Issue by hamdiRuwiss** [OrchardCMS/OrchardCore#6424]
I have been playing with workflow feature in orchard core and it is powerful feature ,I noticed the timer activity will work if set as a start activity in the workflow but it will halt and never resume the workflow if it come after another activity like content published event or content update task .

**Comment by jtkech** [comment]
Which version? Normally it has been fixed by #6124 that is part of the new rc2 release

**Comment by hamdiRuwiss** [comment]
1.0.0-rc1-13031

**Comment by jtkech** [comment]
Okay, you would have to use 1.0.0-rc2-13450

I close the issue, feel free to reopen it if you still have any problem
