### ISSUE TITLE
Invalid serial number for shell descriptor Error

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#6426]
I am constantly getting the following error when trying to setup a new tenant:
![image](https://user-images.githubusercontent.com/22512098/84607045-db7e0880-ae78-11ea-9146-943ec13930d5.png)

I am not familiar with the terminology used here and therefore don't know where to look in order to further debug. Where exactly is this serial number getting generated ? 

When I look at priorSerialNumber it is set to 0, while serialNumber is set to 3 ?

**Comment by jtkech** [comment]
Which version? Can you share the recipe you used?

Looks like something went wrong in a recipe step

Would need more infos, a more complete satck trace

Do you have some errors logged under `App_Data/logs`?

**Comment by JoshLefebvre** [comment]
Hey jtkech,

I was running a custom recipe. I haven't confirmed but I am pretty sure I was forgetting to set my database prefix string which resulted in a conflict. Thanks for pointing me in the right direction

**Comment by jtkech** [comment]
@JoshLefebvre Cool then ;)

**Comment by nikeshmhrzn** [comment]
InvalidOperationException: Invalid serial number for shell descriptor

I am facing the same issue how do we resolve it ?

**Comment by jptissot** [comment]
@nikeshmhrzn I think you need to restart the site.

**Comment by jtkech** [comment]
@nikeshmhrzn 

I saw your comment on gitter

> I got this error while implementing new theme in orchard core.

Which version are you using? Did you just enable a new theme? OR run its recipe through the admin UI? OR by selecting its recipe on a new fresh setup?

E.g. if you delete a tenant folder, then re-do a setup but pointing to a database where a shell descriptor already exists and with a different serial number

**Comment by Piedone** [comment]
I've seen this happening but have no idea how to reproduce it; the exception itself tells that the shell' state (like which features are on/off) is out of sync between the DB and what's loaded into memory in the app. In any case, an app restart should solve it.
