### ISSUE TITLE
Orchardcore-preview: are the daily builds working yet?

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#6430]
I cannot update anymore my files to the latest version using the feed:

`https://www.myget.org/F/orchardcore-preview/api/v3/index.json`

Is this still working after the RC2 release or has it been taken offline for any reason? Visual Studio 2019 does not show any updates available anymore. My files are version 1.0.0-rc1-13433 (from last Thursday).

Aren't there anymore daily builds since that one or something is wrong?

Thanks.

**Comment by agriffard** [comment]
We are now publishing on this feed:
`https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json`
See https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/
