### ISSUE TITLE
How to exclude App_Data from publish?

### ISSUE THREAD

**Issue by micnyk** [OrchardCMS/OrchardCore#6431]
When I publish my Web App to Azure, my local App_Data is also being published and it overrides Azure's environment settings. I tried every solution I found on the web and none of them worked.
I suppose it's because of this file https://github.com/OrchardCMS/OrchardCore/blob/c110128693ae52cd5a6864993df64f7f0db071b2/src/OrchardCore/OrchardCore.Application.Cms.Core.Targets/OrchardCore.Application.Cms.Core.Targets.targets
that excludes App_Data from projects and adds it as a folder to publish.
Now I have no idea how to overwrite that.

**Comment by jtkech** [comment]
@micnyk add this in your app project file


    <PropertyGroup>
      <DefaultItemExcludes>$(DefaultItemExcludes);App_Data\**</DefaultItemExcludes>
    </PropertyGroup>

**Comment by micnyk** [comment]
@jtkech it doesn't work, I still got App_Data when publishing
![image](https://user-images.githubusercontent.com/13575087/84747278-58170100-afb7-11ea-8907-617cd13edc50.png)

My .csproj:
`<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <PreserveCompilationReferences>true</PreserveCompilationReferences>
        <UserSecretsId>f2cc17fc-81a2-425c-9680-1db5ff1cf224</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.AspNetCore" Version="9.0.0-preview4"/>
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.14.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.4"/>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.2"/>
        <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-10004"/>
        <PackageReference Include="OrchardCore.Logging.Serilog" Version="1.0.0-rc1-10004"/>
        <PackageReference Include="OrchardCore.Navigation.Core" Version="1.0.0-rc1-10004"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BigDataPortal.Theme\BigDataPortal.Theme.csproj"/>
        <ProjectReference Include="..\BigDataPortal.UseCaseManagement\BigDataPortal.UseCaseManagement.csproj"/>
        <ProjectReference Include="..\BigDataPortal.Users\BigDataPortal.Users.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <DefaultItemExcludes>$(DefaultItemExcludes);App_Data\**</DefaultItemExcludes>
    </PropertyGroup>
</Project>
`

**Comment by jtkech** [comment]
You would need to update to rc2

In `OC.Application.Cms.Core.Targets.targets` we now use `DefaultItemExcludes`

    <ItemGroup>
      <ResolvedFileToPublish Include="App_Data\**" Exclude="$(DefaultItemExcludes);App_Data\**\*.log">
        <RelativePath>App_Data\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
      </ResolvedFileToPublish>
    </ItemGroup>

This was not the case in rc1

    <ItemGroup>
      <ResolvedFileToPublish Include="App_Data\**" Exclude="App_Data\**\*.log">
        <RelativePath>App_Data\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
    </ResolvedFileToPublish>
