### ISSUE TITLE
Null Reference Exception On All Content Items After Modifying Content Type

### ISSUE THREAD

**Issue by andrew2241** [OrchardCMS/OrchardCore#6433]
The issue that I am facing is that I created a content type for images. I used this content type when creating all my page content items.  After some time I realized that I was missing some fields so I went back to the Image content type definition and added the fields and modified the alternate view. These changes caused every page content item that has the image content type as part of it to now throw a null reference exception because I reference the new fields in the alternate view.

I understand why this happens and I am able to remedy this by republishing each page. 

Where I think there might be a bug is that I tried to do the bulk publish in the admin. That approach did not work. So I need to click on each page content item in the admin and then publish to fix this issue.

Is this functioning as designed or should the bulk publish option work?

**Comment by jtkech** [comment]
When editing and then publishing the json data of the content item are populated with the missing fields, when only publishing a content item (e.g. through a bulk action) only the published / latest states are updated, so yes it is a designed.

Can you show us your alternate view code to see if it is simple to just add a null check

**Comment by andrew2241** [comment]
@jtkech Here is my alternate view code, I do have null checks in there:
`<figure>
    <picture>
        @if (Model.ContentItem.Content.BagPart != null)
        {
            foreach (var item in Model.ContentItem.Content.BagPart.ContentItems)
            {
                string path = item.ImageSourceForPictureSourceSet.SourceSetImage.Paths[0];
                path = path.Replace("\"", "");
                string srcPath = "/media/" + path;

                <source media="(@item.ImageSourceForPictureSourceSet.MediaStyling.Text)" srcset="@srcPath" />
            }

        }
        @if(Model.ContentItem.Content.Image.ImageLink.Url != null && !string.IsNullOrWhiteSpace((string)Model.ContentItem.Content.Image.ImageLink.Url))
        {
            @:<a href="@Model.ContentItem.Content.Image.ImageLink.Url" target="@Model.ContentItem.Content.Image.ImageLinkTarget.Text">
        }
        <img src="~/media/@Model.ContentItem.Content.Image.Image.Paths[0]" alt="@Model.ContentItem.Content.Image.AltText.Text" />
        @if(Model.ContentItem.Content.Image.ImageLink.Url != null && !string.IsNullOrWhiteSpace((string)Model.ContentItem.Content.Image.ImageLink.Url))
        {
            @:</a>
        }
    </picture>
    @if(Model.ContentItem.Content.Image.FigureCaption.Text != null || !string.IsNullOrEmpty((string)Model.ContentItem.Content.Image.FigureCaption.Text)) {
        <figcaption>@Model.ContentItem.Content.Image.FigureCaption.Text</figcaption>
    }
</figure>
`

**Comment by jtkech** [comment]
Hmm, i think that here `ImageLink` may be null, so try to use

    Model.ContentItem.Content.Image.ImageLink?.Url != null

**Comment by andrew2241** [comment]
@jtkech Thank you very much for your suggestion.  It worked out for me.  I appreciate you and your time.
