### ISSUE TITLE
Software theme request

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#6434]
It would be nice to have a theme for software or app downloads.  This is a pretty common scenario.  There would be screenshots of your app and links to download the windows version or the android version or the IOS version etc etc.  Maybe I ill look for a bootstrap theme where this is already done and open for Orchard to use.

**Comment by hishamco** [comment]
Not every theme we should include out of the box, but it's glad to create one for the community here https://github.com/OrchardCoreContrib/OrchardCoreContrib.Themes

**Comment by hishamco** [comment]
@JoshTango If you have an interest we can design it there ...
