### ISSUE TITLE
Image shortcode doesn't work in Html Field

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6435]
1. Set up site with the Blog recipe.
2. Change the Raw Html Widget's Html Field to use the Trumbowyg editor.
3. Add a Raw Html widget to a Page.
4. Insert Media (any image provided by the recipe).
5. The shortcode `[image]post-bg.jpg[/image]` will be inserted but the image is not rendered on the frontend (just the literal shortcode).

The shortcode work properly with the HtmlBody Part using the Trumbowyg editor.

**Comment by deanmarcussen** [comment]
It's related to the `RawHtml` template, which renders the html contents directly, rather than using the driver.

I thought I'd written a liquid filter for shortcodes, but I can't see it anywhere, so must have forgotten.

Will have to write one. 

Good find @Piedone

**Comment by ns8482e** [comment]
@Piedone @deanmarcussen It’s really getting confusing for end users between `Paragraph` `Html` `RawHtml` and `Liquid` Content types when all has support for codemirror and wysiwyg editors

**Comment by ns8482e** [comment]
IMO `Liquid` and `RawHtml` as name suggests, should output as is without any processing

**Comment by deanmarcussen** [comment]
Well yes, @ns8482e obviously `RawHtml` is a `Widget` content type which is not intended to take be changed to a wysiwyg editor, but I think @Piedone was just testing things here, and he did find an issue with the template, which is that it shouldn't be rendering liquid, and should be rendering shortcodes, which could be used in a `RawHtml`.

In the real world, of course you would make a new `ContentType` `Widget` for a `Wysiwyg` variant, and then you would make a template for it. But you may well copy the `RawHtml` template, for example.

Equally the sample `Widgets` that come with the blog recipe, are examples only, and we would anticipate users creating ones with names that suit them, for the behaviour / editor they choice to have.

**Comment by ns8482e** [comment]
@deanmarcussen I understand the test scenario that @Piedone is validating.  

However here my ask would be -  not to change the template to accommodate support of all available editors, instead it should restrict content type's field editor to selected editors via recipe for the intended use of the content type- i.e. If `RawHtml`  is intended for `<html>`  source then it should be restricted to only `CodeMirror` and/or `Multiline` via recipe and should now be allowed to changed to any other editor.

Ideally it should also not support liquid syntax.
