### ISSUE TITLE
Add ability to set Super User at Tenant Creation, instead of Tenant Setup

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#6442]
Just like we currently allow for setting up the Database Provider and Connection String at either the Tenant Creation time or the Setup time, would it be possible to do something similar with the super user?

I am not sure if this is a common use case, but I currently have the current workflow for setting up new client tenants:
1. Default Tenant Super User (me) creates new tenant for a client and during "Tenant Creation" sets up the new Tenant super user (me).
2. Use my new OnTenantCreated Event activity workflow to send the new client email with encoded url for new tenant setup (PR: https://github.com/OrchardCMS/OrchardCore/pull/6438)
3. Extend the existing Tenant setup page to allow the client to add some setup information about his new tenant and create him as a regular admin instead of a super user. I never want a client to have super user privileges.

![image](https://user-images.githubusercontent.com/22512098/84846736-6bf54e00-b01d-11ea-9762-7ef694707a5b.png)

**Comment by hishamco** [comment]
May be related to #6365

**Comment by jptissot** [comment]
I would flip this around, and build a custom form and ask for the additional fields. This form would post to a workflow where you would create a tenant, send you the superuser credentials and also create a user for this tenant with specific roles you choose.

**Comment by jptissot** [comment]
I am also building a system where people will be able to create tenants but we do not want them to have the SuperUser role. We might be missing some workflow tenant activities (CreateTenantUser ?) but I think my goal is similar to yours.

**Comment by JoshLefebvre** [comment]
> I would flip this around, and build a custom form and ask for the additional fields.

So this is exactly how I had started off. I was hard coding everything for new tenant creation/setup and duplicating a lot of the tenant creation and setup logic in a custom module I was working on to accomplish my custom flow. However I found this to be too rigid, seeing as everything was hardcoded, including sending of emails. This would have been a nightmare to maintain.

I later discovered workflows, which allow me to be more dynamic and change steps on the fly. However I am running into problems here as some of the workflow activities I require don't exist yet.
That being said, I think the next logical step would be a hybrid approach. Creating a custom form as you had mentioned and as I was previously doing, and integrating this with tenant creation workflows.

I need to think about this a little more but if our goals align I might send you a PM to see if there is anywhere we could collaborate.

**Comment by JoshLefebvre** [comment]
@jtkech or anyone else who might know. I am currently trying to extend the _OrchardCore.Setup_ module to add some custom logic for my own personal project. I have created a new module called _OrchardCore.CustomSetup_.

In my custom module startup.cs I have the following lines in order to route to my custom setup controller:
```
            routes.MapAreaControllerRoute
            (
                name: "CustomSetup",
                areaName: "OrchardCore.CustomSetip",
                pattern: "setup/{token}",
                defaults: new { controller = "CustomTenantSetup", action = "Index" }
            );
```

However this endpoint only works on tenants that are in the "running" state and have been initialized. What is special about the the OrchardCore.Setup module that allows its controller methods to be called from a tenant that isn't initialized ? For example:

**The following work:**
https://localhost:44300/setup/CfDJ8Bsg...
https://localhost:44300/tenant2/token?CfDJ8Bsg...
**While this does not:**
https://localhost:44300/tenant2/setup/CfDJ8Bsg

**Comment by jtkech** [comment]
@JoshLefebvre this is in `AddOrchardCms()` that we call

                .AddSetupFeatures("OrchardCore.Setup")

which registers at the app level a `ShellFeature` whose id is `OrchardCore.Setup`. So one solution would be to create your own `AddMyOrchardCms()` that would call

                .AddSetupFeatures("OrchardCore.CustomSetup")

We have other helpers as `AddGlobalFeatures()` and `WithFeatures()` that register `ShellFeature` at the app level, but if there are not used another solution is to just replace in your app startup the one registered by `AddSetupFeatures()`.

Too lazy to try it but i think that the following works, if not we will find another simple solution ;)

            var builder = services.AddOrchardCms();

            builder.ApplicationServices
                .Replace(ServiceDescriptor.Transient(sp =>
                    new ShellFeature("OrchardCore.CustomSetup")));

**Comment by JoshLefebvre** [comment]
Ahhhh yes, simply add the setup feature wokred :) ! Thanks @jtkech . I will be closing this issue soon. Just wanted to share my new custom flow for those who are interested first.

**Comment by JoshLefebvre** [comment]
So I just wanted to share my new custom flow before closing this issue. My flow is very customized to my business needs so I don't think there is any code worth submitting as PR but I am likely going to write a blog post on my process with more detail. 

**Goal:**
Create new Tenants from my default tenant and automate emailing the tenant admin a link for "Tenant Setup" through workflows. 

**Reason**
Tenant Admins will administrator their own sites and I never want to give them "Super User" privilege. Using a custom setup module will allow me to create the new tenant admin with a specific role and use a default account for the SuperUser that only I will have access to. 

**Steps**
1. Extend ShellSettings.cs to add a new field called "AdminEmail".  Add new field to the Create.cshtml and Edit.cshtml to supply the admins email.
2. Use the new Workflow event for OnTenantCreated as part of my PR: https://github.com/OrchardCMS/OrchardCore/pull/6438 . Currently on hold due to issues with distributed workflows (this doesn't affect me right now)
3. Use my NewTenantCreatedWorkflow.recipe.json that will use the tenant admin email in step 1 to email the new tenant admin a url for tenant setup: https://github.com/JoshLefebvre/OrchardCore.CustomSetup/blob/master/Recipes/NewTenantCreatedWorkflow.recipe.json
4. Use my [OrchardCore.CustomSetup](https://github.com/JoshLefebvre/OrchardCore.CustomSetup) module that will extend the existing SetupModule. This module will allow me to create a default "SuperUser" using settings read from IConfiguration and instead create the new Tenant admin user with a specific role. 
5. Further extend the CustomSetup module to include other tenant setup settings such as site logo and favicon that the new tenant admin can fill out: https://github.com/JoshLefebvre/OrchardCore.CustomStyleSettings   (still in progress)

CC: @jptissot
