### ISSUE TITLE
Special characters in Link Field are not allowed.

### ISSUE THREAD

**Issue by PixPunch** [OrchardCMS/OrchardCore#6443]
Hi again.
I'm wondering why at some places special characters allowed but at other are not allowed?

### User story
I want to have page with special character in permalink which can be opened by site visitors by site  menu or a button within a slider.
One of the slides should should have link to the page with special character "ø". 

### Details
Default system configuration (rc1-13433).

**Page**
Permalinks with special characters and menu items are allowed - all fine.

**Menu item**
For example at TheBlogTheme I'm allowed to save "~/lønn". That's fine.

**Banner**
Let's say we have `BannerSlide` content type which has `Media Field` and `Link Field`. 
I set to URL input field to "~/lønn" ("payment" from Norwegian), as at Main Menu.
On save I receive system error message "lønn is an invalid url.".

At the same time when you edit configurations of `Link Field`, you have there a field "Watermark for the url" which allows you to set placeholder with special character "http://lønn...".

So that confuses me a little.

**Conclusion**
It looks like `Link Menu Item` and `Link Field` validation rules are not the same. 

Is it done on purpose or can be a task for UI improvements?

**Comment by ns8482e** [comment]
> `Link Field`.
> I set to URL input field to "~/lønn"

`Link Field` is validated using `Uri.IsWellFormedUriString ` https://docs.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring?view=netcore-3.1

**Comment by PixPunch** [comment]
Thank you for feedback, @ns8482e. 
Friend of mine says that it's strange:
`Uri.IsWellFormedUriString("https://www.yourdomin.no/lønn/", UriKind.RelativeOrAbsolute) `
returns "true". So it should not be an issue. But I'm not going to argue about back-end part - I'm not right person :)

Just **as regular user** it's weird for me that I can save "lønn" as link at menu item, as permalink of a page and at the same time can't use it as a LinkField (part of the banner in my case, which can have internal and external links).

So it looks as inconsistent behavior for content managers, according to feedbacks I have received.

**Comment by PixPunch** [comment]
@ns8482e, thank you for your time. My bad.
I understood what the issue was. I was trying relative URLs instead of absolute at the link field.
