### ISSUE TITLE
IWorkflowExpressionEvaluator.EvaluateAsync  breaking change

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#6444]
This code used to work

```await _expressionEvaluator.EvaluateAsync(Folder, workflowContext);```

but now in RC2 it takes three parameters, `System.Text.Encodings.Web.TextEncoder`. What shall I supply here?

**Comment by dodyg** [comment]
Code like this https://github.com/OrchardCMS/OrchardCore/blob/67ca5546955190e8b338aa547a1b1099a774f868/src/OrchardCore.Modules/OrchardCore.Email/Workflows/Activities/EmailTask.cs#L81 is passing null value.

**Comment by deanmarcussen** [comment]
You need to decide how you want your workflow expression encoded, html, javascript, etc.

You can inject any of these direct from your constructor, as they are registered by ASP.NET core

e.g. inject `HtmlEncoder` for the html encoder or `JavascriptEncoder` for the javascript.

There's a guide for customizing them
https://docs.orchardcore.net/en/dev/docs/guides/encoding-settings/

What's this particular workflow task doing?

**Comment by dodyg** [comment]
Processing something like this

```
{
  "sourceContentItemId" : "{{ Workflow.Input.ContentItem.ContentItemId }}"
}
```

So I assume JavascriptEncoder is the right choice.

**Comment by sebastienros** [comment]
@dodyg correct. The idea is that the value you are injecting might contain some Json chars which would break the final document that is created. So in this case Javascript is the correct encoder. You can still use `| raw` if you know that the variable is json compatible. And you know it's not "user provided".

Some other tasks like Email, will have to evaluate HTML fields, and use the HtmlEncoder.

Note that you should "resolve" the encoders from the DI.
