### ISSUE TITLE
Implement Cards for admin placement

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6446]
We should carry this recent improvement to O1 over to OC
https://github.com/OrchardCMS/Orchard/pull/8310

I think we can make a Column modifier in here work as well

**Comment by hishamco** [comment]
This is cool, but I think tabs can organize the fields too, unless the fields per tab are too much

**Comment by sebastienros** [comment]
Are there any other things we mentioned last time we talked about it? Like maybe other properties that would make sense to be able to set on these?

**Comment by deanmarcussen** [comment]
I think I can make a columns property useful.

There were concerns about columns not being useful because of height mismatches between cards but I think I can make it work with flex

**Comment by deanmarcussen** [comment]
It needs a modifier for a position for each tab/card as well.

**Comment by ns8482e** [comment]
@sebastienros @deanmarcussen I have made some improvements on ContentCard in PR #6298. Preferably we could enhance that PR and use same shape by creating a method that Harvest ContentCard from placement similar to tab harvest method
