### ISSUE TITLE
Use multiple layout files

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#6447]
Hi,

I'm trying to use multiple layout files for my site. The home page differs too much in construction from the rest that I can't achieve it with widgets on layers.

I read the documentation and searched in the OC code base, but I couldn't find anything.
Is it possible to define alternates for the layout.cshtml or layout.liquid?

In OC1 there was an Orchard.DesignerTools module that handled url based alternates. Is that the way to go about it?

Thanks,
Arjan

**Comment by remesq** [comment]
This helped me to get a Layout system working https://github.com/OrchardCMS/OrchardCore/issues/5041.

**Comment by Piedone** [comment]
While there is no built-in feature for this you can create your own alternate for the Layout shape when the path matches the homepage's. On how to add alternates see e.g. `OrchardCore.Contents.Shapes`.

**Comment by ArieGato** [comment]
> While there is no built-in feature for this you can create your own alternate for the Layout shape when the path matches the homepage's. On how to add alternates see e.g. `OrchardCore.Contents.Shapes`.

You mean adding an alternate by adding a placement.json file in the root of the project file?

**Comment by ns8482e** [comment]
To change layout In Razor, use
```
{
    ViewLayout = "CustomLayout";
}
```
or In liquid, Use

`{% layout "CustomLayout" %}`

**Comment by ArieGato** [comment]
I setup an Article from TheBlogTheme as home page content item. How do I set the CustomLayout as layout file. The only thing I can think of is by adding an alternate for the Content-Article with a path match in the placement.json file and add it there. But that can't be the right solution, right?

**Comment by ns8482e** [comment]
There are different ways. It depends on what you are trying to achieve.

e.g If you want all `Article` content type to use `CustomLayout` then in your liquid file  `Content-Article.liquid` add `{% layout "CustomLayout" %}` and create `CustomLayout.liquid` in Views.

Same can be achieved using `Templates` feature instead of file, create templates for `Content__Article` and `CustomLayout`

**Comment by ArieGato** [comment]
I want to setup a layoutHomePage.liquid as layout file for the homepage and layout.liquid for the rest of the content.

**Comment by ns8482e** [comment]
For url based - You can achieve that using  widgets & layers.

1. Create  `Layout.liquid` for rest of all pages.
2. Create  `Layout-HomePage.liquid` for home page.
3. Open Design > Widgets
4. Add `Liquid` widget in HomePage layer with following line 
`{% layout "Layout__HomePage" %}`

**Comment by ArieGato** [comment]
That works nicely. Thnx.

One question though, what happens when multiple templates define an alternate layout? Last one wins?

**Comment by ns8482e** [comment]
> One question though, what happens when multiple templates define an alternate layout? Last one wins?

Yes

**Comment by Piedone** [comment]
Yes, you can actually define alternates from Placement.json too, forgot about that :).

**Comment by ArieGato** [comment]
> Yes, you can actually define alternates from Placement.json too, forgot about that :).

Is there an example how to do that, I tried several things, but couldn't figure it out.

**Comment by Piedone** [comment]
What's documented here should work: https://docs.orchardcore.net/en/dev/docs/reference/core/Placement/#placement-files Be sure to verify that your declaration actually matches (like by first just hiding the shape) before trying to create an alternate.

**Comment by ArieGato** [comment]
Well, I didn't get it to work for Layout files, but the suggested solution of the widget on the homepage layer works fine. Thanks for the help.

**Comment by trentnix** [comment]
Reading the comments, I assume this means that URL Alternates like was done in Orchard 1.x doesn't work in Orchard Core?

**Comment by Piedone** [comment]
There are no built-in URL alternates but if you'd like to contribute it (it should be possible in a couple of lines) you're more than welcome :).
