### ISSUE TITLE
[Question] How to get the HTML contents of Container in the template?

### ISSUE THREAD

**Issue by thinkcodellc** [OrchardCMS/OrchardCore#6448]
Please excuse the n00b question on this subject. I am fresh to Orchard Core CMS. I am using the Agency Theme to customize.

I wanted to add a descriptive 3 part HTML view for the products and structured it so.

![image](https://user-images.githubusercontent.com/14080870/84954948-f2606d00-b0bb-11ea-937e-9a4d9666daf8.png)

In the template, if I am displaying the regular HTML content, it is displayed using the Liquid markup as {{ project.HtmlBodyPart.Html | raw }}. Wondering if I can get some guidance on how to display for the Bag > Container > HTML within its definition. (Left sidebar, Middle Bar & Right Sidebar in the attached image).
          `{%` `for project in Model.ContentItem.Content.Portfolio.ContentItems` `%}`
 
                            <h2 class="text-uppercase">{{ project.DisplayText }}</h2>
                            <p class="item-intro text-muted">{{ project.Project.Category.Text }}</p>
                            <img class="img-fluid d-block mx-auto" src="{{ project.Project.Image.Paths.first | asset_url | resize_url: width:80, height: 80, mode: 'min' }}" alt="{{ project.DisplayText }}">
                            <p>{{ project.Container.Html | raw }}</p>
                          	<p>{{ project.HtmlBodyPart.Html | raw }}</p>
Thanks in advance for the help!

**Comment by ns8482e** [comment]
Hows your content type definition for Product look like? It's difficult to guess based on screenshot

**Comment by thinkcodellc** [comment]
I got a bit confused  - Project is the named part from TheAgency theme that ships out of the box.

![image](https://user-images.githubusercontent.com/14080870/85053813-b16e6400-b160-11ea-9157-0948ad2c4313.png)

I wanted to use a custom HTML layout within the portfolio modal popup. The thought was use a Bag/ Flow (since it allows for multiple items, such as HTML block) and display as 3 sections

Left side bar            |                Middle Bar                     |  Right side bar
                                |                                                      |

The template (also OOTB) is rendering the content of the HTMLBody as 
    `<p>{{project.HtmlBodyPart.Html| raw }}</p>` 
In the same vein, I was hoping using Liquid to display the content for Flow/Bag Part that will contain the HTML.

Any thoughts on how to approach is appreciated. 

Thanks.

**Comment by ns8482e** [comment]
@thinkcodellc if you need only fixed three section for html content then easy option is to just add three `HtmlField` in your content type

**Comment by thinkcodellc** [comment]
@ns8482e  Thanks for the suggestion. I thought having the Flow/ Container with HTML elements would help it render based on its definition . It seems however, a flow/container both merely act as a collection of shapes whose rendering is left to the template.
