### ISSUE TITLE
BaseTheme is not enforced for already current theme

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6449]
I think this worked (or was supposed to work) before, not sure: If you add a BaseTheme to an enabled and current site theme then it won't be picked up, just after you disable and enable it again. I.e. the BaseTheme dependency won't be enforced for already current (or enabled) themes. Steps:

1. Make TheTheme the current site theme with all other themes apart from SafeMode disabled.
2. Remove Layout.cshtml from TheTheme as a test.
3. Run the app. "Shape type 'Layout' not found" as expected.
4. Add `BaseTheme = "TheBlogTheme"` to TheTheme's Manifest and restart the app.
5. Still exception, as TheBlogTheme is disabled. At this point IMO the BaseTheme declaration should be picked up and TheBlogTheme enabled.
6. Make TheAgencyTheme the new current theme, then make TheTheme current again.
7. Now TheBlogTheme is enabled and it works.

**Comment by jtkech** [comment]
@Piedone 

This is funny, i thought it was already fixed by #8968 but was not sure, so just tried it

It now works ;)

**Comment by Piedone** [comment]
Fantastic!
