### ISSUE TITLE
Azure AD Login Redirects back to Login Page

### ISSUE THREAD

**Issue by FelixStumvoll** [OrchardCMS/OrchardCore#6451]
I'm currently trying to set up Login with Azure AD.
After the MS Login Page Im redirected to the Login Page without being logged in.
However in Azure it shows up as a successful login.

The CallbackPath in the Admin Panel is the default one and in Azure i set it to https://localhost:5001/signin-oidc

though im not sure if this is a configuration issue or a bug

**Comment by MichaelPetrinolis** [comment]
do you include the email claim from azure ?

**Comment by FelixStumvoll** [comment]
sadly it doesn't work either

**Comment by FelixStumvoll** [comment]
Okay i fixed the issue, as i thought it was a configuration issue with azure
i also had to enable registration (it said registration is disabled) and configured it to not require username, email or password and enabled username generation by script

This is the Login Script:
```
switch (context.loginProvider) {
    case "AzureAD":
    	context.rolesToAdd.push("Administrator");
    	break;
        });
    default:
        log("Warning", "Provider " + loginProvider + " was not handled");
        break;
}
```

And this the Registration Script:
```
switch (context.loginProvider) {
    case "AzureAD":
        context.userName = "azad" + Date.now().toString();
        break;
    default:
        log("Warning", "Provider " + loginProvider + " was not handled");
        break;
}
```

when i log in with a AD User the username is not set according to the registration script, instead its just u+some numbers
also i get redirected to an error page showing the text: **You do not have access to this resource.**

**Comment by jdnow** [comment]
@FelixStumvoll Having the same problem with Azure authentication. Have you figured anything out?
