### ISSUE TITLE
CodeMirror css

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#6452]
I noticed that the css (scss) of codemirror in TheAdmin theme is outdated.

We should copy the latest codemirror css file into it. Or figure out a way to use the css from the node_modules folder

**Comment by agriffard** [comment]
Watching the history, It seems it has been added by @sebastienros when the Queries have been developed.

We should get rid of it because every module that needs CodeMirror should use the Resource (and I think it is already the case everywhere).

Also, it will decrease the size of the admin css.

**Comment by ns8482e** [comment]
@agriffard I agree, it’s better to have all external css/js used in admin to be included in Resources to better manage external dependencies

**Comment by agriffard** [comment]
The style resource isn't used anywhere for the moment though:
`<style asp-name="codemirror"></style>`

I will try to make the changes and try to use the same options everywhere (line numbers, line wrapping, ...).

**Comment by jptissot** [comment]
Thanks :)
