### ISSUE TITLE
Admin : Form submit pressing enter opens up the markdown help

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#6459]
I set up quickly a testing tenant with the blog recipe. Then I wanted to create quickly a blog post from the admin UI. I typed a title only and pressed the enter key and it opened up the "Markdown help" page in a new tab. When we press enter it should submit the current page form.

![orchard](https://user-images.githubusercontent.com/3228637/85179613-58c9c480-b24f-11ea-9762-a50ffcce8b5a.gif)

**Comment by eddamazioribeiro** [comment]
Hi! Could you please give more details to reproduce this bug?

**Comment by Skrypt** [comment]
Try to create a content item that has a MarkdownBody Part. So basically the Content Type needs to have a MarkdownBody part attached to it.

**Comment by eddamazioribeiro** [comment]
Sorry, I'm new to this project, if you could explain me how to get at this screen where is the problem, please. Just a few steps to help me to get at the point where the problem happens.

**Comment by deanmarcussen** [comment]
If you run the blog recipe to start your site setup, you will see the problem when editing the first blog post.

Note: We need to check the markdown field as well (but later @eddamazioribeiro )

**Comment by Skrypt** [comment]
Can't repro anymore.
