### ISSUE TITLE
Save image to gallery via code

### ISSUE THREAD

**Issue by SherifRefaat** [OrchardCMS/OrchardCore#6461]
Hi,
I am having a custom code that upload an image and save it to disk. I want to add that photo to an existing image gallery but using code.

After thinking I know that the gallery is just another content type so adding another item should be sufficient.

Can you point me to specific location inside the repo or show me a snippet that help me achieve this use case.

Thanks in advance.

**Comment by hishamco** [comment]
I think @dodyg already did that long time back ;)

**Comment by dodyg** [comment]
@SherifRefaat  this code will show you how to upload to the media folder https://gist.github.com/duncanhoggan/173a0aaf1e4c89ba18f84b00db192e75#file-diskwritertask-cs. Just change the "folder" variable content to "media".

**Comment by SherifRefaat** [comment]
Thank you all guys.
