### ISSUE TITLE
Default js & css sections in child/custom MVC or Razor pages

### ISSUE THREAD

**Issue by SherifRefaat** [OrchardCMS/OrchardCore#6462]
Hi,
I writing some controllers and views inside a custom Orchard module inside my CMS. My question is that: how can I add css and js that gets rendered in the base _layout 's head & script section. Normally in pure ASP MVC apps you have two sections called JsInline & CssInline. Is there is an equivalent way in my use case here.

Also, do I have to put the css & js in a wwwroot folder inside my module or put it in my CMS Web project. What is the best practice here?

Thanks.

**Comment by hishamco** [comment]
You can register them in the `ResourcesManager`, please have a look to any of the built-in themes

**Comment by SherifRefaat** [comment]
Thanks you.
