### ISSUE TITLE
Separate Resources per Theme

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6469]
It would be nice to have Resource Manager define logical boundary by theme e.g.

`<style asp-name="bootstrap" at="Foot" asp-theme="TheAgency" />`

So that `name `can not conflict with other themes and other themes resources are not accessible.

**Comment by Piedone** [comment]
Wouldn't names including "namespaces", e.g. `<style asp-name="TheAgency.bootstrap" at="Foot" />` work for your use case? Or if you need a resource just for a single theme, then there's usually no need to create a resource, just include the file.
