### ISSUE TITLE
RC2 navigation items

### ISSUE THREAD

**Issue by RobinC4** [OrchardCMS/OrchardCore#6479]
Hi,

We were using navigation items from the documentation https://docs.orchardcore.net/fr/latest/docs/reference/modules/Navigation/ but when we upgraded our nugets to the new rc2 version, they all got an extra section in the href part like so: "?main=647647999" where the numbers are random each time.
This also happens to the admin navigation "Admin/Contents/ContentItems?admin=-1174682562".

Is this a bug, or has there been a feature enabled that does this? I might be missing something here.
This also happens to the admin menu when I simply run the source code of rc2 and start a blank recipe of agency theme on SQLite.

Thanks.

**Comment by jtkech** [comment]
Yes it is used to track the selected menu item by saving its id to a cookie, so that when we go to a page the related menu item is selected, and then if from this page we go to another page that is not related to a menu item we don't lose the previously selected menu item, e.g. in the admin left bar.

**Comment by RobinC4** [comment]
Thanks for the reply jtkech.
Is this an option we can disable or set on a builder?
I just don' like how the query strings look for users and if they want to share urls.

**Comment by RobinC4** [comment]
Or maybe we should not be using navigation items but instead menu items? But for the menu there is no such builder like to create navigation from a module from code?

**Comment by jtkech** [comment]
@RobinC4

You can create a module that depends on `OC.Navigation` (in your manifest) and then define and register an `IShapeTableProvider` as it is done for `NavigationShapes` but that would run after, and maybe just define something like this

            builder.Describe("NavigationItemLink")
                .OnDisplaying(displaying =>
                {
                    dynamic menuItem = displaying.Shape;
                    string menuName = menuItem.Menu.MenuName;
                    int level = menuItem.Level;

                    string href = menuItem.Href;
                    // Maybe check you are not in the admin and / or the menuName
                    // and then remove the id from the query string of the Href
                });


Yes usually for the front end we use the admin UI to define menus that are rendered through templates that you can override. Here also you an use an `IShapeTableProvider`, see `MenuShapes.cs`

Finally you can define shapes by code by using the `[Shape]` attribute.

**Comment by RobinC4** [comment]
@jtkech 

Thanks again for the reply.
We use Orchard Core for the modular approach and not for creating any content and probably not using orchard to it's full potential.
We create our own ERP modules like HRM, Planning, Invoicing, ... And based on what each client wants to use we can activate that module.
The effect is that by enabling / disabling modules the menu will change which works fine with the NavigationProvider.
Doing it through recipes and recipe migrations will be a little too difficult for us to maintain I fear.

I understand that the href and ID is used to mark the last selected menu item. We will look into your suggestions and see the effect if we remove it.
