### ISSUE TITLE
Media Library Component

### ISSUE THREAD

**Issue by SherifRefaat** [OrchardCMS/OrchardCore#6480]
Hi,

How can I reuse the Media Library dialog to open or select folders in a newly created component.
Is there a razor helper for that?

I tried to copy the code from source and modify it and failed miserably. I can see that the paths api is being called but nothing appears on the modal. I tried several ways to make it work but couldn't.

Thanks,

**Comment by hishamco** [comment]
> How can I reuse the Media Library dialog to open or select folders in a newly created component.
Is there a razor helper for that?

@SherifRefaat could you please elaborate what are trying to do exactly?

**Comment by SherifRefaat** [comment]
In custom page, I want to open the Media Gallery modal to select a photo from it. Then, obtain the path of the photo and do some processing.

**Comment by hishamco** [comment]
The current Media Gallery is used for the admin theme, I'm not sure if we can use this at front-end, I'm not sure if there's an impact to reuse it in the front-end

/cc @deanmarcussen

**Comment by SherifRefaat** [comment]
I want to use it in a custom admin page. Not in the front end.

**Comment by hishamco** [comment]
Seems I miss understand you ;) so what's the problem when you reusing the media app in your custom page

**Comment by SherifRefaat** [comment]
I am asking for way to reuse it in custom admin pages. Like a razor helper or something, because i dont know to do that. I want to be able to trigger it (the modal) and select a photo inside the media directory.

**Comment by PiemP** [comment]
look at the `OrchardCore.ContentFields` module. Here you can find the definition oh the HtmlField view. If you look  `Media-HtmlField.Modal.cshtml` you can see an example to call Media Library in a modal.

**Comment by sebastienros** [comment]
Follow @PiemP 's steps
