### ISSUE TITLE
Accessing logged in user from workflows

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/OrchardCore#6481]
I'm trying to get the name of the logged in user when they submit a form from the frontend into a workflow so i can assign to the output of the workflow. I've tried many different things, including a `{{ User.Identity.Name }}` as detailed in the liquid docs. All i get is `User is not defined`. any help would be appreciated.

Thanks

**Comment by jtkech** [comment]
Just tried the following that works

In the `Set Output Task` Value with JavaScript support

    httpContext().User.Identity.Name

In the `Notify Task` Message with Liquid support

    Test: {{ Workflow.Output["UserName"] }}

**Comment by stevetayloruk** [comment]
Thanks @jtkech. This works a treat.
