### ISSUE TITLE
Admin menu out of order on RC2

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#6484]
Did anything got modified on Admin Menu for RC2? Right now all my Admin Menu items are out of order randomly. 

![out-of-order](https://user-images.githubusercontent.com/1761249/85373226-4099c400-b533-11ea-98a6-6ed07ce99785.png)

**Comment by jtkech** [comment]
Maybe related to #6344 that would be fixed by #6369
