### ISSUE TITLE
Error after clicking Graphql on admin page

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#6487]
![image](https://user-images.githubusercontent.com/297675/85393545-3075ea80-b51b-11ea-8810-6563e5bb6c67.png)
<PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-12186" />

**Comment by infofromca** [comment]
<PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc1-12186" />

**Comment by infofromca** [comment]
just tested it  on  Version="1.0.0-rc2-13450" , the same issue.
only for IE,
it is good on  chrome .

**Comment by jptissot** [comment]
It seems Graphiql no longer supports IE. 
https://github.com/graphql/graphiql/blob/2fcd9e8a81ff6ca973edcb2eb1a41fb9a6c229f4/README.md#browserslistrc

Also see: https://github.com/graphql/graphiql/issues/688#issuecomment-591603907

Tested with Firefox, chrome and latest edge and it works fine.
