### ISSUE TITLE
liquid jsonparse documentation example results in error

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#6497]
OC RC2 13535 (latest dev)

The liquid example from the docs results in the following error, even if I remove the wrong comma:
`JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.`

Update after some research:
@jptissot 
You are using `JObject.Parse` right now, but if you use the example from the docs, it only works with `JArray.Parse`, because `JObject.Parse` is not the a universal parser for json strings.

**Comment by jptissot** [comment]
Maybe JValue.Parse woudl work ?

**Comment by Flarescape** [comment]
Just tried it and it would work for this example, but I read that JToken is the base type so it's recommended to use `JToken.Parse`.
https://www.newtonsoft.com/json/help/html/ParseJsonAny.htm

**Comment by jptissot** [comment]
Ok, I think I never tested with using arrays directly, my original example was using an object ;)

**Comment by Flarescape** [comment]
I just tried this example: https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#jsonparse 😄 

Perfect, thank you. 👍

**Comment by jptissot** [comment]
Thanks for noticing :)
