### ISSUE TITLE
I get MySqlException  using mysql as backend db 

### ISSUE THREAD

**Issue by hamdiRuwiss** [OrchardCMS/OrchardCore#6498]
I created a query using orchard core in one controller  : 

          var query = _session.Query<ContentItem, TextFieldIndex>();
            query = query.With<TextFieldIndex>(x => x.ContentType == contentType);
            query = query.With<TextFieldIndex>(x => x.Published);
            query= query.With<TextFieldIndex>(x=>x.Text=="Sale");
            var maxPagedCount = siteSettings.MaxPagedCount;
            if (maxPagedCount > 0 && pager.PageSize > maxPagedCount)
                pager.PageSize = maxPagedCount;
            var routeData = new RouteData();
            var pagerShape = (await New.Pager(pager)).TotalItemCount(maxPagedCount > 0 ? maxPagedCount : await 
             query.CountAsync()).RouteData(routeData);
            var pageOfContentItems = await query.Skip(pager.GetStartIndex()).Take(pager.PageSize).ListAsync();

I get this exception :
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 10 OFFSET 0' at line 1

I use mysql as backend thank you.

**Comment by hishamco** [comment]
Could you please move this issue into [YesSQL](https://github.com/sebastienros/yessql) repo, while it's related

**Comment by hishamco** [comment]
I reopen this issue, so it can be easily tracked after the origin bug - if there's - fixed

**Comment by hishamco** [comment]
Closing this, after we figure out that there's no bug
