### ISSUE TITLE
Throws 404 when used permlink as /location

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#6500]
Hi @deanmarcussen @sebastienros 

Upgraded the orchard core latest package and created a sample page with Permlink(Autoroutepart) as '/location' and published it. 

Throws 404 page when viewing the page. Only throws 404 when used '/location' . It's weird.

Kindly do the needful.

**Comment by jtkech** [comment]
Just tried it works on my side

Do you have some errors in your log file? Which database / version? Maybe a problem with the autoroute migration when upgrading your app, this migration uses a `DropIndex` that is not supported e.g. by some old sql server version

**Comment by Piedone** [comment]
Closing due to no reply from the author.
