### ISSUE TITLE
Widget items become to small in editor

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6501]
Many fields use column classes to establish a max size.

For example the numeric field uses `col-3-sm` so it is a small display for the number.

This doesn't work when you use the flow editor, and put a widget with a numeric field in a small display (25% for example).

i.e.
![Screenshot 2020-06-24 at 13 26 20](https://user-images.githubusercontent.com/13782679/85556290-9dbe7400-b61e-11ea-9635-640e12ead1c0.png)

I have run into the same problem working on https://github.com/OrchardCMS/OrchardCore/issues/6446 and have a solution, a simple mixin to push any columns contained inside another column to full flex.

something that produces something like
```
.ta-col-grouping {
    &.col-md-3 { 
        // TODO via mixin for cols, and the sizing utils (content picker link field)
        .col-sm-3 {
            flex: 0 0 100%;
            max-width: 100%;       
        }
    }
}
```

So this issue is a note / reminder to apply the same resolution to flows when the other pr is completed and merged.

/cc @ns8482e or @Skrypt

**Comment by ns8482e** [comment]
In css we can differentiate with `widget-editor-body > div > .edit-container`  class.

**Comment by Piedone** [comment]
This isn't the case anymore.
