### ISSUE TITLE
Add strikethrough support for markdownify liquid filter

### ISSUE THREAD

**Issue by neolution-ch** [OrchardCMS/OrchardCore#6502]
The Wysiwyg editor has a button to strike through text. It uses two tildes wrapped around the text:

`~~Hi~~ Hello, world!`

should therefore render to

`<del>Hi</del> Hello, world!` (assuming [GFM spec](https://github.github.com/gfm/#strikethrough-extension-))

It seems that the **markdownify** filter does not do that. 
This happens for both  RC1 and RC2.

**Comment by deanmarcussen** [comment]
Markdig (the Markdown Renderer we use has support for this through extensions.
https://github.com/lunet-io/markdig/blob/master/src/Markdig/Extensions/EmphasisExtras/EmphasisExtraExtension.cs

It should be a simple addition toe the existing markdown pipeline if you want to do a pr @neolution-ch

**Comment by saciervo** [comment]
No PR needed. OC already includes these extensions. You just have to activate them in the Markdown Pipeline: https://docs.orchardcore.net/en/dev/docs/reference/modules/Markdown/#markdown-pipeline

Add this to your `Startup.cs`

    services.AddOrchardCms()
        .ConfigureServices(tenantServices =>
            tenantServices.ConfigureMarkdownPipeline(pipeline =>
            {
                pipeline.UseAdvancedExtensions();
            }));
