### ISSUE TITLE
Serve static content of web application to all tenants

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6505]
When static contents are added to web application `wwwroot ` which are not embedded in assembly - i.e. static content added by Blazor web assembly or  static css, javascript or images etc,  `app.UseStaticFiles()` only serves content for `Default` tenant.

In multi-tenant scenario, If  there is `'wwwroot/appfile1.html'` and have  `Default`, `tenant1`, `tenant2` then it should serve `appfile1.html` to all tenants relative to tenant prefix.

i.e. for default tenant `appfile1.html` should be served with url `/appfile1.html` and for `tenant1`and `tenant2` served with url `/tenant1/appfile1.html` and `/tenant2/appfile1.html`.

Ref issue # https://github.com/OrchardCMS/OrchardCore/issues/6474#issuecomment-649139631

/cc @jtkech

**Comment by remesq** [comment]
Does something like this help? https://medium.com/rtl-tech/building-multi-tenant-asp-net-core-applications-with-orchard-core-dffb404558c3

**Comment by ns8482e** [comment]
@remesq Yes, currently if you have static file `appfile1.html` in `wwwroot` of MVC application and you have multitenancy configured, you can only request that static file from `Default` tenant as `/appfile1.html`. 

For all other tenants  it returns 404 . i.e. `/tenant1/appfile1.html` returns 404.
