### ISSUE TITLE
Authorize Razor Page in Orchard

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6507]
can i authorize Razor Pages to deny not-authorized access to folder of pages?
This not really orking ;-(
  
services.Configure<RazorPagesOptions>(options =>
            {
                options.Conventions.AuthorizeFolder("/Clients");
                options.Conventions.AuthorizePage("/CustomersList");
            });

**Comment by ns8482e** [comment]
@vitalybrandes do you mean to protect your RazorPages for admin area?

You can place all your admin razor pages either inside `Admin` folder or define `[Admin]` on `PageModel`

https://github.com/OrchardCMS/OrchardCore/blob/ee33edb7fe538d000aacb3134b79779b9a250bee/src/OrchardCore.Modules/OrchardCore.Demo/Pages/OutsideAdmin.cshtml#L8-L9

**Comment by vitalybrandes** [comment]
> 
> 
> @vitalybrandes do you mean to protect your RazorPages for admin area?
> 
> You can place all your admin razor pages either inside `Admin` folder or define `[Admin]` on `PageModel`
> 
> https://github.com/OrchardCMS/OrchardCore/blob/ee33edb7fe538d000aacb3134b79779b9a250bee/src/OrchardCore.Modules/OrchardCore.Demo/Pages/OutsideAdmin.cshtml#L8-L9

No, To protect from Non authorized access to Pages.

**Comment by ns8482e** [comment]
Then try `[Authorize]` on PageModel

**Comment by vitalybrandes** [comment]
> 
> 
> Then try `[Authorize]` on PageModel

Yeap, this one works,
i am wondering how to do that for all Folder.

**Comment by hishamco** [comment]
You can create a base `PageModel` that applying the `Authorized` attribute, or we can injected it as an attribute filter in Startup

/cc @jtkech

**Comment by vitalybrandes** [comment]
> 
> 
> You can create a base `PageModel` that applying the `Authorized` attribute, or we can injected it as an attribute filter in Startup
> 
> /cc @jtkech

@hishamco  The Injected sound good!

**Comment by ns8482e** [comment]
@vitalybrandes  @hishamco It's already supported  But in OrchardCore - Application being a virtual area - AuthorizeFolder won't work instead use AuthorizeAreaFolder - where [area] = web app name.

 ```
services.AddOrchardCms()
                .ConfigureServices((services =>
               {
                   services.Configure<RazorPagesOptions>(options =>
                   {
                       options.Conventions.AuthorizeAreaFolder("OrchardCore.Cms.Web","/Clients");
                       options.Conventions.AuthorizeAreaPage("OrchardCore.Cms.Web","/CustomersList");

                   });
               }));
```

**Comment by vitalybrandes** [comment]
> @vitalybrandes @hishamco It's already supported But in OrchardCore - Application being a virtual area - `AuthorizeFolder` won't work instead use `AuthorizeAreaFolder`- where [area] = web app name.
> 
> ```
> services.AddOrchardCms()
>                .ConfigureServices((services =>
>               {
>                   services.Configure<RazorPagesOptions>(options =>
>                   {
>                       options.Conventions.AuthorizeAreaFolder("OrchardCore.Cms.Web","/Clients");
>                       options.Conventions.AuthorizeAreaPage("OrchardCore.Cms.Web","/CustomersList");
> 
>                   });
>               }));
> ```

The Area is web app or module name? My pages are in separate module....

**Comment by hishamco** [comment]
Even though, you can still configure the services in a `Startup` class in your newly added module

**Comment by ns8482e** [comment]
> > @vitalybrandes @hishamco It's already supported But in OrchardCore - Application being a virtual area - `AuthorizeFolder` won't work instead use `AuthorizeAreaFolder`- where [area] = web app name.
> > ```
> > services.AddOrchardCms()
> >                .ConfigureServices((services =>
> >               {
> >                   services.Configure<RazorPagesOptions>(options =>
> >                   {
> >                       options.Conventions.AuthorizeAreaFolder("OrchardCore.Cms.Web","/Clients");
> >                       options.Conventions.AuthorizeAreaPage("OrchardCore.Cms.Web","/CustomersList");
> > 
> >                   });
> >               }));
> > ```
> 
> The Area is web app or module name? My pages are in separate module....

If it’s a module then define `ConfigureServices` In Startup of module. Your module project name is `area`

**Comment by vitalybrandes** [comment]
> 
> 
> > > @vitalybrandes @hishamco It's already supported But in OrchardCore - Application being a virtual area - `AuthorizeFolder` won't work instead use `AuthorizeAreaFolder`- where [area] = web app name.
> > > ```
> > > services.AddOrchardCms()
> > >                .ConfigureServices((services =>
> > >               {
> > >                   services.Configure<RazorPagesOptions>(options =>
> > >                   {
> > >                       options.Conventions.AuthorizeAreaFolder("OrchardCore.Cms.Web","/Clients");
> > >                       options.Conventions.AuthorizeAreaPage("OrchardCore.Cms.Web","/CustomersList");
> > > 
> > >                   });
> > >               }));
> > > ```
> > 
> > 
> > The Area is web app or module name? My pages are in separate module....
> 
> If it’s a module then define `ConfigureServices` In Startup of module. Your module project name is `area`

If i am running that in the module startup, what do i setup
services.AddOrchardCms() instead? as this is not cms, this is module.

**Comment by ns8482e** [comment]
See demo module for how to configure services https://github.com/OrchardCMS/OrchardCore/blob/03891a7e94bb41b9df8de6eb96564abdb2f6e136/src/OrchardCore.Modules/OrchardCore.Demo/Startup.cs#L104

**Comment by vitalybrandes** [comment]
> 
> 
> See demo module for how to configure services
> 
> https://github.com/OrchardCMS/OrchardCore/blob/03891a7e94bb41b9df8de6eb96564abdb2f6e136/src/OrchardCore.Modules/OrchardCore.Demo/Startup.cs#L104

Magic!
Thanks
