### ISSUE TITLE
Implementation Notes for Rendering Bag Items and Rendering Bag Items within a Parent Bag

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/OrchardCore#6510]
In the vein of past posts here working through solutions, I want to share my experiences with implementing content types containing a bag (parent) which itself contains a bag/bags (child/children). This was useful to me as I could take common elements like unordered lists, paragraphs and images, and insert them wherever I needed. The benefit was in having something that was reusable and un-styled, so that I can insert it anywhere and style to each circumstance.

I'm going to use an unordered list `<ul><li>. . .</li></ul>` as my example. First, I'll show what I was doing previously (just a bag of items). Then I'll show what I came up with as my goals changed (a bag containing a bag of items and using fields within that child bag). Also, everything is stereotyped as a `widget`, even if it doesn't have a template.

### **1. Rendering a Bag of Items - Two Methods.**

Assume a content type named `BlockItem` with an associated template of `Widget__BlockItem` (or `Widget-BlockItem.liquid`). `BlockItem` has a named part `ItemDetailListElementBag` with a contained content type called `BlockListElement` selected.

`BlockListElement` has one text field named `ListElementItem` which holds the text for the `<li></li>`.

**A. Method One of Displaying a Bag of Items.**
```
<ul class="ul-square">
    {% for listItem in Model.ContentItem.Content.ItemDetailListElementBag.ContentItems %}
        <li>{{ listItem.BlockListElement.ListElementItem.Text }}</li>
    {% endfor %}
</ul>
```
Fairly simple, but with little control over the styling or using fields - I originally used fields in `BlockItem` but the way they displayed in the Admin UI was not intuitive (e.g., can't place one or more fields around or below it as the content types fields all display together). To get a visual of what I mean, look at this image from another content type I have that also uses bags to contain list elements:

![image](https://user-images.githubusercontent.com/727061/85902451-10bc1c00-b7d2-11ea-8e62-b266b5c90126.png)

You can see that I added fields to the main content type, but they appear above the bags. This would be more cumbersome and difficult to work with if I wanted more bags and/or fields.

Also, there is no need to use a template here such as `Widget__BlockListElement` since the unordered list is rendered in `Widget__BlockItem`. This works fine if your requirements are basic and you want something quick.

**B. Method Two of Displaying a Bag of Items.**
```
. . .
{{ "Widget__BlockListElement" | shape_new: content: 
Model.ContentItem.Content.ItemDetailListElementBag.ContentItems | shape_render }}
. . .
```
The above replaces the `<ul>. . .</ul>` code above. Instead, I am using `Widget_BlockItem` to call the "sub"-template `Widget__BlockListElement` to render the unordered list. This gives me a bit more control of how things flow and means I don't have to repeat the Method One code all over the place (which is the point - reusability). To give you an idea, this example is basic (five lines vs. one), but potentially saves me on inserting this 20 times each with 10+ lines of code.

`Widget__BlockListElement` contains the following:
```
<ul class="ul-check">
    {% for listItem in Model.Content %}
    <li>{{ listItem.BlockListElement.ListElementItem.Text }}</li>
    {% endfor %}
</ul>
```
This allows me to create any number of `<li>` elements for an unordered list (in this case). And using this method in separate bags for paragraphs and images just helps me further.

However, because I wanted to expand on the above and have the unordered list within it's own bag (so I can add separate fields to it specific to the bag, and which would display nicer in the Admin UI), I had to figure out how to render a bag which itself contains another bag. Bear in mind I'm not a developer, so all of this is probably pretty easy for most.

Read the next comment for how I worked that out for myself.

**Comment by remesq** [comment]
I've discovered that I can do this to get at the items inside the second bag:

```
<ul class="ul-check">   
    {% for listItem in Model.Content %}
    <li>{{ listItem | shape_build_display: "Detail" | shape_render }}</li>
    {% endfor %}
</ul>
```
However, all the list elements are rendered within the one `<li>` tag. Continuing to investigate.

**Comment by remesq** [comment]
I've **somewhat** solved my problem (see below), but am going to leave this open and edit everything to make it more instructional, if that's okay. I'll close it out after the edits.

I changed the code in `Widget__BlockItem` to the following:
```
{% comment %}{
    { "Widget__BlockListElement" | shape_new: content:
Model.ContentItem.Content.ItemDetailListElementBag.ContentItems | shape_render }}
{% endcomment %}

{% for listItem in Model.ContentItem.Content.ItemDetailListElementBag.ContentItems %}
    {{ listItem | shape_build_display: "Detail" | shape_render }}
{% endfor %}
```
Instead of using `Widget__BlockListElement` I just created new content type called "Block New". This contains the second bag, called `NewBag`. I created the associated template `BlockNew__NewBag` (`BlockNew-NewBag.liquid) with the contents:
```
<ul class="ul-check">
    {% for listElement in Model.ContentItems %}
        <li>{{ listElement.Content.BlockListElement.ListElementItem.Text }}</li>
    {% endfor %}
</ul>
```
This now properly renders the unordered list items how I wanted, I'm sure there is another way to do this, but I'll leave it at that.

The **only** problem I now have is that in the second bag I added a Title Part. I cannot get it to display unless I use `shape_build_display: "Summary"` instead, but then I can't get it to display where I want plus it displays the Title as a link (which goes to a 404 error page, and which I have seen before here as an issue). Please help :).

**Comment by ns8482e** [comment]
Use `DisplayText` Property of content item

**Comment by remesq** [comment]
> Use `DisplayText` Property of content item

I've tried many combinations to get this to work and can't figure out which property to access:

![image](https://user-images.githubusercontent.com/727061/85864886-18100500-b793-11ea-9518-062102c7768a.png)

Assume "Block New" is the content type (widget) and assume `NewBag` is the name of the second (child) bag. How would I access it? Thanks.

**Comment by remesq** [comment]
Now I am stuck at another problem, the whole of which was the point of doing a bag (child) within a bag (parent), adding fields.

I started with a simple text field for `ListStyle` (pre-defined list with class names) in order to render `<ul class="ul-check">` with this bit of code (using the same naming as above for content type and named part within):
```
<ul class="{{ listItem.BlockNew.ListStyle.Text }}">
```
This works. **However** because I am doing `shape_build_display` in the parent content type, it is outputting `ul-check` at the top of the rendered content from the child bag.

I have tried to do `{% shape_remove_item listItem "BlockNew-ListStyle" %}` in both the parent bag and the child bag, but that won't work.

Is there a way to remove the item that way, or is Placement the only option (assuming that would even work)?

**Comment by remesq** [comment]
Well, finally, Placement did the trick but I wish I could have used `shape_remove_item` to keep things a bit cleaner without needing the `placement.json` file. If it's possible to use `shape_remove_item` instead I'd still love to hear some feeback.
