### ISSUE TITLE
Cannot render image on Razor page using @Html.Raw(). 

### ISSUE THREAD

**Issue by kandari7** [OrchardCMS/OrchardCore#6511]
Is there any way I can render Image on my Razor page, as when I display the data on my page using   @Html.Raw(JobDetails.Content.HtmlBodyPart.Html) code, the Image tag is coming as [image]New and Article/T2-M-235-Sunflower-Line-Graph-Differentiated-Activity-Sheets-_ver_9.jpg[/image]

**Comment by hishamco** [comment]
> [image]New and Article/T2-M-235-Sunflower-Line-Graph-Differentiated-Activity-Sheets-_ver_9.jpg[/image]

This is the shortcode for the image, @deanmarcussen of course knows this stuff much better

**Comment by hishamco** [comment]
After a quick look to the code, seems you need to use `HtmlToShortCodesAsync()` extension method

**Comment by kandari7** [comment]
Hi @hishamco Thank you for your response, I am totally new into Orchard CMS, can you tell me where to use HtmlToShortCodesAsync() function as I am using Razor Page

**Comment by hishamco** [comment]
There's a service `IOrchardHelper` injected automatically to the OC views, then you can call the above method

**Comment by ns8482e** [comment]
@hishamco @deanmarcussen any reason why it's `[image]` and not `<img>` is there any setting that can be turned on/off?

**Comment by kandari7** [comment]
@hishamco Thank you it worked, also it would be great if [image] tag is converted into <img> tag

**Comment by hishamco** [comment]
@ns8482e AFAIK, most of the editor are using the shortcodes for now, and the above extension is did what is supposed to be done

@kandari7 happy to hear it works

**Comment by agriffard** [comment]
@ns8482e with Trumbowyg editor, you can specify in the settings that you want to insert a media with <img> but by default, the Short Code is used.

**Comment by ns8482e** [comment]
@hishamco @agriffard I understand. However can it be changed to generate `<img>` tag if needed? , coz in some scenario only `html` is expected in data.

**Comment by agriffard** [comment]
> you can specify in the settings that you want to insert a media with `<img>` 

Yes it can (I forgot the quotes so the `<img>` was not displayed.)
