### ISSUE TITLE
CodeMirror non active line select on Html fields

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6512]
New Code Mirror improvements are great.

But I'm not liking this one so much, where the current line of an Html Field is displayed, even when it is not selected.

Be great if it only show the current line when it is actually selected.

Here the title is currently selected

![Screenshot 2020-06-26 at 08 27 01](https://user-images.githubusercontent.com/13782679/85831956-13ddea80-b787-11ea-9383-e5b0fd007c2d.png)

/cc @agriffard

**Comment by agriffard** [comment]
There is no option to show the current line only when it is selected.
I agree this is weird for a new empty content.
I guess we can simply remove the use of this addon.

**Comment by agriffard** [comment]
Will try this: https://stackoverflow.com/questions/57494690/how-to-disable-highlight-active-line-in-codemirror-when-editor-is-not-selected
