### ISSUE TITLE
Dynamic cache dependency tag helper

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6517]
There is a liquid tag to add dependencies to a cache block, but no corresponding Razor one.

I needed one today, so have implemented it

**Comment by hishamco** [comment]
I think there's a built-in one in ASP.NET or you need to add something special?

**Comment by jtkech** [comment]
@hishamco

We have a custom `DynamicCacheTagHelper` using cache contexts taylored for OrchadCore, look at the code it uses an `IDynamicCacheService` using an `ICacheContextManager` and an `IDynamicCache` using an `IDistributedCache` and so on.

@deanmarcussen

Just remembered that `DynamicCacheTagHelper` has a `dependencies` attribute and can be nested, isn't it sufficient?

**Comment by deanmarcussen** [comment]
@hishamco ours is better ;)

@jtkech yes, I tried to see if nesting was relevant here, but it creates different cache blocks (cache-ids), so the inner nested cache block gets cached by the parent cache-id, and I need to be able to set the cache dependencies, after the cache block has started, rather than nesting another block.

So it needed something that could access the `ICacheScopeManager` and add dependencies to the current cache context. 

I maybe missing something, but I just implemented what we have for Liquid, and seemed to be missing for Razor

**Comment by hishamco** [comment]
Thanks for clarification Jean & Dean .. go for it

**Comment by jtkech** [comment]
@deanmarcussen okay
