### ISSUE TITLE
Do I need to upgrade Orchard Core when using Orchard CMS 1.10.2 for my website?

### ISSUE THREAD

**Issue by kcastro18** [OrchardCMS/OrchardCore#6519]
Hello,

Me and my team are a little confused about Orchard CMS, Orchard Core, and Orchard. We have a website running on Orchard 1.10.2 which we might want to upgrade to the newer version. We also notice a lot of activities happening with Orchard Core and we are wondering if we will have to update our website with newer version of Orchard Core as well?

To add into my confusion, in the Orchard Core page I read that it consists of two projects Orchard Core Framework and Orchard Core CMS. Is the Orchard Core CMS different from Orchard CMS? 

I'm basically trying to get more information/clarification with different Orchard projects so we can develop a process to keep our website up to date with new releases/patches and making sure that we are following the correct releases we need for our website.

Any information is greatly appreciated.

Thank you,

Karen

**Comment by ns8482e** [comment]
@kcastro18 Orchard CMS 1.x is using .NET Framework where as OrchardCore is completely re-written in .net core currently supporting .net core 3.

Orchard Core Framework provides some framework features like mutli-tenancy, modularity, resource management, display management etc. that you can use in your .net core mvc project by referencing nuget pacakges.

Orchard Core CMS is - content management system that built on Orchard Core Framework. currently in RC2.

**Comment by kcastro18** [comment]
@ns8482e So in my understanding from your response OrchardCore is separate/different from OrchardCMS 1.x. If that so, what is the use of Orchard.Core project in OrchardCMS solution? Would I need to install or upgrade to OrchardCore RC2? Or should I just be focusing on upgrading Orchard 1.x?

**Comment by ns8482e** [comment]
Orchard Core CMS is content management solution written for .net core by same group of people who developed Orchard CMS for .net framework.

Content management and Display management Concepts are same for both. So If you know Orchard CMS 1.x then you will understand Orchard Core CMS. 

I would say, Orchard Core CMS is next version of Orchard CMS 1.x - but there is not automatic in-place upgrade.

**Comment by ns8482e** [comment]
> Would I need to install or upgrade to OrchardCore RC2? Or should I just be focusing on upgrading Orchard 1.x?

You can continue to Orchard 1.x if you wish - Orchard Core CMS doesn't replace Orchard 1.x - both are active community projects. Orchard 1.x is using .net framework and works only on windows servers

If you want to take advantage of .net core features like running on cross platform then you can switch to Orchard Core CMS.

**Comment by hishamco** [comment]
I will close this, while the question has been answered, please feel free to open an issue if you have and question

Thanks

**Comment by kcastro18** [comment]
I get the difference between Orchard **Core** CMS and Orchard CMS but I still have not gotten a direct answer about Orchard.Core project in the Orchard solution. Is that related to OrchardCore project that got some activities going on recently? 
![2020-06-29 10_14_16-Orchard - Microsoft Visual Studio](https://user-images.githubusercontent.com/15161975/86023537-6b7f8e80-b9f1-11ea-9503-80202de6c435.png)

**Comment by deanmarcussen** [comment]
Orchard Core CMS is not unrelated to the `Orchard.Core` project in the Orchard CMS project

**Comment by ns8482e** [comment]
Orchard CMS 1.x codebase is here https://github.com/OrchardCMS/Orchard

Where as Orchard Core CMS codebase is here https://github.com/OrchardCMS/OrchardCore

Don’t get confused with naming on projects or files within these repository, they may share similar file names but are not referencing each other

**Comment by kcastro18** [comment]
That clarifies it! Thank you so much!
