### ISSUE TITLE
Lucene Query Api the the endpoints work with get only i can't get to work with post requests

### ISSUE THREAD

**Issue by hamdiRuwiss** [OrchardCMS/OrchardCore#6520]
what type of body do we use when querying the endpoint because i tried most and nothing work with post
here is the get request :
```
https://localhost:5001/api/lucene/content?query={
  "query": {
    "bool":
    {
      "must" :[
        {"term": { "Content.ContentItem.ContentType": "Meal" }},
        { "term": { "Meal.AdType": "{{type}}" }},
           ]
    }
  },
  "sort": {
    "Content.ContentItem.CreatedUtc": {
      "order": "desc",
      "type": "double"
    }
  },
  "size": 3
}&indexName=Meal&parameters={"type": "Rent" }
```
This works fine in postman but when i try it using post items null

I also noticed the endpoints result is not consistent the content return the items with count and the document doesn't

**Comment by deanmarcussen** [comment]
The post request and the get request should be the same

(i.e. don't put anything in the post body, put it all in the query string)

**Comment by hamdiRuwiss** [comment]
ok that was intentional  , it woks if i try post with querystring , becuase i am building a search form with multiple options i thaught i could send the query in the post .

**Comment by sebastienros** [comment]
We might want to accept the query in the body if it's a POST. @hamdiRuwiss Do you want to provide a PR for that?
That would probably mean split the current method in two.

**Comment by hamdiRuwiss** [comment]
Yes i would like to do it
