### ISSUE TITLE
ShapesViewModel proposal

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6524]
With more and more dynamic shapes coming into Orchard Core (all the tab/card grouping shapes, and also shapes like the `ContentCard` it would be potentially useful to have a `ShapesViewModel` that could be used as a hard type abstract class to create specific targetted view models, i.e. a `TabViewModel`.

The problem with the `ShapeViewModel` is it doesn't support a list of positioned `Items`, so right now we are using `Shape` because many of these tab/card/content card shapes require a list of positioned items as well.

So I was not intending that a `ShapesViewModel` was actually an `IShape`, just an abstract that could be used to build shapes with, and the mixin would still turn it into an `IShape`, by mixing in the `ShapeViewModel` which has all the required `IShape` properties.

The idea being you could then use the `IShapeFactory` to create a shape, then add items to it.
```
var shape = ShapeFactory.CreateAsync<TabViewModel>("Tab", m =>
{
    m.TabId = tabId
});

foreach(var item in thetabs)
{
    shape.Add(item);
}
```

for example

**Comment by sebastienros** [comment]
Create a new ShapeViewModel that implements IShapeContainer and has Items. You can inherit from it.
Or just inherit from Shape
