### ISSUE TITLE
Admin Culture switch

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6525]
Allow to switch among the enabled cultures in Admin.

Separated from Front-end culture.

**Comment by hishamco** [comment]
@agriffard can we do this for 1.0.0?

**Comment by agriffard** [comment]
May be @jptissot would be interested in doing it?

**Comment by hishamco** [comment]
I can participate on this, but I don't know if we can add new features in RC, I expect more validation will be more useful

**Comment by agriffard** [comment]
Related to #3665

**Comment by sebastienros** [comment]
Duplicate
