### ISSUE TITLE
Editing Widget throws an error.

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#6526]
I added a "container" widget using the admin panel. when I click "Edit" I get the following error

```
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
/Areas/OrchardCore.Contents/Views/Content.Edit.cshtml

    'ZoneShapes' does not contain a definition for 'HarvestAndSortTabs'

        var tabs = (IEnumerable<string>)ZoneShapes.HarvestAndSortTabs(Model.Parts);
```

![image](https://user-images.githubusercontent.com/24724371/85925912-6afbc200-b850-11ea-934e-54d3da28f102.png)

**Comment by deanmarcussen** [comment]
Can you run a dotnet clean and dotnet restore?

It gets stuck sometimes, and I think it hasn't recompiled the template from your nuget upgrade

**Comment by deanmarcussen** [comment]
Also reported on gitter and a dotnet clean and dotnet restore resolved the issue, so closing this.

If you have any further issues please reopen
