### ISSUE TITLE
Multiple markdown editors in a content type stop working

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#6529]
I have several markdown fields with wyswyg editors. They used to work and now each of these fields stop working. They become unresponsive. Also an "x" appears if you try multiple clicks on the non responsive editor.

![standard-editor](https://user-images.githubusercontent.com/1761249/85960635-4e24d300-b9a5-11ea-9f00-61c1ae6f7be4.png)

**Comment by dodyg** [comment]
Some toolbar options on the markdown editor generate gibberish but some would just create weird display.

![toolbar](https://user-images.githubusercontent.com/1761249/85960684-b83d7800-b9a5-11ea-91a6-dd73860a0ef6.png)

**Comment by dodyg** [comment]
![random-shit](https://user-images.githubusercontent.com/1761249/85960712-02bef480-b9a6-11ea-862e-ee36f593f6dc.png)

**Comment by jptissot** [comment]
Hmm maybe due to my recommendation to modify the css? @agriffard

**Comment by dodyg** [comment]
I am running on `1.0.0-rc2-13610`.

**Comment by agriffard** [comment]
Please refresh your browser cache and retry.

**Comment by dodyg** [comment]
The same problem. Ctrl + F5 does nothing.

**Comment by agriffard** [comment]
I can't repro.

**Comment by jptissot** [comment]
@dodyg do you have a custom admin theme?

**Comment by dodyg** [comment]
No. I do use Admin Menu.

**Comment by jtkech** [comment]
For infos i can repro, same symptoms as @dodyg described

**Comment by dodyg** [comment]
I upgraded to `1.0.0-rc2-13635` and it still have the same problem. I clear my browser cache as well. The problem is console returns no error.

![clear](https://user-images.githubusercontent.com/1761249/86125200-8a0e8400-badc-11ea-947e-a247cd2ea85d.png)

**Comment by dodyg** [comment]
It doesn't even require multiple markdown fields. This is broken with just one field.

![editorial](https://user-images.githubusercontent.com/1761249/86125434-f1c4cf00-badc-11ea-8d7e-8bcdc72b18a1.png)

**Comment by jptissot** [comment]
Found the issue. Sending a PR

**Comment by agriffard** [comment]
Thank you. 
I also managed to repro it. 
I was testing with other fields that are loading code mirror.

I guess that the fix will be to require the codemirror css/script in MarkdownField-Wysiwyg.Edit.cshtml and MarkdownPart-Wysiwyg.Edit..cshtml

**Comment by agriffard** [comment]
We should also replace this code:
```
<script name="simplemde" depends-on="admin" asp-src="~/OrchardCore.Markdown/Scripts/simplemde.min.js" at="Foot"></script>
<style name="simplemdecss" asp-src="~/OrchardCore.Markdown/Styles/simplemde.min.css" debug-src="~/OrchardCore.Markdown/Styles/simplemde.css"></style>
```
and use the resources from a ResourceManifest.

Unless, it loads all the foot scripts with `name="simplemde"`.

**Comment by jptissot** [comment]
Yes, we need to load code mirror css (not script) in MarkdownField-Wysiwyg.Edit.cshtml (and body too)

Our simpleeditor.min.css file does not include codemirror css
https://github.com/sparksuite/simplemde-markdown-editor/blob/master/gulpfile.js#L78
