### ISSUE TITLE
Implement Module for Orchard Core CMS

### ISSUE THREAD

**Issue by minhdn2** [OrchardCMS/OrchardCore#6533]
Hi,

I've been following [this tutorial](https://www.youtube.com/watch?v=yrQaKv2mxFU&list=PLReL099Y5nRd04p81Q7p5TtyjCrj9tz1t.) and successfully implemented module for an Orchard Core project.
However, this approach is not working for an Orchard Core CMS project.

Is there any way to implement an API module for Orchard Core CMS?
I've been trying this and it's not working:
![image](https://user-images.githubusercontent.com/35803003/85990424-35a3cf80-ba1c-11ea-9f17-0c9f9b5c6a1f.png)

I need to create a public API in Orchard Core CMS, so that another web application can make calls to this API to create content items. Is this possible with Orchard Core CMS?

Please help to check and advise,
Many thanks in advance.

**Comment by deanmarcussen** [comment]
Yes, this is possible.

It looks like you are calling both `services.AddOrchardCms();` and `services.AddOrchardCore();`

You need to call just one, if you want the cms, call `services.AddOrchardCore();`

In terms of an api controller, yes, we do already have one, but you can also add your own that does what you need.

Have a look at the `Contents/ApiController.cs` to see if it does what you need / how it works.

Note you will want to use `OpenId` to get an API token auth to use it.

**Comment by ns8482e** [comment]
@minhdn2 if you are building multi tenant modular  application for your asp.net project and you don’t need CMS functionality  then call `services.AddOrchardCore();` if you need CMS functionality then call `services.AddOrchardCms()` 

If you are calling  `AddOrchardCms` then to use your module, you have to enable your module from Admin UI.

**Comment by minhdn2** [comment]
Hi @ns8482e ,

Can you please be more specific?
Is there any guiding article or video that you can share?

Many thanks in advance.

**Comment by minhdn2** [comment]
Hi @ns8482e ,

Thank you very much.
