### ISSUE TITLE
Getting error when click on Content Item on admin section

### ISSUE THREAD

**Issue by kandari7** [OrchardCMS/OrchardCore#6537]
Hi Team,

i am getting the below error when I click on Content Items from Admin section:

**An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
OrchardCore.ContentManagement.Display.ContentItemDisplayManager.BuildDisplayAsync(ContentItem contentItem, IUpdateModel updater, string displayType, string groupId) in ContentDisplayManager.cs, line 68**

**Comment by sebastienros** [comment]
Please provide detailed repro step, including which version of OC you are using (hopefully RC2)
