### ISSUE TITLE
Consider Moving Flow/Bag "Add Item" Dropdown to the Right

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/OrchardCore#6538]
I don't know if it's feasible this late in the game, and I know this might sound trivial, but it might be an improvement to quality of life if the "Add Item" button were moved (floated?) to the right.

Here is what I mean:

![image](https://user-images.githubusercontent.com/727061/86078406-1331a680-ba5c-11ea-9312-8b54b30eeda1.png)
The issue is that the UI can get cluttered, particularly if you are using flow/bags.

I am not referring to the similar dropdown that has a "+" and is centered in the content creation view, that's perfect where it is.

**Comment by ns8482e** [comment]
It’s BagPart.Edit.cshtml You can override ootb shapes if you wish

**Comment by remesq** [comment]
Thanks.
