### ISSUE TITLE
Docker Container Codemirror not working

### ISSUE THREAD

**Issue by FelixStumvoll** [OrchardCMS/OrchardCore#6539]
in the containerized version of orchard core the code mirror in Security>Settings>Login/Registration is not working
Login: `LoginSettings?admin=-98086791:557 Uncaught ReferenceError: $ is not defined at LoginSettings?admin=-98086791:557`
Registration Error: `Uncaught ReferenceError: CodeMirror is not defined at window.onload`

**Comment by agriffard** [comment]
Does it work with the latest version of the docker container?

The error suggests that a jQuery selector is called before that jQuery is loaded.
Can you please tell us what is the code on this line `557` where the error occurs?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
