### ISSUE TITLE
Unable to access import content

### ISSUE THREAD

**Issue by leone-91** [OrchardCMS/OrchardCore#6541]
Hi everyone,
I used the import fuctionnality to bring content items and definitions to my published website from my local project. However I cannot access the content or create content (for the types I have imported only) anymore . This error appears in the console: 
"Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.54.0/mode/css/css.min.js' with computed SHA-256 integrity 'AmHwHDNYa4UtdlIzirPIDXHNwkEfr0NI6AeBnXs6L2c='. The resource has been blocked."

Thanks in advance for your help

**Comment by deanmarcussen** [comment]
Could you provide some more detail / repro steps?

I would need to understand what you mean by cannot access content, do you mean you get errors / they don't show up etc?

The console error was fixed already before rc2 (and is not what is the problem here)

Could you make sure your deployment plan has the content type definitions step first, and the content step after that.

Also what version are you actually running?

**Comment by leone-91** [comment]
This is what I get on my screen when I click on create a new "CabanePage" which is a type I have created, similar to the landing page:
![orchard](https://user-images.githubusercontent.com/61582230/86107419-16f81400-bac2-11ea-8914-a85700d5c5a7.PNG)

I cloned the git repo about two weeks ago so I am working with the rc2 version.

The content type definitions were not first in my deployment plan, however the error still here. (You can also see a bug with the admin menu on the picture and it might be linked...) 
Thanks for your quick answer.

**Comment by deanmarcussen** [comment]
The integrity issue is not related. if you update to the latest dev you will find it gone (but again 100% not related)

You will need to look in your `App_Data/Logs` folder to see the actual error.

I suspect you have a content type definition missing, or incorrect

**Comment by leone-91** [comment]
Okay thank you for that point! I think that I found something, when I delete all the named parts of my page and then recreate them, it works again... The problem might come from BagPart I will look into that, thank you once again!
