### ISSUE TITLE
Script name

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6545]
If you use a script taghelper with a name, all the depending scripts in footer have that attribute.

Ex in TextField-IconPicker.Edit.cshtml:
`<script name="fontpickerScript"...>`
=>
```
<script crossorigin="anonymous" integrity="sha384-/LjQZzcpTzaYn7qWqRIWYC5l8FWEZ2bIHIz0D73Uzba4pShEcdLdZyZkI4Kv676E" name="fontpickerScript" src="https://code.jquery.com/jquery-3.5.1.js" type="text/javascript"></script>
<script name="fontpickerScript" src="/OrchardCore.ContentFields/Scripts/fontawesome-iconpicker.js" type="text/javascript"></script>
```

Is is the expected beahaviour?

**Comment by jtkech** [comment]
@agriffard 

You need to use `asp-name`, idem for the style tag helper

Need to lookup in razor files all script / style razor tag helpers that only use `name` and update them to `asp-name`
