### ISSUE TITLE
Build error on Mac Book

### ISSUE THREAD

**Issue by lbcsy** [OrchardCMS/OrchardCore#6547]
Cloned latest master (46b33c79f), built on Mac Book (Catalina Version 10.15.5) with VS 2019 installed:

MacBook-Pro:OrchardCore xxxxxx$ botnet build

Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/Users/xxxxxx/dev/Orchard/OrchardCore/src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj : error NU1201: Project OrchardCore.Application.Cms.Targets is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Project OrchardCore.Application.Cms.Targets supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) [/Users/xxxxxx/dev/Orchard/OrchardCore/OrchardCore.sln]
/Users/xxxxxx/dev/Orchard/OrchardCore/src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj : error NU1201: Project OrchardCore.Logging.NLog is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Project OrchardCore.Logging.NLog supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) [/Users/xxxxxx/dev/Orchard/OrchardCore/OrchardCore.sln]
  Failed to restore /Users/xxxxxx/dev/Orchard/OrchardCore/src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj (in 1.12 sec).
  156 of 157 projects are up-to-date for restore.

Build FAILED.

/Users/xxxxxx/dev/Orchard/OrchardCore/src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj : error NU1201: Project OrchardCore.Application.Cms.Targets is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Project OrchardCore.Application.Cms.Targets supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) [/Users/xxxxxx/dev/Orchard/OrchardCore/OrchardCore.sln]
/Users/xxxxxx/dev/Orchard/OrchardCore/src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj : error NU1201: Project OrchardCore.Logging.NLog is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Project OrchardCore.Logging.NLog supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) [/Users/xxxxxx/dev/Orchard/OrchardCore/OrchardCore.sln]
    0 Warning(s)
    2 Error(s)

**Comment by deanmarcussen** [comment]
You need to upgrade to the dotnet core 3.1 sdk

**Comment by lbcsy** [comment]
MacBook-Pro:OrchardCore xxxxxx$ dotnet --list-sdks
2.1.302 [/usr/local/share/dotnet/sdk]
2.1.505 [/usr/local/share/dotnet/sdk]
2.2.101 [/usr/local/share/dotnet/sdk]
2.2.301 [/usr/local/share/dotnet/sdk]
3.1.100 [/usr/local/share/dotnet/sdk]
3.1.301 [/usr/local/share/dotnet/sdk]

Same error with 3.1 sdk installed.

**Comment by lbcsy** [comment]
Okay, did a fresh clone and the build worked.
