### ISSUE TITLE
Dynamic Cache Tag Helper conflicts with ASP.NET Core cache tag helper

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6548]
There is an issue with the dynamic cache tag helper, where by default it conflicts with the ASP.NET Core Tag Helper, and both are activated, meaning the inner content is built by the ASP.NET Core tag helper, stored in it's memory cache, and then passed of to the dynamic cache tag helper, which then stores it, in it's cache.

This is because they are both targeting the `cache` element, but it means the `cache-dependency` doesn't have a scope available in the scope manager, as it is being rendered by the ASP.NET Core cache.

Removing the ASP.Net Core one fixes the issue
@removeTagHelper Microsoft.AspNetCore.Mvc.TagHelpers.CacheTagHelper, Microsoft.AspNetCore.Mvc.TagHelpers

So we could either just update the docs to say you have to remove the ASP.NET Core tag helper, or consider renaming the tag helper `dynamic-cache` perhaps?

I think clarifying the name would be a bit breaking, but a better solution long term.

@jtkech was able to repro as well, opening this issue so we can triage it

Related pr which identified the issue https://github.com/OrchardCMS/OrchardCore/pull/6518

**Comment by sebastienros** [comment]
New name

Two hard things, caching and naming

**Comment by hishamco** [comment]
What if we prefix all Orchard Core TagHelper using `oc` to avoid such collision?

**Comment by Skrypt** [comment]
I experienced this issue. Seems like the CacheTagHelper needs to be removed still in the _ViewImport file so that it doesn't collide with the default cache tag.

Also, a bit of documentation would help.

```C#
<dynamic-cache cache-id="dealers" expires-after="@TimeSpan.FromHours(1)">
    @foreach (var item in dealers)
    {
        <div>@item</div>
        <cache-dependency dependency="contentitemid:@item.ContentItemId"/>
    }
    <cache-dependency dependency="contentitemid:@item.ContentItemId"/>
<dynamic-cache>
```
