### ISSUE TITLE
Html field error

### ISSUE THREAD

**Issue by leone-91** [OrchardCMS/OrchardCore#6550]
Hi,
I noticed a problem when I try to use an html field of one of my page: when I use the <iframe> tag into this html field, the content I add just disappear after publishing. However when I use other common tags like <p>, it works normally... I was wondering if that was normal?

**Comment by leone-91** [comment]
By the way, it doesn't work even if I use a container

**Comment by ns8482e** [comment]
If you need to use `<Iframe>` use RawHtml

**Comment by leone-91** [comment]
Do you mean the filter raw? I tried to do this : {{ Model.ContentItem.Content.CabanePage.Calendrier.Html | liquid | raw }}
But I still have the same problem, I also tried just with the raw filter or the liquid one. 
Thanks for your help!
