### ISSUE TITLE
how to add a sample schema on the create query page ?

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#6554]
what is the right schema for here.

_Originally posted by @hyzx86 in https://github.com/OrchardCMS/OrchardCore/pull/6536/files_

**Comment by sebastienros** [comment]
We need to remove these text boxes, or put them in separate tabs, and document them.

**Comment by sebastienros** [comment]
Also make it visible only if the graphql feature is enabled.

**Comment by hyzx86** [comment]
But what should I fill in here? could you give me an example?

**Comment by hyzx86** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/8526
