### ISSUE TITLE
[Question] How do I do SQL query to get all workflows?

### ISSUE THREAD

**Issue by captmomo** [OrchardCMS/OrchardCore#6559]
And how do I export the workflows so I can use them in a recipe?

I noticed a PR has been made to include the feature of exporting workflows; https://github.com/OrchardCMS/OrchardCore/pull/2281/files/e326a7c453e993d780631e80a45f169a0143199b#diff-dc07ddeb0e12a8f978d81b1d4b028a0a  Where can I find this?

Edit; found the export function under deployment

**Comment by sebastienros** [comment]
I have been told you found how to export them, so closing.

**Comment by captmomo** [comment]
Hi

I still have not figured this out.
