### ISSUE TITLE
TablePrefix

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#6560]
For the tenant 's TablePrefix , if the user did not input it, will it use Tenant Name or string.empty?
Why do we allow the user to input, not tenant Name directly? and omit a place which will confuse non-dev guys.
thanks

**Comment by mariojsnunes** [comment]
For your 2nd question, only dev-guys should use the setup interface.
If you are making a SaaS service, you should build your own page and UX for creating new tenants, instead of using the default one. (This is what I'm doing)

**Comment by infofromca** [comment]
even dev-guys , the logic is still keeping the same.
non dev-guys just for example

**Comment by deanmarcussen** [comment]
Using a prefix for the database is optional, so if you want to use one you must specify it.

Some sites will use a prefix with the same database per tenant, some will use a different database per tenant.

**Comment by hishamco** [comment]
As Dean said, table prefix will be useful in case you want to use multiple tenants with the same database
