### ISSUE TITLE
Deprecated warning for Vue Draggable when editing MediaField

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#6562]
This warning (in Firefox it's an error) appears when editing a MediaField:

Element props is deprecated please use tag props instead. See https://github.com/SortableJS/Vue.Draggable/blob/master/documentation/migrate.md#element-props

Based on the migration guide this is a simple solution, and we should update [this file](https://github.com/OrchardCMS/OrchardCore/blob/a202ae204ac02b40de1c82d6af16468f54e7ccc6/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/MediaField/mediaFieldThumbsContainer.js) and based on a quick search [this one](https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore.Modules/OrchardCore.ContentFields/Views/TextFieldPredefinedListEditorSettings.Edit.cshtml) is affected as well.

Also, though it is not strictly related to this issue but I think it would be much nicer to refactor these Vue component template code to a shape instead of hardcoding it to a JavaScript file making developers unable to override it (or actually easy to find).

**Comment by deanmarcussen** [comment]
Fixed over here https://github.com/OrchardCMS/OrchardCore/pull/6558 just recently.

Feel free to review :)

**Comment by agriffard** [comment]
@hishamco Please let @barthamark close his own issue, he said there was the same kind of problem in another file: TextFieldPredefinedListEditorSettings.Edit.cshtml

**Comment by ns8482e** [comment]
It also means `Vue.min.js` is not used
