### ISSUE TITLE
When we use an unauthorized RESTAPI request, it will return the HTML content of a landing page.

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#6563]
https://github.com/OrchardCMS/OrchardCore/blob/7f76a2382dfa7d4b041ab1e7e8152954b4c0371e/src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/ApiController.cs#L63

When we use an unauthorized REST API request, it will return the HTML content of a landing page.
This method should always return a Json result instead of jumping to the login page.

**Comment by ns8482e** [comment]
I guess it just need to `Forbid` the request

**Comment by deanmarcussen** [comment]
The default `CookieAuthenticationOptions` event handlers for Identity use an `IsAjaxRequest` check which checks the 
`Query`, or `Headers` for an `"X-Requested-With` value of `XMLHttpRequest`.

So putting the correct header on should result in an appropriate api response.
