### ISSUE TITLE
add dropdown list

### ISSUE THREAD

**Issue by kandari7** [OrchardCMS/OrchardCore#6569]
The main issue with Orchard is no proper documentation. how do I add a dropdown list with static options in my content type???

**Comment by hishamco** [comment]
> The main issue with Orchard is no proper documentation

Our documentation is improving over the time, but that doesn't mean it will document all the custom use cases, that could done by developers


For your case you can create a content type for your list, then use content type picker, or you could render your list directly in your view

**Comment by kandari7** [comment]
Found out the way for this
