### ISSUE TITLE
TablePrefix conflict possibly

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#6571]
image, use1 use abc for first TablePrefix.
after 1 year, new user2 in the same company also use abc for second TablePrefix.
What happen?
#6560

**Comment by hishamco** [comment]
I was preferring to continuing with the old issue, anyhow the case you mentioned should not be allowed, especially if more than one tenant are using the same database

**Comment by sebastienros** [comment]
Site setup will fail.
