### ISSUE TITLE
AgencyTheme, gulp build/rebuild doesn't work:  Cannot find module './src/OrchardCore.Themes/TheAgencyTheme/wwwroot/gulpfile'

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#6576]
After merge the #6227 the gulpfile in the TheAgencyTheme is removed but the "main" gulpfile require it.

**Comment by agriffard** [comment]
Thank you for noticing.

The styles.css and scripts.js of theAgency are taken from the dist folder.

We don't need them to be built by gulp anymore.
