### ISSUE TITLE
Support AND in SQL JOIN clauses

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6579]
It would be good to extend the sql dialect to support the `AND` clause when performing a `JOIN`

I would like to be able to write a query such as 
```
  SELECT TOP (10) 
      [ContentItemIndex].[DocumentId]
  FROM [dbo].[ContentItemIndex]
  LEFT OUTER JOIN [dbo].[TaxonomyIndex] ON [dbo].[TaxonomyIndex].[ContentItemId] = [dbo].[ContentItemIndex].[ContentItemId] 

   AND [dbo].[TaxonomyIndex].[TermContentItemId] = '4rzh619w81ar45fjv1merrxb57' <-- AND clause here 

  WHERE [ContentItemIndex].[ContentType] = 'PageNews' 
  AND [Published] = 1
```

where the `LEFT JOIN`, has an `AND` clause, allowing to filter on a particular term id.

This would allow me to use the taxonomy to provide a `Featured News` tag, and so retrieve featured items first, then the latest items created.

Reference on SQL 92 JOIN clauses
https://flylib.com/books/en/4.343.1.38/1/

Note: I can make this work without the `AND` but the query becomes less specific, and doesn't allow for different types of `Featured tags` in the query

**Comment by sebastienros** [comment]
The sql parser itself needs to be able to understand it too.

**Comment by lampersky** [comment]
@deanmarcussen @sebastienros I've modified a bit **SqlGrammar** and **SqlParser**, and now you can have support for multiple **AND** clauses when performing **JOIN** and for using parameters instead of just column names.

[changes](https://github.com/lampersky/OrchardCore/commit/cc4d95df3fcc50a3718a7ed3d5c241b9c56959a8)

```
[InlineData("select a from b inner join c on b.b1 = c.c1 and b.b2 = @param", "SELECT [a] FROM [tp_b] INNER JOIN [tp_c] ON [tp_b].[b1] = [tp_c].[c1] AND [tp_b].[b2] = @param;")]
[InlineData("select a from b inner join c on 1 = 1 and @param = 'foo'", "SELECT [a] FROM [tp_b] INNER JOIN [tp_c] ON 1 = 1 AND @param = 'foo';")]
[InlineData("select a from b inner join c on 1 = @param left join d on d.a = @param left join e on e.a = 'foo'", "SELECT [a] FROM [tp_b] INNER JOIN [tp_c] ON 1 = @param LEFT JOIN [tp_d] ON [tp_d].[a] = @param LEFT JOIN [tp_e] ON [tp_e].[a] = 'foo';")]
```

**Comment by sebastienros** [comment]
@lampersky PR that and it's merged

**Comment by lampersky** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/8489
