### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#658]
Create some functional test based on this model:
https://github.com/sebastienros/yessql/commit/1d643b1f89b60592e1e6e2852bd31dc0b46e688d#diff-8fb18935c5447f1d9dc4900e72fe6bd7R14

A first step would be to publish the actual site in a specific location.

- We need to reuse the same deployment as much as possible. Currently O1 does a new Setup for every functional test which is really slow.
- We shouldn't have to use SpecFlow, it too cumbersome compared to the advantages.
- We need to use a fluen api to issue requests and test responses. Using a visual tool is not required. We might even use the same API as in O1.
- Javascript client tools are a possibility as they can also generate a screenshot when an issue happens.

**Comment by Jetski5822** [comment]
Specflow isent donet core compliant, and I tried using it this week with a project and it just doesnt work.

I would like to see the use of something like Browser Monkey https://github.com/featurist/browser-monkey - Super quick and nice dsl.

**Comment by sebastienros** [comment]
I think we should use https://github.com/GoogleChrome/puppeteer
