### ISSUE TITLE
Admin menu item returns all content types instead of the selected one in admin view

### ISSUE THREAD

**Issue by osolvi** [OrchardCMS/OrchardCore#6583]
Version `1.0.0-rc2-13700`

![image](https://user-images.githubusercontent.com/39261036/86507411-aa8e5500-bde0-11ea-91f8-f76127b9d133.png)

![image](https://user-images.githubusercontent.com/39261036/86507536-9434c900-bde1-11ea-813c-155e4e470a08.png)

**Comment by deanmarcussen** [comment]
Oops, yes I can repro this, and know where the issue is.
