### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6584]
Question from @mariojsnunes on Crowdin:

> Does this phrase make sense in English? Do you mean "The default frequency of these content types is likely to change?"

https://github.com/OrchardCMS/OrchardCore/blob/03407feab9ca06547a2d8e0d36763b5c4d93f7c1/src/OrchardCore.Modules/OrchardCore.Contents/Views/Items/ContentTypesSitemapSource.Edit.cshtml#L28

**Comment by Piedone** [comment]
I think yes, simply an "of" is missing.

**Comment by agriffard** [comment]
I would say:
`The default frequency with which these content types are likely to change.`
but I would like a confirmation from a native speaker.
