### ISSUE TITLE
Themes site settings

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6586]
The CurrentThemeName and CurrentAdminThemeName are a bit different than the other site settings.

They are not at the root like other General site settings and they are not in a specific property named Themes in the properties array.
They have their own deployment source and step to export/import.

I guess they have been implemented like this because it was one of the first feature.

Moving them to their own `Themes` sub-properties would make sense but it must be an important breaking change.

Do we keep it like this?

**Comment by deanmarcussen** [comment]
I would keep it as is, as it would be too breaking a change, and these are single value properties, so are ok being directly on `ISite` rather than `ISite.Properties` (it's not hurting anything)
