### ISSUE TITLE
Demo for OpenID authorization

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6588]
Hi, is there any demo available to enable openID client authorization.

Regards.

**Comment by infofromca** [comment]
https://www.youtube.com/watch?v=DsFC0EqCXkE&t=195s

**Comment by khurram4u2** [comment]
Hi Andy,

Thank you for quick reply. I have gone through the video. It is about how other applications can use openid server setup for authentication.

What I want that users can access our multi tenant CMS admin module using external provider authentication using openID.  So we don't have create local users.

Regards.
