### ISSUE TITLE
when i create a content of Page ,I meet the Problem below

### ISSUE THREAD

**Issue by zhhbo** [OrchardCMS/OrchardCore#659]
URL:http://localhost:2918/Admin/Contents/ContentTypes/Page/Create
An unhandled exception occurred while processing the request.

MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IndexingTask] where [ContentItemId] in ('4ymg18j5skrahttgsy7nghawc8')' at line 1
MySql.Data.Serialization.PayloadData.ThrowIfError()

AggregateException: One or more errors occurred. (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IndexingTask] where [ContentItemId] in ('4ymg18j5skrahttgsy7nghawc8')' at line 1)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

Stack:
MySql.Data.Serialization.PayloadData.ThrowIfError()
MySql.Data.Serialization.MySqlSession.TryAsyncContinuation(Task<ArraySegment<byte>> task)
System.Threading.Tasks.ContinuationResultTaskFromResultTask.InnerInvoke()
System.Threading.Tasks.Task.Execute()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()
MySql.Data.MySqlClient.Results.ResultSet+<ReadResultSetHeaderAsync>d__1.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.MySqlDataReader+<ReadFirstResultSetAsync>d__62.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.MySqlDataReader+<CreateAsync>d__61.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor+<ExecuteReaderAsync>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor+<ExecuteNonQueryAsync>d__1.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.MySqlCommand+<ExecuteNonQueryAsync>d__46.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Dapper.SqlMapper+<ExecuteImplAsync>d__29.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Orchard.Indexing.Services.IndexingTaskManager+<FlushAsync>d__11.MoveNext() in IndexingTaskManager.cs
var insertCmd = $"insert into [{table}] ([CreatedUtc], [ContentItemId], [Type]) values (@CreatedUtc, @ContentItemId, @Type);";
                await connection.ExecuteAsync(insertCmd, _tasksQueue, transaction);
            }
            catch(Exception e)
            {
                Logger.LogError("An error occured while updating indexing tasks", e);
                **throw;**
            }
            finally
            {
                transaction.Commit();
                transaction.Dispose();

at line 119

AggregateException: One or more errors occurred. (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[IndexingTask] where [ContentItemId] in ('4ymg18j5skrahttgsy7nghawc8')' at line 1)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
System.Threading.Tasks.Task.Wait()
Orchard.Indexing.Services.IndexingTaskManager.Dispose() in IndexingTaskManager.cs
-
            return Task.CompletedTask;
        }
        public void Dispose()
        {
            **FlushAsync().Wait();**
        }
        private async Task FlushAsync()
        {
            List<IndexingTask> localQueue;
Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
Microsoft.AspNetCore.Modules.ModularTenantContainerMiddleware+<Invoke>d__5.MoveNext() in ModularTenantContainerMiddleware.cs
-
                                }
                            }
                        }
                    }
                    **await _next.Invoke(httpContext);**
                }
            }
        }
    }
}
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by agriffard** [comment]
Has it been fixed in YesSql?
Please retest with the latest version and confirm it works.

**Comment by sfmskywalker** [comment]
Since this is more than a year old and I have not seen this issue anymore, I'm closing this.
