### ISSUE TITLE
Getting error when I click on GraphQL link from admin page

### ISSUE THREAD

**Issue by kandari7** [OrchardCMS/OrchardCore#6590]
I am getting this error "A field with the name: ContentType is already registered for GraphType: ContentType (Parameter 'Name')"

![image](https://user-images.githubusercontent.com/65922707/86541254-bc8e0600-bf4e-11ea-8f5d-e0c52e16cb40.png)

**Comment by infofromca** [comment]
#6487

**Comment by kandari7** [comment]
Same issue

**Comment by sebastienros** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/5536
