### ISSUE TITLE
"where placed" ResourceLocation is needed

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#6593]
On the odd occasion, it is necessary to have a stylesheet or script registered in the HTML exactly where is currently placed in the HTML. If you want to use all the features of the resource manager and/or the tag helpers, there is no way to prevent Orchard Core from loading it in the head or at the foot and still get all the goodness like versioning, debug, cdn and cache busting.

Use case: if you are working with HTML generated by Orchard Core in a SPA and you are leveraging the shadow DOM this requires that you inject styles at exactly the right place in the HTML.

**Comment by sebastienros** [comment]
In the templates we just register resources to be rendered later. This might need another attribute (tag is too heavy) to change the behavior of the tags such that they render the resource inline.

Something line `<script asp-name="bootstrap" at="inline" />` which would not use the ResourceManager.Register call, but render the resource inline.

**Comment by ns8482e** [comment]
If you want to render inline you could use plain html `<script>` or `<style>` tag

**Comment by scleaver** [comment]
> If you want to render inline you could use plain html `<script>` or `<style>` tag

@ns8482e - If you are using the resource management features like named resources, use-cdn etc then a plain HTML tag is not going to cut it unfortunately.

@sebastienros - I like your suggestion. I will have a go at creating a PR for this.

**Comment by ns8482e** [comment]
> @ns8482e - If you are using the resource management features like named resources, use-cdn etc then a plain HTML tag is not going to cut it unfortunately

@scleaver if you are using cdn url and named resource then there’s no benefit  adding it at inline as it’s already an external url loaded separately from the document html

**Comment by scleaver** [comment]
@ns8482e - you seem to be suggesting that there is another way around my need without creating an at="inline" enhancement but your not explaining your alternative solution. I would like to hear you out and understand your alternative.

First let me explain again in my use case - I want to use managed resources and managed resource features but I do not want the output (the link) of my managed resource (in this case a css file￼, which leverages named resources, cdn, debug versions and versions) to be placed in the head or foot but in the exact position where I place it within the HTML. Why you might ask? Well I am generating HTML templates from orchard for use in Vue.Js. The Vue.Js app needs to leverage shadow dom. In order to style HTML loaded in the shadow dom you need to load the css file within the shadow dom itself NOT in the header and footer of the page.

**Comment by ns8482e** [comment]
IMHO having named resource defined with `inline` won't help,

As,

1.  `css`  is applied to whole document, regardless of location of  `<style>` tag within document,  - In case If same style is defined more than once, browser takes the later definition by overriding first definition

2.  named resource gets rendered only once in the document. so due above reason,  It really doesn't matter if it's within `<head>` or somewhere in `<body>`, it always applied to whole document.

If you need style with inline content, currently you can define as following. See PR #5903 by @TFleury 

```cshtml
<style asp-name="custom-style" depends-on="thetheme-bootstrap-oc">
    .my-class {
        /* Some css rules */
    }
</style>
```

Normally we define `<style>` in head only to have `css` available before the content that use it. 

For your specific case, in vuejs, its better to use `shadow dom` for visual html elements and not for `<style>`
It's better that you define your style in your `*.vue` file, using `scoped` and not inside `<template>`

```
<style scoped>

</style>
```

or 

```
<style lang="scss" scoped>

</style>
```

Vue CLI will generate `app.css` scoped to your components and you could register it with resource manager and have it defined in `<head>`

For vue apps, I use `ViewComponent ` with following `Default.cshtml`.

```
<style asp-name="vueapp-myapp"></style>
<script asp-name="vueapp-myapp" at="Foot"></script>
<div id="myapp"></div>
```
and when I need to add `myapp` , I simply Invoke the `ViewComponent` from a shape or mvc view as following and It will register resources required for `myapp`

`@await Component.InvokeAsync("MyVueApp")`

I hope it helps.

**Comment by scleaver** [comment]
@ns8482e thanks for the detailed response. Maybe this is unique to our use case but perhaps others will want the feature for the same reasons we want it.

In response to your comments:

1. CSS is not applied to the whole document if the app and external stylesheet is loaded within the shadow dom. This is perfect for our use case as we don't want the app's CSS to be messed up by the CSS of the website OR vice-versa AND we want the performance gains of using shadow dom over iframe. 
2. We want to make use of named resources as we generate the HTML for the client-side app using Orchard Core templates. This is so tenants can override the templates if needed. If the named resource does not render into the template HTML for the root of the app then we have to load it another way and we lose all the resource management goodness.

Browsers support loading external stylesheets into the shadow for this very reason - so that you can style the HTML using an external stylesheet rather than having it inline or compiled into js.

Vuejs scoped styles do not work by taking advantage of the shadow dom - they work my transpiling the selectors to have a corresponding data-xyz attribute. Also, we don't want to put our CSS into *.vue for quite a few reasons (actually we don't use *.vue files anyway).

**Comment by ns8482e** [comment]
> 1. CSS is not applied to the whole document if the app and external stylesheet is loaded within the shadow dom.

@scleaver  I'd love to learn and see an example of css loaded via external url within a shadow dom which only applies to specific dom element  within the document but doesn't apply to whole document.  I think that would eliminate all my needs of having unnecessary css resets and bootstrap css overrides in my projects.

**Comment by scleaver** [comment]
Hi @ns8482e sorry I haven't got back to you on this. Here is an explaination: https://www.loom.com/share/c69f661afe724304aea66c041a0a3872

Yes this indeed helps you to eliminate all the need to guard you own CSS styles from being ruined by the host website.

I want to use external css files rather than VueJs internal styles for increased maintainability and performance so I still need a way to use Orchard Core resource management with my stylesheet that isn't loaded into the head.
