### ISSUE TITLE
OpenIdServerSettings recipe step results in having authorization code grant type all the time

### ISSUE THREAD

**Issue by alin-devnet** [OrchardCMS/OrchardCore#6602]
I'm trying to configure graphql authentication and setup OpenIdServerSettings recipe step to enable client credentials flow only, but ending with both `client_credentials` and `authorization_code` grant types saved in the database:

`"GrantTypes": ["authorization_code", "client_credentials"],`

Looking at OpenIdServerSettingsStep, that calls `openIdServerService.GetSettingsAsync()`, which adds `authorization_code` and `refresh_token` grant types by default, it then removes/adds grant types based on the recipe step configuration, but it never removes `authorization_code` (even if you set AllowAuthorizationCodeFlow to false).

Now looking at `OpenIdServerSettingsDisplayDriver.UpdateAsync(..) ` which is called when you edit openid settings from UI , it does have the logic for removing/adding the `authorization_code`. 

`if (model.AllowAuthorizationCodeFlow)
            {
                settings.GrantTypes.Add(GrantTypes.AuthorizationCode);
            }
            else
            {
                settings.GrantTypes.Remove(GrantTypes.AuthorizationCode);
            }`

**Comment by kevinchalet** [comment]
Thanks for the detailed explanation. I'll include a fix in my OpenIddict 3.0 migration PR that will be merged soon: https://github.com/OrchardCMS/OrchardCore/pull/4720.
