### ISSUE TITLE
System.ArgumentNullException: Can't resolve a scope on tenant

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#6605]
```
System.ArgumentNullException: Can't resolve a scope on tenant: Contoso (Parameter 'ServiceProvider')
   at OrchardCore.Environment.Shell.Scope.ShellScope..ctor(ShellContext shellContext)
   at OrchardCore.Environment.Shell.Builders.ShellContext.CreateScope()
   at OrchardCore.Environment.Shell.ShellHost.GetScopeAsync(ShellSettings settings)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Steps to reproduce this exception:
  - Create a new OrchardCore site.
  - Enable the OpenID server feature.
  - Create a new public application the code flow enabled and with `client_id`: `postman` and `redirect_uri`: `https://oauth.pstmn.io/v1/callback`.
  - Create a new OrchardCore tenant named `Contoso` and configure it.
  - Create a new `demo_api` scope with the  `Contoso` tenant checked.
  - Enable the OpenID validation feature in the `Contoso` tenant and choose `Default` as the server tenant.
  - Add a test controller using API authentication:

```csharp
[Feature(OpenIdConstants.Features.Validation)]
public class MyController : Controller
{
    [Authorize(AuthenticationSchemes = "Api")]
    [HttpGet("~/test")]
    public IActionResult Test() => Content(User.GetUserIdentifier());
}
```
  - Open Postman and configure it to retrieve an access token using the authorization code flow:

![image](https://user-images.githubusercontent.com/6998306/86937640-c6c32680-c13f-11ea-8f23-2e958c327c29.png)

  - Use the access token to query the demo controller in the `Contoso` tenant:

![image](https://user-images.githubusercontent.com/6998306/86938028-3cc78d80-c140-11ea-8250-5673705b5db6.png)

  - Go to the OpenID server configuration page in the main tenant. Save the changes.

  - Make a new HTTP call to the demo controller. If you get a non-error response, go back to the OpenID server configuration page and save the changes a second time and try again.

**Marking as P0 as this bug puts all the impacted tenants in a completely unusable state until they are manually restarted.**

@jtkech has anything changed recently that could explain this issue?

**Comment by jtkech** [comment]
@kevinchalet 

Okay i will try to repro asap and see what happens

But i'm a newbie in `OpenID` so i first need to be able to repro ;)

**Comment by jtkech** [comment]
@kevinchalet 

I had problem with a self signed ssl certificate, to get a new access token i needed to disable the ssl certificate verification in postman, but not in the settings of the request but in the global settings ;)

Finally i could repro the exact same issue and fixed it, will push a PR soon with some comments

**Comment by kevinchalet** [comment]
Fantastic, thanks! @jtkech 

> I had problem with a self signed ssl certificate, to get a new access token i needed to disable the ssl certificate verification in postman, but not in the settings of the request but in the global settings ;)

Yeah, that sucks: Postman doesn't use Schannel and doesn't support the Windows Certificate store, so even if the TLS self-signed certificate used by ASP.NET Core is trusted, it doesn't work with Postman... 😕 

Anyway, thanks a lot for taking a look at this issue 👏
