### ISSUE TITLE
Announcement: important changes affecting the OpenID module

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#6608]
The OpenID module [was updated to use OpenIddict 3.0 beta2 (released earlier today)](https://github.com/OrchardCMS/OrchardCore/pull/4720).

As part of this migration, a few properties were added to `OpenIdServerSettings` and `OpenIdValidationSettings` and others were renamed for clarity. Due to this change, existing deployments will have to be updated to use the revamped settings. No exception should be thrown and the migration should be limited to re-configuring the server/validation options using the UI and/or updating custom recipes to use the new names.

**An important aspect of this migration is that the validation feature now internally uses the OpenIddict validation handler instead of the Microsoft JWT bearer handler**, even with external OAuth 2.0 authorization servers.  Unlike the MSFT JWT handler, the OpenIddict validation handler uses the new `Microsoft.IdentityModel.JsonWebTokens` stack and comes with JWT token type validation enforced by default, which is required by [the not-yet-standardized JWT access token specification](https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-07).

This change will break existing deployments targeting OAuth 2.0 authorization servers that don't issue `"typ": "at+jwt"` access tokens. At least the following implementations are known to be impacted:

  - Azure AD/B2C.
  - IdentityServer3.
  - IdentityServer4, except its latest 4.0 version (unless 4.0 is configured to use a different `typ` header).

OpenIddict-based deployments are not impacted, as the validation handler includes special logic to deal with the tokens produced by OpenIddict 1.0 and 2.0, whose JWT tokens always include a special `token_usage` claim to prevent token substitution attacks, which has the same purpose as the `"typ": "at+jwt"` header.

To ensure the validation feature can still be used with servers that don't issue `"typ": "at+jwt"` access tokens, an opt-in option was added to the validation configuration UI:

![image](https://user-images.githubusercontent.com/6998306/86268422-75a7b580-bbc8-11ea-814f-a43282da39b3.png)

Note: this option can only be enabled when configuring a remote OAuth 2.0 server and is not shown when using a local OpenID server or a server located in another tenant, as OpenIddict 3.0 always issues `"typ": "at+jwt"` access tokens.

**Comment by kevinchalet** [comment]
@sebastienros looks like this announcement was unpinned. Is it safe to consider everyone had a chance to see it and close it?

**Comment by hishamco** [comment]
@kevinchalet what's the steps or procedures needed to close this, or it just announcement?

**Comment by kevinchalet** [comment]
No step needed, it's just an announcement.

**Comment by hishamco** [comment]
Ok, coz we are trying to close `1.0.0` remaining issues as much as we can

Thanks

**Comment by kevinchalet** [comment]
Note: additional functional changes were introduced in the latest nightly builds of the OpenID module. Users of this module are invited to review their authorization server options and edit their client apps to ensure they are correctly given the appropriate response type permissions, that were introduced in OpenIddict 3.0 beta6.

**Comment by sebastienros** [comment]
Everyone know now. Is there any special action to take when migrating from RC2 ?
