### ISSUE TITLE
Field and Body editor alignments / sizing

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6615]
There are some inconsistencies with sizing of some field elements settings and other views.

Some hints are full-width, some are restricted to col-md-6, other col-sm-6

Hint boxes, should also align together with the rest of the fields

![Screenshot 2020-07-09 at 08 24 53](https://user-images.githubusercontent.com/13782679/87010075-f4e74b80-c1bd-11ea-8477-e4b873fe097b.png)

**Comment by hishamco** [comment]
Should we agree to use `col-md-6` and move the first hint to the next line to save some spacing?

**Comment by deanmarcussen** [comment]
Hint texts should all be full width, not columned, and the hint box just needs it's sizing to match the checkboxes etc.

The sanitize html check box should line up with the beginning of the other elements.

**Comment by hishamco** [comment]
Let me check this all the content fields

**Comment by deanmarcussen** [comment]
Update on this.

There are two / three issues to resolve.

One is a regression from https://github.com/OrchardCMS/OrchardCore/pull/6509
The second is a semantic regression / change from a long time ago when we migrated from bootstrap 3 to bootstrap 4
The third is the actual sizing of fields editors in the admin (`col-md-6`)

Let me explain (and sorry for the novel)

Bootstrap 3 had no auto sizing column classes, such as, `col`, `col-md` . Bootstrap 4 has auto sizing classes.  https://getbootstrap.com/docs/4.1/layout/grid/#auto-layout-columns

We had our own autosizing bootstrap extensions which are used in _some_ places in the admin. But not in others (probably because no one knew about them, and they are not obvious because of the semantic changes in bs4.)

So in our admin css `col-md` kind of means to be a _mediumish_ column depending on the breakpoint, rather than be a column at the `md` breakpoint. This is superconfusing!

Here's the sass that makes it so
```
.col-md {
        @extend .col-12, .col-sm-12, .col-md-10, .col-lg-8, .col-xl-6;
}
```
So at `md` it's actually 10 units, but at `xl` it's actually 6 units. So it's not an `md` column. It's conceptually a medium sized column.

This made sense in bootstrap 3, because there was no concept of autosizing columns. So in bs3 `col-md` meant nothing. However in bs4 `col-md` now has significant meaning.

If you search the cshtml files there are roughly 30/40 usages of `col-sm` `col-md` `col-lg` currently not doing what they were doing. 

However for many many of the editors we are using `col-md-6`, i.e. the standard bootstrap design, which initially look a little like what the same inputs look like when using `col-md` but when resized, behave totally differently. And end up with different padding/margin arrangements.

Here's a gif. Focus on the difference between the _Display Name_ and the _What type of editor should be used_

![Kapture-col-issues](https://user-images.githubusercontent.com/13782679/87127880-9a65f200-c286-11ea-9a6b-a3589c2dbf88.gif)

What to do about this?

I see two options, 
- stick with the `col-md` concept, but rename it to `col-medium`, and we reuse it everywhere instead of `col-md-6` 
- remove the `col-md` concept, and we are explicit about how things behave, by placing the appropriate classes, i.e. `col-12 col-md-10 col-lg-8`

I'll start a pr restoring my regression issue, but think there is more to it, and wonder what others think.

/cc @Skrypt @jptissot @agriffard @hishamco 

@hishamco your pr is fine, but I think you need to merge dev to see the issue.

**Comment by hishamco** [comment]
> So in our admin css col-md kind of means to be a mediumish column depending on the breakpoint, rather than be a column at the md breakpoint. This is superconfusing!

Aha, that's why I surprised when I saw this class ;)

> @hishamco your pr is fine, but I think you need to merge dev to see the issue.

I started the PR based on the latest dev

**Comment by Skrypt** [comment]
Here we should never require to use the grid for form elements that are displayed inline. We should instead use w-sm-25, w-md-50, w-lg-100 to size these elements from what I remember.

**Comment by deanmarcussen** [comment]
Yeah, I think you're right @Skrypt it makes no sense to be the grid for sizing.

**Comment by hishamco** [comment]
Let me have a try ...

**Comment by hishamco** [comment]
> We should instead use w-sm-25, w-md-50, w-lg-100 to size these elements from what I remember.

Seems `row` class conflict with the above classes, i just remove it, and works great!! Shall I did the change for the other fields?
