### ISSUE TITLE
Menu Preview Issue

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6616]
Hi, I have created a CMS and custom template for menu. Now when I update menu link item and show preview changes show in body not in menu. Could you please help?

**Comment by ns8482e** [comment]
It preview button from Menu is removed #5317

**Comment by deanmarcussen** [comment]
We need to remove it from taxonomies as well before I forget.

@khurram4u2 for info because of the way menus are designed a live preview is not possible

**Comment by sebastienros** [comment]
Please rephrase the issue, it's not clear if you are missing the preview button, or if it doesn't work (though it has been removed).
