### ISSUE TITLE
Website in portfolio seems to be built with WordPress

### ISSUE THREAD

**Issue by xJonathanLEI** [OrchardCMS/OrchardCore#6625]
The first showcase website [Sexual Assault Centre of Edmonton](https://www.sace.ca/) seems to be built with WordPress instead of Orchard...

I'm not a WordPress expert but I'm seeing things that seem to indicate a WordPress backend:

- WordPress folders:

![image](https://user-images.githubusercontent.com/19556359/87133807-70362380-c2ca-11ea-9647-cb70f2728093.png)

- builtwith.com [suggests](https://builtwith.com/sace.ca) that the site is built with WordPress and PHP

This is extremely awkward... If it did use Orchard before, this is basically showing how people are abandoning the ship :( Please remove this site from portfolio.

**Comment by hishamco** [comment]
If there's a `Powered-By` header has a `OrchardCore` that means it uses OC

**Comment by xJonathanLEI** [comment]
Fair enough. Then where is that header specifically?

![image](https://user-images.githubusercontent.com/19556359/87142574-518a5980-c2d7-11ea-8fda-7bb24dd9490f.png)

**Comment by xJonathanLEI** [comment]
By contrast:

![image](https://user-images.githubusercontent.com/19556359/87142647-6d8dfb00-c2d7-11ea-9ddf-4e7466af434d.png)

**Comment by ns8482e** [comment]
@xJonathanLEI @hishamco may be the site has switched to wp after listed?

**Comment by deanmarcussen** [comment]
Yes, it looks like they may have moved to WP

Thanks for discovering this @xJonathanLEI 

/cc @agriffard to delist ?

**Comment by deanmarcussen** [comment]
and @Piedone for ShowOrchard

**Comment by hishamco** [comment]
> @xJonathanLEI @hishamco may be the site has switched to wp after listed?

May be

**Comment by Piedone** [comment]
Yep, they moved to WP, sad. I've removed it from Show Orchard. Plenty others remain though: https://showorchard.com/gallery/category/orchard-core

**Comment by agriffard** [comment]
ok, site changed by another one on orchardcore.net.
