### ISSUE TITLE
[Workflows] Http Request Event does not store the invocation token in a recipe

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#6630]
Hello,

When workflows are saved into recipes it appears  the invocation token does not get persisted. I understand why this is as that token has various pieces of information encoded within it. However, it means the recipe can not auto link forms to workflows. After the recipe has been installed, someone has to go through all the forms and workflows making sure they are linked up correctly.

Is there anything that can remove this need for a manual process please?

**Comment by agriffard** [comment]
Related to #5490
