### ISSUE TITLE
Sitemap/SEO Exclusion Not Working

### ISSUE THREAD

**Issue by andrew2241** [OrchardCMS/OrchardCore#6633]
I have enabled the Sitemap module in the admin area.  I have a particular content item that I have gone onto the SEO tab and checked the "Override sitemap configuration". I then check the Exclude checkbox, but the item still shows in my Sitemap.xml.  

Things I have tried:
I have purged the cache. 
I have cleared my browser cache, 
I opened the sitemap.xml in incognito. 
I updated all packages to latest available RC version 1.0.0-rc2-13450.

The content item still exists in the sitemap.xml. Is there anything else that I could be missing as to why I cannot exclude this content item from the sitemap?

**Comment by andrew2241** [comment]
Is there any advice on this?

**Comment by deanmarcussen** [comment]
I could not repro this.

Are you using any language related sitemap features?

Without excluding content item :
```
<urlset xmlns:xsi="http://wwww.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
<loc>/blog1/blog/post-1</loc>
<lastmod>2020-07-20T12:47:31+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>/blog1/blog/hidden-post</loc> 
<lastmod>2020-07-20T12:51:29+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>
</urlset>
```

With `Exclude` set to true
```
<urlset xmlns:xsi="http://wwww.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
<loc>/blog1/blog/post-1</loc>
<lastmod>2020-07-20T12:47:31+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>
</urlset>
```

**Comment by andrew2241** [comment]
Thank you Dean that keyed me into fixing it.  I did have Localized Content Item Sitemaps enabled.  Once I disabled that, I went and unchecked the Exclude, then Published.  I went back into the SEO tab settings and checked the Exclude and Published and it is now not being displayed.
