### ISSUE TITLE
Trumbowyg icons don't display

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6634]
Hi, I have create a content type with following parts 
![image](https://user-images.githubusercontent.com/56805276/87212765-a2479400-c363-11ea-9d6a-3b408002902a.png)

When I try to use trumbowyg editor for htmlbody part as per following SS 
![image](https://user-images.githubusercontent.com/56805276/87212796-d458f600-c363-11ea-8153-ade72665ecd4.png)

trumbowyg editor bar icon doesn't show 
![image](https://user-images.githubusercontent.com/56805276/87212832-01a5a400-c364-11ea-9029-6c5acaf0ab5f.png)

When I inspect the html there is following js query error.

![image](https://user-images.githubusercontent.com/56805276/87212858-2732ad80-c364-11ea-9b29-73735ce2b129.png)

Could you please advise?

Thanks

**Comment by hishamco** [comment]
@agriffard is there any regression bug?

**Comment by agriffard** [comment]
Your example works for me, but should keep the btnsDef if you want to see the image and align buttons:

```
{
  hideButtonTexts: false,
    autogrow: true,
    btns: [
        ["viewHTML"],
        ['emoji', 'giphy', 'fontfamily'],
        ["undo", "redo"],
        ["formatting"],
        ["strong", "em", "del"],
        ["foreColor", "backColor"],
        ["superscript", "subscript"],
        ["link"],
        ["image"],
        ["align"],
        ["unorderedList", "orderedList"],
        ["horizontalRule"],
        ["removeformat"],
        ["fullscreen"]
    ],
    btnsDef: {
        align: {
            dropdown: ["justifyLeft", "justifyCenter", "justifyRight", "justifyFull"],
            ico: "justifyLeft"
        },
        image: {
            dropdown: ["insertImage", "base64", "noembed"],
            ico: "insertImage"
        }
    }
}
```


![image](https://user-images.githubusercontent.com/703248/87223916-21979080-c381-11ea-9100-50bf514d27bf.png)

**Comment by agriffard** [comment]
Are you using the source code or a specific package version?

**Comment by khurram4u2** [comment]
@agriffard I am using following package versions.

![image](https://user-images.githubusercontent.com/56805276/87224008-e8810f80-c3c4-11ea-9191-5e5ad989a810.png)
