### ISSUE TITLE
SubMenu on Side bar

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6636]
Hi there, is there a way to achive that submenu shows in side bar like following SS, where sub menu item of about us display on left side of page.

![image](https://user-images.githubusercontent.com/56805276/87221263-ef505800-c3ad-11ea-9399-f4cf2c5df87d.png)

**Comment by ns8482e** [comment]
Using Taxonomy feature, You can organize your content in hierarchy

**Comment by hishamco** [comment]
This is #4494 a good explanation from @dodyg

**Comment by khurram4u2** [comment]
@hishamco is there any video tutorial to explain it a bit more in detail as I haven't used Taxonomy feature.

**Comment by hishamco** [comment]
I think @deanmarcussen did a lot of demos about Taxonomies, you could check the Lombiq YoubTue channel
