### ISSUE TITLE
How Users are informed of pending (halted) User Task activity of workflow operations? 

### ISSUE THREAD

**Issue by B-Esmaili** [OrchardCMS/OrchardCore#6640]
In Workflow we have a User Task activity which halts the workflow and wait's for user interactions to continue.Now the question is how users are informed there is pending works in dashboard? something like notification or whatsoever.

**Comment by jptissot** [comment]
I think right now it's meant to be an email notification. I think there is nothing preventing you from implementing a content type / item that holds user notifications
