### ISSUE TITLE
Render a Menu with 2 different template

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6641]
Hi, I want to using 2 different templates for same Menu using alternate. I am trying to render main menu using following shap tag. Could you please advise what will be template name, so it overides the default template.

{% shape "menu", alias: "alias:main-menu" , alternate: "Menu_Footer", required: true  %}

**Comment by ns8482e** [comment]
@khurram4u2 Menu alternate is added based on MenuName, if you are using same menu `main-menu` then alternate rendered is same.

**Comment by ns8482e** [comment]
@khurram4u2 I have not tried, following is in documentation, see how alternates are added for menu

https://docs.orchardcore.net/en/dev/docs/reference/core/Placement/#manipulating-shape-metadata
