### ISSUE TITLE
Manage Own Media issue

### ISSUE THREAD

**Issue by staymo** [OrchardCMS/OrchardCore#6645]
Just found that the permission "Manage Own Media" is not acting as what it means -- user with this permission can view/edit/delete all the media files. Is this a bug?
To reproduce,  just create a new user, don't assign it to any role, then give the role authenticated following permissions:
View all content;
Access admin panel;
Manage Own Media

version:     <PackageReference Include="OrchardCore.Application.Cms.Core.Targets" Version="1.0.0-rc2-13799" />

any idea? thanks.

**Comment by hishamco** [comment]
I think I saw similar issue before, let me try to find it ...

**Comment by staymo** [comment]
@hishamco Thanks.
Just noticed that I failed to put the version. my version is:
 "OrchardCore.Application.Cms.Core.Targets" Version="1.0.0-rc2-13799"

**Comment by hishamco** [comment]
Thanks @staymo I will try to reproduce that too, @deanmarcussen is `Manage Own Media` works as expected

**Comment by sebastienros** [comment]
I don't remember if we implemented the "username" folder /cc @matiasmolleja

**Comment by matiasmolleja** [comment]
Hello,
Sorry for being so late!
I never did. 
I found the permission created and never removed it. 
Maybe it could be better if we simply remove it until we add the concept of ownership to media items?

**Comment by hishamco** [comment]
Ok @matiasmolleja let me have a look if I can implement it or remove until we implement it

**Comment by sebastienros** [comment]
Yes we can remove it, and keep an issue open to track the feature.

**Comment by hishamco** [comment]
Closed with the respect of #9369
