### ISSUE TITLE
Released Device Preview Module on Nuget.org

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6649]
## Released Device Preview Module for RC2+
Device Preview module for RC2+ . This module adds an ability to see live preview for different devices while editing content item.

### Nuget Package
https://www.nuget.org/packages/Surevelox.OrchardCore.DevicePreview/

### Documentation Url
https://github.com/surevelox/OrchardCore.Modules/blob/master/DevicePreview/README.md

![image](https://user-images.githubusercontent.com/23270244/87273225-21d97e00-c49e-11ea-8811-ce97fb8f6664.png)

**Comment by sebastienros** [comment]
If it was open sourced we should copy the code.

**Comment by ns8482e** [comment]
Yes! That's the plan
