### ISSUE TITLE
Can't setup Registration and Login Script with Recipe

### ISSUE THREAD

**Issue by FelixStumvoll** [OrchardCMS/OrchardCore#6651]
I'm currently trying to setup a recipe to "bootstrap" my cms.
however i the login/register script wont get set.

the login settings (inside the settings step) look like this:
```
"LoginSettings": {
    "UseScriptToSyncRoles": true,
    "SyncRolesScript": "Test"
}
```

but the script wont get set. the same applies for the register script

**Comment by agriffard** [comment]
The script is correctly imported but there is a condition that displays the defaut commented script if the lineCount is equal to 1 (which is your case).

**Comment by FelixStumvoll** [comment]
ah thanks for the info
