### ISSUE TITLE
De-list Github packages

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#6658]
Github packages are confusing - current release is `RC 2 (latest)`. 
However Github packages are showing `1.0.0-rc1-13285`

If Github packages are not being updated on every release, it's better to de-list them to avoid confusion.

**Comment by agriffard** [comment]
We need to contact GitHub support to delete public packages:
https://docs.github.com/en/packages/publishing-and-managing-packages/deleting-a-package#about-public-package-deletion

**Comment by ns8482e** [comment]
@agriffard not asking to delete  - just hiding it. Isn't there any option to un-list the package?

**Comment by sebastienros** [comment]
We are not generating github packages anymore, we can just remove them.
The "used by" is based on NuGet.org packages, not the ones in GH.

**Comment by ns8482e** [comment]
Oh, i see - then why it's showing only `Used by 6`, hard to believe

**Comment by sebastienros** [comment]
Becuase it's only looking at a small subset of the packages, and also because not many project actually reference these packages. When you build a website, you are not often on GH, and might not reference the packages that GH it looking at.

**Comment by deanmarcussen** [comment]
If it is the `Used By` feature you are concerned about @ns8482e see this issue https://github.com/OrchardCMS/OrchardCore/issues/5942

`Used By` is not related to github packages

**Comment by ns8482e** [comment]
@deanmarcussen thank you for `Used by` - it's informative.

However my concern is relatively simple (uncheck in settings below), to remove packages from repository home as it's adds to confusion as it's not matching with current release. 

![image](https://user-images.githubusercontent.com/23270244/87796167-9c8ff980-c80e-11ea-9b9c-cabdded6e825.png)

**Comment by agriffard** [comment]
Where do you see this 'Include in the home page' section?
I don't find anything similar in th project settings.

**Comment by ns8482e** [comment]
You can access by clicking on gear icon next to About on main page.
![image](https://user-images.githubusercontent.com/23270244/87855702-91f16500-c8df-11ea-8c4f-66847486af59.png)

**Comment by agriffard** [comment]
Ok, I unckecked the packages.
