### ISSUE TITLE
OpenId Connect Recipe Step not working

### ISSUE THREAD

**Issue by FelixStumvoll** [OrchardCMS/OrchardCore#6659]
Im trying to setup the `OpenIdServerSettings` with a Recipe as shown [here](https://docs.orchardcore.net/en/dev/docs/reference/modules/OpenId/). 
This is my current step:
```
{
    "name": "OpenIdServerSettings",
    "EnableTokenEndpoint": true,
    "EnableAuthorizationEndpoint": false,
    "EnableLogoutEndpoint": false,
    "EnableUserInfoEndpoint": false,
    "AllowPasswordFlow": false,
    "AllowClientCredentialsFlow": true,
    "AllowAuthorizationCodeFlow": false,
    "AllowRefreshTokenFlow": false,
    "AllowImplicitFlow": false
}
```
however if `EnableAuthorizationEndpoint` is disabled, it crashes and bricks the cms showing this error:
![image](https://user-images.githubusercontent.com/22666794/87391252-b03b2600-c5aa-11ea-8da2-292602521f60.png)

also if i set `EnableAuthorizationEndpoint` to true, it automatically sets `AllowAuthorizationCodeFlow` to true even if its set to false in the recipe

**Comment by FelixStumvoll** [comment]
i just tried it with a asp.net application and orchard core as a nuget dependency and there it works just fine

**Comment by deanmarcussen** [comment]
I think this was fixed recently in 
https://github.com/OrchardCMS/OrchardCore/pull/4720 to resolve this issue https://github.com/OrchardCMS/OrchardCore/issues/6602

You didn't say which version you are using initially but maybe an older one?

Also worth seeing the announcement on the changes to open id that happened last week. It is pinned

**Comment by FelixStumvoll** [comment]
ah yes im sorry 
i think i was using an older version, my bad
