### ISSUE TITLE
OrchardCore.Forms Checkboxes Not Maintaining State Upon Re-Displaying Page After Validation Error

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/OrchardCore#6667]
I brought up an issue last month regarding Workflow validation of a Checkbox List that I was trying to create. See https://github.com/OrchardCMS/OrchardCore/issues/6472. Basically, although I could set up a Workflow to validate this Checkbox List, the problem was that the values of the individual checkboxes were not being maintained when the form was re-displayed if there were other validation errors on the page

I attempted to use the OrchardCore.Forms Input with the type set to "Checkbox". I used the same name for two checkboxes, making it into a "List" I assume, but they each had different values (lists have the same "name", but different "values). I then hooked up a Workflow Validate Form Field Task to the Checkbox name to make it required. 

I am getting the same behavior. If neither checkbox is checked, I get the appropriate model error. But if one or both of the checkboxes is checked, and another field on the form generates an error, then upon the page being re-displayed both checkboxes do not maintain their state of being checked.

I suspect the same problem will occur with a radio button, but have not confirmed.

Not sure if this is intended, a bug, or just a missing feature. Thanks.

**Comment by rjpowers10** [comment]
I wonder if this could be related to #7174

**Comment by ns8482e** [comment]
Unchecked Checkbox and Radio are not submitted within `<form>`  by browser,  so ASP.NET is not aware of it on server side.

**Comment by gvkries** [comment]
Actually this is even worse: If you have a group of radio buttons or checkboxes with the same name, the value of all checkboxes or radio buttons are changed to the selected value when the form is re-dispayed.
