### ISSUE TITLE
Help on OpenID

### ISSUE THREAD

**Issue by RobinC4** [OrchardCMS/OrchardCore#6668]
Hi,
Just a question if someone can help me or point in the right direction.
I'm a bit new to the identityserver and openid, and the documentation on both orchard core as other sources like openiddict are a bit overwhelming for me with all the types of flows and all...

The question is on how to set it up working. The openId module probably makes it easy, but I can't get it right.
Idea is to have the main application running the authorization server, which will authorize users logging in and also users from another tenant. Later, we might expand this to authorize users on an external application, but first get this working.
Probably this does not sound complicated, but I think I'm missing maybe obvious things.

I did enable the github authentication on a tenant, set it up and got it working, where on the login you are able to select github, which authorizes you and you can login and then link the external login. Yes, this was easy enough.

I enabled the authorization server in the default tenant, enabled all endpoints, allowed authorization code flow. Then created a scope that marks the other tenant. And in the token validation, he marks himself (Default) as authorization server tenant.
On the other tenant, I removed the github authentication, and set the "Default" as authorization server tenant.

Now I don't see any button like that appearing on the login to authenticate like the github one or can I link the account or something like that. I've looked through documentation and am just missing a first time setup example that works, as I guess once you know it's straightforward.

Another question, since I'm new to this, is this the same as Single Sign On or can you use this for it. For example, if we make an external application (or even a tenant for that matter) where you login, could you immediately access the main one without having to login again?

Thanks in advance.

**Comment by hishamco** [comment]
I'm new to Identity Server too ;) It's in your plate @kevinchalet

**Comment by hishamco** [comment]
Regarding SSO it's not supported but it's doable in OC

**Comment by kevinchalet** [comment]
Hey,

The token validation feature is for API endpoints. What you're looking for is the client feature if you want a tenant to authenticate users using an OpenID server located in another tenant.

For that, create a new client in the server tenant and enable the client feature in your other tenant. You'll then need to populate the server details in the configuration UI (we don't currently offer a way to simply select the server tenant like in the token validation feature).

**Comment by RobinC4** [comment]
> Regarding SSO it's not supported but it's doable in OC, please refer to #2900

Thanks a lot, I will look into this then.

> The token validation feature is for API endpoints. If you want a tenant to authenticate users using an OpenID server located in another tenant, what you're looking for is the client feature.
> 
> For that, create a new client in the server tenant and enable the client feature in your other tenant. You'll then need to populate the server details in the configuration UI (we don't currently offer a way to simply select the server tenant like in the token validation feature).

Thanks, so I was indeed not using the right module.
I've done the steps of adding the client application in the authorization server, then enabled the client feature in the tenant and set the details:
- authority: https://localhost:5001/connect/authorize
- selected Code Authentication Flow with Use 'code' response type and set the client secret at the bottom the same as the configured in the server tenant.

This indeed now shows on the login page of the tenant but am getting an exception when I click it:

```
IOException: IDX20807: Unable to retrieve document from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
    Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)
    Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(string address, IDocumentRetriever retriever, CancellationToken cancel)
    Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)
```
and
```
InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.

    Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)
    Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
    Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
    Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.ChallengeAsync(AuthenticationProperties properties)
    Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
    Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
```


Have tried playing around with things, but to no avail. Search online it mentions problem with https.
I have tried enabling the https module for both but to no avail.

Thanks already for the help, this is probably the last hurdle.

**Comment by RobinC4** [comment]
I added something in startup.cs for that PII is hidden, and got this message to show now also:
IOException: IDX20807: Unable to retrieve document from: 'https://localhost:5001/connect/authorize/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
Date: Wed, 15 Jul 2020 10:23:34 GMT
Server: Kestrel
Transfer-Encoding: chunked
X-Powered-By: OrchardCore

**Comment by RobinC4** [comment]
Okay, so after a break doing something else, took a new look, saw in the console some more logs and figured I needed to put the callbackpath settings of the tenant on the main server tenant. Then everything worked.
Am happy!
This will be easier to set up again now I know some more, but there's still a lot of information to process like the different flows.

We will take a look at doing the SSO in few months when it becomes relevant.
Thanks again.

**Comment by kevinchalet** [comment]
Glad you sorted it out, @RobinC4! 👏
