### ISSUE TITLE
OpenId Audiences settings is missing from RC2

### ISSUE THREAD

**Issue by nitewulf** [OrchardCMS/OrchardCore#6669]
I feel like that setting is the missing sauce to enable accessing protected routes on my Strapi server.  I was reading through the doc here: https://docs.orchardcore.net/en/dev/docs/reference/modules/OpenId/

and see that I need to tell the OpenId module that I want to have access to an external resource server.  These are all the settings that I see on my server.  How do I get that Audiences set?

![image](https://user-images.githubusercontent.com/8270448/87456138-80a11380-c5d4-11ea-9ae8-5b3deea54f50.png)

**Comment by nitewulf** [comment]
I also have tried using a recipe as shown in the doc:
https://docs.orchardcore.net/en/dev/docs/reference/modules/OpenId/#configuration

I get an exception when I try and run it:
Error converting value "JsonWebToken" to type 'OrchardCore.OpenId.Settings.OpenIdServerSettings+TokenFormat'. Path 'AccessTokenFormat', line 15, position 38.

Is this doc outdated:
"AccessTokenFormat": "JsonWebToken", // JsonWebToken or DataProtection

What are the valid values for the AccessTokenFormat?

**Comment by kevinchalet** [comment]
> How do I get that Audiences set?

Exclusively via scopes. The `Audiences` mentioned in the documentation is a quite old leftover. I'll make sure it's removed.

> Is this doc outdated:

Actually no, it's the opposite: the documentation applies to the latest nightly builds, where the values have been tweaked for clarity.

**Comment by kevinchalet** [comment]
Fixed: https://github.com/OrchardCMS/OrchardCore/commit/1362bf3d06ede66a69c981fee5113e9d1433866c
