### ISSUE TITLE
Tenants is greyed out for adding a new scope

### ISSUE THREAD

**Issue by nitewulf** [OrchardCMS/OrchardCore#6671]
I am trying to access a protected route on a Strapi server after logging in with OrchardCore.  I have been able to add Orchard as a provider in Strapi and get an Authorization token back from Orchard.  I believe I need to pass in additional Scopes during the auth process to get access to the protected routes.  For example, Strapi tells me one of my routes is bound to "storage-location.find".  So I'm adding a new scope like this:

![image](https://user-images.githubusercontent.com/8270448/87464565-50ac3d00-c5e1-11ea-88af-cec7e74a7526.png)

But I can't check the Default Tenants, its disabled.

Also from the doc @ https://docs.orchardcore.net/en/dev/docs/reference/modules/OpenId/

I also see that the description of a Tenant is "Build the audience based on tenants names.".  It sounds to me like it may be related to the Audience setting that I can't find in my previous question.

How do I enable a Tenant for a new Scope and is it related to the Audience setting that I can't find in the OpenId settings?

**Comment by kevinchalet** [comment]
> But I can't check the Default Tenants, its disabled.

The server tenant is always disabled because it's always included in the access token audiences, even if you use no scope.
That said, I agree it's not super clear: we should probably check the server tenant checkbox even if it's always greyed out.
