### ISSUE TITLE
Liquid "container" not working correctly inside flow part of content items inside list part

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#6674]
Because the title is a little bit confusing, the following explanation also provides the repro steps for this scenario.

1. Create a `ContentType (**A**)` with a `ListPart`
2. Create a `ContentType (**B**)` with a `FlowPart`
3. Add **B** to the `ListPart `of **A**
4. Create a new `Item A`
5. Create a new `Item B` inside the `ListPart` of **A**
6. Create a nested layout inside the `FlowPart` of new `Item B` (It's easier to see when you add `TitleParts` to your nested `FlowPart` elements)
7. Add `{{ Model.ContentItem | container }}` inside every template of your nested `FlowPart` elements

Result when displaying `Item B`: The container element of every item is the same. It's the top element of `Item A's FlowPart`, no mather how deep the element is inside the nested `FlowPart` hierarchy.

If you just create `Item B` outside of the `ListPart`, `{{ Model.ContentItem | container }}` works perfectly fine.

**Comment by deanmarcussen** [comment]
> Add {{ Model.ContentItem | container }} inside every template of your nested FlowPart elements

I am struggling to understand your description. But I suspect what you are trying to do would not work.

Can you post a screen shot of your content item?

`{{ Model.ContentItem | container }}` will only work on the item that is a member of a list, not any nested items.

**Comment by ns8482e** [comment]
@deanmarcussen IMO liquid filter `container` name is misleading, it seems its only for `ListPart`  but it's name adds confusion to content type `Container` which uses `FlowPart`

https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore.Modules/OrchardCore.Liquid/Filters/ContainerFilter.cs#L27

**Comment by jtkech** [comment]
@ns8482e I agree and maybe it would have to be defined / registered in `OC.Lists`, see #6691

**Comment by deanmarcussen** [comment]
@ns8482e @jtkech yes I also agree the name is deceptive.

Still not sure if that is what @Flarescape is struggling with, but quite possibly it is?

It would be ok to register it under a new name, but only if the existing name is also registered, or it is breaking.

Agree it should be in the lists project and it should not be doing this `contentItem.Content?.ContainedPart?.ListContentItemId` but looking at the `ContainedPart` model

**Comment by Flarescape** [comment]
I'm sorry that my explanation is a little bit confusing.
I'll try to describe my current scenario.

Inside our new company website I've created a `ContentType` named `LayoutPage` which is used to create "normal" content pages.
This `LayoutPage` has a `FlowPart`.
To match the bootstrap layout, I've also created some more content types with stereotype **widget** like "Container", "Row", "Column".
They all have `FlowParts` to nest them correctly for bootstrap.
Also they all have their own liquid templates.
For example, this is the template for "Row":
```
<div class="row">
  {{ Model.Content.FlowPart | shape_render }}
</div>
```
So it will look something like this when editors are building a page:
![image](https://user-images.githubusercontent.com/1375119/87692653-44b0ae80-c78c-11ea-820b-d6f73a8d3ec6.png)

**And now for the actual problem:**
If I create a new `LayoutPage` as shown in the image, the `| container` of "Column" is "Row", of "Row" it's "Container".
But if you create a `LayoutPage` inside a `ListPart` of another `ContentItem` and create the exact same `FlowPart` layout, the `| container` inside the "Column" template will return "Container" or just "LayoutPage" which is obviously wrong.

I really don't know how this is effected because of the `ListPart`.
I absolutely need the first behavior and, I think, expected behavior to work everywhere the same way.

**Comment by deanmarcussen** [comment]
> I really don't know how this is effected because of the ListPart.

Thanks for the image, it is making more sense now.

The `container` filter, only works on an item contained by `List`, and it will return either the list item or the current item.

So I suspect when you try to use it on a flow, Column, it will return the Column item.

It is not designed to work for flow items.

Flow Items do not track their parent content item, so there is no way to know this information from within the item.

You can provide your own override of the `FlowPart` and pass this information down yourself as a shape property, but it is one directional, i.e. you need to pass information down, you can't go back up to try and get it.

**Comment by Flarescape** [comment]
@deanmarcussen The thing is, that the `container filter` **IS** working with `FlowParts`, but only if the the content item with a `FlowPart` attached is not inside a `ListPart`.
Here is an example:

Scenario 1 - A content type ListContainer (**not inside a ListPart**) with a FlowPart:
![image](https://user-images.githubusercontent.com/1375119/87928558-4ed0f680-ca85-11ea-80fe-5fa5fe25ab55.png)
---------------------------------------
Scenario 2 - A content type ListContainer (**created inside a ListPart**) with a FlowPart:
![image](https://user-images.githubusercontent.com/1375119/87928744-96578280-ca85-11ea-9d9b-cbc269567979.png)
---------------------------------------
As you can see, I've made the exact same layout as shown in my previous post and it behaves differently.
It's the same content type, but one inside a `ListPart` and the other one not.
So the `ListPart` effects the `FlowPart` of the containing content items or just the `container filter`.

**Comment by deanmarcussen** [comment]
Just read your edit @Flarescape 

So it works as it is designed, but not how you would like it to work?

Perhaps you could update the docs if it is missing to help out others in the future?

**Comment by sebastienros** [comment]
Correct, the container filter is only for lists. Let's add more documentation if it's confusing.
