### ISSUE TITLE
Pager issue with taxonomy term lists of categorized items on the front end

### ISSUE THREAD

**Issue by serverside-is** [OrchardCMS/OrchardCore#6675]
The pager is not working with the list of categorized content items for a taxonomy term.

Repro:

1. Create a Blog using the Blog recipe
2. Add/Clone a few Blog Posts. Use the Taxonomy Picker to categorize many of them with the same Term (e.g. "Earth").
3. Go to the Site and enter the Term page (e.g. https://localhost:5001/tags/earth)
4. Try the pager

At a first glance, looks like the pager is creating links like
`https://localhost:5001/tags?jsonPath=TaxonomyPart.Terms%5B0%5D&any=tags&slug=earth&after=637303986708164752`
instead of `https://localhost:5001/tags/earth?after=637303986708164752`.

Apparently this has nothing to do with #6458 (and it also does not work with the default page size of 10).

![categorizedItemsPagingBug](https://user-images.githubusercontent.com/3681658/87527460-1051cb00-c684-11ea-8fbf-0893c502d1c9.gif)

**Comment by deanmarcussen** [comment]
@jtkech have been looking at this today as it's causing a problem with the `PagerSlim` in general for me.
i.e. not limited to taxonomies, but everything using a `Pager` with `Autoroute`

<img width="633" alt="Screenshot 2020-08-13 at 14 49 17" src="https://user-images.githubusercontent.com/13782679/90142386-372f1a00-dd74-11ea-8ff2-d6ff8c72f362.png">

To repro create more than 10 blog posts.

Then navigate to `https://site/blog` (not the home route, but the `Autoroute` that is set for blog)

any Pager links then get become `https://localhost:5001/blog1?any=blog&after=637329226442266740`

so they are catching the routevalues from the `AutorouteTransformer` `"/{any}/{**slug}"` route pattern, I think via the `AutoRouteValuesAddressScheme` `AmbientValues` property.

The same applies if there are other `AmbientValues` , i.e. the taxonomy / json path values.

In the `PagerSlim` we're building a pager based on route values from the view context, so we end up with more than what we want.

```
var routeData = new RouteValueDictionary(Html.ViewContext.RouteData.Values);
```

I actually needed a tweaked `PagerSlim` so I can just remove the values I don't want for this site, but it would be good to figure out what's going on here.

**Comment by jtkech** [comment]
Hmm, I'm a little afraid of this one ;)

I will start on it tomorrow night
