### ISSUE TITLE
OpenIdServerSettings Recipe Ignoring Audiences

### ISSUE THREAD

**Issue by nitewulf** [OrchardCMS/OrchardCore#6682]
My recipe which does execute is not working fully.  I have noticed three issues.

1.  The Signing/Encryption appears to be ignored.  I know the settings are correct but in the UI for the settings I have to configure it manually.

2. The AccessTokenFormat in the doc says to use JsonWebToken as the value.  That is wrong.  It just needs to be JWT.

3. Most importantly, the Audiences are ignored.  Here's the last portion of the decoded token I get:

  "aud": [
    "oct:Default",
    "storage-location.find"
  ],
  "azp": "SAMS",
  "nbf": 1594838655,
  "exp": 1594842255,
  "iat": 1594838655,
  "iss": "https://orchard.ddns.net/"
}

and the recipe i used:

`{
  "name": "SetupOpenId",
  "displayName": "Setup OpenId Server",
  "description": "Configures the settings unavailable in the UI",
  "author": "Scott",
  "website": "https://website.net",
  "version": "2.0",
  "issetuprecipe": true,
  "categories": [ "default" ],
  "tags": [ "default" ],
  "steps": [
	{
	  "name": "OpenIdServerSettings",
	  "TestingModeEnabled": false,
	  "AccessTokenFormat": "JWT",
	  "Authority": "https://orchard.ddns.net",
	  "Audiences": ["https://orchard.ddns.net", "http://40.122.117.27"],
	  "SigningCertificateStoreLocation": "LocalMachine",
	  "SigningCertificateStoreName": "My",
	  "SigningCertificateThumbprint": "‎fc5e1667c8cfb31f602f2a9d6838d36a1c210b5f",
	  "EncryptionCertificateStoreLocation": "LocalMachine",
	  "EncryptionCertificateStoreName": "My",
	  "EncryptionCertificateThumbprint": "fc5e1667c8cfb31f602f2a9d6838d36a1c210b5f",
	  "EnableTokenEndpoint": true,
	  "EnableAuthorizationEndpoint": true,
	  "EnableLogoutEndpoint": true,
	  "EnableUserInfoEndpoint": true,
	  "AllowPasswordFlow": true,
	  "AllowClientCredentialsFlow": true,
	  "AllowAuthorizationCodeFlow": true,
	  "AllowRefreshTokenFlow": true,
	  "AllowImplicitFlow": true
	}
  ]
}
`

**Comment by kevinchalet** [comment]
Please don't open multiple threads for what is basically the same question.

**Comment by kevinchalet** [comment]
As said in the other thread, audiences are configured via scopes and not globally via the server settings.

Regarding your other questions, the name changed in the nightly builds - as announced in https://github.com/OrchardCMS/OrchardCore/issues/6608.

The docs for RC2 can be found here: https://github.com/OrchardCMS/OrchardCore/blob/1.0.0-rc2/src/docs/reference/modules/OpenId/README.md
