### ISSUE TITLE
Create Template for Content Type: Improve user experience

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#6684]
The UX needs some improvements when you create a template from the Edit page of a content type, clicking on the 'Edit Templates' dropdown button and selecting an action to create a Details or Summary view.

It is not obvious, for people that don't know what Templates are, to understand what happened.

Some people reported on Gitter that they clicked on the button and then didn't know why the Details or Summary page for the corresponding content type was blank.

They just didn't get that a Template had been created and that they could edit it from an admin page.

Reasons of this misunderstanding:
- After the creation, you are redirected to the previous url, which was the Edit content type page, without any notifications.
- You are not warned or prevented from saving with an empty Template.
- Beginners don't know that they can manage the Templates from the Design > Templates admin menu.

**Comment by hishamco** [comment]
> It is not obvious, for people that don't know what Templates are, to understand what happened.

Exactly!! even me I don't totally know what are features supported by templates

So, is the action needed to:

- Create a notification after creation

- Avoid saving empty templates

- Writing some extra docs

or is there something else we can add on the list?

**Comment by hishamco** [comment]
I can handle the first two points
