### ISSUE TITLE
New Tenant non HTTPS

### ISSUE THREAD

**Issue by nitewulf** [OrchardCMS/OrchardCore#6688]
I've learned that I need to create a Tenant and tell a newly created Scope that it is associated with that tenant for the generated JWT to include the correct resource server.  I'm in the processing of setting up the new Tenant, but it is just running over HTTP

After setting the host name, I see that the Tenant URI is automatically prepended with https://.  Is there a config file that can be updated to allow an http tenant?

**Comment by nitewulf** [comment]
I did some more reading and it appears that additional Tenants are just other orchard instances running under the default Tenant. 

If that's true... is it impossible to get a JWT by authorizing with an Orchard user and accessing a REST API from a Resource Server that is not Orchard?

**Comment by sebastienros** [comment]
@MichaelPetrinolis do you understand the question?
