### ISSUE TITLE
Manifest circular dependency

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#6691]
Just saw in the manifests this circular dependency

    OC.Contents => OC.Liquid => OC.Contents

Also the `ContainerFilter` defined in `OC.Liquid` may have to be defined in `OC.Lists`, didn't check other ones.

**Comment by deanmarcussen** [comment]
Yes, it should be defined in lists

**Comment by hishamco** [comment]
@deanmarcussen did your last changes about the references update the projects only or it include the manifests?
