### ISSUE TITLE
Page Flow part broken

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#6710]
![image](https://user-images.githubusercontent.com/13991195/87844705-a6e4de80-c874-11ea-9bbd-7ec3f2b5b88b.png)
The container positioning broke, I can't position it  on the center or the right

**Comment by ns8482e** [comment]
@rserj It’s for text alignment

**Comment by rserj** [comment]
@ns8482e thanks for your feedback.
It looks like, in order to position a container on the right, I have create another empty one on the left first, otherwise, it won't work
 
![image](https://user-images.githubusercontent.com/13991195/87856902-2a371c00-c8d7-11ea-8265-650526374683.png)

I think I'll close the issue
