### ISSUE TITLE
Error While enable OpenID feater

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6711]
Hi, I am receiving following error while enabling openId Client module.

![image](https://user-images.githubusercontent.com/56805276/87850037-7498b700-c930-11ea-9945-7f914f37c854.png)

**Comment by deanmarcussen** [comment]
Can you check your versions and refer to this announcement regarding `OpenId` https://github.com/OrchardCMS/OrchardCore/issues/6608 to see if you have followed the correct procedure upgrading.

If still having an issue please post log files.

**Comment by khurram4u2** [comment]
Hi @deanmarcussen, I am just trying to enable the OpenId client feature not upgrading. As soon as I enable it my deployment crashes.

**Comment by deanmarcussen** [comment]
> If still having an issue please post log files.

Please specify the version you are using and post the exception details from your log files.

(Very hard to try and repro without further information)

**Comment by kevinchalet** [comment]
I suspect this commit broke it by no longer returning `null` for invalid settings and causing a null-ref in the `settings.ResponseType.Contains(..)` check: https://github.com/OrchardCMS/OrchardCore/commit/920d00265d5e5a07dc5330339e66a58ad6f6c261#diff-8c6ffad9a5ad70f3e670808033758924R105.

**Comment by kevinchalet** [comment]
Thanks for your report @khurram4u2.

I fixed this bug as part of https://github.com/OrchardCMS/OrchardCore/pull/6727. Let us know if it still throws an exception after updating your packages.
