### ISSUE TITLE
Use CacheManager

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#6713]
The reason are
1. One interface
2. Support many 
3. Mature

**Comment by sebastienros** [comment]
What is CacheManager ?

**Comment by infofromca** [comment]
http://cachemanager.michaco.net/

**Comment by jtkech** [comment]
See #5249, we plan to use a generic and configurable `IDocumentManager<TDocument>` for any type of single document that can be persisted or volatile (only in memory) and that needs to be kept in sync with a shared cache.

We use a multi level cache from a scoped cache, then a memory cache for each app instance, and at the last level an `IDistributedCache` whose default implementation is a `MemoryDistributedCache` that only uses an inner memory cache.

The multilevel cache allows to get isolated objects of the same document depending if you want to get it from the shared cache or load it from the store for updating, and by taking into account at one layer the knowledge we have on YesSql.

To keep data in sync we use a pattern that is good for Availability but not the best for Consistency, but we compensate this with an additional integrity checking using unique identifiers.

See #5815 where we have a configurable `OrchardCore.Redis.Cache` feature that registers an `IDistributedCache` with a concrete implementation based on `StackExchangeRedis`.
