### ISSUE TITLE
Smtp -> Email

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6714]
IMHO using `Email` instead of `Smtp` in Admin menu is better, because `Smtp` is more technical term

**Comment by sebastienros** [comment]
I am not opposed to it. Anyone has another opinion?

**Comment by vitalybrandes** [comment]
@sebastienros 
Please see print screen of mail settings from Joomla CMS
![image](https://user-images.githubusercontent.com/61165619/89765833-c41d6d80-daff-11ea-830f-abab85bbee39.png)

**Comment by sebastienros** [comment]
> because Smtp is more technical term

Wait until you open the "Email" page and see all these SMTP settings ;) even more complex than the title

**Comment by Skrypt** [comment]
I second that. It has more than just a SMTP setting in there.
