### ISSUE TITLE
Add user deleted event

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore#6719]
In `OrchardCore.Users.Handlers.IUserEventHandler` there is a `CreatedAsync` but no `DeletedAsync`.

It should be added with an empty interface default implementation to preserve compatibility. It should be invoked from `OrchardCore.Users.Services.UserStore` like its counterpart for created event.

**Comment by hishamco** [comment]
Perhaps it is missed

**Comment by DAud-IcI** [comment]
PR is up at #6719
