### ISSUE TITLE
Open Id - UserInfo recive only sub (Id) of user

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6722]
Did update to latest nugets, once done, the Claim for user info return only "sub" instead full profile

![image](https://user-images.githubusercontent.com/61165619/87915665-1debc400-ca7b-11ea-9e77-f02e28823aa0.png)

cc @kevinchalet

**Comment by kevinchalet** [comment]
Thanks for the report. I forgot to update the userinfo controller to use `HasScope()` (`HasClaim(Claims.Scope, "scope")` no longer works as the scopes are now formatted as a unique space-separated `scope` claim, as required by the JWT access tokens spec).
