### ISSUE TITLE
UX Improvement for new ContentItem

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6723]
### I think that "Cancel" or "Close" btn need to be added to Create New content.
Once user change his mind to open it, there is no "Right" way to go back.

![image](https://user-images.githubusercontent.com/61165619/87916264-e16c9800-ca7b-11ea-8c5f-bb4b7a979fc2.png)

**Comment by hishamco** [comment]
Perhaps we need to add a back or cancel button to return back to the content items list, @vitalybrandes could you please add a PR for that

**Comment by vitalybrandes** [comment]
I found now that while you editing exiting content item the btn exist

![image](https://user-images.githubusercontent.com/61165619/87927544-0b2dbb00-ca8c-11ea-9243-9adf9275feb0.png)

**Comment by hishamco** [comment]
It would be nice if you make a PR or I will do it then ;)

**Comment by vitalybrandes** [comment]
> It would be nice if you make a PR or I will do it then ;)

Emmm, I am not sure that I know how 😬

**Comment by hishamco** [comment]
No problem, I will take care about this

Thanks

**Comment by hishamco** [comment]
@agriffard why `Create` doesn't have `Models.Actions` or the cancel button should be added via display driver

**Comment by vitalybrandes** [comment]
@hishamco  following this issue,
See attached link to nice article regarding UI if cancel btn
https://medium.com/@uxmovement/why-cancel-buttons-should-never-have-a-color-6ce7e763d7f1

**Comment by hishamco** [comment]
Thanks @vitalybrandes, I'm still have a doubt about the current button's color, but this is a good article

**Comment by NogginBox** [comment]
@agriffard I was going to have a look at this, but on the latest dev it already seems to be implemented.

I started a new site, created a new content type and then used the new button to create a new content item of that type and there was a 'Cancel' button. Unless there is another way to create a content item that does not show the button?

**Comment by agriffard** [comment]
Thank you @NogginBox, may be solved by the changes that @Skrypt made recently about the ReturnUrl:
https://github.com/OrchardCMS/OrchardCore/commit/b59de402074dd44d807aeb64ebcad49770785c9f
