### ISSUE TITLE
Recommendation UX Improvement in Features sections / Admin

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6724]
Once user going thru the Feature list, select required components he need to goes up till the beginning to enable / disable them.
Recommendation to add btn at the end.

![image](https://user-images.githubusercontent.com/61165619/87918481-2cd47580-ca7f-11ea-861f-24bb3d140103.png)

**Comment by hishamco** [comment]
IMHO you can pick the features by selecting the their checkboxes then go to `Bulk Action` button, you can check GitHub notification for instance, if you have tens of notifications and you want to delete them, you should do the same

**Comment by vitalybrandes** [comment]
> 
> 
> IMHO you can pick the features by selecting the their checkboxes then go to `Bulk Action` button, you can check GitHub notification for instance, if you have tens of notifications and you want to delete them, you should do the same

Well,
I just go thue the all features, select the relevant for me and the  Bulk actions control at the end of page was missing , this was my flow..
then i required to go up to the top Bulk actions control

**Comment by sebastienros** [comment]
If something would be done, I'd suggest a "top" button to go back to the top. I don't think it's worth duplicating the button.
I am afraid we would then do it in more screens.

**Comment by hishamco** [comment]
This is what I come up with

![ScrollToTop](https://user-images.githubusercontent.com/3237266/89709086-67964300-d985-11ea-8d8c-870f3bbecb9f.gif)

**Comment by hishamco** [comment]
@jtkech why when I run `npm install` error shows up, even I delete a `node modules` folder, I stuck to run gulp tasks

**Comment by jtkech** [comment]
@hishamco last time i had some problems with gulp, as i remember i had to update node to the last version

**Comment by hishamco** [comment]
I updates the node same thing I face some issue during `gulp build`, could please list the command I should execute because I saw bunch of them listed when I run `npm run`
