### ISSUE TITLE
Allow management of recipe metadata in deployment plans

### ISSUE THREAD

**Issue by DannyT** [OrchardCMS/OrchardCore#6728]
We use deployment plans to keep project recipes updated. This typically involves taking 95% of the json output from the DP and pasting it into the existing recipe because by default all of the recipe metadata is blank.

It's a small thing but being able to manage the meta data on the deployment plan would be a nice way to allow us to more seamlessly update recipes within our projects.

**Comment by agriffard** [comment]
You can use the `RecipeFileDeploymentStep` to specify the metadata of the recipe that will be generated.

**Comment by DannyT** [comment]
> You can use the `RecipeFileDeploymentStep` to specify the metadata of the recipe that will be generated.

Ha, right, yes that's exactly what we were after. I should have checked first!
