### ISSUE TITLE
Login form as first page for the site

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6733]
Best practice to lock any unauthorized access to the all website pages?
Once user redirected to URL, login form will appear for authentication.

**Comment by deanmarcussen** [comment]
Generally I would just disable the `View all Content` permission for the `Anonymous` role

**Comment by vitalybrandes** [comment]
> 
> 
> Generally I would just disable the `View all Content` permission for the `Anonymous` role

Did it, SAME,
Maybe i am missing something in my custom theme?

**Comment by deanmarcussen** [comment]
> Did it, SAME,

Not sure what SAME means.

Can you explain further what is happening, and what you want to happen?

**Comment by vitalybrandes** [comment]
> 
> 
> > Did it, SAME,
> 
> Not sure what SAME means.
> 
> Can you explain further what is happening, and what you want to happen?

Ok, Sorry,
I removed the View All from anonymous, 

Now i am wondering, hot in best way to set all content of my my Index.CSHTML to be protected by Login .
Is any nicer way except "User.Identity.IsAuthenticated"

**Comment by sebastienros** [comment]
Remove the "View all Content" permission, and in your custom pages, check for this permission too.
