### ISSUE TITLE
OpenID Help

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6734]
Hi, I have an open ID server setup on an external application. I want it to authenticate the users. I have enabled the OpenID client feature and provide the required detail. However, I can not see the open to login from external provider.

Could you please guide me? 

Thanks.

**Comment by MichaelPetrinolis** [comment]
That would be a great getting started tutorial in the documentation. For now, I suggest you to enable the Registration module, and allow users to register with external provider. If you want only to be authenticated by the external provider, there is an option in the login settings I think. But you should provide the roles you want to assign to the users based on the claims you receive from your Idp.
