### ISSUE TITLE
What is "UserClaims":[], "LoginInfos":[], "UserTokens":[]

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6735]
What is "UserClaims":[], "LoginInfos":[], "UserTokens":[], in 
OrchardCore.Users.Models.User, OrchardCore.Users.Core

(From DB, Document)

**Comment by deanmarcussen** [comment]
See this pr for when UserTokens were added https://github.com/OrchardCMS/OrchardCore/pull/6057

The others are related to using external login providers, and the implementation of a user claims store

**Comment by vitalybrandes** [comment]
> 
> 
> See this pr for when UserTokens were added #6057
> 
> The others are related to using external login providers, and the implementation of a user claims store

Questions:
1.Why we don't save "last login date and time" in the LoginsInfo" for Orchard authentication?
2. Just to understand, if i am making signal R module (Desktop client to server), using this Tokens i can protect the connection instead generate new one?

**Comment by deanmarcussen** [comment]
> > See this pr for when UserTokens were added #6057
> > The others are related to using external login providers, and the implementation of a user claims store
> 
> Questions:
> 1.Why we don't save "last login date and time" in the LoginsInfo" for Orchard authentication?

That property is more related to external login providers, so probably not the place for that kind of information.

> 2. Just to understand, if i am making signal R module (Desktop client to server), using this Tokens i can protect the connection instead generate new one?

I believe (best to read the pr, it has a lot of notes on it) this is more related to external open id providers.

Can we close this issue? and pursue login related info on the other issue you have opened?

**Comment by vitalybrandes** [comment]
> 
> 
> > > See this pr for when UserTokens were added #6057
> > > The others are related to using external login providers, and the implementation of a user claims store
> > 
> > 
> > Questions:
> > 1.Why we don't save "last login date and time" in the LoginsInfo" for Orchard authentication?
> 
> That property is more related to external login providers, so probably not the place for that kind of information.
> 
> > 1. Just to understand, if i am making signal R module (Desktop client to server), using this Tokens i can protect the connection instead generate new one?
> 
> I believe (best to read the pr, it has a lot of notes on it) this is more related to external open id providers.
> 
> Can we close this issue? and pursue login related info on the other issue you have opened?

Yes, Thank you!
