### ISSUE TITLE
How do i Query 10 First / Last added users?

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6736]
How do i Query **10** First / Last added users?

 var _Users = await _session.Query<User, UserIndex>().ListAsync();

**Comment by deanmarcussen** [comment]
We don't track anywhere a created / modified date for users, so it would be database ordered.

Maybe we need too, can you describe the use case?

**Comment by vitalybrandes** [comment]
> 
> 
> We don't track anywhere a created / modified date for users, so it would be database ordered.
> 
> Maybe we need too, can you describe the use case?

I am creating some kind of dashboard where i would like to present 10 last created users
![image](https://user-images.githubusercontent.com/61165619/88147376-c463d080-cc05-11ea-96e0-149f5d0e4410.png)

**Comment by deanmarcussen** [comment]
Ok, so two questions came out of this.

1. why don't we track last login date  (ref https://github.com/OrchardCMS/OrchardCore/issues/6735#issuecomment-662294237)
    - This is probably performance related, as it would involve saving the user on every login.
    - There is a Workflow Event `UserLoggedInEvent` so you could implement something here

2. Created Date / Modified Date for users.
    - Not something we have out of the box, neither does ASP.NET Core Identity
    - There are also workflow handlers, and code base `IUserEventHandler` handlers which you can use to extend the user, but worth noting here that the user is committed to the database before they are fired so might be easier to do in code.

general note, an `IUser` is an `IEntity` which has a `Properties` making it extensible (see in the demo project for extending `IUser` with display drivers.)

@kevinchalet may have thoughts on whether a created / mod date is something we should have out of the box, or we can triage the question

**Comment by vitalybrandes** [comment]
> 
> 
> Ok, so two questions came out of this.
> 
>     1. why don't we track last login date  (ref [#6735 (comment)](https://github.com/OrchardCMS/OrchardCore/issues/6735#issuecomment-662294237))
>        
>        * This is probably performance related, as it would involve saving the user on every login.
If so why we do that for external logins?

>        * There is a Workflow Event `UserLoggedInEvent` so you could implement something here
> 
>     2. Created Date / Modified Date for users.
>        
>        * Not something we have out of the box, neither does ASP.NET Core Identity
>        * There are also workflow handlers, and code base `IUserEventHandler` handlers which you can use to extend the user, but worth noting here that the user is committed to the database before they are fired so might be easier to do in code.
> 
> 
> general note, an `IUser` is an `IEntity` which has a `Properties` making it extensible (see in the demo project for extending `IUser` with display drivers.)
> 
> @kevinchalet may have thoughts on whether a created / mod date is something we should have out of the box, or we can triage the question

@deanmarcussen  How can i query only 10 first users?

**Comment by hishamco** [comment]
What about using `Take(10)` LINQ operator to fetch the first 10 users based on their order in the users table

**Comment by vitalybrandes** [comment]
> 
> 
> What about using `Take(10)` LINQ operator to fetch the first 10 users based on their order in the users table

Only last question, why not to log last login for all users? 
Probably for blog this is irrelevant, but for different product...
if this affect performance, so can do it by checkbox , Yes/no.

**Comment by hishamco** [comment]
> Only last question, why not to log last login for all users?

Where should we log?!! could you please clarify what you mean in last paragraph

**Comment by vitalybrandes** [comment]
> 
> 
> > Only last question, why not to log last login for all users?
> 
> Where should we log?!! could you please clarify what you mean in last paragraph

Yes sure,
[ (ref #6735 (comment))](https://github.com/OrchardCMS/OrchardCore/issues/6735#issuecomment-662294237)
Original question:
What is "UserClaims":[], "LoginInfos":[], "UserTokens":[], in
OrchardCore.Users.Models.User, OrchardCore.Users.Core

**Comment by vitalybrandes** [comment]
@kevinchalet maybe you know what for is  UserTokens in user profile?
My issue:
We are adding signal r app as module to our solution,
This module will send notifications from desktop client to server and back.
My client authenticate with Open ID at login using password auth.
My problem is to protect signal r communication using same tokens?

**Comment by kevinchalet** [comment]
> @kevinchalet maybe you know what for is UserTokens in user profile?

This is a non-Orchard-specific ASP.NET Core Identity artifact that is typically used to store the access, identity and refresh tokens retrieved after an external authentication dance with an OAuth 2.0 or OIDC provider.
