### ISSUE TITLE
Permalink not generated automatically

### ISSUE THREAD

**Issue by Nowhk** [OrchardCMS/OrchardCore#6738]
When I save a Custom content, Permalink is not generated automatically:

![image](https://user-images.githubusercontent.com/19835752/88075027-853b6e00-cb78-11ea-9fa6-beac4f242981.png)
As well in the GraphiQL, the value of "path" is null.

What do I need to activate to generate permalink automatically?

**Comment by leone-91** [comment]
When you go to the Content type definition of your page, if you click on modify for the autoroute part, check if the model is this one: {{ ContentItem.DisplayText | slugify }}

**Comment by Nowhk** [comment]
Where is this "model"? Here's the screenshot:

![image](https://user-images.githubusercontent.com/19835752/88379857-e2ffce00-cda3-11ea-926d-542c5281764e.png)

**Comment by leone-91** [comment]
It is "Pattern", sorry for that mistake, my admin dashboard is configured in french! 
I think you just need to add: {{ ContentItem.DisplayText | slugify }} in that pattern input

**Comment by Nowhk** [comment]
I see, nice! Is it possible to enable this by default? Otherwise every time users need to remember this expression :O

**Comment by leone-91** [comment]
I am not sure but I think that in some themes it is enabled by default. Personnally I didn't have to add it manually

**Comment by deanmarcussen** [comment]
`{{ ContentItem.DisplayText | slugify }}` this should be the default setting when you add an `AutoroutePart` to a content type.

If it isn't doing that for you when you create content types, could you post some repro steps / or images of the settings for your content type that isn't doing that.

Also noting the default setting was added during RC1, so we should check your version as well, and make sure you're on RC2

**Comment by Nowhk** [comment]
I take it using dotnet new -i OrchardCore.ProjectTemplates::1.0.0-rc1-*
So probably that's the reason.
