### ISSUE TITLE
Script helper no longer registering script at Foot by default

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#6740]
The documentation says that scripts using the tag helper will render in the FootScript by default if no “at” is declared however I noticed instead scripts are being rendered in the head section by default.

Is the documentation wrong or the code wrong?

**Comment by scleaver** [comment]
Further testing on this reveals that actually it is just rendering the script wherever it is placed when it has no "at" declared rather than in the FootScript. Here is what I used to test - I threw this into the content.liquid file of the Agency Theme and the content.cshtml of the blank theme:

```
{% script src:"~/TheTheme/js/foo.min.js", debug_src:"~/TheTheme/js/foo.js" %}
```

```
<script asp-src="~/TheTheme/js/foo.min.js" debug-src="~/TheTheme/js/foo.js"></script>
```

**Comment by ns8482e** [comment]
@scleaver I guess it's intended behavior see below code.

https://github.com/OrchardCMS/OrchardCore/blob/e3c6488578e73dc14f160f8f46a213a8c47cc0ce/src/OrchardCore/OrchardCore.ResourceManagement/TagHelpers/ScriptTagHelper.cs#L138-L141


https://github.com/OrchardCMS/OrchardCore/blob/cb45b4ec37ecb663b06e8ca1f451f0e69c02747d/src/OrchardCore/OrchardCore.ResourceManagement/TagHelpers/ScriptTagHelper.cs#L186-L189

**Comment by sebastienros** [comment]
I also thought the default was the footer. But since there is an "Unspecified" enum, and the code seems on purpose, that looks like the way it should be documented. Didn't we file an issue recently to allow this feature too? Also we might want to check the history in case the behavior was changed for a reason. I think I wrote most of this, but I don't remember the details. Maybe also check the cshtml file in the demo project that contains lots of examples, if there is one like this. That would confirm its intent.

**Comment by scleaver** [comment]
Unspecified is the default of course when you don't put "at" - so a decision just needs to be made. Is the default behaviour of the SCRIPT tag helper to register in FootScript OR to not implement a default location and just change the documentation?

I will take a look at the historyl

@sebastienros - yes I created a different issue to have an Inline location allowing the style to register where the tag helper was placed. It's still being debated whether this should be added to OC or not.

**Comment by deanmarcussen** [comment]
Yeah, we just need to ping @TFleury because he last added features here, and I have a vague memory he might have needed `at` as a targeting element for the feature he added

**Comment by ns8482e** [comment]
@sebastienros @deanmarcussen It's available before @TFleury's change.

If you define script with only `<script asp-name="xyz">` or `<script asp-src="xyz">` then it renders at local

**Comment by TFleury** [comment]
> Yeah, we just need to ping @TFleury because he last added features here, and I have a vague memory he might have needed `at` as a targeting element for the feature he added

`at` attribute was added to `StyleTagHelper` just to activate the tag helper when there is no 'name' nor 'src' attribute defined. So, not related to this issue.

Looks like it's been like this for a while, I'm much more for a documentation update.

**Comment by ns8482e** [comment]
It added long time back - seems intended behavior - added in PR #2973

**Comment by scleaver** [comment]
I have closed the code changes PR and updated the documentation to reflect the decision here to have no default location for script tag helper.
