### ISSUE TITLE
correct alternates order in shape metadata

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#6744]
Hi,

I have a question about the order of alternates in the shape metadata. As I understand the last matching one in the array is the selected template. Does it make sense that [ContentType]\_\_[FieldType] is preferred over [ContentType]\_\_[PartName]\_\_[FieldName]? I think the first one is less specific than the second.

 I think I tracked it down to this code:
https://github.com/OrchardCMS/OrchardCore/blob/d22493e850f05eb87cd207f6c69a9c084beb9237/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentFieldDisplayDriver.cs#L80-L84

Are these two lines in the correct order?

thnx,
Arjan

**Comment by ns8482e** [comment]
@ArieGato IMHO both alternates are specific to `[ContentType]_[DisplayType]` hence one should create either one or other but not both as same time. 

i.e. If you customize Blog and add `CustomPart` Part having three `TextField `and you want to target all `TextField` in the Blog (**regardless of Parts** they are in based on `FieldType`) to render the same then you would use `Blog-TextField.liquid`.  However if you want to render all three `TextField` with different tags e.g. `h3`, `h4`, `h5` then you will create `Blog-CustomPart-Field1.liquid` `Blog-CustomPart-Field2.liquid`, `Blog-CustomPart-Field3.liquid` 

 I am curious to see what makes you create both kind of alternates?

**Comment by ArieGato** [comment]
Lets say I have a ContentPart containing 4 MediaFields. I want to create a template the same for all but one. Then I want to use [ContentType]\_\_[FieldType] for those. And for the single one I want to use [ContentType]\_\_[PartName]\_\_[FieldName] to differentiate. Now it's not possible. I think it's a shame to duplicate templates for this.
And when you alter the sequence of the two code lines you have full control.

**Comment by ns8482e** [comment]
@ArieGato May be you need DisplayMode

**Comment by ArieGato** [comment]
That could work as well.

But again imho it is not necessay to add these files when the sequence of alternates is changed. And I can't think of a reason why not to. Nothing will break. 

Alternates give a fine grained control of which template will be used. A sort of cascading mechanism where the most specific template should be used.

**Comment by ns8482e** [comment]
@ArieGato IMHO here idea of having `[ContentType]__[FieldType]` is to have common shape for **All** `FieldType` within your content type and current order of alternate seems ok as you choose one way or other. 

@deanmarcussen correct me if I am wrong -

If you really don't want **All**  then you should not use `[ContentType]__[FieldType]`. If you required **All but except** then differentiate with **DisplayMode**  is way to go 

i.e. for `Detail` you can define as `[ContentType]_Display__[FieldType]__[FieldType]__[DisplayMode]`

**Comment by ArieGato** [comment]
> IMHO here idea of having `[ContentType]__[FieldType]` is to have common shape for **All** `FieldType` within your content type and current order of alternate seems ok as you choose one way or other.

I'm not saying that this should work any other way. And it will still work that way when `[ContentType]__[PartName]__[FieldName]` is added after `[ContentType]__[FieldType]`. But when the sequence is changed you have an extra option of determining the template to use.

I think the same goes for the following example. Consider the folling two templates: `HtmlBodyPart__Description` and `Blog__HtmlBodyPart__Description`. If I follow your reasoning, when a template `HtmlBodyPart__Description` is present then the 
`Blog__HtmlBodyPart__Description` will never be used.

> Added advantage of `DisplayMode` is that it's configurable from Settings :)

How is this an advantage?

@ns8482e Let me ask you, why should we not change the sequence?

**Comment by ns8482e** [comment]
@ArieGato my personal opinion, orchard provides different ways to have alternates - however if driving force behind defining alternate is `FieldType` that i'd like to render the same for the content type regardless parts they are in then I'll use `[ContentType]__[FieldType]` and it should win as that's the intention of defining of such template as first place.

**Comment by ArieGato** [comment]
@ns8482e I disagree on that. My opinion is that they are not mutually exclusive. And that the template `[ContentType]__[PartName]__[FieldName]` better descibes the shape than `[ContentType]__[FieldType]`.

**Comment by ns8482e** [comment]
@ArieGato I understand your opinion - however current implementation is not working as you wanted to work and I guess that's how it designed to work.

> Lets say I have a ContentPart containing 4 MediaFields. I want to create a template the same for all but one. Then I want to use `[ContentType]__[FieldType]` for those. And for the single one I want to use `[ContentType]__[PartName]__[FieldName]` to ?differentiate. Now it's not possible.

However It's possible to define the alternate as you described - following are different ways to achieve the same- 

1. Use different DisplayMode for the image that you want to show differently.
1. Use `OnDisplaying`  event and  change the order  of alternates as per your need or the add new one - for the `MediaField` that needs special alternate. e.g.

```
builder.Describe("MediaField")
                .OnDisplaying(displaying =>
                {
                    IShape shape = displaying.Shape;
                    if( myspecialImageField )
                          shape.Metadata.Alternates.Add("Blog__MyPart__MyField__MySpecialMediaField")
                } 

```
3. Use placement to add custom alternate for the special `MediaField` .
```
"MediaField": [
        {
          "displayType": "Detail",
          "differentiator": "MyPart-MyField",
          "contentType": [ "Blog" ],
          "alternates": [ "Blog__MyPart__MyField__MySpecialMediaField" ],

        }
      ]
```

**Comment by ArieGato** [comment]
> however current implementation is not working as you wanted to work and I guess that's how it designed to work.

Wether it is or isn't designed this way is essentially my question. I think it is always good to question why something was done and if (in hindsight) it is still the best solution.

I still believe the sequence can be changed without breaking changes or loss of functionality. All will remain to work as it does right now. The worst case scenario is that someone has added a template in the past that was never going to be used anyway.

Of the three options my preference would go to option number 3 as it requires the least adjustments and can be done without any coding.

**Comment by ArieGato** [comment]
@ns8482e @deanmarcussen Is anyone going to decide wether it is an improvement to change the sequence? I think both sides have produced some good arguments.

**Comment by deanmarcussen** [comment]
@ArieGato Needs Triage

**Comment by jtkech** [comment]
All are good comments but for me `{contentType}{displayType}__{partType}__{fieldName}` is more specialized than `{contentType}{displayType}__{fieldType}`, so i would vote to place it after

Similarly line 120 `{contentType}{displayType}__{partName}__{fieldName}__{shapeType}` is more specialized than `{contentType}{displayType}__{fieldType}__{shapeType}`

**Comment by ArieGato** [comment]
@jtkech So should I make a PR for the change?

**Comment by jtkech** [comment]
@ArieGato It's just my opinion after a quick look but yes feel free to suggest it through a PR
