### ISSUE TITLE
Feature Request: Alternative Text for Markdown Images

### ISSUE THREAD

**Issue by FelixStumvoll** [OrchardCMS/OrchardCore#6745]
Since it is not possible to set an alternative text for an image it would be nice, to add one to the image, when you insert it into a markdown field

**Comment by deanmarcussen** [comment]
This one we can do :)

It could be an argument on the shortcode if you would like to add it as a pr?

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Media/Shortcodes/ImageShortcodeProvider.cs

**Comment by agriffard** [comment]
Closed by #6838
