### ISSUE TITLE
trumbowyg editor ICON doesn't show

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6746]
Hi guys, I having problem with trumbowyg editor it is not showing the icons as they are not loading in page see the following image. 

![image](https://user-images.githubusercontent.com/56805276/88165058-6f04df00-cc58-11ea-802a-3e9134511e8b.png)

Could you please advise?

**Comment by agriffard** [comment]
Do you have a client side error?

**Comment by khurram4u2** [comment]
Here is there error.

![image](https://user-images.githubusercontent.com/56805276/88168763-3831c780-cc5e-11ea-9d7e-e3f1367e4401.png)

**Comment by khurram4u2** [comment]
@agriffard Issue has been fixed. Thanks for your help. I have postfix (/content) which was causing issue.
