### ISSUE TITLE
Update ContentItem without making it Draft

### ISSUE THREAD

**Issue by randaratceridian** [OrchardCMS/OrchardCore#6749]
I know this may seem like an odd request, but is there a way to update a ContentItem without it going into a Draft status?

To keep things in a single location, we added a number of properties to ContentItems. Many of these are hidden MetaData and only accessed via code. But when they are published, we would like to update them without Orchard Core creating a new draft version.

One option seems to be to manipulate the JSON directly in the DB, but that feels wrong as well.

Any suggestions?

Here is an example of the ContentItem JSON. We would like to update the items under HubPage, without creating a Draft.

`
{
  "ContentItemId": "401abanvbsgmntx5ppp10jbad3",
  "ContentItemVersionId": "4a454hvjwqs322ygcrtqz862n6",
  "ContentType": "HubPage",
  "DisplayText": "Company Hub",
  "Latest": false,
  "Published": false,
  "ModifiedUtc": "2020-06-10T21:06:03.7406479Z",
  "PublishedUtc": "2020-06-10T21:06:03.7700208Z",
  "CreatedUtc": "2020-06-09T21:45:36.9771639Z",
  "Owner": "u1591649151",
  "Author": "u1591649151",
  "HubPage": {
    "Description": null,
    "AppearanceId": 2
  }
,
`

**Comment by sebastienros** [comment]
There should be a checkbox to uncheck in the type definition, to disable Versioning.

**Comment by dannoh** [comment]
@sebastienros Sorry for posting on a closed issue, but to clarify.  We would like the ContentItem to be Versionable, but only if they for example change the Name property, but not if they change the Description property.

If they change Description on a published item, it should stay published.  Possible?
