### ISSUE TITLE
Deleteing a content-type that is inuse causes an exception

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#6751]
When creating a content-type "i,e. Widget", then adding it to a Widget. Then deleting the content-type, the system throws an exception, and is hard to use the GUI to recover from it.

**Solution:** prior to performing the "delete" operation content-type or content-part, check that it isn't being used. If it is used, you might want to throw an alert to the user and prevent the delete.

**Comment by hishamco** [comment]
Showing a warning alert may good for this case, @CrestApps would you like to push a PR for this?

**Comment by CrestApps** [comment]
I could mess with it. But it won't be any time soon.

**Comment by hishamco** [comment]
Which version you are using? I just deleted an Article content type successfully

**Comment by KaloyanIT** [comment]
I'm interested in contributing. Could you provide a little more detail on exactly what should be accomplished to resolve this issue?

**Comment by hishamco** [comment]
Glad to hear that @KaloyanIT!! the idea basically to avoid deleting the content type who has already some content items, unless we show a warning alert or confirm message telling that the current content type has associated content types. @CrestApps still waiting for you

**Comment by sebastienros** [comment]
Will be hard for types that are contained (widgets, bag part content items, menu items...)

I assume we should just log the issue, and ignore the content items without throwing exceptions.

**Comment by deanmarcussen** [comment]
Related https://github.com/OrchardCMS/OrchardCore/issues/1014
