### ISSUE TITLE
Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll'

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#6752]
When running the OrchardCore.Mvc.Web sample project there is an error:

An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery

**Comment by agriffard** [comment]
Closed by #6752?
