### ISSUE TITLE
Content Type User Experience should be improved

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6758]
There are few places that we need to change to improve the UX for the content types including:

- Ability to delete the content types directly from Content Types List

- Avoid to delete a content type if there's an associated content items, because this is harmful, unless the intend is delete everything related. Very detailed confirm message may suitable in this case

I will keep this list for others to add any suggestion that may improve the UX

**Comment by agriffard** [comment]
Can be related to #6751, #6300, #5669

**Comment by hishamco** [comment]
Seems the issues that you referred to are duplicates, this includes the deletion issue plus the ability to add a deletion feature on content types page, you can close the duplicates and keep one for tracking
