### ISSUE TITLE
Write guide explaining the file content definition feature

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6760]
> disable the file content definition feature and it will revert to the database. (export it first, as the database copy will be blank, and then reimport it)

Small guide to explain what the file content definition feature is, and how to disable it and use the database when in production

**Comment by ns8482e** [comment]
@deanmarcussen IMHO moving from file store to database store or vise versa should be seamless.

**Comment by jtkech** [comment]
For infos, at least we have a config option to migrate automatically from file to database

**Comment by deanmarcussen** [comment]
@ns8482e make it so!

but I'm wary of it being automatic, because of potential conflicts when both database and file have data, so either with config as @jtkech but definitely only if the destination (i.e. database record), is empty

Regardless we need a guide to explain what it does, I'm bored of explaining on gitter
