### ISSUE TITLE
issues with markdown field html sanitation

### ISSUE THREAD

**Issue by FelixStumvoll** [OrchardCMS/OrchardCore#6761]
im not quire sure if the _Sanitize Html_ option in the Markdown field is not working correctly or if my assumption of its functionality is wrong.

when i input this text `<u>i am underlined</u>` into a markdown field with disabled html sanitation i would assume the u-tag will be kept in the final html. however it escapes it to `&lt;u&gt;i am underlined&lt;/u&gt;` (when i fetch the html via the graphql api).

is this behavior intended or is it a bug?

**Comment by deanmarcussen** [comment]
I've added some overdue documentation here https://github.com/OrchardCMS/OrchardCore/pull/6763

In this case you need to configure the markdown pipeline (see docs pr for example)
