### ISSUE TITLE
Incorrect warning shown when deleting roles

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6765]
Repro:

Create site, with admin user

Try to delete `Moderator` role (with no users assigned to this role)

Warning shown that this role is associated with users.
![Screenshot 2020-07-24 at 10 01 36](https://user-images.githubusercontent.com/13782679/88376186-d162fa00-cd94-11ea-8ce0-f113c7d1bb3e.png)

@hishamco you added this feature I think? It doesn't seem to be working right

**Comment by hishamco** [comment]
I think I added this, I just assign it to me, I will take care about this

Thanks

**Comment by hishamco** [comment]
I was totally wrong when I used `GetRoleClaimsAsync()`, @deanmarcussen is there better way instead of have a dependency on Users?

**Comment by deanmarcussen** [comment]
I would imagine you need to use `UserByRoleNameIndex` which is in `User.Core` but I would not want to create that dependency, or make the query every time the role list is displayed.

Perhaps instead make it a server side validation and call `GetUsersInRoleAsync` from the user store instead.

**Comment by hishamco** [comment]
> but I would not want to create that dependency, or make the query every time the role list is displayed.

Me too ;)

> Perhaps instead make it a server side validation and call GetUsersInRoleAsync from the user store instead.

Let me think about it

**Comment by hishamco** [comment]
What if we create a new index to count users per role? This will avoid the dependency and will not retrieve much data, then we can use the `UsersCount` as a part of `RoleDocument`

**Comment by sebastienros** [comment]
Remove the UI notification altogether

**Comment by hishamco** [comment]
We can change the message, but we should think about such cases where there's a dependency such as ContentTypes with Content Items ... etc.

**Comment by hishamco** [comment]
I just made a PR to revert the role deletion message, let us think later for appropriate solution to fix the message if there are a users belong to the deleted role
