### ISSUE TITLE
Can I remove jqueryui because bootstrap is already used in the project

### ISSUE THREAD

**Issue by justlucky** [OrchardCMS/OrchardCore#6771]
Can I remove jqueryui because bootstrap is already used in the project

**Comment by hishamco** [comment]
Which project do you mean?

**Comment by ns8482e** [comment]
@justlucky `TheAdmin` theme and out-of-the-box modules uses multiple frameworks like - bootstrap, jquery, jqueryui, vuejs and others - these resources are defined in `Resources`  module.

However, for your themes and modules - you are not required to uses these resources - you can use your choice of frameworks and version, by defining your resources in `ResourceManifest` .
