### ISSUE TITLE
Deployment plans should be unique by name

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6774]
Deployment Plans are keyed by name as the unique identifier by the recipe step (and other places), however duplicate names are creatable in the UI.

The UI should prevent adding plans / keys with the same name.

The `CreateOrUpdateDeploymentPlans` in the `DeploymentPlanService` just acts as `Create` and should also handle `Update`

Currently creating a deployment plan recipe, and running it multiple times, will result in multiple deployment plans with the same key, rather than any update to plans that exist.

Alternatively we would have to introduce a GUID ID instead of using name, and update code to handle that (probably migration free)

/cc @agriffard

**Comment by hishamco** [comment]
Can we use `IdGenerator` with `dp` prefix?
