### ISSUE TITLE
Slow page load and browser blocking in Admin caused by font-awesome in Media picker field

### ISSUE THREAD

**Issue by asimeonov** [OrchardCMS/OrchardCore#6775]
Hi Orchard team. 

I found a poor behavior related to fas svg icons generation from all.js file. It kills the browser from promises when there are large number of folders (I have 600) in Media picker. https://stackoverflow.com/questions/55164958/font-awesome-performance give me a hint where the issue may be. 

[**solution / workaround**] I was able to work around it as suggested in the article above by changing from JS to CSS in the 'Admin' theme replacing the usage of font-awesome in Layout.cshml. This seems like a workaround to me and I have no idea is this the optimal solution.

Can you suggest a better approach or a way to handle this really slow load time of JS in case that there are multiple folders under Media folder?

Cheers,
Hacko

**Comment by sebastienros** [comment]
@agriffard is it back>

**Comment by deanmarcussen** [comment]
It might help to test this if you could provide a repro zip with something one of us can pop into a media gallery to see the issue.

Also which version of OC?

**Comment by asimeonov** [comment]
deanmarcussen I can create a console app for you if you like but it is quite simple to make for and to create 300 folders with random names in the "Media" folder. After this every content type that contains Media Field in it after opening will cause the browser to notify you that there is an script that is killing it. Here is the output of firefox 79.0 on windows 10

```Script terminated by timeout at:
_objectSpread@https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/js/all.js:2028:71
makeInlineSvgAbstract@https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/js/all.js:2920:19
generateSvgReplacementMutation/</<@https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/js/all.js:3816:24```
