### ISSUE TITLE
Security Critical Permission badge is missing

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6776]
@agriffard if I'm not wrong there was a badge for a `Security Critical` permission in the feature, but now there's no indicator for that, is there something change? Or it's deleted accidentally

**Comment by agriffard** [comment]
![image](https://user-images.githubusercontent.com/703248/88480668-85ac7e00-cf57-11ea-8b71-272517b480f7.png)

**Comment by hishamco** [comment]
I see, I thought it was show up on the enable / disable features

Thanks

**Comment by hishamco** [comment]
Is this include custom modules and features?
