### ISSUE TITLE
Mixed content with OpenID, authorize endpoint in an iframe

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/OrchardCore#6777]
Hi, 

I'm experiencing an issue where the authorization code flow is failing due to mixed content (everything is https), but when doing the handshake it looks like its using http in the process.  I have an embedded iframe that contains a tableau embed from tableau server and all configurated to use open id.  It all works outside of the iframe but not inside.

```
Mixed Content: The page at 'https://xxx' was loaded over HTTPS, but requested an insecure frame 'http://xxx/connect/authorize?request_id=z5J80VNBZydbmffOmkMuxFprXbgR_QJlietXGykrs2k'. This request has been blocked; the content must be served over HTTPS.
```

All references are using https paths and endpoints.  But I've noticed that the location response header is using http:

```
http://xxx/connect/authorize?request_id=kNe-t7JQa95dR_jJ359q7VGQYI5nHTnPJZXiWfhiY44
```

Any suggestions on whats going on?

Thanks

Steve

**Comment by sebastienros** [comment]
@kevinchalet  could it be a header generated by openiddict?

**Comment by kevinchalet** [comment]
It is, but OpenIddict simply uses `HttpRequest.Scheme` to build an absolute URL as part of its request caching feature. If an incorrect URL is generated, this means your app is not correctly configured to resolve the scheme (which typically happens when a proxy does TLS termination). Take a look at the ASP.NET Core docs to see how to fix that.

**Comment by stevetayloruk** [comment]
Maybe its based on the configuration....

SSL provided by cloudflare and is confgured in "strict mode".  All requests are also forced to SSL.

Azure web app using CurrentUser > My as settings for cert in OC. (set fo both signing cert)

I've just cloned the latest dev branch and noticed that there is now settings for encryption certificate (wasnt an option before in RC2 release), I've set these to the same: CurrentUser > My --- but not sure what this is referring to.

All traffic is https and all url references are https. 

Thanks

Steve

**Comment by kevinchalet** [comment]
> I've just cloned the latest dev branch and noticed that there is now settings for encryption certificate (wasnt an option before in RC2 release), I've set these to the same: CurrentUser > My --- but not sure what this is referring to.

Nope, it's completely unrelated. You're facing a very general issue that is not specific to Orchard nor to its OpenID module: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

**Comment by stevetayloruk** [comment]
Thanks @kevinchalet & @sebastienros.  

Added in the header forwards and all is working now. 

Thank You!

**Comment by kevinchalet** [comment]
@stevetayloruk you're welcome 👍
