### ISSUE TITLE
WebDeploy always push local App_Data

### ISSUE THREAD

**Issue by Nowhk** [OrchardCMS/OrchardCore#6779]
I've a problem with Publish the CMS on the server.
Every time it deploy also the local App_Data on the server, removing all the server setup I've.

I noticed that the folder App_Data is not present in the project when I:

`dotnet new -i OrchardCore.ProjectTemplates::1.0.0-rc1-*`
`dotnet new occms -o cms`

This I think will ignore  pubxml and csporj settings, so it publish it every time.
How can I fix it?

**Comment by jtkech** [comment]
You would need to update to rc2, see #6431

**Comment by Nowhk** [comment]
Thanks.
