### ISSUE TITLE
not contains

### ISSUE THREAD

**Issue by pchoisnard** [OrchardCMS/OrchardCore#6781]
HI.
I try this methods, it's work 

_orchardHelper.QueryContentItemsAsync(query => query.Where(x => x.ContentType.Contains("gg"))).Result.ToList();

The same with a ! not work with an exception.
_orchardHelper.QueryContentItemsAsync(query => query.Where(x => !x.ContentType.Contains("gg"))).Result.ToList();

I have miss something to make a not contains request ?

**Comment by jtkech** [comment]
Yes, YesSql is doing method mappings to build an sql query in a given dialect where you can't use the `!` operator.

One solution is to use the content definition manager to first filter the existing types (that are cached), and then use the `IsIn()` or `IsNotIn()` extension. I tried the following in a razor view.

    @using OrchardCore.ContentManagement.Metadata
    @using YesSql.Services;
    @inject IContentDefinitionManager ContentDefinitionManager

    @{ 
        var types = ContentDefinitionManager.ListTypeDefinitions()
            .Where(x => !x.Name.Contains("icle"))
            .Select(x => x.Name).ToArray();

        var test = (await Orchard.QueryContentItemsAsync(query => query
            .Where(x => x.ContentType.IsIn(types)))).ToList();
    }

**Comment by pchoisnard** [comment]
Thank you for your reply.

It works if we have a list of predefined values. 

But if we want to do a search as not like '% xxx%' on a text field in an index table which can contain any value ?

**Comment by jtkech** [comment]
Yes i understand but i'm afraid that we can't do such `not like`, you may have to change your strategy to categorize items.

Maybe by using Taxonomies / terms the expert being @deanmarcussen 

Or by using Lucene indexing the expert being @Skrypt

**Comment by sebastienros** [comment]
Should be possible to add it in yessql

**Comment by jtkech** [comment]
Cool

**Comment by pchoisnard** [comment]
thank you
it might be a good idea

**Comment by sebastienros** [comment]
Not for myself:
add IsLike("foo%bar"), IsNotLike
Maybe too hard to detect the `!` before Contains. Or maybe add a `NotContains` if it doesn't work.

**Comment by sebastienros** [comment]
IsList, IsNotLike and NotContains are available in yessql

**Comment by Piedone** [comment]
So, we have this now, then.
