### ISSUE TITLE
How to format Lucene search in Razor page

### ISSUE THREAD

**Issue by daene17** [OrchardCMS/OrchardCore#6782]
Hello, I am trying to use the Lucene search function to query content which is working fine. 
![image](https://user-images.githubusercontent.com/8889105/88729692-5594e480-d0e9-11ea-87ab-7344f5ba6c1a.png)

But I want to format the page so its not just plain. 

I see they have a solution on how to do that for .liquid pages in the documentation. 

But I was wondering how this would be possible with a razor page (C#). 

So I took the following example: 
![image](https://user-images.githubusercontent.com/8889105/88729997-ee2b6480-d0e9-11ea-83f3-00a1e6e002cd.png)

And tried to convert the syntax to be in line with razor pages:
![image](https://user-images.githubusercontent.com/8889105/88730686-88d87300-d0eb-11ea-92a8-62a084fb00f8.png)

Also in the documentation it says to create a file at **/Views/SearchResults.liquid or .cshtml** 

But our file structure is different, so would I put it in Pages/Shared/ and just create a razor page called SearchResults.cshtml and that will be the new search? 

Sorry if my question is confusing I am pretty new to orchard, please ask for any clarification if I made no sense. 

Also if there is a better alternative to using the Lucene thing let me know as well. 
Thanks

**Comment by sebastienros** [comment]
You create a Razor Page (@page) instead of a Razor View/Template. That might explain your issue.
Put the file in the Views folder too.

**Comment by daene17** [comment]
@sebastienros thanks for the reply! I have another question though, if you don't mind

I created it here since we don't use a Views folder: 
![image](https://user-images.githubusercontent.com/8889105/89584790-81068600-d7f1-11ea-89d2-676501dd3281.png)

So how do I make sure the changes actually effect the built in /Search page (from above) do I just put @page "/Search" at the top? I am not familiar with Razor views at all sorry.

**Comment by deanmarcussen** [comment]
You need to place it in a `Views` folder. You will need to make one.

And you need to remove `@page`

You could also just copy the view from https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Lucene/Views/Search-Results.cshtml 

to get started as it is the view you are overriding.

Also just updated the docs to have the correct name for the shape

**Comment by daene17** [comment]
@deanmarcussen Where is SearchResultsViewModel coming from? I looked in ViewModel folder and couldn't see anything with that name?
