### ISSUE TITLE
Ability to add an admin template for a dynamic part

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/OrchardCore#6784]
With the admin template feature, it appears that it is not possible to create a template for a dynamic part (a part created via the UI). It appears that there is no shape name to target, but it is possible I am missing something. Currently seeing this with RC2.

**Comment by deanmarcussen** [comment]
Yes, that is correct.
We render a dynamic part template on `BuildDisplayAsync` (special as it has some alternates)

`BuildEditorAsync` just uses `ContentPart_Edit` to group all the shapes for each part together (no alternates)

You could add an alternate in with an `IShapeTableProvider`, but ultimately it's just going to render the parts and fields that are contained inside it.

So depends on what you are wanting to achieve?

**Comment by ns8482e** [comment]
Edit experience is controlled by editor shape, so there won’t be any benefit adding alternates for edit

**Comment by douwinga** [comment]
Ya, already tried adding an alternate for `ContentPart_Edit` with an `IShapeTableProvider` and as @ns8482e  pointed out it does not work.

Just trying to have a template for a named part with a bunch of fields on it multiple times on the same content type and have it styled a specific way.

**Comment by deanmarcussen** [comment]
I don't know why adding an alternate would not work - works fine for me, as I do alternate the `ContentPart_Edit` occasionally - mostly to get rid of the named part descriptions when I've moved the parts contents into a tab.

```
            builder.Describe("ContentPart_Edit")
                .OnDisplaying(displaying => 
                {
                    dynamic shape = displaying.Shape;
                    if (shape.ContentTypePartDefinition != null)
                    {
                        string contentPartName = shape.ContentTypePartDefinition.Name;
                        displaying.Shape.Metadata.Alternates.Add($"ContentPart_Edit__{contentPartName}");
                    }
                }); 
```

But it depends what kind of styling you are trying to achieve, as @ns8482e says it is just a holder for the field editors.

**Comment by ns8482e** [comment]
Yes, as @deanmarcussen suggested you can add alternates to `ContentPart_Edit`. But IMO - the editor is driven by Editor shape - and  `ContentPart_Edit` is simply rendering all `Fields` without any `html` rendering - so technically there no benefit adding alternate to  `ContentPart_Edit` - so it's better to provide custom editor shape for the filed that you want to render differently for the part.

You can also use placement to target different zone.

**Comment by ns8482e** [comment]
@douwinga if you are looking for only to change `widget` editing experience in `Flow` 
you could use  `ContentCard_Frame` template to customize shape.

Here are some example that might help you - https://github.com/OrchardCMS/OrchardCore/pull/4470#issuecomment-540891941

**Comment by douwinga** [comment]
@deanmarcussen that is essentially what I was doing and then having the `ContentPart_Edit__{contentPartName}` be an admin template. Not sure why I couldn't make it work.

By styling I really mean layout. Being able to create something like this like we did in O1 where we can have a bootstrap row and fields in columns. You could then just add the part and it will always be laid out the same way.
![image](https://user-images.githubusercontent.com/11961383/88822301-ac55f900-d191-11ea-9751-20beb28462a1.png)

It is a bit of an edge case as for this project we are not using Orchard as a CMS for a website, but more for case management where most work is done in edit content item views. So having nicely laid out and styled edit views is important.

**Comment by deanmarcussen** [comment]
yeah I wondered if you meant layout @douwinga 

So I've had a similar need, and have done a couple of things around it recently (so depends on your version here)

Implemented some placement rules for tabs/cards/columns - bootstrap ones
and tweaked something last week so placement is applied to dynamic content parts

Docs on cards & cols are here https://docs.orchardcore.net/en/dev/docs/reference/core/Placement/#editor-shape-placement

Can be a little tricky to setup, but once you get into the swing of it seems to work ok, and is covering what I need (which looks pretty similar to what you are wanting)

Surprisingly I thought I really needed the columns, but actually just being able to split out into cards for various things, and collapse them down, has worked better in a lot of cases.

I didn't include it in the pr, because it's a bit unique, but its easy enough to replace the card grouping shape and run it as an accordion

**Comment by ns8482e** [comment]
`Content_Edit` provides alternate out of the box for ContentType like `Content_Edit__ContentType`. May be you can use that in  AdminTemplate

**Comment by sebastienros** [comment]
Ok to add part alternates with the part name and also the type name
