### ISSUE TITLE
Question: Custom Content Item Type Layout in the Admin Section

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#6785]
Hello,

I would like to have the Hint for one of the fields in a Content Item Type be populated dynamically (e.g. show a list of available tokens that are stored in a database). Is there a way I can customize the layout for the form in the Admin section for that specific Content Item Type?

**Comment by sebastienros** [comment]
You can create a custom template if you have a custom admin theme. Find the existing template file, and change it in your admin theme.

**Comment by sebastienros** [comment]
Note that's something that almost nobody does.
