### ISSUE TITLE
Search Results Not Displayed in Correct Order

### ISSUE THREAD

**Issue by thomasebsmith** [OrchardCMS/OrchardCore#6791]
When search results are displayed, they are often in the wrong order.

I have reproduced this issue on version 1.0.0-rc2-13968 and on the dev branch at edc370705709a7ee94c2940fb17859701afb1b75.

### Reproducing
1. Create a new Orchard Core CMS site.
2. Start the site, and initialize it with the blog recipe.
3. Go to the admin backend, and create two new articles: one with the title "Matches Worse" and one with the title "Matches Better". Make sure you create "Matches Worse" before creating "Matches Better".
4. Go to /Search, and search for "Matches Better".
5. The article called "Matches Worse" will be listed first, even though the "Matches Better" article is a better match.

### Screenshots
![bad-search-results](https://user-images.githubusercontent.com/42979377/88967899-faf0b980-d29d-11ea-9c2b-671528ac4252.png)

### Possible Causes
I think this is caused by the lack of ordering in OrchardCore.Lucene's [SearchController](https://github.com/OrchardCMS/OrchardCore/blob/acee23ef121a09568198ebda164d591ae9f084ed/src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/SearchController.cs#L140). Since there is no OrderBy clause in the `queryDb` query, `containedItems` is likely to be in a different order than the correctly ordered `contentItemIds`.

**Comment by hishamco** [comment]
@thomasebsmith can you send a PR for it?
