### ISSUE TITLE
Upload assests to wwwroot of tenant

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6793]
Hi, I have created a multi tenant cms. I want each tenant to upload the assests in "wwwroot" folder using media library. By default it is linked with Media folder. How can I allow clients to upload assests like custom css files or font in wwwroot folder.

Regards.

**Comment by hishamco** [comment]
The media folder is configurable, please checkout [MediaOptionsConfiguration](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Media/Services/MediaOptionsConfiguration.cs)

**Comment by khurram4u2** [comment]
@hishamco thanks got it. I used appsetting.json.
