### ISSUE TITLE
HtmlField is showing 2 textarea standard and Wysiwyg 

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#6799]
I create a part called `FancyPagePart`  class like this

```
public class FancyPagePart : ContentPart
{
    public string Headline { get; set; }
    public string SecondaryHeadline { get; set; }
    public bool ShowSummary { get; set; }
}
```

Then using a migration I create `FancyPagePart` part and `FancyPage` type like so
```
public int Create()
{
    // Fancy Page Part
    _contentDefinitionManager.AlterPartDefinition(nameof(FancyPagePart), part =>
    {
        part.Attachable()
            .WithField("Summary", field =>
            {
                field.OfType("HtmlField")
                .WithEditor("Wysiwyg")
                .WithDescription("Summary")
                .WithDisplayName("Summary");
            })
            .WithField("Details", field =>
            {
                field.OfType("HtmlField")
                .WithEditor("Wysiwyg")
                .WithDescription("Details")
                .WithDisplayName("Details");
            });
    });

    _contentDefinitionManager.AlterTypeDefinition("FancyPage", type =>
    {
        type.Creatable(true)
            .Listable(true)
            .Versionable(true)
            .Securable(true)
            .Draftable(true)
            .WithPart("TitlePart")
            .WithPart(nameof(FancyPagePart))
            .WithPart("SearchForm", "FlowPart")
            .WithPart("SortForm", "FlowPart");
    });

    return 1;
}
```

When I create a new content-item of "FancyPage" type, the editor shows 2 separate fields called "Details". A standard `textarea` editor and another `textarea` with `Wysiwyg` editor.

The generated html show the input name `FancyPagePart.Summary.Html` for the Wysiwyg editor whereas `FancyPagePart.Summary` for the standard editor

![Screenshot_4](https://user-images.githubusercontent.com/24724371/89080535-03003600-d33e-11ea-838b-68ce6acea6a4.png)
![Screenshot_5](https://user-images.githubusercontent.com/24724371/89080537-04316300-d33e-11ea-871d-30257a6b6c92.png)

If needed here is my `FancyPagePartDrive`

```
public class FancyPagePartDriver : ContentPartDisplayDriver<FancyPagePart>
{
    public override IDisplayResult Display(FancyPagePart part, BuildPartDisplayContext context)
    {

        return Initialize<FancyPagePartViewModel>(nameof(FancyPagePart), vm =>
        {
            vm.Headline = part.Headline;
            vm.SecondaryHeadline = part.SecondaryHeadline;
            vm.ShowSummary = part.ShowSummary;
        }).Location("Content:1");
    }

    public override IDisplayResult Edit(FancyPagePart part)
    {
        return Initialize<FancyPagePartViewModel>($"{nameof(FancyPagePart)}_Edit", vm =>
        {
            vm.Headline = part.Headline;
            vm.SecondaryHeadline = part.SecondaryHeadline;
            vm.ShowSummary = part.ShowSummary;
        });
    }

    public async override Task<IDisplayResult> UpdateAsync(FancyPagePart part, IUpdateModel updater)
    {
        var viewModel = new FancyPagePartViewModel();

        if (await updater.TryUpdateModelAsync(viewModel, Prefix))
        {
            part.Headline = viewModel.Headline;
            part.SecondaryHeadline = viewModel.SecondaryHeadline;
            part.ShowSummary = viewModel.ShowSummary;
        }

        return Edit(part);
    }
}
```

**Comment by deanmarcussen** [comment]
Have a look to the type definition in the admin area, and see if you haven't run this migration on an existing content definition record and created the fields twice. 

Otherwise please try from a fresh install and post the type definition from your `ContentDefinition.json` file. 

Somehow you appear to have ended up with two definitions for the same field name, but the code looks ok, so I suspect you've run it twice

**Comment by CrestApps** [comment]
@deanmarcussen I am not sure where should I look to know if the migration ran twice or now. Here is a screenshot from the admin panel


![FancyPage Type](https://user-images.githubusercontent.com/24724371/89133357-0cb9a300-d4d0-11ea-8ebc-891e5ddefc56.png)
![FancyPagePart](https://user-images.githubusercontent.com/24724371/89133358-0dead000-d4d0-11ea-99f0-8b24f144a21b.png)

**Comment by CrestApps** [comment]
It turns out that I was using the wrong view to render my view model which is the reason I was seeing the extra fields. 
Sorry my mistake.
