### ISSUE TITLE
Is it possible to set "readonly" or "disabled" by placement file?

### ISSUE THREAD

**Issue by staymo** [OrchardCMS/OrchardCore#6807]
This should be doable with Placement. Such that shapes would not be rendered based on the current roles.

_Originally posted by @sebastienros in https://github.com/OrchardCMS/OrchardCore/issues/1211#issuecomment-345054193_

**Comment by ns8482e** [comment]
@staymo You can change the shape type by specifying `shape` in placement

**Comment by staymo** [comment]
Thank you.
I tried to set the shape as "TextField" in placement.json:
{
  "TextField_Edit": [
    {
      "inRoles": "Student",  //A matcher I just implemented
      "displayType": "Edit",
      "differentiator": "Profile-RealName",
      "contentType": [ "Profile" ],
      "shape": "TextField"
    }
  ]
}


But I got this exception:
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Castle.Proxies.EditTextFieldViewModelProxy', but this ViewDataDictionary instance requires a model item of type 'OrchardCore.ContentFields.ViewModels.DisplayTextFieldViewModel'.

Which threw at:
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(object value)

Any solution?

**Comment by ns8482e** [comment]
Display shape and edit shape have different view model in this case. With placement, You can change the shape type however the model will still be for Edit.

Suggested to create your own shape type `TextField_Readonly` That render html from edit model instead of using `TextField` shape

**Comment by staymo** [comment]
Yes, it works! Thanks.
