### ISSUE TITLE
Changing svgpath for Trumbowyg

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6808]
Hi Guys, in following two files you have set the svg path to 

$.trumbowyg.svgPath = '/OrchardCore.Resources/Styles/ui/icons.svg'; can it be change to 
$.trumbowyg.svgPath = '~/OrchardCore.Resources/Styles/ui/icons.svg';

as I have set URL prefix to Content which causing issue to load svg file for trumbowyg. it gives error rescource not found.

it has been used in

HtmlBodyPart-Trumbowyg.Edit.cshtml
HtmlField-Trumbowyg.Edit.cshtml

Regards

**Comment by jtkech** [comment]
Better to use

    $.trumbowyg.svgPath = @Url.Content("~/OrchardCore.Resources/Styles/ui/icons.svg");

Note: In many places we pass such data through an html data attribute and retrieve them in the script, e.g. see `ContentPreview.Button.cshtml` and `contentpreview.edit.js`. But not sure it's worth here as it already uses the razor `@` operator in the script with `@Html.IdFor(m => m.Html)`.

Would you want to make a PR to fix this issue?
