### ISSUE TITLE
Consider giving the localization module an explicit (negative) order to ensure it's always invoked early enough

### ISSUE THREAD

**Issue by kevinchalet** [OrchardCMS/OrchardCore#6811]
Currently, the localization module doesn't play well with the new OpenIddict 3.0 beta3 built-in localization support as it's not invoked early enough to have a chance to set `CurrentCulture`/`CurrentUICulture` before OpenIddict returns an error message.

@jtkech any idea what would be an ideal value for `Order` here?

**Comment by jtkech** [comment]
We also have a `ConfigureOrder` that only acts on the `Configure()` ordering

        public override int ConfigureOrder => -100;

I will do a PR with the above and merge it if it fixes your issue
