### ISSUE TITLE
Inject Partials at Runtime

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6815]
Is there a way to inject partials into layout at runtime, without creating a custom them? I need to inject a partial into a the site layout dynamically, I was thinking about zones, but it would not work for my case because I can't predict if there's zones in the site layout, also I was thinking about partial views too, but I need the injection happen automatically without URL invocation

**Comment by deanmarcussen** [comment]
Realistically no, there isn't.

Without knowing exactly what you are trying to inject it is hard to suggest a solution.

However using a `IAsyncResultFilter` to inject to a `Zone` would be the appropriate solution.

You could look at the `LayersFilter` or the `ReCaptchaLoginFilter` for examples of this.

If you're concerned about the zone not being available render to the `Content` zone (which is by convention always present, in for a standard content display ) and move it with js afterwards

**Comment by hishamco** [comment]
> Without knowing exactly what you are trying to inject it is hard to suggest a solution.

Basically I need to inject a piece code of markup something like alert into the layout, it's quite useful for many scenarios one of them which I'm working on it `GDPR`

> However using a IAsyncResultFilter to inject to a Zone would be the appropriate solution.

I will have a try ... thanks Dean

**Comment by hishamco** [comment]
Thanks a lot @deanmarcussen, `AsyncResultFilter` works perfectly, after I convert my partial to shape and tweak the style little bit to make it as expected. 

Last question, how can I control the position if I need to put the shape before the Content Zone?

**Comment by sebastienros** [comment]
There should be a Messages zone already also where we inject the notifications (warnings, errors, ...). And your module could require a theme to have a custom one too.

**Comment by hishamco** [comment]
> And your module could require a theme to have a custom one too.

I don't wanna to create a new theme, anyhow my problem has been fixed

Thanks
