### ISSUE TITLE
Revise Contributor role

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6820]
As we all knew the `Contributor` role not be able to add a new content items, so how the user in this role should be called contributor?!!

I think we need to discuss and agree about the permission for this role before 1.0.0 release

/cc @agriffard @deanmarcussen @sebastienros

**Comment by sebastienros** [comment]
Write and publish own content? Editor can write and publish all content, right? What are the differences in O1?

**Comment by hishamco** [comment]
> Write and publish own content?

That's my expectation, @agriffard what are the differences between Contributor and editor in O1? Because I'm not aware too much about O1

**Comment by hishamco** [comment]
I quote from OC1 docs https://docs.orchardproject.net/en/latest/Documentation/Managing-users-and-roles/

> By default, Orchard includes a number of roles with default permissions:

    - Administrator - Can perform any operation (has all permissions)
    - Editor - Can author, publish and edit his own and others' content items.
    - Moderator - Can moderate comments and tags only. No authoring permissions.
    - Author - Can author, publish and edit his own content items
    - Contributor - Can author and edit his own content items, but not publish them (save draft only)
    - Anonymous - Can view the front-end of the site only.
    - Authenticated - Can view the site front-end, and perform other operations depending on the site and other role permission settings.

**Comment by sebastienros** [comment]
O1 looks good to me

**Comment by hishamco** [comment]
Then I will push a PR ASAP

**Comment by hishamco** [comment]
Seems the permission are fine, but the issue in the UI permission, we should toggle the action buttons based on the role permission

**Comment by sebastienros** [comment]
Please close it and create another issue.
