### ISSUE TITLE
Render content items in ListPart in Summary display

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#6828]
Hi,

I created an ImageGallery content type with a ListPart containing content of type Image (from TheBlogTheme). When I view the ImageGallery in Detail display mode everything works fine.
Then I created a Lucine query  returning all image galleries and display them in a Liquid Page. I use `shape_build_display: "Summary". Now the ListPart is not rendered. From what I see in the Display Driver I think it is by design, but is there a way to render them?

Thnx,
Arjan

**Comment by deanmarcussen** [comment]
This is by design.

There are two approaches
- Render in `Detail` (too obvious?)
- Placement for the `ListPart` to have it render in `Summary` for your particular content type.

i.e.
```
"ListPart": [
  {
     "place": "Content",
     "displayType: "Summary",
     "contentType" : [ "ImageGallery" ]
]
```

Something like that should work.

**Comment by ArieGato** [comment]
> * Render in `Detail` (too obvious?)

yeah, just a bit. 
I really need to distinguish between the two. The layout of the ImageGallery differs between the two.



> * Placement for the `ListPart` to have it render in `Summary` for your particular content type.

This works, but a little too good. For some reason the ListPart is rendered twice.

**Comment by ArieGato** [comment]
I added console_log of Model.Content and Model.ContentItem and the ListPart is present twice in the Content, but once in the ContentItem.
![6828-model-content](https://user-images.githubusercontent.com/1059562/89508506-4b9c7100-d7ce-11ea-83b5-7f7712c6b384.png)
![6828-model-contentitem](https://user-images.githubusercontent.com/1059562/89508513-4d663480-d7ce-11ea-896f-129d7a071399.png)

**Comment by deanmarcussen** [comment]
I am guessing something with the template is not right, or the placement. perhaps you could post both?

**Comment by ArieGato** [comment]
Content-ImageGallery.Summary.liquid
```
{{ Model | console_log }}
{{ Model.Content | console_log }}
{{ Model.ContentItem | console_log }}

<div>
  {{ Model.Content | shape_render }}
</div>
```

placement.json
```
{
  "TitlePart": [
    {
      "displayType": "Summary",
      "place": "Content:0",
      "contentType": ["ImageGallery"]
    }
  ],
  "MarkdownBodyPart": [
    {
      "displayType": "Summary",
      "place": "Content:1",
      "contentType": ["ImageGallery"]
    }
  ],
  "ListPart": [
    {
      "displayType": "Summary",
      "place": "Content:10",
      "contentType": ["ImageGallery"]
    }
  ]
}
```

**Comment by ArieGato** [comment]
Liquid page
```
<div class="layout-container paddings-vertical">
  <div class="row">
    <div class="col-sm-12">
      {% assign imageGalleries = Queries.ImageGalleries | query: contentType: "ImageGallery" %}
      {% for item in imageGalleries %}
      	{{ item | shape_build_display: "Summary" | shape_render }}
      {% endfor %}
    </div>
  </div>
</div>
```

I could make a repo with a recipe which includes the ImageGallery content type definition and contents, the lucene query and razor page.

**Comment by ArieGato** [comment]
I created a repo on TheBlogTheme. Simply copy the folder TheBlogTheme over the existing and create a site. Then click on the Images menu item.

[6828-ListPart-Summary.zip](https://github.com/OrchardCMS/OrchardCore/files/5035063/6828-ListPart-Summary.zip)

**Comment by deanmarcussen** [comment]
Ah, I know why.

The driver returns a `Combined` result both using the `ListPart` shape, one `DetailAdmin` one for `Detail`.
The placement rule is pushing both those results into your `Summary` shape.

So bad advise from me initially.

You could remove one, but the problem with that is that both will still trigger a query on the database (so you get the cost of two queries x by the number of `ImageGallery`.

But equally with the query design you have, you'll make one query initially to get your `ImageGalleries` and then each `ImageGallery` is going to go away and make a query for each of it's list items. 

Maybe this doesn't bother you? it would bother me.

I'd probably end up making a more efficient query to begin with (maybe two, one to retrieve the content types, one to retrieve the list items for each content type). But only if it was a lot of lists/items, and worth the effort.

I might also just wrap the whole thing in a cache block, and suffer the multiple queries once.

**Comment by ArieGato** [comment]
> The driver returns a `Combined` result both using the `ListPart` shape, one `DetailAdmin` one for `Detail`.
> The placement rule is pushing both those results into your `Summary` shape.

This is not very intuitive and expected behavior (to me). Is this by design and desired?

> I'd probably end up making a more efficient query to begin with (maybe two, one to retrieve the content types, one to retrieve the list items for each content type). But only if it was a lot of lists/items, and worth the effort.

I expect that the amount of content items to be low. Are you suggesting to write a custom sql query and merge the results? How would you go about that?

> most of the image galleries I have done are with the `BagPart` as an Image Container

I just didn't think of that. I'll give that a go as well.
