### ISSUE TITLE
Add option to not escape search queries

### ISSUE THREAD

**Issue by thomasebsmith** [OrchardCMS/OrchardCore#6829]
Right now, all search queries are [escaped](https://github.com/OrchardCMS/OrchardCore/blob/acee23ef121a09568198ebda164d591ae9f084ed/src/OrchardCore.Modules/OrchardCore.Lucene/Controllers/SearchController.cs#L123) before being sent to Lucene. This makes sense in most cases, but in some cases, it would be useful to let the user write Lucene query parser syntax directly.

An option should be added to Orchard Core to turn off search query escaping. This could allow easy implementation of advanced searches (e.g. the user could search for "title:search AND tag:lucene").

I am willing to work on a pull request for this feature.

Here's an example of what this could look like:

![search-escape-setting](https://user-images.githubusercontent.com/42979377/89304515-0c024780-d65d-11ea-9cc4-35b99a774001.png)
---
![advanced-search](https://user-images.githubusercontent.com/42979377/89304524-0dcc0b00-d65d-11ea-83c8-83e2800001c1.png)

**Comment by sebastienros** [comment]
I think it's fine to add this option. I would use a boolean that when checked is actually not escaping the query.

"Allow Lucene queries in search forms" 

and it could point to a page in the documentation showing some examples. The default search field is still relevant, in case we type "space or title:foo" for instance, for "space".

**Comment by sebastienros** [comment]
Not that ideally one should write their own search page in this case. We won't be able to support all the syntaxes people can imagine for search.

**Comment by thomasebsmith** [comment]
@sebastienros What do you think the behavior should be when a user enters invalid Lucene syntax? Should the search just return no results, should an error message be displayed, or should something else happen?
