### ISSUE TITLE
Laravel - Passport integration

### ISSUE THREAD

**Issue by andreatosato** [OrchardCMS/OrchardCore#6830]
Hi all, I need to integrate Laravel passport auth to OrchardCore (https://laravel.com/docs/7.x/passport).
I write custom module like Azure Active Directory but we need OpenIdConnect standard. (https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Microsoft.Authentication)
Google implementation is very similar.

Unfortunaly Laravel password not implement OpenIdConnect standard. How can I write module for OAuth2 standard but without OpenIdConnect? 
There are sample? 
docs?
Thanks a lot!

**Comment by jptissot** [comment]
I did write a module like this before. I based myself off of the Github authentication module.

**Comment by andreatosato** [comment]
Thanks @jptissot your sample are great!

**Comment by andreatosato** [comment]
@jptissot  I need to change default **response_type=code** to **response_type=token**.
How can I complete this task?
Thanks a lot

**Comment by andreatosato** [comment]
Change default response_type=code to response_type=token you need to:

Extend class:
```cs
OAuthHandler<CaffeinaOptions>
```
