### ISSUE TITLE
How to  run unit test in Application instance context in Orchard Core

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#6835]
Hi,

I have defain a StartupFixture to start Orchard Applicaiton instance, but I could not works will `ShellScope`.

Defina a OcAppStartupFixture for xUnit test to start an Orchard Core `Application instance`  by `Startup.cs` :

		public class OcAppStartupFixture
		{
			public OcAppStartupFixture()
			{
				var hostBuilder = Host.CreateDefaultBuilder(new string[0])
					.ConfigureLogging(logging => logging.ClearProviders())
					.ConfigureWebHostDefaults(webBuilder => webBuilder

						.UseStartup<ProjectX.Web.App.Startup>()

						.UseNLogWeb());
						
				this.ServiceProvider = host.Services;
			}
			
			public IServiceProvider ServiceProvider { get; private set; }

		}

Define a base Test class to start `Application instance`  by `OcAppStartupFixture`

		public class AppTestBase<TFixture> : IClassFixture<TFixture> where TFixture : class, IApplicationStartupFixture
		{
			public readonly TFixture Application;

			public AppTestBase(TFixture application)
			{
				this.Application = application;
			}
			
			protected T GetService<T>() where T:class
			{
				return this.Application.ServiceProvider.GetService<T>();
			}
			
			protected T GetRequiredService<T>() where T:class
			{
				return this.Application.ServiceProvider.GetRequiredService<T>();
			}
		}
		

Define a Test, run test code in Orchard's Shell Scope:

	   public class IMAppTest : AppTestBase<OcAppStartupFixture>
	   {

			public IMAppTest(OcAppStartupFixture application) : base(application){}
			
			[Fact]
			public async Task InAppRuntimeTest()
			{
				var shellContextFactory = GetRequiredService<IShellContextFactory>();
				IShellHost shellHost = GetRequiredService<IShellHost>();

			   // var runningShellTable = GetRequiredService<IRunningShellTable>();
			   // var shellSettings = runningShellTable.Match(new HostString(), "");
				// using (var scope = base.Application.ServiceProvider.CreateScope())
				
				 using (var shell = await shellContextFactory.CreateDefaultShellContext())
				// using (var shellScope = shell.CreateScope())
				using (var shellScope = await shellHost.GetScopeAsync(shell.Settings))
				{
					var httpContextAccessor = shellScope.ServiceProvider.GetService<IHttpContextAccessor>();
					httpContextAccessor.HttpContext = shellScope.ShellContext.CreateHttpContext();
					await shellScope.UsingAsync(async scope =>
					{
						var session = shellScope.ServiceProvider.GetService<ISession>();
						Assert.NotNull(session);
						var controller = shellScope.ServiceProvider.GetRequiredService<TimNotifyController>();

						var result = await controller.ActionXXX(
							new XxxxxModel() {
								PropertyX = "XXXXXX",
							}
						);

						Assert.NotNull(result);
					});
				}
			}
		   
		}
	

	public static class TestShellContextFactoryExtensions
	{
			internal static Task<ShellContext> CreateDefaultShellContext(this IShellContextFactory shellContextFactory)
			{
				var settings = new ShellSettings()
				{
					Name = ShellHelper.DefaultShellName,
					State = TenantState.Running
				};
				// settings["DatabaseProvider"] = options.DatabaseProvider;
				// settings["ConnectionString"] = options.ConnectionString;
				// settings["TablePrefix"] = options.TablePrefix;

				return shellContextFactory.CreateDescribedContextAsync(settings, new ShellDescriptor()
				{
					Features = new List<ShellFeature>()
					{
						new ShellFeature("Application.Default"),
						new ShellFeature("OrchardCore.Setup"),
						new ShellFeature("Operational"),
					},
					Parameters = new List<ShellParameter>(),
				});
				// return shellContextFactory.CreateShellContextAsync(settings);
			}
	}
	

This unit test throws exception:

	System.NullReferenceException : Object reference not set to an instance of an object.
	   at YesSql.QueryExtensions.Query[T](ISession session)
	   at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.GetShellDescriptorAsync() in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.Infrastructure\Shell\ShellDescriptorManager.cs:line 52
	   
   
         public async Task<ShellDescriptor> GetShellDescriptorAsync()
        {
            // Prevent multiple queries during the same request
            if (_shellDescriptor == null)
            {
			
				// throws NullReferenceException here:
				
                _shellDescriptor = await _session.Query<ShellDescriptor>().FirstOrDefaultAsync();

				........
            }

            return _shellDescriptor;
        }

**Comment by RockNHawk** [comment]
Just add Database setting in ShellSettings can Resove this issue.

	settings["DatabaseProvider"] ="SqlConnection";
	settings["ConnectionString"] = "Server=localhost;Database=xxx;User Id=sa;Password=xxxxxxx";
	settings["TablePrefix"] = "xxx";
	

	internal static Task<ShellContext> CreateDefaultShellContext(this IShellContextFactory shellContextFactory)
	{
			var settings = new ShellSettings()
			{
				Name = ShellHelper.DefaultShellName,
				State = TenantState.Running
			};
			
		settings["DatabaseProvider"] ="SqlConnection";
		settings["ConnectionString"] = "Server=localhost;Database=xxx;User Id=sa;Password=xxxxxxx";
		settings["TablePrefix"] = "xxx";
	
			return shellContextFactory.CreateDescribedContextAsync(settings, new ShellDescriptor()
			{
				Features = new List<ShellFeature>()
				{
					new ShellFeature("Application.Default"),
					new ShellFeature("OrchardCore.Setup"),
					new ShellFeature("Operational"),
				},
				Parameters = new List<ShellParameter>(),
			});
			// return shellContextFactory.CreateShellContextAsync(settings);
	}


But the `Controller` could not resolved by IServiceProvider...

**Comment by jtkech** [comment]
We don't register controllers as services, you may need to do so, at least for your controller, in your unit test context.

We do such things e.g. for GraphQL unit tests but then we use http clients to send requests to API controllers. In fact we have a fixture that is a `WebApplicationFactory<TEntryPoint>` from which we can get http clients.

But see in our `Tests` project what is done e.g. in `OrchardTestFixture.cs`, `SiteStartup.cs`, `SiteContext.cs` and so on, it may give you some ideas ;)

**Comment by RockNHawk** [comment]
@jtkech 
Thank you for response.

I refactor the ASP.NET Core framework, and I resolve controller by `IControllerActivatorProvider`.

To work with Orchard Core, these code may helpful, it works for me:



    public class AppTestBase<TFixture> : IClassFixture<TFixture> where TFixture : class, IApplicationStartupFixture
    {
        public readonly TFixture Application;

        public AppTestBase(TFixture application)
        {
            this.Application = application;
        }

        protected T GetService<T>() where T : class
        {
            return this.Application.ServiceProvider.GetService<T>();
        }

        protected T GetRequiredService<T>() where T : class
        {
            return this.Application.ServiceProvider.GetRequiredService<T>();
        }


        protected async Task RunInShellScopeAsync(Func<ShellScope, Task> execute)
        {
            var shellContextFactory = GetRequiredService<IShellContextFactory>();
            IShellHost shellHost = GetRequiredService<IShellHost>();
            using (var shell = await shellContextFactory.CreateDefaultShellContext())
            using (var shellScope = shell.CreateScope())
            {
                var httpContextAccessor = shellScope.ServiceProvider.GetService<IHttpContextAccessor>();
                httpContextAccessor.HttpContext = shellScope.ShellContext.CreateHttpContext();
                await shellScope.UsingAsync(execute);
            }
        }

        protected T CreateController<T>(ShellScope shellScope, HttpContext httpContext)
        {
            var controllerActivatorProvider =
                shellScope.ServiceProvider.GetService<IControllerActivatorProvider>();
            var controllerContext = new ControllerContext()
            {
                HttpContext = httpContext,
            };
            var controllerObj = (T) controllerActivatorProvider.CreateActivator(
                    new ControllerActionDescriptor()
                        {ControllerTypeInfo = (TypeInfo) typeof(T),})
                .Invoke(controllerContext);
            return controllerObj;
        }
    }


An helper to create `HttpContext`, and set set `shell.RequestServices` to `HttpContext`.

	public static HttpContext CreateHttpContext(this ShellContext shell)
	{
		var settings = shell.Settings;

		var context = new DefaultHttpContext();
         
                // set shell.RequestServices to context
		context.RequestServices = shell.ServiceProvider;
		OrchardCore.Modules.HttpContextExtensions.UseShellScopeServices(context);

		var urlHost = settings.RequestUrlHost?.Split('/',
			StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();

		context.Request.Host = new HostString(urlHost ?? "localhost");

		if (!String.IsNullOrWhiteSpace(settings.RequestUrlPrefix))
		{
			context.Request.PathBase = "/" + settings.RequestUrlPrefix;
		}

		context.Request.Path = "/";
		context.Items["IsBackground"] = true;

		context.Features.Set(new ShellContextFeature
		{
			ShellContext = shell,
			OriginalPathBase = String.Empty,
			OriginalPath = "/"
		});

		return context;
	}




	[Fact]
	public async Task InAppRuntimeTest() {
		await RunInShellScopeAsync(async shellScope =>
		{
			var session = shellScope.ServiceProvider.GetService<ISession>();
			Assert.NotNull(session);

			var controllerObj =
					CreateController<XxxxxController>(shellScope, shellScope.ShellContext.CreateHttpContext());

			var result = await controllerObj.Index(new XxxxModel(){});

			Assert.NotNull(result);
		});
	}
