### ISSUE TITLE
Menu click on admin page is invalid

### ISSUE THREAD

**Issue by keepRunM** [OrchardCMS/OrchardCore#6836]
I downloaded the release version 1.0.0-rc2. After I created the site, I entered the admin page and clicked the menu without any response. No abnormal information

**Comment by hishamco** [comment]
Perhaps it was a browser cache or internet issue, could you please try again without steps to reproduce we aren't able to validate if it's a bug or not

**Comment by ns8482e** [comment]
@keepRunM Are you experiencing similar to this #6334 ?

**Comment by keepRunM** [comment]
> Perhaps it was a browser cache or internet issue, could you please try again without steps to reproduce we aren't able to validate if it's a bug or not

thanks for the reply,I have found the problem. Yesterday, there is an abnormal network  and the script of http://code.jquery.com/ cannot be loaded.

**Comment by keepRunM** [comment]
> @keepRunM Are you experiencing similar to this #6334 ?

It is caused by JavaScript not being loaded, can I use offline scripts?

**Comment by ns8482e** [comment]
@keepRunM yes there is an option in settings
