### ISSUE TITLE
How to display the content-type title in the admin list view if the title isn't from type TitlePart?

### ISSUE THREAD

**Issue by stevo-knievo** [OrchardCMS/OrchardCore#6837]
I have a content-type where I don't use the `TitlePart` as the title of the content-type instead I'm using taxonomy type. I noticed even if I use a simple `Text Field` as the title for `content-type` it won't show up.  

In the admin under _Content -> Content Items_ the title is the `content-type` name instead of the value. I'm not sure what the best way to fix it. I'm struggling to find some (the "right") solution.

**1st attempted: My Own admin controller**
I created my own controller and I managed to get the same view as the "Manage Content" (_Content -> Content Items_) view.

I used this code to guide me:
https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/dev/Controllers/AdminController.cs

But I'm struggling to figure out how to get my own DisplayType to work (Content.SummaryAdminFoo.cshtml)
I copied the [Content.SummaryAdmin.cshtml](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Views/Content.SummaryAdmin.cshtml) but only the checkbox and title (content-type name) shows up.

**2nd attempted: set the contentItem.DisplayText on save**
After digging into the code more I saw at the [ContentLinkTagHelper](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Contents.TagHelpers/ContentLinkTagHelper.cs) class at line 154

```
if (output.TagMode == TagMode.SelfClosing && metadata != null)
{
    output.TagMode = TagMode.StartTagAndEndTag;
    if (!string.IsNullOrEmpty(contentItem.DisplayText))
    {
        output.Content.Append(contentItem.DisplayText);
    }
    else
    {
        var typeDefinition = _contentDefinitionManager.GetTypeDefinition(contentItem.ContentType);
        output.Content.Append(typeDefinition.ToString());
    }
}
```

Should/could try to set the contentItem.DisplayText on save... if yes please give me a hit how.

Every hint is more than welcome.  I'm happy to provide a dummy project too if that helps.

Thanks in advance!

**Comment by jtkech** [comment]
This is what is done in `TitlePartDisplay.cs` by the TilePart driver in its `UpdateAsync()` method.

So you may have a part whose driver do the same on updating but that do nothing in `Display()` for the front end.

That said, look at `TitlePartDisplay.cs`, there is already a `RenderTitle` option in the `TitlePartSettings`. So, if you only want to have a display text but that is not rendered on the front end, this is already possible through the admin by updating the title part settings of your content type.

**Comment by deanmarcussen** [comment]
There is also a liquid pattern and option available for the title part to calculate it from another field, which can be a simple approach when the actual title value is held elsewhere

**Comment by stevo-knievo** [comment]
First of all, thank you both @jtkech and @deanmarcussen for taking the time to reply. I much appreciate it.

Unfortunately, I have no idea what your guys talking about. I'm a newbie in the Orchard world. I'm using Orchard in the headless mode. The content will get served via REST API or GraphQL. But I'm not there yet.

I'm guessing both of my solutions attempted were not on track :)

Unfortunately, I need a bit more guides. I'm pretty much stuck at the moment.

Thanks again!

**Comment by stevo-knievo** [comment]
I got it semi to work with a simple text field using `Liquid` pattern! As described [here](https://docs.orchardcore.net/en/dev/docs/reference/modules/Title/#titlepart-settings):

`{{ ContentItem.Content.Product.Name.Text }}`

Now, I'm trying to figure out the `Liquid` pattern to display the selected tag.

**Comment by stevo-knievo** [comment]
**I got it!!** 

`{{ ContentItem.Content.Product.Title.TagNames[0] }}`

Thanks again! @jtkech  @deanmarcussen
