### ISSUE TITLE
How to physically delete a ContentItem ? 

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#6841]
`IContentManager` only provide a logical deletion, how can I physically delete a ContentItem ? 

        /// <summary>
        /// Removes <see cref="ContentItem.Latest"/> and <see cref="ContentItem.Published"/> flags
        /// from a content item, making it invisible from the system. It doesn't physically delete
        /// the content item.
        /// </summary>
        /// <param name="contentItem"></param>
        Task RemoveAsync(ContentItem contentItem);

**Comment by hishamco** [comment]
What if you create `ContentHandler` and override`IContentHandler.RemovingAsync()` to delete the content item permenantly

**Comment by deanmarcussen** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6056

Someone could implement the feature.

**Comment by aaronamm** [comment]
@hishamco I right now use your suggestion as how to hard remove a content item.
