### ISSUE TITLE
authorization issue with Grapghql (Author role)

### ISSUE THREAD

**Issue by He-Wolf** [OrchardCMS/OrchardCore#6845]
Hey Guys,

I have been working on a project for some days with no issue, but yesterday I got one which I have not been able to solve since then.

I am creating a headless CMS with Graphql and Facebook login. I test my app with Postman and the integrated Graphql interface in the admin panel.

There are two users so far: the admin and me with my Facebook account. I set my FB user account to Author role, which means I can only query the content items which I own. I set up the OIDC server as well so I can authenticate with Postman and also can sign in to the admin panel.

When I set my FB account role to Administrator, I can query all the content items (not just the ones that I created - this is OK). I assume that if I set my role to Author, I should be able to query only my content items. The strange thing is that when I set my role to Author, I get an error: GraphQL.Validation.ValidationError: Authorization is required to access the field. player.

Is it a bug or I did something wrong?

**Comment by sebastienros** [comment]
Have you checked the Permissions for Author and if some differ with Administrator try to check them and see if that solves the issue. If that works we might still think it's a bug to fix, like a wrong default, or maybe just some normal behavior we need to document.

**Comment by He-Wolf** [comment]
Yes, a checked the options.
I think the problem is with the option that can be seen highlighted on the image below:
![image](https://user-images.githubusercontent.com/48729704/89617590-c034e580-d88a-11ea-8e32-6e5d2a733732.png)

When it is ON, I can see all the content items (not just mine), but it is normal because this option aims to mean this.
![image](https://user-images.githubusercontent.com/48729704/89617959-6e408f80-d88b-11ea-8d4d-9235875b2ef4.png)

But when I unclick it, the following error message comes:
![image](https://user-images.githubusercontent.com/48729704/89617815-2a4d8a80-d88b-11ea-8315-0c49860e1d31.png)

Just to show you, who the owners of the items are:
![image](https://user-images.githubusercontent.com/48729704/89617764-173aba80-d88b-11ea-8357-96bdcb54ce7e.png)

**Comment by carlwoodhouse** [comment]
Have you checked the content type specific permission, i think once you unset (view all content) you need to make sure your role still has permission to view the specific type. (I mean that is kinda confusing but its how it works in normal ocore too i think(

**Comment by GoorMoon** [comment]
checked that issue and found that probably that cause because of not proper permission in PR  #3951 
on file src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentTypeQuery.cs

Maybe should be CommonPermissions.ViewOwnContent ?

**Comment by carlwoodhouse** [comment]
The problem is the query is actually requesting content that isn’t just his
.... because he’s is basically asking for all of them .. not just his.

The permission it is checking is correct; otherwise you would get content
returned that isn’t yours when you didn’t have permission. Own content is
implied by the other permission; the reason you get unauthorised is that
the result set includes content you don’t have permission to see

We need to decide if this is the correct behaviour; or if it should only
return your stuff and not throw unauthorised (seems a bit wrong to me
personally)

**Comment by GoorMoon** [comment]
@carlwoodhouse 
```
The problem is the query is actually requesting content that isn’t just his
.... because he’s is basically asking for all of them .. not just his.
```

i see, then maybe executor will filter by user permission

**Comment by carlwoodhouse** [comment]
Personal opinion is that the current behaviour is correct and that if this behaviour / setup is desired they should query by author

**Comment by GoorMoon** [comment]
@carlwoodhouse 

you mean explicitly in each query filter by author ?

**Comment by carlwoodhouse** [comment]
Yeah.

Possibly the author filter should be expanded to be ‘content this author
has permission to view/edit’ as well as content by this author which I
think it is atm.

**Comment by GoorMoon** [comment]
Just checked this, again with author/owner filter:

```
{  
    newsLine(where: {owner: "roman"}) 
    {    
        displayText
    }
}
```
But steal get an authorization error i call GraphQL query from SPA application (Auth0 OpenID authentication)
if i tick `View all content` in Author role, query (without filter) work fine but return all content ether owner or not. 
i can't filter query on client side it's be a security issue, so i think only possible solution is custom controller that return desired result.

@carlwoodhouse  Thank you for the clarification.
