### ISSUE TITLE
Using placement.json with Named Parts

### ISSUE THREAD

**Issue by wgigg** [OrchardCMS/OrchardCore#6850]
As far as I can tell, there is no way to move both the BagPart and the name (which is just an h5) into a column using placement.json. 
My placement contains the following:
`"BagPart_Edit": [
		{
			"differentiator": "Breadcrumbs",
			"place": "Parts#Common:5"
		}
	],`

It is not mentioned in the docs so I would appreciate some help.

**Comment by deanmarcussen** [comment]
No, the H5 name is added via the `ContentPart_Edit` shape, so you can't.

I just replace the shape in one of my modules, with a dependency on `OrchardCore.Contents` 

```
@using OrchardCore.ContentManagement.Metadata.Models
@using OrchardCore.ContentManagement.Metadata.Settings
@using OrchardCore.ContentManagement

@* @{
    ContentPart contentPart = Model.ContentPart;
    ContentTypePartDefinition typePartDefinition = Model.ContentTypePartDefinition;
    var description = typePartDefinition.Description();
    var namedPart = typePartDefinition.PartDefinition.IsReusable() && typePartDefinition.Name != typePartDefinition.PartDefinition.Name;
} *@

@* Removed name part descriptions here *@
@foreach (var shape in Model)
{
    @await DisplayAsync(shape)
}
```

There's an issue here to add some alternates for it https://github.com/OrchardCMS/OrchardCore/issues/6784

You could probably do it with the templates admin feature as well.

We should probably move the `H5` to a driver shape so it is placeable

**Comment by wgigg** [comment]
Thanks, I ended up doing something similar. I initially tried to use ContentPart_Edit to wrap the titles in a new shape which could then be positioned using placement.json but had no luck.
