### ISSUE TITLE
Falling into the loop after content editing

### ISSUE THREAD

**Issue by VahidFPA** [OrchardCMS/OrchardCore#6856]
I wanted to change one of its fields after editing a content (for example, incrementing field) 
in use "Edit Content Updated Event"
After editing, it falls into the loop. Once I edit myself and the rest of the loop falls into the Workflow edit.
![workflow](https://user-images.githubusercontent.com/3223934/89707121-abd31480-d980-11ea-996d-03a6e7c8e1a5.png)

**Comment by jtkech** [comment]
This is because the `UpdateContentTask` call the `UpdateAsync()` of the content manager that triggers again the `ContentUpdatedEvent` and so on. Can you retry with the last dev branch, it has been fixed recently through #6054

**Comment by VahidFPA** [comment]
Thank you very much
Corrected after the update
