### ISSUE TITLE
Lazy loading images

### ISSUE THREAD

**Issue by KshitizGIT** [OrchardCMS/OrchardCore#6859]
With the  attribute loading=”lazy”, images can be lazily loaded. This can be help with load times for Orchard Sites containing lots of images.

**Comment by hishamco** [comment]
This is neat, could you please show us a gif screenshot, also it would be nice if you check the network traffic before and after

**Comment by ns8482e** [comment]
@KshitizGIT I guess you can create `<img>` with attribute `loading="lazy"` in your theme template.

**Comment by sebastienros** [comment]
Once we have a shortcode to render an image url, you will be able to do it with your own img tag. c.f. https://github.com/OrchardCMS/OrchardCore/issues/7186
