### ISSUE TITLE
Remove explicit call to AddNewtonsoftJson, and all via configuration

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#6861]
In purely headless scenarios where we use the raw controllers, we shouldnt be tied to Newtonsoft if we dont want too

https://github.com/OrchardCMS/OrchardCore/blob/6d7d10933127a6f66623cc03081620ca1b8011a2/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L89

**Comment by sebastienros** [comment]
Issue is that content items have a custom formatter in Newtonsoft. So we require it, unless we can provide another formatter when System.Text.Json is used.

**Comment by hishamco** [comment]
This is may related to https://github.com/sebastienros/yessql/pull/237

**Comment by carlwoodhouse** [comment]
Also I think until we upgrade graphqldotnet to the latest version system.text.json isn’t supported @Jetski5822

**Comment by sebastienros** [comment]
Until we can provide some custom serializer for System.Text.Json, we can't remove it.
Which might already be the case. We'd just need to re-implement this class: 
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentItemConverter.cs

**Comment by Piedone** [comment]
After the move to System.Text.Json, this isn't an issue anymore.
