### ISSUE TITLE
OpenId token does not return refresh token 

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#6862]
Hi, I have checked  `Allow Fefresh Token` in applicaiton.

But the token API does not return `refresh_token` parameter, so I can't refresh token. 

![image](https://user-images.githubusercontent.com/3222379/89747273-a268ba00-daf0-11ea-8c67-6064a11d0e3d.png)

Orchard Core version: dev  branch latest version.

**Comment by kevinchalet** [comment]
Hey,

To get a refresh token, you must request the `offline_access` scope.

Cheers.

**Comment by RockNHawk** [comment]
@kevinchalet  Thank you, it works !
