### ISSUE TITLE
Meeting feedback

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#6863]
@agriffard 

About the Password configuration documentation #6800, all the config stack is automatically done at the app level (our tenant level `IShellConfiguration` is built on it), so you don't need to ùse a new `ConfigurationBuilder`, just inject `IConfiguration` in the app startup, and then use the same options binding.

Note: The same can be done at the tenant level in a module startup or from the app with our `ConfigureServices()` helper acting on an `OrchardCoreBuilder` (e.g. returned by `AddOrchardCms()`) but by using `IShellConfiguration`.

@sebastienros 

About `ShellScope`, i thought about making an `IShellScopeAccessor` that we could use as `IHttpContextAccessor`, and maybe an `.AddIShellScopeAccessor()` extension, if you want something more DI friendly. But in fact it would just return the same **static** `AsyncLocal` component that we access directly through `ShellScope`, but as you want ;)

**Comment by deanmarcussen** [comment]
`IShellScopeAccessor` 

I like this idea of this @jtkech , it feels weird to be to be using `ShellScope` directly, even though it works well, and even though it would be just returning the same static.

**Comment by jtkech** [comment]
@deanmarcussen why not, added on my list ;)
