### ISSUE TITLE
Content Picker Hide "used" values from the ContentItems Picker

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#6865]
How can i show list in the ContentItem Picker only once, if any value was used remove it from the list

**Comment by deanmarcussen** [comment]
Can you explain a little more, perhaps with some screen shots? 

I think you mean if the content picker fields supports picking multiple items, that when an item has already been selected, it shouldn't be available for selection again?

Currently the behaviour is that if you select an item that is already selected, it doesn't add it twice, but it should be possible for the select list to stop showing it as available for selection, and that seems like it would be a good improvement to the ui.

But I'm not sure if that's actually what you're asking for @vitalybrandes

**Comment by vitalybrandes** [comment]
> 
> 
> Can you explain a little more, perhaps with some screen shots?
> 
> I think you mean if the content picker fields supports picking multiple items, that when an item has already been selected, it shouldn't be available for selection again?
> 
> Currently the behaviour is that if you select an item that is already selected, it doesn't add it twice, but it should be possible for the select list to stop showing it as available for selection, and that seems like it would be a good improvement to the ui.
> 
> But I'm not sure if that's actually what you're asking for @vitalybrandes

@deanmarcussen 
Customer / Employee
Each one of them are content item,
Employee list in Content Picker for the customers,
I am picking one, and would like to "Hide" it form the Any other customer, as this employee already assigned.

Did i understand right, that now, if content item was added (Employee) , its appear in the list , but can not add it again?

**Comment by deanmarcussen** [comment]
@vitalybrandes ok I thought your requirement was more complex.

You would have to implement a custom editor for the content picker in this case.

`IContentPickerResultProvider` and you would have to query the other `Customer` content items to reduce the list of available employees.

See the `DefaultContentPickerResultProvider` and how that is working, and implement an editor perhaps named `Employee` that is specific to the needs. 

It's in the docs how to make an editor.

**Comment by vitalybrandes** [comment]
@deanmarcussen Thank you!
