### ISSUE TITLE
LinkAdminNode URL based on AdminUrlPrefix

### ISSUE THREAD

**Issue by szilardcsere89** [OrchardCMS/OrchardCore#6866]
I have to change `AdminUrlPrefix`. Is there any way to leave the `Admin/` prefix from the URL of `LinkAdminNode`? Can OC manage that dynamically?

**Comment by deanmarcussen** [comment]
It is just a text field containing a url which can link anywhere in the site, not just the admin area, so there is currently nothing dynamic about it.

By prefixing it automatically with the `AdminUrlPrefix` you would lose the ability to link elsewhere in the site, which is a useful feature.

We could potentially parse it with a liquid, and add a filter to obtain the admin url.
