### ISSUE TITLE
GitHub Discussions setup

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6867]
As we've talked about it before, GitHub has a new beta featured called Discussions. I've now enabled this, see https://github.com/OrchardCMS/OrchardCore/discussions/6869 for details. This issue is to track any tasks for setting it up.

Possible to-dos if and when we completely embrace Discussions, depending on what we decide, all contingent.
~~- [ ] Close Gitter.~~
- [ ] Change the Forum link on the website.
- [ ] Convert issues with the "discussion" and "question" tags to discussions. This can be done in bulk from under [Labels](https://github.com/OrchardCMS/OrchardCore/labels).
Ex: https://github.com/OrchardCMS/OrchardCore/labels/discussion
- [x] ~~Add a very long and opinionated issue template to upset @sebastienros~~ Add an issue template that directs people to discussions for things that are not bug reports or feature requests. This can be nothing more than `<!-- instructions -->`.
- [x] Point https://github.com/OrchardCMS/OrchardCore/blob/dev/CONTRIBUTING.md#other-discussions to Discussions and thus recommend it instead of StackOverflow.

**Comment by sebastienros** [comment]
I don't want to close Gitter

**Comment by sebastienros** [comment]
I don't want to change the forum link on the website

**Comment by Piedone** [comment]
How about not changing the Forum link but having a new link that overwrites the old one?

**Comment by hishamco** [comment]
> I don't want to close Gitter

Gitter is interactive, but we need to balance the efforts, especially for those who active there, one more thing I see many issues filed here and discussed there which is waste the time here or there

We could clarify when we choose each one of them

**Comment by agriffard** [comment]
I also think we should keep Gitter.
We could change the title and specify that you can create discussions on GitHub.

I would change the forum link to point to the GitHub discussions on the website because this is what looks like the most to a forum.

**Comment by Jetski5822** [comment]
I don't see how Discussions would close Gitter in all honesty, they are two very different mediums.

**Comment by hishamco** [comment]
Can we enable discussion categories?

**Comment by Piedone** [comment]
We do have them (Everything, General, Help, etc. are these). There are no custom categories yet, I think GH is working on it for a future date.

**Comment by hishamco** [comment]
I see .. I just confused when I saw this https://github.com/oqtane/oqtane.framework/discussions/738 I thought there's a custom once

**Comment by Piedone** [comment]
The current one also needed to be enabled, I just asked GitHub to do it in the beginning :).

**Comment by agriffard** [comment]
There is actually a Label 'Discussion': https://github.com/OrchardCMS/OrchardCore/labels/discussion
Should we transform those issues to discussions and remove the label?

**Comment by agriffard** [comment]
Along with the Issue template, we could also have some explanations about the issues/triage management.
Ex: https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md
https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md

**Comment by Piedone** [comment]
I think now it's safe to say that Discussions work and they were also improved quite a lot by GitHub.

So if all good then would you change the Forum link to it on the website @agriffard? Maybe by keeping a button like Chat. Also, if anybody has an objection, I'd create an issue template as discussed previously, i.e. 

> Add an issue template that directs people to discussions for things that are not bug reports or feature requests. This can be nothing more than `<!-- instructions -->`.

I don't think changing existing issues is needed.

I've disabled the option to select and answer for all but the Q&A category (previously this wasn't possible) because the others should rather really be just discussions. Let me know if this is wrong.

**Comment by hishamco** [comment]
I think issues suited if there's a bug, but we could move others to discussion

> I've disabled the option to select and answer for all but the Q&A category (previously this wasn't possible) because the others should rather really be just discussions. Let me know if this is wrong.

I think it's good to mark the best answer, to avoid see the entire thread without know which is the best answer. I'm not sure if there's away to hide the answered discussions if it's belong to Q & A category?

**Comment by deanmarcussen** [comment]
What we do need @Piedone is a way to turn discussions into issues, when something is agreed on, and we want them to do a pr about it.

I didn't see a button, if you know of one?

**Comment by hishamco** [comment]
Ya linking issues with PRs is very useful, I didn't see such feature in discussions, unless you have a permission to enable this feature - if it's exist -

**Comment by Piedone** [comment]
I mean issues remain, of course, just changing existing discussion-like issues (like discussed previously) is not really necessary because why bother. So no swapping out issues with discussions :).

The other way around is not possible, so you can't turn discussions into issues (as far as I remember this was deliberate by GitHub) but you can open an issue by referencing a discussion:
![image](https://user-images.githubusercontent.com/1976647/100475311-100e1580-30e3-11eb-8def-08e3ea3e8f12.png)

Answers in the [Q&A category](https://github.com/OrchardCMS/OrchardCore/discussions?discussions_q=category%3AQ%26A) are still enabled so you can also filter on unanswered ones if you want to find ones where help might be needed:
![image](https://user-images.githubusercontent.com/1976647/100475446-6713ea80-30e3-11eb-8be7-7c85c810ca79.png)

I just think this is not necessary in the other categories. E.g. an idea is not "solved" by a single answer (that's a question), it's discussed freely, and then maybe issues opened or something.

BTW no new categories can be added, as well as the existing ones remained but I think these are good for now.

**Comment by hishamco** [comment]
I forgot there's a filter ;)

Thanks

**Comment by Piedone** [comment]
So I think we're done here. Though I'd still change the Gitter link on the website to not say "Forum" but rather "Chat".
