### ISSUE TITLE
a question about localization

### ISSUE THREAD

**Issue by cmrdY** [OrchardCMS/OrchardCore#6871]
Hi, this is my first time posting a question on Github so I am sorry If I am not doing it right.

I have played around with Orchard Core (decoupled scenario) and I have a question . Is there a way for to access localized versions of a content item using the same alias? 
I mean something like
/en-us/products/product-1
/ar-JO/products/product-1

what I was able to achieve is 
/products/product-1
/products/product-1-ar-JO

**Comment by hishamco** [comment]
I didn't try that but as I remember you can do this via Autoroute using a fluid pattern

**Comment by sebastienros** [comment]
Aliases should be unique. What you can do is add a custom TextField, that you can call Alias too if you want, or Handle, and then query it (enable SQL Fields Indexing feature).
