### ISSUE TITLE
Modules - tenant specific settings

### ISSUE THREAD

**Issue by lszomoru** [OrchardCMS/OrchardCore#688]
I just watched [Sébastien's video](https://channel9.msdn.com/Shows/On-NET/Sbastien-Ros-Modular-ASPNET-apps) and I would like to take advantage of the modularity and multi-tenancy in my own ASP.NET Core application. Based on the presentation, the settings that are specific to a tenant should be placed in the tenants.json file. Does that file support strongly types settings, or only key, value (string) pairs? If this support does not exist, is it on the road map? Thanks! 

Ladislau

**Comment by sfmskywalker** [comment]
"tenants.json" is parsed into key (string)/value (string) pairs, so you would have to parse/deserialize the individual values of interest yourself from `ShellSettings`.

Alternatively, you can implement your own sub-class of `ShellSettings` in your hosting web application. You'll notice that this is done with `ShellSettingsWithTenants`.
