### ISSUE TITLE
Media Field breaking on preview

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6888]
When you preview a content item with Media Field via Content Preview then from `MediaFieldDriver.UpdateAsync()` eventually `AttachedMediaFieldFileService.MoveNewFilesToContentItemDirAndUpdatePathsAsync()` will be invoked, which moves attached files (under a folder for a non-existing version of the content item). This results in the content item getting broken.

Related: https://github.com/OrchardCMS/OrchardCore/issues/6887

**Comment by deanmarcussen** [comment]
This ones a duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6594 @Piedone and the pr is in to fix it here https://github.com/OrchardCMS/OrchardCore/issues/6594

**Comment by Piedone** [comment]
Fantastic then!
