### ISSUE TITLE
Change admin prefix at tenants settings

### ISSUE THREAD

**Issue by carlomenicucci** [OrchardCMS/OrchardCore#6889]
In a SaaS implementation, we may use different recipes and themes for certain types of tenants (configurations).  In this case, we'll like to know if we can use the AdminUrlPrefix setting at a tenant's appsetting json?   We'll like to be able to change the default Admin prefix for specific tenant settings.

We tried updating the appsettings.json for tenant with no luck.  A plus would be if instead we manually change appsetting json for a tenant, it could be handle as a property on shellsettings or setupcontext so we can autosetup tenants with corresponding configuration.

**Comment by deanmarcussen** [comment]
Can you show what setting you used in your tenants `appsettings.json` (what you are trying to do should work)

**Comment by carlomenicucci** [comment]
This is the appsettings.json for the tenant:

{
  "DatabaseProvider": "Sqlite",
  "RecipeName": "Blog",
  "OrchardCore": {
    "OrchardCore_Admin": {
      "AdminUrlPrefix": "cpanel"
    }
  }
}



> Can you show what setting you used in your tenants `appsettings.json` (what you are trying to do should work)

**Comment by deanmarcussen** [comment]
Can you try with 

```
```
{
  "DatabaseProvider": "Sqlite",
  "RecipeName": "Blog",
   "OrchardCore_Admin": {
      "AdminUrlPrefix": "cpanel"
  }
}
```

The `OrchardCore` prefix is not required (and doesn't work) when in a tenants `appsettings.json`

**Comment by carlomenicucci** [comment]
> Can you try with
> 
> {
> "DatabaseProvider": "Sqlite",
> "RecipeName": "Blog",
> "OrchardCore_Admin": {
> "AdminUrlPrefix": "cpanel"
> }
> }
> 
> ```
> 
> The `OrchardCore` prefix is not required (and doesn't work) when in a tenants `appsettings.json`
> ```

Thanks Dean.  It works like a charm.  Thought the structure we'll be the same.  Now I'll take in consideration.

Still think it would be a plus to be able to add this property on code, looking at the SetupContext and/or in ShellSettings class this can be done, so we can include this parameter on automated tenant setups.

**Comment by agriffard** [comment]
Answered.
