### ISSUE TITLE
Boolean field: add Bootstrap Toogle editor

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#689]
Add Bootstrap Toogle editor to Boolean field:
http://www.bootstraptoggle.com/

**Comment by lukaskabrt** [comment]
It would be nice, if texts for On/Off states are configurable in the field settings.

**Comment by sebastienros** [comment]
Side note, I assume some editors might also require some configuration that is not part of the field settings. Maybe we should implement a way for editor to have settings, and store it alongside the editor name setting of the field instance. It should work the same way as any other driver based component.

**Comment by agriffard** [comment]
See #705 : Bootstrap Switch Editor.

I would like to store additional settings fot the swicth and be able to edit them:
On and Off label

**Comment by agriffard** [comment]
If we had to do a toogle button, we could use this: http://kleinejan.github.io/titatoggle/

**Comment by agriffard** [comment]
Reminder for myself: Bootstrap has some tracking issues for toogle switch
https://github.com/twbs/bootstrap/issues/22090
