### ISSUE TITLE
Taxonomy editor can throw null exception if term type is missing

### ISSUE THREAD

**Issue by snovak7** [OrchardCMS/OrchardCore#6893]
The case when you first create ContentType, and then Content Item, which depends on that ContentType, when deleting that ContentType it doesn't warn you that it is used by that created item, so when you try to edit that item, it errors.

In my particular case, I used Feature Taxonomy, where I referenced to another ContentType (Term ContentType)

**Comment by deanmarcussen** [comment]
This came up on gitter.

I am still not totally sure of the issue.

Was the Term Type you were using for your Taxonomy deleted?

If that's the case it's probably just a null check we are missing somewhere (I think I see where it maybe missing in the `Taxonomy.Edit` shape)

(Possibly slight related https://github.com/OrchardCMS/OrchardCore/issues/6751)

We won't be doing ref integrity checks, it's document db, so it should be self healing rather.

**Comment by snovak7** [comment]
@deanmarcussen yes, and there happens NullReferenceException in Taxonomy.Edit in rc2.
