### ISSUE TITLE
PagerSlim for Lucene Search

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#6895]
I'm curious why the `Search` method in `OrchardCore.Lucene.Controllers.SearchController` returns a `PagerSlim` instead of a `Pager`. Is the performance really bad with a `Pager`? Are there any plans to use a `Pager` in the future? I think most users would expect to see a full pager for search results.

Sorry to question your design decisions, just figured I would ask :)

**Comment by jtkech** [comment]
Yes it is a lightweight pager, you may have to implement a custom search controller / view OR just override the `Search.cshtml` **mvc view** in your theme, as i remember under `.../Views/{module}/{controller}/{action}.cshtml`, so here `YourTheme/Views/OrchardCore.Lucene/Search/Search.cshtml`, and that would use a full pager.

With a lower precedence can also be just under `YourTheme/Views/Shared/Search.cshtml`, this is what is done under the blog theme but with a `Search.liquid` liquid file. Can also be defined in a module `YourModule/Views/Shared/Search.cshtml` if not defined in the theme that has precedence.

You can also override the `Search-Form.cshtml` and `Search-Results.cshtml` **shape view templates** under `YourTheme/Views` OR `YourModule/Views` if not defined in the current theme that has precedence.
