### ISSUE TITLE
Stored Cross-site Scripting security breach

### ISSUE THREAD

**Issue by rmgc77** [OrchardCMS/OrchardCore#6897]
Hi,
I think there is a Stored Cross-site Scripting security breach through the upload of a malicious SVG file, containing malicious JavaScript code, that is then executed whenever a user tries to view the contents of the uploaded file;

In order to replicate this issue, please follow the steps described below:

- Create an svg file with _malicious_ javascript:
`<?xml version="1.0" standalone="no"?> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> <svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg"> <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" /> <script type="text/javascript"> alert(1); </script> </svg>`

- In the media library, upload the file you just created;

- Locate the uploaded file in the Media Library and select View;  

- Observe that a JavaScript alert popup is triggered.

Can you please verify this?

Tks,
Rui Camarinha

**Comment by sebastienros** [comment]
Crazy! Does it mean that we shouldn't allow users to upload svg files?

We should then remove the .svg from the list of allowed extensions.

**Comment by hishamco** [comment]
Thanks so much Rui for reporting this, I made a PR #6900 to remove .svg from allowed extensions

**Comment by Piedone** [comment]
I think this is along the lines of the "should we allow admins to edit actual HTML" question. Just disabling SVG by default is a safe bet.

**Comment by ns8482e** [comment]
Remember that to have XSS attack,  attacker needs to have access to upload the svg image via media library, so IMHO if attacker has access to admin area then you have bigger problem than just XSS

**Comment by rmgc77** [comment]
I think the svg extension can be an important asset and shouldn't just be removed.
There are some possible approaches to maintain this extension in the allowed extensions.
Possible scenarios without disabling the svg extension.

- Open the svg in an image tag. This way, scripts won't execute.

- In the response header of the svg, add an the Content-Disposition Header.(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)
this way it will download instead of opening.

- Disable the view option for svg files and show the thumbnail in an img tag.

this article cover some other possibilities: https://digi.ninja/blog/svg_xss.php

**Comment by Piedone** [comment]
By default, and in a common scenario these images are actually indeed just displayed in `img` tags (like in the Media Library) but nothing prevents you from opening them directly via an URL (or just have a link for it) where this becomes an issue. Changing `Content-Disposition` is an interesting idea but I'm not sure whether it would be good to have this unexpected behavior just for SVGs.

Do note that as a site operator you can configure these extensions so you can re-enable SVG too if you trust all the people who can access your site's admin area.

**Comment by ns8482e** [comment]
Uploading an  maliciously crafted`<svg>`by anonymous users on front-end could consider an XSS attack and should not be allowed.

However here this issue talks about specifically media library which is in admin area. IMHO uploading `<svg>` with inline script by site operator is an intentional (eg `<svg>` game created by site owner - I am sure you might have seen in past on google home page.)  that would render on website with inline script and is not a case of XSS.

**Comment by deanmarcussen** [comment]
There is no question we need to resolve this as security issue.

Content Editors have access to the media library, but are not considered site owners, or admins. 

Only admins should have the ability to implement scripting, or perform operations that can be considered invasive on users, or user privacy.

That being said, this should be reasonably easy to resolve.

Simple adding a small piece of middleware to write a CSP in the media pipeline will prevent any javascript served via an svg  from the known route `/media` (or if configured differently, the configured but still well known media root).

Just tried with `context.Response.Headers.Add("Content-Security-Policy", "default-src 'self';");` and it resolves the issue, but has no impact on inline javascript on the rest of the site.

In terms of front end display through templates, this is the responsibility of the site creators to wrap the svg in an appropriate img tag, unless someone can show me a further issue that we should address?

**Comment by hishamco** [comment]
@deanmarcussen I'm curious how this happen while we already have `HtmlSantizer` in the media shortcode?!!

**Comment by jtkech** [comment]
@hishamco because the malicious script would be in the image file itself

**Comment by hishamco** [comment]
Ya I forgot that the malicious script will be in the svg file not in the `src`, seems I was sleepy when I wrote my comment ;)

**Comment by ns8482e** [comment]
@deanmarcussen - just clarifying - `<script>` is only executed when svg is directly accessed using url in browser's address bar and not executed when svg media is used inside OC Media Library or  OC provided templates for MediaField  - correct?

**Comment by deanmarcussen** [comment]
@ns8482e to the best of my knowledge yes
