### ISSUE TITLE
How to delete a layer widget

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6904]
I can't see a way to delete a widget from a layer.

You can move them to other layers, and you can delete the layer, but that just orphans the widget in the database.

Am I missing something obvious?

**Comment by agriffard** [comment]
In a site with RC2, there is an Actions dropdown list but It does not appear anymore with the latest version.

**Comment by deanmarcussen** [comment]
That would explain it, I'll try and see where it's disappeared off to.

Thanks @agriffard
