### ISSUE TITLE
Question: How to programmatically add item to BagPart

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#6927]
I have a ContentType ActivitiesPage which has a BagPart in it. In the BagPart I have multiple entries of the type ActivityDateItem. I have created a ActivityDateItem.cs model
```
public class ActivityDateItem : ContentPart
{
        public DateField ActivityDate { get; set; }
        public TextField Description { get; set; }
}
```

I load the ActivitiesPage through the following call
` ContentItem contentItem= _orchardHelper.GetContentItemByIdAsync("MyId1234", false).Result;`

After this, I try to add an item as following
```
// get bag part
var bagPart = contentItem.Get<BagPart>("BagPart");

// create new entry
var newItem = new ActivityDateItem();
newItem.Description = new TextField { Text = "test description" };
newItem.ActivityDate = new DateField { Value = DateTime.Now };

// create new content item
ContentItem ci = new ContentItem { ContentType = "ActivityDateItem" };

// weld the newItem to the contentItem
ci.Weld(newItem);

// weld the content item to the bagPart
bagPart.Weld<ContentItem>(ci);

// weld the bagpart to the main contentitem (the activitypage)
contentItem.Weld<BagPart>(bagPart);

// update and publish page
await _contentManager.UpdateAsync(contentItem);
await _contentManager.PublishAsync(contentItem);
```

This all goes through without any exception. But when calling again `GetContentItemByIdAsync` I still get the original version and the new ActivityDateItem is not saved. 

Thanks for your help

**Comment by Piedone** [comment]
This looks like something for [Discussions](https://github.com/OrchardCMS/OrchardCore/discussions) so I'll convert it into a discussion.
