### ISSUE TITLE
TitlePart TitlePartHandler.UpdateAsync Compute the title only if it's empty

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#6931]
Example:

{% assign seed = "now" | local | date: '%Y' | prepend:'JC-' %}
{% assign serial = seed | serial : 4 %}
{% assign suffix = "now" | local | date: "%m%d-" %}
{{ seed | append:suffix | append : serial }}

Serial self-increases and is called multiple times.

**Comment by deanmarcussen** [comment]
The model sent to the liquid template for the titlepart includes the `ContentItem`
```
                var model = new TitlePartViewModel()
                {
                    Title = part.Title,
                    TitlePart = part,
                    ContentItem = part.ContentItem
                };
```

So you could check for a value on the `ContentItem.DisplayText` property in your liquid and choose not to reevaluate the title / serial value, and just return the existing `ContentItem.DisplayText`

Assuming that's what you are trying to do, it's a little unclear,
