### ISSUE TITLE
Content Definition recipe always merges settings

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6933]
The Content Definition Recipe step always merges settings.

When using this on a dev/stag/prod environment this means arrays, like `BagPartSettings` and `FlowPartSettings` are merged.

When you've removed a content type on dev, and removed it form the `BagPartSettings` this change is not reflected on the server when the content definitions step is ran.

What also happens is the widget content type definition also remains, as the recipe only focuses on updating the definitions in the step.

Of course, this is good for the scenario where definitions may have changed on both servers, and for bringing them into sync. (kind of, but that scenario gets a bit confusing)

Suggest that rather than changing this behaviour, it maybe more useful to have another step (or possibly a flag on this recipe step / and the deployment step) to remove all content type part definitions prior to starting to import the new definitions.

**Comment by sebastienros** [comment]
It can be another step if we can reorder them. Otherwise we need a boolean option in the existing step.

**Comment by sebastienros** [comment]
Or maybe have two ContentDefinition steps. One that is merging, and one that is replacing. If we don't want to break the current implementation, we can create a `ReplaceContentDefinition` step that would be equivalent to the "option" flag.

We'd still need a DeleteContentDefinition. But we would not require steps ordering.
