### ISSUE TITLE
ImageShortCodes are not working

### ISSUE THREAD

**Issue by KshitizGIT** [OrchardCMS/OrchardCore#6936]
After the recent changes of #6661, image short code are not working.

**Comment by jtkech** [comment]
Yes, see the last comment of @KshitizGIT in #6661 

> In `AddShortcode<T>()`, `services.AddScoped<T>();` <= line 15

> Hi @deanmarcussen ,

> This is breaking the feature of image short code. After this, ImageShortcodeProvider is never registered as a IShortcodeProvider in the DI. Line number 15 should be changed to

> `services.AddScoped<IShortcodeProvider,T>();`

@deanmarcussen

**Comment by deanmarcussen** [comment]
Yes totally agree. Will pr in a moment
