### ISSUE TITLE
Users admin <script> doesn't get Razor compiled

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6943]
If the app is deployed without Razor Runtime Compilation then the `<script at="Foot" type="text/javascript">` tag in OrchardCore.Users\Views\Admin\Index.cshtml won't get compiled, thus it appears literally in the HTML output (including `at="Foot"`). This causes an "Uncaught ReferenceError: $ is not defined" error since the tag is loaded before all the foot script inclusions.

I'm investigating what the issue might be, but my hunch is a missing OrchardCore.ResourceManagement reference. @deanmarcussen  I believe you've encountered the same things somewhere else?

Edit: Shortcodes needs this too.

**Comment by Piedone** [comment]
Hmm, yes, this: https://github.com/OrchardCMS/OrchardCore/pull/6662 seems to be the same issue.

**Comment by deanmarcussen** [comment]
Yeah that's likely to be it, I imagine you'll pr

**Comment by Piedone** [comment]
Yeah, I'll check out other modules too. Is there any danger to add this reference to just any project that users Razor (i.e. all modules and some themes), even if they don't use tag helpers?

Since this is basically a hidden dependency that only surfaces in a certain runtime configuration it's very annoying and can cause issues down the line at any time. I think we should add this reference everywhere, as well as to the module and theme templates. While there is the possibility that you won't actually use Razor I'd consider having an unnecessary reference much less of an issue than spending time on debugging something that "works on my machine".

**Comment by deanmarcussen** [comment]
Can you add it to `Shortcodes` too (I forgot)

Umm yes, I get your point, but I wouldn't add it everywhere.

Yes, it acts like a hidden dependency, but the issue surfaces for any related taghelper, and I wouldn't want to add all the taghelpers to every project, just in case. (MenuTagHelper, ContentTagHelper, ShapeTagHelper, MediaTagHelper)

It is in the standard theme template though

**Comment by ns8482e** [comment]
@Piedone @deanmarcussen I don't know if my comments are relevant to the issue - But - I have a module that is pre-compiled and disabled run time compilation by changing `PreserveCompilationReferences` as per #6565 and #6629 and works well with `ScriptTagHelper`  without any issue

Only Issue I had was to harvest pre-compiled shapes.

**Comment by Piedone** [comment]
I'll add it to Shortcodes too.

A reference to OrchardCore.ResourceManagement would cover the basic tag helpers (Link, Meta, Resources, Script, Style) which are the most likely to be needed (especially Script and Style). OrchardCore.DisplayManagement is referenced from most (but not all) modules already, as well as from the module and theme templates, so that covers shapes-related tag helpers too but I'm not really arguing for that. All the other module-specific tag helpers are quite niche IMO and since they come from modules I'd guess the developer would remember to add a reference anyway since they're not from the "core".

Hence why I'd add OrchardCore.ResourceManagement to every Razor-using extension and to the CMS module template (the theme has both it and OrchardCore.DisplayManagement already). While unnecessary references are not nice, I see no practical downside but a significant upside (from personal experience, I had to debug two such issues surfacing in production from custom code, found this third one, and implemented it myself in Publish later too - quite painful for something trivial).

@ns8482e Both precompilation and runtime compilation work fine, you just need to remember adding references to the projects of all tag helpers you use.
