### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException (0x80131904) when import content items

### ISSUE THREAD

**Issue by minhdn2** [OrchardCMS/OrchardCore#6953]
Hi,
I tried to import content items to CMS with this file 
[Recipe.zip](https://github.com/OrchardCMS/OrchardCore/files/5116876/Recipe.zip)

And I got the error:
**Microsoft.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.**

Could please help to check and advise? Because I have quite many content items in my CMS

**Comment by deanmarcussen** [comment]
Which version of OC are you using?

On the most recent we are batching at 500 items (intended to get around this issue). 

If you are using an old version please upgrade.

If not, how many content items are in this recipe? (I ran out of fingers to count them on)
And can you post the full exception, so I can see a bit more of the stack trace

**Comment by Piedone** [comment]
Closing due to no reply from the author.
