### ISSUE TITLE
Dropping a password during setup doesn't work

### ISSUE THREAD

**Issue by planetClaire** [OrchardCMS/OrchardCore#6958]
This tripped me up for a while during setup, I'm using a password manager which allows you to drag & drop saved or generated passwords onto input fields.  During setup, if we do this rather than focus then type or paste, the tick appears in the input, but the strength indicator doesn't update and clicking "Finish setup" just does nothing with no indication.  I think we need to update strength.js to check for the "drop" event.

**Comment by hishamco** [comment]
Thanks @planetClaire for reporting this, could you please send a PR for dropping password support?
