### ISSUE TITLE
Get new document id

### ISSUE THREAD

**Issue by SteeveDumais** [OrchardCMS/OrchardCore#6965]
Is there a way to get a proper document id when adding a new Document from a database script.  I see the value is stored in the Identifiers table but after the script is run the yesSqlSession and the table values are different until the session is renewed.  Is there a call I can do to refresh the yesSQLSession

**Comment by Skrypt** [comment]
Please provide an example of what you are trying to do so that we understand better.

**Comment by sebastienros** [comment]
If your document has an `Id` property it will be updated with the correct value.
