### ISSUE TITLE
ContentItemIndex should have a content type index

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#6966]
There is no index on the `ContentItemIndex` for the `ContentType` property - commonly used for searching on.

Probably it needs to have an index for
`ContentType`
`ContentType, Published, Latest`

Possibly just the second one is enough.

**Comment by Skrypt** [comment]
If you mean having a DB Index then yes.

**Comment by deanmarcussen** [comment]
Yes a DB Index (naming is hard )

Ok, so I reviewed execution plans of some common queries, i.e. `Query<Document, Index>()`

None of the indexes we currently have are being used because none of them include the `DocumentId`

Here's an execution plan for opening the content items list

<img width="914" alt="Screenshot 2020-08-27 at 14 00 22" src="https://user-images.githubusercontent.com/13782679/91446311-35cf1880-e86f-11ea-9777-cf995af5744a.png">

Note the Clustered Scan Index on the `ContentItemIndex` table (meaning it's seeking on the primary key, and then hitting the table)

Here it is after adding an Index `DocumentId`, ContentType`, `Published`, `ModifiedUtc`

<img width="892" alt="Screenshot 2020-08-27 at 14 00 49" src="https://user-images.githubusercontent.com/13782679/91446361-4b444280-e86f-11ea-9715-f038cd4fc965.png">

Now seeking against an Index Scan

My point is that none of our indexes include the `DocumentId` so for most queries that join on the document table they're not being used.

A query direct against the index, i.e. `QueryIndex<ContentItemIndex` with a `Where` would use them.

So needs a bigger review.

**Comment by carlwoodhouse** [comment]
Yeah all indexes should really include the document id: it speeds up publishing perf loads (yes sql deletes get super slow on large indexes without it)

I did suggest that yessql should just do it a while back ;) 

https://github.com/sebastienros/yessql/issues/218

**Comment by deanmarcussen** [comment]
Have you been adding custom indexes @carlwoodhouse ?
 
It would be helpful to know what you've tended to add?

I haven't had the time to properly eval all that I feel we should tweak here, but my general take is that we should (where possible, due to key length issues on index tables like the `Autoroute`) have indexes like

- DocumentId (as you say for the update queries)
- DocumentId, ContentItemId, Published
- DocumentId, ContentItemId, Latest
- DocumentId, ContentType, Published, ModifiedUtc (common query)
- DocumentId, ContentType, Published, Latest, ModifiedUtc (another commonish query)

Where common fields are included on a variety of indexes sequentially (i.e. in the order the query is generally made), plus also including the `DocumentId` as it will most likely be used for the JOIN.

**Comment by carlwoodhouse** [comment]
The only one i really add to any index tables by default is the `DocumentId` one.

In terms of contentitemindex i seem to have added these to the ocore app i have that gets some serious traffic ..

![image](https://user-images.githubusercontent.com/465424/93989685-249bfd80-fd82-11ea-8c4b-da4ff9164c59.png)

The first set of brackets is the columns that form the index, the second where they exist are 'included'; columns in sql server. (https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-indexes-with-included-columns?view=sql-server-ver15)

**Comment by deanmarcussen** [comment]
Cheers, helpful to see.

I looked to see if we could easily do `Included` on YesSql a while ago, but it was a SQL Server feature only (from memory), so didn't achieve anything for MySql, which was the db with the lowest key length, i.e. lowest common denominator we needed to still be able to support.

**Comment by carlwoodhouse** [comment]
yeah sadly it is sqlserver only (not helpful in orchard overall, but helpful in my install for best perf haha)
