### ISSUE TITLE
Exception: Shape type 'ShortcodeModal' not found in edit page

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#6968]
i wanted to edit the information on my default page( content item) . after updating the references to version (1.0.0-rc2-14193) I got this error:
Exception: Shape type 'ShortcodeModal' not found
![ShortcodeModal](https://user-images.githubusercontent.com/56995550/91346981-ebec2100-e7e1-11ea-917e-443c2bb5349e.JPG)

my page items are:
![p](https://user-images.githubusercontent.com/56995550/91347344-746ac180-e7e2-11ea-80d4-5ee2be7b09a9.JPG)

why I got this error?

**Comment by sebastienros** [comment]
Something else might need to be updated. The file is named `ShortCodeModal` now.

**Comment by deanmarcussen** [comment]
Can you reenable the shortcode module please

Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6925

(and documented in the documentation that this maybe required when upgrading)

**Comment by overstartup** [comment]
@sebastienros @deanmarcussen it works now, thank's
