### ISSUE TITLE
stope rendering page in edit contentitem

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#6975]
i weird problem i edit and create items.
wen I go to edit content, it hangovers and I can not do anything.

i just have liquid, HTML, and title in my ContentItems.

![1](https://user-images.githubusercontent.com/56995550/91475528-0387e000-e89c-11ea-92ab-274752b79737.JPG)
![2](https://user-images.githubusercontent.com/56995550/91475542-071b6700-e89c-11ea-982c-d5baef7a7820.JPG)
![3](https://user-images.githubusercontent.com/56995550/91475549-08e52a80-e89c-11ea-9c8d-6f63d70fdecf.JPG)

I don't know really what I can do, I activated the debug mode but I can not find anything.

**Comment by Piedone** [comment]
It looks that your browser runs out of memory. EIther your PC doesn't have enough RAM indeed or something eats it up on that page. The only thing I can imagine is some very complex Flow Part structure. Can you export the content item in question and attach the JSON here?

**Comment by overstartup** [comment]
@Piedone i have surface book 2 with 16g ram. it is strange to don't have enough RAM.

[err.zip](https://github.com/OrchardCMS/OrchardCore/files/5159037/err.zip)

**Comment by Piedone** [comment]
The recipe only contains the content definition. Please export the content item itself so I can see what the content item in question consists of.

**Comment by sebastienros** [comment]
Should be fixed by https://github.com/OrchardCMS/OrchardCore/pull/6993

**Comment by Piedone** [comment]
@sebastienros how is this and #6993 related? I don't see why this has anything to do with tag helpers.
