### ISSUE TITLE
Backup SQLite toSqlServer or Mysql

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#6976]
There is any solution to immigrate all data from SQLite to other databases?
i have 8k users and more than 100k records.

**Comment by Skrypt** [comment]
DB-Browser for SQLite has an export to SQL tool.
You can also export to a .csv file which can then be imported back in SQL Server.
https://sqlitebrowser.org/

**Comment by hishamco** [comment]
I will close this while it has been answered and there's no respond from the author
