### ISSUE TITLE
Support Azure AppConfiguration/AWS Parameter Store

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#6979]
Regarding to [KeyVault module development](https://github.com/OrchardCMS/OrchardCore/pull/6422) and mentions [here](https://github.com/OrchardCMS/OrchardCore/issues/4611#issuecomment-546368326), and [here](https://github.com/OrchardCMS/OrchardCore/issues/4107#issuecomment-526845160) I wonder if how can support of Support Azure AppConfiguration can be implemented?

@mattcrossmarc, @JoshLefebvre, @deanmarcussen

**Comment by Piedone** [comment]
Azure AppConfigurations can be readily used as an ASP.NET Core configuration source, as well as via `IShellConfiguration`. Is there anything specific you're missing?

I don't know AWS Parameter Store.

**Comment by deanmarcussen** [comment]
Same as @Piedone already commented regards AWS Parameter Store, it has an `IConfiguration` implementation.

Docs are here for https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app?tabs=core2x

Should not require anything from Orchard Core to implement, unless there is some issue you have found @xperiandri ?

**Comment by sebastienros** [comment]
Closing until more comments are provided, based on answers.
