### ISSUE TITLE
How to upgrade the site? Are there relevant documents?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#6983]
The layout style of my site is rewritten, and the data content remains unchanged. How can I upgrade my site? Is there any relevant documentation? Thank you

**Comment by Piedone** [comment]
Do you mean upgrading like upgrading to a new Orchard version? You can just update the NuGet packages to the new version and run the app. Most of the changes will be applied automatically. If there are breaking changes in the API then you'll get build errors, and if there are manual steps necessary between versions you'll see them in the release notes.

**Comment by pgy866** [comment]
Thank you, I haven't been to the community for a long time. Is there any related method for orchard core? https://docs.orchardcore.net/projects/O1/en/latest/Documentation/Installing-and-upgrading-modules/
