### ISSUE TITLE
Liquid in Queries API

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/OrchardCore#6985]
Hi,

I have a sql query that queries content items that have a liquid body part attached.  It seems that when querying via the api `api/queries/{queryName}` the liquid expressions do not evaluate before the response is returned.

Is there a way to acheive this currently?

thanks

**Comment by jtkech** [comment]
Yes, here a content item is as is, you would need to do what the `ItemController.display()` does, after getting an item by using the `_contentManager`, it uses the `_contentItemDisplayManager.BuildDisplayAsync()` that return an `IShape`.

    var model = await _contentItemDisplayManager.BuildDisplayAsync(contentItem, ... );

This is here that the related part / field handlers / drivers are called and that evaluate e.g. liquid expressions

If you use liquid templates there is a `shape_build_display` liquid filter

But it depends on your context, in a decoupled mode you can still use `BuildDisplayAsync()` through razor, or the above liquid filter, but in a full headless mode you may have to use GraphQL where we support a `render` field that still uses the shape rendering.
