### ISSUE TITLE
Save and retrieve data from custom data 

### ISSUE THREAD

**Issue by salik634** [OrchardCMS/OrchardCore#6989]
Can anyone tell me how to create custom module that can interact with custom table in which i can create, update and retrieve records from database.
Thanks

**Comment by Piedone** [comment]
This is a bit complex question so I encourage you to first learn the basics of Orchard development. For this, check out [the docs](https://docs.orchardcore.net/en/dev/) and the [Training Demo module](https://github.com/Lombiq/Orchard-Training-Demo-Module/).

**Comment by salik634** [comment]
Actually i need a audit trail feature and i am unable to find it in a project repository if there any repository with feature kindly share.
