### ISSUE TITLE
Please consider adding a filter for localizations in "Content Items"

### ISSUE THREAD

**Issue by saciervo** [OrchardCMS/OrchardCore#6991]
This would greatly reduce the noise for translators

![image](https://user-images.githubusercontent.com/707898/91739081-b6648080-ebb1-11ea-9410-b4b0a8f61d2e.png)

**Comment by sebastienros** [comment]
This should be quite easy to do since this view has been made extensible recently.

**Comment by deanmarcussen** [comment]
Which version are you running @saciervo ?

This feature was added (possibly just after RC2) and is enabled by default when the Content Localization module is turned on.

![Screenshot 2020-08-31 at 18 39 09](https://user-images.githubusercontent.com/13782679/91749482-71444c80-ebb9-11ea-9ca5-cdfe18a0eb0a.png)

Yes, not long after RC2 in this pr https://github.com/OrchardCMS/OrchardCore/pull/6551

**Comment by saciervo** [comment]
I'm running RC2, so it will be included in the next one 🎉 That's good to hear, thank you guys!!!
