### ISSUE TITLE
add <base> on layout.cshtml of every theme

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#6992]
add   <base href="@Href("~/")" /> under <head> .
in this way, it will fit the requirement of  blazor and angular , but will not influence current behavior of implementation.

**Comment by ns8482e** [comment]
Use `HeadMeta` zone using layers or in a shape that adds angular app

**Comment by deanmarcussen** [comment]
I don't think we want to add this to any themes.

Our themes are samples of a coupled / non spa theme, and they don't make any sense in the context of angular, blazor, or any other spa.

If you want to use a spa, I suggest the headless recipe, and making a theme. 

https://docs.orchardcore.net/en/dev/docs/getting-started/templates/#create-a-new-theme
