### ISSUE TITLE
Items Display Types for Search

### ISSUE THREAD

**Issue by daene17** [OrchardCMS/OrchardCore#6995]
Hi, I am using Etch.OrchardCore to implement a search. I only want to display the title and one specific content field in my search results. 

![image](https://user-images.githubusercontent.com/8889105/91892858-33423980-ec48-11ea-89a3-d4029c694894.png)

I see in this dropdown you can have different options such as Summary and Detail (which display all content for that content item). But I do not know any other display type besides these two and there is nothing in the documentation to give me additional information. Does anybody know how I could implement what I mentioned above with Etch?

**Comment by sebastienros** [comment]
closing as question is answered
