### ISSUE TITLE
Abstractions of Events look more like abstractions of event handlers

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/OrchardCore#700]
After listening to the latest podcast I had a look into the events hand how are implemented in Orchard Core and they feel backwards. I understand the desire for a type safe implementation.

It feels like the events are not being abstracted, but the contracts for all the handlers. And if you create a module that wants to handle an event, you are actually implementing the handler contract and then you have to handle ALL the events, not the one you care about.

    var tenantEvents = scope.ServiceProvider
          .GetServices<IModularTenantEvents>();   // <--- This is actually getting handlers??

    foreach (var tenantEvent in tenantEvents)
    {
         tenantEvent.ActivatingAsync().Wait();  //  Isn't this directly calling a method on a handler???
    }

Why cant the IEventBus remain and add publish of event types that are in the abstractions, or contracts, assembly rather than strings??

    _eventBus.PublishAsync(new TenantActivated()).Wait();

Then the event types will be type safe, and you then enable the possibility to handle just single events?

**Comment by sebastienros** [comment]
We removed events
