### ISSUE TITLE
HtmlBody Doesn't show The Editor

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#7007]
HTML body just in standard view and it doesn't show the HTML editors. i tested both editors (Wyswyg , Trumbowyg).

![1](https://user-images.githubusercontent.com/56995550/92160880-02245d80-ee30-11ea-9661-d0cf67949332.JPG)

**Comment by ns8482e** [comment]
There could be a javascript error in console. May be due to unable to download scrips from CDN. 
Try changing to use local settings from Site Settings.

**Comment by hishamco** [comment]
@overstartup please provide us steps to reproduce? Also your can check the console logs as Niraj mentioned before

**Comment by sebastienros** [comment]
Feel free to reopen if @ns8482e 's suggestion doesn't work for you.
