### ISSUE TITLE
Regression - Admin Site - Specific content type list, allow only new content item of the selected type

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#7013]
Hi all, 

I have see that the issue #4985 is already here. I have looked at the code and I have see that the code to render the button is right but the code in the controller doesn't filter the contentitem type when a contentitem type is "selected". 

Would you like that i  create a PR about it?

Thank you. 

PS. when you have filtered the contentitem list with the "Filters" text field, could be useful to have a reset button to clear the filter text field and submit the form to have the list unfiltered?

**Comment by PiemP** [comment]
Sorry, 

the code in the controller to manage the issue exists but this variable is false and the user that I use can create this kind of content item
![backend_contentitem_list](https://user-images.githubusercontent.com/2736009/92223713-253b2580-eea1-11ea-8654-7274447e4cd6.png)

**Comment by deanmarcussen** [comment]
`CanCreateSelectedContentType` is a special property that a menu item can provide to allow non createable content to become creatable.

It's used for Menus. _Content -> Menus_

So I don't think it's related to your issue, i.e. it's not intended for that use.

If I understand the issue, you want the new button to be restricted to just the content type provided by an admin menu content type link?

You could probably do that in the same area of code, just not checking against `CanCreateSelectedContentType`

**Comment by PiemP** [comment]
> So I don't think it's related to your issue, i.e. it's not intended for that use.

Thank you for your explaination. I believe to have understand the meaning of `CanCreateSelectedContentType`.

There something wrong in this code because if the option `CanCreateSelectedContentType` is set to **false**, `model.Options.CreatableTypes` is null and the action fill `CreatableTypes` with all the types that are creatable.  

I can do a PR about it? I can add a button to clear the text field used to search content items in the admin interface where content items are listed or is it possible to overwrite the view `ContentsAdminList-Search.cshtml` of the module `OrchardCore.Contents`? 

Thank you

**Comment by deanmarcussen** [comment]
> There something wrong in this code because if the option `CanCreateSelectedContentType` is set to **false**, `model.Options.CreatableTypes` is null and the action fill `CreatableTypes` with all the types that are creatable.

There's nothing wrong in this code (for it's purpose, which is related to menus) but for your purpose it probably needs to do something else as well. 

So yes, please feel free to make a pr.

If you want to do a pr for a filter clearing button please do that as a different pr (seperate issue, easier to review if it's one change at a time)

**Comment by PiemP** [comment]
> If you want to do a pr for a filter clearing button please do that as a different pr (seperate issue, easier to review if it's one change at a time)

I hope to have do it in the right way. Sorry if I stress you @deanmarcussen.
