### ISSUE TITLE
Using Orchard core Open ID as server and as client 

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#7024]
Hi
I am building complex project for Industrial.
Part of the project based on orchard core.
My plan is to run server with orchard core in cloud, and container with orchard core as local service. (On PC)
The idea to use OPEN ID in both places.
The "Client" connect "Server" using Open ID and create user in Local , "Client environment".
3TH side application (Wpf, core, js whatever) will authenticate with the "Local" Orchard core for some data via Graphql or API.

Can i do that? If yes, any HELP with how to use Open ID client in orchard.
Any other solution, something that maybe i miss?

@kevinchalet I am sure you can say something about? ;-) , please....

Duplicating here for History search ;-)

**Comment by deanmarcussen** [comment]
Closing as duplicate https://github.com/OrchardCMS/OrchardCore/discussions/7023
