### ISSUE TITLE
Orchard Core compatibility with Microsoft Bot Framework   

### ISSUE THREAD

**Issue by mattobox** [OrchardCMS/OrchardCore#7026]
I have services.AddOrchardCms().AddMvc(); in my primary Startup.cs file and a separate module that has a bot that uses Microsoft Bot Framework v4. I'm not sure why, but when I try to connect to the bot api I get a 400 response (Bad Request). If I add this line: 

`services.AddControllers().AddNewtonsoftJson();`

Then the bot works but most of the Orchard Core framework stops working. 

Can anyone provide some guidance or resources on how to get the bot framework working within Orchard Core?

**Comment by jtkech** [comment]
`.AddMvc()` is called automatically, not from the main app but when we compose a tenant container (there is at least one tenant, the `Default` tenant), we also call `AddNewtonsoftJson()`. So, just try `.AddOrchardCms()` but without `.AddMvc()`

**Comment by mattobox** [comment]
Thanks @jtkech, I tried that but it led to a similar result. The bot emulator states:

> value: "{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"traceId":"|f602163a-45c551f96b08ab2d."}"

The bot works great as a separate project, but fails as a module in Orchard Core. Would Orchard Core be messing with the web api PostAsync request in any way? I created a simple GET request that works. See below.

```
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Integration.AspNet.Core;

namespace Test.Bot
{
    [Route("api/messages")]
    [ApiController]
    public class BotController : ControllerBase
    {
        private readonly IBotFrameworkHttpAdapter _adapter;
        private readonly IBot _bot;

        public BotController(IBotFrameworkHttpAdapter adapter, IBot bot)
        {
            _adapter = adapter;
            _bot = bot;
        }

        [HttpPost]
        public async Task PostAsync()
        {
            // Delegate the processing of the HTTP POST to the adapter.
            // The adapter will invoke the bot.
            await _adapter.ProcessAsync(Request, Response, _bot);
        }


        [HttpGet]
        public string Get()
        {
            return "hello";
        }
    }
}
```

**Comment by hishamco** [comment]
Did you enable your module?

**Comment by mattobox** [comment]
Yes @hishamco, the module is enabled. I'm able to connect to the Get request without issue.

**Comment by hishamco** [comment]
>  I'm not sure why, but when I try to connect to the bot api I get a 400 response (Bad Request)

This line confused me ;)

> I'm able to connect to the Get request without issue.

So what's the issue then?

**Comment by mattobox** [comment]
You're right, that statement was unclear. The Microsoft Bot is initiated through a PostAsync method on the web api controller above (from an Orchard Core module). When my bot framework emulator tries to connect to the api, it responds with a 400. I created a separate get request on the api to test if the api endpoint is accessible and it returns the string without a problem, also shown above. 

Thanks for your patience. Any help would be appreciated.

**Comment by hishamco** [comment]
That means the issue with the `POST`? Please check the request format and it's parameter, that's why you got 400. Could you please show us how your request looks like?

**Comment by jtkech** [comment]
Anyway don't call `.AddMc()` yourself

Then look at another of our `Apicontroller`, e.g. in `OC.Tenants`, maybe you have to do the same

    [Route("api/tenants")]
    [ApiController]
    [Authorize(AuthenticationSchemes = "Api"), IgnoreAntiforgeryToken, AllowAnonymous] <= also this line
    public class ApiController : Controller <= don't inherit from ControllerBase

**Comment by mattobox** [comment]
@jtkech, that's exactly what it was! Thanks so much for your help. I've been banging my head against the wall for hours trying to figure this out. Cheers!
