### ISSUE TITLE
Module template project with Part: Settings not working

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7028]
When you use the `dotnet new ocmodulecms -n ModuleName.OrchardCore --AddPart true --PartName Test` , the Part settings are not correctly taken into account
https://docs.orchardcore.net/en/dev/docs/getting-started/templates/#create-a-new-cms-module

**Comment by hishamco** [comment]
>the Part settings are correctly taken into account

Are or aren't?!!
