### ISSUE TITLE
HTTP Request Event - Fluid Field

### ISSUE THREAD

**Issue by andreatosato** [OrchardCMS/OrchardCore#7041]
Hi,
I have this error **"Fluid.Values.NumberValue Fluid.Values.NumberValue.Create(System.Decimal, Boolean)"** when use Form and Fluid page.
In page I have field name/id "nomeEdizione".
In a workflow, after HttpEvent, I want to create content and so i create this expression:
```json
{ 
   "nomeEdizione": {{ Request.Form.nomeEdizione }} 
}
```

I use this version for all module: 1.0.0-rc2-13450
Can anyone help me?
Could it be a bug?

//cc @marcozama

**Comment by sebastienros** [comment]
Have you fixed the issue?

**Comment by andreatosato** [comment]
I fix with new rc2 version!
