### ISSUE TITLE
Bug with placement.json for CustomSettings

### ISSUE THREAD

**Issue by arnaudroystatcan** [OrchardCMS/OrchardCore#7042]
I am trying to use the placement.json file in order to create some tabs in our custom settings, but without success. I have had no issues using this for other content but for custom settings, either tabs, cards or columns are not working.

For cards and columns the content doesn't change at all. 

For Tabs the content becomes hidden and no tabs are shown as if some style was missing. I can see the tabs with the content when I inspect the page (see picture).

![image](https://user-images.githubusercontent.com/66786602/92506569-a3663780-f1d3-11ea-8984-ef690e9398e4.png)

**Comment by sebastienros** [comment]
@deanmarcussen thinks you might be missing a constrain on the "groupid" since it's the way settings will be filtered in these pages.

**Comment by deanmarcussen** [comment]
<img width="1085" alt="Screenshot 2020-09-11 at 14 43 29" src="https://user-images.githubusercontent.com/13782679/92932729-335aea00-f43d-11ea-8427-96bb565188d6.png">


Seems to work fine for me. No GroupId required. 

Perhaps your placement is not working. Maybe share that?

**Comment by arnaudroystatcan** [comment]
Thanks for your replies,

This is the content of my placement.json file:

`{

    "DateField_Edit" : [
        {
            "place" : "Parts#Hackathon:0",
            "contentType": [
                "HackathonCustomSettings"
            ]
        }
    ],
    "MediaField_Edit" : [
        {
            "place" : "Parts#Hackathon:0",
            "contentType": [
                "HackathonCustomSettings"
            ]
        }
    ],
    "TextField_Edit" : [
        {
            "place" : "Parts#Hackathon:0",
            "contentType": [
                "HackathonCustomSettings"
            ]
        }
    ],
    "NumericField_Edit" : [
        {
            "place" : "Parts#Team:1",
            "contentType": [
                "HackathonCustomSettings"
            ]
        }
    ],
    "BooleanField_Edit" : [
        {
            "place" : "Parts#Team:1",
            "contentType": [
                "HackathonCustomSettings"
            ]
        }
    ]
}`

**Comment by deanmarcussen** [comment]
I think you've moved everything out of the Content tab, but there must always be a Content tab
try 
```
    "DateField_Edit" : [
        {
            "place" : "Parts:0#Content",
            "contentType": [
                "HackathonCustomSettings"
            ]
        }
    ],
```

Plus also you've put everything at position 0 which doesn't seem right `;` is the modifier for tab order, rather than `:`

**Comment by arnaudroystatcan** [comment]
Hi,
I have changed my placement.json file to what you suggested and it didn't work. I added another contentType to test it on another contentType:
![image](https://user-images.githubusercontent.com/66786602/93100545-448f3b00-f677-11ea-890e-7cea18ea0d58.png)

Below is the result I get. For some reasons, when looking at the HTML, you can see that the tab-content item is there for both, but the nav bar item doesn't show up for the customSettings. Also you can see the border showing up on the customSettings that isn't there if I comment out the content of the placement.json file.

![image](https://user-images.githubusercontent.com/66786602/93100910-af407680-f677-11ea-981e-05db850080e7.png)

**Comment by deanmarcussen** [comment]
I think you might be on an old version.

The tab ids are generated differently on a later release `tab-content-4061agkqhg37jxa3jjy3nbt3wz` rather than `tab-4061agkqhg37jxa3jjy3nbt3wz-content`, and tabs work in more places because of the changes that were made at that time.

**Comment by jptissot** [comment]
We are running `1.0.0-rc2-13450`

**Comment by deanmarcussen** [comment]
The full tabs/cards/columns was merged after rc2 @jptissot 

https://github.com/OrchardCMS/OrchardCore/pull/6509

**Comment by jptissot** [comment]
Ah ok so this is a version issue. Thanks @deanmarcussen
