### ISSUE TITLE
Current user's entity gets stuck in ISession

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#7044]
Found a very curious issue related to Audit Trail (https://github.com/OrchardCMS/OrchardCore/pull/6679) which might be something in OC or YesSql. Consider the following code (can be put anywhere, I've tested it in a plain controller in the Audit Trail module):

```
var user = await _session.Query<User, UserIndex>(u => u.NormalizedUserName == _hca.HttpContext.User.Identity.Name).FirstOrDefaultAsync();
var auditTrailEvents = await _session.Query<AuditTrailEvent, AuditTrailEventIndex>().OrderBy(eventIndex => eventIndex.Id).ListAsync();
```

This will throw "InvalidCastException: Unable to cast object of type 'OrchardCore.Users.Models.User' to type 'OrchardCore.AuditTrail.Models.AuditTrailEvent'." If I swap the two lines then the exception will change to "Unable to cast object of type 'OrchardCore.AuditTrail.Models.AuditTrailEvent' to type 'OrchardCore.Users.Models.User'." So it seems that somehow the firstly queried entity gets stuck in the YesSql session and returned the second time too.

Note that both `AuditTrailEvent` and `User` have a corresponding index. I didn't get such an issue with a non-index query on e.g. Workflows `ActivityRecord`. Also note that we're querying the current user; if the expression filters for another user this doesn't happen. Furthermore, this doesn't happen if the `AuditTrailEvent` uses a similar WHERE expression instead of `OrderBy`.

Perhaps a YesSql `IdentityMap` issue?

Important that this only happens with SQL Server, not with SQLite.

**Comment by deanmarcussen** [comment]
Would be interesting to know if changing the code to this still causes the same issue?

```
var user = await _session.Query<User>
    .WithIndex<UserIndex>(u => u.NormalizedUserName == _hca.HttpContext.User.Identity.Name).FirstOrDefaultAsync();
var auditTrailEvents = await _session.Query<AuditTrailEvent>
    .WithIndex<AuditTrailEventIndex>().OrderBy(eventIndex => eventIndex.Id).ListAsync();
```

**Comment by Piedone** [comment]
I assume you mean the following (there is no `WithIndex` method in the current YesSql version):

```
var user = await _session.Query<User>().With<UserIndex>(u => u.NormalizedUserName == _hca.HttpContext.User.Identity.Name).FirstOrDefaultAsync();
var auditTrailEvents = await _session.Query<AuditTrailEvent>().With<AuditTrailEventIndex>().OrderBy(eventIndex => eventIndex.Id).ListAsync();
```
This causes the same issue. I played around a bit with similar attempts but in the end, it seems that this very particular repro is that surfaces the issue.

And one quite important bit: this only happens with SQL Server, not with SQLite. I'm quite confused. Might be related to MARS as in https://github.com/OrchardCMS/OrchardCore/issues/6919.

**Comment by Piedone** [comment]
Hmm, no, nothing to do with MARS. Even if I remove that from the connstring the error remains with a trivial controller like this:

```
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.AuditTrail.Indexes;
using OrchardCore.AuditTrail.Models;
using OrchardCore.Users.Indexes;
using OrchardCore.Users.Models;
using System.Threading.Tasks;
using YesSql;
using IYesSqlSession = YesSql.ISession;

namespace OrchardCore.AuditTrail
{
    public class TestController : Controller
    {
        private readonly IYesSqlSession _session;
        private readonly IHttpContextAccessor _hca;

        public TestController(IYesSqlSession session, IHttpContextAccessor hca)
        {
            _session = session;
            _hca = hca;
        }

        public async Task<string> Index()
        {
            var auditTrailEvents = await _session.Query<AuditTrailEvent, AuditTrailEventIndex>().OrderBy(eventIndex => eventIndex.Id).ListAsync();
            var user = await _session.Query<User, UserIndex>(u => u.NormalizedUserName == _hca.HttpContext.User.Identity.Name).FirstOrDefaultAsync();

            return "OK";
        }
    }
}
```

**Comment by Piedone** [comment]
Hmm, and it seems it's also tightly connected to the `OrderBy` being on `eventIndex.Id`. If I changed that to e.g. `eventIndex.CreatedUtc` the issue goes away.

**Comment by jtkech** [comment]
Hmm, `eventIndex.Id` is a property of `MapIndex` from which `AuditTrailEventIndex` derives

Looks like we can't order by this property which is related to a primary key of the index table

**Comment by Piedone** [comment]
Thanks for the tips and insights, Dean and Jean-Thierry.

The SQL query seems to be fine. What's more, if `eventIndex.Id` ˙is ordered on but as a second column like in the below query, it also works.

```C#
query.With<AuditTrailEventIndex>().OrderByDescending(eventIndex => eventIndex.CreatedUtc).ThenByDescending(eventIndex => eventIndex.Id);
```

This generates the below query:

```sql
SELECT DISTINCT [Document].*, [AuditTrailEventIndex].[CreatedUtc], [AuditTrailEventIndex].[Id] FROM [Document] INNER JOIN [AuditTrailEventIndex] ON [AuditTrailEventIndex].[DocumentId] = [Document].[Id]  WHERE [Document].[Type] = 'OrchardCore.AuditTrail.Models.AuditTrailEvent, OrchardCore.AuditTrail' ORDER BY [AuditTrailEventIndex].[CreatedUtc] DESC, [AuditTrailEventIndex].[Id] DESC OFFSET 60 ROWS FETCH NEXT 10 ROWS ONLY
```

I don't really know what kind of unit test would cover this. As I explained, this bug is connected to a very particular repro, with the current user. While this is quite specific I don't yet see how this would work outside of the context of Orchard (like I don't yet see why the current user triggers it, which probably is connected to that being queried before, but why is a similar query for another user not triggering it?).

@jtkech note that the `AuditTrailEventIndex` query alone (as well as the `UserIndex` one) works fine. It's only when it's used in conjunction with the other query that it breaks. So in itself the ordering is fine.

**Comment by sebastienros** [comment]
If you want to help even more, could you try creating a failing unit test in yessql? Though have this simple repro is already helping.

**Comment by Piedone** [comment]
As I said just previously, I don't yet see how this can be tested outside of Orchard.

**Comment by deanmarcussen** [comment]
> As I said just previously, I don't yet see how this can be tested outside of Orchard.

If you look at all the YesSql tests you'll see they are all testing against an actual database implementation.

And there are any number of test indexes you can use to create a two queries that are the same as the one you are experiencing issues with.

**Comment by Piedone** [comment]
In the meantime, I've figured out that interestingly enough, this only happens with a single user account in a given system (and it's not easily reproducible with vanilla Orchard). So calling this action with that particular user, even if not logged in with it (like /OrchardCore.AuditTrail/Test/Index?userName=problematic_user) the exception will happen:

```
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.AuditTrail.Indexes;
using OrchardCore.AuditTrail.Models;
using OrchardCore.Users.Indexes;
using OrchardCore.Users.Models;
using System.Threading.Tasks;
using YesSql;
using IYesSqlSession = YesSql.ISession;

namespace OrchardCore.AuditTrail
{
    public class TestController : Controller
    {
        private readonly IYesSqlSession _session;
        private readonly IHttpContextAccessor _hca;

        public TestController(IYesSqlSession session, IHttpContextAccessor hca)
        {
            _session = session;
            _hca = hca;
        }

        public async Task<string> Index(string userName = null)
        {
            var auditTrailEvents = await _session.Query<AuditTrailEvent, AuditTrailEventIndex>().OrderBy(eventIndex => eventIndex.Id).ListAsync();
            var user = await _session.Query<User, UserIndex>(u => u.NormalizedUserName == (userName ?? _hca.HttpContext.User.Identity.Name)).FirstOrDefaultAsync();

            return "OK";
        }
    }
}
```

I don't yet see what's behind this, what makes that one user special. I can't share more information about the account at this stage though.

**Comment by deanmarcussen** [comment]
When you say one user, do you mean when there is one user in the system, or one particular user account across many users?

I think you mean one particular user. 

I would look at the index and document tables for all related documents and see if you can spot some similarity / conflict / cross ref in either the `Id` or `DocumentId` of Index tables / Document table that might be causing the issue

**Comment by Piedone** [comment]
Yes, there are many users but only this one causes the error. Thanks, I'll check those.

**Comment by jtkech** [comment]
> and it's not easily reproducible with vanilla Orchard

Let us know if you find a easier way to repro it so that i could try to debug it when i will have time

Meanwhile, the only specific thing i saw is when an user is created, audit trail events are saved through the audit trail `UserEventHandler` that is called through the `UserStore` **after commiting the session**. Just for info because normally it should work, but maybe an issue when saving entities through a session that has already been committed.

            _session.Save(user);

            try
            {
                await _session.CommitAsync();

                var context = new UserContext(user);
                await Handlers.InvokeAsync((handler, context) => handler.CreatedAsync(context), context, _logger);
            }

**Comment by Piedone** [comment]
That might be something, thank you! @domonkosgabor what do you think?

**Comment by Piedone** [comment]
This was most possibly an issue with the Audit Trail code.
