### ISSUE TITLE
Cannot filter Content Item by ContentField (Text,Boolean,Number ...) in GraphQL 

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#7047]
I have add some file into Content and enabled the `Content Fields Indexing (SQL)` module, sitll only have ContentItem's internal field's filter, so this module only work with `SQl Query` feature and `session.Query<ContentItem's >().With<TextFieldIndex>()...` API ? 

![image](https://user-images.githubusercontent.com/3222379/92559683-a2044000-f2a3-11ea-85c3-5912e5889d07.png)

**Comment by sebastienros** [comment]
Maybe bindings are missing for the SQL indexes.

/cc @carlwoodhouse and @Skrypt if you know that it's actually missing

**Comment by carlwoodhouse** [comment]
Pretty sure your right ..

As far I know there aren’t any. Can’t say 100% as I haven’t done much with
actual fields but I don’t remember seeing any and def didn’t write the code
for any.

**Comment by Skrypt** [comment]
When we built that SQL Indexing feature it was meant for using SQL Queries only as the GraphQL module was still in a non-merged PR if I remember well. Never coded the bindings for GraphQL.

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/16008.

**Comment by Piedone** [comment]
This was duplicated by https://github.com/OrchardCMS/OrchardCore/issues/12781 but since that has two corresponding PRs and some more  context, I'm closing this one.
