### ISSUE TITLE
Problem with javascript files on publish

### ISSUE THREAD

**Issue by RobinC4** [OrchardCMS/OrchardCore#7051]
Hi,

I'm having some troubles with our custom javascript files we added on our own pages inside a module.
This all works fine during development, but today we tested our first publish and these are missing on the pages after publish.

**Development page:**
![image](https://user-images.githubusercontent.com/67279352/92613197-f9fa7100-f2ba-11ea-80da-b7e9b13ce48a.png)

**Published page:**
![image](https://user-images.githubusercontent.com/67279352/92613252-0bdc1400-f2bb-11ea-93dd-2e2a85a07da2.png)

**For the code:**
Our module has a dependency to OrchardCore.Resources (13450).
Inside our SafoxCore.Cura.Web module we have a ResourceManifest build as shown below.
![image](https://user-images.githubusercontent.com/67279352/92612196-ee5a7a80-f2b9-11ea-9e72-a20167efdcd5.png)

This is then added in the view as follows:
<script asp-name="@ResourceManifest.Lots" at="Foot"></script>

Folder structure is as follows (I've taken the first example here, but it's same for Lots just to not make a big screenshot).
![image](https://user-images.githubusercontent.com/67279352/92612741-72acfd80-f2ba-11ea-844f-0c99c532fea9.png)

all these .js files are set as embedded resource for build action.

I hope someone can help me with this, as the website itself is running, just the javascript is missing from every page.
Thanks in advance

**Comment by deanmarcussen** [comment]
Did you enable the module on your prod server?

Normally when the resource manager stops rendering like this it is because it has failed to find a named script

**Comment by RobinC4** [comment]
Hi Dean,

Yes, it is enabled.
We also tried a few things with the Resource Settings but it didn't change anything.
Settings -> general -> tab Resources

**Comment by Skrypt** [comment]
Is your ResourceManifest inside a Namespace?

**Comment by jtkech** [comment]
Did you register your `ResourceManifest` in your module startup?

    serviceCollection.AddScoped<IResourceManifestProvider, ResourceManifest>();

**Comment by RobinC4** [comment]
@jtkech Yes it is present, Forgot that little piece in my original post.
Also, this would probably give errors also during development.
We only have this on publish.

@Skrypt Yes, in the namespace of the module.
![image](https://user-images.githubusercontent.com/67279352/92715957-75f9c500-f35e-11ea-9d56-15da94eb641b.png)

For quick fix, we put it hardcoded in the view which solves it for the publish but is not the same
![image](https://user-images.githubusercontent.com/67279352/92716066-9e81bf00-f35e-11ea-868d-6d2300c45b42.png)

**Comment by deanmarcussen** [comment]
Like I said before this normally means that the `resources` tag helper has tried to render a named script that has not been registered. 

I've not looked into why, but it always stops all rendering of following scripts if it does not find a named script, or dependency.

Things I suggest you try.

- Isolate out the published vs non published issue (I think that's a red herring - or it may reveal an issue with your publishing process)
- Do this by just changing your ASPNETCORE_ENVIRONMENT variable from Development to something else
- Get rid of the constants string - it's making it hard for us to follow the track of your code
- Try registering each resource with the `<script asp-name` individually to see where your missing script is
- Try registering some of the scripts which ship with OC and see if they are working.

Also I see your confirm script but there doesn't seem to be any dependency on it, so can't see how it's turning up on the page

If you can make a simple repro and isolate some things it will be easier for us to help

**Comment by RobinC4** [comment]
Thanks for the suggestions and i'll look into them.
I'll let you know if we succeed in finding the cause or try to create a repro if we don't.

**Comment by RobinC4** [comment]
Hi @deanmarcussen ,

So I changed the envrionment variable to production, and this had the same effect as the publish.
I had removed every use of `<script asp-name` and tried one of the OC scripts (bootstrap and font-awesome) but they also did not work when running as production environment.

I've created a very simple repo which I hope you can access [here ](https://github.com/RobinC4/OrchardCoreResourceTest)(new to github too). Launchsettings I've added the production environment one.
When run (Run this example with SQLite, blank site recipe) you first need to go to admin, features and enable my module Cura.Web.
The OrchardCore Resources module should be enabled by default.
The home page has a resource that ships with OC which is added perfect in development environment, but is not translated using the production one. Have also added an example how we added our own other resources, which have the same effect.

https://github.com/RobinC4/OrchardCoreResourceTest

Thanks

**Comment by deanmarcussen** [comment]
ok so from your repo what I see is that you're not actually running a theme, which we all probably assumed you are :)

Here https://github.com/RobinC4/OrchardCoreResourceTest/blob/96c10f0341d89ff86de4a72817815168e6a28e3c/CoreResource/SafoxCore.Cura.Web/SafoxCore.Cura.Web.csproj#L15

You have no reference to `OrchardCore.ResourceManagement` which is the projects the tag helpers are in.

So when run in production it will fail to load the tag helpers as they need a direct reference to the assembly in which they are.

If you look further in your `index.cshtml` (viewsource) you'll probably find that the tags are there in raw format (probably higher up the page as the `At="Foot"` isn't taking affect.)

**Comment by RobinC4** [comment]
In my repo I indeed not add a theme. I didn't think it would be necessary, we do have one in our main project which also has dependency to `OrchardCore.ResourceManagement` and also a `_ViewImports.cshtml` that adds the same taghelper.
I didn't include it because nothing else for resources is in the theme.

> If you look further in your index.cshtml (viewsource) you'll probably find that the tags are there in raw format (probably higher up the page as the At="Foot" isn't taking affect.)
Yes, We did see the same that it did not get "translated".

> You have no reference to OrchardCore.ResourceManagement which is the projects the tag helpers are in.
So I added this to our module and now indeed it works. We do not have a reference from the module to the theme as each module is not linked to a specific theme.
I went through the documentation again of OrchardCore.Resources and it does not mention the need to also have `OrchardCore.ResourceManagement` . It includes the Abstraction version so you are good to use all the interfaces and I guess in Development mode it will simple handle it? Maybe a small update to the documentation to mention this could be useful, or I'm just stupid I didn't figure it out and everyone else does.

Thanks for the help @deanmarcussen .

**Comment by deanmarcussen** [comment]
Yeah feel free to make an update to the docs.

Every project which uses a tag helper must have a direct reference to the tag helper assembly (it's an ASP.NET thing). It just isn't an issue in development due to runtime compilation.

Nor is it necesary when using liquid
