### ISSUE TITLE
GraphiQL schema is gone

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#7061]
Hi good people of OrchardCore community,

Quick question, my graphiQL disappeared, any ideas? this happened to you before?

Thank you so much as always! 

![image](https://user-images.githubusercontent.com/2730217/92811932-c3ccf800-f373-11ea-86df-98819d0c5a17.png)

Regards,
G

**Comment by deanmarcussen** [comment]
Can you check your logs, they will give you a better clue as to why.

Probably you need to configure a part / field to be collapsed (see some of the usage in the codebase of `GraphQLContentOptions`)

**Comment by webmedia1012** [comment]
Ok will check thank you. Please close this issue for now
