### ISSUE TITLE
Add Azure Deploy Button

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#7068]

**Comment by agriffard** [comment]
I also thought it was a potential interesting feature when I saw this:
https://github.com/oqtane/oqtane.framework/issues/168

**Comment by hishamco** [comment]
You read my mind, I also work with Oqtane I notice this will be a handy feature to try OC on Azure

**Comment by sebastienros** [comment]
It's also already done on Orchard 1

**Comment by salem84** [comment]
Hi, I would like to try to implement it, but there are many ways to do it.
Do you have any suggestion?

As a starting point, we could use Docker image with AppService with container instance... what do you think ?

**Comment by hishamco** [comment]
I think there's an eas way to use ARM if I'm not wrong

**Comment by sebastienros** [comment]
@salem84 that works
@hishamco all the ways are using ARM

**Comment by salem84** [comment]
Yes always with ARM template!
Another solution maybe a complete stack (AppService + Sql database) with Orchard code installed by automatic git deployment (as used also by oqtane) or using code in release package... I haven't ever tested the last solution and I don't know if it's feasible

**Comment by hishamco** [comment]
Thanks Seb I don't know much details about that ;)

**Comment by Piedone** [comment]
As explained under https://github.com/OrchardCMS/OrchardCore/pull/7258#issuecomment-1891113806, I don't think having such a button makes much sense. Is there a reason to still have it?

**Comment by hishamco** [comment]
It's good for newcomers to start OC quickly, but while we have https://try.orchardcore.net/ we might close this

**Comment by sebastienros** [comment]
> As explained under [#7258 (comment)](https://github.com/OrchardCMS/OrchardCore/pull/7258#issuecomment-1891113806), I don't think having such a button makes much sense. Is there a reason to still have it?

I also think it's some work, maintenance and noise that is not required. People can use try.orchardproject.net which is simpler, quicker ... 

Mike has already started an orchard sample for Aspire (we will have time to review it eventually) and that will provide a better story to test the cloud aspect.

**Comment by Piedone** [comment]
Let's focus on those, then. Since then we also have the https://docs.orchardcore.net/en/latest/getting-started/test-drive-orchard-core/ docs with much all the easier approaches documented in detail too.
