### ISSUE TITLE
Document Table Speed Conversation 

### ISSUE THREAD

**Issue by themattkenney** [OrchardCMS/OrchardCore#7087]
We have been using the OC for almost a year and our experience has been great. I would like to discuss an item I think could keep the system fast as the document table continues to grow. I have noticed on our appinsights that consistently one of our slowest pages is /Admin/Contents/ContentItems.  

**A couple of options I wanted to bring up for discussion:**

- Add a field to the document table called "latest" that can be used to query instead of getting the JSON. Index the field by default in the database.
- Add the title as a separate field in the document table to searched against without getting the full JSON. Index the field by default in the database. 
- Create a documentindex table and only query the document table with the id you are getting or under rare circumstances
- Create a documentversion table and store all old versions of the contentitems in this table. It is not often you need an older version.

**Comment by Skrypt** [comment]
> Add the title as a separate field in the document table to searched against without getting the full JSON. Index the field by default in the database.

I think this one makes sense though I would really like that we build a Lucene index for the admin search. Probably we should have both options. I personnally think that searching against a SQL table directly doesn't really make sense when you can use Lucene but not everyone understands or implements Lucene correctly so we need to have both.

**Comment by sebastienros** [comment]
Don't we have all of these already in `ContentItemIndex` ?

It won't rely on the json at all, and it will be super fast. It already has sql indexes on its columns.

Also there is a recently added feature that allows us to create custom document table for specific objects, so not all documents are stored in the same table. You might want to use it.

**Comment by themattkenney** [comment]
@Skrypt Lucene makes sense for search but for standard listing pages these don't use Lucene do they? 

@sebastienros I was not aware of these. Let me do some looking. Will that help out standard listing pages /Admin/Contents/ContentItems?

**Comment by deanmarcussen** [comment]
> @sebastienros I was not aware of these. Let me do some looking. Will that help out standard listing pages /Admin/Contents/ContentItems?

The `ContentItemIndex` is already used for a standard listing (and subsequent filtering)

By default a standard `/Admin/Contents/ContentItems` will perform a join on the `Document` table and the `ContentItemIndex` to return the top 10 records essentially. 

The JSON has to come back so we can build a `SummaryAdmin` view, but JSON returned is only for the top 10 records (or whatever the page size is set to).

If you are getting recommendations/warnings from AppInsights, normally they would include suggested indexes to be added to the `ContentItemIndex` table. (an Index on an Index table is hard to name correctly, but see here for some comments https://github.com/OrchardCMS/OrchardCore/issues/6966)

I would be interested to see those recommendations from AppInsights if you have any, as they maybe of use for an eval of https://github.com/OrchardCMS/OrchardCore/issues/6966

**Comment by giannik** [comment]
> Also there is a recently added feature that allows us to create custom document table for specific objects, so not all documents are stored in the same table. You might want to use it.
@sebastienros  can you give an example inside code or when this was introduced. ? Would like to use this feature.

**Comment by sebastienros** [comment]
We don't use it yet in OC.

You can call `session.Save("someCollectionName")` as long as your migration has created a new Collection. 

Creating a collection:
https://github.com/sebastienros/yessql/blob/dev/test/YesSql.Tests/CoreTests.cs#L90

Creating the index tables for a collection:
https://github.com/sebastienros/yessql/blob/dev/test/YesSql.Tests/CoreTests.cs#L156-L159

Registering an index for a collection:
https://github.com/sebastienros/yessql/blob/dev/test/YesSql.Tests/CoreTests.cs#L66

Saving in a collection:
https://github.com/sebastienros/yessql/blob/dev/test/YesSql.Tests/CoreTests.cs#L3032

Querying:
https://github.com/sebastienros/yessql/blob/dev/test/YesSql.Tests/CoreTests.cs#L3037

**Comment by giannik** [comment]
Ok, Cool. I was thinking maybe the upcoming audit trail module would be using this feature to log entries.
Or maybe a comments module would be a good candidate.

**Comment by sebastienros** [comment]
@domonkosgabor can you check this feature and see if you can use it with audit trails?

**Comment by Piedone** [comment]
That would be interesting, we actually thought about it a while ago.

**Comment by Piedone** [comment]
There doesn't seem to be much of a need for this now. As elaborated above, most of this can be achieved currently already.
