### ISSUE TITLE
Module template for building custom authentication providers

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#7091]
Could you make a `dotnet new` template for building custom authentication providers like LinkedIn?

Comparing to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers, which I contributed to, there are already lots of samples so that you copy it and adjust for the particular provider.
But here the 3 providers in Orchard have lots of features. While I would start from something simple first to make it work just for auth and maybe then adding more features...

**Comment by sebastienros** [comment]
@MichaelPetrinolis

**Comment by MichaelPetrinolis** [comment]
@xperiandri I would copy the OrchardCore.Microsoft.Authentication project, keep the Microsoft Account authentication related code, and modify it as needed. I don't see the necessity for a dotnet new template.

**Comment by sebastienros** [comment]
I agree that making a template wouldn't be really helpful. At least start from an existing module.
Would be good if someone could create a blog post describing how to build a new one.
