### ISSUE TITLE
Hit a Limitation on content items

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#7099]
Hi Folks, 

This is probably not the case but I'd ask anyway, I have couple of screenshot here, the first one is the familiar content definition the second one is the actual content item, it seems that we're maxing out to 126 items, I know it's an arbitrary limit, I'm thinking maybe its based on bytes. 

![content_type](https://user-images.githubusercontent.com/2730217/93532344-b2e13100-f8f5-11ea-8799-27d2604bcf72.PNG)

Here is where we hit the limit when we add the 127th entry
![add_item_collection](https://user-images.githubusercontent.com/2730217/93532368-c2607a00-f8f5-11ea-90bc-0761922c2084.PNG)

Thank you as always for checking out this issue.

**Comment by jptissot** [comment]
What exception are you having ? Is it a UI exception or when you save ?

**Comment by Skrypt** [comment]
The DOM size is probably too high and making the browser slow down or crash.

**Comment by deanmarcussen** [comment]
Probably this https://github.com/OrchardCMS/OrchardCore/issues/5602 if it's an exception on save

**Comment by webmedia1012** [comment]
> Probably this #5602 if it's an exception on save

I've taken a look at it, and that might be the case, but I will post the actual error, sorry just been bugged down with other stuff. I'll post within today. 

What's the solution on the #5602 issue?

Thank you @deanmarcussen and the team!

-g

**Comment by webmedia1012** [comment]
@deanmarcussen  it's been confirmed that it is same as #5602 issue. Please refer to screenshot below.

![error_limit](https://user-images.githubusercontent.com/2730217/93829924-a3c6ef80-fc23-11ea-9dfa-7a876d9c5257.PNG)

Let me know what's the best workaround.

Thank you!!

**Comment by webmedia1012** [comment]
@deanmarcussen  UPDATE! the #5602 solution worked for now! I guess we'll use this until a new updates comes out regarding this issue. I'm closing this issue.
