### ISSUE TITLE
 javascript module parsing my integers to decimal

### ISSUE THREAD

**Issue by weirdyang** [OrchardCMS/OrchardCore#7108]
Hi
Why is the javascript module parsing my integers to decimals?
integers*
I got a list of objects with integer values
e.g. { "value" : 10 }
when it's parsed using "JSON.parse(property("myValue"))"
 it gets converted to:
"value" : 10.0

**Comment by Skrypt** [comment]
Please show us some repro steps. Looks like a serialization issue but we need to know it's coming from where.

**Comment by captmomo** [comment]
Most basic:

![image](https://user-images.githubusercontent.com/25576022/93871295-ffb37600-fd00-11ea-8a32-21a7a1aa0583.png)

**Comment by captmomo** [comment]
![image](https://user-images.githubusercontent.com/25576022/93871507-515c0080-fd01-11ea-8fba-aa3e864bda5d.png)
```
{
  "id": 10484,
  "workflowId": "4vvn1ezwchxk83q0pvngftx2cy",
  "workflowTypeId": "4mrx117pvck0bzmpdafg186jm0",
  "correlationId": null,
  "state": {
    "LastResult": null,
    "Input": {},
    "Output": {},
    "Properties": {
      "example": {
        "value": 1.0
      }
    },
```

**Comment by Skrypt** [comment]
Ok so it's the Newtonsoft JSON serializer configuration. There was a reason why we do this but I can't remember I will need @sebastienros to comment on this.

**Comment by sebastienros** [comment]
I believe that Jint returns a double all the time, and JSON.NET will always write some decimals for doubles. So maybe a solution would be to use a custom Json.NET converter that would realize it's an integral number, and change the way it's serialized.
