### ISSUE TITLE
Taxonomy Content Type

### ISSUE THREAD

**Issue by l93correia** [OrchardCMS/OrchardCore#7118]
After enabling Taxonomy, a content type (Taxonomy) was created, then I remove the content type and now I can't get again the content type previously created and removed.

**Comment by ns8482e** [comment]
Do you mean you deleted `Taxonomy` Content type after enabling `Taxonomy` feature? 

Enabling Feature creates or updates content definition metadata based on migration version stored for that feature.

After migration runs, Whatever modification you do on content type via admin UI  does not change migration version of that feature, hence disabling and enabling again doesn’t have any effect on deleted content types.

I suggest to not modify feature provided content types
