### ISSUE TITLE
[Question] Azure Media File Explorer Widget

### ISSUE THREAD

**Issue by VJC-NTT** [OrchardCMS/OrchardCore#7122]
I was wondering if there is a widget currently in Orchard core that shows the Azure blob container files in a file explorer view (view/ open) that can be used in the portal? I understand there is one in the admin menu for media, wondering if there is means to adapt it within the portal?

If there is isn't,  1. Can someone point to within GitHub which module I should be looking at?  2. Any thoughts on is there a possibility of adapting it as a widget or reusable element?

**Comment by sebastienros** [comment]
You can already have the media files stored in Azure blob storage. We don't really understand what feature you are asking for.

**Comment by VJC-NTT** [comment]
@sebastienros , I was asking if there is a web based file management/explorer module or widget that can be added to the Orchard CMS that is not limited to the admin module. Is there a possiblity to repurpose the existing module in admin section to behave as a widget to link to other azure storage to for a file explorer view. Thanks.

**Comment by Skrypt** [comment]
Right now I think the Azure Media storage module is made to work with only one configuration which is set on startup of the application by using the appsettings.json file of each tenant and/or globally on the app. It could probably do what you are asking for but that would need some development. Normally when I want to manage different blob storage I simply use external tools. But I can see now where you are going with this request. I'd say that the expert would be @deanmarcussen  and he could tell you more in details.

**Comment by deanmarcussen** [comment]
I still don't really understand what you are asking for.

Do you want a front end view / explorer for the media library?

**Comment by Skrypt** [comment]
Well the media gallery already works in a pop-up right? So it can work as a widget anywhere you require it. Though, what he wants is the ability to switch the Azure Blob Storage configuration on runtime.
