### ISSUE TITLE
Admin user became disabled

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#7125]
Did QA with TryOrchardCore.Web src.
Repro steps:

1. Build SAAS recipe orchard core site
![image](https://user-images.githubusercontent.com/61165619/94000055-49529e00-fd9f-11ea-9d47-dc66e684d49f.png)

2. Login to admin
3. Go to Security - >  users, and edit user you specify on setup
![image](https://user-images.githubusercontent.com/61165619/94000167-743cf200-fd9f-11ea-9ecf-0336ea012bfc.png)

4. Save the user
![image](https://user-images.githubusercontent.com/61165619/94000207-87e85880-fd9f-11ea-93f6-326f97d94a53.png)

User disabled.
![image](https://user-images.githubusercontent.com/61165619/94000245-98003800-fd9f-11ea-8977-a1737ab43c25.png)

**Comment by Skrypt** [comment]
Yep this is a funny one. I did that code. Though you should be able to disable an administrator account but not if it's the last one enabled.

**Comment by Skrypt** [comment]
Ok just tried that. I created a second admin user and I can disable that user. But I can't disabled the current user I'm logged in with. So, I can't disable my own account. So, we need to add a server side check for this because smart people can remove the disabled attribute on the html control to disable the admin account ...

**Comment by Skrypt** [comment]
And I'm looking at your screens and it seems that from that form it should have kept the user as enabled. So, your issue is that you have a custom Handler that sets the User as disabled.

**Comment by vitalybrandes** [comment]
> 
> 
> Yep this is a funny one. I did that code. Though you should be able to disable an administrator account but not if it's the last one enabled.

For sure if you want to disable "yourself" :-)

**Comment by vitalybrandes** [comment]
> 
> 
> And I'm looking at your screens and it seems that from that form it should have kept the user as enabled. So, your issue is that you have a custom Handler that sets the User as disabled.

I agree, looks like that something happen behind the scene, 
the problem is that this this pure code i take from orchard github.
https://github.com/OrchardCMS/TryOrchardCore
I didint make any custom dev...

**Comment by Skrypt** [comment]
You should not be able to disable "yourself" as the "disabled" button is disabled 🤣

**Comment by Skrypt** [comment]
Hmm TryOrchardCore maybe needs an update 😉

**Comment by vitalybrandes** [comment]
> 
> 
> Hmm TryOrchardCore surely needs an update 😉
> Report the issue there as I can't repro in the dev branch of this repository

Did you try clean setup?
remove  App_data and recreate it?

**Comment by Skrypt** [comment]
Yes I did a `git clean -xdf` on the folder. Though I did not recreate the database and tenants as it should not really matter.

**Comment by vitalybrandes** [comment]
> 
> 
> Yes I did a `git clean -xdf` on the folder. Though I did not recreate the database and tenants as it should not really matter.

I think it is,
Its happen only for first user in the system,
When i added second admin and sis the same scenario, it was ok.

**Comment by Skrypt** [comment]
Ok doing it.

**Comment by Skrypt** [comment]
Ok I can repro, I understand the issue now.

**Comment by vitalybrandes** [comment]
> 
> 
> Ok I can repro, I understand the issue now.
Nice one :-)

**Comment by hishamco** [comment]
> You should not be able to disable "yourself" as the "disabled" button is disabled

If I'm not wrong I fix this issue in OC, @Skrypt did you reproduce it in OC or try.OC?

**Comment by Skrypt** [comment]
OC

**Comment by hishamco** [comment]
The admin can disable him/her self ;)

**Comment by hishamco** [comment]
I remembered I fix a delete issue not enable/disable user, I can handle this if no one start on it

**Comment by Skrypt** [comment]
The issue is that when the HTML checkbox slider component is set to disable it returns a false value everytime.
We should validate these things on server side to make this bulletproof.

**Comment by hishamco** [comment]
I see, if you didn't start I can have a look and fix it

**Comment by bertalting** [comment]
where can I contact some devs of OrchardCore about a privilege escalation that I have found...

**Comment by Skrypt** [comment]
//cc @sebastienros

**Comment by bertalting** [comment]
> //cc @sebastienros

Thanks, reported and acknowledged by dev.
