### ISSUE TITLE
Full Text Index for Widgets/Bag Items

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7128]
For pages that are built with a BagPart or a Widget what would be the best approach to include the content of these Contained Items in the FullTextIndex?

I have a rudimentary BodyAspect handler working which looks for all HtmlFields inside the BagPart content items, but it has limitations.

Principally with this rudimentary approach, only HtmlFields are covered, so titles / captions for media fields (which in this case are textfields, and I could include, but haven't at this stage).

The two options I'm seeing is
- What I have which has limitations 
- Calling BuildDisplay on all the ContentItems contained, and executing these shapes into an HtmlContentBuilder

BuildDisplay is going to potentially end up giving me a lot of html tags / theme related output, but it was also mentioned that we're stripping html tags before they go into the lucene index?

The key issue here is that as the pages are built from many contained content items, they don't have a standard html body to build an aspect from.

/cc @Skrypt

**Comment by Skrypt** [comment]
What you mean by limitations?

**Comment by deanmarcussen** [comment]
I think I probably need to be calling recursive fulltextaspects on each content item in the bags so I can take advantage of the liquid templating for custom index fields on each of the content types inside the bag.

The limitation is that the bags have more than just html fields, sometimes nested bags, but I think recursive fulltextaspects will sort it.

Will see tomorrow

**Comment by Skrypt** [comment]
I thought you meant that you we're hitting some performance bottleneck but yes using the FullTextAspect on each content items inside the bags should be the way to go. This way it is configurable and each content item should already be indexed unless it's broken. @hswami did that part where we index the bagparts. I will let you work on it and take a look when you push some draft PR.

**Comment by Skrypt** [comment]
Also after thinking about this twice. There is probably no need to create an indexation on something already indexed. Probably what you need is a proper custom ElasticSearch Query unless we are missing some parts which needs to be added to the index.

**Comment by deanmarcussen** [comment]
ok, so got this working.

Yes the BagParts are indexed, but not as part of the `FullText` index.

So it's either add a lot of fields to the default search index settings for all the bag parts or ...

Have a liquid filter for the `FullTextAspect` so that in the `CustomFullText` settings we can do
```
{% for contentItem in Model.Content.BagPart.Contentitems %}
  {{ contentItem | full_text_aspect }}
{% endfor %}
```

**Comment by hswami** [comment]
Dean, that would be a useful feature to have. I don't know what it would take to add it but I'm sure it can be figured out. Do you want to take a crack at it or would you prefer I do?

**Comment by sebastienros** [comment]
I think you can just iterate over each bag part item in the custom full text configuration, the one using Liquid.
