### ISSUE TITLE
Allow Logout Endpoint not "Checked" in the Admin Dashboard even though when specifying "AllowLogoutEndpoint": true in the recipe

### ISSUE THREAD

**Issue by AngularAdvisers** [OrchardCMS/OrchardCore#7132]
Allow Logout Endpoint not "Checked" in the Admin Dashboard even though when specifying "AllowLogoutEndpoint": true in the recipe.

```
    {
      "DisplayName": "Authorization Code Flow",
      "name": "OpenIdApplication",
      "ClientId": "client_id",
      "AllowLogoutEndpoint": true,
      "AllowAuthorizationCodeFlow": true,
      "RedirectUris": "https://localhost:4200/signin-callback",
      "PostLogoutRedirectUris": "https://localhost:4200/signout-callback",
      "Type": "public"
    }
```

<img width="911" alt="BUG-OIDC-001" src="https://user-images.githubusercontent.com/54124010/94088535-ef1d0180-fdcd-11ea-8695-9e207288ce02.png">
Allow Logout Endpoint not "checked"

<img width="911" alt="BUG-OIDC-002" src="https://user-images.githubusercontent.com/54124010/94088599-1d9adc80-fdce-11ea-9369-1281c8833387.png">
Once "Allow Logout Endpoint" is checked the "Post Logout Redirect Uris" is displayed.  
 The recipe setting "AllowLogoutEndpoint": true, should enable "Allow Logout Endpoint" in the Admin Dashboard OpenID Connect Edit an application settings.

**Comment by kevinchalet** [comment]
Thanks for your report. https://github.com/OrchardCMS/OrchardCore/pull/7135 should fix it.
