### ISSUE TITLE
F# IStringLocalizer Compatibility for AdminMenus?

### ISSUE THREAD

**Issue by willnationsdev** [OrchardCMS/OrchardCore#7134]
I wanted to try making a basic AdminMenu in an F# module; However, I discovered that when I create an AdminMenu that implements INavigationProvider, if I inject an IStringLocalizer into the class, then activating the module suddenly removes all menu items from the admin menu.

```fsharp
namespace TestModule

open System
open System.Threading.Tasks
open Microsoft.AspNetCore.Builder
open Microsoft.Extensions.DependencyInjection
open OrchardCore.Modules
open OrchardCore.Navigation

// If I don't inject this IStringLocalizer, the menu items appear just fine.
// WITH it, they all vanish, even though the sidebar is still expandable/collapseable.
type AdminMenu(S: IStringLocalizer) =
    interface INavigationProvider with
        override __.BuildNavigationAsync(name, builder: NavigationBuilder) =
            Task.Completed

type Startup() =
    inherit StartupBase()

    override __.ConfigureServices(services) =
        services.AddScoped<INavigationProvider, AdminMenu>()

    override __.Configure(builder, routes, serviceProvider) =
        builder
            .UseRouting()
            .UseAuthorization()
        |> ignore
```

Before enabling the module:
![adminmenu_istringlocalizer_before_edited](https://user-images.githubusercontent.com/16217563/94198300-aec88c80-fe7c-11ea-87ea-eef29c7343a2.png)

After enabling the module:
![adminmenu_istringlocalizer_after_edited](https://user-images.githubusercontent.com/16217563/94198328-b7b95e00-fe7c-11ea-94d2-a847686e3d14.png)

This obviously has something to do with the fact that it's an F# language difference, and I'm not even sure if catering to F# users is something you even want to bother supporting, but I figured I'd ask. So, if the answer to this is just "OC is for C#. Use that," then so be it. Personally, I'm interested, long-term, in developing an alternative F# API that can interact with and support everything that Orchard Core does.

Edit: Also, I've tried actually adding menu items to the `builder`, but that appears to be irrelevant to the issue at hand.

**Comment by sebastienros** [comment]
Can you provide the C# equivalent classes just to be certain it's not a bug, or wrong usage?

**Comment by deanmarcussen** [comment]
You can't just inject `IStringLocalizer` like that in C# or F# as it is constructed via a factory.

It would typically be `IStringLocalizer<T>` or IStringLocalizer<AdminMenu>`  in C#.

If you look in your log file you will see the exception.

**Comment by willnationsdev** [comment]
@deanmarcussen Ah, sure enough, it was just a stupid user error like that. -_- Welp! Good to know. Thanks!
