### ISSUE TITLE
Bug: there's no editor-toolbar on fullscreen

### ISSUE THREAD

**Issue by ReddewYoung** [OrchardCMS/OrchardCore#7139]
There's no editor-toolbar on fullscreen.

![](https://www.reddewyoung.com/media/images/no-toolbar-bug.png)

**Comment by deanmarcussen** [comment]
Very unclear what you are reporting.

If you have an image drag it onto a comment.

If not, please provide repro steps and an explanation of the issue.

**Comment by ReddewYoung** [comment]
I've updated. @deanmarcussen

**Comment by hishamco** [comment]
@ReddewYoung seems you update the other issue not this one ;)

**Comment by ReddewYoung** [comment]
> @ReddewYoung seems you update the other issue not this one ;)

That's the issue, but failed to upload image due to the network...
