### ISSUE TITLE
Bug: both <- and -> will back to categories or tags

### ISSUE THREAD

**Issue by ReddewYoung** [OrchardCMS/OrchardCore#7140]
Both <- and -> will back to categories or tags.

![](https://www.reddewyoung.com/media/images/page-bug.png)

**Comment by deanmarcussen** [comment]
Very unclear what you are reporting.

If you have an image drag it onto a comment.

If not, please provide repro steps and an explanation of the issue.

**Comment by ReddewYoung** [comment]
I've updated. @deanmarcussen
