### ISSUE TITLE
Front page display all content localization

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#7143]
If a content has localized version, all localized content will be displayed in the frontend.

# in admin
![image](https://user-images.githubusercontent.com/3222379/94330357-63d28480-fff6-11ea-8350-0fa57f5903bb.png)

# in front with `The Default Theme` Theme ( Home page or categories page)
![image](https://user-images.githubusercontent.com/3222379/94330333-37b70380-fff6-11ea-80e6-45c2c82608b7.png)

**Comment by hishamco** [comment]
Strange!! @RockNHawk which version you are using?

One more thing is this happening with `BlogPost` or any other content types?

**Comment by RockNHawk** [comment]
> 奇怪！！@RockNHawk您正在使用哪个版本？
> 
> `BlogPost`或其他任何内容类型正在发生另一件事？

I use latest dev version.
Yes, it happening with `BlogPost`,

**Comment by deanmarcussen** [comment]
You need to localize the `Blog` not the `BlogPost`

**Comment by RockNHawk** [comment]
@deanmarcussen 

> You need to localize the `Blog` not the `BlogPost`

So there is no relationship between the two posts, just like two `Blog` ?

**Comment by sebastienros** [comment]
> So there is no relationship between the two posts, just like two Blog ?

Exactly.

When you localize a blog, all its posts are also cloned in the target language. But posts don't relate to each others. This is the current behavior with lists. The idea is that you can have posts in each language without having to translate them.

You need to create two blogs.

**Comment by jptissot** [comment]
I thought I had handled this case. I forget exactly what was the behavior but I am pretty sure You could have Localized BlogPosts within a single Blog.
