### ISSUE TITLE
Possible bug when cloning content item

### ISSUE THREAD

**Issue by szilardcsere89** [OrchardCMS/OrchardCore#7145]
I want to clone a ContentItem by overwriting a property in a ContentPart when cloning, so I created a ContentPartHandler. Once the new item is created, all properties will be empty.

```
public override Task CloningAsync(CloneContentContext context, CustomPart part)
{
    context.CloneContentItem.Alter<CustomPart>(clonedPart =>
    {
        clonedPart.CustomProp += "<p>cloned</p>";
    });

    return Task.CompletedTask;
}
```

**Comment by deanmarcussen** [comment]
Code looks fine.

Can you supply the JSON of the content item before cloning and after cloning. And try without altering the ClonedPart to isolate if it related to the code, or cloning itself?

**Comment by szilardcsere89** [comment]
Sure.

Before:
![image](https://user-images.githubusercontent.com/5823033/94339289-2d4a3900-fff9-11ea-95e8-8f64fa30b4a7.png)

After:
![image](https://user-images.githubusercontent.com/5823033/94339303-4fdc5200-fff9-11ea-9f8f-1f685a55dffd.png)

Without altering works fine.

**Comment by deanmarcussen** [comment]
Because it uses a DeepClone the value of `CustomPart` might not been in the elements dictionary.

You may have to copy those other properties from your `ContentPart` when altering during clone.

You might need to get read the original values from `CloneContentItem.Content.CustomPart`

**Comment by szilardcsere89** [comment]
Okay, but it would be worth writing a comment about it somewhere
