### ISSUE TITLE
Feature: Theme setup recipe

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#715]
May be I am a little too optimistic about the technical feasibility but here is the description of what I would love to be able to do when I install a theme:

- Allow to execute a 'setup' recipe in Theme.
	- Include parameterized steps in which you retrieve informations that are passed to execution.
- Create Content type and data.
	- Detect if Content type already exists.
- Enable dependent modules and features
	- About page
	- Blog
		- RSS Feed
	- Comments: Disqus
	- Contact form
- Initialize settings, configure custom parameters.
	- Analytics: Google
	- Contact page: Email, Address
	- Image: Upload Avatar, Logo
	- Social media: Twitter, Linkedin
	- Theme: Layout, Menu, Widgets

Are some of those customizations possible with the setup wizard #495 that @jersiovic is developing and configurable when you select a theme?

Or could it be done by independent small recipes in each module?

**Comment by sebastienros** [comment]
Not crazy at all.
It's also related to the other issue I made to allow parameters in recipes. Two solutions: 
- describe which properties we need from the recipe and let the setup build the ui
- provide a driver and shape template for the setup explicitly

Either way you can then run you own recipe that will take these parameters into account.
Also the Setup module exposes custom events that any module/theme can intercept. Many already do it.

If you meant from the admin and not from the Setup, then it's still doable, we need to expose recipes from all modules, like we do in O1, and make the same UI extensibility.

**Comment by jersiovic** [comment]
I think the driver and shape template approach is better cause it is more powerful than let setup build the ui and neither require any extra knowledge to use it nor having to develop and maintain specific code for every new parameter type we need.
@agriffard this approach https://github.com/OrchardCMS/Orchard2/issues/716 pointed by @sebastienros maybe is the most sensible for implementing it.
Related to the Setup wizard issue I'm going to close the PR as I have commented here: https://github.com/OrchardCMS/Orchard2/issues/495#issuecomment-295924108

**Comment by agriffard** [comment]
As most recipes are now in themes, it would be interesting to allow to execute a recipe from the themes admin page but this execution should be able to check if a Content type has previously been created and prevent to override it.
