### ISSUE TITLE
Filter/search feature for Templates and List Part too

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#7152]
We have this feature on the general content item list on the admin:
![mhildnaamkhnpkih](https://user-images.githubusercontent.com/1976647/94434396-037c4800-019a-11eb-91d9-5911170773e1.png)

The idea here is to make this available in the Templates list as well as List Part lists (like when opening the Blog as created by the Blog recipe). This would then similarly filter/search only among templates and only among the items of the currently opened item with List Part, respectively.

I'd do this in the same extensible way as it is with the Contents list, i.e. something like an `IContentsAdminListQueryService` with contributing providers. The Templates and Lists modules could also use that directly but that would necessitate a hard dependency.

What do you think? We could probably work on this.

**Comment by agriffard** [comment]
These links are more like 'quick filters' so the redirection urls with their parameters actually have to be handled by the controller.

They are not like the filters added by the IContentsAdminListQueryService that you mention but if you think you can provide an extension to manage them, go ahead.

**Comment by Piedone** [comment]
Thanks for your quick feedback!

Yeah, so without using `IContentsAdminListQueryService` directly `TemplateController` would need to do the same as `OrchardCore.Contents.Controllers.AdminController`. List Part already depends on the Contents list in a way now I see.

**Comment by deanmarcussen** [comment]
> List Part already depends on the Contents list in a way now I see

No this is handled by the View / Driver for Summary Admin - currently the same service is used for the front end and backend display/query

It would be nice to have filters on the `ListPart`, if you're going to work on it.

You'd just need to use a different service method for the query, and bind all the query params at driver level.

It should stay independant of the contents list / contents list filters.

There was originally a list query filter for the content items list when I refactored the query filtering, so I left it in. But it behaves differently to the driver view, which gives you the ability to create list items with that view.

Re: the template controller, again it would need to be different as it's not a Query as such that is producing the result, just a filter on the single document which has all the templates. (so actually easier)

**Comment by agriffard** [comment]
See also #5349 for the List UI.

**Comment by Piedone** [comment]
So in the end, let's basically mimic what this filter does in the two features, adapted to how they work already?

**Comment by micrub-it** [comment]
Hi Piedone, this function would be very interesting for me! News about its implementation?
Thank you very much

**Comment by Piedone** [comment]
We'll be ready with it in a few days.
