### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#7157]
I will enforce 2FA for the OrchardCMS org.
These users need to enable it or will automatically be removed from the org:
@Skrypt @hishamco @MatteoPiovanelli-Laser @jersiovic @jrestall

**Comment by hishamco** [comment]
Done from my side

**Comment by Skrypt** [comment]
Waiting on the sms

**Comment by Skrypt** [comment]
done

**Comment by MatteoPiovanelli-Laser** [comment]
done
