### ISSUE TITLE
Multiple menus

### ISSUE THREAD

**Issue by 4m-world** [OrchardCMS/OrchardCore#7159]
I'm building a new business template for Orchard, and one of the templates features having multiple menus on the page.
Main Menu,  and Footer menus

I'm facing following issue, when I try to render footer menu it takes the alternate of the menu container, while it ignores menu item alternates.
`{% shape "menu", alias: main_menu_name_alias, alternate: "MenuFooter" %}`

and MenuItem alternate file name as per documentations:
MenuItem-MenuFooter.liquid

In the shap_render it renders MenuIte.liquid

Main Menu render syntax:
`
{% assign main_menu_name = "main-menu-" + Culture.Name %}
{% assign main_menu_name_alias = "alias:main-menu-" + Culture.Name %}
{% shape "menu", alias: main_menu_name_alias, cache_id: main_menu_name, cache_tag: main_menu_name_alias %}
`

Footer menu code:
`
<ul>
	{% for item in Model.Items %}
	{% shape "menuItem", alternate: "MenuItemFooter" | shape_properties: Model: item %}
	{% endfor %}
</ul>`

Main menu:
`
<nav class="nav-menu d-none d-lg-block">
	<ul>
		{% for item in Model.Items %}
		{{ item | shape_render }}
		{% endfor %}
	</ul>
</nav>
`

MenuItem:
`
<li {% if Model.HasItems %}class="drop-down"{% endif %}>
	
	{% shape_type Model "MenuItemLink" %}
	{{ Model | shape_render }}
	{% if Model.HasItems %}
	<ul>
	{% for item in Model.Items %}
	{{ item | shape_render }}
	{% endfor %}
	</ul>
	{% endif %}
</li>
`

**Comment by jtkech** [comment]
Hmm, not sure but try `alternate: "Menu__Footer"` with a `Menu-Footer.cshtml` file,
and `alternate: "MenuItem__Footer"` with a `MenuItem-Footer.cshtml` file

**Comment by 4m-world** [comment]
> Hmm, not sure but try `alternate: "Menu__Footer"` with a `Menu-Footer.cshtml` file,
> and `alternate: "MenuItem__Footer"` with a `MenuItem-Footer.cshtml` file

It does not work it keep render the original shape

**Comment by 4m-world** [comment]
I resolved the issue by amending the Menu-Footer with the below code, and it took me some time to figure since this point is not clear in the documentation. I would like to suggest adding real code samples to documentation.

`<ul>
	{% for item in Model.Items %}
	### {% shape_add_alternates item "MenuItem__Footer" %}
	{{ item | shape_render }}
	{% endfor %}
</ul>`

**Comment by hishamco** [comment]
@4m-world you can update the docs if it's worth

**Comment by VJC-NTT** [comment]
@4m-world , I am trying out a similar setup, is there any possibility of sharing your solution? I called my other menu as innermenu

{% shape "innermenu", alias: "alias:smartitanalytics", cache_id: "smartitanalytics", cache_tag: "alias:smartitanalytics" %}

however I am unable to render the innermenuitem, despite following your notes and the cryptic documentation on the orchard core site. In the innermenu, I was trying to link the innermenuitem as 

 ```          {% for item in Model.Items %}
            {% shape_add_alternates item "MenuItem__InnerMenu" %}
            {{ item | shape_render }}
            {% endfor %}


Could you share the liquid syntax of how it should be invoked? Thanks  in advance!
