### ISSUE TITLE
Provide generic classes for providing a driver and shape template for an entity class

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#716]
After spent time working on a PR for developing this feature https://github.com/OrchardCMS/Orchard2/issues/495#issuecomment-272035823 using a simple approach I find limitations of that approach. 
Talking with @sebastienros he pointed we can provide a driver and shape template for the setup explicitly. As he also has commented today here https://github.com/OrchardCMS/Orchard2/issues/715#issuecomment-295786814

The point is it is sth very similar to what has been done in Orchard.Settings module. So, @sebastienros suggested it would be useful to refactor that module to provide a generalization that allows composition through shape templating for any entity we need. In that way we can use it for Orchard.Settings, for Orchard.Setup  and for other future uses.

This issue is for implementing that generalization

**Comment by xperiandri** [comment]
So what to do and where?
Who can provide links to source code lines/file and task definition?

**Comment by sebastienros** [comment]
This has been implemented. See `Entity.cs` and also Workflow which uses it.
