### ISSUE TITLE
Bug: no editor-toolbar in Markdown editor fullscreen mode

### ISSUE THREAD

**Issue by ReddewYoung** [OrchardCMS/OrchardCore#7160]
Bug: no editor-toolbar in Markdown editor fullscreen mode.

![](https://www.reddewyoung.com/media/images/no-toolbar-bug.png)

[Screenshot](https://www.reddewyoung.com/media/images/no-toolbar-bug.png)

**Comment by hishamco** [comment]
Did you refresh your browser? perhaps some styles and scripts not loaded properly
