### ISSUE TITLE
Bug: tags/categories pagination not working

### ISSUE THREAD

**Issue by ReddewYoung** [OrchardCMS/OrchardCore#7161]
Bug: tags/categories pagination not working.

![](https://www.reddewyoung.com/media/images/page-bug.png)

[Screenshot](https://www.reddewyoung.com/media/images/page-bug.png)

**Comment by Piedone** [comment]
Since the screenshot point to a dead link, I can't confirm, but Taxonomies paginations seems to be working fine for me now.
