### ISSUE TITLE
Razor cshtml changes not reflecting in browser from Module app 

### ISSUE THREAD

**Issue by nsathiyamoorthi** [OrchardCMS/OrchardCore#7166]
We have 2 web application one is the shell and other one is the module. Both has the nuget package "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" installed to ensure the changes done on the cshtml files are reflected in browser on refresh. The changes done on cshtml pages in main webapplication is working as expected but the changes done on cshtml pages in module application is not.

Please advice.

**Comment by jtkech** [comment]
Here there are many scenarios, show us your application and module project files.

Also, do you want runtime compilation only in a `Development` environment, as it can be specified through the `ASPNETCORE_ENVIRONMENT` env variable, or also in a `Production` environment.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
