### ISSUE TITLE
Upgrade Font Awesome to version 5.15.0

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7177]
https://www.npmjs.com/package/@fortawesome/fontawesome-free

- Upgrade the version in the package.json in OrchardCore.Resources module.
- Run `npm install` in the root folder.
- Run `gulp rebuild` to regenerate the files.
- Only include the modified files related to font-awesome.
- Update the resources in the ResourceManifest.
- Change the `sha...` (You can use https://www.srihash.org/ to generate them from the new urls)
- Change version in the docs Readme: https://docs.orchardcore.net/en/dev/docs/reference/modules/Resources/#named-resources

**Comment by Rajdeepc** [comment]
@agriffard  I would like to contribute to this

**Comment by agriffard** [comment]
ok, @Rajdeepc you can fork the project, make the changes and create a PR targetting the dev branch.

**Comment by Rajdeepc** [comment]
@agriffard Thanks

**Comment by agriffard** [comment]
Fixed by #7181
