### ISSUE TITLE
Role Recipe do not update description

### ISSUE THREAD

**Issue by hung-doan** [OrchardCMS/OrchardCore#7179]
## Problem
**Actual**: The `Roles` step do not add/update the Role Description
**Expect**: The `Roles` step should add/update the Role Description

## About OC
- OC Version: 1.0.0-rc2-14350

## Steps
```json
    {
      "name": "Roles",
      "Roles": [
        {
          "Name": "LB Editor",
          "Description": "LB Editor Description",
          "Permissions": [
            "AccessAdminPanel",
            "EditOwnContent",
            "EditContent",
            "PublishOwnContent",
            "PublishContent",
            "DeleteOwnContent",
            "DeleteContent",
            "CloneContent",
            "CloneOwnContent",
            "ManageOwnMedia"
          ]
        }
      ]
    }
```

![image](https://user-images.githubusercontent.com/11371581/94755188-d8723e00-03bd-11eb-9929-8ad152c2d829.png)

**Comment by hishamco** [comment]
Thanks @hung-doan for reporting this

Can you provide a PR for it?

**Comment by NogginBox** [comment]
I've got a potential fix for this, but wanted to clarify the behavior when a role with that  name already exists.

So if the role exists:

- Should we give the existing role the recipe role description?
- If the recipe has a description, should we overwrite the existing role description with the recipe role description
- If the recipe role has no description and our existing role does, should we delete the existing role's description.

My preference would be to always use the recipe role description, unless it doesn't have one, in which case leave the original description. What do people think?

**Comment by deanmarcussen** [comment]
Great!

The recipe should be the source of truth.

So if it has a description, it should use it, if it doesn't, or the description is empty, it should overwrite the description with the empty one.

As a site progresses the recipes will tend to be produced by deployment plans which will contain whatever is present on the source system, in terms of roles and role descriptions.

There are cases with content items, where we merge properties, but for this step the behaviour should be kept simple.

**Comment by NogginBox** [comment]
Fix is in the PR above. Very simple now recipe is always the source of truth.

**Comment by hung-doan** [comment]
Cool, thanks @NogginBox  for the fix.

@hishamco sorry mate, I would want to contribute to the development, but I'm busy in this period to dive into the code base. Will contribute by posting more bug/issue that I found during working with the OC 😃
