### ISSUE TITLE
FormPart - Add wrapper for content type

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#7180]
`FormPart` is rendered using `Form.Wrapper.cshtml` for all content type containing `FormPart` 

Add wrapper in driver to allow customize form per content type.  

i.e. The custom Form content type  `SignupLead` containing `FormPart` can have shape template `Form-SignupLead.Wrapper.cshtml`.  where developer can provide custom form processing without affecting default implementation for `Form` content type or any other content type containing `FormPart`.

https://github.com/OrchardCMS/OrchardCore/issues/6326#issuecomment-670632804

**Comment by deanmarcussen** [comment]
Also the standard `Form.Wrapper` should read from `Model.Classes` and apply any classes added to the form element. 

and the `ContentItemDisplayManager` can be removed from the template as it is unused.

**Comment by ns8482e** [comment]
> Also the standard `Form.Wrapper` should read from `Model.Classes` and apply any classes added to the form element.

`Model.Classes` are rendered using Widget template.. https://github.com/OrchardCMS/OrchardCore/blob/f5abff87e69851d793f9ae17c27b28f571bbc060/src/OrchardCore.Modules/OrchardCore.Widgets/Views/Widget.cshtml#L1

**Comment by deanmarcussen** [comment]
Different shape, different classes.

The `Form.Wrapper` gets in the way of row/col arrangements (a lot), and needs to be overridden just to get something simple like a col class on it.
 
Which is unnecessary, and annoying. 

If it also read from it's own Model.Classes, then the template as it stands currently would be more useful.

**Comment by ns8482e** [comment]
It's just a wrapper around `ContentItem` and share same `Shape` object.

**Comment by deanmarcussen** [comment]
Don't worry about it @ns8482e we're talking about different things. I'll put a pr in for my request when I have the time. Carry on with the alternates.
