### ISSUE TITLE
Reveal password on setup screen has javasacript null error

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7188]
Latest dev @Skrypt 

![Screenshot 2020-10-02 at 13 32 14](https://user-images.githubusercontent.com/13782679/94923461-cd99d500-04b3-11eb-9dc6-95a335aa516e.png)

and the one on the login screen is looking totally different - but working ;)

![Screenshot 2020-10-02 at 13 38 55](https://user-images.githubusercontent.com/13782679/94924016-ad1e4a80-04b4-11eb-9b55-86bc3ec7bf83.png)

Could it be a grey border instead of the black border around it? 

to match the borders around the inputs`#ced4da`

**Comment by Skrypt** [comment]
Nooo way, the guy who did this is sooo bad 👎
