### ISSUE TITLE
Timer Event Activity which accepts liquid input

### ISSUE THREAD

**Issue by weirdyang** [OrchardCMS/OrchardCore#7192]
Hi,
from the discussion [here](https://github.com/OrchardCMS/OrchardCore/discussions/7136)

I would like to suggest a new Event which allows users to schedule a task by passing in a Date Time. It is similar to the timerEvent, except that it accepts liquid input and string.

for example:
 I would like to do a post with a date string and be able to schedule a task. The current timer event does not accept a liquid input.
```csharp
 I do  a http post with body:
{
    "TargetTime": "02-10-2020 10:00:55";
}
```
 I can set it to a property (e.g. "TriggerDate"), which I can use to schedule a task with {{ Workflow.Properties.TriggerDate}}

This is my current implementation:
https://github.com/weirdyang/OrchardCore.Olaf/blob/main/OrchardCore.Olaf/Delay/DelayEvent.cs

**Comment by sebastienros** [comment]
I am not familiar with TimerEvent. Could it be so close that we only need to change TimerEvent to accept a liquid string instead of a date value?

**Comment by sebastienros** [comment]
I looked at the TimerEvent. So yes it's different and it can be separate. The descriptions should clearly mention the differences.

**Comment by weirdyang** [comment]
Great, thanks.
