### ISSUE TITLE
HtmlBody Doesn't show The Editor in RTL dir

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#7200]
regarding to [@7007](https://github.com/OrchardCMS/OrchardCore/issues/7007) i found the issue in rtl direction. it doesn't work in persian directin.

![1111](https://user-images.githubusercontent.com/56995550/94988752-e36cd000-056f-11eb-9ba6-95688e9f7b74.JPG)

this error just appear in rtl direction culture.

**Comment by hishamco** [comment]
Is this happen on the dev branch?

**Comment by overstartup** [comment]
I'm  using NuGet references 
  ```
  <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc2-14627" />
    <PackageReference Include="OrchardCore.Logging.Serilog" Version="1.0.0-rc2-14627" />
```

**Comment by hishamco** [comment]
Could please check the latest bits instead because sometimes is happen during a regression

**Comment by overstartup** [comment]
what is the latest? it looks I'm using the latest version.

**Comment by hishamco** [comment]
What I mean is try the to run the latest source from this repo

**Comment by deanmarcussen** [comment]
@overstartup which two letter language code are you using?

This code will fail if trumbowyg does not include the language you are using. 

https://github.com/Alex-D/Trumbowyg/tree/develop/src/langs

It does not include all langs, so we might need to null check this better.

```
        @if (culture.GetLanguageDirection() == LanguageDirection.RTL)
        {
            <text>        
            var langs = jQuery.trumbowyg.langs.@culture.TwoLetterISOLanguageName;
            langs['_dir'] = '@culture.GetLanguageDirection()';
            </text>
        }
```

**Comment by overstartup** [comment]
> @overstartup which two letter language code are you using?
> 
> This code will fail if trumbowyg does not include the language you are using.
> 
> https://github.com/Alex-D/Trumbowyg/tree/develop/src/langs
> 
> It does not include all langs, so we might need to null check this better.
> 
> ```
>         @if (culture.GetLanguageDirection() == LanguageDirection.RTL)
>         {
>             <text>        
>             var langs = jQuery.trumbowyg.langs.@culture.TwoLetterISOLanguageName;
>             langs['_dir'] = '@culture.GetLanguageDirection()';
>             </text>
>         }
> ```

sorry for reply late. 
I'm using persian (fa) fa-ir culture.

**Comment by Skrypt** [comment]
Yes as far as I can remember the Trumobwyg editor doesn't support all cultures.
It might be related to that.

**Comment by hishamco** [comment]
@overstartup please check you download the Persian translation, but this will affect on the texts that are display on the Trumbowyg, AFAIK the RTL is already supported

If there's specific thing related to RTL, please clarify, so I can provide a clear answer

**Comment by Skrypt** [comment]
You will probably need to copy this file https://github.com/Alex-D/Trumbowyg/blob/develop/src/langs/fa.js and name it fa-ir

**Comment by hishamco** [comment]
Exactly, this will localize the Trumbowyg

**Comment by overstartup** [comment]
@hishamco @Skrypt  i'm sorry to coming back late.
i tested it with Arabic (ar) and Persian (fa) it has the same issue.
i seem the issue with all HTML Editors types happen.


> You will probably need to copy this file https://github.com/Alex-D/Trumbowyg/blob/develop/src/langs/fa.js and name it fa-ir
@Skrypt where i should put this file?

**Comment by hishamco** [comment]
This is an old issue Ahmad ;) could you please write down the steps to reproduce (in details)

**Comment by Piedone** [comment]
This has since then been fixed.
