### ISSUE TITLE
Task create button could not be found in Admin UI

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#7229]
![image](https://user-images.githubusercontent.com/491759/95461573-f5ec6c80-09a8-11eb-92c7-5cd88f8422c0.png)

I use the OrchardCore package from Nuget, the version is 1.0.0-rc2-13450

I checked the source code and saw that the BackgroundTask project has create/edit views. So I think it should be created using the Admin UI. But it can't be found yet.

**Comment by rjpowers10** [comment]
I'm using a background task in my project. You have to create your task in code by implementing the `OrchardCore.BackgroundTasks.IBackgroundTask` interface.

[https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Abstractions/BackgroundTasks/IBackgroundTask.cs](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Abstractions/BackgroundTasks/IBackgroundTask.cs)
