### ISSUE TITLE
Docker: DataProtection-Key not persisted

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#7231]
Hello

I run orchard on docker. I have configured and added Azure Shells Configuration and Configured DataProtection on Azure as described here (https://docs.orchardcore.net/en/dev/docs/reference/modules/DataProtection.Azure/) 

Orchard generates the keys on the blob storage as expected, but in the logs I still get these errors:

```
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
Storing keys in a directory '/app/App_Data/Sites/Default/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Storing keys in a directory '/home/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
```

Is there anything else I need to make in the code to make DataProtection work with azure? Do I need to add the additional nuget from Microsoft and store the dataprotection to the cloud as described here? https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio          

Thanks

**Comment by deanmarcussen** [comment]
Did you use the Data Protection.Azure module / feature ? https://docs.orchardcore.net/en/dev/docs/reference/modules/DataProtection.Azure/

Or configure it directly yourself?

I don't see any errors when using the data protection module.

**Comment by LMSSonos** [comment]
I use the DataProection Azure module as described in the documentation. It also stores the keys on the blob store. But I still get this warning when launching the app in the container.

**Comment by deanmarcussen** [comment]
It may well just be a spurious warning as the data protection module replaces the key container.

Is it possible you have existing keys in the `App_Data/Sites/Default/DataProtectionKeys` folder and are publishing those in your container, and it's catching them?

The way to know for sure that your keys are being managed externally is to restart / replace the container while logged in, and see if you are still logged in (e.g. the cookie is decrypted successfully with the keys from blob storage)

**Comment by LMSSonos** [comment]
Yes it looks like it is a warning when starting the mvc application with orchard. Probably orchard will then replace it afterwards with the keys from the cloud. 

I tested as you described with redeploying the container, the warning was logged but I still was logged in the admin. So thanks for your help
