### ISSUE TITLE
Custom Admin Template Not Working in Decoupled Mode on Azure App Service

### ISSUE THREAD

**Issue by mattobox** [OrchardCMS/OrchardCore#7233]
I used the blank recipe to create my project for decoupled mode. My custom admin template is just a copy of the one from the Orchard Core project. I made a couple of minor tweaks to the login and login-layout pages. This screenshot is a side-by-side of the menus of the two themes.

![image](https://user-images.githubusercontent.com/52262927/95539816-98f2b580-09ac-11eb-80cf-2efc27776feb.png)

When in Visual Studio I don't experience this problem, but as soon as I publish the site to Azure it doesn't load correctly. Am I missing something or is this due to it being in decoupled mode?

**Comment by deanmarcussen** [comment]
From the looks of it you are missing the css files.

Probably this means you need to take a direct reference to the `OrchardCore.ResourceManagement` nuget package in whichever project / module you have used to make your admin theme.

(not totally sure what you mean by template, I assume you mean theme which has templates)

**Comment by mattobox** [comment]
Oyyyyy. That's exactly what it was. I was referencing `OrchardCore.ResourceManagement.Abstractions` instead. Thanks so much!
