### ISSUE TITLE
SQL nvarchar column size

### ISSUE THREAD

**Issue by markgould** [OrchardCMS/OrchardCore#7235]
Is there a particular reason ContentItemId (and related fields) are 26 chars in sql? We're running into an issue where our recipes work fine in sqlite but not in SQL due to the 26 char limitation.

We are now faced with going through our recipe and changing all the content ids. Is it likely this length could be increased at some point? Thanks!

**Comment by hishamco** [comment]
Why it doesn't work with SQLite? If I'm not wrong the Id is generated by OC itself

**Comment by markgould** [comment]
It does work with sqlite, it does NOT work with MSSQL. SQLite does not have limits on text fields, which is why it works. 

This document lists the 26 char limit: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/docs/reference/modules/SQL/README.md

**Comment by hishamco** [comment]
> Is there a particular reason ContentItemId (and related fields) are 26 chars in sql?

https://github.com/OrchardCMS/OrchardCore/blob/569e256b1aeb86c3321c5233562cea19ee94be9c/src/OrchardCore/OrchardCore.Abstractions/IdGenerator.cs#L14

The Generated Id contains 26 chars
