### ISSUE TITLE
Running TheBlog Theme Recipe Removes Built-In Form Feature

### ISSUE THREAD

**Issue by RaisinBread42** [OrchardCMS/OrchardCore#7238]
Would like to do more testing on this to find the full scope and cause of the issue, but don't think I have the knowledge to do that. What I was able to do was, which didn't work:

- Disable and Enable the form feature
- Changing theme (but didn't run the recipe). Slight digress, but would've imagined there would be a feature to undo changes made by recipes ?

**Comment by deanmarcussen** [comment]
The BlogTheme is a setup recipe.

It's not really designed to be run twice, which sounds like what you're doing.

I don't quite understand what the actual issue is regarding the form feature?

Did it just get turned off?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
