### ISSUE TITLE
when users has more than 10,Users pager throw exception

### ISSUE THREAD

**Issue by yiji** [OrchardCMS/OrchardCore#725]
There is a syntax error near 'OFFSET'. The use of option FIRST in the FETCH statement is invalid
var results = await users
                .Skip(pager.GetStartIndex())
               .Take(pager.PageSize)
                .List();

**Comment by sebastienros** [comment]
Which database are you using?

**Comment by yiji** [comment]
SQLSERVER 2008 R2

**Comment by sebastienros** [comment]
Maybe the dialect that is generated is only compatible with a more recent version. I need to think about a way to specify the dialect in the connection string then.

**Comment by sebastienros** [comment]
Looks like the OFFSET keyword was introduced in SQL Server 2012

**Comment by hishamco** [comment]
@sebastienros you can close this after your merge my PR https://github.com/sebastienros/yessql/pull/64 and update the YesSQL libs
