### ISSUE TITLE
Multiple instances of wysiwyg HtmlBodyPart on the same page get an ever increasing number of 'Insert Shortcode' toolbar icons

### ISSUE THREAD

**Issue by Lawyerson** [OrchardCMS/OrchardCore#7252]
Steps to reproduce:

1.  Define a widget content type with an HtmlBodyPart that uses the Wysiwyg editor.
2.  Define a content type with a FlowPart.
3.  Create a new content item of the type defined in step 2 and add multiple instances of the widget defined in step 1 to the flow.
4.  Every new HtmlBody editor on the page will have an additional 'Insert Shortcode' icon compared to the previous one.

The culprit seems to be this line in HtmlBodyPart-Wysiwyg.Edit.cshtml:
`        var defaultButtons = jQuery.trumbowyg.defaultOptions.btns;
        defaultButtons.splice(6, 0, "insertShortcode");`

This should be included by the ResourceManager so that it only runs once for the whole page.

**Comment by hishamco** [comment]
If @deanmarcussen agree with the proposed solution, @Lawyerson could please send a PR

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/7185 and https://github.com/OrchardCMS/OrchardCore/issues/7154

After updating if you have any further issues please reopen @Lawyerson (always possible to miss some)
