### ISSUE TITLE
Custom Error Pages for Decoupled Environment

### ISSUE THREAD

**Issue by mattobox** [OrchardCMS/OrchardCore#7255]
I'm trying to create custom error pages for the various http status codes in a decoupled environment. Does an Orchard Core decoupled environment support this? For example, the 404 page brings up the Orchard Core "NotFound.cshtml" page, but I want to customize the look of this page, potentially for each decoupled module.

`app.UseStatusCodePagesWithReExecute("/Error/{0}");` appears to be ignored.

`app.UseStatusCodePagesWithRedirects("/Error/{0}");` works but requires a redirect and it loses all of the original error information.

**Comment by hishamco** [comment]
Why this is closed, is the issue resolved?

**Comment by Skrypt** [comment]
I don't remember the details but we have OrchardCore.Diagnostics module.

**Comment by hishamco** [comment]
Ya we have a module, so that's why I'm asking him why he close this

**Comment by mattobox** [comment]
Oops, I closed that too soon. Thanks for making me aware of the module. I’ll look into it.

**Comment by ednsinf** [comment]
stupid cms has many errors
