### ISSUE TITLE
RSS Feed double encodes CDATA

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7260]
The `FeedController` double encodes CDATA when it doesn't need too. For example, viewing source nodes using CDATA should look like this:

`<description><![CDATA[<p>My amazing description.</p>]]></description>`

Instead it is double encoded like this:
`<description>&lt;![CDATA[&lt;p&gt;My amazing description.&lt;/p&gt;]]&gt;</description>`

This messes up some feed readers which results in them displaying the description like: "My amazing description.]]"

**Comment by hishamco** [comment]
Thanks @scleaver for reporting this, I will have a look to it

**Comment by hishamco** [comment]
Seems you already worked on it ;)

**Comment by hishamco** [comment]
After a little investigation seems the issue occurs in FireFox only, I tried this in Chrome and Edge, the encoding looks good

![Rss](https://user-images.githubusercontent.com/3237266/95880511-42a4be80-0d80-11eb-9671-b4f77c2b4dcd.png)

I will keep investigating why FireFox is doing this ...

**Comment by deanmarcussen** [comment]
Look a little deeper @hishamco 

In that view Chrome is reading and rendering the html escaping (it's not encoding related, it's about escaping). 

Have a look at what actually comes in via the network tab.

**Comment by hishamco** [comment]
Ok @deanmarcussen, that's made me in confuse when it render in the browser and what's shown in view source ;)
