### ISSUE TITLE
Shortcode Templates Feature needs deployment plans and recipes

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7270]
Appears to have been forgotten todo

**Comment by hishamco** [comment]
@agriffard could please add it to the TODOs list that you did long time back, I may handle this if Dean don't mind

**Comment by agriffard** [comment]
Added to #5558

**Comment by deanmarcussen** [comment]
@hishamco if are are going to do this please base them off the `Templates` steps and deployment plans

**Comment by agriffard** [comment]
@hishamco Still todo, if you have some time that would help us.

**Comment by hishamco** [comment]
Hopefully I will start on this today or tomorrow, thanks for your reminder

**Comment by hishamco** [comment]
What should the shortcode recipe have, and what should be deployed?

**Comment by deanmarcussen** [comment]
> @hishamco if are are going to do this please base them off the Templates steps and deployment plans

Just copy the templates recipe and deployment steps

**Comment by hishamco** [comment]
AFAIK I know a recipe should be created with 3 templates, in case of Roles the names are deployed, that's why I asked and sorry if I miss understand you

**Comment by agriffard** [comment]
Did you manage to progres on this one @hishamco ?

**Comment by hishamco** [comment]
I started on this a week ago, but I blocked, that's why I asked before, what should deployed in case of shortcodes

**Comment by deanmarcussen** [comment]
> @hishamco if are are going to do this please base them off the Templates steps and deployment plans

Just copy the templates recipe and deployment steps.

I don't understand what is blocking you @hishamco all you need to do for this is the above.

**Comment by hishamco** [comment]
Seems I was looking for something to export, I just find `ShortcodeTemplatesManager` which the thing that I'm looking for, PR will be pushed soon ...
