### ISSUE TITLE
Can direct media URLs be disabled?

### ISSUE THREAD

**Issue by szilardcsere89** [OrchardCMS/OrchardCore#7272]
Once the users access the URL of a media file it will be available for everyone and I can't take advantage of my private container (Azure Storage).

I mean `~/media/path-to-blob/blob.jpg` is a public URL.

Is it possible to disable downloading media files directly with their URLs?

**Comment by deanmarcussen** [comment]
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6027

Not currently supported oob @szilardcsere89 however if you want to implement it suggestions for the implementation detail are on the issue.

Here is some limited middleware I use which secures anything under the path `~/media/secure`

```
    public class SecureMediaMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly ILogger _logger;

        private readonly PathString _assetsRequestPath;

        public SecureMediaMiddleware(
            RequestDelegate next,
            IOptions<MediaOptions> mediaOptions,
            IOptions<UserOptions> userOptions,
            ILogger<SecureMediaMiddleware> logger
            )
        {
            _next = next;
            _logger = logger;

            _assetsRequestPath = mediaOptions.Value.AssetsRequestPath;
        }

        /// <summary>
        /// Secures a media path if request url starts with ~/media/secure
        /// </summary>
        /// <param name="context"></param>
        public async Task Invoke(HttpContext context, IAuthorizationService authorizationService)
        {
            var validateAssetsRequestPath = context.Request.Path.StartsWithNormalizedSegments(_assetsRequestPath, StringComparison.OrdinalIgnoreCase, out var subPath);
            if (!validateAssetsRequestPath)
            {
                _logger.LogDebug("Request path {Path} does not match the assets request path {RequestPath}", subPath, _assetsRequestPath);
                await _next(context);
                return;
            }

            if (subPath.StartsWithNormalizedSegments("/secure"))
            {
                _logger.LogDebug("Request path {SubPath} is secure, authorizing", subPath);
                if (!await authorizationService.AuthorizeAsync(context.User, SecureMediaPermissions.ViewSecureMedia))
                {
                    await context.ChallengeAsync();
                    return;
                }
                _logger.LogDebug("View Media authorization successul");
            }

            // One day if they want thumbnails we could also check the query string for a size of 160
            await _next(context);
            return;
        }
    }
```

You will need to register `app.Use<SecureMediaMiddleware>()` this in a module which has a dependency on `OrchardCore.Admin` to get the middleware loaded in the correct order (needs to be after the standard `AuthenticationMiddleware` but before the `OrchardCore.Media.Middleware`)

**Comment by szilardcsere89** [comment]
Thanks, it works. The only problem if the browser caches the asset.

**Comment by sebastienros** [comment]
We could create a Media Permission module that would create a ViewMedia permission, and check this in the described middleware. Then it could also support folder specific permissions which has been asked too.

Disabling public access would just be about removing ViewMedia from Anonymous.

**Comment by Piedone** [comment]
Just a nitpick @deanmarcussen: You may consider returning a 404 instead of a challenge so the existence of restricted files remains a secret too (much how GitHub does it too: There's no difference between opening a URL that is genuinely a 404 and one that hides something you're not allowed to see).

**Comment by deanmarcussen** [comment]
Good advise @Piedone 

For truly secret files you would prefer that. 

This snippet is from a paywall, where it actually lets thumbnails through up to a certain size and looks for membership for media of a higher quality

**Comment by Piedone** [comment]
Ah I see, then it's fine of course.

**Comment by intellimedhu** [comment]
@deanmarcussen 
Not working anymore. Middleware is ignored when requesting static file directly.

**Comment by MikeKry** [comment]
@deanmarcussen 

I am sorry, but I can not find it anywhere in docs. When I searched it in code, I can not see any configurable part (if I do not want to replace a lot of classes)

As it is defined as static string here:
![image](https://user-images.githubusercontent.com/52829889/137795179-ff5edfcc-cb7a-49fe-bc56-12ae7b20498e.png)

and used directly from azure module:
![image](https://user-images.githubusercontent.com/52829889/137795220-fadebb0e-1101-43bd-bde5-2943a0ec9a33.png)

I did not find is-cache definition though.

**Comment by sebastienros** [comment]
@MikeKry I don't see how it could not be public. What would be the purpose?

**Comment by alandillon** [comment]
I am using the azure blob storage and I really did not want users to be able to easily access the uploaded data through the CMS url.

I disabled the media folder by putting a folder at that route in iis.

![image](https://user-images.githubusercontent.com/3331097/145088331-0a51f966-46d1-4a23-98eb-54a4de14ebb0.png)

And then I put a web.config in that folder with the following:

```
<configuration>
    <system.web>
        <authorization>
           <deny users="*"/>
        </authorization>
    </system.web>
</configuration>
```
And TADA

![image](https://user-images.githubusercontent.com/3331097/145089066-197bbd47-f84e-41d2-83b2-b7e550354259.png)

**Comment by MikeKry** [comment]
@alandillon 

That is an option I ended up doing also, but it is not something I would like to use on every project

**Comment by szilardcsere89** [comment]
I agree. I don't think it's a good solution

**Comment by mariojsnunes** [comment]
Found this workaround, seems to work well:
![image](https://user-images.githubusercontent.com/8073622/149838768-281b09a6-ea12-4a20-b167-ae33592ad81e.png)
What other impacts this code would cause? Is there a reason this shouldn't be done?

**Comment by deanmarcussen** [comment]
Why don't you just remove the call to `cms.UseStaticFiles()`.

It's not necesary unless you plan to serve static files from the host sites `wwwroot` folder. (many static files would come from modules / themes).

Or if you specifically do want to store some static files in the hosts `wwwroot`, make  sub folder in it called `public`, and register the static file options to serve from that folder only.

@mariojsnunes what you have done is fine.

**Comment by sebastienros** [comment]
Custom middleware registration will work too.

**Comment by mariojsnunes** [comment]
@deanmarcussen yeah I confirm that solution works and is way cleaner.
My project setup uses an Angular SPA, I'll post below the full configure method for future reference:

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.Use(async (context, next) =>
    {
        context.Response.Headers.Add("X-Frame-Options", "SAMEORIGIN");
        context.Response.Headers.Add("X-Xss-Protection", "1; mode=block");
        context.Response.Headers.Add("X-Permitted-Cross-Domain-Policies", new StringValues("none"));
        context.Response.Headers.Add("X-Content-Type-Options", "nosniff");

        await next();
    });

    app.UseResponseCompression();

    // add .webmanifest MIME-type support
    FileExtensionContentTypeProvider contentTypeProvider = new FileExtensionContentTypeProvider();
    contentTypeProvider.Mappings[".webmanifest"] = "application/manifest+json";

    app.UseSpaStaticFiles(new StaticFileOptions()
    {
        ContentTypeProvider = contentTypeProvider
    });

    // Host OrchardCore in /cms subfolder
    app.Map(new PathString("/cms"), cms =>
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        if (env.IsProduction() || env.IsStaging())
        {
            app.UseExceptionHandler("/error");
            app.UseHsts();
        }

        cms.UseStaticFiles(new StaticFileOptions()
        {
            ContentTypeProvider = contentTypeProvider,
            FileProvider = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, "wwwroot/Assets")),
            RequestPath = new PathString("/Assets")
        });

        cms.UseOrchardCore(c => c.UseSerilogTenantNameLogging());
    });

    app.UseSpa(spa =>
    {
        spa.Options.SourcePath = "ClientApp";
    });
}
```
