### ISSUE TITLE
Media Library: improve localization and little SCSS modifications

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#7277]
Hi all, 

I would like to ask if I can do a change in the Media Library interface to add localization improvement by add the "Media Library" in the up-left corner (in the first image look at the awful yellow square) to the dictionary. Also I would like todo a little SCSS code modification to fix some elements.
For example, media library before:
![Inkedbefore_LI](https://user-images.githubusercontent.com/2736009/96090372-65da8580-0ec8-11eb-8dde-1647a4bfec18.jpg)

Media Library after:
![after](https://user-images.githubusercontent.com/2736009/96090386-696e0c80-0ec8-11eb-928b-53973eea22d5.jpg)

**Comment by deanmarcussen** [comment]
Yes sounds ok, but can you grab the latest dev @Skrypt made some changes to the media sass it a couple of days ago, and I'm not seeing (different language perhaps) the same issues as you.

<img width="972" alt="Screenshot 2020-10-15 at 08 54 50" src="https://user-images.githubusercontent.com/13782679/96093536-2ad65300-0ec4-11eb-88c9-7a7c32ebaf8c.png">

**Comment by PiemP** [comment]
Thank you @deanmarcussen, seems graphical fix is already implemented 😅. About the translation of the "Media Library", could exist some interest about this?

**Comment by deanmarcussen** [comment]
> About the translation of the "Media Library", could exist some interest about this?

Yeah makes sense, similar to the `MediaField` could have a localization strings partial for `Media Library` and the other strings used in the modal
