### ISSUE TITLE
Lucene indexation: wrong result for Localized ItemList 

### ISSUE THREAD

**Issue by MaxGasta** [OrchardCMS/OrchardCore#7278]
Hello,

I have a **localized** contentype with a **List behavior**, let's say "NewList".
The list items are localized too , let's say "NewsItem"

I have 2 Lucene Indices, one per culture
 
LuceneIdxNewsItemsIt : returns NewItems for Italian localization 
 
LuceneIdxNewsItemsEn: returns NewItems for English localization 

Here's what's happen.

If I modify a NewItem in a culture (eg IT)  (it is enough just saving it ) 
it appears in the other  LuceneIdxNewsItemsEN too.

If I rebuild the LuceneIdxNewsItemsEN the wrong NewItem disappear and everything works fine.

But I can't rebuild every Lucene Index after every modification.

Is there a way to fix it?

Thanks

**Comment by Skrypt** [comment]
LuceneIdxNewsItemsIt and LuceneIdxNewsItemsEn are IndexingProviders?

**Comment by MaxGasta** [comment]
Yes, they are Lucene Indices,  they index the same contentType but with different culture.

**Comment by Skrypt** [comment]
I will take a look.
