### ISSUE TITLE
code.jquery.com cannot access

### ISSUE THREAD

**Issue by checkmateTowindn** [OrchardCMS/OrchardCore#7286]
In some areas，Access to the code.jquery.com/jquery is not allowed，Is there any solution？

**Comment by Skrypt** [comment]
Disable CDN in admin settings.

**Comment by checkmateTowindn** [comment]
However, you can't get into admin without jQuery

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/5969
