### ISSUE TITLE
Admin UI, strange translation

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#7290]
Hi all, 

I hope to do the right thing by open this issue. In this discussion #7279, I want try to understand how to fix the translation of the backend interfaces because something seem correctly translated and something no.

This behavior is appeared a couple of week ago...I'm not sure when it's happened because I'm busy and I have put my attention on it only 3 days ago.
Please, can someone give me some feedback about it.
Thank you.

**Comment by Skrypt** [comment]
You are right, some elements are not translated. Just like in 01 for some reason things like Content Type names are not translatable in the admin UI. We could easily wait for a PR to get merged in for that matter. I personnally made the changes in the views to allow using .po files for this while waiting on a proper way to translate some elements directly from the admin UI.

**Comment by hishamco** [comment]
@Skrypt what you mentioned is a dynamic or data translation which I did a pr for it long time back

@PiemP if what you ask about is translating the non static data, please wait for #4466

**Comment by PiemP** [comment]
>You are right, some elements are not translated. Just like in 01 for some reason things like Content Type names are not translatable in the admin UI. We could easily wait for a PR to get merged in for that matter. I personnally made the changes in the views to allow using .po files for this while waiting on a proper way to translate some elements directly from the admin UI.

If you look at the image in the #7279 you can see the title translated in Italian language and Actions menu is in English.

it's not related only to Content Type names...the Actions menu is already translated but now is rendered like the image in the discussion #7279. I don't know what I have to do if this are an issue,  if I have to regenerate the .po files or something else that restore the translations of this items. But a couple of weeks ago the Published term, the Actions menu and other menus in the list Content Item interface are translated.

**Comment by hishamco** [comment]
Could please let me know what's the difference between this issue and https://github.com/OrchardCMS/OrchardCore/discussions/7279?

No worry I will have a look after finish few things I have

**Comment by PiemP** [comment]
Sorry @hishamco, It's the same problem. I have opened an issue but I don't know if it is the right thinks.

**Comment by hishamco** [comment]
No need, anyhow I will try to fix it if it's not an Italian translation issue

**Comment by hishamco** [comment]
Closed according the comment https://github.com/OrchardCMS/OrchardCore/discussions/7279#discussioncomment-105870
