### ISSUE TITLE
Fix CultureAspect extensibility

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#7306]
We need to refactor code in places where we access directly the LocalizationPart to get the ContentItem current culture.
Instead we should use the `_contentManager.PopulateAspectAsync(contentItem, new CultureAspect());` or something similar so that if someone implements a different ContentPart that could alter the ContentItem culture ; it evaluates both.

## TODO : 

- [ ] Evaluate changes to be made with CultureAspect class.
- [ ] Create a Unit Test that test extensibility.

## Examples : 

https://github.com/OrchardCMS/OrchardCore/blob/cfe0237eb843c103f113d11dfe093c0343ca572b/src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneIndexingService.cs#L189

https://github.com/OrchardCMS/OrchardCore/blob/cfe0237eb843c103f113d11dfe093c0343ca572b/src/OrchardCore.Modules/OrchardCore.Lucene/Handler/LuceneIndexingContentHandler.cs#L85

So far it is the only 2 places I found where we do this. But we probably also use a similar technique with Recipes.
Please report other places where it needs to be fixed here.

**Comment by hishamco** [comment]
Do you start working on this or shall I work on this one, coz I remembered another place that I will try to find, that require using `CultureAspect`

**Comment by Skrypt** [comment]
It's up for grab.

**Comment by hishamco** [comment]
@Skrypt is the unit test to check that `null` value index when the content item doesn't have a `LocalizationPart` or is there something else that we need to check?

**Comment by Skrypt** [comment]
I don't think we should test based on LocalizationPart but on CultureAspect. So, the test would be to check if a different ContentPart could alter the CultureAspect properly.

**Comment by hishamco** [comment]
I think I will separate this into another PR

Thanks
