### ISSUE TITLE
Issues with double encoding in RSS of non-HTML strings

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7323]
In issue #7261  and PR #7268 the double encoding of CDATA was sorted but unfortunately, I have just noticed that other non-HTML strings in the RSS where WebUtility.HtmlEncode is used double encoding occurs because the WebUtility.HtmlEncode encodes the string which is then encoded again by XDocument - it appears that WebUtility.HtmlEncode is not needed.

So a title like this:
What's happening now!

Becomes this in the RSS (must view source of RSS in Chrome to see):
<title>What&amp;#39;s happening now!</title>

Desired result should be just:
<title>What&#39;s happening now!</title>

**Comment by hishamco** [comment]
Thanks Seth for reporting this

> Becomes this in the RSS (must view source of RSS in Chrome to see):

I will check the incoming response from the network tab instead

**Comment by hishamco** [comment]
BTW if you want to fix this, please let me know and I will work on something else

**Comment by scleaver** [comment]
@hishamco  I'll fix it now mate.

**Comment by hishamco** [comment]
It's you now Seth, please let me know if you need any help, please don't forget to add a unit test too

**Comment by sebastienros** [comment]
How is your example "double" encoded? If that was the case we'd see &amp;#39;

**Comment by scleaver** [comment]
> How is your example "double" encoded? If that was the case we'd see `&amp;#39;`

This issue is closed but I updated the original examples - because I didn't have them in code markup it wasn't showing the example properly.
