### ISSUE TITLE
Razor @page setting all image files references to their own page/content item.

### ISSUE THREAD

**Issue by Nic-84** [OrchardCMS/OrchardCore#7333]
I have a website using Orchard Core. I am using a collection of razor pages to pull in the content items. I have three different levels of navigation as follows:

Level One
- Sub Page of Level One
- - Sub Page of Level Two

I am using three different razor pages for the three different levels of navigation so that I can pull the slugs out of the URL and have the page render the correct content item. I have the code for those below.

I have a typical _Layout.cshtml page that controls the main html layout of the entire site, and there are several <img> tags that end up referencing the media directory out of the App_Data directory where I have uploaded all of my images through the Orchard CMS. I am using awaits to set variables from Orchard.GetContentItemByHandleAsync("alias:the-content-item")  These image source references are getting rendered correctly in the browser. However, none of the images are being rendered by the browser, and I get a 404. If I copy the link/URL for any image reference (like media/photos/photo.jpg) the site is directing to what it thinks is a content item and not the actual image in the media directory.

Here is how I am setting up those razor pages:

**Level One Razor Page:**
```
@page "/{Slug1}"
@inject OrchardCore.IOrchardHelper Orchard
@functions
{
        [FromRoute]
        public string Slug1 { get; set; }
}
@{
        var pageData = await Orchard.GetContentItemByHandleAsync($"alias:{Slug1}");
}

@if (pageData != null)
{
        //do stuff
}
else
{
        //do other stuff
}
```

**Level Two Razor Page:**
```
@page "/{Slug1}/{Slug2}"
@inject OrchardCore.IOrchardHelper Orchard
@functions
{
	[FromRoute]
	public string Slug2 { get; set; }
}
@{
        var pageData = await Orchard.GetContentItemByHandleAsync($"alias:{Slug2}");
}

@if (pageData != null)
{
        //do stuff
}
else
{
        //do other stuff
}
```

**Level Three Razor Page:**
```
@page "/{Slug1}/{Slug2}/{Slug3}"
@inject OrchardCore.IOrchardHelper Orchard
@functions
{
	[FromRoute]
	public string Slug3 { get; set; }
}
@{
        var pageData = await Orchard.GetContentItemByHandleAsync($"alias:{Slug3}");
}

@if (pageData != null)
{
        //do stuff
}
else
{
        //do other stuff
}
```

If I modify my razor pages to something like "/test/{Slug2}" or "/test/test/{Slug3}" where the different parts of the URL are not slugs, the images work fine and the site doesn't think that each image file reference is it's own content item or page.

**Comment by deanmarcussen** [comment]
Hmm interesting.

The `StaticFileMiddleware` checks to see it is a valid endpoint request, and passes on the request if it is, so I suspect that's what's happening, is you've essentially create a catch all route, that is catching everything.

`@page "/{Slug1}/{Slug2}/{Slug3}"` I'm not sure this is going to work for you regardless.

If you want to create nested url's would you not make your alias included the nested value

i.e. an alias of `/parent/child/otherchild`

**Comment by sebastienros** [comment]
@Nic-84 feel free to comment if the explanation is not clear enough

**Comment by Nic-84** [comment]
Thank you Dean and Sebastien for your input, I really appreciate it! I am going to abandon the idea/concept that I had above, as it clearly causes issues. I am still very new to working with Orchard and working with Razor pages, so I am still investigating ways to make ideas work. I am going to try Dean's suggestion of specifying the nested page structure using the alias, or maybe a combination of the alias and the permalink. But yeah, you can close this particular issue down. Not a problem with Orchard, but rather my own idea. Thank you both!

**Comment by Nic-84** [comment]
I wanted to give another update on this. I discovered a way to get around the trouble I was having. As long as I nest my images deeper than the depth that my page nesting goes, the images work fine. So if my page structure is set up to have three levels, like page-level-one/page-level-two/page-level-three, then I need to make sure my image director goes at least three levels deep, like media/img/resources. That works and fixes the issue where the site doesn't find the images. Also, I updated my three razor pages to find unique aliases, and the aliases now include the sub-directories, like /parent/child or parent/child/another-child. My page routes look like:

```
@page "/{slug}"
@functions
{
	[FromRoute]
	public string slug { get; set; }
}
@{var pageData = await Orchard.GetContentItemByHandleAsync($"alias:{slug}");}
```
```
@page "/{text?}/{slug}"
@functions
{
	[FromRoute]
	public string text { get; set; }

	[FromRoute]
	public string slug { get; set; }
}
@{var pageData = await Orchard.GetContentItemByHandleAsync($"alias:{text + "/" + slug}");}
```
```
@page "/{text1?}/{text2?}/{slug}"
@functions
{
	[FromRoute]
	public string text1 { get; set; }

	[FromRoute]
	public string text2 { get; set; }

	[FromRoute]
	public string slug { get; set; }
}
@{var pageData = await Orchard.GetContentItemByHandleAsync($"alias:{text1 + "/" + text2 + "/" + slug}");}
```
This works and I can have the specific URLs that I need. So, hopefully this solution will hold up.

Thanks again for poking my brain and making me think a little harder!

**Comment by Nic-84** [comment]
Sorry, another update on this. So, I am stepping back on my wildcards in my page routing. The level three page with the "/{text1}/{text2}/{slug}" route is now messing up all of the CSS/JS file references as well. This blows apart the admin side and it doesn't work with this. So I am going to resort back to setting up a specific razor page file for each specific section of my site that has sub pages/directories. Kind of a bummer that I can't have a few general pages that will handle/funnel everything through them, but I get that it breaks other stuff since it's sort of a catch-all. It was a good try.
