### ISSUE TITLE
Orchard Core Causing Hangfire to Not Work

### ISSUE THREAD

**Issue by mattobox** [OrchardCMS/OrchardCore#7335]
Any luck with getting Hangfire to work with Orchard Core? I have two separate projects (CMS, Module1). Most of my web services are in a decoupled project called "Module1". If I load Hangfire from within "Module1" using `services.AddHangfireServer()` the Hangfire server is not registered. However, if I load it within the "CMS" project it registers the Hangfire server correctly. This would be a good solution, however the scoped services from "Module1" are unavailable to Hangfire if it's loaded in the "CMS" project. 

Any help would be appreciated.

**Comment by mattobox** [comment]
I was able to get it to work from "Module1" by adding this line to the app portion of Startup.cs

`app.UseHangfireServer();`

**Comment by hung-doan** [comment]
@mattobox do you got any problem with Hangfire when working with OrchardCore CMS ?. 
I hit the problem when It's not able to resolve services from OrchareCore CMS: https://github.com/OrchardCMS/OrchardCore/issues/7437

Any thoughts on this would be appreciated thanks mate.
