### ISSUE TITLE
Publish button (that doesn't work) shown to user without publish permission

### ISSUE THREAD

**Issue by Richard-CQC** [OrchardCMS/OrchardCore#7340]
I have a user who can create and edit content, but can not publish it.

However on the content item edit screen they see a 'Publish' button and on the content items list there is a 'Publish draft' action in the actions dropdown for a content item.

If they click either of these they get a 403: You do not have access to this resouce screen.

The expected behaviour would be that they do not see publish option.

**Comment by Richard-CQC** [comment]
This was observed on the RC2 release. I've not tried on latest dev.

**Comment by jptissot** [comment]
I think this issue was fixed recently by @Skrypt

**Comment by Richard-CQC** [comment]
I can confirm that this has been fixed in the latest dev version.
