### ISSUE TITLE
Rename IContentAliasManager to IContentHandleManager

### ISSUE THREAD

**Issue by WolvvCore** [OrchardCMS/OrchardCore#7342]
Greetings,

I wanted to mention the following discrepancy between the de renamed name and the obsolete message.
The interface "IContentAliasManager " has been renamed to "IContentHandleManager". However the obsolete message mentions it has been reanamed to "IContentHandlerManager"

```
public interface IContentHandleManager
{
        Task<string> GetContentItemIdAsync(string handle);
}

 [Obsolete("This interface has been renamed to IContentHandlerManager")]
public interface IContentAliasManager {}
```

So I wonder is the rename correct this way, or can we expect a rename again to "IContentHandlerManager" in the future.

**Comment by hishamco** [comment]
You 're right, I will fix now ..

**Comment by hishamco** [comment]
It's `IContentHandleManager`
