### ISSUE TITLE
Is Liquid syntax implemented in OC only a subset of the full syntax at Shopify? Does it include color-filters?

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#7352]
I'm trying to convert an RGB hex color value into another one with transparency. For that, according to [Shopify color-filters](https://shopify.dev/docs/themes/liquid/reference/filters/color-filters) there is one just for what I need (an example from them):
`{{ '#7ab55c' | color_modify: 'alpha', 0.85 }}`
However, when I try to use it, it does not work. It simply outputs the original hex RGB value without any transparency (solid).

**Comment by jptissot** [comment]
Please see https://github.com/sebastienros/fluid
