### ISSUE TITLE
Taxonomy query to retrieve site level tags/categories 

### ISSUE THREAD

**Issue by 4m-world** [OrchardCMS/OrchardCore#7359]
Can I get help on how to query all tags taxonomy and render it?

I tried to write a Query with Lucence with no luck to retrieve any data, then I wrote a SQL query that retrieved all blog tags with several options retrieving all document  which in this case BlogPost and returned value contained duplicate tags to display,

`SELECT * FROM [TaxonomyIndex] WHERE [ContentType] = 'BlogPost' AND [ContentField] = 'Tags';`

the other option is retrieving TaxonomyContentId and here I was unable to render its content

`SELECT TaxonomyContentItemId FROM [TaxonomyIndex] WHERE [ContentType] = 'BlogPost' AND [ContentField] = 'Tags';`

Note I'm using liquid

**Comment by Skrypt** [comment]
Have you looked at the documentation?
I'm pretty sure it explains how to render a taxonomy with Liquid.

**Comment by 4m-world** [comment]
following below issue #5213 I managed to retrieve tags content however if there is an index for taxonomy it will much easier:

`
{% assign tags = Queries.BlogTags | query %}
{% if tags.size > 0 %}
<h3>TAGS</h3>
{% for tagId in tags %}
{% assign tag = Content.ContentItemId[tagId.TaxonomyContentItemId].ContentItem.Content %}
                    {{ tag | raw  }}
{% endfor %}
{% endif %}
`

**Comment by Skrypt** [comment]
But there is a TaxonomyIndex in the database.

**Comment by 4m-world** [comment]
Yes after enabling the SQL indexing

**Comment by Skrypt** [comment]
No, the TaxonomyIndex is added when you enable the Taxonomy module.

**Comment by 4m-world** [comment]
> No, the TaxonomyIndex is added when you enable the Taxonomy module.

Yes you are right, I couldn't access with Lucence and when and instead of enabling "SQL Queries" feature alone to write the SQL query, I enabled "Content Field Indexing (SQL)"

Another point I used distinct in the query 2nd query to ensure no duplicates.
