### ISSUE TITLE
Body Aspect creates duplicates

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7375]
The fix here https://github.com/OrchardCMS/OrchardCore/pull/5934

for the internal cache of the body aspect was incorrect.

When used in a widget the HtmlBody can be used to generate a `BodyAspect`, but the value is incorrect, because the test is done against the `ContentItem.Id` property which is always 0 on a contained item.

It could evaluate against content item id, but I think the entire idea of caching a body aspect across requests is unnecessary.

I challenge anybody to find a place where a body aspect is called twice on the same request.

Needs to be fixed
- HtmlBody
- MarkdownBody
- LiquidPartHandler
- FacebookPartHandler

**Comment by hishamco** [comment]
@deanmarcussen how can I reproduce the bug? How the RSS feed fix raised this issue?

**Comment by deanmarcussen** [comment]
Repro

- create a `Page`
- create a `Widget` using the `HtmlBodyPart`
- add two of these widgets to the page.
- call `_contentManager.PopulateAspectAsync<BodyPart`>() on all the widgets in the `Page`

Solution
- Remove the internal scoped cache on all the `Handlers`. It's an over optimisation that causes more problems that the little (no) value it provides.

**Comment by hishamco** [comment]
I will try to reproduce, but how my above PR affect that?

**Comment by jtkech** [comment]
Just took a quick look so not sure

> I challenge anybody to find a place where a body aspect is called twice on the same request.

I assume you also mean on the same content item / part

Not sure at 100% but yes it looks like caching is not necessary here

Otherwise one solution would be to cache and compare by ref the contentItem itself (or the part), e.g.

                if (part.ContentItem == _contentItem)
                {
                    bodyAspect.Body = _bodyAspect;
                    return;
                }

But in fact we would need to scope cache e.g. a dictionary of `<ContentItem, BodyAspect>` and use `TryGetValue()`

**Comment by deanmarcussen** [comment]
> Not sure at 100% but yes it looks like caching is not necessary here

Yes, there is nothing in OC itself that calls for a `BodyAspect` on the same content item twice (have checked).

That doesn't mean someone wouldn't do it in their own code, but it is not a high cost operation to render the liquid twice, if they do.

Yes, it would have to be a dictionary, but can't be by ref, because we lose ref everytime we go from `JSON`, to a `ContentItem`.

It also can't be by `ContentItemId` as the content item id is the same between versions, and lucene now offers options to also index drafts. 

It can't be by `ContentItemVersionId` as not all content items have versions (i.e. items in a `BagPart` are not versioned)

Which is why I'm proposing to drop the scoped cache, as too complicated, unnecessary, and causes more problems than it's little value :)

**Comment by sebastienros** [comment]
Let's remove the cache.
