### ISSUE TITLE
The whole system crashed after accidentally disabled the Roles feature. How to enable it back??

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#7389]
Hi, after an accidentally disable the Roles feature, the whole system hash crashed with error:

An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'OrchardCore.Security.Services.IRoleService' while attempting to activate 'OrchardCore.Users.Services.UserStore'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)

Now the question is, how to fix this? :(

I try to use the URL but it doesn't work:
 http://localhost/Admin/Features/Enable/OrchardCore.Roles

**Comment by jptissot** [comment]
You need to modify the database. Look in the document table for an entry that has site settings and enabled features.

**Comment by orchardc** [comment]
Thanks Jean-Philippe ,

I found the record is the: 
OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Abstractions
