### ISSUE TITLE
If you apply multiple taxonomy filters ,  no results.

### ISSUE THREAD

**Issue by nakamura2000** [OrchardCMS/OrchardCore#7395]
steps to reproduce.

1. enable "Taxonomies" feature and "Taxonomies Contents List Filters" feature.
2. create content type "term" which have title body part.
3. create content item "color" as "taxonomy" type, and it has "red" and "blue" (terms) .
4. create content item "shape" as "taxonomy" type, and it has "square" and "round" (terms).
5. create content type "object" and it has "color_field" and "shape_field" as taxonomy field.
6. create content item "dish" for "object" , and it has "red"  term and  "round" term. 
7. create Taxonomy Filters for "color" and "shape".
8. filter content by "color" : "red" , and "dish" content item is successfully filtered and shown.
9. filter content by "shape" : "round" , and "dish" content item is successfully filtered and shown.
10. but If you filter content by both "color" :"red" and "shape" : "round" , there is no result.

This issue may be already addressed to solve. 

https://github.com/sebastienros/yessql/commit/68972b2325c0594f98491fd40e2c77bd75dd3b59#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

I have applied latest yessql from dev source code 
(and fix some changed method) and I confirmed it works.

In TaxonomyContentsAdminListFilter.cs FilterAsync

current:

   query.With<TaxonomyIndex>(x => x.TermContentItemId == viewModel.SelectedContentItemId);

to:
   query.All(
       x => query.With<TaxonomyIndex>(x => x.TermContentItemId == viewModel.SelectedContentItemId)
   );

**Comment by deanmarcussen** [comment]
Yes, it was never designed to work like that.

However the Yes.Sql improvements should work but I suspect just using the `IsIn()` extension would work just as well.

**Comment by sebastienros** [comment]
The query in code needs to change to handle AND. Either with the .All or the IsIn(), whichever makes sense.

**Comment by sebastienros** [comment]
@nakamura2000 do you want to try and create a PR for this?

**Comment by nakamura2000** [comment]
I confirmed that taxonomiIndex is aliased in generated sql and filter is applied for each aliased table with above code.

I will create PR but current linked nuget yessql version is 1514 so I had to add version attribute 1614 in csproj.

SELECT count(distinct [Document].[Id]) 
FROM [Document] 
INNER JOIN [ContentItemIndex] AS [ContentItemIndex_a1] ON [ContentItemIndex_a1].[DocumentId] = [Document].[Id] 
INNER JOIN [TaxonomyIndex] AS [TaxonomyIndex_a1] ON [TaxonomyIndex_a1].[DocumentId] = [Document].[Id] 
WHERE 
[Document].[Type] = @Type AND 
 (([ContentItemIndex_a1].[Latest] = @p1) AND [ContentItemIndex_a1].[ContentType] IN (@p2, @p3) 
AND ([TaxonomyIndex_a1].[TermContentItemId] = @p4) 
AND ([TaxonomyIndex_a1].[TermContentItemId] = @p5))

with query.All

SELECT count(
distinct [Document].[Id])
FROM [Document] 
INNER JOIN [ContentItemIndex] AS [ContentItemIndex_a1] 
ON [ContentItemIndex_a1].[DocumentId] = [Document].[Id] 
INNER JOIN [TaxonomyIndex] AS [TaxonomyIndex_a2] 
ON [TaxonomyIndex_a2].[DocumentId] = [Document].[Id] 
INNER JOIN [TaxonomyIndex] AS [TaxonomyIndex_a3] ON [TaxonomyIndex_a3].[DocumentId] = [Document].[Id] 
WHERE [Document].[Type] = @Type AND 
(
   ([ContentItemIndex_a1].[Latest] = @p1) AND [ContentItemIndex_a1].[ContentType] IN (@p2, @p3)
   AND (
     ([TaxonomyIndex_a2].[TermContentItemId] = @p4) 
   AND 
      ([TaxonomyIndex_a3].[TermContentItemId] = @p5)
   )
)

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/7468
