### ISSUE TITLE
Admin Dark mode

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7402]
There are some incorrect displays when you are in Admin Dark mode:

- `nav` with css class='admin-toolbar' have a light background.
- [X] #7403 List of admin menus has a light background and the type of menu is not displayed because it is in black:
![image](https://user-images.githubusercontent.com/703248/97286174-77fee100-1843-11eb-86e6-a2f038dfdff5.png)
![image](https://user-images.githubusercontent.com/703248/97286270-94028280-1843-11eb-9eac-9c6ecd7897d6.png)

- Text in input-group is not displayed. Ex: Permalink in Create Sitemap or Autoroute:
![image](https://user-images.githubusercontent.com/703248/97286425-c3b18a80-1843-11eb-9642-e8b4dd92f70b.png)

- Readonly input is grey on grey bg. Ex: Technical name in Edit Content type, Edit Layer:
![image](https://user-images.githubusercontent.com/703248/97287083-71249e00-1844-11eb-973e-c023e5207143.png)

- Font picker icons are not displayed:
![image](https://user-images.githubusercontent.com/703248/97287588-0fb0ff00-1845-11eb-840a-dcb15a2c7fca.png)

**Comment by jptissot** [comment]
![image](https://user-images.githubusercontent.com/4681586/97323749-7fc08480-1847-11eb-955f-40ccabedd88c.png)

Non dark mode issue

**Comment by Skrypt** [comment]
Look at the Bootswatch file which adds some unnecessary styles I think. That must be the issue with the default admin theme at least. Other ones are adjustments. Pokemon catch em' all ... too much of them.

**Comment by hishamco** [comment]
I think we need to revise the dark theme for all the pages before we merge this PR

**Comment by Skrypt** [comment]
Nahh, the feature is merged already. The intent was not to have it perfect on first try but to have the proper foundation to achieve it. As much time I put on this I can't find all the small issues but I believe it is functional for the most part.

**Comment by hishamco** [comment]
I can help you on fixing this too

**Comment by Skrypt** [comment]
Let me handle this. You have some other remaining PR's that you can work on 😉

**Comment by hishamco** [comment]
Ya ;)
