### ISSUE TITLE
Login page with Blog Theme

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7408]
If you check 'Use site theme for login page' in the settings of a site using theBlogTheme, the login page looks like this:

![image](https://user-images.githubusercontent.com/703248/97345262-2299f280-188a-11eb-863e-13a8188d1f07.png)

The button to show the password is not looking good.

**Comment by hishamco** [comment]
I will handle this if no one started yet

**Comment by hishamco** [comment]
The issue may happen for other themes as well, I will make a fix soon
