### ISSUE TITLE
Issue 'Your alias is already in use'

### ISSUE THREAD

**Issue by krchome** [OrchardCMS/OrchardCore#7410]
If I try to import a content item with an alias that already exists, this results is  an error 'Your alias is already in use'
Please see the attached stack trace. 

Please  let me know how to resolve this issue
![Capture](https://user-images.githubusercontent.com/8474855/97370577-2bcfa180-1914-11eb-9172-0373a89cb155.JPG)

**Comment by deanmarcussen** [comment]
To resolve this do not try and import a content item with the same alias as another. 

It's quite simple, they must be unique.

If it is the same content item, the `ContentItemId` must match, and the `ContentItemVersionId` must be different

**Comment by krchome** [comment]
Ok, thanks very much. I shall try the solution. By the way is there a tutorial to learn about the way the shapes (rather than the html) that are rendered through the content templates?
