### ISSUE TITLE
Menu's should use the DisplayText property

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7418]
The ContentMenuItem and LinkMenuItem should use the DisplayText property instead of both parts having a "Name" property. Or maybe a CommonMenuItemPart to share the name and common properties.

**Comment by Skrypt** [comment]
Maybe just like the TitlePart it should simply fill the DisplayText from the Name.

**Comment by hishamco** [comment]
@Skrypt I think I already did something similar in another PR, I will check ..

**Comment by jptissot** [comment]
@Skrypt Good idea, simple PR :)

**Comment by hishamco** [comment]
@jptissot I already did that if I'm not wrong in another PR, I don't remember the issue, but I will check all my PRs or add a new one if it's needed

**Comment by hishamco** [comment]
I found my PR the issue was on renaming the display name, when I investigate it's obvious that the `DisplayName` not set, I will check if I can do the fix for this first, or do it in my other PR, then check if this issue still exists

I will assign this to me while it's related

**Comment by hishamco** [comment]
May be related to #6129

**Comment by deanmarcussen** [comment]
For infos.

The `DisplayText` property didn't exist when the Menu module was written, hence it wasn't used.

It's not completely trivial.
as @Skrypt says the `DisplayText` property could be migrated to
will also need a migration to migrate existing menus to update their `DisplayText` so the templates continue working. 
Migration should be ok, I think, small number of menu content items per site.

**Comment by jptissot** [comment]
Yes, I was thinking about migrations as well @deanmarcussen I have been playing with the menu shapes and have found some other small issues. For example, I was unable to attach a dynamic part to the LinkMenuItem for common  menu fields. I will document this further when I have time.

**Comment by hishamco** [comment]
I will take care about the other issue and keep this for `1.0.x`

**Comment by sebastienros** [comment]
This has to be a breaking change since templates will need to be updated. But that's an easy thing to document.
