### ISSUE TITLE
UnitOfWork pattern to reduce reads and writes to db caching and tracking changes in entities

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#742]
This issue is relate with this PR https://github.com/OrchardCMS/Orchard2/pull/741 that tries to fix this:: 
``... because handlers could do queries and / or updates, here session Save() are done as late as possible, after handlers, explicit queries .... This to prevent, as much as possible, from losing updates.``

In Orchard 2 we get rid of an ORM that was good because we get rid of its limitations (due to the gap between relational and Object worlds). But we also lost one of its advantages: the UnitOfWorkPattern for caching entities requested in a session and tracking changes. If we implement it, it would help to avoid problem described in the PR mentioned. IMO it will help us to don't be fighting in the future vs problems of performance because too many queries are performed for any operation when in reality they are repeated queries. 
Some of you maybe have bad memories using unitofwork pattern with an ORM. However the key point is to enable cache and tracking only for queries done to load entities that are going to be updated. Doing that things go smooth like a charm. This is my experience using my own home made unitofwork with tracking and caching on top of a document/Object db.

**Comment by jersiovic** [comment]
Ups, I think I wake up with a mess in my brain this morning.  
YesSQL implements the UoW what I'm not sure it does is the tracking and the caching

**Comment by sebastienros** [comment]
It only doesn't track changes. It was intentional as the code to handle this is not simple, necessitating dynamic proxies and deep object graph tracking (we store aggregate roots) and impacts your POCOs as they need to have virtual properties. I preferred to require explicit save.

**Comment by jersiovic** [comment]
Ok I see, thank you

**Comment by jersiovic** [comment]
After watching Orchard Podcast: 25th of April, 2017 minute 12:34 https://www.youtube.com/watch?v=cIuVMnki9b8&feature=youtu.be hearing problem PR #741 solves, I think it could be good to reopen this issue.
This is what it was explained in the meeting: Currently YesSql when it has changes pending to store in db if a query is done it stores changes before executing the query.
This is a problem when the  query is done in a driver, because after the data is been stored the entity to be stored is unmarked as to be stored. So, if next drivers make changes on the entity they are lost.
Solution provided is that after each query you need to know which entities were marked as changed and imagine which of them could be changed in other parts of the code within same request and mark them to save with sesión.Save method to avoid any future change on them could be lost.
IMO this is not an aceptable solution, because it is obscure and diffcult to see for the consumer of yessql, it looks it will be the cause of many bugs and many time lost looking for what caused the problem. 

At this point I see three alternatives:
- Change YesSQL, to make that when changes are stored because of a query execution the entities stored in db still are maintained as entities to save. This will make the consumer of yessql doesn't need to be aware of its internals. Problem is performance, because every next query will save previously another time entities that maybe haven't changed.
- Change YesSQL, to don't store changes before a query and only save when an explicit commit is called by the consumer like it is done now when request ends. This is a problem because the consumer has to be aware that while commit is not done its queries cannot expect that changes in entities in memory are reflected in db. But at least you won't need to guess what was changed before that could be changed after. 
- Implement change tracking. Then before any query we can store changes and after the query we will continue tracking changed entities, so, only if changes arise we will save another time those entities. This solutions has more work of implementhing but result is good having the benerfits of first and second alternative, and will avoid us many headaches. IMO, in the long term this should be the solution to provide.

**Comment by jersiovic** [comment]
I know most eficient way is using a proxy for tracking changes but it has side effects. What do you think if Yessql requires entities to track that implement IPropertyChanged and we use a solution based on annotations like this which allows to use properychanged at property level or at class level without forcing devs to write too much code: https://github.com/Fody/PropertyChanged/blob/master/README.md
