### ISSUE TITLE
Menus : You do not have access to this resource.  accessing with Admin User

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#7425]
Just created clean OC installation, `(<PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-rc2-15181" />)`
Then enable Menu module from admin panel.
Once trying to access the menus get this error:
![image](https://user-images.githubusercontent.com/61165619/97536888-8590a400-19c6-11eb-9ed8-512b5d68af4c.png)

revert to nuget package  Version="1.0.0-rc2-144771" fix everything.

**Comment by deanmarcussen** [comment]
Which recipe?

**Comment by vitalybrandes** [comment]
> 
> 
> Which recipe?

Wow, forgot to add ,sorry.
some default, saas i think.

**Comment by sebastienros** [comment]
I'd suggest you provide some repro steps and define what you would be expecting.

**Comment by atorres16** [comment]
Just to comment that this happened to me with version 1.1, I had windows authentication enabled for the project.
I disabled it, tried again and was able to enter the admin page. After performing the first time setup, I enabled Windows Auth again and the problem disappeared.

So it seems  you can't do the first time setup if your project has Windows Authentication enabled.
