### ISSUE TITLE
Http Redirect Task URL Encoding Liquid?

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#7431]
I have a form that submits data to a workflow. It passes in the "path" that I want the form results to return to.

![image](https://user-images.githubusercontent.com/1848585/97559162-73593a80-19b3-11eb-8450-6e824a5a61ee.png)

To accomplish this in the flow, I am trying to utilize the Http Redirect Task.  The passed in "Path" is "/" (or any path with a slash). However, when the redirect is done it comes out of the URL rendered as %2F so I am not taken to the actual page. I have tried adding the url_decode filter but that doesn't clear it which makes me wonder if I am missing something:

![image](https://user-images.githubusercontent.com/1848585/97558991-40af4200-19b3-11eb-80bc-1398c21601f9.png)

I will try to get in the source code to figure this out but if you see anything I am doing wrong, please let me know.

**Comment by deanmarcussen** [comment]
Try `| raw`

**Comment by jeffolmstead** [comment]
You are my hero, yes indeed, raw took care of it. Thanks for taking the time!
