### ISSUE TITLE
docs.orchardcore.net is extremely slow

### ISSUE THREAD

**Issue by cutig3r** [OrchardCMS/OrchardCore#7445]
Loading pages on docs.orchardcore.net takes about 2 minutes per page, unless the page has been visited recently.

Navigating to the workflows documentation:
![image](https://user-images.githubusercontent.com/10190259/97716634-3ddb4c80-1a9a-11eb-8c10-64da07ceb3b5.png)

**Comment by agriffard** [comment]
I tried to revert one of the latest change to see if it was related (list authors) but it is not, some pages take time to be displayed the first time and then are displayed quickly the next attempts.

**Comment by agriffard** [comment]
This is clearly related to CloudFlare and the cdn that stores pages in cache because we can see that the getting started pages still have the authors at the bottom while the doc has been rebuilt.

**Comment by agriffard** [comment]
It seems to be back to normal.
