### ISSUE TITLE
Thoughts on implementing Content Syndication?

### ISSUE THREAD

**Issue by willnationsdev** [OrchardCMS/OrchardCore#7455]
I'd like for different tenants to be able to opt-in to sharing their content on other tenants (content syndication), but *without* actually maintaining many different copies of the same content in different Document tables. They retain ownership/management rights.

One way I could see this happening is by having a SharedContent module where users add a ShareablePart to a ContentType that makes the data get stored in the Default tenant's database instead of the local one (somehow?). And then, if the ShareablePart's "Share" flag is toggled on, then those content items can be viewed, perhaps selected from a content picker, etc. Things would gracefully ignore it if a local tenant was using a reference to the ContentItemId.

I'm kind of at a loss for any *good* way to implement this all though. Let's say I add a ShareablePart to the Article content type.

- I create an Article and publish it. Then, I later decide I want to share it. When I toggle the shared state and save, I would need to migrate the ContentItem to the Default database.
- I then want to be able to edit my shared content item from within my local tenant, without going to the Default tenant (which I may not have access to). So the SharedContent module would also add a SharedContentItems menu item with a List view and Editor for those items.
- All of the built-in ContentTypes creation processes redirect to the core Content module, so I wouldn't be able to use this shared content editor for things like Taxonomies or Workflows without also duplicating all of those modules work too.
- Let's say a third tenant then wants to view all of the shared content that they can access to add to some list in a content item. Whatever GUI is responsible for adding things to the content item has to be able to view both local content and the shared content, so you can't use the built-in picker for that either. You'd need a custom one. And because of that, I'm guessing (not sure) that you'd also need a custom ListPart or something that can source content from more than one ISession.

This pattern of having to completely re-implement the frontend in a separate module just to re-configure which tables it should store the item in, or from which tables it should pull a list for a view isn't maintainable at scale or long-term as the open-source project continues to develop and improves those features / adds new ones.

Does anyone here have a suggestion on a better approach?

**Comment by Piedone** [comment]
Hmm, I think you'd need to have a content item on every tenant where you want that content item, otherwise, all content operations will need to be basically duplicated as you've also observed. So, basically, a placeholder item that doesn't do much more than store a reference to the shared item. Then you can access the shared item from the other tenants [like this](https://orcharddojo.net/blog/how-to-access-services-from-another-tenant-in-orchard-core-orchard-nuggets).

I don't think you need to move an item that's shared to the Default tenant. Instead, you can create such a placeholder item on the other tenant you want to use it and reference not just the shared item but its tenant too. Alternatively, if you want a shared content store, you can just create the shared items on the Default tenant (or whichever tenant you designate for this) to begin with.

**Comment by jtkech** [comment]
@Piedone just for info

In place of `_shellSettingsManager.LoadSettingsAsync()` better to use `_shellHost.GetSettings()` or if not sure that the tenant exists `_shellHost.TryGetSettings()`.

**Comment by Piedone** [comment]
Thanks @jtkech. I see there is also a `_shellHost.GetScopeAsync("Default")` overload where you don't even need the `ShellSettings` object. I'll simplify this.

**Comment by willnationsdev** [comment]
@Piedone That sounds like a much more reasonable approach. Thanks! I will start looking into that first thing Monday.

**Comment by willnationsdev** [comment]
@Piedone The more I think about it, the more I see that you're right and I would definitely need to have a dedicated tenant as a third-party shared content store. However, if possible, I would prefer it if tenants didn't need to navigate away from their local admin in order to create, edit, and view the shared content. As such, I'm considering a different feature entirely:

What if I patched the Content module's endpoints/actions so that a GET parameter of a `tenant` could be defined, and I adapt all of them to scope to that tenant if the parameter exists and if they have a specific set of permissions for cross-tenant content management? I could then simply re-use the existing Content module and everything else which redirects to it could potentially work out-of-the-box or with minimal changes. Seems like it would be a fairly conservative set of changes to the core, and if it works well with good maintainability, it could potentially be merged upstream for general use.

Any flaws in this idea that pops out at you (since I don't know much about the OC codebase much yet)?

**Comment by Skrypt** [comment]
You mean the DefaultContentManager?

**Comment by willnationsdev** [comment]
@Skrypt It's more like, I want to have the ability to override the `ISession` instance that is used in the Content module, but only when a specific GET parameter is passed in. Not sure how to safely do that though, since I don't necessarily want to impact the `ISession` for database access for other things not related to content (dunno if I could mess up something else in the request/response pipeline if I override it).

**Comment by Skrypt** [comment]
I'd need to check to know specific details but the DefaultContentManager uses the tenant registered ISession. So, I'm not sure, as far as I know ; content syndication can be achieved by using the GraphQL endpoint or API endpoint too. Each tenants have their own API endpoints. I would probably look at this option first, unless you want to use YesSQL directly at all costs.

If you need to absolutely use YesSQL in server side code then I believe that you have 2 options : 

- Move content items from one tenant to an other (deployment plans)
- Share a content item from one tenant to an other ... e.g. based on content type definition maybe.

The first one can be done easily in OC. The second one is more tricky since there's nothing baked in right now in OC. It's pretty much open to anyone implementation. Though what you are suggesting seems quite intrusive on the DefaultContentManager. If anyone could simply pass a parameter to be able to switch from one tenant to an other that would be a major security issue.

Though, nothing prevents you from creating a second ContentManager without changing the current one. I'm going to think about it ; I don't have a definite answer for now.

**Comment by willnationsdev** [comment]
@Skrypt 

> content syndication can be achieved by using the GraphQL endpoint or API endpoint too. Each tenants have their own API endpoints. I would probably look at this option first, unless you want to use YesSQL directly at all costs.

It's more that we would prefer to not have to make multiple web service calls when it isn't necessary. If we can just directly access YesSQL in the original web service call to handle every operation necessary, that is preferred.

> Move content items from one tenant to an other (deployment plans)

I was thinking about this after I sent the last message too. If I could just add an even handler for whenever a content item is updated, and then have the callback migrate the data for that content item to another tenant using a shell scope as @Piedone described earlier, then that would be an extremely simple way of moving the data from a local admin to a shared content store. Combine that with a DisplayDriver for a ContentPart that takes in a tenant name and a ContentItemId for Edit/Update operations and then pulls that content for the Display operation, and you'd basically get everything working out of the box without any invasive changes to the way OC works. I personally find it a very attractive option. But my senior coworker isn't fond of the data migration / document duplication aspect of the process (prefers "single source of truth"). I may try to convince him of it though, since the local tenant's copy of the ContentItem is still technically the authority.

Speaking of the above, is there an established way to hash the content of a ContentItem to quickly and efficiently test whether all the data during a migration was copied successfully and accurately (rather than manually comparing every field in every part)?

If I can't get them to agree to the migration idea, then I'll likely have to resort to using a dedicated admin-only tenant for shared content (not ideal since it means I have to start tracking who is creating what content for which third-party tenant, control who can edit what, etc.). This is all stuff that would work automatically in their local tenant.

If data migration can't be approved, then the better alternative over a shared content tenant admin would be finding a different solution that replaces default Content module operations with a different database backend in select cases that can be finely controlled. How to do that is the question.

**Comment by Skrypt** [comment]
You could, from a module use a custom ISession with a different connectionString but you seemed to say that you wanted to be able to also create/edit content items from that ISession. So let's say you want to have a single source of truth. Then you can simply use a tenant to create the content items and display them only on the second one. Assuming that your user would have access to both tenants there should not be any issue. Though, if you totally want to have control over which tenant the content items should be saved against then you will need to refactor the OrchardCore.Contents module for your own needs.

**Comment by willnationsdev** [comment]
@Skrypt @Piedone I convinced my boss to go with the data migration approach, so I think we're good. I'll comment here with the results whenever we get it implemented (probably in 1-3 weeks, depending on the sprint) to let you know if the approach worked well for us. Thanks so much for all your feedback and suggestions!
