### ISSUE TITLE
Register Email Validate bug

### ISSUE THREAD

**Issue by cqkisyouq** [OrchardCMS/OrchardCore#7456]
[Feature("OrchardCore.Users.Registration")]
RegistrationController        

Register Action

 if (!string.IsNullOrEmpty(model.Email) && !_emailAddressValidator.Validate(model.Email))
            {
                ModelState.AddModelError("Email", S["Invalid email."]);

                // Check if user with same email already exists
                var userWithEmail = await _userManager.FindByEmailAsync(model.Email);

                if (userWithEmail != null)
                {
                    ModelState.AddModelError("Email", S["A user with the same email already exists."]);
                }
            }

Here, when mail rule validation fails, check whether a user with the same email already exists?
Duplicate emails can never be verified

**Comment by Skrypt** [comment]
I think this code is fine. The first validation checks if the email is formatted properly.
The second one checks if the email is not already taken by a user.

**Comment by cqkisyouq** [comment]
Here is to mail format error  to do the second verification.
If the email is well formed, verification will be skipped

!_emailAddressValidator.Validate(model.Email)

**Comment by Skrypt** [comment]
Yes, but if there is an error on the email validation then the form should not submit at all right?

**Comment by Skrypt** [comment]
Ok please submit a PR with the proposed changes so that I see better what you mean because I don't understand what you are trying to say.

**Comment by cqkisyouq** [comment]
if (!string.IsNullOrEmpty(model.Email))
            {
                var isValidate = _emailAddressValidator.Validate(model.Email);
                if(isValidate ==false)
                {
                    ModelState.AddModelError("Email", S["Invalid email."]);
                }
                else if(await _userManager.FindByEmailAsync(model.Email) != null)
                {
                    ModelState.AddModelError("Email", S["A user with the same email already exists."]);
                }
            }

**Comment by hishamco** [comment]
@cqkisyouq this condition

```csharp
if (!string.IsNullOrEmpty(model.Email) && !_emailAddressValidator.Validate(model.Email))
{
ModelState.AddModelError("Email", S["Invalid email."]);
```
is do what your first conditions exactly did, after we ensure that the email is valid we are checking whether duplicate or not

If there's a usecase the doesn't work with you please mention i, then I will try to reproduce if there's a bug

Thanks

**Comment by cqkisyouq** [comment]
@hishamco The same email appears in my database

**Comment by hishamco** [comment]
Do you mean that when you register second time the error show up and the user with same email created?

**Comment by cqkisyouq** [comment]
@hishamco  Yes

**Comment by Skrypt** [comment]
```
            if(string.IsNullOrEmpty(model.Email))
            {
                ModelState.AddModelError("Email", S["Email is required."]);
            }
            else
            {
                if(!_emailAddressValidator.Validate(model.Email))
                {
                    ModelState.AddModelError("Email", S["Invalid email."]);
                }
                else
                {
                    // Check if user with same email already exists
                    var userWithEmail = await _userManager.FindByEmailAsync(model.Email);

                    if (userWithEmail != null)
                    {
                        ModelState.AddModelError("Email", S["A user with the same email already exists."]);
                    }
                }
            }
```

I think this would be more appropriate. I think something we do wrong here is that we assume that the email passed will not be an empty string because we validate with our ViewModel previously. But if someone wants to use this controller action from a different view it might cause an issue.

**Comment by hishamco** [comment]
I will check this one, two days ago I tried creating users everything was fine, seems we did something wrong here

**Comment by cqkisyouq** [comment]
@Skrypt Yes, you are right
