### ISSUE TITLE
Unable to render a shape in the NavbarTop Zone

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#7469]
I am trying to extend the existing admin theme, specifically the NavbarTop zone to add a new widget. I want this widget to be displayed on every page of the admin theme (at the navbar).

At this time I am trying to follow the example of @await RenderSectionAsync("Navigation", required: false) in the layout, where the side menu is created as a shape and rendered on every page. As a result I have created a NavbarTopShapes in my own module as follows and registered it in the startup
```chsarp
  public class NavbarTopShapes : IShapeTableProvider
  {
    public void Discover(ShapeTableBuilder builder)
    {
      builder.Describe("NavbarTop")
        .OnProcessing(context =>
        {
            dynamic shape = context.Shape;
            shape.Metadata.Alternates.Add("NavbarTop__Admin");
        });
    }
  }
```
and created the NavbarTop-Admin.cshtml template in the same module. 

However the following line in RenderSectionAsync still does not seem to be able to find my custom shape:
 var zone = ThemeLayout[name]; //returns null

Any pointers on where I am going wrong ? Perhaps there is a much easier way of doing this?

**Comment by deanmarcussen** [comment]
I think you probably want to have a look at the `AdminMenuFilter` which is the piece that actually renders the menu shapes into the navigation zone.

The `IShapeTableProvider` you have there just provides meta data, based on events, after a `Display` call is made on a shape.

It doesn't intrinsically render a shape.

The `OnProcessing` event is more for when a shape is being cached. The `OnDisplaying` event is better for adding alternates.

**Comment by JoshLefebvre** [comment]
Awesome! Created a custom NavbarTopFilter, changed a few fields and voila! 

Thanks @deanmarcussen  !
