### ISSUE TITLE
Any "View" action should open in new window

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7472]
A small issue but from the Admin UI, when I click a "View" button in relation to a content type it feels like a new window should be rather than it being in the same window and being take away from the editing UI - like the preview button does.

Reasons:
- Consistency - all buttons that are going to show you what the content looks like, "View" and "Preview", perform the same and the user knows what to expect.
- Loss of contextual actions - say I am on a content list and I am selecting a couple of items to do a bulk action and I think "is this the content item I am thinking of" and I click the "view" button to check, you then loose whatever actions you have done that's aren't saved.

**Comment by scleaver** [comment]
Same for clicking the site name at the top of the banner too.

**Comment by hishamco** [comment]
Go for it @scleaver and open a PR ;)

**Comment by Skrypt** [comment]
Search for `@T["View"]` with Visual Studio Code.
