### ISSUE TITLE
Removing field on a content type fails to remove it from UI/Cache

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#7481]
![orchard](https://user-images.githubusercontent.com/3228637/97828855-4d26e980-1c96-11eb-90a5-80ff8cef9cfb.png)

/cc @jtkech

**Comment by jtkech** [comment]
Just tried to add a date time field, remove it, re-add it, and i can't repro

But i'm on my current PR branch, i will try it on the last dev

**Comment by Skrypt** [comment]
I'm on the last dev branch with TheBlog theme recipe on SQLite. Prett basic setup. Also using file ContentDefinitions.json.

**Comment by Skrypt** [comment]
Can't repro after doing a `git clean -xdf` and restarting from scratch.

**Comment by jtkech** [comment]
Just tried with my local dev branch (not the very last), it works

I will try it with the very last dev

**Comment by Skrypt** [comment]
Maybe the database became in a state that was making this happen. I was trying to make also working the Taxonomy content list filters and they were not working at all. Something that has changed related to that probably.
