### ISSUE TITLE
Javascript error when admin dark mode disabled

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7486]
Just a console error when the enable dark mode setting is disabled.

<img width="1554" alt="Screenshot 2020-11-02 at 14 35 17" src="https://user-images.githubusercontent.com/13782679/97880171-bc452200-1d18-11eb-93fa-1225e2e33de1.png">

Goes away when enabled.

**Comment by jptissot** [comment]
I was just going to report this 😁 

Cypress tests would have failed, just sayin ;) We should merge those soon

**Comment by Skrypt** [comment]
Me bad programmer 🙈
