### ISSUE TITLE
Possible regression: RoleManager CreateAsync

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#7487]
Hello,

I have some tests working on 1.0.0-rc2-14774 that no longer work on 1.0.0-rc2-15222.

Consider the following code which creates a role and adds the current user to it:
```
await _roleManager.CreateAsync(new Role
{
       RoleName = "Test Role"
});
IUser currentUser = _userService.GetAuthenticatedUserAsync(_httpContextAccessor.HttpContext.User).GetAwaiter().GetResult();
await _userManager.AddToRoleAsync(currentUser, "Test Role");
```

This is failing with the error:
> Message: 
>     System.InvalidOperationException : Role Test Role does not exist.
>   Stack Trace: 
>     UserStore.AddToRoleAsync(IUser user, String normalizedRoleName, CancellationToken cancellationToken) line 351
>     UserManager`1.AddToRoleAsync(TUser user, String role)

This error happens when we run the tests on **sqlite**. But it's working fine on the web environment using SqlServer.

Might this have something to do with #5249 ?

**Comment by jtkech** [comment]
Yes, the shared roles list (read only) is only updated if the session is committed successfully, so only at the end of the curent scope. For some reasons, for roles it was not the case before, but now roles also use this pattern, e.g. here it prevents from adding to the user a role that may not be persisted if the session fails

So here the roles list is not yet updated, you would need to update the user in a deferred task

            await _roleManager.CreateAsync(new Role
            {
                RoleName = "Test Role"
            });

            ShellScope.AddDeferredTask(async scope =>
            {
                var userService = scope.ServiceProvider.GetRequiredService<IUserService>();
                var userManager = scope.ServiceProvider.GetRequiredService<UserManager<IUser>>();

                var currentUser = await userService.GetAuthenticatedUserAsync(_httpContextAccessor.HttpContext.User);
                await userManager.AddToRoleAsync(currentUser, "Test Role");
            });

**Comment by hishamco** [comment]
Is this mean that Roles page broken as well?!! @mariojsnunes is it working on the latest bits?

**Comment by mariojsnunes** [comment]
Thanks @jtkech that worked!
@hishamco yes I am working on the latest version. I didn't find any issue with the Roles page.
The issue was doing these actions programmatically, and one right after the other.
