### ISSUE TITLE
dotnet new ocmodulecms has errors

### ISSUE THREAD

**Issue by rsatter** [OrchardCMS/OrchardCore#7494]
I was following the documentation (https://docs.orchardcore.net/en/dev/docs/getting-started/templates/) and ran the command using v1.0.0-rc2-15293
dotnet new ocmodulecms -n ModuleSiteCreator.OrchardCore --AddPart true --PartName SiteCreator 

The project was created without any of the nugget packages. I add the OrchardCore.Module.Targets which fixed the missing NuGet packages.

The template had 2 errors in PartSettingsDisplayDriver template.
![Screen Shot 2020-11-02 at 4 53 28 PM](https://user-images.githubusercontent.com/406116/97934927-f370fe80-1d2b-11eb-8bbe-f2cfc438e6e3.png)
line 22 var settings = contentPartDefinition.GetSettings<SiteCreatorPartSettings>();
line 43 return Edit(contentPartDefinition, context.Updater);

The name 'contentPartDefinition' does not exist in the current context (CS0103).

I assume it should really be contentTypePartDefinition. Is that correct?

**Comment by jtkech** [comment]
@rsatter good catch, thanks
