### ISSUE TITLE
Parameters for filters and sorts in a query

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#750]
As a future work you pointed Queries will accept parameters.
What I propose is parameter should be declared as Entity to harness DisplayManager composition advantages.
We will have different types of parameters with its drivers for edit and display
i.e.: taxonomyFilter Driver, int Driver those like in orchard one will allow us to configure filters, but if we configure them as client side filter they will be also used for displaying the filter in the client for providing an UI to the user to provide a value for the parameter.
For sorting sth similar would be needed, allowing the user to choose between different sort options.

**Comment by sebastienros** [comment]
The solution I implemented is much simpler, it's just a json object to send to the query.

**Comment by jersiovic** [comment]
Cool. It sounds like you keep query module simple because other will take the responsability of rendering. Looking forward your demo 😊 
I will keep attention on how a dev can override default renderization of a param when it is showed to end user for giving him the opportunity of providing a param value for the query.

**Comment by agriffard** [comment]
You can pass parameters in queries and use them in filters and sort.
