### ISSUE TITLE
Adding a New Custom Authentication Scheme for Admin?

### ISSUE THREAD

**Issue by f1software** [OrchardCMS/OrchardCore#7504]
I can add a new authentication scheme and apply it to a particular api action as  below but this does not work when for a route like www.example.com/tenant1/admin.  In this case the original CookieAuthenticaionHandler runs first and terminates the pipeline with a 302 redirect to Login.

Is it possible to replace the existing auth scheme without adding an [Authorize] attribute to every Orchard controller?

```
public class MyStartup: StartupBase
{
   public override void ConfigureServices(IServiceCollection services)
   {
       services.AddAuthentication()
      .AddScheme<OpenIdConnectOptions, MyAuthenticationHandler>("MyAuthScheme", options => …)
   }
}

[HttpGet]
[Route("myaction")]
[Authorize(AuthenticationSchemes = "MyAuthScheme")]
public async Task<IActionResult> MyAction(string s)
{
…
}
```

**Comment by jtkech** [comment]
@f1software 

`StartupBase` has an `Order` and a `ConfigureOrder` properties that you can override

Try to override the `Order` property with a negative value, start with `-1`
