### ISSUE TITLE
Custom Recipe Parameters

### ISSUE THREAD

**Issue by nuno-tiago-reis** [OrchardCMS/OrchardCore#7508]
Hello, I was reading the pull request #4922 and I have a question. I'm trying to use this feature to change the value of my OpenId Connection authority according to the environment I'm on. Does this allow me to retrieve configurations from the main appsettings.json file or only the one that is generated by Orchard and is placed in the App_Data folder?

Another question is that whenever I use the configuration helper I get the following error:

````
JavaScriptException: configuration is not defined
````

The way I'm using it in the recipe is as follows:

````
"variables":
{
	"authority": "[js: configuration('IdentityManager:Host')]"
}
````

**Comment by deanmarcussen** [comment]
it works for all the `appsettings.json` files.

But it only works for single key, i.e. `"authority": "[js: configuration('Host')]"

It would be a nice pr to improve it to allow access to section keys.

**Comment by nuno-tiago-reis** [comment]
Okay but then the error itself is strange, shouldn't it say that there is not matching key?

**Comment by deanmarcussen** [comment]
@nuno-tiago-reis I realised why you're getting the `configuration is not defined` error

Currently it will only work inside the recipe steps section, not the variables section.

I will tweak that, along with the key accessor limitations I already mentioned.
