### ISSUE TITLE
Slightly punchier crosshairs for crop center

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7514]
Can I offer up a slightly easier to see crosshairs for the crop center UI?

Original version (i'm slightly red green colour blind and can hardly see this - it is over the spaceman's helmet visor for those like me):
<img width="1238" alt="Screen Shot 2020-11-05 at 7 28 39 am" src="https://user-images.githubusercontent.com/2867511/98172459-2e964c00-1f3d-11eb-883f-90e73d46e0d5.png">

My suggestion - 80x80px custom SVG in white with ever so slight shadow to give it more punch on light backgrounds:
<img width="1272" alt="Screen Shot 2020-11-05 at 8 06 44 am" src="https://user-images.githubusercontent.com/2867511/98172928-f3484d00-1f3d-11eb-874d-1402a37a9d70.png">
<img width="1270" alt="Screen Shot 2020-11-05 at 8 06 53 am" src="https://user-images.githubusercontent.com/2867511/98172935-f6433d80-1f3d-11eb-9db4-50f44484fed1.png">
<img width="1259" alt="Screen Shot 2020-11-05 at 8 07 00 am" src="https://user-images.githubusercontent.com/2867511/98172944-f80d0100-1f3d-11eb-89ae-9f02619afe12.png">

Modifying the CSS a little I can center it right on the pointer when placed.

@deanmarcussen (I know this is your baby) and @Skrypt

**Comment by Skrypt** [comment]
It's always a question of tastes. If you want this to be visible in all cases you need to use 2 different colors. A dark border/stroke around the icon would make this visible in all cases. I agree with using a black/white crosshair for making this with most images.

**Comment by scleaver** [comment]
ok - original crosshair but in white with added 1px black border size increased to 30px:
<img width="285" alt="Screen Shot 2020-11-05 at 9 23 32 am" src="https://user-images.githubusercontent.com/2867511/98178595-b897e200-1f48-11eb-8700-292464d9a38e.png">
<img width="222" alt="Screen Shot 2020-11-05 at 9 23 26 am" src="https://user-images.githubusercontent.com/2867511/98178600-ba61a580-1f48-11eb-892a-a131d960396c.png">
<img width="245" alt="Screen Shot 2020-11-05 at 9 23 20 am" src="https://user-images.githubusercontent.com/2867511/98178603-bd5c9600-1f48-11eb-9f73-f7032ecbe183.png">

**Comment by scleaver** [comment]
I'll handle this one in the next few days. So it sounds like the preference is to add a black border to the existing icon, increase size and change colour to white.

**Comment by deanmarcussen** [comment]
Yeah I'm not attached to the current picker. Just went with the existing `$pink` color the media app uses, because I couldn't see the white on an image I was using.

Ideas sound good

**Comment by sebastienros** [comment]
I have this image, the current crosshair doesn't work

![image](https://user-images.githubusercontent.com/1165805/99294202-992a7000-27f8-11eb-9db5-2fe9e242ceca.png)

**Comment by agriffard** [comment]
I suggest to use this image:

![image](https://user-images.githubusercontent.com/703248/99294968-17146880-2845-11eb-9149-bec87d68cd28.png)

**Comment by Skrypt** [comment]
And the week is only starting 🤣
