### ISSUE TITLE
TitlePart hints without a pattern is sometimes misleading

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7515]
Came across some issues with TitlePart hints with certain settings may mislead content editors. The reason I cam across this cause I was testing a site and thought "I don't remember setting a pattern for the title generation" and then I went and checked the settings.

#### Test 1
**Option:** Title is editable and required
**Pattern:** EMPTY
**Hint:** `The title of the content item. It will be automatically generated.`
**Issue:** What is being automatically generated? This misleads thinking that something automatic will happen when in fact it won't.
**Suggest:** If the pattern is empty omit "It will be automatically generated" however see test 2 for additional thoughts.

#### Test 2
**Option:** Title is editable and required
**Pattern:** {{ ContentItem.Content.Product.Name.Text }}
**Hint:** `The title of the content item. It will be automatically generated.`
**Issue:** There doesn't seem to be a way that this causes automatic generation. Because the title can't be left empty the pattern will not fire. Not sure if I am missing some understanding of the functionality here that would allow the automatic generation to fire.
**Suggest:** Not sure.

#### Test 3 (Article in Blog theme uses this)
**Option:** Title is editable
**Pattern:** EMPTY
**Hint:** `The title of the content item. Set empty to generate it using the pattern.`
**Issue:** There is no pattern so saying set it to empty to generate misleads editors.
**Suggest:** If the pattern is empty omit "Set empty to generate it using the pattern."

#### Test 4
**Option:** Title is editable
**Pattern:** {{ ContentItem.Content.Product.Name.Text }}
**Hint:** `The title of the content item. Set empty to generate it using the pattern.`
**Issue:** No issues works as expected. Stays the same if the title has a value and is the same as Subtitle if left empty.

Not a huge issue but "The title of the content item" is kind of stating the obvious and I wonder if it is really necessary as it distracts from the important part of the hint.

**Comment by jptissot** [comment]
I agree with these suggestions.
