### ISSUE TITLE
Admin menu link - icon picker: background single icon dark  

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#7519]
If you try to add an icon to a admin menu link I see this page:
![admin_menu_icon](https://user-images.githubusercontent.com/2736009/98235063-9b234200-1f61-11eb-8563-3b72a76a1f2c.jpg)

**Comment by deanmarcussen** [comment]
Yes, I saw that issue yesterday as well.

Does it happen with the TextField icon picker as well? or is it just a regression on the admin menu icon picker?

**Comment by PiemP** [comment]
> Does it happen with the TextField icon picker as well? or is it just a regression on the admin menu icon picker?

I check this

**Comment by PiemP** [comment]
Seem happen only in the admin menu link interface: 
![iconpicker_bg](https://user-images.githubusercontent.com/2736009/98238643-fefc3980-1f66-11eb-8877-568328a3535c.jpg)
