### ISSUE TITLE
Uncaught TypeError: jQuery(...).kendoComboBox is not a function

### ISSUE THREAD

**Issue by MRSheikh** [OrchardCMS/OrchardCore#7525]
hi. 
i wrote a module and add `kendo.all.js`  and other Kendo Ui  bundles to my project within implementing IResourceManifestProvider:

```
public class ResourceManifest : IResourceManifestProvider{
public void BuildManifests(IResourceManifestBuilder builder)
{  
          var manifest = builder.Add();
            manifest
                .DefineScript("jquery")
                .SetUrl("~/PMS/Assets/lib/kendo/js/jquery.min.js");

           manifest
                .DefineScript("jquery2")
                .SetUrl("~/PMS/Assets/JS/jquery-migrate-3.3.1.min.js");

            manifest
                .DefineScript("kendo1")
                .SetUrl("~/PMS/Assets/lib/kendo/js/kendo.all.min.js");
            manifest
                .DefineScript("kendo2")
                .SetUrl("~/PMS/Assets/lib/kendo/js/kendo.core.min.js");
            manifest
                .DefineScript("kendo3")
                .SetUrl("~/PMS/Assets/lib/kendo/js/kendo.data.min.js");
            manifest
                .DefineScript("kendo4")
                .SetUrl("~/PMS/Assets/lib/kendo/js/kendo.aspnetmvc.min.js");
            manifest
                .DefineScript("kendo5")
                .SetUrl("~/PMS/Assets/lib/kendo/js/kendo.combobox.min.js");
            manifest
                .DefineStyle("kendo1")
                .SetUrl("~/PMS/Assets/lib/kendo/css/web/kendo.bootstrap-v4.min.css");
            manifest
                .DefineStyle("kendo2")
                .SetUrl("~/PMS/Assets/lib/kendo/css/web/kendo.default.min.css");
        }
    }
```

and in to my Index view i use <script> tag helper and call kendo combobox but javascript error occured on my page:

> Uncaught TypeError: jQuery(...).kendoComboBox is not a function

```
@using Kendo.Mvc.UI
@model IEnumerable<PMS.Models.Persons>;
@addTagHelper *, OrchardCore.ResourceManagement
<style asp-name="kendo1"></style>
<style asp-name="kendo2"></style>
<script asp-name="jquery"></script>
<script asp-name="kendo1"></script>
<script asp-name="kendo2"></script>
<script asp-name="kendo3"></script>
<script asp-name="kendo4"></script>
<script asp-name="kendo5"></script>`

<div>
@(Html.Kendo().ComboBox()
        .Name("size")
        .Placeholder("Select size...")
        .BindTo(new List<string>() {
            "X-Small",
            "Small",
            "Medium",
            "Large",
            "X-Large",
            "2X-Large"
        })
        .SelectedIndex(0)
        .Suggest(true)
        .HtmlAttributes(new { style = "width:100%;" })
        )

</div>
```

**Comment by jptissot** [comment]
Use DependsOn for your scripts ?

**Comment by MRSheikh** [comment]
> 
> 
> Use DependsOn for your scripts ?

i edit <script> tag s to
`<script asp-name="kendo1" depends-on="jquery"></script>
<script asp-name="kendo2" depends-on="jquery"></script>
<script asp-name="kendo3" depends-on="jquery"></script>
<script asp-name="kendo4" depends-on="jquery"></script>
<script asp-name="kendo5" depends-on="jquery"></script>`
and it works fine!!!
thanks a lot jptissot .

**Comment by diepxuansong** [comment]
<link rel="stylesheet" href="/lib/kendo/css/web/kendo.default-ocean-blue.min.css">
    <link href="~/lib/kendo/css/web/kendo.bootstrap-v4.min.css" rel="stylesheet" />
    <link href="~/lib/kendo/css/web/kendo.default.min.css" rel="stylesheet" />
    <script depend-on="jquery" src="~/lib/kendo/js/jquery.min.js"></script>
    <script depend-on="jquery" src="~/lib/kendo/js/kendo.all.min.js"></script>
    <script depend-on="jquery" src="~/lib/kendo/js/kendo.core.min.js"></script>
    <script depend-on="jquery"  src="~/lib/kendo/js/kendo.data.min.js"></script>
    <script depend-on="jquery"  src="~/lib/kendo/js/kendo.combobox.min.js"></script>
    <script depend-on="jquery" src="~/lib/kendo/js/kendo.aspnetmvc.min.js"></script>


I followed that but still got the same error
