### ISSUE TITLE
On deletion of media (.svg and .ico) files an error indicating file is locked is thrown

### ISSUE THREAD

**Issue by SteeveDumais** [OrchardCMS/OrchardCore#7533]
When I try to delete an .svg or a .ico file an error indicating that the file is locked and the file is not deleted.  This happens both when the files are stored in an azure blob or locally on the serer.

System.IO.IOException: The process cannot access the file 'C:\Dayforce\DayforceHub\Dayforce\Dayforce.Cms.Web\Configurations\Sites\Default\Media\asdf\ico-add.svg' because it is being used by another process.

   at System.IO.FileSystem.DeleteFile(String fullPath)

   at System.IO.File.Delete(String path)

   at OrchardCore.FileStorage.FileSystem.FileSystemStore.TryDeleteFileAsync(String path) in C:\Dayforce\DayforceHub\OrchardCore\src\OrchardCore\OrchardCore.FileStorage.FileSystem\FileSystemStore.cs:line 112

**Comment by sebastienros** [comment]
Does it repro consistently? Only with these extensions? Did you just upload these files?

**Comment by SteeveDumais** [comment]
Its consistent and only happens with these extensions.  I have tried others.,

**Comment by SteeveDumais** [comment]
I found the issue we were calling RetrieveFileStreamAsync.  This was the call that was locking the file.  I modified the call to close the stream and now everything works

**Comment by sebastienros** [comment]
@SteeveDumais so this one in a module of yours?

**Comment by SteeveDumais** [comment]
No RetrieveFileStreamAsync is in orchard core we just called from our code, then we closed the file stream in our code and everything seems to work fine
