### ISSUE TITLE
ResetPasswordViewModel requires an email address to be provided as the user identifier

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#7538]
[ResetPasswordViewModel](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/ViewModels/ResetPasswordViewModel.cs) requires that an email address be provided as the user identifier. But looking at how the property is used [here](https://github.com/OrchardCMS/OrchardCore/blob/7a2e676b44dd1c9070c9b8495e6a6c07aa99c941/src/OrchardCore.Modules/OrchardCore.Users/Controllers/ResetPasswordController.cs#L132) and [here](https://github.com/OrchardCMS/OrchardCore/blob/7a2e676b44dd1c9070c9b8495e6a6c07aa99c941/src/OrchardCore.Modules/OrchardCore.Users/Controllers/AdminController.cs#L415), it seems like a username or an email address should be acceptable, since `IUserService.ResetPasswordAsync` works with either.

The reason I bring this up is because the user _has_ to provide an email address to complete the reset, but that seems potentially misleading since they log in with a username. Also, browsers and password managers will pick up on the change and think the email address is the username.

It's nothing critical, just struck me as odd.

**Comment by sebastienros** [comment]
Maybe a security measure to ensure you know which email was used. Could you check on the ASP.NET repository default templates if they use the same technique, I would assume they do.

**Comment by rjpowers10** [comment]
@sebastienros Perhaps you're right, although you also have to provide the reset token. Maybe knowing the email address is an extra level of security.

I didn't find an definitive answer, but [this sample](https://github.com/dotnet/aspnetcore/blob/1e1293ad01061adc036ac7c6e8e1e0263a6065fa/src/Identity/samples/IdentitySample.Mvc/Models/AccountViewModels/ResetPasswordViewModel.cs#L13) also uses the email address.

**Comment by rjpowers10** [comment]
Depending on what happens with #7540 this could be correct behavior.

**Comment by rjpowers10** [comment]
Obsolete. #7613 removed `IUserService.FindByUsernameOrEmailAsync`.
