### ISSUE TITLE
UserService.FindByUsernameOrEmailAsync could find a user other than the one intended

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#7540]
[UserService.FindByUsernameOrEmailAsync](https://github.com/OrchardCMS/OrchardCore/blob/7a2e676b44dd1c9070c9b8495e6a6c07aa99c941/src/OrchardCore/OrchardCore.Users.Core/Services/UserService.cs#L213) first tries to find a user by username, then by email address.

However, what should happen in this scenario, where the email address of one user is the username of another? I was able to create these users in a fresh site using the blog theme.

![image](https://user-images.githubusercontent.com/68876423/98409712-566ed800-2041-11eb-8fea-e353036f7d1d.png)

It seems like `UserService.FindByUsernameOrEmailAsync` will always prefer the user with the name over the user with the email.

At a minimum, I know the reset password feature uses this method, so the reset email could be sent to the wrong user.

**Comment by sebastienros** [comment]
Reset password should only use emails.

**Comment by sebastienros** [comment]
At least we need to review we are still on par with what ASP.NET Identity UI is doing.

**Comment by rjpowers10** [comment]
Related to #7538

**Comment by rjpowers10** [comment]
Looks like the reset password feature is the only caller of `UserService.FindByUsernameOrEmailAsync`, so it could potentially be changed to strictly be an email lookup.

**Comment by kevinchalet** [comment]
@rjpowers10 thanks for reporting that.

I tried locally, and luckily, this issue doesn't allow stealing an account, as there's the generated user token is correctly attached to the second account (to which the reset token is tied based on its user ID, not the username/email address).

That said, it's a major issue anyway, as it allows an attacker to prevent someone from resetting his/her password using the email address (it's the same targeted DOS attack we mentioned in a recent PR trying to generalize this double lookup system).
