### ISSUE TITLE
Create new tenant during setup crashes

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#7547]
Using latest dev branch with sql server express database I am creating a new tenant from the admin with following settings (using blog recipe) :
 

![image](https://user-images.githubusercontent.com/1516981/98461488-29dbcd00-21b5-11eb-8196-76c42f0ae81b.png)

**Then during setup when completing the installation it crashes with following message :**

![image](https://user-images.githubusercontent.com/1516981/98461532-74f5e000-21b5-11eb-83d2-f0241d99be1e.png)

@jtkech

**Comment by jtkech** [comment]
`Invalid serial number for shell descriptor`

It happens when you setup a tenant but a document table already exists in the database and with a shell descriptor document, so with an higher version than the one we are setting up

**Comment by giannik** [comment]
thanks @jtkech ,
there was something wrong with my recipe !!
Thanks for the pointer.
