### ISSUE TITLE
Trumbowyg/Best Practices Question...

### ISSUE THREAD

**Issue by thierholzer** [OrchardCMS/OrchardCore#755]
So the wyswig editor defaults replaces all div tags with p tags or removes them on save if there are already nested p tags which is really annoying, and I know where to remove that logic but is it best practice for me to copy the script to my own resources module or is that going to become an issue for updates and upgrades in the future? Just curious what's the best practice for things like this. 

Thanks.

**Comment by sebastienros** [comment]
Right now I'd suggest to use a simple TextArea "editor" for the things that don't work with wysiwyg. Also we might have modules that provide other editors as we find better ones, or you want to use some that suit you better.

Are you using the Flow page or just the page? With a Flow page it would be easier to switch between them.

**Comment by thierholzer** [comment]
I'm using just the page. I think I left at the conference when you started going over flow page.  :)
Whats the difference between the two? Or is there information somewhere? 

Thanks.

**Comment by sebastienros** [comment]
You should watch the video, it's much more powerful. Instead of editing a monolithic piece of html, you can make it from widgets, and organize the layout of the widgets, without the UI complexity of drag and dropping.
