### ISSUE TITLE
Question: Is it possible to get the date/time a User last logged in?

### ISSUE THREAD

**Issue by jaketyb** [OrchardCMS/OrchardCore#7554]
Hi,

I would like to know if it's possible to retrieve login audit data for a particular user, for example date/time last logged in, and maybe even login history. The aim of which is to detect which users are more active than others.

I can't seem to find any property on the 'User' model which provides this information.

Thanks.

**Comment by hishamco** [comment]
Have a look to Audit Trail module, I think it provide a rich details info, @Piedone correct me if I'm wrong

**Comment by Piedone** [comment]
Yes, this will be (is) available with Audit Trail: https://github.com/OrchardCMS/OrchardCore/pull/6679
