### ISSUE TITLE
Can't create new users anymore, stuck in loop

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/OrchardCore#7560]
Just updated to the latest bits on dev, can't create new users anymore.

Code is stuck in this loop:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs#L87

Not sure why. A new UserId is generated correctly but the query still finds it.

**Comment by sebastienros** [comment]
Because assigning a new userid to the object and then doing a query will store the new value before doing the query?
It should be assigned to a local variable and tested against it, then assign it to the user.

**Comment by scleaver** [comment]
Adding to this issue... the user seems to be created but is caught in loop. If you exit out and go back to the users page, the user is in the list but on clicking the edit button the user is not found.

**Comment by 4m-world** [comment]
After updating to the latest OC 15520 it resolved the issue of the deadlock when creating a new user account, however, now a new issue came up where {{ Model.ContentItem.Owner }} returns a unique identifier in place of the username.

**Comment by deanmarcussen** [comment]
That is correct, it is a design change.

**Comment by 4m-world** [comment]
@deanmarcussen  it is an excellent decision, my question now how I retrieve the user information?

**Comment by jptissot** [comment]
@4m-world we just merged something this afternoon. See https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#user_id-filter 

I will be renaming the https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#get_users-filter shortly

**Comment by 4m-world** [comment]
So now to get Content owner it will be something like this?
{% assign user = Model.ContentItem.Owner | get_users %}
{{ user.UserName }}
right?

**Comment by jptissot** [comment]
Yes. I just renamed the filter to `users_by_id` but that should work yes :)

**Comment by 4m-world** [comment]
> That is correct, it is a design change.

Hi I noticed in the new build that content resumed reflecting username under Owner, and Author properties of the ContentItem. Is that a permanent change?
Because when you run the the "users_by_id" update the contentItem user details moved to store user id.
