### ISSUE TITLE
Admin permissions - intention of the "manage settings" permission

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#7561]
I want to give a particular role _very_ restricted access to the admin panel. This role should only be able to edit one custom setting that I have defined. To do this, I

1. Grant permission to "Access admin panel" under OrchardCore.Admin
2. Grant permission to _my custom permission_
3. Require _my custom permission_ to edit _my custom setting_

At first glance this seems like it will work. A user with this role can view the admin panel and can see the menu item for my custom setting. But, clicking my menu item results in a forbid result.

The one way I've found to fix this is to also grant permission to "Manage settings" under OrchardCore.Settings.

So far, I think this is working as intended. The issue is, once I grant permission to "Manage settings", the user can also view and edit the site's general settings (site name, base url, time zone, use framework CDN, etc). I'm wondering if those settings are incorrectly tied to "Manage settings", which I _think_ was supposed to be used in a more generic sense.

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/5328

**Comment by sebastienros** [comment]
Makes sense, we need a separate permission.
Closing as a duplicate though.
