### ISSUE TITLE
Taxonomy Term ContentPart with NumberField is not saved

### ISSUE THREAD

**Issue by snovak7** [OrchardCMS/OrchardCore#7571]
So I have a ContentItem with a ContentType "Taxonomy" and a Taxonomy field...
Then I have in ContentItem defined that Taxonomy of "Tags" ContentType which is in use... I can easily add, edit those ContentItems of ContentType Tag... especially a Number Field which is part of a new ContentPart which is applied to "Tag"... When this item is edited as a ContentItem it works. But when you want to edit it as a Term, saving is not possible, the field is shown, but as saving it, it is emptied.

**Comment by deanmarcussen** [comment]
The issue sounds very similar to this fix for Menus https://github.com/OrchardCMS/OrchardCore/pull/7381/files
