### ISSUE TITLE
Media Gallery : Implement owned media

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#7576]
Now that we have the UserId next step logical would be to insert back the ManageOwn permission on the Media Gallery and to implement a specific folder for each users based on the UserId. If the user has ManageOwn permission he should be able to only see his own folder in the Media Gallery and on the Media Gallery Picker Field and so on ...

/cc @deanmarcussen

**Comment by hishamco** [comment]
Ya it's the time to do it

**Comment by JoshTango** [comment]
I agree !! Do it do it do it now !!

**Comment by deanmarcussen** [comment]
Feel free to work on it @JoshTango

**Comment by Skrypt** [comment]
Yeah, I'm kind of busy working on some other PR's already 😉
