### ISSUE TITLE
Custom query schema parsing not working

### ISSUE THREAD

**Issue by tropcicstefan** [OrchardCMS/OrchardCore#7598]
I think method BuildSchemaBasedFieldType inside LuceneQueryFieldTypeProvider.cs and SqlQueryFieldTypeProvider.cs is wrong because [official json ](https://json-schema.org/learn/miscellaneous-examples.html)schema should look something like this&nbsp;
 ```
{
    "type": "object",   
    "properties": {  
        "firstName" : {
            "type" : "string"
        },
        "age": {
            "type": "integer"
        }
     } 
} 
 ```
and line where code tries to get type specifically "child["type"]" will throw error of "System.InvalidOperationException: 'Cannot access child value on Newtonsoft.Json.Linq.JProperty.'"
```
foreach (var child in properties.Children())
    {
        var name = ((JProperty)child).Name;
        var nameLower = name.Replace('.', '_');
        var type = child["type"].ToString();
...
```
fix should be something along the lines of
```
var properties = querySchema["properties"];

foreach (JProperty child in properties.Children())
{
    var name = child.Name;
    var nameLower = name.Replace('.', '_');
    var type = child.Value["type"].ToString();
```
(and properties key should probably be lowercase)

**Comment by sebastienros** [comment]
Honestly I don't think anyone has ever tried it. I was even for removing this, or at least moving the field to somewhere less visible. If you think you can fix it please provide a PR, and if you can contribute a little bit of documentation that would help. Thanks.
