### ISSUE TITLE
Incorrect SQL Query result at Content Level

### ISSUE THREAD

**Issue by 4m-world** [OrchardCMS/OrchardCore#7600]
I wrote a SQL query to retrieve content-type based on a taxonomy, in my case blog posts under a specific category, the issue I face is as follows: Running the query in the query windows retrieves the correct content however in the content template the received content is not relevant to the taxonomy.

### SQL Query
```SQL
SELECT * 
FROM [ContentItemIndex] WHERE [Latest] = 1 
AND [Published] = 1
AND [ContentType] = 'BlogPost' 
AND [ContentItemId] IN (
 SELECT [ContentItemId]
  FROM [TaxonomyIndex] 
 WHERE [TermContentItemId] = @termId 
     AND [ContentType] = 'BlogPost' 
 LIMIT @limit)
 ORDER BY [CreatedUtc] DESC LIMIT @limit;
```

### Query Parameters

`
{ "termId": "42nksr2j68csmrafgaz0dcz9xa", "limit":5}
`

### Screenshots 

![Query Screen Image](https://lh3.googleusercontent.com/K-Cnlr3pu4PEqU-IzocdShMdEGM2oypguOUMI_sxDzY9k2iVUtkI71bbyu9XGCDgIZEllkK1zwqV1A=w1834-h526-rw)

https://drive.google.com/file/d/14am5sx8YMFVkQSrE20AJD2WQy2bdMsuL/view?usp=sharing

![Content Page Image](https://lh4.googleusercontent.com/WOCvYlL4JSlXqZz7blZnI8Qu71h905RHUDu94k4qWH35W76DBw8nPrwlYe5T8-8x2WuaPSXlVTOaYb7uG9sD=w1834-h526-rw)

https://drive.google.com/file/d/1hnfBnFSUdHVXceaKtQA8BgDUwTUSfJru/view?usp=sharing

### Content Razor code:

** content layout name **:  Term-Category.cshtml
```Razor
@{
    async Task<IEnumerable<ContentItem>> GetCategoryPosts(string termId, int limit = 6)
    {
        var parametes = new Dictionary<string, object>();
        parametes.Add("termId", termId);
        parametes.Add("limit", limit);

        return await Orchard.ContentQueryAsync("BlogCategories", parametes);
    }
}
@if ((bool)Model.HasItems)
{
    @foreach (var item in Model.Items)
    {
        <section class="category-item recent-posts">
            @item.TermContentItem.ContentItemId<br />
            @await DisplayAsync(item)

            @{
                var posts = await GetCategoryPosts(item.TermContentItem.ContentItemId);
            }
            @foreach(var post in posts)
            {
                @post.ContentItemId
                <hr />
                @*@await Orchard.DisplayAsync(post, "Summary")*@
            }
        </section>
    }
}
else
{
    <section>
        <div class="container">
            <div class="text-center">
                <h3>@T["No categories to display"]</h3>
                <a class="btn" href="@Url.Content("~/")">@T["Home"]</a>
            </div>
        </div>
    </section>
}
```

I'm using OrchardCore NuGet version 1.0.0-rc2-15409 where same behaviour was observed on previous versions, where I though at the begging there is an issue with the query, therefore, I did not report the case

**Comment by sebastienros** [comment]
The queries you pasted and the one on the screenshot don't match. One is filtering on DocumentId, the other on ContentItemId.
If you are filtering specific versions (latest, published) then you should select the "DocumentId" and use the check box to return the Documents.

**Comment by 4m-world** [comment]
> The queries you pasted and the one on the screenshot don't match. One is filtering on DocumentId, the other on ContentItemId.
Apologies I pasted the wrong code it the same as in the screenshot, on the ContentId level, as I tried different options to verify the output.  

BlogCategories is a SQL query as in the screenshot.
 
> If you are filtering specific versions (latest, published) then you should select the "DocumentId" and use the check box to return the Documents.

I tried both options the output varied between query screen and at rendered content under Term-Category.cshtml

**Comment by 4m-world** [comment]
After investigating further into the case it appears there is an issue with query output when I tried to perform it from the Term or TermItem template.

I ran the query inside a custom liquid page the content retrieved correctly and rendered correctly.

I do not know shall I keep this ticket open or close?!
