### ISSUE TITLE
SqliteException: SQLite Error 1: 'no such table: AutoroutePartIndex'

### ISSUE THREAD

**Issue by josephwambura** [OrchardCMS/OrchardCore#7608]
![image](https://user-images.githubusercontent.com/10076231/99025198-56a73000-2579-11eb-9cf7-285256c38807.png)

**Comment by josephwambura** [comment]
`Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int rc, sqlite3 db)
Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in ProfiledDbCommand.cs
Dapper.SqlMapper.QueryAsync<T>(IDbConnection cnn, Type effectiveType, CommandDefinition command) in SqlMapper.Async.cs
YesSql.Store.ProduceAsync<T>(WorkerQueryKey key, Func<object[], Task<T>> work, object[] args)
YesSql.Services.DefaultQuery+Query<T>.ListImpl()
OrchardCore.Autoroute.Services.AutorouteEntries.CreateDocumentAsync() in AutorouteEntries.cs
+
            var indexes = await Session.QueryIndex<AutoroutePartIndex>(i => i.Published).ListAsync();
OrchardCore.Documents.DocumentManager<TDocument>.GetOrCreateImmutableAsync(Func<Task<TDocument>> factoryAsync) in DocumentManager.cs
+
                    document = await (factoryAsync?.Invoke()
OrchardCore.Autoroute.Services.AutorouteEntries.TryGetEntryByPathAsync(string path) in AutorouteEntries.cs
+
            var document = await GetDocumentAsync();
OrchardCore.ContentLocalization.Services.ContentCulturePickerService.GetContentItemIdFromRouteAsync(PathString url) in CulturePickerService.cs
+
                (var found, var entry) = await _autorouteEntries.TryGetEntryByPathAsync(url.Value);
OrchardCore.ContentLocalization.Services.ContentCulturePickerService.GetLocalizationFromRouteAsync(PathString url) in CulturePickerService.cs
+
            var contentItemId = await GetContentItemIdFromRouteAsync(url);
OrchardCore.ContentLocalization.ContentRequestCultureProvider.DetermineProviderCultureResult(HttpContext httpContext) in ContentRequestCultureProvider.cs
+
            var localization = await culturePickerService.GetLocalizationFromRouteAsync(httpContext.Request.Path);
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
OrchardCore.Diagnostics.DiagnosticsStartupFilter+<>c__DisplayClass3_0+<<Configure>b__1>d.MoveNext() in DiagnosticsStartupFilter.cs
+
                    await next();
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
OrchardCore.ContentPreview.PreviewStartupFilter+<>c+<<Configure>b__1_1>d.MoveNext() in PreviewStartupFilter.cs
+
                    await next();
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in ModularTenantRouterMiddleware.cs
+
            await shellContext.Pipeline.Invoke(httpContext);
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute, bool activateShell) in ShellScope.cs
+
                await execute(this);
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
+
                await shellScope.UsingAsync(scope => _next.Invoke(httpContext));
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by deanmarcussen** [comment]
It looks like you have a failed migration at some point during your setup and some tables have not been created correctly.

Which version of OC?

Do you have any custom migrations?

Can you check with a clean setup if you have any error messages in the log files `App_Data/logs` during the setup process
