### ISSUE TITLE
Cypress Docs

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#7612]
@jptissot could we have a starter docs for how to functional test OC using Cypress, I'm impressed by your demo on last standup, but seems I miss something to make the tests run

**Comment by jptissot** [comment]
### Run once: 
```
npm install
npm run cms:setup  //  careful... this will delete your App_Data
```
The tests assume you the root tenant is setup as a SaaS tenant, the cms:setup command sets this up for you.


### Build & Run OC in a console: 
```
 cd .\test\Functional\
// Builds the code
npm run cms:build
// Hosts oc in release mode
npm run cms:host
```

### In another console, run cypress UI:
```
cd .\test\Functional\
npm run cms:cypress
```

Then, you can run the unit tests as much as you want.

**Comment by hishamco** [comment]
Is this required OC instance up & running?

**Comment by jptissot** [comment]
npm run cms:build
// Hosts oc in release mode
npm run cms:host

this will build and host the CMS site. Yes

**Comment by jptissot** [comment]
npm run cms:setup will delete your  OrchardCore.Cms.Web/App_Data  folder and set a default tenant to be the SaaS tenant.

**Comment by hishamco** [comment]
Wow!! finally it works .. thanks a lot Jean Phillipe, I will keep this open for documentation, if you want to start this or I will do it in your behalf

@agriffard where shall we add this?

**Comment by jptissot** [comment]
I had this issue opened: https://github.com/OrchardCMS/OrchardCore/issues/7534

**Comment by hishamco** [comment]
So closing this ;)

**Comment by jtkech** [comment]
@jptissot 

> this will delete your App_Data

Is it possible to run the app in another working directory? So that a new `App_Data` is created elsewhere

As we do when running our web app through some unit tests

**Comment by jptissot** [comment]
Yes that should be easy, all the testing framework needs is a running app. Nothing more.
