### ISSUE TITLE
Unknown connection type: Microsoft.Data.Sqlite.SqliteConnection

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#7614]
Hi,
My tests started breaking in a non-deterministic way after updating from 1.0.0-rc2-**15309** to 1.0.0-rc2-**15457**.
Throws this error: Unknown connection type: Microsoft.Data.Sqlite.SqliteConnection

The YesSql version was updated, might it have something to do with that?
I found a commit related to this: https://github.com/sebastienros/yessql/commit/ed59267a8f0a099bd5caf349422ec8959ba8dde9

More info on the tests - out of 400 tests, about 5 start breaking. On a re-run, they succeed and others start breaking.

I wasn't sure if I should open an issue here or on the YesSql repository...

**Comment by hishamco** [comment]
Could you move this to YesSQL repo

**Comment by mariojsnunes** [comment]
Sure, here it is https://github.com/sebastienros/yessql/issues/292

**Comment by hishamco** [comment]
Thanks

**Comment by sebastienros** [comment]
New packages should be published soon on nuget. We will also be able to change on MiniProfiler wraps the connections
