### ISSUE TITLE
Investigate nuget package symbols

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7617]
Investigate how to add symbols to the nuget files published to cloudsmith (unless they are already there) 

Something to try is to add `--include-symbols -p:SymbolPackageFormat=snupkg` to the `dotnet pack` command but I am not sure these will be included to the push ?

**Comment by jptissot** [comment]
See: https://github.com/NuGet/Home/issues/4142#issuecomment-350069305
```
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

**Comment by jtkech** [comment]
@jptissot @Skrypt 

Look at the `Directory.Build.targets/props` files we have under the modules / themes folders

We already have

    <PropertyGroup>
      <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>

And the following meaning all is embedded including source files

    <PropertyGroup>
      <DebugType>embedded</DebugType>
      <EmbedAllSources>true</EmbedAllSources>
    </PropertyGroup>

But there is a pending PR #7237 by @ns8482e that may change it

**Comment by jptissot** [comment]
So, no need to include the `snupkg` files ?

**Comment by jtkech** [comment]
Yes we don't need for now

But maybe better to use `snupkg` as suggested in #7237

So if it get merged we will have to also publish symbol packages

**Comment by jptissot** [comment]
I don't think cloudsmith supports snupkg. But I might be missing something: 
https://help.cloudsmith.io/docs/nuget-feed#current-limitations

**Comment by jtkech** [comment]
Yes, `symbol server is not yet supported`

Here it's a "little" + in the pros and cons to keep them embedded

**Comment by hishamco** [comment]
If I'm not wrong @lahma already did that for Fluid, so I think he could help in this one

**Comment by lahma** [comment]
Yeah basically Fluid and others which rely on MyGet just skip publishing symbols against MyGet (non-release branch build). Downside is not getting the symbols of course but I'd consider NuGet main distribution medium and even then knowing how to take advantage of symbols requires a bit more effort anyway.

Here's the [Fluid PR](https://github.com/sebastienros/fluid/pull/213/files) for reference, main points being the `Common.props` (ideally `Directory.Build.props` for people to recognize the idiomatic pattern) and then the `appveyor.yml` configuration.

**Comment by Piedone** [comment]
Cloudsmith now supports symbols: https://help.cloudsmith.io/docs/nuget-symbol-server
