### ISSUE TITLE
Bracket can get removed from field when running a recipe

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7623]
If you fill a TextField starting with `[` and ending with `]` and export it. Add it to a recipe in your module. When the field is imported, the starting `[` and last `]` are removed.

Before export:
![image](https://user-images.githubusercontent.com/4681586/99117880-829bd300-25c4-11eb-9d92-5f3a7c6c8e48.png)

After import:
![image](https://user-images.githubusercontent.com/4681586/99117912-91828580-25c4-11eb-8207-bc44ee2b7982.png)

**Comment by sebastienros** [comment]
Fix the recipe handler custom script substitution. Something that looks for `[ js :` by looking for the first thing that is not `Char.IsLetter` and it should be a `:`. If not, then don't do any substitution.
