### ISSUE TITLE
MarkdownBody editor fullscreen issue

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7625]
The markdown editor is hidden by the admin's navbar when in fullscreen mode
![image](https://user-images.githubusercontent.com/4681586/99127085-75d3ab00-25d5-11eb-970e-b293f15f260d.png)

/cc @Skrypt

**Comment by hishamco** [comment]
Ya this obvious could happen, I will fix this, perhaps the same may happen for other editors

**Comment by hishamco** [comment]
I thought it's a `z-index` issue, but seems it's something else ;) I will push a fix soon ...

**Comment by jptissot** [comment]
@agriffard should the editor display the toobar when in full screen mode ?

**Comment by agriffard** [comment]
Yes, it should:
https://simplemde.com/

**Comment by hishamco** [comment]
@jptissot I will have a look

**Comment by jptissot** [comment]
Reopening because the toolbar should be displayed in full screen mode

**Comment by hishamco** [comment]
Ok it's in my plate ;)

**Comment by aaronamm** [comment]
FYI, it happens to me as well. 
Content go under tool bar. 
Here is the screenshot and please ignore my dark theme.

![image](https://user-images.githubusercontent.com/2938310/100997612-0b3add00-358d-11eb-9367-d64def672373.png)

For @agriffard when say
> Yes, it should:
> https://simplemde.com/
I don't quite understand it but I think https://github.com/sparksuite/simplemde-markdown-editor is an inactive project.
Right now, we use https://github.com/ionaru/easy-markdown-editor which is actively deployment and I think it is a right one to use.

**Comment by Skrypt** [comment]
I thought this issue was fixed I will take a look at it today.

**Comment by aaronamm** [comment]
@Skrypt Thanks for following up.
Please let me know if there is a proplem that I need to build JavaScript to fix.

**Comment by Skrypt** [comment]
Tomorrow first thing.

**Comment by aaronamm** [comment]
@Skrypt 
FYI, I have tried to fix this issue by creating a custom module to override `MarkdownBodyPart_Edit__Wysiwyg` shape to use the latest version of EasyMDE. (https://www.npmjs.com/package/easymde)

Here are what I found. EasyMDE two main components which are:
- EditorToolbar for tool bar icon
- CodeMirror for markdown content

Therefore, to make the editor shows properly in full screen mode, I need to:

Update .editor-toolbar.fullscreen to 
```
.editor-toolbar.fullscreen{
    z-index: 1030; 
}
```
because we have
```
:root[data-theme='darkmode'] .ta-navbar-top {
    z-index: 1030; 
}
```
---
and update `:root[data-theme='darkmode'] .CodeMirror-fullscreen` to 
```
:root[data-theme='darkmode'] .CodeMirror-fullscreen {
    z-index: 1001;
    top: 50px !important;
}
```

because we have
```
:root[data-theme='darkmode'] .left-sidebar-compact #ta-left-sidebar{
z-index: calc(1000 + 1);
```

FYI, I use dark mode for an admin theme.

Please let me clean up some code and I will share it to you.
Thanks.

**Comment by hishamco** [comment]
@aaronamm could you please send a PR and share a screenshot shows the final fix

**Comment by aaronamm** [comment]
@hishamco I can make a PR and I want to improve it as well.
Could you please reply the issue https://github.com/OrchardCMS/OrchardCore/issues/7881 that I opened?

**Comment by hishamco** [comment]
I saw the other issue, I think it introduces a new package or editor, Am I right?

**Comment by aaronamm** [comment]
@hishamco  You are right.
However, the idea is to use the latest version of EasyMDE and use NPM package instead of adding JavaScript file in the module.
We use a fork of SimpleMDE which has been renamed to EasyMDE.
Technically, I think we don't introduce a new editor.

**Comment by hishamco** [comment]
Please submit a PR that update the package and fix this issue, hope @agriffard don't mind with changing the package

**Comment by aaronamm** [comment]
@agriffard has replied me in this issue https://github.com/OrchardCMS/OrchardCore/issues/7881#issuecomment-740559462 already. 
@hishamco Thanks for supporting.
