### ISSUE TITLE
.net 5 Upgrade

### ISSUE THREAD

**Issue by KannanKrish** [OrchardCMS/OrchardCore#7630]
While I upgrade to .net 5 asp.net core to my project I am getting 

**System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer.WithCulture(System.Globalization.CultureInfo)'**

I want to know Orchard Core supported .net 5?

**Comment by hishamco** [comment]
FYI `WithCulture` has been removed in .NET. For more information follow up with #6999

**Comment by deanmarcussen** [comment]
@KannanKrish Orchard Core is running against .net core 5, as of last week.

You will need the preview feed. See the docs here to configure the preview feed. https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/

It is not currently built against .net core 5.

@hishamco if you're going to close peoples issues please give them the correct information

**Comment by KannanKrish** [comment]
@deanmarcussen Thanks, friend. Once I upgraded to the preview feed it is working fine.

**Comment by hishamco** [comment]
@deanmarcussen sorry If I close this accidently, but all of us know that `WithCulture` is removed in .NET 5.0, moreover @agriffard opened a PR to upgrade to .NET but not merged yet!!

**Comment by hishamco** [comment]
@deanmarcussen how it's Orchard Core is running but not built against .net core 5?
