### ISSUE TITLE
Update Logger.LogError usage on dotnet core 2.0

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#764]
Once dotnet core 2.0 is available, we need to review all the calls to Log.LogError to use the newly added overload that accepts a message and an exception.

Right now we are doing calls like `LogError("message", exception)` but it is not doing what we assumed. It's actually doing a `String.Format("message", exception)` so in the end `exception` is not displayed if we didn't use `{0}` in the message.

We'll have to change it to `LogError(exception, message)`

**Comment by agriffard** [comment]
Still to be done in many classes.

Ex: In IndexingTaskManager.cs
`Logger.LogError("An error occured while updating indexing tasks", e);`
