### ISSUE TITLE
Limit serving static files to enabled modules only?

### ISSUE THREAD

**Issue by Sherif-Ahmed** [OrchardCMS/OrchardCore#7648]
Right now, if I have a disabled (not enabled) module, I can serve the static files related to it?
Is this the intended behavior?
It would be nice to limit the static files to enabled modules only.

**Comment by sebastienros** [comment]
The static files are served by the host, not tenants and are supposed to be public.
Enabled modules are tenant-specific, so it would not be possible to do that.

@jtkech correct?

**Comment by jtkech** [comment]
@sebastienros yes
