### ISSUE TITLE
Content localization within decoupled website

### ISSUE THREAD

**Issue by draxtor** [OrchardCMS/OrchardCore#7649]
Hello,
I've created decoupled website using Asp.Net Core 3.1 
I'm using orchard core nugets:
![image](https://user-images.githubusercontent.com/3110724/99191743-f4178500-276e-11eb-9b90-8dab654cf959.png)
2 abstraction nugets I've installed out of despair, I don't know what they do I was looking for ILocalizationService which is mentioned on the internet somewhere.
 
I turned on all localization features and created little component for switching languages (eng and fra for now). 
Based on 
`<html lang="@Orchard.CultureName()">`
 it looks that it is working fine.
So I started to localize content types. But I cannot found any way of filtering content items based on culture. 
I've tried:
 ```
   var articles = await _orchard.GetRecentContentItemsByContentTypeAsync("HomeArticles");
   var articles = await _orchard.QueryContentItemsAsync(x=> x.Where(y => y.Published));
```
but all items for all languages are returned.
There are no overload which I can use to send culture info.

Is there a way to use content localization in decoupled website? Or at least to filet content items based on culture.

Thanks

**Comment by hishamco** [comment]
Try to install Content Localization module if you interested in localizable content items
