### ISSUE TITLE
Unable to use MVC in orchard framework application

### ISSUE THREAD

**Issue by MarcBruins** [OrchardCMS/OrchardCore#7650]
It seems that orchard is not finished setting up the shellsettings for the tenants before the view is rendered.
I've adjusted the `multitenantapplication` in the [Orchard.Samples](https://github.com/OrchardCMS/OrchardCore.Samples) to a MVC example.

To enable it, i took the following steps:

- Add `services.AddMvc` to the startup ConfigureServices(this is a different on then the AddMvc from orchard)
- Rename pages to `Views` in the Multitenantapplication project
- Create a `HomeController` inside a `Controllers` folder that points to `Views\Home\Index.cshtml`
- Copy the content of the original Index.cshtml to the new view and remove the `@page`attribute
- In the `Configure(IApplicationBuilder app, IWebHostEnvironment env)` method call add `app.UseEndpoints(endpoints => endpoints.MapDefaultControllerRoute());`

Because the view(and this is my issue with the real project as well) requires the shellsettings:
``` index.cshtml
@using OrchardCore.Environment.Shell
@using OrchardCore.Environment.Shell.Configuration
@inject ShellSettings settings
@inject OrchardCore.Modules.IApplicationContext app

```

Which are not loaded yet, because the shellsettings are not yet registred. We get a error:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: No service for type 'OrchardCore.Environment.Shell.ShellSettings' has been registered.
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
```

It seems that calling `AddMvc` is calling `AddControllerWithViews` which is loading up the views directly without waiting for the shell setup to finish. So when trying to render the page the ShellSettings are not ready yet. I've you try to access the same page from a different tenant after crash, then it works fine and the output tells that tenants are loaded:

```
dbug: OrchardCore.Environment.Shell.ShellHost[0]
      Registering shell context for tenant 'CustomerA'
```

[Here is a link to the sample](https://github.com/MarcBruins/OrchardCore.Samples/tree/mvcsample)

**Comment by MarcBruins** [comment]
Is there a workaround somebody can think of? Maybe bootstrap the shellsettings initilization earlier or manually to force in the controller to be ready before the view is rendered? 

I would also like to contribute to orchard, but this seems to be targetting orchardcore at the heart which is a bit much for a first step.

**Comment by MarcBruins** [comment]
So i've found out that the shellsettings are not loaded at all for the default tenant even when the view loading is done later in the process. I've did a task run with a delay for 10 seconds on returning the view to see if the shellsettings were loaded, they were not. 

It is however loading if i go the specific tenant page. It is however only loading the settings for that tenant(which is probably the correct behaviour)

**Comment by deanmarcussen** [comment]
@MarcBruins I think the problem is probably with your service registration.

But the link to the samples project you attached above doesn't seem to have any commits in it, so it's hard to suggest your exact issue.

Can you commit something on a branch there, so that it is visible what issue you are struggling with?

**Comment by MarcBruins** [comment]
Oh sorry forgot to push the commit, now it's available(Commit is here: https://github.com/MarcBruins/OrchardCore.Samples/commit/be58609557a2e1c1776d5d058ab27a0bddf719f5)

**Comment by MarcBruins** [comment]
@deanmarcussen as you can see not much has changed only the steps i described in the initial post.There is no other service being registrated then `AddOrchardCore().AddMvc().WithTenats()` and a `AddMvc()` call.

**Comment by jtkech** [comment]
Quite all the things are executed in a tenant container composed of modules / features (we have at least a `Default` tenant), so quite all registrations / pipeline configs need to be done in the context of a tenant, as done by a module / feature startup when it is enabled. The application behaves as a module whose features are always enabled, we have helpers to register / config things from the application but in a tenant context, as done by a regualr module.

So, in your main startup don't call

            services.AddMvc();

If you need more things on the mvc builder, use our  `OrchardCoreBuilder.ConfigureServices()` helper. In the same way, if you want to configure more things use our  `OrchardCoreBuilder.Configure()` helper

            services
                .AddOrchardCore()
                .AddMvc()
                .ConfigureServices(tenantServices =>
                {
                    tenantServices.AddMvc().AddSomeThing(...);
                })
                .Configure(tenantAppBuilder =>
                {
                    tenantAppBuilder.UseSomeThing(...);
                })
                ;

So, also don't call directly

            app.UseHttpsRedirection();

Look at the source code, we have an `OrchardCore.Https` module that does it in its startup, so you could use this module or do it yourself from the app but in a tenant context, so by using our `OrchardCoreBuilder.Configure()` helper

Don't call the following, even if you use using our `.Configure()` helper, as we do it for each tenant.

            app.UseRouting();
            app.UseEndpoints(endpoints => endpoints.MapDefaultControllerRoute());

Finally, to use `WithTenants()` you need to preconfigure your tenants with their preconfigured features, this through a configuration source, e.g. the root appsettings.json. This, as i remember, under an `OrchardCore` section, then for each tenant one child section with the same name, then a `Features` config value defining an array of features to be used. You will also need a set of required config values as the tenant state, the request url prefix and so on.

Maybe better to first not use `WithTenants()` as we have the `Default` tenant, and the app behaves as a module that is always enabled, then see what happens.

You could also first start to just use `AddOrchardCms()`, and then use the admin UI to enabled / disabled modules / features and better understand how they work and collaborate to the tenant composition, then enanble the `.Tenants` feature and create tenants, then see the config values we add in the `tenants.json` file that you could re-use when working again with `WithTenants()`, and so on

**Comment by MarcBruins** [comment]
Thanks JKTech that indeed helps and i works smoothly now. I've moved the service registration to a tenant level. It is however still a bit confusing for me to know when we are in a tenant context and when not. 

What I understand is whenever something is tenant specific use ```  services
            .AddOrchardCore()
            .AddMvc()
            .ConfigureServices(tenantServices =>
            {
                tenantServices.AddMvc().AddSomeThing(...);
            })
            .Configure(tenantAppBuilder =>
            {
                tenantAppBuilder.UseSomeThing(...);
            })
            ;```` or if you are in in the context of a module extend the `: OrchardCore.Modules.StartupBase` for your startup to do the registration.

Is there are case where when we require non specific tenant configuration except for the loading of orchardcore? Or is everything done in a tenant context from that point on? (This sounds most logical to me)

**Comment by jtkech** [comment]
Most of the things are done in a tenant context, a module startup is executed in the context of a given tenant but only if the module / feature is enabled for this tenant (a module can have multiple startups each tied to a feaure), what is defined from the application with our helpers is also executed in a tenant context, and always executed for each tenant, as a module being always enabled.

We can use app level things without our helpers in the main startup, e.g. we use `app.UseStaticFiles()` so that we can serve app level static files, but we also have custom static file providers that are registered and executed in a tenant context.

You can also do some truly app level routing, but if an app level route matches it would bypasses tenant routing and things will not be executed in a tenant container, so without being able to inject tenant services.

**Comment by MarcBruins** [comment]
Thanks so much, this clears it up for me. 👍
