### ISSUE TITLE
WebP: Upgrade SixLabors.ImageSharp and add WebP support to config

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#7657]
Because WebP image format is a big performance boost and becoming more and more of a default image format in browsers, i followed SixLabors in the process to integrade WebP support in their project.
As you can see here: https://github.com/SixLabors/ImageSharp/pull/1271

Since yesterday there is a first version of WebP suppport that should be merged in the master soon(or it is already).
It's marked as "experimental" and is not configured by default in ImageSharp but all the tests for lossy and lossless where looking perferctly fine.

Since i've developed my own extension module for OC and WebP support with ImageSharp Cache, i was hoping for this feature to come and it would be great if someone could please update ImageSharp in OC and configure WebP support in the main configuration of OC ImageSharp.

Because it is only used if someone is trying to resize a WebP image, it shouldn't make any difference for all current websites that use ImageSharp for resizing their JPG, PNG, etc.

I think that you @deanmarcussen are the right person to talk to for this, because i've seen that you implemented these things in the media module.
If i'm wrong, i'm sorry!

Thank you!

**Comment by deanmarcussen** [comment]
Thats exciting @Flarescape I've been looking forward to that pr for sometime as well.

It's not merged yet, so please report back here when it is merged.

In terms of updating Orchard Core, we'll have to wait for a full release to NuGet

But when it is merged you should be able to get it from the ImageSharp myget feed https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp

I don't think we'll have to do anything special to configure it in Orchard Core, but hard to say until it's merged.

**Comment by Flarescape** [comment]
Perfect, thank you!
I'll do that. 👍 

As i've read in the thread around the pr, the feature will be optional because it's in an "experimental" state, so i think it maybe needs a explicit config in MediaImageSharpConfiguration.cs to use it.
But let's see when it's officially merged!

**Comment by johnrom** [comment]
One can enable webp uploads without optimization as explained in the [OrchardCore.Media docs](https://docs.orchardcore.net/en/dev/docs/reference/modules/Media/#configuration).

```cs
services.PostConfigure<MediaOptions>(o => {
    o.AllowedFileExtensions.Add(".webp");
});
```

**Comment by Flarescape** [comment]
Update:
PR: https://github.com/SixLabors/ImageSharp/pull/1552
Close to first release to master.
Two not essential features left to do and performance optimizations.

**Comment by MikeKry** [comment]
Will we update this package so OC can finally support WebP? :) 

Is some need helped here?

**Comment by deanmarcussen** [comment]
I imagine we will do it when ImageSharp release a version which supports WebP to NuGet

Probably quite hard to update it before it is released ;)

**Comment by MikeKry** [comment]
@deanmarcussen  

It seems that it is finally out now in NuGet 🧨

**Comment by Tokyo1985** [comment]
> @deanmarcussen
> 
> It seems that it is finally out now in NuGet 🧨

I confirm that WEBP support is out now in NuGet. You can see some details on these links:

https://github.com/SixLabors/ImageSharp/releases
https://www.nuget.org/packages/SixLabors.ImageSharp/

I'll expect the next release of OrchardCore to get that feature.
