### ISSUE TITLE
How to retrive the final url in a custom Pager_Next_Link.liquid file?

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#7658]
I'm trying to implement the `https://schema.org/SiteNavigationElement` into my theme (i.e. structured data, or microdata) and so I'm trying to customise the Pager shape into something a little more complex.

So far I have a `ListPart.liquid` file which starts with this:

```
{% if Model.ContentItems.size > 0 %}
  {% assign previousText = "Previous" | t %}
  {% assign previousClass = "previous" %}
  {% assign nextText = "Next" | t %}
  {% assign nextClass = "next" %}
  {% 
     shape_pager Model.Pager 
        previous_text: previousText, next_text: nextText, 
        previous_class: previousClass, next_class: nextClass,
        attributes: "{\"role\": \"navigation\", \"itemscope\": null, \"itemtype\": \"http://schema.org/SiteNavigationElement\"}"
  %}
  <nav>
    {{ Model.Pager | shape_render }}
  <nav>

  [The rest of the code with a {% for item in Model.ContentItems %} comes here]
{% endif %}
```

At a second level, I have created a `Pager_Next.liquid` file (and `Pager_Previous.liquid` too, which is basically the same):
```
{% shape_clear_alternates Model %}
{% shape_type Model "Pager_Next_Link" %}
{% shape_add_attributes Model itemprop: "url" %}
{{ Model | shape_render }}
```

And finally, at the deepest level I have `Pager_Next_Link.liquid` (and `Pager_Previous_Link.liquid`):
```
{% assign nextURL = Model.WhatComesHere??? %}
<a itemprop="url" href="{{ nextURL }}">
  <span itemprop="name">{{ "Next" | t }}</span>
</a>
```

I cannot find a way to retrieve this **nextURL** that I need to use in the `href` attribute of the `<a>` tag. It must be something quite easy but the examples in https://docs.orchardcore.net/en/dev/docs/reference/modules/Navigation/ do not go down to such detail and I've run out of ideas trying different things.

The final output should be something like:

```
<nav>
  <ul class="pager" role="navigation" itemscope itemtype="http://schema.org/SiteNavigationElement">
    <li class="previous "><a itemprop="url" href="/en/my-list?before=637139904176677413"><span itemprop="name">Previous</span></a></li>
    <li class="next "><a itemprop="url" href="/en/my-list?after=637127069225504116"><span itemprop="name">Next</span></a></li>
  </ul>
</nav>
```

**Comment by Skrypt** [comment]
Url's are generated from inside the Shape render itself there is not "getter" for them as of now.
I think it would be simpler if you could simply pass attributes when creating the Pager shape.

**Comment by jagbarcelo** [comment]
I tried that in the first place, but since there is no way to add extra tags such as `<span itemprop="name">` I decided to go this way. It seems it's a dead end too. I think that if custom shapes are available, they should provide all the "getters" down the way until the deeper/final tag is reached.
Any workarounds or should I give up completely on my attempt to achieve this?

**Comment by Skrypt** [comment]
Try with {% shape_type Model "Pager_Next" %}

**Comment by Skrypt** [comment]
Pager_Next_Link is not an internal shape. Try with Pager_Link instead.

**Comment by jagbarcelo** [comment]
Now we have this:
![image](https://user-images.githubusercontent.com/6704109/99308994-0f5ebf00-2859-11eb-8e8f-01fc3fdcd062.png)
![image](https://user-images.githubusercontent.com/6704109/99309042-20a7cb80-2859-11eb-88e0-0a5409f209c5.png)
In the `Pager_Link.liquid` file I've inserted a `<pre>` to dump the whole json of the Model, but the output of that piece is just a group of empty braces:
`[[]]`

I've tried with `{{ Model.Pager | json }}`, `{{ Model | json }}` and `{{ Model.Shape | json }}` without any luck either.

Another issue, once this one had been solved (if possible) is how not to use `{{ "Next" | t }}` since this `Pager_Link.liquid` file should work both for the Previous and the Next links.

**Comment by Skrypt** [comment]
Okay I will need to try and debug this.

**Comment by Skrypt** [comment]
Okay this probably currently only works with Pager and not PagerSlim. I'm debugging this right now and it will surely require some more development to make alternate templates work.

**Comment by Skrypt** [comment]
Ok I sorted this out. A Pager_Link output as a TagBuilder not a Shape. This is why you get nothing from your Pager_Link.liquid file. If you want to understand why ; look at ActionLink Shape.

I've fixed the Shape alternates but it would require a refactoring of the ActionLink to return a Shape if we would want to customize them. That's a lot of work for just adding a `<span>`. Can I know why you require this? Is it for SEO?

**Comment by jagbarcelo** [comment]
Yes, this is just SEO. An `itemtype="http://schema.org/SiteNavigationElement"` (see https://schema.org/SiteNavigationElement) can have a chiild `itemprop="url"` (being of type https://schema.org/URL). After checking again these pages for more examples (and others sources) it might be unnecessary to have a third level (which made a third tag needed, thus I picked the `<span>` tag for being dummy/uneffective when rendered into the screen).

So I think you can skip the part when you said that the Pager_Link would need a refactoring in order to change its output into a TagBuilder.

I'll try to apply your changes to my repo and see if I can continue from there. Thanks.

**Comment by Skrypt** [comment]
Remember that in the documentation they say that if you want to have a Shape alternate you must use the PagerId parameter of the Pager or PagerSlim shapes.

**Comment by Skrypt** [comment]
SEO on the Pager remains a task to do. I added some way to make links to be nofollow but there is many ways to achieve proper SEO on those pagers. I keep a note that a SiteNavigationElement could be something we add by default eventually.

**Comment by jagbarcelo** [comment]
It works now. Not having to add a third level (with the `<span>` tag), made it much simpler because we didn't have to create a `Pager_Link.liquid` at all (thus, use the default OC shape). The final result (as a reference for anyone in the future) is this:

**ListPart.liquid**
```
{% if Model.ContentItems.size > 0 %}
  {% assign previousText = "Previous" | t %}
  {% assign previousClass = "previous" %}
  {% assign nextText = "Next" | t %}
  {% assign nextClass = "next" %}
  {% 
     shape_pager Model.Pager 
        previous_text: previousText, next_text: nextText, 
        previous_class: previousClass, next_class: nextClass,
        attributes: "{\"role\": \"navigation\", \"itemscope\": null, \"itemtype\": \"http://schema.org/SiteNavigationElement\"}"
  %}
  <nav>
    {{ Model.Pager | shape_render }}
  <nav>

  [The rest of the code with a {% for item in Model.ContentItems %} comes here]
{% endif %}
```

**Pager_Next.liquid**
```
{% shape_clear_alternates Model %}
{% shape_type Model "Pager_Link" %}
{% shape_add_attributes Model itemprop: "url" %}
{{ Model | shape_render }}
```

**Pager_Previous.liquid**
```
{% shape_clear_alternates Model %}
{% shape_type Model "Pager_Link" %}
{% shape_add_attributes Model itemprop: "url" %}
{{ Model | shape_render }}
```

And that's it.

PS: This simpler scenario even works without your PR applied but feel free to keep on with it if you think it solves more complex cases.

**Comment by Skrypt** [comment]
I'd need to try the exact same thing that you did there. I tried with the Blog List and I was not able to use Pager_Next.liquid at all. I need to check what we do in the List module. Really feels not consistent from one place to an other.

**Comment by jagbarcelo** [comment]
Yes, we did not want different Pagers for each ContentType, so we went directly into creating a global `ListPart.liquid` file, that I we assumed would apply for every 'listable' content type.
