### ISSUE TITLE
Placement issue with validation

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7663]
I have placed fields / parts in different tabs like this.
![image](https://user-images.githubusercontent.com/4681586/99294336-eff07380-2811-11eb-8d03-9121eb711040.png)
![image](https://user-images.githubusercontent.com/4681586/99294373-fbdc3580-2811-11eb-88a1-dcd0a4e38dc5.png)

Some of the fields are marked as required. If I save the form without filling the fields, the placement is broken like this: 
![image](https://user-images.githubusercontent.com/4681586/99294534-2af2a700-2812-11eb-8e4a-5f655eab7024.png)

/cc @deanmarcussen

**Comment by Skrypt** [comment]
Should be easy fix

**Comment by deanmarcussen** [comment]
Should be an easy pr for you then @skrypt ;)

**Comment by Skrypt** [comment]
I'm sure you can fix this faster than me. But looks like when the Validation fails it returns the entire BuildEditor Shape without building the tabs. Maybe it is more complex than I think it is. But normally should be just about moving some code lines around.

**Comment by deanmarcussen** [comment]
> But normally should be just about moving some code lines around.

Bit of cut n paste then 👍
