### ISSUE TITLE
Creating content type from code, Field WithDisplayName is not defined

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#7668]
Creating Content type and parts from the code

```
 _contentDefinitionManager.AlterTypeDefinition("EncriptionKey", type => type
                .DisplayedAs("Encription Key")
                .WithPart("EncriptionKey")
                .Listable()
                .Versionable()
                .Creatable()
                .Securable()
            );
            _contentDefinitionManager.AlterPartDefinition("EncriptionKey", part => part
                .WithField("TockenKey", field => field.OfType("TextField").WithDisplayName("TockenKey").WithDescription("Encription Tocken Key")
                )
                .WithField("TockenPassword", field => field.OfType("TextField").WithDisplayName("TockenPassword").WithDescription("Encription Tocken Password")
                )
            );
```

The conent type created but, instead DispalyName i get "TextField"
As well the  .Listable() .Versionable() .Creatable()  .Securable() not checked

![image](https://user-images.githubusercontent.com/61165619/99392795-f7cd1800-28e4-11eb-9b35-d85ecf117c02.png)

I am creating different content type from different modules,
for test i combine all in one CS file and its created successfully.

**Comment by jtkech** [comment]
Does your module manifest file define a dependency on `OrchardCore.ContentTypes`?

**Comment by vitalybrandes** [comment]
> 
> 
> Does your module manifest file define a dependency on `OrchardCore.ContentTypes`?

Nope,
but this feature enabled in the system by recipe.

**Comment by jtkech** [comment]
> but this feature enabled in the system by recipe.

Yes but maybe not in the right order, a module A having a dependency on a module B ensures e.g. that services registrations of the module B are executed before module A, that handlers / drivers of module B run first, that shape templates of module A have an higher precedence, and so on. And, maybe related to this issue, that migrations of module B run before migrations of module A
