### ISSUE TITLE
CustomUserSettings not accessible in liquid

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7669]
According to the docs, accessing the UserProfile content type with a CustomUserSettings steretotype should be possible by using the following line : `{{ User.Properties.UserProfile.Content.UserProfile.FirstName.Text }}` But this does not work. 

I think the issue is that only the `HttpContext.User` is loaded and not the user entity.

/cc @deanmarcussen

**Comment by deanmarcussen** [comment]
That is quite right and correct @jptissot and the docs are wrong.

It should be
`{{ theUser.Properties.UserProfile.Content.UserProfile.FirstName.Text }}`

where we are assuming `theUser` is part of a user workflow event.

Can you update the docs?

If you want the `FirstName` property in the claims have a look at the `OrchardCore.Demo` project example claims factory.

And write a guide ;)

**Comment by jptissot** [comment]
Thanks for the answer! I will make a liquid filter to load user's properties in liquid pages.

**Comment by deanmarcussen** [comment]
> If you want the FirstName property in the claims have a look at the OrchardCore.Demo project example claims factory.

Claims! don't load it from the db. inject it into the claims

**Comment by deanmarcussen** [comment]
@MichaelPetrinolis reaching out for some advice.

We have a new feature for creating custom user properties from content types, but no way to map them to a user claim without implementing a custom claims factory, i.e. as per `DemoUserClaimsPrincipalFactory`.

I know you wrote a script option for the external login providers, to assist with claims etc.

What do you think about a hook in the `DefaultUserClaimsPrincipalFactory` and custom script to map claims to profile properties?

@jptissot has volunteered to write it :) if it's a good idea

**Comment by jptissot** [comment]
Let's start a separate issue(s) for the Claims mapping. For now, I added a user_properties filter that exposes the User.Properties dictionary in liquid

**Comment by jptissot** [comment]
Closed by #7570
