### ISSUE TITLE
Permissons changes after recent update

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7686]
I recently updated an OC site form RC2 to close to the current dev release. After the update a content manager with the role of "editor" emailed me to say they can only see 4 of the 25 pages in the system.

I am wondering if there have been some permission changes that did not have a proper migrations execution... looks like might be related to this permission "List content item(s) owned by all users "

Can anyone shed any light?

**Comment by deanmarcussen** [comment]
Permission changes, i.e. the default stereotypes applied to roles, only get applied when the module is activated.

So new permissions,  applied to a `GetDefaultStereotypes`, do not get applied to old sites.

None of the changes we've done recently to permissions were applied via a migration, so yes that explains the issue.

See the `RoleUpdater : IFeatureEventHandler` to understand.

We might want to think about going back and adding migrations for the new stereotypes.

**Comment by scleaver** [comment]
It was an easy fix - Just tick `Allow` for the role on `List content item(s) owned by all users` of the `OrchardCore.Contents Feature`. I might keep this open as it probably should be addressed for all those migrating from release candidate 2.

**Comment by Skrypt** [comment]
Yes, we added this permission because it totally makes sense to restrict users to only see their own content. They probably can see now the other content items, but that doesn't mean they will be able to edit them unless they have the permission now.
