### ISSUE TITLE
Issue using AAD for authentication and Orchard for authorization

### ISSUE THREAD

**Issue by juchom** [OrchardCMS/OrchardCore#7687]
Hello,

I followed this documentation [Use Azure AD as an external identity provider](https://docs.orchardcore.net/en/dev/docs/guides/azuread-integration/)

My user can login and are created with the script in the doc:

```js
switch (context.loginProvider) {
    case "AzureAD":
        context.externalClaims.forEach(claim => {
            if (claim.type === "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn") {
                context.userName = claim.value;
            }
        });
        if (!context.userName){
            context.userName = "azad" + Date.now().toString();
        }
    break;
    default:
        log("Warning", "Provider {loginProvider} was not handled", context.loginProvider);
    break;
}
```

Now, if I try to add some Roles to my user I have the error below, because the user doesn't have an email.

![image](https://user-images.githubusercontent.com/17902415/99639738-4515ca80-2a48-11eb-93dd-cbedefecfcfc.png)

Is there a way to solve this issue ?

Thanks

**Comment by jptissot** [comment]
You need to expose the Email claim in your Azure AD app integration. That way, the email is automatically populated.

**Comment by juchom** [comment]
The problem is not with the email, it populates well the Username with the script just above.

The probem is that the script only populate the username and not the email.

And in order to be able to assign roles to my user the email address is a required field.

I'm not sure, if this is a bug of the Users module because email field is optional in case of external provider or an error in the documentation and the script should populate the email field also.

**Comment by jptissot** [comment]
Make sure you have checked these settings in the User Registration Settings page. This will map the email properly.
![image](https://user-images.githubusercontent.com/4681586/99690223-e7887a80-2a55-11eb-8b08-7ed9085326f1.png)

**Comment by juchom** [comment]
The script only map the mail address to this UserName field ->  context.userName = claim.value;

Not to the email field

**Comment by jptissot** [comment]
The "Do not ask email address" checkbox is what I am referring to.

**Comment by MichaelPetrinolis** [comment]
> The problem is not with the email, it populates well the Username with the script just above.

The script is for setting the username. Use the log() function in the script and check if a claim for email is retrieved. the upn stands for User Principal Name and not the email. It might be a bug that introduced later. The "Do not ask email address" does not ask user for the email if there is an email claim, otherwise it should not create the user, as the email field is mandatory.

**Comment by juchom** [comment]
Thanks for your replies, but I have no issue creating the user, everything is set correctly:

![image](https://user-images.githubusercontent.com/17902415/99788145-f9831f80-2b20-11eb-9cf3-de17e783fa5f.png)

My problem is I can't modify Roles on a User because the email field is mandatory.

If I understand the script, it creates a user with a userName coming from the UPN claim (which is an email address in case of Azure AD) at line 5.

This script doesn't set the email address on the context object.

My problem is, we can create a user without an email address, but I can't modify the roles because a user address is required.

I'm not sure if the problem is:

- It is allowed to create a user without an email with a script, then the email field should not be required on the Edit User screen
- It is required to have an email for all users, then the script in the doc should not work because we are able to create a user without an email.

**Comment by MichaelPetrinolis** [comment]
> If I understand the script, it creates a user with a userName coming from the UPN claim (which is an email address in case of Azure AD) at line 5.
It is an email address, but it is not the email claim, that's what @jptissot said and that's why I asked you to dump the received claims. 
Ensure the list of claims you receive from AzureAD contains the email claim.

check
https://openid.net/specs/openid-connect-basic-1_0-28.html for email Standard Claim
https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/19526191-openid-connect-id-token-is-missing-email-claim for an issue regarding AzureAD and email

**Comment by juchom** [comment]
Sorry I didn't get it, so here are the claims I'm receiving:

```
aio
http://schemas.microsoft.com/claims/authnmethodsreferences
http://schemas.microsoft.com/claims/authnmethodsreferences
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
name
http://schemas.microsoft.com/identity/claims/objectidentifier
rh
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
http://schemas.microsoft.com/identity/claims/tenantid
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
uti
```

You are correct, I'm not receiving the email claim. First problem is here.

> The "Do not ask email address" does not ask user for the email if there is an email claim, otherwise it should not create the user, as the email field is mandatory.

Second problem, Orchard did not ask me any email and have created the user.

**Comment by MichaelPetrinolis** [comment]
> Second problem, Orchard did not ask me any email and have created the user.

And this is an issue, it should not create the user.

**Comment by juchom** [comment]
For the first problem I can confirm the issue on the doc, it is missing the step to add the optional email claim when creating the AD App.

When the app is adding the email claim, the user is well created, both fields are populated and I can manage the roles from Orchard.

Since there is two issue, do you want to split this issue and create a second one for the second problem?

**Comment by MichaelPetrinolis** [comment]
yes please. You can also make a PR for the docs on how you solved the first issue.

**Comment by mraparty** [comment]
@juchom
 I have set the AAD in OrchardCoreCMS  as per docs recommended steps Used this link https://docs.orchardcore.net/en/dev/docs/guides/azuread-integration/ , but I'm facing issue when I signed in with my credentials that gives error stating "You do not have access to this resource" . I have also created myself as user with Admin role too. Please suggest whether I'm missing any connection in setting up AAD. Thanks in Advance.
