### ISSUE TITLE
Database connection strings should be not be displayed in the admin

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7691]
When a connection string is defined in an environment variable, the value is displayed in the Tenants creation page. 

```
$env:OrchardCore__ConnectionString="server=localhost;uid=root;database=db;password=my-secret-pw;"
$env:OrchardCore__DatabaseProvider="MySql"
```
![image](https://user-images.githubusercontent.com/4681586/99706688-70f57800-2a69-11eb-8091-fa32ca570bbc.png)

Connection strings should not be displayed if coming from an environment variable.

**Comment by hishamco** [comment]
I think there's an eye icon if I remembered to hide the connection string value

**Comment by Skrypt** [comment]
Yeah but you should not see it at all

**Comment by hishamco** [comment]
Ya but you could toggle it

**Comment by jptissot** [comment]
No they should not appear. It's a security issue

**Comment by hishamco** [comment]
But this may lead to a typo which will break the installation, unless we did a quick connection test to ensure that the connection will break the installation process

**Comment by Skrypt** [comment]
Testing connectionStrings, I think, is a different topic.

**Comment by hishamco** [comment]
So if I made a mistake accidently while I'm writing the connection string the installation will be broken, can you tell me know how we can resolve this issue while the connection is hidden?!!

**Comment by Skrypt** [comment]
If you explicitly added the connectionstring to the appsetting.json file then I assume that you know what you are doing. The idea is that if someone adds a connectionstring there, that's because he doesn't want it to be configurable per tenant.

**Comment by jptissot** [comment]
> Does it not already throw an exception when someone enters a bad connectionstring in that text field?

Yes, but the exception is usually the "invalid serial for shell" generic message.

**Comment by Skrypt** [comment]
Ok, we should then do a connection test step and throw if it fails before anything.

**Comment by jptissot** [comment]
> Ok, we should then do a connection test step and throw if it fails before anything.

Ok, let's do another issue
