### ISSUE TITLE
Container in storage is not showing the uploaded media

### ISSUE THREAD

**Issue by webmedia1012** [OrchardCMS/OrchardCore#7694]
Just a question as to why the container on my storage Azure is not automatically uploading the image from /media/, I've setup the azure CDN enabled on cms admin, and made the json settings based on what's on the documentation. I placed the appsettings.json under the app_data/sites/default folder is this the correct location to place those settings? ie..

```
"OrchardCore": {
    "OrchardCore_Media_Azure": {
      // Set to your Azure Storage account connection string.
      "ConnectionString": "DefaultEndpointsProtocol=https;AccountName=storagename;AccountKey=hashedkey;EndpointSuffix=core.windows.net",
      // Set to the Azure Blob container name. A container name must be a valid DNS name and conform to Azure container naming rules eg. lowercase only.
      "ContainerName": "cms",
      // Optionally, set to a path to store media in a subdirectory inside your container.
      "BasePath": "/",
      "CreateContainer": true
    }
```

Thank you guys as always.

**Comment by Skrypt** [comment]
Technically the App_Data/Site/TenantName/Media folder is now replaced with your Azure Blob Storage. So it's not going to synchronize it even if physically the medias are there. You need to upload these images on the blob storage by yourself.

**Comment by webmedia1012** [comment]
@Skrypt thank you sir, after moving the said config to root directory (where startup.cs) is located, everythiing works, please update documentation to explicitly mention where these settings should be, but looks like I was the only one who didn''t get right the first time lol. 

Thank you and cheers!!

**Comment by jtkech** [comment]
@webmedia1012 

Just for info, in the appsettings under the tenant folder you should not use the `OrchardCore` section nor a child section with the tenant name e.g. `Default`, as it is a tenant specific config file, so here only the `OrchardCore_Media_Azure` section
