### ISSUE TITLE
Orchard is not asking for an email when the email claim is not available

### ISSUE THREAD

**Issue by juchom** [OrchardCMS/OrchardCore#7697]
When you use an external provider and configure registration to no ask email address, Orchard is not asking for an email and it create a user without email.

With this configuration

![image](https://user-images.githubusercontent.com/17902415/99820904-aa091780-2b51-11eb-829b-e3b227336ed5.png)

It creates a user like this

![image](https://user-images.githubusercontent.com/17902415/99821119-e89ed200-2b51-11eb-82e7-759800a52091.png)

**Comment by deanmarcussen** [comment]
@MichaelPetrinolis worth noting here, that the default `UserValidator` in `Identity` doesn't validate the email address, as part of `Create` etc al, unless the `Identity` option `RequireUniqueEmail` is on.

Not sure where the regression is here, but for infos I am hoping to replace the default validator here https://github.com/OrchardCMS/OrchardCore/pull/7645 forcing the requirement for an email address, and other uniqueness
