### ISSUE TITLE
Use nameof in Permission names when possible

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7698]
As @kevinchalet did in the OpenId permissions.

Sometimes, the name is not exactly the same than the permission itself. 
Ex: `Permission ManageMedia = new Permission("ManageMediaContent")`
https://github.com/OrchardCMS/OrchardCore/blob/b1c7d032f349809e6ae3eb6d60194860f5c680f3/src/OrchardCore.Modules/OrchardCore.Media/Permissions.cs#L10

**Comment by sebastienros** [comment]
I like the strings, since they are stored in the db, and any code change would then break the apps, even if it compiles.
