### ISSUE TITLE
OpenID Connect Module needs a mechanism to save new permissions through a recipe. 

### ISSUE THREAD

**Issue by OrchardSkills** [OrchardCMS/OrchardCore#7699]
New OpenID Connect update has breaking changes.

In the OpenID Connect Module the app details and server settings must be saved manually. It will then add the new permissions. There needs to be a way to add these new settings through the recipe. Documentation is also need to explain these new permissions.

<img width="947" alt="OpenIDConnect-UnauthorizedClient" src="https://user-images.githubusercontent.com/59172485/99826851-2251e780-2b16-11eb-9ae2-61947285da53.png">

Manual Work Around
<img width="1003" alt="OpenIDConnect-Server" src="https://user-images.githubusercontent.com/59172485/99828557-53cbb280-2b18-11eb-92e3-15f3a13c71f1.png">
Press Button "Update the server settings and reload the tenant"

<img width="885" alt="OpenIDConnect-Application" src="https://user-images.githubusercontent.com/59172485/99828748-968d8a80-2b18-11eb-949c-ee3869916a6b.png">
Press "Save" Button

<img width="886" alt="OpenIDConnect-Token" src="https://user-images.githubusercontent.com/59172485/99828824-b02ed200-2b18-11eb-9af3-11896f27cb34.png">
How do you set Authorization server tenant through a recipe?

<img width="947" alt="OpenIDConnect-Authorization" src="https://user-images.githubusercontent.com/59172485/99828934-da808f80-2b18-11eb-9afe-7857d3bb2f70.png">

appsettings.json
{
  "Orchard": {
    "ServerUrl": "https://localhost:44300"
  },
  "oidc": {
    "Authority": "https://localhost:44300",
    "ClientId": "code_flow_client_id",
    "UsePkce": true,
    "DefaultScopes": [
      "api"
    ],
    "MetadataAddress": "https://localhost:44300//.well-known/openid-configuration",
    "RedirectUri": "https://localhost:44358/authentication/login-callback",
    "PostLogoutRedirectUri": "https://localhost:44358/authentication/logout-callback",
    "ResponseType": "code"
  }
}

Are "openid" and "profile" scopes implied even though they are not specified?

OpenID Connect recipe settings

     {
      "name": "OpenIdServerSettings",
      "TestingModeEnabled": false,
      "AccessTokenFormat": "JsonWebToken",
      "Authority": "https://localhost:44300",
      "EnableTokenEndpoint": true,
      "EnableAuthorizationEndpoint": true,
      "EnableLogoutEndpoint": true,
      "EnableUserInfoEndpoint": true,
      "AllowPasswordFlow": true,
      "AllowClientCredentialsFlow": true,
      "AllowAuthorizationCodeFlow": true,
      "AllowRefreshTokenFlow": true,
      "AllowImplicitFlow": false,
      "AllowLogoutEndpoint": true,
      "AuthorizationEndpointPath": "https://localhost:44300/connect/authorize",
      "LogoutEndpointPath": "https://localhost:44300/connect/logout",
      "TokenEndpointPath": "https://localhost:44300/connect/token",
      "UserinfoEndpointPath": "https://localhost:44300/connect/userinfo"
    },
    {
      "DisplayName": "Authorization Code Flow",
      "name": "OpenIdApplication",
      "ClientId": "code_flow_client_id",
      "RedirectUris": "https://localhost:44358/authentication/login-callback",
      "PostLogoutRedirectUris": "https://localhost:44358/authentication/logout-callback",
      "AllowAuthorizationCodeFlow": true,
      "AllowLogoutEndpoint": true,
      "Type": "public"
    },
    {
      "name": "OpenIdScope",
      "Description": "A scope to provide api for remote clients",
      "DisplayName": "api Scope",
      "ScopeName": "api",
      "Resources": "my_recipient"
    },
    {
      "name": "OpenIdValidationSettings",
      "Audience": "my_recipient",
      "Authority": "https://localhost:44300"
    }

**Comment by kevinchalet** [comment]
Permissions are automatically inferred from the enabled flows and there's no plan to make that more configurable in OrchardCore, where such granularity is not needed.

Updates of OpenID recipes will be added as part of https://github.com/OrchardCMS/OrchardCore/pull/7646.
