### ISSUE TITLE
Icon Picker Styling Issue for Admin Menu Items

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#7700]
If I create a new website from scratch using the Blog Theme and edit the custom Blog Admin Menu item to change its icon, the icons are all black squares.

![icon-picker-issue](https://user-images.githubusercontent.com/96801/99825468-128dcf80-2b25-11eb-982c-88d146d4d228.png)

One can easily fix this by modifying the [admin-menu-icon-picker.css](https://github.com/OrchardCMS/OrchardCore/blob/b1c7d032f349809e6ae3eb6d60194860f5c680f3/src/OrchardCore.Modules/OrchardCore.AdminMenu/wwwroot/Styles/admin-menu-icon-picker.css#L324) file in OrchardCore.AdminMenu by commenting or removing the following CSS.

`#iconPickerModal .iconpicker-items .iconpicker-item {
    background-color: #212529; }`

It looks like the style was added as part of #7407 so I'm unsure if it serves a purpose for which I am unaware.

**Comment by agriffard** [comment]
This is an optical illusion: Blinking dots at each intersection.

**Comment by jtkech** [comment]
@agriffard 

i didn't see it immediately, but blinking dots at each intersection is amazing ;)
