### ISSUE TITLE
Recipes need to account for AdminUrlPrefix when creating Admin Menus

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#7702]
The blog theme recipe creates a few admin menu links that don't work if the settings have specified a custom AdminUrlPrefix. This is because "Admin" is hardcoded in the URL. Here is a snippet from the [blog link](https://github.com/OrchardCMS/OrchardCore/blob/df011d387465e352ff86a2da79c678648fb9c766/src/OrchardCore.Themes/TheBlogTheme/Recipes/blog.recipe.json#L1314).

`"LinkUrl": "[js: 'Admin/Contents/ContentItems/' +  variables('blogContentItemId') + '/Display']",`

It's not a huge deal to change this in the backend for one instance, but if I specify a custom admin prefix for all tenants at the root settings, all admin menu links created by recipes in all tenants will fail.

If recipes don't have access to the admin prefix, I believe they need it. And, if they do have access to the admin prefix, it needs to be accounted for in the recipes bundled with OC.

**Comment by Skrypt** [comment]
This would require that we be able to evaluate current effective appsettings on a tenant returned by the JavaScriptEngine (Jint).

**Comment by davidhayden** [comment]
I don't think we need to go as far as exposing appsettings.

We could just provide AdminUrlPrefix or AdminOptions like we do for modules that need to have access to the admin prefix.

**Comment by Skrypt** [comment]
That could work.

**Comment by jtkech** [comment]
@Skrypt @davidhayden 

We already have a `ConfigurationMethodProvider` so as i remember maybe we can already use

    "[js:configuration('OrchardCore_Admin').AdminUrlPrefix]"

**Comment by Skrypt** [comment]
We could if the setting was always there. The idea is the the AdminOptions defaults to the `/admin` path.

**Comment by jtkech** [comment]
Oops okay

Hmm, maybe we could change the `ConfigurationMethodProvider` to do a bind on an object instance, so that, if there is no config, we get the default value that is `Admin`. But not sure we can do that here as we would need a typed object
