### ISSUE TITLE
Do we want important features dependent on shortcodes feature?

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#7715]
I decided to disable the shortcodes feature on a client website because I wanted to see if it was responsible for mangling sample code in a knowledge base that included brackets ("[" and "]"), only to realize that disabling shortcodes meant I had to disable the Content Fields and HTML features that have a dependency on it.

Is there a reason we have a hard dependency on the nice-to-have shortcodes feature in other key CMS features? Can't we instead enable features in those modules when and if the shortcodes feature is enabled? Either way, I don't believe I have an option to opt-out like I do with the HTML sanitizer. 

![shortcodes-dependency](https://user-images.githubusercontent.com/96801/99916968-778b2600-2cdb-11eb-87f7-c2d553bd0aa1.png)

**Comment by Skrypt** [comment]
I think the best approach to this would be to add something like a `<code>[ something ]</code>`  that would escape the shortcodes to try to render.

**Comment by davidhayden** [comment]
If it ignored `code` blocks that would certainly help.

I think the problem is bigger though.

I should be able to disable the shortcodes feature without disabling all my CMS editors. If I disable shortcodes, I disable all Content Fields, HtmlBodyPart, MarkdownPart, and possibly other important features.

I should be able to opt-out of shortcode processing in a field, like HTML Sanitizing. This is how I fixed it for my client really quickly, but I think this is just a bandaid for the bigger problem above.

![shortcode-settings](https://user-images.githubusercontent.com/96801/99984606-46fac900-2d7b-11eb-9886-2463dc07661e.png)

**Comment by deanmarcussen** [comment]
For infos @davidhayden 

The reason we (I) integrated shortcodes, as a non optional feature, was primarily because they provide a default behaviour to include media files into content.

i.e. without them you cannot use media from the media library inside any html content blocks.

To be fair, when we first implemented all we had was the `[image]` tag, which wouldn't mangle other `[` ...

**Comment by davidhayden** [comment]
Maybe something changed or I'm experiencing something strange @deanmarcussen , because attributes in all sample code are completely swallowed up by the shortcode processor. If I have an attribute in sample code in an HTML Field, like `[HttpGet]`, the shortcode processor removes it completely from the code. In order to display it, I have to escape it as `[[HttpGet]]`, which I shouldn't have to do.

It gets trickier when you have something like `[Route("api\[controller]")]`, because this cannot be fixed as `[[Route("api\[[controller]]")]]`. It requires a different combination of brackets.

I temporarily added a setting, but it would be nice to have the shortcodes feature play nicely with code samples and other uses of brackets that are not shortcodes.

**Comment by deanmarcussen** [comment]
I don't think anything has changed @davidhayden - was just explaining why it is not an optional feature.

But what might be a nice feature for @sebastienros shortcodes processor, is to return the value, if there is no shortcode registered against that name - not sure of the practicalities of that within the parser (particularly with the nested examples above)

**Comment by sebastienros** [comment]
I am thinking that we could configure the parser to ignore some sections, ideally configurable, like by stating that ` or ``` blocks should not be parsed. Same with using `<pre></pre>` or `<code></code>` but that could be hard to manage.

Another option would be to use a shortcode to use raw content, like `[raw]...[/raw]`. (preferred option)
Final option would be to render the unknown ones as is, but that's also dangerous since it could display arguments.

**Comment by sebastienros** [comment]
I assume the default behavior could also return the original text if no shortcode matches ...
I am also looking at how wordpress is handling this

**Comment by sebastienros** [comment]
Wordpress seems to ignore shortcodes that are unknown or don't have the correct arguments.
Right now our behavior is the strip the shortcode. Should it be an option on the library?

**Comment by davidhayden** [comment]
I think so. I thought it would be the default functionality and was surprised when it stripped the text.

**Comment by davidhayden** [comment]
Awesome work @sebastienros and thank you 👍 

I did some quick testing in an HTMLBodyPart to verify the change is **not** stripping unknown shortcodes, executing known shortcodes, and still escaping tags. This solves my concerns, and the issue can be closed from my perspective.

**Comment by Skrypt** [comment]
Did we document the final solution?

**Comment by hishamco** [comment]
I upgrade Shortcodes to 1.0.0 in #7988 which allow to skip unknown shortcodes

**Comment by Skrypt** [comment]
So the solution is to use any unknown shortcode like :   

```html
<code>[undefined] Html.Raw escaped text [known_shortcode][known_shortcode] [undefined]</code>
```

Please fix my example if I'm wrong and add it to the documentation.

**Comment by sebastienros** [comment]
> which allow to skip unknown shortcodes
=> which skips unknown shortcodes

The solution is to not do anything in OC, the library has a different behavior that fixes this issue

**Comment by sebastienros** [comment]
But we might still need to add a custom shortcode to escape everything on purpose, with `[raw][/raw]`. This can't be done with a custom shortcode since the inner text would be parsed first. It has to be done in the shortcodes library. I couldn't find how Wordpress is handling this though.

**Comment by Skrypt** [comment]
[[shortcode_here]TEXT HERE.[/shortcode_here]]

But I think this already works? I leave you guys at it. I just want to have this documented 😉

**Comment by sebastienros** [comment]
Yes that worked, and it still works, but when you write a blog post and you need to add some c# code with attributes, you don't want to have to do it on every attruibute. Then you have arrays, ... 

What should be documented? How to escape shortcodes?

**Comment by Skrypt** [comment]
I think escaping shortcodes is already documented. I meant documenting how to achieve what @davidhayden wanted to achieve. Maybe I need to read more about the issue and I'm lost but I feel like either the issue remains or that there is some examples that could be show in the documentation.
