### ISSUE TITLE
Duplicate event handler

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#7718]
https://github.com/OrchardCMS/OrchardCore/blob/4ff39ce3b0d818c3bd441797b3fd4a5b90eb2e54/src/OrchardCore.Modules/OrchardCore.Users/Startup.cs#L185 same as line 201

**Comment by jtkech** [comment]
@EternityTeam

Good catch! Do you want to provide a PR to fix it?
