### ISSUE TITLE
Jquery CDN load failed

### ISSUE THREAD

**Issue by JohnnyZhang0628** [OrchardCMS/OrchardCore#7721]
I 'm  .net developer from china. Due to network , CDN scripts can't load success.Please  add a picker in SetUpPage.Thanks

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/7707

**Comment by Skrypt** [comment]
See
https://github.com/OrchardCMS/OrchardCore/pull/7599
https://github.com/OrchardCMS/OrchardCore/pull/7707

**Comment by JohnnyZhang0628** [comment]
@Skrypt Thanks reply. Besides using `hishamco/use-cdn` branch ,are there other ways?The `dev` branch will consider to add the function?

**Comment by Skrypt** [comment]
We will discuss about it this week with @sebastienros 
I will try to take some time tomorrow to test the PR and see if everything could work with it.
Yes, it will eventually be merged in the dev branch.
The issue we have with a CDN setting on the setup is that now we need to define if it should be enabled or not by default. Also, it feels like this option should be configurable from the appsettings.json file.
Also, enabling the CDN doesn't garantee that the CDN will work so we should do some DNS tests first before enabling it. Else it makes the admin UI totally unusable. So there is more work than what it seems to be.

**Comment by JohnnyZhang0628** [comment]
@Skrypt Thanks Reply.I looking foward to next version  ASAP.

**Comment by deanmarcussen** [comment]
Reopening this as for all the complaints about it, we have no issue tracking it.

workarounds

add this to your startup project.
```
using Microsoft.Extensions.Options;
using OrchardCore.ResourceManagement;

namespace OrchardCore.Cms.Web
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms()
                .ConfigureServices(tenantServices => {
                    tenantServices.PostConfigure<ResourceManagementOptions>(o => o.UseCdn = false);
                });
        }
```

or after setup, navigate to 
`https://localhost:5001/Admin/Settings/general` and disable the 'Use Framework CDN'`

**Comment by JohnnyZhang0628** [comment]
@deanmarcussen Thanks.The problem has solved :smiley:.
![image](https://user-images.githubusercontent.com/28375774/99945231-382e0980-2daf-11eb-8339-9bac2677786e.png)

**Comment by agriffard** [comment]
Can this be closed: It seems it has been solved.

**Comment by sebastienros** [comment]
Needs documentation

**Comment by Skrypt** [comment]
This issue should be taken care in first priority for 1.0
@hishamco is working on a PR https://github.com/OrchardCMS/OrchardCore/pull/7599
But there is also documentation to write about the possible workarounds.

**Comment by agriffard** [comment]
The Resource settings are in the second tab in General and if jQuery is not loaded, you cannot switch to change the CDN options.

**Comment by agriffard** [comment]
See also #8154

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/8324
