### ISSUE TITLE
Shell Settings and Tenants

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7727]
Can we clarify why the tenant informations are stored/accessed with a Class called `ShellSettings`?

Does anything prevent us from naming them `TenantSettings`? Same for all other `Shell...` classes.

That would be clearer for everyone trying to understand how Tenants work.

https://docs.orchardcore.net/en/dev/docs/glossary/#tenant

**Comment by agriffard** [comment]
I didn't find any issue raising the question and people are sometimes asking it in the chat.

I was looking at https://www.finbuckle.com/MultiTenant/Docs and their concepts/presentation might be interesting to explore.

**Comment by Skrypt** [comment]
This is a discussion I had a while ago with @jtkech and it is named ShellSettings because it comes from 01.
Renaming it might take some time.

**Comment by HengzheLi** [comment]
A similar issue about the difference between Shell and Tenant. https://github.com/OrchardCMS/OrchardCore/issues/3969. However it didn't explain every detail, but it still can be a short reference for some one who have a query for Tenant and Shell.

**Comment by agriffard** [comment]
@jtkech I f I wanted to create a PR with these changes (renaming ShellSettings into Tenant), would you have some directions to give?

**Comment by jtkech** [comment]
@agriffard 

I've no closed opinion because I already suggested it => `TenantHost`, `TenantContext`, `TenantScope`, `TenantOptions`, `TenantSettings`, `TenantConfiguration` ... I also suggested to not use the term `Modular` => `ITenantEvents`, `TenantContainerMiddleware`, `TenantRouterMiddleware` ...

But see #5961
