### ISSUE TITLE
Error on setup: InvalidOperationException: Invalid serial number for shell descriptor

### ISSUE THREAD

**Issue by cerveser** [OrchardCMS/OrchardCore#7737]
Hi all,
I followed the instructions on: https://docs.orchardcore.net/en/dev/docs/getting-started/ 
On Visual Studio 2019 using the nuget package: OrchardCore.Application.Cms.Targets 1.0.0-rc2-13450
The database used was MySQL.
I get the error: "InvalidOperationException: Invalid serial number for shell descriptor" after filling in the setup page.

I only managed to fix this by copy pasting the "DataProtection-Keys" folder from a previous setup. After that it worked.
I also made sure the tables in the schema where empty from previous attempts.

More details about the error:

    OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(int priorSerialNumber, IEnumerable<ShellFeature> enabledFeatures, IEnumerable<ShellParameter> parameters) in ShellDescriptorManager.cs
    OrchardCore.Setup.Services.SetupService+<>c__DisplayClass11_1+<<SetupInternalAsync>b__1>d.MoveNext() in SetupService.cs
    OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
    OrchardCore.Setup.Services.SetupService.SetupInternalAsync(SetupContext context) in SetupService.cs
    OrchardCore.Setup.Services.SetupService.SetupAsync(SetupContext context) in SetupService.cs
    OrchardCore.Setup.Controllers.SetupController.IndexPOST(SetupViewModel model) in SetupController.cs
    lambda_method(Closure , object )
    Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult()
    Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
    System.Threading.Tasks.ValueTask<TResult>.get_Result()
    System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in ModularTenantRouterMiddleware.cs
    OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
    OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by jptissot** [comment]
This usually occurs when something goes wrong during setup. Is there more information in the `App_Data/logs` folder?

**Comment by cerveser** [comment]
No that folder doesn't exist. The site works only because I've added the map: DataProtection-Keys from another version to App_Data\Sites\Default

**Comment by jptissot** [comment]
You might want to use the latest dev feed to see if the issue is resolved.

**Comment by cerveser** [comment]
ok it works when I use 1.0.0-rc2-15525
