### ISSUE TITLE
Dealing with Blocked Third Party Cookies

### ISSUE THREAD

**Issue by f1software** [OrchardCMS/OrchardCore#7759]
How would you build an Orchard Core App that must run in an iframe on another domain and requires authentication and must work with third party cookies blocked? 

We've considered adding another path segment to the url to hold the session Id but this means we have to modify every url in all the admin pages. Is there an easy way to do this in Orchard Core?

**Comment by sebastienros** [comment]
I don't think there is anything specific to Orchard Core in your question. It looks like a general ASP.NET core one. Have you tried on the aspnet core repository?
