### ISSUE TITLE
Background task re-entrance

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#776]
Working on background tasks, i could see this comment.

> DoWork is not re-entrant as Timer will not call the callback until the previous callback has returned ...

Maybe i misunderstood this comment, but, using a delay higher than the timer period, i could see that the callback is re-called even if the previous call was not ended.

So, maybe we have to check e.g if a given task / group is not already running ...

**Comment by sfmskywalker** [comment]
Could it be the case that the callback was from another timer?

**Comment by jtkech** [comment]
I don't think so because, as i remember, there is only one timer for a given group in a given tenant.

**Comment by sfmskywalker** [comment]
You're right, and it's re-entrant because of this:

![image](https://user-images.githubusercontent.com/938393/35196544-c4f29baa-fed3-11e7-8bb7-94a35b3f5b59.png)

Instead, no period should be passed in. The callback should simply start the timer again once it's done executing.

**Comment by jtkech** [comment]
Yes, you're right but i thought to preserve the period accuracy and to not have a sliding effect.

So, in #1372 i opted to just return if any task of the group is not idle (awaiting for a next execution), assuming it is to handle special cases because a group period should be enough.

**Comment by PinpointTownes** [comment]
:+1: for making tasks non-re-entrant (it's something that wouldn't be appropriate for our new OpenID task as it may result in multiple concurrent DB calls being made at the same time: https://github.com/OrchardCMS/OrchardCore/pull/1400)

**Comment by sebastienros** [comment]
Don't change too much things, I have some notes somewhere with ideas for refactoring this module. If you want to fix the reentrancy though please do, that shouldn't be hard.

**Comment by jtkech** [comment]
Okay cool, if you said it to me, see my last comment in #1372
