### ISSUE TITLE
Media Library allows Directory Traversal for azure blob

### ISSUE THREAD

**Issue by SteeveDumais** [OrchardCMS/OrchardCore#7768]
Create a new media folder at the root folder?  Call it "..\notGoingToShowUp",  Save the folder.  The folder will get created but will never be visible

**Comment by Skrypt** [comment]
Please update to latest dev I'm pretty sure this was fixed.

**Comment by Skrypt** [comment]
![Peek 25-11-2020 14-48](https://user-images.githubusercontent.com/3228637/100275534-11e2a800-2f2e-11eb-8f2e-3ac1c9da26e4.png)

**Comment by SteeveDumais** [comment]
You are creating media.  When you press the add folder button then the
folder name should be "..\something".  Also your media should be azure

**Comment by Skrypt** [comment]
Ok so what you are suggesting here is that we can create folders outside of the /media container path?

**Comment by Skrypt** [comment]
Ok I confirm that I can repro. We should not be able to create folders by using a path.

**Comment by SteeveDumais** [comment]
There is code when using the file store (not azure) that looks to make sure
that the path is under the root.  There is no such thing currently for the
sure blob implementation

**Comment by deanmarcussen** [comment]
This sounded interesting, but I can't repro

- The recent changes from @netwavebe https://github.com/OrchardCMS/OrchardCore/pull/7662 prevent those characters
- I removed that change, they don't act as a traversal, allowing you to get out of the blob's root container, as blob doesn't support tree walking, in that way i.e. ../
- So the only strangeness I could repro was that a folder could be created called `..`. With a subfolder of `something`

But like I said I had to revert this pr https://github.com/OrchardCMS/OrchardCore/pull/7662 to get that 

What am I missing @SteeveDumais ?

**Comment by SteeveDumais** [comment]
It looks like #7662  is only for moveMedia

You need to be using azure blobs
Click the add folder button 
enter ../folder name
This will save a folder outside your default
Also try the escape character equivalent of / such as 

Encoding and double encoding:

%2e%2e%2f represents ../ %2e%2e/ represents ../ ..%2f represents ../  %2e%2e%5c represents ..\ %2e%2e\ represents ..\  ..%5c represents ..\  %252e%252e%255c represents ..\  ..%255c represents ..\  and so on.

**Comment by netwavebe** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/7662 affects creating folders. See the file changes. It also effects both file system and Azure.

**Comment by deanmarcussen** [comment]
@SteeveDumais it´s not possible to traverse up with blob storage using any syntax. ever. 

you could have traverse down. but @netwavebe has fixed that.

Please try with the latest dev, and report back.
