### ISSUE TITLE
Content list, need Edit permissions?

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#7779]
![image](https://user-images.githubusercontent.com/16968103/100417251-6ff0c600-30bb-11eb-8292-e089ec0c7e10.png)
@Skrypt

**Comment by Skrypt** [comment]
Yes, this means that the user should have either "Edit Content for others" or "Edit own content" permission which is what this list is for.

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/100418726-39687a80-30be-11eb-9017-2003e3399751.png)
![image](https://user-images.githubusercontent.com/16968103/100418802-543aef00-30be-11eb-8eb7-60adb40de6ee.png)
Do you understand?

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/100419015-a1b75c00-30be-11eb-836c-0d96f0adf090.png)

**Comment by Skrypt** [comment]
Not sure I understand. I can see that these are "project" content items. You added an admin menu that list those "Projects". 

Then on the second screenshot you display a project. Not sure either, we don't have this in OC.

On the third screenshot you show the content item list which only allows to view the content item.
I want you to check if your current user has the proper permissions on the content items that have only a "View" button.

**Comment by Skrypt** [comment]
You will need to add some explanation to me. I will use Google translate. Just write it in mandarin or chinese I don't make the difference yet 😄

**Comment by chinasqzl** [comment]
点击项目，跳转到了DetailAdmin,而不是Edit页。所以不需要有Edit权限。

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/100421254-fbba2080-30c2-11eb-9ac3-7cc0e2dfe3be.png)

**Comment by chinasqzl** [comment]
![Uploading image.png…]()

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/100422081-91a27b00-30c4-11eb-9a72-9cdc297516d1.png)

**Comment by Skrypt** [comment]
The "Content Items" menu item displays now as soon as you have at least one content type that has the Edit permission.
This is why I added the permission on the List action too. So that it be consistent. Now, if we remove this permission on the Action, we need to think about using a new permission maybe instead of the EditContent one. I will think about it.

**Comment by chinasqzl** [comment]
Thank you.

**Comment by Skrypt** [comment]
Or remove it. Actually maybe that would be the only solution for your use case.

**Comment by chinasqzl** [comment]
#7289

**Comment by Skrypt** [comment]
Yeah more like a Global permission on the "List" action. Something not related with EditContent.
Something that says : Can view the "Content Items" list ... ViewContentList

**Comment by Skrypt** [comment]
I'll take a look tomorrow. I'm out for tonight.

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/100424013-f14e5580-30c7-11eb-8634-e8229313082d.png)
这里也要调整，没有编辑权限该怎么跳转。

**Comment by Skrypt** [comment]
I think this one is fine? Now, if you are using this url to display your AdminDetails view instead of the actual content item editor page, we need to think about something else. Or maybe, I'm missing something. It's late, I'll think about it tomorrow 😉

**Comment by chinasqzl** [comment]
在仓库管理中，进出库完成，不可更改、修改、删除。为此，我改动如下：
1.完成的库存移动内容，所有人不可操作
![image](https://user-images.githubusercontent.com/16968103/100430384-af2a1180-30d1-11eb-8436-d227120d488b.png)
2.完成的库存移动内容，AdminRouteValues -> DetailAdmin Page
![image](https://user-images.githubusercontent.com/16968103/100430666-0cbe5e00-30d2-11eb-9a14-cc0ba981a2cd.png)
3.保存，跳转到AdminRouteValues
![image](https://user-images.githubusercontent.com/16968103/100430981-7e96a780-30d2-11eb-8259-bac0980b3b13.png)

**Comment by chinasqzl** [comment]
内容保存后，满足条件（比如发布），所有人，包括管理员，不可修改，删除。

**Comment by Skrypt** [comment]
Ok, this is a nice trick to make content items readonly. We should maybe have some generic way to do this. Going to sleep on it 😉

**Comment by sebastienros** [comment]
It's a custom feature, with a custom permission, and a custom permission handler that will check if the content has been published. Could also be a custom Part with a field to "lock" a content item, and then check a specific permission.

**Comment by Piedone** [comment]
It seems to me that the original question was answered, as well as follow-up ones. If there's a concrete feature request here in the end, then please open one and elaborate.
