### ISSUE TITLE
GraphQL complexity settings

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#7785]
Hi, 
I have troubles with graphql complexity settings.. Just wondering if we could create setting to disable complexity check? 
I think that inserting null here https://github.com/carlwoodhouse/OrchardCore/blob/ec51978bdce77796af090ecd464c69d38faf1cf7/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs#L169

would solve the problem (skip complexity check).

UC:
Given:
* Content Item with flow and 20 different widgets

When:
* We want to pull all widgets

Then: 
* GraphQL ends on error (complexity can be changed, but sooner or later, we will hit the limit anyway)

Solutions:
* disable graphql complexity check
* retrieve widgets in separate requests, but there are some problems with sorting etc.

If you would agree to add settings to disable complexity check, I can do PR.

**Comment by sebastienros** [comment]
Looks like you can already configure it and there is some documentation about it: https://docs.orchardcore.net/en/dev/docs/reference/modules/Apis.GraphQL/#configuration

**Comment by MikeKry** [comment]
@sebastienros 

I know about this settings, but my point was that it is not possible to disable complexity check completely and when you pass any not null object as ComplexityConfiguration  then graphql performs complexity check and that is a problem for nested queries.

In practice it means that you can not use more than approx. 10 widgets in one request (by design of flow, it has three levels to retrieve anything and this is really increasing complexity). 

We have solved it for our case in different way = currently we are fetching each widget in separate requet, but it is a bit complicated approach.
