### ISSUE TITLE
Admin menu is throwing exception when adding "Content Menu Item"

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#7786]
I created a site using SaaS recipe. Then I enabled the Menu and AdminMenu modules.

Under Content >> Menu. I added a new menu. Then "Edited" the menu to add menu items. I clicked on "Add Menu Item" then clicked on "Add" button under the "Content Menu Item" section on the right. Then I get this error

```
An unhandled exception occurred while processing the request.

RuntimeBinderException: Cannot perform runtime binding on a null reference
```

**Comment by Skrypt** [comment]
Can't repro

**Comment by sebastienros** [comment]
Please add some repro steps
