### ISSUE TITLE
Content items - Actions error

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#7794]
Bulk actions on content item list do not work, falls on concurrency exception, or just do nothing when you try to publish/unpublish/delete item. (using MSSQL)

![image](https://user-images.githubusercontent.com/52829889/100523674-7a41bb80-31b2-11eb-90c8-ae48957b87d4.png)

**Comment by jptissot** [comment]
Which version are you running ?

**Comment by MikeKry** [comment]
@jptissot 

just updated to version with new yessql, works fine, sorry.. 

Closing
