### ISSUE TITLE
Imagesharp.web > rxy querystring param has no effect.

### ISSUE THREAD

**Issue by TimF5** [OrchardCMS/OrchardCore#7797]
Hi,

I'm using OrchardCore as a headless CMS with multiple tenants. In a tenant, when i view an image from _Content > Media Library_ (i.e. https://{mysite}/media/{folder}/xxx.jpg) that works fine. 

When i crop the image using one of the SupportedSizes (i.e. https://{mysite}/media/{folder}/xxx.jpg?width=50&height=100&rmode=crop) that works fine too. 

However, when i add rxy as param to the querystring to set the anchor point for cropping (i.e. https://{mysite}/media/{folder}/xxx.jpg?width=50&height=100&rmode=crop&**rxy=0.5,0.5**) that doesn't seem to have any effect. I always get the same result as https://{mysite}/media/{folder}/xxx.jpg?width=50&height=100&rmode=crop (without the anchor point).

Has anyone encountered this? Could it be a bug?

Thx for helping out.

**Comment by deanmarcussen** [comment]
Yes that won't work.

rxy requires a tokenized query string see https://docs.orchardcore.net/en/dev/docs/reference/modules/Media/#query-string-tokens

From your other issue you are using graphql, so I will close this one and comment there about what we may need
