### ISSUE TITLE
Codemirror: too much space between two lines

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7799]
![image](https://user-images.githubusercontent.com/703248/100526528-ef6cbb00-31c9-11eb-8eea-90692aecd035.png)

**Comment by hishamco** [comment]
I will try to have a look ...

**Comment by Skrypt** [comment]
These styles comes from _codemirror.scss file which are applied globally. If it's not getting applied that's because there is something overriding these styles.

**Comment by Skrypt** [comment]
Can't repro. The spaces are fine. There is a natural margin-bottom on `<p></p>` html paragraphs. If you want to have a "newline" you type `shift + enter` instead of `enter`.

**Comment by agriffard** [comment]
You are showing me screenshots with trumbowyg, not with codemirror.

You can repro with a Standard Editor on Html Field or HtmlBodyPart.
