### ISSUE TITLE
Admin Title

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7806]
The title of the site, in the upper left of the admin, is not styled like previously.

Before:
![image](https://user-images.githubusercontent.com/703248/100540958-07cbec80-3241-11eb-8138-e24d9b5f0b7e.png)
Now:
![image](https://user-images.githubusercontent.com/703248/100540989-38138b00-3241-11eb-8be2-9d65fef80549.png)

Could it be possible to find also a way to add a link to /admin? 
By clicking the logo for example?

**Comment by agriffard** [comment]
I guess this is to handle the changes for the Dark mode but it woud be better to have another font (at least a bit bolder) and color on light mode to easily understand it is a link.

**Comment by agriffard** [comment]
Tooltips added:

![media](https://user-images.githubusercontent.com/703248/101267367-1726ca80-3758-11eb-808d-55246464cf72.gif)

**Comment by hishamco** [comment]
I like the tooltip on filter textbox because it's more useful, but I still don't like the link to the site and tooltips for both logo and title, probably adding a new link to the right with title "Live Site" make sense

**Comment by agriffard** [comment]
> I like the tooltip on filter textbox because it's more useful, but I still don't like the link to the site and tooltips for both logo and title, probably adding a new link to the right with title "Live Site" make sense

![image](https://user-images.githubusercontent.com/703248/101281507-8c81b200-37cf-11eb-9304-f47c3acef897.png)

**Comment by agriffard** [comment]
![media](https://user-images.githubusercontent.com/703248/101281515-a1f6dc00-37cf-11eb-97b5-94663f652c05.gif)

**Comment by hishamco** [comment]
Nice!!
