### ISSUE TITLE
Workflows: Dark mode

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7807]
Worflows connections are not correctly display on Dark mode:

![image](https://user-images.githubusercontent.com/703248/100543497-ce9b7880-3250-11eb-8bc3-fdecaa489463.png)

Light mode:

![image](https://user-images.githubusercontent.com/703248/100543469-b592c780-3250-11eb-950d-11d4ecf2828c.png)

**Comment by hishamco** [comment]
@Skrypt could please fix this or I will do it if you are busy with other PRs
