### ISSUE TITLE
Codemirror double scrollbar issue

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7816]
![image](https://user-images.githubusercontent.com/4681586/100614166-b4f74100-32e3-11eb-84b3-fda472426b54.png)
/cc @Skrypt

**Comment by Skrypt** [comment]
I can't repro.
Here are some tests I made :  

![screencapture-localhost-5001-Admin-Contents-ContentTypes-LiquidPage-Create-2020-12-01-13_22_23](https://user-images.githubusercontent.com/3228637/100780901-52cc3800-33d8-11eb-9f22-825be10d7f0b.png)
![screencapture-localhost-5001-Admin-Templates-Create-2020-12-01-13_22_47](https://user-images.githubusercontent.com/3228637/100780911-53fd6500-33d8-11eb-88d3-61475ee67ec4.png)

**Comment by agriffard** [comment]
PLease try with a large text line that goes after the width of th screen.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/100782468-798b6e00-33da-11eb-8407-1cc136d062ab.png)

**Comment by jptissot** [comment]
Try it inside a widget, then inside a tab. This is where I get the issue.

**Comment by Skrypt** [comment]
Okay! Fixed in #7813
