### ISSUE TITLE
AdminUI issues with bootstrap-select

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#7817]
![20201130225246](https://user-images.githubusercontent.com/14150259/100624903-e7924f80-335e-11eb-99be-65c8f2448bdc.png)

The new TheAdmin.css cause this issue .
ver: 1.0.0-rc2-15539

**Comment by hishamco** [comment]
Is this happing with the dev branch, there are many styles improvement done after RC2

**Comment by EternityTeam** [comment]
yes,I used 1.0.0-rc2-15510 before I update to 1.0.0-rc2-15539.
There is no such issue in 1.0.0-rc2-15510 .

**Comment by hishamco** [comment]
Is this happing with the dev branch, there are many styles improvement done after RC2

**Comment by hishamco** [comment]
@Skrypt is this a regression of the latest changes you made?

**Comment by Skrypt** [comment]
I can't repro. This is probably related to a custom admin theme.

![image](https://user-images.githubusercontent.com/3228637/100780006-3380db00-33d7-11eb-9ac9-cfd92adcfc94.png)

![image](https://user-images.githubusercontent.com/3228637/100780063-45fb1480-33d7-11eb-8044-accbbd347baf.png)


Here is a repro I made and I don't get the same results.

**Comment by EternityTeam** [comment]
@Skrypt thx for reply!

I guess you're missing the following code, so using class selectpicker has no effect.

`<script asp-name="bootstrap-select" at="Foot"></script>
<style asp-name="bootstrap-select"></style>`

![Snipaste_2020-12-02_02-59-35](https://user-images.githubusercontent.com/14150259/100785069-1980e000-344b-11eb-9b15-978a65c49099.png)
![Snipaste_2020-12-02_03-01-56](https://user-images.githubusercontent.com/14150259/100785120-30bfcd80-344b-11eb-8774-1b3ae48e0320.png)

**Comment by Skrypt** [comment]
<style asp-name="bootstrap-select" depends-on="admin"></style>

**Comment by EternityTeam** [comment]
Should not be the reason, even if depens-on is missing, the script is still loaded in the correct order.The loading sequence is shown in the picture above.

![Snipaste_2020-12-02_03-28-00](https://user-images.githubusercontent.com/14150259/100787330-70d47f80-344e-11eb-91e9-8e5e3c0a7ad5.png)

**Comment by EternityTeam** [comment]
I made a demo to reproduce it
[AdminUI.zip](https://github.com/OrchardCMS/OrchardCore/files/5625047/AdminUI.zip)

**Comment by Skrypt** [comment]
Yeah, I'm looking at it and it seems you are right. I'm trying to figure out why the styles are not applied correctly now.
