### ISSUE TITLE
[CI] Add schedule run for manual tests

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7835]
Run the `Functional Tests - all Databases` and the `Frontend Assets build validation` periodically (weekly ?)
Automatically create an issue if the `Functional Tests - all Databases` fails
Automatically create a PR when the `Frontend Assets build validation` if there are any changes.

**Comment by Piedone** [comment]
Both of these now run for PRs and `main` too, see https://github.com/OrchardCMS/OrchardCore/pull/15951 and https://github.com/OrchardCMS/OrchardCore/pull/15735.
