### ISSUE TITLE
PublishLater causes repeated errors in log

### ISSUE THREAD

**Issue by fzadrazil** [OrchardCMS/OrchardCore#7842]
When using PostgreSQL data storage, PublishLater module repeatedly logs error:

`2020-12-03 13:48:32.4132|Default|0HM4NH599E44F||OrchardCore.Modules.ModularBackgroundService|ERROR|Error while processing background task 'OrchardCore.PublishLater.Services.ScheduledPublishingBackgroundTask' on tenant 'Default'. Npgsql.PostgresException (0x80004005): 42883: operator does not exist: character varying < timestamp without time zone`

**Comment by Skrypt** [comment]
Your timezone must be set to null or something like that in your tenant settings.

**Comment by fzadrazil** [comment]
Nope, timezone is set to GMT+01 in /Admin/Settings/general. We have the same settings, same installation process of OrchardCore, on SQL Server instance and no errors in log.

**Comment by Skrypt** [comment]
Ok I think I might know what's happening. I had issues with the publish later module concerning timezones too. It's maybe not even related with PostgreSQL.

**Comment by fzadrazil** [comment]
Any idea what is causing this issue then? I will be glad for any advice.
