### ISSUE TITLE
OpenId

### ISSUE THREAD

**Issue by maksudcs** [OrchardCMS/OrchardCore#7843]
Hey,

I am a dot net developer and thinking to build a blog using OrchardCore. Finally, started the development, but getting a few exceptions with the first build. Stated one exception among others.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0738	'OpenIdApplicationManager<TApplication>' does not implement interface member 'IOpenIddictApplicationManager.CreateAsync(OpenIddictApplicationDescriptor, CancellationToken)'. 'OpenIddictApplicationManager<TApplication>.CreateAsync(OpenIddictApplicationDescriptor, CancellationToken)' cannot implement 'IOpenIddictApplicationManager.CreateAsync(OpenIddictApplicationDescriptor, CancellationToken)' because it does not have the matching return type of 'ValueTask<object>'.	OrchardCore.OpenId.Core	C:\Users\maksudur.rahman\Downloads\OrchardCore-dev\OrchardCore-dev\src\OrchardCore\OrchardCore.OpenId.Core\Services\Managers\OpenIdApplicationManager.cs	21	Active

**Comment by deanmarcussen** [comment]
You will need to update to the dotnet 5 SDK, and latest version of Visual Studio 2019 if you are using it

**Comment by maksudcs** [comment]
Thanks, @deanmarcussen , it's working 👍
