### ISSUE TITLE
InvalidOperationException: Cannot resolve scoped service 'System.Collections.Generic.IEnumerable`1[YesSql.Indexes.IIndexProvider]' from root provider.

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#7847]
I created the following model

    public class Location : ContentItem
    {
        public string Name { get; set; }
    }

Then created the following index and index-provider

    public class LocationIndex : MapIndex
    {
        public string ContentItemId { get; set; }

        public string Name { get; set; }
    }

    public class LocationIndexProvider : IndexProvider<Location>
    {
        public override void Describe(DescribeContext<Location> context) =>
            context.For<LocationIndex>()
                .Map(location =>
            new LocationIndex
            {
                Name = location.Name,
                ContentItemId = location.ContentItemId
            });
    }

I registered the IndexProvider by adding this to the `ConfigureService()` method

    services.AddScoped<IIndexProvider, LocationIndexProvider>();

But when I run the app I get the following error for some reason

> **An unhandled exception occurred while processing the request.**
> InvalidOperationException: Cannot resolve scoped service 'System.Collections.Generic.IEnumerable`1[YesSql.Indexes.IIndexProvider]' from root provider.
> 

Here is my migration in case this is needed

public class LocationMigrations : DataMigration
    {
        IContentDefinitionManager _contentDefinitionManager;

        public LocationMigrations(IContentDefinitionManager contentDefinitionManager)
        {
            _contentDefinitionManager = contentDefinitionManager;
        }

        public int Create()
        {
            _contentDefinitionManager.AlterPartDefinition("USAddressPart", part =>
               part.Attachable()
                   .Reusable()
                   .WithDisplayName("US Address Part")
                   .WithDescription("Provides you a way to capture US address")
                   .WithField("AddressLine1", field => field.OfType(nameof(TextField)).WithDisplayName("Address Line 1"))
                   .WithField("AddressLine2", field => field.OfType(nameof(TextField)).WithDisplayName("Address Line 2"))
                   .WithField("AddressCity", field => field.OfType(nameof(TextField)).WithDisplayName("City"))
                   .WithField("AddressState", field => field.OfType(nameof(ContentPickerField)).WithDisplayName("State"))
                   .WithField("AddressZipCode", field => field.OfType(nameof(TextField))).WithDisplayName("Zip Code"));

           _contentDefinitionManager.AlterPartDefinition("LocationPart", part => part
                    .WithField("Name", field => field.OfType(nameof(TextField))
                                                     .WithDisplayName("Name")
                                                     .WithSettings(new TextFieldSettings()
                                                     {
                                                         Required = true,
                                                     })
                    ).WithField("Phone1", field => field.OfType(nameof(TextField)).WithDisplayName("Phone 1"))
                    .WithField("Phone2", field => field.OfType(nameof(TextField)).WithDisplayName("Phone 2"))
                    .WithField("Fax1", field => field.OfType(nameof(TextField)).WithDisplayName("Fax 1"))
                    .WithField("Fax2", field => field.OfType(nameof(TextField)).WithDisplayName("Fax 2"))
                    .WithField("Website", field => field.OfType(nameof(LinkField)).WithDisplayName("Website"))
                );

            _contentDefinitionManager.AlterTypeDefinition("Location", type => type

                .WithPart("LocationPart")
                .WithPart("USAddressPart")
                // content items of this type can have drafts
                .Draftable()

                // content items versions of this type have saved
                .Versionable()
                // this content type appears in the New menu section
                .Creatable()

                // show the list of locations
                .Listable()

                // permissions can be applied specifically to instances of this type
                .Securable()

            );

            // Create the search index
            SchemaBuilder.CreateMapIndexTable(typeof(LocationIndex), table =>
             {
                 table.Column<string>(nameof(LocationIndex.Name))
                      .Column<string>(nameof(LocationIndex.ContentItemId), column => column.WithLength(26));
             }, string.Empty);

            return 1;
        }
    }

Am I missing something here or is this a bug?

**Comment by jtkech** [comment]
You need to register it as a singleton, otherwise it would need to be an `IScopeIndexProvider`, but you don't need it here as it is used e.g. when it needs to inject scoped services

**Comment by CrestApps** [comment]
@jtkech That did work! Thank you. But now the index table is not populating when a new content item is added. Any reason why it is not updating?

**Comment by CrestApps** [comment]
@jtkech That did work! Thank you. But now the index table is not populating when a new content item is added. Any reason why it is not updating?

**Comment by jtkech** [comment]
To do that, you need to implement an `IndexProvider<ContentItem>`

**Comment by CrestApps** [comment]
@jtkech that is what I am doing above. The Location model inherents from ContentItem the my LocationIndexProvider implements IndexProvider<Location> but the index is empty event after I added née content item from the UI.

**Comment by jtkech** [comment]
@CrestApps 

Try to use the `Contentitem` base class, and then in your mapping check if it is a `Location`

**Comment by deanmarcussen** [comment]
@CrestApps you can't use inheritance this way on a content item. They're based on composition not inheritance.
Correct usage would be

```
public class LocationIndexProvider : IndexProvider<ContentItem>
{
    public override void Describe(DescribeContext<ContentItem> context) =>
        context.For<LocationIndex>()
            .Map(contentItem => 
       {
          var locationPart = contentItem.As<LocationPart>();
          if (locationPart == null)
          {
             return null;
         }

          return new LocationIndex
          {
              Name = location.Name,
              ContentItemId = location.ContentItemId
          });
    }
}
