### ISSUE TITLE
Icon picker does not work in dark mode

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#7860]
Can not see icons in dark-mode, please see the image below

![2020-12-04-icon-picker](https://user-images.githubusercontent.com/13991195/101225338-06862f80-3646-11eb-8430-f84139b0c4cf.png)

**Comment by Skrypt** [comment]
How did you add the Icon Picker to the Link Menu Item?

**Comment by rserj** [comment]
I added "Text Field" to "Link Menu Item" type in Content Definition

![image](https://user-images.githubusercontent.com/13991195/101225770-2c600400-3647-11eb-875d-e371dd000eb0.png)

**Comment by rserj** [comment]
>This bug has been fixed recently. First thing would be to try latest bits and report if the issues remains.

Ohh ok I'll try to check out the last version, thank you

**Comment by Skrypt** [comment]
Actually I'm trying it right now and it's broken in latest version. I'm surprised, maybe it's using a different component than the Boostrap-select one.

**Comment by Skrypt** [comment]
Yeah it is using https://github.com/itsjavi/fontawesome-iconpicker

**Comment by rserj** [comment]
@Skrypt thanks for the fix!
