### ISSUE TITLE
Admin Users

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7868]
Add filters in admin users page like:
- Only enabled.
- Only not email confirmed.

**Comment by hishamco** [comment]
Filter by: 

- Activity (Enable, Disable, All)
 
- Email Confirmation (Confirmed, Not Confirmed, All)

- Role

I can work on this if you are not started yet

**Comment by agriffard** [comment]
@hishamco Do you still want to work on this feature?

**Comment by hishamco** [comment]
Sure if no one pick it up ;)
