### ISSUE TITLE
Hint with dashes

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7869]
Check css for the separator added with @scleaver changes on divs with `hint dashed`.

It needs some space between the dash and the previous word:
![image](https://user-images.githubusercontent.com/703248/101259907-3871c180-372c-11eb-9415-03364a5af2df.png)

**Comment by scleaver** [comment]
@agriffard - Where is this example? I have checked lots of the instances and can't find where it occurs.

**Comment by Skrypt** [comment]
It's the User module Razor templates and it's caused because it needs a refresh on the HTML composition.
