### ISSUE TITLE
Create a Liquid object that returns content items by alias

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#787]
Something like `Alias.MainMenu`

**Comment by agriffard** [comment]
Do you mean?:
- Have a content type with an AliasPart.
- In a Liquid part or in a template, be able to use a Filter?

What would be a good name for the filter and which liquid syntax would be appropriate? 
Ex: `| includecontent:"alias"`

**Comment by sebastienros** [comment]
Implemented here: https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Contents/README/#loading-from-an-alias
