### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by DiomedesDominguez** [OrchardCMS/OrchardCore#7879]
In the latest docker image I got this error message:
```c-sharp
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

![image](https://user-images.githubusercontent.com/4379316/101299739-988a6580-3809-11eb-92cc-b90f7ecd759f.png)

**Comment by deanmarcussen** [comment]
I am guessing this maybe related to a recent YesSql change / then reversion https://github.com/sebastienros/yessql/pull/306

@sebastienros can you merge it to master?

**Comment by DiomedesDominguez** [comment]
I notice in that the dockerfile use the .NET SDK 5 but the runtime is 3.1, can be this the issue?

**Comment by Skrypt** [comment]
Yes this is because you need to have both .NET 3.1 and 5.0 installed.

**Comment by DiomedesDominguez** [comment]
> Yes this is because you need to have both .NET 3.1 and 5.0 installed.

Yes, but the docker image is using only one.

**Comment by Skrypt** [comment]
The Docker images are built by the CI

https://github.com/OrchardCMS/OrchardCore/blob/f53933f678fea62af1e220f171163226e706588b/.github/workflows/release_ci.yml#L26-L30

And you can see that we install both framework there.
And if you build an image by yourself :  https://github.com/OrchardCMS/OrchardCore/blob/dev/Dockerfile
The Dockerfile uses .NET SDK 5.0 for building OC and 3.1 runtime for running the website which is appropriate.

**Comment by DiomedesDominguez** [comment]
The problem persists in the latest docker image

![image](https://user-images.githubusercontent.com/4379316/101526579-30e82d80-3963-11eb-810c-c9b86885c0bd.png)

**Comment by deanmarcussen** [comment]
I'm going to merge a pr that may be (and also may not be) related to this issue.

Note: I couldn't repro myself.

Can you try in half an hour after the latest image has been pushed @DiomedesDominguez

**Comment by DiomedesDominguez** [comment]
> I'm going to merge a pr that may be (and also may not be) related to this issue.
> 
> Note: I couldn't repro myself.
> 
> Can you try in half an hour after the latest image has been pushed @DiomedesDominguez

No problem, I can wait. 

As you can see I'm just pulling the docker image from the docker hub.

**Comment by DiomedesDominguez** [comment]
Now is running!

**Comment by deanmarcussen** [comment]
@sebastienros it was yessql!
