### ISSUE TITLE
Pass in arbitrary data to setup context

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#7882]
When setting up a tenant or site sometimes you need to pass in some custom data  and use it in your setup recipes.

Example : 
1. When a user registers on my site he submits a form with firstname, lastname  etc.  I then call a workflow  that creates the tenant and executes a setup recipe. In this setup recipe I create a landing page and i want  to assign the fisrtname , lastname  to be set as the displaytext of the landing page content item. 
2. Another use case would be to populate the custom  user profile settings during setup.

This is currently not possible.

submitting a pr that adds to  OrchardCore.Setup.Services.SetupContext an additional bag property : 

```
    /// <summary>
        /// Gets and additional key/value info.
        /// </summary>
        public IDictionary<string, string> Properties { get; } = new Dictionary<string, string>();
```
that can be consumed by recipes using the syntax : 

```
 "Text": "[js: parameters('Properties.FirstName')]"
```
that was  aplied by pr #7824

It is up to developer to populate the properties bag from his workflow task or a custom setup screen.

@deanmarcussen

**Comment by hishamco** [comment]
I think we have similar discussion in another PR where we want to set the CDN support from within setup using recieps
