### ISSUE TITLE
call GraphQL API return 400 bad request when anonymous

### ISSUE THREAD

**Issue by IsQiao** [OrchardCMS/OrchardCore#7889]
expect: 401 Unauthorized

**Comment by Piedone** [comment]
This isn't the case anymore. E.g. running `https://localhost:44300/api/graphql?query=query%20MyQuery%20{%20article%20{%20displayText%20}%20}` on a site set up with the Blog recipe, you get back:

```json
{
  "data": {
    "article": [
      {
        "displayText": "About"
      }
    ]
  }
}
```
