### ISSUE TITLE
Why is Email settings listed under Security?

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#7896]
Seems to me it's a Configuration Setting, not a Security Setting

<img width="362" alt="Screenshot 2020-12-08 at 09 28 06" src="https://user-images.githubusercontent.com/13782679/101465415-d2598a00-3937-11eb-9615-a75988ad48b9.png">

/cc @agriffard

**Comment by agriffard** [comment]
It is the 'Change email' settings.
I will rename it.
