### ISSUE TITLE
Icon Picker doesn't work since 15533

### ISSUE THREAD

**Issue by sliu001** [OrchardCMS/OrchardCore#7911]
Icon Picker hasn't been working **since 1.0.0-rc2-15533**. The dropdown area with search textbox and all the icons is not available. I've tried the latest version which is 1.0.0-rc2-15588. The **last working version is 1.0.0-rc2-15532**. Thanks.

**Issue:**
![IconPickerIssue](https://user-images.githubusercontent.com/7218894/101547364-1f5d5080-3978-11eb-8df2-98d79ac3949d.PNG)

**My setup:**
![IconPickerSetup](https://user-images.githubusercontent.com/7218894/101547373-21271400-3978-11eb-8b03-6dadd0c8670f.PNG)

**Comment by Skrypt** [comment]
duplicate and fixed in https://github.com/OrchardCMS/OrchardCore/pull/7862

**Comment by sliu001** [comment]
Just tried version 1.0.0-rc2-15603, it works! Thank you.
