### ISSUE TITLE
Does Admin panel only can be accessed using HTTPS?

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#7916]
My app is exposed to be accessed via http. But when I login to the admin panel like http://localhost:5000/admin, it redirect me to the login page again http://localhost:5000/Login?ReturnUrl=%2Fadmin.

I can confirm that my username and password are correct. Because it works correctly when I use HTTPS.

**Comment by deanmarcussen** [comment]
Generally this is due to chromes same site cookie changes that occurred earlier in the year.

It is resolved on the preview feed https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/

Please upgrade to the preview feed and reopen if the issue still occurs

**Comment by HengzheLi** [comment]
May I know the PR that fixes this issue?

**Comment by HengzheLi** [comment]
I download the latest dev branch code and try again. The issue still exists.

**Comment by jtkech** [comment]
Just tried on my side, it works

As i remember, as soon you logged in with https, then you can't with http

You need to clear the cookies of your browser and / or close all insatnces of you browser

And / or try with another browser ;)

**Comment by HengzheLi** [comment]
OK. Tried again. It works. 

I think I might in this case before

> as soon you logged in with https, then you can't with http
