### ISSUE TITLE
Fields display

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7920]
The idea is to use the display name everywhere in fields display and to provide some default positions for each kind of field, except for the Html and Markdown.

Sorry, I pushed the changes to dev (Forgot to make a branch): https://github.com/OrchardCMS/OrchardCore/commit/4044d7d38f825179b94a6929f1bad0efdd8b55e6

**Comment by agriffard** [comment]
Without the DisplayNames:

![image](https://user-images.githubusercontent.com/703248/101646087-5f373d00-3a37-11eb-828c-88c5cb574272.png)


Now:

![image](https://user-images.githubusercontent.com/703248/101645960-3f077e00-3a37-11eb-9e9c-b51be457870f.png)

**Comment by agriffard** [comment]
Colon (`:`) removed because in RTL, they wouldn't be on the right.

@hishamco Should we generate the separators (`,`) depending on LTR/RTL? 
LTR:  if != .Last()
RTL:  if != .First()

**Comment by hishamco** [comment]
I don't think there is an issue with the separator, almost the issue happen in RTL languages whenever ends with special charcter, example:

هشام:

it should be

:هشام

**Comment by deanmarcussen** [comment]
@agriffard this significantly changes the default templates, by applying bootstrap classes everywhere.

It means someone has to theme / rewrite every one of these templates to get rid of the column layout and display that it imposes.

Can you revert and propose as a pr please?

**Comment by agriffard** [comment]
Reverted

**Comment by agriffard** [comment]
> @agriffard this significantly changes the default templates, by applying bootstrap classes everywhere.

We should find a way to have field / label classes generated in bootstrap-oc.css, inheriting from `form-group` and `col`.

**Comment by deanmarcussen** [comment]
Thank you.

What problem are you trying to solve here?

**Comment by agriffard** [comment]
> What problem are you trying to solve here?

- Be consistent in the use of label with DisplayName in all fields.
- Order the positions of fields in a default way (I'd love to have a drag and drop for the display, like the editors).
- Obtain by default the kind of UI I showed when I use a Bootstrap theme.

Should I add alternates in TheTheme?
