### ISSUE TITLE
AdminUrlPrefix wrong config

### ISSUE THREAD

**Issue by DiomedesDominguez** [OrchardCMS/OrchardCore#7924]
In some links in the admin panel aren't working as expecting: 

For example, I set mine to be "olimpo" but some menu links still point to "admin" instead:

![image](https://user-images.githubusercontent.com/4379316/101677674-40cf4280-3a33-11eb-98ce-ee8bce1715fc.png)

After think about it, I will create a PR at EOD.

**Comment by hishamco** [comment]
Feel free to submit a PR if there's an issue with the `AdminUrlPrefix`

**Comment by DiomedesDominguez** [comment]
> Feel free to submit a PR if there's an issue with the `AdminUrlPrefix`

Thanks, but I'm still a noob in OrchardCore. I found that the problem is in the blogrecipe.json that has _Admin_ in the LinkUrl parameter. I couldn't recognize a variable to use as _AdminUrlPrefix_  in none of the other recipes.

![image](https://user-images.githubusercontent.com/4379316/101684856-6c572a80-3a3d-11eb-9f17-8e3c83057792.png)

**Comment by hishamco** [comment]
I will have a look
