### ISSUE TITLE
beta could be 1.0 actually

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#793]
As we have implemented the module bundle, pack, openid, web api , our first release can focus on webapi.
only  consider the "thin" stuff which api just need. maybe restructure?
then for cms, we can extend it.
how do you guys think of that?

**Comment by agriffard** [comment]
The version will follow the beta-1 => beta2 => rc versions unti 1.0 as planned in https://github.com/OrchardCMS/OrchardCore/wiki/Roadmap

**Comment by gentledepp** [comment]
if you focus on web api, please thing about using json schema as well as swagger, for easyer api integration.
For swagger: I managed to get a custom route (like you do it in orchard to serve content items for specific urls) along with a swagger document filter (which alters the swagger document to include the api that is dynamically defined by the conten type) up and running within an hour. So I know this is possible, and it would be great. I.e.: auto-generating a specialized web api endpoint along with the json schema (including validation) for a content type.

Also, using json schema opens a whole new world of opportunities.
For example, you could just use this MIT licensed angular 2 library, that  creates beautiful forms based on a json schema! [JSON Forms](http://jsonforms.io/)
