### ISSUE TITLE
Adding ability to update logo and favicon in Admin Portal

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#7937]
I've created a very simple module called "[OrchardCore.CustomStyleSettings](https://github.com/JoshLefebvre/OrchardCore.CustomStyleSettings)" a while back with the goal of allowing my tenants to update their logo and favicon in the portal admin theme (I give tenants limited ability to the admin portal).

After reviewing what is in the OrchardCore.Admin module I am seeing a lot of similarities with my module. Would this be something that the OC team would be interested in merging in ?  Essentially I would be extending the AdminSettings.cs to add two additional fields:
```
        public string SiteLogo { get; set; }
        public string SiteFavicon { get; set; }
```
which would display as two MediaFields to select an image for their company logo, and a favicon.

In TheAdmin portal theme layout header:
```
    @if (@adminSettings.SiteFavicon == null)
    {
        <link type="image/x-icon" rel="shortcut icon" href="~/TheAdmin/favicon.ico" />
    }
    else
    {
        <link type="image/x-icon" rel="shortcut icon" href="@adminSettings.SiteFavicon" />
    }
```
and logo:
```
            @if (@adminSettings.SiteLogo == null)
            {
                <a class="ta-navbar-brand" href="@Url.Content("~/portal")">
                    <span>@Site.SiteName</span>
                </a>
            }
            else
            {
                <a class="navbar-brand insitution-logo" href="@Url.Content("~/portal")">
                    <img src="@adminSettings.SiteLogo" class="navbar-brand-img" alt="...">
                </a>
            }
```

I was also thinking about further extending this to the login layout as well. Here is the implementation for my current module:
https://github.com/JoshLefebvre/OrchardCore.CustomStyleSettings

**Comment by hishamco** [comment]
I think you already can do this from site settings

/cc @agriffard

**Comment by JoshLefebvre** [comment]
It sets the navbar-brand to the Sitename text, but doesn't allow you to set a logo image. I can imagine people would also like to use their own fonts here too for their site/company name

**Comment by Skrypt** [comment]
The common thing to do is to create a new Admin Theme simply here. This way you get to have control over templates and styles. I'm not against the suggestion but is it worth adding a AdminSetting for these UI things. Because there might be others over time too if we start doing this. Just a thought.

**Comment by JoshLefebvre** [comment]
Yea in my case I do not wish to create a new admin theme for each tenant, but rather have my clients reuse the existing admin theme. However, I can see how the list of admin settings will quickly grow if we allow this. 

I will close this task and if anyone does stumble upon this thread feel free to checkout my simple module for extending the existing site settings to upload a logo to a theme: https://github.com/JoshLefebvre/OrchardCore.CustomStyleSettings
