### ISSUE TITLE
Probably race condition in ResorceDefinition class

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#7939]
This happend to me two times but I can't replicate it now. Basically I created new website using TheAgencyTheme and when I tried to access `Content -> Content Items` in Admin page crached with `ArgumentException`. Something like:

`System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds.`

It was in line `180 `of file `ResourceDefinition.cs`

The only resonable explanation for such exception I could think of is race condition in this method:

```
public ResourceDefinition SetDependencies(List<string> dependencies)
        {
            if (Dependencies == null)
            {
                Dependencies = new List<string>(); 
            }

            Dependencies.AddRange(dependencies);    // LINE 180

            return this;
        }
```

There is also similar method above this one.

I was using clean OrchardCore source code with last commit:

```
SHA-1: c34341aae6c7e62e112a02c4b329a68e358919a6

* Admin menu icons (#7906)
```

**Comment by jtkech** [comment]
Related to #7712
