### ISSUE TITLE
Filters: Top border disappear on search

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7960]
When you filter a page (ex: Content types), the first item can disappear so there is no top border anymore:

![media](https://user-images.githubusercontent.com/703248/101994560-7ee29580-3cc3-11eb-96a7-22abe8cd7b86.gif)

**Comment by agriffard** [comment]
Do you also see those strange corners around the search? : 
![image](https://user-images.githubusercontent.com/703248/101994620-10ea9e00-3cc4-11eb-81ad-98494ff3e134.png)

**Comment by hishamco** [comment]
I think this because the filter hide the rows based on thier order, that's why you didn't see the border when you search for a `Page`, could try search for `Button`, I expect it should show up

**Comment by agriffard** [comment]
Here is a proposal: Use `list-item-group` (less borders) and alternating background color on odd lines:

![media](https://user-images.githubusercontent.com/703248/101995196-a8ea8680-3cc8-11eb-9ba1-19d01ae3ccf1.gif)

Filtering can mix the lines colors though.

**Comment by hishamco** [comment]
@agriffard why this is reopened?

**Comment by agriffard** [comment]
I thought it was solved but it is still to be fixed.
