### ISSUE TITLE
Ability to set the theme mode from the user menu

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#7961]
I think it would be nice if we add a menu item called `Appearance` on the user menu, that allow user to set the theme mode:

- Default to the system

- Light

- Dark

something similar to 

![Themes](https://user-images.githubusercontent.com/3237266/101995413-b6107100-3cda-11eb-9a7c-e5a6cfe31850.png)

With that no need to enable the dark mode from the settings, all the modes will be there and the default is set to the system

/cc @agriffard @Skrypt

**Comment by Skrypt** [comment]
Maybe, but the menu would be rendered on frontend so the frontend theme needs to support it.
That's a specific theme setting then, not a global menu setting.

**Comment by hishamco** [comment]
Why we need to render it on frontend?

> so the frontend theme needs to support it

This could be if the front theme supports theming modes

**Comment by Skrypt** [comment]
Well you can render these menus on backend if you want but we have an AdminMenu that is more specialized for admin.
I would opt extending the AdminMenus before using the Menus for the admin side of things.

If the front theme supports theming modes then it's a theme setting which we let people decide of.
Should we add a setting for every potential settings a frontend theme could have in the source code of OC?
The SiteSettings are there for that matter if anyone wants to extend them they can.

**Comment by hishamco** [comment]
Let me check what should I come up with ...

**Comment by hishamco** [comment]
Closed while we implemented the 3 options in a menu
