### ISSUE TITLE
Measure performance

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7972]
We should be able to measure the performance of the system (to check if it improves when we use a new sdk for example).

Ram/Cpu usage.
How many req/s with one instance.
How many tenants are supported.
Does Redis enhance the perfs.

Could we use something like Benchmark.NET for some measurements?

**Comment by agriffard** [comment]
If only we knew someone that works on measuring performance improvements ;-)

/cc @sebastienros

**Comment by agriffard** [comment]
Check: 
- Load tests (Page calls, Response times)
- Improvements with new version of framework.
- YesSQL performance (new version, add index).
- CPU/Ram consumption, depending on number of tenants.

**Comment by Piedone** [comment]
Where was this done @agriffard?
