### ISSUE TITLE
Run Blog Recipe throws Validation Exception

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#7995]
If you tried to run the blog recipe from with the admin site, a `ValidationException` will be thrown, because the alias is already in use

**Comment by deanmarcussen** [comment]
Setup recipes shouldn't be run twice. They're not designed for that, and you will end up with all sorts of duplicated content issues.

It still makes sense to have them as runnable, so that a user can run the blog recipe, and the agency recipe.

**Comment by jtkech** [comment]
Yes, as i remember when i tried it, when running the blog recipe it was the only one issue

So worth to fix it

**Comment by hishamco** [comment]
@deanmarcussen if the intend is not run the same recipe I think it will be better to disable the installed recipe to run to avoid such issue

**Comment by Skrypt** [comment]
If everything was idempotent from recipes there should not be any issue.

**Comment by deanmarcussen** [comment]
The issue becomes that setup recipes create weirdness when run twice.

Because content item ids are generated during the setup run.

So setup recipes are not idempotent.

You end up with multiple widgets in footers, extra blogs.
