### ISSUE TITLE
Setup Incorrect GitHub App information blocks the access of the admin site

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#8001]

**Comment by Piedone** [comment]
I don't really understand what this issue is about. Is this still applicable?

**Comment by hishamco** [comment]
When I saw a notification on my mobile I remember that I post a similar issue, but when I opened the GitHub app I notice it's me ;)

Let me check this tomorrow and close it if it's no longer occurs

The issue basically occurs when you register using GitHub account at that time
