### ISSUE TITLE
Default Media File Store virtual methods

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8005]
Recently I had to override one method on the `DefaultMediaFileStore`, which meant copying the entire code over, instead of inheriting, and tweaking the bit I needed.

Think it makes sense to make the methods virtual, to make changing the behaviour a little easier.

**Comment by hishamco** [comment]
Does make all the methods `virtual` make sense? or there some of them that are really could be overriden
