### ISSUE TITLE
Enhancement: Deleted content items

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8009]
Hello, 

since content items are not really removed from DB when you hit "delete", could we show them in content items list, e.g. with some filter?

**Comment by orchardc** [comment]
Agree. I think OC should proivde a way to remove (physically) content records from the DB.

Looking into tables: there might only be 5 tables which contains content:

    AliasPartIndex
    AutoroutePartIndex
    ContentItemIndex
    Document
    IndexingTask

**Comment by hishamco** [comment]
Related to #8133

**Comment by Piedone** [comment]
This is now possible with Audit Trail.
