### ISSUE TITLE
Discuss refactor calls to JObject.FromObject

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#801]
**Purpose**: 
To set `TypeNameHandling.Auto`, for all calls.

**Reason**:
Allow interface properties in a `Part` to serialize and deserialize properly.
- using YesSql directly support this.
- Simplify some modeling.

**Example**:
LogPart saves events on a page.
- It has a `List<ILogEntry>` field.
- I would like different type of events to have a concrete type, like ReferrerLogEntry, ClickLogEntry, DragLogEntry, DurationLogEntry etc.
- Each entry will have different properties.
- In admin, one could derive a Driver to create different shapes according to each entry type.

**Comment by Piedone** [comment]
We've since then moved to System.Text.Json.
