### ISSUE TITLE
Build warning snupkg

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8011]
warning : Source control information is not available - the generated source link is empty.

Must be related to recent changes. 

/cc @ns8482e

**Comment by jtkech** [comment]
@ns8482e is it related to the discussion we had about using `snupkg` in place of our embedded pdb files that also embed the related source files? And that cloudsmith doesn't support yet `snupkg` ;)

**Comment by Skrypt** [comment]
Yes closing this and renaming title as a reference for search. I believe the issue will get fixed when Cloudsmith supports it.
