### ISSUE TITLE
Admin filters in contents list dont work nicely with placement

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#8020]
When in the admin in the contents list I would like to reposition the admin filters using placement  files : 

So there seems to be the following shapes used in the filters display : 
ContentsAdminList
-ContentsAdminList__Search
-ContentsAdminList__Create
-ContentsAdminList__Summary
-ContentsAdminList__Filters

which give out the following layout : 
 
![image](https://user-images.githubusercontent.com/1516981/102329301-ea14bc00-3f90-11eb-9652-7bea970194b3.png)
 
In the admintheme if i add a placement.json file with following rule :

```
{
  "ContentsAdminList__Search": [
    {
      "place": "-"
    }
  ] 
}
```
Then i get the following output , all the filter shapes have dissapeared

![image](https://user-images.githubusercontent.com/1516981/102328694-124feb00-3f90-11eb-859a-c994e1eb2e0b.png)

Not what i hoped for. Was expecting only the text search element to be hidden.
Is this a bug ?
Ideally i would like to reposition thse filter shapes in a sidebar zone using some placement syntax like this :
```
{
  "ContentsAdminList__Search": [
    {
      "place": "\Sidebar:1"
    }
  ] ,
  "ContentsAdminList__Filters": [
    {
      "place": "\Sidebar:2"
    }
  ]

}

```

@deanmarcussen 

By the way, thanks for this great feature, especially the taxonomies integration is terrific.

**Comment by deanmarcussen** [comment]
@giannik it's going to be the same issue as was fixed here https://github.com/OrchardCMS/OrchardCore/pull/7086

Suggest the shape names would need to be renamed to `ContentsAdminListSearch` to work with placement

**Comment by Skrypt** [comment]
Please take a note that these search forms have small differences for when they use a filter or not.
We are still defining Admin UI elements this is mainly why I did not use a shape for now.
If you want to have a common shape for all lists this might take some params to differenciate some elements.

**Comment by deanmarcussen** [comment]
Different issue @Skrypt this is about the shape names for the extended filters for the CI list - taxonomies / culture etc.

So not the form, just some shapes that make up the elements
