### ISSUE TITLE
Unable to build liquid Form_Wrapper

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#8021]
It seems it's not possible to override `Form_Wrapper` with Liquid.

The default Razor template is :
```razor
...
<form id="@formId" action="@formPart.Action" method="@formPart.Method"  enctype="@encType" class="form-content @formContentTypeClassName">
    @if (formPart.EnableAntiForgeryToken)
    {
        @Html.AntiForgeryToken()
    }

    @await DisplayAsync(Model.Metadata.ChildContent)
</form>
```

So, the Liquid equivalent should be :
```liquid
...
<form action="{{ formPart.Action }}" method="{{ formPart.Method }}" enctype="{{ encType }}" class="form-content {{ formContentTypeClassName }}">
    {% if formPart.EnableAntiForgeryToken %}
        {% antiforgerytoken %}
    {% endif %}

  {{ Model.Metadata.ChildContent | shape_render }}
</form>
```

But `Model.Metadata.ChildContent` doesn't evalutes in Liquid, and it's not `IShape` but `IHtmlContent`.

**Comment by jtkech** [comment]
Can't right now but i will take a look asap

I think the fix should be easy, maybe just also check that it is an `IHtmlContent` in the filter

**Comment by sebastienros** [comment]
Note that `@await DisplayAsync(Model.Metadata.ChildContent)` should actually be `@Model.Metadata.ChildContent`
