### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#8027]
We should find another title for the Login screen than `Use a local account to log in.`

**Comment by agriffard** [comment]
My reason for this change was to not have the typical title from the ASP.NET template.

I don't mind having the name of the site.

Should we remove the name of the site? 
Just keep `Log in` ?

**Comment by hishamco** [comment]
What's the wrong with your previous PR?

**Comment by agriffard** [comment]
People might not want to see the site name in this title.

**Comment by hishamco** [comment]
> People might not want to see the site name in this title.

Strange!! the site name already there in the site theme as well, I don't think this is  BIG issue while we can override the login view

**Comment by deanmarcussen** [comment]
> Strange!! the site name already there in the site theme as well, I don't think this is BIG issue while we can override the login view

The general point being made here is to do less to the templates / design, and allow people to override them, rather than forcing changes on them, particularly at this late stage.

**Comment by hishamco** [comment]
Ok Dean, I can remove the site name from the login view, and leave any customization to the user

**Comment by hishamco** [comment]
PR #8123 is created
