### ISSUE TITLE
MyGet feed

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#803]
`Orchard.ResourceManagement.Abstractions ` and `Orchard.ResourceManagement` have version 2.0.0.  Hope they can be removed, because it is always shown to be the latest version in nuget manager in visual studio. They cannot be automatically update to latest preview, 2.0.0 is always selected.

**Comment by sebastienros** [comment]
Please delete you local cache of nuget packages. We fixed it a while ago.

**Comment by awyl** [comment]
[Orchard.ResourceManagement.Abstractions](https://www.myget.org/feed/orchardcore-preview/package/nuget/Orchard.ResourceManagement.Abstractions)

[Orchard.ResourceManagement](https://www.myget.org/feed/orchardcore-preview/package/nuget/Orchard.ResourceManagement)

The recommended releases are still 2.0.  That's why nuget manager keeps saying there are updates for these two packages, when I already have the latest preview.

**Comment by agriffard** [comment]
The packages have been unlisted.
