### ISSUE TITLE
Admin UI : header buttons

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8034]
Before #7851 :  

![image](https://user-images.githubusercontent.com/3228637/102417505-d8033f80-3fc9-11eb-93fd-c96f8ca6258d.png)

After #7851 : 

![image](https://user-images.githubusercontent.com/3228637/102416872-a342b880-3fc8-11eb-8b0b-4d0269897308.png)

I found out that we are displaying these buttons inside a hamburger menu now.
I'm not a fan of it. They should be displayed all the time.
If we have other menu items then they should be added in the hamburger menu but only if they have a text.
This looks strange needing to open the hamburger menu to toggle the darkmode.

![image](https://user-images.githubusercontent.com/3228637/102417154-26640e80-3fc9-11eb-909f-66f9ce7f7541.png)

/cc @agriffard

**Comment by hishamco** [comment]
Seems the icons are wiered in the humberger menu, could we use text instead

**Comment by Skrypt** [comment]
No it needs to be removed from that hamburger menu. Make it how it was before.

**Comment by hishamco** [comment]
May be the first screenshot is accepted but the other once introduce a spacing issue which is not needed

**Comment by Skrypt** [comment]
Well the hamburger menu is not necessary at all I think. We should keep it if people want to extend the top menu with their own menu items (text links). Else I don't think we need it.

**Comment by agriffard** [comment]
What about only show text on small?: 
![media](https://user-images.githubusercontent.com/703248/102536789-6222d500-40aa-11eb-95af-8c1732156e31.gif)

**Comment by Skrypt** [comment]
I'm sorry but I have to say that I don't like it. It doesn't look right.
One of the reasons is that the user menu should not open a second modal like this inside the hamburger menu.
Also, the darkmode and frontend website buttons should be accessible directly in the top bar like the notification button is for Github. Also, notice that the page title is never appended in the top navbar either.

![image](https://user-images.githubusercontent.com/3228637/102561665-41a34c80-40a3-11eb-999b-c84151e9a2ae.png)

Maybe you will say that I'm picky but I can't help but noticing these small details...

**Comment by Skrypt** [comment]
Frontend hamburger menu : 

![image](https://user-images.githubusercontent.com/3228637/102562531-436e0f80-40a5-11eb-9a81-a016d2c2a2c7.png)

Backend hamburger menu : 

![image](https://user-images.githubusercontent.com/3228637/102562557-54b71c00-40a5-11eb-8785-aa41bf8c3a43.png)

Stick to this and I think it will work.

**Comment by hishamco** [comment]
That's why I vote for the text in the menu items at the beginning ;)

**Comment by sebastienros** [comment]
We can't have this hamburger menu in mobile view. This is a regression, and we closed a similar PR some time ago for the same reason. Sorry I didn't think about asking about the mobile view during the meeting. We need more time to evaluate all the changes before taking it.

Better create multiple PRs too for instance for the content items list so we can give feedback independently, and not merge all or nothing.
