### ISSUE TITLE
Markdown script throwing not found error

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8044]
There's a reference to a mde.js script which is throwing a not found error.

I don't think we need it, as it is compiled into the toolbar script. 

So just left over from your refactor I suspect @Skrypt ?

<img width="1371" alt="Screenshot 2020-12-17 at 14 26 28" src="https://user-images.githubusercontent.com/13782679/102500245-0178a580-4074-11eb-9a8b-a85f51832f15.png">

**Comment by Skrypt** [comment]
Possibly, but then the issue was there before too because I just renamed assets to make them more universal.

**Comment by Skrypt** [comment]
I can't repro locally on latest dev.

**Comment by Skrypt** [comment]
Ahh I see it happens only on blogpost
