### ISSUE TITLE
Admin: Key bindings to trigger button actions

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#8059]
In Create/Edit admin pages, provide some keyboard shortcuts to trigger the button actions.

Ex: Alt+S to save.

Handle the Draft/Publish and the 'and continue' cases.

/cc @hishamco

**Comment by sebastienros** [comment]
If we do it please take a look at the common shortcuts in other web apps. At least WP, or apps that have got some accessibility work.
