### ISSUE TITLE
Can all the methods in UserStore be marked virtual to allow the user to override the behavior?

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#8060]
I am trying to change how the users are stored in my app discussed at #7716 

In order to do that, the [UserStore](https://github.com/OrchardCMS/OrchardCore/blob/af6f9b3e17e63db12a8aaf67ac5df1ae34a1489a/src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs) methods needs to be marked as virtual.

Also, shouldn't this [code](https://github.com/OrchardCMS/OrchardCore/blob/af6f9b3e17e63db12a8aaf67ac5df1ae34a1489a/src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs#L102) be `_session.Save(newUser)` instead of `_session.Save(user)`?

**Comment by jtkech** [comment]
> Also, shouldn't this code be _session.Save(newUser) instead of _session.Save(user)?

As said on gitter, after `if (!(user is User newUser))` they reference the same object, so that's okay

**Comment by sebastienros** [comment]
You can already create your own stores and wrap the current implementation instead of inheriting from it.
