### ISSUE TITLE
Preview part missing

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8109]
Hi, 

I have just noticed that Preview Part went missing somewhere between OC version 1.0.0-rc2-15533 and 1.0.0-rc2-15673, it also seems like there is no pull request related to this case, so I guess it was not hidden intentionally? 

If it was hidden intentionally, is there any other way how to configure preview url as in this article? https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/#configuring-the-preview-feature-for-blog-posts

Also there are other problems in last working version:
1) Preview url does not support absolute url, so it can not be used in headless sites where site url is different than cms url. (I can fix this one) 
2) there is different address of preview in listing and detail.

In list there is address from preview part, but it can not handle absolute url (creates something like http://address.com/http://address2.com, that is also a problem for me)
![image](https://user-images.githubusercontent.com/52829889/102766326-3f304380-437e-11eb-875f-edc0aa853a5e.png)

In detail, there is address to preview controller..
![image](https://user-images.githubusercontent.com/52829889/102766295-33dd1800-437e-11eb-8162-d3d5e48ce1da.png)

**Comment by MikeKry** [comment]
Apparently preview part is back in newest version, only problems 1 and 2 remains, will check it myself.

**Comment by MikeKry** [comment]
@deanmarcussen 

I need absolute urls in preview part setting for headless sites to be able to set Client app url prefix. I can do it myself, but I want to discuss this before I do that. 

I think there are two options:
a.1) change logic in ContentLinkTagHelper / ProcessAsync to allow absolute urls (http://headless-client.com/previewpath)
a.2) and in PreviewController / Render - here I am not sure, if it should even go in that function for headless sites, imho it could just redirect to preview url with some parameters to identify (given by pattern and possibly url param &preview=true) as functionality in headless client app can be completely different from OC. 
b) add new setting for remote url (may be useful for also for other things, e.g. preview part) - same as before, but it would change base path for some requests, so you would not need to edit preview part, only setting, I think first option might be better for this case.

**Comment by deanmarcussen** [comment]
@MikeKry

It probably depends on what you mean by Preview.

I can't see how live preview could work with headless, without quite a lot of work, to it, and implementation on the headless app to actually support. It would then require a lot of work in the Headless app to support it (as in pretty much all the code / logic in the PreviewController/ View iFrames. Live preview stores the previewing content item in localstorage, which is where Render starts getting involved, so a headless app would need to be doing similar things.

Maybe what you are talking about / want is Preview Draft? 

How are you fetching? GraphQL I recall, not sure if you can fetch drafts there, but you will know if you are using it.

**Comment by xkuzel06** [comment]
@deanmarcussen 

All I need for headless app is to redirect user from CMS to some path in headless app with some token (contentItemId or something), then I can fetch everything needed through GraphQL. But that is not possible now, because everything uses only relative urls.

So yes, I am probably talking about "Preview Draft" and "View (Published)", if "Preview" button creates live preview, then there could be just possibility to hide it for headless sites (imho this would need some very specific implementation for each headless site so it does not need to be in OC by default)

**Comment by deanmarcussen** [comment]
ok so I would probably just Disable the ContentPreview module, which will remove the Preview button from the edit screen, where contextually for a headless app would make no sense.

I don't think the preview part is useful here for you, nor should it be, as it is designed for decouple mode, not headless.

For the other two buttons, preview draft, and view published, I would suggest just override the views for those, in a module.

Replace https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsButtonActions_SummaryAdmin.cshtml and
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsButtonEdit_SummaryAdmin.cshtml

with what you prefer

**Comment by MikeKry** [comment]
@deanmarcussen

Thanks for tip, that is for sure possible solution! 
Only problem is that these views will need to be updated with every (relevant) update of OC. Otherwise modified views could be inconsistent with currrent OC version.. but I guess it is the simplest solution for now.

Anyway, I have done some more research on this topic and realized, that OC currently has "Base url" setting, which is used in sitemaps and also it is used in Autoroute as an url prefix, but it is not reflected in associated link button:
![image](https://user-images.githubusercontent.com/52829889/107077294-ecef9880-67ec-11eb-87ca-fd3e1f598667.png)

So I am just thinking, if we are currently using "Base url" in autoroute display as route prefix, shouldn't it be also in the link button in autoroute and also View / View draft buttons?

**Comment by Piedone** [comment]
I assume you abandoned or worked around this problem since then. If there's something still in Orchard Core that should be addressed, please open a new issue with specifics, and one for each problem.

**Comment by MikeKry** [comment]
@Piedone 

It depends. I have used custom implementation, but if we would like to go more headless way, it would still be nice to have configurable preview/view links. 

But it is not urgent for me, and if nobody else needs that, I would keep that closed for now. 

I wonder, if there are some statistics how many people use the headless variant of OrchardCore?

**Comment by Piedone** [comment]
We don't (can't) really collect such stats, but judging from the amount of [issues](https://github.com/OrchardCMS/OrchardCore/issues?q=is%3Aissue+is%3Aopen+headless), [PRs](https://github.com/OrchardCMS/OrchardCore/pulls?q=is%3Apr+headless+), [discussions](https://github.com/OrchardCMS/OrchardCore/discussions?discussions_q=is%3Aopen+headless), people are using it, but it's probably a minority of use cases.

**Comment by zyr2288** [comment]
> Hi,
> 
> I have just noticed that Preview Part went missing somewhere between OC version 1.0.0-rc2-15533 and 1.0.0-rc2-15673, it also seems like there is no pull request related to this case, so I guess it was not hidden intentionally?
> 
> If it was hidden intentionally, is there any other way how to configure preview url as in this article? https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/#configuring-the-preview-feature-for-blog-posts
> 
> Also there are other problems in last working version:
> 
> 1. Preview url does not support absolute url, so it can not be used in headless sites where site url is different than cms url. (I can fix this one)
> 2. there is different address of preview in listing and detail.
> 
> In list there is address from preview part, but it can not handle absolute url (creates something like http://address.com/http://address2.com, that is also a problem for me) ![image](https://user-images.githubusercontent.com/52829889/102766326-3f304380-437e-11eb-875f-edc0aa853a5e.png)
> 
> In detail, there is address to preview controller.. ![image](https://user-images.githubusercontent.com/52829889/102766295-33dd1800-437e-11eb-8162-d3d5e48ce1da.png)

I'm having the same problem, I've found the source code:
```cs
public override async Task ProcessAsync(TagHelperContext tagHelperContext, TagHelperOutput output) {
//...
        if (DisplayFor != null)
        {
            contentItem = DisplayFor;
            var previewAspect = await _contentManager.PopulateAspectAsync<PreviewAspect>(contentItem);

            if (!string.IsNullOrEmpty(previewAspect.PreviewUrl))
            {
                var previewUrl = previewAspect.PreviewUrl;
                // "/yourUrl" -> "~/yourUrl"
                // "~/yourUrl" -> "~/yourUrl"
                // Maybe there's a better way to handle this.
                if (!previewUrl.StartsWith("~/", StringComparison.OrdinalIgnoreCase))
                {
                    if (previewUrl.StartsWith('/'))
                    {
                        previewUrl = '~' + previewUrl;
                    }
                    else
                    {
                        previewUrl = "~/" + previewUrl;
                    }
                }

                output.Attributes.SetAttribute("href", urlHelper.Content(previewUrl));
                return;
            }

            metadata = await _contentManager.PopulateAspectAsync<ContentItemMetadata>(DisplayFor);

            if (metadata.DisplayRouteValues == null)
            {
                return;
            }

            ApplyRouteValues(tagHelperContext, metadata.DisplayRouteValues);

            output.Attributes.SetAttribute("href", urlHelper.Action(metadata.DisplayRouteValues["action"].ToString(), metadata.DisplayRouteValues));
        }
//...
}
```

**Comment by hishamco** [comment]
If there's a bug please file a new issue so we can track it
