### ISSUE TITLE
can't find user  use Query<T,TIndex> with linq

### ISSUE THREAD

**Issue by yiji** [OrchardCMS/OrchardCore#811]
i use _session.Query<User,UserIndex>(user=>emailArrys.Contains(user.NormalizedUserName)) can't find user,must use  _session.Query<User, UserIndex>().Where(user=>emailArrys.Contains(user.NormalizedUserName))

**Comment by sebastienros** [comment]
Probably a bug in YesSql

**Comment by sebastienros** [comment]
Please reopen if it repros, it's kind of old and odds are that it's already been fixed.
