### ISSUE TITLE
Relative time

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#8114]
Use a web component that extends `time` to render a relative time (`... days ago`):

![image](https://user-images.githubusercontent.com/703248/102806760-c05afb00-43bd-11eb-9a63-c06090f96007.png)

https://github.com/github/time-elements

**Comment by Skrypt** [comment]
Related with https://github.com/OrchardCMS/OrchardCore/issues/2965

**Comment by hishamco** [comment]
@Skrypt I think you did similar PR that merged today

**Comment by Skrypt** [comment]
Nah it was not a shape that returns a complete html element. We forged the element in the view with the result of a shape.

**Comment by sebastienros** [comment]
Where, when, why?

**Comment by sebastienros** [comment]
After talking with @agriffard the suggestion is to use a client-side component to render the tooltip with the client's timezone instead of the settings one.
