### ISSUE TITLE
OpenId comparing URI-style claims with OpenIdConnectConstants

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#812]
Depending on the host, a `ClaimsIdentity` may use URI-style claims, e.g. `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` instead of just `name`, as it is defined in `OpenIdConnectConstants.Claims.Name`.

This will cause CreateTicketAsync to fail in OrchardCore.Modules\Orchard.OpenId\Controllers\AccessController.cs on these lines:

~~~~
                if ((claim.Type == OpenIdConnectConstants.Claims.Name && ticket.HasScope(OpenIdConnectConstants.Scopes.Profile)) ||
                    (claim.Type == OpenIdConnectConstants.Claims.Email && ticket.HasScope(OpenIdConnectConstants.Scopes.Email)) ||
                    (claim.Type == OpenIdConnectConstants.Claims.Role && ticket.HasScope(OpenIddictConstants.Claims.Roles)))
                {
~~~~

This can be resolved by configuring `IdentityOptions` in `Startup`, for which I will shortly link the PR.

**Comment by kevinchalet** [comment]
This was fixed by https://github.com/OrchardCMS/OrchardCore/pull/3326.
