### ISSUE TITLE
Add default values to all fields and support Liquid

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#8121]
Add default values to all fields and support Liquid
DateField Default today ： {{ "now" | local | date: "%F" }}
TimeField By default, 8 a.m ： 08:00:00

-----------
为所有字段添加默认值，并支持Liquid
如日期字段默认当天:   {{ "now" | local | date: "%F" }}
如时间字段默认早8点:  08:00:00

**Comment by MikeKry** [comment]
This would be great also for textfields

**Comment by hishamco** [comment]
I agree for DateField, regarding the TimeField may be the current time will be better, @chinasqzl could you please send a PR for this?

**Comment by chinasqzl** [comment]
ok @hishamco

**Comment by Piedone** [comment]
Closing due to the same reason as the PR: https://github.com/OrchardCMS/OrchardCore/pull/10497#issuecomment-1897539384
