### ISSUE TITLE
KeyVault Configuration Expose DefaultAzureCredential

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8124]
The new KeyVault Configuration feature is great. ty @JoshLefebvre 

There are some instances where the default `new DefaultAzureCredential(includeInteractiveCredentials: true)` doesn't work though.

It should work properly with VS Code, but doesn't always.

VS Code w/docker needs to have the default values changed.

Suggest we expose an overload where the credentials can be changed.

**Comment by JoshLefebvre** [comment]
Thanks ! 

I've had it working without issue on VSCode using the "Azure Account" extension with the "Azure: Sign In" command. I've specified this in the documentation. Can you specify what exactly doesn't work in vscode.

As far as getting it to work with Docker (or deployed on any non Azure infra) yes you are correct that this would not work and should have an overload to allow service principle or managed identity creds. I can take this on.

**Comment by JoshLefebvre** [comment]
Oh actually just saw the PR! Nvm :)
