### ISSUE TITLE
Absent ContentPickerField in "Content Menu Item Type"

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#8145]
I tried to edit "Content Menu Item" - Content Type in  the "Content definition" UI it looks like this 

![image](https://user-images.githubusercontent.com/13991195/103045628-210f4280-453a-11eb-9d5b-d84d9288254e.png)

I have noticed there is no "ContentPickerField" but `ContentPickerFieldDisplayDriver` is triggered when I'm trying to add "Content Menu Item" 
Plus there is a field in the Menu's module migration recipe "src\OrchardCore.Modules\OrchardCore.Menu\Migrations\menu.recipe.json"
```
{
          "Name": "ContentMenuItemPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true,
              "DisplayName": "Content Menu Item",
              "Description": "Provides a menu link behavior with the Content Picker for your content item."
            }
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "ContentPickerField",
              "Name": "SelectedContentItem",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Selected Content Item",
                  "Position": "0"
                },
                "ContentPickerFieldSettings": {
                  "Required": true,
                  "DisplayAllContentTypes": true,
                  "DisplayedContentTypes": []
                },
                "ContentIndexSettings": {}
              }
            }
          ]
        }
```
I think "ContentPickerField" should be displayed in the "Content definition" UI.
I used the "Agency" installation recipe from dev branch.
Am I missing something or this is a bug?

**Comment by Piedone** [comment]
You don't see it there, because the field is not added on the part called "ContentMenuItem" (that would be the invisible part handing fields if you were to add them to the content type Content Menu Item). Rather, to the part called "ContentMenuItemPart". And that you can inspect, including the Content Picker Field attached to it, under Content -> Content Parts.
