### ISSUE TITLE
Feature Request: Color Picker Field

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#8149]
I would like my tenants to be able to pick their own "primary" and "secondary" colors for their site theme. I don't want to manually have to update css or sass files for each tenant's theme. I already have my own OC module called #[OrchardCore.CustomStyleSettings ](https://github.com/LefeWareSolutions/OrchardCore.CustomStyleSettings) where I would allow them to set this and be used in their theme by injecting the color setting.

Anyways what I am proposing is a new OrchardCore Color picker field. I would be happy to take this on myself if there was interest in adding this to the project, otherwise I will create my own custom module. The only thing I need confirmation on is what existing javascript library to choose from. Again happy to evaluate these myself and help out in any way I can.

A list of popular color picker libraries: https://morioh.com/p/599d55afd92d

**Comment by JoshLefebvre** [comment]
Possibly related: https://github.com/OrchardCMS/OrchardCore/issues/5867

**Comment by agriffard** [comment]
There is a Color editor for the Text field.
Do you want a specific one?

**Comment by JoshLefebvre** [comment]
Oh I had no idea! That would work for my use case ! Thanks @agriffard . I will close this issue
