### ISSUE TITLE
Authentication provider: Reset

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#8157]
There is no way to reset any of the external authentication provider once it has been configured because all the Save require some values.

/cc @MichaelPetrinolis

**Comment by agriffard** [comment]
@MichaelPetrinolis Do you think there should be a Reset method in each external authentication module and a button to call it?

**Comment by MichaelPetrinolis** [comment]
@agriffard why someone will reset the settings if he must enter correct values again? Why not just disable the module if no longer needed? Or something I don't catch here.
