### ISSUE TITLE
Add option to hide recipe in admin recipes list

### ISSUE THREAD

**Issue by arkadiuszwojcik** [OrchardCMS/OrchardCore#8182]
**Is your feature request related to a problem? Please describe.**
Recently I started using inner recipe feature and I have few inner/sub recipes and one master recipe that use them. What bothers me a bit is that my inner recipes are displayed in admin recipes list even if those recipes are  just internal and intendent to be used only by master recipe and not individualy.

**Describe the solution you'd like**
Recipes should have additional flag: Hidden/Visible? that indicate if it should be visible in recipes list.

**Describe alternatives you've considered**
- Maybe instead of flag such invisible recipes should have extension: ".inner.recipe.json"?
- Maybe it is not a problem aftr all and it will only complicate design?

**Comment by giannik** [comment]
try hidden attribute

{
  "name": "01_Setup",
  "displayName": "01_Setup",
  "issetuprecipe": false,
  "tags": [
    "hidden"
  ],


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by arkadiuszwojcik** [comment]
@giannik thank you. That worked for me.
