### ISSUE TITLE
Setup screen fails when user has a previous failed setup

### ISSUE THREAD

**Issue by TalMcMahon** [OrchardCMS/OrchardCore#8189]
Setup screen errors with "The user name is required" even though it is properly filled in (image below).

* If you re-enter the username and submit, the create fails and you end up on the "The requested tenant is currently initializing" screen (also image below)

I have not found an easy way to recover from this state.

This is a tough thing to reproduce, I will do my best to describe it. It seems to be related to the Username being re-used as the Super User.  

I was working on a recipe and wanted to apply it to a "Blank Site" Logged in as the super user (my email address).    My recipe failed when I tried to execute it from the recipes screen. I was unable to do anything else as my recipe really gummed it up.  It was after this point I came across the bug described above.  Here are the steps I followed after that:

**Steps to Reproduce**
1. I closed the browser. (which stops the debugger/iisexpress)
3. Deleted the Bin, Obj, and App_Data folders to get a clean start. (I am using the SqlLite option. so this should be all of the data)
3. Hit F5 to start a brand new site from the create screen.
4. Selected everything the same from my previous setup (Chrome auto filled it)
5. Used the same email address as my Super User Name
6. Hit submit Saw the bug described above.

**Work Around** 
1. I stopped the debugger
2. Deleted the Bin, Obj, and App_Data folders to get a clean start.
3. Hit F5 to start a brand new site from the create screen.
4. Selected everything the same from my previous setup (Chrome auto filled it)
5. Used a **something unique** as my Super User Name
6. Site was created as expected.

**Expected behavior**
I expected that if I delete the Bin, Obj, and App_Data Folders, I would have an entire reset of the app and would be able to start again from scratch. 

**Other information**
 The problem seems cache or cookie related, I have ruled out cookie with the following tests
     * Ran into the same issue in "Incognito" mode on Chrome (Chrome is my default browser)
     * Ran into the same issue running it with Edge Browser.
 
**Screenshots**
The error on the screen:
![image](https://user-images.githubusercontent.com/3964594/103374124-5d8ff080-4a9c-11eb-8433-cc217538d32f.png)

The only screen that will display after the above error occurs:
![Version1 0 0-rc2-15720-Fail2](https://user-images.githubusercontent.com/3964594/103374245-ad6eb780-4a9c-11eb-947e-7e700144cd01.png)

**Comment by jtkech** [comment]
Yes, the `@` char is no more allowed for an user name

But the validation message is not well descriptive, someone needs to fix it

Then, normally when it fails, it returns back from the `Initializing` state to the `UnInitialized` state

When i will have time i will dig into this last part

**Comment by TalMcMahon** [comment]
Is the removal of the "@" char a new thing (last few days)?   It seemed to work around build ...509  Maybe that was why I was so confused as I updated in dev.

**Comment by jtkech** [comment]
@TalMcMahon 

> Is the removal of the "@" char a new thing (last few days)?

Yes

Didn't have enough time to work on it yet, will do it asap

**Comment by deanmarcussen** [comment]
> But the validation message is not well descriptive, someone needs to fix it

Yes, I'll sort that out.

**Comment by deanmarcussen** [comment]
Fixed the validation JT

> Then, normally when it fails, it returns back from the Initializing state to the UnInitialized state

This bit doesn't look like it's happening 

The SetupEventHandler to create the user would have returned errors, but there's nothing here to set the state back to uninitialized. As far as I know it never did that behaviour (would be kinda nice for when you put the wrong connection string, but maybe there are other implications?)

https://github.com/OrchardCMS/OrchardCore/blob/afa69a541bd2b22c3e4197931d23171af7fcc674/src/OrchardCore/OrchardCore.Setup.Core/SetupService.cs#L236-L239

**Comment by jtkech** [comment]
@deanmarcussen

> Fixed the validation JT

Cool

> This bit doesn't look like it's happening

It works if returning after the same check `if (context.Errors.Any())` but before line 187, because it returns to `SetupAsync()` that does

https://github.com/OrchardCMS/OrchardCore/blob/afa69a541bd2b22c3e4197931d23171af7fcc674/src/OrchardCore/OrchardCore.Setup.Core/SetupService.cs#L87-L92

> The SetupEventHandler to create the user would have returned errors, but there's nothing here to set the state back to uninitialized. As far as I know it never did that behaviour (would be kinda nice for when you put the wrong connection string, but maybe there are other implications?)

The problem with the last error checking is that the new `shellSettings` we created line 130 is now the one registered in the running shell table (even it is not yet persisted), which is not the case when checking errors line 187

Easy to fix but here at the end of the setup it seems to be too late, we would need to re-do an idempotent setup, so maybe better to throw an explicit exception saying that the tenant is in an inconsistent state needing a fresh setup, or just remove this last check `if (context.Errors.Any())` and let the app throw afterwards

I will dig into it this night.
