### ISSUE TITLE
Admin UI: Depend on https://cdn.jsdelivr.net/

### ISSUE THREAD

**Issue by MRSheikh** [OrchardCMS/OrchardCore#8216]
my Admin UI site depends on https://cdn.jsdelivr.net/ for JQuery libraries but my site and clients are inside LAN and don't connect to internet. 
i think there was an option to bind local resource to admin area default theme.

![image](https://user-images.githubusercontent.com/17869166/103451855-6ec83f80-4cde-11eb-86c8-fb67db19c6f8.png)

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/7721

Just disabled the cdn option
