### ISSUE TITLE
Trumbowyg editor produces javascript error when used with media picker 

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#8217]
Using the blog recipe when I edit a blog using the trumbowig editor and inserting a media item an error occurs when selecting a media item from the modal picker dialog, as shown below.

context
![image](https://user-images.githubusercontent.com/1516981/103458121-c0d48980-4d0d-11eb-9886-e3251b47d4ff.png)

**Comment by Skrypt** [comment]
Can't repro on latest dev when I add a `HtmlBodyPart` to the `BlogPost` Content Type.

**Comment by PiemP** [comment]
@giannik see https://github.com/OrchardCMS/OrchardCore/issues/6864#issuecomment-769827279

**Comment by hishamco** [comment]
@giannik could you try to set `svgPath: false`
