### ISSUE TITLE
Wysiwyg: Content item link

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8241]
When user inserts link to a content item through wysiwyg, it will become invalid when document permalink changes. 

It would be great, if we could link content items directly (e.g. like in menu), through contentitemid / alias

**Comment by Skrypt** [comment]
You can do this by using a Content Picker outside of the Wysiwyg editor as a Content Picker Field.

**Comment by MikeKry** [comment]
@Skrypt 

But content picker field cannot be referenced from wywisyg, as far as I know. 

That was my suggestion at first, but it appears that content editors need urls inside text :)

**Comment by Skrypt** [comment]
Make a shortcode?

**Comment by MikeKry** [comment]
@Skrypt 

Do you have any example? I cant find any example of using fields in shortcode.. 

Anyway, afaik shortcodes are evaluated in client app, so that is not going to help me with headless implementation.. maybe we add add optional shortcode resolver into GraphQL queries - to allow resolving shortcodes in fields, not only in render?

**Comment by Skrypt** [comment]
Normally, you're supposed to be able to render a Content Item entire HTML from GraphQL. Though, I would need to test with a Shortcode to see if it's rendered. And, shortcodes are rendered from server side, not client side.

**Comment by Skrypt** [comment]
Ok, one issue I found is that the Shortcode Liquid template can't use the ContentLiquidTemplateEventHandler to retrieve a content item with a specific ContentItemId. 

https://docs.orchardcore.net/en/dev/docs/reference/modules/Contents/#loading-from-a-content-item-id

Then the shortcode liquid template could be something like (without taking any parameters to make it simple) : 

``` Liquid
{% assign my_content = Content.ContentItemId["4dgpvyegcxm18te7q3r78eee54"] %}
url : <a href="{{ my_content | display_url }}">{{ my_content | display_text }}</a>
```

And then later on add a parameter to the shortcode to take a contentItemId.
Then in you Wysiwyg editor you add [your_shortcode] ...

**Comment by MikeKry** [comment]
@Skrypt 

Nice, thanks for example, will try to play with it tomorrow!

About qraphql - I know, that it can render shortcode in render of complete content item (as I mentioned in my earlier comment), but the thing is that we do not use it, and I think many others will not be using render from orchard, as it is not very useful for e.g. react based frontend client.

So I think it would be nice to have an option to retrieve resolved shortcode at field level: in your example, when you query markdownfield, it should be able to return clean html or html with resolved shortcode, but now it returns only raw shortcode.

**Comment by deanmarcussen** [comment]
HTML and markdown parts and fields should both render shortcodes. Or at least they did when I wrote it

**Comment by MikeKry** [comment]
@deanmarcussen 

I may try it tomorrow with different parts/fields. I did test it today only on HtmlField, but e.g. HtmlBodyPart has different structure, so maybe it works somewhere.

Anyway, if it does not work, the correct solution according to you would be just to make it resolve shortcodes by default on text fields?

**Comment by MikeKry** [comment]
@deanmarcussen 

ok, according to this file, it should really work on htmlbodypart 
https://github.com/OrchardCMS/OrchardCore/blob/0089096efc3968c4451f8d7442db666f53e577c9/src/OrchardCore.Modules/OrchardCore.Html/GraphQL/HtmlBodyQueryObjectType.cs

but If I am searching correctly, there is nothing similiar for HtmlField, looks like it just returns its value: 
https://github.com/OrchardCMS/OrchardCore/blob/c41f7a457744c2da8ef9910882130986453ae143/src/OrchardCore.Modules/OrchardCore.ContentFields/GraphQL/Fields/ContentFieldsProvider.cs

**Comment by Skrypt** [comment]
This right now doesn't work for me on a MarkdownBodyPart :  

```
{% assign my_content = Content.ContentItemId["417qsjrgv97e74wvp149h4da53"] %}
```

And I'm trying to move the ContentLiquidTemplateEventHandler which gets called but returns no data.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/103818512-ab759d00-5036-11eb-8617-655abf306d56.png)
![image](https://user-images.githubusercontent.com/3228637/103818534-b5979b80-5036-11eb-8ccf-5a1e1390d41c.png)
![image](https://user-images.githubusercontent.com/3228637/103818555-c0523080-5036-11eb-9165-114de3052083.png)

**Comment by MikeKry** [comment]
@Skrypt 

and does it work at least with Content["alias:main-menu"] ?

**Comment by Skrypt** [comment]
No it doesn't, I'm trying to find why right now.

**Comment by Skrypt** [comment]
From a Template it works.

![image](https://user-images.githubusercontent.com/3228637/103822003-51c4a100-503d-11eb-9eb6-e8de7ad70fad.png)
![image](https://user-images.githubusercontent.com/3228637/103822031-5be69f80-503d-11eb-8878-e85606db2862.png)

Though the shortcode can't be parsed.

**Comment by deanmarcussen** [comment]
> Markdown seems to have solved that for both body and field. So the solution could be just adding implementation for HtmlField? I believe I can create PR for this if you agree

Yes looks like it was just missed on the `HtmlField`. Code should be as per the `MarkdownField`, so yes please create a pr.

@Skrypt not sure why the accessors are not working in shortcodes. Will have a look when I have a minute. (for infos in a template, you would have to parse the shortcode with a filter, it's not automatic there. so `| shortcode`)

**Comment by Skrypt** [comment]
Yeah we miss a liquid filter. I agree with that.
Though, I showed the issue last night to @jtkech and we've not been able to find why the ContentLiquidTemplateEventHandler.RenderAsync method doesn't work when rendering a shortcode. So, it renders the shortcode and it passes in the ContentLiquidTemplateEventHandler but it never reach the line where it gathers the ContentItemId of the ContentItem we are looking for. So, it's either a bad execution order or something else we did not find yet. Apart than that everything looks like working normally because it nevers throws an error. It just fails silently.

**Comment by deanmarcussen** [comment]
> Yeah we miss a liquid filter. I agree with that.
We already have the filter, it's called ` | shortcode`

> ContentLiquidTemplateEventHandler

Is probably here, where I am setting the `Content` value, overriding the liquidtemplate event handler. 
https://github.com/OrchardCMS/OrchardCore/blob/8c43b50b2c99cdb2743c0a6604a2bbe0d95069f2/src/OrchardCore.Modules/OrchardCore.Shortcodes/Services/TemplateShortcodeProvider.cs#L47

**Comment by Skrypt** [comment]
I looked and it did not seem to be an issue but I can do a double check. It's just a lambda...

**Comment by Skrypt** [comment]
Ok I confirm for the shortcode filter

![image](https://user-images.githubusercontent.com/3228637/103927717-d0c2e380-50e8-11eb-8ec5-f5bfecb56b49.png)

![image](https://user-images.githubusercontent.com/3228637/103927725-d4566a80-50e8-11eb-8c48-d3e0470df369.png)

**Comment by jtkech** [comment]
@Skrypt 

I found why your custom shortcode template was not working, i will open an issue / PR to fix it

Here i could get it working from a liquid view with the `shortcode` filter, and from an html body part

![Shortcode](https://user-images.githubusercontent.com/8586360/103952381-9b49e480-5140-11eb-9653-7439f89c4fe6.png)
