### ISSUE TITLE
Purpose of huge magnifying glass lurking behind the search field

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#8246]
### Describe the bug
There is a huge invisible magnifying icon lurking behind the search field in some of the admin pages. I have used a few different devices to see if there it has a purpose but it doesn't seem to have one.

Maybe it's an easter egg with a $1M prize money to the person who finds it?

It is represented by the orange box in the screen shot... because the SVG has oveflow:hidden it is currently not showing (unless you create your own admin theme and it appears). 

**To Reproduce**
Go to one of the content items list, view the source around the search field.

**Expected behavior**
No huge icon should be there - I think it is a relic from a bygone era of Orchard Core.

**Screenshots**
<img width="1270" alt="Screen Shot 2021-01-06 at 6 56 16 pm" src="https://user-images.githubusercontent.com/2867511/103749699-90645680-5051-11eb-8b43-cc2b0d677208.png">

Can I get rid of it and submit a PR?

**Comment by agriffard** [comment]
It is coming from this html: 
`<i class="fa fa-search form-control-feedback"></i>`

It should look like this:

![image](https://user-images.githubusercontent.com/703248/103751132-1cea2700-5008-11eb-8029-1e4d9136d2d2.png)
