### ISSUE TITLE
Deployment Plan  has an error

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#8248]
i want to export some content definitions to add in my published website. 
I'm using 1.0.0-rc2-15743 dev neuget version.

1- i create new Deployment Plan
2- i selected "Update Content Definitions"  from  Steps
 model
 3-check 5 "Content Types"
4- after execute  i got this error"An error occurred while executing this request."

**Comment by MikeKry** [comment]
@overstartup  Can you add error message from log file?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
