### ISSUE TITLE
Orchard environmental settings discussion

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#825]
Gathering some thoughts on how Orchard2 deals with environmental settings in conjunction with a multi-environment release flow.

### Background
We work with the notion "_code flows up, content flows down_", meaning that code changes flow from `Development Environment -> Test Environment -> Production Environment`, whereas CMS content flows in reverse `Production Environment -> Test and Development Environments`.

The reason for this is to be able to code and test against real-world data, of course with the relevant obfuscation of sensitive data stored in the db, including user account data.

### In a Perfect World
All environment-related settings, assets and configuration are in App_Data (e.g. Settings.txt), Web.config or, more recently, appsettings.json. Only "portable", environment-agnostic content is stored in "the database". 

This means that no data transformations are required to restore from Production to Test or Development.

### In the Real World
Environment-related settings do find their way into the db, especially where settings relate to hosts. In Orchard1 a good example is the SecureSocketsLayer module (Secure Host and Insecure Host) and site settings such as UseCdn. In Orchard2 a good example is the OpenId module (Authority, App Redirect URL's, etc.).

This means that flowing the CMS content from Production to downlevel environments is somewhat more complex as these settings need to be updated to match each environment.

### Discussion Points
1. Is this an issue worth discussion and, if so:
2. Is Settings.txt being under-utilised in favour of db-stored settings?
3. Should the guideline be to _not_ store any environment-related settings in the db?
4. What would be the definition of an environment-related setting?
5. Is there an overall better solution to this problem?

**Comment by Jetski5822** [comment]
I just a PR https://github.com/OrchardCMS/Orchard2/pull/826

What this will allow you to do is register your own... IShellSettingsConfigurationProvider at the application services level.

This allows you to pull in configuration values from anywhere and get them pushed to the Dictionary in ShellSettings, including environmental configuration. maybe this could help

**Comment by jtkech** [comment]
Just for infos and as a reminder, in the distributed branch i needed to fix some race conditions in our `YamlConfigurationProvider` when syncing tenant settings.

And looking at this [aspnet pr](https://github.com/aspnet/Configuration/pull/147) saying `Remove the ability to commit configurations`, we will have to find a solution to save / sync settings.

I will start working on `Provide a per-tenant configuration story` #2038, e.g to take into account the current environment.
