### ISSUE TITLE
The item of list get displayed with Conten type Name + (uuid) instant of its value

### ISSUE THREAD

**Issue by AmadeuAntunes** [OrchardCMS/OrchardCore#8260]
![image](https://user-images.githubusercontent.com/47931101/104001385-7b91db00-5197-11eb-92cf-367f5cabaaa0.png)

When I add a new category it display a **category(uuid)** 

This data get generated when  clicked  **Add Category** however the "test" word is not displayed but **category(uuid)** 

Note the others fields of list get displayed well but it was set from **Recipe**

![image](https://user-images.githubusercontent.com/47931101/104001937-489c1700-5198-11eb-97d2-933e0a5f92ec.png)

**Category** is Content Type

![image](https://user-images.githubusercontent.com/47931101/104001609-d1668300-5197-11eb-8e85-a1a54a12936d.png)

**Fields**

![image](https://user-images.githubusercontent.com/47931101/104001735-04107b80-5198-11eb-883b-089abd75cf8a.png)

Any idea what to deal with it?

**Comment by deanmarcussen** [comment]
You need to use the `TitlePart` which will set the `DisplayText` property of the term, rather than using a field value.

When the `DisplayText` is empty it will fallback to displaying the content type and id together.

Put a `TitlePart` on your `Category` definition.

**Comment by AmadeuAntunes** [comment]
Thank you it worked
