### ISSUE TITLE
Error installing Orchard core project templates from Cloudsmith

### ISSUE THREAD

**Issue by sea-4** [OrchardCMS/OrchardCore#8263]
I received an error when trying to install Orchard core project templates from the latest dev branch on Cloudsmith. I have .net 3.0, .net 3.1 and .net 5.0 sdks installed.
C:\Users\name\.templateengine\dotnetcli\v5.0.101\scratch\restore.csproj : error NU1101: Unable to find package RoslynCodeTaskFactory. No packages exist with this id in source(s): Orchard Core Preview
Failed to restore C:\Users\name\.templateengine\dotnetcli\v5.0.101\scratch\restore.csproj (in 303 ms).

**To Reproduce**
1. Go to https://docs.orchardcore.net/en/dev/docs/getting-started/templates/ 
2. Copy the comand dotnet new -i OrchardCore.ProjectTemplates::1.0.0-rc2-* --nuget-source https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json  
3. Paste and exe on Powershell

**Comment by Skrypt** [comment]
It could be because of -rc2-* target which was not uploaded entirely yet. When you want to use latest we recommend using the nuget package version pinned on the main readme of the repository to avoid this.
