### ISSUE TITLE
Runtime Compilation not working

### ISSUE THREAD

**Issue by luis3199correia** [OrchardCMS/OrchardCore#8264]
### Describe the bug
I've created a module with Razor views to add in my orchard, and when I'm editing my views I need to restart the server to update the page.
OrchardCore version 1.0.0-rc2-15532

**Expected behavior**
After editing a view, should see the changes on the page.

**Comment by agriffard** [comment]
You need to add this environment variable in your web project properties (the project that hosts the OC instance):
ASPNETCORE_ENVIRONMENT = Development

![image](https://user-images.githubusercontent.com/703248/104049994-31841600-51e6-11eb-826f-7e8816302a90.png)

**Comment by luis3199correia** [comment]
I've tried adding the variable and it didn't work.

**Comment by Piedone** [comment]
Can't reproduce with the latest code, please reopen if still applicable.
