### ISSUE TITLE
Is Azure Blob Storage directory marker really safe to delete?

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#8270]
### Describe the bug

`BlobFileStore` currently says for the OrchardCore.Media.txt files that "This is a directory marker file created by Orchard Core. It is safe to delete it." (see https://github.com/OrchardCMS/OrchardCore/blob/c72c6deb44a5e20c1040c26f12613a105aed33a8/src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs#L359). However, are these really safe to delete? I don't think so. You need them to list empty directories, and even if you can delete them from a non-empty directory without issues if you empty it later it'll cause a problem.

### Expected behavior

I'd just make this say "This is a directory marker file created by Orchard Core. Please don't delete it."

**Comment by sebastienros** [comment]
Or

This is a directory marker file used by Orchard Core.

**Comment by Skrypt** [comment]
I think this file is no longer required when using Azure Blob Storage v2
