### ISSUE TITLE
Admin password reset procedure?

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#828]
Oops. Password complexity has become to complex for me... Is there a hack similar to O1 to reset the admin password?

**Comment by Jetski5822** [comment]
Not that im aware, let me pop this on the backlog so we can get something proper.

**Comment by agriffard** [comment]
Reset password will be implemented with this PR #1789 

You can change the default password requirements with a configuration file : http://www.ideliverable.com/blog/how-to-change-the-password-requirements-for-orchard-core-sites

It could also be interesting to create a feature that allow to define the password settings (Required length, Digit, Lower, Upper, NonAlpha, UniqueChars).
