### ISSUE TITLE
NewtonsoftJsonMvcOptionsSetup is never registered

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#8287]
OrchardCore never calls Microsoft's `AddMvc()` or `AddMvcCore()` during registration. The `AddMvcCore()` extension register [NewtonsoftJsonMvcOptionsSetup](https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Mvc/Mvc.NewtonsoftJson/src/DependencyInjection/NewtonsoftJsonMvcOptionsSetup.cs) class which replaces `SystemTextJsonOutputFormatter` with `NewtonsoftJsonInputFormatter` to allow the binding engine to bind request data from json to objects.

For more info #8275

**Comment by jtkech** [comment]
We call `services.AddMvc(options =>`, see https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L73

And you can re-call it from a module startup, or from the app with one of our helpers

We also call `builder.AddNewtonsoftJson()`, see https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L89
