### ISSUE TITLE
[Orchard.Environment.Shell] ShellSettingsConfigurationProvider writes "null" to settings.txt

### ISSUE THREAD

**Issue by timmahon** [OrchardCMS/OrchardCore#830]
**Summary:**
The new ShellSettingsConfigurationProvider writes the text "null" out to the settings.txt file when the value of a shell settings key is null.  A site can be setup, however on subsequent restarts of the site, the site could potentially fail to load as some values might have "null" instead of an empty string.

Example of created settings.txt

![capture](https://user-images.githubusercontent.com/15673531/27246412-53ed8834-52e9-11e7-8d6a-7cf88229f6ca.PNG)

**Steps to Reproduce:**
- Create a new site
- Observe settings.txt file

**Fix:**
The issue can be fixed by the following at line 67 of ShellSettingsConfigurationProvider

`return value ?? string.Empty;`

**Comment by sebastienros** [comment]
I assigned @Jetski5822 but feel free to create a PR, it looks like a simple change.

**Comment by timmahon** [comment]
Ok.. I'll send in a PR shortly.

Also while I'm at it, it seems the keys written to settings.txt are hardcoded (RequestUrlHost, RequestUrlPrefix, DatabaseProvider, TablePrefix, ConnectionString and State)

`configurationProvider.Set($"{name}:RequestUrlHost", ObtainValue(configuration,$"{name}:RequestUrlHost"));`
`            configurationProvider.Set($"{name}:RequestUrlPrefix", ObtainValue(configuration,$"{name}:RequestUrlPrefix"));`
`            configurationProvider.Set($"{name}:DatabaseProvider", ObtainValue(configuration,$"{name}:DatabaseProvider"));`
`            configurationProvider.Set($"{name}:TablePrefix", ObtainValue(configuration,$"{name}:TablePrefix"));`
`            configurationProvider.Set($"{name}:ConnectionString", ObtainValue(configuration,$"{name}:ConnectionString"));`
`            configurationProvider.Set($"{name}:State", ObtainValue(configuration,$"{name}:State"));`

would it not be better to loop over the keys of the dictionary and write these out.  Potentially you might want to store other keys in the site settings too, like Redis/Azure connection strings as well?

**Comment by sebastienros** [comment]
You can store anything else, these ones are just properties of the Settings class.

**Comment by timmahon** [comment]
Actually it's a bug in the Yaml configuration file parser, apparently null value is written as "null" or "~", so the bug is when the configuration file is read back in.

[https://stackoverflow.com/questions/34089496/empty-field-in-yaml](https://stackoverflow.com/questions/34089496/empty-field-in-yaml)

**Comment by jtkech** [comment]
Just for infos, i confirm that with the last master, the site fails to load when **re-starting**. If i go back just before this commit `Moving settings to use asp configuration properly.`, it works.

**Comment by sebastienros** [comment]
This thing with the settings that can be stored in many providers doesn't very safe.

**Comment by jtkech** [comment]
Oh, maybe not, i don't know, maybe just because of the yaml empty field.

**Comment by sebastienros** [comment]
@Jetski5822 Can you explain in more details how this is used exactly?

I don't understand why you would have tenant settings spread across different location, and how not being able to do that is an issue.
Also when I create a tenant, which configuration is responsible for storing them? 
- If one configuration is supposed to store, why not have everything there in the first place

Some ShellSettingsProvider might not be editable, which is fine, the concern is what's the point of having one that can be written to if it can't even contain all the necessary information if a tenant is created from the admin, and we still have to go to another store to provide more information?

**Comment by Jetski5822** [comment]
Where I work they want some of the settings stored in a KMS, but not all settings. Ill do a PR with a sample in, it will be easier to understand.

**Comment by sebastienros** [comment]
Then we should just separate how to create/list tenants from how to find settings for them. Listing might provide default settings, but we could also read them from other feeds.
Only the Manager will be able to create the tenants. Tenants settings should be read only if they are not defined in the Settings base class.
