### ISSUE TITLE
Liquid Part does not have a description for it.

### ISSUE THREAD

**Issue by aderderian** [OrchardCMS/OrchardCore#8320]
Liquid Part does not have a description for it. When setting it to "Attachable" as a content part. There is no description shown for it. We should add one.

![image](https://user-images.githubusercontent.com/868165/104663588-51f71900-569b-11eb-8211-2f674fcaf82c.png)

**Comment by agriffard** [comment]
There is a description:

![image](https://user-images.githubusercontent.com/703248/110459493-55bc8000-80cd-11eb-938f-d02fe8e52fcd.png)

**Comment by agriffard** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/9bd2e28ac04e4d138cc64fb8189eda56f6623f3b/src/OrchardCore.Modules/OrchardCore.Liquid/Migrations.cs#L20
