### ISSUE TITLE
Disable the CDN by default

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#8324]
For better adoption, the CDN usages needs to be disabled by default. It should be opt-in in the admin.
And CDN sources should use the provider that has the most coverage, especially with coverage in China which has the most restrictions for now.

https://github.com/OrchardCMS/OrchardCore/pull/7599
https://github.com/OrchardCMS/OrchardCore/issues/7721

**Comment by hyzx86** [comment]
> And CDN sources should use the provider that has the most coverage, especially with coverage in China which has the most restrictions for now.

Unfortunately, there are very few.😂
Such CDN servers can only be found from Chinese providers.

It is a good idea to disable it by default and then enable it manually by the site admin.

**Comment by agriffard** [comment]
See also #8315 (Doc to explain how to disable the cdn programmatically) and #8154 (Attempt to use CloudFlare)

**Comment by sebastienros** [comment]
In parallel, could someone from China make a module that updates the cdn urls with ones that work? Though I wouldn't want to have this module in this repository since most contributors can't test it, and there would be no way for us to ensure that these are not malicious versions. However if the hashes matched then that would be great.

**Comment by sebastienros** [comment]
@agriffard I saw the PR, and if we fix this current issue then the PR should be the opposite, how to enable it by default.
