### ISSUE TITLE
Admin UI : gulp-sass not working with Node 15

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8325]
Also, gulp-sass seems to be no longer up to date with latest SASS development.
We need to make the gulp pipeline work with at least latest Node 15 version.
There might be some changes required to make SASS compilation work with Node 15.
Need to investigate further and submit a working PR.

/cc @jptissot

**Comment by deanmarcussen** [comment]
Recommended on the gulp-sass repository is to upgrade to gulp-dart-sass as node-sass is deprecated.

https://www.npmjs.com/package/gulp-dart-sass

Quickly tried it as latest node-sass doesn't compile on the latest nodejs anymore.

Worked fine to get some js out, just had to comment out a few things in the gulpfile related to the blog theme which also has a gulp-sass dependency.

**Comment by Skrypt** [comment]
I tried it quickly last week but did not wanted to waste too much time on this as I was working on something else.
What you report is exactly what I found. Need to make a proper PR and see if there are some caveats on moving to Node 15 for other modules like GraphiQL or else.
