### ISSUE TITLE
Microsoft authentication no longer supports /common endpoint

### ISSUE THREAD

**Issue by willnationsdev** [OrchardCMS/OrchardCore#8327]
### Describe the bug
We added the Microsoft Authentication module to our WIP SaaS app. We got our app ID and app secret, plugged them in, and got re-routed to `https://login.microsoftonline.com/common/oauth2/v2.0/authorize`. However, we then get error below:

Application 'XXXX'(NNNN) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

When we asked the team member who set it up for us whether we could make it multi-tenant, they said that it appears to no longer be supported.

So...how do we resolve this? I'd assume we'd have to then change the OC source code to redirect to a different URL, but I don't see any documentation or settings about that.

### To Reproduce
1. Add Microsoft app with a secret.
2. Add OrchardCore's Microsoft Authentication module.
3. Configure OrchardCore's MSAuth module with app ID and secret.
4. Attempt to login via Microsoft. Get error on Microsoft's end with above message.

### Expected behavior
We'd expect to be asked to login to our Microsoft accounts and have that connect back to a created User in OrchardCore automatically.

**Comment by kevinchalet** [comment]
Orchard uses the MSFT authentication handler maintained by the ASP.NET team, that uses the /common endpoint as the default value: https://github.com/dotnet/aspnetcore/blob/v5.0.0/src/Security/Authentication/MicrosoftAccount/src/MicrosoftAccountDefaults.cs#L27.

TBH, I was not aware of this policy change (that doesn't make much sense). The default endpoints are theoretically replaceable, but you'd have to use `IConfigureOptions<MicrosoftAccountOptions>` for that (no GUI-based way to change directly in OC).

@Tratcher FYI.

**Comment by willnationsdev** [comment]
@kevinchalet It seems like the issue *might* have been that the stuff was set up in Azure AD without my understanding that, so we might have just been using the wrong module. The credentials we were initially given also more closely match what Azure AD appears to expect, so I think it was just some confusion on that point.

When we switched to the Azure AD module, we started getting past that error and on to an `id_token` not allowed kind of issue. They then said they turned on tokens, but it still wasn't working. Workday is over though, and we'll have to come back to it on Tuesday. Hopefully we can get things sorted out. Sorry about wasting time on that. I'll let you know if we get the problem resolved.

**Comment by willnationsdev** [comment]
Okay, well, I went through the Azure AD documentation and setup all the modules/configurations. Now we aren't having that issue anymore. But, we do have this issue. The redirect_uri doesn't match what we are sending to Microsoft. Microsoft doesn't allow you to use a non `https` URI, but the one that OC sends them is only `http`. Docs don't mention any way to configure it that I can see. Something I'm missing? (Also, the original problem of this issue is resolved, but I'd like to figure this out regardless).

**Comment by Tratcher** [comment]
@willnationsdev is there a proxy involved? See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0.

**Comment by willnationsdev** [comment]
@Tratcher Yeah, there's a proxy. After investigating the docs you forwarded, we managed to get it working by forcing the request scheme to use HTTPS at the root web project level. Thanks!
