### ISSUE TITLE
Remove merge conflict marker

### ISSUE THREAD

**Issue by ivaskonyanhec** [OrchardCMS/OrchardCore#8331]
### **Describe the bug**
There is a merge conflict marker left after the last merge and apparently it needs to be removed.
https://github.com/OrchardCMS/OrchardCore/blob/0f592d0c7ec22c1afe95084e124a180287d42006/OrchardCore.sln#L356

**Comment by hishamco** [comment]
Thanks @ivaskonyanhec, the bug was in the PR #2682
