### ISSUE TITLE
wysiwyg Editor showing as Textarea on Arabic page

### ISSUE THREAD

**Issue by ziyadsv** [OrchardCMS/OrchardCore#8334]
the existing website working fine but after updating the cms to latest version. The Arabic ckeditor is not working.  Its showing the following error 
jquery-3.5.1.js:4055 Uncaught TypeError: Cannot set property '_dir' of undefined
    at HTMLDocument.<anonymous> (Edit?returnUrl=%2FAdmin%2FContents%2FContentItems%2FAboutUs%3Fadmin%3D-178328462:5288)
    at mightThrow (jquery-3.5.1.js:3762)
    at process (jquery-3.5.1.js:3830)

### Screenshots
![image](https://user-images.githubusercontent.com/7956063/104846414-71848080-58eb-11eb-8238-3e1ebeee498b.png)

**Comment by dodyg** [comment]
What version are you running at?

**Comment by ziyadsv** [comment]
i download the code at January 2021. the code is running fine when i hide **//langs['_dir'] = '@culture.GetLanguageDirection()';**
from src\OrchardCore.Modules\OrchardCore.ContentFields\Views\HtmlField-Wysiwyg.Edit.cshtml. The issue is with _dir is not getting value when i choose arabic as language

**Comment by sebastienros** [comment]
Can someone using arabic validate the fix?

**Comment by hishamco** [comment]
I will try to check this one again

**Comment by dodyg** [comment]
I am running on release 1.2 on .NET 6 on English and Arabic. It works fine.

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/10697
