### ISSUE TITLE
Custom User Settings user properties profile data not initialized or loaded correctly

### ISSUE THREAD

**Issue by OrchardSkills** [OrchardCMS/OrchardCore#8344]
### Describe the bug
Custom User Settings user properties profile data not initialized or loaded correctly

### To Reproduce
1. Create a Custom User Setting
2. Add the user properties profile data
3. Exit the Orchard CMS Web Application
4. Rerun the Orchard CMS Web Application
5. Try to view the user properties profile data on a liquid page (not there)
6. Go back and save user properties profile data
7. View the user properties profile data on a liquid page (see it there)

### Expected behavior
After exiting the Orchard Core CMS Web application, the user properties profile data should be available in the liquid page without resaving it.

### Screenshots
![image](https://user-images.githubusercontent.com/59172485/104918473-0c17aa80-5952-11eb-9a1b-4115fe5d9e6f.png)
Should have Avatar and (FirstName LastName)

![image](https://user-images.githubusercontent.com/59172485/104918656-4e40ec00-5952-11eb-98e7-7dd1279e84e3.png)
Resave user properties profile data

![image](https://user-images.githubusercontent.com/59172485/104918760-77617c80-5952-11eb-90e3-f28c7837a8df.png)
Avatar and (FirstName LastName) are now being displayed

{% assign user = User | user_id | users_by_id %}
{{ user.Properties.UserProfile.UserProfile.FirstName.Text }} {{ user.Properties.UserProfile.UserProfile.LastName.Text }}

YouTube Video
https://youtu.be/SDQbQzMEq4o

GitHub Repository
https://github.com/OrchardSkills/OrchardSkills.OrchardCore.CustomUserSettings

**Comment by Skrypt** [comment]
I think the issue in this case might be in the driver that you used for extending the Admin UI.

**Comment by deanmarcussen** [comment]
I tried your repository and steps and it all worked fine for me.

- created site
- edited user
- stopped site
- restarted site
- user name etc was there

Am I missing something in the steps here?

<img width="486" alt="Screenshot 2021-01-18 at 18 57 17" src="https://user-images.githubusercontent.com/13782679/104953864-2471de80-59bf-11eb-8a3a-6fa0d84d05ca.png">

**Comment by deanmarcussen** [comment]
Nice theme btw.

you could do a video on how to style the login page - looks very bootstrapping which is odd with material.

**Comment by davidhayden** [comment]
I think it's the way you're accessing the user properties.

In the first part you were logged in as the user and probably accessed those properties from the user that was logged in.

In the second part you were logged out and those properties were not available for the anonymous user.

In your scenario it appears you want to access the properties on the Author or Owner of the ContentItem, and not the logged in user.

I wrote a blog post that did something similar. [Custom User Settings in Orchard Core](https://www.orchardcore.io/blog/custom-user-settings-in-orchard-core)

**Comment by OrchardSkills** [comment]
Thanks, David!
I changed:
Liquid:
{% assign user = Model.ContentItem.Owner | users_by_id %}
Recipe:
"Owner": "[js: parameters('AdminUserId')]",
"Author": "[js: parameters('AdminUsername')]",
And, It's working now.
