### ISSUE TITLE
RolePermissionHandler uses hard coded claim role name

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#8345]
Hello,

I'm running into an issue in RC2 and I've checked the latest dev code and it's the same:

https://github.com/OrchardCMS/OrchardCore/blob/80b3e5bcbfcaa4704aa054ce37765ef8f35195b8/src/OrchardCore.Modules/OrchardCore.Roles/Services/RolesPermissionsHandler.cs#L47

The above checks for a claim role named `http://schemas.microsoft.com/ws/2008/06/identity/claims/role` which relies on the default claim mapping dictionary being left as standard. Explained in this blog post: 

https://mderriey.com/2019/06/23/where-are-my-jwt-claims/

It ought to be possible to use the `RoleClaimName` property which is available on the `Identity` object when doing the above comparison, as that will use the correct role claim name which has been defined in the authentication provider. 

We are only hitting this because we are using a customized authentication module, but I think it's reasonable for Orchard to not make assumptions on the role claim name.

**Comment by Piedone** [comment]
This works very differently now. Please reopen with specifics if this is still an issue.
