### ISSUE TITLE
admin account credentials of try.orchardcore.net not working

### ISSUE THREAD

**Issue by V4A001** [OrchardCMS/OrchardCore#8348]
### Describe the bug
I requested a demo site at https://try.orchardcore.net/

### To Reproduce
1. Request demo site.
2. Wait for demo site and credentials to be emailed by email
3. Access demo site: working.
4. Access admin part of demo site with credentials in email: not working

### Expected behavior
Access to admin part is expected.

**Comment by V4A001** [comment]
I am able to access now. I have idea it is not possible right after receiving the email. I checked my credentials, but I have idea I did use the correct password (without trailing spaces) after copying it.

**Comment by hishamco** [comment]
Ya you need to confirm first, so closing this ...
