### ISSUE TITLE
NumericField only accepts Integers

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#8356]
Even though the NumericField value is a decimal,
![image](https://user-images.githubusercontent.com/8073622/105026573-96413b00-5a46-11eb-80c2-899b751b2a1d.png)

It only allows integers due to this:
https://github.com/OrchardCMS/OrchardCore/blob/f14739dde42286ae736f49bbc5b2bd5e8524949f/src/OrchardCore.Modules/OrchardCore.ContentFields/Drivers/NumericFieldDisplayDriver.cs#L91-L96

Is this intended?

As a workaround I'll use a TextField.

**Comment by Skrypt** [comment]
You have misread this validation.
It says. If the NumericField.Scale == 0 it means it should be an integer. The Scale here is the amount of numbers after the decimal point. So, if you want to use a number with 2 numbers after the decimal point you specify it in the Content Definition of your field.
