### ISSUE TITLE
Blog posts are in the wrong order.

### ISSUE THREAD

**Issue by abazanov** [OrchardCMS/OrchardCore#8357]
I created loads of stub blog posts all in one day. Now I am finishing them one by one and publishing them. On the front end, it is not listing them in the Published date order, but in the created date order, so they all look like they were posted on the same day. Is there a configuration or is it a bug?

**Comment by dodyg** [comment]
Check on the query at "Search > Queries > All Queries" to see how it is sorted. You can modify the sorting criteria there.

**Comment by deanmarcussen** [comment]
There is not a configuration for the list part too sort based on published order.

There is a sorting setting, allowing you to manually sort them.

The general expectation was that they should be sorted in created order, or republishing a content item (after a minor edit) would move it the top of the list.

However, you can also add the `CommonPart` to the `BlogPost` to edit the created date, to organise them as you wish.

**Comment by abazanov** [comment]
Thanks Guys.

@deanmarcussen I do see what you mean about republishing it after a minor change. The thing I found about blogging is that you get ideas during the day, you make a stub blog post, and then you leave it there until you can expand on it properly. That can be months down the line. Then when it gets published as a "big release", it is nowhere to be found, but lost in some long gone by posts in the past. I guess there needs to be a "first published on" date or something. 

Thank you both for your comments. Very helpful. I will close it with this comment because I have some actions that I can take now.
