### ISSUE TITLE
Cannot clear zones in layer zone settings

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#8360]
1. Navigate to **Design** -> **Settings** -> **Zones**
2. Remove all zones from **Available zones for Layers**
3. Click **Save** button

The zones do not clear, but instead remain the same.

The cause is an NRE in the [LayerSiteSettingsDisplayDriver](https://github.com/OrchardCMS/OrchardCore/blob/e0eb00b352db8a4a271c160f37755d5f702b63ab/src/OrchardCore.Modules/OrchardCore.Layers/Drivers/LayerSiteSettingsDisplayDriver.cs#L58) when attempting to split `model.Zones` when null.

```csharp
settings.Zones = model.Zones.Split(new[] { ' ', ',' }, StringSplitOptions.RemoveEmptyEntries);
```

I'll create a pull request to fix this.

**Comment by Skrypt** [comment]
I think this has been intentionally made to not be able to remove every zones but to keep at least one zone active.
Though, it makes sense to be able to clean all zones but then the Widget UI needs to display a proper notification if that's the case. But there are multiple issues "NRE's" that I found over time with this.

**Comment by davidhayden** [comment]
I see what you're saying, but I'm not sure that is the case in this instance. You can create a theme with no zones. I do it when training other developers to create themes from scratch. My base setup recipe starts with no zones and I've never had an issue so far.

There is a [check for no zones when displaying widgets](https://github.com/davidhayden/OrchardCore/blob/e0eb00b352db8a4a271c160f37755d5f702b63ab/src/OrchardCore.Modules/OrchardCore.Layers/Views/Admin/Index.cshtml#L35), which makes me believe that not having zones is expected.
