### ISSUE TITLE
Should there not be a registration confirmation view after an successful registration.

### ISSUE THREAD

**Issue by WolvvCore** [OrchardCMS/OrchardCore#8362]
Greetings, 
Should there not be a registration confirmation view in de user module similar to Forget password function.
Where you inform the user that he has to check his email, to confirm his email address and thereby enabling his account.
And so to speak competing the registration, if email validation is enabled.
I not only suggesting this so I not have to customize the user module every version update
I think this would better guide the user through the process from registration until first login.

**Comment by Piedone** [comment]
There is one `RegistrationPending` page/view now.
