### ISSUE TITLE
ContentPickerField : Add custom text informations into selector

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8374]
Currently content picker has only DisplayText (or ContentItemId) displayed for each content item. This seems to be an issue when you have multiple similiar/same titles on content items in same/different languages.

I have proposed possible change in #8280, but it seems it needs more discussion on this topic.

Maybe it could have some setup field with liquid support, so each project can configure its own display names for content items?

**Comment by deanmarcussen** [comment]
A setting with liquid, similar to the autoroute pattern sounds like a good idea.

Simpler than aspects, and easier to customise

**Comment by MikeKry** [comment]
@deanmarcussen 
as discussed, I have added liquid support to content picker for additional description and I also added option to customize title itself:
![image](https://user-images.githubusercontent.com/52829889/121809799-909afa80-cc5e-11eb-9705-7853ca1ccc18.png)
![image](https://user-images.githubusercontent.com/52829889/121809804-95f84500-cc5e-11eb-9ddb-aa5bbf805d8f.png)

**Comment by Piedone** [comment]
Implemented by https://github.com/OrchardCMS/OrchardCore/pull/8280.
