### ISSUE TITLE
duplicated items in UserPickerFieldIndex table

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#8394]
### Describe the bug
When using User Picker Field, I'm getting duplicated items inside UserPickerFieldIndex table.
No matter if you add ContentItem programatically or via admin panel.

### To Reproduce
1. Create new **ContentType** named **Example**,
2. Add field of type **UserPickerField**, choose "Display All Users" for roles property,
3. Add few **ContentItems** of that new type via admin panel or programatically,
4. Query database (MS SQL)
`select * from [dbo].[MySite_UserPickerFieldIndex] where ContentType = 'Example' and Published = 1 and Latest = 1`,
5. Items are duplicated.

### Expected behavior
One row for each published ContentItem.

### Screenshots
![db](https://user-images.githubusercontent.com/6403130/105418205-01546280-5c3d-11eb-9da1-f7b1722d75bd.JPG)
![code](https://user-images.githubusercontent.com/6403130/105418213-03b6bc80-5c3d-11eb-9ffc-3008fe4aec34.JPG)

**Comment by Skrypt** [comment]
Will try to repro. But is it from the latest dev?

**Comment by Skrypt** [comment]
Ok I can repro with latest dev.

**Comment by lampersky** [comment]
Yes, forgotten to mention, it's latest dev.
