### ISSUE TITLE
Can create shortcode with space or hyphen in name but these are not rendered.

### ISSUE THREAD

**Issue by NogginBox** [OrchardCMS/OrchardCore#8399]
It is possible to create a shortcode with a name like ```my shortcode``` or ```lovely-shortcode``` but when you use them in content they are not rendered and show the shortcode in the final content

### To Reproduce
1. Create short code with name ```my shortcode``` and content ```<span>shortcode content</span>```
2. Creat a content item and use the shortcode in the html body ```[my shortcode]```

### Expected behavior
Either:
- When you view or preview the content item the shortcode is replaced with the shortcode's content.
- When tying to create the shortcode you will be told that the name is not valid.

**Comment by deanmarcussen** [comment]
Probably the best validation to use for the shortcode name is comparing the value against `.ToSafeName()` in the `StringExtensions` class. 

Feel free to open a pr @NogginBox

**Comment by NogginBox** [comment]
@deanmarcussen going to give it a try, but I want to do things in a way consistent to the project.

I'm looking at:

- OrchardCore.Shortcodes.Controllers.AdminController.CreatePost(model, submit)
- OrchardCore.Shortcodes.Controllers.AdminController.Edit(sourceName, model, submit)

The validation code seems to be duplicated in both these methods. Is this normal? If not is there a more DRY example of good validation in action in Orchard that I can base this on.

**Comment by NogginBox** [comment]
Also found a new bug caused by the validation not being duplicated exactly for Edit. You can change the name of a shortcode to be the name of another existing shortcode and it will replace the other shortcode.

Eg: If you start with shortcode1 and shortcode2. Then edit and rename shortcode2 -> shortcode1, this is allowed and now you only have shortcode1.

**Comment by deanmarcussen** [comment]
Sounds like you're looking in the right place @NogginBox 

I wouldn't worry too much about the validation logic being in two places. There are too many places in the code base where it often needs to be a little different on Create and Edit to want to bring them together.

**Comment by NogginBox** [comment]
I have an implementation using ToSafeName(), but this looks a bit too restrictive. It seems to only allow letters and numbers

I've been looking at @sebastienros's [shortcodes project](https://github.com/sebastienros/shortcodes) and it seems to allow more characters, like underscores. I can't work out the definitive set of safe characters for a shortcode name though. @sebastienros what characters can you name a shortcode with?

**Comment by sebastienros** [comment]
First letter: [az][AZ]$_
Any other letter: First letter + any digit

Anything that doesn't match exactly a shortcode will be ignored and rendered as-is
