### ISSUE TITLE
Should assets keep important comments?

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#841]
Assets have "important" comments prefixed with e.g. `/*!` removed on minification / uglification, which may violate the license for 3rd party (open-) source, or at a minimum not give credit where it is due. This is also the case in O1. I'm not a licensing expert, but perhaps this should be fixed.

E.g. change the `removeAll` option to `false`:

~~~~
        .pipe(cssnano({
            autoprefixer: { browsers: ["last 2 versions"] },
            discardComments: { removeAll: false },
            discardUnused: false,
            mergeIdents: false,
            reduceIdents: false,
            zindex: false
        }))
~~~~

And the JsPipeline:

~~~~
        .pipe(uglify({
            output: {
                    comments: "/^!/"
            }
        }))
~~~~

Or using the predefined `comments: "some"` - though somehow the NOTE that is inserted is also preserved.

**Comment by Piedone** [comment]
This isn't applicable anymore.
