### ISSUE TITLE
The "predefined list" in TextField doesn't support multiple selection.

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#8415]
### Is your feature request related to a problem? Please describe.
The "predefined list" in TextField doesn't support multiple selection.

### Describe the solution you'd like
Multiple selection function in the "predefined list". In the database level, could simply store the multiple values with comma seperator.

### Describe alternatives you've considered
This is much simpler than using a bag element which requires another content type to support multiple values.

**Comment by agriffard** [comment]
You can use the `MultiTextField`.

**Comment by orchardc** [comment]
Just realized it is in the latest build now. :) Thanks @agriffard

**Comment by orchardc** [comment]
@agriffard , can I ask  - I can see the **Values** stored in the content field, but how to get the corresponding **Label** in c#?

![image](https://user-images.githubusercontent.com/16193516/105615227-e01f7d80-5dc6-11eb-9679-d2856e18a3a9.png)

**Comment by orchardc** [comment]
Any idea @agriffard ?

**Comment by agriffard** [comment]
It would require to get the settings and for each selected value, find the corresponding label.
