### ISSUE TITLE
Ability to change the logo and ico on the Admin panel without using custom theme.

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#8416]
### Is your feature request related to a problem? Please describe.
Currently, it is not possible to change the Admin panel's logo and ico without a custom theme (set the basetheme to Admin).

### Describe the solution you'd like
Ability to change the logo and ico on the Admin panel without a custom theme.

### Describe alternatives you've considered
A new feature is required.

**Comment by Skrypt** [comment]
This should be a tenant setting then.

**Comment by deanmarcussen** [comment]
I'm not sure another setting is a good idea.

Every setting we add, forces users who have custom admin themes, to also accept that setting.

What if I have already set all the tenants logo to my logo, and don't want them to be able to change it?

And yet suddenly there is a setting that allows them too?

With every new setting we just get further away, from the principle of providing a theming engine which allows users to customize themes as they require.

And then next week someone will want a setting for admin font sizes.
and colors...

Now other options that don't require settings, that might work, for this issue.
- move the relevant bits to a shape, in the `Admin` module. 
- Then to override you can use either the admin templates, or simply place a shape in your own module, take a dependency on the Admin module, and it will override it. No admin theme required.
- We've already done this for the `UserMenu` and it has worked well.

now for css, perhaps we should consider admin layers. much like we have admin templates. would be a simple adaption to the existing layers module.

**Comment by Skrypt** [comment]
I totally agree with that. The only setting that should be kept is the Darkmode one. Because it's a browser/OS feature which can be implemented or not by Admin theme. The others are things that we added to the Admin Theme which are our customizations. For example the admin menu search is a customization that could be removable from a custom admin template.

So basically, we have these settings for them to be changeable on runtime. Which a Liquid template is meant for.

**Comment by Skrypt** [comment]
Also please note that you are supposed to be able to change this image by using only CSS.
See https://stackoverflow.com/questions/28832129/replace-image-src-location-using-css

**Comment by orchardc** [comment]
Hi Skrypt, yes I have tried but the css approach won't apply to the **Admin pane**l wihout using a custom Theme.

**Comment by Skrypt** [comment]
You should be able from the admin to use a Layout Admin Template which should override the current one in your Admin theme. This by enabling the Admin Templates theme of course.

![image](https://user-images.githubusercontent.com/3228637/105613876-586c4b80-5d93-11eb-9e0a-db259c4249db.png)

And then using a custom .css file in this Layout template.
I've not tried, but that should work if not.

**Comment by JoshTango** [comment]
This is already requested from before.
This is the ability to upload a theme or to just enter theme styles into a form of some sort  or upload an image.

**Comment by TFleury** [comment]
Closed by #9149

Documented [here](https://docs.orchardcore.net/en/latest/docs/reference/modules/Admin/#customize-admin-branding)

**Comment by hishamco** [comment]
@deanmarcussen I think we should close this
