### ISSUE TITLE
Autopart SQL error  Invalid column name 'Latest'

### ISSUE THREAD

**Issue by WolvvCore** [OrchardCMS/OrchardCore#8431]
When I edit/created content type with a Autoroute part nothing happens. I see the following error in de log.
`2021-01-25 21:05:57.4126|Default||8977f53-4dc49562e89e70db.||OrchardCore.ContentManagement.Handlers.ContentPartHandlerCoordinator|ERROR|IContentPartHandler thrown from OrchardCore.Autoroute.Handlers.AutoroutePartHandler by SqlException Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Latest'.`

1. I did a pull on 19th jan. Started on localization of content. Added Localization and autoroute part to content item.
2. Wanted to create new language content, But keep seeing "Please save your content item before creating localizations". So I 
    thought maybe I have to remove the content first. But removing content parts from the content item did not work. No change 
    after publish. Than I removed complete content item. Wanted te recreate, and noticed the new content now is not saved.
3. Than checked the log file in app_data, and saw the SQL error.
4. See error above.

### Expected behavior
I checked the database and the AutoroutePartIndex does not have a "Latest' column. 
Looks like more tabels are missing the column, for example the tabel ContainedPartIndex.

Cheers,
Chris Hofgen.

**Comment by Skrypt** [comment]
To resolve your issue you will need to make a SQL Schema Compare between an new Orchard Core installation from the dev branch. Enabling the same modules that you have in your current websites. Then compare it with the clean new installed OC.

This looks like maybe a migration has not executed successfully on your current website.

**Comment by deanmarcussen** [comment]
Normally this is caused by a failed migration on the `Autoroute` or a failed migration in one of your own migrations.

You should see migration errors logged during startup, if it is that.

If you are using an old version of SQL server this is excepted.

See : https://github.com/OrchardCMS/OrchardCore/issues/6210

**Comment by WolvvCore** [comment]
Thank you both for you response. 

I am using SQL Server Express 2019 should not be too old :-) 
There a no error at startup in the logs and I don't use migrations in my customizations.
But maybe the something is wrong with the migration current version in the database. Because non of the update methods are hit during startup. 

In the meanwhile I added the missing columns by hand, and the error a gone.
I not shure if other migrations failed also, .

So I will follow up you advise Skrypt and create new Orchard installation and compare the tables.  
Thx again
