### ISSUE TITLE
Error when executing empty query at Run Sql Query

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#8434]
### Describe the bug
Clicking "Query" button in Run Sql Query feature without entering anything generate error. This happens on the latest nightly build (1.0.0-rc2-15791).

### To Reproduce

1. Go to Run Sql Query
2. Press Query without entering anything
3. It will throw an exception "An error occurred while executing this request."

### Expected behavior
It's should at least show validation message instead of just returning error page.

### Screenshots
![query-1](https://user-images.githubusercontent.com/1761249/105847091-d1fb7800-5fe5-11eb-826a-c3887eff666c.png)
![query-2](https://user-images.githubusercontent.com/1761249/105847100-d58eff00-5fe5-11eb-9ed8-34e2c7f4627b.png)

**Comment by Piedone** [comment]
This was fixed at one point, now the page just reloads.
