### ISSUE TITLE
Add overload to OpenId.UserInfoController.Me action for specific user id

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#844]
It would be nice, especially in server-to-server scenarios, to be able to hit the UserInfo endpoint with an arbitrary userId, that is in addition to `Orchard.OpenId/UserInfo/Me` also have:

`Orchard.OpenId/UserInfo/{userId}`

This will obviously require the caller to have a new permission that allows this, but otherwise a simple task I think. If agreed, I'm happy to submit a PR (and fix #842 too).

**Comment by PinpointTownes** [comment]
The problem with this feature is that it would be totally non-standard, as the userinfo endpoint is only meant to return the profile data associated with the user represented by the access token, not an arbitrary user you specify in the query string.

@anoordende curious: is there any particular reason this feature couldn't be implemented in a separate API controller, decoupled from the userinfo endpoint?

**Comment by anoordende** [comment]
@PinpointTownes Nope, there is no reason it needs to be in UserInfo other than convenience :)

Are there any examples yet of how Api controllers should be architectured in the solution (apart from the OpenId module)? For example, should ApiControllers sit side-by-side regular controllers or in separate modules, e.g. Orchard.Users.Api. Or is this entirely up to custom modules to implement?

And then there's the CORS support (#808), solution-wide, not just for OpenId.

**Comment by PinpointTownes** [comment]
Closing as it doesn't seem there's a high demand to implement this (non-standard) feature OOTB.
