### ISSUE TITLE
WidgetList add widget drop down sometimes appearing under menu

### ISSUE THREAD

**Issue by nogginbox** [OrchardCMS/OrchardCore#8443]
On a page with a widget list the drop down to select a new widget sometimes appears under the menu. Like this:

![Orchard-admin-ui-bug](https://user-images.githubusercontent.com/729381/105974585-f60e9600-6085-11eb-8074-465796ebe573.png)

I'm finding it hard to reproduce on my machine, but it is fequently happening to one of our content editors. They sent me the screenshot.

When I use it the menu goes to the right so does not interfer with the menu. I'm wondering if it is just a certain screen size that causes this issue.

**Comment by Piedone** [comment]
I don't think this happens anyore. If you still see it, please reopen.
