### ISSUE TITLE
Change language: Invariant Language

### ISSUE THREAD

**Issue by luis3199correia** [OrchardCMS/OrchardCore#8448]
### Describe the bug
When I'm setting up my Orchard, the "Change language" field only have "Invariant Language" options, and with that option I have an error in database field "An error occurred while initializing the datastore: Globalization Invariant Mode is not supported."

### Expected behavior
![image](https://user-images.githubusercontent.com/32116636/106027790-258fc380-60c3-11eb-946e-8d60d31a3727.png)

### Screenshots
![image](https://user-images.githubusercontent.com/32116636/106027991-52dc7180-60c3-11eb-8139-4b958d46f5ae.png)

![image](https://user-images.githubusercontent.com/32116636/106029012-8f5c9d00-60c4-11eb-920b-11908a63b76b.png)

![image](https://user-images.githubusercontent.com/32116636/106029042-984d6e80-60c4-11eb-9aa8-914dc9d801c1.png)

I've pre configured my database setup with appsettings
![image](https://user-images.githubusercontent.com/32116636/106028723-34c34100-60c4-11eb-809e-03ad93508d44.png)

**Comment by Skrypt** [comment]
We need more details to repro the issue. Which OS are you using first?

**Comment by luis3199correia** [comment]
> We need more details to repro the issue. Which OS are you using first?

I've Orchard deployed in a AKS pod.

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by luis3199correia** [comment]
I found a system property that was not defined and should be.

**Comment by motord** [comment]
@luis3199correia 
I am having the same problem.
What is this system property you are referring to and how should it be defined?

**Comment by rickythefox** [comment]
> I found a system property that was not defined and should be.

Very helpful...

**Comment by rickythefox** [comment]
For me the problem appeared on the `mcr.microsoft.com/dotnet/aspnet:5.0-alpine` image and was solved by installing lcu-libs.

Change to Dockerfile:
```
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```
