### ISSUE TITLE
Can not add Liquid conditions around <tr> tag in WYSIWYG

### ISSUE THREAD

**Issue by csuhi29** [OrchardCMS/OrchardCore#8455]
### Describe the bug
Cannot add a liquid condition inside a table to display a row conditionally.
### To Reproduce
1. Go to 'WYSIWYG editor'
2. Click on 'View Html button'
3. Write the code
4. Within the table tag write the condition in Liquid. (around the tr tag)
4. Click on 'View Html button' to exit the html view
5. See error (the condition is displayed on the top, outside the table)
#### This is the code i write:
```html
<table>
    <tbody>
        <tr>
            <td><h4>What is your name?</h4></td>
            <td style="text-align: right">My Name</td>
        </tr>
        {% if "yes" == "no" %}
        <tr>
            <td><h4>What seems to be the problem?</h4></td>
            <td style="text-align: right">{% if "problem" == "problem" %}I cannot add liquid tag to display a row conditionally.{% else %}Nothing {% endif %}</td>
        </tr>
        {% endif %}
        <tr>
            <td><h4>How are you feeling?</h4></td>
            <td style="text-align: right">Im feeling confused.</td>
        </tr>
    </tbody>
</table>
```
#### This is the code i get after closing the 'View Html' view:
```html

        {% if "something" == "else" %}
        
        {% endif %}
        <table>
    <tbody>
        <tr>
            <td><h4>What is your name?</h4></td>
            <td style="text-align: right">My Name</td>
        </tr><tr>
            <td><h4>What seems to be the problem?</h4></td>
            <td style="text-align: right">{% if "problem" == "problem" %}I cannot add liquid tag to display a row conditionally.{% else %}Nothing {% endif %}</td>
        </tr><tr>
            <td><h4>How are you feeling?</h4></td>
            <td style="text-align: right">Im feeling confused.</td>
        </tr>
    </tbody>
</table>
```
### Expected behavior
I expected to see the table and inside the table i expected to see the row, and around the row i expected to see the condition.
The result should be a table where a specific row is only displayed if the condition is true.
#### This is what the result looks like instead of the result i desire:
![image](https://user-images.githubusercontent.com/43336129/106251371-2cc6e680-6215-11eb-9065-dcae2c09a820.png)

**Comment by deanmarcussen** [comment]
If you want to be able to use liquid inside the wysiwyg editor, you will need to disable Html Santization.

The sanitizer intentionally prevents usage of liquid inside an html editor, as it could be used to do anything.

You will find the santizer settings in the part settings.

Refer docs https://docs.orchardcore.net/en/dev/docs/reference/modules/Html/

**Comment by csuhi29** [comment]
@deanmarcussen Why is it then that  the liquid **inside the td tag it works just fine** but if i want to display a row conditionally I have to create a new table everytime? As long as I am concerned the Html Sanitization is disabled.
The code below works just fine:
```html
<table>
    <tbody>
        <tr>
            <td><h4>Company Name</h4></td>
            <td style="text-align: right">This is the name of the company</td>
        </tr>
        <tr>
            <td><h4>Email</h4></td>
            <td style="text-align: right">some@email.com</td>
        </tr>
    </tbody>
</table>
{% if "x" == "y" %}
<table>
    <tbody>
        <tr>
            <td><h4>Do not wish to see row</h4></td>
            <td style="text-align: right">{{ Email.Hidden }}</td>
        </tr>
    </tbody>
</table>
{% endif %}
<table>
    <tbody>
        <tr>
            <td><h4>This should always be seen</h4></td>
            <td style="text-align: right">{% if Email.Referrer %}Referred by {{ Email.Referrer }}{% endif %}</td>
        </tr>
    </tbody>
</table>
```
But If i put my Liquid condition inside the table (e.g around the tr tags) the whole thing is put outside of the table in the end.

**Comment by deanmarcussen** [comment]
Ok, so just assumed it was being sanitized. 

Possibly the trumbowyg editor is stripping it. It sounds like from your explanation you are losing pieces during editing?

if that's the case you might want to consider using a liquid part, rather than a wysiwyg editor.

**Comment by csuhi29** [comment]
The editor seems to reorganise the order of the content for some reasons (not losing any content). The Liquid condition is always being put outside of the table tag. So when I try to put a condition inside the table tag (eg. to hide a specific row or column) the condition is put outside of the table.
The same thing happens if I try to create a div and inside a p tag. Then I create a Liquid condition to show/do not show the p tag if the condition is true/false.

**Comment by deanmarcussen** [comment]
Yeah, that's what wysiwig editors do, rearrange content, because they have to render it.

I don't think you will have much success trying to wrap liquid around html tags in a wysiwig editor. I would suggest the `LiquidPart` or the `CodeMirror` editor.

**Comment by Piedone** [comment]
So, then our recommendation is to not mix Liquid with a WYSIWYG editor. If you want to add dynamism to text edited in such an editor, use shortcodes instead.
