### ISSUE TITLE
Should LocalizedSetContentPicker behave this way?

### ISSUE THREAD

**Issue by MananSharma22** [OrchardCMS/OrchardCore#8456]
Refer to the attached video.

Issue : On changing the language of the content type, LocalizedSetContentPickers does not change its respective cultured values .

In the video, the LocalizedContentType is having LocalizedSetContentPickers - Country and State along with their Localized versions. 

On changing the current culture from Hindi | hi to en-IN, LocalizedSetContentPickers is unable to switch to the en-IN version.

https://user-images.githubusercontent.com/50598231/106266022-e93c9e80-624d-11eb-8140-839a6c97cf23.mp4

**Comment by Sen-Gupta** [comment]
I think the issue seems to be that LocalizedSetContentPicker is reading culture from OrchardHelper.GetCulture() instead of the language selected for the content item.

**Comment by jptissot** [comment]
> 
> 
> I think the issue seems to be that LocalizedSetContentPicker is reading culture from OrchardHelper.GetCulture() instead of the language selected for the content item.

Exactly, maybe we could change this behavior for the picker itself, without changing the culture of the entire admin theme ?

**Comment by Sen-Gupta** [comment]
Agree. The LocalizedSetContentPicker is supposed to behave akin to other fields for the item. Read the Item culture not the OrchardCore.

**Comment by jptissot** [comment]
> 
> 
> Agree. The LocalizedSetContentPicker is supposed to behave akin to other fields for the item. Read the Item culture not the OrchardCore.

I think all fields use the culture of the thread, but the ContentPicker allows to pick a item of a specific culture. Does the numeric fields display with the item culture or with the admin culture currently ? (decimal places) Maybe we need to think about all these other fields as well.

**Comment by Piedone** [comment]
Could you please clarify what the issue is, what else would you expect to happen?
