### ISSUE TITLE
IPFS Question - InterPlanetary File Service

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8467]
When someone adds some content and presses save is there a way to hook into the save method so that I can compute the sha256 of the content and only save the hashcode into Orchard Core database?  The actual content would be sent elsewhere to an IFPS service.  Also generally speaking I would like to be able to hook into the save method regardless of IPFS.

**Comment by hishamco** [comment]
You could hook the `IContentHandler` methods

https://github.com/OrchardCMS/OrchardCore/blob/1879619df4418ff175a59ba70dcb36bab89fcbb5/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/Handlers/IContentHandler.cs#L23-L26
