### ISSUE TITLE
Add Remove ContentLocalizationPart handler / index when removed from type definition

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8472]
Apply the equivalent of https://github.com/OrchardCMS/OrchardCore/pull/8382

to the `ContentLocalizationPart` to remove its entries from indexes, when the part is removed from a content type definition.

**Comment by jtkech** [comment]
Then yes idem for `ContentLocalizationPart`, maybe update it also for alias where content definition is used in the map delegate, this is also the case for all sql content fields index, but thare are fields

I noticed that for autoroute, if you remove the part a record is added in the index when you re-publish the item, that's okay, but if you publish it again, the record is removed.

So if another running instance (not re-started) is only requested after the 2nd publish, it will not be in sync

So this record would need to be kept in the index, as we do for a removed item

I will fix it in #8442 

For now #8442 is a only a first pass, i will try these use cases tomorrow

**Comment by deanmarcussen** [comment]
> Then yes idem for `ContentLocalizationPart`, maybe update it also for alias where content definition is used in the map delegate, this is also the case for all sql content fields index, but thare are fields

Agreed. harder to do for fields, but possible.

> I noticed that for autoroute, if you remove the part a record is added in the index when you re-publish the item, that's okay, but if you publish it again, the record is removed.

I thought we decided to do that, but set the Path to null, so it is not picked up? But maybe I missed something there. Tomorrow ;)

**Comment by jtkech** [comment]
As a reminder, there is also the `PublishLaterPartIndexProvider` that also removes the related part in the map delegate

**Comment by jtkech** [comment]
> I thought we decided to do that, but set the Path to null, so it is not picked up? But maybe I missed something there. Tomorrow ;)

Yes,  it is read as a null path so the entry is removed, but when the item is published again the related index row is removed, so if another instance has not yet updated its entries (done on demand) it will not be in sync as it will not find this row.

Update: I'm closed to find a solution, needs some last tweaks
