### ISSUE TITLE
Deploy to Azure option please

### ISSUE THREAD

**Issue by atiq-cs** [OrchardCMS/OrchardCore#848]
Can we have a deploy to Azure option please? Can we also have a page containing instruction how to deploy it on Azure? Thanks.

**Comment by sebastienros** [comment]
We will do it. In the meantime please refer to the official azure sites services deployment as this is the same as a standard dotnet core deployment. From VS 2017 for instance just click publish. Or run `dotnet publish` from the web app folder and deploy the resulting files.

**Comment by atiq-cs** [comment]
I get following when try publishing using VS 2017,

<img width="316" alt="orchard2_azure_deploy_failed" src="https://user-images.githubusercontent.com/7858031/28202222-2ff192fe-6829-11e7-85fd-1f93a2cdfdd9.png">

It gives me following errors,

    Severity	Code	Description	Project	File	Line	Suppression State
    Error		The command "dotnet exec --runtimeconfig "D:\Sourcecodes\Web\netcore\Orchard2\src\Orchard.Cms.Web\bin\Release\netcoreapp1.1\Orchard.Cms.Web.runtimeconfig.json" --depsfile "D:\Sourcecodes\Web\netcore\Orchard2\src\Orchard.Cms.Web\bin\Release\netcoreapp1.1\Orchard.Cms.Web.deps.json" "C:\Users\atiqc\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.1\build\netcoreapp1.1\../../lib/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp1.1\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1.	Orchard.Cms.Web		0	

    Severity	Code	Description	Project	File	Line	Suppression State
    Error		The type or namespace name 'ILiquidManager' does not exist in the namespace 'Orchard.Liquid' (are you missing an assembly reference?)	Orchard.Cms.Web	D:\Sourcecodes\Web\netcore\Orchard2\src\Orchard.Cms.Web\Packages\Orchard.Liquid\Views\LiquidPart.Summary.cshtml	26	

Additional Info
Target Deployment: Microsoft Azure Shared Web App Service
An untouched clone of following revision,

    $ git rev-parse --short HEAD
    ad830c2d

**Comment by jtkech** [comment]
Regarding your trace, this is the views pre-compilation which fails on publishing. Note: there is no views precompilation on building.

Indeed in `LiquidPart.Summary.cshtml` there is `@inject Orchard.Liquid.ILiquidManager` which doesn't exist.


So, it's a bug, we will need to use some code as in ``LiquidPart.cshtml`` ...

Meanwhile, not under `Packages` folder but in the related project `OrchardCore.Modules\Orchard.Liquid`, just remove or change the extension of this view, this if you don't use any liquid parts.

**Comment by atiq-cs** [comment]
You meant `OrchardCore.Modules.Cms\Orchard.Liquid`. Right?

**Comment by atiq-cs** [comment]
I choose to remove that segment which led to successful publish/web deploy,

    @model Orchard.Liquid.ViewModels.LiquidPartViewModel
    -@inject Orchard.Liquid.ILiquidManager LiquidManager
    -
    -@{
    -    string liquid = Model.Liquid;
    -    var html = LiquidManager.GetTemplate(liquid).Render();
    -}
    -
    -@liquid.Substring(0, Math.Min(html.Length, 200))

**Comment by brogits** [comment]
Hi,

Does OrchardCore support deployment to Azure AppServices? It seems it can only get into setup page but after setup the application gets 500 error.

Thanks

**Comment by deanmarcussen** [comment]
@brogits OrchardCore runs well on Azure. 

Can you look for the cause of the 500 error in your `App_Data` logs and post here?

**Comment by brogits** [comment]
I got it to work now but it seems it not able to find the login theme. Is this a known issue?
![image](https://user-images.githubusercontent.com/4569499/57677352-354e4680-7659-11e9-8177-1a70ebba7165.png)

**Comment by deanmarcussen** [comment]
Not a known issue. Which recipe did you run on startup? Have a look in your browser console to see why it's not loading the css

**Comment by brogits** [comment]
hi dean,

I did use the blank recipe. The only error I can see is the missing favicon (404 not found). It let's me also login but it doesn't show any menu.

![image](https://user-images.githubusercontent.com/4569499/57745250-fd014380-76fe-11e9-9fa2-e3fca1440a77.png)

**Comment by brogits** [comment]
hi dean,

I did use the blank recipe. The only error I can see is the missing favicon (404 not found). It let's me also login but it doesn't show any menu.

![image](https://user-images.githubusercontent.com/4569499/57745281-1efac600-76ff-11e9-8f6f-10dd9bba49ff.png)

**Comment by brogits** [comment]
> @brogits OrchardCore runs well on Azure.
> 
> Can you look for the cause of the 500 error in your `App_Data` logs and post here?

There is no log found under App_Data folder

**Comment by brogits** [comment]
> @brogits OrchardCore runs well on Azure.
> 
> Can you look for the cause of the 500 error in your `App_Data` logs and post here?

Please find there the log fix. Note that i enable debug and information to capture all things. Please let me know if I'm missing something

[dwlog.txt](https://github.com/OrchardCMS/OrchardCore/files/3180811/dwlog.txt)

**Comment by Skrypt** [comment]
blank recipe is not setting any themes for the frontend or backend. That's to expect. What you want to use is SaaS recipe if you want to have a minalist frontend theme.

**Comment by brogits** [comment]
Any chance you can check this log. The theme is now loaded but it not redirecting me to the admin dashboard on login.
[dwlog2.txt](https://github.com/OrchardCMS/OrchardCore/files/3183392/dwlog2.txt)

**Comment by sebastienros** [comment]
Even with the blank recipe, the login would use the admin theme.

I looked at your logs. When accessing the home page it's hitting your own controller/action in the DiversityWorks.TheAdmin.Recipe module you apparently created. Then is redirects to the login page.

I see it correctly from my browser:

![image](https://user-images.githubusercontent.com/1165805/57797028-5f0d7900-76fe-11e9-8b11-e46b089ed1cd.png)

So what is the issue?

**Comment by brogits** [comment]
Thanks for the response @sebastienros .

On the setup we aare using our own created a recipe and we named it App.TheAdmin.Receipe and App.TheAdmin theme. Is it a bad idea? Will it be colliding with the default TheAdmin receipe and theme?

Right now the app only shows the Login Page and and Shows Https Error 500 on the /admin page. However this works fine in my local machine.


I've attached a screen shot of the log after login maybe someone has any idea?

![image](https://user-images.githubusercontent.com/4569499/57813956-99315600-77a4-11e9-8ec2-4b1ea6515625.png)

**Comment by deanmarcussen** [comment]
@brogits I don't know if the naming of your themes/modules will confuse Orchard, but it's confused me!

Many of us have OrchardCore sites running in azure.

I can't browse to that url in your logs anymore, so unless you've taken the site down, you have some other issue with your azure app configuration. 

I also see https errors at the top of your log, which suggest you need to look at the WebApp https redirection, and/or OrchardCore https setting I would disable that on the WebApp until you get it running.

Also suggest you look at https://github.com/OrchardCMS/OrchardCore/issues/3642

Lastly I'm not sure how you setup the site, was it with a recipe? which one? Possibly one of your own recipes. Are you sure the recipe is good? If you have a local database running with sqlite, perhaps just upload that to your `App_Data\Sites\Default` or if you're using SQL Server maybe try a bacpac.

**Comment by brogits** [comment]
Thanks all for the active response.
Our site is working now

It turns out we have to use <Project Sdk="Microsoft.NET.Sdk.Razor"> instead of <Project Sdk="Microsoft.NET.Sdk">

**Comment by sebastienros** [comment]
Thanks for the update. Yes, any module with Views needs this SDK.

@jtkech could we add some warning, or errors, to catch these mistakes? In this case if there is a View in the project.

**Comment by jtkech** [comment]
Done, i will do a PR.

![RazorSdk](https://user-images.githubusercontent.com/8586360/57888272-f58e8700-7831-11e9-8187-b7010cbb36cb.png)
