### ISSUE TITLE
Backup feature

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#8488]
Provide a way to backup a site.

Implemented in the modules.

Use deployment plan and steps? (Import/Export)

Configure target: Folder, Zip.

Allow to backup before deleting a tenant?

Discussed during the meeting.

**Comment by Skrypt** [comment]
The way I see this is that I would create database backups based on tenants settings (prefixed tables).
Then, I would create a generic interface with backup methods.

IDataManagement
- RemoveIndexes
- AddIndexes
- CloneTable(string prefix)
- RemoveTable(string prefix)

Then it could be used eventually to clone a tenant quickly without needing to use the import/export feature.
Then, each database provider could implement the interface for their own need.
Knowing that with SQLite we can simply copy the file then the CloneTable method could adapt to simply clone the db file.
Then, depending on each database provider we could need to remove the indexes before moving the data to a different database.

This would work only for the same database provider. So, if I'm cloning a tenant it will clone it only in the same database type.
Now, this would be quicker than using import/export but this is the only caveat of this method.

**Comment by stevetayloruk** [comment]
be able to duplicate a tenant to a new tenant would be nice.

**Comment by Piedone** [comment]
What's the use case here, exactly? You can export a site (if not fully, then we need to fix that) if you want to duplicate it and have a hosting-agnostic backup. Otherwise, you need to use the features of the hosting environment, like SQL Server's or Azure's backup features.
