### ISSUE TITLE
Tenant configuration in distributed environment long term goal?

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8490]
What is the long term goal for tenant config?  Is it not to have a single location that all instances point to like an sql database?
Is the plan to keep a json file on each instance?
What is the plan if you update json file on one instance?  Propagate the changes to the tenants.json files sitting on the other instances?

Seems like a single location is best?
@jtkech

**Comment by jtkech** [comment]
@JoshTango 

We already suport it through a shared database or azure blob storage
https://docs.orchardcore.net/en/dev/docs/reference/core/Shells/#database-shells-configuration-provider
https://docs.orchardcore.net/en/dev/docs/reference/core/Shells/#azure-shells-configuration-provider

**Comment by JoshTango** [comment]
Thank you very much.  Good to hear.

**Comment by JoshTango** [comment]
I pasted in my connection string to the appsettings.json file.
Now I get "Login failed for user"  error.
I was not getting any sql connection string errors when I pasted my connection string in during normal setup.
@jtkech

**Comment by JoshTango** [comment]
Actually since I am in azure i elected to configure the app service connection string and use that instead.
Problem went away
