### ISSUE TITLE
Azure database password pasted into appsettings.json file gives error

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8498]
I've paste din the password azure gave me into appsettings.json and it doesn't like it.
The password contains one single double quote but not a second one.
What do I do?
Are all passwords safe with json?

I'm hooking up the new shell database provider and thats how I came across this.

**Comment by Skrypt** [comment]
Have you tried escaping the double quote char? 

```
{ "something" : "123\"456" }
```

**Comment by JoshTango** [comment]
I just created a new password without weird characters and it worked
