### ISSUE TITLE
Recipes not listing any recipes

### ISSUE THREAD

**Issue by 4m-world** [OrchardCMS/OrchardCore#8527]
### Describe the bug
After upgrading to the latest nightly build 15814 and above the recipes page does not list any of the recipes despite the setup recipe used.

### Expected behaviour
List various recipes in the project

### Screenshots
![image](https://user-images.githubusercontent.com/343273/107141675-203c3f80-6933-11eb-967b-40e0c65c52fb.png)

**Comment by 4m-world** [comment]
I tried several builds and reverted to 1.0.0-rc2-15790 where recipes functionality works normally

**Comment by agriffard** [comment]
The `Setup` recipes are not listed anymore so by default there are no more recipes.

**Comment by 4m-world** [comment]
@agriffard so the only way to run setup recipes through the setup screen?

**Comment by agriffard** [comment]
> so the only way to run setup recipes through the setup screen?

You can also use the json or package import features.
