### ISSUE TITLE
Default tenant table PREFIX not working

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8532]
I added a table prefix setting like so to my appsettings.json:
{
  "OrchardCore": {
    "ConnectionString": "...",
    "DatabaseProvider": "SqlConnection"
  },
  "Default" : {
    "TablePrefix": "Default"
  }
}

and i started with a new database and setup my default tenant.  There were NO prefixes on the tables created for the default tenant.  I expected something like Default_Users.  But nothing.   Just Users table name.

**Comment by jtkech** [comment]
All need to be under the `OrchardCore` section

    {
        "OrchardCore": {
        "ConnectionString": "...",
        "DatabaseProvider": "SqlConnection",
        "Default" : {
            "TablePrefix": "Default"
        }
    }

**Comment by JoshTango** [comment]
Well then you need to fix the documentation here:

https://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/
