### ISSUE TITLE
Support for now() helper function in SQL Queries

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#8538]
Currently OrchardCore has few helper functions to play with dates, it would be good to also have **now()** function which could return current **DateTime** (utc).

I've adjusted YesSql Dialects: https://github.com/lampersky/yessql/commit/051a39ddf7ef4d1836cadad4074b6dc737e8ab01
And also have updated **SqlParser** and **SqlGrammar** to support functions without any arguments:
https://github.com/lampersky/OrchardCore/commit/6ce16c12eee05c03d50a0ba98cf36b52340c5060

/cc @sebastienros

**Comment by Skrypt** [comment]
You can also use Liquid in your SQL query for this.
See : https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#local

**Comment by lampersky** [comment]
Yes, I am aware of that. But I wanted to avoid passing unnecessary
(redundant) parameters. And this simple function do the trick.

**Comment by Skrypt** [comment]
Did you push a PR on YesSQL repo?

**Comment by Skrypt** [comment]
Related with #8126

**Comment by lampersky** [comment]
@Skrypt https://github.com/sebastienros/yessql/pull/345

**Comment by lampersky** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/8557
