### ISSUE TITLE
[Image] tag in HtmlBody doesn't render properly with @Html.Raw() 

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#8555]
### Describe the bug
[Image] tag in HtmlBody doesn't render properly with @Html.Raw() 

### To Reproduce
1. Add an image in the HtmlBody 
![image](https://user-images.githubusercontent.com/16193516/107401851-2f6de980-6afb-11eb-84a5-43a1c5b0562e.png)

2. Try to render the image in the View,
![image](https://user-images.githubusercontent.com/16193516/107401995-63490f00-6afb-11eb-9c29-97ec3b1c8164.png)

3. The image is not rended,  the data is there but [Image] tag not replaced with proper html `<img src=...>` tag
![image](https://user-images.githubusercontent.com/16193516/107402273-ad31f500-6afb-11eb-917e-dc31a2a736ed.png)

### Expected behavior
Image should be rended.

**Comment by MikeKry** [comment]
What OC version are you using?

**Comment by deanmarcussen** [comment]
If you are rendering the html manually, rather than using display management you will need to use the shortcode razor helper

```
var html = @Orchard.HtmlToShortcodesAsync(Model.MyContent.HtmlBodyPart.Html as string);
```

**Comment by orchardc** [comment]
Thanks @deanmarcussen .

I added: `@addTagHelper *, OrchardCore.Shortcodes ` in _ViewImports.cshtml

then in the view I have:

  <p>@Html.Raw(Orchard.HtmlToShortcodesAsync(Model.MyContent.HtmlBodyPart.Html as string))</p>

But the output is 
![image](https://user-images.githubusercontent.com/16193516/107494517-ce8bf300-6b86-11eb-9947-43810fd27059.png)

Anything I missed?

**Comment by deanmarcussen** [comment]
You might need to call `DisplayAsync` on it because it is `IHtmlContent`.

I need to have a look at that helper, it is badly named, and I'm not sure I should have returned `IHtmlContent`

Will investigate, but in the mean time `DisplayAsync(Orchard.HtmlToShortcodesAsync(Model.MyContent.HtmlBodyPart.Html as string))`

**Comment by orchardc** [comment]
```
                    <div>
                        @DisplayAsync(Orchard.HtmlToShortcodesAsync(Model.MyContent.HtmlBodyPart.Html as string))
                    </div>
```
@deanmarcussen 
It shows the same result...

![image](https://user-images.githubusercontent.com/16193516/107501435-49f1a280-6b8f-11eb-98da-f8fb5605ee31.png)

**Comment by deanmarcussen** [comment]
await

**Comment by orchardc** [comment]
Thanks @dalenewman , you are right. It works!

`<p>@Html.Raw(await Orchard.HtmlToShortcodesAsync(Model.MyContent.HtmlBodyPart.Html.ToString() as string))</p>`
