### ISSUE TITLE
Liquid : get utc now datetime

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8562]
### Is your feature request related to a problem? Please describe.
As reported here https://github.com/OrchardCMS/OrchardCore/discussions/8126
We can't get the UtcNow datetime from a liquid template.
We could get it by using the TimeZone filters to get the DateTime with it's offset and then remove the offset on the datetime.
Though, I think we should have a better way to handle this.

### Describe the solution you'd like
We should either be able to configure Fluid to return the UtcNow datetime when doing {{ 'now' }} and/or have a liquid filter that could return a Utc Datetime from a datetime that has a timezone. {{ datetime | date_utc }}.

**Comment by hishamco** [comment]
Why this shouldn't be done in Fluid?

**Comment by Skrypt** [comment]
Well I think we still need a filter to convert a DatetimeOffset to a Datetime UTC. Should this be added in Fluid directly, maybe. But then this would be a new FluidValue like {{ "now_utc" }}

**Comment by hishamco** [comment]
I may check the Shopify docs for this one

**Comment by hishamco** [comment]
Seems it's not there

**Comment by Skrypt** [comment]
I looked and it's not consistent in every places that {{ 'now' }} is used. Some places returns the current client Local Datetime. And we return the current system OS datetime. Both are not DatetimeOffsets. So, if you want to get a UTC Datetime you can't unless you use the {{ 'now' | local }} liquid filter. Which will render as 01/01/2021 12:00 -5:00 if you are in UTC-5. But this is awkward because you can't use this DatetimeOffset to return a proper UTC datetime with it afterward.

I created a draft PR quick https://github.com/OrchardCMS/OrchardCore/pull/8563

Feel free to review that one. I've not tested it at all yet. Seems like it should work to me though.

**Comment by sebastienros** [comment]
try `"now" | time_zone: "UTC"`

**Comment by Skrypt** [comment]
Does not work sadly 😢 
![image](https://user-images.githubusercontent.com/3228637/107684841-446c8900-6c71-11eb-86ab-eab818a9db00.png)
![image](https://user-images.githubusercontent.com/3228637/107684849-4898a680-6c71-11eb-9836-21a49afad096.png)

**Comment by Skrypt** [comment]
Ok, the filter are not currently working in the dev branch but if we change it to Fluid 1.0.0 it works.
{{ "now" | time_zone: "UTC" }}

**Comment by sebastienros** [comment]
I can't find a PR that updated fluid ;)

**Comment by Skrypt** [comment]
Ok will do
