### ISSUE TITLE
FlowPart: Removed widget content type definition  - fails to load

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8566]
I have found an interesting situation in OC.. 

Given: you have Content item with flow part and flowpart has some widgets (content types) inside.
When: you delete widget's content type definition
Then: you can't open content item again, throws error on resolving widget, because it is still stored in json, but not available in content part definition. 

There are some possible scenarios that I thought of as solution:
A) If this happens, we allow user to view this page, without widgets that are missing definition (possibly with some warning, like OC does with images)

that brings two possible ways:
1) if there is no definition, just delete the item - might cause problems if there is a development team and each person has his own contentdefinition in json. But in that case, I guess developers would be using DB storage for content definition.
2) instead of removing content type definition completely, we could put some mark into DB that it was deleted - so we would know for sure, that widget is supposed to be removed from content item.

B) Do not allow user to remove content parts at all, only soft delete. 
C) Remove content part from all content items on delete. 
D) leave it as is, but provide some meaningful error - "CustomWidget definition is missing, ..."

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/1014

**Comment by MikeKry** [comment]
@deanmarcussen 

I tried to search for this issue but did not found anything, sorry. Closing this one.
