### ISSUE TITLE
MediaFieldSettings issues when creating a media field via migrations 

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#8568]
### Describe the bug
When adding a media field to a part via migrations and applying settings doesn't appear to work. Sample of my code:

```
_contentDefinitionManager.AlterPartDefinition("MyPart", part => part
    .WithField("Image", field => field
        .OfType(nameof(MediaField))
        .WithPosition("7")
        .WithDisplayName("Image"))
        .WithSettings(new MediaFieldSettings
        {
            Required = false,
            Multiple = false,
            AllowAnchors = true,
            AllowMediaText = true
        }));
```
When I inspect the resulting settings in the admin UI not all the above settings have been applied:
<img width="562" alt="Screen Shot 2021-02-10 at 7 10 54 pm" src="https://user-images.githubusercontent.com/2867511/107488968-d1610500-6bd3-11eb-85ee-8f3038cd8f3e.png">

When I inspect the resulting content definition for the part, the MediaFieldSettings are not applied in the correct place - see below. I have applied settings to other fields and they are applied to the Field in the definition.

<img width="426" alt="Screen Shot 2021-02-10 at 7 15 52 pm" src="https://user-images.githubusercontent.com/2867511/107489624-914e5200-6bd4-11eb-9243-bafe4a2fa5b8.png">

**Comment by jtkech** [comment]
@scleaver 


        [Obsolete("Use WithSettings<T>. This will be removed in a future version.")]
        public ContentPartFieldDefinitionBuilder WithSetting(string name, string value)
        {
            _settings[name] = value;
            return this;
        }

**Comment by scleaver** [comment]
@jtkech - weird, I have my project setup to warn me about obseletes.

But isn't my code above using `.WithSettings<T>` when I go `.WithSettings(new MediaFieldSettings...)`

**Comment by jtkech** [comment]
@scleaver 

    WithSettings<T>(T settings) => here WithSettings<MediaField>(yourMediaFieldSettings)

**Comment by scleaver** [comment]
Oh.... Ok I will test. Thanks for the pointer.

I am going have to update a lot of code :)

**Comment by jtkech** [comment]
Yes, but as i understand it, so try it first before changing all of them ;)

**Comment by scleaver** [comment]
@jtkech Is it possible that rather than it's meant to be WithSettings<TextFieldSettings> rather than WithSettings<TextField>

```
.WithSettings<TextFieldSettings>(new TextFieldSettings
{
    Hint = "My hint."
}))
```

**Comment by deanmarcussen** [comment]
```
                .WithField("TwitterImage", field => field
                    .OfType("MediaField")
                    .WithDisplayName("Twitter image")
                    .WithSettings(new MediaFieldSettings { Multiple = false }))
```

this works fine for me (I think) - that's the same as your signature above. `WithSettings<TextFieldSettings>(new ...`

```
        {
          "FieldName": "MediaField",
          "Name": "TwitterImage",
          "Settings": {
            "ContentPartFieldSettings": {
              "DisplayName": "Twitter image"
            },
            "MediaFieldSettings": {
              "Multiple": false
            }
          }
        }
```

**Comment by scleaver** [comment]
@deanmarcussen so your code above is basically the same as my original code at the start of this post so not sure why my is resulting in the MediaField Settings landing on the contentpart ather than the field in the resulting content definition.

**Comment by jtkech** [comment]
@scleaver 

In your first json what is the `"Name": "???"` before your `ContentPartFieldDefinitionRecords` property? Normally it is `"Name": "MyPart"` but you also have it after. Do you have another image field named `Image` but directly under your content type (so with a part whose name is the content type name)?

Also, there is this migration that always run

        // This migration does not need to run on new installations, but because there is no
        // initial migration record, there is no way to shortcut the Create migration.
        public int Create()
        {
            _contentDefinitionManager.MigrateFieldSettings<MediaField, MediaFieldSettings>();

Maybe something went wrong if it run before / after. Hmm, maybe there are both creating a part with the same name

**Comment by scleaver** [comment]
Closing issue as this was a problem in my code sorry
