### ISSUE TITLE
[Workflows] can't use {{Site.BaseUrl}} in HttpRequestTask Url field

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#8573]
### Describe the bug
When using liquid syntax with Url field in Http Request Task, I can't get **Site.BaseUrl** value.

### To Reproduce
1. Create workflow, add some initial event and add Http Request Task,
2. Try to perform request to url with base url from **{{Site.BaseUrl}}**,
3. Check Fault Message in the latest Workflow Instance.

### Expected behavior
**Site.BaseUrl** should be accessible from URL field in Http Request Task.

### Screenshots
**BaseUrl is set as follows:**
![image](https://user-images.githubusercontent.com/6403130/107543501-96f26a80-6bc9-11eb-84d3-ca9cf4672c3f.png)

**Url inside Http Request Task has value:**
![image](https://user-images.githubusercontent.com/6403130/107542674-b6d55e80-6bc8-11eb-8798-ba05048ebf8e.png)

**Workflow instance fault message:**

> An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

![image](https://user-images.githubusercontent.com/6403130/107542928-fef48100-6bc8-11eb-9d67-1847656bbd39.png)

Here is my test app, where you can also repro this issue.
https://try.orchardcore.net/nlf5q0ag/Admin
(PM me for password if needed)

/cc @sfmskywalker

**Comment by jtkech** [comment]
@lampersky 

    {{ Site.BaseUrl | raw }}
