### ISSUE TITLE
HOST Settings

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8574]
I would like a section in the appsettings.json called for example HOST.
This section would contain the settings for what you currently call the default tenant.
I would like to for example introduce new terminology called INSTANCES.
Some Orchard Core instances behave like tenants and some behave like a host.
Maybe in the future others could behave like an identity server.
I don't think you should call the default tenant a tenant because it is not a tenant.

**Comment by JoshTango** [comment]
So I guess it would be like this:

OrchardCore
----->HOST
---------->TablePrefix=Default
----->Tenants
---------->Tenant1
---------->Tenant2

**Comment by Skrypt** [comment]
Well the default tenant should be simply named then "Host" on your part.
But yes, we assume that one of these tenants and most likely the default one will be the one that will be used for doing things like adding other tenants, using OpenID server.

By the way each tenants are apps within a more global "host" app too.

**Comment by Piedone** [comment]
I don't really understand the feature request. Are you talking about only renaming the Default tenant to "HOST"? Or would you like multiple tenants that behave similarly to the Default one with other tenants "under" them?

**Comment by JoshTango** [comment]
no

**Comment by Piedone** [comment]
![image](https://user-images.githubusercontent.com/1976647/107773124-7d722f80-6d3d-11eb-9236-15d3cc10fd97.png)

**Comment by Skrypt** [comment]
Let's not get more confused here. These are all ShellSettings stored in the IRunningShellTable. So, yes they are all tenants. So the default tenant is a tenant. More confusion is that they are named Shells in the source code 😉 

@piedone I let you decide what we should do. 🐰

**Comment by Piedone** [comment]
I'll let @JoshTango present their idea or close this and https://github.com/OrchardCMS/OrchardCore/issues/8558 if they decide not to :).

**Comment by JoshTango** [comment]
Well tenant seems a low level entity.  Liek an instance.
I think the appsettings should have a section for which tenant is the master tenant or the one in control

**Comment by JoshTango** [comment]
If u dont agree you don't have to

**Comment by Piedone** [comment]
OK, so we're talking about being able to pretty much appoint the tenant that would take the Default tenant's place?

**Comment by JoshTango** [comment]
See that's part of the problem.  I don't believe it is correct to call it a tenant.  I believe that is incorrect.

**Comment by Piedone** [comment]
Sure, that's debatable. However, tenant and shell are different things and on this level tenant is I think the correct one, then you create shells out of tenants (we've discussed this in more detail under one issue, I welcome you to search for it).

However, I still don't understand what this feature request is about because you're not answering my questions. If you don't want to then no problem but then please close the issue.

**Comment by JoshTango** [comment]
is shell the tenant in charge?

**Comment by JoshTango** [comment]
well regardless i think the master/shell/whatever should be represented in the appsettings.
