### ISSUE TITLE
Placement module not being applied to parts.

### ISSUE THREAD

**Issue by willnationsdev** [OrchardCMS/OrchardCore#8576]
### Describe the bug
When creating a placement rule for a part, the part is not reacting to the placement rule.

### To Reproduce
1. Run Blog recipe.
2. Enable Placements feature.
3. Create a "MyPart" ContentPart definition.
4. Create a "MyPage" ContentType definition with Title, Common, MyPage, Form, HtmlBody, MyPart, Alias, Autoroute, Preview parts (at least, that's the kind of thing I'm actually working with).
5. Create a "MyPage". Add some text to its HtmlBody part.
6. Go to the Edit for the MyPart part in the MyPage content type definition.
7. Generate a template for MyPart part in a MyPage type in details views. Add some text to it.
8. Generate a placement rule for MyPart part in a MyPage type in details views. Set "place" to "-" (to hide it).
9. View the MyPage content item you created earlier. The text from the MyPart template will still be visible.

### Expected behavior
templates defined by the Templates admin respond to Placement rules defined for them.

What I'm seeing:
```
title
TEST TEMPLATE TEXT
        field             input
        field             input
        field             input
        field             input
```

What I expected:
```
title
        field             input
        field             input
        field             input
        field             input
```

Furthermore, since the MyPart part is later in the sequence of parts, I would have expected it to show up after the form / HtmlBody anyway. But it doesn't. It shows up at the top, under the title.

**Comment by Skrypt** [comment]
Can repro.

**Comment by Skrypt** [comment]
Ok so, when you use a Liquid Template for your MyPart part then it removes the ability to use the natural shape placement. But the shape placement works if you are not using a MyPart template from my tests. Somehow, if you are using a template you should then provide what you want to display from that template with conditions made with Liquid code.

**Comment by willnationsdev** [comment]
@Skrypt In my case, the ultimate goal was just to reposition the MyPart visually so that it would show up after the form/htmlbody parts, but it always rendered at the top. Then I tried using the Placements API, but that didn't work either. Seems there are a lot of issues or lacking of documentation about the feature(s) involved, e.g. reordering the parts didn't work as expected the change the rendering order. But beyond that, you can't even "force" the rendering position using the placement system.

**Comment by willnationsdev** [comment]
> Ok so, when you use a Liquid Template for your MyPart part then it removes the ability to use the natural shape placement.

Is this the reason my part is rendering at the top all the time, rather than in the appropriate part location as it is positioned in the ContentType edit page? It's ignoring the position data defined and is just going wherever it wants?

**Comment by Skrypt** [comment]
I need to test more. There is definitely something not right. Maybe mixing templates with placements here becomes an issue.

**Comment by willnationsdev** [comment]
@Skrypt Well, we only added the placements module in an attempt to fix the MyPart part not repositioning based on its position in the list of Parts for the ContentType. So, perhaps an issue with the Template-created shapes not rendering properly?

**Comment by Skrypt** [comment]
Normally the part orders are kept when we are using BuildEditorAsync(). Here we are doing a BuildDisplayAsync() "I think". But that's when we use a shape template "Razor". So, here since we are using a Liquid template the Shape is passed to the Liquid template and the placement is not applied. I will try to debug this one today and see what we can do.

**Comment by ns8482e** [comment]
@willnationsdev  @Skrypt It seems `Generate a placement rule` menu is generating incorrect shape type. Here `MyType__MyPart` is an alternate not a shape type. The actual shape type is `ContentPart`

Create Placement for `ContentPart` shape type with following and it will apply the placement rule as expected.

![image](https://user-images.githubusercontent.com/23270244/108719956-d8e2b100-74e5-11eb-9115-c9e12f276252.png)

**Comment by Skrypt** [comment]
@ns8482e I trust you on that one. I don't have time to test it. We're we not having a pending issue about that one?
