### ISSUE TITLE
Sqlite: Hide connectionstring

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#858]
In Setup and tenant creation, hide the connection string if not needed.

**Comment by azGreg** [comment]
Hiding the connection string is straight forward. But I have been having an issue taking advantage of
    <resources type="Footer" />
in TheAdmin/Views/Layout.cshtml. I see in other modules that it looks like
    <resources type="FootScript" />
I couldn't get that to work either.

Even though the script works, it is rendered immediately after the form. I was trying to put it at the end of body.

**Comment by sebastienros** [comment]
I think it's already the case right?

**Comment by agriffard** [comment]
In the root setup, yes but it is not well initialized if you create a tenant with a sqLite database and then go to the setup page.
The type of database provider is hidden but not the connection string, as it should be when sqLite is selected.
![image](https://user-images.githubusercontent.com/703248/31272008-b825f488-aa89-11e7-819e-a9f2e2d3d005.png)

May be we can display the Database Provider as a label instead of hiding it here:
```
@if (Model.DatabaseProviderPreset)
        {
            <input asp-for="DatabaseProvider" type="hidden" />
            <span asp-validation-for="DatabaseProvider" class="text-danger"></span>
        }
```

**Comment by agriffard** [comment]
Sorry, I intented to make a PR but I forgot to branch my work.
Please confirm I made the correct changes in the setup to fix this issue.

**Comment by sebastienros** [comment]
If you forget to branch, just `git reset --soft dev` which will point to the dev branch, but leave your commits as is, then you can just create a branch and commit again.
