### ISSUE TITLE
Override view

### ISSUE THREAD

**Issue by luis3199correia** [OrchardCMS/OrchardCore#8582]
### Describe the bug
I've created a theme to override some views, like Create/Edit (Contents), and now I want to change the "Clone" button name, and for that, I've tried to override the "Contents-Button-Actions.SummaryAdmin.cshtml" file, and the file I added is not being used.

### Screenshots
File location:
![image](https://user-images.githubusercontent.com/32116636/107663913-cd8cbb80-6c83-11eb-962f-648b31b26fcf.png)

**Comment by Skrypt** [comment]
It need to be in the OrchardCore.Contents folder "I think".

**Comment by luis3199correia** [comment]
> It need to be in the OrchardCore.Contents folder "I think".
Is already inside OrchardCore.Contents folder.

**Comment by Skrypt** [comment]
The view name should be ContentsButtonActions_SummaryAdmin.cshtml

**Comment by luis3199correia** [comment]
> The view name should be ContentsButtonActions_SummaryAdmin.cshtml

Worked. I used the name that is found in the screnshot, because it is the name of the view in the source code.

**Comment by luis3199correia** [comment]
After overriding this view, the Delete option stop working, without changing the view.
I get a "The page could not be found." after trying to Delete a content item.

**Comment by Skrypt** [comment]
You probably need to update your custom admin theme with the latest changes.

**Comment by luis3199correia** [comment]
After updating the packages, as you suggested, this happened
![image](https://user-images.githubusercontent.com/32116636/107962784-4733ea80-6f9f-11eb-850e-c46d11edf624.png)

I've created a theme based on "TheAdmin" theme, and override this views,
![image](https://user-images.githubusercontent.com/32116636/107963000-86623b80-6f9f-11eb-88ea-de12e12844cd.png)

**Comment by luis3199correia** [comment]
> You probably need to update your custom admin theme with the latest changes.
> Every ContentType_SummaryAdmin views might be affected by the latest changes we made in the Admin UI.

`<div class="actions-menu dropdown-menu dropdown-menu-right show" x-placement="top-end"
	style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-123px, -265px, 0px);">

	<a data-url-af="UnsafeUrl" class="dropdown-item btn-sm"
		href="/Contents/ContentItems/4ekvkjf6crad52nyayvxd7k14z/Publish?returnUrl=%2FContents%2FContentItems">Publish
		Draft</a>
	<div class="dropdown-divider"></div>

	<a data-url-af="UnsafeUrl RemoveUrl" data-title="Discard Draft"
		data-message="Are you sure you want to discard this draft?" data-ok-text="Yes" data-cancel-text="No"
		data-ok-class="btn-primary" class="dropdown-item btn-sm"
		href="/Contents/ContentItems/4ekvkjf6crad52nyayvxd7k14z/DiscardDraft?returnUrl=%2FContents%2FContentItems">Discard
		Draft</a>

	<a remove-for="template" class="dropdown-item btn-sm" data-url-af="RemoveUrl UnsafeUrl" data-title="Delete"
		data-message="Are you sure you want to delete this content item?" data-ok-text="Ok" data-cancel-text="Cancel"
		href="/Contents/ContentItems?returnUrl=%2FContents%2FContentItems">Delete</a>

	<a data-url-af="UnsafeUrl" class="dropdown-item btn-sm"
		href="/Contents/ContentItems/4ekvkjf6crad52nyayvxd7k14z/Clone?returnUrl=%2FContents%2FContentItems">New
		Version</a>

	<div class="dropdown-divider"></div>
	<a class="dropdown-item btn btn-primary btn-sm"
		href="/Download/Display/4ekvkjf6crad52nyayvxd7k14z?returnUrl=%2FContents%2FContentItems&amp;latest=true">View
		Draft as JSON</a>
	<a id="4a280e1c08e74b9180e33a72e3476b4c" class="dropdown-item btn btn-primary btn-sm" data-url-af="UnsafeUrl"
		href="/Download/Download/4ekvkjf6crad52nyayvxd7k14z?latest=True">Download Draft as JSON</a>

	<div class="dropdown-divider"></div>
	<button class="dropdown-item btn-sm" type="button" data-toggle="modal"
		data-target="#modalAddToDeploymentPlanActionDeploymentPlan"
		data-content-item-id="4ekvkjf6crad52nyayvxd7k14z">Add to Deployment Plan</button>

</div>`

This is the html rendered after overriding the view.

**Comment by luis3199correia** [comment]
[Solution](https://github.com/OrchardCMS/OrchardCore/issues/8661)
