### ISSUE TITLE
Author, Owner and UserId inconsistencies

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#8583]
On the ContentsHandler, the owner is being set to the UserId and the Author to the UserName.
Is this the intended behaviour?
https://github.com/OrchardCMS/OrchardCore/blob/807ad0286cebde9ee45206102cb56ca9c4874912/src/OrchardCore/OrchardCore.ContentManagement/Handlers/ContentsHandler.cs#L31-L35

If I remember correctly, the reason to use the UserId is because it doesn't change, unlike the UserName and Email.

- I was creating a ContentItem via code where I assigned the Author to the UserId, but because I didn't set the Owner, it replaced it with the UserName.
I would suggest there sould be a sepparate validation for the Author.

- Also here, it doens't verify if the Author/Owner is already set. 
Although, I tested using `UpdateAsync`, and it still keeps the UserId, which is good.
https://github.com/OrchardCMS/OrchardCore/blob/807ad0286cebde9ee45206102cb56ca9c4874912/src/OrchardCore/OrchardCore.ContentManagement/Handlers/ContentsHandler.cs#L40-L50

I can create a PR for this, but would like to hear your thoughts first.
If we change the Author to UserId, will it require a migration?

**Comment by Skrypt** [comment]
The migration we did previously was to assign the current Users username to the UserId. So don't be mistaken by this migration.
We did this for backward compatibility and to avoid needing to change the Owner of every content items. So, if you upgraded to the latest OC bits, when you create a new user ; a UUID will be generated as the UserId for new users. This can be confusing because if you look at the UserIndex table you might see old usernames in the UserId column. This is probably the confusion that is happening to you right now.

One way to avoid this confusion is to use a SQL Script to migrate all your data. I made one for myself but it works only for SQL Server ; let me know if you need it.

**Comment by mariojsnunes** [comment]
Hmm I don't think that's it.
I tested this on a clean install.

My question is why in that referenced piece of code, the Owner is being set to the UserId and the Author to the Username.

And the CreatingAsync event is setting the Author to Username even if it already has info.

**Comment by mariojsnunes** [comment]
> assign the current Users username to the UserId.
You set the old Users Usernames to their new UserID?
What about when you create new users via the Admin UI? The Username is not set to the UserId, is it?
Sorry I'm still a bit confused ahah

**Comment by deanmarcussen** [comment]
The Author was kept as a DisplayName property, i.e. users name, and is intended to change to the most recent user that edited the content item.

The Owner is set once, to the creator of the content item. It can only be changed with the owner part (an editor part)

Does that answer the question?

**Comment by mariojsnunes** [comment]
Yep that answers it, thanks.
Closing as it's the intended behaviour.

**Comment by hungdoan-groove** [comment]
@deanmarcussen can I ask some question around the design of the DocumentId ?. 
- Previously in the RC version the `ClaimTypes.NameIdentifier` is set to DocumentId (OrchardCore.Users.Models.User.Id), which is a number

However, I got a big trouble in the v1.0 as I'm using the DocumentId as the FK in my custom table. 
and in v1.0 there is a breaking change to change `ClaimTypes.NameIdentifier`  to string and going to generating a UUID for it ?. 

**My question is:** 
1/ Why don't we use the DocumentId as we did previously ?. 
2/ If I use DocumentId as a FK for my custom integration. Is that safe to do so ?, Can DocumentId be changed some how ?.

**Comment by hung-doan** [comment]
@deanmarcussen can I ask some question around the design of the DocumentId ?. 
- Previously in the RC version the `ClaimTypes.NameIdentifier` is set to DocumentId (OrchardCore.Users.Models.User.Id), which is a number

However, I got a big trouble in the v1.0 as I'm using the DocumentId as the FK in my custom table. 
and in v1.0 there is a breaking change to change `ClaimTypes.NameIdentifier`  to string and going to generating a UUID for it ?. 

**My question is:** 
1/ Why don't we use the DocumentId as we did previously ?. 
2/ If I use DocumentId as a FK for my custom integration. Is that safe to do so ?, Can DocumentId be changed some how ?.
