### ISSUE TITLE
How to try the latest Orchard2 in a docker container?

### ISSUE THREAD

**Issue by sanyo-ok** [OrchardCMS/OrchardCore#859]
Please let me know image name on the hub.docker.com

If it is not present there yet, can you please publish it like:
https://hub.docker.com/r/microsoft/powershell/

It would be more attractive for a first time to try it in a docker spending only 5-10 mins to install an look at it and then an interested party can already install full stack on his own linux installation.

**Comment by alexbocharov** [comment]
I think in the near future

**Comment by Jetski5822** [comment]
Great idea!!! When we release, we should look to release a docker image too. +1 @sanyo-ok

**Comment by alexbocharov** [comment]
I think I'll do it.

**Comment by sanyo-ok** [comment]
Dear developers, please let me know an estimated 0date of release supporting Core V2

**Comment by alexbocharov** [comment]
You can see the branch `dev`

**Comment by sebastienros** [comment]
https://hub.docker.com/u/orchardproject/
