### ISSUE TITLE
Blog Bug when adding type page, it is missing body

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8592]
I downloaded the latest and made a tenant with the Blog theme.
I added a page type.
There was a textbox to enter my title.
There was NO area to enter my body of the page. 
The body is missing so there is no way to add content.
@deanmarcussen

**Comment by jtkech** [comment]
@JoshTango 

With the blog recipe, the Page content type has no body part, it has a flow part that allows you to add widgets, e.g. raw html, paragraph, liquid, and image widgets.

**Comment by JoshTango** [comment]
It was very hard to see the flow part.  The opacity is so low.
This needs to be more visible.

@jtkech

**Comment by jtkech** [comment]
@JoshTango 

Yes i agree, not visible enough, i didn't saw it myself at some point ;)

Feel free to open a separate issue for this
