### ISSUE TITLE
using Parlot in shortcodes ?

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#8598]
This line is using Parlot :
https://github.com/OrchardCMS/OrchardCore/blob/71fc4a1f120de29eec4f93bda471eb8e16b5d600/src/OrchardCore.Modules/OrchardCore.Shortcodes/Controllers/AdminController.cs#L23

and its breaking my build.
Has this library been included ?

**Comment by deanmarcussen** [comment]
perhaps try a `dotnet clean` and `dotnet restore` 

the `shortcodes` library should be managing the reference to `Parlot` - we haven't needed to take a direct reference to it yet.

**Comment by giannik** [comment]
Thank @deanmarcussen that did it.
