### ISSUE TITLE
[Lucene] Applying a boost doesn't seem to have any effect

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#8600]
I've tried two ways:
1. First is from this https://github.com/OrchardCMS/OrchardCore/issues/4825#issuecomment-554665911.

```
{
  "from": 0,
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "TitlePart": "test*",
            "boost": 2
          }
        },
        {
          "wildcard": {
            "Article.Body": "test*"
          }
        }
      ]
    }
  },
  "size": 10
}
```
It returns the same order as when there is no boost property. Some articles without "test" in the title appear first.

2. I was also trying to use with the simpleQueryString.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html
But it doensn't work, as if I didn't include the "TitlePart" field.

```
{
  "from": 0,
  "query": {
    "bool": {
      "must": [
        {
          "simple_query_string": {
            "analyze_wildcard": true,
            "fields": [
              "TitlePart^2",
              "Article.Body"
            ],
            "query": "(test) (test*)"
          }
        }
      ]
    }
  },
  "size": 10
}
```

With:
```
"fields": [
    "TitlePart^2",
    "Article.Body"
  ]
```
Returns only results of Article.Body

With:
```
"fields": [
    "TitlePart^2"
  ]
```
Returns no results.

With:
```
"fields": [
    "TitlePart"
  ]
```
Returns results.

Am I doing something wrong?
If it's a bug or not implemented I can help.

**Comment by Skrypt** [comment]
Have you tried different higher values in the Boost param?

**Comment by mariojsnunes** [comment]
> Have you tried different higher values in the Boost param?

Yep, 2, 20 or nothing is the same

**Comment by Skrypt** [comment]
I think your issue is that when you need to pass a boost the Wildcard Query part needs to be constructed like this.

```json
{
  "from": 0,
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "TitlePart": { "value": "test*", "boost": 5 }
          }
        },
        {
          "wildcard": {
            "Article.Body": "test*"
          }
        }
      ]
    }
  },
  "size": 10
}
```

**Comment by mariojsnunes** [comment]
Hmm it didn't change the results order either.
Were you able get it working?

Anyway, I'm also interested in the 2nd syntax:
```
{
    "simple_query_string": {
      "analyze_wildcard": true,
      "fields": [
        "TitlePart^2",
        "Article.Body"
      ],
      "query": "test*"
    }
  }
```
I saw on this issue https://github.com/OrchardCMS/OrchardCore/issues/6946 that the "multi-match" query wasn't implemented. could this be a similar situation?
Does this query go through some sort of OC validation/convertion before hitting lucene?

**Comment by Skrypt** [comment]
I will try it and report what I find here. It should work.

**Comment by Skrypt** [comment]
![screencapture-localhost-5001-Admin-Lucene-Query-2021-02-15-15_02_34](https://user-images.githubusercontent.com/3228637/107988870-e9070780-6f9e-11eb-9a0a-6b81e4bee583.png)

```JSON
{
  "from": 0, "size": 10,
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "TitlePart": { "value": "test*", "boost": 5 }
          }
        },
        {
          "wildcard": {
            "Article.HtmlBodyPart": "test*"
          }
        }
      ]
    }
  }  
}
```

**Comment by Skrypt** [comment]
The second `simple_query_string` query you mentioned. Here are my results : 

```json
{
  "from": 0, "size": 10,
  "query": {
    "simple_query_string": {
      "analyze_wildcard": true,
      "fields": [
        "TitlePart",
        "HtmlBodyPart"
      ],
      "query": "test*"
    }
  }
}
```

![screencapture-localhost-5001-Admin-Lucene-Query-2021-02-15-15_21_37](https://user-images.githubusercontent.com/3228637/107990023-819e8700-6fa1-11eb-8b56-6a6250914d9d.png)

**Comment by Skrypt** [comment]
So here I think the Queries are parsed properly. There is definitely something going wrong.

**Comment by mariojsnunes** [comment]
```
{
  "from": 0, "size": 10,
  "query": {
    "simple_query_string": {
      "analyze_wildcard": true,
      "fields": [
        "TitlePart^2"
      ],
      "query": "test*"
    }
  }
}
```

Have you tried this? (only "TitlePart^2"), for me it didn't return any results as mentioned on the first comment.

Please let me know if I can help in any way.

**Comment by Skrypt** [comment]
Yes, I don't think the boost is taken into consideration that way. It's something missing in our implementation.

**Comment by Skrypt** [comment]
Fixed the second one. The first one seems more tricky as I thought it was already working.

**Comment by Skrypt** [comment]
Fixed the WildcardQueryProvider.

**Comment by Skrypt** [comment]
> Please let me know if I can help in any way.

Please test #8602 PR

**Comment by mariojsnunes** [comment]
Yep I can confirm it solved both of them.
Great work!

**Comment by hishamco** [comment]
Reopening this, it should be closed once the PR is merged, @Skrypt you could merge while @mariojsnunes confirms that works for both issues

**Comment by Skrypt** [comment]
I still need to make some other verifications ; but I should be merging it today.
