### ISSUE TITLE
Adding Widget without layer breaks site

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#8608]
### Adding Widget without layer breaks site
There is no restriction in admin from creating a widget not assigned to any layer.
Adding such widget breaks the site :
![Capture d’écran 2021-02-16 151630](https://user-images.githubusercontent.com/7600804/108074882-fa691600-7069-11eb-9da3-a34f39c3e2eb.png)

### To Reproduce
1. Setup a new CMS instance with "Blank" template
2. Go to Content > Content Definition > Content Types and create a widget (eg. Html widget)
3. Go to Design > Settings > Zones and add a Zone (eg. Footer)
4. Go to Design > Widgets and click "Add Widget"
(note the message "Please create a layer before adding Widgets" but it's still possible to create one)
5. Fill the form and Publish your widget
6. Open your site : its broken

### Expected behavior
- Don't allow to publish widget without layer
- Don't throw if layer is missing

**Comment by Skrypt** [comment]
AH! That's why we did not allow having no zones at all in the Zone Layer settings. And we allowed it recenlty in a PR. This is the NRE that I was talking about that you found.
