### ISSUE TITLE
Docker builds are currently failing

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8609]
### Describe the bug

The docker builds have been failing on push since last week.

```
Successfully tagged ***/orchardcore-cms-linux:dev
Using default tag: latest
The push refers to repository [docker.io/***/orchardcore-cms-linux]
tag does not exist: ***/orchardcore-cms-linux:latest
```

https://github.com/OrchardCMS/OrchardCore/runs/1910923050?check_suite_focus=true

/cc @sebastienros

**Comment by agriffard** [comment]
I tried to add a `docker login` like for the working windows docker but still an error.

https://github.com/OrchardCMS/OrchardCore/runs/1931238791?check_suite_focus=true

I don't know what it says; `Using default tag: latest` while we are pushing to dev.

**Comment by agriffard** [comment]
Last build that managed to push the linux docker: https://github.com/OrchardCMS/OrchardCore/runs/1877143638?check_suite_focus=true

**Comment by jtkech** [comment]
Fixed
