### ISSUE TITLE
Add DocumentId to AdminDashboard Index

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8611]
Because it snuck in without one @jtkech

**Comment by jtkech** [comment]
@deanmarcussen 

Through another issue, i saw that a full non clustered index, so including `DocumentId`, may also prevent some dead lock on sqlite, so, even if there will never be a lot of dashboard widgets, yes good to add here a light index (few columns).

I agree

**Comment by deanmarcussen** [comment]
Yes, interesting about the deadlock - saw that issue as well.

I assume it is because without an index, it is doing a table scan just for the join, which locks the table, whereas when it is index scanning, no need to lock. (guessing here, but interesting).

If I have time I will add it today. There is another issue that just came up on gitter as well, so will wait for that pr.

**Comment by jtkech** [comment]
> I assume it is because without an index, it is doing a table scan just for the join, which locks the table, whereas when it is index scanning, no need to lock

I assume too, but i think so ;)

> so will wait for that pr.

No problem
