### ISSUE TITLE
Document Image Shortcode

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8612]
Because when we went looking for the documentation on `[image]`, there was nothing to be found

**Comment by NogginBox** [comment]
Looking at the source code shows these parameters are supported:

- width
- height
- mode
- quality
- format
- class
- alt

Are media profiles supported?

**Comment by deanmarcussen** [comment]
Looks like it what you have written would make a great addition to the documentation.

Re media profiles, it’s not currently supported, but would be a good pr to add that support.

re custom sizes. They need a hash (security) to be supported, and this is something we should also add to the shortcode

re pad modes. I think so, we use imagesharp for that and I’ve also struggled to find exact docs, but what you have lgtm

**Comment by NogginBox** [comment]
I've got some time next month put aside for Hactober so I might work on both this and trying to add profiles to the shortcode. Could you assign me this issue.

**Comment by NogginBox** [comment]
In progress.
Adding to this section in docs:
https://docs.orchardcore.net/en/dev/docs/reference/modules/Shortcodes/#available-shortcodes

**Comment by NogginBox** [comment]
@deanmarcussen I've submitted a PR to add this to docs. Let me know what you think and if you have any suggested tweaks.

I'm going to look at adding profile support to the shortcode now. Is there an issue for this, or should I create one?

**Comment by deanmarcussen** [comment]
@NogginBox looks good, nothing wrong with a free t-shirt :)

I don't think we are tracking an issue for profile support, so yes please pop in an issue, and we can assign you to it.

> re custom sizes. They need a hash (security) to be supported, and this is something we should also add to the shortcode

We should do this too, it will not be hard, and it can be done automatically based on the options see : https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.Media/Razor/OrchardRazorHelperExtensions.cs#L84-L94
