### ISSUE TITLE
Lucene Query Unit Tests

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8613]
We need to add some Lucene Query unit tests and/or functional tests.
Currently we have none at all. Lucene.NET and ElasticSearch specs changes over time and we have nothing to test these at all.
We should at least create some basic unit tests to assert that the basic Lucene QueryProviders works adequately.

/cc @mariojsnunes

**Comment by mariojsnunes** [comment]
Yeah I can start working on this soon.
What do you think of having a recipe to create content items for the tests?

**Comment by Skrypt** [comment]
Yeah maybe a copy of the SaaS recipe to get only minimal features enabled. And then some recipes.

Here some of my latest Queries when debugging : 
[Queries.zip](https://github.com/OrchardCMS/OrchardCore/files/6022876/Queries.zip)

**Comment by hishamco** [comment]
@Skrypt is this totally done by the PR #8775?

**Comment by Skrypt** [comment]
We can close and open a new issue to states that we need to add more unit test.
