### ISSUE TITLE
Task/Event hide in left hand side

### ISSUE THREAD

**Issue by hoangtamnguyen** [OrchardCMS/OrchardCore#8618]
### Describe the bug
After save workflow some task/event cannot see because it hide in left hand side, I attached imaged for detail

### Screenshots

![image](https://user-images.githubusercontent.com/4139252/108190627-c7478500-7144-11eb-8260-917cf1ef3211.png)

**Comment by lampersky** [comment]
duplicate https://github.com/OrchardCMS/OrchardCore/issues/8096
