### ISSUE TITLE
Tabs do not work without Contents module enabled

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8619]
### Describe the bug

It's common to use Tabs to arrange custom properties on the Users View.

The `TabContainer` and related views are in the `Contents` module.

When the `Contents` module is disabled, these views are not discovered, and users settings cannot make use of tabs.

I am currently working on a project which is more about Users, and custom entities, than Content Items, and hence have the `Contents` module disabled, because I do not want to expose unwanted API endpoints like `api/content`, as they have no meaning for this particular project.

### Expected behavior

We need to find a module that can support these views, that has no dependencies.

Or consider placing them in the `DisplayManagement` module. 

That's tricky because the `DisplayManagement` module does not currently provide Views. 

It does have the `ShapeAttributes`, so one alternative could be to move these to shape attributes.

**Comment by jtkech** [comment]
Yes, a separate module with no deps and that `OC.Contents` would depend on, or `ShapeAttributes` in `OC.DisplayManagement`, and maybe also for the `CardContainer.cshtml` and `Card.cshtml` and all future ones.

Hmm, maybe better to use a module, if easier to add future views.

**Comment by deanmarcussen** [comment]
I think maybe I will move them to `ShapeAttributes`

Because `DisplayManagement` would technically fail without them.

Originally I only did them as views, as easier to see what the code is, to override them. But really they are all very simple shapes, mostly built with `TagBuilder` anyway, so still easy as a `ShapeAttribute`

I will do a pr soon
