### ISSUE TITLE
Dashboard Enhancement - Show selected filters

### ISSUE THREAD

**Issue by micrub-it** [OrchardCMS/OrchardCore#8640]
### Is your feature request related to a problem? Please describe.
Dashboard not show selected filters

### Describe the solution you'd like
as an enhancement, how about displaying the current value of 'Content type', 'Show' and 'Sort' in the UI?

For example, in this case, Content Type: Article, Show: All versions, Sort: recenty modified

![image](https://user-images.githubusercontent.com/72412001/108600604-4bde1180-7398-11eb-9f01-ad988a867056.png)

**Comment by Piedone** [comment]
This does show in the seach field now:
![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/d1cd9415-8805-4ec8-93d5-fcedce570d95)
