### ISSUE TITLE
Assign users permissions  to all of author content

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8643]
An author could assign other users to have permissions over ALL of their content.

**Comment by Skrypt** [comment]
The author is just a trace of the username on the content item. Basically, it's just for displaying a name that is not the UserId. The User could have changed his UserName over time and thus this User could have created content items under different UserNames / Authors ... So, it's kind of tricky here. 

Maybe a User could assign other users to have permission over all their content would work better in that case.

**Comment by JoshTango** [comment]
Yes I meant user thats correct.  The userId and not the author.  Maybe better to say the userId who authored the content?

**Comment by Skrypt** [comment]
Generally we use a specific Role for that matter. Even if only 2 users would be in that Role. Though assigning permissions on content per user is not something we have currently.

**Comment by Piedone** [comment]
Do you still think this would be useful, or have you found OC's RBAC sufficient since then?
