### ISSUE TITLE
Users can only see media files they uploaded

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8644]
I want the media library to only show media files uploaded by the user.
I want the user to only be able to see their content, this includes content items and media files.

I suspect you should introduce a SHARED folder at the top of the existing library.
Then create a USERS folder as well on the same level as SHARED.
Then inside of USERS folder create sub folders for each userID.

There should be a setting to choose whether you want to see user specific files or the SHARED folder files.
Also maybe their is a SHARED folder for files that all users can see.

I think the design needs worked on here?

**Comment by Skrypt** [comment]
It's a feature that need to be implemented. User media folders. We needed to have the UserId implemented first. Now this could be implemented using specific folders for each users based on that UserId.

**Comment by JoshTango** [comment]
Well if the username can't be changed you can just name the user folders after the username?

**Comment by Skrypt** [comment]
We can't prevent someone from wanting to change a username. By default ASP.NET Core Identity allows to change a username and Orchard Core too. So, those folders should be named against their UserId.

**Comment by JoshTango** [comment]
Very well then it should be by userId.

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/7576
