### ISSUE TITLE
Meetings Feedback

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#8649]
@sebastienros @Skrypt @deanmarcussen 

**Usage of `ILocalClock` in `ModularBackgroundService`**

- Schedulers are held by the background service (app singleton), we do this to see if schedulers `CanRun()` without creating a shell scope on all tenant every minute, e.g. if we will want to release a tenant after a period of inactivity.

    @sebastienros you suggested to use `ILocalClock` to get / pass the time zone in place of the service.

    - We already pass it but from site settings, not from `ILocalClock` using dynamic scoped selectors (default one from site settings, one based on the request user), because `CanRun()` can't refresh it without having to create a scope.

    - And we still pass `IClock` (app singleton), because the scheduler `CanRun()` needs to compute e.g. a `local now`

    @Skrypt, we update the schedulers when their settings have changed, and also when the related tenant was released, and this is what happens if the time zone is updated in site settings, the tenant is released, so that's okay ;)

**Limitations of database providers**

- SQL server : We can't drop an index before SQL server 2016.

      IF EXISTS Applies to: SQL Server ( SQL Server 2016 (13.x) through current version).

- Sqlite: We can't alter columns.

- MySQL index row size < 768 chars * 4 = 3072 bytes, checked when we create an index.

- PostgreSql: Truncates index names > `nMax` chars, normally `nMax` is 63 but it truncated the 2 following ones, maybe because a suffix is used, so assuming it to e.g. 50 chars may be good. We added the last one without re-running the func tests, no luck that the first `nMax` chars was the same ;)

      IDX_WorkflowBlockingActivitiesIndex_DocumentId_ActivityId    => 57 chars
      IDX_WorkflowBlockingActivitiesIndex_DocumentId_ActivityName  => 59 chars

**Update**: @Skrypt what i pointed out here for SQL server 2016 is that it is before the **specific version 16.3**, but your suggested code on yesSql seems to be okay as it uses directly the `sys.indexes` table.

**Comment by Skrypt** [comment]
I made a PR on YesSQL to fix the SQL Server issue but we definitely need to **not merge it yet** and create a new Dialect for SQL Server < 2016. I did not have time to work on this yet.

**Comment by jtkech** [comment]
@agriffard Nice demo on OC Templates

About the default TFM, didn't re-try it but based on some recent changes (done for another reason), now i think it is net5.0, the json files was copied for each TFM, so the last was winning, now there are only copied for our defined default TFM.
