### ISSUE TITLE
Liquid / Shortcode 'Content' property conflict

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#8650]
Just by anticipation before upgrading to Fluid 2.0 through #8424.

It was related to #8241 fixed by #8259 by creating a custom `LiquidContentAccessor` but no more used in #8424, so we would need to fix it differently.

1. Maybe by creating a liquid filter in place of using the accessor.

2. Use a dedicated `Shortcode` Liquid property, because it is only related to shortcode that we define using liquid, and in which we could retrieve the shortcode `Args`, `Content`, `Context`, so without breaking the shortcode conventions.

3. Or just use names starting with a lowercase, `args`, `content`, `context` for the shortcode liquid properties.

@sebastienros, personnaly i prefer 2. or 3., otherwise keeping the custom accessor would not have a big impact, and it is only used when executing a shortcode that has been defined through the admin using liquid.

**Comment by deanmarcussen** [comment]
@jtkech some thoughts.

so `Content` is also available via `Model.Content` 

However there was a suggestion here, when we talked about it during a meeting, to deprecate the `Content..` accessor to content items, and use filters instead. https://github.com/OrchardCMS/OrchardCore/issues/8283

So maybe option 1 could be to simply add the content filters, i.e. `content_by_id` etc, and for shortcodes, only make the new filters usable, not the older `Content..` accessor.

That might be less breaking to shortcodes, as the fix to retrieve via the `Content` accessor, was pretty recent, so I don't think as many people will be using it, as are currently using `Content` to retrieve shortcodes.

Note: we did also talk about option 3, `args`, `content, `context` when originally writing shortcodes, to keep it more Liquid, but I opted for Pascal, to keep it more Orchard. Maybe the wrong choice :(

**Comment by jtkech** [comment]
@deanmarcussen 

I forgot to number the last option to keep the current `LiquidContentAccessor` but anyway this was not an option that i liked too. So okay for the filter in place of the accessor, even it is also a little breaking change

Maybe i will just add a comment to #8283 and close this one.

**Comment by jtkech** [comment]
Added a comment to #8283
