### ISSUE TITLE
Implementation of UserId has issue during account confirmation with registration proces.

### ISSUE THREAD

**Issue by HofSof** [OrchardCMS/OrchardCore#8654]
When registering a new user. During the account confirmation proces, the user is not found due to the wrong UserId implementation. The previous User.Id (documentId) is used during the creation of the callbackUrl in the ControllerExtension in de OrcharCore.Users module. 
`var callbackUrl = controller.Url.Action("ConfirmEmail", "Registration", new { userId = **user.Id,** code }, protocol: controller.HttpContext.Request.Scheme);`

Callback URL: `(https://localhost:44300/OrchardCore.Users/Registration/ConfirmEmail?**userId=1861**&code=CfDJ8ATZZSF9%2BsZLtkzSD29GsdZyE%2B%2FiwhTG1mqVL7EscTjaQ0LNZBqn33nJX7yQcMGJv1wZTWgAMJFedrD3NMOh7rl%2BIXblbcJUTS0luFzHjwo7tCrVXJhudLxDJ9rlnPihrRk%2FgdhfIRtndi%2B0fH0gJhWZ%2BPdtwAmQ%2F3xNJAnKhHvbp4uV978qS3cVt8dlOBkvrFPPm4CqfjAZXtveCkq6SxIOJwL%2F6my4xkInZafiaaM2)
`
In the RegistrationController on the ConfirmEmail action, The user is not found by it Id, Because 
`var user = await _userManager.FindByIdAsync(userId);` is searching for the user.UserId

To Reproduce
Register with account confirmation enabled. Klik the "Please click here to confirm your account." in the email.
The user is not found, so the NotFound is shown.  

Expected behavior
The short fix I think is here to use the user.UserId in stead of user.Id in the callbackurl creation.
But I think problem is more fundamental in the sense of semantic of user id's used in the code.
Because it makes mistakes like this more likely. 
The user object has two Id's:  Id and UserId
As far I can see they map to the database fields (Id) DocumentId and (UserId) UserId.
So I would expect that the corresponding Find methodes would be called FindById(id) for the user.Id (DocumentId)
and the FindByUserId(userId) for the user.UserId.

**Comment by Skrypt** [comment]
The method name comes from the ASP.NET Core Identity API we can't rename it.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.findbyidasync?view=aspnetcore-5.0#Microsoft_AspNetCore_Identity_UserManager_1_FindByIdAsync_System_String_

Though if there is an issue we will fix it.

**Comment by Skrypt** [comment]
Things look fine from where we generate this url : 

https://github.com/OrchardCMS/OrchardCore/blob/b6b88ccd1db07cf5424d8b5efef9df1e998d0ead/src/OrchardCore.Modules/OrchardCore.Users/Controllers/ControllerExtensions.cs#L96-L104

**Comment by Skrypt** [comment]
Here is my guess on the issue you are experiencing. Users have been created before you upgraded your Orchard Core to latest version and then these emails are still using the old User.Id. So, if you take the latest dev branch code this should normally not be an issue because these url's uses the new User.UserId.

**Comment by HofSof** [comment]
O Sorry guys, Stupid of me.
I see now I must have made a mistake in the merge with the updates into my repository.
I had to make some adjust in the User Module, we want our user frontend users to use email for the username.
And also added the missing Registration confirmation view. Like the one there is for the Forget Password confirmation.
  
.
