### ISSUE TITLE
Add Content programmatically or through a web api.

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8656]
It would be nice if we could add content to Orchard using a web api?

**Comment by Skrypt** [comment]
It's already there look at the OrchardCore.Contents module controllers there's a ApiController.

**Comment by JoshTango** [comment]
Can the graphQL be sued to add content?

**Comment by Skrypt** [comment]
No there is no mutation from the GraphQL endpoint yet. I think though that there is a branch where you can find them but they need more work (be restricted with permissions). See jsonapi branch.

**Comment by JoshTango** [comment]
ok so no "web api" yet but its on the road map?
if i want I can make a module and call the controllers inside the content module yes?

**Comment by Skrypt** [comment]
Yes there is common REST API's in some of our modules. You can call/test them using Postman for example.
