### ISSUE TITLE
Autoroute slugify is not correct

### ISSUE THREAD

**Issue by lengockyquang** [OrchardCMS/OrchardCore#8658]
I'm using Orchard Core RC2. When I create a blog post with autoroute part, I'm using default pattern {{ ContentItem.DisplayText | slugify }}  of autoroute and let it auto-generate permalink for my post. 
But when it generated, the slug is not correct.

Input: Đại học Tôn Đức Thắng
Pattern: {{ ContentItem.DisplayText | slugify }}
Ouput: đai-hoc-ton-đuc-thang
Expected output: dai-hoc-ton-duc-thang

As you can see, the "đ" word after slugify is not transform to "d" word. I'm not sure is it a bug ? If not, are there any options that I can override slugify filter of liquid pattern ? Currently, I have to use "replace" filter of liquid to replace "đ" to "d"
Thanks all

**Comment by flew2bits** [comment]
It appears that this is the "correct" behavior based on the slugify code, but may not be the desired behavior. The "đ" (latin small letter d with stroke) has the Unicode Category of Lowercase Letter, so it doesn't actually have a base character "d". 

Here's a stackoverflow question related to this question: https://stackoverflow.com/questions/2362810/why-doesnt-%C4%90-get-flattened-to-d-when-removing-accents-diacritics

**Comment by lengockyquang** [comment]
oh i see, thanks for the explanation. Gonna close it :)

**Comment by flew2bits** [comment]
I think you should re-open -- I wasn't implying that the issue shouldn't be addressed. The desired behavior probably makes more sense than the "correct" behavior. I only commented because I was curious about the reason it wasn't getting picked up by the slugify code.

**Comment by lengockyquang** [comment]
I was also curious at first but with your link, things get more clearly. Luckily we can use liquid replace to post-process the slug. I reopened this issue for others can give it  a look and close it if needed

**Comment by Piedone** [comment]
What's the issue with the "đ" character in the slug? Can you explain the problem you're experiencing?

BTW you can override the default service by implementing `ISlugService` if you need a different behavior.
