### ISSUE TITLE
Delete content item stop working when overriding ContentsButtonActions_SummaryAdmin.cshtml

### ISSUE THREAD

**Issue by luis3199correia** [OrchardCMS/OrchardCore#8661]
### Describe the bug
After overriding the ContentsButtonActions_SummaryAdmin.cshtml, without changes, the delete button action stop working.

### To Reproduce
1. Add ContentsButtonActions_SummaryAdmin.cshtml [view](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Views/ContentsButtonActions_SummaryAdmin.cshtml) to Views folder
![image](https://user-images.githubusercontent.com/32116636/108837115-b3c76e80-75c9-11eb-8634-6fd84c978728.png)
2. Go to 'Content Items' and try to delete a content

### Expected behavior
I was hoping that after overriding the view, the generated html would be the same.

### Screenshots
Delete button html after overriding the view
`<a remove-for="template" class="dropdown-item btn-sm" data-url-af="RemoveUrl UnsafeUrl" data-title="Delete" data-message="Are you sure you want to delete this content item?" data-ok-text="Ok" data-cancel-text="Cancel" href="/Contents/ContentItems?returnUrl=%2FContents%2FContentItems%3Fadmin%3D-1554890804">Delete</a>`

Delete action result after override
![image](https://user-images.githubusercontent.com/32116636/108837340-fe48eb00-75c9-11eb-80cf-73fa79d0b1f3.png)

Delete button html before overriding the view
`<a class="dropdown-item btn-sm" data-url-af="RemoveUrl UnsafeUrl" data-title="Delete" data-message="Are you sure you want to delete this content item?" data-ok-text="Ok" data-cancel-text="Cancel" href="/Contents/ContentItems/4ekvkjf6crad52nyayvxd7k14z/Delete?returnUrl=%2FContents%2FContentItems%3Fadmin%3D-1554890804">Delete</a>`

**Comment by deanmarcussen** [comment]
You maybe missing a tag helper reference in your `_ViewImports.cshtml`.

`@addTagHelper *, OrchardCore.Contents.TagHelpers` - and a direct reference to the taghelpers project.

`<a remove-for="template"` because the remove-for is still visible in the output html (I assume that's what this is, the output html) it suggests the tag helper hasn't run. Which is a bit odd, because it's also got an href element.

But check you have the taghelper reference.

**Comment by luis3199correia** [comment]
> You maybe missing a tag helper reference in your `_ViewImports.cshtml`.
> 
> `@addTagHelper *, OrchardCore.Contents.TagHelpers` - and a direct reference to the taghelpers project.
> 
> `<a remove-for="template"` because the remove-for is still visible in the output html (I assume that's what this is, the output html) it suggests the tag helper hasn't run. Which is a bit odd, because it's also got an href element.
> 
> But check you have the taghelper reference.

Yes, it worked. Thanks for your help.
