### ISSUE TITLE
Latest OrchardCore packages from Cloudsmith break Razor hot reload

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#8662]
### Describe the bug
Razor hot reload does not work

### To Reproduce
1. Use a project with the latest Orchard Core packages from Cloudsmith and Razor page
2. Run the project with Ctrl+F5
3. Change the Razor of the page
4. Reload the page - nothing changes

But with RC2 packages it works

### Expected behavior
Razor hot reload works

**Comment by xperiandri** [comment]
@sebastienros I've tested all the available CI packages till `1.0.0-rc2-14367` and no one works.
But as soon as I switch to `1.0.0-rc2-13450` it works again.

**Comment by deanmarcussen** [comment]
Have you tried with `dotnet run` ?

I can't repro the issue on mac, and equally can't test in in Visual Studio.

Perhaps paste your `.csproj` host startup file, there maybe missing elements that are required for runtime compilation of views.

**Comment by xperiandri** [comment]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace SecretCircle.BmwCms
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
            var contentTypeProvider = new Microsoft.AspNetCore.StaticFiles.FileExtensionContentTypeProvider();
            contentTypeProvider.Mappings.Add(".scss", "text/scss");
            services.Configure<StaticFileOptions>(o => o.ContentTypeProvider = contentTypeProvider);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }

            app.UseOrchardCore();
        }
    }
}
```

**Comment by deanmarcussen** [comment]
Sorry I meant `.csproj` file

**Comment by xperiandri** [comment]
``` XML
<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\Solution.Build.props" />

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <UserSecretsId>$(AssemblyBaseName)</UserSecretsId>
    <RootNamespace>$(BaseRootNamespace)</RootNamespace>
    <AssemblyName>$(AssemblyBaseName)</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Boxed.AspNetCore" Version="5.1.2" />
    <PackageReference Include="Boxed.AspNetCore.TagHelpers" Version="4.0.0" />
    <PackageReference Include="DisposableFixer" Version="3.3.0" />
    <PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ErrorProne.NET.Structs" Version="0.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Flurl" Version="3.0.1" />
    <!--<PackageReference Include="LigerShark.WebOptimizer.Core" Version="3.0.295" />-->
    <!--<PackageReference Include="LigerShark.WebOptimizer.Sass" Version="3.0.43-beta" />-->
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.2.0" />
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="$(OrcahrdCoreVersion)" />
    <PackageReference Include="OrchardCore.Templates" Version="$(OrcahrdCoreVersion)" />
    <PackageReference Include="Roslynator.Analyzers" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CSharp" Version="1.0.0" />
    <PackageReference Include="Syncfusion.EJ2.AspNet.Core" Version="18.4.0.34" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrchardCore.FavIcon\OrchardCore.FavIcon.csproj" />
    <ProjectReference Include="..\SecretCircle.BmwTheme\SecretCircle.BmwTheme.csproj" />
    <ProjectReference Include="..\SharpScss\src\SharpScss\SharpScss.csproj" />
    <ProjectReference Include="..\WebOptimizer.Sass\src\WebOptimizer.Sass.csproj" />
    <ProjectReference Include="..\WebOptimizer\src\WebOptimizer.Core\WebOptimizer.Core.csproj" />
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties properties_4launchsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>

</Project>
```

**Comment by deanmarcussen** [comment]
try adding `<PreserveCompilationReferences>true</PreserveCompilationReferences>`

**Comment by xperiandri** [comment]
@deanmarcussen it indeed helps! Works after adding that setting

**Comment by xperiandri** [comment]
It is only required in an app project. On a theme project, it does not affect anything.

**Comment by sebastienros** [comment]
JT told me that you need to add this property when you have your ASPNETCORE_ENVIRONMENT defined to Production. This should appear in the console when the app starts. When you run your app from VS you should always have Development, and it will allow you to change the razor files dynamically. Otherwise you will need this PreserveCompilationReferences property and it will build all razor files at runtime which will make the app much slower.

**Comment by sebastienros** [comment]
This value is also usually set in the `launchSettings.json` file. Please check what it contains for you if you don't have the ENV defined on your system, or the project settings.

**Comment by sebastienros** [comment]
c.f. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0

**Comment by xperiandri** [comment]
But if I run with Ctrl+F5 is still sets the environment to Development. But the Razor hot reload does not work.
This is what we used to, doing Razor development on the fly without debugging.

**Comment by jtkech** [comment]
Just tried with Ctrl+F5, it works

Having `PreserveCompilationReferences = true` in the main app project file
Also `Sdk="Microsoft.NET.Sdk.Web` in the first line of the project file
And `"ASPNETCORE_ENVIRONMENT": "Development"` for `"IIS Express"` in the `launchSettings.json`

**Comment by xperiandri** [comment]
Yes, it is.
@sebastienros told that it forces the same behavior in production scenarios which is bad for performance.
Was it the same in .NET 3.1?

**Comment by xperiandri** [comment]
Does it mean the `PreserveCompilationReferences` must be enabled for `Debug` project configuration only or can it be set in `launchSettings.json`?

**Comment by jtkech** [comment]
To have razor runtime compilation you need both

 `PreserveCompilationReferences = true` and `ASPNETCORE_ENVIRONMENT = Development`

If in production you actually have e.g. `ASPNETCORE_ENVIRONMENT = Production`, not `Development`

That's okay, you can keep `PreserveCompilationReferences = true`, you will not have runtime compilation

**Comment by sebastienros** [comment]
How does this last comment make sense?
> To have razor runtime compilation you need both PreserveCompilationReferences = true and ASPNETCORE_ENVIRONMENT = Development

> you can keep PreserveCompilationReferences = true, you will not have runtime compilation

**Comment by jtkech** [comment]
Razor runtime compilation needs compilation libraries in the `refs` folder, otherwise it fails, we check it at runtime before registering the related services, so to have runtime compilation we first need `PreserveCompilationReferences = true` to create and populate the `refs` folder . Then, we need our custom file provider to serve the view contents from their project locations, we activate it only if we are in `Development` mode.

So, to have razor runtime compilation, we need both `PreserveCompilationReferences = true` and `ASPNETCORE_ENVIRONMENT = Development`. If we are not in `Development`, e.g. `Production`, we never have razor runtime compilation, having `PreserveCompilationReferences` or not will just populate or not the `refs` folder, but in both case there is no runtime compilation

**Comment by sebastienros** [comment]
> As i remember, at some point PreserveCompilationReferences was true by default, which is no more the case

Does it mean that the default experience for ASP.NET is to not have runtime compilation, and that if you change a Razor file, even in Development then it doesn't refresh?

**Comment by jtkech** [comment]
Yes, as i remember, razor runtime compilation is no more the default, and if you want it you now need to reference explicitly the razor compilation package in a given application project

Because of our multi tenants structure, we reference this package automatically per tenant, and we register the related services, but only if the `refs folder` exisits.

**Comment by ns8482e** [comment]
In VS 2019, while creating new Razor/MVC project, you have a choice to enable "Razor runtime compilation".

It can also be enabled by setting env var in launchsettings.json
`  "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"`
