### ISSUE TITLE
IOpenIddictTokenManager not implemented

### ISSUE THREAD

**Issue by 1silvertiger** [OrchardCMS/OrchardCore#8668]
### Describe the bug
When I clone the project and try to run it in VS 2019, I get a series of CS0738 errors saying 

>'OpenIdTokenManager<TToken>' does not implement interface member 'IOpenIddictTokenManager.SomeFunction()'. 'OpenIddictTokenManager<TToken>.SomeFunction()' cannot implement 'IOpenIddictTokenManager.SomeFunction()' because it does not have the matching return type of 'TheCorrectReturnType<SomeType>'. 

for every function in IOpenIddictTokenManager. This happens on `master` and `dev`.

The error is thrown on line 13 of `src\OrchardCore\ OrchardCore.OpenId.Core\Services\Managers\OpenIdTokenManager.cs`. `OpenIdTokenManager<TToken>` implements `IOpenIdTokenManager`, which in turn implements `IOpenIddictTokenManager`. But `OpenIdTokenManager<TToken>` doesn't have any of the functions from `IOpenIddictTokenManager`.

The project runs fine from the command line.

### To Reproduce
1. Clone OrchardCore.
2. Make sure `OrchardCore.Cms.Web` is the startup project etc.
3. Run the project in VS 2019.
4. The errors show up in the Error List.

### Expected behavior
The project runs.

### Screenshots
![image](https://user-images.githubusercontent.com/20326519/109078299-b954af80-76c2-11eb-8ad2-71296aa0f693.png)

**Comment by deanmarcussen** [comment]
You need to install the dotnet 5 SDK to build the latest dev branch, due to a bug in the 3 SDK that impacted `OpenIddict`

It will still run on core 3, it is just for the build

**Comment by 1silvertiger** [comment]
Whoops, I forgot to mention that I did install the dotnet 5 SDK.

**Comment by deanmarcussen** [comment]
You probably need to install the latest Visual Studio.

Also just try and see if it builds from the command line `dotnet build`

**Comment by 1silvertiger** [comment]
I updated Visual Studio and it worked 👍 

It also worked running from the command line with `dotnet build` and `dotnet run` before I updated VS. Thanks for the help.
