### ISSUE TITLE
Contents/ContentTypes features in Default tenant suddenly and inexplicably turned off?

### ISSUE THREAD

**Issue by willnationsdev** [OrchardCMS/OrchardCore#8671]
### Describe the bug

End of workday, 5pm, all good. Morning of next day, 8am, we find the admin and frontend broken: AdminMenu is rendered twice, frontend content has errors, the backend admin's content area gives errors, but only when you try to go to the ContentItems section or attempt to edit a content type/part definition.

This occurred in all tenants, including the Default tenant. While investigating, we found that the Default tenant's Contents and ContentTypes features had been disabled, but no person had manipulated the runtime app or the database outside of work hours. Other tenants had Contents/ContentTypes turned on, but still experienced the issue. When we turned the features back on in the Default tenant, it fixed the issue for Default and all of the other tenants.

The question is: **how did this happen?**

This would indicate to *me* that something happened to the ShellState of the Default tenant, either in memory, in the database, or during some serialization/deserialization process of the ShellState in between (since that manages the on/off status of features, right?). Correct me if I'm wrong.

The only indication that *something* happened is a random warning log that occurred at 8:36pm the night before the errors cropped up:

```
2021-02-24 20:36:31.7177||||Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository|WARN|Using an in-memory repository. Keys will not be persisted to storage. 
2021-02-24 20:36:31.7595||||Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. 
2021-02-24 20:36:31.8025||||Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|No XML encryptor configured. Key {c6866a53-f7f5-46f8-a2b6-29c4de167d0f} may be persisted to storage in unencrypted form. 
```

Any ideas how this bug could have happened? Are there any background jobs that OC runs that could have triggered the error message, despite us not having that feature turned on in any tenant? Why would it have suddenly occurred with no human interaction? And why would it have affected the ShellState (or whatever else could suddenly deactivate features like that)?

### To Reproduce
No idea

### Expected behavior
I would expect the application's state to be deterministic and require explicit human commands to be mutated.

**Comment by Skrypt** [comment]
Looks like the DataProtection-keys storage is warning you that the Keys won't be persisted in the App_Data folder.
Here, we store the DataProtection-keys of each tenants in /App_Data/Sites/TenantName/DataProtection-keys or we have a Azure DataProtection feature that allows to use Azure blob storage for this.

That's one part of the issue because the tenant faulted to store it's DataProtection-key.

**Comment by willnationsdev** [comment]
@Skrypt What exactly prompts the attempt to persist the DataProtection-keys then? There must be some instigating factor somewhere. I'll have to peruse the related code at some point. Thanks for the info.

**Comment by Skrypt** [comment]
Good question. I don't know yet to be honest. I would start by looking at IDataProtectionProvider and see what it does exactly. Though the interface makes use of Microsoft.AspNetCore.DataProtection; so the documentation might be in the Asp.NET Core repo.

**Comment by deanmarcussen** [comment]
I read a site restart (i.e. apppool restart) in those logs, i.e. at the time the data protection reports issues.

I have never seen features turn themselves on or off due to server restarts.

Probably the best is a bit more information on your hosting environment, databases in use, o/s that kind of thing.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
