### ISSUE TITLE
Deployment plan failed to execute with related user settings

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8685]
I enabled all the user features like registration and recaptcha and login and I also added them to my deployment plan. 
When I tried to execute my deployment plan is failed and said error.

**Comment by JoshTango** [comment]
Ok I am going to remove them all and add one by one to find the one causing the problem.

**Comment by JoshTango** [comment]
All are fine except the Login Settings.
That one throws an error if you add it to the deployment plan.

Not e that I had toggled use site theme for login on and off.

**Comment by hishamco** [comment]
Could you please share the exception details and attach a sample recipe if it's possible

**Comment by JoshTango** [comment]
It did not show me the details.

**Comment by deanmarcussen** [comment]
You'll have to look in your logs @JoshTango otherwise noone will ever be able to know what the issue is.

**Comment by JoshTango** [comment]
when I can reproduce I will do that

**Comment by Piedone** [comment]
Closing due to no reply update the author.
