### ISSUE TITLE
ArgumentNullException on CreateContentItemVersionAsync

### ISSUE THREAD

**Issue by NickDarvey** [OrchardCMS/OrchardCore#8698]
### Describe the bug
I'm getting a ArgumentNullException when trying to create a new version with `CreateContentItemVersionAsync`.

### To Reproduce
1. Create an updated content item with `Latest = true` and `Published = false`
2. Invoke `CreateContentItemVersionAsync(item)`

```csharp
static ContentItem UpdateEventTemplate(Client.EventTemplate eventTemplate, ContentItem current)
{
  var updated = current
    .Alter<Course.CoursePart>(c =>
    {
      c.Name.Text = eventTemplate.Name;
      c.Summary.Text = eventTemplate.Summary;
      c.Description.Text = eventTemplate.Description ;
    });
  return current.Merge(updated);
}
var existingItems = await _session.Query<ContentItem, MyIndex>(i => i.ExternalId == eventTemplate.Id).ListAsync();
var latestExistingItem = existingItems.OrderByDescending(r => r.ModifiedUtc).FirstOrDefault(r => r.Latest);
// 'New item' code branch omitted from this snippet
var updated = UpdateEventTemplate(eventTemplate, latestExistingItem);
var result = await _content.CreateContentItemVersionAsync(updated);
LogOutcome(result);
if (result.Succeeded) await _content.SaveDraftAsync(updated);
```

### Expected behavior
If there's an existing draft, it is discarded (`Latest = false`) and replaced with my `var updated`.
If there's an existing published item, it stays published and a new draft is created with my `var updated`.

### Actual behaviour
nullargs on (I think) this line:
https://github.com/OrchardCMS/OrchardCore/blob/beea0ae534dd687bbdcc1a8c8f630bcb40c3633d/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L860

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OrchardCore.ContentManagement.DefaultContentManager.RemoveLatestVersionAsync(ContentItem contentItem, IEnumerable`1 evictionVersions)
```

Looking at the code, I can see why: there is a `latestVersion` set so we hit [this branch](https://github.com/OrchardCMS/OrchardCore/blob/beea0ae534dd687bbdcc1a8c8f630bcb40c3633d/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L858-L870). `evictionVersions` is used even though it's null. 
Is the appropriate fix doing a query for the published version if `evictionVersions` hasn't been passed in?

**Comment by deanmarcussen** [comment]
When you are retrieving your content item you should call `_contentManager.GetAsync(myContentItemId, VersionOptions.Latest)` at which point it will retrieve either the current draft (latest), or create a new draft, and place it in the session helpers.

If you do the queries manually like you are you will have to manage the life cycle yourself.

**Comment by NickDarvey** [comment]
Ok, understood. Is using `_contentManager.CreateContentItemVersionAsync(updated)` to update it correct though?

**Comment by jtkech** [comment]
@deanmarcussen @NickDarvey 

Regarding the linked code, we assume that `evictionVersions` may be null, and in that case we still init `latestVersion` that may be not null, so below when using `evictionVersions` we need to add a null check, i will add it.

            if (evictionVersions == null)
            {
                latestVersion = await _session.Query<ContentItem, ContentItemIndex>()
                    .Where(x => x.ContentItemId == contentItem.ContentItemId && x.Latest)
                    .FirstOrDefaultAsync();
            }
            else
            {
                latestVersion = evictionVersions.FirstOrDefault(x => x.Latest);
            }


            if (latestVersion != null)
            {
                var publishedVersion = evictionVersions.FirstOrDefault(x => x.Published);


                var removeContext = new RemoveContentContext(contentItem, publishedVersion == null);
