### ISSUE TITLE
Creating a content item from the admin in a different tenant causes  Exception: Shape type 'PartyPart_Edit' not found

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#8699]
I have a custom module called Parties which has a partyPart part to create Party content types.

When activating the module from the default tenant and creating a new Party content item from the admin from the "New" Menu it works as expected.

When creating a new tenant and activating the feature from the new tenant  I then try to create a new Party content item from the tenant admin and I get : 
Exception: Shape type 'PartyPart_Edit' not found
![image](https://user-images.githubusercontent.com/1516981/109467159-73596c00-7a73-11eb-882e-95a504202c19.png)

Strange because it only happens for my custom features in any other tenant except the Default.
For the built in orchard features it works normally in the other tenants.

**Note :** **If i copy the PartyPart.Edit.cshtml into the admin theme under views folder than it works as expected from the tenant.
So the issue is why isnt it picking the shape from the module Views folder in the context of a different tenant.**

**Comment by deanmarcussen** [comment]
I would check

- that the modules startup is being called (debugger) for the tenant, i.e. is it activated
- your modules `.csproj` to make sure there are no references to the view in question (where VS may have turned it's type into something it shouldn't be) 

When's the party?

**Comment by giannik** [comment]
No parties here , due to covid, only Party data modelling 
https://tdan.com/a-universal-person-and-organization-data-model/5014
Will investigate your points @deanmarcussen .
Its just strange that its working from the default tenant but not from a different one.

**Comment by giannik** [comment]
I confirmed that the module startup in the tenant is running corrctky and the driver.Edit method is beeing called.
Also checked the .csproj file of the module and its clean.No funny elements.

Im thinking if it could be some shape binding mismatch from the admin from the tenant or some shape caching lookup  in the admin.
Maybe @jtkech  can give some pointers where to place a breakpoint to see where its looking for the files to use from the tenant ?

**Comment by jtkech** [comment]
Hmm, maybe because your feature is not the main one of your module, normally the main one is the first one whose id is the module id, and because your feature doesn't depend on the main one in your manifest, because shapes are harvested at the module level, not at the feature level, then they are shared accross tenants but in a given tenant the module need to be enabled, in fact the main feature of the module, not only another feature, so maybe the main feature is only enabled in the default tenant, but not in another one as your feature doesn't depent on the main one.

But not sure at all ;)

**Comment by Skrypt** [comment]
@jtkech I noticed also last night that now the Liquid Templates passes before a fixed route in a module. That's a behavior that changed recently not sure why yet.

**Comment by jtkech** [comment]
@Skrypt not sure i understand, will talk about it on skipe

**Comment by giannik** [comment]
@jtkech , I did'nt know that you had to have at least 1 module defined at the assembly level. I had only features declared in my assembly. Changing that it worked. Thanks
