### ISSUE TITLE
FlowPart button needs to be more pronounced in the editor

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8709]
The flow part button is impossible to see or notice.
Perhaps work on making the flow part more obvious?

**Comment by NogginBox** [comment]
Please add a screenshot to illustrate how you can't see the button.

**Comment by JoshTango** [comment]
Its opacity is lowered so much.

**Comment by JoshTango** [comment]
![image](https://user-images.githubusercontent.com/42816989/110409883-fb340d00-8055-11eb-8501-21d14e49d2cc.png)

**Comment by Skrypt** [comment]
I must agree on that one. It is not obvious for someone who doesn't know that there is a FlowPart there.

**Comment by kdubious** [comment]
Easy to fix, just needs a "decision"

**Comment by deanmarcussen** [comment]
Suggest someone makes a pr, unless you disagree @ns8482e ?

**Comment by ns8482e** [comment]
Usability is debatable,  - IMHO opaque button with primary color was distracting when you have lot of contents with containers.
However ether way, I am fine.

**Comment by kdubious** [comment]
This one is both a usability issue and an accessibility issue, too.

**Comment by Skrypt** [comment]
Without making is opaque could we say we make it 10% less transparent?
