### ISSUE TITLE
Duplicate SQL Running in MSSQLSERVER creating the site

### ISSUE THREAD

**Issue by zippy1981** [OrchardCMS/OrchardCore#8711]
### Describe the bug

When I create an orchard site with SQL Server it seems to be running T-SQL DDL Twice

### To Reproduce

Create an orchardcore site, with Azure Storage Shell (that part probably irrelevant).

Create a SQL Server database, role and contained user like so:

```SQL
/*
EXEC sp_configure 'show advanced', 1
GO
RECONFIGURE
GO
EXEC sp_configure 'contained database authentication', 1
GO
RECONFIGURE
GO
*/
/*
USE MASTER;
ALTER DATABASE orchard SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE orchard SET ONLINE;
DROP DATABASE orchard;
GO
*/
CREATE DATABASE orchard;
ALTER DATABASE orchard SET CONTAINMENT=PARTIAL;
GO
USE orchard;
GO


CREATE ROLE orchard_www;
CREATE USER www WITH PASSWORD = '*************************;
ALTER USER [www] WITH DEFAULT_SCHEMA = dbo;
ALTER ROLE [orchard_www] ADD MEMBER [www];
GRANT SELECT, INSERT, UPDATE, DELETE ON DATABASE::orchard TO [orchard_www];
GRANT ALTER ON SCHEMA::dbo TO [orchard_www];
GRANT CREATE TABLE, REFERENCES TO [orchard_www];
```

Begin a profiler or extended events session to look at DDL and user errors.

Run `dotnet watch run ` in a terminal and hit up <https://localhost:5001>.

Create a site with a SQL Server backend

### Expected behavior

No errors in profile.

### Actual behavior

The following tables created:

![image](https://user-images.githubusercontent.com/146930/109568411-e0d9bc80-7ab4-11eb-9441-45306b8761d6.png)

But also the following errors indicating T-SQL is being run twice:

```
The operation failed because an index or statistics with name 'IX_Dimension' already exists on table 'Identifiers'.
There is already an object named 'Identifiers' in the database.
```

**Comment by jtkech** [comment]
See from this comment https://github.com/sebastienros/yessql/issues/322#issuecomment-762442375 and the following ones

**Comment by sebastienros** [comment]
Can you confirm the setup just worked fine but you could only see this by inspecting the profiler traces?
Did you just do that by curiosity? Feel free to send some feedback on what you see, I believe you have some strong experience with dbs.

**Comment by zippy1981** [comment]
The setup worked fine. I had some issues getting the database to build, but that was because I was using a user that was not db_owner, and purposefully trying to find minimal viable permissions (as mentioned in #8713).  I setup the profiler tracing to help me arrive at the minimal GRANTs and ROLEs to run with no errors.

**Comment by Skrypt** [comment]
PR will close it keep it open.
