### ISSUE TITLE
CQRS and Event Sourcing

### ISSUE THREAD

**Issue by gentledepp** [OrchardCMS/OrchardCore#872]
Hello!

I hope this is the right environment to as such a question:

Are you planning to support CQRS and (especially) Event Sourcing in orchard 2?

As far as I understood, the data is stored in YesSql along with its indices, but there might be other data stores that we want our data to be stored and analyzed in (e.g. Lucene, ElasticSearch, some graph database, etc) and event sourcing just makes it incredibly easy to keep those stores in sync. 

So are there any plans?

And if not: would it be ok, to introduce such a feature as a Module.
E.g. I could create an EventSourcing module that uses NEventStore to store a stream of events in the same database as YesSql does (as I guess they all provide the same set of database systems)

Please let me know your thoughts!

**Comment by Jetski5822** [comment]
@sebastienros whats your thoughts?

**Comment by sebastienros** [comment]
This could be something to add to YesSql directly. However it would not prevent some code to use the tables directly (I do it in one case I think where documents don't make sense).
But it can also be done in Orchard when it makes sense, with custom interfaces when the store can be customized. It depends on the goals.

I'd say that Orchard is already extensible enough that if you wanted to analyze some data, you could just write a module that would gather the information you need.
Structured log could also be a cheap approach for most needs.

Do you have any concrete scenarios that could make us decide to implement it by default?

**Comment by gentledepp** [comment]
Why do you want to add this directly to YesSql?

I think the separation of concerns is quite important when it comes to EventSourcing and it could be too tempting to access the data in a projection together with the event stream at the same time. Don't you aggree?

Basically, we have multiple goals, but the most important ones are **synchronization** and **scalability**

As for scalability, we want to sync the different data stores we use to analyze our data with orchard. (such as graph databases, lucene, some weird sql reporting store, etc.)
The only way to achieve that in a scalable way is through event sourcing.
There is a great video explaining this: https://slack-redir.net/link?url=https%3A%2F%2Fwww.infoq.com%2Fpresentations%2Fevent-streams-kafka 

1) we want to version the content types and sync the changes applied to them between multiple instances of orchard.
As there is no single source of truth in this scenario, we're gonna go with a strategy that is kind of like "git merge" so we get the same stream of events on all systems.

2) we want to sync the "non contenttype" data (content items) between a single orchard instance and multiple mobile apps.
in this scenario, the single source of truth is the orchard instance, so we are going to go with a merge strategy similar to "git rebase" where the clients are rebasing their changes onto the (orchard) server "branch"

I would be happy to opensource all this stuff so that others can benefit for it, but I would rather go with a proved framework (NEventStore) that implementing everything from scatch.


So for the simplest case, I'd need something like a callback whenever a contenttype is changed, so I can catch that, create an event that I'll write to the event stream and after that, forward the call to the original source so the content type is actually changed. (like a dynamic proxy if you wish)

**Comment by gentledepp** [comment]
I recently had a look at your talk on YesSQL at Orchard Harvest 2017.
Very interesting stuff, I have to admit.

But as much as I like it, as much I doubt that this will be a scalable DAL for our purposes.

The main reason is, that the indices are (as far as I understood) maintained synchronously within the same session (or its transaction).

In other document databases (such as RavenDB), indices are created in a separate background process, and that is why adding a document is still fast.
This is the reason why RavenDB tries to shove "CQRS" in our faces. ([see this article for clarity](http://www.lobsterfs.co.uk/blog/the-secret-to-ravendb/))

CQRS is a very important concept for us.
1) I would love to see, that there was a mediator pipeline as it would allow us to ease-in cross cutting concerns  (see [MediatR 1](https://lostechies.com/jimmybogard/2015/05/05/cqrs-with-mediatr-and-automapper/))
and also find the best way to retrieve data for a specific scenario (see [MediatR 2](https://lostechies.com/jimmybogard/2015/05/05/cqrs-with-mediatr-and-automapper/))

Moreover, that would mean, that all changes to the object model (data, etc) is done through commands. 
If needed, we could replace the MediatR handlers with ones, that do not change the orchard data in a CRUD way (as it is done now), but create events.
So we could basically add-in EventSourcing. (sure, it would be a bit more complicated than that, but at least it could be possible)

2) Also, see this post to get an idea how a CQRS based REST API could look like: 
[CQRS and REST](https://lostechies.com/jimmybogard/2016/06/01/cqrs-and-rest-the-perfect-match/)


What do you think?

**Comment by sebastienros** [comment]
I also want to be able to build and rebuild indices asynchronously from the document updates. And make it optional to maintain consistency or not, as we could choose from these scenarios:
1- Update indices in the same transaction as the document updates
2- Update indices in a separate process, which can be triggered automatically when a document is updated

It could also expose some APIs to check if an index is stale, and ideally manipulate indices dynamically.

**Comment by Skrypt** [comment]
I think the main reason why it needs to be added to YesSQL is because this is where you can get an ID from a newly added record. This is the first thing required to be able to trigger an Event that would build incrementally indexes on records. I'm thinking that you might also need a third option that would run an incremental indexation of records every X time to make sure that you get all scenario's covered. Some could import data through SQL import directly too. @sebastienros Am I right?

**Comment by gentledepp** [comment]
@Skrypt - you are right - data synchronization is a whole new topic, but it is the reason why we need EventSourcing, because when you track individual changes (deltas), you can merge much easier.
@sebastienros 

> make it optional to maintain consistency or not
with that, I hope you mean "choose between transactional and eventual consistency", right?
because async indices require the latter, which can only be achieved by using event sourcing.

I already posted an extremely valuable "video plus slidedeck" link on that topic - did you have a look?
If not, I would **strongly** encourage you to do so :-) 
[Staying in Sync: From Transactions to Streams](https://martin.kleppmann.com/2016/03/07/qcon-london.html)

**Comment by gentledepp** [comment]
@sebastienros : [I created an issue for YesSql here](https://github.com/sebastienros/yessql/issues/71), where I am unsure if complex indices as the following are (or will ever be) supported:

```
public CustomerIndex()
{
    AddMap(customers => from customer in customers
        let region = LoadDocument(customer.RegionId)
        let country = LoadDocument(region.CountryId)
        let orders = LoadDocument(customer.OrderIds)
        select new
        {
            Id = customer.Id,
            CustomerName = customer.Name,
            RegionName = region.Name,
            CountryName = country.Name,
            OrdersProcessed = orders.Count(o => o.IsProcessed),
            ProductIds = orders.Select(o => o.ProductId)
        });
    StoreAllFields(FieldStorage.Yes);
}
```

**Comment by Skrypt** [comment]
@bleroy I think knows more about data synchronization than I. This is a topic that has already been discussed about before. I think Bertrand has arguments against using GUID's and also prefers Integers ; that's why it's been designed that way.

Should we presume that when you say "event sourcing" you mean extend through predefined events in Orchard Core?

**Comment by gentledepp** [comment]
Sure, but ravendb “only“ uses lucene for indexing.
What I would criticise is if complex indices (spanning multiple documents) were not supported by yessql.
But as indices are not created in the background bin within the same transaction, that would be a showstopper for us. But i'd really love to use orchard 2 as an application platform... :-$

With event sourcing i mean real event sourcing like “all changes are made through commands, these cause an ordered list of events and that help us create eventually consistent indices using a multitude of technologies such as lucene, elastic search, neo4j, ect. etc.“

**Comment by Skrypt** [comment]
I'm pretty sure this can be done if it's not already "prepared" to be that way. Right now at this "early" stage I'd say that **scalability** was probably not a first priority. I second that it's a feature that is needed. 👍

**Comment by gentledepp** [comment]
Please be more precise - what can be done?
 Event sourcing or complex indices? :-)

**Comment by Skrypt** [comment]
I'm not the one to ask for a precise answer. I'd say though that scalability is important and it seems logic to use tasks/events to make this extensible for using external services like Elastic Search. For complex indices I'd need to look back at YesSQL and it's been a while I've looked at it. I'm pretty sure @sebastienros will find a solution 😄
