### ISSUE TITLE
Expose events for background task execution

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#8726]
### Is your feature request related to a problem? Please describe.
Currently, if you want to know from code when a background task is executed and how long it takes there's no easy way to do it, you can't easily tap into background task execution. It's probably a problem unique to application performance monitoring (and otherwise necessary if you want to collect telemetry on background tasks).

### Describe the solution you'd like
`ModularBackgroundService` could raise events when the execution of a background task starts and when it ends (perhaps separately when it completes successfully and with an error). Basically, raise events when there's logging currently.

### Describe alternatives you've considered
In the Application Insights module this is somewhat hackishly achieved [with a logger](https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/dev/Services/BackgroundTaskTelemetryLoggerProvider.cs#L27) that listens to the specific log entries. However, this is rather an abuse of logging.

**Comment by sebastienros** [comment]
Diagnotic counters?

**Comment by sebastienros** [comment]
https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counters

I believe Application Insights can record them natively?

**Comment by sebastienros** [comment]
Here is how npgsql does that https://github.com/npgsql/npgsql/blob/d42cc68e0fa71ce15d4afd60e7f9481ca370cebb/src/Npgsql/NpgsqlSqlEventSource.cs

**Comment by Piedone** [comment]
The AI docs recommend starting a dependency operation for background tasks: https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#long-running-background-tasks So I'd keep doing that and having events raised in Orchard seems to me like the most straightforward integration point, not just for this use-case.
