### ISSUE TITLE
MySQL connection Error

### ISSUE THREAD

**Issue by don-dev** [OrchardCMS/OrchardCore#873]
While setting up, An error occurred while initializing the datastore: Unable to connect to any of the specified MySQL hosts.

I have other sites connecting to this server correctly. my connection string looks like:
`server=localhost;user id=<username>;password=<pw>;port=8889;database=Orchard;`

also as it fails, the screen reloads, displays the connection error, but removes these fields from the setup form.

**Comment by agriffard** [comment]
Related to #944

**Comment by sebastienros** [comment]
Duplicate of #944
