### ISSUE TITLE
Multi targetting with external nuget packages causing issues 

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8734]
### Describe the bug

When multi targetting an externally built nuget package, it is only discovered as a module, if the entire solution consuming it is also multi targetted. 

If the solution isn't also multi targetted the module is not discovered.

### To Reproduce

```
  <PropertyGroup>
    <!-- <TargetFrameworks>net5.0;netcoreapp3.1</TargetFrameworks> -->
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" />
 </ItemGroup>

```

### Expected behavior

Able to multi target external nuget packages without have to multi target the solution consuming them.

@jtkech something a bit odd going on here.

Felt like it was working yesterday around lunch time(80% think I remember it being ok), then with a few more changes that went in later on it appears that the module doesn't show up in the features list anymore.

Note: This is only happening on packages built from nuget then packed to nuget.

see https://github.com/ThisNetWorks/ThisNetWorks.OrchardCore.OpenApi/pull/12

I've probably done something odd here ;)

**Comment by jtkech** [comment]
Just took a look at your package on nuget

Indeed, in your last package you have a build folder with a props file, but not in your previous one targeting both TFMs

So not related to the main app targeting or not multi TFMs, but that your package doesn't include a build folder with the `YourModule.props` file

Okay, i can repro, when a module **references `OC.Module.Targets` as a package** and targets multi TFMs, it doesn't produces a build folder with the `YourModule.props` file

I will investigate ;)

**Comment by jtkech** [comment]
Okay, i may have found why, when packing a multi TFMs project, it grabs infos in an outer build that doesnt execute the scripts under `build\` of the referenced package, i think we need to put a script under `buildMultiTargeting\`, that will get executed to just import the one under `build\`, as done in this file that is packaged under `buildMultiTargeting\` https://github.com/dotnet/aspnetcore/blob/4807bf84b5d331e3565e8b60e42e3630fbbe09c6/src/FileProviders/Embedded/src/buildMultiTargeting/Microsoft.Extensions.FileProviders.Embedded.props#L1-L3

    <Project>
      <Import Project="..\build\netstandard2.0\Microsoft.Extensions.FileProviders.Embedded.props" />
    </Project>

I was quite sure that we will have to deal with this `buildMultiTargeting` folder at some point ;)

It is specific when a project references one of our `Targets`, as a package, and when packing this project.

We don't see it in our solution as we import props file explicitly

I will check it

**Comment by deanmarcussen** [comment]
ok thanks @jtkech no rush on this issue from me, working around and just building a single target is no big problem currently. 

But if there is anything I can do, or test on that repository with any potential fix, just let me know.

**Comment by jtkech** [comment]
Okay cool, no problem

**Comment by jtkech** [comment]
@deanmarcussen 

I updated `OC.Module.Targets` to use the `buildMultiTargeting`, packing a multi TFMs module referencing `OC.Module.Targets` now produces the `build` folder. I let you retry it on your side when you will have time


I will apply the same change to our other `OC.Xxxx.Targets` projects

**Comment by deanmarcussen** [comment]
@jtkech hmm still doesn't seem to be pulling it in.

Where should I be looking for this `build` folder ?

**Comment by jtkech** [comment]
You need to reference our last packages, update your `OpenApi` module to target multi TFMs

Then re-build / re-pack and re-push it on nuget

Looking at nuget, it seems that you didn't re-pack an re-push it

Open the `.nupkg` file of your module as a zip file, and check if it includes a `build\` folder with a .props file

**Comment by deanmarcussen** [comment]
ok, sorry, what I meant was where could I see it locally before the pack?

Right now I haven't pushed anything, because the sample app, which is only targeting `core5`, still can't see the module, when I switch it to multi target.

No problem, if it will only work if I multitarget the sample app, just seemed a bit strange to have to do that.

**Comment by jtkech** [comment]
When you pack your module locally, see in the produced `.nupkg` file by opening it as a zip file

This is the module package that contains the logic to be found by an application, through a .props file under its `build` folder. The problem was that when your module was targeting multi TFMs, it was not there when packing it.

> No problem, if it will only work if I multitarget the sample app, just seemed a bit strange to have to do that.

No it should work in both cases, but currently on nuget your `OpenApi` module has a multi TFMs version but that doesn't include the `build\` folder, and the last version contains a `build\` but only support one TFM

**Comment by jtkech** [comment]
> Right now I haven't pushed anything, because the sample app, which is only targeting core5, still can't see the module, when I switch it to multi target.

Oops okay, maybe another use case, need more thinkings

**Comment by jtkech** [comment]
Just need to try this scenario, can't right now as i'm upgrading Visual Studio, will do it toonight

**Comment by jtkech** [comment]
Hi @deanmarcussen 

Just tried your use case, it works on my side

So i created a web app project referencing `OC.Application.Cms.Targets` as a package
A module project referencing `OC.Module.Targets` as a package, and targeting both frameworks
Then i referenced the module project in the web app project, as a project

Then i tried with the web app targeting both TFMs, and then only one net5.0, is this last test your use case?

In both case it works, the module features are shown in the admin

When changing the TFM / TFMs, maybe you need to clear some bin / obj folders where it cache the targets that need to be used from the referenced packages.

**Comment by deanmarcussen** [comment]
> and then only net5.0, is this last test your use case?

Yes this was the use case (not an especially important one tbf)

So `git -xfd` just to be sure

What works
- all web app modules multitargetting, and the module multitargetting
- webapp not multitargetting, and refering to a locally packed version of the module, i.e. nuget source = `./artifacts`

What still doesn't quite work is
- webapp not multitargetting, module multitargetting, not packed, just referenced as a local project.

Is not a major for me, making the webapp multi target as well, is no pain point, it's just a bit odd

**Comment by jtkech** [comment]
> webapp not multitargetting, module multitargetting, not packed, just referenced as a local project.

This is exactly what i tried, and that worked

**Comment by jtkech** [comment]
When i tried it, i built the app from VStudio, can't right now but tonight i will try it by building from the dotnet cli

How do yo buildyour app? Do you reference your module directly from the app? If not you need `PrivateAssets="none"`

If it still works on my side, would be good that you share a testing app to repro

Or having a call on skipe tonight to see what's the difference on your side, but only if you have time ;)

**Comment by jtkech** [comment]
Okay, just tried, also works by using the donet CLI

**Comment by deanmarcussen** [comment]
Ok, thanks @jtkech 

I'm going to try in a fresh solution tomorrow and will let you know.

**Comment by deanmarcussen** [comment]
@jtkech made you a sample where I'm getting the same issue as described above

Left the `App_Data` in, but not the bin / obj files etc

user `admin`, password `Password01_`

[SampleJt.zip](https://github.com/OrchardCMS/OrchardCore/files/6096862/SampleJt.zip)

I updated sdks to make sure I was on the latest `5.0.200`

I left some comments in the `csproj` - works fine if both multitarget, but don't see it if only the module is multitargetted.

Also works fine if I publish the module, and access it as a local nuget artefact.

So just a little bit of strangeness! 

Be interesting to see if it's the same issue.

Maybe mac vs PC?

**Comment by jtkech** [comment]
@deanmarcussen Okay cool, thanks

Nothing works well these last days, i was not able to load packages from cloudsmith, so i changed the version from rc2-15923 to rc2-15925, but same problem, i had to wait 4 hours to be able to load them ;) So, just to say that i tried it but with the last version rc2-15925, not the rc2-15923 as you.

Okay i could repro with your app project, and i fixed the issue, i will push it soon.

For the `OC.Module.Targets` package, we already added a custom `OrchardCore.Module.Targets.props` under a `buildMultiTargeting` folder, in fact just to import the original one under the `build` folder, it fixed the issue when packing a module project (referencing `OC.Module.Targets` as a package), and then referencing it as a package.

Here, to fix the issue i just needed to do the same for `OrchardCore.Module.Targets.targets`, i simulated this through my local package storage, i was suspecting this but was not sure as i was not able to repro.

Note: Hmm, multi targeting modules prevents from using some methods with some new useful params, as i just saw while working on the AutoSetup PR.

**Comment by jtkech** [comment]
I merged the fix, re-open if still an issue

**Comment by deanmarcussen** [comment]
All fixed thanks @jtkech

**Comment by jtkech** [comment]
Cool, happy to know it !!!
