### ISSUE TITLE
Configuration stay on while Users Reset Password module disabled

### ISSUE THREAD

**Issue by vitalybrandes** [OrchardCMS/OrchardCore#8736]
### To Reproduce
1. Add Users Reset Password module
2. Enable both check boxes
3. Remove module
4. The selection still relevant.

### Expected behavior
Reset settings to default = disabled.

### Screenshots
![image](https://user-images.githubusercontent.com/61165619/109808723-24a50100-7c30-11eb-9498-82d68e24f736.png)

**Comment by Skrypt** [comment]
These are stored as SiteSettings so they are persisted even if we disable the feature.
What would be needed is a migration for when someone disable the feature.
Some people will like it, others won't. I'm not sure to be honest.

**Comment by deanmarcussen** [comment]
Pretty much of a duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6205

Will close, as there is a good solution on mitigating, or fixing the settings
