### ISSUE TITLE
Sort on hierarchy 

### ISSUE THREAD

**Issue by olxedew** [OrchardCMS/OrchardCore#8738]
I would like the gantt chart to sort on the hierarchy column.  it is not doing so now, I am not certain on how the gantt chart is sorting.  Any suggestion?

**Comment by hishamco** [comment]
Could you please clarify your question, what I undersand that you are talking about Gannt Chart component, how this related to OC?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
