### ISSUE TITLE
Issue with rendering of TaxonomyField

### ISSUE THREAD

**Issue by Graph2133** [OrchardCMS/OrchardCore#8743]
Hi! I am trying to render  TaxonomyField  tags in razor page but the problem is that I can not see dropdown with options.

My content part:

```
public class CarPart : ContentPart
{
public TextField Name {get;set;}
 public TaxonomyField Type { get; set; }
}
```
Car.Edit.cshtml:
```
<div> 
    @await DisplayAsync(Model.Content)
</div>
```

This view i am passing using `Initialize<T>` method from `ContentPartDisplayDriver ` `Edit `method
CarFields.Edit.cshtml:
```
@model MyNamespace.CarPart
<div> 
    <label>@Model.Name.Text</label>
    @await DisplayAsync(Model.Type.Content)
</div>
```
 I am trying to get vue-multiselect dropdown but it is just not rendered:
 
![image](https://user-images.githubusercontent.com/23173060/109892147-120fe380-7c93-11eb-89ae-966c6703bd51.png)

Is there any way to render only specific Taxonomy, Text, Datetime fields  without using placement.json file ?

**Comment by deanmarcussen** [comment]
Hmm, going to need a few more details of what you're trying to do.

I think you're trying to make a razor page?, possibly on the front end? Using a TaxonomyField?

How are you calling `BuildEditorAsync` if so?

It sounds like you might just be called the `CarPart` `Edit` method.

This would only produce the shapes for the `CarPart` not the taxonomy field.

`BuildEditorAsync` would be the entire composition of all parts / fields that make up the `ContentType`.

Let's just get a few more details on what you're trying to achieve
