### ISSUE TITLE
Admin - creating a item with a bagpart

### ISSUE THREAD

**Issue by ruisdias** [OrchardCMS/OrchardCore#8749]
### Describe the bug
The Header, in the admin area, has a z-index of 1030, so when I'm creating an item and choosing an option from a bagpart, the dropdown is appearing behind the header.
### To Reproduce
1. Go to Backoffice
2. Create an item of type with a bagpart with a lot of options
3. See the bug

### Expected behavior
The dropdown options should appear on top of everything else while choosing an option.

### Screenshots

![image](https://user-images.githubusercontent.com/27766766/109987134-453b8c80-7cfe-11eb-9f41-2e9a1ed61702.png)

![image](https://user-images.githubusercontent.com/27766766/109987199-5389a880-7cfe-11eb-8bcf-14e04ab1319f.png)

**Comment by Skrypt** [comment]
It needs a fixed height and a scrollbar.

**Comment by sebastienros** [comment]
I think we need a modal with first the same list, and then later the better lists (thumbnails + decriptions)

**Comment by agriffard** [comment]
https://www.codeply.com/go/Uh8qadr3q2/bootstrap-scrollable-dropdown-menu
