### ISSUE TITLE
Azure AD implementation using obsoleted methods in net5.0

### ISSUE THREAD

**Issue by dafergu2** [OrchardCMS/OrchardCore#8752]
While implementing multi-targeting for netcoreapp3.1 and net5.0 TFMs, it was discovered that the current Azure AD implementation in OC is using methods that have been deprecated in the latest net5.0 Azure AD libs.  The OC code was surrounded by pragmas to ignore the warnings for now, but the code still needs to be updated to use non-deprecated methods when targeting net5.0.

See: https://github.com/OrchardCMS/OrchardCore/issues/8550

**Comment by sebastienros** [comment]
To be done when we move to net6.0 and the method is removed completely.

**Comment by Piedone** [comment]
This was fixed at one point and we have no such `#pragma warning disable CS0618` cases anymore.
