### ISSUE TITLE
Test migration from RC2 to 1.0

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#8753]
And document steps in the release notes.

**Comment by deanmarcussen** [comment]
[yessql.db.zip](https://github.com/OrchardCMS/OrchardCore/files/6096904/yessql.db.zip)

As a reference point here is an RC2 database with the blog and workflows setup.

username `admin` password `Password01_`

Now to see how the upgrade goes ;)

**Comment by deanmarcussen** [comment]
Issues to resolve so far

- Fails to validate cookie when logged in, until `UserId` migration has run. Solution. Log Out first.
- `Layers` migration errors
- `UserPickerField` migration 

`while running migration version 5 for 'OrchardCore.Users'. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: UserPickerFieldIndex'.`

**Comment by deanmarcussen** [comment]
All fixed currently.

Keeping this open to retest prior to any further migration changes.

**Comment by sebastienros** [comment]
TODO: Add this discussion https://github.com/OrchardCMS/OrchardCore/discussions/9119 to the RC2 release notes

**Comment by agriffard** [comment]
Version 1.0.0 released.
