### ISSUE TITLE
Lucene index different behavior on save / rebuild

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8784]
Hi, 

I have a problem with lucene that I am not sure if its a problem with my implementation or with way that OC updates indexes. 

In short: 
I needed to create faceted search, usually I would use Elastic search, but since OC already had Lucene.Net implemented, I had decided to give it a try (so I would save some time that I would need to spend on admin UI etc.). I have found old project that does exactly what I needed but for older version of lucene.net, so I have updated it => https://github.com/aspcodenet/MultiFacetLuceneNet/pull/4

Problem:
Everything works perfect when content items are created after index is created. But on older items, it throws null reference (if you want to look at the code its in method GetFacetCountFromMultipleIndices, fails on creating DISI)

Question:
I do not expect that someone will look at the code and will try to fix it, more likely I would like to know, if there are any differences when I try to reindex whole index vs. when I save content item.

Because if I would save all content items, one by one, then it starts to work. But if I reset/rebuild index, it is still broken. 

I have tried to compare code by myself but I do not see anything that could lead me anywhere.

**Comment by Skrypt** [comment]
I'd need to understand what is the goal you are trying to achieve first. I probably need to read more about the MultiFacetLuceneNet specifications.

**Comment by MikeKry** [comment]
@Skrypt 
Thanks, I will try if that would help. Do you know number of existing issue, so I could watch it in case that is the problem?

**Comment by MikeKry** [comment]
Also index is reported as invalid, when I try to open it with Luke (but that applies to both of them).
