### ISSUE TITLE
Lucene Folders empty

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8791]
This bug is related to my experience with the appdata/lucene folder being empty.
I was suing vs2019 and using webdeploy to Azure.
I selected the check box which would alwasy delete any extra files from azure that weren't part of the publish package.
I did this on purpose because I hooked up sql azure and I wanted to see if there were any dependencies on the harddrive files.
It appears there is.
So each timeI did a publish it would delete the content sof the appdata/lucene folder.

Now naturally you would go to the index and press the rebuild button.
But this results in a page could not be found.

So to fix this bug I would say that there should be some extra code in the rebuild method which will recreate the sub folders inside of the Lucene folder if it is empty.

I also got page could not be found if I tried to delete the index or run the query.  Same reason is that the appdata/lucene folder is empty.

**Comment by Skrypt** [comment]
Fixed by #9166
