### ISSUE TITLE
Update some indexes when upgrading YesSql

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#8794]
As a reminder when we will upgrade yesSql to the version that automatically create indexes on the map / reduce index tables, related to https://github.com/sebastienros/yessql/pull/353

- For the map index tables, an index only including the `DocumentId` column will be created automatically, so we will have to remove from the migrations the indexes that also only include `DocumentId` column.

    For now i found one such index used for Autoroutes, need to check if it is the only one.

- For the reduce index tables, **for the bridge table** an index including the `Id` an the `DocumentId` will be created automatically. **For the table itself** still not sure if we can / is useful to create on our side indexes including some columns, would need to try it under sql server and see how the queries behave with or without these eventual indexes.

**Comment by jtkech** [comment]
Just started some tests, will continue tomorrow

Just tried the following query, `UserByRoleNameIndex` being created with `CreateReduceIndexTable()`

    await _session.Query<User, UserByRoleNameIndex>(u => u.RoleName == "ADMINISTRATOR").ListAsync();

That produces the following query

    SELECT DISTINCT Document.* FROM Document
    INNER JOIN UserByRoleNameIndex_Document AS UserByRoleNameIndex_Document_a1
    ON UserByRoleNameIndex_Document_a1.DocumentId = Document.Id
    INNER JOIN UserByRoleNameIndex AS UserByRoleNameIndex_a1
    ON UserByRoleNameIndex_a1.Id = UserByRoleNameIndex_Document_a1.UserByRoleNameIndexId
    WHERE UserByRoleNameIndex_a1.RoleName = 'ADMINISTRATOR'

![Query Plan 1](https://user-images.githubusercontent.com/8586360/110573183-1c325600-815b-11eb-80dc-17ba27ee76c9.png)

Adding an index on the bridge table `UserByRoleNameIndex_Document`, as yesSql will do, including `UserByRoleNameIndexId` and `[DocumentId]`, we can see at the bottom right the usage of an unclustered index

![Query Plan 2](https://user-images.githubusercontent.com/8586360/110573189-218fa080-815b-11eb-80d0-005c58a8393b.png)

Then adding an index on the table, that for now we don't for reduce index table, including the `RoleName` column, we can see the usage of another non clustered index at the top right.

![Query Plan 3](https://user-images.githubusercontent.com/8586360/110573233-30765300-815b-11eb-9751-1ef78c270348.png)


Will see tomorrow why we still use one clustered index at the bottom.

**Comment by deanmarcussen** [comment]
Did you upgrade YesSql and remove the `AutorouteIndex` @jtkech ?

I think it should be on nuget now, so I just open this again to remember to do it.

**Comment by jtkech** [comment]
> Did you upgrade YesSql and remove the AutorouteIndex @jtkech ?

Not yet

Need to leave, go to the dentist :(
