### ISSUE TITLE
Upgrade Trumbowyg to tip

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#880]
We are quite a bit behind, Lets upgrade

https://github.com/Alex-D/Trumbowyg/releases

**Comment by agriffard** [comment]
I updated Trumbowyg to version 2.8.0 in my Bootstrap 4 PR #986

I added 2 plugins : 
Colors: Allow to select background or foreground color
![image](https://user-images.githubusercontent.com/703248/30776029-366a8fd8-a09f-11e7-8a8b-182662250159.png)

Base64: Allow to add image as base64
![image](https://user-images.githubusercontent.com/703248/30776037-570421fa-a09f-11e7-9b0c-572e9aef779b.png)

Noembed: Allow to detect and add the embed code from an url
![image](https://user-images.githubusercontent.com/703248/30776060-b3381ed6-a09f-11e7-8044-f79cf04b869d.png)
