### ISSUE TITLE
Indexes with multiple records for one document

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#8805]
### Is your feature request related to a problem? 
For some scenarios we need indexes that have multiple records pointing to a document. An example could be if we define a document called productcatalog that contains all the products of a provider. Having all the products in a document helps us to load fast a complete catalog of a provider which is our most frequent use case.
Problem comes when we want to retrieve provider catalogs that contains a product with certain condition. For that we would need to create a yessql index table where it is storred a record per product in a provider catalog, to be able to search by a product property and know which different catalogs to open. So, the index will have multiple records pointing to the same document.

The work needed for storing data in the index seems expensive, so we now are going to define the index in a yessql map index table, but we are not going to register the index at startup to avoid yessql does the job of keeping the index updated when we store sth.
Instead of that we have a background process that does the job which in the future can be located in another machine). The reason it is not urgent for us this index is coherent with documents, at least we don't need it inmediately and in the same transaction.

### Describe the solution you'd like
It would be nicet Yessql supports to define that kind of indexes and also support to load a document from that kind of index without returning multiple times same document because it foundd multiple times same documentid on different records.

Furthermore it would be nice YesSql allow us to define if an index has to be sync inmediately after a change on its document, or if it has to be left to the consumer of the library the decission of when it is sync. And for the second case it would be good to have a way of requesting to yessql to sync an index table for a document, passing to that method the Id of the document. It will search for the document id, if it doesnt finds it it will act as if the doc was deleted removing records of that documentid in index table. In other case index tables will be updated with current state of the document.
Another useful thing would be yessql provide a way to patch an index like this new one type. I mean it provides methods to consumers of the library to update specific rexords of the indexes, cause the consumer code could know on some scenarios exactly which records of the index shoukd be changed and will want to update only records that need to change to make the operation more efficient.

### Describe alternatives you've considered 
For the moment we are going to define a mapindex table not registered at starup for those cases, and all the other operations are going to be done with plain SQL. And for retrieving documents based on one of those indexes we are going to execute a sql toward the index to get the documentIds and then we use yessql to load the document. So, we use two sqls for sth that could be achieved with one with an inner join and a distint if yessql woukd support these kind of indexes for retrieving documents

**Comment by Skrypt** [comment]
Have you also considered using a JSON Function simply in your SQL Query?

**Comment by jersiovic** [comment]
Well I didn't considered it , thank you for remember it to me.
However but as far as I think on it it doesn't look a very good option in performance terms cause a query like that will need to read all catalogs to look into them if they have some products.

**Comment by jersiovic** [comment]
I think it is wrong to post this issue here I should have posted it at yessql repo so I close it here and I open a new one there https://github.com/sebastienros/yessql/issues/355

**Comment by Skrypt** [comment]
https://techcommunity.microsoft.com/t5/sql-server/indexing-json-documents-in-sql-server-2016/ba-p/384456
