### ISSUE TITLE
Document Manager does not persist new documents until UpdateAsync is called

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8811]
@jtkech this is more of a question than anything else, but I'm questioning the design of the `DocumentManager` / `DocumentStore`

both `GetOrCreateMutableAsync` and the immutable version have factory methods for creating the document.

I'm using them as an initializer to consume data and then cache from an external api, so an expensive call, rather the cheap `new()`.

However because I'm never calling `UpdateAsync` on them, they are never actually persisted.

Equally if I'm using `GetOrCreateMutableAsync` as a consumer, the factory method doesn't seem to be cached, when it's initialized, which just results in more calls.

In the case here, I'll probably always be using `GetOrCreateMutableAsync`, until I have components in place to refresh (webhook).

I can call `UpdateAsync` in my factory method as a workaround, and works fine.

But when I look at in OrchardCore, things like the placement document 
(and I think the usage in the placements admin controller maybe incorrect, because for`Index` it is calling `GetOrCreateImmutableAsync` where probably there it should be `GetOrCreateMutableAsync`)

are being fetched everytime the site is restart, until they are populated with some data (I suspect if it was used correctly it would be calling `GetOrCreateMutableAsync`, and always being created, on every request, until it was persisted the first time, because it looks like factory calls there are uncached?

Sorry for the long story, hope it makes sense.

What I'm basically wondering, is if it was by design that `new()` documents would not be persisted automatically, thereby becoming the `master` document.

**Comment by jtkech** [comment]
Okay @deanmarcussen no problem, need to focus on it a little, i will check it this night

**Comment by jtkech** [comment]
@deanmarcussen 

Yes, we don't do an auto update if not yet persisted, all running instances will create (using a factory or not) a new default document (so they are implicitly in sync) which is cached in a local cache, and in a distributed one if provided, this also prevents multiple instances from doing the first time multiple database updates, just to store a default document.

`GetOrCreateImmutableAsync()` is to get read only data that are cached if not yet done, `GetOrCreateMutableAsync()` is to get mutable data before an update, and that are not cached, the usage in the placements controller looks good.

By caching i mean setting data in the local memory, memory cache, distributed cache and so on, but here, what you call caching is to persist in the database some data coming from another source by using an expensive call.

The document manager keeps in sync a multi level cache with a store (e.g. database) that here is not one of the caches, you would need a doc manager where the store is your external source, and the database would be one of the caches ;)

So for me that's okay with the `DocumentManager`.

Yes, using the factory is a good idea as it is called if the document is not yet cached / persisted, but need to check if calling the update in the factory is okay, i think it fails if the factory is called on a `GetOrCreateImmutableAsync()`, hmm but why not using this solution through a `GetOrCreateMutableAsync()`, as i think you did.

But maybe better to use a separate service (auto loader / updater) that would still use the `DocumentManager` (but with no factory) to check if it is not yet cached / persisted, and if so load the document from the external source and then update it in the database store by still using the `DocumentManager`.

**Comment by deanmarcussen** [comment]
@jtkech 

Ok, cool, just checking it's by design, and I understand the potential pain of trying to persist them at that point.

When I see a factory `Task` I assume I can do anything long running in it ;)

But yes I will probably approach this with a loader / migration / activating event to do the long running initialization.

Just checking we weren't missing something we should have :)

Cheers
