### ISSUE TITLE
Edit layer

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#8812]
When I edit a layer and the Rules module is not enabled, there is an error:
`Exception: Shape type 'Rule_Summary' not found`

Enabling the feature fixes the problem.

**Comment by deanmarcussen** [comment]
There's a migration which should have enabled the `Rules` module.

Can you check in your logs to see if you had an issue, or describe better how you didn't have the feature enabled? i.e. custom setup recipe, or ...?

**Comment by agriffard** [comment]
Nothing in the logs. 
Only on the default instance (maybe because it was the one on which I tried the Rules module first before merge), worked for the tenants.
