### ISSUE TITLE
Wechat/qq/weibo login plugin is Needed

### ISSUE THREAD

**Issue by SpikeXy** [OrchardCMS/OrchardCore#8819]
Now many chinese websites have implemented wechat/qq/weibo login, maybe it also needs to do one, just like twitter.

**Comment by hishamco** [comment]
IMHO this is special for certain country, this is good as open source module. If you are interested in this you can add in Orchard Core Contribute repo

**Comment by sebastienros** [comment]
Agreed, we suggest you create a community module for it. Ideally available on NuGet.
