### ISSUE TITLE
Liquid and accented characters

### ISSUE THREAD

**Issue by serverside-is** [OrchardCMS/OrchardCore#8829]
### To Reproduce
Steps to reproduce the first problem:
1. Create a new site with the Blog recipe (I'm using the dev branch, and SQL Server)
2. Change the Title of the blog post "Man must explore, and this is exploration at its greatest" to "École". It's important that _the first_ character is accented.
3. View the site homepage (/)
4. Boom. `ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')`

Steps to reproduce the second problem:

5. Change the blog post name again, to "L'École" (just to notice that, for this second problem, the accented character can be at any position)
6. Open the blog post page (/blog/post-1)
7. Refresh the page (F5), many times
8. You will notice that, on ocasion, instead of "L'École", you will see "LL"

I noticed the first problem after creating a taxonomy item called "Órgãos da Federação". Took me half the afternoon to understand that the problem only occurred when _the first_ character of the title was accented. Noticed the second problem by pure chance.

**Comment by deanmarcussen** [comment]
Can you include a full stack trace (and if you have time try with yesterdays release, as it took Fluid 2.0)

Though I am not sure if this is fluid related.

**Comment by hishamco** [comment]
I will try to reproduce this after megre Fluid 2.0

**Comment by hishamco** [comment]
@serverside-is I check it in the latest bits, the exception is go away

![Blog](https://user-images.githubusercontent.com/3237266/110946190-a3481f80-834f-11eb-824c-dc47e1375ca4.png)

**Comment by serverside-is** [comment]
Looks like I spoke one day too soon!

With Fluid 2.0, I am not able to reproduce any of this problems anymore. They are both gone.
