### ISSUE TITLE
Remove all migration code from pre-1.0

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#8830]
Any migration to 1.1 should assume that the current code is updated to 1.0 already. Any previous migration code to 1.0 can then be removed.

Example:
As soon as 1.0 has shipped, the dev branch (1.x) can squash all the migration steps to only "Create", and will then have a single `MigrateFromX` based on what X was at the time of 1.0.

**Comment by jtkech** [comment]
As a reminder,

Special case for migrations (created at some point) but where `Create()` is used as a 1st step, e.g. in `OC.Media`

        // This migration does not need to run on new installations, but because there is no
        // initial migration record, there is no way to shortcut the Create migration.
        public int Create()
        {
            _contentDefinitionManager.MigrateFieldSettings<MediaField, MediaFieldSettings>();

            return 1;
        }

Better to keep it for version consistency, but with an empty `Create()`

        public int Create()
        {
            return 1;
        }

**Comment by deanmarcussen** [comment]
> Better to keep it for version consistency, but with an empty Create()

Agree. Not having that caused the above issue.

**Comment by Piedone** [comment]
This isn't applicable anymore, right? The Media module has this done, any other examples?
