### ISSUE TITLE
Available rules modal in Layers JS issue

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#8834]
### Describe the bug
Looking for hints as to why this might be happening as I think it might be unique to me - the new "available rules" dialog is popping up but the filter and "add" buttons do not work as there is a JS error. When I look at the HTML the script tags are rendering the like `<script at="Foot" depends-on="jQuery">` and they are not being placed in the correct location which is the issue.

This happens no where else on the site and strangely it doesn't happen when running locally.

I am on version 1.0.0-rc2-15876

**Comment by jtkech** [comment]
I think it has been fixed through #8677

**Comment by scleaver** [comment]
Ahhhh I searched for a fix too!

**Comment by Piedone** [comment]
Fixed in https://github.com/OrchardCMS/OrchardCore/pull/8677.
