### ISSUE TITLE
Liquid logical expression are broken

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#8835]
`a == b and c == d` doesn't respect operator precedence that `a==b`  and `c==d` should be evaluated before `and`.
This is due to a misinterpretation of the fact that operators are evaluated from right to left in liquid.

**Comment by sebastienros** [comment]
Just released 2.0.0-beta-9, can someone create a PR and merge? I am going to bed ;)

**Comment by jtkech** [comment]
I'm doing it before going to the dentist ;)
