### ISSUE TITLE
Culture switching issue

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#8844]
@Skrypt I notice I strange behavior, while I'm trying to switch from culture to another, what I have is 2 cultures: `ar` and `en-US`, when I set the default culture to Arabic, no matter I changed to another culture later the OC still show the OC with Arabic culture, did you notice this bahvior?

I will try to fix it there's a bug

**Comment by hishamco** [comment]
BTW removing Arabic culture make things right ;) which is weird

**Comment by Skrypt** [comment]
Could be related with Fluid 2.0

**Comment by hishamco** [comment]
I don't think so, I remember I notice same behavior before, but I forgot to report it ;) anyhow I will check what's going on

**Comment by jptissot** [comment]
It may be a sync issue with the cookie and the content ? Are you in the English admin and going to a Arabic content page then trying to switch ? If yes, there is an issue where the cookie is not synced properly because the ContentCultureProvider does not set it.

**Comment by hishamco** [comment]
Ooh I forgot to ping you @jptissot ;)

I'm expecting it's a cookie issue as you mentioned, but even you didn't enable the Content Localization the issue is happening

**Comment by Skrypt** [comment]
Try to check which culture is set in your browser config too to figure it out. Maybe it's showing the proper culture because english is prioritary in your browser cultures.

**Comment by hishamco** [comment]
> Maybe it's showing the proper culture because english (en) and/or (en-US) is prioritary in your browser cultures.

The problem it shows Arabic all the time ;) I will try to invistegate on that after finishing the Dark Mode PR

**Comment by hishamco** [comment]
The main issue comes from browser languages, I remembered I added Arabic & French while testing localization support in Oqtane, but I forgot to delete them ;), AcceptLanguageHeaders have precendency over cookie once
