### ISSUE TITLE
Facebook -- ScriptsMiddleware should always passes.

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#8854]
### Describe the bug
if return, ScriptsMiddleware will terminate other middlewares.
### To Reproduce
2. Click on '...'
3. Scroll down to '...'

### Expected behavior
ScriptsMiddleware should always passes next to other middlewares

**Comment by Piedone** [comment]
See JT's reply here: https://github.com/OrchardCMS/OrchardCore/pull/8855#issuecomment-799529945. This doesn't look like an issue, nor the fix is applicable. Please reopen an explain in detail, following the issue template, what the problem you see is.
