### ISSUE TITLE
OpenID Background Task throwing exceptions

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8856]
### Describe the bug

The OpenID Background Pruning Task is currently throwing exceptions, due to a missing feature in the YesSQl.IsIn<TIndex> extensions, and support for collections.

Related YesSql issue https://github.com/sebastienros/yessql/issues/359 and pr is in.

@kevinchalet @jtkech just to keep everyone in the loop :)

**Comment by jtkech** [comment]
Okay
