### ISSUE TITLE
The liquid user filters are not resolved

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#8862]
Try using the liquid filter  :  {{ User | user_id }}
It returns null.

Seems like this line below does not return a claimsrpincipal an exits

https://github.com/OrchardCMS/OrchardCore/blob/47da5ec7c1a984f3ec545dee4c04d3b9b7f5e5c6/src/OrchardCore.Modules/OrchardCore.Users/Liquid/UserFilters.cs#L26

Similarlly it is not possible to access the properties of the user because this line has been commented out.

https://github.com/OrchardCMS/OrchardCore/blob/47da5ec7c1a984f3ec545dee4c04d3b9b7f5e5c6/src/OrchardCore.Modules/OrchardCore.Users/Startup.cs#L241

**Comment by Skrypt** [comment]
This one needs a PR quick.

**Comment by jtkech** [comment]
@giannik Not so simple ;)

@Skrypt I could get it working but in a way that may need to be discussed

I will suggest a PR soon to show why it's not so simple

**Comment by Skrypt** [comment]
Yeah, I think the focus this week should be on fixing these Liquid issues reported by people since we just merged Fluid 2.0.
I almost made plan to work on the Data Localization branch this week 😉 🙊

**Comment by hishamco** [comment]
> I almost made plan to work on the Data Localization branch this week 😉 🙊

I planned to that too, but still I'm not sure if you want to do it for your own purpose or OC?
