### ISSUE TITLE
Order of Fields and Parts

### ISSUE THREAD

**Issue by kdubious** [OrchardCMS/OrchardCore#8877]
In the Content Type Editor:
![image](https://user-images.githubusercontent.com/9756166/111214977-f79a0c00-85a8-11eb-8253-1a4d7014f157.png)

In the Content Item Editor:
![image](https://user-images.githubusercontent.com/9756166/111215102-20220600-85a9-11eb-8155-6141b5737a97.png)

What do we think about having both use the same order?

**Comment by agriffard** [comment]
By default, the fields are rendered where the `NameOfYourContentType` is placed in the Parts (which does not appear in your screenshot).

**Comment by deanmarcussen** [comment]
Note: there are actually draggable.

If you dragged the `NameOfYourContentType` to the top of the list (as @agriffard says it's not visible on your screen shot) then the fields would appear first. 
Fields being contained in the `NameOfYourContentType` part.

**Comment by kdubious** [comment]
Thanks, I didn't realize that!
