### ISSUE TITLE
Liquid don't resolves Model.Classes in widgets

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/OrchardCore#8898]
### Describe the bug
Trying to update an existing site to latest dev, `Model.Classes` expression is evaluated to `NilValue` in widgets, wheras it's a widely used pattern in templates :
```liquid
<article class="{{ Model.Classes | join: " " }}">
...
</article>
```

It seems to be a property white-listing issue since `Model` and `Model.ContentItem` are correctly evaluated.

**Comment by jtkech** [comment]
If i have time i will try to see why

**Comment by TFleury** [comment]
It took me a long time but I found the reason. It was broken by the upgrade to Fluid 2.0.

In Fluid, Shape and ZoneHoldings uses `ShapeAccessor` which doesn't map all properties (ie: Id, TagName, HasItems, Attributes and Classes)

The update removed this in LiquidViewTemplate :
```cs
if (model != null)
  {
    context.MemberAccessStrategy.Register(model.GetType());
  }
```
and which granted access to all members without using `ShapeAccessor`.

I think it was accidentally working before the update, and that we have to add the property mappings to `ShapeAccessor`.

**Comment by hishamco** [comment]
@sebastienros seems a new issue broken by Fluid 2.0 upgrade ;)

**Comment by jtkech** [comment]
Yes, it has been removed

I remember when i added these lines of code at some point, so that we don't need to map all needed props

But maybe the right usage is that we should map them to be able to restrict the other ones

If so, yes we have to update these missing mappings

**Comment by TFleury** [comment]
@jtkech could you check #8905 ?

**Comment by jtkech** [comment]
@TFleury Okay no problem, will do it soon ;)
