### ISSUE TITLE
Upgrade popper to v2

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8902]
https://github.com/popperjs/popper-core

https://github.com/twbs/bootstrap/pull/31178

We should update to V2 now too.

**Comment by agriffard** [comment]
I usually try to stick to the example BS gives in their docs: 
https://getbootstrap.com/docs/4.6/getting-started/introduction/#separate
So I kept 1.16.1 for the moment.

**Comment by Skrypt** [comment]
Ok, nothing urgent. Just trying to see if it's been merged in the current latest BS version or not.
Seems like there is some PR that got merged in their **_main_** branch but maybe it's WIP on 5.0 version. Need to figure out.

**Comment by Skrypt** [comment]
Will be update as part of Bootstrap 5
