### ISSUE TITLE
Searching DisplayText with Lucene StandardAnalyzer does not remove hyphens or punctuation

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#8906]
### Describe the bug
As described here https://lucene.apache.org/core/3_0_3/api/core/org/apache/lucene/analysis/standard/StandardTokenizer.html, the StandardAnalyzer:
- Splits words at punctuation characters, removing punctuation. However, a dot that's not followed by whitespace is considered part of a token.
- Splits words at hyphens, unless there's a number in the token, in which case the whole token is interpreted as a product number and is not split.
- Recognizes email addresses and internet hostnames as one token.

This is working on TextFields, but not on DisplayText.
Or maybe I'm missing a configuration?

### To Reproduce
Create a content item with "Orchard-Core" as the DisplayText.
Run the lucene query:

> {
>   "from": 0,
>   "size": 10,
>   "query": {
>     "simple_query_string": {
>       "analyze_wildcard": true,
>       "fields": [
>         "Content.ContentItem.DisplayText.Normalized"
>       ],
>       "query": "core*"
>     }
>   }
> }

No results match.
Although if you use a text field, it will return results.

Can check my fork here with failing test:
https://github.com/mariojsnunes/OrchardCore/blob/a4e21018b17931acdd634176ae7f82e07886b7ec/test/OrchardCore.Tests/Apis/Lucene/LuceneQueryTests.cs#L164

### Expected behavior
Should find results

Maybe a solution would be having "Content.ContentItem.DisplayText.Normalized" punctuation removed? As I understand, the only difference between that and the non "normalized" version is that it's lower case?

**Comment by Skrypt** [comment]
Will take a look at it tonight.

**Comment by Skrypt** [comment]
![screencapture-localhost-5001-Admin-Lucene-Query-2021-03-18-17_13_02](https://user-images.githubusercontent.com/3228637/111698446-38925a80-880d-11eb-9c9d-0d7524689dd6.png)

From a first test the **Content.ContentItem.DisplayText.Normalized** field is removing accents and making it lowercase.

**Comment by Skrypt** [comment]
Seoncd test here : 

![image](https://user-images.githubusercontent.com/3228637/111699006-ed2c7c00-880d-11eb-9a4c-8e7c323341dc.png)

**Comment by mariojsnunes** [comment]
On the 3rd test, try searching for eaun

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/111703178-a5105800-8813-11eb-88e2-ac968d9a9337.png)

Of course searching for only "eaun" would fail. We need to put a wildcard before then. "*eaun"

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/3f6631b606cfc1b3a6bdb2ff41929abcdea0d6c4/src/OrchardCore.Modules/Orch
ardCore.Contents/Indexing/AspectsContentIndexHandler.cs#L30-L43

Content.ContentItem.DisplayText is a stored field.
Content.ContentItem.DisplayText.Normalized is a stored and normalized (lowercase and no diacritics) field.
Content.ContentItem.DisplayText.Analyzed is an analyzed (tokenized) field.

**Comment by mariojsnunes** [comment]
Ah it works using Content.ContentItem.DisplayText.**Analyzed** !
Didn't know this field existed, great! :)
This should be documented somewhere

> Of course searching for only "eaun" would fail. We need to put a wildcard before then. "*eaun"

Yeah because Normalized doens't split hyphens or punctuation like I was expecting.
Will close this then. Thanks!
