### ISSUE TITLE
Inspect and fix Microsoft Edge (Chromium) issues.

### ISSUE THREAD

**Issue by kdubious** [OrchardCMS/OrchardCore#8912]
Missing x-content-type-options :

![image](https://user-images.githubusercontent.com/9756166/111789558-a84d2780-8897-11eb-8b31-ceef0446b4eb.png)

**Comment by Skrypt** [comment]
Ok let's open up a single issue for these that says. Inspect and fix Microsoft Edge (Chromium) issues.
We need to list them.

**Comment by kdubious** [comment]
1. A 'cache-control' header contains directives which are not recommended: 'no-store'
2. A 'cache-control' header contains directives with invalid values: 's-max-age=31557600'
3. A 'set-cookie' header doesn't have the 'httponly' directive.
4. Response should include 'x-content-type-options' header.
5. The 'Pragma' header should not be used, it is deprecated and is a request header only.
6. The 'server' header should only contain the server name.
7. Response should not include disallowed headers: x-powered-by [ignore]

**Comment by sebastienros** [comment]
Where is that list of issues/recommendations coming from?

Also I read recently that `x-apple-orange` is not recommended anymore, and that we should just use `apple-orange`

**Comment by kdubious** [comment]
@sebastienros, it's coming from me. And I am getting it from the "Issues" tab in "Edge."

https://webhint.io/

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/111819243-7f885a80-88b6-11eb-91cf-aa809825ae4d.png)
