### ISSUE TITLE
Shortcode only works once

### ISSUE THREAD

**Issue by NogginBox** [OrchardCMS/OrchardCore#8914]
### To Reproduce
1. Create a test shortcode ```[lorem]``` that just replaces itself with ```<strong>lorem ipsum ...</strong>```
2. Create some content with a HTML body and use that shortcode more than once. Something like:
```
<p>Here is [lorem]</p>
<p>And some more [lorem]</p>
<p>And even more [lorem]</p>
```

### Expected behavior
In the final content all the [lorem] shortcodes will be replaced.

### Actual
Only the first [lorem] is transformed. If there are two different shortcodes and more then one of each, then only the first of both will be rendered correctly.

**Comment by hishamco** [comment]
@NogginBox is `[lorem]` a custom shortcode if yes, please show us your code

**Comment by NogginBox** [comment]
@hishamco it's one I created in /admin/shortcodes/ to test this bug.

**Name:** lorem
**Content:** <strong>lorem ipsum ...</strong>

**Comment by hishamco** [comment]
I may need to create a unit test for testing this, may be it's a shortcode bug

**Comment by Skrypt** [comment]
I just tried with a Liquid template and the shortcode doesn't work at all.

**Comment by hishamco** [comment]
Nah, seems this is another Fluid issue ;)

**Comment by hishamco** [comment]
@Skrypt @NogginBox said the first occurance replaced successfully, but what you show off ensure that the shortcodes don't works at all

**Comment by Skrypt** [comment]
@hishamco This doesn't work either : 

https://github.com/OrchardCMS/OrchardCore/blob/37459b27a7437d398998e521a650a65172db6b3e/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/OrchardCoreBuilderExtensions.cs#L73-L95

**Comment by jtkech** [comment]
I think they are all related to objects that were added to the liquid scope dynamically through `ILiquidTemplateEventHandler`. And that now are added globally to a Scope options through a custom liquid accessor which needs to define how to access the properties

In the above example maybe we are just missing the Scope options `o.Scope.SetValue("HttpContext"`, and maybe also `o.Scope.SetValue("Request")` with its related custom accessor


I will try to check all of them this night
