### ISSUE TITLE
Liquid Culture tag is empty

### ISSUE THREAD

**Issue by jan-chvojka** [OrchardCMS/OrchardCore#8915]
I have just updated to latest version of nuget packages (commit 37459b27) and noticed that liquid tag {{ Culture.Name }} returns nothing. I tested it with clean cloned repo of dev branch with Agency Theme.

### To Reproduce

1. Clone dev branch and run project OrchardCore.Cms.Web.
2. Setup Agency themed site.
3. Look to html source of the homepage. 
4. See that **html lang attribute** is empty.

### Expected behavior
There should be code of current culture.

**Comment by hishamco** [comment]
I will test this one too, with #8914

**Comment by hishamco** [comment]
@jtkech seems this related to #8914

**Comment by jtkech** [comment]
Maybe, will check it this night ;)
