### ISSUE TITLE
Convert IHtmlContent to FluidValue

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#8918]
Register a Fluid converted that will transform an IHtmlContent to a FluidValue in order to be able to render and instance like `{{ myHtmlContent }}`.

c.f. discussion in this PR https://github.com/OrchardCMS/OrchardCore/pull/8908 related to this issue https://github.com/OrchardCMS/OrchardCore/issues/8021

**Comment by jtkech** [comment]
As a reminder a copy of my coment in the related PR

> One solution would be to make `Shape.Metadata.ChildContent` both an `IHtmlContent` and an `IShape` as the `PositionWrapper` is. But yes, `Shape.Metadata.ChildContent` is not an `IShape`, so looks better to have a filter / converter.

> Note: From memory we already have a fluid value that is an `IHtmlContent` => `HtmlContentValue`

Maybe i will do it this night while working on other liquid accessors ;)
