### ISSUE TITLE
Test upgrade from RC2 with Shortcodes

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#8942]
Reported on gitter

When upgrading from RC2 the shape type `ShortcodesModal` is not found.

I had thought this was related to the renaming, but I suspect it is because the html editors now depend on shortcodes.

But when upgrading (i.e. on site startup) the site does not recheck it's dependencies.

I suspect we just need a migration, similar to what was done for layers / rules to enable the feature.

Need to check it for the content fields, html body part, and markdown body part probably.

So it might be a couple of migrations, just to be sure that each module activates the shortcodes feature.

Will check.

**Comment by jtkech** [comment]
Yes, as we have auto migrations we could have an auto update based on new dependencies

But not sure yet when it needs to be done, e.g. at the beginning or at the end of the shell activation

Needs more thinkings ;)
