### ISSUE TITLE
Bad Link: https://docs.orchardcore.net/en/dev/docs/reference/modules/SQL/README.md

### ISSUE THREAD

**Issue by kdubious** [OrchardCMS/OrchardCore#8943]
https://docs.orchardcore.net/en/dev/docs/reference/modules/SQL/README.md

**Comment by agriffard** [comment]
It should now be: https://docs.orchardcore.net/en/dev/docs/reference/modules/SQLIndexing

Where do you still have this link?

**Comment by kdubious** [comment]
@agriffard https://docs.orchardcore.net/en/dev/docs/topics/search/
