### ISSUE TITLE
Trumbowyg - resizimg plugin

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8959]
### Describe the bug
Resizimg plugin is not working = does not resize, on click and blur makes image disappear, I think it could be related to PR #7774

On project older than this PR, it works OK.

### To Reproduce

Use latest version of OC, create trumbowyg editor, add image, try resize

### Screenshots
After clicking on image / trying to resize
![image](https://user-images.githubusercontent.com/52829889/112304976-6e689080-8c9e-11eb-980d-5460e4e0ca13.png)

**Comment by agriffard** [comment]
Duplicate of #6864

Waiting for PR merge on Trumbowyg repo: https://github.com/Alex-D/Trumbowyg/pull/1192

**Comment by MikeKry** [comment]
hm, tried to search for it at first but I didn't find it.. 

thanks for info, closing duplicate
