### ISSUE TITLE
Fluid 2.0 issues

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#8965]
I got around to trying to Update our codebase to the latest version, which contains the fluid 2.0 update.

Here is the PR https://github.com/StatCan/StatCan.OrchardCore/pull/209 

### An exception of type 'System.ArgumentException' occurred in StatCan.OrchardCore.DisplayHelpers.dll but was not handled in user code: 'UrlHelper missing while invoking 'return_url''

Code is [here](https://github.com/StatCan/StatCan.OrchardCore/blob/2f2e70bc062026a69bcdabb1b43e84774c7a0a1a/src/Modules/StatCan.OrchardCore.DisplayHelpers/Filters/ReturnUrlFilter.cs#L20), usage is in one of our [custom ViewForms](https://github.com/StatCan/StatCan.OrchardCore/blob/a6dce56812c9d64d09c2e5ed3e7f39ac02e4f07c/src/Modules/StatCan.OrchardCore.Hackathon/Recipes/ChallengeSubmissionForm.recipe.json#L63)

### System.Exception: Shape type 'Brand' not found
https://github.com/StatCan/StatCan.OrchardCore/pull/209/checks?check_run_id=2186396514#step:7:135

###  System.Exception: Failed to parse liquid file /Areas/StatCan.OrchardCore.Hackathon/Views/Widget-TeamDashboardWidget.liquid: Invalid 'if' tag at (1:6)

https://github.com/StatCan/StatCan.OrchardCore/pull/209/checks?check_run_id=2186396514#step:7:807

**Comment by jptissot** [comment]
I will update the description / comment when I find additional issues.

**Comment by deanmarcussen** [comment]
The `UrlHelper` is not longer on the ambient values

Here's an example of how to use it now.
 https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ContentLocalization/Liquid/SwitchCultureUrlFilter.cs

**Comment by sebastienros** [comment]
`Invalid 'if' tag at (1:6)`

Check the liquid, it's not valid I assume, like don't use "&&", only `and` and `or`, and no `!variable`. Also no parenthesis.

If you can't find please share the full tag usage.

**Comment by jptissot** [comment]
> `Invalid 'if' tag at (1:6)`
> 
> Check the liquid, it's not valid I assume, like don't use "&&", only `and` and `or`, and no `!variable`. Also no parenthesis.
> 
> If you can't find please share the full tag usage.

Was this working before but no longer works ?

**Comment by sebastienros** [comment]
Fluid 2 ~~breaks~~ fixes it. It's not valid Liquid.

**Comment by jptissot** [comment]
@sebastienros Is this syntax valid liquid (especially the elsif)

```
<v-container >
  <v-card-text>
    <v-row justify="center">
      <v-col cols="8">
        <h1>[locale en]Volunteer registration[/locale][locale fr]Enregistrement des volontaire[/locale]</h1>
      </v-col>
{% if User.Identity.Name == null %}
      <v-col cols="8">
        [locale en]Please <a href="{{ '~/login' | return_url }}">login</a> before registering to this event[/locale]
        [locale fr]Veuillez vous <a href="{{ '~/login' | return_url }}">connecter</a> avant de vous enregistrer a cet événement[/locale]
      </v-col>
{% elsif User | is_in_role: "Volunteer" %}
      <v-col cols="8">
        [locale en]You are already registered to this event[/locale]
        [locale fr]Vous êtes déjà enregistré a cet événement[/locale]
      </v-col>
{% else %}
      <v-col cols="8">
        <validation-provider name="{{ "firstNameLabel" | localize }}" rules="required" v-slot="{ errors, valid }">
          <v-text-field name="firstName" v-model="firstName" :success="valid" :error-messages="errors" filled="filled" label="{{ "firstNameLabel" | localize }}"></v-text-field>
        </validation-provider>
      </v-col>
      <v-col cols="8">
        <validation-provider name="{{ "lastNameLabel" | localize  }}" rules="required" v-slot="{ errors, valid }">
          <v-text-field name="lastName" v-model="lastName" :success="valid" :error-messages="errors" filled="filled" label="{{ "lastNameLabel" | localize }}"></v-text-field>
        </validation-provider>
      </v-col>
      <v-col cols="8">
        <validation-provider name="{{ "emailLabel" | localize }}" rules="required|email" v-slot="{ errors, valid }">
          <v-text-field name="email" v-model="email" :success="valid" :error-messages="errors" filled="filled" label="{{ "emailLabel" | localize }}"></v-text-field>
        </validation-provider>
      </v-col>
      <v-col cols="8">      
        <p>{{ "languageLabel" | localize }}</p>
        <v-radio-group name="language" v-model="language" row >
          <v-radio label="{{ "languageEnglishLabel" | localize }}" value="en" ></v-radio>
          <v-radio label="{{ "languageFrenchLabel" | localize }}" value="fr" ></v-radio>
          <v-radio label="{{ "languageBothLabel" | localize }}" value="both" ></v-radio>
        </v-radio-group>    
      </v-col>
        <v-col cols="8">
          <v-alert type="success" v-if="form.successMessage">
            {% raw %}{{ form.successMessage }}{% endraw %}
          </v-alert>
          <v-alert type="error" v-if="form.serverValidationMessage">
            {% raw %}{{ form.serverValidationMessage[0] }}{% endraw %}
          </v-alert>
        </v-col>
        <v-col cols="8">
    	  <v-btn type="submit" depressed block @click="formHandleSubmit" :disabled="form.submitting">[locale en]Register[/locale][locale fr]S'enregistrer[/locale]</v-btn>
        </v-col>
{% endif %}
    </v-row>
  </v-card-text>
</v-container>

```

Moving the `User | is_in_role: "Volunteer"` in an assign statement and using the variable fixes the display issue. 
No exception is thrown and nothing is displayed on the frontend.

**Comment by jtkech** [comment]
Also, i think you have to use `User.Name` in place of `User.Identity.Name`

**Comment by jptissot** [comment]
@jtkech I am pretty sure we still need `User.Identity.Name` https://github.com/OrchardCMS/OrchardCore/blob/11ce349db32e5eff496140b84d6817ced6846370/src/OrchardCore.Modules/OrchardCore.Users/Startup.cs#L241

**Comment by jptissot** [comment]
System.Exception: Shape type 'Brand' not found
https://github.com/StatCan/StatCan.OrchardCore/pull/209/checks?check_run_id=2186396514#step:7:135

This was an invalid use of the `{% shape %}` tag. We were calling the Brand shape with the ContentItem type. Now I simply call the ContentItem shape with the alias and let the DisplayManager call the right template for the shape.

**Comment by jtkech** [comment]
> @jtkech I am pretty sure we still need User.Identity.Name

Oops you're right, and i updated it recently ;)
