### ISSUE TITLE
{% script ... %} within a Liquid widget is not rendered at all

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#8970]
We have a page where there is a content (a Paragraph widget) and a script (within a Liquid widget). The Liquid widget starts with a `{% script %}` tag in order to load a js library that is only needed in this particular page (there is no need to include it in all pages of the site):

![image](https://user-images.githubusercontent.com/6704109/112501180-50c42580-8d89-11eb-8302-efde37b2a22e.png)

We have this `vendor-uaparser` declared with `DefineScript` in `ResourceManagementOptionsConfiguration`:

```
// https://cdnjs.com/libraries/UAParser.js
_manifest
    .DefineScript("vendor-uaparser")
    .SetUrl("~/myTheme/vendor/ua-parser/0.7.23/ua-parser.min.js", "~/myTheme/vendor/ua-parser/0.7.23/ua-parser.js")
    .SetCdn("https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.23/ua-parser.min.js", "https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.23/ua-parser.js")
    .SetCdnIntegrity("sha512-5gjoQXsBQsm4QreUg5isPzOlXKMTjsWYv6ijaT691hNfUKK2rdpL7oMFzp7Px65avCEx2HIuxgR0U0bMAJIANA==", "sha512-/8yVMB5bgQfbg4OrhpH4DvIFYw+m7q2nJPhJ1J2vILYn6mdJiA4600SmeQE/SfNwreOZEceAsoey4lN30RGxpg==")
    .SetVersion("0.7.23");
```

When this page is rendered, the `ua-parser.js` script is not included at all in the html being generated:

![image](https://user-images.githubusercontent.com/6704109/112502044-042d1a00-8d8a-11eb-85cb-6d5b1d0ce866.png)

Please note the `<!-- Script Begins--><!--Script Ends-->` placeholders with nothing in between.

We have also tried using:
`{% script name:"vendor-uaparser", src:"https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.23/ua-parser.min.js" %}`
instead, with the same results (the script tag is not rendered).

We are using OC 1.0.0-rc2-16014.

This worked in version 1.0.0-rc2-15878.

**Comment by deanmarcussen** [comment]
@jagbarcelo have you tried specifying an `at` location?

By default I would have expected it to turn up at the foot of the page, not inline, as your `<!-- script begins` is suggesting.

And / or have you looked to see if it is being rendered later in the footer?

(the default behaviour may have changed since Fluid 2, in terms of location.)


There are some todos left on the scriptblock tag, which we need to get too.

@sebastienros did you say you knew what the solution for those was now? 

https://github.com/OrchardCMS/OrchardCore/blob/508c9c55f96903173f30fdcb88d0e4a17b7733e5/src/OrchardCore.Modules/OrchardCore.Resources/Liquid/ScriptTag.cs#L199-L220

**Comment by jagbarcelo** [comment]
> @jagbarcelo have you tried specifying an `at` location?

Yes, we tried with `at` with `Inline` too, as https://docs.orchardcore.net/en/dev/docs/reference/modules/Resources/#specify-location suggests:
`{% script name:"vendor-uaparser", at:"Inline" %}`
with same results.

> And / or have you looked to see if it is being rendered later in the footer?

No, it is not rendered at the footer either.

As a final test, we combined the use of the `at` location and `src` too and in this case it worked fine:
`{% script name:"vendor-uaparser", at:"Inline", src:"https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.23/ua-parser.min.js" %}`

![image](https://user-images.githubusercontent.com/6704109/112516290-67717900-8d97-11eb-8905-626327fe696d.png)

But as I said, if we do not specify the `src` too it simply does not pick it from `ResourceManagementOptionsConfiguration` properly. Something around there needs some fixing.

**Comment by jtkech** [comment]
@jagbarcelo 

Yes, as @deanmarcussen said, the related lines are currently commented out, so it can't work

I will check it this night

**Comment by jtkech** [comment]
@jagbarcelo 

Sorry, didn't have enough time to look at it, will see tomorrow

Yes, for the script and style tags we were using a bridge from the related razor `TagHelper`, now there are fully liquid tags

And just remembered that they don't support yet child content block and all cases with the `Inline` location

But for these use cases you can still use the bridge from razor with a little different syntax, from memory

    {% helper "script", name:"vendor-uaparser", at:"Inline" %}

    // For a child content block
    {% block "script", at:"Foot" %}
      var test = "hello";
    {% endblock %}

**Comment by deanmarcussen** [comment]
@jtkech @jagbarcelo 

looks like it is working with 
`{% script name:"vendor-uaparser", at:"Inline", src:"https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.23/ua-parser.min.js" %}`

So probably we just need to look at the src/name if's and get them consistent.

I think `at:inline` should always be required to render inline. @jtkech I know there may have been some variance there between how the liquid blocks behaved and the razor tags, in terms of a default location. Best they come together in terms of behaviour I think.

In an ideal world some code sharing between the tag helper and these filters, as they are difficult to get right / consistent when we have been adding features to them :)

**Comment by jtkech** [comment]
@deanmarcussen 

Yes i agree, i was too lazy to take a deeper look ;) also because of some other issues to fix

So for now i only suggested these workarounds, but yes should be checked afterwards
