### ISSUE TITLE
Layout renders scripts with broken integrity url

### ISSUE THREAD

**Issue by chadbengen** [OrchardCMS/OrchardCore#8973]
### Describe the bug
I have the site hosted on Azure.  The layout page is generating scripts for all themes incorrectly:
 
```
<!-- Custom scripts for this template -->
<link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-xrRywqdh3PHs8keKZNa34MD<!DOCTYPE html>
<html lang=" en-us"="">
```
However, when i run it locally the scripts generate correctly:
```
     <!-- Custom scripts for this template -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css" integrity="sha384-t4IGnnWtvYimgcRMiXD2ZD04g28Is9vYsVaHo5LcWWJkoQGmMwGg+QS0mYlhbVv3" rel="stylesheet" type="text/css">
    <link href="/TheBlogTheme/css/bootstrap-oc.css?v=WbNUpcML-AqW_KWqGYhR3gtacOn8j8cE2VZuI2qOC1Q" rel="stylesheet" type="text/css">
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.2/css/all.css" integrity="sha384-Ex0vLvgbKZTFlqEetkjk2iUgM+H5udpQKFKjBoGFwPaHRGhiWyVI6jLz/3fBm5ht" rel="stylesheet" type="text/css">
    <link href="/TheBlogTheme/css/clean-blog.css?v=BhpWeMISyBL_o9iXSzWjQwXGlTrqmFzvt9150gJHqEo" rel="stylesheet" type="text/css">
```
Note: My local debug using Visual Studio 2019 has the appsettings set to production storage for configuration settings.  Meaning that production and local execution share the same setup.

There are two resources on the layout page that fail:
{% resources type: "Stylesheet" %} and {% resources type: "FootScript" %}.

~~My workaround was to copy and paste the locally generated links/scripts and paste them in the layout page as is.~~
My workaround was to disable using cdn from the resource settings.  

I confess to not fully understanding how templates work, or having any kind of solid grasp on how the site comes together.  But I find it strange that locally it renders the template correct, and further strange that the integrity value starts off differently vs. production.

### To Reproduce
na...this may not be a bug but rather something on my end, i do not know.

### Expected behavior
to render the scripts correctly.

**Comment by jtkech** [comment]
> Meaning that production and local execution share the same setup.

Yes but locally you may be in `IsDevelopment()` mode, it loads `bootstrap.min.css`, while in production it tries to load `bootstrap.css`, to check it locally, in your project `launchSettings.json` in the `IIS Express` profile replace `ASPNETCORE_ENVIRONMENT`  from `Development` to `Production`

Maybe an encoding issue with the integrity attribute see #3914, i'm working on other encoding issues, maybe related, i will let you know

**Comment by jtkech** [comment]
Not sure it is related but there is a recent encoding issue on aspnetcore see https://github.com/dotnet/aspnetcore/issues/31299

I think they will provide a patch soon to fix this issue

If you use the Nuget packages feed (master branch) you have to wait for them

If you use the Cloudsmith feed (last dev branch), we did a workaround that has been merged #8984

**Comment by jeffolmstead** [comment]
Just wanted to leave feedback that I had the same issues, and updating to latest release on DEV branch took care of things. @jtkech thanks for all those pull requests for the encoding issue, I think that took care of it (and some other issues i was having).

**Comment by chadbengen** [comment]
Thanks!  I'm not planning on confirming at this time since my workaround is "good enough for now".  I will assume that @jtkech  and @jeffolmstead  are right and close the bug.

**Comment by jtkech** [comment]
@jeffolmstead Thanks for the feedback

@chadbengen No problem
