### ISSUE TITLE
IServiceProvider disposed when using Hangfire issue

### ISSUE THREAD

**Issue by scottja88** [OrchardCMS/OrchardCore#8974]
We have a production application running multiple tenants that use Hangfire to run background jobs daily. Whenever we update our version of OrchardCore we tend to run in to issues regarding the following error:

![image](https://user-images.githubusercontent.com/7852775/112528096-1d2dcf00-8d7a-11eb-8943-d955c68785ac.png)

Our previous solution was to specifically execute StartAsyncFlow for the shell scope, but that is now an internal method instead of being public in #7158.

It is our thought that when a tenant restarts, the IServiceProvider gets disposed. Here is how we were using StartAsyncFlow. The JobActivator is how Hangfire creates instances of a given class.

```C#
public override JobActivatorScope BeginScope(JobActivatorContext context)
{
	var shellScope = _shellHost.GetScopeAsync(_shellSettings).GetAwaiter().GetResult();
	//shellScope.StartAsyncFlow();

	var httpAccessor = shellScope.ServiceProvider.GetService<IHttpContextAccessor>();

	httpAccessor.HttpContext = CreateHttpContext(shellScope);

	return new OrchardJobActivatorScope(shellScope);
}
```

Is there something we are missing, or can StartAsyncFlow return to being public?

**Comment by jtkech** [comment]
@scottja88 

If it fixes your issue, i will make it again public ;)

**Comment by scottja88** [comment]
@jtkech 

That would be great! I believe we should be able to function as we did if that was exposed for us to call again.
