### ISSUE TITLE
TaxonomyField with Tags display, error 400

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8986]
### Describe the bug

Taxonomy field with Tags display placed in ContentPart inside Widget throws error while saving content item.

### To Reproduce
1. Create content part with taxonomy field and tags display
2. Create widget, add content part from step 1
3. Add widget to flow of some content item
4. Try save = throws error 400

### Expected behavior

Content item should be saved. Also, it works when Standard display is used.

**Comment by MikeKry** [comment]
I am trying to look into it, and so far it seems there is a problem with __RequestVerificationToken, it is duplicated in this case and in debugger console there are following errors:
Exception thrown: 'System.FormatException' in Microsoft.AspNetCore.WebUtilities.dll
Exception thrown: 'Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException' in Microsoft.AspNetCore.Antiforgery.dll
Exception thrown: 'Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException' in System.Private.CoreLib.dll


but not sure how they get there

**Comment by MikeKry** [comment]
Ok, so it definitely is caused by this:
![image](https://user-images.githubusercontent.com/52829889/112612711-8582bc00-8e1f-11eb-95ab-a090f5b52a02.png)

Question is, if it needs to be there, as it is always part of content item and the verification token is send anyway in request for new tag:
![image](https://user-images.githubusercontent.com/52829889/112613074-f9bd5f80-8e1f-11eb-9537-83228e39d8e2.png)

If it has to, then there is probably some error, because it should not appear twice in same request. Any ideas how to solve that please? I can remove it and push, if it is okay with you, but if there is any case, where it would not be included in form with antiforgery token, it could be problem (but I am not aware of that usecase)

**Comment by deanmarcussen** [comment]
Looks reasonable to remove it.

Just try it after removing with the blog recipe, it's got tags on by default, and check it works there as well.

(I would have added it for some reason, but that reason may no longer be valid)

**Comment by MikeKry** [comment]
@deanmarcussen 

Ok, I have tested it on blog recipe and it seems ok - antiforgery token is still added into request and tags are successfully created and saved. 

Pushed into https://github.com/OrchardCMS/OrchardCore/pull/8988

Can I please ask, if it could be merged today/this week? It currently breaks my content items completely and I cannot even use standard editor because of bug described in 8806 which breaks my layout completely.

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/8988
