### ISSUE TITLE
Archives: Query, Widget and Filter

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#899]
@sebastienros : Can you please give some hints to obtain an archives widget for the post of a blog?

- Query to select the posts.
- Liquid syntax to group by and count the posts by month/year.
- Page to display a summary of the posts grouped by month/year.

**Comment by zl2fxy** [comment]
I have this problem, too.I hope query many blogposts belong to a blog.but i can't do

**Comment by agriffard** [comment]
Could be explained in the Queries documentation : #1020

**Comment by agriffard** [comment]
In order to display the number of posts by year/month, I created an 'Archives' query :
```
select 
    month(CreatedUtc) as [Month], 
    year(CreatedUtc) as [Year],
    count(id) as [Count]
from ContentItemIndex 
where Published = true and ContentType = 'BlogPost'
group by month(CreatedUtc), year(CreatedUtc)
order by Year ASC, Month ASC
```
Then, I added a simple Liquid Widget in the Always layer and the Content zone :
```
{% for archive in 'Archives' | query %}
      {{ archive.Year }} {{ archive.Month }} {{ archive.Count }}<br/>
{% endfor %}
```

The preview doesn't show anything and if I make a change, this error appears :
`Syntax error, expected: identifier, ( at line:0, col:18`

Even if I publish it and display the homepage, nothing appears.

My last try was to launch it in Debug and put a breakpoint in the ProcessAsync method of QueryFilter.cs in OrchardCore.Queries\Liquid but it is not executed when I display the page.

**Comment by agriffard** [comment]
When I run the query from the admin, there are some results, of course.

**Comment by agriffard** [comment]
Ok, it works if I do this:
```
{% assign archives = 'Archives' | query %}
{% for archive in archives %}
      {{ archive.Year }} {{ archive.Month }} {{ archive.Count }}<br/>
{% endfor %}
```

**Comment by sebastienros** [comment]
So the issue in the the `in` operator that doesn't take the pipe into account?

I wonder if there is an issue too with {% display foo | build_display: "Summary" %}, I haven't tried yet

**Comment by jtkech** [comment]
Just tried it, `{% display foo | build_display: "Summary" %}` works but foo needs to be a `ContentItem`. I will update the `build_display` filter to also allow a `JObject` input, see my comment in #1178.

**Comment by agriffard** [comment]
https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Queries/README/
