### ISSUE TITLE
Create a liquid filter to format a json object

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#902]
For debugging templates and tokens, create a `render_tree` filter that would render a JObject as a treeview in the html. It could also convert any object to JObject at first.

**Comment by agriffard** [comment]
Isn't there something already like `| raw` ?

**Comment by sebastienros** [comment]
{% raw %} ... {% endraw %}

I believe it's documented, please check.

**Comment by agriffard** [comment]
A json filter seems to exist in Shopify : 
https://help.shopify.com/themes/liquid/filters/additional-filters#json 

On a string, it encodes it and on an object, it displays it in json.

**Comment by sebastienros** [comment]
@agriffard  the `json` filter is actually to encode a json value and will also contain the `"` around it.

**Comment by agriffard** [comment]
Is it still needed since there is a `ConsoleLog` filter?
