### ISSUE TITLE
Deployment plan: Content Item step duplicities

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#9023]
Related to #8900 
When using deployment plan and adding Content Item steps, user is able to add two same content items to plan, which then results into multiple active items in ContentItemIndex, so it shows duplicates in content items list.

### Describe the solution you'd like
Block adding duplicate Content Item steps. 

### Describe alternatives you've considered
Add label to content item, that it is part of plan

**Comment by MikeKry** [comment]
Probably I will go with creating new state of content item "ready for deploy" and custom step, would that be something that would be useful for OC, so I would create some more general thing from it, or it is too much custom and we will focus only on fixing bugs in current export steps?

btw. when deploy plan has more than ~300 items, it is slow and you can not remve items from it.

**Comment by deanmarcussen** [comment]
Could you provide some more explanation of the issue you're describing here.

Which Content Item step are you using?

Is it related to the AddToDeploymentPlanFeature, or another step? there are perhaps 5 content related steps?

A sample deployment plan / recipe, would be also be useful please.

> user is able to add two same content items to plan

However it is that they are doing this, we should resolve the import routine to cope, there are a lot of tests, so with an example plan reproducing the issue it should be easy to fit them into a test, to see what / where it is failing.

**Comment by MikeKry** [comment]
@deanmarcussen 

sure, it is "Conten Item" step, added from Conten Items list by "Add to deployment plan":
![image](https://user-images.githubusercontent.com/52829889/113325905-4968c300-9319-11eb-88ea-eb0bac9d2528.png)

You see, that there can be two same items added and then during import it always creates duplicate items in target environment.

Also when I tested it again, I have noticed, that removing items is possible, but it always removes first item, not the selected one. 

I have setup demo here:
http://try.orchardcore.fr/cb2h1vty/admin
admin / t_@$X53F

http://try.orchardcore.fr/cb2h1vty/Admin/DeploymentPlan/Display/23
there can be tested 
* duplicates when adding from content list
* removal of only first item

I tried to setup also the big dataset test to show slowness of loading, but maybe it happens only when there are distinct items and I dont have dataset like this right now.. 

Anyway, what I think should be done, based on experience from using deployments:
* add label to content items, so I would know, it is present in some export
* block adding duplicate content item step into deployment plan
* even if it is duplicated in deployment plan, filter it out when importing
* add pager.

**Comment by deanmarcussen** [comment]
> You see, that there can be two same items added and then during import it always creates duplicate items in target environment.

ok, great, that's probably enough to go on.

The content manager api needs to be fixed, so that it isn't possible to do this during one session.

**Comment by MikeKry** [comment]
@deanmarcussen 

Great, do you think it is possible, that You will look into this anytime soon, or it is not likely? 

It is breaking graphql api when duplicates are present, so I will need to handle that next week one way or another, so if You will not have time for it, maybe you could guide me on proper solution that could be pushed into OC.
