### ISSUE TITLE
Update to Bootstrap 4 Beta

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#903]
http://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/

There doesn't seem too much migration since the last alpha:
https://getbootstrap.com/docs/4.0/migration/

I will update the resources and test that all the admin screens are displayed correctly.

**Comment by sebastienros** [comment]
Two things in mind:
- the autocollapse changes that @jersiovic did, try to see if the custom scripts are still necessary
- in the setup screen, try to change the recipe with keyboard (right now only mouse)
- maybe the `tether.js` script is not necessary anymore

**Comment by agriffard** [comment]
PR merged
