### ISSUE TITLE
_widgets.scss math error

### ISSUE THREAD

**Issue by kdubious** [OrchardCMS/OrchardCore#9032]
For the 33% and 66% columns, the current code calls `make-col` with a decimal value, but it should pass the "bootstrap" col number.

The result is that 33% and 66% end up as 33% and 66%.

If you try to kill the gutters, and make a "full-width" column, you'll see the issue. With gutters, this issue is negligible.

The fix is here:

```
@each $wsize in (25, 33, 50, 66, 75) {
    .widget-size-#{$wsize} {
        @extend .widget-size-100;

        @include media-breakpoint-up(sm) {
            @include make-col(round($wsize*12/100));
        }
    }

    .widget .widget-size-#{$wsize} {
        @extend .widget-size-#{$wsize};

        @include media-breakpoint-up(md) {
            @include make-col(round($wsize*12/100));
        }
    }
}
```

**Comment by hishamco** [comment]
Could you please submit a PR?

**Comment by sebastienros** [comment]
Agree with @hishamco 

thanks

**Comment by Skrypt** [comment]
I don't understand what is the issue. We should not round these values like you did there.
From what I understand in your fix, the 12 columns will not fit the entire 100% width of it's container.
Please should me an example of your issue so that I can review it.

**Comment by kdubious** [comment]
**Short Version:**

I'm dealing with `.no-gutters`

[Bootstrap: No Gutters](https://getbootstrap.com/docs/4.6/layout/grid/#no-gutters)

**Long version:**
We should get the correct end result when we can.

Bootstrap's function `make-col` takes the Column Width Value (4 in the case of col-md-4), divides it by the column count (typically 12, but its a variable), and gets a percentage. `4 / 12 = 33.33333%`

When you do `(33 * 12 / 100)` you get 3.96. Then that gets passed to the Bootstrap function where they divide it by the column count (typically 12, but its a variable) and we get `3.96 / 12` which equals 33%. (We want 33.33333%)

So the existing code generates:
```
.widget-size-33 = 33%
.widget-size-66 = 66%
```

Add them, and there's a missing 1%. Fine when you use gutters, ugly if not.

My method generates:
```
.widget-size-33 = 33.33333%
.widget-size-66 = 66.66666%
```

Add them with only a missing .00001%

**Comment by kdubious** [comment]
@hishamco I will.

**Comment by Skrypt** [comment]
Ok I agree. I did see the issue after seeing that it was not a width calculated there in the widget but the amount of columns.
