### ISSUE TITLE
The recent release break the footer: InvalidOperationException: Zone not found: Footer

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#9033]
### Describe the bug
With required set to true in the Layout.cshtml:
  `  @await RenderSectionAsync("Footer", required: true)`
The Widget footer doesn't show on any pages - even set to "Always"

Then cause error when browsing the website:
**InvalidOperationException: Zone not found: Footer**

**Comment by sebastienros** [comment]
Couldn't find this code in Orchard so I assume you wrote it. If the zone is not filled with anything then don't make it `required: true`.

**Comment by orchardc** [comment]
Hi @sebastienros , I tried the latest 1.0.0-rc2-16044 but the footer still not shown.

In the Admin panel, I can see it in the Widgets and Layer; I have tried to delete it and create a new one but still can't see the footer on the website.

![image](https://user-images.githubusercontent.com/16193516/113343306-92c00f00-9327-11eb-930d-9bd8e15bc11e.png)

The code is in the TheAdmin theme, although "required" is set to false; I change it to true only for the testing purpose, however, it doesn't show at all. 

![image](https://user-images.githubusercontent.com/16193516/113343505-ce5ad900-9327-11eb-8e5e-dbb192b84cb1.png)

**Comment by orchardc** [comment]
Maybe the **RenderSectionAsync** doesn't work because I'm missing some references ?

**Comment by jtkech** [comment]
@orchardc 

I can't repro

What is the `HtmlWidget`? Is it a widget that you created?

Maybe it is not taken into account, and because it is the only one in the zone, the zone has not been created

Can you try to add to the Footer zone e.g. a simple Paragraph widget, to see if it works

Then add your html widget to the Content zone for testing

**Comment by orchardc** [comment]
No the HtmlWidget was the one that created by the receipt.
After I reset the database with the latest version update, and it works. Thank you jtkech and sebastienros, I'm closing this one.
