### ISSUE TITLE
Setup form fails to submit on firefox when autofilling password

### ISSUE THREAD

**Issue by khalibloo** [OrchardCMS/OrchardCore#9040]
### Describe the bug
During the initial setup, if password is filled from a saved login, the password validation logic isn't triggered on firefox. As such, clicking the "finish setup" button has no effect.

### To Reproduce
1. Using firefox, open the initial setup page
2. For the super user, use a saved login
3. Click submit
4. Form isn't submitted because password strength is still 0

### Expected behavior
I'd expect it to validate the password when I use a saved login.

I'm on firefox 87.0 on Windows 10

**Comment by Piedone** [comment]
I don't see this happening anymore. Please reopen if still applicable.
