### ISSUE TITLE
WorkflowTypeIndex not available for subsequent recipe steps?

### ISSUE THREAD

**Issue by willnationsdev** [OrchardCMS/OrchardCore#9064]
### Describe the bug

I was using build 15800 for a while, and during that time, I built a web app that I could completely recreate on a fresh local tenant using a recipe via Blank recipe + Package Import. It would turn on a set of features, define content types, define workflows, and then create content items with forms that submit to the workflows.

I then updated to build 16039. Now, when I create a Blank tenant and run the recipe to recreate the app locally (for regression testing purposes), I find that the "Package Import" process fails when attempting to create the content items. The error I get is...

`SQLite Error 1: 'no such table: WorkflowTypeIndex'.`

This never happened previously, so I'm wondering if something changed to where the indexes' creation has been delayed or something? I would have thought the index would be created when the feature is turned on, which would have been completed at the end of the Feature recipe step, so the subsequent `content` step would be executing with the index already existing. Is there something I'm missing?

The recipe steps I have are...

1. Feature
    -  "Application.Default",
    - [CustomFormWidgets]
    - "OrchardCore.Liquid",
    - "OrchardCore.Scripting",
    - "OrchardCore.Workflows",
    - "OrchardCore.Workflows.Http",
    - [CustomLiquidFilters]
    - "OrchardCore.Microsoft.Authentication.AzureAD",
    - "OrchardCore.Resources",
    - "OrchardCore.Email",
    - "OrchardCore.Users",
    - "OrchardCore.Users.Registration",
    - [CustomAuthentication],
    - [CustomWorkflowActivities],
    - "OrchardCore.Settings",
    - "OrchardCore.Admin",
    - "OrchardCore.Templates",
    - "OrchardCore.Contents",
    - "OrchardCore.ContentTypes",
    - "OrchardCore.Alias",
    - "OrchardCore.Autoroute",
    - "OrchardCore.Shortcodes",
    - "OrchardCore.ContentFields",
    - "OrchardCore.ContentPreview",
    - "OrchardCore.Deployment",
    - "OrchardCore.Contents.Deployment.AddToDeploymentPlan",
    - "OrchardCore.Contents.FileContentDefinition",
    - "OrchardCore.CustomSettings",
    - "OrchardCore.Deployment.Remote",
    - "OrchardCore.Diagnostics",
    - "OrchardCore.DynamicCache",
    - "OrchardCore.Widgets",
    - "OrchardCore.Features",
    - "OrchardCore.Feeds",
    - "OrchardCore.Flows",
    - "OrchardCore.Forms",
    - "OrchardCore.HomeRoute",
    - "OrchardCore.Html",
    - "OrchardCore.Indexing",
    - "OrchardCore.Layers",
    - "OrchardCore.Lists",
    - "OrchardCore.Lucene",
    - "OrchardCore.Markdown",
    - "OrchardCore.Media",
    - "OrchardCore.Title",
    - "OrchardCore.Menu",
    - "OrchardCore.Navigation",
    - "OrchardCore.Recipes",
    - "OrchardCore.Roles",
    - "OrchardCore.Shortcodes.Templates",
    - "OrchardCore.Taxonomies",
    - "OrchardCore.Taxonomies.ContentsAdminList",
    - "OrchardCore.Themes",
    - "TheAdmin",
    - [CustomAdminTheme],
    - [CustomFrontendTheme]
2. WorkflowType
3. Templates
4. ContentDefinition
5. Themes
6. CustomStepToRefreshWorkflowHttpRequestTokens
7. content
    - main menu
    - side menu
    - form1
    - form2

The recipe executes successfully if I just remove the last `content` step, but it fails if the `content` step is included. Aside from the forms having some custom shortcodes in an HtmlBodyPart, they are typical run-of-the-mill forms without any custom functionality. This leads me to think the problem lies somewhere else, especially since it all worked fine before updating to the latest dev build.

I also wondered if maybe the recipe deployment plan made from a 15800 build was having issues being imported into a 16039 build? But the content/format looked largely the same.

### To Reproduce
1. Have similar recipe steps executed on a Blank fresh tenant with a SQLite database? Not sure how best to reproduce it.

### Expected behavior
Able to successfully import content.

**Comment by jtkech** [comment]
@willnationsdev 

Related to #8785 and #8967

I'm working on, i think it will be fixed by #9046
