### ISSUE TITLE
Liquid raw tag appears to no longer produce output?

### ISSUE THREAD

**Issue by willnationsdev** [OrchardCMS/OrchardCore#9065]
### Describe the bug

Any text placed inside a raw tag no longer renders.

```
TESTING
{% zone "BodyBottom" %}
TEST 2
{% raw %}
{{ TEST 3 }}
{% endraw %}
{% endzone %}
```

When I click 'view source', TESTING shows up on the page, and TEST 2 is teleported to the bottom where it is supposed to be in our Layout, but `{{ TEST 3 }}` does not render. It doesn't render even if we just make it `TEST 3` without the curly braces. I also tested it with just a raw tag, without any zone stuff.

We needed the raw tag to be able to use JS Handlebars templates on our frontend. Worked fine in our 15800 build, but broke when we updated to 16039.

### To Reproduce
1. Add a Liquid part to a content item.
2. Use a raw tag (not filter) to create output.

### Expected behavior
Raw tag allows output in a format that subverts typical Liquid syntax.

**Comment by jtkech** [comment]
Yes, looks like the liquid raw statement write nothing ;)

https://github.com/sebastienros/fluid/blob/c4c184c17b7c0ec1fc3647a24a720f9387a1fc5c/Fluid/Ast/RawStatement.cs#L19

**Comment by willnationsdev** [comment]
Lolwut. Okay. Hmmm, what are we supposed to do to inject custom markup then? Any suggestions @jtkech ?

**Comment by deanmarcussen** [comment]
Suggest to open an issue on the fluid repo and it will get fixed
