### ISSUE TITLE
Media: a few considerations

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#908]
Been testing the media module and it's great. There are a few things that I's like the team to consider before release. Apologizes if I have missed any features that are already there and I just couldn't find them. 

## Items to consider before release

- Alternate Text field added by default and set as required by default (just for image media obviously). Many organisations want to enforce that content editors set the alternative text field. If the default caption field was the intention for this then this may be better to be labeled to be consistent to the HTML language as to avoid confusion.
- Images have a title by default (visible only on the editing side). Once the library gets larger content editors are going to want to be able to search the media library somehow (even if search is not released till later). Title should be shown instead of filename in the selectors and the media field.
- When you upload a image the filename is set by the filename of the uploaded image. You should be able to change this to be something meaningful... perhaps initially an autoroute of the title that can be changed by the content editor.
- There doesn't seem to be anywhere you can change fields added to an image. Is this incomplete?

## Items that could be addressed after release

- When a content editor adds an image to markdown editor or selects and image in the media field, they should be given an opportunity to modify/set the alternative text. By default the selector should get the alternative text stored with the image but they should have the opportunity to override the default value.
- When a content editor adds an image to the markdown editor they should have an opportunity to set the size. If default sizes could be stored this would be great... eventually also be great to support being able to set different sizes for different devices using srcset.

**Comment by sebastienros** [comment]
Just something to keep in mind is that the Media page is nothing more than a file management system, as opposed to the one in O1.
So to be able to handle fields, titles, ... we need an Image content type. There is one already, but I need to fine tune it, and your feedback is valuable. Have you seen the Bag Part ? the idea is that we can use it to add content items like Image to a main content item, then we can add custom metadata here, and use it in the main content item. I'll think about it and ping you when I have done something on it. thanks

**Comment by scleaver** [comment]
Oh ok... file system manager - sorry didn't realise. So you can't extend this to support different storage like db, AWS S3 etc?

Just looking at the bag part now. There is two "image" in the content type checkboxes. Any difference between them?

I also noticed that the width and height params are not changing the image size. Future feature? 

In my own projects I may look at utilising something like https://imageresizing.net/ particularly because of features like DiskCache, name based presets etc.

Thanks for all the hard work.
