### ISSUE TITLE
UI improvement: Show title render settings

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#9098]
Based on feedback from using OC, we have identified that it is useful for users to know if title is rendered on website, or it is just internal identifier in administration.

I have made a customization for this in TitlePart view and if it would make sense, I can create a PR so it could by included by default in OC. It makes sense to me, as we already have setting for rendering.

Looks like this:

![image](https://user-images.githubusercontent.com/52829889/114011214-46b02580-9865-11eb-91e0-9b3db7ba942d.png)

**Comment by Piedone** [comment]
Are you looking for a way to add a custom hint to the title?

**Comment by hishamco** [comment]
If I understand correctly he wants a way for the `TitlePart` to be used internally from within the admin site or could be used in the site. IMHO, with this sort of customization, all the fields / parts could be used internally

Do you have a use case for that, coz all the CMSs I know don't offer such option, but it's doable to add a boolean property `IsPrivate` to make this happen, but again you might need to think how to prevent display it's value in the website if someone add it into the markup accidently
