### ISSUE TITLE
Remote deployment roles missing

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#9101]
Roles for remote deployment can't be set, they aren't in admin at all, probably because they are not registered in startup.cs? OrchardCore.Modules/OrchardCore.Deployment.Remote/Permissions.cs

Because of this, only admin can deploy to another environment. Is there a reason for that, or can I fix it and create PR?

**Comment by deanmarcussen** [comment]
The permissions you mean? yes, just register them

**Comment by MikeKry** [comment]
Registered, created pr.
