### ISSUE TITLE
Fields are not auto welded onto the kernel

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#9103]
### Describe the bug
When creating a content item via the API fields are not auto welded onto the kernel like parts are. This means that you need to either remember to create a new Field via code for every field in your content item otherwise you will not be able to save the item after editing in the Admin UI OR you might get Indexing errors when you save the item via the API.

### To Reproduce
Create a content item that has fields via the API and don't specify some fields in your code

### Expected behavior
I would expect that fields are automatically initialized like parts when using the API.

### Workaround
Workarounds for this problem are:

Apply a field for each item via the API even if it has no value like so:
```
myPart.Apply("Summary", new TextField());
```
Or make sure you initialize each field in your model if you have a model like so:
```
public TextField Summary { get; set; } = new TextField();
```

**Comment by Skrypt** [comment]
Indexing errors in SQL or Lucene?

**Comment by scleaver** [comment]
> Indexing errors in SQL or Lucene?

When the item is created an SQL index error occurs - @deanmarcussen is aware of this issue

**Comment by Skrypt** [comment]
Yeah, it's a known issue. But assuming we should wield the Field to the Content Type would be quite dangerous somehow. This means that potentially you could store data on wrong fields for example if you made a Typo in your code. The thing we are missing then is the ability to know which field(s) are allowed and then drop the ones that are not.

Leaving this one to @deanmarcussen 😉

**Comment by deanmarcussen** [comment]
Yes, so something I have seen as well.

Needs a little thought. Here's why though
`ContentManager.NewAsync()` calls activated in the part handler coordinator
https://github.com/OrchardCMS/OrchardCore/blob/a6ede09c77bbe888fcc6a030ef5721b0a960226d/src/OrchardCore/OrchardCore.ContentManagement/Handlers/ContentPartHandlerCoordinator.cs#L44

which activates the Parts, welding them on.

What it doesn't do is activate the fields for a Part.

They are later activated by `LoadedAsync`
https://github.com/OrchardCMS/OrchardCore/blob/a6ede09c77bbe888fcc6a030ef5721b0a960226d/src/OrchardCore/OrchardCore.ContentManagement/Handlers/ContentPartHandlerCoordinator.cs#L266

But that's only useful from a UI pov, as when creating new content via the content manager API, loaded won't be called, which means that any indexes using those fields, end up not indexed. At least until the content is later edited in the UI.

Be useful to understand if this is just an ommision during activation, or just something that wsn't thought about, and needs fixing, by applying essentially what we are doing with`LoadedAsync`.

**Comment by Skrypt** [comment]
The DisplayManager.BuildEditorAsync method if I remember correctly does the same thing.

**Comment by jptissot** [comment]
I wonder if the same is true for content created via workflows / scripting.

**Comment by Skrypt** [comment]
Probably. Somehow it would make sense that the events triggered work by themselves. It seems strange to need to use the DisplayManager in an API call to weld fields on content parts ...

**Comment by Skrypt** [comment]
@deanmarcussen It was probably lazy loaded intentionally.

**Comment by Skrypt** [comment]
There was a request a while back about doing a JSON Schema validation on API's. Maybe this would be part of the solution.

**Comment by sebastienros** [comment]
We should weld the fields. Unless we (I) saw an issue that will be revealed once it's done.
