### ISSUE TITLE
In recent updates, the NormalizedUserName has changed all '@' into '+'

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#9107]
In recent updates, the NormalizedUserName has changed all '@' into '+'

i..e previously user has login name: user@1 , now in the UserIndex table and Document table, the NormalizedUserName has changed to user+1

What is the recommendation? Because we have business logic that links to NormalizedUserName field; 

Shall we manually update the UserIndex and Document tables to back to uesr@1, or shall we update our custom tables (which contains business logic)

**Comment by Skrypt** [comment]
Your business logic should now link to the UserId instead. NormalizedUserName is not immutable ; UserId is.

**Comment by orchardc** [comment]
Thanks @Skrypt , but there are so many cases that we need to use `User.Identity.Name` as parameter to query, now with UserId, how can we get the UserId

**Comment by Skrypt** [comment]
It should be part of the Claims. See what @kevinchalet does with OpenId.

```C#
    internal static class OpenIdExtensions
    {
        internal static string GetUserIdentifier(this ClaimsPrincipal principal)
            => principal.FindFirst(Claims.Subject)?.Value ??
               principal.FindFirst(ClaimTypes.NameIdentifier)?.Value ??
               principal.FindFirst(ClaimTypes.Upn)?.Value ??
               throw new InvalidOperationException("No suitable user identifier can be found in the principal.");
```

**Comment by Skrypt** [comment]
From a Query.

```C#
var currentUser = (await _session.Query<User, UserIndex>(u => u.UserId == user.FindFirstValue(ClaimTypes.NameIdentifier)).ListAsync()).FirstOrDefault();
```

**Comment by orchardc** [comment]
We actually found a shorter (not sure if it's better) solution :  `userManager.GetUserId(User);`

**Comment by Skrypt** [comment]
Works too. Encapsulates the previous.

https://source.dot.net/#Microsoft.Extensions.Identity.Core/UserManager.cs,16ac3e296ed8ac35,references
https://source.dot.net/#Microsoft.Extensions.Identity.Core/UserManager.cs,530346943c4d6a76,references

**Comment by orchardc** [comment]
Thanks @Skrypt , what is the build number for this change? Is it 16084?
How to call it from the `User` object?

**Comment by orchardc** [comment]
I still think it's not as easy as using `User.Identity.Name`; the new approaches both require to make another call to get the userid.

**Comment by Skrypt** [comment]
We could maybe expose this property on the User object. Need to see but this comes from asp.net identity.

**Comment by orchardc** [comment]
Thank you @Skrypt , since we are using UserId as the key now, it makes perfect sense to expose this property. Not sure how long it will take though?

**Comment by deanmarcussen** [comment]
Which `User` object are you talking about in terms of exposing the `UserId` ?

There are many.
- either current `User`, which is a `ClaimsPrincipal` and is part of the asp.net ecosystem. It can be accessed by the code @Skrypt has already given you, i.e. `httpContext.User.FindFirstValue(ClaimTypes.NameIdentifier)`
- the `IUser` which we would not want to expose the `UserId` on directly, as it's designed to be a replaceable interface, and therefore matches the asp.net claims principal.
- or the `User` database object, which has the user id.

**Comment by orchardc** [comment]
Hi @deanmarcussen , @Skrypt 

I noticed that in the recent upgrade, within the **NormalizedUserName** has changed all '@' into '+'
For example, previously user has login name: user@1 , now in the UserIndex table and Document table, the NormalizedUserName has changed to user+1

This causing business logic error (because we have other tables which use UserName as the key to link to the UserIndex table) and I don't understand why this change ( from @ to +) is needed?

Another observation is: the UserId filed in the UserIndex table, previously it was the same value of UserName, now it has changed to 26 chars string, what is the reason for that? This makes it not stable to be used as the key too.

I'd appreciate your suggestion!

**Comment by Skrypt** [comment]
I feel like this question is redundant. Please make a search on the issues and PR to find "UserId" term and I'm pretty sure we already answered all of these questions.

**Comment by orchardc** [comment]
We end up with replacing '+' with '@' of the NormalizedUserName field in UserIndex table; also updated the Content json in the Document table. So it's back to normal - we don't mind the there is @ in the NormalizedUserName field.

@Skrypt  Do you think the upcoming upgrade will change it again ??

**Comment by Skrypt** [comment]
It won't, but using an email as an identifier is a security concern. This is why we did the change. The appropriate reaction to this is to use the UserId. Using the NormalizedUserName field as an identifier is not recommended as it is not immutable.

**Comment by orchardc** [comment]
Hi @Skrypt , thanks for the suggestion. I have a question: isn't the NormalizedUserName used for user login (as the user name)? By changing @ to +, it also changed the user login (and user don't know it), how come NormalizedUserName is not immutable?

**Comment by Skrypt** [comment]
The NormalizedUserName is not immutable by design. It's part of ASP.NET Core identity. As a user you should be able to change your UserName ... you should also be able to change your account email. So there is no issue there that those are not immutable.

The UserName should never use a @ because you can then spoof someone else account by using the email of someone else account in your UserName. This is why a UserName should never be able to use a @ char. So, this is why the NormalizedUserName has been migrated to use a + char instead of an @ char. If your users we're using a email as their username they can now still login by UserName or Email. It means that the Email of the IUser has not changed so this should still work for your users to login with their Email. If the UserName was using an @ char and it was different than the email then yes the UserName has changed and we can't do anything about it because this is the restriction that we wanted.

**Comment by orchardc** [comment]
Thanks for the clarification, it is clear to me now. Important to know: is there a plan to make users be able to change their UserName (NormalizedUserName ) in OC?

**Comment by Skrypt** [comment]
They already can do that.

**Comment by orchardc** [comment]
I guess there is a way to turn this feature off? :)

**Comment by Skrypt** [comment]
Yes, but nothing prevents from turning this feature on. Any module could reconfigure the ASP.NET Identity middleware options. So, this was not a retained proper solution.

**Comment by orchardc** [comment]
Closed as by design .

**Comment by orchardc** [comment]
Hi @Skrypt ,

I looked into docs and [source code](https://github.com/OrchardCMS/OrchardCore/tree/b093ee27a538873ef5c559afa19572e9368f42b0/src/OrchardCore.Modules/OrchardCore.Users/Views), there isn't a View that supports users to update their username; although Backend Admins can do so, it can be controlled by a security role.

Is it correct or am I miss something? 

Many thanks!
