### ISSUE TITLE
Liquid For Loop 'Non-negative number required'

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#9120]
@sebastienros prior to the Liquid update in 'dev' branch, you, you could do this:

```
{% assign nestedIndexSize = nestedTitles.size | minus: 1 %}
  {% for i in (0..nestedIndexSize) %}
	<li class="breadcrumb-item text-nowrap"><a href="{{ nestedUrls[i] }}">{{ nestedTitles[i] }}</a></li>
  {% endfor %}
{% endif %}
``` 

On the for loop, you did not care if 'nestedIndexSize' was less than 0, it just wouldn't render the for loop. With the latest change it will throw an error of:

```
ArgumentOutOfRangeException: Non-negative number required. (Parameter 'capacity')
```

To fix it you have to do something like this:

```
{% assign nestedIndexSize = nestedTitles.size | minus: 1 %}
	{% if nestedIndexSize > 0 %}
	  {% for i in (0..nestedIndexSize) %}
		<li class="breadcrumb-item text-nowrap"><a href="{{ nestedUrls[i] }}">{{ nestedTitles[i] }}</a></li>
	  {% endfor %}
	{% endif %}
{% endif %}
```

In other words, you have to put an if statement in to ensure it is greater than 0. 

My request is that we either have the underlying code take care of it and not render the loop like it used to. Or, if we don't want to do that, then maybe we can at least have the underlying code fail "gracefully". Normally, no matter what you do in Liquid, it doesn't crash the page. A specific section might not render, but doesn't break the whole page. Just my thoughts.

**Comment by sebastienros** [comment]
I fixed it, will update OC now. I also found an issue when `limit` is negative, it should strip a range/enumeration from the end like `SkipLast()`.
