### ISSUE TITLE
Meeting Feedback

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#9123]
- About disposing `ISession` if an exception is thrown, we have different methods to execute in a given shell scope but we always pass through the following one that uses an `using block` on this shell scope ensuring that it will be disposed, so its service provider and then any `IDisposable` services.

https://github.com/OrchardCMS/OrchardCore/blob/67462e3df7d3930acc17c91aa0f59960982f6e61/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs#L222-L244

- About the `ContentStep` in a deferred task, e.g. to prevent a WF to be executed before the WF migrations, this when triggered by the `OC.Contents.ContentHandler` registered in a startup using the `RequireFeatures` attribute.

    I tried to adjust the dependencies of types requiring features, **it is useful for the execution order of migrations / drivers / handlers between each others**, but it was not fixing the recipe migration issues, so to not break anything i reverted it. 

    **Here the problem is not to adjust the execution order of an handler but to prevent it from being executed before WF migrations**. When executing migrations a shell has been composed, so, even if the `ContentHandler` has been registered later, it is there and nothing prevents any migration to use the `ContentStep` triggering the `ContentHandler`.

    So, at least for the related issues, it was not due to a dependency ordering issue.

- About defining a view template under the application's module, runtime compilation and so on, yes not so obvious, we can be under dev mode or not, the `refs` folder may be outputed or nor based on the `PreserveCompilationReferences`, so already 4 use cases and because it also depends on the version, there are many use cases.

    Before we were using `PreserveCompilationContext`, the one you were talking about in the meeting, then it was not needed if `PreserveCompilationReferences` is set to true which was the default, then they changed it when runtime compilation was no more the default, that's why we currently use it in the web app project file.

    Finally you said to me that under net6.0 `PreserveCompilationContext` will not be managed as before ;)

    So yes a documentation guide would be useful but not so easy to follow all the history and describe what to do for all use cases, maybe just describe what to do for the current version and update it if there are other changes.

**Comment by jtkech** [comment]
@sebastienros 

Finally, about the static `AsyncLocal<ShellScope>` we need a discussion, i'm not against removing its usage

- I already thought about making an `IShellScopeAccessor` to retrieve its service provider, but we already override the `HttpContext.RequestServices` by the following, so using an `IHttpContextAccessor` would do exactly the same as getting the `RequestServices` would just return `ShellScope.Services`.

    We need the following to allow nested shell scopes, shell scopes of other tenants, all executing e.g. in the same request context, also when there is no http context as for GraphQL and background tasks. This to ensure that all codes using an `IHttpContextAccessor` will retrieve the right scoped service provider of the right tenant container.

https://github.com/OrchardCMS/OrchardCore/blob/4e1f974eede50f374a400317771040d1f1ba8dd5/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScopeServices.cs#L5-L17

- That said, there are some methods, e.g. to enlist a `BeforeDispose` or a `DeferredTask` delegate, that can only be called through the current shell scope, so maybe still useful to have an `IShellScopeAccessor`, but not sure as it would do the exact same things but through an injected service.

**Comment by sebastienros** [comment]
I am thinking that if a service needs the current scope, because it's singleton for instance, then it should be passed in a context object to the method, or it should be split in two: 
- singleton service, with the state
- scoped/transient service that is actually used, resolving the singleton service

And if that doesn't work then this component should create its own scope, like background tasks do.

**Comment by jtkech** [comment]
> But accessing IHttpContextAccessor is fine too, at least we are not duplicating this logic in a special accessor.

Yes, this is what i think

But we still need to use the AsyncLocal ShellScope e.g. to add a DeferredTask. That's why in some code where i need to use `ShellScope.AddDeferredTask()`, i also use `ShellScope.Services` if i need to retrieve the service provider.

Note: To prevent multiple async local accesses, better to use an intermediate variable `var scope = ShellScope.Current`

But sometime i let it as it is when it is not an hot code path
