### ISSUE TITLE
Liquid in ViewPart  not working

### ISSUE THREAD

**Issue by datdv260497** [OrchardCMS/OrchardCore#9139]
### Describe the bug
Orchard core version: 1.0.0-rc2-16078
I create module with cmd: dotnet new ocmodulecms -n ModuleName.OrchardCore --AddPart true --PartName Test
I add liquid code  {{ Model.ContentItem | display_text }} into TestPart template.
But liquid not working for me. 

### Screenshots
![image](https://user-images.githubusercontent.com/49801948/114342768-9f91fd80-9b86-11eb-97c6-2206ea605472.png)
![image](https://user-images.githubusercontent.com/49801948/114342830-ce0fd880-9b86-11eb-9a71-2d3eb3f4ec70.png)

**Comment by Skrypt** [comment]
Template name is probably incorrect.

**Comment by datdv260497** [comment]
> Template name is probably incorrect.
I checked Html in template works normally, but liquid is not

**Comment by jtkech** [comment]
@datdv260497 

Just tried it works but not e.g. under TheBlogTheme because of the following reason

In the BlogTheme the views are not using the full shape system, but a mix of rendering data directly from e.g. the content item Content json data as in the database, and of rendering a e.g. a given part / field by using the shape_render filter.

    // Use the Content json data as persisted in the db
    {{ Model.ContentItem.Content.Article.Subtitle.Text }}


    // Use the shape system, Model is a zone holding shape, Content is a zone shape, and so on
    {{ Model.Content.HtmlBodyPart | shape_render }}


So if you are using the BlogTheme and add a part to the Article type, it will not be rendered, you would need to update the related liquid view template to explicitly render your part. Or use another theme already using the full shape system.

---

So for my tests with a TestPart that has a Text1 Textfield i used TheTheme using the full shape system. To render the Text1 field i could have used the shape system but because i created TestPart from the admin Liquid will not allow to access its properties (before the access strategy was added automatically), so i used the ContentItem.Content json data.

    Testing

    // Here i can't use the shape system, only the the json data.
    Test1: {{ Model.ContentItem.Content.TestPart.Text1.Text }}

    Test2: {{ Model.ContentItem | display_text }}

And the output was

    Testing Test1: My Text1 field in my TestPart Test2: About

**Comment by datdv260497** [comment]
> @datdv260497
> 
> Just tried it works but not e.g. under TheBlogTheme because of the following reason
> 
> In the BlogTheme the views are not using the full shape system, but a mix of rendering data directly from e.g. the content item Content json data as in the database, and of rendering e.g. a given part / field by using the shape_render filter.
> 
> ```
> // Use the Content json data as persisted in the db
> {{ Model.ContentItem.Content.Article.Subtitle.Text }}
> 
> 
> // Use the shape system, Model is a zone holding shape, Content is a zone shape, and so on
> {{ Model.Content.HtmlBodyPart | shape_render }}
> ```
> 
> So if you are using the BlogTheme and add a part to the Article type, it will not be rendered, you would need to update the related liquid view template to explicitly render your part. Or use another theme already using the full shape system.
> 
> So for my tests with a TestPart that has a Text1 Textfield i used TheTheme using the full shape system. To render the Text1 field i could have used the shape system but because i created TestPart from the admin, Liquid will not allow to access its properties (before the access strategy was added automatically), so i used the ContentItem.Content json data.
> 
> ```
> Testing
> 
> // Here i can't use the shape system, only the json data.
> Test1: {{ Model.ContentItem.Content.TestPart.Text1.Text }}
> 
> Test2: {{ Model.ContentItem | display_text }}
> ```
> 
> And the output was
> 
> ```
> Testing Test1: My Text1 field in my TestPart Test2: About
> ```
> 
> **Update**: Finally i could get the following working using shape data and rendering (not the json data)
> 
> Test1: {{ Model.Content.TestPart-Text1.Text }}
> Test1: {{ Model.Content.TestPart-Text1 | shape_render }}
> 
> Test1: {{ Model.Content["TestPart-Text1"].Text }}
> Test1: {{ Model.Content["TestPart-Text1"] | shape_render }}
> 
> Note: Yes i know it's confusing but `Model.Content` is a shape, `Model.ContentItem.Content` is a json object.

![image](https://user-images.githubusercontent.com/49801948/116978618-29e50180-acee-11eb-9732-e5ea5f8c9662.png)
![image](https://user-images.githubusercontent.com/49801948/116978815-6ca6d980-acee-11eb-8d84-34be9cc18605.png)
![image](https://user-images.githubusercontent.com/49801948/116978891-81836d00-acee-11eb-84ec-d819b36933ab.png)
Hmm, It not working for me. Liquid not run when I add part template

**Comment by jtkech** [comment]
Just took a look at the cms module template code

Looks like the sample part name is `MyTestPart`

Also just remembered taht there was a typo somewhere, in one place `TestPart` was used in place of `MyTestPart`

So maybe retry it with the last dev packages from the cloudsmith feeds and / or with the `TestPart` name

**Comment by agriffard** [comment]
The module template has been changed recently in #9334

**Comment by jtkech** [comment]
Okay thanks @agriffard 

The missing liquid registration that has been added may explain the issue here

            services.Configure<TemplateOptions>(o =>
            {
                o.MemberAccessStrategy.Register<MyTestPartViewModel>();
            });

**Comment by datdv260497** [comment]
Thanks so much, @jtkech . I added liquid registration and this problem resolved.
