### ISSUE TITLE
Liquid Page title with filter

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#9160]
During meeting, we talked about #9159.
@sebastienros said there might be a way to do it in one line.

I think he refered to a ​https://github.com/sebastienros/fluid/blob/main/Fluid/Ast/FilterExpression.cs and to use it instead of an Expression:
https://github.com/OrchardCMS/OrchardCore/blob/7ff46997d7b1d094102a895195646ef66d54eb90/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/Tags/RenderTitleSegmentsTag.cs#L25

**Comment by sebastienros** [comment]
I meant that: https://github.com/OrchardCMS/OrchardCore/blob/1ec2e9898ff37e49d4224732c8a3e0acb5ed2fa6/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/LiquidViewParser.cs#L21

But it's actually not possible since it accepts a list of arguments, and arguments can't be direct filters.
