### ISSUE TITLE
Formula field

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9163]
Add a Formula field that is not editable but has a pattern similar to the `TitlePart`. This will allow us to have fields that aggregate other pieces of content.

**Comment by Skrypt** [comment]
Elaborate an example where it would be better than using a Liquid template pattern?

**Comment by deanmarcussen** [comment]
also a duplicate (and designed) of https://github.com/OrchardCMS/OrchardCore/issues/4972

**Comment by hishamco** [comment]
Can we close this and keep #4972 open?
