### ISSUE TITLE
TitlePart pattern is cutoff when using a long pattern

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9165]
See the screenshot

![image](https://user-images.githubusercontent.com/4681586/114646392-2808bf00-9ca9-11eb-9b2c-448fe340d1b0.png)

**Comment by Skrypt** [comment]
We should maybe update these using the new Monaco editor. Else this should be an easy css fix.

**Comment by hishamco** [comment]
CSS fix may be easier and better in this case, can you do it Jasim or I will handle it?

**Comment by Skrypt** [comment]
Go for it.

**Comment by jptissot** [comment]
I think this occurs in other fields (Saw it with the Query editor as well @hishamco)

**Comment by hishamco** [comment]
I will have a look to the Query editor too

**Comment by jptissot** [comment]
Occurs on all CodeMirror fields in the admin I think.

**Comment by hishamco** [comment]
After a quick I realise it's a bug in CodeMirror but I forgot to update you guys, but @jptissot mentioned what I wanna wrote

I need to confirm if the bug cause by other style or a CodeMirror bug

**Comment by jptissot** [comment]
After we merge the Monaco PR, we should move most of the patterns to the monaco editor

**Comment by Piedone** [comment]
This pattern now uses the Monaco editor and thus the code can be arbitrarily long.
