### ISSUE TITLE
Azure AD B2C not returning email claim causes OrchardCore not able to pass the registration view

### ISSUE THREAD

**Issue by weimarcoro** [OrchardCMS/OrchardCore#9169]
### OrchardCore presents a blank Email field in the registration view after successfully logged in with Azure AD B2C using OpenID protocol and implementation  
The missing email claim is a known issue here:
- https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/19526191-openid-connect-id-token-is-missing-email-claim
- https://github.com/MicrosoftDocs/azure-docs/issues/16566

### To Reproduce
1. Have an OrchardCore CMS site running configured to use OpenID client with Azure AD B2C
2. Click on the new option to Login using the external provider
3. Login with an existing Azure AD B2C user not registered in OrchardCore
4. Notice that /OrchardCore.Users/Account/ExternalLoginCallback shows the Email field as blank

<img width="807" alt="image" src="https://user-images.githubusercontent.com/12765172/114748447-f1ba5680-9d1f-11eb-8eb7-3ef33dea4d85.png">

### Expected behavior
OrchardCore should look for other claim(s) to obtain email information in case email claim is missing which is the case of Azure AD B2C. Perhaps look inside emails array?

<img width="839" alt="image" src="https://user-images.githubusercontent.com/12765172/114749063-8755e600-9d20-11eb-9cc9-1f4338b167e1.png">

### Notes
We were able to map name claim from Azure AD B2C to the Username using IExternalLoginEventHandler implementation but there is not option to work with email in that interface.

Maybe add more logic in AccountController line 436 where the email is retrieved to look alternatively for the emails claim? Something like:
```c#
var email = info.Principal.FindFirstValue(ClaimTypes.Email) ?? info.Principal.FindFirstValue("email") ?? info.Principal.FindFirstValue("emails");
```

**Comment by MichaelPetrinolis** [comment]
You could map signInNames.emailAddress to 'email' claim and then it will work as expected. 'emails' is not a standard open id claim

**Comment by weimarcoro** [comment]
@MichaelPetrinolis thanks for your answer. However, do you mean map the claims inside Azure AD B2C custom policies, right? If so, I have already tried that but there is another bug preventing that workaround to be a solution. The bug here: https://docs.microsoft.com/en-us/answers/questions/50355/unable-to-sign-on-using-custom-policy.html

**Comment by Piedone** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/3712
