### ISSUE TITLE
Add warning in content preview when disconnected from editor

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/OrchardCore#917]
Hi,
Right now, when the user in the admin navigates to a different page, save or publish changes, the preview window does not update. Even if the user comes back again to edit the same content item, he would need to start a new preview window. The previous one remains "frozen".
I think it would be better if we display a little warning to make obvious that the preview is not functionnal anymore.

**Comment by Skrypt** [comment]
Maybe closing the preview tab since this is what will happen ultimately.

**Comment by matiasmolleja** [comment]
I think that te best user experience would be:
1. Click preview.
2. Expend some time undocking and sizing the preview window.
3. Edit my content ítem while previewing.
4. Save or publish my  content ítem. The preview window notify that its disconnected. But it remains open and the size I like it.
5. I edit a different content ítem, or the same.
6. The preview window automatically detect that Im editing again and load the currently edited content item.

**Comment by matiasmolleja** [comment]
My pull request only addresses the first and easiest part of that scenario, I'm afraid.

**Comment by sebastienros** [comment]
Popup is sufficient for now from having users lost as they would not see updates.
And I agree that the window should be reused when we edit a new content item, even if there could be side effects while editing two content items at the same time, that's an acceptable edge case. This can easily be done by removing the unique id in the content preview filter. We can still open as many preview windows, but they will all show the same content.

And maybe also be able to reuse the preview window for the templates preview, but later as it's harder.

**Comment by matiasmolleja** [comment]
I removed the unique id and now it is using the same window as you edit different content items.
There are a couple of small issues though:

- When the user leaves the editor, the preview displays "not connected" warning. After that, if the user goes to a different content item, the warning is still there even when the preview is connected again. Only when the user starts writing something, the warning is hidden again. It can be fixed by adding a call to "sendForm()" on the document.ready() event of the editor. That will write to the localStorage and will raise the required event on the preview window. Not sure if this small issue worth a writing to the disk on each load of the editor.

- Performance degrades as you keep opening several simultaneous previews. I think that is because localStorage writing and reading is synchronous. Not sure if this needs to be fixed or we can leave it as it is.
