### ISSUE TITLE
Nullable reference types in Razor Views

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#9173]
### Describe the bug
We're trying to enable [nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) in our site. This seems to work well except for this problem we are having with Razor views.

![image](https://user-images.githubusercontent.com/68876423/114777823-1c1d0b80-9d42-11eb-9a70-408a09ad3535.png)

What's strange is that this error only happens at runtime. Thinking that maybe this has something to do with runtime compilation of Razor views, I temporarily removed the `<PreserveCompliationReferences>` element from my project to disable runtime compilation. When I relaunched my site I had no Razor compilation errors and everything worked correctly. I should mention that at no point did I make a change to my view while the site was running. I got the error on a view that should have already been compiled.

The error does go away if I add `#nullable enable` to the view but it seems weird that I would need to do that and unfortunately easy to miss, since this doesn't cause a compile-time error.

### To Reproduce
1. Enable runtime compilation of [Razor views](https://github.com/OrchardCMS/OrchardCore/issues/6565#issuecomment-655761866)
2. Enable nullable reference types in a module (probably easiest to make a new module)
3. Create a simple controller with an endpoint that returns a Razor view
4. Use a nullable reference type in that Razor view. I just added a short snippet like this
`@{
    string? name = "This is a test";
}`
5. Navigate to that endpoint

EDIT: This is 1.0.0-rc2-16060 and my environment is DEVELOPMENT.

**Comment by jtkech** [comment]
Yes, if you remove `PreserveCompliationReferences` it is set to false by default by aspnet (before it was true by default) and then no `refs` folder is outputed, so there is no runtime compilation.

The other condition to use runtime compilation is to be in `IsDevelopment()` mode so that it is not used in production mode. But which version are you using? Recently we did a change because even if in production mode a first razor runtime compilation was still done, this no more the case.

**Comment by jtkech** [comment]
Historically, before, even if in production, we were allowing runtime compilation but only for razor views defined at the application level.

**Comment by rjpowers10** [comment]
@jtkech This is 1.0.0-rc2-16060 and my environment is DEVELOPMENT.

**Comment by Piedone** [comment]
Is this still applicable, @rjpowers10?

**Comment by rjpowers10** [comment]
@Piedone it's been some time since I encountered this issue, and I just tried adding a nullable string to one of my templates and didn't get the runtime error. I'm fine with closing this.
