### ISSUE TITLE
Orchardcore with .net5.0 version can't deploy in mysql database

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#9188]
Orchardcore with .net5.0 version can't deploy in mysql database , 
error happen: "The requested tenant is currently initializing". then never step into next.

**Comment by deanmarcussen** [comment]
You will need to check your log files in `App_Data\Logs`.

Likely there is a problem with the login (I tested MySql last week, and it worked fine)

**Comment by ntdung** [comment]
@jnucpz Can you try to deploy with that DB and recipe is SAAS? I can only deploy the site with that recipe with Postgre and MS SQL. The setup site run forever if I choose to setup with other recipes.

**Comment by jnucpz** [comment]
@deanmarcussen   Because it still be "The requested tenant is currently initializing"; So, the folder files App_Data\Logs and App_Data\Sites is null. just create the two folder. 
I check the Mysql Database, the document and identifier record have create. But Can't be initialized.
![图片](https://user-images.githubusercontent.com/17457950/115031725-10c11000-9efb-11eb-91bc-731a92ccb69f.png)

**Comment by jnucpz** [comment]
I test the version serveral days ago, it work fine. so, the reason maybe some new changed code.

**Comment by giannik** [comment]
I am having the same issue with sql server with latest dev when trying to create a tenant.
Works well with mysql.

**Comment by deanmarcussen** [comment]
Ok, I could repro.

@jtkech looks like something in this https://github.com/OrchardCMS/OrchardCore/pull/9005 is causing it.

Commit before seems to succeed ok.

**Comment by jtkech** [comment]
Okay, just tried, i could repro

I will work on it this night

**Comment by jtkech** [comment]
Good progress

Now it fails during the setup (on sql server) when resolving all `IPermissionProvider`

So under the debugger i stepped into the services resolved through the above providers

It fails when resolving the `IDynamicCacheService`

Removing the registration of this service fixed the issue

Still investigating

Note: So many services are resolved through `IPermissionProvider` resolution !!!
