### ISSUE TITLE
NullReferenceException in BuildDisplayAsync if used content type deleted

### ISSUE THREAD

**Issue by Brendan-csel** [OrchardCMS/OrchardCore#9198]
### Describe the bug
Deleting a used content type results in a `NullReferenceException` and complete page failure.  After playing around with some new (unfortunately home) page content the CMS user decided to "undo " their work and deleted a Content type without realizing it was still used on the home page content item.

This error not only broke the public home page - but also in the Admin content item view if they tried to "fix" the home page.

I also had a lot of trouble tracing and resolving this issue.  There is no reference to the deleted type (or containing item) in the logged error.  Luckily I was able to manually doctor the JSON stored in the database document but only because the user was able to give me a very distinctive name for the deleted content type. 

### To Reproduce (in either RC2 or current DEV)
1. Use templates to `dotnet new occms` and create site with Blog template.
2. Log in to Admin section and delete `Blog post` content type.
3. Refresh home page to see `NullReferenceException` in `OrchardCore.ContentManagement.Display.ContentItemDisplayManager.BuildDisplayAsync`
4. Go to `Content Items -> Blog` to see `NullReferenceException` in `AspNetCore._Areas_OrchardCore_Lists_Views_ListPart_DetailAdmin.ExecuteAsync`

### Expected behavior
This list is listed from ideal outcome to minimum:
1. Ideally the user would have been blocked from deleting the used content type in the first place (some kind of foreign key violation).  This would mitigate trying to catch all the places were something might break if this happens.
2. Add a guard in any code that might be impacted by a used content type being deleted.  From the website consumers perspective they should not see an error page but perhaps just a missing portion of content - like some kind of visual "error boundary" around content items.
3. Logging would offer some clues to the content causing the issue.

**EDIT: sorry originally used the term `content part` a lot above and should have been `content type`**

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/1014
