### ISSUE TITLE
Properties not accessible from liquid

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9199]
### Describe the bug

Blank values are returned when trying to access the Shape `Properties` property.

```
{{ someContentItem| shape_build_display | shape_properties: someProp: "SomeValue" | shape_render }}
```

```
{{ Model.Properties.SomeProp }} // this return blank
{{ Model.SomeProp }} // this works
```

**Comment by jtkech** [comment]
@jptissot 

Yes because in the `ShapeAccessor` we don't support `Properties` as a property ;)

But the accessor also looks into the `Properties` when you want to access a given property e.g. `SomeProp`

So the following don't work

    {{ shape.Properties.SomeProp }}
    {{ shape.Properties["SomeProp"] }}

But the following works

    Test1: {{ shape["SomeProp"] }}
    Test2: {{ shape.SomeProp }}

Do you think it is still an issue?

**Comment by jptissot** [comment]
> Do you think it is still an issue?

I think we should support both, for backwards compatibility?  

At a minimum, we should update all references to `.Properties` in the docs if we choose to keep it like it is. https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#shape_add_properties

**Comment by jtkech** [comment]
Okay, will do a PR asap ;)
