### ISSUE TITLE
Widget parts can't be templated

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#9201]
The current part alternates work only for Content stereotype. A mitigation is to define a part template for the widget's type.

We should be able to customize a part for any stereotype, independently of the type. Such that when the same part is attached to different widget types, the same template can be used.

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentItemDisplayCoordinator.cs#L138

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentPartDisplayDriverTPart.cs#L46

**Comment by sebastienros** [comment]
Delete this code to fix the alternate name with a stereotype: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentPartDisplayDriverTPart.cs#L46-L49

Currently 3 `_` are added, e.g. `Widget___Summary__AddressPart`

**Comment by ns8482e** [comment]
We don't need these lines

https://github.com/OrchardCMS/OrchardCore/blob/8279ca1b16b39a1dde5e26f7a19ff9cd42f93cdd/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentPartDisplayDriverTPart.cs#L46-L49

As, following line altready adds prefix `_` later when alternates are generated

  `displayTypes = new[] { "_" + ctx.Shape.Metadata.DisplayType };`

**Comment by sebastienros** [comment]
Do you want to submit a PR with just this fix? We should also add a line in the Widgets documentation to mention this kind of alternate is available.

**Comment by sebastienros** [comment]
But it also need to work with dynamic parts

**Comment by ns8482e** [comment]
I'll create PR - moving code from the other PR

**Comment by deanmarcussen** [comment]
When registered as a model with AddContentPart<TPart> L136, part.GetType() == typeof(ContentPart) prevents the coordinator from adding alternates.

A dummy driver for dynamic hard type parts might be useful to trigger the TPart driver alternates without running the risk of accidentally running dynamic part code in the coordinator
