### ISSUE TITLE
Workflow task [Create Content]

### ISSUE THREAD

**Issue by timeshift92** [OrchardCMS/OrchardCore#9205]
### Is your feature request related to a problem? Please describe.
when declaring a task to create content
it is necessary to get the dryness of the content from the table,
is it possible to make it autocomplete?

### Describe the solution you'd like
I selected the content type and the content properties were filled with json of the given entity

**Comment by jptissot** [comment]
I think this would be a good enhancement. I am working on building a feature that would allow site administrators to output the json format of a content type.

**Comment by timeshift92** [comment]
> I'm not sure what you mean by "dryness". Do you mean that Content Properties should be automatically populated with all the possible properties a content type (and its parts/fields) can have?

yes I meant it, sorry the translator sometimes does not translate correctly

**Comment by timeshift92** [comment]
> I think this would be a good enhancement. I am working on building a feature that would allow site administrators to output the json format of a content type.

thanks, as a beginner, I may not know the exact structure of the content, this feature would make life easier for newbies like me =)

**Comment by Piedone** [comment]
Closing as per https://github.com/OrchardCMS/OrchardCore/pull/9388#issuecomment-1895341625.
