### ISSUE TITLE
Issue calling post method in xamrin forms

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#9216]
I have a module to Handel register users from Xamarin. 
It works fine by get, but it doesn't  work by post methods.

i get this return:

```
{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Date: Sun, 18 Apr 2021 01:09:34 GMT
  Server: Kestrel
  X-Powered-By: OrchardCore
  Forwarded: host=192.168.0.3:45455; proto=https
  Content-Type: application/problem+json; charset=utf-8
  Content-Length: 163
}}
```

i have this code in xamarin side:

```
    public static async Task<HttpRequestMessage > PostStreamAsync(object content, string Url )
    {

        using (var request = new HttpRequestMessage(HttpMethod.Post, Url))
        using (var httpContent = CreateHttpContent(content))
        {
            request.Content = httpContent;

            var response = await App.client
                .SendAsync(request, HttpCompletionOption.ResponseHeadersRead)
                .ConfigureAwait(false);
           
                response.EnsureSuccessStatusCode();
            
                return response.RequestMessage ;
        }
    }
```

and this is in orchard core side:

 ```
 [HttpPost]
        [Route("reg")]
        public async Task<IActionResult> RegisterInApp([FromBody] UserInformation RegisterVM)
        {
            try
            {
                if (RegisterVM == null)
                {
                    return BadRequest(ErrorCode.TodoItemNameAndNotesRequired.ToString());
                }

....
}
```

**Comment by hishamco** [comment]
I expect issue comes from using `FromBody` which expect the data come from an Html Form. One more thing why you didn't use OC APIs in users module

**Comment by overstartup** [comment]
> HttpClient.PostAsync

i used it, i have same issue.



> One more thing why you didn't use OC APIs in users module

How can i use it?

i thin it needs to add some CORS headers. i don't know what i should add. 
![image](https://user-images.githubusercontent.com/56995550/115148611-ade98900-a060-11eb-8139-4ca6ecede7b9.png)

**Comment by deanmarcussen** [comment]
Probably you are missing an `IgnoreAntiForgeryToken` attribute on the controller / method.

**Comment by hishamco** [comment]
> Probably you are missing an IgnoreAntiForgeryToken

May be

**Comment by overstartup** [comment]
@deanmarcussen @hishamco thank alot for your help. yes it needs IgnoreAntiForgeryToken . it works now
