### ISSUE TITLE
Possible issue with Postgresql with latest version.

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9218]
### Describe the bug

There seems to be an issue with postgresql with the latest version. These tests work locally but fail with PostgreSql
https://github.com/StatCan/StatCan.OrchardCore/runs/2372081966#step:7:219
```
[1:22:40 AM] fail: OrchardCore.ContentManagement.DefaultContentManager[0]
      => SpanId:0ff3207b4348e24b, TraceId:08643f4f1ab70f4eb07bda0914b4c6e4, ParentId:0000000000000000 => ConnectionId:0HM8211E9GQ28 => RequestPath:/t1efs495/ RequestId:0HM8211E9GQ28:00000035 => OrchardCore.Diagnostics.Controllers.DiagnosticsController.Error (OrchardCore.Diagnostics)
      IContentHandler thrown from OrchardCore.ContentManagement.Handlers.ContentPartHandlerCoordinator by ObjectDisposedException
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'IServiceProvider'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at OrchardCore.ContentManagement.Handlers.ContentPartHandlerResolver.GetHandlers(String partName)
         at OrchardCore.ContentManagement.Handlers.ContentPartHandlerCoordinator.LoadingAsync(LoadContentContext context)
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
```

**Comment by jtkech** [comment]
Yes there is a recent change when we call the contentmanager `GetAsync(multipleIds)` on multiple ids, we now call the loading / loaded events that involves the `ContentPartHandlerCoordinator`

I will first check if our all databases func test pass on the last dev

**Comment by jtkech** [comment]
All databases func test passed on our CI for the dev branch

I saw that this is the `hackathon.js` func test that fails on your CI

**Comment by jtkech** [comment]
There is the `content_item_id` liquid filter that, when applied on multiple ids, calls the contentmanager `GetAsync(multipleIds)` on multiple ids.

Only for testing can you try to remove the usage of this `content_item_id` filter in your hackathon liquid views.

    {% assign challengeSelected =  Model.ContentItem.Content.Team.Challenge.ContentItemIds | content_item_id %}

**Comment by jptissot** [comment]
@jtkech I just tried with a pg database locally and I am getting the same exception: 

![image](https://user-images.githubusercontent.com/4681586/115152860-fb55fe00-a040-11eb-9bbb-8c27ad6eea2f.png)

I will investigate a bit further today.

**Comment by jtkech** [comment]
> @jtkech I just tried with a pg database locally and I am getting the same exception:

Even if you remove the usage of the `content_item_id` liquid filter ?

Does it work with sqlite or sql server ?

**Comment by jptissot** [comment]
@jtkech I just tested it manually. The issue occurs when Enabling the Hackathon Feature

**Comment by jptissot** [comment]
As discussed, this issue seems to happen because of this piece of code: https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.Hackathon/Indexes/Migrations.cs#L80

Adding a Deferred task fixes the issue. https://github.com/StatCan/StatCan.OrchardCore/pull/229/files#diff-0b452c5fb3d9ac8b9ddf3f159ea6f82d566a524795c05373f38301a25bf74782R84

**Comment by deanmarcussen** [comment]
Dude. That’s an async void method. Of course it will fail :(

CreateAsync with an await

**Comment by jtkech** [comment]
Oops, didn't see this

Use `public async Task<int> CreateAsync() => await CreateHackathonUsersIndexAsync()`
And also use `private async Task CreateHackathonUsersIndexAsync()`

**Comment by jtkech** [comment]
@jptissot 

But that's okay to still use the deferred task

So i close this one knowing that you now have another issue #9222
