### ISSUE TITLE
Is it possbile to register a local user without email?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#9220]
Is it possible to register a local user without email?

In my scenario, only username and password are required, no email address is needed.

Many thanks!

**Comment by orchardc** [comment]
Hi @Skrypt , is it not a valid proposal?

**Comment by orchardc** [comment]
Closed as thumbdown.

**Comment by aaronamm** [comment]
@orchardc I think your question makes a lot of sense. There are some external providers that do not need user's email.
I think an email should be set as optional for registration flow. 
A developer can set as require later if one need it.
