### ISSUE TITLE
LiquidPart alternate doesn't render anything with {{ Model.Html | liquid }}

### ISSUE THREAD

**Issue by pivielti** [OrchardCMS/OrchardCore#9221]
### Description
I updated the NuGet packages from version 1.0.0-rc213527 to version 1.0.0-rc216115. after that the Alternate of the Liquid Part contained in my Theme project (LiquidPart.liquid) was rendered, but the {{ Model.Html | liquid }} that worked before doesn't render anything anymore.

When I try to see the model' data with {{ Model | json }}, i see that the liquid part is present, but impossible to render it. If I remove my Alternate, then the default template is rendered correctly.

I have one Web project that uses the following packages :
- OrchardCore.Hosting.Console (1.0.0-rc1-10004, the only one available)
- OrchardCore.Logging.NLog
- OrchardCore.Application.Cms.Targets

And another Theme project that uses :
- OrchardCore.Theme.Targets
- OrchardCore.ContentManagement
- OrchardCore.DisplayManagement
- OrchardCore.ResourceManagement

**Comment by jtkech** [comment]
@pivielti 

Just tried it works

In the Admin you may have to go to the content type definition, edit the related content type, go to the setting of the involved part, and uncheck the Html Sanitization option

**Comment by pivielti** [comment]
@jtkech 

Sorry but i don't have this option in the [LiquidPart](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Liquid/Views/LiquidPart.cshtml). Its only [available ](https://docs.orchardcore.net/en/dev/docs/reference/core/Sanitizer/) with Html and Markdown Parts or Fields.

**Comment by jtkech** [comment]
Ah okay, i will test it with a LiquidPart this night

**Comment by pivielti** [comment]
Thank you very much ! 

Another element : my theme contains the **LiquidPart.liquid** width the markup 
```
<div class="w3-container">
  {{ Model.Html | liquid }}
</div>
```

The div.w3-container is rendered, but not the Html inside... I changed the extension to use a **Razor** view instead and I adapted the markup :
```
<div class="w3-container">
  @Html.Raw(Model.Html)
</div>
```
Now the html is fully rendered. So i have a workaround but it is the only razor file in my theme 👎

**Comment by deanmarcussen** [comment]
It’s just missing the template view model registration for the LiquidPartViewModel @jtkech

**Comment by jtkech** [comment]
Ah okay, another one ;)
