### ISSUE TITLE
Potential issue with fluid

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9223]
### Describe the bug

Not 100% sure what is happening. The bug seems to be intermittent. Sometimes the data does not load properly on the following page: https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.Hackathon/Views/Widget-TeamDashboardWidget.liquid#L5

Sometimes the `teamContentItemId` is null when it should not be. I doubled check the database (postgresql) and the data is there. Plus, reloading the page a random number of times sometimes set's that variable properly, sometimes not.

Adding this to the view below the variables: 
```
Variable: {{teamContentItemId}} <hr/>
Direct(.first): {{user.Properties.Hacker.Hacker.Team.ContentItemIds.first}} <hr/>
Direct(first filter): {{user.Properties.Hacker.Hacker.Team.ContentItemIds | first}} <hr/>
Team: {{team.ContentItem.Content}}
```
Outputs this: 
![image](https://user-images.githubusercontent.com/4681586/115155868-beddce80-a04f-11eb-8da4-259c01e043d1.png)

**Comment by jptissot** [comment]
Odd thing is that this if executes properly (true) but the variable is blank ? 
https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.Hackathon/Views/Widget-TeamDashboardWidget.liquid#L12

**Comment by jptissot** [comment]
Reloading the page multiple times displays properly, totally random:

![image](https://user-images.githubusercontent.com/4681586/115156054-87235680-a050-11eb-8261-17af6a586892.png)

**Comment by jtkech** [comment]
It doesn't fix the issue but in your liquid better to use `!= nil` in place of `!= null`.

**Comment by jptissot** [comment]
I am pretty sure this issue stems from this fluid pr: https://github.com/sebastienros/fluid/pull/303

**Comment by jptissot** [comment]
This commit fixes the issue: https://github.com/sebastienros/fluid/commit/9066957e5117447bed4084b7d1100527058cfbdb
