### ISSUE TITLE
Some parts & fields disapeared of Content Items after I migrated to the latest version

### ISSUE THREAD

**Issue by pivielti** [OrchardCMS/OrchardCore#9234]
### Description
I migrated a little website that uses SQLite DB. **In my local environment all is running fine**. But once deployed (with _dotnet publish_ command), lots of my custom content items become uneditable because the Edit page doesn't render some parts or fields. However the content definition is okay.

All the custom Content Items was created via the Admin Zone. The single development of my application is the Theme.

Any idea of what could causes that ?

### **Exemple of the Edit Page of one of a Content Item:**
![image](https://user-images.githubusercontent.com/12090666/115294174-8c6bc880-a158-11eb-8427-e2bbddb7eafe.png)

### **The definition of the Content Item:**
![image](https://user-images.githubusercontent.com/12090666/115294302-bd4bfd80-a158-11eb-9a0e-32914160a679.png)

**Comment by doticca** [comment]
Also noticed that some shared views cannot be found anymore on a published environment.
After remote debugging found out that ShellViewFeatureProvider is not returning any assemblies with views.

**Comment by jptissot** [comment]
Do you have repro steps? I was not able to reproduce this.

**Comment by doticca** [comment]
@jptissot I am using OrchardCore to build a modular application and I am not sure if that helps but version 1.0.0-rc2-16045 is the last version for which I get results from SharedViewLocationExpanderProvider in a published to Azure App service.
My debug findings is that for versions 1.0.0-rc2-16046+ the following code (at SharedViewLocationExpanderProvider constructor) returns zero results:

```
var moduleSharedViewFilePaths = fileProviderAccessor.FileProvider.GetViewFilePaths(
                            module.SubPath + "/Views/Shared", RazorExtensions,
                            viewsFolder: null, inViewsFolder: true, inDepth: true);
```

**Comment by jtkech** [comment]
@doticca About the shared views if in prod (`!IsDevelopment()` and with a `refs` folder outputed under the bin folder, yes since #9047 to prevent some razor compilation in prod, but there is a missing change, i will update it this night.

In the meantime the workaround would be to not output the `refs` folder when publishing to prod, this y removing from your app project `PreserveCompilationReferences = true` or set it to false but normally it is now the default.

@pivielti not sure it will fix your issue, will see.

**Comment by pivielti** [comment]
@jtkech Sorry but the problem is not solved by your commit. I tried with rc2-16130.

I'm working on repro steps to give you soon.

**Comment by doticca** [comment]
@jtkech the issue of my comment is solved, thank you!

**Comment by jtkech** [comment]
@pivielti 

No problem, so i re-open the issue

@doticca Good to know it fixed your issue, thanks

**Comment by sebastienros** [comment]
@pivielti since you also opened https://github.com/OrchardCMS/OrchardCore/issues/9244 it might be related. Please try a clean rebuild.

**Comment by pivielti** [comment]
I did a clean rebuild and also a clean deploy. Now the fields appears again. Thank you very much.
