### ISSUE TITLE
Concurrency checking in Orchard Core

### ISSUE THREAD

**Issue by randaratceridian** [OrchardCMS/OrchardCore#9242]
Can somebody describe what concurrency checking exists in Orchard Core? I've seen a few references to it having optimistic concurrency checks, but we can't seem to make them raise an error if two editors change a page at the same time. The last one in overwrites the second.

I can see references to checkConcurrency in https://github.com/OrchardCMS/OrchardCore/issues/7449 from Oct 2020, so I assume it exists in RC2. 

Can somebody provide an update on what exists and what state it is in?

**Comment by hishamco** [comment]
I remembered there 's an opened issue, the content editing doesn't have concurrency check AFAIK, I will have a look to the issue and reference it

**Comment by Piedone** [comment]
I think this is what you mean, Hisham: https://github.com/OrchardCMS/OrchardCore/issues/8900

I suggest you to check out the linked issue, it contains a lot of info on what's happening if this is what you mean.

**Comment by hishamco** [comment]
I don't think that's the issue ...

**Comment by hishamco** [comment]
Here it is #4540

**Comment by Piedone** [comment]
Nothing else required here, this was a question.
