### ISSUE TITLE
Validation of ContentPickerField in API call

### ISSUE THREAD

**Issue by EricArita** [OrchardCMS/OrchardCore#9243]
### Describe the bug
ContentPickerField is not validated when we create a new ContentItem by calling API '.../api/content' in Postman or any SPA 

### To Reproduce
1. I have 2 content types: Category and Product They have a 1-many relationship, 1 Category has many Products.
2. To perform this relationship, in Product type, I used a ContentPickerField namd CategoryID and link it to Category, this field is required, not allow mutiple to ensure a Product must belong to one and only one Category
3. Then I created a contentItem of type Product, if you leave ContentPickerField empty, it will alert an error and prevent you from creating new contentItem until you set a value for ContentPickerField. It's OK

![image](https://user-images.githubusercontent.com/30250345/115502653-76b4eb00-a29f-11eb-83ec-e932fa4f1dc2.png)

4. Finally, I tried to create a Product contentitem by calling API 'api/content' in Postman, SPA or any tools, but I left contentItemIds field empty and It still allowed me to create, there was not any error thrown. The data constraint was broken.

![image](https://user-images.githubusercontent.com/30250345/115501732-efb34300-a29d-11eb-9e1a-40bec3102834.png)
![image](https://user-images.githubusercontent.com/30250345/115501733-efb34300-a29d-11eb-900f-476a39092c8c.png)

### Expected behavior
So I expect the ContentPickerField will be validated like the way we do in admin UI, maybe it should response any errors instead of creating a new content item with empty value in content picker field

**Comment by deanmarcussen** [comment]
It was designed that API / ContentManager validation should not reflect UI validation rules, as there were / are too many scenarios where content created via an API may need different validation rules.

For API validation you can implement an `IContentHandler` or `IContentPartHandler` , `ValidatingAsync` method to provide the validation you would like to apply.

See https://github.com/OrchardCMS/OrchardCore/blob/3b1e4cb0769f694d8f95a128122c8454044fc658/src/OrchardCore.Modules/OrchardCore.Autoroute/Handlers/AutoroutePartHandler.cs#L117 for an example.

We currently only validate `Autoroute` and `Alias` where the system depends on unicity for those values.

**Comment by EricArita** [comment]
oh I got it! thank you for this useful information
