### ISSUE TITLE
Setup: instruct browser to remember Email but forget Connection string 

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#925]
Currently on setup page Edge stores a list of used connection strings but does not store emails.
As connection string can contain password it is very insecure to allow browser to do that.
While disallowing it to store email is very inconvenient.

**Comment by agriffard** [comment]
Connection string text input replaced by password input in 51c62a0539454cc8be44af82b8f9b12284256c67 .

But wouldn't it be easier to just specify autocomplete="off" ?
