### ISSUE TITLE
Widgets needs to be manually published for an update to the content-type to take effect.

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#9252]
### Describe the bug
I have a content-type of a Widget stereotype with couple fields. I added the widget to a zone on the page and it shows up as expected. However, if I update the Widget content-type by adding a new field, that field won't show up on the widget automatically. For the widget to see the new field, I have to edit and save the widget for the new field to show up. Is this an expected behavior?

### To Reproduce
1. Create a Widget content-type with 1 field.
2. From the admin menu click on Design >> Widgets and add the content-type to a zone.
3. Verify that the widget is showing up
4. edit the content-type and add a new field.
5. Go to the front end where the Widget is visible, you'll notice that the new field is not visible yet.
6. Back to the admin menu, click Design >> Widgets and edit the widget you added earlier. In the edit page, click Publish. Now the new field should show up on the front-end.

### Expected behavior
When a content type is updated, all widgets should also get re-published. This should not be a 2 step process as it'll confuse people.

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/8316

The feature to support this is designed there
