### ISSUE TITLE
Asset Part - Content specific assets

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#9257]
I would like a part called Asset Part made for example.
This part would allow you to add assets such as pics and videos to a content item.
They would be specific to that item only.
There would be a setting which would allow you to add one or more assets.

I imagine when the user specific assets get done there would be 3 types of assets you can use in your content.
Global assets, user specific assets and content specific assets.

I can think of many scenarios where a app would want content specific assets such as a video streaming service.

**Comment by deanmarcussen** [comment]
I think you want to use the `MediaAttachedField` for this. It allows attaching media from the library to a specific content item.

**Comment by JoshTango** [comment]
I will rea the documentation for this.
But I don't want other users to see the media file

**Comment by JoshTango** [comment]
Do you mean the media filed?
I don't see an attached anywhere?

**Comment by JoshTango** [comment]
I think what is needed is a content specific folder.
So a folder in the media library called content with a sub folder of contentitem_id

**Comment by JoshTango** [comment]
In fact I would probably envision a field type called MediaUpload.
Then you would click the upload button in the content editor and choose your file to upload and it would go straight into the contentitem subfolder

**Comment by JoshTango** [comment]
Now if I use this mediafield part i noticed it creates a sub folder with the content item id and puts the file in this sub folder is this correct?

**Comment by JoshTango** [comment]
Is there something that will stop other users from seeing these files in their  media library if they dont have permission to see this content item?

**Comment by JoshTango** [comment]
I think maybe we can close this.

**Comment by JoshTango** [comment]
Ok I have tested this out and I am happy.  I know how their is a seperate content item folder for all associated media files.
