### ISSUE TITLE
ContentItem properties are reserved names but are not handled as such

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#9258]
### Describe the bug

The names of the properties on `ContentItem` (e.g. `Latest`, `Author` are actually reserved names: You can't create content types or named (reusable) parts with the same names, since you'll get an exception.

### To Reproduce
1. Create a content type named "Author", for example.
2. Try to publish an item of the type.
3. Receive a "JsonReaderException: Unexpected character encountered while parsing value..." exception form `ContentItemConverter`.

The same thing happens if you e.g. create a content type with the name "Latest", or if you add a named part with the name "Author".

### Expected behavior
Either no exception happens and the use-cases just work as usual, or I get validation errors when trying to create the type/add the part that I should choose a different name.

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/1514
