### ISSUE TITLE
"Buffer has already been rendered" exception

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9269]
I have a `Menu.liquid` where we render the Items in two different lists.
```
  {% for item in Model.Items %}
      {{ item | shape_render }}
  {% endfor %}

.....
  {% for item in Model.Items %}
      {{ item | shape_render }}
  {% endfor %}
```

This exception occurs. Removing the second for loop fixes the issue.

![image](https://user-images.githubusercontent.com/4681586/115869506-f8c22280-a40b-11eb-8504-eb91143a81cd.png)

As requested, moved the issue from https://github.com/sebastienros/fluid/issues/318

**Comment by jtkech** [comment]
Yes, it can only be rendered once, yes you need to use capture or assign intermediate vars

We already talked about releasing these view buffers at the end of of the scope

I will think about it
