### ISSUE TITLE
Should Orchard be using email instead of username

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#927]
It appears to be the more common practice to use email address nowdays rather than a username to login with especially if you want to implement third party auth (like social login).

Should Orchard Core be following this trend rather than using username?

**Comment by Skrypt** [comment]
Both is fine as long as a email is required.

**Comment by scleaver** [comment]
So users can sign in with email instead or username?

**Comment by sebastienros** [comment]
See https://github.com/OrchardCMS/Orchard2/issues/739#issuecomment-323624200

**Comment by sebastienros** [comment]
Maybe we just need to do two lookups in the controller ... I can see how it could be confusing.

**Comment by scleaver** [comment]
I agree Sébastien - I think the login username field should be "Username or password". A lookup would work although you may need to also prevent a email address being used in the username field in the registration process so you don't get the situation where someone uses an email address in the username... this may cause issues? A lot of sites/platforms seem to have dropped username altogether but your solution allows for choice of either I guess.
