### ISSUE TITLE
Change Permission ClaimType to "per"

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/OrchardCore#929]
In order to reduce size (e.g. on a default Administrator role ~20 permissions x 10 characters = from 200 reduced to 60 characters) and to align the claim type with some other standard-ish lowercase claim types, such as sub, iss, azp, etc., perhaps we should change the Permission ClaimType to "per" in Orchard.Security.Permissions:

`public const string ClaimType = "per";`

_See also discussion #813_

**Comment by PinpointTownes** [comment]
I suggest we stop using permissions claims as it's absolutely not scalable. Instead, we should make a database check in the permissions handler (with some caching to mitigate the perf implications).

/cc @sebastienros

**Comment by sebastienros** [comment]
Let's store roles only, and check for permissions in the handler with caching at the role level.

**Comment by kevinchalet** [comment]
Closing, as it's now quite complicated to change the claim type without breaking users (and moving to a dynamic DB-based permissions model would be a better idea anyway: https://github.com/OrchardCMS/OrchardCore/issues/929#issuecomment-377413683)
