### ISSUE TITLE
[image] Shortcode is not rendered from HtmlField/HtmlBodyPart

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/OrchardCore#9297]
shortcodes are drawn in html field/html body part when used in widget stereotypes only.

1. Create a Content Type
2. Add an Html body part
3. select [image] shortcode for an image in media
4. the output contains [image]imagename.yyy[/image] instead of the <img> tag

The same shortcode from TheAgencyTheme footer widget works

**Comment by deanmarcussen** [comment]
Hmm, I couldn't repro.

I just used the Article content type from the blog theme.

Is it possible you have a template for this that is not rendering the shape? 
Shortcodes are rendered automatically to the shape, but if you're rendering the `.Html` content directly, there are helpers / filters to render the shortcode.

**Comment by MichaelPetrinolis** [comment]
Thanx @deanmarcussen. I added an Html field on LandingPage content item in TheAgencyTheme, and draw it with {{ Model.ContentItem.Content.LandingPage.FieldName.Html | raw }}  I cannot find info in the documentation regarding drawing the Html and replace the shortcodes used.

**Comment by deanmarcussen** [comment]
`{{ Model.ContentItem.Content.LandingPage.FieldName.Html | shortcode | raw }}`

I can't see it in the docs either, so we must add it. there is an html helper as well
