### ISSUE TITLE
trumbowyg Editor error js with image

### ISSUE THREAD

**Issue by pchoisnard** [OrchardCMS/OrchardCore#9303]
### Describe the bug
I try to use the trumbowyg editor and I have this js error when I try to put an image from media.
The image is insert with shortcode but the option InsertMediaWithUrl has no effect
Version : 1.0.0-rc2-16145

Uncaught TypeError: trumbowyg.$ed.find(...).resizable is not a function
    destroyResizable https://localhost:44357/OrchardCore.Resources/Scripts/trumbowyg-plugins.js?v=6op-qHb7Ly78mJ03Nr4IbpUOI5UpTrNee0DSLd9xbVs:2380
    init https://localhost:44357/OrchardCore.Resources/Scripts/trumbowyg-plugins.js?v=6op-qHb7Ly78mJ03Nr4IbpUOI5UpTrNee0DSLd9xbVs:2461
    jQuery 5
        dispatch
        handle
        trigger
        trigger
        each

### To Reproduce
1. Go to Edit a content with an trumbowyg editor on an html field. I use the blog sample.
2. Add an media image
3. See error in javascript console

### Screenshots
![Capture](https://user-images.githubusercontent.com/49313832/116387186-d751a400-a81a-11eb-91eb-008e8b0e618b.PNG)

**Comment by hoanghai1212** [comment]
please fix this bug, I can't not inject image to my post now

**Comment by Skrypt** [comment]
Cannot repro in latest dev branch.
