### ISSUE TITLE
[docs] Incorrect usage of CustomSettings shown in video

### ISSUE THREAD

**Issue by weirdyang** [OrchardCMS/OrchardCore#9309]
### Describe the bug

In the video, the liquid expression used to to display the `CustomSettings` is incorrect.

this doesn't work:
{{ Site.Properties.NewSetting.Content.NewSetting.Brand.Text }} 

this works:
{{ Site.Properties.NewSetting.NewSetting.Brand.Text }} 

### To Reproduce

1. Create a new content type with stereotype `CustomSettings`
2. Add a text field named `Brand`
3. Populate the new custom settings via the admin menu
4. use the new custom setting in a liquid page

### Expected behavior
{{ Site.Properties.NewSetting.Content.NewSetting.Brand.Text }}  should display the text entered for the field.

**Comment by jptissot** [comment]
Maybe the video uses a pre-release version of this feature. The docs are correct (https://docs.orchardcore.net/en/dev/docs/reference/modules/CustomSettings/#liquid) Maybe we need to update the video as this would be a breaking change to current sites.
