### ISSUE TITLE
Error after upgrade to ".net core SDK 3.1.408"

### ISSUE THREAD

**Issue by MRSheikh** [OrchardCMS/OrchardCore#9314]
###
after upgrade to ".net core SDK 3.1.408" this error occurred:
`ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')`

**Comment by jtkech** [comment]
It is due to an aspnetcore security patch

It is fixed in OrchardCore but only in the last dev branch

So you may have to re-use a previous sdk or use our last dev packages from the cloudsmith feed

**Comment by MRSheikh** [comment]
> It is due to an aspnetcore security patch
> 
> It is fixed in OrchardCore but only in the last dev branch
> 
> So you may have to re-use a previous sdk or use our last dev packages from the cloudsmith feed

thanks a lot but I could not upgrade to last dev branch because you are using `mysqlconnector 1.3  ` and I am using `Pomelo.entityframeworkcore.mysql` that is used mysqlconnector < 1.0 in my modules. so when I add module to orchardcore project,  mismatch error occurs. 
do you have any idea ???

**Comment by MRSheikh** [comment]
**I upgrade these packages respectively for all of my modules and that works fine:** 
`---> Ef core 5.0
---> Pomelo.EntityFrameworkCore.MySql 5.0
---> OrchardCore 1.0.0-rc2-16160
`

**Comment by jtkech** [comment]
Cool 👍
