### ISSUE TITLE
AdminMenu: Lists item not displayed

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#9320]
### Describe the bug
When Lists item is added to admin menu, it is not shown in menu.

### To Reproduce

Create admin menu, add Lists element, alone or under placeholder, none of it works 

![image](https://user-images.githubusercontent.com/52829889/116565222-f416d600-a905-11eb-8cba-01a56db56a80.png)

![image](https://user-images.githubusercontent.com/52829889/116565166-e6f9e700-a905-11eb-8399-c71b1b4f92dc.png)

and also, sorting is not working too, even though it is setup in ListPart:
![image](https://user-images.githubusercontent.com/52829889/116565479-350eea80-a906-11eb-8634-fa77c18bf098.png)

**Comment by MikeKry** [comment]
setup example here:
http://try.orchardcore.fr/cb2h1vty/admin
admin / t_@$X53F

sorting works in there, but admin menu is not

**Comment by deanmarcussen** [comment]
I think you just need to a `TitlePart` to your list content type, and give it a title, or it will have no display text, so doesn't know what to display it with.

**Comment by Piedone** [comment]
Yep, that seems to be the issue, and thus nothing really to fix.
