### ISSUE TITLE
Web application is still allow authenticated user to access login page 

### ISSUE THREAD

**Issue by lengockyquang** [OrchardCMS/OrchardCore#9321]
**### Describe the bug**
Orchard Code still allow user to access login page even if user was already login and authenticated

**### To Reproduce**
1. Access to login page by  route /Login
2. Login as normal user or super user
3. After application redirect user to Admin page or Home page, access login page again with /Login and it still allow us to access login page

**### Expected behavior**
Orchard core should redirect user to home page if user already authenticated. Login page should only display for anonymous user

**Comment by Skrypt** [comment]
I'm not sure if it's an issue at all to be honest. The only thing is that we can login to a different account when we are already authenticated. The redirection to the home page is not what everyone will require either ; some people will want it to be redirected to their custom frontend user dashboard ... This is per case.

**Comment by lengockyquang** [comment]
You can refer https://dev.to as an example, Route '/enter' is their login page, after login success, i can't go back to the login page. I think i would be awesome if orchard core provides some configurations for admin to control this behaviour :D

**Comment by deanmarcussen** [comment]
I suggest a small piece of custom middleware to handle your required redirect before it reaches the controller.

As @Skrypt says it's per case, and much more easily handled with custom middleware, than us trying to please everyone.
