### ISSUE TITLE
Create OrchardWebHost.CreateDefaultBuilder()

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#934]
As Orchard default configuration is different from provided by `WebHost.CreateDefaultBuilder()` it would be nice to have specific `OrchardWebHost.CreateDefaultBuilder()`

@sebastienros, @Jetski5822, @PinpointTownes what do you think?

**Comment by Piedone** [comment]
This isn't applicable to the current source anymore.
