### ISSUE TITLE
Recipe commands for tenant operations

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#9348]
### Is your feature request related to a problem? Please describe.
Currently, you can manage tenants via the UI or the API. This proposal is about adding tenant management commands, to be used from recipes as well, allowing you to set up a multi-tenant app with ease. This is particularly useful for local development.

### Describe the solution you'd like
I'd add `tenant create` and `tenant setup` commands for tenant management. These could then be invoked in a commands recipe step to set up other tenants while setting up the Default tenant (if there's no bootstrapping problem with this, actually).

### Describe alternatives you've considered
Tenant management Workflows Tasks or the web API (from setup scripts) can be used for the same purpose too. However, commands would be more convenient and allow for compact local development environment initialization recipes.

**Comment by jtkech** [comment]
We always have a default tenant but that may be uninitialized,  and a tenant can be setup even if the default is not yet setup, we do this in unit tests. Unless if a tenant  depends on another one, e.g. an open id client depending on an open id server supported by e.g. the default tenant.

Maybe better to always have the default tenant running before doing the setup of other ones, this is what the AutoSetup feature does, hmm maybe the AutoSetup feature is just what you need, it is now validated by default, so you just need to set the required data (the tenants to setup, the recipes to use) in any config source (e.g. the root appsettings.json).

When i will have time i will think about it.

**Comment by Piedone** [comment]
Hmm, interesting. I did know about Auto Setup but didn't occur to me to use it as such. I think it nicely covers the use-case, even one particularity of using a non-SQLite DB.

What we do in our team is that while you can set up your dev env with SQLite, for parity with the prod env SQL Server is recommended. While with the default SQL Server config the connection string can be the same for everyone (it'll just refer to the server under ".") the DBs might be different: To allow working with multiple clones of the repo simultaneously, the DB will be prefixed by the parent folder's name (resulting in DB names like Clone1_DB, Clone2_DB...).

We do this with scripts currently but it can also be done with some hacking by overwriting values in the configuration, e.g. in the `Startup` of the web app:

```c#
var tenantCount = _configuration
    .GetSection("OrchardCore:OrchardCore_AutoSetup:Tenants")
    .Get<object[]>()
    .Length;

for (int i = 0; i < tenantCount; i++)
{
    _configuration[$"OrchardCore:OrchardCore_AutoSetup:Tenants:{i}:DatabaseConnectionString"] = "value based on arbitrary logic";
}
```

Thanks for the tip, JT, I guess commands aren't really necessary then.

**Comment by deanmarcussen** [comment]
For infos @Piedone we find both user secrets and key vault configuration useful for that cross dev environment / configuration.

Where user secrets can be used to provide dev specific configuration, and / or the same with keyvault. 

As user secrets loads in after the standard `appsettings.Development.json`, it provides some good overrides.

**Comment by Piedone** [comment]
That's a good idea too, thanks Dean.
