### ISSUE TITLE
Codegen template framework target

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#9350]
Currently these templates are not using multi-targetting.
We should probably update them to do so.

https://github.com/OrchardCMS/OrchardCore/blob/439982c5abea8e7615455d59b7b48810dedee13e/src/Templates/OrchardCore.ProjectTemplates/content/OrchardCore.Templates.Cms.Module/OrchardCore.Templates.Cms.Module.csproj#L4

/cc @agriffard

**Comment by hishamco** [comment]
They are using the `$(TargetFramework)` which is refer to the app target framework if I'm not wrong. Unless there's a variable called `$(TargetFrameworks)`

**Comment by Skrypt** [comment]
In source code we use the Directory.Build.props to define these modules to be using multi-targetting now. So, if I want to create a module from templates while using source code I need to edit the .csproj and remove the `<TargetFramework>` lines. Not much an issue since most dev will find the issue quickly. Though, if the .csproj was including something like

`<TargetFrameworks>$(TemplateTargetPackageFrameworks)</TargetFrameworks>`

That would be consequent to what we have in source code and allow people to do multi-target builds with a Nuget package solution too.

I'm missing one part here. I can't find/remember where this `$(TemplateTargetPackageFramework)` is set.

**Comment by Skrypt** [comment]
Ok found it. We are allowing choices to target netcoreapp3.1 or net5.0 when using the new feature of Visual Studio. But we have no option for multi-targetting. Need to see if it's a limitation with `dotnet new` templates.

**Comment by deanmarcussen** [comment]
I think you only really need to do multi target builds if you are packaging for consumption by both target apps. 

I do have a few external nuget packages like that, but most of our site modules are fine on the target the project is using. We wouldn’t multi target the project is what I mean.

so just trying to understand the use case for the templates to provide the feature?

**Comment by hishamco** [comment]
> I'm missing one part here. I can't find/remember where this $(TemplateTargetPackageFramework) is set.

This will be replaced by `$(TargetFramework)`

**Comment by Skrypt** [comment]
I just noticed that when I am creating a module from these templates that the framework target mismatch because I'm multi-targetting my Nuget Package solution. That's mainly why. Maybe I'm wrong in multi-targetting my Nuget package solution but I believe that if OC allows it then why wouldn't I be able to do it also on the Nuget package solution?

**Comment by deanmarcussen** [comment]
It’s allowed, of course, but it seems a bit unusual/ unnecessary to multi target a web/project solution.

It’s only going to want to run on one framework - the one you deploy to? Unless I’m missing something? So would just double build times for no reason.

necesary for published libraries of course, so there is a use case.

**Comment by sebastienros** [comment]
We don't need to multi-target custom projects. It's "just us" in the OC repository. If users still want to target something else then they change the csproj.

**Comment by Skrypt** [comment]
It's usefull if you want to migrate from netcoreapp3.1 to net50 and build it with the CI to test if things are broken or not. Then decide to move to net50 once everything works.
