### ISSUE TITLE
Cancelling the transaction not works as expected

### ISSUE THREAD

**Issue by intellimedhu** [OrchardCMS/OrchardCore#9363]
I have do the following in the same transaction:

1. Create a **new version** from a ContentItem
2. Create a new User

I call `ISession.CancelAsync()` when exception is thrown but a new version from a content item is created as latest and unpublished. As if user creation would commit the transaction. (Without creating a new user it works as expected.)

### To Reproduce

```
try
{
    var contentItem = await _contentManager.GetAsync("id", VersionOptions.DraftRequired);
    var user = _userService.CreateUserAsync(...);
    ...
    throw new Exception();

    await _contentManager.PublishAsync(contentItem);
}
catch
{
    await _session.CancelAsync();
    throw;
}
```

### Expected behavior
ContentItem will have the original version as latest and published.

I know reversing step 1 and 2 will solve the issue, but doing with CancelAsync() would be the best.

**Comment by jtkech** [comment]
You don't await `CreateUserAsync()`

**Comment by intellimedhu** [comment]
You're right, it's a misspell, sorry. However the problem still exists.

**Comment by jtkech** [comment]
Yes the user store call directly a session commit, as i remember it is related on how the related aspnetcore services work

In fact now it does a `_session.SaveChangesAsync()` that does a flush as i remember, but normally if you do a session cancel, the transaction should not be committed, at some point it was commited but it has been changed to keep the cancel state even after a flush, i will check it tomorrow

Which version are you using?

**Comment by intellimedhu** [comment]
Ok, thanks!

version: 1.0.0-rc2-16169

One more thing, probably related to this issue: I do the user creation first then updating the content item. When the user is created and an exception is thrown I try to delete the user in two ways:

1:
```
await _userManager.DeleteAsync(user); // UserManager<IUser>
await _session.CancelAsync();
```
The problem is the same: user deletion will commit the transaction, so CancelAsync makes no sense.

2.
```
await _session.CancelAsync();
await _userManager.DeleteAsync(user);
```
Content changes will be rolled back, but deleting the user fails.

**Comment by deanmarcussen** [comment]
> Yes the user store call directly a session commit, as i remember it is related on how the related aspnetcore services work

For infos @jtkech this is a behaviour we have talked about needing to change.

While EF/Identity would do this by default, EF/Identity, by default, difer in that they do not treat a the DbContext as a per request, i.e. cancellable, single transaction oer the whole request, by default.
It's something you can work into EF, but isn't done in the default patterns.

So to fit with the way we have chosen to do essentially a transaction per request, Users and OpenID are the odd ones out currently.

**Comment by jtkech** [comment]
@deanmarcussen 

Okay seems that we could change it

But still an issue that cancel doesn't prevent the transaction to be committed

We already fixed this use case with @sebastienros 

I'll try to take a look on it tomorrow

**Comment by jtkech** [comment]
@intellimedhu @deanmarcussen 

Yes i can repro, indeed `SaveChangesAsync()` commit the transaction, yes we already saw that the user store was commiting earlier but let it as is because normally when creating a user we don't save another entity.

Yes, i don't see any problem to commit the transaction at the end of the scope as done for other documents

So look like we should do a PR to remove these `SaveChangesAsync()` in the user store and other openId stores.

**Comment by intellimedhu** [comment]
Thanks for the solution and the merge.
When I implement `CreatingAsync` I don't have the content item and the other variables that are ready in the method above. I only have a user.
Please, show me a very basic example of how to solve my issue.

**Comment by jtkech** [comment]
@intellimedhu 

For some reasons we can't defer the session commit when creating an user. We introduced a new `CreatingAsync()` called before a user is created and let you the ability to cancel its creation, but it doesn't fix your specific use case.

So, you are creating a content item and a user in the same scope, would need more infos but based on your example why not just creating the user after the content item has been created and published successfully (and no exception).

    try
    {
        var contentItem = await _contentManager.GetAsync("id", VersionOptions.DraftRequired);
        ...
        throw new Exception();

        await _contentManager.PublishAsync(contentItem);
    }
    catch
    {
        await _session.CancelAsync();
        throw;
    }

    var user = await _userService.CreateUserAsync(...);

Note: There is a pending PR #9518 to cancel the session on exception, so you will not need to do it yourself.

**Comment by intellimedhu** [comment]
Based on our business needs we have a form that contains fields for a company and a legal representative (user data). Have to let the user sign in. Can't split the form. I'll wait for the mentioned issue, it probably will be a solution.

**Comment by intellimedhu** [comment]
@jtkech Please, help me how to register my custom exception handler. Thanks!

**Comment by jtkech** [comment]
@intellimedhu

Okay but as said, as soon as you have called `_userService.CreateUserAsync()` it is too late, the transaction is committed and any further session cancel will not prevent your content item to be persisted if you already "sesion saved" it.

So here it seems that you just need to call `_userService.CreateUserAsync()` after having tried to mutate and publish your content item. Otherwise, you can add an exception handler like this.

                    ShellScope.Current
                        .AddExceptionHandler((scope, e) =>
                        {
                            // Some stuff.
                        });

But if it is only to cancel the session, you don't need it as it is automatically done for you

                        .AddExceptionHandler((scope, e) =>
                        {
                            return scope.ServiceProvider
                                .GetRequiredService<IDocumentStore>()
                                .CancelAsync();
                        });

**Comment by intellimedhu** [comment]
I insist on a single transaction so:
1. move my content item creation context to a "store"
2. call `CreateUserAsync`
3. retrieve context from "store" in a custom UserEventHandler.CreatingAsync
4. create the content item and update user-related stuff
5. when an exception is thrown CreateUserContext.Cancel is set

What's your opinion?

**Comment by jtkech** [comment]
Looks good to me
