### ISSUE TITLE
Minor security issue: Internal File Path Disclosure

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#9379]
Hello,

A customer of ours has had a pen test undertaken of a system we have built for them, one of the issues that has been raised is the Media module can potentially expose internal file paths, letting a would be attacker find out what OS the server is using and gaining them knowledge about the file structure being used by the web application.

![image](https://user-images.githubusercontent.com/1166915/117460233-3498d400-af44-11eb-9ab2-36ded69751cd.png)

I've tracked it down to this catch statement:

https://github.com/OrchardCMS/OrchardCore/blob/9d4fb5372e6ac0deb9d749dc746a022c3dbe46a4/src/OrchardCore.Modules/OrchardCore.Media/Controllers/AdminController.cs#L184-L195

It's down as a low priority issue on the pen test but I thought I should log it here so it can be eventually resolved. Part of me is tempted to say have a blanket default error message and if someone is really interested they can check the server logs for the full details.

**Comment by hishamco** [comment]
The media path could be useful for server side logging but exposing such thing is a security bug

**Comment by deanmarcussen** [comment]
Yes, the media file stores are supposed to try catch all exceptions, and rethrow them as a `FileStoreException` to prevent this. so an operation isn't being try catched correctly, and needs to be updated
