### ISSUE TITLE
Admin dashboard: does not work on tenant?

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#9395]
### Describe the bug
I can create and unpublish dashboard widgets, but can not modify or delete. It has happened to me on 2 projects and only difference between others is that they run more tenants (with Tenants feature enabled). When there is only default tenant, everything is ok.

What happens is that if I click on Edit button: 
![image](https://user-images.githubusercontent.com/52829889/117619661-d5b7a280-b16f-11eb-9d66-22cc48dca783.png)
(leads here: /Admin/dashboard/manage?returnUrl=%2FAdmin%2Fdashboard%2Fmanage)
it only refreshes page AND also updates last changed date, but does not even open editor view. 

Delete does nothing at all, unpublish works. 

### Expected behavior

Edit should open edit view, delete should delete.

**Comment by jptissot** [comment]
My guess is that the `remove-for` does not work with tenants 
https://github.com/OrchardCMS/OrchardCore/blob/60520b5ced04c189823628dad3ed5f1e6fd8b8ca/src/OrchardCore.Modules/OrchardCore.AdminDashboard/Views/Dashboard.DeleteButton.cshtml#L2

**Comment by agriffard** [comment]
Everything works for me, tenant or not.

**Comment by MikeKry** [comment]
@agriffard 

I tried it on mutiple projects with rc2-16020 version of OC. 

Example can be seen also here:
http://try.orchardcore.fr/cb2h1vty/admin
admin / t_@$X53F

Where it runs on tenant if I am right and dashboard edit / delete does not work
