### ISSUE TITLE
Avoid compiling precompiled cshtml from nuget package

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#9428]
### Describe the bug
As Per https://github.com/OrchardCMS/OrchardCore/issues/6565#issuecomment-655208040

If module is referenced as nuget package e.g. `OrchardCore.Application.Cms.Targets` and if nuget package includes precompiled `Views.dll`, In development views are not served from Views.dll, instead it re-compiles all embedded  `cshtml` resulted in slow start in development.

**Comment by sebastienros** [comment]
Please send a PR if you know how to fix it. Kind of bad that it has to recompile all views.

**Comment by ns8482e** [comment]
Yes I have fix ready will create PR Soon

**Comment by jtkech** [comment]
In dev mode we can check the module assembly location, if not in the current execution directory it means it is loaded from the local package storage. I thought we were already using it, but maybe i only used it for module dynamic compilation.
