### ISSUE TITLE
Darkmode Admin Menu : submenu font color when item is active

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#9440]
![image](https://user-images.githubusercontent.com/3228637/118344945-4f98b480-b4ff-11eb-82e3-283e2714302f.png)

The font color should not be black.

**Comment by grimxreaper** [comment]
Hi, would this be fixed in your CSS file? If so, could I take a stab at this for my first contrib to this repo?

**Comment by hishamco** [comment]
@grimxreaper check the dark theme in the admin theme
