### ISSUE TITLE
Deleting a mediaField that is in a bag doesn't update the image preview

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#945]
Reminder for @sebastienros to fix this behavior, as he demoed it with the agency theme:
The deletion of a media is not hooked so the preview is not refreshed.

**Comment by sebastienros** [comment]
I think it's fixed

**Comment by agriffard** [comment]
No it has never been fixed.
Removing a Team member picture in the Agency homepage with Preview open doesn't update the picture.

**Comment by agriffard** [comment]
I tried to add a javascript to refresh the preview after a media is deleted but it didn't work.
$(document).trigger('contentpreview:render');

**Comment by sebastienros** [comment]
It actually works, in your example it's just that the media is mandatory and there is a validation error. We could show it in a non-blocking way, probably leveraging the same alert as https://github.com/OrchardCMS/OrchardCore/pull/918
