### ISSUE TITLE
String concatenation via + no longer works in Liquid 

### ISSUE THREAD

**Issue by Diman96** [OrchardCMS/OrchardCore#9473]
Priviosly I work with "+" when i need to concat string on Liquid page, when I updated packages, now it fails to parse this
    ` {% assign common_Info = "alias:common-info-" + Culture.Name %}`
and instead of this I must use
    `{% assign common_Info = "alias:common-info-" | append: Culture.Name %}`
Is it intended behavior and must I rewrite all my code?

Version 1.0.0-rc2-16209

**Comment by Diman96** [comment]
looks like no one operator works even substraction a number doesn't work  
`{{ forloop.index - 1 }}`

**Comment by jtkech** [comment]
> Is it intended behavior and must I rewrite all my code?

Yes ;)

Try the filter `| minus: 1`

**Comment by Diman96** [comment]
okey, @jtkech  how to rewrite `{% if forloop.index%2 != 0 %}  order-md-2 {% endif %}`? 
when i use  `{% if forloop.index | modulo: 2 != 0 %}  order-md-2 {% endif %}` this does not work

**Comment by jtkech** [comment]
Hmm, would need to try it

Try to assign a var before `{%assign test = forloop.index | modulo: 2 }` and then `{% test  != 0 %}`

**Comment by Diman96** [comment]
@jtkech Why was it changed to this approach? What are the advantages of Liquid over Razor in order to use such "simple" shortcuts? Because I think more about rewriting everything on Razor, I'm afraid in a year I will wake up and see that if-else constructions have become illegal on Liquid.

**Comment by jtkech** [comment]
About not using `+` it is to be more strict with regard to fluid specifications

About the filter in the If statement not sure, maybe an issue

**Comment by jptissot** [comment]
@Diman96 I think Fluid 2.0 was refactored to be inline with the liquid spec. The liquid spec does not allow using filters in if statements.

**Comment by jtkech** [comment]
@jptissot Thanks, was not sure about the filter ;)

**Comment by Diman96** [comment]
Thanks, I'll keep that in mind.

**Comment by xperiandri** [comment]
> About not using + it is to be more strict with regard to liquid syntax specifications
> Try to assign a var before {%assign test = forloop.index | modulo: 2 } and then {% test != 0 %}

@sebastienros that all looks quite strange... In terms of usability

**Comment by sebastienros** [comment]
@xperiandri 🤷‍♂️
Please file an issue here: https://github.com/Shopify/liquid

The idea is that if we don't standardize on the language, then we can't point to common documentation and samples, or be able to use different implementations. For instance when users try to switch from an engine to Fluid.

**Comment by xperiandri** [comment]
Reasonable, thanks
