### ISSUE TITLE
Recipe text is saved on the Database with � [Encoding]

### ISSUE THREAD

**Issue by XpandIT-RFID** [OrchardCMS/OrchardCore#9474]
### To Reproduce
When I add a field of text that has for exemple a "ç or á" it will not do the encoding correctly and will save in the database with �.
This is a big problem for example in Portugal. 
I also tried to use ` [js: html('string with ç or á')]` and still it didn't work.

Recipe.json:
![image](https://user-images.githubusercontent.com/83280308/118669312-92070d80-b7ed-11eb-8b7b-1c3b068c7838.png)

Json in Default_Document table:
![image](https://user-images.githubusercontent.com/83280308/118669833-fc1fb280-b7ed-11eb-8295-cef2f436b11c.png)

I am new to OrchardCore and I can't find any solution for this.

**Comment by MRSheikh** [comment]
add `;CharSet=utf8;` in to end of your ConnectionString. I think this resolves your issue.

**Comment by pchoisnard** [comment]
You can use javascript encoded like  é -> \u00e9

**Comment by XpandIT-RFID** [comment]
> ;CharSet=utf8;

Seems to only work with MySql, I am using Sql Server

**Comment by XpandIT-RFID** [comment]
> You can use javascript encoded like é -> \u00e9

I will have to do this for a lot of pages :/ it will be a pain to change all words to javascript encoded, Portuguese uses a lot of accentuation an such

**Comment by deanmarcussen** [comment]
Is this solely related with content created via recipes?

Was the content exported from a deployment step (import/export)?

i.e. does a deployment step correctly encode content?

**Comment by XpandIT-RFID** [comment]
Yeah only happens when I deploy via recipe, I can then go to the content type and change the text.

**Comment by XpandIT-RFID** [comment]
It may be because of the Collation of the SQL Database, I am trying to change it from AS to IS, I don't know if that will solve it though.

**Comment by XpandIT-RFID** [comment]
@deanmarcussen doesn't seem to be the Collation.
I used this collation on the db 
![image](https://user-images.githubusercontent.com/83280308/120215322-7e1bcc80-c22d-11eb-89b1-00346ab43020.png)

Also verified that the tables were created with the same Collation.
When the Content Step creates the content items in the "Document" table of the database it seems to use the � when it detects text with special characters like ç, ´, `, etc... 

Is this a known bug? I am in the RC2-16166 version.

**Comment by Skrypt** [comment]
What does the text looks like in your main database? If chars are stored as � then the issue is when you are deploying the recipe.
Then next question is, are you deploying directly from Orchard to a remote client?
If yes, then the issue might be in OC.
If no, then you are saving these recipe locally on your PC before deploying them. Normally these recipes are downloaded as a .zip file which contains the recipe.json file, which means when we save the file it should be saved as a unicode file. Never had issue with this before.

The other issue could be that the target database has a different collation than the main one.

**Comment by XpandIT-RFID** [comment]
The char is saved as � in the database.
![image](https://user-images.githubusercontent.com/83280308/120222982-c1c80380-c238-11eb-89a3-b01b5817b9d5.png)
This is in localhost. Currently using my SQLExpress Database. But happened as well when I deployed to the Database in Azure.
Where can I see this .zip file that is downloaded?  @Skrypt

**Comment by Skrypt** [comment]
If the data is saved with this char that means that it's been saved that way in your database. You need to convert this data using the proper encoding. Your deployments are only using the data that is saved in your database in the end. So, the issue seems to start there. You're deploying data that is not encoded properly. Probably what happened is that your database was using a collation that doesn't support these chars in the beginning. Now, the only thing you can do is find a way to convert these string with the proper encoding.

**Comment by XpandIT-RFID** [comment]
I just made another database with Latin1_General_CI_AS Collation and still got the same result.
![image](https://user-images.githubusercontent.com/83280308/120231372-2d19d180-c249-11eb-8ee1-7a7668ef3c7c.png)
SQL_Latin1_General_CP1_CI_AS == Latin1_General_CI_AS.

This is a problem that occurs when the recipe applies the steps in the database and that I know for sure. Since I can go and edit the data by hand via Orchard and it gets corrected.

After recipe steps are applied: 
![image](https://user-images.githubusercontent.com/83280308/120231535-83871000-c249-11eb-852e-9c4e43c17737.png)
I change and publish: 
![image](https://user-images.githubusercontent.com/83280308/120231560-90a3ff00-c249-11eb-99ac-3a23e9a13244.png)
And it gets corrected in the database, of course.

**Comment by Skrypt** [comment]
Ok, and what about the recipe.json that you are importing. From where are you importing it? And are you using a recipe.json that stands on your filesystem? Because, here the issue could be that this recipe.json file has your system encoding instead of unicode encoding.

**Comment by deanmarcussen** [comment]
I think the issue is likely the recipe.

I suggest using the import / export feature to create a deployment plan with your content items in it. 

I would hope the recipe output is then correctly encoded

**Comment by Skrypt** [comment]
At least if the issue is about the encoding of the recipe.json file we could assert that the file has the right encoding before importing it. Need to see if we could change the encoding of the file in the temp upload folder before parsing it. Waiting on confirmation on this.

**Comment by Skrypt** [comment]
Solution that seems that would fix this issue would be to save the recipe.json file with UTF-8 encoding. But that's the default in Windows for me. I will test it to see which encoding type could cause this issue. ANSI would surely do.

**Comment by Skrypt** [comment]
@XpandIT-RFID The way to export content to a file is to create a "Deployment plan" with the import/export feature of Orchard Core.

**Comment by XpandIT-RFID** [comment]
> Solution that seems that would fix this issue would be to save the recipe.json file with UTF-8 encoding. But that's the default in Windows for me. I will test it to see which encoding type could cause this issue. ANSI would surely do.

Oh this was the problem 🤦 the recipe.json was saved as ANSI for some weird reason... Thanks for the help and sorry for the waste of time, at least if someone ever gets the same problem they can find it on the issues tab 👍 

Closing the issue.
