### ISSUE TITLE
Jint does not seem to handle Json.NET linq objects as one would expect. Affecting the workflow scripting activity.

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#9491]
### Describe the bug

The Orchard docs state both `queryStringAsJson` and `requestFormAsJson` should return the respective item as a JSON object. Looking at the code, each return a `JObject` type in the `GlobalMethod` delegate. However Jint does not appear to be correctly translating this object into a javasrcript object that can be worked with inside the scripting engine. 

I attempted to inspect what the object was by logging the stringified version, aka

```
var form = requestFormAsJson();
log("Debug", JSON.stringify(form));
```
Which resulted in this output:
```
{}
```

I then tried this:
```
var form = requestFormAsJson();
var formLength = Object.keys(form).length;
log("Debug", "Form Length: " + formLength);
```
Which resulted in this output:
```
Form Length: 0
```

I am using Orchard RC2, so I'm not sure if this is resolved by a newer beta release of Jint...

Originally I found this by adding my own custom global method which also returned a `JToken` object, and I found it was not being handled correctly. For the time being i'm getting around it by retrieving the stringified version then doing a `JSON.parse()` call inside the engine, and this has worked as intended.

**Comment by sfmskywalker** [comment]
Yeah makes sense. Or perhaps even simpler (for the user) is to just register a function called e.g. `queryString(name: string): string | string[]`  that returns the query string value by name. If there are multiple values, perhaps return them as an array of strings.

In Elsa I do something similar:

```csharp
engine.SetValue(
   "queryString",
   (Func<string, string>)(key => _httpContextAccessor.HttpContext!.Request.Query[key].ToString())
);
```

**Comment by Skrypt** [comment]
@sfmskywalker Have you thought about when a form is sent with a Content-Type header like "application/x-www-form-urlencoded" ?

**Comment by marlon-tucker** [comment]
Personally I believe Jint needs some ability to have custom type formatting which can translate objects to the "native" types that the Jint engine understands.

Json.Net is a extremely widespread library, and the above mistake in code is going to be a common occurrence. 

I understand under the hood Jint relies on reflection, which covers most Clr instances reasonably well. However when that Clr instance is meant to represent an underlying JSON structure, it falls down a bit. 

So having the ability to add custom formatters which know how to translate specific instances "correctly" would be a huge benefit. 

Maybe a project called `Jint.Formatters.Newtonsoft.Json` or `Jint.Interops.Newtonsoft.Json` etc...

**Comment by sebastienros** [comment]
@marlon-tucker pretty sure it does already.

**Comment by jptissot** [comment]
Maybe we should add this method in the OC codebase: 
https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.Scripting/FormsGlobalMethodsProvider.cs#L44

**Comment by Skrypt** [comment]
Here is the issue I get when using application/json with the reCaptcha : 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3228637/119055846-b4d52580-b997-11eb-9843-797c418c42a3.png)

**Comment by Skrypt** [comment]
@marlon-tucker how do you post your form? Is it an Angular application or a standard form post from HTML?

I couldn't find how to bind the form data from the FORM POST in Angular because I basically was not settings the form post HttpParams in Angular.

Content-Type = application/x-www-form-urlencoded
Set property task = requestFormAsJson()

```Typescript
  postContactData(formData: any, gtoken: string): void {
    this.loading = true;
    this.updateLoaderVal(this.loading)
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'  // Notice I'm forcing it to use typical content type here
      }),
      params: new HttpParams({
          fromObject: {"token": env.ocContactWorkflowKey}
      })
    };

    const body = new HttpParams() // This is really important to post HttpParams and not a JSON object since our Content-Type is set to x-www.form-urlencoded.
    .set('firstName', formData.firstName)
    .set('lastName', formData.lastName)
    .set('email', formData.email)
    .set('phoneNumber', formData.phoneNumber)
    .set('message', formData.message)
    .set('g-recaptcha-response', gtoken);

    this.http.post(env.ocBaseWorkflowUrl, body, httpOptions)
    .pipe(
      catchError((err) => {
        console.log(err);
        this.didSucceed = 0;
        this.updateSucceedVal(this.didSucceed);
        throw err;
      })
    )
    .subscribe(
        data => {
        console.log(data)
        this.loading = false;
        this.updateLoaderVal(this.loading);
        this.didSucceed = 1;
        this.updateSucceedVal(this.didSucceed);
      });
  }
```

Content-Type = application/json 
Set property task = JSON.parse(readBody())

```Typescript
  postContactData(formData: any, gtoken: string): void {
    this.loading = true;
    this.updateLoaderVal(this.loading)
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/json'  // Notice that we could comment these lines as it is the default Content-Type used in Angular.
      }),
      params: new HttpParams({
          fromObject: {"token": env.ocContactWorkflowKey}
      })
    };

    const body = {  // We prepare our form data as json since we set the Content-Type to application/json
      firstName: formData.firstname,
      lastName: formData.lastName,
      email: formData.email,
      phoneNumber: formData.phoneNumber,
      message: formData.message,
      "g-recaptcha-response": gtoken  // Notice here that you won't be able to use reCaptcha as it fails when form is posted as application/json
    }

    this.http.post(env.ocBaseWorkflowUrl, body, httpOptions)
    .pipe(
      catchError((err) => {
        console.log(err);
        this.didSucceed = 0;
        this.updateSucceedVal(this.didSucceed);
        throw err;
      })
    )
    .subscribe(
        data => {
        console.log(data)
        this.loading = false;
        this.updateLoaderVal(this.loading);
        this.didSucceed = 1;
        this.updateSucceedVal(this.didSucceed);
      });
  }
```

**Comment by marlon-tucker** [comment]
@Skrypt We're just using a normal html form. We have been able to retrieve single form values by using the `requestForm('fieldName')` function in the workflow but the `requestFormAsJson()` method does not work at the moment. 

However, I think the name of that method is misleading you slightly. It does not mean it will try to parse the form from an `application/json` content type. It just means it is attempting to pass the form into the scripting engine as a JSON structure, nothing to do with the request's content type.

**Comment by sfmskywalker** [comment]
> @sfmskywalker Have you thought about when a form is sent with a Content-Type header like "application/x-www-form-urlencoded" ?
> 
> When I'm using a common HTML form ; the header Content-Type = "application/x-www-form-urlencoded".
> When I'm using Angular 8, we are using a header Content-Type = "application/json" just like in your examples.
> 
> What I do is I use a "Set Property task" to retrieve these forms values.
> Though when we use "application/json" we need to parse the form with JSON.parse(readBody()).
> But when we use "application/x-www-form-urlencoded" we need to use requestFormAsJson().
> 
> Should it not know already the type of the form by looking at the header Content-Type and bind it to the Workflow Input in case that we do form POST from different forms to the same Workflow?
> 
> Or am I lost here? 😄
> 
> The thing is that I was thinking is that it could read the Content-Type to know how to parse the data that is sent. And then automatically bind it as a JSON Object to the Workflow. Was it intentional to not bind the form data posted to the Workflow in all cases?

I agree- ideally, the activity looks at the content type header and constructs an appropriate Content model.
In fact, that's what I do here:  https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs#L76

Notice that `contentParser` that was select here: https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs#L63

It selects the right content parser based on the content type.
Although in my example I'm doing it from the middleware for reasons, but we might do something similar for the HTTP activity.

**Comment by hyzx86** [comment]
> I think these two methods are not useful in JavaScript (`queryStringAsJson`, and `requestFormAsJson`) since they return `JObject` instances which are not very useful in JS.
> 
> I would instead return a `Dictionary<string, object[]>` that can be indexed in JavaScript, or serialized back to JSON and call them `deserializeQueryString` or `queryStringAsObject`.
> 
> Also the `AsJson` suffix doesn't make much sense since in JavaScript, it's easier an object or a JSON "string". So `AsJson` would imply it's a json formatted string.
> 
> /cc @sfmskywalker

But  how can I send a `Dictionary<string, object[]>` via  `Http Request  Task` ？

https://github.com/OrchardCMS/OrchardCore/discussions/10628
