### ISSUE TITLE
Placement is inconsistent between fields directly on a content type vs. fields on another content part

### ISSUE THREAD

**Issue by mroskamp** [OrchardCMS/OrchardCore#9493]
### Describe the bug
Using placement to place fields is inconsistent depending on whether the field is on the default part for the content item, or on another part attached to the content type. I would expect the fields to all be placed consistently, regardless of whether they're on the default part or another part. Instead, the placement is either ignoring or hiding fields that are defined on a separate content part. Fields that are on the default part for the content item do properly respect the placement.

### To Reproduce
1. Go to the admin panel
2. Enable the "TheTheme" theme
3. Add a new content **part** named "FooPart" with two text fields named "Alpha" and "Beta"
4. Add a new content **part** named "BarPart" with two text fields named "Gamma" and "Delta"
5. Add a new content **type** named "Test" which includes both FooPart and BarPart plus a text field named "Epsilon"
6. Create a new "Test" content **item**. Populate each field (for simplicity, I set each field to its corresponding field name)
7. Publish and view the "Test" content item. Notice that all 6 fields are correctly rendered in the main content zone.
8. Go to Configuration -> Features
9. Enable the "Placements" feature
10. Go to Design -> Placements
11. Add a new placement for the "TextField" shape
12. Filter by `"displayType": "Detail"` and then place the shape in the Header content zone (`"place": "Header"`) and save
13. View your "Test" content item again. Notice that the "Epsilon" field correctly appears in the Header zone, but all of the other fields (those on the Foo and Bar parts) disappear
14. Edit your "TextField" placement
15. Replace `"place": "Header"` with `"place": "Content%Info"` and save
16. View your "Test" content item again. Notice that the "Epsilon" field correctly appears in the "Info" card in the Content content zone, but all of the other fields (those on the Foo and Bar parts) appear in the fallback "Content" card.

Note that I've reproduced this same behavior using the Placement admin UI, a configured placement.json file, and with a ShapeAlterationBuilder.Placement handler via a ShapeTableProvider.

### Expected behavior
At step 13, I would expect that all 5 fields would appear in the Header content zone
At step 16, I would expect that all 5 fields would appear in the "Info" card within the Content content zone.

### Screenshots
Step 7:
![image](https://user-images.githubusercontent.com/4029047/118881744-66edee00-b8c1-11eb-8964-d4bb167c9d97.png)

Step 12:
![image](https://user-images.githubusercontent.com/4029047/118881970-a4eb1200-b8c1-11eb-9253-f111d532fd54.png)

Step 13:
![image](https://user-images.githubusercontent.com/4029047/118882028-b46a5b00-b8c1-11eb-99c2-3cbc2f4efdde.png)

Step 15:
![image](https://user-images.githubusercontent.com/4029047/118881886-8f75e800-b8c1-11eb-817c-34bf953bced7.png)

Step 16:
![image](https://user-images.githubusercontent.com/4029047/118881802-7a00be00-b8c1-11eb-8189-fb52151007c3.png)

**Comment by ns8482e** [comment]
Fields of Part are rendered on `ContentPart` shape whereas fileds of  Type are rendered on  `Content` shape.  These shapes can have it's own local Zone. 

Here `Content.cshtml` has defined local zones for `Header`, `Footer` and `Meta` but `ContentPart.cshmtl` has only local Content zone defined, hence setting local placement at line # 12 only displays Epsilon and hides fields of `FooPart` and `BarPart`

To target the zones defined in `Layout` shape  use `/Header`

**Comment by mroskamp** [comment]
Thanks for the detailed explanation, @ns8482e!
