### ISSUE TITLE
Workflow : Recaptcha with application/json header Content-Type fails.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#9508]
Here is the issue I get when using application/json with the reCaptcha : 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3228637/119055846-b4d52580-b997-11eb-9843-797c418c42a3.png)

So basically I'm trying to validate the recaptcha with it's data-callback method to get it's validation token. Send it to the Workflow as g-recaptcha-response form value so that it passes. As soon as I add the reCaptcha task to the Workflow it faults with an error message saying : "Incorrect Content Type : application/json"

**Comment by Skrypt** [comment]
Ok found the issue by myself. When using reCaptcha the form POST must have a header Content-Type set to "application/x-www-form-urlencoded". Then my issue was about how I was building my form in Angular.

**Comment by jptissot** [comment]
@Skrypt there are valid use cases for sending json (I think). Maybe the recaptcha could be sent in a header like we can do for the requestVerificationToken ?

**Comment by jptissot** [comment]
For reference: https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.VueForms/Assets/vue-forms.js#L84

**Comment by Skrypt** [comment]
The AntiforgeryToken is passed as a form input then. Not the request header.
