### ISSUE TITLE
The condition in the if statement is opposite

### ISSUE THREAD

**Issue by caoxk** [OrchardCMS/OrchardCore#951]
https://github.com/OrchardCMS/Orchard2/blob/018405e8dd67c0dc7b0b000dbe2e2b997390f493/src/OrchardCore/Orchard.Environment.Navigation/NavigationManager.cs#L156

**Comment by sebastienros** [comment]
Would love to see what you are building. In the meantime feel free to create a PR or let us know if you can't.
