### ISSUE TITLE
admin menu on local intranet wait for fonts.googleapis.com ...

### ISSUE THREAD

**Issue by MRSheikh** [OrchardCMS/OrchardCore#9520]
I run Orchardcore on my local intranet and when I change some setting in the admin menu, it's waiting for `looking up for fonts.googleapis.com`
I disabled UseCDN :
` public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms().AddMvc().ConfigureServices(tenantServices => {
                tenantServices.PostConfigure<ResourceManagementOptions>(o => o.UseCdn = false);
            });
        }`
but nothing happened.

**Comment by Skrypt** [comment]
This would require that we download all the fonts and serve them from the themes themselves instead of using the Google font API url.

**Comment by sebastienros** [comment]
`UseCdn` has been the default for a while. Are you using the latest version? Unless you set up the site before this change.

**Comment by Skrypt** [comment]
@sebastienros I don't think we bundle these fonts at all in our themes.

**Comment by sebastienros** [comment]
I think we should, like any other asset we require for the admin. And use the CDN ones only if the settings is set.

**Comment by sebastienros** [comment]
How big are these?

**Comment by deanmarcussen** [comment]
They are not big, it shouldn't be an issue to pull them in.

The font source is here https://github.com/google/material-design-icons/tree/master/font

but the css (also small) only seems to be direct from https://fonts.googleapis.com/css2?family=Material+Icons

so if we bring them in (should be simple) just a matter of keeping both style sheet and font in sync

**Comment by dafergu2** [comment]
I'll see if I can tackle this on the weekend.

**Comment by Skrypt** [comment]
Using the CSS will make use of the CDN too. So, it needs some thinking.

**Comment by Skrypt** [comment]
See this post : https://stackoverflow.com/questions/37270835/how-to-host-material-icons-offline
