### ISSUE TITLE
User.Identity.Name is null despite using valid OpenId bearer token with claim for name

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#9533]
### Describe the bug
Using a bearer token provided by openid module which contains a claim with the user name, when User.Identity.Name is accessed its value is null despite a claim for name is present at User.Claims.
It seems that current configuration Is not mapping properly claims to User.Identity model.

### To Reproduce
1. Check out last bits o Orchard dev branch
2. Setup an Orchard site
3. Enable modules: OpenID Core Components, OpenID Authorization Server, OpenID Management Interface, OpenID Token Validation, and  Contents Module
4. Configure  OpenID settings from dashboard to allow all endpoints,, password flow and refresh flow. Disable Rolling TRefresh Tokens, Chose JSON Web Token (JWT) as token format and Disable Access Token Encryption.
5. Create an openid confidential client app  that allows password and refresh flows
6. Request an access token with postman for admin user, see screenshot section for used data
7. Add a break point at content module controller for route /api/content/ to check value for User.Identity.Name when an action is performed
7. Request with postma a resource to contents api from module controller using the bearer token as is done in the screenshot.
8. You can check that User.Identity.Name has a null value however as you can see at the screenshot the claim for with the name exists

### Expected behavior
I would expect the name "admin" would be at User.Identity.Name

### Screenshots
![image](https://user-images.githubusercontent.com/4950766/119350659-e43da800-bc9f-11eb-952d-723642e0a889.png)
![image](https://user-images.githubusercontent.com/4950766/119350740-f91a3b80-bc9f-11eb-904a-4868385ba037.png)
![image](https://user-images.githubusercontent.com/4950766/119352000-6da1aa00-bca1-11eb-83b0-9df9774e6977.png)

**Comment by jersiovic** [comment]
@kevinchalet may be the answer you gave here is related with this problem https://github.com/openiddict/openiddict-core/issues/1227 However I've not been able to do sth with that answer at Orchard source

**Comment by kevinchalet** [comment]
The OpenID module would have to map the WS-Fed `ClaimTypes.Name` to `name` for that to work (the OpenIddict validation handler uses `name` for the name claim).

**Comment by jersiovic** [comment]
Cool, it works, I'm going to submit a PR asap
thank you

**Comment by kevinchalet** [comment]
I'm pretty sure there are a few tickets about making this part configurable. We should maybe make the mapping configurable using some sort of script?

**Comment by agriffard** [comment]
Fixed by #9555
