### ISSUE TITLE
One item from Add Widget dropdown is hidden behind navbar

### ISSUE THREAD

**Issue by citrusmarlin** [OrchardCMS/OrchardCore#9534]
### Describe the bug
This bug happens on the Design > Widgets page. When I click Add Widget, it ordinarily tries to list all the menu items (namely, widgets) either above or below the relevant Add Widget button (see the "Correct" screenshots below). However, if there isn't enough vertical space on the page for either of these display options, it lists all the widgets starting at the top of the webpage ("Problem" screenshot 1). The issue is that the first widget (Container) is displaying behind the navbar, and scrolling up does not reveal it. While this first item _can_ be selected by tabbing, it's not visible and it can't be selected with the mouse. However, when the navbar is removed using the browser's dev tools, the first item becomes visible ("Problem" screenshot 2).

Potential related bug: #8443

### To Reproduce
1. Go to Design > Widgets.
2. Make the browser window's vertical dimension pretty small ("Replication" screenshot).
3. Click Add Widget, preferably the first Add Widget button on the page, for the maximum change of replicating the bug.
4. Look at the first visible menu item, and see whether it is the same item as when all the menu items appear below the Add Widget button (to do this, try maximizing the browser window and again clicking Add Widget).

**Note:** This bug may not happen if the Widgets page is long (e.g., there are a lot of zones or a lot of widgets in the zones). The longer the Widgets page, the better are the chances that there will be enough space on the page to display all the items either above or below the Add Widget button. For a better change of seeing this bug, try it on a Widgets page that doesn't have much content, or when there are a lot of widgets that would appear in the dropdown.

### Expected behavior
In the problem scenario above, the first menu item should either appear below or behind the navbar.

### Screenshots
Correct screenshot 1: All menu items appear above the button.
![image](https://user-images.githubusercontent.com/84602531/119354579-3e277900-bc72-11eb-8874-ae1deb03b908.png)

Correct screenshot 2: All menu items appear below the button.
![image](https://user-images.githubusercontent.com/84602531/119358426-99f40100-bc76-11eb-9db6-0ea8e29ec8a5.png)

Replication screenshot: If a large/maximized browser window is so tall that there's whitespace at the end of the page, you can make the window's vertical dimension smaller to remove (most of) this whitespace.
![image](https://user-images.githubusercontent.com/84602531/119363625-032a4300-bc7c-11eb-9d2a-4b7d915eb998.png)

Problem screenshot 1: First menu item (Container) appears behind the navbar.
![image](https://user-images.githubusercontent.com/84602531/119358191-65804500-bc76-11eb-86f3-6f7968860cf1.png)

Problem screenshot 2: Previously invisible menu item can be seen, once the navbar is removed using the dev tools (inspector).
![image](https://user-images.githubusercontent.com/84602531/119360260-6d40e900-bc78-11eb-9906-df06e66d855b.png)

Thanks so much and God bless!

**Comment by Skrypt** [comment]
We just need to use a scrollbar and a max-height on those pop-up menus like we did in the FlowPart.
