### ISSUE TITLE
Get the last version of the translation files

### ISSUE THREAD

**Issue by pchoisnard** [OrchardCMS/OrchardCore#9541]
I make a simple project blog with template, and in the folder translation/fr I have only files of 2020.
I crowdin we have file for may 2021.
I have miss something to get the last version ?

My orchard version : 1.0.0-rc2-16238
I clean the loalization folder with the last version found in crowdin
Regenerate the project
The files of 2020 come back.
![may](https://user-images.githubusercontent.com/49313832/119503266-1536df00-bd6b-11eb-96c7-e6302480f7b5.PNG)
![june2020](https://user-images.githubusercontent.com/49313832/119503301-1f58dd80-bd6b-11eb-8cab-7f8a2046dff2.PNG)

**Comment by Skrypt** [comment]
These files are automatically downloaded from Crowdin every time you build the project. No need to update them manually.

**Comment by pchoisnard** [comment]
Yes These files are automatically downloaded from Crowdin but not in the good version.
For example create a site with dotnet new occms -n MySite
Generate the web project and in the Localization\fr all the files are dated 2020-06-11.
The content is not good.

We have for example in orchardcore.contents.po
`#. <select asp-for="Options.ContentsStatus" asp-items="@Model.Options.ContentStatuses" class="selectpicker show-tick mr-2" data-header="@T["Filter by status"]" data-selected-text-format="static" data-width="fit" data-dropdown-align-right="true" title="@T["Show"]" data-style="btn-sm"></select>
#: OrchardCore.Contents\Views\Admin\List.cshtml:96
msgctxt "OrchardCore.Contents.Views.Admin.List"
msgid "Filter by status"
msgstr "Filtrer par statut"`

instead of 

`#. <select asp-for="ContentsStatus" asp-items="@Model.ContentStatuses" class="selectpicker contentstatuses-selectpicker show-tick mr-2" data-header="@T["Filter by status"]" data-selected-text-format="static" data-width="fit" data-dropdown-align-right="auto" title="@T["Show"]" data-style="btn-sm"></select>
#: OrchardCore.Contents\Views\ContentsAdminListFilters.cshtml:12
msgctxt "OrchardCore.Contents.Views.ContentsAdminListFilters"
msgid "Filter by status"
msgstr "Filtrer par statut"`

**Comment by pchoisnard** [comment]
I get the last version 1.0.0-rc2-16269 and I still have the problem. 
Should I do something ?
