### ISSUE TITLE
Modify PortableObjectStringLocalizer to enable correct inheritance

### ISSUE THREAD

**Issue by amolodenov** [OrchardCMS/OrchardCore#9542]
PortableObjectStringLocalizer has non-virtual methods this[string] for getting resources. If you inherit from PortableObjectStringLocalizer, you cannot call the required method using the IStringLocalizer interface.

Need to add a modifier virtual for methods this[string] in PortableObjectStringLocalizer class. Аlso need to change the modifier of GetTranslation methods from private to protected.

Now we have to cast IStringLocalizer to the appropriate type to call the correct method.

**Comment by hishamco** [comment]
I agree there should be a `virtual` methods but not for everything, please let me know what can kind of changes that let you subclass the `PortableObjectStringLocalizer`?

**Comment by amolodenov** [comment]
Thanks for the quick response.

In subclass, I override methods
```
this[string]
this[string, params object[]]
GetTranslation(string, params object[])
```
to get an analog of ResourceManagerWithCultureStringLocalizer сlass.

Need "virtual" for:
```
this[string]
this[string, params object[]]
```

Need "protected" for:
```
GetTranslation(string[], CultureInfo, int?)
GetTranslation(string, string, CultureInfo, int?)
```

I have seen the changes https://github.com/OrchardCMS/OrchardCore/pull/9569/files . There is not enough "protected" for "GetTranslation(string[], CultureInfo, int?)".

**Comment by hishamco** [comment]
> There is not enough "protected" for "GetTranslation(string[], CultureInfo, int?)

I will check this one, other than that everything as expected
