### ISSUE TITLE
IContentPartHandler.ValidatingAsync not called when creating a new content item through the admin

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#9563]
### Describe the bug
I created a new content item for a content type that contains the `AutoroutePart`. When I publish the content item I expect `AutoroutePartHandler.ValidatingAsync` to be called, but it is not.

I used a fresh install of 1.0.0-rc2-16248 and the Blog theme.

### To Reproduce

1. Prepare to launch a fresh install of OC.
2. Set a breakpoint in `AutoroutePartHandler.ValidatingAsync`
3. Launch the site, go through the setup, select the Blog theme.
4. Notice that `AutoroutePartHandler.ValidatingAsync` is correctly called while importing content through the recipe.
5. Once the site is finished with the setup, go to the admin. Create a new Page.
6. Give the page a title and publish it.
7. `AutoroutePartHandler.ValidatingAsync` is not called, but I believe that it should be.

### Expected behavior
`AutoroutePartHandler.ValidatingAsync` should be called when publishing a content item through the admin UI.

**Comment by jtkech** [comment]
Through the admin this is the related handler / driver using mvc binding that does the job without using this `ValidateAsync()`, this in the other cases that it is used, when there is no mvc binding, e.g. while importing, creating through the rest API, through a workflow activity ...

**Comment by rjpowers10** [comment]
In my case I don't have a driver for my content part. It's just displaying some plain old content fields, but I do want to add some complex validation logic for one of the fields. Where does that logic belong?

**Comment by jtkech** [comment]
> My ContentPart is being saved correctly but I'm trying to add in some complex validation logic

Is your part created through the admin UI, or by code? If by code the more natural way is to use a driver on your part with an UpdateAsync()

**Comment by rjpowers10** [comment]
@jtkech I'm creating it through the admin UI.

**Comment by jtkech** [comment]
Okay, so maybe a global content handler so that you can check your added part / fields, if the fields are added directly under the type, there is a special content part to hold them and whose name is the content type.
