### ISSUE TITLE
OC2003 - <Package> is an unmanaged PackageReference

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#9564]
We're receiving an OC2003 compilation warning after adding ApplicationInsights reference to a project and I'm wondering if it's something we need to worry about or if it can be safely ignored.

**Comment by Skrypt** [comment]
If you are using source code your dependencies needs to be added to the Dependencies.props file.
The package reference should not have a Version="x.x.x".
