### ISSUE TITLE
Edit User Custom Settings via code ouside of the Editor

### ISSUE THREAD

**Issue by XpandIT-RFID** [OrchardCMS/OrchardCore#9577]
Hello, I am currently trying to edit the custom user settings of a user in a controller. 

I have tried to follow what is done in the CustomUserSettingsDisplayDriver but it doesn't seem to work
![image](https://user-images.githubusercontent.com/83280308/120025627-e332b080-bfe8-11eb-9e00-dd90f123d70c.png)

Can someone help me?

**Comment by jptissot** [comment]
Have a look at the scripting method we wrote a while back. https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.Scripting/UserGlobalMethodsProvider.cs#L55

**Comment by XpandIT-RFID** [comment]
> Have a look at the scripting method we wrote a while back. https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.Scripting/UserGlobalMethodsProvider.cs#L55

Nice! now I understand better how it works :) 
Closing the issue
