### ISSUE TITLE
Widget template still is run even the Zone is not shown in Layout.

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#9584]
### Describe the bug
I got some widget templates that contain 
```
<script at='Foot'>...</script>
```
and this widget is added to Zone, let me name it Zone A. When I change the website to use another Layout that hasn't the Zone A. The templates still is run and because the 'script' tag is at='Foot'. So the scripts is rendered to website as well.
### To Reproduce
1. Create template for any widget
2. Add some js script with at='Foot' the template
3. Add the widget to a Zone
4. Use a Layout that hasn't the Zone
5. The script will be rendered to website

### Expected behavior
Just like the html content of the template, the scripts in widget template should not be rendered to webiste when there is no Zone for the widget.

**Comment by jptissot** [comment]
The current behavior makes sense to me, what use case are you trying to solve with this?

**Comment by HengzheLi** [comment]
I made some animation effect in my widget using js code. And the code is only affect on specified html tag with predefine id or className. So when there is no those prefefine tags, my js code will throw exception.
Well, I know I should do checking in my js code to prevent the exception throwing. But I was expected all assets in a widget only will be rendered as soon as the Zone where the widget belong to is rendered.

And for now, the html code is not rendered, and the script with which at='Foot' is rendered.

**Comment by Skrypt** [comment]
We would need to verify if a zone is rendered in a template or not which is kind of bad to do. What I suggest is that you add a url rule that prevents this widget to get rendered in any pages. If you need it to be displayed in specific pages then this rule will naturally prevent this widget from displaying.

**Comment by HengzheLi** [comment]
> We would need to verify if a zone is rendered in a template or not which is kind of bad to do. What I suggest is that you add a url rule that prevents this widget to get rendered in any pages. If you need it to be displayed in specific pages then this rule will naturally prevent this widget from displaying.

OK. This solves my problem. I will close this issue if there is no plan to change the widget behavior
