### ISSUE TITLE
Content item editing page reloads when images are uploaded via popup image picker which causes loosing all the changes

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#9585]
### Describe the bug
All the page changes are lost when an image is uploaded via image picker because the content item editing page reloads.
It is extremely annoying behavior!

### To Reproduce
1. Make some changes to a content item
2. Open image picker
3. Upload image
4. Page will reload

### Expected behavior
The page stays without any changes

**Comment by Skrypt** [comment]
Can't repro. Can you send an animated .gif or .png that shows the steps to repro the issue?

**Comment by xperiandri** [comment]
Looks like it happens only when you drag images from Windows Explorer and drop to the web page

**Comment by Skrypt** [comment]
Can't repro either. Please share the repro by doing an animated gif with ScreenToGif free application.

**Comment by Piedone** [comment]
Closing due to no reply from the author.
