### ISSUE TITLE
expect ochard2

### ISSUE THREAD

**Issue by sunzip** [OrchardCMS/OrchardCore#959]
Very happy to join ORCHARD enthusiasts! But would like to know when to publish a beta version of it?

**Comment by jtkech** [comment]
As @Jetski5822 said on [gitter](https://gitter.im/OrchardCMS/Orchard2)

> I would say this week. We are super close, just cleaning up the codebase.

**Comment by xiaoyc** [comment]
Will some doc release together?

**Comment by agriffard** [comment]
@xiaoyc : For the moment, we use the Readme.md files in some modules to generate this documentation site: http://orchardcore.readthedocs.io

**Comment by xiaoyc** [comment]
@agriffard  thanks very much .
