### ISSUE TITLE
Search in Content item has issue

### ISSUE THREAD

**Issue by overstartup** [OrchardCMS/OrchardCore#9595]
If I search for a number or RTL text (Persian words), it doesn't work . 
I'm using this version:
OrchardCore.Application.Cms.Targets  Version="1.0.0-rc2-16261"

1- go to content item
2- type number or RTL words in search box
3- it doesn't show the result 

![image](https://user-images.githubusercontent.com/56995550/120235316-0748f880-c25a-11eb-9b04-ece0ea61ff15.png)

 But it works with English words.

![image](https://user-images.githubusercontent.com/56995550/120235397-2e072f00-c25a-11eb-9e81-f0d061bddfe4.png)

**Comment by Skrypt** [comment]
This one seems related with the YesSQL QueryParser.

**Comment by deanmarcussen** [comment]
Can you try using double quotes around your chars?

I will need to look at it, but that should be a suitable work around for the short term.

**Comment by overstartup** [comment]
![image](https://user-images.githubusercontent.com/56995550/120365904-4b4a0500-c30f-11eb-9fdc-f78dcec102ba.png)

it works by double quotes

**Comment by chinasqzl** [comment]
![image](https://user-images.githubusercontent.com/16968103/122845053-72578d80-d335-11eb-9add-df8d4ba13728.png)

Chinese, quotation marks don't work either.
