### ISSUE TITLE
Content Definition file issue

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#9601]
### Describe the bug
ContentDefinition.json is not being auto-generated.
I run a multi-tenant instance on Azure, and I want to deploy to a slot and swap.
The slot was empty so there was no App_Data or tenant folder, as such, no ContentDefinition.json.
Since ContentDefinition isn't generated, there were no items showing on the backoffice.
This also caused the lucene indexes to not be rebuilt on startup - might be important because the order matters.
Note: I'm using Azure Shell Configuration.

### To Reproduce
1. On a local maching
2. Rename ContentDefinition.json
3. Start the app
4. No items showing on the backoffice

### Expected behavior
Given that they have a valid shell configuration, tenants should be able to rebuild themselves if they don't have a folder in App_Data.

If there is a reason not to check for ContentDefinition.json and rebuild it, maybe also storing it the BlobStoarge like it's done with the AzureShellConfiguration feature would help?

**Comment by jtkech** [comment]
Content type definition are stored by default in a file in our recipes because the `OrchardCore.Contents.FileContentDefinition` feature is enabled.

In your case you may need to not enable this feature in your setup recipe, so that definitions are persisted to the shared database

**Comment by mariojsnunes** [comment]
Yeah that should solve it.
But for existing tenants, if I disable that feature the Content Items disappear, even after reload/restart.
Are they only persisted to the database if it's not enabled on setup?
And what do you mean by shared database? Won't they be persisted to each tenant database?

**Comment by deanmarcussen** [comment]
https://docs.orchardcore.net/en/dev/docs/guides/content-definitions/

**Comment by mariojsnunes** [comment]
Works great, thanks!
