### ISSUE TITLE
can we use blazer server side as front end and adding it to the project?

### ISSUE THREAD

**Issue by swiftinitdotcom** [OrchardCMS/OrchardCore#9608]
will we be able to use blazer server side as front end and adding it to the project?
We want to build cms and also use blazer server side plugins.

**Comment by sebastienros** [comment]
Not sure, if you can answer "can we use Blazor server side and an MVC app in the same project?" then it should be the same answer. This must have been asked already somewhere in the aspnet repos. 

Then there is always the option to use two projects/service and have the blazor app do some http requests to the MVC app (Orchard).

**Comment by sebastienros** [comment]
@dafergu2 says it's possible
