### ISSUE TITLE
From Relational Database to OrchardCore

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#9616]
Are there any methods or modules that
Mapping existing relational database entity types to OrchardCore (Yessql) Model
It is possible to automatically create types based on existing types with only simple adjustments, For example, using Attribute

``` C#
[OC_ContentPart]
    public class Demo
    {
        [OCPart_DisplayText]
        public  string   SalesName {get;set;}
        [OC_TextField]
        public  string SalesNumber {get;set;}
        
    
    }
   
    [OC_ContentType]
    public class Demo
    {
        [OCPart_DisplayText]
        public  string   SalesName {get;set;}
        [OC_TextField(Lenth=25)]
        public  string SalesNumber {get;set;}            
    }
```

Maybe it can also synchronize data to a relational database?

**Comment by hishamco** [comment]
I don't think there's a built-in method to do that in the same way you mentioned above, but simply you can create a recipes from a custom tool, then you can import them to Orchard Core

**Comment by hyzx86** [comment]
So, I also have to develop a data import module for this feature.
At present, OC  seems to be just scattered thirdparoty  modules, the official does not even have a unified place to sum up and collect these modules.

**Comment by hyzx86** [comment]
I think this module is necessary ，because it allows some existing systems to move quickly to oc

**Comment by mariojsnunes** [comment]
You can do this in your own feature by using IContentDefinitionManager for creating ContentTypes and ContentParts, and then IContentManager to create the actual ContentItems.
If you want oc on a new/different database from your old site, I recommend using PetaPoco to access your old database.
Depending on your situation (if your site ContentTypes are the same on each environment), it could be easier to create the ContentTypes on the backoffice manually or with a recipe and only migrate the actual ContentItems.
I'm migrating a SaaS product this way and it's going smothly.

**Comment by hyzx86** [comment]
@mariojsnunes Thanks for your advance ! I will try on this.

**Comment by sebastienros** [comment]
You'd have to re-implement the contents module, which is not realistic. A better approach might be to sync the data stores instead (import/export).
