### ISSUE TITLE
HttpRedirectTask not working as expected

### ISSUE THREAD

**Issue by KshitizGIT** [OrchardCMS/OrchardCore#9617]
HttpRedirectTask not working as expected with liquid expression {{Request.PathBase}}

### To Reproduce
Create a workflow seen in the screenshot

### Expected behavior
Hoping to have it redirected to tenant base path. But it formed some weird url https://localhost:44300/blogSite/workflows/%2FblogSite

### Screenshots
![httpRedirectBugs PNG](https://user-images.githubusercontent.com/8330582/120795832-bab33500-c559-11eb-8602-b738d2cd39d4.jpg)

**Comment by KshitizGIT** [comment]
I narrowed it down to line no 58 in HttpRedirectTask
```csharp
            var location = await _expressionEvaluator.EvaluateAsync(Location, workflowContext, _urlEncoder);
            _httpContextAccessor.HttpContext.Response.Redirect(location, Permanent);

```
Since we _urlEncoder is used, it encodes the url which is meaningful if we were to display in html. But since we have to redirect to the output string. I think we should not use the _urlEncoder.

**Comment by hishamco** [comment]
@KshitizGIT could you please send a PR, then someone on the team will review your suggestion

**Comment by jptissot** [comment]
I ran into the same thing, you have to  `| raw` your path to patch the issue but I agree that a path should not be url encoded by default.

**Comment by Piedone** [comment]
Additionally, you may want to do `{{ '~/' | href | raw }}` instead, see: https://docs.orchardcore.net/en/dev/docs/reference/modules/Liquid/#href

**Comment by jtkech** [comment]
@KshitizGIT @hishamco @Piedone @jptissot 

See my comment https://github.com/OrchardCMS/OrchardCore/pull/9618#issuecomment-868903816
