### ISSUE TITLE
Serilog TenantName not showing up in console.

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9619]
I setup Serilog as described in the Docs but the TenantName always come up blank. Any ideas ?

![image](https://user-images.githubusercontent.com/4681586/120820323-6e003780-c522-11eb-9bec-3bc772c174f6.png)

![image](https://user-images.githubusercontent.com/4681586/120820362-78bacc80-c522-11eb-8924-14adc01e6326.png)

![image](https://user-images.githubusercontent.com/4681586/120820208-53c65980-c522-11eb-9625-86c5e3be764c.png)
![image](https://user-images.githubusercontent.com/4681586/120820277-62ad0c00-c522-11eb-82b6-5708181181ff.png)

**Comment by jptissot** [comment]
I am unable to repro with Orchard's source code.

**Comment by Piedone** [comment]
Do you still think anything needs to be addressed here?
