### ISSUE TITLE
App Insights reports a 404 for every call to GetFile

### ISSUE THREAD

**Issue by randaratceridian** [OrchardCMS/OrchardCore#9629]
### Describe the bug
When monitoring OrchardCore in App Insights, every call to GetFile will return a 404 and then pass. This makes it hard to monitor because these all seem to be false positives. Real errors get lost in the noise. The difference seems to be the same call, with one including an extra escape character.

media%2Fmycompany%2FMX%2FTheHost%20TheProduct%2FWe%20are%20live.png
media%2Fmycompany%2FMX%2FTheHost%2520TheProduct%2FWe%2520are%2520live.png

It almost feels like it's making two calls, possibly due to some older bug.

### To Reproduce
1. Deploy Orchard Core in Azure and use Azure Blobs for media storage
2. Monitor the site using App Insights
3. Look for errors

### Expected behavior
404s should only happen when a file is not found

### Screenshots
![GetFile](https://user-images.githubusercontent.com/49872580/121118067-370e7800-c7e7-11eb-8aa7-fe074b0c681b.png)

**Comment by deanmarcussen** [comment]
We don't actually have an endpoint called Api/GetFile in Orchard Core.

Did you make this yourself or has app insights adjusted the endpoint name?

If this is the standard endpoint it would help to see an actual log file related to an entry - the app insights doesn't give enough information there to really go off.

If you can run the logs in `Debug` level, you should find in App_Data any logs from the `StaticFileMiddleware`. 

Please share those logs.

**Comment by randaratceridian** [comment]
@deanmarcussen Apologies. I misunderstood and thought the call was in OrchardCore, but it looks like it is custom code after all.
