### ISSUE TITLE
What exactly is the syntax supported  at the correlation Task?

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#9634]
Tested not recognized `{{ Workflow.Properties.Doc.Id }}` throws an exception: Workflow is not defined

**Comment by hyzx86** [comment]
When I directly enter the number：
`Unable to cast object of type 'System.Double' to type 'System.String'.`


Strangely enough, this way it works properly
![image](https://user-images.githubusercontent.com/15613121/121306846-ebb4b080-c931-11eb-8268-7fc8e791d05b.png)

**Comment by chinasqzl** [comment]
具我所知，Luquid中，要对对象使用.访问，对象要先注册。不清楚你是否这种情况。
![image](https://user-images.githubusercontent.com/16968103/122846456-6de0a400-d338-11eb-980e-d13e61b45198.png)

**Comment by hyzx86** [comment]
我这是工作流里的json啊



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 22, 2021 09:02 AM
To: ***@***.***&gt;;
Cc: "Tony ***@***.******@***.***&gt;;
Subject: Re: [OrchardCMS/OrchardCore] What exactly is the syntax supported  at the correlation Task? (#9634)




 
具我所知，Luquid中，要对对象使用.访问，对象要先注册。不清楚你是否这种情况。
