### ISSUE TITLE
It has been more than 12 months since a release

### ISSUE THREAD

**Issue by rwasef1830** [OrchardCMS/OrchardCore#9648]
### Describe the bug
The product official nuget packages on the official nuget feed are 12 months old as RC. Multiple breaking changes and major changes and new features(!) and bug fixes have occurred that people depending on the NuGet package feed are missing. I've had to backport many bug fixes myself and override many OrchardCore components with fixed versions.

### Expected behavior
Put a timeline and commit to a feature freeze. Focus only on bug fixes and quality control and cut a branch for release with a commitment to a set of features and release official binaries with the dire needed bugfixes on the NuGet feed (even another RC). This will allow your plugin contributors who develop third party nuget addons (who are vital to the growth of your project), and  people who want to make websites with it and businesses (who may become future sponsors for your project!) who depend on it to rebase all their work on a much newer base.

Asking people to depend on dev packages released on MyGet is not good for the project and in my opinion __not acceptable__. Your build server is not storing previous build NuGet packages of all builds indefinitely, which means in a few weeks, I won't be able to restore NuGet and I am forced to roll forward with introduced bugs and breaking changes and ever changing base. 

In addition, if I use any third party NuGet that depended upon a dev package and later on the dev package disappeared, I can no longer install it! Unless I use nuget binding redirect but then there's a high risk of broken behaviors simply because the addon author didn't test except on the build they built against.

Not releasing even a new RC for this very long time is preventing a lot of people and business from considering your project. No sane person will base his website on a forever unfinished ever shifting code base that may break at any moment next build.

It is possible you may suggest that I copy all of your NuGet packages for a certain build and use a NuGet.config. This is also not an acceptable solution because there is no commitment of any quality level in a dev build. One build may be completely broken or have critical bugs. You are asking me to QC the entire project each build for regressions or forever be stuck on the year old RC (which I am doing now).

Please cut a new RC and stabilize it or make 1.0 release so people (and addons) can come forward and benefit from the new features and fixes that were done past year with some (even medium level) assurance that the build was stabilized.

Thank you for considering my request, and please do not get offended. I am simply saying this out of love and desire to actually use OrchardCore. Thanks for listening.

**Comment by Skrypt** [comment]
Version 1.0 should be released soon. As for the dev branch, I agree that it's only for those who wants to commit into upgrading their websites custom modules periodically more often. Of course, once 1.0 will be released there will be minor patches applied periodically on it which will be more like a normal release cycle.

**Comment by rwasef1830** [comment]
So is there any kind of time line. What order of magnitude are we talking here ? Days ? Weeks ? Months ? Years ?
@Skrypt

**Comment by Skrypt** [comment]
Though updating for a major release (breaking changes) might not be different than using the latest dev branch and updating often. Which means that if we do a lot of breaking changes then you need to migrate your websites and modules still.

You can see the progress on Github by looking at the milestone. Last time I looked we had 5 issues remaining to fix which are mainly small ones. I can't say how much time it will take to push a release as I think it is @agriffard and @sebastienros that will probably take care of this on their spare time.

**Comment by rwasef1830** [comment]
I agree, that's why you shouldn't allow such a long period to pass. The longer you keep people who stick to official release behind the less and less bug reports you will get because less an less people using the newest code, and you will lose their interest and encourage them to move away and leave the project. It is harmful to the community and health of the project.

**Comment by rwasef1830** [comment]
I myself have wanted to open PRs but have been discouraged by the ever changing unstable codebase. And since I am stuck on the old RC I can't make any PR since the code changed too much. So I just override and workaround the problems instead of contributing to the project.

**Comment by Skrypt** [comment]
As for the code base changing, these changes we're necessary. Of course, now, when 1.0 will be release we won't push breaking changes on a 1.0.1 version for example. But, can't prevent breaking changes from happening, this is natural evolution of a project.

**Comment by rwasef1830** [comment]
From what I see in your roadmap, the issue seems to me that Orchard Core is
suffering from feature scope creep. You implemented too many features
beyond the ability to maintain and support them. And since the code base is
monolithic making changes becomes painful and dangerous and regression by
the plentiful and bug reports infinity.

Perhaps consider the following. Split the repo into sub repos, cut and
remove any features that are not used often or leave them to the community
to keep up with the changes in the core.

Stop implementing new features and focus on adding unit tests and
stabilization and refactoring and clean up.

I've noticed with my time with Orchard that one of its issues is that it is
trying to be everything all at once and fit anything which caused the
design to become overly abstracted and overly complicated. There's a few
things that are given very bad confusing names that make sense only when
used in a particular way.

Anyway I am eagerly waiting for a release and wish you guys the best of
luck to accomplish it soon.

**Comment by Skrypt** [comment]
I can't disagree that the base code is starting to grow a lot but at the same time having more features baked in helps people adopting it. It's a two-edged sword ... Unit Tests ; there is never enough of them but at the same time it's never as good as coding it properly 😄 

We've had a discussion about this before with @sebastienros and the fact that we should split the project in 2. One part for the framework which would get updates less often than the CMS part, which would make sense if that's what you meant. I think, we are not there yet as it would require massive amount of work. No one so far as taken the responsibility on doing this because it would surely be a bigger breaking change than what we did in RC2 --> 1.0 dev branch. Maybe version 2.0.

**Comment by rwasef1830** [comment]
You have finally released v1.0.0. Thank you very much for your care and good luck team on the next version adventure!
