### ISSUE TITLE
Cannot run on MariaDB due to migration error

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#9654]
I cloned the Orchard source code and tried to run it against a local MariaDB instance.  It crashes with the following error:

MySqlConnector.MySqlException: 'Specified key was too long; max key length is 3072 bytes'

The error happens at line 33 of \src\OrchardCore.Modules\OrchardCore.Users\Migrations.cs in the "Create" method of the "Migrations" class.:

SchemaBuilder.AlterIndexTable<UserIndex>(table => table
                .CreateIndex("IDX_UserIndex_DocumentId",
                    "DocumentId",
                    "UserId",
                    "NormalizedUserName",
                    "NormalizedEmail",
                    "IsEnabled",
                    "IsLockoutEnabled",
                    "LockoutEndUtc",
                    "AccessFailedCount")
            );

### To Reproduce

1. Create a local database in MariaDB called test.
2. Get the latest code.
3. Build
4. Run OrchardCore.Cms.Web
5. On setup screen, choose the blank recipe, select "MySql," and put connection string "server=localhost; database=test; uid=root; pwd=thepassword;"

### Notes

I found two issues (#2509 and #4753) that may be related but neither seem to help.

If I show tables on the test db, I see this (it seems there are some tables missing):

```
+--------------------+
| Tables_in_test     |
+--------------------+
| aliaspartindex     |
| autoroutepartindex |
| contentitemindex   |
| document           |
| identifiers        |
| userindex          |
+--------------------+
```

**Comment by deanmarcussen** [comment]
Yes looks like the functional tests are failing on MySql 

https://github.com/OrchardCMS/OrchardCore/runs/2794622153

A slight refactor required of the new lockout feature required.

Related https://github.com/OrchardCMS/OrchardCore/issues/9641

**Comment by fuzl-llc** [comment]
Thanks!  Any workarounds you can suggest aside from moving to an earlier snapshot of the code?
