### ISSUE TITLE
Preview doesn't work for HtmlBody part with standard editor

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#9656]
### Describe the bug

The content preview feature doesn't work when using the standard editor for the HtmlBodyPart.

### To Reproduce

1. Create an "HTML Page" content type and add TitlePart, AutoroutePart, and HtmlBodyPart.
2. Create a new HTML page content item.
3. Click the preview button
4. Start typing in the HtmlBody editor.
5. No preview is seen in preview browser window.

Note: All three other editors (WYSIWYG, Trumbowyg, and Monaco) work fine so this probably isn't a huge issue since I'm guessing most will use one of the other editors...

### Expected behavior

Normal live preview should work.

**Comment by Skrypt** [comment]
Issue comes from the fact that the Codemirror editor doesn't update the value of it's textarea on change. It updates the value on the editor object only. And probably on the shadow dom. Now, the preview javascript gets the values from the form elements in the DOM directly. I'm not sure if we should fix this issue or simply deprecate the Codemirror editor now that we have Monaco.
