### ISSUE TITLE
Invalid column name 'UserId' after applying 1.0.0-rc2-16283

### ISSUE THREAD

**Issue by markgould** [OrchardCMS/OrchardCore#9658]
After upgrading from 13450 to 16283 I'm getting the error "Invalid column name 'UserId'"

Digging into the logs, I see there is a failed migration:

> OrchardCore.Data.Migration.DataMigrationManager|Error while running migration version 7 for 'OrchardCore.Users'. Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'IsLockoutEnabled'. Invalid column name 'LockoutEndUtc'. Invalid column name 'AccessFailedCount'. Invalid column name 'IsLockoutEnabled'. Invalid column name 'LockoutEndUtc'. Invalid column name 'AccessFailedCount'.    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown ---    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location where exception was thrown ---    at YesSql.Commands.BatchCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)    at YesSql.Session.FlushAsync()    at YesSql.Session.FlushAsync()    at YesSql.Services.DefaultQuery.Query`1.ListImpl()

**Comment by markgould** [comment]
It looks like PR #5785  may have caused this?

https://github.com/OrchardCMS/OrchardCore/commit/f9f93bf7d2f1a0ce5681f1c6cfb3c8bc85323a6e#diff-a3affe1c5497d75ba4867d94fac5be35f17bb7484033e15f75c50331675a6f57R27

**Comment by markgould** [comment]
Looked at the document table and we are currently on migration version 4. 

To me it looks like the _session.Save is the culprit because it is calling _session.Save which since the User object has those fields on it now, it's trying to update columns that don't yet exist, since they get added in migration 10.

Also, since they are added in UpdateFrom10, it looks like UpdateFrom8 would fail too since those columns won't be there yet to add to the index.

It looks like if I manually add those columns and update the migration metadata, we're going to have a problem since UpdateFrom10

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/9641

**Comment by markgould** [comment]
Ah, thanks. I searched the UserId error and that didn't come up.

**Comment by markgould** [comment]
I think I'm going to have to go further back still - just noting this so you can see it's not just an issue with that one PR.

Error while running migration version 6 for 'OrchardCore.OpenId'. Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'PREFIX_MultiTextFieldIndex'.    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()

**Comment by Skrypt** [comment]
The MultiTextFieldIndex is part of the SQL Field Indexing feature and it says that it fails executing on the OrchardCore.OpenId module. Really weird.

**Comment by deanmarcussen** [comment]
You may need to delete some orphaned indexes, we had issues with them. here is a related discussion https://github.com/OrchardCMS/OrchardCore/discussions/9119
