### ISSUE TITLE
Run Lucene Query admin menu item seems to be in the wrong place

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#9663]
### Describe the bug

The admin menus for search are in this hierarchy

- Search
  - Indexing
    - Lucene Indices
    - Run Lucene Query
   - Queries
     - All Queries
     - Run SQL Query

But it should probably be

- Search
  - Indexing
    - Lucene Indices
   - Queries
     - All Queries
     - Run Lucene Query
     - Run SQL Query

Run Lucene Query is certainly related to Indexing but that page is actually about the querying and is almost the same as the "Run SQL Query" page and has basically the same name.  I was looking for it and the first place I looked was under the "All Queries" node.

**Comment by Skrypt** [comment]
I think it is fine how it is.

**Comment by fuzl-llc** [comment]
Is there any logical argument that separating "Run Lucene Query" from "Run SQL Query" and putting it under "Indexing" is the right thing to do? I'm not trying to be difficult - I just love Orchard and sincerely want to help make it the best it can be. Indexing and running queries are two different things so I just can't see any reasonable way this makes sense... but I'm happy to be educated.

Also, while it may feel "fine" to project developers, especially if that is where it has always been, I don't think we should ignore the very real frustration this can cause new users (and they outnumber the project developers significantly). Orchard is amazing but has a steep learning curve. Therefore, we want to do everything we can to make things intuitively discoverable. I'd *never* look under an "Indexing" menu item if I wanted to *run* a query. If I'm a new user and know where "Run SQL Query" is, and want to "Run Lucene Query," but the menu item isn't right there where it should logically go, under the "Queries" menu, I'm going to get frustrated and annoyed. 

I realize this is a low priority thing but I'd humbly request that this be re-opened and simply marked as low priority.

**Comment by Skrypt** [comment]
While I understand your opinion, I think that if we would want to make this even more obvious the SQL Queries would not even be inside the Search menu. So, while this is only a minor issue and that the important part is that these view works I need to ask @agriffard to reopen the issue if he wants to change these again.

**Comment by fuzl-llc** [comment]
Thanks for the additional input. I never take things personal - just a professional discussion on how to make Orchard great! And I totally understand you all have been at this a long time and many discussions have already happened. Given this new bit of info you've shared, here's my last 2 cents to consider before I let this one go:  Whether to move these out from under the Search menu is a bigger change which adds the additional concern of adding new top level menu items. That is a different question than what I've proposed which is to keep the exact same top level (and 2nd level) structure, and simply move "Run Lucene Query" under its rightful (IMHO) home next to its logical "Run SQL Query" sibling. Thank you for your consideration and all your hard work!

**Comment by Skrypt** [comment]
I think that as an alternative, if you want these menu items to be set differently ; you can reorganize them by overriding them in your own module. But again, I understand your point. I'm leaving this one to @agriffard
