### ISSUE TITLE
AddDatabaseShellsConfiguration Extension Method Missing

### ISSUE THREAD

**Issue by pezadmin** [OrchardCMS/OrchardCore#9668]
### Describe the bug

I have tried importing the above extension method in my code but I have not been successful. In which Nuget Package can I find it?

**Comment by jtkech** [comment]
Not yet available from the Nuget feed, only from the Cloudsmith feed (dev branch), see the Nuget.config in our repo.

The version 1.0 of OrchardCore will be shipped soon, so it will be available soon from the Nuget packages feed.
