### ISSUE TITLE
Active Themes management interface to add multiple picture slider JS？？

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#969]
Active Themes  management interface in the picture, add a slider JS, increase the number of picture rotation? Will it be better to experience?
![qq 20170907132817](https://user-images.githubusercontent.com/28694676/30147508-3b0b424c-93d1-11e7-899e-9760ae00f81d.png)

**Comment by pgy866** [comment]
Can the template add some data like the template effect display? Will there be a better experience?

**Comment by agriffard** [comment]
For the moment, you only can provide on picture which is called theme.png.
