### ISSUE TITLE
HEAD /login returns 404

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#9692]
Head request to `/login` returns **404**.
In my opinion if endpoint exists, then **HEAD** should return **200**.

![image](https://user-images.githubusercontent.com/6403130/122024736-fdca9f00-cdc8-11eb-9e05-7ddfc7392180.png)

You can reproduce this issue using postman, curl etc.

![image](https://user-images.githubusercontent.com/6403130/122025318-96f9b580-cdc9-11eb-90aa-2f10c07efae7.png)

**Comment by HengzheLi** [comment]
Possibly /login only support GET/POST method

**Comment by lampersky** [comment]
> I'm not sure I see the use case for a HEAD request here?

I don't see either. But for some reason each day I can observe hundreds of failed request in AppInsights.
Maybe those requests are not coming from regular browsers.

**Comment by deanmarcussen** [comment]
> Maybe those requests are not coming from regular browsers.

I would suggest looking into where these requests are coming from 

It is hard for me to evaluate if it is something that needs fixing without enough information

**Comment by lampersky** [comment]
> I would suggest looking into where these requests are coming from

it looks like some bots are performing those requests

I will filter them out from my app insights.

Thank you all.
