### ISSUE TITLE
Trumbowyg icons are giant

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#9693]
### Describe the bug
Updated to 1.0.0-rc2-16262 and now the trumbowyg icons are giant when using an HTML body part.
**EDIT:** Still a problem in 1.0.0-rc2-16296

### To Reproduce

1. Create a fresh OC site using the blog theme.
2. Add an HTML body part to the blog post content type.
3. Set the site to use framework CDN.
4. Create a new blog post.

### Screenshots
![image](https://user-images.githubusercontent.com/68876423/122060666-c86b8480-cdbb-11eb-838e-ee770e64759e.png)

From the console window:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/trumbowyg@2.24.0/dist/ui/trumbowyg.css' with computed SHA-256 integrity 'c3pFwAU4HTx9A6bnVa7aUSYrnr/bWqPfHEe7UuhE2e8='. The resource has been blocked.
```

### Workaround
Disable CDN from the admin settings

**Comment by Skrypt** [comment]
Try with version 16296 we updated Trumbowyg to latest version recently.

**Comment by rjpowers10** [comment]
> Try with version 16296 we updated Trumbowyg to latest version recently.

Yes, 1.0.0-rc2-16262 contains the new Trumbowyg version (v2.24). But I also tried the latest version of OC, 1.0.0-rc2-16296 and the problem is still there.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/122075765-50f02200-cdc8-11eb-8228-d8c256cdd57f.png)

I don't get this issue here with Microsoft Edge by testing quickly. Can you try to clear your browser cache?

**Comment by Skrypt** [comment]
Ok nevermind I forgot to enable the CDN option in the admin as it is disabled by default now.
