### ISSUE TITLE
Trumbowyg: Missing Shortcodes icon

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#9696]
![image](https://user-images.githubusercontent.com/703248/122076934-967a1280-cdfb-11eb-95c1-d848674cf945.png)

The Shortcodes button icon is not displayed with the latest changes in Trumbowyg.

@deanmarcussen : Do you remember where the css/icon is coming from?

**Comment by deanmarcussen** [comment]
From memory here https://github.com/OrchardCMS/OrchardCore/blob/b9c6b0e4dbfbefc05db35d50f853f185b12b2471/src/OrchardCore.Modules/OrchardCore.ContentFields/Views/HtmlField-Trumbowyg.Edit.cshtml#L76

It was documented I think on trumbowyg docs that was the way to do it, so maybe there is just a small change with trumbowyg.

See what the js object looks like?
