### ISSUE TITLE
Add ability to set admin panel languages regardless of content item languages

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#9721]
### Is your feature request related to a problem? Please describe.
Sometimes admin panel users can read a language that is not used on pages.
For example, we need a website in Ukrainian and English. There is no admin panel localization in Ukrainian but there is localization in Russian. Which can be read by admin panel users. In this case, we need to have 3 languages enabled while only 2 are used for content items. And we need to provide some mechanism to switch to Russian or make it default to display admin panel in it.

### Describe the solution you'd like
There are 2 lists of languages: for content items and for admin panel

**Comment by hishamco** [comment]
This is already requested long time ago, perhaps we need to investigate on this in the upcoming versions

**Comment by hishamco** [comment]
I will try to find the previous issue and likk it

**Comment by hyzx86** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/7248

Although the language switching function is not easy to use, at least it can still be worked. .
But after updating the dev version, it is found that the language cannot be switched, even if the localization module is disabled, it cannot be switched back to the English version.

**Comment by Piedone** [comment]
The Admin Culture Picker feature now provides this.
