### ISSUE TITLE
Is there any new on support for DotNet Core 5.0 for OrchardCore.Application.Targets? Currently it only targets up to 3.1.

### ISSUE THREAD

**Issue by sudheeryadav013** [OrchardCMS/OrchardCore#9724]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

**Comment by sudheeryadav013** [comment]
I am migrating my code from core 3.1 to 5.0 but I am facing issues due to OrchardCore.Application.Targets only support up to 3.1.

**Comment by jptissot** [comment]
@sudheeryadav013 do you use the latest nuget dev feed on cloudsmith or the released RC2 version ?

**Comment by sudheeryadav013** [comment]
I am using it from nuget version 1.0.0-rc2-13450 which  is the latest and support up to 3.1 mention on nuget.

**Comment by Skrypt** [comment]
Latest is 1.0.0-rc2-16309 which supports multi-targetting 3.1 and 5.0

**Comment by sudheeryadav013** [comment]
I couldn't find it on NuGet, How can I include it in my project?
