### ISSUE TITLE
IContentManager isn't saving updates to TitlePart.Title

### ISSUE THREAD

**Issue by fuzl-llc** [OrchardCMS/OrchardCore#9727]
### Describe the bug

I'm using a custom module form in an ASP.NET view that gets posted to an ASP.NET controller. I inject IContentManager into the controller and use it to create and save a content item. While it is able to create the content item and save properties defined as fields on the content type, it isn't saving updates to the Title property on TitlePart.

### To Reproduce

Using the admin UI, create a new "Conversation" content type with a title part, autoroute part, and a text field named "Message." Create a ContactViewModel class with string Name and Message properties.

Create an ASP.NET core view where the user can submit a form to specify the "Name" and "Message" field values.  Create a controller with IContentManager injected and add the following code for the form post handler:

```
[Route("contact")]
[HttpPost]
public async Task<ActionResult> Index(ContactViewModel vm)
{
    var contentItem = await _contentManager.NewAsync("Conversation");

    var titlePart = contentItem.As<TitlePart>();
    titlePart.Title = $"Message from {vm.Name}";
    // contentItem.Content.TitlePart.Title = $"Message from {vm.Name}";

    contentItem.Alter<ContentPart>("Conversation", x =>
    {
        x.Alter<TextField>(nameof(vm.Message), textField => textField.Text = vm.Message);
    });

    var result = await _contentManager.UpdateValidateAndCreateAsync(contentItem, VersionOptions.Draft);

    if (result.Succeeded)
        await _contentManager.PublishAsync(contentItem);

    return RedirectToAction("Index");
}
```

I try to set the title, set the "Message" field, and save/publish the content item. All seems to work but when I go to the admin content items list the Title is not being saved. The "Message" field value is saved properly.

Interestingly, if I inspect the contentItem.Content value in Visual Studio after setting titlePart.Title it isn't reflected. If I instead try to update with the commented out line above `contentItem.Content.TitlePart.Title = $"Message from {vm.Name}";` the change is reflected when I inspect the contentItem.Content value but it still doesn't get saved. I tried several other ways to get that title property to save (e.g. using .Alter like I did for setting the Message property) but nothing works.  Maybe I'm missing something but it seems like the above should work...  but please let me know if this isn't a bug and I'm just doing it wrong.

### Expected behavior

A new "Conversation" content item is saved with the title properly set.

**Comment by fuzl-llc** [comment]
So of course after I spend hours failing and then submit this bug report I try one more thing and it works. If I do this instead:

`contentItem.DisplayText = $"Message from {vm.Name}";`

...then the title property gets saved properly. Is this the proper way to do this and everything is fine or is there still a bug? It is very surprising that I can't do the old `.As<TtilePart>()` thing I remember from Orchard 1 or update the contentItem.Content fields directly but maybe this is just the way it its. I'll be interested to see what happens if I try to update other kinds of built in parts but TitlePart is all I need to get working now.

**Comment by deanmarcussen** [comment]
The `TitlePart` is now only an editor for `contentItem.DisplayText`

We're probably at the point we should stop saving data in it (and probably obsolete the value property)
