### ISSUE TITLE
Unable to update a content item

### ISSUE THREAD

**Issue by intellimedhu** [OrchardCMS/OrchardCore#9759]
```
System.ArgumentException: An item with the same key has already been added. Key: 19627
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at YesSql.Session.Save(Object entity, Boolean checkConcurrency, String collection)
   at OrchardCore.ContentManagement.DefaultContentManager.UpdateAsync(ContentItem contentItem)
```
19627 is the document ID

The exception is thrown randomly.

The code is quite simple:
```
var contentItem = await _contentManager.GetAsync("ID");
contentItem.Alter<APart>(part => part.A = "A");
await _contentManager.UpdateAsync(contentItem);
```

OC version: 1.0.0-rc2-16317

**Comment by lampersky** [comment]
I had same issue https://github.com/OrchardCMS/OrchardCore/discussions/9237

**Comment by deanmarcussen** [comment]
This suggest the code might be more complicated.

Do you have any `Task.WhenAll` operating on the sample code?

What is the context that you are calling this from, is it one item being updated per http request, or many>

**Comment by intellimedhu** [comment]
Yes I have `Task.WhenAll` with 2 methods:
- update content item
- insert another record to db (not related to content item)

I try to await both one by one.

**Comment by deanmarcussen** [comment]
> Yes I have Task.WhenAll with 2 methods:

An `ISession` is not threadsafe, so you can't ever `Task.WhenAll` it. So that sounds like the issue
