### ISSUE TITLE
Dump objects in Liquid page or template

### ISSUE THREAD

**Issue by jeremycook** [OrchardCMS/OrchardCore#976]
I'd like to be able to dump the contents of an object in Liquid templates.

One thought was a `json` filter that would output formatted JSON, and would be used like so:

    {{ Site | json }}

@sebastienros cautioned "not sure it's good as it would accept anything, and potentially expose unauthorized information. better to handle it on a case by case."

**Comment by jeremycook** [comment]
If the concern for exposing unauthorized information is a show stopper, perhaps a filter that outputs just property names would be acceptable.

    {{ Site | properties }}

A "properties" filter could list the object's properties and descendant properties in JSON format, but without values.

**Comment by hishamco** [comment]
> {{ Site | json }}

This address the issue https://github.com/sebastienros/fluid/issues/115

**Comment by sebastienros** [comment]
no, the ` | json` we implemented is the same  as shopify and in the end it's just to encode in json.
We still need one that dumps the object in a tree view, like this:

![image](https://user-images.githubusercontent.com/1165805/56387917-7aa66200-61da-11e9-86ce-829368a60d6a.png)

**Comment by hishamco** [comment]
@deanmarcussen is your dump PR related to this one?

**Comment by agriffard** [comment]
Can be closed?

**Comment by deanmarcussen** [comment]
I think so @agriffard but we need to document the `ConsoleLog` helper Sebastien wrote as that is the fix / alternative for this issue

**Comment by jeremycook** [comment]
Chiming in, my primary use case is for exploring what properties and objects are available, and troubleshooting situations where I get no output and don't know why. If it seems like that use case is addressed then closing this seems fine to me.

One more thought, the ability to dump the root object would be extremely helpful. Perhaps this is possible already and I've overlooked it.

**Comment by Skrypt** [comment]
I normally simply just do `<code>{{ Model.Content }} </code>`
And then I'm using json editor online website https://jsoneditoronline.org/
To format it beautifully as a tree view

**Comment by deanmarcussen** [comment]
@sebastienros added a `ConsoleLog` helper which dumps content items to the chrome console, which we're proposing as the solution to this.

Have you tried it @jeremycook / @Skrypt ? 

There's a PR in for extending it to dump shapes well https://github.com/OrchardCMS/OrchardCore/pull/4495 

and we would also need to write a liquid filter to match

**Comment by jeremycook** [comment]
Thanks @deanmarcussen I haven't had a chance to try it but if everyone says it is golden then I'm good with it. I'll open another issue if I see a need.
