### ISSUE TITLE
RegisterUserTask: Subject & Template for confirmation email should not be required if Send Email is unchecked

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/OrchardCore#9760]
### Describe the bug
Subject & Template for confirmation email are required even if Send Confirmation Email is not checked
### To Reproduce
1. Workflows
2. Create Workflow
3. Add Task "Register User"

### Expected behavior
Subject & Template for confirmation email fields should be required only if Send Confirmation Email is checked

### Screenshots
![image](https://user-images.githubusercontent.com/1871551/123142522-31a96280-d462-11eb-8470-41c0b2381dd6.png)

**Comment by hishamco** [comment]
@urbanit I'm glad if you push a PR for it
