### ISSUE TITLE
How  use http request to start/resume a workflow

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#9770]
I have created a workflow definition like this:
How can I send the `correlationId` when start request ?

Because my workflow requires multiple instances at the same time, and multiple levels of approval are required in the process
So I want to isolate them using Correlation Id

![image](https://user-images.githubusercontent.com/15613121/123396966-7bb25580-d5d4-11eb-89dc-1fabd2eaad30.png)

**Comment by weirdyang** [comment]
You need to use the `correlate task` to set a value that will be used as the correlation id.
