### ISSUE TITLE
Editing menu causes exception: Shape type 'ContentPart_Thumbnail' not found

### ISSUE THREAD

**Issue by thinkcodellc** [OrchardCMS/OrchardCore#9773]
Editing the menu causes an exception An unhandled exception occurred while processing the request.
Exception: Shape type 'ContentPart_Thumbnail' not found
OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context)
Currently on RC2-15292.
I suppose this was discussed earlier in issues - https://github.com/OrchardCMS/OrchardCore/issues/4237 but not sure what needs to be done. Please advise.

![image](https://user-images.githubusercontent.com/14080870/123458746-03836a00-d5ab-11eb-8b6d-c975c39d4add.png)

**Comment by deanmarcussen** [comment]
quite simple, upgrade.

**Comment by thinkcodellc** [comment]
Thanks @deanmarcussen . However the recent upgrade contained Fluid fixes for Liquid syntax that was causing trouble. I was wondering if there is any suggestion on syntax to render the form block, since that stopped working. Thanks in advance.

   
                <li>
                    {% block "form", area:"OrchardCore.Users", controller:"Account", action:"LogOff", method:"post", class:"form-inline", id:"logoff-form"  %}
                        <a href="#" onclick="document.getElementById('logoff-form').submit();" class="section-scroll"> <i class="fa fa-lock"></i> Log Off</a>
                    {% endblock %}
                </li>

**Comment by ns8482e** [comment]
If you would like to stay on `RC2-15292 `then Temporary workaround is to create a template `ContentPart.Thumbnail.cshtml` in  `Views` folder of application project.

**Comment by thinkcodellc** [comment]
Thanks
