### ISSUE TITLE
Admin menu Recipes is empty!!

### ISSUE THREAD

**Issue by MRSheikh** [OrchardCMS/OrchardCore#9785]
after i upgrade to lates dev branch, Admin menu Recipes nothing shows.
`Nothing here! There are no recipes for the moment. `

**Comment by deanmarcussen** [comment]
This is by design. Setup recipes are no longer listed in the recipes list, as they do not run well, when they are run on sites that have already been setup.

if you include your own non setup recipes, via a `Recipes` folder, they will but listed
