### ISSUE TITLE
Base url is ignored in redirect_uri when Microsoft AD authentication is enabled

### ISSUE THREAD

**Issue by bambuca** [OrchardCMS/OrchardCore#9806]
### Describe the bug
Our instance runs on http in the docker and is behind a proxy that handles https.
Setting the Base url to "https://ourdomain.cz" (in Configuration>Settings>General) is ignored when generating the redirect_uri value in the url when redirecting to login.microsoftonline.com. See this stripped url https://login.microsoftonline.com/(blabla)/oauth2/authorize?client_id=(blabla)&redirect_uri=http%3A%2F%2Fourdomain.cz%2Fsignin-oidc&response_type=id_token&..... - the redirect_uri is http://ourdomain.cz/signin-oidc, but the 

### To Reproduce
1. Go to 'admin'
2. Set the Base Url to https://test.com
3. Logout
4. Go to admin and click Azure AD login button
5. redirect_uri in the url should be https://test.com/signin-oidc but is different

### Expected behavior
See step 5 in previous section

**Comment by jptissot** [comment]
Did you set up the Https / reverse proxy modules ? I had the same issue until I setup the reverse-proxy module

**Comment by bambuca** [comment]
Thank you. I've enabled "Reverse Proxy Configuration" feature and now it's working.
