### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 6: 'database table is locked: ContentItemIndex'.'

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#9807]
### Describe the bug
In my code, when running "_lucene.ProcessContentItemsAsync" it causes database table locked error:
This error only exists in recent weeks' updates.

![image](https://user-images.githubusercontent.com/16193516/123695051-ffc54100-d851-11eb-815b-90ef9d24e570.png)

**Comment by Skrypt** [comment]
This is generally happening when you are trying to write and read on the same YesSQL session. Indexing task should be deferred like we did in the LuceneIndexingHandler.

**Comment by orchardc** [comment]
What I actually found is these two lines of code cannot run together, if I comment either of them , it will not lock.

So I think @Skrypt is right. Now the question is how to make sure they are not trying to write and read on the same YesSQL session? Note both statements are Orchard functions, there is no custom code.

```
            await _lucene.RebuildIndexAsync(indexName);
            await _lucene.ProcessContentItemsAsync(indexName);
```

**Comment by Piedone** [comment]
This exception doesn't happen in the latest `main` with a Lucene index rebuild, with SQLite. Please reopen if still applicable.
