### ISSUE TITLE
Issues with setup page on latest release

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#9822]
### Describe the bug
Seems to be an issue with the layout and js on the setup page in latest release today. rc2-16337

<img width="1418" alt="Screen Shot 2021-06-30 at 2 01 55 pm" src="https://user-images.githubusercontent.com/2867511/123900091-c0126c80-d9ab-11eb-908e-a3472c29117e.png">

If the site is a brand new setup the recipe selector doesn't work.

**Comment by Skrypt** [comment]
Regression from #9804
