### ISSUE TITLE
Use redis for storing session identity tickets

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9834]
Sometimes, the authentication cookie for a request can get quite big with large identities. Could we implement a module that adds a Redis store for the identity tickets? 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.sessionstore?view=aspnetcore-5.0#Microsoft_AspNetCore_Authentication_Cookies_CookieAuthenticationOptions_SessionStore

https://mikerussellnz.github.io/.NET-Core-Auth-Ticket-Redis/

**Comment by sebastienros** [comment]
Moving to https://github.com/OrchardCMS/OrchardCore/issues/12142 instead
