### ISSUE TITLE
Lucene Query doesn't return anything - even after recreate, reset or rebuild?

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#9838]
### Describe the bug

I found Lucene Query doesn't work and returns no result.

I tried recreating a new index; reset it; rebuild it; but none of them works.

Any idea?

![image](https://user-images.githubusercontent.com/16193516/124110161-dda10e00-da5f-11eb-94c9-02194ab8ac52.png)

**Comment by Skrypt** [comment]
Make sure you are indexing a Content Type in the index settings. Also, if your content items have been created before creating the index you will require to publish the content items so that they get added to the IndexingTask table. You could alternatively do a SQL Query to fill up that table with the Content Item you want to index. We already have an issue open about this to repopulate the IndexingTask table.

**Comment by orchardc** [comment]
Hi @Skrypt , it is strange that my IndexingTask table doesn't contain any 'Product' content type.

I try to reset or rebuild, even manually delete the lucene.status.json file and Lucene folder then recreate the index,  but nothing works. Any idea how to totally RESET the whole Lucene search function?

![image](https://user-images.githubusercontent.com/16193516/124395516-81a6e580-dcfc-11eb-9ab0-22feb9c65b31.png)

**Comment by Skrypt** [comment]
Like I said previously you need to publish back the content items in the admin UI or create a SQL Query that will add the content items you wish to index in the IndexingTask table else they won't get indexed.

**Comment by orchardc** [comment]
Hi @Skrypt , I had published the Content Items manually in the admin UI  but the search did not return anything still (no items are added to the IndexingTask). When you say _"That's because you created the Lucene index (or added the content type in the index) after creating these content items."_ In fact I tried to delete and recreate the Search Indices (after creating the content items) as well. But none of them work.

**Comment by orchardc** [comment]
In the Search folder,\Sites\Default\Lucene\ProductSearch, there are two files, 1kb in size.
![image](https://user-images.githubusercontent.com/16193516/124741838-0c156200-df14-11eb-8f5e-4d97d519ab73.png)

In lucene.status.json file
{
  "ProductSearch": 0
}

In IndexingTask table is empty

I have tried to reset/rebuild/delete and recreate  Lucene Indicies from the Admin UI; as well as Publish the content items.


None of the approaches works. I guess just need a way to reset this function. Any comment?

**Comment by orchardc** [comment]
This is 'fixed' now - Something was wrong I guess, so end up with creating a new DB.
