### ISSUE TITLE
Can not Enable any Feature on Multi-Instance environment

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#9840]
Can not Enable any Feature on Multi-Instance environment

### To Reproduce

1. Spin up Multi-instance env
2. Use Database Shell Configuration, https://docs.orchardcore.net/en/dev/docs/reference/core/Shells/#enable-database-shells-configuration
```.AddDatabaseShellsConfiguration()```
3. I'm using Redis Features too 
```
 var redisFeatures = new[]
                {
                    "OrchardCore.Redis.DataProtection", // Asp.Net Core DPAPI Redis Storage
                    "OrchardCore.Redis.Lock", // Distributed Lock for Multi-instance setup and Shell Activation
                    "OrchardCore.Redis.Bus", // Distributed Signals, IMessageBus Redis implementation 
                    "OrchardCore.Redis.Cache" // Distributed Redis Cache
                };
                builder.AddTenantFeatures(redisFeatures)
```
3. Try to Enable Any Feature in Admin Dashboard ```Admin/Features```
4. When you click Enable button after page refresh Feature still has the "Enable" button displayed. 
![image](https://user-images.githubusercontent.com/13991195/124180988-c9620e80-da69-11eb-829b-3cb0fa5b8c8a.png)

Sometimes it just fails with error "An error occurred while executing this request."
![image](https://user-images.githubusercontent.com/13991195/124180688-67a1a480-da69-11eb-9f5e-4634d0c0cb9d.png)

5. See the Logs
`{"@t":"2021-07-01T19:05:05.4867172Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"System.InvalidOperationException: Invalid serial number for shell descriptor\n   at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(Int32 priorSerialNumber, IEnumerable`1 enabledFeatures)\n   at OrchardCore.Environment.Shell.ShellDescriptorFeaturesManager.UpdateFeaturesAsync(ShellDescriptor shellDescriptor, IEnumerable`1 featuresToDisable, IEnumerable`1 featuresToEnable, Boolean force)\n   at OrchardCore.Environment.Shell.ShellFeaturesManagerExtensions.EnableFeaturesAsync(IShellFeaturesManager shellFeaturesManager, IEnumerable`1 features, Boolean force)\n   at OrchardCore.Features.Controllers.AdminController.EnableOrDisableFeaturesAsync(IEnumerable`1 features, FeaturesBulkAction action, Nullable`1 force)\n   at OrchardCore.Features.Controllers.AdminController.Enable(String id)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)\n   at OrchardCore.Media.Services.MediaFileStoreResolverMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\n   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware","RequestId":"0HM9SO42IKG4H:00000002","RequestPath":"/Admin/Features/OrchardCore.Forms/Enable","SpanId":"|365ed3cb-401133d0986d6962.","TraceId":"365ed3cb-401133d0986d6962","ParentId":"","ConnectionId":"0HM9SO42IKG4H","ExceptionDetail":{"Type":"System.InvalidOperationException","HResult":-2146233079,"Message":"Invalid serial number for shell descriptor","Source":"OrchardCore.Infrastructure"}}`

### Expected behavior
Feature should be enabled

**Comment by rserj** [comment]
@jtkech when you have a chance can you please take a look?

**Comment by jtkech** [comment]
@rserj 

- If possible, I suggest to use `.AddDatabaseShellsConfiguration()` from the beginning in place of step 2.

- No need to use `OC.Redis.Bus`, for cache invalidation we don't use the signal service anymore.

- So it seems that you have a sateless configuration by sharing tenant specific configs / settings through the database, and by sharing other settings through database documents, and their cached data through a Redis shared cache.

    **But you are not yet ready to keep in sync tenant states**. For some settings we don't need to restart a given tenant, so in a distributed env we only need to invalidate local caches. But for some other settings we need to release a given tenant so that it is reloaded on a subsequent request, in that case we need to do the same on each instance.

   When enabling / disabling features it is the same, a given tenant needs to be reloaded to take into account the up to date shell descriptor (and its serial number). Note: Here the behavior depends on how a given request is load balanced (using or not some affinity e.g. based on cookies), maybe you hit a given instance but you are redirected to another one.

- So, at this point try to enable the `OrchardCore.Tenants.Distributed` feature and let me know what happens.

**Comment by rserj** [comment]
>maybe you hit a given instance but you are redirected to another one

this is the case, we don't use sticky session
I've tried to enable ```OrchardCore.Tenants.Distributed``` here is my code

```
var distributedFeatures = new[]
                {
                    "OrchardCore.Redis.DataProtection", // Asp.Net Core DPAPI Redis Storage
                    "OrchardCore.Redis.Lock", // Distributed Lock for Multi-instance auto-setup and Shell activation
                    "OrchardCore.Redis.Cache", // Distributed Redis Cache
                };

                builder

                    // Make Orchard restore its tenant state when it starts, otherwise, setup screen will be displayed
                    .AddDatabaseShellsConfiguration()

                    .AddSetupFeatures(distributedFeatures)
                    .AddTenantFeatures(distributedFeatures)
                    .AddTenantFeatures("OrchardCore.Tenants.Distributed"
                    ...
```
                    
**It does not fail with Exception anymore**, but I have to refresh the page one more time to see the actual result
![image](https://user-images.githubusercontent.com/13991195/124303271-18b24880-db17-11eb-89cf-ee2377dc6c03.png)
It might be caching issue.

**Comment by jtkech** [comment]
> It does not fail with Exception anymore!

Good to know!

> but I have to refresh the page one more time to see the actual result after I Enable a Feature
> It might be caching issue.

Yes for most of the documents we check on demand on each scope if the related identifier has changed, but not for the shell descriptor that is held by the local shell until it is released. Here, we share states identifiers to know if a shell needs to be released, but each instance pool them only each second, so here it seems that the redirect happens too soon.

So, one solution would be to use some cookie affinity with your balancer / ingress to ensure that a given client remains tied to the same instance.

That said, if it is really necessary, in the `Features` controller action we could check if the shell descriptor serial number has changed, and then maybe release the shell locally and redirect again, hmm but if redirected again to another instance where the local shell is also not yet released ;) need to think about it.

In the meantime, in the `Features()` controller action, can you try the folllowing to get the local and shared serial numbers, and then render them to see if there are diferent or not.

        public async Task<ActionResult> Features()
        {
            var shellDescriptorManager = ShellScope.Services.GetRequiredService<IShellDescriptorManager>();
            var sharedSerialNumber = (await shellDescriptorManager.GetShellDescriptorAsync()).SerialNumber;
            var localSerialNumber = ShellScope.Context.Blueprint.Descriptor.SerialNumber;

**Comment by Piedone** [comment]
Closing due to no reply from the author.
