### ISSUE TITLE
Cors policy changes may require a site reload to be activated

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#9841]
### Describe the bug
Recently adding a new cors policy on a tenant and it just didn't seem to be being acknowledged and the cross domain request was blocked - this is for a web api controller. The I decided to disabled and enable the tenant from the default site and boom it started working.

I am thinking this might require the current tenant to be reloaded for policies to be activated similar to the general settings.

Not sure if anyone else has experienced this.

### To Reproduce
1. Go to 'Settings > CORS'.
2. Click on 'Add policy'.
3. Create a new policy for a cross site request.
4. Make an cross site request that would require the policy - it should not work be cause of missing headers.
5. Disable and renable the tenant and it should now work.

### Expected behavior
Policies should be able to be activated or modified without having to go to the default site to reload the site.

**Comment by jtkech** [comment]
Yes, looking at the code it doesn't release the tenant / shell, as we do in some other settings drivers so that the tenant is reloaded on a subsequent request. Note: Here the job is done in a controller, not in a driver.

**Comment by scleaver** [comment]
@jtkech - like your opinion here - seems rather risky to restart when you create each policy (however I guess this is no different to how the general settings UI works). Wondering if the policy list view needs a button like "Apply policy changes and reload tenant" or should we just have the reload take place on the creation or update of a policy?

**Comment by jtkech** [comment]
@scleaver 

Not all `SectionDisplayDriver<ISite, SomeSettings>` release the shell on updating but there are many that do it.

Is it risky i don't know, i'm not an expert on security, what i can say is that there are many `SectionDisplayDriver<ISite, SomeSettings>` that are also related to security, and that release the shell on updating.

    await _shellHost.ReleaseShellContextAsync(_shellSettings);

And that just use this kind of alert message in their view.

    @T["The current tenant will be reloaded when the settings are saved."]
