### ISSUE TITLE
Admin: No redirection to login page if not connected

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#985]
If I am not connected and I open an url like /Admin/Settings/general, the page stays blank and I am not redirected to /Login?ReturnUrl=%2FAdmin%2FSettings%2Fgeneral

It only works if I open /Admin

**Comment by agriffard** [comment]
It returns a `401 Unauthorized` but doesn't redirect to the login page.

**Comment by agriffard** [comment]
Seeing this : http://blogs.lessthandot.com/index.php/webdev/serverprogramming/aspnet/custom-authentication-in-asp-net-core-without-identity/
I supposed it was due to the changes between ASP.NET Core 1.x and 2.0 when the AutomaticChallenge option has been lost.

So I tried to add a custom OnRedirectToLogin event in OrchardCore.Users Startup.cs :

```
.AddCookie(IdentityConstants.ApplicationScheme, o =>
            {
                o.LoginPath = new PathString("/Account/Login");
                o.Events = new CookieAuthenticationEvents
                {
                    OnValidatePrincipal = async context =>
                    {
                        await SecurityStampValidator.ValidatePrincipalAsync(context);
                    }
                    ,
                    // Overwrite the attempt to redirect API calls to login page w/ 401 response instead
                    OnRedirectToLogin = context => 
                    {
                        // return true 401 to API calls, continue redirect to login for interactive
                        if (context.Request.Path.StartsWithSegments("/api") && context.Response.StatusCode == 200)
                        {
                            context.Response.StatusCode = 401;
                            return Task.FromResult<object>(null);
                        }

                        context.Response.Redirect(context.RedirectUri);
                        return Task.FromResult<object>(null);
                    }
                };
            })
```

and put a breakpoint to see if it was passing into to this to return a 401, but it doesn't so I don't have any other clue.

**Comment by sebastienros** [comment]
Weird as I got redirected automatically last time I tried. Like a few days ago. Will try again.

**Comment by sebastienros** [comment]
So if we are not authenticated and we go to /admin then the redirection happens correctly. Even from a tenant.
