### ISSUE TITLE
Support custom parameters in the OpenId Connect client

### ISSUE THREAD

**Issue by deanmarcussen** [OrchardCMS/OrchardCore#9856]
### Is your feature request related to a problem? Please describe.

The `OpenIdConnectOptions` support an `OnRedirectToIdentityProvider` event feature which allows setting of custom parameters on the protocal message when generating an `OpenIdConnectMessage` to an external provider.

We need to be able to send some custom parameters to some of our tenants `AzureB2C` auth servers (but not all, and it varies per tenant)

i.e.
```
            options.Events.OnRedirectToIdentityProvider = (context) =>
            {
                context.ProtocolMessage.SetParameter("foo", "bar");

                return Task.CompletedTask;
            };
```

### Describe the solution you'd like

Editable parameter (kvp) options on the `OpenIdConnectSettings` so we can configure different tenants to use different custom parameters.

### Describe alternatives you've considered

`OpenIdConnectOptions` is configurable vis `PostConfigure` so we can do this manually, in code, but it would be nicer if we were able to support this through UI based settings.

// cc @MichaelPetrinolis @kevinchalet 

Currently working on a pr for this unless anyone sees any issues with supporting this through the UI?

**Comment by MichaelPetrinolis** [comment]
The only thing is that we will cover only a fraction of the functionality provided by the Events. But could be extended as needed :)
