### ISSUE TITLE
Recaptcha not showing on register/login page

### ISSUE THREAD

**Issue by MohitNaroliya** [OrchardCMS/OrchardCore#9857]
### Describe the bug
I've upgraded with latest OC packages and now the Recaptcha not showing on login/Register page and it throw an error message when we try to submit register details - 

### Screenshots
![image](https://user-images.githubusercontent.com/26460323/124468001-35b87700-ddb6-11eb-96ee-d5c42444d87f.png)

**Comment by Skrypt** [comment]
Recaptcha shows after some login attemps failed. I need to test with the registration form.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/124508505-13b2fa80-dd9e-11eb-8d5e-8dc745ebbe7f.png)

**Comment by liketodev1** [comment]
@Skrypt - Any update on this?

**Comment by Skrypt** [comment]
Well I would need to be able to repro. Are you sure you have set a proper Recaptcha key in the admin settings?

**Comment by liketodev1** [comment]
Yes, I am sure about this and it only doesn't add the Recaptcha section on the register page all stuff related to setting looks good and configured.

**Comment by Skrypt** [comment]
Have you used a Google Entreprise Recaptcha key or a standard one?

**Comment by Piedone** [comment]
Closing due to no reply from the author.
