### ISSUE TITLE
sometimes admin page is loaded without styles

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#9862]
Once in a while, page is loaded without styles.
I've never observed this in PROD env, only when playing with OC locally.

https://user-images.githubusercontent.com/6403130/124588186-cfd0fb80-de58-11eb-96b9-9ccc8180d88c.mp4

### Screenshots
![image](https://user-images.githubusercontent.com/6403130/124588462-1d4d6880-de59-11eb-9680-ef2ff0739497.png)

**Comment by Skrypt** [comment]
That's because it tries to get the .css from a https endpoint while you are navigating on a http url. Your Chrome browser needs to allow https on localhost "I think".

```
chrome://flags/#allow-insecure-localhost
```

Click enable.

**Comment by lampersky** [comment]
@Skrypt it tries from **https** endpoint, please note there is a padlock icon next to the URL, which means connection is secure:
![image](https://user-images.githubusercontent.com/6403130/124642682-67057580-de90-11eb-8d1d-d2021ee36825.png)
other than that, this happens very rare, as you can see on attached video, most of the time styles are loaded

**Comment by Skrypt** [comment]
What I don't understand is that it tries to resolve it from https while you request it from http.

**Comment by Skrypt** [comment]
Ok, my mistake I thought I saw you trying to navigate on http and that it was trying to resolve the resource on https.

**Comment by Skrypt** [comment]
Can you a screenshot of your content request header?

**Comment by Skrypt** [comment]
Here is what I get from localhost in Chrome : 

![image](https://user-images.githubusercontent.com/3228637/124653106-e41df400-de6a-11eb-96cc-f31cf847e270.png)

**Comment by lampersky** [comment]
@Skrypt please check "Disable cache" because you are getting response from browser memory cache.

![image](https://user-images.githubusercontent.com/6403130/124655554-46ddb280-dea0-11eb-8ee1-99f04621b301.png)

**Comment by Skrypt** [comment]
I also disabled the cache and I can't repro.

**Comment by lampersky** [comment]
@Skrypt it looks like it's not OC issue, I've never seen it in PROD env, so it seems to be VS related issue, I've just upgraded to 16.10.4 and can't repro so far

https://stackoverflow.com/a/67934980
