### ISSUE TITLE
[Solution included] Unable to add the EntityFramework Core migration

### ISSUE THREAD

**Issue by NickMaev** [OrchardCMS/OrchardCore#9882]
### Describe the bug
When I tried to add initial Entity Framework Core migration it couldn't create the database context.

### To Reproduce
Steps to reproduce the behaviour:
1. Create a solution with name `Test`.
2. Create the web application project in the solution with name `WebApp` from the latest `dev` branch using the following commands:
```cmd
dotnet new -i "OrchardCore.ProjectTemplates::1.0.0-rc2-*" --nuget-source https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json
```
```cmd
dotnet new occms
```
3. Create the .NET Core 5 library with name `Core`;
4. Add EntityFramework Core packages to both projects.
5. Create the EF Core database context `ApplicationDbContext` in the `Core` project and one entity type.
6. Try to create the initial migration. Run the following command in the solution's directory: 
```cmd
dotnet ef migrations add Initial -c ApplicationDbContext -s .\WebApp -v -p .\Core
```
7. Get the error:
```
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

### Expected behavior
Migration will be created successfully.

### Screenshots
![image](https://user-images.githubusercontent.com/13121346/125075965-f5177100-e0c7-11eb-8756-6a4f4d673c77.png)

### Solution
The problem was in the `Program.cs`. I renamed the `BuildHost` static method to `CreateHostBuilder` and changed the return type to `IHostBuilder`.

Before:
`Program.cs`
```csharp
    public class Program
    {
        public static Task Main(string[] args)
            => BuildHost(args).RunAsync();

        public static IHost BuildHost(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging => logging.ClearProviders())
                .ConfigureWebHostDefaults(webBuilder => webBuilder
                    .UseStartup<Startup>()
                    .UseNLogWeb())
                .Build()
            ;
    }
```
After:
`Program.cs`
```csharp
    public class Program
    {
        public static Task Main(string[] args)
            => CreateHostBuilder(args).Build().RunAsync();

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging => logging.ClearProviders())
                .ConfigureWebHostDefaults(webBuilder => webBuilder
                    .UseStartup<Startup>()
                    .UseNLogWeb())
            ;
    }
```

**Comment by ns8482e** [comment]
Have you tried with latest dev templates? I guess rc2 templates are on based on .net core 3.1 and not .net 5

**Comment by NickMaev** [comment]
> Have you tried with latest dev templates? I guess rc2 templates are based on .net core 3.1 and not .net 5

Orchard Core `dev` branch contains old templates:

![image](https://user-images.githubusercontent.com/13121346/125079597-7f61d400-e0cc-11eb-8d52-6c0602d3c169.png)
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Cms.Web/Program.cs

**Comment by ns8482e** [comment]
Looks like templates needs update for EF as  is looking from `CreateHostBuilder` method

**Comment by ns8482e** [comment]
The other solution that i am using in my 3.1 project is to create design time factory as below.
```cs
public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            optionsBuilder.UseSqlServer("******");

            return new ApplicationDbContext(optionsBuilder.Options);
        }
    }
```

**Comment by NickMaev** [comment]
> The other solution that i am using in my 3.1 project is to create design time factory as below.
> 
> ```cs
> public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
>     {
>         public ApplicationDbContext CreateDbContext(string[] args)
>         {
>             var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
>             optionsBuilder.UseSqlServer("******");
> 
>             return new ApplicationDbContext(optionsBuilder.Options);
>         }
>     }
> ```

Custom Design time factory has a lot of disadvantages such as:
- you can't resolve DI there;
- you can't access the environment variables, services, configurations of your project;
- workarounds to fix the sharing of configurations with startup assembly looks like dirty hacks;
- etc.

**Comment by ns8482e** [comment]
Agree, this only helps you if you are not using DI to configure your Context options

**Comment by NickMaev** [comment]
> Agree, this only helps you if you are not using DI to configure your Context options

... and you can't share your connection string from the `appsettings.json`

**Comment by ns8482e** [comment]
For my specific use case,  for connection strings, I use command line with arguments and manage my uid/pwd in secret manager.

**Comment by deanmarcussen** [comment]
Is the solution here to update the templates to use `CreateHostBuilder` ?

**Comment by ns8482e** [comment]
@deanmarcussen Sure! template can be updated for EF  

Btw, It's unrelated to OrchardCore CMS's connection string as OC's connection string is stored per Tenant under App_Data

**Comment by NickMaev** [comment]
> @deanmarcussen Sure! template can be updated for EF
> 
> Btw, It's unrelated to OrchardCore CMS's connection string as OC's connection string is stored per Tenant under App_Data

It would be great to add some examples how to init the EC Core for tenants in the right way. 😉

**Comment by ns8482e** [comment]
@NickMaev  OC is not using EF.  Also each tenant can have it's own `yessql.db`

**Comment by NickMaev** [comment]
> @NickMaev OC is not using EF. Also each tenant can have it's own `yessql.db`

I know it. But EF Core is the most popular ORM.

**Comment by Skrypt** [comment]
Dapper is quite popular too and you can use it with YesSQL.

**Comment by ns8482e** [comment]
@Skrypt @deanmarcussen I guess we can update the template to have `CreateHostBuilder` to align with latest ASP.NET Web application template.

@NickMaev this will help EF to read connection string from `appsettings`,  However,be aware that  change you are proposing is not related to OC's database connection string and It will not connect to any tenant specific `yessql.db`  as OC's connection string is stored under `App_Data`
