### ISSUE TITLE
Sample can not  run normally

### ISSUE THREAD

**Issue by leisurelyclouds** [OrchardCMS/OrchardCore#989]
When I ran the OrchardCore.Mvc.Web project on commit f099a23 whitch created at the master branch with Visual Studio, an error happened and showed a blank page, however, it could run normally when I used dotnet run command.

**Comment by xiaoyc** [comment]
+1

**Comment by xiaoyc** [comment]
Actually ,it throw "A tenant could not be started: {settings.Name}" expcetion.

**Comment by leisurelyclouds** [comment]
same issue #916
