### ISSUE TITLE
Enabling the [Auto Setup] module will automatically change the site language, and you can never change it back through the interface

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#9890]
Enabling the [Auto Setup] module will automatically change the site language, and you can never change it back through the interface

![autoSetupError](https://user-images.githubusercontent.com/15613121/125182328-c9b79200-e23f-11eb-9d5e-085a7b7c8157.gif)

**Comment by jtkech** [comment]
@hyzx86 

The Auto Setup module is not intended to be enabled on an already setup site

Like the Setup module it is only used for the setup experience, we already use it by using this in the app startup

    services.AddOrchardCms().AddSetupFeatures("OrchardCore.AutoSetup");

We already have the following in the view to not show the enable button for the Setup module

    var showEnable = Model.IsAllowed(feature.Descriptor) && !missingDependencies.Any() &&
        feature.Descriptor.Id != "OrchardCore.Setup";

We should add the same for the Auto Setup module, will do a PR tomorrow

**Comment by hyzx86** [comment]
got it. Thank you

**Comment by jtkech** [comment]
Okay cool then

**Comment by jtkech** [comment]
Reopen it, will do a PR that will close it
