### ISSUE TITLE
Recipes is empty on Setup page 

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#9891]
![微信截图_20210711121553](https://user-images.githubusercontent.com/15613121/125182578-c3c2b080-e241-11eb-8810-dd995000e90e.png)

**Comment by hishamco** [comment]
Which version you are using?

**Comment by hyzx86** [comment]
@hishamco It has been fixed, maybe because I enabled`Auto Setup`, I deleted the app_data folder and obj folder and restored it
