### ISSUE TITLE
implement interface for logoff similar to ILoginFormEvent 

### ISSUE THREAD

**Issue by MRSheikh** [OrchardCMS/OrchardCore#9895]
I want to clear all TempData and other variables used in my module after the logoff post method of OrchardCore .

is there any way to implement some code for logoff , like `ILoginFormEvent `?

**Comment by deanmarcussen** [comment]
You probably want to use the `CookieAuthenticationOptions` events `OnSigningOut` for this.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationevents.onsigningout?view=aspnetcore-5.0#Microsoft_AspNetCore_Authentication_Cookies_CookieAuthenticationEvents_OnSigningOut

I don't think we need another event as `Identity` already provides these,

**Comment by MRSheikh** [comment]
> 
> 
> You probably want to use the `CookieAuthenticationOptions` events `OnSigningOut` for this.
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationevents.onsigningout?view=aspnetcore-5.0#Microsoft_AspNetCore_Authentication_Cookies_CookieAuthenticationEvents_OnSigningOut
> 
> I don't think we need another event as `Identity` already provides these,

oh yes. that's all I need. 
thanks.
