### ISSUE TITLE
How to set appsettings.Production.json to configure different connectionstring when deploying

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#9905]
Following the configuration docs: 
https://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/index.html

 it seems that its not possible at tenant level (in App_data/Sites/{tenant}) to have an appsettings.Production.json environment to configure a different connection string when deploying to production.

![image](https://user-images.githubusercontent.com/1516981/125415989-c06cb814-2f9d-4e9d-8ddb-ee1276dd212b.png)

What is the recommended way to set the connection string  for production environment ?

It seems that   **Database Shells Configuration** is the way to go but how would one differentiate the connection string per tenant

https://docs.orchardcore.net/en/dev/docs/reference/core/Shells/index.html

**Comment by giannik** [comment]
In my appsettings.json I added the following :

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "OrchardCore": {
     "ConnectionString": "Server=localhost\\SQLEXPRESS02;Database=IntelliDev;Trusted_Connection=True",
    "DatabaseProvider": "SqlConnection",
    "TablePrefix": "Default",
    "Default": {
      "Identifier": "463tp8mfy3pbrrgs4qp7x9c54a",
      "State": "Running",
      "ConnectionString": "Server=localhost\\SQLEXPRESS02;Database=IntelliDev;Trusted_Connection=True",
      "DatabaseProvider": "SqlConnection",
      "TablePrefix": "Default"
    },
    "OrchardCore_Shells_Database": {
      "DatabaseProvider": "SqlConnection",
      "ConnectionString": "Server=localhost\\SQLEXPRESS02;Database=IntelliDev;Trusted_Connection=True",
      "TablePrefix": "",
      "MigrateFromFiles": true
    }
  }
}
```

and in host startup added :

```
   services.AddOrchardCms()
           .AddDatabaseShellsConfiguration() 
           .AddSetupFeatures("OrchardCore.AutoSetup");
```

but now on startup its showing the setup screen , ignoring that I already have the default tenant setup.

I deliberately added the Default {} section for the default tenant hoping it would pick it up and see that its running but no luck.

Am I doing something wrong ?

**Comment by hyzx86** [comment]
Why are there two identical database connection configurations here, And the table prefix is also the same

```
  "OrchardCore": {
     "ConnectionString": "Server=localhost\\SQLEXPRESS02;Database=IntelliDev;Trusted_Connection=True",
    "DatabaseProvider": "SqlConnection",
    "TablePrefix": "Default",
    "Default": {
      "Identifier": "463tp8mfy3pbrrgs4qp7x9c54a",
      "State": "Running",
      "ConnectionString": "Server=localhost\\SQLEXPRESS02;Database=IntelliDev;Trusted_Connection=True",
      "DatabaseProvider": "SqlConnection",
      "TablePrefix": "Default"
    },
```

**Comment by giannik** [comment]
@hyzx86 
I was experimenting with various settings to get it to work.
i also found similar issue #8387 where @Piedone  tried it and mentioned it worked.

**Comment by Piedone** [comment]
Such tenant-specific config in the root appsettings file (or in any configuration provider) works currently. Please reopen if still applicable.
