### ISSUE TITLE
Pluralization doco

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#9917]
### Describe the bug
I'm trying to understand the doco for pluralization and I'm unclear how the T.Plural method is supposed to be used.

[Pluralization](https://docs.orchardcore.net/en/dev/docs/reference/modules/Localize/index.html#usage)

![image](https://user-images.githubusercontent.com/68876423/125659507-1d90d6eb-1272-44c5-8249-8e789c2cbe86.png)

In this example, I believe that "1 book" is the singular form and "{0} books" is the plural form. Which form is used is decided based on the count parameter. Usually, this means that if `count == 1` the singular form is used, otherwise the plural form is used.

Now, let's say I want to run my OC in French.

[Wikipedia link for French rules](https://en.wikipedia.org/wiki/Grammatical_number#French)

![image](https://user-images.githubusercontent.com/68876423/125659805-557ed794-c1fb-46ac-9b5c-491183b07ef4.png)

If French treats zero as singular, then the rule changes such that that if `count == 0 || count == 1` the singular form is used, otherwise the plural form is used. However, the doco places a hardcoded "1" in the singular form. So doesn't that mean that if `count == 0`, the translated form of "1 book" is going to be displayed? And if the translator kept the hardcoded "1" the wrong number will be displayed.

I guess my question is, should the doco example actually be this?
```
T.Plural(count, "{0} book", "{0} books")
```

Maybe the doco is assuming the translator will replace the hardcoded "1" with "{0}"?

**Comment by Skrypt** [comment]
Here your count will be applied on both singular and plural form that's why.

**Comment by Skrypt** [comment]
I may add that I understand your suggestion but it would not be appropriate for example that if there is "no book" that the applications returns " book" with a leading space either.

**Comment by rjpowers10** [comment]
I'm not sure I understand your example. Having explicit handing for the count being greater than 0 seems like the opposite of what I'm supposed to do. Isn't the purpose of `T.Plural` to handle the culture-specific rules so that programmers are not spreading faulty assumptions throughout the code?

It looks like [DefaultPluralRuleProvider](https://github.com/OrchardCMS/OrchardCore/blob/20d5554f78794d85acdb8b9e61a365f12b514b7b/src/OrchardCore/OrchardCore.Localization.Core/DefaultPluralRuleProvider.cs#L20) adds the rule for FR that I expect: `n > 1 ? 1 : 0`. And the EN rule is `n != 1 ? 1 : 0`.

So again, if my template uses the following I think everything works out.

```
T.Plural(count, "{0} book", "{0} books")
```

Here's what I got in my tests (I didn't actually provide a translation for FR, but notice that the rule did change for 0).

|Culture|Count|Result|
|---|---|---|
|EN|0|0 books|
|EN|1|1 book|
|EN|2|2 books|
|FR|0|0 book|
|FR|1|1 book|
|FR|2|2 books|

>I may add that I understand your suggestion but it would not be appropriate for example that if there is "no book" that the applications returns " book" with a leading space either.

I'm not sure I understand this, either. When would " book" with a leading space be returned?

Thanks for taking the time to reply.

**Comment by Skrypt** [comment]
I see there is probably an issue there. @sebastienros

**Comment by hishamco** [comment]
@rjpowers10 if you are complaing about the 1 in `T.Plural(count, "1 book", "{0} books")` you are right. Arabic for instance is more complicated ;)

Similar to what you said in case of 0 will `0 book` not `1 book`

**Comment by rjpowers10** [comment]
Yes, it is specifically the "1". It seems to me like it should be "{0}".

Current doco example:
```
T.Plural(count, "1 book", "{0} books")
```

Proposed doco example:
```
T.Plural(count, "{0} book", "{0} books")
```

**Comment by hishamco** [comment]
Wait a minute, the "1 book" is a singular message Id, not a value

**Comment by rjpowers10** [comment]
> Wait a minute, the "1 book" is a singular message Id, not a value

Correct, "1 book" is the message ID. But how is a translator supposed to translate it? If they see a "1" in the untranslated string I think they are likely to keep it in the translated string. But that means that the singular form is only useable when `count == 1`. That works for English, but other languages use the singular form for other values of `count`.

Suppose "1 book" is translated as "1 livre" and that `count == 0`. That means that in this example
```
T.Plural(count, "1 book", "{0} books")
```
the string "1 livre" is returned. But I think the correct string to return is "0 livre".

But if "{0} book" is translated as "{0} livre", the example would work for both `count == 0` and `count ==1`, which both should use the singular form in French.

Keep in mind I'm not an expert in localization and I only know English. It's entirely possibly I'm missing something here. But it is important for my application to properly support French, so I am trying to figure out what the best practices are.

**Comment by rjpowers10** [comment]
To be clear, my complaint is only about the example in the doco. I think the code is behaving correctly. My complaint is that "1 book" is misleading to the translator, which can result in incorrect behavior for languages that use the singular form for counts other than 1.

Technically, the translator could translate "1 book" as "{0} livre" and everything would work correctly. But I think a translator is unlikely to have that foresight. I think it is more likely that "1 book" gets translated as "1 livre", and that's where you can run into problems.

**Comment by hishamco** [comment]
Perhaps the issue with the languages that treat zero as plural
