### ISSUE TITLE
Orchard can't discovery pages and controllers when IActionDescriptorCollectionProvider implementation is added to the host application

### ISSUE THREAD

**Issue by davidfowl** [OrchardCMS/OrchardCore#9921]
### Describe the bug
Adding default MVC services to the shell application results in controllers and pages not being found:

### To Reproduce
1. Make a new project targeting .NET 5 (could be any version)
2. Use the following code:

```C#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Primitives;

Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(webbuilder =>
{
    webbuilder.Configure(app =>
    {
        app.UseOrchardCore();
    });
})
.ConfigureServices(services =>
{
    services.AddSingleton<IActionDescriptorCollectionProvider, Collection>();
    services.AddOrchardCms();
})
.Build()
.Run();

class Collection : ActionDescriptorCollectionProvider
{
    public override ActionDescriptorCollection ActionDescriptors { get; } = new(new ActionDescriptor[0], 0);

    public override IChangeToken GetChangeToken()
    {
        return NullChangeToken.Singleton;
    }
}
```
3. Run the main page
4. Get a 404

### Expected behavior
The modules should still be able to discover their controllers and pages regardless of what the shell application does.

This was discovered when we [added more default services](https://github.com/dotnet/aspnetcore/commit/2af293dc72625b865fa7fcad5aeb510df46386bd) to the main web host. Even though the change was [reverted](https://github.com/dotnet/aspnetcore/pull/34257), it can still break orchard if this method call is made or if a custom implementation is added.

Scanning the orchard code it look as though [this method](https://github.com/OrchardCMS/OrchardCore/blob/1ec2e9898ff37e49d4224732c8a3e0acb5ed2fa6/src/OrchardCore/OrchardCore/Shell/Builders/Extensions/ServiceProviderExtensions.cs#L15) needs to special case descriptors that can affect the tenant container. I don't have any expertise here though this was just me debugging to figure out why orchard broke on .NET 6.

**Comment by jtkech** [comment]
@davidfowl Thanks a lot, i will work on it asap.
