### ISSUE TITLE
Check SubResourceIntegrity

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#9941]
In order to avoid incorrect SRIs, we should find a way to check the resources that have cdn versions declared.

Ex:
https://github.com/Dotnet-Boxed/Framework/blob/1fd6ecc5966d820166ca633bc1cefa91bbcb4369/Source/Boxed.AspNetCore.TagHelpers/SubresourceIntegrityTagHelper.cs#L243

**Comment by deanmarcussen** [comment]
This should be as simple as having a test, or perhaps a console app, which discovers all registered resource manifests, checks if they have an integrity set, reads the file from the `src` and `debug-src` property, and compares it against the calculated one (from the code ag linked above).

Additionally it could output the correct one.

**Comment by hishamco** [comment]
I will try to add a unit test for this one

**Comment by hishamco** [comment]
I think we can calculate the SRI instead of entering them manually during the resource manifest registration

**Comment by hishamco** [comment]
There's a related PR ready to merge, just waiting for Zoltan approval
