### ISSUE TITLE
When rebuilding from source I get errors restoring nuget packages

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#996]
Anyone else seeing this?

![image](https://user-images.githubusercontent.com/619530/30368917-94043ea6-986a-11e7-81d5-3afc9bec98f3.png)

**Comment by infofromca** [comment]
it only happened when I loaded the sln.
![load-err](https://user-images.githubusercontent.com/297675/30380910-dc006e0c-9868-11e7-9ed6-4c9ceebc9409.png)

but rebuild succeeded

**Comment by sebastienros** [comment]
Works for me from a clean repos on master. Buids are also fine from appveyor and travis (osx and linux).

Try a `git clean -xdf`

**Comment by agriffard** [comment]
I also have these errors when I open the sln.
