### ISSUE TITLE
the release 1.0 can not be isntall since Orchardcore.Rules was missed

### ISSUE THREAD

**Issue by hylinux** [OrchardCMS/OrchardCore#9969]
### To Reproduce
1.  Create a empty web application by visual studio
2. install the pakcage: OrchardCore.Application.Cms.Targets
3. it will failed
4. See error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package OrchardCore.Rules. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	MySecondlyCMS	C:\Users\hongw\source\repos\MySecondlyCMS\MySecondlyCMS\MySecondlyCMS.csproj	1	
![image](https://user-images.githubusercontent.com/145199/126776571-01d28761-d59f-4658-b38e-176ef703c209.png)

**Comment by Skrypt** [comment]
It's there : https://www.nuget.org/packages/OrchardCore.Rules/

**Comment by deanmarcussen** [comment]
Yes, this was reported on gitter as well. I couldn't reproduce any issue with Visual Studio, or dotnet add

What version of Visual Studio are you using @hylinux ? you will need to be on the latest

I did notice that the package is referenced twice in the targets package, so we need to fix that, but I'm not sure it's related.

**Comment by Skrypt** [comment]
I can repro something similar when using a Nuget packages solution and using latest build 1.0.0-rc2-16385
