### ISSUE TITLE
Could not install nuget package:  Unable to find package OrchardCore.Rules. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#9974]
### To Reproduce
1.install `OrchardCore.Application.Cms.Targets` nuget package, package console throws `Unable to find package OrchardCore.Rules. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org`.

2.Or direct add PackageReference  to .csproj, then build:
`
    <ItemGroup>
      <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0" />
    </ItemGroup>
`

### Screenshots
![image](https://user-images.githubusercontent.com/3222379/126886772-8995b2ed-97ca-47c9-ba57-77bf5a652e7f.png)

**Comment by Skrypt** [comment]
Repeating myself but here it is : https://www.nuget.org/packages/OrchardCore.Rules/
So, not sure what the issue exactly is since I've been able to successfully build this in a Nuget Package solution.
Maybe this is a Nuget cache issue. Try cleaning the project build and Nuget cache.

**Comment by deanmarcussen** [comment]
The error `Microsoft Visual Studio Offline Packages` suggests that you have a cached package source, and the nuget server may have been set as offline.

Try the solution here.

https://stackoverflow.com/a/58945739/5836151

Or make sure you're updated to the latest visual studio, and dotnet 5, if not please report your version of visual studio and dotnet

**Comment by PimHwang** [comment]
I got this problem too after I tried everything include reinstalling the brand-new OS whatever Windows or Linux，I have no choice but decide to build/pack as the local packages, then this problem solved! 
so it must be something wrong somewhere.

**Comment by hyzx86** [comment]
Tools
Nuget Package Manager
General
Click button "Clear All Nuget Cache(s)
Package Resources and click "Update"
Woolah! Error gone...

**Comment by RockNHawk** [comment]
> Tools Nuget Package Manager General Click button "Clear All Nuget Cache(s) Package Resources and click "Update" Woolah! Error gone...

Wait for some days or user another computer....
