### ISSUE TITLE
ContentPicker - not working in widget before save

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#9986]
ContentPicker field is not working in widgets when there is no other contentpicker on page - it is not loading data. After saving, it loads correctly. 

I guess it will be a problem with missing javascripts on page load.

**Comment by Piedone** [comment]
Can't reproduce; the Content Picker Field works when adding a widget to a Layer as well as to Flow Part (Page) without any other Content Picker being present.
