### ISSUE TITLE
error page from "OrchardCore.Diagnostics" module isn't presented when [ValidateAntiForgeryToken] attribute is used and validation failed

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#9987]
### Describe the bug
Sometimes, when my "**orchantiforgery_**" cookie expires, and when login page is still opened in browser, I can't log in, because of **[AntiforgeryValidationException](https://github.com/dotnet/aspnetcore/blob/main/src/Antiforgery/src/Internal/DefaultAntiforgery.cs)** which is expected behavior, but instead of seeing error page from 'OrchardCore.Diagnostics' I see default one.

### You can reproduce the issue by removing "**orchantiforgery_**" cookie, or by manipulating with html code.
1. Make sure 'OrchardCore.Diagnostics' module is enabled,
2. Go to 'https://try.orchardcore.net/Login',
3. Inspect page and change value of '__RequestVerificationToken' input,
4. Click on 'Log in',
5. See default 400 error page.
![image](https://user-images.githubusercontent.com/6403130/127175417-abf4d68c-f20a-4c69-b218-6e7403632915.png)

### Expected behavior
This error page should be presented to the user:
![image](https://user-images.githubusercontent.com/6403130/127174996-7c5d6750-0d0d-48a8-9b70-be2359477b9e.png)

**Comment by sebastienros** [comment]
Maybe a middleware order, specific to antiforgery token.

**Comment by lampersky** [comment]
this issue is related to this [change](https://github.com/OrchardCMS/OrchardCore/pull/3993)
![image](https://user-images.githubusercontent.com/6403130/127631388-ee1256da-dd1a-4d3e-b2cc-8b2c8da59667.png)

**Comment by hishamco** [comment]
@deanmarcussen seems this broken after #3993

**Comment by sebastienros** [comment]
@lampersky any suggestion on how to fix it? or if the order is the issue?

**Comment by lampersky** [comment]
@sebastienros when you are applying filter globally it means that every controller will be affected, even our **DiagnosticsController** and that's why we are observing issue with **app.UseStatusCodePagesWithReExecute("/Error/{0}")**

The simplest way to fix this issue is just by adding **[IgnoreAntiforgeryToken]** attribute to **DiagnosticsController**.
This will prevent antiforgery token validation for re executed requests.

I've just prepared [PR](https://github.com/OrchardCMS/OrchardCore/pull/10206)
