### ISSUE TITLE
For version 1.0 - Symbols are not published to nuget.org

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#9990]
### Describe the bug
For version 1.0 - Symbols are not published to nuget.org

### Expected behavior
Symbol to be published to nuget.org for  V 1.0

**Comment by sebastienros** [comment]
We need to add these tags to the csproj files

```
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <DebugType>portable</DebugType>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

**Comment by sebastienros** [comment]
We could try to push the packages with the same version an hopefully get only the symbols updated on nuget. Otherwise we'd do it during next release.

**Comment by ns8482e** [comment]
It's already there in `OrchardCore.Commons.props` finished in PR #7237

**Comment by rjpowers10** [comment]
I don't have anything to add other than it would be great to have this 👍

**Comment by sebastienros** [comment]
We are about to ship 1.1, target date is Tuesday, worth waiting now.
