### ISSUE TITLE
Will CSS isolation work out of the box in .NET 6?

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/OrchardCore#9993]
### Is your feature request related to a problem? Please describe.
https://www.mikesdotnetting.com/article/355/css-isolation-in-razor-pages
Will it work out of the box if targeting .NET 6?

### Describe the solution you'd like
Adding CSS file to a Razor page enables CSS isolation

**Comment by Piedone** [comment]
Hmm, while I guess this will just work with Razor Pages (i.e. decoupled CMS) in the traditional CMS approach I'm not sure if you'd want to use it. The point there is to utilize the static resource management of Orchard, including dependency management and cache busting. Perhaps we could integrate these somehow.

**Comment by xperiandri** [comment]
But at the end it composes into a single CSS file

**Comment by ns8482e** [comment]
Exclude all *.razor.css from assets and include in <None>

**Comment by ns8482e** [comment]
> Exclude all *.razor.css from assets and include in `<None>`

e.g.
```
<PropertyGroup>
<ModuleDefaultAssetExcludes>$(ModuleDefaultAssetExcludes);**/*.razor.css</ModuleDefaultAssetExcludes>
</PropertyGroup>

<ItemGroup>
  <None Include="**/*.razor.css" />
</ItemGroup>
```

**Comment by sebastienros** [comment]
@jtkech might be able to understand how it works and what needs to be done so it also adds the bundles as embedded, but he's a busy person.

**Comment by ns8482e** [comment]
@xperiandri  with above changes  - it will create bundle that gets added to `staticwebassets` folder in nuget

you can include it in pages as 
`<link href="~/[OCModule].bundle.scp.css" rel="stylesheet">`

**Comment by jtkech** [comment]
@sebastienros Yes, would need to see how things are generated and where (e.g. bundle files), and how there are referenced in dev / prod modes and in a published contex or not.

In the meantime what @ns8482e suggested looks good. Maybe only use the PropertyGroup, e.g. for `*.cshtml.css` files I think that the following also works as `ModuleAssetExcludes` are then included in the `None` items collection.

    <PropertyGroup>
      <ModuleAssetExcludes>$(ModuleAssetExcludes);**/*.cshtml.css</ModuleAssetExcludes>
      <ModuleDefaultAssetExcludes>$(ModuleDefaultAssetExcludes);**/*.cshtml.css</ModuleDefaultAssetExcludes>
    </PropertyGroup>

**Comment by xperiandri** [comment]
Does current 1.2-preview version already target .NET 6 and we can try CSS isolation again?

**Comment by xperiandri** [comment]
So does it already work in 1.2 release?

**Comment by deanmarcussen** [comment]
Did you try it? That's a great way to find out

**Comment by Piedone** [comment]
Closing due to no reply from the author.
